### ISSUE TITLE
Support serviceaccounts

### ISSUE THREAD

**Issue by runseb** [kubernetes/minikube#10]
Without them DNS addon won't work (and lots of other things as well)
It is not an issue if we keep relying on weave in localkube.

**Comment by luxas** [comment]
ServiceAccount should be present.
Weave should not be a dep, we'll manage without it

**Comment by dlorenc** [comment]
This is how hyperkube sets up service accounts:
https://github.com/kubernetes/kubernetes/blob/master/cluster/images/hyperkube/setup-files.sh

They generate tokens using urandom and pass them into the api server via --token-auth-file

**Comment by luxas** [comment]
Yes, we're using `easyrsa` for certificate creation
However, when we have go, we should do something like this: https://github.com/redspread/localkube/pull/50

**Comment by dlorenc** [comment]
This should be working now with #48.
