### ISSUE TITLE
Template Change: the PR template to not have 'fixes #issuenumber' suggestion

### ISSUE THREAD

**Issue by amarts** [kubernetes/minikube#10000]
** What happened **

1. I picked up an issue, and committed a fix, and opened a PR. (#9999)
2. While opening the PR, it recommended me to have 'Fixes: #issues number' in commit to have it reviewed faster.
3. As a practice in other practices, I had the fixes: as part of commit message.
4. After opening the PR, it got tagged with `<invalid-commit-message>`

** What is ideal **

1. Looks like having mentions or issue numbers in commit message is not recommended now as per policy, so change the PR template file to clearly talk about it, so it would remind people again.

**Comment by Jorropo** [comment]
https://github.com/kubernetes/minikube/blame/master/.github/pull_request_template.md#L4

This seems pretty clear to me that it should be in the description not the title (end of line 4).
As in #9998 (I did put in the title at first by reflex) :)

**Comment by amarts** [comment]
@Jorropo thanks. I agree, that it says the issue number in 'description' :-) 

:+1:

**Comment by bl-ue** [comment]
Issue 10,000! :smile::smile::smile: @amarts You lucked out!
