### ISSUE TITLE
Include registry mirror if specified in addon template yamls

### ISSUE THREAD

**Issue by denverdino** [kubernetes/minikube#10012]
**Steps to reproduce the issue:** 

1. Create minikube with 
$ minikube start --vm=true --image-mirror-country=cn --registry-mirror=https://6udu7vtl.mirror.aliyuncs.com

2. $ minikube addons enable ingress
🔎  Verifying ingress addon...

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

The reason is in https://github.com/kubernetes/minikube/blob/master/deploy/addons/ingress/ingress-dp.yaml.tmpl

Some image from Docker Hub is also using the mirror repo

          image: {{default "jettech" .ImageRepository}}/kube-webhook-certgen:v1.3.0

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

Current logic for handle Docker Hub image seems incorrect and not leveraging --registry-mirror

Thanks a lot
</details>

**Comment by priyawadhwa** [comment]
Hey @denverdino thank you for opening this issue, it looks like a bug. We should be handling registry mirror if specified in the addon yamls.

We would do this by adding `RegistryMirror` to our options for generating the template here:

https://github.com/kubernetes/minikube/blob/92511decd0ece326701c385f1c642d11af092d16/pkg/minikube/assets/addons.go#L486

And then adding `{{.RegistryMirror}}` in the correct place in the addon template yamls themselves.

If anyone is interested in fixing this issue, please feel free to take it on by commenting /assign

**Comment by presztak** [comment]
@denverdino @priyawadhwa 

`minikube addons enable` has `registries` option, so:

`minikube addons enable ingress --registries=IngressController=https://6udu7vtl.mirror.aliyuncs.com`

won't be solution for this problem?

**Comment by denverdino** [comment]
@presztak after #12578 been merged. I can close this issue.

So, we will use the mapping file to specify the mirror of addon images for  for chinese developer.

Thanks
