### ISSUE TITLE
[UX~] Change default context and/or namespace

### ISSUE THREAD

**Issue by matanshukry** [kubernetes/minikube#10017]
1. `minikube start`
2. `cat ~/.kube/config`

**Problem:** 
I'm restarting my computer frequently at which times I need to start minikube again.
Every time I start minikube, it "refreshed" the default namespace, by doing 2 things:

1. It sets the current kubectl context to be minikube
2. It sets the minikube namespace to default

I am fine with having minikube by default, but I need a different namespace to be the default.

However it seems it's not doble with either namespace or context, since minikube overwrite both everytime it starts ?

**Comment by tstromberg** [comment]
You are in luck: someone recently added a `--namespace` flag to `minikube start`.

You may also be interested in `--keep-context`
