### ISSUE TITLE
Audit not working

### ISSUE THREAD

**Issue by kmohanram** [kubernetes/minikube#10013]
**Steps to reproduce the issue:** 

1. On a fresh install: `minikube start --extra-config=apiserver.audit-policy-file=/etc/kubernetes/addons/audit-policy.yaml --extra-config=apiserver.audit-log-path=/var/log/audit.log --driver parallels --extra-config=apiserver.authorization-mode=Node,RBAC`
2. Install hangs and finally terminates. I can ssh into minikube, and it appears that the apiserver never takes off.
3. Inspection of manifests show that the audit policy and command line options are recorded properly in the apiserver yaml. I tried the log-path=- option as seen in other minikube audit tutorials with no luck.
4. I tried the hyperkit, parallels, and docker drivers on my Mac. I also upgraded to minikube 1.16 this morning with no luck. I also tried an Ubuntu VM with VirtualBox but the command pretty much hangs at the same point and never proceeds further.

**Full output of failed command:** 

$ minikube start   --extra-config=apiserver.audit-policy-file=/etc/kubernetes/addons/audit-policy.yaml   --extra-config=apiserver.audit-log-path=/var/log/audit.log  --driver parallels   --extra-config=apiserver.authorization-mode=Node,RBAC
😄  minikube v1.16.0 on Darwin 10.15.7
✨  Using the parallels driver based on user configuration
💿  Downloading VM boot image ...
    > minikube-v1.16.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.16.0.iso: 212.62 MiB / 212.62 MiB [] 100.00% 4.17 MiB p/s 51s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.20.0 preload ...
    > preloaded-images-k8s-v8-v1....: 491.00 MiB / 491.00 MiB  100.00% 4.65 MiB
🔥  Creating parallels VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
    ▪ apiserver.audit-policy-file=/etc/kubernetes/addons/audit-policy.yaml
    ▪ apiserver.audit-log-path=/var/log/audit.log
    ▪ apiserver.authorization-mode=Node,RBAC
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...| 💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.20.0
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost minikube] and IPs [10.211.55.10 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [localhost minikube] and IPs [10.211.55.10 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in docker:
		- 'docker ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'docker logs CONTAINERID'

stderr:
💡  Suggestion: Check output of 'journalctl -xeu kubelet', try passing --extra-config=kubelet.cgroup-driver=systemd to minikube start
🍿  Related issue: https://github.com/kubernetes/minikube/issues/4172

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
$ minikube logs --problems
❌  Problems detected in kubelet:
    Dec 21 21:36:42 minikube kubelet[3069]: E1221 21:36:42.826714    3069 pod_workers.go:191] Error syncing pod 75b771284865e3884f28922a20378be8 ("kube-apiserver-minikube_kube-system(75b771284865e3884f28922a20378be8)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "back-off 1m20s restarting failed container=kube-apiserver pod=kube-apiserver-minikube_kube-system(75b771284865e3884f28922a20378be8)"
    Dec 21 21:36:49 minikube kubelet[3069]: E1221 21:36:49.823599    3069 pod_workers.go:191] Error syncing pod f8d3d61ad8d45c80ab92bcedbe7fdb7d ("kube-controller-manager-minikube_kube-system(f8d3d61ad8d45c80ab92bcedbe7fdb7d)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 1m20s restarting failed container=kube-controller-manager pod=kube-controller-manager-minikube_kube-system(f8d3d61ad8d45c80ab92bcedbe7fdb7d)"
    Dec 21 21:36:54 minikube kubelet[3069]: E1221 21:36:54.830276    3069 pod_workers.go:191] Error syncing pod 75b771284865e3884f28922a20378be8 ("kube-apiserver-minikube_kube-system(75b771284865e3884f28922a20378be8)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "back-off 1m20s restarting failed container=kube-apiserver pod=kube-apiserver-minikube_kube-system(75b771284865e3884f28922a20378be8)"
    Dec 21 21:37:04 minikube kubelet[3069]: E1221 21:37:04.826072    3069 pod_workers.go:191] Error syncing pod f8d3d61ad8d45c80ab92bcedbe7fdb7d ("kube-controller-manager-minikube_kube-system(f8d3d61ad8d45c80ab92bcedbe7fdb7d)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 1m20s restarting failed container=kube-controller-manager pod=kube-controller-manager-minikube_kube-system(f8d3d61ad8d45c80ab92bcedbe7fdb7d)"
    Dec 21 21:37:08 minikube kubelet[3069]: E1221 21:37:08.309216    3069 pod_workers.go:191] Error syncing pod 75b771284865e3884f28922a20378be8 ("kube-apiserver-minikube_kube-system(75b771284865e3884f28922a20378be8)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "back-off 2m40s restarting failed container=kube-apiserver pod=kube-apiserver-minikube_kube-system(75b771284865e3884f28922a20378be8)"
    Dec 21 21:37:10 minikube kubelet[3069]: E1221 21:37:10.690606    3069 pod_workers.go:191] Error syncing pod 75b771284865e3884f28922a20378be8 ("kube-apiserver-minikube_kube-system(75b771284865e3884f28922a20378be8)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "back-off 2m40s restarting failed container=kube-apiserver pod=kube-apiserver-minikube_kube-system(75b771284865e3884f28922a20378be8)"

</details>

**Comment by priyawadhwa** [comment]
Hey @kmohanram thanks for opening this issue. I have a couple questions:

1. Does a fresh`minikube start` successfully run, without any additional apiserver configuration? If it does, that will help us narrow this down to the audit not working
2. If `minikube start` alone fails, does `minikube start --force-systemd` pass?

**Comment by kmohanram** [comment]
Yes, a fresh `minikube start` works perfectly with no issues that I have encountered so far. It fails on a fresh start when run with the additional apiserver configuration (as seen in the command line invocation when I filed the issue). I did ssh into minikube to grab the kube-apiserver.yaml file and here the result of a diff between the default and audit configs:

```
$ diff ~/kube-apiserver.yaml  ~/kube-apiserver.default.yaml 
18,19d17
<     - --audit-log-path=/var/log/audit.log
<     - --audit-policy-file=/etc/kubernetes/addons/audit-policy.yaml
```
An additional thought: I am not explicitly mounting any volumes to create the audit.log file since I was unable to determine how to go about this. However, I would suspect that the install should proceed smoothly even without this file and that if anything, logging should fail on a successful start. I did ssh into minikube to create this file explicitly, but a stop and start of minikube did not get me any further and the install hung around before terminating as before.

**Comment by kmohanram** [comment]
hello, would it be possible to look into this and prioritize as appropriate? i see multiple attempts and workarounds listed/documented here and elsewhere to enable auditing, but unless i am mistaken, auditing does not function correctly as of the latest release. thank you.

**Comment by medyagh** [comment]
@kmohanram i wonder would following this Doc help ?

https://minikube.sigs.k8s.io/docs/tutorials/audit-policy/

**Comment by medyagh** [comment]
@kmohanram I haven't heard from you, did that doc help ?

**Comment by medyagh** [comment]
I follow the docs on our website 
https://minikube.sigs.k8s.io/docs/tutorials/audit-policy/

and it works for me, if u dont mind I will close this issue and if u still have this  please reopen

```
 2152  [2021-03-10 11:18:22 -0800] minikube stop
 2153  [2021-03-10 11:18:32 -0800] minikube start --extra-config=apiserver.audit-policy-file=/etc/kubernetes/addons/audit-policy.yaml --extra-config=apiserver.audit-log-path=/var/log/audit.log --driver parallels --extra-config=apiserver.authorization-mode=Node,RBAC
 2154  [2021-03-10 11:19:10 -0800] cat <<EOF > ~/.minikube/files/etc/ssl/certs/audit-policy.yaml
 2155  [2021-03-10 11:19:32 -0800] mkdir -p ~/.minikube/files/etc/ssl/certs
 2156  [2021-03-10 11:20:27 -0800] cat <<EOF > ~/.minikube/files/etc/ssl/certs/audit-policy.yaml
 2157  [2021-03-10 11:20:32 -0800] minikube start   --extra-config=apiserver.audit-policy-file=/etc/ssl/certs/audit-policy.yaml   --extra-config=apiserver.audit-log-path=-
 2158  [2021-03-10 11:21:03 -0800] kubectl logs kube-apiserver-minikube -n kube-system | grep audit.k8s.io/v1

```

**Comment by kmohanram** [comment]
IIrc, that was the first set of instructions that I followed. However, I
will follow these instructions again and report back to you in the next 1-2
days. Thank you.
