### ISSUE TITLE
Run conformance test for k8s 1.20

### ISSUE THREAD

**Issue by azhao155** [kubernetes/minikube#10015]
We have already run conformance test for V1.19, Need to run the same tests for multi nodes for v1.20

**Comment by azhao155** [comment]
@medyagh

**Comment by tstromberg** [comment]
Any volunteers for taking this on and uploading the results?

**Comment by azhao155** [comment]
yeah, will send out pr soon

**Comment by azhao155** [comment]
Sent the pr: https://github.com/cncf/k8s-conformance/pull/1277. Waiting for review and merge

**Comment by azhao155** [comment]
@medyagh @tstromberg

**Comment by azhao155** [comment]
It' merged. please close this one @medyagh

**Comment by medyagh** [comment]
thanks @azhao155
