### ISSUE TITLE
fix minikube installation using gcloud snap

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10020]
https://cloud.google.com/sdk/docs/downloads-snap

gcloud components install minikube

**Comment by afbjorklund** [comment]
I thought we deleted the minikube snap ?

**Comment by medyagh** [comment]
this one is for minikube that is is installed by gcloud 
a glcoud that is installed by snap


we found the root cause of this issue, minikube creates certs in /tmp and then we wanna do "docker cp" the certs
but "Docker" in snap does NOT have acess to same /tmp as mnikube so it can not "docker cp" the cert file...


so for snap we might need to create our temp files in minikhbe home folder
