### ISSUE TITLE
docker-env do not exit if can't restart docker

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10026]
this line should be changed to klog.Warnning
https://github.com/medyagh/minikube/blob/75cd17801287339a00efe44fbd451b4dbfadef86/cmd/minikube/cmd/docker-env.go#L191

this would be helpful for the workflows that run in a loop, and would hit the burst liimit of 5 times per miniute

**Comment by azhao155** [comment]
https://github.com/kubernetes/minikube/pull/10028

**Comment by priyawadhwa** [comment]
Hey @azhao155 thank you for taking this issue on!
