### ISSUE TITLE
minikube addons enable registry-creds Failed 

### ISSUE THREAD

**Issue by steephengeorge** [kubernetes/minikube#10022]
I am trying to set up Minikube in my local Windows machine against AWS ECR by following the instructions from [here](https://minikube.sigs.k8s.io/docs/tutorials/configuring_creds_for_aws_ecr/).

I successfully ran

minikube addons configure registry-creds

>* registry-creds was successfully configured

But it failed in following step

 minikube addons enable registry-creds
> X Exiting due to MK_ENABLE: run callbacks: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/registry-creds-rc.yaml: Process exited with status 1 stdout:

> stderr: error: error parsing /etc/kubernetes/addons/registry-creds-rc.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key

minikube version: v1.15.1 with VirtualBox
commit: 23f40a012abb52eff365ff99a709501a61ac5876
Windows 10

I compared the latest version of registry-creds-rc.yaml with my local version, both are same.

**Comment by priyawadhwa** [comment]
Hey @steephengeorge looks like this is a known issue with minikube version 1.15.x

https://github.com/kubernetes/minikube/issues/9893

This should have been fixed by https://github.com/kubernetes/minikube/pull/9733

Could you try upgrading to our latest release, [v1.16.0](https://github.com/kubernetes/minikube/releases/tag/v1.16.0), to see if that resolves the issue? Thank you!

**Comment by steephengeorge** [comment]
Thank you for the info. Windows choco didn't yet support V1.16.0. I will hack it and let you know

**Comment by priyawadhwa** [comment]
@steephengeorge sounds good, please let us know if the newest version works for you!

**Comment by spowelljr** [comment]
@steephengeorge Any update?

**Comment by steephengeorge** [comment]
It worked as expected. You can close this ticket.

**Comment by steephengeorge** [comment]
It is working as expected with version v1.17.1
