### ISSUE TITLE
fix docker network inspect to handle networks without MTU

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10033]
while this is rate but it might happen (if user uses a bad docker verison once and then later upgrade docker but still have a stuck old minikube network)

to replicate, create a network without mtu

```
$ docker network create m1
c681cfeab80f7cce0e16948aa6c31b2c451d03974e2ec3675ddbba54c7f3c8c9
```

## Currrent behaviour "
using this code
https://github.com/medyagh/minikube/blob/9e5beb4e37298d296694cd7339740e336c62a653/pkg/drivers/kic/oci/network_create.go#L175-L176
it will run this:
```
$ docker network inspect m1 --format '{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{(index .Options "com.docker.network.driver.mtu")}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}'
```
which outputs this  (and it is missing MTU)
```
{"Name": "m1","Driver": "bridge","Subnet": "172.19.0.0/16","Gateway": "172.19.0.1","MTU": , "ContainerIPs": []}
```

we want it to fix the go template to instead return 0 for the MTU so it does NOT have a parsing error.

so it should return
## desired behaviour

```
{"Name": "m1","Driver": "bridge","Subnet": "172.19.0.0/16","Gateway": "172.19.0.1","MTU": 0 , "ContainerIPs": []}
```

_Originally posted by @baiwfg2 in https://github.com/kubernetes/minikube/issues/9811#issuecomment-748493691_

**Comment by azhao155** [comment]
Has pr: https://github.com/kubernetes/minikube/pull/10053
