### ISSUE TITLE
Spinner mess up minikube-pr-bot report

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes/minikube#10043]
https://github.com/kubernetes/minikube/pull/9920#issuecomment-747538974

![image](https://user-images.githubusercontent.com/14567045/103056184-35ede380-45d7-11eb-90fb-62b9bdeb5eda.png)

**Comment by priyawadhwa** [comment]
Hey @lingsamuel thank you for opening this issue. I'm going to close it as a duplicate of #9939 , which is our solution for improving the output here.
