### ISSUE TITLE
sometimes K8s still try to pull cached images

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes/minikube#10045]
When I am verifying #10044, I found sometimes k8s still try to pull cached images.

![image](https://user-images.githubusercontent.com/14567045/103060568-84a17a80-45e3-11eb-8a6f-e30e56d0fedc.png)

**Comment by lingsamuel** [comment]
I am sure these images are loaded into the host machine (checked by `docker images`). Not sure why it happens. I guess maybe the pod is started before the images are loaded? If remove the pod, the newly created pod recognizes existed images correctly.

**Comment by lingsamuel** [comment]
potential reason https://github.com/kubernetes/minikube/blob/3dac483db9c5511056865c448be3121f97a6a796/pkg/minikube/machine/cache_images.go#L97-L106

**Comment by priyawadhwa** [comment]
Hey @lingsamuel -- I'm wondering if maybe those images are in the cache from a previous iteration of minikube. What is the ouptut of:

```
minikube cache list
```

**Comment by lingsamuel** [comment]
@priyawadhwa In the upper right corner of the picture

**Comment by lingsamuel** [comment]
I encountered this problem again and delete pod can't fix. Seems like kubelet didn't check local images?

```bash
# inside kvm
$ curl -s --unix-socket /var/run/docker.sock http://localhost/images/json | jq | grep metrics-server
      "k8s.gcr.io/metrics-server/metrics-server:v0.4.1"
      "k8s.gcr.io/metrics-server-amd64:v0.2.1"
$ docker images | grep metrics-server
k8s.gcr.io/metrics-server/metrics-server                v0.4.1     9759a41ccdf0   7 weeks ago     60.5MB
k8s.gcr.io/metrics-server-amd64                         v0.2.1     9801395070f3   3 years ago     42.5MB
```

```log
# journalctl -u kubelet
Jan 08 09:21:14 minikube kubelet[8737]: W0108 09:21:14.358190    8737 docker_sandbox.go:402] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/metrics-server-d9b576748-txkbk through plugin: invalid network status for
Jan 08 09:21:28 minikube kubelet[8737]: E0108 09:21:28.432723    8737 remote_image.go:113] PullImage "k8s.gcr.io/metrics-server-amd64:v0.2.1" from image service failed: rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connecti
Jan 08 09:21:28 minikube kubelet[8737]: E0108 09:21:28.432788    8737 kuberuntime_image.go:51] Pull image "k8s.gcr.io/metrics-server-amd64:v0.2.1" failed: rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Tim
```

Some logs may help.

**Comment by medyagh** [comment]
@lingsamuel I suspect you are on something ! our cace add could have more vefifications in it, I would accept any PR that would fix this.

**Comment by lingsamuel** [comment]
No idea why this happened. I can't find a reliable way to re-pro this issue.

**Comment by medyagh** [comment]
if anyone else a way to reproduce this issue, please if you contribute your logs and steps it would help with finding the root cause,

**Comment by andriyDev** [comment]
We haven't been able to reproduce this issue for a while, if anyone can please reopen this issue and add logs here!
