### ISSUE TITLE
minikube addons enable ingress fails

### ISSUE THREAD

**Issue by springcomefromprogrammingtheworld** [kubernetes/minikube#10059]
**重现问题所需的命令**：minikube addons enable ingress

**失败的命令的完整输出**：<details>
🔎  Verifying ingress addon...

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：centos 7 64位

**Comment by lingsamuel** [comment]
run `kubectl get pod -n kube-system` and make sure there is no error (e.g. ErrImagePull).

Use `minikube cache add image:tag` to add a local image to minikube if required images pull error.

**Comment by lingsamuel** [comment]
Or you can start cluster by adding `--image-mirror-country cn` to use aliyun mirror.

**Comment by lingsamuel** [comment]
xref #10063

**Comment by tstromberg** [comment]
@springcomefromprogrammingtheworld - did @lingsamuel 's advice help?

**Comment by zhangb191** [comment]
解决了吗，我也遇到了这个问题，来求助～

**Comment by springcomefromprogrammingtheworld** [comment]
@zhangb191  解决了  
第一步从阿里云镜像仓库拉取镜像
1.docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2

第二步重现命名标签
2.docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2 us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2

第三步添加镜像缓存
3.minikube cache add us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2
第四步启用ingress
4.minikube addons enable ingress --alsologtostderr

**Comment by spowelljr** [comment]
@springcomefromprogrammingtheworld Is your issue solved now? Or are you still having the issue?

-----

@springcomefromprogrammingtheworld 您的问题现在解决了吗？还是您还有问题？

**Comment by lingsamuel** [comment]
He said
> 解决了
means solved.

**Comment by spowelljr** [comment]
@lingsamuel Thanks

Since this is solved I'm going to close the issue.

Feel free to reopen the issue if needed.

**Comment by Bytesu** [comment]
> @zhangb191 解决了
> 第一步从阿里云镜像仓库拉取镜像
> 1.docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2
> 
> 第二步重现命名标签
> 2.docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/nginx-ingress-controller:v0.40.2 us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2
> 
> 第三步添加镜像缓存
> 3.minikube cache add us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2
> 第四步启用ingress
> 4.minikube addons enable ingress --alsologtostderr

not work for me . it is still  'waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending:'
