### ISSUE TITLE
Error while connecting minikube VM with Local Host | need help to set IP address in minikube VM

### ISSUE THREAD

**Issue by bkaran08** [kubernetes/minikube#10052]
C:\Windows\system32> minikube start
* minikube v1.15.1 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. Running "minikube delete" may fix it: provision: IP not found

X Exiting due to GUEST_PROVISION: Failed to start host: provision: IP not found
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose
![Capture](https://user-images.githubusercontent.com/76641997/103166807-aac95380-484b-11eb-9f91-945beea11ba6.PNG)

**Comment by priyawadhwa** [comment]
Hey @bkaran08 does this also happen on a freshly created cluster?

Could you try the following:

```
minikube delete
minikube start
```

to see if that fixes it? 

If you have docker installed, I'd also recommend switching to the docker driver because that is our recommended driver. You can do it by running `minikube start --driver docker`.

Let me know what results you get. Thank you!

**Comment by lboening** [comment]
```shell
C:\Users\PAR32LSB01>minikube start --driver=hyperv --hyperv-use-external-switch
😄  minikube v1.15.1 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
✨  Using the hyperv driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperv VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
```

I had identical problem. I will use docker driver.

**Comment by bkaran08** [comment]
> Hey @bkaran08 does this also happen on a freshly created cluster?
> 
> Could you try the following:
> 
> ```
> minikube delete
> minikube start
> ```
> 
> to see if that fixes it?
> 
> If you have docker installed, I'd also recommend switching to the docker driver because that is our recommended driver. You can do it by running `minikube start --driver docker`.
> 
> Let me know what results you get. Thank you!

Thank you for the helpful reply, 
I tried and I reinstalled according to your suggestion and it work.
