### ISSUE TITLE
.kube directory: permission denied

### ISSUE THREAD

**Issue by Nellyoj** [kubernetes/minikube#10056]
Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /Users/nelsonojong/.kube: mkdir /Users/nelsonojong/.kube: permission denied

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by priyawadhwa** [comment]
Hey @Nellyoj 

This is probably failing because the `Users/nelsonojong/.kube` directory is owned by another user or was created by sudo.

Could you try:

```
sudo chown -R /Users/nelsonojong/.kube
```
If that doesn't fix it, do you mind sharing the output of:

```
ls -la /Users/nelsonojong/.kube
```

Thank you!

**Comment by priyawadhwa** [comment]
Ref: https://github.com/kubernetes/minikube/issues/5417#issuecomment-533580130

**Comment by Nellyoj** [comment]
nelsonojong@Nelsons-MacBook-Pro ~ % minikube start --vm-driver=hyperkit
😄  minikube v1.16.0 on Darwin 11.1
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running hyperkit "minikube" VM ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...\ 🤦  Unable to restart cluster, will reset it: getting k8s client: client config: client config: context "minikube" does not exist

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...

❌  Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /Users/nelsonojong/.kube: mkdir /Users/nelsonojong/.kube: permission denied

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

nelsonojong@Nelsons-MacBook-Pro ~ % minikube start --vm-driver=hyperkit

**Comment by Nellyoj** [comment]
i was trying to install vm driver=hyperkit for the first time on my machine. Here is the error message

**Comment by sharifelgamal** [comment]
The user you're running minikube does not have access to the `.kube` folder. If you're running minikube as `nelsonojong` then the permissions for `/Users/nelsonojong/.kube` are totally messed up (maybe you tried starting it with sudo first?). I would just try deleting that directory (along with the `.minikube` directory) and trying again.

**Comment by priyawadhwa** [comment]
Hey @Nellyoj did you try deleting that directory and starting again?

**Comment by ilya-zuyev** [comment]
@Nellyoj any update on this issue?

**Comment by medyagh** [comment]
Hi @KimSeongHo-cloud , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
