### ISSUE TITLE
minikube delete giving error : X Exiting due to GUEST_PROFILE_DELETION: CreateFile C:\Users\username\.minikube\machines\minikube\boot2docker.iso: Access is denied., even though I'm running this command in administrator shell

### ISSUE THREAD

**Issue by Allah-The-Dev** [kubernetes/minikube#10050]
**Steps to reproduce the issue:** 

1. minikube start --cpus=4 --memory=8000M --driver=hyperv 
2. minikube delete

**Full output of failed command:** 
* Removing C:\Users\username\.minikube\machines\minikube ...

X Exiting due to GUEST_PROFILE_DELETION: CreateFile C:\Users\username\.minikube\machines\minikube\boot2docker.iso: Access is denied.
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

 minikube start --cpus=4 --memory=8000M --driver=hyperv

**Optional: Full output of `minikube logs` command:**
<details>
X Exiting due to GUEST_NOT_FOUND: load: filestore "minikube": open C:\Users\username\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

</details>

**Comment by medyagh** [comment]
@Allah-The-Dev  do u mind checking if u ave access to the folder ?  C:\Users\username.minikube\machines\minikube\b

and also do u mind installing the latest verison of minikbue ? your verison seems to be outdated.

and also can u please share the full output of  these commands ?

```
minikube delete --all
minikube start --cpus=4 --memory=8000M --alsologtostderr
```

**Comment by Allah-The-Dev** [comment]
After this problem I uninstalled minikube using chocolatey and installed again, it worked. Now after minikube version 16, I never faced this issue again, may be it is fixed or not sure.

**Comment by medyagh** [comment]
glad to see u dont have this issue

**Comment by maxuellstalin** [comment]
Sorry I'm using the translator.

The same error happened to me, I simply deleted the minikube from my VM, which in this case is the HYPER-V, and then ran the minikube delete --all
