### ISSUE TITLE
service type=NodePort doesn't work in non-standard port range (even with apiserver configuration)

### ISSUE THREAD

**Issue by notmaxx** [kubernetes/minikube#1006]
BUG REPORT

**Minikube version**: v0.15.0

**Environment**:
- **OS**: OS X El Captain, Version: 10.11.6 (15G1212)
- **VM Driver**: xhyve
- **Docker version**: 1.12.6, build 78d1802
- **Install tools**: `curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.15.0/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/`
- **Others**: 

**What happened**:
Issue is similar to https://github.com/kubernetes/minikube/issues/836 but doesn't work for me

I receive error when start service on ports other than 30000-32767: 
`The Service "http-service" is invalid: spec.ports[0].nodePort: Invalid value: 3000: provided port is not in the valid range. The range of valid ports is 30000-32767`

Even with apiserver port range configured during `minikube start`
```
minikube start --extra-config=apiserver.GenericServerRunOptions.ServerRunOptions.ServiceNodePortRange=1000-10000
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.
```

**What you expected to happen**:
I expect my "http-service" service would be created successfully & I can use my rails app running in pod in minikube on port 3000

**How to reproduce it** (as minimally and precisely as possible):
```
minikube start --extra-config=apiserver.GenericServerRunOptions.ServerRunOptions.ServiceNodePortRange=1000-10000
kubectl create -f web-service.json
```

**Anything else do we need to know**:

Here is my web-service.json

```
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "http-service"
  },
  "spec": {
    "type": "NodePort",
    "ports": [
      {
        "name": "http",
        "protocol": "TCP",
        "port": 3000,
        "targetPort": 3000,
        "nodePort": 3000
      },
      {
        "name": "http-webpack",
        "protocol": "TCP",
        "port": 3010,
        "targetPort": 3010,
        "nodePort": 3010
      },
      {
        "name": "test-nginx",
        "protocol": "TCP",
        "port": 80,
        "targetPort": 8080,
        "nodePort": 8080
      }
    ],
    "selector": {
      "name": "http-service"
    }
  }
}
```

**Comment by notmaxx** [comment]
Right now I use `socat` as workaround (in case someone use similar problems)
```
# in my current config I map http & http-webpack to ports 31000 & 31010 
socat TCP-LISTEN:3010,fork TCP:192.168.64.4:31010 & 
socat TCP-LISTEN:3000,fork TCP:192.168.64.4:31000 & 
```

**Comment by r2d4** [comment]
Can you show the output of `minikube logs | grep ServiceNodePortRange`

**Comment by notmaxx** [comment]
hi @r2d4 

here you go, seems my error is similar to discussion in https://github.com/kubernetes/minikube/issues/836, people posted similar logs there
```
~/workato-root/workato (dockerizing) alexeypikin$ minikube logs | grep ServiceNodePortRange
Jan 20 19:50:27 minikube localkube[2691]: I0120 19:50:27.159478    2691 localkube.go:117] Setting GenericServerRunOptions.ServerRunOptions.ServiceNodePortRange to 1000-10000 on apiserver.
Jan 20 19:50:27 minikube localkube[2691]: W0120 19:50:27.159490    2691 localkube.go:119] Unable to set GenericServerRunOptions.ServerRunOptions.ServiceNodePortRange to 1000-10000. Error: Unable to find field by name: ServerRunOptions
Jan 20 19:50:27 minikube localkube[2691]: I0120 19:50:27.159495    2691 localkube.go:117] Setting GenericServerRunOptions.ServerRunOptions.ServiceNodePortRange to 1000-10000 on apiserver.
Jan 20 19:50:27 minikube localkube[2691]: W0120 19:50:27.159499    2691 localkube.go:119] Unable to set GenericServerRunOptions.ServerRunOptions.ServiceNodePortRange to 1000-10000. Error: Unable to find field by name: ServerRunOptions
```

**Comment by r2d4** [comment]
Your issue is that you're not using the correct path for ServiceNodePortRange, it should be 

```
$ minikube start --extra-config=apiserver.GenericServerRunOptions.ServiceNodePortRange=1000-10000
$ minikube logs | grep ServiceNodePortRange
 
Jan 20 20:45:51 minikube localkube[12296]: I0120 20:45:51.238465   12296 localkube.go:117] Setting GenericServerRunOptions.ServiceNodePortRange to 1000-10000 on apiserver.
```

i.e. apiserver.GenericServerRunOptions<del>.ServerRunOptions</del>.ServiceNodePortRange=1000-10000

**Comment by notmaxx** [comment]
@r2d4 thank you
