### ISSUE TITLE
 Error restarting cluster: waiting for apiserver: apiserver process never appeared

### ISSUE THREAD

**Issue by jjbapt21** [kubernetes/minikube#10073]
**Steps to reproduce the issue:** 

1.# minikube start --vm-driver=none
* minikube v1.5.2 on Centos 7.9.2009 (xen/amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Using the running none "minikube" VM ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.16.2 on Docker '20.10.1' ...
* Relaunching Kubernetes using kubeadm ...
*
X Error restarting cluster: waiting for apiserver: apiserver process never appeared
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
minikube v1.5.2 is very old. Please upgrade to the latest version.

If you run into problems there, please include the `minikube logs` output in your issue report. Thank you!
