### ISSUE TITLE
Bug: kubernetes 1.5 full crash under certain conditions in linux (both vbox and kvm)

### ISSUE THREAD

**Issue by v1k0d3n** [kubernetes/minikube#1007]
**Minikube version** (use `minikube version`): v0.15.0

**Environment**:
- **OS:** Ubuntu 16.04 (and CentOS from what I understand)
- **VM Driver:** both virtualbox and kvm
- **Docker version:** 1.12.6
- **Install tools:** Helm is being used for Kubernetes components
- **Others:**

**What happened:** Under certain conditions, Kubernetes cluster API becomes unusable (virtualbox), or unstable (kvm). This occurs with charts we have created for MariaDB. Issue happens during job.

**What you expected to happen:** When minikube is not used, helm charts deploy just fine (containers and jobs).

**How to reproduce it:** (as minimally and precisely as possible): Full instructions for our Helm charts can be found at: https://github.com/att-comdev/openstack-helm/blob/master/docs/developer/minikube.md

Openstack on Kubernetes in *about* 10 commands:
1. Install latest version of Minikube and Helm
2. Start Minikube/cluster with the following conditions:
```
$ minikube start \
    --network-plugin=cni \
    --kubernetes-version v1.5.1 \
    --disk-size 40g \
    --memory 4048
```
3. Deploy Calico or other SDN with CNI enabled
4. Clone our repository: `git clone https://github.com/att-comdev/openstack-helm.git && cd openstack-helm`
5. Run `helm init` to deploy tiller
6. Start a helm local repo: `helm serve &`
7. Add the local repo to helm: `helm repo add local http://localhost:8879/charts`
8.  Run `make` to lint and install helm charts in the local repo (do `helm search` to verify charts are added).
9. Label nodes to be "openstack controller nodes": `$ kubectl label nodes openstack-control-plane=enabled --all --namespace=openstack`
10. Deploy the MariaDB chart with flags for "developer mode" (if statement for using hostPath vs. PVC): `$ helm install --name mariadb --set development.enabled=true local/mariadb --namespace=openstack`

**Anything else do we need to know**: This seems to deploy just fine in OSX under VirtualBox (which is how I drafted my instructions). However, users are complaining that etcd is "freaking out" with Linux/Minikube. I attempted to run this myself in Ubuntu, and sure enough...I can repeat this issue each time. With vbox, it's total annihilation of the Kubernetes API. In KVM, services become entirely unstable until `eviction` occurs. I can answer any questions you might have. The logs seem to be a bit all over the place, so if you can tell me where to start, I'll grab whatever is needed.

**Comment by v1k0d3n** [comment]
to help the development team a little bit (i think we can provide some logs also), changing the source iso resolved the issue: 

```
$ minikube start \
        --network-plugin=cni \
        --kubernetes-version v1.5.1 \
        --disk-size 40g \
        --memory 16384 \
        --cpus 4 \
        --vm-driver kvm \
        --iso-url=https://storage.googleapis.com/minikube/iso/minikube-v1.0.4.iso
```

This allowed me to run through our startup guide (mentioned above) without issue.

**Comment by r2d4** [comment]
@v1k0d3n Thanks for the update on this bug.  We enabled the kernel config CONFIG_IP_SET=y in the ISO and this seemed to resolve some of the issues with the CNI network plugin.  

It looks like there are still some issues with calico and weave needing some additional kernel modules enabled.  https://github.com/projectcalico/calicoctl/issues/1444.  A little more work needs to go into figuring out exactly what these are so that we can add them into the new image.
