### ISSUE TITLE
minikube-v1.0.2.iso is missing vmlinuz64

### ISSUE THREAD

**Issue by parkerd** [kubernetes/minikube#1008]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`): v0.15.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac OS X 10.11.2
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **Docker version** (e.g. `docker -v`):
- **Install tools**:
- **Others**:

**What happened**:

Failed on missing vmlinuz64. Looked at minikube-v1.0.2.iso and it's not there.

```
Starting local Kubernetes cluster...
Downloading Minikube ISO
 68.95 MB / 68.95 MB [==============================================] 100.00% 0s
E0115 14:43:13.054900   70319 start.go:96] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: open /Users/pdebardelaben/.minikube/machines/minikube/b2d-image/boot/vmlinuz64: no such file or directory.

 Retrying.
E0115 14:43:13.055841   70319 start.go:102] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: open /Users/pdebardelaben/.minikube/machines/minikube/b2d-image/boot/vmlinuz64: no such file or directory
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
```

**What you expected to happen**:

Cluster setup.

**How to reproduce it** (as minimally and precisely as possible):

- Download minikube v0.15.0
- Run `minikube start --vm-driver=xhyve`

**Anything else do we need to know**:

I've downgraded to v0.14.0 which uses an older version of the iso and works as expected.

**Comment by dlorenc** [comment]
Which version of the xhyve driver are you using? We fixed this in newer releases.

**Comment by parkerd** [comment]
```
$ xhyve -v
xhyve: 0.2.0
```

Installed via homebrew, appears to be the latest release.

**Comment by dlorenc** [comment]
Sorry, you'll need to install docker-machine-driver-xhyve through brew. Could you run:

$ brew upgrade docker-machine-driver-xhyve

I have 0.3.1

**Comment by parkerd** [comment]
Thanks, docker-machine-driver-xhyve v0.3.1 works with minikube v0.15.0.

This may be worth a mention in the minikube release notes and/or docs.
