### ISSUE TITLE
minikube start error

### ISSUE THREAD

**Issue by wallwind** [kubernetes/minikube#10083]
**Steps to reproduce the issue:** 

 minikube start --driver=none
😄  minikube v1.16.0 on Centos 7.2
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Tencent tlinux 2.2 (Final)
🐳  Preparing Kubernetes v1.20.0 on Docker  ...

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
        panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc0001df348)
        /usr/local/go/src/text/template/exec.go:166 +0x1b5
panic(0x7fecfdd2a540, 0x7fecfe066b20)
        /usr/local/go/src/runtime/panic.go:522 +0x1b9
reflect.Value.FieldByIndex(0x7fecfdf0bac0, 0xc000478080, 0x99, 0xc000110940, 0x2, 0x2, 0x0, 0x7fecfe129d60, 0x7fecfdd2a540)
        /usr/local/go/src/reflect/value.go:852 +0x32b
text/template.(*state).evalField(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7ffe20c8c444, 0xc, 0x7fecfe0e8f80, 0xc000446de0, 0xc0003cbac0, 0x1, ...)
        /usr/local/go/src/text/template/exec.go:604 +0xa59
text/template.(*state).evalFieldChain(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7fecfe0e8f80, 0xc000446de0, 0xc0003cbab0, ...)
        /usr/local/go/src/text/template/exec.go:554 +0x222
text/template.(*state).evalFieldNode(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0xc000446de0, 0xc0003cbac0, 0x1, 0x1, 0x7fecfddde980, 0x7fecff2fc710, ...)
        /usr/local/go/src/text/template/exec.go:518 +0x116
text/template.(*state).evalCommand(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0xc000446db0, 0x7fecfddde980, 0x7fecff2fc710, 0x99, 0xc0001df0e0, 0x0, ...)
        /usr/local/go/src/text/template/exec.go:456 +0x7aa
text/template.(*state).evalPipeline(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0xc0003db320, 0x0, 0xc0004ea3c8, 0x0)
        /usr/local/go/src/text/template/exec.go:430 +0x11e
text/template.(*state).walk(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7fecfe0e8e00, 0xc000446e10)
        /usr/local/go/src/text/template/exec.go:254 +0x49e
text/template.(*state).walk(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7fecfe0e9040, 0xc000446d80)
        /usr/local/go/src/text/template/exec.go:262 +0x145
text/template.(*Template).execute(0xc000478000, 0x7fecfe0890a0, 0xc0002494a0, 0x7fecfdf0bac0, 0xc000478080, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:217 +0x1ea
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:200
github.com/docker/cli/cli/command/system.formatInfo(0x7fecfe122cc0, 0xc00027a000, 0x0, 0xc0003cb8a0, 0x1, 0x1, 0xc000297ec0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/system/info.go:482 +0x1f6
github.com/docker/cli/cli/command/system.runInfo(0xc00021a500, 0x7fecfe122cc0, 0xc00027a000, 0xc0003cb260, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:85 +0x344
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc00021a500, 0xc0003f53a0, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:52 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00021a500, 0xc000219b10, 0x2, 0x2, 0xc00021a500, 0xc000219b10)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x467
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f8a00, 0xc000219b00, 0x3, 0x3)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ee
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
main.runDocker(0xc00027a000, 0x7fecfe08b440, 0xc000010020)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x1d5
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
What is your Docker version ?

**Comment by priyawadhwa** [comment]
Hey @wallwind are you still seeing this issue with the latest release of minikube and docker?

**Comment by manpreet1994** [comment]
I had the same error. 
In my case, issue was "docker info" had permission issue.

The following resolved the permission issue:-
https://stackoverflow.com/questions/48957195/how-to-fix-docker-got-permission-denied-issue

**Comment by rmon-vfer** [comment]
I am having this exact same issue running `minikube start --driver=none` on Ubuntu 10.4 inside Virtual Box 6.1. Here is the error trace:
```shell
student@cluster-server:~$ minikube start --driver none
* minikube v1.18.1 on Ubuntu 18.04 (vbox/amd64)
* Using the none driver based on existing profile

X The requested memory allocation of 1992MiB does not leave room for system overhead (tota                                                             l system memory: 1992MiB). You may face stability issues.
* Suggestion: Start minikube with less memory allocated: 'minikube start --memory=1992mb'

* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 18.04.5 LTS
* Preparing Kubernetes v1.20.2 on Docker  ...
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getti                                                             ng cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
        panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc0005512a8)
        /usr/local/go/src/text/template/exec.go:170 +0x1b5
panic(0x559b537219a0, 0x559b53a62e80)
        /usr/local/go/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x559b538daca0, 0xc00004e100, 0x99, 0xc00014ab30, 0x2, 0x2, 0x0                                                             , 0x559b53b19fc0, 0x559b537219a0)
        /usr/local/go/src/reflect/value.go:883 +0x39e
text/template.(*state).evalField(0xc000551228, 0x559b538daca0, 0xc00004e100, 0x99, 0x7ffc0                                                             d45f731, 0xc, 0x559b53aeae80, 0xc000160f30, 0xc00038e0b0, 0x1, ...)
        /usr/local/go/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc000551228, 0x559b538daca0, 0xc00004e100, 0x99, 0x                                                             559b538daca0, 0xc00004e100, 0x99, 0x559b53aeae80, 0xc000160f30, 0xc00038e0a0, ...)
        /usr/local/go/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc000551228, 0x559b538daca0, 0xc00004e100, 0x99, 0xc                                                             000160f30, 0xc00038e0b0, 0x1, 0x1, 0x559b537c6920, 0x559b54b1f448, ...)
        /usr/local/go/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc000551228, 0x559b538daca0, 0xc00004e100, 0x99, 0xc00                                                             0160e70, 0x559b537c6920, 0x559b54b1f448, 0x99, 0xd0, 0x559b538ba880, ...)
        /usr/local/go/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc000551228, 0x559b538daca0, 0xc00004e100, 0x99, 0xc0                                                             00099c80, 0xc00010a138, 0xc00039cd00, 0xc0005510e0)
        /usr/local/go/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc000551228, 0x559b538daca0, 0xc00004e100, 0x99, 0x559b53aead                                                             00, 0xc000160f60)
        /usr/local/go/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc000551228, 0x559b538daca0, 0xc00004e100, 0x99, 0x559b53aeaf                                                             40, 0xc000160e40)
        /usr/local/go/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc00004e080, 0x559b53a847c0, 0xc000233b30, 0x559b538dac                                                             a0, 0xc00004e100, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x559b53b14ce0, 0xc00039cb60, 0x0, 0xc                                                             00056a350, 0x1, 0x1, 0xc0003ca3c0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/system/info.go:490 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc00052a840, 0x559b53b14ce0, 0xc00039cb6                                                             0, 0xc0003f4c00, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x37c
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc00052a840, 0xc000566280,                                                              0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00052a840, 0xc00                                                             052f780, 0x2, 0x2, 0xc00052a840, 0xc00052f780)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00025e2c0, 0xc0                                                             0052f770, 0x3, 0x3)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc00039cb60, 0x559b53a86de0, 0xc0000cc010)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3

*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose
```
