### ISSUE TITLE
Unable to get host IP: network inspect: docker network inspect minikube, exit status 64

### ISSUE THREAD

**Issue by LANCECN** [kubernetes/minikube#10081]
**Steps to reproduce the issue:** 

1.-- /stdout --
E0102 08:31:45.759884 1450618 start.go:99] Unable to get host IP: network inspect: docker network inspect minikube --format $
{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.$
onfig}}{{.Gateway}}{{end}}","MTU": {{(index .Options "com.docker.network.driver.mtu")}},{{$first := true}} "ContainerIPs": [$
{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

2. 
3.

**Full output of failed command:** 

I0102 08:31:45.707841 1450618 cli_runner.go:111] Run: docker network inspect minikube
/ I0102 08:31:45.759744 1450618 network_create.go:240] output of [docker network inspect minikube]: -- stdout --
[
    {
        "Name": "minikube",
        "Id": "c35b48224b815c786d292498419425cb0b2b65a68a527beaecf8a69b789d0e1c",
        "Created": "2021-01-02T08:31:03.980844015+08:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": {},
            "Config": [
                {
                    "Subnet": "192.168.49.0/24",
                    "Gateway": "192.168.49.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "7cf326f83d937b5e2e74b8b1d42c6bafafefd863b938f80a14b6b76755feec5c": {
                "Name": "minikube",
                "EndpointID": "4c7209e48f585746f341ea98aa770e052d2f9af5e345b9dbf6a3578efb68c8dd",
                "MacAddress": "02:42:c0:a8:31:02",
                "IPv4Address": "192.168.49.2/24",
                "IPv6Address": ""
            }
        },
        "Options": {
            "--icc": "",
            "--ip-masq": ""
        },
        "Labels": {
            "created_by.minikube.sigs.k8s.io": "true"
        }
    }
]

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
Please include complete logs and system information.

Most likely similar to the issues in #9811 (64=template)

**Comment by LANCECN** [comment]
docker version
Client:
 Version:           18.09.0
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:49:01 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.0
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       4d60db4
  Built:            Wed Nov  7 00:16:44 2018
  OS/Arch:          linux/amd64
  Experimental:     false

**Comment by LANCECN** [comment]
**Updated docker version from 18.09.0 to 20.10.1, problem solved.  Thanks!** 

docker version
Client: Docker Engine - Community
 Version:           20.10.1
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        831ebea
 Built:             Tue Dec 15 04:34:59 2020
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       f001486
  Built:            Tue Dec 15 04:32:40 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
