### ISSUE TITLE
Add functional test for system versions of container engines

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#10089]
_(This is issue is about KIC on Linux)_

Currently we are testing with the **vendor** versions of the container engines:

- docker.com
  - https://docs.docker.com/engine/install/
- podman.io
   - https://podman.io/getting-started/installation

But maybe we also need to test with the **system** versions, in the distributions:

- debian
  - https://packages.debian.org/docker.io 
  - https://packages.debian.org/podman
- ubuntu
  - https://packages.ubuntu.com/docker.io 
  - https://packages.ubuntu.com/podman
- fedora
  - https://src.fedoraproject.org/rpms/moby-engine _(Provides: docker)_
  - https://src.fedoraproject.org/rpms/podman
- centos
  - docker (el7: 1.13)
  - podman (el8: 2.0)

Or at least add some documentation, as to which "variants" are supported.

Currently users expect to be able to install the packages from anywhere...

----

Note that this issue is about the container engine to be used for the node:

* Docker
* Podman

It's **not** about the container runtime to be used _inside_ the container node:

* Docker (dockershim/cri-dockerd)
* CRI-O
* containerd

For those we still only support the vendor versions, as per [Kubernetes upstream](https://kubernetes.io/docs/setup/production-environment/container-runtimes/).
There are system versions in some other dedicated Kubernetes operating systems.
But we don't use those, so it is up to each Kubernetes distribution to support them.
Example is our own custom Buildroot distribution for the ISO, with system packages.

**Comment by afbjorklund** [comment]
Otherwise we risk seeing distribution-specific issues like #10088

Could also be a good idea to document supported versions: #9077

**Comment by afbjorklund** [comment]
Using vagrant for regression/release testing is a great idea.

Unfortunately it only works for real servers, not nested VMs.

**Comment by afbjorklund** [comment]
Partly related to #3552, for adding support for fedora/centos.

Also need some good way to aggregate/present the results ?

**Comment by afbjorklund** [comment]
I started on some test infrastructure, for generic: #4733

Should clean it up and make it general... https://github.com/kubernetes/minikube/pull/9545#issuecomment-718855132

**Comment by medyagh** [comment]
do u mind adding more clarificaiton, I am a bit confused, if you are talking about the inside minikube podman engine?

**Comment by afbjorklund** [comment]
> do u mind adding more clarificaiton, I am a bit confused, if you are talking about the inside minikube podman engine?

I tried to clarify:

> Note that this issue is about the container engine to be used for the node.
>
> It's **not** about the container runtime to be used inside the container node.

When using docker-in-docker, it can easilly get confusing which is "docker" and which is "docker". 🙂

We control the inside, and there we _only_ run the vendor variant. Not whatever is in the distribution.
This is the same as kubernetes upstream* (kubeadm), except we don't have the same version lock.

\* https://kubernetes.io/docs/setup/production-environment/container-runtimes/

Except for the "none" driver, but there are really no guarantees if you try to use something else...
Ultimately we should probably always provision the runtime - also for the none and generic drivers.

So this issue was all about the outside, if we should support the distribution versions as well ?

**Comment by afbjorklund** [comment]
Main reason to support the standard versions, would be to make it simpler for the user.

`sudo apt install docker.io`

vs
```console
$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
$ sudo apt-get update
$ sudo apt-get install docker-ce docker-ce-cli containerd.io
```

It also makes it easier to access the source code, and integrate with other packages.

That is important to some people, especially Debian users. They don't want the binaries.

**Comment by medyagh** [comment]
this is a good idea ! for the starting point we should at least add ubuntu test to our matrix.

**Comment by afbjorklund** [comment]
Maybe weigh the test matrix, against what minikube users are actually using ?

**Comment by ilya-zuyev** [comment]
We need to add functional tests for older versions of ubuntu and included docker versions

**Comment by afbjorklund** [comment]
Actually this issue doesn't have so much to do with the OS versions that minikube is doing the testing with.

It was about testing with the system package of the container runtimes, as well as the vendor packages ?

**Comment by medyagh** [comment]
I dont know if we have ifnra bandwith to add more tests infra just for this. if Github Actions would provide older OS or Debian we could add functioan on github action if not we could close this issue for now till that infra is available for us
