### ISSUE TITLE
`docker-env` should ignore invalid docker proxy env vars

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes/minikube#10098]
**Steps to reproduce the issue:** 

1. minikube start --driver=kvm2
1. minikube docker-env

I found sometimes `docker-env` finished almost instantly, sometimes it takes about 10s+.

**Comment by afbjorklund** [comment]
You can try troubleshooting with `--alsologtostderr`, to see where it is spending the time ?

There were a lot of health checks added, both to the cluster and to the docker runtime itself.

**Comment by lingsamuel** [comment]
Okay I found the reason...
```
I0108 11:08:47.237526 3197810 docker-env.go:427] Testing Docker connectivity with: /usr/bin/docker version --format={{.Server}}
W0108 11:08:47.276089 3197810 docker-env.go:293] couldn't connect to docker inside minikube.  output: proxy: unknown scheme: socks
 error: exit status 1
W0108 11:08:47.276112 3197810 docker-env.go:187] dockerd is not active will try to reload it...
```
I have proxy set to `socks://127.0.0.1:1080/`

**Comment by lingsamuel** [comment]
So that's the reason why my pods always restart :joy: I was thought that's because of my lack of memory

**Comment by afbjorklund** [comment]
There should be some output, when minikube is doing "extra" stuff (instead of printing docker-env)

**Comment by lingsamuel** [comment]
> There should be some output, when minikube is doing "extra" stuff
Couldn't agree more! Sometimes I have to add `--alsologtostderr` to see why minikube hangs there.
