### ISSUE TITLE
Minikube failed to start

### ISSUE THREAD

**Issue by rama-jpmc** [kubernetes/minikube#10090]
1. minikube start --driver=hyperv

**Full output of failed command:** 
Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

**Comment by priyawadhwa** [comment]
Hey @rama-jpmc thanks for opening this issue. Did you try creating a virtual switch as described here? https://docs.docker.com/machine/drivers/hyper-v/

**Comment by medyagh** [comment]
@rama-jpmc i wonder if u are still facing the issue did the comment above help ? 

btw I am wondeirng if u have tried our docker driver?
