### ISSUE TITLE
Error starting host: Error creating new host: Driver "kvm" not found. Do you have the plugin binary accessible in your PATH?

### ISSUE THREAD

**Issue by ervikrant06** [kubernetes/minikube#1009]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`):

# minikube version
minikube version: v0.15.0

**Environment**:
- **OS** (e.g. from /etc/os-release):  RHEL 7.2 

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
# cat ~/.minikube/machines/minikube/config.json | grep DriverName
cat: /root/.minikube/machines/minikube/config.json: No such file or directory

- **Docker version** (e.g. `docker -v`):
- **Install tools**:
# kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}

- **Others**:

**What happened**:
minikube start operation getting failed with following error. 
~~~
# minikube start --vm-driver kvm
Starting local Kubernetes cluster...
E0116 22:20:58.397271   30991 start.go:96] Error starting host: Error creating new host: Driver "kvm" not found. Do you have the plugin binary accessible in your PATH?.

 Retrying.
E0116 22:20:58.397803   30991 start.go:102] Error starting host:  Error creating new host: Driver "kvm" not found. Do you have the plugin binary accessible in your PATH?
~~~

I am running it as a root user. Able to use the virsh commands successfully no permission issue.

~~~
# virsh -c qemu:///system list
 Id    Name                           State
----------------------------------------------------
~~~

**What you expected to happen**:
Expecting to see successful creation of KVM minikube VM. 

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
Tried following option but no luck.

~~~
# minikube config set vm-driver kvm
These changes will take effect upon a minikube delete and then a minikube start

# minikube delete
Deleting local Kubernetes cluster...
Errors occurred deleting machine:  Error deleting host: minikube: Host does not exist: "minikube"

# minikube start
Starting local Kubernetes cluster...
E0116 22:22:11.330462   31035 start.go:96] Error starting host: Error creating new host: Driver "kvm" not found. Do you have the plugin binary accessible in your PATH?.

 Retrying.
E0116 22:22:11.331588   31035 start.go:102] Error starting host:  Error creating new host: Driver "kvm" not found. Do you have the plugin binary accessible in your PATH?
~~~

**Comment by r2d4** [comment]
You'll also need this driver binary in your PATH

https://github.com/dhiltgen/docker-machine-kvm/releases

> I am running it as a root user.

You shouldn't be running minikube as root

**Comment by ervikrant06** [comment]
Thanks. It's working after installing driver.

~~~
# minikube status
minikubeVM: Running
localkube: Running
~~~

Closing the request.
