### ISSUE TITLE
DockerEnv Test: 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10107]
https://storage.googleapis.com/minikube-builds/logs/10100/0b52244/Docker_Linux.html#fail_TestFunctional%2fparallel%2fDockerEnv

```
functional_test.go:194: (dbg) Non-zero exit: /bin/bash -c "eval $(out/minikube-linux-amd64 -p functional-20210106230346-2918037 docker-env) && docker images": exit status 1 (631.613712ms)
** stderr ** 
	The server probably has client authentication (--tlsverify) enabled. Please check your TLS client certification settings: Get https://192.168.124.150:2376/v1.40/images/json: remote error: tls: bad certificate
** /stderr **

```

I suspect this could be because the other parallel clusters are putting a lock on the Cert and it is not useable by the user. snice it hasppanes mostly in integration test and not in Github action where we run less parallel.

one solution could be generating Certs per cluster
```
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://127.0.0.1:55010"
export DOCKER_CERT_PATH="/Users/medya/.minikube/certs"
export MINIKUBE_ACTIVE_DOCKERD="minikube"

```

rght now the certs used for docker-env are shared across all clusters

Users/medya/.minikube/certs
```

**Comment by medyagh** [comment]
@azhao155

**Comment by medyagh** [comment]
one thing to check is if our Lock is getting activated each time we try to look at the cert

https://github.com/medyagh/minikube/blob/dce38fb331b6172c0c618ad486ac1b60661af687/pkg/util/crypto.go#L158

currentlty we do NOT regerenreate the cert if it exists.  I wonder if we activate the Lock while checking if the cert exists.

**Comment by medyagh** [comment]
we should add debgging to the DockerEnv test if it fails, to give us the timestamp for the certs in home folder and the last time they were changed.

**Comment by azhao155** [comment]
very possible related to this issue: https://github.com/docker/machine/issues/3634

**Comment by medyagh** [comment]
> very possible related to this issue: [docker/machine#3634](https://github.com/docker/machine/issues/3634)

good find that could pretty much be the reason

**Comment by medyagh** [comment]
fixed by https://github.com/kubernetes/minikube/pull/10118
