### ISSUE TITLE
Flake TestFunctional/parallel/ComponentHealth"  bind: address already in use

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10113]
as seen here https://storage.googleapis.com/minikube-builds/logs/10112/b856a47/none_Linux.html
```
	* ==> kube-apiserver [076e3079ac3c] <==
	* Flag --insecure-port has been deprecated, This flag has no effect now and will be removed in v1.24.
	* I0108 18:24:12.793975       1 server.go:632] external host was not specified, using 10.138.0.44
	* I0108 18:24:12.795295       1 server.go:182] Version: v1.20.0
	* Error: failed to create listener: failed to listen on 0.0.0.0:8441: listen tcp 0.0.0.0:8441: bind: address already in use

```

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
