### ISSUE TITLE
Ingress should support HTTP, not just HTTPS

### ISSUE THREAD

**Issue by itamarst** [kubernetes/minikube#1011]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Minikube version** (use `minikube version`):

0.15.0

**Environment**:

Ubuntu 16.04
VirtualBox
Docker: client 1.12, server 1.11

**What happened**:
Ingress add-on is currently exposed as HTTPS service with self-signed certificate. This is annoying: I need to tell my browser that it's OK to use that certificate. It's also unnecessary: minikube is for local testing, not for production use, and a self-signed certificate isn't particularly secure anyway.

**What you expected to happen**:
Support HTTP as well, so I can just point my browser at ingress for testing.

**How to reproduce it** (as minimally and precisely as possible):
1. Enable `ingress` add-on.
2. Add `Ingress` k8s object configured with a `path`.
3. Access the IP address of the Ingress service with browser. It always redirects to HTTPS.

**Comment by Starefossen** [comment]
I have the other way around, I can only access minikube ingress routes over HTTP, any access over HTTPS results in `default backend - 404` from ingress loadbalancer.

**Comment by rothgar** [comment]
This works as intended in minikube 0.21. The ingress controller accepts traffic on port 80 and 443. If the ingress rule has a certificate it will redirect to 443. The default backend has a certificate so if your rule doesn't match a backend it will redirect to the default backend with a self signed certificate.

Please test and close let us know if you have other issues.
