### ISSUE TITLE
Add apple M1 to build scripts & release process

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#10116]
Hopefully simply setting `GOARCH=arm64` is enough, but this needs testing.

**Comment by ilya-zuyev** [comment]
https://github.com/kubernetes/minikube/pull/10202
Waiting for go 1.16 release. darwin/arm64 is not supported in go 1.15

**Comment by ilya-zuyev** [comment]
fixed in https://github.com/kubernetes/minikube/pull/10202
