### ISSUE TITLE
minikube addons enable ingress error:  X Exiting due to MK_ENABLE -- waiting for app.k ubernetes.io/name=ingress-nginx pods: timed out

### ISSUE THREAD

**Issue by ConradKrinock** [kubernetes/minikube#10127]
### (This works successfully on our ubuntu server but not on our Window2019server)

**Steps to reproduce the issue:** 

`minikube addons enable ingress --alsologtostderr` 

* Verifying ingress addon...

X Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.k
ubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

I0111 18:14:47.203519    1212 out.go:185] Setting OutFile to fd 284 ...
I0111 18:14:47.205471    1212 out.go:232] TERM=xterm,COLORTERM=, which probably
does not support color
I0111 18:14:47.205471    1212 out.go:198] Setting ErrFile to fd 288...
I0111 18:14:47.205471    1212 out.go:232] TERM=xterm,COLORTERM=, which probably
does not support color
W0111 18:14:47.211329    1212 root.go:254] Error reading config file at C:\Users
\Administrator\.minikube\config\config.json: open C:\Users\Administrator\.miniku
be\config\config.json: The system cannot find the file specified.
I0111 18:14:47.213282    1212 addons.go:55] Setting ingress=true in profile "min
ikube"
I0111 18:14:47.213282    1212 addons.go:131] Setting addon ingress=true in "mini
kube"
I0111 18:14:47.213282    1212 host.go:66] Checking if "minikube" exists ...
I0111 18:14:47.215234    1212 main.go:119] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0111 18:14:47.266979    1212 main.go:119] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="ac278cff-3abc-4973-8f9d-bd3a072954ba"
CfgFile="C:\\Users\\Administrator\\.minikube\\machines\\minikube\\minikube\\mini
kube.vbox"
SnapFldr="C:\\Users\\Administrator\\.minikube\\machines\\minikube\\minikube\\Sna
pshots"
LogFldr="C:\\Users\\Administrator\\.minikube\\machines\\minikube\\minikube\\Logs
"

### Additional info:

`minikube start`
* minikube v1.15.1 on Microsoft Windows Server 2019 Standard 10.0.17763 Build 17
763
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
* Preparing Kubernetes v1.19.4 on Docker 19.03.13 ...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass, dashboard
* Done! kubectl is now configured to use "minikube" cluster and "default" namesp
ace by default

**Optional: Full output of `minikube logs  command:**
[minikube.logs.txt](https://github.com/kubernetes/minikube/files/5798585/minikube.logs.txt)

**Comment by priyawadhwa** [comment]
Hey @ConradKrinock thanks for opening this issue! This does seem like a bug. Could you provide the output of:

```
kubectl get po -A
```

and

```
kubectl describe deploy ingress-nginx-controller -n kube-system
```

I'm curious to see what the state of the ingress pods is.

**Comment by ConradKrinock** [comment]
OK thanks I'll be able to respond later today.

**Comment by ConradKrinock** [comment]
kubectl get po -A
NAMESPACE              NAME                                        READY   STATUS              RESTARTS   AGE
default                hello-minikube-6ddfcc9757-c4lvb             1/1     Running             3          17d
default                mongo-express-78fcf796b8-kfz2x              0/1     CrashLoopBackOff    1270       18d
default                mongodb-deployment-8f6675bc5-62nmm          1/1     Running             3          18d
default                nginx-conrad-685b84d6d-td8km                1/1     Running             3          20d
kube-system            coredns-f9fd979d6-lghmf                     0/1     Running             5          41d
kube-system            etcd-minikube                               1/1     Running             5          41d
kube-system            ingress-nginx-controller-558664778f-qfxjw   0/1     ContainerCreating   0          14d
kube-system            kube-apiserver-minikube                     1/1     Running             5          41d
kube-system            kube-controller-manager-minikube            1/1     Running             5          41d
kube-system            kube-proxy-tc2bg                            1/1     Running             5          41d
kube-system            kube-scheduler-minikube                     1/1     Running             5          41d
kube-system            storage-provisioner                         0/1     CrashLoopBackOff    6769       41d
kubernetes-dashboard   dashboard-metrics-scraper-c95fcf479-8cmx8   0/1     NodeAffinity        0          14d
kubernetes-dashboard   dashboard-metrics-scraper-c95fcf479-8zd2v   1/1     Running             1          14d
kubernetes-dashboard   dashboard-metrics-scraper-c95fcf479-k2hfx   0/1     NodeAffinity        0          40d
kubernetes-dashboard   dashboard-metrics-scraper-c95fcf479-tkzzm   0/1     NodeAffinity        0          14d
kubernetes-dashboard   kubernetes-dashboard-584f46694c-fkvbq       0/1     NodeAffinity        0          40d
kubernetes-dashboard   kubernetes-dashboard-584f46694c-qg2hk       0/1     NodeAffinity        0          14d
kubernetes-dashboard   kubernetes-dashboard-584f46694c-zmvhr       0/1     CrashLoopBackOff    295        14d

**Comment by ConradKrinock** [comment]
kubectl describe deploy ingress-nginx-controller -n kube-system

Name:                   ingress-nginx-controller
Namespace:              kube-system
CreationTimestamp:      Mon, 11 Jan 2021 16:10:47 -0500
Labels:                 addonmanager.kubernetes.io/mode=Reconcile
                        app.kubernetes.io/component=controller
                        app.kubernetes.io/instance=ingress-nginx
                        app.kubernetes.io/name=ingress-nginx
                        app.kubernetes.io/part-of=kube-system
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app.kubernetes.io/component=controller,app.kubernetes.io/instance=ingress-nginx,app.kubernetes.io/name=ingress-nginx
Replicas:               1 desired | 1 updated | 1 total | 0 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  1 max unavailable, 1 max surge
Pod Template:
  Labels:           addonmanager.kubernetes.io/mode=Reconcile
                    app.kubernetes.io/component=controller
                    app.kubernetes.io/instance=ingress-nginx
                    app.kubernetes.io/name=ingress-nginx
                    gcp-auth-skip-secret=true
  Service Account:  ingress-nginx
  Containers:
   controller:
    Image:       us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2
    Ports:       80/TCP, 443/TCP, 8443/TCP
    Host Ports:  80/TCP, 443/TCP, 0/TCP
    Args:
      /nginx-ingress-controller
      --configmap=$(POD_NAMESPACE)/nginx-load-balancer-conf
      --report-node-internal-ip-address
      --tcp-services-configmap=$(POD_NAMESPACE)/tcp-services
      --udp-services-configmap=$(POD_NAMESPACE)/udp-services
      --validating-webhook=:8443
      --validating-webhook-certificate=/usr/local/certificates/cert
      --validating-webhook-key=/usr/local/certificates/key
    Requests:
      cpu:      100m
      memory:   90Mi
    Liveness:   http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:  http-get http://:10254/healthz delay=10s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAME:        (v1:metadata.name)
      POD_NAMESPACE:   (v1:metadata.namespace)
    Mounts:
      /usr/local/certificates/ from webhook-cert (ro)
  Volumes:
   webhook-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  ingress-nginx-admission
    Optional:    false
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    False   ProgressDeadlineExceeded
OldReplicaSets:  <none>
NewReplicaSet:   ingress-nginx-controller-558664778f (1/1 replicas created)
Events:          <none>

**Comment by AMRITKV88** [comment]
You can try the workaround mentioned by **renich** and **Hongbo-Miao** on this thread #8756. It may resolve your issue.

**Comment by priyawadhwa** [comment]
Hey @ConradKrinock did that resolve your issue? It also looks like your cluster may be ~40 days old based on the output of `kubectl get po -A` -- minikube clusters are typically ephemeral. It may be worth it to delete the cluster and recreate `minikube delete && minikube start`, though this will wipe whatever you currently have on your cluster.

**Comment by spowelljr** [comment]
Hi @ConradKrinock, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by jhadjar** [comment]
Related:

- Issue: https://github.com/kubernetes/minikube/issues/9514
- Pull request [merged]: https://github.com/kubernetes/minikube/pull/9515

Side note: A better behavior would be to be able to pass timeout duration as a parameter instead of 3 minutes or 6 minutes for slow connections or starts. Leave it to the user.

**Comment by vagdevik** [comment]
I had the same issue.

The error disappeared when I have run the same command

```
minikube addons enable ingress
```
again after a minute. 
Then, the ingress was set-up after some time. So, the issue might be due to some network delays, I guess.

**Comment by vhp1360** [comment]
> I had the same issue.
> 
> The error disappeared when I have run the same command
> 
> ```
> minikube addons enable ingress
> ```
> 
> again after a minute. Then, the ingress was set-up after some time. So, the issue might also be due to some network delays, I guess.
Hi,
but it could not be a network issue. I run it on one machine and the 10.96.0.1 is on that machine, please explain what do mean of network issue?
