### ISSUE TITLE
mac M1 minikube start failed - hyperkit

### ISSUE THREAD

**Issue by xiazemin** [kubernetes/minikube#10120]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

 Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  正在删除 hyperkit 中的“minikube”…
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: waiting: Maximum number of retries (60) exceeded

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by priyawadhwa** [comment]
Hey @xiazemin did you try deleting and recreating the cluster?

```
minikube delete
minikube start
```

If that fails, could you provide the output of 
```
minikube start --alsologtostderr
```

**Comment by medyagh** [comment]
till hyperkit add M1 support we should detect this

https://github.com/medyagh/minikube/blob/a278e45dbfd11dc567ba3646453f2b51a07a8b9c/pkg/minikube/registry/drvs/hyperkit/hyperkit.go#L51
