### ISSUE TITLE
Can't enable kube-dns addon in minikube

### ISSUE THREAD

**Issue by codyowl** [kubernetes/minikube#10121]
I keep on getting this error while am trying to enable kube-dns addon for minikube.

1.minikube start 
2.minikube addons enable kube-dns

Error I got :

❌  Exiting due to MK_ENABLE: run callbacks: kubedns is not a valid addon

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

Note : I've been using minikube with docker driver.

**Comment by prasadkatti** [comment]
possible dup of https://github.com/kubernetes/minikube/issues/8949

@codyowl - Check out this comment on the other issue - https://github.com/kubernetes/minikube/issues/8949#issuecomment-689734209

**Comment by prasadkatti** [comment]
The addon was removed here - https://github.com/kubernetes/minikube/pull/3556 almost 2 years back

**Comment by codyowl** [comment]
Thanks for the comments @prasadkatti .I figured it out, the version I'm using does have "coredns" as its default one.Thanks a lot by the way !

**Comment by prasadkatti** [comment]
You are welcome! Feel free to close the issue since you figured it out.
