### ISSUE TITLE
Path for windows version of kubectl is wrong

### ISSUE THREAD

**Issue by justechn** [kubernetes/minikube#1014]
**Minikube version** (use `minikube version`):
minikube version: v0.15.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
does not exist
- **Docker version** (e.g. `docker -v`):
not installed
- **Install tools**:
- **Others**:

**What happened**:

When I tried to start minikube it says
```
download kubectl from:
https://storage.googleapis.com/kubernetes-release/release/v1.5.1/bin/windows/amd64/kubectl
Add kubectl to your system PATH
```

**What you expected to happen**:
the path is wrong because it is missing the .exe on the end of the file

**How to reproduce it** (as minimally and precisely as possible):
remove the kubectl.exe file from your path and start minikube

**Anything else do we need to know**:

**Comment by aaron-prindle** [comment]
Closing, fixed with #1022
