### ISSUE TITLE
Some integration tests are disabled on linux/arm64

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#10144]
Currently some integration tests are skipped when running on arm64.

This issue is to track those and enable it back when blocking issues with dependencies are resolved.

TestDownloadOnlyKic - preloads are not supported for arm64 yet
TestPreload - preloads are not supported for arm64 yet

TestOffline - crio and containerd are not fully supported on arm64
TestAddons - helm addon is not supported yet
TestKVMDriverInstallOrUpdate - kvm is not supported on arm64 yet
functional/validateMySQL - mysql image is not available for arm64

**Comment by sharifelgamal** [comment]
We should only skip the helm addon for Addons test, as opposed to skipping everything.

**Comment by medyagh** [comment]
We still wanna unskip them
@ilya-zuyev
