### ISSUE TITLE
Tools like helm and k9s are not able to access minikube cluster, but other clusters work fine. Also kubectl works fine with minikube.

### ISSUE THREAD

**Issue by Dhua-v** [kubernetes/minikube#10142]
$ minikube version
minikube version: v1.16.0
commit: 9f1e482427589ff8451c4723b6ba53bb9742fbb1-dirty

$ helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-23T02:22:32Z", GoVersion:"go1.15.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

**Steps to reproduce the issue:** 

1. minikube start
2. helm template xyz bla-repo

**Full output of failed command:** 
helm.go:71: invalid configuration: [unable to read client-cert /home/pkv/.minikube/profiles/minikube/client.crt for minikube due to open /home/pkv/.minikube/profiles/minikube/client.crt: permission denied, unable to read client-key /home/pkv/.minikube/profiles/minikube/client.key for minikube due to open /home/pkv/.minikube/profiles/minikube/client.key: permission denied, unable to read certificate-authority /home/pkv/.minikube/ca.crt for minikube due to open /home/pkv/.minikube/ca.crt: permission denied]

I have even tried, 
sudo chmod -R a+rwx  /home/pkv/.minikube/ca.crt; 
ls -l /home/pkv/.minikube/profiles

Still same issue. Why in the world helm and k9s not able to read public files. The error in both is common, hence thinking the issue is in minikube.

 

**Full output of `minikube start` command used, if not already included:**

$ minikube start
😄  minikube v1.16.0 on Ubuntu 20.04
    ▪ KUBECONFIG=/home/pkv/Desktop/bin/kubeconfigs/dev/config-notthere
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Comment by tstromberg** [comment]
Is it possible you are installing k9s or helm via snap? If so, they are sandboxed and unable to access files that were not created by them.

You may be able to workaround this using `minikube start --embed-certs`

**Comment by Dhua-v** [comment]
Hy yes, I always use snap, so is there any flag for snap to provide to disable sandboxing?
Closing the issue as reason is there.
