### ISSUE TITLE
`minikube kubectl --profile` does not switch context

### ISSUE THREAD

**Issue by owenthereal** [kubernetes/minikube#10143]
**Steps to reproduce the issue:** 

1. Provision multiple minikube clusters, e.g. cluster-a & cluster-b
2. Change context to cluster-a with `kubectl config use-context cluster-a`
3. Get namespaces in cluster-b with `minikube kubectl --profile cluster-b -- get ns`, context isn't switched from cluster-a to cluster-b and cluster-a namespaces are shown.

The reason is that https://github.com/kubernetes/minikube/blob/5ce9d99d68a57f833b7af035c384479122479968/cmd/minikube/cmd/kubectl.go#L34-L81 doesn't consider `--profile`.

**Full output of failed command:** 

N/A

**Full output of `minikube start` command used, if not already included:**

N/A

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @owenthereal thank you for reporting this bug. We should be taking profile into account for the `kubectl ` command.

It should be on the easier end to fix. If you, or anyone else, would be interested in taking this issue on, please comment /assign.

**Comment by BLasan** [comment]
@priyawadhwa Ma'am could you please verify this issue?

**Comment by BLasan** [comment]
> @priyawadhwa Ma'am could you please verify this issue?

Starting the implementations
