### ISSUE TITLE
image-repository not respected for cni=calico

### ISSUE THREAD

**Issue by krezovic** [kubernetes/minikube#10156]
**Steps to reproduce the issue:** 

1. minikube start --driver=docker --image-repository=private-registry.net/infrastructure --cni=calico

All manifests, including addons, include the specified registry, except calico deployment and daemonset. They still point to their default images (from docker.io)

**Comment by priyawadhwa** [comment]
Hey @krezovic thanks for opening this issue. This sounds like a bug -- if you or anyone else would be interested in fixing it, I'd be happy to look at a PR. 

The changes would happen in this file:
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cni/calico.go

We would want to add `{{.ImageRepository}}` into the template and pass it in if it is set by the user.

**Comment by BLasan** [comment]
@priyawadhwa I would like to take up this issue.

**Comment by krezovic** [comment]
Not fully fixed. There's still calico/cni and calico/pod2daemon-flexvol on lines 611 and 647, respectively.

**Comment by BLasan** [comment]
> Not fully fixed. There's still calico/cni and calico/pod2daemon-flexvol on lines 611 and 647, respectively.

Thanks for pointing. Will fix this

**Comment by BLasan** [comment]
@priyawadhwa Do we need to change the images used for installation purposes in initcontainers ?

**Comment by BLasan** [comment]
> Not fully fixed. There's still calico/cni and calico/pod2daemon-flexvol on lines 611 and 647, respectively.

I have configured the images to be loaded dynamically according to the repository you passed in cni Deployment & Daemonsets. Those images used in the above line numbers you've pointed out are to install the necessary configurations. (used in initcontainers). I think there's no need of changing those images. @priyawadhwa please correct me if I'm wrong

**Comment by krezovic** [comment]
I can confirm that calico/cni and calico/podman... do not have substituted registry and fail on non-internet-facing machines.
