### ISSUE TITLE
minikube start --driver=none

### ISSUE THREAD

**Issue by lolbuddy** [kubernetes/minikube#10155]
**Steps to reproduce the issue:** 

1. minikube start --driver=none
2. 
2. 
3.

**Full output of failed command:** 

 minikube v1.16.0 on Ubuntu 20.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 20.04.1 LTS
* Preparing Kubernetes v1.20.0 on Docker  ...
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
        panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc000329320)
        /usr/lib/go-1.13/src/text/template/exec.go:170 +0x1b5
panic(0x555f8f790200, 0x555f8fae5e10)
        /usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x555f8f974da0, 0xc0002c9f40, 0x99, 0xc0001ad7c0, 0x2, 0x2, 0x0, 0x555f8fba2a00, 0x555f8f790200)
        /usr/lib/go-1.13/src/reflect/value.go:876 +0x39e
text/template.(*state).evalField(0xc0003292a0, 0x555f8f974da0, 0xc0002c9f40, 0x99, 0x7ffdc197272d, 0xc, 0x555f8fb71aa0, 0xc00059f590, 0xc0003f3570, 0x1, ...)
        /usr/lib/go-1.13/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc0003292a0, 0x555f8f974da0, 0xc0002c9f40, 0x99, 0x555f8f974da0, 0xc0002c9f40, 0x99, 0x555f8fb71aa0, 0xc00059f590, 0xc0003f3560, ...)
        /usr/lib/go-1.13/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc0003292a0, 0x555f8f974da0, 0xc0002c9f40, 0x99, 0xc00059f590, 0xc0003f3570, 0x1, 0x1, 0x555f8f843aa0, 0x555f90a9abb8, ...)
        /usr/lib/go-1.13/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc0003292a0, 0x555f8f974da0, 0xc0002c9f40, 0x99, 0xc00059f560, 0x555f8f843aa0, 0x555f90a9abb8, 0x99, 0xd0, 0x555f8f94cae0, ...)
        /usr/lib/go-1.13/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc0003292a0, 0x555f8f974da0, 0xc0002c9f40, 0x99, 0xc0000d0d20, 0xc0001cb338, 0xc0001cf930, 0xc000329158)
        /usr/lib/go-1.13/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc0003292a0, 0x555f8f974da0, 0xc0002c9f40, 0x99, 0x555f8fb71920, 0xc00059f5c0)
        /usr/lib/go-1.13/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc0003292a0, 0x555f8f974da0, 0xc0002c9f40, 0x99, 0x555f8fb71b60, 0xc00059f530)
        /usr/lib/go-1.13/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc0002c9ec0, 0x555f8fb09520, 0xc0002ab110, 0x555f8f974da0, 0xc0002c9f40, 0x0, 0x0)
        /usr/lib/go-1.13/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
        /usr/lib/go-1.13/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x555f8fb9d8c0, 0xc0001e00f0, 0x0, 0xc0003f3520, 0x1, 0x1, 0xc0002c9e80, 0x0, 0x0, 0x0, ...)
        /build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cli/command/system/info.go:478 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc0001b6780, 0x555f8fb9d8c0, 0xc0001e00f0, 0xc0003f2f50, 0x0, 0x0)
        /build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cli/command/system/info.go:85 +0x343
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc0001b6780, 0xc0000c4e80, 0x0, 0x2, 0x0, 0x0)
        /build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cli/command/system/info.go:52 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001b6780, 0xc000240280, 0x2, 0x2, 0xc0001b6780, 0xc000240280)
        /build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00041af00, 0xc000240270, 0x3, 0x3)
        /build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
main.runDocker(0xc0001e00f0, 0x555f8fb0ba40, 0xc0000ce010)
        /build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x1d3
main.main()
        /build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@lolbuddy could it be possibly because docker is not running on your system ? on none driver, u would need docker to run for the container run time

**Comment by medyagh** [comment]
it seems like minikube could give a better error messge in this case, and let the user know their docker is not running,  if u dont mind lets track this issue here, https://github.com/kubernetes/minikube/issues/10165
