### ISSUE TITLE
minikube start failed

### ISSUE THREAD

**Issue by rameez523** [kubernetes/minikube#10157]
**Steps to reproduce the issue:** 

![image](https://user-images.githubusercontent.com/61797840/104814597-a59b6b00-5831-11eb-8b4b-e017ee5586e8.png)

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by rameez523** [comment]
it got resolved by disabling swap

swapoff -a

**Comment by priyawadhwa** [comment]
Hey @rameez523 glad to hear you were able to resolve this issue. I'm going to go ahead and close it, but feel free to open if you run into more issues or have any questions.
