### ISSUE TITLE
arch linux: Minikube mount fails with /bin/bash: nil: No such file or directory

### ISSUE THREAD

**Issue by rh-dluong** [kubernetes/minikube#10160]
**Steps to reproduce the issue:** 

1. minikube start --driver=podman --container-runtime=cri-o
2. minikube mount "/etc/home-assistant/:/etc/home-assistant/"
3.

**Full output of failed command:** 
📁  Mounting host path /etc/home-assistant/ into VM as /etc/home-assistant/ ...
    ▪ Mount type:   
    ▪ User ID:      docker
    ▪ Group ID:     docker
    ▪ Version:      9p2000.L
    ▪ Message Size: 262144
    ▪ Permissions:  755 (-rwxr-xr-x)
    ▪ Options:      map[]
    ▪ Bind Address: <nil>:45453
🚀  Userspace file server: ufs starting
🛑  Userspace file server is shutdown

❌  Exiting due to GUEST_MOUNT: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=45453,trans=tcp,version=9p2000.L <nil> /etc/home-assistant/" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=45453,trans=tcp,version=9p2000.L <nil> /etc/home-assistant/": Process exited with status 1
stdout:

stderr:
/bin/bash: nil: No such file or directory

**Full output of `minikube start` command used, if not already included:**
😄  minikube v1.16.0 on Arch rolling
✨  Using the podman (experimental) driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating podman container (CPUs=2, Memory=2200MB) ...
🎁  Preparing Kubernetes v1.20.0 on CRI-O 1.19.0 ...
🔗  Configuring CNI (Container Networking Interface) ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by rh-dluong** [comment]
It's on Arch Linux, from past issues, I tried to see if it was a networking issue, I turned off iptables, but it would never actually get anywhere, after 5 min I gave up on it:
```
📁  Mounting host path /etc/openvpn/server/ into VM as /etc/openvpn/server/ ...
    ▪ Mount type:   
    ▪ User ID:      docker
    ▪ Group ID:     docker
    ▪ Version:      9p2000.L
    ▪ Message Size: 262144
    ▪ Permissions:  755 (-rwxr-xr-x)
    ▪ Options:      map[]
    ▪ Bind Address: <nil>:38879
🚀  Userspace file server: ufs starting
🛑  Userspace file server is shutdown
```

I would try to CtrlC escape it and it never actually does, I actually have to close out the window because it's just stuck there:
```
^C🔥  Unmounting /etc/openvpn/server/ ...
```

I'm assuming this is the network that it's trying to use:
```
36: br-69056cbd7419: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:c1:09:70:cc brd ff:ff:ff:ff:ff:ff
    inet 192.168.49.1/24 brd 192.168.49.255 scope global br-69056cbd7419
       valid_lft forever preferred_lft forever
    inet6 fe80::42:c1ff:fe09:70cc/64 scope link 
       valid_lft forever preferred_lft forever
```

I tried using the following iptable rules, but I get that /bin/bash error from earlier, so I'm definitely doing something wrong there:
sudo iptables -A INPUT -i br-69056cbd7419 -j ACCEPT
sudo iptables -A OUTPUT -o br-69056cbd7419 -j ACCEPT

**Comment by medyagh** [comment]
@rh-dluong I am curious if you have this same problem on debian and a different dirver (docker) ? we dont have integration test for arch linux

/triage needs-information
/kind support

**Comment by rh-dluong** [comment]
Hm, I have not, but I don't have a spare machine to test this on unfortunately since this is the setup for my home router.

**Comment by medyagh** [comment]
thanks for updating this @rh-dluong  unfortunately I dont have much experience with arch linux, and we dont test minikube on arch in our integraiton tests, but if github actions allowed arch linux for test fleet would be good if we could test minikube on arch too. meanwhile I will close this issue , feel free to reopen if u have more information

**Comment by aschleck** [comment]
I just hit this on Debian and sort-of of understand why it's happening.

In the original bug report GitHub stripped a crucial `<nil>` because the error was not in backticks.

```
X Exiting due to GUEST_MOUNT: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port
=44763,trans=tcp,version=9p2000.L <nil> /run/pulse" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=26
2144,port=44763,trans=tcp,version=9p2000.L <nil> /run/pulse": Process exited with status 1
```

Tracing through where that nil comes from, it appears that https://github.com/kubernetes/minikube/blob/1562092a9e3b77746785603068a0088837e118a4/cmd/minikube/cmd/mount.go#L113 somehow ends up in the situation where ip is nil without an err. I am having trouble tracing how it ends up in that situation though.
