### ISSUE TITLE
none driver: provide solution message  when docker not running 

### ISSUE THREAD

**Issue by Gopikrishna73** [kubernetes/minikube#10165]
**Steps to reproduce the issue:** 

1.ubuntu@ip-172-31-45-236:~$ minikube dashboard
* The control plane node must be running for this command
  - To start a cluster, run: "minikube start"
ubuntu@ip-172-31-45-236:~$ minikube config set driver docker
! These changes will take effect upon a minikube delete and then a minikube start
ubuntu@ip-172-31-45-236:~$ minikube start
* minikube v1.16.0 on Ubuntu 18.04

! Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "none" driver, which is incompatible with requested "docker" driver.
* Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=none'

ubuntu@ip-172-31-45-236:~$ 'minikube start --driver=none
> ^C
ubuntu@ip-172-31-45-236:~$ minikube start --driver=none
* minikube v1.16.0 on Ubuntu 18.04
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 18.04.5 LTS
* Preparing Kubernetes v1.20.0 on Docker  ...
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
        panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc0001d5348)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:166 +0x1b5
panic(0x5575eb4aed00, 0x5575eb7ecd00)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/runtime/panic.go:522 +0x1b9
reflect.Value.FieldByIndex(0x5575eb691460, 0xc0003e07c0, 0x99, 0xc000058dc0, 0x2, 0x2, 0x0, 0x5575eb8b0380, 0x5575eb4aed00)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/reflect/value.go:852 +0x32b
text/template.(*state).evalField(0xc0001d52c8, 0x5575eb691460, 0xc0003e07c0, 0x99, 0x7fff625d3776, 0xc, 0x5575eb86f480, 0xc000177f20, 0xc000590a50, 0x1, ...)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:604 +0xa59
text/template.(*state).evalFieldChain(0xc0001d52c8, 0x5575eb691460, 0xc0003e07c0, 0x99, 0x5575eb691460, 0xc0003e07c0, 0x99, 0x5575eb86f480, 0xc000177f20, 0xc000590a40, ...)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:554 +0x222
text/template.(*state).evalFieldNode(0xc0001d52c8, 0x5575eb691460, 0xc0003e07c0, 0x99, 0xc000177f20, 0xc000590a50, 0x1, 0x1, 0x5575eb563440, 0x5575ecaa3830, ...)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:518 +0x116
text/template.(*state).evalCommand(0xc0001d52c8, 0x5575eb691460, 0xc0003e07c0, 0x99, 0xc000177e30, 0x5575eb563440, 0x5575ecaa3830, 0x99, 0xc0001d50e0, 0x0, ...)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:456 +0x7aa
text/template.(*state).evalPipeline(0xc0001d52c8, 0x5575eb691460, 0xc0003e07c0, 0x99, 0xc00058f5c0, 0x0, 0xc00057f198, 0x0)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:430 +0x11e
text/template.(*state).walk(0xc0001d52c8, 0x5575eb691460, 0xc0003e07c0, 0x99, 0x5575eb86f300, 0xc0000b63f0)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:254 +0x49e
text/template.(*state).walk(0xc0001d52c8, 0x5575eb691460, 0xc0003e07c0, 0x99, 0x5575eb86f540, 0xc000177cb0)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:262 +0x145
text/template.(*Template).execute(0xc0003e0740, 0x5575eb80f2c0, 0xc0002b2e10, 0x5575eb691460, 0xc0003e07c0, 0x0, 0x0)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:217 +0x1ea
text/template.(*Template).Execute(...)
        /build/docker.io-IpWXdj/docker.io-19.03.6/go/src/text/template/exec.go:200
github.com/docker/cli/cli/command/system.formatInfo(0x5575eb8a92e0, 0xc00030c0f0, 0x0, 0xc000590a00, 0x1, 0x1, 0xc0003e0700, 0x0, 0x0, 0x0, ...)
        /build/docker.io-IpWXdj/docker.io-19.03.6/.gopath/src/github.com/docker/cli/cli/command/system/info.go:478 +0x1f6
github.com/docker/cli/cli/command/system.runInfo(0xc000593b80, 0x5575eb8a92e0, 0xc00030c0f0, 0xc0005903c0, 0x0, 0x0)
        /build/docker.io-IpWXdj/docker.io-19.03.6/.gopath/src/github.com/docker/cli/cli/command/system/info.go:85 +0x344
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc000593b80, 0xc0002487e0, 0x0, 0x2, 0x0, 0x0)
        /build/docker.io-IpWXdj/docker.io-19.03.6/.gopath/src/github.com/docker/cli/cli/command/system/info.go:52 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000593b80, 0xc000358010, 0x2, 0x2, 0xc000593b80, 0xc000358010)
        /build/docker.io-IpWXdj/docker.io-19.03.6/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x467
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003aaf00, 0xc000358000, 0x3, 0x3)
        /build/docker.io-IpWXdj/docker.io-19.03.6/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ee
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /build/docker.io-IpWXdj/docker.io-19.03.6/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
main.runDocker(0xc00030c0f0, 0x5575eb811680, 0xc0000ca010)
        /build/docker.io-IpWXdj/docker.io-19.03.6/.gopath/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x1d5
main.main()
        /build/docker.io-IpWXdj/docker.io-19.03.6/.gopath/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3

*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
Looks similar to: #10083 and #10155

For some reason, these trivial Docker commands are failing:

`docker version --format {{.Server.Version}}`

`docker info --format {{.CgroupDriver}}`

**Comment by afbjorklund** [comment]
That was easy enough to reproduce. Just stop the docker daemon.

```
$ sudo systemctl stop docker.socket
$ docker version --format {{.Server.Version}}

Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
$ docker info --format {{.CgroupDriver}}
panic: reflect: indirection through nil pointer to embedded struct [recovered]
	panic: reflect: indirection through nil pointer to embedded struct

```

**Comment by Gopikrishna73** [comment]
Hi Kubernetes/Minikube,

Thank you for your reply and the issue got resolved and it is working now.

Once again thank you for your support.

Regards,
Gopikrishna

**Comment by medyagh** [comment]
minikube could do a better job checking if Docker is running for "None Driver" and provide a better error

**Comment by hetong07** [comment]
@hetong07 /assign

**Comment by medyagh** [comment]
as noted by @hetong07  this is caused by this line

https://github.com/medyagh/minikube/blob/72443005764661ff12dafedee6c0afed4829b379/pkg/minikube/bootstrapper/bsutil/kubeadm.go#L64

```
	cgroupDriver, err := r.CGroupDriver()
	if err != nil {
		return nil, errors.Wrap(err, "getting cgroup driver")
	}
```


one way to fix this is, we can parse for the error message and if the docker is not run we can return a ErrorType and if it is None Driver, add solution to user that they need to start docker

**Comment by hetong07** [comment]
We can either use ```systemctl status docker``` to check docker status or use a trivial docker command to check docker daemon status, for example ```docker ps```, which will return following message:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Comment by hetong07** [comment]
We can add a check like this 
```
cgroupDriver, err := r.CGroupDriver()
if err != nil {
	if driver.BareMetal(cc.Driver) && r.Name() == "Docker" && strings.Contains(err.Error(), "panic") {
		return nil, errors.Wrap(err, "Docker daemon is not running with None driver")
	}
	return nil, errors.Wrap(err, "getting cgroup driver")
}
```
But eventually when it returns at https://github.com/kubernetes/minikube/blob/a4ee1e07910fc2e9e37ba08a4b203148cbf23507/pkg/minikube/node/start.go#L299-L300
Should I use something like below to give user advice of running docker daemon?
https://github.com/kubernetes/minikube/blob/9d5faff315282f1a5e1a82a3929b1b7598bd6ebc/cmd/minikube/cmd/start.go#L265-L267

**Comment by afbjorklund** [comment]
> we can parse for the error message

You can't really parse the error message, since it panics before even outputting one ? Parsing for "panic" sounds icky.

Since it is the client crashing, it doesn't help if the server is local or remote - so it will affect all types of docker daemons.

**Comment by afbjorklund** [comment]
It **did** fail earlier, though. Just silently:

`Preparing Kubernetes v1.20.0 on Docker ... `

So there _was_ an error, running "docker version"

But the current code is ignoring it, maybe it shouldn't ?

```go
// Version retrieves the current version of this runtime
func (r *Docker) Version() (string, error) {
        // Note: the server daemon has to be running, for this call to return successfully
        c := exec.Command("docker", "version", "--format", "{{.Server.Version}}")
        rr, err := r.Runner.RunCmd(c)
        if err != nil {
                return "", err
        }
        return strings.Split(rr.Stdout.String(), "\n")[0], nil
}
```

**Comment by hetong07** [comment]
@afbjorklund I think parse the error info can work. Look at the info:

```
X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
panic: reflect: indirection through nil pointer to embedded struct

```
The ```X Exiting due to K8S_INSTALL_FAILED``` shows the minikube does not crash, the ```stderr panic...``` info is actually the stderr message captured by minikube.
