### ISSUE TITLE
Unable to download images in mac using minikube on hyperkit

### ISSUE THREAD

**Issue by Yash0182** [kubernetes/minikube#10170]
While downloading docker image, using minikube on hyperkit, getting below error:
Failed to pull image "nginx": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.2:41674->192.168.64.1:53: read: connection refused

I checked the other link:
https://github.com/kubernetes/minikube/issues/4589
but it does not solves the problem

Whereas, while starting minikube, if I does'nt specify the vm driver, it works fine.

**Comment by priyawadhwa** [comment]
Hey @Yash0182 thanks for opening an issue. When you say:

>Whereas, while starting minikube, if I does'nt specify the vm driver, it works fine.

Is that because it is using a different driver?

**Comment by Yash0182** [comment]
Below are the logs, I got when I started minikube with default driver. I guess it took the one that came with DockerForMac.
$ minikube start
😄  minikube v1.16.0 on Darwin 10.13.6
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.20.0 preload ...
    > preloaded-images-k8s-v8-v1....: 491.00 MiB / 491.00 MiB  100.00% 6.90 MiB
🔥  Creating docker container (CPUs=2, Memory=1988MB) ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
===========================================================
These are the logs when I start cluster using hyperkit:

$ minikube start --vm-driver=hyperkit
😄  minikube v1.16.0 on Darwin 10.13.6
✨  Using the hyperkit driver based on user configuration
💾  Downloading driver docker-machine-driver-hyperkit:
    > docker-machine-driver-hyper...: 65 B / 65 B [----------] 100.00% ? p/s 0s
    > docker-machine-driver-hyper...: 11.44 MiB / 11.44 MiB  100.00% 8.77 MiB p

💿  Downloading VM boot image ...
    > minikube-v1.16.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.16.0.iso: 212.62 MiB / 212.62 MiB [ 100.00% 21.22 MiB p/s 10s
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
❗  This VM is having trouble accessing https://k8s.gcr.io

**Comment by sharifelgamal** [comment]
Yes, docker is the default driver for all platforms, which is why not specifying the driver is different from using hyperkit.

If you cannot access GCR, try using a registry mirror.

**Comment by johnmba** [comment]
I had the same issue on arch Linux but I discovered that minikube run a separate docker machine in VM that needs network to download images, so running minikube on proxy by exporting proxy variables to the env like in below:
export HTTP_PROXY=http://<proxy hostname:port>
export HTTPS_PROXY=https://<proxy hostname:port>
export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
Resolved my own issues.
