### ISSUE TITLE
site: add calendar invite link to Triage Meeting 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10173]
on our site, there should be a link to add a calendar invite for triage meeting, or we could direct the users to join a the google group so they receive the invitation on their calendar automatically 
https://minikube.sigs.k8s.io/docs/contrib/triage/

**Comment by uhari03** [comment]
@medyagh Do you have the google group link that you would like to add to the triage page?

**Comment by medyagh** [comment]
yes this group https://groups.google.com/forum/#!forum/minikube-dev
