### ISSUE TITLE
install clean up cron job for ARM64 aws CI machines

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10179]
simmilar to https://github.com/medyagh/minikube/blob/89a8cdc794098f9ba0550fbb5eeb19bc3dd8774d/hack/jenkins/cron/cleanup_and_reboot_Linux.sh
we need to check if there is no job running, if not then prune docker and kill stuck process and reboot

**Comment by sharifelgamal** [comment]
All arm64 integration test jobs automatically install the cleanup cron by default now, including the arm64 ones.
