### ISSUE TITLE
Add Cpu/memory limits on minikube resources 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10185]
for example on mysql test we can specify max cpu and memory to not allow mysql to over eat the resources
https://github.com/medyagh/minikube/blob/89a8cdc794098f9ba0550fbb5eeb19bc3dd8774d/test/integration/testdata/mysql.yaml#L29

we could possibly add limiations to api sever or other things (etcd) in the next iteration

example https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-default-namespace/

**Comment by BLasan** [comment]
@medyagh Basically what you want is to add resource limits for the deployments under test/integrations right?

**Comment by medyagh** [comment]
yes I would like to see absolute limits for all the examples that we deploy in tests (could try by setting very low limits and increase little by little till it passes

**Comment by BLasan** [comment]
> yes I would like to see absolute limits for all the examples that we deploy in tests (could try by setting very low limits and increase little by little till it passes

will check it sir
