### ISSUE TITLE
Add cronjob clean up job for GitHub Action runner hosts (arm machines)

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#10181]
For self-hosted Actions runner machines, add a clean up cron task to delete integrations test remains, similar to https://github.com/medyagh/minikube/blob/89a8cdc794098f9ba0550fbb5eeb19bc3dd8774d/hack/jenkins/cron/cleanup_and_reboot_Linux.sh

**Comment by medyagh** [comment]
we still wanna do this, for next milestone
