### ISSUE TITLE
missing required cgroups: pids

### ISSUE THREAD

**Issue by keppusamyibm** [kubernetes/minikube#10186]
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: missing
CGROUPS_HUGETLB: enabled

stderr:
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR SystemVerification]: missing required cgroups: pids
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@keppusamyibm  do u mind sharing full logs ? minikube start --alsologtostderr ?

and also what version of minikube and what platform ?

**Comment by medyagh** [comment]
This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by keppusamyibm** [comment]
[root@minikube boot]# minikube start --alsologtostderr
I0120 16:35:29.107108    4970 out.go:221] Setting OutFile to fd 1 ...
I0120 16:35:29.107427    4970 out.go:268] TERM=xterm,COLORTERM=, which
probably does not support color
I0120 16:35:29.107442    4970 out.go:234] Setting ErrFile to fd 2...
I0120 16:35:29.107456    4970 out.go:268] TERM=xterm,COLORTERM=, which
probably does not support color
I0120 16:35:29.107810    4970 root.go:280] Updating PATH:
/root/.minikube/bin
I0120 16:35:29.108544    4970 out.go:228] Setting JSON to false
I0120 16:35:29.110621    4970 start.go:104] hostinfo:
{"hostname":"minikube","uptime":2858,"bootTime":1611175671,"procs":162,"os":"linux","platform":"centos","platformFamily":"rhel","platformVersion":"7.9.2009","kernelVersion":"3.10.0-229.el7.x86_64","virtualizationSystem":"","virtualizationRole":"","hostid":"825c8a86-e3d3-4929-8064-e99640569b45"}
I0120 16:35:29.111478    4970 start.go:114] virtualization:
I0120 16:35:29.137316    4970 out.go:119] * minikube v1.16.0 on Centos
7.9.2009
* minikube v1.16.0 on Centos 7.9.2009
I0120 16:35:29.138445    4970 driver.go:303] Setting default libvirt URI to
qemu:///system
I0120 16:35:29.140743    4970 out.go:119] * Using the virtualbox driver
based on user configuration
* Using the virtualbox driver based on user configuration
I0120 16:35:29.140793    4970 start.go:277] selected driver: virtualbox
I0120 16:35:29.140816    4970 start.go:686] validating driver "virtualbox"
against <nil>
I0120 16:35:29.140857    4970 start.go:697] status for virtualbox:
{Installed:false Healthy:false Running:false NeedsImprovement:false
Error:unable to find VBoxManage in $PATH Fix:Install VirtualBox Doc:
https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/}
I0120 16:35:29.139349    4970 notify.go:126] Checking for updates...
I0120 16:35:29.147284    4970 out.go:119]

W0120 16:35:29.148203    4970 out.go:181] * Exiting due to
PROVIDER_VIRTUALBOX_NOT_FOUND: The 'virtualbox' provider was not found:
unable to find VBoxManage in $PATH
* Exiting due to PROVIDER_VIRTUALBOX_NOT_FOUND: The 'virtualbox' provider
was not found: unable to find VBoxManage in $PATH
W0120 16:35:29.149900    4970 out.go:181] * Suggestion: Install VirtualBox
* Suggestion: Install VirtualBox
W0120 16:35:29.150105    4970 out.go:181] * Documentation:
https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/
* Documentation:
https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/
I0120 16:35:29.164078    4970 out.go:119]

[root@minikube boot]#

[root@minikube boot]# minikube version
minikube version: v1.16.0
commit: 9f1e482427589ff8451c4723b6ba53bb9742fbb1
[root@minikube boot]#

Platform : Cent Os 7

**Comment by priyawadhwa** [comment]
Hey @keppusamyibm it looks like you have configuring minikube to run with the `virtualbox` driver, but the `virtualbox` binary is either not installed or not on the $PATH so minikube can't execute it. 

>* Exiting due to PROVIDER_VIRTUALBOX_NOT_FOUND: The 'virtualbox' provider
was not found: unable to find VBoxManage in $PATH

Possible solutions for this:
1. Install virtualbox on your machine
2. Run minikube on docker instead of virtualbox by running `minikube delete && minikube start --driver docker`. Docker is our recommende driver, so I would say this is preferable if you have docker installed.

Please let us know if either of these resolves the issue for you

**Comment by ilya-zuyev** [comment]
@keppusamyibm are you still facing this issue?

**Comment by medyagh** [comment]
Hi @keppusamyibm , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
