### ISSUE TITLE
Add a --network-plugin=cni and rkt integration test

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1019]
We should continue to make sure that both CNI network plugin and rkt container runtime are supported on future versions of minikube and minikube-iso

**Comment by intlabs** [comment]
This would be great, using CNI in minikube is really useful, especially when testing and developing network policy and services using more advanced network primitives. In particular, there have been some regressions recently that have caused some difficulty: notably the lack of `ipset` support, which was added in 1.0.4 (see: https://github.com/kubernetes/minikube/issues/973 and https://github.com/kubernetes/minikube/pull/972 ) but seems to have dropped off with later builds.

**Comment by r2d4** [comment]
Yeah, the regressions were a result of us building our own image and not knowing exactly what kernel modules needed to be included to support various network plugins.  

We've enabled them as we've found them, but we will happily take PRs that enable modules needed by k8s network plugins.

**Comment by intlabs** [comment]
@r2d4 These things happen, building an image from the kernel up ain't easy! I'll try to be a better person/member of the community, and see if we can get some PR's in to help. :)

**Comment by dlorenc** [comment]
Closing as obsolete, we have a cri-o test now.
