### ISSUE TITLE
failed to run minikube after installing minikube_1.17.0-1_amd64.deb

### ISSUE THREAD

**Issue by yasharne** [kubernetes/minikube#10239]
**Steps to reproduce the issue:** 

1. install minikube_1.17.0-1_amd64.deb

**Full output of failed command:** 
```sh
minikube start --alsologtostderr                                                                                                             
minikube: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by minikube)
```

**Optional: Full output of `minikube logs` command:**
<details>
minikube: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by minikube)

</details>
I'm using ubuntu 18.04

**Comment by medyagh** [comment]
Thank you @yasharne for reporting this, this is a known issue we are working on a patch for this, for tracking the updates on this please see https://github.com/kubernetes/minikube/issues/10239 I will close this one to keep the information in one place

**Comment by yasharne** [comment]
Thanks @medyagh you have mentioned this issue instead of the main issue

**Comment by afbjorklund** [comment]
It was supposed to be #10224 but you can use the binaries meanwhile.

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
```
