### ISSUE TITLE
add integration test to test debian package

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10256]
to prevent mistakes like this, https://github.com/kubernetes/minikube/issues/10224
we should add integration test to install our own deb package on debian and verify it is working well.
```
# delete any existing installed minikube
# build the deb package locally
sudo dpkg -i minikube_latest_amd64.deb
# verify the the installed minikube
```

**Comment by afbjorklund** [comment]
And the same for arm64 on a arm64 host, if possible.

**Comment by afbjorklund** [comment]
As well as rpm package on fedora, when available.

**Comment by ilya-zuyev** [comment]
For x86 we probably can just add a verification step to our release job, starting docker debian containers and running dpkg inside

**Comment by afbjorklund** [comment]
I guess the main concern was the arch failures, but there could be other failures with the produced .deb and .rpm wrappers...

**Comment by afbjorklund** [comment]
A shortcut would be to just inspect the architecture:

```console
$ dpkg-deb --showformat '${Architecture}\n' --show out/minikube_1.17.1-0_amd64.deb 
amd64
$ rpm --queryformat '%{ARCH}\n' -q out/minikube-1.17.1-0.x86_64.rpm 
x86_64
```

Just to make sure that _that_ particular issue is fixed ?

**Comment by ilya-zuyev** [comment]
Fixed in https://github.com/kubernetes/minikube/pull/10464
