### ISSUE TITLE
docker-env returns linux export commands if ssh'd from linux to windows

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/minikube#10259]
directly on powershell, docker-env works as expected:
```
PS C:\jenkins\> .\minikube-windows-amd64.exe docker-env
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://127.0.0.1:55002"
$Env:DOCKER_CERT_PATH = "C:\Users\jenkins\.minikube\certs"
$Env:MINIKUBE_ACTIVE_DOCKERD = "minikube"
# To point your shell to minikube's docker-daemon, run:
# & minikube -p minikube docker-env | Invoke-Expression
```

but if you ssh into a windows machine from a linux machine, minikube will return linux export commands instead of the appropriate powershell commands:

```
jenkins@WINDOWS-SERVER- >powershell.exe -NoProfile -NonInteractive ./minikube-
windows-amd64.exe docker-env
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://127.0.0.1:55002"
export DOCKER_CERT_PATH="C:\Users\jenkins\.minikube\certs"
export MINIKUBE_ACTIVE_DOCKERD="minikube"

# To point your shell to minikube's docker-daemon, run:
# eval $(minikube -p minikube docker-env)
```

**Comment by afbjorklund** [comment]
Do you still have $SHELL set ?

**Comment by medyagh** [comment]
we might wanna use this trick https://devblogs.microsoft.com/scripting/powertip-determine-if-running-in-powershell-console/

**Comment by sharifelgamal** [comment]
> Do you still have $SHELL set ? If so, libmachine will use that as your preference.

SHELL is set to `c:\windows\system32\cmd.exe`

**Comment by sharifelgamal** [comment]
This is *mostly* fixed, but probably doesn't account for the SHELL being `cmd.exe` instead of just `cmd`.

**Comment by sharifelgamal** [comment]
This is fixed.
