### ISSUE TITLE
Test image registry connectivity should also ignore scheme prefixed proxy

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes/minikube#10253]
https://github.com/kubernetes/minikube/blob/b1ccf54f8327aa0dc5421f92f49af057e8e9ebee/pkg/minikube/node/start.go#L498-L501

![image](https://user-images.githubusercontent.com/14567045/105714869-db3e0380-5f57-11eb-9c59-ba729b70841c.png)

Could extract a util function from #8885

By the way, I am wondering if we can convert localhost to host machine IP? Or add a flag to replace localhost?

something like: `minikube start --host-ip=$(nmcli -g ip4.address dev show eth0)`

**Comment by sharifelgamal** [comment]
I believe you can set the DOCKER_HOST environment variable and we will honor that IP address instead of localhost.

**Comment by spowelljr** [comment]
Hi @lingsamuel, you haven't responded to @sharifelgamal's suggestion, so I'm going to close this issue. However, if you try his suggestion and it doesn't work, feel free to reopen the issue, thanks!
