### ISSUE TITLE
DEB_REVISION is not propagated into .deb metadata

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#10264]
> Are you mentioning the versions reported by `apt`/`dpkg`, or the one reported by `minikube version`?

The former -- the version info in the `.deb` package metadata.

A quick check identifies the issue here: https://github.com/kubernetes/minikube/blob/master/Makefile#L478

That should be `sed -E -i 's/--VERSION--/'$(DEB_VERSION)-$(DEB_REVISION)'/g' ...`

_Originally posted by @mgabeler-lee-6rs in https://github.com/kubernetes/minikube/issues/10224#issuecomment-767185001_

**Comment by afbjorklund** [comment]
We never had a revision before, so I guess it wasn't in the "template" fields. (missing is the same as 0)

```
Package: minikube
Version: --VERSION--
Section: base
Priority: optional
```

It still seems hard-coded (as zero) in the rpm template, so need to add a parameter for that one too...

```
Name: minikube
Version: --VERSION--
Release: 0
Summary: Run Kubernetes locally
```

**Comment by afbjorklund** [comment]
You'll notice that if they can name something differently, they _will_ do so... Potatoh, potahto.
