### ISSUE TITLE
Flake: TestMultiNode/serial/RestartMultiNode	

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10272]
This test flakes 

example:
https://storage.googleapis.com/minikube-builds/logs/10270/7e9d58c/VirtualBox_Linux.html

**Comment by jiefenghe** [comment]
did some initial investigation, this is what I found so far:
1. I manually run the steps locally, and cannot reproduce. 
2. The failure has nothing to do with the third node. If I only have `validateMultiNodeStart`, `validateStopMultiNodeCluster` and `validateRestartMultiNodeCluster` in the test set. The integration test will still fail.
3. The test is always failing in my linux machine, so it's not flaky. Maybe it's related to some setup.

**Comment by jiefenghe** [comment]
getting more familiar with running test, noticed that my previous debugging experience was not correct...
Ran `make integration -e TEST_ARGS="-test.run TestMultiNode/serial --profile=minikube -cleanup=false"` and compared it with my manual run logs. I noticed that the test failed because the restart step didn't wait long enough, the second node needs more time to be ready.

In my manual restart, I noticed that the kubeadmin waited for the the second Node to be ready.
```
I0203 17:29:54.845903 1514561 command_runner.go:123] ! error execution phase kubelet-start: a Node with name "jiefeng-m02" and status "Ready" already exists in the cluster. You must delete the existing Node or change the name of this new joining Node
...
I0203 17:30:28.214603 1514561 kubeadm.go:725] still waiting for the worker node to register with the api server
...
I0203 17:31:00.489413 1514561 kubeadm.go:709] JoinCluster complete in 1m17.371577602s
...
```
But in the test run, there isn't such error and waiting.
```
I0203 17:29:27.311869 1509398 ssh_runner.go:189] Completed: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm join control-plane.minikube.internal:8443 --token 5mc5n1.asucr3x38yi5ghig     --discovery-token-ca-cert-hash sha256:542e36143fcd8f49ce44fd4a4e315d5392e442ff899ee7581ffb051237dd1fe2 --ignore-preflight-errors=all --node-name=minikube-m02": (5.904041328s)
I0203 17:29:27.311884 1509398 ssh_runner.go:149] Run: /bin/bash -c "sudo systemctl daemon-reload && sudo systemctl enable kubelet && sudo systemctl start kubelet"
I0203 17:29:27.459313 1509398 kubeadm.go:709] JoinCluster complete in 17.564997413s
```

**Comment by jiefenghe** [comment]
in the test, we used to sleep 45 seconds until the Node is ready https://github.com/kubernetes/minikube/commit/fc8110f9c8685dc34ad208a7fcd897fc7e196326

**Comment by sharifelgamal** [comment]
We can try opening up a PR with the sleep reintroduced and see if that helps at all.

**Comment by medyagh** [comment]
> We can try opening up a PR with the sleep reintroduced and see if that helps at all.

@jiefenghe 
the better way is to ensure our --wait=all works on multinode without us needing to add arbitary timeouts in the test

**Comment by jiefenghe** [comment]
> We can try opening up a PR with the sleep reintroduced and see if that helps at all.

Adding a sleep time do make the test pass. I'll look into @medyagh's suggestion to ensure the wait flag is enforced.
