### ISSUE TITLE
Restore BUILD_IMAGE value to 'kube-cross'

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#10276]
https://github.com/kubernetes/minikube/pull/10202 changed default BUILD_IMAGE value from `us.gcr.io/k8s-artifacts-prod/build-image/kube-cross:v$(GO_VERSION)-1` to `golang:1.16beta1-buster` to be able to build for darwin/arm64

We need to return back to `kube-cross` when it supports go 1.16

**Comment by medyagh** [comment]
as part of this task I recommend updating go.mod to 1.16 too so we can start using the go embed instead of go-bindata
