### ISSUE TITLE
! This VM is having trouble accessing https://k8s.gcr.io (different than reported so far)

### ISSUE THREAD

**Issue by ryzior** [kubernetes/minikube#10294]
Issue fixed:
Switching to a new VSwitch fixed the issue (external one connected to a physical eth network card).
but leaving this description in case someone has similar issue in the future.

this is Windows 10 pro setup with Hyper-V

```
minikube config view
- disk-size: 200GB
- driver: hyperv
- memory: 16384

minikube version
minikube version: v1.17.0
commit: 7e8b5a89575945ba8f8246bfe547178c1a995198

minikube ip
172.27.162.122

minikube start
* minikube v1.17.0 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing hyperv VM for "minikube" ...
! This VM is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: 
                                           https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.20.2 on Docker 20.10.2...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass

! C:\bin\terraform\kubectl.exe is version 1.17.4, which may have incompatibilites with Kubernetes 1.20.2.
  - Want kubectl v1.20.2? Try 'minikube kubectl -- get pods -A'
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

minikube kubectl -- get pods -A
NAMESPACE     NAME                                              READY   STATUS              RESTARTS   AGE
cf-operator   cf-operator-pre-delete-hook-m2q8c                 0/1     ContainerCreating   0          9h
cf-operator   cf-operator-quarks-746d74dc8b-btccl               0/1     ImagePullBackOff    0          9h
cf-operator   cf-operator-quarks-job-5985988b5c-q7zt9           0/1     ErrImagePull        0          9h
cf-operator   cf-operator-quarks-secret-b8b44bbc8-fpfwf         0/1     ImagePullBackOff    0          9h
cf-operator   cf-operator-quarks-statefulset-7cc9d55876-9tts5   0/1     ImagePullBackOff    0          9h
kube-system   coredns-74ff55c5b-wdhbs                           1/1     Running             1          9h
kube-system   etcd-minikube                                     1/1     Running             0          95s
kube-system   kube-apiserver-minikube                           1/1     Running             0          85s
kube-system   kube-controller-manager-minikube                  1/1     Running             1          9h
kube-system   kube-proxy-ghhwr                                  1/1     Running             1          9h
kube-system   kube-scheduler-minikube                           1/1     Running             1          9h
kube-system   storage-provisioner                               1/1     Running             1          9h
```

I have already spent some time troubleshooting this , trying to follow many suggestions from here and other sites.
I have a standard issue with external DNS queries, these queries are targetted into the Default Virtual Switch (172.27.160.1):
```
  Warning  Failed       9h                     kubelet, minikube  Failed to pull image "ghcr.io/cloudfoundry-incubator/quarks-job:v1.0.213": rpc error: code = Unknown desc = Error response from daemon: Get https://ghcr.io/v2/: dial tcp: lookup ghcr.io on 172.27.160.1:53: read udp 172.27.163.210:58796->172.27.160.1:53: i/o timeout
  Warning  Failed       9h                     kubelet, minikube  Failed to pull image "ghcr.io/cloudfoundry-incubator/quarks-job:v1.0.213": rpc error: code = Unknown desc = Error response from daemon: Get https://ghcr.io/v2/: dial tcp: lookup ghcr.io on 172.27.160.1:53: read udp 172.27.163.210:57315->172.27.160.1:53: i/o timeout
  Warning  Failed       9h (x3 over 9h)        kubelet, minikube  Error: ErrImagePull
```
I had identical issue using CRC (CodeReady Containers which are minikube like but for openshift) and it was easy to overcome by puttin nameserver option in the setup.
So I tried to login to the minikube (ssh) and modify /etc/resolv.conf with my default DNS server and google's one (8.8.8.8) and it turned out it started working (but only for a while , then resolv.conf got fixed by some automated config drift process).

I checked VSwitch settings, there is a DNS field filled with IP: 172.27.168.97 , I have now no idea what is this IP but I put google's dns ip instead (on top of previous one) but nothing changed. I switched off windows firewall (as suggested somewhere - no help) even created a default rule for udp:53 just to make sure it does no problem in the future.

Every time I put some external dns into resolv.conf and kill failed pod it is recovering and sometimes it happens it gets the image before dns name gets cleared from the minikube vm resolv.conf file.

So it seems the issues is somewhere in the Vswitch->external connection. Maybe I need to set it up differently (no requirements for this part in the docs) or there should be some option to get it overriden , because relying on it is a bad idea especially the trafic is able to get out via this router as long as the DNS IP is different than the vswitch IP.

I have neither any proxy nor a vpn configured (in that case also overriden dns IP would not work if I had one configured right?).
Currently cannot switch back to virtualbox to check because I need HyperV for CRC to be runnig (which disables vbox virtualization engine to fix it reboot needed - it's a mess). 

Maybe there is an option to override the DNS setup permanently which would fix the issue like on CRC ?
regards

Addendum:
DNS IP on the Default Switch is set by CRC :
```
INFO Adding [DNS IP from nameserver option] as nameserver to the instance ...
INFO Will run as admin: add dns server address to interface vEthernet (Default Switch)
INFO Check internal and public DNS query ...
INFO Check DNS query from host ...
```
Checking now another option with a different VSwitch

Switching to a new VSwitch fixed the issue (external one connected to a physical eth network card).

**Comment by ilya-zuyev** [comment]
@ryzior Please try to restart minikube after updating /etc/resolv.conf
