### ISSUE TITLE
minikube addons enable ingress timed out waiting for the condition

### ISSUE THREAD

**Issue by adithyak21** [kubernetes/minikube#10296]
**Steps to reproduce the issue:** 

1.minikube start --driver=hyperv
2. minikube addons enable ingress  

**Full output of failed command:** 

X Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@adithyak21 do you still have this issue with latest version of minikube ? do u mind sharing the logs ?

minikube logs ?

**Comment by prezha** [comment]
hey @adithyak21 – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:
    * Whether the issue occurs with the latest minikube release
    * The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.
    * The full output of minikube logs

    Thank you for sharing your experience!

/close
