### ISSUE TITLE
Metallb addon is not setting the IP range

### ISSUE THREAD

**Issue by seguidor777** [kubernetes/minikube#10307]
Hi,

I'm trying to use the metallb addon and I'm following [this guide](https://medium.com/faun/metallb-configuration-in-minikube-to-enable-kubernetes-service-of-type-loadbalancer-9559739787df) about how to install it and configure it.
After I add the first and end IPs (192.168.49.10, 192.168.49.30) and I query the configmap, the addresses list appear empty.
And I have to edit the configmap and add them manually, can you please help me so I can set the values from the `minikube addons configure metallb` command? I actually have a script that bootstraps minikube with all of its addons and configs

**Comment by seguidor777** [comment]
I'm using this patch as a workaround `kubectl patch configmap config -n metallb-system -p '{"data":{"config": "address-pools:\n- name: default\n  protocol: layer2\n  addresses:\n  - 192.168.49.10-192.168.49.20"}}'`

**Comment by sharifelgamal** [comment]
This seems to be a bug in the `minikube addons configure metallb` command, I can definitely reproduce it locally.

**Comment by tonejito** [comment]
If it helps anyone, I couldn't configure the addon in a script with this:

```bash
echo -e "${METALLB_IP_START}\n${METALLB_IP_END}\n" | \
minikube addons configure metallb --profile ${MINIKUBE_PROFILE} || true
```

I ended up applying a revised version of the ConfigMap:

```bash
minikube addons enable metallb
sleep 10

# Patch MetalLB config with updated IP address range
kubectl apply -f - -n metallb-system << EOF
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - ${METALLB_IP_START}-${METALLB_IP_END}
EOF
```

I put a wait command to be sure that the components are deployed correctly with the new configuration:

```bash
sleep 5

NAMESPACE=metallb-system
APP=metallb
for COMPONENT in controller speaker
do
  kubectl wait --for condition=ready pod -l app=${APP} -l component=${COMPONENT} -n ${NAMESPACE} --timeout=${TIMEOUT}
done
```
