### ISSUE TITLE
minikube is not starting when not providing an IP address for ssh driver

### ISSUE THREAD

**Issue by hackcoderr** [kubernetes/minikube#10308]
**Steps to reproduce the issue:** 

C:\Program Files\Kubernetes\Minikube>minikube start --driver=ssh
* minikube v1.17.1 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the ssh driver based on user configuration
* Starting control plane node minikube in cluster minikube
! StartHost failed, but will try again: config: please provide an IP address
* Failed to start ssh bare metal machine. Running "minikube delete" may fix it: config: please provide an IP address

X Exiting due to GUEST_PROVISION: Failed to start host: config: please provide an IP address

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
Same as #10266, can we provide some better driver documentation or make it more clear somehow ?

https://minikube.sigs.k8s.io/docs/drivers/ssh/

When you supply your own VM, you _will_ need to provide the connection parameters for it (at a minimum, the IP)

Currently there are also some issues with the default SSH keys, so you need to provide those explicitly: https://github.com/kubernetes/minikube/issues/10289#issuecomment-769212722

**Comment by hackcoderr** [comment]
thank you so much for helping me.
