### ISSUE TITLE
Minikube does not start on Windows10

### ISSUE THREAD

**Issue by grebenisan** [kubernetes/minikube#10312]
minikube start --vm-driver="hyperv" --hyperv-virtual-switch="minikube"
**Steps to reproduce the issue:** 

1.execue this command from the PowerShell running as Admin:
minikube start --vm-driver="hyperv" --hyperv-virtual-switch="minikube"

the output of the command is:

* minikube v1.17.1 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. Running "minikube delete" may fix it: provision: IP not found

X Exiting due to GUEST_PROVISION: Failed to start host: provision: IP not found
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by spowelljr** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The full output of the command you are using by adding --alsologtostderr -v=8 for example

```
$ minikube start --alsologtostderr -v=8
```
- Also the full the output of the
```
$ minikube logs
```
This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
