### ISSUE TITLE
running minikube.exe in WSL looks for home in C:\...

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10311]
when minikube.exe runs in Powershell it will create a MINIKUBE_HOME in C:\Program ...

but when the same binary is called in WSL (windows sub linux) it looks for minikube home in linux Path ~/.minikube 
this causes confusion ! 

for that reason we need to either, not allow running .exe binary in WSL and make suer make a choice of downloading Linux binary on WSL or .exe binary needs to do the right thing if it is run in WSL

I suggest as a start we disallow running the .exe binary WSL (unless --force is applied) 

as seen in https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/338

**Comment by hetong07** [comment]
1. Where to check this scenario
We have to make this check before any command is executed, so it seems the check should be put in this function https://github.com/kubernetes/minikube/blob/da9e1819aec5f316077616b2660a19e2195a02ac/cmd/minikube/main.go#L58.

2. How to check this scenario
We can use 
```
if filepath.Ext(os.Args[0]) == '.ext' && driver.IsMicrosoftWSL():
  exit.Advice(reason.WSLEXEConflict, "Cannot run windows binary inside WSL") //better name needed
```
and in https://github.com/kubernetes/minikube/blob/9d5faff315282f1a5e1a82a3929b1b7598bd6ebc/pkg/minikube/reason/reason.go#L74
add a new reason
```
WSLEXEConflict = = Kind{ID: "WSL_EXE_CONFLICT", ExitCode: xxxx, Style: style.Conflict} //better name needed
```

**Comment by hetong07** [comment]
Experiment result:
```
$:/mnt/d/tonghe$ ./minikube-windows-amd64.exe -v 1 --alsologtostderr
I0131 12:27:14.065210   16456 out.go:229] Setting OutFile to fd 96 ...
I0131 12:27:14.067210   16456 out.go:242] Setting ErrFile to fd 100...
I0131 12:27:14.067210   16456 main.go:81] running windows binary inside WSL is not allowed
I0131 12:27:14.072583   16456 out.go:119]

W0131 12:27:14.072583   16456 out.go:181] ❌  Exiting due to WSL_EXE_CONFLICT: Cannot run windows binary inside WSL.
❌  Exiting due to WSL_EXE_CONFLICT: Cannot run windows binary inside WSL.
I0131 12:27:14.077581   16456 out.go:119]
```

**Comment by medyagh** [comment]
@hetong07 that sounds like a good idea !

we could also tell users where to download linux binaries
https://minikube.sigs.k8s.io/docs/start/ and also tell them if they still wanna run .exe binary in linux they should pass --force.

**Comment by hetong07** [comment]
```
$: ./minikube-windows-amd64.exe start -v 1 --alsologtostderr --dry-run
W0202 23:24:55.708303   18132 out.go:181] ❌  Exiting due to WRONG_BINARY: Cannot run Windows binary inside WSL, please download linux binary from https://minikube.sigs.k8s.io/docs/start/. Or you can use '--force' to force execution which would be at your own risk.
❌  Exiting due to WRONG_BINARY: Cannot run Windows binary inside WSL, please download linux binary from https://minikube.sigs.k8s.io/docs/start/. Or you can use '--force' to force execution which would be at your own risk.
```

```
./minikube-windows-amd64.exe start -v 1 --alsologtostderr --dry-run --force
I0202 23:26:48.564699   21768 out.go:229] Setting OutFile to fd 96 ...
I0202 23:26:48.565697   21768 out.go:242] Setting ErrFile to fd 100...
I0202 23:26:48.577731   21768 out.go:236] Setting JSON to false
......
I0202 23:26:50.199145   21768 out.go:119] 🌵  dry-run validation complete!
```
