### ISSUE TITLE
Helm deployed in Minikube Error : Failing init helm-chart: Unable to connect to the server: dial tcp 192.168.49.2:8443: i/o timeout

### ISSUE THREAD

**Issue by DulshanRD** [kubernetes/minikube#10316]
**Steps to reproduce the issue:** 

I have OSM in my Azure VM and minikube is installed in that VM and attached minkube cluster to the OSM

1. curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
 sudo install minikube-linux-amd64 /usr/local/bin/minikube

2. minikube start

3. kubectl create serviceaccount tiller --namespace kube-system

4. Create a tiller-clusterrolebinding.yaml file with the following contents:

                kind: ClusterRoleBinding
                apiVersion: rbac.authorization.k8s.io/v1beta1
                metadata:
                  name: tiller-clusterrolebinding
                subjects:
                - kind: ServiceAccount
                  name: tiller
                  namespace: kube-system
                roleRef:
                  kind: ClusterRole
                  name: cluster-admin
                  apiGroup: ""

5. kubectl create -f tiller-clusterrolebinding.yaml

6.  helm init --service-account tiller --upgrade

7.  Now in OSM Dashboard when I navigate to K8 Cluster; there is an error saying " Failing init helm-chart: Unable to connect to the server: dial tcp 192.168.49.2:8443: i/o timeout"

8. Full Error :  

                {
	              "_id": "1a4df38f-aef5-4c14-a9a1-cef798f52ebc",
	              "name": "minikube",
	              "namespace": "kube-system",
	              "schema_version": "1.11",
	              "_admin": {
		              "operations": [
			              {
				              "lcmOperationType": "create",
				              "operationParams": null,
				              "worker": null,
				              "operationState": "FAILED",
				              "startTime": 1611990889.015983,
				              "detailed-status": "Failing init juju-bundle: b'ERROR ensuring k8s credential \"85d6f588\" 
                                                 with RBAC setup: ensuring cluster role \"juju-credential-85d6f588\" in namespace \"kube-
                                                 system\": Get https://192.168.49.2:8443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-
                                                 credential-85d6f588: dial tcp 192.168.49.2:8443: i/o timeout\\n';Failing init helm-chart: Unable 
                                                 to connect to the server: dial tcp 192.168.49.2:8443: i/o timeout",
				              "statusEnteredTime": 1611990889.015983
			              }
		              ],
		              "projects_write": [
			              "c07581a8-b058-4090-b89f-784867fb8734"
		              ],
		              "created": 1611990889.0159528,
		              "juju_bundle_repos": [],
		              "modified": 1611991039.2912538,
		              "current_operation": null,
		              "projects_read": [
			              "c07581a8-b058-4090-b89f-784867fb8734"
		              ],
		              "helm_chart_repos": [
			              "22e35d0b-ca0d-46b6-b21f-044d4f32ab16"
		              ],
		              "juju-bundle": {
			              "operationalState": "ERROR",
			               "error_msg": "b'ERROR ensuring k8s credential \"85d6f588\" with RBAC setup: ensuring cluster role 
                                            \"juju-credential-85d6f588\" in namespace \"kube-system\": Get 
                                            https://192.168.49.2:8443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-credential-85d6f588: 
                                            dial tcp 192.168.49.2:8443: i/o timeout\\n'",
			              "id": null
		              },
		              "operationalState": "ERROR",
		              "detailed-status": "Failing init juju-bundle: b'ERROR ensuring k8s credential \"85d6f588\" with RBAC setup: 
                                ensuring cluster role \"juju-credential-85d6f588\" in namespace \"kube-system\": 
                                Get https://192.168.49.2:8443/apis/rbac.authorization.k8s.io/v1/clusterroles/juju-credential-85d6f588: 
                                dial tcp 192.168.49.2:8443: i/o timeout\\n';Failing init helm-chart: Unable to connect to the server: dial tcp 
                                 192.168.49.2:8443: i/o timeout",
		              "helm-chart": {
			              "operationalState": "ERROR",
			              "error_msg": "Unable to connect to the server: dial tcp 192.168.49.2:8443: i/o timeout",
			              "id": null
		              }
	              },
	              "k8s_version": "1.20.2",
	              "credentials": {
		              "kind": "Config",
		              "preferences": {},
		              "contexts": [
			              {
				              "name": "minikube",
				              "context": {
					              "cluster": "minikube",
					              "namespace": "default",
					              "extensions": [
						              {
							              "name": "context_info",
							              "extension": {
								              "last-update": "Fri, 29 Jan 2021 07:20:54 UTC",
								              "version": "v1.17.1",
								              "provider": "minikube.sigs.k8s.io"
							              }
						              }
					              ],
					              "user": "minikube"
				              }
			              }
		              ],
		              "apiVersion": "v1",
		              "current-context": "minikube",
		              "clusters": [
			              {
				              "cluster": {
					              "certificate-authority-data": "L....",
					              "extensions": [
						              {
							              "name": "cluster_info",
							              "extension": {
								              "last-update": "Fri, 29 Jan 2021 07:20:54 UTC",
								              "version": "v1.17.1",
								              "provider": "minikube.sigs.k8s.io"
							              }
						              }
					              ],
					              "server": "https://192.168.49.2:8443"
				              },
				              "name": "minikube"
			              }
		              ],
		              "users": [
			              {
				              "name": "minikube",
				              "user": {
					              "client-certificate-data": "L......"
                           

**Full output of failed command:** 

<img width="1440" alt="Screenshot 2021-01-30 at 13 28 18" src="https://user-images.githubusercontent.com/78251191/106350929-8c4cf100-62fe-11eb-9543-ccb4bd99cbab.png">

<img width="659" alt="Screenshot 2021-01-30 at 13 30 40" src="https://user-images.githubusercontent.com/78251191/106350969-e6e64d00-62fe-11eb-83e7-ccad467c6a13.png">

<img width="659" alt="Screenshot 2021-01-30 at 13 31 21" src="https://user-images.githubusercontent.com/78251191/106350971-e8b01080-62fe-11eb-8ee9-b697c30f326f.png">

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
[minikube logs.docx](https://github.com/kubernetes/minikube/files/5897575/minikube.logs.docx)

What can I do to resolve the Issue with at least Helm init in Kubernetes mentioned in the Error.

<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @DulshanRD thanks for opening this issue. I'm not super familiar with helm, but it seems like you are installing tiller yourself?

I believe we have an addon in minikube that you can try, perhaps that will work:

```
minikube delete
minikube start
minikube addons enable helm-tiller
```

Please let us know if that works better for you!

**Comment by medyagh** [comment]
Hi @DulshanRD c, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
