### ISSUE TITLE
delete --purge --all: open .minikube/logs/audit.json: no such file or directory

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#10324]
**Steps to reproduce the issue:** 

1. Install minikube v1.17.1
1. Run `minikube delete --purge --all` 

If you do not have a new profile created, you will see an error such as:

```
🔥  Successfully deleted all profiles
💀  Successfully purged minikube directory located at - [/usr/local/google/home/tstromberg/.minikube]
E0201 09:02:33.689733  567894 audit.go:59] unable to open /usr/local/google/home/tstromberg/.minikube/logs/audit.json: open /usr/local/google/home/tstromberg/.minikube/logs/audit.json: no such file or directory
```

Note: You may need to run the delete command twice, to have an empty directory, in order to duplicate this.

**Comment by tstromberg** [comment]
I would suggest making this error message a warning instead.

**Comment by spowelljr** [comment]
In-progress
