### ISSUE TITLE
NFS mounts across all drivers

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1033]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

The host filesystem mounting across drivers is inconsistent across drivers.  This leads to permission and performance problems.  

I propose that we add a NFS mount option configurable through a flag or command to share a host folder with the minikube VM.  Some users have been doing this manually, and found that it works well.  We can set it up similar to how its done in the xhyve driver [1].  

[1] https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L912-L947

**Comment by aaron-prindle** [comment]
An NFS client has been added inside of the host ISO but there is issues running/bundling an NFS server on all platforms.  For this reason, I have decided to use 9p as the official cross-platform solution.  The PR for the 9p solution can be found here:
#1066 
For now it is not run automatically on `minikube start` but if you checkout this PR you can run:
`minikube mount /directory/to/mount` and it will startup a 9p server and run the mount command in the VM for you automatically

**Comment by aaron-prindle** [comment]
Closing.  We have decided to use a 9p mounting solution.  `minikube mount /path/to/dir/to/mount` allows users to mount files into minikube across all platforms and the path is user configurable and can be modified during a session.

**Comment by tony-kerz** [comment]
can this facility be used to run an `nfs` type `PersistentVolume` in minikube?

i see the doc indicates only support for `hostPath` type, but i'm currently trying to identify strategies to mirror an `nfs` type deploy in minikube...
