### ISSUE TITLE
Cannot install minikube on Windows / Docker : Error dialing TCP: dial tcp 127.0.0.1:49204: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by noelwelsh** [kubernetes/minikube#10342]
I'm trying to install minikube on Windows 10 Home (10.0.19041 Build 19041) with Docker Desktop installed. The installation consistently fails at the `minikube start` command. The issue is that minikube cannot connect to the running docker instance. I have turned off the Microsoft Defender Firewall and closed my work VPN (CheckPoint) and the problem still persists.

**Steps to reproduce the issue:** 

1. minikube delete --all
2.  minikube start --alsologtostderr -v=5 2>minikube-err.txt

**Full output of failed command:** 
😄  minikube v1.17.1 on Microsoft Windows 10 Home 10.0.19041 Build 19041
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🏃  Updating the running docker "minikube" container ...

**Full output of `minikube start` command used, if not already included:**

The logs saved in `minikube-err.txt` are in [a gist](https://gist.github.com/noelwelsh/22267c5c6347855f06b7e6ce8d0bb4ef).

**Other**

I tried to ssh to the same host and post as minikube:

```
> ssh  127.0.0.1 -p 49208
ssh: connect to host 127.0.0.1 port 49208: Connection refused
```

TIA!

**Comment by omjadas** [comment]
Also experiencing the same issue on Windows 10 with the Docker driver

**Comment by priyawadhwa** [comment]
Hey @noelwelsh thanks for opening this issue. Looks like the failing error is:

```
W0202 13:05:54.378261    6584 out.go:181] ÔØî  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: 
NewSession: new client: new client: dial tcp 127.0.0.1:49208: connectex: No connection could be made because the target machine 
actively refused it.
```

which seems similar to https://github.com/kubernetes/minikube/issues/7549. Based on https://github.com/kubernetes/minikube/issues/7549#issuecomment-611595010 looks like it is an issue with your firewall. Unfortunately, I'm not sure what more you can do besides turning it off since I'm not very familiar with Windows, but perhaps that thread will have something useful.

**Comment by ffroliva** [comment]
I am also facing this issue.

**Comment by sharifelgamal** [comment]
We have separate checks to make sure there is enough disk space dedicated to docker and will generally error out with a special message if there isn't enough space.

We have made a bunch of changes to the docker driver on windows in the past few months, so this issue might not happen as frequently or, hopefully, at all.
