### ISSUE TITLE
minikube unable to recover from system prune: DRV_CP_ENDPOINT: failed to get API Server URL: failed to parse ip for ""

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#10357]
To reproduce:

```
minikube start --driver=docker
docker system prune -a
minikube start --driver=docker --delete-on-failure=true
```

Output:

```
😄  minikube v1.17.1 on Debian rodete
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...

❌  Exiting due to DRV_CP_ENDPOINT: failed to get API Server URL: failed to parse ip for ""
💡  Suggestion: 

    Recreate the cluster by running:
    minikube delete --profile=minikube
    minikube start --profile=minikube
```

Expectation: minikube deletes the broken cluster and recreates it. Verbose logs:

[logs.txt](https://github.com/kubernetes/minikube/files/5920817/logs.txt)

**Comment by GarryKab** [comment]
What is the solution to this issue?

**Comment by kadern0** [comment]
@tstromberg I'm not able to reproduce this issue on Ubuntu 20.10

**Comment by EmadMokhtar** [comment]
I was facing an issue that looks the same. I was setting the environment variable `DOCKER_HOST` to `tcp://localhost:2375` and it is fixed after I set it to `tcp://127.0.0.1:2375`

**Comment by notklaatu** [comment]
Running CentOS on a Pi.

```
$ DOCKER_HOST=tcp://localhost:2375 minkube delete --profile=minikube ; minikube start --network-plugin=cni --cni=bridge --extra-config=kubelet.container-runtime=remote --extra-config=kubelet.container-runtime-endpoint=/var/run/crio.sock --extra-config=kubelet.image-service-endpoint=/var/run/crio.sock --driver=podman
```

Got around the `❌  Exiting due to DRV_CP_ENDPOINT: failed to get API Server URL: failed to parse ip for ""` error.

I haven't tested beyond `kubectl get nodes`, to be fair, but specifiying `DOCKER_HOST` at least gets it started.

**Comment by emcrisostomo** [comment]
I can reproduce this on macOS big sur. Docker is running on a virtual machine (VMWare Fusion), and the solution is the same, as mentioned by @EmadMokhtar: if I specify the IP address instead of the host name in the `DOCKER_HOST` variable, then it works.
