### ISSUE TITLE
Make the getting started / installation page look nice again

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#10353]
After adding architectures to the "Installation" section, it's an even bigger mess than it was before...

Now it separates both on OS and on CPU, and it can be confusing to know what to actually download:

https://minikube.sigs.k8s.io/docs/start/

**(1) Installation**
* Linux
  * x86
    * Binary download
    * Debian package
    * RPM package 
  * ARM
    * Binary download
    * Debian package
    * RPM package 
* macOS
  * Brew package manager
  * x86
    * Binary download
  * ARM
    * Binary download
* Windows
  * Windows Package Manager
  * Chocolatey
  * Stand-alone Windows Installer

Hopefully there is some nice web design that could be done, especially for the Linux tab ?

![minikube-installation](https://user-images.githubusercontent.com/10364051/106711126-5443f780-65f7-11eb-9110-07469eacbbfe.png)

I described three different workarounds (in text), but am looking for a better looking solution.

**Comment by afbjorklund** [comment]
There was also a long rant about the installation page and the evil of nested tabs, in https://github.com/kubernetes/minikube/pull/9066#issuecomment-686588915

**Comment by medyagh** [comment]
anyone picking up this task, u could do a nested Tab in the installation page https://minikube.sigs.k8s.io/docs/start/

**Comment by afbjorklund** [comment]
@dinever : I like it! And I think that nested tabs are horrible.

Ultimately the computer should be able to find this out for itself, but until we are there I think this "mini-quiz" will work ?

It also has plenty of room for scalability, if we want to add the other three platforms in a more "dimmed out" manner...

minikube-1.20.0-0.aarch64.rpm
minikube-1.20.0-0.armv7hl.rpm
minikube-1.20.0-0.ppc64le.rpm
minikube-1.20.0-0.s390x.rpm
minikube-1.20.0-0.x86_64.rpm
minikube-darwin-amd64
minikube-darwin-amd64.tar.gz
minikube-darwin-arm64
minikube-installer.exe
minikube-linux-amd64
minikube-linux-amd64.tar.gz
minikube-linux-arm
minikube-linux-arm64
minikube-linux-ppc64le
minikube-linux-s390x
minikube-windows-amd64.exe
minikube-windows-amd64.tar.gz
minikube_1.20.0-0_amd64.deb
minikube_1.20.0-0_arm64.deb
minikube_1.20.0-0_armhf.deb
minikube_1.20.0-0_ppc64el.deb
minikube_1.20.0-0_s390x.deb
