### ISSUE TITLE
Accessing apps documentation issue

### ISSUE THREAD

**Issue by ashwanth1109** [kubernetes/minikube#10352]
## Section from Documentation:
Getting the NodePort using the service command
```
minikube service --url $SERVICE
```

## Problem:
It's not clear from the documentation how to use this command. After experimentation, I believe the usage would look something like this: `minikube service --url hello-minikube1`

Why is this confusing?
Because in the documentation in the section just before, the convention is to use `<>` tags to represent a dynamic value, example:
```
minikube addons enable <name>
```

There should be one convention for representing dynamic values. I'm happy to raise a PR with these changes if you agree with my reasoning

**Comment by sharifelgamal** [comment]
Yeah, I definitely agree with the reasoning here. Feel free to open a PR for this and I'll happily review it.
