### ISSUE TITLE
Add `minikube image load` command

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#10365]
This will load an image into the correct runtime but won't store it in the cache.

**Comment by afbjorklund** [comment]
What is with the double command ? We don't call it `minikube image cache`

**Comment by priyawadhwa** [comment]
This could be extended into `minikube image build` or `minikube image delete`. I agree that right now just `minikube load` would be easier but for future it could be nice to organize all image related content under one subcommand.
