### ISSUE TITLE
X Exiting due to GUEST_PROVISION: Failed to start host: config: please provide an IP address

### ISSUE THREAD

**Issue by shreesh2106** [kubernetes/minikube#10360]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by ilya-zuyev** [comment]
@shreesh2106 Please provide the full output of 'minikube start' command used and the full output of minikube logs command

**Comment by prezha** [comment]
hey @shreesh2106  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:
* The exact minikube start command line used
* Whether the issue occurs with the latest minikube release
* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.
* The full output of minikube logs

Thank you for sharing your experience!

/close
