### ISSUE TITLE
`minikube status` command crashes when minikube is not up

### ISSUE THREAD

**Issue by kirs** [kubernetes/minikube#1037]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): not sure ¯\_(ツ)_/¯ 

**Minikube version** (use `minikube version`): `v0.15.0`

**Environment**:
- **OS**: macOS (`Darwin Kernel Version 16.1.0`)
- **VM Driver**: virtualbox

**What happened**:

Running `minikube status` when minikube is not up results to the crash:

```
E0123 12:11:51.393690   45483 status.go:57] Error getting machine status: Something went wrong running an SSH command!
command :
if which systemctl 2>&1 1>/dev/null; then
  sudo systemctl is-active localkube 2>&1 1>/dev/null && echo "Running" || echo "Stopped"
else
  if ps $(cat /var/run/localkube.pid) 2>&1 1>/dev/null; then
    echo "Running"
  else
    echo "Stopped"
  fi
fi

err     : exit status 255
output  :

================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
```

**What you expected to happen**:

Running `minikube status` when minikube is not up is expected to report that it's not up and (maybe) suggest to run `minikube start`.

**How to reproduce it** (as minimally and precisely as possible):

```
minikube stop
minikube start
```

**Comment by gtirloni** [comment]
Cannot reproduce with minikube 0.17.1

```
$ minikube version
minikube version: v0.17.1

$ minikube status
minikubeVM: Does Not Exist
localkube: N/A
```

**Comment by kirs** [comment]
I upgraded to `v0.17.1` and looks like it's now fixed 🎉

**Comment by idcrosby** [comment]
I am getting this same error with minikube `v0.20.0` (OSX/VirtualBox)
