### ISSUE TITLE
Preparing Kubernetes v1.20.2 on Docker 20.10.2 ... initialization failed on Mac M1

### ISSUE THREAD

**Issue by natalia-umka** [kubernetes/minikube#10370]
MacBook-Air ~ % minikube start --driver=docker      
       
😄  minikube v1.17.1 on Darwin 11.0.1✨  Using the docker driver based on existing profile👍  Starting control plane node minikube in cluster minikube🚜  Pulling base image ...
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=1981MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:
SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=0

goroutine 1 [running]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose
________________________

MacBook-Air ~ % minikube status
E0205 07:53:06.727860    4379 status.go:389] kubeconfig endpoint: extract IP: "minikube" does not appear in /Users/natalia_umka/.kube/config
minikube
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Misconfigured
timeToStop: Nonexistent

WARNING: Your kubectl is pointing to stale minikube-vm.
To fix the kubectl context, run `minikube update-context`

**Comment by sharifelgamal** [comment]
We're working on proper support for Apple M1 for the next release.

**Comment by natalia-umka** [comment]
> We're working on proper support for Apple M1 for the next release.

When will be the next release?

**Comment by burlutskiy** [comment]
Getting exactly the same error. @natalia-umka have you found any workaround to start minikube on M1?

**Comment by afbjorklund** [comment]
Docker crashing needs a new release of Docker, the main thing left in minikube is providing an ARM ISO for the VM...

**Comment by burlutskiy** [comment]
> Docker crashing needs a new release of Docker, the main thing left in minikube is providing an ARM ISO for the VM...

I was able to workaround it by replacing /usr/local/minikube with 
https://github.com/kubernetes/minikube/releases/download/v1.17.1/minikube-darwin-arm64

Surprisingly it also prepares Kubernetes v1.20.2 on Docker 20.10.2 but doesn't fail and the same v1.17.1.
The original v1.17.1 was installed with the brew.

**Comment by natalia-umka** [comment]
> > Docker crashing needs a new release of Docker, the main thing left in minikube is providing an ARM ISO for the VM...
> 
> I was able to workaround it by replacing /usr/local/minikube with
> https://github.com/kubernetes/minikube/releases/download/v1.17.1/minikube-darwin-arm64
> 
> Surprisingly it also prepares Kubernetes v1.20.2 on Docker 20.10.2 but doesn't fail and the same v1.17.1.
> The original v1.17.1 was installed with the brew.

I reinstalled docker for M1 and  I did as U for minikube. 

minikube start
😄  minikube v1.18.0 on Darwin 11.0.1 (arm64)
✨  Automatically selected the docker driver. Other choices: hyperkit, virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1981MB) ...
    > kubectl.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 35.44 MiB / 35.44 MiB [----------------] 100.00% 3.94 MiB p/s 9s
    > kubelet: 100.57 MiB / 100.57 MiB [-------------] 100.00% 4.81 MiB p/s 21s
    > kubeadm: 34.50 MiB / 34.50 MiB [---------------] 100.00% 1.47 MiB p/s 24s

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v4
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
