### ISSUE TITLE
minikube not starting from a powered down VM (VirtualBox)

### ISSUE THREAD

**Issue by mheese** [kubernetes/minikube#1038]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
minikube version: v0.15.0

**Environment**:
- **OS**: macOS 10.12.2
- **VM Driver**: virtualbox
- **Docker version**: Docker version 1.12.5, build 7392c3b (not sure how this is relevant)
- **Install tools**: kubectl v1.5.2
- **Others**: VirtualBox 5.1.14 r112924 (Qt5.6.2)

**What happened**:
The first time after creating my minikube cluster, the VM is created, it boots and the cluster is working as expected.

When my minikube is sleeping or powered off though, and I turn it on again with `minikube start`, it hangs at the `Starting local Kubernetes cluster...` line forever.

**What you expected to happen**:
I'd expect it to start and provide me with a working minikube cluster.

**How to reproduce it** (as minimally and precisely as possible):
Start a powered off minikube VM, or a minikube VM in "saved" state (VirtualBox driver).

**Anything else do we need to know**:
After doing some digging, I found out that the VM is starting fine and boots up. I can enter the console as root user (no password). And I found out that localkube was not started.

`systemctl status localkube` said that localkube is dead / not running.

I simply did a `systemctl start localkube` and everything came back as expected. Maybe there is a missing dependency in the `localkube.service` file which causes localkube to crash on startup and it therefore does not come up properly?

**Comment by dlorenc** [comment]
Could you attach the output of:

`journalctl -u localkube`

and 
`systemctl status localkube`

**Comment by mheese** [comment]
@dlorenc I switched back to v0.15.0 right now and tried to get you the output as requested... However, I tried it 3 times now and I was not able to reproduce it anymore. It came properly up as expected. Did maybe the minikube default ISO change?
