### ISSUE TITLE
adding more control-plane nodes doesn't work

### ISSUE THREAD

**Issue by michaelhenkel** [kubernetes/minikube#10382]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube node add --control-plane
3. second node never succeeds

**Full output of failed command:** 
minikube --driver hyperkit --container-runtime crio start 
😄  minikube v1.17.0 on Darwin 11.1
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🎁  Preparing Kubernetes v1.20.2 on CRI-O 1.19.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass

minikube node add --control-plane                         
😄  Adding node m02 to cluster minikube
❗  Cluster was created without any CNI, adding node to it might cause broken network.
E0205 17:29:35.683097   48700 register.go:137] unexpected first step: ""
👍  Starting node minikube in cluster minikube
🏃  Updating the running hyperkit "minikube" VM ...
E0205 17:29:37.406439   48700 register.go:137] unexpected first step: ""
🎁  Preparing Kubernetes v1.20.2 on CRI-O 1.19.0 ...

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by IvanKuchin** [comment]
Hi @michaelhenkel 

I had the same problem with multi-node minikube (incl: master and worker). If you just go further with the error you'll get all sorts of errors with networking, for example different pods will be assigned with a same IP-address, services will redirect you to random pods, etc.....

```
$ minikube node add
* Adding node m02 to cluster minikube
! Cluster was created without any CNI, adding node to it might cause broken network.
E0214 23:00:34.076209   25503 register.go:139] unexpected first step: ""
* Starting node minikube-m02 in cluster minikube
E0214 23:00:34.080698   25503 register.go:139] unexpected first step: ""
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...- E0214 23:01:41.224426   25503 register.go:139] unexpected first step: ""

* Preparing Kubernetes v1.20.2 on Docker 20.10.2 .../ E0214 23:01:53.914161   25503 register.go:139] unexpected first step: ""

* Verifying Kubernetes components...
* Successfully added m02 to minikube!

```

I fixed it by pointing out minikube to exact drivers for virtual environment

`$ minikube start --driver=virtualbox`

Check this [URL](https://minikube.sigs.k8s.io/docs/drivers/) out. 

HTH

**Comment by sharifelgamal** [comment]
We do not currently support multiple control planes in minikube, it's a feature that's currently under development, see #7461.
