### ISSUE TITLE
Document all windows integration tests failures

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/minikube#10405]

**Comment by sharifelgamal** [comment]
The tests that are currently failing every time:
- TestCertOptions
- TestAddons/Registry
- TestDockerFlags
- TestForceSystemdEnv

In addition, TestStartStop is failing frequently under all sorts of different permutations.

Those will be top priorities to fix, then we'll re-examine where we are.

**Comment by medyagh** [comment]
I recommend adding failure logs for each test in a separate issue.

**Comment by sharifelgamal** [comment]
TestCertOptions: #10622
TestDockerFlags: #10624
TestForceSystemdEnv: #10625
TestForceSystemd: #10626
TestFunctional/DockerEnv: #10627
TestErrorSpam: #10628

**Comment by medyagh** [comment]
done
