### ISSUE TITLE
Create Config variable MINIKUBE_HOME to host dir .minikube

### ISSUE THREAD

**Issue by michael-l-schneider** [kubernetes/minikube#1041]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

**Minikube version** (use `minikube version`):
1.5.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
Windows (although would add value to all)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
- **Docker version** (e.g. `docker -v`):
- **Install tools**:
- **Others**:

**What happened**:

On windows, we have a strange drive setup
1) $HOME is  on a small network drive (~1GB)
2) The C: drive is small
3) D: and E: are large drives

Today, on 1.5.0   I am not able to run minicube start on windows becuase I do not have sufficent disk space and redefining   $HOME and $HOMEDRIVE and $HOMEPATH did not change drive locacation of .minikube

It would be very nice if there was an env variable (on all platforms) that we could set to be the parent drive of .minikube.

There are other uses of $HOME on the system, it would be nice to have an env variable to specify the parent of .minikube.

You are better than names than I, but something like   MINIKUBE_HOME or MINIKUBE_CONFIG_HOME

many other large enterprise sites are set up with drives like ours, so this would be useful.

Thank you for your consideration.
Michael

PS.  Is there any way to change the parent of .minikube on windows in  minkube 1.5.0 today?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by r2d4** [comment]
Should be easy enough to let this be configurable, a good feature to have.

Unfortunately, until then, theres not a way to change it.

**Comment by aaron-prindle** [comment]
Fixed with #1104
See:
https://github.com/kubernetes/minikube#minikube-environment-variables

**Comment by michael-l-schneider** [comment]
Verified fix in corp environment with small home drives
