### ISSUE TITLE
StartHost failed, but will try again: config: please provide an IP address

### ISSUE THREAD

**Issue by keremtekant** [kubernetes/minikube#10416]
**Steps to reproduce the issue:** 
[student@localhost ~]$ minikube start
* minikube v1.17.1 on Fedora 33
* Using the ssh driver based on existing profile
* Starting control plane node minikube in cluster minikube
! StartHost failed, but will try again: config: please provide an IP address
* Failed to start ssh bare metal machine. Running "minikube delete" may fix it: config: please provide an IP address

X Exiting due to GUEST_PROVISION: Failed to start host: config: please provide an IP address
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

1.
2. 
3.

**Full output of failed command:** 
[student@localhost ~]$ minikube start --alsologtostderr
I0209 18:47:18.065059    3132 out.go:229] Setting OutFile to fd 1 ...
I0209 18:47:18.065486    3132 out.go:276] TERM=xterm,COLORTERM=, which probably does not support color
I0209 18:47:18.065498    3132 out.go:242] Setting ErrFile to fd 2...
I0209 18:47:18.065543    3132 out.go:276] TERM=xterm,COLORTERM=, which probably does not support color
I0209 18:47:18.065761    3132 root.go:291] Updating PATH: /home/student/.minikube/bin
I0209 18:47:18.066299    3132 out.go:236] Setting JSON to false
I0209 18:47:18.067793    3132 start.go:106] hostinfo: {"hostname":"localhost.localdomain","uptime":757,"bootTime":1612884881,"procs":228,"os":"linux","platform":"fedora","platformFamily":"fedora","platformVersion":"33","kernelVersion":"5.10.13-200.fc33.x86_64","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"cccf643b-b04a-4633-899b-9585d41bc0e1"}
I0209 18:47:18.067991    3132 start.go:116] virtualization: kvm host
I0209 18:47:18.068804    3132 out.go:119] * minikube v1.17.1 on Fedora 33
* minikube v1.17.1 on Fedora 33
I0209 18:47:18.069874    3132 driver.go:315] Setting default libvirt URI to qemu:///system
W0209 18:47:18.069939    3132 start.go:631] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I0209 18:47:18.071319    3132 notify.go:126] Checking for updates...
I0209 18:47:18.074761    3132 out.go:119] * Using the ssh driver based on existing profile
* Using the ssh driver based on existing profile
I0209 18:47:18.074803    3132 start.go:279] selected driver: ssh
I0209 18:47:18.074810    3132 start.go:702] validating driver "ssh" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.17@sha256:1cd2e039ec9d418e6380b2fa0280503a72e5b282adea674ee67882f59f4f546e Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:ssh HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] Network: MultiNodeRequested:false}
I0209 18:47:18.074931    3132 start.go:713] status for ssh: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0209 18:47:18.075522    3132 start_flags.go:390] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.17@sha256:1cd2e039ec9d418e6380b2fa0280503a72e5b282adea674ee67882f59f4f546e Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:ssh HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] Network: MultiNodeRequested:false}
I0209 18:47:18.080299    3132 out.go:119] * Starting control plane node minikube in cluster minikube
* Starting control plane node minikube in cluster minikube
I0209 18:47:18.080339    3132 preload.go:97] Checking if preload exists for k8s version v1.20.2 and runtime docker
I0209 18:47:18.080364    3132 preload.go:105] Found local preload: /home/student/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v8-v1.20.2-docker-overlay2-amd64.tar.lz4
I0209 18:47:18.080377    3132 cache.go:54] Caching tarball of preloaded images
I0209 18:47:18.080402    3132 preload.go:131] Found /home/student/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v8-v1.20.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0209 18:47:18.080411    3132 cache.go:57] Finished verifying existence of preloaded tar for  v1.20.2 on docker
I0209 18:47:18.080695    3132 profile.go:148] Saving config to /home/student/.minikube/profiles/minikube/config.json ...
I0209 18:47:18.081000    3132 cache.go:185] Successfully downloaded all kic artifacts
I0209 18:47:18.081050    3132 start.go:313] acquiring machines lock for minikube: {Name:mk7927ff94a651ed792284bf4870353061bc1b05 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0209 18:47:18.081471    3132 start.go:317] acquired machines lock for "minikube" in 376.083µs
I0209 18:47:18.081545    3132 start.go:89] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.17@sha256:1cd2e039ec9d418e6380b2fa0280503a72e5b282adea674ee67882f59f4f546e Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:ssh HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] Network: MultiNodeRequested:false} &{Name: IP: Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}
I0209 18:47:18.081662    3132 start.go:126] createHost starting for "" (driver="ssh")
I0209 18:47:18.081987    3132 ssh_runner.go:149] Run: systemctl --version
I0209 18:47:18.082110    3132 retry.go:31] will retry after 276.165072ms: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP address is not set
I0209 18:47:18.364657    3132 retry.go:31] will retry after 540.190908ms: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP address is not set
I0209 18:47:18.906271    3132 retry.go:31] will retry after 655.06503ms: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP address is not set
I0209 18:47:19.562955    3132 retry.go:31] will retry after 791.196345ms: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP address is not set
I0209 18:47:20.360574    3132 start.go:129] duration metric: createHost completed in 2.278895678s
I0209 18:47:20.360612    3132 start.go:80] releasing machines lock for "minikube", held for 2.279115699s
W0209 18:47:20.360647    3132 start.go:377] error starting host: config: please provide an IP address
I0209 18:47:20.360752    3132 cli_runner.go:111] Run: docker container inspect minikube --format={{.State.Status}}
I0209 18:47:20.360785    3132 delete.go:46] couldn't inspect container "minikube" before deleting: unknown state "minikube": docker container inspect minikube --format={{.State.Status}}: exec: "docker": executable file not found in $PATH
stdout:

stderr:
I0209 18:47:20.360831    3132 cli_runner.go:111] Run: sudo -n podman container inspect minikube --format={{.State.Status}}
W0209 18:47:20.373653    3132 cli_runner.go:149] sudo -n podman container inspect minikube --format={{.State.Status}} returned with exit code 1
I0209 18:47:20.373732    3132 delete.go:46] couldn't inspect container "minikube" before deleting: unknown state "minikube": sudo -n podman container inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
sudo: a password is required
W0209 18:47:20.373762    3132 start.go:382] delete host: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
W0209 18:47:20.373849    3132 out.go:181] ! StartHost failed, but will try again: config: please provide an IP address
! StartHost failed, but will try again: config: please provide an IP address
I0209 18:47:20.373864    3132 start.go:392] Will try again in 5 seconds ...
I0209 18:47:25.393612    3132 start.go:313] acquiring machines lock for minikube: {Name:mk7927ff94a651ed792284bf4870353061bc1b05 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0209 18:47:25.394575    3132 start.go:317] acquired machines lock for "minikube" in 565.595µs
I0209 18:47:25.394954    3132 start.go:89] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.17@sha256:1cd2e039ec9d418e6380b2fa0280503a72e5b282adea674ee67882f59f4f546e Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:ssh HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] Network: MultiNodeRequested:false} &{Name: IP: Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}
I0209 18:47:25.395352    3132 start.go:126] createHost starting for "" (driver="ssh")
I0209 18:47:25.395786    3132 start.go:129] duration metric: createHost completed in 63.004µs
I0209 18:47:25.396067    3132 start.go:80] releasing machines lock for "minikube", held for 1.288763ms
W0209 18:47:25.396687    3132 out.go:181] * Failed to start ssh bare metal machine. Running "minikube delete" may fix it: config: please provide an IP address
* Failed to start ssh bare metal machine. Running "minikube delete" may fix it: config: please provide an IP address
I0209 18:47:25.398231    3132 out.go:119]

W0209 18:47:25.398916    3132 out.go:181] X Exiting due to GUEST_PROVISION: Failed to start host: config: please provide an IP address
X Exiting due to GUEST_PROVISION: Failed to start host: config: please provide an IP address
W0209 18:47:25.399743    3132 out.go:181] *
*
W0209 18:47:25.400641    3132 out.go:181] * If the above advice does not help, please let us know:
* If the above advice does not help, please let us know:
W0209 18:47:25.401281    3132 out.go:181]   - https://github.com/kubernetes/minikube/issues/new/choose
  - https://github.com/kubernetes/minikube/issues/new/choose
I0209 18:47:25.401320    3132 out.go:119]

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
Seems like this is some residue from the bug with 1.17.0: #10268

It selected the SSH driver by default, when there was no installation of either virtualization or containerization available.

Delete the existing ssh profile, and start over using minikube 1.17.1

> Running "minikube delete" may fix it
