### ISSUE TITLE
Add containerd start times to PR bot

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#10437]

**Comment by priyawadhwa** [comment]
If anyone is interested in taking this on, it's just a matter of updating [mkcmp](https://github.com/kubernetes/minikube/blob/master/cmd/performance/mkcmp/cmd/README.md) to also track start times for containerd.

You could pretty much copy what is happening here, and just pass in `--container-runtime=containerd`:

https://github.com/kubernetes/minikube/blob/2aa2d1fb8da9d97798f5d5f6852b42f938ab4ff7/pkg/minikube/perf/start.go#L97

**Comment by sgirem463** [comment]
@priyawadhwa
I have just started to contribute to kubernetes, it's my first issue. I read code and document in 
https://github.com/kubernetes/minikube/blob/master/cmd/performance/mkcmp/cmd/mkcmp.go
https://minikube.sigs.k8s.io/docs/handbook/config/

Am I right that I basically need to repeat this command:

    startCmd := exec.CommandContext(ctx, binary.path, "start", fmt.Sprintf("--driver=%s", driver))

with a similar one like:

    startCmd2 := exec.CommandContext(ctx, binary.path, "start", fmt.Sprintf("--driver=%s", driver), "--container-runtime=containerd")

and handle logs and errors in the same way?
I also think it may be cleaner to use a loop to execute these two commands with/without --container-runtime=containerd.

Would appreciate your input, thanks!

**Comment by sgirem463** [comment]
@priyawadhwa
The current idea is to have:

// CompareMinikubeStart compares the time to run `minikube start` between two minikube binaries
func CompareMinikubeStart(ctx context.Context, out io.Writer, binaries []*Binary) error {
        runtimes := []string{"docker", "containerd"}
	drivers := []string{"kvm2", "docker"}
        for _, r := range runtimes {
	       for _, d := range drivers {

and pass r and d into downstream functions.

The output will look like:

docker runtime, kvm2 Driver
....

docker runtime, docker Driver
....

containerd runtime, kvm2 Driver
....

containerd runtime, docker Driver
....

**Comment by sgirem463** [comment]
@priyawadhwa 

I have made changes and started testing with:

    make test WHAT=./pkg/minikube/perf  GOFLAGS=-v

It seems to run through tests without issues. My question:
where I can find logs for the tests related to the "mkcmp" command I am making changes to?

Below is the diffs:

ALLANs-MBP:minikube alue$ 
ALLANs-MBP:minikube alue$ git diff
diff --git a/pkg/minikube/perf/result_manager.go b/pkg/minikube/perf/result_manager.go
index 61f857d4c..3c9cadfdb 100644
--- a/pkg/minikube/perf/result_manager.go
+++ b/pkg/minikube/perf/result_manager.go
@@ -64,9 +64,9 @@ func (rm *resultManager) averageTime(binary *Binary) float64 {
        return average(times)
 }
 
-func (rm *resultManager) summarizeResults(binaries []*Binary, driver string) {
+func (rm *resultManager) summarizeResults(binaries []*Binary, runtime string, driver string) {
        // print total and average times
-       fmt.Printf("**%s Driver**\n", driver)
+       fmt.Printf("**%s Runtime %s Driver**\n", runtime, driver)
 
        for _, b := range binaries {
                fmt.Printf("Times for %s: ", b.Name())
diff --git a/pkg/minikube/perf/start.go b/pkg/minikube/perf/start.go
index 3a9c62bf9..cea1627cc 100644
--- a/pkg/minikube/perf/start.go
+++ b/pkg/minikube/perf/start.go
@@ -34,6 +34,7 @@ const (
 
 // CompareMinikubeStart compares the time to run `minikube start` between two minikube binaries
 func CompareMinikubeStart(ctx context.Context, out io.Writer, binaries []*Binary) error {
+       runtimes := []string{"docker", "containerd"}
        drivers := []string{"kvm2", "docker"}
        for _, d := range drivers {
                fmt.Printf("**%s Driver**\n", d)
@@ -41,23 +42,25 @@ func CompareMinikubeStart(ctx context.Context, out io.Writer, binaries []*Binary
                        fmt.Printf("error downloading artifacts: %v", err)
                        continue
                }
-               rm, err := collectResults(ctx, binaries, d)
-               if err != nil {
-                       fmt.Printf("error collecting results for %s driver: %v\n", d, err)
-                       continue
+               for _, r := range runtimes {
+                       rm, err := collectResults(ctx, binaries, r, d)
+                       if err != nil {
+                               fmt.Printf("error collecting results for %s runtime %s driver: %v\n", r, d, err)
+                               continue
+                       }
+                       rm.summarizeResults(binaries, r, d)
+                       fmt.Println()
                }
-               rm.summarizeResults(binaries, d)
-               fmt.Println()
        }
        return nil
 }
 
-func collectResults(ctx context.Context, binaries []*Binary, driver string) (*resultManager, error) {
+func collectResults(ctx context.Context, binaries []*Binary, runtime string, driver string) (*resultManager, error) {
        rm := newResultManager()
        for run := 0; run < runs; run++ {
                log.Printf("Executing run %d/%d...", run+1, runs)
                for _, binary := range binaries {
-                       r, err := timeMinikubeStart(ctx, binary, driver)
+                       r, err := timeMinikubeStart(ctx, binary, runtime, driver)
                        if err != nil {
                                return nil, errors.Wrapf(err, "timing run %d with %s", run, binary.Name())
                        }
@@ -93,8 +96,8 @@ func downloadArtifacts(ctx context.Context, binaries []*Binary, driver string) e
 }
 
 // timeMinikubeStart returns the time it takes to execute `minikube start`
-func timeMinikubeStart(ctx context.Context, binary *Binary, driver string) (*result, error) {
-       startCmd := exec.CommandContext(ctx, binary.path, "start", fmt.Sprintf("--driver=%s", driver))
+func timeMinikubeStart(ctx context.Context, binary *Binary, runtime string, driver string) (*result, error) {
+       startCmd := exec.CommandContext(ctx, binary.path, "start", fmt.Sprintf("--container-runtime=%s --driver=%s", runtime, driver))
        startCmd.Stderr = os.Stderr
 
        log.Printf("Running: %v...", startCmd.Args)
ALLANs-MBP:minikube alue$

**Comment by sgirem463** [comment]
@sharifelgamal 
Can you please provide inputs?

**Comment by sharifelgamal** [comment]
This is done.
