### ISSUE TITLE
The connection to the server localhost:8443 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by dxviidmg** [kubernetes/minikube#10440]
Exiting due to MK_ENABLE: run callbacks: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.20.0/kubectl apply -f /etc/kubernetes/addons/dashboard-ns.yaml -f /etc/kubernetes/addons/dashboard-clusterrole.yaml -f /etc/kubernetes/addons/dashboard-clusterrolebinding.yaml -f /etc/kubernetes/addons/dashboard-configmap.yaml -f /etc/kubernetes/addons/dashboard-dp.yaml -f /etc/kubernetes/addons/dashboard-role.yaml -f /etc/kubernetes/addons/dashboard-rolebinding.yaml -f /etc/kubernetes/addons/dashboard-sa.yaml -f /etc/kubernetes/addons/dashboard-secret.yaml -f /etc/kubernetes/addons/dashboard-svc.yaml: Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by prezha** [comment]
@dxviidmg  we don’t yet have a clear way to replicate this issue. Do you mind adding some additional details?

Here is additional information that would be helpful:

    * The exact minikube start command line used
    * The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.
    * The full output of minikube logs
    * The full output of kubectl get po -A

Thank you for sharing your experience!
