### ISSUE TITLE
The minikube v1.17.1 release did not update the iso image

### ISSUE THREAD

**Issue by nixpanic** [kubernetes/minikube#10444]
Hi,

#10255 made a modification to the iso image for the minikube VM. Unfortunately the updated image was not released. What is needed to get that done?

Thanks!
Niels

**Comment by afbjorklund** [comment]
Normally the minor versions don't update the ISO, but there will be one for v1.18.0 soon enough

**Comment by nixpanic** [comment]
Ok, thanks!

**Comment by humblec** [comment]
> Normally the minor versions don't update the ISO, but there will be one for v1.18.0 soon enough

@afbjorklund where can we track the release cycle? may be I missed it , if thats the case apologies in advance.

**Comment by afbjorklund** [comment]
It is here for now: https://github.com/kubernetes/minikube/milestones

But there is some work to make it more obvious than that: #10409

**Comment by humblec** [comment]
> It is here for now: https://github.com/kubernetes/minikube/milestones
> 
> But there is some work to make it more obvious than that: #10409
Sure.. Thanks!

**Comment by humblec** [comment]
> > It is here for now: https://github.com/kubernetes/minikube/milestones
> > But there is some work to make it more obvious than that: #10409
 Sure.. Thanks!

**Comment by priyawadhwa** [comment]
Since we have resolved this issue, I'm going to go ahead and close it. Thank you! Feel free to reopen if you have any additional thoughts or questions by including /reopen in your comment.
