### ISSUE TITLE
driver for VmwareFusion to start minikube

### ISSUE THREAD

**Issue by UdayP23** [kubernetes/minikube#10445]
**Steps to reproduce the issue:** 

1. Unable to set driver for vmware fusion 
2. 
3.

**Full output of failed command:** 
~]$ minikube config set driver hyperkit

❌  Exiting due to MK_CONFIG_SET: run validations for "driver" with value of "hyperkit": [driver "hyperkit" is not supported]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
The vmwarefusion driver is no longer supported in minikube, please try using the vmware driver instead.

Also, in your description, it seems like you're trying to set the driver to hyperkit, which isn't supported by your system. What OS are you using?

**Comment by sharifelgamal** [comment]
Hey @author – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!
