### ISSUE TITLE
Update outdated moby/hyperkit package in minikube code

### ISSUE THREAD

**Issue by dytyniuk** [kubernetes/minikube#10443]
**Steps to reproduce the issue:** 

1. Start a new Minikube cluster based on Hyperkit driver `minikube start --driver=hyperkit --cpus=2 --disk-size=10g --memory=4g --hyperkit-vpnkit-sock='auto'`
2. VM creation fails:
```
$ minikube start --driver=hyperkit --cpus=2 --disk-size=10g --memory=4g --hyperkit-vpnkit-sock='auto'
😄  minikube v1.17.1 on Darwin 11.2.1
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=10240MB) ...
🔥  Deleting "minikube" in hyperkit ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/r3ntg3n/Library/Containers/com.docker.docker/Data/s50: no such file or directory
🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=10240MB) ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/r3ntg3n/Library/Containers/com.docker.docker/Data/s50: no such file or directory

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/r3ntg3n/Library/Containers/com.docker.docker/Data/s50: no such file or directory
```

**Full output of failed command:** 
<details>
<pre><code>
$ minikube start --driver=hyperkit --cpus=2 --disk-size=10g --memory=4g --hyperkit-vpnkit-sock='auto' --alsologtostderr
I0211 11:48:41.072533   16803 out.go:229] Setting OutFile to fd 1 ...
I0211 11:48:41.073164   16803 out.go:281] isatty.IsTerminal(1) = true
I0211 11:48:41.073176   16803 out.go:242] Setting ErrFile to fd 2...
I0211 11:48:41.073184   16803 out.go:281] isatty.IsTerminal(2) = true
I0211 11:48:41.073356   16803 root.go:291] Updating PATH: /Users/r3ntg3n/.minikube/bin
I0211 11:48:41.073969   16803 out.go:236] Setting JSON to false
I0211 11:48:41.123464   16803 start.go:106] hostinfo: {"hostname":"Yevheniis-MacBook-Pro.local","uptime":128060,"bootTime":1612908861,"procs":669,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"11.2.1","kernelVersion":"20.3.0","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"c86236b2-4976-3542-80ca-74a6b8b4ba03"}
W0211 11:48:41.123589   16803 start.go:114] gopshost.Virtualization returned error: not implemented yet
I0211 11:48:41.160190   16803 out.go:119] 😄  minikube v1.17.1 on Darwin 11.2.1
😄  minikube v1.17.1 on Darwin 11.2.1
I0211 11:48:41.161856   16803 driver.go:315] Setting default libvirt URI to qemu:///system
I0211 11:48:41.163252   16803 notify.go:126] Checking for updates...
I0211 11:48:41.198536   16803 out.go:119] ✨  Using the hyperkit driver based on user configuration
✨  Using the hyperkit driver based on user configuration
I0211 11:48:41.198579   16803 start.go:279] selected driver: hyperkit
I0211 11:48:41.198591   16803 start.go:702] validating driver "hyperkit" against <nil>
I0211 11:48:41.198611   16803 start.go:713] status for hyperkit: {Installed:true Healthy:true Running:true NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0211 11:48:41.198975   16803 install.go:51] acquiring lock: {Name:mk4023283b30b374c3f04c8805d539e68824c0b8 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0211 11:48:41.199177   16803 install.go:116] Validating docker-machine-driver-hyperkit, PATH=/Users/r3ntg3n/.minikube/bin:/usr/local/opt/node@12/bin:/Users/r3ntg3n/.symfony/bin:/usr/local/opt/php@7.3/sbin:/usr/local/opt/php@7.3/bin:~/Library/Python/2.7/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion.app/Contents/Public:/usr/local/MacGPG2/bin
I0211 11:48:41.214215   16803 install.go:136] /Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit version is 1.11.0
I0211 11:48:41.223622   16803 install.go:78] stdout: /Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit
I0211 11:48:41.223653   16803 install.go:80] /Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit looks good
I0211 11:48:41.223986   16803 start_flags.go:249] no existing cluster config was found, will generate one from the flags
I0211 11:48:41.224871   16803 start_flags.go:671] Wait components to verify : map[apiserver:true system_pods:true]
I0211 11:48:41.224935   16803 cni.go:74] Creating CNI manager for ""
I0211 11:48:41.224954   16803 cni.go:139] CNI unnecessary in this configuration, recommending no CNI
I0211 11:48:41.224968   16803 start_flags.go:390] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.17@sha256:1cd2e039ec9d418e6380b2fa0280503a72e5b282adea674ee67882f59f4f546e Memory:4096 CPUs:2 DiskSize:10240 VMDriver: Driver:hyperkit HyperkitVpnKitSock:auto HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] Network: MultiNodeRequested:false}
I0211 11:48:41.225837   16803 iso.go:119] acquiring lock: {Name:mk28ee3698f8e23bb9721ac391fba3986864d250 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0211 11:48:41.382843   16803 out.go:119] 👍  Starting control plane node minikube in cluster minikube
👍  Starting control plane node minikube in cluster minikube
I0211 11:48:41.382936   16803 preload.go:97] Checking if preload exists for k8s version v1.20.2 and runtime docker
I0211 11:48:41.383075   16803 preload.go:105] Found local preload: /Users/r3ntg3n/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v8-v1.20.2-docker-overlay2-amd64.tar.lz4
I0211 11:48:41.383501   16803 cache.go:54] Caching tarball of preloaded images
I0211 11:48:41.383637   16803 preload.go:131] Found /Users/r3ntg3n/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v8-v1.20.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0211 11:48:41.383659   16803 cache.go:57] Finished verifying existence of preloaded tar for  v1.20.2 on docker
I0211 11:48:41.384241   16803 profile.go:148] Saving config to /Users/r3ntg3n/.minikube/profiles/minikube/config.json ...
I0211 11:48:41.384326   16803 lock.go:36] WriteFile acquiring /Users/r3ntg3n/.minikube/profiles/minikube/config.json: {Name:mk1827875fb37cb30ff03c1d8e2a1eba275b9991 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0211 11:48:41.388058   16803 cache.go:185] Successfully downloaded all kic artifacts
I0211 11:48:41.388119   16803 start.go:313] acquiring machines lock for minikube: {Name:mk9c594ef910327703e92d85a3f1a21f7ecbad4d Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0211 11:48:41.388365   16803 start.go:317] acquired machines lock for "minikube" in 200.233µs
I0211 11:48:41.388420   16803 start.go:89] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.17.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.17@sha256:1cd2e039ec9d418e6380b2fa0280503a72e5b282adea674ee67882f59f4f546e Memory:4096 CPUs:2 DiskSize:10240 VMDriver: Driver:hyperkit HyperkitVpnKitSock:auto HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] Network: MultiNodeRequested:false} &{Name: IP: Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}
I0211 11:48:41.388550   16803 start.go:126] createHost starting for "" (driver="hyperkit")
I0211 11:48:41.426625   16803 out.go:140] 🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=10240MB) ...
🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=10240MB) ...| I0211 11:48:41.428234   16803 main.go:119] libmachine: Found binary path at /Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit
I0211 11:48:41.428306   16803 main.go:119] libmachine: Launching plugin server for driver hyperkit
I0211 11:48:41.441899   16803 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:59918
I0211 11:48:41.442539   16803 main.go:119] libmachine: () Calling .GetVersion
I0211 11:48:41.443236   16803 main.go:119] libmachine: Using API Version  1
I0211 11:48:41.443258   16803 main.go:119] libmachine: () Calling .SetConfigRaw
I0211 11:48:41.443611   16803 main.go:119] libmachine: () Calling .GetMachineName
I0211 11:48:41.443790   16803 main.go:119] libmachine: (minikube) Calling .GetMachineName
I0211 11:48:41.443952   16803 main.go:119] libmachine: (minikube) Calling .DriverName
I0211 11:48:41.444146   16803 start.go:160] libmachine.API.Create for "minikube" (driver="hyperkit")
I0211 11:48:41.444189   16803 client.go:168] LocalClient.Create starting
I0211 11:48:41.444255   16803 main.go:119] libmachine: Reading certificate data from /Users/r3ntg3n/.minikube/certs/ca.pem
I0211 11:48:41.444598   16803 main.go:119] libmachine: Decoding PEM data...
I0211 11:48:41.444629   16803 main.go:119] libmachine: Parsing certificate...
I0211 11:48:41.445157   16803 main.go:119] libmachine: Reading certificate data from /Users/r3ntg3n/.minikube/certs/cert.pem
I0211 11:48:41.445481   16803 main.go:119] libmachine: Decoding PEM data...
I0211 11:48:41.445509   16803 main.go:119] libmachine: Parsing certificate...
I0211 11:48:41.445605   16803 main.go:119] libmachine: Running pre-create checks...
I0211 11:48:41.445626   16803 main.go:119] libmachine: (minikube) Calling .PreCreateCheck
I0211 11:48:41.445827   16803 main.go:119] libmachine: (minikube) DBG | exe=/Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0211 11:48:41.446149   16803 main.go:119] libmachine: (minikube) Calling .GetConfigRaw
I0211 11:48:41.447046   16803 main.go:119] libmachine: Creating machine...
I0211 11:48:41.447062   16803 main.go:119] libmachine: (minikube) Calling .Create
I0211 11:48:41.447286   16803 main.go:119] libmachine: (minikube) DBG | exe=/Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0211 11:48:41.447960   16803 main.go:119] libmachine: (minikube) DBG | ERROR: logging before flag.Parse: I0211 11:48:41.447252   16811 common.go:99] Making disk image using store path: /Users/r3ntg3n/.minikube
I0211 11:48:41.448077   16803 main.go:119] libmachine: (minikube) Downloading /Users/r3ntg3n/.minikube/cache/boot2docker.iso from file:///Users/r3ntg3n/.minikube/cache/iso/minikube-v1.17.0.iso...
| I0211 11:48:41.883644   16803 main.go:119] libmachine: (minikube) DBG | ERROR: logging before flag.Parse: I0211 11:48:41.883529   16811 common.go:106] Creating ssh key: /Users/r3ntg3n/.minikube/machines/minikube/id_rsa...
/ I0211 11:48:41.952119   16803 main.go:119] libmachine: (minikube) DBG | ERROR: logging before flag.Parse: I0211 11:48:41.952002   16811 common.go:112] Creating raw disk image: /Users/r3ntg3n/.minikube/machines/minikube/minikube.rawdisk...
I0211 11:48:41.952141   16803 main.go:119] libmachine: (minikube) DBG | Writing magic tar header
I0211 11:48:41.952156   16803 main.go:119] libmachine: (minikube) DBG | Writing SSH key tar header
I0211 11:48:41.952483   16803 main.go:119] libmachine: (minikube) DBG | ERROR: logging before flag.Parse: I0211 11:48:41.952425   16811 common.go:126] Fixing permissions on /Users/r3ntg3n/.minikube/machines/minikube ...
\ I0211 11:48:42.184504   16803 main.go:119] libmachine: (minikube) DBG | exe=/Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0211 11:48:42.184542   16803 main.go:119] libmachine: (minikube) DBG | clean start, hyperkit pid file doesn't exist: /Users/r3ntg3n/.minikube/machines/minikube/hyperkit.pid
I0211 11:48:42.188987   16803 client.go:171] LocalClient.Create took 744.784108ms
- I0211 11:48:44.189977   16803 start.go:129] duration metric: createHost completed in 2.801414499s
I0211 11:48:44.190034   16803 start.go:80] releasing machines lock for "minikube", held for 2.801661117s
\ W0211 11:48:44.195633   16803 start.go:377] error starting host: creating host: create: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/r3ntg3n/Library/Containers/com.docker.docker/Data/s50: no such file or directory
I0211 11:48:44.196479   16803 main.go:119] libmachine: Found binary path at /Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit
I0211 11:48:44.196557   16803 main.go:119] libmachine: Launching plugin server for driver hyperkit
I0211 11:48:44.213229   16803 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:59922
I0211 11:48:44.214047   16803 main.go:119] libmachine: () Calling .GetVersion
I0211 11:48:44.214897   16803 main.go:119] libmachine: Using API Version  1
I0211 11:48:44.214929   16803 main.go:119] libmachine: () Calling .SetConfigRaw
I0211 11:48:44.215379   16803 main.go:119] libmachine: () Calling .GetMachineName
I0211 11:48:44.216099   16803 main.go:119] libmachine: Found binary path at /Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit
I0211 11:48:44.216155   16803 main.go:119] libmachine: Launching plugin server for driver hyperkit
I0211 11:48:44.232309   16803 main.go:119] libmachine: Plugin server listening at address 127.0.0.1:59926
I0211 11:48:44.232894   16803 main.go:119] libmachine: () Calling .GetVersion
I0211 11:48:44.233561   16803 main.go:119] libmachine: Using API Version  1
I0211 11:48:44.233586   16803 main.go:119] libmachine: () Calling .SetConfigRaw
I0211 11:48:44.233978   16803 main.go:119] libmachine: () Calling .GetMachineName
I0211 11:48:44.234152   16803 main.go:119] libmachine: (minikube) Calling .GetState
I0211 11:48:44.234302   16803 main.go:119] libmachine: (minikube) DBG | exe=/Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0211 11:48:44.234359   16803 main.go:119] libmachine: (minikube) Error reading pid file: open /Users/r3ntg3n/.minikube/machines/minikube/hyperkit.json: no such file or directory
I0211 11:48:44.234381   16803 main.go:119] libmachine: (minikube) DBG | hyperkit pid from json: 0
I0211 11:48:44.234433   16803 main.go:119] libmachine: (minikube) Calling .DriverName
I0211 11:48:44.266583   16803 out.go:119] 🔥  Deleting "minikube" in hyperkit ...

🔥  Deleting "minikube" in hyperkit ...
I0211 11:48:44.266680   16803 main.go:119] libmachine: (minikube) Calling .Remove
I0211 11:48:44.267126   16803 main.go:119] libmachine: (minikube) DBG | exe=/Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0211 11:48:44.267171   16803 main.go:119] libmachine: (minikube) DBG | exe=/Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0211 11:48:44.267345   16803 main.go:119] libmachine: (minikube) Error reading pid file: open /Users/r3ntg3n/.minikube/machines/minikube/hyperkit.json: no such file or directory
I0211 11:48:44.267394   16803 main.go:119] libmachine: (minikube) DBG | hyperkit pid from json: 0
W0211 11:48:44.298852   16803 out.go:181] 🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/r3ntg3n/Library/Containers/com.docker.docker/Data/s50: no such file or directory
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/r3ntg3n/Library/Containers/com.docker.docker/Data/s50: no such file or directory
I0211 11:48:44.298885   16803 start.go:392] Will try again in 5 seconds ...
</code></pre>
</details>

**Workaround found:**
1. There is nothing related to `s50` in `~/Library/Containers/com.docker.docker/Data`, but obviously the VPNKit Socket we're looking for
```
total 131200
srwxr-xr-x  1 r3ntg3n  staff         0 11 лют 10:21 backend-for-guest.sock
[REDACTED]
srwxr-xr-x  1 r3ntg3n  staff         0 11 лют 10:21 vpnkit.data.sock
srwxr-xr-x  1 r3ntg3n  staff         0 11 лют 10:21 vpnkit.diag.sock
srwxr-xr-x  1 r3ntg3n  staff         0 11 лют 10:21 vpnkit.eth.sock
srwxr-xr-x  1 r3ntg3n  staff         0 11 лют 10:21 vpnkit.pcap.sock
srwxr-xr-x  1 r3ntg3n  staff         0 11 лют 10:21 vpnkit.port.sock
```
2. Replace `--hyperkit-vpn-sock='auto'` with full path and machine boots up:
```
$ minikube start --driver=hyperkit --cpus=2 --disk-size=10g --memory=4g --hyperkit-vpnkit-sock='/Users/r3ntg3n/Library/Containers/com.docker.docker/Data/vpnkit.eth.sock' -v5
😄  minikube v1.17.1 on Darwin 11.2.1
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=10240MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```
@afbjorklund was very kind to pinpoint the root cause of this. Used moby/hyperkit package version is quite outdated:
 * the issue has been fixed in the upstream more than 1 year ago: https://github.com/moby/hyperkit/commit/dab74a60d38b34aa4ddc20183f2411e2467d9445
 * "nearest" version with the fix is https://github.com/moby/hyperkit/releases/tag/v0.20190802

**Comment by priyawadhwa** [comment]
Hey @dytyniuk thanks for pointing this out. If you, or anyone  else, would be interested in upgrading this library in minikube we'd be happy to take a look at the PR!

**Comment by medyagh** [comment]
@dytyniuk do u mind checking if the binary in this PR fixes the problem ? https://github.com/kubernetes/minikube/pull/10631

http://storage.googleapis.com/minikube-builds/10631/minikube-darwin-amd64

**Comment by dytyniuk** [comment]
Hey @medyagh 
Pardon my silence, was "disconnected" a bit. Sure thing, I will check the binary today.

**Comment by dytyniuk** [comment]
@medyagh @daehyeok the issue persists
```
$ ./minikube-darwin-amd64 start --driver=hyperkit --cpus=2 --disk-size=10g --memory=4g --hyperkit-vpnkit-sock='auto'
😄  minikube v1.18.0-beta.0 on Darwin 11.2.1
✨  Using the hyperkit driver based on user configuration
💿  Downloading VM boot image ...
    > minikube-v1.18.0-beta.0.iso...: 65 B / 65 B [----------] 100.00% ? p/s 0s
    > minikube-v1.18.0-beta.0.iso: 212.99 MiB / 212.99 MiB  100.00% 5.47 MiB p/
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.20.2 preload ...
    > preloaded-images-k8s-v9-v1....: 491.22 MiB / 491.22 MiB  100.00% 6.01 MiB
🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=10240MB) ...
🔥  Deleting "minikube" in hyperkit ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: new-ing Hyperkit: stat /Users/r3ntg3n/Library/Containers/com.docker.docker/Data/s50: no such file or directory
```

**Comment by daehyeok** [comment]
@medyagh it need update driver binary.
@daehyeok  could you overwrite other binary and change permission?

```shell
#!/usr/bin/env bash

sudo rm "$HOME/.minikube/bin/docker-machine-driver-hyperkit"
curl "http://storage.googleapis.com/minikube-builds/10631/docker-machine-driver-hyperkit" --output "$HOME/.minikube/bin/docker-machine-driver-hyperkit"
chmod +x "$HOME/.minikube/bin/docker-machine-driver-hyperkit"
```

**Comment by daehyeok** [comment]
Just in case,  you delete whole minikube home dir for test.
Please make sure downloaded driver file is not overwritten again by released version. 
Following logs should not be included in your first run :)
```shell
I0301 09:33:08.013643   26835 out.go:119] 💾  Downloading driver docker-machine-driver-hyperkit:
💾  Downloading driver docker-machine-driver-hyperkit:
I0301 09:33:08.013754   26835 download.go:78] Downloading: https://github.com/kubernetes/minikube/releases/download/v1.18.0-beta.0/docker-machine-driver-hyperkit?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.18.0-beta.0/docker-machine-driver-hyperkit.sha256 -> /Users/daehyeok/.minikube/bin/docker-machine-driver-hyperkit
    > docker-machine-driver-hyper...: 65 B / 65 B [----------] 100.00% ? p/s 0s
    > docker-machine-driver-hyper...: 11.45 MiB / 11.45 MiB  100.00% 27.00 MiB
```

**Comment by dytyniuk** [comment]
@daehyeok an updated driver + minikube build works like a charm:

```
$ ./minikube-darwin start --driver=hyperkit --cpus=2 --disk-size=10g --memory=4g --hyperkit-vpnkit-sock='auto'
😄  minikube v1.18.0-beta.0 on Darwin 11.2.1
✨  Using the hyperkit driver based on user configuration
🔑  The 'hyperkit' driver requires elevated permissions. The following commands will be executed:

    $ sudo chown root:wheel /Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit
    $ sudo chmod u+s /Users/r3ntg3n/.minikube/bin/docker-machine-driver-hyperkit


Password:
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=10240MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v4
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

$ minikube ssh
                         _             _
            _         _ ( )           ( )
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ telnet 10.5.0.80 3306
Connected to 10.5.0.80
N
5.7.12-logV�x-O^FHsA�!)Y6
EpeV0Amysql_native_password^]
```

`10.5.0.80` host is the one behind OpenVPN connection currently active 🎉
