### ISSUE TITLE
minikube start:get a wrong img-repo access url(with double-protocol)

### ISSUE THREAD

**Issue by darkmatterjinx** [kubernetes/minikube#10449]
**Steps to reproduce the issue:** 

1.just ```minikube start```

notice: error info about docker pull image failt url contains a protocol at the begining,

**Full output of failed command:** 
😄  minikube v1.17.1 on Ubuntu 18.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 18.04.5 LTS
❗  This bare metal machine is having trouble accessing ```https://https://registry.aliyuncs.com/google_containers```
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.20.2 on Docker 19.03.6 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": exit status 1
stdout:
[init] Using Kubernetes version: v1.20.2
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'

stderr:
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image ```https://registry.aliyuncs.com/google_containers/kube-apiserver:v1.20.2```: output: invalid reference format
, error: exit status 1
	[ERROR ImagePull]: failed to pull image ```https://registry.aliyuncs.com/google_containers/kube-controller-manager:v1.20.2```: output: invalid reference format
, error: exit status 1
	[ERROR ImagePull]: failed to pull image ```https://registry.aliyuncs.com/google_containers/kube-scheduler:v1.20.2```: output: invalid reference format
, error: exit status 1
	[ERROR ImagePull]: failed to pull image ```https://registry.aliyuncs.com/google_containers/kube-proxy:v1.20.2```: output: invalid reference format
, error: exit status 1
	[ERROR ImagePull]: failed to pull image ```https://registry.aliyuncs.com/google_containers/pause:3.2```: output: invalid reference format
, error: exit status 1
	[ERROR ImagePull]: failed to pull image ```https://registry.aliyuncs.com/google_containers/etcd:3.4.13-0```: output: invalid reference format
, error: exit status 1
	[ERROR ImagePull]: failed to pull image ```https://registry.aliyuncs.com/google_containers/coredns:1.7.0```: output: invalid reference format
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

**Full output of `minikube start` command used, if not already included:**
minikube start --vm-driver=none --apiserver-ips=127.0.0.1 --image-mirror-country cn \
 --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.17.0.iso \
 --registry-mirror=https://registry.docker-cn.com \
 --image-repository=https://registry.aliyuncs.com/google_containers

if I use ```minikube start``` without other args,it will get same error

apparently,a useless ```https://``` in img-repo url and pull img url.

**Comment by priyawadhwa** [comment]
Hey @darkmatterjinx thanks for opening this issue. Just to clarify, it seems like the issue is that minikube is pulling from `https://https://registry.aliyuncs.com/google_containers` even though you didn't specify it in `minikube start`?

Are you located in China? This registry is a mirror of GCR that allows users in China to use minikube -- some details can be found in this PR https://github.com/kubernetes/minikube/pull/8555
