### ISSUE TITLE
vmware driver for minikube (using VmwareFusion) 

### ISSUE THREAD

**Issue by UdayP23** [kubernetes/minikube#10446]
unable to find any support for vmware Fusion driver for minikube. At first it was pointing towards installation of docker-machine-driver-vmware, i some tried to find this package over internet and installed docker-machine-driver-vmware_linux_amd64 and now it cannot find vmrun ..?? where do i find it ? Please cover this in the documentation .

[osboxes@osboxes ~]$ minikube start --alsologtostderr -v=7
I0211 14:23:04.593741   44353 out.go:229] Setting OutFile to fd 1 ...
I0211 14:23:04.595756   44353 out.go:281] isatty.IsTerminal(1) = true
I0211 14:23:04.595764   44353 out.go:242] Setting ErrFile to fd 2...
I0211 14:23:04.595768   44353 out.go:281] isatty.IsTerminal(2) = true
I0211 14:23:04.595854   44353 root.go:291] Updating PATH: /home/osboxes/.minikube/bin
I0211 14:23:04.596935   44353 out.go:236] Setting JSON to false
I0211 14:23:04.598867   44353 start.go:106] hostinfo: {"hostname":"osboxes","uptime":15357,"bootTime":1613034428,"procs":289,"os":"linux","platform":"centos","platformFamily":"rhel","platformVersion":"8.2.2004","kernelVersion":"4.18.0-193.el8.x86_64","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"0242d28f-a59c-4282-a224-807febd58c38"}
I0211 14:23:04.598925   44353 start.go:116] virtualization:  
I0211 14:23:04.600738   44353 out.go:119] 😄  minikube v1.17.1 on Centos 8.2.2004
😄  minikube v1.17.1 on Centos 8.2.2004
I0211 14:23:04.600847   44353 driver.go:315] Setting default libvirt URI to qemu:///system
I0211 14:23:04.601459   44353 out.go:119] ✨  Using the vmware driver based on user configuration
✨  Using the vmware driver based on user configuration
I0211 14:23:04.601471   44353 start.go:279] selected driver: vmware
I0211 14:23:04.601475   44353 start.go:702] validating driver "vmware" against <nil>
I0211 14:23:04.601484   44353 start.go:713] status for vmware: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "vmrun": executable file not found in $PATH Reason: Fix:Install vmrun Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/}
I0211 14:23:04.601781   44353 out.go:119] 

W0211 14:23:04.601827   44353 out.go:181] 🤷  Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in $PATH
🤷  Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in $PATH
W0211 14:23:04.602313   44353 out.go:181] 💡  Suggestion: Install vmrun
💡  Suggestion: Install vmrun
W0211 14:23:04.602345   44353 out.go:181] 📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/
I0211 14:23:04.603172   44353 out.go:119]

**Comment by medyagh** [comment]
@UdayP23 does the minikube suggestion help ? it seems like u dont have the vmware in the path 
```
🤷 Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in $PATH
W0211 14:23:04.602313 44353 out.go:181] 💡 Suggestion: Install vmrun
💡 Suggestion: Install vmrun
```

**Comment by medyagh** [comment]
Hi @UdayP23 , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by parag4u** [comment]
find vmrun and add to path, it works.
