### ISSUE TITLE
Exiting due to GUEST_START: wait 6m0s for node

### ISSUE THREAD

**Issue by n-mam** [kubernetes/minikube#10467]
Hi

I am new to kubernetes. For the past one week I have been playing around with minikube on windows primarily in the context of developing a CSI driver.. Today, I was testing my controller yaml couple of times and then at one point I shutdown the cluster before lunch. When I came back I was not able to start the cluster back again. I have reproduced the exact console logs below. Could you please advise what could be the issue here ? Prior to shutting down, I was iteratively deploying and then deleting the namespace and all the deployments seemed to be fine..

![image](https://user-images.githubusercontent.com/17683324/107849198-ae2a9580-6e1f-11eb-9b3e-f87fdd27f8ac.png)

**Comment by priyawadhwa** [comment]
Hey @n-mam thanks for opening this issue . It seems similar to https://github.com/kubernetes/minikube/issues/9070

Unfortunately I don't have better advice than what was written in that issue. I'd recommend deleting minikube and restarting it:

```
minikube delete
minikube start
```

if you can't sucessfully start the cluster, please provide the output of the following and we can try to diagnose the issue:

```
minikube start --alsologtostderr
```

**Comment by n-mam** [comment]
Thanks @priyawadhwa . This was happening intermittently.. sometime it did start fine. Since then, I moved to a minikube setup inside a linux vm and it is working fine there. I'll close this for now. Will update in case I find anything interesting
