### ISSUE TITLE
support $KUBE_ENABLE_INSECURE_REGISTY

### ISSUE THREAD

**Issue by bacongobbler** [kubernetes/minikube#1046]
When using kube-up, one nifty feature is the ability to disable https requirements for registries hosted in the local RFC1918 network via `KUBE_ENABLE_INSECURE_REGISTRY=true`. This feature allows the kubelet to talk to registries hosted within the cluster without requiring it to be backed by SSL.

This is in a similar vein to `minikube start --insecure-registry=10.0.0.0/24`, however I did not know if the services' virtual IPs will always be hosted on the 10.0.0.0/24 network. If this internal network is not configurable and is a known constant, I'd be more than happy to provide some documentation :)

The use case for this is:

```
$ kubectl get svc
registry     10.0.0.216   <none>        5000/TCP   2h
$ kubectl get po foo -o=jsonpath='{.spec.containers[0].image}'
10.0.0.216:5000/foo:564364b5fe5c9fdb80128dae96d3e3d1fb2b1208
```

**Comment by dlorenc** [comment]
It should be a constant. We set the service cluster IP range here: https://github.com/kubernetes/minikube/blob/a403a949dde02d0c9025f21a821bb4a65725bce9/pkg/util/constants.go#L23

and here: https://github.com/kubernetes/minikube/blob/7e313451c15832bb546055d84a2cbe508fdc3ff5/cmd/localkube/cmd/options.go#L31

We'd love a doc PR for this!

**Comment by bacongobbler** [comment]
Awesome! I'd be happy to doc this feature/hack. :)
