### ISSUE TITLE
Upgrade CRI-O to 1.20.0

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#10478]
Upgrade cri-o package, from 1.19.0 to 1.20.0

Tracker for #10476 (ISO) and #10477 (KIC)

**Comment by afbjorklund** [comment]
Ran into packaging issues, with storage.conf

**Comment by medyagh** [comment]
@afbjorklund could we close this ? since we merged https://github.com/kubernetes/minikube/pull/10477 ?
or do we need still update the VM too ?

**Comment by afbjorklund** [comment]
I think the VM was updated in #10476 was it not ?
