### ISSUE TITLE
Not able to start minikube on Cent os

### ISSUE THREAD

**Issue by Naresh-Challa** [kubernetes/minikube#10482]
**Steps to reproduce the issue:** 

1. minikube start --memory 5120 --cpus=4 --cache-images=false
2. Taking Pre loaded images into my /home/username.lastname/.minikube
3. Exiting due to GUEST_PROVISION: Failed to save config: open /home/naresh.challa/.minikube/profiles/minikube/config.json: no space left on device

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
> no space left on device

You need 20G free disk space, for minikube

See https://minikube.sigs.k8s.io/docs/start/
