### ISSUE TITLE
docker: Unable to get host IP: network: Template parsing error: template: :1: unexpected "=" in operand

### ISSUE THREAD

**Issue by michaelparra** [kubernetes/minikube#10489]
buenas tardes amigos, alguien me podra ayudar con lo siguiente, estoy aprendiendo y quiero terminar de levantar minikube en gcp
muchas gracias

**Los comandos necesarios para reproducir la incidencia**:
 minikube start --driver=docker
**El resultado completo del comando que ha fallado**: <details>

😄  minikube v1.17.1 on Centos 7.9.2009 (kvm/amd64)
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3700MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...E0216 19:11:21.917384    6538 start.go:99] Unable to get host IP: network inspect: docker network
 inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM
.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}
}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}
}]}": exit status 64
stdout:
stderr:
Template parsing error: template: :1: unexpected "=" in operand
E0216 19:11:21.918868    6538 out.go:330] unable to execute Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Na
me": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","M
TU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "Co
ntainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:
stderr:
Template parsing error: template: :1: unexpected "=" in operand
: template: Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet
": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.dr
iver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{i
f $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:
stderr:
Template parsing error: template: :1: unexpected "=" in operand
:1:253: executing "Failed to setup kubeconfig: network inspect: docker network inspect minikube --format \"{\"Name\": \"{{.Name}}\",\"Driver\": \"{{.Dr
iver}}\",\"Subnet\": \"{{range .IPAM.Config}}{{.Subnet}}{{end}}\",\"Gateway\": \"{{range .IPAM.Config}}{{.Gateway}}{{end}}\",\"MTU\": {{if (index .Opti
ons \"com.docker.network.driver.mtu\")}}{{(index .Options \"com.docker.network.driver.mtu\")}}{{else}}0{{end}},{{$first := true}} \"ContainerIPs\": [{{
range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}\"{{$v.IPv4Address}}\"{{end}}]}\": exit status 64\nstdout:\n\nstderr:\nTem
plate parsing error: template: :1: unexpected \"=\" in operand\n" at <index .Options "com.docker.network.driver.mtu">: error calling index: index of un
typed nil - returning raw string.
❌  Exiting due to GUEST_START: Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:
centos 7.9.2009  kernel 3.10.0-1160.15.2.el7.x86_64

**Comment by tstromberg** [comment]
I suspect this is fixed at master - do you mind trying? https://storage.googleapis.com/minikube/latest/minikube-linux-amd64

I think this was due to a really old version of Docker being installed.

**Comment by medyagh** [comment]
the reason is your Docker version is ancient, fixed on Master to support ancient dockers.

I recommend either wait for next version of minikube to support ancient docker or upgrade ur docker
