### ISSUE TITLE
Minikube start

### ISSUE THREAD

**Issue by ChocaGame** [kubernetes/minikube#10481]
minikube start --driver=none
😄 minikube v1.16.0 on Centos 7.2
✨ Using the none driver based on existing profile
👍 Starting control plane node minikube in cluster minikube
🔄 Restarting existing none bare metal machine for "minikube" ...
ℹ️ OS release is Tencent tlinux 2.2 (Final)
🐳 Preparing Kubernetes v1.20.0 on Docker ...

❌ Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc0001df348)
/usr/local/go/src/text/template/exec.go:166 +0x1b5
panic(0x7fecfdd2a540, 0x7fecfe066b20)
/usr/local/go/src/runtime/panic.go:522 +0x1b9
reflect.Value.FieldByIndex(0x7fecfdf0bac0, 0xc000478080, 0x99, 0xc000110940, 0x2, 0x2, 0x0, 0x7fecfe129d60, 0x7fecfdd2a540)
/usr/local/go/src/reflect/value.go:852 +0x32b
text/template.(*state).evalField(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7ffe20c8c444, 0xc, 0x7fecfe0e8f80, 0xc000446de0, 0xc0003cbac0, 0x1, ...)
/usr/local/go/src/text/template/exec.go:604 +0xa59
text/template.(*state).evalFieldChain(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7fecfe0e8f80, 0xc000446de0, 0xc0003cbab0, ...)
/usr/local/go/src/text/template/exec.go:554 +0x222
text/template.(*state).evalFieldNode(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0xc000446de0, 0xc0003cbac0, 0x1, 0x1, 0x7fecfddde980, 0x7fecff2fc710, ...)
/usr/local/go/src/text/template/exec.go:518 +0x116
text/template.(*state).evalCommand(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0xc000446db0, 0x7fecfddde980, 0x7fecff2fc710, 0x99, 0xc0001df0e0, 0x0, ...)
/usr/local/go/src/text/template/exec.go:456 +0x7aa
text/template.(*state).evalPipeline(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0xc0003db320, 0x0, 0xc0004ea3c8, 0x0)
/usr/local/go/src/text/template/exec.go:430 +0x11e
text/template.(*state).walk(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7fecfe0e8e00, 0xc000446e10)
/usr/local/go/src/text/template/exec.go:254 +0x49e
text/template.(*state).walk(0xc0001df2c8, 0x7fecfdf0bac0, 0xc000478080, 0x99, 0x7fecfe0e9040, 0xc000446d80)
/usr/local/go/src/text/template/exec.go:262 +0x145
text/template.(*Template).execute(0xc000478000, 0x7fecfe0890a0, 0xc0002494a0, 0x7fecfdf0bac0, 0xc000478080, 0x0, 0x0)
/usr/local/go/src/text/template/exec.go:217 +0x1ea
text/template.(*Template).Execute(...)
/usr/local/go/src/text/template/exec.go:200
github.com/docker/cli/cli/command/system.formatInfo(0x7fecfe122cc0, 0xc00027a000, 0x0, 0xc0003cb8a0, 0x1, 0x1, 0xc000297ec0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/docker/cli/cli/command/system/info.go:482 +0x1f6
github.com/docker/cli/cli/command/system.runInfo(0xc00021a500, 0x7fecfe122cc0, 0xc00027a000, 0xc0003cb260, 0x0, 0x0)
/go/src/github.com/docker/cli/cli/command/system/info.go:85 +0x344
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc00021a500, 0xc0003f53a0, 0x0, 0x2, 0x0, 0x0)
/go/src/github.com/docker/cli/cli/command/system/info.go:52 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00021a500, 0xc000219b10, 0x2, 0x2, 0xc00021a500, 0xc000219b10)
/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x467
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f8a00, 0xc000219b00, 0x3, 0x3)
/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ee
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
main.runDocker(0xc00027a000, 0x7fecfe08b440, 0xc000010020)
/go/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x1d5
main.main()
/go/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by ChocaGame** [comment]
Alguna solución para Linux …

**Comment by priyawadhwa** [comment]
Hey @ChocaGame thanks for opening this issue. Are you running `minikube start` as root? Running as root may help since you are using the none driver. I would try `sudo minikube start --driver none`. Please let us know if that fixes the issue for you!

**Comment by sharifelgamal** [comment]
I'll go ahead and close this for now, feel free to reopen if you still experience issues with the advice above.
