### ISSUE TITLE
output: lstat /tmp/tmpf-memory-asset392507495: no such file or directory

### ISSUE THREAD

**Issue by x8core** [kubernetes/minikube#10497]
Hi! I got such error, anyone has ideas how to troubleshoot this?

minikube start
😄  minikube v1.14.2 on Ubuntu 19.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset392507495 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset392507495: no such file or directory
: exit status 1
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset846354074 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset846354074: no such file or directory
: exit status 1

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset846354074 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset846354074: no such file or directory
: exit status 1

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
I believe this is a snap-related issue, and may have been fixed in minikube v1.17.1. Do you mind trying to upgrade to the latest minikube?

**Comment by medyagh** [comment]
same as https://github.com/kubernetes/minikube/issues/10772
