### ISSUE TITLE
Exiting due to RSRC_INSUFFICIENT_SYS_MEMORY: System only has 0MiB available, less than the required 1800MiB for Kubernetes

### ISSUE THREAD

**Issue by Jiu-hong** [kubernetes/minikube#10538]
**Steps to reproduce the issue:** 

I am doing according to this instruction exactly
https://phoenixnap.com/kb/install-minikube-on-ubuntu
Then I am failed at this step:
**minikube start**

**Full output of failed command:** 

😄  minikube v1.17.1 on Ubuntu 20.04 (vbox/amd64)
✨  Automatically selected the docker driver

⛔  Exiting due to RSRC_INSUFFICIENT_SYS_MEMORY: System only has 0MiB available, less than the required 1800MiB for Kubernetes

**Full output of `minikube start` command used, if not already included:**

😄  minikube v1.17.1 on Ubuntu 20.04 (vbox/amd64)
✨  Automatically selected the docker driver

⛔  Exiting due to RSRC_INSUFFICIENT_SYS_MEMORY: System only has 0MiB available, less than the required 1800MiB for Kubernetes

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
Sounds like a bug, can you post the output of `free -m` and `cat /proc/meminfo` ?

**Comment by afbjorklund** [comment]
Can also try this sample code
```go
package main

import (
	"fmt"

	"github.com/shirou/gopsutil/v3/mem"
)

func main() {
	v, _ := mem.VirtualMemory()

	fmt.Printf("Total: %v, Free:%v, UsedPercent:%f%%\n", v.Total, v.Free, v.UsedPercent)
}

```

**Comment by BLasan** [comment]
@afbjorklund Can I work on this? I faced the same issue

**Comment by Jiu-hong** [comment]
free -m output:
```
              total        used        free      shared  buff/cache   available
Mem:            978         166          97           0         714         642
Swap:             0           0           0

```
output of cat /proc/meminfo
```
MemTotal:        1002100 kB
MemFree:           99920 kB
MemAvailable:     657844 kB
Buffers:           52656 kB
Cached:           604272 kB
SwapCached:            0 kB
Active:           357724 kB
Inactive:         373036 kB
Active(anon):      82572 kB
Inactive(anon):      152 kB
Active(file):     275152 kB
Inactive(file):   372884 kB
Unevictable:       21940 kB
Mlocked:           18528 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:         95812 kB
Mapped:            62116 kB
Shmem:               808 kB
KReclaimable:      75148 kB
Slab:             123488 kB
SReclaimable:      75148 kB
SUnreclaim:        48340 kB
KernelStack:        2332 kB
PageTables:         1904 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:      501048 kB
Committed_AS:     740148 kB
VmallocTotal:   34359738367 kB
VmallocUsed:        9172 kB
VmallocChunk:          0 kB
Percpu:            11520 kB
HardwareCorrupted:     0 kB
AnonHugePages:         0 kB
ShmemHugePages:        0 kB
ShmemPmdMapped:        0 kB
FileHugePages:         0 kB
FilePmdMapped:         0 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
Hugetlb:               0 kB
DirectMap4k:       96256 kB
DirectMap2M:      952320 kB
```

**Comment by afbjorklund** [comment]
Thank you, that looks more normal. It's still too small to run minikube, but it's not zero...

You need 2 GB RAM in the VM (and also 2 vCPU as well), rather than the current 1 GB.

**Comment by afbjorklund** [comment]
@ BLasan The bug is here:

```go
        if sysLimit < minUsableMem {
                exitIfNotForced(reason.RsrcInsufficientSysMemory, "System only has {{.size}}MiB available, less than the required {{.req}}MiB for Kubernetes", out.V{"size": containerLimit, "driver": drvName, "req": minUsableMem})
        }
```

Should use sysLimit, not containerLimit.

The second value is only relevant to KIC.

**Comment by Jiu-hong** [comment]
Thank you @afbjorklund. I did not realize the minimium require for minikube. I got it now! Thank you again!

**Comment by afbjorklund** [comment]
We try to mention it here: https://minikube.sigs.k8s.io/docs/start/ but the code is supposed to verify it...
The requirement actually comes from `kubeadm`, so mostly trying to provide sane defaults for `minikube`

It's a bit confusing since it talks about the memory total _after_ the system and kernel take their share.
So even if you start out with a virtual hardware of 1024 MiB, then it only shows something like 978 MiB.

**Comment by BLasan** [comment]
> @BLasan The bug is here:
> 
> ```go
>         if sysLimit < minUsableMem {
>                 exitIfNotForced(reason.RsrcInsufficientSysMemory, "System only has {{.size}}MiB available, less than the required {{.req}}MiB for Kubernetes", out.V{"size": containerLimit, "driver": drvName, "req": minUsableMem})
>         }
> ```
> 
> Should use sysLimit, not containerLimit.
> 
> The second value is only relevant to KIC.

Yuh. Thanks for pointing us. Shall I send a PR for this?

**Comment by afbjorklund** [comment]
> Shall I send a PR for this?

Please do, the current message is confusing
