### ISSUE TITLE
Docker Image created during the functional testing are not getting removed once done

### ISSUE THREAD

**Issue by BLasan** [kubernetes/minikube#10539]
**To Reproduce**

1. Run `make functional`
2. Check docker images by running `docker images`

**Output of `docker images` command:**
```
$ docker images
REPOSITORY                                                TAG                                IMAGE ID       CREATED          SIZE
minikube-local-cache-test                                 functional-20210220224626-594968   3d0e01f439b0   14 minutes ago   30B
```

Those images should be removed once the `make functional` gets finished. This will be applicable for some other `make` commands too.
If this is good to proceed I would like to send a PR for this

**Comment by medyagh** [comment]
sounds like a good clean up idea

**Comment by BLasan** [comment]
> sounds like a good clean up idea

Would like to send a PR sir

**Comment by BLasan** [comment]
@medyagh Can I start working on this?

**Comment by priyawadhwa** [comment]
@BLasan sure go for it!
