### ISSUE TITLE
minikube start: Failed to setup kubeconfig

### ISSUE THREAD

**Issue by phper-xiao** [kubernetes/minikube#10534]
**重现问题所需的命令**：
minikube start --driver=docker
**失败的命令的完整输出**：<details>
😄  Centos 7.2 (amd64) 上的 minikube v1.17.1
✨  根据现有的配置文件使用 docker 驱动程序
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🐳  正在 Docker 20.10.2 中准备 Kubernetes v1.20.2…| E0220 16:59:16.499554   43783 start.go:99] Unable to get host IP: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

stderr:
Template parsing error: template: :1: unexpected "=" in operand
E0220 16:59:16.500490   43783 out.go:330] unable to execute Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

stderr:
Template parsing error: template: :1: unexpected "=" in operand
: template: Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

stderr:
Template parsing error: template: :1: unexpected "=" in operand
:1:253: executing "Failed to setup kubeconfig: network inspect: docker network inspect minikube --format \"{\"Name\": \"{{.Name}}\",\"Driver\": \"{{.Driver}}\",\"Subnet\": \"{{range .IPAM.Config}}{{.Subnet}}{{end}}\",\"Gateway\": \"{{range .IPAM.Config}}{{.Gateway}}{{end}}\",\"MTU\": {{if (index .Options \"com.docker.network.driver.mtu\")}}{{(index .Options \"com.docker.network.driver.mtu\")}}{{else}}0{{end}},{{$first := true}} \"ContainerIPs\": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}\"{{$v.IPv4Address}}\"{{end}}]}\": exit status 64\nstdout:\n\nstderr:\nTemplate parsing error: template: :1: unexpected \"=\" in operand\n" at <index .Options "com.docker.network.driver.mtu">: error calling index: index of untyped nil - returning raw string.

❌  Exiting due to GUEST_START: Failed to setup kubeconfig: network inspect: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}},{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }}{{if $first}}{{$first = false}}{{else}}, {{end}}"{{$v.IPv4Address}}"{{end}}]}": exit status 64
stdout:

stderr:
Template parsing error: template: :1: unexpected "=" in operand

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>
==> Docker <==
-- Logs begin at Sat 2021-02-20 08:53:24 UTC, end at Sat 2021-02-20 09:00:14 UTC. --
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.277226978Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.277253467Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.277272703Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.278631452Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.278652741Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.278670174Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.278681586Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.279892517Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.318802639Z" level=info msg="Loading containers: start."
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.320214327Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found in directory /lib/modules/3.10.107-1-tlinux2_kvm_guest-0049\n, error: exit status 1"
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.378759558Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.441153578Z" level=info msg="Loading containers: done."
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.451555779Z" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: opaque flag erroneously copied up, consider update to kernel 4.8 or later to fix" storage-driver=overlay2
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.451754291Z" level=info msg="Docker daemon" commit=8891c58 graphdriver(s)=overlay2 version=20.10.2
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.451823742Z" level=info msg="Daemon has completed initialization"
Feb 20 08:53:25 minikube systemd[1]: Started Docker Application Container Engine.
Feb 20 08:53:25 minikube dockerd[171]: time="2021-02-20T08:53:25.493392771Z" level=info msg="API listen on /run/docker.sock"
Feb 20 08:53:27 minikube systemd[1]: /lib/systemd/system/docker.service:13: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Feb 20 08:53:27 minikube systemd[1]: docker.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Feb 20 08:53:27 minikube systemd[1]: docker.service: Failed to set 'pids.max' attribute on '/docker/6334ffbbff655af6934195cf9c84733cfd92d8a7fbaffdacfb9b978e3e7b97ec/system.slice/docker.service' to 'max': Invalid argument
Feb 20 08:53:27 minikube systemd[1]: /lib/systemd/system/docker.service:13: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Feb 20 08:53:27 minikube systemd[1]: docker.service: Failed to set 'pids.max' attribute on '/docker/6334ffbbff655af6934195cf9c84733cfd92d8a7fbaffdacfb9b978e3e7b97ec/system.slice/docker.service' to 'max': Invalid argument
Feb 20 08:53:27 minikube systemd[1]: /lib/systemd/system/docker.service:13: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Feb 20 08:53:27 minikube systemd[1]: docker.service: Failed to set 'pids.max' attribute on '/docker/6334ffbbff655af6934195cf9c84733cfd92d8a7fbaffdacfb9b978e3e7b97ec/system.slice/docker.service' to 'max': Invalid argument
Feb 20 08:53:27 minikube systemd[1]: /lib/systemd/system/docker.service:13: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Feb 20 08:53:27 minikube systemd[1]: docker.service: Failed to set 'pids.max' attribute on '/docker/6334ffbbff655af6934195cf9c84733cfd92d8a7fbaffdacfb9b978e3e7b97ec/system.slice/docker.service' to 'max': Invalid argument
Feb 20 08:53:27 minikube systemd[1]: Stopping Docker Application Container Engine...
Feb 20 08:53:27 minikube dockerd[171]: time="2021-02-20T08:53:27.991045090Z" level=info msg="Processing signal 'terminated'"
Feb 20 08:53:27 minikube dockerd[171]: time="2021-02-20T08:53:27.991847105Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Feb 20 08:53:27 minikube dockerd[171]: time="2021-02-20T08:53:27.992197622Z" level=info msg="Daemon shutdown complete"
Feb 20 08:53:28 minikube systemd[1]: docker.service: Succeeded.
Feb 20 08:53:28 minikube systemd[1]: Stopped Docker Application Container Engine.
Feb 20 08:53:28 minikube systemd[1]: docker.service: Failed to set 'pids.max' attribute on '/docker/6334ffbbff655af6934195cf9c84733cfd92d8a7fbaffdacfb9b978e3e7b97ec/system.slice/docker.service' to 'max': Invalid argument
Feb 20 08:53:28 minikube systemd[1]: Starting Docker Application Container Engine...
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.091671652Z" level=info msg="Starting up"
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.093071607Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.093097245Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.093115309Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.093129676Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.093989228Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.094011811Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.094029404Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.094040635Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.095155857Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.129407140Z" level=info msg="Loading containers: start."
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.130703142Z" level=warning msg="Running modprobe bridge br_netfilter failed with message: modprobe: WARNING: Module br_netfilter not found in directory /lib/modules/3.10.107-1-tlinux2_kvm_guest-0049\n, error: exit status 1"
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.252365468Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.300575094Z" level=info msg="Loading containers: done."
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.309610541Z" level=warning msg="Not using native diff for overlay2, this may cause degraded performance for building images: opaque flag erroneously copied up, consider update to kernel 4.8 or later to fix" storage-driver=overlay2
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.309781742Z" level=info msg="Docker daemon" commit=8891c58 graphdriver(s)=overlay2 version=20.10.2
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.309823891Z" level=info msg="Daemon has completed initialization"
Feb 20 08:53:28 minikube systemd[1]: Started Docker Application Container Engine.
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.323785218Z" level=info msg="API listen on [::]:2376"
Feb 20 08:53:28 minikube dockerd[420]: time="2021-02-20T08:53:28.327539850Z" level=info msg="API listen on /var/run/docker.sock"
Feb 20 08:53:28 minikube systemd[1]: /lib/systemd/system/docker.service:13: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Feb 20 08:53:28 minikube systemd[1]: docker.service: Failed to set 'pids.max' attribute on '/docker/6334ffbbff655af6934195cf9c84733cfd92d8a7fbaffdacfb9b978e3e7b97ec/system.slice/docker.service' to 'max': Invalid argument
Feb 20 08:53:53 minikube systemd[1]: /lib/systemd/system/docker.service:13: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Feb 20 08:53:53 minikube systemd[1]: docker.service: Failed to set 'pids.max' attribute on '/docker/6334ffbbff655af6934195cf9c84733cfd92d8a7fbaffdacfb9b978e3e7b97ec/system.slice/docker.service' to 'max': Invalid argument
Feb 20 08:59:16 minikube systemd[1]: /lib/systemd/system/docker.service:13: Unknown key name 'StartLimitIntervalSec' in section 'Service', ignoring.
Feb 20 08:59:16 minikube systemd[1]: docker.service: Failed to set 'pids.max' attribute on '/docker/6334ffbbff655af6934195cf9c84733cfd92d8a7fbaffdacfb9b978e3e7b97ec/system.slice/docker.service' to 'max': Invalid argument

==> container status <==
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
time="2021-02-20T09:00:16Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"

==> describe nodes <==
E0220 17:00:16.729395   44426 logs.go:181] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.20.2/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.20.2/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
error: stat /var/lib/minikube/kubeconfig: no such file or directory
 output: "\n** stderr ** \nerror: stat /var/lib/minikube/kubeconfig: no such file or directory\n\n** /stderr **"

==> dmesg <==
[  +0.002839] death_row create: alloc new. net:ffff880422720f80
[  +0.814742] hashinfo destroy: put hashinfo net:ffff880422720f80 hash:ffff880427c10080
[  +5.322709] hashinfo create: new net:ffff880422721f00 get new hashinfo ffff880427c00000
[  +0.003040] death_row create: alloc new. net:ffff880422721f00
[  +0.886284] hashinfo destroy: put hashinfo net:ffff880422721f00 hash:ffff880427c00000
[Jan28 06:22] hashinfo create: new net:ffff880421051f00 get new hashinfo ffff880427c20100
[  +0.003047] death_row create: alloc new. net:ffff880421051f00
[  +0.877017] hashinfo destroy: put hashinfo net:ffff880421051f00 hash:ffff880427c20100
[  +7.940366] hashinfo create: new net:ffff88027d05be00 get new hashinfo ffff880427c30180
[  +0.002848] death_row create: alloc new. net:ffff88027d05be00
[  +0.844813] hashinfo destroy: put hashinfo net:ffff88027d05be00 hash:ffff880427c30180
[ +38.316401] hashinfo create: new net:ffff880421051f00 get new hashinfo ffff880427c10080
[  +0.003102] death_row create: alloc new. net:ffff880421051f00
[  +0.856637] hashinfo destroy: put hashinfo net:ffff880421051f00 hash:ffff880427c10080
[Jan28 06:23] hashinfo create: new net:ffff880421052e80 get new hashinfo ffff880427c00000
[  +0.002914] death_row create: alloc new. net:ffff880421052e80
[Jan28 06:32] hashinfo destroy: put hashinfo net:ffff880421052e80 hash:ffff880427c00000
[  +8.978518] hashinfo create: new net:ffff880422722e80 get new hashinfo ffff880427c20100
[  +0.002919] death_row create: alloc new. net:ffff880422722e80
[Jan28 06:33] hashinfo destroy: put hashinfo net:ffff880422722e80 hash:ffff880427c20100
[  +1.520947] hashinfo create: new net:ffff880421e81f00 get new hashinfo ffff880427c30180
[  +0.002925] death_row create: alloc new. net:ffff880421e81f00
[  +0.771979] hashinfo destroy: put hashinfo net:ffff880421e81f00 hash:ffff880427c30180
[  +6.574276] hashinfo create: new net:ffff880422723e00 get new hashinfo ffff880427c10080
[  +0.003219] death_row create: alloc new. net:ffff880422723e00
[Feb20 08:28] hashinfo create: new net:ffff88027d05cd80 get new hashinfo ffff880427c00000
[  +0.002951] death_row create: alloc new. net:ffff88027d05cd80
[  +0.897470] hashinfo destroy: put hashinfo net:ffff88027d05cd80 hash:ffff880427c00000
[  +0.072721] hashinfo create: new net:ffff880391558000 get new hashinfo ffff880427c20100
[  +0.002963] death_row create: alloc new. net:ffff880391558000
[  +0.117871] hashinfo create: new net:ffff8802bca50000 get new hashinfo ffff880427c30180
[  +0.003030] death_row create: alloc new. net:ffff8802bca50000
[Feb20 08:42] hashinfo destroy: put hashinfo net:ffff880391558000 hash:ffff880427c20100
[  +0.495979] hashinfo destroy: put hashinfo net:ffff8802bca50000 hash:ffff880427c30180
[ +15.280019] hashinfo create: new net:ffff8802c74c9f00 get new hashinfo ffff880427c00000
[  +0.000019] death_row create: alloc new. net:ffff8802c74c9f00
[  +0.852515] hashinfo destroy: put hashinfo net:ffff8802c74c9f00 hash:ffff880427c00000
[  +0.012747] hashinfo create: new net:ffff88027d05dd00 get new hashinfo ffff880427c20100
[  +0.000019] death_row create: alloc new. net:ffff88027d05dd00
[  +0.065451] hashinfo create: new net:ffff880391558f80 get new hashinfo ffff880427c30180
[  +0.000020] death_row create: alloc new. net:ffff880391558f80
[  +2.993351] hashinfo destroy: put hashinfo net:ffff88027d05dd00 hash:ffff880427c20100
[Feb20 08:43] hashinfo destroy: put hashinfo net:ffff880391558f80 hash:ffff880427c30180
[Feb20 08:47] hashinfo create: new net:ffff880421e82e80 get new hashinfo ffff880427c00000
[  +0.000020] death_row create: alloc new. net:ffff880421e82e80
[  +0.799211] hashinfo destroy: put hashinfo net:ffff880421e82e80 hash:ffff880427c00000
[  +0.077454] hashinfo create: new net:ffff8802c74cae80 get new hashinfo ffff880427c20100
[  +0.000019] death_row create: alloc new. net:ffff8802c74cae80
[  +0.071550] hashinfo create: new net:ffff88027d05ec80 get new hashinfo ffff880427c30180
[  +0.000019] death_row create: alloc new. net:ffff88027d05ec80
[  +3.238865] hashinfo destroy: put hashinfo net:ffff8802c74cae80 hash:ffff880427c20100
[Feb20 08:52] hashinfo destroy: put hashinfo net:ffff88027d05ec80 hash:ffff880427c30180
[Feb20 08:53] hashinfo create: new net:ffff88027d05ec80 get new hashinfo ffff880427c00000
[  +0.000020] death_row create: alloc new. net:ffff88027d05ec80
[  +0.816635] hashinfo destroy: put hashinfo net:ffff88027d05ec80 hash:ffff880427c00000
[  +0.058768] hashinfo create: new net:ffff8802c75f0f80 get new hashinfo ffff880427c20100
[  +0.000019] death_row create: alloc new. net:ffff8802c75f0f80
[  +0.049326] hashinfo create: new net:ffff880391559f00 get new hashinfo ffff880427c30180
[  +0.000021] death_row create: alloc new. net:ffff880391559f00
[  +2.915863] hashinfo destroy: put hashinfo net:ffff8802c75f0f80 hash:ffff880427c20100

==> kernel <==
 09:00:17 up 145 days, 20:11,  0 users,  load average: 0.01, 0.08, 0.12
Linux minikube 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04.1 LTS"

==> kubelet <==
-- Logs begin at Sat 2021-02-20 08:53:24 UTC, end at Sat 2021-02-20 09:00:17 UTC. --
-- No entries --

❗  unable to fetch logs for: describe nodes

</details>

**使用的操作系统版本**：
Linux VM-145-118-centos 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phper-xiao** [comment]
minikube version: v1.17.1
Docker version: 20.10.2

**Comment by sharifelgamal** [comment]
Based on the minikube start output, it would seem that you are trying to restart a cluster that is corrupted or broken in some way. My suggestion would be to run `minikube delete` then `minikube start` again and see what happens.

---


根据minikube start输出，您似乎正在尝试重新启动以某种方式损坏或损坏的群集。我的建议是再次运行“ minikube delete”，然后再次运行“ minikube start”，看看会发生什么。

**Comment by spowelljr** [comment]
Hi @phper-xiao, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

-----

嗨@phper-xiao，我们还没有收到您的回音，您还有这个问题吗？
此问题中没有足够的信息以使其无法操作，并且持续了足够长的时间，因此此问题很可能难以复制。

我将暂时关闭此问题，但是当您准备提供更多信息时，可以随时重新打开。
