### ISSUE TITLE
Problem was arise when Minikube start

### ISSUE THREAD

**Issue by Chiragmodha** [kubernetes/minikube#10547]
C:\Users\Chirag Modha>minikube start
* minikube v1.17.1 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
* Using the ssh driver based on existing profile
* Starting control plane node minikube in cluster minikube
! StartHost failed, but will try again: config: please provide an IP address
* Failed to start ssh bare metal machine. Running "minikube delete" may fix it: config: please provide an IP address

X Exiting due to GUEST_PROVISION: Failed to start host: config: please provide an IP address
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by afbjorklund** [comment]
Hmm, something went wrong for the initial run.

Try providing either Hyper-V or Docker, run `minikube delete` and then `minikube start` again ?

**Comment by afbjorklund** [comment]
Possibly same as #10516

**Comment by medyagh** [comment]
closing same as the other one
