### ISSUE TITLE
Setting up a bridged interface on Minikube VM with VirtualBox

### ISSUE THREAD

**Issue by 6monlambert** [kubernetes/minikube#10549]
Hello,

I would like to add a bridged interface on my Minikube VM using VirtualBox, or change the configuration of eth0 to use a bridge instead of the default NAT Network.
I run my Minikube on a VM (Ubuntu 20.04) on a vCenter, therefore my services/pods are accessible from this Ubuntu VM but not from the browser of my laptop. I'd like the minikube VM to get an IP address from the DHCP of my LAN router.

I was able to add an interface using VBoxManage : 
**Steps to reproduce the issue:** 

1. VBoxManage modifyvm --nic3 bridged ----bridgeadapter3 ens160

Then when I connect I can see the new interface but it does not get an IP address from the DHCP : 

2. minikube ssh
3. ifconfig -a

**Full output of failed command:** 

`eth2      Link encap:Ethernet  HWaddr 08:00:27:3D:AD:9F
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:66492 errors:0 dropped:41238 overruns:0 frame:0
          TX packets:1946 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:4284733 (4.0 MiB)  TX bytes:452632 (442.0 KiB)
`

Do you know how to set this up on BuildRoot ? Or change the eth0 interface to use a bridge adapter instead ?

**Full output of `minikube start` command used, if not already included:**

* minikube v1.17.1 on Ubuntu 20.04
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
* Verifying Kubernetes components...
* Enabled addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

Thanks a lot

**Comment by priyawadhwa** [comment]
Hey @6monlambert thanks for opening this issue. I've never tried to set up a bridge interface with virtualbox before, but I did find this blog post -- maybe that would have some useful info?

https://dpb587.me/post/2020/04/11/minikube-and-bridged-networking/
