### ISSUE TITLE
Machine does not exist

### ISSUE THREAD

**Issue by rothgar** [kubernetes/minikube#1055]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

If this is a BUG REPORT, please:
  - Fill in as much of the template below as you can.  If you leave out
    information, we can't help you as well.

In both cases, be ready for followup questions, and please respond in a timely
manner.  If we can't reproduce a bug or think a feature already exists, we
might close your issue.  If we're wrong, PLEASE feel free to reopen it and
explain why.
-->

**Minikube version** (use `minikube version`):
0.15.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Fedora 25
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **Docker version** (e.g. `docker -v`): Docker version 1.13.0, build 49bf474
- **Install tools**: 
- **Others**:
rpm -qa | grep VirtualBox
kmod-VirtualBox-4.9.5-200.fc25.x86_64-5.1.14-1.fc25.x86_64
VirtualBox-kmodsrc-5.1.14-1.fc25.x86_64
VirtualBox-server-5.1.14-1.fc25.x86_64
kmod-VirtualBox-4.9.3-200.fc25.x86_64-5.1.10-1.fc25.x86_64
kmod-VirtualBox-4.9.4-201.fc25.x86_64-5.1.14-1.fc25.x86_64
akmod-VirtualBox-5.1.14-1.fc25.x86_64
VirtualBox-5.1.14-1.fc25.x86_64

**What happened**:
`minikube start` does not start the VM. Ouput is

```
minikube -v 9 start
Starting local Kubernetes cluster...
Found binary path at /usr/local/bin/minikube
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:42995
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetState
(minikube) DBG | COMMAND: /bin/VBoxManage showvminfo minikube --machinereadable
(minikube) DBG | STDOUT:
(minikube) DBG | {
(minikube) DBG | }
(minikube) DBG | STDERR:
(minikube) DBG | {
(minikube) DBG | VBoxManage: error: Could not find a registered machine named 'minikube'
(minikube) DBG | VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
(minikube) DBG | VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2781 of file VBoxManageInfo.cpp
(minikube) DBG | }
E0130 21:30:14.093538    5270 start.go:96] Error starting host: Error getting state for host: machine does not exist.

 Retrying.
E0130 21:30:14.093979    5270 start.go:102] Error starting host:  Error getting state for host: machine does not exist
```

**What you expected to happen**:
minikube would start

**How to reproduce it** (as minimally and precisely as possible):
Install fedora 25
Install Virtualbox
run `minikube start`

**Anything else do we need to know**:
I can run other VMs but minikube always fails with this error. I have a separate fedora 25 laptop and minikube works fine there. I couldn't figure out how to fix my desktop.

**Comment by r2d4** [comment]
Can you check whats in `~/.minikube/machines/`?  Sometimes leftover machine configurations can make it think that the machine exists.

You should be able to run a `minikube delete` and then a subsequent `minikube start` to fix this

**Comment by rothgar** [comment]
Yep, indeed that fixed it. Thanks for the fast reply.

Maybe consider this issue a call to make the error more clear to fix this for people in the future.

**Comment by Naami** [comment]
i'm execute 

> minikube delete

 but it doesn't work for me :

**minikube start**
```
minikube start --v=999
Starting local Kubernetes cluster...
Found binary path at minikube.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:51344
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetState
(minikube) DBG | COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
(minikube) DBG | STDOUT:
(minikube) DBG | {
E0203 17:01:38.317474   12648 start.go:107] Error starting host: Error getting state for host: machine does not exist.

 Retrying.
(minikube) DBG | }
(minikube) DBG | STDERR:
(minikube) DBG | {
(minikube) DBG | VBoxManage.exe: error: Could not find a registered machine named 'minikube'
(minikube) DBG | VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
(minikube) DBG | VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2781 of file VBoxManageInfo.cpp
(minikube) DBG | }
E0203 17:01:38.322482   12648 start.go:113] Error starting host:  Error getting state for host: machine does not exist
```

**minikube version**
```
minikube version
minikube version: v0.16.0
```

**Comment by EriksonMurrugarra** [comment]
Make sure you are running as root or administrator

**Comment by esyekas** [comment]
Remove the cache files and folder worked for me
   rm  -rf home/.minikube/
