### ISSUE TITLE
please enable CONFIG_TUN in the vm image kernel config

### ISSUE THREAD

**Issue by ensonic** [kubernetes/minikube#1056]
FEATURE REQUEST
minikube version: v0.15.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="14.04.5 LTS, Trusty Tahr"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 14.04.5 LTS"
VERSION_ID="14.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
"DriverName": "virtualbox",
- **Docker version** (e.g. `docker -v`):
Docker version 1.12.6, build 78d1802

**What happened**:
I am deploying an image running openvpn into a minikube pod. It fails with
```
ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such device (errno=19)
```
To debug I run
```
minikube ssh
cat /proc/config.gz | grep "_TUN "
# CONFIG_TUN is not set
```

**What you expected to happen**:
TUN support enabled on the vm host kernel.
https://github.com/kubernetes/minikube/blame/master/deploy/iso/minikube-iso/board/coreos/minikube/linux-4.7_defconfig

**How to reproduce it** (as minimally and precisely as possible):
There is not simple repro as you need to configure a vpn before you can run it.

**Anything else do we need to know**:
This docker image has good info for a dockerized vpn setup: https://github.com/kylemanna/docker-openvpn.

**Comment by ensonic** [comment]
I am desperately trying to send a PR fixing it. I have change the linux-4.7_defconfig and run ```make minikube-iso```. I get a new ```out/buildroot/output/images/rootfs.iso9660```. I run my minikube with ```minikube start --iso-url=file://$PATH_TO_BUILD/out/buildroot/output/images/rootfs.iso9660```.
But nothing changed. Do I need to delete the cluster? Is there a way to verify what iso the cluster is actually using?

**Comment by dlorenc** [comment]
Yeah, you'll need to run "minikube delete" for the new ISO to get used.

**Comment by dlorenc** [comment]
Thanks for sending a PR!

**Comment by r2d4** [comment]
@enisoc you can check using 
```
$ cat ~/.minikube/machines/minikube/config.json  | grep iso
        "Boot2DockerURL": "file:///home/mrick/.minikube/cache/iso/minikube-v1.0.3.iso",
```

**Comment by enisoc** [comment]
@r2d4 Did you mean to tag @ensonic?

@ensonic Nice to meet you... :)

**Comment by electroma** [comment]
Have the same issue. It worked with 0.14 for sure.

**Comment by ensonic** [comment]
@r2d4 got it to work, learned a lot, PR sent. Will also sent a PR to update some of the docs in a bit.
