### ISSUE TITLE
add a local multi-arch kic image Make target

### ISSUE THREAD

**Issue by jiefenghe** [kubernetes/minikube#10577]
Previous single arch kicbase make target is removed at this [commit](https://github.com/kubernetes/minikube/commit/5d284c72f55602dd232d646852787e71039869bd).

It's is still very useful to have a local target, which is good for debugging. The initiative of this issue comes from this [discussion](https://kubernetes.slack.com/archives/C1F5CT6Q1/p1613893823024200).

The `--output` flag of `docker buildx` provides multiple ways to export the build results.
`local`: all result files to be exported to a pointed directory. (I tried and it takes a long time to build the result)
`tar`: writes all result files as a single tarball. On multi-platform builds all results will be put in sub-directories by their platform.
`oci`: writes the result manifest list as an OCI image layout tarball.
~`docker`: currently, this is not supported for multi-arch~
`image`: writes a manifest list
~`registry`~

In current implementation, we can pass the local build tag into `base-image` flag, and minikube will find the image [in local docker daemon](https://github.com/kubernetes/minikube/blob/v1.17.1/pkg/minikube/image/image.go#L87).

In proposed solution, minikube will load the tarball into the local daemon, or somehow provision the container from a minifest list.

**Comment by jiefenghe** [comment]
@ilya-zuyev Please let me know if you have any suggestions.

**Comment by ilya-zuyev** [comment]
Yeah, currently there's no way to build and store multi-arch images locally (`docker` output) and we have to use --push all the time.
When migrated to multi-arch kicbase we decided to remove the old make target after some internal discussion, to avoid extra complexity in Makefile and supporting two formats of kicbase image. We're going to add an option for local registry builds when/if `--output docker` is supported.

For now, may be it makes sense just to add an external script to build single-arch kicbase if you really need it?

**Comment by jiefenghe** [comment]
Cool, that makes sense. Closing it to wait for `--output docker` is supported!
