### ISSUE TITLE
kubeadm stderr is occasionally truncated

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#10570]
As noted in #10508 - I suspect there may be a recent regression in our ability to preserve kubeadm output, but it may also be a much older issue.

It might be worth checking against minikube v1.15 for instance, to see if the behavior changed, with an identical --kubernetes-version selected.

**Comment by spowelljr** [comment]
In-progress

**Comment by spowelljr** [comment]
I removed `session.Close()` from `cmd.Wait` as `cmd.Start` doesn't call it, now the stderr logs are there sometimes and sometimes not, there seems to be a race condition going on.

**Comment by tstromberg** [comment]
Nice work on solving this tricky race condition within an exceptionally tricky section of code.
