### ISSUE TITLE
minikube start issue

### ISSUE THREAD

**Issue by Dhairya-Dudhatra** [kubernetes/minikube#10588]
minikube --driver=none start     

 `😄  minikube v1.17.1 on Ubuntu 20.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 20.04.2 LTS
🐳  Preparing Kubernetes v1.20.2 on Docker  ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
	panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc00058d2a8)
	/usr/local/go/src/text/template/exec.go:170 +0x1b5
panic(0x55676d7670e0, 0x55676daa85a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x55676d9203e0, 0xc0002bc0c0, 0x99, 0xc000226710, 0x2, 0x2, 0x0, 0x55676db5f760, 0x55676d7670e0)
	/usr/local/go/src/reflect/value.go:883 +0x39e
text/template.(*state).evalField(0xc00058d228, 0x55676d9203e0, 0xc0002bc0c0, 0x99, 0x7ffed8ec12ea, 0xc, 0x55676db30620, 0xc00020fcb0, 0xc00033cf70, 0x1, ...)
	/usr/local/go/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc00058d228, 0x55676d9203e0, 0xc0002bc0c0, 0x99, 0x55676d9203e0, 0xc0002bc0c0, 0x99, 0x55676db30620, 0xc00020fcb0, 0xc00033cf30, ...)
	/usr/local/go/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc00058d228, 0x55676d9203e0, 0xc0002bc0c0, 0x99, 0xc00020fcb0, 0xc00033cf70, 0x1, 0x1, 0x55676d80c060, 0x55676eb65648, ...)
	/usr/local/go/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc00058d228, 0x55676d9203e0, 0xc0002bc0c0, 0x99, 0xc00020fc80, 0x55676d80c060, 0x55676eb65648, 0x99, 0xd0, 0x55676d8fffc0, ...)
	/usr/local/go/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc00058d228, 0x55676d9203e0, 0xc0002bc0c0, 0x99, 0xc0000ab9e0, 0xc0005ecb38, 0xc0005a3ee0, 0xc00058d0e0)
	/usr/local/go/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc00058d228, 0x55676d9203e0, 0xc0002bc0c0, 0x99, 0x55676db304a0, 0xc00020fce0)
	/usr/local/go/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc00058d228, 0x55676d9203e0, 0xc0002bc0c0, 0x99, 0x55676db306e0, 0xc00020fc50)
	/usr/local/go/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc0002bc040, 0x55676dac9f20, 0xc000221b00, 0x55676d9203e0, 0xc0002bc0c0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
	/usr/local/go/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x55676db5a480, 0xc0003c8750, 0x0, 0xc00033c770, 0x1, 0x1, 0xc0002d5c20, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/cli/command/system/info.go:490 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc00059f600, 0x55676db5a480, 0xc0003c8750, 0xc00031a200, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x37c
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc00059f600, 0xc00022d7c0, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00059f600, 0xc000606430, 0x2, 0x2, 0xc00059f600, 0xc000606430)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0002502c0, 0xc000606420, 0x3, 0x3)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc0003c8750, 0x55676dacc540, 0xc000010020)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

i am trying to solve this issue from yesterday but couldn't solve it.
i am also attaching a config file .

`apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCakNDQWU2Z0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRJeE1ESXlNakV6TVRFMU1Gb1hEVE14TURJeU1URXpNVEUxTUZvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTExQCnpUdFNJZ3UremVhaHZ6VExKUlBPVDFJY21odkRkOVRqYXo0MFUxdmJoYTgvTFpDYjErRXlBODdmamIrYzUzRXcKSG4zczFMVW42OXpIcUUrb1U0djVxbDFqMTZCSC9VOXJMMk5PNGZCdEdEZ1BqWlpCZ2VqVTl4dmpqdjh4dlR1ZgpRQ2Z5WUJDOVM5aU9LTnZXZndtZnRJRDVlcVJwVDNnRVIwRUJiVnJKaWpNNlF6dGpkRXZOSW5RSE1wZitEZEpGCkQvK0M5T09nU1czUjNxV0xGZkpIMUlIcEdzNDFSalNHZEt2RkJiUW5nSUI0K1c2ZDBDM1B2OEdoZkdQUDlyWjgKb2NHcWNZcWp1WVNwQjduWHVkTndXYXd3bUxDbldIb0FLZmdMWTI4NlFnMmorUWRUbTh1MkxoMzRQd2I4Q2xCOApoYXlEZmx0OUZuRnZNc0ZiSW9FQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQjBHQTFVZERnUVcKQkJUQTBXdjRZVkZ5ejFNUnJBUnhxOXFsMHJSWXl6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFTWkFwK2tRdQo1VFpwU2tTUjlqU3BDY0loM3c4dlFkWmNLT1cwQ0FucFZvcnpxTnZqa1psQ2tsN2xzZmxPdFd1dGpNcHYyRVlXCm4raDQ3WWFXQ1gvRkNVVTVMNjRqS2xXU05PNjNYOERPcGlnUit1K0ZWaS8zM3l2VGhkNTlyRTFFR2VhZW10d08KNDRTVzZKbis0Z2h3VHVEMUczejJ3WUsweWxLc0k1MmF2SE8wQlJBVUgvaDQzSTlpS2t5cmhhdXpFY1JsVmh6UQpEMnJWMEVwaTdBME9Db082N3YwWnJRTVAvQW9sRjFVZUxiUXU4N2hZUmIvak52bkdrcXQ3dWU2cC9Zcm9CSnZ6CnlnUEhDVmtJVndBRkV3eE9NSmk4MGZZdlNndGY0MEY2T0pJOEp1NWE4bUdZYzg5QjZZakMzVWlBeThaeDJMeWUKN3ZlZFNvSjlveGJNZEE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://control-plane.minikube.internal:6443
  name: mk
contexts:
- context:
    cluster: mk
    user: kubernetes-admin
  name: kubernetes-admin@mk
current-context: ""
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFekNDQWZ1Z0F3SUJBZ0lJQnF6c0dZd3pxdTh3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2JXbHVhV3QxWW1WRFFUQWVGdzB5TVRBeU1qSXhNekV4TlRCYUZ3MHlNakF5TWpNeE16RTVNRGhhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW1QMFBickM2YzhCVFBDUGEKWEhCV0xHODdhN3V6S0UvVUplWS95YktHQmQyQ2k0eUxGbXRNMndmZEtlYnppa1FoODZUNCtmWHF6NTVZMUx2dgo4bVBnUUM5VnNHTGwvU0lzemhTcDA0MFNjQU9iTlpmVzE1dU03d3dFeHcvM0syNCs5ZmdVcXlRYjFLa09NQnhGCmVEclFtVCt3T0E3TUI2UkduR1ZUbzF5R0lIQmtRZ09FRUwyeEZ2UUQ0VTh2KzByMStROGVxUWE4OGo1VndkWWQKRnNicURmSlNvRTJQVkJiNmhKcVkvS0o3c0xDVEtLRm9QRVVQVUF5ZnFSNG0ybXBlbnNQZHByeFU0WTZML05HUwo4VXU0eTNYZ1JqYVZBZkdHcE0xMk1qTWpTTmJ2QnZ6dnNpS20yUmlxTFVrdTJKRXdUakhSQUlGblZRQWcxczkyCjkvQlZGd0lEQVFBQm8wZ3dSakFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0h3WURWUjBqQkJnd0ZvQVV3TkZyK0dGUmNzOVRFYXdFY2F2YXBkSzBXTXN3RFFZSktvWklodmNOQVFFTApCUUFEZ2dFQkFJUXMrR0xUTlE0L3UyK2tpbXNGeCttWGNhZDhFazB0TlJUYTdSdThiTkJqcGI3NzlYVHp6Q0RPCnJZZllFRFRLbkoyQmorMFpqbFpvcHZIUldNdjhsU2xwbXl5R0t2K0dIbkFhWHNWSkd2QnY1ODZqaC9CeFNybTcKZ2pCSWJIb3RacGpHeitXb1ZxOXVzRWNGTElrdkd3Z3pWdnhLR09mamFiUk15bk10NWhOOW5ZV1MvbHNoUlZDdgpGMTlNSjhYakxUbnZXOU9xU2xtMkZ6dGRWMEt2U05YQmxkZzl2eXA3elJjSWt6VlBaVXJGeWc0Zi90WUdUNmF6CjJibThmb2tXZUxIRXVXOXZGeXFZUlhnY0x3MUxBbEZjaWcyK2x2Rm5iNXArT0lRbXRUR1JuQWlMakpCSm04QzEKeTRvVjF5eTQwY0pIU0lSd3Y5bXErR2NHNmE1Y2lnRT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbVAwUGJyQzZjOEJUUENQYVhIQldMRzg3YTd1ektFL1VKZVkveWJLR0JkMkNpNHlMCkZtdE0yd2ZkS2ViemlrUWg4NlQ0K2ZYcXo1NVkxTHZ2OG1QZ1FDOVZzR0xsL1NJc3poU3AwNDBTY0FPYk5aZlcKMTV1TTd3d0V4dy8zSzI0KzlmZ1VxeVFiMUtrT01CeEZlRHJRbVQrd09BN01CNlJHbkdWVG8xeUdJSEJrUWdPRQpFTDJ4RnZRRDRVOHYrMHIxK1E4ZXFRYTg4ajVWd2RZZEZzYnFEZkpTb0UyUFZCYjZoSnFZL0tKN3NMQ1RLS0ZvClBFVVBVQXlmcVI0bTJtcGVuc1BkcHJ4VTRZNkwvTkdTOFV1NHkzWGdSamFWQWZHR3BNMTJNak1qU05idkJ2enYKc2lLbTJSaXFMVWt1MkpFd1RqSFJBSUZuVlFBZzFzOTI5L0JWRndJREFRQUJBb0lCQUZ2d2tNcXJxSkdSZmpRQgpNK1FqbXBYL2pzMHlzdnRCNWpPVWlMY1U4MWdwQTZBTHFUYWk2MEFpSExabTFlczlBTTVrVVVBZW1xdUU5TXQ3CjJqcG43VWVGYXRDaXpxWnVXRkRNdURhcmErNG5MS3ByZ3JCMkNaOUxNTC9VaDJ6eFJ5TVlvSXN0R3hDVlBES0wKZXZCRElFTkl0QVVzVjA4c1dVYjUyZWF0M3VrMDFBOStua1BhMEc3Ym1UWDROYS9qaTZJR05MZTRvV0wyTTBVeQo2WGl0WjRrNTJPb1hTaHNzNUt2aXpCbHZUaDA2WDN5ekRYTlM5cVVYVGtoaGlZVmEwQ1lrN3VMcE9JZEhTWHpDClhOREJ2UjQ1MWNicFg5bjJ0SG9weG1TeEhJektzcURyaFg2c0RoeVl0bmxlR0QyVW11a0hxdm8vdWd6TWsyZG0KZVN5UW9oa0NnWUVBd1ptRU5WdzhyS2szR1piZXVydzJJdkVVRTBYY1BWY3FnZVJGTFJONHREc1pQMmVEcDVCQQp2eStmRGpSR1hoaDNHTVRkc3hFeTlQL3VMTXUzVVF6U24yQjdKZnFndk1QWVhDTXBuZXFqbGJHYUVndnZtb29ECmlyUXkzdkw4UG9NVkRvMG1uZUF3aUsyQTRjRkk0TUxhaW5YTDJJUDVqUDlDSXlXQVl3ZjJ3dk1DZ1lFQXlreVkKeHBmbHNXVGtMazFyaHRxbU9YcStuQmlPdHJwV25PbVZWeFFkZXBVVlEzcE9oYktLWHp1SVJBNHFvTVhiZjFLYgpqbjI5bjVGYjc0ZDNtd3RjQjJMcElST0hEN0V3bndtdllnRFBTeVc0cDJZUFVpdC83L1laNXNWSFllV2EvQ2xoClIzQTkzTzdFZzljc3lXQ3lud1hTbDA1eXN6d0JQTzQvSVRyQ0JrMENnWUFqeUUwUVU4RC9KTE9EYmtneWVYRUUKR2t6Y2x3L3k0blovMVlJWHA3NnFpVFhNYTBTQkp2OWdsdHV1RTJsaUlPRjZXWUNraFN4RzdqckdXc3pDRlQyawpxWDk1Y0k1ZTlVKzdEK0MwU0ZiOTV2cVVGVkt1M0kxMUNJTlNnOVN0ZFNyaUtxS1ZrWWRHNjlLalowY2lDOEc2Cno3VGlpdG9IL25IcDd4ZUF0a3Nja3dLQmdRQ1JRVmg5V0RuY0d4WmdUTVRGYXAvcUs4RkxjYktmYjhLYkhubFYKc2lMTWp0bGF2eW84ZzRzcGdDU0N3UzFJaldqaXpoelZ2bUYyZnJmbGtINkgvQ3NUUHFrb1Q4NHRyVXU5RmdZeApOMldnanJBOHVtS0wzS0liV2JrVlkxZXk2bHRUYmg3a1hhcDl4WStqSHRDUXMvYnRpZy9CQnRvQzZqWDFXeGhICk10cDREUUtCZ0JYREJSMGJVN2hReTFOT1JNTmtldEpsaU1WL0J2RTBoaEU2bHZWNWo4blYya2JWUUE2ckVqc2QKMDJQeFZtS2UvUUpucEtuSkp2SlNOaFRxdDg1dGNIM1FxUHpUSVJlY2NydDlxRjBHakNJTCt5K29qT3pLNnR3dAowYnhRR3lydW5JQ0NkUU9XRlZCR1BMSU1lOHRkWnVoMUJaTm9uNUJSaENsQ05JcnBWRmZRCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==

`

**Comment by Dhairya-Dudhatra** [comment]
I am sorry for poor formating .
also ask if any further info. is required.

**Comment by spowelljr** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The full output of the command you are using by adding --alsologtostderr, for example:

```
$ minikube start --alsologtostderr
```
- Also the full the output of the
```
$ minikube logs
```
This will help us isolate the problem further. Thank you!

For formatting, you could do this to improve the readability:
```
`minikube start logs`
<details>
Paste logs here
</details>
```
Looks like:
`minikube start logs`
<details>
Paste logs here
</details>

/triage needs-information
/kind support

**Comment by afbjorklund** [comment]
@spowelljr : Currently docker shows this "panic", when the daemon is not running. Solution is to start docker.

See #10165

**Comment by Dhairya-Dudhatra** [comment]
`minikube start --driver=none --alsologtostderr`
<details>
I0225 10:36:27.973093    9868 out.go:229] Setting OutFile to fd 1 ...
I0225 10:36:27.982694    9868 out.go:281] isatty.IsTerminal(1) = true
I0225 10:36:27.982780    9868 out.go:242] Setting ErrFile to fd 2...
I0225 10:36:27.982830    9868 out.go:281] isatty.IsTerminal(2) = true
I0225 10:36:27.986371    9868 root.go:291] Updating PATH: /home/dd/.minikube/bin
W0225 10:36:28.014949    9868 root.go:266] Error reading config file at /home/dd/.minikube/config/config.json: open /home/dd/.minikube/config/config.json: no such file or directory
I0225 10:36:28.051510    9868 out.go:236] Setting JSON to false
I0225 10:36:28.078823    9868 start.go:106] hostinfo: {"hostname":"dhairya-HP","uptime":3554,"bootTime":1614226034,"procs":286,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.8.0-34-generic","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"d1d1bf21-244e-46bb-8092-36a80d05f637"}
I0225 10:36:28.079072    9868 start.go:116] virtualization: kvm host
I0225 10:36:28.251163    9868 out.go:119] 😄  minikube v1.17.1 on Ubuntu 20.04
😄  minikube v1.17.1 on Ubuntu 20.04
I0225 10:36:28.251511    9868 notify.go:126] Checking for updates...
I0225 10:36:28.371558    9868 exec_runner.go:52] Run: systemctl --version
I0225 10:36:28.385845    9868 driver.go:315] Setting default libvirt URI to qemu:///system
I0225 10:36:28.640181    9868 out.go:119] ✨  Using the none driver based on existing profile
✨  Using the none driver based on existing profile
I0225 10:36:28.640276    9868 start.go:279] selected driver: none
I0225 10:36:28.640298    9868 start.go:702] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.17@sha256:1cd2e039ec9d418e6380b2fa0280503a72e5b282adea674ee67882f59f4f546e Memory:2900 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.43.166 Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[dashboard:true] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] Network: MultiNodeRequested:false}
I0225 10:36:28.640617    9868 start.go:713] status for none: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:running the 'none' driver as a regular user requires sudo permissions Reason: Fix: Doc:}
I0225 10:36:28.673592    9868 out.go:119] 

W0225 10:36:28.674112    9868 out.go:181] 🤷  Exiting due to PROVIDER_NONE_NOT_FOUND: The 'none' provider was not found: running the 'none' driver as a regular user requires sudo permissions
🤷  Exiting due to PROVIDER_NONE_NOT_FOUND: The 'none' provider was not found: running the 'none' driver as a regular user requires sudo permissions
I0225 10:36:28.857021    9868 out.go:119] 
</details>

`minikube logs`
<details>
Feb 25 10:37:26 dhairya-HP systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Feb 25 10:37:26 dhairya-HP systemd[1]: kubelet.service: Failed with result 'exit-code'.
Feb 25 10:37:27 dhairya-HP systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 4770.
Feb 25 10:37:27 dhairya-HP systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Feb 25 10:37:27 dhairya-HP systemd[1]: Started kubelet: The Kubernetes Node Agent.
Feb 25 10:37:27 dhairya-HP systemd[10132]: kubelet.service: Failed to execute command: No such file or directory
Feb 25 10:37:27 dhairya-HP systemd[10132]: kubelet.service: Failed at step EXEC spawning /var/lib/minikube/binaries/v1.20.2/kubelet: No such file or directory
Feb 25 10:37:27 dhairya-HP systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Feb 25 10:37:27 dhairya-HP systemd[1]: kubelet.service: Failed with result 'exit-code'.
Feb 25 10:37:27 dhairya-HP systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 4771.
Feb 25 10:37:27 dhairya-HP systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Feb 25 10:37:27 dhairya-HP systemd[1]: Started kubelet: The Kubernetes Node Agent.
Feb 25 10:37:27 dhairya-HP systemd[10155]: kubelet.service: Failed to execute command: No such file or directory
Feb 25 10:37:27 dhairya-HP systemd[10155]: kubelet.service: Failed at step EXEC spawning /var/lib/minikube/binaries/v1.20.2/kubelet: No such file or directory
Feb 25 10:37:27 dhairya-HP systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Feb 25 10:37:27 dhairya-HP systemd[1]: kubelet.service: Failed with result 'exit-code'.
Feb 25 10:37:28 dhairya-HP systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 4772.
Feb 25 10:37:28 dhairya-HP systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Feb 25 10:37:28 dhairya-HP systemd[1]: Started kubelet: The Kubernetes Node Agent.
Feb 25 10:37:28 dhairya-HP systemd[10156]: kubelet.service: Failed to execute command: No such file or directory
Feb 25 10:37:28 dhairya-HP systemd[10156]: kubelet.service: Failed at step EXEC spawning /var/lib/minikube/binaries/v1.20.2/kubelet: No such file or directory
Feb 25 10:37:28 dhairya-HP systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Feb 25 10:37:28 dhairya-HP systemd[1]: kubelet.service: Failed with result 'exit-code'.
Feb 25 10:37:29 dhairya-HP systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 4773.
Feb 25 10:37:29 dhairya-HP systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Feb 25 10:37:29 dhairya-HP systemd[1]: Started kubelet: The Kubernetes Node Agent.
Feb 25 10:37:29 dhairya-HP systemd[10163]: kubelet.service: Failed to execute command: No such file or directory
Feb 25 10:37:29 dhairya-HP systemd[10163]: kubelet.service: Failed at step EXEC spawning /var/lib/minikube/binaries/v1.20.2/kubelet: No such file or directory
Feb 25 10:37:29 dhairya-HP systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Feb 25 10:37:29 dhairya-HP systemd[1]: kubelet.service: Failed with result 'exit-code'.
Feb 25 10:37:30 dhairya-HP systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 4774.
Feb 25 10:37:30 dhairya-HP systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Feb 25 10:37:30 dhairya-HP systemd[1]: Started kubelet: The Kubernetes Node Agent.
Feb 25 10:37:30 dhairya-HP systemd[10169]: kubelet.service: Failed to execute command: No such file or directory
Feb 25 10:37:30 dhairya-HP systemd[10169]: kubelet.service: Failed at step EXEC spawning /var/lib/minikube/binaries/v1.20.2/kubelet: No such file or directory
Feb 25 10:37:30 dhairya-HP systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
Feb 25 10:37:30 dhairya-HP systemd[1]: kubelet.service: Failed with result 'exit-code'.

❗  unable to fetch logs for: describe nodes
</details>
 also my config file is in ~/.kube/config and not in ~/.minikube is it fine ?

**Comment by spowelljr** [comment]
@Dhairya-Dudhatra You're getting the error `running the 'none' driver as a regular user requires sudo permissions`.

If you look at the documentation for using the none driver https://minikube.sigs.k8s.io/docs/drivers/none/#usage you will see the way to start minikkube is `sudo -E minikube start --driver=none`
