### ISSUE TITLE
Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2

### ISSUE THREAD

**Issue by zeshahid** [kubernetes/minikube#10589]
kube@ubuntu:~$ minikube start
😄  minikube v1.17.1 on Ubuntu 20.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 20.04.2 LTS
🐳  Preparing Kubernetes v1.20.2 on Docker  ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
	panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc000565320)
	/usr/lib/go-1.13/src/text/template/exec.go:170 +0x1b5
panic(0x55d12131c200, 0x55d121671e10)
	/usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x55d121500da0, 0xc00004edc0, 0x99, 0xc00010c9f0, 0x2, 0x2, 0x0, 0x55d12172ea00, 0x55d12131c200)
	/usr/lib/go-1.13/src/reflect/value.go:876 +0x39e
text/template.(*state).evalField(0xc0005652a0, 0x55d121500da0, 0xc00004edc0, 0x99, 0x7ffe3ddc2401, 0xc, 0x55d1216fdaa0, 0xc0004e98f0, 0xc0003ffb20, 0x1, ...)
	/usr/lib/go-1.13/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc0005652a0, 0x55d121500da0, 0xc00004edc0, 0x99, 0x55d121500da0, 0xc00004edc0, 0x99, 0x55d1216fdaa0, 0xc0004e98f0, 0xc0003ffb10, ...)
	/usr/lib/go-1.13/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc0005652a0, 0x55d121500da0, 0xc00004edc0, 0x99, 0xc0004e98f0, 0xc0003ffb20, 0x1, 0x1, 0x55d1213cfaa0, 0x55d122626bb8, ...)
	/usr/lib/go-1.13/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc0005652a0, 0x55d121500da0, 0xc00004edc0, 0x99, 0xc0004e98c0, 0x55d1213cfaa0, 0x55d122626bb8, 0x99, 0xd0, 0x55d1214d8ae0, ...)
	/usr/lib/go-1.13/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc0005652a0, 0x55d121500da0, 0xc00004edc0, 0x99, 0xc00043cc60, 0xc0004ef038, 0xc0004f3930, 0xc000565158)
	/usr/lib/go-1.13/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc0005652a0, 0x55d121500da0, 0xc00004edc0, 0x99, 0x55d1216fd920, 0xc0004e9920)
	/usr/lib/go-1.13/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc0005652a0, 0x55d121500da0, 0xc00004edc0, 0x99, 0x55d1216fdb60, 0xc0004e9890)
	/usr/lib/go-1.13/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc00004ed40, 0x55d121695520, 0xc0002b2090, 0x55d121500da0, 0xc00004edc0, 0x0, 0x0)
	/usr/lib/go-1.13/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
	/usr/lib/go-1.13/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x55d1217298c0, 0xc0004ba000, 0x0, 0xc0003ffad0, 0x1, 0x1, 0xc00004ed00, 0x0, 0x0, 0x0, ...)
	/build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cli/command/system/info.go:478 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc0004d6780, 0x55d1217298c0, 0xc0004ba000, 0xc0003feba0, 0x0, 0x0)
	/build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cli/command/system/info.go:85 +0x343
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc0004d6780, 0xc00043eda0, 0x0, 0x2, 0x0, 0x0)
	/build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cli/command/system/info.go:52 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc0004d6780, 0xc0004e8a60, 0x2, 0x2, 0xc0004d6780, 0xc0004e8a60)
	/build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc00042a000, 0xc0004e8a50, 0x3, 0x3)
	/build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
main.runDocker(0xc0004ba000, 0x55d121697a40, 0xc000010020)
	/build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x1d3
main.main()
	/build/docker.io-2kpJHD/docker.io-19.03.8/.gopath/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

kube@ubuntu:~$ minikube status
minikube
type: Control Plane
host: Stopped
kubelet: Stopped
apiserver: Stopped
kubeconfig: Stopped
timeToStop: Nonexistent

kube@ubuntu:~$ minikube logs
🤷  The control plane node must be running for this command
👉  To start a cluster, run: "minikube start"
kube@ubuntu:~$ 

***********************************************************

root@ubuntu:/etc/docker# docker info
Client:
 Debug Mode: false

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 11
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-43-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 7.22GiB
 Name: ubuntu
 ID: CT2I:CNVO:AXJD:U6IP:N7GT:ZVW5:QLRY:LUZO:AGAT:YVNA:PCWT:FMJJ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

**Comment by priyawadhwa** [comment]
Hey @zeshahid thanks for opening this issue. It looks similar to https://github.com/kubernetes/minikube/issues/9744. 

Based on this comment, could you try adding the user you are running under to the docker group? Thank you. https://github.com/kubernetes/minikube/issues/9744#issuecomment-753595656

**Comment by ilya-zuyev** [comment]
Duplicate https://github.com/kubernetes/minikube/issues/9744

**Comment by rajesh444aws** [comment]
Hi @zeshahid Zeeshan Shahid, how you resolve this issue

**Comment by hausliu** [comment]
`sudo minikube start` 
I use this command to solve the problem. Maybe it's a problem of permission.

**Comment by nickdine** [comment]
> `sudo minikube start` I use this command to solve the problem. Maybe it's a problem of permission.

Not work for me . Got "❌  Exiting due to DRV_AS_ROOT: The "docker" driver should not be used with root privileges.
"
