### ISSUE TITLE
minikube service error : no DISPLAY environment variable specified

### ISSUE THREAD

**Issue by devunixguy** [kubernetes/minikube#10584]
**Steps to reproduce the issue:** 
~]$ minikube start
* minikube v1.13.0 on Redhat 7.5
* Using the docker driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Creating docker container (CPUs=2, Memory=2200MB) ...
! This container is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.19.0 on Docker 19.03.8 ...
* Verifying Kubernetes components...
* Enabled addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube" by default

Minikube dashboard also failed
~]$ minikube dashboard
* Enabling dashboard ...

* Verifying dashboard health ...
* Launching proxy ...
* Verifying proxy health ...
* Opening http://127.0.0.1:39808/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
START /usr/bin/firefox "http://127.0.0.1:39808/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/"
Error: no DISPLAY environment variable specified
xdg-open: no method available for opening 'http://127.0.0.1:39808/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/'

X Exiting due to HOST_BROWSER: failed to open browser: exit status 3

 ~]$ minikube service hello-minikube --url
http://172.17.0.3:30338
 ----> but not able to connect the url, timing our after couple of minutes

~]$ minikube service hello-minikube
|-----------|----------------|-------------|-------------------------|
| NAMESPACE |      NAME      | TARGET PORT |           URL           |
|-----------|----------------|-------------|-------------------------|
| default   | hello-minikube |        8080 | http://172.17.0.3:30338 |
|-----------|----------------|-------------|-------------------------|
* Opening service default/hello-minikube in default browser...
START /usr/bin/firefox "http://172.17.0.3:30338"
Error: cannot open display: localhost:0.0
xdg-open: no method available for opening 'http://172.17.0.3:30338'

X Exiting due to HOST_BROWSER: exit status 3
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by spowelljr** [comment]
Hi @devunixguy, thanks for reporting your issue.

Could you check if your `DISPLAY` env is set and report back. If it's not set, set it and try running the command again.

**Comment by devunixguy** [comment]
Thanks Steve. I did try setting up the DISPLAY env but still facing the same issue.  Please suggest. 

Initially this machine didn't had any browser, so I have installed firefox. 

Even installed, xorg-x11-xauth and libXmu. 

per a colleagues suggesting, updated X11 config in /etc/ssh/sshd_config
X11UseLocalhost no   (it was 'yes' before)

~]$ export DISPLAY=localhost:0.0
 ~]$ echo $DISPLAY
localhost:0.0

 ~]$ minikube service hello-minikube
|-----------|----------------|-------------|-------------------------|
| NAMESPACE |      NAME      | TARGET PORT |           URL           |
|-----------|----------------|-------------|-------------------------|
| default   | hello-minikube |        8080 | http://172.17.0.3:30338 |
|-----------|----------------|-------------|-------------------------|
* Opening service default/hello-minikube in default browser...
START /usr/bin/firefox "http://172.17.0.3:30338"
Error: cannot open display: localhost:0.0                                                              ----> Not able to open the display
xdg-open: no method available for opening 'http://172.17.0.3:30338'

X Exiting due to HOST_BROWSER: exit status 3
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by afbjorklund** [comment]
You need to make sure that there is an X11 server running, normally `startx` will set up the display for you.

**Comment by spowelljr** [comment]
Hi @devunixguy, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
