### ISSUE TITLE
auto-pause: make time to pause configurable

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10595]

**Comment by daehyeok** [comment]
we need to add extra flag into `start` command  because, we don't have any flag not exists for addon's option. so  is it right?
How about use `--addon-config` with `{addon_name}.{key}={value}` 
e.g.) 
```minikube start ..... --addon-config=auto-pause.time=10s```

**Comment by r4j4h** [comment]
FWIW there is also `configure` inside of `minikube addons` but for configuring at time of enabling I think you are right and a new flag would be needed like `--images`. --images is used like `minikube addons enable <x> --images=image:a,image:b,image:c`

I don't know if this would belong as an argument to minikube start though, as the add-on isn't installed by default AFAIK

**Comment by sharifelgamal** [comment]
@daehyeok are you still interested in this? I would be in favor of adding a new parameter to minikube start, perhaps as illustrated by @r4j4h

**Comment by klaases** [comment]
Hi @vishjain, is this still something that you're working on?
