### ISSUE TITLE
auto-pause: make it memory-leak proof

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10596]
each call of `time.After` creates a new timer instance which is not released until the timer fired. If we have high traffic in `incomeCh` we'll end up with a lot of pending timers

https://groups.google.com/g/golang-nuts/c/cCdm0Ixwi9A

_Originally posted by @ilya-zuyev in https://github.com/kubernetes/minikube/pull/10427#discussion_r580669849_

https://www.fatalerrors.org/a/use-with-caution-time.after-can-cause-memory-leak-golang.html

**Comment by medyagh** [comment]
@hetong07 thanks for picking this up, let me know if u need help or have questions

**Comment by vishjain** [comment]
Saw this issue had gotten abandoned and wanted some practice on this part of the codebase because I'm working on another related auto-pause feature. Hope this is ok - thanks!
