### ISSUE TITLE
Unable to access Minikube dashboard from Local machine without GUI

### ISSUE THREAD

**Issue by vcashadoop** [kubernetes/minikube#10592]
**Steps to reproduce the issue:** 

1.Installed Oracle VM in my laptop, and jave installed minikube  in the CENTOS 7 running in the VM
2. Installed the minikube 
3.and then ran the command minikube dashboard --url=true

* Verifying dashboard health ...
* Launching proxy ...
* Verifying proxy health ...
http://127.0.0.1:34986/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/

4. Run kubectl proxy
Starting to serve on 127.0.0.1:8001

when I try to access with the  above url like  http://127.0.0.1:8001 or 80 not abl top open in my local browser.

Please let me know how to access this in my windows browser

**Comment by ilya-zuyev** [comment]
Hi @vcashadoop! Thanks for reporting this.  Could you provide logs of `minikube start -v=5 --alsologtostderr`?

**Comment by afbjorklund** [comment]
If you run minikube in a VM, you need to run the browser in the VM.

**Comment by vcashadoop** [comment]
> If you run minikube in a VM, you need to run the browser in the VM.

Can you please guide me how to do this? Because I have other products installed in the VM and can be accessed in the local browser.

**Comment by vcashadoop** [comment]
Just to add additional details, I did the below setting in Oracle VM also.
minikube ip
192.168.49.2

]$ minikube dashboard --url=true
* Verifying dashboard health ...
* Launching proxy ...
* Verifying proxy health ...
http://127.0.0.1:44876/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/

![image](https://user-images.githubusercontent.com/5534773/109102709-7260cb80-774f-11eb-8820-b0fd0e7f5a4d.png)

**Comment by afbjorklund** [comment]
> > If you run minikube in a VM, you need to run the browser in the VM.
> 
> Can you please guide me how to do this? Because I have other products installed in the VM and can be accessed in the local browser.

You say that you are running CentOS 7, so I think it comes with Firefox ?

`yum install firefox`

Normally we just let minikube handle the VM, and run with normal browser.

**Comment by vcashadoop** [comment]
> > > If you run minikube in a VM, you need to run the browser in the VM.
> > 
> > 
> > Can you please guide me how to do this? Because I have other products installed in the VM and can be accessed in the local browser.
> 
> You say that you are running CentOS 7, so I think it comes with Firefox ?
> 
> `yum install firefox`
> 
> ![](https://camo.githubusercontent.com/e0e25da617f1cab6bf7bcd979143b1272d902b29e916d0a8c11e2a24f59c00ee/68747470733a2f2f77696b692e63656e746f732e6f72672f53637265656e73686f74733f616374696f6e3d41747461636846696c6526646f3d676574267461726765743d73637265656e73686f742d63372d7769646573637265656e2e706e67)
> 
> > 1.Installed Oracle VM in my laptop, and jave installed minikube in the CENTOS 7 running in the VM
> 
> Normally we just let minikube handle the VM, and run with normal browser.
> 
> But you should be able to reach it over the forwarded port (127.0.0.1:8002)

I'm using non GUI due to some restrictions. Could you guide how to do in the non GUI one

**Comment by medyagh** [comment]
@vcashadoop without Gui you could use a cli tool like https://github.com/derailed/k9s 
or just good old Curl (that would be harder to read)

does that answer your question ? if not plz reopen this

**Comment by harika1210** [comment]
Hi, I am very new to minikube. I am using Linux server on my Oracle VM and have installed minikube. Right now, I am experiencing the same problem. I am not able to open the minikube dashboard in my local machine, not with the url I am given. It's not opening automatically either. Is there any solution to this?

**Comment by nuxwin** [comment]
1. Start the dashboard as follow:
    ```shell
    $ minikube dashboard --port 8080 --url
    ```
2. Run the following command in terminal of your workstation:
    ```shell
    $ ssh -L 8080:127.0.0.1:8080 <user>@<vmip>
    ```

**where**

1. \<user\>: is your ssh user
2. \<vmip\>: is your virtual machine IP (LAN)

Then access the dashboard from your workstation through browser at `http:127.0.0.1:8080`
