### ISSUE TITLE
auto-pause: intiliaze the pause state from the current state

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10602]
curently when we start the addon we assume it is not pause. which could be wrong (though not the standard use-case but might be possible)

so instead of
```
var runtimePaused = false
```

we should initialize it as getting the current state

**Comment by BLasan** [comment]
@medyagh Shall I give a try?

**Comment by medyagh** [comment]
yes, go for it ! @BLasan  
I recommend trying the auto-pause addon to learn it first

**Comment by medyagh** [comment]
@BLasan feel free send me ur questions on slack or if u make an early prototype I can look at

**Comment by BLasan** [comment]
> @BLasan feel free send me ur questions on slack or if u make an early prototype I can look at

sure

**Comment by medyagh** [comment]
@BLasan I haven't heard from you, unfortnatelyl I have to un-assign this issue, so others could pick it up

**Comment by sharifelgamal** [comment]
This was done
