### ISSUE TITLE
auto-pause: add VM driver support

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10601]
currently for KIC we do this
```
.PHONY: deploy/kicbase/auto-pause # auto pause binary to be used for kic image work arround for not passing the whole repo as docker context
deploy/kicbase/auto-pause: $(SOURCE_GENERATED) $(SOURCE_FILES)
	GOOS=linux GOARCH=$(GOARCH) go build -o $@ cmd/auto-pause/auto-pause.go
```
https://github.com/medyagh/minikube/blob/f272822d15fc3ffdeb2e51da2b202fbf37e715f1/Makefile#L817

and in Dockerfile we add this
```
COPY auto-pause /usr/local/bin/auto-pause
```

we need to do something similar for our ISO

**Comment by afbjorklund** [comment]
You copy it from minikube to the docker build context ? You could copy it to the buildroot as well, perhaps ?
