### ISSUE TITLE
minikube addons enable ingress failed to pull images using cn mirror

### ISSUE THREAD

**Issue by wswind** [kubernetes/minikube#10612]
**Steps to reproduce the issue:** 

1. minikube addons enable ingress 
2. minikube dashboard & 

**Full output of failed command:** 
Failed to pull image "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.2.2": rpc error: code = Unknown desc = Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen, repository does not exist or may require 'docker login': denied: requested access to the resource is denied 

![image](https://user-images.githubusercontent.com/18399096/109094622-45171c00-7755-11eb-9869-29d21b1affc5.png)

Failed to pull image "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.3.0": rpc error: code = Unknown desc = Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen, repository does not exist or may require 'docker login': denied: requested access to the resource is denied 

![image](https://user-images.githubusercontent.com/18399096/109094756-7c85c880-7755-11eb-90c1-efeffefcd7bb.png)

MountVolume.SetUp failed for volume "webhook-cert" : secret "ingress-nginx-admission" not found 
![image](https://user-images.githubusercontent.com/18399096/109094827-958e7980-7755-11eb-8e49-da7b4dd202a0.png)

**Full output of `minikube start` command used, if not already included:**

ws@debian:~$ minikube start --image-mirror-country=cn
😄  minikube v1.17.1 on Debian 10.8 (vbox/amd64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Comment by wswind** [comment]
Where is the image "kube-webhook-certgen" exactly? Is it in gcr.io/kube-webhook-certgen ?

**Comment by wswind** [comment]
I think it's a small bug with minikube's mirror function . `kube-webhook-certgen` mirror is at `docker.io/jettech/kube-webhook-certgen`, see <https://github.com/wangyingping/docker.io_kube-webhook-certgen/blob/master/Dockerfile>. But it uses aliyun mirror.

**Comment by wswind** [comment]
a work around for ones meet the same problem:
```
minikube ssh

docker pull docker.io/jettech/kube-webhook-certgen:v1.2.2 registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.2.2
docker tag  docker.io/jettech/kube-webhook-certgen:v1.2.2 registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.2.2
```

**Comment by wswind** [comment]
get an error again for pod  ingress-nginx-controller
```
Failed to pull image "registry.cn-hangzhou.aliyuncs.com/google_containers/controller:v0.40.2": rpc error: code = Unknown desc = Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/google_containers/controller, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

**Comment by wswind** [comment]
I made a mirror to fix this:  https://github.com/wswind/mirror-k8s.gcr.io-ingress-nginx-controller

**Comment by wswind** [comment]
finally:

ws@debian:~$ minikube addons enable ingress
🔎  Verifying ingress addon...
🌟  The 'ingress' addon is enabled

**Comment by wswind** [comment]
I think minikube cn mirror is a great function. But with the use of it, there still can be a lot of problems.
I can fix the problems with the help of the real image list which are needed by minikube.
But I must search for the image urls for a long time. 
If minikube  can just list the required images with a command or logs  would be great for me

**Comment by priyawadhwa** [comment]
Hey @wswind thanks for pointing out, this is definitely a user experience that could be improved. If you could specify your own registry mirror for the ingress addon, would that be a suitable solution for you?

We have an issue open for that here: https://github.com/kubernetes/minikube/issues/10012

**Comment by wswind** [comment]
That feature would be great too.   
But what I want is something like `kubeadm config images list`  for minikube addons, to help me to check what imgaes exactlly is needed.
![image](https://user-images.githubusercontent.com/18399096/109266392-fba4fa80-7842-11eb-9eee-539cb8c29a4f.png)

**Comment by priyawadhwa** [comment]
Ah I see, something like `minikube addons images list` is what you're looking for.

If you, or anyone else, would be interested in submitting a PR for that we'd be happy to take a look at it !

**Comment by spowelljr** [comment]
Sounds good, I'll close this issue for now, but if you or someone else experiences this issue feel free to re-open the issue, thanks!
