### ISSUE TITLE
ssh-user is not used in native mode

### ISSUE THREAD

**Issue by rgordill** [kubernetes/minikube#10618]
**Steps to reproduce the issue:** 

1. minikube start --driver=ssh --ssh-ip-address=192.168.122.171 --ssh-user=centos -p kubevirt

**Full output of failed command:** 

😄  [kubevirt] minikube v1.17.1 on Fedora 33
✨  Using the ssh driver based on existing profile
👍  Starting control plane node kubevirt in cluster kubevirt
🏃  Updating the running ssh "kubevirt" bare metal machine ...
🤦  StartHost failed, but will try again: provision: fast detect: OS type not recognized
🏃  Updating the running ssh "kubevirt" bare metal machine ...

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
Full of logs in the target host:

Feb 25 11:31:24 kubevirt sshd[65242]: Connection closed by authenticating user **root** 192.168.122.1 port 42952 [preauth]

</details>

**Comment by afbjorklund** [comment]
I think this is the same problem as in #10578, you might have to recreate the profile to pick up the new parameters

**Comment by afbjorklund** [comment]
Currently we only validate the IP address. Eventually we might want to "ping" the entire connection, test SSH.

**Comment by rgordill** [comment]
> I think this is the same problem as in #10578, you might have to recreate the profile to pick up the new parameters

It is a fresh one. It works with native=false (on some connections).

**Comment by afbjorklund** [comment]
Sorry, I meant the same underlying problem - the parameter itself is different. Also, there is no validation of user or key.

**Comment by afbjorklund** [comment]
Ah, maybe you are talking about the go-native implementation of ssh ? (`--native-ssh=true`) Yeah, that does have issues.

**Comment by afbjorklund** [comment]
Do you have more information or more verbose logs ? It is supposed to always use the ssh user, when connecting to the VM. 

`ssh centos@192.168.122.171`

**Comment by afbjorklund** [comment]
When I set up a VM with vagrant, I get the correct parameters for connecting:

`new ssh client: &{IP:192.168.50.4 Port:22 SSHKeyPath:/home/anders/.minikube/machines/ssh/private_key Username:vagrant}`


### Native

```
libmachine: Using SSH client type: native
libmachine: &{{{<nil> 0 [] [] []} vagrant [0x7f4aa0] 0x7f4a60 <nil>  [] 0s} 192.168.50.4 22 <nil> <nil>}
```

### External

```
libmachine: Using SSH client type: external
libmachine: &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null vagrant@192.168.50.4 -o IdentitiesOnly=yes -i /home/anders/.minikube/machines/ssh/private_key -p 22] /usr/bin/ssh <nil>}
```

**Comment by klaases** [comment]
Hi @rgordill, were you able to apply the suggestion provided by @afbjorklund?

**Comment by rgordill** [comment]
Sorry, I used another alternative for my tests, as I am not using vagrant.

**Comment by klaases** [comment]
Hi @rgordill – thanks for updating the issue, will close out for now as a viable alternative was found. Please feel free to re-open the issue by commenting with `/reopen` if needed.

Thank you for sharing your experience!
