### ISSUE TITLE
Failing test: TestFunctional/DockerEnv on Windows Docker

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/minikube#10627]
https://storage.googleapis.com/minikube-builds/logs/10603/fb9f08b/Docker_Windows.html#fail_TestFunctional%2fparallel%2fDockerEnv

This is due to how we run our windows test. We ssh from a linux machine into a windows machine, starting a cmd terminal that then executes a powershell script. `minikube docker-env` then detects the cmd env and gives us incorrect commands since we're actually in powershell.

**Comment by hetong07** [comment]
seems to be a duplicate issue of #10626

**Comment by medyagh** [comment]
this is solved
