### ISSUE TITLE
Pod is unable to reach internet

### ISSUE THREAD

**Issue by psaini79** [kubernetes/minikube#10629]
**Steps to reproduce the issue:** 

1. Installed the minikube 1.17.1 on a VM . It is installed as a root user.
2. Minikube using docker engine installed on a docker host
3. Created the pod and unable to download any package using yum. However, on minikube host machine, I am able to download the packages using yum.

**Full output of failed command:** 
```
[root@ol7 /]# ping yum.oracle.com
PING yum.oracle.com (184.28.88.97) 56(84) bytes of data.
^C
--- yum.oracle.com ping statistics ---
9 packets transmitted, 0 received, 100% packet loss, time 8230ms

[root@ol7 /]#

Ping works from minikube machine
```
[root@alexminikubeshard ~]# ping  yum.oracle.com
PING e10877.g.akamaiedge.net (184.28.88.97) 56(84) bytes of data.
64 bytes from a184-28-88-97.deploy.static.akamaitechnologies.com (184.28.88.97): icmp_seq=1 ttl=57 time=2.95 ms
64 bytes from a184-28-88-97.deploy.static.akamaitechnologies.com (184.28.88.97): icmp_seq=2 ttl=57 time=2.99 ms
```

**Full output of `minikube start` command used, if not already included:**

```
[root@alexminikubeshard ~]# minikube start
* minikube v1.17.1 on Oracle 7.9 (amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Oracle Linux Server 7.9
* Preparing Kubernetes v1.20.2 on Docker 19.03.11-ol ...
* Configuring local host environment ...
*
! The 'none' driver is designed for experts who need to integrate with an existing VM
* Most users should use the newer 'docker' driver instead, which does not require root!
* For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/
*
! kubectl and minikube configuration will be stored in /root
! To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:
*
  - sudo mv /root/.kube /root/.minikube $HOME
  - sudo chown -R $USER $HOME/.kube $HOME/.minikube
*
* This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass, dashboard
* kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
[root@alexminikubeshard ~]#
```

**Optional: Full output of `minikube logs` command:**
<details>


</details>

**Comment by afbjorklund** [comment]
If you run other docker containers on the host, do they have proper networking (can they reach the outside?)

**Comment by Butterneck** [comment]
Hi, same problem here. 

If I run other container inside minikube they're able to reach internet. 
Only containers created applying `.yaml` files are affected.

Changing `nameserver` from `10.96.0.10` to `8.8.8.8` in `/etc/resolv.conf` make the pod able to ping internet resources

**Comment by psaini79** [comment]
@afbjorklund @Butterneck 

Thanks. I managed to make it work by adding the following and restarted the docker daemon. 
```
[root@alexminikubeshard oke-based-sharding-deployment]# cat /etc/docker/daemon.json
{
    "dns": ["8.8.8.8"]
}
```

Now, I am able to download packages.

**Comment by teng1** [comment]
I have this same exact issue v1.18.0 It worked fine for one day, it stopped working since.

**Comment by squakez** [comment]
I was having the same problem when I moved to another internet connection and the provider was adding a `search` in the host `/etc/resolv.conf` machine. It seems that minikube lookup that file and include that search configuration in its DNS.

I've removed the line with `search`, restarted minikube and now the Pods are able to lookup DNS with no problem.

**Comment by joaocostamm** [comment]
I am having the same issue. Here are the steps to reproduce on intel Mac:
`brew install hyperkit minikube docker kubectl docker-compose
minikube start --kubernetes-version=v1.22.1 --driver=hyperkit --container-runtime=docker
kubectl apply -f dnsutil.yaml
kubectl exec -i -t dnsutils -- ping 1.1.1.1
`

**Comment by klaases** [comment]
Hi @psaini79, per your comment above, glad that this issue was able to be resolved.

Will go ahead and close the issue. If needed, please feel free to re-open the issue by commenting with `/reopen`.

Thank you for sharing your experience!
