### ISSUE TITLE
[Bump-up] VolumeSnapshot from v1beta1 to v1(GA)

### ISSUE THREAD

**Issue by govargo** [kubernetes/minikube#10636]
/area addons

Minikube can use VolumeSnapshot as an addon.
Its version is v1beta1 api version.

https://github.com/kubernetes/minikube/blob/a2a3475e7d2b901bbdd59baa63c6c0f207a653de/deploy/addons/volumesnapshots/snapshot.storage.k8s.io_volumesnapshots.yaml.tmpl#L148-L152

In Kubernetes v1.20, the VolumeSnahot moved to GA(v1).

[Kubernetes 1.20: Kubernetes Volume Snapshot Moves to GA](https://kubernetes.io/blog/2020/12/10/kubernetes-1.20-volume-snapshot-moves-to-ga/)

We need to upgrade volumesnapshot versions.

**Comment by priyawadhwa** [comment]
Thanks for taking this on @govargo !
