### ISSUE TITLE
Accessing the application 

### ISSUE THREAD

**Issue by rishabds** [kubernetes/minikube#10662]
When deploying a service on Kubernetes it is not working.
When you do minikube service (pod_name) --url 
It gives 127.0.0.1:port number but when accessing the ip it shows can't find the link

**Comment by ilya-zuyev** [comment]
Hi @rishabds. Thanks for reporting. Could you provide more information about your system/os and also use `minikube start -v=5 --alsologtostderr` to run minikube and provide logs? Thanks!

**Comment by prezha** [comment]
hi @rishabds hopefully it’s ok if i close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it or create a new issue.

Here is additional information that may be helpful to us:
- Whether the issue occurs with the latest minikube release
- The exact minikube commands used
- The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging
- The full output of minikube logs

thank you for sharing your experience!

/close
