### ISSUE TITLE
Pause: bump to newest image v3.4.1

### ISSUE THREAD

**Issue by prezha** [kubernetes/minikube#10665]
reasons:

- 3 weeks ago pause image was promoted to v3.4.1 (https://github.com/kubernetes/kubernetes/pull/98205)
```
❯ docker pull k8s.gcr.io/pause:3.4.1
3.4.1: Pulling from pause
fac425775c9d: Pull complete
Digest: sha256:6c3835cab3980f11b83277305d0d736051c32b17606f5ec59f1dda67c9ba3810
Status: Downloaded newer image for k8s.gcr.io/pause:3.4.1
k8s.gcr.io/pause:3.4.1
```

- `pause:latest` is not latest - last time updated at ***Jan 11, 2017*** (ref: https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/pause)
note: latest pause version available on `gcr.io/google_containers` is 3.2 (and that repo should be replaced with `k8s.gcr.io`):
```
❯ docker pull gcr.io/google_containers/pause:3.2
3.2: Pulling from google_containers/pause
c74f8866df09: Pull complete
Digest: sha256:927d98197ec1141a368550822d18fa1c60bdae27b78b0c004f705f548c07814f
Status: Downloaded newer image for gcr.io/google_containers/pause:3.2
gcr.io/google_containers/pause:3.2
```

- ~minikube tests, more often than not, fail with a message `FATA[0000] no such image "k8s.gcr.io/pause:latest", eg:~ - my bad: this is actually a 'delete' test and does not fail
```
    functional_test.go:730: (dbg) Non-zero exit: out/minikube -p functional-20210301023641-94177 ssh sudo crictl inspecti k8s.gcr.io/pause:latest: exit status 1 (272.439218ms)
        
        -- stdout --
                FATA[0000] no such image "k8s.gcr.io/pause:latest" present 
        
        -- /stdout --
        ** stderr ** 
                ssh: Process exited with status 1
        
        ** /stderr **
```

- changelog (ref: https://github.com/kubernetes/kubernetes/blob/master/build/pause/CHANGELOG.md):
```
3.4.1
    Support for Windows container images (OS Versions: 20H2) was added.(#97322, @claudiubelu)

3.4
    Support for Windows container images (OS Versions: 1809, 1903, 1909, 2004) was added. (#91452, @claudiubelu)

3.3
    update debian-base version to v2.1.0 (#90665, [@justaugustus]

3.2
    The pause container is built with the correct "Architecture" metadata. (#87954, @BenTheElder)

3.1
    The pause container gains a signal handler to clean up orphaned zombie processes. (#36853, @verb)
    pause -v will return build information for the pause binary. (#56762, @verb)

3.0
    The pause container was rewritten entirely in C. (#23009, @uluyol)
```

**Comment by afbjorklund** [comment]
Normally we would want to follow `kubeadm` on this, no ?

$ kubeadm config images list
k8s.gcr.io/kube-apiserver:v1.20.4
k8s.gcr.io/kube-controller-manager:v1.20.4
k8s.gcr.io/kube-scheduler:v1.20.4
k8s.gcr.io/kube-proxy:v1.20.4
**k8s.gcr.io/pause:3.2**
k8s.gcr.io/etcd:3.4.13-0
k8s.gcr.io/coredns:1.7.0

**Comment by prezha** [comment]
hmmm, yes, i guess, and according to these below, they've already updated to the pause image v3.4.1 some 25 days ago:
https://github.com/kubernetes/kubernetes/pull/98205/files
and
https://github.com/kubernetes/kubernetes/blob/be2a2988a0c6b5f0b66e4ebdc335fc1318e029ca/cmd/kubeadm/app/constants/constants.go#L418-L419
