### ISSUE TITLE
add thanks to top 5 PR reviewers and issue commenters in the release notes

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10671]
use 
https://github.com/google/pullsheet
and udpate the script in hack folder for release notes

here is how to use pullsheet

```
pullsheet --kind=leaderboard --token-path=/usr/local/google/home/tstromberg/.github-private-token-extended --users tstromberg,medyagh,spowelljr,zuyev,sharifelgamal --repos kubernetes/minikube --since 2020-10-01
 
```

the --users should be replaced with list of triagers in minikube and --since should be since last release

**Comment by anencore94** [comment]
If nobody is responsible to this issue now, may I take this issue ?

**Comment by sharifelgamal** [comment]
@anencore94, sure go ahead. just add it our release script in the `hack` folder

**Comment by medyagh** [comment]
@anencore94

**Comment by anencore94** [comment]
sry @medyagh , I've tried it but have trouble on how to get maintainers' names and parse date of last tag with commit hash value.
I've been busy for now, so if this issue needs to be included with next release, anyone else could take this.

Thank you for reminding me.

**Comment by andriyDev** [comment]
I would like this issue!
