### ISSUE TITLE
benchmark different image build/push ways in minikube

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10672]
generate charts across 100 runs for docker-env, image load, and registry and podman-env addon 
for docker, containerd, crio

and compare the build image and the time that image was availalbe inside minikube.

for different docker files
small layers, few
small layers, a lot
big layers, few
big l ayers, a lot
duplicate layers

**Comment by afbjorklund** [comment]
When running docker there is `docker-env` and when running cri-o there is `podman-env`.

But when running containerd, you currently still have to tunnel buildctl manually.
Also you have to start the buildkitd daemon, which is another manual command.

But after that, it should be possible to use `buildctl` similar to `docker` and `podman-remote`

**Comment by afbjorklund** [comment]
The easiest way to see the ssh parameters is: `minikube --alsologtostderr ssh --native-ssh=false`

However, I don't think minikube allows running as root by default (and root owns the buildkitd.sock)

You can either add authorized_keys to the root user.

Or you can add a "buildkit" group to own the socket.

**Comment by afbjorklund** [comment]
I opened up a ticket about trying to add this to the minikube documentation: #10685

**Comment by medyagh** [comment]
in-progress created a private repo to measure 
https://github.com/GoogleContainerTools/minikube-image-benchmark

**Comment by spowelljr** [comment]
In-progress

**Comment by afbjorklund** [comment]
I outlined the basic approach taken by the "build" wrapper:

https://github.com/kubernetes/minikube/issues/4868#issuecomment-792347686

The extra steps are about writing the tar to disk, on both sides
(once on the client/host, and once on the server/machine)

How much extra time this takes, depends on the size etc...

By using the native client to the unix socket, it saves the copies.
Instead the archive can stream out, and go right in to the builder.

**Comment by medyagh** [comment]
this was added to our website https://minikube.sigs.k8s.io/docs/benchmarks/imagebuild/

need to add MacOS and also microK8s and k3s

**Comment by afbjorklund** [comment]
It would be good with some background on that page, like what is actually being done ?

Or make the git repo behind it public, perhaps ? Also curious why it calls a load a build...
