### ISSUE TITLE
parsing

### ISSUE THREAD

**Issue by hlulaniM** [kubernetes/minikube#10688]
! Error parsing HTTP_PROXY=C:\Program Files (x86)\Anaconda3, parse "http://C:\\Program Files (x86)\\Anaconda3": invalid port ":\\Program Files (x86)\\Anaconda3" after host
! Error parsing HTTP_PROXY=C:\Program Files (x86)\Anaconda3, parse "http://C:\\Program Files (x86)\\Anaconda3": invalid port ":\\Program Files (x86)\\Anaconda3" after host
! StartHost failed, but will try again: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --entrypoint /usr/bin/test -v minikube:/var <local_docker_registry>:5000/gcr.io/k8s-minikube/kicbase:latest -d /var/lib: exit status 125
stdout:

**Comment by medyagh** [comment]
@hlulaniM it is not clear from the logs what driver, version and what command u are trying to do,
, do u mind sharing
output of

```
minikube delete --all
minikube start --alsologtostderr
```
```minikube logs```

**Comment by prezha** [comment]
@hlulaniM  `HTTP_PROXY` is an environment variable, and the value you've got is really strange (eg, having a local path instead of a network address); can you please check and also provide additional information (https://github.com/kubernetes/minikube/issues/10688#issuecomment-789066684)

thanks!

**Comment by spowelljr** [comment]
Hi @hlulaniM, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
