### ISSUE TITLE
site: Add tutorial for using --user 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10692]
we have a flag called --user but most ppl dont know what it is meant for and how to use it
we could add a tutorial how to use this flag
https://minikube.sigs.k8s.io/docs/tutorials/

**Comment by afbjorklund** [comment]
❓

**Comment by ilya-zuyev** [comment]
@medyagh Could you add more details to this issue please?

**Comment by spowelljr** [comment]
In-progress
