### ISSUE TITLE
Error message prints a dead link

### ISSUE THREAD

**Issue by Paul-E** [kubernetes/minikube#10693]
The error on [this line](https://github.com/kubernetes/minikube/blob/6ea2b3298e6b68a0f757670cad3b85987731fef6/cmd/minikube/cmd/start.go#L1173) links to a dead resource: https://docs.doInfo.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities

**Comment by medyagh** [comment]
@Paul-E thanks for reporting this ! that is a bug the right link should be

https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities

would u like to make a PR to fix this ?

**Comment by urohit011** [comment]
I would like to take it if that's okay.

**Comment by afbjorklund** [comment]
Got broken in 9a30756d38e786698371ab936c513295f35af4c9

**Comment by medyagh** [comment]
this issue is assigned to @NamrataShah5
