### ISSUE TITLE
remove kicbase image from local docker daemon on delete --purge

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#10708]
Currently, if 'docker' driver is used, `minikube delete --all --purge` command does not remove the pulled kicbase image 

```
➜  minikube git:(master) ✗ out/minikube start --driver=docker
* minikube v1.18.0 on Darwin 11.2
* Using the docker driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Creating docker container (CPUs=2, Memory=3890MB) ...
* Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v4
* Enabled addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

➜  minikube git:(master) ✗ docker images | grep kicbase
gcr.io/k8s-minikube/kicbase                           v0.0.18                           a776c544501a   5 days ago      1.08GB


➜  minikube git:(master) ✗ out/minikube delete --all --purge
* Deleting "minikube" in docker ...
* Removing /Users/izuyev/.minikube/machines/minikube ...
* Removed all traces of the "minikube" cluster.
* Successfully deleted all profiles
* Successfully purged minikube directory located at - [/Users/izuyev/.minikube]

➜  minikube git:(master) ✗ docker images | grep kicbase     
gcr.io/k8s-minikube/kicbase                           v0.0.18                           a776c544501a   5 days ago      1.08GB
```

This can be unexpected for user. For example, if he/she is using the locally built kicbase image and wants to reset it to the official one. `--purge` could be interpreted as `remove everything related`. 

May be we should delete the image or, if not, print an explicit warning/info message that we keep it when running `minikube delete`

**Comment by medyagh** [comment]
I think a lot of people use --purge just to purge configs but they dont really wanna delete the image
I think the right thing to do is, to add a "Info" and letting them know we did NOT delete the kicbase
and here is the command to run to delete the kicbase .

but I can be convinced other way

**Comment by prezha** [comment]
@sharifelgamal agreed with @ilya-zuyev's 2nd option and also with what @medyagh proposed - ie, warn the user and provide a cleanup command to use if they wish so

**Comment by tstromberg** [comment]
I agree, `--purge` should remove all local state.

**Comment by presztak** [comment]
I've started working on this.
/assign
