### ISSUE TITLE
Windows Terminal Error when using 1.18

### ISSUE THREAD

**Issue by fljamie** [kubernetes/minikube#10702]
**Trying to run minikube.exe from Windows Terminal.  If I open a normal powershell or cmd window it runs fine:**

PS C:\Users\username> minikube start
* minikube v1.18.0 on Microsoft Windows 10 Pro 10.0.19042 Build 19042
* Using the vmware driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing vmware VM for "minikube" ...
* Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v4
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**But...i open a terminal and run it from powershell, powershell 7, or cmd window and i get this:**

PS C:\Users\username> minikube start

❌  Exiting due to MK_WRONG_BINARY_WSL: You are trying to run windows .exe binary inside WSL, for better integration please use Linux binary instead (Download at https://minikube.sigs.k8s.io/docs/start/.). Otherwise if you still want to do this, you can do it using --force

# Notes
Was working on minikube 1.17 for a while but stopped working when i updated to minikube 1.8 

# Environment
```none
Windows build number: Windows 10 Pro 10.0.19042 Build 19042
Windows Terminal
Version: 1.6.10571.0

```
# Steps to reproduce
Try to run minikube from command line -- needs a virtualization component, docker, virtualbox, vmware (i am using vmware)
 -- first run i use:  minikube start --vm-driver=vmware

# Expected behavior
Starts fine and output is above..

# Actual behavior
Error also above..

**Comment by medyagh** [comment]
@fljamie we are aware of this bug, 
```
But...i open a terminal and run it from powershell, powershell 7, or cmd window and i get this:
```
do u mind giving examples ?

**Comment by medyagh** [comment]
if u dont mind lets close this issue and track it here 
https://github.com/kubernetes/minikube/issues/10689
