### ISSUE TITLE
website/handbook: don't advise users to create a symbolic link to minikube’s binary named ‘kubectl’

### ISSUE THREAD

**Issue by prezha** [kubernetes/minikube#10717]
this confuses users and doesn't work (eg, minikube calling kubectl would loopback to itself)
ref: https://minikube.sigs.k8s.io/docs/handbook/kubectl/ (https://github.com/kubernetes/minikube/blob/master/site/content/en/docs/handbook/kubectl.md)

```
Alternatively, you can create a symbolic link to minikube’s binary named ‘kubectl’.

ln -s $(which minikube) /usr/local/bin/kubectl
```

example: https://github.com/kubernetes/minikube/issues/9976

previously, there were discussions in issue #8857 and pr #8872

alternatively, we can make it work by 'recognising' that minikube was called as kubectl and assign the flags as flags for minikube's own downloaded kubectl binary...

**Comment by medyagh** [comment]
good idea, needs fix

**Comment by afbjorklund** [comment]
It would be better to fix the feature, for whatever it is that is broken ?

For me, I think it is just that it has a bunch of cluster checks now... (instead of just calling the binary)

```
$ kubectl version --client --output=json
🤷  Profile "minikube" not found. Run "minikube profile list" to view all profiles.
👉  To start a cluster, run: "minikube start"
```

**Comment by afbjorklund** [comment]
I think it was broken in 8f9a2b94136bb13749076932804bdd4768880282, that added the `mustload.Healthy`
