### ISSUE TITLE
Not able to access service in browser

### ISSUE THREAD

**Issue by patelrutva** [kubernetes/minikube#10719]
**Steps to reproduce the issue:** 

1. kubectl run docserver --image=docker.io/{myusername}/{image}:latest --port=80
2. kubectl expose pod docserver --type=NodePort
3. minikube service docserver

![image](https://user-images.githubusercontent.com/41102770/110014536-e7547800-7cf0-11eb-86a1-667879b97498.png)

**Full output of minikube dashboard logs:**
![image](https://user-images.githubusercontent.com/41102770/110014671-12d76280-7cf1-11eb-8121-a86fa9c3d037.png)

**But In browser getting this**
![image](https://user-images.githubusercontent.com/41102770/110014733-24b90580-7cf1-11eb-9679-4185fe437dbb.png)

<details>

how can I hit the service?

Thanks in advance.

</details>

**Comment by medyagh** [comment]
@patelrutva have u tried the random port that minkube gives u ? (docker limitaiton on  Darwin makes the port random)

I see the URL in ur terminal is 30872 and the second time it is 62529
you need to hit that port instead of 8000

**Comment by patelrutva** [comment]
@medyagh I have tried both ports: 

1) With 30872 I'm getting ERR_CONNECTION_REFUSED 

2) With 62529 I'm getting ERR_CONNECTION_RESET

Thanks

**Comment by patelrutva** [comment]
@medyagh  I got this fixed. Thank you for your help.

As a solution I have used LoadBalancer instead of NodePort using this example as a reference:
https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-service.
