### ISSUE TITLE
Failed to start hyperv VM. Running "minikube delete" may fix it: provision: IP not found

### ISSUE THREAD

**Issue by SUK1** [kubernetes/minikube#10727]
**Steps to reproduce the issue:** 

1.minikube start --vm-driver="hyperv"

run this command on windows 10 enterprise version 

* minikube v1.15.1 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. Running "minikube delete" may fix it: provision: IP not found

X Exiting due to GUEST_PROVISION: Failed to start host: provision: IP not found
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
PS C:\WINDOWS\system32> minikube logs

X Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""
* Suggestion:

    Recreate the cluster by running:
    minikube delete
    minikube start
*
* If the above advice does not help, please let us know:

</details>

**Comment by medyagh** [comment]
@SUK1 I noticed u are using a very old minikube, two questions, have u tried with latest minikube ?
and secondly is there a reason u dont use the Docker Driver?

I suggest download latest https://minikube.sigs.k8s.io/docs/start/
and then 
minikube delete --all
minikube start

(if u have docker installed we will use docker as the driver)

**Comment by sharifelgamal** [comment]
Hey @SUK1, I'm going to go ahead and close this issue for now, if you upgrade to 1.18.1 and still experience issues please reopen this issue and give us some extra details, such as,

The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

The full output of minikube logs
