### ISSUE TITLE
minikube start with none driver 

### ISSUE THREAD

**Issue by AnannyaShanmugam23** [kubernetes/minikube#10725]
MINIKUBE START COMMAND:
sudo minikube start --vm-driver=none --cpus=2 --memory='3000mb' --disk-size='10000mb'

OUTPUT:

Failed to save config: failed to acquire lock for /root/.minikube/profiles/minikube/config.json: {Name:mk270d1b5db5965f2dc9e9e25770a63417031943 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}: unable to open /tmp/juju-mk270d1b5db5965f2dc9e9e25770a63417031943: permission denied

**Comment by afbjorklund** [comment]
Probably systemd again, see #6391

`sudo sysctl fs.protected_regular=0`

**Comment by afbjorklund** [comment]
By the way, those cpus/memory/disk-size parameters don't have any effect when running on localhost.

You also don't need to use "sudo" to run minikube as root, it will use sudo internally when required to.

**Comment by AnannyaShanmugam23** [comment]
Is there a way i can specify cpus/memory/disksize?
ALso, It doesnt run without sudo. it says permission denied

**Comment by afbjorklund** [comment]
> Is there a way i can specify cpus/memory/disksize?

It uses the local machine, so you have to specify that when you create (or build) that.

> ALso, It doesnt run without sudo. it says permission denied

What version of minikube do you have ? It was added as a feature in 1.16

**Comment by krishsaha2020** [comment]
Getting the below error while starting minikube on WSL2 ( Ubuntu 20.04.2 LTS).  Please let me know how to overcome this error.

$ minikube start --driver=none

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl restart docker: exit status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by spowelljr** [comment]
@krishsaha2020 This is a different error than the original issue, please make a new issue specifically for your issue.

It seems @AnannyaShanmugam23 was solved by @afbjorklund's suggestion, so I'm going to close this issue.

Feel free to re-open if you have more questions.
