### ISSUE TITLE
Template parsing error: template: :1: unexpected "=" in operand

### ISSUE THREAD

**Issue by wandellamaia** [kubernetes/minikube#10724]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

</details>

**A saída do comando `minikube logs`**:<details>

[</details>](url)

**A versão do sistema operacional usado**:
[](url)

**Comment by wandellamaia** [comment]
Fazendo o curso de minikube, depois de executar o comando "minikube start", ocorreu este erro de template e os resultados estão diferentes do curso.

**Comment by medyagh** [comment]
@wandellamaia 
¿Qué versión de minikube usas?
¿Te importaría probar con la última versión de minikube? Creo que este error está relacionado con la versión anterior de "docker" si instalas la última versión de minikube, debería ser bueno

/triage needs-information
/kind support

**Comment by wandellamaia** [comment]
Boa noite! Eu reinistalei o docker para a versão desejada pelo mikube e funcionou.
Obrigado!Wandella Maia. 

    Em quinta-feira, 4 de março de 2021 22:43:46 BRT, Medya Ghazizadeh <notifications@github.com> escreveu:  
 
 


@wandellamaia
¿Qué versión de minikube usas?
¿Te importaría probar con la última versión de minikube? Creo que este error está relacionado con la versión anterior de "docker" si instalas la última versión de minikube, debería ser bueno

/triage needs-information
/kind support

**Comment by prezha** [comment]
@wandellamaia obrigado pela sua resposta!

/close
