### ISSUE TITLE
can't start minikube with docker driver 

### ISSUE THREAD

**Issue by abdelmonem17** [kubernetes/minikube#10738]
**Steps to reproduce the issue:** 
I am running ubuntu 20 at virtual box  so I install docker and and minikube  finally to run minikube so I run the following command 

$ minikube start --driver=docker

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
😄  minikube v1.17.1 on Ubuntu 20.04 (vbox/amd64)
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🎉  minikube 1.18.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.18.1
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

✋  Stopping node "minikube"  ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: creating: create kic node: container name "minikube": log: 2021-03-07T09:35:49.656567684Z  + echo 'INFO: remounting /sys read-only'
2021-03-07T09:35:49.656580550Z  INFO: remounting /sys read-only
2021-03-07T09:35:49.656582974Z  + mount -o remount,ro /sys
2021-03-07T09:35:49.675515823Z  mount: /sys: permission denied.: container exited unexpectedly
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: creating: create kic node: container name "minikube": log: 2021-03-07T09:36:34.716397784Z  + echo 'INFO: remounting /sys read-only'
2021-03-07T09:36:34.716400225Z  INFO: remounting /sys read-only
2021-03-07T09:36:34.716402386Z  + mount -o remount,ro /sys
2021-03-07T09:36:34.723644635Z  mount: /sys: permission denied.: container exited unexpectedly

💢  The minikube docker container exited unexpectedly.
💡  If you are still interested to make docker driver work. The following suggestions might help you get passed this issue:

	- Prune unused docker images, volumes, networks and abandoned containers.

				docker system prune --volumes

	- Restart your docker service

	- Delete and recreate minikube cluster
		minikube delete
		minikube start --driver=docker

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: create kic node: container name "minikube": log: 2021-03-07T09:36:34.716397784Z  + echo 'INFO: remounting /sys read-only'
2021-03-07T09:36:34.716400225Z  INFO: remounting /sys read-only
2021-03-07T09:36:34.716402386Z  + mount -o remount,ro /sys
2021-03-07T09:36:34.723644635Z  mount: /sys: permission denied.: container exited unexpectedly

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
How did you install ubuntu and docker ? It doesn't seem reproducible with a regular Vagrant installation.

**Comment by abdelmonem17** [comment]
@afbjorklund  I install ubuntu on virtual-box which runs under windows 10,
I install docker like in the docker website steps

**Comment by afbjorklund** [comment]
Doesn't reproduce with VirtualBox 6.1 on Ubuntu 20.04, there it works OK.

```
vagrant@ubuntu-focal:~$ minikube start --driver=docker
😄  minikube v1.17.1 on Ubuntu 20.04 (vbox/amd64)
...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

```
vagrant@ubuntu-focal:~$ docker logs minikube
...
+ fix_mount
+ echo 'INFO: ensuring we can execute mount/umount even with userns-remap'
INFO: ensuring we can execute mount/umount even with userns-remap
++ which mount
++ which umount
+ chown root:root /usr/bin/mount /usr/bin/umount
++ which mount
++ which umount
+ chmod -s /usr/bin/mount /usr/bin/umount
+++ which mount
++ stat -f -c %T /usr/bin/mount
+ [[ overlayfs == \a\u\f\s ]]
+ echo 'INFO: remounting /sys read-only'
INFO: remounting /sys read-only
+ mount -o remount,ro /sys
+ echo 'INFO: making mounts shared'
INFO: making mounts shared
+ mount --make-rshared /
...
```

**Comment by abdelmonem17** [comment]
also I run "Ubuntu 20.04.2 LTS" on my virtualbox 6.1
could you share all steps install minikube and docker with me and I will apply it as it is and check

**Comment by abdelmonem17** [comment]
@afbjorklund Thank you for help, I tried anther new VM image instance and worked for me.
