### ISSUE TITLE
CoreDNS: Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica

### ISSUE THREAD

**Issue by prezha** [kubernetes/minikube#10736]
since we've moved closer to the point when coredns is deployed, there could be a race condition that needs to be handled and operation retried

full error:
```
Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: deployment rescale: Operation cannot be fulfilled on deployments.apps "coredns": the object has been modified; please apply your changes to the latest version and try again
```

/assign

**Comment by SubhanshuMG** [comment]
[logs.txt](https://github.com/kubernetes/minikube/files/9692432/logs.txt)

I'm getting this error. Can someone please help me fix this?
Thanx in advance.
