### ISSUE TITLE
Configure credentials for AWS Elastic Container Registry using registry at ubuntu inside vm with none driver

### ISSUE THREAD

**Issue by abdelmonem17** [kubernetes/minikube#10740]
Hello everyone I am working on ubuntu under VM in windows 10 and I want to configure credentials for AWS Elastic Container Registry for minikube and none as virtualization driver, I tried many ways like in this link https://minikube.sigs.k8s.io/docs/tutorials/configuring_creds_for_aws_ecr/ but I can't pull images from private ECR repo so could anyone help me to do so ? thank you in advance.

**Comment by medyagh** [comment]
@abdelmonem17 do u mind sharing the full Steps and full logs ? and what error do u get ?

**Comment by medyagh** [comment]
here is the docs from the addon maintainer if it helps https://github.com/upmc-enterprises/registry-creds#registry-credentials

**Comment by abdelmonem17** [comment]
I use docker as driver instead of none for minikube and I managed to use addons
