### ISSUE TITLE
update the Outdated catalog in OLM addon 

### ISSUE THREAD

**Issue by kadel** [kubernetes/minikube#10768]
I was wondering why my minikube instance is installing old operator versions.

Then I found out that the `CatalogSource` image in the OLM addon points to the SHA of the image that is several months old.  https://github.com/kubernetes/minikube/blob/81eeb7dd979e29a712ac5153fc4b6b40bd519f9f/pkg/minikube/assets/addons.go#L294

It might make sense for this one case to be an exception from https://github.com/kubernetes/minikube/issues/9884 and to use  `latest` tag. Otherwise, every user will have to update the image refernce themself to pick up the latest changes in Operator Catalog.

**Comment by medyagh** [comment]
@kadel thanks for this issue, I would be happy to accept a PR that updates the version to latest version,

by the way minikube addon has an option to provide your own image to the addon 
$ minikube addons enable --help
```
      --images='': Images used by this addon. Separated by commas.
```

**Comment by kadel** [comment]
@medyagh Can you please reopen these issues?

#10947 updated OLM operators but it did not update the OLM catalog.

### Description of the problem with OLM catalog

Problem is that the latest tagged version of OLM catalog image (https://quay.io/repository/operator-framework/upstream-community-operators?tab=tags) is 4 months old. 


The `latest` tag gets frequent rebuilds but for security reasons, minikube can't just use `latest` 

I've tried to pin down the `upstream-community-operators` image using hash.
But this doesn't work, as the image becomes unavailable after new latest rebuild.  It looks like each new image rebuilds deletes the old layers, as they are not used in any tagged version

I'll try to contact OLM team to check what is the recommended way for referencing catalog images. Or if they are willing to start tagging and versioning catalog images.

Meanwhile, the only way to use the newest catalog image is this?
```
minikube addons enable olm --images "UpstreamCommunityOperators=operator-framework/upstream-community-operators:latest"
```
