### ISSUE TITLE
Minikube tunnel hangs

### ISSUE THREAD

**Issue by ale8k** [kubernetes/minikube#10762]
I'm trying to tunnel through to ambassador, when running "minikube tunnel" it hangs. Sometimes it asks for sudo password, sometimes it doesn't. When I check the loadbalancer it is being assigned to the localhost, but there's no output from the command after typing the sudo password.

I did try access it despite the command not fully running to no avail.

I've also tried running it as a sudo command, no luck.

OS: MacOS.

**Steps to reproduce the issue:** 

1. minikube start
2. helm repo add datawire https://www.getambassador.io
3. kubectl create namespace ambassador
4. helm install ambassador --namespace ambassador datawire/ambassador
5. minikube tunnel

**Full output of failed command:** 
❗  The service ambassador requires privileged ports to be exposed: [80 443]
🔑  sudo permission will be asked for it.
🏃  Starting tunnel for service ambassador.
Password:

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@ale8k on macos the tunnel I believe uses localhost (due to the docker network limiations)
if you would like a full IP support, have u tried the hyperkit driver ? that has more network freedom.
