### ISSUE TITLE
Fix `no such file or directory` error when Docker installed via Snap

### ISSUE THREAD

**Issue by OrpheonZeroh** [kubernetes/minikube#10772]
**Los comandos necesarios para reproducir la incidencia**:

**El resultado completo del comando que ha fallado**: <details>
alberts@4lbrts:~/oauth2-proxy-v6.1.1.linux-amd64$ export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
alberts@4lbrts:~/oauth2-proxy-v6.1.1.linux-amd64$ minikube delete
🔥  Deleting "minikube" in docker ...
🔥  Deleting container "minikube" ...
🔥  Removing /home/alberts/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
alberts@4lbrts:~/oauth2-proxy-v6.1.1.linux-amd64$ minikube start
😄  minikube v1.18.1 on Debian buster/sid
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset207003446 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset207003446: no such file or directory
: exit status 1
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset508036381 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset508036381: no such file or directory
: exit status 1

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset508036381 into minikube:/home/docker/.ssh/authorized_keys, output: lstat /tmp/tmpf-memory-asset508036381: no such file or directory
: exit status 1

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**El resultado del comando `minikube logs`**: <details>
alberts@4lbrts:~/oauth2-proxy-v6.1.1.linux-amd64$ minikube logs

❌  Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""
💡  Suggestion: 

    Recreate the cluster by running:
    minikube delete
    minikube start

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**La versión del sistema operativo que utilizaste**:
utilizo elementary OS 5.1.7 Hera, basado e ubuntu 18.04
![Screenshot from 2021-03-10 12 15 22](https://user-images.githubusercontent.com/46404129/110669810-b796eb80-819a-11eb-90b3-aa069ac09629.png)

**Comment by medyagh** [comment]
@OrpheonZeroh que es un error interesante, ¿te importa compartir, sospecho que el sistema operativo elemnatry no tiene un "/ tmp" escribible
¿Te importa compartir la salida de
''
ls -lah / tmp /
''

-----
@OrpheonZeroh that is an interestnig error, do u mind sharing, I suspect the elemnatry OS does not have a writeable "/tmp"

do u mind sharing the output of 

``
ls -lah /tmp/
```

**Comment by medyagh** [comment]
@spowelljr this issue feels  similar to the Snap not being able to write to /tmp  (for elementary OS linux)
https://github.com/kubernetes/minikube/issues/10772

maybe we could generalize the logic for SNAP if we can't write to /tmp/ then just write to home folder ?

**Comment by OrpheonZeroh** [comment]
hi ls -lah /tmp/ output @medyagh 
total 68K
drwxrwxrwt 16 root    root    4.0K mar 16 19:34 .
drwxr-xr-x 24 root    root    4.0K mar  9 12:39 ..
-rw-------  1 alberts alberts    0 mar 16 19:24 config-err-o5cX0i
drwxrwxrwt  2 root    root    4.0K mar 16 19:09 .font-unix
drwxrwxrwt  2 root    root    4.0K mar 16 19:25 .ICE-unix
-rw-------  1 alberts alberts    0 mar 16 19:32 juju-mke07d338ee843c08295d89280856d6fe06c6d68
drwx------  3 root    root    4.0K mar 16 19:25 snap.discord
drwx------  3 root    root    4.0K mar 16 19:09 snap.docker
drwx------  3 root    root    4.0K mar 16 19:11 snap.opera
drwx------  2 alberts alberts 4.0K mar 16 19:25 ssh-l4LXlwazHyUv
drwx------  3 root    root    4.0K mar 16 19:10 systemd-private-82c882db4a5040c88667e796a01b6850-colord.service-lTEA1n
drwx------  3 root    root    4.0K mar 16 19:09 systemd-private-82c882db4a5040c88667e796a01b6850-ModemManager.service-TwoSrI
drwx------  3 root    root    4.0K mar 16 19:10 systemd-private-82c882db4a5040c88667e796a01b6850-rtkit-daemon.service-kQQ54v
drwx------  3 root    root    4.0K mar 16 19:09 systemd-private-82c882db4a5040c88667e796a01b6850-systemd-resolved.service-6vMt1Z
drwx------  3 root    root    4.0K mar 16 19:09 systemd-private-82c882db4a5040c88667e796a01b6850-systemd-timesyncd.service-VnIgZh
drwxrwxrwt  2 root    root    4.0K mar 16 19:09 .Test-unix
-r--r--r--  1 root    root      11 mar 16 19:09 .X0-lock
drwxrwxrwt  2 root    root    4.0K mar 16 19:09 .X11-unix
drwxrwxrwt  2 root    root    4.0K mar 16 19:09 .XIM-unix

![Screenshot from 2021-03-16 19 35 57](https://user-images.githubusercontent.com/46404129/111397272-e1ff1200-868e-11eb-8916-3a3e2e80845a.png)

**Comment by OrpheonZeroh** [comment]
that's right

**Comment by spowelljr** [comment]
@OrpheonZeroh Gotcha, the issue is that packages installed via Snap can only see their own files in `/tmp`. So the problem is that mininkube is copying a file to `/tmp` for Docker to copy, but because Docker is managed by Snap, it prevents it from seeing that file, resulting in `no such file or directory`. We'll have to something to detect if Docker is installed via Snap and write to the users home dir instead if that's the case.

-----

@OrpheonZeroh Gotcha, el problema es que los paquetes instalados a través de Snap solo pueden ver sus propios archivos en `/ tmp`. Entonces, el problema es que mininkube está copiando un archivo en `/ tmp` para que Docker lo copie, pero debido a que Docker es administrado por Snap, evita que vea ese archivo, lo que resulta en` no tal archivo o directorio`. Tendremos que hacer algo para detectar si Docker está instalado a través de Snap y escribir en el directorio de inicio de los usuarios si ese es el caso.
