### ISSUE TITLE
docker: Update prune suggestion to exclude minikube containers

### ISSUE THREAD

**Issue by tejal29** [kubernetes/minikube#10773]
I love`minikube pause` a lot. It saves me CPU, makes my laptop faster. 

However, after running a bunch of docker builds, my laptop ran out of memory.  I decided to run `docker system prune`
which ended up deleting minikube stopped containers.

```
➜  skaffold git:(fix_release) ✗ docker system prune 
WARNING! This will remove:
  - all stopped containers
  - all networks not used by at least one container
  - all dangling images
  - all dangling build cache

Are you sure you want to continue? [y/N] y
Deleted Containers:
8a6ffa08e4c50f7759071a7e047db6e43f22da65f8c865e791011ce50c1b8958
416a5a5eefbb25683ce97867110287183a44e5d12b9a314524ae17dfa7bac4d0
d872cdd0d0fbd57110c9350770f0b1537278398c8e8fb117529a7135f7607960
ec6ec9a968379ed54362127f2546e2ec3d779fae72445b8c846257202f2f81bf
21d3ef81b35b96f96a91c24a049a59b2cd4663d796f93945c75a154bfb332ac1

Deleted Networks:
minikube

Deleted Images:
deleted: sha256:fb344716f42ca1d99b1aa3352aeb26bcd3365b2bf8f93c3fdd290b7afc4a6dd8
deleted: sha256:09591f14029b906d83cc2305a5f33d7afb4fc7afa38a4066acd539405316362a
deleted: sha256:ed7e58353be3e7a7e3d8b0585da0cadec53ea4372bb47069533a9c67ea896c7a
....
deleted: sha256:d7547014673a01801c9cb33f3c69819930a24c7db96a4826de5e6ee1ea0ed27a

Total reclaimed space: 6.657GB
```

Issues
1) `docker system prune` delete stopped containers and i had totally forgotten this will delete my minikube.
  - would have appreciated some notice when i ran `minikube pause` e.g. `Warning: docker system prune will delete paused minikube`
2) Now, i have to create minikube cluster again :(

**Expected**
Is there a way we would not delete minikube containers?

```
➜  skaffold git:(fix_release) ✗ minikube status
E0310 09:47:33.266232    8299 status.go:246] status error: host: state: unknown state "minikube": docker container inspect minikube --format={{.State.Status}}: exit status 1
stdout:


stderr:
Error: No such container: minikube
E0310 09:47:33.266625    8299 status.go:249] The "minikube" host does not exist!
minikube
type: Control Plane
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent
timeToStop: Nonexistent

➜  skaffold git:(fix_release) ✗
````

**Comment by medyagh** [comment]
@tejal29 docker system prune would delete all the stopped containers, the only way to stop this, make sure minikube is  running before prune.

**Comment by tejal29** [comment]
yes. I think with Auto Pause add on, this can occur fairly often when the cluster is paused without user knowing and then puff, it gets deleted.

**Comment by medyagh** [comment]
that is a good point, one way to fix this is to suggest our users to pass a filter to the docker system prune so it does not delete minikube stopped resources.
```
docker system prune --filter="label!=created_by.minikube.sigs.k8s.io=true"
```

**Comment by tstromberg** [comment]
I don't understand this issue. Docker prune should absolutely prune stopped containers.

Pause does not stop containers.

**Comment by sharifelgamal** [comment]
I don't think we're going to do this.
