### ISSUE TITLE
Exiting due to MK_ENABLE: loading profile: cluster "minikube" does not exist

### ISSUE THREAD

**Issue by chazzrobbz** [kubernetes/minikube#10783]
**Steps to reproduce the issue:** 

1.minikube-linux-amd64 addons enable ingress. 
2.

❌  Exiting due to MK_ENABLE: loading profile: cluster "minikube" does not exist

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

😄  [devnation] minikube v1.18.1 on Centos 8.3.2011
🆕  Kubernetes 1.20.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.20.2
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node devnation in cluster devnation
🏃  Updating the running virtualbox "devnation" VM ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.3 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v4
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "devnation" cluster and "default" namespace by default

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by chazzrobbz** [comment]
Found the solution. Silly mistake failed to include the -p flag in my minikube addons enable ingress command

minikube-linux-amd64 addons enable ingress -p devnation

**Comment by chazzrobbz** [comment]
▪ Using image us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2
    ▪ Using image jettech/kube-webhook-certgen:v1.2.2
    ▪ Using image jettech/kube-webhook-certgen:v1.3.0
🔎  Verifying ingress addon...

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

Now this is the new issue I'm facing.
Help me troubleshoot this ?

**Comment by chazzrobbz** [comment]
▪ Using image us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.40.2
    ▪ Using image jettech/kube-webhook-certgen:v1.2.2
    ▪ Using image jettech/kube-webhook-certgen:v1.3.0
🔎  Verifying ingress addon...
🌟  The 'ingress' addon is enabled

Re ran the initial command again. You have to be patient enough. 1 min or more. :)

**Comment by medyagh** [comment]
@chazzrobbz glad u found the correct usage :) I will close this issue. please feel free to reopen if needed
