### ISSUE TITLE
minikube kubectl appends --cluster flag breaking exec commands

### ISSUE THREAD

**Issue by bkeelan** [kubernetes/minikube#10791]
Looks like [ #10535](https://github.com/kubernetes/minikube/pull/10535) may have introduced a bug
```
[minikube] ~ $ minikube kubectl -- --context minikube exec ambassador-84ffc9fdc4-nxp4h -- echo "hello"
hello --cluster minikube

[minikube] ~ $ kubectl --context minikube exec ambassador-84ffc9fdc4-nxp4h -- echo "hello"
hello
```

This causes issues when trying to run exec commands because the `--cluster` flag is always appended to the end leading to issues such as

```
[minikube] ~ $ minikube kubectl -- --context minikube exec mysql-db-79b945965d-gtzf7 -- mysqladmin ping

mysqladmin: [ERROR] unknown option '--cluster'
command terminated with exit code 2
``` 
```
[minikube] ~ $ minikube version
minikube version: v1.18.1
commit: 09ee84d530de4a92f00f1c5dbc34cead092b95bc
```

**Comment by afbjorklund** [comment]
I have noticed this as well, ever since the introduction of that extra `--` in exec.

`kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.`
