### ISSUE TITLE
Upgrade csi-hostpath-driver addon to v1.6.0

### ISSUE THREAD

**Issue by govargo** [kubernetes/minikube#10797]
VolumeSnapshot is upgraded to GA by https://github.com/kubernetes/minikube/pull/10654.
But current csi-hostpath-driver addon is not latest version(It's using rc image version).

I'll send PR to upgrade csi-hostpath-driver addon to v1.6.0(latest).

/area addons

**Comment by medyagh** [comment]
sounds good !
