### ISSUE TITLE
Trouble setting up minikube in Alpine Linux

### ISSUE THREAD

**Issue by Myssiry** [kubernetes/minikube#10805]
Can you please help me with installing minikube on Alpine Linux?
I am following instruction from https://minikube.sigs.k8s.io/docs/start/

**Steps to reproduce the issue:** 

1. Have docker installed(https://wiki.alpinelinux.org/wiki/Docker)
2. Install curl `sudo apk add curl`
3. Download minikube `curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64`
4. Add minikube to path `sudo install minikube-linux-amd64 /usr/local/bin/minikube`
5. Execute any command with minikube for example: `minikube` or `minikube start` or `minikube start --driver=docker`

**Full output of failed command:** 
```
/usr/local/bin/minikube: line 1: ELF: not found
/usr/local/bin/minikube: line 2: @$: not found
/usr/local/bin/minikube: line 1: %: not found
/usr/local/bin/minikube: line 3: can't open : no such file
/usr/local/bin/minikube: line 1: %: not found
/usr/local/bin/minikube: line 4: o%X: not found
/usr/local/bin/minikube: line 5: x not found
/usr/local/bin/minikube: line 5: Yٯ: not found
/usr/local/bin/minikube: line 6: syntax error: unexpected ")"
/usr/local/bin/minikube: line 5: xYY: not found
```

**Full output of `minikube start` command used, if not already included:**
Completely same as above

**Optional: Full output of `minikube logs` command:**
Completely same as above

**Comment by afbjorklund** [comment]
Try downloading again, looks like your file got corrupted ?

Ultimately you would want to compare the checksum as well:

```
$ curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
$ curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64.sha256
$ sha256sum minikube-linux-amd64
86f65235361ebe4916350d988c756fcb2f27fc1bd3e2d84912462b39bb660dfe  minikube-linux-amd64
$ cat minikube-linux-amd64.sha256 
86f65235361ebe4916350d988c756fcb2f27fc1bd3e2d84912462b39bb660dfe
```

Before you install it. Unfortunately, there are no signatures yet.

**Comment by Myssiry** [comment]
Checksum is fine.
I have also tried downloading it fresh a few times.
This is not the problem sadly.
```shell
$ sha256sum minikube-linux-amd64
86f65235361ebe4916350d988c756fcb2f27fc1bd3e2d84912462b39bb660dfe  minikube-linux-amd64
$ cat minikube-linux-amd64.sha256
86f65235361ebe4916350d988c756fcb2f27fc1bd3e2d84912462b39bb660dfe
```

**Comment by afbjorklund** [comment]
And you are on same architecture, etc ?

```console
uname -m
x86_64
```

**Comment by afbjorklund** [comment]
That does indeed seem to be the case.

Tried running with `alpine:latest`:

```console
~ # more /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.13.2
PRETTY_NAME="Alpine Linux v3.13"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
~ # minikube version
ash: minikube: not found
~ # ./minikube version
minikube version: v1.18.0
commit: 9aee24b86106dca1af580dae2db904695ea854f4
```

So the regular binary **doesn't** work.

Only the static, that I had built myself.

**Comment by afbjorklund** [comment]
Unfortunately the Alpine package is quite out-of-date: (0.35.0, 2019)

https://pkgs.alpinelinux.org/package/edge/testing/x86_64/minikube

**Comment by Myssiry** [comment]
> 
> 
> And you are on same architecture, etc ?
> 
> ```
> $ uname -m
> x86_64
> ```
> 
> But I guess Alpine runs with musl and not glibc, maybe that is part of the problem ?
> 
> ```
> $ ldd minikube-linux-amd64
> 	linux-vdso.so.1 (0x00007ffe9e5d0000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fdb4cf79000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fdb4cd87000)
> 	/lib64/ld-linux-x86-64.so.2 (0x00007fdb4cfcb000)
> ```
> 
> You might have to build a special binary for your C library, or perhaps even a static one.

Actually I am on `i686`. That might be a problem too.

**Comment by afbjorklund** [comment]
> Actually I am on `i686`. That might be a problem too.

Yeah, that has not be tried afaik. There are no images and no binaries, for that 32-bit platform...

Kubernetes supports 32-bit, but only partially and only on ARM (mostly because of Raspberry Pi)

`ALL_ARCH = amd64 arm arm64 ppc64le s390x`

I am afraid you will have to upgrade.

**Comment by Myssiry** [comment]
Ok, thanks for you help.

**Comment by afbjorklund** [comment]
Both i686 and armv6 are basically in the same situation, they are too old and too small for regular Kubernetes.

You will be able to run some Docker containers, but you would be better off with e.g. Nomad for orchestration.

**Comment by Myssiry** [comment]
I was able to get rancher to work on it before. Althought it was running Ubuntu before. So I will probably just go back to it. 
I assume I can close this issue now?

**Comment by afbjorklund** [comment]
Due to the 2 GB memory requirement, we will probably only target Raspberry Pi 4 for minikube anyway.

So as soon as Raspberry Pi OS goes 64-bit by default, there will be no more 32-bit platforms around.

**Comment by afbjorklund** [comment]
>  I assume I can close this issue now?

Yes, there are no kubernetes images and no minikube images around for this platform (`x86`, 32-bit)

So you would have to compile everything yourself, and I don't think it would be worth the trouble ?

**Comment by afbjorklund** [comment]
We should probably have GNU C Library and 64-bit architecture listed as requirements in the "fine print"

And if someone is using Alpine Linux on x86_64, it would probably be a good idea to update that old apk...

**Comment by Myssiry** [comment]
Hello, just wanted to tell you that I found a solution to my problem.
I was accidentally using the wrong version of Alpine Linux.(Which was build for different architecture.)
I reinstalled my OS with the `x86_64 ` version of Alpine Linux.
Minikube works perfectly now.
Thank you for your help. I would not have realized this without you.

**Comment by afbjorklund** [comment]
Glad to know it worked out!

Unfortunately our current method of installation requires the user to know their Operating System and their Architecture...

Most users don't reallly care, they just want to install something that works on their machine - or get a warning if it does not.

But we'll continue to document.


![caution-5096068_960_720](https://user-images.githubusercontent.com/10364051/111063097-23d06280-84ad-11eb-832e-45a4546639ae.png)
