### ISSUE TITLE
Slow system docker:  "GUEST_STOP_TIMEOUT: context deadline exceeded"

### ISSUE THREAD

**Issue by sheikhimtiaz** [kubernetes/minikube#10809]
**Steps to reproduce the issue:** 

1.  Start the minikube start
2.  See the dash board with : minikube dashboard
3. Then finally: minikube stop (This is where command fails with following output)

I0314 00:18:46.930471    9555 out.go:239] Setting OutFile to fd 1 ...
I0314 00:18:46.931253    9555 out.go:291] isatty.IsTerminal(1) = true
I0314 00:18:46.931266    9555 out.go:252] Setting ErrFile to fd 2...
I0314 00:18:46.931275    9555 out.go:291] isatty.IsTerminal(2) = true
I0314 00:18:46.931445    9555 root.go:308] Updating PATH: /Users/sheikhimtiaz/.minikube/bin
W0314 00:18:46.931720    9555 root.go:283] Error reading config file at /Users/sheikhimtiaz/.minikube/config/config.json: open /Users/sheikhimtiaz/.minikube/config/config.json: no such file or directory
I0314 00:18:46.932487    9555 out.go:246] Setting JSON to false
I0314 00:18:46.932801    9555 mustload.go:66] Loading cluster: minikube
I0314 00:18:46.933473    9555 stop.go:39] StopHost: minikube
I0314 00:18:46.972638    9555 out.go:129] ✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
I0314 00:18:46.973314    9555 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0314 00:19:05.977598    9555 out.go:191] ❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 19.004554555s
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 19.004554555s
W0314 00:19:05.977724    9555 out.go:191] 💡  Restarting the docker service may improve performance.
💡  Restarting the docker service may improve performance.
W0314 00:19:05.977776    9555 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0314 00:19:05.977807    9555 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0314 00:19:05.977834    9555 retry.go:31] will retry after 1.104660288s: context deadline exceeded
I0314 00:19:07.082604    9555 stop.go:39] StopHost: minikube
I0314 00:19:07.119599    9555 out.go:129] ✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
I0314 00:19:07.119960    9555 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0314 00:19:26.122493    9555 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0314 00:19:26.122537    9555 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0314 00:19:26.122561    9555 retry.go:31] will retry after 2.160763633s: context deadline exceeded
I0314 00:19:28.284920    9555 stop.go:39] StopHost: minikube
I0314 00:19:28.333736    9555 out.go:129] ✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
I0314 00:19:28.334178    9555 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0314 00:19:47.341289    9555 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0314 00:19:47.341325    9555 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0314 00:19:47.341347    9555 retry.go:31] will retry after 2.62026012s: context deadline exceeded
I0314 00:19:49.961615    9555 stop.go:39] StopHost: minikube
I0314 00:19:50.000667    9555 out.go:129] ✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
I0314 00:19:50.000948    9555 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0314 00:20:09.007842    9555 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0314 00:20:09.007942    9555 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0314 00:20:09.007974    9555 retry.go:31] will retry after 3.164785382s: context deadline exceeded
I0314 00:20:12.176772    9555 stop.go:39] StopHost: minikube
I0314 00:20:12.221476    9555 out.go:129] ✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
I0314 00:20:12.221846    9555 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0314 00:20:31.226111    9555 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0314 00:20:31.226155    9555 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0314 00:20:31.226188    9555 retry.go:31] will retry after 4.680977329s: context deadline exceeded
I0314 00:20:35.910138    9555 stop.go:39] StopHost: minikube
I0314 00:20:35.956395    9555 out.go:129] ✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
I0314 00:20:35.956741    9555 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0314 00:20:54.961896    9555 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0314 00:20:54.961953    9555 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0314 00:20:54.992626    9555 out.go:129] 

W0314 00:20:54.993126    9555 out.go:191] ❌  Exiting due to GUEST_STOP_TIMEOUT: context deadline exceeded
❌  Exiting due to GUEST_STOP_TIMEOUT: context deadline exceeded
W0314 00:20:54.993267    9555 out.go:191] 

W0314 00:20:54.993364    9555 out.go:191] 😿  If the above advice does not help, please let us know: 
😿  If the above advice does not help, please let us know: 
W0314 00:20:54.993436    9555 out.go:191] 👉  https://github.com/kubernetes/minikube/issues/new/choose
👉  https://github.com/kubernetes/minikube/issues/new/choose
I0314 00:20:55.029676    9555 out.go:129] 

**Optional: Full output of `minikube logs` command:**

❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 19.002888544s
💡  Restarting the docker service may improve performance.
❌  Exiting due to GUEST_STATUS: state: unknown state "minikube": context deadline exceeded
😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@sheikhimtiaz minikube indicates that the Docker is very very slow on your machine, it took 19 Seconds to do "docker inspect"

do u mind trying this and see if it helps ?
```
minikube delete --all
docker system prune --all 
# and then Restart Docker 
minikube start
```

**Comment by sheikhimtiaz** [comment]
Thanks @medyagh for your kind response. 
I have tried the above commands and it seems somewhat stable now. works fine. I will let you know if the problem reappears again.

**Comment by spowelljr** [comment]
@sheikhimtiaz I'm glad this solved your issue, I'm going to close this ticket, feel free to reopen if needed.

**Comment by cmaster11** [comment]
Just encountered the same issue, `minikube stop` would hang and then throw the timeout. Just leaving this here for future reference.

Without having to run `minikube delete`, I managed to solve by:

1. `service docker stop`
2. Get the PID of the running minikube process `ps -ef | grep minikube` and kill it `kill -9 PID`
3. `minikube start`
