### ISSUE TITLE
test errror spam: unexpected stderr: "    > docker-machine-driver-kvm2.

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10802]
error_spam_test.go:79: unexpected stderr: "    > docker-machine-driver-kvm2....: 65 B / 65 B [----------] 100.00% ? p/s 0s    > docker-machine-driver-kvm2: 11.39 MiB / 11.39 MiB [----] 100.00% ? p/s 0s"

I think the lib might be poluting the stderr for no reason, as seen in this test

https://storage.googleapis.com/minikube-builds/logs/10793/e8a35de/KVM_Linux.html#fail_TestErrorSpam

**Comment by prezha** [comment]
@medyagh actually, i think this doesn't come from `TestErrorSpam` but from another completely different concurrently-run test - as seen in the log:
```
...
error_spam_test.go:64: (dbg) Run:  out/minikube-linux-amd64 start -p nospam-20210312200735-7295 -n=1 --memory=2250 --wait=false --driver=kvm2 
> docker-machine-driver-kvm2....: 65 B / 65 B [----------] 100.00% ? p/s 0s    > docker-machine-driver-kvm2: 48.57 MiB / 48.57 MiB [----] 100.00% ? p/s 0s    > docker-machine-driver-kvm2....: 65 B / 65 B [----------] 100.00% ? p/s 0s    > docker-machine-driver-kvm2: 48.57 MiB / 48.57 MiB [----] 100.00% ? p/s 1s--- PASS: TestKVMDriverInstallOrUpdate (2.35s)
=== CONT  TestErrorSpam
error_spam_test.go:64: (dbg) Done: out/minikube-linux-amd64 start -p nospam-20210312200735-7295 -n=1 --memory=2250 --wait=false --driver=kvm2 : (1m6.062264248s)
...
```
end of 2nd line: `--- PASS: TestKVMDriverInstallOrUpdate (2.35s)`
