### ISSUE TITLE
Running minikube on outdated and unsupported platforms

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#10845]
Running minikube requires `amd64` for x86, and at least an `armv7` (but preferrably `arm64`) for ARM...

It also requires 2 GB of RAM and 20 GB of hard disk, which might not be available on the local machine.

But we could _still offer_ `minikube start` and the kubernetes experience on these machines, for learning ?

Assuming that there is _another_ computer available to run the actual cluster (but **not** the desktop interface)

~~#4733~~

----

With the possibility of loading and building images in the cluster, and also running kubernetes client there*,
the lack of `docker` and `kubectl` is not really blocking. The client would only be used for editing files etc.

\* #10843

This would allow running minikube on ~~`i586`~~ `i686` and ~~`armv5`~~ `armv6`, towards an `amd64` or `arm64` VM.
Ultimately, we also want to be able to use a different architecture for the host and the cluster (different story*)

\* #9593 

`GOARCH=386`

`GOARCH=arm GOARM=5`

**Comment by medyagh** [comment]
I dont see why not !

**Comment by tstromberg** [comment]
What changes are you suggesting to minikube exactly?

**Comment by afbjorklund** [comment]
> What changes are you suggesting to minikube exactly?

My initial idea was to build a static minikube binary for these, but that also assumes it has access to another machine for the cluster.

So it might need some improvements to the ssh driver, and it would also need splitting of architecture between host and machine.

Basically I want to stretch the definition of "local Kubernetes", without changing the main target or introduce any security concerns.

The end goal is to bring it to more platforms, you might not have access to _one_ big computer (or VM) - but maybe two smaller ?

**Comment by medyagh** [comment]
I believe the pre-requisite for this is, to have our cached fixed

**Comment by medyagh** [comment]
I am going to close this issue for now till we have more interest from the users
