### ISSUE TITLE
Add support for running kubectl remotely as an alternative

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#10843]
Some clients don't have the possibility to run the kubernetes client locally, due to binaries not being available...

But we already install `kubectl` on the control plane in the cluster, so we can run that using the `ssh` connection.

```
$ minikube kubectl --ssh=false -- get nodes
NAME       STATUS   ROLES                  AGE   VERSION
minikube   Ready    control-plane,master   12h   v1.20.2
```
```
$ minikube kubectl --ssh=true -- get nodes
NAME       STATUS   ROLES                  AGE   VERSION
minikube   Ready    control-plane,master   12h   v1.20.2
```

This makes minikube accessible on more platforms.

Especially when using the `ssh` driver for the cluster.

**Comment by medyagh** [comment]
sounds like a good idea !
