### ISSUE TITLE
minikube addons enable logviewer

### ISSUE THREAD

**Issue by husseinferas** [kubernetes/minikube#10857]
❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/logviewer-dp-and-svc.yaml -f /etc/kubernetes/addons/logviewer-rbac.yaml: Process exited with status 1
stdout:
service/logviewer unchanged
serviceaccount/sa-logviewer unchanged
clusterrole.rbac.authorization.k8s.io/cr-logviewer unchanged
clusterrolebinding.rbac.authorization.k8s.io/crb-logviewer unchanged

stderr:
error: error parsing /etc/kubernetes/addons/logviewer-dp-and-svc.yaml: error converting YAML to JSON: yaml: line 25: did not find expected key
]

**Comment by husseinferas** [comment]
Thank you for reply @spowelljr 

- The version of minikube.  _**v1.15.1**_
- The driver you are using. (docker, virtualbox, hyperv....)    _**docker**_
- The Operation system you are using (windows, mac or linux and version of it)    _**linux ubunut 20 desktop**_
- The full output of the command you are using by adding --alsologtostderr, for example:

` I0318 08:45:10.371538   23734 out.go:185] Setting OutFile to fd 1 ...
I0318 08:45:10.372237   23734 out.go:237] isatty.IsTerminal(1) = true
I0318 08:45:10.372248   23734 out.go:198] Setting ErrFile to fd 2...
I0318 08:45:10.372257   23734 out.go:237] isatty.IsTerminal(2) = true
I0318 08:45:10.372355   23734 root.go:279] Updating PATH: /home/hussein/.minikube/bin
I0318 08:45:10.372806   23734 addons.go:55] Setting logviewer=true in profile "minikube"
I0318 08:45:10.372854   23734 addons.go:131] Setting addon logviewer=true in "minikube"
I0318 08:45:10.372878   23734 host.go:66] Checking if "minikube" exists ...
I0318 08:45:10.373637   23734 cli_runner.go:110] Run: docker container inspect minikube --format={{.State.Status}}
I0318 08:45:10.408819   23734 addons.go:243] installing /etc/kubernetes/addons/logviewer-dp-and-svc.yaml
I0318 08:45:10.408857   23734 ssh_runner.go:215] scp deploy/addons/logviewer/logviewer-dp-and-svc.yaml.tmpl --> /etc/kubernetes/addons/logviewer-dp-and-svc.yaml (1973 bytes)
I0318 08:45:10.408923   23734 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0318 08:45:10.443904   23734 sshutil.go:45] new ssh client: &{IP:127.0.0.1 Port:49156 SSHKeyPath:/home/hussein/.minikube/machines/minikube/id_rsa Username:docker}
I0318 08:45:10.557026   23734 addons.go:243] installing /etc/kubernetes/addons/logviewer-rbac.yaml
I0318 08:45:10.557050   23734 ssh_runner.go:215] scp deploy/addons/logviewer/logviewer-rbac.yaml.tmpl --> /etc/kubernetes/addons/logviewer-rbac.yaml (1064 bytes)
I0318 08:45:10.567968   23734 ssh_runner.go:148] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/logviewer-dp-and-svc.yaml -f /etc/kubernetes/addons/logviewer-rbac.yaml
W0318 08:45:10.711808   23734 addons.go:264] apply failed, will retry: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/logviewer-dp-and-svc.yaml -f /etc/kubernetes/addons/logviewer-rbac.yaml: Process exited with status 1
stdout:
service/logviewer unchanged
serviceaccount/sa-logviewer unchanged
clusterrole.rbac.authorization.k8s.io/cr-logviewer unchanged
clusterrolebinding.rbac.authorization.k8s.io/crb-logviewer unchanged

stderr:
error: error parsing /etc/kubernetes/addons/logviewer-dp-and-svc.yaml: error converting YAML to JSON: yaml: line 25: did not find expected key
I0318 08:45:10.712075   23734 retry.go:31] will retry after 276.165072ms: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/logviewer-dp-and-svc.yaml -f /etc/kubernetes/addons/logviewer-rbac.yaml: Process exited with status 1
stdout:
service/logviewer unchanged
serviceaccount/sa-logviewer unchanged
clusterrole.rbac.authorization.k8s.io/cr-logviewer unchanged
clusterrolebinding.rbac.authorization.k8s.io/crb-logviewer unchanged

stderr:
error: error parsing /etc/kubernetes/addons/logviewer-dp-and-svc.yaml: error converting YAML to JSON: yaml: line 25: did not find expected key
I0318 08:45:10.988487   23734 ssh_runner.go:148] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/logviewer-dp-and-svc.yaml -f /etc/kubernetes/addons/logviewer-rbac.yaml
W0318 08:45:11.141522   23734 addons.go:264] apply failed, will retry: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/logviewer-dp-and-svc.yaml -f /etc/kubernetes/addons/logviewer-rbac.yaml: Process exited with status 1
stdout:
service/logviewer unchanged
serviceaccount/sa-logviewer unchanged
clusterrole.rbac.authorization.k8s.io/cr-logviewer unchanged
clusterrolebinding.rbac.authorization.k8s.io/crb-logviewer unchanged

  `

**Comment by spowelljr** [comment]
Hi @husseinferas, thanks you very much for your response.

I did some digging for your issue, based on the logs you provided me it seems the issue is `apply failed, will retry` followed by `error converting YAML to JSON: yaml: line 25: did not find expected key`.

Here's a past issue that seems to have the same problem you're experiencing #9722.

Based on that issue this seems to be an issue specific to v1.15.0 & v1.15.1 of minikube.

Please try updating to the newest version of minikube v1.18.1 and let me know if the error still persists.
