### ISSUE TITLE
logs command outputs lines slowly, takes >45 seconds to run

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#10854]
I realized that on macOS, with minikube v1.18.1, the logs command runs so slowly that I can literally see the lines drawn individually. A ran it with the `time` command, and it can take over a minute to run. Here is output from my last, slightly faster run:

```
________________________________________________________
Executed in   53.95 secs   fish           external 
   usr time    0.99 secs  101.00 micros    0.99 secs 
   sys time    1.08 secs  1410.00 micros    1.08 secs 
```

It feels like the buffer is flushed between each line, but I don't see the CPU load to indicate that is in fact the case. We should throw a profiler at the `logs` command to better understand why it's taking so much time.

To duplicate:

`minikube start --container-runtime=containerd`
`minikube logs`

As a comparison, this command runs in 1.2 seconds: 

` time minikube ssh "sudo journalctl -u kubelet --no-pager" >/tmp/x`

**Comment by afbjorklund** [comment]
Results on Ubuntu:

```

real	0m3,658s
user	0m0,504s
sys	0m0,355s
```

**Comment by tstromberg** [comment]
I can confirm this annoying problem still exists with 1.20.0-beta.0 on macOS 10.15.7

minikube logs > /dev/null  0.55s user 0.73s system 3% cpu 32.106 total
