### ISSUE TITLE
minkube on windows won't pass ssh step

### ISSUE THREAD

**Issue by jaysonsantos** [kubernetes/minikube#1086]
**Minikube version** (use `minikube version`):
v0.16.0

**Environment**:
- **OS** (e.g. from /etc/os-release): windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO`): 13:        "Boot2DockerURL": "file://C:/Users/santo/.minikube/cache/iso/minikube-v1.0.6.iso",
- **Install tools**:
- **Others**: openssh installed from choco install openssh (microsoft's port, https://github.com/powershell/win32-openssh)

**What happened**:
minikube is able to go up to the step where it starts the vm and then get it's ip but ssh command will always fail (log below) 

**What you expected to happen**:
minikube start should work

**How to reproduce it** (as minimally and precisely as possible):
minikube start -v 7

**Anything else do we need to know**:

running ssh with the same parameters but removing -F /dev/null will make it return status code as 0.
this is the output and it will always retry the same thing.

Getting to WaitForSSH function...
(minikube) Calling .GetSSHHostname
(minikube) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minikube ).state
(minikube) DBG | [stdout =====>] : Running
(minikube) DBG |
(minikube) DBG | [stderr =====>] :
(minikube) DBG | [executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM minikube ).networkadapters[0]).ipaddresses[0]
(minikube) DBG | [stdout =====>] : fe80::215:5dff:fe38:162
(minikube) DBG |
(minikube) DBG | [stderr =====>] :
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: external
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@fe80::215:5dff:fe38:162 -o IdentitiesOnly=yes -i C:\Users\santo\.minikube\machines\minikube\id_rsa -p 22] C:\Program Files\OpenSSH-Win64\ssh.exe <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: exit status 255:
Error getting ssh command 'exit 0' : Something went wrong running an SSH command!
command : exit 0
err     : exit status 255
output  :

**Comment by raghur** [comment]
@jaysonsantos I faced the same issue - looks like it cant handle path with spaces. Easiest way around is to remove the external ssh.exe from path temporarily - this forces minikube to use the internal ssh and go beyond this step.

BTW, there's a few more troubles/workarounds I had to do on Windows - wrote up some of those here https://blog.rraghur.in/2017/01/minikube-on-windows-teething-troubles.html

**Comment by dlorenc** [comment]
We can try forcing libmachine to use the native client all the time.

**Comment by Ansonhkg** [comment]
> @jaysonsantos I faced the same issue - looks like it cant handle path with spaces. Easiest way around is to remove the external ssh.exe from path temporarily - this forces minikube to use the internal ssh and go beyond this step.
> 
> BTW, there's a few more troubles/workarounds I had to do on Windows - wrote up some of those here https://blog.rraghur.in/2017/01/minikube-on-windows-teething-troubles.html

Spaces was the problem in my case. I had to change my switch from "Hyper V External Virtual Switch" to simply "hyperv", then I run "minikube start --vm-driver="hyperv" --memory=4096 --cpus=4 --hyperv-virtual-switch="hyperv" --v=7 --alsologtostderr" it's all working now! Thanks!
