### ISSUE TITLE
Error creating Virtualbox with minikube 

### ISSUE THREAD

**Issue by sanjarora** [kubernetes/minikube#10864]
Team , getting below error as I install minikube on my local setup @ macos

Exiting due to RUNTIME_ENABLE: Run: "/bin/bash -c \"sudo mkdir -p /etc && printf %s \"runtime-endpoint: unix:///var/run/dockershim.sock\nimage-endpoint: unix:///var/run/dockershim.sock\n\" | sudo tee /etc/crictl.yaml\"": NewSession: new client: new client: dial tcp 127.0.0.1:49881: connect: connection refused

please find below command details :

brew install minikube
==> Downloading https://homebrew.bintray.com/bottles/minikube-1.18.1.catalina.bottle.tar.gz
==> Downloading from https://d29vzk4ow07wi7.cloudfront.net/ca09a0fb9854641e6352fc1a983529f21bcac35be52b39d0cf664033459af893?response-content-disposition=attachment%3Bfilename%3D%22minikube-1.18.1.catali
######################################################################## 100.0%
==> Pouring minikube-1.18.1.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d
==> Summary
🍺  /usr/local/Cellar/minikube/1.18.1: 8 files, 59.4MB
Macbooks-MacBook-Pro:home macbook$ minikube start
😄  minikube v1.18.1 on Darwin 10.15.7
✨  Automatically selected the virtualbox driver
💿  Downloading VM boot image ...
    > minikube-v1.18.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.18.0.iso: 212.99 MiB / 212.99 MiB  100.00% 2.30 MiB p/s 1m33s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.20.2 preload ...
    > preloaded-images-k8s-v9-v1....: 491.22 MiB / 491.22 MiB  100.00% 2.76 MiB
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...

❌  Exiting due to RUNTIME_ENABLE: Run: "/bin/bash -c \"sudo mkdir -p /etc && printf %s \"runtime-endpoint: unix:///var/run/dockershim.sock\nimage-endpoint: unix:///var/run/dockershim.sock\n\" | sudo tee /etc/crictl.yaml\"": NewSession: new client: new client: dial tcp 127.0.0.1:49881: connect: connection refused

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by spowelljr** [comment]
Thank you @sanjarora for sharing your experience! If you don't mind, could you please provide:

- The full output of the command you are using by adding --alsologtostderr, for example:
```
$ minikube start --alsologtostderr
```

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by medyagh** [comment]
Hi @sanjarora, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by sanjarora** [comment]
Apologies for delayed response - thanks for your help here ..
