### ISSUE TITLE
"minikube start" or "minikube start -- vm-driver=virtualbox" 

### ISSUE THREAD

**Issue by orlygh** [kubernetes/minikube#10863]
**Steps to reproduce the issue:** 

1.on a amd_64 w10 pro powershell CLI, I run the "minikube start" or "minikube start -- vm-driver=virtualbox"  and I get the same output
* minikube v1.18.1 on Microsoft Windows 10 Pro 10.0.19042 Build 19042
* Using the ssh driver based on existing profile

X Exiting due to MK_USAGE: No IP address provided. Try specifying --ssh-ip-address, or see https://minikube.sigs.k8s.io/docs/drivers/ssh/

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
Please try re-installing Virtualbox, and then do "minikube delete" before trying again with "minikube start"

A future version of minikube will _avoid_ selecting the "ssh" driver by default, unlesss requested by the user

**Comment by orlygh** [comment]
re-installing Virtualbox, and then do "minikube delete" before trying again with "minikube start"

minikube delete failed  see below
 

PS C:\Users\Orly> minikube delete
* Uninstalling Kubernetes v1.20.2 using kubeadm ...
E0318 08:57:47.638230   16004 delete.go:391] unpause failed: list paused: docker: NewSession: new client: new client: dial tcp 192.168.56.1:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
X error deleting profile "minikube": failed to delete cluster: NewSession: new client: new client: dial tcp 192.168.56.1:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

Thank for the response

**Comment by tstromberg** [comment]
Try running `minikube delete` - it seems like you might have an existing profile that used the ssh feature.

**Comment by afbjorklund** [comment]
If you want to delete _everything_ and start over (with virtualbox), there is a "minikube delete --purge"

**Comment by sharifelgamal** [comment]
Upgrading to the newest version of minikube and running `minikube delete --all --purge` should fix any environmental issues you are seeing.
