### ISSUE TITLE
registry-creds may not be working with gcr

### ISSUE THREAD

**Issue by mdenend** [kubernetes/minikube#10861]
Hi there,

I am currently using minikube v1.18.1, commit 09ee84d530de4a92f00f1c5dbc34cead092b95bc, running minikube as a Docker image on macOS 10.15. 

I followed the directions given here to try and connect to gcr here from within minikube: https://minikube.sigs.k8s.io/docs/handbook/registry/

I am still not able to connect to my gcr (getting `ImagePullError` for my pod) after running `minikube addons configure registry-creds` and `minikube addons enable registry-creds`, using my default credentials in `application_default_credentials.json`.

I noticed something odd. It appears the add on creates secrets in each namespace corresponding to the secrets. However, the gcr-secret appears to have no data in it. Is this why I can't connect to gcr?

```
$ kgsec
NAME                             TYPE                                  DATA   AGE
acr-secret                       kubernetes.io/dockerconfigjson        1      16m
awsecr-cred                      kubernetes.io/dockerconfigjson        1      16m
default-token-xr8x6              kubernetes.io/service-account-token   3      20m
dpr-secret                       kubernetes.io/dockerconfigjson        1      16m
gcr-secret                       Opaque                                0      16m
influxdb-auth                    Opaque                                2      17m
sh.helm.release.v1.tsds-api.v1   helm.sh/release.v1                    1      18m
tsds-api-influxdb-token-2bc2l    kubernetes.io/service-account-token   3      18m
```

Here's my latest start if you need it (I deleted the cluster beforehand, was trying everything I knew to make this work).

```
$ minikube start
😄  minikube v1.18.1 on Darwin 10.15.7
✨  Automatically selected the docker driver. Other choices: hyperkit, virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.20.2 preload ...
    > preloaded-images-k8s-v9-v1....: 491.22 MiB / 491.22 MiB  100.00% 30.47 Mi
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v4
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

Let me know if you need any additional info. Thanks!

**Comment by medyagh** [comment]
@mdenend  that addon is not maitained by minikube team itself, but a 3rd party addon, 
we are working on adding the functionality to gcp-auth addon which will be better support 

here is the issue to track the progress on that

https://github.com/kubernetes/minikube/issues/9002

**Comment by sharifelgamal** [comment]
I have tried the registry-creds addon and it does work with GCR, I've had success using it but first enabling it then configuring it.

**Comment by mdenend** [comment]
@medyagh @sharifelgamal Thanks for getting back to me. When will the `gcp-auth` plugin have the changes that look like they were recently merged? A comment on #9002 suggests sometime in April? Would be awesome if it were ready that quickly.

I tried as @sharifelgamal suggested, and still wasn't having luck pulling the image using that order, even after wiping minikube. Also still noticing that gcr-secret has no data after waiting for the config to reload.

If all is good, can I keep this issue open until the gcp-auth plugin is updated, and that I verify things are working as expected?

**Comment by sharifelgamal** [comment]
Yeah, the 1.19 minikube release will have the new functionality, which should be out this week.

**Comment by afbjorklund** [comment]
Minikube 1.19 has been released, see https://github.com/kubernetes/minikube/releases/tag/v1.19.0
