### ISSUE TITLE
Minikube dashboard and storage-provisioner image pull failed in China

### ISSUE THREAD

**Issue by Chuyukang** [kubernetes/minikube#10889]
**Steps to reproduce the issue:** 

1. minikube start --image-mirror-country=cn
2. minikube dashboard

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

😄  Arch  上的 minikube v1.18.1
✨  根据现有的配置文件使用 docker 驱动程序
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🐳  正在 Docker 20.10.3 中准备 Kubernetes v1.20.2…
🔎  Verifying Kubernetes components...
    ▪ Using image **registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-minikube/storage-provisioner:v4** (global image repository)
    ▪ Using image **registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/dashboard:v2.1.0@sha256:7f80b5ba141bead69c4fee8661464857af300d7d7ed0274cf7beecedc00322e6** (global image repository)
    ▪ Using image **registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/metrics-scraper:v1.0.4@sha256:555981a24f184420f3be0c79d4efb6c948a85cfce84034f85a563f4151a81cbf** (global image repository)
🌟  Enabled addons: storage-provisioner, default-storageclass, dashboard
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Additional Notes**
The image urls for storage-provisioner, dashboard, metrics-scraper are wrong.

**Comment by Chuyukang** [comment]
The image urls for storage-provisioner, dashboard, metrics-scraper are wrong.

Dashboard and metrics-scraper image is available on docker hub. But minikube dashboard will use the wrong url, even if change the image manually.

Storage-provisioner image does not seem to be available on docker hub.

**Comment by RainingNight** [comment]
@Chuyukang 怎么解决的，我也遇到同样的问题了。

**Comment by Chuyukang** [comment]
国内没找到好用的gcr.io镜像，只能走代理。我目前是在用digital ocean上的集群。应该本地走代理下镜像也行。

**Comment by RainingNight** [comment]
这个好多坑，用了`--image-mirror-country=cn`，Ingress的镜像也变成了` registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-artifacts-prod/ingress-nginx/controller`了，问题是阿里云镜像上根部没有这些镜像。
