### ISSUE TITLE
wsl2: System has not been booted with systemd as init system (PID 1). Can't operate.

### ISSUE THREAD

**Issue by sovbangit** [kubernetes/minikube#10884]
**Steps to reproduce the issue:** 

1. Install minikube in WSL 2
2. Install virtual box
3. Start minikube

**Full output of failed command:** 

minikube start 

**Error**

**System has not been booted with systemd as init system (PID 1). Can't operate.**

**Optional: Full output of `minikube logs` command:**
<details>

sovban@DESKTOP-CE0M4V1:/c/WINDOWS/system32$ minikube start
😄  minikube v1.18.1 on Ubuntu 20.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 20.04.1 LTS

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl daemon-reload: exit status 1
stdout:

stderr:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
</details>

**Comment by tstromberg** [comment]
For some reason, minikube was configured to start with the `none` driver -- which doesn't appear to work with WSL2 out of the box. Here's my suggestion:

* Run `minikube delete`
* Install `docker` (if it isn't installed already)
* Run `minikube start` (it will default to docker)

Please let me know if this helps.

**Comment by medyagh** [comment]
Hi @sovbangit , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by kuraleb** [comment]
I was able to reproduce this problem.
Solution from @tstromberg didn't work for me as I get:

`$ sudo minikube delete
🔄  Uninstalling Kubernetes v1.22.3 using kubeadm ...
E1205 20:44:13.851355     494 delete.go:448] unpause failed: list paused: docker: docker ps --filter status=paused --filter=name=k8s_ --format={{.ID}}: exit status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
💣  error deleting profile "minikube": failed to delete cluster: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.22.3:$PATH" kubeadm reset --cri-socket /var/run/dockershim.sock --force": exit status 127
stdout:

stderr:
env: ‘kubeadm’: No such file or directory`

**Comment by tstromberg** [comment]
That sounds like a different bug - I encourage you to open an issue with
the title of: "minikube delete on Docker: kubeadm exit status 127"
