### ISSUE TITLE
cancelling scheduled stop not getting reflected in minikube status

### ISSUE THREAD

**Issue by tharun208** [kubernetes/minikube#10907]
So, I configured a `scheduled-stop` and checked the status of minikube. It shows `TimeToStop` as x time remaining.

When I canceled the `scheduled-stop` using `--cancel-scheduled`, it still shows `TimeToStop`  with the remaining time and not as `NonExistent` or not to mention ( when this pr #10906 get's merged)

minikube version: locally built from master
<img width="499" alt="Screen Shot 2021-03-24 at 12 00 13 PM" src="https://user-images.githubusercontent.com/14926492/112265447-850be900-8c98-11eb-8cb6-2dafddfd9f6a.png">

The issue is we are killing the PID's of all active `scheduled-stop` but not updating the config with `scheduledStop` as nil.

I have a draft pr. if we are prioritizing this issue means, I will make it up for review.

**Comment by tstromberg** [comment]
Thanks for finding this issue! The current behavior is wrong, and I would be happy to review a PR that fixes this behavior.
