### ISSUE TITLE
Arguments in PowerShell require quotes to not error

### ISSUE THREAD

**Issue by altwohill** [kubernetes/minikube#10900]
1. (Hyper-V was already installed previously)
2. Configure new switch for minikube called "Kubernetes Virtual Switch"
3. run the following in Administrative powershell window:

```
PS C:\WINDOWS\system32> minikube start --hyperv-virtual-switch "Kubernetes Virtual Switch" --alsologtostderr --v=2
I0323 14:31:34.062069   26444 out.go:239] Setting OutFile to fd 84 ...
I0323 14:31:34.062590   26444 out.go:286] TERM=,COLORTERM=, which probably does not support color
I0323 14:31:34.063110   26444 out.go:252] Setting ErrFile to fd 88...
I0323 14:31:34.063110   26444 out.go:286] TERM=,COLORTERM=, which probably does not support color
I0323 14:31:34.086293   26444 out.go:246] Setting JSON to false
I0323 14:31:34.105977   26444 start.go:108] hostinfo: {"hostname":"XPS15-H5D0453","uptime":13293,"bootTime":1616449801,"procs":351,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.19042 Build 19042","kernelVersion":"10.0.19042 Build 19042","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"31adaf87-f5b4-4498-b9f3-eb58b5b14e54"}
W0323 14:31:34.105977   26444 start.go:116] gopshost.Virtualization returned error: not implemented yet
I0323 14:31:34.108128   26444 out.go:129] * minikube v1.18.1 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
* minikube v1.18.1 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
I0323 14:31:34.108679   26444 notify.go:126] Checking for updates...
I0323 14:31:34.109248   26444 driver.go:323] Setting default libvirt URI to qemu:///system
I0323 14:31:42.445605   26444 out.go:129] * Using the hyperv driver based on user configuration
* Using the hyperv driver based on user configuration
I0323 14:31:42.446220   26444 start.go:276] selected driver: hyperv
I0323 14:31:42.446728   26444 start.go:718] validating driver "hyperv" against <nil>
I0323 14:31:42.446766   26444 start.go:729] status for hyperv: {Installed:false Healthy:false Running:true NeedsImprovement:false Error:C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent failed:
 Reason: Fix:Start PowerShell as an Administrator Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/}
I0323 14:31:42.447352   26444 out.go:129]

W0323 14:31:42.447970   26444 out.go:191] * Exiting due to PROVIDER_HYPERV_NOT_FOUND: The 'hyperv' provider was not found: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent failed:

* Exiting due to PROVIDER_HYPERV_NOT_FOUND: The 'hyperv' provider was not found: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent failed:

W0323 14:31:42.448052   26444 out.go:191] * Suggestion: Start PowerShell as an Administrator
* Suggestion: Start PowerShell as an Administrator
W0323 14:31:42.448999   26444 out.go:191] * Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/
I0323 14:31:42.449527   26444 out.go:129]
```
Running the command to check if Hypervisor is Present gives this:
```
PS C:\WINDOWS\system32> @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent
True
```

If I roll back to 1.6.2 as per #6683 I am able to start successfully.

**Comment by medyagh** [comment]
@altwohill sorry to hear about this... curious, are u running windows in the cloud ? or a physical machine?
if yes what cloud ?

minikube is errorig 
```
 Reason: Fix:Start PowerShell as an Administrator Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv
```

have u already tried running the powershell with administrator powers?

**Comment by altwohill** [comment]
> 
> 
> @altwohill sorry to hear about this... curious, are u running windows in the cloud ? or a physical machine?
> if yes what cloud ?

This is on a physical machine

> 
> minikube is errorig
> 
> ```
>  Reason: Fix:Start PowerShell as an Administrator Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv
> ```
> 
> have u already tried running the powershell with administrator powers?

Yes, this output occurs when running powershell as administrator.

**Comment by medyagh** [comment]
I am curious what does command returns if u run it manually ? (The one minikube runs to check if hyperkit is there)
```
@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent
```
Or maybe 
```
Get-Wmiobject Win32_ComputerSystem
```

I am curious why is command fails for u and not on our intergration tests... do u have like windows Data center hyperv ?
Is it a single user hyper setup ? What is different with your windows and than our integration test ?

**Comment by altwohill** [comment]
> 
> 
> I am curious what does command returns if u run it manually ? (The one minikube runs to check if hyperkit is there)
> 
> ```
> @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent
> ```
I did mention this in the initial note:

Running the command to check if Hypervisor is Present gives this:
```
PS C:\WINDOWS\system32> @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent
True
```


> I am curious why is command fails for u and not on our intergration tests... do u have like windows Data center hyperv ?
> Is it a single user hyper setup ? What is different with your windows and than our integration test ?

As far as I know this is just a standard windows 10 box with normal hyper-v on it. I can't speak for your integration test sorry; the only other thing to point out is it works absolutely fine when downgrading to 1.6.2, but it fails on any later version.

**Comment by medyagh** [comment]
Thank you, for providing more informations, I wonder if windows is giving Wrong exit code, in integration test use windows 10 professional edition. 

Does the error happen consistently (if u run it 5 times in a row?  I say this because I noticed in integration tests our dry-run tests exits with a non-zero code even though if it is successful .... I wonder if this is what is happenining here....


Regardless minikube should have included better logs of the root cause... another thing to check is what changed since 1.6.2 that broke it.

Does any other version newer work ? Other than 1.6.2 ?
Or 1.10 ?

**Comment by medyagh** [comment]
And  one last question, does this help ?

https://stackoverflow.com/questions/60447586/hyperv-does-not-appear-to-be-installed

**Comment by altwohill** [comment]
The problem happens consistently, and I tried the SO answer before posting here :)
I cherry-picked a bunch of versions between 1.6.2 and 18, none of them worked.

I think perhaps the way the command is being run is causing the issue. 

https://github.com/kubernetes/minikube/blob/57d33de86adc8d5e40aa1d40658882355df3b4aa/pkg/minikube/registry/drvs/hyperv/hyperv.go#L93

If I run `@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent` I get `True` back. 

However the program runs `C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent` and when I try that I get the response:

```
PS C:\WINDOWS\system32> C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent
True : The term 'True' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ True
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (True:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

I _think_ you just need to quote the arguments being passed to powershell, as we're already within a powershell session so the arguments get resolved before being passed through.

```
PS C:\WINDOWS\system32> C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive "@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent"
True
```

**Comment by medyagh** [comment]
> to quote the arguments being passed to powershell, as we're already within a powershell session so the a

@altwohill that looks like a great find you found out ! I think that might be something we could fix ! or if you are interested to make aPR I would be happy to accept the PR.

**Comment by spowelljr** [comment]
@medyagh @altwohill 
I created the following example program that mimics the minikube code in question:
```
package main

import (
        "context"
        "fmt"
        "log"
        "os/exec"
        "time"
)

func main() {
        path, err := exec.LookPath("powershell")
        if err != nil {
                log.Fatal(err)
        }

        ctx, cancel := context.WithTimeout(context.Background(), 8*time.Second)
        defer cancel()

        cmd := exec.CommandContext(ctx, path, "-NoProfile", "-NonInteractive", "@(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent")
        out, err := cmd.CombinedOutput()
        if err != nil {
                log.Fatal(err)
        }
        fmt.Printf("%s", out)

        cmd = exec.CommandContext(ctx, path, "-NoProfile", "-NonInteractive", `@([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")`)
        out, err = cmd.CombinedOutput()
        if err != nil {
                log.Fatal(err)
        }
        fmt.Printf("%s", out)

        cmd = exec.CommandContext(ctx, path, "-NoProfile", "-NonInteractive", `@([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole(([System.Security.Principal.SecurityIdentifier]::new("S-1-5-32-578")))`)
        out, err = cmd.CombinedOutput()
        if err != nil {
                log.Fatal(err)
        }
        fmt.Printf("%s", out)
}
```

And for me, it returns the expected:
```
True
True
False
```

@altwohill Could you try running the example code at let me know if you get the same result?

**Comment by spowelljr** [comment]
@altwohill I'm going to close this issue, but if you get back to this feel free to respond and I can re-open the issues, thanks!
