### ISSUE TITLE
implement minikube image rm `IMG_NAME`

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#10916]
we need to add a feature for users to easily delete an image from minikube

maybe 
```
minikube image rm IMG_NAME
```

**Comment by afbjorklund** [comment]
Or you could just use: `crictl rmi`

**Comment by afbjorklund** [comment]
We only need "minikube image" for the holes in the Container Runtime Interface.

Such as loading images (from tarball), or building images (from Dockerfile context)

**Comment by medyagh** [comment]
@afbjorklund this is a request from Skaffold, since they build tons of images on iterations on the code, they wanna be able to remove and clean up after themslves, and they dont wanna worry about what command to use Internally to minikube (docker or crictl)

**Comment by tharun208** [comment]
@medyagh , I like to work on this

**Comment by afbjorklund** [comment]
> they dont wanna worry about what command to use Internally to minikube (docker or crictl)

`crictl` isn't something internal to minikube, it's a generic kubernetes CRI command...

But sure, we can add it to the "cruntime" abstraction:

```
        // Load an image idempotently into the runtime on a host
        LoadImage(string) error
        // Remove an image from the runtime on a host
        RemoveImage(string) error
```

And implement both for Docker, and for generic CRI.

**Comment by afbjorklund** [comment]
@tharun208 : please make a PR for review

**Comment by afbjorklund** [comment]
User suggested adding "unload" as an alias (rhymes with "load")

**Comment by tharun208** [comment]
@afbjorklund sure will update the PR

**Comment by tharun208** [comment]
@afbjorklund also I am thinking to return an error to the end-user when trying to remove an image that is not present ( same behaviour for `load` command also, which not returning an error to the end-user). There is a workaround we can use `--alsologtostderr` to see what actually happened. But, need your suggestions on this.

**Comment by tharun208** [comment]
> User suggested adding "unload" as an alias (rhymes with "load")
> 
> https://github.com/spf13/viper#registering-and-using-aliases

Used cobra's `cmd.Aliases` for this
