### ISSUE TITLE
--download-only should store/load kicbase on local filesystem

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#10912]
To ensure minikube can startup in an air-gapped environment.

Related issue: #10149

**Comment by afbjorklund** [comment]
Currently it is only implemented for daemon, there is nothing in the cache - or for the other engines, such as podman

The logic today is quite weird, if we **fail** saving the image to the daemon - then we try saving it to the cache ?!?

**Comment by afbjorklund** [comment]
Another ironic thing is that in order to save it to the docker daemon, go-registry first downloads a copy to a tempfile...

**Comment by afbjorklund** [comment]
I think we discussed this feature in issue #7766, but settled for the daemon-only (docker-only) solution.

I suppose that technically `/var/lib/docker` is a local filesystem ? But I assume this issue means cache.

**Comment by afbjorklund** [comment]
@tstromberg : should this be stored under "images", along with kubernetes and addons

or should it be stored in a top-level directory, similar to "iso" (maybe something like "kic")
