### ISSUE TITLE
X Exiting due to RUNTIME_ENABLE: sudo systemctl restart docker: exit status 1 stdout:  stderr: Failed to restart docker.service: Unit docker.service is masked

### ISSUE THREAD

**Issue by anilchandana** [kubernetes/minikube#10929]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Hi there @anilchandana, could you provide more details, such which OS, and version of minikube you're using, as well as the logs `minikube start  -v=5 --alsologtostderr` outputs?

Based on the error message in the issue title, it seems to be an issue with your docker installation. Could you try 

```
sudo systemctl unmask docker
sudo systemctl start docker
```

and see if that helps?

**Comment by sharifelgamal** [comment]
Hey @anilchandana – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!

**Comment by korvalds** [comment]
After installing minikube for the first time I found this thread after getting the following error message:
```
X Exiting due to RUNTIME_ENABLE: sudo systemctl restart docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```
[](https://stackoverflow.com/a/65423698) provided a solution that worked for me:
`docker system prune` 
`minikube delete`
`minikube start --driver=docker`
