### ISSUE TITLE
Do not allow running darwin/amd64 minikube on darwin/arm64 macs

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#10928]
M1 macs allow to run amd64 in rosetta mode. We need to prohibit this, as it leads to downloading amd64 preloads, running amd64 kubeadm and SEGFAULT in the end. 

runtime.GOARCH is 'amd64' in this case, so we need an extra step to detect what we're running im emulation mode, like using`gopsutil` library, or running an external binary like `arch` or `uname`

**Comment by afbjorklund** [comment]
This can also be addressed by making it more explicit what architecture to use for the actual cluster, as suggested in #9593

**Comment by afbjorklund** [comment]
Theoretically it should be _possible_ to run an amd64 VM on an arm64 host, even thought it would be slower (emulating the CPU)

**Comment by ilya-zuyev** [comment]
> Theoretically it should be _possible_ to run an amd64 VM on an arm64 host, even though it would be slower (emulating the CPU)
> 
> I think the mentioned segfault mostly affects the Docker Preview, when running with the "docker" driver ? (haven't tried it on Linux)

Yes. This should probably be fixed in Docker release version, but right now we have a lot of segfault reports from users who running amd64 binaries in emulation mode. Seems like the easiest workaround for now is to ask them to use native binary and exit.
