### ISSUE TITLE
X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: create kic node: container name "minikube"

### ISSUE THREAD

**Issue by Yakir6** [kubernetes/minikube#10934]
\* minikube v1.18.1 on Centos 8.2.2004
\* Using the docker driver based on user configuration
! docker is currently using the fuse-overlayfs storage driver, consider switching to overlay2 for better performance
\* Starting control plane node minikube in cluster minikube
\* Creating docker container (CPUs=2, Memory=2200MB) ...
\* Stopping node "minikube"  ...
\* Deleting "minikube" in docker ...
! StartHost failed, but will try again: creating host: create: waiting: Maximum number of retries (60) exceeded
\* Creating docker container (CPUs=2, Memory=2200MB) ...
\* Failed to start docker container. Running "minikube delete" may fix it: creating host: create: creating: create kic node: container name "minikube": log: 2021-03-27T06:28:49.146040264Z  + echo 'INFO: remounting /sys read-only'
2021-03-27T06:28:49.146043527Z  INFO: remounting /sys read-only
2021-03-27T06:28:49.146045738Z  + mount -o remount,ro /sys
2021-03-27T06:28:49.174793911Z  mount: /sys: permission denied.: container exited unexpectedly

! The minikube docker container exited unexpectedly.
\* If you are still interested to make docker driver work. The following suggestions might help you get passed this issue:

	* - Prune unused docker images, volumes, networks and abandoned containers.

				docker system prune --volumes

	* - Restart your docker service

	* - Delete and recreate minikube cluster
		minikube delete
		minikube start --driver=docker

**Comment by medyagh** [comment]
@Yakir6 did you already try the minikube's suggestion ?
```
* - Prune unused docker images, volumes, networks and abandoned containers.

			docker system prune --volumes

* - Restart your docker service

* - Delete and recreate minikube cluster
	minikube delete
	minikube start --driver=docker
```

**Comment by medyagh** [comment]
Hi @Yakir6 , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
