### ISSUE TITLE
Minikube's Hyper-V Driver ignores Hyper-V Settings

### ISSUE THREAD

**Issue by SantosVictorero** [kubernetes/minikube#10940]
I was looking at: https://github.com/kubernetes/minikube/issues/5717 and I wonder why this hasn't been fixed.

What is the point of using Hyper-V if Minikube it isn't using those resources?

I have several testing profiles and they each take 5G+ in the C: drive.

I have set Hyper-V to use other drives but Minikube ignores those settings. Why?

**Comment by medyagh** [comment]
that seems like a bug

I would be happy to accept a PR that either fixes it or adds a new feature to accept alternative disk location by a flag
--hyperv-disk-location ...

@SantosVictorero would u be interested to contribute this feature ?

**Comment by SantosVictorero** [comment]
@medyagh,

Thanks for the offer to contribute towards this project. Unfortunately, we are working on a special project, which is talking up much of the time. Should our project finish sooner, I will keep this offer in mind. 

Best

**Comment by medyagh** [comment]
@SantosVictorero  sure thing ! I add help wanted label, anyone wants to contribute this feature I would happy to offer a PR review for it

**Comment by dmeyerholt** [comment]
While setting the specific disk-location maybe a reasonable flag, using the MINIKUBE_HOME env-var could solve this too, if you don't mind having all your minikube config/image/vm stuff in a different directory.

**Comment by spowelljr** [comment]
> While setting the specific disk-location maybe a reasonable flag, using the MINIKUBE_HOME env-var could solve this too, if you don't mind having all your minikube config/image/vm stuff in a different directory.

@SantosVictorero as @dmeyerholt said above, you can set the `MINIKUBE_HOME` env to `D:\path\to\dir\.minikube` and minikube will store everything in that location. I tried looking at a programmatic way to pull the default hard drive location from Hyper-V Manager but didn't see anyway to do so. If you know of a way please let me know and I could easily implement that.
