### ISSUE TITLE
Accidentally updated the docker version on Jenkins

### ISSUE THREAD

**Issue by hetong07** [kubernetes/minikube#10956]
When I am trying to update the kubectl version on jenkins to resolve related windows test failure issue, I accidentally update the docker version to the latest one. Have a short discuss with afbjorklund, and it seems k8s still does not support docker 20.10, so 19.03 maybe a safe version to downgrade to. So according to the [docker release history](https://docs.docker.com/docker-for-windows/release-notes/#docker-desktop-community-2305) it seems we should downgrade to docker desktop < 2.5.0.1? @medyagh any suggestions?

**Comment by medyagh** [comment]
no it is okay, latest docker is fine on jenkins we already have a script that installs latest docker automatically so it will always be latest
https://github.com/kubernetes/minikube/blob/master/hack/jenkins/installers/check_install_docker.sh

**Comment by hetong07** [comment]
thanks for clarification.

**Comment by afbjorklund** [comment]
The version support was when using Docker as a container runtime, not as a Minikube driver. Sorry for the confusion.

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

Also my information was outdated, Kubernetes now also supports Docker 20.10 (in the 1.21 release, that is)

https://github.com/kubernetes/system-validators/commit/13e0dde25fef584ab6cce6efabf725ff69348733
