### ISSUE TITLE
Cluster Reset automatically after suspend/resume

### ISSUE THREAD

**Issue by longwuyuan** [kubernetes/minikube#10965]
**Steps to reproduce the issue:** 
Ubuntu focal LTS amd64 on Thinkpad with VirtualBox Driver auto chosen

1. minikube start --container-runtime=containerd --memory 7000m --disk-size 40g --extra-config=kubelet.authentication-token-webhook=true --extra-config=kubelet.authorization-mode=Webhook --extra-config=scheduler.address=0.0.0.0 --extra-config=controller-manager.address=0.0.0.0

2. Install metallb, ingress-nginx, vault, linkerd as per respective docs and deploy a "helloworld" of python/js/whatever
3. Close Laptop Lid with suspend configured as action on lid close. 
4. Reopen Laptop lid after a few minutes to resume from suspend 
5. Minikube status will freeze for long
6. Run "minikube stop"
7. Repeat step1 above
8. Cluster will get reset

**Full output of failed command:** 

 minikube v1.18.1 on Linuxmint 20.1                                                           
    ▪ KUBECONFIG=/home/user/.kube/config
✨  Using the virtualbox driver based on existing profile                                        
👍  Starting control plane node minikube in cluster minikube                                     
🔄  Restarting existing virtualbox VM for "minikube" ...                                         
📦  Preparing Kubernetes v1.20.2 on containerd 1.4.3 ...                                         
    ▪ kubelet.authentication-token-webhook=true                                                  
    ▪ kubelet.authorization-mode=Webhook                                                         
    ▪ scheduler.address=0.0.0.0                                                                  
    ▪ controller-manager.address=0.0.0.0                                                         
🔗  Configuring bridge CNI (Container Networking Interface) ...                                  
🤦  Unable to restart cluster, will reset it: addons: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml": Process exi
ted with status 1                                  
stdout:                                            stderr:                                            
error execution phase addon/coredns: unable to create a new DNS service: Post "https://control-plane.minikube.internal:8443/api/v1/namespaces/kube-system/services?timeout=10s": net/http: request canceled (
Client.Timeout exceeded while awaiting headers)    
To see the stack trace of this error execute with --v=5 or higher                                         ▪ Generating certificates and keys ...         
    ▪ Booting up control plane ...                 
    ▪ Configuring RBAC rules ...                   
🔗  Configuring bridge CNI (Container Networking Interface) ...                                       
🔎  Verifying Kubernetes components...             
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v4                                          
🌟  Enabled addons: storage-provisioner, default-storageclass                                         
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default   

**Optional: Full output of `minikube logs` command:**
There is much going on so not asking for anything but had a chat with @afbjorklund and feel that losing all the workload and previously installed stuff without consent could use a prompt at least before the cluster reset

**Comment by medyagh** [comment]
@longwuyuan  it is expected to get a reset after a "minikube stop" since the IP of the VM might have changed (in some drivers static IP is not supported)

is there a reason that the cluster reset conflicts with your workflow ?

**Comment by longwuyuan** [comment]
thank you @medyagh . The reset occured on reopening laptop lid so suspend resume.
The reset basically removed all my namespaces, resources etc. and I was handed a pristine cluster.
But unable to reproduce with 1.19.0 so will close issue.
Thanks tons again
