### ISSUE TITLE
Using Multi-Node Clusters

### ISSUE THREAD

**Issue by TaoPanfeng** [kubernetes/minikube#10969]
# why I no display **hello**  URL ： `http://xxx:31000`

<https://minikube.sigs.k8s.io/docs/tutorials/multi_node/>

```
------------minikube service list -p multinode-demo
|-------------|------------|--------------|-----|
|  NAMESPACE  |    NAME    | TARGET PORT  | URL |
|-------------|------------|--------------|-----|
| default     | hello      |           80 |     |
| default     | kubernetes | No node port |
| kube-system | kube-dns   | No node port |
|-------------|------------|--------------|-----|
```

**Comment by sharifelgamal** [comment]
Could I get more details about what you tried? 

* The version of minikube and OS you're using

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A
