### ISSUE TITLE
podman support on macos in Minikube 

### ISSUE THREAD

**Issue by claywd-x** [kubernetes/minikube#10980]
I don't know or immediately recognize the impediments to using podman as the container engine on MacOs so I was curious if it's already on the roadmap somewhere or if there is already an effort to support it. 

Note*
Current documentation does explain linux is required and the driver is experimental but I don't know if the predefined flow is to bring features to linux first and MacOs/Windows later

Links
- https://minikube.sigs.k8s.io/docs/drivers/podman/

**Comment by claywd-x** [comment]
ah, podman doesn't technically interface with runc on MacOs. They use a VM. Got it.

**Comment by afbjorklund** [comment]
@claywd-x : it is in the backlog, but it's not really a priority at the moment: #8003

The previous podman-machine has been deprecated (and doesn't support podman2),
and the new podman machine has not yet been released - maybe for podman4 or so ?

Like you say, both Docker and Podman do require a VM when running on Mac or Win.

The main difference is whether you as a user see this VM - or if it is "hidden away".
Not having access to the VM does cause some issues, with for instance networking.

**Comment by afbjorklund** [comment]
Also, the container runtime (for k8s) is called "cri-o" but the engine is called "podman".
