### ISSUE TITLE
X Exiting due to GUEST_START: Failed to setup kubeconfig: Error getting VM/Host IP address: connection is shut down

### ISSUE THREAD

**Issue by maksym1hladkykh** [kubernetes/minikube#10981]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by ilya-zuyev** [comment]
@maksym1hladkykh thanks for reporting! please provide some details about your system, and output of `minikube start --v=5 --alsologtostderr'

**Comment by ilya-zuyev** [comment]
Going to close this issue. If the problem still exists please feel free to reopen it
