### ISSUE TITLE
Feature request: multiplatform hosts manager as minikube addon

### ISSUE THREAD

**Issue by lukasmrtvy** [kubernetes/minikube#10994]
Would be nice to implement support for something like https://github.com/guumaster/hostctl as minikube addon ( https://github.com/guumaster/hostctl/pull/66 ). It has few bugs and seems to be unmaintained, but there is Linux, Windows, MacOS  support and it might eventually work.

Another related tools that I found:
https://github.com/cbednarski/hostess
https://gitlab.com/dbohdan/hosts

These things needs to be fixed:
- https://github.com/guumaster/hostctl/issues/72
- https://github.com/guumaster/hostctl/issues/71

Thanks

**Comment by spowelljr** [comment]
Thanks for creating this issue!

The project does in-fact seem to be dormant, but if those issues are fixed feel be sure to keep us updated, thanks.

**Comment by guumaster** [comment]
Thanks for proposing `hostctl` as a `minikube` addon. As you can see, both issues guumaster/hostctl#71 guumaster/hostctl#72 are now fixed and `hostctl` is now idempotent and can also be added with comments. (NOTE: guumaster/hostctl#66 is not a path that I'd consider exploring further)
