### ISSUE TITLE
upgrade spinner library fork: fix spin.Stop() output

### ISSUE THREAD

**Issue by prezha** [kubernetes/minikube#11002]
as seen in the logs:

```
...
I0406 11:28:47.270311   15077 start.go:126] createHost starting for "" (driver="kvm2")
I0406 11:28:47.282841   15077 out.go:184] 🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...| I0406 11:28:47.283045   15077 main.go:126] libmachine: Found binary path at /home/prezha/bin/k8s/docker-machine-driver-kvm2
I0406 11:28:47.283109   15077 main.go:126] libmachine: Launching plugin server for driver kvm2
...
```
there's a newline missing at the end of the `🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB)`

@alonyb i guess `fmt.Print("\n")` should be changed to `fmt.Printf("\n")` in your `github.com/alonyb/spinner@v1.12.7` fork of `github.com/briandowns/spinner`:

https://github.com/alonyb/spinner/blob/7607d83ff2c82094402aa67046905d4c765869ad/spinner.go#L342

minikube `go.mod`:
```
replace (
...
	github.com/briandowns/spinner => github.com/alonyb/spinner v1.12.7
...
```

(not sure if that's all it takes to fix it)

thanks!

**Comment by prezha** [comment]
just thinking out loud: actually, this might not fix the issue of the appended log line - 
since the operation of creating a vm takes some time, another process (with libmachine in this case) could echo the output to the same std out line before creation is completed...

please just check if you would still want to change fmt.Print to fmt.Printf, if that was the intention

**Comment by alonyb** [comment]
hey @prezha thanks for the observation, I will check it :)

**Comment by sharifelgamal** [comment]
Is this still something that needs fixing?
