### ISSUE TITLE
minikube kubectl has broken option parsing

### ISSUE THREAD

**Issue by jameswilsongrant** [kubernetes/minikube#11009]
**Steps to reproduce the issue:** 

1. fresh minikube installation on 1.18.1 or 1.19.0-beta0 using docker-ce and ubuntu 20.04
2. minikube kubectl create deployment nginx --image=nginx
Error: unknown flag: --image
See 'minikube kubectl --help' for usage.

3. Try the same command with two dashes after kubectl
minikube kubectl -- create deployment nginx --image=nginx
deployment.apps/nginx created

<details>
My understanding is that some versions of kubectl had an upstream library problem with the option parser that was causing this.

Full output:
```
user@user:~$ minikube kubectl create deployment nginx --image=nginx
Error: unknown flag: --image
See 'minikube kubectl --help' for usage.
user@user:~$ minikube kubectl -- create deployment nginx --image=nginx
deployment.apps/nginx created
user@user:~$ minikube kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

Strangely enough, using what is supposedly the same version of kubectl directly works. Copying this version on top of the one that gets dumped into .minikube does not work. 

```
user@user:~$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
user@user:~$ kubectl delete deployment nginx
deployment.apps "nginx" deleted
user@user:~$ kubectl create deployment nginx --image=nginx
deployment.apps/nginx created
user@user:~$
```

</details>

**Comment by afbjorklund** [comment]
What is the issue ? Minikube requires that extra --, both for "minikube ssh --" and "minikube kubectl --".

There were some bugs when it came to symlinking kubectl to minikube, but those should be fixed now.

**Comment by jameswilsongrant** [comment]
This is my mistake. I must have mixed up my kubectl docs.

What you’re describing is clearly shown in the getting started
documentation. This is closable.
