### ISSUE TITLE
Feature Request: Resource usage

### ISSUE THREAD

**Issue by justechn** [kubernetes/minikube#1100]
Is there a way to check resource usage? I have been tracking down a crashing bug for a couple days now and and after days of searching I think it is because I am running out of disk space on my minikube VM. It would be great if Minikube/Kubernetes could warn about resources when they are getting low, or provide some kind of report that would show what current resource usage is.

Thanks

**Comment by bjoernstuetztss** [comment]
Hi there, did you try using the minikube addon `heapster` together with the `dashboard` [[1]](https://github.com/kubernetes/minikube#add-ons)? I think the features you are after are available already.
In regard to your specific question, you might find `kubectl describe node | grep disk` useful. You might find some background information in the kube docs [[2]](https://kubernetes.io/docs/admin/out-of-resource/).
 [[1]](https://github.com/kubernetes/minikube#add-ons) https://github.com/kubernetes/minikube#add-ons
[[2]](https://kubernetes.io/docs/admin/out-of-resource/) https://kubernetes.io/docs/admin/out-of-resource/

**Comment by justechn** [comment]
Thanks, I enabled the addon. It shows CPU and Memory usage, but not disk usage. The other command is useful, I will just have to remember to run it occasionally.

**Comment by bjoernstuetztss** [comment]
Have a look at the node, i.e., Admin > Nodes > Conditions.
`OutOfDisk False 3 seconds 7 minutes KubeletHasSufficientDisk kubelet has sufficient disk space available`
...
