### ISSUE TITLE
do I need to Downgrade Minikube version for old kuberentes versions ?

### ISSUE THREAD

**Issue by imoisharma** [kubernetes/minikube#11020]
Hi there,

I am running my application for Minikube version 1.18.1, but now I want to downgrade the minikube v 1.15.1 to make it compatible with other services. Could you provide me a way to downgrade the minikube. 

I can't see it in the documentation.

I am using Ubuntu 20.04 LTS | 32GB | x86_64 Arch

**Comment by imoisharma** [comment]
Till far what I figure out, I've to run minikube delete and purge all the files and download and install again minikube v 1.5.1.

Can't we do it via CLI directly rather than performing all the steps?

**Comment by afbjorklund** [comment]
You should be able to start clusters with older kubernetes versions, without having to downgrade minikube itself.

See `--kubernetes-version`

**Comment by imoisharma** [comment]
How would you provide more details on this?

**Comment by afbjorklund** [comment]
It's a parameter to the "minikube start" command, I think `kubeadm` supports minor upgrades:

https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/

> .. upgrade a Kubernetes cluster created with kubeadm from version 1.19.x to version 1.20.x, and from version 1.20.x to 1.20.y (where y > x). Skipping MINOR versions when upgrading is unsupported.

So you could not go directly from 1.20 down to 1.15, and downgrading is less supported as well.

But the usual approach minikube is to delete the cluster and start a new (or second) one...

You can use two different profiles for this, like "old" (with 1.15) and "new" (with 1.20)

**Comment by imoisharma** [comment]
I'll look into it and come back but the kubeadm link is only upgrade not for degrade.

**Comment by medyagh** [comment]
@imoisharma 

minikube versions and kubernetes versions are not same thing,  you could start an older kuberentes version with New versions of minikube

so you could do 
```
minikube start --kuberentes-version=v1.15.0 
```
with latest minikube ! 

I recommend using using the lastest minikube version since has most bugs fixed. only specify the kuberenetes version

**Comment by imoisharma** [comment]
Hi @medyagh, I tried this same command for two different profiles for minikube, however, I ran into issues, only when I try to run for the second profile. My current applications are only supported with v1.15 until my developers upgrade the application which is compatible with the new version of minikube.

**Comment by imoisharma** [comment]
https://github.com/kubernetes/minikube/issues/11090 (issue link)

**Comment by medyagh** [comment]
closing this one in favor of https://github.com/kubernetes/minikube/issues/11090
