### ISSUE TITLE
minikube kubectl proxy - address flag unkown

### ISSUE THREAD

**Issue by mwiora** [kubernetes/minikube#11035]
```
# minikube version
minikube version: v1.18.1
commit: 09ee84d530de4a92f00f1c5dbc34cead092b95bc
```
I was trying to run the minikube dashboard by executing:
```
minikube dashboard -url
```
and to change the listener IP to 0.0.0.0
```
minikube kubectl proxy --address='0.0.0.0' --accept-hosts='.*'
```

unfortunately the kubectl proxy command is failing with:
```
Error: unknown flag: --address
See 'minikube kubectl --help' for usage.
```
while the documentation says:
```
# minikube kubectl proxy -- --help
...
Options:
      --accept-hosts='^localhost$,^127\.0\.0\.1$,^\[::1\]$': Regular expression for hosts that the proxy should accept.
      --accept-paths='^.*': Regular expression for paths that the proxy should accept.
      --address='127.0.0.1': The IP address on which to serve on.
      --api-prefix='/': Prefix to serve the proxied API under.
      --disable-filter=false: If true, disable request filtering in the proxy. This is dangerous, and can leave you
```
so the option should be available...
did I miss somthing?

**Comment by afbjorklund** [comment]
You need to use the same `minikube kubectl -- proxy` when running the command, as with the help.

Otherwise the options will be for `minikube kubectl`, which doesn't have to so many:

```console
$ minikube kubectl --help
Run the Kubernetes client, download it if necessary. Remember -- after kubectl!

Examples:
minikube kubectl -- --help
minikube kubectl -- get pods --namespace kube-system

Usage:
  minikube kubectl [flags] [options]

Use "minikube options" for a list of global command-line options (applies to all
commands).

```

**Comment by afbjorklund** [comment]
You probably want to set up a shell alias or a symlink, alternatively install `kubectl` with your package manager:

https://minikube.sigs.k8s.io/docs/handbook/kubectl/

https://kubernetes.io/docs/tasks/tools/#kubectl

**Comment by mwiora** [comment]
oh - nice - thanks to both of you!
Maybe it would be an idea to show up a hint regarding this double dash speciality with minikube kubectl commands - meanwhile I will close this issue :)
