### ISSUE TITLE
Persistent volumes created using default storage class not persisted across restart

### ISSUE THREAD

**Issue by twelvelabs** [kubernetes/minikube#1103]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Minikube version** (use `minikube version`):

`minikube version: v0.16.0`

**Environment**:

- **OS** (e.g. from /etc/os-release): OS X 10.12.3
- **VM Driver**: virtualbox
- **ISO version**: minikube-v1.0.6.iso
- **Install tools**: installed via homebrew

**What happened**:

I installed the `stable/mysql` helm chart via:

```bash
$ brew install kubernetes-helm
$ helm init
# wait for tiller to start up
$ helm install stable/mysql
```

The mysql chart has a `PersistentVolumeClaim` that [uses the default dynamic storage provisioner](https://github.com/kubernetes/charts/blob/f9ce327b86f1fac812f3013aa024e8c41fb802c6/stable/mysql/templates/pvc.yaml#L15). Kubernetes automatically provisioned a `PersistentVolume` at `/tmp/hostpath_pv/...` and bound it to the claim:

```bash
$ kubectl describe pv,pvc

Name:		pvc-a3b23e9b-ed6e-11e6-88f2-080027577d50
Labels:		<none>
StorageClass:	
Status:		Bound
Claim:		default/exiled-manta-mysql
Reclaim Policy:	Delete
Access Modes:	RWO
Capacity:	8Gi
Message:	
Source:
    Type:	HostPath (bare host directory volume)
    Path:	/tmp/hostpath_pv/a3de1646-ed6e-11e6-88f2-080027577d50
No events.


Name:		exiled-manta-mysql
Namespace:	default
StorageClass:	default
Status:		Bound
Volume:		pvc-a3b23e9b-ed6e-11e6-88f2-080027577d50
Labels:		app=exiled-manta-mysql
		chart=mysql-0.2.4
		heritage=Tiller
		release=exiled-manta
Capacity:	8Gi
Access Modes:	RWO
No events.
```

From my understanding of https://github.com/kubernetes/minikube#persistent-volumes, `/tmp` is not one of the directories persisted across restart.

**What you expected to happen**:

I expected the dynamically provisioned persistent volume to be... well... `persistent` 😄. Either created in `/data` or some other non-tmpfs directory.

**How to reproduce it** (as minimally and precisely as possible):

Repro steps are above. Note that helm is not required: any `PersistentVolumeClaim` that makes use of dynamic provisioning should reproduce this, too.

**Comment by dlorenc** [comment]
Yeah we should fix this. I'm not sure if that directory is configurable, but we should figure something out.

A current workaround is to create your own PV with hostpath in a persisted directory so the claim will use that.

**Comment by dlorenc** [comment]
Looks like the directory is hardcoded here: https://github.com/kubernetes/kubernetes/blob/master/pkg/volume/host_path/host_path.go#L275

We could mount /tmp/hostpath_pv persistently.

**Comment by tvon** [comment]
In addition to persistence issues, `/tmp/hostpath_pv` does not have much space compared to what might be requested.
