### ISSUE TITLE
calico: apiextensions.k8s.io/v1beta1 is deprecated in v1.16+, unavailable in v1.22+

### ISSUE THREAD

**Issue by prezha** [kubernetes/minikube#11032]
as seen in logs - example:
https://storage.googleapis.com/minikube-builds/logs/11006/74537ca/Docker_Linux_containerd.html#fail_TestAddons
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Comment by sharifelgamal** [comment]
this should be as simple as changing the appropriate yaml files

**Comment by spowelljr** [comment]
This has been resolved
