### ISSUE TITLE
Process exited with status 139 from signal SEGV

### ISSUE THREAD

**Issue by ncksp** [kubernetes/minikube#11034]
**Steps to reproduce the issue:** 

1. ./minikube-darwin-amd64 start

**Full output of failed command:** ./minikube-darwin-amd64 start

**Optional: Full output of `minikube logs` command:**
<details>
❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
stdout:

stderr:
SIGSEGV: segmentation violation
PC=0x0 m=0 sigcode=0

goroutine 1 [running]:
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
</details>

**Comment by afbjorklund** [comment]
Most likely this is a known issue with Docker Preview on Apple M1

#10243

**Comment by ncksp** [comment]
> Most likely this is a known issue with Docker Preview on Apple M1
> 
> #10243
> 
> If you are on arm64, you should be using "minikube-darwin-arm64"

I was start the minikube using command: 
./minikube-darwin-amd64 start

And I also not running minikube using docker preview. Fyi, minikube with docker on M1 is running well

**Comment by ilya-zuyev** [comment]
@ncksp anyway, native (`minikube-darwin-arm64`) version is a bit faster and way more stable on M1. Please use it.

**Comment by ncksp** [comment]
@ilya-zuyev I already use it, and when I start the minikube using command "./minikube-darwin-amd64 start" the error will showing like above

**Comment by medyagh** [comment]
@ncksp since minikube v1.19.0 we do not support running X86 Binary on M1, please use the Arm Binary

**Comment by sharifelgamal** [comment]
Closing this as a dupe of #10243
