### ISSUE TITLE
Exiting due to HOST_KUBECTL_PROXY: readByteWithTimeout: EOF

### ISSUE THREAD

**Issue by luisvelalopez** [kubernetes/minikube#11045]
**Los comandos necesarios para reproducir la incidencia**:
`minikube dashboards`

**El resultado completo del comando que ha fallado**: <details>
🔌  Enabling dashboard ...
    ▪ Using image kubernetesui/dashboard:v2.1.0
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
🤔  Verifying dashboard health ...
🚀  Launching proxy ...

❌  Exiting due to HOST_KUBECTL_PROXY: readByteWithTimeout: EOF

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:
Operating System: Ubuntu 20.04.2 LTS

**Comment by spowelljr** [comment]
@luisvelalopez Thanks for reporting your issue! Could you please re-run `minikube dashboards` with the `--alsologtostderr` flag to get more details logs and then report back with the new logs.

-----

@luisvelalopez ¡Gracias por informar tu problema! ¿Podrías volver a ejecutar `minikube dashboards` con la marca` --alsologtostderr` para obtener registros más detallados y luego informar con los nuevos registros?

**Comment by medyagh** [comment]
@luisvelalopez what version of minikube do you use ?
do you mind sharing

`minikube logs`

**Comment by spowelljr** [comment]
Going to close this issue in favor of #11380. Please follow along there for updates, thanks!

-----

Va a cerrar este tema a favor del #11380. Siga allí para recibir actualizaciones, ¡gracias!
