### ISSUE TITLE
Alternative Buildroot 2021.02 image, using Linux version 5

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11056]
The current 2020.02 LTS series are now end of life, we should upgrade to 2021.02 LTS if we want to keep it.

While doing so, we should make yet another attempt at upgrading from Linux version 4 to Linux version 5...

```
# From https://www.kernel.org/pub/linux/kernel/v5.x/sha256sums.asc
sha256  930ae76b9a3b64b98802849aca332d17a706f20595de21e1ae729b55ee461add  linux-5.10.25.tar.xz
sha256  1c3cef545f366b56332c11c28d074c9d9148c28059a970ec8710826652237560  linux-5.4.107.tar.xz
# From https://www.kernel.org/pub/linux/kernel/v4.x/sha256sums.asc
sha256  05db750ba01ad557bef50835c253894fad9fb0db2224f0e803b25e2ff7ab2365  linux-4.19.182.tar.xz
sha256  7adc041af81424ff8d68affe3005fa9e5babc4e84e0b07e4effdf54225ba9426  linux-4.14.226.tar.xz
```

This relates to #9992 and #10501

**Comment by afbjorklund** [comment]
With the amount of leftovers still todo, this will probably not make it this month.

**Comment by medyagh** [comment]
I agree on doing this, but priority wise donest need to be high prirority. I think this will help with cgroup v2 one thing to consider is doesnt break cgroup v1

**Comment by afbjorklund** [comment]
Could always upgrade the userspace and leave the kernel, but we already did that once.

**Comment by afbjorklund** [comment]
Added the userspace upgrade as part of #11652, we don't expect it to break much

**Comment by afbjorklund** [comment]
Supposedly next LTS will be something like 5.16, and end up in Ubuntu 22.04 LTS etc.

**Comment by afbjorklund** [comment]
Sadly 2021.02 also went end-of-life, before the kernel bump happened. But it _needs_ to be done, for 2022.02.

**Comment by afbjorklund** [comment]
The minikube ISO is now using Linux 5.10 (for 2021.02), so this is completed.

```
BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="5.10.57"
```

https://github.com/buildroot/buildroot/blob/2021.02.x/linux/linux.hash (EOL)

```
sha256  c467c3077946370fb26c9277313b601d6c48bb557abc889f4892caf627fcdfea  linux-5.10.107.tar.xz
```
