### ISSUE TITLE
multiple /etc/hosts entries created for control-plane.minikube.internal

### ISSUE THREAD

**Issue by EdVinyard** [kubernetes/minikube#11052]
**Steps to reproduce the issue:** 

I've tried this on both Mac OS using the hyperkit driver and Ubuntu 18.04 using the "none" driver.

1. start Minikube
2. switch to a different network
3. start Minikube

Multiple `/etc/hosts` files entries are created for _control-plane.minikube.internal_.  After using the "none" driver for some time, `/etc/hosts` has accumulated quite a few entries for me.

**Full output of failed command:** 
```bash
$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	myhostname

# The following lines are desirable for IPv6 capable hosts
::1     ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
127.0.0.1	host.minikube.internal
192.168.50.139	control-plane.minikube.internal
10.8.0.22	control-plane.minikube.internal
... many more ...
10.8.0.26	control-plane.minikube.internal
192.168.50.117	control-plane.minikube.internal
10.8.0.5	control-plane.minikube.internal
```

<details>
My colleague @iguanito and I noticed this today while trying to understand why his Minikube was failing to start when he moves from one network to another.  We don't know if this is the whole reason, but it certainly doesn't seem to be the author's intent.

We _think_ this is due to a tiny error at [machine/start.go:362](https://github.com/kubernetes/minikube/blob/15cede53bdc5fe242228853e737333b09d4336b5/pkg/minikube/machine/start.go#L362)
```
script := fmt.Sprintf(`{ grep -v '\t%s$' /etc/hosts; echo "%s"; } > /tmp/h.$$; sudo cp /tmp/h.$$ /etc/hosts`, name, record)
```

As written, the `grep` expression never matches anything because the `\t` is ignored, so a new line is appended to the file every time.  [There are several ways to fix it](https://askubuntu.com/a/53096/398512), but I was successful adding a `$` before of the expression to enable [BASH ANSI-C quoting](https://www.gnu.org/software/bash/manual/html_node/ANSI_002dC-Quoting.html#ANSI_002dC-Quoting):

```
script := fmt.Sprintf(`{ grep -v $'\t%s$' /etc/hosts; echo "%s"; } > /tmp/h.$$; sudo cp /tmp/h.$$ /etc/hosts`, name, record)
```
</details>

If there's a better place for this discussion, or I can help with the fix (I have a rough test and fix locally), just point me in the right direction.

**Comment by afbjorklund** [comment]
Sounds like a simple fix, the script is hardcoded to use `/bin/bash` anyway so no need to worry about portability.

Can you do a PR ?

**Comment by EdVinyard** [comment]
I've opened https://github.com/kubernetes/minikube/pull/11081, and I'm working on the contributor agreement.

**Comment by sharifelgamal** [comment]
This seems to be fixed now, correct? I'll go ahead and close this issue. If something comes up, feel free to reopen.
