### ISSUE TITLE
Remove docker assumptions from minikube installation

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11059]
Now that Docker is deprecated in Kubernetes (after 1.20), it should be the same in minikube.

Unfortunately this issue is not addressed upstream, and makes misleading statements:

https://kubernetes.io/blog/2020/12/02/dont-panic-kubernetes-and-docker/

> [...] We’re talking about two different environments here, and that’s creating confusion. [...] 

> [...] the Docker installation you’re using in development is unrelated to the Docker runtime inside your Kubernetes cluster. [...] 

In minikube, these so called "two environments" are one and the same.

We should aim for using CRI for the runtime operations, and to use CNI for the networking

We should stop using `docker-env` etc, and instead use the `minikube image` abstractions.

`docker image load` => `minikube image load`

`docker image build` => `minikube image build`

The minikube user does **not** need to have a local Docker client installation, when using a VM.

----

Images should be called "container images", and be fully qualified (including "docker.io" where needed) (#11126)

The code base should **not** assume that there is a local Docker daemon running, to be queried (#8577)

Stop using libmachine legacy, and allow for choosing a different runtime when provisioning the machine. (#10883)

**It is still perfectly legit to default to the "docker" driver, and to the "docker" container runtime (with cri-dockerd)**

Other drivers such as "podman", need to first prove that they are a viable alternative before default is changed.

    --driver=docker
    --driver=podman

Same goes for the "containerd" container runtime, it could need some better integration (especially buildkitd)

    --container-runtime=docker
    --container-runtime=containerd

**Comment by afbjorklund** [comment]
The dockershim will be removed in Kubernetes 1.22: https://kubernetes.io/blog/2020/12/02/dockershim-faq/

This means that for the newer versions, we need to install and start `cri-dockerd` to provide the CRI socket.

**Comment by medyagh** [comment]
how about intergration test in GH Action without any Docker at all to ensure minikube can run without any docker at all...
