### ISSUE TITLE
VM starts but the download of `preloaded-images-k8s` was not completed

### ISSUE THREAD

**Issue by Pictor13** [kubernetes/minikube#11061]
*(This is not a regular issue, but a support request)*

**Steps to reproduce the issue:** 
```
minikube start
minikube delete
minikube start
```
>😄  minikube v1.19.0 on Darwin 10.14.6
>    ▪ MINIKUBE_ACTIVE_DOCKERD=minikube
>✨  Using the virtualbox driver based on user configuration
>👍  Starting control plane node minikube in cluster minikube
>💾  Downloading Kubernetes v1.20.2 preload ...
>    \> preloaded-images-k8s-v10-v1...: 308.70 MiB / 491.71 MiB  62.78% 84.05 KiB
>🔥  Creating virtualbox VM (CPUs=3, Memory=5120MB, Disk=20000MB) ...
> ...

### Questions:

* Does Minikube has any way to *avoid re-downloading the `preloaded-images-k8s`, every time* that a VM is created?
* Where does Minikube stores the `preloaded-images-k8s`?\
So I can manually *copy it* before `delete` and *restore it* before `start`.

I am having connectivity problems and I would like to **reuse the images that were already downloaded on the first execution of `minikube start`**, when re-creating the Virtual Machine.

Is there **any** way to achieve this?

**Comment by afbjorklund** [comment]
The preloaded images are _supposed_ to be downloaded once, and kept in the cache (between delete and start)

**Comment by afbjorklund** [comment]
It would have to be copied to the VM, and unpacked again, but the actual download (.tar.lz4) should be saved.

**Comment by Pictor13** [comment]
Great infos, thank you.

----
 I tried to `minikube delete` plus  `rm -fr ~/.minikube/cache/preloaded-tarball` and `minikube start` again, to have a clear example to reproduce the issue; but **now it reloads** correctly.

I guess *macOS* went to sleep mode while downloading, and that confused Minikube.
See the output in my first post:\
VM creation started after downloading **only 62% of the tarball**.
Supposedly, waking from sleep made Minikube think it completed the download, and provoked some weird state, that it wasn't able to clear with the following `minikube delete`/`minikube start`.

Clearing the tarball cache with `rm -fr ~/.minikube/cache/preloaded-tarball` seems to have helped.

I'll try to reproduce the case.

**Comment by Pictor13** [comment]
OK, I was able to reproduce the bug once more.\

### Output of `minikube start`
> 😄  minikube v1.19.0 on Darwin 10.14.6
> ✨  Using the virtualbox driver based on user configuration
> 👍  Starting control plane node minikube in cluster minikube
> 💾  Downloading Kubernetes v1.20.2 preload ...
>     > preloaded-images-k8s-v10-v1...: 395.46 MiB / 491.71 MiB  80.43% 959.40 Ki
> 🔥  Creating virtualbox VM (CPUs=3, Memory=5120MB, Disk=20000MB) ...|

### Steps to reproduce

* `minikube start` and wait for the preloaded images download to start
* turn your system WiFi *off*, to simulate the loss of connectivity (what probably happened to me)
* wait the download speed to degrade until `0 B p/s` (or maybe until some internal timeout is triggered; I didn't verify in the source-code)
* put macOS on *sleep* for a while (1 minute?); then *wake up*
* quickly turn your system WiFi *on* again (*before* Minikube see that there's no connectivity)
* notice how now Minikube proceeds to the next step of creation (or update) of the VM, thinking that the download was completed:
> 🔥  Creating virtualbox VM (CPUs=3, Memory=5120MB, Disk=20000MB) ...\
or\
> 🏃  Updating the running virtualbox "minikube" VM ...

It might not do that at the first attempt, but I was able to reproduce it 2-3 times following these steps. Connection timeouts might also play a role.

### Temporary workaround to the bug:

My suggestion is to kill the `minikube start` process and re-run it.\
Or eventually to `rm -fr ~/.minikube/cache/preloaded-tarball` before starting minikube (in case you have enough bandwidth and can afford to loose the cached parts of the tarball).

**Comment by afbjorklund** [comment]
There is a checksum on the download, that should prevent this (partial downloads) from happening.

Probably we should **not** rename the temporary file, until the checksum has been verified first.

```go
        if err := download(url, targetPath); err != nil {
                return errors.Wrapf(err, "download failed: %s", url)
        }

        if err := saveChecksumFile(k8sVersion, containerRuntime); err != nil {
                return errors.Wrap(err, "saving checksum file")
        }

        if err := verifyChecksum(k8sVersion, containerRuntime, targetPath); err != nil {
                return errors.Wrap(err, "verify")
        }
```

So the "tmpDst" should be moved, from download and out to the main function (the caller)

        tmpDst := dst + ".download"

        return os.Rename(tmpDst, dst)
