### ISSUE TITLE
minikube not working

### ISSUE THREAD

**Issue by cahityusuf** [kubernetes/minikube#11083]
minikube start --alsologtostderr -v=8  ===>

 * Failed to start docker container. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Cahit Yusuf KAFADAR\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Failed to start docker container. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Cahit Yusuf KAFADAR\.minikube\machines\minikube\config.json: The system cannot find the file specified.
I0412 22:28:44.390851    8040 out.go:157]

W0412 22:28:44.393012    8040 out.go:222] X Exiting due to GUEST_PROVISION: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Cahit Yusuf KAFADAR\.minikube\machines\minikube\config.json: The system cannot find the file specified.
X Exiting due to GUEST_PROVISION: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Cahit Yusuf KAFADAR\.minikube\machines\minikube\config.json: The system cannot find the file specified
W0412 22:28:44.398390    8040 out.go:222] *
*
W0412 22:28:44.399390    8040 out.go:222] * If the above advice does not help, please let us know:
* If the above advice does not help, please let us know:
W0412 22:28:44.400784    8040 out.go:222]   https://github.com/kubernetes/minikube/issues/new/choose
  https://github.com/kubernetes/minikube/issues/new/choose
I0412 22:28:44.407478    8040 out.go:157]

minikube delete --all ====> 

* Deleting "minikube" in docker ...
* Removing C:\Users\Cahit Yusuf KAFADAR\.minikube\machines\minikube ...

X Exiting due to GUEST_PROFILE_DELETION: CreateFile C:\Users\Cahit Yusuf miniKAFADAR\.minikube\machines\minikube\minikube\Snapshots: access denied.

minikube status ====>

E0412 22:31:53.852460    7644 status.go:257] status error: host: load: filestore "minikube": open C:\Users\Cahit Yusuf KAFADAR\.minikube\machines\minikube\config.json: Sistem belirtilen dosyayı bulamıyor.
E0412 22:31:53.853014    7644 status.go:260] The "minikube" host does not exist!
minikube
type: Control Plane
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent

minikube version  ====>

minikube version: v1.19.0
commit: 15cede53bdc5fe242228853e737333b09d4336b5

can you please help to run minikube.

*
* If the above advice does not help, please let us know:
  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by cahityusuf** [comment]
**problem solved**

1-docker uninstall
2-minikube delete
3-docker install (Docker Desktop)
4-minikube start --driver=hyperv (Windows 10)
5-minikube status ----->

type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

**Comment by spowelljr** [comment]
@cahityusuf Glad you were able to solve your issue! I will close this issue, but if the issue returns feel free to reopen it.
