### ISSUE TITLE
Not working --kubernetes-version for Minikube upgrade | Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by imoisharma** [kubernetes/minikube#11090]
Hi there, I am trying to install the minikube version 1.19.0 in my second profile, but it's not working.
![image](https://user-images.githubusercontent.com/30807347/114503489-bca2fb00-9c70-11eb-89a2-c80698a25049.png)

In my pc, I have already default minikube with v1.15.1 but now to run some Jenkins jobs I require minikube with the above v1.17. 
So, I am trying to create a new profile and using the start command as per the documentation with providing `--kubernetes-version` tag for providing the version, I wanna download. 

Could you please provide me why it's not working, it's just getting stuck after pre-loading images k8s (see the screenshot)

About my laptop details:
i7, Ubuntu 20.04 LTS ( uname details -> Linux ubuntu 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux)  | 32GB | 8 Cores

Default minikube I am running v1.15 | KVM2 is my VM.

**Comment by spowelljr** [comment]
@imoisharma Thanks for reporting your issue. There seems to be a little confusion here.

If you want to upgrade to the minikube v1.19.0 you can download it here: https://github.com/kubernetes/minikube/releases

minikube and Kubernetes versions are two different things.

As per your issue starting minikube v1.15.1 with Kubernetes version v1.19.0, please re-run the start command with the `--alsologtostderr` flag to produce more detailed logs and provide them in this issue.

**Comment by imoisharma** [comment]
Hi @spowelljr, thanks for replying.

**Requirement**: I need to install two different minikube versions on my Ubuntu 20.04 LTS. One is `minikube 1.15` and another one is `minikube 1.19`. 
I need to know, is there a way to run create two profile
1. default which always refers to `minikube 1.15` 
2. another one refers to `minikube 1.19` when I specified via [profile tag](https://minikube.sigs.k8s.io/docs/commands/profile/)

Issue:  I am not able to install two different versions of minikube on my local ubuntu pc and as it got stuck after downloading the pre-load image as shown above.

Q: How do I run two different minikube versions of minikube on my local PC? And, is there any way to configure this via CLI?

Looking forward to hearing from you soon.

Best Regards
Mohit Sharma

**Comment by medyagh** [comment]
@imoisharma you can create a second cluster using "-p" flag

for example this will create a cluster called p1 with default kubernetes verison
```
minikube start -p p1 
```
and this will create another cluster called p2 with a different k8s version
```
minikube start -p p2 --kubernetes-version=v1.15.1
```

does that answer your quesiton ?

**Comment by imoisharma** [comment]
@medyagh I figure it out the issue, and your above propose solution is kind of similar. So, I am closing the issue, because I can run multiple minikube inside my Ubuntu.
