### ISSUE TITLE
Inaccesible kube-webhook-certgen image in addons.go causing a fail in ingress addon provisioning?

### ISSUE THREAD

**Issue by HubertStefanski** [kubernetes/minikube#11091]
The ingress addon stopped working with: 
```
minikube version: v1.19.0
commit: 15cede53bdc5fe242228853e737333b09d4336b5
```
After starting the minikube cluster using defaults, and enabling the ingress addon, the app will hang on verification.
This is caused by an unavailable image for the create and patch pods.
 ```
docker.io/jettech/kube-webhook-certgen:v1.5.1@sha256:950833e19ade18cd389d647efb88992a7cc077abedef343fa59e012d376d79b7
```
These images are defined here : [https://github.com/kubernetes/minikube/blob/master/pkg/minikube/assets/addons.go#L239-L241](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/assets/addons.go#L239-L241)
as a result, causing the ingress controller to fail as it cannot discover pre-requisites that are set up by create/patch pods

***Ingress controller pod fail message***
```
 MountVolume.SetUp failed for volume "webhook-cert" : secret "ingress-nginx-admission" not found 
```

### Failing pods
![image](https://user-images.githubusercontent.com/35736504/114570792-06d6ad00-9c6e-11eb-95db-9b7257d89430.png)

I'll try to address this soon.

**Steps to reproduce the issue:** 

1. `minikube start` (using default configuration)
2. `minikube addons enable ingress` 
3.  Minikube will get stuck on  `🔎  Verifying ingress addon...`

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
```shell
minikube start                 
😄  minikube v1.19.0 on Fedora 33
✨  Automatically selected the docker driver. Other choices: kvm2, ssh
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.5 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
 π grafana-operator master ✗ ❯ minikube addons enable ingress                    
    ▪ Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
🔎  Verifying ingress addon...
```

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by spowelljr** [comment]
@HubertStefanski Thank you for reporting the issue!

```
The ingress addon stopped working with
```
Just curious, do you know if this worked fine with a previous version of mininkube?

**Comment by HubertStefanski** [comment]
Hey @spowelljr , thanks for reaching out, It had worked with a prior version, however, I seem to have gotten it working now with v1.19.0 after a clean reinstall with rpm. Feel free to close this,

**Comment by spowelljr** [comment]
@HubertStefanski Glad you were able to resolve the issue! I will close the issue but feel free to reopen if the issue persists.
