### ISSUE TITLE
minikube failing to start with containerd and --wait=all flag

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#11101]
Starting minikube with containerd and without the `--wait=all` flag completes successfully.

But since #10985, if you start containerd with the `--wait=all` flag minikube fails to start with the following error
```
E0414 13:29:33.328256   76460 pod_ready.go:66] WaitExtra: waitPodCondition: timed out waiting for the condition
E0414 13:29:33.331163   76460 pod_ready.go:66] WaitExtra: waitPodCondition: error getting pod "coredns-74ff55c5b-ngsjr" in "kube-system" namespace: pods "coredns-74ff55c5b-ngsjr" not found

❌  Exiting due to GUEST_START: wait 6m0s for node: waiting for apps_running: expected k8s-apps: missing components: kube-dns
```

The coredns pod is failing to start, the logs of the coredns pods are
```
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Warning  FailedCreatePodSandBox  21m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "f8ad333be454f7a02489bbc08856bd9032fab763d68069c0c785e32846796857": failed to set bridge addr: could not add IP address to "cni0": permission denied
```

**Comment by medyagh** [comment]
seems like when I specify the CNI manually it works

$ minikube start --container-runtime=containerd --cni=cilium
😄  minikube v1.19.0 on Darwin 11.2.3
✨  Automatically selected the docker driver. Other choices: hyperkit, parallels, virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > index.docker.io/kicbase/sta...: 357.67 MiB / 357.67 MiB  100.00% 25.24 Mi
❗  minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.20, but successfully downloaded kicbase/stable:v0.0.20 as a fallback image
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
📦  Preparing Kubernetes v1.20.2 on containerd 1.4.4 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring Cilium (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
$ kc get pods -A 
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   cilium-dmj4w                       0/1     Running   0          62s
kube-system   cilium-operator-7c755f4594-gzljb   1/1     Running   0          62s
kube-system   coredns-74ff55c5b-w9vtl            0/1     Running   0          62s
kube-system   etcd-minikube                      1/1     Running   0          73s
kube-system   kube-apiserver-minikube            1/1     Running   0          73s
kube-system   kube-controller-manager-minikube   1/1     Running   0          73s
kube-system   kube-proxy-txzm2                   1/1     Running   0          62s
kube-system   kube-scheduler-minikube            0/1     Running   0          73s
kube-system   storage-provisioner                1/1     Running   1          74s

**Comment by spowelljr** [comment]
@medyagh The `--wait=all` flag wasn't passed

**Comment by medyagh** [comment]
ah you are right, with wait=all

it says

```

🌟  Enabled addons: storage-provisioner, default-storageclass
E0414 16:49:58.947751   94626 pod_ready.go:66] WaitExtra: waitPodCondition: error getting pod "coredns-74ff55c5b-nhk6w" in "kube-system" namespace: pods "coredns-74ff55c5b-nhk6w" not found
❌  Problems detected in kubelet:
    Apr 14 23:48:48 minikube kubelet[1573]: E0414 23:48:48.966843    1573 reflector.go:138] object-"kube-system"/"cilium-aws": Failed to watch *v1.Secret: failed to list *v1.Secret: secrets "cilium-aws" is forbidden: User "system:node:minikube" cannot list resource "secrets" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
    Apr 14 23:48:48 minikube kubelet[1573]: E0414 23:48:48.966985    1573 reflector.go:138] object-"kube-system"/"cilium-operator-token-69qjh": Failed to watch *v1.Secret: failed to list *v1.Secret: secrets "cilium-operator-token-69qjh" is forbidden: User "system:node:minikube" cannot list resource "secrets" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
❌  Problems detected in kubelet:
    Apr 14 23:48:48 minikube kubelet[1573]: E0414 23:48:48.966843    1573 reflector.go:138] object-"kube-system"/"cilium-aws": Failed to watch *v1.Secret: failed to list *v1.Secret: secrets "cilium-aws" is forbidden: User "system:node:minikube" cannot list resource "secrets" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
    Apr 14 23:48:48 minikube kubelet[1573]: E0414 23:48:48.966985    1573 reflector.go:138] object-"kube-system"/"cilium-operator-token-69qjh": Failed to watch *v1.Secret: failed to list *v1.Secret: secrets "cilium-operator-token-69qjh" is forbidden: User "system:node:minikube" cannot list resource "secrets" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
```

**Comment by prezha** [comment]
@medyagh yes, you are right - we are waiting on wrong things:

according to your [logs](https://github.com/kubernetes/minikube/issues/11101#issuecomment-819921426) above, depending on the order we get in the list of (coredns) pods, we might end up waiting for the initially created ("coredns-74ff55c5b-nhk6w" in this case) pod that got terminated, instead of waiting for the newly created one that replaced it ("coredns-74ff55c5b-9lgfb" in this case); i'll fix that in the upcoming pr

`Problems detected in kubelet` is a bit misleading here (ie, those errors in the logs are expected/irrelevant)
