### ISSUE TITLE
Replace references to echoserver with supported image from all documentation

### ISSUE THREAD

**Issue by sschober** [kubernetes/minikube#11107]
Trying out minikube on my Mac mini apple silicon/m1. 
But step 4 from [minikube start](https://minikube.sigs.k8s.io/docs/start/) is not working for me.
 
I am using Docker Desktop 3.3.1 (63152). I have activated the experimental feature: 
"Use new virtualisation framework" 
> Enables the new Big Sur virtualization.framework instead of the hypervisor.framework. You must reset your Kubernetes cluster when enabling for the first time.

Please let me know if I can provide further information!

**Steps to reproduce the issue:** 

1. brew install minikube
2. minikube start
3. kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.10

**Full output of failed command:** 
```
kubectl logs hello-minikube-5d9b964bfb-bscl4
Generating self-signed cert
Generating a 2048 bit RSA private key
.............+++
................................................................................................+++
writing new private key to '/certs/privateKey.key'
-----
Starting nginx
2021/04/15 19:56:10 [error] 14#14: failed to initialize Lua VM in /etc/nginx/nginx.conf:88
nginx: [error] failed to initialize Lua VM in /etc/nginx/nginx.conf:88
```

**Full output of `minikube start` command used, if not already included:**

😄  minikube v1.19.0 auf Darwin 11.2.3 (arm64)
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
\    > gcr.io/k8s-minikube/kicbase...: 357.67 MiB / 357.67 MiB  100.00% 1.82 MiB
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
    > kubectl.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 35.44 MiB / 35.44 MiB [------------] 100.00% 2.18 MiB p/s 16.44s
    > kubeadm: 34.50 MiB / 34.50 MiB [-----------] 100.00% 1.72 MiB p/s 20.229s
    > kubelet: 100.57 MiB / 100.57 MiB [---------] 100.00% 3.32 MiB p/s 30.452s

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Optional: Full output of `minikube logs` command:**
[minikube.log](https://github.com/kubernetes/minikube/files/6320839/minikube.log)

**Comment by sschober** [comment]
I just deactivated the "new virtualisation framework" option and retried, with the same result.

**Comment by afbjorklund** [comment]
I'm not sure if k8s.gcr.io/echoserver:1.10 has any arm64 variant, it looks like amd64 only ?

**Comment by sschober** [comment]
Thanks for the hint! Might this be worth a note in the docs? Would have saved me some time. :)

**Comment by afbjorklund** [comment]
> I could do that as well, if this would be welcome-

That would be much welcome. I'm not sure if there is an alternative image available, but a note in the docs would be a start!

```
REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
k8s.gcr.io/echoserver   1.10      365ec60129c5   3 years ago   95.4MB
k8s.gcr.io/echoserver   1.4       a90209bb39e3   4 years ago   140MB
```

https://minikube.sigs.k8s.io/docs/start/
https://kubernetes.io/docs/tutorials/hello-minikube/

It seems to be based on the "nginx" image, so it should be possible to make a new version of it that also supports `arm64`.

```console
$ docker run -it --entrypoint "" k8s.gcr.io/echoserver:1.4 nginx -V
nginx version: nginx/1.10.0
```
/etc/os-release
PRETTY_NAME="Ubuntu 16.04 LTS"

```console
$ docker run -it --entrypoint "" k8s.gcr.io/echoserver:1.10 nginx -V
nginx version: nginx/1.13.3
```
/etc/os-release
PRETTY_NAME="Ubuntu 16.04.2 LTS"

**Comment by afbjorklund** [comment]
I found it, it lived in k8s "ingress-nginx" - but it died in 2018.

https://github.com/kubernetes/ingress-nginx/tree/84a6e0c1ab54f8c8e374237b8d9215dcbaa29f0f/images/echoheaders

```
REPOSITORY                            TAG       IMAGE ID       CREATED       SIZE
gcr.io/google_containers/echoserver   1.10      365ec60129c5   3 years ago   95.4MB
```

Then it got bumped to 2.1, but nobody bothered updating docs.

`gcr.io/kubernetes-e2e-test-images/echoserver:2.1`

nginx version: nginx/1.12.2
PRETTY_NAME="Alpine Linux v3.7"

**Comment by sschober** [comment]
Hey thank you for all this information! I am trying to digest what this means for me currently...

I tried deploying `echoserver:2.2`, but only got the following result:

```
Generating self-signed cert
Generating a 2048 bit RSA private key
..............................................+++
......+++
writing new private key to '/certs/privateKey.key'
-----
Starting nginx
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
```

`echoserver:2.1` yields the same.

I currently clone the Kubernetes repo and try to build the echoserver image on my machine... and yes this seems to be successful:

```shell
git clone <kubernetes-repo>
cd kubernetes/test/images/echoserver
vim Dockerfile # get rid of all that cross-build stuff I do not know :)
docker build .
docker tag <image id> echoserver:v2.2
minikube load echoserver:v2.2
kubectl create deployment hello-minikube --image=echoserver:v2.2
# success :)
```
This way, I can now continue with the getting started guide. :)

I can add a note to the docs if you like, with a reference to this issue maybe?

**Comment by afbjorklund** [comment]
My bad, I should have tested the image rather than assuming that it would work just because it is used in the k8s test.

Crashes the same way on Linux. Apparently they "forgot" to release a version of the echoserver, with arm64 support...

https://github.com/kubernetes/ingress-nginx/issues/2802

```
ubuntu@ubuntu:~$ docker run gcr.io/kubernetes-e2e-test-images/echoserver:2.2
Generating self-signed cert
Generating a 2048 bit RSA private key
...............................+++
.............................................................................+++
writing new private key to '/certs/privateKey.key'
-----
Starting nginx
PANIC: unprotected error in call to Lua API (bad light userdata pointer)
```

Like you say, minikube doesn't need the LuaJIT support anyway.

But upgrading nginx to something less ancient, would fix it too...

The weird thing is that the git repository says nginx 1.15, but image says 1.12 ?
Anything newer than 2018 would work, the nginx-ingress-controller used 1.15.6.

**Comment by awarus** [comment]
+1, I've spent about 2 days running hello-minikube. I couldn't start hello-minikube on apple MacBook Pro with M1 chip(MacOS 11.4 BigSur (20F71)). Have always the same situation:
`hello-minikube-6ddfcc9757-5x8bp             0/1     CrashLoopBackOff`

**Comment by FLAGLORD** [comment]
@awarus Have you solved this problem?

**Comment by awarus** [comment]
> @awarus Have you solved this problem?

No, as far I understand hello-minikube image is not available now for M1

**Comment by sharifelgamal** [comment]
What we're going to end up doing here is creating an image that support multiple archs and using that instead of echoserver for all these demos and guides.

**Comment by zhyyu** [comment]
> Hey thank you for all this information! I am trying to digest what this means for me currently...
> 
> I tried deploying `echoserver:2.2`, but only got the following result:
> 
> ```
> Generating self-signed cert
> Generating a 2048 bit RSA private key
> ..............................................+++
> ......+++
> writing new private key to '/certs/privateKey.key'
> -----
> Starting nginx
> PANIC: unprotected error in call to Lua API (bad light userdata pointer)
> ```
> 
> `echoserver:2.1` yields the same.
> 
> I currently clone the Kubernetes repo and try to build the echoserver image on my machine... and yes this seems to be successful:
> 
> ```shell
> git clone <kubernetes-repo>
> cd kubernetes/test/images/echoserver
> vim Dockerfile # get rid of all that cross-build stuff I do not know :)
> docker build .
> docker tag <image id> echoserver:v2.2
> minikube load echoserver:v2.2
> kubectl create deployment hello-minikube --image=echoserver:v2.2
> # success :)
> ```
> 
> This way, I can now continue with the getting started guide. :)
> 
> I can add a note to the docs if you like, with a reference to this issue maybe?

Hi, can you share the Dockerfile you changed with us?

**Comment by zhyyu** [comment]
> > @awarus Have you solved this problem?
> 
> No, as far I understand hello-minikube image is not available now for M1

e2eteam/echoserver:2.2-linux-arm64 worked for me on m1

**Comment by spowelljr** [comment]
Thanks for finding that image @zhyyu! This issue is open to anyone that wants to take it.

**Comment by ollydixon** [comment]
@zhyyu when I use that image, I get the following

```
Generating self-signed cert
Generating a RSA private key
...............+++++
...........................................................+++++
writing new private key to '/certs/privateKey.key'
-----
Starting nginx
2021/11/29 16:50:50 [alert] 10#10: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2021/11/29 16:50:50 [error] 10#10: lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
no field package.preload['resty.core']
no file './resty/core.lua'
no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
no file '/usr/local/share/lua/5.1/resty/core.lua'
no file '/usr/local/share/lua/5.1/resty/core/init.lua'
no file '/usr/share/lua/5.1/resty/core.lua'
no file '/usr/share/lua/5.1/resty/core/init.lua'
no file '/usr/share/lua/common/resty/core.lua'
no file '/usr/share/lua/common/resty/core/init.lua'
no file './resty/core.so'
no file '/usr/local/lib/lua/5.1/resty/core.so'
no file '/usr/lib/lua/5.1/resty/core.so'
no file '/usr/local/lib/lua/5.1/loadall.so'
no file './resty.so'
no file '/usr/local/lib/lua/5.1/resty.so'
no file '/usr/lib/lua/5.1/resty.so'
no file '/usr/local/lib/lua/5.1/loadall.so')
nginx: [error] lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
no field package.preload['resty.core']
no file './resty/core.lua'
no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
no file '/usr/local/share/lua/5.1/resty/core.lua'
no file '/usr/local/share/lua/5.1/resty/core/init.lua'
no file '/usr/share/lua/5.1/resty/core.lua'
no file '/usr/share/lua/5.1/resty/core/init.lua'
no file '/usr/share/lua/common/resty/core.lua'
no file '/usr/share/lua/common/resty/core/init.lua'
no file './resty/core.so'
no file '/usr/local/lib/lua/5.1/resty/core.so'
```

Any ideas?

**Comment by doortts** [comment]
@ollydixon Thanks! It works for me!
@zhyyu Sorry, it doesn't work for me, m1/Monterey system.

**Comment by preslavmihaylov** [comment]
The image @zhyyu didn't work for me unfortunately (I'm on Apple M1).

I used this one instead which served the same purpose for me - [nginxdemos/hello](https://hub.docker.com/r/nginxdemos/hello)

**Comment by dadan2019** [comment]
> > > @awarus Have you solved this problem?
> > 
> > 
> > No, as far I understand hello-minikube image is not available now for M1
> 
> e2eteam/echoserver:2.2-linux-arm64 worked for me on m1

This does not work for me on m1. Yes. the pod seems healthy on the dashboard. However, I got the below error when running 'k logs hello-minikube-bc84b9485-x6p5h'


2021/12/31 00:49:26 [alert] 10#10: detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
nginx: [alert] detected a LuaJIT version which is not OpenResty's; many optimizations will be disabled and performance will be compromised (see https://github.com/openresty/luajit2 for OpenResty's LuaJIT or, even better, consider using the OpenResty releases from https://openresty.org/en/download.html)
2021/12/31 00:49:26 [error] 10#10: lua_load_resty_core failed to load the resty.core module from https://github.com/openresty/lua-resty-core; ensure you are using an OpenResty release from https://openresty.org/en/download.html (rc: 2, reason: module 'resty.core' not found:
	no field package.preload['resty.core']
	no file './resty/core.lua'
	no file '/usr/share/luajit-2.1.0-beta3/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core.lua'
	no file '/usr/local/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/5.1/resty/core.lua'
	no file '/usr/share/lua/5.1/resty/core/init.lua'
	no file '/usr/share/lua/common/resty/core.lua'
	no file '/usr/share/lua/common/resty/core/init.lua'
	no file './resty/core.so'
	no file '/usr/local/lib/lua/5.1/resty/core.so'
	no file '/usr/lib/lua/5.1/resty/core.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './resty.so'
	no file '/usr/local/lib/lua/5.1/resty.so'
	no file '/usr/lib/lua/5.1/resty.so'
	no file '/usr/local/lib/lua/5.1/loadall.so')

**Comment by dadan2019** [comment]
> For anyone else still struggling, just use a node echo server `polyverse/node-echo-server`

This works as of today. Thanks ollydixon.

**Comment by ysheikh245** [comment]
I am trying the following on my M1 macbook and getting the following error:
kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment hello-minikube --type=NodePort --port=8080


|-----------|----------------|-------------|---------------------------|
| NAMESPACE |      NAME      | TARGET PORT |            URL            |
|-----------|----------------|-------------|---------------------------|
| default   | hello-minikube |        9080 | http://192.168.49.2:30635 |
|-----------|----------------|-------------|---------------------------|
🏃  Starting tunnel for service hello-minikube.
|-----------|----------------|-------------|------------------------|
| NAMESPACE |      NAME      | TARGET PORT |          URL           |
|-----------|----------------|-------------|------------------------|
| default   | hello-minikube |             | http://127.0.0.1:54812 |
|-----------|----------------|-------------|------------------------|
🎉  Opening service default/hello-minikube in default browser...
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.


Kindly suggest.

**Comment by spowelljr** [comment]
Hi @ysheikh245, as commented above there are a couple different images that work for M1.

https://github.com/kubernetes/minikube/issues/11107#issuecomment-919742761
https://github.com/kubernetes/minikube/issues/11107#issuecomment-981830947

**Comment by preslavmihaylov** [comment]
None of the image cited above worked for me so I created a small, similar image myself which aims to test getting deployed on minikube.

Here's how to use it:
```
kubectl create deployment hello-minikube --image=preslavmihaylov/kubehelloworld:latest
kubectl expose deployment hello-minikube --type=NodePort --port=3000
```

Then, expose it on localhost & go to `http://localhost:3000`:
```
kubectl port-forward service/hello-minikube 3000:3000
```

**Comment by AliNazariii** [comment]
@preslavmihaylov Thanks.

**Comment by Tazovsky** [comment]
@preslavmihaylov thanks!



I have following service:

```
$ kubectl -n traefik get service   
NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                       AGE
ggtips                    ClusterIP   10.96.41.7      <none>        80/TCP                        33m
traefik-ingress-service   NodePort    10.110.178.12   <none>        80:32194/TCP,8080:31621/TCP   33m
whoami                    ClusterIP   10.103.52.177   <none>        80/TCP                        33m

$ minikube ip
192.168.49.2
```

Can anyone explain why it is available only after port forwarding at http://localhost:8081 and http://localhost:8080:

```
kubectl -n traefik  port-forward service/traefik-ingress-service 8081:80 8080:8080
``` 
instead of 127.0.0.1:32194, 127.0.0.1:31621 or 192.168.49.2:32194, 192.168.49.2:31621 ?


`minikube` does not return any URL:

```
 $ minikube --namespace=traefik service traefik-ingress-service --url

🏃  Starting tunnel for service traefik-ingress-service.
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
```

**Comment by preslavmihaylov** [comment]
@Tazovsky I believe this is because the addresses you see in there are part of minikube's internal network and you have to expose them for this to work locally.

When using AWS or similar as backend, usually, you'll get a hostname you can connect to directly

**Comment by drinkbeer** [comment]
> kubectl port-forward service/hello-minikube 3000:3000

Thank you so much! It works in my M1 macbook.

**Comment by shorif2000** [comment]
> > > @awarus Have you solved this problem?
> > 
> > 
> > No, as far I understand hello-minikube image is not available now for M1
> 
> e2eteam/echoserver:2.2-linux-arm64 worked for me on m1

This is showing all green but when running `minikube service hello-minikube` it fails with
```

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.startKicServiceTunnel({0x14000213450, 0x1, 0x1}, {0x0, 0x0, 0x0}, {0x1045f0cf3, 0x8}, {0x14000d87b1a, 0x6})
	/app/cmd/minikube/cmd/service.go:205 +0x340
k8s.io/minikube/cmd/minikube/cmd.glob..func35(0x106109aa0, {0x14000213450, 0x1, 0x1})
	/app/cmd/minikube/cmd/service.go:143 +0x594
github.com/spf13/cobra.(*Command).execute(0x106109aa0, {0x14000213420, 0x1, 0x1})
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x1061095a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:157 +0xdb8
main.main()
	/app/cmd/minikube/main.go:86 +0x2a0

```

**Comment by klaases** [comment]
Hi @sschober, did the comments above help resolve this issue in your case?

We see that @[drinkbeer](https://github.com/drinkbeer) was able to get things working as well.

**Comment by silasb** [comment]
I ended up forking echoserver as https://github.com/silasb/echoserver and a ARM64 docker image is located here https://hub.docker.com/r/silasb/echoserver

**Comment by scubbo** [comment]
+1 to the request for a note in the docs that this image might not work for everyone. I only happened to recognize the error log of `exec user process caused: exec format error` as being related to architecture issues from previous experience, we shouldn't assume newbies would be able to infer that.

(FWIW, I found that [`echoserver-arm:1.8`](https://console.cloud.google.com/gcr/images/google-containers/global/echoserver-arm) worked fine on my Raspberry Pi 4 64-bit)

**Comment by klaases** [comment]
If anyone is interested in creating their own pod and service to use with the tutorial on Mac M1/ARM64, this [comment](https://github.com/kubernetes/minikube/issues/14580#issuecomment-1185990358) might be helpful. Let me know if any questions.

**Comment by hanseltime** [comment]
> I ended up forking echoserver as https://github.com/silasb/echoserver and a ARM64 docker image is located here https://hub.docker.com/r/silasb/echoserver

Thank you for pushing an image that works for the architecture.  Would love to see this repo added to the k8s docks/registry

**Comment by spowelljr** [comment]
I found an image `docker.io/jmalloc/echo-server:0.3.3` that works on both amd64 & arm64, will make a PR shortly to update the documentation.

Also scanned the image for vulnerabilities and scan can back clean.

```
Testing docker.io/jmalloc/echo-server:0.3.3...

Package manager:   linux
Project name:      docker-image|docker.io/jmalloc/echo-server
Docker image:      docker.io/jmalloc/echo-server:0.3.3
Platform:          linux/arm64
Licenses:          enabled

✔ Tested docker.io/jmalloc/echo-server:0.3.3 for known issues, no vulnerable paths found.

Note that we do not currently have vulnerability data for your image.

-------------------------------------------------------

Testing docker.io/jmalloc/echo-server:0.3.3...

Package manager:   gomodules
Target file:       /bin/echo-server
Project name:      github.com/jmalloc/echo-server
Docker image:      docker.io/jmalloc/echo-server:0.3.3
Licenses:          enabled

✔ Tested 9 dependencies for known issues, no vulnerable paths found.


Tested 2 projects, no vulnerable paths were found.
```
