### ISSUE TITLE
Dockerized build for minikube-iso

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1110]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

Allow the minikube iso to be compiled inside a container.

**Comment by dlorenc** [comment]
Yeah we should do this. I tried once and ran into some locale issues with buildroot in a debian container, but I'm sure it's possible.

**Comment by tvon** [comment]
I've been poking at this a bit and can get as far as syslinux before the build fails.

The `Dockerfile`:

```dockerfile
FROM ubuntu:16.10

RUN dpkg --add-architecture i386 \
      && apt-get -q update \
      && apt-get -y install \
        automake \
        bc \
        build-essential \
        bzr \
        cpio \
        cvs \
        gcc-multilib \
        git \
        gnupg \
        golang-go \
        libc6:i386 \
        libncurses5-dev \
        libtool \
        mercurial \
        p7zip-full \
        python \
        subversion \
        unzip \
        vim \
        wget \
      && rm -rf /var/lib/apt/lists/* \
      && localedef -c -f UTF-8 -i en_US en_US.UTF-8

# Without dumb-init a ^C during a "docker run make" seems to just hang.
RUN cd /tmp && wget https://github.com/Yelp/dumb-init/releases/download/v1.2.0/dumb-init_1.2.0_amd64.deb && dpkg -i dumb-init_*.deb && rm dumb-init_*.deb

WORKDIR /usr/local/src
VOLUME /usr/local/src

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD ["/bin/bash"]
```

Run via:

```
docker build -t minikube-iso-builder .
cd /path/to/minikube
docker run --rm -it -v $PWD:/usr/local/src minikube-iso-builder make minikube-iso
```

It fails building syslinux with the following:


    arch/i386/interface/pcbios/int13.c:469:2: error: impossible constraint in 'asm'
    bin/deps/arch/i386/interface/pcbios/int13.c.d:86: recipe for target 'bin/int13.o' failed
    make[6]: *** [bin/int13.o] Error 1
    make[6]: Leaving directory '/usr/local/src/out/buildroot/output/build/syslinux-6.03/gpxe/src'
    /usr/local/src/out/buildroot/output/build/syslinux-6.03/gpxe/Makefile:44: recipe for target 'src/bin/blib.a' failed
    make[5]: *** [src/bin/blib.a] Error 2
    make[5]: Leaving directory '/usr/local/src/out/buildroot/output/build/syslinux-6.03/bios/gpxe'
    /usr/local/src/out/buildroot/output/build/syslinux-6.03/Makefile:285: recipe for target 'gpxe' failed
    make[4]: *** [gpxe] Error 2
    make[4]: Leaving directory '/usr/local/src/out/buildroot/output/build/syslinux-6.03/bios'
    /usr/local/src/out/buildroot/output/build/syslinux-6.03/Makefile:254: recipe for target 'bios' failed
    make[3]: *** [bios] Error 2
    make[3]: Leaving directory '/usr/local/src/out/buildroot/output/build/syslinux-6.03'
    Makefile:103: recipe for target 'bios' failed
    make[2]: *** [bios] Error 2
    make[2]: Leaving directory '/usr/local/src/out/buildroot/output/build/syslinux-6.03'
    package/pkg-generic.mk:201: recipe for target '/usr/local/src/out/buildroot/output/build/syslinux-6.03/.stamp_built' failed
    make[1]: *** [/usr/local/src/out/buildroot/output/build/syslinux-6.03/.stamp_built] Error 2
    make[1]: Leaving directory '/usr/local/src/out/buildroot'
    Makefile:85: recipe for target 'minikube-iso' failed
    make: *** [minikube-iso] Error 2


This is apparently a known issue with using a GCC built with `--enable-default-pie` (ref at the bottom here http://www.syslinux.org/wiki/index.php?title=Building) but I have not been able to figure out how to pass CFLAGS to syslinux, but this is my first interaction with buildroot so maybe someone has some ideas.

**Comment by tvon** [comment]
[Moved to a gist](https://gist.github.com/tvon/2a9f633546d951b9a083edf680702fca)

**Comment by tvon** [comment]
I have a WIP [branch over here](https://github.com/tvon/minikube/tree/iso-build-container).  The container there can build `minikube-iso`, though it could be made to be much smarter.
