### ISSUE TITLE
Bring back bootlocal.sh

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1111]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

The boot2docker image had a script that was run on every machine start.  The minikube-iso has a similar script, but it combined with a lot of other setup.  I'm proposing that we execute a "bootlocal" script here so that people can put all their customizations there instead of modifying the automount script.

**Comment by dlorenc** [comment]
It would be cool if we could get this on a mounted directory.
