### ISSUE TITLE
The dilemma of VPN connection: Cisco AnyConnnect

### ISSUE THREAD

**Issue by ChampionZP** [kubernetes/minikube#11112]
**Steps to reproduce the issue:** 

1. Connect VPN (Cisco AnyConnnect)
2. minikube start --vm-driver=hyperkit

**Full output of failed command:** 
    > docker-machine-driver-hyper...: 65 B / 65 B [----------] 100.00% ? p/s 0s
    > docker-machine-driver-hyper...: 10.52 MiB / 10.52 MiB  100.00% 981.70 KiB
🔑  The 'hyperkit' driver requires elevated permissions. The following commands will be executed:

    $ sudo chown root:wheel /Users/ping/.minikube/bin/docker-machine-driver-hyperkit
    $ sudo chmod u+s /Users/ping/.minikube/bin/docker-machine-driver-hyperkit

Password:
    > minikube-v1.19.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.19.0.iso: 244.49 MiB / 244.49 MiB  100.00% 456.03 KiB p/s 9m9
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.20.2 preload ...
    > preloaded-images-k8s-v10-v1...: 491.71 MiB / 491.71 MiB  100.00% 683.03 K
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🔥  removing hyperkit “minikube”…
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for 2e:d2:21:65:88:31
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for 5a:c2:f6:ea:ce:34

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for 5a:c2:f6:ea:ce:34

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

1. disconnect my VPN
2. minikube delete && minikube start --vm-driver=hyperkit

**Optional: Full output of `minikube logs` command:**

removing hyperkit “minikube”…
💀  Removed all traces of the "minikube" cluster.
😄  Darwin 11.2.3 minikube v1.19.0
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
❗  ***This VM is having trouble accessing https://k8s.gcr.io***
💡  ***To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/***
🐳  Docker 20.10.4 Kubernetes v1.20.2…
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

I have also tried "Allow local(LAN) access when using VPN" as below, but it didn't work:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/24950619/114995923-e5c1c680-9ed0-11eb-9403-5cfce50eea53.png">

**Comment by spowelljr** [comment]
@ChampionZP Thanks for reporting the issue. Could you re-run the start command with the `--alsologtostderr` flag to generate more detailed logs and attach those logs to this issue please.

**Comment by ChampionZP** [comment]
Thank you. @spowelljr 

I have run ` minikube start --vm-driver=docker --alsologtostderr` and got the below output (please see the attached output.txt):

[output.txt](https://github.com/kubernetes/minikube/files/6355181/output.txt)

Basically, the current issue is that I got a "ImagePullBackOff" error when I try to work out a demo minikube project with MongoDB and mongo express:

The complete process that I tried is as follows:

1. `minikube start --vm-driver=docker`
2. `kubectl get nodes`

NAME       STATUS   ROLES                  AGE   VERSION
minikube   Ready    control-plane,master   10m   v1.20.2

3. `kubectl apply -f mongo-secret.yaml`

secret/mongodb-secret created

4. `kubectl apply -f mongo.yaml`

eployment.apps/mongodb-deployment created
service/mongodb-service created

5. `kubectl apply -f mongo-configmap.yaml`

configmap/mongodb-configmap created

6. ` kubectl apply -f mongo-express.yaml`

deployment.apps/mongodb-express created

7. `kubectl get pods`

NAME                                 READY   STATUS             RESTARTS   AGE
mongodb-deployment-8f6675bc5-jsjhb   1/1     Running            0          119s
mongodb-express-7d65d5c746-28nbq     0/1     ImagePullBackOff   0          26s

The above results show that the pod "mongodb-express-7d65d5c746-28nbq" is not running and get a "ImagePullBackOff".

I try to describe the details as 

`kubectl describe pod mongodb-express-7d65d5c746-28nbq`

and I got:

Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  3m3s                 default-scheduler  Successfully assigned default/mongodb-express-7d65d5c746-28nbq to minikube
  Normal   Pulling    86s (x4 over 3m3s)   kubelet            Pulling image "mongodb-express"
  Warning  Failed     79s (x4 over 2m56s)  kubelet            Failed to pull image "mongodb-express": rpc error: code = Unknown desc = Error response from daemon: pull access denied for mongodb-express, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
  Warning  Failed     79s (x4 over 2m56s)  kubelet            Error: ErrImagePull
  Warning  Failed     53s (x6 over 2m55s)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    39s (x7 over 2m55s)  kubelet            Back-off pulling image "mongodb-express"

I have also tried `docker login`, but it didn't work.

The above used .yaml files are:

[mongo-secret-yaml.txt](https://github.com/kubernetes/minikube/files/6355257/mongo-secret-yaml.txt)
[mongo-yaml.txt](https://github.com/kubernetes/minikube/files/6355261/mongo-yaml.txt)
[mongo-configmap-yaml.txt](https://github.com/kubernetes/minikube/files/6355263/mongo-configmap-yaml.txt)
[mongo-express-yaml.txt](https://github.com/kubernetes/minikube/files/6355274/mongo-express-yaml.txt)

Thanks a lot!

**Comment by medyagh** [comment]
@ChampionZP thank you for providing more comments, I wonder if you would be willing to do a private slack chat to go over this problem live together or schedule a call ?

**Comment by spowelljr** [comment]
@ChampionZP Due to no response I'm going to close this issue. If in the future you're interested in doing a private slack chat or scheduling a call feel free to respond, thanks!
