### ISSUE TITLE
minikube freezes after  start command is executed

### ISSUE THREAD

**Issue by pancudaniel7** [kubernetes/minikube#11124]
**Steps to reproduce the issue:** 

1. minikube start --drive=docker 

**Full output of failed command:** 

Error: "failed to get storage capacity of /var: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain"

**Full output of `minikube start` command used, if not already included:**

😄  minikube v1.19.0 on Ubuntu 20.10
✨  Using the docker driver based on user configuration
🛑  The "docker" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❌  Exiting due to DRV_AS_ROOT: The "docker" driver should not be used with root privileges.

➜  workspace  minikube start --driver=docker    
😄  minikube v1.19.0 on Ubuntu 20.10
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
     
🤦  StartHost failed, but will try again: provision: Temporary Error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
🏃  Updating the running docker "minikube" container ...

(Freeze here)

**Optional: Full output of `minikube logs` command:**
<details>

Minikube status:

E0417 20:28:28.896904   16372 status.go:373] failed to get storage capacity of /var: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
E0417 20:28:28.896966   16372 status.go:257] status error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

</details>

OS:

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.10
Release:	20.10
Codename:	groovy

**Comment by pancudaniel7** [comment]
I've found the problem on Ubuntu, my **Docker** was installed using **snap** witch for some reason dose not work properly with **minikube**, so I've reinstall **Docker** using **apt-get** and it works now.

**Comment by medyagh** [comment]
@pancudaniel7 thanks for updating, we add support for minikube to run with docker installed with snap
do u mind trying

https://github.com/kubernetes/minikube/releases/tag/v1.20.0-beta.0

**Comment by pancudaniel7** [comment]
Thank you, I will test and comeback with a status 👍🏻

**Comment by 1dropaflame** [comment]
I get this error. I have Docker Desktop on Windows 11 with WSL2 installed.

```
C:\Windows\System32>minikube start --kubernetes-version=1.26.2  --driver=docker
* minikube v1.29.0 on Microsoft Windows 11 Home 10.0.22621.1265 Build 22621.1265
! Specified Kubernetes version 1.26.2 is newer than the newest supported version: v1.26.1. Use `minikube config defaults kubernetes-version` for details.
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Downloading Kubernetes v1.26.2 preload ...
    > preloaded-images-k8s-v18-v1...:  396.97 MiB / 396.97 MiB  100.00% 12.23 M
* Restarting existing docker container for "minikube" ...
! StartHost failed, but will try again: provision: Temporary Error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
* Updating the running docker "minikube" container ...
```
