### ISSUE TITLE
How to get or specify the ETCd server IP.

### ISSUE THREAD

**Issue by skormos** [kubernetes/minikube#1113]
I've read other issues where it was suggested that utilizing minikube's ETCd was not recommended practice, which is an answer that I cannot accept, unfortunately.

We have built our kubernetes cluster with some tooling that is based on the availability of ETCd to work in concert with confd. This was long before minikube was created.

I would like to know how to make minikube's ETCd server available to query from inside the cluster, so that a service / pod can see it, and hence confd can use it as a data source. 

This is OS X (El Capitan or Sierra), minikube 0.12+, xhyve or VirtualBox.

**Comment by r2d4** [comment]
Right now we only listen on localhost, and we could possibly try to add another listener that binds to the cluster ip.  If this works in normal k8s installs, we should probably support it here.

**Comment by skormos-lv** [comment]
Aw, this is awesome. I can't wait to try it out. 

Thanks for the quick turnaround, and the addition to the README!
