### ISSUE TITLE
minikube start should wailt till "download-only" is finishing

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11166]
we could use our lock package https://github.com/kubernetes/minikube/tree/master/pkg/util/lock

to put a lock when ```minikube start --download-only``` happens

and then when `minikube start` runs when this lock exists will Wait for it to finish up to a reasonable time

**Comment by afbjorklund** [comment]
I'm confused. You mean that `minikube start` exits currently, before the downloads have been completed ?

**Comment by andriyDev** [comment]
The latter. When running two instances of `minikube start`, only one image should be downloaded.

The original issue involved only locking when `--download-only` was involved, but perhaps this should be more generic and apply to any `minikube start`.

**Comment by afbjorklund** [comment]
Good thing, we had some other corruption of the download images so I was starting to question everything :-)
