### ISSUE TITLE
minikube start fails \  

### ISSUE THREAD

**Issue by mben19** [kubernetes/minikube#11162]
**Steps to reproduce the issue:** 

1.minikube start
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create host timed out in 360.000000 seconds
! Startup with hyperv driver failed, trying with alternate driver ssh: Failed to start host: creating host: create host timed out in 360.000000 seconds
* Stopping node "minikube"  ...
* Powering off "minikube" via SSH ...
* Deleting "minikube" in hyperv ...
! Failed to delete cluster minikube, proceeding with retry anyway.

X Exiting due to MK_USAGE: No IP address provided. Try specifying --ssh-ip-address, or see https://minikube.sigs.k8s.io/docs/drivers/ssh/

**then I tried with
minikube start --driver=ssh --ssh-ip-address=vm.example.com**

PS C:\WINDOWS\system32> minikube start --driver=ssh --ssh-ip-address=vm.example.com
* minikube v1.19.0 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
* Using the ssh driver based on user configuration

X Exiting due to MK_USAGE: lookup vm.example.com: no such host
*
* If the above advice does not help, please let us know:
  https://github.com/kubernetes/minikube/issues/new/choose

3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@mben19 for SSH driver you need a remote IP

do u mind pasting the output of `minikube logs`

**Comment by spowelljr** [comment]
Hi @mben19, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
