### ISSUE TITLE
Offline mode with GPU

### ISSUE THREAD

**Issue by belsakn** [kubernetes/minikube#11163]
**Steps to reproduce the issue:** 

1. `minikube start --download-only`
2. Turn off the wifi and lan
3. `minikube start --driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost`

**Full output of failed command:** 
```
$ minikube start --driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost
😄  minikube v1.19.0 on Ubuntu 20.10
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
🤦  StartHost failed, but will try again: driver start: no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"
🔄  Restarting existing none bare metal machine for "minikube" ...
😿  Failed to start none bare metal machine. Running "minikube delete" may fix it: driver start: no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"

❌  Exiting due to GUEST_PROVISION: Failed to start host: driver start: no default routes found in "/proc/net/route" or "/proc/net/ipv6_route"

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
Kubernetes requires a network interface.

```
// getAllDefaultRoutes obtains IPv4 and IPv6 default routes on the node. If unable
// to read the IPv4 routing info file, we return an error. If unable to read the IPv6
// routing info file (which is optional), we'll just use the IPv4 route information.
// Using all the routing info, if no default routes are found, an error is returned.
```

**Comment by belsakn** [comment]
@afbjorklund tnx for the info.
Do you know why does it work if i run just `minikube start` when offline?

**Comment by afbjorklund** [comment]
If you don't want to use the real networks, you probably have to set up some host-local network just for the cluster.

But only having loopback doesn't really work, when you have multiple nodes. It also expects unique MACs and so on...

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#before-you-begin

The virtual environments (hypervisor or container) set up by minikube, are supposed to provide these for you (normally)

**Comment by spowelljr** [comment]
Based on the conversation this seems to have been resolved. I'm going to close this issue, but if your issue is not resolved feel free to reopen the issue, thanks!
