### ISSUE TITLE
kubeadm join error: "Found multiple CRI sockets, please use --cri-socket to select one: /var/run/dockershim.sock, /var/run/crio/crio.sock"

### ISSUE THREAD

**Issue by prezha** [kubernetes/minikube#11179]
kubeadm join will fail with this error if multiple CRI sockets exist (eg, both docker and crio are started at the same time)

/assign

**Comment by afbjorklund** [comment]
minikube is supposed to set the criSocket in the config, but maybe it fails to do so for the non-CRI (i.e. dockershim)
