### ISSUE TITLE
Error while starting service in minikube .cfs_quota_us: invalid argument: unknown

### ISSUE THREAD

**Issue by ranjankhanna** [kubernetes/minikube#11170]
We are using minikube version: v1.19.0 on OEL 7 with docker driver.
 
While starting a service we are  getting following error:
  Warning  Failed     14m (x5 over 15m)   kubelet            Error: failed to start container "coherence": Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: process_linux.go:495: container init caused: process_linux.go:458: setting cgroup config for procHooks process caused: failed to write "3200000": write /sys/fs/cgroup/cpu,cpuacct/kubepods/burstable/pod5f937ae5-4b75-4ad2-8dc4-133f32ada485/coherence/cpu.cfs_quota_us: invalid argument: unknown
  Warning  BackOff    52s (x72 over 15m)  kubelet            Back-off restarting failed container

**Comment by medyagh** [comment]
@ranjankhanna do u mind sharing the full output of `minikube logs`

**Comment by ranjankhanna** [comment]
[logs-Apr-22.txt](https://github.com/kubernetes/minikube/files/6362078/logs-Apr-22.txt)
Attached log file

**Comment by ranjankhanna** [comment]
Any suggestions that i can try?

**Comment by andriyDev** [comment]
This issue has been quiet for over a month, so I'm closing it. If the issue continues, please reopen!
