### ISSUE TITLE
KubeVirt addon couldn't get enabled

### ISSUE THREAD

**Issue by yeahdongcn** [kubernetes/minikube#11187]
**Steps to reproduce the issue:** 

1. minikube addons enable kubevirt -p demo
2. 
3.

**Full output of failed command:** 

[xx@nhk8s-node2 ~]$ minikube addons enable kubevirt -p demo
  - Using image bitnami/kubectl:1.17
* The 'kubevirt' addon is enabled

kubevirt-install-manager got started but nothing happened.

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

[xx@nhk8s-node2 ~]$ kubectl logs kubevirt-install-manager -n kube-system
v0.40.0
error: the path "/manifests/kubevirt-base.yaml" does not exist
error: unable to recognize "/manifests/kubevirt.yaml": no matches for kind "KubeVirt" in version "kubevirt.io/v1"

</details>

**Comment by ilya-zuyev** [comment]
Hi @yeahdongcn! What is you OS, and what version of minikube and which minikube driver are you using? Thanks!

**Comment by andriyDev** [comment]
This issue is getting quite old, so I will close it. If the issue persists, please feel free to reopen!

**Comment by mecampbellsoup** [comment]
Did you ever resolve this @yeahdongcn ?

**Comment by cheese** [comment]
Still an issue as reported at https://github.com/kubernetes/kubernetes/issues/93513
