### ISSUE TITLE
Only run `minikube image build` on control plane by default

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11192]
Currently there is a lot of duplicated code, between `minikube image load` and `minikube image build`.

One of these includes selecting which minikube nodes (machines) to run on, in the selected profile that is.

This might have some issues with multi-node:

For **load**, it will load the image to all the nodes in the cluster (which makes sense, without a registry)
For **build**, it will build the image on each and every node - which might make less sense, for some builds

For **save**, it would the save the image from each node in the cluster - which doesn't make so much sense.
The regular assumption is that the same image (name:tag) contains the same content, so only save once ?

The suggestion is to build/save on the Control Plane.

See https://github.com/kubernetes/minikube/issues/11130#issuecomment-822670847 for `minikube image save`

----

This is the single-node workflow:

1) Build image on control plane

When the save functionality is in place, that would be a simple method of loading the new image to the other nodes:

1) Build image on control plane
2) Save image from control plane, to the host cache
3) Load image on worker nodes, from the host cache

When having a registry deployed, or when using an external registry, this becomes the usual cluster workflow:

1) Build image on control plane
2) Push image from control plane, to the registry
3) Pull image on worker nodes, from the registry
or)
3a) _Save image from registry, in the host cache_
3b) _Load image on worker nodes, from the host cache_

It would be possible to select another node in the cluster.

```
  -n, --node='': The node to build on. Defaults to the primary control plane.
```

Steps 1+2 would be one single command, `build`.
Same with steps 3, that's also a one-liner `load`.

As always you have the option of building directly on the host (external to minikube), and saving and pushing from there...
But that would mean that you would always have to transfer the image (even for single-node), instead of rapid turnaround.

**Comment by medyagh** [comment]
I agree this is a bug ! that is a good idea to build on only on control plane

**Comment by sharifelgamal** [comment]
Ideally, we could add a `--all` flag for when we want to build an image on all nodes instead of just the control plane

**Comment by afbjorklund** [comment]
Commands:

```
minikube image build --tag myimage .
minikube image save myimage
minikube image load myimage
```
