### ISSUE TITLE
Make host folder sharing configurable

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1119]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

Host folder sharing is a great feature, and it will be even more awesome once we get the embedded 9p server working across the drivers.  We should let users pick the path that gets mounted

**Comment by aaron-prindle** [comment]
Currently the `minikube mount` command takes a directory as an argument:
`minikube mount /path/to/dir`
