### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by akshayshelke18** [kubernetes/minikube#11204]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

 Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.10.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,SystemVerification": Process exited with status 1
stdout:

stderr:
unable to decode config from "/var/tmp/minikube/kubeadm.yaml" [no kind "InitConfiguration" is registered for version "kubeadm.k8s.io/v1alpha3"]

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by ilya-zuyev** [comment]
Hey @akshayshelke18! Please provide: version of minikube, full output of `minikube start` command and information about your OS. Thanks!

**Comment by akshayshelke18** [comment]
Thank You, I have properly installed the minikube now, the error was it was
not supporting the KVM so now I have tried with normal Virtualbox. it's
running fine.
