### ISSUE TITLE
pod-to-pod source IP is lost when using driver=docker with services

### ISSUE THREAD

**Issue by oprudkyi** [kubernetes/minikube#11211]
**Steps to reproduce the issue:** 

1. expose echo server according to https://kubernetes.io/docs/tutorials/services/source-ip/
```
kubectl create deployment source-ip-app --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment source-ip-app --name=clusterip --port=80 --target-port=8080
kubectl expose deployment source-ip-app --name=nodeport --port=80 --target-port=8080 --type=NodePort
```
2.  run from any other pod (expected client address 172.17.0.22)
```
$ ifconfig | grep inet
        inet 172.17.0.22  netmask 255.255.0.0  broadcast 172.17.255.255
$ curl -s http://clusterip | grep client_address
client_address=172.17.0.1
$ curl -s http://nodeport | grep client_address
client_address=172.17.0.1     
```

**Full output of `minikube start` command used, if not already included:**
```
Starting minikube ...
?  minikube v1.16.0 on "Opensuse-Leap" "15.2"
?  Kubernetes 1.20.0 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.20.0
?  Using the docker driver based on existing profile
?  Starting control plane node minikube in cluster minikube
?  Restarting existing docker container for "minikube" ...
?  minikube 1.19.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.19.0
?  To disable this notice, run: 'minikube config set WantUpdateNotification false'

?  Preparing Kubernetes v1.17.13 on Docker 20.10.0 ...
?  Verifying Kubernetes components...
?  Verifying ingress addon...
?  Enabled addons: storage-provisioner, default-storageclass, ingress
?  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

docker is bound to 172.17/16
```
ps ax | grep dockerd
1664603 ?        Ssl    0:02 /usr/bin/dockerd --add-runtime oci=/usr/sbin/docker-runc --ip=172.17.0.1 --insecure-registry 172.30.0.0/16 --storage-driver=overlay2
```

also affected minikube v1.19.0 and k8 version v1.18.16 

we are using ftpd in active mode (i.e. when ftpd connects back to client), it is working in gke and in minikube with driver=none for few years, problem happens only with driver=docker 
also, using direct IP of pod returns correct ip, so it seems only services are affected 
```
$ kubect describe pod source-ip-app-7c79c78698-9x2vs | grep IP:
IP:           172.17.0.14
$ curl -s http://172.17.0.14:8080 | grep client_address
client_address=172.17.0.22
```

**Solution**
suggested by @medyagh
cni driver (tested with  --cni=cilium and  --cni=bridge) fixes the issue, unfortunately it breaks ingress

**Comment by medyagh** [comment]
thank you for creating this issue, I noticed you are using a very old minikube  to use an older kubernetes verison

you could pass --kubernetes-version to specify the k8s version to any minikube verison


@oprudkyi I am curious would enabling CNI would fix this issue ?

minikube start --cni=cilium
or any of these cnis

```
      --cni='': CNI plug-in to use. Valid options: auto, bridge, calico, cilium, flannel, kindnet, or path to a CNI manifest (default: auto)
```

**Comment by oprudkyi** [comment]
Hi @medyagh 
> thank you for creating this issue, I noticed you are using a very old minikube to use 
I am checking with minikube v1.19.0 (and v1.16.0) to be sure it's not some sort of regression 
>an older kubernetes verison
for gke k8 v1.18 in the regular channel https://cloud.google.com/kubernetes-engine/docs/release-notes and I am trying to be close to prod

> @oprudkyi I am curious would enabling CNI would fix this issue ?
> 
> minikube start --cni=cilium
thank you, it does fix the issue with IPs but breaks ingress 
any ideas how to solve ?
```
$ ping 192.168.49.2
PING 192.168.49.2 (192.168.49.2) 56(84) bytes of data.
64 bytes from 192.168.49.2: icmp_seq=1 ttl=64 time=0.052 ms

$ curl https://192.168.49.2 -i -k
curl: (7) Failed to connect to 192.168.49.2 port 443: No route to host

$ ip route | grep 192
192.168.49.0/24 dev br-e0dd7047cc10 proto kernel scope link src 192.168.49.1 

```
i.e. routing works for ping, but doesn't for 443

from minikube it works 
```
$ minikube ssh
$ curl https://192.168.49.2 -k
<!DOCTYPE html> ...

```

**Comment by afbjorklund** [comment]
I think this is a known issue with the Docker bridge.

**Comment by medyagh** [comment]
Glad that  CNI fixes that issue, I am curious did the ingress work with bridge ? ( I assume you are using on Linux ?)

**Comment by oprudkyi** [comment]
@medyagh  I've tried with bridge and cilium and ingress doesn't work for me
also 
- I haven't found way to disable cni without deletion of minikube machine (I suppose it's hard installed into minikube container somehow) 
- the cni breaks something in local system (sysctl/firewall ?) so even after recreation of minikube profile without cni enables ingress , only after reboot ingress start working

**Comment by oprudkyi** [comment]
closing as resolved, it seems cni fixes the issue (but breaks ingress)
