### ISSUE TITLE
start V1.20.1 k8s by minikube fail，no checksum found in，but the link is work on my pc 

### ISSUE THREAD

**Issue by lrul** [kubernetes/minikube#11215]
**重现问题所需的命令**： minikube start --registry-mirror=https://registry.docker-cn.com --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=docker --alsologtostderr -v=8 --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10 --kubernetes-version=1.20.1

**失败的命令的完整输出**：<details>

 Failed to update cluster: updating node: downloading binaries: downloading kubeadm: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm.sha256 Dst:/home/admin/.minikube/cache/linux/v1.20.1/kubeadm.download Pwd: Mode:2 Detectors:[0x2b1e5f8 0x2b1e5f8 0x2b1e5f8 0x2b1e5f8 0x2b1e5f8 0x2b1e5f8] Decompressors:map[bz2:0x2b1e5f8 gz:0x2b1e5f8 tar.bz2:0x2b1e5f8 tar.gz:0x2b1e5f8 tar.xz:0x2b1e5f8 tbz2:0x2b1e5f8 tgz:0x2b1e5f8 txz:0x2b1e5f8 xz:0x2b1e5f8 zip:0x2b1e5f8] Getters:map[file:0xc000836580 http:0xc0007e7780 https:0xc0007e77c0] Dir:false ProgressListener:0x2af6dc0 Options:[0xc1e140]}: invalid checksum: no checksum found in: https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm.sha256
</details>

**`minikube logs`命令的输出**： <details>

==> Docker <==
-- Logs begin at Tue 2021-04-27 10:15:43 UTC, end at Tue 2021-04-27 10:19:23 UTC. --
Apr 27 10:15:55 minikube systemd[1]: Starting Docker Application Container Engine...
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.644450103Z" level=info msg="Starting up"
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.647106634Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.647133559Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.647171954Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.647219413Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.647327807Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0007f19c0, CONNECTING" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.650166938Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0007f19c0, READY" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.651017292Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.651029046Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.651041252Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.651111490Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.651397207Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006d8670, CONNECTING" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.651853010Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006d8670, READY" module=grpc
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.717546433Z" level=info msg="Loading containers: start."
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.823359310Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.861954209Z" level=info msg="Loading containers: done."
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.873851710Z" level=info msg="Docker daemon" commit=6a30dfca03 graphdriver(s)=overlay2 version=19.03.2
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.873938809Z" level=info msg="Daemon has completed initialization"
Apr 27 10:15:55 minikube dockerd[166]: time="2021-04-27T10:15:55.907010100Z" level=info msg="API listen on /run/docker.sock"
Apr 27 10:15:56 minikube systemd[1]: Started Docker Application Container Engine.
Apr 27 10:16:01 minikube systemd[1]: docker.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Apr 27 10:16:03 minikube systemd[1]: Stopping Docker Application Container Engine...
Apr 27 10:16:03 minikube dockerd[166]: time="2021-04-27T10:16:03.261790135Z" level=info msg="Processing signal 'terminated'"
Apr 27 10:16:03 minikube dockerd[166]: time="2021-04-27T10:16:03.263156275Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Apr 27 10:16:03 minikube dockerd[166]: time="2021-04-27T10:16:03.263885742Z" level=info msg="Daemon shutdown complete"
Apr 27 10:16:03 minikube systemd[1]: docker.service: Succeeded.
Apr 27 10:16:03 minikube systemd[1]: Stopped Docker Application Container Engine.
Apr 27 10:16:03 minikube systemd[1]: Starting Docker Application Container Engine...
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.325670098Z" level=info msg="Starting up"
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.327421237Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.327436249Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.327451214Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.327459189Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.327522117Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006b7ba0, CONNECTING" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.328606407Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006b7ba0, READY" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.331622603Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.331637971Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.331666162Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.331673596Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.331709716Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006a4d60, CONNECTING" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.332071812Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006a4d60, READY" module=grpc
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.379665777Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.381463895Z" level=info msg="Loading containers: start."
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.448932766Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.474801168Z" level=info msg="Loading containers: done."
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.486704611Z" level=info msg="Docker daemon" commit=6a30dfca03 graphdriver(s)=overlay2 version=19.03.2
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.486777248Z" level=info msg="Daemon has completed initialization"
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.498863018Z" level=info msg="API listen on [::]:2376"
Apr 27 10:16:03 minikube dockerd[336]: time="2021-04-27T10:16:03.498941286Z" level=info msg="API listen on /var/run/docker.sock"
Apr 27 10:16:03 minikube systemd[1]: Started Docker Application Container Engine.

==> container status <==
time="2021-04-27T10:19:25Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> describe nodes <==
E0427 18:19:26.009369   18670 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.20.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.20.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: /var/lib/minikube/binaries/v1.20.1/kubectl: command not found
 output: "\n** stderr ** \nsudo: /var/lib/minikube/binaries/v1.20.1/kubectl: command not found\n\n** /stderr **"

==> dmesg <==
[Apr27 02:31] ACPI: RSDP 00000000000e0000 00024 (v02 VBOX  )
[  +0.000000] ACPI: XSDT 00000000dfff0030 0003C (v01 VBOX   VBOXXSDT 00000001 ASL  00000061)
[  +0.000000] ACPI: FACP 00000000dfff00f0 000F4 (v04 VBOX   VBOXFACP 00000001 ASL  00000061)
[  +0.000000] ACPI: DSDT 00000000dfff0470 02325 (v02 VBOX   VBOXBIOS 00000002 INTL 20100528)
[  +0.000000] ACPI: FACS 00000000dfff0200 00040
[  +0.000000] ACPI: APIC 00000000dfff0240 0005C (v02 VBOX   VBOXAPIC 00000001 ASL  00000061)
[  +0.000000] ACPI: SSDT 00000000dfff02a0 001CC (v01 VBOX   VBOXCPUT 00000002 INTL 20100528)
[  +0.000000] Zone ranges:
[  +0.000000]   DMA      [mem 0x00001000-0x00ffffff]
[  +0.000000]   DMA32    [mem 0x01000000-0xffffffff]
[  +0.000000]   Normal   [mem 0x100000000-0x11fffffff]
[  +0.000000] Movable zone start for each node
[  +0.000000] Early memory node ranges
[  +0.000000]   node   0: [mem 0x00001000-0x0009efff]
[  +0.000000]   node   0: [mem 0x00100000-0xdffeffff]
[  +0.000000]   node   0: [mem 0x100000000-0x11fffffff]
[  +0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 1032057
[  +0.000000] Policy zone: Normal
[  +0.000000] ACPI: All ACPI Tables successfully acquired
[  +0.169757] ACPI: Executed 1 blocks of module-level executable AML code
[  +0.001608] ACPI: Enabled 2 GPEs in block 00 to 07
[  +0.003002] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[  +0.338999] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[  +1.052295] [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send host log message.
[  +0.000570] [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send host log message.
[  +8.474999] snd_intel8x0 0000:00:05.0: measure - unreliable DMA position..
[  +0.384709] snd_intel8x0 0000:00:05.0: measure - unreliable DMA position..
[  +0.356870] snd_intel8x0 0000:00:05.0: measure - unreliable DMA position..
[  +0.929681] TECH PREVIEW: Overlay filesystem may not be fully supported.
              Please review provided documentation for limitations.
[Apr27 02:45] vboxvideo: loading out-of-tree module taints kernel.
[  +0.031170] vgdrvHeartbeatInit: Setting up heartbeat to trigger every 2000 milliseconds
[  +0.002372] vboxguest: Successfully loaded version 6.1.18
[  +0.000037] vboxguest: misc device minor 58, IRQ 20, I/O port d040, MMIO at 00000000f0400000 (size 0x400000)
[  +0.004170] vboxsf: g_fHostFeatures=0x8000000f g_fSfFeatures=0x1 g_uSfLastFunction=29
[  +0.000103] vboxsf: Successfully loaded version 6.1.18 on 3.10.0-1160.24.1.el7.x86_64 SMP mod_unload modversions  (LINUX_VERSION_CODE=0x30a00)
[  +6.466800] 02:45:38.499139 main     VBoxService 6.1.18 r142142 (verbosity: 0) linux.amd64 (Jan  7 2021 17:26:51) release log
              02:45:38.499142 main     Log opened 2021-04-27T02:45:38.499124000Z
[  +0.000047] 02:45:38.499226 main     OS Product: Linux
[  +0.000022] 02:45:38.499253 main     OS Release: 3.10.0-1160.24.1.el7.x86_64
[  +0.000023] 02:45:38.499275 main     OS Version: #1 SMP Thu Apr 8 19:51:47 UTC 2021
[  +0.000030] 02:45:38.499299 main     Executable: /opt/VBoxGuestAdditions-6.1.18/sbin/VBoxService
              02:45:38.499300 main     Process ID: 29648
              02:45:38.499301 main     Package type: LINUX_64BITS_GENERIC
[  +0.001014] 02:45:38.500310 main     6.1.18 r142142 started. Verbose level = 0
[  +0.001272] 02:45:38.501568 main     vbglR3GuestCtrlDetectPeekGetCancelSupport: Supported (#1)
[  +0.008296] 02:45:38.509821 automount vbsvcAutomounterMountIt: Successfully mounted 'go_example' on '/etc/go_ex'
[Apr27 02:49] 02:49:44.127696 automount vbsvcAutomounterMountIt: Successfully mounted 'kubebuild' on '/home/admin/kubebuild'
[Apr27 06:27] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +1.556304] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Apr27 10:04] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Apr27 10:06] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Apr27 10:13] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Apr27 10:15] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)

==> kernel <==
 10:19:26 up  7:47,  0 users,  load average: 0.15, 0.30, 0.27
Linux minikube 3.10.0-1160.24.1.el7.x86_64 #1 SMP Thu Apr 8 19:51:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 19.10"

==> kubelet <==
-- Logs begin at Tue 2021-04-27 10:15:43 UTC, end at Tue 2021-04-27 10:19:26 UTC. --
-- No entries --

❗  unable to fetch logs for: describe nodes
</details>

**使用的操作系统版本**：
CentOS Linux release 7.9.2009 (Core)

**Comment by ilya-zuyev** [comment]
Hey @lrul, thanks for reporting. Could you check if https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm.sha256 link works on your system?

**Comment by lrul** [comment]
> Hey @lrul, thanks for reporting. Could you check if https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.20.1/bin/linux/amd64/kubeadm.sha256 link works on your system?

i had resolved it by upgrade minikube to latest verison
