### ISSUE TITLE
minikube image build test Flake

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11237]
example

https://storage.googleapis.com/minikube-builds/logs/11233/2e12378/Docker_Linux.html#fail_TestFunctional%2fparallel%2fBuildImage

**Comment by medyagh** [comment]
cc: @afbjorklund

**Comment by afbjorklund** [comment]
I notice that we are running docker build and docker rm at the `same` time, not sure how crash-safe docker is for this ?

**Comment by afbjorklund** [comment]
Then again, maybe not:

```
=== CONT  TestFunctional/parallel/RemoveImage
    functional_test.go:259: (dbg) Done: out/minikube-linux-amd64 -p functional-20210430072953-5799 image load busybox:latest: (1.583674167s)
    functional_test.go:265: (dbg) Run:  out/minikube-linux-amd64 -p functional-20210430072953-5799 image rm busybox:latest
    functional_test.go:301: (dbg) Run:  out/minikube-linux-amd64 ssh -p functional-20210430072953-5799 -- docker images
```


{"Time":"2021-04-30T08:09:13.279041944Z","Action":"output","Test":"TestFunctional/parallel/RemoveImage","Output":"    functional_test.go:265: (dbg) Run:  out/minikube-linux-amd64 -p functional-20210430072953-5799 image rm busybox:latest\n"}

```
=== CONT  TestFunctional/parallel/BuildImage
    functional_test.go:325: (dbg) Done: out/minikube-linux-amd64 -p functional-20210430072953-5799 image build -t localhost/my-image:functional-20210430072953-5799 testdata/build: (3.633341994s)
    functional_test.go:330: (dbg) Stdout: out/minikube-linux-amd64 -p functional-20210430072953-5799 image build -t localhost/my-image:functional-20210430072953-5799 testdata/build:
        Sending build context to Docker daemon  3.072kB

        Step 1/3 : FROM busybox
        latest: Pulling from library/busybox
        f531cdc67389: Pulling fs layer
        f531cdc67389: Verifying Checksum
        f531cdc67389: Download complete
        f531cdc67389: Pull complete
        Digest: sha256:ae39a6f5c07297d7ab64dbd4f82c77c874cc6a94cea29fdec309d0992574b4f7
        Status: Image is up to date for busybox:latest
         ---> 388056c9a683
        Step 2/3 : RUN true
         ---> Running in 4919bfd5dc17
    functional_test.go:333: (dbg) Stderr: out/minikube-linux-amd64 -p functional-20210430072953-5799 image build -t localhost/my-image:functional-20210430072953-5799 testdata/build:
        failed to get digest sha256:388056c9a6838deea3792e8f00705b35b439cf57b3c9c2634fb4e95cfc896de6: open /var/lib/docker/image/overlay2/imagedb/content/sha256/388056c9a6838deea3792e8f00705b35b439cf57b3c9c2634fb4e95cfc896de6: no such file or directory
    functional_test.go:287: (dbg) Run:  out/minikube-linux-amd64 ssh -p functional-20210430072953-5799 -- docker image inspect localhost/my-image:functional-20210430072953-5799
```

{"Time":"2021-04-30T08:09:13.278698675Z","Action":"output","Test":"TestFunctional/parallel/BuildImage","Output":"    functional_test.go:325: (dbg) Run:  out/minikube-linux-amd64 -p functional-20210430072953-5799 image build -t localhost/my-image:functional-20210430072953-5799 testdata/build\n"}
{"Time":"2021-04-30T08:09:13.27910219Z","Action":"output","Test":"TestFunctional/parallel/BuildImage","Output":"    functional_test.go:325: (dbg) Done: out/minikube-linux-amd64 -p functional-20210430072953-5799 image build -t localhost/my-image:functional-20210430072953-5799 testdata/build: (3.633341994s)\n"}

**Comment by afbjorklund** [comment]
I'm experimenting with a new tool to show the test report as a trace:

![report-trace](https://user-images.githubusercontent.com/10364051/116775927-1f183b80-aa66-11eb-96a4-b5645e797137.png)

**Comment by afbjorklund** [comment]
Leaving the original image alone, should fix the failing build.

**Comment by afbjorklund** [comment]
But there is something very wrong in the test json from the functional test:

`{"Time":"2021-04-30T08:09:13.278526026Z","Action":"run","Test":"TestFunctional/parallel/BuildImage"}`

`{"Time":"2021-04-30T08:09:13.287802144Z","Action":"fail","Test":"TestFunctional/parallel/BuildImage","Elapsed":9.28}`

So the timestamps says 9ms (0.009276118000000722s), but the Elapsed says 9.28s ?

According to the log, all test stopped and started on the **same second**: 08:09:13
