### ISSUE TITLE
Guru Meditation is coming every time I try to start minikube in virtual box

### ISSUE THREAD

**Issue by SatishBala** [kubernetes/minikube#11234]
**Steps to reproduce the issue:** 

1. minikube --start --alsologtostderr -v=7
2. 
3.

**Full output of failed command:** 
Please refer the log file
![VBox](https://user-images.githubusercontent.com/37960563/116700343-ab5a2e00-a994-11eb-8dcf-678eec61c18c.png)
[VBox.log](https://github.com/kubernetes/minikube/files/6405570/VBox.log)

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by SatishBala** [comment]
I am running VirtualBox on Mac Mojave (10.14.6). I have uploaded log file for the same issue. Please help. I try to delete all the profiles and still having similar issue.
[VBox.log](https://github.com/kubernetes/minikube/files/6405590/VBox.log)

**Comment by SatishBala** [comment]
Also, I am using fedora 33 in Virtual box

**Comment by afbjorklund** [comment]
Does the same thing happen with minikube (rather than fedora), if you run `minikube start --driver virtualbox` instead of nested ?

**Comment by SatishBala** [comment]
Hi, I try to run the command you mentioned and I got the following

Exiting due to PROVIDER_VIRTUALBOX_NOT_FOUND: The 'virtuabox' provider was not found: unable to find VBoxManage in $PATH.
I am not sure why it is asking to install virtual box..

I am running fedora 33 in Virtual Box as a VM.

**Comment by afbjorklund** [comment]
> I am running fedora 33 in Virtual Box as a VM.

I meant that you should run it on the host instead.

**Comment by andriyDev** [comment]
This issue is quite old, so I will close this issue. If you continue to have the same issue after trying the above solution, feel free to reopen and add more info!
