### ISSUE TITLE
Add --file flag to minikube logs.

### ISSUE THREAD

**Issue by andriyDev** [kubernetes/minikube#11231]
We should have a --file flag in `minikube logs` so that logs output is sent directly to a file for easy transfer.

Before:
```
$ minikube logs
<tons of output>
```
After:
```
$ minikube logs --file out
```
File 'out' written full of logs.

**Comment by spowelljr** [comment]
@medyagh This seems to be the exact same thing as the existing `log_file` flag. Just curious why we're adding another flag that seems to do the same thing

**Comment by andriyDev** [comment]
@spowelljr The trouble with using log_file is that you get logs from the current command interspersed with logs from previous runs which can make it harder to reason about. You also get timestamps on the logged messages which can make it confusing which timestamp you should be looking at.

Another possibility was just doing `minikube logs > debug.log` but the problem there is that some of the logs use ErrT and others use Styled which write to different output streams, so merging that can be confusing. It also may be less portable.

**Comment by spowelljr** [comment]
@andriyDev I wasn't able to see an example of your first point about logs from previous runs. But I see your point about the the timestamps, we definitely don't want those.
