### ISSUE TITLE
Port 53 is taken on V0.16.0

### ISSUE THREAD

**Issue by NickClark** [kubernetes/minikube#1124]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
v0.16.0

**Environment**:

- **OS** (e.g. from /etc/os-release):
MacOS Sierra 10.12.3

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
xhyve

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO`):
minikube-v1.0.6.iso

- **Install tools**:

- **Others**:

**What happened**:
I upgraded to the latest minikube, deleted my vm and recreated it. (I think I upgraded from v0.14.0) Then added back my custom DNS using the normal docker commands. It failed to start due to a port conflict on 53. (I use this custom dnsmasq server for resolving `*.dev` domains for my local projects by adding a specific `nameserver` rule pointing to it in `/etc/resolver/dev` in MacOS, not for internal cluster resolution)

**What you expected to happen**:
I expected to be able to run a docker container on port 53 like on the older minikube versions.

**How to reproduce it** (as minimally and precisely as possible):
```bash
eval $(minikube docker-env)
KUBE_IP=$(minikube ip)
docker run --restart=always --name dnsmasq -d \
	-p 53:53/tcp \
	-p 53:53/udp \
	--cap-add=NET_ADMIN \
	andyshinn/dnsmasq -A /dev/$KUBE_IP
nslookup anything.dev $KUBE_IP # This should resolve to the KUBE_IP
```

**Anything else do we need to know**:

**Comment by r2d4** [comment]
Kube-DNS is taking port 53 running its own dnsmasq  

This is not a great answer, but maybe you can configure that to do what you want or provide your own?  Or you could possibly use something like https://docs.traefik.io/user-guide/kubernetes/

**Comment by NickClark** [comment]
Kube DNS runs on the host port 53? I thought that was only for cluster resolution, and on a different IP/subnet. I do use an ingress already. Not sure how traefik would solve this though.
