### ISSUE TITLE
Use gotestsum to generate minikube integration test JSON

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11249]
The current logs all claim to have been run the same second, with duration in microseconds:

```
{"Time":"2021-05-01T17:13:07.828742425+02:00","Action":"run","Test":"TestFunctional/parallel/BuildImage"}
{"Time":"2021-05-01T17:13:07.8287592+02:00","Action":"pause","Test":"TestFunctional/parallel/BuildImage"}
{"Time":"2021-05-01T17:13:07.828763322+02:00","Action":"cont","Test":"TestFunctional/parallel/BuildImage"}
{"Time":"2021-05-01T17:13:07.828858375+02:00","Action":"pass","Test":"TestFunctional/parallel/BuildImage","Elapsed":0.7}
```

In reality, the tests had rather different timings which can be seen when reading the live output:

```
{"Time":"2021-05-01T17:13:53.877285629+02:00","Action":"run","Test":"TestFunctional/parallel/BuildImage"}
{"Time":"2021-05-01T17:13:53.877327628+02:00","Action":"pause","Test":"TestFunctional/parallel/BuildImage"}
{"Time":"2021-05-01T17:13:53.877331911+02:00","Action":"cont","Test":"TestFunctional/parallel/BuildImage"}
{"Time":"2021-05-01T17:13:54.571565772+02:00","Action":"pass","Test":"TestFunctional/parallel/BuildImage","Elapsed":0.69}
```

The root cause is misusing the `test2json` tool.

Inserting timestamps assumes a _live_ test stream.

**Comment by afbjorklund** [comment]
ping @medyagh

**Comment by afbjorklund** [comment]
This tool looks interesting: https://github.com/gotestyourself/gotestsum

**Comment by afbjorklund** [comment]
Besides fixing JSON, it also looks nicer...

Before: https://asciinema.org/a/411101
After: https://asciinema.org/a/411102

**Comment by medyagh** [comment]
> Besides fixing JSON, it also looks nicer...
> (when just running interactively, that is)
> 
> Before: https://asciinema.org/a/411101
> After: https://asciinema.org/a/411102
> 
> The old formats are still available as well.
> 
> * `standard-quiet` - the standard go test format.
> * `standard-verbose` - the standard go test -v format.
> 
> The JSON also goes into the `--jsonfile`

Could it be used for both unit and integration test?

**Comment by medyagh** [comment]
> This tool looks interesting: https://github.com/gotestyourself/gotestsum
> 
> It would allow outputting both formats (go test, test2json) in the _same_ run.

If this tool can do both, Output to text and json at same time lets do it !

**Comment by afbjorklund** [comment]
> > The JSON also goes into the `--jsonfile`
> 
> Could it be used for both unit and integration test?

I don't see why not. The documentation actually says:

> To convert the output of a "go test" command, use "go test -json" instead of invoking test2json directly.

https://golang.org/cmd/test2json/

We might want to keep `go test` as a fallback, though.

For CI we can install tools like this during the build process, but in the Makefile for running locally I mean.
Just some simple check and some make variables should be enough. Could need one for $(GO) as well.

**Comment by sharifelgamal** [comment]
@andriyDev any interest in working on this?

**Comment by andriyDev** [comment]
I will get around to this.

/assign andriyDev
