### ISSUE TITLE
`minikube config set embed-certs true` does have no effect

### ISSUE THREAD

**Issue by dominikbraun** [kubernetes/minikube#11253]
**Steps to reproduce the issue:** 

1. Run `minikube config set embed-certs true`.
2. Verify that it has been set: `minikube config get embed-certs`
3. Restart minikube.
4. View `$HOME/.kube/config`. There is no field `user.client-certificate-data` in the `minikube` profile.

**Expected behavior**

The certificate should be embedded directly in the `minikube` profile inside `$HOME/.kube/config`.

However, starting the cluster using `minikube start --embed-certs` will work.

**Comment by medyagh** [comment]
@dominikbraun the confit set ... is meant for global config, for all profiles.
I dont think we have a global field for embed-cents in minikube,

but if you think we should be able to set this globally I would be happy to add this to minikube ! And accept any PR that does it.

Also minikube should have Exited with a usage message that That specific config can not be set globally when it just lied and let you set that config without any error while it was not used.

So thank you for filling this issue !  Are you interested in making a contribution to minikube’s code?

**Comment by JacekDuszenko** [comment]
Turns out we do have a global `embed-certs` config field, but the deserialization bug was causing field to be ignored while determining final config during cluster `minikube start`. I fixed it in #11576 and posted more information under the PR. @medyagh feel free to review. Thanks!

**Comment by michaelschem** [comment]
I'm experiencing similar results although based off of the PR it seems like I'm supposed to set `EmbedCerts` instead of `embed-certs`.  Neither work for me. `minikube start --embed-certs` does though.
