### ISSUE TITLE
Minikube keeps on reporting "Unable to fetch image" from remote server while I have the image set up locally

### ISSUE THREAD

**Issue by peidaqi** [kubernetes/minikube#11257]
**Steps to reproduce the issue:** 

I'm testing with this repo: https://github.com/knative/docs/tree/main/docs/serving/samples/hello-world/helloworld-python
And what I did was:

1. Configure docker to use minkube's registry by:
`eval $(minikube -p minikube docker-env)`
2. Build the image with
`docker build -t docker.io/test/helloworld-python .`
3. Now if I run:
`minikube image list`
I will see: docker.io/test/helloworld-python:latest in the list.
4. I have to update the yaml file accordingly by making the lines:
```
      - image: docker.io/test/helloworld-python:latest
        imagePullPolicy: Never

```
5. But when I deploy the service with:
`kubectl create -f service.yaml`

I keep on getting the same error from the log:
`Unable to fetch image "docker.io/test/helloworld-python:latest": failed to resolve image to digest: HEAD https://index.docker.io/v2/test/helloworld-python/manifests/latest: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)`

Is there a document somewhere that details how local registery works with minkube? There seems to be scattered information all over the interent but not sure about the official steps. Below is the version I use:
```
minikube version: v1.19.0
commit: 15cede53bdc5fe242228853e737333b09d4336b5
```

And I'm using Ubuntu 20.04 kernel 5.4.0-72-generic

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by afbjorklund** [comment]
I wouldn't call it a "registry", but the steps taken seems to have been the correct one. Wonder why the deployment doesn't use it.

Normally a registry involves something like "localhost:5000/test/helloworld-python:latest", so we just call this the runtime storage.

**Comment by afbjorklund** [comment]
Wonder if this is something special to Knative ? A regular Service gives the expected

`Container image "docker.io/test/helloworld-python:latest" already present on machine`

**Comment by sharifelgamal** [comment]
Yeah I have definitely been able to use local images for testing just like this before for sure. I wonder if renaming it to something that's not `docker.io` would help.
