### ISSUE TITLE
Test Failure docker containerd test Image Load Flake

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11268]
@afbjorklund docker containerd test, not related?

https://storage.googleapis.com/minikube-builds/logs/11248/6012a8f/Docker_Linux_containerd.html#fail_TestFunctional%2fparallel%2fLoadImage

```

== CONT  TestFunctional/parallel/LoadImage
functional_test.go:301: (dbg) Non-zero exit: out/minikube-linux-amd64 ssh -p functional-20210501121325-6077 -- sudo crictl inspecti docker.io/library/busybox:load-functional-20210501121325-6077: exit status 1 (373.937442ms)
-- stdout --
	[31mFATA[0m[0000] no such image "docker.io/library/busybox:load-functional-20210501121325-6077" present 
-- /stdout --
** stderr ** 
	ssh: Process exited with status 1
** /stderr **

```

_Originally posted by @medyagh in https://github.com/kubernetes/minikube/issues/11248#issuecomment-831372344_

**Comment by dinever** [comment]
Hi,

From my end, it seems like Docker removes the official registry prefix `docker.io/library/` when I try to tag an image:

For example:

```
❯ docker pull busybox:latest
latest: Pulling from library/busybox
Digest: sha256:be4684e4004560b2cd1f12148b7120b0ea69c385bcc9b12a637537a2c60f97fb
Status: Image is up to date for busybox:latest
docker.io/library/busybox:latest

❯ docker tag busybox:latest docker.io/library/busybox:load-functional-20210509050948-6775

❯ docker image ls docker.io/library/busybox:load-functional-20210509050948-6775
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE

❯ docker image ls busybox:load-functional-20210509050948-6775
REPOSITORY   TAG                                   IMAGE ID       CREATED      SIZE
busybox      load-functional-20210509050948-6775   c55b0f125dc6   5 days ago   1.24MB

❯ docker image ls busybox
REPOSITORY   TAG                                   IMAGE ID       CREATED      SIZE
busybox      latest                                c55b0f125dc6   5 days ago   1.24MB
busybox      load-functional-20210509050948-6775   c55b0f125dc6   5 days ago   1.24MB
```

So the functional test couldn't load the image `docker.io/library/busybox:load-functional-20210509050948-6775` because it doesn't exist.

BTW I'm using Docker 20.10.6

**Comment by afbjorklund** [comment]
Yes, it's a problem. We tried to remove it, when looking for the actual image and only match the partial string (short name).

But apparently some places were missed. However, this particular issue is about containerd which does list them (I think).

**Comment by afbjorklund** [comment]
> So the functional test couldn't load the image `docker.io/library/busybox:load-functional-20210509050948-6775` because it doesn't exist.

Even for docker (which this issue is **not** about), you will find that it does exist. It just lies in the list.

```
$ docker image ls docker.io/library/busybox:load-functional-20210509050948-6775
REPOSITORY   TAG       IMAGE ID   CREATED   SIZE
$ docker image inspect docker.io/library/busybox:load-functional-20210509050948-6775 | head -n 3
[
    {
        "Id": "sha256:c55b0f125dc65ee6a9a78307d9a2dfc446e96af7477ca29ddd4945fd398cc698",
```
