### ISSUE TITLE
Overlay driver errors when using minikube with docker-compose

### ISSUE THREAD

**Issue by philipn** [kubernetes/minikube#1130]
**Minikube version** (use `minikube version`): v0.15.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OS X 10.12.2
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO`): minikube-v1.0.2.iso
- **Install tools**:
- **Others**:

**What happened**:

When using minikube alongside `docker-compose`, errors relating to the overlay driver appear. These overlay errors prevent full usage of `docker-compose` while the kubernetes processes are running inside of the minikube VM.

I'm not sure what exactly the root cause of this issue is, but this seems relevant to minikube because making local development easier (and dual usage of `docker` and `docker-compose` alongside `minikube` and the usual K8s services) is a goal of minikube.

Here's what I see when running `docker-compose up` followed by `docker-compose down` followed by `docker-compose build`:

```
ERROR: open /mnt/sda1/var/lib/docker/overlay/47e401fe290e61d20f644c3389da6f8ffb60da30597077ad639ded7ea7de0653/lower-id: no such file or directory
ERROR: open /mnt/sda1/var/lib/docker/overlay/9fe1d235b6af267992c2b7ebebbdc11bdebe4408421ea0ab997df5659e88ba61/lower-id: no such file or directory
```

Similar errors such as the following also appear when running normal docker commands such as `docker rm <id>` (not `rm -f`):

```
Error response from daemon: Driver overlay failed to remove root filesystem a9c48caff3a50e12ea5f88531d60780d351d0b1df1b87f4dc578359a7293cd6a: readdirent: no such file or directory
Error response from daemon: Driver overlay failed to remove root filesystem fed43ccebd6a5161ea3b3a59edc7af19541adc2dcb62c52c6cb2fe4db138b131: readdirent: no such file or directory
Error response from daemon: Driver overlay failed to remove root filesystem 386eb2dcb7639b1e0cbe68988748aa07bcc45c73ba3d3226843e9d15c079646e: readdirent: no such file or directory
Error response from daemon: Driver overlay failed to remove root filesystem f022dc54e68aa465aaef64f6cd0b4c35fb029d04fe2cf224486a9a29ad0a1323: readdirent: no such file or directory
```

**What you expected to happen**:

`docker-compose` should run as usual.

**How to reproduce it** (as minimally and precisely as possible):

I don't have a minimal reproducible test case.  I can consistently reproduce the problem using our local stack.  `docker-compose build` of several containers (taking 5-10 minutes) followed by `docker-compose up` followed by `docker-compose down` followed by `docker-compose up` or `build` will consistently reproduce it with our local containers.

**Anything else do we need to know**:

These errors may be related to the following docker issue: https://github.com/docker/docker/issues/14474.

My first thought was that the Kubernetes container / image garbage collection was interfering with `docker-compose build` commands.  I attempted to disable the garbage collection as follows:

```
minikube start --extra-config=kubelet.MinimumGCAge=30m --extra-config=kublet.ImageMinimumGCAge=30m --extra-config=kublet.minimum_container_ttl_duration=30m
```

My naive testing seemed to indicate that GC'ing wasn't happening with the above options.  But I may have used the wrong flags -- please let me know if so!

I was unable to run using an alternative storage driver, as the only other driver supported by the minikube VM is `vfs`, which appeared to take > 18 hours to build our local dev stack.

**Workaround**:

My workaround has been to stop the `localkube` systemd process and kill all of the kubernetes containers:

```
minikube ssh -- sudo bash -c "'systemctl stop localkube.service && (docker kill \$(docker ps -q) &> /dev/null || true)'"
```

Then I start back up the `localkube` service when I want to do kubernetes-specific local testing.  Our day-to-day development workflow is built on top of `docker-compose`, so we'd like to be able to continue to use compose + minikube if possible.  Another alternative is to run a dedicated docker-machine VM and minikube, but given constrained tiny-laptop-resources, running two VMs is less than ideal.

Running `docker-compose` on the 'raw' minikube docker machine, after killing `localkube`, works as expected.  This leads me to believe that the kubernetes processes are interfering with the functioning of `docker-compose` somehow, perhaps in a way hinted at in the above docker issue.

Unfortunately, I don't know where it would be best to report this issue. But because minikube's goal is to allow local kubernetes + docker development, I figured this was a good starting point.

**Comment by r2d4** [comment]
Thanks for the detailed bug report.  We're investigating this.  Would you be able to give the smallest example that you're able to reproduce this with?  That might help us debug.

**Comment by r2d4** [comment]
Any update on this @philipn ?
