### ISSUE TITLE
Cannot enable registry addons Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for kubernetes.io/minikube-addons=registry pods: timed out waiting for the condition]

### ISSUE THREAD

**Issue by apupier** [kubernetes/minikube#11306]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable registry

**Full output of `minikube logs` command:**
<details>

Cannot provide full due to size and cannot use pastebin because "potentially offensive or questionable content in your paste." so extrating some of the errors:

:1:94: executing "I0506 09:56:49.319017    5837 cli_runner.go:115] Run: docker container inspect -f \"'{{(index (index .NetworkSettings.Ports \"22/tcp\") 0).HostPort}}'\" minikube\n" at <index .NetworkSettings.Ports "22/tcp">: error calling index: index of untyped nil - returning raw string.
I0506 09:56:49.319017    5837 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0506 09:56:49.356817    5837 main.go:126] libmachine: Using SSH client type: native
E0506 10:16:33.583691   23530 out.go:374] unable to parse "I0506 09:56:49.356951    5837 main.go:126] libmachine: &{{{<nil> 0 [] [] []} docker [0x800360] 0x800320 <nil>  [] 0s} 127.0.0.1 49157 <nil> <nil>}\n": template: I0506 09:56:49.356951    5837 main.go:126] libmachine: &{{{<nil> 0 [] [] []} docker [0x800360] 0x800320 <nil>  [] 0s} 127.0.0.1 49157 <nil> <nil>}
:1: unexpected "{" in command - returning raw string.
I0506 09:56:49.356951    5837 main.go:126] libmachine: &{{{<nil> 0 [] [] []} docker [0x800360] 0x800320 <nil>  [] 0s} 127.0.0.1 49157 <nil> <nil>}
I0506 09:56:49.356958    5837 main.go:126] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0506 09:56:49.357887    5837 main.go:126] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:53018->127.0.0.1:49157: read: connection reset by peer

:1:94: executing "I0506 09:57:07.508867    5837 cli_runner.go:115] Run: docker container inspect -f \"'{{(index (index .NetworkSettings.Ports \"22/tcp\") 0).HostPort}}'\" minikube\n" at <index .NetworkSettings.Ports "22/tcp">: error calling index: index of untyped nil - returning raw string.
I0506 09:57:07.508867    5837 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0506 09:57:07.552632    5837 main.go:126] libmachine: Using SSH client type: native
</details>

**Full output of failed command:**
<details>
(base) [apupier@localhost ~]$ minikube addons enable registry --alsologtostderr
I0506 10:37:29.283623   42663 out.go:278] Setting OutFile to fd 1 ...
I0506 10:37:29.283700   42663 out.go:330] isatty.IsTerminal(1) = true
I0506 10:37:29.283710   42663 out.go:291] Setting ErrFile to fd 2...
I0506 10:37:29.283720   42663 out.go:330] isatty.IsTerminal(2) = true
I0506 10:37:29.283830   42663 root.go:317] Updating PATH: /home/apupier/.minikube/bin
W0506 10:37:29.283948   42663 root.go:292] Error reading config file at /home/apupier/.minikube/config/config.json: open /home/apupier/.minikube/config/config.json: no such file or directory
I0506 10:37:29.284243   42663 addons.go:55] Setting registry=true in profile "minikube"
I0506 10:37:29.284262   42663 addons.go:131] Setting addon registry=true in "minikube"
I0506 10:37:29.284286   42663 host.go:66] Checking if "minikube" exists ...
I0506 10:37:29.284790   42663 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
I0506 10:37:29.323064   42663 out.go:157]     ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
    ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
I0506 10:37:29.323138   42663 out.go:157]     ▪ Using image registry:2.7.1
    ▪ Using image registry:2.7.1
I0506 10:37:29.323205   42663 addons.go:261] installing /etc/kubernetes/addons/registry-rc.yaml
I0506 10:37:29.323220   42663 ssh_runner.go:316] scp memory --> /etc/kubernetes/addons/registry-rc.yaml (788 bytes)
I0506 10:37:29.323256   42663 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0506 10:37:29.359339   42663 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:49172 SSHKeyPath:/home/apupier/.minikube/machines/minikube/id_rsa Username:docker}
I0506 10:37:29.484735   42663 addons.go:261] installing /etc/kubernetes/addons/registry-svc.yaml
I0506 10:37:29.484785   42663 ssh_runner.go:316] scp memory --> /etc/kubernetes/addons/registry-svc.yaml (398 bytes)
I0506 10:37:29.519560   42663 addons.go:261] installing /etc/kubernetes/addons/registry-proxy.yaml
I0506 10:37:29.519610   42663 ssh_runner.go:316] scp memory --> /etc/kubernetes/addons/registry-proxy.yaml (950 bytes)
I0506 10:37:29.544579   42663 ssh_runner.go:149] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.20.2/kubectl apply -f /etc/kubernetes/addons/registry-rc.yaml -f /etc/kubernetes/addons/registry-svc.yaml -f /etc/kubernetes/addons/registry-proxy.yaml
I0506 10:37:29.752006   42663 addons.go:299] Verifying addon registry=true in "minikube"
I0506 10:37:29.752163   42663 out.go:157] 🔎  Verifying registry addon...
🔎  Verifying registry addon...
I0506 10:37:29.768587   42663 kapi.go:75] Waiting for pod with label "kubernetes.io/minikube-addons=registry" in ns "kube-system" ...
I0506 10:37:29.781216   42663 kapi.go:86] Found 2 Pods for label selector kubernetes.io/minikube-addons=registry
I0506 10:37:29.781239   42663 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0506 10:37:30.285556   42663 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0506 10:37:30.852652   42663 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]

[...] a lot of other times the same line

I0506 10:43:29.285403   42663 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0506 10:43:29.785402   42663 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0506 10:43:29.788406   42663 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0506 10:43:29.788437   42663 kapi.go:108] duration metric: took 6m0.019854174s to wait for kubernetes.io/minikube-addons=registry ...
I0506 10:43:29.788754   42663 out.go:157] 

W0506 10:43:29.788963   42663 out.go:222] ❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for kubernetes.io/minikube-addons=registry pods: timed out waiting for the condition]
❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for kubernetes.io/minikube-addons=registry pods: timed out waiting for the condition]
W0506 10:43:29.789083   42663 out.go:222] 

W0506 10:43:29.789133   42663 out.go:222] 😿  If the above advice does not help, please let us know: 
😿  If the above advice does not help, please let us know: 
W0506 10:43:29.789178   42663 out.go:222] 👉  https://github.com/kubernetes/minikube/issues/new/choose
👉  https://github.com/kubernetes/minikube/issues/new/choose
I0506 10:43:29.789244   42663 out.go:157] 

</details>

it started to fail yesterday. i was with minikube 1.18.1. I upgraded today and still failing.
I notice this error in the registry node log:
```
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  15m                  default-scheduler  Successfully assigned kube-system/registry-xtmr7 to minikube
  Normal   Pulling    11m (x4 over 15m)    kubelet            Pulling image "registry:2.7.1@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa"
  Warning  Failed     10m (x4 over 15m)    kubelet            Error: ErrImagePull
  Warning  Failed     10m (x7 over 15m)    kubelet            Error: ImagePullBackOff
  Warning  Failed     5m37s (x6 over 15m)  kubelet            Failed to pull image "registry:2.7.1@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   BackOff    41s (x44 over 15m)   kubelet            Back-off pulling image "registry:2.7.1@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa"
```

**Comment by medyagh** [comment]
@apupier mind sharing what OS and versions are u on ? 

it seems like you can not Pull form docker hub, do u have any network restriction ? or maybe pull limit ?

```
 Failed to pull image "registry:2.7.1@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```

can you verify manually if u can pull that image ? what do u get for this ?
```
docker pull registry:2.7.1@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa
```

**Comment by apupier** [comment]
> mind sharing what OS and versions are u on ?

Fedora 33
minikube 1.19.0

```
(base) [apupier@linux ~]$ docker pull registry:2.7.1@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa
docker.io/library/registry@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa: Pulling from library/registry
0a6724ff3fcd: Pull complete 
d550a247d74f: Pull complete 
1a938458ca36: Pull complete 
acd758c36fc9: Pull complete 
9af6d68b484a: Pull complete 
Digest: sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa
Status: Downloaded newer image for registry@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa
docker.io/library/registry:2.7.1@sha256:d5459fcb27aecc752520df4b492b08358a1912fcdfa454f7d2101d4b09991daa
```

and it is working now:
```
(base) [apupier@linux minikube]$ minikube addons enable registry
    ▪ Using image registry:2.7.1
    ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
🔎  Verifying registry addon...
🌟  The 'registry' addon is enabled
```

> it seems like you can not Pull form docker hub, do u have any network restriction ? or maybe pull limit ?

I have no network restriction. So it was likely a matter of pull limit

@medyagh thanks for having taken the time to look at it.

**Comment by medyagh** [comment]
I feel like minikube should had done a better job giving a more user friendly solution telling the user we couldn't network wise pull an image...

@apupier would you be interested to make minikube better ? maybe contribute a better message for exit ?
