### ISSUE TITLE
vmware driver not working

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes/minikube#11308]
minikube start --alsologtostderr -v=7
I0506 15:08:18.175744   23728 out.go:278] Setting OutFile to fd 84 ...
I0506 15:08:18.175744   23728 out.go:291] Setting ErrFile to fd 88...
W0506 15:08:18.191730   23728 root.go:292] Error reading config file at C:\Users\UReddy\.minikube\config\config.json: open C:\Users\UReddy\.minikube\config\config.json: The system cannot find the file specified.
I0506 15:08:18.191730   23728 out.go:285] Setting JSON to false
I0506 15:08:18.199725   23728 start.go:108] hostinfo: {"hostname":"Q1V2M063","uptime":157540,"bootTime":1620136358,"procs":291,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.19042 Build 19042","kernelVersion":"10.0.19042 Build 19042","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"c6de315e-9ff1-46df-adac-42aa05400708"}
W0506 15:08:18.199725   23728 start.go:116] gopshost.Virtualization returned error: not implemented yet
I0506 15:08:18.199725   23728 out.go:157] 😄  minikube v1.19.0 on Microsoft Windows 10 Pro 10.0.19042 Build 19042
😄  minikube v1.19.0 on Microsoft Windows 10 Pro 10.0.19042 Build 19042
I0506 15:08:18.199725   23728 notify.go:126] Checking for updates...
I0506 15:08:18.199725   23728 driver.go:322] Setting default libvirt URI to qemu:///system
I0506 15:08:18.199725   23728 global.go:103] Querying for installed drivers using PATH=C:\Program Files (x86)\VMware\VMware Workstation\bin\;C:\Program Files\Python39\Scripts\;C:\Program Files\Python39\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\flutter\bin;C:\HashiCorp\Vagrant\bin;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Users\UReddy\AppData\Local\Microsoft\WindowsApps;D:\softwares\sqllite\sqlite-tools-win32-x86-3350500;C:\Users\UReddy\AppData\Roaming\npm
I0506 15:08:18.216305   23728 global.go:111] docker default: true priority: 9, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "docker": executable file not found in %PATH% Reason: Fix:Install Docker Doc:https://minikube.sigs.k8s.io/docs/drivers/docker/}
I0506 15:08:18.475397   23728 global.go:111] hyperv default: true priority: 8, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent returned "False\r\n" Reason: Fix:Enable Hyper-V: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All' Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/}
I0506 15:08:18.484503   23728 global.go:111] podman default: true priority: 3, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "podman": executable file not found in %PATH% Reason: Fix:Install Podman Doc:https://minikube.sigs.k8s.io/docs/drivers/podman/}
I0506 15:08:18.484503   23728 global.go:111] ssh default: false priority: 4, state: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0506 15:08:18.502213   23728 global.go:111] virtualbox default: true priority: 6, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:unable to find VBoxManage in $PATH Reason: Fix:Install VirtualBox Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/}
I0506 15:08:18.512493   23728 global.go:111] vmware default: true priority: 7, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "vmrun": executable file not found in %PATH% Reason: Fix:Install vmrun Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/}
I0506 15:08:18.513035   23728 driver.go:258] not recommending "ssh" due to default: false
I0506 15:08:18.513035   23728 driver.go:292] Picked:
I0506 15:08:18.513035   23728 driver.go:293] Alternatives: [ssh]
I0506 15:08:18.513035   23728 driver.go:294] Rejects: [docker hyperv podman virtualbox vmware]
I0506 15:08:18.515720   23728 out.go:157] 👎  Unable to pick a default driver. Here is what was considered, in preference order:
👎  Unable to pick a default driver. Here is what was considered, in preference order:
I0506 15:08:18.516784   23728 out.go:157]     ▪ docker: Not installed: exec: "docker": executable file not found in %PATH%
    ▪ docker: Not installed: exec: "docker": executable file not found in %PATH%
I0506 15:08:18.517847   23728 out.go:157]     ▪ hyperv: Not installed: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent returned "False\r\n"
    ▪ hyperv: Not installed: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent returned "False\r\n"
I0506 15:08:18.518888   23728 out.go:157]     ▪ podman: Not installed: exec: "podman": executable file not found in %PATH%
    ▪ podman: Not installed: exec: "podman": executable file not found in %PATH%
I0506 15:08:18.518888   23728 out.go:157]     ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH
    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH
I0506 15:08:18.520434   23728 out.go:157]     ▪ vmware: Not installed: exec: "vmrun": executable file not found in %PATH%
    ▪ vmware: Not installed: exec: "vmrun": executable file not found in %PATH%
I0506 15:08:18.520434   23728 out.go:157]

W0506 15:08:18.520434   23728 out.go:222] ❌  Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/
❌  Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/
I0506 15:08:18.520434   23728 out.go:157]

PS C:\Users\UReddy>

**Comment by afbjorklund** [comment]
Have you installed VMware ? It claims it cannot find `vmrun`

You also need the `docker-machine-driver-vmware`

**Comment by ukreddy-erwin** [comment]
yes it is installed, it seems we need to set the path variable to the vmrun folder. It is not picking directly from the installation folder.Thanks for your reply. And one more thing, minikube VM is not showing in the vmware workstation GUI, is there any option to show it?

**Comment by afbjorklund** [comment]
Might need a modification to the driver ? Not sure if it is created "hidden" somehow

For VirtualBox, the machines created by minikube are visible in the VirtualBox GUI

**Comment by ukreddy-erwin** [comment]
> @ukreddy-erwin do u sill have this issue ?
> do u mind trying with latest verison and try agian? minikube delete --all

I tried just now, still same
