### ISSUE TITLE
 Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in %PATH%

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes/minikube#11307]
Latest version of vmware workstation is installed on the machine.
Windows 10 pro.

But, the vmware workstation driver is not getting detected..

The output of command: minikube start --driver vmware
😄  minikube v1.19.0 on Microsoft Windows 10 Pro 10.0.19042 Build 19042
✨  Using the vmware driver based on user configuration

🤷  Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in %PATH%
💡  Suggestion: Install vmrun
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

PS C:\Users\UReddy> minikube version
minikube version: v1.19.0
commit: 15cede53bdc5fe242228853e737333b09d4336b5

**Comment by afbjorklund** [comment]
Might need an issue opened upstream: https://github.com/machine-drivers/docker-machine-driver-vmware

**Comment by ukreddy-erwin** [comment]
Fixed by setting path variable to C:\Program Files (x86)\VMware\VMware Workstation
