### ISSUE TITLE
Docs: Please highlight the current page in the list on the left side

### ISSUE THREAD

**Issue by guettli** [kubernetes/minikube#11326]
Docs: Please highlight the current page in the list on the left side

See screenshot:

![image](https://user-images.githubusercontent.com/414336/117460543-e9cf8a00-af4c-11eb-8abd-ae4be1f03b95.png)

**Comment by dinever** [comment]
Working on this

/assign

**Comment by dinever** [comment]
This has been fixed in #11341. I forgot to mention this issue in the PR. @medyagh could you help close this? Thanks!
