### ISSUE TITLE
I am trying to run terraform as a container in minikube but the container is getting crash loop back This is the cmdlet i am using kubectl create deployment terraform --image=hashicorp/terraform:light please suggest how to resolve this

### ISSUE THREAD

**Issue by AbhuSteyn** [kubernetes/minikube#11324]
I am trying to run terraform as a container in minikube but the container is getting crash loop back This is the cmdlet i am using kubectl create deployment terraform --image=hashicorp/terraform:light please suggest how to resolve this

**Comment by medyagh** [comment]
@AbhuSteyn this doesnt seem to be a minikube issue, and without proper logs I cant help with this

I suggest getting support from kubernetes-users slack channell for how to use kubernetes
