### ISSUE TITLE
Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2

### ISSUE THREAD

**Issue by Laxminarayan1502** [kubernetes/minikube#11323]
**Steps to reproduce the issue:** 
I am trying to install kubernetes and minikube on amazon ec2 linux instance. when i am triggering the below CLI it is throwing error" Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2"

minikube start --driver=none

Please help in resolving the issue.

**Full output of `minikube logs` command:**
<details>
 minikube logs
*
* ==> Audit <==
* |---------|------|---------|------|---------|------------|----------|
| Command | Args | Profile | User | Version | Start Time | End Time |
|---------|------|---------|------|---------|------------|----------|
|---------|------|---------|------|---------|------------|----------|

*
* ==> Last Start <==
* Log file created at: 2021/05/07 11:12:52
Running on machine: ip-172-31-40-142
Binary: Built with gc go1.16.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0507 11:12:52.160284   61178 out.go:291] Setting OutFile to fd 1 ...
I0507 11:12:52.160434   61178 out.go:338] TERM=xterm,COLORTERM=, which probably does not support color
I0507 11:12:52.160439   61178 out.go:304] Setting ErrFile to fd 2...
I0507 11:12:52.160444   61178 out.go:338] TERM=xterm,COLORTERM=, which probably does not support color
I0507 11:12:52.160586   61178 root.go:316] Updating PATH: /home/ec2-user/.minikube/bin
W0507 11:12:52.160715   61178 root.go:291] Error reading config file at /home/ec2-user/.minikube/config/config.json: open /home/ec2-user/.minikube/config/config.json: no such file or directory
I0507 11:12:52.160851   61178 out.go:298] Setting JSON to false
I0507 11:12:52.162383   61178 start.go:108] hostinfo: {"hostname":"ip-172-31-40-142.ap-south-1.compute.internal","uptime":1921,"bootTime":1620384051,"procs":101,"os":"linux","platform":"redhat","platformFamily":"rhel","platformVersion":"8.3","kernelVersion":"4.18.0-240.1.1.el8_3.x86_64","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"33189548-bfda-4fdf-a666-97d273e78b7b"}
I0507 11:12:52.162480   61178 start.go:118] virtualization: xen guest
I0507 11:12:52.164376   61178 out.go:170] * minikube v1.20.0 on Redhat 8.3 (xen/amd64)
I0507 11:12:52.165194   61178 exec_runner.go:52] Run: systemctl --version
I0507 11:12:52.165314   61178 notify.go:169] Checking for updates...
I0507 11:12:52.171147   61178 driver.go:322] Setting default libvirt URI to qemu:///system
I0507 11:12:52.190683   61178 out.go:170] * Using the none driver based on existing profile
I0507 11:12:52.190722   61178 start.go:276] selected driver: none
I0507 11:12:52.190729   61178 start.go:718] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.40.142 Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false}
I0507 11:12:52.190826   61178 start.go:729] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0507 11:12:52.191369   61178 cni.go:93] Creating CNI manager for ""
I0507 11:12:52.191377   61178 cni.go:147] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0507 11:12:52.191384   61178 start_flags.go:273] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.40.142 Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false}
I0507 11:12:52.192808   61178 out.go:170] * Starting control plane node minikube in cluster minikube
I0507 11:12:52.192920   61178 profile.go:148] Saving config to /home/ec2-user/.minikube/profiles/minikube/config.json ...
I0507 11:12:52.193148   61178 cache.go:194] Successfully downloaded all kic artifacts
I0507 11:12:52.193178   61178 start.go:313] acquiring machines lock for minikube: {Name:mkc69c5e218853d090d0ab1d731ba22f29102a47 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0507 11:12:52.193456   61178 start.go:317] acquired machines lock for "minikube" in 262.099µs
I0507 11:12:52.193494   61178 start.go:93] Skipping create...Using existing machine configuration
I0507 11:12:52.193501   61178 fix.go:55] fixHost starting: m01
W0507 11:12:52.193726   61178 none.go:130] unable to get port: "minikube" does not appear in /home/ec2-user/.kube/config
I0507 11:12:52.193745   61178 api_server.go:148] Checking apiserver status ...
I0507 11:12:52.193771   61178 exec_runner.go:52] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0507 11:12:52.219246   61178 api_server.go:152] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0507 11:12:52.219301   61178 exec_runner.go:52] Run: sudo systemctl is-active --quiet service kubelet
I0507 11:12:52.260845   61178 fix.go:108] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0507 11:12:52.260862   61178 fix.go:134] unexpected machine state, will restart: <nil>
I0507 11:12:52.262251   61178 out.go:170] * Restarting existing none bare metal machine for "minikube" ...
I0507 11:12:52.264763   61178 profile.go:148] Saving config to /home/ec2-user/.minikube/profiles/minikube/config.json ...
I0507 11:12:52.264917   61178 start.go:267] post-start starting for "minikube" (driver="none")
I0507 11:12:52.264927   61178 start.go:277] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0507 11:12:52.264978   61178 exec_runner.go:52] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0507 11:12:52.283556   61178 main.go:128] libmachine: Couldn't set key PLATFORM_ID, no corresponding struct field found
I0507 11:12:52.283580   61178 main.go:128] libmachine: Couldn't set key CPE_NAME, no corresponding struct field found
I0507 11:12:52.283595   61178 main.go:128] libmachine: Couldn't set key , no corresponding struct field found
I0507 11:12:52.283605   61178 main.go:128] libmachine: Couldn't set key REDHAT_BUGZILLA_PRODUCT, no corresponding struct field found
I0507 11:12:52.283616   61178 main.go:128] libmachine: Couldn't set key REDHAT_BUGZILLA_PRODUCT_VERSION, no corresponding struct field found
I0507 11:12:52.283627   61178 main.go:128] libmachine: Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
I0507 11:12:52.283637   61178 main.go:128] libmachine: Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
I0507 11:12:52.285832   61178 out.go:170] * OS release is Red Hat Enterprise Linux 8.3 (Ootpa)
I0507 11:12:52.285866   61178 filesync.go:118] Scanning /home/ec2-user/.minikube/addons for local assets ...
I0507 11:12:52.285905   61178 filesync.go:118] Scanning /home/ec2-user/.minikube/files for local assets ...
I0507 11:12:52.285927   61178 start.go:270] post-start completed in 20.998971ms
I0507 11:12:52.285937   61178 fix.go:95] none is local, skipping auth/time setup (requires ssh)
I0507 11:12:52.285942   61178 fix.go:57] fixHost completed within 92.442586ms
I0507 11:12:52.285948   61178 start.go:80] releasing machines lock for "minikube", held for 92.464972ms
I0507 11:12:52.286392   61178 exec_runner.go:52] Run: sudo systemctl is-active --quiet service containerd
I0507 11:12:52.286568   61178 exec_runner.go:52] Run: curl -sS -m 2 https://k8s.gcr.io/
I0507 11:12:52.309912   61178 exec_runner.go:52] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/dockershim.sock
image-endpoint: unix:///var/run/dockershim.sock
" | sudo tee /etc/crictl.yaml"
I0507 11:12:52.343705   61178 exec_runner.go:52] Run: sudo systemctl unmask docker.service
I0507 11:12:52.507947   61178 exec_runner.go:52] Run: sudo systemctl enable docker.socket
I0507 11:12:52.668212   61178 exec_runner.go:52] Run: sudo systemctl cat docker.service
I0507 11:12:52.694261   61178 exec_runner.go:52] Run: sudo systemctl daemon-reload
I0507 11:12:52.851693   61178 exec_runner.go:52] Run: sudo systemctl restart docker
I0507 11:12:53.165163   61178 exec_runner.go:52] Run: docker version --format {{.Server.Version}}
I0507 11:12:53.213472   61178 out.go:197] * Preparing Kubernetes v1.20.2 on Docker  ...
I0507 11:12:53.213847   61178 exec_runner.go:52] Run: grep 127.0.0.1    host.minikube.internal$ /etc/hosts
I0507 11:12:53.215509   61178 preload.go:98] Checking if preload exists for k8s version v1.20.2 and runtime docker
I0507 11:12:53.490617   61178 preload.go:123] Found remote preload: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.lz4
I0507 11:12:53.490724   61178 exec_runner.go:52] Run: docker images --format {{.Repository}}:{{.Tag}}
I0507 11:12:53.533568   61178 exec_runner.go:52] Run: sudo cat /var/lib/docker/image/overlay2/repositories.json
I0507 11:12:53.554984   61178 exec_runner.go:52] Run: which lz4
I0507 11:12:53.555697   61178 kubeadm.go:862] preload failed, will try to load cached images: lz4
I0507 11:12:53.555740   61178 exec_runner.go:52] Run: docker info --format {{.CgroupDriver}}
I0507 11:12:53.647717   61178 exec_runner.go:52] Run: sudo systemctl is-active --quiet service docker
I0507 11:12:53.676706   61178 out.go:170]
W0507 11:12:53.676886   61178 out.go:235] X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
        panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc00055d2a8)
        /usr/local/go/src/text/template/exec.go:170 +0x1b5
panic(0x55fd26ab97a0, 0x55fd26dfaae0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x55fd26c72780, 0xc0003260c0, 0x99, 0xc000126bb0, 0x2, 0x2, 0x0, 0x55fd26eb1da0, 0x55fd26ab97a0)
        /usr/local/go/src/reflect/value.go:883 +0x39e
text/template.(*state).evalField(0xc00055d228, 0x55fd26c72780, 0xc0003260c0, 0x99, 0x7ffeea4af6e8, 0xc, 0x55fd26e82ba0, 0xc00013b050, 0xc0002780b0, 0x1, ...)
        /usr/local/go/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc00055d228, 0x55fd26c72780, 0xc0003260c0, 0x99, 0x55fd26c72780, 0xc0003260c0, 0x99, 0x55fd26e82ba0, 0xc00013b050, 0xc0002780a0, ...)
        /usr/local/go/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc00055d228, 0x55fd26c72780, 0xc0003260c0, 0x99, 0xc00013b050, 0xc0002780b0, 0x1, 0x1, 0x55fd26b5e4e0, 0x55fd27eae9c8, ...)
        /usr/local/go/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc00055d228, 0x55fd26c72780, 0xc0003260c0, 0x99, 0xc00013af00, 0x55fd26b5e4e0, 0x55fd27eae9c8, 0x99, 0xd0, 0x55fd26c52360, ...)
        /usr/local/go/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc00055d228, 0x55fd26c72780, 0xc0003260c0, 0x99, 0xc00009a300, 0xc0000fa238, 0xc0000b0340, 0xc00055d0e0)
        /usr/local/go/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc00055d228, 0x55fd26c72780, 0xc0003260c0, 0x99, 0x55fd26e82a20, 0xc00013b0e0)
        /usr/local/go/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc00055d228, 0x55fd26c72780, 0xc0003260c0, 0x99, 0x55fd26e82c60, 0xc00013ae70)
        /usr/local/go/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc000326040, 0x55fd26e1c4a0, 0xc00022dad0, 0x55fd26c72780, 0xc0003260c0, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x55fd26eacac0, 0xc0003f56c0, 0x0, 0xc0003dd300, 0x1, 0x1, 0xc0002b5e00, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/system/info.go:490 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc000560840, 0x55fd26eacac0, 0xc0003f56c0, 0xc0003dcbe0, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x37c
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc000560840, 0xc0005808e0, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000560840, 0xc000565720, 0x2, 0x2, 0xc000560840, 0xc000565720)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003f3b80, 0xc000565710, 0x3, 0x3)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc0003f56c0, 0x55fd26e1eac0, 0xc000010020)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3

W0507 11:12:53.676980   61178 out.go:424] no arguments passed for "* \n" - returning raw string
W0507 11:12:53.676995   61178 out.go:235] *
W0507 11:12:53.677010   61178 out.go:424] no arguments passed for "* If the above advice does not help, please let us know:\n" - returning raw string
W0507 11:12:53.677015   61178 out.go:424] no arguments passed for "  https://github.com/kubernetes/minikube/issues/new/choose\n\n" - returning raw string
W0507 11:12:53.677021   61178 out.go:424] no arguments passed for "* Please attach the following file to the GitHub issue:\n" - returning raw string
W0507 11:12:53.677081   61178 out.go:424] no arguments passed for "* If the above advice does not help, please let us know:\n  https://github.com/kubernetes/minikube/issues/new/choose\n\n* Please attach the following file to the GitHub issue:\n* - /home/ec2-user/.minikube/logs/lastStart.txt\n\n" - returning raw string
W0507 11:12:53.678045   61178 out.go:235] ╭──────────────────────────────────────────────────────────────────╮
W0507 11:12:53.678060   61178 out.go:235] │                                                                  │
W0507 11:12:53.678067   61178 out.go:235] │    * If the above advice does not help, please let us know:      │
W0507 11:12:53.678073   61178 out.go:235] │      https://github.com/kubernetes/minikube/issues/new/choose    │
W0507 11:12:53.678084   61178 out.go:235] │                                                                  │
W0507 11:12:53.678091   61178 out.go:235] │    * Please attach the following file to the GitHub issue:       │
W0507 11:12:53.678097   61178 out.go:235] │    * - /home/ec2-user/.minikube/logs/lastStart.txt               │
W0507 11:12:53.678102   61178 out.go:235] │                                                                  │
W0507 11:12:53.678110   61178 out.go:235] ╰──────────────────────────────────────────────────────────────────╯
W0507 11:12:53.678117   61178 out.go:235]

*
* The control plane node must be running for this command
  To start a cluster, run: "minikube start"

</details>

**Full output of failed command:**
<details>

</details>

**Comment by medyagh** [comment]
@Laxminarayan1502 do u have same problem with Docker driver ?
```
minikube start --driver=docker
```

**Comment by afbjorklund** [comment]
Most likely a duplicate of https://github.com/kubernetes/minikube/issues/10165, docker does this panic when daemon is not running

**Comment by spowelljr** [comment]
Hi @Laxminarayan1502, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
