### ISSUE TITLE
apiserver-ips option is not working

### ISSUE THREAD

**Issue by gtolarc** [kubernetes/minikube#11320]
Even if you run as follows, apiserver ip does not change from the default. Is this a bug?

```bash
minikube start --apiserver-ips=192.168.1.5
```

<img width="537" alt="스크린샷 2021-05-07 오후 2 29 10" src="https://user-images.githubusercontent.com/8623798/117402036-9bb48980-af40-11eb-97ef-fa41add4a601.png">

**Comment by medyagh** [comment]
@gtolarc that is the external IP of the api server, the right way to verify the IP is

```
$ kubectl get pod -o wide -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE   IP             NODE       NOMINATED NODE   READINESS GATES
kube-system   coredns-74ff55c5b-cs7kp            1/1     Running   0          25s   172.17.0.2     minikube   <none>           <none>
kube-system   etcd-minikube                      0/1     Running   0          37s   192.168.49.2   minikube   <none>           <none>
kube-system   kube-apiserver-minikube            1/1     Running   0          37s   192.168.49.2   minikube   <none>           <none>
kube-system   kube-controller-manager-minikube   0/1     Running   0          37s   192.168.49.2   minikube   <none>           <none>
kube-system   kube-proxy-ljtcm                   1/1     Running   0          25s   192.168.49.2   minikube   <none>           <none>
kube-system   kube-scheduler-minikube            0/1     Running   0          37s   192.168.49.2   minikube   <none>           <none>
```

but it does seem like it is a bug and we are not setting the api-sever IP

**Comment by medyagh** [comment]
@gtolarc do u mind sharing why do u need to share the api-server ip inside minikube ? why would that be important ?

if this is really needed  I would accept a PR that allows users setting their own api-server ip

**Comment by gtolarc** [comment]
In my case, because istio cannot be installed on m1 silicon macbook. I want to access kubernete installed on another intel computer on the same local network. @medyagh

**Comment by rvarner** [comment]
I am also seeing this behavior. Setting --apiserver-ip and --apiserver-port does not get reflected in my kubeconfig, nor is the control plane accessible from outside localhost. My use-case is to have a CI/CD (jenkins) pipeline dynamically launch agents in the cluster. Jenkins is deployed externally to minikube.

**Comment by medyagh** [comment]
@gtolarc does this help ? https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network

**Comment by sharifelgamal** [comment]
The [ssh driver](https://minikube.sigs.k8s.io/docs/drivers/ssh/) might also be an option here.

**Comment by Sn-Kinos** [comment]
> @gtolarc does this help ? https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network

I had spend almost 2 days for it... thank you so much 😭

**Comment by klaases** [comment]
Hi @gtolarc, did the [link](https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network) that @medyagh provided above work for you as well?

Also, @[Sn-Kinos](https://github.com/Sn-Kinos) mentioned that this helped with the issue as well.

**Comment by klaases** [comment]
Hi @gtolarc  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by puravpanchal** [comment]
Hey guys, I would like to connect Jenkins which is running on an external server with Kubernetes installed using minikube on a vm of another server. I am struggling to change and access the api-server. Thank you in advance :)
