### ISSUE TITLE
Support `cp` between minikube nodes

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#11336]
Related to https://github.com/kubernetes/minikube/issues/11296

It would be nice to have an ability to copy files not only between the host and a node, but also between minikube nodes

`minikube cp node1:/tmp/foo node2:/tmp/bar`

**Comment by spowelljr** [comment]
@daehyeok Are you still working on this issue?

**Comment by daehyeok** [comment]
@spowelljr  sorry didn't take care of this issues long time. i updated my PR for this isseus
