### ISSUE TITLE
fix TestPause/serial/* tests for docker driver with containerd runtime

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#11332]
These three failures seem related:

https://storage.googleapis.com/minikube-builds/logs/master/c31bd57/Docker_Linux_containerd.html#fail_TestPause%2fserial%2fPause
https://storage.googleapis.com/minikube-builds/logs/master/c31bd57/Docker_Linux_containerd.html#fail_TestPause%2fserial%2fPauseAgain
https://storage.googleapis.com/minikube-builds/logs/master/c31bd57/Docker_Linux_containerd.html#fail_TestPause%2fserial%2fVerifyStatus

Full log: https://storage.googleapis.com/minikube-builds/logs/master/c31bd57/Docker_Linux_containerdout.txt

**Comment by medyagh** [comment]
how about we stop the containers before we delete minikube so it doesnt hang
