### ISSUE TITLE
fix TestFunctional/parallel/LoadImage for docker driver with containerd runtime

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#11330]
TestFunctional/parallel/LoadImage is failing for docker/containerd 

Example of logs: 
https://storage.googleapis.com/minikube-builds/logs/master/c31bd57/Docker_Linux_containerd.html#fail_TestFunctional%2fparallel%2fLoadImage
Full log: https://storage.googleapis.com/minikube-builds/logs/master/c31bd57/Docker_Linux_containerdout.txt

`minikube image load <image>` returns ok, but then `minikue ssh  -- sudo crictl inspecti <image>` can not find the image.

**Comment by spowelljr** [comment]
Steps to reproduce:
```
docker pull busybox:latest
docker tag busybox:latest docker.io/library/busybox:load-minikube
docker tag busybox:latest docker.io/library/busybox:remove-minikube
minikube image load docker.io/library/busybox:load-minikube
minikube image load docker.io/library/busybox:remove-minikube
minikube ssh -p minikube -- sudo crictl inspecti docker.io/library/busybox:load-minikube
// image exists
minikube image rm docker.io/library/busybox:remove-minikube
minikube ssh -p minikube -- sudo crictl inspecti docker.io/library/busybox:load-minikube
// image now doesn't exist
```
It seems if you have two images loaded with the same image ID, containerd removes all images matching the image ID.

**Comment by spowelljr** [comment]
The reason this is flaky is it depends on the timing between the `LoadImage` and `RemoveImage` tests.
