### ISSUE TITLE
/Users not available after minikube stop and start

### ISSUE THREAD

**Issue by justechn** [kubernetes/minikube#1133]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Minikube version** (use `minikube version`):
minikube version: v0.16.0

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS Sierra version 10.12.3
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "xhyve",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO`): that command does not return anything
- **Install tools**:
- **Others**:

**What happened**:
When I run `minikube start --vm-driver=xhyve` and then run `minikube ssh` and `ls -ll /` I see the following

```
total 5
drwxr-xr-x    1 rkt      staff          238 Jan 30 17:16 Users
lrwxrwxrwx    1 root     root             7 Feb  8 19:26 bin -> usr/bin
lrwxrwxrwx    1 root     root            14 Feb 16 00:22 data -> /mnt/sda1/data
drwxr-xr-x   15 root     root          3020 Feb 16 00:22 dev
drwxr-xr-x   23 root     root           960 Feb 16 00:22 etc
drwxr-xr-x    4 root     root            80 Feb  8 20:00 home
-rwxr-xr-x    1 root     root           176 Feb  8 19:59 init
lrwxrwxrwx    1 root     root             7 Feb  8 19:26 lib -> usr/lib
lrwxrwxrwx    1 root     root             3 Feb  8 19:26 lib64 -> lib
lrwxrwxrwx    1 root     root            11 Feb  8 19:32 linuxrc -> bin/busybox
drwxr-xr-x    2 root     root            40 Feb  8 19:23 media
drwxr-xr-x    3 root     root            60 Feb 16 00:22 mnt
drwxr-xr-x    3 root     root            60 Feb  8 19:58 opt
dr-xr-xr-x  336 root     root             0 Feb 16 00:21 proc
drwxr-xr-x    2 root     root            40 Feb  8 19:23 root
drwxr-xr-x   17 root     root           540 Feb 16 00:22 run
lrwxrwxrwx    1 root     root             8 Feb  8 19:26 sbin -> usr/sbin
drwxr-xr-x    2 root     root            40 Feb 16 00:22 srv
dr-xr-xr-x   12 root     root             0 Feb 16 00:22 sys
drwxrwxrwt    8 root     root           240 Feb 16 00:22 tmp
drwxr-xr-x    8 root     root           180 Feb 10 23:36 usr
drwxr-xr-x    4 root     root           220 Feb 16 00:22 var
```

however when I run `minikube stop` and `minikube start --vm-driver=xhyve` and then run `minikube ssh` and `ls -ll /` I get this

```
total 4
lrwxrwxrwx    1 root     root             7 Feb  8 19:26 bin -> usr/bin
lrwxrwxrwx    1 root     root            14 Feb 16 00:23 data -> /mnt/sda1/data
drwxr-xr-x   15 root     root          3020 Feb 16 00:23 dev
drwxr-xr-x   23 root     root           960 Feb 16 00:23 etc
drwxr-xr-x    4 root     root            80 Feb  8 20:00 home
-rwxr-xr-x    1 root     root           176 Feb  8 19:59 init
lrwxrwxrwx    1 root     root             7 Feb  8 19:26 lib -> usr/lib
lrwxrwxrwx    1 root     root             3 Feb  8 19:26 lib64 -> lib
lrwxrwxrwx    1 root     root            11 Feb  8 19:32 linuxrc -> bin/busybox
drwxr-xr-x    2 root     root            40 Feb  8 19:23 media
drwxr-xr-x    3 root     root            60 Feb 16 00:23 mnt
drwxr-xr-x    3 root     root            60 Feb  8 19:58 opt
dr-xr-xr-x  474 root     root             0 Feb 16 00:23 proc
drwxr-xr-x    2 root     root            40 Feb  8 19:23 root
drwxr-xr-x   16 root     root           520 Feb 16 00:24 run
lrwxrwxrwx    1 root     root             8 Feb  8 19:26 sbin -> usr/sbin
drwxr-xr-x    2 root     root            40 Feb 16 00:23 srv
dr-xr-xr-x   12 root     root             0 Feb 16 00:23 sys
drwxrwxrwt    8 root     root           240 Feb 16 00:23 tmp
drwxr-xr-x    8 root     root           180 Feb 10 23:36 usr
drwxr-xr-x    4 root     root           220 Feb 16 00:23 var
```

you will notice the absence of the Users directory

**What you expected to happen**:
I expect the Users directory to remount on restart

**How to reproduce it** (as minimally and precisely as possible):
exactly as I mentioned above

**Anything else do we need to know**:

**Comment by r2d4** [comment]
It looks like the mount code in the xhyve driver only get called on create.  We should move it so that it gets called on start also.  This would be a fix upstream in the xhyve driver.

https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L445

**Comment by justechn** [comment]
Thanks, should I file a bug with xhyve?

**Comment by dlorenc** [comment]
We can track it here, but feel free to open an issue there too.

**Comment by justechn** [comment]
@dlorenc @r2d4 Thanks for getting this fixed so quickly. Any change of getting a new release that includes this fix?

**Comment by justechn** [comment]
@dlorenc @r2d4 So I decided to compile this myself and test it out. Unfortunately I am seeing the same results.

I made sure i removed all traces of the old xhyve driver and then followed the steps [here](https://github.com/zchee/docker-machine-driver-xhyve#install) to build my own. It automatically installed the file into /usr/local/bin.

When I start minikube the first time it works great, but a stop and start breaks it.

It looks like minikube hard codes [Virtio9p](https://github.com/kubernetes/minikube/blob/2f02060355a0579b44d47a27f78be79d8ef293bb/pkg/minikube/cluster/cluster_darwin.go#L66) on create, but I could not find the code for start. Is it possible this is not getting set on start and preventing the volume from mounting?

**Comment by justechn** [comment]
ok I looked through the log during startup and noticed this line when I run `minikube start` `(minikube) DBG | virtio-9p setup failed: Host is not running` Any idea how to get around that?

**Comment by justechn** [comment]
here is a little more info. I output what is being run on [this line](https://github.com/zchee/docker-machine-driver-xhyve/blob/a2a0e24e52f59f2552e9616be8ed1695bc6c7697/xhyve/xhyve.go#L948). If I run `minikube ssh` and then run what was output above the volume appears and works correctly. It looks like xhyve is not waiting for the host to start before trying to create the volume.

**Comment by r2d4** [comment]
Thanks for the detailed debugging.  I think we might have to move `setupMounts` to be after d.waitForIP

https://github.com/zchee/docker-machine-driver-xhyve/blob/a2a0e24e52f59f2552e9616be8ed1695bc6c7697/xhyve/xhyve.go#L485-L487

**Comment by justechn** [comment]
yes, I did that and it works.

Thanks

**Comment by justechn** [comment]
Any idea when we can get an official build?

**Comment by r2d4** [comment]
That would be up to @zchee until we vendor in his driver
