### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate,

### ISSUE THREAD

**Issue by jeevanm87** [kubernetes/minikube#11352]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by vigothehacker** [comment]
Needs more detail

**Comment by ilya-zuyev** [comment]
@jeevanm87 Please provide full log output of failed operation (run minikube with `-v=6 --alsologtostderr`) and details about your os/system. Thanks!

**Comment by jeevanm87** [comment]
@ilya-zuyev 
Thanks for your response. I am very much new to Kubernetes. 
I am trying to setup and RUN KUBERNETES LOCALLY VIA MINIKUBE on my VM with all the resource recommendation. 

Below is what I am getting when I run "$  minikube start --driver=ssh --ssh-ip-address=10.201.206.16 --ssh-key='~/.ssh/id_rsa' --ssh-user=msicka  --alsologtostderr -v=4"

I0510 12:49:07.480742  228492 main.go:128] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
I0510 12:49:10.530501  228492 main.go:128] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
I0510 12:49:13.582713  228492 main.go:128] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
I0510 12:49:16.632398  228492 main.go:128] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain
I0510 12:49:19.687699  228492 main.go:128] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain

And getting below when I run with driver ssh. 
![image](https://user-images.githubusercontent.com/20540129/117702904-c1fb5300-b1e6-11eb-89f6-a3bb1d78accd.png)


Please suggest me where I am missing.

**Comment by ilya-zuyev** [comment]
@jeevanm87 Cool, thanks for the logs! You are using the ssh driver, and it cannot establish the connection with the target host (`10.201.206.16`).  Please check that `10.201.206.16` machine has ssh server running, and `msicka` can authenticate.

Also please note, usually the ssh driver is recommended for advanced scenarios, if you just need a local minikube instance, `docker` or `virtualbox` drivers are much easier to work with.

**Comment by ilya-zuyev** [comment]
hey @jeevanm87! any update on this issue?

**Comment by spowelljr** [comment]
Hi @jeevanm87, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
