### ISSUE TITLE
Host access documentation uses tools that are not installed in docker

### ISSUE THREAD

**Issue by bandwiches** [kubernetes/minikube#11372]
Validating Connectivity

Ping is the recommended test, however ping is not included in the image.

```bash
user@host:~$ minikube ssh
docker@minikube:~$ ping host.minikube.internal
-bash: ping: command not found
docker@minikube:~$
```

**Comment by afbjorklund** [comment]
We can install `iputils-ping`. I don't think we need telnet, there is `netcat`. Maybe update the docs ?

**Comment by afbjorklund** [comment]
> If the only troubleshooting method you are going to provide/suggest is `ping`, why would you not include it in the image?

It was in the VM image, but then missed for the KIC image.

**Comment by afbjorklund** [comment]
Eventually we might consider keeping just **one** operating system. We just have to decide on which one to keep, first...

#11058 #11018

**Comment by gitgithan** [comment]
How do i install nc to use `nc -vz host.minikube.internal 8000` stated at https://minikube.sigs.k8s.io/docs/handbook/host-access/?
apt or apt-get are also not found inside `minikube ssh`

**Comment by afbjorklund** [comment]
You can use `toolbox`
