### ISSUE TITLE
Can not start minikube with  "minikube start"

### ISSUE THREAD

**Issue by hoibuikms** [kubernetes/minikube#11385]
**Steps to reproduce the issue:** 

1. Open cmd
2.  Run: >minikube start

**Full output of `minikube logs` command:**
<details>
! Executing "docker ps -a --format {{.Names}}" took an unusually long time: 15.4228278s
* Restarting the docker service may improve performance.
! StartHost failed, but will try again: recreate: creating host: create host timed out in 360.000000 seconds
* docker "minikube" container is missing, will recreate.
* Powering off "minikube" via SSH ...
* Stopping node "minikube"  ...
* Deleting "minikube" in docker ...
</details>

**Full output of failed command:**
<details>

</details>

**Comment by vigothehacker** [comment]
Please provide full log output of failed operation (run minikube start with -v=6 --alsologtostderr) and details about your os/system. Thanks!
