### ISSUE TITLE
Issues starting the dashboard on windows

### ISSUE THREAD

**Issue by ram2031** [kubernetes/minikube#11380]
**Steps to reproduce the issue:** 

1.Running docker desktop
2.downloaded minicube and kubectl exe files and able to start minicube
3.minucube dashboard give an error HOST_KUBECTL_PROXY: readByteWithTimeout: EOF

**Full output of `minikube logs` command:**
<details>
log file attached

</details>

**Full output of failed command:**
<details>

[minikube_dashboard_ebbf03cfed1349d6547905ae88a08ec70af8cba3_0.log](https://github.com/kubernetes/minikube/files/6462119/minikube_dashboard_ebbf03cfed1349d6547905ae88a08ec70af8cba3_0.log)

</details>

**Comment by spowelljr** [comment]
Same issue as #9473 #9759 #11045

@ram2031 What version of minikube are you using?

**Comment by andriyDev** [comment]
This issue is getting quite old, closing. If the issue persists, please feel free to reopen!
