### ISSUE TITLE
Putting flag as first argument causes unintended log file names

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#11382]
Current:
```
$ minikube -p m1 status

Log file created is: /tmp/minikube_-p_<hash>.log
```

Expected:
```
$ minikube -p m1 status

Log file created is: /tmp/minikube_status_<hash>.log
```

**Comment by vigothehacker** [comment]
Running `minikube --alsologtostderr status` generates `minikube_--alsologtostderr_<hash>_0.log` 

Can I have a look at this? Would like to triage this issue as a beginner

/assign
