### ISSUE TITLE
Automate `make generate-doc` 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11388]
currently we updated make lint to geneate docs, the problem is, if a couple PRs touch integration tests or translations,
it will cause in delay with contribuotrs to ask them to update the docs and rebase

1- we should have an automation to rebase a user's PR and generate Docs for them and push it to their PR
with a command word like
```
ok-to-generate-doc
```

2- or  alternatively we can make a github action to create a PR on every merge and run `make generate-doc` after each PR is merged

exmaple https://github.com/marketplace/actions/create-pull-request#reference-example

the second option seems easier to implement

**Comment by ilya-zuyev** [comment]
may be add `make submit` and ask everyone to use it instead of `git submit`? Inside that rule we could run all generators, linters and unit tests and commit only if everything is ok
