### ISSUE TITLE
Run minikube as root

### ISSUE THREAD

**Issue by Oliver-Sellwood** [kubernetes/minikube#11383]
Hi I am looking for a way to run minikube as root with the Docker driver. In my workflow I am using sysbox system containers to help separate different projects I'm working on. Going great so far but trying to run `minikube` within one of these containers I get the error that it cannot be run as root.

Since I'm already inside a container when running minikube I don't really care if it has root and it's a little painful to have to create a user and deal with that side of things.

Given this situation is there any more danger in running minikube as root that I'm not considering and if I decide to go ahead anyway is there any way to force minikube to run as root

**Comment by afbjorklund** [comment]
Same as #8257

**Comment by Oliver-Sellwood** [comment]
oh yup, my bad. the force flag does the job.

Thanks

**Comment by afbjorklund** [comment]
Our main issues came from people running `sudo minikube`, which creates a mixture of files and directories owned by different users (both user and root). Running the entire process as root from start to finish "works", it's just considered as bad practice.

But when you have a dedicated virtual machine or a dedicated system containers, it's a little different from running as root on your laptop. So maybe that scenario needs special handling, but it's also a bit different and has some usability concerns as well.

**Comment by afbjorklund** [comment]
@Oliver-Sellwood : note that you are effectively running docker-in-docker-in-docker here
