### ISSUE TITLE
Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

### ISSUE THREAD

**Issue by Marco-Zheng** [kubernetes/minikube#11397]
**Steps to reproduce the issue:** 

1. minikube start --driver=hyperkit
![image](https://user-images.githubusercontent.com/52538259/118072521-8de98300-b3dc-11eb-8e93-b258b42b613e.png)

2. then i try to run `minikube delete` and start minikube again, bu result is the same

macOs: BigSur 11.2.3
minikube version:minikube version: v1.18.1
hyperkit version: v0.20210107-2-g2f061e
docker verison:20.10.6

**Comment by medyagh** [comment]
@Marco-Zheng  have you tried upgrading the Hyperkit ?

```
brew upgrade hyperkit
```

?

**Comment by Marco-Zheng** [comment]
@medyagh I just followed your operation, but still failed, hyperkit upgrade to 0.20200908 now.
![image](https://user-images.githubusercontent.com/52538259/118225621-0b35f600-b4b8-11eb-8b22-af8701e3de84.png)

**Comment by mubarak-bunza** [comment]
@medyagh I followed same instructions but still fails.

**Comment by pcallahan-r7** [comment]
any resolution to this?   I see this with 

```
minikube version: v1.25.1
hyperkit: v0.20210107-12-gadc4ea
```
on macos Monterey 12.2

/remove-lifecycle stale
