### ISSUE TITLE
Simplify kicbase cache handling by removing digest

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11411]
Currently we load the kicbase image using **both** tag and digest:

`gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e`

However, we can only load the tag from the cache and not the digest:

`gcr.io/k8s-minikube/kicbase:v0.0.22`

This makes the code **not** find the image next time, since it has no digest.

```
        "Id": "sha256:bcd131522525c9c3b8695a8d144be8d177bcd5614ec5397f188115d3be0bbc24",
        "RepoTags": [
            "gcr.io/k8s-minikube/kicbase:v0.0.22"
        ],
        "RepoDigests": [],
```

The current workaround is to pull the manifest down from the registry again:

```console
$ docker pull gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
gcr.io/k8s-minikube/kicbase@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e: Pulling from k8s-minikube/kicbase
Digest: sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
Status: Downloaded newer image for gcr.io/k8s-minikube/kicbase@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
```

The layers were already downloaded, so it pulls down the manifest and fills in the digest:

```
        "Id": "sha256:bcd131522525c9c3b8695a8d144be8d177bcd5614ec5397f188115d3be0bbc24",
        "RepoTags": [
            "gcr.io/k8s-minikube/kicbase:v0.0.22"
        ],
        "RepoDigests": [
            "gcr.io/k8s-minikube/kicbase@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e"
        ],
```

And so the code can find the image in the list. But it doesn't work offline or with podman.

```
$ sudo podman pull gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
Error: invalid image reference "gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e": Docker references with both a tag and digest are currently not supported
```

----

It would be much simpler if we would _only_ use the digest for the first download (to the cache).
After that, we would only use the (name and) tag to check if the image has already been loaded.

The only downside is that you cannot have two images with the same tag, but different digests.
However that doesn't really work anyway, when you pull the second one the tag will also move.

**And we wouldn't have to patch go-containerregistry, if we did this...**

We could still keep the digest in the filename, if we are paranoid.

`kicbase_v0.0.22@sha256_7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e.tar`

But then we would have to provide two parameters (or strip the digest)

**Comment by afbjorklund** [comment]
ping @medyagh

Do we gain anything by saving the digest in the cache and in the daemon, after we have verified the initial pull ?

**Comment by afbjorklund** [comment]
Images with _only_ digests could be handled too. The problem is when trying to have both RepoTags and RepoDigest.

```console
$ docker save busybox@sha256:be4684e4004560b2cd1f12148b7120b0ea69c385bcc9b12a637537a2c60f97fb > busybox.tar
$ docker load < busybox.tar
Loaded image ID: sha256:c55b0f125dc65ee6a9a78307d9a2dfc446e96af7477ca29ddd4945fd398cc698
```
```
[{"Config":"c55b0f125dc65ee6a9a78307d9a2dfc446e96af7477ca29ddd4945fd398cc698.json","RepoTags":null,"Layers":["a355ae7461fdd43484ed16e7e48620ff19b187adc03bcd4b5cfd5ba3ce2ee670/layer
.tar"]}]
```

However, such an image will be listed as `<none>`, so it can be only be referenced using the image ID (that we don't save)

```
[
    {
        "Id": "sha256:c55b0f125dc65ee6a9a78307d9a2dfc446e96af7477ca29ddd4945fd398cc698",
        "RepoTags": [],
        "RepoDigests": [],
```

Which makes it rather useless for the kicbase, at least with the current cache implementation.

**Comment by dinever** [comment]
Hi @afbjorklund, this sounds like an issue I can work on. Can I take it? Thanks!

**Comment by afbjorklund** [comment]
@dinever : it's part of an ongoing effort to fix the kicbase and podman, see ~~PR #11063~~ and PR #11346

We currently have a working solution, with a patched go-containerregistry, so this is mostly simplication...

**Comment by afbjorklund** [comment]
Having "daemon" in the API is not great either, but that was inherited from go-containerregistry

**Comment by medyagh** [comment]
@afbjorklund how about this, we first try to get the image by digest and if we fail, we try to get it without digest ... ? would that be any better ?

are you saying in the current path we are not using the Digest SHA at all and giving the use no feeling of confidence of integrity at all ?

I kind of do want to provide the SHA anywhere that we could, it would be nice for local developement too, if u accidently tag your image kicbase:v0.0.20 minikube wont use it

**Comment by medyagh** [comment]
if removing the digest from kicsha makes it easier for everyone, I will not object but I would love to see a proposal that at least we tried to verify the integrity and reduce the surface attack for our users

**Comment by afbjorklund** [comment]
> @afbjorklund how about this, we first try to get the image by digest and if we fail, we try to get it without digest ... ? would that be any better ?
> 
> are you saying in the current path we are not using the Digest SHA at all and giving the use no feeling of confidence of integrity at all ?

That's not really how it works, first we pull the image by digest and use our patched library to save it.

After loading it from the cache, we ignore the digest and pull the tag again and hope that they match.
Sometimes this fails horribly, like when we pulled the `amd64` image by mistake on `arm64` (#11208)

There is also no error reporting in the library, so the fetch and the load can fail silently and it goes on.
This means we could end up with half a file, and we didn't have any error reporting why the load failed.

So we would have to pull it by tag, and then we could check the digest to see if it matches before saving.

----

This is what the manifest looks like:

### crane pull

```
[{"Config":"sha256:c55b0f125dc65ee6a9a78307d9a2dfc446e96af7477ca29ddd4945fd398cc698","RepoTags":["index.docker.io/library/busybox:i-was-a-digest"],"Layers":["aa2a8d90b84cb2a9c422e7005cd166a008ccf22ef5d7d4f07128478585ce35ea.tar.gz"]}]
```

### docker save

```
[{"Config":"c55b0f125dc65ee6a9a78307d9a2dfc446e96af7477ca29ddd4945fd398cc698.json","RepoTags":null,"Layers":["a355ae7461fdd43484ed16e7e48620ff19b187adc03bcd4b5cfd5ba3ce2ee670/layer.tar"]}]
```

### podman save

```
[{"Config":"c55b0f125dc65ee6a9a78307d9a2dfc446e96af7477ca29ddd4945fd398cc698.json","RepoTags":[],"Layers":["36b45d63da70799f32c6e82de9be2e75167099b010def8771cf847c0e4c9c975.tar"]}]

```
When trying to save a regular image.

docker.io/library/busybox:latest@sha256:be4684e4004560b2cd1f12148b7120b0ea69c385bcc9b12a637537a2c60f97fb


```
        "Id": "sha256:c55b0f125dc65ee6a9a78307d9a2dfc446e96af7477ca29ddd4945fd398cc698",
        "RepoTags": [
            "busybox:latest"
        ],
        "RepoDigests": [
            "busybox@sha256:be4684e4004560b2cd1f12148b7120b0ea69c385bcc9b12a637537a2c60f97fb"
        ],
```

So they each fail, in their own special way. Without the patch, we can only save tagged images (not digests).

If you use both, then docker happily uses the digests and tags it with whatever you want. There is no check.

```console
$ docker pull gcr.io/k8s-minikube/kicbase:1.2.3@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
gcr.io/k8s-minikube/kicbase@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e: Pulling from k8s-minikube/kicbase
Digest: sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
Status: Image is up to date for gcr.io/k8s-minikube/kicbase@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
gcr.io/k8s-minikube/kicbase:1.2.3@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e
```

**Comment by afbjorklund** [comment]
To clarify, we would keep the old patch that saves the tag of the manifest also as the tag of the image.

`tarball.Write`
https://github.com/google/go-containerregistry/commit/019cdfc6adf96a4905a1b93a7aeaea1e50c0b6cf

But we would drop the patch that pulls the tag from the registry after loading the image from the tarball.

`daemon.Write`
https://github.com/google/go-containerregistry/commit/08e94985c297f6b7ca74d4995ccd008edc810453

----

So when pulling from the registry, we would use the `name.Digest`:

gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e

But when looking in the daemon/podman, we use the `name.Tag`:

gcr.io/k8s-minikube/kicbase:v0.0.22

**Comment by sharifelgamal** [comment]
We added a feature to failover to trying to pull without the sha, which solves some of these issues.
