### ISSUE TITLE
Latest version of kicbase on Github packages is 0.0.17

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11422]
![Screenshot from 2021-05-16 19-21-08](https://user-images.githubusercontent.com/10364051/118406339-f6a25b00-b67b-11eb-9ee3-e3a10d8a631e.png)

Even though v0.0.22 is released on gcr.io (and docker.io)

https://github.com/orgs/kubernetes/packages

> kicbase `v0.0.17`
> Published on Jan 22 by Kubernetes in kubernetes/minikube
>
> kicbase-build `v0.0.17-1614032225-10572`
> Published on Feb 23 by Kubernetes in kubernetes/minikube

Are these still in use ? Should they be removed or updated ?

https://hub.docker.com/r/kicbase/stable/tags

> `v0.0.22`
> Last pushed 11 days ago by minikubebot

https://hub.docker.com/r/kicbase/build/tags

> `v0.0.22-1620785771-11384`
> Last pushed 5 days ago by minikubebot

With the original still being hosted on Google Cloud Registry

`gcr.io/k8s-minikube/kicbase`

`gcr.io/k8s-minikube/kicbase-builds`

**Comment by sharifelgamal** [comment]
github packages are abandoned and hidden
