### ISSUE TITLE
Minikube Dashboard renders incorrectly in Firefox

### ISSUE THREAD

**Issue by jwhitehouse-raise** [kubernetes/minikube#1142]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
minikube version: v0.16.0

**Environment**:
- **OS** OS X El Capitan 10.11.6
- **VM Driver** "DriverName": "xhyve"
- **ISO version** "Boot2DockerURL": "file:///Users/jennawhitehouse/.minikube/cache/iso/minikube-v1.0.6.iso"
- **Install tools** Minikube via curl instructions, Kubectl via Brew
- **Others**: Firefox 51.0.1 (64-bit)

**What happened**:
Firefox renders `minikube dashboard` without any images/icons.

**What you expected to happen**:
Firefox renders the page correctly.

**How to reproduce it** (as minimally and precisely as possible):
Using Firefox as default browser, install minikube v0.16, minikube start, minikube dashboard.
![minikube_render_error](https://cloud.githubusercontent.com/assets/23040526/23077161/f9b5ee30-f508-11e6-8b4d-ab72e85f435e.png)

**Anything else do we need to know**:
Google Chrome & Safari render the dashboard correctly for me. Also note, did turn off plug-ins such as ad-block when testing. Final addition: the Label & Images blurring is intentional, not part of my rendering error.

**Comment by r2d4** [comment]
Hey thanks for using minikube and reporting this issue.  The right place for all dashboard issues is

https://github.com/kubernetes/dashboard

You should re-open that bug in that repository.  Thanks!

**Comment by jwhitehouse-raise** [comment]
Thanks!
