### ISSUE TITLE
Generate public fail rate of a test

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11434]
for all the downstream jobs of "minikube" in jenkins
```
https://a646c87040050000000000000000001.proxy.googleprod.com/job/Build_Cross/
```

there will be an json summary for example:

https://storage.googleapis.com/minikube-builds/logs/11258/e7907e3/KVM_Linux_summary.json

```
FailedDocker_Cloud_Shell_integration
FailedDocker_Linux_containerd_arm64
In progressDocker_Linux_containerd_integration
In progressDocker_Linux_crio_arm64
In progressDocker_Linux_crio_integration
In progressDocker_Linux_docker_arm64
In progressDocker_Windows_integration
In progressDocker_macOS_integration
DisabledHyper-V_Windows_integration
In progressHyperkit_macOS_integration
In progressKVM_Linux_containerd_integration
In progressKVM_Linux_crio_integration
In progressKVM_Linux_integration
In progressPerformance Bot
FailedVirtualBox_Linux_integration
FailedVirtualBox_Windows_integration
In progressdocker_Linux_integration
In progressnone_Linux_integration
```

should be simmilar to our internal flake chart but with Commits Dots clickable to see full html Report

<img width="1631" alt="Screen Shot 2021-05-17 at 1 43 04 PM" src="https://user-images.githubusercontent.com/4564227/118553951-d2935800-b715-11eb-8d01-e016dc552a17.png">

and as a follow UP there should be stats reteriable per Test
for example I should be able to see what is the flake rate for "TestFunctional/ImageLoad" in the past week

and as a follow up the @minikube-bot should create a Failing Test Issue with example gopogh report when there is a flake rate about 10% in a week

in addition to that there shoudl be a separate chart that also tracks numbers of Passed Tests/ Failed Tests and Skipped tests and Total Number of all tests (regradless of restul) in a chart per Driver

like KVM_LINUX Chart
a graph that shows trend of total number of ran tests, passed and failed and skipped (so we see in one big look in what driver we are skipping most tests or what driver is not running all tests)

**Comment by medyagh** [comment]
gsutil ls -l gs://minikube-builds/logs/master | sort -k 2

**Comment by medyagh** [comment]
https://github.com/medyagh/minikube/blob/1be59b8f23c66d9a6be174dcd579b17302857f5f/hack/jenkins/common.sh

**Comment by medyagh** [comment]
we could use plotter lib and put it in hack folder hack/test-flake-chart https://github.com/medyagh/minikube/blob/1be59b8f23c66d9a6be174dcd579b17302857f5f/hack/benchmark/cpu_usage/idle_only/chart.go#L30

**Comment by andriyDev** [comment]
Here's the current plan:
- Convert gopogh summary data into entries in a CSV file, and generate this for all runs.
- Keep the CSV up to date by appending rows to the CSV after gopogh
  - Possibly use SQLite
  - Possibly just append rows directly on the shell
- In an HTML+JS, load the CSV data
  - Create a chart for the flake rate of tests, duration of tests, and number of tests run (sanity check).
- Upload HTML+JS+CSV to GCP to host this

We want charts to be dynamic in some way, so we have to use HTML+JS instead of hosting a static chart.

**Comment by andriyDev** [comment]
In addition to this, we'd like a bot to send messages to PRs with failed tests to inform them of flake rates of those tests (with links to the charts for those tests). It would be even more useful for the bot to highlight tests with very stable near-0 flake rates. This way if a PR breaks a stable test, they can clearly see which tests are most definitely their fault.

**Comment by andriyDev** [comment]
Comment from the CLI!

**Comment by andriyDev** [comment]
Here is the data path.
0) Manual: Run collect_data.sh to collect all existing log files and process them into a neat CSV file that is then uploaded to the GCS bucket.
1) Jenkins runs tests
2) Each Jenkins integration test job creates gopogh output. After being uploaded (as normal), the output is processed and appended to data present in GCS bucket.
3) Separate Jenkins cron job runs regularly to use GCS bucket data to compute recent flake rates. These flake rates are then stored back into GCS bucket.
4) PR bot uses flake rate data from GCS bucket and comments on PRs about flake rates and links to flake rate charts
5) Flake rate charts (hosted on GCS) loads raw data from GCS and charts historical flakiness.

**Comment by andriyDev** [comment]
Change: PR bot cannot be the one to comment about flake rate. This is because we can't guarantee the order of Jenkins builds and we need to ensure some test data is present.

**Comment by andriyDev** [comment]
These are the flake rates of all failed tests on Docker_Linux_crio.
|Failed Tests|Flake Rate|
|---|---|
|TestAddons/parallel/Ingress|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crioTestAddons/parallel/Ingress,100.00test=TestAddons/parallel/Ingress))|
|TestPreload|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crioTestPreload,100.00test=TestPreload))|
|TestRunningBinaryUpgrade|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crioTestRunningBinaryUpgrade,100.00test=TestRunningBinaryUpgrade))|
|TestStoppedBinaryUpgrade|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crioTestStoppedBinaryUpgrade,100.00test=TestStoppedBinaryUpgrade))|

**Comment by andriyDev** [comment]
These are the flake rates of all failed tests on Docker_Linux_crio.
|Failed Tests|Flake Rate|
|---|---|
|TestAddons/parallel/Ingress|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crio&test=TestAddons/parallel/Ingress))|
|TestPreload|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crio&test=TestPreload))|
|TestRunningBinaryUpgrade|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crio&test=TestRunningBinaryUpgrade))|
|TestStoppedBinaryUpgrade|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crio&test=TestStoppedBinaryUpgrade))|

**Comment by andriyDev** [comment]
These are the flake rates of all failed tests on Docker_Linux_crio.
|Failed Tests|Flake Rate (%)|
|---|---|
|TestAddons/parallel/Ingress|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crio&test=TestAddons/parallel/Ingress))|
|TestPreload|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crio&test=TestPreload))|
|TestRunningBinaryUpgrade|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crio&test=TestRunningBinaryUpgrade))|
|TestStoppedBinaryUpgrade|100.00 ([chart](https://storage.googleapis.com/minikube-flake-rate/flake_chart.html?env=Docker_Linux_crio&test=TestStoppedBinaryUpgrade))|
