### ISSUE TITLE
Auto generate Base Image Tools versions

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11435]
in our kic base automation https://github.com/medyagh/minikube/blob/1be59b8f23c66d9a6be174dcd579b17302857f5f/hack/jenkins/kicbase_auto_build.sh#L31

we could generate the base image version of things each time we build a new Kic Base or ISO

for example

docker version
crictl verison
or things that users care about, so when we install latest version of everything on each build we communicate to the user what docker verison is included in the base

**Comment by ilya-zuyev** [comment]
Should we just maintain a file to keep installed tools versions per kicbase version?
