### ISSUE TITLE
add maintainer column to addons list

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11444]

**Comment by JulienBreux** [comment]
Hi @andriyDev,

I can open a PR about this issue and help you. 🤗 
But what do you expect in the maintainer column?

The name and email address of the maintainer?
The username of the Github account?

Have a good day.

**Comment by andriyDev** [comment]
@JulienBreux I actually have a PR for this all ready to go haha, just aggregating the maintainers, I'll send a PR by the end of the day.

**Comment by JulienBreux** [comment]
> @JulienBreux I actually have a PR for this all ready to go haha, just aggregating the maintainers, I'll send a PR by the end of the day. I appreciate it though!

Perfect 🙏
