### ISSUE TITLE
minikube start issues

### ISSUE THREAD

**Issue by techstacksavvy** [kubernetes/minikube#11449]
minikube start
**Steps to reproduce the issue:** 

1. minikube start command
2. 
3.

**Full output of `minikube logs` command:**
<* minikube v1.20.0 on Microsoft Windows 10 Home 10.0.19041 Build 19041
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Updating the running docker "minikube" container ...

X Exiting due to RUNTIME_ENABLE: sudo systemctl start docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

*
╭──────────────────────────────────────────────────────────────────╮
│                                                                  │
│    * If the above advice does not help, please let us know:      │
│      https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                  │
│    * Please attach the following file to the GitHub issue:       │
│    * - C:\Users\sahee\.minikube\logs\lastStart.txt               │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @techstacksavvy, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
