### ISSUE TITLE
docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/share/doc/adduser/examples/adduser.local.conf.examples: directory not empty.

### ISSUE THREAD

**Issue by Ashwin-Raj18** [kubernetes/minikube#11452]
**Steps to reproduce the issue:** 

1.On linux CentOs 7
2.cmd : minikube start

**Full output of `minikube logs` command:**
<details>
$ minikube start
* minikube v1.20.0 on Centos 7.2.1511
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
    > gcr.io/k8s-minikube/kicbase...: 358.10 MiB / 358.10 MiB  100.00% 1.07 MiB
* docker "minikube" container is missing, will recreate.
* Creating docker container (CPUs=2, Memory=2200MB) ...
! StartHost failed, but will try again: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e' locally
gcr.io/k8s-minikube/kicbase@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e: Pulling from k8s-minikube/kicbase
a70d879fa598: Pulling fs layer
...
74754ab5b883: Waiting
...
c4394a92d1f8: Verifying Checksum
c4394a92d1f8: Download complete
10e6159c56c0: Verifying Checksum
10e6159c56c0: Download complete
...
3493142a6c0f: Pull complete
b123634b22fa: Verifying Checksum
b123634b22fa: Download complete
...
3507e244768c: Verifying Checksum
3507e244768c: Download complete

docker: failed to register layer: ApplyLayer exit status 1 stdout:  stderr: unlinkat /usr/share/doc/adduser/examples/adduser.local.conf.examples: directory not empty.
See 'docker run --help'.

[lastStart.txt](https://github.com/kubernetes/minikube/files/6505879/lastStart.txt)

</details>

**Comment by medyagh** [comment]
@Ashwin-Raj18 it seems like the problem is related to no disk space on your machine for docker to pull the image

related
https://github.com/moby/moby/issues/29508

can you check if there is no space left?

df -h

**Comment by ilya-zuyev** [comment]
the error in https://github.com/moby/moby/issues/29508 is different

`no space left on device`
vs 
`unlinkat /usr/share/doc/adduser/examples/adduser.local.conf.examples: directory not empty`

**Comment by medyagh** [comment]
@Ashwin-Raj18 are you using rootless docker ?

**Comment by spowelljr** [comment]
Hi @Ashwin-Raj18, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by anubhav13103738** [comment]
I am facing the same issue:
ApplyLayer exit status 1 stdout:  stderr: unlinkat /etc/cron.daily: directory not empty

df -h:
Filesystem                      Size  Used Avail Use% Mounted on
/dev/sda2                       155G   14G  141G   9% /
devtmpfs                         16G     0   16G   0% /dev
tmpfs                            16G     0   16G   0% /dev/shm
tmpfs                            16G   17M   16G   1% /run
tmpfs                            16G     0   16G   0% /sys/fs/cgroup
/dev/sda1                       297M  151M  147M  51% /boot
tmpfs                           3.2G     0  3.2G   0% /run/user/0

df -i:
Filesystem                        Inodes   IUsed     IFree IUse% Mounted on
/dev/sda2                      161930768   39171 161891597    1% /
devtmpfs                         4064266     419   4063847    1% /dev
tmpfs                            4066749       1   4066748    1% /dev/shm
tmpfs                            4066749     609   4066140    1% /run
tmpfs                            4066749      16   4066733    1% /sys/fs/cgroup
/dev/sda1                         307200     337    306863    1% /boot
tmpfs                            4066749       1   4066748    1% /run/user/0

**Comment by spowelljr** [comment]
Hi @anubhav13103738, are you running Rootless Docker perhaps?

**Comment by anubhav13103738** [comment]
> Hi @anubhav13103738, are you running Rootless Docker perhaps?

No, I am using Root Docker.
