### ISSUE TITLE
https://minikube.sigs.k8s.io/docs/start linux x86_64 rpm download link fails

### ISSUE THREAD

**Issue by mark-hyde** [kubernetes/minikube#11460]
Download  link for 'Linux x86-64 rpm in https://minikube.sigs.k8s.io/docs/start/ is given as:
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86-64.rpm

But this doesn't work.

Real link appears to be at curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm
(underscore instead of hyphen)

**Comment by spowelljr** [comment]
@mark-hyde Thanks for bringing this to attention, will update the documentation.
