### ISSUE TITLE
无法从registry.cn-hangzhou.aliyuncs.com/google_containers下载镜像

### ISSUE THREAD

**Issue by JiangJungle** [kubernetes/minikube#11476]
你好：我是中国大陆用户，我无法从registry.cn-hangzhou.aliyuncs.com/google_containers下载相关镜像

**重现问题所需的命令**：minikube start --image-mirror-country=cn  和  minikube dashboard

**失败的命令的完整输出**：<details>

kube-system                    storage-provisioner                                             0/1     ImagePullBackOff   0          5m3s
kubernetes-dashboard   dashboard-metrics-scraper-8554f74445-9x4qb   0/1     ImagePullBackOff   0          6s
kubernetes-dashboard   kubernetes-dashboard-6c87f58d7c-f7txl             0/1     ErrImagePull       0          6s  

</details>

**`minikube logs`命令的输出**： <details>
May 21 14:11:00 minikube kubelet[4547]: E0521 14:11:00.448797    4547 pod_workers.go:191] Error syncing pod f9d0cab0-f1f7-470d-b64f-8bbc36ebc82e ("kubernetes-dashboard-6c87f58d7c-f7txl_kubernetes-dashboard(f9d0cab0-f1f7-470d-b64f-8bbc36ebc82e)"), skipping: failed to "StartContainer" for "kubernetes-dashboard" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/dashboard, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
May 21 14:11:05 minikube kubelet[4547]: E0521 14:11:05.536787    4547 pod_workers.go:191] Error syncing pod 981c80bc-461d-4f63-83a9-227b3e5af388 ("storage-provisioner_kube-system(981c80bc-461d-4f63-83a9-227b3e5af388)"), skipping: failed to "StartContainer" for "storage-provisioner" with ImagePullBackOff: "Back-off pulling image \"registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-minikube/storage-provisioner:v5\""
May 21 14:11:08 minikube kubelet[4547]: E0521 14:11:08.546653    4547 pod_workers.go:191] Error syncing pod c1a886ec-5a49-4fcc-874e-b96b18fdc495 ("dashboard-metrics-scraper-8554f74445-9x4qb_kubernetes-dashboard(c1a886ec-5a49-4fcc-874e-b96b18fdc495)"), skipping: failed to "StartContainer" for "dashboard-metrics-scraper" with ImagePullBackOff: "Back-off pulling image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/metrics-scraper:v1.0.4@sha256:555981a24f184420f3be0c79d4efb6c948a85cfce84034f85a563f4151a81cbf\""
May 21 14:11:14 minikube kubelet[4547]: E0521 14:11:14.539581    4547 pod_workers.go:191] Error syncing pod f9d0cab0-f1f7-470d-b64f-8bbc36ebc82e ("kubernetes-dashboard-6c87f58d7c-f7txl_kubernetes-dashboard(f9d0cab0-f1f7-470d-b64f-8bbc36ebc82e)"), skipping: failed to "StartContainer" for "kubernetes-dashboard" with ImagePullBackOff: "Back-off pulling image \"registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/dashboard:v2.1.0@sha256:7f80b5ba141bead69c4fee8661464857af300d7d7ed0274cf7beecedc00322e6\""
May 21 14:11:17 minikube kubelet[4547]: E0521 14:11:17.535651    4547 pod_workers.go:191] Error syncing pod 981c80bc-461d-4f63-83a9-227b3e5af388 ("storage-provisioner_kube-system(981c80bc-461d-4f63-83a9-227b3e5af388)"), skipping: failed to "StartContainer" for "storage-provisioner" with ImagePullBackOff: "Back-off pulling image \"registry.cn-hangzhou.aliyuncs.com/google_containers/k8s-minikube/storage-provisioner:v5\""

</details>

**使用的操作系统版本**：win10

**Comment by dinever** [comment]
Hi,

Thanks for reporting the issue! There seems to be some issue with the aliyun hosted images.

I saw this issue reported by other users as well: https://github.com/AliyunContainerService/minikube/issues/51
