### ISSUE TITLE
Minikube  - Enable colors error message

### ISSUE THREAD

**Issue by fredcsfaria** [kubernetes/minikube#11470]
**Steps to reproduce the issue:** 

1. Run "minikube status" 

The message "Enable colors error"   shoud not be displayed in output.  This issue occurs in releases 1.20  and 1.19.  

 
![image](https://user-images.githubusercontent.com/52935549/119034997-76366f80-b985-11eb-8deb-c0c726aa2cbc.png)

![image](https://user-images.githubusercontent.com/52935549/119037637-9e739d80-b988-11eb-8d9a-e08bcba60aba.png)

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @fredcsfaria, I wasn't able to reproduce your error with minikube v1.20, can you produce this error with the latest version of minikube (v1.23.2)?

**Comment by spowelljr** [comment]
Hi @fredcsfaria, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by fredcsfaria** [comment]
Hi  Steven,
 The issue has been solved in 1.23.2 and can be closed.



    Em quarta-feira, 3 de novembro de 2021 15:12:41 BRT, Steven Powell ***@***.***> escreveu:  
 
 


Hi @fredcsfaria, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
