### ISSUE TITLE
Add a warning to minikube if flag options are different than that of the running VM

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1147]
Add a warning to minikube if a user passes in flag options that are different than the current VM.  
Related: #945

**Comment by hferentschik** [comment]
Same issue is tracked here in Minishift - https://github.com/minishift/minishift/issues/179.
I am wondering whether it makes most sense to split the _start_ into _create_ and _start_. This is aligning more with what docker-machine does as well and I think it would in the long run be more transparent for the user. With a single start you keep having unexpected border cases. Having dedicated _create_ and _start_ commands might be beneficial for implementing #886 as well. WDYT?

**Comment by aaron-prindle** [comment]
I am in favor of splitting the commands up, it would definitely help to solve some of the configuration issues we've been seeing.
There is an open issue regarding splitting minikube start into minikube create and start: https://github.com/kubernetes/minikube/issues/364

We can discuss the strategy for implementing this there.

**Comment by hferentschik** [comment]
> I am in favor of splitting the commands up, it would definitely help to solve some of the configuration issues we've been seeing.

Nice, I also think this is the best approach to solve these user issues we are seeing. 

> There is an open issue regarding splitting minikube start into minikube create and start: #364
> We can discuss the strategy for implementing this there.

Ok

**Comment by damnhipster** [comment]
+1 just came across this issue locally.

**Comment by Turbots** [comment]
This still seems to be the case (v0.28.2) and is quite annoying
