### ISSUE TITLE
Not able to run minikube at all !! 

### ISSUE THREAD

**Issue by mshahat** [kubernetes/minikube#1148]
Hi All, 

Need some high level guidance here. 

I've the following stack 

- macOS Sierra 10.12.3 (16D32)
- minikube version: v0.16.0
- kubectl Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"2017-02-17T20:49:14Z", GoVersion:"go1.8", Compiler:"gc", Platform:"darwin/amd64"}
- VirtualBox Version 5.1.14 r112924 (Qt5.6.2) 
- Docker for mac Version 1.13.1 (15353) - installed as well. 

I've installed both minikube and kubectl through homebrew. 
I've tried running it both through vmware fusion and virtualbox, i keep on having issues. 

minikube config
- "DriverName": "virtualbox"
- cat ~/.minikube/machines/minikube/config.json | grep ISO  ==> Revealed nothing ! 
- I found this however .minikube/cache/iso/minikube-v1.0.6.iso

The following is an example run: 

```
➜ ~ mshahat minikube start
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.

➜ ~ mshahat minikube addons list
- heapster: disabled
- ingress: disabled
- registry-creds: disabled
- addon-manager: enabled
- dashboard: enabled
- kube-dns: enabled

➜ ~ mshahat minikube dashboard

Could not find finalized endpoint being pointed to by kubernetes-dashboard: Temporary Error: Get https://192.168.99.101:8443/api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: dial tcp 192.168.99.101:8443: i/o timeout
Temporary Error: Get https://192.168.99.101:8443/api/v1/namespaces/kube-system/endpoints/kubernetes-dashboard: dial tcp 192.168.99.101:8443: i/o timeout
```

tried uninstalling the whole stack, rm -rf .kube .minikube few times ... with the same behaviour

**Comment by dlorenc** [comment]
Could you attach the output of:

```shell
kubectl get pods --all-namespaces
```

**Comment by mshahat** [comment]
Thanks @dlorenc  
```

➜ ~ mshahat kubectl get pods --all-namespaces
Unable to connect to the server: dial tcp 192.168.99.100:8443: i/o timeout
```

**Comment by mshahat** [comment]
any pointer here ?  thanks,

**Comment by mshahat** [comment]
Spending sometime today, i got it working. Please ensure that connection to the internet is a mandate to get minikube started - at least the first time. Depending on the connection, it can take quite a while to pull the docker images to the minikube machine. 

it's also good to mention that docker client has to be available on the machine running minikube. 

Thanks,

**Comment by r2d4** [comment]
@mshahat feel free to add some requirements to the readme.

Internet access is required to start up minikube (unless you supply the image yourself), however the docker client _doesn't_ need to be installed for minikube.

**Comment by ChillarAnand** [comment]
registry-creds pod fails to start. 

```
kube-system   kube-addon-manager-minikube              1/1       Running             0          1h        192.168.99.100   minikube
kube-system   kube-dns-v20-4wkzg                       3/3       Running             0          1h        172.17.0.3       minikube
kube-system   kubernetes-dashboard-td73h               1/1       Running             0          1h        172.17.0.2       minikube
kube-system   registry-creds-xzh3x                     0/1       RunContainerError   0          8m        172.17.0.4       minikube
kube-system   tiller-deploy-2923304080-qhm11           1/1       Running             0          47m       172.17.0.5       minikube
```

When I do desribe it shows, secrets not found.
```
  FirstSeen     LastSeen        Count   From                    SubObjectPath                   Type            Reason          Message
  ---------     --------        -----   ----                    -------------                   --------        ------          -------
  7m            7m              1       {default-scheduler }                                    Normal          Scheduled       Successfully assigned registry-creds-xzh3x to minikube
  7m            12s             25      {kubelet minikube}      spec.containers{registry-creds} Normal          Pulling         pulling image "upmcenterprises/registry-creds:1.5"
  7m            8s              25      {kubelet minikube}      spec.containers{registry-creds} Normal          Pulled          Successfully pulled image "upmcenterprises/registry-creds:1.5"
  7m            8s              25      {kubelet minikube}                                      Warning         FailedSync      Error syncing pod, skipping: failed to "StartContainer" for "registry-creds" with RunContainerError: "GenerateRunContainerOptions: secrets \"registry-creds\" not found"
```

Any help on how to fix it?
