### ISSUE TITLE
reflect: indirection through nil pointer to embedded struct [recovered]

### ISSUE THREAD

**Issue by JoseCabreraPalou2000** [kubernetes/minikube#11524]
**Los comandos necesarios para reproducir la incidencia**:

**El resultado completo del comando que ha fallado**: <details>

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by ilya-zuyev** [comment]
Going to close this issue too. Please feel free to create a new one describing your problem with details and providing logs and system info.
