### ISSUE TITLE
Minikube fails to create 192.168.x.0/24 network even if there is possibility, when there exists some colliding 192.168.y.0/20

### ISSUE THREAD

**Issue by jest** [kubernetes/minikube#11534]
**Steps to reproduce the issue:** 

1. `ip a | grep 192.168.48`
   ```
   192.168.48.1/20 brd 192.168.63.255 scope global br-370f35d5583f
   ```
2. `minikube start`

**Full output of `minikube logs` command:**
<details>
😄  minikube v1.20.0 on Linuxmint 18.3
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) .../ E0528 17:54:49.814491 2355545 network_create.go:79] failed to find free subnet for docker network minikube after 20 attempts: no free private network subnets found with given parameters (start: "192.168.57.0", step: 9, tries: 20)

❗  Unable to create dedicated network, this might result in cluster IP change after restart: un-retryable: no free private network subnets found with given parameters (start: "192.168.57.0", step: 9, tries: 20)

</details>

**Full output of failed command:**
<details>
I0528 18:25:02.206093 2401506 cli_runner.go:115] Run: docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}}, "ContainerIPs": [{{range $k,$v := .Containers }}"{{$v.IPv4Address}}",{{end}}]}"
W0528 18:25:02.243264 2401506 cli_runner.go:162] docker network inspect minikube --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}}, "ContainerIPs": [{{range $k,$v := .Containers }}"{{$v.IPv4Address}}",{{end}}]}" returned with exit code 1
I0528 18:25:02.243427 2401506 network_create.go:249] running [docker network inspect minikube] to gather additional debugging logs...
I0528 18:25:02.243454 2401506 cli_runner.go:115] Run: docker network inspect minikube
W0528 18:25:02.286604 2401506 cli_runner.go:162] docker network inspect minikube returned with exit code 1
I0528 18:25:02.286641 2401506 network_create.go:252] error running [docker network inspect minikube]: docker network inspect minikube: exit status 1
stdout:
[]

stderr:
Error: No such network: minikube
I0528 18:25:02.286677 2401506 network_create.go:254] output of [docker network inspect minikube]: -- stdout --
[]

-- /stdout --
** stderr **
Error: No such network: minikube

** /stderr **
I0528 18:25:02.286831 2401506 cli_runner.go:115] Run: docker network inspect bridge --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}}, "ContainerIPs": [{{range $k,$v := .Containers }}"{{$v.IPv4Address}}",{{end}}]}"
/ I0528 18:25:02.341162 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.345407 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.348366 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.351474 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.354687 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.358302 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.362020 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.365184 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.368507 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.373151 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.376684 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.380436 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.384307 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.386713 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.389935 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.393880 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.399530 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.402659 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
I0528 18:25:02.405191 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
- I0528 18:25:02.407748 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}
E0528 18:25:02.407782 2401506 network_create.go:79] failed to find free subnet for docker network minikube after 20 attempts: no free private network subnets found with given parameters (start: "192.168.57.0", step: 9, tries: 20)
W0528 18:25:02.407888 2401506 out.go:235] ❗  Unable to create dedicated network, this might result in cluster IP change after restart: un-retryable: no free private network subnets found with given parameters (start: "192.168.57.0", step: 9, tries: 20)

❗  Unable to create dedicated network, this might result in cluster IP change after restart: un-retryable: no free private network subnets found with given parameters (start: "192.168.57.0", step: 9, tries: 20)

</details>

On my machine there is an offending network `192.168.48.0/20`, created by Docker, that collides with `192.168.49.0/24` that minikube wants to create. Although there is a lot of CIDR "space" in `192.168.64.0` - `192.168.254.0`, minikube is not able to find out due to looping 20 times checking the same range over again:

```
I0528 18:25:02.345407 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}     
I0528 18:25:02.348366 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}     
I0528 18:25:02.351474 2401506 network.go:215] skipping subnet 192.168.48.0/20 that is taken: &{IP:192.168.48.0 Netmask:255.255.240.0 Prefix:20 CIDR:192.168.48.0/20 Gateway:192.168.48.1 ClientMin:192.168.48.2 ClientMax:192.168.63.254 Broadcast:192.168.63.255 Interface:{IfaceName:br-370f35d5583f IfaceIPv4:192.168.48.1 IfaceMTU:1500 IfaceMAC:02:42:1c:f4:d6:49}}     
[...]
```

The bug is in probably in simplistic choosing the next subnet (lines 220-227):

https://github.com/kubernetes/minikube/blob/0de45800895549cb49b1e4c5722430e8990bc89e/pkg/network/network.go#L196-L227

For my example, if the initial tried network is `192.168.49.0/24`, it is replaced with `192.168.48.0` in line 202. Increasing it by `step == 9` in line 225 gives `192.168.57.0`, which happen to fall inside the same colliding network and the logic repeats in the next loop. After 20 times, the minikube gives up and the error is reported.

(A minor bug is that the reported network is incorrect: `192.168.57.0` mentioned in the error message is a modified value in `startSubnet`, not the one passed as the argument to `FreeSubnet`)

The solution could be to continue the next loop pass with the `max(next_network_after_colliding_scope; nextSubnet)` instead of `nextSubnet`.

Note that my config is nothing special: by default Docker creates `/20` networks in `192.168.x.0` space after it runs out of networks `172.17.0.0/16` to `172.31.0.0/16`, which is not so many for intensive `docker-compose` use...

**Comment by weshouman** [comment]
Following is a workaround until the issue is fixed  

## Manual Network Creation
- Create a `br10.xml` network file as following
```xml
<network>
  <name>br10</name>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='br10' stp='on' delay='0'/>
  <ip address='192.168.30.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.30.50' end='192.168.30.200'/>
    </dhcp>
  </ip>
</network>
```
- `sudo virsh net-list`: to check no previous network with the name *br10* existed
- `sudo virsh net-create br10.xml`: to create the network
- `sudo virsh net-list`: to check the *br10* network is created
- `sudo virsh net-start br10`: to start the newly created network
- `sudo virsh net-autostart br10`: to auto start (enable) the newly created network upon reboot
- `minikube start --vm-driver kvm2 --network br10 --profile minikubeN`: to start a cluster using the created network using a new profile

Reference: [How to create and configure bridge networking for kvm in Linux](https://computingforgeeks.com/how-to-create-and-configure-bridge-networking-for-kvm-in-linux/)
