### ISSUE TITLE
Minikube not starting

### ISSUE THREAD

**Issue by dhanujsirohi** [kubernetes/minikube#11538]
**Steps to reproduce the issue:** 

1.sudo minikube start --driver=none
2. 
3.

**Full output of `minikube logs` command:**
<details>

root@ubuntu:~# sudo minikube start --driver=none
* minikube v1.20.0 on Ubuntu 14.04
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 14.04.5 LTS
* Preparing Kubernetes v1.20.2 on Docker  ...

X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
flag provided but not defined: --format
See 'docker info --help'.

* 
╭──────────────────────────────────────────────────────────────────╮
│                                                                  │
│    * If the above advice does not help, please let us know:      │
│      https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                  │
│    * Please attach the following file to the GitHub issue:       │
│    * - /home/hduser/.minikube/logs/lastStart.txt                 │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯

root@ubuntu:~# 

</details>

**Full output of failed command:**
<details>

</details>

**Comment by dinever** [comment]
Hi @dhanujsirohi, thanks for reporting the issue!

`docker info --format` was introduced in [1.13.0](https://github.com/moby/moby/pull/23808), it appears that you are using an older version of Docker, 

Could you upgrade your docker engine to version 18.09 or later and try minikube again? https://minikube.sigs.k8s.io/docs/drivers/docker/

Thanks!

**Comment by spowelljr** [comment]
Hi @dhanujsirohi, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
