### ISSUE TITLE
minikube driver flag is renamed to vm-driver?

### ISSUE THREAD

**Issue by halfzebra** [kubernetes/minikube#11548]
While looking at the documentation https://minikube.sigs.k8s.io/docs/drivers/docker/, I've noticed that it suggests that the parameter for specifying a driver is called `driver`, while it's actually `vm-driver` in the latest version.

Is this something that needs fixing or am I missing something?

**Comment by dinever** [comment]
Hi @halfzebra, thanks for reporting this issue! Could you share your output of `minikube version`?

`vm-driver` has been deprecated and renamed to `driver` in [v1.8.0](https://github.com/kubernetes/minikube/releases/tag/v1.8.0): e2ce45c6f0ca9fe51bd37b2fd478ec4ec69dd181

From the latest version of minikube(v1.20.0) I'm seeing:

```
--driver='': Driver is one of: virtualbox, parallels, vmwarefusion, hyperkit, vmware, docker, ssh (defaults to auto-detect)
--vm-driver='': DEPRECATED, use `driver` instead.
```

**Comment by halfzebra** [comment]
Hi @dinever!

Thanks for your reply, I've actually been using an outdated version, which relied on a deprecated format.

Thanks for clarifying this!
