### ISSUE TITLE
Error while enabling ingress in minikube

### ISSUE THREAD

**Issue by IndrajeetTech2020** [kubernetes/minikube#11540]
indrajeet@indrajeet-X540LA:~/Development$ minikube addons enable ingress
    ▪ Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
🔎  Verifying ingress addon...

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.14.0/kubectl apply -f /etc/kubernetes/addons/ingress-configmap.yaml -f /etc/kubernetes/addons/ingress-rbac.yaml -f /etc/kubernetes/addons/ingress-dp.yaml: exit status 1
stdout:
namespace/ingress-nginx unchanged
configmap/ingress-nginx-controller unchanged
configmap/tcp-services unchanged
configmap/udp-services unchanged
serviceaccount/ingress-nginx unchanged
clusterrole.rbac.authorization.k8s.io/ingress-nginx unchanged
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged
role.rbac.authorization.k8s.io/ingress-nginx unchanged
rolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged
serviceaccount/ingress-nginx-admission unchanged
clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
role.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
service/ingress-nginx-controller-admission unchanged
service/ingress-nginx-controller unchanged
deployment.apps/ingress-nginx-controller configured
job.batch/ingress-nginx-admission-create unchanged
job.batch/ingress-nginx-admission-patch unchanged

stderr:
error: unable to recognize "/etc/kubernetes/addons/ingress-dp.yaml": no matches for kind "ValidatingWebhookConfiguration" in version "admissionregistration.k8s.io/v1"
]

╭─────────────────────────────────────────────────────────────────────────────╮
│                                                                             │
│    😿  If the above advice does not help, please let us know:               │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose             │
│                                                                             │
│    Please attach the following file to the GitHub issue:                    │
│    - /tmp/minikube_addons_a1ac1680e491a42b80edb3a9198c348f23a72656_0.log    │

**Comment by dinever** [comment]
Hi @IndrajeetTech2020, thanks for reporting the issue!

```
minikube/binaries/v1.14.0/kubectl
```

It looks like you are running Kubernetes v1.14.0. However, `igress-nginx>=0.40.0` requires Kubernetes **v1.16** or newer: https://github.com/kubernetes/ingress-nginx/releases/tag/controller-v0.40.0

If possible, could you try upgrade the k8s cluster to a newer version and enable the addon again?

```
minikube start --kubernetes-version='stable'
```

**Comment by spowelljr** [comment]
Hi @IndrajeetTech2020, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
