### ISSUE TITLE
minikube start problem

### ISSUE THREAD

**Issue by oushihou** [kubernetes/minikube#11541]
**重现问题所需的命令**：minikube start --vm-driver=none

**失败的命令的完整输出**：<details>
* minikube v1.20.0 on Centos 7.9.2009
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is CentOS Linux 7 (Core)
* Preparing Kubernetes v1.20.2 on Docker  ...

X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
        panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc00059d2a8)
        /usr/local/go/src/text/template/exec.go:170 +0x1b5
panic(0x56414b55b7a0, 0x56414b89cae0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x56414b714780, 0xc0002c85c0, 0x99, 0xc0002fe6e0, 0x2, 0x2, 0x0, 0x56414b953da0, 0x56414b55b7a0)
        /usr/local/go/src/reflect/value.go:883 +0x39e
text/template.(*state).evalField(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0x7ffce368b759, 0xc, 0x56414b924ba0, 0xc00033fb30, 0xc0003c4290, 0x1, ...)
        /usr/local/go/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0x56414b714780, 0xc0002c85c0, 0x99, 0x56414b924ba0, 0xc00033fb30, 0xc0003c4270, ...)
        /usr/local/go/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0xc00033fb30, 0xc0003c4290, 0x1, 0x1, 0x56414b6004e0, 0x56414c9509c8, ...)
        /usr/local/go/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0xc00033faa0, 0x56414b6004e0, 0x56414c9509c8, 0x99, 0xd0, 0x56414b6f4360, ...)
        /usr/local/go/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0xc00023e4e0, 0xc00033c438, 0xc000402750, 0xc00059d0e0)
        /usr/local/go/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0x56414b924a20, 0xc0003a1020)
        /usr/local/go/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0x56414b924c60, 0xc00033e2a0)
        /usr/local/go/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc0002c8500, 0x56414b8be4a0, 0xc00023dad0, 0x56414b714780, 0xc0002c85c0, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x56414b94eac0, 0xc000403ba0, 0x0, 0xc000449300, 0x1, 0x1, 0xc000343e00, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/system/info.go:490 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc000566840, 0x56414b94eac0, 0xc000403ba0, 0xc000448be0, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x37c
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc000566840, 0xc0004125c0, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000566840, 0xc00056b720, 0x2, 0x2, 0xc000566840, 0xc00056b720)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000375080, 0xc00056b710, 0x3, 0x3)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc000403ba0, 0x56414b8c0ac0, 0xc0000ce010)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3

*
╭──────────────────────────────────────────────────────────────────╮
│                                                                  │
│    * If the above advice does not help, please let us know:      │
│      https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                  │
│    * Please attach the following file to the GitHub issue:       │
│    * - /home/oushihou/.minikube/logs/lastStart.txt               │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯

</details>

**`minikube logs`命令的输出**： <details>
*
* ==> Audit <==
* |---------|------|---------|------|---------|------------|----------|
| Command | Args | Profile | User | Version | Start Time | End Time |
|---------|------|---------|------|---------|------------|----------|
|---------|------|---------|------|---------|------------|----------|

*
* ==> Last Start <==
* Log file created at: 2021/05/31 09:33:27
Running on machine: localhost
Binary: Built with gc go1.16.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0531 09:33:27.836006    5968 out.go:291] Setting OutFile to fd 1 ...
I0531 09:33:27.836082    5968 out.go:338] TERM=xterm,COLORTERM=, which probably does not support color
I0531 09:33:27.836084    5968 out.go:304] Setting ErrFile to fd 2...
I0531 09:33:27.836085    5968 out.go:338] TERM=xterm,COLORTERM=, which probably does not support color
I0531 09:33:27.836164    5968 root.go:316] Updating PATH: /home/oushihou/.minikube/bin
W0531 09:33:27.836247    5968 root.go:291] Error reading config file at /home/oushihou/.minikube/config/config.json: open /home/oushihou/.minikube/config/config.json: no such file or directory
I0531 09:33:27.836325    5968 out.go:298] Setting JSON to false
I0531 09:33:27.839450    5968 start.go:108] hostinfo: {"hostname":"localhost.localdomain","uptime":13378,"bootTime":1622411430,"procs":128,"os":"linux","platform":"centos","platformFamily":"rhel","platformVersion":"7.9.2009","kernelVersion":"3.10.0-1160.el7.x86_64","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"c64adeea-36c7-4287-bde9-17fbf4b80da6"}
I0531 09:33:27.839556    5968 start.go:118] virtualization:
I0531 09:33:27.840348    5968 out.go:170] * minikube v1.20.0 on Centos 7.9.2009
I0531 09:33:27.841058    5968 exec_runner.go:52] Run: systemctl --version
I0531 09:33:27.841411    5968 notify.go:169] Checking for updates...
I0531 09:33:27.843646    5968 driver.go:322] Setting default libvirt URI to qemu:///system
I0531 09:33:27.859485    5968 out.go:170] * Using the none driver based on existing profile
I0531 09:33:27.859508    5968 start.go:276] selected driver: none
I0531 09:33:27.859512    5968 start.go:718] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.1.136 Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false}
I0531 09:33:27.859562    5968 start.go:729] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0531 09:33:27.859964    5968 cni.go:93] Creating CNI manager for ""
I0531 09:33:27.859969    5968 cni.go:147] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0531 09:33:27.859974    5968 start_flags.go:273] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.22@sha256:7cc3a3cb6e51c628d8ede157ad9e1f797e8d22a1b3cedc12d3f1999cb52f962e Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.1.136 Port:8443 KubernetesVersion:v1.20.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false}
I0531 09:33:27.860730    5968 out.go:170] * Starting control plane node minikube in cluster minikube
I0531 09:33:27.860798    5968 profile.go:148] Saving config to /home/oushihou/.minikube/profiles/minikube/config.json ...
I0531 09:33:27.860982    5968 cache.go:194] Successfully downloaded all kic artifacts
I0531 09:33:27.861051    5968 start.go:313] acquiring machines lock for minikube: {Name:mk338558db1bc8fa5e3c5ad3909a9e3e0f715bca Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0531 09:33:27.861518    5968 start.go:317] acquired machines lock for "minikube" in 429.937µs
I0531 09:33:27.861599    5968 start.go:93] Skipping create...Using existing machine configuration
I0531 09:33:27.861605    5968 fix.go:55] fixHost starting: m01
W0531 09:33:27.861721    5968 none.go:130] unable to get port: "minikube" does not appear in /home/oushihou/.kube/config
I0531 09:33:27.861731    5968 api_server.go:148] Checking apiserver status ...
I0531 09:33:27.861745    5968 exec_runner.go:52] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0531 09:33:27.878046    5968 api_server.go:152] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0531 09:33:27.878081    5968 exec_runner.go:52] Run: sudo systemctl is-active --quiet service kubelet
I0531 09:33:27.890633    5968 fix.go:108] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0531 09:33:27.890648    5968 fix.go:134] unexpected machine state, will restart: <nil>
I0531 09:33:27.901875    5968 out.go:170] * Restarting existing none bare metal machine for "minikube" ...
I0531 09:33:27.904083    5968 profile.go:148] Saving config to /home/oushihou/.minikube/profiles/minikube/config.json ...
I0531 09:33:27.904229    5968 start.go:267] post-start starting for "minikube" (driver="none")
I0531 09:33:27.904234    5968 start.go:277] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0531 09:33:27.904270    5968 exec_runner.go:52] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0531 09:33:27.917732    5968 main.go:128] libmachine: Couldn't set key CPE_NAME, no corresponding struct field found
I0531 09:33:27.917764    5968 main.go:128] libmachine: Couldn't set key , no corresponding struct field found
I0531 09:33:27.917770    5968 main.go:128] libmachine: Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
I0531 09:33:27.917778    5968 main.go:128] libmachine: Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
I0531 09:33:27.917787    5968 main.go:128] libmachine: Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
I0531 09:33:27.917791    5968 main.go:128] libmachine: Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
I0531 09:33:27.917795    5968 main.go:128] libmachine: Couldn't set key , no corresponding struct field found
I0531 09:33:27.918484    5968 out.go:170] * OS release is CentOS Linux 7 (Core)
I0531 09:33:27.918517    5968 filesync.go:118] Scanning /home/oushihou/.minikube/addons for local assets ...
I0531 09:33:27.918720    5968 filesync.go:118] Scanning /home/oushihou/.minikube/files for local assets ...
I0531 09:33:27.918735    5968 start.go:270] post-start completed in 14.498194ms
I0531 09:33:27.918740    5968 fix.go:95] none is local, skipping auth/time setup (requires ssh)
I0531 09:33:27.918743    5968 fix.go:57] fixHost completed within 57.140864ms
I0531 09:33:27.918745    5968 start.go:80] releasing machines lock for "minikube", held for 57.22297ms
I0531 09:33:27.919107    5968 exec_runner.go:52] Run: sudo systemctl is-active --quiet service containerd
I0531 09:33:27.919287    5968 exec_runner.go:52] Run: curl -sS -m 2 https://k8s.gcr.io/
I0531 09:33:27.932567    5968 exec_runner.go:52] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/dockershim.sock
image-endpoint: unix:///var/run/dockershim.sock
" | sudo tee /etc/crictl.yaml"
I0531 09:33:27.954742    5968 exec_runner.go:52] Run: sudo systemctl unmask docker.service
I0531 09:33:28.008714    5968 exec_runner.go:52] Run: sudo systemctl enable docker.socket
I0531 09:33:28.049179    5968 exec_runner.go:52] Run: sudo systemctl cat docker.service
I0531 09:33:28.061420    5968 exec_runner.go:52] Run: sudo systemctl daemon-reload
I0531 09:33:28.106465    5968 exec_runner.go:52] Run: sudo systemctl restart docker
I0531 09:33:28.769394    5968 exec_runner.go:52] Run: docker version --format {{.Server.Version}}
I0531 09:33:28.798136    5968 out.go:197] * Preparing Kubernetes v1.20.2 on Docker  ...
I0531 09:33:28.798742    5968 exec_runner.go:52] Run: grep 127.0.0.1    host.minikube.internal$ /etc/hosts
I0531 09:33:28.800702    5968 preload.go:98] Checking if preload exists for k8s version v1.20.2 and runtime docker
I0531 09:33:29.044813    5968 preload.go:123] Found remote preload: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.lz4
I0531 09:33:29.044890    5968 exec_runner.go:52] Run: docker images --format {{.Repository}}:{{.Tag}}
I0531 09:33:29.076203    5968 exec_runner.go:52] Run: sudo cat /var/lib/docker/image/overlay2/repositories.json
I0531 09:33:29.092331    5968 exec_runner.go:52] Run: which lz4
I0531 09:33:29.092942    5968 kubeadm.go:862] preload failed, will try to load cached images: getting file asset: open: open /home/oushihou/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v10-v1.20.2-docker-overlay2-amd64.tar.lz4: no such file or directory
I0531 09:33:29.092975    5968 exec_runner.go:52] Run: docker info --format {{.CgroupDriver}}
I0531 09:33:29.170302    5968 exec_runner.go:52] Run: sudo systemctl is-active --quiet service docker
I0531 09:33:29.189644    5968 out.go:170]
W0531 09:33:29.189792    5968 out.go:235] X Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
        panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc00059d2a8)
        /usr/local/go/src/text/template/exec.go:170 +0x1b5
panic(0x56414b55b7a0, 0x56414b89cae0)
        /usr/local/go/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x56414b714780, 0xc0002c85c0, 0x99, 0xc0002fe6e0, 0x2, 0x2, 0x0, 0x56414b953da0, 0x56414b55b7a0)
        /usr/local/go/src/reflect/value.go:883 +0x39e
text/template.(*state).evalField(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0x7ffce368b759, 0xc, 0x56414b924ba0, 0xc00033fb30, 0xc0003c4290, 0x1, ...)
        /usr/local/go/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0x56414b714780, 0xc0002c85c0, 0x99, 0x56414b924ba0, 0xc00033fb30, 0xc0003c4270, ...)
        /usr/local/go/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0xc00033fb30, 0xc0003c4290, 0x1, 0x1, 0x56414b6004e0, 0x56414c9509c8, ...)
        /usr/local/go/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0xc00033faa0, 0x56414b6004e0, 0x56414c9509c8, 0x99, 0xd0, 0x56414b6f4360, ...)
        /usr/local/go/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0xc00023e4e0, 0xc00033c438, 0xc000402750, 0xc00059d0e0)
        /usr/local/go/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0x56414b924a20, 0xc0003a1020)
        /usr/local/go/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc00059d228, 0x56414b714780, 0xc0002c85c0, 0x99, 0x56414b924c60, 0xc00033e2a0)
        /usr/local/go/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc0002c8500, 0x56414b8be4a0, 0xc00023dad0, 0x56414b714780, 0xc0002c85c0, 0x0, 0x0)
        /usr/local/go/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
        /usr/local/go/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x56414b94eac0, 0xc000403ba0, 0x0, 0xc000449300, 0x1, 0x1, 0xc000343e00, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/docker/cli/cli/command/system/info.go:490 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc000566840, 0x56414b94eac0, 0xc000403ba0, 0xc000448be0, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x37c
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc000566840, 0xc0004125c0, 0x0, 0x2, 0x0, 0x0)
        /go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000566840, 0xc00056b720, 0x2, 0x2, 0xc000566840, 0xc00056b720)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000375080, 0xc00056b710, 0x3, 0x3)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc000403ba0, 0x56414b8c0ac0, 0xc0000ce010)
        /go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
        /go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3

W0531 09:33:29.189845    5968 out.go:424] no arguments passed for "* \n" - returning raw string
W0531 09:33:29.189851    5968 out.go:235] *
W0531 09:33:29.189860    5968 out.go:424] no arguments passed for "* If the above advice does not help, please let us know:\n" - returning raw string
W0531 09:33:29.189862    5968 out.go:424] no arguments passed for "  https://github.com/kubernetes/minikube/issues/new/choose\n\n" - returning raw string
W0531 09:33:29.189864    5968 out.go:424] no arguments passed for "* Please attach the following file to the GitHub issue:\n" - returning raw string
W0531 09:33:29.189891    5968 out.go:424] no arguments passed for "* If the above advice does not help, please let us know:\n  https://github.com/kubernetes/minikube/issues/new/choose\n\n* Please attach the following file to the GitHub issue:\n* - /home/oushihou/.minikube/logs/lastStart.txt\n\n" - returning raw string
W0531 09:33:29.190430    5968 out.go:235] ╭──────────────────────────────────────────────────────────────────╮
W0531 09:33:29.190456    5968 out.go:235] │                                                                  │
W0531 09:33:29.190460    5968 out.go:235] │    * If the above advice does not help, please let us know:      │
W0531 09:33:29.190462    5968 out.go:235] │      https://github.com/kubernetes/minikube/issues/new/choose    │
W0531 09:33:29.190465    5968 out.go:235] │                                                                  │
W0531 09:33:29.190467    5968 out.go:235] │    * Please attach the following file to the GitHub issue:       │
W0531 09:33:29.190470    5968 out.go:235] │    * - /home/oushihou/.minikube/logs/lastStart.txt               │
W0531 09:33:29.190472    5968 out.go:235] │                                                                  │
W0531 09:33:29.190475    5968 out.go:235] ╰──────────────────────────────────────────────────────────────────╯
W0531 09:33:29.190478    5968 out.go:235]

*
* The control plane node must be running for this command
  To start a cluster, run: "minikube start"

</details>

**使用的操作系统版本**：Centos 7.9.2009

**Comment by dinever** [comment]
Hi @oushihou, thanks for reporting the issue!

This seems to be related to #8798 and #10589 

Could you try the following command and see what happens?

```
docker info --format "{{.CgroupDriver}}"
```

If it crashes, could you provide the result of `docker info`? Thanks!

**Comment by spowelljr** [comment]
Hi @oushihou, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
