### ISSUE TITLE
Add explanations for all minikube error codes

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/minikube#11555]
We now populate documentation for all error/exit codes at https://minikube.sigs.k8s.io/docs/contrib/errorcodes/, but most of them don't have a comment explaining what they are. We should add those.

**Comment by sharmarajdaksh** [comment]
Hey @sharifelgamal, I can work on this if you could let me know some way to understand the meaning of the error codes. TIA!

**Comment by sharifelgamal** [comment]
@sharmarajdaksh, my plan was to go through the code and for each error string and figure out where in the code it was called, then describe to type of error. 

So for example, MK_INTERRUPTED is only used with `reason.Interrupted` (as seen in https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/reason.go#L67), which is only used in https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/mount.go#L188. This tells us the MK_INTERRUPTED is only used when minikube was interrupted by Ctrl+C or some other signal. So we would add a comment above https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/reason.go#L67 saying something like `// minikube was interrupted by a signal`.

**Comment by sharmarajdaksh** [comment]
I see. It might take a bit for me to get a general idea of the codebase, but I think I can slowly make way through these exit codes.

**Comment by sharifelgamal** [comment]
Sounds great! Don't hesitate to reach out if you have questions.

**Comment by sharmarajdaksh** [comment]
@sharifelgamal one thing that I'm not sure about:
Should I just be adding these commends to https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/reason.go
Or should I be also adding these error descriptions to https://github.com/kubernetes/minikube/blob/master/site/content/en/docs/contrib/errorcodes.en.md?

**Comment by sharifelgamal** [comment]
Add them as comments in https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/reason.go, we have machinery to automatically add it to the documentation
