### ISSUE TITLE
Is there any configuration file that can change my remote vm’s IP address(using ssh driver)

### ISSUE THREAD

**Issue by masontien** [kubernetes/minikube#11578]
❓ I want to delete my cluster (--driver=ssh), but my remote vm IP address has changed.  Is there any configuration file that can change my remote vm’s IP address?

**Comment by masontien** [comment]
I found in `~/.minikube/profiles/minikube/config.json` 😊

**Comment by afbjorklund** [comment]
That is the workaround for now, suggest /etc/hosts (or DNS)
