### ISSUE TITLE
Odd pulsing progress bar

### ISSUE THREAD

**Issue by briandealwis** [kubernetes/minikube#11581]
**Steps to reproduce the issue:** 

This is purely cosmetic.

1. minikube start --driver docker --container-runtime containerd
2. watch minikube download kicbase and preloaded-images compete

![minikube-pulsing-progress](https://user-images.githubusercontent.com/202851/120813844-4c03b680-c51c-11eb-975a-553f29c337c8.gif)

**Comment by afbjorklund** [comment]
This is supposed to use two lines, one for the kicbase image and one for the preloaded images.

**Comment by spowelljr** [comment]
Closing this issue in favor of #11069 due to good discussion of the problem on the other one.

Please follow along there @briandealwis, thanks!
