### ISSUE TITLE
Minikube hangs at "minikube addons enable ingress" steps

### ISSUE THREAD

**Issue by arjunsreepad** [kubernetes/minikube#11591]
When I run 

> minikube addons enable ingress

system hangs and no response

**Comment by soluchok** [comment]
I have the same problem, seems like it is related to the latest OS kernel.
 `Linux desktop 5.10.36-2-MANJARO`  - does not work.

**Comment by ishanjain28** [comment]
Hey @arjunsreepad Does the system hang or is it the minikube process that appears to be stuck?

**Comment by spowelljr** [comment]
Hi @arjunsreepad, thanks for reporting your issue!

This is a duplicate of #10544, in order to keep all discussion of this issue centralized I'm going to close this issue.

Please follow along with #10544 and contribute any findings there, thanks for your understanding!
