### ISSUE TITLE
Create the addon-manager at cluster start time.

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#116]
I believe we just need to add this pod spec as a static pod in the kubelet initialization:
https://github.com/kubernetes/kubernetes/pull/23600/commits/3e1c0b59517c8ceb39dfdc59e1748688f5f86688#diff-ffcd99bc6b27b0dfad18312db1a4ef9f

**Comment by dlorenc** [comment]
Ref #3

**Comment by luxas** [comment]
This should be pretty straightforward. We just have to put the config file in `/etc/kubernetes/manifests/`, and pass that path to kubelet

But we should think about how we should package the manifest. Should it be packaged with the iso? Maybe that's the best thing to do...

**Comment by dlorenc** [comment]
Yeah, I think that's best. We'll have to update the iso-url at the same time we change the kubelet config, but that's exactly why we just made that a versioned URL.

**Comment by dlorenc** [comment]
Fixed with #128

**Comment by luxas** [comment]
Same, if this is working with v0.1, set the v0.1 milestone
