### ISSUE TITLE
Curl still not working?

### ISSUE THREAD

**Issue by ryankbales** [kubernetes/minikube#1161]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): `v0.16.0`

**Environment**: `Development/Local`
- **OS** (e.g. from /etc/os-release): `macOS Sierra 10.12.1`
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): `"DriverName": "virtualbox"`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO`): No Info
- **Install tools**: na
- **Others**: na

**What happened**:  Downloaded v0.16.0 in hopes to see `curl` added again based on https://github.com/kubernetes/minikube/pull/1065.  Verify I'm running v0.16.0, `ssh` into my local minikube installation using `minikube ssh`, run `curl google.com`, and receive `-bash: curl: command not found`

**What you expected to happen**: I expect a normal `curl` response.

**How to reproduce it** (as minimally and precisely as possible): `minikube ssh` and run a curl command.

**Related past issue**: https://github.com/kubernetes/minikube/issues/1059

There is a slight chance I'm missing something obvious here, but I'm uncertain of where else to look.  Thanks.

**Comment by ankon** [comment]
In terms of "obvious": Did you recreate your minikube VM after updating the minikube binary?

**Comment by ryankbales** [comment]
@ankon I did just uninstall and reinstall the `docker-machine-driver-xhyve`, if that's what you're talking about.  Otherwise, I'm unclear what you mean?

**Comment by ryankbales** [comment]
I also made sure I was using the `xhyve` driver and still now success.

**Comment by r2d4** [comment]
The xhyve driver shouldn't have anything to do with curl inside the VM.

Can you verify the checksum of the image you're running?
```
$ shasum -a 256 ~/.minikube/cache/iso/minikube-v1.0.6.iso 
78b0a8ca1fb76886e6402e7b8e68a44dbcf4a2b279258260dcb6b9b6a721d3b0  /Users/mrick/.minikube/cache/iso/minikube-v1.0.6.iso
```

If they are different, then you'll need to follow these steps
These steps should work:

1. `minikube delete`
2. Delete the cached image `rm ~/.minikube/cache/iso/minikube-v1.0.6.iso`
3. `minikube start`

**Comment by ryankbales** [comment]
@r2d4 Thanks!  That was it.  Not sure if that's documented as a required step for upgrading anywhere, (I couldn't find anything), or if I should just know that.

**Comment by r2d4** [comment]
Curious, was it a different version other than v1.0.6?  We might have accidentally pushed a new version of the image without bumping the version.  And we don't check the checksum if you're using the default version.

**Comment by ryankbales** [comment]
`minikube-v1.0.2.iso` is what I had in the cached iso.

**Comment by ryankbales** [comment]
@r2d4 Was this user error on my part or did I stumble across a legit bug?  Thanks for the quick response and resolution either way.  :clinking_glasses:

**Comment by r2d4** [comment]
I guess its a bit confusing on our part.  You won't get the updated minikube image until you delete and recreate the VM with a delete/start.  Curl was added in a recent minikube image, and wasn't in v1.0.2.  The "bug" is more of we dont have a way to do an in-place upgrade without a delete/start

**Comment by ryankbales** [comment]
Got it.  Thanks again.
