### ISSUE TITLE
CRIO runtime & registry addon

### ISSUE THREAD

**Issue by commarmi76** [kubernetes/minikube#11621]
minikube version: v1.20.0

**Steps to reproduce the issue:**

1. Start minikube using crio as a container runtime and registry addon

 minikube start --driver=kvm2 --cpus=8 --memory=8192m --container-runtime=crio --insecure-registry "192.168.39.0/24" --addons registry

2. Push image using minikube ip:

podman push --tls-verify=false $(minikube ip):5000/test-img

3. Access the shell via minikube ssh

4. Check crio service: ps fax|grep "/usr/bin/crio"

2098 ?        Ssl    0:22 **/usr/bin/crio –log-level=debug**

You can see there is no “--insecure-registry” in the command line.

### If you try to create a pod it will fail because crio uses https to pull the image.
kubectl run test1 --image=$(minikube ip):5000/test-img

5. To solve the problem you have to restart crio service.

minikube ssh
sudo systemctl restart crio

after that you can see:

ps fax|grep "/usr/bin/crio"

4004 ?        Ssl    0:00 **/usr/bin/crio --log-level=debug --insecure-registry 10.96.0.0/12 --insecure-registry 192.168.39.0/24**

now there are two “--insecure-registry” in the command line and crio can pull the image using http.

**Comment by afbjorklund** [comment]
I think the images were usually accessed through the localhost:5000 proxy (hack), to avoid having to configure runtime

**Comment by commarmi76** [comment]
> I think the images were usually accessed through the localhost:5000 proxy (hack), to avoid having to configure runtime

I'm not able to make this solution (registry proxy) to work, maybe you could write some instructions to help me.

**Comment by afbjorklund** [comment]
Like this: `kubectl run test1 --image=localhost:5000/test-img`

I think most of the documentation was removed when it was deprecated, but maybe the registry has some docs somewhere...

https://minikube.sigs.k8s.io/docs/handbook/addons/

https://minikube.sigs.k8s.io/docs/handbook/registry/

**Comment by commarmi76** [comment]
> Like this: `kubectl run test1 --image=localhost:5000/test-img`
> 
> I think most of the documentation was removed when it was deprecated, but maybe the registry has some docs somewhere...
> 
> https://minikube.sigs.k8s.io/docs/handbook/addons/
> 
> https://minikube.sigs.k8s.io/docs/handbook/registry/

It's not working for me, I've got : _"ErrImagePull: "rpc error: code = Unknown desc = error pinging docker registry localhost:5000: Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: i/o timeout"_

PD: I forgot to mention I'm using podman

**Comment by afbjorklund** [comment]
This looks OK: `podman push --tls-verify=false $(minikube ip):5000/test-img`
