### ISSUE TITLE
Pausing apiserver and then running minikube status reports stopped apiserver

### ISSUE THREAD

**Issue by andriyDev** [kubernetes/minikube#11628]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube pause
3. minikube status

MInikube then hangs.

**Comment by andriyDev** [comment]
This seems to be due to my Linux not putting cgroup freezer files in the expected directory. While #11629 will fix the hang itself, it doesn't fix the underlying trouble of not checking the correct place for freezer files. I'll need to look into this more to see where my freezer files go. The main issue this produces at the moment is that `minikube status` reports the API server is `Stopped` when it should be `Paused`.

**Comment by klaases** [comment]
Hi @andriyDev,  I see that https://github.com/kubernetes/minikube/pull/11629 has been merged.

I have not yet encountered this - are you still experiencing this issue?

**Comment by andriyDev** [comment]
I no longer use minikube, and no one else has reported this so I'll just close the issue.
