### ISSUE TITLE
Pod does not see files in persistent volume claim, when following official Kubernetes tutorial.

### ISSUE THREAD

**Issue by adamjablonowski** [kubernetes/minikube#11635]
**Steps to reproduce the issue:** 

1. Install minikube on linux desktop
2. Copy all comands from https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/ in terminal
3. kubectl exec -it task-pv-pod -- /bin/bash
4. ls /usr/share/nginx/html
5. See the folder is empty

I have installed minikube in linux system. I can not setup a persistent volume claim, so a pod using this pvc could see files placed in this pvc on host machine.
I have followed this tutorial https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/.
Every thing goes like in the tutorial, except at the and pod does not see index.html file placed in persistent volume claim.
How to set up persistent volume claim in Minikube?

**Comment by afbjorklund** [comment]
Sorry, cannot reproduce this. Did you forget to use `minikube ssh` ?

```console
minikube ssh
docker@minikube:~$ sudo mkdir /mnt/data
docker@minikube:~$ sudo sh -c "echo 'Hello from Kubernetes storage' > /mnt/data/index.html"
docker@minikube:~$ cat /mnt/data/index.html
Hello from Kubernetes storage
docker@minikube:~$ logout
```

(do the rest of the commands, not shown here)

```console
$ kubectl exec -it task-pv-pod -- /bin/bash
root@task-pv-pod:/# ls /usr/share/nginx/html
index.html
root@task-pv-pod:/# apt update
Get:1 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:2 http://deb.debian.org/debian buster InRelease [121 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [292 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7907 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [10.9 kB]
Fetched 8449 kB in 2s (4741 kB/s)                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
2 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@task-pv-pod:/# apt install curl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
curl is already the newest version (7.64.0-4+deb10u2).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.
root@task-pv-pod:/# curl http://localhost/
Hello from Kubernetes storage
root@task-pv-pod:/# exit

```

**Comment by adamjablonowski** [comment]
Thanks. Previously I have created /mnt/data on the host. I can move my files to persistent volume claim using `kubectl cp <PATH> task-pv-pod:/usr/share/nginx/html`.

**Comment by afbjorklund** [comment]
So that sounds like you put the files on your laptop (where you run kubectl) instead of on the minikube node (where kubelet runs).

The use of the term "host" can be misleading, since it is relative (similar to localhost). But I thought the documentation was OK:

> Open a shell to the single Node in your cluster. How you open a shell depends on how you set up your cluster.
> For example, if you are using Minikube, you can open a shell to your Node by entering `minikube ssh`.
