### ISSUE TITLE
change registery_mirror to registery-mirror

### ISSUE THREAD

**Issue by Nasrin-Shiraly** [kubernetes/minikube#11649]
in this line:

 `registryMirror = viper.GetStringSlice("registry_mirror")`

the flag string should be `registry-mirror`

https://github.com/kubernetes/minikube/blob/d76259e86f4845bd01fe3e81e65214b9e231ecdb/cmd/minikube/cmd/start.go#L165

It is initially defined as 
`startCmd.Flags().StringSliceVar(&registryMirror, "registry-mirror", nil, "Registry mirrors to pass to the Docker daemon")`

https://github.com/kubernetes/minikube/blob/51aa548e237456249cf7cabc1dffe2885ffb44f6/cmd/minikube/cmd/start_flags.go#L228

**Comment by Nasrin-Shiraly** [comment]
If approved, I can do it. 
/assign

**Comment by spowelljr** [comment]
@Nasrin-Shiraly You can definitely work on this issue, thank you for contributing to minikube!

**Comment by Nasrin-Shiraly** [comment]
According to [a comment](https://github.com/kubernetes/minikube/pull/11701#issuecomment-865167768) , this issue can be set to resolved once the other PR is merged.  /unassign

**Comment by ilya-zuyev** [comment]
Seems like fixed in https://github.com/kubernetes/minikube/pull/11678
