### ISSUE TITLE
timeToK8s: Give minikube the same amount of memory as kind and k3d

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/minikube#11650]
By default, kind and k3d do not have a set limit on the amount of memory they use. minikube by default decides how much memory to allocate, this difference in available memory puts minikube at a disadvantage. Give minikube unlimited or a large amount of memory during the time-to-k8s benchmark to make the results more comparable.

**Comment by spowelljr** [comment]
In-progress
