### ISSUE TITLE
Upgrade software versions on the minikube ISO

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11652]
Tracker for some separate issues, regarding ISO:

- [x] Upgrade Buildroot, from 2020.02 to 2021.02
    - ~2020.02.12~ (EOL)
    - 2021.02.4 (LTS)
- [ ] Upgrade Docker and other container runtimes
    - runc v1.0.1 ✓
    - containerd v1.4.9 ✓
    - docker 20.10.8 ✓
    - buildkit 0.9.0 ✓
    - ~~(crun 0.20.1) _(alternative to runc)_~~
    - ~~cri-o 1.20.3~~
    - ~~podman 3.1.2~~
    - ~~(buildah 1.20.1)~~ _(included in podman)_

PRs: ~~**#11688**~~ #12268 ~#11593~ #12122 ~#11594~ #12032 #11595 #11679  #11727

EDIT: PR #11688 was reverted in #11799 due to #11810

**Comment by afbjorklund** [comment]
We still don't fully now what the long term plan will be: #9992

**Comment by afbjorklund** [comment]
This issue is currently blocking the Linux 5 version and the ARM 64 version.

Those would be add-ons/alternative versions building, from this updated ISO.

**Comment by afbjorklund** [comment]
The buildroot OS upgrade is being blocked by "cilium" issues with systemd: #11810

**Comment by afbjorklund** [comment]
2021.02.4:
http://lists.busybox.net/pipermail/buildroot/2021-August/620747.html

/etc/sysctl.d/90-cilium-rp_filter.conf
```
net.ipv4.conf.lxc*.rp_filter = 0
net.ipv4.conf.cilium_*.rp_filter = 0
```

**Comment by djgraff209** [comment]
Should this issue now be punted to milestone 1.24.0 since 1.23.0 went out with out it?

**Comment by afbjorklund** [comment]
Possibly wrong to add a "tracker" bug, most things except for podman/cri-o actually did make it...

**Comment by djgraff209** [comment]
Understood and thank you for your efforts.

Is there any clarity around an updated podman? I'm super interested in using this as a docker desktop replacement on windows and Mac.

All of the clients that are available are 3.3.0 or later which are not compatible with the 2.2.1 API version bundled.

Thank you again

**Comment by afbjorklund** [comment]
Podman is not fully supported for running containers with, it's more like a support tool to CRI-O (for loading and building)

So the main use is for `minikube image`, but I think that it still works OK as long as you install a `podman2` separately...

There is no support for rootless containers though, so you have to run `sudo podman` (or use `minikube podman-env`)

If looking for a tool similar to Docker Machine/Podman Machine, I would currently recommend using Vagrant (until 4.0)

**Comment by afbjorklund** [comment]
There are a lot of "Podman Desktop" discussions elsewhere though, including a Podman Community meeting happening tomorrow.

But we might have to add a FAQ about Docker Desktop (and also Docker Engine), since it is the preferred minikube driver now...

**Comment by djgraff209** [comment]
I think my main focus was being able to do minikube + podman-env for the near term - heck even docker-env with the cli might suffice.

The one thing that was most appealing was the ability to use either hyperkit (macos) or hyper-v (windows 10 ent/pro). The virtualization options looked much cleaner in those respects.

Thanks again for providing alternatives to just docker desktop as well as a solid (simple) kubernetes environment.

**Comment by afbjorklund** [comment]
> I think my main focus was being able to do minikube + podman-env for the near term - heck even docker-env with the cli might suffice.

Those features will remain for the foreseeable future, a bit of a pity with the lack of compatibilty between podman2 and podman3 (and soon it will break again with podman4!) and about the slow adoption of `ssh:` support in the docker client and libraries.

But right now it is mostly the containerd runtime that lacks a proper environment, due to shortcomings in the tools (but workarounds documented). It is not impossible to make a "minikube containerd-env", but it would also be nice **not** to have to...

I'm not sure how long Docker will continue to support machine and hyperkit\*, so we might have to fork and include them.

\* hyperkit is based on an open source project called xhyve, which in turn is based on Apple's system frameworks. So no worries.

**Comment by afbjorklund** [comment]
Closing this issue, due to that the OS and docker/containerd did make it (and nobody cares about podman/crio)
