### ISSUE TITLE
how to add DNS search domains

### ISSUE THREAD

**Issue by blbradley** [kubernetes/minikube#1165]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Minikube version** (use `minikube version`): 0.16.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO`): 1.0.6
- **Install tools**:
- **Others**: busybox image

**What happened**:
I could not find a way to add my router's domain to the searched domains.

**What you expected to happen**:
Access machines outside of the cluster without router's domain

**How to reproduce it** (as minimally and precisely as possible):

I'm behind a router that serves DNS and DHCP. So, YMMV.
```
$ minikube start
$ cat busybox.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
$ kubectl create -f busybox.yaml
$ kubectl exec -it busybox -- /bin/sh
# nslookup zooey0-dev
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

nslookup: can't resolve 'zooey0-dev'
# nslookup zooey0-dev.home
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      zooey0-dev.home
Address 1: 192.168.1.238 zooey0-dev.home
```

**Anything else do we need to know**:
I tried to edit the minikubeVM's resolv.conf and restart the cluster, but my changes did not persist. Pods are supposed to inherit the node's resolv.conf according to [this](https://kubernetes.io/docs/admin/dns/) (bottom of page).

**Comment by r2d4** [comment]
You might be able to edit this file https://www.freedesktop.org/software/systemd/man/resolved.conf.html.  

Systemd may be overwriting your changes in resolv.conf.  We'll look into this

**Comment by blbradley** [comment]
The good news is that pods inherit the node's resolv.conf as described.

Docker daemon has a parameter `--dns-search`. I tried `minikube start --docker-env DOCKER_OPTS="--dns-search=home"` to no avail. I'm not sure where the break is there, too many levels of indirection.

**Comment by r2d4** [comment]
You need to delete and start minikube for docker-env options to take effect

**Comment by blbradley** [comment]
I did. DOCKER_OPTS does nothing on machines with systemd.

**Comment by wzhliang** [comment]
+1

**Comment by snps-brucejia** [comment]
To be honest I really think this is a valid feature request. In my case I need to access some external nodes (with their short names, like my-db-1) from minikube cluster. I'd like to have some feature like docker option "--dns-search" which can be applied to each node/pod of the minikube cluster.
