### ISSUE TITLE
vmware driver install instructions for Mac

### ISSUE THREAD

**Issue by psedwards99** [kubernetes/minikube#11657]
These instructions for installation on a Mac are wrong.

r=https://api.github.com/repos/machine-drivers/docker-machine-driver-vmware
curl -LO $(curl -s $r/releases/latest | grep -o 'http.*darwin_amd64' | head -n1) \
 && install docker-machine-driver-vmware_darwin_amd64 \
  /usr/local/bin/docker-machine-driver-vmware

You need an uppercase 'D' (for darwin) in 'http.*darwin_amd64' and also 'docker-machine-driver_darwin_amd64' or change the name of the distribution file in Github

**Comment by spowelljr** [comment]
I have verified that the instructions on the website do not work, thanks for reporting the issue!

**Comment by mahalrs** [comment]
@spowelljr I will work on this.

/assign
