### ISSUE TITLE
Failing to disable docker service, when running containerd on ISO

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#11661]
The systemd unit docker.service is created by minikube, but not when running containerd as the runtime.

So ironically we fail to stop docker.service, and therefore also fail to disable docker.socket (since bec9f23e29680caec7a79892a05e5406e6088ec9)

We should probably continue with the disable and the mask, even if the force-stop failed (for some reason) ?

`"Failed to stop" err="sudo systemctl stop -f docker.service: Process exited with status 5\nstdout:\n\nstderr:\nFailed to stop docker.service: Unit docker.service not loaded.\n" service="docker.service"`

**Comment by afbjorklund** [comment]
This is only some ugly output, the docker.socket is still stopped - even if not disabled, for next time.

```console
● docker.socket - Docker Socket for the API
     Loaded: loaded (/usr/lib/systemd/system/docker.socket; enabled; vendor preset: enabled)
     Active: inactive (dead)
   Triggers: ● docker.service
     Listen: /run/docker.sock (Stream)

```

But it **cannot** start accidentally, since the docker.service unit has been removed.

```
Unit docker.service could not be found.
```

**Comment by afbjorklund** [comment]
The unit has been gone for a _long_ time: 56e250e9796bb1600ae867a47eb60bdcc44e32ad

It was re-introduced in KIC, using standard Docker.

**Comment by spowelljr** [comment]
@afbjorklund I believe this is a duplicate of #11622

**Comment by afbjorklund** [comment]
Right, we can continue there instead. Found why, at least.
