### ISSUE TITLE
Daemon cached image ignored if missing file cached image

### ISSUE THREAD

**Issue by andriyDev** [kubernetes/minikube#11689]
Currently, if the kicbase image is present in the daemon, but not stored in the cache, the image is redownloaded rather than using the existing kicbase image.

**Comment by afbjorklund** [comment]
How did the image end up in the daemon, without passing the cache ? User pulled it manually ?

**Comment by andriyDev** [comment]
The user could pull it manually, or in my case, I ran `minikube delete --purge --all`, which still keeps the daemon image around.
