### ISSUE TITLE
/tmp/minikube_stop_c0edbb93fcf65d589e1033c924a9706717a28738_0.log

### ISSUE THREAD

**Issue by zettaRepo** [kubernetes/minikube#11695]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by ilya-zuyev** [comment]
Going to close this issue. Please feel free to reopen it attaching logs and system info as described in issue template
