### ISSUE TITLE
Minikube service on windows

### ISSUE THREAD

**Issue by Iquis** [kubernetes/minikube#11699]
I want to run a nginx image with minikube on windows 10

Here is my deployment & service configuration :

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-container
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000
        `
I used kubectl apply command to create both pod and service

Then I start minikube service with
`minikube service myapp-service

| NAMESPACE |     NAME      | TARGET PORT |            URL            |
|-----------|---------------|-------------|---------------------------|
| default   | myapp-service |        8080 | http://192.168.49.2:30000 |

 Starting tunnel for service myapp-service.

| NAMESPACE |     NAME      | TARGET PORT |          URL           |
|-----------|---------------|-------------|------------------------|
| default   | myapp-service |             | http://127.0.0.1:53747 |

 Opening service default/myapp-service in default browser...`
It opens my browser at 127.0.01:53747 but I can't connect through the tunnel.

I'm running kubectl v1.19.7 and minikube v1.21.0

I heard there is a bug on minikube for Windows. Is it still the case or am I doing something wrong?

(of course the indentation in the yaml file is right but I can't get it right on this post)

**Comment by sharifelgamal** [comment]
I believe the solution here is `minikube tunnel`, let me know if running that in another terminal then trying again helps.

**Comment by klaases** [comment]
Hi @Iquis – were you able to try using `minikube tunnel` as suggested above?

Also, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by Iquis** [comment]
Yeah my problem was solved using minikube tunnel
