### ISSUE TITLE
minikube - missing the Publisher Name on Windows

### ISSUE THREAD

**Issue by igorradovanov** [kubernetes/minikube#11710]
The minikube installed via the Windows installer from the official source page found at https://minikube.sigs.k8s.io/docs/start/ is missing the **Publisher Name** which is causing Windows Defender to display a message that the app is not trusted and that it may put the PC at risk. This may be a blocker for new users who may want to try out minikube.

Screenshot: 
![image](https://user-images.githubusercontent.com/20539903/122728254-3a3e4500-d278-11eb-9179-7a0b14c41dd9.png)

minikube: **v1.21.0**
OS: **Windows 10 Version	10.0.19042 Build 19042**

**Comment by ilya-zuyev** [comment]
@igorradovanov thanks for reporting this

**Comment by spowelljr** [comment]
I believe this might be a duplicate of https://github.com/kubernetes/minikube/issues/4841

**Comment by spowelljr** [comment]
I'm going to close this issue in favor of #4841, please follow along with the issue there, thanks!
