### ISSUE TITLE
libvirt group check causes false positives

### ISSUE THREAD

**Issue by leoluk** [kubernetes/minikube#11730]
PR https://github.com/kubernetes/minikube/pull/10712 checks whether the user is in the libvirt group.

However, there's many ways to give users permissions to use system libvirt that do not involve this group. It may be named differently, may be pointing to a remote libvirt instance, or a polkit rule like this one may be used:

```
polkit.addRule(function(action, subject) {
    if (action.id == "org.libvirt.unix.manage" &&
        subject.isInGroup("wheel")) {
            return polkit.Result.YES;
    }
});
```

Minikube should first check whether it can actually access libvirt, and only then check for the missing group. Using `--force` is not an appropriate workaround since that would skip other safety checks, too.

Related:

- https://github.com/kubernetes/minikube/issues/11630
- https://github.com/kubernetes/minikube/issues/11551

**Comment by medyagh** [comment]
@leoluk seems like a good idea ! I would be happy to review a PR that implemetns your idea ! are you interested?

**Comment by leoluk** [comment]
Sure thing! Submitted PR
