### ISSUE TITLE
list version of all included packages 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11747]
```
docker version --format='{{.Client.Version}}'
sudo crictl version 
runc --version
crio version
buildctl --version
sudo ctr version
sudo podman version
```

**Comment by afbjorklund** [comment]
I don't think those are actually packages, more like `--detailed` or `--system` or something ?

If you want package versions, you would use something like `apt list` to show the installed.

```
docker-ce-cli/now 5:20.10.7~3-0~ubuntu-focal amd64 [installed,local]
cri-tools/now 1.21.0~1 amd64 [installed,local]
cri-o/now 1.20.3~0 amd64 [installed,local]
podman/now 100:3.1.2-1 amd64 [installed,local]
```
Some don't have any package, such as runc (containerd.io) or ctr (containerd.io) or buildkit (tgz)

```
containerd.io: /usr/bin/runc
containerd.io: /usr/bin/ctr
```

----

Note that Buildroot doesn't use packages at all, other than the ones in the (source) Makefile.

So calling the programs is probably best, but calling it "packages" can be misleading here ?

**Comment by afbjorklund** [comment]
Normally Kubernetes just reports the basic versions, and let the OS and CRI handle details.

```
  Kernel Version:             4.19.194
  OS Image:                   Buildroot 2021.02.3
  Operating System:           linux
  Architecture:               amd64
  Container Runtime Version:  docker://20.10.7
```

**Comment by afbjorklund** [comment]
Follow up to fix the wrong versions reported (of for instance ctr and crictl), in PR #12085
