### ISSUE TITLE
iSCSI volumes can not be used because iscsiadm (and eventually kmods) are missing

### ISSUE THREAD

**Issue by fabiand** [kubernetes/minikube#1174]
**Minikube version** (use `minikube version`):
$ minikube version
minikube version: v0.16.0

**Environment**:
- **OS** (e.g. from /etc/os-release): linux/fedora
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): libvirt
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:

**What happened**:
I tried to use an iSCSI PVC on a pod

**What you expected to happen**:
The kubelet is able to attach the PVC to the pod

**How to reproduce it** (as minimally and precisely as possible):
Always

**Anything else do we need to know**:
The error is a little cryptic:
```
2017-02-24 16:51:08 +0100 CET   2017-02-24 16:43:00 +0100 CET   12        mypod     Pod                 Warning   FailedMount   {kubelet minikube}   MountVolume.SetUp failed for volume "kubernetes.io/iscsi/ebd01c3a-faa7-11e6-8b79-5254009a9694-myvol" (spec.Name: "myvol") pod "ebd01c3a-faa7-11e6-8b79-5254009a9694" (UID: "ebd01c3a-faa7-11e6-8b79-5254009a9694") with: executable file not found in $PATH
```
but I guess that this is because `iscsiadm` is missing in the kubelet env and thus the iscsi lun can not get attached.

**Comment by aaron-prindle** [comment]
Right now the PR that I have does not properly build the open-iscsi binaries (iscsid and iscsiadm) and they are then not available in the ISO.  I used the buildfile here: http://lists.busybox.net/pipermail/buildroot/2007-February/013810.html as an example but it seems this source repository: http://www.open-iscsi.org/bits  Is no longer correct.  I am looking at using: https://github.com/open-iscsi/open-iscsi/releases but am having issues building it.  Any help/thoughts would be appreciated, thanks.

**Comment by fabiand** [comment]
@aaron-prindle do you have a hint of how to test the builds? The I could take a look

**Comment by fredleger** [comment]
Please re-open because this is still the case i think:

```shell
kubectl apply -f https://raw.githubusercontent.com/rancher/longhorn/v0.2/deploy/longhorn.yaml
kubectl apply -f https://raw.githubusercontent.com/rancher/longhorn/master/deploy/example-storageclass.yaml
```
fails because iscsiadm is missing

**Comment by renich** [comment]
I, also, need this to try out EdgeFS on Minikube; which is part of Rook.
