### ISSUE TITLE
Flake Chart comment to incude Number of tests

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11750]
currently it looks like this
<img width="972" alt="Screen Shot 2021-06-22 at 10 42 30 PM" src="https://user-images.githubusercontent.com/4564227/123027030-25160300-d3ab-11eb-90ce-6b1f1400ac66.png">

_Originally posted by @minikube-bot in https://github.com/kubernetes/minikube/issues/11743#issuecomment-866453880_

but I want to see the Summary that I see in the commit status
```
Docker_Linux -  completed with 5 / 268 failures in 55.08 minute(s).

...then now put the table

```

that way I don't have to scroll down to see how long it took and ideally there should be a link to the gopogh on the First Title

**Comment by tharun208** [comment]
@medyagh I like to work on this

**Comment by andriyDev** [comment]
Go for it!

/assign tharun208

**Comment by andriyDev** [comment]
@tharun208 This doc may help https://github.com/kubernetes/minikube/pull/11757. Specifically, look for "report_flakes.sh".

**Comment by tharun208** [comment]
sorry, for the delay. will come with a pr soon

**Comment by andriyDev** [comment]
@tharun208 this has become obsolete, sorry! The newest report_flakes.sh now reports on multiple environments at once, so having total test count doesn't really make sense.
