### ISSUE TITLE
is KVM crio test results over-writting KVM Linux test results?

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11751]
while looking at the Pending KVM Linux commit status
```
@minikube-bot
KVM_Linux Pending — Jenkins

```
for this PR https://github.com/kubernetes/minikube/pull/11731
this was the pending URL
https://storage.googleapis.com/minikube-builds/logs/11731/5727823/KVM_Linux.pending

changing this to txt give u this
https://storage.googleapis.com/minikube-builds/logs/11731/5727823/KVM_Linux.txt
and in the logs u can see in the logs everywhere is reffering to crio

```
+ EXTRA_START_ARGS=' --container-runtime=crio'
++ out/e2e-linux-amd64 '-minikube-start-args=--driver=kvm2  --container-runtime=crio' -test.timeout=120m -test.v -binary=out/minikube-linux-amd64
++ tee /home/jenkins/minikube-integration/linux-amd64-kvm2-crio-11731-776580-57278239649e9b4bc4e78ee39aa0374f6a387dc4/testout.txt
Found 8 cores, limiting parallelism with --test.parallel=4
===
```

**Comment by sharifelgamal** [comment]
this was a bug in our Jenkins configuration, it should be fixed.
