### ISSUE TITLE
documentation: --embed-certs

### ISSUE THREAD

**Issue by karezza** [kubernetes/minikube#11771]
Regarding page:
https://minikube.sigs.k8s.io/docs/handbook/untrusted_certs/

Request additional information:
- if the ca certs are installed on the host machine is this step necessary?
- if no, what if the ca certs are installed to the host machine after 'minikube start' is executed, will it see them?
- after running command will deployments need to be restarted in order to work?
- maybe a little information (education?) on how containers will then be able to use those certs, to help with troubleshooting

I tried:
minikube kubectl -- rollout restart deployment itsawx

This didn't get LDAP working on a recent AWX Operator style install of AWX, but I have this sneaking suspicion that if I were to now reinstall AWX from scratch it would work because I have now installed the ca certs using --embed-certs.

**Comment by medyagh** [comment]
> Regarding page:
> https://minikube.sigs.k8s.io/docs/handbook/untrusted_certs/
> 
> Request additional information:
> 
> * if the ca certs are installed on the host machine is this step necessary?
Yes, it needs to be installed on the guest as well.

> * if no, what if the ca certs are installed to the host machine after 'minikube start' is executed, will it see them?
No, Installing on host doesnt concern minikube, you would need to copy the PEM into minikube cert folder as instructed in the doc
```
mkdir -p $HOME/.minikube/certs
cp my_company.pem $HOME/.minikube/certs/my_company.pem
```
> * after running command will deployments need to be restarted in order to work?
after that, I recommend restarting minikube
minikube stop
minikube start --embed-certs


and that should do !
> * maybe a little information (education?) on how containers will then be able to use those certs, to help with troubleshooting
> 
> I tried:
> minikube kubectl -- rollout restart deployment itsawx
> 
> This didn't get LDAP working on a recent AWX Operator style install of AWX, but I have this sneaking suspicion that if I were to now reinstall AWX from scratch it would work because I have now installed the ca certs using --embed-certs.

**Comment by medyagh** [comment]
@ karezza does that answer your question ?

**Comment by karezza** [comment]
I created this ticket to have the documentation updated.  I have the answers now but I suspect others will have the same questions.  I leave it up to you whether you update the documentation or not.

**Comment by giuliohome** [comment]
> after running command will deployments need to be restarted in order to work?

This question needs to be clarified as it can be misleading.

The certificate in question is meant to support the Kubernetes container runtime on the worker node, specifically Docker on the Minikube OS. The issue it addresses is the ErrImagePull error for any deployment, as it validates the image registry from the Minikube OS perspective.

However, this does not address similar certificate problems that might occur inside the containers of deployments once the container images have been created and the pods are running. In such cases, a fix in the corresponding Dockerfile might still be needed. This other, different issue is more related to Kubernetes itself rather than Minikube.

**Comment by giuliohome** [comment]
**Edit**, after looking deeper into the code of  --embed-certs I see that it is related to the **kubeconfig**, that is **not relevant** in my case, where minukube is local and the proxy ErrImagePull problem is only between the minikube os and the docker registry....
