### ISSUE TITLE
Add journalctl to the iso

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#118]
I saw this in my logs today:
W0526 16:09:41.697993    2816 manager.go:264] Could not configure a source for OOM detection, disabling OOM events: exec: "journalctl": executable file not found in $PATH

**Comment by luxas** [comment]
Please see: kubernetes/kubernetes#26093

**Comment by dlorenc** [comment]
Nice! Once this list is finalized we should make a test for the ISO that verifies everything is present.

**Comment by vishh** [comment]
cAdvisor does not require journalctl. It can look at kernel logs using `/var/log.messages` too. I suspect that there is some bug. Filed an issue against cAdvisor

**Comment by luxas** [comment]
crossref: https://github.com/google/cadvisor/issues/1313

**Comment by vishh** [comment]
`journalctl` is not required, as i mentioned in that issue.

**Comment by luxas** [comment]
Okay, good to know

**Comment by dlorenc** [comment]
Closing this out, since it's not required.
