### ISSUE TITLE
windows vbox: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027a1690b

### ISSUE THREAD

**Issue by sshafiuddin** [kubernetes/minikube#11801]
Windows - VirtualBox - minikube start issue - getting not find matching IP for MAC address (PFA for full log  info )

$minikube start driver=virtualbox
[lastStart.txt](https://github.com/kubernetes/minikube/files/6731298/lastStart.txt)

* minikube v1.20.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Maximum number of retries (5) exceeded
* Updating the running virtualbox "minikube" VM ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027a1690b

X Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027a1690b

**Comment by medyagh** [comment]
@sshafiuddin thanks for attaching the logs

do u happen to be using a VPN ? 
```
I0629 11:35:15.072316   15316 main.go:128] libmachine: Using SSH client type: native
I0629 11:35:15.072316   15316 main.go:128] libmachine: &{{{<nil> 0 [] [] []} docker [0xd42d60] 0xd42d20 <nil>  [] 0s} 127.0.0.1 64292 <nil> <nil>}
I0629 11:35:15.072316   15316 main.go:128] libmachine: About to run SSH command:
ip addr show
I0629 11:35:17.075506   15316 main.go:128] libmachine: Error dialing TCP: dial tcp 127.0.0.1:64292: connectex: No connection could be made because the target machine actively refused it.

```

**Comment by spowelljr** [comment]
Hi @sshafiuddin, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
