### ISSUE TITLE
localkube error "hairpin.go:61] Unable to find pair interface, setting up all interfaces: exec: "ethtool": executable file not found in $PATH"

### ISSUE THREAD

**Issue by ankon** [kubernetes/minikube#1182]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG
**Minikube version** (use `minikube version`): 0.16.0
**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 10.12.1
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep ISO` or `minikube ssh cat /etc/VERSION`): 1.0.6
- **Install tools**:
- **Others**:

**What happened**:
Watching logs inside `minikube ssh` using `journalctl -fu localkube`, and observed error message
~~~~
Feb 25 09:04:05 minikube localkube[3465]: I0225 09:04:05.145584    3465 hairpin.go:61] Unable to find pair interface, setting up all interfaces: exec: "ethtool": executable file not found in $PATH
~~~~

**What you expected to happen**:
No such error message.

**How to reproduce it** (as minimally and precisely as possible):
Unclear, but from reading through the issues in the main kubernetes project this seems to be "expected" when there is no ethtool available.

**Anything else do we need to know**:
https://github.com/kubernetes/kubernetes/issues/18251 "kube-proxy in iptables mode uses ethtool." - fixed by including ethtool in the image.
https://github.com/kubernetes/kubernetes/pull/37548 attempted to remove the dependency, was closed due to fundamental flaws in the solution.

**Comment by dims** [comment]
Right, there's nothing we can do in minikube to avoid this problem. There are some more details in: https://github.com/kubernetes/kubernetes/issues/26093
