### ISSUE TITLE
Include information about arm64 releases in release.json and release-beta.json

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#11825]
We maintain release list files:  https://storage.googleapis.com/minikube/releases.json  for GA and https://storage.googleapis.com/minikube/releases-beta.json for betas.

ATM, those are lists of items like: 
```
{
"name": "v1.20.0",
"checksums": {
"darwin": "5185b7a4156671444dc7ad33b013b90f8a0ffb5186fc5c1a084e7c1cb6cd0788",
"linux": "87e5260afcba82dfcb7681b542c3e15665113b6d388faebe77bb0a784737dd13",
"windows": "ab3239792c89225b9f1b6f70cebe2fd6f6afd95d3755a4b708937a8ed876042f"
}

```
all hash sums are assumed to be for amd64 architecture.
Now arm64 is the officially supported architecture for darwin and linux, we need to extend the format to provide checksums for other platforms

**Comment by medyagh** [comment]
I agree ! thanks for noticing this, lets add that

**Comment by medyagh** [comment]
as discussed in triage party, we would like to have this, with backward compatibility ina way that an old minikube accessing this json file to see if there is a new version
