### ISSUE TITLE
Error restarting cluster: waiting for apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by youzeliang** [kubernetes/minikube#11830]
I type it "minikube start --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'" in terminal .
But it always time out 
I try to use different net

**Comment by spowelljr** [comment]
Hi @youzeliang, thanks for reporting your issue!

This is a duplicate of #10544, in order to keep all discussion of this issue centralized I'm going to close this issue.

Please follow along with #10544 and contribute any findings there, thanks for your understanding!

**Comment by youzeliang** [comment]
ok，thank you
