### ISSUE TITLE
X Exiting due to GUEST_PROVISION: Failed to start host: provision: Error getting config for native Go SSH: open C:\Users\LENOVO\.minikube\machines\minikube\id_rsa: Access is denied.

### ISSUE THREAD

**Issue by amanravi12** [kubernetes/minikube#11855]
C:\Users\LENOVO>minikube start
* minikube v1.21.0 on Microsoft Windows 10 Home Single Language 10.0.19043 Build 19043
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
* Updating the running virtualbox "minikube" VM ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Error getting config for native Go SSH: open C:\Users\LENOVO\.minikube\machines\minikube\id_rsa: Access is denied.

X Exiting due to GUEST_PROVISION: Failed to start host: provision: Error getting config for native Go SSH: open C:\Users\LENOVO\.minikube\machines\minikube\id_rsa: Access is denied.
[lastStart.txt](https://github.com/kubernetes/minikube/files/6750264/lastStart.txt)

**Comment by spowelljr** [comment]
Hi @amanravi12, thanks for reporting your issue with minikube!

You don't seem to have permission to access to your `id_rsa` file.

Are you using Command Prompt or Powershell? And did you `Run as administrator` when you opened it?

One other thing I noticed is that the path of the file it's looking for is strange:
`C:\Users\LENOVO.minikube\machines\minikube\id_rsa`
Most noticeably `LENOVO.minikube`, there should be a `\` between the two.
Right now it looks like it's trying to access a file in a different user space, which may be causing the permission error.

**Comment by amanravi12** [comment]
using CMD prompt and run as adminstration thank you for your suggestion
.... i appreciate of your helping nature

**Comment by andriyDev** [comment]
@amanravi12 Is this issue resolved? Your message is a little unclear, sorry! Please close the issue if it's resolved

**Comment by amanravi12** [comment]
Yes, it is working.

**Comment by pappusanodiya** [comment]
# getting this errors please help, also the access denied came up
![image](https://github.com/user-attachments/assets/5c2f59ae-509b-4b18-b144-3c6863a252dd)
