### ISSUE TITLE
site: Add command-line download instructions for windows binary

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11861]
how about as a follow up PR fix the windows "Download" so we have a command to download binaries for windows  too ? instead of asking peoople to go to the release page
https://github.com/medyagh/minikube/blob/b5cf45a1d47f1660a7e91075269000d4d0c29aa6/site/content/en/docs/start/_index.md#L211

something like this might work ? (that we use to download gopogh)
```
 (New-Object Net.WebClient).DownloadFile("https://github.com/medyagh/gopogh/releases/download/v0.8.0/gopogh.exe", "C:\ProgramData\chocolatey\bin\gopogh.exe")
```

_Originally posted by @medyagh in https://github.com/kubernetes/minikube/pull/11859#issuecomment-872505225_

**Comment by mahalrs** [comment]
@medyagh I will look into this and will get back to you soon.

/assign @mahalrs

**Comment by medyagh** [comment]
@mahalrs its urs... I am not sure whats best thing to do on windows

curl.exe -Lo minikube.exe URL
Move-Item .\minikube.exe c:\something-in-path\minibe.exe
