### ISSUE TITLE
typo in pause command

### ISSUE THREAD

**Issue by rsteube** [kubernetes/minikube#11873]
**Steps to reproduce the issue:** 

1. . `minikube pause ----namespaces example`

**Full output of failed command:**
```sh
bad flag syntax: ----namespaces
```

Flag should probably be `namespaces` instead of `--namespaces`: https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/pause.go#L107

**Comment by mahalrs** [comment]
Thanks for reporting this. I will fix it as soon as I can.

/kind bug
/assign @mahalrs

**Comment by rsteube** [comment]
@mahalrs seems this applies for the `unpause` command as well

**Comment by mahalrs** [comment]
Hi @rsteube, thanks for reporting these issues. We will fix them as soon as possible.
