### ISSUE TITLE
minikube config set driver hyperkit in mac m1

### ISSUE THREAD

**Issue by NitichaiSawangsai** [kubernetes/minikube#11886]
**Steps to reproduce the issue:** 

1.  minikube config set driver hyperkit

**Full output of `minikube logs` command:**
<pre>

Log file created at: 2021/07/02 22:50:32
Running on machine: Macintosh-2
Binary: Built with gc go1.16.4 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0702 22:50:32.196527   30528 out.go:291] Setting OutFile to fd 1 ...
I0702 22:50:32.196692   30528 out.go:343] isatty.IsTerminal(1) = true
I0702 22:50:32.196694   30528 out.go:304] Setting ErrFile to fd 2...
I0702 22:50:32.196696   30528 out.go:343] isatty.IsTerminal(2) = true
I0702 22:50:32.196933   30528 root.go:316] Updating PATH: /Users/nitichaisawangsai/.minikube/bin
W0702 22:50:32.197044   30528 root.go:291] Error reading config file at /Users/nitichaisawangsai/.minikube/config/config.json: open /Users/nitichaisawangsai/.minikube/config/config.json: no such file or directory
I0702 22:50:32.216462   30528 out.go:170] 
W0702 22:50:32.216568   30528 out.go:235] ❌  Exiting due to MK_CONFIG_SET: run validations for "driver" with value of "hyperkit": [driver "hyperkit" is not supported]
W0702 22:50:32.216573   30528 out.go:235] 
W0702 22:50:32.218135   30528 out.go:235] [31m╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
W0702 22:50:32.218140   30528 out.go:235] [31m│[0m                                                                                                                         [31m│[0m
W0702 22:50:32.218144   30528 out.go:235] [31m│[0m    😿  If the above advice does not help, please let us know:                                                           [31m│[0m
W0702 22:50:32.218145   30528 out.go:235] [31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                         [31m│[0m
W0702 22:50:32.218147   30528 out.go:235] [31m│[0m                                                                                                                         [31m│[0m
W0702 22:50:32.218149   30528 out.go:235] [31m│[0m    Please attach the following file to the GitHub issue:                                                                [31m│[0m
W0702 22:50:32.218193   30528 out.go:235] [31m│[0m    - /var/folders/mt/cx4v80x10kd8k5kw5xw4sgzc0000gn/T/minikube_config_5dd274b389d1f63327a30c1206ffe8e47e4f6330_0.log    [31m│[0m
W0702 22:50:32.218197   30528 out.go:235] [31m│[0m                                                                                                                         [31m│[0m
W0702 22:50:32.218199   30528 out.go:235] [31m╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
W0702 22:50:32.218202   30528 out.go:235] 

</pre>

**Comment by spowelljr** [comment]
Hi @NitichaiSawangsai thanks for reporting your issue!

This is related to the other issue you created (#11885). Since hyperkit is currently not supported on M1 Macs, it is failing the validation we have in place.

Once we support hyperkit on M1 Macs this will be resolved.

Thanks for using minikube!
