### ISSUE TITLE
Proposal: "restart" command

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/minikube#1189]
Often times when my laptop goes to sleep, I encounter issues with my minikube setup, such as sometimes it just hangs, sometimes a time drift occurs between VM and the host and I end up just doing:

    minikube stop; minikube start

It would be great if there was a `minikube restart`.

Similarly, `docker-machine` also has a "restart" subcommand. It's useful when things just go wrong and you quickly want to fix it. Thoughts? I can volunteer to implement this.

**Comment by r2d4** [comment]
Yeah, I think it sounds reasonable.  Today `minikube start` actually restarts the localkube and docker instances, so theres a little bit of overlap in functionality, but it doesn't cover the full case of a stop;start.  

SGTM.  I'll assign the issue to you if thats alright

**Comment by ahmetb** [comment]
I'll abandon this, the implementation was not quite trivial and value add is fairly low.

**Comment by asarkar** [comment]
@ahmetb I came here looking for a restart command; instead of closing the ticket just because you didn't get around to implementing it, I suggest leaving it open so that someone else may pick it up if they want to.

**Comment by ahmetb** [comment]
OK, it would be good to see if proposal is accepted before someone implements.

**Comment by tstromberg** [comment]
How would this behave differently than the existing `minikube start` command? 

The only thing that I can think of is a preservation of command-line flags previously used to start the cluster.

**Comment by ahmetb** [comment]
It doesn't seem like there's a common need for this.
/close
