### ISSUE TITLE
睡一觉起来发现kubectl不能用了，想重新创建集群，minikube stop也停不了了

### ISSUE THREAD

**Issue by WinnerSong** [kubernetes/minikube#11896]
Log file created at: 2021/07/04 10:22:06
Running on machine: songzwdeMBP
Binary: Built with gc go1.16.4 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0704 10:22:06.520048   20371 out.go:291] Setting OutFile to fd 1 ...
I0704 10:22:06.520287   20371 out.go:343] isatty.IsTerminal(1) = true
I0704 10:22:06.520290   20371 out.go:304] Setting ErrFile to fd 2...
I0704 10:22:06.520295   20371 out.go:343] isatty.IsTerminal(2) = true
I0704 10:22:06.520453   20371 root.go:316] Updating PATH: /Users/songzw/.minikube/bin
W0704 10:22:06.521407   20371 root.go:291] Error reading config file at /Users/songzw/.minikube/config/config.json: open /Users/songzw/.minikube/config/config.json: no such file or directory
I0704 10:22:06.523450   20371 out.go:298] Setting JSON to false
I0704 10:22:06.525786   20371 mustload.go:65] Loading cluster: minikube
I0704 10:22:06.528524   20371 profile.go:148] Saving config to /Users/songzw/.minikube/profiles/minikube/config.json ...
I0704 10:22:06.529743   20371 mustload.go:65] Loading cluster: minikube
I0704 10:22:06.530558   20371 stop.go:39] StopHost: minikube
I0704 10:22:06.541684   20371 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:22:06.543058   20371 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
I0704 10:22:06.985764   20371 out.go:170] 🛑  正在通过 SSH 关闭“minikube”…
I0704 10:22:06.986003   20371 cli_runner.go:115] Run: docker exec --privileged -t minikube /bin/bash -c "sudo init 0"
Log file created at: 2021/07/04 10:41:47
Running on machine: songzwdeMBP
Binary: Built with gc go1.16.4 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0704 10:41:47.453396   20861 out.go:291] Setting OutFile to fd 1 ...
I0704 10:41:47.453968   20861 out.go:343] isatty.IsTerminal(1) = true
I0704 10:41:47.453976   20861 out.go:304] Setting ErrFile to fd 2...
I0704 10:41:47.453982   20861 out.go:343] isatty.IsTerminal(2) = true
I0704 10:41:47.454198   20861 root.go:316] Updating PATH: /Users/songzw/.minikube/bin
W0704 10:41:47.454325   20861 root.go:291] Error reading config file at /Users/songzw/.minikube/config/config.json: open /Users/songzw/.minikube/config/config.json: no such file or directory
I0704 10:41:47.454420   20861 out.go:298] Setting JSON to false
I0704 10:41:47.455401   20861 mustload.go:65] Loading cluster: minikube
I0704 10:41:47.455889   20861 profile.go:148] Saving config to /Users/songzw/.minikube/profiles/minikube/config.json ...
I0704 10:41:47.456540   20861 mustload.go:65] Loading cluster: minikube
I0704 10:41:47.456727   20861 stop.go:39] StopHost: minikube
I0704 10:41:47.464519   20861 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:41:47.464824   20861 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:42:06.473142   20861 out.go:235] ❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 19.00762763s
W0704 10:42:06.473329   20861 out.go:235] 💡  Restarting the docker service may improve performance.
W0704 10:42:06.474952   20861 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:42:06.474980   20861 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:42:06.475408   20861 retry.go:31] will retry after 1.104660288s: context deadline exceeded
I0704 10:42:07.580930   20861 stop.go:39] StopHost: minikube
I0704 10:42:07.590706   20861 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:42:07.590995   20861 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:42:26.600528   20861 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:42:26.600557   20861 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:42:26.600573   20861 retry.go:31] will retry after 2.160763633s: context deadline exceeded
I0704 10:42:28.761638   20861 stop.go:39] StopHost: minikube
I0704 10:42:28.768963   20861 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:42:28.769242   20861 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:42:47.773898   20861 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:42:47.773939   20861 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:42:47.773963   20861 retry.go:31] will retry after 2.62026012s: context deadline exceeded
I0704 10:42:50.395236   20861 stop.go:39] StopHost: minikube
I0704 10:42:50.400960   20861 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:42:50.401752   20861 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:43:09.410117   20861 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:43:09.410147   20861 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:43:09.410165   20861 retry.go:31] will retry after 3.164785382s: context deadline exceeded
I0704 10:43:12.578474   20861 stop.go:39] StopHost: minikube
I0704 10:43:12.586175   20861 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:43:12.586436   20861 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:43:31.593759   20861 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:43:31.593781   20861 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:43:31.593796   20861 retry.go:31] will retry after 4.680977329s: context deadline exceeded
I0704 10:43:36.279672   20861 stop.go:39] StopHost: minikube
I0704 10:43:36.291228   20861 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:43:36.291490   20861 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:43:55.296286   20861 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:43:55.296310   20861 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:43:55.306045   20861 out.go:170]
W0704 10:43:55.306500   20861 out.go:235] ❌  Exiting due to GUEST_STOP_TIMEOUT: context deadline exceeded
W0704 10:43:55.306616   20861 out.go:235]
W0704 10:43:55.325807   20861 out.go:235] ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
W0704 10:43:55.325861   20861 out.go:235] │                                                                                                                       │
W0704 10:43:55.325883   20861 out.go:235] │    😿  If the above advice does not help, please let us know:                                                         │
W0704 10:43:55.325890   20861 out.go:235] │    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                       │
W0704 10:43:55.325898   20861 out.go:235] │                                                                                                                       │
W0704 10:43:55.325904   20861 out.go:235] │    Please attach the following file to the GitHub issue:                                                              │
W0704 10:43:55.326671   20861 out.go:235] │    - /var/folders/cx/76l8wn1x1vggh7vrccq6bc2m0000gn/T/minikube_stop_f1482b7056264a314ea464d5816b9795b65747d2_0.log    │
W0704 10:43:55.326685   20861 out.go:235] │                                                                                                                       │
W0704 10:43:55.326700   20861 out.go:235] ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
W0704 10:43:55.326708   20861 out.go:235]
Log file created at: 2021/07/04 10:44:52
Running on machine: songzwdeMBP
Binary: Built with gc go1.16.4 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0704 10:44:52.251439   20940 out.go:291] Setting OutFile to fd 1 ...
I0704 10:44:52.252180   20940 out.go:343] isatty.IsTerminal(1) = true
I0704 10:44:52.252194   20940 out.go:304] Setting ErrFile to fd 2...
I0704 10:44:52.252203   20940 out.go:343] isatty.IsTerminal(2) = true
I0704 10:44:52.252500   20940 root.go:316] Updating PATH: /Users/songzw/.minikube/bin
W0704 10:44:52.252697   20940 root.go:291] Error reading config file at /Users/songzw/.minikube/config/config.json: open /Users/songzw/.minikube/config/config.json: no such file or directory
I0704 10:44:52.252820   20940 out.go:298] Setting JSON to false
I0704 10:44:52.256373   20940 mustload.go:65] Loading cluster: minikube
I0704 10:44:52.258620   20940 profile.go:148] Saving config to /Users/songzw/.minikube/profiles/minikube/config.json ...
I0704 10:44:52.259046   20940 mustload.go:65] Loading cluster: minikube
I0704 10:44:52.259222   20940 stop.go:39] StopHost: minikube
I0704 10:44:52.270878   20940 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:44:52.271842   20940 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:45:11.279032   20940 out.go:235] ❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 19.006073946s
W0704 10:45:11.279255   20940 out.go:235] 💡  Restarting the docker service may improve performance.
W0704 10:45:11.280690   20940 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:45:11.280880   20940 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:45:11.281017   20940 retry.go:31] will retry after 1.104660288s: context deadline exceeded
I0704 10:45:12.388065   20940 stop.go:39] StopHost: minikube
I0704 10:45:12.401105   20940 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:45:12.401434   20940 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:45:31.407662   20940 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:45:31.407687   20940 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:45:31.407705   20940 retry.go:31] will retry after 2.160763633s: context deadline exceeded
I0704 10:45:33.569207   20940 stop.go:39] StopHost: minikube
I0704 10:45:33.576762   20940 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:45:33.576982   20940 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:45:52.585096   20940 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:45:52.585126   20940 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:45:52.585148   20940 retry.go:31] will retry after 2.62026012s: context deadline exceeded
I0704 10:45:55.210282   20940 stop.go:39] StopHost: minikube
I0704 10:45:55.221678   20940 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:45:55.221946   20940 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:46:14.230467   20940 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:46:14.230493   20940 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:46:14.230515   20940 retry.go:31] will retry after 3.164785382s: context deadline exceeded
I0704 10:46:17.396921   20940 stop.go:39] StopHost: minikube
I0704 10:46:17.403867   20940 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:46:17.404193   20940 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:46:36.409213   20940 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:46:36.409263   20940 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:46:36.409297   20940 retry.go:31] will retry after 4.680977329s: context deadline exceeded
I0704 10:46:41.092911   20940 stop.go:39] StopHost: minikube
I0704 10:46:41.104764   20940 out.go:170] ✋  Stopping node "minikube"  ...
I0704 10:46:41.104973   20940 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W0704 10:47:00.109762   20940 stop.go:75] unable to get state: unknown state "minikube": context deadline exceeded
W0704 10:47:00.109811   20940 stop.go:165] stop host returned error: ssh power off: unknown state "minikube": context deadline exceeded
I0704 10:47:00.119654   20940 out.go:170]
W0704 10:47:00.119947   20940 out.go:235] ❌  Exiting due to GUEST_STOP_TIMEOUT: context deadline exceeded
W0704 10:47:00.120069   20940 out.go:235]
W0704 10:47:00.137923   20940 out.go:235] ╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
W0704 10:47:00.137952   20940 out.go:235] │                                                                                                                       │
W0704 10:47:00.137975   20940 out.go:235] │    😿  If the above advice does not help, please let us know:                                                         │
W0704 10:47:00.137995   20940 out.go:235] │    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                       │
W0704 10:47:00.138013   20940 out.go:235] │                                                                                                                       │
W0704 10:47:00.138034   20940 out.go:235] │    Please attach the following file to the GitHub issue:                                                              │
W0704 10:47:00.138354   20940 out.go:235] │    - /var/folders/cx/76l8wn1x1vggh7vrccq6bc2m0000gn/T/minikube_stop_f1482b7056264a314ea464d5816b9795b65747d2_0.log    │
W0704 10:47:00.138375   20940 out.go:235] │                                                                                                                       │
W0704 10:47:00.138383   20940 out.go:235] ╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
W0704 10:47:00.138394   20940 out.go:235]

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you provide minikube logs ?


Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:


```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by sharifelgamal** [comment]
It looks like you are trying to restart a cluster where the config is gone:

```
Error reading config file at /Users/songzw/.minikube/config/config.json: open /Users/songzw/.minikube/config/config.json: no such file or directory
```

The best solution here is to run `minikube delete` then try `minikube start` again.

**Comment by spowelljr** [comment]
Hi @WinnerSong, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
