### ISSUE TITLE
Can't install ingress 

### ISSUE THREAD

**Issue by yan-v** [kubernetes/minikube#11900]
Hi,
the following command failing with timeout, logs attached
     >minikube addons enable ingress

minikube version: v1.21.0
[minikube_addons_70b86610413e6902e868350cf628a17efcae1d38_0.log](https://github.com/kubernetes/minikube/files/6762614/minikube_addons_70b86610413e6902e868350cf628a17efcae1d38_0.log)

**Comment by medyagh** [comment]
mind attaching this log file

minikube logs -f output.txt


@yan-v co is this a flake or consistent and what version of minikube do u sue?

**Comment by andriyDev** [comment]
I'm closing this issue since it's been quiet. Feel free to reopen!
