### ISSUE TITLE
virtualbox: Could not find matching IP for MAC address 08002718aeaf

### ISSUE THREAD

**Issue by aayusranjan** [kubernetes/minikube#11908]
**Steps to reproduce the issue:** 

1. minikube start
[lastStart.txt](https://github.com/kubernetes/minikube/files/6766495/lastStart.txt)

**Full output of `minikube logs` command:**
<details>
😄  minikube v1.21.0 on Ubuntu 21.04
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running virtualbox "minikube" VM ...
🤦  StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08002718aeaf
🏃  Updating the running virtualbox "minikube" VM ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08002718aeaf

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08002718aeaf

</details>

**Full output of failed command:**
<details>
🤦  StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08002718aeaf

😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08002718aeaf

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08002718aeaf

</details>

**Comment by medyagh** [comment]
@aayusranjan virtualbox is not our most supported driver, is there a reason you are not using KVM or docker driver on ubuntu ?

**Comment by aayusranjan** [comment]
_Oh, Thanks for response I appreciated it ._
Btw, I solved the issue by running ` minikube delete `and `minikube delete --all`
then after that `minikube start --driver=docker`
