### ISSUE TITLE
Resolve domain to ingress

### ISSUE THREAD

**Issue by gufoe** [kubernetes/minikube#11903]
My pods:  
- http-server (which i aliased in the host `/etc/hosts`: `192.168.49.2 example.test`)
- worker

Now from my machine I can go to http://example.test and it works nice

Problem:  
The worker pod cannot resolve `example.test` to the minikube instance.
I'd like to configure example.test requests to be directed to the minikube ingress so that they can correctly dispatched to the right pod.

What I tried:  
I tried using `minikube --dns-domain example.test` but it is not working.

Question:  
How can I set my cluster dns so that my pods resolve such domain to the cluster itself?

**Comment by medyagh** [comment]
Which Dunbar driver do you use? Which addons do you enable? What platform?

**Comment by gufoe** [comment]
I use the docker driver on a debian host

**Comment by oweise** [comment]
I have the same problem. 

Generally I would recommend using the [ingress-dns addon](https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/) so you actually don't need to modify the hostsfile to resolve to ingress dns from the host machine. I use the variant where I told my local dnsmasq to redirect DNS requests for a specific domain, I use "local.k8s", to the minikube dns. That will always returns the minikube ip. So all my local ingresses use the domain "local.k8s".

But while this addon supports my host machine to resolve ingress dns correctly, the minikube internal DNS is not able to resolve these internally itself. Which is even more strange as, when I understand correctly, minikube on docker driver SHOULD use the DNS from my host machine to resolve DNS requests. That again is dnsmasq and should totally be able to resolve to "local.k8s". However this does not work for unknown reasons.
