### ISSUE TITLE
Mention of "VirtualBox" in subcommand help

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/minikube#1191]
It appears like help messages for start/stop is mentioning VirtualBox:

Here, the second sentence isn't necessarily true anymore:

```
minikube start -h
Starts a local kubernetes cluster using Virtualbox. This command
assumes you already have Virtualbox installed.
```

Also:

```
minikube stop -h
Stops a local kubernetes cluster running in Virtualbox. [...]
```

People like me might be using xhyve drivers etc. In this case it won't be applicable.

Should these be changed? It's not a big deal and anyone who's using xhyve or some other driver explicitly must have done so, but stuff like `This command
assumes you already have Virtualbox installed.` might actually mislead people and imply that they should definitely install VirtualBox.

Thoughts?

**Comment by r2d4** [comment]
We put those there since virtual box is the default across all platforms. We are planning to change the defaults to KVM, HyperV, and Xhyve soon and change the help message.

Personally I'm fine if we just change the defaults now. I don't think there are any major blockers

**Comment by aaron-prindle** [comment]
Ref: #1352
