### ISSUE TITLE
--image-repository strips off container prefix

### ISSUE THREAD

**Issue by bodgit** [kubernetes/minikube#11934]
I'm trying to get minikube to work in an offline environment, or at least without direct access to the internet. I have Artifactory available and configured with a virtual Docker repository that ties together multiple upstream repositories (docker.io, k8s.gcr.io, gcr.io, etc.) together and presents them as a single registry.

The problem I'm having is that when I use the `--image-repository` option with minikube, it is removing any prefix from the image names, so for example `kubernetesui/dashboard` or `gcr.io/k8s-minikube/storage-provisioner` are being pulled as `docker.artifactory.example.com/dashboard` or `docker.artifactory,example.com/storage-provisioner` which doesn't work, however if you manually pull `docker.artifactory.example.com/k8s-minikube/storage-provisioner` it will succeed.

**Steps to reproduce the issue:** 

1. `minikube start --download-only --image-repository=docker.artifactory.example.com`
2. All images will be pulled apart from `kubernetesui/dashboard`, `kubernetesui/metrics-scraper` & `gcr.io/k8s-minikube/storage-provisioner` as they're the only ones with a prefix, all of the `k8s.gcr.io/*` images are fetched successfully.
3. It also affects the pulling of the kicbase image as the original name is `gcr.io/k8s-minikube/kicbase` so I suspect the `/k8s-minikube/` is being stripped there as well.

**Full output of `minikube start` command:**
<details>
minikube start --download-only --image-repository=docker.artifactory.example.com --kubernetes-version=v1.19.0
😄  minikube v1.22.0 on Redhat 7.9
🆕  Kubernetes 1.21.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.21.2
✨  Using the docker driver based on existing profile
❗  docker is currently using the devicemapper storage driver, consider switching to overlay2 for better performance

👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
❗  The image 'docker.artifactory.example.com/metrics-scraper:v1.0.4' was not found; unable to add it to cache.
❗  The image 'docker.artifactory.example.com/storage-provisioner:v5' was not found; unable to add it to cache.
❗  The image 'docker.artifactory.example.com/dashboard:v2.1.0' was not found; unable to add it to cache.
E0708 11:28:24.112160  101078 cache.go:200] Error downloading kic artifacts:  getting remote image: GET https://docker.artifactory.example.com/v2/kicbase/manifests/sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79: MANIFEST_UNKNOWN: The named manifest is not known to the registry.; map[manifest:kicbase]
✅  Download complete!
</details>

So either the `--image-repository` option needs to not strip any prefix from the image names or an additional option to tune whether to do that or not if it's going to break behaviour with other registries. So to summarise, I'm looking to be able to map the image names as follows:

kubernetesui/dashboard -> docker.artifactory.example.com/kubernetesui/dashboard
k8s.gcr.io/kube-apiserver -> docker.artifactory.example.com/kube-apiserver
gcr.io/k8s-minikube/storage-provisioner -> docker.artifactory.example.com/k8s-minikube/storage-provisioner
etc.

**Comment by medyagh** [comment]
@bodgit that seems to be a bug, Would you be interetested to a send a fix ? I would be happy to review a PR that fixes it

**Comment by bodgit** [comment]
@medyagh Sure, I can dig into the code and see if I can work out what is going on.

But doesn't this feature work for some people currently? Do some registry mirrors discard that extra prefix information, or have users been pushing/tagging the images to their local registry mirrors with the shortened names to match the minikube behaviour?

**Comment by bodgit** [comment]
See #11948 

With this applied, my cache now looks like this:
```
$ find .minikube/cache/
.minikube/cache/
.minikube/cache/images
.minikube/cache/images/registry.example.com
.minikube/cache/images/registry.example.com/kubernetesui
.minikube/cache/images/registry.example.com/kubernetesui/dashboard_v2.1.0
.minikube/cache/images/registry.example.com/kubernetesui/metrics-scraper_v1.0.4
.minikube/cache/images/registry.example.com/k8s-minikube
.minikube/cache/images/registry.example.com/k8s-minikube/storage-provisioner_v5
.minikube/cache/images/registry.example.com/kube-scheduler_v1.19.0
.minikube/cache/images/registry.example.com/kube-apiserver_v1.19.0
.minikube/cache/images/registry.example.com/coredns_1.7.0
.minikube/cache/images/registry.example.com/pause_3.2
.minikube/cache/images/registry.example.com/kube-proxy_v1.19.0
.minikube/cache/images/registry.example.com/etcd_3.4.9-1
.minikube/cache/images/registry.example.com/kube-controller-manager_v1.19.0
.minikube/cache/linux
.minikube/cache/linux/v1.19.0
.minikube/cache/linux/v1.19.0/kubelet
.minikube/cache/linux/v1.19.0/kubeadm
.minikube/cache/linux/v1.19.0/kubectl
.minikube/cache/kic
.minikube/cache/kic/kicbase_v0.0.25@sha256_6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79.tar
```
