### ISSUE TITLE
Ability to set a mirror for downloading kubectl, kubelet, & kubeadm

### ISSUE THREAD

**Issue by bodgit** [kubernetes/minikube#11935]
This is partly related to #11934 in that I'm trying to get minikube to work in an offline environment, or at least without direct internet connectivity. I have Artifactory configured as a Docker registry so assuming that issue is fixed, I don't need direct internet access to download the container images.

However minikube still needs internet access to download the three `kube*` binaries. If I configure proxy access then there's nothing really to stop the container images being pulled through the proxy as well, which I'd like to avoid as it circumvents our internal policies and checks. It would be handy if I could supply an alternative URL that could be used to download the three `kube*` binaries. I can then set up an internal mirror of the https://storage.googleapis.com/kubernetes-release/release/* content.

**Steps to reproduce the issue:** 

1. `minikube start --download-only --image-repository=docker.artifactory.example.com`
2. Containers are (mostly, see linked issue) downloaded, but it times out downloading `kubelet`, etc.

There is obviously the `--image-repository` option already, as well as the `--iso-url` option that could be used to point to an alternative location for the minikube ISO (I don't need/use that particular option), so it seems odd that there's no way to specify an alternative location for the remaining `kube*` binaries.

**Comment by bodgit** [comment]
This is where the binary URLs are constructed: https://github.com/kubernetes/minikube/blob/f40b6eabacca2c4400acb9531a8bf04826a96eba/pkg/minikube/download/binary.go#L35

**Comment by sharifelgamal** [comment]
I think this is a great idea!
