### ISSUE TITLE
docker-machine-driver-kvm2_1.22.0-0_arm64.deb has wrong package architecture

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [kubernetes/minikube#11930]
**Steps to reproduce the issue:** 

1. Download `docker-machine-driver-kvm2_1.22.0-0_arm64.deb` from the v1.22.0 release
2. Try to install it on an arm64 system, or (my initial case) try to add it to an apt repo that hosts arm64 packages
3. Errors out because the package internally says that it's `aarch64` when it should be `arm64`

The `minikube` package correctly has the `arm64` architecture.

**Full output of `minikube logs` command:**
N/A

**Full output of failed command:**
<details>

```
Error looking at 'docker-machine-driver-kvm2_1.22.0-0_arm64.deb': 'aarch64' is not one of the valid architectures: 'i386 amd64 armhf arm64 source'
```
</details>
<details>

```
 new Debian package, version 2.0.
 size 4649436 bytes: control archive=423 bytes.
     446 bytes,    12 lines      control
 Package: docker-machine-driver-kvm2
 Version: 1.22.0
 Section: base
 Priority: optional
 Architecture: aarch64
 Depends: libvirt0 (>= 1.3.1)
 Recommends: minikube
 Maintainer: Thomas Strömberg <t+minikube@stromberg.org>
 Description: Machine driver for KVM
  minikube uses Docker Machine to manage the Kubernetes VM so it benefits
  from the driver plugin architecture that Docker Machine uses to provide
  a consistent way to manage various VM providers.
```
</details>

**Comment by afbjorklund** [comment]
Simple mistake in 0033bf7ed3d8bd61aec9bbcc89b81caedec1a84a, using the wrong architecture for the deb packages:

```diff
 out/docker-machine-driver-kvm2_$(DEB_VERSION).deb: out/docker-machine-driver-kvm2_$(DEB_VERSION)-0_amd64.deb
        cp $< $@
 
+out/docker-machine-driver-kvm2_$(DEB_VERSION)-$(DEB_REVISION)_amd64.deb: out/docker-machine-driver-kvm2_$(DEB_VERSION)-0_x86_64.deb
+       cp $< $@
+
+out/docker-machine-driver-kvm2_$(DEB_VERSION)-$(DEB_REVISION)_arm64.deb: out/docker-machine-driver-kvm2_$(DEB_VERSION)-0_aarch64.deb
+       cp $< $@
+
```

Should be amd64 and arm64 for .deb, even if it is x86_64 and aarch64 for .arm.

@mgabeler-lee-6rs : as a workaround, you can download the separate arm64 binary.

**Comment by medyagh** [comment]
Cc: @ilya-zuyev
