### ISSUE TITLE
Skipping CI for Draft Pull Request.

### ISSUE THREAD

**Issue by klutingrusang8377** [kubernetes/minikube#11952]
Skipping CI for Draft Pull Request.
If you want CI signal for your change, please convert it to an actual PR.
You can still manually trigger a test run with `/test all`

_Originally posted by @k8s-ci-robot in https://github.com/kubernetes/community/issues/5824#issuecomment-858043641_

**Comment by medyagh** [comment]
I agree we shuld not run CI on Draft PRs

**Comment by sharifelgamal** [comment]
we can add one of the following to our github action yamls:
`if: github.event.pull_request.draft == false`

or

```
on:
  pull_request:
    types: [review_requested, ready_for_review]
```
