### ISSUE TITLE
minikube driver check should not call sudo, if sudo fails 

### ISSUE THREAD

**Issue by bigon** [kubernetes/minikube#11973]
**Steps to reproduce the issue:** 

1. minikube start (without `--driver`)

**Full output of `minikube logs` command:**
```
😄  minikube v1.22.0 on Debian 11.0
✨  Automatically selected the docker driver. Other choices: kvm2, ssh
👍  Starting control plane node minikube in cluster minikube
[...]
```

It seems that minikube stills calls podman executable (and sudo) even if it tells that it uses docker. I see logs/mails coming from sudo telling me that minikube tried to run podman executable without providing a password

Messages like:

> edoras.bigon.be : Jul 14 09:36:54 : bigon : a password is required ; TTY=pts/2 ; PWD=/home/bigon/bin ; USER=root ; COMMAND=/usr/bin/podman version --format {{.Version}}
> edoras.bigon.be : Jul 14 10:05:28 : bigon : a password is required ; TTY=pts/2 ; PWD=/home/bigon ; USER=root ; COMMAND=/usr/bin/podman ps -a --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Names}}
> edoras.bigon.be : Jul 14 10:05:28 : bigon : a password is required ; TTY=pts/2 ; PWD=/home/bigon ; USER=root ; COMMAND=/usr/bin/podman volume ls --filter label=name.minikube.sigs.k8s.io=minikube --format {{.Name}}
> edoras.bigon.be : Jul 14 10:05:28 : bigon : a password is required ; TTY=pts/2 ; PWD=/home/bigon ; USER=root ; COMMAND=/usr/bin/podman network ls --filter=label=created_by.minikube.sigs.k8s.io --format {{.Name}}
> [...]

**Comment by afbjorklund** [comment]
I think this is the driver auto-detection in action... You can select the docker driver explicitly, to avoid it...

It assumes that if podman is installed, that it has also been setup for passwordless sudo (`sudo -n podman`)

Similarly it assumes that if docker is installed, that the user has been added to the root-equivalent group (no sudo)

There is no particular reason why podman couldn't use a group or docker use sudo, other than "historic reasons".

**Comment by afbjorklund** [comment]
I suppose we could try parsing the output of `sudo -l`, before trying to invoke `sudo -k -n podman`.

1) Check for podman
2) Check for sudo
3) Check for sudo podman

There are a few corner cases like ALL and groups and such, but other than that it should be there.

**Comment by medyagh** [comment]
@bigon the reason minikube is calling podman, it is because when you don't specify the driver with --driver flag, minikube will check all installed tools on your system and automatically select best driver (most healthy one)

**Comment by bigon** [comment]
The main problem is that it calls sudo, it immediately fails and and sudo failures generate a mail

**Comment by clintonyeb** [comment]
@medyagh I would like to pick this up as a good first issue. Could you please give me some pointers? I am looking at `driver/driver.go` which seems to be responsible for selecting the best driver to run with.

**Comment by djplt** [comment]
@clintonyeb just wanted to check if you were still working on this issue or if I'm okay to pick this up?

**Comment by klaases** [comment]
Hi @djplt, @medyagh left a comment on your PR, once we merge the PR we can close this issue. Thanks!
