### ISSUE TITLE
System has not been booted with systemd as init system (PID 1). Can't operate. Failed to connect to bus: Host is down

### ISSUE THREAD

**Issue by farhat67** [kubernetes/minikube#11975]
**Steps to reproduce the issue:** 

1.sudo minikube start --vm-driver=none
2.minikube delete
3.Tried sudo minikube start 
4. Also tried start Ubuntu as administrator 

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>
😄 minikube v1.22.0 on Ubuntu 20.04 ✨ Using the none driver based on existing profile 👍 Starting control plane node minikube in cluster minikube 🔄 Restarting existing none bare metal machine for "minikube" ... ℹ️ OS release is Ubuntu 20.04.2 LTS
❌ Exiting due to RUNTIME_ENABLE: sudo systemctl daemon-reload: exit status 1
stdout:

stderr:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

╭────────────────────────────────────────────────────────────────────╮
│ │
│ 😿 If the above advice does not help, please let us know: │
│ 👉 https://github.com/kubernetes/minikube/issues/new/choose │
│ │
│ Please attach the following file to the GitHub issue: │
│ - /root/.minikube/logs/lastStart.txt │
│ │
╰────────────────────────────────────────────────────────────────────╯

</details>

**Comment by spowelljr** [comment]
Is this native Ubuntu, or is this WSL on Windows?

**Comment by farhat67** [comment]
It's WSL 2.

**Comment by spowelljr** [comment]
Could you please include the log file located here `/root/.minikube/logs/lastStart.txt`, this would help debug the issue.

Also, I found a SO post with the same issue, not sure if that provides any insight or not
https://stackoverflow.com/questions/52197246/system-has-not-been-booted-with-systemd-as-init-system-pid-1-cant-operate
