### ISSUE TITLE
Troubleshooting

### ISSUE THREAD

**Issue by thedag** [kubernetes/minikube#11976]
I am having nothing but problems so far, trying to get this supposedly "production ready" Kubernetes stuff up and running at all.

And now it turns out even the troubleshooting instructions offer nothing but more error messages in my face.

The world I am used to: you get an installer, you follow mostly easy-to-understand instructions or accept defaults where you don't quite know what some choice involves, and the software installs and works. Usually you're asked if you'd like to launch it at the end of the installation process, but whether you say yes or no, it is generally super easy to find and launch again via a searchable, graphical interface...

I hear terminals are really cool, but I am really not sold on this so far. Basically trying to use this stuff consists of copying various commands, usually requiring root access, from around the internet and hope something good might come of it. And this is a pretty risky business, since the official instructions produce nothing but error messages. I tried to do the "manual" install via curl, it spits out something incomprehensible about not being able to write the output (yes, with sudo, and as su; I tried that, too), install via package manager (first, edit package sources files... wtf are you guys thinking?

`minikube start` fails with the to me (made a living as a programmer since 2001) incomprehensible diagnostic "dial tcp: missing address". What dialling has to do with TCP IDK, but I understand something tried to talk to something using TCP but some address is missing. Why the programmer who knows EXACTLY what that address is used for and perhaps also where it came from didn't bother to spend one minute including something instructive in the diagnostic, and thereby saving hundreds of thousands of people HOURS if not DAYS of incredibly tedious guesswork at WTF might be the problem... is beyond me. 

But I also get errors of a CLASS that simply shouldn't exist if the quality of this ecosystem (software, docs) was up to snuff. To troubleshoot you suggest `minikube log --problems`, but minikube says "unknown flag: problems". Either it's the program that lies about what flags exist (perhaps it does this when minikube isn't running, as it refuses to start due to the aforementioned "dial" problem), or the docs and reality are so out of sync as to make the former (and thus for us new to this, also the latter) utterly useless.

I began fighting with this stuff on Friday and after many hours trying the same things or slight variations over and over it suddenly succeeded starting up, and I managed to get into the dashboard. I thought something might be due to the fact I had to add my user to a group or two along the way, and it seems in terminal you must explicitly tell it to refresh the group memberships, so maybe there were some processes that used outdated group membership data or something. Then my battery died and I haven't tried more until today, only to find that absolutely nothing works AGAIN.

I have docker and VirtualBox installed, though my understanding is I only need a hypervisor and that VirtualBox is the default choice (presumably the easiest one to get started with). 

Now, I'm sure somebody will give me the "this is an open source thingy" speech - as if this in any ways makes it any different for users who want to get stuff running. I really don't care about the reasons WHY absolutely nothing works as advertised, I want to know where it is possible to find instructions that work so i can get the damn thing going without having to spend two and a half eternities.

**Comment by thedag** [comment]
I'm now trying to follow instructions at https://www.linuxtechi.com/how-to-install-minikube-on-ubuntu/ - and so far, it looks much more promising (though it IS a bit crazy to just blindly trust someone able to publish at linuxtechi, which I've never heard of before, with my root).

**Comment by spowelljr** [comment]
Hi @thedag, thanks for reporting your issue with minikube! Sorry you're having problems getting started with minikube. We recommend against using VirtualBox, it is very error prone with minikube, we're currently in the process of adding a message for users who start minikube using VirtualBox recommending them to use another driver. If you're going to be changing clusters, I recommend you run `minikube delete -all` to delete all existing clusters to ensure you're in a clean slate. If you have Docker installed and running, minikube should default to using it, but as you pointed out you can pass the `--driver docker` flag to be sure it will use Docker. If you have any problems feel free to report back and we can try and help you with your issues.

GUI's can be very nice, but almost the entirety of the kubernetes ecosystem is CLI only (kubectl, kubeadm, etc.) so using the terminal to work with kubernetes is very common place.

**Comment by spowelljr** [comment]
Hi @thedag, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
