### ISSUE TITLE
Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: command failed

### ISSUE THREAD

**Issue by dstjahjono** [kubernetes/minikube#11980]
Hi,

I have no idea what could be wrong, suddenly I can't start minikube 😣

$ minikube start
* minikube v1.2.0 on linux (amd64)

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the kvm2 driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`

* Restarting existing kvm2 VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
* Relaunching Kubernetes v1.15.0 using kubeadm ...

X Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml
stdout: [certs] Using certificateDir folder "/var/lib/minikube/certs/"
[certs] Using existing etcd/ca certificate authority

stderr: error execution phase certs/etcd-healthcheck-client: failed to write or validate certificate "etcd-healthcheck-client": failure loading etcd/healthcheck-client certificate: failed to load certificate: the certificate has expired
: Process exited with status 1

**Comment by spowelljr** [comment]
Hi @dstjahjono, thanks for reporting your issue with minikube!

So from the logs you provided me it seems you're trying to start minikube with the `--vm-driver=virtualbox` flag, but you have an existing cluster running that's using the kvm2 driver.

Please delete all existing clusters using `minikube delete --all` then try starting minikube again with `minikube start --vm-driver=virtualbox` and let me know if that solves your issue.

**Comment by dstjahjono** [comment]
Hi @spowelljr ,

1) I got this with "-all"

$ minikube delete --all
Error: unknown flag: --all
Usage:
  minikube delete [flags]

Flags:
  -h, --help   help for delete

Global Flags:
      --alsologtostderr                  log to standard error as well as files
  -b, --bootstrapper string              The name of the cluster bootstrapper that will set up the kubernetes cluster. (default "kubeadm")
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
  -p, --profile string                   The name of the minikube VM being used.
                                                This can be modified to allow for multiple minikube instances to be run independently (default "minikube")
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

2) So I run with 

$ minikube delete --alsologtostderr
* Deleting "minikube" from kvm2 ...
W0716 02:20:23.465012   14641 exit.go:100] Failed to delete cluster: destroying running domain: virError(Code=55, Domain=20, Message='Requested operation is not valid: doman is not running')

X Failed to delete cluster: destroying running domain: virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

(Apparently it's not working)


3) Try to start

$ minikube start --vm-driver=virtualbox
* minikube v1.2.0 on linux (amd64)

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the kvm2 driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`

* Re-using the currently running kvm2 VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
* Relaunching Kubernetes v1.15.0 using kubeadm ...

X Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm init phase certs all --config /var/lb/kubeadm.yaml
stdout: [certs] Using certificateDir folder "/var/lib/minikube/certs/"
[certs] Using existing ca certificate authority

stderr: error execution phase certs/apiserver-kubelet-client: failed to write or validate certificate "apiserver-kubelet-client": failure loading apiserver-kubelet-client crtificate: failed to load certificate: the certificate has expired
: Process exited with status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
* Problems detected in "kube-addon-manager":
  - error: no objects IpassNFedO t: o Leaapdeplr y
  - error: no objects passedINFO t: o==  aKupbply

**Comment by spowelljr** [comment]
Hi @dstjahjono, thanks for reporting back! I just noticed you're using v1.2.0 of minikube. This version is over two years old, there have been uncountable features and improvements introduced since then. Our latest version of minikube is v1.22.0, I strongly recommend you update to this version as you'll have a much better experience with minikube.

You can find install instructions here: https://minikube.sigs.k8s.io/docs/start/
I also recommend you run `minikube delete --all --purge` when you install the new version of minikube as the configs in v1.2.0 may be too old to the newest version to understand.

Let me know how that goes!

**Comment by dstjahjono** [comment]
Hi @spowelljr ,

The '--all' option is not working.

$ minikube delete --all --purge
Error: unknown flag: --all
Usage:
  minikube delete [flags]

Flags:
  -h, --help   help for delete

Global Flags:
      --alsologtostderr                  log to standard error as well as files
  -b, --bootstrapper string              The name of the cluster bootstrapper that will set up the kubernetes cluster. (default "kubeadm")
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
  -p, --profile string                   The name of the minikube VM being used.
                                                This can be modified to allow for multiple minikube instances to be run independently (default "minikube")
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

**Comment by spowelljr** [comment]
@dstjahjono Did you update to v1.22.0? v1.2.0 is so old it doesn't support the all flag

**Comment by medyagh** [comment]
Hi @dstjahjono , I haven't heard back from you, I wonder if you tried to download the Latest minikube version ?

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
