### ISSUE TITLE
Minikube v1.22.0 cannot load E:\image tar.gz

### ISSUE THREAD

**Issue by sunbinzhu** [kubernetes/minikube#11992]
I used to run the following command to load an image archive file into Minikube. It worked pretty well in V1.20.0. But when i upgraded to V1.22.0, it didn't work anymore, there was no error message, but when i ran "minikube image list", the image didn't show up. I  also tried v1.21.0, it didn't work either. 

minikube image load e:\myimage.tar.gz
minikube image list

**Comment by sunbinzhu** [comment]
Any update on this issue? Or do you need any more information?

**Comment by sharifelgamal** [comment]
This definitely seems like a bug in our `minikube image` subcommand. What VM driver and container runtime are you using?

cc @afbjorklund

**Comment by afbjorklund** [comment]
Pretty sure that `E:\` DOS path could have something to do with it... Can you try with a `cd`, and then without the drive letter ?

**Comment by afbjorklund** [comment]
Sadly the image load command doesn't show any output to the console, so all the information would be in the minikube log

**Comment by sunbinzhu** [comment]
> Pretty sure that `E:\` DOS path could have something to do with it... Can you try with a `cd`, and then without the drive letter ?

Thanks @afbjorklund, just tried, you are right, if i cd into the folder and then load the image with file name (but not the full file path), it worked, so we got a workaround for this issue. But as i mentioned, loading with the full file path used to work in v1.20, and broke in v1.21. Since the root cause is clear, could you guys help to fix? Thanks

And below is the output with the full file path:
minikube --alsologtostderr image load e:\temp\test.tar.gz
I0805 14:09:15.448641    4656 out.go:286] Setting OutFile to fd 84 ...
I0805 14:09:15.482116    4656 out.go:333] TERM=,COLORTERM=, which probably does not support color
I0805 14:09:15.483127    4656 out.go:299] Setting ErrFile to fd 88...
I0805 14:09:15.484124    4656 out.go:333] TERM=,COLORTERM=, which probably does not support color
I0805 14:09:15.537263    4656 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
I0805 14:09:16.796131    4656 cli_runner.go:168] Completed: docker container inspect minikube --format={{.State.Status}}: (1.258873s)
I0805 14:09:16.815164    4656 ssh_runner.go:149] Run: systemctl --version
I0805 14:09:16.828998    4656 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0805 14:09:17.272132    4656 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:56625 SSHKeyPath:C:\Users\sunbinzhu\.minikube\machines\minikube\id_rsa Username:docker}
I0805 14:09:17.376351    4656 docker.go:236] Removing image: e:\temp\test.tar.gz
I0805 14:09:17.391972    4656 ssh_runner.go:149] Run: docker rmi e:\temp\test.tar.gz
W0805 14:09:17.430959    4656 cache_images.go:244] Failed to load cached images for profile minikube. make sure the profile is running. loading images: removing image: remove image docker.: docker rmi e:\temp\test.tar.gz: Process exited with status 1
stdout:

stderr:
Error response from daemon: invalid reference format
I0805 14:09:17.431483    4656 cache_images.go:252] succeeded pushing to:
I0805 14:09:17.432525    4656 cache_images.go:253] failed pushing to: minikube

**Comment by afbjorklund** [comment]
Seems to be a bug introduced in 32a91d6eb29c477e4f197b4387f5bbee5592b2af

It assumes that the filename is the same as the image name, which is only true in the cache - but fails when loading files.

**Comment by spowelljr** [comment]
@afbjorklund I created a PR that solves the issue, but if you have a better way in mind feel free to comment on it.

I'm going to add a test to catch this case tomorrow.
