### ISSUE TITLE
minikube start failure.

### ISSUE THREAD

**Issue by corbaejb** [kubernetes/minikube#11999]
**重现问题所需的命令**：minikube start

**失败的命令的完整输出**：<details>

* Microsoft Windows 10 Pro 10.0.19042 Build 19042 上的 minikube v1.22.0
* 自动选择 docker 驱动。其他选项：virtualbox, ssh
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
! The image 'k8s.gcr.io/kube-scheduler:v1.21.2' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/pause:3.4.1' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/kube-proxy:v1.21.2' was not found; unable to add it to cache.
! The image 'docker.io/kubernetesui/metrics-scraper:v1.0.4' was not found; unable to add it to cache.
! The image 'gcr.io/k8s-minikube/storage-provisioner:v5' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/kube-apiserver:v1.21.2' was not found; unable to add it to cache.
! The image 'docker.io/kubernetesui/dashboard:v2.1.0' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/etcd:3.4.13-0' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/kube-controller-manager:v1.21.2' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/coredns/coredns:v1.8.0' was not found; unable to add it to cache.
E0719 14:17:52.838193   17680 cache.go:200] Error downloading kic artifacts:  failed to download kic base image or any fallback image
* Creating docker container (CPUs=2, Memory=8100MB) ...
! StartHost failed, but will try again: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

* docker "minikube" container is missing, will recreate.
* Creating docker container (CPUs=2, Memory=8100MB) ...
* Failed to start docker container. Running "minikube delete" may fix it: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

! Startup with docker driver failed, trying with alternate driver virtualbox: Failed to start host: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

* 正在删除 docker 中的“minikube”…
* 正在移除 C:\Users\86133\.minikube\machines\minikube…
! Failed to delete cluster minikube, proceeding with retry anyway.
* 正在下载 VM boot image...
E0719 14:19:09.949898   17680 iso.go:88] Unable to download https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso.sha256 Dst:C:\Users\86133\.minikube\cache\iso\minikube-v1.22.0.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3968488 0x3968488 0x3968488 0x3968488 0x3968488 0x3968488 0x3968488] Decompressors:map[bz2:0x3968488 gz:0x3968488 tar:0x3968488 tar.bz2:0x3968488 tar.gz:0x3968488 tar.xz:0x3968488 tar.zst:0x3968488 tbz2:0x3968488 tgz:0x3968488 txz:0x3968488 tzst:0x3968488 xz:0x3968488 zip:0x3968488 zst:0x3968488] Getters:map[file:0xc000c50e20 http:0xc0005b87e0 https:0xc0005b8800] Dir:false ProgressListener:0x3914080 Insecure:false Options:[0x1d9c5c0]}: invalid checksum: Error downloading checksum file: Get "https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso.sha256": proxyconnect tcp: EOF
* 正在下载 VM boot image...
E0719 14:19:11.280654   17680 iso.go:88] Unable to download https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-v1.22.0.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-v1.22.0.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-v1.22.0.iso.sha256 Dst:C:\Users\86133\.minikube\cache\iso\minikube-v1.22.0.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3968488 0x3968488 0x3968488 0x3968488 0x3968488 0x3968488 0x3968488] Decompressors:map[bz2:0x3968488 gz:0x3968488 tar:0x3968488 tar.bz2:0x3968488 tar.gz:0x3968488 tar.xz:0x3968488 tar.zst:0x3968488 tbz2:0x3968488 tgz:0x3968488 txz:0x3968488 tzst:0x3968488 xz:0x3968488 zip:0x3968488 zst:0x3968488] Getters:map[file:0xc000c51380 http:0xc0005b89c0 https:0xc0005b89e0] Dir:false ProgressListener:0x3914080 Insecure:false Options:[0x1d9c5c0]}: invalid checksum: Error downloading checksum file: Get "https://github.com/kubernetes/minikube/releases/download/v1.22.0/minikube-v1.22.0.iso.sha256": proxyconnect tcp: EOF
* 正在下载 VM boot image...
E0719 14:19:12.508932   17680 iso.go:88] Unable to download https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.22.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.22.0.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.22.0.iso.sha256 Dst:C:\Users\86133\.minikube\cache\iso\minikube-v1.22.0.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3968488 0x3968488 0x3968488 0x3968488 0x3968488 0x3968488 0x3968488] Decompressors:map[bz2:0x3968488 gz:0x3968488 tar:0x3968488 tar.bz2:0x3968488 tar.gz:0x3968488 tar.xz:0x3968488 tar.zst:0x3968488 tbz2:0x3968488 tgz:0x3968488 txz:0x3968488 tzst:0x3968488 xz:0x3968488 zip:0x3968488 zst:0x3968488] Getters:map[file:0xc000c51930 http:0xc0005b8c20 https:0xc0005b8c40] Dir:false ProgressListener:0x3914080 Insecure:false Options:[0x1d9c5c0]}: invalid checksum: Error downloading checksum file: Get "https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.22.0.iso.sha256": proxyconnect tcp: EOF

X Exiting due to GUEST_PROVISION: Failed to start host: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.

*
╭──────────────────────────────────────────────────────────────────╮
│                                                                  │
│    * If the above advice does not help, please let us know:      │
│      https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                  │
│    * Please attach the following file to the GitHub issue:       │
│    * - C:\Users\86133\.minikube\logs\lastStart.txt               │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

Microsoft Windows 20H2 (OS Build 19042.1083
[lastStart.txt](https://github.com/kubernetes/minikube/files/6838436/lastStart.txt)

**Comment by spowelljr** [comment]
Hi @corbaejb, thanks for reporting your issue with minikube!

It seems like you're using minikube from China, am I correct?

If so, run:
```
minikube start --image --image-mirror-country=cn
```

And then it will pull the images from `registry.cn-hangzhou.aliyuncs.com` instead of `gcr.io`.

-----

嗨@corbaejb，感谢您报告您的 minikube 问题！

好像你在使用来自中国的 minikube，我说得对吗？

如果是这样，请运行：
```
minikube start --image --image-mirror-country=cn
```

然后它会从`registry.cn-hangzhou.aliyuncs.com`而不是`gcr.io`拉取图像。

**Comment by spowelljr** [comment]
Hi @corbaejb, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
