### ISSUE TITLE
Provide installation script

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#12]
Later we'll have full .dmg/deb/msi installers.

**Comment by dlorenc** [comment]
We should ship checksums of all components as well.

Ref #41

**Comment by luxas** [comment]
Is this for the first version or not?

**Comment by dlorenc** [comment]
I'd say no. This can come right after.

**Comment by dlorenc** [comment]
Let's start with a homebrew installer for OSX.

**Comment by dlorenc** [comment]
We should check the machine for dependencies during installation.

**Comment by luxas** [comment]
Also, a .deb package would be great.
We may host the packages on packagecloud.io if you (Google) don't want to setup an own deb/rpm/whatever repositories.
Generally, it might be a good idea to have at least a deb repository for kubernetes

**Comment by dlorenc** [comment]
Yeah, a .deb would be cool. We currently host some other .debs for GCP stuff, I'll look into how that is setup. packagecloud.io looks nice too.

Here's what we'd have ideally:

* A brew installer for OSX
* A .pkg/img installer for OSX
* A .deb installer
* A .rpm installer
* A chocolatey installer for Windows

These should all include minikube, the .iso, man pages, bash completion (where relevant), kubectl (if the user doesn't already have it) and a docker CLI (if the user doesn't already have it).

**Comment by ramitsurana** [comment]
Checkout https://github.com/ramitsurana/turbo/blob/master/cmd/minikube.go

**Comment by r2d4** [comment]
- [x] A brew installer for OSX
- [x] A .pkg/img installer for OSX
- [x] A .deb installer
- [ ] A .rpm installer
- [ ] A chocolatey installer for Windows
- [x] MSI for Windows
- [x] Arch linux PKGBUILD

Closing this as we have a good number of installers for all platforms for now.
