### ISSUE TITLE
gcp-auth registries is too restrictive

### ISSUE THREAD

**Issue by briandealwis** [kubernetes/minikube#12003]
The gcp-auth addon configures `kubernetes.io/dockercfg` secrets but only for `gcr.io` and `us-docker.pkg.dev`.
https://github.com/kubernetes/minikube/blob/791e3b59c193e0f2b3f1b675f52e3f71c6b1ab57/pkg/addons/addons_gcpauth.go#L134-L136

We should either make this configurable or add support for a broader set of endpoints.

One approach would be to query GCR/AR for the list of registries visible to the account.

cc: @sharifelgamal

**Comment by sharifelgamal** [comment]
yeah good call, when I originally implemented gcp-auth I made the explicit choice to not worry about registry mirrors, now is a good time to fix that.

**Comment by briandealwis** [comment]
I followed up with the GCR/AR team and they suggested either hard-coding a list or taking a dependency on https://github.com/GoogleCloudPlatform/docker-credential-gcr/blob/faed5e8b8ca2a14e6cfff27ec915dbbdcce696ea/config/const.go#L49-L77
