### ISSUE TITLE
Site: add icon to side bar items

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#12025]
every top item in the side bar should have some sort of icon or at least a - or a box icon so it is easier to see that items under handbook are indented.
<img width="182" alt="Screen Shot 2021-07-20 at 1 29 38 PM" src="https://user-images.githubusercontent.com/4564227/126391269-0daea13b-89dc-4076-ad9f-24cedfcef1e9.png">

for example

- Get Started
- Handbook
      (clear indent)
- FAQ
- Presentations
- ...

https://minikube.sigs.k8s.io/docs/

**Comment by coolamiy** [comment]
@medyagh how about this ?
![image](https://user-images.githubusercontent.com/29359234/126772901-46420048-5a76-4608-a238-3fdc286ff431.png)
