### ISSUE TITLE
Report crun version in `minikube version`

### ISSUE THREAD

**Issue by andriyDev** [kubernetes/minikube#12027]
Important location: https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/version.go#L55

Discussion: https://kubernetes.slack.com/archives/C1F5CT6Q1/p1626820802044000?thread_ts=1626811554.016000&cid=C1F5CT6Q1

**Comment by amino19** [comment]
@andriyDev : Important location link is not working..? :thinking:

**Comment by andriyDev** [comment]
@amino19 Woops! I guess my link extension doesn't work haha, fixed!

**Comment by jayesh-srivastava** [comment]
Hi. Is this issue open? Can I work on it?

**Comment by amino19** [comment]
> Hi. Is this issue open? Can I work on it?

@jayesh-srivastava : Hi, Thanks for showing interest.
Pl go through the links, mentioned by @andriyDev, & ones you feel comfortable to get started with, give a shot with PR, after self-assigning yourself, by typing `/assign` :slightly_smiling_face:

**Comment by jayesh-srivastava** [comment]
Okay sure. Thank you so much. I am a new contributor here but will try to work on this.

**Comment by jayesh-srivastava** [comment]
Hi @amino19 , I have somewhat understood what needs to be done, basically, I'll have to add crun in the list. Just wanted to ask that what will be its value and is that all that I have to do. Your help will be much appreciated : )

**Comment by spowelljr** [comment]
@jayesh-srivastava `crun --version` gets you the version for crun. The only other thing that needs to be done is update the test to ensure it's actually being output.

https://github.com/kubernetes/minikube/blob/master/test/integration/functional_test.go#L1983

**Comment by afbjorklund** [comment]
Note that `crun --version` also output some extra junk  (beyond version), but fixed in PR #12085

```
$ crun --version
crun version 0.20.1.5-925d-dirty
commit: 0d42f1109fd73548f44b01b3e84d04a279e99d2e
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL
```

The "dirty" thing is some kind of upstream packaging bug, modifying the source before building...

https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/crun

**Comment by jayesh-srivastava** [comment]
Hey @spowelljr I have added the crun version. I am facing some issues in updating the tests to output it. I have made a PR without updating the test. Can anyone guide me through how to update the tests?

**Comment by spowelljr** [comment]
Hi @jayesh-srivastava, to update the test all you need to do is add crun to the list of strings to search for in the output.

https://github.com/kubernetes/minikube/blob/master/test/integration/functional_test.go#L2140

**Comment by jayesh-srivastava** [comment]
Hey @spowelljr I have understood and will update the test. Thank you. I already made a PR earlier without updating the test. Should I make a new one?

**Comment by spowelljr** [comment]
@jayesh-srivastava You should update the existing PR since it hasn't been merged yet, just commit another change to the same branch and push it again, thanks!

**Comment by jayesh-srivastava** [comment]
@spowelljr Gotcha, thanks!

**Comment by jayesh-srivastava** [comment]
Hey @spowelljr, made the necessary change and updated the existing PR.

**Comment by spowelljr** [comment]
@jayesh-srivastava The change looks good, thanks! Waiting for the tests to finish to make sure they pass.

In the meantime, could you address @medyagh's comment: https://github.com/kubernetes/minikube/pull/12381#issuecomment-909670462

All he's asking is to run `minikube version --components` against the master branch and save the output and then do the same thing on your own branch and then put both the outputs into the PR description so we can easily see the difference. You can use my recent PR as an example of what he means #12437.

**Comment by jayesh-srivastava** [comment]
@spowelljr Sure will try to address this.

**Comment by jayesh-srivastava** [comment]
Hey @spowelljr regarding yesterday's PR, only one test is failing. Can you please address this and tell me what's the issue?

**Comment by jayesh-srivastava** [comment]
@spowelljr Attaching a screenshot for your reference:
![Screenshot (803)](https://user-images.githubusercontent.com/49337716/132729845-184515e5-fde3-445b-ae36-e327f8348826.png)

**Comment by spowelljr** [comment]
@jayesh-srivastava minikube has tests that are flakey (fail from time to time), in this case the test that failed is `TestFunctional/parallel/MountCmd/any-port` which is completely unrelated to anything you changed. So don't worry about the test failure, we're used to it and know to check what exactly failed and ignore it if it's unrelated.

**Comment by jayesh-srivastava** [comment]
Oh okay @spowelljr. So will my PR be approved?

**Comment by spowelljr** [comment]
Your PR is already approved, it just needs to be merged, I'll merge it now.

**Comment by jayesh-srivastava** [comment]
Thanks @spowelljr
