### ISSUE TITLE
Minikube crashing after laptop sleep OSX

### ISSUE THREAD

**Issue by arthurlm44** [kubernetes/minikube#1203]
I occasionally encounter weird behavior from my minikube.
It would appear that this is caused by my laptop going to sleep.
When trying to run any minikube command, including `stop`, `start`, or `status`, I get the following:
```
~/ansible-workstation (fix-ssl *) $ minikube status
E0301 13:47:15.765383   55600 status.go:57] Error getting machine status: Something went wrong running an SSH command!
command :
if which systemctl 2>&1 1>/dev/null; then
  sudo systemctl is-active localkube 2>&1 1>/dev/null && echo "Running" || echo "Stopped"
else
  if ps $(cat /var/run/localkube.pid) 2>&1 1>/dev/null; then
    echo "Running"
  else
    echo "Stopped"
  fi
fi

err     : exit status 255
output  :
```

**Minikube version** (use `minikube version`): `minikube version: v0.16.0`

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): `minikube-v1.0.6.iso`
- **Install tools**:
- **Others**:

**Comment by forresthopkinsa** [comment]
I had a different error: after my Macbook went to sleep and woke back up, I couldn't start the dashboard or access the Minikube network. Stopping and starting minikube would interrupt a long-running operation, so I instead did `minikube pause -A && minikube unpause -A` and it fixed the problem.

**Comment by cglacet** [comment]
I have a similar issue, but it is completely silent. 

Everytime my laptop goes to sleep, minikube doesn't work anymore, running `minikube status` hang forever.

The only solution (that is not really viable) is to restart docker (app), then run `minikube start` again.

```bash
$ minikube version
minikube version: v1.33.1
commit: 5883c09216182566a63dff4c326a6fc9ed2982ff
```

When I start minikube I have some errors, maybe its related?

```bash
😄  minikube v1.33.1 on Darwin 14.4.1
... 
🐳  Preparing Kubernetes v1.25.2 on Docker 20.10.20 ...\ Bad local forwarding specification '0:localhost:8443'
```

**Comment by humb1t** [comment]
Same for me as @forresthopkinsa mentioned. Minikube does not survive mac os sleep.

**Comment by alessandrocavalli** [comment]
No updates on this?
