### ISSUE TITLE
Unable to start Minikube on Windows 10

### ISSUE THREAD

**Issue by HemanthAditi** [kubernetes/minikube#12048]
Please find the minikube logs

Log file created at: 2021/07/24 09:59:20
Running on machine: LAPTOP-G373LAE7
Binary: Built with gc go1.16.4 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0724 09:59:20.670636    8108 out.go:286] Setting OutFile to fd 84 ...
I0724 09:59:20.670636    8108 out.go:333] TERM=,COLORTERM=, which probably does not support color
I0724 09:59:20.670636    8108 out.go:299] Setting ErrFile to fd 88...
I0724 09:59:20.670636    8108 out.go:333] TERM=,COLORTERM=, which probably does not support color
W0724 09:59:20.679620    8108 root.go:291] Error reading config file at C:\Users\heman\.minikube\config\config.json: open C:\Users\heman\.minikube\config\config.json: The system cannot find the file specified.
I0724 09:59:20.680653    8108 out.go:293] Setting JSON to false
I0724 09:59:20.684927    8108 start.go:111] hostinfo: {"hostname":"LAPTOP-G373LAE7","uptime":894,"bootTime":1627083866,"procs":264,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.19042 Build 19042","kernelVersion":"10.0.19042 Build 19042","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"b2a2741d-c6df-4d11-9448-f90a2f0dd1bb"}
W0724 09:59:20.685074    8108 start.go:119] gopshost.Virtualization returned error: not implemented yet
I0724 09:59:20.721712    8108 out.go:165] * minikube v1.22.0 on Microsoft Windows 10 Pro 10.0.19042 Build 19042
I0724 09:59:20.722401    8108 notify.go:169] Checking for updates...
I0724 09:59:20.724309    8108 driver.go:335] Setting default libvirt URI to qemu:///system
I0724 09:59:22.353717    8108 out.go:165] * Using the hyperv driver based on existing profile
I0724 09:59:22.355068    8108 start.go:278] selected driver: hyperv
I0724 09:59:22.355068    8108 start.go:751] validating driver "hyperv" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.21.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.21.2 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false}
I0724 09:59:22.355209    8108 start.go:762] status for hyperv: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0724 09:59:22.441437    8108 cni.go:93] Creating CNI manager for ""
I0724 09:59:22.441437    8108 cni.go:167] CNI unnecessary in this configuration, recommending no CNI
I0724 09:59:22.441437    8108 start_flags.go:275] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.22.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.21.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.21.2 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false}
I0724 09:59:22.442097    8108 iso.go:123] acquiring lock: {Name:mka22b52a1d31f579c6c3d336d0bea147d0537fc Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0724 09:59:22.446105    8108 out.go:165] * Starting control plane node minikube in cluster minikube
I0724 09:59:22.446375    8108 preload.go:134] Checking if preload exists for k8s version v1.21.2 and runtime docker
I0724 09:59:22.446375    8108 preload.go:150] Found local preload: C:\Users\heman\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v11-v1.21.2-docker-overlay2-amd64.tar.lz4
I0724 09:59:22.447444    8108 cache.go:56] Caching tarball of preloaded images
I0724 09:59:22.448427    8108 preload.go:174] Found C:\Users\heman\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v11-v1.21.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0724 09:59:22.448427    8108 cache.go:59] Finished verifying existence of preloaded tar for  v1.21.2 on docker
I0724 09:59:22.449424    8108 profile.go:148] Saving config to C:\Users\heman\.minikube\profiles\minikube\config.json ...
I0724 09:59:22.453944    8108 cache.go:205] Successfully downloaded all kic artifacts
I0724 09:59:22.455004    8108 start.go:313] acquiring machines lock for minikube: {Name:mk89f5ac72f57cabc838394b2a5da4e0c250bfc6 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0724 09:59:22.455004    8108 start.go:317] acquired machines lock for "minikube" in 0s
I0724 09:59:22.456249    8108 start.go:93] Skipping create...Using existing machine configuration
I0724 09:59:22.456249    8108 fix.go:55] fixHost starting: 
I0724 09:59:22.457262    8108 main.go:130] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0724 09:59:22.947683    8108 main.go:130] libmachine: [stdout =====>] : Running

I0724 09:59:22.947733    8108 main.go:130] libmachine: [stderr =====>] : 
I0724 09:59:22.947733    8108 fix.go:108] recreateIfNeeded on minikube: state=Running err=<nil>
W0724 09:59:22.947733    8108 fix.go:134] unexpected machine state, will restart: <nil>
I0724 09:59:22.984991    8108 out.go:165] * Updating the running hyperv "minikube" VM ...
I0724 09:59:22.985723    8108 machine.go:88] provisioning docker machine ...
I0724 09:59:22.985723    8108 buildroot.go:166] provisioning hostname "minikube"
I0724 09:59:22.985723    8108 main.go:130] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0724 09:59:23.456184    8108 main.go:130] libmachine: [stdout =====>] : Running

I0724 09:59:23.456184    8108 main.go:130] libmachine: [stderr =====>] : 
I0724 09:59:23.456402    8108 main.go:130] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0724 09:59:24.013584    8108 main.go:130] libmachine: [stdout =====>] : 
I0724 09:59:24.013584    8108 main.go:130] libmachine: [stderr =====>] : 
I0724 09:59:24.013584    8108 machine.go:91] provisioned docker machine in 1.027861s
I0724 09:59:24.013792    8108 fix.go:57] fixHost completed within 1.5575436s
I0724 09:59:24.013792    8108 start.go:80] releasing machines lock for "minikube", held for 1.5587887s
W0724 09:59:24.013887    8108 start.go:523] error starting host: provision: IP not found
W0724 09:59:24.013887    8108 out.go:230] ! StartHost failed, but will try again: provision: IP not found
I0724 09:59:24.013887    8108 start.go:538] Will try again in 5 seconds ...
I0724 09:59:29.029522    8108 start.go:313] acquiring machines lock for minikube: {Name:mk89f5ac72f57cabc838394b2a5da4e0c250bfc6 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0724 09:59:29.030317    8108 start.go:317] acquired machines lock for "minikube" in 795.3µs
I0724 09:59:29.030595    8108 start.go:93] Skipping create...Using existing machine configuration
I0724 09:59:29.030622    8108 fix.go:55] fixHost starting: 
I0724 09:59:29.031201    8108 main.go:130] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0724 09:59:29.539384    8108 main.go:130] libmachine: [stdout =====>] : Running

I0724 09:59:29.539384    8108 main.go:130] libmachine: [stderr =====>] : 
I0724 09:59:29.539384    8108 fix.go:108] recreateIfNeeded on minikube: state=Running err=<nil>
W0724 09:59:29.539384    8108 fix.go:134] unexpected machine state, will restart: <nil>
I0724 09:59:29.577219    8108 out.go:165] * Updating the running hyperv "minikube" VM ...
I0724 09:59:29.577700    8108 machine.go:88] provisioning docker machine ...
I0724 09:59:29.577700    8108 buildroot.go:166] provisioning hostname "minikube"
I0724 09:59:29.578066    8108 main.go:130] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0724 09:59:30.084469    8108 main.go:130] libmachine: [stdout =====>] : Running

I0724 09:59:30.084469    8108 main.go:130] libmachine: [stderr =====>] : 
I0724 09:59:30.084469    8108 main.go:130] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0724 09:59:30.654810    8108 main.go:130] libmachine: [stdout =====>] : 
I0724 09:59:30.654967    8108 main.go:130] libmachine: [stderr =====>] : 
I0724 09:59:30.654967    8108 machine.go:91] provisioned docker machine in 1.0772671s
I0724 09:59:30.654967    8108 fix.go:57] fixHost completed within 1.6243446s
I0724 09:59:30.654967    8108 start.go:80] releasing machines lock for "minikube", held for 1.6246495s
W0724 09:59:30.655662    8108 out.go:230] * Failed to start hyperv VM. Running "minikube delete" may fix it: provision: IP not found
I0724 09:59:30.656842    8108 out.go:165] 
W0724 09:59:30.657371    8108 out.go:230] X Exiting due to GUEST_PROVISION: Failed to start host: provision: IP not found
W0724 09:59:30.657371    8108 out.go:230] * 
W0724 09:59:30.658425    8108 out.go:230] ╭──────────────────────────────────────────────────────────────────╮
│                                                                  │
│    * If the above advice does not help, please let us know:      │
│      https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                  │
│    * Please attach the following file to the GitHub issue:       │
│    * - C:\Users\heman\.minikube\logs\lastStart.txt               │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯

**Comment by spowelljr** [comment]
Hi @HemanthAditi, thanks for reporting you issue with minikube!

Have you tried running the advice listed in the logs?
`Failed to start hyperv VM. Running "minikube delete" may fix it`

**Comment by spowelljr** [comment]
Hi @HemanthAditi, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
