### ISSUE TITLE
Minikube Error

### ISSUE THREAD

**Issue by Mukhammadamin2002** [kubernetes/minikube#12041]
**Steps to reproduce the issue:** 

1. Minikube host only running others just not working
2. 
3.

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by RA489** [comment]
@Mukhammadamin2002 Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by Mukhammadamin2002** [comment]
> @Mukhammadamin2002 Do you mind adding some additional details. Here is additional information that would be helpful:
> 
> * The exact minikube start command line used
> * The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.
> * The full output of minikube logs
> * The full output of kubectl get po -A
> 
> Thank you for sharing your experience!

Firstly, thanks for responding,

**Comment by apupier** [comment]
@Mukhammadamin2002 Can you close your issue as it is fixed please?

Sharing the exact error and the configuration changed can also help other in the future which are hitting the sam eproblem.
