### ISSUE TITLE
Can't open Minikube dashboard 

### ISSUE THREAD

**Issue by ashutosh5786** [kubernetes/minikube#12063]
**Steps to reproduce the issue:** 

minkube start --driver vmware

minikube dashboard

**Full output of `minikube logs` command:**
Log file created at: 2021/07/27 18:09:13
Running on machine: DESKTOP-R8456DV
Binary: Built with gc go1.16.4 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0727 18:09:13.572000   11716 out.go:286] Setting OutFile to fd 84 ...
I0727 18:09:13.581157   11716 out.go:299] Setting ErrFile to fd 88...
I0727 18:09:13.592166   11716 mustload.go:65] Loading cluster: minikube
I0727 18:09:13.593947   11716 main.go:130] libmachine: Found binary path at C:\Program Files (x86)\VMware\VMware Workstation\bin\docker-machine-driver-vmware.exe
I0727 18:09:13.593947   11716 main.go:130] libmachine: Launching plugin server for driver vmware
I0727 18:09:13.614665   11716 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:63535
I0727 18:09:13.616166   11716 main.go:130] libmachine: () Calling .GetVersion
I0727 18:09:13.616928   11716 main.go:130] libmachine: Using API Version  1
I0727 18:09:13.616928   11716 main.go:130] libmachine: () Calling .SetConfigRaw
I0727 18:09:13.617295   11716 main.go:130] libmachine: () Calling .GetMachineName
I0727 18:09:13.617518   11716 main.go:130] libmachine: (minikube) Calling .GetState
I0727 18:09:13.618266   11716 main.go:130] libmachine: (minikube) DBG | executing: C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe list
I0727 18:09:13.883212   11716 main.go:130] libmachine: (minikube) DBG | Total running VMs: 1
I0727 18:09:13.883212   11716 main.go:130] libmachine: (minikube) DBG | C:\Users\ashut\.minikube\machines\minikube\minikube.vmx
I0727 18:09:13.892916   11716 host.go:66] Checking if "minikube" exists ...
I0727 18:09:13.893844   11716 main.go:130] libmachine: Found binary path at C:\Program Files (x86)\VMware\VMware Workstation\bin\docker-machine-driver-vmware.exe
I0727 18:09:13.893844   11716 main.go:130] libmachine: Launching plugin server for driver vmware
I0727 18:09:13.914133   11716 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:63537
I0727 18:09:13.914299   11716 main.go:130] libmachine: () Calling .GetVersion
I0727 18:09:13.914887   11716 main.go:130] libmachine: Using API Version  1
I0727 18:09:13.914887   11716 main.go:130] libmachine: () Calling .SetConfigRaw
I0727 18:09:13.915800   11716 main.go:130] libmachine: () Calling .GetMachineName
I0727 18:09:13.916299   11716 main.go:130] libmachine: (minikube) Calling .DriverName
I0727 18:09:13.916299   11716 api_server.go:164] Checking apiserver status ...
I0727 18:09:13.936834   11716 ssh_runner.go:149] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0727 18:09:13.936834   11716 main.go:130] libmachine: (minikube) Calling .GetSSHHostname
I0727 18:09:13.937835   11716 main.go:130] libmachine: (minikube) DBG | executing: C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe list
I0727 18:09:14.203501   11716 main.go:130] libmachine: (minikube) DBG | Total running VMs: 1
I0727 18:09:14.203501   11716 main.go:130] libmachine: (minikube) DBG | C:\Users\ashut\.minikube\machines\minikube\minikube.vmx
I0727 18:09:14.213783   11716 main.go:130] libmachine: (minikube) DBG | MAC address in VMX: 00:0c:29:cd:ad:2c
I0727 18:09:14.213783   11716 main.go:130] libmachine: (minikube) DBG | Trying to find IP address in configuration file: C:\ProgramData\VMware\vmnetdhcp.conf
I0727 18:09:14.214285   11716 main.go:130] libmachine: (minikube) DBG | Following IPs found map[00:50:56:c0:00:01:192.168.139.1 00:50:56:c0:00:08:192.168.198.1]
I0727 18:09:14.214285   11716 main.go:130] libmachine: (minikube) DBG | Trying to find IP address in leases file: C:\ProgramData\VMware\vmnetdhcp.leases
I0727 18:09:14.214285   11716 main.go:130] libmachine: (minikube) DBG | IP found in DHCP lease table: 192.168.198.130
I0727 18:09:14.214781   11716 main.go:130] libmachine: (minikube) Calling .GetSSHPort
I0727 18:09:14.214781   11716 main.go:130] libmachine: (minikube) Calling .GetSSHKeyPath
I0727 18:09:14.214781   11716 main.go:130] libmachine: (minikube) Calling .GetSSHUsername
I0727 18:09:14.215282   11716 sshutil.go:53] new ssh client: &{IP:192.168.198.130 Port:22 SSHKeyPath:C:\Users\ashut\.minikube\machines\minikube\id_rsa Username:docker}
I0727 18:09:14.339217   11716 ssh_runner.go:149] Run: sudo egrep ^[0-9]+:freezer: /proc/6337/cgroup
I0727 18:09:14.345194   11716 api_server.go:180] apiserver freezer: "9:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod7cef2f3f019cac995036a9bf86ab9525.slice/docker-f711121d4e6b5ac235ceba4e656ceaba9791be21db674cc2d2a91ed2ac6d8cd4.scope"
I0727 18:09:14.365708   11716 ssh_runner.go:149] Run: sudo cat /sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod7cef2f3f019cac995036a9bf86ab9525.slice/docker-f711121d4e6b5ac235ceba4e656ceaba9791be21db674cc2d2a91ed2ac6d8cd4.scope/freezer.state
I0727 18:09:14.372684   11716 api_server.go:202] freezer state: "THAWED"
I0727 18:09:14.372684   11716 api_server.go:239] Checking apiserver healthz at https://192.168.198.130:8443/healthz ...
I0727 18:09:14.378175   11716 api_server.go:265] https://192.168.198.130:8443/healthz returned 200:
ok
W0727 18:09:14.378674   11716 out.go:230] 🤔  Verifying dashboard health ...
I0727 18:09:14.398707   11716 service.go:214] Found service: &Service{ObjectMeta:{kubernetes-dashboard  kubernetes-dashboard  c9cacc8a-881a-404f-8ddc-7ff8fb61bfdf 634 0 2021-07-27 18:08:41 +0530 IST <nil> <nil> map[addonmanager.kubernetes.io/mode:Reconcile k8s-app:kubernetes-dashboard kubernetes.io/minikube-addons:dashboard] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubernetes-dashboard","kubernetes.io/minikube-addons":"dashboard"},"name":"kubernetes-dashboard","namespace":"kubernetes-dashboard"},"spec":{"ports":[{"port":80,"targetPort":9090}],"selector":{"k8s-app":"kubernetes-dashboard"}}}
] [] []  [{kubectl-client-side-apply Update v1 2021-07-27 18:08:41 +0530 IST FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:addonmanager.kubernetes.io/mode":{},"f:k8s-app":{},"f:kubernetes.io/minikube-addons":{}}},"f:spec":{"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:k8s-app":{}},"f:sessionAffinity":{},"f:type":{}}}}]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:80,TargetPort:{0 9090 },NodePort:0,AppProtocol:nil,},},Selector:map[string]string{k8s-app: kubernetes-dashboard,},ClusterIP:10.110.216.186,Type:ClusterIP,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,TopologyKeys:[],IPFamilyPolicy:*SingleStack,ClusterIPs:[10.110.216.186],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:nil,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
W0727 18:09:14.398707   11716 out.go:230] 🚀  Launching proxy ...
I0727 18:09:14.399431   11716 dashboard.go:146] Executing: kubectl.exe [kubectl.exe --context minikube proxy --port=0]
I0727 18:09:14.409677   11716 out.go:165] 
W0727 18:09:14.410175   11716 out.go:230] ❌  Exiting due to HOST_KUBECTL_PROXY: proxy start: fork/exec kubectl.exe: %1 is not a valid Win32 application.
W0727 18:09:14.410175   11716 out.go:230] 
W0727 18:09:14.412220   11716 out.go:230] [31m╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                             [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                                               [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                             [31m│[0m
[31m│[0m                                                                                                             [31m│[0m
[31m│[0m    Please attach the following file to the GitHub issue:                                                    [31m│[0m
[31m│[0m    - C:\Users\ashut\AppData\Local\Temp\minikube_dashboard_5fed37a00a23a8e8c684a572c596e3b7c65c5e16_0.log    [31m│[0m
[31m│[0m                                                                                                             [31m│[0m
[31m╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m

</details>

**Full output of failed command:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @ashutosh5786, thanks for reporting your issue with minikube! Is your machine 32-bit? `is not a valid Win32 application`

**Comment by ashutosh5786** [comment]
> Hi @ashutosh5786, thanks for reporting your issue with minikube! Is your machine 32-bit? `is not a valid Win32 application`

Nopes I have 64 bit O.S

**Comment by spowelljr** [comment]
The other possibility is that the `kubectl.exe` didn't finish downloading, if you try running:
```
C:\> kubectl.exe version
```
Do you get an error message?

**Comment by spowelljr** [comment]
Hi @ashutosh5786, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
