### ISSUE TITLE
Failed to start on Raspberry Pi OS arm(v7)

### ISSUE THREAD

**Issue by kristianpaul** [kubernetes/minikube#12072]
**Steps to reproduce the issue:** 
1.  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm
2. sudo install minikube-linux-arm /usr/local/bin/minikube
3.  minikube start
```
minikube  start
😄  minikube v1.22.0 on Raspbian 10.10 (arm)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0729 03:55:06.239878    2022 cache.go:200] Error downloading kic artifacts:  failed to download kic base image or any fallback image
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79' locally
sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79: Pulling from k8s-minikube/kicbase
docker: no matching manifest for unknown in the manifest list entries.
See 'docker run --help'.

```

<details>
pi@rpi1:~ $ minikube start
😄  minikube v1.22.0 on Raspbian 10.10 (arm)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0729 03:57:22.918515    2692 cache.go:200] Error downloading kic artifacts:  failed to download kic base image or any fallback image
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79' locally
sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79: Pulling from k8s-minikube/kicbase
docker: no matching manifest for unknown in the manifest list entries.
See 'docker run --help'.

</details>

[lastStart.txt](https://github.com/kubernetes/minikube/files/6897607/lastStart.txt)

**Comment by medyagh** [comment]
I am curious can you pull the image manually?


docker pull gcr.io/k8s-minikube/kicbase:v0.0.25

**Comment by afbjorklund** [comment]
There is currently no support for arm(32), only arm64.

**Comment by afbjorklund** [comment]
There is a beta version available, of Raspberry Pi OS 64-bit

https://www.raspberrypi.org/blog/latest-raspberry-pi-os-update-may-2020/

**Comment by afbjorklund** [comment]
I made a PR to include "arm" in the kicbase arch: #12079

**Comment by spowelljr** [comment]
arm should now be available since a couple releases ago, you can view all our release artifacts here https://github.com/kubernetes/minikube/releases/tag/v1.25.2

I'm going to close this issue, but if you have any further questions feel free to reopen and respond, thanks!
