### ISSUE TITLE
`minikube version --components` docker error

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#12083]
```
% minikube version --components
...

docker:
error

...
```
MacOS: 11.5.1
Docker: 20.10.7

**Comment by afbjorklund** [comment]
I get the same results on Ubuntu, at least when running with containerd runtime (rather expected?)

`Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?`

**Comment by spowelljr** [comment]
@afbjorklund Ah, you're right, forgot that instance was containerd, but I agree we should log something else instead of error.

**Comment by afbjorklund** [comment]
You get the same results from "ctr version", when running with CRI-O. I will make a PR to use --version instead of version.

```
ctr:
error

docker:
error

```

```console
$ minikube ssh -- sudo ctr version
Client:
  Version:  1.4.6
  Revision: d71fcd7d8303cbf684402823e425e9dd2e99285d
  Go version: go1.13.15

ctr: failed to dial "/run/containerd/containerd.sock": context deadline exceeded
ssh: Process exited with status 1
```

```
$ minikube ssh -- ctr --version
ctr containerd.io 1.4.6
$ minikube ssh -- containerd --version
containerd containerd.io 1.4.6 d71fcd7d8303cbf684402823e425e9dd2e99285d
```

Once we fix the bug of installing unused container runtimes, we will start to get a lot more "command not found" instead.
