### ISSUE TITLE
Minikube fails to deploy working cluster (expired certificate)

### ISSUE THREAD

**Issue by ctron** [kubernetes/minikube#12093]
**Steps to reproduce the issue:** 

1. `minikube delete && minikube start --cpus 6 --memory 20480 --disk-size 20gb --addons ingress`
2. Wait …
3.

To me it looks like there is an expired certificate in there somewhere:

~~~
E0802 08:34:51.830701       1 authentication.go:63] "Unable to authenticate the request" err="[x509: certificate has expired or is not yet valid: current time 2021-08-02T08:34:51Z is after 2021-07-30T13:32:02Z, verifying certificate SN=2, SKID=, AKID= failed: x509: certificate has expired or is not yet valid: current time 2021-08-02T08:34:51Z is after 2021-07-30T13:32:02Z]"
~~~

**Full output of `minikube logs` command:**

> There was an error creating your Issue: body is too long (maximum is 65536 characters). 

[logs.txt](https://github.com/kubernetes/minikube/files/6915584/logs.txt)

**Comment by spowelljr** [comment]
Hi @ctron, thanks for reporting your issue with minikube!

This seems to be a duplicate of #10122, however, running `minikube delete` usually fixes the issue, which it doesn't for you.

I'm curious if you have another minikube cluster that's keeping the old cert around. Could you try running `minikube delete --all` to delete all clusters and see if that fixes your issue?

If that doesn't work, running `minikube delete --all --purge` which will delete your minikube home directory and you should be completely fresh at that point.

Let me know if this resolves you issue, thanks!

**Comment by ctron** [comment]
I went along and deleted some certs:

~~~
rm ~/.minikube/client.*
~~~

That did fix the issue for me. I would have expected that this is done automatically when the certificates expire.

**Comment by spowelljr** [comment]
Glad that fixed your issue! The plan to auto-resolve this has an issue (#10122), it just hasn't been implemented yet. Hopefully we can get to it soon. I'll leave the issue open incase you have any other questions, if not feel free to close this issue, thanks!

**Comment by ctron** [comment]
Thanks for letting me know. So the solution is to simply wait for #10122 :grinning:
