### ISSUE TITLE
Installing minikube virtualbox with another bridged network VM running breaks virtualbox network for all VMs

### ISSUE THREAD

**Issue by awhileback** [kubernetes/minikube#12108]
**Steps to reproduce the issue:** 

1. download minikube deb package
2. start another VM (not minikube) with a bridged network interface in virtualbox on the host OS
3. install minikube with virtualbox driver on the host OS

**Full output of `minikube logs` command:**
<details>

N/A

</details>

**Full output of failed command:**
<details>

N/A

</details>

Doing the above will cause the minikube installer to redirect the host's network through the bridged VM.

Additionally, uninstalling the minikube package with apt --purge seemed to break DHCP for the entire VirtualBox installation (all other VMs).

Suggests that the minikube installer is mis-identifying which interface is the host's interface when setting itself up and messing with the VirtualBox core networking config.

Furthermore, there have been 3-4 years worth of requests to provide a VirtualBox image that can be configured to work on a bridged network, which to date has not been addressed.  

https://github.com/kubernetes/minikube/issues/1471
https://github.com/kubernetes/minikube/issues/10549
https://github.com/kubernetes/minikube/issues/6775

**Comment by awhileback** [comment]
![image](https://user-images.githubusercontent.com/84097090/128082039-0d68dd2a-2fc4-472e-974f-2a14f5c97a0a.png)

I didn't make the above setting, yet there it is.

**Comment by awhileback** [comment]
![image](https://user-images.githubusercontent.com/84097090/128082905-3867fddd-017f-485d-9929-4c5a0ef47702.png)

![image](https://user-images.githubusercontent.com/84097090/128082948-1cf6a02c-0839-40ca-9a51-b4a2112d6c29.png)

The only thing that has happened to this (previously working) VirtualBox installation in the past hour has been to install, then uninstall, minikube.

**Comment by awhileback** [comment]
It seems an `apt reinstall virtualbox` and/or `dpkg-reconfigure virtualbox` (I did both) restores network connectivity to all of the other VMs that the minikube install broke. There was nothing else apparently wrong with either the host or the Virtualbox network configuration, as shown in the screenshots above, so I don't know where else I might've looked to see where the damage was done.

**Comment by medyagh** [comment]
@awhileback thanks for sharing your experience, virtualbox is our least supported driver I suggest using KVM or docker driver on linux.

however minikube has a few options for virtualbox driver

```
      --host-only-cidr='192.168.99.1/24': The CIDR to be used for the minikube VM (virtualbox driver only)
      --host-only-nic-type='virtio': NIC Type used for host only network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
      --nat-nic-type='virtio': NIC Type used for nat network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
```

I am curious have u already tried passing those network options to minikube start ?

**Comment by spowelljr** [comment]
Hi @awhileback, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
