### ISSUE TITLE
Netlify fails on many PRs

### ISSUE THREAD

**Issue by andriyDev** [kubernetes/minikube#12118]
Example: https://app.netlify.com/sites/kubernetes-sigs-minikube/deploys/6109bc0be50436000876dea6

**Comment by afbjorklund** [comment]
Back in the "tests are always red" state, which is a dangerous place to be in (people stop looking at tests)

**Comment by andriyDev** [comment]
Related: https://github.com/kubernetes/community/issues/5932

**Comment by afbjorklund** [comment]
I'm not even sure why we have the web pages in the same git repository. Especially since hugo is so... huge ?

**Comment by sftim** [comment]
kubernetes/community#5932 suggests a “turn it off and on again” kind of fix: retry the Netlify build using the “Clear cache and redeploy” option.
I recommend trying that if not already attempted.

**Comment by sftim** [comment]
I've gone ahead and clicked that. Hope nobody objects.

**Comment by medyagh** [comment]
@sftim unfortunately none of the minikube maintainers have the permission, is there a way we could get permission ?

@medyagh @shahiddev @spowelljr

**Comment by sharifelgamal** [comment]
Netlify has been far more stable lately. I'm going to go ahead and close this.
