### ISSUE TITLE
minikube start on ubuntu

### ISSUE THREAD

**Issue by tomaszkolodziej** [kubernetes/minikube#12117]
**Steps to reproduce the issue:** 

1. Type 'minikube start'
2. error. I attached a log file.
[lastStart.txt](https://github.com/kubernetes/minikube/files/6930736/lastStart.txt)

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @tomaszkolodziej, thanks for reporting you issue with minikube!

Thanks for including your log file in the issue. I took a look the file, but unfortunately the log seems incomplete.

The last line in the log is a command being run:
```
I0804 12:45:19.213214   32212 ssh_runner.go:149] Run: docker version --format {{.Server.Version}}
```

Is it possible you cut execution short via `ctl + c`?

To verify this, please run `minikube logs --file=logs.txt` and then upload the `logs.txt` file that is created to this issue, thanks!

**Comment by tomaszkolodziej** [comment]
[logs.txt](https://github.com/kubernetes/minikube/files/6986086/logs.txt)

Thx for your response. I attached full log file.

**Comment by spowelljr** [comment]
@tomaszkolodziej Thanks for attaching the log file! I can see from it you're restarting an existing instance, I'd recommend running `minikube delete --all` if you already haven't to clear out the existing virtualbox VM and then try starting minikube again.

**Comment by tomaszkolodziej** [comment]
Thx, delete helps :)

**Comment by spowelljr** [comment]
Glad that worked!
