### ISSUE TITLE
Add `minikube unpause` next to `minikube pause` in documentation

### ISSUE THREAD

**Issue by billgale** [kubernetes/minikube#12130]
Under Manage Cluster at [minikube start](https://minikube.sigs.k8s.io/docs/start/) it would be nice to reference **minikube unpause** in conjunction with **minikube pause**.

**Comment by spowelljr** [comment]
@billgale Thanks for bringing that up, that's a valid concern, I'll fix that right now.

**Comment by billgale** [comment]
@spowelljr Beautiful doc is now even more beautiful!   Tysm for the quick turnaround.
