### ISSUE TITLE
Fix `TestAddons/parallel/HelmTiller` failing to pull the image

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#12145]
**deploy/addons/helm-tiller**

TestAddons/parallel/HelmTiller 

`gcr.io/kubernetes-helm/tiller:v2.16.12`

`Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication`

Should update to the End-Of-Life image:

```console
$ docker pull ghcr.io/helm/tiller:v2.17.0 
v2.17.0: Pulling from helm/tiller
Digest: sha256:4c43eb385032945cad047d2350e4945d913b90b3ab43ee61cecb32a495c6df0f
Status: Image is up to date for ghcr.io/helm/tiller:v2.17.0
ghcr.io/helm/tiller:v2.17.0
```

https://github.com/helm/helm/releases/tag/v2.17.0

> Helm v2.17.0 is a feature release of Helm v2. The focus of this release is the End of Life for Helm v2 support and the deprecation of the stable and incubator Helm chart repositories. The chart repositories are moving to a new location that will serve as a long term archive.

**Comment by medyagh** [comment]
Thanks for noting this

**Comment by sharifelgamal** [comment]
so we have updated our addons to pull ghcr.io/helm/tiller:v2.16.12 so that things don't totally fail, but i agree we should update the image to v2.17.0, which should be as easy as changing https://github.com/kubernetes/minikube/blob/master/pkg/minikube/assets/addons.go#L470 to be the correct image.
