### ISSUE TITLE
Untagged images built show up as "none" in the image list

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#12157]
When not tagging the images, the `minikube image list` format is not so great:

```
docker.io/library/<none>:<none>
docker.io/library/busybox:latest
```

The `crictl images` is more usable and less weird, for this particular case.

```
IMAGE                                     TAG                 IMAGE ID            SIZE
<none>                                    <none>              f873937d21951       1.24MB
busybox                                   latest              69593048aa3ac       1.24MB
```

The "docker.io/library" prefix is a bug, it should have been `<none>:<none>`

i.e. a bug in the Docker output handling, it shows up OK in the CRI-O output

----

This is the result of the build command:

`Successfully built f873937d2195`

Maybe we should only show the ID ?

`sha256:f873937d2195159c3eca110594d7571ea8742f56d196d4990c819016bc3465d2`

Same format as `crictl images --quiet`.

For those images without any tags.

**Comment by yxxhero** [comment]
@afbjorklund What's your cri?
