### ISSUE TITLE
Not Able to start Minikube with Docker driver

### ISSUE THREAD

**Issue by SaurabhGh-learn** [kubernetes/minikube#12158]
Minikube failed to start with docker driver, attching last start file, please help.
[lastStart.txt](https://github.com/kubernetes/minikube/files/6949653/lastStart.txt)

**Comment by sharifelgamal** [comment]
so it looks like starting the minikube docker container failed in a pretty spectacular way:
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: signal: segmentation fault (core dumped), stdout: , stderr:: unknown.
```

Is this error reproducible? Have you tried `minikube delete` and `minikube start`?

**Comment by sharifelgamal** [comment]
Hey @SaurabhGh-learn, I haven't heard from you in awhile. If you try my suggestion above and still have issues, feel free to reopen this issue with more details.
