### ISSUE TITLE
Localkube in Docker generates incorrect certs

### ISSUE THREAD

**Issue by Calpicow** [kubernetes/minikube#1215]
```E0303 01:37:51.087654       1 reflector.go:199] pkg/dns/dns.go:145: Failed to list *api.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: x509: certificate is valid for 10.0.0.0, 127.0.0.1, 192.168.65.2, 172.18.0.1, 172.17.0.1, 172.19.0.1, 172.20.0.1, ::1, fe80::dc09:8c42:48f3:716d, fe80::42:1cff:fede:90e, not 10.0.0.1```

**Comment by r2d4** [comment]
@Calpicow what minikube version are you running?

**Comment by Calpicow** [comment]
Using commit 0c616a6b42b28a1aab8397f5a9061f8ebbd9f3d9, which is fairly recent

**Comment by Calpicow** [comment]
Problem lies on https://github.com/kubernetes/minikube/blob/master/pkg/localkube/localkube.go#L183. It should be getting the first IP within the CIDR, but instead returns the CIDR IP (10.0.0.0 instead of 10.0.0.1).

**Comment by r2d4** [comment]
Are you sure thats the issue?  That code hasn't changed in 10 months.  https://github.com/kubernetes/minikube/blame/master/pkg/localkube/localkube.go#L183

Can you try deleting and recreating the minikube VM?

**Comment by Calpicow** [comment]
Keep in mind that I'm running localkube in Docker. From a cursory look, it appears that the minikube script is doing it's own thing (at https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cluster/cluster.go#L248).

**Comment by r2d4** [comment]
Ah - sorry I didn't read the title correctly.  I'll tag it appropriately.  I wonder how this is working with localkube inside the VM

**Comment by aaron-prindle** [comment]
@Calpicow Docker support is experimental right now.  We will happily take PRs to improve the experience here and we are currently working on it.

**Comment by Calpicow** [comment]
@aaron-prindle Of course. From what I've seen, Localkube in Docker seems to work pretty well aside from this issue and loopback. It's been really valuable so far. I'll file a PR soon with updated instructions on running it.
