### ISSUE TITLE
Storage provisioner broken for multinode mode

### ISSUE THREAD

**Issue by R-omk** [kubernetes/minikube#12165]
It seems that the hostpath provisioner is completely unsuitable for multinode installations.

It must create and prepare directories on the exact host on which a pv is requested. In addition, it must add nodeaffinity for every hostpath pv exactly the same as it happens at https://github.com/rancher/local-path-provisioner

**Steps to reproduce the issue:** 

1. minikube create -n 3
2. install any statefulset that requests pv and has pod anti affinity rule 

<details>

minikube version: v1.22.0
storage-provisioner:       image: 'gcr.io/k8s-minikube/storage-provisioner:v5'
</details>

**Comment by afbjorklund** [comment]
> It seems that the hostpath provisioner is completely unsuitable for multinode installations.

I think this is a known limitation. Possibly somewhat undocumented, but not surprising.

**Comment by sharifelgamal** [comment]
Yeah, this is a known issue. Thank you for filing this. Help wanted!

**Comment by afbjorklund** [comment]
afaik, kind just uses the rancher local-path-provisioner (although somewhat customized) :

https://github.com/kubernetes-sigs/kind/blob/main/pkg/build/nodeimage/const_storage.go

https://github.com/rancher/local-path-provisioner

**Comment by Poweranimal** [comment]
Is there an alternative storage driver one can use for minikube that supports multi-node setups?

**Comment by R-omk** [comment]
```Makefile

install_provisioner:
  curl https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml | sed 's/\/opt\/local-path-provisioner/\/var\/opt\/local-path-provisioner/ ' | kubectl apply -f -
  kubectl patch storageclass standard -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"false"}}}'
  kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
```

**Comment by Poweranimal** [comment]
@R-omk Thanks for your quick reply.

So this installs the rancher `local-path-provisioner` into my minikube cluster.
Then one sets the `local-path-provisioner` to the default storage class.

I will install it in the upcoming days in my cluster and will let you know, if I face any troubles ;)

**Comment by Poweranimal** [comment]
@R-omk Yes, the [local-path-provisioner](https://github.com/rancher/local-path-provisioner) solved all my multi node issues.
Thanks a lot!

**Comment by klaases** [comment]
Hi @R-omk, we continue to seek help wanted for this issue.

**Comment by klaases** [comment]
Hi @imrj, it looks like @presztak has created a PR for this issue, hopefully this helps, please feel free to review https://github.com/kubernetes/minikube/pull/15062
