### ISSUE TITLE
Add possibility to share host paths 

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#12167]
After adding data volumes, it would be useful if these could be shared between multiple nodes.

Either by using Gluster in the case of virtual machines, or by using Bind-mounts for containers.

* https://docs.gluster.org/en/latest/Quick-Start-Guide/Architecture/

![replicated volume](https://docs.gluster.org/en/latest/images/New-ReplicatedVol.png)

* https://docs.docker.com/storage/bind-mounts/

![bind mount](https://docs.docker.com/storage/images/types-of-mounts-bind.png)

Everything stored on these mount paths would appear on the other nodes.

So that means that HostPath would still work, even if outside the cluster...

It also allows access to the shared paths from the (real) host, just by mounting it there.

Without having to rely on VirtualBox Shared Folders or 9p (`mount`) or what-have-you.

----

This means that it would emulate using cloud provider storage.

The alternative would be a cloud native solution, such as [Rook](https://rook.io/)/[Ceph](https://ceph.io).

Or maybe the "good ole" nfs-provisioner, running on the Control Plane: 😛

https://github.com/kubernetes-sigs/nfs-ganesha-server-and-external-provisioner

**Comment by sharifelgamal** [comment]
I'm definitely in favor of this

**Comment by yayaha** [comment]
Just trying to gain some context: What's the use case for shared host paths? My understanding is that host paths in k8s clusters are local to each host. Does minikube need to different behavior because you use host paths to emulate real volumes in k8s?

The part about being able to access from the host sounds like #11296?

**Comment by afbjorklund** [comment]
> Just trying to gain some context: What's the use case for shared host paths? My understanding is that host paths in k8s clusters are local to each host. Does minikube need to different behavior because you use host paths to emulate real volumes in k8s?

The main use case is to emulate cloud provider storage or cloud native storage, a "magic path" that is available everywhere.

It is an _alternative_ to creating kubernetes volumes. Another alternative would be running an NFS server on the host itself ?
