### ISSUE TITLE
Issue while running minikube using : minikube start --driver=docker --cpus 6 --disk-size=50g --extra-config=apiserver.authorization-role=RBAC

### ISSUE THREAD

**Issue by UmarNeo** [kubernetes/minikube#12161]
**Steps to reproduce the issue:** 

1.minikube start --driver=docker --cpus 6 --disk-size=50g --extra-config=apiserver.authorization-role=RBAC
2. minikube logs

**Full output of `minikube logs` command:**
<details>
Aug 08 19:33:14 minikube kubelet[1302]: I0808 19:33:14.264572    1302 status_manager.go:566] "Failed to get status for pod" podUID=326646a3bec1b473a8d1796fe222348c pod="kube-system/kube-apiserver-minikube" error="Get \"https://control-plane.minikube.internal:8443/api/v1/namespaces/kube-system/pods/kube-apiserver-minikube\": dial tcp 192.168.49.2:8443: connect: connection refused"
Aug 08 19:33:14 minikube kubelet[1302]: E0808 19:33:14.264863    1302 pod_workers.go:190] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"kube-apiserver\" with CrashLoopBackOff: \"back-off 10s restarting failed container=kube-apiserver pod=kube-apiserver-minikube_kube-system(326646a3bec1b473a8d1796fe222348c)\"" pod="kube-system/kube-apiserver-minikube" podUID=326646a3bec1b473a8d1796fe222348c
Aug 08 19:33:14 minikube kubelet[1302]: E0808 19:33:14.362688    1302 kubelet.go:2291] "Error getting node" err="node \"minikube\" not found"
Aug 08 19:33:14 minikube kubelet[1302]: I0808 19:33:14.389827    1302 kubelet_node_status.go:71] "Attempting to register node" node="minikube"
Aug 08 19:33:14 minikube kubelet[1302]: E0808 19:33:14.390161    1302 kubelet_node_status.go:93] "Unable to register node with API server" err="Post \"https://control-plane.minikube.internal:8443/api/v1/nodes\": dial tcp 192.168.49.2:8443: connect: connection refused" node="minikube"
Aug 08 19:33:14 minikube kubelet[1302]: E0808 19:33:14.463551    1302 kubelet.go:2291] "Error getting node" err="node \"minikube\" not found"
Aug 08 19:33:14 minikube kubelet[1302]: E0808 19:33:14.563941    1302 kubelet.go:2291] "Error getting node" err="node \"minikube\" not found"
Aug 08 19:33:14 minikube kubelet[1302]: E0808 19:33:14.664301    1302 kubelet.go:2291] "Error getting node" err="node \"minikube\" not found"
Aug 08 19:33:14 minikube kubelet[1302]: E0808 19:33:14.764714    1302 kubelet.go:2291] "Error getting node" err="node \"minikube\" not found"

.
.
.
KERNEL_VERSION: 5.4.0-1035-aws
DOCKER_VERSION: 20.10.7
DOCKER_GRAPH_DRIVER: overlay2
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: enabled
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

	Unfortunately, an error has occurred:
		timed out waiting for the condition

	This error is likely caused by:
		- The kubelet is not running
		- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

	If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
		- 'systemctl status kubelet'
		- 'journalctl -xeu kubelet'

	Additionally, a control plane component may have crashed or exited when started by the container runtime.
	To troubleshoot, list all containers using your preferred container runtimes CLI.

	Here is one example how you may list all Kubernetes containers running in docker:
		- 'docker ps -a | grep kube | grep -v pause'
		Once you have found the failing container, you can inspect its logs with:
		- 'docker logs CONTAINERID'

stderr:
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/5.4.0-1035-aws\n", err: exit status 1
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

💡  Suggestion: Check output of 'journalctl -xeu kubelet', try passing --extra-config=kubelet.cgroup-driver=systemd to minikube start
🍿  Related issue: https://github.com/kubernetes/minikube/issues/4172

</details>

**Full output of failed command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Did you try passing in `--extra-config=kubelet.cgroup-driver=systemd` into `minikube start` as suggested?

**Comment by sharifelgamal** [comment]
Hey @UmarNeo – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

**Comment by Apocaly-pse** [comment]
https://github.com/kubernetes/minikube/issues/14477#issuecomment-1176188284 this issue helped me.
