### ISSUE TITLE
Unable to use userspace proxy instead of iptables proxy

### ISSUE THREAD

**Issue by eden** [kubernetes/minikube#1217]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Minikube version** (use `minikube version`): 0.17.1

**Environment**:
- **OS**: macOS 10.12.3
- **VM Driver**: xhyve
- **ISO version**: v1.0.7

**What happened**:

Tried to set proxy mode by passing `--extra-config=proxy.Mode=userspace` to `minikube start` but saw that iptables proxier was still being used.

**What you expected to happen**:

The userspace proxier was used instead of iptables proxier

**How to reproduce it** (as minimally and precisely as possible):

    minikube start --extra-config=proxy.Mode=userspace
    minikube ssh -- journalctl -u localkube

You'll see `Unable to set Mode to userspace. Error: Unable to set type ProxyMode`. Also you see the line `Using iptables Proxier`.

**Comment by r2d4** [comment]
This is fixed with your PR @eden? If not feel free to reopen
