### ISSUE TITLE
Allow swap size to be configured

### ISSUE THREAD

**Issue by gjcarneiro** [kubernetes/minikube#1219]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Minikube version** (use `minikube version`): v0.16.0

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 16.10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v1.0.6.iso
- **Install tools**:
- **Others**:

**What happened**:

Minikube creates a VM with 1GB swap.

**What you expected to happen**:

I want to disable swap, or at least control its size.  There should be a `--swap-size` option, like there is  `--memory` and `--disk-size`.

**How to reproduce it** (as minimally and precisely as possible):
Just create a VM with minikube

**Anything else do we need to know**:

Note: the reason why I want swap disabled is that my hard drive is not SSD, and I often run things in minikube that don't fit the system.  If that is the case, I would rather have random processes killed than thrash the swap hard disk.  Swapping inside the VM severely degrades the performance of my desktop due to spinning hard disks being slow.  My whole desktop becomes unresponsive, while I think one of the goals of using a VM is so  that any damage done is (mostly) contained inside the VM.

**Comment by aaron-prindle** [comment]
This can be configured by modifying this:
https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/automount/minikube-automount#L30
You can make your own swap using this method and changing the parameters.  This doesn't make sense to make configurable in minikube as it is in image parameter and not a minikube parameter.

**Comment by aaron-prindle** [comment]
Were you able to configure this manually?  This is not an option we can easily configure with our current code as it is in a image parameter and not a minikube parameter.

**Comment by aaron-prindle** [comment]
Closing.  This is not something we plan on making changeable as it is an iso option and not a driver option. 
 Re-open if you are having issues modifying the swap.
