### ISSUE TITLE
Run CPU benchmark daily via GitHub Actions

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#12238]
We have the ability to run CPU benchmarks via `make cpu-benchmark-idle` & `make cpu-benchmark-autopause` which creates a chart such as https://minikube.sigs.k8s.io/docs/benchmarks/cpuusage/.

Two problems with this:
1. This command has to be run manually, and then manually commit and create a PR
2. This command only shows the latest run, it would be good to see the CPU usage over time

So we should create a GCP bucket to store the run results, and then make a script that takes in past results and the results from the day and put them all together to make a chart like this https://minikube.sigs.k8s.io/docs/benchmarks/timetok8s/daily_benchmark/ and then push this chart and data to the bucket.

And then run this script should automatically run daily via a GitHub Action so this can be as handsfree as possible.

**Comment by afbjorklund** [comment]
@spowelljr : another more severe problem is that these nested virtualization benchmarks doesn't seem to match reality ?

![virtualbox](https://user-images.githubusercontent.com/10364051/129199662-fffa4832-558a-453c-a439-659beeeb9efa.png)

So I think we need to run the benchmarks on a _real_ server, or maybe focus on the docker driver results (not vbox vs kvm)

**Comment by spowelljr** [comment]
@afbjorklund That's a fair point, we could run these tests on an Equinix Metal machine so there's no nested virtualization.

**Comment by afbjorklund** [comment]
As long as you compare the trends of one test, I guess it still serves the purpose ? But better pick the Docker driver then
