### ISSUE TITLE
Unable to connect to the server: dial tcp <IP>: i/o timeout

### ISSUE THREAD

**Issue by electricsrini** [kubernetes/minikube#1224]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug

**Minikube version** (use `minikube version`): Tried with both v0.17.1 and v0.16.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac OS Sierra 10.12.3
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "virtualbox"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): Boot2DockerURL": "file:///Users/srinkri2/.minikube/cache/iso/minikube-v1.0.6.iso
- **Install tools**: None
- **Others**:

**What happened**:

$ VBoxManage --version
5.1.14r112924
$ minikube status
minikubeVM: Running
localkube: Running

$ kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080
Unable to connect to the server: dial tcp 192.168.99.102:8443: i/o timeout

**What you expected to happen**:
Deployment should have proceeded and created.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by r2d4** [comment]
Can you provide the output of `minikube ssh systemctl status localkube`?

**Comment by peterlozano** [comment]
I have the same problem:

Docker for mac works correctly, but Minikube docker host doesn't seem to be able to pull images.

OS: macos Sierra 10.12.2 (16C67)
Driver: xhyve
ISO: minikube-v1.0.7.iso

```
10:35:11 ~$ minikube version
minikube version: v0.17.1
10:35:18 ~$ minikube start --vm-driver=xhyve
Starting local Kubernetes cluster...
Starting VM...
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
10:36:00 ~$ minikube status
minikubeVM: Running
localkube: Running
10:38:06 ~$ kubectl cluster-info
Kubernetes master is running at https://192.168.64.6:8443

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
10:38:22 ~$ echo $(minikube docker-env)
export DOCKER_TLS_VERIFY="1" export DOCKER_HOST="tcp://192.168.64.6:2376" export DOCKER_CERT_PATH="/Users/pedro/.minikube/certs" export DOCKER_API_VERSION="1.23" # Run this command to configure your shell: # eval $(minikube docker-env)
10:38:42 ~$ eval $(minikube docker-env)
10:38:49 ~$ doc
docker                         docker-credential-osxkeychain  docker-machine-driver-xhyve
docker-compose                 docker-machine
10:38:49 ~$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Swarm:
 NodeID:
 Is Manager: false
 Node Address:
Init Binary:
containerd version:
runc version:
init version:
Kernel Version: 4.7.2
Operating System: Buildroot 2016.08
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: minikube
ID: KQ56:O562:XOCU:ZFCF:RZNZ:Z4RA:FGBF:GTEK:GGJQ:SKWQ:NY3Z:TFU3
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=xhyve
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
10:38:56 ~$ docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
14476b82a347        bridge              bridge              local
30d8f0cee9d1        host                host                local
3935c51c0ad6        none                null                local
10:39:06 ~$ docker pull node:6.9.2
Pulling repository docker.io/library/node
Network timed out while trying to connect to https://index.docker.io/v1/repositories/library/node/images. You may want to check your internet connection or if you are behind a proxy.
10:39:37 ~$ minikube ssh systemctl status localkube
● localkube.service - Localkube
   Loaded: loaded (/lib/systemd/system/localkube.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-03-05 09:36:00 UTC; 3min 46s ago
     Docs: https://github.com/kubernetes/minikube/tree/master/pkg/localkube
 Main PID: 3097 (localkube)
    Tasks: 16 (limit: 4915)
   Memory: 139.0M
      CPU: 22.263s
   CGroup: /system.slice/localkube.service
           ├─3097 /usr/local/bin/localkube --generate-certs=false --logtostderr=true --enable-dns=false --node-ip=192.168.64.6 --apiserver-name=minikubeCA
           └─3182 journalctl -k -f

Mar 05 09:38:05 minikube localkube[3097]: E0305 09:38:05.487344    3097 docker_manager.go:2183] Failed to create pod infra container: ErrImagePull; Skipping pod "kube-addon-manager-minikube_kube-system(9b29121baa99a09de533b255cb6c9ea7)": image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 192.168.64.1:53: read udp 192.168.64.6:51243->192.168.64.1:53: i/o timeout)
Mar 05 09:38:05 minikube localkube[3097]: E0305 09:38:05.487665    3097 pod_workers.go:184] Error syncing pod 9b29121baa99a09de533b255cb6c9ea7, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 192.168.64.1:53: read udp 192.168.64.6:51243->192.168.64.1:53: i/o timeout)"
Mar 05 09:38:06 minikube localkube[3097]: E0305 09:38:06.765909    3097 docker_manager.go:2183] Failed to create pod infra container: ImagePullBackOff; Skipping pod "kube-addon-manager-minikube_kube-system(9b29121baa99a09de533b255cb6c9ea7)": Back-off pulling image "gcr.io/google_containers/pause-amd64:3.0"
Mar 05 09:38:06 minikube localkube[3097]: E0305 09:38:06.766023    3097 pod_workers.go:184] Error syncing pod 9b29121baa99a09de533b255cb6c9ea7, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/pause-amd64:3.0\""
Mar 05 09:39:05 minikube localkube[3097]: E0305 09:39:05.515044    3097 docker_manager.go:2183] Failed to create pod infra container: ErrImagePull; Skipping pod "hello-minikube-3015430129-nxlgt_default(bfd41171-017c-11e7-9801-a63c1b79fdfb)": image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 192.168.64.1:53: read udp 192.168.64.6:56314->192.168.64.1:53: i/o timeout)
Mar 05 09:39:05 minikube localkube[3097]: E0305 09:39:05.515636    3097 pod_workers.go:184] Error syncing pod bfd41171-017c-11e7-9801-a63c1b79fdfb, skipping: failed to "StartContainer" for "POD" with ErrImagePull: "image pull failed for gcr.io/google_containers/pause-amd64:3.0, this may be because there are no credentials on this request.  details: (Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp: lookup gcr.io on 192.168.64.1:53: read udp 192.168.64.6:56314->192.168.64.1:53: i/o timeout)"
Mar 05 09:39:20 minikube localkube[3097]: I0305 09:39:20.172370    3097 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/bfd41171-017c-11e7-9801-a63c1b79fdfb-default-token-gg21h" (spec.Name: "default-token-gg21h") pod "bfd41171-017c-11e7-9801-a63c1b79fdfb" (UID: "bfd41171-017c-11e7-9801-a63c1b79fdfb").
Mar 05 09:39:20 minikube localkube[3097]: E0305 09:39:20.456525    3097 docker_manager.go:2183] Failed to create pod infra container: ImagePullBackOff; Skipping pod "hello-minikube-3015430129-nxlgt_default(bfd41171-017c-11e7-9801-a63c1b79fdfb)": Back-off pulling image "gcr.io/google_containers/pause-amd64:3.0"
Mar 05 09:39:20 minikube localkube[3097]: E0305 09:39:20.456603    3097 pod_workers.go:184] Error syncing pod bfd41171-017c-11e7-9801-a63c1b79fdfb, skipping: failed to "StartContainer" for "POD" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/pause-amd64:3.0\""
Mar 05 09:39:35 minikube localkube[3097]: I0305 09:39:35.160486    3097 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/bfd41171-017c-11e7-9801-a63c1b79fdfb-default-token-gg21h" (spec.Name: "default-token-gg21h") pod "bfd41171-017c-11e7-9801-a63c1b79fdfb" (UID: "bfd41171-017c-11e7-9801-a63c1b79fdfb").

```

**Comment by electricsrini** [comment]
Hi Matt,

I deleted and started again today. Interestingly I am able to proceed now. The only difference, I am on different WiFi network (was at a meetup yesterday and connecting from home today). Not sure if the output still helps, but here is the result for the query :

● localkube.service - Localkube
   Loaded: loaded (/lib/systemd/system/localkube.service; enabled; vendor preset: enabled)
   Active: active (running) since Sun 2017-03-05 07:04:55 UTC; 4h 6min ago
     Docs: https://github.com/kubernetes/minikube/tree/master/pkg/localkube
 Main PID: 3298 (localkube)
    Tasks: 22 (limit: 4915)
   Memory: 212.2M
      CPU: 40min 30.642s
   CGroup: /system.slice/localkube.service
           ├─3298 /usr/local/bin/localkube --generate-certs=false --logtostderr=true --enable-dns=false --node-ip=192.168.99.103
           └─3383 journalctl -k -f

Mar 05 11:08:59 minikube localkube[3298]: W0305 11:08:59.664551    3298 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [15340/15202]) [16339]
Mar 05 11:09:35 minikube localkube[3298]: I0305 11:09:35.472685    3298 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/18700210-0172-11e7-8f1a-080027430daf-default-token-mwkfx" (spec.Name: "default-token-mwkfx") pod "18700210-0172-11e7-8f1a-080027430daf" (UID: "18700210-0172-11e7-8f1a-080027430daf").
Mar 05 11:09:50 minikube localkube[3298]: I0305 11:09:50.437810    3298 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/1888c379-0172-11e7-8f1a-080027430daf-default-token-mwkfx" (spec.Name: "default-token-mwkfx") pod "1888c379-0172-11e7-8f1a-080027430daf" (UID: "1888c379-0172-11e7-8f1a-080027430daf").
Mar 05 11:10:53 minikube localkube[3298]: W0305 11:10:53.573255    3298 reflector.go:319] pkg/storage/cacher.go:201: watch of *batch.Job ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [15466/15162]) [16465]
Mar 05 11:10:53 minikube localkube[3298]: W0305 11:10:53.573345    3298 reflector.go:319] pkg/storage/cacher.go:201: watch of *batch.CronJob ended with: 401: The event in requested index is outdated and cleared (the requested history has been cleared [15466/15162]) [16465]
Mar 05 11:10:54 minikube localkube[3298]: W0305 11:10:54.574750    3298 cacher.go:119] Terminating all watchers from cacher *batch.CronJob
Mar 05 11:10:54 minikube localkube[3298]: W0305 11:10:54.579217    3298 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: too old resource version: 15161 (16465)
Mar 05 11:10:54 minikube localkube[3298]: W0305 11:10:54.579521    3298 reflector.go:319] pkg/controller/garbagecollector/garbagecollector.go:768: watch of <nil> ended with: too old resource version: 15161 (16465)
Mar 05 11:10:56 minikube localkube[3298]: E0305 11:10:56.775453    3298 repair.go:132] the node port 30000 for service kubernetes-dashboard/kube-system is not allocated; repairing
Mar 05 11:11:02 minikube localkube[3298]: I0305 11:11:02.499925    3298 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/18700210-0172-11e7-8f1a-080027430daf-default-token-mwkfx" (spec.Name: "default-token-mwkfx") pod "18700210-0172-11e7-8f1a-080027430daf" (UID: "18700210-0172-11e7-8f1a-080027430daf").

**Comment by peterlozano** [comment]
I solved my issue by disabling macos firewall. It seems mac's firewall avoids machines created with docker-machine-driver-xhyve to have network connectivity.

I also had to manually change the nameserver in /etc/resolv.conf to 8.8.8.8 (inside the minikube vm) to get name resolution working.

Note that I don't have any of these issues using Docker for Mac normally, so they probably must have implemented some workarounds for these issues.

**Comment by norbert-yoimo** [comment]
I'm running into this too, output of `minikube ssh systemctl status localkube`:

```
● localkube.service - Localkube
   Loaded: loaded (/lib/systemd/system/localkube.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-03-06 14:09:08 UTC; 14min ago
     Docs: https://github.com/kubernetes/minikube/tree/master/pkg/localkube
 Main PID: 3271 (localkube)
    Tasks: 16 (limit: 4915)
   Memory: 141.8M
      CPU: 1min 54.669s
   CGroup: /system.slice/localkube.service
           ├─3271 /usr/local/bin/localkube --generate-certs=false --logtostderr=true --enable-dns=false --node-ip=192.168.99.100 --apiserver-name=minikubeCA
           └─3350 journalctl -k -f

Mar 06 14:19:12 minikube localkube[3271]: I0306 14:19:12.296016    3271 replication_controller.go:322] Observed updated replication controller kubernetes-dashboard. Desired pod count change: 1->1
Mar 06 14:19:12 minikube localkube[3271]: I0306 14:19:12.296150    3271 replication_controller.go:322] Observed updated replication controller kube-dns-v20. Desired pod count change: 1->1
Mar 06 14:19:17 minikube localkube[3271]: I0306 14:19:17.895294    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/8357ed5c-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "8357ed5c-0276-11e7-9885-0800272e2447" (UID: "8357ed5c-0276-11e7-9885-0800272e2447").
Mar 06 14:20:30 minikube localkube[3271]: I0306 14:20:30.883835    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/836b1214-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "836b1214-0276-11e7-9885-0800272e2447" (UID: "836b1214-0276-11e7-9885-0800272e2447").
Mar 06 14:20:47 minikube localkube[3271]: I0306 14:20:47.820727    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/8357ed5c-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "8357ed5c-0276-11e7-9885-0800272e2447" (UID: "8357ed5c-0276-11e7-9885-0800272e2447").
Mar 06 14:21:02 minikube localkube[3271]: apply entries took too long [11.765144ms for 1 entries]
Mar 06 14:21:02 minikube localkube[3271]: avoid queries with large range/delete range!
Mar 06 14:21:09 minikube localkube[3271]: E0306 14:21:09.826764    3271 repair.go:132] the node port 30000 for service kubernetes-dashboard/kube-system is not allocated; repairing
Mar 06 14:21:57 minikube localkube[3271]: I0306 14:21:57.895042    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/836b1214-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "836b1214-0276-11e7-9885-0800272e2447" (UID: "836b1214-0276-11e7-9885-0800272e2447").
Mar 06 14:21:58 minikube localkube[3271]: I0306 14:21:58.899802    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/8357ed5c-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "8357ed5c-0276-11e7-9885-0800272e2447" (UID: "8357ed5c-0276-11e7-9885-0800272e2447").
```

OS: Arch
VM Driver: virtualbox
ISO version: minikube-v1.0.7.iso
VBoxmanage --version: 5.1.14r112924
Minikube status:
```
minikubeVM: Running
localkube: Running
```

**Comment by aaron-prindle** [comment]
It seems that two people have resolved their issues.  I am closing this for now.  @norbert-yoimo please create a separate issue if you're still having trouble with this.

**Comment by migmartri** [comment]
I am running into this issue as well.

`systemd-networkd-wait-online.service` is marked as failed.

```
systemctl status systemd-networkd-wait-online.service
● systemd-networkd-wait-online.service - Wait for Network to be Configured
   Loaded: loaded (/lib/systemd/system/systemd-networkd-wait-online.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2017-04-21 15:15:52 UTC; 29min ago
     Docs: man:systemd-networkd-wait-online.service(8)
  Process: 3230 ExecStart=/lib/systemd/systemd-networkd-wait-online (code=exited, status=1/FAILURE)
 Main PID: 3230 (code=exited, status=1/FAILURE)

Apr 21 15:13:52 minikube systemd[1]: Starting Wait for Network to be Configured...
Apr 21 15:13:52 minikube systemd-networkd-wait-online[3230]: ignoring: lo
Apr 21 15:15:52 minikube systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
Apr 21 15:15:52 minikube systemd[1]: Failed to start Wait for Network to be Configured.
Apr 21 15:15:52 minikube systemd[1]: systemd-networkd-wait-online.service: Unit entered failed state.
Apr 21 15:15:52 minikube systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
```

I am running Minikube in VirtualBox 5.1.18.

**Comment by sndwch** [comment]
I had this on ubuntu zesty. I was running docker-ce on my machine - stopping the docker service allowed kubectl to connect.

**Comment by mehuman** [comment]
Was having this problem on fresh installs of both Ubuntu Zesty and Fedora 26 with Virtualbox. My solution was to run `ifconfig vboxnet0 up`

Although `ip addr show` was showing the correct ip being set the minikube was not bringing up the interface.

**Comment by weisserd** [comment]
@mehuman Worked for me as well with Ubuntu

Before `sudo ifconfig vboxnet0 up`

```
15: vboxnet0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.1/24 scope global vboxnet0
       valid_lft forever preferred_lft forever
```

and after

```
15: vboxnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.1/24 scope global vboxnet0
       valid_lft forever preferred_lft forever
    inet6 fe80::800:27ff:fe00:0/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by Ademord** [comment]
@mehuman, @weisserd  I could kiss you right now I was going a little nutty about this. This finally worked for me. Thx!

**Comment by mehuman** [comment]
A little more testing and the interface will stay up after a minikube stop, delete, and start. I have not yet tried after a machine restart.

**Comment by davidberardozzi** [comment]
@mehuman THANKS !

**Comment by amitsam92** [comment]
@mehuman 
Thanks a lot for the wonderful fix. Works for me as well .

**Comment by trickl** [comment]
@mehuman Thank you, fixed identical problem on 16.04.

**Comment by bkcsfi** [comment]
Hi, I have the same problem on ubuntu zesty, I had to also manually 'up' vboxnet0

thanks for the tip

**Comment by vishalpurohit** [comment]
@mehuman   Thank a lot. It worked fine for Ubuntu 16.04. I had recently upgraded to latest Virtualbox 5.1.24 and encountered I/O timeout issue.

**Comment by shitWang** [comment]
@mehuman Is also fixed for centos7？No one try？

**Comment by jingpengw** [comment]
unfortunately, do not work for me with Ubuntu 14.04.

**Comment by liuml07** [comment]
FWIW, I have a similar problem on macOS, and found that the VPN will make the API server `192.168.99.100` unreachable.

**Comment by jingpengw** [comment]
BTW, reconnect and authorize works for me.
`gcloud container clusters get-credentials my-cluster-name`

**Comment by elliott-beach** [comment]
> Was having this problem on fresh installs of both Ubuntu Zesty and Fedora 26 with Virtualbox. My solution was to run ifconfig vboxnet0 up

I had to restart minikube via `minikube stop && minikube start` for kubectl to connect.

**Comment by LingboTang** [comment]
@jingpengw Reconnect and authorize doesn't work for me.

**Comment by marcellodesales** [comment]
@liuml07 Same problem here... I have MAC with `OpenPulse` VPN and I installed everything connected to my office... Working fine without VPN... Sucks!

**Comment by vhosakot** [comment]
I saw the same error too when I ran `docker build -t hello-node:v1 .` in the tutorial https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/#create-a-docker-container-image on Mac OS X Sierra (`10.12.6`), Docker version `17.12.0-ce`, minikube version `v0.25.0`, xhyve version `0.2.0` and kubernetes version `v1.9.0`:

```
$ docker build -t hello-node:v1 .
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM node:6.9.2
Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.3:37095->192.168.64.1:53: read: connection refused
```

Switching to **virtualbox**  fixed this issue for me.

I stopped minikube, deleted it, started it without `--vm-driver=xhyve` (minikube uses virtualbox driver by default), and then `docker build -t hello-node:v1 .` worked fine without errors:

```
minikube stop
eval $(minikube docker-env -u)
minikube delete

minikube start (without --vm-driver=xhyve)

eval $(minikube docker-env)
docker build -t hello-node:v1 .

$ docker images | grep hello
hello-node                                    v1                  9cc51aa82a30        39 seconds ago      655MB
```

I do see the `kube-dns` pod running:

```
$ kubectl get pod --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   kube-addon-manager-minikube             1/1       Running   0          1m
kube-system   kube-dns-54cccfbdf8-vmvjm               3/3       Running   0          1m
kube-system   kubernetes-dashboard-77d8b98585-5mbcf   1/1       Running   0          1m
kube-system   storage-provisioner                     1/1       Running   0          1m
```

This issue does look like an `xhyve` issue not seen with virtualbox. My virtualbox version is `5.2.6r120293`:

```
$ VBoxManage --version
5.2.6r120293
```

**Comment by N3xtHub** [comment]
Check if you have VPN connection. In my case, after disconnect VPN, everything is working.

**Comment by jstxx** [comment]
So I deleted terraform.tfstate, did a terraform apply and it started working

**Comment by rjpruitt16** [comment]
`minikube start `worked for me.

**Comment by huynhthienthach** [comment]
> BTW, reconnect and authorize works for me.
> `gcloud container clusters get-credentials my-cluster-name`

WORKED for me. Thank you very much

**Comment by donngchao** [comment]
After I set up my /etc/hosts file correctly， I finally solved this problem in my scenario.

**Comment by Shesoff** [comment]
In my MacOS Big Sur I did that:
1. Down/Up virtual interface 
`sudo ifconfig vboxnet0 down && sudo ifconfig vboxnet0 up`
2. Check that interface is up `ping 192.168.99.1' where 192.168.99.1 is IP address your virtual interface (show in ifconfig output)
3. Enjoy

Very strange that if do only `sudo ifconfig vboxnet0 up `it not work, VMs not accessable over network (time out) and link not answer on ICMP echo requests (aka ping)
