### ISSUE TITLE
Error starting cluster message after starting minikube cluster.

### ISSUE THREAD

**Issue by laxmikantbpandhare** [kubernetes/minikube#12277]
**Steps to reproduce the issue:** 

1. minikube start
[lastStart.txt](https://github.com/kubernetes/minikube/files/6995590/lastStart.txt)

**Full output of `minikube logs` command:**
<details>

</details>

After starting minikube cluster, getting Error starting cluster.

```
💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
```

Attached text file for the same.

<img width="1792" alt="Screen Shot 2021-08-16 at 2 51 28 PM" src="https://user-images.githubusercontent.com/47066536/129633944-0eba8afe-0261-4c11-98f6-cca1f1d04df5.png">

**Comment by spowelljr** [comment]
Hi @laxmikantbpandhare, thanks for reporting your issue with minikube!

First recommendation, I'd suggest updating to the latest minikube version (v1.23.2).

After that, could you try running minikube with `minikube start --force-systemd=true` and let me know if that works, thanks!

**Comment by spowelljr** [comment]
Hi @laxmikantbpandhare, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
