### ISSUE TITLE
Allow using `minikube --cluster whatever` in place of --profile flag

### ISSUE THREAD

**Issue by andriyDev** [kubernetes/minikube#12275]
`minikube --profile` can be confusing for some users, and we have had several requests to add multi-cluster support (even though we've had it for a while). To mitigate this, we should add a `minikube --cluster` flag as an alias for profile.

**Comment by morhook** [comment]
Good idea! Thanks.

**Comment by afbjorklund** [comment]
@andriyDev : Also consider a `minikube cluster` command alias (for `minikube profile`)

**Comment by andriyDev** [comment]
@afbjorklund ah yes I didn't make that clear, that is already done! :)

**Comment by klaases** [comment]
Closing out as this was resolved previously.
