### ISSUE TITLE
error with command minikube service hello-node

### ISSUE THREAD

**Issue by VictorViana** [kubernetes/minikube#12272]
**Os comandos necessários para reproduzir o problema**:
 minikube service hello-node

**A saída completa do comando que apresentou falha**: <details>
minikube service hello-node
|-----------|------------|-------------|---------------------------|
| NAMESPACE |    NAME    | TARGET PORT |            URL            |
|-----------|------------|-------------|---------------------------|
| default   | hello-node |        8080 | http://192.168.15.4:30302 |
|-----------|------------|-------------|---------------------------|
🎉  Opening service default/hello-node in default browser...
[26347:26347:0815/232217.253396:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
[26364:26364:0815/232217.275908:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Running Firefox as root in a regular user's session is not supported.  ($HOME is /home/vviana which is owned by vviana.)
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium-browser: not found
[26401:26401:0815/232217.342655:ERROR:zygote_host_impl_linux.cc(90)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://192.168.15.4:30302'

❌  Exiting due to HOST_BROWSER: exit status 3

╭──────────────────────────────────────────────────────────────────────────────╮
│                                                                              │
│    😿  If the above advice does not help, please let us know:                │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose              │
│                                                                              │
│    Please attach the following file to the GitHub issue:                     │
│    - /tmp/minikube_service_31309052c4ecc0f40a3e3d565f6a34e3e043332e_0.log    │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
</details>

**A saída do comando `minikube logs`**:<details>
- /tmp/minikube_service_31309052c4ecc0f40a3e3d565f6a34e3e043332e_0.log 

</details>

**A versão do sistema operacional usado**:
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
Codename:	bionic

**Comment by kadern0** [comment]
Ola @VictorViana, este erro e porque minikube nao atopa nenhum browser para conectar a URL. Normalmente o Desktop Environment ja configura o navegador por defecto mais voce posse configuralo coa variable $BROWSER.

Estas a ejecutar os comandos dende umha terminal ou dende X11?

**Comment by spowelljr** [comment]
Hi @VictorViana, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

-----

Olá @VictorViana, não tivemos notícias suas. Você ainda tem esse problema?
Não há informações suficientes neste problema para torná-lo acionável e uma duração longa o suficiente já passou, então é provável que seja difícil replicar o problema.

Encerrarei este problema por enquanto, mas fique à vontade para reabri-lo quando você se sentir pronto para fornecer mais informações.
