### ISSUE TITLE
xhyve driver tries to use /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

### ISSUE THREAD

**Issue by dkoston** [kubernetes/minikube#1227]
**Minikube version** (use `minikube version`):

minikube version: v0.17.1

**Environment**:
- **OS**: macOS Sierra 10.12.3 (16D32)
- **VM Driver** : No such file
- **ISO version**: I haven't been able to create a machine
- **Install tools**: brew (for xhyve), minikube installed from repo instructions
- **Others**:

**What happened**:

Trying to create a machine with the xhyve driver attempts to use /Applications/VirtualBox.app/Contents/MacOS/VBoxManage

**What you expected to happen**:

The machine to be created using xhyve

**How to reproduce it** (as minimally and precisely as possible):
```
minikube start --vm-driver=xhyve --cpus 6 --memory 14922 -v=7
Starting local Kubernetes cluster...
Starting VM...
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
Plugin server listening at address 127.0.0.1:54373
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetMachineName
(minikube) Calling .DriverName
Running pre-create checks...
(minikube) Calling .PreCreateCheck
(minikube) DBG | ===== Docker Machine xhyve Driver Version 0.3.1 (Homebrewab0aeba) =====
(minikube) DBG |
(minikube) DBG | executing: /usr/local/bin/VBoxManage -v
(minikube) DBG | STDOUT:
(minikube) DBG | STDERR: /usr/local/bin/VBoxManage: line 2: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage: No such file or directory
(minikube) DBG | /usr/local/bin/VBoxManage: line 2: exec: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage: cannot execute: No such file or directory
(minikube) DBG |
E0306 16:59:33.169338   73441 start.go:113] Error starting host: Error creating host: Error with pre-create check: "Error detecting VBox version: exit status 126".

 Retrying.
E0306 16:59:33.172917   73441 start.go:119] Error starting host:  Error creating host: Error with pre-create check: "Error detecting VBox version: exit status 126"
```

**Anything else do we need to know**:

**Comment by dkoston** [comment]
Ah, looks like I need an executable VBoxManage to use minikube.

https://github.com/kubernetes/minikube/issues/283

Would be nice to have that in the instructions.

I didn't want to install VirtualBox so I just added a dummy /usr/local/bin/VBoxManage -v:

```
#!/bin/bash
echo '5.0.0_Ubuntur77245'
```

Seems like minikube should ignore this part of the process if VBoxManage isn't found in the path rather than dying

**Comment by r2d4** [comment]
You do not need VboxManage to use xhyve

You need to delete the VBoxManage binary if you've also deleted virtualbox.  Xhyve needs to check because of a kernel panic if an old version of virtualbox is installed.  If VboxManage is not found, xhyve continues, but if VboxManage is found and there is no Virtualbox install, it will throw an error. 

This is explained in https://github.com/kubernetes/minikube/issues/519#issuecomment-246021997

https://github.com/zchee/docker-machine-driver-xhyve/issues/134

**Comment by dkoston** [comment]
Thanks. I'll clean up the VBoxManage binary as well
