### ISSUE TITLE
Minikube start fails >minikube start --driver=hyperv

### ISSUE THREAD

**Issue by reshmahulagur** [kubernetes/minikube#12286]
**Steps to reproduce the issue:** 

1.>both minikube start and minikube start --driver=hyperv fails,  attaching logs
[lastStart.txt](https://github.com/kubernetes/minikube/files/6996982/lastStart.txt)

**Full output of `minikube logs` command:**
<details>
* minikube v1.22.0 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
E0817 09:32:37.598516   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

* hyperv "minikube" VM is missing, will recreate.
E0817 09:32:38.615198   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:32:39.446981   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:32:40.607189   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Stop-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:1
+ Hyper-V\Stop-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Stop-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.StopVM

E0817 09:32:41.765106   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:32:42.983106   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:32:43.969097   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Remove-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:1
+ Hyper-V\Remove-VM minikube -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Remove-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.RemoveVM

E0817 09:32:45.663900   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:32:46.352122   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Remove-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:1
+ Hyper-V\Remove-VM minikube -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Remove-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.RemoveVM

* Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...- E0817 09:32:49.290787   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VMSwitch : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have
been deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:69
+ ...  [Text.Encoding]::UTF8; ConvertTo-Json @(Hyper-V\Get-VMSwitch|Select  ...
+                                              ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMSwitch

! StartHost failed, but will try again: recreate: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/
E0817 09:32:57.046163   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

* hyperv "minikube" VM is missing, will recreate.
E0817 09:32:57.843905   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:32:58.571220   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:32:59.286717   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Stop-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:1
+ Hyper-V\Stop-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Stop-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.StopVM

E0817 09:33:00.009298   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:33:00.737288   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:33:01.547702   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Remove-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:1
+ Hyper-V\Remove-VM minikube -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Remove-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.RemoveVM

E0817 09:33:03.287216   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

E0817 09:33:04.080552   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Remove-VM : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have been
deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:1
+ Hyper-V\Remove-VM minikube -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Remove-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.RemoveVM

* Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...\ E0817 09:33:07.112241   25196 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VMSwitch : Hyper-V encountered an error trying to access an object on computer 'WKWIN7075014' because the object was not found. The object might have
been deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:69
+ ...  [Text.Encoding]::UTF8; ConvertTo-Json @(Hyper-V\Get-VMSwitch|Select  ...
+                                              ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMSwitch

* Failed to start hyperv VM. Running "minikube delete" may fix it: recreate: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

X Exiting due to GUEST_PROVISION: Failed to start host: recreate: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

</details>

**Full output of failed command:**
<details>

</details>

**Comment by hlesesne** [comment]
This may be a silly question, but Hyper-V has been enabled on windows, right?

**Comment by spowelljr** [comment]
This is the same error as issue #12555, I believe this error might be specific to `Windows Server 2019 Datacenter`.

**Comment by spowelljr** [comment]
Hi @reshmahulagur, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
