### ISSUE TITLE
localkube: Start up the servers in the right order to avoid possible race conditions

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#123]
proposed order: 
- setup certs if the flag is set
- kubelet, etcd
- apiserver
- controller-manager, scheduler, kube-proxy
- dns

**Comment by dlorenc** [comment]
Going to move this out of the 0.2 Release because we've fixed the existing race conditions. It still seems like a good idea to do long term, though.

**Comment by dlorenc** [comment]
Fixed with #1371
