### ISSUE TITLE
Running minikube start fails due to insufficient cpus available.  

### ISSUE THREAD

**Issue by JasonShenk** [kubernetes/minikube#12309]
**Steps to reproduce the issue:** 

minikube start --memory=16192

**Full output of `minikube logs` command:**
<details>
PS C:\code\Xjasshe> minikube start --memory=16192
* minikube v1.21.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the docker driver based on existing profile
* - Ensure your docker daemon has access to enough CPU/memory resources.

        * - Docs https://docs.docker.com/docker-for-windows/#resources

X Exiting due to RSRC_INSUFFICIENT_CORES: Requested cpu count 2 is greater than the available cpus of 1

</details>

**Full output of failed command:**
<details>
PS C:\code\Xjasshe> minikube start --memory=16192 --alsologtostderr
I0819 07:01:52.929848   27080 out.go:291] Setting OutFile to fd 84 ...
I0819 07:01:52.931848   27080 out.go:338] TERM=,COLORTERM=, which probably does not support color
I0819 07:01:52.931848   27080 out.go:304] Setting ErrFile to fd 88...
I0819 07:01:52.931848   27080 out.go:338] TERM=,COLORTERM=, which probably does not support color
I0819 07:01:52.954847   27080 out.go:298] Setting JSON to false
I0819 07:01:52.968042   27080 start.go:111] hostinfo: {"hostname":"UMEL800141","uptime":60257,"bootTime":1629310655,"procs":362,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"10.0.18363 Build 18363","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"8f8ba35b-e210-47b4-bb55-ef2045e6f2a7"}
W0819 07:01:52.968042   27080 start.go:119] gopshost.Virtualization returned error: not implemented yet
I0819 07:01:52.969610   27080 out.go:170] * minikube v1.21.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* minikube v1.21.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
I0819 07:01:52.970649   27080 driver.go:335] Setting default libvirt URI to qemu:///system
I0819 07:01:53.450781   27080 docker.go:132] docker version: linux-20.10.8
I0819 07:01:53.466376   27080 cli_runner.go:115] Run: docker system info --format "{{json .}}"
I0819 07:01:54.360374   27080 info.go:261] docker info: {ID:4LE3:EOQH:X6DT:2MFW:663E:2QX6:ZKUM:3DMY:JNGG:A72C:D26A:H2AS Containers:2 ContainersRunning:0 ContainersPaused:0 ContainersStopped:2 Images:2 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:true KernelMemoryTCP:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:40 OomKillDisable:true NGoroutines:40 SystemTime:2021-08-19 11:01:54.2753619 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:2 KernelVersion:5.10.16.3-microsoft-standard-WSL2 OperatingSystem:Docker Desktop OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:1 MemTotal:1024241664 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:docker-desktop Labels:[] ExperimentalBuild:false ServerVersion:20.10.8 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:e25210fe30a0a703442421b0f60afac609f950a3 Expected:e25210fe30a0a703442421b0f60afac609f950a3} RuncCommit:{ID:v1.0.1-0-g4144b63 Expected:v1.0.1-0-g4144b63} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default] ProductLicense: Warnings:[WARNING: No blkio throttle.read_bps_device support WARNING: No blkio throttle.write_bps_device support WARNING: No blkio throttle.read_iops_device support WARNING: No blkio throttle.write_iops_device support] ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Name:buildx Path:C:\Program Files\Docker\cli-plugins\docker-buildx.exe SchemaVersion:0.1.0 ShortDescription:Build with BuildKit Vendor:Docker Inc. Version:v0.6.1-docker] map[Name:compose Path:C:\Program Files\Docker\cli-plugins\docker-compose.exe SchemaVersion:0.1.0 ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.0.0-rc.1] map[Name:scan Path:C:\Program Files\Docker\cli-plugins\docker-scan.exe SchemaVersion:0.1.0 ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.8.0]] Warnings:<nil>}}
I0819 07:01:54.365256   27080 out.go:170] * Using the docker driver based on existing profile
* Using the docker driver based on existing profile
I0819 07:01:54.368611   27080 start.go:279] selected driver: docker
I0819 07:01:54.369257   27080 start.go:752] validating driver "docker" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.23@sha256:baf6d94b2050bcbecd98994e265cf965a4f4768978620ccf5227a6dcb75ade45 Memory:16192 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.20.7 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:192.168.49.2 Port:8443 KubernetesVersion:v1.20.7 ControlPlane:true Worker:true}] Addons:map[default-storageclass:true storage-provisioner:true] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false}
I0819 07:01:54.371961   27080 start.go:763] status for docker: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0819 07:01:54.374132   27080 out.go:170] * - Ensure your docker daemon has access to enough CPU/memory resources.
* - Ensure your docker daemon has access to enough CPU/memory resources.
I0819 07:01:54.379170   27080 out.go:170]

        I0819 07:01:54.381273   27080 out.go:170] * - Docs https://docs.docker.com/docker-for-windows/#resources
* - Docs https://docs.docker.com/docker-for-windows/#resources
I0819 07:01:54.383924   27080 out.go:170]

W0819 07:01:54.384962   27080 out.go:235] X Exiting due to RSRC_INSUFFICIENT_CORES: Requested cpu count 2 is greater than the available cpus of 1
X Exiting due to RSRC_INSUFFICIENT_CORES: Requested cpu count 2 is greater than the available cpus of 1
I0819 07:01:54.389830   27080 out.go:170]

</details>

**Comment by andriyDev** [comment]
Ensure your docker is configured to use more than 1 core (minikube needs at least 2) https://docs.docker.com/docker-for-windows/#resources. If this works, please close the issue If your machine has only a single core, you're out of luck... sorry!

**Comment by JasonShenk** [comment]
I will close it.  The problem is my docker configuration, not minikube.
