### ISSUE TITLE
Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /etc/kubernetes: mkdir /etc/kubernetes: permission denied

### ISSUE THREAD

**Issue by syedkhalandar80** [kubernetes/minikube#12307]
1. minikube start VM_DRIVER=hyperkit
2. echo $KUBECONFIG.    
/etc/kubernetes/admin.conf
3.$KUBECONFIG
bash: /etc/kubernetes/admin.conf: No such file or directory

minikube version
<details>
minikube version: v1.22.0
commit: a03fbcf166e6f74ef224d4a63be4277d017bb62e
</details>
my system details

<details>
Hardware Overview:

  Model Name:	MacBook Air
  Model Identifier:	MacBookAir7,2
  Processor Name:	Intel Core i5
  Processor Speed:	1.8 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache (per Core):	256 KB
  L3 Cache:	3 MB
  Hyper-Threading Technology:	Enabled
  Memory:	8 GB
  Boot ROM Version:	427.0.0.0.0
  SMC Version (system):	2.27f2
  Serial Number (system):	FVFVM5DDJ1WK
  Hardware UUID:	2083E226-1B2F-5977-BE8C-EE688EECCBA5
</details>

**Full output of `minikube logs` command:**

**Full output of failed command:**
<details>

et-bridge-bridge-nf-call-iptables"
I0819 13:38:06.264850   44777 out.go:192]     ▪ Generating certificates and keys ...
I0819 13:38:06.328819   44777 out.go:192]     ▪ Booting up control plane ...
I0819 13:38:06.352593   44777 out.go:192]     ▪ Configuring RBAC rules ...
I0819 13:38:06.357868   44777 cni.go:93] Creating CNI manager for ""
I0819 13:38:06.357884   44777 cni.go:167] CNI unnecessary in this configuration, recommending no CNI
I0819 13:38:06.357929   44777 ssh_runner.go:149] Run: /bin/bash -c "cat /proc/$(pgrep kube-apiserver)/oom_adj"
I0819 13:38:06.358020   44777 ssh_runner.go:149] Run: sudo /var/lib/minikube/binaries/v1.21.2/kubectl create clusterrolebinding minikube-rbac --clusterrole=cluster-admin --serviceaccount=kube-system:default --kubeconfig=/var/lib/minikube/kubeconfig
I0819 13:38:06.358028   44777 ssh_runner.go:149] Run: sudo /var/lib/minikube/binaries/v1.21.2/kubectl label nodes minikube.k8s.io/version=v1.22.0 minikube.k8s.io/commit=a03fbcf166e6f74ef224d4a63be4277d017bb62e minikube.k8s.io/name=minikube minikube.k8s.io/updated_at=2021_08_19T13_38_06_0700 --all --overwrite --kubeconfig=/var/lib/minikube/kubeconfig
I0819 13:38:07.061394   44777 kubeadm.go:985] duration metric: took 703.431876ms to wait for elevateKubeSystemPrivileges.
I0819 13:38:07.441820   44777 ssh_runner.go:189] Completed: /bin/bash -c "cat /proc/$(pgrep kube-apiserver)/oom_adj": (1.08383886s)
I0819 13:38:07.441826   44777 ssh_runner.go:189] Completed: sudo /var/lib/minikube/binaries/v1.21.2/kubectl label nodes minikube.k8s.io/version=v1.22.0 minikube.k8s.io/commit=a03fbcf166e6f74ef224d4a63be4277d017bb62e minikube.k8s.io/name=minikube minikube.k8s.io/updated_at=2021_08_19T13_38_06_0700 --all --overwrite --kubeconfig=/var/lib/minikube/kubeconfig: (1.083744499s)
I0819 13:38:07.441836   44777 ops.go:34] apiserver oom_adj: -16
I0819 13:38:07.441852   44777 kubeadm.go:392] StartCluster complete in 28.258419977s
I0819 13:38:07.443528   44777 settings.go:142] acquiring lock: {Name:mkd828db7b7cf864e2d4d124744c6ee9c2490d8b Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0819 13:38:07.444463   44777 settings.go:150] Updating kubeconfig:  /etc/kubernetes/admin.conf
I0819 13:38:07.462346   44777 out.go:165] 
W0819 13:38:07.463048   44777 out.go:230] ❌  Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /etc/kubernetes: mkdir /etc/kubernetes: permission denied
W0819 13:38:07.463103   44777 out.go:230] 
W0819 13:38:07.465399   44777 out.go:230] ╭────────────────────────────────────────────────────────────────────╮
│                                                                    │
│    😿  If the above advice does not help, please let us know:      │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                    │
│    Please attach the following file to the GitHub issue:           │
│    - /Users/apple/.minikube/logs/lastStart.txt                     │
│                                                                    │
╰────────────────────────────────────────────────────────────────────╯

</details>

**Comment by sharifelgamal** [comment]
This is an interesting failure because it means you got a permission denied error inside of your minikube guest, that's what "Updating kubeconfig" means. I'm not sure how that's possible. Have you tried just running a `minikube delete` and `minikube start` just to see what happen?

**Comment by spowelljr** [comment]
Hi @syedkhalandar80, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
