### ISSUE TITLE
Failed to run initialization script from /var/lib/boot2docker/bootlocal.sh

### ISSUE THREAD

**Issue by zcahana** [kubernetes/minikube#1230]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
v0.17.1

**Environment**:
- **OS** (e.g. from /etc/os-release):
Windows 7 x64
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v1.0.7
- **Install tools**:
- **Others**:

**What happened**:

I've loaded an initialization script into `/var/lib/boot2docker/bootlocal.sh` within minikube's VM, in an attempt to configure it with a static IP. The command I've used is as follows:
```
minikube ssh "echo 'pkill udhcpc && ifconfig eth1 192.168.99.100 netmask 255.255.255.0 broadcast 192.168.99.255 up' | sudo tee /var/lib/boot2docker/bootlocal.sh > /dev/null"
```

However, it seems that the script is never run during minikube's VM boot (i.e., upon a subsequent `minikube start`).

**What you expected to happen**:
I'm expecting this script to be run whenever I run `minikube start`, as per [this code](https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/automount/minikube-automount#L210)

**How to reproduce it** (as minimally and precisely as possible):
1. Create a new minikube VM:
`minikube start`
2. Run the following:
 `minikube ssh "echo 'touch /var/lib/boot2docker/test-file' | sudo tee /var/lib/boot2docker/bootlocal.sh > /dev/null"`
3. Restart the minikube VM:
`minikube stop && minikube start`
4. Check if the file was created:
`minikube ssh ls /var/lib/boot2docker/`

**Anything else do we need to know**:

Probing into minikube's boot procedure, it seems that the `bootlocal.sh` is searched for at `/var/lib/bootlocal.sh`, instead of at `/var/lib/boot2docker/bootlocal.sh`.

Here's what I'm seeing:
```
$ minikube ssh "cat /usr/sbin/minikube-automount | tail -n 5"

# This script will get called when the machine is started up
# Feel free to add any initialization you need to be ran here
if [ -e /var/lib/bootlocal.sh ]; then
    /bin/sh /var/lib/bootlocal.sh
fi
```
Furthermore, checking the systemd service status, it suggests that this is indeed the code being executed from the automount script:
```
$ minikube ssh systemctl status minikube-automount.service
● minikube-automount.service - minikube automount
   Loaded: loaded (/lib/systemd/system/minikube-automount.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2017-03-09 13:24:56 UTC; 57min ago
 Main PID: 2359 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 4915)
   Memory: 0B
      CPU: 0
   CGroup: /system.slice/minikube-automount.service

Mar 09 13:24:56 minikube minikube-automount[2359]: + for line in '$(VBoxControl --nologo sharedfolder list -automount | tail -n+3 | cut  -d '\'' '\'' -f 3)'
Mar 09 13:24:56 minikube minikube-automount[2359]: + try_mount_share c/Users
Mar 09 13:24:56 minikube minikube-automount[2359]: + dir=c/Users
Mar 09 13:24:56 minikube minikube-automount[2359]: + name=c/Users
Mar 09 13:24:56 minikube minikube-automount[2359]: + dir=/c/Users
Mar 09 13:24:56 minikube minikube-automount[2359]: + mkdir -p /c/Users
Mar 09 13:24:56 minikube minikube-automount[2359]: + mount -t vboxsf -o defaults,iocharset=utf8,uid=1001,gid=1001 c/Users /c/Users
Mar 09 13:24:56 minikube minikube-automount[2359]: + return 0
Mar 09 13:24:56 minikube minikube-automount[2359]: + '[' -e /var/lib/bootlocal.sh ']'
Mar 09 13:24:56 minikube systemd[1]: Started minikube automount.
```

I've tried workaround'ing this by writing my initialization script into `/var/lib/bootlocal.sh`, but apparently this file is not persisted upon minikube restart.
I've also tried modifying `/usr/sbin/minikube-automount` to execute `/var/lib/boot2docker/bootlocal.sh`, but these changes are not persisted neither.

**Comment by aaron-prindle** [comment]
Thanks for the detailed bug report.  This script should be moved to a persistent folder, like back into /var/lib/boot2docker/bootlocal.sh.  In the meantime you can modify usr/sbin/minikube-automount to have your init scripts

**Comment by zcahana** [comment]
I've attempted to modify `/usr/sbin/minikube-automount` using the following command:
```
minikube ssh "sudo sed -i s@/var/lib/bootlocal.sh@/var/lib/boot2docker/bootlocal.sh@ /usr/sbin/minikube-automount"
```
But apparently that's not persisted either - the next time I restart minikube, the `minikube-automount` file is restored to its original version, and `/var/lib/boot2docker/bootlocal.sh` isn't invoked.

My workaround for now is to use minikube v0.12.2, and write my init stuff into `/var/lib/boot2docker/bootsync.sh`.

**Comment by dlorenc** [comment]
I'm confused, it looks like we already should be calling /var/lib/boot2docker/bootlocal.sh:
https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/automount/minikube-automount#L212

**Comment by r2d4** [comment]
@dlorenc I saw this over the weekend and tried to rerun the Jenkins job but it failed on something else.  I think I may have uploaded 1.0.7 from my machine and somehow missed that change (through one of buildroots odd caching layers)

We should be able to just re-release 1.0.7 from Jenkins

**Comment by r2d4** [comment]
@zcahana this should be fixed now.  

You can get the fix just by `minikube delete` and `rm -r ~/.minikube/cache` then `minikube start` with 0.17.1

**Comment by zcahana** [comment]
Thanks @r2d4.
I've reinstalled minikube and verified that this is now working as expected.

**Comment by zcahana** [comment]
p.s., feel free to close the issue when you see fit.
