### ISSUE TITLE
Better deal with failures under golang 1.8 reopening

### ISSUE THREAD

**Issue by IxDay** [kubernetes/minikube#1231]
#1164 was fixing an issue on minikube when compiled with golang1.8, however, as the vendor have been updated in [this patch](https://github.com/kubernetes/minikube/commit/7bfa1275ac161ce1b79b3070f8260e35dcfb8855) the compatibility is broken again.

**Comment by aaron-prindle** [comment]
This is fixed upstream and should be fixed when we upgrade to v1.5.4 of k8s.  We shouldn't be changing vendor as that isn't a sustainable solution for this.

**Comment by IxDay** [comment]
Using Archlinux default compiler which is now 1.8

**Comment by r2d4** [comment]
Not a great solution to the problem, but I've been using https://github.com/wfarr/goenv to manage go versions at the folder level.

**Comment by aaron-prindle** [comment]
Can you build off of the k8s-v1.6 branch?  That should have the required fix in it.  Its up to date and will be merged into master soon.

**Comment by IxDay** [comment]
This actually works. As we can see the patch in the file [here](https://github.com/kubernetes/kubernetes/blob/release-1.6/staging/src/k8s.io/client-go/rest/url_utils.go#L36)

**Comment by r2d4** [comment]
We're on track to merge the branch as soon as 1.6 is released. 

Our 1.6 branch is tracking the latest beta, beta.4 and passing all our integration tests. It should also be mostly rebased with master
