### ISSUE TITLE
Unable to download kubectl, kubelet & kubeadm from China

### ISSUE THREAD

**Issue by kanghaiyan** [kubernetes/minikube#12317]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>
$ minikube start --driver=virtualbox --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'
😄  minikube v1.22.0 on Darwin 10.15.7
✨  Using the virtualbox driver based on user configuration
✅  Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🐳  Preparing Kubernetes v1.21.2 on Docker 20.10.6 ...
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubelet: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.21.2/bin/linux/amd64/kubelet?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.21.2/bin/linux/amd64/kubelet.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.21.2/bin/linux/amd64/kubelet?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.21.2/bin/linux/amd64/kubelet.sha256 Dst:/Users/haiyankang/.minikube/cache/linux/v1.21.2/kubelet.download Pwd: Mode:2 Umask:---------- Detectors:[0x71f3c88 0x71f3c88 0x71f3c88 0x71f3c88 0x71f3c88 0x71f3c88 0x71f3c88] Decompressors:map[bz2:0x71f3c88 gz:0x71f3c88 tar:0x71f3c88 tar.bz2:0x71f3c88 tar.gz:0x71f3c88 tar.xz:0x71f3c88 tar.zst:0x71f3c88 tbz2:0x71f3c88 tgz:0x71f3c88 txz:0x71f3c88 tzst:0x71f3c88 xz:0x71f3c88 zip:0x71f3c88 zst:0x71f3c88] Getters:map[file:0xc002454f40 http:0xc002318160 https:0xc002318180] Dir:false ProgressListener:0x71b6ff0 Insecure:false Options:[0x563f180]}: invalid checksum: Error downloading checksum file: Get "https://storage.googleapis.com/kubernetes-release/release/v1.21.2/bin/linux/amd64/kubelet.sha256": EOF

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
[lastStart.txt](https://github.com/kubernetes/minikube/files/7020288/lastStart.txt)

**Comment by Rits333** [comment]
Hey,
Try this one I am using minikube on virtual box
**# minikube start --kubernetes-version=v1.20.0 --driver=virtualbox**
and let me know if it works.

**Comment by spowelljr** [comment]
Hi @kanghaiyan, thanks for reporting you issue with minikube!

The issue you're experiencing is because you're located in China and are unable to access Google resources.

minikube is trying to download `https://storage.googleapis.com/kubernetes-release/release/v1.21.2/bin/linux/amd64/kubelet` but is being blocked.

 Let me investigate and get back to you, thanks!

-----

嗨@kanghaiyan，感谢您报告您的 minikube 问题！

您遇到的问题是因为您位于中国并且无法访问 Google 资源。

minikube 正在尝试下载 `https://storage.googleapis.com/kubernetes-release/release/v1.21.2/bin/linux/amd64/kubelet` 但被阻止。

 让我调查一下再回复你，谢谢！

**Comment by zhan9san** [comment]
试试下面这个可以吗？
这样minikube会从阿里云拉取镜像

'minikube start --driver=docker --image-mirror-country=cn'
