### ISSUE TITLE
Cannot start minikube - OSX Catalina 10.15.7

### ISSUE THREAD

**Issue by bpschuck** [kubernetes/minikube#12312]
minikube start fails

<details>
bruce.schuck@Bruces-MacBook-Pro-2 ~ % minikube start
😄  minikube v1.22.0 on Darwin 10.15.7
🆕  Kubernetes 1.21.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.21.2
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🤷  virtualbox "minikube" VM is missing, will recreate.
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 41.01 MiB / 41.01 MiB [--------------] 100.00% 4.56 MiB p/s 9.2s
    > kubeadm: 37.30 MiB / 37.30 MiB [---------------] 100.00% 3.17 MiB p/s 12s
    > kubelet: 104.88 MiB / 104.88 MiB [-------------] 100.00% 6.93 MiB p/s 15s

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...| E0819 13:25:35.221595    4717 start.go:141] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
    ▪ Using image kubernetesui/dashboard:v2.1.0
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
🌟  Enabled addons: storage-provisioner, dashboard

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.0
</datails>

**Comment by rdgacarvalho** [comment]
which version of minikube are you using?

**Comment by bpschuck** [comment]
On 8/23/21 02:25, Rodrigo Carvalho wrote:

> which version of minikube are you using?

Sorry, please ignore. I completely removed all the K8s components as
well as my ~/.minikube and ~/.kube directories, then reinstalled with
the current versions. The issue no longer exists.

- Bruce S

**Comment by spowelljr** [comment]
@bpschuck This is a known issue #8765, it's related to the minikube config in the `~/.minikube` that you deleted. Another way to fix it would be `minikube delete --all --purge`.
