### ISSUE TITLE
Unable to start Minikube in Ubuntu-20.04  after installing Kubernetes v1.22.

### ISSUE THREAD

**Issue by tcchen123** [kubernetes/minikube#12316]
I followed the Install and Set Up kubectl on Linux on Kubernetes documentation for Ubuntu-20.04.
I have installed Kubernetes v1.22 on my Windows laptop with WSL2.
Then, I move on to install Minikube.

!--- Please include the "minikube start" command you used in your reproduction steps --->
**Steps to reproduce the issue:** 

1. Install Minikube 
Click on the buttons that describe your target platform. For other architectures, see the release page for a complete list of minikube binaries.
Operating system : Linux 
Architecture :x86-64
Release type : Stable
Installer type : Binary download

To install the latest minikube stable release on x86-64 Linux using binary download:

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube

2.  Start Cluster
From a terminal with administrator access (but not logged in as root), run:
minikube start

Minikube failed to start. Minikube picks up Kubernetes v1.21, instead of Kubernetes v1.22.
See lastStart.tx log file.

[lastStart.txt](https://github.com/kubernetes/minikube/files/7019162/lastStart.txt)

Kindly advise.
Thanks,
Chen TC

**Comment by tcchen123** [comment]
[lastStart.txt](https://github.com/kubernetes/minikube/files/7019406/lastStart.txt)
Re-run 
user1@DESKTOP-HOG39FK:~/.local/bin/kubectl$ curl -LO https://storage.googleapis.com/minikube/releases/v1.22.0/minikube-linux-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 66.5M  100 66.5M    0     0  3908k      0  0:00:17  0:00:17 --:--:-- 4494k
user1@DESKTOP-HOG39FK:~/.local/bin/kubectl$ sudo install minikube-linux-amd64 /usr/local/bin/minikube
[sudo] password for user1:
user1@DESKTOP-HOG39FK:~/.local/bin/kubectl$ ls -al
total 176180
drwxr-xr-x 2 user1 user1     4096 Aug 20 11:53 .
drwxr-xr-x 3 user1 user1     4096 Aug 20 11:16 ..
-rwxrwxrwx 1 user1 user1 46907392 Aug 20 10:56 kubectl
-rw-r--r-- 1 user1 user1 63708512 Aug 20 11:49 kubectl-convert
-rw-r--r-- 1 user1 user1       64 Aug 20 11:50 kubectl-convert.sha256
-rwxrwxrwx 1 user1 user1       64 Aug 20 11:12 kubectl.sha256
-rw-r--r-- 1 user1 user1 69774135 Aug 20 13:39 minikube-linux-amd64
user1@DESKTOP-HOG39FK:~/.local/bin/kubectl$ minikube start
😄  minikube v1.22.0 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.21.2 on Docker 20.10.7 ...
    ▪ Generating certificates and keys ...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.21.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml

Still Minikube is retrieve v1.21.2, instead of v1.22.0. How to make it to retrieve from v1.22.0
See attached log lastStart.txt 
[lastStart.txt](https://github.com/kubernetes/minikube/files/7019428/lastStart.txt)

**Comment by afbjorklund** [comment]
`minikube start --kubernetes-version=v1.22.0`

**Comment by craigjennings11** [comment]
I'm seeing the same failure on Windows 10 even with the `--kubernetes-version=v1.22.0` flag,

> C:\>minikube start --kubernetes-version=v1.22.0
😄  minikube v1.22.0 on Microsoft Windows 10 Pro 10.0.19043 Build 19043
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.22.0 preload ...
    > preloaded-images-k8s-v11-v1...: 495.61 MiB / 495.61 MiB  100.00% 82.45 Mi
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.22.0 on Docker 20.10.7 ...
    ▪ Generating certificates and keys ...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.22.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1

**Comment by afbjorklund** [comment]
But at least it is failing the wanted version

**Comment by Rits333** [comment]
Try this one I am using this one but it is on virtual box
**# minikube start --kubernetes-version=v1.20.0 --driver=virtualbox**

**Comment by tcchen123** [comment]
Thanks Anders Björklund. It worked.
minikube start --kubernetes-version=v1.22.0
