### ISSUE TITLE
[Debian][11][Crash] Starting minikube crash the terminal and never start

### ISSUE THREAD

**Issue by malnajdi** [kubernetes/minikube#12345]
1. I added the Debian Bulleye sourcelist for docker and installed it
2. I downloaded minikube and install it
`curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64`
`sudo install minikube-linux-amd64 /usr/local/bin/minikube`
3. minikube start
4. terminal closes.

**Full output of `minikube logs` command:**
command do not work. But i got some logs from .minikube/logs/laststart.txt

<details>
Log file created at: 2021/08/24 18:16:54
Running on machine: malnajdi
Binary: Built with gc go1.16.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0824 18:16:54.863854    4952 out.go:286] Setting OutFile to fd 1 ...
I0824 18:16:54.863955    4952 out.go:338] isatty.IsTerminal(1) = true
I0824 18:16:54.863965    4952 out.go:299] Setting ErrFile to fd 2...
I0824 18:16:54.863975    4952 out.go:338] isatty.IsTerminal(2) = true
I0824 18:16:54.864074    4952 root.go:312] Updating PATH: /home/malnajdi/.minikube/bin
W0824 18:16:54.864186    4952 root.go:291] Error reading config file at /home/malnajdi/.minikube/config/config.json: open /home/malnajdi/.minikube/config/config.json: no such file or dire
ctory
I0824 18:16:54.864289    4952 out.go:293] Setting JSON to false
I0824 18:16:54.911281    4952 start.go:111] hostinfo: {"hostname":"malnajdi","uptime":1604,"bootTime":1629816611,"procs":232,"os":"linux","platform":"debian","platformFamily":"debian","pl
atformVersion":"11.0","kernelVersion":"5.10.0-8-amd64","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"ffc3520d-4af9-44d7-b90e-46d9003bbda0"}
I0824 18:16:54.911347    4952 start.go:121] virtualization: kvm host
I0824 18:16:54.912905    4952 out.go:165] 😄  minikube v1.22.0 on Debian 11.0
I0824 18:16:54.913019    4952 notify.go:169] Checking for updates...
I0824 18:16:54.913064    4952 driver.go:335] Setting default libvirt URI to qemu:///system
I0824 18:16:54.913087    4952 global.go:111] Querying for installed drivers using PATH=/home/malnajdi/.minikube/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
I0824 18:16:54.940589    4952 docker.go:132] docker version: linux-20.10.8
I0824 18:16:54.940637    4952 cli_runner.go:115] Run: docker system info --format "{{json .}}"
I0824 18:16:54.995619    4952 info.go:263] docker info: {ID:SUN7:NGMC:7BEY:IMCK:O2XF:A4CE:TDRS:XSDS:HGF4:NPVG:P3Z5:UGWF Containers:1 ContainersRunning:0 ContainersPaused:0 ContainersStopp
ed:1 Images:1 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Netw
ork:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true Ker
nelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:f
alse NFd:24 OomKillDisable:false NGoroutines:34 SystemTime:2021-08-24 18:16:54.957882164 +0300 +03 LoggingDriver:json-file CgroupDriver:systemd NEventsListener:0 KernelVersion:5.10.0-8-am
d64 OperatingSystem:Debian GNU/Linux 11 (bullseye) OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] A
llowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:8 MemTotal:166
85723648 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:malnajdi Labels:[] ExperimentalBuild:false ServerVersion:20.10.8 ClusterStore: ClusterAd
vertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isol
ation: InitBinary:docker-init ContainerdCommit:{ID:e25210fe30a0a703442421b0f60afac609f950a3 Expected:e25210fe30a0a703442421b0f60afac609f950a3} RuncCommit:{ID:v1.0.1-0-g4144b63 Expected:v1
.0.1-0-g4144b63} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=apparmor name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientI
nfo:{Debug:false Plugins:[map[Experimental:true Name:app Path:/usr/libexec/docker/cli-plugins/docker-app SchemaVersion:0.1.0 ShortDescription:Docker App Vendor:Docker Inc. Version:v0.9.1-
beta3] map[Name:buildx Path:/usr/libexec/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Build with BuildKit Vendor:Docker Inc. Version:v0.6.1-docker] map[Name:scan
Path:/usr/libexec/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.8.0]] Warnings:<nil>}}
I0824 18:16:54.995691    4952 docker.go:244] overlay module found
I0824 18:16:54.995698    4952 global.go:119] docker default: true priority: 9, state: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0824 18:16:54.995719    4952 global.go:119] kvm2 default: true priority: 8, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "virsh": executable fil
e not found in $PATH Reason: Fix:Install libvirt Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/}
I0824 18:16:54.995737    4952 global.go:119] none default: false priority: 4, state: {Installed:false Healthy:false Running:true NeedsImprovement:false Error:exec: "iptables": executable
file not found in $PATH Reason: Fix:iptables must be installed Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/none/}
I0824 18:16:54.995751    4952 global.go:119] podman default: true priority: 7, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "podman": executable
file not found in $PATH Reason: Fix:Install Podman Doc:https://minikube.sigs.k8s.io/docs/drivers/podman/}
I0824 18:16:54.995758    4952 global.go:119] ssh default: false priority: 4, state: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0824 18:16:54.995777    4952 global.go:119] virtualbox default: true priority: 6, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:unable to find VBoxManage in $PATH Reason: Fix:Install VirtualBox Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/}
I0824 18:16:54.995790    4952 global.go:119] vmware default: true priority: 7, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "docker-machine-driver-vmware": executable file not found in $PATH Reason: Fix:Install docker-machine-driver-vmware Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/}
I0824 18:16:54.995798    4952 driver.go:279] "docker" has a higher priority (9) than "" (0)
I0824 18:16:54.995803    4952 driver.go:270] not recommending "ssh" due to default: false
I0824 18:16:54.995814    4952 driver.go:305] Picked: docker
I0824 18:16:54.995819    4952 driver.go:306] Alternatives: [ssh]
I0824 18:16:54.995823    4952 driver.go:307] Rejects: [kvm2 none podman virtualbox vmware]
I0824 18:16:54.996903    4952 out.go:165] ✨  Automatically selected the docker driver
I0824 18:16:54.996917    4952 start.go:278] selected driver: docker
I0824 18:16:54.996924    4952 start.go:751] validating driver "docker" against <nil>
I0824 18:16:54.996937    4952 start.go:762] status for docker: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0824 18:16:54.996977    4952 cli_runner.go:115] Run: docker system info --format "{{json .}}"
I0824 18:16:55.052479    4952 info.go:263] docker info: {ID:SUN7:NGMC:7BEY:IMCK:O2XF:A4CE:TDRS:XSDS:HGF4:NPVG:P3Z5:UGWF Containers:1 ContainersRunning:0 ContainersPaused:0 ContainersStopped:1 Images:1 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:24 OomKillDisable:false NGoroutines:34 SystemTime:2021-08-24 18:16:55.014128796 +0300 +03 LoggingDriver:json-file CgroupDriver:systemd NEventsListener:0 KernelVersion:5.10.0-8-amd64 OperatingSystem:Debian GNU/Linux 11 (bullseye) OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:8 MemTotal:16685723648 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:malnajdi Labels:[] ExperimentalBuild:false ServerVersion:20.10.8 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:e25210fe30a0a703442421b0f60afac609f950a3 Expected:e25210fe30a0a703442421b0f60afac609f950a3} RuncCommit:{ID:v1.0.1-0-g4144b63 Expected:v1.0.1-0-g4144b63} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=apparmor name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Experimental:true Name:app Path:/usr/libexec/docker/cli-plugins/docker-app SchemaVersion:0.1.0 ShortDescription:Docker App Vendor:Docker Inc. Version:v0.9.1-beta3] map[Name:buildx Path:/usr/libexec/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Build with BuildKit Vendor:Docker Inc. Version:v0.6.1-docker] map[Name:scan
Path:/usr/libexec/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.8.0]] Warnings:<nil>}}
I0824 18:16:55.052581    4952 start_flags.go:261] no existing cluster config was found, will generate one from the flags
I0824 18:16:55.053133    4952 start_flags.go:342] Using suggested 3900MB memory alloc based on sys=15912MB, container=15912MB
I0824 18:16:55.053193    4952 start_flags.go:669] Wait components to verify : map[apiserver:true system_pods:true]
I0824 18:16:55.053204    4952 cni.go:93] Creating CNI manager for ""
I0824 18:16:55.053210    4952 cni.go:167] CNI unnecessary in this configuration, recommending no CNI
I0824 18:16:55.053214    4952 start_flags.go:275] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.25@sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79 Memory:3900 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.21.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false}
I0824 18:16:55.054260    4952 out.go:165] 👍  Starting control plane node minikube in cluster minikube
I0824 18:16:55.054284    4952 cache.go:117] Beginning downloading kic base image for docker with docker
</details>

**Comment by afbjorklund** [comment]
You could try downloading the image ahead of time ? Maybe it would show a more explicit error.

Either using minikube:

```
$ minikube start --download-only
😄  minikube v1.22.0 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
✅  Download complete!
```

Or directly in docker:

```console
$ docker pull gcr.io/k8s-minikube/kicbase:v0.0.25
v0.0.25: Pulling from k8s-minikube/kicbase
Digest: sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79
Status: Image is up to date for gcr.io/k8s-minikube/kicbase:v0.0.25
gcr.io/k8s-minikube/kicbase:v0.0.25


```

**Comment by malnajdi** [comment]
> ```
> docker pull gcr.io/k8s-minikube/kicbase:v0.0.25
> ```


This is from my machine.

Running `minikube start --download-only` still crashes the terminal.
Check this video here: https://twitter.com/i/status/1429010611753598979

For pulling the image check the output
```
docker pull gcr.io/k8s-minikube/kicbase:v0.0.25
v0.0.25: Pulling from k8s-minikube/kicbase
Digest: sha256:6f936e3443b95cd918d77623bf7b595653bb382766e280290a02b4a349e88b79
Status: Image is up to date for gcr.io/k8s-minikube/kicbase:v0.0.25
gcr.io/k8s-minikube/kicbase:v0.0.25
```

Not sure if has anyone tested it on Debian 11 ?

**Comment by afbjorklund** [comment]
> Not sure if has anyone tested it on Debian 11 ?

Doesn't seem so... Guess you just did ?

But I don't know anyone from Debian being involved in Kubernetes (or Docker). Would be nice to have minikube included there...

**Comment by afbjorklund** [comment]
You could try `export MINIKUBE_IN_STYLE=false`

In case there was something wrong with the emoji support ?

**Comment by malnajdi** [comment]
@afbjorklund You were right i was emoji issue. which package that minikube relay on for Emoji ?

**Comment by malnajdi** [comment]
@afbjorklund So I thought that one of the emoji might be the cause so i tested the printed emojis by minikube and i found this

```
malnajdi@malnajdi:~$ printf '\U1F604\n\U2728\n\U1F44D\n'
😄
✨
👍
malnajdi@malnajdi:~$ printf '\U1F604\n\U2728\n\U1F44D\n\U1F525\n'
--- Terminal Crash With Adding the Fire Emoji.
```

**Comment by malnajdi** [comment]
For anyone who is running a minimal desktop Env (Debian 11)(Xmonad) with ST terminal 
All had to do is install missing fonts listed below:

- emojione-android.ttf
- NotoColorEmoji.ttf
- NotoEmoji-Regular.ttf

Now everything works.
