### ISSUE TITLE
minikube start uses curl but does not seem to support setting CURL_CA_BUNDLE as often required by proxies

### ISSUE THREAD

**Issue by spkane** [kubernetes/minikube#12354]
**Steps to reproduce the issue:** 

macOS Catalina with current Docker Desktop and minikube installed.

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.15.7
BuildVersion:	19H1323

$ minikube version
minikube version: v1.22.0
commit: a03fbcf166e6f74ef224d4a63be4277d017bb62e

$ hyperkit -v
hyperkit: v0.20210107-9-gacbc2d

Homepage: https://github.com/docker/hyperkit
License: BSD
```

Using a VPN and connected to a network that is behind a proxy which requires its own TLS CA BUNDLE.

1.

```sh
minikube start \
     --kubernetes-version=1.19.13 \
     --wait=true \
     --cpus=4 \
     --memory=10g \
     --disk-size=40g \
     --mount=true \
     --driver=hyperkit \
     --docker-env http_proxy=http://proxy.companyx.com:81 \
     --docker-env https_proxy=http://proxy.companyx.com:81 \
     --docker-env no_proxy=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,10.96.0.0/12,192.168.0.0/16,.dev.companyx.com,.cdns.companyx.com,.inf.companyx.com,.ccpc.companyx.com \
     --service-cluster-ip-range=10.96.0.0/12 \
     --alsologtostderr -v=7
```

2. Watch the logs
3. The system will come up, but will report that `This VM is having trouble accessing https://k8s.gcr.io`
4. Looking at detailed logs will show that this step is failing.

```
W0825 11:00:30.431815   27520 start.go:655] [curl -x http://proxy.companyx.com:81 -sS -m 2 https://k8s.gcr.io/] failed: curl -x http://proxy.companyx.com:81 -sS -m 2 https://k8s.gcr.io/: Process exited with status 60
stdout:

stderr:
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

- This is despite the fact that the correct cert is being copied into the VM here `I0825 11:00:29.801209   27520 ssh_runner.go:316] scp /Users/spkane/.minikube/files/etc/ssl/certs/cx-ca-bundle.2017-02-14.crt --> /etc/ssl/certs/cx-ca-bundle.2017-02-14.crt (319100 bytes)` and a bash profile file has even been uploaded to set CURL_CA_BUNDLE to point at that cert here `I0825 11:00:29.785248   27520 ssh_runner.go:316] scp /Users/spkane/.minikube/files/etc/profile.d/curl-companyx-cert.sh --> /etc/profile.d/curl-companyx-cert.sh (61 bytes)`.
- My attempt to fix this was to copy the cert and profile file to the systm. The profile simply runs `export CURL_CA_BUNDLE=/etc/ssl/certs/companyx-ca-bundle.pem`. This allows me to run `minikube ssh` and then run `curl -x http://proxy.companyx.com:81 -sS -m 2 https://k8s.gcr.io/` without error, however, I suspect that the profile is not being used when `start.go` is running this command internally. Either way it seems like there should be a better way to set the CURL_CA_BUNDLE so that it works when a custom cert is required.

**Full output of failed command:**
<details>
I0825 11:26:09.581558   30478 main.go:130] libmachine: Checking connection to Docker...
I0825 11:26:09.581614   30478 main.go:130] libmachine: (minikube) Calling .GetURL
I0825 11:26:09.581882   30478 main.go:130] libmachine: Docker is up and running!
I0825 11:26:09.581901   30478 main.go:130] libmachine: Reticulating splines...
I0825 11:26:09.581924   30478 client.go:171] LocalClient.Create took 18.392872057s
I0825 11:26:09.581973   30478 start.go:168] duration metric: libmachine.API.Create for "minikube" took 18.393017354s
I0825 11:26:09.581997   30478 start.go:267] post-start starting for "minikube" (driver="hyperkit")
I0825 11:26:09.582008   30478 start.go:277] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0825 11:26:09.582029   30478 main.go:130] libmachine: (minikube) Calling .DriverName
I0825 11:26:09.582422   30478 ssh_runner.go:149] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0825 11:26:09.582451   30478 main.go:130] libmachine: (minikube) Calling .GetSSHHostname
I0825 11:26:09.582688   30478 main.go:130] libmachine: (minikube) Calling .GetSSHPort
I0825 11:26:09.582829   30478 main.go:130] libmachine: (minikube) Calling .GetSSHKeyPath
I0825 11:26:09.582956   30478 main.go:130] libmachine: (minikube) Calling .GetSSHUsername
I0825 11:26:09.583081   30478 sshutil.go:53] new ssh client: &{IP:192.168.64.25 Port:22 SSHKeyPath:/Users/spkane/.minikube/machines/minikube/id_rsa Username:docker}
I0825 11:26:09.625108   30478 ssh_runner.go:149] Run: cat /etc/os-release
I0825 11:26:09.629497   30478 info.go:137] Remote host: Buildroot 2020.02.12
I0825 11:26:09.629560   30478 filesync.go:126] Scanning /Users/spkane/.minikube/addons for local assets ...
I0825 11:26:09.629727   30478 filesync.go:126] Scanning /Users/spkane/.minikube/files for local assets ...
I0825 11:26:09.630011   30478 filesync.go:149] local asset: /Users/spkane/.minikube/files/etc/profile.d/curl-companyx-cert.sh -> curl-companyx-cert.sh in /etc/profile.d
I0825 11:26:09.630023   30478 vm_assets.go:99] NewFileAsset: /Users/spkane/.minikube/files/etc/profile.d/curl-companyx-cert.sh -> /etc/profile.d/curl-companyx-cert.sh
I0825 11:26:09.630202   30478 filesync.go:149] local asset: /Users/spkane/.minikube/files/etc/ssl/certs/cx-ca-bundle.2017-02-14.crt -> cx-ca-bundle.2017-02-14.crt in /etc/ssl/certs
I0825 11:26:09.630212   30478 vm_assets.go:99] NewFileAsset: /Users/spkane/.minikube/files/etc/ssl/certs/cx-ca-bundle.2017-02-14.crt -> /etc/ssl/certs/cx-ca-bundle.2017-02-14.crt
I0825 11:26:09.630397   30478 ssh_runner.go:149] Run: sudo mkdir -p /etc/profile.d /etc/ssl/certs
I0825 11:26:09.635940   30478 ssh_runner.go:316] scp /Users/spkane/.minikube/files/etc/profile.d/curl-companyx-cert.sh --> /etc/profile.d/curl-companyx-cert.sh (61 bytes)
I0825 11:26:09.648569   30478 ssh_runner.go:149] Run: stat -c "%s %y" /etc/ssl/certs/cx-ca-bundle.2017-02-14.crt
I0825 11:26:09.652090   30478 ssh_runner.go:306] existence check for /etc/ssl/certs/cx-ca-bundle.2017-02-14.crt: stat -c "%s %y" /etc/ssl/certs/cx-ca-bundle.2017-02-14.crt: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/etc/ssl/certs/cx-ca-bundle.2017-02-14.crt': No such file or directory
I0825 11:26:09.652151   30478 ssh_runner.go:316] scp /Users/spkane/.minikube/files/etc/ssl/certs/cx-ca-bundle.2017-02-14.crt --> /etc/ssl/certs/cx-ca-bundle.2017-02-14.crt (319100 bytes)
I0825 11:26:09.669037   30478 start.go:270] post-start completed in 87.023929ms
I0825 11:26:09.669075   30478 main.go:130] libmachine: (minikube) Calling .GetConfigRaw
I0825 11:26:09.669951   30478 main.go:130] libmachine: (minikube) Calling .GetIP
I0825 11:26:09.670219   30478 profile.go:148] Saving config to /Users/spkane/.minikube/profiles/minikube/config.json ...
I0825 11:26:09.670788   30478 start.go:129] duration metric: createHost completed in 18.504448666s
I0825 11:26:09.670803   30478 start.go:80] releasing machines lock for "minikube", held for 18.528779927s
I0825 11:26:09.670851   30478 main.go:130] libmachine: (minikube) Calling .DriverName
I0825 11:26:09.671037   30478 main.go:130] libmachine: (minikube) Calling .GetIP
I0825 11:26:09.674489   30478 out.go:165] 🌐  Found network options:

🌐  Found network options:
I0825 11:26:09.680162   30478 out.go:165]     ▪ HTTP_PROXY=http://proxy.companyx.com:81
    ▪ HTTP_PROXY=http://proxy.companyx.com:81
W0825 11:26:09.680252   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.680285   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.680301   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.680314   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.680327   30478 proxy.go:118] fail to check proxy env: Error ip not in block
I0825 11:26:09.687772   30478 out.go:165]     ▪ HTTPS_PROXY=http://proxy.companyx.com:81
    ▪ HTTPS_PROXY=http://proxy.companyx.com:81
W0825 11:26:09.687851   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.687863   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.687872   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.687880   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.687887   30478 proxy.go:118] fail to check proxy env: Error ip not in block
I0825 11:26:09.694211   30478 out.go:165]     ▪ NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,10.96.0.0/12,192.168.0.0/16,.dev.companyx.com,.cdns.companyx.com,.inf.companyx.com,.ccpc.companyx.com
    ▪ NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,10.96.0.0/12,192.168.0.0/16,.dev.companyx.com,.cdns.companyx.com,.inf.companyx.com,.ccpc.companyx.com
W0825 11:26:09.694258   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.694271   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.694279   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.694287   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.695753   30478 proxy.go:118] fail to check proxy env: Error ip not in block
I0825 11:26:09.703582   30478 out.go:165]     ▪ http_proxy=http://proxy.companyx.com:81
    ▪ http_proxy=http://proxy.companyx.com:81
W0825 11:26:09.703669   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.703682   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.703692   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.703701   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.703708   30478 proxy.go:118] fail to check proxy env: Error ip not in block
I0825 11:26:09.710324   30478 out.go:165]     ▪ https_proxy=http://proxy.companyx.com:81
    ▪ https_proxy=http://proxy.companyx.com:81
W0825 11:26:09.710386   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.710399   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.710408   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.710417   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.710430   30478 proxy.go:118] fail to check proxy env: Error ip not in block
I0825 11:26:09.716055   30478 out.go:165]     ▪ no_proxy=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,10.96.0.0/12,192.168.0.0/16,.dev.companyx.com,.cdns.companyx.com,.inf.companyx.com,.ccpc.companyx.com
    ▪ no_proxy=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,10.96.0.0/12,192.168.0.0/16,.dev.companyx.com,.cdns.companyx.com,.inf.companyx.com,.ccpc.companyx.com
W0825 11:26:09.716108   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.716121   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.716130   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.716140   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.716156   30478 proxy.go:118] fail to check proxy env: Error ip not in block
I0825 11:26:09.716190   30478 main.go:130] libmachine: (minikube) Calling .DriverName
I0825 11:26:09.716445   30478 main.go:130] libmachine: (minikube) Calling .DriverName
I0825 11:26:09.717074   30478 main.go:130] libmachine: (minikube) Calling .DriverName
W0825 11:26:09.717328   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.717368   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.717387   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.717401   30478 proxy.go:118] fail to check proxy env: Error ip not in block
W0825 11:26:09.717420   30478 proxy.go:118] fail to check proxy env: Error ip not in block
I0825 11:26:09.717708   30478 ssh_runner.go:149] Run: curl -x http://proxy.companyx.com:81 -sS -m 2 https://k8s.gcr.io/
I0825 11:26:09.717724   30478 ssh_runner.go:149] Run: systemctl --version
I0825 11:26:09.717746   30478 main.go:130] libmachine: (minikube) Calling .GetSSHHostname
I0825 11:26:09.717760   30478 main.go:130] libmachine: (minikube) Calling .GetSSHHostname
I0825 11:26:09.717945   30478 main.go:130] libmachine: (minikube) Calling .GetSSHPort
I0825 11:26:09.717979   30478 main.go:130] libmachine: (minikube) Calling .GetSSHPort
I0825 11:26:09.718126   30478 main.go:130] libmachine: (minikube) Calling .GetSSHKeyPath
I0825 11:26:09.718166   30478 main.go:130] libmachine: (minikube) Calling .GetSSHKeyPath
I0825 11:26:09.718274   30478 main.go:130] libmachine: (minikube) Calling .GetSSHUsername
I0825 11:26:09.718304   30478 main.go:130] libmachine: (minikube) Calling .GetSSHUsername
I0825 11:26:09.718414   30478 sshutil.go:53] new ssh client: &{IP:192.168.64.25 Port:22 SSHKeyPath:/Users/spkane/.minikube/machines/minikube/id_rsa Username:docker}
I0825 11:26:09.718456   30478 sshutil.go:53] new ssh client: &{IP:192.168.64.25 Port:22 SSHKeyPath:/Users/spkane/.minikube/machines/minikube/id_rsa Username:docker}
I0825 11:26:10.280237   30478 preload.go:134] Checking if preload exists for k8s version v1.19.13 and runtime docker
W0825 11:26:10.280296   30478 start.go:655] [curl -x http://proxy.companyx.com:81 -sS -m 2 https://k8s.gcr.io/] failed: curl -x http://proxy.companyx.com:81 -sS -m 2 https://k8s.gcr.io/: Process exited with status 60
stdout:

stderr:
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
I0825 11:26:10.280567   30478 ssh_runner.go:149] Run: docker images --format {{.Repository}}:{{.Tag}}
W0825 11:26:10.280615   30478 out.go:230] ❗  This VM is having trouble accessing https://k8s.gcr.io
❗  This VM is having trouble accessing https://k8s.gcr.io
W0825 11:26:10.280661   30478 out.go:230] 💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
I0825 11:26:10.313988   30478 docker.go:535] Got preloaded images:
I0825 11:26:10.314012   30478 docker.go:541] k8s.gcr.io/kube-apiserver:v1.19.13 wasn't preloaded
</details>

**Comment by sharifelgamal** [comment]
This seems like a reasonable feature to add. We'll slot it into our near term work.

**Comment by medyagh** [comment]
This issue is available to be picked up by anyone interested.

**Comment by Karmavil** [comment]
Before digging further. Why are you using https over http?
[Check the settings](https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/#macos-and-linux)
I guess you can use the same port .. but why would you send an encrypted communication as unencrypted? If that's what you need to do or if I am missing some technical concept here let me know to avoid asking details beyond the scope of this issue

**Comment by spkane** [comment]
> Before digging further. Why are you using https over http?

It has been awhile, but this shouldn't be relevant to the ticket. The point was just that `CURL_CA_BUNDLE` is not properly passed through to the underlying `curl` commands, when it is defined and this breaks proxies that use SSL certs from internal CAs.
