### ISSUE TITLE
`/etc/containerd/config.toml` mixes up v1 config and v2 config

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/minikube#12355]
https://github.com/kubernetes/minikube/blob/0bb1f675eae5c89244843f4d91a5a65fc947d30c/pkg/minikube/cruntime/containerd.go#L75-L90

The current `/etc/containerd/config.toml` mixes up v1 config (`plugins.cri`) and v2 config (`plugins."io.containerd.grpc.v1.cri"`).

v1 config is deprecated, and mixing up v1 and v2 is never supported.

**Comment by spowelljr** [comment]
This should be fixed with https://github.com/kubernetes/minikube/pull/12740
