### ISSUE TITLE
kicbase/entrypoint: zfs workaround is broken

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/minikube#12358]
https://github.com/kubernetes/minikube/blob/0bb1f675eae5c89244843f4d91a5a65fc947d30c/deploy/kicbase/entrypoint#L23-L27

The zfs workaround above is broken, because `/etc/containerd/config.toml` is overriden by `pkg/minikube/cruntime.Containerd.Enable()`

https://github.com/kubernetes/minikube/blob/0bb1f675eae5c89244843f4d91a5a65fc947d30c/pkg/minikube/cruntime/containerd.go#L225-L244

**Comment by medyagh** [comment]
@AkihiroSuda I would be happy to see a fix for this issue, PRs are welcome
