### ISSUE TITLE
Make localkube build without cgo

### ISSUE THREAD

**Issue by copumpkin** [kubernetes/minikube#1238]
**FEATURE REQUEST**

Although it currently works in many situations, the cgo-based `localkube` build can be painful. For one, it requires a running docker on non-Linux platforms, unlike pure Go solutions. It needs to go out of its way to produce a static Linux binary, which would otherwise be the default if we stuck to pure Go. And furthermore, in some environments, it's quite difficult/unwieldy to get a working docker build environment.

My understanding is that there's currently a handful of `localkube` vendored dependencies that require cgo. The most obvious of them is `go-systemd`, but upstream seems to have since split out a pure Go version from the cgo one and I think we coul use the pure one. Another is `dlopen`, but I think that's only used by `go-systemd`, so if we move to a pure version of that `dlopen` won't be necessary anymore. I haven't finished enumerating them.

Anyway, it doesn't seem too far-fetched to make `localkube` into a pure Go build. Am I missing something obvious?

Edit: I'm going to tinker with this to see if I can get it working; but anyone with advice or good reasons why this is a hopeless endeavor, please chime in!

**Comment by dlorenc** [comment]
I think there was some stuff in the kubelet code that still required compilation with CGO.

**Comment by aaron-prindle** [comment]
This makes sense and is something we should look into. We should find all the CGO dependencies and track them in this issue.

**Comment by r2d4** [comment]
`k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/cm/cgroup_manager_linux.go`
imports
`github.com/opencontainers/runc/libcontainer/cgroups/systemd`
imports 
`"github.com/coreos/go-systemd/util"`
for `IsRunningSystemd`, which doesn't use CGO.  However, the file contained other CGO code, causing the CGO dependency.  This has been split out in the latest version https://github.com/coreos/go-systemd/pull/190

Upgrading should remove the CGO dependency, however, it needs to be upgraded in Kubernetes itself, since that is where the dependency lies

**Comment by copumpkin** [comment]
So would it make more sense for me to file an equivalent of this ticket against kubernetes, then link it from here?

**Comment by r2d4** [comment]
Yeah, that would be a good start.  We get our dependency from kuberentes.  I'm not entirely certain that this is the only CGO dependency, but this will help.

**Comment by copumpkin** [comment]
@r2d4 looks like it made it into k8s master! https://github.com/kubernetes/kubernetes/commit/f60ac80ee4e8aa979d2110907746001620077355

**Comment by copumpkin** [comment]
Or perhaps not, based on https://github.com/kubernetes/kubernetes/issues/43580#issuecomment-289516172

**Comment by copumpkin** [comment]
I think this might be another dependency of kubelet (which I think means localkube too): https://github.com/google/cadvisor

**Comment by aaron-prindle** [comment]
Closing this for now as it seems that kubernetes does not want to remove this for now: https://github.com/kubernetes/kubernetes/issues/43580#issuecomment-289516172

**Comment by copumpkin** [comment]
Sad but makes sense
