### ISSUE TITLE
Japanese translation needs a policy

### ISSUE THREAD

**Issue by yosshy** [kubernetes/minikube#12388]
We found variants of Japanese translation in translations/ja.json. For example,

- driver
  - ドライバ
  - ドライバー
- '{{...}}'
  - '{{...}}'
  - 「{{...}}」
- command line
  - command line
  - 「command line」

So, we need a policy for consistent Japanese translation. [和訳一般](https://github.com/kubernetes/dashboard/tree/master/i18n/ja#%E5%92%8C%E8%A8%B3%E4%B8%80%E8%88%AC) from Kubernetes Dashboard Japanese i18n Team looks a good candidate for us.

**Comment by t-inu** [comment]
As I commented at https://github.com/kubernetes/minikube/pull/12364#issuecomment-910952611, I agree with using the Dashboard policy.

>> 現存する翻訳方針は、私の知る限り下記２つですが、どちらを採用するか、あるいは新たに方針を立てるか、まず決めた方がよいと思います。
>> [Dashboard](https://github.com/kubernetes/dashboard/tree/master/i18n/ja#%E5%92%8C%E8%A8%B3%E4%B8%80%E8%88%AC)
>> [Docs ja](https://kubernetes.io/ja/docs/contribute/localization/#%E7%BF%BB%E8%A8%B3%E3%82%B9%E3%82%BF%E3%82%A4%E3%83%AB%E3%82%AC%E3%82%A4%E3%83%89)
>
>私は、Dashboardの方針に合わせるのがよいのではと思いました。
>細かく決められていて判断しやすいことと、
>
>- カタカナ用語の語尾に長音表記をつける
>- 英単語と日本語の間に半角スペースを入れる
>- " "は「」に置き換える
>
>といった点が、既存のminikubeの和訳でも多く見られるためです。
>ただ、そうなっていないものも一部あるようなので、この機会に統一していけたらと思います。

**Comment by YuikoTakada** [comment]
@t-inu thank you for your suggestion.
I also agree with Dashboard policy.

**Comment by shu-mutou** [comment]
I had created the translation policy for dashboard. Please ask me if you have question.

**Comment by yosshy** [comment]
/cc @hiroygo @tomocy 
Any comment?

**Comment by tomocy** [comment]
I also agree with this proposal.

**Comment by yosshy** [comment]
Ok, no one is against Dashboard policy. Let's use it for Japanese translation.
