### ISSUE TITLE
Fix building for ppc64le and arm(v7) in kicbase

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#12399]
Building for ppc64le in kicbase was failing so we removed it (#12398) so we could release, ppc64le should be revisited and added back.

**Comment by sharifelgamal** [comment]
the error itself:
```
15:06:41 #160 57.33 Reading state information...
15:06:41 #160 57.96 E: Unable to locate package catatonit
15:06:41 #160 57.96 E: Unable to locate package cri-tools
15:06:41 #160 57.96 E: Unable to locate package podman-plugins
```

**Comment by sharifelgamal** [comment]
for armv7:
```
17:48:54  > [linux/arm/v7 stage-1  9/38] RUN sh -c "echo 'deb https://download.docker.com/linux/ubuntu focal stable' > /etc/apt/sources.list.d/docker.list" &&     curl -L https://download.docker.com/linux/ubuntu/gpg -o docker.key &&     apt-key add - < docker.key &&     clean-install docker-ce docker-ce-cli containerd.io:
17:48:54 #115 36.93 Reading state information...
17:48:54 #115 37.31 Package docker-ce is not available, but is referred to by another package.
17:48:54 #115 37.31 This may mean that the package is missing, has been obsoleted, or
17:48:54 #115 37.31 is only available from another source
17:48:54 #115 37.31 
17:48:54 #115 37.89 E: Package 'docker-ce' has no installation candidate
17:48:54 #115 37.89 E: Unable to locate package docker-ce-cli
17:48:54 #115 37.89 E: Unable to locate package containerd.io
17:48:54 #115 37.89 E: Couldn't find any package by glob 'containerd.io'
17:48:54 #115 37.89 E: Couldn't find any package by regex 'containerd.io'
```

**Comment by afbjorklund** [comment]
You can view the upstream packages here: https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable

* https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/catatonit

* https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/cri-tools

* https://build.opensuse.org/package/show/devel:kubic:libcontainers:stable/podman-plugins

Seems like the `ppc64le` arch was disabled for Ubuntu, even if available for some other distributions such as Fedora.

**Comment by afbjorklund** [comment]
For Docker, I think you have to resort to the tarballs rather than the packages ? But upstream _claims_ to support both:

https://docs.docker.com/engine/install/ubuntu/

```shell
echo \
  "deb [arch=armhf signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

**Comment by afbjorklund** [comment]
@sharifelgamal : this is a bug in the docker packaging for arm32, you need to use the 18.04 packages also on 20.04 :

https://github.com/docker/for-linux/issues/1035

**Comment by afbjorklund** [comment]
@sharifelgamal : looks like cri-o is looking for some help, when it comes to supporting ppc64 and I guess also the .deb

https://github.com/cri-o/cri-o/issues/2467

**Comment by spowelljr** [comment]
According to discussion, if we can't make crio with with PowerPC, just not include if for that arch and let the user know

**Comment by medyagh** [comment]
Lets skip crio on powerpc and arm32
