### ISSUE TITLE
Cannot find provisioner "k8s.io/minikube-hostpath" for hostPath-driven volumes

### ISSUE THREAD

**Issue by shaundomingo** [kubernetes/minikube#1239]
**Report type**: BUG (possible)
**Minikube version**: v0.17.1
**Environment**: 
- **OS**: macOS Sierra - 10.12.3
- **VM Driver**: virtualbox
- **ISO version**: minikube-v1.0.7.iso
- **Install tools**: curl as per README instructions for macOS
- **Others**:

**What happened**: The way PV claims are made against PVs seems to have changed for hostPaths. Instead of getting bound to a volume based on a hostPath with accessModes RWO, a new volume is being created.

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: kube-registry-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  hostPath:
    path: /Users/username/path/to/hostdata/registry
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kube-registry-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
```

Listing the persistent volume (the one I'm hoping to claim against is: kube-registry-pv, the auto-created PV is pvc-04f*):
```
$ kubectl get pv
NAME                                       CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS      CLAIM                       REASON    AGE
kube-registry-pv                           10Gi       RWO           Retain          Available                                         32s
pvc-04f89b3c-0840-11e7-a05a-080027b8816b   10Gi       RWO           Delete          Bound      default/kube-registry-pvc             18s
```

Describing the PVC says _cannot find provisioner "k8s.io/minikube-hostpath"_.
```
$ kubectl describe pvc kube-registry-pvc
Name:           kube-registry-pvc
Namespace:      default
StorageClass:   standard
Status:         Bound
Volume:         pvc-04f89b3c-0840-11e7-a05a-080027b8816b
Labels:         <none>
Capacity:       10Gi
Access Modes:   RWO
Events:
  FirstSeen     LastSeen        Count   From                                                                            SubObjectPath   Type            Reason                  Message
  ---------     --------        -----   ----                                                                            -------------   --------        ------                  -------
  1m            1m              2       {persistentvolume-controller }                                                                  Normal          ExternalProvisioning    cannot find provisioner "k8s.io/minikube-hostpath", expecting that a volume for the claim is provisioned either manually or via external software
  1m            1m              1       {k8s.io/minikube-hostpath minikube bdad1f87-083f-11e7-a05a-080027b8816b }                       Normal          ProvisioningSucceeded   Successfully provisioned volume pvc-04f89b3c-0840-11e7-a05a-080027b8816b
```

**What you expected to happen**: A claim to be created against the declared PV. It should work as it works in in minikube 0.16.0.
```
$ kubectl get pv
NAME               CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                       REASON    AGE
kube-registry-pv   10Gi       RWO           Retain          Bound     default/kube-registry-pvc             21m
$ kubectl describe pvc
Name:           kube-registry-pvc
Namespace:      default
StorageClass:
Status:         Bound
Volume:         kube-registry-pv
Labels:         <none>
Capacity:       10Gi
Access Modes:   RWO
No events.
```

**How to reproduce it** (as minimally and precisely as possible): In a fresh 0.17.1 minikube environment, create the PV, create the PVC. kubectl get pv; kubectl describe pvc

**Anything else do we need to know**: I can see the macOS home directory successfully mounted within the minikube vm when I SSH onto the box, so there is no issue there.

I used to be running minikube 0.13.1 and didn't experience this issue. After upgrading to the latest minikube I'm seeing this behavior. I'm not sure if it's related to this in your release notes:

Version 0.17.0 - 3/2/2017
* Added external hostpath provisioner to localkube

The problem doesn't occur in minikube 0.16.0
```curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.16.0/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/```

Thanks for looking into this / for your help!

**Comment by SpectralHiss** [comment]
bug also occuring for minikube v0.17.1 ..

**Comment by SpectralHiss** [comment]
As a workaround, falling back on minikube 16 also fixes the problem for me .

**Comment by rohanshah** [comment]
I'm having the same issue with minikube version 0.17+
- **OS**: OSX Yosemite 10.10.5
-  **VM Drivier** xhyve

Downgrading to version 0.16 resolved it.

It seems to happen when creating a pvc.. some autogenerated pvc-* pv is created an bound to instead of the pv that the claim should be binding to.

**Comment by rohanshah** [comment]
Some more info that might be helpful. It seems like there's something weird about the `default-storageclass` addon where I can't enable/disable it through the minikube cli. See the following output:

```
$ minikube version
minikube version: v0.17.1
```

```
$ minikube addons list
- addon-manager: enabled
- dashboard: enabled
- default-storageclass: enabled
- kube-dns: enabled
- heapster: disabled
- ingress: disabled
- registry-creds: disabled
```

```
$ minikube addons disable default-storageclass
Property name default-storageclass not found
```

```
$ minikube addons disable dashboard
dashboard was successfully disabled
```

```
$ minikube addons enable dashboard
dashboard was successfully enabled
```

And it seems like that addon (`deafult-storageclass`) is where the `k8s.io/minikube-hostpath` provisioner comes from: https://github.com/kubernetes/minikube/blob/4293b0186608b01b2d9e018b950156f7a8934011/deploy/addons/storageclass/storageclass.yaml

**Comment by wpbeckwith** [comment]
I'm also seeing this issue in version v0.16.0

```
9m		9m		2	{persistentvolume-controller }									Normal		ExternalProvisioning	cannot find provisioner "k8s.io/minikube-hostpath", expecting that a volume for the claim is provisioned either manually or via external software

9m		9m		1	{k8s.io/minikube-hostpath minikube 1957a912-13f5-11e7-80ee-000c29fe7d08 }			Normal		ProvisioningSucceeded	Successfully provisioned volume pvc-d2254ff7-13fa-11e7-80ee-000c29fe7d08
example$ minikube version
minikube version: v0.16.0
```

**Comment by mappedinn** [comment]
:+1:

**Comment by r2d4** [comment]
In the next version of minikube, you should be able to disable the default hostpath provisioner through `minikube addons disable default-storageclass`

https://github.com/kubernetes/minikube/pull/1289

**Comment by er1c** [comment]
I still get the original error with `v0.19.0` 

```cannot find provisioner "k8s.io/minikube-hostpath", expecting that a volume for the claim is provisioned either manually or via external software```

I can solve it by manually specifying `storageClassName: "standard"`, but based upon some of the minikube docs (https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md) I don't think that's the intended behavior/usage.

Specifically if I take the original yaml file: https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/minikube.yml and make the storageClassName change: https://github.com/jenkinsci/kubernetes-plugin/compare/master...er1c:minikube then this error message goes away.

Is this a symptom of some other issue?

**Comment by dlorenc** [comment]
Yeah that's a bit strange. Can you attach the output of:

`kubectl version`

`kubectl get storageclass`

and

`minikube addons list`

**Comment by er1c** [comment]
Original comment updated, and just verified again, that if I explicitly add in the `storageClassName: "standard"` it works fine...ugh..

**Comment by dlorenc** [comment]
Reopening, you definitely shouldn't need to do that.

**Comment by dlorenc** [comment]
Can you show the output of: 

`kubectl describe storageclass standard`

My understanding is that the annotation: "storageclass.beta.kubernetes.io/is-default-class": "true" should mean that this is treated as the default.

This message makes sense:
```shell
message: cannot find provisioner "k8s.io/minikube-hostpath", expecting that a volume for the claim is provisioned either manually or via external software
```

because we moved the k8s.io/minikube-hostpath provisioner to be external.

**Comment by er1c** [comment]
```
$ kubectl describe storageclass standard
Name:		standard
IsDefaultClass:	Yes
Annotations:	kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true"},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile"},"name":"standard","namespace":""},"provisioner":"k8s.io/minikube-hostpath"}
,storageclass.beta.kubernetes.io/is-default-class=true
Provisioner:	k8s.io/minikube-hostpath
Parameters:	<none>
Events:		<none>
```

If I add the `storageClassName: "standard"` here is what the describe pv/pvc look like (normal ish):

```
$ kubectl describe pv
Name:		jenkins
Labels:		<none>
Annotations:	pv.kubernetes.io/bound-by-controller=yes
StorageClass:	standard
Status:		Bound
Claim:		kubernetes-plugin/jenkins
Reclaim Policy:	Retain
Access Modes:	RWO
Capacity:	100Mi
Message:
Source:
    Type:	HostPath (bare host directory volume)
    Path:	/data/kubernetes-plugin-jenkins
Events:		<none>

$ kubectl describe pvc
Name:		jenkins-data-claim
Namespace:	default
StorageClass:	standard
Status:		Lost
Volume:		pvc-e639b9f2-35ba-11e7-877a-080027247732
Labels:		<none>
Annotations:	control-plane.alpha.kubernetes.io/leader={"holderIdentity":"666a194d-35ba-11e7-877a-080027247732","leaseDurationSeconds":15,"acquireTime":"2017-05-10T19:57:30Z","renewTime":"2017-05-10T19:57:32Z","lea...
		pv.kubernetes.io/bind-completed=yes
		pv.kubernetes.io/bound-by-controller=yes
		volume.beta.kubernetes.io/storage-provisioner=k8s.io/minikube-hostpath
Capacity:	0
Access Modes:
Events:		<none>
```

**Comment by dlorenc** [comment]
Ah, hmm. Could you also try with:

```shell
storageClassName: ""
```

I think this might, sadly, be WAI and due to a slight change in behavior in k8s 1.6.

**Comment by er1c** [comment]
Adding `storageClassName: ""` instead of `storageClassName: "standard"` results in the same original error `cannot find provisioner "k8s.io/minikube-hostpath", expecting that a volume for the claim is provisioned either manually or via external software`

**Comment by dlorenc** [comment]
OK, I still can't explain why that PV that gets created for you (pvc-2a08e9bf-366e-11e7-bb0f-080027247732) doesn't get bound to your pvc (jenkins), but I think I see what's going on.

It looks like you don't want dynamic provisioning at all, you want the PVC to get bound to the PV you've created. I think that's not happening for two reasons.

1. because the PV is created in a different namespace. You need the PV and PVC to be in the namespace for kubernetes to bind them.

2. because in k8s 1.6, you need to explicitly opt out of PV provisioning. If you have a DefaultStorageClass in your cluster (and minikube does), any PVCs that do not specify a storageClassName will get an auto-provisioned PV. I'm not sure why this part is not working for you.

But anyway, to get what I think you want, you'll need to change your YAML to put the PV and PVC in the same namespace and to add:

storageClassName: "" to the PVC spec.

**Comment by er1c** [comment]
Unfortunately, this is my first foray into this whole kubernetes world, so sorry I couldn't be more helpful.  Where the original YAML, I was just trying to use "off the shelf" from https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/kubernetes/minikube.yml  I did try to set the PV to the same namespace, but that change by itself did not work.  Next I tried keeping the namespace to be identical, but also adding the `storageClassName: ""`  That still results in the same "cannot find provisioner" error message :(

**Comment by er1c** [comment]
@dlorenc would you mind linking me to that spec so I can read up more on it?  I'm a little confused what the best practice would be here too  Is this what you were referring to? https://kubernetes.io/docs/concepts/storage/persistent-volumes/#dynamic

**Comment by dlorenc** [comment]
Here's the exact YAML I'm using that works:

```yaml
---
apiVersion: "v1"
kind: "List"
items:
  # jenkins

  - apiVersion: "v1"
    kind: "PersistentVolume"
    metadata: 
      name: "jenkins"
    spec: 
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 100Mi
      hostPath:
        path: "/data/kubernetes-plugin-jenkins"

  - apiVersion: "v1"
    kind: "PersistentVolumeClaim"
    metadata: 
      name: "jenkins"
    spec: 
      storageClassName: ""
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
```

I named it pvcs.yaml for the test.

Delete just to make sure nothing is there from before
```shell
$ kubectl delete -f pvcs.yaml
```

```shell
$ kubectl create -f pvcs.yaml 
persistentvolume "jenkins" created
persistentvolumeclaim "jenkins" created
```

```shell
$ kubectl get pv
NAME      CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM             STORAGECLASS   REASON    AGE
jenkins   100Mi      RWO           Retain          Bound     default/jenkins                            2s

$ kubectl get pvc
NAME      STATUS    VOLUME    CAPACITY   ACCESSMODES   STORAGECLASS   AGE
jenkins   Bound     jenkins   100Mi      RWO                          7s
```

With this yaml do you get different results?

**Comment by er1c** [comment]
@dlorenc nope I get the same!

**Comment by dlorenc** [comment]
Cool! So it looks like something in there made it work :)

As for best practices, I'm not sure what the best place for docs is. This blog post explains some of the conventions:
http://blog.kubernetes.io/2016/10/dynamic-provisioning-and-storage-in-kubernetes.html

But it's also a bit outdated since the storageClassName moved to a first class property instead of an annotation.

**Comment by er1c** [comment]
@dlorenc this did the job for me:  https://github.com/jenkinsci/kubernetes-plugin/pull/159/commits/0e41d94cd032d41b92e10d57d68562490e566f82

**Comment by dlorenc** [comment]
Cool. We should fix up our docs to explain this new behavior.

FWIW I think you'll need to make similar changes for any k8s 1.6 environment that has a default storage class enabled.

**Comment by markacola** [comment]
Just in relation to @er1c 's error, I was able to fix this by manually running `minikube addons enable default-storageclass` and recreating any pvcs.

**Comment by er1c** [comment]
@markacola I tried that :( didn't work for me
