### ISSUE TITLE
Create l/ja label and issue template for Japanese

### ISSUE THREAD

**Issue by t-inu** [kubernetes/minikube#12403]
Please create `l/ja` label for Japanese. I don't have the authority to create it.
Then I will add ja.md in .github/ISSUE_TEMPLATE.

**Comment by spowelljr** [comment]
@t-inu Create a PR for the issue template and I'll be sure to create the label before I merge it, thanks!

**Comment by t-inu** [comment]
@spowelljr I created a PR for adding the issue template.
Please confirm https://github.com/kubernetes/minikube/pull/12427.
