### ISSUE TITLE
enable addon 'gcp-auth' on minikube MK_ADDON_ENABLE 

### ISSUE THREAD

**Issue by mddoor** [kubernetes/minikube#12406]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>
Log file created at: 2021/09/03 12:59:54
Running on machine: MD6821-2
Binary: Built with gc go1.16.4 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0903 12:59:54.714623    2988 out.go:286] Setting OutFile to fd 1428 ...
I0903 12:59:54.715133    2988 out.go:333] TERM=,COLORTERM=, which probably does not support color
I0903 12:59:54.715133    2988 out.go:299] Setting ErrFile to fd 1712...
I0903 12:59:54.715133    2988 out.go:333] TERM=,COLORTERM=, which probably does not support color
I0903 12:59:54.728777    2988 addons.go:59] Setting gcp-auth=true in profile "cloud-run-dev-internal"
I0903 12:59:54.729295    2988 mustload.go:65] Loading cluster: cloud-run-dev-internal
I0903 12:59:54.736051    2988 cli_runner.go:115] Run: docker container inspect cloud-run-dev-internal --format={{.State.Status}}
I0903 12:59:55.084399    2988 host.go:66] Checking if "cloud-run-dev-internal" exists ...
I0903 12:59:55.087587    2988 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" cloud-run-dev-internal
I0903 12:59:55.423101    2988 ssh_runner.go:316] scp memory --> /var/lib/minikube/google_application_credentials.json (344 bytes)
I0903 12:59:55.427351    2988 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I0903 12:59:55.870142    2988 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:60055 SSHKeyPath:C:\Users\bzaetz\.minikube\machines\cloud-run-dev-internal\id_rsa Username:docker}
I0903 13:00:03.599409    2988 ssh_runner.go:316] scp memory --> /var/lib/minikube/google_cloud_project (17 bytes)
I0903 13:00:03.612474    2988 addons.go:135] Setting addon gcp-auth=true in "cloud-run-dev-internal"
I0903 13:00:03.612474    2988 addons.go:313] Verifying addon gcp-auth=true in "cloud-run-dev-internal"
I0903 13:00:03.613019    2988 out.go:165] * Verifying gcp-auth addon...
I0903 13:00:03.621293    2988 kapi.go:75] Waiting for pod with label "kubernetes.io/minikube-addons=gcp-auth" in ns "gcp-auth" ...
I0903 13:00:03.629915    2988 kapi.go:86] Found 0 Pods for label selector kubernetes.io/minikube-addons=gcp-auth
I0903 13:05:47.365137    2460 kapi.go:108] duration metric: took 6m0.0234354s to wait for kubernetes.io/minikube-addons=gcp-auth ...
I0903 13:05:47.366239    2460 out.go:165] 
W0903 13:05:47.366239    2460 out.go:230] X Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for kubernetes.io/minikube-addons=gcp-auth pods: timed out waiting for the condition]
W0903 13:05:47.366239    2460 out.go:230] * 
W0903 13:05:47.372065    2460 out.go:230] ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                             │
│    * If the above advice does not help, please let us know:                                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                                               │
│                                                                                                             │
│    * Please attach the following file to the GitHub issue:                                                  │
│    * - C:\Users\user\AppData\Local\Temp\minikube_addons_2e8f999635676c8eabd63ff5417c06c728a3a3e5_0.log    │
│                                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
I0903 13:06:03.629333    2988 kapi.go:108] duration metric: took 6m0.0269388s to wait for kubernetes.io/minikube-addons=gcp-auth ...
I0903 13:06:03.629885    2988 out.go:165] 
W0903 13:06:03.629885    2988 out.go:230] X Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for kubernetes.io/minikube-addons=gcp-auth pods: timed out waiting for the condition]
W0903 13:06:03.629885    2988 out.go:230] * 
W0903 13:06:03.636521    2988 out.go:230] ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                             │
│    * If the above advice does not help, please let us know:                                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                                               │
│                                                                                                             │
│    * Please attach the following file to the GitHub issue:                                                  │
│    * - C:\Users\user\AppData\Local\Temp\minikube_addons_2e8f999635676c8eabd63ff5417c06c728a3a3e5_0.log    │
│                                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by klaases** [comment]
Hi @[mddoor](https://github.com/mddoor) – is this issue still occurring? Are additional details available?

I'm afraid that troubleshooting will be limited without the log output requested above:

```
Please attach the following file to the GitHub issue: │ │ * - C:\Users\user\AppData\Local\Temp\minikube_addons_2e8f999635676c8eabd63ff5417c06c728a3a3e5_0.log
```

If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
