### ISSUE TITLE
Update cri-o from v1.20.0 to v1.22.0

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#12410]
The crio-bin hash constantly changes and causes an issue when building ISO since we hardcode the sha so we can check for mitm attacks. We need to find a way to remedy this since we've made PRs to change the hash 5 times and it has changed once again.

**Comment by spowelljr** [comment]
cc @afbjorklund

**Comment by afbjorklund** [comment]
This was supposed to be fixed in https://github.com/cri-o/cri-o/issues/4820, for cri-o version `v1.22.0`.

So the problem should disappear, once minikube gets upgraded (currently still on 1.20, not even 1.21)

**Comment by medyagh** [comment]
@spowelljr lets upgrade the crio to 1.22 then everywhere kic/iso

**Comment by spowelljr** [comment]
It looks like cri-o stopped supporting s390x after 1.20.

**1.20**
<img width="180" alt="Screen Shot 2021-09-08 at 4 08 57 PM" src="https://user-images.githubusercontent.com/44844360/132597377-163e6eb8-1836-4505-8f73-3e86ec9bee0f.png">
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.20/xUbuntu_20.04/

**1.22**
<img width="173" alt="Screen Shot 2021-09-08 at 4 09 06 PM" src="https://user-images.githubusercontent.com/44844360/132597415-1b840665-5562-47c3-a4b0-01461e72127d.png">
https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04/

Trying to build the kicbase after updating to 1.22 is resulting in the following error:
```
 > [linux/s390x stage-1 15/38] RUN sh -c "echo 'deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable:cri-o:1.22.list" &&     curl -LO https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.22/xUbuntu_20.04/Release.key &&     apt-key add - < Release.key &&     clean-install cri-o cri-o-runc:
#76 13.02 Get:17 http://ports.ubuntu.com/ubuntu-ports focal-backports/main s390x Packages [2684 B]
#76 15.20 Get:18 https://download.docker.com/linux/ubuntu focal/stable s390x Packages [2750 B]
#76 17.49 Get:19 http://ports.ubuntu.com/ubuntu-ports focal-security/restricted s390x Packages [3083 B]
#76 17.53 Get:20 http://ports.ubuntu.com/ubuntu-ports focal-security/main s390x Packages [532 kB]
#76 17.57 Get:21 http://ports.ubuntu.com/ubuntu-ports focal-security/universe s390x Packages [568 kB]
#76 17.61 Get:22 http://ports.ubuntu.com/ubuntu-ports focal-security/multiverse s390x Packages [3243 B]
#76 29.40 Reading package lists...
#76 35.89 Building dependency tree...
#76 36.83 Reading state information...
#76 37.43 E: Unable to locate package cri-o
```
https://storage.cloud.google.com/minikube-builds/logs/12425/991a994/kic_image_build.txt

Any advice on what to do from here @afbjorklund?

**Comment by afbjorklund** [comment]
We should disable cri-o on that architecture (making the packages conditional)

We have a similar issue with docker on armv7.

**Comment by spowelljr** [comment]
Created issue with cri-o to create s390x packages: https://github.com/cri-o/cri-o/issues/5292
