### ISSUE TITLE
Problem in Starting minikube on window10

### ISSUE THREAD

**Issue by zulgey** [kubernetes/minikube#12416]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube start --driver=hyperv
3.

**when executing the above startup commands for minikube I get the following output**

**Full output of failed command if not `minikube start`:**
* minikube v1.23.0 en Microsoft Windows 10 Home Single Language 10.0.19042 Build 19042
* Using the hyperv driver based on user configuration

* Exiting due to PROVIDER_HYPERV_NOT_FOUND: The 'hyperv' provider was not found: exec: "powershell": executable file not found in %PATH%
* 
<details>
*Perform the installation according to what is specified in the documentation*
*when running the command to enable Hyper-v I get the following*

Enable-WindowsOptionalFeature : The feature name Microsoft-Hyper-V is unknown.
In line: 1 Chaaracter: 1
+ Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
+ FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

</details>

**Comment by spowelljr** [comment]
Hi @zulgey, thanks for reporting your issue with minikube!

Try enabling Hyper-V via control panel using the following steps and let me know if that solves your issue.

```
Open Control Panel and navigate to Programs > Programs and Features > Turn Windows features on or off. In the pop-up window, find and check Hyper-V folder, then click OK.

Finally, restart computer when the installation has completed.
```
Instructions from: https://www.partitionwizard.com/partitionmanager/hyper-v-assembly-not-found-error.html

**Comment by zulgey** [comment]
Hi @spowelljr , thanks for the answer, but when verifying I realize that Hyper-v is not in the options to activate or deactivate features of windows

The version is Windows 10 Home Single Language

**Comment by spowelljr** [comment]
@zulgey I did some digging and found the following response:
```
Windows 10 Home edition doesn’t support Hyper-V feature, it can only be enabled on Windows 10 Enterprise, Pro, or Education.

If you want to use virtual machine, you need to use third-party VM software, such as VMware and VirtualBox.
```
https://docs.microsoft.com/en-us/answers/questions/29175/installation-of-hyper-v-on-windows-10-home.html

However in that Q&A I also found a link to the following that others were having success with.
https://www.itechtics.com/enable-hyper-v-windows-10-home/

**Comment by spowelljr** [comment]
Hi @zulgey, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
