### ISSUE TITLE
Ingress functionality broken on 1.23 with kubernetes 1.22.1

### ISSUE THREAD

**Issue by chandler14362** [kubernetes/minikube#12414]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable dashboard
3. minikube dashboard --url

Here is my kubectl version output:
`Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:38:26Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.1", GitCommit:"632ed300f2c34f6d6d15ca4cef3d3c7073412212", GitTreeState:"clean", BuildDate:"2021-08-19T15:39:34Z", GoVersion:"go1.16.7", Compiler:"gc", Platform:"linux/amd64"}`

I followed this [example](https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/) in the handbook on a fresh install (uninstall/install through homebrew) and was unable to complete it successfully. There was no luck using the ingress-dns to resolve a service. 

The dashboard also shows a new error now when trying to present any ingress information, other views without ingress information are still possible to access.

[logs.txt](https://github.com/kubernetes/minikube/files/7112303/logs.txt)
<img width="1440" alt="Screen Shot 2021-09-05 at 3 59 09 PM" src="https://user-images.githubusercontent.com/5816171/132140254-9ea5e70a-4836-4257-b7b3-2537808121bd.png">

The logs I provided are from running on macOS but I also get the same issue running on Windows.

**Comment by Bigsmooth68** [comment]
Hello,
Did you check ingress-nginx-controller pod log ?

**Comment by sjansen1** [comment]
Same issue after updating from 1.22 to 1.23. Minikube getting preloaded images and prepares containers, got a few pages of errors about applying updates. After that i see on container ingress container crashlooping and i get the same error on the webui.

Tested on Ubuntu and RHEL with Docker. This is easy reproduceable by just install 1.22, start, stop, update minikube to 1.23 and start.

**Enabled addons:**
dashboard
ingress
storage-provisioner
default-storageclass

**One of the containers crashloop with:**

Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "67ae6ab5bb9d0e45976d647df044b615234366781a9a0ff7b4ab7e46680438d7" network for pod "ingress-nginx-controller-59b45fb494-4nvk4": networkPlugin cni failed to set up pod "ingress-nginx-controller-59b45fb494-4nvk4_ingress-nginx" network: open /run/flannel/subnet.env: no such file or directory

**Comment by spowelljr** [comment]
Hi @chandler14362, thanks for reporting your issue with minikube!

This is a known issue and we have someone working on the issue (#12424).

To keep all the information and conversation centralized I'm closing other issues and re-directing to #12424. Please feel free to contribute and follow along there, thank you for your understanding!
