### ISSUE TITLE
Minikube site Community Page's Footer Links Not working as expected.

### ISSUE THREAD

**Issue by shadowshot-x** [kubernetes/minikube#12429]
I have been going over the minikube website but on the community page https://minikube.sigs.k8s.io/community/, I am facing issues to click on the links in the footer. The Cursor keeps on flickering and I am not able to click anything. This does not happen in pages like https://minikube.sigs.k8s.io/docs/ which use the same footer.

I am using Google Chrome Version 92.0.4515.131 (Official Build) (64-bit) on Ubuntu 18.04.5 LTS.

Short GIF of the issue. Look closely at the footer
![minikube-issue](https://user-images.githubusercontent.com/43992469/132489695-4aa63f60-47d8-4c4e-ba8d-eaa8cfa8976e.gif)

**Comment by spowelljr** [comment]
Hi @shadowshot-x, thanks for reporting your issue with minikube!

That is indeed a weird bug, I tried on my machine but mine worked as expected: Google Chrome Version 93.0.4577.63 (Official Build) (x86_64) on macOS 11.5.2

Maybe someone else can reproduce this issue.

**Comment by duttaANI** [comment]
@spowelljr  I am experiencing same issue with Google Chrome 93.0.4577.82 and Ubuntu 18.04.6 LTS

**Comment by spowelljr** [comment]
I'm going to assume this might be a Linux or Ubuntu specific bug, code wise if uses the exact same footer as the other pages. I could be wrong, but I'm going to assume the bug is going to be with [docsy](https://github.com/google/docsy) as that's the framework we use for our website.
