### ISSUE TITLE
`curl -Lo` Error

### ISSUE THREAD

**Issue by rwxrob** [kubernetes/minikube#12422]
**Steps to reproduce the issue:** 

1. Open documentation
2. Read step 1 of Getting Started
3. Attempt the `curl -Lo` line from Windows Powershell

<details>
Copying and pasting the `curl -Lo ...` line from the install
instructions produces a PowerShell `Invoke-WebRequest` error with the
message "A parameter cannot be found that matches parameter name 'Lo'.

This can be bypassed by just omitting the capital L since no redirection
is happening.

It's a small thing, but worth mentioning.
</details>

**Comment by spowelljr** [comment]
Hi @rwxrob, thanks for reporting you issue with minikube!

There's currently a PR up that addresses this exact issue #12397, once it's merged this should be resolved.

**Comment by rwxrob** [comment]
Thank you.
