### ISSUE TITLE
VMWare driver mount broken in 1.23

### ISSUE THREAD

**Issue by zarenner** [kubernetes/minikube#12426]
Upgraded to 1.23 and driver mounts in VMWare Fusion appear to be broken. The `/mnt/hgfs` folder is entirely missing, and `vmhgfs-fuse` utility is missing.

**Steps to reproduce the issue:** 

1. `minikube start --iso-url=https://storage.googleapis.com/minikube/iso/minikube-v1.23.0.iso --driver=vmware`
2. `minikube ssh`
3. `ls /mnt/hgfs` returns `No such file or directory`
4. `vmhgfs-fuse` doesn't exist in `/usr/bin/` Exists and works in v1.22.

While this seems potentially related to https://github.com/kubernetes/minikube/pull/12268 (/cc @afbjorklund), it's not obvious to me why `vmhgfs-fuse` went missing. `BR2_PACKAGE_OPENVMTOOLS=y` is still set, so perhaps it's something in https://github.com/buildroot/buildroot/tree/2021.02.x/package/openvmtools or https://github.com/vmware/open-vm-tools itself.

I'm not able to successfully build the ISO on macOS otherwise I'd investigate further.

**Comment by dsedivec** [comment]
Having this here too.  I did see this in the logs:

```
$ journalctl|grep -i hg
Sep 12 23:21:00 minikube sudo[4945]:   docker : PWD=/ ; USER=root ; COMMAND=/usr/bin/mount --bind /mnt/hgfs//hosthome /hosthome
Sep 12 23:21:00 minikube sudo[4948]:   docker : PWD=/ ; USER=root ; COMMAND=/usr/bin/mount -t vmhgfs -o uid=1000,gid=1000 .host:/Users /hosthome
```

Presumably that last would work if the vmhgfs kernel module was available—but open-vm-tools says that's been deprecated in favor of vmhgfs-fuse, as zarenner said.

**Comment by afbjorklund** [comment]
The kernel was kept back, so it should **not** be related to that (upgrading from Linux 4 to Linux 5, that is)

**Comment by schwichtgit** [comment]
PR #13000 should address this issue.

$ ls -al  /mnt/hgfs
total 5
dr-xr-xr-x 1 root root 4192 Jan  6 21:24 .
drwxr-xr-x 4 root root   80 Jan  6 19:18 ..
drwxr-xr-x 1 root   80  160 Dec  7 23:39 Users
