### ISSUE TITLE
Unable to pull `dashboard` & `metrics-scraper` images from `registry.cn-hangzhou.aliyuncs.com/google_containers`

### ISSUE THREAD

**Issue by Fcscanf** [kubernetes/minikube#12428]
**Steps to reproduce the issue:** 

1.I executed minikube start successfully to start minikube, but it failed to start minikube dashboard
```bash
 Exiting due to SVC_URL_TIMEOUT: http://127.0.0.1:40107/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ is not accessible: Temporary Error: unexpected response code: 503
```
![image](https://user-images.githubusercontent.com/27654200/132467099-236f3396-2c95-42a7-adb7-d2964c8050b7.png)

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
The following is the log record of `minikube dashboard`
<details>

[minikube_dashboard_1989b4f49854eaf6b3ed7671224c8f15e3a568a9_0.log](https://github.com/kubernetes/minikube/files/7126972/minikube_dashboard_1989b4f49854eaf6b3ed7671224c8f15e3a568a9_0.log)
[minikube_dashboard_27014b127e5c6c9c95792ad751b8db0a7d7a54aa_0.log](https://github.com/kubernetes/minikube/files/7126974/minikube_dashboard_27014b127e5c6c9c95792ad751b8db0a7d7a54aa_0.log)
[minikube_dashboard_0e027cdabd32d18e1757ed354235ff3cd1e2bdbc_0.log](https://github.com/kubernetes/minikube/files/7126975/minikube_dashboard_0e027cdabd32d18e1757ed354235ff3cd1e2bdbc_0.log)

</details>

**Comment by spowelljr** [comment]
Hi @Fcscanf, thanks for reporting you issue with minikube!

Could you please run `minikube logs --file=logs.txt` and attach the log file to this issue, this will help us with the debugging process, thanks!

**Comment by Fcscanf** [comment]
Hi @spowelljr ,Thank you for checking, I have uploaded the log files related to the dashboard
![image](https://user-images.githubusercontent.com/27654200/132605166-5c608b8d-a23a-4936-9ca8-b843327aae82.png)

**Comment by spowelljr** [comment]
Hi @Fcscanf, I have read through all those logs but I need more information to be able to debug this problem. The `minikube logs` command contains additional logs that would help with this effort.

**Comment by Fcscanf** [comment]
Thank you for checking again, I have added the relevant log files under the comment。
![image](https://user-images.githubusercontent.com/27654200/132807449-1efa82a0-2d95-4641-8454-0a00bea2592d.png)

[minikube_logs_9246e7b09b9f13f7147fa2d5bfd173ecc73ec530_0.log](https://github.com/kubernetes/minikube/files/7141572/minikube_logs_9246e7b09b9f13f7147fa2d5bfd173ecc73ec530_0.log)

[minikube_logs_ccea95423134ea807ec8b2d6fdfa66ebc74176d6_0.log](https://github.com/kubernetes/minikube/files/7141574/minikube_logs_ccea95423134ea807ec8b2d6fdfa66ebc74176d6_0.log)

[minikube_dashboard_27014b127e5c6c9c95792ad751b8db0a7d7a54aa_0.log](https://github.com/kubernetes/minikube/files/7141570/minikube_dashboard_27014b127e5c6c9c95792ad751b8db0a7d7a54aa_0.log)

**Comment by spowelljr** [comment]
Hi @Fcscanf, thanks for uploading the logs, unfortunately there seems to be some issues.

1. Not an issue, but when you pass the `--file=logs.txt` it should should generate a `logs.txt` file in the dir you're running the command from and you can upload that instead of having to find the file in the `/tmp` dir.
2. You uploaded two files containing the output for `minikube logs`, the first one contains the `permission denied` error in the screenshot and doesn't actually contain any logs.
3. The second one contains some logs, but based on the output it looks like your minikube instance wasn't running when you ran the command and wasn't able to collect the pods logs which would be key to solving the error with the dashboard.
4. Further, based on the logs it says the last time you tried to start minikube it failed with the error `❌  Exiting due to DRV_AS_ROOT: The "docker" driver should not be used with root privileges.` But at the top of your screenshot I see that minikube successfully started. Did you try starting minikube in another terminal? From what I'm seeing the logs and the screenshot doesn't exactly match up.

What should generate the logs command correctly is starting minikube and then running `minikube logs` while minikube is running. So if you could try that and then upload the generated log file then I should have something I can work off of, thanks!

**Comment by Fcscanf** [comment]
Hi，@spowelljr,I am very glad that you responded to my question seriously. I have successfully output the relevant log files and upload them through `minikube logs` command.
[logs.txt](https://github.com/kubernetes/minikube/files/7149818/logs.txt)

Regarding what you see in my other logs and screenshots, the inconsistency is caused by my wrong operation. At the beginning, the wrong command may be used or the lack of commands did not start successfully, but I have dealt with these later and succeeded Minikube is started, but the log records them, so you don’t have to pay too much attention to them.

**Comment by spowelljr** [comment]
HI @Fcscanf, sorry for the delayed response, I took a look at this again and narrowed this error down to the `registry.cn-hangzhou.aliyuncs.com/google_containers` image repository.

It's failing to pull the `dashboard` & `metrics-scraper` images.

```
Sep 12 14:41:42 minikube dockerd[207]: time="2021-09-12T14:41:42.704465900Z" level=warning msg="reference for unknown type: " digest="sha256:555981a24f184420f3be0c79d4efb6c948a85cfce84034f85a563f4151a81cbf" remote="registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/metrics-scraper@sha256:555981a24f184420f3be0c79d4efb6c948a85cfce84034f85a563f4151a81cbf"
Sep 12 14:41:43 minikube dockerd[207]: time="2021-09-12T14:41:43.021427619Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Sep 12 14:41:43 minikube dockerd[207]: time="2021-09-12T14:41:43.021466566Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Sep 12 14:41:53 minikube dockerd[207]: time="2021-09-12T14:41:53.575347571Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Sep 12 14:41:53 minikube dockerd[207]: time="2021-09-12T14:41:53.575376426Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
Sep 12 14:41:55 minikube dockerd[207]: time="2021-09-12T14:41:55.364066229Z" level=warning msg="reference for unknown type: " digest="sha256:7f80b5ba141bead69c4fee8661464857af300d7d7ed0274cf7beecedc00322e6" remote="registry.cn-hangzhou.aliyuncs.com/google_containers/kubernetesui/dashboard@sha256:7f80b5ba141bead69c4fee8661464857af300d7d7ed0274cf7beecedc00322e6"
Sep 12 14:41:56 minikube dockerd[207]: time="2021-09-12T14:41:56.131675822Z" level=error msg="Not continuing with pull after error: errors:\ndenied: requested access to the resource is denied\nunauthorized: authentication required\n"
Sep 12 14:41:56 minikube dockerd[207]: time="2021-09-12T14:41:56.131703500Z" level=info msg="Ignoring extra error returned from registry: unauthorized: authentication required"
```

Looks like the resources require authentication, I'm not too sure why that is, the core minikube maintainers team doesn't actually manage the `registry.cn-hangzhou.aliyuncs.com/google_containers`, but I'll see if we can get in contact with them to see if they can resolve it on their end.

**Comment by spowelljr** [comment]
The version of minikube you were using is v1.20.0, but this seems to be resolved by using v1.24.0, try updating and let me know if your issue is resolved, thanks!

**Comment by Fcscanf** [comment]
@spowelljr  Thank you for your review and reply, I will let you know if the problem is solved after trying the new version, thank you!

**Comment by Fcscanf** [comment]
@spowelljr The mirror has been successfully pulled, thank you very much for your help!
![image](https://user-images.githubusercontent.com/27654200/147798325-3aee2557-bc9e-447f-87d7-65a6c5c76b6d.png)
