### ISSUE TITLE
Unknown error (404) the server could not find the requested resource (get ingresses.extensions)

### ISSUE THREAD

**Issue by rsanluis** [kubernetes/minikube#12438]
**Steps to reproduce the issue:** 

minikube version
minikube version: v1.23.0
commit: 5931455374810b1bbeb222a9713ae2c756daee10

macOS Big Sur version 11.5.2
Docker Desktop Version 4.0.0 (4.0.0.12)

1. minikube start
minikube start
😄  minikube v1.23.0 on Darwin 11.5.2
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > gcr.io/k8s-minikube/kicbase: 355.82 MiB / 355.82 MiB  100.00% 21.35 MiB p
🔥  Creating docker container (CPUs=2, Memory=1985MB) ...
🐳  Preparing Kubernetes v1.22.1 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
codified@codified-macpro ~ % minikube dashboard
🔌  Enabling dashboard ...
    ▪ Using image kubernetesui/dashboard:v2.1.0
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
🎉  Opening http://127.0.0.1:50511/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...

2. minikube dashboard
 
Unknown error (404)
the server could not find the requested resource (get ingresses.extensions)

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Incoming HTTP/1.1 GET /api/v1/settings/pinner request from 127.0.0.1:
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Incoming HTTP/1.1 GET /api/v1/settings/global request from 127.0.0.1:
2021/09/08 22:27:20 Getting application global configuration
2021/09/08 22:27:20 Application configuration {"serverTime":1631140040353}
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Incoming HTTP/1.1 GET /api/v1/plugin/config request from 127.0.0.1:
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Incoming HTTP/1.1 GET /api/v1/settings/global request from 127.0.0.1:
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Incoming HTTP/1.1 GET /api/v1/login/status request from 127.0.0.1:
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Incoming HTTP/1.1 GET /api/v1/systembanner request from 127.0.0.1:
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Incoming HTTP/1.1 GET /api/v1/login/status request from 127.0.0.1:
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Incoming HTTP/1.1 GET /api/v1/login/status request from 127.0.0.1:
2021/09/08 22:27:20 [2021-09-08T22:27:20Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/cronjob/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 Getting list of all cron jobs in the cluster
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/namespace request from 127.0.0.1:
2021/09/08 22:27:21 Getting list of namespaces
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/daemonset/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/deployment/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 Getting list of all deployments in the cluster
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/job/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 Getting list of all jobs in the cluster
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/pod/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 Getting list of all pods in the cluster
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/replicaset/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 Getting list of all replica sets in the cluster
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/ingress/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/replicationcontroller/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 Getting list of all replication controllers in the cluster
2021/09/08 22:27:21 Getting pod metrics
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/statefulset/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 Getting list of all pet sets in the cluster
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Incoming HTTP/1.1 GET /api/v1/service/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 127.0.0.1:
2021/09/08 22:27:21 Getting list of all services in the cluster
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
**2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 404 status code**
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code
2021/09/08 22:27:21 [2021-09-08T22:27:21Z] Outcoming response to 127.0.0.1 with 200 status code

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by spowelljr** [comment]
Hi @rsanluis, thanks for reporting your issue with minikube!

This is a known issue and we have someone working on the issue (#12424).

To keep all the information and conversation centralized I'm closing other issues and re-directing to #12424. Please feel free to contribute and follow along there, thank you for your understanding!
