### ISSUE TITLE
Unable to disable default-storageclass addon

### ISSUE THREAD

**Issue by Uvedale** [kubernetes/minikube#1244]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Minikube version** (use `minikube version`): v0.17.1

**Environment**:
- **OS** (e.g. from /etc/os-release): Arch Linux
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v1.0.7
- **Install tools**:
- **Others**:

**What happened**: I tried to disable the default-storageclass addon by typing:
```
minikube addons disable default-storageclass
```

**What you expected to happen**: 
The result to be:
```
 default-storageclass was successfully disabled
```
but I got:
```
Property name default-storageclass not found
```

**How to reproduce it** (as minimally and precisely as possible):
```
minikube addons disable default-storageclass
```

**Anything else do we need to know**:
That property is missing from the [config](https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/config/config.go)

**Comment by r2d4** [comment]
Yeah sorry about that. I'll add it

**Comment by r2d4** [comment]
I was having some trouble with the addon-manager not deleting the storageclass.  You can always turn off dynamic provisioning through the admission controller with the --extra-config flag

**Comment by dlorenc** [comment]
I just did some digging. It looks like the addon-manager won't prune storageclass objects: 
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/apply.go#L408

**Comment by r2d4** [comment]
Maybe we can do a custom callback to delete the storage class through client-go.
