### ISSUE TITLE
Improve "Minikube tunnel" when port is taken

### ISSUE THREAD

**Issue by noxora** [kubernetes/minikube#12459]
**Steps to reproduce the issue:** 

0. Kill minikube with a tunnel open
1. minikube start
2. kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4
3. kubectl expose deployment hello-node --type=LoadBalancer --port=8080

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

[logs.txt](https://github.com/kubernetes/minikube/files/7155965/logs.txt)

So I was testing the envoy-x509 example from SPIRE https://github.com/spiffe/spire-tutorials/tree/master/k8s/envoy-x509

in this testing, I deleted my minikube cluster (to tear down and set back up with different configuration) and I did this with `minikube tunnel` running in a different window in my terminal (I'm on MacOS). I don't know if that caused the issue, but after doing this a few times, ports stopped being opened. 

The tunnel spat out 
```E0913 10:59:35.061018    9261 ssh_tunnel.go:72] error listing services: Get "https://127.0.0.1:55548/api/v1/services": dial tcp 127.0.0.1:55548: connect: connection refused```

When I killed the cluster while it was open, which makes sense. 

The issue resolves itself by restarting my computer, but it is still frustrating to have to do so
</details>

**Comment by xavidram** [comment]
This issue is also related.
https://github.com/kubernetes/minikube/issues/12115

Been like this for a while now. Tunnel does work on Linux environments. Just not windows at the moment.

**Comment by sayantanu-dey** [comment]
Hi @noxora , I was trying to reproduce this issue on my linux machine, but failed to reproduce the error, 
what I did was - 
1. started minikube (`minikube start`)
2. created a deployment with loadbalancer
3. ran `minikube tunnel`
4. deleted minikube (`minikube delete`)
5. The tunnel stopped automatically after spitting connection refused errors. 
6. Then I repeated the above steps
Am I missing something?

**Comment by spowelljr** [comment]
Hi @sayantanu-dey, I tried the same and got the same result.

Since we haven't got a response from @noxora I'm going to close this issue since it was unreproducible by two of us.

If you're able to provide more details @noxora feel free to respond and reopen the issue, thanks!
