### ISSUE TITLE
request: cgroup v2 CI infra (for testing Rootless Docker driver)

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/minikube#12456]
Support for Rootless Docker with cgroup v2 was merged in https://github.com/kubernetes/minikube/pull/12359 , but not tested on CI.

We need a cgroup v2 CI infra to test the rootless docker driver (and eventually rootless podman driver too).

### cgroup v2 CI infra in other projects
-  `kind` uses Fedora 34 Vagrant box on macOS instances of GHA. Free and easy, but slow. https://github.com/kubernetes-sigs/kind/blob/4910c3e221a858e68e29f9494170a38e1c4e8b80/.github/workflows/cgroup2.yaml

-  runc uses Fedora 34 Vagrant box on Linux KVM instances of Cirrus CI. Free, easy, and relatively faster than GHA macOS. Needs to be set up by an admin of `github.com/kubernetes` organization. https://github.com/opencontainers/runc/blob/v1.0.2/.cirrus.yml#L23

- k/k uses Fedora CoreOS instances on GCP https://github.com/kubernetes/test-infra/blob/5c6d26134d55239241b6ce2ad231a5543696e0d7/jobs/e2e_node/crio/latest/image-config-cgrpv2.yaml

**Comment by afbjorklund** [comment]
@sharifelgamal ?

We talked about getting some Fedora infrastructure at _some_ point or other (see #3552)

It's needed for testing other strange setups, such as btrfs and whatever next they come up with

**Comment by fkorotkov** [comment]
Hey there, Cirrus CI founder here. With Cirrus you can use a [custom GCP VM image](https://cirrus-ci.org/guide/custom-vms/) (it's free for OSS). For example, [Podman is using a custom VM](https://github.com/containers/podman/blob/f38503a1a3336a87a950c1d97bf1cb9a1a883ada/.cirrus.yml#L32-L34) to test on Fedora. Just wanted to note these in case you'd prefer not to use Vagrant as a "middleman".

**Comment by AkihiroSuda** [comment]
> Hey there, Cirrus CI founder here. With Cirrus you can use a [custom GCP VM image](https://cirrus-ci.org/guide/custom-vms/) (it's free for OSS). For example, [Podman is using a custom VM](https://github.com/containers/podman/blob/f38503a1a3336a87a950c1d97bf1cb9a1a883ada/.cirrus.yml#L32-L34) to test on Fedora. Just wanted to note these in case you'd prefer not to use Vagrant as a "middleman".

Is Fedora (not Fedora CoreOS) image publicly available?

**Comment by fkorotkov** [comment]
> Is Fedora (not Fedora CoreOS) image publicly available?

They are not. The one publicly available are the CoreOS. Podman folks [seems do build a regular Fedora](https://github.com/containers/automation_images/blob/8522f112bf76ce1f9acb2abd06e5eb8a7682018a/base_images/gce.yml#L30) though.

**Comment by sharifelgamal** [comment]
Adding testing infra for Fedora is on our near term list of things to do. I'll use this issue to track it.

**Comment by sharifelgamal** [comment]
Update here, I ran our integration test suites on Ubuntu 21.10 with cgroupsv2 enabled, and we found a lot of general flakiness and instability. 

With regards to Fedora, we have the ability to spin up Fedora machines on GCP, but they do not support nested virtualization, which makes them of limited use to us.
