### ISSUE TITLE
Broken hyperlinks at https://minikube.sigs.k8s.io/docs/handbook/pushing

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/minikube#12478]
https://minikube.sigs.k8s.io/docs/handbook/pushing lists methods for uploading images:
1. docker-env command which is a hyperlink to https://minikube.sigs.k8s.io/docs/handbook/pushing/#1pushing-directly-to-the-in-cluster-docker-daemon-docker-env 
2. podman-env command, which is a hyperlink to https://minikube.sigs.k8s.io/docs/handbook/pushing/#3-pushing-directly-to-in-cluster-crio-podman-env .

and so on

These and the following hyperlinks do not work.  The correct hyperlinks would have been

https://minikube.sigs.k8s.io/docs/handbook/pushing/#1-pushing-directly-to-the-in-cluster-docker-daemon-docker-env

https://minikube.sigs.k8s.io/docs/handbook/pushing/#2-push-images-using-cache-command

https://minikube.sigs.k8s.io/docs/handbook/pushing/#3-pushing-directly-to-in-cluster-cri-o-podman-env

**Comment by spowelljr** [comment]
Thanks for bringing these issues to attention @dilyanpalauzov!

**Comment by lakshya8066** [comment]
I think I did something wrong, let me figure it out and create a new pull request 😅
