### ISSUE TITLE
Can not connect Kafka Producer or consumer using Minikube with locally installed Kafka cluster

### ISSUE THREAD

**Issue by PriyankaDasKafka** [kubernetes/minikube#12471]
I have a local kafka cluster. I have deployed my producer and consumer in minikube from where I am trying to access the local Kafka Topic I have created.(Kafka is not in Minikube). But even though both the applications are running in Kubernetes dashboard as healthy I can not see any consumer connected to the Kafka topic , neither can I produce message in the Kafka Topic. I have set advertised.listener as localhost:9092

 **My Producer Yaml is:**
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer-deployment
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: chamilaliyanage/keda-demo-kafka-producer
          imagePullPolicy: Never
          ports:
            - containerPort: 8090
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "localhost:29092"
            - name: KAFKA_ORDERS_TOPIC
              value: "FSMTest"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-producer-svc
  labels:
    app: kafka-producer
spec:
  type: NodePort
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 32000
      protocol: TCP
      name: http
  selector:
    app: kafka-producer

**My consumer yaml is:**

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer-deployment
  labels:
    app: kafka-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
        - name: kafka-consumer
          image: chamilaliyanage/keda-demo-kafka-consumer
          imagePullPolicy: Never
          env:
            - name: KAFKA_BOOTSTRAP_SERVER
              value: "localhost:29092"
            - name: KAFKA_ORDERS_TOPIC
              value: "FSMTest"

My Kafka information are:

     Name                Command              State               Ports         
--------------------------------------------------------------------------------
broker            /etc/confluent/docker/   Up             0.0.0.0:29092->29092/t
                  run                                     cp,:::29092->29092/tcp
                                                          , 0.0.0.0:9092->9092/t
                                                          cp,:::9092->9092/tcp, 
                                                          0.0.0.0:9101->9101/tcp
                                                          ,:::9101->9101/tcp    
connect           /etc/confluent/docker/   Up (healthy)   0.0.0.0:8083->8083/tcp
                  run                                     ,:::8083->8083/tcp,   
                                                          9092/tcp              
ksql-datagen      bash -c echo Waiting     Up                                   
                  for K ...                                                     
ksqldb-cli        /bin/sh                  Up                                   
ksqldb-server     /etc/confluent/docker/   Up             0.0.0.0:8088->8088/tcp
                  run                                     ,:::8088->8088/tcp    
rest-proxy        /etc/confluent/docker/   Up             0.0.0.0:8082->8082/tcp
                  run                                     ,:::8082->8082/tcp    
schema-registry   /etc/confluent/docker/   Up             0.0.0.0:8081->8081/tcp
                  run                                     ,:::8081->8081/tcp    
zookeeper         /etc/confluent/docker/   Up             0.0.0.0:2181->2181/tcp
                  run                                     ,:::2181->2181/tcp,   
                                                          2888/tcp, 3888/tcp    
[pdas@localhost kubectlfilesFSM]$ 

**My Kubectl informations are:**

[pdas@localhost kubectlfilesFSM]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.0", GitCommit:"c2b5237ccd9c0f1d600d3072634ca66cefdf272f", GitTreeState:"clean", BuildDate:"2021-08-04T18:03:20Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
WARNING: version difference between client (1.22) and server (1.20) exceeds the supported minor version skew of +/-1

**Comment by PriyankaDasKafka** [comment]
> access my Producer Service from browser or postman. It gives error as
> **Resource not found**.

oduce any

**Comment by sharifelgamal** [comment]
Your ability to access resources outside of minikube, on your local machine, depends on what OS and minikube driver you're using. We don't currently have any documentation on how that works, but we're working on adding it.
