### ISSUE TITLE
docs/handbook/pushing : reorder the content

### ISSUE THREAD

**Issue by dilyanpalauzov** [kubernetes/minikube#12477]
At https://minikube.sigs.k8s.io/docs/handbook/pushing/ the top lists methods to upload images:

1. docker-env command
2. podman-env command
3. ctr/buildctl command

Afterwards the methods are described in more detail in the order:
1. Pushing directly to the in-cluster Docker daemon (docker-env)
2. Push images using ‘cache’ command.
3. Pushing directly to in-cluster CRI-O. (podman-env)

The order of the methods at the top, shall be the same as the order, in which the methods are described in more detail.

**Comment by spowelljr** [comment]
Thanks for bringing these issues to attention @dilyanpalauzov!
