### ISSUE TITLE
Debian installation instructions problematic

### ISSUE THREAD

**Issue by oliversalzburg** [kubernetes/minikube#12486]
The minikube installation instructions don't lead to a good experience on Debian.

```shell
oliver@oliver-work:~$ minikube start
😄  minikube v1.23.0 on Debian 11.0
👎  Unable to pick a default driver. Here is what was considered, in preference order:
    ▪ docker: Not healthy: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    ▪ docker: Suggestion: Start the Docker service <https://minikube.sigs.k8s.io/docs/drivers/docker/>
    ▪ kvm2: Not installed: exec: "virsh": executable file not found in $PATH
    ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH
    ▪ podman: Not healthy: "sudo -k -n podman version --format {{.Version}}" exit status 1: sudo: a password is required
    ▪ podman: Suggestion: Add your user to the 'sudoers' file: 'oliver ALL=(ALL) NOPASSWD: /usr/bin/podman' <https://podman.io>
    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH

❌  Exiting due to DRV_DOCKER_NOT_RUNNING: Found docker, but the docker service isn't running. Try restarting the docker service.
```

The system this is being run on has a valid installation of `podman` and the user calling `minikube start` is already in the sudoers file with exactly the syntax noted in the command, yet it fails.

The output indicates that it's calling `sudo -k` for some reason. This explicitly will require the user to provide a password, ignoring the sudoers configuration.

```shell
oliver@oliver-work:~$ cat /etc/*-release
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Steps to reproduce the issue:** 

1. `minikube start`

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by afbjorklund** [comment]
The idea behind -k is just so that it wouldn't reuse credentials from an existing session, only to fail half-way through.

Currently minikube expects podman to be set up using password less `sudo`, this might change for rootless podman.

**Comment by afbjorklund** [comment]
Does `sudo -k -n podman` work ? Does `sudo -l` show the right commands ? Is it matching the path of `which podman` ?

**Comment by oliversalzburg** [comment]
Apologies. I missed the part in the documentation where it says "Be sure this text is after #includedir /etc/sudoers.d."
