### ISSUE TITLE
Clean Debian/OSX install has broken dashboard

### ISSUE THREAD

**Issue by rjhuijsman** [kubernetes/minikube#12498]
Simply following [the getting started instructions](https://minikube.sigs.k8s.io/docs/start/) on a clean system seems to result in a broken dashboard installation.

**Steps to reproduce the issue:** 

Tested on a clean Debian VM (Google Cloud image `debian-10-buster-v20210915`) and on a very-not-clean Mac OS X 11.6. Same results.

0. Make sure you have Docker installed
```
$ docker --version
Docker version 20.10.8, build 3967b7d
```

1. Install minikube per the [instructions](https://minikube.sigs.k8s.io/docs/start/) - using Debian image on Debian, or binary on Mac.

2. Start minikube per the [instructions](https://minikube.sigs.k8s.io/docs/start/):
```
$ minikube start
😄  minikube v1.23.0 on Debian 10.10 (amd64)
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
🐳  Preparing Kubernetes v1.22.1 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```
3. See your healthy cluster per the [instructions](https://minikube.sigs.k8s.io/docs/start/):
```
$ minikube kubectl -- get po -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-78fcd69978-cgvkx           1/1     Running   0          2m34s
kube-system   etcd-minikube                      1/1     Running   0          2m48s
kube-system   kube-apiserver-minikube            1/1     Running   0          2m47s
kube-system   kube-controller-manager-minikube   1/1     Running   0          2m47s
kube-system   kube-proxy-6pdjm                   1/1     Running   0          2m35s
kube-system   kube-scheduler-minikube            1/1     Running   0          2m47s
kube-system   storage-provisioner                1/1     Running   0          2m46s
```
4. Run the dashboard per the [instructions](https://minikube.sigs.k8s.io/docs/start/):
```
$ minikube dashboard
🔌  Enabling dashboard ...
    ▪ Using image kubernetesui/dashboard:v2.1.0
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
🎉  Opening http://127.0.0.1:44401/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
👉  http://127.0.0.1:44401/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/
```
5. Click the link. Be greeted with a broken dashboard like so:
<img width="1227" alt="Screen Shot 2021-09-16 at 2 51 39 PM" src="https://user-images.githubusercontent.com/22160949/133692615-e619e007-6c3c-4e8e-bb8e-3470c94067ed.png">

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
[logs.txt](https://github.com/kubernetes/minikube/files/7181241/logs.txt)

**Full output of failed command if not `minikube start`:**
No commands failed outright, but see screenshot above.

**Final thoughts**
I appreciate your investigation! Thanks!

**Comment by spowelljr** [comment]
Hi @rjhuijsman, thanks for reporting your issue with minikube!

minikube v1.23.0 has an ingress regression, please try updating to v1.23.1 and trying again and see if that solves your issue.

**Comment by rjhuijsman** [comment]
Yup, upgrading to v1.23.1 did the trick! Glad you already had that release ready to go! Thanks!
