### ISSUE TITLE
Minikube podman-env does not work with podman 3.1

### ISSUE THREAD

**Issue by VeitSanner** [kubernetes/minikube#12504]
**Steps to reproduce the issue:** 

1. Execute `eval $(minikube -p minikube podman-env)`.
2. Execute `podman-remote build -t example:latest .`

**Full output of failed command if not `minikube start`:**
```text
Error: cannot connect to the Podman socket, please verify that Podman REST API service is running: server API version is too old. Client "3.1.0" server "2.0.0"
```
<details>
Operating System: macOS 11.6

Podman Version:
```text
Client:
Version:      3.3.1
API Version:  3.3.1
Go Version:   go1.17
Built:        Mon Aug 30 21:15:26 2021
OS/Arch:      darwin/amd64
```

minikube version
```text
minikube version: v1.23.0
commit: 5931455374810b1bbeb222a9713ae2c756daee10
```
</details>

**Comment by afbjorklund** [comment]
You need to install the older podman-remote version, or run podman over ssh, until the podman version has been updated (PR)

Podman is not backwards compatible, so you need multiple clients (podman1, podman2, podman3, podman4 etc)

**Comment by afbjorklund** [comment]
You can also use `minikube image build` instead.

**Comment by dilyanpalauzov** [comment]
You could try `podman --remote` instead of `podman-remote`.

**Comment by afbjorklund** [comment]
> You could try `podman --remote` instead of `podman-remote`.

That would have the same effect, but could be a good idea anyway.

Hopefully the `podman-remote` binary will go away in the future, and the `--remote` flag will be automatic.
Right now it is needed on Linux, but not on macOS/Windows. Which makes instructions rather confusing.

**Comment by afbjorklund** [comment]
Anyway, the needed podman client binaries can be downloaded here:

https://github.com/containers/podman/releases/tag/v2.2.1

**Comment by dilyanpalauzov** [comment]
I mean, the user might have different versions behind `podman-remote` and `podman`.

**Comment by VeitSanner** [comment]
I have installed `podman` and `podman-remote` via `brew`. So both binaries are fairly up-to-date with versions `3.3.1`. 

As far as I can see, PR #11727 seems to be pretty close to be complete. Is there an ETA when the fix would be available?

Until then I can work with `minikube image build`.
