### ISSUE TITLE
Error appear enabling minikube ingress addon.

### ISSUE THREAD

**Issue by cpinochet** [kubernetes/minikube#12538]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>
carlos@carlos-Inspiron-5558:~ $ minikube start
😄  minikube v1.23.0 en Linuxmint 20.1
🎉  minikube 1.23.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.23.1
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🐳  Preparando Kubernetes v1.22.1 en Docker 20.10.8...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Complementos habilitados: default-storageclass, storage-provisioner

❗  /home/carlos/Descargas/google-cloud-sdk/bin/kubectl is version 1.18.18-dispatcher, which may have incompatibilites with Kubernetes 1.22.1.
    ▪ Want kubectl v1.22.1? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

</details>
[logs.txt](https://github.com/kubernetes/minikube/files/7204423/logs.txt)

[minikube_logs_5488fedf0ab159f35d5314ef013f295e2579a129_0.log](https://github.com/kubernetes/minikube/files/7204433/minikube_logs_5488fedf0ab159f35d5314ef013f295e2579a129_0.log)
[minikube_addons_d7bf01f8264d29a2149445846b5104a94fa94498_0.log](https://github.com/kubernetes/minikube/files/7204434/minikube_addons_d7bf01f8264d29a2149445846b5104a94fa94498_0.log)

**Comment by medyagh** [comment]
@cpinochet this is a known regression that was fixed in the 1.23.1 patch would u please try the latest version fo minikube ?
https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md#version-1231---2021-09-17



/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Fixed, sorry about that

**Comment by cpinochet** [comment]
Hi Guys, sorry for my late answer. I don-tg cvisit github many often. I don-t have this issue anymore. I remember I moved to a GKE cluster to do my tests. Anyway thankd for yor reply and concern. Be safe. Peace.
