### ISSUE TITLE
Additional Option for registry-creds

### ISSUE THREAD

**Issue by Teddy-Schmitz** [kubernetes/minikube#1253]
I would like to add an additional config option to the addon setup prompts that show up when you enable registry-creds.  Specifically I would like the option to set the gcr-url to something other then the default without having to edit the replication controller.

I'm happy to do a PR on this if thats ok.

**Comment by aaron-prindle** [comment]
We will gladly accept a PR for this.  Currently the gcr-url is a CLI arg into the addon:
https://github.com/upmc-enterprises/registry-creds/blob/master/main.go#L57

The code for the prompt to input parameters into the addon is here:
https://github.com/kubernetes/minikube/blob/9b539db1ff2d08fcae34e13b465ee0ea58af5b8b/cmd/minikube/cmd/config/util.go#L121

You should be able to edit the addon to take a Config Map that passes the gcr-url parameter as a command line arg:
https://kubernetes.io/docs/user-guide/configmap/

**Comment by Teddy-Schmitz** [comment]
Great, I'll start with adding the config map option to the addon.
