### ISSUE TITLE
not able to connect to internet from minikube pods

### ISSUE THREAD

**Issue by debimishra89** [kubernetes/minikube#12549]
**Steps to reproduce the issue:** 

1. curl -LO https://storage.googleapis.com/minikube/releases/v1.21.0/minikube-linux-amd64
2.  sudo install minikube-linux-amd64 /usr/local/bin/minikube
3. minikube start --addons=ingress --vm=true --memory=8192 --driver=none

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

PODs of this minikube cluster are not able to connect to internet.

![image](https://user-images.githubusercontent.com/84674037/134395898-89509699-b2eb-4757-a106-0294a4d82173.png)

However My host VM has internet connection with no firewall or iptables setup.

cluster info
![image](https://user-images.githubusercontent.com/84674037/134397503-1b7e6269-0a10-403f-b84e-908206e0110c.png)

</details>
[logs.txt](https://github.com/kubernetes/minikube/files/7212799/logs.txt)

**Comment by spowelljr** [comment]
Hi @debimishra89, this works for me using minikube v1.24.0 on Linux using the kvm2 driver. Could you try upgrading to the latest version of minikube and see if you issue is resolved? If not I'm going to assume this is an error specific to the none driver.

**Comment by spowelljr** [comment]
Hi @debimishra89, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
