### ISSUE TITLE
Can not configure RBAC rules

### ISSUE THREAD

**Issue by markgarrigan** [kubernetes/minikube#12548]
1. brew install docker
2. brew install hyperkit
3. brew install minikube
4. minikube start  --driver=hyperkit --container-runtime=docker

minikube logs --file=logs.txt
🤷  The control plane node must be running for this command
👉  To start a cluster, run: "minikube start"

**Full output of failed command if not `minikube start`:**
<details>
😄  minikube v1.23.2 on Darwin 10.15.7
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=6, Memory=12288MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.22.2 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...| E0922 09:05:43.002060   45328 start.go:142] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
🌟  Enabled addons: storage-provisioner
</details>

**Comment by markgarrigan** [comment]
More context...

I'm on a corporate Mac. If i'm on the VPN I can't get past the Creating hyperkit VM part. It just timesout. If I disable the VPN I get past that then it hangs on trying to configure RBAC. When I disable my VPN that also disables my users admin rights on my machine and I can't do anything about that.

**Comment by spowelljr** [comment]
Hi @markgarrigan, thanks for reporting your issue with minikube!

I know you ran `minikube logs --file=logs.txt` and it output `🤷 The control plane node must be running for this command`, but it actually still creates a log file. Could you run that again and attach it to this issue, thanks!

**Comment by klaases** [comment]
Hi @markgarrigan, did you have a chance to respond to @spowelljr's suggestion? Are you still experiencing this issue?

**Comment by markgarrigan** [comment]
@spowelljr and @klaases 

I haven't looked at this in a while. After this I started looking at more docker alternatives and I'm currently pleased with my Rancher Desktop + nerdctl + kim set up.

**Comment by spowelljr** [comment]
No problem @markgarrigan, if you come back to this feel free to reopen this issue, thanks!
