### ISSUE TITLE
crio.conf empty with Docker driver

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#12552]
Since updating cri-o from 1.20 to 1.22 (#12425) the `/etc/crio/crio.conf` file is empty when using the Docker driver.

**Comment by afbjorklund** [comment]
Maybe bug in the OBS package ?

**Comment by afbjorklund** [comment]
It was a change in cri-o, not listing default configuration...

It is being reverted for 1.22, but maybe a good idea to move to /etc/crio.conf.d anyway ?

**Comment by spowelljr** [comment]
@afbjorklund Will the `crio.conf` file being empty affect us in anyway?

**Comment by afbjorklund** [comment]
I think we try to change things (using `sed`), so that fails...

**Comment by spowelljr** [comment]
See how soon crio is going to revert this and then decide from there

**Comment by medyagh** [comment]
The recommendation to have a generic config template and if the installed  crio doesn not have config, we should geneate one
