### ISSUE TITLE
minikube start returned error no such file while the file exists

### ISSUE THREAD

**Issue by MrJackQiao** [kubernetes/minikube#12557]
I am trying to setup https://github.com/ostenbom/refunction. 
```
minikube start \
    --driver=docker \
    --container-runtime=containerd \
    --network-plugin=cni \
    --enable-default-cni \
    --cri-socket=/tmp/refunction.sock \
    --extra-config=kubelet.container-runtime=remote \
    --extra-config=kubelet.container-runtime-endpoint=unix:///tmp/refunction.sock \
    --extra-config=kubelet.image-service-endpoint=unix:///tmp/refunction.sock
```
The error I got was
```
Exiting due to RUNTIME_ENABLE: stat /tmp/refunction.sock: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/tmp/refunction.sock': No such file or directory
```

I am sure the file /tmp/refunction.sock exists and I can run `stat /tmp/refunction.sock` myself in command line
```
  File: /tmp/refunction.sock
  Size: 0         	Blocks: 0          IO Block: 4096   socket
Device: 803h/2051d	Inode: 126222423   Links: 1
Access: (0755/srwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2021-09-22 19:30:57.987148609 -0400
Modify: 2021-09-22 18:53:17.550758729 -0400
Change: 2021-09-22 18:53:17.550758729 -0400
 Birth: -
```

Below is the full error log from lastStart.txt

[lastStart.txt](https://github.com/kubernetes/minikube/files/7214424/lastStart.txt)

**Comment by klaases** [comment]
Hi @ MrJackQiao – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
