### ISSUE TITLE
Cannot start Minikube on Windows 10

### ISSUE THREAD

**Issue by Monte-Christo** [kubernetes/minikube#12560]
**Steps to reproduce the issue:** 

1. minikube start --network-plugin=cni --cni=calico
2. Errors are thrown right and left

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

- Windows version: 20H2, build 19042.1165
- Docker version 4.0.1, WSL2

[logs.txt](https://github.com/kubernetes/minikube/files/7219102/logs.txt)

**Comment by spowelljr** [comment]
Hi @Monte-Christo, thanks for reporting your issue with minikube!

It seems your running into a known configuration issue.

Try running the following to reset minikube to a fresh state and then try starting minikube again and let me know if it works:
```
$ minikube delete --all --purge
```

**Comment by Monte-Christo** [comment]
Thank you, that worked. In the meantime, I had figured out another way by myself: stop minikube, then first run only "minikube start --network-plugin=cni", then, when that succeeded, stop minikube again and start the whole cahuna. Should i close this issue, or does it require actions on your part to resolve?

**Comment by spowelljr** [comment]
I can close the issue for you, here's the issue for reference https://github.com/kubernetes/minikube/issues/8765, we'll fix this issue when we have the bandwidth to do so.

Thanks for using minikube!
