### ISSUE TITLE
Get this error while installing Minikube on my AWS EC2 instance

### ISSUE THREAD

**Issue by Mjahannivas** [kubernetes/minikube#12575]
minikube start --force --driver=docker
😄  minikube v1.23.2 on Ubuntu 20.04
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
✨  Using the docker driver based on existing profile
🛑  The "docker" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
💡  Tip: To remove this root owned cluster, run: sudo minikube delete
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
❗  The image 'k8s.gcr.io/kube-scheduler:v1.23.2' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/kube-controller-manager:v1.23.2' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/kube-apiserver:v1.23.2' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/kube-proxy:v1.23.2' was not found; unable to add it to cache.
🐳  Preparing Kubernetes v1.23.2 on Docker 20.10.8 ...
❌  Unable to load cached images: loading cached images: stat /root/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.23.2: no such file or directory

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.23.2/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.23.2/bin/linux/amd64/kubectl.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.23.2/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.23.2/bin/linux/amd64/kubectl.sha256 Dst:/root/.minikube/cache/linux/v1.23.2/kubectl.download Pwd: Mode:2 Umask:---------- Detectors:[0x34559c0 0x34559c0 0x34559c0 0x34559c0 0x34559c0 0x34559c0 0x34559c0] Decompressors:map[bz2:0x34559c0 gz:0x34559c0 tar:0x34559c0 tar.bz2:0x34559c0 tar.gz:0x34559c0 tar.xz:0x34559c0 tar.zst:0x34559c0 tbz2:0x34559c0 tgz:0x34559c0 txz:0x34559c0 tzst:0x34559c0 xz:0x34559c0 zip:0x34559c0 zst:0x34559c0] Getters:map[file:0xc000e4fac0 http:0xc0012ee840 https:0xc0012ee860] Dir:false ProgressListener:0x3417550 Insecure:false Options:[0x1830280]}: invalid checksum: Error downloading checksum file: bad response code: 404

E0925 13:11:21.666737   55759 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.23.2/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.23.2/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: /var/lib/minikube/binaries/v1.23.2/kubectl: command not found
 output: "\n** stderr ** \nsudo: /var/lib/minikube/binaries/v1.23.2/kubectl: command not found\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

**Comment by afbjorklund** [comment]
You can try pulling the images manually, see if you get more verbose errors ?

```console
$ docker pull k8s.gcr.io/pause:3.5
3.5: Pulling from pause
Digest: sha256:1ff6c18fbef2045af6b9c16bf034cc421a29027b800e4f9b68ae9b1cb3e9ae07
Status: Image is up to date for k8s.gcr.io/pause:3.5
k8s.gcr.io/pause:3.5
```

Don't run as root.

**Comment by Mjahannivas** [comment]
> You can try pulling the images manually, see if you get more verbose errors ?
> 
> ```
> $ docker pull k8s.gcr.io/pause:3.5
> 3.5: Pulling from pause
> Digest: sha256:1ff6c18fbef2045af6b9c16bf034cc421a29027b800e4f9b68ae9b1cb3e9ae07
> Status: Image is up to date for k8s.gcr.io/pause:3.5
> k8s.gcr.io/pause:3.5
> ```
> 
> Don't run as root.



getting this following issue while installing Promethues operator using helm(mini kube)

helm install --name my-release stable/prometheus-operator
Error: unknown flag: --name
