### ISSUE TITLE
Error when trying to run minikube with podman machine

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#12581]
Something is different between `podman` and `podman-remote` (podman machine):

`Error: error preparing container cc26ed492ddbd1f0f4dac495e4c64a3bc29c246d00c246c2df58ca87ea6e66ba for attach: error configuring network namespace for container cc26ed492ddbd1f0f4dac495e4c64a3bc29c246d00c246c2df58ca87ea6e66ba: error adding pod minikube-preload-sidecar_minikube-preload-sidecar to CNI network "podman": unexpected end of JSON input`

**Comment by afbjorklund** [comment]
Never mind, this was a bug in podman when it tried to read the **docker** config

**Comment by afbjorklund** [comment]
The bug is related to the new "podman-machine" CNI plugin, in the network

**Comment by afbjorklund** [comment]
Editing /etc/cni/net.d/minikube.conflist to remove "podman-machine" makes it limp along

Downgrading the Fedora CoreOS image (and thus podman version) should also work...

**Comment by afbjorklund** [comment]
Possible workaround:

```
podman machine ssh
[root@localhost ~]# rpm-ostree install podman-machine-cni
```

**Comment by jorhett** [comment]
Seems you can just recreate the machine. This worked for me https://stackoverflow.com/a/69626738/3078154
