### ISSUE TITLE
 Error starting cluster: kubeadm init timed out in 10 minutes

### ISSUE THREAD

**Issue by maheshsmc5** [kubernetes/minikube#12582]
**Steps to reproduce the issue:** 

1.trying to start minikube start command, Below is the output.
# minikube start
* minikube v1.23.2 on Centos 7.9.2009
* Using the none driver based on existing profile

X The requested memory allocation of 2200MiB does not leave room for system overhead (total system memory: 3020MiB). You may face stability issues.
* Suggestion: Start minikube with less memory allocated: 'minikube start --memory=2200mb'

* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is CentOS Linux 7 (Core)
E0926 22:24:44.354161   84281 docker.go:131] "Failed to enable" err="sudo systemctl enable docker.socket: exit status 1\nstdout:\n\nstderr:\nFailed to execute operation: No such file or directory\n" service="docker.socket"
* Preparing Kubernetes v1.22.2 on Docker 1.13.1 ...
! initialization failed, will try again: kubeadm init timed out in 10 minutes
*
X Error starting cluster: kubeadm init timed out in 10 minutes
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

X Exiting due to GUEST_START: kubeadm init timed out in 10 minutes
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

2. Next check the status, below is the results.
 minikube status
minikube
type: Control Plane
host: Stopped
kubelet: Stopped
apiserver: Stopped
kubeconfig: Stopped

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

Output  for the above command -->**Run `minikube logs --file=logs.txt` 
]# minikube logs --file=logs.txt
* The control plane node must be running for this command
  To start a cluster, run: "minikube start"

minikube version: v1.23.2

Below is the Kubectl version results.

 kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.2", GitCommit:"8b5a19147530eaac9476b0ab82980b4088bbc1b2", GitTreeState:"clean", BuildDate:"2021-09-15T21:38:50Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 192.168.190.130:8443 was refused - did you specify the right host or port?

Can some one plz have a look into the issue please?

**Comment by maheshsmc5** [comment]
closing the issue, due to my problem was solved from other sources

**Comment by makezhonguogreatagain** [comment]
> closing the issue, due to my problem was solved from other sources

i come across the same problem could you tell me how to solve it ?

**Comment by piatkiewicz** [comment]
This issue is the first link from google when you search for "Error starting cluster: kubeadm init timed out in 10 minutes" - please provide some reference or remove this issue
