### ISSUE TITLE
mount: /sys: permission denied.: container exited unexpectedly

### ISSUE THREAD

**Issue by darman96** [kubernetes/minikube#12583]
**Steps to reproduce the issue:** 

Fresh virtual Ubuntu server hosted by Strato.
I have docker installed and ran following command:

`minikube start --driver=docker --container-runtime=containerd`

**Fails with:**
<details>
2021-09-26T19:31:14.995807552Z  INFO: remounting /sys read-only
2021-09-26T19:31:14.995814418Z  + mount -o remount,ro /sys
2021-09-26T19:31:15.001984066Z  mount: /sys: permission denied.: container exited unexpectedly
</details>

The full log is in the attached file.
[minikube-logs.txt](https://github.com/kubernetes/minikube/files/7232119/minikube-logs.txt)

**Comment by afbjorklund** [comment]
Is this a real VM, or kind of LXC solution ?

`virtualization: openvz guest`

Nested containerization currently doesn't work, and it would be containerd-in-docker-in-openvz if it did...

See  #7957 and #8167 (use "none" driver)

**Comment by darman96** [comment]
I guess it's a real VM but I don't know what strato uses for virtualization.

**Comment by afbjorklund** [comment]
According to the Go "ps" output, it uses OpenVZ: https://openvz.org/

**Comment by darman96** [comment]
I see, thanks.

So as you mentioned in the other issue would using kubeadm be possible inside a OpenVZ container?

**Comment by afbjorklund** [comment]
As long as you can make a container runtime work inside it, that should be possible (in theory).

We were eventually able to hack both docker and podman to allow it, but with systemd it's a pain...

**Comment by darman96** [comment]
I know that docker works, was using docker-compose before.

**Comment by afbjorklund** [comment]
See here, for the full list of requirements:

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by spowelljr** [comment]
Hi @darman96, we haven't heard back from you in a while, so I'm going to close this issue. But if you have more questions feel free to re-open the issue, thanks!
