### ISSUE TITLE
iproute2 support

### ISSUE THREAD

**Issue by mindfulmonk** [kubernetes/minikube#1262]
Currently minikube depends on net-tools on Linux for setting up the routes.
net-tools have been deprecated on multiple Linux distributions in favour of iproute2.
What would be involved in getting iproute2 support?

This is related to https://github.com/kubernetes/minikube/issues/549

**Comment by r2d4** [comment]
I think somewhere we use `netstat -tln` to check if the docker daemon is up and running.  This used to be called in `WaitForDocker` but I don't think we actually call that anymore.  So I'm not even sure this is an actual dependency on linux anymore.

**Comment by mindfulmonk** [comment]
Had to install net-tools on Arch Linux to get access, so I think it's still a dependency.

**Comment by r2d4** [comment]
What driver are you using?  KVM or virtualbox?

**Comment by mindfulmonk** [comment]
Virtualbox

**Comment by r2d4** [comment]
The dependency is coming from `netstat` that is used to check for the docker daemon listening. 
 We should change this to use `ss` from the `iptables2` package. 
 
https://github.com/docker/machine/blob/e095e1d031301d6668bd6c34cb5d62f71ca2dd7e/libmachine/provision/utils.go#L254-L266

**Comment by r2d4** [comment]
Sorry, my last two comments weren't correct.  The dependency is actually from virtualbox, which requires net-tools.  You can get around this by using the KVM driver https://github.com/kubernetes/minikube/blob/master/DRIVERS.md#kvm-driver

I don't think there is really much we can do here in minikube.

https://bugs.archlinux.org/task/28856

**Comment by mindfulmonk** [comment]
Thanks for the explanation. I tried looking into virtualbox and iproute2, but couldn't find any info about future plans to support it. 

I agree, there is little benefit to reimplement adding routes in minikube itself.
