### ISSUE TITLE
What URLs are used to download minikube base images?

### ISSUE THREAD

**Issue by s0mb3x** [kubernetes/minikube#12633]
In our company we have strict firewall rules, basically we cannot download anything that is not whitelisted.
Unfortunately I haven't found any information about the URLs minikube is using to download its dependencies.
So I wanted to ask if you could please provide some information about those addresses, so we can maybe whitelist them in our firewall.
We do not use a proxy, so proxy configuration as mentioned in https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/ is not applicable.

I'm not able to provide logs from our environment, but basically minikube says it cannot download certain images / binaries.

Thank you!

**Steps to reproduce the issue:** 

1. Company firewall blocks everything, except whitelisted domains
2. `minikube start`
3. minkube cannot download a single dependency/image/binary

**Comment by spowelljr** [comment]
Hi @s0mb3x, I'll list the URLs below.

https://storage.googleapis.com
This is where we download our Kubernetes preloads and VM boot images.

https://github.com
This is where we download our machine drivers such as hyperkit & kvm.

https://gcr.io
https://k8s.gcr.io
https://docker.io
These are the repositories that we download container images from.

These URLS are where at least 99% of the downloading occurs, it's possible I missed a stray link, but this should cover the majority of it.

**Comment by s0mb3x** [comment]
Hey @spowelljr,

thank you very much!
With the provided list I was able to whitelist the URLs.
minikube is able to pull all dependencies and is now starting just fine!
