### ISSUE TITLE
new issue

### ISSUE THREAD

**Issue by SurajNarayan94** [kubernetes/minikube#12645]
! StartHost failed, but will try again: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...- E1003 22:52:21.627900    4528 main.go:126] libmachine: [stderr =====>] : Hyper-V\Get-VMSwitch : Hyper-V encountered an error trying to access an object on computer 'DESKTOP-MLVU2RA' because the object
was not found. The object might have been deleted. Verify that the Virtual Machine Management service on the computer is running.
At line:1 char:69
+ ...  [Text.Encoding]::UTF8; ConvertTo-Json @(Hyper-V\Get-VMSwitch|Select  ...
+                                              ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMSwitch

* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/
*

**Comment by Rits333** [comment]
Hey, @SurajNarayan94  can you elaborate on the issue so I can help you out.

**Comment by spowelljr** [comment]
Hi @SurajNarayan94, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
