### ISSUE TITLE
Using `~` in `--ssh-key` causes `SSH key does not exist`

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#12659]
```
$minikube start ... --ssh-key=~/.ssh/id_rsa
...
🤦  StartHost failed, but will try again: creating host: create: precreate: SSH key does not exist: "~/.ssh/id_rsa"
```

The weird quirk is this only occurs if you use an `=` between the key pair, if you use a space your terminal will rewrite to the absolute path.
```
$ echo ~/.ssh
/Users/user/.ssh

$ echo --ssh-key=~/.ssh
--ssh-key=~/.ssh
```

We should update the ssh-key value with the absolute path if we detect a `~`.

**Comment by marcvelasco** [comment]
Can I take a look at this one?
/assign

**Comment by spowelljr** [comment]
@marcvelasco Yup, go ahead!
