### ISSUE TITLE
I cannot enable Ingress addons

### ISSUE THREAD

**Issue by vanimarcos** [kubernetes/minikube#12669]
Reproduce this behavior execute -> minikube addons enable ingress

[logs.txt](https://github.com/kubernetes/minikube/files/7297755/logs.txt)

**Comment by sharifelgamal** [comment]
Hey @vanimarcos, can you please try upgrading to minikube v1.24.0, deleting your existing cluster and trying again? If you continue to have issues, feel free to reopen this issue.
