### ISSUE TITLE
Unable to install Minikube with vmware Drivers

### ISSUE THREAD

**Issue by amitsalunkhe21** [kubernetes/minikube#12673]
Commenad run # minikube start --driver vmware
Post running this command even after sufficent respurces  VM not getting created is the error seen on the og stats.

**Run `minikube logs attached.

Following are the few lines for the logs getting generated while runnig minikube start command- Please help.

logs as followings

* Log file created at: 2021/10/07 13:49:21
Running on machine: MUM-L-00062300
Binary: Built with gc go1.17.1 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1007 13:49:21.863848   16560 out.go:298] Setting OutFile to fd 84 ...
I1007 13:49:21.865512   16560 out.go:345] TERM=,COLORTERM=, which probably does not support color
I1007 13:49:21.865512   16560 out.go:311] Setting ErrFile to fd 88...
I1007 13:49:21.865512   16560 out.go:345] TERM=,COLORTERM=, which probably does not support color
I1007 13:49:21.881035   16560 out.go:305] Setting JSON to false
I1007 13:49:21.887710   16560 start.go:111] hostinfo: {"hostname":"MUM-L-00062300","uptime":98222,"bootTime":1633496539,"procs":268,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"10.0.18363 Build 18363","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"ec4a7f6d-d8f4-44c8-80b2-b78c034d469e"}
W1007 13:49:21.887894   16560 start.go:119] gopshost.Virtualization returned error: not implemented yet
I1007 13:49:21.891163   16560 out.go:177] * minikube v1.23.2 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
I1007 13:49:21.891222   16560 notify.go:169] Checking for updates...
I1007 13:49:21.891746   16560 config.go:177] Loaded profile config "minikube": Driver=vmware, ContainerRuntime=docker, KubernetesVersion=v1.22.2
W1007 13:49:21.892273   16560 start.go:659] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I1007 13:49:21.892273   16560 driver.go:343] Setting default libvirt URI to qemu:///system
W1007 13:49:21.892884   16560 start.go:659] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I1007 13:49:21.916291   16560 out.go:177] * Using the vmware driver based on existing profile
I1007 13:49:21.916613   16560 start.go:278] selected driver: vmware
I1007 13:49:21.916613   16560 start.go:751] validating driver "vmware" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.23.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:vmware HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.22.2 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0}
I1007 13:49:21.916613   16560 start.go:762] status for vmware: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I1007 13:49:24.932912   16560 cni.go:93] Creating CNI manager for ""
I1007 13:49:24.933019   16560 cni.go:167] CNI unnecessary in this configuration, recommending no CNI
I1007 13:49:24.933040   16560 start_flags.go:278] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.23.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:vmware HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.22.2 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0}
I1007 13:49:24.933040   16560 iso.go:123] acquiring lock: {Name:mk5904f54f6115c940a28bba147ca3de8caef0c6 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1007 13:49:24.939738   16560 out.go:177] * Starting control plane node minikube in cluster minikube
I1007 13:49:24.939832   16560 preload.go:131] Checking if preload exists for k8s version v1.22.2 and runtime docker
I1007 13:49:24.940450   16560 preload.go:147] Found local preload: C:\Users\a.salunkhe\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v13-v1.22.2-docker-overlay2-amd64.tar.lz4
I1007 13:49:24.940450   16560 cache.go:57] Caching tarball of preloaded images
I1007 13:49:24.941027   16560 preload.go:173] Found C:\Users\a.salunkhe\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v13-v1.22.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I1007 13:49:24.941532   16560 cache.go:60] Finished verifying existence of preloaded tar for  v1.22.2 on docker
I1007 13:49:24.941603   16560 profile.go:148] Saving config to C:\Users\a.salunkhe\.minikube\profiles\minikube\config.json ...
I1007 13:49:24.947024   16560 cache.go:206] Successfully downloaded all kic artifacts
I1007 13:49:24.948226   16560 start.go:313] acquiring machines lock for minikube: {Name:mk81b83d9fceb5f447d364707c65a94eb55887db Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I1007 13:49:24.948824   16560 start.go:317] acquired machines lock for "minikube" in 597.5µs
I1007 13:49:24.948824   16560 start.go:89] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.23.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:vmware HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.22.2 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0} &{Name: IP: Port:8443 KubernetesVersion:v1.22.2 ControlPlane:true Worker:true}
I1007 13:49:24.948824   16560 start.go:126] createHost starting for "" (driver="vmware")
I1007 13:49:24.952585   16560 out.go:204] * Creating vmware VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
I1007 13:49:24.973412   16560 main.go:130] libmachine: Found binary path at C:\Program Files\Docker\Docker\docker-machine-driver-vmware.exe
I1007 13:49:24.973412   16560 main.go:130] libmachine: Launching plugin server for driver vmware
I1007 13:49:25.031947   16560 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:60021
I1007 13:49:25.032505   16560 main.go:130] libmachine: () Calling .GetVersion
I1007 13:49:25.033027   16560 main.go:130] libmachine: Using API Version  1
I1007 13:49:25.033027   16560 main.go:130] libmachine: () Calling .SetConfigRaw
I1007 13:49:25.033027   16560 main.go:130] libmachine: () Calling .GetMachineName
I1007 13:49:25.033642   16560 main.go:130] libmachine: (minikube) Calling .GetMachineName
I1007 13:49:25.033642   16560 main.go:130] libmachine: (minikube) Calling .DriverName
I1007 13:49:25.034190   16560 start.go:160] libmachine.API.Create for "minikube" (driver="vmware")
I1007 13:49:25.034190   16560 client.go:168] LocalClient.Create starting
I1007 13:49:25.034190   16560 client.go:171] LocalClient.Create took 0s
I1007 13:49:27.035019   16560 start.go:129] duration metric: createHost completed in 2.0861953s
I1007 13:49:27.035019   16560 start.go:80] releasing machines lock for "minikube", held for 2.0861953s
W1007 13:49:27.035019   16560 start.go:522] error starting host: creating host: create: driver "vmwareworkstation" does not exist
I1007 13:49:27.046267   16560 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
I1007 13:49:27.046267   16560 delete.go:46] couldn't inspect container "minikube" before deleting: unknown state "minikube": docker container inspect minikube --format={{.State.Status}}: exec: "docker": executable file not found in %!P(MISSING)ATH%!
(MISSING)stdout:

stderr:
I1007 13:49:27.055002   16560 cli_runner.go:115] Run: podman container inspect minikube --format={{.State.Status}}
I1007 13:49:27.055002   16560 delete.go:46] couldn't inspect container "minikube" before deleting: unknown state "minikube": podman container inspect minikube --format={{.State.Status}}: exec: "podman": executable file not found in %!P(MISSING)ATH%!
(MISSING)stdout:

stderr:
W1007 13:49:27.055002   16560 start.go:527] delete host: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
W1007 13:49:27.055002   16560 out.go:242] ! StartHost failed, but will try again: creating host: create: driver "vmwareworkstation" does not exist
I1007 13:49:27.056639   16560 start.go:537] Will try again in 5 seconds ...
I1007 13:49:32.058008   16560 start.go:313] acquiring machines lock for minikube: {Name:mk81b83d9fceb5f447d364707c65a94eb55887db Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I1007 13:49:32.058904   16560 start.go:317] acquired machines lock for "minikube" in 693.8µs
I1007 13:49:32.059095   16560 start.go:89] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.23.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:vmware HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.22.2 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0} &{Name: IP: Port:8443 KubernetesVersion:v1.22.2 ControlPlane:true Worker:true}
I1007 13:49:32.059226   16560 start.go:126] createHost starting for "" (driver="vmware")
I1007 13:49:32.064019   16560 out.go:204] * Creating vmware VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
I1007 13:49:32.095441   16560 main.go:130] libmachine: Found binary path at C:\Program Files\Docker\Docker\docker-machine-driver-vmware.exe
I1007 13:49:32.095441   16560 main.go:130] libmachine: Launching plugin server for driver vmware
I1007 13:49:32.163255   16560 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:60026
I1007 13:49:32.163255   16560 main.go:130] libmachine: () Calling .GetVersion
I1007 13:49:32.164483   16560 main.go:130] libmachine: Using API Version  1
I1007 13:49:32.164483   16560 main.go:130] libmachine: () Calling .SetConfigRaw
I1007 13:49:32.164483   16560 main.go:130] libmachine: () Calling .GetMachineName
I1007 13:49:32.165025   16560 main.go:130] libmachine: (minikube) Calling .GetMachineName
I1007 13:49:32.165025   16560 main.go:130] libmachine: (minikube) Calling .DriverName
I1007 13:49:32.165025   16560 start.go:160] libmachine.API.Create for "minikube" (driver="vmware")
I1007 13:49:32.165025   16560 client.go:168] LocalClient.Create starting
I1007 13:49:32.165025   16560 client.go:171] LocalClient.Create took 0s
I1007 13:49:34.165719   16560 start.go:129] duration metric: createHost completed in 2.1064147s
I1007 13:49:34.165753   16560 start.go:80] releasing machines lock for "minikube", held for 2.1068489s
W1007 13:49:34.166423   16560 out.go:242] * Failed to start vmware VM. Running "minikube delete" may fix it: creating host: create: driver "vmwareworkstation" does not exist
I1007 13:49:34.175221   16560 out.go:177]
W1007 13:49:34.178160   16560 out.go:242] X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: driver "vmwareworkstation" does not exist
W1007 13:49:34.209869   16560 out.go:242] *
W1007 13:49:34.221927   16560 out.go:242] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

Rgds- Amit
[minikube.logs.txt](https://github.com/kubernetes/minikube/files/7301035/minikube.logs.txt)

**Comment by klaases** [comment]
Hi @amitsalunkhe21 – is this issue still occurring? Are additional details available?

**Comment by spowelljr** [comment]
Hi @amitsalunkhe21, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
