### ISSUE TITLE
Ingress DNS configuration linux configuration without resolv.conf.d/base

### ISSUE THREAD

**Issue by yhjhoo** [kubernetes/minikube#12670]
Related to this document

https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/

I don't have file in my linux distribution, what should I do?

**Comment by sharifelgamal** [comment]
Do you have the `/etc/NetworkManager/NetworkManager.conf` file instead? That's the other option for linux in the docs.

**Comment by klaases** [comment]
Hi @[yhjhoo](https://github.com/yhjhoo), did you have a chance to review @sharifelgamal's suggestion above?

**Comment by klaases** [comment]
Hi @yhjhoo  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
