### ISSUE TITLE
Cant see audit logs of HTTPS requests to kubelet

### ISSUE THREAD

**Issue by R-G-11** [kubernetes/minikube#12674]
Hi,
I'm tried to understand what I am missing but I cant find a solution 

I am using "--extra-config=kubelet.anonymous-auth=true --extra-config=kubelet.authorization-mode=AlwaysAllow" for test env 
**Steps to reproduce the issue:** 

1.audit logs for HTTPS requests to kubelet
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

[minikube-logs.txt](https://github.com/kubernetes/minikube/files/7303289/minikube-logs.txt)
<details>

I have to create a logging system that will collect all the audit logs and remote HTTPS requests to my minikube cluster.
When I tried to get information from API port (6443) I can see audit logs that include the source ip and the requested url.
I'm used for that by  following this link 
https://minikube.sigs.k8s.io/docs/tutorials/audit-policy/
The issue is that when I try to get any information from kublet that used port 10250,
for example https://my_minikube_ip:10250/pods
there is no any audit logs about it(that include source ip, requested url  etc).
when I  filter the logs I got
![image](https://user-images.githubusercontent.com/76783935/136382725-94985241-ef29-405b-8249-38df73c0afa4.png)
I tried to create a tls connection  between kubelet to kubeapi without any success
I can see that the parameters for cert files between kube-apiserver.yaml and kubelet.conf are not the same but I am not sure if its relevant.
kube-apiserver.yaml
   --kubelet-client-certificate=/var/lib/minikube/certs/apiserver-kubelet-client.crt
   --kubelet-client-key=/var/lib/minikube/certs/apiserver-kubelet-client.key

kubelet.conf
 client-certificate: /var/lib/kubelet/pki/kubelet-client-current.pem
         client-key: /var/lib/kubelet/pki/kubelet-client-current.pem 
What am I need to do to get these logs?
Please help me because I am lost

</details>

**Comment by klaases** [comment]
Hi @R-G-11, are you still working on this? Do you have any additional updates to share?
