### ISSUE TITLE
Minikube will require kubectl >v1.5.x

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1267]
Kubernetes 1.6 requires kubectl 1.5.x or above.  

- [x]  We should upgrade kubectl on our nodes and in our tests to v1.6.0 when its released
- [x]  How should we communicate to users using kubectl v1.4 or below?

**Comment by dlorenc** [comment]
Is there anything wrong with updating to v1.5 now? What does the error look like for kubectl 1.4 users now? That might be sufficient communication.

**Comment by r2d4** [comment]
The error message is pretty obtuse

`
$ ./kubectl get po
error: group map[autoscaling:0xc820387ea0 batch:0xc82044e070 certificates.k8s.io:0xc82044e0e0 componentconfig:0xc82044e150 policy:0xc82004e070 :0xc820387c00 authentication.k8s.io:0xc820387ce0 authorization.k8s.io:0xc820387e30 rbac.authorization.k8s.io:0xc82004e150 storage.k8s.io:0xc82004e1c0 federation:0xc820387730 apps:0xc820387c70 extensions:0xc8204fa000] is already registered
`

Actually I might be wrong with being able to use 1.5, you might actually just need kubectl 1.6.  There seem to be a few issues with kubectl/server skew.  We should probably just instruct users to use kubectl 1.6

https://github.com/kubernetes/kubernetes/issues/42392

**Comment by r2d4** [comment]
I upgraded to v1.6.1 on all the jenkins slaves

**Comment by r2d4** [comment]
ref #1361
