### ISSUE TITLE
InitializeSandbox() called with multiple threads in process gpu-process.

### ISSUE THREAD

**Issue by srfrnk** [kubernetes/minikube#12687]
**Steps to reproduce the issue:** 

1. Config file:
```json
{
    "cpus": 4,
    "disk-size": "10g",
    "driver": "kvm2",
    "memory": "8000"
}
```
2. `minikube start` 
3. `minikube dashboard`
4. Output is: 
```bash
😄  minikube v1.23.2 on Ubuntu 21.04
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=4, Memory=8000MB, Disk=10240MB) ...
🐳  Preparing Kubernetes v1.22.2 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
🔌  Enabling dashboard ...
    ▪ Using image kubernetesui/dashboard:v2.3.1
    ▪ Using image kubernetesui/metrics-scraper:v1.0.7
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
🎉  Opening http://127.0.0.1:40031/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
Opening in existing browser session.
[1441369:1441369:0100/000000.895226:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
[logs.txt](https://github.com/kubernetes/minikube/files/7317278/logs.txt)

<details>
After upgrading to latest version thie error started to show everytime I open the dashboard,
It still works but I'm not sure if the error has any other significance.
</details>

**Comment by sharifelgamal** [comment]
Hey @srfrnk, this seems to be an issue with your browser, rather than with `minikube dashboard`. Are you able to successfully `curl` that endpoint in a terminal, or manually paste the URL into a browser?

**Comment by srfrnk** [comment]
Thanks @sharifelgamal - after you comment I googled the error with chrome and ubuntu and indeed it's a known issue with chrome on ubuntu. (https://simpleit.rocks/linux/ubuntu/fixing-common-google-chrome-gpu-process-error-message-in-linux/)
I'm gonna close this. Thanks for the help!
