### ISSUE TITLE
Proxies and VPNs

### ISSUE THREAD

**Issue by fkn-iteratec** [kubernetes/minikube#12686]
Hi, 

based on the [proxy documentation](https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/) I tried to set the environmemnt variables HTTP_PROXY and HTTPS_PROXY but in my case the given examples are not working. I have to set both variables to the **same** protocol and it must be http not https. So I think the documentation may be improved to:

```
set HTTP_PROXY=http://<proxy hostname:port>
set HTTPS_PROXY=http://<proxy hostname:port>
``` 
In this case I was working on a windows machine. 

Regards,
Fabian

**Comment by 3ch01c** [comment]
I think it depends if your proxy supports SSLi. In your case, it sounds like it doesn't. I don't think the documentation should be changed in this case.

**Comment by fkn-iteratec** [comment]
@3ch01c : So perhaps a hint in the documentation for SSLi would be great. For users like me, who do know nothing about SSLi &#x1F609;

**Comment by sharmavishalvk** [comment]
I will work on this and submit a PR later
