### ISSUE TITLE
Fully remove boot2docker support

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1268]
I propose that we remove boot2docker support from minikube.  It adds extra complexity in the code paths to support both a systemd OS and a non-systemd OS.  We have done many releases of minikube-iso, to the point where it is stable and default.

**Comment by aaron-prindle** [comment]
SGTM.  We can also simplify some of the code in commands.go as well:
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cluster/commands.go#L99
