### ISSUE TITLE
minikube start: IPs output should only be one line, got 2 lines

### ISSUE THREAD

**Issue by Apocryphon06** [kubernetes/minikube#12681]
**Steps to reproduce the issue:** 

1.minikube start
2. getting error at creation of base container

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
[logs.txt](https://github.com/kubernetes/minikube/files/7314833/logs.txt)

**Full output of failed command if not `minikube start`:**
<details>
😄  minikube v1.23.2 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.

</details>

**Comment by afbjorklund** [comment]
I think this is related to previous docker swarm networks, it was supposed to be fixed in later versions of minikube.

`docker network ls` probably has multiple bridges.

**Comment by spowelljr** [comment]
Hi @Apocryphon06, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
