### ISSUE TITLE
minikube is not started getting error

### ISSUE THREAD

**Issue by snag9032** [kubernetes/minikube#12688]
* minikube v1.23.2 on Ubuntu 18.04
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.232822 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
* Restarting existing virtualbox VM for "minikube" ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: driver start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.240935 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

X Exiting due to HOST_VTX_UNAVAILABLE: Failed to start host: driver start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.240935 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
* Suggestion: Your host does not support virtualization. If you are running minikube within a VM, try '--driver=docker'. Otherwise, enable virtualization in your BIOS
* Related issues:
  - https://github.com/kubernetes/minikube/issues/1994
  - https://github.com/kubernetes/minikube/issues/5326
![Uploading minikube issue.PNG…]()

**Comment by spowelljr** [comment]
Hi @snag9032, thanks for reporting your issue with minikube!

What version of VirtualBox are you using?

**Comment by medyagh** [comment]
Hi @snag9032  , I haven't heard back from you, I wonder if you still have this issue?

we had an issue with older virtualbox I recommend trying newest vbox with newest minikube (newer than 1.24.0)

Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
