### ISSUE TITLE
Have a ghost VM running with portainer! How can I delete it?

### ISSUE THREAD

**Issue by cduran** [kubernetes/minikube#12698]
**Steps to reproduce the issue:** 

1. Install minikube: `brew install minikube`
2. Install hyperkit: `brew install hyperkit`
3. Install docker-cli: `brew install docker`
4. Install docker-compose: `brew install docker-compose`
4. Then I put this on my .zshrc:
 `export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.64.2:2376"
export DOCKER_CERT_PATH="/Users/cduran/.minikube/certs"
export MINIKUBE_ACTIVE_DOCKERD="minikube"`
5. Then started a new terminal. And run `minikube config set driver hyperkit`
6. Then started `minikube start --driver=hyperkit`
7. Then run `docker run hello-world` and worked ok.
8. Then installed portainer: 
`docker volume create portainer_data`
`docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce` 
10. Then I run: `echo "'minikube ip' docker.local" | sudo tee -a /etc/hosts > /dev/null`
11. Opened the browser in `docker.local:9000` and was presented with login screen. Could not set password nor login.
12. Proceed and delete portainer, then volume, then kyperkit then minikube for clean install again.
13. Rebooted mac and tried accessing portainer for kicks here`docker.local:9000` and it is still there...!!!
14. How can I delete a VM created by hyperkit with just portainer running and not being able to access it anywhere?
15. I tried installing minikube with hyperkit to see if it would pickup that VM but it created a new one with IP 192.168.64.4
16. I still have the 192.168.64.2 pointing to docker.local and able to access portainer on port 9000

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
Manage to get this log found it looking for the IP address 192.168.64.2 just found this file.
[minikube_logs_43a3a2183d759166b9135eefb234951321429c2a_0.log](https://github.com/kubernetes/minikube/files/7326837/minikube_logs_43a3a2183d759166b9135eefb234951321429c2a_0.log)

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by klaases** [comment]
Hi @cduran, are you still experiencing this error? Is any additional information available? Also, would you be able to try this with the the latest version of minikube?

**Comment by sharifelgamal** [comment]
This doesn't seem to be strictly related to minikube, as it's a portainer VM created by hyperkit. While I'm no hyperkit expert, I feel like there has to be a way to wipe all VMs from a machine.

For the record, minikube has a portainer addon that should work as well.

**Comment by klaases** [comment]
Hi @cduran – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
