### ISSUE TITLE
 minikube addons enable istio

### ISSUE THREAD

**Issue by jpcv19** [kubernetes/minikube#12699]
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 2.5903249s
💡  Restarting the docker service may improve performance.
❗  Istio needs 8192MB of memory -- your configuration only allocates 4000MB
❗  Istio needs 4 CPUs -- your configuration only allocates 2 CPUs

❌  Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.22.2/kubectl apply -f /etc/kubernetes/addons/istio-default-profile.yaml: Process exited with status 1
stdout:
namespace/istio-system unchanged

stderr:
error: unable to recognize "/etc/kubernetes/addons/istio-default-profile.yaml": no matches for kind "IstioOperator" in version "install.istio.io/v1alpha1"
]
[minikube_addons_7bcf29cad66f368b9c9424049dfa6db386538c33_0.log](https://github.com/kubernetes/minikube/files/7330255/minikube_addons_7bcf29cad66f368b9c9424049dfa6db386538c33_0.log)

**Comment by g00nix** [comment]
I can confirm this bug. Istio does not work on minikube.

**Comment by spowelljr** [comment]
Also confirmed this bug, this is likely caused by https://github.com/kubernetes/minikube/pull/12230.

**Comment by Calvin0520** [comment]
this is likely caused by https://github.com/kubernetes/minikube/issues/13536.
