### ISSUE TITLE
Builddate is wrong in 0.17.1

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/minikube#1270]
**Minikube version** 

0.17.1

**What happened**:

When we do `kubectl version` the _builddate_ of minikube is wrong, it is set to epoch 0.

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What you expected to happen**:

The date of the release.

**Comment by r2d4** [comment]
Whats the proper value?  The date off the kubernetes release or the date we've built it?  The latter would probably be easiest to add, but the former is probably of more value to people.

**Comment by sebgoa** [comment]
I think the date you have built it.
