### ISSUE TITLE
bump pause image to v3.6 

### ISSUE THREAD

**Issue by kerthcet** [kubernetes/minikube#12713]
xref: https://github.com/kubernetes/kubernetes/issues/104890
I found the pause image in minikube is remained in v3.1, I wonder whether it's necessary to upgrade pause image to pause:3.6, some improvements in windows server supports. 
Further, should minikube keep in sync with the kubernetes latest pause image as the document says?

**Comment by kerthcet** [comment]
yeah, it's what the https://github.com/kubernetes/kubernetes/issues/104890 working for. I'll close the issue then.

**Comment by afbjorklund** [comment]
It's not merged yet, but anyway...
