### ISSUE TITLE
SSH driver: --ssh-port ignored (it always use port 22)!

### ISSUE THREAD

**Issue by salvoravida** [kubernetes/minikube#12721]
SSH driver: --ssh-port ignored (it always uses port 22)!

**Comment by afbjorklund** [comment]
Can you try if it works better with `--native-ssh=false` ?

**Comment by salvoravida** [comment]
I1017 11:58:49.738138   10448 main.go:130] libmachine: Getting to WaitForSSH function...
I1017 11:58:49.738597   10448 main.go:130] libmachine: Using SSH client type: external
I1017 11:58:49.738786   10448 main.go:130] libmachine: &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@__IP_ADDRESS__ -p 22] /usr/bin/ssh <nil>}
I1017 11:58:49.738847   10448 main.go:130] libmachine: About to run SSH command:
exit 0
I1017 11:58:50.171391   10448 main.go:130] libmachine: SSH cmd err, output: exit status 255: 
I1017 11:58:50.171537   10448 main.go:130] libmachine: Error getting ssh command 'exit 0' : ssh command error:
command : exit 0
err     : exit status 255

**Comment by salvoravida** [comment]
with the native false, it ignores the user also.

**Comment by salvoravida** [comment]
sorry i do not use minikube anymore

**Comment by klaases** [comment]
Hi @salvoravida, thanks for taking the time to work with minikube. Will close out this issue for now. All the best.
