### ISSUE TITLE
Add "kubeflow" add-on

### ISSUE THREAD

**Issue by anencore94** [kubernetes/minikube#12725]
Hi forks, I have a question if you guys have any plan to support kubeflow as an add-on.

Microk8s supports kubeflow as an add-on like this : https://github.com/ubuntu/microk8s/blob/master/microk8s-resources/actions/enable.kubeflow.sh

If you guys are interested, I'd like to take this issue.

Thanks in advance.

**Comment by medyagh** [comment]
there are no rules u could put them either in files that are Numbered so the lower number will go first and then other numbers
like 
0-fileA.yaml
1-fileB.yaml

**Comment by klaases** [comment]
Hi @[anencore94](https://github.com/anencore94), just checking in, are you still actively working on this issue?

**Comment by anencore94** [comment]
@klaases No, I'm currently not available on this issue. If you are interested in, please take this :)  I will unassign me now

**Comment by klaases** [comment]
Sure @anencore94, I understand - we will continue to remain open for community contributions for this issue.
