### ISSUE TITLE
/Users/macbook/.minikube/logs/lastStart.txt 

### ISSUE THREAD

**Issue by al-hujaylan** [kubernetes/minikube#12722]
**الأوامر المطلوبة لإعادة إظهار المشكلة**:

**النتيجة الكاملة للأمر الذي تعذّر تنفيذه**:<details>

</details>

**نتيجة الأمر `minikube logs`**: <details>

</details>

**إصدار نظام التشغيل المُستخدَم**:

**Comment by sharifelgamal** [comment]
Hey @al-hujaylan – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!

---

مرحبًا @ al-hujaylan - آمل أن يكون الأمر جيدًا إذا أغلقت هذا - لم تكن هناك معلومات كافية لجعله قابلاً للتنفيذ ، وقد مر بعض الوقت بالفعل. إذا كنت قادرًا على تقديم تفاصيل إضافية ، فيمكنك إعادة فتحه في أي وقت عن طريق إضافة / إعادة فتح تعليقك.

فيما يلي معلومات إضافية قد تكون مفيدة لنا:

* ما إذا كانت المشكلة تحدث مع أحدث إصدار من minikube أم لا

* استخدام سطر أوامر minikube البدء الدقيق

* الإخراج الكامل لأمر minikube start ، ويفضل أن يكون مع --alsologtostderr -v = 3 للتسجيل الإضافي.

* الإخراج الكامل لسجلات minikube

شكرا لتقاسم تجربتك!
