### ISSUE TITLE
Unable to connect to the server: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by monikapatil77** [kubernetes/minikube#12731]
**Steps to reproduce the issue:** 

1. minikube start
2. 
<img width="1401" alt="Screenshot 2021-10-19 at 5 43 31 PM" src="https://user-images.githubusercontent.com/91019007/137907689-03eb84bf-1da3-45fb-a86b-4e4b95331195.png">

3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Hey @monikapatil77  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The full output of minikube logs --file=logs.txt

Thank you for sharing your experience!
