### ISSUE TITLE
Minikube with Podman driver fails to start on NixOS systems

### ISSUE THREAD

**Issue by alias-dev** [kubernetes/minikube#12738]
**Steps to reproduce the issue:** 

1. Install minikube and podman on a [NixOS](https://nixos.org/) system.
2. Run `minikube start --driver=podman --container-runtime=cri-o`.

**Full output of failed command if not `minikube start`:**
<details>

* minikube v1.23.2 on Nixos 21.11 (Porcupine)
  - MINIKUBE_IN_STYLE=0
* Using the podman driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
E1019 20:20:59.191986  581071 cache.go:201] Error downloading kic artifacts:  not yet implemented, see issue #8426
* Creating podman container (CPUs=2, Memory=2200MB) ...
! StartHost failed, but will try again: creating host: create: creating: create kic node: create container: sudo -n podman run --cgroup-manager cgroupfs -d -t --privileged --device /dev/fuse --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --network minikube --ip 192.168.49.2 --volume minikube:/var:exec -e container=podman --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 --publish=127.0.0.1::32443 gcr.io/k8s-minikube/kicbase:v0.0.27: exit status 125
stdout:

stderr:
Error: statfs /lib/modules: no such file or directory

* Restarting existing podman container for "minikube" ...
* Failed to start podman container. Running "minikube delete" may fix it: podman inspect ip minikube: sudo -n podman container inspect -f {{.NetworkSettings.IPAddress}} minikube: exit status 125
stdout:

stderr:
Error: error inspecting object: no such container minikube

X Exiting due to GUEST_PROVISION: Failed to start host: podman inspect ip minikube: sudo -n podman container inspect -f  minikube: exit status 125
stdout:

stderr:
Error: error inspecting object: no such container minikube

</details>

On NixOS `/lib/modules` exists at `/run/current-system/kernel-modules/lib/modules`, so the volume mount fails.

**Comment by azahi** [comment]
Run to this same issue today. 

```
🤦  StartHost failed, but will try again: creating host: create: creating: create kic node: create container: sudo -n podman run --cgroup-manager cgroupfs -d -t --privileged --device /dev/fuse --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --network minikube --ip 192.168.49.2 --volume minikube:/var:exec -e container=podman --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 --publish=127.0.0.1::32443 gcr.io/k8s-minikube/kicbase:v0.0.28: exit status 125
stdout:

stderr:
Error: statfs /lib/modules: no such file or directory
```

The fix was to just create the `/lib/modules` directory manually because NixOS doesn't follow FHS. Although, it would be really nice if minikube didn't assume that there must be this directory on the host system. Is there any reason on why this volume is being mounted?

**Comment by afbjorklund** [comment]
> Is there any reason on why this volume is being mounted?

I think it is mounted for `modprobe` purposes (looking for kernel modules).

They usually fail because of a lack of "config", but that's another story...

**Comment by afbjorklund** [comment]
Couldn't NixOS add a symlink, to make it self compatible ?
