### ISSUE TITLE
minikube alpine 13

### ISSUE THREAD

**Issue by ghost** [kubernetes/minikube#12749]
It would be nice to present the information about how to install minikube on alpine images, since many VMs work with that system.
As a requirement to install it in an Alpine Linux image there is a requirement.
`apk add libc6-compat`
Just that. Otherwise minikube will return:
`-ash: minikube: not found`

**Comment by klaases** [comment]
Closing out as OP left Github, if anyone needs to re-open the issue by commenting with `/reopen`.
