### ISSUE TITLE
kvm2 - link to OpenSUSE instructions is outdated

### ISSUE THREAD

**Issue by cyc1ingsir** [kubernetes/minikube#12755]
At the kvm2 driver documentation the link to the openSuse instructions is outdated:

Inside:
https://github.com/kubernetes/minikube/blob/master/site/content/en/docs/drivers/includes/kvm2_usage.inc

`[OpenSUSE](` ~https://doc.opensuse.org/documentation/leap/virtualization/html/book.virt/cha-vt-installation.html~ `)`
Should be replaced with:
https://doc.opensuse.org/documentation/leap/virtualization/html/book-virtualization/cha-vt-installation.html

**Comment by sharifelgamal** [comment]
I would love help with documentation PRs like this. I'd be willing to review a PR that fixes this.
