### ISSUE TITLE
Enabled feature gate "EphemeralContainers" but feature is not supported? 

### ISSUE THREAD

**Issue by chrisbirster** [kubernetes/minikube#12763]
**Steps to reproduce the issue:** 

1. minikube start --feature-gates=EphemeralContainers=true

```sh
😄  minikube v1.23.2 on Darwin 11.6
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.22.2 on Docker 20.10.8 ...
🔎  Verifying Kubernetes components...
    ▪ Using image kubernetesui/metrics-scraper:v1.0.7
    ▪ Using image kubernetesui/dashboard:v2.3.1
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass, dashboard
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

2. kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4

```sh
deployment.apps/hello-node created
```

3. kubectl get pods

```sh
NAME                          READY   STATUS    RESTARTS   AGE
hello-node-7567d9fdc9-ntnv4   1/1     Running   0          6s
```

4. kubectl debug -it hello-node-7567d9fdc9-ntnv4 --image=busybox --target=hello-node-7567d9fdc9-ntnv4

```sh
Defaulting debug container name to debugger-dklhx.
error: error updating ephemeral containers: EphemeralContainers in version "v1" cannot be handled as a Pod: no kind "EphemeralContainers" is registered for version "v1" in scheme "k8s.io/kubernetes/pkg/api/legacyscheme/scheme.go:30"
```

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

[logs.txt](https://github.com/kubernetes/minikube/files/7401979/logs.txt)

</details>

**Comment by klaases** [comment]
Hi @chrisbirster, are you still experiencing this issue? It looks like there may be a version mismatch.

Make sure your version of kubectl (command line for viewing k8s resources) is at least 1.22, or try and use kubernetes 1.23 which is in beta. EphemeralContainers are disabled by default in 1.22

The following additional information may be helpful:
https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/#api-changes-and-improvements-for-ephemeral-containers

**Comment by spowelljr** [comment]
Hi @chrisbirster, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
