### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by raghav6615** [kubernetes/minikube#12767]
minikube kubectl -- get pods -A

description of the command -A is not given in official doc

**Comment by sharifelgamal** [comment]
`minikube kubectl` is just a `kubectl` binary that's distributed along with minikube, there's nothing special about it. If you refer to the [official kubectl docs](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#get), you'll see that `-A` is just a shorthand for `--all-namespaces` .
