### ISSUE TITLE
Don't throw `Docker is nearly out of disk space` errors if more than X GB of disk space available

### ISSUE THREAD

**Issue by HarHarLinks** [kubernetes/minikube#12761]
I have just cleared out some space so minikube would even start at "100%" used disk - which in this case is several terabytes large and still had several 100GB free.
It is now warning me that "Docker is nearly out of disk space" at 98% which equals 843GB currently available space which is quite frankly ridiculous.

**Comment by F1ko** [comment]
going to remove the frozen lifecycle since there are new commits being pushed to the PR

unless there is another reason to freeze this issue? (@spowelljr )

/remove-lifecycle frozen

**Comment by spowelljr** [comment]
Frozen prevents it from going stale

**Comment by mayur-tolexo** [comment]
Has this issue been worked on? I will like to take it up.

**Comment by F1ko** [comment]
Yes, it actually is done already, I am just waiting for a final review.
