### ISSUE TITLE
Error getting config: CreateFile C:\Users\921812\.minikube\profiles\minikube\config.json: The system cannot find the path specified.

### ISSUE THREAD

**Issue by Sivasedhu** [kubernetes/minikube#12783]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Hey @Sivasedhu  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of `minikube logs --file=logs.txt`

Thank you for sharing your experience!
