### ISSUE TITLE
Limiting minikube network banwidth

### ISSUE THREAD

**Issue by babaksit** [kubernetes/minikube#12785]
**Steps to reproduce the issue:** 

1.  minikube start --network-plugin=cni
2. Change the cni_network_config config of https://docs.projectcalico.org/manifests/calico-vxlan.yaml to the following:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: calico-config
  namespace: kube-system
data:
  typha_service_name: "none"
  calico_backend: "vxlan"

  veth_mtu: "0"

  cni_network_config: |-
    {
      "name": "k8s-pod-network",
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "calico",
          "log_level": "info",
          "log_file_path": "/var/log/calico/cni/cni.log",
          "datastore_type": "kubernetes",
          "nodename": "__KUBERNETES_NODE_NAME__",
          "mtu": __CNI_MTU__,
          "ipam": {
              "type": "calico-ipam"
          },
          "policy": {
              "type": "k8s"
          },
          "kubernetes": {
              "kubeconfig": "__KUBECONFIG_FILEPATH__"
          }
        },
        {
          "type": "portmap",
          "snat": true,
          "capabilities": {"portMappings": true}
        },
        {
          "type": "bandwidth",
          "capabilities": {"bandwidth": true}
          "ingressRate": 1000,
          "ingressBurst": 1000,
          "egressRate": 1000,
          "egressBurst": 1000
        }
      ]
    }

```

3. Apply the modified config file.

kubectl apply -f calico-vxlan.yaml 

<details>

I am trying to limit the minikube bandwidth, however, applying the above-mentioned config does not take an effect.

</details>

**Comment by sharifelgamal** [comment]
The `network-plugin=cni` parameter is effectively deprecated, try using the `--cni` parameter instead:

`minikube start --cni=<path to yaml file>`

**Comment by sharifelgamal** [comment]
Hey @babaksit, I'm going to go ahead and close this issue since there hasn't been a response in quite some time. If you try my advice above and still have issues, feel free to reopen this with more details.
