### ISSUE TITLE
minikube install k8s error 

### ISSUE THREAD

**Issue by niuzhiweimr** [kubernetes/minikube#12780]
**重现问题所需的命令**：

 minikube start  -p nzw-k8s --cpus=8 --memory=10240 --disk-size='102400MB'  --kubernetes-version=v1.19.0

**失败的命令的完整输出**：<details>

💣  更新 cluster 失败: downloading binaries: downloading kubelet: Error downloading kubelet v1.19.0: failed to download: failed to download to temp file: failed to create validator: failed to create validator: failed to download checksum file: received status code 404
</details>

**`minikube logs`命令的输出**： <details>
😄  Darwin 10.15.2 上的 [nzw-k8s] minikube v1.6.2
✨  Selecting 'hyperkit' driver from existing profile (alternates: [])
🏃  Using the running hyperkit "nzw-k8s" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  正在 Docker '19.03.5' 中准备 Kubernetes v1.19.0…

💾  正在下载 kubelet v1.19.0
💾  正在下载 kubeadm v1.19.0

💣  更新 cluster 失败: downloading binaries: downloading kubelet: Error downloading kubelet v1.19.0: failed to download: failed to download to temp file: failed to create validator: failed to create validator: failed to download checksum file: received status code 404

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**使用的操作系统版本**：

macos  10.15.2

**Comment by sharifelgamal** [comment]
Please update your minikube version to v1.24.0 and please try again. Feel free to reopen this issue if you continue to see problems.

---

请将您的 minikube 版本更新到 v1.24.0，然后再试一次。如果您继续看到问题，请随时重新打开此问题。
