### ISSUE TITLE
Exiting due to GUEST_START: Failed kubeconfig update: could not read config: Error decoding config from data: piVersion: v1

### ISSUE THREAD

**Issue by zhang14725804** [kubernetes/minikube#12795]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

[logs.txt](https://github.com/kubernetes/minikube/files/7423737/logs.txt)

</details>

**Comment by spowelljr** [comment]
Hi @zhang14725804, thanks for reporting your issue with minikube!

It looks like you're missing an `a` in `apiVersion: v1`, were you manually editing `~/.kube/config` perhaps?

All you have to do is add an `a` in front of `piVersion` in `~/.kube/config` and your issue should be resolved.

**Comment by zhang14725804** [comment]
thank you

**Comment by spowelljr** [comment]
I'm going to close this issue as I believe this solved your issue, but if not feel free to re-open it, thanks for using minikube!
