### ISSUE TITLE
No NodePort access with rootless Minikube

### ISSUE THREAD

**Issue by TekTimmy** [kubernetes/minikube#12796]
**Steps to reproduce the issue:** 

1. Use Ubuntu 20.04 LTS
2. Install docker from offical repo as root: https://docs.docker.com/engine/install/debian/#set-up-the-repository
```
sudo apt-get install --assume-yes docker-ce docker-ce-cli containerd.io
```
3. Setup rootless docker as normal user
```
dockerd-rootless-setuptool.sh install -f
docker context use rootless
systemctl --user start docker
systemctl --user enable docker
```
4. Start Minikube:
```
minikube config set container-runtime containerd
minikube start
```
5. Deploy application with NodePort
```
kubectl create deployment hello-minikube1 --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment hello-minikube1 --type=NodePort --port=8080
```
6. Determine minikube service url and open that in browser:
```
minikube service list
```
7. **Issue**: the NodePort is not accessible from outside Minikube (as usually is without rootless docker)

**Comment by AkihiroSuda** [comment]
> But minikube ip gives me an IP address back so Minikube in rootless Docker does have its own IP as it seems.

Yes, but the IP is network-namespaced and you can't reach that IP from the host.

**Comment by TekTimmy** [comment]
> > But minikube ip gives me an IP address back so Minikube in rootless Docker does have its own IP as it seems.
> 
> Yes, but the IP is network-namespaced and you can't reach that IP from the host.

Thank you for the explanation. For me its a bit confusing that minikube changes its behavior when using a different container runtime or operating system.. probably a necessary evil

**Comment by TekTimmy** [comment]
So for those who (for whatever reason) read this ticket in the future: `minikube tunnel` is the way to go, `minikube service` only provides accessible URLs when the OS is linux and the container runtime is `docker`.
