### ISSUE TITLE
Website page for 'minikube cache' has wrong description

### ISSUE THREAD

**Issue by yosshy** [kubernetes/minikube#12809]
https://minikube.sigs.k8s.io/docs/commands/cache/ describes `minikube cache` command. It says:

> Add, delete, or push a local image into minikube

But the command has 3 sub-commands below:

- add
- delete
- reload

So, it should be:

> Add, delete, or reload an image into minikube

**Comment by yosshy** [comment]
/assign @tstromberg
any comment?

**Comment by medyagh** [comment]
@yosshy the source of confusion is that was a description not meant for listing sub commands, I would accept a PR that would fix that to be more simple and not confusing :)

**Comment by t-inu** [comment]
According to https://github.com/kubernetes/minikube/pull/13764, document pages are automatically updated by modifying the source code.
So, I'll create a PR to fix the description within the source code.
/assign

**Comment by t-inu** [comment]
I confirmed [`minikube cache` command page](https://minikube.sigs.k8s.io/docs/commands/cache/) had been updated automatically.
