### ISSUE TITLE
Minikube fails to start on non default k8s version

### ISSUE THREAD

**Issue by vidhill** [kubernetes/minikube#1281]
**BUG REPORT**

**Minikube version**: v0.17.1

**Environment**:
- **OS**: Ubuntu 16.04 LTS
- **VM Driver**: virtualbox
- **ISO version**: minikube-v1.0.7.iso
- **Install tools**: 
- **Others**:

**What happened**:
run `minikube start --kubernetes-version="v1.4.5" --disk-size="10g"  --logtostderr`
stdout: [here](https://gist.github.com/vidhill/ff2898753dabec9c42a66b0886a58552)

Running `minikube status` returns:
```
E0323 12:59:03.942247   12406 notify.go:54] Error getting json from minikube version url: Error getting minikube version url via http: Get https://storage.googleapis.com/minikube/releases.json: dial tcp [2a00:1450:400b:801::2010]:443: connect: network is unreachable
minikubeVM: Running
localkube: Stopped
```

**What you expected to happen**:
Running `minikube status` would return:
```
minikubeVM: Running
localkube: Running
```

**How to reproduce it** (as minimally and precisely as possible):
run `minikube start --kubernetes-version="v1.4.5"

**Anything else do we need to know**:
running `minikube start` works correctly, as expected, 

Issue only occurs when specifying different version of kubernetes using --kubernetes-version

**Comment by gtirloni** [comment]
Duplicated of #1220

**Comment by vidhill** [comment]
Is there a workaround?

**Comment by gtirloni** [comment]
If you don't specifically need v1.4.5, you could try a newer version instead.

Alternatively, you could edit the systemd unit file and remove that option but I'm not sure it won't get overwritten next time the machine boots (still figuring out how minikube works in that regard). That should let localkube run.

As mentioned in #1220, this should be fixed in the next minikube version due to #1245. If you build minikube from master, the issue should be gone.

**Comment by vidhill** [comment]
Yea, I need to do a test on an earlier version of kubernetes, I will build from master.
Thanks

**Comment by vidhill** [comment]
I've built from master but still seem to be getting the same/a similar error, 

I removed minikube from my /usr/local/bin and removed the ~/.minikube folder

I cloned down master, and built using `Make` and am running minikube from the `out/` folder

[stdout log](https://gist.github.com/vidhill/f47845df8d491420d9285a25ca6889c8)

It seems it's failing at the creation of the symlink, as far as I can see it's trying to create a symlink to a file that doesn't exist

**Comment by r2d4** [comment]
Can you give the output of `minikube logs`?

**Comment by vidhill** [comment]
Yes, certainly
https://gist.github.com/vidhill/20d84eab27b8b5ca45160a6a87b45e80

**Comment by r2d4** [comment]
I've just added a PR to fix.  You can grab the CI artifacts from 

```
https://storage.googleapis.com/minikube-builds/1286/minikube-darwin-amd64
https://storage.googleapis.com/minikube-builds/1286/minikube-linux-amd64
https://storage.googleapis.com/minikube-builds/1286/minikube-windows-amd64.exe
```

When the CI build is complete to test

**Comment by vidhill** [comment]
Thanks for that, 
I'm finished up for a day, I'll check in tomorrow
