### ISSUE TITLE
Minikube with driver "new Virtualization Framework" on Apple M1

### ISSUE THREAD

**Issue by cscetbon** [kubernetes/minikube#12826]
As more and more people are thinking of moving to Minikube to replace "Docker For Mac" some work to enable virtualization on it should be a priority to get them onboard. Hyperkit being deprecated going with the **new Virtualization Framework** which uses higher API and is supposed to be easier to use probably makes more sense

See https://github.com/Code-Hex/vz

**Comment by cscetbon** [comment]
Did someone start any work on this somewhere that could be used as a base or needs to be completed ?

**Comment by afbjorklund** [comment]
Currently containerd (lima) uses QEMU and podman (machine) uses QEMU, but there is room for more hypervisor drivers.

The main issue is actually not the CPU virtualization, at least not anymore. The problem is the network, especially VPN...

**Comment by cscetbon** [comment]
@afbjorklund but as Minikube already supports hyperkit I thought it should be easier to start from there and migrate it to the new framework which is supposed to be simple and support everything that is already supported.

**Comment by afbjorklund** [comment]
Yes, as far as I know both HyperKit and LinuxKit are still Open Source even if Docker's new libraries might not be.

**Comment by afbjorklund** [comment]
> migrate it to the new framework 

What "new framework" are you talking about here ?

**Comment by cscetbon** [comment]
> > migrate it to the new framework 
> 
> What "new framework" are you talking about here ?

https://developer.apple.com/documentation/virtualization

The new one that deprecates hyperkit and there is a go binding for it at https://github.com/Code-Hex/vz

**Comment by afbjorklund** [comment]
Okay thanks, we will need someone to turn that into a "driver" for the libmachine framework:

https://github.com/docker/machine/blob/master/libmachine/drivers/drivers.go

**Comment by cscetbon** [comment]
@afbjorklund You mean writing something like https://github.com/kubernetes/minikube/tree/master/pkg/drivers/hyperkit, right ? Also do you know why the hyperkit doesn't work on M1 atm ?

**Comment by afbjorklund** [comment]
> @afbjorklund You mean writing something like https://github.com/kubernetes/minikube/tree/master/pkg/drivers/hyperkit, right ?

Right (you will notice it imports the libmachine framework)

There is also an old driver for QEMU.

> Also do you know why the hyperkit doesn't work on M1 atm ?

Same reason as VirtualBox, I suppose. No arm64 support.

See https://github.com/moby/hyperkit/issues/303#issuecomment-875122919

**Comment by riaz7se** [comment]
Any reference or links to follow for installing minikube on M1 using Apple Virtualization framework?
pls suggest

**Comment by sharifelgamal** [comment]
This is still something we're looking into. One prerequisite for this to work is a minikube ISO that will work on the arm64/aarch64 architecture, which is still in progress.

**Comment by xaocon** [comment]
> This is still something we're looking into. One prerequisite for this to work is a minikube ISO that will work on the arm64/aarch64 architecture, which is still in progress.

Is that conversation going on somewhere public? I'd like to help. Not sure I could help much with the GO stuff but I could probably help with the ISO or helping track down how other projects are doing similar things (looking through lima for example).

**Comment by sharifelgamal** [comment]
The tracking issue for the arm64 ISO is #9228

**Comment by spowelljr** [comment]
We just released minikube v1.26.0-beta.0 that supports the QEMU driver `--driver=qemu2`.

https://github.com/kubernetes/minikube/releases/tag/v1.26.0-beta.0

**Comment by afbjorklund** [comment]
It would still be interesting to see a dedicated Mac driver using virtualization.framework (like the old HyperKit driver)

But the QEMU driver is _also_ getting some real networking support, using the vmnet.framework (courtesy of lima).

**Comment by afbjorklund** [comment]
* https://github.com/lima-vm/lima/issues/889

**Comment by tmoschou** [comment]
Looks like [Podman v5.0.0-rc7](https://github.com/containers/podman/releases/tag/v5.0.0-rc7) have switched their driver on MacOS over from QEMU to the native MacOS virtualization framework / hypervisor thanks to https://github.com/crc-org/vfkit and https://github.com/Code-Hex/vz 

As a side, it would be good to know if the new framework potentially fixes the networking issue / firewall bugs we have with [socket_vmnet](https://github.com/lima-vm/socket_vmnet/issues/18) - we are running MacOS's enrolled in MDM, which [prohibit firewall modifications](https://github.com/lima-vm/socket_vmnet/issues/18#issuecomment-1717216573) and our IT are reluctant to deploy a custom Firewall MDM payload. We basically have to stop/uninstall/reboot/reinstall socket_vmnet as a workaround, which is a shame as its limiting uptake of minikube/kubernetes.

**Comment by afbjorklund** [comment]
You can use Lima, for running virtual machines with vz without having to use Podman and CoreOS...

https://lima-vm.io/docs/config/vmtype/

**Comment by afbjorklund** [comment]
Now you can use `gvproxy` for the network, since it has integration with the `vfkit` program.

https://github.com/containers/gvisor-tap-vsock#run-with-vfkit

**Comment by afbjorklund** [comment]
Apparently using gvproxy is optional, since the built-in "nat" actually gives you an IP with dhcp.

So that can at least be used for ssh, by parsing the dhcp_leases
