### ISSUE TITLE
minikube service hello-minikube won't work for Mac M1

### ISSUE THREAD

**Issue by hjoly2003** [kubernetes/minikube#12833]
Hi, invoking `minikube service hello-minikube` won't work for Mac M1.

The docker image `k8s.gcr.io/echoserver:1.4` is not compatible to the Mac M1 arm64 architecture. A suggestion for your tutorial would be the following:
```bash
kubectl create deployment hello-minikube --image=docker/getting-started --replicas=2
kubectl expose deployment hello-minikube --type=NodePort --port=80
```

Thanks

**Comment by afbjorklund** [comment]
Same as #11107

**Comment by spowelljr** [comment]
Closing this issue due to duplication.
