### ISSUE TITLE
Minikube start fails in macos Big Sur with Internet Sharing on regardless of driver

### ISSUE THREAD

**Issue by juandesant** [kubernetes/minikube#12840]
**Steps to reproduce the issue:** 

1. Activate Internet Sharing in the Sharing System Preferences pane
2. Type `minikube start`.
3. Minikube start fails
4. Deactivate Internet Sharing in the Sharing System Preferences pane
5. Type `minikube start`.
6. Minikube start succeeds

After step 6., you can keep accessing your minikube even if you activate Internet Sharing again, although some spurious issues can happen sometimes.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
Log file cannot be generated, as the control plane never gets to be activated.

**Full output of failed command if not `minikube start`:**

<details>

**Minikube start with `hyperkit`**

~ minikube start --alsologtostderr
I1102 07:22:20.016948   10516 out.go:298] Setting OutFile to fd 1 ...
I1102 07:22:20.017192   10516 out.go:350] isatty.IsTerminal(1) = true
I1102 07:22:20.017199   10516 out.go:311] Setting ErrFile to fd 2...
I1102 07:22:20.017210   10516 out.go:350] isatty.IsTerminal(2) = true
I1102 07:22:20.017307   10516 root.go:313] Updating PATH: /Users/j.santander-vela/.minikube/bin
I1102 07:22:20.017339   10516 oci.go:561] shell is pointing to dockerd inside minikube. will unset to use host
I1102 07:22:20.017935   10516 out.go:305] Setting JSON to false
I1102 07:22:20.059899   10516 start.go:111] hostinfo: {"hostname":"IT001163.local","uptime":30392,"bootTime":1635818148,"procs":573,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"11.6.1","kernelVersion":"20.6.0","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"abc69550-60c2-34fe-b307-c24a8c39309c"}
W1102 07:22:20.060029   10516 start.go:119] gopshost.Virtualization returned error: not implemented yet
I1102 07:22:20.083212   10516 out.go:177] 😄  minikube v1.23.2 on Darwin 11.6.1
😄  minikube v1.23.2 on Darwin 11.6.1
I1102 07:22:20.083298   10516 notify.go:169] Checking for updates...
I1102 07:22:20.121953   10516 out.go:177]     ▪ MINIKUBE_ACTIVE_DOCKERD=minikube
    ▪ MINIKUBE_ACTIVE_DOCKERD=minikube
I1102 07:22:20.122779   10516 config.go:177] Loaded profile config "minikube": Driver=hyperkit, ContainerRuntime=docker, KubernetesVersion=v1.22.2
I1102 07:22:20.122872   10516 driver.go:343] Setting default libvirt URI to qemu:///system
I1102 07:22:20.125696   10516 main.go:130] libmachine: Found binary path at /Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit
I1102 07:22:20.125754   10516 main.go:130] libmachine: Launching plugin server for driver hyperkit
I1102 07:22:20.137248   10516 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:54573
I1102 07:22:20.137759   10516 main.go:130] libmachine: () Calling .GetVersion
I1102 07:22:20.138319   10516 main.go:130] libmachine: Using API Version  1
I1102 07:22:20.138336   10516 main.go:130] libmachine: () Calling .SetConfigRaw
I1102 07:22:20.138620   10516 main.go:130] libmachine: () Calling .GetMachineName
I1102 07:22:20.138746   10516 main.go:130] libmachine: (minikube) Calling .DriverName
I1102 07:22:20.181922   10516 out.go:177] ✨  Using the hyperkit driver based on existing profile
✨  Using the hyperkit driver based on existing profile
I1102 07:22:20.181953   10516 start.go:278] selected driver: hyperkit
I1102 07:22:20.181965   10516 start.go:751] validating driver "hyperkit" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.23.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:hyperkit HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:192.168.64.7 Port:8443 KubernetesVersion:v1.22.2 ControlPlane:true Worker:true}] Addons:map[ambassador:false auto-pause:false csi-hostpath-driver:false dashboard:false default-storageclass:true efk:false freshpod:false gcp-auth:false gvisor:false helm-tiller:false ingress:false ingress-dns:false istio:false istio-provisioner:false kubevirt:false logviewer:false metallb:false metrics-server:false nvidia-driver-installer:false nvidia-gpu-device-plugin:false olm:false pod-security-policy:false portainer:false registry:false registry-aliases:false registry-creds:false storage-provisioner:true storage-provisioner-gluster:false volumesnapshots:false] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0}
I1102 07:22:20.182172   10516 start.go:762] status for hyperkit: {Installed:true Healthy:true Running:true NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I1102 07:22:20.182310   10516 install.go:52] acquiring lock: {Name:mk4023283b30b374c3f04c8805d539e68824c0b8 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1102 07:22:20.182439   10516 install.go:117] Validating docker-machine-driver-hyperkit, PATH=/Users/j.santander-vela/.minikube/bin:/Users/j.santander-vela/opt/anaconda3/bin:/Users/j.santander-vela/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/munki:/opt/X11/bin:/Library/Apple/usr/bin
I1102 07:22:20.191963   10516 install.go:137] /Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit version is 1.23.2
I1102 07:22:20.199162   10516 install.go:79] stdout: /Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit
I1102 07:22:20.199190   10516 install.go:81] /Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit looks good
I1102 07:22:20.199456   10516 cni.go:93] Creating CNI manager for ""
I1102 07:22:20.199469   10516 cni.go:167] CNI unnecessary in this configuration, recommending no CNI
I1102 07:22:20.199492   10516 start_flags.go:278] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.23.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:hyperkit HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:192.168.64.7 Port:8443 KubernetesVersion:v1.22.2 ControlPlane:true Worker:true}] Addons:map[ambassador:false auto-pause:false csi-hostpath-driver:false dashboard:false default-storageclass:true efk:false freshpod:false gcp-auth:false gvisor:false helm-tiller:false ingress:false ingress-dns:false istio:false istio-provisioner:false kubevirt:false logviewer:false metallb:false metrics-server:false nvidia-driver-installer:false nvidia-gpu-device-plugin:false olm:false pod-security-policy:false portainer:false registry:false registry-aliases:false registry-creds:false storage-provisioner:true storage-provisioner-gluster:false volumesnapshots:false] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0}
I1102 07:22:20.199740   10516 iso.go:123] acquiring lock: {Name:mkd2a64b18ba55eb2fc9a5db11923cd0ee528cc0 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1102 07:22:20.243892   10516 out.go:177] 👍  Starting control plane node minikube in cluster minikube
👍  Starting control plane node minikube in cluster minikube
I1102 07:22:20.243928   10516 preload.go:131] Checking if preload exists for k8s version v1.22.2 and runtime docker
I1102 07:22:20.243973   10516 preload.go:147] Found local preload: /Users/j.santander-vela/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v13-v1.22.2-docker-overlay2-amd64.tar.lz4
I1102 07:22:20.243995   10516 cache.go:57] Caching tarball of preloaded images
I1102 07:22:20.244159   10516 preload.go:173] Found /Users/j.santander-vela/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v13-v1.22.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I1102 07:22:20.244173   10516 cache.go:60] Finished verifying existence of preloaded tar for  v1.22.2 on docker
I1102 07:22:20.244293   10516 profile.go:148] Saving config to /Users/j.santander-vela/.minikube/profiles/minikube/config.json ...
I1102 07:22:20.245663   10516 cache.go:206] Successfully downloaded all kic artifacts
I1102 07:22:20.245699   10516 start.go:313] acquiring machines lock for minikube: {Name:mk73a6af75d8100d00bc1cfa43b9a9676ce5c889 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I1102 07:22:20.245769   10516 start.go:317] acquired machines lock for "minikube" in 53.871µs
I1102 07:22:20.245798   10516 start.go:93] Skipping create...Using existing machine configuration
I1102 07:22:20.245808   10516 fix.go:55] fixHost starting: 
I1102 07:22:20.246088   10516 main.go:130] libmachine: Found binary path at /Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit
I1102 07:22:20.246113   10516 main.go:130] libmachine: Launching plugin server for driver hyperkit
I1102 07:22:20.255683   10516 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:54577
I1102 07:22:20.256133   10516 main.go:130] libmachine: () Calling .GetVersion
I1102 07:22:20.256517   10516 main.go:130] libmachine: Using API Version  1
I1102 07:22:20.256539   10516 main.go:130] libmachine: () Calling .SetConfigRaw
I1102 07:22:20.256853   10516 main.go:130] libmachine: () Calling .GetMachineName
I1102 07:22:20.256975   10516 main.go:130] libmachine: (minikube) Calling .DriverName
I1102 07:22:20.257096   10516 main.go:130] libmachine: (minikube) Calling .GetState
I1102 07:22:20.257227   10516 main.go:130] libmachine: (minikube) DBG | exe=/Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit uid=0
I1102 07:22:20.257348   10516 main.go:130] libmachine: (minikube) DBG | hyperkit pid from json: 1374
I1102 07:22:20.258855   10516 main.go:130] libmachine: (minikube) DBG | hyperkit pid 1374 missing from process table
I1102 07:22:20.258893   10516 fix.go:108] recreateIfNeeded on minikube: state=Stopped err=<nil>
I1102 07:22:20.258911   10516 main.go:130] libmachine: (minikube) Calling .DriverName
W1102 07:22:20.259010   10516 fix.go:134] unexpected machine state, will restart: <nil>
I1102 07:22:20.278028   10516 out.go:177] 🔄  Restarting existing hyperkit VM for "minikube" ...
🔄  Restarting existing hyperkit VM for "minikube" ...
I1102 07:22:20.278055   10516 main.go:130] libmachine: (minikube) Calling .Start
I1102 07:22:20.278231   10516 main.go:130] libmachine: (minikube) DBG | exe=/Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit uid=0
I1102 07:22:20.278277   10516 main.go:130] libmachine: (minikube) DBG | clean start, hyperkit pid file doesn't exist: /Users/j.santander-vela/.minikube/machines/minikube/hyperkit.pid
I1102 07:22:20.278296   10516 main.go:130] libmachine: (minikube) DBG | Using UUID d5b8d362-3b80-11ec-9972-acde48001122
I1102 07:22:20.299603   10516 main.go:130] libmachine: (minikube) DBG | virtio_net: Could not create vmnet interface, permission denied or no entitlement?
I1102 07:22:20.299773   10516 fix.go:57] fixHost completed within 53.961071ms
I1102 07:22:20.299796   10516 start.go:80] releasing machines lock for "minikube", held for 54.017582ms
W1102 07:22:20.299812   10516 start.go:522] error starting host: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1
W1102 07:22:20.299997   10516 out.go:242] 🤦  StartHost failed, but will try again: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🤦  StartHost failed, but will try again: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

I1102 07:22:20.300010   10516 start.go:537] Will try again in 5 seconds ...
I1102 07:22:25.302031   10516 start.go:313] acquiring machines lock for minikube: {Name:mk73a6af75d8100d00bc1cfa43b9a9676ce5c889 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I1102 07:22:25.302176   10516 start.go:317] acquired machines lock for "minikube" in 102.784µs
I1102 07:22:25.302207   10516 start.go:93] Skipping create...Using existing machine configuration
I1102 07:22:25.302213   10516 fix.go:55] fixHost starting: 
I1102 07:22:25.302609   10516 main.go:130] libmachine: Found binary path at /Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit
I1102 07:22:25.302638   10516 main.go:130] libmachine: Launching plugin server for driver hyperkit
I1102 07:22:25.318552   10516 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:54581
I1102 07:22:25.319645   10516 main.go:130] libmachine: () Calling .GetVersion
I1102 07:22:25.320281   10516 main.go:130] libmachine: Using API Version  1
I1102 07:22:25.320294   10516 main.go:130] libmachine: () Calling .SetConfigRaw
I1102 07:22:25.320668   10516 main.go:130] libmachine: () Calling .GetMachineName
I1102 07:22:25.320792   10516 main.go:130] libmachine: (minikube) Calling .DriverName
I1102 07:22:25.320905   10516 main.go:130] libmachine: (minikube) Calling .GetState
I1102 07:22:25.321011   10516 main.go:130] libmachine: (minikube) DBG | exe=/Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit uid=0
I1102 07:22:25.321147   10516 main.go:130] libmachine: (minikube) DBG | hyperkit pid from json: 1374
I1102 07:22:25.322645   10516 main.go:130] libmachine: (minikube) DBG | hyperkit pid 1374 missing from process table
I1102 07:22:25.322674   10516 fix.go:108] recreateIfNeeded on minikube: state=Stopped err=<nil>
I1102 07:22:25.322683   10516 main.go:130] libmachine: (minikube) Calling .DriverName
W1102 07:22:25.322786   10516 fix.go:134] unexpected machine state, will restart: <nil>
I1102 07:22:25.350076   10516 out.go:177] 🔄  Restarting existing hyperkit VM for "minikube" ...
🔄  Restarting existing hyperkit VM for "minikube" ...
I1102 07:22:25.350109   10516 main.go:130] libmachine: (minikube) Calling .Start
I1102 07:22:25.350294   10516 main.go:130] libmachine: (minikube) DBG | exe=/Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit uid=0
I1102 07:22:25.350334   10516 main.go:130] libmachine: (minikube) DBG | clean start, hyperkit pid file doesn't exist: /Users/j.santander-vela/.minikube/machines/minikube/hyperkit.pid
I1102 07:22:25.350409   10516 main.go:130] libmachine: (minikube) DBG | Using UUID d5b8d362-3b80-11ec-9972-acde48001122
I1102 07:22:25.351655   10516 main.go:130] libmachine: (minikube) DBG | virtio_net: Could not create vmnet interface, permission denied or no entitlement?
I1102 07:22:25.351741   10516 fix.go:57] fixHost completed within 49.526774ms
I1102 07:22:25.351754   10516 start.go:80] releasing machines lock for "minikube", held for 49.567835ms
W1102 07:22:25.351903   10516 out.go:242] 😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

I1102 07:22:25.390932   10516 out.go:177] 

W1102 07:22:25.391086   10516 out.go:242] ❌  Exiting due to PR_HYPERKIT_VMNET_FRAMEWORK: Failed to start host: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

❌  Exiting due to PR_HYPERKIT_VMNET_FRAMEWORK: Failed to start host: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

W1102 07:22:25.391162   10516 out.go:242] 💡  Suggestion: Hyperkit networking is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --driver
💡  Suggestion: Hyperkit networking is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --driver
W1102 07:22:25.391175   10516 out.go:242] 🍿  Related issues:
🍿  Related issues:
W1102 07:22:25.391222   10516 out.go:242]     ▪ https://github.com/kubernetes/minikube/issues/6028
    ▪ https://github.com/kubernetes/minikube/issues/6028
W1102 07:22:25.391268   10516 out.go:242]     ▪ https://github.com/kubernetes/minikube/issues/5594
    ▪ https://github.com/kubernetes/minikube/issues/5594
I1102 07:22:25.429737   10516 out.go:177] 

**Minikube start with `virtualbox`**

~ minikube start --driver=virtualbox --alsologtostderr
I1102 07:25:59.309390   10738 out.go:298] Setting OutFile to fd 1 ...
I1102 07:25:59.314738   10738 out.go:350] isatty.IsTerminal(1) = false
I1102 07:25:59.314747   10738 out.go:311] Setting ErrFile to fd 2...
I1102 07:25:59.314791   10738 out.go:350] isatty.IsTerminal(2) = false
I1102 07:25:59.315752   10738 root.go:313] Updating PATH: /Users/j.santander-vela/.minikube/bin
I1102 07:25:59.317502   10738 oci.go:561] shell is pointing to dockerd inside minikube. will unset to use host
I1102 07:25:59.319087   10738 out.go:305] Setting JSON to false
I1102 07:25:59.356453   10738 start.go:111] hostinfo: {"hostname":"IT001163.local","uptime":30611,"bootTime":1635818148,"procs":574,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"11.6.1","kernelVersion":"20.6.0","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"abc69550-60c2-34fe-b307-c24a8c39309c"}
W1102 07:25:59.356605   10738 start.go:119] gopshost.Virtualization returned error: not implemented yet
I1102 07:25:59.381701   10738 out.go:177] * minikube v1.23.2 on Darwin 11.6.1
* minikube v1.23.2 on Darwin 11.6.1
I1102 07:25:59.383114   10738 notify.go:169] Checking for updates...
I1102 07:25:59.423186   10738 out.go:177]   - MINIKUBE_ACTIVE_DOCKERD=minikube
  - MINIKUBE_ACTIVE_DOCKERD=minikube
I1102 07:25:59.424691   10738 config.go:177] Loaded profile config "minikube": Driver=hyperkit, ContainerRuntime=docker, KubernetesVersion=v1.22.2
I1102 07:25:59.426218   10738 main.go:130] libmachine: Found binary path at /Users/j.santander-vela/.minikube/bin/docker-machine-driver-hyperkit
I1102 07:25:59.427965   10738 main.go:130] libmachine: Launching plugin server for driver hyperkit
I1102 07:25:59.438882   10738 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:54662
I1102 07:25:59.439764   10738 main.go:130] libmachine: () Calling .GetVersion
I1102 07:25:59.441237   10738 main.go:130] libmachine: Using API Version  1
I1102 07:25:59.441253   10738 main.go:130] libmachine: () Calling .SetConfigRaw
I1102 07:25:59.441498   10738 main.go:130] libmachine: () Calling .GetMachineName
I1102 07:25:59.441600   10738 main.go:130] libmachine: (minikube) Calling .DriverName
W1102 07:25:59.442640   10738 out.go:242] ! Deleting existing cluster minikube with different driver hyperkit due to --delete-on-failure flag set by the user. 
! Deleting existing cluster minikube with different driver hyperkit due to --delete-on-failure flag set by the user. 
I1102 07:25:59.462437   10738 out.go:177] 

W1102 07:25:59.462594   10738 out.go:242] ! Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "hyperkit" driver, which is incompatible with requested "virtualbox" driver.
! Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "hyperkit" driver, which is incompatible with requested "virtualbox" driver.
W1102 07:25:59.462749   10738 out.go:242] * Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=hyperkit'
* Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=hyperkit'
I1102 07:25:59.517245   10738 out.go:177] 
</code>
</details>

**Comment by juandesant** [comment]
Only tested on macOS Big Sur, might happen in other versions of macOS…

**Comment by medyagh** [comment]
thank u for this issue, I think we should detect internet sharing and let the user know how to disable it

**Comment by spowelljr** [comment]
A solution message was added with https://github.com/kubernetes/minikube/pull/12863, closing issue
