### ISSUE TITLE
Minikube wont start 6.2 VirtualBox

### ISSUE THREAD

**Issue by veperales** [kubernetes/minikube#12850]
**Steps to reproduce the issue:** 

1. ➜  ~ minikube start --driver=virtualbox
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

I was not able to get the log, dont know if I did it correctly.. still here's the output.

MacbookPro 2015 running Latest big sur OS. / 6.2 VirtualBox.
I do have VMware Fusion Installed but I set driver to virtualbox since the beginning using 
minikube config set driver virtualbox

<details>
😄  minikube v1.23.2 on Darwin 11.6.1
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create: creating: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet5 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: creating: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet6 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet6 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

➜  ~ minikube logs --file=logs.txt
🤷  The control plane node must be running for this command
👉  To start a cluster, run: "minikube start"

</details>

**Comment by medyagh** [comment]
@veperales we are aware of a virtubalox issue with newest vbox

there is a PR that fixes it

https://github.com/kubernetes/minikube/pull/12811

here is the link to the binary from a PR that I think might fix this issue, do you mind trying it out ?

http://storage.googleapis.com/minikube-builds/12811/minikube-linux-amd64
http://storage.googleapis.com/minikube-builds/12811/minikube-darwin-amd64
http://storage.googleapis.com/minikube-builds/12811/minikube-windows-amd64.exe

**Comment by veperales** [comment]
@medyagh Thank you for replying!.

Indeed it fixed my issue.#12811

I am now able to start my minikube and seems to be working properly.

**Comment by klaases** [comment]
Hi **@veperales**, is this issue still occurring?

From what I can tell, kubectl is pointing to a k8s cluster config that is not running.

Maybe try starting k8s and then re-starting minikube.

Also the command `minikube update context` may help point to the running k8s cluster.

**Comment by veperales** [comment]
@klaases ,

I did a workaround to solve my issue. 
that consisted in uninstalling and reinstall everything using brew.
then recreate the cluster and now everything was working as it should.

I posted my findings and procedure in another thread.

I think we can close this one.
