### ISSUE TITLE
VMware driver does not support amd64 (Apple Silicon) architecture on macOS

### ISSUE THREAD

**Issue by hendrikhalkow** [kubernetes/minikube#12858]
**Steps to reproduce the issue:** 

```
minikube start --driver=vmware
😄  minikube v1.23.2 on Darwin 12.0.1 (arm64)
✨  Using the vmware driver based on user configuration

❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'vmware' is not supported on darwin/arm64
```

Could you please implement darwin/amd64 support? Thanks :-)

**Comment by afbjorklund** [comment]
I think this is an issue for https://github.com/machine-drivers/docker-machine-driver-vmware

**Comment by klaases** [comment]
Hi @hendrikhalkow, were you able to review @afbjorklund's comment? Perhaps filing an issue with https://github.com/machine-drivers/docker-machine-driver-vmware would help in this case.

If needed, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as some time has passed.

Thank you for sharing your experience!
