### ISSUE TITLE
service question

### ISSUE THREAD

**Issue by employeeeee** [kubernetes/minikube#12853]
**重现问题所需的命令**：
minikube service k8s-demo-svc --url
**失败的命令的完整输出**：<details>

</details>
Exiting due to SVC_TUNNEL_START: creating ssh conn: listen tcp *********: bind: can't assign requested address

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
macos

**Comment by klaases** [comment]
From what I can tell, the requested port that is needed for SSH is already in use.

Please consider stopping whatever process is currently using the SSH port.

=== From Google Translate / 来自谷歌翻译 ===

据我所知，SSH 所需的请求端口已在使用中。

请考虑停止当前正在使用 SSH 端口的任何进程。

**Comment by klaases** [comment]
Hi @[employeeeee](https://github.com/employeeeee) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

---

嗨@[employeeeee](https://github.com/employeeeee)——这个问题还在发生吗？是否有其他详细信息？如果是这样，请随时通过使用 `/reopen` 评论重新打开问题。由于无法获得更多信息并且已经过了一段时间，此问题将被关闭。

可能有帮助的其他信息：

* 问题是否出现在最新的 minikube 版本中

* 使用的确切 minikube 启动命令行

* 附上minikube日志的完整输出，运行`minikube logs --file=logs.txt`创建日志文件

感谢您分享您的经验！
