### ISSUE TITLE
Outdated tutorial: ingress-dns not working on Big Sur (MacOS)

### ISSUE THREAD

**Issue by exocode** [kubernetes/minikube#12876]
Hi there

I try to follow this totorial for `ingress-dns` addon: https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/

**But I can't get it working.** 
If you need further informations please let me know.

I am on MacOS 11.6 (20G165)

**Steps to reproduce the issue:** 

This is my `minikube-minikube-test` in `/etc/resolver` (which is an alias for `/private/etc/resolver`):

```shell
domain test
nameserver 192.168.49.2 # which is the ip of 'minikube ip'
search_order 1
timeout 5
```

1. `brew install minikube`
2. `minikube start`
3. `minikube addons enable ingress-dns`
4. `minikube tunnel (as described in the output of step 3 (missing in tutorial)`
4. `kubectl apply -f https://raw.githubusercontent.com/kubernetes/minikube/master/deploy/addons/ingress-dns/example/example.yaml`
5. `nslookup hello-john.test $(minikube ip)`
6. `ping hello-john.test`

What can I do to get this running. I have no error messages in any of the running

[logs.txt](https://github.com/kubernetes/minikube/files/7491350/logs.txt)

```

❯ k get ingress --all-namespaces -o wide
NAMESPACE     NAME              CLASS   HOSTS                             ADDRESS   PORTS   AGE
kube-system   example-ingress   nginx   hello-john.test,hello-jane.test             80      10m

    ~ ──────────────────────────────────────────────────────────────────────────────────────────────────── minikube ⎈
❯ k get svc --all-namespaces
NAMESPACE     NAME              TYPE           CLUSTER-IP     EXTERNAL-IP                                 PORT(S)                  AGE
default       hello-world-app   NodePort       10.98.148.50   <none>                                      80:31178/TCP             10m
default       kubernetes        ClusterIP      10.96.0.1      <none>                                      443/TCP                  15m
kube-system   hello-world-app   ExternalName   <none>         hello-world-app.default.svc.cluster.local   <none>                   10m
kube-system   kube-dns          ClusterIP      10.96.0.10     <none>                                      53/UDP,53/TCP,9153/TCP   15m

```

BTW: regular `addons enable ingress` not described anywhere in the docs.

**Comment by spowelljr** [comment]
Hi @exocode, thanks for creating your issue with minikube!

Is it the `nslookup` and `ping` commands that aren't working for you?

I see you're using the Docker driver and I know with networking Docker differs in many ways. Have you tried using the `hyperkit` driver? I've been able to get `nslookup` and `ping` using it.

**Comment by exocode** [comment]
@spowelljr you are right with Hyperkit I got it working. 🤔

**Comment by bound2** [comment]
If anybody is still struggling with this issue.

```
brew install hyperkit
minikube start --driver=hyperkit
minikube addons enable ingress
minikube addons enable ingress-dns
# make sure to update minikube ip in /etc/resolver/test

# restart dns
sudo killall -HUP mDNSResponder
# verify that your dns test resolver shows here
scutil --dns 
# start hello world
kubectl apply -f https://raw.githubusercontent.com/kubernetes/minikube/master/deploy/addons/ingress-dns/example/example.yaml
ping hello-john.test
curl hello-john.test
```

It is actually documented here https://minikube.sigs.k8s.io/docs/drivers/docker/ that the ingress and ingress-dns only work in Linux.

**Comment by mattduguid** [comment]
I'm having similar issues after followed the same instructions from https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/ but im on an mac m1 chipset so installing hyperkit is not currently supported "hyperkit: The x86_64 architecture is required for this software."

i can see queries making it to the pod for ingress-dns but they always return empty results, any pointers appreciated

```
  questions: [ { name: 'kubernetes.default', type: 28, class: 1 } ],
  answers: [],
  authorities: [],
  additionals: []
```

**Comment by damianobarbati** [comment]
@bound2 the snippet you provided is not working, at least not on MacOS Ventura: the ping  / curl command hang.
```sh
# install and start minikube with hyperkit driver for VM
brew install minikube hyperkit
minikube start --cpus=2 --memory=4g --driver=hyperkit --addons=ingress,ingress-dns

# add resolver
sudo mkdir /etc/resolver 
echo -e "domain test\nnameserver $(minikube ip)\nsearch_order 1\ntimeout 5\n" | sudo tee /etc/resolver/minikube

# restart dns
sudo killall -HUP mDNSResponder

# verify that your dns test resolver shows here
scutil --dns 

# start hello world
kubectl apply -f https://raw.githubusercontent.com/kubernetes/minikube/master/deploy/addons/ingress-dns/example/example.yaml

# ping hangs
ping hello-john.test

# curl hangs
curl hello-john.test
```

Both ping and curl hang, do you have any suggestion? 😔

I can see the resolve listed:
```sh
resolver #8
  domain   : test
  nameserver[0] : 192.168.49.2
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000002 (Reachable)
  order    : 1
```sh
