### ISSUE TITLE
Cannot create minikube with hyperkit

### ISSUE THREAD

**Issue by leeadh** [kubernetes/minikube#12878]
**Steps to reproduce the issue:** 

Cannot create minikube with hyperkit.

[logs.txt](https://github.com/kubernetes/minikube/files/7492021/logs.txt)

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Hey @leeadh, I'm going to go ahead and close this issue. If you try the advice above and still have an issue, feel free to reopen this with more details.
