### ISSUE TITLE
minikube is not getting started

### ISSUE THREAD

**Issue by sbasu123** [kubernetes/minikube#12875]
**Steps to reproduce the issue:** 
C:\Users\sbasu>minikube start
* minikube v1.22.0 on Microsoft Windows 10 Home Single Language 10.0.19042 Build 19042
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
* Updating the running virtualbox "minikube" VM ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Error getting config for native Go SSH: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.

X Exiting due to GUEST_PROVISION: Failed to start host: provision: Error getting config for native Go SSH: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
*
╭──────────────────────────────────────────────────────────────────╮
│                                                                  │
│    * If the above advice does not help, please let us know:      │
│      https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                  │
│    * Please attach the following file to the GitHub issue:       │
│    * - C:\Users\sbasu\.minikube\logs\lastStart.txt               │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯
1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
C:\Users\sbasu>minikube logs --file=logs.txt
E1106 19:01:36.382273   20068 logs.go:267] Failed to list containers for "kube-apiserver": docker: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
E1106 19:01:38.342421   20068 logs.go:267] Failed to list containers for "etcd": docker: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
E1106 19:01:40.058518   20068 logs.go:267] Failed to list containers for "coredns": docker: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
E1106 19:01:41.920202   20068 logs.go:267] Failed to list containers for "kube-scheduler": docker: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
E1106 19:01:43.686667   20068 logs.go:267] Failed to list containers for "kube-proxy": docker: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
E1106 19:01:45.520055   20068 logs.go:267] Failed to list containers for "kubernetes-dashboard": docker: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
E1106 19:01:46.707628   20068 logs.go:267] Failed to list containers for "storage-provisioner": docker: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
E1106 19:01:48.630737   20068 logs.go:267] Failed to list containers for "kube-controller-manager": docker: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied.
E1106 19:01:50.621649   20068 logs.go:190] command /bin/bash -c "sudo journalctl -u docker -n 60" failed with error: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied. output: ""
E1106 19:01:51.941467   20068 logs.go:190] command /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a" failed with error: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied. output: ""
E1106 19:01:53.561917   20068 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.21.2/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied. output: ""
E1106 19:01:55.806512   20068 logs.go:190] command /bin/bash -c "sudo dmesg -PH -L=never --level warn,err,crit,alert,emerg | tail -n 60" failed with error: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied. output: ""
E1106 19:01:58.455329   20068 logs.go:190] command /bin/bash -c "uptime && uname -a && grep PRETTY /etc/os-release" failed with error: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied. output: ""
E1106 19:01:59.865462   20068 logs.go:190] command /bin/bash -c "sudo journalctl -u kubelet -n 60" failed with error: NewSession: new client: new client: Error creating new native config from ssh using: docker, &{[] [C:\Users\sbasu\.minikube\machines\minikube\id_rsa]}: open C:\Users\sbasu\.minikube\machines\minikube\id_rsa: Access is denied. output: ""

! unable to fetch logs for: Docker, container status, describe nodes, dmesg, kernel, kubelet
[logs.txt](https://github.com/kubernetes/minikube/files/7490527/logs.txt)

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by SatishChandraPalakoti** [comment]
@sbasu123 did you resolve it ?

**Comment by sbasu123** [comment]
I run minikube delete and then reinstall minikube higher version , that resolve the issue 
 
  On Mon, 8 Nov 2021 at 11:39, Satish Chandra ***@***.***> wrote:   


@sbasu123 did you resolve it ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sharifelgamal** [comment]
Looks like this was resolved, I'll go ahead and close this.

**Comment by sbasu123** [comment]
Hi ,It is resolved.
Regards
Siddhartha Basu 
 
  On Thu, 16 Dec 2021 at 1:54, Sharif ***@***.***> wrote:   


Looks like this was resolved, I'll go ahead and close this.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
