### ISSUE TITLE
Using minikube for hosting a staging server?

### ISSUE THREAD

**Issue by tamis-laan** [kubernetes/minikube#12879]
Is it possible to run minikube on a server as a staging testing area? 

I would like to use gitlab CI/CD to build and deploy to minikube running on the same machine. 

If this is possible, is there some guide available?

**Comment by afbjorklund** [comment]
There are some examples here: https://minikube.sigs.k8s.io/docs/tutorials/continuous_integration/

**Comment by tamis-laan** [comment]
> There are some examples here: https://minikube.sigs.k8s.io/docs/tutorials/continuous_integration/

This is not really what I was looking for, here Gitlab Ci/CD pipeline starts downloads minikube:
[https://github.com/minikube-ci/examples/blob/master/.gitlab-ci.yml](https://github.com/minikube-ci/examples/blob/master/.gitlab-ci.yml) 

I'm looking to automatically build my code with gitlab CI/CD and deploy it to a kubernetes cluster (setup with minikube).

**Comment by afbjorklund** [comment]
You don't need minikube for that, just the kubeconfig to your existing cluster

**Comment by spowelljr** [comment]
This issue has been open for a while without any further questions so I'm going to close this issue. Feel free to reopen and ask further questions if needed, thanks!
