### ISSUE TITLE
不支持Mac M1笔记本

### ISSUE THREAD

**Issue by pywangwwei** [kubernetes/minikube#12874]
▪ You are trying to run amd64 binary on M1 system. Please consider running darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.23.1/minikube-darwin-arm64.)
😄  Darwin 11.2.1 上的 minikube v1.23.1
✨  自动选择 parallels 驱动。其他选项：virtualbox, ssh
💿  正在下载 VM boot image...
    > minikube-v1.23.1.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
🎉  minikube 1.23.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.23.2
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

    > minikube-v1.23.1.iso: 225.22 MiB / 225.22 MiB [] 100.00% 5.04 MiB p/s 45s
👍  Starting control plane node minikube in cluster minikube
🔥  Creating parallels VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
❗  The image 'registry.cn-hangzhou.aliyuncs.com/google_containers/coredns/coredns:v1.8.4' was not found; unable to add it to cache.
🔥  正在删除 parallels 中的“minikube”…
🤦  StartHost failed, but will try again: creating host: create: creating: exit status 255
🔥  Creating parallels VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start parallels VM. Running "minikube delete" may fix it: creating host: create: creating: exit status 255
❗  Startup with parallels driver failed, trying with alternate driver virtualbox: Failed to start host: creating host: create: creating: exit status 255
🔥  正在删除 parallels 中的“minikube”…
💀  Removed all traces of the "minikube" cluster.
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
❗  The image 'registry.cn-hangzhou.aliyuncs.com/google_containers/coredns/coredns:v1.8.4' was not found; unable to add it to cache.
🤦  StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: exit status 255

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

xianwei.wang@xianweiwangdeMacBook-Pro ~ % minikube logs --file=logs.txt
    ▪ You are trying to run amd64 binary on M1 system. Please consider running darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.23.1/minikube-darwin-arm64.)
🤷  The control plane node "" does not exist.
👉  To start a cluster, run: "minikube start"
xianwei.wang@xianweiwangdeMacBook-Pro ~ %

**Comment by spowelljr** [comment]
Hi @pywangwwei, in our logs you see the following `You are trying to run amd64 binary on M1 system. Please consider running darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.23.1/minikube-darwin-arm64.)`
Please try downloading the arm64 binary and using it and see if that resolves your issue, thanks!

-----

嗨@pywangwwei，在我们的日志中，您会看到以下内容`您正在尝试在 M1 系统上运行 amd64 二进制文件。请考虑运行 darwin/arm64 二进制文件（You are trying to run amd64 binary on M1 system. Please consider running darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.23.1/minikube-darwin-arm64.)`
请尝试下载 arm64 二进制文件并使用它，看看是否能解决您的问题，谢谢！

**Comment by medyagh** [comment]
I recommend downloading the right binary for M1 to avoid that warning

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-arm64
sudo install minikube-darwin-arm64 /usr/local/bin/minikube 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by medyagh** [comment]
我建议为 M1 下载正确的二进制文件以避免该警告

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-arm64
须藤安装 minikube-darwin-arm64 /usr/local/bin/minikube

我将暂时关闭此问题，但请随时在您准备好提供更多信息时重新打开。 
Wǒ jiànyì wèi M1 xiàzài zhèngquè de èrjìnzhì wénjiàn yǐ bìmiǎn gāi jǐnggào
