### ISSUE TITLE
minikube can't re-configure ingress to use a different ssl certificate

### ISSUE THREAD

**Issue by LanDinh** [kubernetes/minikube#12896]
**Steps to reproduce the issue:** 

Tutorial that was followed: https://minikube.sigs.k8s.io/docs/tutorials/custom_cert_ingress/

1. start minikube locally `minikube start`
2. enable ingress `minikube addons enable ingress`
3. add the auto-generated certificate in .pem:
  4. `kubectl -n kube-system create secret tls mkcert --key ~/.minikube/key.pem --cert ~/.minikube/cert.pem`
  5. `minikube addons configure ingress`
  6. In the prompt to add the certificate: be stupid and have a typo: `bogus-namespace/mkcert`
7. Re-enable the ingress:
  8. `minikube addons disable ingress`
  9. `minikube addons enable ingress`
10.  Notice the mistake
11. Try to re-configure the ingress: `minikube addons configure ingress`
12. instead of getting the prompt again, it auto-proceeds to `ingress was successfully configured` <--- this is the bug! Why would I be stuck with this typo forever?

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by medyagh** [comment]
cc: @sharifelgamal

**Comment by sharifelgamal** [comment]
yeah, I can reproduce this pretty easily, it seems like it's by design: 

https://github.com/kubernetes/minikube/blob/2ec8875aedf248c98a4647ad19db0321014b0b67/cmd/minikube/cmd/config/configure.go#L223-L225

I agree that calling `minikube addons configure ingress` should allow for overriding existing config, so I'll add it our short term work to fix.

**Comment by medyagh** [comment]
@LanDinh 

There is a PR that might fix this issue,  here is the link to the binary from a PR that I think might fix this issue, do you mind trying it out ?

http://storage.googleapis.com/minikube-builds/12897/minikube-linux-amd64
http://storage.googleapis.com/minikube-builds/12897/minikube-darwin-amd64
http://storage.googleapis.com/minikube-builds/12897/minikube-windows-amd64.exe

**Comment by LanDinh** [comment]
I confirm that this is working - I especially like the warning about overwriting an existing certificate :) thanks!
