### ISSUE TITLE
version 1.19 not supported?

### ISSUE THREAD

**Issue by leeadh** [kubernetes/minikube#12895]
minikube start --cpus 8 --memory 8000 --disk-size=128g --kubernetes-version v1.19
😄  minikube v1.24.0 on Darwin 11.6

❌  Exiting due to MK_USAGE: Unable to parse "v1.19": No Major.Minor.Patch elements found

Why?

**Comment by sharifelgamal** [comment]
The kubernetes version you request needs to be a proper semver object (thus the `No Major.Minor.Patch elements found` error) so it needs to be v1.19.0, not just v1.19

**Comment by klaases** [comment]
Hi @leeadh – were you able to follow sharif's suggestion above?

Closing out for now, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.
