### ISSUE TITLE
Missing documentation for NFS mounts

### ISSUE THREAD

**Issue by mcgitty** [kubernetes/minikube#12898]
In this documentation topic: "[Driver mounts](https://minikube.sigs.k8s.io/docs/handbook/mount/#driver-mounts)", the last entry in the table is:

`HyperKit | Linux | Unsupported (see NFS mounts)`

The issues are:
1. There is no documentation on "NFS mounts" to "see".
2. HyperKit (without Docker) is supported in MacOS, and you can make "NFS mounts" work in MacOS. Therefore, either this last entry column 2 be replaced with "MacOS" or add a new entry for "MacOS".

**Comment by klaases** [comment]
Will update the documentation, replacing Linux with macOS and marking as unsupported without `(see NFS mounts)`, per #13399.

FWIW, as far as `NFS mounts` documentation goes, this would be unique to each Linux distro, as each kernel will have its own documentation, like `man mount`.

**Comment by klaases** [comment]
FWIW, as far as `NFS mounts` documentation goes, this would be unique to each Linux distro, as each kernel will have its own documentation, like `man mount`.
