### ISSUE TITLE
Got permission denied while trying to connect to the Docker  when run minikube ssh 

### ISSUE THREAD

**Issue by abdelrazekrizk** [kubernetes/minikube#12912]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

ubuntu@ip-172-31-90-31:~$ minikube ssh

❌  Exiting due to GUEST_STATUS: state: unknown state "minikube": docker container inspect minikube --format=: exit status 1
stdout:

stderr:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/minikube/json": dial unix /var/run/docker.sock: connect: permission denied

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_ssh_e281f3aa4a4b0cf42eacd9b50a963829e109d436_0.log                     │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

ubuntu@ip-172-31-90-31:~$ minikube logs --file=logs.txt

❌  Exiting due to GUEST_STATUS: state: unknown state "minikube": docker container inspect minikube --format=: exit status 1
stdout:

stderr:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/minikube/json": dial unix /var/run/docker.sock: connect: permission denied

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_logs_c49e5676455064afca239bda3e1aa61c4ad27f61_0.log                    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

**Full output of failed command if not `minikube start`:**
<details>
Log file created at: 2021/11/09 21:44:40
Running on machine: ip-172-31-90-31
Binary: Built with gc go1.17.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1109 21:44:40.703092    3200 out.go:297] Setting OutFile to fd 1 ...
I1109 21:44:40.703325    3200 out.go:349] isatty.IsTerminal(1) = true
I1109 21:44:40.703332    3200 out.go:310] Setting ErrFile to fd 2...
I1109 21:44:40.703339    3200 out.go:349] isatty.IsTerminal(2) = true
I1109 21:44:40.703432    3200 root.go:313] Updating PATH: /home/ubuntu/.minikube/bin
W1109 21:44:40.704172    3200 root.go:291] Error reading config file at /home/ubuntu/.minikube/config/config.json: open /home/ubuntu/.minikube/config/config.json: no such file or directory
I1109 21:44:40.709070    3200 mustload.go:65] Loading cluster: minikube
I1109 21:44:40.712433    3200 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.22.3
I1109 21:44:40.715816    3200 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
W1109 21:44:40.764101    3200 cli_runner.go:162] docker container inspect minikube --format={{.State.Status}} returned with exit code 1
I1109 21:44:40.768907    3200 out.go:176] 
W1109 21:44:40.769041    3200 out.go:241] ❌  Exiting due to GUEST_STATUS: state: unknown state "minikube": docker container inspect minikube --format=: exit status 1
stdout:

stderr:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/minikube/json": dial unix /var/run/docker.sock: connect: permission denied

W1109 21:44:40.769069    3200 out.go:241] 
W1109 21:44:40.773916    3200 out.go:241] [31m╭───────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                             [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                             [31m│[0m
[31m│[0m    - /tmp/minikube_ssh_e281f3aa4a4b0cf42eacd9b50a963829e109d436_0.log                     [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯[0m

</details>

**Comment by abdelrazekrizk** [comment]
ubuntu@ip-172-31-90-31:~$ minikube start
😄  minikube v1.24.0 on Ubuntu 20.04
✨  Using the docker driver based on existing profile

💣  Exiting due to PROVIDER_DOCKER_NEWGRP: "docker version --format -" exit status 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied
💡  Suggestion: Add your user to the 'docker' group: 'sudo usermod -aG docker $USER && newgrp docker'
📘  Documentation: https://docs.docker.com/engine/install/linux-postinstall/

**Comment by spowelljr** [comment]
Hi @abdelrazekrizk, thanks for reporting your issue with minikube!

Have you run the following?
```
$ sudo groupadd docker
$ sudo usermod -aG docker $USER
$ newgrp docker
```

**Comment by abdelrazekrizk** [comment]
yes
but I also run another one you can see it in 
https://github.com/abdelrazekrizk/Project-4-ml-microservice-kubernetes#install-docker-engine-on-ubuntu
but when I close my instance in AWS
and open it after that I need to run the same command again
but if you ask if that work yes it is that command start docker and can start Kubectl after that
I hope my answer covers your request

**Comment by spowelljr** [comment]
That's odd that you have to re-run that command every time you reconnect to your AWS instance. Are you always logging in as the same user?

This doesn't seem to be a minikube error itself, this is the result of your user not being in the `docker` group and therefore not being able to run `docker` commands without `sudo`.

**Comment by spowelljr** [comment]
Hi @abdelrazekrizk, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
