### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by pabloelisseo** [kubernetes/minikube#12920]
**Steps to reproduce the issue:** 

1. minikube start
2. 
3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

[logs.txt](https://github.com/kubernetes/minikube/files/7513345/logs.txt)

</details>

**Comment by spowelljr** [comment]
Hi @pabloelisseo, thanks for reporting your issue with minikube!

There's an old issue that has a list of steps on how to resolve this, but the instructions are for Linux: https://github.com/kubernetes/minikube/issues/4835#issuecomment-532483752

If you try `minikube delete --all --purge` and `Remove-Item -Recurse -Force $HOMEPATH\.kube` and then try starting minikube again does that resolve your issue?

**Comment by pabloelisseo** [comment]
Yes! Thank you @spowelljr 
I tried uninstalling minikube and manually deleting the directories `.kube` and `.minikube `but I suppose that these `--all --purge` flags do something else.

I will close the thread as It solved my problem.

**Comment by spowelljr** [comment]
Glad that solved your issue, thanks for using minikube!

**Comment by bergstenarn** [comment]
Just would like to tell that I experienced the very same problem today. Fortunately the workaround above solved the problem, i.e.
```
minikube delete --all --purge
minkube start
```

FYI I have the following:

macOS Monterey, Version 12.3.1, MacBook Air M1
minikube version: v1.25.2, commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
Docker version 20.10.13, build a224086
