### ISSUE TITLE
Running minikube under lima

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#12926]
As an alternative to #12508, I looked into running minikube under [lima](https://github.com/lima-vm/lima).

It _mostly_ works, but there are some issues when using CRI and CNI...
The default is containerd rather than docker, so lima runs into these:

* A "docker" binary is required on the VM, even when using containerd

* The "none" driver chooses to run without any CNI, so the node fails.

These dependencies are not really properly documented, how to install:

* `conntrack`

* `crictl`

Another issue is that `/etc/cni/net.d` under lima is owned by root user:

```
apply cni: cni apply: copy: chmod /etc/cni/net.d/1-k8s.conflist: permission denied
```

You also get some scary looking minikube warnings:

```
Using the 'containerd' runtime with the 'none' driver is an untested configuration!
```

With some comments that don't really apply to the lima VM, which was already created:

```
The 'none' driver is designed for experts who need to integrate with an existing VM
Most users should use the newer 'docker' driver instead, which does not require root!
```

And there are some bogus warnings about moving config files from $HOME to $HOME:

```
kubectl and minikube configuration will be stored in /home/anders.linux
To use kubectl or minikube commands as your own user, you may need to relocate them.
```

---

But otherwise it works, after working around these:

```console
$ limactl start https://raw.githubusercontent.com/afbjorklund/lima/minikube/examples/minikube.yaml
? Creating an instance "minikube" Proceed with the default configuration
```

Internally, it will run:
`minikube start --driver=none --container-runtime=containerd --cni=bridge`

See the serial.log:
```
* minikube v1.24.0 on Ubuntu 20.04 (kvm/amd64)
* Using the none driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=4, Memory=3931MB, Disk=99067MB) ...

* Preparing Kubernetes v1.22.3 on containerd 1.5.7 ..
* Configuring bridge CNI (Container Networking Interface) ...
```

After boot, minikube is accessible over the limactl shell:

```console
$ limactl shell minikube kubectl version
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
$ limactl shell minikube kubectl cluster-info
Kubernetes control plane is running at https://192.168.5.15:8443
CoreDNS is running at https://192.168.5.15:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

And port 8443 (and all others) are mapped to localhost.

The footprint of cloud ubuntu is quite "heavy", compared...

```
542M	/home/anders/.lima/minikube/basedisk
2,9G	/home/anders/.lima/minikube/diffdisk
```

But the default alpine and k3s installation is much smaller.

See YAML file: https://github.com/afbjorklund/lima/blob/minikube/examples/minikube.yaml

Compare with kubeadm: https://github.com/lima-vm/lima/blob/master/examples/k8s.yaml

**Comment by afbjorklund** [comment]
@medyagh fyi

Running containerd right on the VM has a smaller footprint than running docker-in-docker on the VM...

But that could also be done, if cluster startup time (**excluding** virtual machine boot time) is important.

See [docker.yaml](https://github.com/lima-vm/lima/blob/master/examples/docker.yaml)

**Comment by medyagh** [comment]
@afbjorklund how about adding this as a tutorial in minikube site ? 

do we already have an issue for fixing containerd in none driver?

**Comment by afbjorklund** [comment]
> do we already have an issue for fixing containerd in none driver?

Not as far as I know, since docker is still the default container runtime for minikube

**Comment by saltbo** [comment]
> See [docker.yaml](https://github.com/lima-vm/lima/blob/master/examples/docker.yaml)
> 
> ```
> $ brew install lima
> $ limactl start https://raw.githubusercontent.com/lima-vm/lima/master/examples/docker.yaml
> $ brew install docker
> $ export DOCKER_HOST=unix://$HOME/.lima/docker/sock/docker.sock
> $ brew install minikube
> $ minikube start --driver=docker
> ```

I tried it, but I change the arch to x86_64 on my m1 MBP. minikube can't run...

The file `kubeadm` `kubectl` and `kubelet` is arm arch bin file. I don't understand why the files such as kubeadm are based on arm architecture in the container image of x86,

**Comment by afbjorklund** [comment]
At the moment, minikube _always_ runs the native architecture. Try "examples/k8s.yaml", if you want to emulate ?

**Comment by nirs** [comment]
@afbjorklund this option sound very interesting, what is current status?

**Comment by afbjorklund** [comment]
> @afbjorklund this option sound very interesting, what is current status?

Sorry, what option is that?

You can currently run both kubeadm and kind, right out of the box in Lima...

`limactl start template://k8s` _or maybe_

`limactl start && kind create cluster`

This uses containerd by default, there is no need to install Docker or Podman.

And it doesn't need `minikube`

**Comment by afbjorklund** [comment]
Lima is in this context more similar to Vagrant, than it is to VirtualBox.

Minikube has it's own QEMU driver, but so far there is no "[VZ](https://developer.apple.com/documentation/virtualization)" driver...

**Comment by nirs** [comment]
Sure you can use lima without minikube, but creating a k8s cluster is much slower compared with minikube. With minikube (libvirt driver) we can start a working cluster in 30 seconds. With lima the first time I tried took several minutes.

So I wonder if we can use a "lima" driver to start the vm (replacing libvirt), and then use the standard minikube flow to provision the vm.

**Comment by afbjorklund** [comment]
The biggest difference is probably in the package and image cache (there is none yet in lima, by default...), otherwise it should be the eaxct same `kubeadm` doing the bootstrapping in both of them - the "localkube" is no longer available.

The other features that would have to be provided by a minikube-ish wrapper is the kubectl installation and the dashboard deployment, for those you have to go to the original upstream documentation (they are also not included)

**Comment by afbjorklund** [comment]
> So I wonder if we can use a "lima" driver to start the vm (replacing libvirt), and then use the standard minikube flow to provision the vm.

It is possible to use the "none" or the "ssh" drivers in minikube, but unfortunately those are buggy and/or limited enough to not recommend...

**Comment by afbjorklund** [comment]
So while you _can_ use lima to provide a docker or a podman or an ubuntu, it's not really a minikube alternative.

The same drivers (virtualbox/libvirt/qemu/vz) are needed for both, whether it is a libmachine or if it is a lima driver.
