### ISSUE TITLE
Tab completion breaks if using recommended alias kubectl='minikube kubectl --'

### ISSUE THREAD

**Issue by vcc-huf** [kubernetes/minikube#12938]
1. install minkube
2. add alias kubectl='minikube kubectl --' to .bashrc
3. add source <(kubectl completion bash) to .bashrc

result:
only the commands get tab-completed, nothing after that.

the underlying issue is this:
```
$ minikube kubectl __completeNoDesc get p
Error: flags cannot be placed before plugin name: --cluster
```

this works however:
```
~/.minikube/cache/linux/v1.22.3/kubectl __completeNoDesc get p
```

related to this: https://github.com/kubernetes/kubectl/issues/884

**Comment by afbjorklund** [comment]
You could try making "kubectl" a symlink to "minikube", rather than a bash alias.

**Comment by vcc-huf** [comment]
found this workaround. put it in bashrc:

```
export KUBECTL_PATH="$HOME/.minikube/cache/linux/$(minikube kubectl -- version -o json | jq -r '.clientVersion.gitVersion')/kubectl"

kubectl() {
    exec $KUBECTL_PATH "$@"
}

source <(kubectl completion bash)

```

**Comment by vcc-huf** [comment]
> You could try making "kubectl" a symlink to "minikube", rather than a bash alias.

nah, same problem, minikube starts kubectl with --cluster minikube before the completion stuff, and kubectl cant handle that (see the bug i linked).

**Comment by medyagh** [comment]
hm.. that seems like a feature it can't do, I would accept a purposal or a PR that would fix or find a work around for this?

we would need to add the --cluster because the user might have multiple clusters and that had caused our tests to fail

**Comment by vcc-huf** [comment]
well, until they fix kubectl, you can maybe provide an official and supported way to directly call the kubectl installed by minikube?
the one i discovered is rather a hack.

**Comment by vcc-huf** [comment]
just realized that my hack doesnt work if the minikube node is down... because of reasons.

this does work however:
```
KUBECTL_PATH="$HOME/.minikube/cache/linux/$(minikube kubectl -- version 2>/dev/null | perl -lne '/GitVersion:"([^"]*)"/ && print $1')/kubectl"
```

it's even worse though.

**Comment by medyagh** [comment]
> just realized that my hack doesnt work if the minikube node is down... because of reasons.
> 
> this does work however:
> 
> ```
> KUBECTL_PATH="$HOME/.minikube/cache/linux/$(minikube kubectl -- version 2>/dev/null | perl -lne '/GitVersion:"([^"]*)"/ && print $1')/kubectl"
> ```
> 
> it's even worse though.

@vcc-huf is this a good work arround ? if yes you could add it to our website as a tip for other users

**Comment by oldium** [comment]
Same on Windows actually. The command `minikube kubectl` is broken with regards to autocomplete (i.e. command `__completion`) in PowerShell too.

**Comment by oldium** [comment]
Maybe it would be sufficient to update the following line to simply accept `__completion` in the same was as `--help`: https://github.com/kubernetes/minikube/blob/8d34afdf449ed905f2da10be917153c27b285d9a/cmd/minikube/cmd/kubectl.go#L99

**Comment by oldium** [comment]
Created PullRequest with the fix, now the `__complete` request is passed as-is to `kubectl`.

**Comment by vipseixas** [comment]
> just realized that my hack doesnt work if the minikube node is down... because of reasons.
> 
> this does work however:
> 
> ```
> KUBECTL_PATH="$HOME/.minikube/cache/linux/$(minikube kubectl -- version 2>/dev/null | perl -lne '/GitVersion:"([^"]*)"/ && print $1')/kubectl"
> ```
> 
> it's even worse though.

I had to change this a little to work:

```
KUBECTL_PATH="$HOME/.minikube/cache/linux/amd64/$(minikube kubectl -- version --client 2>/dev/null | perl -lne '/GitVersion:"([^"]*)"/ && print $1')/kubectl"
```
