### ISSUE TITLE
ssh: handshake failed: ssh: unable to authenticate

### ISSUE THREAD

**Issue by poiskail23** [kubernetes/minikube#12939]
Hello, looks like version 1.23.2 causes below issue when running "minikube start":
**provision: Temporary Error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain**

I downgraded to version 1.23.0 and it works fine.

**Information**
Docker version: Docker Desktop 4.1.1 (69879)
Operating system: Win10
Minikube installed via: chocolatey
Powershell Version: 5.1.19041.1320

**Comment by poiskail23** [comment]
#3930 reported the same kind of issue:
https://github.com/kubernetes/minikube/issues/3930

**Comment by spowelljr** [comment]
Hi @poiskail23, thanks for reporting your issue with minikube!

Could you please run `minikube logs --file=logs.txt` and upload the file to this issue, this will help with debugging, thanks!

**Comment by spowelljr** [comment]
Hi @poiskail23, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by poiskail23** [comment]
Hello, sorry for late reply, it appears that issue was not related to minikube version, but likely coming from a missing/wrong settings on my workstation. I wish I did a proper follow-up with more info to share.

**Comment by spowelljr** [comment]
@poiskail23 No worries, if you have an issue again in the future let us know, thanks for using minikube!

**Comment by MatrixManAtYrService** [comment]
I think I've got the same issue.  The interesting part of logs.txt is:
```
I1230 12:49:51.285478   73112 start.go:364] acquiring machines lock for minikube: {Name:mkce1eac97007bc3a5fbbe71b7e0fcacdc493109 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1230 12:49:51.285995   73112 start.go:368] acquired machines lock for "minikube" in 448.383µs
I1230 12:49:51.286060   73112 start.go:96] Skipping create...Using existing machine configuration
I1230 12:49:51.286082   73112 fix.go:55] fixHost starting:
I1230 12:49:51.287311   73112 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I1230 12:49:51.394587   73112 fix.go:103] recreateIfNeeded on minikube: state=Running err=<nil>
W1230 12:49:51.394650   73112 fix.go:129] unexpected machine state, will restart: <nil>
I1230 12:49:51.396842   73112 out.go:177] 🏃  Updating the running docker "minikube" container ...
I1230 12:49:51.397983   73112 machine.go:88] provisioning docker machine ...
I1230 12:49:51.398031   73112 ubuntu.go:169] provisioning hostname "minikube"
I1230 12:49:51.398319   73112 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1230 12:49:51.507434   73112 main.go:134] libmachine: Using SSH client type: native
I1230 12:49:51.508091   73112 main.go:134] libmachine: &{{{<nil> 0 [] [] []} docker [0x7ed4c0] 0x7f0640 <nil>  [] 0s} 127.0.0.1 49157 <nil> <nil>}
I1230 12:49:51.508139   73112 main.go:134] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I1230 12:49:51.595126   73112 main.go:134] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
I1230 12:49:54.683352   73112 main.go:134] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
I1230 12:49:57.772174   73112 main.go:134] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
I1230 12:50:00.860158   73112 main.go:134] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
I1230 12:50:03.946472   73112 main.go:134] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
[logs.txt](https://github.com/kubernetes/minikube/files/10326213/logs.txt)

**Comment by tchaton** [comment]
Yes, I am having the same issue running minikuke into an EC2 instance.
