### ISSUE TITLE
Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority.

### ISSUE THREAD

**Issue by Mandeepsheoran** [kubernetes/minikube#12944]
Hi,
I recently started working on minikube and created the cluster, once I started pulling docker images inside VM, its throwing following error:

 Failed to pull image "selenium/hub": rpc error: code = Unknown desc = Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority

I checked with Docker team and they are saying this is minikube/kubernetes issue. KIndly help me to solve this. I don't have any private repository and want to use default docker public registry.

Simple steps which i used:
minikube start 
kubectl craete -f pod.yml
kubectl describe pods

=======
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  Failed   17h (x26 over 19h)     kubelet  F**ailed to pull image "selenium/hub": rpc error: code = Unknown desc = Error response from daemon: Get "https://registry-1.docker.io/v2/": x509: certificate signed by unknown authority**
  Normal   Pulling  17h (x29 over 19h)     kubelet  Pulling image "selenium/hub"
  Normal   BackOff  4m40s (x701 over 19h)  kubelet  Back-off pulling image "selenium/hub"

**Comment by spowelljr** [comment]
Hi @Mandeepsheoran, thanks for reporting your issue with minikube!

Could you run `minikube logs --file=logs.txt` and upload the the file to this issue, this will help debug the issue, thanks!

**Comment by sharifelgamal** [comment]
We have this exact scenario in our [proxy and VPN documentation](https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/#x509-certificate-signed-by-unknown-authority). Try following those steps and seeing if that helps/

**Comment by spowelljr** [comment]
Hi @Mandeepsheoran, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by Mandeepsheoran** [comment]
> Hi @Mandeepsheoran, we haven't heard back from you, do you still have this issue?
> There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.
> 
> I will close this issue for now but feel free to reopen when you feel ready to provide more information.

I did some workaround to fix that problem at that time. But I will try to replicate that same case once I will get some bandwidth and will let you know.
