### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by felixfarquharson** [kubernetes/minikube#12945]
just a passing comment, but why would i forward the port if i just started it on 8080 what is the purpose and how will this work if i use a cloud provider? 

kubectl port-forward service/hello-minikube 7080:8080

**Comment by afbjorklund** [comment]
The cloud provider will usually offer a real LoadBalancer, for exposing your application:

https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/

You can use `minikube tunnel` cmd, to test it locally.

https://minikube.sigs.k8s.io/docs/handbook/accessing/

**Comment by spowelljr** [comment]
Hi @felixfarquharson, you haven't responded so I'm going to assume that satisfied your question. I'm going to close this issue, but if you have further questions feel free to reopen the issue, thanks!
