### ISSUE TITLE
Minikube unable to connect to the VM: dial tcp 192.168.99.107:22: i/o timeout

### ISSUE THREAD

**Issue by Sprakhar97** [kubernetes/minikube#12949]
Problem statement and error: 
I'm unable to start minikube on virtualBox
**Steps to reproduce the issue:** 

1. installed virtualBox
2. Run minikube start --vm=true --driver=virtualbox
3. Minikube version: 1.16.0
4. darwin 11.6

**LOG FILE**

[logs.txt](https://github.com/kubernetes/minikube/files/7537314/logs.txt)

**Full output of failed command if not `minikube start`:**

<details>
😄  minikube v1.16.0 on Darwin 11.6
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=3, Memory=8192MB, Disk=20000MB) ...
❌  minikube is unable to connect to the VM: dial tcp 192.168.99.107:22: i/o timeout

	This is likely due to one of two reasons:

	- VPN or firewall interference
	- virtualbox network configuration issue

	Suggested workarounds:

	- Disable your local VPN or firewall software
	- Configure your local VPN or firewall to allow access to 192.168.99.107
	- Restart or reinstall virtualbox
	- Use an alternative --vm-driver
	- Use --force to override this connectivity check

❌  Exiting due to GUEST_PROVISION: Failed to validate network: dial tcp 192.168.99.107:22: i/o timeout

</details>

**Comment by spowelljr** [comment]
Hi @Sprakhar97, thanks for reporting your issue with minikube!

minikube v1.16.0 is an old version of minikube, as a first step I'd strongly recommend you update to the latest version (1.24.0).

Also, what version of VirtualBox are you using?

**Comment by spowelljr** [comment]
Hi @Sprakhar97, we had another user run into this issue this morning and they were able to solve this by running (https://github.com/kubernetes/minikube/issues/12943):
```
$ minikube delete --all --purge
$ rm -rf ~/.kube
```
Then try starting minikube again, let me know if that works.

**Comment by medyagh** [comment]
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by 3ch01c** [comment]
I get this error if I try to use the Virtualbox driver on a VPN, and [it looks like a lot of other people have similar problems](https://github.com/kubernetes/minikube/issues?q=is%3Aopen+is%3Aissue+virtualbox+vpn). The easiest solution seems to be to use a different driver. The VMware driver works out of the box for me, and the HyperKit driver works if I update Minikube's DNS to use my host's DNS:

```
minikube start --driver hyperkit
minikube ssh sudo resolvectl dns eth0 192.168.0.53
minikube ssh sudo resolvectl domain eth0 example.com
```

If you're using a proxy, have you set your proxy vars? Don't forget to add Minikube's IP addresses to `NO_PROXY`. The [Minikube documentation on proxies & VPNs](https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/) might also help.

**Comment by charly71** [comment]
I have still the same problem on a MacOS machine Monterey. This is the log backtrace:

```
I0913 10:54:42.132360    1711 out.go:177] 🌐  Found network options:
🌐  Found network options:
I0913 10:54:42.176318    1711 out.go:177]     ▪ HTTP_PROXY=http://proxy.csi.it:3128
    ▪ HTTP_PROXY=http://proxy.csi.it:3128
I0913 10:54:42.219448    1711 out.go:177]     ▪ HTTPS_PROXY=http://proxy.csi.it:3128
    ▪ HTTPS_PROXY=http://proxy.csi.it:3128
I0913 10:54:42.241505    1711 out.go:177]     ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.49.0/24,192.168.39.0/24,192.168.59.103
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.49.0/24,192.168.39.0/24,192.168.59.103
W0913 10:54:45.263386    1711 start.go:689] dial failed (will retry): dial tcp 192.168.59.103:22: i/o timeout
I0913 10:54:45.263429    1711 retry.go:31] will retry after 1.104660288s: dial tcp 192.168.59.103:22: i/o timeout
W0913 10:54:49.369239    1711 start.go:689] dial failed (will retry): dial tcp 192.168.59.103:22: i/o timeout
I0913 10:54:49.369268    1711 retry.go:31] will retry after 2.160763633s: dial tcp 192.168.59.103:22: i/o timeout
W0913 10:54:54.530671    1711 start.go:689] dial failed (will retry): dial tcp 192.168.59.103:22: i/o timeout
W0913 10:54:54.530830    1711 out.go:239] ❌  minikube is unable to connect to the VM: dial tcp 192.168.59.103:22: i/o timeout
```
