### ISSUE TITLE
Go through all documentation and ensure commands/tutorials exist for both Unix & Windows

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#12968]
Our documentation is generally written for Unix, this can be annoying if users have to find the Windows versions of the commands online themselves. To help out our Windows users we should ensure all documentations contains both Unix & Windows commands, this will greatly help out new Windows users who are trying to get started with Windows.

**Comment by mpuckett159** [comment]
Hey I was going through the docs and taking a stab at this and noticed that there's some inconsistency on the kind of formatting used to provide tabbed views of commands for Windows/Linux/macOS, wanted to get takes on which would be preferred formatting:

Example 1:
https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/
The above page uses quiz card styling like so
```
{{% card %}}

{{% quiz_row base="" name="Operating system" %}}
{{% quiz_button option="Linux" %}} {{% quiz_button option="macOS" %}} {{% quiz_button option="Windows" %}}
{{% /quiz_row %}}

{{% card %}}

{{% quiz_instruction_plain id="/Linux" %}}
...
{{% /quiz_instruction_plain %}}

{{% quiz_instruction_plain id="/macOS" %}}
...
{{% /quiz_instruction_plain %}}

{{% quiz_instruction_plain id="/Windows" %}}
...
{{% /quiz_instruction_plain %}}

{{% /card %}}

{{% /card %}}
```

Example 2:
https://minikube.sigs.k8s.io/docs/handbook/pushing/
This page uses tabs like so
```
{{% tabs %}}
{{% linuxtab %}}
...
{{% /linuxtab %}}
{{% mactab %}}
...
{{% /mactab%}}
{{% windowstab %}}
...
{{% /windowstab %}}
{{% /tabs %}}
```

I personally kind of like the second option more but wanted to see if there was any specific desire for conformity there and if so which one to go with.

**Comment by spowelljr** [comment]
Hi @mpuckett159, the reason the first one uses a different style is because there are many different options other than OS, so we went with a style to keep all the buttons consistent (shown below).
![Screen Shot 2021-11-17 at 3 30 05 PM](https://user-images.githubusercontent.com/44844360/142299013-aa058423-2f54-410a-abaa-dc618bf3523d.png)

Where as the second option is perfectly fine for everything else were there's only different OS systems to choose from, so I'd say using the second style for everything than the Getting Started page which uses the other style.

**Comment by mpuckett159** [comment]
Sorry I was referring to this one on the `handbook>addons>ingress-dns.md` page. Either way, I'll use the second option.
<img width="930" alt="Screen Shot 2021-11-17 at 3 51 06 PM" src="https://user-images.githubusercontent.com/13648427/142300643-896268a1-f8cf-4a72-992d-14705daac891.png">

**Comment by spowelljr** [comment]
Ah, that looks a little weird to me, feel free to change that one the second option when you make your changes.
