### ISSUE TITLE
ingress DNS slow to recognize new subdomain

### ISSUE THREAD

**Issue by iamnoah** [kubernetes/minikube#12962]
Not sure how to categorize or describe this.  Basically we create new Ingress objects under a wildcard domain. e.g., `*.foo.minikube` we have the resolver configured:

```
> cat etc/resolver/minikube
domain foo.minikube
nameserver 192.168.64.52
search_order 1
timeout 5
```

In 1.22, a new Ingress hostname (e.g., `123.foo.minikube`) was pretty much instantly resolved, routed to ingress-nginx, and to the backend service.  Now with 1.24, DNS queries for `123.foo.minikube` don't resolve for quite some time after creating the Ingress, sometimes a minute or more, which really slows us down. 

This is what I see in the kube-ingress-dns-minikube logs:

```
{"header":{"id":36667,"qr":0,"opcode":0,"aa":0,"tc":0,"rd":1,"ra":0,"z":0,"rcode":0,"qdcount":1,"nscount":0,"arcount":0,"ancount":0},"questions":[{"name":"123.foo.minikube","type":28,"class":1}],"answers":[],"authorities":[],"additionals":[]}
Confirmed names:[]
Packet {
  header: {
    id: 36667,
    qr: 1,
    opcode: 0,
    aa: 0,
    tc: 0,
    rd: 1,
    ra: 1,
    z: 0,
    rcode: 0,
    qdcount: 1,
    nscount: 0,
    arcount: 0,
    ancount: 0
  },
  questions: [
    {
      name: '123.foo.minikube',
      type: 28,
      class: 1
    }
  ],
  answers: [],
  authorities: [],
  additionals: []
}
```

Is there a way we can make anything under `*.foo.minikube` resolve to the host so ingress-nginx can handle it?

**Comment by sharifelgamal** [comment]
A lot of things about ingress has changes over the last two version of minikube, mostly due to changes on Kubernetes' side, I'm willing to bet that's the reason.

cc @prezha who is our ingress guru.

**Comment by klaases** [comment]
Hi @iamnoah – is this issue still occurring with the latest version of minikube?

If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
