### ISSUE TITLE
Establish release guidelines, document it and create scripts to automate things

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#130]
We should follow the conventions as close as possible to other Kubernetes projects.

Proposed things:
 - Follow semver when possible
 - All releases should be named `vX.Y.Z` with an optional `vX.Y.Z-{alpha,beta}.W` extension for pre-releases.
 - The commit the tag `vX.Y.Z` is associated with should only bump the version in the `Makefile`
 - The first commit after a release is tagged should bump the version to `vX.(Y+1).Z-dev`
 - Release binaries should be built from a released tag.
 - Initially, we should only increment the `Y` value, i. e. `v0.1.0`, `v0.2.0`, `v0.3.0`, until we consider minikube be "production ready" and "feature complete", which will set `X` to 1.
 - When there are only bugfixes, and a release really is needed, only the `Z` should be incremented.

This is just a suggestion... Most things are the same as core k8s.

Mostly I wrote this to avoid confusion for end users... 
After all, the project's goal is to make it as possible to use, and no one want to dig into the source just to know which versioning scheme we used at a given time, so we should be consistent.

Feel free to give feedback!

@dlorenc @aaron-prindle @vishh @bgrant0607 @david-mcmahon

**Comment by david-mcmahon** [comment]
There is work happening in https://github.com/kubernetes/release to split the release tooling and processes (not build) from core kubernetes.  This is a place where we should generalize and provide tooling for any and all subprojects of kubernetes such as this one.

**Comment by dlorenc** [comment]
I'll document and write scripts for this release as I go, but I'll have to actually cut it first in order to do that. Moving this to 0.3.0, where we'll actually have the documents and scripts. committed.

**Comment by david-mcmahon** [comment]
Thank you @dlorenc.  Getting a baseline of basic steps / instructions for cutting a minikube release is the first step.  We can improve and generalize as we move forward.
