### ISSUE TITLE
Can't enable ingress addon - Kubernetes Version 1.19.15

### ISSUE THREAD

**Issue by joe-legg** [kubernetes/minikube#13004]
**Steps to reproduce the issue:** 

1. `minikube start --kubernetes-version=v1.19.15 --vm-driver=docker`
2. `minikube addons enable ingress`

**Full output of `minikube addons enable ingress`:**
<details>

```
    ▪ Using image k8s.gcr.io/ingress-nginx/controller:v1.0.4
    ▪ Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
    ▪ Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
🔎  Verifying ingress addon...

❌  Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.15/kubectl apply -f /etc/kubernetes/addons/ingress-deploy.yaml: Process exited with status 1
stdout:
namespace/ingress-nginx unchanged
serviceaccount/ingress-nginx unchanged
configmap/ingress-nginx-controller unchanged
configmap/tcp-services unchanged
configmap/udp-services unchanged
clusterrole.rbac.authorization.k8s.io/ingress-nginx unchanged
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged
role.rbac.authorization.k8s.io/ingress-nginx unchanged
rolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged
service/ingress-nginx-controller-admission unchanged

stderr:
error: error validating "/etc/kubernetes/addons/ingress-deploy.yaml": error validating data: [ValidationError(Service.spec): unknown field "ipFamilies" in io.k8s.api.core.v1.ServiceSpec, ValidationError(Service.spec): unknown field "ipFamilyPolicy" in 
io.k8s.api.core.v1.ServiceSpec]; if you choose to ignore these errors, turn validation off with --validate=false
 waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_addons_2c0e0cafd16ea0f95ac51773aeef036b316005b6_0.log                  │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```
</details>

**Output of `minikube logs --file=logs.txt`**
[logs.txt](https://github.com/kubernetes/minikube/files/7583550/logs.txt)

`/tmp/minikube_addons_2c0e0cafd16ea0f95ac51773aeef036b316005b6_0.log`
[minikube_addons_2c0e0cafd16ea0f95ac51773aeef036b316005b6_0.log](https://github.com/kubernetes/minikube/files/7583558/minikube_addons_2c0e0cafd16ea0f95ac51773aeef036b316005b6_0.log)

**Comment by joe-legg** [comment]
It works when I downgrade to minikube v1.23.2.

**Comment by sfc-gh-adlee** [comment]
same here. Im running 1.19.2 and doesnt work

**Comment by trust-freedom** [comment]
> It works when I downgrade to minikube v1.23.2.

me too. 
At first I used minikube v1.24.0,  The same problem occurred.
downgrade to minikube v1.23.2, it works

**Comment by frankli-dev** [comment]
> > It works when I downgrade to minikube v1.23.2.
> 
> me too. At first I used minikube v1.24.0, The same problem occurred. downgrade to minikube v1.23.2, it works

How can I downgrade minikube?

**Comment by trust-freedom** [comment]
> > > It works when I downgrade to minikube v1.23.2.
> > 
> > 
> > me too. At first I used minikube v1.24.0, The same problem occurred. downgrade to minikube v1.23.2, it works
> 
> How can I downgrade minikube?

I think you can try.

**Comment by frankli-dev** [comment]
> > > > It works when I downgrade to minikube v1.23.2.
> > > 
> > > 
> > > me too. At first I used minikube v1.24.0, The same problem occurred. downgrade to minikube v1.23.2, it works
> > 
> > 
> > How can I downgrade minikube?
> 
> I think you can try.

Could you give me the command to downgrade minikube on MacOS? I installed minikube using brew.

**Comment by trust-freedom** [comment]
> > > > > It works when I downgrade to minikube v1.23.2.
> > > > 
> > > > 
> > > > me too. At first I used minikube v1.24.0, The same problem occurred. downgrade to minikube v1.23.2, it works
> > > 
> > > 
> > > How can I downgrade minikube?
> > 
> > 
> > I think you can try.
> 
> Could you give me the command to downgrade minikube on MacOS? I installed minikube using brew.

I think you can download minikube from https://github.com/kubernetes/minikube/releases ， and Reinstall according to official documentation https://minikube.sigs.k8s.io/docs/start/
