### ISSUE TITLE
virtualbox: Unable to start the minikube 

### ISSUE THREAD

**Issue by prathapdasari** [kubernetes/minikube#13019]
Hi Team,

I am unable to start the minikube in virtual box on mac laptop due to the following error.
Please find the attached logs.txt file here 

k8@k8-VirtualBox:~$ minikube start --driver=virtualbox
😄  minikube v1.24.0 on Ubuntu 20.04
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running virtualbox "minikube" VM ...
🤦  StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800274369cc
🏃  Updating the running virtualbox "minikube" VM ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800274369cc

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800274369cc

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by prathapdasari** [comment]
[logs.txt](https://github.com/kubernetes/minikube/files/7592981/logs.txt)

**Comment by medyagh** [comment]
hi @prathapdasari I am curious have u tried a newer version of Vbox or a different driver?

**Comment by prathapdasari** [comment]
Hi @medyagh  I have uploaded screenshot of my VirtualBox
<img width="1675" alt="Screenshot 2021-11-25 at 09 18 59" src="https://user-images.githubusercontent.com/67961663/143404771-ce0c9d7a-d4aa-4098-882a-baf89692714c.png">

<img width="669" alt="Screenshot 2021-11-25 at 09 20 11" src="https://user-images.githubusercontent.com/67961663/143404928-313ef546-4a3a-40b7-916d-8ce85da2d0cf.png">

**Comment by prathapdasari** [comment]
May i know any update on this ?

**Comment by klaases** [comment]
Hi @[prathapdasari](https://github.com/prathapdasari), are you able to try the latest versions of minikube and VirtualBox?

**Comment by shaquiba739** [comment]
I am unable to start the Minikube inside centOS VM
I am getting the below error while trying to start minikube using the below commands.
#minikube start --driver=virtualbox
![image](https://user-images.githubusercontent.com/61896157/161379566-21876ce2-81a5-4c43-b817-c6b75a7e63fb.png)

**Comment by sharifelgamal** [comment]
@shaquiba739 your issue is that you're trying to use virtualbox in an environment where it's not installed. If you're already inside a VM, you might want to try the `none` driver.

**Comment by phalsam** [comment]
> I am unable to start the Minikube inside centOS VM I am getting the below error while trying to start minikube using the below commands. #minikube start --driver=virtualbox ![image](https://user-images.githubusercontent.com/61896157/161379566-21876ce2-81a5-4c43-b817-c6b75a7e63fb.png)

![image](https://user-images.githubusercontent.com/104772274/166239262-0502d9d9-768d-4aac-af88-c5408ccce7c2.png)
i am getting the error as well

**Comment by sharifelgamal** [comment]
This error just means you do not have VBoxManage in your PATH, which means it was not installed correctly.

**Comment by klaases** [comment]
Hi @prathapdasari – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
