### ISSUE TITLE
minikube no t starting, saying "X Exiting due to PROVIDER_VIRTUALBOX_NOT_RUNNING: exit status 1"

### ISSUE THREAD

**Issue by ravimalvia** [kubernetes/minikube#13028]
*
* ==> Audit <==
* |---------|-----------------------|----------|----------------------|---------|-------------------------------|-------------------------------|
| Command |         Args          | Profile  |         User         | Version |          Start Time           |           End Time            |
|---------|-----------------------|----------|----------------------|---------|-------------------------------|-------------------------------|
| start   |                       | minikube | Mr_Marvel\Mr. Marvel | v1.24.0 | Fri, 19 Nov 2021 16:06:59 IST | Fri, 19 Nov 2021 16:23:45 IST |
| config  | set driver virtualbox | minikube | Mr_Marvel\Mr. Marvel | v1.24.0 | Fri, 19 Nov 2021 16:33:51 IST | Fri, 19 Nov 2021 16:33:51 IST |
| delete  |                       | minikube | Mr_Marvel\Mr. Marvel | v1.24.0 | Fri, 26 Nov 2021 14:09:12 IST | Fri, 26 Nov 2021 14:09:19 IST |
| delete  |                       | minikube | Mr_Marvel\Mr. Marvel | v1.24.0 | Fri, 26 Nov 2021 14:41:18 IST | Fri, 26 Nov 2021 14:41:26 IST |
| delete  |                       | minikube | Mr_Marvel\Mr. Marvel | v1.24.0 | Fri, 26 Nov 2021 14:46:01 IST | Fri, 26 Nov 2021 14:46:02 IST |
|---------|-----------------------|----------|----------------------|---------|-------------------------------|-------------------------------|

*
* ==> Last Start <==
* Log file created at: 2021/11/26 15:04:16
Running on machine: Mr_Marvel
Binary: Built with gc go1.17.2 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1126 15:04:16.235725    1656 out.go:297] Setting OutFile to fd 84 ...
I1126 15:04:16.240607    1656 out.go:344] TERM=,COLORTERM=, which probably does not support color
I1126 15:04:16.240607    1656 out.go:310] Setting ErrFile to fd 88...
I1126 15:04:16.240607    1656 out.go:344] TERM=,COLORTERM=, which probably does not support color
I1126 15:04:16.281363    1656 out.go:304] Setting JSON to false
I1126 15:04:16.291828    1656 start.go:112] hostinfo: {"hostname":"Mr_Marvel","uptime":356900,"bootTime":1637562356,"procs":224,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.19043 Build 19043","kernelVersion":"10.0.19043 Build 19043","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"90551d03-a07e-4fcc-b50f-84f095e3e6b4"}
W1126 15:04:16.292508    1656 start.go:120] gopshost.Virtualization returned error: not implemented yet
I1126 15:04:16.335090    1656 out.go:176] * minikube v1.24.0 on Microsoft Windows 10 Pro 10.0.19043 Build 19043
I1126 15:04:16.339638    1656 notify.go:174] Checking for updates...
I1126 15:04:16.344803    1656 driver.go:343] Setting default libvirt URI to qemu:///system
W1126 15:04:21.181492    1656 virtualbox.go:93] "C:\\Program Files\\Oracle\\VirtualBox\\VBoxManage.exe list hostinfo" timed out.
I1126 15:04:21.241184    1656 out.go:176] * Using the virtualbox driver based on user configuration
I1126 15:04:21.242341    1656 start.go:280] selected driver: virtualbox
I1126 15:04:21.242341    1656 start.go:762] validating driver "virtualbox" against <nil>
I1126 15:04:21.242584    1656 start.go:773] status for virtualbox: {Installed:true Healthy:false Running:false NeedsImprovement:false Error:exit status 1 Reason: Fix:Restart VirtualBox Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/}
I1126 15:04:21.264664    1656 out.go:176]
W1126 15:04:21.265302    1656 out.go:241] X Exiting due to PROVIDER_VIRTUALBOX_NOT_RUNNING: exit status 1
W1126 15:04:21.274537    1656 out.go:241] * Suggestion: Restart VirtualBox
W1126 15:04:21.277425    1656 out.go:241] * Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

*
* Profile "minikube" not found. Run "minikube profile list" to view all profiles.
  To start a cluster, run: "minikube start"

**Comment by spowelljr** [comment]
Hi @ravimalvia, thanks for reporting your issue with minikube!

It looks like your VirtualBox is not healthy (`Healthy:false`), have you try restarting VirtualBox?

**Comment by ravimalvia** [comment]
@spowelljr yes i tried starting it again , reinstalling virtualbox'  , even deleting complete package of minikube and again installing

**Comment by AmiteshDTU** [comment]
I am getting this same error. Has anyone solved this problem ?

**Comment by sharifelgamal** [comment]
The specific issue OP is having is that `C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostinfo` is timing out. A good way to see if your installation of vbox is healthy is to try running that yourself in powershell and seeing what happens.

**Comment by ravimalvia** [comment]
> The specific issue OP is having is that `C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostinfo` is timing out. A good way to see if your installation of vbox is healthy is to try running that yourself in powershell and seeing what happens.

![IMG_20211224_104501.jpg](https://user-images.githubusercontent.com/53039826/147319351-13c78684-2d37-4d34-8848-db9d09fb261d.jpg)

It looks virtualbox is healthy

**Comment by ravimalvia** [comment]
> I am getting this same error. Has anyone solved this problem ?

Have you find any solution

**Comment by ravimalvia** [comment]
The problem with minikube happened because of update of windows 10, i have find the solution that uninstall  some updates then check if minikube is working

**Comment by klaases** [comment]
Hi @ravimalvia – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
