### ISSUE TITLE
Update istio addon YAML for newer Kubernetes versions

### ISSUE THREAD

**Issue by wallrick** [kubernetes/minikube#13025]
minikube start -p minikube -n 1 --apiserver-names="minikube.local" --memory 15360 --cpus 6
Also tried a simple
minikube start

**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable istio-provisioner
3. minikube addons enable istio

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>
Getting error when attempting to enable istio after a freshly deployed kubernetes.

Running on Ubuntu with Virtual Box driver.
`Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal`

Running the latest minikube, v1.24.0 but it also fails on 1.23

minikube start
* minikube v1.24.0 on Ubuntu 20.04
* Automatically selected the virtualbox driver
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.22.3 on Docker 20.10.8 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

minikube addons enable istio-provisioner

Seeing this error
`stderr:
error: error validating "/etc/kubernetes/addons/istio-operator.yaml": error validating data: ValidationError(CustomResourceDefinition.spec): unknown field "subresources" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionSpec; if you choose to ignore these errors, turn validation off with --validate=false`

Attempt One
[istio_failure1.log](https://github.com/kubernetes/minikube/files/7605654/istio_failure1.log)

Attempt Two
[istio_failure.log](https://github.com/kubernetes/minikube/files/7605625/istio_failure.log)

</details>

**Comment by wallrick** [comment]
Problem looks to be a compatibility mismatch between the kubernetes version and the istio version that is being used for the addon.

**Comment by wallrick** [comment]
Installing istio by hand using the instructions here works. So the issue isn't the kubernetes cluster that minikube deploys but the addon version/configuration of istio.

https://istio.io/latest/docs/setup/getting-started

**Comment by sharifelgamal** [comment]
We should update our istio addon yaml to be compatible with newer versions of Kubernetes. Thanks for pointing that out. Help wanted!
