### ISSUE TITLE
cannot be accessed nginx port  with "connect refused"

### ISSUE THREAD

**Issue by lmx1989219** [kubernetes/minikube#13026]
**Steps to reproduce the issue:** 

1.curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
2. sudo install minikube-linux-amd64 /usr/local/bin/minikube
3.minikube start

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>
[root@apm opt]# kubectl create deployment ngx2 --image=docker.io/nginx
[root@apm opt]# kubectl expose deployment ngx2 --type=NodePort --port=18082

[root@apm opt]# kubectl get services ngx2
NAME   TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)           AGE
ngx2   NodePort   10.106.148.175   <none>        18082:30230/TCP   20h

[root@apm opt]# minikube service ngx2 --url
http://192.168.58.2:30230

[root@apm opt]# curl http://192.168.58.2:30230
curl: (7) Failed connect to 192.168.58.2:30230; Connection refused

and  i used netstat command also  not fund the port 30230 be listening
</details>

**Comment by lmx1989219** [comment]
follow is minikube running detail
```
[root@apm opt]# minikube kubectl -- get po -A
NAMESPACE              NAME                                         READY   STATUS    RESTARTS      AGE
default                ngx1-5d987546fc-lbscw                        1/1     Running   0             20h
default                ngx2-5df77f8f46-2lzxl                        1/1     Running   0             20h
kube-node-lease        nginx-deployment-66b6c48dd5-gdkq9            1/1     Running   0             21h
kube-node-lease        nginx-deployment-66b6c48dd5-kdn2d            1/1     Running   0             21h
kube-system            coredns-78fcd69978-dgqgf                     1/1     Running   0             22h
kube-system            etcd-minikube                                1/1     Running   0             22h
kube-system            kube-apiserver-minikube                      1/1     Running   0             22h
kube-system            kube-controller-manager-minikube             1/1     Running   0             22h
kube-system            kube-proxy-x28cx                             1/1     Running   0             22h
kube-system            kube-scheduler-minikube                      1/1     Running   0             22h
kube-system            storage-provisioner                          1/1     Running   1 (22h ago)   22h
kubernetes-dashboard   dashboard-metrics-scraper-5594458c94-hngmb   1/1     Running   0             22h
kubernetes-dashboard   kubernetes-dashboard-654cf69797-9p5lh        1/1     Running   0             22h
```

**Comment by issamahmoud355** [comment]
Hi
