### ISSUE TITLE
windows 10 Unable to use docker command but minikube is running

### ISSUE THREAD

**Issue by beterhans** [kubernetes/minikube#13021]
WIndows 10 power shell
Hyper-V disabled, windows docker uninstalled
Virtualbox can run

I'm using direct internet NOT behind a firewall or proxy
but it always give me this This VM is having trouble accessing https://k8s.gcr.io
in the end it can run but I'm unable to access to docker command.

I'm not sure I need to install docker or not
I tried to install it but it can't run, and also destroy my virtualbox and made my virutalbox unable to start.
so I removed docker and disabled hyper-v.
from another tutorial shows no need to install docker should able to access docker from minikube.

```
PS C:\Temp> #Virtualbox version = 1.6.28
PS C:\Temp> minikube start --driver=virtualbox
* minikube v1.24.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
  - MINIKUBE_ACTIVE_DOCKERD=minikube
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=3000MB, Disk=20000MB) ...
! This VM is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.22.3 on Docker 20.10.8 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: storage-provisioner, default-storageclass
* Verifying Kubernetes components...
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
PS C:\Temp>
PS C:\Temp> minikube docker-env
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://192.168.59.101:2376"
$Env:DOCKER_CERT_PATH = "C:\Users\yaohuap\.minikube\certs"
$Env:MINIKUBE_ACTIVE_DOCKERD = "minikube"
# To point your shell to minikube's docker-daemon, run:
# & minikube -p minikube docker-env | Invoke-Expression
PS C:\Temp> & minikube -p minikube docker-env | Invoke-Expression
PS C:\Temp> docker images
docker : The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ docker images
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\Temp> minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
docker-env: in-use

```

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>
[logs.txt](https://github.com/kubernetes/minikube/files/7601443/logs.txt)
</details

>

**Comment by spowelljr** [comment]
Hi @beterhans, thanks for reporting your issue with minikube!

To use `minikube docker-env` you need to have Docker Desktop installed, which is why you're getting `The term 'docker' is not recognized`.

However, minikube has commands built-in to replicate Docker without needing it to be installed.

```
$ minikube image <command>

Available Commands:
  build       Build a container image in minikube
  load        Load a image into minikube
  ls          List images
  pull        Pull images
  push        Push images
  rm          Remove one or more images
  save        Save a image from minikube
  tag         Tag images
```

To have even more options you can `minikube ssh` to be inside the minikube cluster and there's a Docker instance running in there you can run docker commands against.

**Comment by spowelljr** [comment]
Hi @beterhans, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
