### ISSUE TITLE
Error in starting a cluster Failed kubeconfig update: could not read config: Error decoding config from data

### ISSUE THREAD

**Issue by vikramsh2002** [kubernetes/minikube#13031]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube logs --file=logs.txt
[logs.txt](https://github.com/kubernetes/minikube/files/7611153/logs.txt)

3.

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
[logs.txt](https://github.com/kubernetes/minikube/files/7611150/logs.txt)
[logs.txt](https://github.com/kubernetes/minikube/files/7611151/logs.txt)

<details>

</details>

**Comment by spowelljr** [comment]
Hi @vikramsh2002, thanks for reporting your issue with minikube!

It seems your kubeconfig somehow get corrupted. Delete the file `C:\Users\HP\.kube\config` and then try starting minikube again and see if that resolves your issue.
