### ISSUE TITLE
Investigate only requiring admin privileges once on Windows

### ISSUE THREAD

**Issue by baseely** [kubernetes/minikube#13035]
**Steps to reproduce the issue:** 

1.Start a Windows command prompt (Do not "Run as Administrator").
2. Type `minikube start --vm-driver=hyperv`

**Output of the command:**
`Exiting due to PROVIDER_HYPERV_NOT_RUNNING: Hyper-V requires Administrator privileges`

**Question:**
Why should a Minikube cluster be started with an Administrator privileges ? Is it possible to run the above command using a normal user account ? I tried to add my current user to the Hyper-V administrator users group but not sure if it was added correctly. (Maybe because this is a corporate laptop)

**Comment by medyagh** [comment]
@baseely hyperV does require an admin power user to create VMs, however if there is a way to create hyperV Vms by adding normal user to power-user group that would be a great addition to our doucmentation

**Comment by medyagh** [comment]
cc: @spowelljr

**Comment by baseely** [comment]
@medyagh Maybe I’m not familiar enough with the mechanics of how `minikube start` works behind the scenes, but as far as I can understand it should create the hyperV VM once (using a power windows user) and never ask again for an administrator privileges for the consequent starts.

**Comment by medyagh** [comment]
I believe windows requires admin powers for any operation on VMs (stopping and starting it again) unless you configure your user to do so I am not fimmiliar with windows but have u tried if this instructions work ? https://docs.microsoft.com/en-gb/archive/blogs/virtual_pc_guy/allowing-non-administrators-to-control-hyper-v

**Comment by baseely** [comment]
@medyagh It appears that the `InitialStore.xml` is missing on Windows 10. I tried to add my current Windows user account and a couple of other accounts (`DefaultAccount`, `defaultuser100001`) but I get the same error message.
`X Exiting due to PROVIDER_HYPERV_NOT_RUNNING: Hyper-V requires Administrator privileges`
`* Suggestion: Right-click the PowerShell icon and select Run as Administrator to open PowerShell in elevated mode.`

**Comment by 3ster** [comment]
Adding my user account to the Hyper-V Administrators group as outlined in the [updated version](https://web.archive.org/web/20190419215015/https://blogs.msdn.microsoft.com/virtual_pc_guy/2014/06/11/allowing-non-administrators-to-control-hyper-vupdated/) of the guide mentioned in the comment above seems to work fine, including creating a new Hyper-V VM via `minikube start --driver=hyperv` as a normal user. Running `minikube dashboard` as a normal user now also works while previously requiring administrator privileges.

**Comment by thepaulmacca** [comment]
This doesn't work for me, still have to do everything as admin even though I'm added to the group

**Comment by thepaulmacca** [comment]
> Adding my user account to the Hyper-V Administrators group as outlined in the [updated version](https://web.archive.org/web/20190419215015/https://blogs.msdn.microsoft.com/virtual_pc_guy/2014/06/11/allowing-non-administrators-to-control-hyper-vupdated/) of the guide mentioned in the comment above seems to work fine, including creating a new Hyper-V VM via `minikube start --driver=hyperv` as a normal user. Running `minikube dashboard` as a normal user now also works while previously requiring administrator privileges.

This doesn't work for me, still have to run commands as admin even though I'm added to the group

If I run `minikube status` for example, I get an error unless I run it as admin

**Comment by baseely** [comment]
For other platforms, Linux for instance, all you have to do is to modify the user account that will run the binary and add it to the secondary group that control the minikube.

**Comment by 3ster** [comment]
> > Adding my user account to the Hyper-V Administrators group as outlined in the [updated version](https://web.archive.org/web/20190419215015/https://blogs.msdn.microsoft.com/virtual_pc_guy/2014/06/11/allowing-non-administrators-to-control-hyper-vupdated/) of the guide mentioned in the comment above seems to work fine, including creating a new Hyper-V VM via `minikube start --driver=hyperv` as a normal user. Running `minikube dashboard` as a normal user now also works while previously requiring administrator privileges.
> 
> This doesn't work for me, still have to run commands as admin even though I'm added to the group
> 
> If I run `minikube status` for example, I get an error unless I run it as admin

Note that you'll have to re-create your cluster if you've previously created it with admin permissions.

**Comment by thepaulmacca** [comment]
> Note that you'll have to re-create your cluster if you've previously created it with admin permissions.

That works fine until I run `minikube service hello-minikube` for example. I get this:

```bash
➜ minikube service hello-minikube
🤷  This control plane is not running! (state=Stopped)
❗  This is unusual - you may want to investigate using "minikube logs"
👉  To start a cluster, run: "minikube start"
```
I don't get an error when I run it in admin mode though

When I run `minikube service hello-minikube` it doesn't even open in the browser for me, so seems quite a few issues with it on Windows at the moment

**Comment by janheindejong** [comment]
> Adding my user account to the Hyper-V Administrators group as outlined in the [updated version](https://web.archive.org/web/20190419215015/https://blogs.msdn.microsoft.com/virtual_pc_guy/2014/06/11/allowing-non-administrators-to-control-hyper-vupdated/) of the guide mentioned in the comment above seems to work fine, including creating a new Hyper-V VM via `minikube start --driver=hyperv` as a normal user. Running `minikube dashboard` as a normal user now also works while previously requiring administrator privileges.

This worked for me. Note that it requires a restart.

**Comment by baseely** [comment]
We can close this issue now. You can now bypass it by following @3ster steps.
