### ISSUE TITLE
Docker | Change Data Directory 

### ISSUE THREAD

**Issue by backtrackshubham** [kubernetes/minikube#13032]
**Steps to reproduce the issue:** 

1. Create a minikube cluster using `minikube start`
2. Mount a directory using `mount <local-dir>:<path in minikube vm>`
3. Try to change/add the `data-root` in `deamon.json` with `path in minikube vm` so that pull images on minikube can be persisted and used later by simply mounting the volume back then updating the `daemon.json` followed by restarting the `docker.service`

Note: the above works fine when we change the value for `data-root` to a directory which is existing in minikube vm but it fails if we use a host mounted value for it, then the docker service won't start

the mount command used is
```
#Default mode is 495
minikube mount --mode 511 /Users/backtrackshubham/docker-dir:/docker-dir
```

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by afbjorklund** [comment]
You can't really use a network filesystem as the container storage, so probably look into minikube cache instead.

**Comment by backtrackshubham** [comment]
So does that mean that if we mount an external volume probably from host to minikube it gets mounted as a nfs, ohh I wonder that's why mount command always showed some ip and and port information

**Comment by TekTimmy** [comment]
> You can't really use a network filesystem as the container storage, so probably look into minikube cache instead.

Sorry for the offtopic question but i don't understand the usecase of docker cache because of the very low performance. We have some pretty large docker images and everytime only a single layer was changed the whole image has to be transferred into the cache which takes a very long time.

**Comment by afbjorklund** [comment]
If you have large images, that often have single layer changes, then it is better to use a registry.

**Comment by spowelljr** [comment]
> So does that mean that if we mount an external volume probably from host to minikube it gets mounted as a nfs, ohh I wonder that's why mount command always showed some ip and and port information

That's correct @backtrackshubham

**Comment by backtrackshubham** [comment]
Hi Team one quick question, so I am trying to install nfs server in minikube so that I could install nfs storage class and use it, but the pods for nfs server are failing so can I actually do it ?
