### ISSUE TITLE
Minikube doesn't start

### ISSUE THREAD

**Issue by ribasnath** [kubernetes/minikube#13030]
**I've installed Minikube to use along with Docker on Windows Server 2019. However, when I try to start with `minikube start`, it shows the follow errors:**

* minikube v1.24.0 on Microsoft Windows Server 2019 Datacenter 10.0.17763 Build 17763
* Using the hyperv driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...WWE1126 15:39:22.081362    4968 main.go:126] libmachine: 
The Virtual Machine Management Service could not start the 'minikube' virtual machine because one of the
Hyper-V component is not running.
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

X Exiting due to GUEST_PROVISION: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.

<br>
<br>

**Trying to start with `minikube start --driver=hyper-v`:**

X Exiting due to DRV_UNSUPPORTED_OS: The driver 'hyper-v' is not supported on windows/amd64

**Comment by medyagh** [comment]
@ribasnath do u mind sharing the log file?

```
minikube logs --file=logs.txt
```

**Comment by vij-code** [comment]
minikube start
