### ISSUE TITLE
ingress-dns test fails on nslookup (MacOs)

### ISSUE THREAD

**Issue by ethnhll** [kubernetes/minikube#13067]
Following https://minikube.sigs.k8s.io/docs/start/#what-youll-need

and 

https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/

I am not able to ping or reach the example applications for testing ingress-dns addon. Perhaps I am missing something, but the documentation doesn't seem to be clear on what else I should have done.

```zsh
brew install minikube
minikube start --memory 8192 --cpus 4
minikube addons enable ingress
minikube addons enable ingress-dns
sudo vim /etc/resolver/minikube-test
```

```config
# /etc/resolver/minikube-test
domain test
nameserver 192.168.49.2
search_order 1
timeout 5
```

```zsh
kubectl apply -f https://raw.githubusercontent.com/kubernetes/minikube/master/deploy/addons/ingress-dns/example/example.yaml
# command that fails...
nslookup hello-john.test $(minikube ip)
>> ;; connection timed out; no servers could be reached
```

[logs.txt](https://github.com/kubernetes/minikube/files/7638828/logs.txt)

**Comment by ethnhll** [comment]
```
  System Version:	macOS 11.6 (20G165)
  Kernel Version:	Darwin 20.6.0
  Boot Volume:	Macintosh HD
  Boot Mode:	Normal
  Secure Virtual Memory:	Enabled
  System Integrity Protection:	Enabled
  Time since boot:	6 days 9:29
```

**Comment by ethnhll** [comment]
I should clarify that I am using the docker driver. Changing the driver to hyperkit seems to resolve the issue, but the documentation makes no mention of this caveat that MacOS + docker driver is not supported for the addons (in fact the documentation often encourages docker).

**Comment by bidossessi** [comment]
@ethnhll I think the docs do mention it, in the [known issues](https://minikube.sigs.k8s.io/docs/drivers/docker/) section.

**Comment by huxulm** [comment]
hi, bro
i came to the same situation, have you solved the problem?

**Comment by bidossessi** [comment]
@huxulm see [this comment](https://github.com/kubernetes/minikube/issues/13067#issuecomment-995244057). TL;DR, it's only supported on Linux.

**Comment by gerrywd** [comment]
/remove-lifecycle stale

Yuck. This project wants me to sign a contract before I can update the docs. Not going to happen. I release the change above to the public domain so somebody else who's already signed this contract can add it. Please 🙏

**Comment by sharifelgamal** [comment]
I wonder if `minikube tunnel` would help with the ingress-dns addon for the docker driver, it certainly helps with the ingress addon.
