### ISSUE TITLE
windows10 hyperv 隔一天，访问不了

### ISSUE THREAD

**Issue by xiewendan** [kubernetes/minikube#13066]
**重现问题所需的命令**：
{"specversion":"1.0","id":"ef839012-9d5c-4fba-8e27-668e1fc169db","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"delete","endTime":"Tue, 30 Nov 2021 17:16:54 CST","profile":"minikube","startTime":"Tue, 30 Nov 2021 17:12:56 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"7657a263-45c2-4bd6-8978-542152b51f87","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"delete","endTime":"Tue, 30 Nov 2021 17:17:24 CST","profile":"minikube","startTime":"Tue, 30 Nov 2021 17:17:23 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"14c1664b-6f27-4bf6-adc6-a08222ce383c","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"--help","command":"start","endTime":"Tue, 30 Nov 2021 17:20:16 CST","profile":"minikube","startTime":"Tue, 30 Nov 2021 17:20:11 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"87b5336e-3bc6-416d-994d-0a8e64c2e48d","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"delete","endTime":"Tue, 30 Nov 2021 17:43:30 CST","profile":"minikube","startTime":"Tue, 30 Nov 2021 17:43:21 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"034821b3-e3f2-464a-b213-3b64d88d5167","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"--vm-driver=hyperv --disk-size=40000mb --cpus=5 --memory=8096mb --hyperv-virtual-switch=MinikubeSwitch --registry-mirror=https://k775w8t1.mirror.aliyuncs.com","command":"start","endTime":"Tue, 30 Nov 2021 17:46:07 CST","profile":"minikube","startTime":"Tue, 30 Nov 2021 17:44:05 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"192ef026-ded4-48ec-8241-662249828e20","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"stop","endTime":"Wed, 01 Dec 2021 10:49:27 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 10:49:09 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"f0252815-80ed-494a-986a-02d3d07ef64a","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"stop","endTime":"Wed, 01 Dec 2021 12:08:27 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 12:08:20 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"39e6c6e8-91f1-4312-989d-4cd1584f4567","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"delete","endTime":"Wed, 01 Dec 2021 12:08:41 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 12:08:37 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"14fb63e1-5ecc-4707-94a2-83062f37a6c3","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"--vm-driver=hyperv --disk-size=40000mb --cpus=5 --memory=8096mb --hyperv-virtual-switch=MinikubeSwitch --registry-mirror=https://k775w8t1.mirror.aliyuncs.com","command":"start","endTime":"Wed, 01 Dec 2021 12:09:58 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 12:08:51 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"f7c12d5d-c573-4ca9-94f2-1fbde0f91872","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"delete","endTime":"Wed, 01 Dec 2021 19:02:55 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:02:29 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"fb5b3b80-7103-4c3d-8485-7ce84fada865","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"--vm-driver=hyperv --hyperv-virtual-switch=MinikubeSwitch","command":"start","endTime":"Wed, 01 Dec 2021 19:04:38 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:03:21 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"7abb1cfa-6e05-4cbc-8b8e-234e2774e6bb","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"-- get po -A","command":"kubectl","endTime":"Wed, 01 Dec 2021 19:13:55 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:13:46 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"53660098-c6d1-40e2-ba10-8772771b378d","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"-- delete deployment hello-minikube","command":"kubectl","endTime":"Wed, 01 Dec 2021 19:15:00 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:14:59 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"32e9813c-6938-42d3-a148-d7a80f4d5bd3","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"-- create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4","command":"kubectl","endTime":"Wed, 01 Dec 2021 19:15:41 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:15:40 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"36315a9b-31f1-45c2-8bbd-bce8ef3baac6","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"-- get pods","command":"kubectl","endTime":"Wed, 01 Dec 2021 19:15:53 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:15:52 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"9812f02b-33bd-49ef-89f3-fa87e112ec44","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"-- describe deployments","command":"kubectl","endTime":"Wed, 01 Dec 2021 19:16:11 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:16:10 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"6b010a75-bcc8-4fb6-a497-44153896fe13","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"-- describe pods","command":"kubectl","endTime":"Wed, 01 Dec 2021 19:16:28 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:16:27 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"8e290bf2-ea95-445f-a171-b7d7aeb7de59","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"stop","endTime":"Wed, 01 Dec 2021 19:18:58 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:18:42 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"a4b9bd06-24cd-42dc-82df-731f047a8ef6","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"delete","endTime":"Wed, 01 Dec 2021 19:23:20 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:23:13 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"3343f867-3ade-4ea1-a171-5935ecfd4706","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"--vm-driver=hyperv --hyperv-virtual-switch=MinikubeSwitch --insecure-registry=registry-1.docker.io","command":"start","endTime":"Wed, 01 Dec 2021 19:29:25 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:28:12 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"3d393d74-03c2-438b-af7d-e0c5f4419424","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"-- create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4","command":"kubectl","endTime":"Wed, 01 Dec 2021 19:30:47 CST","profile":"minikube","startTime":"Wed, 01 Dec 2021 19:30:46 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"fb75743f-1e36-48e1-8b7d-ca0186e38f3f","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"logs","endTime":"Thu, 02 Dec 2021 10:23:06 CST","profile":"minikube","startTime":"Thu, 02 Dec 2021 10:22:35 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}
{"specversion":"1.0","id":"46028f82-3679-41b9-a964-c102a412ce8d","source":"https://minikube.sigs.k8s.io/","type":"io.k8s.sigs.minikube.audit","datacontenttype":"application/json","data":{"args":"","command":"logs","endTime":"Thu, 02 Dec 2021 10:40:05 CST","profile":"minikube","startTime":"Thu, 02 Dec 2021 10:39:28 CST","user":"GIH-D-27180\\g87","version":"v1.24.0"}}

**失败的命令的完整输出**：<details>
*
E1202 10:39:33.914716    3696 logs.go:267] Failed to list containers for "kube-apiserver": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:35.844952    3696 logs.go:267] Failed to list containers for "etcd": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:37.688596    3696 logs.go:267] Failed to list containers for "coredns": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:39.535530    3696 logs.go:267] Failed to list containers for "kube-scheduler": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:41.506656    3696 logs.go:267] Failed to list containers for "kube-proxy": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:43.384654    3696 logs.go:267] Failed to list containers for "kubernetes-dashboard": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:45.311811    3696 logs.go:267] Failed to list containers for "storage-provisioner": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:47.184741    3696 logs.go:267] Failed to list containers for "kube-controller-manager": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
* ==> Docker <==
E1202 10:39:49.173782    3696 logs.go:190] command /bin/bash -c "sudo journalctl -u docker -n 60" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""

</details>

**`minikube logs`命令的输出**： <details>

I1201 19:29:24.424026   12796 main.go:130] libmachine: [stderr =====>] :
I1201 19:29:24.424026   12796 main.go:130] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I1201 19:29:24.566778   12796 main.go:130] libmachine: [stdout =====>] : 10.225.91.20

I1201 19:29:24.566778   12796 main.go:130] libmachine: [stderr =====>] :
I1201 19:29:24.566778   12796 sshutil.go:53] new ssh client: &{IP:10.225.91.20 Port:22 SSHKeyPath:C:\Users\g87\.minikube\machines\minikube\id_rsa Username:docker}
I1201 19:29:24.669698   12796 ssh_runner.go:152] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.22.3/kubectl apply -f /etc/kubernetes/addons/storage-provisioner.yaml
I1201 19:29:24.943453   12796 main.go:130] libmachine: [stdout =====>] : 10.225.91.20

I1201 19:29:24.943453   12796 main.go:130] libmachine: [stderr =====>] :
I1201 19:29:24.943453   12796 sshutil.go:53] new ssh client: &{IP:10.225.91.20 Port:22 SSHKeyPath:C:\Users\g87\.minikube\machines\minikube\id_rsa Username:docker}
I1201 19:29:25.046982   12796 ssh_runner.go:152] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.22.3/kubectl apply -f /etc/kubernetes/addons/storageclass.yaml
I1201 19:29:25.139179   12796 out.go:176] * Enabled addons: storage-provisioner, default-storageclass
I1201 19:29:25.139179   12796 addons.go:417] enableAddons completed in 1.9432225s
I1201 19:29:25.273526   12796 start.go:473] kubectl: 1.22.4, cluster: 1.22.3 (minor skew: 0)
I1201 19:29:25.274603   12796 out.go:176] * Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

*
E1202 10:39:33.914716    3696 logs.go:267] Failed to list containers for "kube-apiserver": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:35.844952    3696 logs.go:267] Failed to list containers for "etcd": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:37.688596    3696 logs.go:267] Failed to list containers for "coredns": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:39.535530    3696 logs.go:267] Failed to list containers for "kube-scheduler": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:41.506656    3696 logs.go:267] Failed to list containers for "kube-proxy": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:43.384654    3696 logs.go:267] Failed to list containers for "kubernetes-dashboard": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:45.311811    3696 logs.go:267] Failed to list containers for "storage-provisioner": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1202 10:39:47.184741    3696 logs.go:267] Failed to list containers for "kube-controller-manager": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
* ==> Docker <==
E1202 10:39:49.173782    3696 logs.go:190] command /bin/bash -c "sudo journalctl -u docker -n 60" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""
*
* ==> container status <==
E1202 10:39:51.079280    3696 logs.go:190] command /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""
*
* ==> describe nodes <==
</details>

**使用的操作系统版本**：windows10

**具体问题描述**: 启动后，拉取gcr的一个image失败，这个时候还可以正常使用常用的命令， 隔了一天，就爆如下错误：
<details>
E1202 10:46:42.397170   12996 status.go:350] failed to get driver ip: getting IP: IP not found
E1202 10:46:42.397170   12996 status.go:258] status error: getting IP: IP not found
minikube
type: Control Plane
host: Error
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent
</details>

**Comment by spowelljr** [comment]
Hi @xiewendan, what version of minikube are you using? And could you run `minikube logs --file=logs.txt` and upload the generated log file to this issue, thanks!

**Comment by spowelljr** [comment]
Hi @xiewendan, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
