### ISSUE TITLE
Enhance service command to support multiple services

### ISSUE THREAD

**Issue by darkedges** [kubernetes/minikube#13075]
It would be great to see 
https://github.com/txn2/kubefwd incorporated so that you can forward all services in a namespace in a single request.

This would help those running within docker where metallb does not work due to the host not being able to NAT requests into the kubernetes container. Other examples are when you have multiple services and need to implement multiple shells and commands to handle the port forward / services requests.

**Comment by spowelljr** [comment]
Hi @darkedges, thanks for the suggestion! We're open to any PR's that implement this!

**Comment by cdkgoog** [comment]
@spowelljr I'd be happy to take this one. From a design perspective, any ideas on how we want this to work? kubefwd supports quite a few flags. Maybe MVP for this feature would be just supporting forwarding all services in a namespace (-n) and all services in a namespace with label selectors (-l labelname=foo,labelname=bar)?

**Comment by medyagh** [comment]
I am not sure how the implementation would work, but I would be okay with a design that could make it work as long as the user doesnt have to install anything extra

maybe something like "minikube service --all" could be a good idea to forward all services instead of just one

@ckannon please feel free to take a stab at it

**Comment by ckannon** [comment]
Awesome, that's what I was thinking as well.. I don't want to include the
library, more so, some of the functionality.

**Comment by medyagh** [comment]
thank you @ckannon if u dont mind adding it as a PR on minikube repo so I could review that way

**Comment by ckannon** [comment]
Already done, PR is here:
https://github.com/kubernetes/minikube/pull/13367/commits/3629b508d3912fdb593208f7a316ec76ba0dbc66

**Comment by medyagh** [comment]
here is the link to the binary from a PR that I think might fix this issue, do you mind trying it out ?

https://storage.googleapis.com/minikube-builds/13756/minikube-linux-amd64
https://storage.googleapis.com/minikube-builds/13756/minikube-darwin-amd64
https://storage.googleapis.com/minikube-builds/13756/minikube-windows-amd64.exe
