### ISSUE TITLE
Support zsh for `minikube docker-env`

### ISSUE THREAD

**Issue by crucialfelix** [kubernetes/minikube#1307]
BUG

**Minikube version** v0.17.1

**Environment**:
- **OS** OS X El Capitan
- **VM Driver**     "DriverName": "virtualbox",
- **ISO version**  v1.0.7

zsh 5.0.8 (x86_64-apple-darwin15.0)
Docker version 17.03.1-ce, build c6d412e

**What happened**:

Following https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/

docker commands do not work because the exported DOCKER variables are all wrapped with quotes.

```zsh
# Run this command to configure your shell:
eval $(minikube docker-env)

hellonode ❯ echo $DOCKER_HOST
"tcp://192.168.99.100:2376"

hellonode ❯ minikube docker-env                                                                                                                                                                       ⏎
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.99.100:2376"
export DOCKER_CERT_PATH="/Users/crucial/.minikube/certs"
export DOCKER_API_VERSION="1.23"

hellonode ❯ docker --version                                                                                                                                                                          ⏎
Invalid bind address format: "tcp://192.168.99.100:2376"

# I manually fixed DOCKER_HOST to remove the quotes,
# then the next failure:

hellonode ❯ docker --version
could not read CA certificate "\"/Users/crucial/.minikube/certs\"/ca.pem": open "/Users/crucial/.minikube/certs"/ca.pem: no such file or directory

```

Everything has quotes around it !

Manually resetting these allows it to work correctly:

```zsh
hellonode ❯ export DOCKER_CERT_PATH=/Users/crucial/.minikube/certs
hellonode ❯ export DOCKER_TLS_VERIFY=1
hellonode ❯ export DOCKER_API_VERSION=1.23
# now everything works:
hellonode ❯ docker ps
CONTAINER ID        IMAGE                                                        COMMAND                  CREATED             STATUS              PORTS               NAMES
9adf7df675b7        gcr.io/google_containers/kube-dnsmasq-amd64:1.4              "/usr/sbin/dnsmasq..."   22 minutes ago      Up 22 minutes                           k8s_dnsmasq.2d51151_kube-dns-v20-z4099_kube-system_81e5e332-14ae-11e7-8493-080027c2330f_f32cc373
etc.
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by r2d4** [comment]
Not a zsh user, but here is the relevant code.  The default is bash, so zsh is using bash's exports, but we could definitely add specific zsh formatting.

https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/env.go#L78-L80

https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/env.go#L247-L250

**Comment by crucialfelix** [comment]
Ah I suspected it might be a zsh issue. I will have to look into this more: http://unix.stackexchange.com/questions/68694/when-is-double-quoting-necessary

zsh is different than other shells. I wouldn't expect kubernetes to support every quirky shell, but maybe this one should be. thanks

**Comment by jrcamp** [comment]
Works with a newer version of zsh from Homebrew. I'm running:

`zsh 5.3.1 (x86_64-apple-darwin16.4.0)`

**Comment by r2d4** [comment]
@crucialfelix can you check if @jrcamp's solution to upgrade zsh works for you?

**Comment by crucialfelix** [comment]
Yes, it's good now. Thanks @jrcamp 

```
mattermind ❯ eval $(minikube docker-env)
mattermind ❯ echo $DOCKER_HOST
tcp://192.168.99.100:2376
```
