### ISSUE TITLE
Feature request (mounting host paths into the VM for kvm driver) / deprecated method issue

### ISSUE THREAD

**Issue by hir3npatel** [kubernetes/minikube#1308]
When running k8s locally for day-to-day development, a quick code/test cycle is crutial and is the main reason for doing it locally. Previous I ran k8s on the host native with docker and hyperkube, putting k8s volume config in to let the pods use source code directories on the host laptop, this worked well to make changes in the code and see it immediately without having to rebuild the container etc.

Breaking this is a deal-breaker for a quick local dev cycle. With minikube not mounting host paths into the VM, is one now expected to code changes, push it to vm, build container, restart pod, then see if it worked?

Previously I was using the "Run it" step from this link to run k8s on the linux laptop native:
https://github.com/kubernetes/community/blob/master/contributors/devel/local-cluster/docker.md
I know this method is now deprecated for a while, but I continued using it while it worked.
Then I updated to hyperkube-amd64 v1.6.0, which did not start up with the same start up command from that link, mostly because --config is gone. Even after changing --config to --pod-manifest-path, I have issues. The pods start, but the api server has issues. A 'get pods' hangs then times out.

I guess I shouldn't try and diagnose this, but switch to minikube because native is not supported anymore. So I got as far as minikube start succeeding, but saw in the docs that "Note: Host folder sharing is not implemented on Linux yet."

Is it worth pursuing the native route and fixing that, does anyone still run it like that anymore?

minikube v0.17.1
linux mint 18.1
kvm driver
"ISO": "/home/user/.minikube/machines/minikube/boot2docker.iso",
"Boot2DockerURL": "file:///home/user/.minikube/cache/iso/minikube-v1.0.7.iso",

**Comment by r2d4** [comment]
The hypervisor mounting solutions are going to be superseded by the `minikube mount` command.  While there are still a few issues to work out with it today, that will be the preferred way of host-vm folder sharing.  Today, if the `minikube mount` command doesn't satisfy all your requirements, you can use virtualbox on linux, which supports host foldering sharing or the experimental docker support for minikube https://github.com/kubernetes/minikube/tree/master/deploy/docker

**Comment by hir3npatel** [comment]
Ah, I didn't know about minikube mount, and that it supports 9p. Needs to be documented I guess.

In that case the section "Mounted Host Folders" on this link is incorrect/outdated?
https://github.com/kubernetes/minikube

**Comment by r2d4** [comment]
Yeah we should probably document the minikube mount command there.

**Comment by aaron-prindle** [comment]
Fixed with #1335
