### ISSUE TITLE
The ingress addon is not listening on `minikube ip`:80

### ISSUE THREAD

**Issue by victor-sudakov** [kubernetes/minikube#13088]
On minikube version: v1.24.0, commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b-dirty, Manjaro Linux:

when I enable the ingress addon, it's not listening on ports 80 or 443:

```console
$ minikube addons enable ingress
  - Using image k8s.gcr.io/ingress-nginx/controller:v1.0.4
  - Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
  - Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
* Verifying ingress addon...
* The 'ingress' addon is enabled
$ telnet `minikube ip` 80
Trying 192.168.49.2...
telnet: Unable to connect to remote host: Connection refused
```
`kubectl get pods -A` shows that the ingress-nginx-controller-* pod is running. Should not it start listening immediately?

My minikube start command was:
```console
minikube start  --disk-size=50g  --nodes=2 --insecure-registry "192.168.88.0/24" --mount --mount-string ~/.volumes:/volumes
```
I'm attaching the ingress-controller pod log
[ingress-controller.txt](https://github.com/kubernetes/minikube/files/7653951/ingress-controller.txt)

**Comment by victor-sudakov** [comment]
I had to do some guesswork. This should be documented somehow in https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/:

```console
$ minikube node list
minikube	192.168.49.2
minikube-m02	192.168.49.3
$
$ telnet `minikube ip -n minikube-m02` 80
Trying 192.168.49.3...
Connected to 192.168.49.3.
Escape character is '^]'.
```
That''s where my ingress is listening: on the second node.

**Comment by medyagh** [comment]
I believe implentation of ingress assumes u recieve traffic only on control plane
do u mind sharing what driver or OS you are using ?

**Comment by victor-sudakov** [comment]
>  do u mind sharing what driver or OS you are using ?

Manjaro Linux, docker driver
Linux vrs11 5.14.18-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:24:59 UTC 2021 x86_64 GNU/Linux

**Comment by sharifelgamal** [comment]
This might be a bug in our ingress addon for multinode clusters. I would like to take a closer look at this, or have someone who's ingress-savvy take a look at it.

cc @prezha

**Comment by iam-veeramalla** [comment]
I will be happy to contribute to this. Please let me know if you can assign this issue to me.
@medyagh

**Comment by victor-sudakov** [comment]
> make sure that ingress is always deployed on the 1st node in multi-node cluster (referenced by minikube ip)

Oh, thanks a lot!
