### ISSUE TITLE
none: Exiting due to RUNTIME_ENABLE: sudo systemctl daemon-reload:

### ISSUE THREAD

**Issue by mremreozan** [kubernetes/minikube#13091]
**Steps to reproduce the issue:** 

- sudo minikube start --driver=none

Exiting due to RUNTIME_ENABLE: sudo systemctl daemon-reload: exit status 1
stderr:
System has not been booted with systemd as init system (PID 1). Can't operate.

**Comment by medyagh** [comment]
@mremreozan I dont think none drive is supported on your system since it doesnt have systemd

**Comment by mremreozan** [comment]
Yes, you are right. I realized that and I installed systemd from [this documentation](https://kubernetes.io/blog/2020/05/21/wsl-docker-kubernetes-on-the-windows-desktop/ 
[Kubernetes)]
