### ISSUE TITLE
failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containe

### ISSUE THREAD

**Issue by minejzy** [kubernetes/minikube#13097]
**Steps to reproduce the issue:** 
[logs.txt](https://github.com/kubernetes/minikube/files/7660467/logs.txt)
**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>
i have running th command to start k8s cluster, the minikube command as shown below:
minikube start --vm-driver=none --image-mirror-country='cn'

The error message as shown below:
ERROR ImagePull]: failed to pull image registry.cn-hangzhou.aliyuncs.com/google_containe/kube-controller-manager:v1.22.3: output: Error response from daemon: Get https://registry.cn-hangzhou.aliyuncs.com/v2/: write tcp 192.168.8.136:60048->120.55.105.209:443: write: connection reset by peer
, error: exit status 1
</details>

**Comment by sharifelgamal** [comment]
This seems like it was a temporary connection issue to our alibaba mirror. Have you tried this again?

**Comment by klaases** [comment]
Hi @minejzy  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
