### ISSUE TITLE
Need ability to change cluster domain. 

### ISSUE THREAD

**Issue by jbehrends** [kubernetes/minikube#1309]
minikube doesn't expose any arguments that I can see to change the cluster domain.

It appears that localkube controls this via an argument:
`--dns-domain string                            The cluster dns domain (default "cluster.local")`

Is there a way currently to pass arguments like this to localkube?

If not, can this please be added.

**Environment**:
- **OS**: OSX 10.12.3
- **VM Driver**: virtualbox
- **ISO version** : minikube-v1.0.7.iso

**Comment by aaron-prindle** [comment]
Fixed w/ #1321.  Closing.
