### ISSUE TITLE
Minikube Start - Wrong image for MacOS arm architecture users 

### ISSUE THREAD

**Issue by iamjoseph331** [kubernetes/minikube#13129]
In 4. Deploy applications

The commands
```
kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment hello-minikube --type=NodePort --port=8080

```
will result in CrashLoopBackOff. Please replace the image refer with k8s.gcr.io/echoserver-arm:1.8.

Reference: https://stackoverflow.com/questions/61775778/kubernetes-throws-crashloopbackoff-for-echo-server/61776435

**Comment by spowelljr** [comment]
Hi @iamjoseph331, thanks for reporting your issue with minikube!

We have an existing issue for this (https://github.com/kubernetes/minikube/issues/11107), so I'm going to close to issue to reduce duplication, please follow along there, thanks!
