### ISSUE TITLE
"minikube image save" is extremely slow

### ISSUE THREAD

**Issue by Pictor13** [kubernetes/minikube#13132]
### What Happened?

I'm trying to backup (over local host) some docker images that take hours to build (not images of mine; I have no way to reduce that).
This because I want to **`minikube delete` and then restore everything, removing the re-build time**.

Running
```
cd /mini-backup/
minikube image save myimage:mytag myimage_mytag.tar
```
works......
...but **takes so long to complete**. \
Is the command supposed to be _that_ slow?\
Should I expect the same slowness also when putting the images back with `minikube image load`?

The whole reason I was trying to backup & restore images, was to be able to delete the VM and **come back to productivity quickly**.\
But with these timings the strategy doesn't really serve, and I might well delete and rebuild everything from scratch.

Am I doing something wrong?\
**How can I take the images out of Minikube to restore them afterwards?** (in decent times)

**Additionally:**

* I _could_ run a local repository that stores in a local volume mount, but that would require renaming the repository name everywhere in my codebase in order to interface with it.
* just in case, yes, I'm using Virtualbox & no, I can't switch to hyperkit.

### Attach the log file

[log contains too much private data; and is not relevant here: eventually ask for specific info from it]

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Hi @Pictor13, thanks for reporting your issue with minikube!

Curious, how big is the image you're trying to save?

**Comment by Pictor13** [comment]
The image size is ~3.77GB 🙁

**Comment by spowelljr** [comment]
I just tried myself but on a different setup, I did it on Linux using the Docker driver
```
REPOSITORY                                TAG       IMAGE ID       CREATED          SIZE
benchmark                                 latest    8018f5a27c80   59 seconds ago   3.01GB

$ minikube image save benchmark:latest benchmark_latest.tar
real    1m5.835s
user    0m8.389s
sys     0m8.849s
```

How long was yours taking to complete?

**Comment by afbjorklund** [comment]
> Is the command supposed to be _that_ slow?

Yes. It will save a local copy on the VM, before copying.

**Comment by afbjorklund** [comment]
> * I _could_ run a local repository that stores in a local volume mount, but that would require renaming the repository name everywhere in my codebase in order to interface with it.

Just retag the image after loading or pulling it. You could also set your registry up as a pull-through cache.

**Comment by Pictor13** [comment]
@afbjorklund could the pull-through cache spare me from re-tagging the images?

I used to run a local registry on Minikube, as cache (ideal for travelling & no connection); but I couldn't make it "transparent":
proxying the remote registry (_myprivate.registry.net_) via the local registry (_registry2.local_, set as pull-through cache), required additional operations on my side (re-tagging; or updating URIs in codebase to fetch images from registry2.local rather than myprivate.registry.net).

I wanted to `echo "myprivate.registry.net 127.0.0.1" > /etc/hosts` on Minikube VM, to use the local registry transparently; but the `hosts` change would prevent the local registry to resolve the remote registry IP. 😕

**Comment by Pictor13** [comment]
> How long was yours taking to complete?

I don't have an exact benchmark, but the saving was taking some 10-20 minutes. And the loading 5-10 minutes.

Thanks for the benchmark @spowelljr, tho. I'm not sure if the different engine & OS could cause such difference.

**Comment by afbjorklund** [comment]
The registry might be hard-coded to only proxy the "default" (docker.io)

https://docs.docker.com/registry/recipes/mirror/

If you run with a higher log-level, you can see the actual commands...
It will go faster, if you skip the temporary file and pipe directly to output.

e.g. `docker image save myimage:mytag > myimage_mytag.tar`

We couldn't do this in the general API, because every CRI is "special"

**Comment by afbjorklund** [comment]
A separate data disk would have helped with extreme (GB) cases like this one...

* #12166

**Comment by medyagh** [comment]
@Pictor13 
have u tried adding a extra disk to minikube ? (currently only supported by hyperkit and kvm2)
```
      --extra-disks=0: Number of extra disks created and attached to the minikube VM (currently only implemented for hyperkit and kvm2 drivers)
```

**Comment by klaases** [comment]
Hi @Pictor13, have you had a chance to try adding extra disk to minikube as mentioned above by @medyagh?

**Comment by klaases** [comment]
Hi @Pictor13 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by cerebrotecnologico** [comment]
I am observing the same issue. 
I have docker running with lima in MacOSX (intel) 
I have several images that need to be available in minikube.
I decided to `pull` the images with docker and then `load` them into minikube. 
But loading the images is extremely slow.
There is no advantage on perhaps pulling the images directly in minikube rather than copying them locally with `minikube image load` 
```
$ minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0

$ docker pull some-large-image:v1

$ minikube start --extra-config=apiserver.service-node-port-range=1000-65535 \
               --memory=16384m \
               --cpus=max \
               --disk-size 128GB

$ minikube image load "some-large-image:v1" --overwrite=false
```
