### ISSUE TITLE
MacOSX xhyve driver does not mount /Users when minikube is restarted

### ISSUE THREAD

**Issue by julienbachmann** [kubernetes/minikube#1313]
BUG REPORT

**Minikube version** (use `minikube version`): v0.17.1

**Environment**:
- **OS**: OS X 10.11.6
- **VM Driver**: xhyve
- **ISO version** : v1.0.7
- **Install tools**:
- **Others**:

**What happened**:
xhyve driver is supposed to mount `/Users` host folder into the minikube VM. It is working when you start a new minikube instance but if you stop it and start it again, the folder is no no more mounted.

**What you expected to happen**:
I expect that if I stop and then start again the minikube, then the `/Users` folder is still mounted in the minikube image

**How to reproduce it** (as minimally and precisely as possible):
```
HOST$> minikube delete
HOST$> minikube start --vm-driver xhyve
HOST$> minikube ssh
MINIKUBE$> ls -la /Users
total 10
drwxr-xr-x    1 rkt      staff          238 Sep 16  2016 .
drwxr-xr-x   17 root     root           480 Mar 31 13:52 ..
-rw-r--r--    1 rkt      staff            0 Aug  2  2015 .localized
drwxr-xr-x    1 rkt      staff          374 Jun  4  2015 Guest
drwxrwxrwx    1 rkt      staff          340 Sep 16  2016 Shared
drwxrwxrwx    1 rkt      username       340 Sep 16  2016 username
MINIKUBE$>exit
HOST$> minikube stop
HOST$> minikube start --vm-driver xhyve
HOST$> minikube ssh
MINIKUBE$> ls -la /Users
ls: /Users: No such file or directory
```
First we delete minikube to be sure we create a new one. And at the end we can see the `/Users` is no more mounted

**Anything else do we need to know**:

**Comment by justechn** [comment]
https://github.com/kubernetes/minikube/issues/1133

**Comment by julienbachmann** [comment]
Thanks @justechn for pointing me to this closed bug. 

To avoid that someone else enter again this ticker I think we should let it open until the bug is really closed (until a new release of docker-machine-driver-xhyve).

**Comment by r2d4** [comment]
Sure we'll leave this open until a new version of docker-machine-driver-xhyve is released with the fix.

**Comment by aaron-prindle** [comment]
We have just added the `minikube mount` command.  This command should allow for the mounting of the `/Users/` directory with minikube mount /Users.  If you restart the VM, rerunning `minikube mount` will remount the folder.
