### ISSUE TITLE
Can't start minikube,

### ISSUE THREAD

**Issue by DARKBOW923** [kubernetes/minikube#13133]
### What Happened?

When i try to start minikube with ``sudo minikube --start driver=none´` it says the following error:

``Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed to start host: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied´`

I need some help, thanks.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/7687444/log.txt)

### Operating System

Ubuntu

**Comment by spowelljr** [comment]
Hi @DARKBOW923, thanks for reporting your issue with minikube!

Are you able to `sudo rm /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89` and then try starting minikube again?

**Comment by Pictor13** [comment]
To me, running a `rm -fr ~/.minikube` solved a couple of weird issues. You might give it a try before starting the machine.

**Comment by DARKBOW923** [comment]
> Hi @DARKBOW923, thanks for reporting your issue with minikube!
> 
> Are you able to `sudo rm /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89` and then try starting minikube again?

I tried, and it doesn't work

**Comment by DARKBOW923** [comment]
Ok so i don know how to close an issue here,

The solution was copying the .minikube and .kube folders from /root/ to /home/$USER.

Then i deleted the folders located in /root/ and i edited the .config file inside .kube and i changed the /root/ to /home/$USER.

Hope this helps to someone with the same problem.
