### ISSUE TITLE
minikube service failed to start 

### ISSUE THREAD

**Issue by Vijay-git-kub** [kubernetes/minikube#13145]
### What Happened?

I am trying to install minikube on my Linux machine  in proxy enabled environment .  i succeed to download minikube rpm but while starting the minikube failing with below error

  > kubectl.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 64 B / 64 B [--------------------------] 100.00% ? p/s 0s
*
X Failed to update cluster: updating node: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl.sha256: invalid checksum: no checksum found in: https://storage.googleapis.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl.sha256
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

### Attach the log file

file cannot genrate since minikube not running 

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by medyagh** [comment]
@Vijay-git-kub it seems like your network does NOT have access to download kubectl ?

are u using a vpn that restricts ur access to googleapis.com ?

can u check if u can download the file manually ?

https://storage.googleapis.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl.sha256

**Comment by spowelljr** [comment]
Hi @Vijay-git-kub, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by thaisroch** [comment]
minikube stop
minikube delete
minikube start
