### ISSUE TITLE
 minikube addons open efk - connection failed

### ISSUE THREAD

**Issue by Awot83** [kubernetes/minikube#13146]
**Étapes pour reproduire le problème:** 

1.minikube start --memory 4096
2.  minikube addons enable efk
3. minikube addons open efk   > open the browser on a connexion failed

I have already stopped, delete, and restarted minikube
 also for information the dashboard is well accessible in the browser with :  minikube dashboard

minikube is installed in virutalbox on windows 10
I don't understand why I can't access kibana,
Thanks for your help
**Sortie complète de la commande `minikube logs`:**
<details>

</details>

**Sortie complète de la commande échouée:**
<details>

</details>

**Comment by Awot83** [comment]
i have read that it s take almost 1 hour to set up so i wait and here are the logs : after 15 min : error: http2: client connection lost :

minikube kubectl -- logs -f kibana-logging-42h5m -n kube-system
{"type":"log","@timestamp":"2021-12-12T13:49:09Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for graph, ml, kibana, stateSessionStorageRedirect, timelion and status_page. This may take a few minutes"}
**error: http2: client connection lost**

then : 
Minikube>minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Stopped
kubeconfig: Configured

**Comment by sharifelgamal** [comment]
A lot of our addons are maintained on a best effort basis, and unfortunately we don't have a lot of EFK expertise among the maintainers currently. If you could post some logs when EFK is enabled and when you try to acces kibana, perhaps we could help.

**Comment by spowelljr** [comment]
Hi @Awot83, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
