### ISSUE TITLE
Add make target to bump preload version

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#13158]
### What Happened?

simmilar to when we run
`update-golint-version`

https://github.com/medyagh/minikube/blob/dafc6aa0b07040a21dca7a1755c1dcdaeee686f9/hack/update/golint_version/update_golint_version.go#L27

we should have a make target 
`make bump-preload`

that bumps the preload version by 1

### Attach the log file

no

**Comment by NikhilSharmaWe** [comment]
@medyagh I would like to work on it. Could you please elaborate, I have some confusion in understanding the issue here.

**Comment by NikhilSharmaWe** [comment]
@medyagh I would like to work on it. Could you please elaborate, I have some confusion in understanding the issue here.

**Comment by NikhilSharmaWe** [comment]
@medyagh I would like to work on it. Could you please elaborate, I have some confusion in understanding the issue here. What do you mean by
```
we should have a make target
make bump-preload
that bumps the preload version by 1
```

**Comment by NikhilSharmaWe** [comment]
@medyagh the code will be the same as in `make update-golint-version` or not. If it is the same, why do we need it again with another target name. And if not, what should be the correct code in `make bump-preload`, to bump version by 1.

Could you please explain. 

I am making a PR with target name `bump-preload` and running `update_golint_version.go` in it. We can discuss correct way to bump the version by 1.

**Comment by afbjorklund** [comment]
It is not the same.

**Comment by NikhilSharmaWe** [comment]
@afbjorklund Could you provide some guidance how should this functionality be added of bumping the preload version by 1 in `make bump-preload`.

**Comment by afbjorklund** [comment]
I think @klaases is working on it, but maybe @medyagh can explain the feature. I think it's about the preload version. (e.g. 13)

preloaded-images-k8s-**v13**-v1.22.3-containerd-overlay2-amd64.tar.lz4.download

**Comment by medyagh** [comment]
closed by https://github.com/kubernetes/minikube/pull/13217
