### ISSUE TITLE
upgrade minikube API server stopped

### ISSUE THREAD

**Issue by 5u9** [kubernetes/minikube#13198]
**Perintah yang diperlukan untuk merekonstruksi masalah**:

minikube start

**Output penuh dari perintah yang gagal**:<details>

https://pastebin.com/nSwzW8Ya

</details>

**Output dari perintah `minikube logs`**: <details>

[logs.txt](https://github.com/kubernetes/minikube/files/7741624/logs.txt)

</details>

**Versi sistem operasi yang digunakan**:

Ubuntu 20.04 Desktop

❯ minikube version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b

**Comment by spowelljr** [comment]
Hi @5u9, from looking at your logs it looks like you went from using minikube v1.20.0 to v1.24.0 using the same cluster. Try running `minikube delete` and try starting minikube again.

-----

Hai @5u9, dari melihat log Anda, sepertinya Anda beralih dari minikube v1.20.0 ke v1.24.0 menggunakan cluster yang sama. Coba jalankan `minikube delete` dan coba mulai minikube lagi.
