### ISSUE TITLE
Registry addon with docker driver uses port 62214 please use that instead of default port 5000 

### ISSUE THREAD

**Issue by robtayl0r** [kubernetes/minikube#13219]
### What Happened?

What does this mean? The documentation only mentions port 5000.

```
minikube addons enable registry

╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                      │
│    Registry addon with docker driver uses port 62214 please use that instead of default port 5000    │
│                                                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯
📘  For more information see: https://minikube.sigs.k8s.io/docs/drivers/docker
    ▪ Using image registry:2.7.1
    ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
🔎  Verifying registry addon...
🌟  The 'registry' addon is enabled
```

If I'm following [the documentation](https://minikube.sigs.k8s.io/docs/handbook/registry/#docker-on-macos), does this negate the all the mentions of port 5000, replaced with 62214? I've tried both. 

``` sh
% docker push localhost:5000/organization-svc                                                                                             
Using default tag: latest
The push refers to repository [localhost:5000/organization-svc]
Get "http://localhost:5000/v2/": dial tcp [::1]:5000: connect: connection refused

(1) ~/Projects/k8s-configurations
% docker run --rm -it --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:62214,reuseaddr,fork TCP:$(minikube ip):62214"       (DSO-2 +x!>$)
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ncurses-terminfo-base (6.3_p20211120-r0)
(2/4) Installing ncurses-libs (6.3_p20211120-r0)
(3/4) Installing readline (8.1.1-r0)
(4/4) Installing socat (1.7.4.2-r0)
Executing busybox-1.34.1-r3.trigger
OK: 7 MiB in 18 packages
^C%                                                                                                                                                     

(130) 6s ~/Projects/k8s-configurations
% docker tag 105afe044d89 localhost:62214/organization-svc                                                                                 

~/Projects/k8s-configurations
% docker push localhost:62214/organization-svc                                                                                            
Using default tag: latest
The push refers to repository [localhost:62214/organization-svc]
Get "http://localhost:62214/v2/": dial tcp [::1]:62214: connect: connection refused
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/7749999/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by klaases** [comment]
Hi @robtayl0r, from what I can tell, the [doc](https://minikube.sigs.k8s.io/docs/handbook/registry/#docker-on-macos) says to ignore the other port that is recommended by Minikube and just use the port 5000.

Can you try instead using port `5000` in your command:

```
% docker run --rm -it --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:62214,reuseaddr,fork TCP:$(minikube ip):62214"       (DSO-2 +x!>$)
```

**Comment by klaases** [comment]
Hi @robtayl0r – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by kcirtapfromspace** [comment]
Feel like needing to start up an additional listener is super hacky. like why not make the add-on require the ingress & post to port 5001. 

1/10 overall poor experience & poor documentation. Like should you tag your images with the random port? what happens when you want to access that from inside the cluster which is listening on 5000.? 

Docs & solution need a lot more work for it to make any sense of what is supposed to happen.
