### ISSUE TITLE
Support for Nvidia RTX 30X0: nvidia-driver-installer addon fails to start (driver fails to install in the container) 

### ISSUE THREAD

**Issue by skol101** [kubernetes/minikube#13228]
### What Happened?

minikube start --driver kvm2 --kvm-gpu
minikube addons enable nvidia-gpu-device-plugin
minikube addons enable nvidia-driver-installer

When looking inside nvidia-driver-installer pod I can observe that it tries to install NVIDIA GPU driver 390.67 , which obviously doesn't support RTX 3090 (or any 30X0 Nvidia GPU).

Please, provide instructions on how to update existing addon or use custom addon where I could point the image to the latest Nvidia GPU driver.

### Attach the log file

To be provided.

### Operating System

Ubuntu

### Driver

KVM2

**Comment by skol101** [comment]
This fix is to set NVIDIA_DRIVER_VERSION in the env variables for the container as suggested here https://github.com/GoogleCloudPlatform/container-engine-accelerators/issues/204, but how do I do that if minikube comes precompiled ?

**Comment by skol101** [comment]
KVM2 doesn't support RTX 30X0/20X0 drivers because nvidia. Had to usedriver none and nvidia k8s plugin to make it work.

**Comment by joaquinfdez** [comment]
@skol101 I actually trying to do it with driver none but it is not working. Here I posted my issue:

https://github.com/kubernetes/minikube/issues/16827

Did you have any problems with your installation?
