### ISSUE TITLE
localhost:8443 was refused ? 

### ISSUE THREAD

**Issue by kimyongyeon** [kubernetes/minikube#13242]
### What Happened?

    ▪ You are trying to run amd64 binary on M1 system. Please consider running darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.24.0/minikube-darwin-arm64.)
E1225 19:48:42.706902   49141 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

### Attach the log file

    ▪ You are trying to run amd64 binary on M1 system. Please consider running darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.24.0/minikube-darwin-arm64.)
E1225 19:48:42.706902   49141 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

**Comment by spowelljr** [comment]
Hi @kimyongyeon, thanks for reporting your issue with minikube!

The first thing you posted is: `You are trying to run amd64 binary on M1 system. Please consider running darwin/arm64 binary instead (Download at https://github.com/kubernetes/minikube/releases/download/v1.24.0/minikube-darwin-arm64.)`

This is likely your issue, please download the arm64 binary of minikube and try using that instead.

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this issue for now. If you try the arm64 binary as recommended above (after a `minikube delete --all --purge`) and still have issues, please reopen this with more details.
