### ISSUE TITLE
Can't start Minikube since Win 11 upgrade

### ISSUE THREAD

**Issue by jorgeolive** [kubernetes/minikube#13243]
### What Happened?

I am unable to start my minikube cluster after upgrading to windows 11.  I've tried to re-install docker desktop, Minikube, WSL 2 stuff with no luck at all. Seems that there's some internal connectivity issue due to control pane not starting but quite lost here. 

```
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get "http://localhost:10248/healthz": dial tcp: lookup localhost on 192.168.65.2:53: no such host.
```

```
Dec 25 22:41:05 minikube kubelet[48606]: I1225 22:41:05.931936   48606 docker_service.go:277] "Setting cgroupDriver" cgroupDriver="cgroupfs"
Dec 25 22:41:05 minikube kubelet[48606]: E1225 22:41:05.933862   48606 docker_service.go:416] "Streaming server stopped unexpectedly" err="listen tcp: lookup localhost on 192.168.65.2:53: no such host"
```

Thanks,
Jorge.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/7776337/logs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by jorgeolive** [comment]
I found out the problem. The MINIKUBE_HOME environment variable had no value; For some reason clean reinstalls didn't map it to my local .minikube folder.

**Comment by spowelljr** [comment]
If `MINIKUBE_HOME` is not set it defaults to `C:\Users\<user>\.minikube` which I can see in your provided logs that it was doing so. After setting `MINIKUBE_HOME` is starting working for you?

**Comment by jorgeolive** [comment]
Yes, it works. For some reason, fresh Minikube installations were not able to create and set up this environment variable, which got deleted when upgrading from Windows 10 to Windows 11.

**Comment by spowelljr** [comment]
The `MINIKUBE_HOME` environmental variable is not required, it's only if you want to set a specific folder to use. If `MINIKUBE_HOME` isn't set it will default to `C:\Users\<user>\.minikube` on Windows.

I can see the default was working correctly from the logs:
```
I1225 23:35:35.359935   20116 preload.go:148] Found local preload: C:\Users\joliv\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v13-v1.22.3-docker-overlay2-amd64.tar.lz4
I1225 23:35:35.359935   20116 cache.go:57] Caching tarball of preloaded images
I1225 23:35:35.359935   20116 preload.go:174] Found C:\Users\joliv\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v13-v1.22.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I1225 23:35:35.359935   20116 cache.go:60] Finished verifying existence of preloaded tar for  v1.22.3 on docker
I1225 23:35:35.360452   20116 profile.go:147] Saving config to C:\Users\joliv\.minikube\profiles\minikube\config.json ...
```

A minikube installation does not set an environmental variable for `MINIKUBE_HOME`, that's completely up to the user to set if desired.

The issue here is why didn't your minikube start without `MINIKUBE_HOME` being set, but if that's not something you're interested in debugging feel free to close the issue.

**Comment by spowelljr** [comment]
I haven't heard back so I'm going to close this issue, but you experience more problems feel free to reopen this issue, thanks!
