### ISSUE TITLE
minikube start --driver=docker

### ISSUE THREAD

**Issue by nallagondu** [kubernetes/minikube#13248]
### What Happened?

PS C:\Users\g> minikube start --driver=docker
* minikube v1.24.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the docker driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Creating docker container (CPUs=2, Memory=4000MB) ...
! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 3.6198528s
* Restarting the docker service may improve performance.
* Preparing Kubernetes v1.22.3 on Docker 20.10.8 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...

X Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error writing file C:\Users\nallag\.kube\config: open C:\Users\nallag\.kube\config: Access is denied.
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

PS C:\Users\g> minikube logs --file=log.tx

**Comment by spowelljr** [comment]
Hi @nallagondu, thanks for reporting your issue with minikube!

So you're running the command from `C:\Users\g` but it looks like it's trying to access the kube config in `C:\Users\nallag`. Do you have multiple users accounts on your machine?

Try `$env:KUBECONFIG = "C:\Users\g\.kube\config"`

**Comment by medyagh** [comment]
Hi @@nallagondu, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
