### ISSUE TITLE
Ingress DNS: Confirm that domain names are resolving on the host OS NOT working as per document

### ISSUE THREAD

**Issue by getkub** [kubernetes/minikube#13260]
Regarding documentation: https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/
Did exactly as per steps
But the step:
```
Confirm that domain names are resolving on the host OS
ping hello-john.test
ping hello-jane.test
```
is NOT working. Any extra steps needed or is the documenation incorrect?

**Comment by klaases** [comment]
Hi @getkub, if you don't mind, could you please provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by getkub** [comment]
Unfortunately I've uninstalled minikube as it was really hard to resolve DNS. (and went with k3sup due to urgency)

**Comment by damianobarbati** [comment]
@getkub and how are you managing your local kube cluster? can you give some indication?

I'm having hard times trying to host based routing working both on my imac (intel) and macbook (silicon), what a mess.
