### ISSUE TITLE
Minikube installation failed in new MacOS Chip M1 - OS Big Sur

### ISSUE THREAD

**Issue by koushikmgithub** [kubernetes/minikube#13265]
### What Happened?

I am trying to install minikube on my mac os with M1 chip and following below guideline.

https://minikube.sigs.k8s.io/docs/start/

I am running docker desktop 20.10.8 on my mac and getting the following error when I start minikube. Do I need to do anything for this to work on the new macos chip M1?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/7792940/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @koushikmgithub, thanks for reporting your issue with minikube!

First, make sure you're running the terminal you're using as administrator.

Then try `minikube delete --all` and then try starting minikube again, thanks!

**Comment by klaases** [comment]
Hi @koushikmgithub – did you have a chance to apply @spowelljr's suggestion above?

Going to go ahead and close this issue as some time has passed. Thank you for sharing your experience!
