### ISSUE TITLE
Allow specification of the Virtual Switch to use with the Hyper-V driver

### ISSUE THREAD

**Issue by gbraad** [kubernetes/minikube#1326]
This is more of a question, than a bug report. As I have a hunch and an issue with https://github.com/minishift/minishift/issues/590. Upon creation of an instance with Hyper-V, always the first Virtual Switch is selected. However, the driver allows you to override this with `HYPERV_VIRTUAL_SWITCH`. Although, this is part of the `GetCreateFlags`... Is this function ever called?

**What you expected to happen**:
Allow override of the virtual switch to be used with the Hyper-V driver using the environment variables as described in https://docs.docker.com/machine/drivers/hyper-v/#usage.

**What actually happens**
The first switch is always selected.

Note: sorry for the scarce information, but currently on paternity leave, but I do want to be sure this works as expected.

**Comment by gbraad** [comment]
```
PS C:\Users\gbraad\Downloads> $env:HYPERV_VIRTUAL_SWITCH="External (Wireless)"
PS C:\Users\gbraad\Downloads> .\minikube-windows-amd64.exe start --vm-driver hyperv --v=3
========================================
kubectl could not be found on your path.  kubectl is a requirement for using minikube
To install kubectl, please do the following:

download kubectl from:
https://storage.googleapis.com/kubernetes-release/release/v1.5.3/bin/windows/amd64/kubectl.exe
Add kubectl to your system PATH

To disable this message, run the following:

minikube config set WantKubectlDownloadMsg false
========================================
Starting local Kubernetes cluster...
Starting VM...
Running pre-create checks...
Creating machine...
(minikube) Downloading C:\Users\gbraad\.minikube\cache\boot2docker.iso from file://C:/Users/gbraad/.minikube/cache/iso/minikube-v1.0.7.iso...
(minikube) Creating SSH key...
(minikube) Creating VM...
(minikube) Using switch "External (Ethernet)"
(minikube) Creating VHD
```

**Comment by aaron-prindle** [comment]
minikube has the flag `--hyperv-virtual-switch=VSWITCH_NAME` which can be set in `minikube start`

**Comment by aaron-prindle** [comment]
Also minikube accepts its flag parameters as environment variables from: 
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/root.go#L161
So the environment variable `MINIKUBE_HYPERV_VIRTUAL_SWITCH=VSWITCH_NAME` should also work.

**Comment by gbraad** [comment]
Check, I see: 
https://github.com/kubernetes/minikube/blob/4b3459ed5baefb6d94f174f0e2d790c4f3eb3985/cmd/minikube/cmd/config/config.go#L157

Will try this...

**Comment by gbraad** [comment]
Works as expected. Thanks

```powershell
PS C:\Users\gbraad\Downloads> $env:MINIKUBE_HYPERV_VIRTUAL_SWITCH="External (Wireless)"
PS C:\Users\gbraad\Downloads> .\minikube-windows-amd64.exe start --vm-driver hyperv --v=3
========================================
kubectl could not be found on your path.  kubectl is a requirement for using minikube
To install kubectl, please do the following:

download kubectl from:
https://storage.googleapis.com/kubernetes-release/release/v1.5.3/bin/windows/amd64/kubectl.exe
Add kubectl to your system PATH

To disable this message, run the following:

minikube config set WantKubectlDownloadMsg false
========================================
Starting local Kubernetes cluster...
Starting VM...
Running pre-create checks...
Creating machine...
(minikube) Downloading C:\Users\gbraad\.minikube\cache\boot2docker.iso from file://C:/Users/gbraad/.minikube/cache
o/minikube-v1.0.7.iso...
(minikube) Creating SSH key...
(minikube) Creating VM...
(minikube) Using switch "External (Wireless)"
(minikube) Creating VHD
```

**Comment by reza-ebrahimi** [comment]
https://github.com/kubernetes/minikube/issues/1523
