### ISSUE TITLE
Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.18.0

### ISSUE THREAD

**Issue by ediazm** [kubernetes/minikube#13284]
### What Happened?

When I try to run minikube start I get the same problem as was reported on the issue:
https://github.com/kubernetes/minikube/issues/9860

### Attach the log file

I tried to run the command: minikube logs --file=log.txt 
and I got the following error
E0101 14:18:44.945582   75049 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.0/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.0/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by spowelljr** [comment]
@ediazm Try running `minikube delete --all` and then run `minikube logs --file=log.txt` again.

**Comment by ediazm** [comment]
I was able to create the logfile attaching it. Thank you
[log.txt](https://github.com/kubernetes/minikube/files/7836064/log.txt)

**Comment by spowelljr** [comment]
`error execution phase certs/apiserver-kubelet-client: failed to write or validate certificate "apiserver-kubelet-client": failure loading apiserver-kubelet-client certificate: failed to load certificate: the certificate has expired`

Looks like you're getting some sort of certificate error, can you try running `minikube delete --all --purge` to clear out your existing minikube certs and then try starting minikube again.

**Comment by sharifelgamal** [comment]
hey @ediazm, did the advice above help?

**Comment by ediazmen** [comment]
Yes. It solved my problem, thank you!!!

**Comment by ediazm** [comment]
Yes, it solved my problem, thank you!!!
