### ISSUE TITLE
Cannot remove Docker images through minikube image rm

### ISSUE THREAD

**Issue by cdivita** [kubernetes/minikube#13289]
### What Happened?

Since `minikube cache` is going to be deprecated, I'm using `minikube image` for managing images.

Adding images works fine, but I'm not able to remove them. For example, I've added the [hello-world](https://hub.docker.com/_/hello-world) image using the following command:

`minikube image load hello-world`

Then, when I try to delete it through the command:

`minikube image unload hello-world`

I got the following error:

> Failed to remove images for profile minikube error removing images: remove image docker.: docker rmi hello-world: Process exited with status 1
stdout:
>
> stderr:
Error response from daemon: conflict: unable to remove repository reference "hello-world" (must force) - container 8e09c64c6772 is using its referenced image feb5d9fea6a5

The only way to remove the image is deleting it them from the `~/.minikube/cache/images` directory.

### Attach the log file

N/A

### Operating System

macOS (Default)

### Driver

Hyperkit

**Comment by spowelljr** [comment]
Hi @cdivita, thanks for reporting your issue with minikube!

What version of minikube are you using? I tried your two commands on v1.24.0 and it was successful for me.

**Comment by cdivita** [comment]
I'm using minikube 1.24.0 also.

**Comment by spowelljr** [comment]
I also used macOS and the Docker driver. Could you try deleting the cluster `minikube delete --all` and then try starting and running the image commands again and see if that helps.

**Comment by cdivita** [comment]
I can try, however I'm using the Hyperkit driver since I'm using minikube as Docker Desktop replacement

**Comment by spowelljr** [comment]
Ah, you indicated that you're using the Docker driver in the initial issue creation, let me try using HyperKit.

**Comment by cdivita** [comment]
> Ah, you indicated that you're using the Docker driver in the initial issue creation, let me try using HyperKit.

My fault, sorry. I updated the issue

**Comment by spowelljr** [comment]
It was successful for me with HyperKit as well, can you try `minikube delete --all` and then starting minikube again and running the image commands and see if that resolves your issue, thanks!

**Comment by cdivita** [comment]
It works, thanks
