### ISSUE TITLE
Error on volume mounting

### ISSUE THREAD

**Issue by shankar524** [kubernetes/minikube#13285]
### What Happened?

So I tried mapping volumes by running ` minikube mount $PWD:/config` --port 54296 and I got this following issue
```
Exiting due to GUEST_MOUNT_COULD_NOT_CONNECT: /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=54296,trans=tcp,version=9p2000.L 192.168.64.1 /config": Process exited with status 32
stdout:

stderr:
mount: /config: mount(2) system call failed: Connection timed out
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/7798561/log.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by klaases** [comment]
Hi @shankar524, would you be able to try running this without the `port` flag?

In terms of debugging, it might be that the port is not set correctly.

**Comment by klaases** [comment]
Hi @[shankar524](https://github.com/shankar524), – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
