### ISSUE TITLE
`minikube version` should not create $HOME/.minikube folder structure

### ISSUE THREAD

**Issue by keimoon** [kubernetes/minikube#1330]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): 0.17.1

**Environment**:
- OS: Mac OS X 10.11.6:
- **VM Driver**:  virtualbox
- **ISO version**: minikube-v1.0.7.iso
- **Install tools**:
- **Others**:

**What happened**: `minikube version` created HOME/.minikube folder structure

**What you expected to happen**: `minikube version` should not have unexpected side effect like that

**How to reproduce it** (as minimally and precisely as possible): Delete the machine, delete $HOME/.minikube and run `minikube version`

**Comment by aaron-prindle** [comment]
This is due to this PersistentPreRun call in the `minikube` root command.  I agree this call does not make sense for commands like `versions` or `delete`.  We could move folder creation to a subset of functions and remove it from `root.go` or we could override the PersistentPreRun in `version`

**Comment by r2d4** [comment]
We should probably look into moving some of the log level setup and client configration to init() anyways.
