### ISSUE TITLE
docker "Failed to enable" when not using systemd

### ISSUE THREAD

**Issue by djangolo** [kubernetes/minikube#13315]
### What Happened?

when trying to execute the:
minikube start --driver=none 

minikube does not start properly

### Attach the log file

*
* ==> Audit <==
* |---------|------|---------|------|---------|------------|----------|
| Command | Args | Profile | User | Version | Start Time | End Time |
|---------|------|---------|------|---------|------------|----------|
|---------|------|---------|------|---------|------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/01/08 00:30:07
Running on machine: N-20L6PF1N8SPF
Binary: Built with gc go1.17.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0108 00:30:07.352829     719 out.go:297] Setting OutFile to fd 1 ...
I0108 00:30:07.352921     719 out.go:349] isatty.IsTerminal(1) = true
I0108 00:30:07.352924     719 out.go:310] Setting ErrFile to fd 2...
I0108 00:30:07.352927     719 out.go:349] isatty.IsTerminal(2) = true
I0108 00:30:07.353000     719 root.go:313] Updating PATH: /home/django/.minikube/bin
W0108 00:30:07.353101     719 root.go:291] Error reading config file at /home/django/.minikube/config/config.json: open /home/django/.minikube/config/config.json: no such file or directory
I0108 00:30:07.353218     719 out.go:304] Setting JSON to false
I0108 00:30:07.353784     719 start.go:112] hostinfo: {"hostname":"N-20L6PF1N8SPF","uptime":1073,"bootTime":1641600735,"procs":10,"os":"linux","platform":"rocky","platformFamily":"rhel","platformVersion":"8.5","kernelVersion":"5.10.16.3-microsoft-standard-WSL2","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"4a5d14d9-c754-48c2-a4b8-15c26e7d21d3"}
I0108 00:30:07.353859     719 start.go:122] virtualization:
I0108 00:30:07.356408     719 out.go:176] 😄  minikube v1.24.0 on Rocky 8.5
W0108 00:30:07.356605     719 preload.go:294] Failed to list preload files: open /home/django/.minikube/cache/preloaded-tarball: no such file or directory
I0108 00:30:07.356611     719 notify.go:174] Checking for updates...
I0108 00:30:07.356877     719 config.go:176] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.22.3
I0108 00:30:07.357078     719 exec_runner.go:51] Run: systemctl --version
I0108 00:30:07.361061     719 driver.go:343] Setting default libvirt URI to qemu:///system
I0108 00:30:07.373726     719 out.go:176] ✨  Using the none driver based on existing profile
I0108 00:30:07.373783     719 start.go:280] selected driver: none
I0108 00:30:07.373788     719 start.go:762] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.28@sha256:4780f1897569d2bf77aafb3d133a08d42b4fe61127f06fcfc90c2c5d902d893c Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.234.180 Port:8443 KubernetesVersion:v1.22.3 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/home/django:/minikube-host}
I0108 00:30:07.373863     719 start.go:773] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0108 00:30:07.376184     719 cni.go:93] Creating CNI manager for ""
I0108 00:30:07.376192     719 cni.go:147] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0108 00:30:07.376196     719 start_flags.go:282] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.28@sha256:4780f1897569d2bf77aafb3d133a08d42b4fe61127f06fcfc90c2c5d902d893c Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.234.180 Port:8443 KubernetesVersion:v1.22.3 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/home/django:/minikube-host}
I0108 00:30:07.378736     719 out.go:176] 👍  Starting control plane node minikube in cluster minikube
I0108 00:30:07.378871     719 profile.go:147] Saving config to /home/django/.minikube/profiles/minikube/config.json ...
I0108 00:30:07.379057     719 cache.go:206] Successfully downloaded all kic artifacts
I0108 00:30:07.379091     719 start.go:313] acquiring machines lock for minikube: {Name:mkbcad290f60af1a82d13e84cc846fb1ea3daa11 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0108 00:30:07.379298     719 start.go:317] acquired machines lock for "minikube" in 195µs
I0108 00:30:07.379308     719 start.go:93] Skipping create...Using existing machine configuration
I0108 00:30:07.379311     719 fix.go:55] fixHost starting: m01
W0108 00:30:07.379472     719 none.go:130] unable to get port: "minikube" does not appear in /home/django/.kube/config
I0108 00:30:07.379478     719 api_server.go:165] Checking apiserver status ...
I0108 00:30:07.379504     719 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0108 00:30:07.399134     719 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0108 00:30:07.399172     719 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0108 00:30:07.412150     719 fix.go:108] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0108 00:30:07.412161     719 fix.go:134] unexpected machine state, will restart: <nil>
I0108 00:30:07.415258     719 out.go:176] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0108 00:30:07.416719     719 profile.go:147] Saving config to /home/django/.minikube/profiles/minikube/config.json ...
I0108 00:30:07.416881     719 start.go:267] post-start starting for "minikube" (driver="none")
I0108 00:30:07.416891     719 start.go:277] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0108 00:30:07.416966     719 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0108 00:30:07.427097     719 main.go:130] libmachine: Couldn't set key PLATFORM_ID, no corresponding struct field found
I0108 00:30:07.427115     719 main.go:130] libmachine: Couldn't set key CPE_NAME, no corresponding struct field found
I0108 00:30:07.427124     719 main.go:130] libmachine: Couldn't set key ROCKY_SUPPORT_PRODUCT, no corresponding struct field found
I0108 00:30:07.427131     719 main.go:130] libmachine: Couldn't set key ROCKY_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
I0108 00:30:07.430537     719 out.go:176] ℹ️  OS release is Rocky Linux 8.5 (Green Obsidian)
I0108 00:30:07.430604     719 filesync.go:126] Scanning /home/django/.minikube/addons for local assets ...
I0108 00:30:07.430647     719 filesync.go:126] Scanning /home/django/.minikube/files for local assets ...
I0108 00:30:07.430675     719 start.go:270] post-start completed in 13.77ms
I0108 00:30:07.430681     719 fix.go:95] none is local, skipping auth/time setup (requires ssh)
I0108 00:30:07.430683     719 fix.go:57] fixHost completed within 51.3732ms
I0108 00:30:07.430685     719 start.go:80] releasing machines lock for "minikube", held for 51.3829ms
I0108 00:30:07.431002     719 exec_runner.go:51] Run: sudo systemctl is-active --quiet service containerd
I0108 00:30:07.431199     719 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0108 00:30:07.443653     719 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/dockershim.sock
image-endpoint: unix:///var/run/dockershim.sock
" | sudo tee /etc/crictl.yaml"
I0108 00:30:07.465722     719 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0108 00:30:07.480931     719 exec_runner.go:51] Run: sudo systemctl enable docker.socket
E0108 00:30:07.493419     719 docker.go:131] "Failed to enable" err="sudo systemctl enable docker.socket: exit status 1\nstdout:\n\nstderr:\nFailed to enable unit, unit docker.socket does not exist.\n" service="docker.socket"
I0108 00:30:07.493514     719 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0108 00:30:07.509281     719 out.go:176]
W0108 00:30:07.509474     719 out.go:241] ❌  Exiting due to RUNTIME_ENABLE: sudo systemctl daemon-reload: exit status 1
stdout:

stderr:
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down

W0108 00:30:07.509501     719 out.go:241]
W0108 00:30:07.510349     719 out.go:241] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

*

### Operating System

Other

**Comment by afbjorklund** [comment]
Currently there are still a few places left that has systemd hardcoded, it is supposed to use the "sysinit" wrapper.

* #12276

Upstream support for not using systemd is getting less and less tested, since all major distros have changed now.

**Comment by afbjorklund** [comment]
I think the main issue here is running under WSL2, and that is covered in other issues.

```json
{
  "hostname": "N-20L6PF1N8SPF",
  "uptime": 1073,
  "bootTime": 1641600735,
  "procs": 10,
  "os": "linux",
  "platform": "rocky",
  "platformFamily": "rhel",
  "platformVersion": "8.5",
  "kernelVersion": "5.10.16.3-microsoft-standard-WSL2",
  "kernelArch": "x86_64",
  "virtualizationSystem": "",
  "virtualizationRole": "",
  "hostId": "4a5d14d9-c754-48c2-a4b8-15c26e7d21d3"
}

```

**Comment by klaases** [comment]
Hi @djangolo, did you have a chance to review @afbjorklund's comments above?

**Comment by spowelljr** [comment]
Hi @djangolo, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
