### ISSUE TITLE
Exiting due to GUEST_STATUS: state: unknown state "minikube": docker container inspect minikube --format=: exit status 1

### ISSUE THREAD

**Issue by addy3494** [kubernetes/minikube#13330]
### What Happened?

Unable to start, Anything i'm missing. Was working fine few days back
[logs.txt](https://github.com/kubernetes/minikube/files/7852911/logs.txt)
.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/7852912/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
This is not supposed to fail, it is just a sanity check that the volume contents was copied correctly from the kicbase image:

`docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.28@sha256:4780f1897569d2bf77aafb3d133a08d42b4fe61127f06fcfc90c2c5d902d893c -d /var/lib returned with exit code 125`

The volume was created OK, so hard to tell why `/var/lib` is missing ?

`docker volume create minikube --label name.minikube.sigs.k8s.io=minikube --label created_by.minikube.sigs.k8s.io=true`

**Comment by spowelljr** [comment]
Hi @addy3494, it seems like the minikube container got deleted from Docker somehow. I'm assuming `minikube delete --all` and then starting minikube would resolve this issue.

**Comment by addy3494** [comment]
Yeah I did it and it's fine now.

**Comment by spowelljr** [comment]
Glad it works, I'm going to close this issue, thanks for using minikube!
