### ISSUE TITLE
improve "make update-kubeadm-constants" to go over "Patch" versions of kuberentes 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#13338]
we have an automation for bumping the kubeadm constants,
```
make update-kubeadm-constants
```

thats runs as a cron job in github action
https://github.com/kubernetes/minikube/blob/master/.github/workflows/update-kubadm-constants.yml

that creates a PR like this
https://github.com/kubernetes/minikube/pull/13336

the code for the script is in 
https://github.com/kubernetes/minikube/blob/master/hack/update/kubeadm_constants/update_kubeadm_constants.go

the current code goes over kubernetes Minor Versions (1.22, 1.23,...)
and then downloads the kubeadm for that minior version and then runs "config images list"
```
$ curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.24.0-alpha.1/bin/linux/amd64/kubeadm

$ ./kubeadm config images list
k8s.gcr.io/kube-apiserver:v1.23.1
k8s.gcr.io/kube-controller-manager:v1.23.1
k8s.gcr.io/kube-scheduler:v1.23.1
k8s.gcr.io/kube-proxy:v1.23.1
k8s.gcr.io/pause:3.6
k8s.gcr.io/etcd:3.5.1-0
k8s.gcr.io/coredns/coredns:v1.8.6
```

I noticed for 1.24 it still using 
```
k8s.gcr.io/kube-apiserver:v1.23.1
```

then @afbjorklund pointed out that we should pass the --kuberntes-version to the `$ ./kubeadm config images list` command

which gives us this:
```
$ ./kubeadm config images list --kubernetes-version=1.24.0
W0112 14:59:03.059033 1526372 images.go:80] could not find officially supported version of etcd for Kubernetes v1.24.0, falling back to the nearest etcd version (3.5.1-0)
k8s.gcr.io/kube-apiserver:v1.24.0
k8s.gcr.io/kube-controller-manager:v1.24.0
k8s.gcr.io/kube-scheduler:v1.24.0
k8s.gcr.io/kube-proxy:v1.24.0
k8s.gcr.io/pause:3.6
k8s.gcr.io/etcd:3.5.1-0
k8s.gcr.io/coredns/coredns:v1.8.6
```

so we need to change our automation to go over all releases of kubernetes (including patched versions)
and run the 

```
kubeadm config images list --kubernetes-version=VERSION
```

this will make a huge constants file but since it is auto-generated it is okay.
and this will make preload tar bals accurate and user wont have to re-download the image again

**Comment by afbjorklund** [comment]
You can probably remove all the kubernetes components from the version list, since they _always_ match ?

~~k8s.gcr.io/kube-apiserver:v1.24.0~~
~~k8s.gcr.io/kube-controller-manager:v1.24.0~~
~~k8s.gcr.io/kube-scheduler:v1.24.0~~
~~k8s.gcr.io/kube-proxy:v1.24.0~~
k8s.gcr.io/pause:3.6
k8s.gcr.io/etcd:3.5.1-0
k8s.gcr.io/coredns/coredns:v1.8.6

Maybe double-check the names or something. If there is a new component, or someone moved something.

**Comment by medyagh** [comment]
> You can probably remove all the kubernetes components from the version list, since they _always_ match ?
> 
> ~k8s.gcr.io/kube-apiserver:v1.24.0~ ~k8s.gcr.io/kube-controller-manager:v1.24.0~ ~k8s.gcr.io/kube-scheduler:v1.24.0~ ~k8s.gcr.io/kube-proxy:v1.24.0~ k8s.gcr.io/pause:3.6 k8s.gcr.io/etcd:3.5.1-0 k8s.gcr.io/coredns/coredns:v1.8.6
> 
> Maybe double-check the names or something. If there is a new component, or someone moved something.
> 
> * [--image-repository + coredns pulling issue due to namespace removed #13324 (comment)](https://github.com/kubernetes/minikube/issues/13324#issuecomment-1009333023)

thats intersting,

look at this experiment, seems like kubeadm just dumbly prints whatever we pass to it
```
16:25:34 medya
$ ./kubeadm config images list --kubernetes-version=1.23.100000
k8s.gcr.io/kube-apiserver:v1.23.100000
k8s.gcr.io/kube-controller-manager:v1.23.100000
k8s.gcr.io/kube-scheduler:v1.23.100000
k8s.gcr.io/kube-proxy:v1.23.100000
k8s.gcr.io/pause:3.6
k8s.gcr.io/etcd:3.5.1-0
k8s.gcr.io/coredns/coredns:v1.8.6
```
