### ISSUE TITLE
add kubeadm v1beta3  template for newer k8s version

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#13337]
kubeadm v1beta3 is out  https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta3/

for kubernetes 1.23.0 and above we could use it

we should add a file to 
https://github.com/medyagh/minikube/blob/25d17c2dde4920c00b4fe6f42aece999ce92cd5c/pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta2.go#L21

and then make kubeadm init to use that template instead for k8s versions 1.23.0+

**Comment by medyagh** [comment]
```
$ ./kubeadm config print init-defaults
apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: abcdef.0123456789abcdef
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 1.2.3.4
  bindPort: 6443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  imagePullPolicy: IfNotPresent
  name: node
  taints: null
---
apiServer:
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: /etc/kubernetes/pki
clusterName: kubernetes
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: 1.24.0
networking:
  dnsDomain: cluster.local
  serviceSubnet: 10.96.0.0/12
scheduler: {}

```

**Comment by medyagh** [comment]
```
19:23:36 medya
$ ./kubeadm config print join-defaults
apiVersion: kubeadm.k8s.io/v1beta3
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: kube-apiserver:6443
    token: abcdef.0123456789abcdef
    unsafeSkipCAVerification: true
  timeout: 5m0s
  tlsBootstrapToken: abcdef.0123456789abcdef
kind: JoinConfiguration
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  imagePullPolicy: IfNotPresent
  name: medya.c.googlers.com
  taints: null

```

**Comment by medyagh** [comment]
this needs to be added here 

https://github.com/kubernetes/minikube/blob/3f205a0e14f334e34225ee996277ff69006c3097/pkg/minikube/bootstrapper/bsutil/kubeadm.go#L151

**Comment by NikhilSharmaWe** [comment]
@medyagh Could you please elaborate what are we trying to achieve here - 
- What file should be added to https://github.com/medyagh/minikube/blob/25d17c2dde4920c00b4fe6f42aece999ce92cd5c/pkg/minikube/bootstrapper/bsutil/ktmpl/v1beta2.go#L21.
- What you are trying to say by these two configs mentioned in the comments ?

Looking forward to collaborate.
