### ISSUE TITLE
Unable to run minikube start

### ISSUE THREAD

**Issue by leogovan** [kubernetes/minikube#13334]
### What Happened?

I am running an M1 Macbook Pro with MacOS 11.6.1. 

I am trying to run `minikube start driver=docker` command and I am running into the error output attached to this issue. I am quite new to this so not really sure what to do here. I've attempted to run `swapoff -a` and `systemctl enable kubelet.service` but neither command is recognised.

I've tried running `minikube logs --file=logs.txt` but this also fails (see terminal-output.txt attached)

### Attach the log file

[terminal-output.txt](https://github.com/kubernetes/minikube/files/7856686/terminal-output.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
If you previously ran the amd64 version of minikube, you might need to clear your cache before running arm64 version

**Comment by leogovan** [comment]
Thanks @afbjorklund, that was exactly it. Your reference led me to this https://github.com/kubernetes/minikube/issues/12274#issuecomment-1006201978 which completely solved it!
