### ISSUE TITLE
Connection refused when connecting to node port service via domain or ip

### ISSUE THREAD

**Issue by DylanSijanivandi** [kubernetes/minikube#13344]
minikube start --driver=docker --container-runtime=containerd
minikube image load mywebapp:1.0-SNAPSHOT
kubectl create deployment my-deployment --image=mywebapp:1.0-SNAPSHOT
kubectl expose deployment my-deployment --type=NodePort --port=443 --target-port=8443
kubectl port-forward my-deployment-57f4d6c9fb-hcqjl 443:8443

curl https://localhost/utilities/json-test
works.
curl https://[domain name or ip]/utilities/json-test
connection refused.

This isn't a domain or router port-forwarding problem because the above curl works when using standalone docker.
I'm using windows 11 running a virtualbox vm of centos8, centos 8 runs minikube and docker.

**Comment by DylanSijanivandi** [comment]
Making a nat rule to forward https request to the external ip of a load balancer service worked, so I'll close the thread.

**Comment by zarak-shahjee** [comment]
@DylanSijanivandi Can you please explain how did you made it work in detail?
