### ISSUE TITLE
minikube start arm64架构报告无法下载kubelet、kubeadm等

### ISSUE THREAD

**Issue by rico-qian** [kubernetes/minikube#13350]
**重现问题所需的命令**：
minikube start --image-mirror-country='cn' --force

**失败的命令的完整输出**：<details>
😄  minikube v1.24.0 on Centos 7.9.2009 (arm64)
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
✨  Automatically selected the docker driver. Other choices: none, ssh
🛑  The "docker" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
✅  Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=32100MB) ...
❗  This container is having trouble accessing https://registry.cn-hangzhou.aliyuncs.com/google_containers
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.22.3 on Docker 20.10.8 ...

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubelet: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.22.3/bin/linux/arm64/kubelet?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.22.3/bin/linux/arm64/kubelet.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.22.3/bin/linux/arm64/kubelet?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.22.3/bin/linux/arm64/kubelet.sha256 Dst:/root/.minikube/cache/linux/v1.22.3/kubelet.download Pwd: Mode:2 Umask:---------- Detectors:[0x3083e58 0x3083e58 0x3083e58 0x3083e58 0x3083e58 0x3083e58 0x3083e58] Decompressors:map[bz2:0x3083e58 gz:0x3083e58 tar:0x3083e58 tar.bz2:0x3083e58 tar.gz:0x3083e58 tar.xz:0x3083e58 tar.zst:0x3083e58 tbz2:0x3083e58 tgz:0x3083e58 txz:0x3083e58 tzst:0x3083e58 xz:0x3083e58 zip:0x3083e58 zst:0x3083e58] Getters:map[file:0x400188cfd0 http:0x40017014a0 https:0x40017014c0] Dir:false ProgressListener:0x3045b50 Insecure:false Options:[0x142bbc0]}: invalid checksum: Error downloading checksum file: bad response code: 404

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

</details>

**`minikube logs`命令的输出**： <details>
E0114 15:52:25.987531   62545 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: /var/lib/minikube/binaries/v1.22.3/kubectl: command not found
 output: "\n** stderr ** \nsudo: /var/lib/minikube/binaries/v1.22.3/kubectl: command not found\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

</details>

**使用的操作系统版本**：
centos7 aarch64

也尝试过手动在服务器安装kubectl、kubelet、kubeadm，同样出错

**Comment by sharifelgamal** [comment]
The issue here is that the Alibaba mirror doesn't have the arm64 kubelet binary for Kubernetes v1.22.3.  I'm not sure if it just doesn't exist of if we're supplying the wrong endpoint for the mirror. Someone should look into this.

---

这里的问题是阿里巴巴镜像没有 Kubernetes v1.22.3 的 arm64 kubelet 二进制文件。如果我们为镜像提供了错误的端点，我不确定它是否不存在。有人应该调查一下。

**Comment by spowelljr** [comment]
The core minikube team doesn't support the Alibaba mirror, we're hoping to have control over it in the future, but as for now it's maintained at a best effort basis by external contributors.
