### ISSUE TITLE
inatallization error

### ISSUE THREAD

**Issue by Alan-Jino** [kubernetes/minikube#13355]
### What Happened?

 Exiting due to HOST_CONFIG_LOAD: unmarshal: unexpected end of JSON input

### Attach the log file

 - /tmp/minikube_logs_ea560e7c39f4d4d2c62e74a8ec967c82d0891d24_0.log              

### Operating System

Ubuntu

**Comment by Alan-Jino** [comment]
please help

**Comment by klaases** [comment]
Hi @[Alan-Jino](https://github.com/Alan-Jino), although we see a path to the local log file, could you attach the actual log file? We currently cannot see it.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by klaases** [comment]
Hi @[Alan-Jino](https://github.com/Alan-Jino) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
