### ISSUE TITLE
Please embed docker cli

### ISSUE THREAD

**Issue by cornfeedhobo** [kubernetes/minikube#13356]
### What Happened?

When starting a cluster with a non-docker driver, docker is running inside the created virtual machine. It would be nice if a docker cli was downloaded to match the version, similar to what is currently done with `kubectl`.

### Attach the log file

n/a

### Operating System

Ubuntu

### Driver

KVM2

**Comment by cornfeedhobo** [comment]
maybe nerdctl could be embedded instead if this is a licensing issue?

**Comment by afbjorklund** [comment]
We talked about it before, but it was decided that the user "knows" how to install the Docker client:

* #6402

Instead the parts of a docker CLI that minikube is using (image) was embeeded into `minikube image`.

Support for `nerdctl` is being added to a future release, currently there is only `ctr` and `buildctl`.

----

Since Kubernetes is moving towards towards the CRI standard, there is no use for the legacy CLI...

But minikube _is_ providing docker-env for docker, podman-env for crio and ssh (no env) for containerd.

User is supposed to use package management to install the clients, and minikube will **not** be doing that.

It is a problem, but one that is scoped out. It is supposed to be enough with using `kubectl` and `crictl`.

**Comment by afbjorklund** [comment]
It would be great if you could detail the requirements that are **not** being covered by `kubectl` and `image` ?

Running with `--no-kubernetes` comes to mind, but that is not the primary use case of minikube I suppose...

Or if there is some better documentation available upstream, that could be added to the runtime documentation ?

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

The docs are mostly focused on loading and building: https://minikube.sigs.k8s.io/docs/handbook/pushing/

Other use cases might be possible, but there are no docs on how to talk directly to the container runtime.

**Comment by afbjorklund** [comment]
Note that you can use ssh:

`minikube ssh -- docker`

`minikube ssh -- sudo podman`

`minikube ssh -- sudo ctr`
`minikube ssh -- sudo buildctl`
`minikube ssh -- sudo nerdctl` (soon: #13252)

And for all of them, there is CRI:

`minikube ssh -- sudo crictl`

**Comment by afbjorklund** [comment]
> When starting a cluster with a non-docker driver, docker is running inside the created virtual machine.

All clusters will have a container runtime, which might not be docker. For none/ssh, it runs directly on host.

The container runtime used for the driver doesn't interact with the container runtime used for the host(s).
It is somewhat confusing, especially when running docker-in-docker. (as in: "which docker is which ?")

Tried to expand upon the topic in the Kubecon EU 2021 talk: https://sched.co/iE7w. For better and worse.

**Comment by cornfeedhobo** [comment]
> ```minikube ssh -- docker```

This might be a viable solution

> It would be great if you could detail the requirements that are not being covered

The use case is the host does not have docker installed at all wants to use minikube's docker directly.

**Comment by cornfeedhobo** [comment]
@afbjorklund I'm going to close this since #9524 documents this topic will, and you've given some great comments here too. I'll also explore `minikube build`

**Comment by afbjorklund** [comment]
Was just trying to get some input into why it (docker) should be kept, since upstream is desperately trying to get rid of it.

**Comment by cornfeedhobo** [comment]
Oh. It's because it's staying power will be here for a while longer. A lot of development workflows assume it. I'm sure this will finally flip in a few years but I'm working with the expectations I see right now.

**Comment by afbjorklund** [comment]
This was for Kubernetes 1.24, which is just a few months away...

Thanks for confirming my suspicions that it might be a bit premature

**Comment by cornfeedhobo** [comment]
For anyone following this, I decided to move to Rancher Desktop. That team seems more focused on end-user experience and development lifecycle. Thanks everyone.
