### ISSUE TITLE
unable to start minikube

### ISSUE THREAD

**Issue by shuklagauravjn** [kubernetes/minikube#13357]
### What Happened?

 Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /mnt/c/dev/kubernetes: mkdir /mnt: read-only file system

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/7876490/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
I think minikube gets a bit confused, when the standard location is removed from KUBECONFIG.

```
I0116 11:41:32.606949   18483 out.go:176]     ▪ KUBECONFIG=/mnt/c/dev/kubernetes/rnd-admin.conf:/mnt/c/Users/rahul/.kube/config
```

So the first one should be writable, so that minikube can update the cluster-context in there.

**Comment by klaases** [comment]
Hi @[shuklagauravjn](https://github.com/shuklagauravjn), did you have a chance to review @[afbjorklund](https://github.com/afbjorklund)'s comment?

**Comment by klaases** [comment]
Hi @shuklagauravjn  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
