### ISSUE TITLE
Document container runtimes available in minikube

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#13358]
We should add some more detailed documentation, about the available container runtimes.

In alphabetical order:

* "containerd"

  * server: `containerd` + `buildkitd`
  * client: `nerdctl` (+ `ctr` + `buildctl`)

* "cri-o"

  * server: `crio` + `podman`
  * client: `podman`

* "docker"

  * server: `dockerd`
  * client: `docker`

We need some more information about tools and envionment, than what upstream provides:

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

Some information is available under https://minikube.sigs.k8s.io/docs/handbook/pushing/

* nerdctl env: **note:** nerdctl doesn't have any remote API yet, only a CLI

* podman env: https://minikube.sigs.k8s.io/docs/commands/podman-env/

* docker env: https://minikube.sigs.k8s.io/docs/commands/docker-env/

Spelling should be the same as what Kubernetes uses, when listing the runtime for a node:

```
minikube kubectl -- get nodes -o wide
```

Don't need so much information about `crictl`, that can be left for upstream to document.

https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/

**Comment by afbjorklund** [comment]
For containerd, see:
* #13252

**Comment by sftim** [comment]
I'm not quite clear on what's meant by the “client” part of the issue description.

Let's say I run Minikube with qemu + kvm VM driver. I don't need to know about `docker`, `nerdctl` or `podman` to do that.

I recommend mentioning some additional context for this issue so it's clear what kind of pages this is relevant to and under what circumstances the user's choice of client becomes relevant.

**Comment by afbjorklund** [comment]
The "client" refers to the program that runs on host, such as `kubectl`.

**Comment by afbjorklund** [comment]
Also, there is even a new feature where people use minikube without Kubernetes.

Previously they could use "Docker Machine", but that project has been deprecated.

**Comment by afbjorklund** [comment]
The **preferred** driver for minikube even runs the cluster in a container inside a virtual machine:

* #13434

It is possible that the host no longer runs Docker Desktop, and the cluster no longer runs Docker Engine.

The subscription changes and interface changes are only _distantly_ related to this, but accelerates usage.

* https://www.docker.com/blog/updating-product-subscriptions/

* https://kubernetes.io/blog/2020/12/02/dockershim-faq/

**Comment by afbjorklund** [comment]
> Let's say I run Minikube with qemu + kvm VM driver. I don't need to know about `docker`, `nerdctl` or `podman` to do that.

You can run `minikube start`, and then `minikube kubectl` and `minikube dashboard` without learning the "internals".

This was more advanced documentation, for users that want to talk directly to the container runtime (outside of the CRI)

Either because there are things missing in the specification, or because they are doing something outside of Kubernetes ?

But there should not be any _need_ to do it, hopefully `minikube image build` covers that - until `kubectl build` is standard.
