### ISSUE TITLE
Disable native folder sharing for drivers in favor of `minikube mount`

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1336]
With the addition of the `minikube mount` command we should now be able to remove the native folder sharing options that were driver specific.  The roadmap for this is the do it in the v0.19.0 release.

**Comment by r2d4** [comment]
We should make sure to not break clients who are assuming that the home folder is mounted by default.

**Comment by aaron-prindle** [comment]
We have a flag to start the mount daemon for `minikube start` and a flag to disable the vbox mount as well.  I think that we should support NFS based mounts for OSX and linux before moving forward as mount speed might be an issue.
