### ISSUE TITLE
Not able start minikube 

### ISSUE THREAD

**Issue by rsurendraidexcel** [kubernetes/minikube#13369]
### What Happened?

Hi any when i start 
minikube start   i am not able start the service  i got error issue  bellow log file i attached. any body have idia about this issue 
better one command 
minikube doctor -> have option  all dependency software are checked if it is not available auto install, to make soure minikube ready to start.   some kind of commandline interface provides . it would be better for minikube user. or developer 

[logs.txt](https://github.com/kubernetes/minikube/files/7885546/logs.txt)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/7885577/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @rsurendraidexcel, thanks for reporting your issue with minikube!

You seem to be getting some cert issues:
```
[certs] certificate apiserver-kubelet-client not signed by CA certificate ca: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "minikubeCA")
```

Try running `minikube delete --all --purge` and then try starting minikube again and see if that resolves your issue.

**Comment by rsurendraidexcel** [comment]
Hi @spowelljr  thank you so much . quick support help  you are greate.

$ minikube delete --all --purge    

this command  is realy work ,  awsome  ,Now  my  system  is up and runing kuernete s. thank you  for help and supports

**Comment by spowelljr** [comment]
Glad it worked!
