### ISSUE TITLE
minikube : Requested cpu count 2 

### ISSUE THREAD

**Issue by chiterdidine** [kubernetes/minikube#13372]
**Étapes pour reproduire le problème:** 
user@ubuntu:~$ sudo minikube start --driver docker --nodes 3

*Sortie complète de la commande `minikube logs`:**
<details>
😄  minikube v1.24.0 on Ubuntu 20.04
✨  Using the docker driver based on user configuration

⛔  Exiting due to RSRC_INSUFFICIENT_CORES: Requested cpu count 2 is greater than the available cpus of 1

</details>

**Sortie complète de la commande échouée:**
<details>

</details>

**Comment by medyagh** [comment]
@chiterdidine 
```
⛔ Exiting due to RSRC_INSUFFICIENT_CORES: Requested cpu count 2 is greater than the available cpus of 1
```

u need 2 CPUs on your machine, but your machine has only 1 CPU
