### ISSUE TITLE
minikube will not start -- hangs after "About to run SSH command"

### ISSUE THREAD

**Issue by kwiechmann** [kubernetes/minikube#13374]
### What Happened?

> hyperkit -v       
hyperkit: v0.20210107-14-g09fe92
Homepage: https://github.com/docker/hyperkit
License: BSD

> minikube version
minikube version: v1.24.0
commit: 76b94fb3c4e8ac5062daf70d60cf03ddcc0a741b

- MacOS Big Sur 11.6.2
- Cisco AnyConnect Version 4.10.01075

When debugging levels are more verbose, the last step seen is **About to run SSH command** before flip-flopping between. The IPs are not pingable, shareable, nor tracerouteable once the vpnkit is enabled:

- main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.13:22: connect: operation timed out
- main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.14:22: connect: operation timed out

> minikube start --hyperkit-vpnkit-sock=/tmp/vpnkit.eth.sock --driver=hyperkit 
😄  minikube v1.24.0 on Darwin 11.6.2
    ▪ MINIKUBE_ACTIVE_DOCKERD=minikube
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running hyperkit "minikube" VM ...

> minikube start --hyperkit-vpnkit-sock=/tmp/vpnkit.eth.sock --driver=hyperkit --v=2 --alsologtostderr
I0118 09:51:57.551964   14373 out.go:297] Setting OutFile to fd 1 ...
I0118 09:51:57.552382   14373 out.go:349] isatty.IsTerminal(1) = true
I0118 09:51:57.552393   14373 out.go:310] Setting ErrFile to fd 2...
I0118 09:51:57.552404   14373 out.go:349] isatty.IsTerminal(2) = true
I0118 09:51:57.552530   14373 root.go:313] Updating PATH: /Users/kwiechma/.minikube/bin
I0118 09:51:57.552566   14373 oci.go:561] shell is pointing to dockerd inside minikube. will unset to use host
I0118 09:51:57.553157   14373 out.go:304] Setting JSON to false
I0118 09:51:57.612263   14373 start.go:112] hostinfo: {"hostname":"WITSC02GD336MD6","uptime":6840,"bootTime":1642510677,"procs":537,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"11.6.2","kernelVersion":"20.6.0","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"9e47f461-37ce-523d-baa1-d14cb9576b4d"}
W0118 09:51:57.612397   14373 start.go:120] gopshost.Virtualization returned error: not implemented yet
I0118 09:51:57.631650   14373 out.go:176] 😄  minikube v1.24.0 on Darwin 11.6.2
😄  minikube v1.24.0 on Darwin 11.6.2
I0118 09:51:57.631792   14373 notify.go:174] Checking for updates...
I0118 09:51:57.651235   14373 out.go:176]     ▪ MINIKUBE_ACTIVE_DOCKERD=minikube
    ▪ MINIKUBE_ACTIVE_DOCKERD=minikube
I0118 09:51:57.652894   14373 config.go:176] Loaded profile config "minikube": Driver=hyperkit, ContainerRuntime=docker, KubernetesVersion=v1.22.3
I0118 09:51:57.653529   14373 main.go:130] libmachine: Found binary path at /Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit
I0118 09:51:57.653587   14373 main.go:130] libmachine: Launching plugin server for driver hyperkit
I0118 09:51:57.663513   14373 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:52495
I0118 09:51:57.664033   14373 main.go:130] libmachine: () Calling .GetVersion
I0118 09:51:57.664488   14373 main.go:130] libmachine: Using API Version  1
I0118 09:51:57.664510   14373 main.go:130] libmachine: () Calling .SetConfigRaw
I0118 09:51:57.664739   14373 main.go:130] libmachine: () Calling .GetMachineName
I0118 09:51:57.664862   14373 main.go:130] libmachine: (minikube) Calling .DriverName
I0118 09:51:57.664995   14373 driver.go:343] Setting default libvirt URI to qemu:///system
I0118 09:51:57.665460   14373 main.go:130] libmachine: Found binary path at /Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit
I0118 09:51:57.665488   14373 main.go:130] libmachine: Launching plugin server for driver hyperkit
I0118 09:51:57.674977   14373 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:52497
I0118 09:51:57.675460   14373 main.go:130] libmachine: () Calling .GetVersion
I0118 09:51:57.675840   14373 main.go:130] libmachine: Using API Version  1
I0118 09:51:57.675864   14373 main.go:130] libmachine: () Calling .SetConfigRaw
I0118 09:51:57.676139   14373 main.go:130] libmachine: () Calling .GetMachineName
I0118 09:51:57.676266   14373 main.go:130] libmachine: (minikube) Calling .DriverName
I0118 09:51:57.702422   14373 out.go:176] ✨  Using the hyperkit driver based on existing profile
✨  Using the hyperkit driver based on existing profile
I0118 09:51:57.702511   14373 start.go:280] selected driver: hyperkit
I0118 09:51:57.702524   14373 start.go:762] validating driver "hyperkit" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.24.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.28@sha256:4780f1897569d2bf77aafb3d133a08d42b4fe61127f06fcfc90c2c5d902d893c Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:hyperkit HyperkitVpnKitSock:/tmp/vpnkit.eth.sock HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.22.3 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/Users:/minikube-host}
I0118 09:51:57.702755   14373 start.go:773] status for hyperkit: {Installed:true Healthy:true Running:true NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0118 09:51:57.703094   14373 install.go:52] acquiring lock: {Name:mk4023283b30b374c3f04c8805d539e68824c0b8 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0118 09:51:57.703506   14373 install.go:117] Validating docker-machine-driver-hyperkit, PATH=/Users/kwiechma/.minikube/bin:/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin:/usr/local/sbin:/Users/kwiechma/.nvm/versions/node/v17.1.0/bin:/Users/kwiechma/.platformsh/bin:/Users/kwiechma/Library/Python/2.7/bin:/usr/local/bin:/Users/kwiechma/.yarn/bin:/Users/kwiechma/.config/yarn/global/node_modules/.bin:/Users/kwiechma/.composer/vendor/bin:/usr/local/opt/git/bin:/Library/Frameworks/Python.framework/Versions/3.9/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/Users/kwiechma/.platformsh/bin:/Users/kwiechma/bin:/usr/local/opt/node@16/bin:/usr/local/opt/php@7.2/bin:/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home/bin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/Apple/usr/bin
I0118 09:51:57.733749   14373 install.go:137] /Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit version is 1.24.0
I0118 09:51:57.739503   14373 install.go:79] stdout: /Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit
I0118 09:51:57.739531   14373 install.go:81] /Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit looks good
I0118 09:51:57.739753   14373 cni.go:93] Creating CNI manager for ""
I0118 09:51:57.739766   14373 cni.go:167] CNI unnecessary in this configuration, recommending no CNI
I0118 09:51:57.739778   14373 start_flags.go:282] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.24.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.28@sha256:4780f1897569d2bf77aafb3d133a08d42b4fe61127f06fcfc90c2c5d902d893c Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:hyperkit HyperkitVpnKitSock:/tmp/vpnkit.eth.sock HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.22.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.22.3 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/Users:/minikube-host}
I0118 09:51:57.739912   14373 iso.go:123] acquiring lock: {Name:mk49e48777b32dadb8dff58be53f2e9eb00620ea Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0118 09:51:57.777264   14373 out.go:176] 👍  Starting control plane node minikube in cluster minikube
👍  Starting control plane node minikube in cluster minikube
I0118 09:51:57.777320   14373 preload.go:132] Checking if preload exists for k8s version v1.22.3 and runtime docker
I0118 09:51:57.777391   14373 preload.go:148] Found local preload: /Users/kwiechma/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v13-v1.22.3-docker-overlay2-amd64.tar.lz4
I0118 09:51:57.777419   14373 cache.go:57] Caching tarball of preloaded images
I0118 09:51:57.777735   14373 preload.go:174] Found /Users/kwiechma/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v13-v1.22.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0118 09:51:57.777759   14373 cache.go:60] Finished verifying existence of preloaded tar for  v1.22.3 on docker
I0118 09:51:57.777894   14373 profile.go:147] Saving config to /Users/kwiechma/.minikube/profiles/minikube/config.json ...
I0118 09:51:57.779404   14373 cache.go:206] Successfully downloaded all kic artifacts
I0118 09:51:57.779444   14373 start.go:313] acquiring machines lock for minikube: {Name:mk64bb858c92c63017488632b3b69b53bc2cc97c Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0118 09:51:57.779639   14373 start.go:317] acquired machines lock for "minikube" in 178.006µs
I0118 09:51:57.779678   14373 start.go:93] Skipping create...Using existing machine configuration
I0118 09:51:57.779688   14373 fix.go:55] fixHost starting: 
I0118 09:51:57.780272   14373 main.go:130] libmachine: Found binary path at /Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit
I0118 09:51:57.780308   14373 main.go:130] libmachine: Launching plugin server for driver hyperkit
I0118 09:51:57.791207   14373 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:52500
I0118 09:51:57.791707   14373 main.go:130] libmachine: () Calling .GetVersion
I0118 09:51:57.792141   14373 main.go:130] libmachine: Using API Version  1
I0118 09:51:57.792160   14373 main.go:130] libmachine: () Calling .SetConfigRaw
I0118 09:51:57.792425   14373 main.go:130] libmachine: () Calling .GetMachineName
I0118 09:51:57.792565   14373 main.go:130] libmachine: (minikube) Calling .DriverName
I0118 09:51:57.792674   14373 main.go:130] libmachine: (minikube) Calling .GetState
I0118 09:51:57.792777   14373 main.go:130] libmachine: (minikube) DBG | exe=/Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0118 09:51:57.792929   14373 main.go:130] libmachine: (minikube) DBG | hyperkit pid from json: 14336
I0118 09:51:57.794189   14373 main.go:130] libmachine: (minikube) DBG | hyperkit pid 14336 missing from process table
I0118 09:51:57.794233   14373 fix.go:108] recreateIfNeeded on minikube: state=Stopped err=<nil>
I0118 09:51:57.794263   14373 main.go:130] libmachine: (minikube) Calling .DriverName
W0118 09:51:57.794357   14373 fix.go:134] unexpected machine state, will restart: <nil>
I0118 09:51:57.813195   14373 out.go:176] 🔄  Restarting existing hyperkit VM for "minikube" ...
🔄  Restarting existing hyperkit VM for "minikube" ...
I0118 09:51:57.813223   14373 main.go:130] libmachine: (minikube) Calling .Start
I0118 09:51:57.813469   14373 main.go:130] libmachine: (minikube) DBG | exe=/Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0118 09:51:57.813505   14373 main.go:130] libmachine: (minikube) minikube might have been shutdown in an unclean way, the hyperkit pid file still exists: /Users/kwiechma/.minikube/machines/minikube/hyperkit.pid
I0118 09:51:57.814951   14373 main.go:130] libmachine: (minikube) DBG | hyperkit pid 14336 missing from process table
I0118 09:51:57.814969   14373 main.go:130] libmachine: (minikube) DBG | pid 14336 is in state "Stopped"
I0118 09:51:57.814988   14373 main.go:130] libmachine: (minikube) DBG | Removing stale pid file /Users/kwiechma/.minikube/machines/minikube/hyperkit.pid...
I0118 09:51:57.832656   14373 main.go:130] libmachine: (minikube) DBG | Using UUID 1c4e3eb4-786e-11ec-9837-acde48001122
I0118 09:51:58.061327   14373 main.go:130] libmachine: (minikube) DBG | Generated MAC 42:d7:b0:8a:2b:c9
I0118 09:51:58.061426   14373 main.go:130] libmachine: (minikube) DBG | Starting with cmdline: loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
I0118 09:51:58.062139   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 DEBUG: hyperkit: Start &hyperkit.HyperKit{HyperKit:"/usr/local/bin/hyperkit", Argv0:"", StateDir:"/Users/kwiechma/.minikube/machines/minikube", VPNKitSock:"/tmp/vpnkit.eth.sock", VPNKitUUID:"", VPNKitPreferredIPv4:"", UUID:"1c4e3eb4-786e-11ec-9837-acde48001122", Disks:[]hyperkit.Disk{(*hyperkit.RawDisk)(0xc0004e0990)}, ISOImages:[]string{"/Users/kwiechma/.minikube/machines/minikube/boot2docker.iso"}, VSock:false, VSockDir:"", VSockPorts:[]int(nil), VSockGuestCID:3, VMNet:true, Sockets9P:[]hyperkit.Socket9P(nil), Kernel:"/Users/kwiechma/.minikube/machines/minikube/bzimage", Initrd:"/Users/kwiechma/.minikube/machines/minikube/initrd", Bootrom:"", CPUs:2, Memory:6000, Console:1, Serials:[]hyperkit.Serial(nil), Pid:0, Arguments:[]string(nil), CmdLine:"", process:(*os.Process)(nil)}
I0118 09:51:58.062196   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 DEBUG: hyperkit: check &hyperkit.HyperKit{HyperKit:"/usr/local/bin/hyperkit", Argv0:"", StateDir:"/Users/kwiechma/.minikube/machines/minikube", VPNKitSock:"/tmp/vpnkit.eth.sock", VPNKitUUID:"", VPNKitPreferredIPv4:"", UUID:"1c4e3eb4-786e-11ec-9837-acde48001122", Disks:[]hyperkit.Disk{(*hyperkit.RawDisk)(0xc0004e0990)}, ISOImages:[]string{"/Users/kwiechma/.minikube/machines/minikube/boot2docker.iso"}, VSock:false, VSockDir:"", VSockPorts:[]int(nil), VSockGuestCID:3, VMNet:true, Sockets9P:[]hyperkit.Socket9P(nil), Kernel:"/Users/kwiechma/.minikube/machines/minikube/bzimage", Initrd:"/Users/kwiechma/.minikube/machines/minikube/initrd", Bootrom:"", CPUs:2, Memory:6000, Console:1, Serials:[]hyperkit.Serial(nil), Pid:0, Arguments:[]string(nil), CmdLine:"", process:(*os.Process)(nil)}
I0118 09:51:58.062312   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 DEBUG: hyperkit: Arguments: []string{"-A", "-u", "-F", "/Users/kwiechma/.minikube/machines/minikube/hyperkit.pid", "-c", "2", "-m", "6000M", "-s", "0:0,hostbridge", "-s", "31,lpc", "-s", "1:0,virtio-vpnkit,path=/tmp/vpnkit.eth.sock", "-s", "2:0,virtio-net", "-U", "1c4e3eb4-786e-11ec-9837-acde48001122", "-s", "3:0,virtio-blk,/Users/kwiechma/.minikube/machines/minikube/minikube.rawdisk", "-s", "4,ahci-cd,/Users/kwiechma/.minikube/machines/minikube/boot2docker.iso", "-s", "5,virtio-rnd", "-l", "com1,autopty=/Users/kwiechma/.minikube/machines/minikube/tty,log=/Users/kwiechma/.minikube/machines/minikube/console-ring", "-f", "kexec,/Users/kwiechma/.minikube/machines/minikube/bzimage,/Users/kwiechma/.minikube/machines/minikube/initrd,earlyprintk=serial loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube"}
I0118 09:51:58.062410   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 DEBUG: hyperkit: CmdLine: "/usr/local/bin/hyperkit -A -u -F /Users/kwiechma/.minikube/machines/minikube/hyperkit.pid -c 2 -m 6000M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-vpnkit,path=/tmp/vpnkit.eth.sock -s 2:0,virtio-net -U 1c4e3eb4-786e-11ec-9837-acde48001122 -s 3:0,virtio-blk,/Users/kwiechma/.minikube/machines/minikube/minikube.rawdisk -s 4,ahci-cd,/Users/kwiechma/.minikube/machines/minikube/boot2docker.iso -s 5,virtio-rnd -l com1,autopty=/Users/kwiechma/.minikube/machines/minikube/tty,log=/Users/kwiechma/.minikube/machines/minikube/console-ring -f kexec,/Users/kwiechma/.minikube/machines/minikube/bzimage,/Users/kwiechma/.minikube/machines/minikube/initrd,earlyprintk=serial loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube"
I0118 09:51:58.062432   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 DEBUG: hyperkit: Redirecting stdout/stderr to logger
I0118 09:51:58.062819   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 DEBUG: hyperkit: Starting &exec.Cmd{Path:"/usr/local/bin/hyperkit", Args:[]string{}, Dir:"", Stdin:io.Reader(nil), Stdout:(*os.File)(0xc00020c020), Stderr:(*os.File)(0xc00020c030), ExtraFiles:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(nil), Process:(*os.Process)(nil), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File(nil), closeAfterStart:[]io.Closer{(*os.File)(0xc00020c020), (*os.File)(0xc00020c030)}, closeAfterWait:[]io.Closer{(*os.File)(0xc00020c018), (*os.File)(0xc00020c028)}, goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)}
I0118 09:51:58.064567   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 DEBUG: hyperkit: Pid is 14384
I0118 09:51:58.065211   14373 main.go:130] libmachine: (minikube) DBG | Attempt 0
I0118 09:51:58.065229   14373 main.go:130] libmachine: (minikube) DBG | exe=/Users/kwiechma/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0118 09:51:58.065427   14373 main.go:130] libmachine: (minikube) DBG | hyperkit pid from json: 14384
I0118 09:51:58.065627   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 DEBUG: hyperkit: Waiting for &exec.Cmd{Path:"/usr/local/bin/hyperkit", Args:[]string{}, Dir:"", Stdin:io.Reader(nil), Stdout:(*os.File)(0xc00020c020), Stderr:(*os.File)(0xc00020c030), ExtraFiles:[]*os.File(nil), SysProcAttr:(*syscall.SysProcAttr)(nil), Process:(*os.Process)(0xc0000ca1e0), ProcessState:(*os.ProcessState)(nil), ctx:context.Context(nil), lookPathErr:error(nil), finished:false, childFiles:[]*os.File{(*os.File)(0xc00020c038), (*os.File)(0xc00020c020), (*os.File)(0xc00020c030)}, closeAfterStart:[]io.Closer{(*os.File)(0xc00020c020), (*os.File)(0xc00020c030), (*os.File)(0xc00020c038)}, closeAfterWait:[]io.Closer{(*os.File)(0xc00020c018), (*os.File)(0xc00020c028)}, goroutine:[]func() error(nil), errch:(chan error)(nil), waitDone:(chan struct {})(nil)}
I0118 09:51:58.066864   14373 main.go:130] libmachine: (minikube) DBG | Searching for 42:d7:b0:8a:2b:c9 in /var/db/dhcpd_leases ...
I0118 09:51:58.067088   14373 main.go:130] libmachine: (minikube) DBG | Found 15 entries in /var/db/dhcpd_leases!
I0118 09:51:58.067129   14373 main.go:130] libmachine: (minikube) DBG | dhcp entry: {Name:minikube IPAddress:192.168.65.16 HWAddress:42:d7:b0:8a:2b:c9 ID:1,42:d7:b0:8a:2b:c9 Lease:0x61e82576}
I0118 09:51:58.067155   14373 main.go:130] libmachine: (minikube) DBG | Found match: 42:d7:b0:8a:2b:c9
I0118 09:51:58.067168   14373 main.go:130] libmachine: (minikube) DBG | IP: 192.168.65.16
I0118 09:51:58.067176   14373 main.go:130] libmachine: (minikube) Calling .GetConfigRaw
I0118 09:51:58.068846   14373 main.go:130] libmachine: (minikube) Calling .GetIP
I0118 09:51:58.069067   14373 profile.go:147] Saving config to /Users/kwiechma/.minikube/profiles/minikube/config.json ...
I0118 09:51:58.070213   14373 main.go:130] libmachine: (minikube) Calling .DriverName
I0118 09:51:58.070374   14373 machine.go:88] provisioning docker machine ...
I0118 09:51:58.070387   14373 main.go:130] libmachine: (minikube) Calling .DriverName
I0118 09:51:58.070508   14373 main.go:130] libmachine: (minikube) Calling .GetMachineName
I0118 09:51:58.070644   14373 buildroot.go:166] provisioning hostname "minikube"
I0118 09:51:58.070660   14373 main.go:130] libmachine: (minikube) Calling .GetMachineName
I0118 09:51:58.070799   14373 main.go:130] libmachine: (minikube) Calling .GetSSHHostname
I0118 09:51:58.070914   14373 main.go:130] libmachine: (minikube) Calling .GetSSHPort
I0118 09:51:58.071033   14373 main.go:130] libmachine: (minikube) Calling .GetSSHKeyPath
I0118 09:51:58.071129   14373 main.go:130] libmachine: (minikube) Calling .GetSSHKeyPath
I0118 09:51:58.071240   14373 main.go:130] libmachine: (minikube) Calling .GetSSHUsername
I0118 09:51:58.071497   14373 main.go:130] libmachine: Using SSH client type: native
I0118 09:51:58.071774   14373 main.go:130] libmachine: &{{{<nil> 0 [] [] []} docker [0x43a0ca0] 0x43a3d80 <nil>  [] 0s} 192.168.65.16 22 <nil> <nil>}
I0118 09:51:58.071789   14373 main.go:130] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0118 09:51:58.084293   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: virtio-net-vpnkit: magic=VMN3T version=22 commit=0123456789012345678901234567890123456789???
I0118 09:51:58.194284   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: /Users/kwiechma/.minikube/machines/minikube/boot2docker.iso: fcntl(F_PUNCHHOLE) Operation not permitted: block device will not support TRIM/DISCARD
I0118 09:51:58.195639   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: vmx_set_ctlreg: cap_field: 4 bit: 12 unspecified don't care: bit is 0
I0118 09:51:58.195655   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: vmx_set_ctlreg: cap_field: 4 bit: 20 unspecified don't care: bit is 0
I0118 09:51:58.195668   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: vmx_set_ctlreg: cap_field: 3 bit: 13 unspecified don't care: bit is 0
I0118 09:51:58.741100   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: rdmsr to register 0x140 on vcpu 0
I0118 09:51:58.851320   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: vmx_set_ctlreg: cap_field: 4 bit: 12 unspecified don't care: bit is 0
I0118 09:51:58.851408   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: vmx_set_ctlreg: cap_field: 4 bit: 20 unspecified don't care: bit is 0
I0118 09:51:58.851442   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: vmx_set_ctlreg: cap_field: 3 bit: 13 unspecified don't care: bit is 0
I0118 09:51:58.852023   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:51:58 INFO : hyperkit: stderr: rdmsr to register 0x140 on vcpu 1
I0118 09:52:02.532186   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:52:02 INFO : hyperkit: stderr: rdmsr to register 0x64e on vcpu 1
I0118 09:52:02.537979   14373 main.go:130] libmachine: (minikube) DBG | 2022/01/18 09:52:02 INFO : hyperkit: stderr: rdmsr to register 0x34 on vcpu 1
I0118 09:54:44.461711   14373 main.go:130] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 10.0.0.6:52503->192.168.65.16:22: read: connection reset by peer
I0118 09:56:04.932777   14373 main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.16:22: connect: operation timed out
I0118 09:57:24.846300   14373 main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.16:22: connect: operation timed out
I0118 09:58:44.599023   14373 main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.16:22: connect: operation timed out
I0118 10:00:04.503127   14373 main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.16:22: connect: operation timed out
I0118 10:01:24.403045   14373 main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.16:22: connect: operation timed out
I0118 10:02:43.808593   14373 main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.16:22: connect: operation timed out
I0118 10:04:03.366871   14373 main.go:130] libmachine: Error dialing TCP: dial tcp 192.168.65.16:22: connect: operation timed out

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8383138/log.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by kwiechmann** [comment]
Will add the "minikube start ..." is behaving the same when running Docker Desktop for Macintosh 3.6.0 is used. Both would be using HyperKit under the covers.

**Comment by spowelljr** [comment]
Hi @kwiechmann, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by Zaba107** [comment]
Same issue on mac docker 4.12.0 and minikube

**Comment by svinther** [comment]
Same issue on gitlab CI shared runners, here is my .gitlab-ci.yml

```yaml
image: docker:stable
variables:
  KUBECTL: v1.17.0
services:
  - docker:dind
stages:
  - test
test:
  stage: test
  script:
    - apk add -U wget libc6-compat
    - wget -O ./minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
    - chmod +x ./minikube
    - wget -O ./kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL}/bin/linux/amd64/kubectl
    - chmod +x ./kubectl
    - ./minikube start --extra-config=kubeadm.ignore-preflight-errors=NumCPU --force --cpus=1
    - ./kubectl get nodes -o wide
    - ./kubectl get pods --all-namespaces -o wide
    - ./kubectl get services --all-namespaces -o wide
```

**Comment by pluveto** [comment]
same
