### ISSUE TITLE
minikube emojis not showing up

### ISSUE THREAD

**Issue by ahmedas1980** [kubernetes/minikube#13375]
### What Happened?

![image](https://user-images.githubusercontent.com/96700665/149990378-814af9b3-74df-40d5-a290-68ae69b4023f.png)

### Attach the log file

q

**Comment by afbjorklund** [comment]
Probably missing a font ?

**Comment by ahmedas1980** [comment]
thanks

**Comment by spowelljr** [comment]
Hi @ahmedas1980, did this resolve your issue? Can I close this issue? Thanks!

**Comment by Neandril** [comment]
Hi.
I have the same issue after installing noto color emoji.
Any advice ?

**Comment by afbjorklund** [comment]
Try uninstalling and installing the font, to make sure the cache is updated

**Comment by klaases** [comment]
> Try uninstalling and installing the font, to make sure the cache is updated

Hi @ahmedas1980, did this help solve the issue?

**Comment by klaases** [comment]
Hi @ahmedas1980  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
