### ISSUE TITLE
My Minikube dashboard doesn't work

### ISSUE THREAD

**Issue by Tchokomeni** [kubernetes/minikube#13398]
### What Happened?

Fermeture en raison de HOST_KUBECTL_PROXY : proxy start: fork/exec /usr/local/bin/kubectl: exec format error

### Attach the log file

Log file created at: 2022/01/19 16:55:38
Running on machine: MacBook-Pro-de-TCHOKOMENI
Binary: Built with gc go1.17.2 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0119 16:55:38.019783   17155 out.go:297] Setting OutFile to fd 1 ...
I0119 16:55:38.020067   17155 out.go:349] isatty.IsTerminal(1) = true
I0119 16:55:38.020070   17155 out.go:310] Setting ErrFile to fd 2...
I0119 16:55:38.020074   17155 out.go:349] isatty.IsTerminal(2) = true
I0119 16:55:38.020217   17155 root.go:313] Updating PATH: /Users/christophe/.minikube/bin
W0119 16:55:38.020317   17155 root.go:291] Error reading config file at /Users/christophe/.minikube/config/config.json: open /Users/christophe/.minikube/config/config.json: no such file or directory
I0119 16:55:38.021044   17155 mustload.go:65] Loading cluster: minikube
I0119 16:55:38.022920   17155 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.22.3
I0119 16:55:38.023942   17155 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
I0119 16:55:38.389838   17155 host.go:66] Checking if "minikube" exists ...
I0119 16:55:38.390258   17155 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0119 16:55:38.579726   17155 api_server.go:165] Checking apiserver status ...
I0119 16:55:38.580493   17155 ssh_runner.go:152] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0119 16:55:38.580597   17155 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0119 16:55:38.784848   17155 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:57397 SSHKeyPath:/Users/christophe/.minikube/machines/minikube/id_rsa Username:docker}
I0119 16:55:38.894236   17155 ssh_runner.go:152] Run: sudo egrep ^[0-9]+:freezer: /proc/1601/cgroup
W0119 16:55:38.912019   17155 api_server.go:176] unable to find freezer cgroup: sudo egrep ^[0-9]+:freezer: /proc/1601/cgroup: Process exited with status 1
stdout:

stderr:
I0119 16:55:38.912046   17155 api_server.go:240] Checking apiserver healthz at https://127.0.0.1:57396/healthz ...
I0119 16:55:38.922046   17155 api_server.go:266] https://127.0.0.1:57396/healthz returned 200:
ok
W0119 16:55:38.922141   17155 out.go:241] 🔌  Activation du tableau de bord...
I0119 16:55:38.922437   17155 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.22.3
I0119 16:55:38.922449   17155 addons.go:65] Setting dashboard=true in profile "minikube"
I0119 16:55:38.922456   17155 addons.go:153] Setting addon dashboard=true in "minikube"
I0119 16:55:38.922480   17155 host.go:66] Checking if "minikube" exists ...
I0119 16:55:38.922815   17155 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
I0119 16:55:39.135306   17155 out.go:176]     ▪ Utilisation de l'image kubernetesui/dashboard:v2.3.1
I0119 16:55:39.155267   17155 out.go:176]     ▪ Utilisation de l'image kubernetesui/metrics-scraper:v1.0.7
I0119 16:55:39.155408   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-ns.yaml
I0119 16:55:39.155421   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-ns.yaml (759 bytes)
I0119 16:55:39.155607   17155 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0119 16:55:39.373875   17155 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:57397 SSHKeyPath:/Users/christophe/.minikube/machines/minikube/id_rsa Username:docker}
I0119 16:55:39.471320   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-clusterrole.yaml
I0119 16:55:39.471328   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-clusterrole.yaml (1001 bytes)
I0119 16:55:39.487471   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-clusterrolebinding.yaml
I0119 16:55:39.487479   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-clusterrolebinding.yaml (1018 bytes)
I0119 16:55:39.509584   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-configmap.yaml
I0119 16:55:39.509603   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-configmap.yaml (837 bytes)
I0119 16:55:39.525958   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-dp.yaml
I0119 16:55:39.525965   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-dp.yaml (4278 bytes)
I0119 16:55:39.543359   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-role.yaml
I0119 16:55:39.543367   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-role.yaml (1724 bytes)
I0119 16:55:39.560289   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-rolebinding.yaml
I0119 16:55:39.560300   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-rolebinding.yaml (1046 bytes)
I0119 16:55:39.577330   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-sa.yaml
I0119 16:55:39.577338   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-sa.yaml (837 bytes)
I0119 16:55:39.593824   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-secret.yaml
I0119 16:55:39.593835   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-secret.yaml (1389 bytes)
I0119 16:55:39.610636   17155 addons.go:348] installing /etc/kubernetes/addons/dashboard-svc.yaml
I0119 16:55:39.610644   17155 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/dashboard-svc.yaml (1294 bytes)
I0119 16:55:39.629310   17155 ssh_runner.go:152] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.22.3/kubectl apply -f /etc/kubernetes/addons/dashboard-ns.yaml -f /etc/kubernetes/addons/dashboard-clusterrole.yaml -f /etc/kubernetes/addons/dashboard-clusterrolebinding.yaml -f /etc/kubernetes/addons/dashboard-configmap.yaml -f /etc/kubernetes/addons/dashboard-dp.yaml -f /etc/kubernetes/addons/dashboard-role.yaml -f /etc/kubernetes/addons/dashboard-rolebinding.yaml -f /etc/kubernetes/addons/dashboard-sa.yaml -f /etc/kubernetes/addons/dashboard-secret.yaml -f /etc/kubernetes/addons/dashboard-svc.yaml
I0119 16:55:40.496052   17155 addons.go:116] Writing out "minikube" config to set dashboard=true...
W0119 16:55:40.497967   17155 out.go:241] 🤔  Vérification de l'état du tableau de bord...
I0119 16:55:40.588750   17155 service.go:214] Found service: &Service{ObjectMeta:{kubernetes-dashboard  kubernetes-dashboard  c206690f-bce6-48dc-b56c-ea2e74c55e33 5131 0 2022-01-19 16:55:40 +0100 CET <nil> <nil> map[addonmanager.kubernetes.io/mode:Reconcile k8s-app:kubernetes-dashboard kubernetes.io/minikube-addons:dashboard] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubernetes-dashboard","kubernetes.io/minikube-addons":"dashboard"},"name":"kubernetes-dashboard","namespace":"kubernetes-dashboard"},"spec":{"ports":[{"port":80,"targetPort":9090}],"selector":{"k8s-app":"kubernetes-dashboard"}}}
] [] []  [{kubectl-client-side-apply Update v1 2022-01-19 16:55:40 +0100 CET FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:addonmanager.kubernetes.io/mode":{},"f:k8s-app":{},"f:kubernetes.io/minikube-addons":{}}},"f:spec":{"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}}}]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:80,TargetPort:{0 9090 },NodePort:0,AppProtocol:nil,},},Selector:map[string]string{k8s-app: kubernetes-dashboard,},ClusterIP:10.99.163.209,Type:ClusterIP,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,TopologyKeys:[],IPFamilyPolicy:*SingleStack,ClusterIPs:[10.99.163.209],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
W0119 16:55:40.590556   17155 out.go:241] 🚀  Lancement du proxy...
I0119 16:55:40.592119   17155 dashboard.go:152] Executing: /usr/local/bin/kubectl [/usr/local/bin/kubectl --context minikube proxy --port 0]
I0119 16:55:40.632761   17155 out.go:176] 
W0119 16:55:40.632957   17155 out.go:241] ❌  Fermeture en raison de HOST_KUBECTL_PROXY : proxy start: fork/exec /usr/local/bin/kubectl: exec format error
W0119 16:55:40.632971   17155 out.go:241] 
W0119 16:55:40.638643   17155 out.go:241] ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                            │
│    😿  Si les conseils ci-dessus ne vous aident pas, veuillez nous en informer :                                           │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                            │
│                                                                                                                            │
│    Veuillez exécuter `minikube logs --file=logs.txt` et attachez logs.txt au problème GitHub.                              │
│    Veuillez également joindre le fichier suivant au problème GitHub                                                        │
│    - /var/folders/zd/z4g508jx1hvczmkqsj6wll680000gn/T/minikube_dashboard_5b9326851acd8bcb48ab89643c4c9c27c7a4f75a_0.log    │
│                                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Log file created at: 2022/01/19 17:00:20

### Operating System

macOS (Default)

### Driver

Docker

**Comment by omersalaj** [comment]
Same here

**Comment by spowelljr** [comment]
Hi @Tchokomeni, are you using an M1 Mac?

**Comment by spowelljr** [comment]
Hi @Tchokomeni, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
