### ISSUE TITLE
Exiting due to DRV_MISSING_ADDRESS: Failed to start host: new host: dial tcp: missing address

### ISSUE THREAD

**Issue by dropthemasquerade** [kubernetes/minikube#13395]
## my libvirtd is running

```
[developer@VM-226-174-centos ~]$ systemctl status libvirtd
* libvirtd.service - Virtualization daemon
   Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2022-01-19 11:55:10 CST; 14min ago
     Docs: man:libvirtd(8)
           http://libvirt.org
 Main PID: 4408 (libvirtd)
    Tasks: 18
   Memory: 6.5M
   CGroup: /system.slice/libvirtd.service
           |- 4408 /usr/sbin/libvirtd
           |-24933 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --...
           `-24934 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --...
```

## my docker is running

```
[developer@VM-226-174-centos ~]$ systemctl status docker  
* docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; enabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/docker.service.d
           `-http-proxy.conf
   Active: active (running) since Wed 2022-01-19 11:35:08 CST; 36min ago
     Docs: https://docs.docker.com
 Main PID: 29561 (dockerd)
    Tasks: 25
   Memory: 37.1M
   CGroup: /system.slice/docker.service
           `-29561 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd....
```

## my minikube version

```
[developer@VM-226-174-centos ~]$ kubectl version --client -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "23",
    "gitVersion": "v1.23.1",
    "gitCommit": "86ec240af8cbd1b60bcc4c03c20da9b98005b92e",
    "gitTreeState": "clean",
    "buildDate": "2021-12-16T11:41:01Z",
    "goVersion": "go1.17.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}

```

## os information

```
[developer@VM-226-174-centos ~]$ uname -a
Linux VM-226-174-centos 3.10.107-1-tlinux2_kvm_guest-0049 #1 SMP Tue Jul 30 23:46:29 CST 2019 x86_64 x86_64 x86_64 GNU/Linux
```

### Attach the log file

[developer@VM-226-174-centos ~]$ minikube start
😄  minikube v1.24.0 on Centos 7.2 (amd64)
✨  Using the kvm2 driver based on existing profile
💾  Downloading driver docker-machine-driver-kvm2:
    > docker-machine-driver-kvm2....: 65 B / 65 B [----------] 100.00% ? p/s 0s
    > docker-machine-driver-kvm2: 11.40 MiB / 11.40 MiB  100.00% 40.27 MiB p/s 
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🤦  StartHost failed, but will try again: new host: dial tcp: missing address
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
😿  Failed to start kvm2 VM. Running "minikube delete" may fix it: new host: dial tcp: missing address

❌  Exiting due to DRV_MISSING_ADDRESS: Failed to start host: new host: dial tcp: missing address
💡  Suggestion: The machine-driver specified is failing to start. Try running 'docker-machine-driver-<type> version'
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6023
    ▪ https://github.com/kubernetes/minikube/issues/4679

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @dropthemasquerade, thanks for reporting your issue with minikube!

Could you run `minikube logs --file=logs.txt` and upload the log file to this issue. That will output more verbose logs and will help with debugging, thanks!

**Comment by klaases** [comment]
Hi @[dropthemasquerade](https://github.com/dropthemasquerade) – were you able to review Steven's comment in order to provide the additional log data that is needed for debugging?

Also, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
