### ISSUE TITLE
Impossible de démarrer MiniKube (macOS)

### ISSUE THREAD

**Issue by pchanas** [kubernetes/minikube#13396]
**Étapes pour reproduire le problème:** 

1. minikube start --kubernetes-version=v1.19.14 --driver=hyperkit --container-runtime=docker
2. MacOS Montery 12.1
3. Etapes suivies pour l'installation, etc : https://itnext.io/goodbye-docker-desktop-hello-minikube-3649f2a1c469 

**Sortie complète de la commande `minikube logs`:**
<details>

W0119 10:40:33.016650   49592 out.go:241] ❌  Fermeture en raison de GUEST_PROVISION : Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory

Fichier de logs en PJ

[logs.txt](https://github.com/kubernetes/minikube/files/7896048/logs.txt)

**Comment by spowelljr** [comment]
Hi @pchanas, thanks for reporting your issue with minikube!

This is a duplicate of https://github.com/kubernetes/minikube/issues/4206, so I'll close this issue as that issue has many comments and suggestions on it. Please read https://github.com/kubernetes/minikube/issues/4206 and see if any of the advice applies to you, thanks!

-----

Salut @pchanas, merci d'avoir signalé votre problème avec minikube !

Ceci est un doublon de https://github.com/kubernetes/minikube/issues/4206, donc je vais fermer ce problème car ce problème contient de nombreux commentaires et suggestions. Veuillez lire https://github.com/kubernetes/minikube/issues/4206 et voir si l'un des conseils s'applique à vous, merci !
