### ISSUE TITLE
minikube storage provisioner

### ISSUE THREAD

**Issue by backtrackshubham** [kubernetes/minikube#13406]
### What Happened?

Please go through this issue https://github.com/kubernetes-sigs/kind/issues/2597

### Attach the log file

Na

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by afbjorklund** [comment]
This was about the nfs provisioner, right ? Not the default hostpath one

**Comment by backtrackshubham** [comment]
@afbjorklund to me it seems both as I tried with kind and minikubes inbuilt k8s and in both the cases I found similar kind of behaviour

**Comment by klaases** [comment]
Hi @[backtrackshubham](https://github.com/backtrackshubham), did you have a chance to review @afbjorklund's comment on the [linked](https://github.com/kubernetes-sigs/kind/issues/2597) issue?

`I think you want to open a new issue for which "docker" to use in kind, it is off-topic here.`
