### ISSUE TITLE
Create new `releases.json` schema to support SHAs for all archs

### ISSUE THREAD

**Issue by unixlab** [kubernetes/minikube#13407]
### What Happened?

Hi!

I noticed that the current [releases.json](https://github.com/kubernetes/minikube/blob/master/deploy/minikube/releases.json) does not comply with the [schema](https://github.com/kubernetes/minikube/blob/master/deploy/minikube/schema.json).

I noticed because `minikube update-check` is broken since the new `releases.json` was pushed out.
(see `Attach the log file` section)

The `releases.json` generation [here](https://github.com/kubernetes/minikube/blob/master/hack/jenkins/release_update_releases_json.go#L33), does not match the corresponting counterpart [here](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/notify/notify.go#L134)

I tried to write a fix and currently all tests besides the schema check are green.
However, I'm struggling with the schema and would need help or someone else to take this over.
The current state I have is here: https://github.com/unixlab/minikube/commit/5f3f93b60ebc408e4c9c162964c99100557623a6

### Attach the log file

```
13:53:28 ~ $ minikube update-check

X Exiting due to INET_VERSION_UNAVAILABLE: Error getting json from minikube version url: json: cannot unmarshal object into Go struct field Release.Checksums of type string
* 
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    * Please also attach the following file to the GitHub issue:                             │
│    * - /tmp/minikube_update-check_7db9daf36ec61d5021304844f4320678ea49b1a1_0.log            │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Comment by rotty3000** [comment]
I observed exact issue just now.

Here is the log as error message requests.

[minikube_update-check_ae3ada15876f093074b98305c9e67f32241694da_0.log](https://github.com/kubernetes/minikube/files/7907648/minikube_update-check_ae3ada15876f093074b98305c9e67f32241694da_0.log)

**Comment by paurana** [comment]
This is occurring because the first element of the json array is
```{
	"checksums": {
		"amd64": {
			"darwin": "e90ad1c822d483665306c1d7d4368cfbaae3de9c5caf2ea1f41aaae052bec709",
			"linux": "ea633466a96ef354d8cee13b6894d9cff159635be8f9f6ac12bf630f578f2433",
			"windows": "f95e8f90214af616b0a455fa1f21d1f2290ceed476ac8ee7c2df352deda88259"
		},
		"arm": {
			"linux": "ed503e425be60d4e6cbd874b678e282826f838ba43522218b4fcf34eb7456961"
		},
		"arm64": {
			"darwin": "5a8b4ede041623f4ccffccc981c547aeb20e63843027a3c52c231786a1b87712",
			"linux": "7b4802fdb63dd69611905d3050b027bcb14f99170ec478f8c7d3468e9fe596b8"
		},
		"ppc64le": {
			"linux": "33506ac2ecf2825b32c7218ce8ddc99c975cfd1169ba274a67699f3771e9bb8e"
		},
		"s390x": {
			"linux": "af8dc756487be870ec5f9589d756b379fcd486c500303c415614ec890a4b27ac"
		},
		"darwin": "e90ad1c822d483665306c1d7d4368cfbaae3de9c5caf2ea1f41aaae052bec709",
		"linux": "ea633466a96ef354d8cee13b6894d9cff159635be8f9f6ac12bf630f578f2433",
		"windows": "f95e8f90214af616b0a455fa1f21d1f2290ceed476ac8ee7c2df352deda88259"
	},
	"name": "v1.25.0"
}
```

The above json does not follow  this format 
```
type release struct {
	Checksums checksums `json:"checksums"`
	Name      string    `json:"name"`
}
```


I did find a temporary fix, but it'll only work as long as the new versions follow the same format

**Comment by spowelljr** [comment]
Thanks for pointing this out @unixlab, I updated the file to include SHAs for all out binaries but was unaware we had a schema file. I can take this over.

**Comment by spowelljr** [comment]
For `1.25.0` & `1.25.1` we're going to revert to the old style of the schema and than for `1.26.0` we're going to have the new schema at a different endpoint that the newer versions of minikube can hit and not break the older versions.

**Comment by spowelljr** [comment]
Reverted the `releases.json` file, `minikube update-check` should be working again now, sorry for the inconvenience.

**Comment by medyagh** [comment]
@unixlab mind verifing if it is fixed now?

**Comment by unixlab** [comment]
@spowelljr @medyagh I can confirm that the fix is working of the following minikube versions:
- 1.23.3
- 1.24.0
- 1.25.0
- 1.25.1

I expect that it also works for all other minikube versions, I just haven't checked thoses.
