### ISSUE TITLE
X Exiting due to HOST_KUBECTL_PROXY: readByteWithTimeout: EOF

### ISSUE THREAD

**Issue by omersalaj** [kubernetes/minikube#13405]
### What Happened?

Throws an error when try to start minikube dashboard (using vmware driver)

I0120 09:31:35.591697   14708 out.go:297] Setting OutFile to fd 92 ...
I0120 09:31:35.592631   14708 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0120 09:31:35.592631   14708 out.go:310] Setting ErrFile to fd 96...
I0120 09:31:35.592631   14708 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0120 09:31:35.602014   14708 mustload.go:65] Loading cluster: minikube
I0120 09:31:35.602917   14708 config.go:176] Loaded profile config "minikube": Driver=vmware, ContainerRuntime=docker, KubernetesVersion=v1.22.3
I0120 09:31:35.603865   14708 main.go:130] libmachine: Found binary path at C:\Program Files (x86)\VMware\VMware Workstation\bin\docker-machine-driver-vmware.exe
I0120 09:31:35.603865   14708 main.go:130] libmachine: Launching plugin server for driver vmware
I0120 09:31:36.409967   14708 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:3039
I0120 09:31:36.410984   14708 main.go:130] libmachine: () Calling .GetVersion
I0120 09:31:36.411519   14708 main.go:130] libmachine: Using API Version  1
I0120 09:31:36.411519   14708 main.go:130] libmachine: () Calling .SetConfigRaw
I0120 09:31:36.412034   14708 main.go:130] libmachine: () Calling .GetMachineName
I0120 09:31:36.412563   14708 main.go:130] libmachine: (minikube) Calling .GetState
I0120 09:31:36.413080   14708 main.go:130] libmachine: (minikube) DBG | executing: C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe list
I0120 09:31:36.842684   14708 main.go:130] libmachine: (minikube) DBG | Total running VMs: 1
I0120 09:31:36.842684   14708 main.go:130] libmachine: (minikube) DBG | C:\Users\omersalaj\.minikube\machines\minikube\minikube.vmx
I0120 09:31:36.859137   14708 host.go:66] Checking if "minikube" exists ...
I0120 09:31:36.860070   14708 main.go:130] libmachine: Found binary path at C:\Program Files (x86)\VMware\VMware Workstation\bin\docker-machine-driver-vmware.exe
I0120 09:31:36.860243   14708 main.go:130] libmachine: Launching plugin server for driver vmware
I0120 09:31:36.871172   14708 main.go:130] libmachine: Plugin server listening at address 127.0.0.1:3041
I0120 09:31:36.872250   14708 main.go:130] libmachine: () Calling .GetVersion
I0120 09:31:36.872250   14708 main.go:130] libmachine: Using API Version  1
I0120 09:31:36.872754   14708 main.go:130] libmachine: () Calling .SetConfigRaw
I0120 09:31:36.873385   14708 main.go:130] libmachine: () Calling .GetMachineName
I0120 09:31:36.874401   14708 main.go:130] libmachine: (minikube) Calling .DriverName
I0120 09:31:36.874942   14708 api_server.go:165] Checking apiserver status ...
I0120 09:31:36.887167   14708 ssh_runner.go:152] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0120 09:31:36.887167   14708 main.go:130] libmachine: (minikube) Calling .GetSSHHostname
I0120 09:31:36.888463   14708 main.go:130] libmachine: (minikube) DBG | executing: C:\Program Files (x86)\VMware\VMware Workstation\vmrun.exe list
I0120 09:31:37.314169   14708 main.go:130] libmachine: (minikube) DBG | Total running VMs: 1
I0120 09:31:37.314251   14708 main.go:130] libmachine: (minikube) DBG | C:\Users\omersalaj\.minikube\machines\minikube\minikube.vmx
I0120 09:31:37.332320   14708 main.go:130] libmachine: (minikube) DBG | MAC address in VMX: 00:0c:29:98:36:79
I0120 09:31:37.333422   14708 main.go:130] libmachine: (minikube) DBG | Trying to find IP address in configuration file: C:\ProgramData\VMware\vmnetdhcp.conf
I0120 09:31:37.333492   14708 main.go:130] libmachine: (minikube) DBG | Following IPs found map[00:50:56:c0:00:01:192.168.18.1 00:50:56:c0:00:08:192.168.25.1]
I0120 09:31:37.335336   14708 main.go:130] libmachine: (minikube) DBG | Trying to find IP address in leases file: C:\ProgramData\VMware\vmnetdhcp.leases
I0120 09:31:37.332753   14708 main.go:130] libmachine: (minikube) Calling .GetSSHPort
I0120 09:31:37.335892   14708 main.go:130] libmachine: (minikube) DBG | IP found in DHCP lease table: 192.168.25.129
I0120 09:31:37.335892   14708 main.go:130] libmachine: (minikube) Calling .GetSSHKeyPath
I0120 09:31:37.337047   14708 main.go:130] libmachine: (minikube) Calling .GetSSHUsername
I0120 09:31:37.337550   14708 sshutil.go:53] new ssh client: &{IP:192.168.25.129 Port:22 SSHKeyPath:C:\Users\omersalaj\.minikube\machines\minikube\id_rsa Username:docker}
I0120 09:31:37.463013   14708 ssh_runner.go:152] Run: sudo egrep ^[0-9]+:freezer: /proc/6129/cgroup
I0120 09:31:37.471617   14708 api_server.go:181] apiserver freezer: "7:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podba63ce52540842499547450afdeee766.slice/docker-af47b6509ac2c10bc35dfa7afe9232c15eee3bc6ba66be5f4436ac63ea08c383.scope"
I0120 09:31:37.482649   14708 ssh_runner.go:152] Run: sudo cat /sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podba63ce52540842499547450afdeee766.slice/docker-af47b6509ac2c10bc35dfa7afe9232c15eee3bc6ba66be5f4436ac63ea08c383.scope/freezer.state
I0120 09:31:37.490015   14708 api_server.go:203] freezer state: "THAWED"
I0120 09:31:37.490015   14708 api_server.go:240] Checking apiserver healthz at https://192.168.25.129:8443/healthz ...
I0120 09:31:37.495900   14708 api_server.go:266] https://192.168.25.129:8443/healthz returned 200:
ok
W0120 09:31:37.496143   14708 out.go:241] * Verifying dashboard health ...
* Verifying dashboard health ...
I0120 09:31:37.512218   14708 service.go:214] Found service: &Service{ObjectMeta:{kubernetes-dashboard  kubernetes-dashboard  6f0a8570-f9c0-4d9e-a3fd-7f5c30ffd9aa 801 0 2022-01-20 09:26:45 +0100 CET <nil> <nil> map[addonmanager.kubernetes.io/mode:Reconcile k8s-app:kubernetes-dashboard kubernetes.io/minikube-addons:dashboard] map[kubectl.kubernetes.io/last-applied-configuration:{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubernetes-dashboard","kubernetes.io/minikube-addons":"dashboard"},"name":"kubernetes-dashboard","namespace":"kubernetes-dashboard"},"spec":{"ports":[{"port":80,"targetPort":9090}],"selector":{"k8s-app":"kubernetes-dashboard"}}}
] [] []  [{kubectl-client-side-apply Update v1 2022-01-20 09:26:45 +0100 CET FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}},"f:labels":{".":{},"f:addonmanager.kubernetes.io/mode":{},"f:k8s-app":{},"f:kubernetes.io/minikube-addons":{}}},"f:spec":{"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}}}]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:80,TargetPort:{0 9090 },NodePort:0,AppProtocol:nil,},},Selector:map[string]string{k8s-app: kubernetes-dashboard,},ClusterIP:10.104.252.240,Type:ClusterIP,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,TopologyKeys:[],IPFamilyPolicy:*SingleStack,ClusterIPs:[10.104.252.240],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
W0120 09:31:37.512733   14708 out.go:241] * Launching proxy ...
* Launching proxy ...
I0120 09:31:37.515876   14708 dashboard.go:152] Executing: C:\Windows\system32\kubectl.bat [C:\Windows\system32\kubectl.bat --context minikube proxy --port 0]
I0120 09:31:37.518057   14708 dashboard.go:157] Waiting for kubectl to output host:port ...
I0120 09:31:37.630809   14708 out.go:176]

W0120 09:31:37.632102   14708 out.go:241] X Exiting due to HOST_KUBECTL_PROXY: readByteWithTimeout: EOF
X Exiting due to HOST_KUBECTL_PROXY: readByteWithTimeout: EOF
W0120 09:31:37.634459   14708 out.go:241] *

### Attach the log file

[minikube_dashboard_e92c16188bc7a55b4785439aca9a14af3e0d8327_0.log](https://github.com/kubernetes/minikube/files/7903546/minikube_dashboard_e92c16188bc7a55b4785439aca9a14af3e0d8327_0.log)

### Operating System

Windows

### Driver

VMWare

**Comment by klaases** [comment]
Hi @[omersalaj](https://github.com/omersalaj) are you still experiencing this issue?

**Comment by omersalaj** [comment]
@klaases I updated to Minikube v1.25.2 and the problem still exist to me. I can get pods and do the stuff but can not start dashboard. Same issue seems to appear here https://github.com/kubernetes/minikube/issues/13361

**Comment by ohiliazov** [comment]
I have the same issue with docker driver.
