### ISSUE TITLE
minikube import command OR document how to import docker images w/o rebuild

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1341]
Users often have pre-built docker images on their local docker daemon that they wish to use in minikube.  Currently most users switch to using minikube's docker daemon and then have to rebuild their images but this is not necessary.  We should either document transferring images using `docker save <image> | minikube ssh docker load` or we can perhaps alias this command as `minikube import`

**Comment by hypnoglow** [comment]
Upvote for this.

For some reason,  `docker save <image> | minikube ssh docker load` doesn't work for me on macOS, it just outputs random binary data instead. 

What I'm trying to achieve is to have my docker image inside minikube without setting up a registry. I cannot just `eval $(minikube docker-env)`  and build my docker image there, because docker in minikube iso is too old.

**Comment by msteffen** [comment]
@hypnoglow did you ever figure out a solution to your issue? `docker save <image> | minikube ssh docker load` used to work for me, but I just upgraded to `minikube version: v0.22.1` and starting seeing this issue (lots of garbled binary data gets dumped to standard out and the docker image is never loaded).

**Comment by hypnoglow** [comment]
@msteffen I simply switched to plain ssh instead of  `minikube ssh`:

```bash
docker save <image> | ssh docker@$(minikube ip) docker load

# the full command I use:
docker save <image> | ssh -o UserKnownHostsFile=/dev/null \
    -o StrictHostKeyChecking=no -o LogLevel=quiet \
    -i ~/.minikube/machines/minikube/id_rsa docker@$(minikube ip) docker load
```

**Comment by msteffen** [comment]
For posterity: an interesting alternative I found, that doesn't use ssh, is:
`docker save "${1}" | pv | (eval $(minikube docker-env) && docker load)`

**Comment by the-redback** [comment]
```bash
$ docker save "${1}" | pv | (eval $(minikube docker-env) && docker load)
```
@msteffen , How to convert this command for [fish shell](https://fishshell.com/)?? I am having hard time doing it. :(

**Comment by timoreimann** [comment]
I keep going back to this issue to figure out our the trick works. IMHO, it should still be turned into a proper command or a piece of documentation.

Can we consider to reopen the issue?

**Comment by mauriciomoccelin** [comment]
## This script works for windows, import local image from Docker to Minikube Docker Daemon 
```
param(
  [Parameter(Mandatory=$true)][string]$image,
  [Parameter(Mandatory=$true)][string]$name,
  [Parameter][string]$output 
)

if (!$output) {
  $output = Get-Location
}
```
#### Save image to output with specified name
`docker save -o "$output\$name" $image`

#### Connects to Docker registry inside Minikube
`& minikube docker-env | Invoke-Expression`

#### Load image saved to Docker registry inside Minikube
`docker load -i "$output\$name"` 

#### Back to local docker registration
`& minikube docker-env -u | Invoke-Expression`

#### Full script

```
param(
  [Parameter(Mandatory=$true)][string]$image,
  [Parameter(Mandatory=$true)][string]$name,
  [Parameter][string]$output 
)

if (!$output) {
  $output = Get-Location
}

docker save -o "$output\$name" $image
& minikube docker-env | Invoke-Expression
docker load -i "$output\$name" 
& minikube docker-env -u | Invoke-Expression

```
