### ISSUE TITLE
【Mac M1】Exiting due to GUEST_START

### ISSUE THREAD

**Issue by codelhh** [kubernetes/minikube#13424]
Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /etc/kubernetes: mkdir /etc/kubernetes: permission denied

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by codelhh** [comment]
xxx@macintoshdeMacBook-Pro ~ % minikube start --driver=docker --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'

😄  minikube v1.24.0 on Darwin 11.2 (arm64)
    ▪ KUBECONFIG=/etc/kubernetes/admin.conf
✨  Using the docker driver based on user configuration
✅  Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1988MB) ...
🐳  Preparing Kubernetes v1.22.3 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...

❌  Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error writing file /etc/kubernetes/admin.conf: open /etc/kubernetes/admin.conf: permission denied

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

xxx@macintoshdeMacBook-Pro ~ % minikube logs --file=logs.txt
xxx@macintoshdeMacBook-Pro ~ %

**Comment by codelhh** [comment]
log file is empty

**Comment by codelhh** [comment]
==> container status <==
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
time="2022-01-24T06:39:16Z" level=warning msg="runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock]. As the default settings are now deprecated, you should set the endpoint instead."
time="2022-01-24T06:39:18Z" level=error msg="connect endpoint 'unix:///var/run/dockershim.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded"
time="2022-01-24T06:39:18Z" level=warning msg="image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock]. As the default settings are now deprecated, you should set the endpoint instead."
time="2022-01-24T06:39:20Z" level=error msg="connect endpoint 'unix:///var/run/dockershim.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded"
time="2022-01-24T06:39:20Z" level=fatal msg="listing containers: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"


==> describe nodes <==
E0124 14:39:20.271549   90529 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: /var/lib/minikube/binaries/v1.22.3/kubectl: command not found
 output: "\n** stderr ** \nsudo: /var/lib/minikube/binaries/v1.22.3/kubectl: command not found\n\n** /stderr **"

==> dmesg <==
[Jan23 21:07] cacheinfo: Unable to detect cache hierarchy for CPU 0
[  +0.027649] the cryptoloop driver has been deprecated and will be removed in in Linux 5.16
[ +19.115386] grpcfuse: loading out-of-tree module taints kernel.
[Jan23 22:06] hrtimer: interrupt took 51868291 ns


==> kernel <==
 06:39:20 up  9:31,  0 users,  load average: 0.41, 0.42, 0.30
Linux minikube 5.10.76-linuxkit #1 SMP PREEMPT Mon Nov 8 11:22:26 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04.2 LTS"


==> kubelet <==
-- Logs begin at Mon 2022-01-24 06:39:03 UTC, end at Mon 2022-01-24 06:39:20 UTC. --
-- No entries --


❗  unable to fetch logs for: describe nodes


@spowelljr

**Comment by codelhh** [comment]
I tried minicube delete -- all -- purge and restart minicube, but now I still report this error

**Comment by codelhh** [comment]
> Thank you for sharing your experience!
> 
> Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.
> 
> This will help us isolate the problem further, thank you!

After looking at other issues, it has been solved ，thanks
