### ISSUE TITLE
minikube wont start

### ISSUE THREAD

**Issue by bekamdo** [kubernetes/minikube#13430]
### What Happened?

E0122 12:38:08.927239   15084 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

! unable to fetch logs for: describe nodes

### Attach the log file

E0122 12:38:08.927239   15084 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

! unable to fetch logs for: describe nodes

### Operating System

Windows

### Driver

Hyper-V

**Comment by spowelljr** [comment]
Hi @bekamdo, thanks for reporting your issue with minikube!

Try running `minikube delete` and then run `minikube logs --file=logs.txt` again and upload the log file to this issue, thanks!

**Comment by klaases** [comment]
Hi @[bekamdo](https://github.com/bekamdo) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
