### ISSUE TITLE
Show the container runtime when running without kubernetes

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#13432]
Currently we hide the container runtime output.

But there should be plenty of room to show it ?

No Kubernetes

```
😄  minikube v1.25.1 on Ubuntu 20.04
✨  Automatically selected the kvm2 driver. Other choices: virtualbox, ssh
👍  Starting minikube without Kubernetes minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
🏄  Done! minikube is ready without Kubernetes!
╭───────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                       │
│                       💡  Things to try without Kubernetes ...                        │
│                                                                                       │
│    - "minikube ssh" to SSH into minikube's node.                                      │
│    - "minikube docker-env" to point your docker-cli to the docker inside minikube.    │
│    - "minikube image" to build images without docker.                                 │
│                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────╯
```

With Kubernetes

```
😄  minikube v1.25.1 on Ubuntu 20.04
✨  Automatically selected the kvm2 driver. Other choices: virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.23.1 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

----

This sentence is somewhat weird: "Starting minikube without Kubernetes minikube"

~Probably better off as "Starting virtual machine minikube" (or "container", for KIC) ?~

EDIT: It did say "VM" on the line below, so maybe something else rhyming with node.

```
👍  Starting node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
```

And this one doesn't contain much info: "Done! minikube is ready without Kubernetes!"

~Slightly more useful as "Done! minikube is ready with Docker 20.10.12" instead~

EDIT: Possibly on a separate line, to show the fancy runtime emoji (like that whale)

```
🐳  Preparing Docker 20.10.12 ...
🏄  Done! minikube is ready without Kubernetes!
```

**Comment by afbjorklund** [comment]
Eventually this should tie into provisioning, and output the result of it:

* #10883

**Comment by afbjorklund** [comment]
This also looks a bit useless:

```
I0123 12:54:26.754644   60094 preload.go:132] Checking if preload exists for k8s version v0.0.0 and runtime containerd
W0123 12:54:26.953318   60094 preload.go:115] https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v16-v0.0.0-containerd-overlay2-amd64.tar.lz4 status code: 404
```

Can skip the preload, for v0.0.0

**Comment by MdSahil-oss** [comment]
@afbjorklund Do you think this is good first issue to contribute, if so, can you suggest me the path of changing files as I'm beginner and want to contribute too.

**Comment by MdSahil-oss** [comment]
@afbjorklund, if we rename  "Starting minikube without Kubernetes minikube" to "Starting node minikube in cluster minikube" , it's good but if we change 🏄 emoji with something else like that 🐳, it will change the minikube status meaning that is already specified by minikube (you can check emojis meaning https://github.com/kubernetes/minikube/blob/master/pkg/minikube/style/style.go).

**Comment by MdSahil-oss** [comment]
and don't you think ?, Showing container runtime output will be a little bit confusing for beginners.

**Comment by afbjorklund** [comment]
> Showing container runtime output will be a little bit confusing for beginners.

It was supposed to look something like this:

```
😄  minikube v1.25.1 on Ubuntu 20.04
✨  Automatically selected the kvm2 driver. Other choices: virtualbox, ssh
👍  Starting node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
🐳  Preparing Docker 20.10.12 ...
🏄  Done! minikube is ready without Kubernetes!
```

Should hopefully be less confusing, not more ?

**Comment by MdSahil-oss** [comment]
> @afbjorklund, if we rename "Starting minikube without Kubernetes minikube" to "Starting node minikube in cluster minikube" , it's good but if we change surfer emoji with something else like that whale, it will change the minikube status meaning that is already specified by minikube (you can check emojis meaning https://github.com/kubernetes/minikube/blob/master/pkg/minikube/style/style.go).

What about this ?

**Comment by klaases** [comment]
Hi @MdSahil-oss, please see @spowelljr's comments on PR #13513 before we can  merge.

**Comment by klaases** [comment]
Hi @MdSahil-oss, just wanted to check if you are still actively working on this issue?

**Comment by klaases** [comment]
Un-assigning @MdSahil-oss, please feel free to re-assign if still actively working on this issue.

**Comment by klaases** [comment]
Hi @[afbjorklund](https://github.com/afbjorklund), would you mind taking a look at [Gimb0](https://github.com/Gimb0)'s [PR](https://github.com/kubernetes/minikube/pull/14200) to see if this helps display the container runtime data that you were looking for?
