### ISSUE TITLE
Error while configuring RBAC rules

### ISSUE THREAD

**Issue by abhidesh128** [kubernetes/minikube#13431]
I just started to learn about kubernetes and was successful to set it up on my MX Linux 21 (Debian 11) Machine.

I started the cluster using `minikube start` command and after my tutorial, I halted it with `minikube stop`. Now, when I try to start it again, it starts correctly, but throws these errors :
```
▪ Configuring RBAC rules ...- E0122 16:14:32.539124   50570 kubeadm.go:270] unable to create cluster role binding, some addons might not work: apply sa: sudo /var/lib/minikube/binaries/v1.23.1/kubectl create clusterrolebinding minikube-rbac --clusterrole=cluster-admin --serviceaccount=kube-system:default --kubeconfig=/var/lib/minikube/kubeconfig: Process exited with status 1
stdout:

stderr:
error: failed to create clusterrolebinding: clusterrolebindings.rbac.authorization.k8s.io "minikube-rbac" already exists
```
I am using minikube 1.25.1.

**Comment by VtG242** [comment]
I had the same issue ... removing whole ./minicube dir and minikube start solved the problem for me.

**Comment by abhidesh128** [comment]
@VtG242 Thanks for your reply. Did you tried running `minikube stop` once and then again `minikube start` ?

When I first time ran `minikube start`, this issue was not there. It originated after halting the cluster, and then starting back again.

**Comment by VtG242** [comment]
You're right, stop and start and the message is back :-(

**Comment by purplegrapeZz** [comment]
looks like an issue in minikue1.25. Downgrade to minikube1.24 works.

**Comment by abhidesh128** [comment]
Indeed. Downgrading to 1.24 works correctly. This is an issue in 1.25 for sure.

**Comment by spowelljr** [comment]
Thanks for reporting this issue, I did some testing and it was introduced with my PR https://github.com/kubernetes/minikube/pull/13121. It seems to be specific to VM drivers, it wasn't caught by the tests as it doesn't break the start, it just outputs the error to the screen.
