### ISSUE TITLE
Avoid downloading preload, when not using kubernetes

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#13448]
Currently it is looking for `v0.0.0` on the preload server first

**Comment by medyagh** [comment]
is this bug still happening?

**Comment by medyagh** [comment]
I would be happy to review a PR that fixes it !

**Comment by spowelljr** [comment]
I just tried with HyperKit and Docker and neither downloaded the preload when I passed `--no-kubernetes` so this seems to be fixed.
