### ISSUE TITLE
 Bump go.opentelemetry.io/otel/trace from 1.0.0-RC1 to 1.3.0 in go mod

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#13459]
This automation Bot failed because it needs some API changes

https://github.com/kubernetes/minikube/pull/13382#issue-1107377417

**Comment by eyskim** [comment]
Hi @medyagh, I've created a PR with changes identical to that of #13382. Could you please advise if more changes are required? Thanks!

/assign

**Comment by chungjin** [comment]
Hi @eyskim , do you still want to work on it? I can help to pick it up.
