### ISSUE TITLE
Append Changelog to KIC Base Image build and ISO Image build process

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#13486]
each time we comment ok-to-build-iso or ok-to-build-image our Bots creates an Docker image and ISO image
we should add a changelog.txt to file both ISO and KIC image with PR number and Commit number

so we see and audit of all merged things in that ISO / Kic Image

This task can be done by two PRs one for KIC and one for ISO

Example Pr that pushes new image by ok-to-build-image 

https://github.com/kubernetes/minikube/pull/13302#issuecomment-1010400304

**Comment by NikhilSharmaWe** [comment]
@medyagh I would like to work on it, could you please provide some information on how to proceed in the task and where the changes needed in the repo.

**Comment by NikhilSharmaWe** [comment]
@medyagh I would like to work on it, could you please provide some information on how to proceed in the task and where the changes needed in the repo. Some code pointers would be really helpful.
