### ISSUE TITLE
Output message if user tries to enable addons with `--no-kubernetes`

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#13487]
It's not possible to enable addons with `--no-kubernetes` passed because the addons in their current state are deployed to Kubernetes. So if a user tries to enable an addon with `--no-kubernetes` output a message notifying them that it's not possible without Kubernetes and exit execution.

Related https://github.com/kubernetes/minikube/issues/13461

**Comment by NikhilSharmaWe** [comment]
@spowelljr I would like to work on it, could you please give me some code pointers or inform about where in the repo the changes are needed.

**Comment by spowelljr** [comment]
@NikhilSharmaWe This is where the `minikube addons enable <addon>` logic gets called initially. You can run the command `config.Load(ClusterFlagValue())` to get the existing cluster config and check if `--no-kubernetes` is set, and if it is just exit with the message.

**Comment by deepto98** [comment]
Can I pick this up, if its still open?

**Comment by Aut0R3V** [comment]
Hey, anyone working on this?
