### ISSUE TITLE
Unable to start Minkube.  Exiting due to GUEST_NOT_FOUND

### ISSUE THREAD

**Issue by chrisc1122** [kubernetes/minikube#13498]
### What Happened?

* minikube v1.25.1 on Microsoft Windows 10 Enterprise LTSC 2019 10.0.17763 Build 17763
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

* Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\CC10489\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\CC10489\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

Tried to delete, same message.  Also tried updating VirtualBox from 5.2.34 to 6.1.32.  Still does not start.

### Attach the log file

Log file created at: 2022/01/26 12:14:28
Running on machine: LSC64LITA177PRE
Binary: Built with gc go1.17.5 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0126 12:14:28.702836    2660 out.go:297] Setting OutFile to fd 92 ...
I0126 12:14:28.705426    2660 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0126 12:14:28.705426    2660 out.go:310] Setting ErrFile to fd 96...
I0126 12:14:28.705426    2660 out.go:344] TERM=,COLORTERM=, which probably does not support color
W0126 12:14:28.716535    2660 root.go:293] Error reading config file at C:\Users\CC10489\.minikube\config\config.json: open C:\Users\CC10489\.minikube\config\config.json: The system cannot find the file specified.
I0126 12:14:28.717608    2660 out.go:297] Setting OutFile to fd 696 ...
I0126 12:14:28.717608    2660 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0126 12:14:28.717608    2660 out.go:310] Setting ErrFile to fd 696...
I0126 12:14:28.717608    2660 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0126 12:14:28.718824    2660 out.go:176] * 
I0126 12:14:28.719343    2660 out.go:176] * ==> Audit <==
I0126 12:14:28.720956    2660 out.go:176] * |---------|------|---------|------|---------|------------|----------|
| Command | Args | Profile | User | Version | Start Time | End Time |
|---------|------|---------|------|---------|------------|----------|
|---------|------|---------|------|---------|------------|----------|

I0126 12:14:28.721575    2660 out.go:176] * 
I0126 12:14:28.722646    2660 out.go:176] * ==> Last Start <==
I0126 12:14:28.723963    2660 out.go:176] * Log file created at: 2022/01/26 12:13:09
Running on machine: LSC64LITA177PRE
Binary: Built with gc go1.17.5 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0126 12:13:09.762216     920 out.go:297] Setting OutFile to fd 92 ...
I0126 12:13:09.772242     920 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0126 12:13:09.772242     920 out.go:310] Setting ErrFile to fd 96...
I0126 12:13:09.772242     920 out.go:344] TERM=,COLORTERM=, which probably does not support color
W0126 12:13:09.783045     920 root.go:293] Error reading config file at C:\Users\CC10489\.minikube\config\config.json: open C:\Users\CC10489\.minikube\config\config.json: The system cannot find the file specified.
I0126 12:13:09.784121     920 out.go:304] Setting JSON to false
I0126 12:13:09.787653     920 start.go:112] hostinfo: {"hostname":"LSC64LITA177PRE","uptime":1330,"bootTime":1643215859,"procs":213,"os":"windows","platform":"Microsoft Windows 10 Enterprise LTSC 2019","platformFamily":"Standalone Workstation","platformVersion":"10.0.17763 Build 17763","kernelVersion":"10.0.17763 Build 17763","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"488634e6-2290-4e16-ab4c-d0fca40b2884"}
W0126 12:13:09.787653     920 start.go:120] gopshost.Virtualization returned error: not implemented yet
I0126 12:13:09.793061     920 out.go:176] * minikube v1.25.1 on Microsoft Windows 10 Enterprise LTSC 2019 10.0.17763 Build 17763
I0126 12:13:09.793061     920 notify.go:174] Checking for updates...
I0126 12:13:09.794154     920 config.go:176] Loaded profile config "minikube": Driver=virtualbox, ContainerRuntime=docker, KubernetesVersion=v1.23.1
I0126 12:13:09.794154     920 driver.go:344] Setting default libvirt URI to qemu:///system
W0126 12:13:09.795230     920 start.go:703] api.Load failed for minikube: filestore "minikube": Error getting migrated host: unexpected end of JSON input
I0126 12:13:10.181400     920 out.go:176] * Using the virtualbox driver based on existing profile
I0126 12:13:10.182055     920 start.go:280] selected driver: virtualbox
I0126 12:13:10.182055     920 start.go:795] validating driver "virtualbox" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.25.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.29@sha256:be897edc9ed473a9678010f390a0092f488f6a1c30865f571c3b6388f9f56f9b Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.23.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[{Component:kubelet Key:housekeeping-interval Value:5m}] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.23.1 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:C:\Users\CC10489:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror:}
I0126 12:13:10.182661     920 start.go:806] status for virtualbox: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc:}
I0126 12:13:10.182661     920 start.go:1498] auto setting extra-config to "kubelet.housekeeping-interval=5m".
I0126 12:13:10.704235     920 cni.go:93] Creating CNI manager for ""
I0126 12:13:10.704235     920 cni.go:167] CNI unnecessary in this configuration, recommending no CNI
I0126 12:13:10.704235     920 start_flags.go:300] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.25.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.29@sha256:be897edc9ed473a9678010f390a0092f488f6a1c30865f571c3b6388f9f56f9b Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.23.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[{Component:kubelet Key:housekeeping-interval Value:5m}] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.23.1 ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:C:\Users\CC10489:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror:}
I0126 12:13:10.704235     920 iso.go:123] acquiring lock: {Name:mk3505be32405b2d8c9f09e58876df9df8c4e612 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0126 12:13:10.710605     920 out.go:176] * Starting control plane node minikube in cluster minikube
I0126 12:13:10.710605     920 preload.go:132] Checking if preload exists for k8s version v1.23.1 and runtime docker
I0126 12:13:10.710605     920 preload.go:148] Found local preload: C:\Users\CC10489\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v16-v1.23.1-docker-overlay2-amd64.tar.lz4
I0126 12:13:10.710605     920 cache.go:57] Caching tarball of preloaded images
I0126 12:13:10.710605     920 preload.go:174] Found C:\Users\CC10489\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v16-v1.23.1-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0126 12:13:10.711109     920 cache.go:60] Finished verifying existence of preloaded tar for  v1.23.1 on docker
I0126 12:13:10.711183     920 profile.go:147] Saving config to C:\Users\CC10489\.minikube\profiles\minikube\config.json ...
I0126 12:13:10.713362     920 cache.go:208] Successfully downloaded all kic artifacts
I0126 12:13:10.713362     920 start.go:313] acquiring machines lock for minikube: {Name:mk5c6be63d85dc00c46d2b67dc6fe38e63d92398 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0126 12:13:10.713362     920 start.go:317] acquired machines lock for "minikube" in 0s
I0126 12:13:10.713362     920 start.go:93] Skipping create...Using existing machine configuration
I0126 12:13:10.713362     920 fix.go:55] fixHost starting: 
I0126 12:13:10.713925     920 fix.go:57] fixHost completed within 563µs
I0126 12:13:10.713925     920 start.go:80] releasing machines lock for "minikube", held for 563µs
W0126 12:13:10.713925     920 start.go:566] error starting host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": Error getting migrated host: unexpected end of JSON input
W0126 12:13:10.713925     920 out.go:241] ! StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": Error getting migrated host: unexpected end of JSON input
I0126 12:13:10.714444     920 start.go:581] Will try again in 5 seconds ...
I0126 12:13:15.717082     920 start.go:313] acquiring machines lock for minikube: {Name:mk5c6be63d85dc00c46d2b67dc6fe38e63d92398 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0126 12:13:15.717730     920 start.go:317] acquired machines lock for "minikube" in 647.7µs
I0126 12:13:15.717730     920 start.go:93] Skipping create...Using existing machine configuration
I0126 12:13:15.717730     920 fix.go:55] fixHost starting: 
I0126 12:13:15.718926     920 fix.go:57] fixHost completed within 1.1955ms
I0126 12:13:15.718926     920 start.go:80] releasing machines lock for "minikube", held for 1.1955ms
W0126 12:13:15.719498     920 out.go:241] * Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": Error getting migrated host: unexpected end of JSON input
I0126 12:13:15.724791     920 out.go:176] 
W0126 12:13:15.725035     920 out.go:241] X Exiting due to GUEST_PROVISION: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": Error getting migrated host: unexpected end of JSON input
W0126 12:13:15.726516     920 out.go:241] * 
W0126 12:13:15.728126     920 out.go:241] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

I0126 12:14:28.724612    2660 out.go:176] * 
I0126 12:14:28.724612    2660 out.go:310] Setting ErrFile to fd 96...
I0126 12:14:28.724612    2660 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0126 12:14:28.724612    2660 out.go:297] Setting OutFile to fd 92 ...
I0126 12:14:28.724612    2660 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0126 12:14:28.724612    2660 mustload.go:65] Loading cluster: minikube
I0126 12:14:28.725773    2660 config.go:176] Loaded profile config "minikube": Driver=virtualbox, ContainerRuntime=docker, KubernetesVersion=v1.23.1
I0126 12:14:28.727016    2660 out.go:176] 
W0126 12:14:28.727016    2660 out.go:241] X Exiting due to GUEST_STATUS: load: filestore "minikube": Error getting migrated host: unexpected end of JSON input
W0126 12:14:28.728068    2660 out.go:241] * 
W0126 12:14:28.733116    2660 out.go:241] ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                            │
│    * If the above advice does not help, please let us know:                                                │
│      https://github.com/kubernetes/minikube/issues/new/choose                                              │
│                                                                                                            │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                   │
│    * Please also attach the following file to the GitHub issue:                                            │
│    * - C:\Users\CC10489\AppData\Local\Temp\minikube_logs_e826d8bdf6447c15610767151789325ca1789ed3_0.log    │
│                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Windows

### Driver

VirtualBox

**Comment by alidurgun** [comment]
I had same problem and I resolved my problem with
1-) minikube delete
2-) minikube start --no-vtx-check   (Without specifying driver)
Magically it worked maybe it will help you too.

**Comment by klaases** [comment]
Hi @[chrisc1122](https://github.com/chrisc1122), were you able to apply @[alidurgun](https://github.com/alidurgun)'s suggestion?

**Comment by shrutiebony** [comment]
@alidurgun thanks. I was facing the same issue and your solution worked for me. But now it is using docker as the base container and not Hyperv, as I wanted it to use. Any idea how to use Hyperv as the base container without facing the same problem again.
