### ISSUE TITLE
Got this error after execute command 'minikube delete' and run again 'minikube start --driver=docker'

### ISSUE THREAD

**Issue by manyfacegod** [kubernetes/minikube#13495]
* 
* ==> Audit <==
* |---------|------|----------|---------|---------|-------------------------------|-------------------------------|
| Command | Args | Profile  |  User   | Version |          Start Time           |           End Time            |
|---------|------|----------|---------|---------|-------------------------------|-------------------------------|
| delete  |      | minikube | user | v1.25.1 | Wed, 26 Jan 2022 14:27:07 WIB | Wed, 26 Jan 2022 14:27:09 WIB |
|---------|------|----------|---------|---------|-------------------------------|-------------------------------|

* 
* ==> Last Start <==
* Log file created at: 2022/01/26 14:43:13
Running on machine: parrot
Binary: Built with gc go1.17.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0126 14:43:13.870874   32134 out.go:297] Setting OutFile to fd 1 ...
I0126 14:43:13.870978   32134 out.go:349] isatty.IsTerminal(1) = true
I0126 14:43:13.870982   32134 out.go:310] Setting ErrFile to fd 2...
I0126 14:43:13.870987   32134 out.go:349] isatty.IsTerminal(2) = true
I0126 14:43:13.871103   32134 root.go:315] Updating PATH: /home/jonsnow/.minikube/bin
I0126 14:43:13.871378   32134 out.go:304] Setting JSON to false
I0126 14:43:13.872574   32134 start.go:112] hostinfo: {"hostname":"parrot","uptime":11313,"bootTime":1643171681,"procs":237,"os":"linux","platform":"debian","platformFamily":"debian","platformVersion":"parrot","kernelVersion":"5.14.0-2parrot1-amd64","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"14975851-69d1-4e32-8c52-556990f56e1f"}
I0126 14:43:13.872665   32134 start.go:122] virtualization: kvm host
I0126 14:43:13.875213   32134 out.go:176] 😄  minikube v1.25.1 on Debian parrot
W0126 14:43:13.875276   32134 out.go:241] ❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
W0126 14:43:13.875328   32134 preload.go:294] Failed to list preload files: open /home/user/.minikube/cache/preloaded-tarball: no such file or directory
I0126 14:43:13.875365   32134 notify.go:174] Checking for updates...
I0126 14:43:13.875848   32134 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.1
W0126 14:43:13.876538   32134 out.go:241] ❗  Deleting existing cluster minikube with different driver docker due to --delete-on-failure flag set by the user. 
I0126 14:43:13.878364   32134 out.go:176] 
W0126 14:43:13.878472   32134 out.go:241] 💢  Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "docker" driver, which is incompatible with requested "hyperv" driver.
W0126 14:43:13.878578   32134 out.go:241] 💡  Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=docker'

*

**Comment by klaases** [comment]
Hi @manyfacegod, are you using the "--force" with delete?

**Comment by klaases** [comment]
Hi @manyfacegod – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
