### ISSUE TITLE
Bump Docker to v1.11

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#135]
Ref https://github.com/kubernetes/kubernetes/issues/25893

To do this:
* Bump this [value](https://github.com/kubernetes/minikube/blob/master/deploy/iso/Dockerfile#L20)
* Download Docker 1.11 and calculate the SHA, change this value [here](https://github.com/kubernetes/minikube/blob/master/deploy/iso/Dockerfile#L21)
* Take special note of this [comment](https://github.com/kubernetes/minikube/blob/master/deploy/iso/Dockerfile#L35)
* Build and test a new iso with these [instructions](https://github.com/kubernetes/minikube/blob/master/deploy/iso/README.md).
* Release the ISO.

**Comment by luxas** [comment]
But does latest k8s support docker 1.11 yet?
They're testing it, but it might have some issues at the moment...

**Comment by dlorenc** [comment]
It looks like the PR to switch to 1.11.1 in the GCE Container VM is merged, but we can hold off another week here.

**Comment by dlorenc** [comment]
Fixed with #161
