### ISSUE TITLE
"minikube tunnel" - throwing "Client.Timeout exceeded while awaiting headers"

### ISSUE THREAD

**Issue by JustinT01** [kubernetes/minikube#13505]
Hi,

I am using minikube **version 1.2.0**  _(as I eventually want to run Keptn and Keptn as of now only supports v1.2.0)_ and when I try to run `minikube tunnel` after `minikube start `command it throws: 

`loadbalancer emulator: Get https://192.168.56.170:8443/api/v1/services?timeout=1s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

just before the above error, it also logs :

```
W0119 00:22:52.466848   19834 route.go:56] overlapping CIDR detected in routing table with minikube tunnel (CIDR: 10.96.0.0/12). It is advisable to remove these rules:

8/5                100.64.0.1         UGSc         utun2       
10.96/14           100.64.0.1         UGSc         utun2       
10.101.20.112      100.64.0.1         UGHS         utun2
```

I tried deleting the route manually but that didn't solve the issue. Anyone has any idea how to get around this issue?.

Thanks.

**Comment by sharifelgamal** [comment]
What OS/driver combo are you using? I'm sure you do realize that minikube v1.2.0 is quite old (3 years old, in fact), so it's going to be difficult to help debug.

**Comment by JustinT01** [comment]
> What OS/driver combo are you using? I'm sure you do realize that minikube v1.2.0 is quite old (3 years old, in fact), so it's going to be difficult to help debug.

OS = `macOS BigSur (11.6)`
driver = `virtualbox`

**Comment by klaases** [comment]
Hi @[JustinT01](https://github.com/JustinT01), could you help us understand your use case for Keptn in a little more detail?

I checked the following [support documentation from Keptn](https://keptn.sh/docs/0.9.x/operate/k8s_support/), but not see a specific limitation for minikube version.

Additionally (if possible) would you mind updating to a more recent version of minikube? Our resources are limited in terms of debugging prior minikube releases.

**Comment by klaases** [comment]
Hi @[JustinT01](https://github.com/JustinT01) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
