### ISSUE TITLE
Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed to start host: boot lock: unable to open /tmp/juju-mke11f63b5835bf422927bf558fccac7a21a838f: permission denied

### ISSUE THREAD

**Issue by naseercs91** [kubernetes/minikube#13502]
### What Happened?

When I start K8S with minikube over my local ubuntu 20.04 LTS with the command $ minikube start --force --driver=docker (I user --driver=docker unless I use minikube start will not work for me) 
Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed to start host: boot lock: unable to open /tmp/juju-mke11f63b5835bf422927bf558fccac7a21a838f: permission denied
can you guys please help me to fix the issue permanently I used $ sudo sysctl fs.protected_regular=0 also but still the issue remains same. 

### Attach the log file

stderr:
error: failed to create clusterrolebinding: clusterrolebindings.rbac.authorization.k8s.io "minikube-rbac" already exists

❌  Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed kubeconfig update: unable to acquire lock for {Name:mk19004591210340446308469f521c5cfa3e1599 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}: unable to open /tmp/juju-mk19004591210340446308469f521c5cfa3e1599: permission denied
💡  Suggestion: Run 'sudo sysctl fs.protected_regular=0', or try a driver which does not require root, such as '--driver=docker'
🍿  Related issue: https://github.com/kubernetes/minikube/issues/6391

### Operating System

Ubuntu

### Driver

Docker

**Comment by sharifelgamal** [comment]
Hey @naseercs91, is there any reason you're running `--force`? There's clearly some sort of permissions issues happening but it's not clear what's happening based on the info provided. 

If it is still happening (both with and without `--force`), please run `minikube logs --file=logs.txt` and upload the contents of logs.txt here.

**Comment by Ameer-clk** [comment]
I have the same issue also.When i first start minikube  using minikube start --force --driver=docker it worked.After i stopped it and the again tos start it it showing this same error
