### ISSUE TITLE
Image load fails to overwrite existing image with same tag when container is using image

### ISSUE THREAD

**Issue by SteveCurran** [kubernetes/minikube#13511]
### What Happened?

We build our images locally and use image load to push the image into minikube when developing and debugging. This avoids the slow process of copying the huge build context over to minikube and building there. We also use a local container in minikube as the registry. When i use image load it does not overwrite the existing image when I have a container currently using it running in minikube. If I delete the deployment and stop the container the image load overwrites. When running image unload/rm while running a container using the image I get the error "Error response from daemon: conflict: unable to remove repository reference "some-image" (must force)". 

However, if I build the same image in minikube it overwrites it. 

I was hoping to achieve and easier build/run/debug scenario by building locally, image load, image push and restart the container and have the new image pull (ImagePullAlways). However this only works when building in minikube and pushing in minikube. 

Using version 1.25.1

### Attach the log file

nothing in the logs

### Operating System

Windows

### Driver

Docker

**Comment by afbjorklund** [comment]
I think this an "optimization" in the scp layer, it doesn't overwrite an image (such as a .tar) when one already exists.

Seems like the problem here is that "build" moves the tag, where as "load" refuses to move the tag if it is running ?

**Comment by SteveCurran** [comment]
@afbjorklund docker 20.10.12

**Comment by Airblader** [comment]
We are running into the same issue, it seems. In our case we are trying to use this for a local development setup where the image is built and then pushed into minikube. Due to the still running deployment, that seems to silently just not work – same thing here: if I scale the Deployment to 0, rm the image, load it again, and scale it back up, everything appears to work.

I would expect that running `image load --overwrite` would actually overwrite.

**Comment by klaases** [comment]
> _Edit:_ We are working around this issue now by building in minikube directly.

Hi @SteveCurran, are you able to build in minikube directly as suggested above?

/triage needs-information
/kind support

**Comment by alexbrand** [comment]
This continues to be an issue and is causing surprising behavior.

/reopen
