### ISSUE TITLE
minikube v 1.25 dose not save resources after reboot

### ISSUE THREAD

**Issue by daviduash** [kubernetes/minikube#13519]
### What Happened?

minikube version 1.25 dose not save k8s resources after reboot (or service restart)

### Attach the log file

Non

### Operating System

Ubuntu

**Comment by mingsoap** [comment]
i come across this issue as well after update to v1.25

**Comment by wajda** [comment]
It looks like it's the same issue as #13503

**Comment by klaases** [comment]
Hi, @daviduash, this is fixed in minikube v1.25.2. Please take a moment to update your minikube installation to the latest version.
