### ISSUE TITLE
Unable to add istio addon from CLI

### ISSUE THREAD

**Issue by OscarAlmgren** [kubernetes/minikube#13536]
### What Happened?

Following the regular handbook/tutorials at [https://minikube.sigs.k8s.io/docs/handbook/deploying/](https://minikube.sigs.k8s.io/docs/handbook/deploying/) and trying out the command `minikube addons enable istio` results in a process exit. 

Does this addon require additional pre-configuration or is it not installed in the correct way using this command?

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/7978564/logs.txt)
[minikube_addons_3fdeb35888061502f4ce4fb5e947f9901a37fed2_0.log](https://github.com/kubernetes/minikube/files/7978569/minikube_addons_3fdeb35888061502f4ce4fb5e947f9901a37fed2_0.log)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by presztak** [comment]
Hello @OscarAlmgren,

I think that you don't have `IstioOperator` resource defined, so you should run first:

`minikube addons enable istio-provisioner`

and then:

`minikube addons enable istio`

as described here:  https://github.com/kubernetes/minikube/blob/master/deploy/addons/istio/README.md

Please note that istio addon was broken for a long time and it was fixed here: #13521
