### ISSUE TITLE
Minikube mount does not work. (Windows 10 / Hyper-v)

### ISSUE THREAD

**Issue by yjanjar** [kubernetes/minikube#13535]
### What Happened?

The mount operation from the VM to my local host get denied, having a running minikube VM I run: 

`minikube mount  ${PWD}:/test --alsologtostderr`

I0201 13:09:30.333464    6124 out.go:297] Setting OutFile to fd 92 ...
I0201 13:09:30.339727    6124 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0201 13:09:30.340282    6124 out.go:310] Setting ErrFile to fd 96...
I0201 13:09:30.347935    6124 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0201 13:09:30.356538    6124 mustload.go:65] Loading cluster: minikube
I0201 13:09:30.357586    6124 config.go:176] Loaded profile config "minikube": Driver=hyperv, ContainerRuntime=docker, KubernetesVersion=v1.23.1
I0201 13:09:30.363978    6124 main.go:130] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0201 13:09:30.812670    6124 main.go:130] libmachine: [stdout =====>] : Running

I0201 13:09:30.812670    6124 main.go:130] libmachine: [stderr =====>] :
I0201 13:09:30.813703    6124 host.go:66] Checking if "minikube" exists ...
I0201 13:09:30.822554    6124 ip.go:159] getIPForInterface: searching for "vEthernet (Default Switch)"
I0201 13:09:30.832434    6124 ip.go:173] "Ethernet 2" does not match prefix "vEthernet (Default Switch)"
I0201 13:09:30.832965    6124 ip.go:173] "Ethernet" does not match prefix "vEthernet (Default Switch)"
I0201 13:09:30.837500    6124 ip.go:173] "Ethernet 3" does not match prefix "vEthernet (Default Switch)"
I0201 13:09:30.838049    6124 ip.go:168] found prefix matching interface for "vEthernet (Default Switch)": "vEthernet (Default Switch)"
I0201 13:09:30.838602    6124 ip.go:194] Found interface: {Index:24 MTU:1500 Name:vEthernet (Default Switch) HardwareAddr:00:15:5d:86:4d:61 Flags:up|broadcast|multicast}
I0201 13:09:30.846605    6124 ip.go:197] interface addr: fe80::3d5e:e536:4b0d:9dfb/64
I0201 13:09:30.847114    6124 ip.go:197] interface addr: 172.18.112.1/20
I0201 13:09:30.857541    6124 out.go:176] * Mounting host path C:\Users\Janjar\Documents\test_mount into VM as /test ...
* Mounting host path C:\Users\Janjar\Documents\test_mount into VM as /test ...
I0201 13:09:30.861211    6124 out.go:176]   - Mount type:
  - Mount type:
I0201 13:09:30.870364    6124 out.go:176]   - User ID:      docker
  - User ID:      docker
I0201 13:09:30.874060    6124 out.go:176]   - Group ID:     docker
  - Group ID:     docker
I0201 13:09:30.878809    6124 out.go:176]   - Version:      9p2000.L
  - Version:      9p2000.L
I0201 13:09:30.885959    6124 out.go:176]   - Message Size: 262144
  - Message Size: 262144
I0201 13:09:30.889972    6124 out.go:176]   - Options:      map[]
  - Options:      map[]
I0201 13:09:30.901480    6124 out.go:176]   - Bind Address: 172.18.112.1:61495
  - Bind Address: 172.18.112.1:61495
I0201 13:09:30.902033    6124 ssh_runner.go:195] Run: /bin/bash -c "[ "x$(findmnt -T /test | grep /test)" != "x" ] && sudo umount -f /test || echo "
I0201 13:09:30.902608    6124 main.go:130] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0201 13:09:30.905997    6124 out.go:176] * Userspace file server:
* Userspace file server: ufs starting
I0201 13:09:31.330192    6124 main.go:130] libmachine: [stdout =====>] : Running

I0201 13:09:31.330192    6124 main.go:130] libmachine: [stderr =====>] :
I0201 13:09:31.339304    6124 main.go:130] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0201 13:09:31.958857    6124 main.go:130] libmachine: [stdout =====>] : 172.18.123.148

I0201 13:09:31.959394    6124 main.go:130] libmachine: [stderr =====>] :
I0201 13:09:31.962540    6124 sshutil.go:53] new ssh client: &{IP:172.18.123.148 Port:22 SSHKeyPath:C:\Users\Janjar\.minikube\machines\minikube\id_rsa Username:docker}
I0201 13:09:32.052340    6124 ssh_runner.go:235] Completed: /bin/bash -c "[ "x$(findmnt -T /test | grep /test)" != "x" ] && sudo umount -f /test || echo ": (1.1497314s)
I0201 13:09:32.052340    6124 mount.go:168] unmount for /test ran successfully
I0201 13:09:32.053715    6124 ssh_runner.go:195] Run: /bin/bash -c "sudo mkdir -p /test"
I0201 13:09:32.067709    6124 ssh_runner.go:195] Run: /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61495,trans=tcp,version=9p2000.L 172.18.112.1 /test"
I0201 13:10:04.080543    6124 ssh_runner.go:235] Completed: /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61495,trans=tcp,version=9p2000.L 172.18.112.1 /test": (32.0089354s)
I0201 13:10:04.087120    6124 out.go:176]

W0201 13:10:04.092604    6124 out.go:241] X Exiting due to GUEST_MOUNT_COULD_NOT_CONNECT: /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61495,trans=tcp,version=9p2000.L 172.18.112.1 /test": Process exited with status 32
stdout:

stderr:
mount: /test: mount(2) system call failed: Connection timed out.

X Exiting due to GUEST_MOUNT_COULD_NOT_CONNECT: /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61495,trans=tcp,version=9p2000.L 172.18.112.1 /test": Process exited with status 32
stdout:

stderr:
mount: /test: mount(2) system call failed: Connection timed out.

W0201 13:10:04.093711    6124 out.go:241] * Suggestion:

    If the host has a firewall:

    1. Allow a port through the firewall
    2. Specify "--port=<port_number>" for "minikube mount"
* Suggestion:

    If the host has a firewall:

    1. Allow a port through the firewall
    2. Specify "--port=<port_number>" for "minikube mount"
W0201 13:10:04.094306    6124 out.go:241] *
*
W0201 13:10:04.097542    6124 out.go:241] ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                            │
│    * If the above advice does not help, please let us know:                                                │
│      https://github.com/kubernetes/minikube/issues/new/choose                                              │
│                                                                                                            │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                   │
│    * Please also attach the following file to the GitHub issue:                                            │
│    * - C:\Users\Janjar\AppData\Local\Temp\minikube_mount_b5c50d5cac360a063211ec0cd2ed0a5f03260735_0.log    │
│                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                            │
│    * If the above advice does not help, please let us know:                                                │
│      https://github.com/kubernetes/minikube/issues/new/choose                                              │
│                                                                                                            │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                   │
│    * Please also attach the following file to the GitHub issue:                                            │
│    * - C:\Users\Janjar\AppData\Local\Temp\minikube_mount_b5c50d5cac360a063211ec0cd2ed0a5f03260735_0.log    │
│                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
I0201 13:10:04.101285    6124 out.go:176]

When running the mount command specify the IP of the minikube VM (result of minikube ip):

`minikube mount  ${PWD}:/test --alsologtostderr --ip 172.18.123.148`

I0201 13:16:23.799214   18008 out.go:297] Setting OutFile to fd 92 ...
I0201 13:16:23.800645   18008 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0201 13:16:23.800645   18008 out.go:310] Setting ErrFile to fd 96...
I0201 13:16:23.800645   18008 out.go:344] TERM=,COLORTERM=, which probably does not support color
I0201 13:16:23.808485   18008 mustload.go:65] Loading cluster: minikube
I0201 13:16:23.809033   18008 config.go:176] Loaded profile config "minikube": Driver=hyperv, ContainerRuntime=docker, KubernetesVersion=v1.23.1
I0201 13:16:23.809582   18008 main.go:130] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0201 13:16:24.250288   18008 main.go:130] libmachine: [stdout =====>] : Running

I0201 13:16:24.250288   18008 main.go:130] libmachine: [stderr =====>] :
I0201 13:16:24.250942   18008 host.go:66] Checking if "minikube" exists ...
I0201 13:16:24.257418   18008 out.go:176] * Mounting host path C:\Users\Janjar\Documents\test_mount into VM as /test ...
* Mounting host path C:\Users\Janjar\Documents\test_mount into VM as /test ...
I0201 13:16:24.261047   18008 out.go:176]   - Mount type:
  - Mount type:
I0201 13:16:24.264050   18008 out.go:176]   - User ID:      docker
  - User ID:      docker
I0201 13:16:24.266915   18008 out.go:176]   - Group ID:     docker
  - Group ID:     docker
I0201 13:16:24.270113   18008 out.go:176]   - Version:      9p2000.L
  - Version:      9p2000.L
I0201 13:16:24.273319   18008 out.go:176]   - Message Size: 262144
  - Message Size: 262144
I0201 13:16:24.274362   18008 out.go:176]   - Options:      map[]
  - Options:      map[]
I0201 13:16:24.278162   18008 out.go:176]   - Bind Address: 172.18.123.148:61524
  - Bind Address: 172.18.123.148:61524
I0201 13:16:24.280299   18008 ssh_runner.go:195] Run: /bin/bash -c "[ "x$(findmnt -T /test | grep /test)" != "x" ] && sudo umount -f /test || echo "
I0201 13:16:24.280299   18008 main.go:130] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0201 13:16:24.285539   18008 out.go:176] * Userspace file server:
* Userspace file server: ufs starting
I0201 13:16:24.291368   18008 main.go:116] stdlog: ufs.go:27 listen tcp 172.18.123.148:61524: bind: The requested address is not valid in its context.
I0201 13:16:24.294738   18008 out.go:176] * Userspace file server is shutdown
* Userspace file server is shutdown
I0201 13:16:24.707150   18008 main.go:130] libmachine: [stdout =====>] : Running

I0201 13:16:24.707150   18008 main.go:130] libmachine: [stderr =====>] :
I0201 13:16:24.709381   18008 main.go:130] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0201 13:16:25.323331   18008 main.go:130] libmachine: [stdout =====>] : 172.18.123.148

I0201 13:16:25.323331   18008 main.go:130] libmachine: [stderr =====>] :
I0201 13:16:25.332163   18008 sshutil.go:53] new ssh client: &{IP:172.18.123.148 Port:22 SSHKeyPath:C:\Users\Janjar\.minikube\machines\minikube\id_rsa Username:docker}
I0201 13:16:25.417710   18008 ssh_runner.go:235] Completed: /bin/bash -c "[ "x$(findmnt -T /test | grep /test)" != "x" ] && sudo umount -f /test || echo ": (1.1374111s)
I0201 13:16:25.417710   18008 mount.go:168] unmount for /test ran successfully
I0201 13:16:25.418809   18008 ssh_runner.go:195] Run: /bin/bash -c "sudo mkdir -p /test"
I0201 13:16:25.431298   18008 ssh_runner.go:195] Run: /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61524,trans=tcp,version=9p2000.L 172.18.123.148 /test"
I0201 13:16:25.444107   18008 out.go:176]

W0201 13:16:25.444107   18008 out.go:241] X Exiting due to GUEST_MOUNT: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61524,trans=tcp,version=9p2000.L 172.18.123.148 /test" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61524,trans=tcp,version=9p2000.L 172.18.123.148 /test": Process exited with status 32
stdout:

stderr:
mount: /test: mount(2) system call failed: Connection refused.

X Exiting due to GUEST_MOUNT: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61524,trans=tcp,version=9p2000.L 172.18.123.148 /test" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61524,trans=tcp,version=9p2000.L 172.18.123.148 /test": Process exited with status 32
stdout:

stderr:
mount: /test: mount(2) system call failed: Connection refused.

W0201 13:16:25.445159   18008 out.go:241] *
*
W0201 13:16:25.448047   18008 out.go:241] ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                            │
│    * If the above advice does not help, please let us know:                                                │
│      https://github.com/kubernetes/minikube/issues/new/choose                                              │
│                                                                                                            │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                   │
│    * Please also attach the following file to the GitHub issue:                                            │
│    * - C:\Users\Janjar\AppData\Local\Temp\minikube_mount_b5c50d5cac360a063211ec0cd2ed0a5f03260735_0.log    │
│                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                            │
│    * If the above advice does not help, please let us know:                                                │
│      https://github.com/kubernetes/minikube/issues/new/choose                                              │
│                                                                                                            │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                   │
│    * Please also attach the following file to the GitHub issue:                                            │
│    * - C:\Users\Janjar\AppData\Local\Temp\minikube_mount_b5c50d5cac360a063211ec0cd2ed0a5f03260735_0.log    │
│                                                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
I0201 13:16:25.458019   18008 out.go:176]

I added the IP range of the VM to my inbound rules of the firewall to allow the connection and the problem persists. I would really appreciate some assistance here.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/7978307/logs.txt)
[minikube_mount_b5c50d5cac360a063211ec0cd2ed0a5f03260735_0.log](https://github.com/kubernetes/minikube/files/7978314/minikube_mount_b5c50d5cac360a063211ec0cd2ed0a5f03260735_0.log)

### Operating System

Windows

### Driver

Hyper-V

**Comment by jatinTyagi98** [comment]
I am new to kubernetes , can I contribute to this issue ?

**Comment by yjanjar** [comment]
Go ahead any help is welcomed.

**Comment by jatinTyagi98** [comment]
@yjanjar can you please tell me whether the issue is in the connection to hyper v or in the minikube logs command ? This would help me clarify the issues more.

**Comment by yjanjar** [comment]
@jatinTyagi98 the issue is in the minikube mount like you can see in the post right:

W0201 13:16:25.444107 18008 out.go:241] X Exiting due to GUEST_MOUNT: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61524,trans=tcp,version=9p2000.L 172.18.123.148 /test" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=61524,trans=tcp,version=9p2000.L 172.18.123.148 /test": Process exited with status 32
stdout:

stderr:
mount: /test: mount(2) system call failed: Connection refused.

The mount command is not getting throught.

**Comment by jatinTyagi98** [comment]
ok . I'll try my best to solve it.

**Comment by klaases** [comment]
Hi @jatinTyagi98, are you still working on this issue?

Additionally, @yjanjar – did you have a chance to review @spowelljr's suggestion above?

Is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
