### ISSUE TITLE
kubelet.service: Main process exited, code=exited, status=203/EXEC

### ISSUE THREAD

**Issue by abdekwant** [kubernetes/minikube#13537]
### What Happened?

My apologies. Perhaps a newbie mistake ... but I can't figure out why I can't get minikube started. Spend hours on trying to find the root cause / my error. Perhaps someone with more experience can see the issue quickly or point me in the right direction.
After: install kubectl and install minikube I can't get "minikube start --driver=none" to successfully complete. Kubelet service seems to fail with 203/EXEC.
I have also tried to delete minikube, download and install again. All with the same result.
Attached output of: 
- minikube logs
- journalctl -xeu kubelet
- systemctl status kubelet

After a "minikube start --driver=none --alsologtostderr -v=5"

Environment:
- ESXi server (6.5.0 U2)
- VM with CentOS Stream 8 (2 cpu 4GB mem)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/7980318/logs.txt)
[journal.txt](https://github.com/kubernetes/minikube/files/7980320/journal.txt)
[status.txt](https://github.com/kubernetes/minikube/files/7980321/status.txt)

### Operating System

Other

### Driver

None

**Comment by klaases** [comment]
Hi @abdekwant, is there a specific reason for using `--driver=none`?

Using `--driver=none`:
- Would generally need to be run as root.
- Would be running minikube on bare metal.

It is not advised to use `--driver=none`, would you be able to try with the default driver?
