### ISSUE TITLE
[Bug] Netfilter is slowing down all traffic (needlessly)

### ISSUE THREAD

**Issue by dalehamel** [kubernetes/minikube#1353]
BUG REPORT

**Minikube version** (use `minikube version`):

All versions

**Environment**:
- **OS** (e.g. from /etc/os-release): Any OS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Any VM driver
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): Any ISO version
- **Install tools**:
- **Others**:

**What happened**:

All traffic is being significantly slowed down by netfilter. Netfilter is necessary in order for kubernetes to create service proxies (using either iptables or userspace mode).

**Note**: This only applies to traffic originating from outside of the localkube VM (ie, the host). Traffic within the VM should all go over the loopback interface, and be relatively speedy.

**What you expected to happen**:

Only traffic requiring NAT (service addresses) should be slow.

**How to reproduce it** (as minimally and precisely as possible):

Create a custom VM image that prevents docker and localkube from automatically starting on boot.

To benchmark the network performance, I've just been using a very terse `redis-benchmark`, but `iperf` will do the job as well. 

* Benchmark the performance with either tool (if using redis, install redis-server in the VM to be able to bench against it) from the host to the VM.
* Start localkube or docker, or just run `iptables -L -t nat` to force the iptables NAT modules to get loaded
* Run the benchmark again

You should see that as soon as iptables loads the NAT modules, you take approximately a 30% network performance hit. This is because all traffic is being subjected to netfilter processing.

**Anything else do we need to know**:

In a custom image, I have enabled the kernel option `CONFIG_IP_NF_RAW=m` to support the raw iptables.

Using this, we can tell netfilter to completely bypass any traffic that does not specifically require the special NAT processing:

```
iptables -t raw -A PREROUTING -m iprange --dst-range 10.0.0.0-10.0.0.255 -j ACCEPT
iptables -t raw -A PREROUTING -j NOTRACK
```

(assuming `10.0.0.0/24' is the SERVICE_CIDR)

This should allow for all non-service traffic to continue to be fast, while only service traffic (which actually needs NAT) will be slowed down by the additional processing.

It's a relatively simple fix. At the very least, including `CONFIG_IP_NF_RAW=m` in the kernel would be nice, so that users can opt-in to this if they want to.

Right now I'm using a custom image, because the performance penalty here is prohibitive to our use case.

**Comment by dalehamel** [comment]
To illustrate my point, here is an example showing the performance implications for redis using redis-benchmark (which establishes a lot of connections, and is a good real-world test):


Stock minikube, running a simple redis config using host networking:

```
redis-benchmark -h $(minikube ip) --csv
"PING_INLINE","29542.10"
"PING_BULK","28465.70"
"SET","30385.90"
"GET","19267.82"
"INCR","24032.69"
"LPUSH","24900.40"
"RPUSH","25056.38"
"LPOP","29498.52"
"RPOP","31308.70"
"SADD","22794.62"
"SPOP","25361.40"
"LPUSH (needed to benchmark LRANGE)","28336.64"
"LRANGE_100 (first 100 elements)","13101.01"
"LRANGE_300 (first 300 elements)","9196.25"
"LRANGE_500 (first 450 elements)","6372.27"
"LRANGE_600 (first 600 elements)","3937.32"
"MSET (10 keys)","17091.10"
```

I then apply my change (note: https://github.com/kubernetes/minikube/issues/1355 is required for this, and a custom image built):

```
iptables -t raw -A PREROUTING -m iprange --dst-range 10.0.0.0-10.0.0.255 -j ACCEPT
iptables -t raw -A PREROUTING -j NOTRACK
``` 

There is a **significant** improvement in performance, as now these connections can bypass conntrack completely:

```
redis-benchmark -h $(minikube ip) --csv
"PING_INLINE","39323.63"
"PING_BULK","38729.67"
"SET","38343.56"
"GET","35727.05"
"INCR","37735.85"
"LPUSH","37721.61"
"RPUSH","37091.99"
"LPOP","37327.36"
"RPOP","38774.72"
"SADD","38505.97"
"SPOP","36589.83"
"LPUSH (needed to benchmark LRANGE)","37425.15"
"LRANGE_100 (first 100 elements)","20639.84"
"LRANGE_300 (first 300 elements)","9475.98"
"LRANGE_500 (first 450 elements)","6343.57"
"LRANGE_600 (first 600 elements)","4990.77"
"MSET (10 keys)","35410.77"
```

Note that connections to the service IP address are still slow, but accessing the backend directly as above is quite speedy.

The first rule allows for service addresses to still go through conntrack, and the second one says everything else can avoid it.

I confirmed service that service IPs still work.

In my case, I exposed them to my host (on OS X):

```
sudo route -n add 10.0.0.1/24 $(minikube ip)
sudo ifconfig bridge100 -hostfilter en26 # needed for xhyve driver, which I'm using for testing
```

And I can still connect to redis:

```
telnet 10.0.0.254 6379 # redis service address
```

But the speed for this address is, of course, slower:

```
redis-benchmark -h 10.0.0.254 --csv
"PING_INLINE","31476.23"
"PING_BULK","31705.77"
"SET","32175.03"
"GET","32669.06"
"INCR","33478.41"
"LPUSH","31836.99"
"RPUSH","30293.85"
"LPOP","27034.33"
"RPOP","27472.53"
"SADD","30111.41"
"SPOP","30892.80"
"LPUSH (needed to benchmark LRANGE)","30220.61"
"LRANGE_100 (first 100 elements)","18419.60"
"LRANGE_300 (first 300 elements)","8862.89"
"LRANGE_500 (first 450 elements)","5610.41"
"LRANGE_600 (first 600 elements)","4801.46"
"MSET (10 keys)","30740.85"
```

**Comment by dlorenc** [comment]
I think we can close this now that #1355 was merged.
