### ISSUE TITLE
Minikube lost everything

### ISSUE THREAD

**Issue by zasboth** [kubernetes/minikube#13543]
### What Happened?

When I restart my Linux every deployment, service etc. disappear like when I make "minikube delete"
 
Env:
Hyper-v
Ubuntu 21.10
64 bit
docker
minikube version: v1.25.1
commit: 3e64b11ed75e56e4898ea85f96b2e4af0301f43d

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/7983805/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by mor-cybellum** [comment]
Also happened to me, I downgraded to version 1.24.0 and it doesn't produce so I'm guessing it is a new version kind of issue.
My environment:
WSL through windows 11, ubuntu 20.04
minikube version: 1.25.1
driver: docker

**Comment by MrCreeper2033** [comment]
Same Issue here. 
My enviroment:
Centos 7
docker
minikube version: v1.25.1

**Comment by lmanzke** [comment]
Same issue here.

Kernel: 5.16.5-1-MANJARO
docker
minikube 1.25.1

Downgrading minikube to 1.24.0 fixes the issue.

Easiest reproduction steps I could find:
Start minikube 1.25.1
Create any namespace 
minikube stop
minikube start (btw, consider a restart command)

-> Namespace you created is gone

**Comment by Commifreak** [comment]
[#13552](https://github.com/kubernetes/minikube/issues/13552)

**Comment by spowelljr** [comment]
As @Commifreak noted, this has been resolved and will be included in the next release.

You can get binaries with the fix from https://github.com/kubernetes/minikube/issues/13503#issuecomment-1026257723

I'm going to close this issue, but if you feel free to respond if you have any further questions, thanks!
