### ISSUE TITLE
Minikube doesn't save its state after being stopped

### ISSUE THREAD

**Issue by a-mazed** [kubernetes/minikube#13552]
### What Happened?

Hello everyone
I have a problem with Minikube.
After I exit Minikube all my pods are gone. What is the issue? 
See screenshot below
![image](https://user-images.githubusercontent.com/25726917/152338492-d58651da-1869-4aab-bbff-d0bc7cd863eb.png)

As far as I understand, command stop should save my data
`This command stops the underlying VM or container, but keeps user data intact.`
But I lost it every time.

My config:
WSL2 with Ubuntu 20.04.3 LTS
Docker driver
minikube version: v1.25.1
commit: 3e64b11ed75e56e4898ea85f96b2e4af0301f43d

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/7994323/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by Guillaume-Mayer** [comment]
You have to downgrade to 1.24 or use the corrected binary, see https://github.com/kubernetes/minikube/issues/13503#issuecomment-1026257723

**Comment by a-mazed** [comment]
Oh, that's the point
I'm new with Minikube - this is my first install 

Ok, this issue can be closed then
