### ISSUE TITLE
minikube issues

### ISSUE THREAD

**Issue by ugyen1998** [kubernetes/minikube#13559]
### What Happened?

Tried to start the minikube but i am not able to load all the data. It gets stopped in between. what might be the possible solution for that.

### Attach the log file

PS D:\course\Networking\Kubernetes\voting-app> minikube start --driver=virtualbox
😄  minikube v1.24.0 on Microsoft Windows 11 Home Single Language 10.0.22000 Build 22000    
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running virtualbox "minikube" VM ...

### Operating System

Windows

### Driver

VirtualBox

**Comment by jatinTyagi98** [comment]
check if your hyper v is enable that can create a conflict with virtual box. If that's the case you  need to uncheck your hyper v or you can use hyper v as a driver.

**Comment by ugyen1998** [comment]
Thank you
