### ISSUE TITLE
minikube running on ssh session with podman driver

### ISSUE THREAD

**Issue by karegoie** [kubernetes/minikube#13569]
### What Happened?

[error.txt](https://github.com/kubernetes/minikube/files/8013264/error.txt)

On ssh terminal, my minikube does not works fluently. Is there other ways to use minikube on ssh session?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8013265/log.txt)

### Operating System

Ubuntu

### Driver

Podman

**Comment by spowelljr** [comment]
Hi @karegoie, thanks for reporting your issue with minikube!

Is the output of `error.txt` from `minikube dashboard`? And is that the command you're having difficulty with? Or there other things as well?

**Comment by klaases** [comment]
Hi @[karegoie](https://github.com/karegoie)– were you able to review Steven's comments above?

Also, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
