### ISSUE TITLE
Minikube Fails to Start with Podman Driver on Fedora 35

### ISSUE THREAD

**Issue by djnotes** [kubernetes/minikube#13565]
### What Happened?

I installed Minikube using Homebrew on Fedora 35. Then, tried to start minikube with Podman driver (no other driver was installed):  

```
minikube start
😄  minikube v1.25.1 on Fedora 35
✨  Automatically selected the podman driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0206 04:58:04.136487   16556 cache.go:203] Error downloading kic artifacts:  not yet implemented, see issue #8426
🔥  Creating podman container (CPUs=2, Memory=3900MB) ...
🤦  StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds
🔄  Restarting existing podman container for "minikube" ...
😿  Failed to start podman container. Running "minikube delete" may fix it: podman inspect ip minikube: sudo -n podman container inspect -f {{.NetworkSettings.IPAddress}} minikube: exit status 125
stdout:

stderr:
Error: error inspecting object: no such container minikube


❌  Exiting due to GUEST_PROVISION: Failed to start host: podman inspect ip minikube: sudo -n podman container inspect -f  minikube: exit status 125
stdout:

stderr:
Error: error inspecting object: no such container minikube

````
I thought maybe the issue is because I'm using the Homebrew package, so I installed the [binary from Google](https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64), and ran it again after running "minikube delete", but I got the same error. 

First, I wanted to report this as a Podman issue, but Minikube output hinted me to send it here. 
Is there something I can do to fix this or should I use another driver like VirtualBox for now? 

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8009937/log.txt)

### Operating System

Redhat/Fedora

### Driver

Podman

**Comment by sharifelgamal** [comment]
It would certainly seem like the podman container is crashing, `podman container inspect` isn't returning anything while `podman inspect` is returning very minimal information.

While I'm not a podman expert (@afbjorklund knows far more than I do), this feels like a very basic usecase and should work. If you want to try a VM driver, I'd suggest KVM.

**Comment by fuzhouch** [comment]
Hey, 

I happened to find a fix when I saw same problem on my Manjaro Linux. By debugging it seems minikube tries to create a virtual machine by calling `podman machine init --cpus=2 --memory=3900`. This command results in an error complaining `Error: exec: "qemu-system-x86_64": executable file not found in $PATH`. 

So I tried to manually install qemu first (`pacman -S qemu`, surely `dnf` should be used on Fedora) and return `minikube start --driver=podman ...`. The error disappeared and successfully launch minikube. 

@djnotes Mehdi feel free to give a shot.

**Comment by 12cew** [comment]
Should this issue be labeled as priority/awaiting-more-evidence or priority/backlog ?

We are doing research about “Issue Priority Prediction". We have developed a tool to automatically label the priority of an issue. The basic idea is to employ Bert model to encode the textual and code descriptions of the issue, and incorporate the issue’s attributes in the model, then apply multi-task learning to facilitate other information boosting the prediction performance. 
 We have conducted experiments on four GitHub projects with 21700 issues, and results show that [79% accuracy]() can be achieved.

Our tool shows that this issue has a very large possibility to be labeled as priority/awaiting-more-evidence or priority/backlog 
Could you please tell us whether it should be labeled as priority/awaiting-more-evidence or priority/backlog ?
And if you have any comments or suggestions with this tool, could you please tell us? 
Thank you so much.

**Comment by djnotes** [comment]
@fuzhouch I tried installing qemu-system-x86_64 first and then running minikube start again, but it didn't work. Error is the same as before.

**Comment by fuzhouch** [comment]
Hey, @djnotes Did you successfully create VM by running `podman machine init --cpus=2 --memory=3900` before running minikube?

Sorry for late response. Actually I also noticed the podman version minikube on my machine still has more issues when minikube shutdown. So following suggestion above I also switched to KVM2 driver. If it's not a must to use podman+minikube combination, I also suggest using KVM2 instead. (For me I don't use Docker for a study reason). I also shared my startup command below. Hopefully it helps.

```
sudo systemctl status libvertd  # make sure KVM is installed and service started.
minikube start \
    --driver=kvm2 \
    --registry-mirror=https://registry.docker-cn.com \
    --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers  # I use it for download speed-up in China.
```

**Comment by djnotes** [comment]
Hi @fuzhouch. Thank you for the snippet. I was able to create the VM using kvm2 driver.

**Comment by djnotes** [comment]
The podman driver does not work yet though

**Comment by djnotes** [comment]
/remove-lifecycle stale

This is still an ongoing issue as of 1.26.0:
[minikube_logs_b23938bbae7b811f7ec03fc58948b26b0ebbeb37_0.log](https://github.com/kubernetes/minikube/files/9247777/minikube_logs_b23938bbae7b811f7ec03fc58948b26b0ebbeb37_0.log)
