### ISSUE TITLE
apiserver stopped

### ISSUE THREAD

**Issue by vivekvishal011** [kubernetes/minikube#13573]
### What Happened?

my apiserver stop working in minikube  so tell me resons behinde and possibe solution

### Attach the log file

type: Control Plane
host: Running
kubelet: Running
apiserver: Stopped
kubeconfig: Configured

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by RA489** [comment]
@vivekvishal011 I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!
