### ISSUE TITLE
Call out in docs which minikube drivers support Apple Silicon

### ISSUE THREAD

**Issue by danielhelfand** [kubernetes/minikube#13572]
### What Happened?

I was attempting to run minikube without using Docker on an m1 mac. I eventually gave up and ended up using Docker as it seems the other options really don't support Apple silicon yet. I am assuming that Docker is the only real option at this point. All the others mentioned (i.e. VirtualBox, [hyperkit/podman](https://github.com/kubernetes/minikube/issues/13006), [vmware](https://github.com/kubernetes/minikube/issues/12858), [parallels](https://github.com/kubernetes/minikube/issues/11219)) do not seem to work at this point.

It's pretty well documented in GitHub issues that m1 support is still a WIP, but calling out in the [drivers doc](https://minikube.sigs.k8s.io/docs/drivers/#macos) about m1 support/updating over time might help users with the situation.

### Attach the log file

N/A

### Operating System

macOS (Default)

**Comment by danielhelfand** [comment]
Happy to pick this up if all the details above look right.

**Comment by afbjorklund** [comment]
Both vmware and parallels are supposed to work, but you also need an ISO that supports arm64.

However, hyperkit will not work so we need to resurrect the "qemu" driver and use that instead.

**Comment by afbjorklund** [comment]
Docker is still the "preferred" driver and "default" runtime.

**Comment by danielhelfand** [comment]
@afbjorklund  Appreciate you filling me in on the state of things. Let me try to distill some of this information into some minor doc edits.

**Comment by afbjorklund** [comment]
Not sure about Podman support, maybe revisit once Podman Desktop 4.0.0 is out and once it has been tested ?

* https://github.com/kubernetes/minikube/issues/8003

As far as I will know, it will **not** feature Kubernetes (like Docker Desktop or Rancher Desktop), you need CRC.

* https://developers.redhat.com/products/codeready-containers

**Comment by afbjorklund** [comment]
Users are _supposed_ to be able to find out their OS ("Darwin") and Arch ("aarch64"), in order to install binaries.

It would be nice if we used similiar wording here, even though it is fine to call it macOS and arm64 of course.

"Apple silicon" this, "Intel silicon" that.

Preferrably, both would be invisible.
