### ISSUE TITLE
Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /etc/kubernetes: mkdir /etc/kubernetes: permission denied

### ISSUE THREAD

**Issue by prudhvinag06** [kubernetes/minikube#13586]
### What Happened?

when I ran minikube start the following error appears every time

Failed kubeconfig update: Error reading file "/home/prudhvi/.kube/config": read /home/prudhvi/.kube/config: is a directory

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8030543/log.txt)

### Operating System

Ubuntu

###Solution:
change the name of directory config to configtemp. Because file name clashing with the config directory name.

**Comment by afgoncal** [comment]
Worked to pass that step but still failed to start cluster. Solution was to clean KUBECONFIG env variable and restart

https://github.com/kubernetes/minikube/issues/9278
