### ISSUE TITLE
minikube ip can't be used to ssh 

### ISSUE THREAD

**Issue by joaogl** [kubernetes/minikube#13598]
### What Happened?

Hello,

I have docker running on my machine pointing to a remote host by doing DOCKER_HOST=tcp://10.0.1.108:49156.
minikube is then installed on my machine and the docker running on the remote.

If I do minikube ip, I get an ip that is only reachable on the DOCKER_HOST and not my machine, but somehow if I run minikube ssh I do connect nicely to it, I'm wondering how can I find out the IP that minikube ssh is using instead of the minikube ip.

My goal was to copy a directory from my machine to the minikube but since minikube cp doesn't support folders I have to do scp and for that I need the minikube ip :/

Hopefully I wasn't too confusing.
Thanks.

### Attach the log file

user@MacBook-Pro dev-env % ping $(minikube  ip)
PING 192.168.49.2 (192.168.49.2): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @joaogl, if you run `minikube ssh` with the `--alsologtostderr` flag it will have more verbose output and will have the IP listed in the logs.

**Comment by klaases** [comment]
Hi @[joaogl](https://github.com/joaogl) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
