### ISSUE TITLE
Minikube issue

### ISSUE THREAD

**Issue by ugyen1998** [kubernetes/minikube#13594]
### What Happened?

Minikube not able to start 

### Attach the log file

  Exiting due to K8S_INSTALL_FAILED: updating control plane: copy: copy: sudo test -d /var/tmp/minikube && sudo scp -t /var/tmp/minikube: Process exited with status 1
output: �☺scp: /var/tmp/minikube/kubeadm.yaml.new: Read-only file system
☺scp: protocol error: expected control record

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by ugyen1998** [comment]
Thank you

Ugyen Tshomo

OJT, Trainee || NDI

GCIT, 2021 Cohort

***@***.***

17817754

**Comment by spowelljr** [comment]
Hi @ugyen1998, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
