### ISSUE TITLE
`ServiceNodePortRange` config no longer recognised

### ISSUE THREAD

**Issue by georgecrawford** [kubernetes/minikube#1359]
**Minikube version** `v0.18.0`

**Environment**:
- **OS** `OS X 10.12.4 (16E195)`
- **VM Driver** `xhyve` (also a problem with `virtualbox`)
- **ISO version** `minikube-v0.18.0.iso`
- **Install tools**:
- **Others**:

**What happened**:

Until recently, I could start minkube with `--extra-config=apiserver.GenericServerRunOptions.ServiceNodePortRange=1-50000` and expose a service as a NodePort on port 80. Worked great. In minikube 0.18.0, this param no longer seems to be recognised: 
```
Apr 10 21:54:17 minikube localkube[3097]: I0410 21:54:17.532142    3097 localkube.go:119] Setting GenericServerRunOptions.ServiceNodePortRange to 1-50000 on apiserver.
Apr 10 21:54:17 minikube localkube[3097]: W0410 21:54:17.532304    3097 localkube.go:121] Unable to set GenericServerRunOptions.ServiceNodePortRange to 1-50000. Error: Unable to find field by name: ServiceNodePortRange
```

**What you expected to happen**:
No errors in logs, and `NodePort` services can be assigned to any port in the selected range.

**How to reproduce it**
`minikube start --vm-driver=$DRIVER --extra-config=apiserver.GenericServerRunOptions.ServiceNodePortRange=1-50000` and then `minikube logs | grep ServiceNodePortRange` to check for errors.

**Anything else do we need to know**:

**Comment by aaron-prindle** [comment]
Can you try using `config=apiserver.ServiceNodePortRange=1-50000`?  From the documentation it seems this setting might have moved as it appears to not be under GenericServerRunOptions anymore.

**Comment by aaron-prindle** [comment]
Resolved, closing

**Comment by georgecrawford** [comment]
Yep, that's it. Many thanks @aaron-prindle. Worth linking to https://github.com/kubernetes/minikube/issues/1006.

**Comment by gsaslis** [comment]
didn't quite work for me, but good pointers here. I solved it with: 
https://github.com/kubernetes/minikube/issues/2765#issuecomment-385251422
