### ISSUE TITLE
FEATURE REQUEST: Add vxlan kernel module

### ISSUE THREAD

**Issue by tomdee** [kubernetes/minikube#1362]
FEATURE REQUEST
Would it be possible to add the vxlan module?

I'm starting to use minikube for local flannel development and I can't use the vxlan backend because (I think) the module is missing.

I'm currently using `minikube version: v0.17.1` on Arch with virtualbox

```
minikube ssh cat /etc/VERSION
v1.0.7
```

**Comment by r2d4** [comment]
Yeah, thats totally reasonable.  If you want to take a stab at adding it yourself to minikube-iso, that would be awesome.  Otherwise, one of us can get to it when we get a chance.

**Comment by djbb7** [comment]
@r2d4 would that be as simple as adding CONFIG_VXLAN to minikube/deploy/iso/minikube-iso/board/coreos/minikube/linux-4.9_defconfig ?

**Comment by r2d4** [comment]
Yeah @djbb7.  I know @dlorenc was planning to enable a few modules, so maybe this could be added to the list
