### ISSUE TITLE
Trying to start minikube using virtualbox driver but getting error (Windows 10 Home)

### ISSUE THREAD

**Issue by ErKriti** [kubernetes/minikube#13629]
### What Happened?

I have Windows 10 Home edition build 19042.
**I did below steps:**
Installed Ubuntu 18.04 (this was not working until I enabled WSL, so I enabled WSL2)

Installed kubectl and minikube in linux distro

Installed VBox Version 6.1.32 r149290 (Qt5.6.2)on Windows using .exe file available here https://www.virtualbox.org/ (CPU virualization is ON, Secure boot system is disabled in BIOS, Virtual Machine Platform and Windows Hypervisor Plaform are unchecked in Control Panel) (Somewhere I read VBox doesn't compatible with WSL2 so I downgraded WSL1)

In Ubuntu termina l ran $ minikube start --driver=virtualbox got this error
😄  minikube v1.24.0 on Ubuntu 18.04
✨  Using the virtualbox driver based on existing profile
🤷  Exiting due to PROVIDER_VIRTUALBOX_NOT_FOUND: The 'virtualbox' provider was not found: unable to find VBoxManage in $PATH
💡  Suggestion: Install VirtualBox
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

I ran $ sudo apt-get install virtualbox 
After that $ minikube start (and got this error)
[minikube_start_error.docx](https://github.com/kubernetes/minikube/files/8091850/minikube_start_error.docx)

Tried to install linux header $ sudo apt-get install linux-headers-`uname -r`
Got this error
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-4.4.0-19041-Microsoft
E: Couldn't find any package by glob 'linux-headers-4.4.0-19041-Microsoft'
E: Couldn't find any package by regex 'linux-headers-4.4.0-19041-Microsoft'

I am very new to kubernetes and virtualbox. Please help me and let me know what wrong am I doing? My aim to start minikube using virtualbox driver because the tutorial I am following to learn Kuberenetes, it's using the same tools.
Thanks.

Edit: One more thing, I am able to start minikube from windows cmd prompt but not from Ubuntu linux distro. (But want to use linux distro for kubernetes).

### Attach the log file

None

### Operating System

Windows

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Hi @ErKriti, thanks for reporting your issue with minikube!

I did some research and there are multiple blogs talking about the incompatibility of using WSL2 and VirtualBox at the same time.

https://nicolaiarocci.com/troubles-with-virtualbox-and-the-windows-subsystem-for-linux/

Have you considered using Docker Desktop?

**Comment by ErKriti** [comment]
> Hi @ErKriti, thanks for reporting your issue with minikube!
> 
> I did some research and there are multiple blogs talking about the incompatibility of using WSL2 and VirtualBox at the same time.
> 
> https://nicolaiarocci.com/troubles-with-virtualbox-and-the-windows-subsystem-for-linux/
> 
> Have you considered using Docker Desktop?

Hi @spowelljr thanks for replying. Yes, I tried using Docker desktop and it's working fine. 
I also tried disabling WSL but then Ubuntu is not working on Windows. Is there any way I can run Ubuntu linux distro without WSL on windows 10 home?

Thanks

**Comment by spowelljr** [comment]
Ubuntu runs on WSL so it makes sense disabling WSL making Ubuntu stop working. The only way to run Ubuntu otherwise would be to use a VM like VirtualBox or VMware.

**Comment by ErKriti** [comment]
> Ubuntu runs on WSL so it makes sense disabling WSL is making Ubuntu stop working. The only way to run Ubuntu otherwise would be to use a VM like VirtualBox or VMware.
> 
> You should be able to run WSL and Docker Desktop at the same time with minikube if that's what you're trying to accomplish.

Ok, Thank you so much :)

**Comment by spowelljr** [comment]
Hi @ErKriti, haven't heard back from you for a while so I'm going to close this issue. But if you have further questions feel free to respond and reopen this issue, thanks!
