### ISSUE TITLE
minikube doesn't start

### ISSUE THREAD

**Issue by thor15xxx** [kubernetes/minikube#13634]
### What Happened?

minikube start --driver=virtualbox --host-only-cidr=192.168.99.1/24 --no-vtx-check
😄  minikube v1.12.1 on Darwin 12.2.1
    ▪ KUBECONFIG=/Users/kayamatimbou028715/istio-tutorial/.kube/config
    ▪ MINIKUBE_HOME=/Users/kayamatimbou028715/istio-tutorial
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet26 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

### Attach the log file

MacBook-Pro-de-THOR:istio-tutorial kayamatimbou028715$ minikube logs --files=log.txt
Error: unknown flag: --files
See 'minikube logs --help' for usage.

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Hi @thor15xxx, thanks for reporting your issue with minikube!

If you look at our documentation page on [VirtualBox](https://minikube.sigs.k8s.io/docs/drivers/virtualbox/) you will see the following:
`VirtualBox >= 6.1.28, [only IP addresses in the 192.68.56.0/21 range are allowed for host-only networking by default](https://www.virtualbox.org/manual/ch06.html#network_hostonly). Passing a disallowed value to --host-only-cidr will result in a VirtualBox access denied error: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available).`

So if you use `--host-only-cidr 192.168.59.1/24` it should work.

**Comment by thor15xxx** [comment]
when i tried, i have same errors

MacBook-Pro-de-THOR:istio-tutorial kayamatimbou028715$ minikube start --memory=8192 --cpus=3 --kubernetes-version=v1.18.6 --vm-driver=virtualbox -p istio-devnation  --host-only-cidr 192.168.59.1/24

😄  [istio-devnation] minikube v1.12.1 on Darwin 12.2.1
    ▪ KUBECONFIG=/Users/kayamatimbou028715/istio-tutorial/.kube/config
    ▪ MINIKUBE_HOME=/Users/kayamatimbou028715/istio-tutorial
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node istio-devnation in cluster istio-devnation
🔄  Restarting existing virtualbox VM for "istio-devnation" ...
🤦  StartHost failed, but will try again: driver start: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet30 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

**Comment by erlangparasu** [comment]
@spowelljr sorry but it's not working

**Comment by spowelljr** [comment]
> @spowelljr sorry but it's not working

Hi @erlangparasu, could you open a new issue with the specifics of the error you're encountering and we can help you there, thanks!
