### ISSUE TITLE
kubelet not enabled in ubuntu.

### ISSUE THREAD

**Issue by Aashish-cyber** [kubernetes/minikube#13638]
### What Happened?

kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "minikubeCA")
after running command 'systemctl enable kubelet.service' is also not working. what should i do?

### Attach the log file

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│
                         │
│    😿  If the above advice does not help, please let us know:
                         │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose
                         │
│
                         │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│
                         │
╰──────────────────────────────────────────────────────────────────

### Operating System

Ubuntu

### Driver

Docker

**Comment by achintya-7** [comment]
Faced the same problem here as well.

**Comment by achintya-7** [comment]
So apparently I looked over the internet and found a solution that worked for me.
I had the same issue as `certificate apiserver-kubelet-client not signed by CA certificate ca`

The following command solved all these issues and warnings for me
`minikube delete && minikube start`

Hope this helps

**Comment by Aashish-cyber** [comment]
yeah, i had already solved this issue but thank you brother
