### ISSUE TITLE
minikube doesn't work with  vmware driver also

### ISSUE THREAD

**Issue by panktrip** [kubernetes/minikube#13644]
### What Happened?

since minikube failed to create  cluster with virtualbox, so I thought to try with other drivers, and I tried with vmware-workstation now.  
But I see, it failed here too.   later I tried with hyper-v and it failed there too.  
I am not sure, how others are using it , OR is there any issue with 1.25 version.

PS C:\>  minikube start --driver=vmware
* minikube v1.25.1 on Microsoft Windows 10 Enterprise 10.0.19044 Build 19044
* Using the vmware driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.25.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.25.0.iso: 226.25 MiB / 226.25 MiB [] 100.00% 8.80 MiB p/s 26s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.23.1 preload ...
    > preloaded-images-k8s-v16-v1...: 504.42 MiB / 504.42 MiB  100.00% 9.77 MiB
* Creating vmware VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Deleting "minikube" in vmware ...
! StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
* Creating vmware VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Failed to start vmware VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting

X Exiting due to DRV_NO_IP: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
* Suggestion: Check your firewall rules for interference, and run 'virt-host-validate' to check for KVM configuration issues. If you are running minikube within a VM, consider using --driver=none
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/
* Related issues:
  - https://github.com/kubernetes/minikube/issues/4249
  - https://github.com/kubernetes/minikube/issues/3566

****  Cleaning off now, and uninstalling minikube... its a shit **********

PS C:\WINDOWS\system32> minikube delete
* Deleting "minikube" in vmware ...
* Removed all traces of the "minikube" cluster.
PS C:\WINDOWS\system32> minikube delete
! "minikube" profile does not exist, trying anyways.
* Removed all traces of the "minikube" cluster.
PS C:\WINDOWS\system32> choco uninstall minikube
Chocolatey v0.12.1
Uninstalling the following packages:
minikube
Minikube v1.25.1
 Skipping auto uninstaller - No registry snapshot.
 Minikube has been successfully uninstalled.

### Attach the log file

did not capture logs this time, before that I uninstalled minikube. 

### Operating System

Windows

### Driver

VMware

**Comment by spowelljr** [comment]
Hi @panktrip, thanks for reporting your issue with minikube!

I'm sorry you didn't have a good experience with minikube, to figure out why this isn't working I would need more detailed logs, and since you've already uninstalled minikube this will not be possible.

I'm going to close this issue, but if you reinstall it in the future and want help debugging this issue feel free to reopen this issue and respond, thanks!
