### ISSUE TITLE
Reorganize docs

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1364]
As we grow and onboard more users, we should look at reorganizing the docs. Right now, its become something of a monolith, as well as having many docs at the top level.  Before I send a PR, I'd like to discuss a little what we think it should look like.

cc @dlorenc @aaron-prindle 

**README.md**
At a high level, I think that we should remove all the developer specific wording from the README and include it in a the docs/ folder.  Ideally, this could be copied to our `getting-started` page on kubernetes.io

* **Logo**
* **What is Minikube?**
I think we should get rid of "Features", since providing a subset of what we support almost makes it seem like that list is composed of the _only_ things we support.
* **Installation**
  * Requirements
  * Instructions
   Our installation instructions have been pretty consistent, so we should save users the trouble of going to a different page to install.  So just put them in the README in addition to the releases page.
* **Quickstart**
* **Interacting with your cluster**
* **Managing your cluster**
* **Design**
* **Community**
* **Advanced topics and tutorials**
This will be a list of links to markdown files contained in docs/, each topic will get its own file
   * Debugging
   * Addons
   * Using minikube with a HTTP Proxy
   * Minikube Environment Variables
   * Accessing Localkube Resources From Inside a Pod
   * Using rkt 
   * Enabling an Insecure Registry
   * Configuring Kubernetes
   * Persistent Volumes
   * Mounting Host Folders
   * Private Container Registries
* **Contributing**
  All the top level markdown files, except for the readme, will be moved into docs/contributing/
  These file should be cleaned up, but I'm not sure the layout needs to change.

**Comment by aaron-prindle** [comment]
Related documentation stuff:
Troubleshooting Guide: #399
"Tips and Tricks" Guide: Suggestion by @pgray in Slack.  This would be a page with hacks that people use in minikube to add additional functionality/UX that we can't fit in a major category.  For example #1353.
