### ISSUE TITLE
mk-minikube: un-retryable: no free private network subnets found with given parameters

### ISSUE THREAD

**Issue by softstuck** [kubernetes/minikube#13655]
### What Happened?

[hyena@centos ~]$ minikube start --memory=4096 --vm-driver kvm2
* minikube v1.25.1 on Centos 8.0.1905
* Using the kvm2 driver based on existing profile
! You cannot change the memory size for an existing minikube cluster. Please first delete the cluster.
* Starting control plane node minikube in cluster minikube
* Restarting existing kvm2 VM for "minikube" ...
! StartHost failed, but will try again: driver start: ensuring active networks: recreating inoperable network mk-minikube: un-retryable: no free private network subnets found with given parameters (start: "192.168.11.0", step: 11, tries: 20)
* Restarting existing kvm2 VM for "minikube" ...
* Failed to start kvm2 VM. Running "minikube delete" may fix it: driver start: ensuring active networks: recreating inoperable network mk-minikube: un-retryable: no free private network subnets found with given parameters (start: "192.168.11.0", step: 11, tries: 20)

X Exiting due to GUEST_PROVISION: Failed to start host: driver start: ensuring active networks: recreating inoperable network mk-minikube: un-retryable: no free private network subnets found with given parameters (start: "192.168.11.0", step: 11, tries: 20)
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

[hyena@centos ~]$

[hyena@centos ~]$ hostnamectl
   Static hostname: centos.ramnet.local
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 2412860845594257bd611c564476fc1a
           Boot ID: 081c4a26e1d34e5cbd73f2c5481aba6f
    Virtualization: vmware
  Operating System: CentOS Linux 8 (Core)
       CPE OS Name: cpe:/o:centos:centos:8
            Kernel: Linux 4.18.0-80.11.2.el8_0.x86_64
      Architecture: x86-64
[hyena@centos ~]$

### Attach the log file

[hyena@centos ~]$ minikube logs --file=logs.txt

X Exiting due to GUEST_KVM2_NO_DOMAIN: state: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')
* Suggestion: The VM that minikube is configured for no longer exists. Run 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/3636

[hyena@centos ~]$

### Operating System

Other

### Driver

KVM2

**Comment by softstuck** [comment]
did all these 
[hyena@centos ~]$ minikube delete
* Removing /home/hyena/.minikube/machines/minikube ...
* Removed all traces of the "minikube" cluster.
[hyena@centos ~]$

[hyena@centos ~]$ sudo systemctl restart libvirtd

- nothing works as such.

**Comment by sharifelgamal** [comment]
Hey @softstuck, can you run `virsh net-list`? If there are more than 20 active libvirt networks running, minikube won't be able to find a free one. If that's indeed the case, running `virsh net-destroy` on the old minikube networks should fix the issue.
