### ISSUE TITLE
Ping to host.minikube.internal not working on Mac OS  on Hyperkit

### ISSUE THREAD

**Issue by devNaresh** [kubernetes/minikube#13717]
### What Happened?

I am using macos monterey and installed minikube using brew. Inside minikube cluster i am trying to connect to service running on my host machine but it's not working. Steps to reproduce and logs.
```
$ minikube ssh
$ ping host.minikube.internal
PING host.minikube.internal (192.168.64.1): 56 data bytes
--- don't receive any packets ----- waiting --- 

❯ minikube version
minikube version: v1.25.1
commit: 3e64b11ed75e56e4898ea85f96b2e4af0301f43d
```

I am not able to figure out why it's not working.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8134674/logs.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by klaases** [comment]
Hi @[devNaresh](https://github.com/devNaresh), are you using any customized network settings, for example, a custom DNS?

Please try deleting your minikube instance and starting again.

```
$ ping host.minikube.internal
PING host.minikube.internal (192.168.64.1): 56 data bytes
64 bytes from 192.168.64.1: seq=0 ttl=64 time=0.513 ms
64 bytes from 192.168.64.1: seq=1 ttl=64 time=0.473 ms
64 bytes from 192.168.64.1: seq=2 ttl=64 time=0.624 ms
64 bytes from 192.168.64.1: seq=3 ttl=64 time=0.331 ms
64 bytes from 192.168.64.1: seq=4 ttl=64 time=0.326 ms
64 bytes from 192.168.64.1: seq=5 ttl=64 time=0.351 ms
64 bytes from 192.168.64.1: seq=6 ttl=64 time=0.570 ms
64 bytes from 192.168.64.1: seq=7 ttl=64 time=0.449 ms
64 bytes from 192.168.64.1: seq=8 ttl=64 time=0.521 ms
64 bytes from 192.168.64.1: seq=9 ttl=64 time=0.322 ms
64 bytes from 192.168.64.1: seq=10 ttl=64 time=0.522 ms
^C
--- host.minikube.internal ping statistics ---
11 packets transmitted, 11 packets received, 0% packet loss
round-trip min/avg/max = 0.322/0.454/0.624 ms
```

**Comment by klaases** [comment]
Hi @devNaresh  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by Schoko19961** [comment]
I'm facing exactly the same issue as @devNaresh.
I followed this tutorial until the docker-compose part: https://itnext.io/goodbye-docker-desktop-hello-minikube-3649f2a1c469

No other configurations were made.
The command to start minikube is: `minikube start --driver=hyperkit --container-runtime=docker`
```
😄  minikube v1.25.2 sur Darwin 12.2.1
    ▪ MINIKUBE_ACTIVE_DOCKERD=minikube
✨  Utilisation du pilote hyperkit basé sur le profil existant
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
🔄  Redémarrage du hyperkit VM existant pour "minikube" ...
❗  Ce VM rencontre des difficultés pour accéder à https://k8s.gcr.io
💡  Pour extraire de nouvelles images externes, vous devrez peut-être configurer un proxy : https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Préparation de Kubernetes v1.23.3 sur Docker 20.10.12...
    ▪ kubelet.housekeeping-interval=5m
🔎  Vérification des composants Kubernetes...
    ▪ Utilisation de l'image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Modules activés: storage-provisioner, default-storageclass
🏄  Terminé ! kubectl est maintenant configuré pour utiliser "minikube" cluster et espace de noms "default" par défaut.
```

I want to connect the nodes to the cntlm running on the host machine as a next step, but therefore I need `host.minikube.internal` to work if I understood it well.

**Comment by pelcasandra** [comment]
Same problem is also happening to me.

**Comment by devNaresh** [comment]
yes, this issue still persist

**Comment by miroslav-chandler** [comment]
Have the same issue

**Comment by FelixSuXP** [comment]
Have the same issue

**Comment by pyangzen** [comment]
I believe this is related to the issue: https://github.com/kubernetes/minikube/issues/11510

**Comment by Brice-D** [comment]
Hello, I'm facing the same issue on MacOs, can I reopen this issue?
I could provide the minikube logs. Any personal data I should remove from the logs before sharing it here?

**Comment by jasplil** [comment]
I'm facing the same issue on MacOs intel
