### ISSUE TITLE
Can't start minikube inside docker network

### ISSUE THREAD

**Issue by dazzzed** [kubernetes/minikube#13729]
### What Happened?

I'm trying to start minikube on ubuntu 18.04 inside nginx proxy manager docker network in order to setup some kubernetes services and manage the domain names and the proxy hosts in the nginx proxy manager platform.

so I have `nginxproxymanager_default` docker network and when I run `minikube start --network=nginxproxymanager_default` I get

> Exiting due to GUEST_PROVISION: Failed to start host: can't create with that IP, address already in use

what might I been doing wrong?

### Attach the log file

🤷  The control plane node "" does not exist.
👉  To start a cluster, run: "minikube start"

**Comment by zhan9san** [comment]
Hi @dazzzed 

This issue can be reproduced in v1.25.2 on Ubuntu 21.04.

Here is a workaround.

Assume gateway IP is `172.18.0.1`.

Minikube will try to use `172.18.0.2`(gateway + 1), so if you start Minikube container first and then other containers in `nginxproxymanager_default `. The minikube contaienr will take `172.18.0.2` as its IP address

**Comment by zhan9san** [comment]
Hi team,

I just comment [the static IP code](https://github.com/kubernetes/minikube/blob/e78c26ff370c1717b1384fabd8061b0366e607d6/pkg/drivers/kic/oci/oci.go#L187) and compile a new minikube binary. It works well.

Do you have concerns if static IP is removed?
If no, I'd like to continue working on this feature.

Does static Minikube container IP have any scenarios?


How to test

1. Create a test network in docker

```
$ docker network create test
ae984c8b281dc1ab2209f9df202557c215fe6d923c33b4eb78c521d0706fcc1e
```

2. Run a container, in which the `gateway + 1` IP address(`"IPv4Address": "172.19.0.2/16"`)will be assigned
```
$ docker run --rm -d --network=test test-nginx
$ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' test-nginx
172.19.0.2
```

3. Start Minikube

As the static IP code is commented, the `minikube` container will be assigned an available IP address automatically

```
$ ./out/minikube start --network=test --driver=docker -v=8 --alsologtostderr
$ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' minikube
172.19.0.3
$ $ ./out/minikube ip
172.19.0.3
```

**Comment by klaases** [comment]
Hi @zhan9san, I see that this functionality may work for some scenarios, but perhaps not for all. As @medyagh has suggested in https://github.com/kubernetes/minikube/pull/13766, it might make more sense for this option to become available as an optional feature.

**Comment by zhan9san** [comment]
Hi @klaases 

Thank you for your attention.

I'd appreciate it if you could explain the detailed scenarios.

IMHO, there is no conflict between #13766 and #13050.

## remove static ip in docker and podman #13766
  
It does in the same manner as Docker does. By default a container would be assigned an available IP from DHCP pool. Instead, currently Minikube would generate an IP address which is `gateway` + 1, and it doesn't care about whether the IP is available.

## wip: new flag --static-ip to allow random IP #13050
  
This feature is to make Minikube has ability to assign a static IP.

**Comment by sharifelgamal** [comment]
Having a static IP on by default is useful so minikube can survive things like the user's laptop going to sleep and the like. It seems like the issue is less about minikube assigning a static IP and how the static IP is determined. Getting rid of the feature isn't the answer, but fixing it is definitely a good option.
