### ISSUE TITLE
error: group map[(...)] is already registered

### ISSUE THREAD

**Issue by olalonde** [kubernetes/minikube#1372]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): minikube version: v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 10.12.4
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.18.0.iso
- **Install tools**: ?
- **Others**: ?

**What happened**:

```bash
$ minikube start
....
$ kubectl cluster-info
Kubernetes master is running at https://192.168.99.102:8443
error: group map[authorization.k8s.io:0xc4203db030 certificates.k8s.io:0xc4203db2d0 federation:0xc4203da930 authentication.k8s.io:0xc4203daee0 autoscaling:0xc4203db0a0 batch:0xc4203db260 componentconfig:0xc4203db340 extensions:0xc4203a6070 policy:0xc4203a60e0 rbac.authorization.k8s.io:0xc4203a6150 :0xc4203dae00 apps:0xc4203dae70 storage.k8s.io:0xc4203a61c0] is already registered
```

**What you expected to happen**:

`kubectl cluster-info` should not output an error

**How to reproduce it** (as minimally and precisely as possible):

`minikube start; kubectl cluster-info` (was able to reproduce 3 times... minikube delete, deleted `~/.minikube`, etc. and still getting the error on a fresh minikube start).

**Comment by olalonde** [comment]
Fixed by updating `kubectl` (I had an old version... v1.4)

**Comment by MaLub** [comment]
Also fixed by updating {{kubectl}}

**Comment by vlado-github** [comment]
I am experiencing same issue today.

OS: win10
minikube: 1.0.0, minikube-v1.0.0.iso
kubectl: 1.14.0

` $ kubectl cluster-info
...
Kubernetes master is running at https://192.168.99.101:8443
error: group map[authorization.k8s.io:0xc0823ba000 extensions:0xc0823ba3f0 federation:0xc0823178f0 :0xc082317dc0 authentication.k8s.io:0xc082317ea0 storage.k8s.io:0xc0823ba540 networking.k8s.io:0xc0823bb1f0 certificates.k8s.io:0xc0823ba2a0 componentconfig:0xc0823ba310 policy:0xc0823ba460 rbac.authorization.k8s.io:0xc0823ba4d0 apps:0xc082317e30 autoscaling:0xc0823ba070 batch:0xc0823ba230] is already registered`
