### ISSUE TITLE
kube-proxy doesn't work on first start with none-driver

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [kubernetes/minikube#13726]
### What Happened?

On the first start of minikube on a fresh install, the `control-plane.minikube.internal` host is not resolvable by the `kube-proxy` pod, resulting in that functionality not working correctly.

Stopping minikube and starting it again results in it working properly.

Simultaneously, also seeing the storage provisioner error described in #13635 which seems like it _might_ have a related cause.

### Attach the log file

Logs of kube-proxy on first time start: [kube-proxy-fail.txt](https://github.com/kubernetes/minikube/files/8144205/kube-proxy-fail.txt)
The errors keep repeating ad infinitum until minikube is stopped.

For comparison, here is a successful log:
```
I0225 19:47:17.461469       1 node.go:163] Successfully retrieved node IP: 10.0.0.167
I0225 19:47:17.461511       1 server_others.go:138] "Detected node IP" address="10.0.0.167"
I0225 19:47:17.461536       1 server_others.go:561] "Unknown proxy mode, assuming iptables proxy" proxyMode=""
I0225 19:47:17.486619       1 server_others.go:206] "Using iptables Proxier"
I0225 19:47:17.486637       1 server_others.go:213] "kube-proxy running in dual-stack mode" ipFamily=IPv4
I0225 19:47:17.486642       1 server_others.go:214] "Creating dualStackProxier for iptables"
I0225 19:47:17.486658       1 server_others.go:491] "Detect-local-mode set to ClusterCIDR, but no IPv6 cluster CIDR defined, , defaulting to no-op detect-local for IPv6"
I0225 19:47:17.486822       1 server.go:656] "Version info" version="v1.23.3"
I0225 19:47:17.487523       1 config.go:317] "Starting service config controller"
I0225 19:47:17.487538       1 shared_informer.go:240] Waiting for caches to sync for service config
I0225 19:47:17.487552       1 config.go:226] "Starting endpoint slice config controller"
I0225 19:47:17.487555       1 shared_informer.go:240] Waiting for caches to sync for endpoint slice config
I0225 19:47:17.588014       1 shared_informer.go:247] Caches are synced for endpoint slice config 
I0225 19:47:17.588049       1 shared_informer.go:247] Caches are synced for service config 
E0225 19:47:19.019066       1 proxier.go:1600] "can't open port, skipping it" err="listen tcp4 :5432: bind: address already in use" port={Description:nodePort for default/postgres IP: IPFamily:4 Port:5432 Protocol:TCP}
```

The last line is a service I started ... what I find interesting is that the port is already in use ... _because that copy of `kube-proxy` opened it_ :raised_eyebrow: Not sure if this is the result of a dual stack thing or a multiple interfaces / none-driver thing, but it works at any rate.

### Operating System

Ubuntu

### Driver

None (Baremetal)

**Comment by aleksandar-kinanov** [comment]
@mgabeler-lee-6rs Do you happen to encounter any issues with Services exposure?

We are currently hitting a problem with **driver=none** and no services are accessible from outside on: http://minikube-ip:NodePort

We also encounter that same `"bind: address already in use" ` and surely there's nothing else running on that port.

**Comment by mgabeler-lee-6rs** [comment]
@aleksandar-kinanov yes, that is the precise issue I'm observing here

**Comment by rifaterdemsahin** [comment]
<img width="504" alt="image" src="https://user-images.githubusercontent.com/5270036/167392619-1b62f999-58f2-4a13-b319-7fdc660c6873.png">


similar issues

**Comment by mgabeler-lee-6rs** [comment]
I finally tracked this down to an error in my machine provisioning script that was racing with minikube to update `/etc/hosts` and always winning (and thus undoing minikube's edits).
