### ISSUE TITLE
minikube start  启动失败

### ISSUE THREAD

**Issue by yuandongx** [kubernetes/minikube#13733]
**重现问题所需的命令**：
minikube start --base-image="docker.io/kicbase/stable:v0.0.30" --kubernetes-version v1.23.0
**失败的命令的完整输出**：<details>
minikube start --base-image="docker.io/kicbase/stable:v0.0.30" --kubernetes-version v1.23.0
* minikube v1.25.2 on Centos 8.3.2011 (amd64)
* Automatically selected the podman driver
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Downloading Kubernetes v1.23.0 preload ...
    > preloaded-images-k8s-v17-v1...: 504.42 MiB / 504.42 MiB  100.00% 5.73 MiB
E0301 17:05:27.866425  105125 cache.go:203] Error downloading kic artifacts:  not yet implemented, see issue #8426
* Creating podman container (CPUs=2, Memory=2200MB) ...
! StartHost failed, but will try again: creating host: create: creating: setting up container node: preparing volume for minikube container: sudo -n podman run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var docker.io/kicbase/stable:v0.0.30 -d /var/lib: exit status 127
stdout:

stderr:
time="2022-03-01T17:05:28+08:00" level=error msg="error loading cached network config: network \"podman\" not found in CNI cache"
time="2022-03-01T17:05:28+08:00" level=warning msg="falling back to loading from existing plugins on disk"
time="2022-03-01T17:05:28+08:00" level=error msg="Error tearing down partially created network namespace for container cfac4d71f5992c79389fa88224494ecadd7a51c79ae8e17922e3f12e5f5f2979: CNI network \"podman\" not found"
Error: error configuring network namespace for container cfac4d71f5992c79389fa88224494ecadd7a51c79ae8e17922e3f12e5f5f2979: CNI network "podman" not found

* Restarting existing podman container for "minikube" ...
* Failed to start podman container. Running "minikube delete" may fix it: podman inspect ip minikube: sudo -n podman container inspect -f {{.NetworkSettings.IPAddress}} minikube: exit status 125
stdout:

stderr:
Error: error inspecting object: no such container minikube

X Exiting due to GUEST_PROVISION: Failed to start host: podman inspect ip minikube: sudo -n podman container inspect -f  minikube: exit status 125
stdout:

stderr:
Error: error inspecting object: no such container minikube

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰────────────────────────────────────────────

</details>

**`minikube logs`命令的输出**： <details>

minikube logs --file=logs.txt

X Exiting due to GUEST_STATUS: state: unknown state "minikube": sudo -n podman container inspect minikube --format=: exit status 125
stdout:

stderr:
Error: error inspecting object: no such container minikube

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    * Please also attach the following file to the GitHub issue:                             │
│    * - /tmp/minikube_logs_efc9013384fb3142588e6582f1a88043fcdddadd_0.log                    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

</details>

**使用的操作系统版本**：
Centos 8.3.2011 (amd64)

**Comment by klaases** [comment]
Hi @[yuandongx](https://github.com/yuandongx) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

---

嗨@[yuandongx](https://github.com/yuandongx) - 这个问题还在发生吗？是否提供其他详细信息？如果是这样，请随时通过使用 `/reopen` 评论重新打开问题。由于无法获得更多信息并且已经过了一段时间，此问题将被关闭。

可能有帮助的其他信息：

* 问题是否出现在最新的 minikube 版本中

* 使用的确切 minikube 启动命令行

* 附上minikube日志的完整输出，运行`minikube logs --file=logs.txt`创建日志文件

感谢您分享您的经验！
