### ISSUE TITLE
Exiting due to MK_ADDON_ENABLE

### ISSUE THREAD

**Issue by vraghavach** [kubernetes/minikube#13738]
### What Happened?

With minikube 1.25.2 and Kubernetes 1.20.2 could not enable ngnix ingress controller. All the details are attached. Some flavors of these have been reported. But do not see any with the latest version.

### Attach the log file

* 
* ==> Audit <==
* |---------|----------------|----------|----------|---------|-------------------------------|-------------------------------|
| Command |      Args      | Profile  |   User   | Version |          Start Time           |           End Time            |
|---------|----------------|----------|----------|---------|-------------------------------|-------------------------------|
| ssh     |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 06:51:20 PST | Tue, 01 Mar 2022 06:51:30 PST |
| stop    |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 07:05:36 PST | Tue, 01 Mar 2022 07:05:37 PST |
| delete  |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 07:37:25 PST | Tue, 01 Mar 2022 07:37:27 PST |
| start   |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 07:37:35 PST | Tue, 01 Mar 2022 07:38:02 PST |
| stop    |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 07:38:15 PST | Tue, 01 Mar 2022 07:38:28 PST |
| start   |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 07:38:30 PST | Tue, 01 Mar 2022 07:38:50 PST |
| stop    |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 09:43:04 PST | Tue, 01 Mar 2022 09:43:16 PST |
| delete  |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 09:43:37 PST | Tue, 01 Mar 2022 09:43:39 PST |
| start   |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 09:43:47 PST | Tue, 01 Mar 2022 09:44:15 PST |
| addons  |                | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 10:46:31 PST | Tue, 01 Mar 2022 10:46:31 PST |
| addons  | list           | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 10:46:37 PST | Tue, 01 Mar 2022 10:46:37 PST |
| addons  | ingress        | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 10:47:19 PST | Tue, 01 Mar 2022 10:47:19 PST |
| addons  | ingress enable | minikube | vkaushik | v1.25.2 | Tue, 01 Mar 2022 10:47:36 PST | Tue, 01 Mar 2022 10:47:36 PST |
|---------|----------------|----------|----------|---------|-------------------------------|-------------------------------|

* 
* ==> Last Start <==
* Log file created at: 2022/03/01 09:43:47
Running on machine: GMinor
Binary: Built with gc go1.17.7 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0301 09:43:47.596406   45157 out.go:297] Setting OutFile to fd 1 ...
I0301 09:43:47.596474   45157 out.go:349] isatty.IsTerminal(1) = true
I0301 09:43:47.596477   45157 out.go:310] Setting ErrFile to fd 2...
I0301 09:43:47.596481   45157 out.go:349] isatty.IsTerminal(2) = true
I0301 09:43:47.596571   45157 root.go:315] Updating PATH: /home/vkaushik/.minikube/bin
I0301 09:43:47.596783   45157 out.go:304] Setting JSON to false
I0301 09:43:47.617199   45157 start.go:112] hostinfo: {"hostname":"GMinor","uptime":11703,"bootTime":1646144925,"procs":391,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"21.10","kernelVersion":"5.13.0-30-generic","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"9d36a92d-8994-491f-b9a1-5b0f5a15ef63"}
I0301 09:43:47.617276   45157 start.go:122] virtualization: kvm host
I0301 09:43:47.620454   45157 out.go:176] 😄  minikube v1.25.2 on Ubuntu 21.10
I0301 09:43:47.620601   45157 notify.go:193] Checking for updates...
I0301 09:43:47.620662   45157 driver.go:344] Setting default libvirt URI to qemu:///system
I0301 09:43:47.620682   45157 global.go:111] Querying for installed drivers using PATH=/home/vkaushik/.minikube/bin:/home/vkaushik/.local/bin:/usr/bin/python3:/home/vkaushik/Software/java17/bin:/home/vkaushik/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/vkaushik/Software/jmeter/bin:/home/vkaushik/Software/sonar/bin/linux-x86-64:/home/vkaushik/Software/gradle/bin:/home/vkaushik/Software/node/bin:/home/vkaushik/Software/as/bin:/home/vkaushik/Software/appium:/home/vkaushik/anaconda3/bin:/home/vkaushik/Software/cassandra/bin:/home/vkaushik/Software/groovy/bin::/home/vkaushik/Software/go/bin:/usr/lib/postgresql/14/bin:/home/vkaushik/Software/elastic/bin:/home/vkaushik/Software/kibana/bin:/home/vkaushik/keycloak/bin:/home/vkaushik/Software/as/bin:/home/vkaushik/Software/ij/bin:/home/vkaushik/Openshot:/home/vkaushik/node_modules/.bin:/usr/local/bin
I0301 09:43:47.620788   45157 global.go:119] podman default: true priority: 7, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "podman": executable file not found in $PATH Reason: Fix:Install Podman Doc:https://minikube.sigs.k8s.io/docs/drivers/podman/ Version:}
I0301 09:43:47.620809   45157 global.go:119] ssh default: false priority: 4, state: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0301 09:43:47.646008   45157 virtualbox.go:136] virtual box version: 6.1.32r149290
I0301 09:43:47.646021   45157 global.go:119] virtualbox default: true priority: 6, state: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:6.1.32r149290
}
I0301 09:43:47.646146   45157 global.go:119] vmware default: true priority: 7, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "docker-machine-driver-vmware": executable file not found in $PATH Reason: Fix:Install docker-machine-driver-vmware Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/ Version:}
I0301 09:43:47.687614   45157 docker.go:132] docker version: linux-20.10.11
I0301 09:43:47.687686   45157 cli_runner.go:133] Run: docker system info --format "{{json .}}"
I0301 09:43:47.771912   45157 info.go:263] docker info: {ID:XOPF:VXD3:PKRA:OXPZ:CJSN:BEGY:BPMC:LVME:GVMV:O5VR:YY5O:UFF7 Containers:1 ContainersRunning:1 ContainersPaused:0 ContainersStopped:0 Images:2 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:33 OomKillDisable:false NGoroutines:44 SystemTime:2022-03-01 09:43:47.714910453 -0800 PST LoggingDriver:json-file CgroupDriver:systemd NEventsListener:0 KernelVersion:5.13.0-30-generic OperatingSystem:Ubuntu Core 18 OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:4 MemTotal:16457043968 GenericResources:<nil> DockerRootDir:/var/snap/docker/common/var-lib-docker HTTPProxy: HTTPSProxy: NoProxy: Name:GMinor Labels:[] ExperimentalBuild:false ServerVersion:20.10.11 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:7b11cfaabd73bb80907dd23182b9347b4245eb5d Expected:7b11cfaabd73bb80907dd23182b9347b4245eb5d} RuncCommit:{ID: Expected:} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=apparmor name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Experimental:true 

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by klaases** [comment]
Hi, [vraghavach](https://github.com/vraghavach), thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @[vraghavach](https://github.com/vraghavach) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
