### ISSUE TITLE
minikube is exiting due to an error

### ISSUE THREAD

**Issue by SATVIk-7** [kubernetes/minikube#13745]
### What Happened?

Well, i am trying to start minikube using "minikube start" command from my command prompt inside windows 10 and virtual box is my driver but not able to connect with my minikube.
Error:
X Failed to start virtualbox VM. "minikube start" may fix it.: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027839767
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
 Error:
X Unable to get command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:54341: connectex: No connection could be made because the target machine actively refused it.

### Attach the log file

Not able to get the log file.

### Operating System

Windows

### Driver

VirtualBox

**Comment by klaases** [comment]
Hi @[SATVIk-7](https://github.com/SATVIk-7), this sounds like a potential networking issue. Please ensure that on Windows, VirtualBox is running and is not in use by another application.

As for the logs, these can still be obtained even if `minikube start` has failed.

https://minikube.sigs.k8s.io/docs/commands/logs/

Please try `minikube logs --file "logs.txt"` to generate, and subsequently attach the logs.

**Comment by klaases** [comment]
Hi @[SATVIk-7](https://github.com/SATVIk-7) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
