### ISSUE TITLE
Xhyve driver permission issues with /Users

### ISSUE THREAD

**Issue by pothibo** [kubernetes/minikube#1374]
BUG REPORT

minikube version: v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OS X Sierra
- **VM Driver** : xhyve
- **ISO version**: 0.18.0

**What happened**:
```
$ cd /
$ ls
Users  bin  data  dev  etc  home  init  lib  lib64  linuxrc  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
$ ls -ll
total 5
drwxr-xr-x   1 rkt  staff  238 Sep 21  2016 Users
lrwxrwxrwx   1 root root     7 Apr  7 17:14 bin -> usr/bin
lrwxrwxrwx   1 root root    14 Apr 17 12:50 data -> /mnt/sda1/data
drwxr-xr-x  15 root root  3020 Apr 17 12:50 dev
drwxr-xr-x  23 root root  1000 Apr 17 12:50 etc
drwxr-xr-x   4 root root    80 Apr  7 17:42 home
-rwxr-xr-x   1 root root   176 Apr  7 17:42 init
lrwxrwxrwx   1 root root     7 Apr  7 17:14 lib -> usr/lib
lrwxrwxrwx   1 root root     3 Apr  7 17:14 lib64 -> lib
lrwxrwxrwx   1 root root    11 Apr  7 17:19 linuxrc -> bin/busybox
drwxr-xr-x   2 root root    40 Feb  8 19:23 media
drwxr-xr-x   3 root root    60 Apr 17 12:50 mnt
drwxr-xr-x   3 root root    60 Apr  7 17:41 opt
dr-xr-xr-x 438 root root     0 Apr 17 12:50 proc
drwxr-xr-x   2 root root    40 Feb  8 19:23 root
drwxr-xr-x  17 root root   560 Apr 17 12:51 run
lrwxrwxrwx   1 root root     8 Apr  7 17:14 sbin -> usr/sbin
drwxr-xr-x   2 root root    40 Apr 17 12:50 srv
dr-xr-xr-x  12 root root     0 Apr 17 12:52 sys
drwxrwxrwt   9 root root   300 Apr 17 12:50 tmp
drwxr-xr-x   8 root root   180 Mar  7 22:49 usr
drwxr-xr-x   4 root root   220 Apr 17 12:50 var
$ cd Users/
$ touch test
touch: cannot touch 'test': Permission denied
```

**What you expected to happen**:
Be able to edit files in  either `/Users` or `/Users/pothibo`

**How to reproduce it** (as minimally and precisely as possible):
This is a vanilla build with `xhyve 0.2.0`

**Comment by aaron-prindle** [comment]
@pothibo Can you try mounting your files using the `minikube mount` command and see if that resolves the permission issues?

**Comment by pothibo** [comment]
Sorry, I should have mentionned that I did that already, `mount-9p/` had the same issue

**Comment by dalehamel** [comment]
FYI i've had the same issue.

If you run 

```
mount | grep /Users
```

You'll see that `dfltuid=1000` is hardcoded. However, the docker user has a uid of 1001, and rkt has a uid of 1000.

This is probably due to a race in creading the docker / rkt users.

If you see the output above, you can see that /Users is also owned by rkt.

**Comment by dalehamel** [comment]
Yep, that's definitely it - it's hardcoded to 1000:

https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L910

Going to submit a PR to fix that.

**Comment by dalehamel** [comment]
See https://github.com/zchee/docker-machine-driver-xhyve/pull/171

**Comment by pothibo** [comment]
Wow, you rock @dalehamel!

**Comment by aaron-prindle** [comment]
Closing.  This should be resolved if you use the latest release of https://github.com/zchee/docker-machine-driver-xhyve.
