### ISSUE TITLE
pod in minikube doesn't use local image in windows wsl 

### ISSUE THREAD

**Issue by hjy93** [kubernetes/minikube#13758]
### What Happened?

Environment declaration:
minikube installed in wsl ubuntu. version: 1.25.2
docker via docker desktop.

I deploy a pod use self-build docker image. 
set imagePullPolicy to never or ifnotpresent.

`docker image ` command on wsl show the exist local image. the pod was expected to use the local image.
but container in minikube cannot start because of imagePullBackOff error.

I have also try execute `minikube image load ` and image apper under ./minikube/cache. However minikube still cannot find the local image.

### Attach the log file

minikube profile list
|----------|-----------|---------|--------------|------|----------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version  | Status  | Nodes |
|----------|-----------|---------|--------------|------|----------|---------|-------|
| k8s123   | docker    | docker  | 192.168.58.2 | 8443 | v1.23.3  | Running |     1 |
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.19.10 | Unknown |     2 |

### Operating System

Windows

### Driver

Docker

**Comment by hjy93** [comment]
solved after I start default minikube cluster and do image loading. then image loaded into minikube.
Is this true that `minikube image load` can only  load into default minikube cluster rather than the  current running cluster

**Comment by spowelljr** [comment]
`minikube image load` _should_ work on all profiles, but there's possible there's a bug and it's only working on the default profile. This is worth someone looking into to confirm if this is the case or not.

**Comment by hjy93** [comment]
I have tried again later at v1.25.2, use `minikube image load -p` and it worked as expected. maybe I missed `-p` option last time.
