### ISSUE TITLE
Error loading existing host.

### ISSUE THREAD

**Issue by fsantoyo01** [kubernetes/minikube#13767]
### What Happened?

Hello There

my kuberbetes minikube server was working perfectly fine until yesterday.  Today, I tried to started it up by entering 

Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
minikube start --driver=hyperv 

After this I got the following error:

* minikube v1.25.2 en Microsoft Windows 10 Enterprise 10.0.19043 Build 19043
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
! StartHost failed, but will try again: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\ferna\.minikube\machines\minikube\config.json: El sistema no puede encontrar el archivo especificado.
* Failed to start hyperv VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\ferna\.minikube\machines\minikube\config.json: El sistema no puede encontrar el archivo especificado.

X Saliendo por un error GUEST_PROVISION: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\ferna\.minikube\machines\minikube\config.json: El sistema no puede encontrar el archivo especificado.
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

"minikube delete" command doesnt work either

Would you help me?

### Attach the log file

PS C:\users\ferna\documents\kubernetes> minikube logs --file=log.txt

X Saliendo por un error GUEST_STATUS: load: filestore "minikube": open C:\Users\ferna\.minikube\machines\minikube\config.json: El sistema no puede encontrar el archivo especificado.
*
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                          │
│    * If the above advice does not help, please let us know:                                              │
│      https://github.com/kubernetes/minikube/issues/new/choose                                            │
│                                                                                                          │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                 │
│    * Please also attach the following file to the GitHub issue:                                          │
│    * - C:\Users\ferna\AppData\Local\Temp\minikube_logs_b7c8d828f3377bebee2aac1265a556ed077a8d33_0.log    │
│                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯

PS C:\users\ferna\documents\kubernetes>

### Operating System

Windows

### Driver

Hyper-V

**Comment by sharifelgamal** [comment]
`open C:\Users\ferna.minikube\machines\minikube\config.json: El sistema no puede encontrar el archivo especificado.` means that the minikube config for the HyperV VM no longer exists even if minikube still thinks there is one. 

Run `minikube delete` then try `minikube start --drive=hyperv` again and see if that helps.

**Comment by spowelljr** [comment]
Hi @fsantoyo01, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
