### ISSUE TITLE
Error while starting minikube cluster

### ISSUE THREAD

**Issue by amiros2018** [kubernetes/minikube#13769]
$sudo minikube start --vm-driver=none
Error:
\U0001f604  minikube v1.2.0 on linux (amd64)
\U0001f4a1  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
\U0001f504  Restarting existing none VM for "minikube" ...
\u231b  Waiting for SSH access ...
\U0001f433  Configuring environment for Kubernetes v1.15.0 on Docker 19.03.6
    \u25aa kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
\U0001f504  Relaunching Kubernetes v1.15.0 using kubeadm ... 

\U0001f4a3  Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

\U0001f63f  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
\U0001f449  https://github.com/kubernetes/minikube/issues/new

**Comment by klaases** [comment]
Hi @amiros2018, I noticed that in the logs, the message `Restarting existing none` seems to indicate that an existing cluster exists.

Would you be able to try running `minikube delete --all` to remove existing clusters and try again?

**Comment by klaases** [comment]
Hi @[amiros2018](https://github.com/amiros2018) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
