### ISSUE TITLE
problem with certificate generation on positive timezone inside VM

### ISSUE THREAD

**Issue by Cinorid** [kubernetes/minikube#13779]
### What Happened?

1. `minikube start --driver vmware`
2. `minikube stop`
3. `minikube start`

After running above commands one by one, this error happens. (TimeZone: +4:30)
### related error:
`error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-13T06:25:23Z is before 2022-03-13T09:34:34Z`

### log output of 3rd command

`minikube start`

😄  minikube v1.25.2 on Microsoft Windows 10 Enterprise 10.0.19043 Build 19043
✨  Using the vmware driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing vmware VM for "minikube" ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0313 06:25:22.721303    3974 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0313 06:25:23.718792    3974 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
W0313 06:25:23.719661    3974 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2023-03-13 09:34:35 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-13T06:25:23Z is before 2022-03-13T09:34:34Z
To see the stack trace of this error execute with --v=5 or higher

    ▪ Generating certificates and keys ...

💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0313 06:25:24.013181    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0313 06:25:24.544839    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
W0313 06:25:24.545194    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2023-03-13 09:34:35 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-13T06:25:24Z is before 2022-03-13T09:34:34Z
To see the stack trace of this error execute with --v=5 or higher

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0313 06:25:24.013181    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0313 06:25:24.544839    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
W0313 06:25:24.545194    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2023-03-13 09:34:35 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-13T06:25:24Z is before 2022-03-13T09:34:34Z
To see the stack trace of this error execute with --v=5 or higher

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Windows

### Driver

VMware

**Comment by RA489** [comment]
/ev/certificate-errors

**Comment by RA489** [comment]
/area/provider/vmware

**Comment by spowelljr** [comment]
Hi @Cinorid, thanks for reporting your issue with minikube!

Could you try running `minikube delete --all --purge` and then try starting minikube again and let me know if you still experience the same issue, thanks!

**Comment by Cinorid** [comment]
@spowelljr 
> Hi @Cinorid, thanks for reporting your issue with minikube!
> 
> Could you try running `minikube delete --all --purge` and then try starting minikube again and let me know if you still experience the same issue, thanks!

Hello. I tried but it did not help.

1. `minikube delete --all --purge`
🔥  Successfully deleted all profiles
💀  Successfully purged minikube directory located at - [C:\Users\Ahmad\.minikube]
2. `minikube start --driver=vmware`
😄  minikube v1.25.2 on Microsoft Windows 10 Enterprise 10.0.19043 Build 19043
✨  Using the vmware driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating vmware VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
3. `minikube stop`
✋  Stopping node "minikube"  ...
🛑  1 node stopped.
4. `minikube start`
😄  minikube v1.25.2 on Microsoft Windows 10 Enterprise 10.0.19043 Build 19043
✨  Using the vmware driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing vmware VM for "minikube" ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
E0325 15:17:39.862802   33208 kubeadm.go:682] sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml failed - will try once more: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1
stdout:
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0325 10:47:37.574842    4013 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
W0325 10:47:37.576929    4013 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
W0325 10:47:37.578389    4013 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2023-03-25 15:14:37 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-25T10:47:37Z is before 2022-03-25T15:14:37Z
To see the stack trace of this error execute with --v=5 or higher
🤦  Unable to restart cluster, will reset it: run: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1
stdout:
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0325 10:47:37.670944    4019 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
W0325 10:47:37.673335    4019 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
W0325 10:47:37.673725    4019 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2023-03-25 15:14:37 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-25T10:47:37Z is before 2022-03-25T15:14:37Z
To see the stack trace of this error execute with --v=5 or higher

    ▪ Generating certificates and keys ...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0325 10:47:39.556348    4227 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0325 10:47:40.719087    4227 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
W0325 10:47:40.719212    4227 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2023-03-25 15:14:37 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-25T10:47:40Z is before 2022-03-25T15:14:37Z
To see the stack trace of this error execute with --v=5 or higher

    ▪ Generating certificates and keys ...

💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0325 10:47:41.135015    4335 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0325 10:47:41.725850    4335 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
W0325 10:47:41.726696    4335 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2023-03-25 15:14:37 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-25T10:47:41Z is before 2022-03-25T15:14:37Z
To see the stack trace of this error execute with --v=5 or higher


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0325 10:47:41.135015    4335 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0325 10:47:41.725850    4335 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2032-03-22 15:14:37 +0000 UTC
W0325 10:47:41.726696    4335 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-25 15:14:37 +0000 UTC, NotAfter: 2023-03-25 15:14:37 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-25T10:47:41Z is before 2022-03-25T15:14:37Z
To see the stack trace of this error execute with --v=5 or higher


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by Cinorid** [comment]
@spowelljr 
This is my temporary solution to this problem:
1. `minikube delete --all`
2. Set the system time back at least as much as the time zone. (ex. change 18:45 to 14:15)
3. `minikube start --driver=vmware`
4. `minikube stop`
5. Return the system time to normal state. (ex. change to 18:48)
6. `minikube start`

We have to do these steps every time we want to create a new node.

**Comment by spowelljr** [comment]
Hi @Cinorid, we think it has to do with something relating to syncing the time on the VMware instance.

We implemented a sync change, could you download the binary and do a delete and start and see if there is any change, thanks.

https://storage.googleapis.com/minikube-builds/13889/minikube-windows-amd64.exe

**Comment by Cinorid** [comment]
@spowelljr
I will check and let you know.
Thanks a lot for your time and support.

Regards,

**Comment by Cinorid** [comment]
@spowelljr
This binary fixed the problem.
Thanks a lot for your time and support.

**Comment by spowelljr** [comment]
Glad that resolved your issue @Cinorid! I'm going to close this issue, the fix will be included in the next release of minikube. If the issue comes back feel free to respond and reopen the issue, thanks!
