### ISSUE TITLE
list all currently supported Kubernetes versions

### ISSUE THREAD

**Issue by prezha** [kubernetes/minikube#13773]
### What Happened?

users requested the ability to list all supported Kubernetes versions by their minikube, as per https://minikube.sigs.k8s.io/docs/, it should be the _latest Kubernetes release (+6 previous minor versions)_

ref: https://github.com/kubernetes/minikube/issues/1201, https://github.com/kubernetes/minikube/issues/4121

### Attach the log file

n/a

**Comment by ilanni2460** [comment]
i have same issue @prezha +1
