### ISSUE TITLE
minikube does not start on Ubuntu

### ISSUE THREAD

**Issue by mhabibi** [kubernetes/minikube#1379]
**BUG REPORT**:

**Minikube version** : v0.18.0

**Environment**:
- **OS**: Ubuntu 16.04.2 LTS (Xenial Xerus)
- **VM Driver**: virtualbox (Version 5.1.18 r114002 (Qt5.5.1))
- **ISO version**: ~/.minikube/cache/iso/minikube-v0.18.0.iso

**What happened**: After starting minikube (minikube start), I get this error:
```
Starting local Kubernetes cluster...
Starting VM...
E0419 09:07:23.145582    5675 start.go:116] Error starting host: Error starting stopped host: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
.

 Retrying.
E0419 09:07:23.146012    5675 start.go:122] Error starting host:  Error starting stopped host: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

```

**What you expected to happen**:
virtualbox starts normally with minikube

**How to reproduce it**: In ubuntu,
1) install virtualbox
2) install minikube
3) start minikube with virtualbox driver
4) see the error

**Anything else do we need to know**:
I have tried some solutions which are posted in other bug reports for pretty the same problem, but none of them worked.
I also tried different versions of minikube and virtualbox without any success.

**Comment by aaron-prindle** [comment]
Are you able to start other VM images with virtualbox?  I'm guessing that this has to do with a bad Virtualbox installation.  Have you tried completely uninstalling and reinstalling Virtualbox?  That seems to be the primary suggestion here: 
https://askubuntu.com/questions/122211/getting-error-message-when-trying-to-start-a-virtual-machine

**Comment by mhabibi** [comment]
I had tried with uninstalling but not `purge`. It seems to be fixed by:
`sudo apt-get purge virtualbox virtualbox-dkms`
`sudo apt-get install virtualbox-5.1`

**Comment by mongrelion** [comment]
I just want to confirm that purging the virtualbox installation on Ubuntu machines did the trick. Apparently Ubuntu now comes out of the box with VirtualBox. However, the version is a little too old.

1. Purge
2. Delete the `~/.minikube` folder just to be on the safe side
3. Restart the computer
4. Install newest version of VirtualBox

**Comment by avisrivastava254084** [comment]
> 2\. ~/.minikube

This is the ultimate trick!
