### ISSUE TITLE
MK_CONFIG_SET

### ISSUE THREAD

**Issue by MacFlurry** [kubernetes/minikube#13798]
Hello,

I'm on Apple M1 MacBook Pro. 
I know that Hyperkit is not supported for Apple M1.

with Rosetta, I installed the intel version hyperkit for arch x86_64 with Rosetta.
so how to bypass or disable the 
```
Exiting due to MK_CONFIG_SET: run validations for "driver" with value of "hyperkit": [driver "hyperkit" is not supported]
```

Also, how to disable checking `DRV_UNSUPPORTED_OS` , 
in order to test Minikube with Hyperkit Rosettated ?

Thanks

**Comment by afbjorklund** [comment]
Hyperkit is not supported with Rosetta

**Comment by MacFlurry** [comment]
> Hyperkit is not supported with Rosetta either, sorry

so is there no other way to run Minikube on M1 ?

**Comment by MacFlurry** [comment]
I can live with those workaround.
I'll keep an eye on porting minikube on M1.

Is there a way to be notified on the porting to M1 announcement ?

Thanks

**Comment by MacFlurry** [comment]
I can live with those workaround.
I'll keep an eye on porting minikube on M1.

Is there a way to be notified on the porting to M1 announcement ?

Thanks

**Comment by afbjorklund** [comment]
> Is there a way to be notified on the porting to M1 announcement ?

Just the GitHub issues involved, and the Slack channel

It will get featured in the release notes and on KubeCon

**Comment by MacFlurry** [comment]
thanks @afbjorklund
