### ISSUE TITLE
minikuber start, then coredns In crashloop

### ISSUE THREAD

**Issue by Scannery** [kubernetes/minikube#13819]
### What Happened?

192.168.49.1    start minikuber here;    vmware:centos7
192.168.49.2/172.17.0.1 minikuber docker image
172.17.0.2 coredns

docker log dns-image：
[ERROR] plugin/errors: 2 3890269790922051111.174307046596220162. HINFO: read udp 172.17.0.2:51981->192.168.49.1:53: i/o timeout

53端口要什么啊？本机的。

### Attach the log file

docker log dns-image
[ERROR] plugin/errors: 2 3890269790922051111.174307046596220162. HINFO: read udp 172.17.0.2:51981->192.168.49.1:53: i/o timeout
[ERROR] plugin/errors: 2 3890269790922051111.174307046596220162. HINFO: read udp 172.17.0.2:41893->192.168.49.1:53: i/o timeout
[ERROR] plugin/errors: 2 3890269790922051111.174307046596220162. HINFO: read udp 172.17.0.2:40609->192.168.49.1:53: i/o timeout
[ERROR] plugin/errors: 2 3890269790922051111.174307046596220162. HINFO: read udp 172.17.0.2:43894->192.168.49.1:53: i/o timeout

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @Scannery, thanks for reporting your issue with minikube!

Could you run `minikube logs --file=logs.txt` and then upload the log file to this issue, thanks!

**Comment by Scannery** [comment]
[logs.txt](https://github.com/kubernetes/minikube/files/8367716/logs.txt)

Restart too much, gen temp file once run out my disk,I close this deploy some days ago.
restart minikube today, it crash again.

**Comment by LiJinyao** [comment]
I've run into the same issue, here's my log.
[logs.txt](https://github.com/kubernetes/minikube/files/8379013/logs.txt)
I've tried add iptable rule `iptables -P FORWARD ACCEPT`, but it didn't work.

**Comment by klaases** [comment]
Hi @Scannery  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
