### ISSUE TITLE
minikube image load crashes with no helpful information.  I am unable to use a locally built image otherwise in a kubernetes/minikube cluster

### ISSUE THREAD

**Issue by githubforw0rk** [kubernetes/minikube#13818]
### What Happened?

![image](https://user-images.githubusercontent.com/99474436/159214480-56019edf-53e9-4420-8bd5-90eb775a36dc.png)
I have successfully built a docker image and tried to load it into minikube for testing purposes because of questionable kubernetes design that always goes to docker.io for images.  I've tried to eval my env into minikube and tried to set imagePullPolicy to a variety of values.  I'm now trying the long route of setting a private local registry with certs https auth and everything.  I doubt I will make any headway there before finding yet another issue.  It feels like there's a real bug with kubernetes, docker, minikube or any of the moving parts involved.  I can't provide the docker image but it is 1.86 GB

kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3", GitCommit:"816c97ab8cff8a1c72eccca1026f7820e93e0d25", GitTreeState:"clean", BuildDate:"2022-01-25T21:25:17Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"linux/amd64"}

minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7

docker version
Client: Docker Engine - Community
 Version:           20.10.13
 API version:       1.41
 Go version:        go1.16.15
 Git commit:        a224086
 Built:             Thu Mar 10 14:07:51 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.13
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.15
  Git commit:       906f57f
  Built:            Thu Mar 10 14:05:44 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.10
  GitCommit:        2a1d4dbdb2a1030dc5b01e96fb110a9d9f150ecc
 runc:
  Version:          1.0.3
  GitCommit:        v1.0.3-0-gf46b6ba
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

![image](https://user-images.githubusercontent.com/99474436/159215049-924c053f-8fc7-4534-aa6f-e12c9065895c.png)

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8313590/log.txt)

**Comment by afbjorklund** [comment]
Most of the output from "minikube image" is still only in the logs, so you might want look there first.

**Comment by afbjorklund** [comment]
> because of questionable kubernetes design that always goes to docker.io for images

This is inherited from Docker, but if you add your registry to the images it should **not** go to docker.io unless requested to

**Comment by githubforw0rk** [comment]
It looks like logs aren't even getting anything from the minikube image command.  Is there a more serious issue at hand?

**Comment by githubforw0rk** [comment]
I attempted to minikube image load nginx:latest and this succeeded.  I wonder if it's the image size that's the problem.

**Comment by githubforw0rk** [comment]
It turns out it was a memory issue.  I upped the VM's memory from 4 to 8 gb and this issue went away.  
![image](https://user-images.githubusercontent.com/99474436/159219405-0f8b4515-ce0c-4d76-9cdc-473b97b628cc.png)

**Comment by afbjorklund** [comment]
> It looks like logs aren't even getting anything from the minikube image command

It should the individual commands, but maybe that required increased verbosity
