### ISSUE TITLE
Minikube does not start properly but minikube start returns exit code 0

### ISSUE THREAD

**Issue by kschaab** [kubernetes/minikube#13838]
### What Happened?

In the attached logs the command:
`minikube start -p minikube --delete-on-failure`
returns exit code 0

However, minikube did not start the kube api server successfully as indicated in its log:
```
W0322 17:13:34.854121   99236 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: Process exited with status 1
stdout:
 
stderr:
```

### Attach the log file

[minikube start logs](https://gist.github.com/kschaab/e36326c73d84c1377b411fec6d84bace)
[Cloud Code Logs](https://gist.github.com/kschaab/bcc0cc1ef0bd968f9eba563809a079b7)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by spowelljr** [comment]
Hi @kschaab, the logs you provided are for `minikube profile list -o json`, but we can look into this
