### ISSUE TITLE
minikube mount not functioning as expected

### ISSUE THREAD

**Issue by ashernevins** [kubernetes/minikube#1384]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OS X
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.18.0

**What happened** + **How to reproduce it**:
After following the format in README to mount a volume, the following happened

```
$ minikube mount /Users/asher/code/lf:/mount-code
Cannot find directory /Users/asher/code/lf:/mount-code for mount
Mounting /Users/asher/code/lf:/mount-code into /mount-9p on the minikubeVM
```

`minikube mount /Users/asher/code/lf:/mount-9p` failed similarly.

`minikube mount /Users/asher/code/lf`worked, and mounted the directory to `/mount-9p` inside the vm.

**What you expected to happen**:

I expected the path after the `:` in the mount command to be the path in the VM's where the directory was mounted.

In lieu of an immediate fix for this, it would be nice to know if `/mount-9p` will always be the path where an external directory will be mounted.

**Comment by aaron-prindle** [comment]
The `minikube mount` syntax was recently changed at HEAD to use a `:` notation similar to mounting a docker volume.  The `minikube mount` command in v0.18.0 has the syntax `minikube mount /path/to/host/dir` and that host directory is automatically mounted into /mount-9 on the VM.
