### ISSUE TITLE
After upgrade PC hardware and os, minikube doesn't start

### ISSUE THREAD

**Issue by DonggookKim** [kubernetes/minikube#13840]
### What Happened?

I upgrade my pc hardware Ryzen x2700 -> Ryzen x5800 and upgrade os version from windows 10 to windows 11.

After that minikube doesn't start.

I removed minikube and reinstall minikube with winget but it still got error.

Can you help me?

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8330388/logs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @DonggookKim, thanks for reporting your issue with minikube!

It looks like your certificate expired, could you try running `minikube delete --all --purge` and then try starting minikube again and see if that resolves your issue, thanks!

**Comment by DonggookKim** [comment]
Thank you very much. It solve my problem perfectly.
