### ISSUE TITLE
failed to Deploy the Kubernetes Ingress Controller

### ISSUE THREAD

**Issue by gabe2code** [kubernetes/minikube#13854]
### What Happened?

I'm trying to deploy kong following [the guide](https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/deployment/minikube/) on the official website. 

1- I installed minikube without issues 👍 
2- kubectl create -f https://bit.ly/k4k8s 👍 
3- export PROXY_IP=$(minikube service -n kong kong-proxy --url | head -1) 👎 

receiving this error: 

```$ export PROXY_IP=$(minikube service kong-1648148481-kong-proxy --url | head -1)
! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 2.5899263s
* Restarting the docker service may improve performance.
E0324 15:22:28.752584    3004 out.go:189] Fprintf failed: write /dev/stdout: The pipe is being closed.
! Because you are using a Docker driver on windows, the terminal needs to be open to run it.
```
any suggestions?

PS: Also tried with **helm** and receive the same error

### Attach the log file

Log file created at: 2022/03/24 15:11:18
Running on machine: DESKTOP-8ESOF1A
Binary: Built with gc go1.17.7 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0324 15:11:18.031156   38712 out.go:297] Setting OutFile to fd 756 ...
I0324 15:11:18.031156   38712 out.go:344] TERM=xterm,COLORTERM=, which probably does not support color
I0324 15:11:18.031156   38712 out.go:310] Setting ErrFile to fd 1044...
I0324 15:11:18.031156   38712 out.go:344] TERM=xterm,COLORTERM=, which probably does not support color
W0324 15:11:18.043156   38712 root.go:293] Error reading config file at C:\Users\Gabriel\.minikube\config\config.json: open C:\Users\Gabriel\.minikube\config\config.json: The system cannot find the file specified.
I0324 15:11:18.043156   38712 mustload.go:65] Loading cluster: minikube
I0324 15:11:18.044534   38712 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0324 15:11:18.061556   38712 cli_runner.go:133] Run: docker container inspect minikube --format={{.State.Status}}
W0324 15:11:20.322501   38712 out.go:241] ! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 2.2600779s
W0324 15:11:20.322501   38712 out.go:241] * Restarting the docker service may improve performance.
I0324 15:11:20.323012   38712 cli_runner.go:186] Completed: docker container inspect minikube --format={{.State.Status}}: (2.2600779s)
I0324 15:11:20.323012   38712 host.go:66] Checking if "minikube" exists ...
I0324 15:11:20.335458   38712 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0324 15:11:21.356848   38712 cli_runner.go:186] Completed: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube: (1.0213901s)
I0324 15:11:21.356848   38712 api_server.go:165] Checking apiserver status ...
I0324 15:11:21.369432   38712 ssh_runner.go:195] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0324 15:11:21.377736   38712 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0324 15:11:22.527948   38712 cli_runner.go:186] Completed: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: (1.1499667s)
I0324 15:11:22.527948   38712 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:5847 SSHKeyPath:C:\Users\Gabriel\.minikube\machines\minikube\id_rsa Username:docker}
I0324 15:11:22.915742   38712 ssh_runner.go:235] Completed: sudo pgrep -xnf kube-apiserver.*minikube.*: (1.54631s)
I0324 15:11:22.929290   38712 ssh_runner.go:195] Run: sudo egrep ^[0-9]+:freezer: /proc/1576/cgroup
W0324 15:11:22.947452   38712 api_server.go:176] unable to find freezer cgroup: sudo egrep ^[0-9]+:freezer: /proc/1576/cgroup: Process exited with status 1
stdout:

stderr:
I0324 15:11:22.947452   38712 api_server.go:240] Checking apiserver healthz at https://127.0.0.1:5846/healthz ...
I0324 15:11:22.963235   38712 api_server.go:266] https://127.0.0.1:5846/healthz returned 200:
ok
I0324 15:11:22.963235   38712 host.go:66] Checking if "minikube" exists ...
I0324 15:11:22.973107   38712 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0324 15:11:24.008807   38712 cli_runner.go:186] Completed: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube: (1.0357s)
I0324 15:11:24.109492   38712 service.go:214] Found service: &Service{ObjectMeta:{kong-1648148481-kong-proxy  default  3ba70628-ca76-49d6-8b07-dc32d843bb7c 8025 0 2022-03-24 15:01:23 -0400 EDT <nil> <nil> map[app.kubernetes.io/instance:kong-1648148481 app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:kong app.kubernetes.io/version:2.7 enable-metrics:true helm.sh/chart:kong-2.7.0] map[meta.helm.sh/release-name:kong-1648148481 meta.helm.sh/release-namespace:default] [] []  [{helm Update v1 2022-03-24 15:01:23 -0400 EDT FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/version":{},"f:enable-metrics":{},"f:helm.sh/chart":{}}},"f:spec":{"f:allocateLoadBalancerNodePorts":{},"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}},"k:{\"port\":443,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:kong-proxy,Protocol:TCP,Port:80,TargetPort:{0 8000 },NodePort:32608,AppProtocol:nil,},ServicePort{Name:kong-proxy-tls,Protocol:TCP,Port:443,TargetPort:{0 8443 },NodePort:32507,AppProtocol:nil,},},Selector:map[string]string{app.kubernetes.io/component: app,app.kubernetes.io/instance: kong-1648148481,app.kubernetes.io/name: kong,},ClusterIP:10.108.229.197,Type:LoadBalancer,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.108.229.197],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:*true,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0324 15:11:24.114881   38712 service.go:214] Found service: &Service{ObjectMeta:{kong-1648148481-kong-proxy  default  3ba70628-ca76-49d6-8b07-dc32d843bb7c 8025 0 2022-03-24 15:01:23 -0400 EDT <nil> <nil> map[app.kubernetes.io/instance:kong-1648148481 app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:kong app.kubernetes.io/version:2.7 enable-metrics:true helm.sh/chart:kong-2.7.0] map[meta.helm.sh/release-name:kong-1648148481 meta.helm.sh/release-namespace:default] [] []  [{helm Update v1 2022-03-24 15:01:23 -0400 EDT FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/version":{},"f:enable-metrics":{},"f:helm.sh/chart":{}}},"f:spec":{"f:allocateLoadBalancerNodePorts":{},"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}},"k:{\"port\":443,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:kong-proxy,Protocol:TCP,Port:80,TargetPort:{0 8000 },NodePort:32608,AppProtocol:nil,},ServicePort{Name:kong-proxy-tls,Protocol:TCP,Port:443,TargetPort:{0 8443 },NodePort:32507,AppProtocol:nil,},},Selector:map[string]string{app.kubernetes.io/component: app,app.kubernetes.io/instance: kong-1648148481,app.kubernetes.io/name: kong,},ClusterIP:10.108.229.197,Type:LoadBalancer,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.108.229.197],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:*true,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0324 15:11:24.114881   38712 host.go:66] Checking if "minikube" exists ...
I0324 15:11:24.124732   38712 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0324 15:11:25.151094   38712 cli_runner.go:186] Completed: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube: (1.0262347s)
I0324 15:11:25.161327   38712 out.go:176] http://192.168.49.2:32608
http://192.168.49.2:32507
I0324 15:11:25.170691   38712 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0324 15:11:26.189120   38712 cli_runner.go:186] Completed: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: (1.0184288s)
I0324 15:11:26.222625   38712 out.go:176] * Starting tunnel for service kong-1648148481-kong-proxy.
E0324 15:11:26.222625   38712 out.go:189] Fprintf failed: write /dev/stdout: The pipe is being closed.
W0324 15:11:27.237430   38712 out.go:241] ! Because you are using a Docker driver on windows, the terminal needs to be open to run it.
I0324 15:12:03.200331   38712 out.go:176] * Stopped tunnel for service kong-1648148481-kong-proxy.
E0324 15:12:03.200331   38712 out.go:189] Fprintf failed: write /dev/stdout: The pipe is being closed.
Log file created at: 2022/03/24 15:12:15
Running on machine: DESKTOP-8ESOF1A
Binary: Built with gc go1.17.7 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0324 15:12:15.464895   12968 out.go:297] Setting OutFile to fd 768 ...
I0324 15:12:15.465894   12968 out.go:344] TERM=xterm,COLORTERM=, which probably does not support color
I0324 15:12:15.465894   12968 out.go:310] Setting ErrFile to fd 1044...
I0324 15:12:15.465894   12968 out.go:344] TERM=xterm,COLORTERM=, which probably does not support color
W0324 15:12:15.476900   12968 root.go:293] Error reading config file at C:\Users\Gabriel\.minikube\config\config.json: open C:\Users\Gabriel\.minikube\config\config.json: The system cannot find the file specified.
I0324 15:12:15.477897   12968 mustload.go:65] Loading cluster: minikube
I0324 15:12:15.477897   12968 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0324 15:12:15.494522   12968 cli_runner.go:133] Run: docker container inspect minikube --format={{.State.Status}}
W0324 15:12:17.970097   12968 out.go:241] ! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 2.4749765s
W0324 15:12:17.970097   12968 out.go:241] * Restarting the docker service may improve performance.
I0324 15:12:17.970097   12968 cli_runner.go:186] Completed: docker container inspect minikube --format={{.State.Status}}: (2.4749765s)
I0324 15:12:17.970097   12968 host.go:66] Checking if "minikube" exists ...
I0324 15:12:17.977914   12968 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0324 15:12:19.067559   12968 cli_runner.go:186] Completed: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube: (1.089645s)
I0324 15:12:19.067559   12968 api_server.go:165] Checking apiserver status ...
I0324 15:12:19.080584   12968 ssh_runner.go:195] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0324 15:12:19.088724   12968 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0324 15:12:20.116077   12968 cli_runner.go:186] Completed: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: (1.0273526s)
I0324 15:12:20.116077   12968 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:5847 SSHKeyPath:C:\Users\Gabriel\.minikube\machines\minikube\id_rsa Username:docker}
I0324 15:12:20.407979   12968 ssh_runner.go:235] Completed: sudo pgrep -xnf kube-apiserver.*minikube.*: (1.3273943s)
I0324 15:12:20.421229   12968 ssh_runner.go:195] Run: sudo egrep ^[0-9]+:freezer: /proc/1576/cgroup
W0324 15:12:20.437049   12968 api_server.go:176] unable to find freezer cgroup: sudo egrep ^[0-9]+:freezer: /proc/1576/cgroup: Process exited with status 1
stdout:

stderr:
I0324 15:12:20.437049   12968 api_server.go:240] Checking apiserver healthz at https://127.0.0.1:5846/healthz ...
I0324 15:12:20.463558   12968 api_server.go:266] https://127.0.0.1:5846/healthz returned 200:
ok
I0324 15:12:20.463558   12968 host.go:66] Checking if "minikube" exists ...
I0324 15:12:20.472202   12968 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0324 15:12:21.493473   12968 cli_runner.go:186] Completed: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube: (1.0212708s)
I0324 15:12:21.565967   12968 service.go:214] Found service: &Service{ObjectMeta:{kong-1648148481-kong-proxy  default  3ba70628-ca76-49d6-8b07-dc32d843bb7c 8025 0 2022-03-24 15:01:23 -0400 EDT <nil> <nil> map[app.kubernetes.io/instance:kong-1648148481 app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:kong app.kubernetes.io/version:2.7 enable-metrics:true helm.sh/chart:kong-2.7.0] map[meta.helm.sh/release-name:kong-1648148481 meta.helm.sh/release-namespace:default] [] []  [{helm Update v1 2022-03-24 15:01:23 -0400 EDT FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/version":{},"f:enable-metrics":{},"f:helm.sh/chart":{}}},"f:spec":{"f:allocateLoadBalancerNodePorts":{},"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}},"k:{\"port\":443,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:kong-proxy,Protocol:TCP,Port:80,TargetPort:{0 8000 },NodePort:32608,AppProtocol:nil,},ServicePort{Name:kong-proxy-tls,Protocol:TCP,Port:443,TargetPort:{0 8443 },NodePort:32507,AppProtocol:nil,},},Selector:map[string]string{app.kubernetes.io/component: app,app.kubernetes.io/instance: kong-1648148481,app.kubernetes.io/name: kong,},ClusterIP:10.108.229.197,Type:LoadBalancer,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.108.229.197],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:*true,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0324 15:12:21.570860   12968 service.go:214] Found service: &Service{ObjectMeta:{kong-1648148481-kong-proxy  default  3ba70628-ca76-49d6-8b07-dc32d843bb7c 8025 0 2022-03-24 15:01:23 -0400 EDT <nil> <nil> map[app.kubernetes.io/instance:kong-1648148481 app.kubernetes.io/managed-by:Helm app.kubernetes.io/name:kong app.kubernetes.io/version:2.7 enable-metrics:true helm.sh/chart:kong-2.7.0] map[meta.helm.sh/release-name:kong-1648148481 meta.helm.sh/release-namespace:default] [] []  [{helm Update v1 2022-03-24 15:01:23 -0400 EDT FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:meta.helm.sh/release-name":{},"f:meta.helm.sh/release-namespace":{}},"f:labels":{".":{},"f:app.kubernetes.io/instance":{},"f:app.kubernetes.io/managed-by":{},"f:app.kubernetes.io/name":{},"f:app.kubernetes.io/version":{},"f:enable-metrics":{},"f:helm.sh/chart":{}}},"f:spec":{"f:allocateLoadBalancerNodePorts":{},"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":80,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}},"k:{\"port\":443,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:kong-proxy,Protocol:TCP,Port:80,TargetPort:{0 8000 },NodePort:32608,AppProtocol:nil,},ServicePort{Name:kong-proxy-tls,Protocol:TCP,Port:443,TargetPort:{0 8443 },NodePort:32507,AppProtocol:nil,},},Selector:map[string]string{app.kubernetes.io/component: app,app.kubernetes.io/instance: kong-1648148481,app.kubernetes.io/name: kong,},ClusterIP:10.108.229.197,Type:LoadBalancer,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.108.229.197],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:*true,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0324 15:12:21.570860   12968 host.go:66] Checking if "minikube" exists ...
I0324 15:12:21.578978   12968 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0324 15:12:22.605730   12968 cli_runner.go:186] Completed: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube: (1.0267518s)
I0324 15:12:22.614093   12968 out.go:176] http://192.168.49.2:32608
http://192.168.49.2:32507
I0324 15:12:22.625040   12968 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0324 15:12:23.667151   12968 cli_runner.go:186] Completed: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: (1.042111s)
I0324 15:12:23.679439   12968 out.go:176] * Starting tunnel for service kong-1648148481-kong-proxy.
E0324 15:12:23.679439   12968 out.go:189] Fprintf failed: write /dev/stdout: The pipe is being closed.
W0324 15:12:24.680068   12968 out.go:241] ! Because you are using a Docker driver on windows, the terminal needs to be open to run it.
I0324 15:12:48.621499   12968 out.go:176] * Stopped tunnel for service kong-1648148481-kong-proxy.
E0324 15:12:48.621499   12968 out.go:189] Fprintf failed: write /dev/stdout: The pipe is being closed.

### Operating System

Windows

### Driver

Docker

**Comment by zhan9san** [comment]
Hi @gabe2code 

Try this

## start minikube cluster with docker driver

```
minikube start --driver=docker
```

## Deploy the Kubernetes Ingress Controller

```
kubectl create -f https://bit.ly/k4k8s
```

## Set up tunnel and keep the terminal(terminal 1) open

```
minikube service -n kong kong-proxy --url
```

## Get PROXY_IP in another terminal, named terminal 2

The http PROXY_IP would be http://127.0.0.1:HTTP_PORT

You can get the HTTP_PORT thru the following command.

For example, the HTTP_PORT is `50030` which is after the first '-L'. The second port after `-L` is for https.

```
$ ps -ef | grep 'ssh -o UserKnownHostsFile'
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -N docker@127.0.0.1 -p 64297 -i /Users/xxx/.minikube/machines/minikube/id_rsa -L 50030:10.97.253.241:80 -L 50031:10.97.253.241:443
```

## Set PROXY_IP in terminal 2

Change the `HTTP_PRXOY` to the real port in previous step.

```
export PROXY_IP=http://127.0.0.1:HTTP_PORT
```

## Test PROXY_IP

```
$ curl -i $PROXY_IP
{"message":"no Route matched with those values"}
```

## Test route[optional]

[Getting started with the Kubernetes Ingress Controller](https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/guides/getting-started/)

**Comment by gabe2code** [comment]
Hi @zhan9san Thank you for answering the question

I had followed your steps and I really don't get the "HTTP_PORT" part.

I ran the command: `minikube service -n kong kong-proxy --url`
I got this: 
![image](https://user-images.githubusercontent.com/8299560/160052317-41e8bc29-048f-4bb2-994d-ec04a0411b81.png)

So, I'm assuming that the next command should look like this:
`ps -ef | grep 'ssh -o UserKnownHostsFile'
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -N docker@127.0.0.1 -p 64297 -i /Users/xxx/.minikube/machines/minikube/id_rsa -L 30688:10.97.253.241:80 -L 30693:10.97.253.241:443`

Which throws a connection refuse result
![image](https://user-images.githubusercontent.com/8299560/160052856-f4a5ba82-8acc-4eec-bfe6-1ee8699e63ba.png)
(I also try with the IP that appears in the first image)

I'm I missing something?

Best Regards
Gabriel

**Comment by zhan9san** [comment]
Hi @gabe2code 

Sorry, I assume it's MacOS by mistake.

For Windows with Docker driver, I tried to set up a tunnel by `minikube service` command, but failed.
Luckily, the tunnel for ingress works as below.(If you cannot understand what I am saying here, it's better to go through the reference in the end)

After the `kong` ingress is created, try run the following commands

Create a tunnel in terminal 1 and please keep this terminal 1 open

```bash
minikube tunnel
```

And then in terminal 2

```bash
export PROXY_IP=http://127.0.0.1
```

Verify it in terminal 2

```bash
curl -i $PROXY_IP
```

Reference:

The magic is documented in this document, [Accessing apps](https://minikube.sigs.k8s.io/docs/handbook/accessing/)

**Comment by gabe2code** [comment]
@zhan9san Works like a charm.

Could you please add those specifications to the Readme, or something to indicate that is you're a Windows user, you should follow different steps?

I'm very sure that will be very appreciated.

Thank you for your time 😃

**Comment by zhan9san** [comment]
Hi @gabe2code 

Thanks for your suggestion.

It's better to update the document of `Kong` as well.

Besides, I'll try to make `minikube service` and `minikube tunnel` work in the same manner between `Windows`, `MacOs`.

Could we close this ticket?

**Comment by gabe2code** [comment]
Sure, thanks for your time
