### ISSUE TITLE
Error with pre-create check: Powershell was not found in the path

### ISSUE THREAD

**Issue by jysoo** [kubernetes/minikube#1387]
**Minikube version** (use `minikube version`):
minikube version: v0.17.1
(upgraded to 0.18.0 then back to 0.17.1 but neither works)

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 10
- **VM Driver** (e.g. `cat `~/.minikube/machines/minikube/config.json` | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): 
- **Install tools**:
- **Others**:

**What happened**:

`PS C:\> minikube start --vm-driver="hyperv" --hyperv-virtual-switch=Minikube --insecure-registry= -
-v=7 --alsologtostderr --cpus=4 --memory=10240`
`Starting local Kubernetes cluster...`
`Starting VM...`
`I0420 16:40:12.320928    9576 downloader.go:56] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.0.7.iso`
`Found binary path at C:\kubernetes\minikube.exe`
`Launching plugin server for driver hyperv`
`Plugin server listening at address 127.0.0.1:57371`
`() Calling .GetVersion`
`Using API Version  1`
`() Calling .SetConfigRaw`
`() Calling .GetMachineName`
`(minikube) Calling .GetMachineName`
`(minikube) Calling .DriverName`
`Running pre-create checks...`
`(minikube) Calling .PreCreateCheck`
`E0420 16:40:14.590592    9576 start.go:113] Error starting host: Error creating host: Error with pre-create check: "Powershell was not found in the path".`
` Retrying.
E0420 16:40:14.596601    9576 start.go:119] Error starting host:  Error creating host: Error with pre-create check: "Pershell was not found in the path"`

**What you expected to happen**:
start Minikube

**How to reproduce it (as minimally and precisely as possible)**: start Minikube on Powershell

**Comment by aaron-prindle** [comment]
Did this work with a previous version of `minikube`?  My understanding is that to run hyperv you have to have Powershell in the path.  So while you can run `minikube` in any terminal on Windows (cygwin, cmd, etc.), that terminal still needs to have Powershell in the path if you want to use hyperv.

**Comment by jysoo** [comment]
@aaron-prindle  Thanks for the reply. No it didn't. How do I go about ensuring that Powershell is in the path?

**Comment by aaron-prindle** [comment]
What terminal/shell are you using?  Powershell?

**Comment by jysoo** [comment]
Yes, Powershell

**Comment by r2d4** [comment]
This is the code that is checking for the powershell.exe 

https://github.com/kubernetes/minikube/blob/master/vendor/github.com/docker/machine/drivers/hyperv/powershell.go#L24

**Comment by fisshy** [comment]
Adding powershell to path solved it for me. 

Path for Windows 10 64 bit.
`C:\Windows\System32\WindowsPowerShell\v1.0`

**Comment by jysoo** [comment]
Ah yes. I forgot to update. I had the wrong path for Powershell, so I thought that couldn't be the cause of the error, but went back to it eventually. :)
