### ISSUE TITLE
error "dial tcp: lookup mailsjobq1.servicebus.windows.net on 10.96.0.10:53: server misbehaving"

### ISSUE THREAD

**Issue by MoosaSaadat** [kubernetes/minikube#13882]
### What Happened?

I am using Keda with Azure Service Bus but I am unable to make a connection with Azure. I got the above error. I believe something is wrong with the DNS. Here are the logs:

**coredns logs:**
```
[ERROR] plugin/errors: 2 mailsjobq1.servicebus.windows.net. A: read udp 172.17.0.4:55758->192.168.49.1:53: i/o timeout
[ERROR] plugin/errors: 2 mailsjobq1.servicebus.windows.net. AAAA: read udp 172.17.0.4:35915->192.168.49.1:53: i/o timeout
[ERROR] plugin/errors: 2 mailsjobq1.servicebus.windows.net. AAAA: read udp 172.17.0.4:53967->192.168.49.1:53: i/o timeout
[ERROR] plugin/errors: 2 mailsjobq1.servicebus.windows.net. A: read udp 172.17.0.4:34764->192.168.49.1:53: i/o timeout
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8380208/log.txt)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by klaases** [comment]
Hi @MoosaSaadat, this sounds like a networking issue. Were you able to get this resolved?

**Comment by MoosaSaadat** [comment]
Hi @klaases 
I was unable to solve the issue. This is for local testing so I didn't spend much time on it. Eventually moved the cluster to Azure.
Although, I tried multiple solutions I found online (for DNS resolution) but nothing helped.
