### ISSUE TITLE
why the cpu usage of pod always zero？

### ISSUE THREAD

**Issue by liaochan** [kubernetes/minikube#13898]
### What Happened?

I am runing a hpa test in minikube.The metric-server works fine. I could get the memory information when i run the ‘kubectl top pod ’ and it also shows in minikube dashboard.

I deployede a php app and set the initial replicas as 5, then the hpa began to work and one pod left at last. However, when I made stress test  to the pod by wget pod‘s ip, the pod's cpu usage is always zero through ‘kubectl top pod ’ and dashboard. and the pods didn't autoscale. Actually, I could get the wget process by command ‘top’ when I entered the test container. 
![image](https://user-images.githubusercontent.com/43428515/161245214-3d4bc142-ec4a-48d2-be28-46998288ae2f.png)![image](https://user-images.githubusercontent.com/43428515/161245461-ab5b869d-da8c-40c8-8cf6-2c8a615eba4f.png)![image](https://user-images.githubusercontent.com/43428515/161245527-ccf792d6-391a-4bf3-8975-6ad8fcd5406d.png)
BTW, i could get the cpu and memory usage of the node.![image](https://user-images.githubusercontent.com/43428515/161244748-85158e4e-08ee-4a28-9d65-8ae95e2c7cd1.png)

I've try many ways to fix it but failed, even the prometheus could not got the cpu metrics of pods. so, can anyone help me to solve it?![image](https://user-images.githubusercontent.com/43428515/161246420-0d0caf44-2c37-4b03-9d33-c329d336808d.png)
environment:
minikube version: v1.25.2
Docker Desktop 4.6.1
**PC:latest version of mac with docker&&hyperkit and windows10 with docker&&hyper-V(I tried it in two systems but got same situation)**

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8396873/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @liaochan, thanks for reporting your issue with minikube!

We made a change to the metric reporting timing of minikube which seemed to disable metrics altogether, this is going to be reverted in the next release of minikube.

In the meantime, you can append `--extra-config=kubelet.housekeeping-interval=10s` or `--disable-optimizations` to `minikube start` and your issue should be resolved.

**Comment by liaochan** [comment]
> Hi @liaochan, thanks for reporting your issue with minikube!
> 
> We made a change to the metric reporting timing of minikube which seemed to disable metrics altogether, this is going to be reverted in the next release of minikube.
> 
> In the meantime, you can append `--extra-config=kubelet.housekeeping-interval=10s` or `--disable-optimizations` to `minikube start` and your issue should be resolved.

thanks a lot 😭!!!

**Comment by willersonsp** [comment]
> Hi @liaochan, thanks for reporting your issue with minikube!
> 
> We made a change to the metric reporting timing of minikube which seemed to disable metrics altogether, this is going to be reverted in the next release of minikube.
> 
> In the meantime, you can append `--extra-config=kubelet.housekeeping-interval=10s` or `--disable-optimizations` to `minikube start` and your issue should be resolved.

just reporting that --disable-optimizations worked here, pod metrics wasnt working correctly, using that option it started to work.

**Comment by rwatler** [comment]
Confirmed that --disable-optimizations required to restore container level CPU using minikube v1.25.2.
