### ISSUE TITLE
Update release tags

### ISSUE THREAD

**Issue by dgoldsmith** [kubernetes/minikube#13899]
### What Happened?

A problem with the service tunnel was updated in issue #13756 and was merged to master on Mar 7, but the latest version tag of 1.25.2 is from Feb 24.  A process such as "brew install minikube" is still grabbing the 1.25.2 tag as the latest and does not include the patched code.

Please add an additional release tag such as 1.25.3.

### Attach the log file

No logs provided

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @dgoldsmith, thanks for reporting your issue with minikube!

We're looking at releasing `1.26.0` soon, we're just waiting for the ISO arm64 support to get finished up (https://github.com/kubernetes/minikube/pull/13762).

Once that's complete we will immediately be releasing, thank you for your patience!
