### ISSUE TITLE
Support adding external nodes to cluster

### ISSUE THREAD

**Issue by alfhad** [kubernetes/minikube#13893]
### What Happened?

I am trying to setup a 3 node cluster with minikube. I have successfully started a single node cluster and have also configured calico(CNI).

While adding nodes to this cluster using ```minikube node add``` an individual node gets added into the cluster with some configuration. Instead I want to add an external VM as a node to this cluster using either it's IP_ADDRESS or HOSTNAME.
Is this possible with minikube ? If yes, how is it done ?

Thanks!

### Attach the log file

Not attaching the log file since I am not facing any kind of error, but seeking help with adding nodes to the cluster.

### Operating System

Redhat/Fedora

### Driver

KVM2

**Comment by spowelljr** [comment]
Hi @alfhad, this is currently not a supported case, ideally in the future we would support this if we have the resources to implement it.

Here's a Slack thread about this question incase it provides some insight for you:
https://kubernetes.slack.com/archives/C1F5CT6Q1/p1618153463048100
