### ISSUE TITLE
[Question] extra args for minikube oci driver

### ISSUE THREAD

**Issue by zhan9san** [kubernetes/minikube#13892]
### What Happened?

There are many `xxx driver only` in `minikube start --help`.

For `docker` and `podman` drivers, could we unified them in one args, like `--extra-args`, and then pass this args to `CreateContainerNode` function as below. https://github.com/kubernetes/minikube/blob/03b5bb7bef42648bcf4d88f62f0f5337a1d55f8c/pkg/drivers/kic/oci/oci.go#L156-L180

If we do so, some features can be easier implemented without code change, e.g.

Feature | With `--extra-args` | Without `--extra-args`
---|---|--
Run Minikube container with a static IP | --extra-args ip=192.168.10.3 | add a parameter like `--ip` to `minikube start`
Run Minikube container in a subnet | --extra-args subnet=192.168.10.0/30 | add a parameter like `--subnet` to `minikube start` #12315 #13730 #13766 
Expose port in Minikube container | --extra-args publish=80:8080 | add a parameter like `--ports=[]` to `minikube start` 
etc | TBD | add a new parameter

I am not sure `extra-args` is a better design, and some validations may be lost.

Let me know what you think.

```shell
minikube start --help | grep only
      --dns-proxy=false: Enable proxy for NAT DNS requests (virtualbox driver only)
      --download-only=false: If true, only download and cache files for later use - don't install or start anything.
      --extra-disks=0: Number of extra disks created and attached to the minikube VM (currently only implemented for hyperkit and kvm2 drivers)
      --host-dns-resolver=true: Enable host resolver for NAT DNS requests (virtualbox driver only)
      --host-only-cidr='192.168.59.1/24': The CIDR to be used for the minikube VM (virtualbox driver only)
      --host-only-nic-type='virtio': NIC Type used for host only network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
      --hyperkit-vpnkit-sock='': Location of the VPNKit socket used for networking. If empty, disables Hyperkit VPNKitSock, if 'auto' uses Docker for Mac VPNKit connection, otherwise uses the specified VSock (hyperkit driver only)
      --hyperkit-vsock-ports=[]: List of guest VSock ports that should be exposed as sockets on the host (hyperkit driver only)
      --hyperv-external-adapter='': External Adapter on which external switch will be created if no external switch is found. (hyperv driver only)
      --hyperv-use-external-switch=false: Whether to use external switch over Default Switch if virtual switch not explicitly specified. (hyperv driver only)
      --hyperv-virtual-switch='': The hyperv virtual switch name. Defaults to first found. (hyperv driver only)
      --kvm-hidden=false: Hide the hypervisor signature from the guest in minikube (kvm2 driver only)
      --kvm-network='default': The KVM default network name. (kvm2 driver only)
      --kvm-numa-count=1: Simulate numa node count in minikube, supported numa node count range is 1-8 (kvm2 driver only)
      --kvm-qemu-uri='qemu:///system': The KVM QEMU connection URI. (kvm2 driver only)
      --listen-address='': IP Address to use to expose ports (docker and podman driver only)
      --nat-nic-type='virtio': NIC Type used for nat network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
      --nfs-share=[]: Local folders to share with Guest via NFS mounts (hyperkit driver only)
      --nfs-shares-root='/nfsshares': Where to root the NFS Shares, defaults to /nfsshares (hyperkit driver only)
      --no-kubernetes=false: If set, minikube VM/container will start without starting or configuring Kubernetes. (only works on new clusters)
      --no-vtx-check=false: Disable checking for the availability of hardware virtualization before the vm is started (virtualbox driver only)
      --ports=[]: List of ports that should be exposed (docker and podman driver only)
      --ssh-ip-address='': IP address (ssh driver only)
      --ssh-key='': SSH key (ssh driver only)
      --ssh-port=22: SSH port (ssh driver only)
      --ssh-user='root': SSH user (ssh driver only)
      --uuid='': Provide VM UUID to restore MAC address (hyperkit driver only)
      --vm=false: Filter to use only VM Drivers
```

### Attach the log file

None

### Operating System

Other

### Driver

Docker

**Comment by klaases** [comment]
Hi @[zhan9san](https://github.com/zhan9san), we are always open to open to improving the minikube user experience.

In this case, it looks like having multiple persistent settings would be helpful, rather than entering numerous flags on `minikube start`.

**Have you tried looking at the minikube config mechanism?**
https://minikube.sigs.k8s.io/docs/commands/config/

With a minikube config, you can make many changes that will persist when starting minikube.

**Comment by zhan9san** [comment]
Hi @klaases 

Thanks for your attention. 

Sorry for no making myself understood. Let me highlight the key point.

If we use `--extra-args`,
1. There is no need to update the code when someone wants to customize the Minikube container's behavior. Instead, we only need to update the document showing how to implement the feature.
2. Reduce the code size

Besides, `--extra-args` would be configured in config file as well.

**Comment by afbjorklund** [comment]
In the original libmachine design, the flags were per driver and not global like in minikube.

So it was a side effect if forking and including the drivers, possibly also the cli lib used.

**Comment by klaases** [comment]
Hi @zhan9san, we currently allow for arguments and the configuration files. However, if we modify an `--extra-args` parameter, this might conceal some combination of arguments.

While this may add some convenience, we also find that it may add complexity.

1. Have you tried the config mechanism that was previously mentioned? This would be helpful in the sense that it allows for the arguments to be set as a default in a file, and therefore they no longer need to be passed as arguments when starting minikube.

2. Another suggestion would be to create a small bash script for your use case. With a script, you could customize the additional args that are needed in varying scenarios. So the list of args could be stored in the bash script, and they could be parameterized and called upon later.

I agree that having a large number of arguments can become unwieldily, and it makes sense to work on ways to more highly organize them.

**Comment by zhan9san** [comment]
@klaases 

Thanks for your update. Please allow me to recap the issue.

I know the `config mechanism`, but it's a different scenario.

The key point is for how to implement new features in Minikube.

Assume features list in the first column is not supported in Minikube.

Let us compare how Minikube implement them with `--extra-args` and without `--extra-args`.

As we can see, if `--extra-args` is supported, the new features can be implemented without any code changes in Minikube. Instead, we have to create another pull requests to wrapper the parameters and pass it to docker daemon one by one.

Feature | With `--extra-args` | Without `--extra-args`
---|---|--
Run Minikube container with a static IP | --extra-args ip=192.168.10.3 | add a parameter like `--ip` to `minikube start`
Run Minikube container in a subnet | --extra-args subnet=192.168.10.0/30 | add a parameter like `--subnet` to `minikube start` #12315 #13730 #13766 
Expose port in Minikube container | --extra-args publish=80:8080 | add a parameter like `--ports=[]` to `minikube start` 
etc | TBD | add a new parameter

Hope I express myself clearly.

**Comment by afbjorklund** [comment]
This is both a pro and a con, less "typing" of arguments also means more chance of breakage by not checking them.

It is similar to a programming language, where you have named parameters ("args") and pass in dictionaries ("kwargs")
