### ISSUE TITLE
Minikube start ignores proxy

### ISSUE THREAD

**Issue by lazydream** [kubernetes/minikube#13897]
### What Happened?

I'm trying to run the minikube cluster with `hyperkit` and `containerd`. I'm also using proxy and set environment variables according to [minikube vpn and proxy guide](https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/).

I've set up a local proxy on localhost:3128 and exported following environment variables to zshrc:
```
export http_proxy='http://localhost:3128'
export https_proxy='http://localhost:3128'
export HTTP_PROXY='http://localhost:3128'
export HTTPS_PROXY='http://localhost:3128'
export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.39.0/24,192.168.49.2
```

Also I've tried to start minikube with explicit assignment of http proxy in `--docker-env` (starting with just `minikube start` gives the same result):
```
minikube start --docker-env HTTP_PROXY=$HTTP_PROXY --docker-env HTTPS_PROXY=$HTTPS_PROXY --docker-env http_proxy=$http_proxy --docker-env https_proxy=$https_proxy --docker-env NO_PROXY=$NO_PROXY
😄  minikube v1.25.2 on Darwin 11.6.4
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=10, Memory=12288MB, Disk=122880MB) ...
❗  Local proxy ignored: not passing HTTP_PROXY=http://localhost:3128 to docker env.
❗  Local proxy ignored: not passing HTTPS_PROXY=http://localhost:3128 to docker env.
❗  Local proxy ignored: not passing HTTP_PROXY=http://localhost:3128 to docker env.
❗  Local proxy ignored: not passing HTTPS_PROXY=http://localhost:3128 to docker env.
🌐  Found network options:
    ▪ HTTP_PROXY=http://localhost:3128
❗  You appear to be using a proxy, but your NO_PROXY environment does not include the minikube IP (192.168.64.25).
📘  Please see https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/ for more details
    ▪ HTTPS_PROXY=http://localhost:3128
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.39.0/24,192.168.64.7
    ▪ http_proxy=http://localhost:3128
    ▪ https_proxy=http://localhost:3128
❗  This VM is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
📦  Preparing Kubernetes v1.23.3 on containerd 1.4.12 ...
    ▪ env HTTP_PROXY=http://localhost:3128
    ▪ env HTTPS_PROXY=http://localhost:3128
    ▪ env http_proxy=http://localhost:3128
    ▪ env https_proxy=http://localhost:3128
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.39.0/24,192.168.64.7
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

What should I do to pass proxy correctly to minikube when starting the cluster?

### Attach the log file

[minikube_logs.txt](https://github.com/kubernetes/minikube/files/8395096/minikube_logs.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by bugalwena** [comment]
[minikube_logs.txt](https://github.com/kubernetes/minikube/files/8395326/minikube_logs.txt)

Very frustrating for God All-Mother Bugal Wena. Swearing helps

**Comment by zhan9san** [comment]
Hi @lazydream 

Could you plz try to use IP address instead of localhost?

e.g.
http://192.168.31.100:3128

**Comment by lazydream** [comment]
> Hi @lazydream
> 
> Could you plz try to use IP address instead of localhost?
> 
> e.g. http://192.168.31.100:3128

Maybe it's better to try with `host.minikube.internal` ? With this proxy there is no more error about ignored proxy but now process hungs at Creating hyperkit VM stage. It seems like it cannot connect to my host machine from Hyperkit

**Comment by zhan9san** [comment]
Hi @lazydream 

Have you tried to delete the broken cluster and recreate it in a clear environment?

1. How to delete

```
minikube delete
```

2. Recreate

If it still doesn't work, would you please provide the full commands?

**Comment by lazydream** [comment]
Yes, I delete old cluster.

```
minikube stop && minikube delete
✋  Stopping node "minikube"  ...
🛑  1 node stopped.
🔥  Deleting "minikube" in hyperkit ...
💀  Removed all traces of the "minikube" cluster.
~ % echo $HTTP_PROXY
http://192.168.2.19:3128
~ % echo $HTTPS_PROXY
http://192.168.2.19:3128
~ % minikube start
😄  minikube v1.25.2 on Darwin 11.6.4
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=10, Memory=12288MB, Disk=122880MB) ...\
```

And then in logs:
```

❌  Exiting due to DRV_CP_ENDPOINT: failed to lookup ip for ""
💡  Suggestion:

    Recreate the cluster by running:
    minikube delete
    minikube start
```

**Comment by sharifelgamal** [comment]
@lazydream could you provide the detailed minikube logs with `minikube logs --file=logs.txt`. It'll help us figure out why hyperkit is hanging.

**Comment by kind03** [comment]
Your proxy is for circumventing the China Greate Firewall (GFW) correct? Then I know why it is not working. It is not releated to hyperkit or virutalbox at all.

I checked the [source code](https://github.com/kubernetes/minikube/blob/f567893cdbb8e98a0348c1d93455af71cf6ce12c/pkg/minikube/proxy/proxy.go) of minikube. "Local proxy ignored" actually means that your proxy url is set to localhost (127.0.*) and minikube thinks you set the proxy incorrectly so it will just ignore this setting.

The resolution is just to edit your host file (for Windows it is in C:\Windows\System32\drivers\etc\hosts), to give 127.0.0.1 a hostname. I opened the host file on my machine and found minikue has already set one domain name for 127.0.0.1 for me:

127.0.0.1 kubernetes.docker.internal

So I just change my http_proxy and https_proxy to http://kubernetes.docker.internal:1235.

Then restart the minikue. The "Local proxy ignored" message is gone and I finally can download the image from gcr.io!

**Comment by Acture** [comment]
having the same issue as @kind03 mentioned.

**Comment by bugalwena** [comment]
Thank you for your response.

The VS Code editor an untapped reservoir of advanced potential; I'm barely
scratching the surface.

I must admit I didn't work much with Minikube software at the time, and VS
Code workspace has evolved since then.  It's not hard work.

I'm back at my office over the weekend. I will follow up on existing issues
with Minikube/Kubernetes

I will keep you posted.

Cheers

**Comment by flmelody** [comment]
solved?
