### ISSUE TITLE
minikube install on Windows 11 Home fails. "The Hyper-V role cannot be installed on Windows 10 Home"

### ISSUE THREAD

**Issue by 1dropaflame** [kubernetes/minikube#13919]
### What Happened?

 minikube start fails on Windows 11 Home.

 StartHost failed, but will try again: creating host: create: precreate: Hyper-V PowerShell Module is not available
* Creating hyperv VM (CPUs=2, Memory=3000MB, Disk=20000MB) ...
* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: precreate: Hyper-V PowerShell Module is not available

"The Hyper-V role cannot be installed on Windows 10 Home"   https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v

Is it possible to install minikube at all?

```
PS C:\Users\Me\.minikube> minikube start
* minikube v1.25.2 on Microsoft Windows 11 Home 10.0.22000 Build 22000
* Using the hyperv driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.25.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.25.2.iso: 237.06 MiB / 237.06 MiB [ 100.00% 10.69 MiB p/s 22s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.23.3 preload ...
    > preloaded-images-k8s-v17-v1...: 505.68 MiB / 505.68 MiB  100.00% 11.56 Mi
* Creating hyperv VM (CPUs=2, Memory=3000MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: Hyper-V PowerShell Module is not available
* Creating hyperv VM (CPUs=2, Memory=3000MB, Disk=20000MB) ...
* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: precreate: Hyper-V PowerShell Module is not available

X Exiting due to PR_HYPERV_MODULE_NOT_INSTALLED: Failed to start host: creating host: create: precreate: Hyper-V PowerShell Module is not available
* Suggestion: Run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Tools-All'
* Documentation: https://www.altaro.com/hyper-v/install-hyper-v-powershell-module/
* Related issue: https://github.com/kubernetes/minikube/issues/9040
```

### Attach the log file

PS C:\Users\Me\.minikube> minikube logs --file=log.txt
* The control plane node "" does not exist.
  To start a cluster, run: "minikube start"

### Operating System

Windows

**Comment by abs007** [comment]
Hyper-V doesn't run on Windows Home. You'd need Windows Pro for that.

Here you can find the list of all the drivers supported for Windows:
https://minikube.sigs.k8s.io/docs/drivers/

Personally, I'm using Docker as the minikube driver. So, I run Docker desktop on the background while using minikube.

**Comment by abs007** [comment]
Yes, the answer there is what I mentioned.

**Comment by 1dropaflame** [comment]
https://stackoverflow.com/questions/71774813/minikube-fails-to-start-on-windows-11-home-and-docker-desktop

**Comment by sharifelgamal** [comment]
Using the docker driver instead of hyper-v on machines that don't support it is the best solution here.
