### ISSUE TITLE
minikube service doesn't work

### ISSUE THREAD

**Issue by eduardocalfaia** [kubernetes/minikube#13914]
### What Happened?

The minikube service starts but the simple webpage with the hello world is not showed. I am using minikube 1.25.2, after the update the service stopped working.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8418851/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @eduardocalfaia, thanks for reporting your issue with minikube!

This is a known regression with 1.25.2, we have made a fix and it will be included with the next release of minikube.

In the meantime trying using a binary from this comment that has the fix included with it and it should fix the issue you're experiencing, thanks!

https://github.com/kubernetes/minikube/issues/13736#issuecomment-1063470210

**Comment by medyagh** [comment]
@eduardocalfaia I belive we have fixed this issue, please reopen if u still experience the issue
