### ISSUE TITLE
Error while installing ingress-nginx on minikube

### ISSUE THREAD

**Issue by codesInML** [kubernetes/minikube#13928]
### What Happened?

I'm trying to install ingress-nginx on my mac os. I'm using minikube v1.25.2 with docker driver.

I've followed the way the ingress docs said I should install it by running the first step which was
> kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/cloud/deploy.yaml

Then since I'm using minikube, I also ran the command
> minikube addons enable ingress

but I keep getting this error, even on multiple tries

> After the addon is enabled, please run "minikube tunnel" and your ingress resources would be available at "127.0.0.1"
    ▪ Using image k8s.gcr.io/ingress-nginx/controller:v1.1.1
    ▪ Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
    ▪ Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
🔎  Verifying ingress addon...
❌  Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.23.3/kubectl apply -f /etc/kubernetes/addons/ingress-deploy.yaml: Process exited with status 1
stdout:
namespace/ingress-nginx unchanged
serviceaccount/ingress-nginx unchanged
serviceaccount/ingress-nginx-admission unchanged
role.rbac.authorization.k8s.io/ingress-nginx unchanged
role.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
clusterrole.rbac.authorization.k8s.io/ingress-nginx unchanged
clusterrole.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
rolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged
rolebinding.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx unchanged
clusterrolebinding.rbac.authorization.k8s.io/ingress-nginx-admission unchanged
configmap/ingress-nginx-controller unchanged
configmap/tcp-services unchanged
configmap/udp-services unchanged
service/ingress-nginx-controller unchanged
service/ingress-nginx-controller-admission unchanged
deployment.apps/ingress-nginx-controller configured
ingressclass.networking.k8s.io/nginx unchanged
validatingwebhookconfiguration.admissionregistration.k8s.io/ingress-nginx-admission configured
stderr:
Error from server (Invalid): error when applying patch:

[minikube_addons.log](https://github.com/kubernetes/minikube/files/8453384/minikube_addons.log)

Also when i run 
> kubectl get pods -n ingress-nginx

I get the following
> NAME                                       READY   STATUS      RESTARTS   AGE
ingress-nginx-admission-create-95jrx       0/1     Completed   0          70m
ingress-nginx-admission-patch-rtgzr        0/1     Completed   0          70m
ingress-nginx-controller-cc8496874-f77j9   1/1     Running     0          68m

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8453355/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by sharifelgamal** [comment]
This is a documentation issue, ingress on the docker driver on macOS requires `minikube tunnel` to be run in order to work.

**Comment by klaases** [comment]
Hi @codesInML, were you able to run `minikube tunnel` and get this to work?

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @codesInML – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
