### ISSUE TITLE
Registries documentation does not mention how to handle multiple nodes

### ISSUE THREAD

**Issue by fabb** [kubernetes/minikube#13927]
The documentation mentions that running this command will allow to push to the minikube registry:
```
docker run --rm -it --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):5000"
```
https://minikube.sigs.k8s.io/docs/handbook/registry/

The documentation does not mention that when using multiple nodes (`minikube start --nodes 2`), each node has its own registry, and pushing images to `localhost:5000` will only push images to the docker registry of the master node. So when pods are created on other nodes than the master, they will fail with an `ImagePullBackOff` error.

It would be helpful if the documentation warned about this, or even suggested how to proceed when using multiple nodes.

**Comment by fabb** [comment]
nvm, i forgot to pass `--insecure-registry "10.0.0.0/24"` when starting minikube 🙈

**Comment by afbjorklund** [comment]
The localhost proxy should still be able to find the cluster registry, even when deployed on multiple nodes.
