### ISSUE TITLE
[Documentation] minikube start

### ISSUE THREAD

**Issue by ZCai319** [kubernetes/minikube#13921]
I follow the exact steps, copy every command and paste it in the command line (of my project in Intellij). I first tried `minikube service <service-name>` on my own project...didn't work. Now I went back to the basics and those don't seem to work either. 

I use the command and it redirects me to the site with url `<minikube-ip>:<randomport>` which should work according to a lot of sites, but it just doesn't work and I don't know why. (I'm using the Docker-driver for minikube)
![image_2022-04-07_105820](https://user-images.githubusercontent.com/54841677/162161867-76de0a3d-db29-4f7f-9c2f-71f7ce7fcb83.png)
![image](https://user-images.githubusercontent.com/54841677/162162205-c1dd2607-06d7-4a32-bf01-9b7c672af1e4.png)
![image_2022-04-07_105751](https://user-images.githubusercontent.com/54841677/162161765-c25d7c8f-d4b9-4bf0-86ae-13e3952328a3.png)

**Comment by shubham-cmyk** [comment]
Try port forwarding.
