### ISSUE TITLE
Access App deployment outside Master (VM)

### ISSUE THREAD

**Issue by cantprogram01** [kubernetes/minikube#13931]
### What Happened?

I have this Lab,

I'm Using Windows 11, Installed VM Workstation PRO

I created Linux Centos VM

> Inside the centos vm

- installed kubectl
- installed minikube
- installed docker driver

> I create cluster inside the centos using minikube start

- cluster is working deployment of apps and exposing of apps is working...
- I can curl the IP of the deployed app

ISSUE:

when I use the URL (minikube service <service name> --url) outside of Linux, meaning on my Windows 11 chrome browser, i cannot access it..
even tried using the ip for @ kubectl get all

My settings: 

- firewalld disabled in centos
- centos vm network adapter is bridged mode (it replicate physical network connection state)

### Attach the log file

na

### Operating System

Windows

### Driver

Docker

**Comment by klaases** [comment]
Host Windows > VM Workstation PRO > CentOS VM > Minikube

This might not be an issue with minikube, as it is accessible via Linux (CentOS).

It could be that networking is not working between the other windows hosts.

From what I can tell, this isn't an issue with minikube but the host/vm configuration.

**Comment by klaases** [comment]
Hi @cantprogram01 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
