### ISSUE TITLE
minikube service does not open up a browser

### ISSUE THREAD

**Issue by ondrej-ivanko** [kubernetes/minikube#13930]
### What Happened?

Running `minikube service --https=true -n <namespace> <service name>` does not fire up the browser like it used to do in minikube version 1.24.x.

Workaround is to add --url flag which display url in terminal and clicking it opens browser.

Logs from the above mentioned command without --url flag:

I0408 22:25:45.389938  110922 out.go:297] Setting OutFile to fd 1 ...
I0408 22:25:45.390024  110922 out.go:349] isatty.IsTerminal(1) = true
I0408 22:25:45.390031  110922 out.go:310] Setting ErrFile to fd 2...
I0408 22:25:45.390058  110922 out.go:349] isatty.IsTerminal(2) = true
I0408 22:25:45.390149  110922 root.go:315] Updating PATH: /home/oji/.minikube/bin
I0408 22:25:45.390297  110922 mustload.go:65] Loading cluster: k8s-desktop-dev
I0408 22:25:45.390585  110922 config.go:176] Loaded profile config "k8s-desktop-dev": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0408 22:25:45.390915  110922 cli_runner.go:133] Run: docker container inspect k8s-desktop-dev --format={{.State.Status}}
I0408 22:25:45.433349  110922 host.go:66] Checking if "k8s-desktop-dev" exists ...
I0408 22:25:45.433558  110922 cli_runner.go:133] Run: docker system info --format "{{json .}}"
I0408 22:25:45.508784  110922 info.go:263] docker info: {ID:KGW5:K6Z5:2F6F:FU5H:EOP6:33G2:SDBE:T2DG:A6TV:BGO7:S7DY:YETZ Containers:1 ContainersRunning:1 ContainersPaused:0 ContainersStopped:0 Images:17 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff false] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:true KernelMemoryTCP:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:32 OomKillDisable:true NGoroutines:45 SystemTime:2022-04-08 22:25:45.454153788 +0200 CEST LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:0 KernelVersion:5.17.1-artix1-1 OperatingSystem:Artix Linux OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:12 MemTotal:33243942912 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:oji-latitude5511 Labels:[] ExperimentalBuild:false ServerVersion:20.10.14 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:de8046a5501db9e0e478e1c10cbcfb21af4c6b2d Expected:de8046a5501db9e0e478e1c10cbcfb21af4c6b2d} RuncCommit:{ID:v1.0.2-0-g52b36a2d Expected:v1.0.2-0-g52b36a2d} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Name:buildx Path:/usr/lib/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.8.1-docker] map[Name:compose Path:/usr/lib/docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShortDescription:Docker Compose Vendor:Docker Inc. Version:2.4.1] map[Name:scan Path:/usr/lib/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.1.0-227-g061fe0a0c5]] Warnings:<nil>}}
I0408 22:25:45.508864  110922 api_server.go:165] Checking apiserver status ...
I0408 22:25:45.508894  110922 ssh_runner.go:195] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0408 22:25:45.508916  110922 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" k8s-desktop-dev
I0408 22:25:45.532408  110922 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:49157 SSHKeyPath:/home/oji/.minikube/machines/k8s-desktop-dev/id_rsa Username:docker}
I0408 22:25:45.644541  110922 ssh_runner.go:195] Run: sudo egrep ^[0-9]+:freezer: /proc/1739/cgroup
I0408 22:25:45.650621  110922 api_server.go:181] apiserver freezer: "8:freezer:/docker/276ba6f07a4c28d22ce51f29cf75531a1a8fc354ac7d4942f2d7c8639030546b/kubepods/burstable/pod3945b1e8b0b0b711e2a9de93f17838d5/ca10f00244aef678d2e53aeb3b06e4491ea62b2e56bb1e2f451b5fb132df0a9a"
I0408 22:25:45.650697  110922 ssh_runner.go:195] Run: sudo cat /sys/fs/cgroup/freezer/docker/276ba6f07a4c28d22ce51f29cf75531a1a8fc354ac7d4942f2d7c8639030546b/kubepods/burstable/pod3945b1e8b0b0b711e2a9de93f17838d5/ca10f00244aef678d2e53aeb3b06e4491ea62b2e56bb1e2f451b5fb132df0a9a/freezer.state
I0408 22:25:45.656025  110922 api_server.go:203] freezer state: "THAWED"
I0408 22:25:45.656068  110922 api_server.go:240] Checking apiserver healthz at https://192.168.49.2:8443/healthz ...
I0408 22:25:45.659908  110922 api_server.go:266] https://192.168.49.2:8443/healthz returned 200:
ok
I0408 22:25:45.659925  110922 host.go:66] Checking if "k8s-desktop-dev" exists ...
I0408 22:25:45.660120  110922 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" k8s-desktop-dev
I0408 22:25:45.890142  110922 service.go:214] Found service: &Service{ObjectMeta:{es-desktop-dev-kb-http  es-desktop-dev  4768f3cf-02a9-42d8-a4d0-7d86de7dd841 981 0 2022-04-08 21:48:23 +0200 CEST <nil> <nil> map[common.k8s.elastic.co/type:kibana kibana.k8s.elastic.co/name:es-desktop-dev] map[] [{kibana.k8s.elastic.co/v1 Kibana es-desktop-dev 562c4b67-408f-466a-9c39-a1b73a9c2d24 0xc00061530e 0xc00061530f}] []  [{elastic-operator Update v1 2022-04-08 21:48:23 +0200 CEST FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:common.k8s.elastic.co/type":{},"f:kibana.k8s.elastic.co/name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"562c4b67-408f-466a-9c39-a1b73a9c2d24\"}":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":5601,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:https,Protocol:TCP,Port:5601,TargetPort:{0 5601 },NodePort:32444,AppProtocol:nil,},},Selector:map[string]string{common.k8s.elastic.co/type: kibana,kibana.k8s.elastic.co/name: es-desktop-dev,},ClusterIP:10.100.47.140,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.100.47.140],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0408 22:25:45.892954  110922 service.go:214] Found service: &Service{ObjectMeta:{es-desktop-dev-kb-http  es-desktop-dev  4768f3cf-02a9-42d8-a4d0-7d86de7dd841 981 0 2022-04-08 21:48:23 +0200 CEST <nil> <nil> map[common.k8s.elastic.co/type:kibana kibana.k8s.elastic.co/name:es-desktop-dev] map[] [{kibana.k8s.elastic.co/v1 Kibana es-desktop-dev 562c4b67-408f-466a-9c39-a1b73a9c2d24 0xc00106cbac 0xc00106cbad}] []  [{elastic-operator Update v1 2022-04-08 21:48:23 +0200 CEST FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:common.k8s.elastic.co/type":{},"f:kibana.k8s.elastic.co/name":{}},"f:ownerReferences":{".":{},"k:{\"uid\":\"562c4b67-408f-466a-9c39-a1b73a9c2d24\"}":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":5601,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:https,Protocol:TCP,Port:5601,TargetPort:{0 5601 },NodePort:32444,AppProtocol:nil,},},Selector:map[string]string{common.k8s.elastic.co/type: kibana,kibana.k8s.elastic.co/name: es-desktop-dev,},ClusterIP:10.100.47.140,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.100.47.140],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0408 22:25:45.893026  110922 host.go:66] Checking if "k8s-desktop-dev" exists ...
I0408 22:25:45.893182  110922 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" k8s-desktop-dev

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8455142/log.txt)

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
It should be a fairly straightforward call to `xdg-open`, you might want to try it to see if it has better error reporting ?

**Comment by ondrej-ivanko** [comment]
> It should be a fairly straightforward call to `xdg-open`, you might want to try it to see if it has better error reporting ?
> 
> ```
> xdg-open https://minikube.sigs.k8s.io/docs/
> ```

Hi @afbjorklund,

I tried this and it works OK. It might be that newest minikube cli does not call xdg-open properly now.

When trying: `xdg-open $(minikube service --https=true -n es-desktop-dev es-desktop-dev-kb-http --url=true)` it opens up the browser like in previous minikube versions.

**Comment by ondrej-ivanko** [comment]
seems to be fixed in newer versions of minikube, or maybe it was issue with xdg-open.
