### ISSUE TITLE
Deleting pods with host mounts takes a long time

### ISSUE THREAD

**Issue by ashernevins** [kubernetes/minikube#1394]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT (maybe?)

Minikube version (use minikube version): v0.18.0

Environment:

OS (e.g. from /etc/os-release): OS X
VM Driver (e.g. cat ~/.minikube/machines/minikube/config.json | grep DriverName): virtualbox
ISO version (e.g. cat ~/.minikube/machines/minikube/config.json | grep -i ISO or minikube ssh cat /etc/VERSION): v0.18.0

**What happened**:

When mounting a host volume to a pod in minikube (mounted to host with the default /Users mount), a pod takes 30-60 seconds to destroy using `kubectl delete pods --all --force`. I am unsure if this is an unexpected behaviour, but doing the same operation in GKE is significantly faster. Is there something that may be impacting the time it takes to delete that I can fix?

**Comment by r2d4** [comment]
ref #1423
