### ISSUE TITLE
minikube image load doesn't show any progress by default, and it should

### ISSUE THREAD

**Issue by matteoolivi** [kubernetes/minikube#13949]
### What Happened?

I ran `minikube image load <my really really big image>`, the command took a while, and stdout showed nothing.

I know that logs can be enabled with appropriate flags, and can convey some progress, but in my opinion **it'd be useful if by default the command showed some progress** (if nothing to know if everything is ok or not), that's akin to what's done for other commands such as `start`, that show progress to stdout even without logging

### Attach the log file

N/A

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
Currently the "minikube image" commands doesn't show any output at all, except for the in the log, which is a bad thing...

I'm not sure it will be possible to show progress bars like when using "docker load", but at least the _steps_ could be shown.

`minikube --alsologtostderr image load busybox`

1. pull image from registry
2. save image to disk
3. copy from cache to machine
4. load image from disk

**Comment by Shivansh-yadav13** [comment]
Is anyone working on this issue?

**Comment by matteoolivi** [comment]
@Shivansh-yadav13 apparently no. Do you have the time and want to fix that?

**Comment by Shivansh-yadav13** [comment]
@matteoolivi yes, I want to try working on this.

**Comment by medyagh** [comment]
This would be a neat feature ! If anyone interested in this issue I would be happy to review the PR

**Comment by Shivansh-yadav13** [comment]
@medyagh I have created a pr but I'm not sure if that is what this issue requests, I feel there is more to be done than what I have added please suggest changes. @matteoolivi @afbjorklund

**Comment by eggachecat** [comment]
Any updates?

**Comment by peterbecich** [comment]
Can we re-open this issue please?
