### ISSUE TITLE
imagePullPolicy of 'IfNotPresent' should pull images tagged as 'latest' but doesn't

### ISSUE THREAD

**Issue by boosh** [kubernetes/minikube#1395]
BUG REPORT:

**Minikube version**: v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX 10.12.4
- **VM Driver**: virtualbox
- **ISO version**: v0.18.0
- **Install tools**:
- **Others**:

**What happened**:
Running a k8s deployment with an `imagePullPolicy` of `IfNotPresent` and just an image name didn't force minikube to pull the image as per the [docs](https://kubernetes.io/docs/concepts/containers/images/#updating-images).

**What you expected to happen**:
K8s/minikube should have forced K8s to repull the image.

**How to reproduce it** (as minimally and precisely as possible):
Create a deployment with an `imagePullPolicy` of `IfNotPresent`, then build and run a docker image twice. The first time it pulls the image; the second time it just says it already has the image so doesn't bother pulling it again. This makes it impossible to force K8s under minikube from repulling an image that has since been rebuilt.

**Anything else do we need to know**:
Using an explicit tag of 'latest' doesn't force K8s to pull the image when run under minikube either, which directly conflicts the docs.

I'm not sure if this is an issue with K8s or minikube, but I assume minikube...

**Comment by r2d4** [comment]
I think these docs may be misleading. I don't think that an imagepullpolicy of IfNotPresent and latest tag will force a pull every time. You should just use the Always pull policy if you want that behavior

I will verify on non-minikube cluster

**Comment by boosh** [comment]
@r2d4 Unfortunately minikube requires an `imagePullPolicy` of `IfNotPresent`. Using `Always` doesn't work.

**Comment by dlorenc** [comment]
Minikube only requires `IfNotPresent` if the image you're trying to run only exists inside minikube. Otherwise Kubernetes will try to check with a registry to make sure the local image is up to date. Does that make sense?

**Comment by boosh** [comment]
Yes, that's my situation. I discovered this during development, where I don't want to have to be pushing containers up to, and pulling down from remote registries. I'm rebuilding my containers locally during my dev cycle, so I want to force K8s to repull the 'latest' tagged image for the particular service I'm working on. Is there a workaround for this?
