### ISSUE TITLE
Pulling an image by sha256 hash fails with an auth error

### ISSUE THREAD

**Issue by boosh** [kubernetes/minikube#1396]
BUG REPORT

**Minikube version**: v0.18.0

**Environment**:
- **OS**: OSX 10.12.4
- **VM Driver**: virtualbox
- **ISO version**: 0.18.0
- **Install tools**:
- **Others**:

**What happened**:
K8s couldn't pull an image by SHA256. An authentication error was returned instead. From `kubectl get pod`:

4s	4s	1	kubelet, minikube	spec.containers{survey}	Warning	Failed	Failed to pull image "survey@sha256:6882b4c826eddcd22ce1638cc70c12a37ce1ba088ae4917a3a9a50b91afa4844": rpc error: code = 2 desc = Error response from daemon: unauthorized: authentication required
4s	4s	1	kubelet, minikube	Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "survey" with ErrImagePull: "rpc error: code = 2 desc = Error response from daemon: unauthorized: authentication required"

**What you expected to happen**:
It should have pulled the image.

**How to reproduce it** (as minimally and precisely as possible):
Create a K8s deployment with an image SHA, e.g. survey@sha256:6882b4c826eddcd22ce1638cc70c12a37ce1ba088ae4917a3a9a50b91afa4844

Check logs with `kubectl get pod survey-xxxx`

**Anything else do we need to know**:
No

**Comment by r2d4** [comment]
Where are you trying to pull he image from?   It looks like it might be a private registry that requires credentials. You should see the registry-creds add on that we provide with minikube if that's the case

**Comment by boosh** [comment]
@r2d4 Just from the local registry installed with minikube. I've just done `minikube start`, built an image then tried to pull it by hash.

**Comment by dlorenc** [comment]
How did you setup the local registry?

Or are you just using the local docker daemon, and not doing any pulling?

What's your imagePullPolicy?

**Comment by boosh** [comment]
Literally all I've done is follow the [Hello Minikube](https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/) tutorial: Installed Docker for Mac, installed Minikube, ran `minikube start`, then built some docker images.

My `imagePullPolicy` is `IfNotPresent` because I'm rebuilding images in my local registry during development. See #1395 for more details. Using a SHA sum was an attempt to get around the issue in that ticket.

**Comment by dlorenc** [comment]
I'm going to resolve this one as a dup of #1395. I think these are basically the same issue.
