### ISSUE TITLE
Shorten the audit log dates

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#13977]
Currently:
```
==> Audit <==
|---------|---------------------|----------|--------------|---------|-------------------------------|-------------------------------|
| Command |        Args         | Profile  |     User     | Version |          Start Time           |           End Time            |
|---------|---------------------|----------|--------------|---------|-------------------------------|-------------------------------|
| delete  | --user minikube-gui | minikube | minikube-gui | v1.25.2 | Mon, 18 Apr 2022 15:52:01 PDT | Mon, 18 Apr 2022 15:52:01 PDT |
|---------|---------------------|----------|--------------|---------|-------------------------------|-------------------------------|
```

You can see the `Start Time` & `End Time` dates are quite long and include things like the day of the week which are unnecessary.

It would be nice to shorten these, maybe mm/dd/yyyy + time or something similar.

**Comment by Nikhil2001** [comment]
@spowelljr 

Your thoughts ?
I came up with two different formats, I think layout1 is good
const (

	RFC1123      = "Mon, 02 Jan 2006 15:04:05 MST" //currently we use
	Layout1 = "01/02/2006 15:04:05 MST" // change1
        Layout2 = "01/02/2006 15:04:05" // clean but do we need time zone, Right?
	
)

**Comment by afbjorklund** [comment]
It's much better to use a standard format, than to invent some custom format to save a few characters.

**Comment by Nikhil2001** [comment]
@medyagh
