### ISSUE TITLE
How to use Apple M1 Max GPU in Minikube?

### ISSUE THREAD

**Issue by hongery** [kubernetes/minikube#13981]
### What Happened?

I installed minikube on my mac, my computer is 2021 macbook pro M1 Max (arm64), but minikube supports NVIDIA GPU, not M1, is there a solution?

### Attach the log file

no logs

### Operating System

macOS (Default)

**Comment by afbjorklund** [comment]
I don't think that there is any support in minikube for using the host GPU on macOS systems, mostly because there are no drivers that are able to pass-through them to the Linux operating system (in the VM being used)

https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/

**Comment by Hongery** [comment]
So is it possible to provide a driver for mac GPU?

**Comment by afbjorklund** [comment]
I have only seen some attempts to speed up virtualization, by making the VM use the host GPU for rendering the interface.

But have not yet seen any examples where a Linux VM is able to use the host GPU for something like maching learning ?

**Comment by Hongery** [comment]
Yes, there is no such example.I want to use k8s and volcano to do some machine learning related model acceleration attempts, but it seems to only support NVIDIA GPU, I want to use my mac GPU to do it.

**Comment by dirtyValera** [comment]
Hi @hongery, have you managed to solve this?
