### ISSUE TITLE
如何获取这个镜像：k8s.gcr.io/echoserver:1.4

### ISSUE THREAD

**Issue by youyj-tech** [kubernetes/minikube#13996]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
macos

**Comment by zhan9san** [comment]
国内是无法直接获取这个镜像的，你可以通过阿里云的镜像站点获取

```shell
$ docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/echoserver:1.4
1.4: Pulling from google_containers/echoserver
6d9e6e7d968b: Pull complete
a3ed95caeb02: Pull complete
cd23f57692f8: Pull complete
412c0feed608: Pull complete
dcd34d50d5ee: Pull complete
d3c51dabc842: Pull complete
b4241160ce0e: Pull complete
7abee76f69c0: Pull complete
Digest: sha256:5d99aa1120524c801bc8c1a7077e8f5ec122ba16b6dda1a5d3826057f67b9bcb
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/echoserver:1.4
registry.cn-hangzhou.aliyuncs.com/google_containers/echoserver:1.4
```

**Comment by peteliu66** [comment]
可以在启动minikube的时候通过参数，修改镜像仓库：
`$minikube start --cache-image=true --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers`

**Comment by klaases** [comment]
>You can modify the image repository through parameters when starting minikube: $ minikube start --cache-image=true --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
>
>It can be used normally

Hi @youyj-tech, did the above comments help resolve this issue?

If not, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

---

> 可以在启动minikube的时候通过参数，修改镜像仓库： `$ minikube start --cache-image=true --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers`
> 
> 这样就可以正常使用了

嗨@youyj-tech，上述评论是否有助于解决此问题？

如果没有，请随时通过使用 `/reopen` 评论重新打开问题。由于无法获得更多信息并且已经过去了一段时间，此问题将被关闭。

可能有帮助的其他信息：

* 问题是否出现在最新的 minikube 版本中

* 使用的确切 minikube 启动命令行

* 附上minikube日志的完整输出，运行`minikube logs --file=logs.txt`创建日志文件

感谢您分享您的经验！
