### ISSUE TITLE
Unable to Start minikube

### ISSUE THREAD

**Issue by mkum98** [kubernetes/minikube#13993]
Getting Below Error while trying to Start the minikube.. Please help

PS C:\windows\system32> minikube start --vm-driver="hyperv" --hyperv-virtual-switch="minikube"
* minikube v1.25.2 on Microsoft Windows 10 Pro 10.0.19043 Build 19043
* Using the hyperv driver based on user configuration
* Downloading VM boot image ...
E0421 01:11:50.695962   16784 iso.go:88] Unable to download https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso.sha256 Dst:C:\Users\b\.minikube\cache\iso\amd64\minikube-v1.25.2.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0] Decompressors:map[bz2:0x3d18fc0 gz:0x3d18fc0 tar:0x3d18fc0 tar.bz2:0x3d18fc0 tar.gz:0x3d18fc0 tar.xz:0x3d18fc0 tar.zst:0x3d18fc0 tbz2:0x3d18fc0 tgz:0x3d18fc0 txz:0x3d18fc0 tzst:0x3d18fc0 xz:0x3d18fc0 zip:0x3d18fc0 zst:0x3d18fc0] Getters:map[file:0xc000e3c6f0 http:0xc00051a1e0 https:0xc00051a3a0] Dir:false ProgressListener:0x3cb1040 Insecure:false Options:[0x1f14000]}: invalid checksum: Error downloading checksum file: Get "https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso.sha256": dial tcp 216.58.220.144:443: i/o timeout
* Downloading VM boot image ...
E0421 01:12:33.215143   16784 iso.go:88] Unable to download https://github.com/kubernetes/minikube/releases/download/v1.25.2/minikube-v1.25.2.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.25.2/minikube-v1.25.2.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.25.2/minikube-v1.25.2.iso.sha256 Dst:C:\Users\b\.minikube\cache\iso\amd64\minikube-v1.25.2.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0] Decompressors:map[bz2:0x3d18fc0 gz:0x3d18fc0 tar:0x3d18fc0 tar.bz2:0x3d18fc0 tar.gz:0x3d18fc0 tar.xz:0x3d18fc0 tar.zst:0x3d18fc0 tbz2:0x3d18fc0 tgz:0x3d18fc0 txz:0x3d18fc0 tzst:0x3d18fc0 xz:0x3d18fc0 zip:0x3d18fc0 zst:0x3d18fc0] Getters:map[file:0xc000d3aa90 http:0xc000501200 https:0xc000501220] Dir:false ProgressListener:0x3cb1040 Insecure:false Options:[0x1f14000]}: invalid checksum: Error downloading checksum file: Get "https://github.com/kubernetes/minikube/releases/download/v1.25.2/minikube-v1.25.2.iso.sha256": dial tcp 13.114.40.48:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
X Exiting due to INET_DOWNLOAD_TIMEOUT: Failed to cache ISO: unable to cache ISO:
  https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso.sha256 Dst:C:\Users\b\.minikube\cache\iso\amd64\minikube-v1.25.2.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0] Decompressors:map[bz2:0x3d18fc0 gz:0x3d18fc0 tar:0x3d18fc0 tar.bz2:0x3d18fc0 tar.gz:0x3d18fc0 tar.xz:0x3d18fc0 tar.zst:0x3d18fc0 tbz2:0x3d18fc0 tgz:0x3d18fc0 txz:0x3d18fc0 tzst:0x3d18fc0 xz:0x3d18fc0 zip:0x3d18fc0 zst:0x3d18fc0] Getters:map[file:0xc000e3c6f0 http:0xc00051a1e0 https:0xc00051a3a0] Dir:false ProgressListener:0x3cb1040 Insecure:false Options:[0x1f14000]}: invalid checksum: Error downloading checksum file: Get "https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso.sha256": dial tcp 216.58.220.144:443: i/o timeout
  https://github.com/kubernetes/minikube/releases/download/v1.25.2/minikube-v1.25.2.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.25.2/minikube-v1.25.2.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.25.2/minikube-v1.25.2.iso.sha256 Dst:C:\Users\b\.minikube\cache\iso\amd64\minikube-v1.25.2.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0] Decompressors:map[bz2:0x3d18fc0 gz:0x3d18fc0 tar:0x3d18fc0 tar.bz2:0x3d18fc0 tar.gz:0x3d18fc0 tar.xz:0x3d18fc0 tar.zst:0x3d18fc0 tbz2:0x3d18fc0 tgz:0x3d18fc0 txz:0x3d18fc0 tzst:0x3d18fc0 xz:0x3d18fc0 zip:0x3d18fc0 zst:0x3d18fc0] Getters:map[file:0xc000d3aa90 http:0xc000501200 https:0xc000501220] Dir:false ProgressListener:0x3cb1040 Insecure:false Options:[0x1f14000]}: invalid checksum: Error downloading checksum file: Get "https://github.com/kubernetes/minikube/releases/download/v1.25.2/minikube-v1.25.2.iso.sha256": dial tcp 13.114.40.48:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.25.2.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.25.2.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.25.2.iso.sha256 Dst:C:\Users\b\.minikube\cache\iso\amd64\minikube-v1.25.2.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0 0x3d18fc0] Decompressors:map[bz2:0x3d18fc0 gz:0x3d18fc0 tar:0x3d18fc0 tar.bz2:0x3d18fc0 tar.gz:0x3d18fc0 tar.xz:0x3d18fc0 tar.zst:0x3d18fc0 tbz2:0x3d18fc0 tgz:0x3d18fc0 txz:0x3d18fc0 tzst:0x3d18fc0 xz:0x3d18fc0 zip:0x3d18fc0 zst:0x3d18fc0] Getters:map[file:0xc000ddc660 http:0xc000308f60 https:0xc000308f80] Dir:false ProgressListener:0x3cb1040 Insecure:false Options:[0x1f14000]}: invalid checksum: Error downloading checksum file: Get "https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.25.2.iso.sha256": dial tcp 47.110.23.59:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by kumar6808** [comment]
checkout the link this might help.
[k8s]-https://learnk8s.io/

Getting started with Docker and Kubernetes on Windows 10
https://learnk8s.io/installing-docker-kubernetes-windows#:~:text=Installing%20Kubernetes%20on%20Windows%2010%20with%20Minikube,-Minikube%20is%20one&text=If%20you%20haven't%20done,can%20find%20the%20instructions%20here.&text=choco%20install%20minikube%20%2Dy%20Installing,accept%20licenses%20for%20the%20packages.

**Comment by klaases** [comment]
Hi @mkum98 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by yezhengli-Mr9** [comment]
> checkout the link this might help. [k8s]-https://learnk8s.io/
> 
> Getting started with Docker and Kubernetes on Windows 10 https://learnk8s.io/installing-docker-kubernetes-windows#:~:text=Installing%20Kubernetes%20on%20Windows%2010%20with%20Minikube,-Minikube%20is%20one&text=If%20you%20haven't%20done,can%20find%20the%20instructions%20here.&text=choco%20install%20minikube%20%2Dy%20Installing,accept%20licenses%20for%20the%20packages.

Not feel the link works.
Happened on two Ubuntu 22.04:
```bash
 minikube start
E0306 10:47:31.719042   14458 notify.go:54] Get https://storage.googleapis.com/minikube/releases.json: dial tcp [2404:6800:4007:800::201b]:443: connect: network is unreachable
Starting local Kubernetes cluster...
E0306 10:47:31.721271   14458 start.go:83] Error starting host: Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:818::201b]:443: connect: network is unreachable. Retrying.
E0306 10:47:31.723040   14458 start.go:83] Error starting host: Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:800::201b]:443: connect: network is unreachable. Retrying.
E0306 10:47:31.724766   14458 start.go:83] Error starting host: Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:82e::201b]:443: connect: network is unreachable. Retrying.
E0306 10:47:31.724777   14458 start.go:89] Error starting host:  Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:818::201b]:443: connect: network is unreachable
Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:800::201b]:443: connect: network is unreachable
Get https://storage.googleapis.com/minikube/minikube-0.6.iso: dial tcp [2404:6800:4007:82e::201b]:443: connect: network is unreachable
```
