### ISSUE TITLE
Minikube start failure

### ISSUE THREAD

**Issue by wwillfred** [kubernetes/minikube#14005]
### What Happened?

Running minikube start with hyperkit failed.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8534425/logs.txt)

**Comment by shubham-cmyk** [comment]
I think there is problem with the virtual box.

**Comment by klaases** [comment]
Hi @wwillfred – have you tried reinstalling hyperkit? Is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
