### ISSUE TITLE
[Question] How to build images into minikube node with containerd runtime?

### ISSUE THREAD

**Issue by hiroaki2020** [kubernetes/minikube#14018]
### What Happened?

Following [this guide from minikube official](https://minikube.sigs.k8s.io/docs/handbook/pushing/#5-building-images-inside-of-minikube-using-ssh), I am trying to build images from dockerfile into minikube node with containerd runtime. I run `minikube ssh` to go inside minikube and then run 
```
sudo buildctl build --frontend=dockerfile.v0 --local context=/PATH/TO/BUILD/CONTEXT --local dockerfile=/PATH/TO/DOCKERFILE
```
to build an image. After that, I run `sudo ctr images list` but there is no image.
I think this is not an error caused by minikube and it is just my mistake or a lack of knowledge to do this properly.
Could you elaborate a bit more about how to do this?

Related info
I use multinode cluster and want to build images into every node.
I want to make the time that images are built and then get ready to use in minikube nodes shorter and chose this No.5 method in the guide but if there is faster method, I also want to hear about it.

Thanks,

### Attach the log file

I provide logs later if necessary.

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
You need to use `sudo ctr -n k8s.io images list`, to view the Kubernetes namespace.

Alternative you can use `minikube image build` and `minikube image list` wrappers.

**Comment by hiroaki2020** [comment]
@afbjorklund Thank you for your kind support and quick reply.
> You need to use sudo ctr -n k8s.io images list, to view the Kubernetes namespace.
Thanks now I can see my built image but my k8s deployment resource cannot access the resource.
I used the following cmd in a minikube node to build my image.
```
sudo buildctl build --frontend=dockerfile.v0 --local context=/PATH/TO/BUILD/CONTEXT --local dockerfile=/PATH/TO/DOCKERFILE --output type=image,name=image_name:tag,push=false
```
Did I do anything wrong?

> Alternatively you can use minikube image build and minikube image list wrappers.
I want to use the fastest method. Is this faster than the one I'm working on?

> Eventually minikube should support pushing from control plane (build) to the other nodes...
That sounds great. I can build even faster then.

**Comment by afbjorklund** [comment]
Should have some better documentation about it, if I recall correctly you need to change the image pull policy (or use a tag other than "latest"), and to make sure to prefix with docker.io (or some other registry)

**Comment by hiroaki2020** [comment]
> Should have some better documentation about it, if I recall correctly you need to change the image pull policy (or use a tag other than "latest"), and to make sure to prefix with docker.io (or some other registry)

That sounds like you actually push image to dockerhub (="docker.io") in the official guide's example by changing the image pull policy to other than "Never" (maybe "IfNotPresent"?) and by prefixing image with "docker.io". Since [buildkit documentation](https://github.com/moby/buildkit) does not explain everything to a T, I am not 100% sure about this but maybe you push image to registry and pull it to minikube node. Do you know how to build image directly into minikube node by buildctl cmd?

**Comment by afbjorklund** [comment]
It was just a naming thing, an external registry is not used.

One method of distributing the image in the multi node setup, is to use the internal cluster registry. It could also use some updating, and better docs.

**Comment by afbjorklund** [comment]
> I want to use the fastest method. Is this faster than the one I'm working on?

It is the same, the method to use a local build context is somewhat undocumented.

`minikube image build file:///PATH/TO/BUILD/CONTEXT`

By default, the build context path will refer to something on the host that needs transferring.

But by stating it as an URL instead, it will be used in the VM - and file:// refers to a local path.

**Comment by afbjorklund** [comment]
> I am not 100% sure about this but maybe you push image to registry and pull it to minikube node.

If you look in the log, you can see what is happening:

`minikube --alsologtostderr image build -t myimage file:///tmp/build`

```
Run: sudo buildctl build --frontend dockerfile.v0 --local context=/tmp/build --local dockerfile=/tmp/build --output type=image,name=myimage:latest
...
#6 naming to myimage:latest done
```

So it is tagged with myimage, but that means docker.

`minikube ssh sudo crictl images`

```
IMAGE                                     TAG                  IMAGE ID            SIZE
...
docker.io/library/myimage                 latest               90d9ade2aa377       2.82MB
```

**Comment by afbjorklund** [comment]
Unfortunately, containerd doesn't really have a way to stream an image to a remote daemon the way docker does.

So if **not** wanting to use a registry, which is the fastest since it understand layers, it would be something like:

ctr images export image.tar image + scp image.tar node:/tmp + ssh node ctr images import /tmp/image.tar

With a local registry, there are no such steps needed. You would just use registry.kube-system.svc.cluster.local/image

**Comment by hiroaki2020** [comment]
Sorry for my late reply.
> It was just a naming thing, an external registry is not used.

Thank you for sharing this. I just confirmed that without using an external registry, my k8s deployment resource can properly access the image I built by running
```
buildctl build ... --output type=image,name=docker.io/username/image:tag,push=false
```
My k8s file is like
```
...
image: username/image:tag
imagePullPolicy: Never
...
```
Since I use multi-node cluster, I need to build images in each node though.
Sorry I need some time to digest things you said but I understand what I just did and `minikube image build` do the same internally. Then why official documentation says minikube ssh+buildctl is faster?

> Trying to start the image without the full name, gives error:

About this part, my k8s file needs to be
```
...
image: username/image:tag
...
```
instead of
```
...
image: image:tag
...
```
to work properly. Is this what you mean?

I knew about omitting imagePullPolicy and :latest tag but thx for your reminder.

> ctr images export image.tar image + scp image.tar node:/tmp + ssh node ctr images import /tmp/image.tar

So this is the fastest one. I'm going to try this.

You also recommended using local registry but then I have to build image and push it to registry and pull it when I create k8s deployment resource, which sounds slow. As I said,

> I want to make the time that images are built and then get ready to use in minikube nodes shorter

so I choose the other method.

**Comment by afbjorklund** [comment]
> So this is the fastest one. I'm going to try this.

It depends on the image.

You save the initial upload to the registry, since the image is already on the build node. But when you export the image, it will include _all_ layers. Even if you only modified the last one ? So there _could_ be a lot of transferring the base image over and over

The fastest is another registry

**Comment by afbjorklund** [comment]
> to work properly. Is this what you mean?

I find that the kubernetes image needs to be the same as the containerd image, i.e. to include the "docker.io/library" part.

`#6 naming to docker.io/library/testimage:testtag done`

`Container image "docker.io/library/testimage:testtag" already present on machine`

You can use another registry, such as gcr.io, but what you cannot do is omit the image (like we used to do, with docker)

Note that it never gets pushed anywhere, i.e. the registry isn't actually used

It is just used, to get away from the vague/undefined standards of the CRI.

**Comment by hiroaki2020** [comment]
> You save the initial upload to the registry, since the image is already on the build node. But when you export the image, it will include all layers. Even if you only modified the last one ? So there could be a lot of transferring the base image over and over
The fastest is another registry

Actually I am working on my project by myself, not on a team. Currently I am using minikube in dev env (and maybe in test env but not sure). I know k8s is not necessary for my small project but I use it to learn. So I do not have many occasions to export image. Do you still think I need to use registry?

> You can use another registry, such as gcr.io, but what you cannot do is omit the image (like we used to do, with docker)

> Note that it never gets pushed anywhere, i.e. the registry isn't actually used
It is just used, to get away from the vague / undefined standards of the CRI.

I understand. Thanks.

**Comment by afbjorklund** [comment]
> Do you still think I need to use registry?

No, but it is the most straight-forward way to distribute images within a multi-node cluster. Especially the new ones, with IPFS.

If you run a single-node cluster (the default minikube setup), then there is no need to run a registry (or a Docker VM) - at all.

**Comment by hiroaki2020** [comment]
> No, but it is the most straight-forward way to distribute images within a multi-node cluster. Especially the new ones, with IPFS.

I got it.
Thank you for your time and all the great answers to my questions.

**Comment by afbjorklund** [comment]
No worries, except for missing documentation there didn't seem to be anything "wrong" ?

**Comment by hiroaki2020** [comment]
> No worries, except for missing documentation there didn't seem to be anything "wrong" ?
There are a lot of other settings, like build context and build cache, that are more important to the overall turnaround

I understand. Thx.
