### ISSUE TITLE
Unable to start VM - This computer doesn't have VT-X/AMD-v enabled

### ISSUE THREAD

**Issue by gcsaba2** [kubernetes/minikube#14017]
### What Happened?

Related to issue #4816 

Running with --no-vtx-check seems to solve the issue.

Virtualization is enabled in BIOS and I'm able to start VMs and Docker on my Windows.

PS C:\WINDOWS\system32> minikube start
* minikube v1.25.2 on Microsoft Windows 10 Pro 10.0.19044 Build 19044
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

X Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900
  - https://github.com/kubernetes/minikube/issues/4730

### Attach the log file

PS C:\WINDOWS\system32> minikube start
* minikube v1.25.2 on Microsoft Windows 10 Pro 10.0.19044 Build 19044
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

X Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900
  - https://github.com/kubernetes/minikube/issues/4730

### Operating System

Windows

### Driver

VirtualBox

**Comment by afbjorklund** [comment]
Probably a bug in libmachine, not recognizing newer cpuid or something similar like that.

If VirtualBox is working fine (and has hardware acceleration), it's a bug in "virtualbox" driver.

----

So one would need to look at the VirtualBox.log, for details why it was disabled ?

https://github.com/machine-drivers/machine/blob/master/drivers/virtualbox/vtx.go

It could also be something specific to the CPU type, not recognizing the extensions:

https://github.com/machine-drivers/machine/blob/master/drivers/virtualbox/vtx_intel.go
https://github.com/machine-drivers/machine/blob/master/drivers/virtualbox/vtx_other.go

**Comment by afbjorklund** [comment]
Similar to:
* https://github.com/kubernetes/minikube/issues/13935
