### ISSUE TITLE
[podman] Custom containers.conf w/ crun

### ISSUE THREAD

**Issue by jesperpedersen** [kubernetes/minikube#14019]
### What Happened?

😄  minikube v1.25.2 on Fedora 35
    ▪ MINIKUBE_ROOTLESS=true
✨  Using the podman driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0422 10:52:27.079008  935976 cache.go:201] Error downloading kic artifacts:  not yet implemented, see issue #8426
🔄  Restarting existing podman container for "minikube" ...
🤦  StartHost failed, but will try again: podman inspect ip minikube: podman container inspect -f {{.NetworkSettings.IPAddress}} minikube: exit status 125
stdout:

stderr:
time="2022-04-22T10:52:28-04:00" level=warning msg="Failed to decode the keys [\"runtime\"] from \"/home/demo/.config/containers/containers.conf\"."
time="2022-04-22T10:52:28-04:00" level=warning msg="Failed to decode the keys [\"runtime\"] from \"/home/demo/.config/containers/containers.conf\"."
time="2022-04-22T10:52:28-04:00" level=warning msg="Failed to decode the keys [\"runtime\"] from \"/home/demo/.config/containers/containers.conf\"."
time="2022-04-22T10:52:28-04:00" level=warning msg="Failed to decode the keys [\"runtime\"] from \"/home/demo/.config/containers/containers.conf\"."
Error: error inspecting object: no such container minikube

🔄  Restarting existing podman container for "minikube" ...
😿  Failed to start podman container. Running "minikube delete" may fix it: podman inspect ip minikube: podman container inspect -f {{.NetworkSettings.IPAddress}} minikube: exit status 125
stdout:

stderr:
time="2022-04-22T10:52:37-04:00" level=warning msg="Failed to decode the keys [\"runtime\"] from \"/home/demo/.config/containers/containers.conf\"."
time="2022-04-22T10:52:37-04:00" level=warning msg="Failed to decode the keys [\"runtime\"] from \"/home/demo/.config/containers/containers.conf\"."
time="2022-04-22T10:52:37-04:00" level=warning msg="Failed to decode the keys [\"runtime\"] from \"/home/demo/.config/containers/containers.conf\"."
time="2022-04-22T10:52:37-04:00" level=warning msg="Failed to decode the keys [\"runtime\"] from \"/home/demo/.config/containers/containers.conf\"."
Error: error inspecting object: no such container minikube

### Attach the log file

The content of `~/.config/containers/containers.conf` is

```
runtime = "crun"
```

### Operating System

Redhat/Fedora

### Driver

Podman

**Comment by jesperpedersen** [comment]
Using 1dae0f842cac2fe184a17fdf6bfe946d1ac9987d w/ `go version go1.18 linux/amd64`

**Comment by jesperpedersen** [comment]
Without the `containers.conf` file

```
😄  minikube v1.25.2 on Fedora 35
    ▪ MINIKUBE_ROOTLESS=true
✨  Using the podman driver based on user configuration
📌  Using rootless Podman driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0422 11:00:51.050068  953324 cache.go:201] Error downloading kic artifacts:  not yet implemented, see issue #8426
🔥  Creating podman container (CPUs=2, Memory=8192MB) ...
🎁  Preparing Kubernetes v1.23.5 on CRI-O 1.22.3 ...
    ▪ kubelet.cni-conf-dir=/etc/cni/net.mk
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

```
runc --version
runc version 1.1.1
commit: babb8ce-dirty
spec: 1.0.2-dev
go: go1.16.15
libseccomp: 2.5.3
```

**Comment by afbjorklund** [comment]
There should be more information in the original log, why podman fails to start when you have configured crun.

**Comment by jesperpedersen** [comment]
@jesperpedersen Thanks, Anders ! My bad
