### ISSUE TITLE
Minikube not picking up proxy on windows 

### ISSUE THREAD

**Issue by jaydo1** [kubernetes/minikube#1402]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

**Minikube version** (use `minikube version`):
0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
Windows  64 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
virtualbox 
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:

**What happened**:
unable to to connect to pull down image 
minikube start --vm-driver="virtualbox" --docker-env HTTP_PROXY=http://XXXX.edu.au:80 --docker-env HTTPS_PROXY=https://XXXX.edu.au:443

**What you expected to happen**:
minikube to pull images via proxy server 

**How to reproduce it** (as minimally and precisely as possible):
try to pull via proxy server 

**Anything else do we need to know**:

**Comment by dlorenc** [comment]
Could you run and paste the output of this command?

```
minikube ssh "systemctl show docker --property=Environment"
```

**Comment by jaydo1** [comment]
Hi 

I get an error when i run this command 
ssh "systemctl show docker --property=Environment"

.\minikube.exe : E0426 07:55:53.412522   11460 notify.go:54] Error getting json from minikube version url: Error getting minikube version url via http: Get 
https://storage.googleapis.com/minikube/releases.json: dial tcp 216.58.196.144:443: connectex: A connection attempt failed because the connected party did not 
properly respond after a period of time, or established connection failed because connected host has failed to respond.
At line:1 char:1
+ .\minikube.exe ssh "systemctl show docker --property=Environment"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (E0426 07:55:53....led to respond.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
E0426 07:55:53.552049   11460 ssh.go:44] Error attempting to ssh/run-ssh-command: Error checking if api exist and loading it: Machine does not exist for 
api.Exists(minikube)

**Comment by dhiaayachi** [comment]
Hi
You need to define the environment variables  HTTP_PROXY=xxx and HTTPS_PROXY=yyy 
(with xxx and yyy according to your http proxy server) in windows environment.
