### ISSUE TITLE
storage-provisioner uses hardcoded path `/tmp/hostpath-provisioner` for PVC data, which leads to unexpected data loss

### ISSUE THREAD

**Issue by maxb** [kubernetes/minikube#14034]
### What Happened?

The storage-provisioner places PVC data under `/tmp/hostpath-provisioner`.

It is common for distributions to erase the contents of `/tmp/` at boot time - this destroys PVs if you are using the `none` driver.

I found this out when a testing environment had all its PVCs wiped when I rebooted my laptop.

The path is also not configurable, meaning the user has no easy workaround for this, and neither can they relocate the PVs to another disk.

I propose that the default location should change (potentially to a new subdirectory of `/var/lib/minikube/`), and it should also be made configurable via `minikube config ...`.

### Attach the log file

n/a

### Operating System

Ubuntu

### Driver

None (Baremetal)

**Comment by afbjorklund** [comment]
You are supposed to mount a persistent directory, at that temporary mountpoint.

It could be configurable:
* https://github.com/kubernetes/minikube/issues/3318

But then you would need to configure it, so it would still require setup on your part.

**Comment by klaases** [comment]
Hi @maxb, were you able to take a look at @afbjorklund's comment and did it help resolve the situation?

**Comment by klaases** [comment]
Hi @maxb – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by maxb** [comment]
/reopen

Sorry for going quiet here, as with #14035, I put this to one side to think about how to effectively challenge "You are supposed to mount a persistent directory, at that temporary mountpoint", and then life got in the way.

It's certainly fair to send me to the documentation, and it does say that I should bind mount or symlink these directories to another location.

However, there are a few ways this could be improved:

* Symlinking doesn't actually work. The provisioner fails if the directory is a symlink:
```
E0717 09:06:47.115171       1 controller.go:981] error syncing claim "ea541c05-a8ae-47de-a8d5-7f0b10292f68": failed to provision volume with StorageClass "standard": mkdir /tmp/hostpath-provisioner: file exists
```

* Bind mounting doesn't actually work. Somehow this prevents Kubernetes from performing the `chown` it would usually do, so that a PV matches the `securityContext` of the pod it is being mounted in, so when the application needing the PV starts, it can't write to it. At least, this is what happens on my Ubuntu 22.04 laptop. It seems like it works on an Ubuntu 20.04 VM, which is somewhat confusing. If you know where I could look for more information on this one, please do let me know.

* Even if these were options, it would still be nicer if the out-of-the-box behaviour didn't store PVC content in a location that it is fairly common for Linux distros to automatically wipe on reboot. I was lucky that I had not spent long setting up any specific experiments before discovering this, but it could have been worse - some people don't reboot their workstations for weeks at a time.

**Comment by afbjorklund** [comment]
Patches accepted:

* https://github.com/kubernetes/minikube/issues/3318

The current workaround is to document the status quo, how it is being used from the ISO and from KIC, so that user can duplicate the setup in their own machine. It _would_ be better, if this was in config instead.

**Comment by pythonwood** [comment]
my solvtion (test in minikube v1.37) :

`minikube start -n 2 --mount-string=./data/minikube/data:/var/hostpath-provisioner`

because minikube auto bind /var/hostpath-provisioner to /tmp/hostpath-provisioner, and storageclass ` standard (default)                k8s.io/minikube-hostpath ` use hostpath /tmp/hostpath-provisioner as storage path. 
so, every things is well down.
