### ISSUE TITLE
The terminal needs to be open to run it (mac M1)

### ISSUE THREAD

**Issue by sinevitch** [kubernetes/minikube#14039]
### What Happened?

I'm using a new mac on an m1 processor. I run minikube through docker using the command minikube start --driver=docker.
Minicube starts up and works fine but there is one problem. When I execute the command minikube service first-app then I get this error in the console "Because you are using a Docker driver on darwin, the terminal needs to be open to run it."
Tell me how to solve this problem?

### Attach the log file

kubectl get deployments

NAME        READY   UP-TO-DATE   AVAILABLE   AGE
first-app   1/1     1            1           11m

kubectl get services
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
first-app    LoadBalancer   10.101.117.139   <pending>     8080:32159/TCP   18s
kubernetes   ClusterIP      10.96.0.1        <none>        443/TCP          12m

### Operating System

macOS (Default)

### Driver

Docker

**Comment by zhan9san** [comment]
Hi @sinevitch 

It is expected. See #13806

**Comment by sinevitch** [comment]
so how do I solve the problem? I haven't figured anything out yet

**Comment by sinevitch** [comment]
It seems to work
https://github.com/kubernetes/minikube/issues/13788#issuecomment-1068640594

**Comment by klaases** [comment]
Hi @sinevitch, thanks for your confirmation, closing out for now.
