### ISSUE TITLE
Minikube not starting with Hyperkit

### ISSUE THREAD

**Issue by purvalraj** [kubernetes/minikube#14031]
### What Happened?

Below is error after running minikube --driver=hyperkit

Password:
E0424 08:52:47.902674   41803 iso.go:88] Unable to download https://storage.googleapis.com/minikube/iso/minikube-v1.25.2.iso: unable to acquire lock for {Name:798744c300c427722d7ec0b Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}: timeout acquiring mutex

Can anyone help with this problem ?

Ping works on website - https://storage.googleapis.com/  and also If I copy paste the URL to browser ISO is getting downloaded.

### Attach the log file

NA

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by klaases** [comment]
Hi @purvalraj, would you be able to try again with the latest version of minikube, v1.26.0?

Otherwise, it seems like there could have been a connectivity issue when downloading hyperkit.

**Comment by klaases** [comment]
Hi @purvalraj – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
