### ISSUE TITLE
Exiting due to GUEST_STOP_TIMEOUT: Temporary Error: stop: stopping minikube: exit status 1

### ISSUE THREAD

**Issue by dancaugherty** [kubernetes/minikube#14040]
### What Happened?

"minikube stop" will not stop minikube!

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8555457/logs.txt)
[minikube_logs_c0c5b648c8bfaf86b2de6a6a2480d02ddf10a723_0.log](https://github.com/kubernetes/minikube/files/8555465/minikube_logs_c0c5b648c8bfaf86b2de6a6a2480d02ddf10a723_0.log)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by klaases** [comment]
Hi @dancaugherty, I have not yet encountered this situation, are you still experiencing this issue?

**Comment by klaases** [comment]
Hi @[dancaugherty](https://github.com/dancaugherty) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
