### ISSUE TITLE
Convenience Method For Mapping GCP creds into pods To Simulate Running In That Env

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1405]
From: https://github.com/kubernetes/minikube/issues/612#issuecomment-296481405
This command `minikube auth gcp` would be a convenience function for mapping application default credentials into every pod so that the cluster operates similar to how it would in GCE/GKE with no additional yaml modifications required by the user.

**Comment by paulwalker** [comment]
To be more explicit, `a convenience function for mapping application default credentials into every "newly created" pod`

**Comment by tswast** [comment]
The way to do this which would be most consistent with the way application default credentials work on App Engine, GCE, and GKE would be to emulate the [GCP Metadata Server](https://cloud.google.com/compute/docs/storing-retrieving-metadata). Specifically, HTTP requests in the pod to:

- `metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token` Should return [an access token for a service account](https://stackoverflow.com/a/39856616/101923).
- `metadata.google.internal/computeMetadata/v1/project/project-id` Should return [a project ID](https://cloud.google.com/compute/docs/storing-retrieving-metadata#default), probably the one associated with a service account, but maybe we'd want to be able to override this.

**Comment by tstromberg** [comment]
Closing this bug as it hasn't seen activity in awhile, and there does not appear to be any plans to address it.
