### ISSUE TITLE
API server is not started !!

### ISSUE THREAD

**Issue by silentknight2001** [kubernetes/minikube#14067]
### What Happened?

``
$ minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Stopped
kubeconfig: Configured

``
>as we can see host and kubelet is running but API-server is not started any more i tried couple of time but it's not happen

### Attach the log file

> here is the issue showing ........................................................

``
silentknight@silentknight-2001:~$ minikube start
😄  minikube v1.25.2 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > index.docker.io/kicbase/sta...: 0 B [_______________________] ?% ? p/s 0s
    > index.docker.io/kicbase/sta...: 0 B [_______________________] ?% ? p/s 0s
    > gcr.io/k8s-minikube/kicbase...: 0 B [_______________________] ?% ? p/s 0s
    > index.docker.io/kicbase/sta...: 0 B [_______________________] ?% ? p/s 0s
E0428 17:21:11.824330    8354 cache.go:203] Error downloading kic artifacts:  failed to download kic base image or any fallback image
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m

🤦  Unable to restart cluster, will reset it: apiserver health: apiserver healthz never reported healthy: cluster wait timed out during healthz check
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...\ E0428 17:29:11.765372    8354 start.go:264] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.49.2:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 192.168.49.2:8443: i/o timeout]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition

``

### Operating System

Ubuntu

### Driver

Docker

**Comment by silentknight2001** [comment]
> this is first time for me submit a issue.......

**Comment by pellizzetti** [comment]
Hi @silentknight2001 👋🏻

Clear your minikube config files with `minikube delete --all --purge` and try again.

**Comment by hdava** [comment]
I'm facing the same issue.

I've tried doing `minikube delete --all --purge` multiple times, but it didn't solve the problem.

**Comment by ilyazr** [comment]
Same problem.
@silentknight2001 @hdava were you able to solve this issue?

**Comment by IP14Y3RI** [comment]
@ilyazr 
Same problem. Were you able to solve this issue?

**Comment by TiagoIesbick** [comment]
Run this:
`minikube update-context`
