### ISSUE TITLE
Drivers

### ISSUE THREAD

**Issue by izharaazmi** [kubernetes/minikube#14066]
> minikube can be deployed as a VM, a container, or bare-metal.

It should state or link to a page that states the difference between these two deployment approaches.

> Here is what’s supported:  ...

There should be clarified whether are the listed platforms (Linux, Windows, MacOS) are host platform or guest platforms.

**Comment by afbjorklund** [comment]
Do you have some suggestions on wording or format ?

* https://github.com/kubernetes/minikube/issues/9803

I count "three" form factors, but that's more like 6 or 12

**Comment by izharaazmi** [comment]
This is my first day with kubernetes, hence I have no idea.

**Comment by afbjorklund** [comment]
No worries, the comment with what info you are looking for is also helpful
