### ISSUE TITLE
Error after minikube start

### ISSUE THREAD

**Issue by Pali15** [kubernetes/minikube#14061]
### What Happened?

![image](https://user-images.githubusercontent.com/75538899/165555398-aa216344-c023-4596-a2a5-5bf7c0779e75.png)
 Cant start minikube

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8573435/logs.txt)

**Comment by klaases** [comment]
Hi @Pali15 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
