### ISSUE TITLE
Minikube not starting for a fresh install in WSL

### ISSUE THREAD

**Issue by debasishdhar7** [kubernetes/minikube#14075]
### What Happened?

I am installing  Minikube for the first time in windows subsystem . It is not starting

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8590846/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
`System has not been booted with systemd as init system (PID 1). Can't operate.`

There is a suggestion to replace the remaining `systemctl` calls with "sysinit"

* https://github.com/kubernetes/minikube/issues/12276

Not sure if it would be enough to get WSL going, but I guess it is worth doing...

**Comment by klaases** [comment]
Hi @debasishdhar7, I see that the related issue https://github.com/kubernetes/minikube/issues/12276 has been resolved.

Would you be able to try again with the latest version of minikube?

**Comment by klaases** [comment]
Hi @debasishdhar7, based on recent changes, would you mind updating minikube and trying again?

**Comment by klaases** [comment]
Hi @debasishdhar7 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
