### ISSUE TITLE
minikube  can't  build image

### ISSUE THREAD

**Issue by fanspace** [kubernetes/minikube#14077]
### What Happened?

step 1
minikube start --driver=virtualbox --memory 16777 --cpus 4

step 2
minikube kubectl -- get pod --all-namespaces
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-64897985d-7xdmt            1/1     Running   0          30m
kube-system   etcd-minikube                      1/1     Running   0          30m
...

step 3
minikube image pull alpine:latest

step4
minikube image list
gcr.io/google_containers/kube-registry-proxy:<none>
docker.io/library/registry:<none>
docker.io/library/alpine:latest
....

step5
minikube image build -t alpine_utc .
Dockerfile has no problem
occur err
I0430 23:20:33.633097    5156 out.go:297] Setting OutFile to fd 92 ...
I0430 23:20:33.657938    5156 out.go:310] Setting ErrFile to fd 96...
I0430 23:20:33.667069    5156 config.go:176] Loaded profile config "minikube": Driver=virtualbox, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0430 23:20:35.203675    5156 out.go:176]

W0430 23:20:35.203675    5156 out.go:241] ❌  Exiting due to GUEST_FILE_IN_USE: cannot open "C:\\Users\\weara\\AppData\\Local\\D3DSCache\\60a1dd3ae0603106\\52264C4C-172F-41B9-91B8-7F0C3B1E9021_VEN_1002&DEV_67DF&SUBSYS_B31&REV_E7.idx" for reading: open C:\Users\weara\AppData\Local\D3DSCache\60a1dd3ae0603106\52264C4C-172F-41B9-91B8-7F0C3B1E9021_VEN_1002&DEV_67DF&SUBSYS_B31&REV_E7.idx: The process cannot access the file because it is being used by another process.
❌  Exiting due to GUEST_FILE_IN_USE: cannot open "C:\\Users\\weara\\AppData\\Local\\D3DSCache\\60a1d\\172F-41B9-91B8-7F0C3B1E9021_VEN_1002&DEV_67DF&SUBSYS_B31&REV_E7.idx" for reading: open C:\Users\weara\AppData\Local\D3DSCache\03106\172F-41B9-91B8-7F0C3B1E9021_VEN_1002&DEV_67DF&SUBSYS_B31&REV_E7.idx: The process cannot access the file because it is being used by another process.
W0430 23:20:35.204640    5156 out.go:241] 💡  建议：Another program is using a file required by minikube. If you are using Hyper-V, try stopping the minikube VM from within the Hyper-V manager
💡  建议：Another program is using a file required by minikube. If you are using Hyper-V, try stopping the minikube VM from within the Hyper-V manager
W0430 23:20:35.204640    5156 out.go:241] 📘  文档：https://docs.docker.com/machine/drivers/hyper-v/
📘  文档：https://docs.docker.com/machine/drivers/hyper-v/
W0430 23:20:35.204640    5156 out.go:241] 🍿  Related issue: https://github.com/kubernetes/minikube/issues/7300
🍿  Related issue: https://github.com/kubernetes/minikube/issues/7300
I0430 23:20:35.205628    5156 out.go:176]

install minikube and run minikube all use administrator privileges

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8597243/log.txt)

### Operating System

Windows

### Driver

VirtualBox

**Comment by klaases** [comment]
Hi @fanspace – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
