### ISSUE TITLE
Cannot use kubectl on cluster started by minikube - "Unable to connect to the server: Access violation"

### ISSUE THREAD

**Issue by osadalakmal** [kubernetes/minikube#1407]
This is a BUG REPORT

Minikube version: v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release): 
        
     ProductName:	Mac OS X 
     ProductVersion:	10.12.4
     BuildVersion:	16E195

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
    virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
    "Boot2DockerURL": "file:///Users/oparanaliyan/.minikube/cache/iso/minikube-v0.18.0.iso"
- **Install tools**:
    
- **Others**:

**What happened**:
    
   1. I downloaded minikube from https://github.com/kubernetes/minikube/releases/download/v0.18.0/minikube-darwin-amd64 and installed it with the command given in the releases page.
   2. I followed the quickstart guide at https://github.com/kubernetes/minikube/blob/v0.18.0/README.md#quickstart.
   3. Everything was ok with minikube start

```
minikube start
Starting local Kubernetes cluster...
Starting VM...
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
```

4. Then kubectl command to deploy the service fails with

`$ kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8080
Unable to connect to the server: Access violation`

**What you expected to happen**: 

Expected the output to be `deployment "hello-minikube" created`

**How to reproduce it** (as minimally and precisely as possible):

Follow the procedure stated above

**Anything else do we need to know**:

I tried running kubectl with --v=10. The output was as follows

```
$ kubectl cluster-info --v=10
I0425 00:06:17.373301   17745 loader.go:354] Config loaded from file /Users/oparanaliyan/.kube/config
I0425 00:06:17.374463   17745 round_trippers.go:299] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: kubectl/v1.5.4 (darwin/amd64) kubernetes/7243c69" https://192.168.99.102:8443/api
I0425 00:06:17.392848   17745 round_trippers.go:318] GET https://192.168.99.102:8443/api  in 18 milliseconds
I0425 00:06:17.392864   17745 round_trippers.go:324] Response Headers:
I0425 00:06:17.392942   17745 helpers.go:221] Connection error: Get https://192.168.99.102:8443/api: Access violation
F0425 00:06:17.392952   17745 helpers.go:116] Unable to connect to the server: Access violation
```

**Comment by r2d4** [comment]
Can you share the output of `minikube logs`?
