### ISSUE TITLE
failure loading apiserver certificate: failed to load certificate: the certificate has expired

### ISSUE THREAD

**Issue by KanikaBishnoi** [kubernetes/minikube#14082]
### What Happened?

Hi,

I am trying to install minikube on my personal laptop, I followed the instruction on the minikube installation page, installed docker also from there :
minikube installation: https://minikube.sigs.k8s.io/docs/start/
docker installation : https://hub.docker.com/search?q=&type=edition&offering=community&sort=updated_at&order=desc

I am using a windows laptop. getting below error:
[minikubeError.txt](https://github.com/kubernetes/minikube/files/8604751/minikubeError.txt)

### Attach the log file

[minikubeError.txt](https://github.com/kubernetes/minikube/files/8604758/minikubeError.txt)

C:\Users\kanik>minikube logs --file=log.txt
Error: unknown flag: --file
See 'minikube logs --help' for usage.

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @KanikaBishnoi, thanks for reporting your issue with minikube!

You're using minikube v1.15.1 which is very old, please update to minikube v1.25.2, run `minikube delete --all --purge` and then try starting minikube again and see if that resolves your issue, thanks!
