### ISSUE TITLE
Can't build minikube ISO because of wrong hash

### ISSUE THREAD

**Issue by goto-loop** [kubernetes/minikube#14080]
### What Happened?

Background: I'm trying to set up minikube on my local machine with kvm2 driver and GPU support. It's not working with the binary release, but I saw there are some recent commits to fix GPU issues so I decided to build the binary and ISO files myself, the latter following [this guide](https://minikube.sigs.k8s.io/docs/contrib/building/iso/).

The problem is that after some time, the `make out/minikube.iso` command outputs the following error message:

> 2022-05-02 09:32:04 (5.54 MB/s) - ‘/mnt/out/buildroot/output/build/.v1.5.11.tar.gz.ZXc6uR/output’ saved [7494477]
> 
> ERROR: v1.5.11.tar.gz has wrong sha256 hash:
> ERROR: expected: 02b79d5e2b07b5e64cd28f1fe84395ee11eef95fc49fd923a9ab93022b148be6
> ERROR: got     : 6a289406c1c0583763e5a9754e31a1eced55cd5f162a7bc2a3a315d5eb05c7a1
> ERROR: Incomplete download, or man-in-the-middle (MITM) attack
> --2022-05-02 09:32:04--  http://sources.buildroot.net/containerd-bin/v1.5.11.tar.gz
> Resolving sources.buildroot.net (sources.buildroot.net)... 172.67.72.56, 104.26.0.37, 104.26.1.37, ...
> Connecting to sources.buildroot.net (sources.buildroot.net)|172.67.72.56|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2022-05-02 09:32:04 ERROR 404: Not Found.
> 
> --2022-05-02 09:32:04--  http://sources.buildroot.net/v1.5.11.tar.gz
> Resolving sources.buildroot.net (sources.buildroot.net)... 172.67.72.56, 104.26.0.37, 104.26.1.37, ...
> Connecting to sources.buildroot.net (sources.buildroot.net)|172.67.72.56|:80... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2022-05-02 09:32:04 ERROR 404: Not Found.
> 
> package/pkg-generic.mk:144: recipe for target '/mnt/out/buildroot/output/build/containerd-bin-v1.5.11/.stamp_downloaded' failed
> make[2]: *** [/mnt/out/buildroot/output/build/containerd-bin-v1.5.11/.stamp_downloaded] Error 1
> make[2]: Leaving directory '/mnt/out/buildroot'
> Makefile:286: recipe for target 'minikube_iso' failed
> make[1]: Leaving directory '/mnt'
> make[1]: *** [minikube_iso] Error 2
> make: *** [out/minikube.iso] Error 2
> Makefile:312: recipe for target 'out/minikube.iso' failed
> make: *** [Makefile:314: out/minikube.iso] Error 2

I've downloaded the file manually using both CLI and browser and it always has the same checksum as mentioned in the error, but NOT the expected one.

How can I fix this? Maybe it's possible to change the expected checksum as a workaround?

### Attach the log file

No log available since the binary can't be built.

### Operating System

Ubuntu

**Comment by goto-loop** [comment]
UPDATE: I've had another look at the error message and after the first errors the script tries to download http://sources.buildroot.net/containerd-bin/v1.5.11.tar.gz, which results in an error 404. This is because the directory `containerd-bin` doesn't exist on the server; however, `containerd` exists plus it contains a file with the expected hash. I suppose if we changed this URL, the problem would be solved.

**Comment by afbjorklund** [comment]
That's just the fallback URL

The real problem is upstream

**Comment by afbjorklund** [comment]
It would be a good idea to provide a cache for the minikube packages, since those are not available at buildroot.net

**Comment by afbjorklund** [comment]
> Maybe it's possible to change the expected checksum as a workaround?

Yeah, but... 8dca3b0b992a38c2096924420502c35dc6a0acaf

**Comment by afbjorklund** [comment]
Closing as duplicate, just update the hash if it happens to you (again)
