### ISSUE TITLE
Failed to start docker container. Running "minikube delete" may fix it: boot lock: timeout acquiring mutex

### ISSUE THREAD

**Issue by sudhirwakchoure** [kubernetes/minikube#14081]
### What Happened?

issue

### Attach the log file

=> Audit <==
|---------|------|---------|------|---------|------------|----------|
| Command | Args | Profile | User | Version | Start Time | End Time |
|---------|------|---------|------|---------|------------|----------|
|---------|------|---------|------|---------|------------|----------|

==> Last Start <==
Log file created at: 2022/05/02 19:59:03
Running on machine: GS-6086
Binary: Built with gc go1.17.7 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0502 19:59:03.825812   60568 out.go:297] Setting OutFile to fd 1 ...
I0502 19:59:03.825868   60568 out.go:349] isatty.IsTerminal(1) = true
I0502 19:59:03.825870   60568 out.go:310] Setting ErrFile to fd 2...
I0502 19:59:03.825872   60568 out.go:349] isatty.IsTerminal(2) = true
I0502 19:59:03.825940   60568 root.go:315] Updating PATH: /home/sudhir/.minikube/bin
W0502 19:59:03.825998   60568 root.go:293] Error reading config file at /home/sudhir/.minikube/config/config.json: open /home/sudhir/.minikube/config/config.json: no such file or directory
I0502 19:59:03.826129   60568 out.go:304] Setting JSON to false
I0502 19:59:03.845722   60568 start.go:112] hostinfo: {"hostname":"GS-6086","uptime":8891,"bootTime":1651492853,"procs":319,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.14.0-1034-oem","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"95977f12-7572-474c-b2ef-85331938b2f0"}
I0502 19:59:03.845768   60568 start.go:122] virtualization: kvm host
I0502 19:59:03.856283   60568 out.go:176] 😄  minikube v1.25.2 on Ubuntu 20.04
W0502 19:59:03.856347   60568 preload.go:295] Failed to list preload files: open /home/sudhir/.minikube/cache/preloaded-tarball: no such file or directory
I0502 19:59:03.859224   60568 out.go:176]     ▪ KUBECONFIG=/home/sudhir/.kube/config
I0502 19:59:03.856370   60568 notify.go:193] Checking for updates...
I0502 19:59:03.859333   60568 driver.go:344] Setting default libvirt URI to qemu:///system
I0502 19:59:03.880737   60568 docker.go:132] docker version: linux-20.10.14
I0502 19:59:03.880788   60568 cli_runner.go:133] Run: docker system info --format "{{json .}}"
I0502 19:59:03.937751   60568 info.go:263] docker info: {ID:XY6F:X5P7:PMON:QWAJ:E64S:RDZL:RMK4:UTBJ:D47R:KMC2:IUXR:D55B Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:1 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:true KernelMemoryTCP:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:24 OomKillDisable:true NGoroutines:34 SystemTime:2022-05-02 19:59:03.895783548 +0530 IST LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:0 KernelVersion:5.14.0-1034-oem OperatingSystem:Ubuntu 20.04.4 LTS OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:8 MemTotal:33306783744 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:GS-6086 Labels:[] ExperimentalBuild:false ServerVersion:20.10.14 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:3df54a852345ae127d1fa3092b95168e4a88e2f8 Expected:3df54a852345ae127d1fa3092b95168e4a88e2f8} RuncCommit:{ID:v1.0.3-0-gf46b6ba Expected:v1.0.3-0-gf46b6ba} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=apparmor name=seccomp,profile=default] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Experimental:true Name:app Path:/usr/libexec/docker/cli-plugins/docker-app SchemaVersion:0.1.0 ShortDescription:Docker App Vendor:Docker Inc. Version:v0.9.1-beta3] map[Name:buildx Path:/usr/libexec/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.8.1-docker] map[Name:compose Path:/usr/libexec/docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.3.3] map[Name:scan Path:/usr/libexec/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.17.0]] Warnings:<nil>}}
I0502 19:59:03.937853   60568 docker.go:237] overlay module found
I0502 19:59:03.942300   60568 out.go:176] ✨  Using the docker driver based on user configuration
I0502 19:59:03.942319   60568 start.go:281] selected driver: docker
I0502 19:59:03.942321   60568 start.go:798] validating driver "docker" against <nil>
I0502 19:59:03.942330   60568 start.go:809] status for docker: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0502 19:59:03.942426   60568 cli_runner.go:133] Run: docker system info --format "{{json .}}"
I0502 19:59:04.000352   60568 info.go:263] docker info: {ID:XY6F:X5P7:PMON:QWAJ:E64S:RDZL:RMK4:UTBJ:D47R:KMC2:IUXR:D55B Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:1 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:true KernelMemoryTCP:true CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:24 OomKillDisable:true NGoroutines:34 SystemTime:2022-05-02 19:59:03.958192315 +0530 IST LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:0 KernelVersion:5.14.0-1034-oem OperatingSystem:Ubuntu 20.04.4 LTS OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:8 MemTotal:33306783744 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy: HTTPSProxy: NoProxy: Name:GS-6086 Labels:[] ExperimentalBuild:false ServerVersion:20.10.14 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:3df54a852345ae127d1fa3092b95168e4a88e2f8 Expected:3df54a852345ae127d1fa3092b95168e4a88e2f8} RuncCommit:{ID:v1.0.3-0-gf46b6ba Expected:v1.0.3-0-gf46b6ba} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=apparmor name=seccomp,profile=default] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Experimental:true Name:app Path:/usr/libexec/docker/cli-plugins/docker-app SchemaVersion:0.1.0 ShortDescription:Docker App Vendor:Docker Inc. Version:v0.9.1-beta3] map[Name:buildx Path:/usr/libexec/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.8.1-docker] map[Name:compose Path:/usr/libexec/docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.3.3] map[Name:scan Path:/usr/libexec/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.17.0]] Warnings:<nil>}}
I0502 19:59:04.000463   60568 start_flags.go:288] no existing cluster config was found, will generate one from the flags 
I0502 19:59:04.018118   60568 start_flags.go:369] Using suggested 7900MB memory alloc based on sys=31763MB, container=31763MB
I0502 19:59:04.018265   60568 start_flags.go:397] setting extra-config: kubelet.housekeeping-interval=5m
I0502 19:59:04.018280   60568 start_flags.go:813] Wait components to verify : map[apiserver:true system_pods:true]
I0502 19:59:04.018306   60568 cni.go:93] Creating CNI manager for ""
I0502 19:59:04.018313   60568 cni.go:167] CNI unnecessary in this configuration, recommending no CNI
I0502 19:59:04.018321   60568 start_flags.go:302] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 Memory:7900 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.23.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: ExtraOptions:[{Component:kubelet Key:housekeeping-interval Value:5m}] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/home/sudhir:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false}
I0502 19:59:04.022007   60568 out.go:176] 👍  Starting control plane node minikube in cluster minikube
I0502 19:59:04.022028   60568 cache.go:120] Beginning downloading kic base image for docker with docker
I0502 19:59:04.024890   60568 out.go:176] 🚜  Pulling base image ...
I0502 19:59:04.024910   60568 preload.go:132] Checking if preload exists for k8s version v1.23.3 and runtime docker
I0502 19:59:04.024980   60568 image.go:75] Checking for gcr.io/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 in local docker daemon
I0502 19:59:04.042792   60568 image.go:79] Found gcr.io/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 in local docker daemon, skipping pull
I0502 19:59:04.042806   60568 cache.go:142] gcr.io/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 exists in daemon, skipping load
I0502 19:59:04.303094   60568 preload.go:119] Found remote preload: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/v17/v1.23.3/preloaded-images-k8s-v17-v1.23.3-docker-overlay2-amd64.tar.lz4
I0502 19:59:04.303149   60568 cache.go:57] Caching tarball of preloaded images
I0502 19:59:04.303422   60568 preload.go:132] Checking if preload exists for k8s version v1.23.3 and runtime docker
I0502 19:59:04.313984   60568 out.go:176] 💾  Downloading Kubernetes v1.23.3 preload ...
I0502 19:59:04.314040   60568 preload.go:238] getting checksum for preloaded-images-k8s-v17-v1.23.3-docker-overlay2-amd64.tar.lz4 ...
I0502 19:59:04.709887   60568 download.go:101] Downloading: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/v17/v1.23.3/preloaded-images-k8s-v17-v1.23.3-docker-overlay2-amd64.tar.lz4?checksum=md5:1c52b21a02ef67e2e4434a0c47aabce7 -> /home/sudhir/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v17-v1.23.3-docker-overlay2-amd64.tar.lz4
I0502 19:59:53.083513   60568 preload.go:249] saving checksum for preloaded-images-k8s-v17-v1.23.3-docker-overlay2-amd64.tar.lz4 ...
I0502 19:59:53.083560   60568 preload.go:256] verifying checksumm of /home/sudhir/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v17-v1.23.3-docker-overlay2-amd64.tar.lz4 ...
I0502 19:59:53.769482   60568 cache.go:60] Finished verifying existence of preloaded tar for  v1.23.3 on docker
I0502 19:59:53.769649   60568 profile.go:148] Saving config to /home/sudhir/.minikube/profiles/minikube/config.json ...
I0502 19:59:53.769660   60568 lock.go:35] WriteFile acquiring /home/sudhir/.minikube/profiles/minikube/config.json: {Name:mkce955b1227262270a038635f4f07c18574fdc0 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0502 19:59:53.769738   60568 cache.go:208] Successfully downloaded all kic artifacts
I0502 19:59:53.769745   60568 start.go:313] acquiring machines lock for minikube: {Name:mk853e711a98ffbd4c1e5feb41e2b4da678c9319 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}

### Operating System

Ubuntu

### Driver

Docker

**Comment by klaases** [comment]
Hi @sudhirwakchoure, thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @sudhirwakchoure – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
