### ISSUE TITLE
Cant run minikube on !popOS

### ISSUE THREAD

**Issue by FelixJacobsen** [kubernetes/minikube#14099]
### What Happened?

Can't start minikube. I have tried purge everything relating to minikube without any results. Currently running on !popOS. 

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8627433/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by klaases** [comment]
Hi @FelixJacobsen, could you be more specific in the actual error that is occurring?

Are you referring to: `Error: No such network: minikube`?
