### ISSUE TITLE
Error in Start

### ISSUE THREAD

**Issue by Ram7378** [kubernetes/minikube#14095]
### What Happened?

Problem in minikube start command 

### Attach the log file

![Screenshot 2022-05-04 180911](https://user-images.githubusercontent.com/76605185/166682805-f2b322d0-d93a-4f30-a355-5c49af17b85b.png)

### Operating System

Windows

### Driver

Hyper-V

**Comment by klaases** [comment]
Hi @Ram7378, from the error `Failed to start hyperv VM. "minikube start" may fix`.

Thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @Ram7378 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
