### ISSUE TITLE
error start minikube

### ISSUE THREAD

**Issue by fadesiderio** [kubernetes/minikube#14090]
**Los comandos necesarios para reproducir la incidencia**:

minikube start --driver=docker

**El resultado completo del comando que ha fallado**: <details>

* minikube v1.25.2 on Redhat 8.5
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
! The image 'gcr.io/k8s-minikube/storage-provisioner:v5' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/kube-apiserver:v1.23.3' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/kube-controller-manager:v1.23.3' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/coredns/coredns:v1.8.6' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/kube-proxy:v1.23.3' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/kube-scheduler:v1.23.3' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/pause:3.6' was not found; unable to add it to cache.
! The image 'k8s.gcr.io/etcd:3.5.1-0' was not found; unable to add it to cache.
! The image 'docker.io/kubernetesui/metrics-scraper:v1.0.7' was not found; unable to add it to cache.
! The image 'docker.io/kubernetesui/dashboard:v2.3.1' was not found; unable to add it to cache.
E0503 11:24:55.044947  469091 cache.go:203] Error downloading kic artifacts:  failed to download kic base image or any fallback image
* docker "minikube" container is missing, will recreate.
* Creating docker container (CPUs=2, Memory=2200MB) ...
! StartHost failed, but will try again: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2' locally
docker: Error response from daemon: Get "https://gcr.io/v2/": x509: certificate signed by unknown authority.
See 'docker run --help'.

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:
Redhat 8.5

**Comment by klaases** [comment]
Thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

---

¡Gracias por compartir su experiencia! Si no le importa, ¿podría proporcionar registros de minikube?

Adjunte (arrastre) el archivo `logs.txt` a este problema que se puede generar ejecutando este comando:

```
$ minikube logs --file=logs.txt
````

Esto nos ayudará a aislar aún más el problema. ¡Gracias!

**Comment by sharifelgamal** [comment]
It looks like an existing cluster was already running. Have you tried deleting it and starting a new one?

```
minikube delete
minikube start --driver=docker
```
