### ISSUE TITLE
installing minikube

### ISSUE THREAD

**Issue by vinal26** [kubernetes/minikube#14104]
### What Happened?

 minikube v1.25.2 on Microsoft Windows 10 Pro 10.0.19044 Build 19044
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
! StartHost failed, but will try again: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\Admin\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Failed to start hyperv VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\Admin\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\Admin\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

### Attach the log file

X Exiting due to GUEST_NOT_FOUND: load: filestore "minikube": open C:\Users\Admin\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

### Operating System

Windows

### Driver

Hyper-V

**Comment by klaases** [comment]
Hi @vinal26, would you be able to try running `minikube delete --all`?

Then, start minikube again. Please let us know if this error is still occuring.

**Comment by vinal26** [comment]
Hi, yeah I've applied all those commands but still it's not working.
