### ISSUE TITLE
k8s 1.24 	stat: cannot stat '/var/run/cri-dockerd.sock': No such file or directory when running on cloud shell without systemd

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#14128]
### What Happened?
as doing this PR https://github.com/kubernetes/minikube/pull/14126
I see K8 1.24 breaks minikube on cloud shell

```
** stderr ** 
	! Your cgroup does not allow setting memory.
	! Local proxy ignored: not passing HTTP_PROXY=localhost:44453 to docker env.
	! Local proxy ignored: not passing HTTP_PROXY=localhost:44453 to docker env.
	! You appear to be using a proxy, but your NO_PROXY environment does not include the minikube IP (192.168.49.2).
	X Exiting due to RUNTIME_ENABLE: stat /var/run/cri-dockerd.sock: Process exited with status 1
	stdout:
	
	stderr:
	stat: cannot stat '/var/run/cri-dockerd.sock': No such file or directory
	
	* 

```

I SSHed manually to the docker driver
```
docker@minikube:~$ ls -lah /var/run/cri-dockerd.sock 
srw-rw---- 1 root docker 0 May  9 19:39 /var/run/cri-dockerd.sock
docker@minikube:~$ cat /var/run/cri-dockerd.sock
cat: /var/run/cri-dockerd.sock: No such device or address
docker@minikube:~$ sudo cat /var/run/cri-dockerd.sock
cat: /var/run/cri-dockerd.sock: No such device or address
docker@minikube:~$ 

```

### Attach the log file

https://storage.googleapis.com/minikube-builds/logs/14126/23853/Docker_Cloud_Shell.html#fail_TestFunctional%2fserial%2fStartWithProxy

**Comment by afbjorklund** [comment]
You will need to check the output of `cri-docker.service`, to see why it didn't start up properly.

**Comment by afbjorklund** [comment]
You can view the log with `journalctl` or `systemctl status -l`

**Comment by spowelljr** [comment]
This has to do with the `--force-systemd` flag, which is enabled by default on Cloud Shell.

Starting v1.24 without the flag works fine on my Mac, but when I pass the flag in I get:
```
❌  Exiting due to RUNTIME_ENABLE: stat /var/run/cri-dockerd.sock: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/var/run/cri-dockerd.sock': No such file or directory
```

@medyagh, I think you tested this without the `--force-systemd` flag because when I run `systemctl status cri-docker` I get:
```
● cri-docker.service - CRI Interface for Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/cri-docker.service; disabled; vendor preset: enabled)
     Active: inactive (dead)
TriggeredBy: ● cri-docker.socket
       Docs: https://docs.mirantis.com
```
And `ls`ing returns that the socket doesn't exist

**Comment by spowelljr** [comment]
As a follow up, the only difference with `--force-systemd` is the following:
```
        if forceSystemd {
                if err := r.forceSystemd(); err != nil {
                      return err
                }
                return r.Init.Restart("docker")
        }
```
I tried commenting out `r.forceSystemd()` and it still failed, so then I commented out `r.Init.Restart("docker")` and then it worked, so it's something to do with restarting Docker.

**Comment by afbjorklund** [comment]
There is a `cri-docker.socket`, that is supposed to create the file - and hand it over to `cri-docker.service` when requested.

However, that _only_ works with systemd - so if you have a weird system like cloud-shell (without it), then it would fail.

It is related to how we handle "docker.socket", there needs to be a fallback to work with other init systems #12276

If they _don't_ support socket activation (on systemd), it needs to call the "service" instead - and also edit the config.

----

Here is the daemon config, when using socket activation:

`ExecStart=/usr/bin/cri-dockerd --container-runtime-endpoint fd:// --network-plugin=`

`ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock`

Those "fd" (file descriptor 3) are passed, from the socket unit:

http://0pointer.de/blog/projects/socket-activation.html

https://www.freedesktop.org/software/systemd/man/systemd-socket-activate.html

**Comment by spowelljr** [comment]
I found the error, if `--force-systemd` was passed we were returning before enabling and starting the CRI service.
