### ISSUE TITLE
Configure credentials for AWS Elastic Container Registry using registry-creds addon

### ISSUE THREAD

**Issue by asdf93074** [kubernetes/minikube#14132]
Shouldn't the yaml file here also be using the secret created by the addon i.e. awsecr-cred?

EDIT: Sorry if it's not clear but I created this issue from the website and I assumed it would automatically add some link/reference here. [This ](https://minikube.sigs.k8s.io/docs/tutorials/configuring_creds_for_aws_ecr/)is the page I'm referring to.

**Comment by klaases** [comment]
Hi @asdf93074, to verify, are you able to check if you have a secret called `awsecr-cred` in the default namespace by running `kubectl get secrets`?

**Comment by klaases** [comment]
Hi @[asdf93074](https://github.com/asdf93074) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by asdf93074** [comment]
I had this a few months ago so I don't remember all the details now but yes we had the awsecr-cred secret in our default namespace. Lets just keep this closed though till I get time to repro this issue with the latest minikube release. If the guide works for others then I think its all good.
