### ISSUE TITLE
Update runc version in minikube to 1.1

### ISSUE THREAD

**Issue by ondrej-ivanko** [kubernetes/minikube#14149]
### What Happened?

Hi,

I run into issue that specific elastic-search CRDs are unable to run, because Minikube is internally using runc v 1.0.2.

Linux kernel 4.11 introduced RDMA cgroup controller, but support for that controller is available since runc v 1.1.x

More on my system setup, problem explanation and workaround that I use is [here](https://github.com/elastic/cloud-on-k8s/issues/5325)

I would appreciate if you can update runc version, so I dont have to resort to my personal patched base image for minikube.

Cheers.

Ondřej

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8679302/log.txt)

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
Docker 20.10.15 updated to runc 1.1.1 (and containerd to 1.6.4)

https://docs.docker.com/engine/release-notes/#201015

**Comment by afbjorklund** [comment]
Fixed:
* #14152
