### ISSUE TITLE
Error starting cluster: apiserver healthz: apiserver process never appeared

### ISSUE THREAD

**Issue by SXDDFMYFJ** [kubernetes/minikube#14148]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by zhan9san** [comment]
@SXDDFMYFJ 

方便提供下模版里的信息吗？
比如启动命令，日志，以及如何复现这个问题，还有版本信息

**Comment by klaases** [comment]
嗨@SXDDFMYFJ——这个问题还在发生吗？是否有其他详细信息？如果是这样，请随时通过使用 `/reopen` 评论重新打开问题。由于无法获得更多信息并且已经过了一段时间，此问题将被关闭。

可能有帮助的其他信息：

* 问题是否出现在最新的 minikube 版本中

* 使用的确切 minikube 启动命令行

* 附上minikube日志的完整输出，运行`minikube logs --file=logs.txt`创建日志文件

感谢您分享您的经验！
---
Hi @SXDDFMYFJ  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
