### ISSUE TITLE
minikube installing problem

### ISSUE THREAD

**Issue by krishnarayapudi25** [kubernetes/minikube#14159]
### What Happened?

i have already disabled hyper-v but stll showing enabled in your device

### Attach the log file

C:\Users\rayap>minikube start --driver=virtualbox
* minikube v1.25.2 on Microsoft Windows 11 Home 10.0.22000 Build 22000
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

X Exiting due to PR_VBOX_HYPERV_64_BOOT: Failed to start host: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Suggestion: VirtualBox and Hyper-V are having a conflict. Use '--driver=hyperv' or disable Hyper-V using: 'bcdedit /set hypervisorlaunchtype off'
* Related issues:
  - https://github.com/kubernetes/minikube/issues/4051
  - https://github.com/kubernetes/minikube/issues/4783

### Operating System

Windows

### Driver

VirtualBox

**Comment by klaases** [comment]
Hi @krishnarayapudi25, please try running `minikube delete --all` to remove all profiles. Then run `minikube start` to run with your preferred driver. Does this help resolve the issue?

**Comment by krishnarayapudi25** [comment]
worked

**Comment by klaases** [comment]
Hi @krishnarayapudi25, glad to hear and thanks for working with minikube!
