### ISSUE TITLE
Image pull times out with minikube behind proxy

### ISSUE THREAD

**Issue by unmarshall** [kubernetes/minikube#1415]
Similar to Issue #530 
**Environment**
- **Minikube Version**: v0.18.0
- **kubectl version**:  
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.2", GitCommit:"477efc3cbe6a7effca06bd1452fa356e2201e1ee", GitTreeState:"clean", BuildDate:"2017-04-19T20:33:11Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"dirty", BuildDate:"2017-04-07T20:46:46Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
- **OS**: Mac OSX Sierra (10.12.3)
- **VM Driver** (cat ~/.minikube/machines/minikube/config.json | grep DriverName): 
"DriverName": "virtualbox" 
- **Docker Version**: Docker version 17.03.1-ce, build c6d412e

**Description**
Following set up steps were followed to configure and start minikube

- I started minikube with:
minikube start --docker-env HTTPS_PROXY=http://proxy.blrl.sap.corp:8080 --docker-env HTTP_PROXY=http://proxy.blrl.sap.corp:8080
I have also tried using lower cased http_proxy and https_proxy (result is the same)
- export no_proxy=127.0.0.1,localhost,$(minikube ip)

I am able to get nodes, get pods and use the existing deployed images to start pods.

When i try and run a simple kubectl command to run an echoserver image (which has not been downloaded yet):
kubectl run hello-minikube --image=gcr.io/google_containers/echoserver:1.4 --port=8443. The pod transitions to ImagePullBackOff.

kubectl describe  kubectl describe pods hello-minikube-1203707573-44xrk it gives the following `Name:		hello-minikube-1203707573-kvqdg
Namespace:	default
Node:		minikube/192.168.99.100
Start Time:	Wed, 26 Apr 2017 15:35:44 +0530
Labels:		pod-template-hash=1203707573
		run=hello-minikube
Annotations:	kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"hello-minikube-1203707573","uid":"e9400c2b-2a67-11e7-885f-080027...
Status:		Pending
IP:		172.17.0.8
Controllers:	ReplicaSet/hello-minikube-1203707573
Containers:
  hello-minikube:
    Container ID:
    Image:		gcr.io/google_containers/echoserver:1.4
    Image ID:
    Port:		8443/TCP
    State:		Waiting
      Reason:		ImagePullBackOff
    Ready:		False
    Restart Count:	0
    Environment:	<none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-z1k0q (ro)
Conditions:
  Type		Status
  Initialized 	True
  Ready 	False
  PodScheduled 	True
Volumes:
  default-token-z1k0q:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-z1k0q
    Optional:	false
QoS Class:	BestEffort
Node-Selectors:	<none>
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubObjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  1m		1m		1	default-scheduler					Normal		Scheduled	Successfully assigned hello-minikube-1203707573-kvqdg to minikube
  19s		19s		1	kubelet, minikube	spec.containers{hello-minikube}	Warning		Failed		Failed to pull image "gcr.io/google_containers/echoserver:1.4": rpc error: code = 2 desc = Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 74.125.68.82:443: i/o timeout
  19s		19s		1	kubelet, minikube					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "hello-minikube" with ErrImagePull: "rpc error: code = 2 desc = Error response from daemon: Get https://gcr.io/v1/_ping: dial tcp 74.125.68.82:443: i/o timeout"

  18s	18s	1	kubelet, minikube	spec.containers{hello-minikube}	Normal	BackOff		Back-off pulling image "gcr.io/google_containers/echoserver:1.4"
  18s	18s	1	kubelet, minikube					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "hello-minikube" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/echoserver:1.4\""

  1m	7s	2	kubelet, minikube	spec.containers{hello-minikube}	Normal	Pulling	pulling image "gcr.io/google_containers/echoserver:1.4"`

It is clear that the image pull timed out.
When i SSH into minikube VM and the i find that:
- there are no proxy system or environment properties set
- there is no profile file at /var/lib/boot2docker/

I am able to use docker native commands to pull images though. I suspect that docker-env only sets the proxy for the docker containers and not for the VM on which the minikube is being setup.

Any ideas on how to resolve this issue as the current solutions are not working.

Best Regards,
Madhav

**Comment by r2d4** [comment]
Can you run `minikube ssh -- systemctl show docker --property=Environment --no-pager`?

**Comment by unmarshall** [comment]
>>Can you run minikube ssh -- systemctl show docker --property=Environment --no-pager
Environment=DOCKER_RAMDISK=yes

I made it work. The trick was that one needs to SSH into the VM started with minikube. Get the gateway IP via netstat and then use that IP as the proxy configuration for the docker daemon that runs on my mac. I had to also setup a proxy listening on a port and use that port in the proxy address set on the docker daemon.

I wish this could be made a bit easier. I will close the issue now.

Best Regards,
Madhav

**Comment by endejoli** [comment]
Can you paste your configuration ?  I am facing similar issue

**Comment by Rev1408** [comment]
I have the same isue

**Comment by nayyaung** [comment]
For those unaware, you can use `route -n` to get the gateway IP and set it as http_proxy
