### ISSUE TITLE
(CentOS Linux release 7.9) Minikube addons enable ingress ERROR

### ISSUE THREAD

**Issue by yoelgf** [kubernetes/minikube#14189]
minikube addons enable ingress

❌  Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

</details>

**El resultado del comando `minikube logs`**: <details>

![Screenshot 2022-05-18 at 12 29 43](https://user-images.githubusercontent.com/9391553/169019592-a08f9c9f-1c1a-4786-afe7-c177064731bb.png)

**Comment by kadern0** [comment]
Hola @yoelgf, para poder entender cuál es la causa del problema es necesario que adjuntes los dos ficheros que se especifican en ese error: `logs.txt` y `/tmp/minikube_addons_cb9f....*.log`.

**Comment by KAKALZF** [comment]
I also met the same quetion

**Comment by kadern0** [comment]
@KAKALZF, if you are facing the same problem, could you please attach the logs to this issue?

**Comment by klaases** [comment]
Hi @yoelgf, you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support
