### ISSUE TITLE
IP of gateway should be dynamically detected

### ISSUE THREAD

**Issue by tsjk** [kubernetes/minikube#14192]
### What Happened?

I recently migrated to minikube from a custom-built docker-machine setup (with a now ancient userland) on my macOS v10.15.7 (19H1824) system.
It all works well, with 9P, NFS and CIFS mounts all operating (I use all of them as different mounts work with different apps depending on the file locking required).
One of the immediate issues I had to solve however was to fix the /etc/hosts file. I have a routed network on 192.168.64.0/24, and thus using that for virtual machines is unsuitable. I have configured the dhcp server for vm nets to supply IPs from  192.168.255.0/24 instead. Thus, after the minikube vm boots I do this (from the host machine):
```
cat <<-'__minikube_setup_etc_hosts_EOF1' | minikube ssh --native-ssh=false -- sudo bash
                VM_HOST_IP_ADDRESS="`route -n | awk -F ' ' '(($1 == "0.0.0.0") && ($NF == "eth0")) { print $2 }'`" && \
                sed -i -E '\@host\.minikube\.internal@s@^[0-9\.]+@'"${VM_HOST_IP_ADDRESS}"'@' /etc/hosts
__minikube_setup_etc_hosts_EOF1
```
It would be nice however if this was done automatically.

### Attach the log file

Not applicable.

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by klaases** [comment]
Hi @tsjk, thanks for filing this request. We are always open to accepting community contributions.
