### ISSUE TITLE
❌  Exiting due to RUNTIME_ENABLE: sudo systemctl daemon-reload: exit status 1 stdout:  stderr: System has not been booted with systemd as init system (PID 1). Can't operate.

### ISSUE THREAD

**Issue by Madhan911** [kubernetes/minikube#14191]
### What Happened?

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl daemon-reload: exit status 1
stdout:

stderr:
System has not been booted with systemd as init system (PID 1). Can't operate.

above error i am getting in linux , not able to resolve it 

### Attach the log file

![image](https://user-images.githubusercontent.com/84218555/169066868-2dc1de74-dce9-4282-ad2e-89b5bebd2796.png)

### Operating System

Ubuntu

**Comment by afbjorklund** [comment]
This is related to #12276, it needs to stop calling `systemctl` on systems that are not running systemd - such as this WSL

**Comment by klaases** [comment]
Hi @Madhan911 – I see that the related issue https://github.com/kubernetes/minikube/issues/12276, is now closed, does this help resolve this issue?

If not, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
