### ISSUE TITLE
Publish releases to Windows Package Manager (WinGet)

### ISSUE THREAD

**Issue by vedantmgoyal2009** [kubernetes/minikube#14190]
### What Happened?

With every new release of Minikube, use a GitHub workflow to update manifests at https://github.com/microsoft/winget-pkgs repository.

I can create a pull request if maintainers would like.

### Attach the log file

N/A

### Operating System

Windows

### Driver

N/A

**Comment by spowelljr** [comment]
Hi @vedantmgoyal2009, you're free to implement this if you'd like. This will be completely automated once implemented, correct?
