### ISSUE TITLE
Request hangs when accessing a pod through a service

### ISSUE THREAD

**Issue by migueloller** [kubernetes/minikube#1419]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Minikube version**: v0.18.0

**Environment**:
- **OS**: Mac OS X v10.12.4
- **VM Driver**: xhyve
- **ISO version**: v0.18.0

**What happened**:
Making a request from a pod to a service that routes to the pod itself causes the request to hang.

**What you expected to happen**:
The request shouldn't hang.

**How to reproduce it**:
```bash
# After setting up Minikube...
kubectl run nginx --image=nginx
kubectl expose deploy nginx --port=80
POD_NAME=$(kubectl get po -o jsonpath='{.items[0].metadata.name}')
kuebctl exec ${POD_NAME} -- apt-get update -y
kuebctl exec ${POD_NAME} -- apt-get install curl -y
kubectl exec ${POD_NAME} -- curl nginx
```

**Anything else do we need to know**:
If you scale the deployment to 2 replicas you will be able to see that the curl command will work after a 15 second timeout if it hits the pod running the curl command or immediately if the service happens to hit the other pod. If you scale back down to 1 replica then the service will always hit the same pod (the one calling the curl command) and it will hang even past the 15 second timeout (it will eventually time out after 2 minutes).

I tested this on GKE and didn't have the issue so I'm assuming it's a Minikube issue.

**Comment by RiaanLab** [comment]
Exactly the same issue on bare metal install of k8s v1.6.2. I dont have the same issues on GKE.

**Comment by anuragy** [comment]
This is still an issue in Minikube
