### ISSUE TITLE
Minikube image load on MacOS will cache an arm64 image even though minikube vm runs with qemu as amd64

### ISSUE THREAD

**Issue by pre** [kubernetes/minikube#14206]
### What Happened?

Minikube VM runs on `amd64` cpu architecture with qemu and container images should also be of that cpu arch.

With MacOS M1 `arm64`, when preloading images to cache with `minikube image load`, the cached image will be of `arm64`. As a result, the preloaded cached image cannot be used by the container which requires platform `amd64`. 

Steps to reproduce:

```
# On MacOS arm64
> minikube image load --pull=true --daemon=true docker.io/argoproj/argocd:v2.3.1

# Should be able to load amd64 image instead
> ls ~/.minikube/cache/images
arm64
```

### Attach the log file
```
stat: cannot stat '/var/lib/minikube/images/argocd_v2.3.1': No such file or directory
I0522 21:44:29.350124   66746 ssh_runner.go:362] scp /Users/pre/.minikube/cache/images/arm64/docker.io/argoproj/argocd_v2.3.1 --> /var/lib/minikube/images/argocd_v2.3.1 (207232000 bytes)
I0522 21:44:36.964331   66746 docker.go:254] Loading image: /var/lib/minikube/images/argocd_v2.3.1
I0522 21:44:36.964367   66746 ssh_runner.go:195] Run: /bin/bash -c "sudo cat /var/lib/minikube/images/argocd_v2.3.1 | docker load"
I0522 21:45:01.188533   66746 ssh_runner.go:235] Completed: /bin/bash -c "sudo cat /var/lib/minikube/images/argocd_v2.3.1 | docker load": (24.22389675s)
I0522 21:45:01.188569   66746 cache_images.go:315] Transferred and loaded /Users/pre/.minikube/cache/images/arm64/docker.io/argoproj/argocd_v2.3.1 from cache
I0522 21:45:01.188694   66746 cache_images.go:123] Successfully loaded all cached images
I0522 21:45:01.188702   66746 cache_images.go:92] LoadImages completed in 32.081307416s
I0522 21:45:01.188711   66746 cache_images.go:262] succeeded pushing to: my-dev-cluster-2
```

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
Minikube is supposed to use the native architecture for the VM, and therefore also by default for the container images.

It _should_ be possible to run images from other platforms with qemu-user, but not sure if binfmt_misc is always set up ?

**Comment by afbjorklund** [comment]
Need to make "defaultPlatform" into a overridable parameter.

```go
var defaultPlatform = v1.Platform{
        Architecture: runtime.GOARCH,
        OS:           "linux",
}

```

**Comment by pre** [comment]
in my use case I have Docker Desktop with —driver=docker. Docker runs with qemu and is slow, of course, but the images are amd64. In this use case many components we need are not compatible with arm64. 

Being able to provide `—platform` to `minikube image load` would help in this case.

**Comment by afbjorklund** [comment]
Running with qemu-user when absolutely required is still faster than running everything (including kernel) with qemu-system.

So it should be supported, and the cache now has arch subdirectories so storage should not be an issue. Just the --platform.

**Comment by klaases** [comment]
Hi @pre – did the above comments help resolve the issue?

If not, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
