### ISSUE TITLE
More than one tunnel is running

### ISSUE THREAD

**Issue by tzuf-illumex** [kubernetes/minikube#14203]
### What Happened?

While trying to connect minikube it showed the error : "another tunnel is already running, shut it down first..."
ministop & restart did not seem to work.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8748842/logs.txt)

### Operating System

Other

**Comment by klaases** [comment]
Hi @tzuf-illumex – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
