### ISSUE TITLE
Exiting due to GUEST_START: error on running minikube start

### ISSUE THREAD

**Issue by KakoozaJerry** [kubernetes/minikube#14207]
### What Happened?

On running minikube start on my macbook m1 2020, I get the error below

### Attach the log file

 minikube v1.25.2 on Darwin 12.3.1 (arm64)
    ▪ KUBECONFIG=/etc/kubernetes/admin.conf
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1988MB) ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...

❌  Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /etc/kubernetes: mkdir /etc/kubernetes: permission denied

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
Normally the KUBECONFIG is in your home directory, less permission errors that way.

**Comment by KakoozaJerry** [comment]
I enabled Kubernetes on my docker and also ran this command below in `~/.kube/config`

```
sudo chown $(id -u):$(id -g) $HOME/.kube/config   
```

Seemed to have solved my error
