### ISSUE TITLE
Cannot open dashboard

### ISSUE THREAD

**Issue by fdfytr** [kubernetes/minikube#14204]
### What Happened?

I'm using minikube on Debian 11 server and do not see dashboard
minikubes creates proxy and link but webpage is empty
Tried different browsers

there is a bridge network assigned and it looks like podman created a separate one
Not sure if that may be the reason

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8749420/log.txt)

### Operating System

Other

### Driver

Podman

**Comment by afbjorklund** [comment]
Minikube creates a private bridge for the cluster, and it should be reachable from the kubectl proxy.

`minikube kubectl cluster-info`

**Comment by fdfytr** [comment]
> kubernetes-dashboard logs

 Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
🎉  Opening http://127.0.0.1:42963/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
👉  http://127.0.0.1:42963/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/

controlpanel https://192.168.49.2:8443 is not accessible 

is firebaseinstallations.googleapis has anything to do? im using nextdns and noticed blocks there (allowing doesnt help though)

**Comment by afbjorklund** [comment]
The exact network can vary, but it should output yours (you can also check `podman network inspect`)

**Comment by fdfytr** [comment]
> You can see the kubernetes-dashboard logs, if there were any problems with starting the application ?

`Creating podman container (CPUs=2, Memory=2200MB) ...\ E0604 12:43:45.986302     349 network_create.go:95] error while trying to create podman network minikube 192.168.49.0/24: create podman network minikube 192.168.49.0/24 with gateway 192.168.49.1 and MTU of 0: sudo -n podman network create --driver=bridge --subnet=192.168.49.0/24 --gateway=192.168.49.1 --label=created_by.minikube.sigs.k8s.io=true minikube: exit status 125
stdout:

stderr:
Error: network name minikube already used: network already exists

❗  Unable to create dedicated network, this might result in cluster IP change after restart: un-retryable: create podman network minikube 192.168.49.0/24 with gateway 192.168.49.1 and MTU of 0: sudo -n podman network create --driver=bridge --subnet=192.168.49.0/24 --gateway=192.168.49.1 --label=created_by.minikube.sigs.k8s.io=true minikube: exit status 125
stdout:

stderr:
Error: network name minikube already used: network already exists`




> The exact network can vary, but it should output yours (you can also check `podman network inspect`)

podman network inspect podman

`ERRO[0000] cannot find UID/GID for user grizzly: open /etc/subuid: no such file or directory - check rootless mode in man pages.
WARN[0000] Using rootless single mapping into the namespace. This might break some images. Check /etc/subuid and /etc/subgid for adding sub*ids if not using a network user
[
     {
          "name": "podman",
          "id": "2f259bab93aaaaa2542ba43ef33eb990d0999ee1b9924b557b7be53c0b7a1bb9",
          "driver": "bridge",
          "network_interface": "podman0",
          "created": "2022-06-04T15:20:46.536477072+01:00",
          "subnets": [
               {
                    "subnet": "10.88.0.0/16",
                    "gateway": "10.88.0.1"
               }
          ],
          "ipv6_enabled": false,
          "internal": false,
          "dns_enabled": false,
          "ipam_options": {
               "driver": "host-local"
          }
     }
]`

**Comment by afbjorklund** [comment]
I think that would be: podman network inspect minikube

**Comment by fdfytr** [comment]
Error: inspecting object: network minikube: unable to find network with name or ID minikube: network not found

**Comment by fdfytr** [comment]
[The UI can only be accessed from the machine where the command is executed.](https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/) 

Does it mean that dashboard wont be accessible at another machine at local network?
I thought it is a good alternative for portainer...

**Comment by afbjorklund** [comment]
> Does it mean that dashboard wont be accessible at another machine at local network?

It uses kubectl proxy, which is only available to localhost

Otherwise you need a deployment cluster, with login etc

**Comment by fdfytr** [comment]
> Otherwise you need a deployment cluster, with login etc

Thank you, that is actually explains the issue.
