### ISSUE TITLE
podman-remote fails on Fedora 36

### ISSUE THREAD

**Issue by jessesaga** [kubernetes/minikube#14201]
### What Happened?

On Fedora 36 with podman 4.1.0 podman-remote fails with the following error

Error: unable to connect to Podman socket: server API version is too old. Client "4.0.0" server "3.4.2"

### Attach the log file

* 
* ==> Audit <==
* |------------|--------------------------------|----------|----------|----------------|-------------------------------|-------------------------------|
|  Command   |              Args              | Profile  |   User   |    Version     |          Start Time           |           End Time            |
|------------|--------------------------------|----------|----------|----------------|-------------------------------|-------------------------------|
| start      | --driver=podman                | minikube | dev-user | v1.26.0-beta.1 | 20 May 22 22:26 EDT           | 20 May 22 22:27 EDT           |
|            | --container-runtime=cri-o      |          |          |                |                               |                               |
| addons     | enable ingress                 | minikube | dev-user | v1.26.0-beta.1 | 20 May 22 22:28 EDT           | 20 May 22 22:28 EDT           |
| kubectl    | -- create secret tls           | minikube | dev-user | v1.26.0-beta.1 | 20 May 22 22:28 EDT           | 20 May 22 22:28 EDT           |
|            | minikube-dev.local --key       |          |          |                |                               |                               |
|            | minikube-dev.local+4-key.pem   |          |          |                |                               |                               |
|            | --cert                         |          |          |                |                               |                               |
|            | minikube-dev.local+4.pem       |          |          |                |                               |                               |
| podman-env |                                | minikube | dev-user | v1.26.0-beta.1 | 20 May 22 22:29 EDT           | 20 May 22 22:29 EDT           |
|------------|--------------------------------|----------|----------|----------------|-------------------------------|-------------------------------|

* 
* ==> Last Start <==
* Log file created at: 2022/05/20 22:26:50
Running on machine: fedora
Binary: Built with gc go1.18.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0520 22:26:50.375612   73539 out.go:296] Setting OutFile to fd 1 ...
I0520 22:26:50.376085   73539 out.go:343] TERM=dumb,COLORTERM=, which probably does not support color
I0520 22:26:50.376103   73539 out.go:309] Setting ErrFile to fd 2...
I0520 22:26:50.376176   73539 out.go:343] TERM=dumb,COLORTERM=, which probably does not support color
I0520 22:26:50.376280   73539 root.go:322] Updating PATH: /home/dev-user/.minikube/bin
I0520 22:26:50.376520   73539 out.go:303] Setting JSON to false
I0520 22:26:50.378305   73539 start.go:115] hostinfo: {"hostname":"fedora","uptime":21113,"bootTime":1653078898,"procs":398,"os":"linux","platform":"fedora","platformFamily":"fedora","platformVersion":"36","kernelVersion":"5.17.8-300.fc36.x86_64","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"guest","hostId":"fbc9530b-93d7-4e65-9522-628cef4bbc93"}
I0520 22:26:50.378347   73539 start.go:125] virtualization: kvm guest
I0520 22:26:50.400679   73539 out.go:177] * minikube v1.26.0-beta.1 on Fedora 36 (kvm/amd64)
I0520 22:26:50.432574   73539 notify.go:193] Checking for updates...
I0520 22:26:50.432869   73539 driver.go:358] Setting default libvirt URI to qemu:///system
I0520 22:26:50.584050   73539 podman.go:123] podman version: 4.1.0
I0520 22:26:50.608533   73539 out.go:177] * Using the podman driver based on user configuration
I0520 22:26:50.639084   73539 start.go:284] selected driver: podman
I0520 22:26:50.639100   73539 start.go:806] validating driver "podman" against <nil>
I0520 22:26:50.639184   73539 start.go:817] status for podman: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0520 22:26:50.639658   73539 cli_runner.go:164] Run: sudo -n podman system info --format json
I0520 22:26:50.787625   73539 info.go:287] podman info: {Host:{BuildahVersion:1.26.1 CgroupVersion:v2 Conmon:{Package:conmon-2.1.0-2.fc36.x86_64 Path:/usr/bin/conmon Version:conmon version 2.1.0, commit: } Distribution:{Distribution:fedora Version:36} MemFree:11263066112 MemTotal:25253793792 OCIRuntime:{Name:crun Package:crun-1.4.4-1.fc36.x86_64 Path:/usr/bin/crun Version:crun version 1.4.4
commit: 6521fcc5806f20f6187eb933f9f45130c86da230
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +YAJL} SwapFree:8589930496 SwapTotal:8589930496 Arch:amd64 Cpus:16 Eventlogger:journald Hostname:fedora Kernel:5.17.8-300.fc36.x86_64 Os:linux Security:{Rootless:false} Uptime:5h 51m 52.69s (Approximately 0.21 days)} Registries:{Search:[registry.fedoraproject.org registry.access.redhat.com docker.io quay.io]} Store:{ConfigFile:/etc/containers/storage.conf ContainerStore:{Number:0} GraphDriverName:overlay GraphOptions:{} GraphRoot:/var/lib/containers/storage GraphStatus:{BackingFilesystem:btrfs NativeOverlayDiff:false SupportsDType:true UsingMetacopy:true} ImageStore:{Number:0} RunRoot:/run/containers/storage VolumePath:/var/lib/containers/storage/volumes}}
I0520 22:26:50.787744   73539 start_flags.go:292] no existing cluster config was found, will generate one from the flags 
I0520 22:26:50.789040   73539 start_flags.go:373] Using suggested 6000MB memory alloc based on sys=24083MB, container=24083MB
I0520 22:26:50.789205   73539 start_flags.go:829] Wait components to verify : map[apiserver:true system_pods:true]
I0520 22:26:50.816222   73539 out.go:177] * Using Podman driver with the root privilege
I0520 22:26:50.831446   73539 cni.go:95] Creating CNI manager for ""
I0520 22:26:50.831468   73539 cni.go:162] "podman" driver + crio runtime found, recommending kindnet
I0520 22:26:50.831479   73539 start_flags.go:301] Found "CNI" CNI - setting NetworkPlugin=cni
I0520 22:26:50.831509   73539 start_flags.go:306] config:

............... too long for github issue .......

### Operating System

Redhat/Fedora

### Driver

Podman

**Comment by afbjorklund** [comment]
If you want to use `minikube podman-env`, you need to use a client matching the server...

Alternatively you can run without client/server, using `minikube ssh sudo podman` instead.

**Comment by jessesaga** [comment]
Right. I just figured it was worth noting that the version of podman that ships with Fedora 36 exhibits this issue with the current versions of minikube including v1.26.0-beta.1. I've already worked around the issue but I was surprised when I upgraded from Fedora 35 and things started failing.

**Comment by afbjorklund** [comment]
Unlike Docker, the Podman client is not backwards compatible. So the versions needs to match.

**Comment by jessesaga** [comment]
Understood. I'll close this ticket since it's more of a podman issue and minikube can't really be expected so support all incompatible podman versions.

It might be worth adding some language to the documentation around minikube and podman to mention the podman version sensitivity. https://minikube.sigs.k8s.io/docs/drivers/podman/

**Comment by afbjorklund** [comment]
You can also use `minikube image`, which is compatible with all runtimes and all versions.

Eventually the legacy "docker-env" and "Podman-env" will not be needed anymore...

**Comment by afbjorklund** [comment]
Note that it is not related to the driver, but to the runtime...

The host runtime can be newer, than the cluster runtime
