### ISSUE TITLE
minikube SSH driver + Apple M1 not working. The minikube does not check the OS of the target VM.

### ISSUE THREAD

**Issue by aarzhanov** [kubernetes/minikube#14214]
### What Happened?

I am trying to start minikube on Apple M1 with x86_64 Ubuntu 20.04 target VM (SSH driver).

The process ends with an error:
`error: /var/lib/minikube/binaries/v1.19.12/kubeadm: 1: Syntax error: “)” unexpected`

I found the reason for the error.
The minikube is copied to the **remote x86_64 machine** in directory "/var/lib/minikube/binaries/v*/" and in directory "/var/lib/minikube/images/ " files for  **ARM aarch64 architecture**.

### Attach the log file

![Screenshot 2022-05-20 at 15 54 20](https://user-images.githubusercontent.com/12065749/169838806-693437af-a7e6-429f-9cc0-7c95ea58b781.png)

### Operating System

macOS (Default)

### Driver

SSH

**Comment by aarzhanov** [comment]
I found a temporary solution.
I run the minikube x86_64 through Rosetta 2.
In this case, the necessary x86_64 files will be copied to the target ssh vm.

**Comment by klaases** [comment]
Hi @aarzhanov, glad to hear about your temporary solution. As @afbjorklund mentioned, the code may eventually be split out into separate architectures, but this is a significant task. Thanks for your comment and am closing out for now to help clear the queue.
