### ISSUE TITLE
Mounted volume does not report correct stat timestamps

### ISSUE THREAD

**Issue by spwhitt** [kubernetes/minikube#1421]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Minikube version**: v0.18.0

**Environment**:
- **OS**: macOS Sierra 10.12.4
- **VM Driver**: xhyve and Virtualbox
- **ISO version** : v0.18.0

**What happened**:
I was trying to use `nodemon -L` and similar tools to monitor a volume for file changes. This works with Virtualbox shared folders, but not with Xhyve or the new `minikube mount` command. I traced the problem back to the output of `stat` which shows constantly changing timestamps for all files in the volume.

**What you expected to happen**:
The timestamps should only change when the file is changed/modified/accessed.

**How to reproduce it**:
1) Run `minikube start && minikube mount /some/dir`
2) `minikube ssh`
3) Run `stat /mount-9p/some/file` repeatedly and observe the changing result

**Anything else do we need to know**:
Since there are also no inotify events, this makes it impossible to set up a file watcher, which is very unfortunate.

**Comment by aaron-prindle** [comment]
Dupe of #1375

**Comment by spwhitt** [comment]
Don't know how I missed that. Thanks.
