### ISSUE TITLE
Katacoda platform hosting "hello minikube" could use open alternatives

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#14228]
The docs are running a "none" driver installation:

https://kubernetes.io/docs/tutorials/hello-minikube/

It is closing: https://www.oreilly.com/online-learning/leveraging-katacoda-technology.html

It would be nice if people could still run a minikube-based solution, for learning kubernetes ?

----

Document how to use minikube, in such an environment:

* https://github.com/kubernetes/website/issues/33936

It should allow for running `minikube start`, without any issues.

After that, `minikube kubectl` should "just work", out of the box.

**Comment by afbjorklund** [comment]
```
Your Interactive Learning Environment Bash Terminal

$ start.sh
Starting Kubernetes...minikube version: v1.18.0
commit: ec61815d60f66a6e4f6353030a40b12362557caa-dirty
* minikube v1.18.0 on Ubuntu 18.04 (amd64)
* Using the none driver based on existing profile

X The requested memory allocation of 2200MiB does not leave room for system overhead (total system memory: 2460MiB). You may face stability issues.
* Suggestion: Start minikube with less memory allocated: 'minikube start --memory=2200mb'

* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=2, Memory=2460MB, Disk=194868MB) ...
* OS release is Ubuntu 18.04.5 LTS
* Preparing Kubernetes v1.20.2 on Docker 19.03.13 ...
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Configuring local host environment ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v4
* Enabled addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
  - Using image k8s.gcr.io/metrics-server-amd64:v0.2.1
* The 'metrics-server' addon is enabled
  - Using image kubernetesui/metrics-scraper:v1.0.4
  - Using image kubernetesui/dashboard:v2.1.0
* Some dashboard features require the metrics-server addon. To enable all features please run:

        minikube addons enable metrics-server


* The 'dashboard' addon is enabled
Kubernetes Started
$ 
```

**Comment by afbjorklund** [comment]
Here are some hacks, using vagrant: (it could be changed, to use the "none" driver instead of the "ssh" driver)

* ~~ https://github.com/kubernetes/minikube/pull/12185~~

Eventually the efforts to run kubernetes with containerd and with ubuntu were moved to "lima" project instead:

https://github.com/lima-vm/lima/blob/master/examples/k8s.yaml

* ~~https://github.com/kubernetes/minikube/issues/9639~~

* ~~https://github.com/kubernetes/minikube/issues/9992~~

**Comment by Rabattkarte** [comment]
One alternative is killercoda.com

**Comment by afbjorklund** [comment]
I _think_ this is the scenario, the image source code and the licensing is unclear.

https://github.com/katacoda-scenarios/kubernetes-bootcamp-scenarios

**Comment by afbjorklund** [comment]
Here is vagrant file that handles most things, except for the storage provisioner (automount):

```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
  end
  config.vm.provision "shell", inline: <<-SHELL
    # docker provisioning
    if ! type docker; then curl -sSL https://get.docker.com | sh -; fi
    usermod -aG docker vagrant
    # minikube requirements
    apt-get update
    apt-get install -y conntrack
    # minikube installation
    curl -sSLO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
    sudo dpkg -i minikube_latest_amd64.deb
    # minikube preparation
    su vagrant -c "minikube config set driver none"
    su vagrant -c "minikube start --download-only"
  SHELL
end
```

After doing `vagrant up`, one can do `vagrant ssh` and see the scary output from the default:

```
😄  minikube v1.25.2 on Ubuntu 20.04 (vbox/amd64)
✨  Using the none driver based on user configuration

🧯  The requested memory allocation of 1983MiB does not leave room for system overhead (total system memory: 1983MiB). You may face stability issues.
💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=1983mb'

👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=2, Memory=1983MB, Disk=39642MB) ...
ℹ️  OS release is Ubuntu 20.04.4 LTS
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.16 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🤹  Configuring local host environment ...

❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl and minikube configuration will be stored in /home/vagrant
❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /home/vagrant/.kube /home/vagrant/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

Missing:

* storage provisioner automount script
* kubernetes dashboard and metrics-server

**Comment by afbjorklund** [comment]
Note that the above will break with v1.24.0, since it doesn't install `crictl` and `cri-dockerd`.

It also doesn't install a CNI configuration, so it doesn't work with any other container runtimes.

**Comment by afbjorklund** [comment]
This extra information in the output is not particularly helpful:

🤹  Configuring local host environment ...
❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl and minikube configuration will be stored in /home/vagrant
❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:
    ▪ sudo mv /home/vagrant/.kube /home/vagrant/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

_(note that $HOME and /home/vagrant is the same thing...)_

**Comment by afbjorklund** [comment]
> One alternative is killercoda.com

It is not _entirely_ obvious, where the source code for these images (either katacoda or killercoda) are being hosted ?

https://github.com/killercoda/scenario-examples

> `kubernetes-kubeadm-2nodes`: Kubeadm latest (atm 1.24) cluster with one controlplane and one node, ready to schedule workload.
> `kubernetes-kubeadm-1node`: Kubeadm latest (atm 1.24) cluster with one controlplane, taint removed, ready to schedule workload. Loads faster then 2nodes!

https://github.com/katacoda-scenarios/kubernetes-scenarios

> Kubernetes Cluster 1.21 | 2 nodes with kubeadm installed, nothing running. Based on Ubuntu.Designed for teaching how to use Kubernetes from scratch | `kubernetes-cluster `/ kubernetes-cluster:1.14
> Kubernetes Cluster 1.21 (Pre-configured) | 2 node cluster with 1 main, 1 node. Based on Ubuntu.Run launch.sh when the scenario starts to ensure cluster is running. | `kubernetes-cluster-running` / kubernetes-cluster-running:1.14

**Comment by afbjorklund** [comment]
It is also possible to use the same vagrant setup, and over-allocate two system containers on the same VM.

`minikube start --driver=docker --nodes=2`

```
NAME           STATUS   ROLES                  AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
minikube       Ready    control-plane,master   59s   v1.23.3   192.168.49.2   <none>        Ubuntu 20.04.2 LTS   5.4.0-113-generic   docker://20.10.12
minikube-m02   Ready    <none>                 34s   v1.23.3   192.168.49.3   <none>        Ubuntu 20.04.2 LTS   5.4.0-113-generic   docker://20.10.12
```

This way it will have both CRI and CNI, installed on the nodes.

```console
vagrant@ubuntu-focal:~$ minikube start --driver=docker --nodes=2
😄  minikube v1.25.2 on Ubuntu 20.04 (vbox/amd64)
✨  Using the docker driver based on user configuration

🧯  The requested memory allocation of 1983MiB does not leave room for system overhead (total system memory: 1983MiB). You may face stability issues.
💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=1983mb'

👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1983MB) ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
    ▪ kubelet.cni-conf-dir=/etc/cni/net.mk
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner

👍  Starting worker node minikube-m02 in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=1983MB) ...
🌐  Found network options:
    ▪ NO_PROXY=192.168.49.2
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ env NO_PROXY=192.168.49.2
🔎  Verifying Kubernetes components...
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

**Comment by afbjorklund** [comment]
Apparently "hello minikube" is **not** shutting down

**Comment by afbjorklund** [comment]
Katacoda (O'Reilly) is shutting down _all_ environments in 2022, including the Kubernetes.io tutorials and images.

* https://github.com/kubernetes/website/issues/33936#issuecomment-1346832443
