### ISSUE TITLE
Very slow startup and shutdown of Minikube VM instance

### ISSUE THREAD

**Issue by rprodan** [kubernetes/minikube#14222]
### What Happened?

I am observing tremendously slow startup and shutdown phase of Minikube instance. I installed fresh **Minikube v1.25.2** on **Microsoft Windows 10** Enterprise LTSC 2019 10.0.17763 Build 17763 and **VirtualBox** 6.1.34. I am using **virtualbox** driver.

Startup command

`minikube start --no-vtx-check --alsologtostderr --v=1`

The above command takes up approx. 7 minutes and most notably the logs are stopped in

```
Waiting for VM "minikube" to power on...
VM "minikube" has been successfully started.
}
I0524 16:26:47.549816   31848 main.go:130] libmachine: STDERR:
{
}
I0524 16:26:47.549816   31848 main.go:130] libmachine: Waiting for an IP...
I0524 16:26:47.549816   31848 main.go:130] libmachine: Getting to WaitForSSH function...
I0524 16:26:47.552749   31848 main.go:130] libmachine: Using SSH client type: native
I0524 16:26:47.553722   31848 main.go:130] libmachine: &{{{<nil> 0 [] [] []} docker [0x115bfa0] 0x115ee60 <nil>  [] 0s} 127.0.0.1 59242 <nil> <nil>}
I0524 16:26:47.553722   31848 main.go:130] libmachine: About to run SSH command:
exit 0
I0524 16:27:30.064936   31848 main.go:130] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:59398->127.0.0.1:59242: wsarecv: An existing connection was forcibly closed by the remote host.
I0524 16:27:33.286592   31848 main.go:130] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:59403->127.0.0.1:59242: wsarecv: An existing connection was forcibly closed by the remote host.
I0524 16:27:36.344011   31848 main.go:130] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:59405->127.0.0.1:59242: wsarecv: An existing connection was forcibly closed by the remote host.
I0524 16:27:41.116486   31848 main.go:130] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:59406->127.0.0.1:59242: wsarecv: An existing connection was forcibly closed by the remote host.
I0524 16:27:44.434538   31848 main.go:130] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:59415->127.0.0.1:59242: wsarecv: An existing connection was forcibly closed by the remote host.
```

It appears Minikube startup process is checking free ports and this takes considerable amount of time. Nevertheless Minikube starts and is up and running.

The shutdown phase is even more slower but somehow stops.

`minikube stop --alsologtostderr --v=1`

But if I want to start my instance again it just takes forever and hangs.

`minikube start --alsologtostderr --v=1`

```
* minikube v1.25.2 on Microsoft Windows 10 Enterprise LTSC 2019 10.0.17763 Build 17763
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! This VM is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
  - kubelet.housekeeping-interval=5m
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Verifying Kubernetes components...
```

### Attach the log file

Log file created after starting Minikube instance [log.txt](https://github.com/kubernetes/minikube/files/8764162/log.txt)

### Operating System

Windows

### Driver

VirtualBox

**Comment by klaases** [comment]
Hi @rprodan  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support

**Comment by rprodan** [comment]
@klaases I switched to **hyperv** driver after several unsuccessfull atempts to stabilize fast Minikube startup with **virtual box** driver.
