### ISSUE TITLE
minikube service <svc> documentation outdated, no way to undo its effect?

### ISSUE THREAD

**Issue by attila123** [kubernetes/minikube#14235]
### What Happened?

As per https://minikube.sigs.k8s.io/docs/handbook/accessing/ I wanted to make a NodePort service accessible, e.g. `minikube service <svc> --url`

I get it working (on Linux host), `minikube service list` shows it, but now how can I undo this?

The documentation does not provide any hint how to make the service inaccessible again, so how to undo the effect of `minikube service <svc>`.

The documentation mentions `$ ps -ef | grep docker@127.0.0.1` -> I did not find such process.  
I also tried to grep to the port name in the URL (as listed by `minikube service list`), e.g. `sudo ps -ef | grep 30443` in my case, found nothing.  
`sudo netstat -tlnp`: found nothing.

Also, I tried to change it to https, e.g. `minikube service <svc> --url --https`, but `minikube service list` still shows it as http.

(Not related to this documentation problem, I run minikube on Arch Linux.)
```
$ minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7-dirty
```

```
$ minikube profile list
|---------------|------------|---------|----------------|------|---------|---------|-------|
|    Profile    | VM Driver  | Runtime |       IP       | Port | Version | Status  | Nodes |
|---------------|------------|---------|----------------|------|---------|---------|-------|
| minikube      | docker     | docker  | 192.168.49.2   | 8443 | v1.23.1 | Running |     1 |
| minikube-1-21 | virtualbox | docker  | 192.168.59.101 | 8443 | v1.21.9 | Stopped |     1 |
|---------------|------------|---------|----------------|------|---------|---------|-------|
```

### Attach the log file

Logs are not relevant as it is mainly documentation issue.

### Operating System

Other

### Driver

Docker

**Comment by yuzhaopeng** [comment]
maybe try to restart minikube

**Comment by medyagh** [comment]
@attila123 are you using docker driver or a vm driver?

**Comment by medyagh** [comment]
@attila123 are you using docker driver or a vm driver?

on a VM driver the service ip:port always resolves to the service (even if you dont run the minikube service <svc> command


on docker driver on Mac and Windows it is a different story (since it needs a tunnel)

**Comment by spowelljr** [comment]
Hi @attila123, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
