### ISSUE TITLE
error when running "minikube start --driver=docker"

### ISSUE THREAD

**Issue by juneciel510** [kubernetes/minikube#14236]
### What Happened?

stderr:
        [WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
        [WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: x509: certificate signed by unknown authority (possibly because of "crypto/rsa: verification error" while trying to verify candidate authority certificate "minikubeCA")

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"
I0527 14:27:45.975060    4040 out.go:176]

I0527 14:27:45.977096    4040 out.go:176] ==> dmesg <==

### Attach the log file

E0527 14:31:41.026819    4083 logs.go:192] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.23.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.23.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

### Operating System

Ubuntu

### Driver

Docker

**Comment by yuzhaopeng** [comment]
Just like description in the log ，you should enable `bridge-nf-call-iptables `  and disable swap .
 before doing so,delete the old cache  

1.  Delete old cache 
    `minikube delete`

2.  Temporarily enable `bridge-nf-call-iptables`
 `sysctl -w net.bridge.bridge-nf-call-iptables=1`

3. Temporarily  disable swap 
 ` swapoff -a`

4. start minikube 
 `minikube start --driver=docker`

**Comment by spowelljr** [comment]
Hi @juneciel510, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
