### ISSUE TITLE
X Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

### ISSUE THREAD

**Issue by wankowatat** [kubernetes/minikube#14231]

**Comment by klaases** [comment]
Hi @wankowatat, this seems to be an issue with virtualization being enabled on your computer. Could you retry starting minikube with virtualization enabled?

**Comment by klaases** [comment]
Hi @wankowatat – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
