### ISSUE TITLE
minikube can not start

### ISSUE THREAD

**Issue by luis-giraldo** [kubernetes/minikube#14248]
### What Happened?

minikube can not start

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8800817/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Duplicate, #14202

**Comment by spowelljr** [comment]
Hi @luis-giraldo, since this is a duplicate I'm going to close this issue. Please follow along with https://github.com/kubernetes/minikube/issues/14202, thanks!
