### ISSUE TITLE
docker: open /var/lib/docker/tmp/GetImageBlob2246773910: no such file or directory.

### ISSUE THREAD

**Issue by DeepInsideWorld** [kubernetes/minikube#14243]
### What Happened?

[log.txt](https://github.com/kubernetes/minikube/files/8795627/log.txt)

### Attach the log file

file:///home/ngohoanglong/Downloads/log.txt

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @DeepInsideWorld, thanks for reporting your issue with minikube.

Your logs indicate the error is:
`docker: open /var/lib/docker/tmp/GetImageBlob2246773910: no such file or directory.`

Based on my research this seems to be a problem with your Docker (https://github.com/moby/moby/issues/22074).

Could your try some of the commands in that issue to restart Docker and then do a `minikube delete --all` to get back in a clean state and then try starting minikube again, thanks!
