### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by balajinsr** [kubernetes/minikube#14246]
C:\work\kube>minikube start --no-vtx-check
o   minikube v1.0.1 on windows (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running virtualbox VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.99.101
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.06.3-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
X   Unable to load cached images: loading cached images: loading image C:\Users\bn657134\.minikube\cache\images\k8s.gcr.io\pause_3.1: Docker load /tmp/pause_3.1: command failed: docker load -i /tmp/pause_3.1
stdout:
stderr: Error processing tar file(exit status 2): panic: runtime error: index out of range

goroutine 1 [running]:
regexp.makeOnePass.func1(0x4, 0xc4200b63f0, 0x2e, 0x2e, 0x0)
        /usr/local/go/src/regexp/onepass.go:404 +0x187f
regexp.makeOnePass.func1(0x7f3300000002, 0xc4200b63f0, 0x2e, 0x2e, 0x1b)
        /usr/local/go/src/regexp/onepass.go:349 +0xf1
regexp.makeOnePass.func1(0x1, 0xc4200b63f0, 0x2e, 0x2e, 0x2e)
        /usr/local/go/src/regexp/onepass.go:358 +0x614
regexp.makeOnePass(0xc42017ac60, 0xc42017ac60)
        /usr/local/go/src/regexp/onepass.go:448 +0x3d7
regexp.compileOnePass(0xc42017ac00, 0xc42017ac00)
        /usr/local/go/src/regexp/onepass.go:502 +0x1b5
regexp.compile(0x1a7a391, 0x83, 0x7f33f90000d4, 0xc4200e19a0, 0x0, 0x0)
        /usr/local/go/src/regexp/regexp.go:186 +0xef
regexp.Compile(0x1a7a391, 0x83, 0xc4200e19a0, 0x0, 0x0)
        /usr/local/go/src/regexp/regexp.go:133 +0x43
regexp.MustCompile(0x1a7a391, 0x83, 0xc4200e19a0)
        /usr/local/go/src/regexp/regexp.go:238 +0x4f

: Process exited with status 1

!   Failed to update cluster: downloading binaries: copying kubelet: copy: wait: remote command exited without exit status or exit signal

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by spowelljr** [comment]
Hi @balajinsr, thanks for reporting your issue with minikube!

You seem to be using minikube `v1.0.1` which is extremely old, could you please update to a current version of minikube (`v1.25.2`) and then run `minikube delete --all --purge` and then try starting minikube again, thanks!

`v1.25.2` downloads: https://github.com/kubernetes/minikube/releases/tag/v1.25.2

**Comment by spowelljr** [comment]
Hi @balajinsr, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
