### ISSUE TITLE
Enable IPVS proxy-mode in minikube 

### ISSUE THREAD

**Issue by Aadarsh-Verma** [kubernetes/minikube#14256]
### What Happened?

Cannot find documentation to enable ipvs proxy mode in minikube with  ipvs-scheduler as "rr"

### Attach the log file

NA

**Comment by spowelljr** [comment]
Hi @Aadarsh-Verma, thanks for reporting your issue with minikube.

If you want to use any Kubernetes flags you can use the `--extra-config` flag, it follows the format `--extra-config=<component>.<key>=<value>`. So in your case you'll add the following flag to your start command to use `ipvs`:
`--extra-config=kube-proxy.proxy-mode=ipvs`

You can find more information about this command by running `minikube start --help`

**Comment by klaases** [comment]
Hi @Aadarsh-Verma – were you able to try using the `--extra-config` flags as suggested above?

Also, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
