### ISSUE TITLE
Can't start minikube on Mac M1 silicon 

### ISSUE THREAD

**Issue by afanwang** [kubernetes/minikube#14276]
### What Happened?

 minikube start --driver=docker

😄  minikube v1.25.2 on Darwin 12.3.1 (arm64)
    ▪ KUBECONFIG=/Users/fan/.kube/azurek8s-dev
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.23.3 preload ...
    > preloaded-images-k8s-v17-v1...: 419.07 MiB / 419.07 MiB  100.00% 9.23 MiB
    > gcr.io/k8s-minikube/kicbase: 343.12 MiB / 343.12 MiB  100.00% 5.06 MiB p/
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
✋  Stopping node "minikube"  ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: provisioning: get ssh host-port: unable to inspect a not running container to get SSH port
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: waiting: Maximum number of retries (60) exceeded

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: waiting: Maximum number of retries (60) exceeded

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8838410/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @cecilphillip, could you run the command `minikube logs --file=logs.txt` and then upload the generated log file so I could see the kubelet and docker logs.

**Comment by cecilphillip** [comment]
@spowelljr I sorted it out. There was a script setting `export DOCKER_DEFAULT_PLATFORM=linux/amd64`.
I got it running now.

**Comment by spowelljr** [comment]
Glad you got it working @cecilphillip, I'll mark this issue as closed.
