### ISSUE TITLE
kvm2: container can't acquire file descriptors

### ISSUE THREAD

**Issue by Poweranimal** [kubernetes/minikube#14277]
My containers (specifically `envoy`) can't acquire any file descriptors after reaching a threshold of containers on my node, because the file descriptors seem to be exhausted.

The containers in question are `envoy` containers that all share the same uid `5995`.
After launching the 15th `envoy` container, all further `envoy` containers crash, because of a lack of file descriptors.

Incrementing the user id for each container (e.g. `5995`, `5996`, ...) solves the issue.
That indicates to me that the host sums up all file descriptors of all processes with the uid `5995` and checks it against a limit.

However, this seems to me very unlikely that the limit of my file descriptors get hit based on the following finding:

*Node Host FDs (kvm2)*
```shell
ulimit -Sn
# 1024
ulimit -Hn
# 524288
```

*Container FDs (inside container)*
```shell
ulimit -Sn
# 1048576
ulimit -Hn
# 1048576
```

*Total amount of all used FDs on Host*
```shell
ls -1 /proc/*/fd | wc -l
# 8953
```

*Total amount of all used FDs on Host with uid 5995*
```shell
ps -u 5995 | tr -s ' ' | cut -d ' ' -f 2 | xargs -tn 1 -I {} ls -1 /proc/{}/fd | wc -l
# ls -1 /proc/27441/fd 
# ls -1 /proc/28438/fd 
# ls -1 /proc/40617/fd 
# ls -1 /proc/40964/fd 
# ls -1 /proc/41428/fd 
# ls -1 /proc/41763/fd 
# ls -1 /proc/44359/fd 
# ls -1 /proc/67896/fd 
# ls -1 /proc/68257/fd 
# ls -1 /proc/68803/fd 
# ls -1 /proc/69175/fd 
# ls -1 /proc/69588/fd 
# ls -1 /proc/69871/fd 
# ls -1 /proc/70276/fd 
# 2124
```

The only idea I have what might be the issue here, is the soft limit `1024` of the host.
However, I was not able to change the soft limit of the host, because changing the soft limit in `/etc/security/limits.conf` or `/etc/systemd/{system.conf,user.conf}` requires a system restart. A restart of a minkube node using `kvm2` driver doesn't persist any data besides the data placed in specific directories (listed [here](https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/)). Thus my previously mentioned changes get lost.

Can one confirm that the soft cap of the node host might be the issue?
And if this is the case, can one explain me how to modify the softcap of file descriptors in a `kvm2` minikube node?

I look forward to your help.

**Comment by medyagh** [comment]
Hi this is an interesting issue @Poweranimal I am curious if you like to experiment building the ISO with a larger file limit
@afbjorklund might know the file limit size on the iso

**Comment by medyagh** [comment]
@Poweranimal I am curious have you tried the same thing with Docker Driver ? since that one is ubuntu I am curious what the difference is

**Comment by klaases** [comment]
Hi @Poweranimal, did you have a chance to review the above comments?

- larger ISO file limit
- try with Docker Driver

**Comment by klaases** [comment]
Hi @Poweranimal  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
