### ISSUE TITLE
Rootless config property not found

### ISSUE THREAD

**Issue by robshelly** [kubernetes/minikube#14270]
### What Happened?

Can't set config to run podman as rootless as instructed by the following docs:
https://minikube.sigs.k8s.io/docs/drivers/podman/

Using minikube v1.25.2 on Fedora 34

```
$ minikube config set rootless true

❌  Exiting due to MK_CONFIG_SET: find settings for "rootless" value of "true": property name "rootless" not found

```

```
$ minikube config 
config modifies minikube config files using subcommands like "minikube config set driver kvm2"
Configurable fields: 

 * driver
 * vm-driver
 * container-runtime
 * feature-gates
 * v
 * cpus
 * disk-size
 * host-only-cidr\
 * memory
 * log_dir
 * kubernetes-version
 * iso-url
 * WantUpdateNotification
 * WantBetaUpdateNotification
 * ReminderWaitPeriodInHours
 * WantNoneDriverWarning
 * WantVirtualBoxDriverWarning
 * profile
 * bootstrapper
 * insecure-registry
 * hyperv-virtual-switch
 * disable-driver-mounts
 * cache
 * EmbedCerts
 * native-ssh

Available Commands:
  defaults    Lists all valid default values for PROPERTY_NAME
  get         Gets the value of PROPERTY_NAME from the minikube config file
  set         Sets an individual value in a minikube config file
  unset       unsets an individual value in a minikube config file
  view        Display values currently set in the minikube config file
```

### Attach the log file

==> Last Start <==
Log file created at: 2022/06/02 15:00:20
Running on machine: localhost
Binary: Built with gc go1.17.7 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0602 15:00:20.617903 1650048 out.go:297] Setting OutFile to fd 1 ...
I0602 15:00:20.617994 1650048 out.go:349] isatty.IsTerminal(1) = true
I0602 15:00:20.618000 1650048 out.go:310] Setting ErrFile to fd 2...
I0602 15:00:20.618004 1650048 out.go:349] isatty.IsTerminal(2) = true
I0602 15:00:20.618417 1650048 root.go:315] Updating PATH: /home/<USER>/.minikube/bin
I0602 15:00:20.618840 1650048 out.go:304] Setting JSON to false
I0602 15:00:20.638025 1650048 start.go:112] hostinfo: {"hostname":"localhost.localdomain","uptime":106944,"bootTime":1654071476,"procs":396,"os":"linux","platform":"fedora","platformFamily":"fedora","platformVersion":"34","kernelVersion":"5.15.6-100.fc34.x86_64","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"beb132bb-dfc4-4a7f-a147-44653954cb4a"}
I0602 15:00:20.638092 1650048 start.go:122] virtualization: kvm host
I0602 15:00:20.642474 1650048 out.go:176] 😄  minikube v1.25.2 on Fedora 34
I0602 15:00:20.642554 1650048 notify.go:193] Checking for updates...
W0602 15:00:20.642607 1650048 preload.go:295] Failed to list preload files: open /home/<USER>/.minikube/cache/preloaded-tarball: no such file or directory
I0602 15:00:20.642779 1650048 driver.go:344] Setting default libvirt URI to qemu:///system
W0602 15:00:20.655014 1650048 podman.go:136] podman returned error: exit status 1
I0602 15:00:20.660963 1650048 out.go:176] ✨  Using the podman driver based on user configuration
I0602 15:00:20.660993 1650048 start.go:281] selected driver: podman
I0602 15:00:20.661000 1650048 start.go:798] validating driver "podman" against <nil>
I0602 15:00:20.661015 1650048 start.go:809] status for podman: {Installed:true Healthy:false Running:false NeedsImprovement:false Error:"sudo -k -n podman version --format {{.Version}}" exit status 1: sudo: a password is required Reason: Fix:Add your user to the 'sudoers' file: '<USER> ALL=(ALL) NOPASSWD: /usr/bin/podman' Doc:https://podman.io Version:}
I0602 15:00:20.664881 1650048 out.go:176] 
W0602 15:00:20.665011 1650048 out.go:241] 💣  Exiting due to PROVIDER_PODMAN_NOT_RUNNING: "sudo -k -n podman version --format " exit status 1: sudo: a password is required
W0602 15:00:20.665086 1650048 out.go:241] 💡  Suggestion: Add your user to the 'sudoers' file: '<USER> ALL=(ALL) NOPASSWD: /usr/bin/podman'
W0602 15:00:20.665130 1650048 out.go:241] 📘  Documentation: https://podman.io

### Operating System

Redhat/Fedora

### Driver

Podman

**Comment by afbjorklund** [comment]
Fedora 34 is old, please update Podman version.

**Comment by AkihiroSuda** [comment]
Rootless Podman needs minikube 1.26 (https://github.com/kubernetes/minikube/pull/13829)

**Comment by klaases** [comment]
Hi @robshelly, minikube v1.26.0 is now the latest version of minikube and has support for rootless podman.

Please update to the latest version and thank you for sharing your experience.
