### ISSUE TITLE
Error creating new cluster on podman on wsl2 Ubuntu 22.04

### ISSUE THREAD

**Issue by peterzandbergen** [kubernetes/minikube#14271]
### What Happened?

This behavior started after upgrading Ubuntu to from 21.04 to 22.04

I am running Windows 10 with WSL2 with Ubuntu 22.04

Symptoms:
minikube start fails with an error 
😿  Failed to start podman container. 

I tried minikube delete without result

logfile attached.

```
$ podman version
Version:      3.4.4
API Version:  3.4.4
Go Version:   go1.17.3
Built:        Thu Jan  1 01:00:00 1970
OS/Arch:      linux/amd64
```

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```

Operating System
- OS Name	Microsoft Windows 10 Enterprise
- Version	10.0.19044 Build 19044
- WSL2
- Ubuntu 22.04

### Attach the log file

[minikube-logs.txt](https://github.com/kubernetes/minikube/files/8830824/minikube-logs.txt)

### Operating System

Other

### Driver

Podman

**Comment by peterzandbergen** [comment]
Hi, @spowelljr , first thanks for hour reply. 

Following your advice I performed the following actions:

```
minikube delete --all
```

This did not solve the issue. Minikube ended with the same error message.

This is the logfile after performing the following actions:
```
podman system reset
sudo apt remove podman 
sudo apt install podman

minikube start
minikube logs --file=logs.txt
```
[logs.txt](https://github.com/kubernetes/minikube/files/8948600/logs.txt)

**Comment by klaases** [comment]
Hi @peterzandbergen, are you still experiencing this issue? It seems like something ephemeral, perhaps restarting has helped?
