### ISSUE TITLE
Unable to access deployment after running minikube service <service_name> ?

### ISSUE THREAD

**Issue by Leem0sh** [kubernetes/minikube#14288]
### What Happened?

Having trouble with accessing a pod.  Using Windows 10 with docker. 

Made a minimal example with only Deployment, Service & Namespace here: https://github.com/Leem0sh/k8s_simple_api

Prereqs: 
1. `git clone https://github.com/Leem0sh/k8s_simple_api`
2. `cd k8s_simple_api`

Running: 

0. `minikube start`
1. `minikube -p minikube docker-env --shell powershell | Invoke-Expression` # for accessing local docker images? 
2.  `docker build -t simple-api .` creates a docker image
3. `kubectl apply -k k8s` applies kustomization

![image](https://user-images.githubusercontent.com/32645670/172378008-34a69f36-16a8-41bf-894f-14f8b6edc58d.png)

Now I have a running pod which can be accessed from inside the cluster with clusterIP. Only thing that is missing is accessing it from my browser so I use 
4. `minikube service api-deployment-service -n api`
which should open a tunnel and a window in the browser with address (which opens) but I'm not able to access it. 

![image](https://user-images.githubusercontent.com/32645670/172378176-c011d2ad-3a84-4f4a-9cca-9c3ed2d2a356.png)

When using `kubectl proxy` which opens `127.0.0.1:8001` - and accessing `http://127.0.0.1:8001/api/v1/namespaces/api/services/http:api-deployment-service:/proxy/` the response from pod is accessed. What am I doing wrong with the `minikube service ...`? How should I access the pod without using `kubectl proxy`? 

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8853187/log.txt)

### Operating System

Windows

### Driver

Docker

**Comment by klaases** [comment]
Hi @Leem0sh  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support
