### ISSUE TITLE
当我运行minikube service <service_name>时，发生了一个panic

### ISSUE THREAD

**Issue by DomineCore** [kubernetes/minikube#14287]
**重现问题所需的命令**：
`minikube service <service_name>
`
**失败的命令的完整输出**：<details>
`C:\Users\Administrator>minikube service ks-console
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.startKicServiceTunnel({0xc000f1f5a0, 0x1, 0x25680ca}, {0x0, 0x0, 0x256b28d}, {0x256a64c, 0x8}, {0xc000bc7886, 0x6})
        /app/cmd/minikube/cmd/service.go:205 +0x2f1
k8s.io/minikube/cmd/minikube/cmd.glob..func35(0x3c15be0, {0xc000f1f5a0, 0x1, 0x1})
        /app/cmd/minikube/cmd/service.go:143 +0x534
github.com/spf13/cobra.(*Command).execute(0x3c15be0, {0xc000f1f570, 0x1, 0x1})
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0x3c156e0)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:157 +0x9df
main.main()
        /app/cmd/minikube/main.go:86 +0x1f5
`

</details>

**`minikube logs`命令的输出**： <details>

`*
* ==> coredns [1c3b5961aa0a] <==
* [INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"
[WARNING] plugin/kubernetes: starting server with unsynced Kubernetes API
.:53
[INFO] plugin/reload: Running configuration MD5 = c23ed519c17e71ee396ed052e6209e94
CoreDNS-1.8.6
linux/amd64, go1.17.1, 13a9191
[INFO] plugin/ready: Still waiting on: "kubernetes"
[INFO] plugin/ready: Still waiting on: "kubernetes"

*
* ==> describe nodes <==

`
</details>

**使用的操作系统版本**：
Windows10

**Comment by spowelljr** [comment]
Duplicate https://github.com/kubernetes/minikube/issues/13736

Hi @DomineCore, thanks for reporting your issue with minikube.

This is a know issue that has been fixed, but we haven't released since the change was merged. Use the following binary which includes the fix until our next release, thanks!

https://storage.googleapis.com/minikube-builds/13756/minikube-windows-amd64.exe

-----

嗨 @DomineCore，感谢您报告 minikube 的问题。

这是一个已修复的已知问题，但自更改合并后我们尚未发布。使用以下包含修复的二进制文件，直到我们的下一个版本，谢谢！

https://storage.googleapis.com/minikube-builds/13756/minikube-windows-amd64.exe

**Comment by klaases** [comment]
Hi @DomineCore  – were you able to try the fix suggested above?

With the fix, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

---

嗨@DomineCore - 你能尝试上面建议的修复吗？

修复后，这个问题是否仍然存在？是否有其他详细信息？如果是这样，请随时通过使用 `/reopen` 评论重新打开问题。由于无法获得更多信息并且已经过去了一段时间，此问题将被关闭。

可能有帮助的其他信息：

* 问题是否出现在最新的 minikube 版本中

* 使用的确切 minikube 启动命令行

* 附上minikube日志的完整输出，运行`minikube logs --file=logs.txt`创建日志文件

感谢您分享您的经验！
