### ISSUE TITLE
Error running minikube in mac m1

### ISSUE THREAD

**Issue by charboubmustapha** [kubernetes/minikube#14299]
### What Happened?

❌  Exiting due to MK_ADDON_ENABLE: loading profile: cluster "minikube" does not exist

### Attach the log file

Binary: Built with gc go1.17.6 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0607 18:00:04.476924   57003 out.go:297] Setting OutFile to fd 1 ...
I0607 18:00:04.477147   57003 out.go:349] isatty.IsTerminal(1) = true
I0607 18:00:04.477149   57003 out.go:310] Setting ErrFile to fd 2...
I0607 18:00:04.477152   57003 out.go:349] isatty.IsTerminal(2) = true
I0607 18:00:04.477227   57003 root.go:315] Updating PATH: /Users/mcharboub/.minikube/bin
I0607 18:00:04.477757   57003 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0607 18:00:04.477764   57003 addons.go:65] Setting registry=true in profile "minikube"
I0607 18:00:04.477768   57003 addons.go:153] Setting addon registry=true in "minikube"
I0607 18:00:04.477929   57003 host.go:66] Checking if "minikube" exists ...
I0607 18:00:04.478428   57003 cli_runner.go:133] Run: docker container inspect minikube --format={{.State.Status}}
I0607 18:00:04.669580   57003 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}'" minikube
I0607 18:00:04.766172   57003 out.go:176] [31m╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                      [31m│[0m
[31m│[0m    Registry addon with docker driver uses port 51042 please use that instead of default port 5000    [31m│[0m
[31m│[0m                                                                                                      [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0607 18:00:04.785147   57003 out.go:176] 📘  For more information see: https://minikube.sigs.k8s.io/docs/drivers/docker
I0607 18:00:04.806202   57003 out.go:176]     ▪ Using image registry:2.7.1
I0607 18:00:04.825412   57003 out.go:176]     ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
I0607 18:00:04.825572   57003 addons.go:348] installing /etc/kubernetes/addons/registry-rc.yaml
I0607 18:00:04.825593   57003 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-rc.yaml (788 bytes)
I0607 18:00:04.825685   57003 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0607 18:00:04.897244   57003 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:51039 SSHKeyPath:/Users/mcharboub/.minikube/machines/minikube/id_rsa Username:docker}
I0607 18:00:05.006434   57003 addons.go:348] installing /etc/kubernetes/addons/registry-svc.yaml
I0607 18:00:05.006449   57003 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-svc.yaml (398 bytes)
I0607 18:00:05.021030   57003 addons.go:348] installing /etc/kubernetes/addons/registry-proxy.yaml
I0607 18:00:05.021044   57003 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-proxy.yaml (950 bytes)
I0607 18:00:05.034765   57003 ssh_runner.go:195] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.23.3/kubectl apply -f /etc/kubernetes/addons/registry-rc.yaml -f /etc/kubernetes/addons/registry-svc.yaml -f /etc/kubernetes/addons/registry-proxy.yaml
I0607 18:00:05.216633   57003 addons.go:386] Verifying addon registry=true in "minikube"
I0607 18:00:05.253796   57003 out.go:176] 🔎  Verifying registry addon...
I0607 18:00:05.256465   57003 kapi.go:75] Waiting for pod with label "kubernetes.io/minikube-addons=registry" in ns "kube-system" ...
I0607 18:00:05.271211   57003 kapi.go:86] Found 2 Pods for label selector kubernetes.io/minikube-addons=registry
I0607 18:00:05.271217   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:05.777340   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:06.277079   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:06.777261   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:07.279245   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:07.779241   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:08.276709   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:08.779075   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:09.278818   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:09.777669   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:10.276813   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:10.776755   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:11.277542   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:11.777106   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:12.276024   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:12.777289   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:13.278128   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:13.777461   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:14.276361   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:14.776264   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:15.276575   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:15.776627   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:16.278129   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:16.775940   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:17.276875   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:17.777680   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:18.276782   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:18.778400   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:19.280953   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:19.776714   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:20.278145   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:20.816476   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:21.280792   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:21.777223   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:22.276990   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:22.779718   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:23.276461   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:23.776378   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:24.277938   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:24.776527   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:25.276908   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:25.779212   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:26.277471   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:26.777434   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:27.284598   57003 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0607 18:00:27.777301   57003 kapi.go:108] duration metric: took 22.521023584s to wait for kubernetes.io/minikube-addons=registry ...
I0607 18:00:27.777311   57003 addons.go:116] Writing out "minikube" config to set registry=true...
I0607 18:00:27.798407   57003 out.go:176] 🌟  The 'registry' addon is enabled
Log file created at: 2022/06/08 15:27:12
Running on machine: macbook-pro-8
Binary: Built with gc go1.17.6 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0608 15:27:12.424023   24403 out.go:297] Setting OutFile to fd 1 ...
I0608 15:27:12.424522   24403 out.go:349] isatty.IsTerminal(1) = true
I0608 15:27:12.424526   24403 out.go:310] Setting ErrFile to fd 2...
I0608 15:27:12.424529   24403 out.go:349] isatty.IsTerminal(2) = true
I0608 15:27:12.424616   24403 root.go:315] Updating PATH: /Users/mcharboub/.minikube/bin
I0608 15:27:12.425128   24403 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0608 15:27:12.425135   24403 addons.go:65] Setting registry=true in profile "minikube"
I0608 15:27:12.425138   24403 addons.go:153] Setting addon registry=true in "minikube"
I0608 15:27:12.425367   24403 host.go:66] Checking if "minikube" exists ...
I0608 15:27:12.425873   24403 cli_runner.go:133] Run: docker container inspect minikube --format={{.State.Status}}
I0608 15:27:12.596629   24403 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}'" minikube
I0608 15:27:12.696357   24403 out.go:176] [31m╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                      [31m│[0m
[31m│[0m    Registry addon with docker driver uses port 57111 please use that instead of default port 5000    [31m│[0m
[31m│[0m                                                                                                      [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0608 15:27:12.714593   24403 out.go:176] 📘  For more information see: https://minikube.sigs.k8s.io/docs/drivers/docker
I0608 15:27:12.748985   24403 out.go:176]     ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
I0608 15:27:12.768039   24403 out.go:176]     ▪ Using image registry:2.7.1
I0608 15:27:12.768171   24403 addons.go:348] installing /etc/kubernetes/addons/registry-rc.yaml
I0608 15:27:12.768185   24403 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-rc.yaml (788 bytes)
I0608 15:27:12.768301   24403 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0608 15:27:12.852791   24403 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:57108 SSHKeyPath:/Users/mcharboub/.minikube/machines/minikube/id_rsa Username:docker}
I0608 15:27:12.959226   24403 addons.go:348] installing /etc/kubernetes/addons/registry-svc.yaml
I0608 15:27:12.959235   24403 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-svc.yaml (398 bytes)
I0608 15:27:12.972582   24403 addons.go:348] installing /etc/kubernetes/addons/registry-proxy.yaml
I0608 15:27:12.972588   24403 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-proxy.yaml (950 bytes)
I0608 15:27:12.986852   24403 ssh_runner.go:195] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.23.3/kubectl apply -f /etc/kubernetes/addons/registry-rc.yaml -f /etc/kubernetes/addons/registry-svc.yaml -f /etc/kubernetes/addons/registry-proxy.yaml
I0608 15:27:13.219510   24403 addons.go:386] Verifying addon registry=true in "minikube"
I0608 15:27:13.254018   24403 out.go:176] 🔎  Verifying registry addon...
I0608 15:27:13.256991   24403 kapi.go:75] Waiting for pod with label "kubernetes.io/minikube-addons=registry" in ns "kube-system" ...
I0608 15:27:13.271403   24403 kapi.go:86] Found 2 Pods for label selector kubernetes.io/minikube-addons=registry
I0608 15:27:13.271410   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:13.783228   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:14.277001   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:14.777212   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:15.277498   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:15.786808   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:16.279485   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:16.777490   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:17.277363   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:17.777192   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:18.278496   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:18.788878   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:19.331144   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:19.777188   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:20.285028   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:20.778743   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:21.277956   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:21.836320   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:22.312716   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:22.810735   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:23.313793   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:23.810005   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:24.278161   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:24.777711   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:25.320030   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:25.814089   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:26.283881   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:26.791306   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:27.279723   24403 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:27:27.777705   24403 kapi.go:108] duration metric: took 14.520689833s to wait for kubernetes.io/minikube-addons=registry ...
I0608 15:27:27.777715   24403 addons.go:116] Writing out "minikube" config to set registry=true...
I0608 15:27:27.797427   24403 out.go:176] 🌟  The 'registry' addon is enabled
Log file created at: 2022/06/08 15:52:20
Running on machine: macbook-pro-8
Binary: Built with gc go1.17.6 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0608 15:52:20.608914   28662 out.go:297] Setting OutFile to fd 1 ...
I0608 15:52:20.609207   28662 out.go:349] isatty.IsTerminal(1) = true
I0608 15:52:20.609209   28662 out.go:310] Setting ErrFile to fd 2...
I0608 15:52:20.609212   28662 out.go:349] isatty.IsTerminal(2) = true
I0608 15:52:20.609312   28662 root.go:315] Updating PATH: /Users/mcharboub/.minikube/bin
I0608 15:52:20.609841   28662 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0608 15:52:20.609850   28662 addons.go:65] Setting registry=true in profile "minikube"
I0608 15:52:20.609856   28662 addons.go:153] Setting addon registry=true in "minikube"
I0608 15:52:20.610054   28662 host.go:66] Checking if "minikube" exists ...
I0608 15:52:20.610539   28662 cli_runner.go:133] Run: docker container inspect minikube --format={{.State.Status}}
I0608 15:52:20.793489   28662 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "5000/tcp") 0).HostPort}}'" minikube
I0608 15:52:20.883798   28662 out.go:176] [31m╭──────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                      [31m│[0m
[31m│[0m    Registry addon with docker driver uses port 58310 please use that instead of default port 5000    [31m│[0m
[31m│[0m                                                                                                      [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0608 15:52:20.902004   28662 out.go:176] 📘  For more information see: https://minikube.sigs.k8s.io/docs/drivers/docker
I0608 15:52:20.920369   28662 out.go:176]     ▪ Using image registry:2.7.1
I0608 15:52:20.939468   28662 out.go:176]     ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
I0608 15:52:20.939665   28662 addons.go:348] installing /etc/kubernetes/addons/registry-rc.yaml
I0608 15:52:20.939680   28662 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-rc.yaml (788 bytes)
I0608 15:52:20.939781   28662 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0608 15:52:21.016607   28662 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:58307 SSHKeyPath:/Users/mcharboub/.minikube/machines/minikube/id_rsa Username:docker}
I0608 15:52:21.117935   28662 addons.go:348] installing /etc/kubernetes/addons/registry-svc.yaml
I0608 15:52:21.117944   28662 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-svc.yaml (398 bytes)
I0608 15:52:21.137724   28662 addons.go:348] installing /etc/kubernetes/addons/registry-proxy.yaml
I0608 15:52:21.137731   28662 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/registry-proxy.yaml (950 bytes)
I0608 15:52:21.152106   28662 ssh_runner.go:195] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.23.3/kubectl apply -f /etc/kubernetes/addons/registry-rc.yaml -f /etc/kubernetes/addons/registry-svc.yaml -f /etc/kubernetes/addons/registry-proxy.yaml
I0608 15:52:21.373092   28662 addons.go:386] Verifying addon registry=true in "minikube"
I0608 15:52:21.407979   28662 out.go:176] 🔎  Verifying registry addon...
I0608 15:52:21.411304   28662 kapi.go:75] Waiting for pod with label "kubernetes.io/minikube-addons=registry" in ns "kube-system" ...
I0608 15:52:21.430162   28662 kapi.go:86] Found 2 Pods for label selector kubernetes.io/minikube-addons=registry
I0608 15:52:21.430169   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:21.937315   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:22.437591   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:22.935998   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:23.449116   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:23.935671   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:24.437035   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:24.938889   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:25.435756   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:25.935995   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:26.443619   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:26.935936   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:27.436079   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:27.935201   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:28.434954   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:28.935766   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:29.439570   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:29.944454   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:30.437918   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:30.940144   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:31.436132   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:31.935452   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:32.468449   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:32.968532   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:33.469216   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:33.968463   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:34.471594   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:34.966765   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:35.458965   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:35.935999   28662 kapi.go:96] waiting for pod "kubernetes.io/minikube-addons=registry", current state: Pending: [<nil>]
I0608 15:52:36.436061   28662 kapi.go:108] duration metric: took 15.024863125s to wait for kubernetes.io/minikube-addons=registry ...
I0608 15:52:36.436071   28662 addons.go:116] Writing out "minikube" config to set registry=true...
I0608 15:52:36.456326   28662 out.go:176] 🌟  The 'registry' addon is enabled
Log file created at: 2022/06/08 17:32:21
Running on machine: macbook-pro-8
Binary: Built with gc go1.17.6 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0608 17:32:21.379063   41051 out.go:297] Setting OutFile to fd 1 ...
I0608 17:32:21.379392   41051 out.go:349] isatty.IsTerminal(1) = true
I0608 17:32:21.379394   41051 out.go:310] Setting ErrFile to fd 2...
I0608 17:32:21.379397   41051 out.go:349] isatty.IsTerminal(2) = true
I0608 17:32:21.379496   41051 root.go:315] Updating PATH: /Users/mcharboub/.minikube/bin
I0608 17:32:21.397629   41051 out.go:176] 
W0608 17:32:21.397713   41051 out.go:241] ❌  Exiting due to MK_ADDON_ENABLE: loading profile: cluster "minikube" does not exist
W0608 17:32:21.397718   41051 out.go:241] 
W0608 17:32:21.399439   41051 out.go:241] [31m╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                                         [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                                                           [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                         [31m│[0m
[31m│[0m                                                                                                                         [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                  [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                                                           [31m│[0m
[31m│[0m    - /var/folders/pr/23c_r5zx6393qqqvmzb5cccw0000gn/T/minikube_addons_8d0ed66ce74d8eab479977df2a809d671500a844_0.log    [31m│[0m
[31m│[0m                                                                                                                         [31m│[0m
[31m╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @charboubmustapha, thanks for reporting your issue with minikube.

It looks like you cluster got deleted, try running `minikube start` and then try enabling the addons again.

**Comment by klaases** [comment]
Hi @charboubmustapha – were you able to try running `minikube start` and then try enabling addons again as suggested above?

Also, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
