### ISSUE TITLE
The connection to the server localhost:8080 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by mesutbunaldi** [kubernetes/minikube#14293]
### What Happened?

When i start minikube , i used default name space of minikube , then i changed my KUBECONFIG and i used my another remote cluster. I did not need minikube anymore and i deleted the minikube. But with minikube delete command is  deleted my available KUBECONFIG and i could not access my remote cluster with kubectl. whereas i need delete only minikube config. How can i solve this problem ?

### Attach the log file

The connection to the server localhost:8080 was refused - did you specify the right host or port?

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @mesutbunaldi, thanks for reporting your issue with minikube.

Could you provide a before and after example of your kubeconfig to help me understand exactly what's getting deleted, thanks!

**Comment by mesutbunaldi** [comment]
Hi @spowelljr , thanks for interest.

First of all, i am sorry for my expression : `with minikube delete command is deleted my available KUBECONFIG ` . Instead of the expression before i said, i can say that ; `minikube delete command makes inaccessible my other clusters`

Actually , i am using kubeconfig file more than one and i am picking one with export KUBECONFIG=~/.kube/myconfig . And i am working on my remote or local cluster. For example;  
![image](https://user-images.githubusercontent.com/37230896/173157088-3b8fdb09-d35f-4242-9777-974f5ed3ef4f.png)
![image](https://user-images.githubusercontent.com/37230896/173158379-b0e8bc21-bdfe-4a8d-a1db-a26baf32efad.png)


Actually did not change anything my kubeconfig files. Could it be minikube delete command is deleting something extra? Because my export KUBECONFIG=~/.kube/myconfig command does not work after the minikube delete command. Thanks

**Comment by spowelljr** [comment]
Thanks for the clarification @mesutbunaldi!

What I think is happening is that `kubectl` is still pointing to `minikube`, hence the error you're seeing.

If you look at your first run of `kubectlx` you can see that `kubernetes-admin@clustetr.local` is yellow, indicating it's active.

Then if you look at the second run you see that `minikube` is yellow.

But on the final run see how `kubernetes-admin@clustetr.local` is not yellow, I believe it's still pointing to `minikube`.

If you run `kubectl config set-context kubernetes-admin@cluster.local` and then running the command does that resolve it?

**Comment by mesutbunaldi** [comment]
Hi again @spowelljr ,

`kubectl config set-context kubernetes-admin@cluster.local` or `kubectx kubernetes-admin@clustetr.local` is resolved my problem. But why i need to do this? Already i am using `export KUBECONFIG=~/.kube/myconfig` command and i changed my KUBECONFIG. if `minikube` deleted `kubectl` must not point to `minikube` . Am i wrong ? 

Also my last initial kubeconfig  before minikube is does not work after the `minikube delete` command. For example;

![image](https://user-images.githubusercontent.com/37230896/173183641-4f4d0c92-44ed-4b86-a959-eaff914707d6.png)

Note : 

- `kubeconfig_remotedevboxes` is my latest kubeconfig before `minikube`
- `kubeconfig_testboxes` is a different kubeconfig
