### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by nahomdebretsion** [kubernetes/minikube#14297]
### What Happened?

X Exiting due to K8S_INSTALL_FAILED: updating control plane: copy: copy: sudo test -d /var/tmp/minikube && sudo scp -t /var/tmp/minikube: Process exited with status 1
output: �☺scp: /var/tmp/minikube/kubeadm.yaml.new: Read-only file system
☺scp: protocol error: expected control record

### Attach the log file

minikube logs --file=logs.txt

### Operating System

Windows

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Duplicate of https://github.com/kubernetes/minikube/issues/14298
