### ISSUE TITLE
ingress-dns addon returning 0 results and NOERROR

### ISSUE THREAD

**Issue by hoppla20** [kubernetes/minikube#14309]
### What Happened?

Shouldn't the normal behavior of a DNS server to return the status NXDOMAIN if the domain could not be resolved? My current problem is, that I have a DNS entry `static.local.example.com` on Cloudflare, which points to a remote server, but when I use ingress-dns with the domain `local.example.com`, the ingress-dns server returns 0 results with the status NOERROR. The NOERROR status means that the local DNS resolver stops and doesn't try to resolve the domain with other configured DNS servers (for example in a split dns setup).
For me this is a problem, because my host (I use the docker driver) and the containers started in minikube can't resolve `static.local.example.com`.

These are the logs from a container:
```
root@debug:~# nslookup static.local.example.com
Server:		10.96.0.10
Address:	10.96.0.10#53

Non-authoritative answer:
*** Can't find static.local.example.com: No answer

root@debug:~# dig static.local.example.com

; <<>> DiG 9.11.3-1ubuntu1.15-Ubuntu <<>> static.local.example.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 5032
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
; COOKIE: d14b37cd62deec72 (echoed)
;; QUESTION SECTION:
;static.local.example.com.	IN	A

;; Query time: 5 msec
;; SERVER: 10.96.0.10#53(10.96.0.10)
;; WHEN: Thu Jun 09 12:47:14 UTC 2022
;; MSG SIZE  rcvd: 69
```

Is this the intended behavior?

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8870432/logs.txt)

### Operating System

Other

### Driver

Docker

**Comment by klaases** [comment]
> For me this is a problem, because my host (I use the docker driver) and the containers started in minikube can't resolve `static.local.example.com`.

Hi – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support
