### ISSUE TITLE
minikube service <service-name> --url panics

### ISSUE THREAD

**Issue by Only-a-User** [kubernetes/minikube#14307]
### What Happened?

When trying to get the url of a ClusterIP service with

`minikube service <service-name> --url`

I get the following output:

> 😿  service default/SERVICE_NAME has no node port
 panic: runtime error: index out of range [3] with length 3
>
> goroutine 1 [running]:
 k8s.io/minikube/cmd/minikube/cmd.glob..func35(0x1073a1800, {0x140000a7400, 0x1, 0x2})
	/private/tmp/minikube-20220224-22619-1l4wp0k/cmd/minikube/cmd/service.go:138 +0x6a8
github.com/spf13/cobra.(*Command).execute(0x1073a1800, {0x140000a73e0, 0x2, 0x2})
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:860 +0x640
github.com/spf13/cobra.(*Command).ExecuteC(0x1073a1300)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:974 +0x410
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.3.0/command.go:902
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/private/tmp/minikube-20220224-22619-1l4wp0k/cmd/minikube/cmd/root.go:157 +0xdb8
main.main()
	/private/tmp/minikube-20220224-22619-1l4wp0k/cmd/minikube/main.go:86 +0x2a0

I already tried the solve described [here](https://github.com/kubernetes/minikube/issues/13736#issuecomment-1063470210) with the binary for darwin-arm64 as I'm on a apple silicon, but the result remained the same.

### Attach the log file

...

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @Only-a-User, thanks for reporting your issue with minikube.

I also noticed this recently, I'm going to look into this.

**Comment by Only-a-User** [comment]
The result is:

```
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
```

**Comment by spowelljr** [comment]
`362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7` doesn't have https://github.com/kubernetes/minikube/pull/13756 in it.

Make sure you're using https://storage.googleapis.com/minikube-builds/13756/minikube-linux-arm64

**Comment by Only-a-User** [comment]
As I am on mac the linux binary doesn't work, so i tried with the darwin one (https://storage.googleapis.com/minikube-builds/13756/minikube-darwin-arm64). Problem is it doesn't do anything. The commit doesn't change and the result is still the same.

**Comment by spowelljr** [comment]
I just tried downloading that binary and I'm getting `9d8634cd018dc9ed32c83f86917b202e5450409b` when I do a version check. It sounds like you're still using the existing binary, did you install the binary to `/usr/local/bin/minikube`?

**Comment by Only-a-User** [comment]
that dir doesn't exist, because i installed with brew.

**Comment by spowelljr** [comment]
If you want to use `brew` you'll have to wait for the next release, otherwise you'll have to uninstall the brew version and manually install the version linked.

**Comment by Only-a-User** [comment]
ok thanks for your help
