### ISSUE TITLE
Please add `zfsutils-linux` to the gcr.io/k8s-minikube/kicbase container image

### ISSUE THREAD

**Issue by dhs-rec** [kubernetes/minikube#14314]
### What Happened?

Since my playground system is running purely on ZFS, I wanted to setup a ZFS storage provider after starting a minikube cluster, but didn't get it to work. I finally found out that the storage provider needs the "zfs" commands on the host (which in this case is the minikube container).

However, it started working as soon as I installed the `zfsutils-linux` package into the running minikube container.
So my request is to add that package to the image.

### Attach the log file

```
% kubectl logs -f openebs-zfs-node-5wvj7 -n kube-system -c openebs-zfs-plugin
E0610 09:58:17.676074       1 zfs_util.go:424] zfs: could not create volume data/kubernetes/pvc-c0bb83d0-c3f9-411d-b4d2-51faf147d2a2 cmd [create -o quota=4294967296 -o recordsize=4k -o dedup=off -o compression=off -o mountpoint=legacy data/kubernetes/pvc-c0bb83d0-c3f9-411d-b4d2-51faf147d2a2] error: chroot: failed to run command 'zfs': No such file or directory
````

### Operating System

Ubuntu

### Driver

Docker

**Comment by klaases** [comment]
> However, it started working as soon as I installed the `zfsutils-linux` package into the running minikube container.
> So my request is to add that package to the image.

Hi @dhs-rec, would you be open to creating a PR for the above?
