### ISSUE TITLE
Got permission denied while trying to connect to the Docker daemon socket

### ISSUE THREAD

**Issue by Mohammad-Ali-Rauf** [kubernetes/minikube#14313]
### What Happened?

Exiting due to PROVIDER_DOCKER_NEWGRP: "docker version --format -" exit status 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied
💡  Suggestion: Add your user to the 'docker' group: 'sudo usermod -aG docker $USER && newgrp docker'
📘  Documentation: https://docs.docker.com/engine/install/linux-postinstall

### Attach the log file

Profile "minikube" not found. Run "minikube profile list" to view all profiles.
👉  To start a cluster, run: "minikube start"

### Operating System

Ubuntu

**Comment by spowelljr** [comment]
Hi @Mohammad-Ali-Rauf, thanks for reporting your issue with minikube.

It seems you just need to run the Docker post-installation steps the error message indicates.

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by klaases** [comment]
Hi @Mohammad-Ali-Rauf – did you have a chance to run the Docker post-installation steps?

Also, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by Surya-Gs** [comment]
It seems like you're encountering a permission issue while trying to connect to the Docker daemon socket when starting Minikube. Here's how you can troubleshoot and resolve this issue:

Check Docker Installation: Ensure that Docker is installed correctly on your system and running without any issues.
Verify Docker Permissions: Make sure that the user you're using to run Minikube has the necessary permissions to access the Docker daemon socket. Typically, this involves being a member of the docker group.You can add your user to the docker group with the following command:

try following steps:

**sudo usermod -aG docker your_username**
Replace your_username with your actual username.


Restart Docker Service: After adding your user to the docker group, restart the Docker service to apply the changes

**sudo service docker restart**


check the permission 


**ls -l /var/run/docker.sock**


Add the minikube to the user

**sudo usermod -aG docker $USER && newgrp docker**
