### ISSUE TITLE
Cannot set "rootless" option for podman driver

### ISSUE THREAD

**Issue by dan-m8t** [kubernetes/minikube#14311]
Hi there,

the documentation states to set
 `minikube config set rootless true`
for running minikube with podman in rootless mode.

I get this error when I try to set the setting:

`Exiting due to MK_CONFIG_SET: find settings for "rootless" value of "true": property name "rootless" not found`

Versions running:
`minikube version            
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7-dirty`

`podman version
Client:       Podman Engine
Version:      4.1.0
API Version:  4.1.0
Go Version:   go1.18.1
Git Commit:   e4b03902052294d4f342a185bb54702ed5bed8b1
Built:        Fri May  6 20:18:30 2022
OS/Arch:      linux/amd64`

Thanks

Dan

**Comment by AkihiroSuda** [comment]
You need minikube 1.26

**Comment by dan-m8t** [comment]
Thanks, 1.26 is beta but I will try it out.
This should be clarified in the documentation, there's no hint about the supported version for rootless podman.
