### ISSUE TITLE
minikube issue

### ISSUE THREAD

**Issue by vipinfidy** [kubernetes/minikube#14322]
### What Happened?

error execution phase certs/apiserver: failed to write or validate certificate "apiserver": failure loading apiserver certificate: couldn't load the certificate file /var/lib/minikube/certs/apiserver.crt: error reading /var/lib/minikube/certs/apiserver.crt: x509: cannot parse IP address of length 0
To see the stack trace of this error execute with --v=5 or higher

### Attach the log file

error execution phase certs/apiserver: failed to write or validate certificate "apiserver": failure loading apiserver certificate: couldn't load the certificate file /var/lib/minikube/certs/apiserver.crt: error reading /var/lib/minikube/certs/apiserver.crt: x509: cannot parse IP address of length 0
To see the stack trace of this error execute with --v=5 or higher

**Comment by vishalswami-ust** [comment]
> Thank you for sharing your experience!
> 
> Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.
> 
> This will help us isolate the problem further, thank you!

I am sharing log file.[
[Uploading logs.txt…]()
]
