### ISSUE TITLE
Issue in starting Kubernetes Cluster using Minikube

### ISSUE THREAD

**Issue by dabasank** [kubernetes/minikube#14339]
### What Happened?

Issue in starting Kubernetes Cluster using Minikube, giving certificates error and also when trying to start kubelet, it is giving error.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8899608/logs.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by spowelljr** [comment]
Hi @dabasank, thanks for reporting your issue with minikube.

It looks like pods from the existing minikube instance are not running.

To get back into a clean slate run `minikube delete --all` then try starting minikube and let me know what the outcome is, thanks

**Comment by dabasank** [comment]
> Hi @dabasank, thanks for reporting your issue with minikube.
> 
> It looks like pods from the existing minikube instance are not running.
> 
> To get back into a clean slate run `minikube delete --all` then try starting minikube and let me know what the outcome is, thanks

Thanks @spowelljr  - it worked.
