### ISSUE TITLE
Docker Driver Start: "Error getting ip during provisioning: IPs output should only be one line, got 2 lines"

### ISSUE THREAD

**Issue by mechaHarry** [kubernetes/minikube#14340]
### What Happened?

Found minikube in an error state after noticing cronjobs were not running.
Ran minikube start to restart the cluster, and encountered the following log output.

### Attach the log file

~$ minikube start --driver=docker --kubernetes-version=v1.23.3
😄  minikube v1.25.2 on Ubuntu 18.04 (amd64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.23.3 preload ...
    > preloaded-images-k8s-v17-v1...: 505.68 MiB / 505.68 MiB  100.00% 44.24 Mi
🏃  Updating the running docker "minikube" container ...
🤦  StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
🏃  Updating the running docker "minikube" container ...
😿  Failed to start docker container. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Ubuntu

### Driver

Docker

**Comment by klaases** [comment]
Thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by mechaHarry** [comment]
```
user@machine:~$ minikube logs --file=logs.txt
E0628 18:12:30.714322 2558251 logs.go:192] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.23.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.23.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: /var/lib/minikube/binaries/v1.23.3/kubectl: command not found
 output: "\n** stderr ** \nsudo: /var/lib/minikube/binaries/v1.23.3/kubectl: command not found\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes
user@machine:~$ which kubectl
/usr/local/bin/kubectl
user@machine:~$ kubectl --help
kubectl controls the Kubernetes cluster manager.

 Find more information at: https://kubernetes.io/docs/reference/kubectl/overview/

**Comment by medyagh** [comment]
@mechaHarry does this help ?

chmod 777 ~/.docker
chmod 66 ~/.docker/config.json


https://github.com/kubernetes/minikube/issues/8409#issuecomment-907269490

**Comment by medyagh** [comment]
if it is confirmed that this can be fixed by 
```
chmod 777 ~/.docker
chmod 66 ~/.docker/config.json
```

we need to add solution message to minikube

**Comment by klaases** [comment]
Hi @mechaHarry, were you able to find an alternate way to resolve the permission issue?

**Comment by mechaHarry** [comment]
@klaases Unfortunately not, just ended up using another software solution for short term kubeing.
The alts I found easiest to set up are:
https://www.rancher.com/products/k3s
https://kind.sigs.k8s.io/
https://kops.sigs.k8s.io/#can-i-see-it-in-action
