### ISSUE TITLE
minikube fails on Windows 11 and PopOS! dualboot

### ISSUE THREAD

**Issue by otisscott** [kubernetes/minikube#14348]
My team is currently trying to move from a single Django Rest Framework monolith to a hybrid monolith and micro service approach, but I cannot even get a local instance to spin up even without our jank source code. I am attaching my logs.txt to this issue as a prayer that someone can help. Thank you so much and thank goodness for amazing open source resources.
[logs.txt](https://github.com/kubernetes/minikube/files/8924922/logs.txt)
.

**Comment by RA489** [comment]
@otisscott I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by otisscott** [comment]
> @otisscott I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:
> 
> * The exact minikube start command line used
> 
> * The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.
> 
> * The full output of minikube logs
> 
> * The full output of kubectl get po -A
> 
> Thank you for sharing your experience!
> 
> 

I fixed it, rhe documentation with docket desktop and Kube sucks. But to fix this Uninstaller docket desktop

**Comment by klaases** [comment]
Hi @otisscott, thank you for sharing your experience. Closing this out for now per your fix above.
