### ISSUE TITLE
Access a service from a remote browser

### ISSUE THREAD

**Issue by TamarNR** [kubernetes/minikube#14346]
### What Happened?

I am trying to figure out how to access services from a remote browser - but with no success.
Both Linux (minikube) and laptop (browser) are connected to the same internal (company) network.

I tried to use instructions as described here:
https://kubernetes.io/docs/tutorials/hello-minikube/#create-your-node-js-application
and then here:
https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access

But both do not seem to work.

My minikube is running on Linux debian:
```
$ minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
```

This is what I tried:
**First method:**
```
deploy@octopus:~/k8s-config/new$ kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4
deployment.apps/hello-node created

deploy@octopus:~/k8s-config/new$ kubectl get deployments
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
hello-node         0/1     1            0           6s

deploy@octopus:~/k8s-config/new$ kubectl get pods
NAME                               READY   STATUS    RESTARTS   AGE
hello-node-6b89d599b9-wz22t        1/1     Running   0          13s

deploy@octopus:~/k8s-config/new$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/deploy/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Jun 2022 12:32:58 IDT
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Thu, 16 Jun 2022 12:32:58 IDT
        provider: minikube.sigs.k8s.io
        version: v1.25.2
      name: context_info
    namespace: default
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/deploy/.minikube/profiles/minikube/client.crt
    client-key: /home/deploy/.minikube/profiles/minikube/client.key

deploy@octopus:~/k8s-config/new$ kubectl expose deployment hello-node --type=LoadBalancer --port=8080
service/hello-node exposed

deploy@octopus:~/k8s-config/new$ kubectl get services
NAME         TYPE           CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
hello-node   LoadBalancer   10.105.163.240   <pending>     8080:30927/TCP   14s
kubernetes   ClusterIP      10.96.0.1        <none>        443/TCP          174m

deploy@octopus:~/k8s-config/new$ minikube service hello-node

deploy@octopus:~/k8s-config/new$ minikube service --all
* service default/kubernetes has no node port
|-----------|------------|--------------|---------------------------|
| NAMESPACE |    NAME    | TARGET PORT  |            URL            |
|-----------|------------|--------------|---------------------------|
| default   | hello-node |         8080 | http://192.168.49.2:30927 |
| default   | kubernetes | No node port |
|-----------|------------|--------------|---------------------------|
```
Then I try to access http://192.168.49.2:30927  from my laptop browser , but it fails.

**Second method (with minikube tunnel):**
From one terminal:
```
~$ minikube tunnel
Status:
        machine: minikube
        pid: 11837
        route: 10.96.0.0/12 -> 192.168.49.2
        minikube: Running
        services: [hello-node]
    errors:
                minikube: no errors
                router: no errors
                loadbalancer emulator: no errors
```
From  another terminal:
```
deploy@octopus:~$ kubectl create deployment hello-minikube1 --image=k8s.gcr.io/echoserver:1.4
deployment.apps/hello-minikube1 created

deploy@octopus:~$ kubectl expose deployment hello-minikube1 --type=LoadBalancer --port=8080
service/hello-minikube1 exposed

deploy@octopus:~$ kubectl get svc
NAME              TYPE           CLUSTER-IP     EXTERNAL-IP    PORT(S)          AGE
hello-minikube1   LoadBalancer   10.101.28.15   10.101.28.15   8080:31220/TCP   8s
kubernetes        ClusterIP      10.96.0.1      <none>         443/TCP          3h

```

Try to access the external ip displayed above from my laptop browser, but it fails:
http://10.101.28.15:8080

How can I achieve this then?

Thanks

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8918292/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by Yensan** [comment]
😭 I am a newbie just like you. K8S is painful to learn...
you, and your cluster is OK. But, K8S is a complex project, it's network very different from our home&school&company in usual. 
Do you know OpenStack ? They are about the same in complex in network....
If you can use `kubectl` to interact with you cluster, `kubectl port-forward services/hello-minikube 8080:8080 -n default`, then, you can open it in your browser.
However, I must say, use vscode, get `ms-kubernetes-tools.vscode-kubernetes-tools` & `mindaro.mindaro` extension, and follow the doc, You Will Save Your Life 😆

**Comment by yuri-potatoq** [comment]
@Yensan thank your so much, a had the same issue and the forward did solve it. 
But my service has a NodePort type. And i cant understand why i cant do that like described at [doc](https://minikube.sigs.k8s.io/docs/handbook/accessing/#example-of-nodeport).

**Comment by TamarNR** [comment]
Hi @Yensan,

Thank you for the reply - but still don't get it..

So I used this from the begining:
```
$ kubectl create deployment hello-node --image=k8s.gcr.io/echoserver:1.4
deployment.apps/hello-node created

$ kubectl get deployments
NAME               READY   UP-TO-DATE   AVAILABLE   AGE
hello-node         1/1     1            1           8s

$ kubectl get pods
NAME                               READY   STATUS    RESTARTS      AGE
hello-node-6b89d599b9-7lj8b        1/1     Running   0             19s

$ kubectl expose deployment hello-node --type=LoadBalancer --port=8080
service/hello-node exposed

$ kubectl get services
NAME              TYPE           CLUSTER-IP       EXTERNAL-IP    PORT(S)          AGE
hello-node        LoadBalancer   10.103.235.192   <pending>      8080:30875/TCP   14s
kubernetes        ClusterIP      10.96.0.1        <none>         443/TCP          3d23h

$ minikube service hello-node

$  minikube service --all
* service default/kubernetes has no node port
|-----------|-----------------|--------------|---------------------------|
| NAMESPACE |      NAME       | TARGET PORT  |            URL            |
|-----------|-----------------|--------------|---------------------------|
| default   | hello-node      |         8080 | http://192.168.49.2:30875 |
| default   | kubernetes      | No node port |
|-----------|-----------------|--------------|---------------------------|

$ kubectl port-forward services/hello-node 8080:8080 -n default
Forwarding from 127.0.0.1:8080 -> 8080
Forwarding from [::1]:8080 -> 8080

```
What should I use in my browser? - as all of the below do not work:

http://192.168.49.2:30875
http://192.168.49.2:8080/
http://localhost:8080/
http://127.0.0.1:8080
http://10.103.19.196:8080  #My server external ip

Thanks,
Tamar

**Comment by Yensan** [comment]
if `kubectl port-forward services/hello-node 8080:8080 -n default` have not echoed ERROR,
the url will be as it said,  http://127.0.0.1:8080

**Comment by Yensan** [comment]
believe me, use GUI save yourself, command line is not for big project. Does shell script make you happier ? 🤣

**Comment by TamarNR** [comment]
Hi @Yensan,

So the web page shows me this:

> This site can’t be reached127.0.0.1 refused to connect.
> Try:
> 
> Checking the connection
> [Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
> ERR_CONNECTION_REFUSED
> ### ### ### 

![image](https://user-images.githubusercontent.com/67385218/174566170-2eeaabbb-ab61-423b-941e-a420ad4542db.png)

 

But I really fail to understand why is this so complicated... 
We are using docker containers to deploy our application for some time (we have a container for the forntend, and a container for the backend), and mapping an external port to the internal container port is straight forward.
Is it not obvious that most application will be running on a linux machine, but accesssed form the end-user browser?
Seems to me strange that tnere is no striaght forward easy way to achieve this.

Thanks,
Tamar

**Comment by zhan9san** [comment]
Hi,

Sorry to make you confused.

Almost all the docs are mainly for local use, including the [hello-minikube](https://kubernetes.io/docs/tutorials/hello-minikube/) and [accessing apps doc](https://minikube.sigs.k8s.io/docs/handbook/accessing/)


If you just want to access the application, do the following commands address your issue?

1. Create a deployment

  ```shell
  $ kubectl create deployment hello-minikube1 --image=k8s.gcr.io/echoserver:1.4
  ```

2. Forward one or more local ports to a pod(no need to create NodePort or LoadBalancer service)

```shell
kubectl port-forward --address localhost,<YOUR_Linux_Server_IP> deployment/hello-minikube1 8080
```

3. Access application remotely

```shell
$ curl <YOUR_Linux_Server_IP>:8080
CLIENT VALUES:
client_address=127.0.0.1
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://<YOUR_Linux_Server_IP>:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=*/*
host=<YOUR_Linux_Server_IP>:8080
user-agent=curl/7.79.1
BODY:
-no body in request-
```

**Comment by TamarNR** [comment]
Thank you @zhan9san !!

I have been struggling with this for some time, and could not find any documentation for it.

I also used it for my frontend deployment and it works.

**Comment by Yensan** [comment]
@zhan9san 
K8S & minikube document... it is not friendly for human... 🤣 
OR, manage a cluster never an easy thing, k8s just only bring the difficulty to everyone.  When I use k8s, I finally realise it is very different from home-net and business-server-net, and my two poor pc is different from a big cluster.
To achieve the net-config as I said above, I search over the world, and learn everything.  Exhausted.

**Comment by zhan9san** [comment]
Thanks for sharing your experience. Minikube help us set up a local Kubernetes cluster quickly.

We have to add another Docs to make it easy to use. I'll try it later.

Related to #14364

**Comment by emoxam** [comment]
> Hi,
> 
> Sorry to make you confused.
> 
> Almost all the docs are mainly for local use, including the [hello-minikube](https://kubernetes.io/docs/tutorials/hello-minikube/) and [accessing apps doc](https://minikube.sigs.k8s.io/docs/handbook/accessing/)
> 
> If you just want to access the application, do the following commands address your issue?
> 
> 1. Create a deployment
> 
> ```shell
> $ kubectl create deployment hello-minikube1 --image=k8s.gcr.io/echoserver:1.4
> ```
> 
> 2. Forward one or more local ports to a pod(no need to create NodePort or LoadBalancer service)
> 
> ```shell
> kubectl port-forward --address localhost,<YOUR_Linux_Server_IP> deployment/hello-minikube1 8080
> ```
> 
> 3. Access application remotely
> 
> ```shell
> $ curl <YOUR_Linux_Server_IP>:8080
> CLIENT VALUES:
> client_address=127.0.0.1
> command=GET
> real path=/
> query=nil
> request_version=1.1
> request_uri=http://<YOUR_Linux_Server_IP>:8080/
> 
> SERVER VALUES:
> server_version=nginx: 1.10.0 - lua: 10001
> 
> HEADERS RECEIVED:
> accept=*/*
> host=<YOUR_Linux_Server_IP>:8080
> user-agent=curl/7.79.1
> BODY:
> -no body in request-
> ```
And how to use ingress with minikube? I don't want to port-forward only application, i want to application be available via the ingress. Thanks.
