### ISSUE TITLE
Question : Retaining the data in PVC with dynamic storage provisioning 

### ISSUE THREAD

**Issue by goldytech** [kubernetes/minikube#14356]
### What Happened?

Hi
I'm using the dynamic storage provisioning (HostPath) using the default `standard` storage class. I lose the data when my minikube cluster gets started after being stopped. Is there any way to make the data getting persist over the restarts? I was unable to change the 'reclaimPolicy` value of the default 'standard` storage class.

### Attach the log file

None

### Operating System

macOS (Default)

### Driver

Docker

**Comment by klaases** [comment]
Hi @goldytech, have you tried asking your question in the Slack channel?

https://minikube.sigs.k8s.io/community/

**Comment by RA489** [comment]
@goldytech Please ask questions on #minikube slack.
