### ISSUE TITLE
Feature Request: enable `CONFIG_PROC_CHILDREN` kernel configuration option for the VirtualBox VM

### ISSUE THREAD

**Issue by rm3l** [kubernetes/minikube#14351]
### What Happened?

Hi there!

We have an existing tool that runs in containers and relies on the `/proc` pseudo-filesystem to retrieve children processes of any given parent process. It leverages the `/proc/[pid]/task/[tid]/children` file, the presence of which is governed by a `CONFIG_PROC_CHILDREN` kernel config option on the host running those containers [1]

While this works great on most environments, we tested recently with Minikube (using the VirtualBox driver), and noticed that this file was missing because the kernel of the Minikube VirtualBox VM surprisingly does not set this config:

```
$ minikube ssh
$ zgrep CONFIG_PROC_CHILDREN /proc/config.gz                             
# CONFIG_PROC_CHILDREN is not set
```

We worked around this by building a custom minikube ISO, but I was wondering if it wouldn't make more sense to have this set as a default config instead.

If you think this makes sense, I can happily try to contribute a PR :-)

Thanks.

[1] https://man7.org/linux/man-pages/man5/proc.5.html

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8936506/log.txt)

### Operating System

Redhat/Fedora

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Hi @rm3l, thank you for your issue, I'm happy to accept a PR that enables the configuration option.

**Comment by rm3l** [comment]
> Hi @rm3l, thank you for your issue, I'm happy to accept a PR that enables the configuration option.

Thanks for your feedback, @spowelljr ! I'll look into this when I get some time.

**Comment by klaases** [comment]
Hi @rm3l, are you still interested in working on this issue?

**Comment by rm3l** [comment]
> are you still interested in working on this issue?

@klaases Yeah definitely. I've submitted a PR (#14689) to fix this issue. It has been already been approved, but I am not sure what remains to be done from my standpoint. That was the point of my question asked in https://github.com/kubernetes/minikube/pull/14689#issuecomment-1262364765 a few days ago.
Thanks.
