### ISSUE TITLE
Kubernetes addons enable error

### ISSUE THREAD

**Issue by EnesErten** [kubernetes/minikube#14355]
### What Happened?

"$minikube addons enable ingress " I am trying to run previous command. However, I am taken following error. I cannot find any solution. 

  - Using image k8s.gcr.io/ingress-nginx/controller:v1.1.1
  - Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
  - Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
* Verifying ingress addon...

X Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    * Please also attach the following file to the GitHub issue:                             │
│    * - /tmp/minikube_addons_63d5aaebbb272eea44b9208d7275913abf1afd99_0.log                  │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

* I0620 10:49:54.583703       1 storage_provisioner.go:116] Initializing the minikube storage provisioner...
I0620 10:49:54.622798       1 storage_provisioner.go:141] Storage provisioner initialized, now starting service!
I0620 10:49:54.623311       1 leaderelection.go:243] attempting to acquire leader lease kube-system/k8s.io-minikube-hostpath...
I0620 10:49:54.674541       1 leaderelection.go:253] successfully acquired lease kube-system/k8s.io-minikube-hostpath
I0620 10:49:54.674877       1 controller.go:835] Starting provisioner controller k8s.io/minikube-hostpath_minikube_e95d0e5b-971e-4bb4-b3b1-f4f8c5d00737!
I0620 10:49:54.687559       1 event.go:282] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"k8s.io-minikube-hostpath", UID:"d0049b93-0c2a-4ff4-b879-7671b5cb210c", APIVersion:"v1", ResourceVersion:"492", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' minikube_e95d0e5b-971e-4bb4-b3b1-f4f8c5d00737 became leader
I0620 10:49:54.775545       1 controller.go:884] Started provisioner controller k8s.io/minikube-hostpath_minikube_e95d0e5b-971e-4bb4-b3b1-f4f8c5d00737!

*
* ==> storage-provisioner [f43184dfc181] <==
* I0620 10:49:21.596756       1 storage_provisioner.go:116] Initializing the minikube storage provisioner...
F0620 10:49:51.602828       1 main.go:39] error getting server version: Get "https://10.96.0.1:443/version?timeout=32s": dial tcp 10.96.0.1:443: i/o timeout

### Operating System

Ubuntu

### Driver

KVM2

**Comment by EnesErten** [comment]
Also I tried different ways and I shared on stackoverflow. You can acces the issue by the following link. https://stackoverflow.com/questions/72697256/kubernetes-dashboard-open-remote-acces-issue

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by EnesErten** [comment]
Hello i solved the problem by the kube proxy for current situation it solved the problem. Thanks for supporting

**Comment by klaases** [comment]
Hi @EnesErten – glad to hear that the issue was able to be solved. I'll go ahead and close the issue for now, so that we can prioritize our backlog.

Thank you for sharing your experience!
