### ISSUE TITLE
Question: How to connect docker inside?

### ISSUE THREAD

**Issue by Yensan** [kubernetes/minikube#14350]
### What Happened?

minikube is an learn/debug/test tool for K8S.  
I use a Mac Air as a dev computer, ip `192.168.0.5`.
use a old PC as a openSUSE Linux server, ip `192.168.0.9`, 
in linux run `minikube start --driver=kvm2`, generated a VM `192.168.39.155`
Mac not in the VM subnet, it is imposable to access the VM. So, I create a nginx proxy for it. 
But, when I use docker-cli in mac to connect it, it gives me an error.
```shell
$ docker -H=tcp://192.168.0.9:57303 --tlsverify     --tlscacert=ca.pem     --tlscert=cert.pem     --tlskey=key.pem      ps -a
>>> error during connect: Get https://192.168.0.9:57303/v1.26/containers/json?all=1: x509: certificate is valid for 192.168.39.155, 192.168.39.155, 127.0.0.1, not 192.168.0.9
```

Nginx's configure is right. In linux(minikube's host)
```shell
$ cd ~
$ docker -H=127.0.0.1:57303 --tlsverify --tlscacert=ca.pem --tlscert=cert.pem --tlskey=key.pem ps -a
>>> (show all containers in cluster)
```

So, how can I access the docker in cluster? I know, `ssh admin@linux_ip`, then interact with it, but I want use some UI tool, such as vscode `docker extension`.

### Attach the log file

null

### Operating System

Ubuntu

### Driver

KVM2

**Comment by knrt10** [comment]
I you couls ssh into the vm using `minikube ssh` commans

**Comment by RA489** [comment]
@Yensan doesn't minikube ssh worked for you?

**Comment by afbjorklund** [comment]
> So, how can I access the docker in cluster?

`minikube docker-env`

**Comment by sharifelgamal** [comment]
`minikube docker-env` will give you the commands to run to connect your local docker client to the docker inside minikube.

**Comment by Yensan** [comment]
> @Yensan doesn't `minikube ssh `worked for you?

I knew, `minikube ssh`, `eval $(minikube -p minikube docker-env) ` , but I want to know what is the k8s. So, I want to interact with the container from remote and directly, without any wrapper.

Finally, I made it with complex settings. https://github.com/kubernetes/minikube/issues/14346#issuecomment-1160738744
Now, I use vscode's docker plugin, GUI, docker containers is in my eyes, exposed everything. When I look into k8s, I can't help to yield, so huge, nested. It is not easy to achieve. 
Minikube is a good playground to learn. Thank you making it.
And thanks all of you to reply. 
I head in Helm now.

**Comment by Yensan** [comment]
```mermaid
flowchart LR
A([nicM_192.168.0.12])<--->B([nicL_192.168.0.9]); B -.-x C-->B;
C([S_192.168.39.1])<--->D[VM_192.168.39.88]; E[Process];C <-->E; B <--> E
subgraph Linux
B;C;D;E
end
subgraph macOS
A
end
```

In Linux server, I open a nginx tcp proxy to inject data into virtual machine. Maybe it is silly, I am not familiar with KVM-QEMU-virsh toolchain. Most people use parallels, VMWare and virtualbox. While, in deployment env, most case is hyper-v, kvm, openstack... This is the reason I use kvm.
