### ISSUE TITLE
minikube not installed

### ISSUE THREAD

**Issue by Bhushan199** [kubernetes/minikube#14365]
### What Happened?

when am installing minikube in ubuntu server not installed .

Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

### Attach the log file

[minikube_logs_c1f401d1170bb53a8f6da5b02e8de4d4f5f00562_0.log](https://github.com/kubernetes/minikube/files/8946117/minikube_logs_c1f401d1170bb53a8f6da5b02e8de4d4f5f00562_0.log)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @Bhushan199, thanks for reporting your issue with minikube.

Could you try running the following:
```
$ chmod 777 ~/.docker
$ chmod 66 ~/.docker/config.json
```

https://github.com/kubernetes/minikube/issues/8409#issuecomment-907269490

**Comment by klaases** [comment]
Hi @Bhushan199 – did you have a chance to try and run the above commands?

Also, is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by Bhushan199** [comment]
Hi Kubernetes/Minikube,

Thank you for your reply , now it's working for me.

Regards,
Bhushan.
