### ISSUE TITLE
Remote access minikube service problem when I minikube start --listen-address='0.0.0.0', it not works, no any local address listening

### ISSUE THREAD

**Issue by Jijingling** [kubernetes/minikube#14364]
### What Happened?

I want to access some minikube service from remote internet sites, according to the minikube guides, the parameter --listen-address='0.0.0.0' should be added. When I follow it but seems no any effect, pls see below output, thanks for someone to help!

**Start MiniKube**
~$ minikube start --listen-address='0.0.0.0'
* minikube v1.25.2 on Ubuntu 20.04
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Restarting existing docker container for "minikube" ...
! This container is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
  - kubelet.housekeeping-interval=5m
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**MiniKube Service List**
~$ minikube service list
|-------------|---------------------------------|--------------|---------------------------|
|  NAMESPACE  |              NAME               | TARGET PORT  |            URL            |
|-------------|---------------------------------|--------------|---------------------------|
| default     | keda-operator-metrics-apiserver | No node port |
| default     | kubernetes                      | No node port |
| default     | locust                          |         8089 | http://192.168.49.2:30015 |
| default     | main-nginx-ingress              | http/80      | http://192.168.49.2:30005 |
|             |                                 | https/443    | http://192.168.49.2:30600 |
| default     | podinfo                         |           80 | http://192.168.49.2:30001 |
| default     | prometheus-alertmanager         | No node port |
| default     | prometheus-kube-state-metrics   | No node port |
| default     | prometheus-node-exporter        | No node port |
| default     | prometheus-pushgateway          | No node port |
| default     | prometheus-server               | http/80      | http://192.168.49.2:30010 |
| kube-system | kube-dns                        | No node port |
|-------------|---------------------------------|--------------|---------------------------|

**Netstat -a**
~$ netstat -a |grep tcp
tcp        0      0 localhost:49168         0.0.0.0:*               LISTEN     
tcp        0      0 localhost:49169         0.0.0.0:*               LISTEN     
tcp        0      0 localhost:41649         0.0.0.0:*               LISTEN     
tcp        0      0 localhost:49170         0.0.0.0:*               LISTEN     
tcp        0      0 localhost:49171         0.0.0.0:*               LISTEN     
tcp        0      0 localhost:49172         0.0.0.0:*               LISTEN     
tcp        0      0 localhost:domain        0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:ssh             0.0.0.0:*               LISTEN     
tcp        0      0 localhost:ipp           0.0.0.0:*               LISTEN     
tcp        0      0 localhost:6010          0.0.0.0:*               LISTEN     
tcp        0      0 localhost:6011          0.0.0.0:*               LISTEN     
tcp        0      0 localhost:56694         localhost:49172         TIME_WAIT  
tcp        0     36 localhost:ssh           localhost:58367         ESTABLISHED
tcp        0      0 localhost:40916         bogon:ssh               TIME_WAIT  
tcp        0      0 localhost:ssh           localhost:61181         ESTABLISHED
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN     
tcp6       0      0 ip6-localhost:ipp       [::]:*                  LISTEN     
tcp6       0      0 ip6-localhost:6010      [::]:*                  LISTEN     
tcp6       0      0 ip6-localhost:6011      [::]:*                  LISTEN     

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8944989/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by Jijingling** [comment]
I know how to use port-forward or kubectl proxy to remote access minikube service, but my question is how to use switch --listen-address='0.0.0.0' to automatically expose the minikube service(https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network); anyone can help?

**Comment by zhan9san** [comment]
Hi,

I am glad to help you.

Please allow me to clarify something to help you understand.

1. The `Minikube service` is different from Kubernetes service.
2. `--listen-address='0.0.0.0'` is mainly to make users can access Kubernetes cluster from another server.

Please let me know what is your real scenario.

If you choose `docker` or `podman` driver, Kubernetes cluster will run inside a container named `minikube` in which cluster components run as below.

```shell
$ minikube ssh
docker@minikube:~$ docker ps
CONTAINER ID   IMAGE                                                                     COMMAND                  CREATED         STATUS         PORTS     NAMES
c5ee8313a63b   registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner   "/storage-provisioner"   5 minutes ago   Up 5 minutes             k8s_storage-provisioner_storage-provisioner_kube-system_770168e3-baff-418e-b8b2-99eeb567aff0_0
2ffee2a23d20   a4ca41631cc7                                                              "/coredns -conf /etc…"   5 minutes ago   Up 5 minutes             k8s_coredns_coredns-65c54cc984-bjzzk_kube-system_6fd8f210-7787-4657-b6cc-f23b4ac78609_0
2c99c0b30880   9b7cc9982109                                                              "/usr/local/bin/kube…"   5 minutes ago   Up 5 minutes             k8s_kube-proxy_kube-proxy-29zbx_kube-system_10f39b29-f42a-4a90-b0cf-8fd239b2a00d_0
e88a2b3ed8e5   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_kube-proxy-29zbx_kube-system_10f39b29-f42a-4a90-b0cf-8fd239b2a00d_0
ea62fd80763c   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_coredns-65c54cc984-bjzzk_kube-system_6fd8f210-7787-4657-b6cc-f23b4ac78609_0
efbb0b490c41   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_storage-provisioner_kube-system_770168e3-baff-418e-b8b2-99eeb567aff0_0
4e8b3bac2cff   b07520cd7ab7                                                              "kube-controller-man…"   6 minutes ago   Up 6 minutes             k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_b3f2a7e9e78f98635fedbf1475ca018b_0
7047225a98bf   99a3486be4f2                                                              "kube-scheduler --au…"   6 minutes ago   Up 6 minutes             k8s_kube-scheduler_kube-scheduler-minikube_kube-system_48e84b90b1cc4ad712938e8925bfc527_0
4ef526cf6178   25f8c7f3da61                                                              "etcd --advertise-cl…"   6 minutes ago   Up 6 minutes             k8s_etcd_etcd-minikube_kube-system_d73ec7a951d8fd3737cb02128c96776c_0
59cc1ed888e0   f40be0088a83                                                              "kube-apiserver --ad…"   6 minutes ago   Up 6 minutes             k8s_kube-apiserver_kube-apiserver-minikube_kube-system_296b4435a215a902aca6622aa80da022_0
cac6e48405de   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_etcd-minikube_kube-system_d73ec7a951d8fd3737cb02128c96776c_0
21f7b2e33c5a   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-apiserver-minikube_kube-system_296b4435a215a902aca6622aa80da022_0
0456a09034e1   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-scheduler-minikube_kube-system_48e84b90b1cc4ad712938e8925bfc527_0
eedc5de2defa   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-controller-manager-minikube_kube-system_b3f2a7e9e78f98635fedbf1475ca018b_0
```

These components inside container including kube-apiserver, cannot be accessed until they are exposed to Host OS.

### Without `--listen-address='0.0.0.0'`

It's `127.0.0.1`, that's to say, it can only be accessed from Host OS.

```shell
$ docker port 0cb
8443/tcp -> 127.0.0.1:49164
22/tcp -> 127.0.0.1:49167
2376/tcp -> 127.0.0.1:49166
32443/tcp -> 127.0.0.1:49163
5000/tcp -> 127.0.0.1:49165
```

### With `--listen-address='0.0.0.0'`

[how-can-i-access-a-minikube-cluster-from-a-remote-network](https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network) is to expose the ports of Minikube container on '0.0.0.0'

If the listen address is `0.0.0.0`, they can be accessed from another server using the Host IP address as well.

```shell
$ docker port minikube
8443/tcp -> 0.0.0.0:49162
22/tcp -> 0.0.0.0:49165
2376/tcp -> 0.0.0.0:49164
32443/tcp -> 0.0.0.0:49161
5000/tcp -> 0.0.0.0:49163
```

After you create a Kubernetes cluster by `Minikube`, you can copy the `~/.kube/config`, certificate and key files defined in `~/.kube/config` to another server.

Finally, you can create Kubernetes service remotely, and access it using `kubectl port-forward`.

**Comment by Jijingling** [comment]
> Hi,
> 
> I am glad to help you.
> 
> Please allow me to clarify something to help you understand.
> 
> 1. The `Minikube service` is different from Kubernetes service.
> 2. `--listen-address='0.0.0.0'` is mainly to make users can access Kubernetes cluster from another server.
> 
> Please let me know what is your real scenario.
> 
> If you choose `docker` or `podman` driver, Kubernetes cluster will run inside a container named `minikube` in which cluster components run as below.
> 
> ```shell
> $ minikube ssh
> docker@minikube:~$ docker ps
> CONTAINER ID   IMAGE                                                                     COMMAND                  CREATED         STATUS         PORTS     NAMES
> c5ee8313a63b   registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner   "/storage-provisioner"   5 minutes ago   Up 5 minutes             k8s_storage-provisioner_storage-provisioner_kube-system_770168e3-baff-418e-b8b2-99eeb567aff0_0
> 2ffee2a23d20   a4ca41631cc7                                                              "/coredns -conf /etc…"   5 minutes ago   Up 5 minutes             k8s_coredns_coredns-65c54cc984-bjzzk_kube-system_6fd8f210-7787-4657-b6cc-f23b4ac78609_0
> 2c99c0b30880   9b7cc9982109                                                              "/usr/local/bin/kube…"   5 minutes ago   Up 5 minutes             k8s_kube-proxy_kube-proxy-29zbx_kube-system_10f39b29-f42a-4a90-b0cf-8fd239b2a00d_0
> e88a2b3ed8e5   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_kube-proxy-29zbx_kube-system_10f39b29-f42a-4a90-b0cf-8fd239b2a00d_0
> ea62fd80763c   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_coredns-65c54cc984-bjzzk_kube-system_6fd8f210-7787-4657-b6cc-f23b4ac78609_0
> efbb0b490c41   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_storage-provisioner_kube-system_770168e3-baff-418e-b8b2-99eeb567aff0_0
> 4e8b3bac2cff   b07520cd7ab7                                                              "kube-controller-man…"   6 minutes ago   Up 6 minutes             k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_b3f2a7e9e78f98635fedbf1475ca018b_0
> 7047225a98bf   99a3486be4f2                                                              "kube-scheduler --au…"   6 minutes ago   Up 6 minutes             k8s_kube-scheduler_kube-scheduler-minikube_kube-system_48e84b90b1cc4ad712938e8925bfc527_0
> 4ef526cf6178   25f8c7f3da61                                                              "etcd --advertise-cl…"   6 minutes ago   Up 6 minutes             k8s_etcd_etcd-minikube_kube-system_d73ec7a951d8fd3737cb02128c96776c_0
> 59cc1ed888e0   f40be0088a83                                                              "kube-apiserver --ad…"   6 minutes ago   Up 6 minutes             k8s_kube-apiserver_kube-apiserver-minikube_kube-system_296b4435a215a902aca6622aa80da022_0
> cac6e48405de   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_etcd-minikube_kube-system_d73ec7a951d8fd3737cb02128c96776c_0
> 21f7b2e33c5a   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-apiserver-minikube_kube-system_296b4435a215a902aca6622aa80da022_0
> 0456a09034e1   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-scheduler-minikube_kube-system_48e84b90b1cc4ad712938e8925bfc527_0
> eedc5de2defa   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-controller-manager-minikube_kube-system_b3f2a7e9e78f98635fedbf1475ca018b_0
> ```
> 
> These components inside container including kube-apiserver, cannot be accessed until they are exposed to Host OS.
> 
> ### Without `--listen-address='0.0.0.0'`
> It's `127.0.0.1`, that's to say, it can only be accessed from Host OS.
> 
> ```shell
> $ docker port 0cb
> 8443/tcp -> 127.0.0.1:49164
> 22/tcp -> 127.0.0.1:49167
> 2376/tcp -> 127.0.0.1:49166
> 32443/tcp -> 127.0.0.1:49163
> 5000/tcp -> 127.0.0.1:49165
> ```
> 
> ### With `--listen-address='0.0.0.0'`
> [how-can-i-access-a-minikube-cluster-from-a-remote-network](https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network) is to expose the ports of Minikube container on '0.0.0.0'
> 
> If the listen address is `0.0.0.0`, they can be accessed from another server using the Host IP address as well.
> 
> ```shell
> $ docker port minikube
> 8443/tcp -> 0.0.0.0:49162
> 22/tcp -> 0.0.0.0:49165
> 2376/tcp -> 0.0.0.0:49164
> 32443/tcp -> 0.0.0.0:49161
> 5000/tcp -> 0.0.0.0:49163
> ```
> 
> After you create a Kubernetes cluster by `Minikube`, you can copy the `~/.kube/config`, certificate and key files defined in `~/.kube/config` to another server.
> 
> Finally, you can create Kubernetes service remotely, and access it using `kubectl port-forward`.

Hello zhan9san,

Appreciated for your kindly explain, it means this flag is designed for expose minikube management function not for inside user deployed applications, am I right?
Very helpful, your answer indeed, thanks buddy.

**Comment by clarencesham** [comment]
Hello zhan9san,

I have set up minikube with --listen-address='0.0.0.0' on a server, and a remote machine with kubectl installed.  What are the detail set up that I need to do in order to issue "kubectl get nodes -A" and get the information of minikube pods?

> Hi,
> 
> I am glad to help you.
> 
> Please allow me to clarify something to help you understand.
> 
> 1. The `Minikube service` is different from Kubernetes service.
> 2. `--listen-address='0.0.0.0'` is mainly to make users can access Kubernetes cluster from another server.
> 
> Please let me know what is your real scenario.
> 
> If you choose `docker` or `podman` driver, Kubernetes cluster will run inside a container named `minikube` in which cluster components run as below.
> 
> ```shell
> $ minikube ssh
> docker@minikube:~$ docker ps
> CONTAINER ID   IMAGE                                                                     COMMAND                  CREATED         STATUS         PORTS     NAMES
> c5ee8313a63b   registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner   "/storage-provisioner"   5 minutes ago   Up 5 minutes             k8s_storage-provisioner_storage-provisioner_kube-system_770168e3-baff-418e-b8b2-99eeb567aff0_0
> 2ffee2a23d20   a4ca41631cc7                                                              "/coredns -conf /etc…"   5 minutes ago   Up 5 minutes             k8s_coredns_coredns-65c54cc984-bjzzk_kube-system_6fd8f210-7787-4657-b6cc-f23b4ac78609_0
> 2c99c0b30880   9b7cc9982109                                                              "/usr/local/bin/kube…"   5 minutes ago   Up 5 minutes             k8s_kube-proxy_kube-proxy-29zbx_kube-system_10f39b29-f42a-4a90-b0cf-8fd239b2a00d_0
> e88a2b3ed8e5   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_kube-proxy-29zbx_kube-system_10f39b29-f42a-4a90-b0cf-8fd239b2a00d_0
> ea62fd80763c   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_coredns-65c54cc984-bjzzk_kube-system_6fd8f210-7787-4657-b6cc-f23b4ac78609_0
> efbb0b490c41   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_storage-provisioner_kube-system_770168e3-baff-418e-b8b2-99eeb567aff0_0
> 4e8b3bac2cff   b07520cd7ab7                                                              "kube-controller-man…"   6 minutes ago   Up 6 minutes             k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_b3f2a7e9e78f98635fedbf1475ca018b_0
> 7047225a98bf   99a3486be4f2                                                              "kube-scheduler --au…"   6 minutes ago   Up 6 minutes             k8s_kube-scheduler_kube-scheduler-minikube_kube-system_48e84b90b1cc4ad712938e8925bfc527_0
> 4ef526cf6178   25f8c7f3da61                                                              "etcd --advertise-cl…"   6 minutes ago   Up 6 minutes             k8s_etcd_etcd-minikube_kube-system_d73ec7a951d8fd3737cb02128c96776c_0
> 59cc1ed888e0   f40be0088a83                                                              "kube-apiserver --ad…"   6 minutes ago   Up 6 minutes             k8s_kube-apiserver_kube-apiserver-minikube_kube-system_296b4435a215a902aca6622aa80da022_0
> cac6e48405de   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_etcd-minikube_kube-system_d73ec7a951d8fd3737cb02128c96776c_0
> 21f7b2e33c5a   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-apiserver-minikube_kube-system_296b4435a215a902aca6622aa80da022_0
> 0456a09034e1   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-scheduler-minikube_kube-system_48e84b90b1cc4ad712938e8925bfc527_0
> eedc5de2defa   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-controller-manager-minikube_kube-system_b3f2a7e9e78f98635fedbf1475ca018b_0
> ```
> 
> These components inside container including kube-apiserver, cannot be accessed until they are exposed to Host OS.
> 
> ### Without `--listen-address='0.0.0.0'`
> It's `127.0.0.1`, that's to say, it can only be accessed from Host OS.
> 
> ```shell
> $ docker port 0cb
> 8443/tcp -> 127.0.0.1:49164
> 22/tcp -> 127.0.0.1:49167
> 2376/tcp -> 127.0.0.1:49166
> 32443/tcp -> 127.0.0.1:49163
> 5000/tcp -> 127.0.0.1:49165
> ```
> 
> ### With `--listen-address='0.0.0.0'`
> [how-can-i-access-a-minikube-cluster-from-a-remote-network](https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network) is to expose the ports of Minikube container on '0.0.0.0'
> 
> If the listen address is `0.0.0.0`, they can be accessed from another server using the Host IP address as well.
> 
> ```shell
> $ docker port minikube
> 8443/tcp -> 0.0.0.0:49162
> 22/tcp -> 0.0.0.0:49165
> 2376/tcp -> 0.0.0.0:49164
> 32443/tcp -> 0.0.0.0:49161
> 5000/tcp -> 0.0.0.0:49163
> ```
> 
> After you create a Kubernetes cluster by `Minikube`, you can copy the `~/.kube/config`, certificate and key files defined in `~/.kube/config` to another server.
> 
> Finally, you can create Kubernetes service remotely, and access it using `kubectl port-forward`.

**Comment by clarencesham** [comment]
> Hello zhan9san,
> 
> I have set up minikube with --listen-address='0.0.0.0' on a server, and a remote machine with kubectl installed. What are the detail set up that I need to do in order to issue "kubectl get nodes -A" and get the information of minikube pods?
> 
> > Hi,
> > I am glad to help you.
> > Please allow me to clarify something to help you understand.
> > 
> > 1. The `Minikube service` is different from Kubernetes service.
> > 2. `--listen-address='0.0.0.0'` is mainly to make users can access Kubernetes cluster from another server.
> > 
> > Please let me know what is your real scenario.
> > If you choose `docker` or `podman` driver, Kubernetes cluster will run inside a container named `minikube` in which cluster components run as below.
> > ```shell
> > $ minikube ssh
> > docker@minikube:~$ docker ps
> > CONTAINER ID   IMAGE                                                                     COMMAND                  CREATED         STATUS         PORTS     NAMES
> > c5ee8313a63b   registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner   "/storage-provisioner"   5 minutes ago   Up 5 minutes             k8s_storage-provisioner_storage-provisioner_kube-system_770168e3-baff-418e-b8b2-99eeb567aff0_0
> > 2ffee2a23d20   a4ca41631cc7                                                              "/coredns -conf /etc…"   5 minutes ago   Up 5 minutes             k8s_coredns_coredns-65c54cc984-bjzzk_kube-system_6fd8f210-7787-4657-b6cc-f23b4ac78609_0
> > 2c99c0b30880   9b7cc9982109                                                              "/usr/local/bin/kube…"   5 minutes ago   Up 5 minutes             k8s_kube-proxy_kube-proxy-29zbx_kube-system_10f39b29-f42a-4a90-b0cf-8fd239b2a00d_0
> > e88a2b3ed8e5   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_kube-proxy-29zbx_kube-system_10f39b29-f42a-4a90-b0cf-8fd239b2a00d_0
> > ea62fd80763c   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_coredns-65c54cc984-bjzzk_kube-system_6fd8f210-7787-4657-b6cc-f23b4ac78609_0
> > efbb0b490c41   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 5 minutes ago   Up 5 minutes             k8s_POD_storage-provisioner_kube-system_770168e3-baff-418e-b8b2-99eeb567aff0_0
> > 4e8b3bac2cff   b07520cd7ab7                                                              "kube-controller-man…"   6 minutes ago   Up 6 minutes             k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_b3f2a7e9e78f98635fedbf1475ca018b_0
> > 7047225a98bf   99a3486be4f2                                                              "kube-scheduler --au…"   6 minutes ago   Up 6 minutes             k8s_kube-scheduler_kube-scheduler-minikube_kube-system_48e84b90b1cc4ad712938e8925bfc527_0
> > 4ef526cf6178   25f8c7f3da61                                                              "etcd --advertise-cl…"   6 minutes ago   Up 6 minutes             k8s_etcd_etcd-minikube_kube-system_d73ec7a951d8fd3737cb02128c96776c_0
> > 59cc1ed888e0   f40be0088a83                                                              "kube-apiserver --ad…"   6 minutes ago   Up 6 minutes             k8s_kube-apiserver_kube-apiserver-minikube_kube-system_296b4435a215a902aca6622aa80da022_0
> > cac6e48405de   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_etcd-minikube_kube-system_d73ec7a951d8fd3737cb02128c96776c_0
> > 21f7b2e33c5a   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-apiserver-minikube_kube-system_296b4435a215a902aca6622aa80da022_0
> > 0456a09034e1   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-scheduler-minikube_kube-system_48e84b90b1cc4ad712938e8925bfc527_0
> > eedc5de2defa   registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.6             "/pause"                 6 minutes ago   Up 6 minutes             k8s_POD_kube-controller-manager-minikube_kube-system_b3f2a7e9e78f98635fedbf1475ca018b_0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These components inside container including kube-apiserver, cannot be accessed until they are exposed to Host OS.
> > ### Without `--listen-address='0.0.0.0'`
> > It's `127.0.0.1`, that's to say, it can only be accessed from Host OS.
> > ```shell
> > $ docker port 0cb
> > 8443/tcp -> 127.0.0.1:49164
> > 22/tcp -> 127.0.0.1:49167
> > 2376/tcp -> 127.0.0.1:49166
> > 32443/tcp -> 127.0.0.1:49163
> > 5000/tcp -> 127.0.0.1:49165
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ### With `--listen-address='0.0.0.0'`
> > [how-can-i-access-a-minikube-cluster-from-a-remote-network](https://minikube.sigs.k8s.io/docs/faq/#how-can-i-access-a-minikube-cluster-from-a-remote-network) is to expose the ports of Minikube container on '0.0.0.0'
> > If the listen address is `0.0.0.0`, they can be accessed from another server using the Host IP address as well.
> > ```shell
> > $ docker port minikube
> > 8443/tcp -> 0.0.0.0:49162
> > 22/tcp -> 0.0.0.0:49165
> > 2376/tcp -> 0.0.0.0:49164
> > 32443/tcp -> 0.0.0.0:49161
> > 5000/tcp -> 0.0.0.0:49163
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After you create a Kubernetes cluster by `Minikube`, you can copy the `~/.kube/config`, certificate and key files defined in `~/.kube/config` to another server.
> > Finally, you can create Kubernetes service remotely, and access it using `kubectl port-forward`.

I finally tested successfully.

When you do your first "minikube start", you have to specify the option of "--apiserver-ips", setting it to the IP address of the minikube host, and the option of "--listen-address=0.0.0.0".  Otherwise, you need to do "minikube delete" and re-create minikube docker image with the 2 options.

Next, you have to copy 4 files: ca.crt, client.crt, client.key and config on the minikube server to your remote machine.

Then, on your remote machine, you have to change "config" file by specifying the locations of ca.crt, client.crt and client.key, as well as the IP address and port on the line "server: https://<IP.address.of.minikube>:49154".  Remember that minikube is listening to 0.0.0.0:49154 and not 8443.

Finally, you can do "kubectl --kubeconfig <location_of_config> get pods -A

And it worked!!

**Comment by klaases** [comment]
> When you do your first "minikube start", you have to specify the option of "--apiserver-ips", setting it to the IP address of the minikube host, and the option of "--listen-address=0.0.0.0". Otherwise, you need to do "minikube delete" and re-create minikube docker image with the 2 options.
> 
> Next, you have to copy 4 files: ca.crt, client.crt, client.key and config on the minikube server to your remote machine.
> 
> Then, on your remote machine, you have to change "config" file by specifying the locations of ca.crt, client.crt and client.key, as well as the IP address and port on the line "server: https://<IP.address.of.minikube>:49154". Remember that minikube is listening to 0.0.0.0:49154 and not 8443.
> 
> Finally, you can do "kubectl --kubeconfig <location_of_config> get pods -A

Hi @Jijingling, did you have a chance to review the comments from @clarencesham, and if so, were they helpful in resolving the issue?

**Comment by klaases** [comment]
Hi @Jijingling – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by Fritskee** [comment]
> I finally tested successfully.
> 
> When you do your first "minikube start", you have to specify the option of "--apiserver-ips", setting it to the IP address of the minikube host, and the option of "--listen-address=0.0.0.0". Otherwise, you need to do "minikube delete" and re-create minikube docker image with the 2 options.
> 
> Next, you have to copy 4 files: ca.crt, client.crt, client.key and config on the minikube server to your remote machine.
> 
> Then, on your remote machine, you have to change "config" file by specifying the locations of ca.crt, client.crt and client.key, as well as the IP address and port on the line "server: https://<IP.address.of.minikube>:49154". Remember that minikube is listening to 0.0.0.0:49154 and not 8443.
> 
> Finally, you can do "kubectl --kubeconfig <location_of_config> get pods -A
> 
> And it worked!!

This one actually saved me! Thanks so much!

**Comment by robipresotto** [comment]
you can use the command below without the need of copying the certificates.
minikube kubectl -- config view --flatten > ~/Download/remote-config

Copy the file to the new machine and change the ip as mentioned previously ;)
