### ISSUE TITLE
Unable to connect to the server: dial tcp <ip>

### ISSUE THREAD

**Issue by mahuyaacharya** [kubernetes/minikube#14367]
### What Happened?

Unable to connect to the server: dial tcp 192.168.59.100:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

### Attach the log file

![image](https://user-images.githubusercontent.com/92091348/174797306-463d6f68-81dc-4836-bea4-dc350269ab5f.png)

### Operating System

Windows

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by klaases** [comment]
Hi @mahuyaacharya – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
