### ISSUE TITLE
On Minikube pause image is always pulled from internet and proxy setting doesn't work

### ISSUE THREAD

**Issue by Rev1408** [kubernetes/minikube#1437]
Issue is mention here, I should have open the issue here, i did not realize it earlier 

https://github.com/kubernetes/kubernetes/issues/45226

**Comment by aaron-prindle** [comment]
It seems like you were able to resolve this here https://github.com/kubernetes/kubernetes/issues/45226#issuecomment-298882493.  We should better document how to use minikube behind a proxy.

**Comment by Rev1408** [comment]
@aaron-prindle I was able to solve the proxy setting, I mentioned two issues here one related to running behind http proxy and other imagePullPolicy not working correctly. I have a local copy of images on my laptop instance of docker not on docker instance on Minikube VM, so I guess that's not a issue, I will verify it and close the bug.

This need to be documented, looks like no where it is mentioned, all other places, nobody running behind a http proxy had a local instance of docker and than installed Minikube. They are directly installing Minikube and exporting the Minikube docker to host machine with` eval $(minikube docker-env)`
