### ISSUE TITLE
Minikube start fails - IP not available after waiting; machine minikube didn't return IP after 1 minute

### ISSUE THREAD

**Issue by glinker** [kubernetes/minikube#14385]
### What Happened?

Starting minikube for first time. Fails with the error message that the ip address not available. I've checked and my virtual machine has virtualization enabled. I'm on Centos 8. 

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8960585/logs.txt)

### Operating System

Other

### Driver

KVM2

**Comment by klaases** [comment]
Hi @glinker, are you still experiencing this issue? Are there any other services that could be tying up the ip address?

**Comment by glinker** [comment]
Yes I still have the issue.  I don’t know if any other services. This is a new install.  I installed a minimal Centos 8 system with GUI and then installed the minikube/kvm packages.

Gary Linker
IBM Security Expert Labs
***@***.***
512-413-8040
________________________________
From: klaases ***@***.***>
Sent: Tuesday, June 28, 2022 5:05:39 PM
To: kubernetes/minikube ***@***.***>
Cc: Gary Linker ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [kubernetes/minikube] Minikube start fails - IP not available after waiting; machine minikube didn't return IP after 1 minute (Issue #14385)

Hi @glinker, are you still experiencing this issue? Are there any other services that could be tying up the ip address? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.

ZjQcmQRYFpfptBannerEnd

Hi @glinker<https://github.com/glinker>, are you still experiencing this issue? Are there any other services that could be tying up the ip address?

**Comment by glinker** [comment]
How can I tell which IP is being used? Can I change which IP is being used?

**Comment by klaases** [comment]
Hi @glinker, also, are you running minikube in the cloud or on a physical machine?

**Comment by klaases** [comment]
Hi @glinker – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
