### ISSUE TITLE
failed to start

### ISSUE THREAD

**Issue by Darshants16081995** [kubernetes/minikube#14395]
### What Happened?

Failed to enable unit: Unit file cri-docker.socket does not exist.

### Attach the log file

fffffff

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by klaases** [comment]
Hi @Darshants16081995 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
