### ISSUE TITLE
testo

### ISSUE THREAD

**Issue by vadgis** [kubernetes/minikube#14401]
**Étapes pour reproduire le problème:** 

1.
2. 
3.

**Sortie complète de la commande `minikube logs`:**
<details>

</details>

**Sortie complète de la commande échouée:**
<details>

</details>

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

-----

Merci de partager votre expérience!

Pourriez-vous s'il vous plaît exécuter `minikube logs --file=logs.txt` et faire glisser et déposer le fichier dans ce problème.

Cela nous aidera à mieux isoler le problème, merci !
