### ISSUE TITLE
Issue in X Exiting due to MK_ADDON_ENABLE

### ISSUE THREAD

**Issue by nipunarora222** [kubernetes/minikube#14414]
### What Happened?

Please provide us the solution.

### Attach the log file

[minikube_addons_684d5494eb12cc8d43eafdba2efd60841d94e340_0.log](https://github.com/kubernetes/minikube/files/8975671/minikube_addons_684d5494eb12cc8d43eafdba2efd60841d94e340_0.log)

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @nipunarora222, looking at the logs you provided I can see you ran the command multiple times and all but the last time it succeeded, have you tried enabling it again to see if it was just a a flake?

**Comment by klaases** [comment]
Hi @nipunarora222  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
