### ISSUE TITLE
minikube start asking for an ssh password

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/minikube#1441]
Using:

- minikube 0.18.0
- Version 5.1.22 r115126 (Qt5.6.2)
- kuibectl v1.6.2
- Platform: darwin/amd64

Starting up minikube cluster using `minikube start` is asking for password. The `sudo` password is not working.

What is wrong?

**Comment by r2d4** [comment]
You shouldn't be prompted for any password, minikube doesn't require root and should be run as your normal user.  Can you give any more information?  Maybe the ownership of the minikube binary?

**Comment by arun-gupta** [comment]
Binary is owned by the current user.

0.17.1 starts up successfully with the following output:

```
0.17.1 $ ./minikube start
There is a newer version of minikube available (v0.18.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.18.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
Starting local Kubernetes cluster...
Starting VM...
Downloading Minikube ISO
 89.26 MB / 89.26 MB [==============================================] 100.00% 0s
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
```

**Comment by arun-gupta** [comment]
Weird, starting a cluster using 0.17.1 and now starting using 0.18.0 seems to work. Not sure what got updated/fixed during the process.

**Comment by QuinnyPig** [comment]
I'm betting it's an ssh key failure into the VM.

**Comment by arun-gupta** [comment]
There was no error message indicating that though, but glad it worked at least.

**Comment by r2d4** [comment]
@QuinnyPig is correct.  This happens when the minikube VM is in a bad state (the machine exists but the ssh key isn't present anymore).  Password auth shouldn't be enabled for the minikube VM anyways, not sure why that is the case now.

Going to reopen this, so that we remove this prompt even in bad states.

**Comment by tz70s** [comment]
Hi @r2d4, 
I'm curious about so what is the appropriate result do you expect if we get the ssh key lost?
Thanks!

**Comment by r2d4** [comment]
We should disable password prompts through an option on the client - so that there is never a password prompt when ssh key authentication fails

**Comment by vishwanath79** [comment]
hi,

New user here. I'm seeing the same issue. Is there a solve for this? - thanks.

minikube version: v0.20.1
Environment: Mac OS Sierra 10.12.5
    
I was following the install instructions here: https://github.com/kubernetes/minikube

What happened:
It does not accept root password. Not sure how to get past this. Tried reinstalling as well.

`==> Linking Binary 'minikube-darwin-amd64' to '/usr/local/bin/minikube'.
🍺  minikube was successfully installed!
$ minikube start 
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
Password:`

**Comment by divbit** [comment]
@vishwanath79 
I solved similar thing with a solution I found at another github issue somewhere
```
minikube delete
minikube start
```
which I guess clears ~/.minikube/machines

**Comment by vishwanath79** [comment]
@divbit  thanks for chiming in. Had tried that as well but that did not work for me either. I gave up on minikube. It was easier for me to just set up a Kubernetes cluster :).

**Comment by divbit** [comment]
@vishwanath79 No problem, I spent a couple of hours getting it working this morning, so figured to not waste the work just on myself as I came across this thread a couple times.

**Comment by songokudbz** [comment]
Any news on this? I have minikube version 0.23.0 on Windows and trying to start it with Hyperv. It still waits for you to login to minikube ....

**Comment by pienaarp** [comment]
I just entered 'root' as the root password on startup and it worked.

**Comment by pienaarp** [comment]
I entered 'root' as the root passwords when the VM boots and it works:

Starting local Kubernetes v1.7.5 cluster...
Starting VM...
** ENTER password in VM ***
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.

**Comment by emoulder** [comment]
I was having same issues but the minikube delete seems to have cleared up the problem.

**Comment by yujiangshui** [comment]
The issue still has.

**Comment by imroc** [comment]
The issue still has.

**Comment by drkrishnan8109** [comment]
The issue still exists

**Comment by drkrishnan8109** [comment]
I tried with username: root, pwd: root and it works. But you may have to think if you need root access. Its just an initial work around, I hope you could change pwds later

**Comment by sadjadtalakoob74** [comment]
> I entered 'root' as the root passwords when the VM boots and it works:
> 
> Starting local Kubernetes v1.7.5 cluster...
> Starting VM...
> ** ENTER password in VM ***
> Getting VM IP address...
> Moving files into cluster...
> Setting up certs...
> Connecting to cluster...
> Setting up kubeconfig...
> Starting cluster components...
> Kubectl is now configured to use the cluster.

i have same problem but it works as type "root" for password, thanks

**Comment by afbjorklund** [comment]
This ticket (and your kubernetes version) is ancient...
Can you try again with the latest, and open a new issue ?

**Comment by emoulder** [comment]
Sure, thanks.

**Comment by rodolfoap** [comment]
FYI, crashed with this today [SMP Debian 10 (Buster) 5.9.15-1~bpo10+1 (2020-12-31) x86_64 GNU/Linux], solved, the solution was adding $USER to the `libvirt` group.

**Comment by backnotprop** [comment]
Im using **hyperkit**. For me the issue was found when running `minikube start --alsologtostderr` 

```bash
I0510 06:44:33.826368   68809 out.go:176] 🔑  The 'hyperkit' driver requires elevated permissions. The following commands will be executed:

    $ sudo chown root:wheel /Users/<YOU>/.minikube/bin/docker-machine-driver-hyperkit
    $ sudo chmod u+s /Users/<YOU>/.minikube/bin/docker-machine-driver-hyperkit

I0510 06:44:33.826511   68809 install.go:99] testing: [sudo -n chown root:wheel /Users/<YOU>/.minikube/bin/docker-machine-driver-hyperkit]
Password:
```

Entering my mac's user password did not work... could be a corporate-issued mac controls thing I don't have time to look into. 

I **resolved the issue** by manually running the `chown` and `chmod` commands.

**Comment by 0xchabbi** [comment]
For all HyperV on Windows 11 User: 
open your powershell as admin
minikube delete 
minikube start 
test it with:
kubectl get po -A
or
minikube kubectl -- get po -A
