### ISSUE TITLE
 minikube start --vm-driver=hyperkit

### ISSUE THREAD

**Issue by augustotavares86** [kubernetes/minikube#14421]
### What Happened?

Hey guys I'm having a problem running minikube start --vm-driver=hyperkit  is anyone has a problem before with  hyperkit.

### Attach the log file

Last login: Thu Jun 23 21:40:55 on ttys000
❯ minikube start --vm-driver=hyperkit
😄  minikube v1.25.2 on Darwin 12.4
    ▪ KUBECONFIG=/etc/kubernetes/admin.conf
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running hyperkit "minikube" VM ...
🤦  StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: IP address is not set
🏃  Updating the running hyperkit "minikube" VM ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: IP address is not set

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IP address is not set

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by mprimeaux** [comment]
@augustotavares86 Thanks for opening this issue.

Would you mind posting the logs as per the above? `minikube logs --file=logs.txt`.  Also, would you mind posting the output of `minikube config view`?

**Comment by mprimeaux** [comment]
Also, I found [issue #7888](https://github.com/kubernetes/minikube/issues/7888) in case this is related.

**Comment by klaases** [comment]
Thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @augustotavares86 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
