### ISSUE TITLE
failure to enable ingress

### ISSUE THREAD

**Issue by sid-hbm** [kubernetes/minikube#14422]
### What Happened?

The command: **minikube addons enable ingress**
failed and the message is this:

Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8983377/logs.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by klaases** [comment]
Hi @sid-hbm, are you still experiencing this issue? Please try running `minikube delete` and try starting again.

**Comment by klaases** [comment]
Thank you for sharing your experience! Would it be possible to provide **pod** logs?

```
# 1. Get all images running in a cluster
kubectl get pods -A
```

```
# 2. Describe the pod in detail
kubectl describe pods my-pod
```

```
# 3. Get pod logs (stdout)
kubectl logs my-pod
```

Example
```
# Replace 'my-pod' with `ingress-nginx`
Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for [app.kubernetes.io/name=ingress-nginx](http://app.kubernetes.io/name=ingress-nginx) pods: timed out waiting for the condition
```

This will help us isolate the problem further, thank you!

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @sid-hbm – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
