### ISSUE TITLE
Docs / earlier checking for dependencies

### ISSUE THREAD

**Issue by jtagcat** [kubernetes/minikube#14427]
### What Happened?

Came from https://minikube.sigs.k8s.io/docs/start/ → https://minikube.sigs.k8s.io/docs/drivers/none/

systemd-nspawn; docker can run (setup: https://wiki.wut.ee/sysadmin/systemd-nspawn_containers)

debian bullseye / stable

What I did to get from 0 to start:
```
apt-get update
apt-get install -y \
    ca-certificates \
    curl \
    gnupg \
    lsb-release
mkdir -p /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
  $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
curl -LO https://github.com/Mirantis/cri-dockerd/releases/download/v0.2.3/cri-dockerd_0.2.3.3-0.debian-bullseye_amd64.deb
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
dpkg -i cri-dockerd_0.2.3.3-0.debian-bullseye_amd64.deb
dpkg -i minikube_latest_amd64.deb
minikube start --driver none # pls install conntrack
apt install conntrack -y
minikube start --driver none # no sudo: stderr: StartHost failed, but will try again: post-start: sudo mkdir (none): sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/miniku
be /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs:
 exec: "sudo": executable file not found in $PATH
apt install sudo -y
minikube start --driver none # stderr: sudo: crictl: command not found
curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.24.2/crictl-v1.24.2-linux-amd64.tar.gz
tar -xf crictl-v1.24.2-linux-amd64.tar.gz
mv crictl /usr/local/bin
minikube start --driver none # optional: CGROUPS_HUGETLB, CGROUPS_BLKIO:: missing + ethtool, socat + fatals (in log section)
# apt install -y ethtool socat
```

## Main points:
 - Check for sudo, crictl (and tell where to get it) before proceeding anywhere.
 - Is sudo even needed?
 - Can't continue (see above and below).

## Additional:
 - `/docs/drivers/none/`: [cri-dockerd](https://github.com/Mirantis/cri-dockerd#build-and-install): Maybe point to /releases; first time I tried to build it :)
 - On previous systemd-nspawn instance, when docker didn't have access to privileged syscalls (and failed mid-way), I couldn't delete, switch to an another driver (kubeadm n/a).

Sorry to blurt this here like this.

### Attach the log file

```
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
        [ERROR SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs no
t found in directory /lib/modules/5.10.0-8-amd64\n", err: exit status 1
```

[logs(1).txt](https://github.com/kubernetes/minikube/files/8985418/logs.1.txt)

Can't ignore and continue. Machine uses systemd-networkd.

### Operating System

Other

### Driver

None (Baremetal)

**Comment by afbjorklund** [comment]
When using the "none" driver, the user is reponsible for provisioning the container runtime (including any CRI adapter).

https://kubernetes.io/docs/setup/production-environment/container-runtimes/

> Is sudo even needed?

Minikube uses "sudo" for the privilege escalation, running as root complicates things for the setup and is not recommended.

----

If you have special needs outside the regular use case, sometimes it is easier to just run `kubeadm` directly.

**Comment by afbjorklund** [comment]
It would probably be a good idea to add checks for required tools, such as sudo
