### ISSUE TITLE
! StartHost failed, but will try again: error loading existing host

### ISSUE THREAD

**Issue by NinadD26** [kubernetes/minikube#14428]
! StartHost failed, but will try again: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\HP\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Failed to start virtualbox VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\HP\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\HP\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'

**Comment by Yensan** [comment]
+1 , It occurred in my case.
OS: openSUSE Leap 15.4, kernel 5.14.21-150400.22
I try many times. Both in virtualbox and kvm2. Enter the VM, docker images all done. No one containers at all.
```sh
$ minikube ssh
                         _             _

$ crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock ps -a | grep kube | grep -v pause
$ docker images
REPOSITORY                                                                    TAG       IMAGE ID       CREATED         SIZE
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver            v1.24.1   e9f4b425f919   4 weeks ago     130MB
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager   v1.24.1   b4ea7e648530   4 weeks ago     119MB
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy                v1.24.1   beb86f5d8e6c   4 weeks ago     110MB
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler            v1.24.1   18688a72645c   4 weeks ago     51MB
registry.cn-hangzhou.aliyuncs.com/google_containers/etcd                      3.5.3-0   aebe758cef4c   2 months ago    299MB
registry.cn-hangzhou.aliyuncs.com/google_containers/pause                     3.7       221177c6082a   3 months ago    711kB
registry.cn-hangzhou.aliyuncs.com/google_containers/coredns                   v1.8.6    a4ca41631cc7   8 months ago    46.8MB
registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner       v5        6e38f40d628d   15 months ago   31.5MB
$ docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
$ exit
```

**Comment by Yensan** [comment]
enter VM --> enter container, things go well. I can't fix it.

```sh
$ minikube ssh
                         _             _
$ docker pull busybox
Using default tag: latest
latest: Pulling from library/busybox
19d511225f94: Pull complete
Digest: sha256:3614ca5eacf0a3a1bcc361c939202a974b4902b9334ff36eb29ffe9011aaad83
Status: Downloaded newer image for busybox:latest
docker.io/library/busybox:latest
$ docker run -it --rm busybox
/ # w
USER		TTY		IDLE	TIME		 HOST
/ # who
/ # whoami
root
/ # exit
```

**Comment by Yensan** [comment]
```sh
$ minikube version
minikube version: v1.25.2
commit: 362d5fdc0a3dbee389b3d3f1034e8023e72bd3a7
```

rollback to `v1.25.2`, every thing is OK.

**Comment by klaases** [comment]
> * Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'

Hi @NinadD26, were you able to try `minikube delete` as suggested above? Does the issue persist?

**Comment by klaases** [comment]
Hi @NinadD26 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by plan9better** [comment]
What fixed it for me was removing the minikube docker container, removing the docker network, the ~/.minikube directory and completely restarting the computer, not just docker.

**Comment by caduunisal** [comment]
It works for me when I removed the .minikube directory and tried to start again.

1. sudo rm -rf .minikube/
2. minikube start
