### ISSUE TITLE
I can't able to see the node / pods when I hit the command kubectl get node/pods

### ISSUE THREAD

**Issue by Fattehali** [kubernetes/minikube#14436]
### What Happened?

The connection to the server localhost:8080 was refused - did you specify the right host or port?

### Attach the log file

I0627 06:19:26.857144    8970 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/li>
I0627 06:19:26.880503    8970 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0627 06:19:26.880532    8970 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0627 06:19:26.880544    8970 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0627 06:19:26.883596    8970 out.go:177] ℹ️  OS release is Ubuntu 22.04 LTS
I0627 06:19:26.885268    8970 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0627 06:19:26.885332    8970 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0627 06:19:26.885355    8970 start.go:309] post-start completed in 28.247531ms
I0627 06:19:26.885962    8970 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0627 06:19:26.886125    8970 start.go:134] duration metric: createHost completed in 353.592914ms
I0627 06:19:26.886135    8970 start.go:81] releasing machines lock for "minikube", held for 353.690349ms
I0627 06:19:26.886518    8970 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/r>
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0627 06:19:26.886555    8970 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0627 06:19:26.909513    8970 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0627 06:19:27.197068    8970 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0627 06:19:27.501511    8970 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0627 06:19:27.776896    8970 exec_runner.go:51] Run: sudo systemctl restart docker
I0627 06:19:28.124090    8970 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0627 06:19:28.140697    8970 out.go:177]
W0627 06:19:28.142771    8970 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

W0627 06:19:28.142807    8970 out.go:239]
W0627 06:19:28.143820    8970 out.go:239] ^[[31m╭───────────────────────────────────────────────────────────────────────────────────────────╮^>
^[[31m│^[[0m                                                                                           ^[[31m│^[[0m
^[[31m│^[[0m    😿  If the above advice does not help, please let us know:                             ^[[31m│^[[0m
^[[31m│^[[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           ^[[31m│^[[0m
^[[31m│^[[0m                                                                                           ^[[31m│^[[0m
^[[31m│^[[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    ^[[31m│^[[0m
^[[31m│^[[0m                                                                                           ^[[31m│^[[0m
^[[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯^[[0m
I0627 06:19:28.146401    8970 out.go:177]

*

### Operating System

Ubuntu

**Comment by klaases** [comment]
Hi @Fattehali, please try installing `cri-dockerd` and then try again.

https://github.com/Mirantis/cri-dockerd

Does this help?

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @Fattehali, were you able to try installing `cri-dockerd`, any luck?

**Comment by medyagh** [comment]
@Fattehali do you mind attaching the full log file ?

**Comment by klaases** [comment]
Hi @Fattehali, as suggested, please go ahead and try to install `cri-dockerd`, we look forward to any other questions you may have.

If needed, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
