### ISSUE TITLE
Unable to start Ingress on Minikube v1.26.0 with Kubernetes v1.23.8

### ISSUE THREAD

**Issue by sid-hbm** [kubernetes/minikube#14430]
### What Happened?

Minikube started successfully with the following command:

minikube start --kubernetes-version=v1.23.8 --memory=12g --cpus=6 --disk-size=50g --driver=hyperkit --container-runtime=docker

By the way, if you use the last version of Kubernetes in that command, Minikube won't start at all. 

The following command to enable Ingress is failing:

minikube addons enable ingress

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8985651/logs.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by klaases** [comment]
Hi @sid-hbm, I appreciate your update to the issue and detailed solution, thanks.
