### ISSUE TITLE
minikube start --driver=none throwing error

### ISSUE THREAD

**Issue by Abhijitrb** [kubernetes/minikube#14438]
### What Happened?

Execution output error log::
Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

Operating System- RHEL 9
Attached log

trying to set-up minikube on local Linux VM.
[logs.txt](https://github.com/kubernetes/minikube/files/8989945/logs.txt)

Note:: Error is coming when executed as "root" user as well as "Non-Root" User.
Kindly help

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/8989957/logs.txt)

### Operating System

Redhat/Fedora

**Comment by afbjorklund** [comment]
For Kubernetes 1.24, you need to also install cri-dockerd

https://kubernetes.io/blog/2022/02/17/dockershim-faq/

**Comment by afbjorklund** [comment]
Duplicates:
* #14410

**Comment by Abhijitrb** [comment]
Thanks!!

Can you help me with organized steps/commands to be executed to resolve this issue

**Comment by afbjorklund** [comment]
See https://kubernetes.io/docs/setup/production-environment/container-runtimes/

**Comment by spowelljr** [comment]
Going to close this issue to centralize these duplicated `cri-docker` issues in https://github.com/kubernetes/minikube/issues/14410. If you have any further questions or comments please leave them in https://github.com/kubernetes/minikube/issues/14410, thank you.

**Comment by riteshprasad1** [comment]
Follow following steps
for linux ubuntu 20 version:

VERSION="v1.24.1"
wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
rm -f crictl-$VERSION-linux-amd64.tar.gz

# version and wget to be executed together
Check
cat /etc/crictl.yaml
runtime-endpoint: unix:///var/run/dockershim.sock
image-endpoint: unix:///var/run/dockershim.sock
timeout: 2
debug: true
pull-image-on-create: false

Then run minikube start --driver=none
Source from: https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md
