### ISSUE TITLE
how to start minikube after restart my host pc

### ISSUE THREAD

**Issue by msh2050** [kubernetes/minikube#14440]
### What Happened?

I install minikube with podman and cri-o, the issue I have the pc will be late if I restart, and minikube will not work after restart my pc. this is my status after restart
```
$ minikube status 
E0627 11:54:21.381414   22556 status.go:261] The "minikube" host does not exist!
minikube
type: Control Plane
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent
```
So how to handle my cluster before and after restart the pc

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8990492/log.txt)

### Operating System

Ubuntu

### Driver

Podman

**Comment by klaases** [comment]
Hi @msh2050, please try running `minikube delete` and then start minikube again after restarting your PC, does this help get minikube working?

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @msh2050 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by klaases** [comment]
Hi @msh2050 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
