### ISSUE TITLE
Add qemu-user-static to qemu specific iso images

### ISSUE THREAD

**Issue by arixmkii** [kubernetes/minikube#14444]
### What Happened?

Quick start example https://minikube.sigs.k8s.io/docs/start/ (starting from step 4 deploy applications) fails on MacOS on M1 macs, because echoserver is amd64 only.

May be it is worth to provide this option to allow to run foreign architecture images using this new driver.

### Attach the log file

Echoserver in constant crashloop because it can't start amd64 application on aarch64 OS.

### Operating System

macOS (Default)

### Driver

Qemu2

**Comment by arixmkii** [comment]
Inspired by this https://edofic.com/posts/2021-09-12-podman-m1-amd64/

I'm not sure if default docker runtime is capable of doing the same. If not, then quick start documentation should be updated.

**Comment by afbjorklund** [comment]
There are two issues here.

One is that echoserver uses an ancient nginx, and should be updated (including multi-arch support)

The other is to add the qemu-user binaries (for amd64 and arm64) to the iso build, for running other images cross-architecture
