### ISSUE TITLE
unable to start minikube on ubuntu 18.04 on aws instance

### ISSUE THREAD

**Issue by ramvish52** [kubernetes/minikube#14453]
### What Happened?

* minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 18.04.6 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: File cri-docker.socket: Invalid argument

### Attach the log file

* ==> Last Start <==
* Log file created at: 2022/06/28 11:53:40
Running on machine: ip-172-31-29-124
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0628 11:53:40.132528    9659 out.go:296] Setting OutFile to fd 1 ...
I0628 11:53:40.132650    9659 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0628 11:53:40.132655    9659 out.go:309] Setting ErrFile to fd 2...
I0628 11:53:40.132661    9659 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0628 11:53:40.132851    9659 root.go:329] Updating PATH: /root/.minikube/bin
W0628 11:53:40.132966    9659 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0628 11:53:40.133068    9659 out.go:303] Setting JSON to false
I0628 11:53:40.133782    9659 start.go:115] hostinfo: {"hostname":"ip-172-31-29-124","uptime":2122,"bootTime":1656415098,"procs":123,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.4.0-1078-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec2e66f0-79ad-7373-09c4-d5fc84ab5c84"}
I0628 11:53:40.133844    9659 start.go:125] virtualization: xen guest
I0628 11:53:40.136175    9659 out.go:177] * minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
W0628 11:53:40.137899    9659 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0628 11:53:40.138097    9659 notify.go:193] Checking for updates...
I0628 11:53:40.138258    9659 config.go:178] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.1
I0628 11:53:40.138557    9659 exec_runner.go:51] Run: systemctl --version
I0628 11:53:40.141855    9659 driver.go:360] Setting default libvirt URI to qemu:///system
I0628 11:53:40.144270    9659 out.go:177] * Using the none driver based on existing profile
I0628 11:53:40.146194    9659 start.go:284] selected driver: none
I0628 11:53:40.146201    9659 start.go:805] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.29.124 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0628 11:53:40.146317    9659 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0628 11:53:40.146339    9659 start.go:1541] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0628 11:53:40.146718    9659 cni.go:95] Creating CNI manager for ""
I0628 11:53:40.146725    9659 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0628 11:53:40.146738    9659 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.29.124 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0628 11:53:40.151294    9659 out.go:177] * Starting control plane node minikube in cluster minikube
I0628 11:53:40.154373    9659 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0628 11:53:40.154572    9659 cache.go:208] Successfully downloaded all kic artifacts
I0628 11:53:40.154596    9659 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0628 11:53:40.154788    9659 start.go:356] acquired machines lock for "minikube" in 160.921µs
I0628 11:53:40.154807    9659 start.go:94] Skipping create...Using existing machine configuration
I0628 11:53:40.154814    9659 fix.go:55] fixHost starting: m01
W0628 11:53:40.155332    9659 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0628 11:53:40.155342    9659 api_server.go:165] Checking apiserver status ...
I0628 11:53:40.155383    9659 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0628 11:53:40.174625    9659 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0628 11:53:40.174661    9659 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0628 11:53:40.183622    9659 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0628 11:53:40.183636    9659 fix.go:129] unexpected machine state, will restart: <nil>
I0628 11:53:40.186439    9659 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I0628 11:53:40.190626    9659 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0628 11:53:40.190759    9659 start.go:306] post-start starting for "minikube" (driver="none")
I0628 11:53:40.190768    9659 start.go:316] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0628 11:53:40.190802    9659 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0628 11:53:40.196691    9659 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0628 11:53:40.196709    9659 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0628 11:53:40.196719    9659 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0628 11:53:40.199022    9659 out.go:177] * OS release is Ubuntu 18.04.6 LTS
I0628 11:53:40.200625    9659 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0628 11:53:40.200661    9659 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0628 11:53:40.200679    9659 start.go:309] post-start completed in 9.910622ms
I0628 11:53:40.200687    9659 fix.go:57] fixHost completed within 45.874189ms
I0628 11:53:40.200693    9659 start.go:81] releasing machines lock for "minikube", held for 45.895294ms
I0628 11:53:40.201060    9659 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0628 11:53:40.201087    9659 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0628 11:53:40.217419    9659 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0628 11:53:40.369857    9659 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0628 11:53:40.525802    9659 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0628 11:53:40.706160    9659 exec_runner.go:51] Run: sudo systemctl restart docker
I0628 11:53:41.001722    9659 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0628 11:53:41.014538    9659 out.go:177]
W0628 11:53:41.016405    9659 out.go:239] X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: File cri-docker.socket: Invalid argument

### Operating System

Ubuntu

**Comment by afbjorklund** [comment]
Same as:
* #14410

**Comment by spowelljr** [comment]
Going to close this issue to centralize these duplicated `cri-docker` issues in https://github.com/kubernetes/minikube/issues/14410. If you have any further questions or comments please leave them in https://github.com/kubernetes/minikube/issues/14410, thank you.
