### ISSUE TITLE
How to connect minikube's volume to docker automatically after minikube restart ?

### ISSUE THREAD

**Issue by zenpeaky** [kubernetes/minikube#14450]
### What Happened?

Hi community, I have a fiew container running on docker with command `--restart always -v /Users:/var/www/html` which /Users is volume that I create with `minikube start --mount-string="/Volumes/Zenpeaky/Code/Docker:/Users" --mount` but everytime I restart minikube, I have to manually restart the container to connect with the minikube's volume. Did I miss something or is there better way to do this ? Thanks

This is how I start minikube
```
# check if minikube has been started
if [[ $(echo $(minikube status -o json) | \
    grep -o '"[^"]*"\s*:\s*"[^"]*"' | \
    grep -E '^"(Host)"' | \
    sed 's/,$//') == '"Host":"Running"' ]]; then

    # minikube is started and ready to enable docker
    if [[ $(echo $(minikube status -o json) | \
    grep -o '"[^"]*"\s*:\s*"[^"]*"' | \
    grep -E '^"(DockerEnv)"' | \
    sed 's/,$//') != '"DockerEnv":"in-use"' ]]; then
        echo "🫖   Activating docker ..."
        eval $(minikube -p minikube docker-env)
        echo "☕️  Docker is ready"
    else
        echo "☕️  Docker is ready"
    fi

else
    # start minikube
    minikube start --mount-string="/Volumes/Zenpeaky/Code/Docker:/Users" --mount

    echo "🫖   Activating docker ..."
    eval $(minikube -p minikube docker-env)
    echo "☕️  Docker is ready"
fi
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8996692/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by klaases** [comment]
From your script I see that you are starting minikube with `minikube start`, but I don't see how you are later restarting minikube. Typically, I would do `minikube delete`, and then run start again.

It seems that you are running start again on an already running minikube?

**Comment by zenpeaky** [comment]
hi @klaases thanks for your response, ya I think I started minikube twice, I will close my issue since this doesn't affect me anymore
