### ISSUE TITLE
❌  Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1 stdout:  stderr: Failed to execute operation: No such file or directory

### ISSUE THREAD

**Issue by joshua143** [kubernetes/minikube#14457]
### What Happened?

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to execute operation: No such file or directory

### Attach the log file

minikube logs --file=logs.txt

### Operating System

Other

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @joshua143, thanks for reporting your issue with minikube.

Kubernetes v1.24 dropped support for Dockershim, so if you want to use the combination of the none driver, Kubernetes v1.24+, and the Docker container runtime you'll need to install cri-dockerd on your system, as listed in our [requirements page](https://minikube.sigs.k8s.io/docs/drivers/none/#requirements).

Other options include using a [different driver](https://minikube.sigs.k8s.io/docs/drivers/), using an older version of Kubernetes `--kubernetes-version`, or using a different container runtime `--container-runtime`.

Please try one of those solution and let me know if it resolves your issue, thanks

**Comment by spowelljr** [comment]
Hi @joshua143, just double checking that you're using the Docker driver.

If that's the case you likely created your current minikube cluster with a previous version of minikube and then you updated the minikube binary to v1.26.0 which tries to start `cri-docker`, but because your cluster was created with a previous version `cri-docker` isn't installed.

This should be easily resolvable by running `minikube delete --all` and then try starting minikube again, thanks

**Comment by robrich** [comment]
Just hit this as well.  I wish this issue was called out on the release's download page.

**Comment by afbjorklund** [comment]
It is theoretically possible to install cri-dockerd, when upgrading an old installation

**Comment by spowelljr** [comment]
@joshua143 & @robrich are both of you using the docker driver? Or are you perhaps using the none driver?

**Comment by spowelljr** [comment]
Going to close this issue to centralize these duplicated `cri-docker` issues in https://github.com/kubernetes/minikube/issues/14410. If you have any further questions or comments please leave them in https://github.com/kubernetes/minikube/issues/14410, thank you.

**Comment by robrich** [comment]
I'm using the `hyperv` driver.
