### ISSUE TITLE
Kubernetes get pod throwing ImagePullBackOff error

### ISSUE THREAD

**Issue by Abhijitrb** [kubernetes/minikube#14452]
### What Happened?

Kubernetes get pod throwing ImagePullBackOff error

During App build installation using "helm install command".

Have attached log with kubectl describe pods <Pod>

### Attach the log file

[ErrorLog.txt](https://github.com/kubernetes/minikube/files/8998389/ErrorLog.txt)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by klaases** [comment]
Hi @Abhijitrb, did you find the above comment helpful?

Are you still working on the issue or do you have any further questions?

Thanks

**Comment by klaases** [comment]
Hi @Abhijitrb – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
