### ISSUE TITLE
while installing minikube got error

### ISSUE THREAD

**Issue by asmimore** [kubernetes/minikube#14455]
### What Happened?

after minikube start got error

### Attach the log file

stderr:
Failed to execute operation: No such file or directory

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Redhat/Fedora

### Driver

None (Baremetal)

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by klaases** [comment]
Hi @[asmimore](https://github.com/asmimore) – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by asmimore** [comment]
hi klaases , thanks for your concern.It resolved

**Comment by klaases** [comment]
Hi @asmimore, thanks for your confirmation, and glad to hear it was resolved.
