### ISSUE TITLE
Version 1.26 no longer auto-mounts VirtualBox shared folders

### ISSUE THREAD

**Issue by adam-olema** [kubernetes/minikube#14465]
### What Happened?

After upgrading from 1.25.2 to 1.26.0, shared folders from the VirtualBox driver are no longer auto-mounted.  If this is expected behavior or requires new configs, I have not found any documentation to that effect.

Using:
- Mac OSX Monterey 12.4
- VirtualBox
- minikube upgraded by brew

In versions prior to 1.26, the "Shared Folders" setup in VirtualBox with "automount" set to true would be auto-mounted to / on bootup of the host container.  In 1.26 this no longer happens.  `minikube mount` does work, but this is not convenient and would prefer to use the host drivers anyway instead of 9p.

Tried a full `minikube delete` and fresh `minikube start`, with no improvement.

The default setup for VirtualBox is to share the users home directory.  In the past, minikube would automount this to /Users.

Adding more shared directories with "automount" would also result in them being automatically mounted in the root directory of the host container.

Note of this happens in 1.26.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9008848/log.txt)

Note log entries such as:

> I0629 01:38:28.203993   32538 main.go:134] libmachine: COMMAND: /usr/local/bin/VBoxManage sharedfolder add minikube --name Users --hostpath /Users --automount
> I0629 01:38:28.134845   32538 main.go:134] libmachine: COMMAND: /usr/local/bin/VBoxManage guestproperty set minikube /VirtualBox/GuestAdd/SharedFolders/MountPrefix /
> I0629 01:38:28.168837   32538 main.go:134] libmachine: COMMAND: /usr/local/bin/VBoxManage guestproperty set minikube /VirtualBox/GuestAdd/SharedFolders/MountDir /
> SharedFolderNameMachineMapping1="Users"
> SharedFolderPathMachineMapping1="/Users"

These are expected and are supposed to result in auto mounting, but do not.

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by adam-olema** [comment]
Downgrading back to 1.25.2 definitely fixes this problem.

**Comment by nwbt** [comment]
Same experience

OS: Mac OSX Monterey 12.3
VirtualBox: 6.1.34 r150636 (Qt5.6.3)

Downgrade to 1.25.2 worked as described (thanks)

**Comment by afbjorklund** [comment]
There were no changes done to libmachine or the virtualbox driver, but it could be something with the kernel perhaps.

**Comment by afbjorklund** [comment]
It was in that package you deleted

**Comment by vroetman** [comment]
I was working on building the iso image yesterday so I could test this, but it took a while to figure out how to build it.
I just pulled down minikube v1.26.1 again to test. I can run that above command without issues. I am on RHEL-8 running VirtualBox 6.1.36r152435.

You can see here that it is mounted:
```
% minikube ssh mount | grep vboxsf
hosthome on /hosthome type vboxsf (rw,relatime)
```
But I don't see `mount.vboxsf` on the system.

```
%  minikube ssh cat /etc/os-release
NAME=Buildroot
VERSION=2021.02.12-1-g379d09f-dirty
ID=buildroot
VERSION_ID=2021.02.12
PRETTY_NAME="Buildroot 2021.02.12"
```

**Comment by vroetman** [comment]
These are the steps I used:
```
% minikube version
minikube version: v1.26.1

% minikube -p test start minikube --driver=virtualbox
😄  [test] minikube v1.26.1 on Redhat 8.6
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node test in cluster test
🔥  Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
    ▪ Want kubectl v1.24.3? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "test" cluster and "default" namespace by default
commit: 1a5bb3e6850ca685fde7d4b07213e922680e9d2c-dirty

% minikube profile test
✅  minikube profile was successfully set to test

% minikube ssh ls /hosthome
ls: cannot access '/hosthome': No such file or directory
ssh: Process exited with status 2

% minikube ssh sudo mkdir /hosthome
% minikube ssh 'sudo mount -t vboxsf hosthome /hosthome'
% minikube ssh mount | grep vboxsf
hosthome on /hosthome type vboxsf (rw,relatime)
```

**Comment by vroetman** [comment]
> > commit: 1a5bb3e6850ca685fde7d4b07213e922680e9d2c-dirty
> 
> What does this commit reference?

Oh, I got minikube from conda-forge, so that is from the the minikube-feedstock repo.
https://github.com/conda-forge/minikube-feedstock/commit/1a5bb3e6850ca685fde7d4b07213e922680e9d2c

**Comment by vroetman** [comment]
That is strange. Were you using a virtualbox driver when you were testing it earlier, or some other driver? vboxsf is the shared filesystem driver for VirtualBox, so it would then make sense if it didn't work with another driver.

**Comment by afbjorklund** [comment]
> I never used `virtualbox`, I only use `qemu/kvm`.

Then why modify virtualbox ? Seems to be crashing here too.

```
VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1936 of file VBoxManageModifyVM.cpp
```

Possibly because it is no longer compatible with VirtualBox 6.1 ?

**Comment by vroetman** [comment]
> If the binary is not needed (which will make the fix easier, as it is only a matter of a service), what is the path which should be mounted?

I think the service is what is missing. The path is different depending on the host operating system (Linux, Mac, and Windows are all different). My little mount test is only showing that the vboxsf `hosthome` share is able to mount somewhere.

If you have a working branch, or make a PR, I can build the iso and test it.

**Comment by afbjorklund** [comment]
> At the beginning you said it did not boot then you were able to boot it?

It gave an error so I thought it failed, but in the end the boot was successful after all.

Maybe it was there all along, did not compare with how it worked with the old ISO...

Sorry for the mixed messages.

**Comment by vroetman** [comment]
I built and tested the iso from the PR, and left some comments. It doesn't work yet, but I think we are moving in the right direction.

**Comment by vroetman** [comment]
> What do you call by service: systemd service or `VBoxService`?
> Because the recipe is not the same if I need to get the `VBoxService` (even though in a first time I will extract it from the .iso and not build it from sources).

The `vboxservice.service` file calls the `VBoxService` program.

**Comment by mm0** [comment]
> Same problem on RHEL 8.6.
> 
> `minikube ssh 'sudo mkdir -p /hosthome; sudo mount -t vboxsf hosthome /hosthome'`
> 
> works, so the vboxsf drivers are working fine. It just doesn't mount automatically on start. The missing `VBoxService` may well be the problem.

This is now fixed as of 1.28 @vroetman 

> Adding more shared directories with "automount" would also result in them being automatically mounted in the root directory of the host container.

@adam-olema I don't see how this would be possible considering that VBoxService was [previously configured](https://github.com/kubernetes/minikube/blob/v1.25.2/deploy/iso/minikube-iso/package/vbox-guest/vboxservice.service#L14) to use the `--disable-automount` flag

**Comment by adam-olema** [comment]
> @adam-olema I don't see how this would be possible considering that VBoxService was [previously configured](https://github.com/kubernetes/minikube/blob/v1.25.2/deploy/iso/minikube-iso/package/vbox-guest/vboxservice.service#L14) to use the `--disable-automount` flag

Don't know why, but it did work in much earlier versions.  In any case, it works fine now :)

**Comment by vroetman** [comment]
> @adam-olema I don't see how this would be possible considering that VBoxService was [previously configured](https://github.com/kubernetes/minikube/blob/v1.25.2/deploy/iso/minikube-iso/package/vbox-guest/vboxservice.service#L14) to use the `--disable-automount` flag

I think minikube is explicitly doing the mounting in this particular case, not the VirtualBox automounter.

**Comment by vroetman** [comment]
@adam-olema, This is working for me now on RHEL-8. If it's working for you, I think you can close the issue.
