### ISSUE TITLE
Minikube startup error 

### ISSUE THREAD

**Issue by liyuwei-cute** [kubernetes/minikube#14464]
**重现问题所需的命令**：minikube start --vm-driver=none

**失败的命令的完整输出**：<details>
* Ubuntu 20.04 上的 minikube v1.26.0
* 根据现有的配置文件使用 none 驱动程序
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 20.04.3 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

* 
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

</details>

**`minikube logs`命令的输出**： <details>
* 
* ==> Audit <==
* |---------|------------------------------------------------------------------------|----------|------|---------|---------------------|----------|
| Command |                                  Args                                  | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------------------------------------------------------------|----------|------|---------|---------------------|----------|
| start   | --vm-driver=none                                                       | minikube | root | v1.26.0 | 29 Jun 22 15:44 CST |          |
| start   | --vm-driver=none                                                       | minikube | root | v1.26.0 | 29 Jun 22 15:44 CST |          |
|         | --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers |          |      |         |                     |          |
| start   | --vm-driver=none                                                       | minikube | root | v1.26.0 | 29 Jun 22 15:45 CST |          |
| start   | --vm-driver=none                                                       | minikube | root | v1.26.0 | 29 Jun 22 15:48 CST |          |
|         | --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers |          |      |         |                     |          |
| start   | --vm-driver=none                                                       | minikube | root | v1.26.0 | 29 Jun 22 15:48 CST |          |
| start   | --vm-driver=none                                                       | minikube | root | v1.26.0 | 29 Jun 22 15:53 CST |          |
|         | --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers |          |      |         |                     |          |
| start   | --force --driver=docker                                                | minikube | root | v1.26.0 | 29 Jun 22 15:56 CST |          |
| start   | --vm-driver=none                                                       | minikube | root | v1.26.0 | 29 Jun 22 15:56 CST |          |
| start   | --vm-driver=none                                                       | minikube | root | v1.26.0 | 29 Jun 22 16:12 CST |          |
| start   | --force --driver=docker                                                | minikube | root | v1.26.0 | 29 Jun 22 16:13 CST |          |
|---------|------------------------------------------------------------------------|----------|------|---------|---------------------|----------|

* 
* ==> Last Start <==
* Log file created at: 2022/06/29 16:13:35
Running on machine: liyuwei-virtual-machine
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0629 16:13:35.991540   23771 out.go:296] Setting OutFile to fd 1 ...
I0629 16:13:35.991709   23771 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0629 16:13:35.991713   23771 out.go:309] Setting ErrFile to fd 2...
I0629 16:13:35.991716   23771 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0629 16:13:35.991962   23771 root.go:329] Updating PATH: /root/.minikube/bin
W0629 16:13:35.992067   23771 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0629 16:13:35.992133   23771 out.go:303] Setting JSON to false
I0629 16:13:35.993118   23771 start.go:115] hostinfo: {"hostname":"liyuwei-virtual-machine","uptime":3389,"bootTime":1656487027,"procs":325,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.13.0-48-generic","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"f75f4d56-f422-8448-01c8-713ef45bc7dd"}
I0629 16:13:35.993172   23771 start.go:125] virtualization:  
I0629 16:13:35.993970   23771 out.go:177] * Ubuntu 20.04 上的 minikube v1.26.0
W0629 16:13:35.994640   23771 out.go:239] ! minikube skips various validations when --force is supplied; this may lead to unexpected behavior
W0629 16:13:35.994692   23771 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0629 16:13:35.994809   23771 notify.go:193] Checking for updates...
I0629 16:13:35.995176   23771 config.go:178] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.1
I0629 16:13:35.995590   23771 exec_runner.go:51] Run: systemctl --version
I0629 16:13:35.997436   23771 out.go:177] 
W0629 16:13:35.997883   23771 out.go:239] ! Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "none" driver, which is incompatible with requested "docker" driver.
W0629 16:13:35.997958   23771 out.go:239] * 建议：Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=none'
I0629 16:13:35.998325   23771 out.go:177] 

* 
* The control plane node must be running for this command
  To start a cluster, run: "minikube start"

</details>

**使用的操作系统版本**：Ubuntu 20.04.3 LTS

**Comment by klaases** [comment]
Hi, have you tried installing `cri-dockerd`? This may be the source of the error.

---

嗨，你试过安装 cri-dockerd 吗？这可能是错误的根源。

**Comment by spowelljr** [comment]
Hi @liyuwei-cute, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

-----

嗨@liyuwei-cute，我们还没有收到你的回复，你还有这个问题吗？
此问题中没有足够的信息使其可操作，并且已经过去了足够长的时间，因此此问题可能难以复制。

我将暂时关闭此问题，但当您准备好提供更多信息时，请随时重新打开。
