### ISSUE TITLE
Deprecate `storage-provisioner-gluster` addon

### ISSUE THREAD

**Issue by akhal3d96** [kubernetes/minikube#14469]
### What Happened?

This image doesn't exist

https://github.com/kubernetes/minikube/blob/319dd493820e517410fb2faa5255f549942de757/pkg/minikube/assets/addons.go#L191

```
NAME                                       READY   STATUS             RESTARTS   AGE
glusterfile-provisioner-59c9647cb6-7tdgx   1/1     Running            0          12m
glusterfs-54gfm                            0/1     ImagePullBackOff   0          3m36s
heketi-77585cd657-4nkzx                    1/1     Running            0          12m

```

```
  Warning  Failed     3m27s (x4 over 5m57s)  kubelet            Failed to pull image "quay.io/nixpanic/glusterfs-server:pr_fake-disk@sha256:3c58ae9d4e2007758954879d3f4095533831eb757c64ca6a0e32d1fc53fb6034": rpc error: code = Unknown desc = Error response from daemon: unauthorized: access to the requested resource is not authorized

```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9012617/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
It looks like the image repo that had that image is gone now. We're going to have to deprecate the addon unless we can get one of the maintainers of the addon to resurrect the image repo as I wasn't able to find an official replacement.

**Comment by Madhu-1** [comment]
cc @nixpanic

**Comment by nixpanic** [comment]
The location for the image was not intentionally removed, but it also isn't the right location. It seems I forgot to update it once [the PR was merged](https://github.com/gluster/gluster-containers/pull/95) in the [gluster-containers](https://github.com/gluster/gluster-containers) project.

The image `docker.io/gluster/gluster-centos:latest` would be more appropriate, although it seems that the Gluster Containers do not get updated (anymore?). I am happy to send a PR with the right image location. However, if you prefer to deprecate the addon, I understand that decision too.

**Comment by spowelljr** [comment]
Hi @nixpanic, thanks for the update, I'm happy to accept a PR that updates the location of the image.
