### ISSUE TITLE
Error when stopping Minikube on Docker

### ISSUE THREAD

**Issue by sketchysavage215** [kubernetes/minikube#14468]
### What Happened?

 % minikube stop
✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...
✋  Stopping node "minikube"  ...

❌  Exiting due to GUEST_STOP_TIMEOUT: docker container inspect minikube --format=: exit status 1
stdout:

stderr:
Error: No such container: minikube

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9011932/log.txt)
[logs.txt](https://github.com/kubernetes/minikube/files/9011933/logs.txt)
[minikube_stop_364c9ed6f3a23ff7ee941617a6b40c61124dc0a0_0.log](https://github.com/kubernetes/minikube/files/9011938/minikube_stop_364c9ed6f3a23ff7ee941617a6b40c61124dc0a0_0.log)
[minikube_logs_62b6c16b935b97a65023b44396e4da3ebada51f1_0.log](https://github.com/kubernetes/minikube/files/9011939/minikube_logs_62b6c16b935b97a65023b44396e4da3ebada51f1_0.log)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @sketchysavage215, thanks for reporting your issue with minikube.

Looking at your logs it looks like you're using a minikube v1.25.2 cluster with minikube v1.26.0 binary.

Could you try running `minikube delete --all` to clear out the existing clusters and then try starting minikube again and see if that resolves your issue, thanks

**Comment by spowelljr** [comment]
Glad that resolved your issue!
