### ISSUE TITLE
Make `docker` cruntime also look for `dockerd` & `cri-dockerd`

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#14460]
As suggested by @afbjorklund https://github.com/kubernetes/minikube/issues/14410#issuecomment-1169090487

We only check for `docker`, not `dockerd` & `cri-dockerd`, this will let the user know earlier on that they don't have all the requirements to run the `docker` container runtime.

**Comment by afbjorklund** [comment]
Note: the cri-dockerd server is only needed for k8s 1.24 and later, see the checks done when selecting CRI or not

**Comment by klaases** [comment]
Hi @afbjorklund, I was looking through the codebase when I found `.github/workflows/master.yml` which on line 509 states: `# cri-dockerd is required for Kubernetes 1.24 and higher for none driver`.

Per your comment above, does minikube already enforce k8s 1.24+ for `cri-dockerd`?

I am working on PR to address this issue: #14555,  and was curious whether I needed to manually check for k8s 1.24+.

**Comment by afbjorklund** [comment]
> Per your comment above, does minikube already enforce k8s 1.24+ for cri-dockerd?

It starts the service and configures the socket, but it does not installing for you

**Comment by klaases** [comment]
Hi @afbjorklund, thanks for your response, I've added a check for k8s >= 1.24 in #14555 which should resolve this.

**Comment by klaases** [comment]
Closing out for now as I have fixed this in #14555, thank you!

**Comment by DanielViniciusAlves** [comment]
Hi, so I'm trying to understand the workflow of the minikube project and since there are no Good First Issue open without someone already assign I'm going through closed issue. Could someone explain to me what was the problem and how it was fixed? I already read the pr that fixed but had some trouble understanding!
