### ISSUE TITLE
unable to start minikube

### ISSUE THREAD

**Issue by Anandkumarh25** [kubernetes/minikube#14462]
### What Happened?

i am trying to start the minikube but it always failed.

anhanuma@anhanuma-mac Downloads % minikube start
😄  minikube v1.26.0 on Darwin 11.6.4
✨  Automatically selected the docker driver
📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🤦  StartHost failed, but will try again: boot lock: timeout acquiring mutex
😿  Failed to start docker container. Running "minikube delete" may fix it: boot lock: timeout acquiring mutex

❌  Exiting due to GUEST_PROVISION: Failed to start host: boot lock: timeout acquiring mutex

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9006988/logs.txt)

### Operating System

macOS (Default)

**Comment by klaases** [comment]
In this case please try `minikube delete --all` to start fresh.

**Comment by klaases** [comment]
Hi @Anandkumarh25 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
