### ISSUE TITLE
Cannot access services since they get assigned 172.17.x.x IP addresses

### ISSUE THREAD

**Issue by CGavrila** [kubernetes/minikube#1447]
**Minikube version** (use `minikube version`): v0.17.1

**Environment**:
- **OS** (e.g. from /etc/os-release):
```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.1 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.1 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): `"DriverName": "virtualbox",`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): `"Boot2DockerURL": "file:///home/jmen/.minikube/cache/iso/minikube-v1.0.7.iso",`
- **Install tools**:
- **Others**:

**What happened**:
I have a very simple Hello World type of application that I am trying to run: one Redis service and one other deployment which just connects to it. However, it seems like I cannot reach the Redis service on its assigned 10.x.x.x port, even though env. variables have been created in the other pod. 

I can provide the `.yaml` files, I just didn't think they're very relevant in this case.

**What you expected to happen**:
Well, I would expect to be able to get to my Redis service from another container.

```
$ kubectl get endpoints
NAME           ENDPOINTS           AGE
kubernetes     10.0.2.15:8443      25d
poller-redis   172.17.0.6:6379     22d
```

```
$ kubectl get services
NAME           CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
kubernetes     10.0.0.1     <none>        443/TCP    25d
poller-redis   10.0.0.137   <none>        6379/TCP   22d
```

As you can see, `poller-redis` gets assigned a `172.17.x.x.` IP when looking at endpoints, but a 10.x.x.x IP when looking at services.

**How to reproduce it** (as minimally and precisely as possible):
Not sure, I only installed it and immediately tried to run this simple setup but couldn't. I'm pretty sure it's something specific to my machine, but I have no idea what it might be.

**Comment by aaron-prindle** [comment]
From the host machine you won't be able to access services inside of private k8s network.  You will need to use a nodeport service and you get access the service at $(minikube ip):Nodeport or look at the ip address returned for the service from `minikube service list`

**Comment by CGavrila** [comment]
@aaron-prindle I am not trying to access a service in the minikube cluster from my host machines. 

I am trying to get two pods to talk to each other - one is a Redis service and one a custom app. The `172.17.x.x` IP is being assigned to the Redis inside minikube.

**Comment by CGavrila** [comment]
Finally got it. The problem was that my labels were not matching:
