### ISSUE TITLE
Indicate `--network-plugin` flag is deprecated in flag description

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#14471]
`--network-plugin` is deprecated, `--cni` should be used instead, but if you do `minikube start --help` there's no indication that the flag is deprecated:
```
    --network-plugin='':
	Kubelet network plug-in to use (default: auto)
```

The description should be updated to indicate that the flag is deprecated and `--cni` should be used instead.

**Comment by afbjorklund** [comment]
The --network-plugin is still supported by Docker (only!), but it is recommended to switch to using a CNI plugin instead
