### ISSUE TITLE
Minikube didnt start

### ISSUE THREAD

**Issue by arpitmishra-eaton** [kubernetes/minikube#14477]
### What Happened?

when hitting command "minikube start" on local machine, getting the below error. However, i tried minikube delete and start again but didnt resolve the issue. 

Docker Desktop is installed. 

Error: minikube start
* minikube v1.26.0 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Updating the running docker "minikube" container ...
! This container is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.24.1 on Docker 20.10.17 ...
! Unable to restart cluster, will reset it: apiserver healthz: apiserver process never appeared
  - Generating certificates and keys ...
  - Booting up control plane ...
! initialization failed, will try again: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.24.1:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.24.1
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
        - 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock logs CONTAINERID'

stderr:
W0630 04:39:08.115388   20761 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
        [WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

  - Generating certificates and keys ...
  - Booting up control plane ...
*
X Error starting cluster: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.24.1:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.24.1
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
        - 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock logs CONTAINERID'

stderr:
W0630 04:43:10.333772   22525 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
        [WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

X Exiting due to K8S_KUBELET_NOT_RUNNING: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.24.1:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.24.1
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using the existing "sa" key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
        - 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock logs CONTAINERID'

stderr:
W0630 04:43:10.333772   22525 initconfiguration.go:120] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
        [WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

* Suggestion: Check output of 'journalctl -xeu kubelet', try passing --extra-config=kubelet.cgroup-driver=systemd to minikube start
* Related issue: https://github.com/kubernetes/minikube/issues/4172

### Attach the log file

[minikubelogs.txt](https://github.com/kubernetes/minikube/files/9016660/minikubelogs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by Tony-Sol** [comment]
Looks like have a same issue, but on macos

**Comment by Apocaly-pse** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

it helps me~ thx~~

**Comment by fujiahui** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

解决了我的问题。

**Comment by jeeinn** [comment]
my logs.
[minikubelogs.log](https://github.com/kubernetes/minikube/files/9117052/minikubelogs.log)

**Comment by maslke** [comment]
minikube version: v1.26.0 On Ubuntu 20.04.4 LTS，same issue.
This saved me.


> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

**Comment by cityiron** [comment]
good job.

**Comment by Mxiaoyu** [comment]
mac 系统，遇到同样问题，解决！

**Comment by OronDF343** [comment]
Same issue still exists on minikube v1.26.1, same fix of using previous Kubernetes v1.23.8 worked for me.

Tested on WSL2 (on both Debian 11.4 and Ubuntu 22.04 LTS, using a shared Docker socket running on Debian), and also the Hyper-V driver on Windows.
Host is Windows 10 21H2, connected to a corporate proxy (Windows authentication). Proxy environment variables configured correctly according to [documentation](https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/).

Has any contributor been able to reproduce this issue? It seems to be widespread judging by the number of reactions here and the number of similar/duplicate issues.

**Comment by l6l6ng** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

it help me!

**Comment by Drongerman** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

It works! Thanks!

**Comment by lunkaleung** [comment]
it really helps!

**Comment by BnkTCh** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

minikube can run but now it can not pull any image. 
I tried to run kubectl run nignx --image=nginx and I had  Error: ImagePullBackOff
Somebody knows what could be wrong?

**Comment by l6l6ng** [comment]
> > Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> > `minikube start --kubernetes-version=v1.23.8`
> 
> minikube can run but now it can not pull any image. I tried to run kubectl run nignx --image=nginx and I had Error: ImagePullBackOff Somebody knows what could be wrong?

minikube ssh
docker search nginx
then pull the nginx image?

**Comment by BnkTCh** [comment]
> > > Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> > > `minikube start --kubernetes-version=v1.23.8`
> > 
> > 
> > minikube can run but now it can not pull any image. I tried to run kubectl run nignx --image=nginx and I had Error: ImagePullBackOff Somebody knows what could be wrong?
> 
> minikube ssh docker search nginx then pull the nginx image?

No it can't pull any image, minikube is not reaching internet I don't know why :/
`bianca@kubernetes:~$ minikube ssh
docker@minikube:~$ docker search nginx
Error response from daemon: Get "https://index.docker.io/v1/search?q=nginx&n=25": dial tcp 44.206.182.67:443: i/o timeout
docker@minikube:~$ docker pull nginx
Using default tag: latest
Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

**Comment by Apocaly-pse** [comment]
> > > > Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> > > > `minikube start --kubernetes-version=v1.23.8`
> > > 
> > > 
> > > minikube can run but now it can not pull any image. I tried to run kubectl run nignx --image=nginx and I had Error: ImagePullBackOff Somebody knows what could be wrong?
> > 
> > 
> > minikube ssh docker search nginx then pull the nginx image?
> 
> No it can't pull any image, minikube is not reaching internet I don't know why :/ `bianca@kubernetes:~$ minikube ssh docker@minikube:~$ docker search nginx Error response from daemon: Get "https://index.docker.io/v1/search?q=nginx&n=25": dial tcp 44.206.182.67:443: i/o timeout docker@minikube:~$ docker pull nginx Using default tag: latest Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)`

maybe you need China mirror image, by adding `"registry-mirrors":["https://registry.docker-cn.com"]` in `~/.docker/daemon.json`.

**Comment by medyagh** [comment]
this is possible that you are upgrading kubernets version on an older minikube iso/base image,
I wish we could detect this on minikube side so the user be aware, but do you all mind trying 

minikube delete --all --purge
and then start minikube and see if it works ?

**Comment by ZoeLeee** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

it helps me!

**Comment by liangjihua** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`


Works for me! Thanks!

**Comment by xakoy** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

666

**Comment by organics2016** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

minikube v1.27.0 on Ubuntu 18.04 (vbox/amd64)
It works! Thanks!

**Comment by gxcuit** [comment]
same issue

**Comment by ScorpIan555** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

This worked for me as well.

**Comment by brettKK** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

fix my problem and it works.

**Comment by gobraves** [comment]
> minikube version: v1.26.0 On Ubuntu 20.04.4 LTS，same issue. This saved me.
> 
> > Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> > `minikube start --kubernetes-version=v1.23.8`

fix my problem and it works.

**Comment by xueh007** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

On macos, same issue. And it fix my problem. Further more, I try with kubernetes verison of 1.25.x and 1.24.x, no one works. Only version 1.23.x works.

**Comment by LizhenQiangCOOL** [comment]
> 

fix my problem and it works

**Comment by BassMonkey** [comment]
I would like to point out that using an older kubernetes version is a workaround and not a fix. @arpitmishra-eaton can you change this to a bug instead of a support question?

Or should we open a new bug for this?

**Comment by fkaanoz** [comment]
minikube delete --all --purge
minikube start

work for me! thank you @medyagh

**Comment by tweaknc** [comment]
This is fixed my issue Ubuntu 22.04 with minkube 1.29

**Comment by wbcny** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

It works for me

**Comment by h4rvey99** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

It works for me. Arch Linux with minikube 1.28.0

**Comment by MustacheXb** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

hope it help me!!!

**Comment by bobbyz007** [comment]
> I would like to point out that using an older kubernetes version is a workaround and not a fix. @arpitmishra-eaton can you change this to a bug instead of a support question?
> 
> Or should we open a new bug for this?

So have it been submitted as a bug to track?

**Comment by dusatvoj** [comment]
`minikube start --container-runtime=containerd`

**Comment by velvetzhero** [comment]
`minikube start --container-runtime=containerd` --> is working on ubuntu 22.04/docker 23.0.1

**Comment by Kaushik4852** [comment]
> > Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> > `minikube start --kubernetes-version=v1.23.8`
> 
> fix my problem and it works.

works like a charm

**Comment by Palak-1202** [comment]
> minikube version: v1.26.0 On Ubuntu 20.04.4 LTS，same issue. This saved me.
> 
> > Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> > `minikube start --kubernetes-version=v1.23.8`

Same here, using the latest version v1.25.2 caused the issue but it worked fine with v1.23.8

**Comment by KirylMi** [comment]
> minikube version: v1.26.0 On Ubuntu 20.04.4 LTS，same issue. This saved me.
> 
> > Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> > `minikube start --kubernetes-version=v1.23.8`

Thanks a lot!

**Comment by ayeshasiddiqs7** [comment]
> Using a specific version of kubectl worked for me. Apparently, Kubernetes version 1.24 was causing some issues for me.
> 
> `minikube start --kubernetes-version=v1.23.8`

Thanks a lot! Faced the same issue, this helped!
