### ISSUE TITLE
minikube with kvm2 driver doesn't work on ubuntu

### ISSUE THREAD

**Issue by matiasalessandrini** [kubernetes/minikube#14479]
### What Happened?

runnning "minikube start --driver=kvm2 I get this error:

minikube v1.26.0 on Ubuntu 20.04
✨  Using the kvm2 driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing kvm2 VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: ensuring active networks: recreating inoperable network mk-minikube: un-retryable: no free private network subnets found with given parameters (start: "192.168.43.0", step: 11, tries: 20)
🔄  Restarting existing kvm2 VM for "minikube" ...
😿  Failed to start kvm2 VM. Running "minikube delete" may fix it: driver start: ensuring active networks: recreating inoperable network mk-minikube: un-retryable: no free private network subnets found with given parameters (start: "192.168.43.0", step: 11, tries: 20)

❌  Exiting due to GUEST_PROVISION: Failed to start host: driver start: ensuring active networks: recreating inoperable network mk-minikube: un-retryable: no free private network subnets found with given parameters (start: "192.168.43.0", step: 11, tries: 20)

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │

### Attach the log file

❌  Exiting due to GUEST_KVM2_NO_DOMAIN: state: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')
💡  Suggestion: The VM that minikube is configured for no longer exists. Run 'minikube delete'
🍿  Related issue: https://github.com/kubernetes/minikube/issues/3636

### Operating System

Ubuntu

### Driver

KVM2

**Comment by medyagh** [comment]
@matiasalessandrini 

it seems like all network subnets minikube wanted to try are taken
```
 no free private network subnets found with given parameters 
```

I am curious if you bump the network tries from 20 to something larger like 100, will it fix the problem for you?

here is the part of the code
https://github.com/medyagh/minikube/blob/9da4671df32c59cd99b11ad274ede2caae28153a/pkg/drivers/kic/oci/network_create.go#L92

**Comment by medyagh** [comment]
@matiasalessandrini I am also curious if deleting minikube helps ?

minikube delete --all


/triage needs-information
/kind support

**Comment by medyagh** [comment]
> > @matiasalessandrini
> > it seems like all network subnets minikube wanted to try are taken
> > ```
> >  no free private network subnets found with given parameters 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I am curious if you bump the network tries from 20 to something larger like 100, will it fix the problem for you?
> > here is the part of the code https://github.com/medyagh/minikube/blob/9da4671df32c59cd99b11ad274ede2caae28153a/pkg/drivers/kic/oci/network_create.go#L92
> 
> I
> 
> > @matiasalessandrini I am also curious if deleting minikube helps ?
> > minikube delete --all
> > /triage needs-information /kind support
> 
> I already run this command and I'm still with the same issue. Which parameter should I send to allow 100 retries?

that is not configurable (but I would accept a PR that make this configurable)

**Comment by klaases** [comment]
If anyone in the the minikube community is interested in working on this please let us know.

**Comment by PapaLaplace** [comment]
In my case a simple workaround was to provide the "default" network (which should be present, given your kvm2 is properly installed). Just call `virsh net-list`, the output should look like this:
```
 Name      State    Autostart   Persistent
--------------------------------------------
 default   active   yes         yes
```
If the "default" network is present, you can start minikube using it:
`minikube start --driver kvm2 --network="default"`
Be sure to run `minikube delete --all` beforehand!

Surely this is not the best solution, but if you only use the kvm2 driver to run minikube, it should cause no problems. Also, this network has the same /24 mask just like the regular minikube network.
