### ISSUE TITLE
Improve Linux installation instructions

### ISSUE THREAD

**Issue by LenzGr** [kubernetes/minikube#14487]
The installation instructions for Linux on the [Get Started!](https://minikube.sigs.k8s.io/docs/start/) page could be slightly improved:
* For the RPM-based installation method, there is no need to download the RPM package via `curl` beforehand, one can simply do `rpm -Uhv https://storage.googleapis.com/minikube/releases/latest/minikube-latest.x86_64.rpm`.
* For DEB packages, the recommended tool to perform package installations nowadays is `apt` - it has a somewhat nicer UI and also takes care of resolving missing package dependencies automatically.

**Comment by afbjorklund** [comment]
I think we kept it as two steps, just to make the instructions similar between the two platforms. (deb/rpm)

Using apt and yum and is a long sad story, I don't think it will ever be properly supported with a repo etc...

**Comment by LenzGr** [comment]
> I think we kept it as two steps, just to make the instructions similar between the two platforms. (deb/rpm)

I personally prefer to minimize the effort and steps involved in getting something up and running, hence my suggestion. But if keeping these steps separate is preferred from a consistency point of view, feel free to reject the PR and this issue.

> Using apt and yum is a long sad story, I don't think it will ever be properly supported with a repository etc...

Well, making software available in the "native" packaging format is a great first step, especially for automated deployments.
