### ISSUE TITLE
minikube on podman fails to start

### ISSUE THREAD

**Issue by wskb** [kubernetes/minikube#14484]
### What Happened?

In summary v1.26.0 fails to start using this sequence:

    minikube delete --all --purge
    minikube config set driver podman
    # docker or cri-o produces same result
    minikube config set container-runtime docker
    minikube start

In detail, here's the `minikube start --alsologtostderr` [output](https://github.com/kubernetes/minikube/files/9024111/minikube.start.error.txt)

### Attach the log file

`minikube logs --file=log.txt` doesn't produce anything:

    >minikube logs --file=log.txt
    E0630 18:00:47.045210   66528 logs.go:192] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.24.1/kubectl 
    describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo 
    /var/lib/minikube/binaries/v1.24.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with 
    status 1
    stdout:

    stderr:
    The connection to the server localhost:8443 was refused - did you specify the right host or port?
    output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

    ❗  unable to fetch logs for: describe nodes

### Operating System

macOS (Default)

### Driver

Podman

**Comment by alias-dev** [comment]
This looks similar to https://github.com/kubernetes/minikube/issues/14400, does [this workaround](https://github.com/kubernetes/minikube/issues/14400#issuecomment-1171758619) work for you?

**Comment by wskb** [comment]
I was able to work around this issue by recreating my podman machine.

**Comment by klaases** [comment]
Hi @wskb, thanks for following up and acknowledging the solution to the issue, thanks.
