### ISSUE TITLE
Homebrew package not found

### ISSUE THREAD

**Issue by dseravalli** [kubernetes/minikube#1449]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Minikube version** (use `minikube version`): N/A

**Environment**:
- **OS** : OS X El Capitan 10.11.6
- **Install tools**: 
Homebrew 1.2.0-43-g29429df
Homebrew/homebrew-core (git revision 7b946; last commit 2017-05-03)

**What happened**:
`brew update && brew install minikube` =>
```
Already up-to-date.
Error: No available formula with the name "minikube"
==> Searching for a previously deleted formula...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.
```

**Comment by r2d4** [comment]
Sorry I updated this today - the command is actually `brew cask install minikube`.  I'll update the docs
