### ISSUE TITLE
Unit file cri-docker.socket does not exist

### ISSUE THREAD

**Issue by sirajqs** [kubernetes/minikube#14501]
### What Happened?

Failed to enable unit: Unit file cri-docker.socket does not exist.

### Attach the log file

sudo systemctl enable cri-docker.socket: exit status 1

### Operating System

Ubuntu

### Driver

VMware

**Comment by sirajqs** [comment]
i m facing some problem while running the command
minikube start --vm-driver=none

**Comment by afbjorklund** [comment]
same as:
* https://github.com/kubernetes/minikube/issues/14410

**Comment by spowelljr** [comment]
I'm going to close this issue as it's a duplicate of https://github.com/kubernetes/minikube/issues/14410, please follow along there for solutions, thanks!
