### ISSUE TITLE
Building an ISO under linux/arm64 does not work

### ISSUE THREAD

**Issue by gilbahat** [kubernetes/minikube#14500]
### What Happened?

When trying to build the minikube ISO under linux/arm64 (either with or without docker), the build script will fail due to the lack of gcc-multilib. gcc-multilib is not available for arm64, see https://packages.ubuntu.com/bionic/gcc-multilib and https://packages.ubuntu.com/focal/gcc-multilib

### Attach the log file

log file not relevant ("package gcc-multilib has no installation candidate" is the only message worthy of note)

### Operating System

Ubuntu focal arm64

### Driver

N/A

**Comment by afbjorklund** [comment]
I don't think you need multilib, especially not for aarch64, can you try installing gcc instead ?

**Comment by afbjorklund** [comment]
Actually it seems that vagrant and VM is still the default build environment:

https://github.com/buildroot/buildroot/blob/master/support/misc/Vagrantfile

Most likely it only supports VirtualBox (maybe VMware), so no ARM support ?

The package selection and setup should be the same, no matter the environment.

**Comment by gilbahat** [comment]
> Note that you don't have to use the docker image, most of our builds were done on the host.
> https://minikube.sigs.k8s.io/docs/contrib/building/iso/ (basically you set IN_DOCKER=1)

Seems like it's ignored at least for the first part: 

root@fervent-archerfish:~/minikube# IN_DOCKER=1 make buildroot-image
docker build  -t gcr.io/k8s-minikube/buildroot-image -f deploy/iso/minikube-iso/Dockerfile deploy/iso/minikube-iso/
Sending build context to Docker daemon  602.6kB

(... snip ...)

The following additional packages will be installed:
  autoconf autotools-dev binutils binutils-common binutils-x86-64-linux-gnu
  cpp cpp-7 dpkg-dev fakeroot g++ g++-7 gcc gcc-7 gcc-7-base gcc-7-multilib
(...)
The following NEW packages will be installed:
  autoconf automake autotools-dev bc binutils binutils-common
  binutils-x86-64-linux-gnu build-essential cpio cpp cpp-7 dpkg-dev dumb-init
  fakeroot g++ g++-7 gcc gcc-7 gcc-7-base gcc-7-multilib gcc-multilib

so this won't pass on linux/arm64.

**Comment by afbjorklund** [comment]
Okay, that must have changed recently then...

**Comment by afbjorklund** [comment]
No, "Buildroot-image" is just for building the docker image

The real targets are something in "out" folder

**Comment by gilbahat** [comment]
> No, "Buildroot-image" is just for building the docker image (you can skip that step, if installing the required packages on host instead - tweaked for arm64)
> 
> The real targets are something in "out" folder

okay, that explains it. Either way - I tried upgrading to 2022.05 and for reasons unclear to me, the config would always be overridden with some parameters that are legacy, breaking the build. I fear that this needs someone more familiar with this codebase to fix this.

**Comment by nirs** [comment]
This works know - I can build on Fedora 43 both x86_64 and aarch64 (but the post-image script fails).

I did not try on Ubuntu/Debian.
