### ISSUE TITLE
Minikube cannot start with VirtualBox Backend

### ISSUE THREAD

**Issue by justgotthis** [kubernetes/minikube#14508]
I was trying multi node (just 2) and it is very unreliable as it fails either on the master or worker creation. I kept getting out of memory errors so I am trying to run with 8gb RAM for both. I also notice the setup process (mainly Docker and kubeadm) takes up a lot of CPU so I have been going with 6 cores to get to the end of the setup. These high values are weird because on the minikube site, it says it can run on 2 core and 2 gb RAM. My laptop has 32GB ram and plenty of CPUs btw. I am on windows 11 home edition (so no hyper v backend availability)

I tried docker backend but it does not do load balancer, node port and ingress. 

Anything i should look out for when using VirtualBox? Is there a way to control docker and kubeadm from using up so much CPU at setup? These pieces are really hindering me from completing the setup. I am using the latest minikube and virtualbox versions. Any help would be greatly appreciated.

-Luis.

**Comment by justgotthis** [comment]
Also, virtual box only works when i have virtual box open. If i have the application closed, it fails every time. Just another data point.

**Comment by klaases** [comment]
Hi @justgotthis, were you able to find a way to reduce the number of resources required? Maybe taking a look into virtual box settings?

2gb of memory should be sufficient for minikube.

/triage needs-information
/kind support

**Comment by justgotthis** [comment]
> Hi @justgotthis, were you able to find a way to reduce the number of resources required? Maybe taking a look into virtual box settings?
> 
> 2gb of memory should be sufficient for minikube.
> 
> /triage needs-information
> /kind support

Unfortunately I was unable to get it to work on Windows 10 Home Edition and Windows 11 Home Edition. I tried it with the default resources and with everything stopped on my laptop but it still did not work for me. VirtualBox provider is very buggy with minikube. It only works with single node. When you try to create multinode or join a new node, it gets stuck at the join. I used multiple versions of minikube and virtualbox including the latest versions of each but kept getting the same results. I sank so much time into it that i finally decided to go with Docker Desktop although now I'm missing Load Balancer capabilities since i need silly tunnel commands to duplicate that. I'm assuming Virtualbox and Minikube multinode only works on Windows 8 and below?

**Comment by klaases** [comment]
Hi @justgotthis, yes Minikube should work with VirtualBox on Windows 10, 11 as you have tried. I am not exactly sure what the issue may be but it seems that you are close to resolving it.

The following video for Windows shows multiple minikube nodes running:

How to run multiple minikube clusters and multiple node kubernetes cluster
https://www.youtube.com/watch?v=cMQY9kLwO-g

Is this of any use?

**Comment by justgotthis** [comment]
Thanks for the response. Although I am using Docker provider exclusively,
I'll take a look at the video.

**Comment by klaases** [comment]
Hi @justgotthis  – please let us know if you wanted to re-open, else closing out for now.

Welcome to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
