### ISSUE TITLE
 demarage minikube

### ISSUE THREAD

**Issue by kitoko123** [kubernetes/minikube#14514]
**Étapes pour reproduire le problème:** 

1. ouvrir powershell en tant qu'administrateur
2. saisir minikue start
3.

**Sortie complète de la commande `minikube logs`:**
<details>

[LOGs.txt](https://github.com/kubernetes/minikube/files/9045407/LOGs.txt)

</details>

**Comment by spowelljr** [comment]
Hi @kitoko123, thanks for reporting your issue with minikube.

It looks like you're trying to start an existing instance of minikube. If you do `minikube delete` and then try starting minikube again do you get a different error?

-----

Salut @kitoko123, merci d'avoir signalé votre problème avec minikube.

Il semble que vous essayez de démarrer une instance existante de minikube. Si vous faites "minikube delete", puis essayez de redémarrer minikube, obtenez-vous une autre erreur ?

**Comment by klaases** [comment]
Hi @kitoko123 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

---

Bonjour @kitoko123 - ce problème persiste-t-il ? Des détails supplémentaires sont-ils disponibles ? Si c'est le cas, n'hésitez pas à rouvrir le problème en commentant avec `/reopen`. Ce problème sera fermé car des informations supplémentaires n'étaient pas disponibles et un certain temps s'est écoulé.

Informations supplémentaires pouvant être utiles :

* Si le problème se produit avec la dernière version de minikube

* La ligne de commande de démarrage minikube exacte utilisée

* Joignez la sortie complète des journaux minikube, exécutez `minikube logs --file=logs.txt` pour créer un fichier journal

Merci de partager votre expérience!
