### ISSUE TITLE
minnikube error

### ISSUE THREAD

**Issue by amairyousuf** [kubernetes/minikube#14526]
### What Happened?

unable to run minikube start --vm-driver=none

### Attach the log file

* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   |                  | minikube | root | v1.26.0 | 08 Jul 22 06:04 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 06:06 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 06:06 UTC |          |
| start   |                  | minikube | root | v1.26.0 | 08 Jul 22 06:09 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/07/08 06:09:28
Running on machine: ip-172-31-18-59
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0708 06:09:28.079487    4046 out.go:296] Setting OutFile to fd 1 ...
I0708 06:09:28.079628    4046 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0708 06:09:28.079632    4046 out.go:309] Setting ErrFile to fd 2...
I0708 06:09:28.079638    4046 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0708 06:09:28.079849    4046 root.go:329] Updating PATH: /root/.minikube/bin
W0708 06:09:28.079952    4046 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0708 06:09:28.080063    4046 out.go:303] Setting JSON to false
I0708 06:09:28.080780    4046 start.go:115] hostinfo: {"hostname":"ip-172-31-18-59","uptime":656,"bootTime":1657259912,"procs":119,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.13.0-1029-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec290622-a5d1-8699-c024-8cc772fd71f2"}
I0708 06:09:28.080846    4046 start.go:125] virtualization: xen guest
I0708 06:09:28.084682    4046 out.go:177] * minikube v1.26.0 on Ubuntu 20.04 (xen/amd64)
I0708 06:09:28.087633    4046 config.go:178] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.1
I0708 06:09:28.087685    4046 driver.go:360] Setting default libvirt URI to qemu:///system
I0708 06:09:28.087959    4046 exec_runner.go:51] Run: systemctl --version
I0708 06:09:28.089505    4046 notify.go:193] Checking for updates...
I0708 06:09:28.092762    4046 out.go:177] * Using the none driver based on existing profile
I0708 06:09:28.095197    4046 start.go:284] selected driver: none
I0708 06:09:28.095211    4046 start.go:805] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.18.59 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0708 06:09:28.095289    4046 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0708 06:09:28.095309    4046 start.go:1541] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
W0708 06:09:28.092541    4046 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0708 06:09:28.095721    4046 cni.go:95] Creating CNI manager for ""
I0708 06:09:28.095731    4046 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0708 06:09:28.095743    4046 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.18.59 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0708 06:09:28.100685    4046 out.go:177] * Starting control plane node minikube in cluster minikube
I0708 06:09:28.103146    4046 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0708 06:09:28.103357    4046 cache.go:208] Successfully downloaded all kic artifacts
I0708 06:09:28.103425    4046 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
W0708 06:09:28.103498    4046 start.go:599] error starting host: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied
W0708 06:09:28.103829    4046 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0708 06:09:28.103838    4046 api_server.go:165] Checking apiserver status ...
I0708 06:09:28.103860    4046 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0708 06:09:28.153423    4046 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0708 06:09:28.153457    4046 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0708 06:09:28.166443    4046 out.go:177] * Deleting "minikube" in none ...
I0708 06:09:28.168895    4046 exec_runner.go:51] Run: sudo systemctl stop -f kubelet
W0708 06:09:28.178692    4046 none.go:151] couldn't force stop kubelet. will continue with kill anyways: sudo systemctl stop -f kubelet: exit status 5
stdout:

stderr:
Failed to stop kubelet.service: Unit kubelet.service not loaded.
I0708 06:09:28.178727    4046 exec_runner.go:51] Run: docker ps -a --filter=name=k8s_ --format={{.ID}}
I0708 06:09:28.210087    4046 none.go:185] Removing: [/var/tmp/minikube /etc/kubernetes/manifests /var/lib/minikube]
I0708 06:09:28.210147    4046 exec_runner.go:51] Run: sudo rm -rf /var/tmp/minikube /etc/kubernetes/manifests /var/lib/minikube
W0708 06:09:28.218284    4046 out.go:239] ! StartHost failed, but will try again: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied
I0708 06:09:28.218314    4046 start.go:614] Will try again in 5 seconds ...
I0708 06:09:33.218801    4046 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
W0708 06:09:33.219086    4046 out.go:239] * Failed to start none bare metal machine. Running "minikube delete" may fix it: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied
I0708 06:09:33.223391    4046 out.go:177]
W0708 06:09:33.226723    4046 out.go:239] X Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed to start host: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied
W0708 06:09:33.226840    4046 out.go:239] * Suggestion: Run 'sudo sysctl fs.protected_regular=0', or try a driver which does not require root, such as '--driver=docker'
W0708 06:09:33.226930    4046 out.go:239] * Related issue: https://github.com/kubernetes/minikube/issues/6391
I0708 06:09:33.230360    4046 out.go:177]

*
root@ip-172-31-18-59:/home/ubuntu#

### Operating System

Ubuntu

**Comment by spowelljr** [comment]
Hi @amairyousuf, thanks for reporting your issue with minikube.

Have you tried running `sudo sysctl fs.protected_regular=0`?

**Comment by klaases** [comment]
Hi @amairyousuf, did you have a chance to review the above comment?

**Comment by klaases** [comment]
Hi @amairyousuf  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
