### ISSUE TITLE
`minikube mount` doesn't work with clusters launched with the xhyve driver

### ISSUE THREAD

**Issue by boosh** [kubernetes/minikube#1452]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release):OSX 10.12.4
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.18.0.iso
- **Install tools**:
- **Others**:

**What happened**:
`minikube mount` doesn't share any files or directories into a minikube cluster launched with the `xhyve` driver on OSX.

**What you expected to happen**:
It would share files into the cluster.

**How to reproduce it** (as minimally and precisely as possible):
- Start a cluster with `minikube start --vm-driver=xhyve`
- Export env vars with `eval $(minikube docker-env)` in 2 terminals
- Run `minikube mount $(pwd)` in one
- In the other, run `minikube ssh`, then `cd /mount-9p`. Type `ls` and the directory is empty.

**Anything else do we need to know**:
No

**Comment by aaron-prindle** [comment]
Can you post the output of `minikube mount --v=9 $(pwd)`?

**Comment by boosh** [comment]
Sure, here it is:

```
Mounting /Users/me/projects/clients/my-service into /mount-9p on the minikubeVM
This daemon process needs to stay alive for the mount to still be accessible...
Found binary path at /usr/local/bin/docker-machine-driver-xhyve
Launching plugin server for driver xhyve
ufs starting
Plugin server listening at address 127.0.0.1:52625
() DBG | operation not supported by device
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/me/.minikube/machines/minikube/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.64.7 -o IdentitiesOnly=yes -i /Users/me/.minikube/machines/minikube/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:

sudo umount /mount-9p;
sudo rm -rf /mount-9p;

SSH cmd err, output: <nil>: umount: /mount-9p: not mounted

(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /Users/me/.minikube/machines/minikube/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@192.168.64.7 -o IdentitiesOnly=yes -i /Users/me/.minikube/machines/minikube/id_rsa -p 22] /usr/bin/ssh <nil>}
About to run SSH command:

sudo mkdir /mount-9p;
sudo mount -t 9p -o trans=tcp -o port=5640 -o uid=1001 -o gid=1001 192.168.64.1 /mount-9p;
sudo chmod 775 /mount-9p;
```

**Comment by aaron-prindle** [comment]
@boosh are you still experiencing this error?  We have released a few bug fixes to mount since then.  I don't see anything from the logs, can you verify that xhyve is using the 192.168.64.1 network interface?  Also can you check that the directory is mounted by running `minikube ssh -- mount | grep 9p`?

**Comment by boosh** [comment]
@aaron-prindle I've just confirmed this still affects minikube v0.19.1
