### ISSUE TITLE
Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1

### ISSUE THREAD

**Issue by ganesshi** [kubernetes/minikube#14537]
### What Happened?

[root@k8s-machine ~]# minikube start --vm-driver=none
😄  minikube v1.26.0 on Centos 7.9.2009
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is CentOS Linux 7 (Core)

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to execute operation: No such file or directory

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

[root@k8s-machine ~]#

### Attach the log file

[root@k8s-machine ~]# cat logs.txt
*
* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|---------------------|
| Command |       Args       | Profile  | User | Version |     Start Time      |      End Time       |
|---------|------------------|----------|------|---------|---------------------|---------------------|
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 19:19 IST |                     |
| start   |                  | minikube | root | v1.26.0 | 08 Jul 22 19:19 IST |                     |
| start   |                  | minikube | root | v1.26.0 | 08 Jul 22 19:20 IST |                     |
| start   |                  | minikube | root | v1.26.0 | 08 Jul 22 19:23 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 19:23 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 19:25 IST |                     |
| delete  |                  | minikube | root | v1.26.0 | 08 Jul 22 19:26 IST | 08 Jul 22 19:26 IST |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 19:26 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 19:31 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 19:43 IST |                     |
| start   |                  | minikube | root | v1.26.0 | 08 Jul 22 21:33 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 21:33 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 21:35 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 22:26 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 22:28 IST |                     |
| start   |                  | minikube | root | v1.26.0 | 08 Jul 22 22:28 IST |                     |
| start   |                  | minikube | root | v1.26.0 | 08 Jul 22 22:30 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 22:30 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 08 Jul 22 22:35 IST |                     |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 09 Jul 22 09:56 IST |                     |
|---------|------------------|----------|------|---------|---------------------|---------------------|

*
* ==> Last Start <==
* Log file created at: 2022/07/09 09:56:15
Running on machine: k8s-machine
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0709 09:56:15.325997   19991 out.go:296] Setting OutFile to fd 1 ...
I0709 09:56:15.326951   19991 out.go:348] isatty.IsTerminal(1) = true
I0709 09:56:15.326961   19991 out.go:309] Setting ErrFile to fd 2...
I0709 09:56:15.326969   19991 out.go:348] isatty.IsTerminal(2) = true
I0709 09:56:15.327356   19991 root.go:329] Updating PATH: /root/.minikube/bin
W0709 09:56:15.327541   19991 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0709 09:56:15.327714   19991 out.go:303] Setting JSON to false
I0709 09:56:15.332307   19991 start.go:115] hostinfo: {"hostname":"k8s-machine","uptime":41329,"bootTime":1657299446,"procs":132,"os":"linux","platform":"centos","platformFamily":"rhel","platformVersion":"7.9.2009","kernelVersion":"3.10.0-1160.66.1.el7.x86_64","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"6ee72542-43dd-b9e4-f5d3-27c0348c07ea"}
I0709 09:56:15.332382   19991 start.go:125] virtualization:
I0709 09:56:15.358449   19991 out.go:177] 😄  minikube v1.26.0 on Centos 7.9.2009
W0709 09:56:15.370826   19991 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0709 09:56:15.370870   19991 notify.go:193] Checking for updates...
I0709 09:56:15.371381   19991 config.go:178] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.1
I0709 09:56:15.371908   19991 exec_runner.go:51] Run: systemctl --version
I0709 09:56:15.374593   19991 driver.go:360] Setting default libvirt URI to qemu:///system
I0709 09:56:15.382933   19991 out.go:177] ✨  Using the none driver based on existing profile
I0709 09:56:15.393298   19991 start.go:284] selected driver: none
I0709 09:56:15.393314   19991 start.go:805] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:10.203.105.60 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0709 09:56:15.393443   19991 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0709 09:56:15.394922   19991 cni.go:95] Creating CNI manager for ""
I0709 09:56:15.394934   19991 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0709 09:56:15.394952   19991 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:10.203.105.60 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0709 09:56:15.405008   19991 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0709 09:56:15.409868   19991 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0709 09:56:15.410308   19991 cache.go:208] Successfully downloaded all kic artifacts
I0709 09:56:15.410362   19991 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0709 09:56:15.411572   19991 start.go:356] acquired machines lock for "minikube" in 1.14963ms
I0709 09:56:15.411595   19991 start.go:94] Skipping create...Using existing machine configuration
I0709 09:56:15.411615   19991 fix.go:55] fixHost starting: m01
W0709 09:56:15.411888   19991 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0709 09:56:15.411908   19991 api_server.go:165] Checking apiserver status ...
I0709 09:56:15.412203   19991 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0709 09:56:15.457468   19991 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0709 09:56:15.457750   19991 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0709 09:56:15.480471   19991 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0709 09:56:15.480487   19991 fix.go:129] unexpected machine state, will restart: <nil>
I0709 09:56:15.484948   19991 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0709 09:56:15.500920   19991 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0709 09:56:15.501114   19991 start.go:306] post-start starting for "minikube" (driver="none")
I0709 09:56:15.501121   19991 start.go:316] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0709 09:56:15.501165   19991 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0709 09:56:15.516399   19991 main.go:134] libmachine: Couldn't set key CPE_NAME, no corresponding struct field found
I0709 09:56:15.516421   19991 main.go:134] libmachine: Couldn't set key , no corresponding struct field found
I0709 09:56:15.516431   19991 main.go:134] libmachine: Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
I0709 09:56:15.516440   19991 main.go:134] libmachine: Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
I0709 09:56:15.516449   19991 main.go:134] libmachine: Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
I0709 09:56:15.516457   19991 main.go:134] libmachine: Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
I0709 09:56:15.516465   19991 main.go:134] libmachine: Couldn't set key , no corresponding struct field found
I0709 09:56:15.523391   19991 out.go:177] ℹ️  OS release is CentOS Linux 7 (Core)
I0709 09:56:15.534890   19991 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0709 09:56:15.534935   19991 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0709 09:56:15.534950   19991 start.go:309] post-start completed in 33.827888ms
I0709 09:56:15.534958   19991 fix.go:57] fixHost completed within 123.356578ms
I0709 09:56:15.534962   19991 start.go:81] releasing machines lock for "minikube", held for 123.380315ms
I0709 09:56:15.535532   19991 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0709 09:56:15.535552   19991 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0709 09:56:15.566583   19991 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0709 09:56:15.651534   19991 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0709 09:56:15.720639   19991 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0709 09:56:15.786833   19991 exec_runner.go:51] Run: sudo systemctl restart docker
I0709 09:56:16.729051   19991 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0709 09:56:16.761023   19991 out.go:177]
W0709 09:56:16.767933   19991 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to execute operation: No such file or directory

W0709 09:56:16.767965   19991 out.go:239]
W0709 09:56:16.768860   19991 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0709 09:56:16.811092   19991 out.go:177]

*
[root@k8s-machine ~]#

### Operating System

Other

**Comment by klaases** [comment]
Hi @ganesshi, have you tried installing `cri-dockerd` as shown below:

`❌ Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1`

**Comment by afbjorklund** [comment]
Same issue as:
* https://github.com/kubernetes/minikube/issues/14410

**Comment by klaases** [comment]
Hi @ganesshi, you're going to want to install cri-dockerd, please take a look at this comment:

https://github.com/kubernetes/minikube/issues/14410#issuecomment-1193323463

For more information.

Thank you for sharing your experience!

/triage needs-information
/kind support
