### ISSUE TITLE
minikube --cni does not delete the origin cni config file

### ISSUE THREAD

**Issue by kubefay** [kubernetes/minikube#14536]
### What Happened?

minikube start --driver kvm2 --registry-mirror=https://registry.docker-cn.com --image-mirror-country cn --extra-config=kubelet.cgroup-driver=systemd --kubernetes-version=v1.18.8 -n 1 --cni=kubefay.yaml --network-plugin='cni' -v 5

when use the above command to start cluster in specific CNI yaml file, the cluster **started with the default cni bridge**. The cni config at **/etc/cni/net.d/87-podman-bridge.conflist** is not deleted. The CNI developer may hope a cluster with out any other cni config file when use --cni flag.

I find it that the 87-podman-bridge.conflist are created at minikube iso build stage, the makefile, deploy/iso/minikube-iso/package/podman/podman.mk , just create the conf file. Is it necessary to make cni conf in podman setting up stage?
![image](https://user-images.githubusercontent.com/28134721/178089832-dbd27b2b-f9e8-478d-bca9-b631c179beeb.png)

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9075700/log.txt)

### Operating System

Ubuntu

### Driver

KVM2

**Comment by afbjorklund** [comment]
This is a known issue, the podman files conflict with the kubernetes files. They are supposed to not be used, by setting a different cni configuration. But it would be better to change the podman configuration, to use another directory for the podman cni.

* https://github.com/kubernetes/minikube/issues/11194

Especially with 1.24, when cni config works "differently"
