### ISSUE TITLE
Minikube failed to start with 2 error

### ISSUE THREAD

**Issue by nissanist** [kubernetes/minikube#14532]
### What Happened?

Device: Lenevo E480 (Laptop)
OS: Ubuntu 20.04.4 LTS
use command for start : minikube start 
gettring 2 error: 
      error1: Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
      error2: Failed to enable unit: Unit file cri-docker.socket does not exist

Log file attached 

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9074471/logs.txt)

### Operating System

Ubuntu

**Comment by klaases** [comment]
Hi @nissanist, have you tried installing `cri-dockerd`?

https://github.com/Mirantis/cri-dockerd

**Comment by klaases** [comment]
Hi @nissanist  – here is some additional installation information: https://github.com/kubernetes/minikube/issues/14410#issuecomment-1193323463

---

If needed, please feel free to re-open the issue by commenting with /reopen. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

Whether the issue occurs with the latest minikube release

The exact minikube start command line used

Attach the full output of minikube logs, run minikube logs --file=logs.txt to create a log file

Thank you for sharing your experience!
