### ISSUE TITLE
Refactor release job to release both minikube and minikube.iso at the same time

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1454]
The minikube.iso now inherits its version from the minikube binary for simpler versioning.  However, that means that releasing the minikube.iso must happen in tandem with the minikube binaries.  Our release process only handled uploading the minikube binaries, but now must do both at the same time.  Here's the proposed refactor.

**Current Process**:

0. Build and upload minikube.iso with new version
1. Send PR with changelog and bumped version
2. Run release job
2a. Build and release minikube binaries
2b. Send PR: Add release to releases.json
2c. Upload github release

**Proposed Process**
1. Run release job:
1a. Send PR: Bump minikube version and add release to releases.json
1b. Build and upload minikube.iso, minikube binaries
1c. Send PR with bumped version and releases.json updates
1d. Upload github release in *draft* form
2. Add changelog commit to PR (could attempt to auto-generate this in step 1c)

**Comment by aaron-prindle** [comment]
ref: #916
