### ISSUE TITLE
Limit size of audit log

### ISSUE THREAD

**Issue by oprudkyi** [kubernetes/minikube#14543]
### What Happened?

after updating to v1.26 spotted the slowness of 'minikube kubectl' command
investigation shows that audit.json was greater 5mb and that causes real slowness for every command

```
>time minikube options
minikube options  16.86s user 2.37s system 266% cpu 7.219 total
```

deletion of audit.json speedup things considerably 
```
minikube options  0.03s user 0.03s system 91% cpu 0.064 total
```

probably audit.json should have limit on max size and truncated when needed 

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by afbjorklund** [comment]
It should only be slower the first time after a Kubernetes version upgrade, while the client binary (kubectl) is being downloaded... After that, it should be cached and the same as running it directly.

**Comment by oprudkyi** [comment]
deletion of /home/user/.minikube/logs/* helped, autdit.json file was something like 5mb and probably updating of that file created such slow work

**Comment by spowelljr** [comment]
Can confirm it takes a while with a large audit file, I'm going to find exactly what part is a long time and see if I can optimize any, will likely cap the log count as well
