### ISSUE TITLE
❌  Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error creating directory: /etc/kubernetes: mkdir /etc/kubernetes: permission denied

### ISSUE THREAD

**Issue by Sidhant-MT** [kubernetes/minikube#14557]
### What Happened?

[logs.txt](https://github.com/kubernetes/minikube/files/9090604/logs.txt)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9090607/logs.txt)

### Operating System

MAC OS

**Comment by klaases** [comment]
Hi @Sidhant-MT – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
