### ISSUE TITLE
StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds

### ISSUE THREAD

**Issue by urvashichoubey-dev** [kubernetes/minikube#14558]
### What Happened?

! StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds
E0712 14:39:46.341176   17280 main.go:130] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".

### Attach the log file

[minikube_logs_897b957174bfa6fff433509624fd7b095f76f55a_0.log](https://github.com/kubernetes/minikube/files/9091487/minikube_logs_897b957174bfa6fff433509624fd7b095f76f55a_0.log)

### Operating System

Windows

**Comment by klaases** [comment]
Hi @urvashichoubey-dev, are you still experiencing this issue?

Please try `minikube delete --all` and do let us know if this helps.
