### ISSUE TITLE
Switch to Kubeadm

### ISSUE THREAD

**Issue by ethernetdan** [kubernetes/minikube#1456]
I'd like to propose adding the ability for minikube to deploy a self-hosted Kubernetes cluster. There are several reasons this would be useful:
- **Immediately consume Kubernetes releases.** Official hyperkube images can be used with self-hosting, allowing upgrades with a manifest change. Currently users have to wait for a minikube release which generally involves making manual changes to localkube and bumping dependencies.
- **Allow full Kubernetes customization.** Users would have the ability to use the Kubernetes API to modify the configuration of every cluster component.
- **Avoid localkube.** Running every cluster component in a single binary is an environment that is unique from basically any other Kubernetes setup out there. This variation can cause behavior differences that make developing with minikube less portable. As the original author of localkube I have no qualms saying it's probably time to move on, if self-hosting had been mature at the time I would have used it instead.

@aaronlevy @pires @luxas @dlorenc @philips - would be interesting to get your thoughts here

**Comment by dlorenc** [comment]
Thanks for getting this discussion started!

I see this as a few separate issues:

Should we retire localkube? I think we probably should, running everything in one process has been problematic and the work to keep up with upstream k8s is always ongoing.

Do we need to use a self hosted setup? I'm not sure about this. The main benefit would be potentially easier upgrades via manifest changes.

Another option is a simple single node setup based on hyperkube without any self hosting.

**Comment by dlorenc** [comment]
I'll also add that there is a lot of value in keeping a single command to start the cluster (the localkube part). This makes it easy to stand up clusters inside a single VM for CI workloads.

I don't think we should switch to something like having minikube run all the bash commands from Kubernetes The Hard Way inside a VM.

**Comment by pires** [comment]
Last time I checked, minikube didn't allow for multi-VM setup. If that's still the case, going self-hosted may bring very little gains, if any, at a higher cost when compared to just go the hyperkube way (as @dlorenc just suggested).

**Comment by luxas** [comment]
I think it would just be best to adopt kubeadm to run the k8s cluster inside of the VM initially.
Then kubeadm will provide self-hosting as an option and we can later decide whether it makes sense to do that or not -- it might probably do.

However, migrating from localkube is the first step and I think that should have the highest priority.
I'm opposed to going the hyperkube-deployment way, see: https://groups.google.com/forum/#!topic/kubernetes-dev/iBs-EBCQxq0 and https://github.com/kubernetes/kubernetes/pull/45360#issuecomment-300181323

Makes sense @dlorenc?

**Comment by dlorenc** [comment]
> I'm opposed to going the hyperkube-deployment way, see: https://groups.google.com/forum/#!topic/kubernetes-dev/iBs-EBCQxq0 and kubernetes/kubernetes#45360 (comment)

Can you explain this a little more? It looks like the problems around hyperkube are more related to the documentation and scripts for setting up a single-node cluster. We'd just be using the binary and wrapping it ourselves.

I think it's pretty important to keep a single process that can run in the foreground that runs and supervises all cluster components. I'm not sure kubeadm is designed for that case.

**Comment by luxas** [comment]
@dlorenc Ah, so you meant using the hyperkube binary/image only, not the "deployment" attached to it?
I see.

> I think it's pretty important to keep a single process that can run in the foreground that runs and supervises all cluster components. I'm not sure kubeadm is designed for that case.

The only mono-process we have is localkube. hyperkube isn't a monoprocess running everything-in-one. Instead, nearly everyone use kubelet for hosting the control plane (all three pieces run separately).

That's what kubeadm does as well. You'll just attach to the kubelet and it'll run everything else on top.

**Comment by dlorenc** [comment]
> The only mono-process we have is localkube. hyperkube isn't a monoprocess running everything-in-one. Instead, nearly everyone use kubelet for hosting the control plane (all three pieces run separately).

Right. We wouldn't need a mono-process, but a supervisor that can execute and stop the other processes. I think this is a unique need for minikube because users tend to start and stop their cluster/node very often.

**Comment by r2d4** [comment]
I'm definitely interesting in this, and I do think that we should move away from localkube to either bootkube or kubeadm.

> Immediately consume Kubernetes releases. Official hyperkube images can be used with self-hosting, allowing upgrades with a manifest change. Currently users have to wait for a minikube release which generally involves making manual changes to localkube and bumping dependencies.

We've actually been upgrading localkube in tandem with upstream k8s.  For both 1.5 and 1.6 we've released localkube binaries the day of the upstream release.  This is an important feature we'd like to keep.  I'm not familiar with the bootkube or kubeadm release processes, but it seems like we would be equally as blocked by either.  

> Allow full Kubernetes customization. Users would have the ability to use the Kubernetes API to modify the configuration of every cluster component.

I actually think we need to think about this one a little more.  We need a better plan on how we're going to expose kubernetes configuration through minikube.  Currently, we use this [method](https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md), which is tied closely to how localkube works.  

> Avoid localkube. Running every cluster component in a single binary is an environment that is unique from basically any other Kubernetes setup out there. This variation can cause behavior differences that make developing with minikube less portable. As the original author of localkube I have no qualms saying it's probably time to move on, if self-hosting had been mature at the time I would have used it instead.

Absolutely.  This has actually caused us a few issues with TPRs already.  https://github.com/kubernetes/minikube/issues/1252.  I think we should start working on prototypes of alternatives now, while we don't have any major blockers.  

The other concerns I have right now are stability - I think we can start the work of moving over to kubeadm or bootkube, but neither of these projects run integration tests as far as I know.

I think we could rework the interface that we currently have, `GetLogs`, `StartLocalkube`, etc. to support a different binary.  The release plan would probably be to support both localkube and alternative backends at first, and then later switch off of localkube fully.
