### ISSUE TITLE
minikube start error

### ISSUE THREAD

**Issue by zhengerkui** [kubernetes/minikube#14578]
**minikube start --driver=docker**：

**  minikube v1.18.1 on Darwin 11.3.1
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubectl: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubectl.sha256 Dst:/Users/wecash/.minikube/cache/linux/v1.20.2/kubectl.download Pwd: Mode:2 Umask:---------- Detectors:[0x39a0ac0 0x39a0ac0 0x39a0ac0 0x39a0ac0 0x39a0ac0 0x39a0ac0 0x39a0ac0] Decompressors:map[bz2:0x39a0ac0 gz:0x39a0ac0 tar.bz2:0x39a0ac0 tar.gz:0x39a0ac0 tar.xz:0x39a0ac0 tbz2:0x39a0ac0 tgz:0x39a0ac0 txz:0x39a0ac0 xz:0x39a0ac0 zip:0x39a0ac0] Getters:map[file:0xc00055c620 http:0xc00122f5c0 https:0xc00122f5e0] Dir:false ProgressListener:0x3965f70 Options:[0x1bd4240]}: invalid checksum: Error downloading checksum file: bad response code: 404

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**mac os pro M1**：

**Comment by little-hang** [comment]
I install mac-minikube by homebrew method: brew install minikube
and the problem has been solved

**Comment by klaases** [comment]
> I install mac-minikube by homebrew method: brew install minikube and the problem has been solved

Hi @zhengerkui, were you able to try `brew` to help provide a solution?

**Comment by spowelljr** [comment]
Hi @zhengerkui, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
