### ISSUE TITLE
getting error "unable to retrieve container logs for docker://" after minikube or machine restarts

### ISSUE THREAD

**Issue by vipulsharma27** [kubernetes/minikube#14577]
### What Happened?

I have created a cronjob which runs every 5 mins and keep 7 successful pods.
Till machine is up, logs are visible fine.
But when machine restarts, getting below error for older pods which were created when last time machine was up:
**unable to retrieve container logs for docker://6e0a0d4f20ec63ec1ced235905e4f17a1a49435745155c6916457ae4c5dd3dfa**

This does not come up for pods created after machine starts (current session)

This is how minikube and kubernetes were installed:

### updating machine
yum update -y

### installing, configuring and starting docker
yum install docker -y
usermod -a -G docker ec2-user
systemctl start docker.service
systemctl enable docker.service

#### installing and configuring minikube
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
install minikube-linux-amd64 /usr/local/bin/minikube
ln -s $(which minikube) /usr/local/bin/kubectl
eval $(minikube docker-env)

### starting minikube and exposing kubernetes dashboard using ec2-user
su - ec2-user -c "minikube start --driver docker"
su - ec2-user -c "kubectl delete -f https://raw.githubusercontent.com/kubernetes/dashboard/master/aio/deploy/recommended.yaml"
su - ec2-user -c "kubectl apply -f /home/ec2-user/kubernetes_dashboard_viewuser.yaml"
su - ec2-user -c "kubectl create namespace cxuser-test"
su - ec2-user -c "kubectl proxy --address 0.0.0.0 --accept-hosts '.*' &"

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9100495/log.txt)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by vipulsharma27** [comment]
Hi Team,

Any update??

**Comment by klaases** [comment]
Hi @vipulsharma27, is it possible that the name of the pods changes after restart?

Would you mind posting the code for the `cronjob` file?

/triage needs-information

**Comment by spowelljr** [comment]
Hi @vipulsharma27, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by RomanTG** [comment]
Same issue

**Comment by netoxp70** [comment]
I have the same problem in a Rest API
"unable to retrieve container logs for containerd://5218df92a044d616fdaeefc34a6564a7958d2b6341e806a72e4639e7ef36969f"
