### ISSUE TITLE
Add "service" command for qemu driver on M1

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#14580]
### What Happened?

the service command on Qemu driver on MacBook is not implemented

Per @afbjorklund  this could be done similar to Docker Driver port forwarding

https://github.com/medyagh/minikube/blob/5b91e27da6f81d89829ae50d2381a76f650db806/cmd/minikube/cmd/service.go#L149

### Attach the log file

none

**Comment by klaases** [comment]
Yes, I am following instructions on [minikube Start documentation](https://minikube.sigs.k8s.io/docs/start/) to create a service. This would be a good first step towards create a new service for QEMU.

**Blocked** - however these instructions are for INTEL CPU, and NOT M1/ARM64.

After doing some research, I located a similar issue ([link](https://github.com/kubernetes/minikube/issues/11107)).

1. Comment suggests to use the image `e2eteam/echoserver:2.2-linux-arm64` ([link](https://github.com/kubernetes/minikube/issues/11107#issuecomment-919742761)).

Create deployment:
```
$ kubectl create deployment echo1 --image=e2eteam/echoserver:2.2-linux-arm64
$ kubectl expose deployment echo1 --type=NodePort --port=3000
$ kubectl port-forward service/echo1 3000:3000
```

Pod is running:
```
$ kubectl get po -A
NAMESPACE              NAME                                         READY   STATUS             RESTARTS         AGE
default                echo1-577dc7f846-97hx6                       1/1     Running            0
```

Forward port:
```
kubectl port-forward service/echo1 3000:3000
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
Handling connection for 3000
```

Try accessing 127.0.0.1:3000, but an error occurred:
```
E0714 23:23:15.543574    6606 portforward.go:406] an error occurred forwarding 3000 -> 3000: error forwarding port 3000 to pod 4dd425f76f832f4d8bd8096312b5d6e3c0d3198c6e50c560f6ab6db6444bd34f, uid : exit status 1: 2022/07/15 06:23:15 socat[1760120] E connect(5, AF=2 127.0.0.1:3000, 16): Connection refused
E0714 23:23:15.544114    6606 portforward.go:234] lost connection to pod
```

Note: tried above on M1 Mac, not Linux as the image suggests. May try again when on Linux. But for this task we want to see it working on M1 Mac too.


2. Comment suggests `polyverse/node-echo-server` ([link](https://github.com/kubernetes/minikube/issues/11107#issuecomment-919742761)).

Create deployment:
```
$ kubectl create deployment poly1 --image=polyverse/node-echo-server
$ kubectl expose deployment poly1 --type=NodePort --port=3000
$ kubectl port-forward service/poly1 3000:3000
```

Pod is running:
```
default                poly1-6bfbdb98cc-2kmqd                       1/1     Running            0              81s
```

Port forward:
```
$ kubectl port-forward service/poly1 3000:3000
Forwarding from 127.0.0.1:3000 -> 3000
Forwarding from [::1]:3000 -> 3000
```

Connection refused:
```
Handling connection for 3000
E0714 23:31:59.871759    7269 portforward.go:406] an error occurred forwarding 3000 -> 3000: error forwarding port 3000 to pod 36c57a7668d3dce6135144cc32d7733dbe89d62d2a203480ce9b432468799023, uid : exit status 1: 2022/07/15 06:31:59 socat[1767779] E connect(5, AF=2 127.0.0.1:3000, 16): Connection refused
E0714 23:31:59.872052    7269 portforward.go:234] lost connection to pod
```

3. Comment suggests a custom image ([link](https://github.com/kubernetes/minikube/issues/11107#issuecomment-1059927768)).

```
$ kubectl create deployment hello-minikube --image=preslavmihaylov/kubehelloworld:latest
$ kubectl expose deployment hello-minikube --type=NodePort --port=3000
$ kubectl port-forward service/hello-minikube 3000:3000
$ kubectl get po -A
default                hello-minikube1-85dbb788f6-9865l             0/1     ErrImagePull       0              9m54s
```

**Question** - which image is intended to be used for M1/ARM64?

**Comment by klaases** [comment]
Thanks @medyagh for helping me to build an image for Mac M1/ARM64!

What is a service in Kubernetes?
- Port that points to a pod in Kubernetes, a pod that is running a server.
- hello-minikube is a simple server to say _hello-world_.

Create a new file `nginx.yaml`:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    app.kubernetes.io/name: proxy
spec:
  containers:
  - name: nginx
    image: nginx:stable
    ports:
      - containerPort: 80
        name: http-web-svc
        
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app.kubernetes.io/name: proxy
  ports:
  - name: name-of-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
```

Apply an Kubernetes pod & service configuration:
`kubectl apply -f nginx.yaml`

Login to pod:
`kubectl exec --stdin --tty nginx -- /bin/sh`

Get all pods:
`kubectl get pod -A`

Get pod state:
`kubectl get pod nginx`

Describe pod in detail:
`kubectl describe pod nginx`

Get service:
`kubectl get service`

Minikube services:
`minikube service list`

Minikube nginx service (opens in a new web browser):
`minikube service nginx-service`

**Clean Up**

Delete pod:
`kubectl delete pod nginx`

Delete service:
`kubectl delete service nginx-service`

**Comment by klaases** [comment]
Minikube service documentation reference:
https://minikube.sigs.k8s.io/docs/commands/service/

**Comment by medyagh** [comment]
this was done by @spowelljr
