### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by techpenit** [kubernetes/minikube#14584]
### What Happened?

😄  minikube v1.26.0 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
💨  For improved Docker performance, enable the overlay Linux kernel module using 'modprobe overlay'
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > index.docker.io/kicbase/sta...: 0 B [_______________________] ?% ? p/s 0s
    > index.docker.io/kicbase/sta...: 0 B [_______________________] ?% ? p/s 0s
    > gcr.io/k8s-minikube/kicbase...: 0 B [_______________________] ?% ? p/s 0s
    > index.docker.io/kicbase/sta...: 0 B [_______________________] ?% ? p/s 0s
E0714 15:48:08.100871   79090 cache.go:203] Error downloading kic artifacts:  failed to download kic base image or any fallback image
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.24.1 on Docker 20.10.17 ...
🤦  Unable to restart cluster, will reset it: apiserver health: apiserver healthz never reported healthy: cluster wait timed out during healthz check
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules .../ E0714 15:56:02.510345   79090 start.go:264] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.49.2:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 192.168.49.2:8443: i/o timeout]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition

### Attach the log file

controller-manager-minikube"
Jul 14 12:53:02 minikube kubelet[43870]: E0714 12:53:02.067120   43870 kubelet.go:1690] "Failed creating a mirror pod for" err="pods \"kube-apiserver-minikube\" already exists" pod="kube-system/kube-apiserver-minikube"
Jul 14 12:53:02 minikube kubelet[43870]: E0714 12:53:02.263547   43870 kubelet.go:1690] "Failed creating a mirror pod for" err="pods \"kube-scheduler-minikube\" already exists" pod="kube-system/kube-scheduler-minikube"
Jul 14 12:53:12 minikube kubelet[43870]: I0714 12:53:12.247703   43870 kuberuntime_manager.go:1095] "Updating runtime config through cri with podcidr" CIDR="10.244.0.0/24"
Jul 14 12:53:12 minikube kubelet[43870]: I0714 12:53:12.248343   43870 kubelet_network.go:60] "Updating Pod CIDR" originalPodCIDR="" newPodCIDR="10.244.0.0/24"
Jul 14 12:53:12 minikube kubelet[43870]: I0714 12:53:12.740243   43870 topology_manager.go:200] "Topology Admit Handler"
Jul 14 12:53:12 minikube kubelet[43870]: I0714 12:53:12.770782   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"lib-modules\" (UniqueName: \"kubernetes.io/host-path/1a0953be-18e2-49d1-ada4-425be29b7188-lib-modules\") pod \"kube-proxy-wzg7h\" (UID: \"1a0953be-18e2-49d1-ada4-425be29b7188\") " pod="kube-system/kube-proxy-wzg7h"
Jul 14 12:53:12 minikube kubelet[43870]: I0714 12:53:12.770823   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-proxy\" (UniqueName: \"kubernetes.io/configmap/1a0953be-18e2-49d1-ada4-425be29b7188-kube-proxy\") pod \"kube-proxy-wzg7h\" (UID: \"1a0953be-18e2-49d1-ada4-425be29b7188\") " pod="kube-system/kube-proxy-wzg7h"
Jul 14 12:53:12 minikube kubelet[43870]: I0714 12:53:12.770845   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-d7jqk\" (UniqueName: \"kubernetes.io/projected/1a0953be-18e2-49d1-ada4-425be29b7188-kube-api-access-d7jqk\") pod \"kube-proxy-wzg7h\" (UID: \"1a0953be-18e2-49d1-ada4-425be29b7188\") " pod="kube-system/kube-proxy-wzg7h"
Jul 14 12:53:12 minikube kubelet[43870]: I0714 12:53:12.770889   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"xtables-lock\" (UniqueName: \"kubernetes.io/host-path/1a0953be-18e2-49d1-ada4-425be29b7188-xtables-lock\") pod \"kube-proxy-wzg7h\" (UID: \"1a0953be-18e2-49d1-ada4-425be29b7188\") " pod="kube-system/kube-proxy-wzg7h"
Jul 14 12:53:13 minikube kubelet[43870]: I0714 12:53:13.201055   43870 topology_manager.go:200] "Topology Admit Handler"
Jul 14 12:53:13 minikube kubelet[43870]: I0714 12:53:13.207097   43870 topology_manager.go:200] "Topology Admit Handler"
Jul 14 12:53:13 minikube kubelet[43870]: I0714 12:53:13.273587   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-n7t25\" (UniqueName: \"kubernetes.io/projected/d146a028-c1ce-4e6d-a4aa-895bf755c9bc-kube-api-access-n7t25\") pod \"coredns-6d4b75cb6d-2r8xf\" (UID: \"d146a028-c1ce-4e6d-a4aa-895bf755c9bc\") " pod="kube-system/coredns-6d4b75cb6d-2r8xf"
Jul 14 12:53:13 minikube kubelet[43870]: I0714 12:53:13.273621   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/d146a028-c1ce-4e6d-a4aa-895bf755c9bc-config-volume\") pod \"coredns-6d4b75cb6d-2r8xf\" (UID: \"d146a028-c1ce-4e6d-a4aa-895bf755c9bc\") " pod="kube-system/coredns-6d4b75cb6d-2r8xf"
Jul 14 12:53:13 minikube kubelet[43870]: I0714 12:53:13.273637   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"config-volume\" (UniqueName: \"kubernetes.io/configmap/313eceb0-ca05-4218-a49d-2615402d1c7e-config-volume\") pod \"coredns-6d4b75cb6d-8xdwb\" (UID: \"313eceb0-ca05-4218-a49d-2615402d1c7e\") " pod="kube-system/coredns-6d4b75cb6d-8xdwb"
Jul 14 12:53:13 minikube kubelet[43870]: I0714 12:53:13.273663   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-625kc\" (UniqueName: \"kubernetes.io/projected/313eceb0-ca05-4218-a49d-2615402d1c7e-kube-api-access-625kc\") pod \"coredns-6d4b75cb6d-8xdwb\" (UID: \"313eceb0-ca05-4218-a49d-2615402d1c7e\") " pod="kube-system/coredns-6d4b75cb6d-8xdwb"
Jul 14 12:56:03 minikube kubelet[43870]: I0714 12:56:03.160328   43870 topology_manager.go:200] "Topology Admit Handler"
Jul 14 12:56:03 minikube kubelet[43870]: I0714 12:56:03.171174   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"tmp\" (UniqueName: \"kubernetes.io/host-path/be3bb2f6-3363-4bdd-baf8-10761642e316-tmp\") pod \"storage-provisioner\" (UID: \"be3bb2f6-3363-4bdd-baf8-10761642e316\") " pod="kube-system/storage-provisioner"
Jul 14 12:56:03 minikube kubelet[43870]: I0714 12:56:03.171208   43870 reconciler.go:270] "operationExecutor.VerifyControllerAttachedVolume started for volume \"kube-api-access-j4kj5\" (UniqueName: \"kubernetes.io/projected/be3bb2f6-3363-4bdd-baf8-10761642e316-kube-api-access-j4kj5\") pod \"storage-provisioner\" (UID: \"be3bb2f6-3363-4bdd-baf8-10761642e316\") " pod="kube-system/storage-provisioner"
Jul 14 12:58:00 minikube kubelet[43870]: W0714 12:58:00.306419   43870 sysinfo.go:203] Nodes topology is not available, providing CPU topology
Jul 14 13:03:00 minikube kubelet[43870]: W0714 13:03:00.300067   43870 sysinfo.go:203] Nodes topology is not available, providing CPU topology

* 
* ==> storage-provisioner [5c11c98bc858] <==
* I0714 12:56:03.717533       1 storage_provisioner.go:116] Initializing the minikube storage provisioner...
I0714 12:56:03.725680       1 storage_provisioner.go:141] Storage provisioner initialized, now starting service!
I0714 12:56:03.725717       1 leaderelection.go:243] attempting to acquire leader lease kube-system/k8s.io-minikube-hostpath...
I0714 12:56:03.736007       1 leaderelection.go:253] successfully acquired lease kube-system/k8s.io-minikube-hostpath
I0714 12:56:03.736172       1 controller.go:835] Starting provisioner controller k8s.io/minikube-hostpath_minikube_733ff1bb-718b-408b-9c43-3b84fdef70e9!
I0714 12:56:03.736962       1 event.go:282] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"k8s.io-minikube-hostpath", UID:"92153017-7469-4975-8cab-6cedaadb82c6", APIVersion:"v1", ResourceVersion:"417", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' minikube_733ff1bb-718b-408b-9c43-3b84fdef70e9 became leader
I0714 12:56:03.836639       1 controller.go:884] Started provisioner controller k8s.io/minikube-hostpath_minikube_733ff1bb-718b-408b-9c43-3b84fdef70e9!

**Comment by Pablompg** [comment]
Same error as me [here](https://github.com/kubernetes/minikube/issues/14618). What OS are you running? What command did you use to run minikube? Are you using docker as a driver or something else? Has docker worked fine for you before?

**Comment by spowelljr** [comment]
I see that it states it's using an `existing profile`, if you run `minikube delete` and then try starting it again does it result in a different error?

**Comment by klaases** [comment]
Hi @techpenit, have you tried deleting the minikube profile as suggested above?

If you have created multiple profiles, you can clear them all with `minikube delete --all`.

**Comment by spowelljr** [comment]
Hi @techpenit, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
