### ISSUE TITLE
CoreDNS fail to start on k8s v1.21.2 with minikube 1.26.0

### ISSUE THREAD

**Issue by ekersale** [kubernetes/minikube#14588]
### What Happened?

After upgrading from minikube 1.25.2 to 1.26.0 the k8s cluster does not initialize properly.

The pod coredns fail to start with the following error: 

`Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "fe730ceb2c951612ac1abcb13154f504640fada10852ccf03a570c4f75d38924": plugin type="bridge" name="crio" failed (add): failed to set bridge addr: could not add IP address to "cni0": permission denied`

We tried multiple times to delete minikube, reset docker etc... without any success.

Minikube cluster is created with the following: 

`ctlptl create cluster minikube --registry=ctlptl-registry --min-cpus=4 --kubernetes-version=v1.21.2
`

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9114030/log.txt)

### Operating System

Windows

### Driver

Docker

**Comment by urvashichoubey-dev** [comment]
Can you please provide solution the following.

**Comment by ekersale** [comment]
The only solution that we have for now is to rollback to minikube 1.25.2.

**Comment by klaases** [comment]
Hi @ekersale, we have updated minikube v1.27.0 to work with a newer version of kubernetes, would it be possible to try CoreDNS with the newer versions?

**Comment by ekersale** [comment]
Hello, it seems to have fix the issue.
