### ISSUE TITLE
Не устанавливается Addon Ingress  при использовании драйвера Parallels

### ISSUE THREAD

**Issue by Kishinskiy** [kubernetes/minikube#14593]
### Что произошло?

Пытаюсь установить аддон ingress но в итоге установка завершается ошибкой

❯ minikube addons enable ingress
    ▪ Используется образ k8s.gcr.io/ingress-nginx/controller:v1.2.1
    ▪ Используется образ k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
    ▪ Используется образ k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
🔎  Verifying ingress addon...

❌  Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

### Приложите логи

[logs.txt](https://github.com/kubernetes/minikube/files/9122863/logs.txt)

### Операционная система

macOS (Default)

### Драйвер

Parallels

**Comment by drobit** [comment]
hey @Kishinskiy 
can you check it with:
`export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.49.0/24,192.168.39.0/24`

**Comment by klaases** [comment]
> hey @Kishinskiy
> can you check it with:
> `export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.49.0/24,192.168.39.0/24`

Hi @Kishinskiy, did you have a chance to review @drobit's comment above?

---

Привет @Kishinskiy, у тебя была возможность просмотреть комментарий @drobit выше?

**Comment by klaases** [comment]
Hi @Kishinskiy – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

---

Привет @Kishinskiy - эта проблема все еще возникает? Доступны ли дополнительные детали? Если это так, пожалуйста, не стесняйтесь снова открыть проблему, комментируя `/reopen`. Этот вопрос будет закрыт, так как дополнительной информации не было и прошло некоторое время.

Дополнительная информация, которая может быть полезна:

* Возникает ли проблема с последним выпуском minikube

* Используемая точная командная строка запуска minikube

* Прикрепите полный вывод журналов minikube, запустите `minikube logs --file=logs.txt`, чтобы создать файл журнала.

Спасибо, что поделились своим опытом!
