### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by vivek625** [kubernetes/minikube#14594]
### What Happened?

minikube logs --file=log.txt

### Attach the log file

minikube logs --file=log.txt

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by vivek625** [comment]
same problem

**Comment by spowelljr** [comment]
Duplicate of https://github.com/kubernetes/minikube/issues/14595, closing
