### ISSUE TITLE
A11y: emoji use in log output

### ISSUE THREAD

**Issue by mwilc0x** [kubernetes/minikube#14603]
### What Happened?

Hi,

This is not an code specific issue but feedback from a blind developer friend using the software:

"The use of emojis in the output logs makes using this software more challenging for me."

Thanks

### Attach the log file

N/A

**Comment by afbjorklund** [comment]
Sorry to hear that, it is possible to disable the emoji output using `$MINIKUBE_IN_STYLE`:

https://minikube.sigs.k8s.io/docs/faq/#can-i-get-rid-of-the-emoji-in-minikubes-output

**Comment by afbjorklund** [comment]
If someone else is wondering about "ally", it is about accessibility: https://www.a11yproject.com/

**Comment by klaases** [comment]
Hi @mwilc0x, were you able to disable the emojis as @afbjorklund suggested?

---

Please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Thank you for sharing your experience!
