### ISSUE TITLE
Wrong CPU emulation on minikube qemu driver

### ISSUE THREAD

**Issue by gilbahat** [kubernetes/minikube#14607]
### What Happened?

For some reason unclear to me, qemu will default to emulated CPU when running under minikube:

➜  ~ minikube ssh
(snipped)
$ cat /proc/cpuinfo |grep -i model
model		: 107
model name	: QEMU Virtual CPU version 2.5+
model		: 107
model name	: QEMU Virtual CPU version 2.5+

this is the command line that generated this machine:

➜  ~ ps aux | grep -i qemu
gilbahat         12640  83.6 25.0 40808748 4196160   ??  R     8:02PM 133:03.40 qemu-system-x86_64 -display none -accel hvf -m 6144 -smp 2 -boot d -cdrom /Users/gilbahat/.minikube/machines/minikube/boot2docker.iso -qmp unix:/Users/gilbahat/.minikube/machines/minikube/monitor,server,nowait -pidfile /Users/gilbahat/.minikube/machines/minikube/qemu.pid -nic user,model=virtio,hostfwd=tcp::64985-:22,hostfwd=tcp::64986-:2376,hostname=minikube -daemonize /Users/gilbahat/.minikube/machines/minikube/disk.qcow2

qemu docs suggest the default would be to use the host cpu.
in particular on my system, this caused disabling of AVX flags which stopped mongo 5 from working, but this can have any other potentially undesirable side effects as host is recommended according to qemu docs.

➜  ~ qemu-system-x86_64 --version
QEMU emulator version 7.0.0
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

perhaps it is better to explicitly pass a -cpu host flag to qemu-system-x86_64?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9135201/log.txt)

### System

MacBook Pro (15-inch, 2018)

### Operating System

macOS (monterey) x86_64

### Driver

qemu

**Comment by afbjorklund** [comment]
> perhaps it is better to explicitly pass a -cpu host flag to qemu-system-x86_64?

Sounds reasonable, the only issue seen so far was that it is not available on all OS.

**Comment by afbjorklund** [comment]
Sure, but no need to list all the exotic OS... Just enable it for "linux" and "darwin" when the arch matches ?

**Comment by gilbahat** [comment]
> Sure, but no need to list all the exotic OS... Just enable it for "linux" and "darwin", when the arch matches ?

I agree - if we don't have all the details as it's preferable to totally breaking support for an OS, however exotic.
Then again, I'd like to consider 'host' the real default and avoid using it only when there's a reason not to because it has downsides.

**Comment by afbjorklund** [comment]
It is only semi-supported on macOS and Darwin, making qemu work on Windows is a work-in-progress still...
NetBSD works (but nobody uses it), and FreeBSD is currently lacking acceleration (ever since kqemu died)

**Comment by afbjorklund** [comment]
```go
            switch runtime.GOOS {
            case ""linux", "darwin":
                    qemuMachine = ""
                    qemuCPU = "host"
            default:
                    qemuMachine = "" // default
                    qemuCPU = ""     // default
            }
```
