### ISSUE TITLE
X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1 stdout:  stderr: Failed to enable unit: Unit file cri-docker.socket does not exist.

### ISSUE THREAD

**Issue by baibhavas** [kubernetes/minikube#14611]
### What Happened?

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

### Attach the log file

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

### Operating System

Ubuntu

**Comment by klaases** [comment]
Hi @baibhavas, yes, I am working on. PR (#14555) to help improve this error message.

But to solve this situation, please install cri-dockerd:
https://github.com/Mirantis/cri-dockerd#build-and-install

**Comment by klaases** [comment]
Hi @baibhavas, the PR above #14555 has now been merged, please update to the latest version of minikube.

Also, were you able to install cri-dockerd?

**Comment by klaases** [comment]
Hi @baibhavas  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
