### ISSUE TITLE
Incorrectly formatted error message

### ISSUE THREAD

**Issue by ashok-arora** [kubernetes/minikube#14619]
### What Happened?

I ran `minikube service hello-node` and received the following message:
```
E0721 15:30:50.857211    1168 main.go:130] libmachine: [stderr =====>] : Hyper-V\Get-VM : You do not have the required permission to complete this task. Contact the
administrator of the authorization policy for the computer 'DESKTOP-0T5J9VF'.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.GetVM


* The control plane node "" does not exist.
  To start a cluster, run: "minikube start"
```
Instead this should have been just
```
 You do not have the required permission to complete this task. Contact the
administrator of the authorization policy for the computer 'DESKTOP-0T5J9VF'.
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9158353/log.txt)

### Operating System

Windows

### Driver

Hyper-V

**Comment by ashok-arora** [comment]
I would love to send a patch to fix this but I am not sure how to do that.

**Comment by ashok-arora** [comment]
The error message is confusing and cryptic at first, with the mention of line numbers of the  source code file and stuff. We should print just the error message for the end user.

**Comment by klaases** [comment]
Hi @ashok-arora, while the logs may seem verbose, as developers we sometimes need to take a look at the actual underlying code to find out where the error is coming from.

This helps us to troubleshoot issues beyond the error message itself.

/kind support

**Comment by ashok-arora** [comment]
@klaases Yeah I understand that, we could have the error message and underlying code piped to the log file while displaying a nicer message to the end user.

**Comment by klaases** [comment]
Hi @ashok-arora, if you are interested in contributing a PR, please check out the contributor guide on minikube's website.

https://minikube.sigs.k8s.io/docs/contrib/guide/

Thanks for sharing your experience.

**Comment by klaases** [comment]
Hi @ashok-arora  – we currently have limited bandwidth and will close out this task.

If this is still something you wanted to work on, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Thank you for sharing your experience!
