### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by justinhj** [kubernetes/minikube#1461]
Trying to start minikube using the virtual box driver but it looks like it ignores and tries to use xhyve. I do have virtualbox installed 

see below for my software versions

justin:~/minikube (master):$ minikube start --vm-driver=virtualbox
Starting local Kubernetes cluster...
Starting VM...
E0505 15:39:36.470310   45704 start.go:116] Error starting host: Error getting state for host: Driver "xhyve" not found. Do you have the plugin binary accessible in your PATH?.

 Retrying.
E0505 15:39:36.470737   45704 start.go:122] Error starting host:  Error getting state for host: Driver "xhyve" not found. Do you have the plugin binary accessible in your PATH?

docker --version
Docker version 17.03.0-ce, build 60ccb22

docker-compose --version
docker-compose version 1.11.2, build dfed245

docker-machine --version
docker-machine version 0.10.0, build 76ed2a6

minikube version
minikube version: v0.18.0

kubectl version --client 

Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by aaron-prindle** [comment]
Can you try running `minikube delete`, removing the `~/.minikube` directory, and then rerunning `minikube start`?  There is an issue where minikube may have originally stored a configuration to run w/ xhyve but if you delete and remove the dir, your settings should then work.

**Comment by justinhj** [comment]
That worked! Thanks.
