### ISSUE TITLE
apiserver healthz never reported healthy: timed out waiting for the condition

### ISSUE THREAD

**Issue by Pablompg** [kubernetes/minikube#14618]
### What Happened?

After installing minikube and running `minikube start --alsologtostderr` on ubuntu 22 the error attached is shown with this summary:

```
minikube v1.26.0 on Ubuntu 22.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > gcr.io/k8s-minikube/kicbase: 0 B [_________________________] ?% ? p/s 43s
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.24.1 on Docker 20.10.17 ...
🤦  Unable to restart cluster, will reset it: apiserver health: apiserver healthz never reported healthy: cluster wait timed out during healthz check
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...- E0721 10:15:25.951136   29800 start.go:264] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.58.2:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 192.168.58.2:8443: i/o timeout]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition
```

minikube was installed via stable release on x86-64 Linux using binary download.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9157846/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
I see that it states it's using an `existing profile`, if you run `minikube delete` and then try starting it again does it result in a different error?

**Comment by Pablompg** [comment]
It used to return the same error. However, today it did work. There has only been two significant changes on my machine since I posted the issue:

1. updated and upgraded via `sudo apt`.
2. Installing `libssl1.1` manually due to this other issue: Github issue Vscode](https://github.com/MicrosoftDocs/live-share/issues/4646#issuecomment-1200488721)

As I am no longer having the error I am closing this issue. Thank you for your time.
