### ISSUE TITLE
Minikube Exiting due to PROVIDER_DOCKER_NOT_RUNNING: "docker system info" accepts no arguments.

### ISSUE THREAD

**Issue by rob2universe** [kubernetes/minikube#14617]
### What Happened?

Minikube does not start because ""docker system info" accepts no arguments.

I0721 15:48:06.938659   20401 start.go:816] status for docker: {Installed:true Healthy:false Running:false NeedsImprovement:false Error:docker system info --format "{{json .}}": exit status 1
stdout:

stderr:
"docker system info" accepts no arguments.

**However Docker on my Ubuntu 18 WSL is working fine and I can run the command** 
`docker system info --format \"{{json .}}\"`

It produces this output:
`({"ID":"XODK:ELXN:ACRH:L43W:UCWY:MDV3:24XP:7HX6:LV6X:ZQRL:XPNN:ELLD","Containers":23,"ContainersRunning":0,"ContainersPaused":0,"ContainersStopped":23,"Images":82,"Driver":"overlay2","DriverStatus":[["Backing Filesystem","extfs"],["Supports d_type","true"],["Native Overlay Diff","true"],["userxattr","false"]],"Plugins":{"Volume":["local"],"Network":["bridge","host","ipvlan","macvlan","null","overlay"],"Authorization":null,"Log":["awslogs","fluentd","gcplogs","gelf","journald","json-file","local","logentries","splunk","syslog"]},"MemoryLimit":true,"SwapLimit":true,"KernelMemory":true,"KernelMemoryTCP":true,"CpuCfsPeriod":true,"CpuCfsQuota":true,"CPUShares":true,"CPUSet":true,"PidsLimit":true,"IPv4Forwarding":true,"BridgeNfIptables":true,"BridgeNfIp6tables":true,"Debug":false,"NFd":24,"OomKillDisable":true,"NGoroutines":39,"SystemTime":"2022-07-21T15:56:38.9755973+08:00","LoggingDriver":"json-file","CgroupDriver":"cgroupfs","CgroupVersion":"1","NEventsListener":0,"KernelVersion":"5.10.102.1-microsoft-standard-WSL2","OperatingSystem":"Ubuntu 18.04.2 LTS","OSVersion":"18.04","OSType":"linux","Architecture":"x86_64","IndexServerAddress":"https://index.docker.io/v1/","RegistryConfig":{"AllowNondistributableArtifactsCIDRs":[],"AllowNondistributableArtifactsHostnames":[],"InsecureRegistryCIDRs":["127.0.0.0/8"],"IndexConfigs":{"docker.io":{"Name":"docker.io","Mirrors":[],"Secure":true,"Official":true}},"Mirrors":[]},"NCPU":8,"MemTotal":13179596800,"GenericResources":null,"DockerRootDir":"/var/lib/docker","HttpProxy":"","HttpsProxy":"","NoProxy":"","Name":"LAPTOP-NHIKAJ44","Labels":[],"ExperimentalBuild":false,"ServerVersion":"20.10.17","Runtimes":{"io.containerd.runc.v2":{"path":"runc"},"io.containerd.runtime.v1.linux":{"path":"runc"},"runc":{"path":"runc"}},"DefaultRuntime":"runc","Swarm":{"NodeID":"","NodeAddr":"","LocalNodeState":"inactive","ControlAvailable":false,"Error":"","RemoteManagers":null},"LiveRestoreEnabled":false,"Isolation":"","InitBinary":"docker-init","ContainerdCommit":{"ID":"10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1","Expected":"10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1"},"RuncCommit":{"ID":"v1.1.2-0-ga916309","Expected":"v1.1.2-0-ga916309"},"InitCommit":{"ID":"de40ad0","Expected":"de40ad0"},"SecurityOptions":["name=seccomp,profile=default"],"Warnings":["WARNING: No blkio throttle.read_bps_device support","WARNING: No blkio throttle.write_bps_device support","WARNING: No blkio throttle.read_iops_device support","WARNING: No blkio throttle.write_iops_device support"],"ClientInfo":{"Debug":false,"Context":"default","Plugins":[{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.9.1-beta3","ShortDescription":"Docker App","Experimental":true,"Name":"app","Path":"/usr/libexec/docker/cli-plugins/docker-app"},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v0.8.2-docker","ShortDescription":"Docker Buildx","Name":"buildx","Path":"/usr/libexec/docker/cli-plugins/docker-buildx"},{"SchemaVersion":"0.1.0","Vendor":"Docker Inc.","Version":"v2.3.3","ShortDescription":"Docker Compose","Name":"compose","Path":"/home/rob/.docker/cli-plugins/docker-compose"},{"Name":"scan","Path":"/usr/local/lib/docker/cli-plugins/docker-scan","Err":"failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-scan: no such file or directory","ShadowedPaths":["/usr/libexec/docker/cli-plugins/docker-scan"]}],"Warnings":null}})`

### Attach the log file

==> Last Start <==
Log file created at: 2022/07/21 15:48:06
Running on machine: xyz
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0721 15:48:06.849082   20401 out.go:296] Setting OutFile to fd 1 ...
I0721 15:48:06.849200   20401 out.go:309] Setting ErrFile to fd 2...
I0721 15:48:06.849340   20401 root.go:329] Updating PATH: /home/rob/.minikube/bin
I0721 15:48:06.849491   20401 out.go:303] Setting JSON to false
I0721 15:48:06.850151   20401 start.go:115] hostinfo: {"hostname":"xyz","uptime":14525,"bootTime":1658375162,"procs":49,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.10.102.1-microsoft-standard-WSL2","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"a61f770a-9aad-4799-93cf-036e13ff6f19"}
I0721 15:48:06.850218   20401 start.go:125] virtualization:
I0721 15:48:06.867295   20401 out.go:177] 😄  minikube v1.26.0 on Ubuntu 18.04
I0721 15:48:06.869705   20401 notify.go:193] Checking for updates...
I0721 15:48:06.869708   20401 driver.go:360] Setting default libvirt URI to qemu:///system
W0721 15:48:06.869780   20401 preload.go:295] Failed to list preload files: open /home/rob/.minikube/cache/preloaded-tarball: no such file or directory
I0721 15:48:06.909412   20401 docker.go:137] docker version: linux-20.10.17
I0721 15:48:06.909495   20401 cli_runner.go:164] Run: docker system info --format "{{json .}}"
W0721 15:48:06.934231   20401 cli_runner.go:211] docker system info --format "{{json .}}" returned with exit code 1
W0721 15:48:06.934264   20401 info.go:257] docker info: docker system info --format "{{json .}}": exit status 1
stdout:

stderr:
"docker system info" accepts no arguments.
See 'docker system info --help'.

Usage:  docker system info [OPTIONS]

Display system-wide information
I0721 15:48:06.936693   20401 out.go:177] ✨  Using the docker driver based on user configuration
I0721 15:48:06.938638   20401 start.go:284] selected driver: docker
I0721 15:48:06.938647   20401 start.go:805] validating driver "docker" against <nil>
I0721 15:48:06.938659   20401 start.go:816] status for docker: {Installed:true Healthy:false Running:false NeedsImprovement:false Error:docker system info --format "{{json .}}": exit status 1
stdout:

stderr:
"docker system info" accepts no arguments.
See 'docker system info --help'.

Usage:  docker system info [OPTIONS]

Display system-wide information

docker system info
k8s.io/minikube/pkg/drivers/kic/oci.dockerSystemInfo
        /app/pkg/drivers/kic/oci/info.go:258
k8s.io/minikube/pkg/drivers/kic/oci.DaemonInfo
        /app/pkg/drivers/kic/oci/info.go:65
k8s.io/minikube/pkg/drivers/kic/oci.CachedDaemonInfo
        /app/pkg/drivers/kic/oci/info.go:48
k8s.io/minikube/pkg/minikube/registry/drvs/docker.status
        /app/pkg/minikube/registry/drvs/docker/docker.go:146
k8s.io/minikube/pkg/minikube/registry.Status
        /app/pkg/minikube/registry/global.go:149
k8s.io/minikube/pkg/minikube/driver.Status
        /app/pkg/minikube/driver/driver.go:343
k8s.io/minikube/cmd/minikube/cmd.selectDriver
        /app/cmd/minikube/cmd/start.go:612
k8s.io/minikube/cmd/minikube/cmd.runStart
        /app/cmd/minikube/cmd/start.go:196
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
k8s.io/minikube/cmd/minikube/cmd.Execute
        /app/cmd/minikube/cmd/root.go:170
main.main
        /app/cmd/minikube/main.go:88
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571
docker info
k8s.io/minikube/pkg/minikube/registry/drvs/docker.status
        /app/pkg/minikube/registry/drvs/docker/docker.go:149
k8s.io/minikube/pkg/minikube/registry.Status
        /app/pkg/minikube/registry/global.go:149
k8s.io/minikube/pkg/minikube/driver.Status
        /app/pkg/minikube/driver/driver.go:343
k8s.io/minikube/cmd/minikube/cmd.selectDriver
        /app/cmd/minikube/cmd/start.go:612
k8s.io/minikube/cmd/minikube/cmd.runStart
        /app/cmd/minikube/cmd/start.go:196
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
k8s.io/minikube/cmd/minikube/cmd.Execute
        /app/cmd/minikube/cmd/root.go:170
main.main
        /app/cmd/minikube/main.go:88
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571 Reason:PROVIDER_DOCKER_INFO_FAILED Fix: Doc:https://minikube.sigs.k8s.io/docs/drivers/docker/ Version:}
E0721 15:48:06.938965   20401 out.go:448] unable to parse "docker info: docker system info: docker system info --format \"{{json .}}\": exit status 1\nstdout:\n\nstderr:\n\"docker system info\" accepts no arguments.\nSee 'docker system info --help'.\n\nUsage:  docker system info [OPTIONS]\n\nDisplay system-wide information\n": template: docker info: docker system info: docker system info --format "{{json .}}": exit status 1
stdout:

stderr:
"docker system info" accepts no arguments.
See 'docker system info --help'.

Usage:  docker system info [OPTIONS]

Display system-wide information
:1: function "json" not defined - returning raw string.
I0721 15:48:06.941144   20401 out.go:177]
W0721 15:48:06.942889   20401 out.go:239] 💣  Exiting due to PROVIDER_DOCKER_NOT_RUNNING: docker info: docker system info: docker system info --format "{{json .}}": exit status 1
stdout:

stderr:
"docker system info" accepts no arguments.
See 'docker system info --help'.

Usage:  docker system info [OPTIONS]

Display system-wide information

W0721 15:48:06.942960   20401 out.go:239] 📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/
I0721 15:48:06.944490   20401 out.go:177]

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Is your client the same version as the server (20.10.17) ? Can you post the output of `docker version` ?

The help is _supposed_ to look like:

```
Usage:  docker system info [OPTIONS]

Display system-wide information

Options:
  -f, --format string   Format the output using the given Go template

```

Normally they are the same version.

**Comment by rob2universe** [comment]
Thanks for your reply. Both 20.10.17:

Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:56 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:02 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by rob2universe** [comment]
docker system info without --format \"{{json .}}\" parameter:

Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.8.2-docker)
  compose: Docker Compose (Docker Inc., v2.3.3)
WARNING: Plugin "/usr/local/lib/docker/cli-plugins/docker-scan" is not valid: failed to fetch metadata: fork/exec /usr/local/lib/docker/cli-plugins/docker-scan: no such file or directory

Server:
 Containers: 23
  Running: 0
  Paused: 0
  Stopped: 23
 Images: 82
 Server Version: 20.10.17
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc version: v1.1.2-0-ga916309
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.102.1-microsoft-standard-WSL2
 Operating System: Ubuntu 18.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.27GiB
 Name: LAPTOP-NHIKAJ44
 ID: XODK:ELXN:ACRH:L43W:UCWY:MDV3:24XP:7HX6:LV6X:ZQRL:XPNN:ELLD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support

**Comment by afbjorklund** [comment]
Hmm, still no clues as to where it is picking up the old docker client from.

**Comment by rob2universe** [comment]
@afbjorklund thanks for your feedback. Is this an internal comment or are you asking me to add this somewhere?

**Comment by rob2universe** [comment]
I installed an additional Ubuntu 22 LTS, docker and minikube. Here its working fine

**Comment by afbjorklund** [comment]
> @afbjorklund thanks for your feedback. Is this an internal comment or are you asking me to add this somewhere?

I guess you would have to run a patched binary, if wanting to know what happens (for you only)

**Comment by klaases** [comment]
Hi @rob2universe, were you able to run a patched binary as @afbjorklund suggested?

/triage needs-information

**Comment by varun-telus** [comment]
Hi I am facing the same issue - here is my docker system info without format

`Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
  compose: Docker Compose (Docker Inc., v2.10.2)
  scan: Docker Scan (Docker Inc., v0.17.0)

Server:
 Containers: 7
  Running: 0
  Paused: 0
  Stopped: 7
 Images: 2
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 12.39GiB
 Name: L801334
 ID: XDEW:N2LM:FILM:Y2UK:VRKG:RIPP:JEAI:6IC2:4ER7:5DQK:EQSV:POQM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: API is accessible on http://127.0.0.1:2375 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/go/attack-surface/
WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support`

**Comment by rob2universe** [comment]
@klaases that you for following up. I am not sure how to go about creating and installing such a patch and my issue was resolved when I moved to Ubuntu 22 LTS. Here the Docker installation seem to differ.

**Comment by rob2universe** [comment]
Hi @klaases - it wasn't a Minikube update. It was a complete fresh install on a new Ubuntu (WSL). To me it would make sense to add at least the logging which was missing to diagnose this to Minikube, so it could be better understood when if occurs again.
