### ISSUE TITLE
minikube start failed

### ISSUE THREAD

**Issue by Linzi-demo** [kubernetes/minikube#14625]
### What Happened?

I made some errors when using minicube. Kubelet did not start normally. Here is my log

[minikube_start_log.txt](https://github.com/kubernetes/minikube/files/9175229/minikube_start_log.txt)

my docker version
![image](https://user-images.githubusercontent.com/20336742/180634912-5d3d6619-fed6-4fa7-b824-edd4154deefa.png)

### Attach the log file

run command error

```
minikube logs --file=log.txt
```

E0724 14:01:47.354244    5164 logs.go:192] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.24.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.24.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

**Comment by tamaw** [comment]
Can you try:
`minikube delete`
`minikube start --kubernetes-version=1.23.9`

and see if it works please? 
Could be related to https://github.com/kubernetes/kubernetes/pull/107413 but unconfirmed.

**Comment by Linzi-demo** [comment]
> 

Thanks, it has been solved
