### ISSUE TITLE
not able to start minikube in ubuntu instance 

### ISSUE THREAD

**Issue by adarshhp14** [kubernetes/minikube#14621]
### What Happened?

root@ip-172-31-34-0:/home/ubuntu# minikube start --vm-driver=none
* minikube v1.26.0 on Ubuntu 22.04 (xen/amd64)
* Using the none driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=2, Memory=3922MB, Disk=7764MB) ...
* OS release is Ubuntu 22.04 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9164710/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Same as:
* https://github.com/kubernetes/minikube/issues/14410

**Comment by MRafaydev** [comment]
This Same issue happened to me,
Steps to Reproduce:
1) Reinstall the ubuntu.
2) Download the minikube from its original documentation according to your os.
3) After the installation simply uses **minikube start** it will automatically detect the driver.

<img width="956" alt="image" src="https://user-images.githubusercontent.com/66843891/180551627-97f0b86a-0124-4658-b591-1212a01e905d.png">

**Comment by afbjorklund** [comment]
You don't need to reinstall your OS, just to install cri-dockerd in the VM.

**Comment by klaases** [comment]
Hi @adarshhp14 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
