### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by vinay2204** [kubernetes/minikube#14626]
### What Happened?

i have ubuntu and wants to start minikube but facing issues

### Attach the log file

If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.  

### Operating System

Ubuntu

### Driver

Docker

**Comment by drobit** [comment]
Hey, @vinay2204 could you provide minikube logs?
`minikube logs --file=logs.txt`

**Comment by RA489** [comment]
@vinay2204 I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by klaases** [comment]
Hi @vinay2204 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by omnain11** [comment]
If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.
