### ISSUE TITLE
Failed to run Minikube

### ISSUE THREAD

**Issue by speedfinger** [kubernetes/minikube#14623]
### What Happened?

Failed to run Minikube on wsl2 unbuntu(Release : 20.04)
and i'm using docker desktop

I have already  identified the following issues.
https://github.com/kubernetes/minikube/issues/12274

1. Make sure you're using the arm64 binary of minikube
  -> checked
2. Run minikube delete --all --purge
  -> checked
Try starting minikube again
 -> still failed.

### Attach the log file

I0723 22:34:05.442809    6330 kubeadm.go:152] config check failed, skipping stale config cleanup: sudo ls -la /etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf: Process exited with status 2
stdout:

stderr:
ls: cannot access '/etc/kubernetes/admin.conf': No such file or directory
ls: cannot access '/etc/kubernetes/kubelet.conf': No such file or directory
ls: cannot access '/etc/kubernetes/controller-manager.conf': No such file or directory
ls: cannot access '/etc/kubernetes/scheduler.conf': No such file or directory

### Operating System

Ubuntu

### Driver

Docker

**Comment by speedfinger** [comment]
[logs220723.txt](https://github.com/kubernetes/minikube/files/9173984/logs220723.txt)

full logs

**Comment by aoga88** [comment]
I'm having the same issue on Fedora 36

**Comment by klaases** [comment]
Hi @speedfinger, are you able to update to Ubuntu 20.10?
