### ISSUE TITLE
Hi @preetsohivirk, I am working on PR (#14555) and encountered this issue too, I solved it via the following:

### ISSUE THREAD

**Issue by vivek625** [kubernetes/minikube#14620]
Hi @preetsohivirk, I am working on PR (#14555) and encountered this issue too, I solved it via the following:

---

(Copied from: #14555):

Note: if you encounter the error crictl not found:

```
$ sudo -E ./out/minikube start --driver=none
[sudo] password for klaases: 
😄  minikube v1.26.0 on Debian rodete (kvm/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Debian GNU/Linux rodete

❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
...
```

By default, `crictl` will work from `/usr/local/bin/`, however minikube requires crictl to be in `/usr/bin/` (https://github.com/kubernetes/minikube/issues/5547#issuecomment-556984525).

Manually fix `sudo crictl` by running the following command:
`sudo cp /usr/local/bin/crictl /usr/bin/crictl`

_Originally posted by @klaases in https://github.com/kubernetes/minikube/issues/14604#issuecomment-1190611171_

**Comment by vivek625** [comment]
cp: cannot stat '/usr/local/bin/crictl': No such file or directory
this problem create sir 
please another method provide

**Comment by a2026211583** [comment]
Many thanks，"sudo cp /usr/local/bin/crictl /usr/bin/crictl "This method successfully solved my problem
But I reported the following error
`
unable to determine runtime API version: rpc error: code = DeadlineExceeded desc = context deadline exceeded
`

**Comment by klaases** [comment]
Hi, `crictl` may be installed in a different location based on your operating system. In the example provided, this was for a Mac with M1 processor.

@vivek625, were you able to get `crictl` working for your OS?

**Comment by klaases** [comment]
Hi @vivek625 – 

Here is some additional installation information: https://github.com/kubernetes/minikube/issues/14410#issuecomment-1193323463


---

If needed, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
