### ISSUE TITLE
minikube start failed even with --image-mirror-country=cn in china

### ISSUE THREAD

**Issue by qiuyuhang** [kubernetes/minikube#14624]
## Reason：
Still access k8s.gcr.io/pause:3.6.

## How to work around：
```
docker exec -it minikube bash
docker pull registry.aliyuncs.com/google_containers/pause:3.6
docker tag registry.aliyuncs.com/google_containers/pause:3.6 k8s.gcr.io/pause:3.6
```
## How to fix:
need to use registry.aliyuncs.com/google_containers/pause:3.6 in minikube.

### Attach the log file

Noop

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by qiuyuhang** [comment]
Forgot the version. It's the latest version.
```
minikube version: v1.26.0
commit: f4b412861bb746be73053c9f6d2895f12cf78565
```

**Comment by hutersman** [comment]
I am new to minikube and I get the same issue
### Operating System
Redhat/Fedora
### Driver
Docker
### What I did
Follow the document and do the installation
```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
```
I am in China mainland, so I start with
```
minikube start --image-mirror-country=cn
```
I hope it works, but I got follow messages
```
* minikube v1.26.0 on Centos 7.9.2009
* Automatically selected the docker driver
* Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
* Using Docker driver with root privileges
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
    > registry.cn-hangzhou.aliyun...: 0 B [_____________________] ?% ? p/s 8m0s
* Creating docker container (CPUs=2, Memory=23700MB) ...
! StartHost failed, but will try again: creating host: create: bootstrapping certificates: Failed to decode PEM data
* Creating docker container (CPUs=2, Memory=23700MB) ...
* Failed to start docker container. Running "minikube delete" may fix it: creating host: create: bootstrapping certificates: Failed to decode PEM data

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: bootstrapping certificates: Failed to decode PEM data
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

```
So I run `minikube logs --file=logs.txt`
```
* Profile "minikube" not found. Run "minikube profile list" to view all profiles.
  To start a cluster, run: "minikube start"
```
Then I run `minikube profile list`
```
* Exiting due to MK_USAGE_NO_PROFILE: No minikube profile was found.
* Suggestion:

    You can create one using 'minikube start'.
```

**Comment by c1ay** [comment]
> ### What Happened?
> ## Reason：
> Still access k8s.gcr.io/pause:3.6.
> 
> ## How to work around：
> ```
> docker exec -it minikube bash
> docker pull registry.aliyuncs.com/google_containers/pause:3.6
> docker tag registry.aliyuncs.com/google_containers/pause:3.6 k8s.gcr.io/pause:3.6
> ```
> 
> ## How to fix:
> need to use registry.aliyuncs.com/google_containers/pause:3.6 in minikube.
> 
> ### Attach the log file
> Noop
> 
> ### Operating System
> Redhat/Fedora
> 
> ### Driver
> Docker

works for me
```
minikube start --image-mirror-country=cn

## until it gets stuck (could't pull image k8s.gcr.io/pause:3.6)

docker exec -it minikube bash
docker pull registry.aliyuncs.com/google_containers/pause:3.6
docker tag registry.aliyuncs.com/google_containers/pause:3.6 k8s.gcr.io/pause:3.6
```

**Comment by cheese** [comment]
> ### What Happened?
> ## Reason：
> 
> Still access k8s.gcr.io/pause:3.6.
> ## How to work around：
> 
> ```
> docker exec -it minikube bash
> docker pull registry.aliyuncs.com/google_containers/pause:3.6
> docker tag registry.aliyuncs.com/google_containers/pause:3.6 k8s.gcr.io/pause:3.6
> ```
> 
> ## How to fix:
> 
> need to use registry.aliyuncs.com/google_containers/pause:3.6 in minikube.
> ### Attach the log file
> 
> Noop
> ### Operating System
> 
> Redhat/Fedora
> ### Driver
> 
> Docker

With minikube v1.29.0, change `k8s.gcr.io` to `registry.k8s.io`.
