### ISSUE TITLE
Minikube unable to pick a default driver

### ISSUE THREAD

**Issue by edgarboris** [kubernetes/minikube#14632]
### What Happened?

After installing KUBECTL successfully i wanted to install minikube.
but it sends me the error details as pasted below.

I am using a WSL2(Ubuntu)
i have also installed a docker desktop

### Attach the log file

Here is what was considered, in preference order:
    ▪ docker: Not healthy: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied
    ▪ docker: Suggestion: Add your user to the 'docker' group: 'sudo usermod -aG docker $USER && newgrp docker' <https://docs.docker.com/engine/install/linux-postinstall/>
💡  Alternatively you could install one of these drivers:
    ▪ kvm2: Not installed: exec: "virsh": executable file not found in $PATH
    ▪ podman: Not installed: exec: "podman": executable file not found in $PATH
    ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH
    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH
    ▪ qemu2: Not installed: exec: "qemu-system-x86_64": executable file not found in $PATH

❌  Exiting due to DRV_NOT_HEALTHY: Found driver(s) but none were healthy. See above for s

### Operating System

Windows

### Driver

Docker

**Comment by edgarboris** [comment]
- 
<img width="539" alt="image" src="https://user-images.githubusercontent.com/32974755/180841452-f2dac583-bc83-441e-912f-9e96939c194d.png">

I have found a solution it worked for me
anyway i just share it it could help someone else

**Comment by spowelljr** [comment]
Glad you resolved your issue, it looks like you just needed to run the Docker Engine post-install steps

https://docs.docker.com/engine/install/linux-postinstall/

**Comment by happy111** [comment]
sudo chmod 666 /var/run/docker.sock
sudo adduser #USER docker

I have found a solution it worked for me
anyway i just share it it could help someone else

**Comment by Josue198s** [comment]
Thanks, the post-installation instruction worked.

**Comment by anil8064** [comment]
it working for me thanks.

**Comment by Emalton** [comment]
For those of you trying to get this going on Windows you need to start Docker Desktop before using starting minikube.

**Comment by Ankit-Jha98** [comment]
> For those of you trying to get this going on Windows you need to start Docker Desktop before using starting minikube.

Thanks, it worked.
