### ISSUE TITLE
Shorten flag --name to -n

### ISSUE THREAD

**Issue by jorgemoralespou** [kubernetes/minikube#1463]
Feature request:
Shorten the flag babe (or allow booth) to make user experience better.

From:
`minikube start --name=test`

To:
`minikube start -n test`

**Comment by ankon** [comment]
-n is used for "namespace", matching kubectl. Having it here mean name would be confusing I think.

**Comment by jorgemoralespou** [comment]
@ankon I can agree. I preferred to have that called profile, but since this has been named --name, I think that a shortened name is required. Also, this commands are used on minikube, and AFAIK you don't specify --namespace or -n on minikube commands.

**Comment by ankon** [comment]
Actually you do - at least for `minikube service`.

**Comment by jorgemoralespou** [comment]
@ankon then maybe -n is not an option, but I would think that minimizing options should be a must for frequently used options, so maybe rename name to profile could fix it before a release is cut with this functionality (if not yet happen).

**Comment by aaron-prindle** [comment]
Closing.  This is supported in v0.19.0 w/ the `-p` flag.  Also a convenience method `minikube profile <name>' was added
