### ISSUE TITLE
Unable to start Minikube by using ec2 ubuntu machine 

### ISSUE THREAD

**Issue by Omprakashsurwase** [kubernetes/minikube#14646]
### What Happened?

root@ip-172-31-5-109:~# minikube start --vm-driver=none
* minikube v1.26.0 on Ubuntu 22.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 22.04 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

* 
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

root@ip-172-31-5-109:~# sudo apt update && apt -y install docker.io
Hit:1 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy InRelease
Get:2 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates InRelease [114 kB]
Get:3 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:4 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-backports InRelease [99.8 kB]
Get:5 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [14.1 MB]
Get:6 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [228 kB]
Get:7 http://security.ubuntu.com/ubuntu jammy-security/main Translation-en [56.3 kB]
Get:8 http://security.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [3564 B]
Get:9 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [203 kB]             
Get:10 http://security.ubuntu.com/ubuntu jammy-security/restricted Translation-en [30.4 kB]    
Get:11 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 c-n-f Metadata [512 B] 
Get:12 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [95.3 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/universe Translation-en [33.8 kB]           
Get:14 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [2204 B]    
Get:15 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [4192 B]             
Get:16 http://security.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [900 B]         
Get:17 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 c-n-f Metadata [228 B]
Get:18 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy/universe Translation-en [5652 kB]
Get:19 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy/universe amd64 c-n-f Metadata [286 kB]
Get:20 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [217 kB]
Get:21 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse Translation-en [112 kB]
Get:22 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy/multiverse amd64 c-n-f Metadata [8372 B]
Get:23 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [384 kB]
Get:24 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [97.6 kB]Get:25 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [6704 B]
Get:26 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [238 kB]
Get:27 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [36.4 kB]
Get:28 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 c-n-f Metadata [536 B]
Get:29 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [177 kB]
Get:30 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [61.9 kB]
Get:31 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [4252 B]
Get:32 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [7000 B]
Get:33 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [2112 B]
Get:34 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 c-n-f Metadata [420 B]
Get:35 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/main amd64 c-n-f Metadata [112 B]
Get:36 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/restricted amd64 c-n-f Metadata [116 B]
Get:37 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [5416 B]
Get:38 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe Translation-en [8160 B]
Get:39 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/universe amd64 c-n-f Metadata [236 B]
Get:40 http://ap-south-1.ec2.archive.ubuntu.com/ubuntu jammy-backports/multiverse amd64 c-n-f Metadata [116 B]
Fetched 22.4 MB in 7s (3190 kB/s)                                                                                        
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
I0727 05:54:37.018551    3461 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0727 05:54:37.293158    3461 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0727 05:54:37.574958    3461 exec_runner.g
727 05:54:37.940473    3461 out.go:239] X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit s
tatus 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

W0727 05:54:37.940498    3461 out.go:239] * 
W0727 05:54:37.941519    3461 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────
──────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0727 05:54:37.943583    3461 out.go:177] 

### Operating System

Ubuntu

### Driver

SSH

**Comment by RA489** [comment]
@Omprakashsurwase As a workaround Could you please try it with docker driver.

 `minikube start --driver=none`

**Comment by Omprakashsurwase** [comment]
Thanks I will try..

**Comment by Omprakashsurwase** [comment]
Hello team,

I am trying minikube start --driver=none this command but same issue
happening.

Thanks
Omprakash

**Comment by afbjorklund** [comment]
If you use docker, you also need to install cri-dockerd

**Comment by klaases** [comment]
Hi @Omprakashsurwase, have you tried installing `cri-dockerd`?

https://github.com/Mirantis/cri-dockerd

**Comment by Omprakashsurwase** [comment]
Yes, it is working.

Thanks for your help.

**Comment by klaases** [comment]
Hi @Omprakashsurwase, glad to hear that this is now working for you now.

Thanks for using minikube!
