### ISSUE TITLE
Minikube can't configure API server

### ISSUE THREAD

**Issue by IvanZavaruev** [kubernetes/minikube#14648]
### What Happened?

I try start minikube  (PC Windows 10, proc intel core i5 10210)i tried)
i tried everything: > minikube delete 
> minikube delete --all --purge
>restarting the computer
> program reinstallation 

C:\Users\IZavaruev>minikube start --vm-driver=vmware
* minikube v1.26.0 на Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
  - KUBECONFIG=C:\Users\IZavaruev\.kube\config
* Используется драйвер vmware на основе конфига пользователя
* Downloading VM boot image ...
    > minikube-v1.26.0-amd64.iso....: 65 B / 65 B [----------] 100.00% ? p/s 0s
    > minikube-v1.26.0-amd64.iso: 268.86 MiB / 268.86 MiB  100.00% 36.20 MiB p/
* Запускается control plane узел minikube в кластере minikube
* Скачивается Kubernetes v1.24.1 ...
    > preloaded-images-k8s-v18-v1...: 405.83 MiB / 405.83 MiB  100.00% 31.35 Mi
* Creating vmware VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Подготавливается Kubernetes v1.24.1 на Docker 20.10.16 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...- E0727 13:45:31.931176   23716 start.go:264] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

* Компоненты Kubernetes проверяются ...
! Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.239.129:8443/apis/storage.k8s.io/v1/storageclasses": x509: certificate signed by unknown authority]
  - Используется образ gcr.io/k8s-minikube/storage-provisioner:v5
* Включенные дополнения: storage-provisioner
X Problems detected in kubelet:
  Jul 27 06:43:44 minikube kubelet[2159]: W0727 06:43:44.776133    2159 reflector.go:324] object-"kube-system"/"kube-proxy": failed to list *v1.ConfigMap: configmaps "kube-proxy" is forbidden: User "system:node:minikube" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
  Jul 27 06:43:44 minikube kubelet[2159]: E0727 06:43:44.776214    2159 reflector.go:138] object-"kube-system"/"kube-proxy": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "kube-proxy" is forbidden: User "system:node:minikube" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
X Problems detected in kubelet:
  Jul 27 06:43:44 minikube kubelet[2159]: W0727 06:43:44.776133    2159 reflector.go:324] object-"kube-system"/"kube-proxy": failed to list *v1.ConfigMap: configmaps "kube-proxy" is forbidden: User "system:node:minikube" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
X Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition

C:\Users\IZavaruev>minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Stopped
kubeconfig: Configured

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9196000/logs.txt)

### Operating System

Windows

### Driver

VMware

**Comment by spowelljr** [comment]
Hi @IvanZavaruev, can you read this section of your documentation and see if that helps.

https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/#x509-certificate-signed-by-unknown-authority

**Comment by klaases** [comment]
Hi @IvanZavaruev, were you able to review the above comment?

Does that help with the issue?

**Comment by klaases** [comment]
Hi @IvanZavaruev – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
