### ISSUE TITLE
oci runtime error: could not synchronise with container process: no subsystem for mount

### ISSUE THREAD

**Issue by emiellohr** [kubernetes/minikube#1464]
BUG REPORT

minikube version: v0.18.0
macOs: 10.12.4
driver: xhyve

I've started the tutorial as described here: https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/

After deployment, the pod is stucked at state ContainerCreating

➜  hellonode kubectl get pods
NAME                          READY     STATUS              RESTARTS   AGE
hello-node-1644695913-cswht   0/1       ContainerCreating   0          41m

kubectl describe pod hello-node-1644695913-cswht gives me

Error syncing pod, skipping: failed to "CreatePodSandbox" for "hello-node-1644695913-cswht_default(a89605ae-3244-11e7-bd27-3a910ed5367d)" with CreatePodSandboxError: "CreatePodSandbox for pod \"hello-node-1644695913-cswht_default(a89605ae-3244-11e7-bd27-3a910ed5367d)\" failed: rpc error: code = 2 desc = failed to start sandbox container for pod \"hello-node-1644695913-cswht\": Error response from daemon: rpc error: code = 2 desc = \"oci runtime error: could not synchronise with container process: no subsystem for mount\""

**Comment by emiellohr** [comment]
Hi, is this ringing a bell by someone or should i post my problem else/on stackoverflow? I'm not sure this is related to minikube or another involved component.

**Comment by aaron-prindle** [comment]
Can you post the output of `minikube logs`?

**Comment by emiellohr** [comment]
Looks solved after installing the latest minikube version.
