### ISSUE TITLE
Start Minikube failed

### ISSUE THREAD

**Issue by BlackImpl** [kubernetes/minikube#14651]
### What Happened?

😄  minikube v1.26.0 on Darwin 11.6.5
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
❗  The image 'k8s.gcr.io/kube-scheduler:v1.24.1' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/kube-apiserver:v1.24.1' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/pause:3.7' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/coredns/coredns:v1.8.6' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/kube-proxy:v1.24.1' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/etcd:3.5.3-0' was not found; unable to add it to cache.
❗  The image 'gcr.io/k8s-minikube/storage-provisioner:v5' was not found; unable to add it to cache.
❗  The image 'k8s.gcr.io/kube-controller-manager:v1.24.1' was not found; unable to add it to cache.
E0727 14:18:33.949310   33909 cache.go:203] Error downloading kic artifacts:  failed to download kic base image or any fallback image
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.24.1 on Docker 20.10.17 ...
❌  Unable to load cached images: loading cached images: stat /Users/jielong/.minikube/cache/images/amd64/gcr.io/k8s-minikube/storage-provisioner_v5: no such file or directory

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubeadm.sha256 Dst:/Users/jielong/.minikube/cache/linux/amd64/v1.24.1/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x432e048 0x432e048 0x432e048 0x432e048 0x432e048 0x432e048 0x432e048] Decompressors:map[bz2:0x432e048 gz:0x432e048 tar:0x432e048 tar.bz2:0x432e048 tar.gz:0x432e048 tar.xz:0x432e048 tar.zst:0x432e048 tbz2:0x432e048 tgz:0x432e048 txz:0x432e048 tzst:0x432e048 xz:0x432e048 zip:0x432e048 zst:0x432e048] Getters:map[file:0xc000be1000 http:0xc000cda550 https:0xc000cda5a0] Dir:false ProgressListener:0x42e9db0 Insecure:false DisableSymlinks:false Options:[0x25f0ba0]}: invalid checksum: Error downloading checksum file: Get "https://storage.googleapis.com/kubernetes-release/release/v1.24.1/bin/linux/amd64/kubeadm.sha256": dial tcp 74.125.198.128:443: connect: bad file descriptor

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9196674/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
It seems you're unable to access the internet, are you behind a proxy or firewall perhaps? Or are you located in China?

**Comment by klaases** [comment]
Hi @BlackImpl – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
