### ISSUE TITLE
minkube 

### ISSUE THREAD

**Issue by chandraveer1996** [kubernetes/minikube#14659]
### What Happened?

when i am running minikube start command it is not working 

### Attach the log file

i tried this on ubuntu, rhel8 and amazon linux error was same everywhere getting this error
😄  minikube v1.26.0 on Amazon 2 (xen/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Amazon Linux 2

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to execute operation: No such file or directory

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Ubuntu

**Comment by afbjorklund** [comment]
Same as:
* https://github.com/kubernetes/minikube/issues/14410

**Comment by klaases** [comment]
Hi @chandraveer1996, you're going to want to install `cri-dockerd`, please take a look at this comment:

https://github.com/kubernetes/minikube/issues/14410#issuecomment-1193323463

For more information.

Thank you for sharing your experience!

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @chandraveer1996 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
