### ISSUE TITLE
Enabling 'default-storageclass' returned an error

### ISSUE THREAD

**Issue by PalmaPedro** [kubernetes/minikube#14650]
### What Happened?

I'm on Linux Mint 20.03. When running 'minikube start', I get this error. 

![image](https://user-images.githubusercontent.com/47104435/181192351-ebb82110-eefe-4690-af06-67506a5954f6.png)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9196191/logs.txt)

### Operating System

Other

### Driver

Docker

**Comment by RA489** [comment]
@PalmaPedro Looks like API server is not up and running here.

**Comment by PalmaPedro** [comment]
I still can't start minikube. Any suggestion as to why the api server stops?

**Comment by klaases** [comment]
Hi @PalmaPedro, if you need additional support, you may also reach out to the minikube community Slack channel.

https://minikube.sigs.k8s.io/community/
