### ISSUE TITLE
minikube start --driver=docker failed on raspberry pi 4

### ISSUE THREAD

**Issue by f0xMccloud** [kubernetes/minikube#14655]
### What Happened?

minikube start --driver=docker failed with multiple errors:

`command error:                                                                                                                                                 
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?` 

docker version: 
` Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:34 2022
 OS/Arch:           linux/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:01 2022
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0`

minikube verison:
`minikube version: v1.26.0
commit: f4b412861bb746be73053c9f6d2895f12cf78565`

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9203298/logs.txt)

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
Something seems wrong with the `/docker/root` directory

**Comment by f0xMccloud** [comment]
Yes it seems to, I changed the default path of docker root directory as you can see. Part of dirs are owned by root and other parts owned by regular user (since, i think, i added pi user to docker group).

> total 84K
drwx--x--x  4 pi   pi   4.0K May 23 20:39 buildkit
drwx--x---  6 root root 4.0K Jul 27 21:06 containers
drwx------  3 pi   pi   4.0K May 23 20:39 image
drwxr-x---  3 pi   pi   4.0K May 23 20:39 network
drwx--x--- 98 root root  16K Jul 27 21:06 overlay2
drwx------  4 pi   pi   4.0K May 23 20:39 plugins
drwx------  2 root root 4.0K Jul 27 20:54 runtimes
drwx------  2 pi   pi   4.0K May 23 20:39 swarm
drwx------  2 root root 4.0K Jul 27 20:54 tmp
drwx------  2 pi   pi   4.0K May 23 20:39 trust
drwx-----x  7 root root  28K Jul 27 21:01 volumes

Maybe user and rights are not correct for minikube ?

**Comment by afbjorklund** [comment]
I don't think it is the ownership as such, it looks more like you mounted it `nosuid` or something ? Anyway, this is a Docker problem and not really related to minikube

**Comment by f0xMccloud** [comment]
Correct. Thanks for help

**Comment by f0xMccloud** [comment]
> I don't think it is the ownership as such, it looks more like you mounted it `nosuid` or something ? Anyway, this is a Docker problem (for `sudo`) and not really related to minikube
> 
> > Yes it seems to, I changed the default path of docker root directory as you can see.
> 
> What was the reason for moving away from `/var/lib/docker` ? Added a disk to the Pi ?

Yes, that was the reason.

**Comment by afbjorklund** [comment]
There was a backlog item of adding more helpful instructions for the Raspberry Pi.

* https://github.com/kubernetes/minikube/issues/9762

When running with arm64 and 4 GiB of RAM, I don't think there's _that_ much left ?

https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-64-bit

**Comment by spowelljr** [comment]
Hi @f0xMccloud, was your question resolved? Is it okay if I close this issue?

**Comment by f0xMccloud** [comment]
Hi @spowelljr , yes it is. Sorry I completely forget to close it.
