### ISSUE TITLE
Enabling hubble fails

### ISSUE THREAD

**Issue by Neskews** [kubernetes/minikube#14662]
### What Happened?

I started a minikube cluster with cilium enabled like this:

```shell
minikube start -p cilium-cluster --cni=cilium
```

Then I tried to enable hubble like this
```shell
cilium hubble enable
```

I got following error message
```
Error: Unable to enable Hubble: unable to retrieve helm values secret kube-system/cilium-cli-helm-values: secrets "cilium-cli-helm-values" not found
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9207611/log.txt)

**Comment by spowelljr** [comment]
Hi @Neskews, are you running it directly on your machine or are you `ssh`ing into minikube and then running the command?

**Comment by klaases** [comment]
Hi @Neskews, did you have a chance to review the above comment? You'll need to first `ssh` into minikube.

**Comment by pipixi** [comment]
Maybe you can run `cilium install` first, then `cilium hubble enable`
It's works for me :)
@Neskews

**Comment by klaases** [comment]
Hi @Neskews, were either of the above comments helpful in reaching a resolution to the issue?

**Comment by Neskews** [comment]
I was indeed running `cilium install` locally, because I assumed it would somehow pick up the cluster form my `kubectx`.

However, I'm still running into issues. What I did now was

1. Start a new cluster
```sh
minikube start -p cilium-cluster --cni=cilium
```

2. Mount eBPF file system:
```sh
minikube ssh -- sudo mount bpffs -t bpf /sys/fs/bpf
```
`kubectl -n kube-system get pods` shows running cilium pods now

3. Try to run `cilium install` in the cluster:
- `minikube -p cilium-cluster ssh` works
- `cilium` (I ran it **in** the cluster) now says `command not found`, so I installed it as described [here](https://docs.cilium.io/en/v1.12/gettingstarted/k8s-install-default/#install-the-cilium-cli)
- `cilium status` (again I ran it **in** the cluster) gives me an error: 
`Get "http://localhost:8080/apis/apps/v1/namespaces/kube-system/daemonsets/cilium": dial tcp 127.0.0.1:8080: connect: connection refused`

Not sure what I am doing wrong.

**Comment by rowansmithau** [comment]
encountered the same issue, did the following to get it up and running:

1. Ran `minikube ssh`
2. Installed the Cilium CNI per https://docs.cilium.io/en/v1.12/gettingstarted/k8s-install-default/#install-the-cilium-cli
3. Ran `ps -ef | grep kube-apiserver` in order to show the `advertise-address` value (for me, 192.168.49.2) [A]
4. created `/home/docker/.kube/config` and copied in the config from the host machine, including the certificates, updating the certificate paths as needed.
5. Running `cilium status` showed the expected positive output.
6. Ran `cilium hubble enable` however it seems to fail. [B]
7. Cilium pod logs seem to get stuck at `level=info msg="Waiting for Hubble server TLS certificate and key files to be created" subsys=hubble` which pointed me to https://github.com/cilium/cilium-cli/issues/300 however that issue is from a while ago.
8. Per the linked issue I ran `cilium hubble enable --create-ca` 
9. it's still broken and times out with waiting for cert and key creation :( 

A:
```
docker@minikube:~$ ps -ef | grep kube-apiserver
root        2300    2281  6 05:27 ?        00:15:06 kube-apiserver --advertise-address=192.168.49.2 --allow-p.....
```

B:
```
docker@minikube:~$ cilium hubble enable
⚠️  Error parsing helm cli secret: unable to retrieve helm values secret kube-system/cilium-cli-helm-values: secrets "cilium-cli-helm-values" not found
⚠️  Proceeding in unknown installation state
🔮 Auto-detected cilium version v1.15.3
🔑 Found CA in secret cilium-ca
ℹ️  helm template --namespace kube-system cilium cilium/cilium --version 1.15.3 --set hubble.enabled=true,hubble.relay.enabled=true,tls.ca.cert=LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNGVENDQWJxZ0F3SUJBZ0lVUVhzMHN3ZTYwSlVVelk3VzdtRTRuQXZMTzdFd0NnWUlLb1pJemowRUF3SXcKYURFTE1Ba0dBMVVFQmhNQ1ZWTXhGakFVQmdOVkJBZ1REVk5oYmlCR2NtRnVZMmx6WTI4eEN6QUpCZ05WQkFjVApBa05CTVE4d0RRWURWUVFLRXdaRGFXeHBkVzB4RHpBTkJnTlZCQXNUQmtOcGJHbDFiVEVTTUJBR0ExVUVBeE1KClEybHNhWFZ0SUVOQk1CNFhEVEkwTURjeU16QTVNVGt3TUZvWERUSTVNRGN5TWpBNU1Ua3dNRm93YURFTE1Ba0cKQTFVRUJoTUNWVk14RmpBVUJnTlZCQWdURFZOaGJpQkdjbUZ1WTJselkyOHhDekFKQmdOVkJBY1RBa05CTVE4dwpEUVlEVlFRS0V3WkRhV3hwZFcweER6QU5CZ05WQkFzVEJrTnBiR2wxYlRFU01CQUdBMVVFQXhNSlEybHNhWFZ0CklFTkJNRmt3RXdZSEtvWkl6ajBDQVFZSUtvWkl6ajBEQVFjRFFnQUV4bWo2a3VRTHBJcFVPaVZITUlQWUpnQTcKTkZFamZyR3MwMWNkYnNleXlzMUc2d2U0cUM5V0EwcEdxMk9JcWFpVWovRG5CSGhjVjJKUGRpY3dScEJqZjZOQwpNRUF3RGdZRFZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSGtpCjBJNk54QXNIRHR6aitNSlhDRVVYcDJkTE1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQ0l2anBabXRJZVNoWmMKWjdtWmtCMHI1SjIzMWxLeWg4bFR5c2ZGMnZKaTZRSWhBSmtQVVdDOXRxNmZYMFo5N2hEVVVsNzg4YldVM2RJagoxWTdDQWpJOWVxcjYKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=,tls.ca.key=[--- REDACTED WHEN PRINTING TO TERMINAL (USE --redact-helm-certificate-keys=false TO PRINT) ---]
✨ Patching ConfigMap cilium-config to enable Hubble...
🚀 Creating ConfigMap for Cilium version 1.15.3...
♻️  Restarted Cilium pods
⌛ Waiting for Cilium to become ready before deploying other Hubble component(s)...
    /¯¯\
 /¯¯\__/¯¯\    Cilium:             1 warnings
 \__/¯¯\__/    Operator:           OK
 /¯¯\__/¯¯\    Envoy DaemonSet:    disabled (using embedded mode)
 \__/¯¯\__/    Hubble Relay:       disabled
    \__/       ClusterMesh:        disabled

DaemonSet         cilium             Desired: 1, Ready: 1/1, Available: 1/1
Deployment        cilium-operator    Desired: 1, Ready: 1/1, Available: 1/1
Containers:       cilium-operator    Running: 1
                  cilium             Running: 1
Cluster Pods:     7/7 managed by Cilium
Image versions    cilium             quay.io/cilium/cilium:v1.15.3@sha256:da74ab61d1bc665c1c088dff41d5be388d252ca5800f30c7d88844e6b5e440b0: 1
                  cilium-operator    quay.io/cilium/operator-generic:v1.15.3@sha256:c97f23161906b82f5c81a2d825b0646a5aa1dfb4adf1d49cbb87815079e69d61: 1
Warnings:         cilium             cilium-s24h4    Hubble: Server not initialized


Error: Unable to enable Hubble: timeout while waiting for status to become successful: context deadline exceeded
```

C:
