### ISSUE TITLE
Multi nodes Hyper-V resolves DNS wrong

### ISSUE THREAD

**Issue by VerdonTrigance** [kubernetes/minikube#14665]
### What Happened?

1. Set driver to Hyper-V
 ```
minikube config view
- EmbedCerts: true
- cpus: 6
- driver: hyperv
- memory: 4096
```
2. minikube start --nodes 3 (I use Default Switch)
3. check in hyper-v manager 3 VMs with names minikube, minikube-m02, minikube-m03
4. check etc\hosts.ics. There should be a record like this:
`172.18.128.234 minikube.mshome.net # 2022 8 4 4 13 15 45 148`
5. save VMs with Hyper-V manager in this order: from minikube-m03 to minikube.
6. start VMs with Hyper-V manager in this order: from minikube to minikube-m03.
7. check etc\hosts.ics again. IP has been changed from 172.18.128.234 to minikube-m03's IP - 172.18.141.220.
8. check it with ping.
```
ping minikube.mshome.net

Pinging minikube.mshome.net [172.18.141.220] with 32 bytes of data:
Reply from 172.18.141.220: bytes=32 time<1ms TTL=64
```
9. Because of that any ingress rules that was configured to minikube host are become broken.
10. Repeat step 5
11. Now try to start VMs in different order: from minikube-m03 to minikube.
12. check hosts.ics again. Now it has 172.18.128.234 back.

So we can see that start order is important. But why? Is it problem of Hyper-V or minikube? Who set these changes in hosts.ics file? 

### Attach the log file

[log_tmp.txt](https://github.com/kubernetes/minikube/files/9210288/log_tmp.txt)

### Operating System

Windows

### Driver

Hyper-V

**Comment by VerdonTrigance** [comment]
As I know hosts.ics is managed by ICS, but I'm not sure how it does it. I have a picture in my mind: guest VM do DHCP request to DHCP server which is somewhere in a host, after that DHCP response with IP to guest and dynamically writes a record into hosts.ics. If guest (with minikube scripts) somehow can specify it's DNS name within that DHCP request than it's a minikube fault and it responsible to fix it. If it's not than Hyper-V do this under the hood. But probably it's not Hyper-V because another VMs works fine.

**Comment by klaases** [comment]
Hi @VerdonTrigance, did you find out more as to whether this is a part of minikube or hyperkit?

**Comment by VerdonTrigance** [comment]
No, I can’t figure out this. But question is why any other resources that use ics file are fine? I mean different VMs with same network switch are change theirs IP properly, but not minikube VMs?

**Comment by klaases** [comment]
Hi @VerdonTrigance – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

**Comment by VerdonTrigance** [comment]
> Hi @VerdonTrigance – is this issue still occurring? Were you able to find a solution?
> 
> For additional assistance, please consider reaching out to the minikube community:
> 
> https://minikube.sigs.k8s.io/community/
> 
> We also offer support through Slack, Groups, and office hours.

Yes. Situation is same right now. I don’t have solution and hope you have one.
