### ISSUE TITLE
X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1 stdout:  stderr: sudo: crictl: command not found

### ISSUE THREAD

**Issue by Priyauttu** [kubernetes/minikube#14676]
### What Happened?

I have many times to start minikube. But always this error is shown.

### Attach the log file

![error](https://user-images.githubusercontent.com/105982145/181807331-064702cc-5ca2-4eda-af54-f4511310ff6c.jpg)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
You need to install `crictl` from [cri-tools](https://github.com/kubernetes-sigs/cri-tools)

**Comment by dcambronero** [comment]
Thanks!! that solved the issue

**Comment by Jkudjo** [comment]
Thus Helped . Thanks

**Comment by shantanudatarkar** [comment]
not work

**Comment by QasimSultani** [comment]
not work for me

**Comment by ashwin974** [comment]
If is not work try this:

wget https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.25.0/crictl-v1.25.0-linux-amd64.tar.gz
sudo tar zxvf crictl-v1.25.0-linux-amd64.tar.gz -C /usr/local/bin

in root mode you can start minikube with this command : minikube start --driver=none

**Comment by QasimSultani** [comment]
Appreciate for your response it's work after sending several hours

**Comment by marswhc** [comment]
Make a symbolic link solved it.

`ln -s /usr/local/bin/crictl /usr/bin/crictl`

**Comment by caubenganha** [comment]
Please try this solution

VERSION="v1.25.0"
wget https://github.com/kubernetes-sigs/cri-tools/releases/download/$VERSION/crictl-$VERSION-linux-amd64.tar.gz
sudo tar zxvf crictl-$VERSION-linux-amd64.tar.gz -C /usr/local/bin
rm -f crictl-$VERSION-linux-amd64.tar.gz

Hope to help you!

**Comment by ImaneKABKAB** [comment]
> Make a symbolic link solved it.
> 
> `ln -s /usr/local/bin/crictl /usr/bin/crictl`

Thank you so much it works

**Comment by ImaneKABKAB** [comment]
> You need to install `crictl` from [cri-tools](https://github.com/kubernetes-sigs/cri-tools) (new for 1.24)
> 
> See https://minikube.sigs.k8s.io/docs/drivers/non
Thank it works

**Comment by mudassirsyed39** [comment]
Thanks a lot, that solved the problem.

**Comment by victordavidalarcon** [comment]
Ya no sirve al ejecutar --2022-11-26 21:47:57--  https://github.com/kubernetes-sigs/cri-tools/releases/download//crictl--linux-amd64.tar.gz
Resolviendo github.com (github.com)... 140.82.113.4
Conectando con github.com (github.com)[140.82.113.4]:443... conectado.
Petición HTTP enviada, esperando respuesta... 404 Not Found
2022-11-26 21:47:57 ERROR 404: Not Found.

parece que la solucion ya no funciona y me quede atascado alguien tiene otra forma de solcuionar?

**Comment by victordavidalarcon** [comment]
> > Necesita instalar `crictl`desde [cri-tools](https://github.com/kubernetes-sigs/cri-tools) (nuevo para 1.24)
> > Consulte https://minikube.sigs.k8s.io/docs/drivers/non 
> > Gracias, funciona

Not found
Oops! This page doesn't exist. Try going back to the [home page](https://minikube.sigs.k8s.io/).

**Comment by BijenderRana** [comment]
> ln -s /usr/local/bin/crictl /usr/bin/crictl

its working for me, Thanks
