### ISSUE TITLE
aarch64: CONFIG_BPF_SYSCALL=y is missing

### ISSUE THREAD

**Issue by kakkoyun** [kubernetes/minikube#14674]
### What Happened?

I'm trying to run an eBPF application on Minikube on a Mac using QEMU (--drive=qemu2). 

The first thing I realized when I tried to mount `/sys/fs/bpf`, it wasn't there.

Then when I tried to load an eBPF program, I got the following error.

```
libbpf: Error in bpf_object__probe_loading():Function not implemented(38). 
Couldn't load trivial BPF program. 
Make sure your kernel supports BPF (CONFIG_BPF_SYSCALL=y) and/or that RLIMIT_MEMLOCK is set to big enough value.
libbpf: failed to load object 'XXX'
```

This is what the config looks like:
```
$ cat /proc/config.gz | gunzip | grep CONFIG_BPF
CONFIG_BPF=y
# CONFIG_BPF_SYSCALL is not set
CONFIG_BPF_JIT_DEFAULT_ON=y
# CONFIG_BPFILTER is not set
CONFIG_BPF_JIT=y
```

FWIW, the same program flawlessly runs on minikube on a linux/amd64 platform.
I had assumed with https://github.com/kubernetes/minikube/pull/14316, this should work regardless of the driver.

I might be missing something trivial. I'd be glad if you could nudge me in the right direction.

cc @eiffel-fl

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9221421/log.txt)

### Operating System

macOS (Default)

### Driver

N/A

**Comment by afbjorklund** [comment]
> FWIW, the same program flawlessly runs on minikube on a linux/amd64 platform.

But that kernel config has `CONFIG_BPF_SYSCALL=y` set

**Comment by kakkoyun** [comment]
> > FWIW, the same program flawlessly runs on minikube on a linux/amd64 platform.
> 
> But that kernel config has `CONFIG_BPF_SYSCALL=y` set, where the linux/arm64 does not

Now that I checked. Yes, it is defined for x86_64 https://github.com/kubernetes/minikube/blob/632839e77d6aae61bcea96dedda90e31e8401f52/deploy/iso/minikube-iso/board/minikube/x86_64/linux_x86_64_defconfig#L44

But it is not defined for aarch64
https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/board/minikube/aarch64/linux_aarch64_defconfig

I think it's overlooked. If you can confirm, I'm happy to contribute.

**Comment by carlosonunez** [comment]
Not stale. This is preventing Calico from working on "qemu2" minikube nodes (which you'll need to use if you want VM-based nodes on Apple Silicon).
