### ISSUE TITLE
Exiting due to RUNTIME_ENABLE: sudo service cri-docker.socket start: Process exited with status 5

### ISSUE THREAD

**Issue by nidhish1** [kubernetes/minikube#14672]
### What Happened?

stderr:
Failed to start cri-docker.socket.service: Unit cri-docker.socket.service not found.

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │

### Attach the log file

stderr:
Failed to start cri-docker.socket.service: Unit cri-docker.socket.service not found.

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
Hmm, this is supposed to be "cri-docker.socket" _or_ "cri-docker.service" - not **both**

Where did this error come from, do you have any logs to go with it perhaps ?

**Comment by klaases** [comment]
Hi @nidhish1, did you have a chance to review @afbjorklund's inquiry?

/kind support

**Comment by klaases** [comment]
Hi @nidhish1 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
