### ISSUE TITLE
Issue during start minikube start (CentOS Linux 7 (Core))

### ISSUE THREAD

**Issue by MohSulta** [kubernetes/minikube#14679]
### What Happened?

issue during start the minikube the OS (CentOS) installed on the VM in VMware
 

hostnamectl>
      Static hostname: localhost.localdomain
      Icon name: computer-vm
      Chassis: vm
      Machine ID: d6ae6176edd34554afef3cda98e32054
      Boot ID: 0da86e032c574b04a592027316860766
      Virtualization: vmware
      Operating System: CentOS Linux 7 (Core)
      CPE OS Name: cpe:/o:centos:centos:7
      Kernel: Linux 3.10.0-1160.71.1.el7.x86_64
      Architecture: x86-64

### Attach the log file

[](url
[Mylogs.txt](https://github.com/kubernetes/minikube/files/9224063/Mylogs.txt)
)

### Operating System

Other

### Driver

VMware

**Comment by afbjorklund** [comment]
Same as:

* https://github.com/kubernetes/minikube/issues/14410
