### ISSUE TITLE
minikube addons enable ingress - Failed

### ISSUE THREAD

**Issue by pransukh** [kubernetes/minikube#14684]
### What Happened?

minikube addons enable ingress command doesn't end well.
My purpose was to use ingress service but it failed.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9229495/logs.txt)

### Operating System

Windows

### Driver

Hyper-V

**Comment by maksat-yskak** [comment]
I guess I have same error. Getting `ErrImagePull` for ingress-nginx-controller. Tried on Windows 10 with Hyper-V and Docker drivers. Then tried on Ubuntu with Docker driver. 

Also lately I had `ErrImagePull` when tried to deploy mongo. But light images deploy without any issue, like nginx and mongo-express. Then tried to workaround with `minikube image pull mongo`, and pod was created. Couldn't pull ingress image though. Is it even possibel to pull addon image like that?

1. 300 sec / 6 min timeout
2. Slow internet (8Mb/s)
3. Location: Kazakhstan

[minikube_addons_ead353e65a8710fdf0e628d00169f7c723a4d1bb_0.log](https://github.com/kubernetes/minikube/files/9229569/minikube_addons_ead353e65a8710fdf0e628d00169f7c723a4d1bb_0.log)
[log.txt](https://github.com/kubernetes/minikube/files/9229570/log.txt)

**Comment by maksat-yskak** [comment]
My issue solved on Windows and Linux with changing ISP to mobile data, and images got pulled. Ridiculous.

**Comment by pransukh** [comment]
> My issue solved on Windows and Linux with changing ISP to mobile data, and images got pulled. Ridiculous.

Should i consider it as solution ? 😄

I tried updating the ingress-deployment.yaml in minikube srever but still no success.

**Comment by klaases** [comment]
Hi @pransukh, yes sometimes the ISP or network proxy, settings, etc. are unable to reach the images.

Please try another network to see if it works, or you can also try to `curl` the network resources directly to see if things work regardless of minikube.

@maksat-yskak, glad that you were able to find a network solution that worked.

**Comment by pransukh** [comment]
> Hi @pransukh, yes sometimes the ISP or network proxy, settings, etc. are unable to reach the images.
> 
> Please try another network to see if it works, or you can also try to `curl` the network resources directly to see if things work regardless of minikube.
> 
> @maksat-yskak, glad that you were able to find a network solution that worked.

@klaases 
minikube delete command solved the issue for me, but it happened at random i don't know what exactly solved the issue.

**Comment by pransukh** [comment]
minikube delete command solved the issue for me, but it happened at random i don't know what exactly solved the issue.
