### ISSUE TITLE
minikuber start issue

### ISSUE THREAD

**Issue by MohSulta** [kubernetes/minikube#14681]
### What Happened?

when i tried to start minikube  i faced error that:
 minikube start
* minikube v1.26.0 on Centos 7.9.2009
* Using the none driver based on existing profile

X Requested memory allocation (1838MB) is less than the recommended minimum 1900MB. Deployments may fail.

* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is CentOS Linux 7 (Core)

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

the issue if i type command without sudo the command run as normal as:crictl version
Version:  0.1.0
RuntimeName:  docker
RuntimeVersion:  20.10.17
RuntimeApiVersion:  1.41.0
but if i use sudo crictl version tha command doesn't work , kindly i need support for this issue sine my OS is Centos linux 

### Attach the log file

[](url
[mylogs.txt](https://github.com/kubernetes/minikube/files/9226605/mylogs.txt)
)

### Operating System

Other

### Driver

VMware

**Comment by afbjorklund** [comment]
You need to install `crictl` from [cri-tools](https://github.com/kubernetes-sigs/cri-tools) (new for 1.24)

See https://minikube.sigs.k8s.io/docs/drivers/none/

**Comment by afbjorklund** [comment]
Wonder why this is still an issue ? Should have been fixed.

* https://github.com/kubernetes/minikube/issues/5547

**Comment by afbjorklund** [comment]
Problem was with the new code, not noticed since CentOS is not tested.

* https://github.com/kubernetes/minikube/issues/3552

**Comment by afbjorklund** [comment]
Workarounds meanwhile are to move the `crictl` binary.

Or use a supported operating system, like Ubuntu LTS.

**Comment by JesudassJosephraj** [comment]
1.Install docker
2.install kubectl
3.install minikube according to you device compatibility (https://minikube.sigs.k8s.io/docs/start/)
4.once all done before starting minikube install conntrack ( apt install conntrack)
5. After that if you get any error like juju,cric dockered id, cric ctl not found any error it may be..
6. jusz give this command minikube start --force
7. Minikube works without any error following above steps..

**Comment by klaases** [comment]
Hi @MohSulta, did you have a chance to install `crictl`?

> crictl is a command-line interface for CRI-compatible container runtimes. You can use it to inspect and debug container runtimes and applications on a Kubernetes node. crictl and its source are hosted in the [cri-tools](https://github.com/kubernetes-sigs/cri-tools) repository.

https://kubernetes.io/docs/tasks/debug/debug-cluster/crictl/#installing-crictl

/triage needs-information
/kind support

**Comment by klaases** [comment]
Hi @MohSulta – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!

**Comment by MohSulta** [comment]
This issue happened we I was use centos Linux , I delete it and I have
installed Ubuntu then I install minikube and  I did face the issue again
