### ISSUE TITLE
Failed to enable unit: Unit file cri-docker.socket does not exist.

### ISSUE THREAD

**Issue by ajitgupta123** [kubernetes/minikube#14686]
### What Happened?

root@ip-172-31-37-85:/home/ubuntu# minikube start --vm-driver=none
😄  minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 18.04.6 LTS

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9231480/log.txt)

### Operating System

Ubuntu

**Comment by afbjorklund** [comment]
Same issue as:
* https://github.com/kubernetes/minikube/issues/14410

**Comment by JesudassJosephraj** [comment]
1.Install docker
2.install kubectl
3.install minikube according to you device compatibility (https://minikube.sigs.k8s.io/docs/start/)
4.once all done before starting minikube install conntrack ( apt install conntrack)
5. After that if you get any error like juju,cric-dockerd id, cric ctl not found any error it may be..
6. jusz give this  command minikube start --force
7. Minikube works without any error following above steps..

**Comment by klaases** [comment]
Hi @ajitgupta123 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
