### ISSUE TITLE
kubectl

### ISSUE THREAD

**Issue by nirshif** [kubernetes/minikube#14685]
### What Happened?

PS C:\WINDOWS\system32> kubectl status
error: unknown command "status" for "kubectl"
PS C:\WINDOWS\system32> kubectl describe pod
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\WINDOWS\system32> kubectl apply
error: must specify one of -f and -k
PS C:\WINDOWS\system32> kubectl get nods
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\WINDOWS\system32> minikube start -p aged --kubernetes-version=v1.16.1
* [aged] minikube v1.26.0 on Microsoft Windows 11 Pro 10.0.22000 Build 22000
* Automatically selected the hyperv driver. Other choices: virtualbox, ssh
* Starting control plane node aged in cluster aged
* Creating hyperv VM (CPUs=2, Memory=16384MB, Disk=20000MB) ...\ E0731 21:30:50.221860   18128 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'aged' failed to start.
Unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
'aged' failed to start. (Virtual machine ID 5C01DC5F-08CD-47ED-9411-4B6D61CE1BCE)
'aged' is unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID
5C01DC5F-08CD-47ED-9411-4B6D61CE1BCE)
At line:1 char:1
+ Hyper-V\Start-VM aged
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM

* Stopping node "aged"  ...
* Deleting "aged" in hyperv ...
! StartHost failed, but will try again: creating host: create: creating: exit status 1
* Creating hyperv VM (CPUs=2, Memory=16384MB, Disk=20000MB) ...| E0731 21:32:12.776874   18128 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'aged' failed to start.
Unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
'aged' failed to start. (Virtual machine ID EF3B8020-8F90-48C9-90FA-5BDA94FCC769)
'aged' is unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID
EF3B8020-8F90-48C9-90FA-5BDA94FCC769)
At line:1 char:1
+ Hyper-V\Start-VM aged
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete -p aged" may fix it: creating host: create: creating: exit status 1
! Startup with hyperv driver failed, trying with alternate driver virtualbox: Failed to start host: creating host: create: creating: exit status 1
* Stopping node "aged"  ...
* Deleting "aged" in hyperv ...
! Failed to delete cluster aged, proceeding with retry anyway.
* Starting control plane node aged in cluster aged
* Creating virtualbox VM (CPUs=2, Memory=16384MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Creating virtualbox VM (CPUs=2, Memory=16384MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete -p aged" may fix it: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: exit status 1

### Attach the log file

PS C:\WINDOWS\system32> kubectl status
error: unknown command "status" for "kubectl"
PS C:\WINDOWS\system32> kubectl describe pod
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\WINDOWS\system32> kubectl apply
error: must specify one of -f and -k
PS C:\WINDOWS\system32> kubectl get nods
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.
PS C:\WINDOWS\system32> minikube start -p aged --kubernetes-version=v1.16.1
* [aged] minikube v1.26.0 on Microsoft Windows 11 Pro 10.0.22000 Build 22000
* Automatically selected the hyperv driver. Other choices: virtualbox, ssh
* Starting control plane node aged in cluster aged
* Creating hyperv VM (CPUs=2, Memory=16384MB, Disk=20000MB) ...\ E0731 21:30:50.221860   18128 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'aged' failed to start.
Unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
'aged' failed to start. (Virtual machine ID 5C01DC5F-08CD-47ED-9411-4B6D61CE1BCE)
'aged' is unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID
5C01DC5F-08CD-47ED-9411-4B6D61CE1BCE)
At line:1 char:1
+ Hyper-V\Start-VM aged
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM

* Stopping node "aged"  ...
* Deleting "aged" in hyperv ...
! StartHost failed, but will try again: creating host: create: creating: exit status 1
* Creating hyperv VM (CPUs=2, Memory=16384MB, Disk=20000MB) ...| E0731 21:32:12.776874   18128 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'aged' failed to start.
Unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
'aged' failed to start. (Virtual machine ID EF3B8020-8F90-48C9-90FA-5BDA94FCC769)
'aged' is unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA). (Virtual machine ID
EF3B8020-8F90-48C9-90FA-5BDA94FCC769)
At line:1 char:1
+ Hyper-V\Start-VM aged
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete -p aged" may fix it: creating host: create: creating: exit status 1
! Startup with hyperv driver failed, trying with alternate driver virtualbox: Failed to start host: creating host: create: creating: exit status 1
* Stopping node "aged"  ...
* Deleting "aged" in hyperv ...
! Failed to delete cluster aged, proceeding with retry anyway.
* Starting control plane node aged in cluster aged
* Creating virtualbox VM (CPUs=2, Memory=16384MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Creating virtualbox VM (CPUs=2, Memory=16384MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete -p aged" may fix it: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: exit status 1

### Operating System

Windows

### Driver

Hyper-V

**Comment by klaases** [comment]
> * Unable to allocate 16384 MB of RAM: Insufficient system resources exist to complete the requested service.

Hi @nirshif, it may be that there are insufficient resources available on your machine. Would you be able to allocate less memory to your VM?

**Comment by klaases** [comment]
Hi @nirshif – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
