### ISSUE TITLE
minikube installation issue on ubuntu

### ISSUE THREAD

**Issue by azharism123** [kubernetes/minikube#14682]
minikube start --driver=none    while performing the command

**Comment by azharism123** [comment]
f the above advice does not help, please let us k                                                                 now:                                 │
│      https://github.com/kubernetes/minikube/issues/new/                                                                 choose                               │
│                                                                                                                                                              │
│    * Please run `minikube logs --file=logs.txt` and att                                                                 ach logs.txt to the GitHub issue.    │
│

**Comment by vinnyzhaowenyu** [comment]
you should upload your `logs.txt` file or contents

**Comment by JesudassJosephraj** [comment]
1.Install docker
2.install kubectl
3.install minikube according to you device compatibility (https://minikube.sigs.k8s.io/docs/start/)
4.once all done before starting minikube install conntrack ( apt install conntrack)
5. After that if you get any error like juju,cric id, cric ctl not found any error it may be..
6. jusz give this command minikube start --force
7. Minikube works without any error following above steps..

**Comment by klaases** [comment]
Hi @azharism123, did you have a chance to review the above comments?

Else we may close the issue due to inactivity.

**Comment by spowelljr** [comment]
Hi @azharism123, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
