### ISSUE TITLE
prototype minikube qemu driver with dedicated network

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#14692]
### What Happened?

https://github.com/lima-vm/vde_vmnet

### Attach the log file

n/a

**Comment by afbjorklund** [comment]
There are some similar solutions to this, that might also be used.

For mac, there is "vde" and "socket". For linux, there is "tap" and "bridge"

(for reference, the default networking is called "user" and uses "slirp" lib)

More details on: https://wiki.qemu.org/Documentation/Networking

----

The main difference is that with "user", your IP is **not** accessible from host (like Docker Desktop)

This means that every node will be "10.0.2.15", and we need to use tunneling to reach it from host.

But when using "vde" (or the others), you get an IP address reachable from host (like Docker Engine)

This is more similar to the traditional minikube setup (before kic), with things like `minikube ip` etc

**Comment by afbjorklund** [comment]
In the qemu driver, this is chosen with the "network" parameters:

```
 docker-machine create --driver qemu --help | grep net
   --qemu-network "user"										Name of network to connect to (user, tap, bridge)
   --qemu-network-address 										IP of the network adress to be used for networking (for tap)
   --qemu-network-bridge "br0"										Name of the network bridge to be used for networking (for bridge)
   --qemu-network-interface "tap0"									Name of the network interface to be used for networking (for tap)
   --qemu-network-socket "tap0"										Path of the network socket to be used for networking (for vde)
```

In the code, it's in `Network` and `NetworkSocket`

**Comment by AkihiroSuda** [comment]
vde_vmnet will be deprecated by https://github.com/lima-vm/socket_vmnet

**Comment by afbjorklund** [comment]
> vde_vmnet will be deprecated by https://github.com/lima-vm/socket_vmnet

I think it will work the same, just replace Network: "vde" with Network: "socket"

`-netdev vde,id=net0,sock=/var/run/vde.ctl`

`-netdev socket,id=net0,fd=3`

However, it might require some more code to do the prefix command wrapper ?

`/opt/socket_vmnet/bin/socket_vmnet_client /var/run/socket_vmnet ...`

There is no such execution parameter, in the current qemu driver at least.

```
   --qemu-program "qemu-system-x86_64"									Name of program to run
```

But it shouldn't be a big change, later on.

**Comment by afbjorklund** [comment]
It would need some code to pass the fd, either way :-) And for the network type

**Comment by afbjorklund** [comment]
If I understand this prototype correctly, the user will be required to set up the network:

sudo vde_vmnet --vmnet-gateway=192.168.105.1 /tmp/vde.ctl

sudo socket_vmnet --vmnet-gateway=192.168.105.1 /tmp/socket_vmnet

And then the socket will be passed to the minikube start as a parameter

**Comment by AkihiroSuda** [comment]
Btw QEMU 7.1 will add [the native support for vmnet](https://github.com/qemu/qemu/commit/81ad2964e93848fc0998145043c395dea67f00da), but that requires running the entire QEMU as the root (So I'm not going to use it for Lima)

**Comment by afbjorklund** [comment]
Sounds good! I don't know how slow slirp is compared to the other two, but it will probably stay as the default.

**Comment by klaases** [comment]
So far have tried the following on Mac M1, but need to find another approach:

```
$ sudo make PREFIX=/opt/vde install
Password:
make: *** No rule to make target `install'.  Stop.
```
