### ISSUE TITLE
Support different type of network adapter besides host-only

### ISSUE THREAD

**Issue by sunghospark** [kubernetes/minikube#1471]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

I'm sure there are reasons why minikube is specifically using host-only adapter only for networking but I couldn't find a thread yet.

It would be nice to have an option to use different network adapter which will make exposing minikube services easier.

**Minikube version** (use `minikube version`):  v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.18.0.iso
- **Install tools**: brew
- **Others**:

**What happened**:

Trying to expose services running in minikube via port forwarding, but couldn't find an easy way to do so because of host-only network adapter

**What you expected to happen**:

Have an option to use NAT or bridged network for minikube.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by ikulis** [comment]
After creating minicube you can just change the adapter in Virtualbox settings for the vm, like for any other.

**Comment by caseeker** [comment]
@ikulis when network adapter is changed, minikube commands stop working.
```
minikube start                                                                                              351ms  Wed May 10 09:36:19 2017
Starting local Kubernetes cluster...
Starting VM...
E0510 09:37:21.859481   32740 start.go:116] Error starting host: Temporary Error: Error configuring auth on host: Temporary Error: Machine does not have a host-only adapter
Temporary Error: Machine does not have a host-only adapter
```

```
minikube ip                                                                                                                  Wed May 10 09:36:49 2017
E0510 09:38:41.173485   32910 ip.go:48] Error getting IP:  Machine does not have a host-only adapter
```

**Comment by aaron-prindle** [comment]
We don't currently support using a bridged network.  Could you describe your use case for this?

**Comment by caseeker** [comment]
@aaron-prindle Yes, developers are using minikube as dev environment on their laptop and they want to expose few services for testing with external components.

**Comment by jylin** [comment]
One use case, which I think the original bug alludes to, is to allow exposing services running in minikube to the internet. I'm guessing if you set a router to port forward to the minikube IP, it doesn't currently work. I know there are ways to remap ports with netcat and such, but it would be cleaner if there was some way to directly expose services.

**Comment by juguerre** [comment]
This would be great.

**Comment by rafaelsoaresbr** [comment]
It could be possible to do something like what is possible with docker-machine:
```
docker-machine create --driver generic --generic-ip-address=203.0.113.81 --generic-ssh-key ~/.ssh/id_rsa vm_name
```

**Comment by gclawes** [comment]
Similar use case is running minikube on a libvirt/virtualbox machine (headless server) and accessing it from other hosts on the local network (laptop).

**Comment by mcwienczek** [comment]
I've been able to use NAT network in virtualbox and then setting up port-forwarding. But I agree that bridged network would be much more elegant solution.

**Comment by sebinsua** [comment]
@mcwienczek How was this done?

**Comment by mcwienczek** [comment]
https://cwienczek.com/reaching-minikube-from-your-machines-public-ip-aka-network-bridge/

**Comment by timothyclarke** [comment]
I'd still like this feature
/remove-lifecycle rotten

**Comment by nano2007** [comment]
I am able to get around this problem with an additional bridged network configured for the minikube VM (I am running minikube on a Mac).

**Comment by JonDum** [comment]
This is still a huge issue for me. My use case is simple: I'd like to be able to expose services for development (y'know, the whole point of minikube). With Docker Swarm I can access exposed containers via `localhost:port` with no configuration. With minikube, however, I cannot access anything at all regardless of Ingress/LoadBalancer/NodePort configurations nor `kubectl proxy`. 

Worse yet there's no mention of this anywhere in the docs that I've found after hours of scouring and googling. How am I supposed to test and develop without being able to access anything?

/reopen
/remove-lifecycle rotten

**Comment by timothyclarke** [comment]
@JonDum Can you confirm if you're talking about local access, or remote access?

/reopen
/remove-lifecycle rotten

**Comment by JonDum** [comment]
@timothyclarke yea just normal local access from host laptop

**Comment by timothyclarke** [comment]
Last time I was using minikube I just used `minikube addons enable ingress` then standard ingresses worked fine. I cannot remember if I added `stable/nginx-ingress` or if the ingress addon above did that for me.
I believe I added a hosts file entry to bypass dns

**Comment by EdByrnee** [comment]
> I am able to get around this problem with an additional bridged network configured for the minikube VM (I am running minikube on a Mac).

You are able to give minikube an IP on your local network ??

**Comment by deepdad** [comment]
Port forwarding using VirutalBox NAT usually works, but with minikube, it seems like requests keep being routed to the host only network. When I use `./ncat -l -p 8080 --sh-exec "./ncat 127.0.0.1 8080"` on my Mac, I can get WAN access to the services on minikube:

```
$ kubectl get svc --all-namespaces
NAMESPACE     NAME                   TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default       cheddar-cheese         NodePort    10.105.31.148    <none>        80:30598/TCP             56m
default       echoserver             NodePort    10.105.22.175    <none>        8080:30718/TCP           65m
default       kubernetes             ClusterIP   10.96.0.1        <none>        443/TCP                  76m
default       stilton-cheese         NodePort    10.102.46.75     <none>        80:31908/TCP             58m
kube-system   default-http-backend   NodePort    10.96.6.74       <none>        80:30001/TCP             67m
kube-system   kube-dns               ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   76m
kube-system   kubernetes-dashboard   ClusterIP   10.111.168.166   <none>        80/TCP                   76m
```

<img width="651" alt="Screenshot 2019-07-30 at 12 36 42" src="https://user-images.githubusercontent.com/22483621/62122776-c6cb6d00-b2c6-11e9-8fa5-265207b55288.png">

This is obviously kind of strange. I'm thinking that the router or Mac host drop something, but everything seems to come through:

```
$ ./ncat -l -p 8080
GET / HTTP/1.1
Host: xxx.nl
Upgrade-Insecure-Requests: 1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.1 Safari/605.1.15
Accept-Language: en-us
Accept-Encoding: gzip, deflate
Connection: keep-alive
```
