### ISSUE TITLE
cri-dockerd v0.2.4 does not work out of the box with minikube

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [kubernetes/minikube#14724]
### What Happened?

https://github.com/Mirantis/cri-dockerd/releases/tag/v0.2.4 now defaults to using the `kubenet` network plugin (https://github.com/Mirantis/cri-dockerd/pull/99). This does not work, at least with the none driver.

The cri-dockerd README suggests the `cni` driver as perhaps an alternative, but this doesn't work either.

Only by checking the old code from cri-dockerd v0.2.3 can one find that it used to run with "no" network plugin (`--network-plugin=` on the cri-dockerd command line) as a valid arg, and that is what is needed to make it work.

### Attach the log file

With the `kubenet` driver, kubelet reports:
```
Aug 03 16:04:29 MYHOSTNAME kubelet[3512192]: E0803 16:04:29.502654 3512192 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: could not locate kubenet required CNI plugins [bridge host-local loopback] at [\"/opt/cni/bin\" \"/opt/cni/bin\"]"
```
and the node never becomes ready and so no pod is ever scheduled.

With the `cni` driver:
```
Aug 03 16:05:15 MYHOSTNAME kubelet[3517922]: E0803 16:05:15.295210 3517922 kubelet.go:2349] "Container runtime network not ready" networkReady="NetworkReady=false reason:NetworkPluginNotReady message:docker: network plugin is not ready: cni config uninitialized"
```

### Operating System

Ubuntu

### Driver

None (Baremetal)

**Comment by afbjorklund** [comment]
This seems like a breaking change from upstream

**Comment by afbjorklund** [comment]
It is fixed by this PR, which _always_ sets the network plugin: (avoids the previous shortcut)

* https://github.com/kubernetes/minikube/pull/14703

**Comment by afbjorklund** [comment]
@mgabeler-lee-6rs the errors (with "cni") seems weird, it is like CNI plugins were not properly installed ?

`network plugin is not ready: could not locate kubenet required CNI plugins [bridge host-local loopback] at [\"/opt/cni/bin\" \"/opt/cni/bin\"]`

`network plugin is not ready: cni config uninitialized`

If not using the "no-op" (previous default network plugin), then both `cri-tools` and `cni-plugins` are required.

* https://github.com/kubernetes-sigs/cri-tools

* https://github.com/containernetworking/plugins

When installing kubernetes from packages, these are installed as requirements (of the kubelet, and kubeadm)

**Comment by afbjorklund** [comment]
Note that **both** dockershim and kubenet were removed from upstream, while recommending to use CRI and CNI.

* https://github.com/kubernetes/kubernetes/issues/100707

**Comment by mgabeler-lee-6rs** [comment]
> If not using the "no-op" (previous default network plugin), then both cri-tools and cni-plugins are required:

Where is this documented?
* https://minikube.sigs.k8s.io/docs/drivers/none/ ? nope!
* Linked kubeadm docs https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/ ? nope!
* Your link to the github repo for these plugins is actually the first time I've been able to find where to get them from. Searching based on the errors was unsuccessful for me (though now that I know more what to search for I can find this info ... though only in bug reports or indirect links from other documentation, that repo doesn't directly show up in any search results)

And actually, the "no-op" plugin does _not_ seem to need the cni-plugins, it is the kubenet and cni plugin that need it?

> When installing kubernetes from packages

But that isn't what happens here, unless I'm misunderstanding what you mean by "packages". Minikube is the one installing kubelet & kubeadm when using the none driver, looks like from binaries from its own release process. Minikube's on packages don't have any dependencies on these other tools, not least because only cri-dockerd even has .deb/.rpm packages available, crictl and the cni plugins do not.

---

Seems like the changes from https://github.com/kubernetes/minikube/pull/14555 should be extended to also check for the CNI plugins if they are required? Though with the PR you linked it seems like they may no longer be required?

---

> https://github.com/kubernetes/minikube/pull/14703

Thanks for the link to this PR. I will try building from this branch and confirm if that fixes this issue for me or not!

---

I'm well aware the none driver is "advanced mode" and has extra requirements and caveats. I'd move away from it if the alternatives weren't horrifically worse for my team's use case ;)

It just seems the documentation on how to use it has degraded significantly with kubernetes 1.24 (in the sense that the documentation hasn't been fully updated to make it easy to setup as it was with 1.23). Granted, the lacking documentation is not just down to minikube, but also other kubernetes and peripheral projects too.

**Comment by afbjorklund** [comment]
The documentation hasn't really been updated (properly) for 1.24, the requirements have changed since 1.23

* **docker**
* cri-dockerd (new)
* cri-tools (new!)
* cni-plugins (new!)

**Comment by afbjorklund** [comment]
> Granted, the lacking documentation is not just down to minikube, but also other kubernetes and peripheral projects too.

The documentation was actually **deleted** from Kubernetes, since it has been delegated to the container runtime providers.

**Comment by afbjorklund** [comment]
> But that isn't what happens here, unless I'm misunderstanding what you mean by "packages"

It was a vague reference to the upstream documentation of installing kubernetes with apt or yum:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

Like you say, that is not what is happening with the "none" driver - it "assumes" that they are there.
The requirements are supposed to be checked by kubeadm, except for CNI which is "optional"*

\* the "normal" behaviour is for Kubernetes to into CrashLoopBackoff, waiting for the installation...

**Comment by afbjorklund** [comment]
> And actually, the "no-op" plugin does _not_ seem to need the cni-plugins, it is the kubenet and cni plugin that need it?

Correct.

**Comment by mgabeler-lee-6rs** [comment]
> Like you say, that is not what is happening with the "none" driver - it "assumes" that they are there.

Sorry but no, it does assume they (kubectl and kubeadm) are present. Minikube itself downloads its own copies of them and installs them into `/var/lib/minikube/binaries/${kubernetes-version}/` -- https://github.com/kubernetes/minikube/blob/master/pkg/minikube/download/binary.go

**Comment by afbjorklund** [comment]
I meant that minikube assumes that cri and cni are installed by the user, it does add the k8s components

For the supported OS, minikube pre-installs the packages on the ISO and in the KIC image

**Comment by mgabeler-lee-6rs** [comment]
> It is fixed by this PR, which _always_ sets the network plugin: (avoids the previous shortcut, to not set it)
> 
> * [Handle CRI config of NetworkPlugin and PauseImage #14703](https://github.com/kubernetes/minikube/pull/14703)

This PR is not working for me. Since I think it is an error in the PR, I'll post info there

**Comment by mgabeler-lee-6rs** [comment]
/remove-lifecycle stale

The PRs are still going, this is still an issue

**Comment by mgabeler-lee-6rs** [comment]
Minikube being broken due to this and linked issues as simply led to me & my team abandoning use of this. It's probably still broken, but I won't be able to help confirm any fixes. That said, the PRs are still out there :shrug:
