### ISSUE TITLE
migrate to localStorageCapacityIsolation kubelet option from feature gate

### ISSUE THREAD

**Issue by BenTheElder** [kubernetes/minikube#14728]
The LocalStorageCapacityIsolation feature will be GA in v1.25.0 and thus there will be no feature gate, but for rootless users like this I've requested a kubelet config option that will be available in v1.25.0 thanks to `@jinxu97`.  You can set `localStorageCapacityIsolation: false` in the kubelet config instead of disabling the feature gate when Kubernetes v1.25.0 is out.

I've identified this project as using the feature gate, so this issue is a friendly heads up about the coming removal and replacement 😅 

see: https://github.com/kubernetes/kubernetes/pull/111513, https://github.com/kubernetes/enhancements/issues/361, coming in Kubernetes v1.25.0

**Comment by spowelljr** [comment]
Thanks for the heads up @BenTheElder, we'll look into this!

**Comment by afbjorklund** [comment]
Apparently it is _only_ used as a workaround for (unsupported) btrfs

```go
                if si.StorageDriver == "btrfs" {
                        klog.Info("auto-setting LocalStorageCapacityIsolation to false because using btrfs storage driver")
                        cc.KubernetesConfig.FeatureGates = addFeatureGate(cc.KubernetesConfig.FeatureGates, "LocalStorageCapacityIsolation=false")
                }

```

**Comment by oleastre** [comment]
I don't know if btrfs is supported or not (the feature gate auto setting was added as part of minikube 1.25.0), but with the latest 1.27.0 release, and the switch to Kubernetes 1.25.0, the feature gate setting does not work any more, and using brtfs is broken.

I tried various variations around: ```minikube start --driver=docker --extra-config=kubelet.local-storage-capacity-isolation=false```
But none works, and I always get an error like the old one described in https://github.com/kubernetes/minikube/issues/11932

Something else I noticed in the logs is this: 
```
Sep 20 08:42:51 minikube kubelet[3414]: Flag --local-storage-capacity-isolation has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 20 08:42:51 minikube kubelet[3414]: E0920 08:42:51.352150    3414 run.go:74] "command failed" err="failed to set feature gates from initial flags-based config: cannot set feature gate LocalStorageCapacityIsolation to false, feature is locked to true"
```
Seems something is blocking my command line setting, but I don't have any clue about where it comes from.

Conclusion is that for me, on Fedora 36, btrfs does not work anymore with minikube. As a work around, I switched docker to `overlay2`.

**Comment by mbana** [comment]
Might be related <https://github.com/kubernetes/minikube/issues/15099>.
