### ISSUE TITLE
ARM64 fail to nslookup

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#14722]
### What Happened?

On M1 Qemu driver trying to debug why we have a 
```
❗  This VM is having trouble accessing https://k8s.gcr.io
```
```
minikube ssh
cat  /etc/resolv.conf 
```

I noticed we can not nslookup google, the content of  /etc/resolv.conf is 
```
nameserver 10.0.2.3
search .
```

and when I change it to 
```
nameserver 10.0.2.3
search .
```

**Comment by afbjorklund** [comment]
qemu should use the first nameserver **on the host**, so check that to make sure it works OK

I don't think it will try the second nameserver, even if you have more than one in /etc/resolv.conf

**Comment by spowelljr** [comment]
More detailed information about this bug in https://github.com/kubernetes/minikube/issues/15021
