### ISSUE TITLE
X Exiting due to GUEST_STATUS: state: unknown state "minikube": docker container inspect minikube --format=: exit status 1

### ISSUE THREAD

**Issue by srpeddolla** [kubernetes/minikube#14737]
### What Happened?

error during connect: In the default daemon configuration on Windows, the docker client must be run with elevated privileges to connect.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/minikube/json": open //./pipe/docker_engine: The system cannot find the file specified.

### Attach the log file

 C:\Users\SHASHI\AppData\Local\Temp\minikube_logs_03c4ab707865d306246ab2f7e4b6f4a0674fb5b0_0.log

### Operating System

Windows

**Comment by spowelljr** [comment]
Hi @srpeddolla, this error sounds like your Docker Desktop is not running, double check that's it's running.

If it is look at some of the fixes here: https://stackoverflow.com/a/61062715

**Comment by klaases** [comment]
Hi @srpeddolla – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
