### ISSUE TITLE
Add all versions of minikube to brew

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#14733]
Currently, only the latest version of minikube is available on brew.

But if a user is experiencing issues with the latest version, they should be allowed to downgrade to an older version.

For example: postgresql
```
$ brew search postgresql
==> Formulae
postgresql               postgresql@10            postgresql@11            postgresql@12            postgresql@13            postgresql@9.4           postgresql@9.5           postgresql@9.6 
```

**Comment by afbjorklund** [comment]
This is normal for brew (and others), it only has the latest version - unless it is not backwards compatible.

**Comment by 9bany** [comment]
In my approach, we only need to release (add to brew) versions with [major].[minor] numbers and we don't need to include a patch number. So, for example, we would release versions like `0.1.x`,` 0.2.x`, ... `1.3.x`.

Please let me know your expectations, @spowelljr 
Many thanks.
