### ISSUE TITLE
Minikube start failure

### ISSUE THREAD

**Issue by sistewar** [kubernetes/minikube#14738]
### What Happened?

I'm trying to start the minikube in local gitbash terminal after installing the latest version from
https://minikube.sigs.k8s.io/docs/start/ but am unable to do so as am getting checksum errors. I've enclosed the version am using and errors which I got while starting the minikube. appreciate anyones help to assist to provide any suggestion for this.

$ minikube version
minikube version: v1.26.1
commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc

**Comment by spowelljr** [comment]
Hi @sistewar, when you run `minikube logs --file=logs.txt` even though an error is displayed it should still have created a log file. Could you upload that log file to this issue so I can look further into the issue, thank you.

**Comment by sistewar** [comment]
Hi Steven,

It looks like it was not able to download iso image from web automatically when I run 'minikube start'. As a workaround I had to manually download it from here https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.26.1-amd64.iso and then place it in my local to fix that issue. I have pasted the complete error messages in what happened text box earlier. On the other hand not sure if it's a problem with latest version of minikube that we need to always use stable version of minikube. If you have any thoughts on this please do let me know. But for now I can confirm that manual workaround worked for me. Thank you very much for your response.

**Comment by spowelljr** [comment]
Were you using a different version of minikube before that the download was working with?

**Comment by sistewar** [comment]
@spowelljr no, this is the first time am trying minikube setup.

**Comment by sistewar** [comment]
Thank you for your help.
