### ISSUE TITLE
Randomly mapping host ports no longer works

### ISSUE THREAD

**Issue by vbode** [kubernetes/minikube#14731]
### What Happened?

I updated minikube recently (don't remember which version exactly), and since then, I see we need to specify the host and minikube port when using the --ports flag during startup.

Previously, when setting the --ports flag, it was enough to specify the minikube port to expose, and minikube would then pick a random host port. I have not found a way to have minikube use a random host port, is this no longer possible? 

### Attach the log file

No logs as it is a general question, no a bug.

### Operating System

Windows

### Driver

Docker

**Comment by klaases** [comment]
Hi @vbode, for additional community based support you may also reach out on minikube's Slack channel.

https://minikube.sigs.k8s.io/community/

Did you find a working solution?

/triage needs-information
/kind support

**Comment by vbode** [comment]
Hi @klaases. I did not find a solution. We are now having to generate a random port ourselves before starting minikube.

**Comment by spowelljr** [comment]
Hi @vbode, we did add validation to the ports flag a few releases ago, but we may have made it too strict. Could you give of example of what you you used to pass to the `--ports` flag and I can follow up on this, thanks!

**Comment by vbode** [comment]
Hi @spowelljr. I used to pass `--ports 1433,1444` which would then expose 1433 and 1444 on a random host port.
