### ISSUE TITLE
FAQ Why doesn't Minikube support a local Ingress?

### ISSUE THREAD

**Issue by robertlagrant** [kubernetes/minikube#14736]
_Some context, in case that helps in creating an answer:_

I believe in local dev, so I'm trying to create as much as possible a local kubernetes environment that reflects the final deployed state of a system. One area is that of traffic ingress.

It looks as though I can run NginX ingress controllers to my heart's content, and my understanding is that they do the HTTP heavy lifting, as one would expect with NginX.

So, how can I improve my local setup with Minikube to better reflect the final system? Can I install something external and make Minikube-hosted ingress controllers aware of it, for example?

**Comment by afbjorklund** [comment]
I think "better ingress" would be a good item for the roadmap, even if might be tough to implement for some drivers*.

\* Docker Desktop, Podman Desktop, QEMU "user" network - are all known to have poor networking

\* Docker Engine, Podman Engine, QEMU "vde" network - should have more regular IP networking

Also a thing is that minikube isn't really concerned with deployment, everything is only available to localhost anyway...
