### ISSUE TITLE
❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines

### ISSUE THREAD

**Issue by tiancai110a** [kubernetes/minikube#14746]
**重现问题所需的命令**：
minikube start --driver=docker
**失败的命令的完整输出**：<details>
minikube start --driver=docker

</details>
**`minikube logs`命令的输出**： <details>
W0807 01:52:29.649784   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.649807   72547 retry.go:31] will retry after 110.466µs: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.649977   72547 provision.go:83] configureAuth start
I0807 01:52:29.650104   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:29.728174   72547 provision.go:86] duration metric: configureAuth took 78.089195ms
W0807 01:52:29.728229   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.728245   72547 retry.go:31] will retry after 216.077µs: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.728524   72547 provision.go:83] configureAuth start
I0807 01:52:29.728613   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:29.801988   72547 provision.go:86] duration metric: configureAuth took 73.374223ms
W0807 01:52:29.801998   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.802009   72547 retry.go:31] will retry after 262.026µs: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.802333   72547 provision.go:83] configureAuth start
I0807 01:52:29.802411   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:29.873221   72547 provision.go:86] duration metric: configureAuth took 70.798516ms
W0807 01:52:29.873233   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.873245   72547 retry.go:31] will retry after 316.478µs: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.873632   72547 provision.go:83] configureAuth start
I0807 01:52:29.873720   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:29.950472   72547 provision.go:86] duration metric: configureAuth took 76.745408ms
W0807 01:52:29.950484   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.950518   72547 retry.go:31] will retry after 468.098µs: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:29.951073   72547 provision.go:83] configureAuth start
I0807 01:52:29.951154   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.028542   72547 provision.go:86] duration metric: configureAuth took 77.378357ms
W0807 01:52:30.028560   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.028571   72547 retry.go:31] will retry after 901.244µs: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.029631   72547 provision.go:83] configureAuth start
I0807 01:52:30.029813   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.114441   72547 provision.go:86] duration metric: configureAuth took 84.708687ms
W0807 01:52:30.114458   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.114492   72547 retry.go:31] will retry after 644.295µs: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.115264   72547 provision.go:83] configureAuth start
I0807 01:52:30.115388   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.202851   72547 provision.go:86] duration metric: configureAuth took 87.485882ms
W0807 01:52:30.202867   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.202881   72547 retry.go:31] will retry after 1.121724ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.204174   72547 provision.go:83] configureAuth start
I0807 01:52:30.204290   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.286455   72547 provision.go:86] duration metric: configureAuth took 82.184874ms
W0807 01:52:30.286468   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.286480   72547 retry.go:31] will retry after 1.529966ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.288105   72547 provision.go:83] configureAuth start
I0807 01:52:30.288217   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.365280   72547 provision.go:86] duration metric: configureAuth took 77.082942ms
W0807 01:52:30.365292   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.365304   72547 retry.go:31] will retry after 3.078972ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.368847   72547 provision.go:83] configureAuth start
I0807 01:52:30.369002   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.445374   72547 provision.go:86] duration metric: configureAuth took 76.431607ms
W0807 01:52:30.445385   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.445397   72547 retry.go:31] will retry after 5.854223ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.451904   72547 provision.go:83] configureAuth start
I0807 01:52:30.452027   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.524410   72547 provision.go:86] duration metric: configureAuth took 72.418833ms
W0807 01:52:30.524422   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.524434   72547 retry.go:31] will retry after 11.362655ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.535874   72547 provision.go:83] configureAuth start
I0807 01:52:30.536045   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.610893   72547 provision.go:86] duration metric: configureAuth took 74.930752ms
W0807 01:52:30.610906   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.610916   72547 retry.go:31] will retry after 9.267303ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.620274   72547 provision.go:83] configureAuth start
I0807 01:52:30.620395   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.701587   72547 provision.go:86] duration metric: configureAuth took 81.217611ms
W0807 01:52:30.701599   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.701609   72547 retry.go:31] will retry after 17.139291ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.719263   72547 provision.go:83] configureAuth start
I0807 01:52:30.719413   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.793821   72547 provision.go:86] duration metric: configureAuth took 74.446418ms
W0807 01:52:30.793833   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.793871   72547 retry.go:31] will retry after 23.881489ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.818863   72547 provision.go:83] configureAuth start
I0807 01:52:30.819027   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:30.899230   72547 provision.go:86] duration metric: configureAuth took 80.270389ms
W0807 01:52:30.899262   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.899274   72547 retry.go:31] will retry after 42.427055ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:30.941974   72547 provision.go:83] configureAuth start
I0807 01:52:30.942216   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:31.019538   72547 provision.go:86] duration metric: configureAuth took 77.472446ms
W0807 01:52:31.019550   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:31.019562   72547 retry.go:31] will retry after 51.432832ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:31.072156   72547 provision.go:83] configureAuth start
I0807 01:52:31.072349   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:31.147269   72547 provision.go:86] duration metric: configureAuth took 75.026504ms
W0807 01:52:31.147281   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:31.147292   72547 retry.go:31] will retry after 78.14118ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:31.226537   72547 provision.go:83] configureAuth start

I0807 01:52:31.226712   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:31.305051   72547 provision.go:86] duration metric: configureAuth took 78.423984ms
W0807 01:52:31.305063   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines

I0807 01:52:31.305075   72547 retry.go:31] will retry after 174.255803ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:31.480078   72547 provision.go:83] configureAuth start
I0807 01:52:31.480223   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:31.555440   72547 provision.go:86] duration metric: configureAuth took 75.276424ms
W0807 01:52:31.555452   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:31.555463   72547 retry.go:31] will retry after 159.291408ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines

I0807 01:52:31.715401   72547 provision.go:83] configureAuth start
I0807 01:52:31.715585   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:31.798779   72547 provision.go:86] duration metric: configureAuth took 83.249525ms
W0807 01:52:31.798792   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:31.798803   72547 retry.go:31] will retry after 233.827468ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:32.032983   72547 provision.go:83] configureAuth start
I0807 01:52:32.033179   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:32.116509   72547 provision.go:86] duration metric: configureAuth took 83.435715ms
W0807 01:52:32.116520   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:32.116531   72547 retry.go:31] will retry after 429.392365ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:32.547583   72547 provision.go:83] configureAuth start
I0807 01:52:32.547775   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:32.626582   72547 provision.go:86] duration metric: configureAuth took 78.912189ms
W0807 01:52:32.626596   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:32.626608   72547 retry.go:31] will retry after 801.058534ms: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:33.428503   72547 provision.go:83] configureAuth start
I0807 01:52:33.428635   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:33.508394   72547 provision.go:86] duration metric: configureAuth took 79.794869ms
W0807 01:52:33.508405   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:33.508415   72547 retry.go:31] will retry after 1.529087469s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:35.039827   72547 provision.go:83] configureAuth start
I0807 01:52:35.040111   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:35.117002   72547 provision.go:86] duration metric: configureAuth took 77.085172ms
W0807 01:52:35.117014   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:35.117025   72547 retry.go:31] will retry after 1.335136154s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:36.454358   72547 provision.go:83] configureAuth start
I0807 01:52:36.454526   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:36.529508   72547 provision.go:86] duration metric: configureAuth took 75.085609ms
W0807 01:52:36.529521   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:36.529533   72547 retry.go:31] will retry after 2.012724691s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:38.543848   72547 provision.go:83] configureAuth start
I0807 01:52:38.544116   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:38.625550   72547 provision.go:86] duration metric: configureAuth took 81.63815ms
W0807 01:52:38.625565   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:38.625597   72547 retry.go:31] will retry after 4.744335389s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:43.372947   72547 provision.go:83] configureAuth start
I0807 01:52:43.373173   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:43.446515   72547 provision.go:86] duration metric: configureAuth took 73.521538ms
W0807 01:52:43.446527   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:43.446539   72547 retry.go:31] will retry after 4.014454686s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:47.462727   72547 provision.go:83] configureAuth start
I0807 01:52:47.462851   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:47.548821   72547 provision.go:86] duration metric: configureAuth took 86.049079ms
W0807 01:52:47.548834   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:47.548847   72547 retry.go:31] will retry after 11.635741654s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:59.187942   72547 provision.go:83] configureAuth start
I0807 01:52:59.188181   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:52:59.266120   72547 provision.go:86] duration metric: configureAuth took 78.148743ms
W0807 01:52:59.266132   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:52:59.266142   72547 retry.go:31] will retry after 15.298130033s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:53:14.566292   72547 provision.go:83] configureAuth start
I0807 01:53:14.566842   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:53:14.645863   72547 provision.go:86] duration metric: configureAuth took 79.55082ms
W0807 01:53:14.645875   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:53:14.645885   72547 retry.go:31] will retry after 19.631844237s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:53:34.278929   72547 provision.go:83] configureAuth start
I0807 01:53:34.279070   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:53:34.361839   72547 provision.go:86] duration metric: configureAuth took 82.896385ms
W0807 01:53:34.361851   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:53:34.361865   72547 retry.go:31] will retry after 15.195386994s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:53:49.557660   72547 provision.go:83] configureAuth start
I0807 01:53:49.557806   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:53:49.636592   72547 provision.go:86] duration metric: configureAuth took 78.920154ms
W0807 01:53:49.636604   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:53:49.636620   72547 retry.go:31] will retry after 28.402880652s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:54:18.040179   72547 provision.go:83] configureAuth start
I0807 01:54:18.040372   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:54:18.115027   72547 provision.go:86] duration metric: configureAuth took 74.836545ms
W0807 01:54:18.115039   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:54:18.115051   72547 retry.go:31] will retry after 1m6.435206373s: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:55:24.550671   72547 provision.go:83] configureAuth start
I0807 01:55:24.550797   72547 cli_runner.go:115] Run: docker container inspect -f "" minikube
I0807 01:55:24.773848   72547 provision.go:86] duration metric: configureAuth took 223.144385ms
W0807 01:55:24.816385   72547 ubuntu.go:180] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:55:24.816429   72547 ubuntu.go:189] Error configuring auth during provisioning Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 3 lines
I0807 01:55:24.816438   72547 machine.go:91] provisioned docker machine in 2m55.649956777s
I0807 01:55:24.816476   72547 client.go:171] LocalClient.Create took 2m58.325827738s
I0807 01:55:26.817491   72547 ssh_runner.go:149] Run: sh -c "df -h /var | awk 'NR==2{print $5}'"
E0807 01:55:27.766137   74705 out.go:340] unable to execute I0807 01:55:26.817576   72547 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
: template: I0807 01:55:26.817576   72547 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
:1:94: executing "I0807 01:55:26.817576   72547 cli_runner.go:115] Run: docker container inspect -f \"'{{(index (index .NetworkSettings.Ports \"22/tcp\") 0).HostPort}}'\" minikube\n" at <index .NetworkSettings.Ports "22/tcp">: error calling index: index of untyped nil - returning raw string.
I0807 01:55:26.817576   72547 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0807 01:55:27.044211   72547 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:57635 SSHKeyPath:/Users/lizongrong/.minikube/machines/minikube/id_rsa Username:docker}

</details>

**使用的操作系统版本**：
MacOS

I tried everything , chown,chmod ,minikube delete , delete config , nothing helps

**Comment by klaases** [comment]
Thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @tiancai110a, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
