### ISSUE TITLE
Unable to start Minkube. Exiting due to GUEST_NOT_FOUND. Tried every advice

### ISSUE THREAD

**Issue by Mary4325** [kubernetes/minikube#14749]
### What Happened?

Hi!
Unfortunately nothing helps me from https://github.com/kubernetes/minikube/issues/9130
I have installed and run Virtualbox and Minikube with administrator privilidges.
I've used: minikube start --driver=virtualbox --no-vtx-check
Virtualbox, kubectl, minikube are located at disk D, because I don't have enough space at disk C. 

### Attach the log file

[lastStart.txt](https://github.com/kubernetes/minikube/files/9277202/lastStart.txt)

### Operating System

Windows

### Driver

VirtualBox

**Comment by klaases** [comment]
Hi @Mary4325, were you able to get this working?

From your log file, the following standout:

```
I0807 19:53:48.278631    6388 start.go:115] hostinfo: {"hostname":"alexandra","uptime":2673,"bootTime":1659888555,"procs":233,"os":"windows","platform":"Microsoft Windows 10 Home Single Language","platformFamily":"Standalone Workstation","platformVersion":"10.0.19043 Build 19043","kernelVersion":"10.0.19043 Build 19043","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"39689c0e-350c-4cb6-8ba2-db4ed104c2f3"}
W0807 19:53:48.278631    6388 start.go:123] gopshost.Virtualization returned error: not implemented yet
```
Maybe try re-configuring VirtualBox?


```
W0807 19:53:48.385549    6388 preload.go:295] Failed to list preload files: open D:\Work\Kubernetes\.minikube\cache\preloaded-tarball: The system cannot find the file specified.
```

Maybe try making sure all files are available / accessible?

**Comment by spowelljr** [comment]
Hi @Mary4325, a long duration has passed since your last response so I'm going to close this issue. But if you do come back to it could you upload the log file listed below, thanks!

`D:\Work\Kubernetes\.minikube\machines\minikube\minikube\Logs\VBoxHardening.log`
