### ISSUE TITLE
Not able to start miniqube using hyperv

### ISSUE THREAD

**Issue by chaudharynidhi** [kubernetes/minikube#14748]
### What Happened?

Hi,
I am unable to start miniqube using this command;
`minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"`
I am getting this error: 
`* minikube v1.26.1 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042                                            * Using the hyperv driver based on existing profile                                                                     ! Local proxy ignored: not passing HTTP_PROXY=http://127.0.0.1:65367/;http://127.0.0.1:65368/;http://127.0.0.1:65369/;http://127.0.0.1:65370/;http://127.0.0.1:65371/ to docker env.
! Local proxy ignored: not passing HTTP_PROXY=http://127.0.0.1:65367/;http://127.0.0.1:65368/;http://127.0.0.1:65369/;http://127.0.0.1:65370/;http://127.0.0.1:65371/ to docker env.
* Starting control plane node minikube in cluster minikube
* Restarting existing hyperv VM for "minikube" ...
E0807 21:32:51.491246   23224 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Unable to allocate 4000 MB of RAM: Insufficient system resources exist to complete the requested service. (0x800705AA).
'minikube' failed to start. (Virtual machine ID 12F9A410-52E7-42AB-A3DB-B4A0CE3E9F11)
'minikube' is unable to allocate 4000 MB of RAM: Insufficient system resources exist to complete the requested
service. (0x800705AA). (Virtual machine ID 12F9A410-52E7-42AB-A3DB-B4A0CE3E9F11)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.StartVM

! StartHost failed, but will try again: driver start: exit status 1
* Restarting existing hyperv VM for "minikube" ...
E0807 21:33:04.421163   23224 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Microsoft Video Monitor (Instance ID BA8735EF-E3A9-4F1B-BADD-DBF3A5909915): Error 'Unspecified error'.
'minikube' failed to start. (Virtual machine ID 12F9A410-52E7-42AB-A3DB-B4A0CE3E9F11)
'minikube' Microsoft Video Monitor: Failed to finish reserving resources with Error 'Unspecified error' (0x80004005).
(Virtual machine ID 12F9A410-52E7-42AB-A3DB-B4A0CE3E9F11)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: driver start: exit status 1

X Exiting due to GUEST_PROVISION: Failed to start host: driver start: exit status 1
*
╭──────────────────────────────────────────────────────────────────────────────
│                                                                                             
│    * If the above advice does not help, please let us know:                                 
│      https://github.com/kubernetes/minikube/issues/new/choose                               
│                                                                                             
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    
│                                                                                             `

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9277122/logs.txt)

### Operating System

Windows

### Driver

Hyper-V

**Comment by spowelljr** [comment]
Hi @chaudharynidhi, it looks like your machine doesn't have enough memory available for the requested amount:
`Unable to allocate 4000 MB of RAM: Insufficient system resources exist to complete the requested service.`

Could you try deleting the cluster (`minikube delete`) and then start it and pass it a memory flag (`--memory 2200`) to set it to use 2200 MB of memory.
