### ISSUE TITLE
The command line option `--kubernetes-version` causes minikube start to fail

### ISSUE THREAD

**Issue by gjcarneiro** [kubernetes/minikube#1475]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`):
v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 17.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): `file:///home/gjc/.minikube/cache/iso/minikube-v0.18.0.iso`
- **Install tools**:
- **Others**:

**What happened**:

```
01:53:29 {master} ~/projects/mollyapi/ansible$ minikube start --memory=16384 --disk-size=100g --cpus=3 --logtostderr --kubernetes-version=v1.6.3 -v 3
I0511 13:53:47.970977    9693 notify.go:112] Checking for updates...
Starting local Kubernetes v1.6.3 cluster...
Starting VM...
I0511 13:53:48.028304    9693 downloader.go:56] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v0.18.0.iso
Running pre-create checks...
Creating machine...
(minikube) Downloading /home/gjc/.minikube/cache/boot2docker.iso from file:///home/gjc/.minikube/cache/iso/minikube-v0.18.0.iso...
(minikube) Creating VirtualBox VM...
(minikube) Creating SSH key...
(minikube) Starting the VM...
(minikube) Check network to re-create if needed...
(minikube) Waiting for an IP...
Waiting for machine to be running, this may take a few minutes...
Detecting operating system of created instance...
Waiting for SSH to be available...
Detecting the provisioner...
Provisioning with buildroot...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...
Checking connection to Docker...
Docker is up and running!
SSH-ing files into VM...
E0511 13:54:52.388066    9693 start.go:147] Error updating cluster:  Error updating localkube from uri: Error attempting to download and cache localkube: Error getting localkube download url: Invalid localkube version
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
```
minikube start --insecure-registry=docker.gambit --memory=16384 --disk-size=100g --cpus=3 --logtostderr --kubernetes-version=v1.6.3 -v 3
```

**Anything else do we need to know**:

Without the  `--kubernetes-version` it works.

**Comment by r2d4** [comment]
`E0511 13:54:52.388066    9693 start.go:147] Error updating cluster:  Error updating localkube from uri: Error attempting to download and cache localkube: Error getting localkube download url: Invalid localkube version`

You can view the available k8s versions with `minikube get-k8s-versions`.  Not all kubernetes versions are immediately available to use in minikube, but we do our best to publish them as them come out.  In this case, 

```
$ minikube get-k8s-versions
The following Kubernetes versions are available:
        - v1.6.0
        - v1.6.0-rc.1
        - v1.6.0-beta.4
        - v1.6.0-beta.3
        - v1.6.0-beta.2
        - v1.6.0-alpha.1
        - v1.6.0-alpha.0
        - v1.5.3
        - v1.5.2
        - v1.5.1
        - v1.4.5
        - v1.4.3
        - v1.4.2
        - v1.4.1
        - v1.4.0
        - v1.3.7
        - v1.3.6
        - v1.3.5
        - v1.3.4
        - v1.3.3
        - v1.3.0
```

**Comment by gjcarneiro** [comment]
Well, in that case it's a UI bug at least.  From `Invalid localkube version` I would never have guessed it...

**Comment by r2d4** [comment]
@gjcarneiro yeah, I've added a check in #1490

**Comment by gjcarneiro** [comment]
Thank you.
