### ISSUE TITLE
Failing to Launch Browser using minikube service [service-name]

### ISSUE THREAD

**Issue by manq2010** [kubernetes/minikube#14778]
### What Happened?

Failing to Launch Browser using minikube service [service-name]

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9307737/logs.txt)
[minikube_service_5cfe402bc577ab8742bacdf983881be08e569791_0.log](https://github.com/kubernetes/minikube/files/9307766/minikube_service_5cfe402bc577ab8742bacdf983881be08e569791_0.log)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Looks similar to:
* https://github.com/kubernetes/minikube/issues/11222

What browser are you using ?

Does it help to run the command with `--url`, and then `xdg-open` that location ?

**Comment by klaases** [comment]
Hi @manq2010  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
