### ISSUE TITLE
Failed to running minikube under lima

### ISSUE THREAD

**Issue by thr3a** [kubernetes/minikube#14776]
### What Happened?

I have tried to install minikube on a virtual environment built using lima but it fails.

# Environment

Macbook M1

```
❯ lima -v
limactl version 0.11.3
❯ which lima
/opt/homebrew/bin/lima

❯ docker -v
Docker version 20.10.17, build 100c70180f
❯ which docker
/opt/homebrew/bin/docker
❯ docker context list
NAME            DESCRIPTION                               DOCKER ENDPOINT                                      KUBERNETES ENDPOINT                ORCHESTRATOR
default         Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                          https://127.0.0.1:6443 (default)   swarm
lima-docker *                                             unix:///Users/thr3a/.lima/default/sock/docker.sock

❯ minikube version
minikube version: v1.26.1
commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc
❯ which minikube
/opt/homebrew/bin/minikube
```

# Command

```
minikube start --driver=docker --container-runtime=containerd --alsologtostderr -v=1
```

I confirmed that the installation failed as well after running the initialization command (`minikube delete --all --purge`).

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9305967/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
You might need to set the DOCKER_HOST, explicitly. I don't think all clients understand the "context" (yet)

But the root cause seems to be stray binary characters in the output from the commands over ssh ?

**Comment by afbjorklund** [comment]
We discussed various ways to run under lima, but it is not yet a supported docker platform

* https://github.com/kubernetes/minikube/issues/12926

The default is to just install containerd and kubeadm on the Lima VM directly...

It _should_ support running with docker-in-docker too, even rootless, but it is not tested

**Comment by afbjorklund** [comment]
It worked ok with lima on Linux, using rootless docker

So the docker host (vs context) warnings were not related

**Comment by thr3a** [comment]
I have tried several patterns and have successfully installed minikube only when the virtual machine architecture is aarch64 and **rootful**.

In the case of x86_64 & rootful, the installation proceeded better than in the other cases but eventually failed.

| lima arch \ rootless? | rootful | rootless(default) |
|-------------------------------|---------|-------------------|
| aarch64                       | ⭕       | ❌                 |
| x86_64                        | ❌       | ❌                 |

[x86_64-rootful.txt](https://github.com/kubernetes/minikube/files/9308262/x86_64-rootful.txt)

**Comment by afbjorklund** [comment]
Could be related to the flaky "user" networking on Mac then (known lima issue...) Can you try with "vde", to see if it helps ?

**Comment by afbjorklund** [comment]
It seems to have the same issue as on other platforms, when the Unix socket is **not** local but tunneled to another machine in secret... It seems to be using 192.168.52.2 for the IP, while Lima wants it to be 127.0.0.1 (tunneled)

In the Lima k3s/k8s, this is done with `sed` on kube config...

**Comment by afbjorklund** [comment]
Turns out the 192.168.58 was a freak show with minikube deciding that 192.168.49 was in use **on the host**, and therefore deciding to use 192.168.52 for the docker network without noticing it was the same network as the Lima VM...

Anyway, minikube doesn't work with lima and tunneling sockets. It expects real IPs and TCP sockets, the way it was with `docker-machine`

For now, you have to run `lima minikube` instead.

It could be made to work, if there was any interest. But so far, there hasn't been - not from lima, not from kind. So we're doing the "qemu" driver instead

**Comment by thr3a** [comment]
I realized that the way I tried to run minikube under lima was not the standard way.
Actually, I also tried `lima minikube`(arch: x86_64), but it was too late, so I decided to install minikube on Linux host.
(I understand that the slow problem is not caused by minikube or lima.)

Thank you.
