### ISSUE TITLE
minikube start failed with kvm2

### ISSUE THREAD

**Issue by holylong** [kubernetes/minikube#14772]
### What Happened?

😄  Ubuntu 20.04 上的 minikube v1.25.1
🎉  minikube 1.26.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.26.1
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

✨  根据用户配置使用 kvm2 驱动程序

💣  Exiting due to PROVIDER_KVM2_ERROR: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to get emulator capabilities
error: invalid argument: KVM is not supported by '/usr/bin/qemu-system-x86_64' on this host
exit status 1
💡  建议：Follow your Linux distribution instructions for configuring KVM
📘  文档：https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/

### Attach the log file

* 
* ==> Audit <==
* |---------|--------------------|----------|-------|---------|-------------------------------|-------------------------------|
| Command |        Args        | Profile  | User  | Version |          Start Time           |           End Time            |
|---------|--------------------|----------|-------|---------|-------------------------------|-------------------------------|
| config  | set vm-driver kvm2 | minikube | skyer | v1.25.1 | Wed, 10 Aug 2022 17:26:56 CST | Wed, 10 Aug 2022 17:26:56 CST |
| delete  | --all              | minikube | skyer | v1.25.1 | Wed, 10 Aug 2022 17:27:21 CST | Wed, 10 Aug 2022 17:27:22 CST |
| config  | set vm-driver kvm2 | minikube | skyer | v1.25.1 | Wed, 10 Aug 2022 17:27:24 CST | Wed, 10 Aug 2022 17:27:24 CST |
| config  | unset vm-driver    | minikube | skyer | v1.25.1 | Wed, 10 Aug 2022 17:28:07 CST | Wed, 10 Aug 2022 17:28:07 CST |
|---------|--------------------|----------|-------|---------|-------------------------------|-------------------------------|

* 
* ==> Last Start <==
* Log file created at: 2022/08/10 17:33:40
Running on machine: build
Binary: Built with gc go1.17.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0810 17:33:40.330023 3766759 out.go:297] Setting OutFile to fd 1 ...
I0810 17:33:40.330073 3766759 out.go:349] isatty.IsTerminal(1) = true
I0810 17:33:40.330075 3766759 out.go:310] Setting ErrFile to fd 2...
I0810 17:33:40.330078 3766759 out.go:349] isatty.IsTerminal(2) = true
I0810 17:33:40.330162 3766759 root.go:315] Updating PATH: /home/skyer/.minikube/bin
I0810 17:33:40.330290 3766759 out.go:304] Setting JSON to false
I0810 17:33:40.350859 3766759 start.go:112] hostinfo: {"hostname":"build","uptime":1138285,"bootTime":1658985736,"procs":409,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.11.0-43-generic","kernelArch":"x86_64","virtualizationSystem":"vbox","virtualizationRole":"host","hostId":"fa42e33d-2c44-49b4-8690-d46f664026c0"}
I0810 17:33:40.350904 3766759 start.go:122] virtualization: vbox host
I0810 17:33:40.379583 3766759 out.go:176] 😄  Ubuntu 20.04 上的 minikube v1.25.1
W0810 17:33:40.379749 3766759 preload.go:294] Failed to list preload files: open /home/skyer/.minikube/cache/preloaded-tarball: no such file or directory
I0810 17:33:40.379878 3766759 notify.go:174] Checking for updates...
I0810 17:33:40.380327 3766759 driver.go:344] Setting default libvirt URI to qemu:///system
I0810 17:33:40.692584 3766759 lock.go:35] WriteFile acquiring /home/skyer/.minikube/last_update_check: {Name:mk9bea0f18c25e867a9ce570b91459c630278eda Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0810 17:33:40.736804 3766759 out.go:176] 🎉  minikube 1.26.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.26.1
I0810 17:33:40.794567 3766759 out.go:176] 💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

I0810 17:33:41.293144 3766759 out.go:176] ✨  根据用户配置使用 kvm2 驱动程序
I0810 17:33:41.293207 3766759 start.go:280] selected driver: kvm2
I0810 17:33:41.293219 3766759 start.go:795] validating driver "kvm2" against <nil>
I0810 17:33:41.293255 3766759 start.go:806] status for kvm2: {Installed:true Healthy:false Running:true NeedsImprovement:false Error:/usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to get emulator capabilities
error: invalid argument: KVM is not supported by '/usr/bin/qemu-system-x86_64' on this host
exit status 1 Reason: Fix:Follow your Linux distribution instructions for configuring KVM Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/}
I0810 17:33:41.317646 3766759 out.go:176] 
W0810 17:33:41.318024 3766759 out.go:241] 💣  Exiting due to PROVIDER_KVM2_ERROR: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to get emulator capabilities
error: invalid argument: KVM is not supported by '/usr/bin/qemu-system-x86_64' on this host
exit status 1
W0810 17:33:41.318268 3766759 out.go:241] 💡  建议：Follow your Linux distribution instructions for configuring KVM
W0810 17:33:41.318408 3766759 out.go:241] 📘  文档：https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/

### Operating System

Ubuntu

### Driver

KVM2

### virt-host-validate
QEMU: Checking for hardware virtualization                                 : FAIL (Only emulated CPUs are available, performance will be significantly limited)
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS

**Comment by klaases** [comment]
Hi @holylong, you may have to choose a driver other than Qemu, per the error message:

`KVM is not supported by '/usr/bin/qemu-system-x86_64' on this host`

Do you have another driver available?

/triage needs-information
/kind support

**Comment by medyagh** [comment]
@holylong could you try installing KVM correctly ?
are you using a VM in the cloud that does not have virtualization capability?


also I noticed you are not using the latest version of minkube ?

1- Install KVM
https://minikube.sigs.k8s.io/docs/drivers/kvm2/
2- Install latest version of minikbue
https://minikube.sigs.k8s.io/docs/start/
3- delete and start again
minikube delete --all
minikube start --driver=kvm2

**Comment by medyagh** [comment]
I will delete this issue for now but if you still like to ask please re-open
