### ISSUE TITLE
minikube issue

### ISSUE THREAD

**Issue by Arun297** [kubernetes/minikube#14775]
### What Happened?

Error: sudo crictl version: exit status 1

### Attach the log file

* ==> Audit <==
* |---------|--------------------|----------|------|---------|---------------------|----------|
| Command |        Args        | Profile  | User | Version |     Start Time      | End Time |
|---------|--------------------|----------|------|---------|---------------------|----------|
| start   | --driver=docker    | minikube | root | v1.26.1 | 09 Aug 22 20:39 UTC |          |
| start   | --driver=none      | minikube | root | v1.26.1 | 09 Aug 22 20:40 UTC |          |
| start   | --driver=none      | minikube | root | v1.26.1 | 09 Aug 22 20:42 UTC |          |
| start   | --driver=none      | minikube | root | v1.26.1 | 09 Aug 22 20:42 UTC |          |
| start   | --driver=none      | minikube | root | v1.26.1 | 09 Aug 22 20:51 UTC |          |
| start   | --driver=none      | minikube | root | v1.26.1 | 09 Aug 22 20:55 UTC |          |
| start   | --driver=docker    | minikube | root | v1.26.1 | 09 Aug 22 21:00 UTC |          |
| start   | --driver=none      | minikube | root | v1.26.1 | 09 Aug 22 21:00 UTC |          |
| start   |                    | minikube | root | v1.26.1 | 09 Aug 22 21:01 UTC |          |
| start   |                    | minikube | root | v1.26.1 | 09 Aug 22 21:03 UTC |          |
| start   | --driver=none      | minikube | root | v1.26.1 | 09 Aug 22 22:15 UTC |          |
| start   | --vm-driver=none   | minikube | root | v1.26.1 | 09 Aug 22 22:18 UTC |          |
| start   | --vm-driver=none   | minikube | root | v1.26.1 | 09 Aug 22 22:18 UTC |          |
| start   | --vm-driver=docket | minikube | root | v1.26.1 | 09 Aug 22 22:19 UTC |          |
| start   | --vm-driver=docker | minikube | root | v1.26.1 | 09 Aug 22 22:19 UTC |          |
| start   | --vm-driver=none   | minikube | root | v1.26.1 | 09 Aug 22 22:19 UTC |          |
| start   | --vm-driver=none   | minikube | root | v1.26.1 | 09 Aug 22 22:19 UTC |          |
| start   | --vm-driver=none   | minikube | root | v1.26.1 | 10 Aug 22 17:29 UTC |          |
| start   | --vm-driver=none   | minikube | root | v1.26.1 | 10 Aug 22 17:30 UTC |          |
| start   | --vm-driver=none   | minikube | root | v1.26.1 | 10 Aug 22 17:30 UTC |          |
|---------|--------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/08/10 17:30:33
Running on machine: ip-172-31-23-198
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0810 17:30:33.201240   26341 out.go:296] Setting OutFile to fd 1 ...
I0810 17:30:33.201452   26341 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0810 17:30:33.201457   26341 out.go:309] Setting ErrFile to fd 2...
I0810 17:30:33.201463   26341 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0810 17:30:33.201607   26341 root.go:333] Updating PATH: /root/.minikube/bin
W0810 17:30:33.201731   26341 root.go:310] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0810 17:30:33.201925   26341 out.go:303] Setting JSON to false
I0810 17:30:33.202813   26341 start.go:115] hostinfo: {"hostname":"ip-172-31-23-198","uptime":78631,"bootTime":1660074003,"procs":141,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.0-1011-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec291a00-f624-ed02-9e87-d399ead36e82"}
I0810 17:30:33.202879   26341 start.go:125] virtualization: xen guest
I0810 17:30:33.205964   26341 out.go:177] * minikube v1.26.1 on Ubuntu 22.04 (xen/amd64)
W0810 17:30:33.208105   26341 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0810 17:30:33.208298   26341 notify.go:193] Checking for updates...
I0810 17:30:33.208513   26341 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.3
W0810 17:30:33.208555   26341 start.go:716] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I0810 17:30:33.208594   26341 driver.go:365] Setting default libvirt URI to qemu:///system
W0810 17:30:33.208624   26341 start.go:716] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I0810 17:30:33.211501   26341 out.go:177] * Using the none driver based on existing profile
I0810 17:30:33.213648   26341 start.go:284] selected driver: none
I0810 17:30:33.213673   26341 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.23.198 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0810 17:30:33.213761   26341 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0810 17:30:33.213781   26341 start.go:1544] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0810 17:30:33.214356   26341 cni.go:95] Creating CNI manager for ""
I0810 17:30:33.214367   26341 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0810 17:30:33.214381   26341 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.23.198 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0810 17:30:33.216839   26341 out.go:177] * Starting control plane node minikube in cluster minikube
I0810 17:30:33.219048   26341 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0810 17:30:33.219233   26341 cache.go:208] Successfully downloaded all kic artifacts
I0810 17:30:33.219252   26341 start.go:371] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0810 17:30:33.219498   26341 start.go:375] acquired machines lock for "minikube" in 220.93µs
I0810 17:30:33.219515   26341 start.go:92] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.23.198 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:} &{Name:m01 IP:172.31.23.198 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}
I0810 17:30:33.219566   26341 start.go:132] createHost starting for "m01" (driver="none")
I0810 17:30:33.222128   26341 out.go:177] * Running on localhost (CPUs=4, Memory=16000MB, Disk=7764MB) ...
I0810 17:30:33.224409   26341 exec_runner.go:51] Run: systemctl --version
I0810 17:30:33.226674   26341 start.go:166] libmachine.API.Create for "minikube" (driver="none")
I0810 17:30:33.226706   26341 client.go:168] LocalClient.Create starting
I0810 17:30:33.226776   26341 main.go:134] libmachine: Reading certificate data from /root/.minikube/certs/ca.pem
I0810 17:30:33.226813   26341 main.go:134] libmachine: Decoding PEM data...
I0810 17:30:33.226829   26341 main.go:134] libmachine: Parsing certificate...
I0810 17:30:33.226891   26341 main.go:134] libmachine: Reading certificate data from /root/.minikube/certs/cert.pem
I0810 17:30:33.226914   26341 main.go:134] libmachine: Decoding PEM data...
I0810 17:30:33.226925   26341 main.go:134] libmachine: Parsing certificate...
I0810 17:30:33.227788   26341 client.go:171] LocalClient.Create took 1.072488ms
I0810 17:30:33.227814   26341 start.go:174] duration metric: libmachine.API.Create for "minikube" took 1.142137ms
I0810 17:30:33.227821   26341 start.go:307] post-start starting for "minikube" (driver="none")
I0810 17:30:33.227854   26341 start.go:335] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0810 17:30:33.227883   26341 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0810 17:30:33.238328   26341 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0810 17:30:33.238354   26341 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0810 17:30:33.238367   26341 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0810 17:30:33.241303   26341 out.go:177] * OS release is Ubuntu 22.04 LTS
I0810 17:30:33.243305   26341 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0810 17:30:33.243968   26341 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0810 17:30:33.244564   26341 start.go:310] post-start completed in 16.732361ms
I0810 17:30:33.245128   26341 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0810 17:30:33.245290   26341 start.go:135] duration metric: createHost completed in 25.713568ms
I0810 17:30:33.245300   26341 start.go:82] releasing machines lock for "minikube", held for 25.791379ms
I0810 17:30:33.245690   26341 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0810 17:30:33.245784   26341 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0810 17:30:33.265169   26341 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0810 17:30:33.545672   26341 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0810 17:30:33.793727   26341 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0810 17:30:34.053625   26341 exec_runner.go:51] Run: sudo systemctl restart docker
I0810 17:30:34.408717   26341 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0810 17:30:34.665524   26341 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0810 17:30:34.945589   26341 exec_runner.go:51] Run: sudo systemctl start cri-docker.socket
I0810 17:30:34.958156   26341 start.go:450] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0810 17:30:34.958199   26341 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0810 17:30:34.959503   26341 start.go:471] Will wait 60s for crictl version
I0810 17:30:34.959535   26341 exec_runner.go:51] Run: sudo crictl version
I0810 17:30:34.965316   26341 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0810 17:30:46.014349   26341 exec_runner.go:51] Run: sudo crictl version
I0810 17:30:46.021012   26341 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0810 17:31:07.632452   26341 exec_runner.go:51] Run: sudo crictl version
I0810 17:31:07.644855   26341 retry.go:31] will retry after 26.202601198s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0810 17:31:33.848083   26341 exec_runner.go:51] Run: sudo crictl version
I0810 17:31:33.857140   26341 out.go:177]
W0810 17:31:33.859250   26341 out.go:239] X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

W0810 17:31:33.859282   26341 out.go:239] *
W0810 17:31:33.860218   26341 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0810 17:31:33.862772   26341 out.go:177]

### Operating System

Ubuntu

**Comment by afbjorklund** [comment]
You need to install `crictl`, it's a new requirement (for docker) since k8s 1.24

**Comment by klaases** [comment]
Hi @Arun297, here is some additional information that may be helpful:

https://github.com/kubernetes/minikube/issues/14410#issuecomment-1193323463

If necessary, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.
Thank you for sharing your experience!
