### ISSUE TITLE
Copy bootlocal.sh from .minikube dir into the VM on start

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1478]
Similar to .minikube/addons we should have a place in the minikube directory where users can place a bootlocal.sh script and it will be copied over to the VM.  From: https://kubernetes.slack.com/archives/C1F5CT6Q1/p1494524339889965
https://kubernetes.slack.com/archives/C1F5CT6Q1/p1494525174352190

**Comment by huguesalary** [comment]
As an FYI, this will cause issues with the `xhyve` driver on mac.

Currently, the driver overwrites `bootlocal.sh` to setup Virtio9p mounts and NFS mounts. Which means that with this feature either the user's `bootlocal.sh` will be overwritten (by `xhyve`), or, `xhyve`'s `bootlocal.sh` will (by the user).

It is, however, probably something that should be fixed at the `xhyve` driver level, and not at the minikube level.

I happen to be actively working on Virtio9p mounts and NFS mounts, so I'll try and think about solutions for this as well.
