### ISSUE TITLE
minikube start issue

### ISSUE THREAD

**Issue by mtbctesting** [kubernetes/minikube#14785]
### What Happened?

minikube start

### Attach the log file

* 
* ==> Audit <==
* |---------|--------------------------------|----------|------|---------|---------------------|---------------------|
| Command |              Args              | Profile  | User | Version |     Start Time      |      End Time       |
|---------|--------------------------------|----------|------|---------|---------------------|---------------------|
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 19:57 PKT |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 19:58 PKT |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 19:58 PKT |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 19:59 PKT |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 21:50 PKT |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 21:53 PKT |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 21:54 PKT |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 21:56 PKT |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 21:59 PKT |                     |
|         | --container-runtime=containerd |          |      |         |                     |                     |
|         | --cni=bridge                   |          |      |         |                     |                     |
| start   | --driver=none                  | minikube | root | v1.26.1 | 12 Aug 22 21:59 PKT |                     |
|         | --container-runtime=containerd |          |      |         |                     |                     |
|         | --cni=bridge                   |          |      |         |                     |                     |
| start   |                                | minikube | root | v1.26.1 | 12 Aug 22 22:01 PKT |                     |
| delete  |                                | minikube | root | v1.26.1 | 12 Aug 22 22:02 PKT | 12 Aug 22 22:02 PKT |
| start   | --driver=docker                | minikube | root | v1.26.1 | 12 Aug 22 22:03 PKT |                     |
| start   |                                | minikube | root | v1.26.1 | 12 Aug 22 22:03 PKT |                     |
| start   | --driver=docker                | minikube | root | v1.26.1 | 12 Aug 22 22:03 PKT |                     |
|         | --container-runtime=containerd |          |      |         |                     |                     |
| start   | --force --driver=docker        | minikube | root | v1.26.1 | 12 Aug 22 22:03 PKT |                     |
| start   | --force --driver=nono          | minikube | root | v1.26.1 | 12 Aug 22 22:03 PKT |                     |
| start   |                                | minikube | root | v1.26.1 | 12 Aug 22 22:06 PKT |                     |
|---------|--------------------------------|----------|------|---------|---------------------|---------------------|

* 
* ==> Last Start <==
* Log file created at: 2022/08/12 22:06:20
Running on machine: IT1R3-14
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0812 22:06:20.998601    3739 out.go:296] Setting OutFile to fd 1 ...
I0812 22:06:20.998723    3739 out.go:348] isatty.IsTerminal(1) = true
I0812 22:06:20.998726    3739 out.go:309] Setting ErrFile to fd 2...
I0812 22:06:20.998731    3739 out.go:348] isatty.IsTerminal(2) = true
I0812 22:06:20.998797    3739 root.go:333] Updating PATH: /root/.minikube/bin
W0812 22:06:20.998862    3739 root.go:310] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0812 22:06:20.998982    3739 out.go:303] Setting JSON to false
I0812 22:06:20.999481    3739 start.go:115] hostinfo: {"hostname":"IT1R3-14","uptime":14597,"bootTime":1660309384,"procs":19,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.10.102.1-microsoft-standard-WSL2","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"fb44c62e-be20-4d89-b913-fe806f03ec75"}
I0812 22:06:20.999513    3739 start.go:125] virtualization:  
I0812 22:06:21.003548    3739 out.go:177] 😄  minikube v1.26.1 on Ubuntu 18.04
W0812 22:06:21.009237    3739 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0812 22:06:21.009340    3739 notify.go:193] Checking for updates...
I0812 22:06:21.009435    3739 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=containerd, KubernetesVersion=v1.24.3
I0812 22:06:21.009465    3739 driver.go:365] Setting default libvirt URI to qemu:///system
I0812 22:06:21.009656    3739 exec_runner.go:51] Run: systemctl --version
I0812 22:06:21.015415    3739 out.go:177] ✨  Using the none driver based on existing profile
I0812 22:06:21.018655    3739 start.go:284] selected driver: none
I0812 22:06:21.018664    3739 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:3100 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:containerd CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI:bridge NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.26.165.162 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:containerd ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0812 22:06:21.018728    3739 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0812 22:06:21.019500    3739 cni.go:95] Creating CNI manager for "bridge"
I0812 22:06:21.019512    3739 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:3100 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:containerd CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI:bridge NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.26.165.162 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:containerd ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0812 22:06:21.022690    3739 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0812 22:06:21.025537    3739 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0812 22:06:21.025656    3739 cache.go:208] Successfully downloaded all kic artifacts
I0812 22:06:21.025669    3739 start.go:371] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0812 22:06:21.025808    3739 start.go:375] acquired machines lock for "minikube" in 119.5µs
I0812 22:06:21.025821    3739 start.go:95] Skipping create...Using existing machine configuration
I0812 22:06:21.025826    3739 fix.go:55] fixHost starting: m01
W0812 22:06:21.026295    3739 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0812 22:06:21.026301    3739 api_server.go:165] Checking apiserver status ...
I0812 22:06:21.026318    3739 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0812 22:06:21.032643    3739 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0812 22:06:21.032674    3739 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0812 22:06:21.039043    3739 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0812 22:06:21.039053    3739 fix.go:129] unexpected machine state, will restart: <nil>
I0812 22:06:21.043757    3739 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0812 22:06:21.048516    3739 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0812 22:06:21.048603    3739 start.go:307] post-start starting for "minikube" (driver="none")
I0812 22:06:21.048609    3739 start.go:335] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0812 22:06:21.048632    3739 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0812 22:06:21.053783    3739 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0812 22:06:21.053795    3739 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0812 22:06:21.053801    3739 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0812 22:06:21.058429    3739 out.go:177] ℹ️  OS release is Ubuntu 18.04.2 LTS
I0812 22:06:21.061601    3739 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0812 22:06:21.061634    3739 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0812 22:06:21.061646    3739 start.go:310] post-start completed in 13.0367ms
I0812 22:06:21.061651    3739 fix.go:57] fixHost completed within 35.8256ms
I0812 22:06:21.061654    3739 start.go:82] releasing machines lock for "minikube", held for 35.841ms
I0812 22:06:21.065289    3739 out.go:177] 
I0812 22:06:21.062040    3739 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
W0812 22:06:21.068572    3739 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: unknown network plugin: 
W0812 22:06:21.068614    3739 out.go:239] 
W0812 22:06:21.069386    3739 out.go:239] [31m╭───────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                             [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0812 22:06:21.073943    3739 out.go:177] 

* 

### Operating System

Windows

### Driver

Hyper-V

**Comment by klaases** [comment]
Are you passing a network flag or using plugin, re:

`❌ Exiting due to RUNTIME_ENABLE: unknown network plugin:`

If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

`$ minikube logs --file=logs.txt` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
I'm not sure if this is resolved with minikube v1.27.0, but network plugin is empty which is failing the following call:

https://github.com/kubernetes/minikube/blob/aca5f29b40319bf79de1e3eb15edcca7da7b5481/pkg/minikube/cruntime/cruntime.go#L341-L347

We should likely be defaulting network plugin to `cni` to prevent this failure.
