### ISSUE TITLE
Minikube start isuse

### ISSUE THREAD

**Issue by schauhan0055** [kubernetes/minikube#14781]
### What Happened?

*
* ==> Audit <==
* |---------|----------------------------------------------------------|----------|------|---------|---------------------|---------------------|
| Command |                           Args                           | Profile  | User | Version |     Start Time      |      End Time       |
|---------|----------------------------------------------------------|----------|------|---------|---------------------|---------------------|
| start   | --driver=docker                                          | minikube | root | v1.26.1 | 11 Aug 22 20:55 UTC |                     |
|         | --extra-config=apiserver.service-node-port-range=1-65535 |          |      |         |                     |                     |
|         | --apiserver-ips=172.17.0.1                               |          |      |         |                     |                     |
| start   | --driver=none                                            | minikube | root | v1.26.1 | 11 Aug 22 20:55 UTC |                     |
|         | --extra-config=apiserver.service-node-port-range=1-65535 |          |      |         |                     |                     |
|         | --apiserver-ips=172.17.0.1                               |          |      |         |                     |                     |
| start   | --driver=none                                            | minikube | root | v1.26.1 | 11 Aug 22 20:57 UTC |                     |
|         | --extra-config=apiserver.service-node-port-range=1-65535 |          |      |         |                     |                     |
|         | --apiserver-ips=172.17.0.1                               |          |      |         |                     |                     |
| start   | --vm-driver=none                                         | minikube | root | v1.26.1 | 11 Aug 22 20:59 UTC |                     |
| start   | --vm-driver=none                                         | minikube | root | v1.26.1 | 11 Aug 22 20:59 UTC |                     |
| delete  |                                                          | minikube | root | v1.26.1 | 11 Aug 22 21:00 UTC | 11 Aug 22 21:00 UTC |
| start   | --vm-driver=none                                         | minikube | root | v1.26.1 | 11 Aug 22 21:00 UTC |                     |
| start   | --vm-driver=none                                         | minikube | root | v1.26.1 | 11 Aug 22 21:02 UTC |                     |
| start   | --vm-driver=none                                         | minikube | root | v1.26.1 | 11 Aug 22 21:13 UTC |                     |
| start   |                                                          | minikube | root | v1.26.1 | 11 Aug 22 21:16 UTC |                     |
| start   |                                                          | minikube | root | v1.26.1 | 11 Aug 22 21:17 UTC |                     |
|---------|----------------------------------------------------------|----------|------|---------|---------------------|---------------------|

*
* ==> Last Start <==
* Log file created at: 2022/08/11 21:17:57
Running on machine: K8
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0811 21:17:57.459876    9595 out.go:296] Setting OutFile to fd 1 ...
I0811 21:17:57.459993    9595 out.go:348] isatty.IsTerminal(1) = true
I0811 21:17:57.459996    9595 out.go:309] Setting ErrFile to fd 2...
I0811 21:17:57.460002    9595 out.go:348] isatty.IsTerminal(2) = true
I0811 21:17:57.460103    9595 root.go:333] Updating PATH: /root/.minikube/bin
W0811 21:17:57.460192    9595 root.go:310] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0811 21:17:57.460364    9595 out.go:303] Setting JSON to false
I0811 21:17:57.461025    9595 start.go:115] hostinfo: {"hostname":"K8","uptime":1978,"bootTime":1660250700,"procs":134,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.15.0-1017-azure","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"740609f6-10bd-4a9e-9878-c139ffdcee6e"}
I0811 21:17:57.461079    9595 start.go:125] virtualization: kvm host
I0811 21:17:57.471559    9595 out.go:177] 😄  minikube v1.26.1 on Ubuntu 20.04
W0811 21:17:57.479763    9595 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0811 21:17:57.479903    9595 notify.go:193] Checking for updates...
I0811 21:17:57.480374    9595 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.3
I0811 21:17:57.480433    9595 driver.go:365] Setting default libvirt URI to qemu:///system
I0811 21:17:57.480816    9595 exec_runner.go:51] Run: systemctl --version
I0811 21:17:57.489626    9595 out.go:177] ✨  Using the none driver based on existing profile
I0811 21:17:57.493943    9595 start.go:284] selected driver: none
I0811 21:17:57.493957    9595 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[172.17.0.1] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:apiserver Key:service-node-port-range Value:1-65535} {Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:10.0.0.4 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0811 21:17:57.494044    9595 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0811 21:17:57.494068    9595 start.go:1544] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0811 21:17:57.494547    9595 cni.go:95] Creating CNI manager for ""
I0811 21:17:57.494551    9595 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0811 21:17:57.494562    9595 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[172.17.0.1] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:apiserver Key:service-node-port-range Value:1-65535} {Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:10.0.0.4 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0811 21:17:57.503940    9595 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0811 21:17:57.508532    9595 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0811 21:17:57.508717    9595 cache.go:208] Successfully downloaded all kic artifacts
I0811 21:17:57.508742    9595 start.go:371] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0811 21:17:57.508941    9595 start.go:375] acquired machines lock for "minikube" in 184.898µs
I0811 21:17:57.508954    9595 start.go:95] Skipping create...Using existing machine configuration
I0811 21:17:57.508958    9595 fix.go:55] fixHost starting: m01
W0811 21:17:57.509111    9595 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0811 21:17:57.509118    9595 api_server.go:165] Checking apiserver status ...
I0811 21:17:57.509141    9595 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0811 21:17:57.524168    9595 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0811 21:17:57.524197    9595 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0811 21:17:57.536544    9595 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0811 21:17:57.536560    9595 fix.go:129] unexpected machine state, will restart: <nil>
I0811 21:17:57.541820    9595 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0811 21:17:57.551312    9595 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0811 21:17:57.551419    9595 start.go:307] post-start starting for "minikube" (driver="none")
I0811 21:17:57.551451    9595 start.go:335] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0811 21:17:57.551491    9595 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0811 21:17:57.574780    9595 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0811 21:17:57.574800    9595 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0811 21:17:57.574808    9595 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0811 21:17:57.580129    9595 out.go:177] ℹ️  OS release is Ubuntu 20.04.4 LTS
I0811 21:17:57.587402    9595 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0811 21:17:57.587459    9595 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0811 21:17:57.587476    9595 start.go:310] post-start completed in 36.050712ms
I0811 21:17:57.587482    9595 fix.go:57] fixHost completed within 78.524655ms
I0811 21:17:57.587485    9595 start.go:82] releasing machines lock for "minikube", held for 78.538155ms
I0811 21:17:57.588485    9595 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0811 21:17:57.588486    9595 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0811 21:17:57.613062    9595 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0811 21:17:57.909708    9595 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0811 21:17:58.197060    9595 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0811 21:17:58.475748    9595 exec_runner.go:51] Run: sudo systemctl restart docker
I0811 21:17:58.868239    9595 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0811 21:17:59.143735    9595 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0811 21:17:59.424831    9595 exec_runner.go:51] Run: sudo systemctl start cri-docker.socket
I0811 21:17:59.438216    9595 start.go:450] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0811 21:17:59.438269    9595 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0811 21:17:59.439715    9595 start.go:471] Will wait 60s for crictl version
I0811 21:17:59.439745    9595 exec_runner.go:51] Run: sudo crictl version
I0811 21:17:59.447886    9595 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0811 21:18:10.494771    9595 exec_runner.go:51] Run: sudo crictl version
I0811 21:18:10.504745    9595 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0811 21:18:32.116952    9595 exec_runner.go:51] Run: sudo crictl version
I0811 21:18:32.131167    9595 retry.go:31] will retry after 26.202601198s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0811 21:18:58.334049    9595 exec_runner.go:51] Run: sudo crictl version
I0811 21:18:58.352140    9595 out.go:177]
W0811 21:18:58.359194    9595 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

W0811 21:18:58.359218    9595 out.go:239]
W0811 21:18:58.360150    9595 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0811 21:18:58.368538    9595 out.go:177]

### Attach the log file

We unable to start the minikube

**Comment by afbjorklund** [comment]
You need to install `crictl`, it's a new requirement (for docker) since k8s 1.24

https://minikube.sigs.k8s.io/docs/drivers/none/

**Comment by klaases** [comment]
Hi @schauhan0055 – were you able to install `crictl` as suggested?

Please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
