### ISSUE TITLE
Error on command minikube start

### ISSUE THREAD

**Issue by sachinjangramp** [kubernetes/minikube#14790]
### What Happened?

![Screenshot from 2022-08-14 19-52-28](https://user-images.githubusercontent.com/97403847/184541909-b4fbaeb8-9d60-46da-b186-c2260fa88d26.png)

### Attach the log file

As issue content character limit was crossing, i'm giving a link for logs.txt
https://drive.google.com/drive/folders/19a-Bhca28pAMMF5BJbUDB70o_qB9qIOu?usp=sharing

### Operating System

Ubuntu

### Driver

Docker

**Comment by RA489** [comment]
@sachinjangramp looks like your apiserver is not in running state.

**Comment by sachinjangramp** [comment]
> 

There are also problems in configuring RBAC rules and enabling default storageclass

**Comment by hal-shin** [comment]
@sachinjangramp Hey, I'm also on Ubuntu 22.0.4 and I had the same issue as you yesterday. Take a look at [https://github.com/kubernetes/minikube/issues/14540#issuecomment-1208974865](https://github.com/kubernetes/minikube/issues/14540#issuecomment-1208974865). It could be that if you have Docker Desktop installed, that may be causing some problems in your minikube cluster.

**Comment by sachinjangramp** [comment]
@hal-shin Hey, thanks for the effort. Although i tried to install minkube with KVM according to official documentation - https://minikube.sigs.k8s.io/docs/drivers/kvm2/ and it worked fine for me, but i'll try it in some days.
