### ISSUE TITLE
Not able start minikube

### ISSUE THREAD

**Issue by umeshsoni2** [kubernetes/minikube#14792]
### What Happened?

Not start minikube.

### Attach the log file

* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   | --vm-driver=none | minikube | root | v1.26.1 | 15 Aug 22 04:43 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.1 | 15 Aug 22 04:49 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/08/15 04:49:29
Running on machine: ip-172-31-38-114
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0815 04:49:29.858665    8106 out.go:296] Setting OutFile to fd 1 ...
I0815 04:49:29.858789    8106 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0815 04:49:29.858794    8106 out.go:309] Setting ErrFile to fd 2...
I0815 04:49:29.858800    8106 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0815 04:49:29.858925    8106 root.go:333] Updating PATH: /root/.minikube/bin
W0815 04:49:29.859043    8106 root.go:310] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0815 04:49:29.859222    8106 out.go:303] Setting JSON to false
I0815 04:49:29.860003    8106 start.go:115] hostinfo: {"hostname":"ip-172-31-38-114","uptime":475,"bootTime":1660538495,"procs":119,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.4.0-1078-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec285fdb-56ce-fb1b-41f8-00cbb74e3d5b"}
I0815 04:49:29.860070    8106 start.go:125] virtualization: xen guest
I0815 04:49:29.864120    8106 out.go:177] * minikube v1.26.1 on Ubuntu 18.04 (xen/amd64)
W0815 04:49:29.866290    8106 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0815 04:49:29.866509    8106 notify.go:193] Checking for updates...
I0815 04:49:29.866714    8106 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.3
I0815 04:49:29.867035    8106 exec_runner.go:51] Run: systemctl --version
I0815 04:49:29.870105    8106 driver.go:365] Setting default libvirt URI to qemu:///system
I0815 04:49:29.872528    8106 out.go:177] * Using the none driver based on existing profile
I0815 04:49:29.874520    8106 start.go:284] selected driver: none
I0815 04:49:29.874535    8106 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0815 04:49:29.874624    8106 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0815 04:49:29.874648    8106 start.go:1544] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0815 04:49:29.875079    8106 cni.go:95] Creating CNI manager for ""
I0815 04:49:29.875087    8106 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0815 04:49:29.875101    8106 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0815 04:49:29.877485    8106 out.go:177] * Starting control plane node minikube in cluster minikube
I0815 04:49:29.879635    8106 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0815 04:49:29.879835    8106 cache.go:208] Successfully downloaded all kic artifacts
I0815 04:49:29.879856    8106 start.go:371] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0815 04:49:29.880046    8106 start.go:375] acquired machines lock for "minikube" in 172.226µs
I0815 04:49:29.880064    8106 start.go:95] Skipping create...Using existing machine configuration
I0815 04:49:29.880072    8106 fix.go:55] fixHost starting: m01
W0815 04:49:29.880247    8106 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0815 04:49:29.880261    8106 api_server.go:165] Checking apiserver status ...
I0815 04:49:29.880287    8106 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0815 04:49:29.894252    8106 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0815 04:49:29.894292    8106 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0815 04:49:29.904285    8106 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0815 04:49:29.904300    8106 fix.go:129] unexpected machine state, will restart: <nil>
I0815 04:49:29.906756    8106 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I0815 04:49:29.909696    8106 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0815 04:49:29.909837    8106 start.go:307] post-start starting for "minikube" (driver="none")
I0815 04:49:29.909883    8106 start.go:335] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0815 04:49:29.909921    8106 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0815 04:49:29.920484    8106 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0815 04:49:29.920505    8106 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0815 04:49:29.920517    8106 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0815 04:49:29.923821    8106 out.go:177] * OS release is Ubuntu 18.04.6 LTS
I0815 04:49:29.925846    8106 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0815 04:49:29.925907    8106 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0815 04:49:29.925951    8106 start.go:310] post-start completed in 16.10309ms
I0815 04:49:29.925960    8106 fix.go:57] fixHost completed within 45.890376ms
I0815 04:49:29.925967    8106 start.go:82] releasing machines lock for "minikube", held for 45.911449ms
I0815 04:49:29.926403    8106 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0815 04:49:29.926522    8106 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0815 04:49:29.955588    8106 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0815 04:49:30.109421    8106 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0815 04:49:30.238634    8106 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0815 04:49:30.390713    8106 exec_runner.go:51] Run: sudo systemctl restart docker
I0815 04:49:30.695727    8106 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0815 04:49:30.866028    8106 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0815 04:49:31.034723    8106 exec_runner.go:51] Run: sudo systemctl start cri-docker.socket
I0815 04:49:31.046115    8106 start.go:450] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0815 04:49:31.046193    8106 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0815 04:49:31.050243    8106 start.go:471] Will wait 60s for crictl version
I0815 04:49:31.050281    8106 exec_runner.go:51] Run: sudo crictl version
I0815 04:49:31.054754    8106 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0815 04:49:42.103141    8106 exec_runner.go:51] Run: sudo crictl version
I0815 04:49:42.108156    8106 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0815 04:50:03.716087    8106 exec_runner.go:51] Run: sudo crictl version
I0815 04:50:03.721371    8106 retry.go:31] will retry after 26.202601198s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0815 04:50:29.924201    8106 exec_runner.go:51] Run: sudo crictl version
I0815 04:50:29.933369    8106 out.go:177]
W0815 04:50:29.935459    8106 out.go:239] X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

W0815 04:50:29.935487    8106 out.go:239] *
W0815 04:50:29.936429    8106 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0815 04:50:29.938295    8106 out.go:177]

**Comment by klaases** [comment]
Hi @umeshsoni2, have you tried installing `crictl`?

From the logs:

```
sudo: crictl: command not found
I0815 04:49:42.103141 8106 exec_runner.go:51] Run: sudo crictl version
I0815 04:49:42.108156 8106 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0815 04:50:03.716087 8106 exec_runner.go:51] Run: sudo crictl version
I0815 04:50:03.721371 8106 retry.go:31] will retry after 26.202601198s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0815 04:50:29.924201 8106 exec_runner.go:51] Run: sudo crictl version
I0815 04:50:29.933369 8106 out.go:177]
W0815 04:50:29.935459 8106 out.go:239] X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
```

**Comment by klaases** [comment]
Hi @umeshsoni2 – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
