### ISSUE TITLE
minikube start fails with network unreachable

### ISSUE THREAD

**Issue by RalfBeckesch** [kubernetes/minikube#14809]
### What Happened?

I tried to run minikube start, but it failed.

rb@ralf-schenkervia15pro~> lsb_release -a
LSB Version:    n/a
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        21.3.7
Codename:       Ruah

rb@ralf-schenkervia15pro~> uname -a
Linux ralf-schenkervia15pro 5.19.1-3-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Aug 13 06:34:52 UTC 2022 x86_64 GNU/Linux

rb@ralf-schenkervia15pro~> minikube version
minikube version: v1.26.1
commit: 62e108c3dfdec8029a890ad6d8ef96b6461426dc-dirty

rb@ralf-schenkervia15pro~(1!)> kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"archive", BuildDate:"2022-08-08T17:09:48Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Unable to connect to the server: dial tcp 192.168.49.2:8443: connect: network is unreachable

[logs.txt](https://github.com/kubernetes/minikube/files/9368411/logs.txt)

----
rb@ralf-schenkervia15pro~> minikube start
😄  minikube v1.26.1 auf Arch 21.3.7
✨  Treiber docker wurde automatisch ausgewählt. Andere Möglichkeiten: virtualbox, ssh
📌  Using Docker driver with root privileges
👍  Starte Control Plane Node minikube in Cluster minikube
🚜  Ziehe das Base Image ...
💾  Lade Kubernetes v1.24.3 herunter ...
    > gcr.io/k8s-minikube/kicbase:  386.61 MiB / 386.61 MiB  100.00% 2.09 MiB p
    > preloaded-images-k8s-v18-v1...:  405.75 MiB / 405.75 MiB  100.00% 1.87 Mi
    > gcr.io/k8s-minikube/kicbase:  0 B [______________________] ?% ? p/s 1m52s
🔥  Erstelle docker container (CPUs=2, Speicher=7601MB) ...
🐳  Vorbereiten von Kubernetes v1.24.3 auf Docker 20.10.17...
    ▪ Generiere Zertifikate und Schlüssel ...
    ▪ Starte Control-Plane ...
    ▪ Konfiguriere RBAC Regeln ...\ E0818 08:47:27.870720    4445 start.go:267] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifiziere Kubernetes Komponenten...
    ▪ Verwende Image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Das Aktivieren von 'default-storageclass lieferte einen Fehler zurück: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.49.2:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 192.168.49.2:8443: connect: network is unreachable]
🌟  Addons aktiviert: storage-provisioner

❌  Terminiere aufgrund von GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                           │
│    😿  Bitte lassen Sie es uns wissen, falls der obige Hinweis nicht weiterhilft:                         │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                           │
│                                                                                                           │
│    Bitte führen Sie `minikube logs --file=logs.txt` aus und fügen Sie logs.txt an das GitHub Issue an.    │
│                                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────╯

rb@ralf-schenkervia15pro~(80!)> minikube logs --file=logs.txt
----

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9368414/logs.txt)

### Operating System

Other

### Driver

Docker

**Comment by RalfBeckesch** [comment]
[logs.txt](https://github.com/kubernetes/minikube/files/9371391/logs.txt)

This log is from an identical run with additional "--v=5"

**Comment by afbjorklund** [comment]
minikube does not support docker desktop yet

* https://github.com/kubernetes/minikube/issues/14202

the "docker" driver assumes docker engine (no VM)

https://docs.docker.com/engine/
