### ISSUE TITLE
Error while pulling image (rpc error: code = Unknown desc = context deadline exceeded)

### ISSUE THREAD

**Issue by mertkaant** [kubernetes/minikube#14806]
Hello all, 

I'm a newbie with minikube and Kubernetes. I'll give you a brief info about what I did for installation and what's my issue. I'm dealing with this issue for a couple of weeks now and I still couldn't fix it so I wanted to ask you people so maybe someone can help me.

- My OS: Ubuntu 16.04
- minikube version: v1.26.1
- Docker version: 20.10.17
- Kubernetes version: v1.24.3

My installation order:
1. Docker
2. Kubectl
3. Minikube
4. Helm

I'm trying to deploy an OpenSearch cluster to Kubernetes with Helm. I'm using Docker as driver for minikube. When I run `minikube start --cpus 4 --memory 8192`
minikube starts successfully but it gives me a warning message like "This container is having trouble accessing https://k8s.gcr.io" 
```
* minikube v1.26.1 on Ubuntu 16.04
* Using the docker driver based on user configuration
* Using Docker driver with root privileges
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Creating docker container (CPUs=4, Memory=8192MB) ...
! This container is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

After the setup, I tried to install the default OpenSearch demo cluster with Helm. My command for Helm:
`helm install opensearch-master opensearch/opensearch -f master.yaml`
The master.yaml has the variables for OpenSearch cluster and image name etc. (There are no typos hence my error is not about typo)

When I run that command I get the following error:
```
ntsysadm@ubuntu-vm2:~$ kubectl get events
9m51s       Normal    Pulling                   pod/opensearch-cluster-master-0   Pulling image "opensearchproject/opensearch:2.2.0"
7m52s       Warning   Failed                    pod/opensearch-cluster-master-0   Failed to pull image "opensearchproject/opensearch:2.2.0": rpc error: code = Unknown desc = context deadline exceeded
7m52s       Warning   Failed                    pod/opensearch-cluster-master-0   Error: ErrImagePull
2m          Normal    BackOff                   pod/opensearch-cluster-master-0   Back-off pulling image "opensearchproject/opensearch:2.2.0"
10m         Warning   Failed                    pod/opensearch-cluster-master-0   Error: ImagePullBackOff

```
I still have no clue why I can't pull images. I don't know whether it's related to docker or not. Like I said I'm a newbie who wants to learn more about this Kubernetes, Docker, minikube ocean. Can anyone help me understand and troubleshoot the issue, please?

Thanks already!

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9359481/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by leirons** [comment]
I have same error any ideas how to fix?

**Comment by afbjorklund** [comment]
Looks like a duplicate:

* #14789

**Comment by mertkaant** [comment]
> minikube ssh docker pull

This command fixed my issue. I pulled the OpenSearch image and run the demo as I mentioned on the issue and it is now successfully deployed. Thanks a lot @afbjorklund

**Comment by cedricroijakkers** [comment]
I am having the same issue pulling rather large (> 2GB) containers in minikube.

In my `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf` I have the timeout property set to `--runtime-request-timeout=15m` (this was set by default, I did not have to change this), but according to the [documentation](https://v1-24.docs.kubernetes.io/docs/reference/command-line-tools-reference/kubelet/), this is now deprecated and should be in the kubelet configuration file.

Seems like this is not only deprecated, but quite frankly no longer working. Even with the timeout set to `15m`, a pull of a large image fails after exactly 2 minutes, which is the default.

So, I have updated both the file `/var/lib/kubelet/config.yaml` and the configmap `kube-system/kubelet-config` by setting the key `runtimeRequestTimeout` to `15m`, restarted kubelet, but still after 2 minutes the pull of the image stops.

Pulling time image manually with the `docker pull` command works, but this is of course not a viable solution, as it needs to be done for every image failing. It should just accept the timeout of 15 minutes which has been configured in multiple places, but it is not having any effect.

**Comment by afbjorklund** [comment]
See the original issue for links and patches

**Comment by ccdaniele** [comment]
Thanks, this solved my issue

> Looks like a duplicate:
> 
> * [Can't pull modestly sized image from Quay.io #14789](https://github.com/kubernetes/minikube/issues/14789)
> 
> Workaround (no timeout):
> 
> `minikube ssh docker pull`

**Comment by ADNANFAKHAR4504** [comment]
Set your environment variable and encode in the right manner .dokcerconfigjson and encode into base64 and copy the text that is encoded and place in yaml and then apply Hopefully it will resolve the issue

**Comment by cedricroijakkers** [comment]
With `cri-dockerd` version `0.2.6` (https://github.com/Mirantis/cri-dockerd/releases/tag/v0.2.6) this issue is now resolved for me.
