### ISSUE TITLE
Unable to stop VM: registry: driver not found

### ISSUE THREAD

**Issue by zeng8750** [kubernetes/minikube#14808]
minikube start --registry-mirror=https://registry.docker-cn.com
😄  minikube v1.2.0 on linux (amd64)
💥  Kubernetes downgrade is not supported, will continue to use v1.24.3
✅  using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
E0818 11:39:02.652826  149915 start.go:559] StartHost: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: registry: driver not found

💣  Unable to start VM: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: registry: driver not found

---

 minikube delete

💣  Failed to delete cluster: registry: driver not found

**Comment by klaases** [comment]
Hi @zeng8750  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support
