### ISSUE TITLE
`minikube start` gives memory allocation warning even with 8 GB of RAM

### ISSUE THREAD

**Issue by astrojuanlu** [kubernetes/minikube#14810]
### What Happened?

One of our users reports memory allocation warnings when running `minikube start --memory max` on AWS instances with 8 GB of RAM:

```
$ minikube start --cpus max --memory max --disk-size 50g
...
* minikube v1.26.1 on Ubuntu 20.04 (xen/amd64)
* Using the docker driver based on existing profile
X The requested memory allocation of 7948MiB does not leave room for system overhead (total system memory: 7948MiB). You may face stability issues.
* Suggestion: Start minikube with less memory allocated: 'minikube start --memory=2200mb'
...
```

If there needs to be overhead anyway, what's the point of `--memory max`?

### Attach the log file

(TBC)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Using `max` is supposed to suggest 1GiB _less_ than the system memory:

```go
func noLimitMemory(sysLimit int, containerLimit int) int {
        if containerLimit != 0 {
                return containerLimit
        }
        // Recommend 1GB to handle OS/VM overhead
        return sysLimit - 1024
}
```

Looks like it is using the value from `docker info`, without the extra buffer...

**Comment by kadern0** [comment]
@afbjorklund , should the function `noLimitMemory` return `containerLimit - 1024` then?

**Comment by afbjorklund** [comment]
Possibly...

On a system running Docker Engine (or Podman Engine), they will be the same.

On a system with Docker Desktop (or Podman Desktop), it shows the VM.

But either should use as much as possible, without complaining.

**Comment by afbjorklund** [comment]
Kubernetes only requires that the "hardware" has at least 2048 MiB, and that the OS has at least 1700 MiB total. It doesn't require anything like this 1024 MiB heuristic.
