### ISSUE TITLE
Minicube ingress not found

### ISSUE THREAD

**Issue by Luchik51** [kubernetes/minikube#14816]
### What Happened?

command
minikube addons enable ingress
not work

### Attach the log file

Log file created at: 2022/08/18 20:36:38
Running on machine: vagrant
Binary: Built with gc go1.16.4 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0818 20:36:38.331684   30942 out.go:291] Setting OutFile to fd 1 ...
I0818 20:36:38.331826   30942 out.go:343] isatty.IsTerminal(1) = true
I0818 20:36:38.331830   30942 out.go:304] Setting ErrFile to fd 2...
I0818 20:36:38.331834   30942 out.go:343] isatty.IsTerminal(2) = true
I0818 20:36:38.331983   30942 root.go:316] Updating PATH: /home/vagrant/.minikube/bin
W0818 20:36:38.332123   30942 root.go:291] Error reading config file at /home/vagrant/.minikube/config/config.json: open /home/vagrant/.minikube/config/config.json: no such file or directory
I0818 20:36:38.338782   30942 out.go:170] 
W0818 20:36:38.339030   30942 out.go:235] ❌  Exiting due to MK_ENABLE: loading profile: cluster "minikube" does not exist
W0818 20:36:38.339058   30942 out.go:235] 
W0818 20:36:38.341140   30942 out.go:235] ╭─────────────────────────────────────────────────────────────────────────────╮
W0818 20:36:38.341186   30942 out.go:235] │                                                                             │
W0818 20:36:38.341197   30942 out.go:235] │    😿  If the above advice does not help, please let us know:               │
W0818 20:36:38.341206   30942 out.go:235] │    👉  https://github.com/kubernetes/minikube/issues/new/choose             │
W0818 20:36:38.341214   30942 out.go:235] │                                                                             │
W0818 20:36:38.341223   30942 out.go:235] │    Please attach the following file to the GitHub issue:                    │
W0818 20:36:38.341231   30942 out.go:235] │    - /tmp/minikube_addons_f229260beb9d81c81fc02ad297432f98de5063c5_0.log    │
W0818 20:36:38.341239   30942 out.go:235] │                                                                             │
W0818 20:36:38.341249   30942 out.go:235] ╰─────────────────────────────────────────────────────────────────────────────╯
W0818 20:36:38.341259   30942 out.go:235] 

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by klaases** [comment]
Hi @Luchik51, thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @Luchik51, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
