### ISSUE TITLE
network: protocol not available

### ISSUE THREAD

**Issue by lvyuan8908412** [kubernetes/minikube#14825]
[root@ch7 ~]# kubectl get pod --all-namespaces
![1661075913706](https://user-images.githubusercontent.com/16499436/185785745-ae3c5cfa-5821-480a-b011-2fb46304a0a6.png)
[root@ch7 ~]# kubectl describe pod coredns-7f74c56694-wq57m -n kube-system

Warning  FailedCreatePodSandBox  50s (x3 over 51s)   kubelet, ch7.nauu.com  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "610a6b3999d9b7329e2a9efb5a5ede8dee05dd68c98c230c4a3e9b8d2e30ba6b" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
 
![1661076109137](https://user-images.githubusercontent.com/16499436/185785850-9bfc630c-e581-4377-920f-02d4abf6dd8d.png)

**Comment by kundan2707** [comment]
@lvyuan8908412 can you share log for coredns pod?

**Comment by lvyuan8908412** [comment]
[root@ch7 ~]# kubectl describe pod coredns-7f74c56694-wq57m -n kube-system
Name:                 coredns-7f74c56694-wq57m
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 ch7.nauu.com/192.168.124.27
Start Time:           Sun, 21 Aug 2022 02:39:05 -0700
Labels:               k8s-app=kube-dns
                      pod-template-hash=7f74c56694
Annotations:          <none>
Status:               Pending
IP:                   
IPs:                  <none>
Controlled By:        ReplicaSet/coredns-7f74c56694
Containers:
  coredns:
    Container ID:  
    Image:         registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.8.6
    Image ID:      
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8181/ready delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-nlzkh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  kube-api-access-nlzkh:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly
                             node-role.kubernetes.io/control-plane:NoSchedule
                             node-role.kubernetes.io/master:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute for 300s
                             node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                  Age                      From                   Message
  ----     ------                  ----                     ----                   -------
  Normal   SandboxChanged          3d2h (x20308 over 3d7h)  kubelet, ch7.nauu.com  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  3d2h (x20582 over 3d7h)  kubelet, ch7.nauu.com  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "2c466496a8fad9993d80f390e07e61078596cbcfcf43e980205ef16e31e2cec2" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  83s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "edc6477fba7b4cda2df6f166887b02454fb22f611777696047b800710247e9a5" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  81s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a8ed5ba31f655ad8d1ec6f7b109d1564766ab92bf7c3df2a4f87f3515e8c6e51" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  80s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "6650566c56cbd42a40cf7a8238440e154885e7fa27c8ba24fd81e4cf89666bd8" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  79s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "a4a947b492280ea8bc9b27de6e0f084e292d42fee782c7ccceba39aea20ef4d9" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  78s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "602eddc1f0e236c7c99cff6b539118dd6a2436d7fd4f543af2e02173a6df1da2" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  77s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "1882096a5d5c3785589c876a1ec0fb8a15117a77130ba6d04aef8556e8779172" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  76s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "c0c1df98e74ba8e8afb7af10ebe6a52adae11519fb0ff07601cd6990daabae42" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  75s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "1199c59cfee4ec998a5b194466ae5601fdc4b66a516cf9c8b2bdb9e9011396dc" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Warning  FailedCreatePodSandBox  74s                      kubelet, ch7.nauu.com  Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "2a1ec547dd3d7b6bbb0d36932fad0a1a0f6c3f8f3154e0b42762eb23d935fb3c" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available
  Normal   SandboxChanged          70s (x13 over 86s)       kubelet, ch7.nauu.com  Pod sandbox changed, it will be killed and re-created.
  Warning  FailedCreatePodSandBox  70s (x3 over 72s)        kubelet, ch7.nauu.com  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "3e83f8e88e0338c43bb83d5a77eac25602517ad5e28d41eddc775ab5b317458d" network for pod "coredns-7f74c56694-wq57m": networkPlugin cni failed to set up pod "coredns-7f74c56694-wq57m_kube-system" network: protocol not available


[root@ch7 ~]# kubectl logs coredns-7f74c56694-wq57m -n kube-system
Error from server (BadRequest): container "coredns" in pod "coredns-7f74c56694-wq57m" is waiting to start: ContainerCreating

**Comment by klaases** [comment]
Thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
