### ISSUE TITLE
minikube  not connfigure

### ISSUE THREAD

**Issue by shinnu73** [kubernetes/minikube#14820]
### What Happened?

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰──────────────────────────────────

### Attach the log file

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰──────────────────────────────────

### Operating System

Ubuntu

### Driver

Docker

**Comment by shinnu73** [comment]
solve me plz

**Comment by spowelljr** [comment]
Hi, you need to have crictl installled, you can follow the instructions here https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md#install-crictl

**Comment by spowelljr** [comment]
Hi @shinnu73, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
