### ISSUE TITLE
Stop using gs://kubernetes-release bucket, use dl.k8s.io for downloads

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#14828]
The downloads should be using "`dl.k8s.io`" instead.

The hardcoded urls might cause a problem in the future
(like is happening **today**, with the registry and packages)

i.e. no more `storage.googleapis.com/kubernetes-release`

----

See: 

* https://github.com/kubernetes/k8s.io/issues/2396

**Comment by afbjorklund** [comment]
@medyagh another google infrastructure cleanup item...

~~https://storage.googleapis.com/kubernetes-release/release/stable.txt~~

I guess it also affects the "minikube" subdirectory, eventually ?

But primarily it was about kubeadm/kubelet/kubectl downloads:

```go
// DefaultKubeBinariesURL returns a URL to kube binaries
func DefaultKubeBinariesURL() string {
        return fmt.Sprintf("https://%s/kubernetes-release/release", downloadHost)
}
```

`var downloadHost = "storage.googleapis.com"`

**Comment by afbjorklund** [comment]
Current procedure follows upstream: ("Without a package manager")
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

```sh
sudo curl -L --remote-name-all https://storage.googleapis.com/kubernetes-release/release/${RELEASE}/bin/linux/${ARCH}/{kubeadm,kubelet,kubectl}
sudo chmod +x {kubeadm,kubelet,kubectl}
```

**Comment by afbjorklund** [comment]
Now changed to use "dl.k8s.io" (and removed kubectl)

* https://github.com/kubernetes/website/issues/33228

**Comment by sftim** [comment]
We are also keen to reduce our reliance on GCP (as in, on _only_ GCP) due to financial concerns.

**Comment by afbjorklund** [comment]
Note that:

Most minikube users will get their binaries from the "preload" (GCR), not from the dl.k8s.io

If the Kubernetes project _really_ wanted to make the downloads smaller, it would use .tar.xz ?

```
45M	kubeadm
46M	kubectl
116M	kubelet
207M	total
```
```
14M	kubeadm.tar.xz
15M	kubectl.tar.xz
30M	kubelet.tar.xz
58M	total
```

Should still do this change. Will make a PR...

Wonder if `dl.k8s.io` also works in China ?

**Comment by sftim** [comment]
The approach we recommend for end users subject to state-level censorship is to use a trusted mirror within their state's allowed boundary (we don't provide such a mirror).

**Comment by afbjorklund** [comment]
OK, will continue to use the current mirror then.

**Comment by afbjorklund** [comment]
Seem to be confusing GCR and GCS while typing, too close alphabetically...

Also, it seems that https://dl.k8s.io/stable.txt does not exist (so `sed` failed)

**Comment by afbjorklund** [comment]
Apparently the directory is still there, my bad. Needs a `release/`, and `--location` (to follow the redirection)

sed -e 's|curl -s https://storage.googleapis.com/kubernetes-release/release|curl -sSL https://dl.k8s.io/release|'
