### ISSUE TITLE
Unable to run the service of the minikube

### ISSUE THREAD

**Issue by blacksoul9412** [kubernetes/minikube#14834]
### What Happened?

Unable to run the minikube services 
![Screenshot 2022-08-22 172329](https://user-images.githubusercontent.com/77640947/185915194-bbb5bac2-7047-447c-90ce-bdf9fdaee30e.png)

### Attach the log file

[log error for minikube.txt](https://github.com/kubernetes/minikube/files/9394035/log.error.for.minikube.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi, you need to have crictl installled, you can follow the instructions here https://github.com/kubernetes-sigs/cri-tools/blob/master/docs/crictl.md#install-crictl

**Comment by Ranjithkhan17** [comment]
Thank you  @spowelljr , able to run minikube after installing crictl.

**Comment by spowelljr** [comment]
Glad this resolved your issue!
