### ISSUE TITLE
Allow `minikube start` to not download `docker-machine-driver-kvm2` automatically

### ISSUE THREAD

**Issue by FollieHiyuki** [kubernetes/minikube#14843]
### What Happened?

AlpineLinux has `docker-machine-driver-kvm2` packaged and I want `minikube` to use the package. Even though the command is installed and available in /usr/bin, `minikube start` keeps downloading `docker-machine-driver-kvm2` binary into ~/.minikube/bin and that binary doesn't work (might have something to do with Go binary linking).

The work around for me is symlinking /usr/bin/docker-machine-driver-kvm2 to ~/.minikube/bin/docker-machine-driver-kvm2. `minikube start --driver=kvm2` now works.

Having a flag for `start` command or a config option (that can be set with `minikube config set ...` to prevent downloading the driver helper would be nice.

### Attach the log file

Well I think we don't need the log for this case.

### Operating System

AlpineLinux

### Driver

KVM2

**Comment by afbjorklund** [comment]
Most likely the reason it doesn't work is that you are not using glibc...
The driver cannot be statically linked, since it needs libvirt library.

Having an option to opt-out if the download (or skip it, when driver exists) sounds good

**Comment by FollieHiyuki** [comment]
Yes, AlpineLinux uses musl so it should be the case. Thanks for considering the option.

**Comment by afbjorklund** [comment]
The other binaries (minikube, kubectl) probably have the same issue ? Unless installing glibc compat

Hopefully they are all available as packages, otherwise either as static or build them from source.

**Comment by FollieHiyuki** [comment]
[`minikube`](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/minikube) and [`kubectl`](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/kubectl) are already packaged for AlpineLinux. I'm using them without any issues.
