### ISSUE TITLE
can I join worker node to minikube cluster from different machine cluster

### ISSUE THREAD

**Issue by aungsanoo1996** [kubernetes/minikube#14852]
### What Happened?

can I join worker node to minikube cluster from different machine cluster

### Attach the log file

can I join worker node to minikube cluster from different machine cluster

### Operating System

Ubuntu

### Driver

KVM2

**Comment by klaases** [comment]
Hi @aungsanoo1996, please take a look at the following documentation, is this helpful?

[Using Multi-Node Clusters
](https://minikube.sigs.k8s.io/docs/tutorials/multi_node/)

/triage needs-information
/kind support

**Comment by aungsanoo1996** [comment]
> Hi @aungsanoo1996, please take a look at the following documentation, is this helpful?
> 
> [Using Multi-Node Clusters
> ](https://minikube.sigs.k8s.io/docs/tutorials/multi_node/)
> 
> /triage needs-information
> /kind support

Thanks for your advance.
