### ISSUE TITLE
apiserver :stopped

### ISSUE THREAD

**Issue by Manda-supraja26** [kubernetes/minikube#14850]
### apiserver:stopped

![image](https://user-images.githubusercontent.com/88205562/186299964-519024d6-f213-4ba2-9fff-8694da01377f.png)
![image](https://user-images.githubusercontent.com/88205562/186300055-dbdf0a36-6075-4dc2-8126-022465fc11ad.png)

apiserver health is never found healthy.
I have deleted and started again but found no difference.
can someone help me to solve my problem.

### Attach the log file

`minikube delete --all --purge`
`minikube start`
`minikube status`

### Operating System

Ubuntu

### Driver

Docker

**Comment by ps68060** [comment]
I am in this situation on Windows 10.  

Tried minikube delete and delete --all --purge as well as unistalled and re-installed minikube several times and no improvement.

**Comment by Manda-supraja26** [comment]
My problem is cleared and I have successfully installed the minikube, so I'm closing this issue.
