### ISSUE TITLE
Not able to start minikube

### ISSUE THREAD

**Issue by CoderMercury** [kubernetes/minikube#14853]
Hi All,

**I am getting error when using following command

$  minikube start --vm-driver="hyperv" --hyperv-virtual-switch="My Virtual Switch" --alsologtostderr -v=8

Here is the error**

W0824 12:02:54.519403    3344 root.go:151] Error reading config file at C:\cygwin64\home\Mercury.Coder\.minikube\config\config
.json: open C:\cygwin64\home\Mercury.Coder\.minikube\config\config.json: The system cannot find the file specified.
* minikube v1.2.0 on windows (amd64)
I0824 12:02:54.524405    3344 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v
1.2.0.iso
I0824 12:02:54.525396    3344 start.go:753] Saving config:
{
    "MachineConfig": {
        "KeepContext": false,
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso",
        "Memory": 2048,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "hyperv",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "My Virtual Switch",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "Hidden": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.15.0",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    }
}
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1
at C:\cygwin64\home\Mercury.Coder\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.15.0 at C:\cygwin64\ho
me\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.15.0
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.15.0 at C:\cygwin6
4\home\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.15.0
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.15.0 at C
:\cygwin64\home\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.15.0
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.15.0 at C:\cygwin6
4\home\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.15.0
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/pause:3.1 at C:\cygwin64\home\Mercury
.Coder\.minikube\cache\images\k8s.gcr.io\pause_3.1
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at C:
\cygwin64\home\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13
at C:\cygwin64\home\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at C:\
cygwin64\home\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at C:\cygwin64\home\Merc
ury.Coder\.minikube\cache\images\k8s.gcr.io\etcd_3.3.10
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at C:\cygwin64\home\Me
rcury.Coder\.minikube\cache\images\k8s.gcr.io\coredns_1.3.1
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 a
t C:\cygwin64\home\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.10.1
I0824 12:02:54.525396    3344 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at C:\cygwin
64\home\Mercury.Coder\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0
I0824 12:02:54.533414    3344 cluster.go:95] Skipping create...Using existing machine configuration
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minik
ube ).state
I0824 12:02:54.779283    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.779283    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.780295    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.780295    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.781977    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.781977    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.784484    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.784484    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.785485    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.785485    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.788485    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.788485    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.788485    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.788485    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.788485    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.788485    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.788485    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.789485    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.790484    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.790484    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.798485    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.798485    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:54.798485    3344 main.go:78] stdlog: keychain.go:109 Unable to read "C:\\Users\\Mercury.Coder\\.docker\\config.js
on": open C:\Users\Mercury.Coder\.docker\config.json: The system cannot find the path specified.
I0824 12:02:54.798485    3344 main.go:78] stdlog: options.go:52 No matching credentials were found, falling back on anonymous
I0824 12:02:55.128394    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0824 12:02:55.193394    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.10.1
I0824 12:02:55.346759    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0
I0824 12:02:55.404090    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13
I0824 12:02:55.425092    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.15.0
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

I0824 12:02:55.466007    3344 cluster.go:114] Machine state:
* Restarting existing hyperv VM for "minikube" ...
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minik
ube
I0824 12:02:55.549005    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13
I0824 12:02:55.580912    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\etcd_3.3.10
I0824 12:02:55.641599    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0824 12:02:55.644599    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\coredns_1.3.1
I0824 12:02:56.019574    3344 cache_images.go:309] OPENING:  \\?\Volume{9207e237-e55c-4772-bea7-869665461f36}\cygwin64\home\M
ercury.Coder\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.15.0
[stdout =====>] :
[stderr =====>] : Hyper-V\Start-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.StartVM

E0824 12:02:56.208876    3344 start.go:559] StartHost: start: exit status 1
I0824 12:02:56.212877    3344 utils.go:123] non-retriable error: start: exit status 1
W0824 12:02:56.212877    3344 exit.go:100] Unable to start VM: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**I tried to delete minikube by following command
- minikube delete

and it is not working either.

How can I start minikube installation all over?
I think this all started when I used "Cigwin" terminal in non-admin mode to install minikube to begin with.

Appreciate your help.** 

Thank you.

**Comment by spowelljr** [comment]
Hi @CoderMercury, I can see from the logs that you're using minikube v1.2.0. That version is extremely old, the current version is v1.26.1. Please try updating to the latest version, run `minikube delete` and then try starting minikube again.

**Comment by klaases** [comment]
Hi @CoderMercury – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
