### ISSUE TITLE
minikube start执行失败

### ISSUE THREAD

**Issue by shentan007git** [kubernetes/minikube#14857]
**重现问题所需的命令**：

**失败的命令的完整输出**：
minikube start --driver=docker
* minikube v1.18.1 on Centos 7.9.2009 (amd64)
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running docker "minikube" container ...
* Preparing Kubernetes v1.20.2 on Docker 20.10.3 ...

X Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubeadm.sha256 Dst:/home/tiger/.minikube/cache/linux/v1.20.2/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58] Decompressors:map[bz2:0x2db2d58 gz:0x2db2d58 tar.bz2:0x2db2d58 tar.gz:0x2db2d58 tar.xz:0x2db2d58 tbz2:0x2db2d58 tgz:0x2db2d58 txz:0x2db2d58 xz:0x2db2d58 zip:0x2db2d58] Getters:map[file:0xc0011ed3a0 http:0xc000f56880 https:0xc000f568a0] Dir:false ProgressListener:0x2d78370 Options:[0xfdf780]}: invalid checksum: Error downloading checksum file: bad response code: 404
* 
* If the above advice does not help, please let us know: 
  - https://github.com/kubernetes/minikube/issues/new/choose

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
CentOS 7.5 64bit

**Comment by fireinrain** [comment]
你这个原因大概率是一些k8s的组件在国内下载太慢了 有一些甚至不翻墙下载不到。我当初安装也是这样  我的方法是 centos安装代理工具，然后让安装时候的所有流量走代理端口，直到下载好所有组件

**Comment by fireinrain** [comment]
响应代码404 很说明问题了
