### ISSUE TITLE
not able to start minikube

### ISSUE THREAD

**Issue by Ranjithkhan17** [kubernetes/minikube#14866]
### What Happened?

ubuntu@ip-172-31-44-16:~$ sudo su
root@ip-172-31-44-16:/home/ubuntu# sudo minikube start --vm-driver=none
* minikube v1.26.1 on Ubuntu 18.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 18.04.6 LTS

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit stat                                                      us 1
stdout:

stderr:
sudo: crictl: command not found

*
╭───────────────────────────────────────────────────────────────────────────────                                                      ──────────────╮
│                                                                                                                                                   │
│    * If the above advice does not help, please let us know:                                                                                       │
│      https://github.com/kubernetes/minikube/issues/new/choose 

### Attach the log file

*
* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   |                  | minikube | root | v1.26.1 | 28 Aug 22 02:11 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.1 | 28 Aug 22 02:12 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.1 | 28 Aug 22 02:16 UTC |          |
| start   | --driver=none    | minikube | root | v1.26.1 | 28 Aug 22 02:17 UTC |          |
| start   |                  | minikube | root | v1.26.1 | 28 Aug 22 02:18 UTC |          |
| start   |                  | minikube | root | v1.26.1 | 28 Aug 22 02:33 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.1 | 28 Aug 22 02:35 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.1 | 28 Aug 22 02:36 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.1 | 28 Aug 22 02:41 UTC |          |
| start   |                  | minikube | root | v1.26.1 | 28 Aug 22 02:42 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/08/28 02:42:51
Running on machine: ip-172-31-44-16
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0828 02:42:51.337928    2158 out.go:296] Setting OutFile to fd 1 ...
I0828 02:42:51.338051    2158 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0828 02:42:51.338056    2158 out.go:309] Setting ErrFile to fd 2...
I0828 02:42:51.338062    2158 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0828 02:42:51.338184    2158 root.go:333] Updating PATH: /root/.minikube/bin
W0828 02:42:51.338297    2158 root.go:310] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0828 02:42:51.338483    2158 out.go:303] Setting JSON to false
I0828 02:42:51.339269    2158 start.go:115] hostinfo: {"hostname":"ip-172-31-44-16","uptime":184,"bootTime":1661654387,"procs":120,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.4.0-1078-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec26b5ae-bc27-e2cf-5dd7-a929af01972f"}
I0828 02:42:51.339332    2158 start.go:125] virtualization: xen guest
I0828 02:42:51.342105    2158 out.go:177] * minikube v1.26.1 on Ubuntu 18.04 (xen/amd64)
W0828 02:42:51.344077    2158 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
"logs.txt" 100L, 12713C 

### Operating System

Ubuntu

**Comment by Ranjithkhan17** [comment]
Issue got resolved after installing crictl...

Reference
https://github.com/kubernetes/minikube/issues/14834#issuecomment-1228929199

**Comment by spowelljr** [comment]
Glad your issue was resolved!
