### ISSUE TITLE
Minikube mount is empty

### ISSUE THREAD

**Issue by Rev1408** [kubernetes/minikube#1486]
I am on Ubuntu 16.04.2 LTS (Xenial Xerus) I am using minikube(v0.18.0) with KVM driver I had to mount host directory to Minikube VM, so they will be accessible to my pod, but the mounted directory is empty.

I am using the below command

minikube mount /path/to/host/directory

**Comment by aaron-prindle** [comment]
Can post the output of the mount command with debug enabled?
`minikube mount --v 10 /path/to/host/directory`

**Comment by Rev1408** [comment]
@aaron-prindle I was using minikube 0.18, updating to 0.19 mount works now
but looks like the correct command is
minikube mount /path/to/host/directory:/vmpath
