### ISSUE TITLE
minikube issue

### ISSUE THREAD

**Issue by asifktr** [kubernetes/minikube#14865]
### What Happened?

assif@ubuntu:~$ minikube start
😄  minikube v1.26.1 on Ubuntu 20.04

💢  Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "none" driver, which is incompatible with requested "docker" driver.
💡  Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=none'

### Attach the log file

sif@ubuntu:~$ minikube start
😄  minikube v1.26.1 on Ubuntu 20.04

💢  Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "none" driver, which is incompatible with requested "docker" driver.
💡  Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=none'

### Operating System

Ubuntu

### Driver

Docker

**Comment by fireinrain** [comment]
It seem you have create a minikube profile. and you start again,it failed.
try  minikube delete, and run minikube start -p cluster-name to start cluster

**Comment by spowelljr** [comment]
Adding to what @fireinrain said, once you start a profile was a driver, you can't change the driver type without first deleting the cluster (`minikube delete`). However, you can have multiple profiles, so you could run `minikube start --driver docker -p docker` and then you'd have two profiles, one using the none driver and one using the docker driver.

**Comment by klaases** [comment]
Hi @asifktr – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
