### ISSUE TITLE
 Exiting due to GUEST_PROVISION: Failed to start host: new host: dial tcp 127.0.0.1:52364: connect: can't assign requested address

### ISSUE THREAD

**Issue by claudiobizzotto-slalom** [kubernetes/minikube#14873]
### What Happened?

Minikube won't properly start on MacOS with Hyperkit.

```shell
$ minikube start
StartHost failed, but will try again: new host: dial tcp 127.0.0.1:52358: connect: can't assign requested address
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: new host: dial tcp 127.0.0.1:52364: connect: can't assign requested address

❌  Exiting due to GUEST_PROVISION: Failed to start host: new host: dial tcp 127.0.0.1:52364: connect: can't assign requested address
```

MacOS version: `12.5.1` (Monterrey), Intel
Minikube version: `v1.26.1`
Hyperkit version: `0.20200908`

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9446608/logs.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by klaases** [comment]
Hi @claudiobizzotto-slalom, did you install minikube via Brew?

Also, do you have docker installed? From the error log I noticed:

```
"minikube": docker container inspect minikube --format={{.State.Status}}: exec: "docker": executable file not found in $PATH
stdout:

stderr:
I0829 12:47:12.280664   10499 cli_runner.go:164] Run: podman container inspect minikube --format={{.State.Status}}
I0829 12:47:12.280676   10499 delete.go:46] couldn't inspect container "minikube" before deleting: unknown state "minikube": podman container inspect minikube --format={{.State.Status}}: exec: "podman": executable file not found in $PATH
stdout:

stderr:
W0829 12:47:12.280684   10499 start.go:607] delete host: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
```

**Comment by klaases** [comment]
Hi @claudiobizzotto-slalom  – is this issue still occurring? Are additional details available? If so, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
