### ISSUE TITLE
minikube start wrong k8s version

### ISSUE THREAD

**Issue by ngtuna** [kubernetes/minikube#1488]
**This is a BUG REPORT**

**Minikube version**
v0.17.1

**Environment**:
- **OS**
MacOS
- **VM Driver**
xhyve
- **ISO version**
"Boot2DockerURL": "file:///Users/tuna/.minikube/cache/iso/minikube-v1.0.7.iso"
- **Install tools**:
- **Others**:

**What happened**:
I installed k8s v1.6.0 on minikube by running `$minikube start --vm-driver=xhyve --kubernetes-version=v1.6.0` but it happened to install v1.5.3

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.3", GitCommit:"029c3a408176b55c30846f0faedf56aae5992e9b", GitTreeState:"clean", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**What you expected to happen**:
I think it should be v1.6.0

**How to reproduce it** (as minimally and precisely as possible):
```
$ minikube start --vm-driver=xhyve --kubernetes-version=v1.6.0

$ kubectl version
```

**Comment by r2d4** [comment]
Can you update to the latest minikube? (v0.19.0).  This shouldn't be happening and I'm not able to reproduce it, but v1.6.0 is the default in the latest version of minikube, so you should be able to just 

```
$ minikube delete
#upgrade to 0.19.0
$ minikube start
```

**Comment by budhrg** [comment]
Confirmed from my end that with latest version `0.19.0` I am not able to reproduce this issue.

**Comment by ngtuna** [comment]
Yeah thanks @budhrg @r2d4  `v0.19.0` makes it done beautifully. Closing.
