### ISSUE TITLE
Request for minikube to resolve host.docker.internal to the same as host.minikube.internal

### ISSUE THREAD

**Issue by nmldiegues** [kubernetes/minikube#14905]
### What Happened?

minikube resolves "host.minikube.internal" to the host IP.
Other platforms (such as Docker for Mac, or Windows) use "host.docker.internal" instead.

It would be great the latter could be added by minikube as an alias to the former, to help convergence across platforms. This way, my docker/k8s resources do not have to worry about the difference.

### Attach the log file

Not applicable

### Operating System

Ubuntu

### Driver

Docker

**Comment by klaases** [comment]
Hi @nmldiegues, have you tried setting up a local alias to point `host.minikube.internal` to `host.docker.internal`?

**Comment by nmldiegues** [comment]
How would I go about doing that in minikube?

the idea is to not have to change the container logic nor k8s deployments

**Comment by klaases** [comment]
Hi @nmldiegues, this would be a setting on your local machine, without changing container logic or k8s deployments.

Would something like the following help?

https://linux.die.net/man/8/iptables
