### ISSUE TITLE
vmware: StartHost fails : Machine didn't return an IP after 120 seconds, aborting

### ISSUE THREAD

**Issue by langyan1022** [kubernetes/minikube#14900]
I had the same problem.
After viewing the debug information, it is found that the status of the virtual machine cannot be obtained normally after starting the virtual machine.

I try to start the virtual machine directly, the virtual machine can start normally （without nogui）
![image](https://user-images.githubusercontent.com/5259422/187879936-95ef25c2-ed46-4630-9add-a1f423d45a2a.png)
![image](https://user-images.githubusercontent.com/5259422/187879973-19576dfd-e6b6-4961-943a-a41d04d35c79.png)

with nogui

![image](https://user-images.githubusercontent.com/5259422/187880178-3aa471d0-90e1-4a69-ac43-47f53ba3fddc.png)

But after executing minikube start, the newly opened window executes vmrun.exe list and the result is that there is no running virtual machine，

Below is the log file during execution
[logs.txt](https://github.com/kubernetes/minikube/files/9468559/logs.txt)

What should I do to get it working?

_Originally posted by @langyan1022 in https://github.com/kubernetes/minikube/issues/9434#issuecomment-1234007545_

**Comment by klaases** [comment]
Hi @langyan1022  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support
