### ISSUE TITLE
minikube error

### ISSUE THREAD

**Issue by toufikbenkhelifa** [kubernetes/minikube#14906]
### What Happened?

command :
sudo minikube start
output : 
😄  minikube v1.26.1 on Ubuntu 22.04
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
✨  Using the docker driver based on existing profile
🛑  The "docker" driver should not be used with root privileges. If you wish to continue as root, use --force.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
💡  Tip: To remove this root owned cluster, run: sudo minikube delete
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: boot lock: unable to open /tmp/juju-mke11f63b5835bf422927bf558fccac7a21a838f: permission denied
😿  Failed to start docker container. Running "minikube delete" may fix it: boot lock: unable to open /tmp/juju-mke11f63b5835bf422927bf558fccac7a21a838f: permission denied

❌  Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed to start host: boot lock: unable to open /tmp/juju-mke11f63b5835bf422927bf558fccac7a21a838f: permission denied
💡  Suggestion: Run 'sudo sysctl fs.protected_regular=0', or try a driver which does not require root, such as '--driver=docker'
🍿  Related issue: https://github.com/kubernetes/minikube/issues/6391

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9481450/logs.txt)

**Comment by toufikbenkhelifa** [comment]
this command worked for me : 
`minikube delete && minikube start`

**Comment by klaases** [comment]
Hi @toufikbenkhelifa, glad that you were able to find a solution to the issue!

If needed, please feel free to re-open the issue by commenting with `/reopen`.

Thank you for sharing your experience!
