### ISSUE TITLE
minikube: Failed to pull image "nginx:alpine": rpc error: code = Unknown desc = error pulling image configuration: download failed after attempts=6: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Sachin-Sangal** [kubernetes/minikube#14907]
### What Happened?

I just started learning Docker and Kubernetes. Installed minikube and docker on my windows machine. I am able to pull image from docker using docker pull command but getting below error with kubectl. Please help.

 Warning  Failed     18s (x2 over 53s)  kubelet            Failed to pull image "nginx:alpine": rpc error: code = Unknown desc = error pulling image configuration: download failed after attempts=6: x509: certificate signed by unknown authority
  Warning  Failed     18s (

This is my yml file.

apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
  - name: nginx1
    image: nginx:alpine
    ports:
      - containerPort: 80
      - containerPort: 443

Thanks in advance.

### Attach the log file

![image](https://user-images.githubusercontent.com/112748659/188260176-7a6c9f48-f49d-44f0-b930-9d17b88e9c52.png)

### Operating System

Windows

### Driver

Docker

**Comment by klaases** [comment]
Thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @Sachin-Sangal, regarding your error please see: https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/#x509-certificate-signed-by-unknown-authority.

Since it's going to be a long duration since the last response I'm going to close this issue. If you have any further questions feel free to reopen the issue, thanks.
