### ISSUE TITLE
Docker driver results in duplicate CAdvisor entries

### ISSUE THREAD

**Issue by DieterDP-ng** [kubernetes/minikube#14915]
### What Happened?

I am not sure if this is a bug or undocumented feature/side-effect.

When running minikube with the Docker driver, CAdvisor will report memory metrics multiple times for a single pod, but with a different `id`.

For example:
```
# Extracted from http://localhost:8080/api/v1/nodes/minikube/proxy/metrics/cadvisor
# using "minikube start --vm-driver=docker --cni=calico --kubernetes-version=1.23.10" and "kubectl proxy --port=8080"
container_memory_working_set_bytes{container="",id="/kubepods/besteffort/pod12606883-05a6-4572-bb79-ffa847b300fb",image="",name="",namespace="kube-system",pod="calico-kube-controllers-8594699699-kqj79"} 2.5243648e+07 1662469140184
container_memory_working_set_bytes{container="POD",id="/docker/85b8af02515cb3e49ca58e7f9d5f59e038a1cb400bec20870842393ee6fe39c4/kubepods/besteffort/pod12606883-05a6-4572-bb79-ffa847b300fb/28369cae89b3fa80f9e06cabcaa96b678501d818df1007be653dc6664b3651d7",image="k8s.gcr.io/pause:3.6",name="k8s_POD_calico-kube-controllers-8594699699-kqj79_kube-system_12606883-05a6-4572-bb79-ffa847b300fb_51",namespace="kube-system",pod="calico-kube-controllers-8594699699-kqj79"} 348160 1662469139673
container_memory_working_set_bytes{container="POD",id="/kubepods/besteffort/pod12606883-05a6-4572-bb79-ffa847b300fb/28369cae89b3fa80f9e06cabcaa96b678501d818df1007be653dc6664b3651d7",image="k8s.gcr.io/pause:3.6",name="k8s_POD_calico-kube-controllers-8594699699-kqj79_kube-system_12606883-05a6-4572-bb79-ffa847b300fb_51",namespace="kube-system",pod="calico-kube-controllers-8594699699-kqj79"} 348160 1662469135889
container_memory_working_set_bytes{container="calico-kube-controllers",id="/docker/85b8af02515cb3e49ca58e7f9d5f59e038a1cb400bec20870842393ee6fe39c4/kubepods/besteffort/pod12606883-05a6-4572-bb79-ffa847b300fb/13286b5d114854d539b62bb987599ea853243cf000b34ffbe7a9d1b214ef0a81",image="sha256:76ba70f4748f962e448bad0123b1d716432dd380b5af6baef1b199d71b6860f5",name="k8s_calico-kube-controllers_calico-kube-controllers-8594699699-kqj79_kube-system_12606883-05a6-4572-bb79-ffa847b300fb_12",namespace="kube-system",pod="calico-kube-controllers-8594699699-kqj79"} 2.4793088e+07 1662469141976
container_memory_working_set_bytes{container="calico-kube-controllers",id="/kubepods/besteffort/pod12606883-05a6-4572-bb79-ffa847b300fb/13286b5d114854d539b62bb987599ea853243cf000b34ffbe7a9d1b214ef0a81",image="sha256:76ba70f4748f962e448bad0123b1d716432dd380b5af6baef1b199d71b6860f5",name="k8s_calico-kube-controllers_calico-kube-controllers-8594699699-kqj79_kube-system_12606883-05a6-4572-bb79-ffa847b300fb_12",namespace="kube-system",pod="calico-kube-controllers-8594699699-kqj79"} 2.480128e+07 1662469136194
```

You'll notice the second/third entry, and the fourth/fifth entry being almost identical in value, and only differing in their `id` label. 

These values seem to mirror the structure of the `/sys/fs/cgroup/memory/` folder in the minikube node (though the exact mapping is not clear to me), so CAdvisor is not wrong to report these. But I wonder if it is correct that there is both a `docker` and `kubepods` folder in `/sys/fs/cgroup/memory/`?

Knowing whether this is intended or not is relevant for reporting Grafana dashboards. While investigating this issue, I found out that Lens in fact [seems to report incorrect memory usage](https://github.com/lensapp/lens/issues/6179) due to this. (Note that `kubectl top pods` and the first confirm that the entries should not be combined.)

### Attach the log file

N/A

### Operating System

Ubuntu

### Driver

Docker

**Comment by DieterDP-ng** [comment]
As a side question, is there a definition on how the `id` field is used for different drivers? I believe for the KVM2 driver, the `id` is of the form `/kubepods.slice/...`. And what exactly is the meaning of `besteffort` and `burstable`?

**Comment by klaases** [comment]
Hi @DieterDP-ng  – apologies on being unable to address your questions directly, but there may be alternative ways to find the answers that you're looking for.

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support
