### ISSUE TITLE
docs: Mixed signals regarding `minikube dashboard`

### ISSUE THREAD

**Issue by adesso-os** [kubernetes/minikube#14912]
<https://minikube.sigs.k8s.io/docs/drivers/none/> first says:

> * Many `minikube` commands are not supported, such as: `dashboard`, `mount`, `ssh`

Then it says:

> * minikube with the `none` driver has a confusing permissions model, as some commands need to be run as root ("start"), and others by a regular user ("dashboard")

If `minikube dashboard` is not supported, why mention it in the next line?

**Comment by afbjorklund** [comment]
The documentation is outdated, the none driver does need to run as root anymore (it uses `sudo`)

Patches to docs welcome

**Comment by afbjorklund** [comment]
Instead of running the minikube program as root and reading config from /root, it runs as your regular user and then adds a "sudo" to the system commands that actually need it

**Comment by klaases** [comment]
Hi @adesso-os, did you want to create a PR to update the doc?

Else, I could create a PR if you don't mind, could you let me know the specific change you are seeking?

**Comment by adesso-os** [comment]
@klaases I sadly still haven't understood the difference. I left the issue open in case someone else can handle it. So, please do :)

To clarify, the quoted paragraphs seem to contain contradicting information. It first says the dashboard command is not supported, then it mentions the dashboard command needs to be run as a regular user. If it isn't obvious how that can be confusing, then I'd rather not invest any more time into this.

**Comment by medyagh** [comment]
@adesso-os I thin the difference @afbjorklund pointed out that minikbue no longer needs Root for none driver, but only sudo (still using same user but as super user)

**Comment by adesso-os** [comment]
@medyagh Yeah, but I wasn't able to project what that means onto the section of the documentation. If it's clear to you guys, please just make the change or close the ticket if it's invalid. I don't even use minikube.
