### ISSUE TITLE
Exiting due to HOST_BROWSER: exec: "cmd": executable file not found in %PATH%

### ISSUE THREAD

**Issue by srpeddolla** [kubernetes/minikube#14917]
### What Happened?

Exiting due to HOST_BROWSER: exec: "cmd": executable file not found in %PATH%

### Attach the log file

$ minikube service k8s-web-hello
🏃  Starting tunnel for service k8s-web-hello.
🎉  Opening service default/k8s-web-hello in default browser...

❌  Exiting due to HOST_BROWSER: exec: "cmd": executable file not found in %PATH%

╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                           
 │
│    😿  If the above advice does not help, please let us know:                                             
 │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                           
 │
│                                                                                                           
 │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                    
 │
│    Please also attach the following file to the GitHub issue:                                             
 │
│    - C:\Users\SHASHI\AppData\Local\Temp\minikube_service_6658521f771743b72061a3fc4f0151df68bcbe26_0.log   
 │
│                                                                                                           
 │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Windows

### Driver

Docker

**Comment by srpeddolla** [comment]
Log file created at: 2022/09/07 14:46:34
Running on machine: DESKTOP-L1VN0AU
Binary: Built with gc go1.17.7 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0907 14:46:34.198106   29112 out.go:297] Setting OutFile to fd 452 ...
I0907 14:46:34.199148   29112 out.go:349] isatty.IsTerminal(452) = true
I0907 14:46:34.199148   29112 out.go:310] Setting ErrFile to fd 452...
I0907 14:46:34.199148   29112 out.go:349] isatty.IsTerminal(452) = true
I0907 14:46:34.216644   29112 mustload.go:65] Loading cluster: minikube
I0907 14:46:34.217683   29112 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0907 14:46:34.241538   29112 cli_runner.go:133] Run: docker container inspect minikube --format={{.State.Status}}
I0907 14:46:34.487254   29112 host.go:66] Checking if "minikube" exists ...
I0907 14:46:34.500244   29112 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0907 14:46:34.674370   29112 api_server.go:165] Checking apiserver status ...
I0907 14:46:34.702357   29112 ssh_runner.go:195] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0907 14:46:34.715788   29112 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0907 14:46:34.903988   29112 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:51223 SSHKeyPath:C:\Users\SHASHI\.minikube\machines\minikube\id_rsa Username:docker}
I0907 14:46:35.252353   29112 ssh_runner.go:195] Run: sudo egrep ^[0-9]+:freezer: /proc/1719/cgroup
I0907 14:46:35.275424   29112 api_server.go:181] apiserver freezer: "7:freezer:/docker/a181ebfeba19bef45e6d07c0b8d7d05d034f8423aa6465c943d0c1fa47cd4ba2/kubepods/burstable/podcd6e47233d36a9715b0ab9632f871843/9fe3f9e7d878bf8fe4f196e7d1b0cd8a71405e9edf797e3aef45a51e8800e2f5"
I0907 14:46:35.298826   29112 ssh_runner.go:195] Run: sudo cat /sys/fs/cgroup/freezer/docker/a181ebfeba19bef45e6d07c0b8d7d05d034f8423aa6465c943d0c1fa47cd4ba2/kubepods/burstable/podcd6e47233d36a9715b0ab9632f871843/9fe3f9e7d878bf8fe4f196e7d1b0cd8a71405e9edf797e3aef45a51e8800e2f5/freezer.state
I0907 14:46:35.312846   29112 api_server.go:203] freezer state: "THAWED"
I0907 14:46:35.313376   29112 api_server.go:240] Checking apiserver healthz at https://127.0.0.1:51227/healthz ...
I0907 14:46:35.342285   29112 api_server.go:266] https://127.0.0.1:51227/healthz returned 200:
ok
I0907 14:46:35.342285   29112 host.go:66] Checking if "minikube" exists ...
I0907 14:46:35.366207   29112 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0907 14:46:35.695680   29112 service.go:214] Found service: &Service{ObjectMeta:{k8s-web-hello  default  c5a82cbf-2508-4611-ad27-5b1c88e024c4 18786 0 2022-09-07 14:33:11 +0530 IST <nil> <nil> map[app:k8s-web-hello] map[] [] []  [{kubectl-expose Update v1 2022-09-07 14:33:11 +0530 IST FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":3000,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:3000,TargetPort:{0 3000 },NodePort:32124,AppProtocol:nil,},},Selector:map[string]string{app: k8s-web-hello,},ClusterIP:10.105.70.125,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.105.70.125],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0907 14:46:35.714874   29112 service.go:214] Found service: &Service{ObjectMeta:{k8s-web-hello  default  c5a82cbf-2508-4611-ad27-5b1c88e024c4 18786 0 2022-09-07 14:33:11 +0530 IST <nil> <nil> map[app:k8s-web-hello] map[] [] []  [{kubectl-expose Update v1 2022-09-07 14:33:11 +0530 IST FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":3000,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:3000,TargetPort:{0 3000 },NodePort:32124,AppProtocol:nil,},},Selector:map[string]string{app: k8s-web-hello,},ClusterIP:10.105.70.125,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.105.70.125],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0907 14:46:35.715414   29112 host.go:66] Checking if "minikube" exists ...
I0907 14:46:35.741701   29112 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0907 14:46:35.974003   29112 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0907 14:46:36.173761   29112 out.go:176] 🏃  Starting tunnel for service k8s-web-hello.
I0907 14:46:37.174539   29112 out.go:176] 🎉  Opening service default/k8s-web-hello in default browser...
I0907 14:46:37.196719   29112 out.go:176] 
W0907 14:46:37.196719   29112 out.go:241] ❌  Exiting due to HOST_BROWSER: exec: "cmd": executable file not found in %PATH%
W0907 14:46:37.196719   29112 out.go:241] 
W0907 14:46:37.205709   29112 out.go:241] [31m╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                            [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                                              [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                            [31m│[0m
[31m│[0m                                                                                                            [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                     [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                                              [31m│[0m
[31m│[0m    - C:\Users\SHASHI\AppData\Local\Temp\minikube_service_6658521f771743b72061a3fc4f0151df68bcbe26_0.log    [31m│[0m
[31m│[0m                                                                                                            [31m│[0m
[31m╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
Log file created at: 2022/09/07 15:05:30
Running on machine: DESKTOP-L1VN0AU
Binary: Built with gc go1.17.7 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0907 15:05:30.913923   12512 out.go:297] Setting OutFile to fd 452 ...
I0907 15:05:30.918612   12512 out.go:349] isatty.IsTerminal(452) = true
I0907 15:05:30.918612   12512 out.go:310] Setting ErrFile to fd 452...
I0907 15:05:30.918612   12512 out.go:349] isatty.IsTerminal(452) = true
I0907 15:05:30.937080   12512 mustload.go:65] Loading cluster: minikube
I0907 15:05:30.937587   12512 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0907 15:05:30.962954   12512 cli_runner.go:133] Run: docker container inspect minikube --format={{.State.Status}}
I0907 15:05:31.139373   12512 host.go:66] Checking if "minikube" exists ...
I0907 15:05:31.153568   12512 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0907 15:05:31.339440   12512 api_server.go:165] Checking apiserver status ...
I0907 15:05:31.363606   12512 ssh_runner.go:195] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0907 15:05:31.377048   12512 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0907 15:05:31.585830   12512 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:51223 SSHKeyPath:C:\Users\SHASHI\.minikube\machines\minikube\id_rsa Username:docker}
I0907 15:05:31.986197   12512 ssh_runner.go:195] Run: sudo egrep ^[0-9]+:freezer: /proc/1719/cgroup
I0907 15:05:32.008444   12512 api_server.go:181] apiserver freezer: "7:freezer:/docker/a181ebfeba19bef45e6d07c0b8d7d05d034f8423aa6465c943d0c1fa47cd4ba2/kubepods/burstable/podcd6e47233d36a9715b0ab9632f871843/9fe3f9e7d878bf8fe4f196e7d1b0cd8a71405e9edf797e3aef45a51e8800e2f5"
I0907 15:05:32.034036   12512 ssh_runner.go:195] Run: sudo cat /sys/fs/cgroup/freezer/docker/a181ebfeba19bef45e6d07c0b8d7d05d034f8423aa6465c943d0c1fa47cd4ba2/kubepods/burstable/podcd6e47233d36a9715b0ab9632f871843/9fe3f9e7d878bf8fe4f196e7d1b0cd8a71405e9edf797e3aef45a51e8800e2f5/freezer.state
I0907 15:05:32.048117   12512 api_server.go:203] freezer state: "THAWED"
I0907 15:05:32.048117   12512 api_server.go:240] Checking apiserver healthz at https://127.0.0.1:51227/healthz ...
I0907 15:05:32.059525   12512 api_server.go:266] https://127.0.0.1:51227/healthz returned 200:
ok
I0907 15:05:32.059525   12512 host.go:66] Checking if "minikube" exists ...
I0907 15:05:32.077470   12512 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0907 15:05:32.416569   12512 service.go:214] Found service: &Service{ObjectMeta:{k8s-web-hello  default  c5a82cbf-2508-4611-ad27-5b1c88e024c4 18786 0 2022-09-07 14:33:11 +0530 IST <nil> <nil> map[app:k8s-web-hello] map[] [] []  [{kubectl-expose Update v1 2022-09-07 14:33:11 +0530 IST FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":3000,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:3000,TargetPort:{0 3000 },NodePort:32124,AppProtocol:nil,},},Selector:map[string]string{app: k8s-web-hello,},ClusterIP:10.105.70.125,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.105.70.125],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0907 15:05:32.426596   12512 service.go:214] Found service: &Service{ObjectMeta:{k8s-web-hello  default  c5a82cbf-2508-4611-ad27-5b1c88e024c4 18786 0 2022-09-07 14:33:11 +0530 IST <nil> <nil> map[app:k8s-web-hello] map[] [] []  [{kubectl-expose Update v1 2022-09-07 14:33:11 +0530 IST FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":3000,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:3000,TargetPort:{0 3000 },NodePort:32124,AppProtocol:nil,},},Selector:map[string]string{app: k8s-web-hello,},ClusterIP:10.105.70.125,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.105.70.125],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0907 15:05:32.427129   12512 host.go:66] Checking if "minikube" exists ...
I0907 15:05:32.450634   12512 cli_runner.go:133] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0907 15:05:32.721871   12512 cli_runner.go:133] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0907 15:05:32.951677   12512 out.go:176] 🏃  Starting tunnel for service k8s-web-hello.
I0907 15:05:33.960234   12512 out.go:176] 🎉  Opening service default/k8s-web-hello in default browser...
I0907 15:05:33.998886   12512 out.go:176] 
W0907 15:05:33.999419   12512 out.go:241] ❌  Exiting due to HOST_BROWSER: exec: "cmd": executable file not found in %PATH%
W0907 15:05:33.999419   12512 out.go:241] 
W0907 15:05:34.010076   12512 out.go:241] [31m╭────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                            [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                                              [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                            [31m│[0m
[31m│[0m                                                                                                            [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                     [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                                              [31m│[0m
[31m│[0m    - C:\Users\SHASHI\AppData\Local\Temp\minikube_service_6658521f771743b72061a3fc4f0151df68bcbe26_0.log    [31m│[0m
[31m│[0m                                                                                                            [31m│[0m
[31m╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m

**Comment by klaases** [comment]
Hi @srpeddolla  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @srpeddolla, what terminal are you using? Are you able to type `cmd` into the terminal yourself?

**Comment by spowelljr** [comment]
Hi @srpeddolla, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
