### ISSUE TITLE
Ingress not working

### ISSUE THREAD

**Issue by dilipfci** [kubernetes/minikube#14913]
### What Happened?

Ingress not working when I run minikube with hyper-v driver

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9495149/logs.txt)
[minikube_addons_adee472434ed849dada132520141af09a4763611_0.log](https://github.com/kubernetes/minikube/files/9495150/minikube_addons_adee472434ed849dada132520141af09a4763611_0.log)

### Operating System

Windows

### Driver

Hyper-V

**Comment by klaases** [comment]
Hi @dilipfci  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @dilipfci, can you run `kubectl get pods -A` you should see an ingress pod, then run `kubectl logs <ingress_pod_name>` and upload the logs.
