### ISSUE TITLE
minikube - access denied

### ISSUE THREAD

**Issue by ishav92** [kubernetes/minikube#14914]
### What Happened?

! StartHost failed, but will try again: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied * Failed to start none bare metal machine. Running "minikube delete" may fix it: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied  X Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed to start host: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied * Suggestion: Run 'sudo sysctl fs.protected_regular=0', or try a driver which does not require root, such as '--driver=docker' * Related issue: https://github.com/kubernetes/minikube/issues/6391  root@ip-172-31-90-231:/home/ubuntu/cri-dockerd# ^C root@ip-172-31-90-231:/home/ubuntu/cri-dockerd# sudo sysctl fs.protected_regular=0 fs.protected_regular = 0 root@ip-172-31-90-231:/home/ubuntu/cri-dockerd# kubectl get nodes The connection to the server 172.31.90.231:8443 was refused - did you specify the right host or port? root@ip-172-31-90-231:/home/ubuntu/cri-dockerd# minikube start --vm-driver=none^C root@ip-172-31-90-231:/home

### Attach the log file

! StartHost failed, but will try again: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied * Failed to start none bare metal machine. Running "minikube delete" may fix it: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied  X Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed to start host: boot lock: unable to open /tmp/juju-mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89: permission denied * Suggestion: Run 'sudo sysctl fs.protected_regular=0', or try a driver which does not require root, such as '--driver=docker' * Related issue: https://github.com/kubernetes/minikube/issues/6391  root@ip-172-31-90-231:/home/ubuntu/cri-dockerd# ^C root@ip-172-31-90-231:/home/ubuntu/cri-dockerd# sudo sysctl fs.protected_regular=0 fs.protected_regular = 0 root@ip-172-31-90-231:/home/ubuntu/cri-dockerd# kubectl get nodes The connection to the server 172.31.90.231:8443 was refused - did you specify the right host or port? root@ip-172-31-90-231:/home/ubuntu/cri-dockerd# minikube start --vm-driver=none^C root@ip-172-31-90-231:/home

### Operating System

Ubuntu

**Comment by klaases** [comment]
Hi @ishav92  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @ishav92, did you try running `sudo sysctl fs.protected_regular=0`?
