### ISSUE TITLE
Minikube 19 does not start up on MacOS after upgrade

### ISSUE THREAD

**Issue by skate056** [kubernetes/minikube#1492]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS Sierra 10.12.4 (16E195)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): "Boot2DockerURL": "file:///Users/saket-bgch/.minikube/cache/iso/minikube-0.7.iso"

        $ minikube ssh cat /etc/VERSION
        cat: can't open '/etc/VERSION': No such file or directory
        E0515 11:30:34.271190    8804 ssh.go:44] Error attempting to ssh/run-ssh-command: exit status 1

- **Install tools**:
- **Others**:

**What happened**: Upgraded minikube to version 19 and minikube does not start up properly.

    $ minikube start
    Starting local Kubernetes v1.6.0 cluster...
    Starting VM...
    SSH-ing files into VM...
    Setting up certs...
    Starting cluster components...
    Connecting to cluster...
    Setting up kubeconfig...
    Kubectl is now configured to use the cluster.

minikube status results in:

    $ minikube status
    E0515 11:34:26.856060    8883 status.go:62] Error getting machine status: Error: Unrecognize output from GetLocalkubeStatus: sudo: systemctl: command not found
    Stopped
    E0515 11:34:26.857572    8883 util.go:142] Error formatting error message: Error msg with no stack trace cannot be reported

kubectl commands result in 

     $ kubectl get po
     The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

```
$ minikube logs
2017/05/15 11:41:53 Error getting machine logs: ssh command error:
command : sudo journalctl  -u localkube
err     : exit status 1
output  : sudo: journalctl: command not found

E0515 11:41:53.726972    8975 util.go:142] Error formatting error message: Error msg with no stack trace cannot be reported
```

**Comment by joscas** [comment]
+1

**Comment by aaron-prindle** [comment]
It seems that you are using an old version of the minikube-iso: `minikube-0.7.iso`.  Currently the iso is at `minikube-v0.18.0.iso`.  There is some incompatibility between iso and binary versions.  Can you try deleting you running minikube instance w/ `minikube delete` and then restarting minikube w/ `minikube start`.  This should pickup the newest iso.

**Comment by aaron-prindle** [comment]
We should have better error information if an old minikube iso that doesn't have systemd is used with a new binary version

**Comment by skate056** [comment]
Yes, `minikube delete` and `minikube start` fixes the issue. Agree, a helpful error message will be useful.

**Comment by r2d4** [comment]
Closing.  Upgrading from 0.18 -> 0.21.0 should work fine now.
