### ISSUE TITLE
Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition

### ISSUE THREAD

**Issue by kzaghloul1980** [kubernetes/minikube#14939]
### What Happened?

I cannot install Minikube

[logs.txt](https://github.com/kubernetes/minikube/files/9547915/logs.txt)

### Attach the log file

kz@kz-ubuntu:~$ minikube start --driver=docker
😄  minikube v1.26.1 on Ubuntu 22.04
✨  Using the docker driver based on user configuration
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.24.3 preload ...
    > preloaded-images-k8s-v18-v1...:  405.75 MiB / 405.75 MiB  100.00% 11.26 M
    > gcr.io/k8s-minikube/kicbase:  386.60 MiB / 386.61 MiB  100.00% 7.92 MiB p
    > gcr.io/k8s-minikube/kicbase:  0 B [________________________] ?% ? p/s 33s
🔥  Creating docker container (CPUs=2, Memory=3638MB) ...
🐳  Preparing Kubernetes v1.24.3 on Docker 20.10.17 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...\ E0912 13:12:14.468320  357990 start.go:267] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://x.x.x.x:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp x.x.x.x:8443: i/o timeout]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/14202

**Comment by paranjay-patel** [comment]
same issue here, do you able to find any solution??

**Comment by klaases** [comment]
Hi @paranjay-patel, please see the related issue https://github.com/kubernetes/minikube/issues/14202 for the latest updates.
