### ISSUE TITLE
minikube cluster issue

### ISSUE THREAD

**Issue by jit19** [kubernetes/minikube#14930]
### What Happened?

* |---------|---------------|----------|------|---------|---------------------|----------|
| Command |     Args      | Profile  | User | Version |     Start Time      | End Time |
|---------|---------------|----------|------|---------|---------------------|----------|
| start   | --driver=none | minikube | root | v1.26.1 | 08 Sep 22 17:49 UTC |          |
| start   |               | minikube | root | v1.26.1 | 08 Sep 22 17:50 UTC |          |
| start   | --driver=none | minikube | root | v1.26.1 | 08 Sep 22 17:53 UTC |          |
| start   | --driver=none | minikube | root | v1.26.1 | 08 Sep 22 18:01 UTC |          |
| start   | --driver=none | minikube | root | v1.26.1 | 08 Sep 22 18:01 UTC |          |
|---------|---------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/09/08 18:01:45
Running on machine: ip-172-31-86-91
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0908 18:01:45.497809   19566 out.go:296] Setting OutFile to fd 1 ...
I0908 18:01:45.497926   19566 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0908 18:01:45.497932   19566 out.go:309] Setting ErrFile to fd 2...
I0908 18:01:45.497938   19566 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0908 18:01:45.498070   19566 root.go:333] Updating PATH: /root/.minikube/bin
W0908 18:01:45.498188   19566 root.go:310] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0908 18:01:45.498386   19566 out.go:303] Setting JSON to false
I0908 18:01:45.499087   19566 start.go:115] hostinfo: {"hostname":"ip-172-31-86-91.ec2.internal","uptime":1911,"bootTime":1662658195,"procs":112,"os":"linux","platform":"amazon","platformFamily":"rhel","platformVersion":"2","kernelVersion":"5.10.130-118.517.amzn2.x86_64","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec2552ca-7bb6-33ef-feaa-af0d2a2fef94"}
I0908 18:01:45.499149   19566 start.go:125] virtualization: xen guest
I0908 18:01:45.501018   19566 out.go:177] * minikube v1.26.1 on Amazon 2 (xen/amd64)
W0908 18:01:45.502309   19566 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0908 18:01:45.502512   19566 notify.go:193] Checking for updates...
I0908 18:01:45.502682   19566 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.3
I0908 18:01:45.502984   19566 exec_runner.go:51] Run: systemctl --version
I0908 18:01:45.504782   19566 driver.go:365] Setting default libvirt URI to qemu:///system
I0908 18:01:45.506182   19566 out.go:177] * Using the none driver based on existing profile
I0908 18:01:45.514052   19566 start.go:284] selected driver: none
I0908 18:01:45.514063   19566 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.86.91 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0908 18:01:45.514177   19566 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0908 18:01:45.514604   19566 cni.go:95] Creating CNI manager for ""
I0908 18:01:45.514611   19566 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0908 18:01:45.514627   19566 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.86.91 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0908 18:01:45.516135   19566 out.go:177] * Starting control plane node minikube in cluster minikube
I0908 18:01:45.517449   19566 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0908 18:01:45.517633   19566 cache.go:208] Successfully downloaded all kic artifacts
I0908 18:01:45.517660   19566 start.go:371] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0908 18:01:45.517870   19566 start.go:375] acquired machines lock for "minikube" in 191.63µs
I0908 18:01:45.517887   19566 start.go:95] Skipping create...Using existing machine configuration
I0908 18:01:45.517894   19566 fix.go:55] fixHost starting: m01
W0908 18:01:45.518132   19566 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0908 18:01:45.518141   19566 api_server.go:165] Checking apiserver status ...
I0908 18:01:45.518164   19566 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0908 18:01:45.538504   19566 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0908 18:01:45.538554   19566 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0908 18:01:45.551240   19566 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0908 18:01:45.551257   19566 fix.go:129] unexpected machine state, will restart: <nil>
I0908 18:01:45.553245   19566 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I0908 18:01:45.555712   19566 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0908 18:01:45.555814   19566 start.go:307] post-start starting for "minikube" (driver="none")
I0908 18:01:45.555848   19566 start.go:335] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0908 18:01:45.555884   19566 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0908 18:01:45.566283   19566 main.go:134] libmachine: Couldn't set key CPE_NAME, no corresponding struct field found
I0908 18:01:45.568748   19566 out.go:177] * OS release is Amazon Linux 2
I0908 18:01:45.569738   19566 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0908 18:01:45.569773   19566 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0908 18:01:45.569790   19566 start.go:310] post-start completed in 13.96694ms
I0908 18:01:45.569798   19566 fix.go:57] fixHost completed within 51.90445ms
I0908 18:01:45.569803   19566 start.go:82] releasing machines lock for "minikube", held for 51.924839ms
I0908 18:01:45.570297   19566 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0908 18:01:45.570306   19566 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0908 18:01:45.598535   19566 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0908 18:01:45.688315   19566 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0908 18:01:45.789098   19566 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0908 18:01:45.863279   19566 exec_runner.go:51] Run: sudo systemctl restart docker
I0908 18:01:46.124315   19566 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0908 18:01:46.216490   19566 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0908 18:01:46.304012   19566 exec_runner.go:51] Run: sudo systemctl start cri-docker.socket
I0908 18:01:46.320864   19566 start.go:450] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0908 18:01:46.320913   19566 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0908 18:01:46.322282   19566 start.go:471] Will wait 60s for crictl version
I0908 18:01:46.322321   19566 exec_runner.go:51] Run: sudo crictl version
I0908 18:01:46.329072   19566 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0908 18:01:57.375921   19566 exec_runner.go:51] Run: sudo crictl version
I0908 18:01:57.382907   19566 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

### Attach the log file

* |---------|---------------|----------|------|---------|---------------------|----------|
| Command |     Args      | Profile  | User | Version |     Start Time      | End Time |
|---------|---------------|----------|------|---------|---------------------|----------|
| start   | --driver=none | minikube | root | v1.26.1 | 08 Sep 22 17:49 UTC |          |
| start   |               | minikube | root | v1.26.1 | 08 Sep 22 17:50 UTC |          |
| start   | --driver=none | minikube | root | v1.26.1 | 08 Sep 22 17:53 UTC |          |
| start   | --driver=none | minikube | root | v1.26.1 | 08 Sep 22 18:01 UTC |          |
| start   | --driver=none | minikube | root | v1.26.1 | 08 Sep 22 18:01 UTC |          |
|---------|---------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/09/08 18:01:45
Running on machine: ip-172-31-86-91
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0908 18:01:45.497809   19566 out.go:296] Setting OutFile to fd 1 ...
I0908 18:01:45.497926   19566 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0908 18:01:45.497932   19566 out.go:309] Setting ErrFile to fd 2...
I0908 18:01:45.497938   19566 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0908 18:01:45.498070   19566 root.go:333] Updating PATH: /root/.minikube/bin
W0908 18:01:45.498188   19566 root.go:310] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0908 18:01:45.498386   19566 out.go:303] Setting JSON to false
I0908 18:01:45.499087   19566 start.go:115] hostinfo: {"hostname":"ip-172-31-86-91.ec2.internal","uptime":1911,"bootTime":1662658195,"procs":112,"os":"linux","platform":"amazon","platformFamily":"rhel","platformVersion":"2","kernelVersion":"5.10.130-118.517.amzn2.x86_64","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec2552ca-7bb6-33ef-feaa-af0d2a2fef94"}
I0908 18:01:45.499149   19566 start.go:125] virtualization: xen guest
I0908 18:01:45.501018   19566 out.go:177] * minikube v1.26.1 on Amazon 2 (xen/amd64)
W0908 18:01:45.502309   19566 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0908 18:01:45.502512   19566 notify.go:193] Checking for updates...
I0908 18:01:45.502682   19566 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.3
I0908 18:01:45.502984   19566 exec_runner.go:51] Run: systemctl --version
I0908 18:01:45.504782   19566 driver.go:365] Setting default libvirt URI to qemu:///system
I0908 18:01:45.506182   19566 out.go:177] * Using the none driver based on existing profile
I0908 18:01:45.514052   19566 start.go:284] selected driver: none
I0908 18:01:45.514063   19566 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.86.91 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0908 18:01:45.514177   19566 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0908 18:01:45.514604   19566 cni.go:95] Creating CNI manager for ""
I0908 18:01:45.514611   19566 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0908 18:01:45.514627   19566 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.33@sha256:73b259e144d926189cf169ae5b46bbec4e08e4e2f2bd87296054c3244f70feb8 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.86.91 Port:8443 KubernetesVersion:v1.24.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0908 18:01:45.516135   19566 out.go:177] * Starting control plane node minikube in cluster minikube
I0908 18:01:45.517449   19566 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0908 18:01:45.517633   19566 cache.go:208] Successfully downloaded all kic artifacts
I0908 18:01:45.517660   19566 start.go:371] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0908 18:01:45.517870   19566 start.go:375] acquired machines lock for "minikube" in 191.63µs
I0908 18:01:45.517887   19566 start.go:95] Skipping create...Using existing machine configuration
I0908 18:01:45.517894   19566 fix.go:55] fixHost starting: m01
W0908 18:01:45.518132   19566 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0908 18:01:45.518141   19566 api_server.go:165] Checking apiserver status ...
I0908 18:01:45.518164   19566 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0908 18:01:45.538504   19566 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0908 18:01:45.538554   19566 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0908 18:01:45.551240   19566 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0908 18:01:45.551257   19566 fix.go:129] unexpected machine state, will restart: <nil>
I0908 18:01:45.553245   19566 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I0908 18:01:45.555712   19566 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0908 18:01:45.555814   19566 start.go:307] post-start starting for "minikube" (driver="none")
I0908 18:01:45.555848   19566 start.go:335] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0908 18:01:45.555884   19566 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0908 18:01:45.566283   19566 main.go:134] libmachine: Couldn't set key CPE_NAME, no corresponding struct field found
I0908 18:01:45.568748   19566 out.go:177] * OS release is Amazon Linux 2
I0908 18:01:45.569738   19566 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0908 18:01:45.569773   19566 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0908 18:01:45.569790   19566 start.go:310] post-start completed in 13.96694ms
I0908 18:01:45.569798   19566 fix.go:57] fixHost completed within 51.90445ms
I0908 18:01:45.569803   19566 start.go:82] releasing machines lock for "minikube", held for 51.924839ms
I0908 18:01:45.570297   19566 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0908 18:01:45.570306   19566 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0908 18:01:45.598535   19566 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0908 18:01:45.688315   19566 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0908 18:01:45.789098   19566 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0908 18:01:45.863279   19566 exec_runner.go:51] Run: sudo systemctl restart docker
I0908 18:01:46.124315   19566 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0908 18:01:46.216490   19566 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0908 18:01:46.304012   19566 exec_runner.go:51] Run: sudo systemctl start cri-docker.socket
I0908 18:01:46.320864   19566 start.go:450] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0908 18:01:46.320913   19566 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0908 18:01:46.322282   19566 start.go:471] Will wait 60s for crictl version
I0908 18:01:46.322321   19566 exec_runner.go:51] Run: sudo crictl version
I0908 18:01:46.329072   19566 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I0908 18:01:57.375921   19566 exec_runner.go:51] Run: sudo crictl version
I0908 18:01:57.382907   19566 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by afbjorklund** [comment]
You need to install `crictl`, it's a new requirement (for docker) since k8s 1.24

https://minikube.sigs.k8s.io/docs/drivers/none/

**Comment by jit19** [comment]
Thanks alot for yr replay

**Comment by klaases** [comment]
Hi @jit19  – thanks for following up and letting us know that installing `crictl` was of help.

Closing out for now, if needed, please feel free to re-open the issue by commenting with `/reopen`.

Thank you for sharing your experience!

**Comment by jit19** [comment]
Thank you!
