### ISSUE TITLE
Using minikube as Docker Desktop Replacement  

### ISSUE THREAD

**Issue by StingyJack** [kubernetes/minikube#14946]
https://minikube.sigs.k8s.io/docs/tutorials/docker_desktop_replacement/

The powershell and CMD examples for step 3 require that a profile be specified. Users coming to this kind of document will probably not know what the profile name is, and the error messages are less than helpful  (using `default` returns `false: The term 'false' is not recognized as a name of a cmdlet, function, script file, or executable program` for powershell for example). 

A note on here stating that the default profile name is `minikube` would have saved a bit of time

**Comment by klaases** [comment]
Sure, I'd be happy to create a PR for this, accepted.
