### ISSUE TITLE
Scheduling POD With gVisor - Permission Denied

### ISSUE THREAD

**Issue by danilo-lopes** [kubernetes/minikube#14958]
### What Happened?

Start minkube as mentioned here:

https://github.com/kubernetes/minikube/blob/master/deploy/addons/gvisor/README.md

* ContainerD
* gVisor

Scheduling POD before deploying gVisor:

```
(Python3.8.13)  dansolo@gondor  ~/Downloads  k run nginx-before-gvisor --image nginx
(Python3.8.13)  dansolo@gondor  ~/Downloads  k get pods
NAME                  READY   STATUS    RESTARTS   AGE
nginx-before-gvisor   1/1     Running   0          5m20s
(Python3.8.13)  dansolo@gondor  ~/Downloads 
```

Scheduling POD after deploying gVisor:

```
(Python3.8.13)  dansolo@gondor  ~/Downloads  k run nginx-before-gvisor-2 --image nginx
(Python3.8.13)  dansolo@gondor  ~/Downloads  k get pods
NAME                    READY   STATUS              RESTARTS   AGE
nginx-before-gvisor     1/1     Running             0          7m20s
nginx-before-gvisor-2   0/1     ContainerCreating   0          56s
(Python3.8.13)  dansolo@gondor  ~/Downloads 
```

```
Warning  FailedCreatePodSandBox  19s   kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "7a777f09ef43335f65f3a994d1c6e50ff09c19ae0bdd500059f980f083c77237": plugin type="bridge" name="crio" failed (add): failed to set bridge addr: could not add IP address to "cni0": permission denied
```
The same happens with `runtimeClassName: gvisor`.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9578121/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by klaases** [comment]
Hi @danilo-lopes  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support

**Comment by spowelljr** [comment]
Hi @danilo-lopes, I believe this matches https://github.com/google/gvisor/issues/7877
