### ISSUE TITLE
minikube logs --file=logs.txt

### ISSUE THREAD

**Issue by souravsk** [kubernetes/minikube#14952]
### What Happened?

Unable to start the minikube don't know what happened. It was working fine yesterday but now it's not working. I don't understand please help me.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9570089/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
`KUBECONFIG=/path/to/kubeconfig/file`

If you want to override the default location, you need to use a file that actually exists (and not the placeholder text)

**Comment by souravsk** [comment]
environment location is automatically get changed to that location. 
I set the `export=KUBECONFI=&HOME/.kube/config` and then run it the minikube get started but after that again the location get changed to that.
