### ISSUE TITLE
Minikube kubectl autocompletion not working

### ISSUE THREAD

**Issue by itay-grudev** [kubernetes/minikube#14959]
### What Happened?

As the documentation specified I tried using the `kubectl` provided in the project using:

```bash
sudo ln -s $(which minikube) /usr/local/bin/kubectl
```

I am on Ubuntu 22.04 and I tried both `bash` and `zsh`. In both cases the autocompletion doesn't work. I tried multiple things, sourcing the auto completion manually and putting them in the configuration file for each respective shell:

```bash
source <(kubectl completion zsh)
source <(kubectl completion bash)
```

I tried using the `oh-my-zsh` plugin. Nothing - it just doesn't work.

After installing a dedicated kubectl package via `snapd` everything works fine. There is just something wrong with the minikube setup.

### Attach the log file

Not applicable.

### Operating System

Ubuntu

### Driver

Docker

**Comment by hypeitnow** [comment]
I can confirm

**Comment by fede843** [comment]
same here

**Comment by moto-ctrl** [comment]
I have just spent half day trying to make it to work and failed. I'm on Debian 11 Bullseye with bash.
minikube completion works perfectly fine, built-in kubectl I cannot configure to do completion. tried both with link and with alias, user command, bashrc and system-wide file drop.

**Comment by moto-ctrl** [comment]
It appears to have been reported before but never fixed
https://github.com/kubernetes/minikube/issues/12938

**Comment by ben-krieger** [comment]
Using `export BASH_COMP_DEBUG_FILE=$HOME/kubectl.completion` and then attempting to complete `kubectl ge`, I see these logs:

```
========= starting completion logic ==========
cur is ge, words[*] is kubectl ge, #words[@] is 2, cword is 1
Truncated words[*]: kubectl ge,
lastParam ge, lastChar e
Calling kubectl __complete ge
The completion directive is: 0
The completions are: 
__kubectl_handle_completion_types: COMP_TYPE is 9
```

You can see that it's evaluating `kubectl __complete ge` in a subshell. Trying this myself, I get an error:

```bash
$ kubectl __complete ge; echo $?
Error: flags cannot be placed before plugin name: --cluster
1
```

So it appears that since minikube is always adding some flags, the completion script (`minikube kubectl completion bash`) now cannot be used with `minikube kubectl` either linked or aliased.

**Comment by ben-krieger** [comment]
It seems like a pretty simple fix:

```diff
diff --git a/cmd/minikube/cmd/kubectl.go b/cmd/minikube/cmd/kubectl.go
index ace509340..26825b1c3 100644
--- a/cmd/minikube/cmd/kubectl.go
+++ b/cmd/minikube/cmd/kubectl.go
@@ -96,7 +96,7 @@ host. Please be aware that when using --ssh all paths will apply to the remote m
                        os.Exit(1)
                }
 
-               if len(args) > 1 && args[0] != "--help" {
+               if len(args) > 1 && args[0] != "--help" && args[0] != "__complete" {
                        cluster := []string{"--cluster", cname}
                        args = append(cluster, args...)
```

I'll submit a PR.

**Comment by moto-ctrl** [comment]
great job @ben-krieger - I can see you got your PR merged! Thank you, looking forward to the new release to test it!
