### ISSUE TITLE
localkube silently panics when using TPRs

### ISSUE THREAD

**Issue by kyessenov** [kubernetes/minikube#1496]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`):
 v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release):] mac
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.18.0
- **Install tools**:
- **Others**:

**What happened**:

`minikube start` succeeds but cluster is not reachable with `kubectl`.
Poking into the logs I see this:
```
May 15 19:54:04 minikube localkube[4393]: W0515 19:54:04.328722    4393 registered.go:288] Could not find groupMeta for istio.io
May 15 19:54:04 minikube localkube[4393]: panic: runtime error: invalid memory address or nil pointer dereference
May 15 19:54:04 minikube localkube[4393]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0x179e3b2]
May 15 19:54:04 minikube localkube[4393]: goroutine 1906 [running]:
May 15 19:54:04 minikube localkube[4393]: panic(0x37d74c0, 0xc420016030)
May 15 19:54:04 minikube localkube[4393]:         /usr/local/go/src/runtime/panic.go:500 +0x1a1
May 15 19:54:04 minikube localkube[4393]: k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/apimachinery/registered.(*APIRegistrationManager).RESTMapper(0xc42000c960, 0x0, 0x0, 0x0, 0x20, 0x1100000009)
May 15 19:54:04 minikube localkube[4393]:         /go/src/k8s.io/minikube/vendor/k8s.io/apimachinery/pkg/apimachinery/registered/registered.go:290 +0x2a2
May 15 19:54:04 minikube localkube[4393]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.startNamespaceController(0x68dfca0, 0xc421c54540, 0x68eacc0, 0xc42364f3b0, 0x0, 0x0, 0x0, 0x0, 0xc420410590, 0x1, ...)
May 15 19:54:04 minikube localkube[4393]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/core.go:103 +0x5d
May 15 19:54:04 minikube localkube[4393]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.StartControllers(0xc42364e6c0, 0xc420cc18c0, 0x68dfca0, 0xc421c54540, 0x68dfca0, 0xc421c54540, 0xc423cfd7a0, 0x0, 0x0)
May 15 19:54:04 minikube localkube[4393]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:428 +0x5b3
May 15 19:54:04 minikube localkube[4393]: k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app.Run.func2(0xc423cfd7a0)
May 15 19:54:04 minikube localkube[4393]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/cmd/kube-controller-manager/app/controllermanager.go:180 +0xc6
May 15 19:54:04 minikube localkube[4393]: created by k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection.(*LeaderElector).Run
May 15 19:54:04 minikube localkube[4393]:         /go/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/client/leaderelection/leaderelection.go:150 +0x97
May 15 19:54:04 minikube systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 15 19:54:04 minikube systemd[1]: localkube.service: Unit entered failed state.
May 15 19:54:04 minikube systemd[1]: localkube.service: Failed with result 'exit-code'.
```

**What you expected to happen**:

Cluster is operational. The first time I start the cluster things work as expected. But if I stop and start again, the cluster  no longer works.

**How to reproduce it** (as minimally and precisely as possible):

I'm using TPRs. The cluster needs to be restarted for the error to occur.

**Anything else do we need to know**:

**Comment by r2d4** [comment]
This was my fault.  A copy-paste error 

The patch we're applying
https://github.com/kubernetes/minikube/blob/261c77bc4f4c1f03afc51ae89b7586e484781737/hack/tpr-patch.diff

My original PR upstream (catches the error but doesn't skip with continue)
https://github.com/kubernetes/kubernetes/pull/44771/files

I can patch the 1.6.3 version of localkube, so that it will work with `--kubernetes-version v1.6.3`.  We could also do a release with that as the default version @dlorenc @aaron-prindle

**Comment by r2d4** [comment]
I'm going to keep this open until we release a 0.19.1

**Comment by amitsaha** [comment]
@r2d4 does this mean that if I build from master, I shouldn't see the issue?

**Comment by r2d4** [comment]
Yes @amitsaha, the final fix was https://github.com/kubernetes/minikube/pull/1497 and we will be doing a 0.19.1 release soon

**Comment by amitsaha** [comment]
Thanks. I did try the same, but still had the same issue. I posted on the mailing list: https://groups.google.com/forum/#!topic/kubernetes-dev/CayRgR7kDng

**Comment by r2d4** [comment]
This should be fixed in 0.19.1

**Comment by kufi** [comment]
@r2d4 Could it be that there was a regression in the latest v0.23.0? It at least seems to happen for me in my minikube.

If I look at the file in the v0.23.0 release the corresponding code is gone: https://github.com/kubernetes/minikube/blob/v0.23.0/vendor/k8s.io/apimachinery/pkg/apimachinery/registered/registered.go#L244

Interestingly enough, the code appears again on the master as well as on the v0.22.0 branch: https://github.com/kubernetes/minikube/blob/master/vendor/k8s.io/apimachinery/pkg/apimachinery/registered/registered.go#L246

**Comment by r2d4** [comment]
@kufi I believe it was backported to the 1.6.x releases, but not 1.5.x
