### ISSUE TITLE
MacOS minikube / hyperkit / kubelet failed to start

### ISSUE THREAD

**Issue by Beenhakker** [kubernetes/minikube#14966]
### What Happened?

Tried to start minikube with the hyperkit driver: (I already tried the suggestion to add the extra option cgroup-driver, but problem remains the same)

- minikube start --driver=hyperkit --hyperkit-vsock-ports 8000 --cpus 3 --memory 7962 --extra-config=apiserver.service-node-port-range=80-65535 --extra-config=kubelet.cgroup-driver=systemd

Kubelet fails to boot, and we are left with an incomplete cluster.

### Attach the log file

[kubectl_error.log.txt](https://github.com/kubernetes/minikube/files/9598648/kubectl_error.log.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by yuzhaopeng** [comment]
There may be a problem with IP assignment，Hyperkit requires '192.168.64.1' as the host address

**Comment by yuzhaopeng** [comment]
Try deleting all Hyperkit machines ，and then boot up

**Comment by yuzhaopeng** [comment]
Or you can try specifying Kubernetes version 1.23.10

**Comment by klaases** [comment]
Hi @Beenhakker  – is this issue still occurring? Were you able to find a solution?

For additional assistance, please consider reaching out to the minikube community:

https://minikube.sigs.k8s.io/community/

We also offer support through Slack, Groups, and office hours.

/triage needs-information
/kind support

**Comment by Beenhakker** [comment]
Hi @klaases,

Thanks for getting back at this.

Seems like it fixed without any further references.

I updated to the latest versions, and it is running again.

References:
😄  minikube v1.27.1 on Darwin 12.6
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.25.2 preload ...
