### ISSUE TITLE
add an additional worker node to a bare-metal cluster (--driver=none)

### ISSUE THREAD

**Issue by mulan04** [kubernetes/minikube#14971]
### What Happened?

I was wondering how to add / join an additional (physical) worker node to an existing bare-metal cluster (--driver=none) which consists only of the single master node which was created by 'minikube start --driver=none --container-runtime=docker --kubernetes-version=v1.24.3 --network-plugin=cni --cni=calico  --extra-config=kubelet.cgroup-driver=systemd" and works well?

Is this possible at all? Can someone please provide a step-by-step description if this has been done successfully?

I tried with "kubeadm token create" on the master and accordingly "kubeadm join" on my other node, but finally it does not register.
(naming resolution on both nodes works well and needed communication ports are open in the FWs)

### Attach the log file

# kubeadm join 192.168.0.20:8443 --token pkwlnw.ymgmerlmb0m11zin --discovery-token-ca-cert-hash sha256:2e22c4c178bf5ef149ddcaf2910dd4c8df03e6caaa4eee7b92f8250d306fc4de -v 5
I0918 20:47:13.464803  116082 join.go:413] [preflight] found NodeName empty; using OS hostname as NodeName
I0918 20:47:13.464992  116082 initconfiguration.go:117] detected and using CRI socket: unix:///var/run/cri-dockerd.sock
[preflight] Running pre-flight checks
I0918 20:47:13.465108  116082 preflight.go:92] [preflight] Running general checks
I0918 20:47:13.465520  116082 checks.go:282] validating the existence of file /etc/kubernetes/kubelet.conf
I0918 20:47:13.465552  116082 checks.go:282] validating the existence of file /etc/kubernetes/bootstrap-kubelet.conf
I0918 20:47:13.465585  116082 checks.go:106] validating the container runtime
I0918 20:47:13.571505  116082 checks.go:331] validating the contents of file /proc/sys/net/bridge/bridge-nf-call-iptables
I0918 20:47:13.571605  116082 checks.go:331] validating the contents of file /proc/sys/net/ipv4/ip_forward
I0918 20:47:13.571683  116082 checks.go:646] validating whether swap is enabled or not
I0918 20:47:13.571750  116082 checks.go:372] validating the presence of executable crictl
I0918 20:47:13.571795  116082 checks.go:372] validating the presence of executable conntrack
I0918 20:47:13.572655  116082 checks.go:372] validating the presence of executable ip
I0918 20:47:13.573504  116082 checks.go:372] validating the presence of executable iptables
I0918 20:47:13.573576  116082 checks.go:372] validating the presence of executable mount
I0918 20:47:13.574070  116082 checks.go:372] validating the presence of executable nsenter
I0918 20:47:13.574143  116082 checks.go:372] validating the presence of executable ebtables
I0918 20:47:13.575657  116082 checks.go:372] validating the presence of executable ethtool
I0918 20:47:13.576109  116082 checks.go:372] validating the presence of executable socat
I0918 20:47:13.576876  116082 checks.go:372] validating the presence of executable tc
I0918 20:47:13.577209  116082 checks.go:372] validating the presence of executable touch
I0918 20:47:13.577357  116082 checks.go:518] running all checks
I0918 20:47:13.588232  116082 checks.go:403] checking whether the given node name is valid and reachable using net.LookupHost
I0918 20:47:13.588418  116082 checks.go:612] validating kubelet version
I0918 20:47:14.072832  116082 checks.go:132] validating if the "kubelet" service is enabled and active
I0918 20:47:14.122817  116082 checks.go:205] validating availability of port 10250
I0918 20:47:14.123025  116082 checks.go:282] validating the existence of file /etc/kubernetes/pki/ca.crt
I0918 20:47:14.123045  116082 checks.go:432] validating if the connectivity type is via proxy or direct
I0918 20:47:14.123465  116082 join.go:530] [preflight] Discovering cluster-info
I0918 20:47:14.123512  116082 token.go:80] [discovery] Created cluster-info discovery client, requesting info from "192.168.0.20:8443"
I0918 20:47:14.141884  116082 token.go:118] [discovery] Requesting info from "192.168.0.20:8443" again to validate TLS against the pinned public key
I0918 20:47:14.148365  116082 token.go:135] [discovery] Cluster info signature and contents are valid and TLS certificate validates against pinned roots, will use API Server "192.168.0.20:8443"
I0918 20:47:14.148398  116082 discovery.go:52] [discovery] Using provided TLSBootstrapToken as authentication credentials for the join process
I0918 20:47:14.148431  116082 join.go:544] [preflight] Fetching init configuration
I0918 20:47:14.148437  116082 join.go:590] [preflight] Retrieving KubeConfig objects
[preflight] Reading configuration from the cluster...
[preflight] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -o yaml'
I0918 20:47:14.159310  116082 kubelet.go:92] attempting to download the KubeletConfiguration from the new format location (UnversionedKubeletConfigMap=true)
I0918 20:47:14.163941  116082 interface.go:432] Looking for default routes with IPv4 addresses
I0918 20:47:14.163999  116082 interface.go:437] Default route transits interface "eth0"
I0918 20:47:14.165054  116082 interface.go:209] Interface eth0 is up
I0918 20:47:14.165127  116082 interface.go:257] Interface "eth0" has 6 addresses :[192.168.0.45/24 2a02:810d:4d3f:fe30:1b46:139d:67fa:578f/64 2a02:810d:4d3f:fe30:e8ef:6ec3:51a8:77d5/64 2a02:810d:4d3f:fe30:1cd3:4334:ba46:5074/64 fe80::1772:f452:6b22:27f1/64 fe80::6243:1423:f28:38f/64].
I0918 20:47:14.165168  116082 interface.go:224] Checking addr  192.168.0.45/24.
I0918 20:47:14.165179  116082 interface.go:231] IP found 192.168.0.45
I0918 20:47:14.165199  116082 interface.go:263] Found valid IPv4 address 192.168.0.45 for interface "eth0".
I0918 20:47:14.165221  116082 interface.go:443] Found active IP 192.168.0.45 
I0918 20:47:14.172422  116082 preflight.go:103] [preflight] Running configuration dependant checks
I0918 20:47:14.172458  116082 controlplaneprepare.go:220] [download-certs] Skipping certs download
I0918 20:47:14.172478  116082 kubelet.go:119] [kubelet-start] writing bootstrap kubelet config file at /etc/kubernetes/bootstrap-kubelet.conf
I0918 20:47:14.173084  116082 kubelet.go:134] [kubelet-start] writing CA certificate at /etc/kubernetes/pki/ca.crt
I0918 20:47:14.173460  116082 kubelet.go:155] [kubelet-start] Checking for an existing Node in the cluster with name "mulan042.daheim.com" and status "Ready"
I0918 20:47:14.177265  116082 kubelet.go:170] [kubelet-start] Stopping the kubelet
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Starting the kubelet
[kubelet-start] Waiting for the kubelet to perform the TLS Bootstrap...
I0918 20:47:19.999237  116082 cert_rotation.go:137] Starting client certificate rotation controller
I0918 20:47:19.999680  116082 kubelet.go:218] [kubelet-start] preserving the crisocket information for the node
I0918 20:47:20.028652  116082 patchnode.go:31] [patchnode] Uploading the CRI Socket information "unix:///var/run/cri-dockerd.sock" to the Node API object "mulan042.daheim.com" as an annotation
[kubelet-check] Initial timeout of 40s passed.
nodes "mulan042.daheim.com" not found
error uploading crisocket
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/join.runKubeletStartJoinPhase
        cmd/kubeadm/app/cmd/phases/join/kubelet.go:220
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:234
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdJoin.func1
        cmd/kubeadm/app/cmd/join.go:178
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
        cmd/kubeadm/app/kubeadm.go:50
main.main
        cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571
error execution phase kubelet-start
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run.func1
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:235
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).visitAll
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:421
k8s.io/kubernetes/cmd/kubeadm/app/cmd/phases/workflow.(*Runner).Run
        cmd/kubeadm/app/cmd/phases/workflow/runner.go:207
k8s.io/kubernetes/cmd/kubeadm/app/cmd.newCmdJoin.func1
        cmd/kubeadm/app/cmd/join.go:178
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        vendor/github.com/spf13/cobra/command.go:856
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        vendor/github.com/spf13/cobra/command.go:974
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        vendor/github.com/spf13/cobra/command.go:902
k8s.io/kubernetes/cmd/kubeadm/app.Run
        cmd/kubeadm/app/kubeadm.go:50
main.main
        cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:250
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1571

# systemctl status kubelet.service
● kubelet.service - kubelet: The Kubernetes Node Agent
     Loaded: loaded (/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/kubelet.service.d
             └─10-kubeadm.conf
     Active: active (running) since Sun 2022-09-18 21:13:29 CEST; 6min ago
       Docs: http://kubernetes.io/docs/
   Main PID: 53958 (kubelet)
      Tasks: 21 (limit: 4582)
     CGroup: /system.slice/kubelet.service
             └─ 53958 /var/lib/minikube/binaries/v1.24.3/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --cgroup-driver=systemd --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/var/run/cri-dockerd.sock --hostname-override=mulan04.daheim.com --image-service-endpoint=/var/run/cri-dockerd.sock --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=192.168.0.45 --runtime-request-timeout=15m

Sep 18 21:18:56 mulan042.daheim.com kubelet[53958]: E0918 21:18:56.952880   53958 controller.go:187] failed to update lease, error: Operation cannot be fulfilled on leases.coordination.k8s.io "mulan04.daheim.com": the object has been modified; please apply your changes to the latest version and try again

### Operating System

Redhat/Fedora

**Comment by afbjorklund** [comment]
Since the "none" driver basically runs `kubeadm` on the localhost, it should be theoretically possible to join it.

Looks like a rather nasty crash there though, you might be better off with running kubeadm directly instead ?

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/

**Comment by mulan04** [comment]
ok - thanks
