### ISSUE TITLE
 minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.34

### ISSUE THREAD

**Issue by Parthiba-Hazra** [kubernetes/minikube#14973]
### What Happened?

After execute the command  minikube start --driver=docker   
First it continually pulling the gcr.io/k8s-minikube/kicbase and index.docker.io/kicbase/sta. even after 100% download . Then it  shows minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.34,

next I tried minikube delete and minikube start again 
but it gives same error every time .

Os - Ubuntu 22.04

### Attach the log file

![Screenshot from 2022-09-19 11-24-29](https://user-images.githubusercontent.com/101032025/190958189-904fef2d-95c8-4e45-a527-16fae46c601e.png)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
You can try with `docker pull` see if it gives you a better error message ?

**Comment by Parthiba-Hazra** [comment]
> You can try with `docker pull` to see if it gives you a better error message ?

Yes it's work, thank you @afbjorklund  I pull the image gcr.io/k8s-minikube/kicbase and the error solved.

But the second error (Enabling 'default-storageclass' returned an error: running callbacks) yet not solved . can you help on that also?

**Comment by afbjorklund** [comment]
Sounds normal if the cluster is down

**Comment by Parthiba-Hazra** [comment]
hey @afbjorklund  thank you for your support but I still cant find the solution as I am a new learner .
here in the logs of minikube ... it shows "Failed to find module 'autofs4'" and  I am using ubuntu 22.04 LTS , I cant find what is broken :(
![Screenshot from 2022-09-20 11-00-11](https://user-images.githubusercontent.com/101032025/191175598-edc2e497-7cdd-4dea-904a-2cd6b08fab68.png)

**Comment by afbjorklund** [comment]
Docker Desktop is not yet supported on Linux

**Comment by Parthiba-Hazra** [comment]
here is the log file-
[logs.txt](https://github.com/kubernetes/minikube/files/9605032/logs.txt)

**Comment by Parthiba-Hazra** [comment]
Ok then I am going with Kvm ;)

**Comment by hemanthkotaprolu** [comment]
I am using docker desktop in linux. And it worked.
I did `docker pull` for the first error and it seemed to work and i am able to run the cluster.

**Comment by Parthiba-Hazra** [comment]
> I am using docker desktop in linux(Pop OS). And it worked. I did `docker pull` for the first error and it seemed to work and i am able to run the cluster.

But sadly, it's not working in ubuntu-22.04.

**Comment by moeshinyo** [comment]
> But sadly, it's not working in ubuntu-22.04.

you may pull the lastest (10/17/2022, v0.0.35) container manually, and execute `minikube start` again. 

```bash
docker pull gcr.io/k8s-minikube/kicbase@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b
```

from <https://gcr.io/k8s-minikube/kicbase> -> <https://console.cloud.google.com/gcr/images/k8s-minikube/GLOBAL/kicbase> -> ![image](https://user-images.githubusercontent.com/89891762/196082313-17b97c51-4858-4015-b9ae-0241c4bfed35.png)

**Comment by zioproto** [comment]
I had the same issue not being able to: `minikube start` on Mac with Docker Desktop.
The `gcr.io/k8s-minikube/kicbase` was stuck in download forever:

```
% minikube start
😄  minikube v1.27.1 on Darwin 12.6 (arm64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > gcr.io/k8s-minikube/kicbase:  0 B [__________________________] ?% ? p/s ?^C
```

Downloading the specific version as suggested fixed the problem:
```
docker pull gcr.io/k8s-minikube/kicbase@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b
```

**Comment by mpostoronca** [comment]
Turn off your firewall and make sure `DOCKER_DEFAULT_PLATFORM=''` that's what helped me

**Comment by shsma** [comment]
>Turn off your firewall and make sure DOCKER_DEFAULT_PLATFORM='' that's what helped me (on a macOS)



This worked for me.
