### ISSUE TITLE
The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd

### ISSUE THREAD

**Issue by Parthasarathy28** [kubernetes/minikube#14984]
### What Happened?

The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd

### Attach the log file

The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd

**Comment by afbjorklund** [comment]
Yes, that sounds right.

https://minikube.sigs.k8s.io/docs/drivers/none/
