### ISSUE TITLE
Built-in kubernetes-dashboard (v2.6.0) doesn't work properly on minikube 1.27.0

### ISSUE THREAD

**Issue by wiktor-golonka** [kubernetes/minikube#14986]
### What Happened?

On fresh install of minikube 1.27.0, dashboard is not working properly on the 'Workloads' page.
- minikube 1.27.0
- kubernetes 1.25
- kubernetes-dashboard (v2.6.0) (included in minikube)

Steps to reproduce: 

minikube delete
minikube start --driver docker
minikube dashboard 

Expected: 
Workloads page works fine

Current behaviour: 
Workloads page returns 404 -> the server could not find the requested resource

Looks like the request that fails is: 
http://127.0.0.1:51371/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/api/v1/cronjob/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp

kubernetes-dashboard (v2.7.0) works fine with this version of minikube

### Attach the log file

Request General: 
```
Request URL: http://127.0.0.1:51371/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/api/v1/cronjob/default?itemsPerPage=10&page=1&sortBy=d,creationTimestamp
Request Method: GET
Status Code: 404 Not Found
Remote Address: 127.0.0.1:51371
Referrer Policy: strict-origin-when-cross-origin
```

Request headers from chrome console: 
```
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9,en-US;q=0.8,pl;q=0.7
Connection: keep-alive
Host: 127.0.0.1:51371
Referer: http://127.0.0.1:51371/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/
sec-ch-ua: "Microsoft Edge";v="107", "Chromium";v="107", "Not=A?Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36
```

### Operating System

Windows

### Driver

Docker

**Comment by MDutro** [comment]
I am having the same issue on the same versions of minikube and kubernetes. 

I am on Fedora 36 and use driver kvm2. Please let me know if I can provide further helpful information.

**Comment by spowelljr** [comment]
This should be fixed with https://github.com/kubernetes/minikube/pull/15000

**Comment by MDutro** [comment]
Thanks for the update! I'll test it out just as soon as possible and report back.

**Comment by wiktor-golonka** [comment]
@spowelljr : Thank you. I can confirm it works fine.

**Comment by MDutro** [comment]
Can confirm that the Workloads page works correctly now in Fedora 36 on kvm2. Thanks folks!

**Comment by spowelljr** [comment]
Glad it works, I'm going to close this issue, release should come out on Thursday.

**Comment by nahuelmd** [comment]
Same issue on MacOs minikube version: v1.27.0
