### ISSUE TITLE
Ubuntu22.04 Docker(rootless mode)20.10.18 Minikubev1.27.0 start failed

### ISSUE THREAD

**Issue by coco961003** [kubernetes/minikube#14985]
### What Happened?

[Uploading minikube-start.log…]()
I am learning k8s and want to begin with minikube, but met some problems.
I would appreciate any suggestions/solutions/advices.

Command:
`minikube start --container-runtime='containerd' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --image-mirror-country='cn' --kubernetes-version='1.21.14' --alsologtostderr` 

Stdout/StdErr: See attachment（A little decoding problem in my computer. If necessary, I would paste another one.）

Possible helpful msgs:
Disable swap `swapoff -a && sed -ri 's/.*swap.*/#&/' /etc/fstab`
Add syh(the user other than root) to docker user group
Enable CPU, CPUSET, and I/O delegation (follow https://rootlesscontaine.rs/getting-started/common/cgroup2/)
Add Aliyun yum repo and docker repo
Run dockerd-rootless-setuptool.sh and add ENV to ~/.bashrc but UNSET DOCKER_HOST becuase `docker context rootless` warn

Many thanks.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9615464/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by AkihiroSuda** [comment]
> Sep 21 09:58:08 minikube kubelet[108686]: E0921 09:58:08.895170  108686 server.go:186] "Failed to set feature gates from initial flags-based config" err="unrecognized feature gate: KubeletInUserNamespace"

`--kubernetes-version='1.21.14'` is incompatible with rootless. Please chose a newer version.
