### ISSUE TITLE
Support driver options through environment variables

### ISSUE THREAD

**Issue by budhrg** [kubernetes/minikube#1499]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**Expected Behavior**
Docker-machine driver supports few environment variables like [hyperv options](https://docs.docker.com/machine/drivers/hyper-v/#environment-variables-and-default-values), [virtualbox options](https://docs.docker.com/machine/drivers/virtualbox/#options) etc. It would be great if we support this with just exporting the desired environment variables.

For example, we can explicitly set virtual switch for HyperV as `HYPERV_VIRTUAL_SWITCH`. It's an another way to set switch apart from `MINIKUBE_HYPERV_VIRTUAL_SWITCH`.

With this approach, we can support most of driver options instead of adding them as option for start command.

Inspiration taken from https://github.com/minishift/minishift/issues/305 or https://github.com/minishift/minishift/issues/739.

**Comment by budhrg** [comment]
Still underprogress here https://github.com/budhrg/minikube/tree/issue-1499. 

Bit stuck in passing unit tests here. Working on that.

**Comment by huguesalary** [comment]
@budhrg great to see someone working on this, thanks!

I'm also interested in being able to pass custom driver options when creating a minikube vm.

Using environment variables is great, but I'd also like to be use a command line flag.

In your code, you copy/paste driver flags from the driver code:

![image](https://user-images.githubusercontent.com/755890/28227828-9d7d2b46-6890-11e7-94ce-04ae16be19d1.png)

Wouldn't it be better to simply create a minikube flag like `--driver-options` that would be passed to the driver instead?

For example `--driver-options=virtualbox-memory=8gb,virtualbox-cpu-count=8`.

This would allow the driver to add new flags overtime without having to change your code to reflect the new driver options.

**Comment by budhrg** [comment]
I am closing this as it seems it is not best fit for profile case. We are reverting back similar changes in Minishift side too https://github.com/minishift/minishift/issues/1622
