### ISSUE TITLE
Bundle the localkube binary with the release

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#15]
Rather than fetching it from github, we should include a fixed copy of the localkube binary that will run in the VM. This can either be transferred in from the minikube CLI or baked into the VM image.

**Comment by vishh** [comment]
Do we plan on supporting in-place upgrades? If yes, injecting localkube will be useful..

**Comment by dlorenc** [comment]
Good point. Injecting at boot time would help there. One approach we can use to bundle the binary might be to use something like go-bindata: https://github.com/jteeuwen/go-bindata

This would let us ship just a single binary with everything in it, including the components that run in the guest image.

**Comment by vishh** [comment]
`go-bindata` sounds promosing. Another alternative is to do something
similar to `hyperkube`. We can have `minikube` run `localkube` if it is
invoked as `localkube`.

**Comment by dlorenc** [comment]
Yeah, that could work too. But we'd still need to get the binary itself into the VM. I guess we could have minikube send itself into the VM over scp, and then rename that file to localkube.

**Comment by dlorenc** [comment]
Whoops, that wouldn't work on OSX/windows since we need localkube to be amd64 inside the vm and minikube to be darwin on the outside :) We'll have to bundle a separate binary.

**Comment by dlorenc** [comment]
This is fixed with #66
