### ISSUE TITLE
Exiting due to RUNTIME_ENABLE: kernel >= 5.11 is required for rootless mode: service "kernel" version is 4.18.0-408.el8.x86_64. Required: 5.11

### ISSUE THREAD

**Issue by lees0088** [kubernetes/minikube#15008]
### What Happened?

Unable to get minikube running on Centos8-stream
SELinux tested with Permissive and Disabled also the same result

Any help would be much appreciated.

[admin@awx-lab-c8s ~]$ uname -r
4.18.0-408.el8.x86_64

[admin@awx-lab-c8s ~]$ sudo firewall-cmd --list-all
public (active)
  target: default
  icmp-block-inversion: no
  interfaces: ens160
  sources:
  services: cockpit dhcpv6-client ssh
  ports:
  protocols:
  forward: no
  masquerade: yes
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

[admin@awx-lab-c8s ~]$ kubectl version --short
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v1.25.2
Kustomize Version: v4.5.7
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[admin@awx-lab-c8s ~]$ minikube version
minikube version: v1.27.0
commit: 4243041b7a72319b9be7842a7d34b6767bbdac2b
[admin@awx-lab-c8s ~]$ docker version
Client: Docker Engine - Community
 Version:           20.10.18
 API version:       1.41
 Go version:        go1.18.6
 Git commit:        b40c2f6
 Built:             Thu Sep  8 23:11:56 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.18
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.6
  Git commit:       e42327a
  Built:            Thu Sep  8 23:10:04 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9635317/logs.txt)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by AkihiroSuda** [comment]
As shown in the error message, you need to use a host OS with kernel 5.11 or later to use rootless mode.
e.g., Rocky/Alma 9 (kernel 5.14), Ubuntu 22.04 (kernel 5.15), or Fedora 36 (kernel 5.17).

**Comment by klaases** [comment]
> As shown in the error message, you need to use a host OS with kernel 5.11 or later to use rootless mode.
> e.g., Rocky/Alma 9 (kernel 5.14), Ubuntu 22.04 (kernel 5.15), or Fedora 36 (kernel 5.17).

Hi @lees0088  – did the above help resolve the issue? If not, please feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed.

Additional information that may be helpful:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* Attach the full output of minikube logs, run `minikube logs --file=logs.txt` to create a log file

Thank you for sharing your experience!
