### ISSUE TITLE
Cannot open minikube dashboard from the VM on my local machine

### ISSUE THREAD

**Issue by harika1210** [kubernetes/minikube#15015]
### What Happened?

I have installed minikube on my linux server on my Oracle VM. I have tried opening the dashboard, but I can't open it open on my local machine.

The process I follow: 
1. minikube start
2. minikube dashboard
3.   Enabling dashboard ...
 Verifying dashboard health ...
 Launching proxy ...
 Verifying proxy health ...
 
 After this, it gives me a url (http://127.0.0.1:44987/api/v1/namespaces/kubernetes-dashboard/services/https:kubernetes-dashboard:proxy/ ) 
 
 When I tried opening it manually on my local machine (Chrome or Firefox) it doesn't open. 

### Attach the log file

I have not provided with the logs, please let me know if they are necessary. 

### Operating System

Windows

### Driver

Docker

**Comment by afbjorklund** [comment]
If you run minikube on a VM, that _is_ your local machine. It assumes the browser is on the same host.

You can set up tunneling of that port (to the VM), or you can run minikube on your preferred machine.
