### ISSUE TITLE
minikube addons enable ingress;

### ISSUE THREAD

**Issue by Dhaded** [kubernetes/minikube#15010]
### What Happened?

I ran minikube addons enable ingress;

### Attach the log file

Log file created at: 2022/09/24 12:11:42
Running on machine: kd-ef5d364c-1f67-11b2-a85c-c3afe46a9a0e
Binary: Built with gc go1.17.7 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0924 12:11:42.354768  104302 out.go:297] Setting OutFile to fd 1 ...
I0924 12:11:42.354874  104302 out.go:349] isatty.IsTerminal(1) = true
I0924 12:11:42.354877  104302 out.go:310] Setting ErrFile to fd 2...
I0924 12:11:42.354879  104302 out.go:349] isatty.IsTerminal(2) = true
I0924 12:11:42.354948  104302 root.go:315] Updating PATH: /home/shivalingesh/.minikube/bin
I0924 12:11:42.355268  104302 config.go:176] Loaded profile config "minikube": Driver=kvm2, ContainerRuntime=docker, KubernetesVersion=v1.23.3
I0924 12:11:42.355277  104302 addons.go:65] Setting ingres=true in profile "minikube"
I0924 12:11:42.355483  104302 out.go:176] 
W0924 12:11:42.355543  104302 out.go:241] ❌  Exiting due to MK_ADDON_ENABLE: run callbacks: ingres is not a valid addon
W0924 12:11:42.355550  104302 out.go:241] 
W0924 12:11:42.356407  104302 out.go:241] [31m╭───────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                             [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                             [31m│[0m
[31m│[0m    - /tmp/minikube_addons_779a741b3c18c2c2e487d3dad84a776d362b3c45_0.log                  [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯[0m

### Operating System

Redhat/Fedora

### Driver

KVM2

**Comment by klaases** [comment]
Hi @Dhaded,

I think there is a typo in ingress (ingres):

`❌ Exiting due to MK_ADDON_ENABLE: run callbacks: ingres is not a valid addon`

Consider `ingress`

Example:
https://minikube.sigs.k8s.io/docs/commands/addons/#examples-1

Does this help?

/triage needs-information
/kind support
