### ISSUE TITLE
Update kube-dns to 1.14.2

### ISSUE THREAD

**Issue by ankon** [kubernetes/minikube#1501]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request.

**Minikube version** (use `minikube version`): v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Fedora 25 on x86_64
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.18.0
- **Install tools**:
- **Others**:

**What happened**:
I updated to minikube 0.19.0, and since then dns inside the containers is extremely flaky: pods fail to resolve names either completely, or only partially (for example regular queries fail, but querying for the SRV records works).

I checked kube-dns for anything, and found that there is a version 1.14.2 which claims to fix concurrency issues: https://github.com/kubernetes/kubernetes/commit/1c223c8e1b0af36bdfe389a364b7cc7ca836ecde#diff-7613ffc069fdb10506c01a83b89bb804

**What you expected to happen**: Stable DNS, latest version of kube-dns.

**How to reproduce it** (as minimally and precisely as possible): Not really sure about the instability; `kubectl -n kube-system describe deploy kube-dns` for the older version of kube-dns in use.

**Anything else do we need to know**:

**Comment by bluto56** [comment]
I'm having similar instabilities

```
vic_server/deployment [ kubectl get services                                                                                                                                                      k8s * ] 11:02 PM
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.0.0.1     <none>        443/TCP   41m
vic_server/deployment [ kubectl exec -it busybox-2965826744-5h0j9 sh                                                                                                                              k8s * ] 11:02 PM
/ # nslookup kubernetes
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'kubernetes'
/ # nslookup kubernetes
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes
Address 1: 10.0.0.1 kubernetes.default.svc.cluster.local
/ # nslookup kubernetes
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'kubernetes'
/ # exit
```

**Comment by dlorenc** [comment]
Thanks, we'll try updating to 1.14.2. I'd like to make sure I can reproduce this (so I can make sure the update fixes it). Are you doing anything special, or just running the busybox pod?

**Comment by ankon** [comment]
FWIW: In my case the environment is more complicated, but I am able to test builds if needed.
