### ISSUE TITLE
Podman version mismatch

### ISSUE THREAD

**Issue by bhunsicker** [kubernetes/minikube#15036]
### What Happened?

Installed Podman on Windows 10 (v4.2)
installed Minikube

`
podman machine stop
podman machine set --rootful
podman machine start
minikube config set driver podman
minikube config set rootless false
minikube config set container-runtime crio
minikube config set insecure-registry docker-base-usaa.repo.usaa.com
minikube config set embed-certs true
copy the roo2GA to ~/.minikube/certs/
minikube start --network-plugin=cni --cni=auto --extra-config=kubelet.cgroup-driver=systemd --embed-certs
kubectl config use-context minikube 
& minikube -p minikube podman-env --shell powershell | Invoke-Expression
`
try to run a podman build `podman build . -t api-ecosystem-ref-app`

get this error:
Error: unable to connect to Podman socket: server API version is too old. Client "4.0.0" server "3.4.2"

Any idea when minikube will upgrade the internal podman or instructions so I can do it myself?

### Attach the log file

log file too long

### Operating System

Windows

### Driver

Podman

**Comment by afbjorklund** [comment]
It will have to wait until the Ubuntu version is upgraded (to 22.04)...

For now, you can install the older podman3 client for it.
https://github.com/containers/podman/releases/tag/v3.4.4

You can also use `minikube image`, instead of `podman`.

**Comment by bhunsicker** [comment]
yea, that was my workaround.  it has been ... interesting :)

Thanks!

**Comment by mnebus** [comment]
Any updates on this?

**Comment by afbjorklund** [comment]
Probably just remove the podman support (for remote), though you can still use `minikube ssh` and `minikube image`.

* https://github.com/kubernetes/minikube/issues/15461

There was some idea to update the 3.4.2 to something like 3.4.4 or 3.4.7, but I don't think anyone started on 4.x ?

The external driver should probably support it, though. Or only Podman Desktop.

**Comment by phvogtrbi** [comment]
I would really be interested in an update, as RHEL 9 provides podman > 4.x and therefore minikube cannot really be used together with podman built images.

**Comment by afbjorklund** [comment]
Why are the images depending on the podman version ? It does need an older client, but that's a different story.

**Comment by oprudkyi** [comment]
it is still 3.3.4 

`
minikube ssh -- bash
podman -v    
podman version 3.4.4
`

**Comment by sebastian-philipp** [comment]
can confirm: 

```
$ podman images                            
Error: unable to connect to Podman socket: server API version is too old. Client "4.0.0" server "3.4.4"
```

**Comment by afbjorklund** [comment]
The `podman-env` command is deprecated, it should be replaced with `docker-env` (and `docker` client) eventually

Since it is backwards compatible, unlike the Podman clients. But the old `podman-remote` should still be available.

**Comment by sebastian-philipp** [comment]
> The `podman-env` command is deprecated

```
LANG=C minikube docker-env

❌  Exiting due to MK_USAGE: the docker-env command only supports the docker and containerd runtimes
``` 

That was the only reason to try podman-env

**Comment by afbjorklund** [comment]
No, but it should be doable to convert the syntax. The podman socket itself supports a docker client.
