### ISSUE TITLE
minikube start failing with addon/coredns issue

### ISSUE THREAD

**Issue by mrityunjay308** [kubernetes/minikube#15033]
### What Happened?

I have been running minikube on Amazon Linux 2 for few months but suddenly the minikube service stopped on the instances.  
When minikube is started with minikube start --vm-driver=none on the instances, it errors out with below errors:
OS Details: Amazon Linux 2
Minikube version: minikube version: v1.19.0
Docker Client/Server Version: 20.10.7

The minikube start command errors out (with multiple errors):
error execution phase addon/coredns: unable to get list of changes to the configuration.: start version 'v1.8.0' not supported
To see the stack trace of this error execute with --v=5 or higher
W0929 01:11:30.669600   19373 out.go:222] 
W0929 01:11:30.669785   19373 out.go:222] 💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  

error execution phase addon/coredns: unable to get list of changes to the configuration.: start version 'v1.8.0' not supported
To see the stack trace of this error execute with --v=5 or higher

W0929 01:11:30.669913   19373 out.go:222] 
W0929 01:11:30.669949   19373 out.go:222] 😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
W0929 01:11:30.669979   19373 out.go:222] 👉  https://github.com/kubernetes/minikube/issues/new/choose
I0929 01:11:30.673739   19373 out.go:157] 
W0929 01:11:30.673926   19373 out.go:222] ❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml

Can someone help with why coredns has suddenly started throwing error.

### Attach the log file

[minikubelog.txt](https://github.com/kubernetes/minikube/files/9670040/minikubelog.txt)

### Operating System

Other

### Driver

None (Baremetal)

**Comment by mrityunjay308** [comment]
Any help here?
Is there a way to edit coredns cm to use different image tag before minikube start. I cant use kubectl to update coredns cm as there is nothing running currently.

**Comment by remram44** [comment]
I am also getting that error but minikube starts successfully:

> `minikube start --kubernetes-version=1.22.15 --driver=docker --nodes=1 --container-runtime=docker --ports=8000:30808`
> `stderr:`
> `error execution phase addon/coredns: unable to get list of changes to the configuration.: start version '1.8.6' not supported`

This stopped happening when I got off my company's VPN. It routes a lot of networks through, which tends to interfere with Docker operation, for example `docker-compose up` fails with:

> `failed to create network myapp_default: Error response from daemon: could not find an available, non-overlapping IPv4 address pool among the defaults to assign to the network`

So this might be related.
