### ISSUE TITLE
❗  This container is having trouble accessing https://registry.k8s.io

### ISSUE THREAD

**Issue by kumar-niteesh** [kubernetes/minikube#15047]
### What Happened?

How to resolve this issue ?

### Attach the log file

W1001 11:11:34.178758   75062 start.go:735] [curl -sS -m 2 https://registry.k8s.io/] failed: curl -sS -m 2 https://registry.k8s.io/: Process exited with status 60
stdout:

stderr:
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
W1001 11:11:34.178995   75062 out.go:239] ❗  This container is having trouble accessing https://registry.k8s.io

### Operating System

macOS (Default)

### Driver

Docker

**Comment by rreddy78** [comment]
I got the same problem running on Ubuntu 20.04.

  This container is having trouble accessing https://registry.k8s.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

**Comment by ahs8w** [comment]
I'm seeing the same issue on macOS with docker driver.  Any ideas on how to proceed?
