### ISSUE TITLE
Explicit that the "Automated Google Cloud Platform Authentication" addon does'nt work with isolated service account

### ISSUE THREAD

**Issue by mensis-labs** [kubernetes/minikube#15045]
The second phrase of second paragraph, don't match reality.

===
The addon normally uses the [Google Application Default Credentials](https://google.aip.dev/auth/4110) as configured with gcloud auth application-default login. If you already have a json credentials file you want specify, such as to use a service account, set the GOOGLE_APPLICATION_CREDENTIALS environment variable to point to that file.
===

Even if create a service account, give it artifact registry reader permission, and use it's json key with this addon, it doesn't work.
The doc should make it explicit to use one retrieved from that gcloud command!

**Comment by medyagh** [comment]
@mensis-labs are you referring to gcp-auth addon ? and do you mind sharing more details such as steps to reproduce the issues and the expected result ?

**Comment by mensis-labs** [comment]
sry for my delay. 
Yes @medyagh I'm referring to gcp-auth addon. 
Yes @klaases that's the doc I've read

The steps I made were like that (for the parte were I couldn't make it work):

- access a gcp project where my built images were
- create a service account
- give it artifact registry reader permission
- get it's json key
- test it on other external gcp project to see if it can access my images
- put that json in my dev environment
- refer to it in env variable before start minikube
- "activate" gcp-auth addon
- try to run some image that were in artifact registry 
- go 403 errors because that service account wasn't allowed to access my images


The steps I made were I succesful make it run:

- access a gcloud (i use it in a docker image)
- make application default auth 
- copy the json it to my dev env
- refer to its in env variable
- start minikube
- activate gcp-auth
- try to run
- it works...
