### ISSUE TITLE
k8s RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1

### ISSUE THREAD

**Issue by QasimSultani** [kubernetes/minikube#15049]
### What Happened?

I'm installing k8s on Virtual box with one node only no cluster 
RAM=4
HD=40
vCPU=2

following these steps:

Install Docker
$  sudo apt update && apt -y install docker.io

 Install kubectl
$  curl -LO [https://storage.googleapis.com/kubern...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbWxERUlXYklvRktEeWVXcjJvaTU2cEJnanFSUXxBQ3Jtc0ttVlQ0Wm92Tm1ZalBCNXVyd2NfUE50aVdoOVhXdkJXb0RxRjFEa2MwaVdYdGRsVUtXR0REaGNIa0k5NC1tVzhwNi1rd2hKVFJOa25PekxuOVVNTzIzY21OTW5NZjNUMHlBT2tTZ3RQTlhLNWFlb2REQQ&q=https%3A%2F%2Fstorage.googleapis.com%2Fkubernetes-release%2Frelease%2F%24%28curl&v=J2sUlm2cwQk) -s [https://storage.googleapis.com/kubern...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqa19mbEVySFJvazNrWEM2LXNIOGczV3BwNENJUXxBQ3Jtc0trLTVvNW9QenRTSzg4Q2YwdW1lTTZqMWdHMExiWmNOSjEwa28zVmV0OEhSd2tweVQwbE43eHBLUnR4c2dweEtNMXF2OXZISVhlWnpyVVFMYnlrTEVJT2VIVV9mczNBUWoybE1abnRqTUtHaElfMERRSQ&q=https%3A%2F%2Fstorage.googleapis.com%2Fkubernetes-release%2Frelease%2Fstable.txt%29%2Fbin%2Flinux%2Famd64%2Fkubectl&v=J2sUlm2cwQk) &&   chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl

 Install Minikube
$  curl -Lo minikube [https://storage.googleapis.com/miniku...](https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbno1V0pvZDlBUTdqR1NaRmZMaFlXRFNpOVZJUXxBQ3Jtc0trbEpDSnlQUFFMeEFLRjN5Q1c3N1h3ejJ2LWNsbzZzN1VJX09ZTXFQdDR1aUpTekN6NGhRZWZMblg2WUw5VElGS3VQUzNqbzFVY0hwbTFEVVNTZDFFc05fcUFfa3ZzdDFVdUI0a2ZjcDRBY0NmR1ptdw&q=https%3A%2F%2Fstorage.googleapis.com%2Fminikube%2Freleases%2Flatest%2Fminikube-linux-amd64&v=J2sUlm2cwQk) && chmod +x minikube && sudo mv minikube /usr/local/bin/

 Start Minikube
$  apt install conntrack
$  minikube start --vm-driver=none

$https://github.com/Mirantis/cri-dockerd#build-and-install

$  minikube status

but getting these error can you help me on this?

![Capture](https://user-images.githubusercontent.com/64696469/193446980-583c4bb5-f6ca-4aa0-a8d0-8e8dcba1e466.PNG)

### Attach the log file

k

### Operating System

Other

**Comment by afbjorklund** [comment]
You also need to install the `crictl` program.:
https://github.com/kubernetes-sigs/cri-tools

See https://minikube.sigs.k8s.io/docs/drivers/none/
