### ISSUE TITLE
Exiting due to GUEST_START

### ISSUE THREAD

**Issue by ibilalkayy** [kubernetes/minikube#15057]
### What Happened?

Hey there, I am trying to start the minikube but it is giving me the following error.

![Screenshot from 2022-10-03 11-40-35](https://user-images.githubusercontent.com/64713734/193515507-4b8f0bd2-395c-4a3c-8582-ab5018ddfc37.png)

I don't know what is the problem here. I searched a lot but didn't find a solution. I have an attached **log.txt** file also.

Thank you!

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9695167/logs.txt)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by ps68060** [comment]
Have a look at minikube status.  I suspect apiserver hasn't started.

I had to revert to minikube 1.25.1 to get it to work.

**Comment by ibilalkayy** [comment]
How to revert to minikube 1.25.1?

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/14202

**Comment by spowelljr** [comment]
Hi @ibilalkayy, as @afbjorklund pointed out, this is related to using Docker Desktop on Linux as minikube does not yet support it. We have a previously existing issue, please follow along with https://github.com/kubernetes/minikube/issues/14202 for developments.
