### ISSUE TITLE
minikube failed to start

### ISSUE THREAD

**Issue by SubhanshuMG** [kubernetes/minikube#15051]
### What Happened?

😄  minikube v1.27.0 on Ubuntu 22.04
❗  Kubernetes 1.25.0 has a known issue with resolv.conf. minikube is using a workaround that should work for most use cases.
❗  For more information, see: https://github.com/kubernetes/kubernetes/issues/112135
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh, qemu2 (experimental)
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > gcr.io/k8s-minikube/kicbase:  0 B [_________________________] ?% ? p/s 0s
    > index.docker.io/kicbase/sta...:  0 B [______________________] ?% ? p/s 0s
    > gcr.io/k8s-minikube/kicbase...:  0 B [______________________] ?% ? p/s 0s
    > index.docker.io/kicbase/sta...:  0 B [______________________] ?% ? p/s 0s
❗  minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.34, but successfully downloaded docker.io/kicbase/stable:v0.0.34 as a fallback image
E1002 17:28:01.686138   30129 cache.go:203] Error downloading kic artifacts:  failed to download kic base image or any fallback image
🔥  Creating docker container (CPUs=2, Memory=2761MB) ...
🐳  Preparing Kubernetes v1.25.0 on Docker 20.10.17 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...| E1002 17:31:34.071498   30129 start.go:267] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.49.2:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 192.168.49.2:8443: i/o timeout]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition

---

> `minikube status`
> -apiserver: stopped

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9692440/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Probably related to using Docker Desktop, instead of Docker Engine:

* https://github.com/kubernetes/minikube/issues/14202

**Comment by klaases** [comment]
Hi @SubhanshuMG, did you have a chance to review the comment above?

> Probably related to using Docker Desktop, instead of Docker Engine:
> https://github.com/kubernetes/minikube/issues/14202
