### ISSUE TITLE
How to properly install the minikube on fedora?

### ISSUE THREAD

**Issue by ibilalkayy** [kubernetes/minikube#15068]
### What Happened?

For two days, I am trying to install minikube but every time I run `minikube start`, it gives me an error that I don't understand. I am new and I read many blogs and official documents but still didn't solve it. I have installed docker, kubectl, kubeadm, kubelet, conntrack, and minikube.

![Screenshot from 2022-10-04 21-06-30](https://user-images.githubusercontent.com/64713734/193869759-dbd25370-bd60-46b0-b46a-bd13cc503447.png)

### Attach the log file

Here is the log.txt file

[logs.txt](https://github.com/kubernetes/minikube/files/9708715/logs.txt)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by tcchawla** [comment]
Hello @ibilalkayy try this command before starting `minikube delete --all --purge`. Hope this helps.

**Comment by afbjorklund** [comment]
Docker Desktop is not yet supported by minikube on Linux

* https://github.com/kubernetes/minikube/issues/14202
