### ISSUE TITLE
minikube virtualisation

### ISSUE THREAD

**Issue by Koushik8142** [kubernetes/minikube#15067]
though virtualisation is enabled but it was showing not enabled while installing minikube

**Comment by RA489** [comment]
@Koushik8142 I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by Koushik8142** [comment]
while installing minikube it was showing virtualization is disabled, if you are running within a virtual machine, try '--driver docker'. Otherwise consult your bios manual for how to enable virtualization 

 even though  I enabled virtualization it was showing like these while installing minikube

**Comment by klaases** [comment]
Hi @Koushik8142 could you provide an example for:

> it was showing not enabled while installing minikube

Thank you for sharing your experience! If you don't mind, could you provide minikube logs?

Please attach (drag) the`logs.txt` file to this issue  which can be generated by running this command:

```
$ minikube logs --file=logs.txt
```` 

This will help us isolate the problem further. Thank you!

/kind support
