### ISSUE TITLE
minikube status take long time when paused on docker driver

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15076]
### What Happened?

Quoting from Chris

" I've also noticed that when my cluster is paused, `minikube status` runs much more slowly. If the cluster is stopped, it takes around 0.15 seconds. If started, about 0.25 seconds. But if paused, it's more like 16 seconds. "

### Driver

Docker Driver

**Comment by spowelljr** [comment]
This seems to be specific to Docker driver. I tried HyperKit and KVM and for both of them the apiserver status is `Paused` and the status call is instant. On Docker it keeps trying to curl the apiserver and the call fails and it keeps retrying, hence why it takes so long.

The VM drivers, it uses the freezer gcroup to detect the status:
`freezer state: "FROZEN"`
But with Docker:
`unable to find freezer cgroup: sudo egrep ^[0-9]+:freezer: /proc/1821/cgroup: Process exited with status 1`
So then it tries doing the HTTP curls which makes the call take a long time.
