### ISSUE TITLE
Mac M1 invalid accelerator hvf 

### ISSUE THREAD

**Issue by AJ1058310** [kubernetes/minikube#15093]
### What Happened?

Failed to run cmd :
`minikube start --driver=qemu2 --qemu-firmware-path=/usr/local/bin/qemu-system-aarch64
`
Got Error:
`I1009 20:56:20.978890   18356 main.go:134] libmachine: STDERR: qemu-system-aarch64: -accel hvf: invalid accelerator hvf`

See details in:
[log_with_flag_alsologtostderr.txt](https://github.com/kubernetes/minikube/files/9742356/log_with_flag_alsologtostderr.txt)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9742354/logs.txt)

### Operating System

macOS M1

### Driver

_qemu2_

**Comment by spowelljr** [comment]
Hi @AJ1058310, it looks like you may be using the `--qemu-firmware-path` incorrectly. The value will usually be something like `/opt/homebrew/Cellar/qemu/7.1.0/share/qemu/edk2-aarch64-code.fd`. It looks like you want to overwrite `qemu-system-aarch64`, is that correct?

**Comment by bskiefer** [comment]
This worked for me: https://github.com/lima-vm/lima/issues/713#issuecomment-1072613761

**Comment by medyagh** [comment]
@AJ1058310 does this fix your problem as well ? https://github.com/kubernetes/minikube/issues/15093#issuecomment-1410708354
