### ISSUE TITLE
Katakoda is using a very old minikube v1.18

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15097]
### What Happened?

the katakoda on Kubernetes website is using a very old minikube and it needs to be updated. 
if anyone can give a hand in finding out how to update it, this task is available to be picked up

https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by afbjorklund** [comment]
More details:

* https://github.com/kubernetes/minikube/issues/14228

**Comment by nikitar** [comment]
Would this be covered by #37817? I presume any k8s upgrade would also include a minikube upgrade.

**Comment by nikitar** [comment]
Would this be covered by [#37817](https://github.com/kubernetes/website/issues/37817)? I presume any k8s upgrade would also include a minikube upgrade.

**Comment by afbjorklund** [comment]
Sure, it is the same task.

I still think it would be a good idea to have solution that could run both in a cloud provider as well as in your own laptop. There is also room for alternative scenarios such as multi-node, as a step two. Especially now when they can share one VM (running two node containers)

**Comment by afbjorklund** [comment]
Except for some quirks, this is an approximation of an updated UI:

![browser-minikube](https://user-images.githubusercontent.com/10364051/206979923-4f5c3d39-0d92-4620-9b6b-291afdb80773.png)

As compared with the one that is currently in the releate notes/tutorials:

![hello-minikube](https://user-images.githubusercontent.com/10364051/206980126-e3b24127-d313-4a41-b96b-fa78caec3514.png)

**Comment by afbjorklund** [comment]
As mentioned before, it would be nice to get rid of all the misleading spam.

**Comment by afbjorklund** [comment]
Happy face, with issues above fixed:

```
😄  minikube v1.28.0 on Ubuntu 22.04 (kvm/amd64)
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=4, Memory=3919MB, Disk=99053MB) ...
ℹ️  OS release is Ubuntu 22.04.1 LTS
📦  Preparing Kubernetes v1.25.3 on containerd 1.6.8 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🤹  Configuring local host environment ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: default-storageclass, storage-provisioner
💡  kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

Still need --preload=false, if not using ISO.

**Comment by afbjorklund** [comment]
I think that SIG Docs is still trying to find alternative hosting, before Katacoda shuts down (tomorrow)

* https://github.com/kubernetes/website/issues/33936#issuecomment-1357005866

It is not clear if there will be a new deployment of the old version (1.18), or of the new version (1.28) ?

There is support for Kubernetes in Killercoda, but I don't think that it is using minikube ? (just kubeadm)

**Comment by afbjorklund** [comment]
Made separate issues for the output spam:

* #15576 
* #15577

See https://github.com/kubernetes/minikube/issues/15097#issuecomment-1345982947

It will still complain about "none", and about containerd.

But those can be worked around or fixed, and are not _bugs_.

❗  The 'none' driver is designed for experts who need to integrate with an existing VM

❗  Using the 'containerd' runtime with the 'none' driver is an untested configuration!

Especially ironic since containerd was the _only_ runtime for 1.26.0

The support for Docker and for CRI-O was a bit late, and didn't arrive until some weeks later.

But it is true that it still buggy in minikube, due to it requiring a `docker` binary since forever.

* #10908
* #5549

**Comment by afbjorklund** [comment]
https://kubernetes.io/blog/2023/02/14/kubernetes-katacoda-tutorials-stop-from-2023-03-31/
