### ISSUE TITLE
Not able to install Minikube

### ISSUE THREAD

**Issue by dhaliwalsinghmanpreet** [kubernetes/minikube#15092]
### What Happened?

Trying to install Minikube by referencing https://minikube.sigs.k8s.io/docs/start/ 
but not able to install it.
System details
Ubuntu 20.04.5 LTS 
Intel® Core™ i7-6700 CPU @ 3.40GHz × 8, Mesa Intel® HD Graphics 530 (SKL GT2)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9740104/logs.txt)

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/14202
