### ISSUE TITLE
cri-docker cannot started after stop and start minikube again 

### ISSUE THREAD

**Issue by marverlous811** [kubernetes/minikube#15096]
### What Happened?

● cri-docker.service - CRI Interface for Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/cri-docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/cri-docker.service.d
           └─10-cni.conf
   Active: failed (Result: exit-code) since Mon 2022-10-10 11:52:07 UTC; 34s ago
     Docs: https://docs.mirantis.com
  Process: 1837 ExecStart=/usr/bin/cri-dockerd --container-runtime-endpoint fd:// --network-plugin=cni --cni-bin-dir=/opt/cni/bin --cni-cache-dir=/var/lib/cn
 Main PID: 1837 (code=exited, status=203/EXEC)

Oct 10 11:52:07 ubuntu-18 systemd[1]: cri-docker.service: Service hold-off time over, scheduling restart.
Oct 10 11:52:07 ubuntu-18 systemd[1]: cri-docker.service: Scheduled restart job, restart counter is at 3.
Oct 10 11:52:07 ubuntu-18 systemd[1]: Stopped CRI Interface for Docker Application Container Engine.
Oct 10 11:52:07 ubuntu-18 systemd[1]: cri-docker.service: Start request repeated too quickly.
Oct 10 11:52:07 ubuntu-18 systemd[1]: cri-docker.service: Failed with result 'exit-code'.
Oct 10 11:52:07 ubuntu-18 systemd[1]: Failed to start CRI Interface for Docker Application Container Engine.

### Attach the log file

* 
* ==> Audit <==
* |---------|--------------------------------|----------|------|---------|---------------------|----------|
| Command |              Args              | Profile  | User | Version |     Start Time      | End Time |
|---------|--------------------------------|----------|------|---------|---------------------|----------|
| start   | --network-plugin=cni           | minikube | root | v1.27.1 | 10 Oct 22 11:02 UTC |          |
|         | --cni=calico --driver=none     |          |      |         |                     |          |
| start   | --network-plugin=cni           | minikube | root | v1.27.1 | 10 Oct 22 11:03 UTC |          |
|         | --cni=calico --driver=none     |          |      |         |                     |          |
| start   | --network-plugin=cni           | minikube | root | v1.27.1 | 10 Oct 22 11:50 UTC |          |
|         | --cni=calico --driver=none     |          |      |         |                     |          |
| start   | --network-plugin=cni           | minikube | root | v1.27.1 | 10 Oct 22 11:53 UTC |          |
|         | --cni=calico --driver=none     |          |      |         |                     |          |
|---------|--------------------------------|----------|------|---------|---------------------|----------|

* 
* ==> Last Start <==
* Log file created at: 2022/10/10 11:53:11
Running on machine: ubuntu-18
Binary: Built with gc go1.19.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1010 11:53:11.179979    2431 out.go:296] Setting OutFile to fd 1 ...
I1010 11:53:11.180934    2431 out.go:348] isatty.IsTerminal(1) = true
I1010 11:53:11.180938    2431 out.go:309] Setting ErrFile to fd 2...
I1010 11:53:11.180943    2431 out.go:348] isatty.IsTerminal(2) = true
I1010 11:53:11.181047    2431 root.go:333] Updating PATH: /root/.minikube/bin
W1010 11:53:11.182075    2431 root.go:310] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I1010 11:53:11.183408    2431 out.go:303] Setting JSON to false
I1010 11:53:11.186047    2431 start.go:116] hostinfo: {"hostname":"ubuntu-18","uptime":83,"bootTime":1665402708,"procs":132,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"4.15.0-29-generic","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"422eb94b-83fd-d64c-d671-3b8f1f661c31"}
I1010 11:53:11.186106    2431 start.go:126] virtualization:  
I1010 11:53:11.187791    2431 out.go:177] 😄  minikube v1.27.1 on Ubuntu 18.04
I1010 11:53:11.206471    2431 notify.go:220] Checking for updates...
I1010 11:53:11.207315    2431 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.25.2
W1010 11:53:11.207852    2431 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I1010 11:53:11.208063    2431 exec_runner.go:51] Run: systemctl --version
I1010 11:53:11.214814    2431 driver.go:362] Setting default libvirt URI to qemu:///system
I1010 11:53:11.216373    2431 out.go:177] ✨  Using the none driver based on existing profile
I1010 11:53:11.225184    2431 start.go:282] selected driver: none
I1010 11:53:11.225192    2431 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI:calico NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:171.244.50.32 Port:8443 KubernetesVersion:v1.25.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1010 11:53:11.225305    2431 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I1010 11:53:11.225341    2431 start.go:1568] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I1010 11:53:11.225995    2431 cni.go:95] Creating CNI manager for "calico"
I1010 11:53:11.233371    2431 start_flags.go:317] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI:calico NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:171.244.50.32 Port:8443 KubernetesVersion:v1.25.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1010 11:53:11.234754    2431 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I1010 11:53:11.244361    2431 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I1010 11:53:11.253703    2431 cache.go:208] Successfully downloaded all kic artifacts
I1010 11:53:11.253726    2431 start.go:364] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I1010 11:53:11.253850    2431 start.go:368] acquired machines lock for "minikube" in 105.855µs
I1010 11:53:11.253863    2431 start.go:96] Skipping create...Using existing machine configuration
I1010 11:53:11.253867    2431 fix.go:55] fixHost starting: m01
W1010 11:53:11.256776    2431 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I1010 11:53:11.256784    2431 api_server.go:165] Checking apiserver status ...
I1010 11:53:11.256830    2431 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W1010 11:53:11.290840    2431 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I1010 11:53:11.290883    2431 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I1010 11:53:11.298170    2431 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W1010 11:53:11.298182    2431 fix.go:129] unexpected machine state, will restart: <nil>
I1010 11:53:11.299934    2431 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I1010 11:53:11.311082    2431 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I1010 11:53:11.311199    2431 start.go:300] post-start starting for "minikube" (driver="none")
I1010 11:53:11.311261    2431 start.go:328] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I1010 11:53:11.311296    2431 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I1010 11:53:11.330038    2431 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I1010 11:53:11.330054    2431 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I1010 11:53:11.330063    2431 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I1010 11:53:11.332206    2431 out.go:177] ℹ️  OS release is Ubuntu 18.04 LTS
I1010 11:53:11.341360    2431 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I1010 11:53:11.341414    2431 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I1010 11:53:11.341441    2431 start.go:303] post-start completed in 30.23523ms
I1010 11:53:11.341448    2431 fix.go:57] fixHost completed within 87.581715ms
I1010 11:53:11.341451    2431 start.go:83] releasing machines lock for "minikube", held for 87.596023ms
I1010 11:53:11.341955    2431 exec_runner.go:51] Run: sudo mkdir -p /etc/systemd/system/cri-docker.service.d
I1010 11:53:11.350114    2431 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
I1010 11:53:11.350236    2431 exec_runner.go:144] found /etc/systemd/system/cri-docker.service.d/10-cni.conf, removing ...
I1010 11:53:11.350247    2431 exec_runner.go:207] rm: /etc/systemd/system/cri-docker.service.d/10-cni.conf
I1010 11:53:11.350704    2431 exec_runner.go:151] cp: memory --> /etc/systemd/system/cri-docker.service.d/10-cni.conf (233 bytes)
I1010 11:53:11.350816    2431 exec_runner.go:51] Run: sudo cp -a /tmp/minikube3496247821 /etc/systemd/system/cri-docker.service.d/10-cni.conf
I1010 11:53:11.375199    2431 exec_runner.go:51] Run: sudo systemctl daemon-reload
I1010 11:53:11.609006    2431 exec_runner.go:51] Run: sudo systemctl restart cri-docker
I1010 11:53:11.625502    2431 out.go:177] 
W1010 11:53:11.634273    2431 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: sudo systemctl restart cri-docker: exit status 1
stdout:

stderr:
Job for cri-docker.service failed because the control process exited with error code.
See "systemctl status cri-docker.service" and "journalctl -xe" for details.

W1010 11:53:11.634300    2431 out.go:239] 
W1010 11:53:11.635051    2431 out.go:239] [31m╭───────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                             [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯[0m
I1010 11:53:11.643298    2431 out.go:177] 

* 

### Operating System

Ubuntu

**Comment by afbjorklund** [comment]
Weirdly, it seems to be missing an "i" in cni ?

`--cni-bin-dir=/opt/cni/bin --cni-cache-dir=/var/lib/cn`

**Comment by marverlous811** [comment]
> Weirdly, it seems to be missing an "i" in cni ?
> 
> `--cni-bin-dir=/opt/cni/bin --cni-cache-dir=/var/lib/cn`
> 
> Looks like the override file got truncated

I don't think that is the problem, because of i already have started it without any error yet. But after I stoped minikube or restarted the server, I always got this error. For some reason, my system can't start the cri-dockered again

**Comment by afbjorklund** [comment]
OK, maybe you pasted half the line or something. Can you run the comman directly (as root), from the ExecStart ?

It might give some better output, especially if you also add the `--log-level debug` options to the end of `cri-dockerd`

**Comment by tuanaac** [comment]
I'm facing the same issue with minikube version 1.28.0. Any updates for this issue. Thank you.

**Comment by tuanaac** [comment]
@marverlous811 I think I found the root cause. When I start minikube with `minikube start --driver=none --network-plugin=cni --cni=bridge`, then minikube creates the folder `/etc/systemd/system/cri-docker.service.d` containing a cni-config file (if it does not exist). This file contains the path `/usr/bin/cri-dockerd` used by systemd to start the service.

![image](https://user-images.githubusercontent.com/88043957/214164354-d57919b3-f111-4692-9583-b18f407946b8.png)![image](https://user-images.githubusercontent.com/88043957/214161415-4d0a26d6-c410-4ffb-a41e-a193543f6b22.png)

And I assume that you also followed the official guide to install cri-dockerd, where the executable file `cri-dockerd` is actually moved to `/usr/local/bin` (https://github.com/Mirantis/cri-dockerd#build-and-install). That is the reason why cri-dockerd.service cannot be started. 
![image](https://user-images.githubusercontent.com/88043957/214159177-31a7ad82-b29f-4d9b-a36f-4804a961a7a7.png)

To resolve this issue, I copied the executable file `cri-dockerd` to `/usr/bin`: `sudo cp /usr/local/bin/cri-dockerd /usr/bin/` 
After that minikube can start normally. I hope this answer helps you.

@afbjorklund I would like to ask you a question. Should minikube takes the path to `cri-dockerd` from `/etc/systemd/system/cri-docker.service`?

![image](https://user-images.githubusercontent.com/88043957/214165999-f3686797-7465-4d1e-827f-e830965b23af.png)
