### ISSUE TITLE
Is it possible to select network interface(eth0, eth1, ens192 etc.) in none driver?

### ISSUE THREAD

**Issue by m18unet** [kubernetes/minikube#15102]
### What Happened?

I have two network interfaces on my computer. Their names are `eth0` and `eth1`. 

```
+--------------------------------------------------+
|                     My Computer                  |
|                                                  |
|  eth0                                       eth1 |
|   +                                          +   |
+--------------------------------------------------+
    |                                          |
    |                                          |
    |                                          |
    |                                          |
    v                                          v
10.10.22.50                               192.168.29.50
(minikube selects it automatically)       (I want you to select this)
```

`eth0` network interface is **selected automatically** when I start minikube with the following command: _(I prefer `none` driver for some special reasons.)_

``` bash
$ sudo -E minikube start \
  --driver=none \
  --kubernetes-version=1.24.3 \
  --container-runtime=docker \
```

```bash
$ minikube ip
10.10.22.50
```

I want to select `eth1` network interface(`192.168.29.50`). Is this possible?

### Attach the log file

N/A

### Operating System

Ubuntu

### Driver

`--driver=none`

**Comment by vonProteus** [comment]
I would also like to know the answer to this question

**Comment by afbjorklund** [comment]
Currently the node IP comes from `ChooseHostInterface`, which I think think chooses the one with the gateway.

https://pkg.go.dev/k8s.io/apimachinery@v0.25.3/pkg/util/net#ChooseHostInterface

In the original docker-machine, it was a flag (confusingly called `--url`)

**Comment by m18unet** [comment]
> I would also like to know the answer to this question
> @m18unet did you find a solution to this problem?

@vonProteus

Unfortunately, I couldn't find a solution.

**Comment by m18unet** [comment]
> Currently the node IP comes from `ChooseHostInterface`, which I think chooses the one with the gateway.
> 
> ```go
> // GetIP returns an IP or hostname that this host is available at
> func (d *Driver) GetIP() (string, error) {
>         ip, err := knet.ChooseHostInterface()
>         if err != nil {
>                 return "", err
>         }
>         return ip.String(), nil
> }
> ```
> 
> https://pkg.go.dev/k8s.io/apimachinery@v0.25.3/pkg/util/net#ChooseHostInterface
> 
> In the original docker-machine, it was a flag (confusingly called `--url`)

@afbjorklund 

Thank you very much for your reply. I don't think there is a solution for now. Am I right?

**Comment by afbjorklund** [comment]
Only workarounds*, as far as I know. All flags are hardcoded in the minikube "registry"

* https://github.com/kubernetes/minikube/issues/14035

* https://github.com/kubernetes/minikube/blob/master/pkg/minikube/registry/drvs/none/none.go

So it needs to have a new flag for the `IP`, and then propagate that to the "none2" driver.

**Comment by m18unet** [comment]
Anything worth noting?
