### ISSUE TITLE
Registry mirror doesn't work with xhyve

### ISSUE THREAD

**Issue by zzq889** [kubernetes/minikube#1512]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS Sierra 10.12.4 (16E195)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.18.0
- **Install tools**: Homebrew
- **Others**:

**What happened**:
I start minikube with following command
```
minikube start --vm-driver=xhyve --registry-mirror="https://<my-registry-domain>"
```
but `Registry Mirror` is not set correctly.

```
$ docker info
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.11.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge null host
Kernel Version: 4.7.2
Operating System: Buildroot 2016.08
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.954 GiB
Name: minikube
ID: 37RE:O4JW:JKCC:C6NB:3R3H:RWO4:NHGM:EK22:PL3M:2YT7:7MRK:EBQ6
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=xhyve
```

**What you expected to happen**:
`Registry Mirror` should appear in the docker info.

**How to reproduce it** (as minimally and precisely as possible):

```
minikube delete
minikube start --vm-driver=xhyve --registry-mirror="https://<my-registry-domain>"
```

**Anything else do we need to know**:

**Comment by tz70s** [comment]
Hi @zzq889 @aaron-prindle 
Same problem for me.
Seems like it is not a problem from xhyve, the registry-mirror doesn't appear in the docker info whether  using virtualbox, xhyve, kvm.
Not sure this flag works in Docker v1.11, but I can successfully produce the result in Docker v1.7^.
