### ISSUE TITLE
Add cloud-spanner emulator as a minikube add on 

### ISSUE THREAD

**Issue by agarwalnit** [kubernetes/minikube#15138]
### What Happened?

We are working on to use minikube as an end to end test environment. As part of test environment, we depend on cloud services and would like to offer emulators for the same. 

Bundling emulator as part of minikube provide reusability across the teams. 

### Attach the log file

None.

**Comment by spowelljr** [comment]
Completed in https://github.com/kubernetes/minikube/pull/15160
