### ISSUE TITLE
start error

### ISSUE THREAD

**Issue by pratheek2shiva** [kubernetes/minikube#15134]
### What Happened?

minikube single node cluster is not getting started

### Attach the log file

==> Audit <==
|------------|-------------------|----------|------|---------|---------------------|---------------------|
|  Command   |       Args        | Profile  | User | Version |     Start Time      |      End Time       |
|------------|-------------------|----------|------|---------|---------------------|---------------------|
| start      |                   | minikube | user | v1.27.1 | 13 Oct 22 16:06 IST |                     |
| start      |                   | minikube | user | v1.27.1 | 13 Oct 22 16:16 IST |                     |
| dashboard  |                   | minikube | user | v1.27.1 | 13 Oct 22 16:25 IST |                     |
| docker-env |                   | minikube | user | v1.27.1 | 13 Oct 22 16:57 IST |                     |
| start      |                   | minikube | user | v1.27.1 | 14 Oct 22 10:00 IST |                     |
| dashboard  |                   | minikube | user | v1.27.1 | 14 Oct 22 10:14 IST |                     |
| dashboard  |                   | minikube | user | v1.27.1 | 14 Oct 22 10:16 IST |                     |
| start      |                   | minikube | user | v1.27.1 | 14 Oct 22 10:16 IST |                     |
| start      |                   | minikube | user | v1.27.1 | 14 Oct 22 13:45 IST |                     |
| start      |                   | minikube | user | v1.27.1 | 14 Oct 22 15:00 IST |                     |
| start      |                   | minikube | user | v1.27.1 | 14 Oct 22 15:01 IST |                     |
| delete     |                   | minikube | user | v1.27.1 | 14 Oct 22 15:14 IST | 14 Oct 22 15:14 IST |
| start      | --driver hyperkit | minikube | user | v1.27.1 | 14 Oct 22 15:14 IST |                     |
| delete     |                   | minikube | user | v1.27.1 | 14 Oct 22 15:17 IST | 14 Oct 22 15:17 IST |
| start      |                   | minikube | user | v1.27.1 | 14 Oct 22 15:42 IST |                     |
| dashboard  |                   | minikube | user | v1.27.1 | 14 Oct 22 15:53 IST |                     |
|------------|-------------------|----------|------|---------|---------------------|---------------------|

==> Last Start <==
Log file created at: 2022/10/14 15:42:12
Running on machine: IND040100043
Binary: Built with gc go1.19.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1014 15:42:12.391255   36140 out.go:296] Setting OutFile to fd 1 ...
I1014 15:42:12.391725   36140 out.go:348] isatty.IsTerminal(1) = true
I1014 15:42:12.391729   36140 out.go:309] Setting ErrFile to fd 2...
I1014 15:42:12.391738   36140 out.go:348] isatty.IsTerminal(2) = true
I1014 15:42:12.391923   36140 root.go:333] Updating PATH: /home/user/.minikube/bin
I1014 15:42:12.394315   36140 out.go:303] Setting JSON to false
I1014 15:42:12.414995   36140 start.go:116] hostinfo: {"hostname":"IND040100043","uptime":33506,"bootTime":1665708826,"procs":282,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.0-48-generic","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"3545b64f-ed3b-463e-bc8b-28ed40d22a90"}
I1014 15:42:12.415063   36140 start.go:126] virtualization: kvm host
I1014 15:42:12.491036   36140 out.go:177] 😄  minikube v1.27.1 on Ubuntu 22.04
I1014 15:42:12.558155   36140 notify.go:220] Checking for updates...
I1014 15:42:12.558238   36140 driver.go:362] Setting default libvirt URI to qemu:///system
I1014 15:42:12.558275   36140 global.go:111] Querying for installed drivers using PATH=/home/user/.minikube/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/user/.rvm/bin:/home/user/.rvm/bin
I1014 15:42:12.597787   36140 global.go:119] none default: false priority: 4, state: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I1014 15:42:12.597931   36140 global.go:119] podman default: true priority: 7, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "podman": executable file not found in $PATH Reason: Fix:Install Podman Doc:https://minikube.sigs.k8s.io/docs/drivers/podman/ Version:}
I1014 15:42:12.598017   36140 global.go:119] qemu2 default: true priority: 3, state: {Installed:true Healthy:true Running:true NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I1014 15:42:12.598054   36140 global.go:119] ssh default: false priority: 4, state: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I1014 15:42:12.598170   36140 global.go:119] virtualbox default: true priority: 6, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:unable to find VBoxManage in $PATH Reason: Fix:Install VirtualBox Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/ Version:}
I1014 15:42:12.598257   36140 global.go:119] vmware default: true priority: 7, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "docker-machine-driver-vmware": executable file not found in $PATH Reason: Fix:Install docker-machine-driver-vmware Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/ Version:}
I1014 15:42:12.691212   36140 docker.go:137] docker version: linux-20.10.17
I1014 15:42:12.691308   36140 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I1014 15:42:13.002032   36140 info.go:265] docker info: {ID:BYKJ:WOFS:C2MT:XAAM:LPEY:BQQD:FZZC:7FF4:2Z5H:QRYD:VEKX:BURZ Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:0 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:48 OomKillDisable:false NGoroutines:53 SystemTime:2022-10-14 10:12:12.774143523 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:7 KernelVersion:5.10.124-linuxkit OperatingSystem:Docker Desktop OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:2 MemTotal:3991531520 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy:http.docker.internal:3128 HTTPSProxy:http.docker.internal:3128 NoProxy:hubproxy.docker.internal Name:docker-desktop Labels:[] ExperimentalBuild:false ServerVersion:20.10.17 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6 Expected:9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6} RuncCommit:{ID:v1.1.4-0-g5fd4c4d Expected:v1.1.4-0-g5fd4c4d} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Experimental:true Name:app Path:/usr/libexec/docker/cli-plugins/docker-app SchemaVersion:0.1.0 ShortDescription:Docker App Vendor:Docker Inc. Version:v0.9.1-beta3] map[Name:buildx Path:/usr/libexec/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.9.1-docker] map[Name:compose Path:/usr/lib/docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShadowedPaths:[/usr/libexec/docker/cli-plugins/docker-compose] ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.10.2] map[Name:extension Path:/usr/lib/docker/cli-plugins/docker-extension SchemaVersion:0.1.0 ShortDescription:Manages Docker extensions Vendor:Docker Inc. Version:v0.2.9] map[Name:sbom Path:/usr/lib/docker/cli-plugins/docker-sbom SchemaVersion:0.1.0 ShortDescription:View the packaged-based Software Bill Of Materials (SBOM) for an image URL:https://github.com/docker/sbom-cli-plugin Vendor:Anchore Inc. Version:0.6.0] map[Name:scan Path:/usr/lib/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShadowedPaths:[/usr/libexec/docker/cli-plugins/docker-scan] ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.19.0]] Warnings:<nil>}}
I1014 15:42:13.002184   36140 docker.go:254] overlay module found
I1014 15:42:13.002193   36140 global.go:119] docker default: true priority: 9, state: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I1014 15:42:13.002291   36140 global.go:119] kvm2 default: true priority: 8, state: {Installed:false Healthy:false Running:false NeedsImprovement:false Error:exec: "virsh": executable file not found in $PATH Reason: Fix:Install libvirt Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/ Version:}
I1014 15:42:13.002315   36140 driver.go:297] not recommending "none" due to default: false
I1014 15:42:13.002322   36140 driver.go:297] not recommending "ssh" due to default: false
I1014 15:42:13.002328   36140 driver.go:302] not recommending "qemu2" due to priority: 3
I1014 15:42:13.002343   36140 driver.go:332] Picked: docker
I1014 15:42:13.002348   36140 driver.go:333] Alternatives: [none ssh qemu2 (experimental)]
I1014 15:42:13.002356   36140 driver.go:334] Rejects: [podman virtualbox vmware kvm2]
I1014 15:42:13.080428   36140 out.go:177] ✨  Automatically selected the docker driver. Other choices: none, ssh, qemu2 (experimental)
I1014 15:42:13.125223   36140 start.go:282] selected driver: docker
I1014 15:42:13.125232   36140 start.go:808] validating driver "docker" against <nil>
I1014 15:42:13.125253   36140 start.go:819] status for docker: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I1014 15:42:13.125346   36140 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I1014 15:42:13.410796   36140 info.go:265] docker info: {ID:BYKJ:WOFS:C2MT:XAAM:LPEY:BQQD:FZZC:7FF4:2Z5H:QRYD:VEKX:BURZ Containers:0 ContainersRunning:0 ContainersPaused:0 ContainersStopped:0 Images:0 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:48 OomKillDisable:false NGoroutines:53 SystemTime:2022-10-14 10:12:13.206949717 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:7 KernelVersion:5.10.124-linuxkit OperatingSystem:Docker Desktop OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:2 MemTotal:3991531520 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy:http.docker.internal:3128 HTTPSProxy:http.docker.internal:3128 NoProxy:hubproxy.docker.internal Name:docker-desktop Labels:[] ExperimentalBuild:false ServerVersion:20.10.17 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6 Expected:9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6} RuncCommit:{ID:v1.1.4-0-g5fd4c4d Expected:v1.1.4-0-g5fd4c4d} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Experimental:true Name:app Path:/usr/libexec/docker/cli-plugins/docker-app SchemaVersion:0.1.0 ShortDescription:Docker App Vendor:Docker Inc. Version:v0.9.1-beta3] map[Name:buildx Path:/usr/libexec/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.9.1-docker] map[Name:compose Path:/usr/lib/docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShadowedPaths:[/usr/libexec/docker/cli-plugins/docker-compose] ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.10.2] map[Name:extension Path:/usr/lib/docker/cli-plugins/docker-extension SchemaVersion:0.1.0 ShortDescription:Manages Docker extensions Vendor:Docker Inc. Version:v0.2.9] map[Name:sbom Path:/usr/lib/docker/cli-plugins/docker-sbom SchemaVersion:0.1.0 ShortDescription:View the packaged-based Software Bill Of Materials (SBOM) for an image URL:https://github.com/docker/sbom-cli-plugin Vendor:Anchore Inc. Version:0.6.0] map[Name:scan Path:/usr/lib/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShadowedPaths:[/usr/libexec/docker/cli-plugins/docker-scan] ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.19.0]] Warnings:<nil>}}
I1014 15:42:13.410961   36140 start_flags.go:303] no existing cluster config was found, will generate one from the flags 
I1014 15:42:13.430124   36140 start_flags.go:384] Using suggested 3758MB memory alloc based on sys=15866MB, container=3806MB
I1014 15:42:13.430257   36140 start_flags.go:867] Wait components to verify : map[apiserver:true system_pods:true]
I1014 15:42:13.514254   36140 out.go:177] 📌  Using Docker driver with root privileges
I1014 15:42:13.603322   36140 cni.go:95] Creating CNI manager for ""
I1014 15:42:13.603358   36140 cni.go:169] CNI unnecessary in this configuration, recommending no CNI
I1014 15:42:13.603367   36140 start_flags.go:317] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b Memory:3758 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/home/user:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1014 15:42:13.714626   36140 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I1014 15:42:13.770307   36140 cache.go:120] Beginning downloading kic base image for docker with docker
I1014 15:42:13.859319   36140 out.go:177] 🚜  Pulling base image ...
I1014 15:42:13.915036   36140 preload.go:132] Checking if preload exists for k8s version v1.25.2 and runtime docker
I1014 15:42:13.915062   36140 image.go:75] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local docker daemon
I1014 15:42:13.915119   36140 preload.go:148] Found local preload: /home/user/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.25.2-docker-overlay2-amd64.tar.lz4
I1014 15:42:13.915127   36140 cache.go:57] Caching tarball of preloaded images
I1014 15:42:13.915649   36140 preload.go:174] Found /home/user/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.25.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I1014 15:42:13.915670   36140 cache.go:60] Finished verifying existence of preloaded tar for  v1.25.2 on docker
I1014 15:42:13.916112   36140 profile.go:148] Saving config to /home/user/.minikube/profiles/minikube/config.json ...
I1014 15:42:13.916130   36140 lock.go:35] WriteFile acquiring /home/user/.minikube/profiles/minikube/config.json: {Name:mk6327333169e91a1071710da22e1494715b6bb7 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I1014 15:42:13.997984   36140 cache.go:147] Downloading gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local cache
I1014 15:42:13.998333   36140 image.go:59] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local cache directory
I1014 15:42:13.998363   36140 image.go:62] Found gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local cache directory, skipping pull
I1014 15:42:13.998398   36140 image.go:103] gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b exists in cache, skipping pull
I1014 15:42:13.998433   36140 cache.go:150] successfully saved gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b as a tarball
I1014 15:42:13.998438   36140 cache.go:161] Loading gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b from local cache
I1014 15:42:14.134257   36140 cache.go:170] Downloading gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local daemon
I1014 15:42:14.134559   36140 image.go:75] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local docker daemon
I1014 15:42:14.216636   36140 image.go:243] Writing gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local daemon
I1014 15:42:16.563470   36140 cache.go:182] failed to download gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b, will try fallback image if available: writing daemon image: error loading image: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/images/load?quiet=0": dial unix /var/run/docker.sock: connect: permission denied
I1014 15:42:16.563503   36140 image.go:75] Checking for docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local docker daemon
I1014 15:42:16.685187   36140 cache.go:147] Downloading docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local cache
I1014 15:42:16.685488   36140 image.go:59] Checking for docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local cache directory
I1014 15:42:16.685537   36140 image.go:62] Found docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local cache directory, skipping pull
I1014 15:42:16.685544   36140 image.go:103] docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b exists in cache, skipping pull
I1014 15:42:16.685564   36140 cache.go:150] successfully saved docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b as a tarball
I1014 15:42:16.685582   36140 cache.go:161] Loading docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b from local cache
I1014 15:42:16.687435   36140 cache.go:170] Downloading docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local daemon
I1014 15:42:16.687615   36140 image.go:75] Checking for docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local docker daemon
I1014 15:42:16.780868   36140 image.go:243] Writing docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local daemon
I1014 15:42:38.872058   36140 cache.go:182] failed to download docker.io/kicbase/stable:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b, will try fallback image if available: writing daemon image: error loading image: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/images/load?quiet=0": dial unix /var/run/docker.sock: connect: permission denied
I1014 15:42:38.872088   36140 image.go:75] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35 in local docker daemon
I1014 15:42:38.957519   36140 cache.go:147] Downloading gcr.io/k8s-minikube/kicbase:v0.0.35 to local cache
I1014 15:42:38.957859   36140 image.go:59] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35 in local cache directory
I1014 15:42:38.957877   36140 image.go:62] Found gcr.io/k8s-minikube/kicbase:v0.0.35 in local cache directory, skipping pull
I1014 15:42:38.957882   36140 image.go:103] gcr.io/k8s-minikube/kicbase:v0.0.35 exists in cache, skipping pull
I1014 15:42:38.957902   36140 cache.go:150] successfully saved gcr.io/k8s-minikube/kicbase:v0.0.35 as a tarball
I1014 15:42:38.957908   36140 cache.go:161] Loading gcr.io/k8s-minikube/kicbase:v0.0.35 from local cache
I1014 15:42:38.960074   36140 cache.go:170] Downloading gcr.io/k8s-minikube/kicbase:v0.0.35 to local daemon
I1014 15:42:38.960318   36140 image.go:75] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35 in local docker daemon
I1014 15:42:39.047490   36140 image.go:243] Writing gcr.io/k8s-minikube/kicbase:v0.0.35 to local daemon
I1014 15:42:40.526606   36140 cache.go:182] failed to download gcr.io/k8s-minikube/kicbase:v0.0.35, will try fallback image if available: writing daemon image: error loading image: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/images/load?quiet=0": dial unix /var/run/docker.sock: connect: permission denied
I1014 15:42:40.526622   36140 image.go:75] Checking for docker.io/kicbase/stable:v0.0.35 in local docker daemon
I1014 15:42:40.608962   36140 cache.go:147] Downloading docker.io/kicbase/stable:v0.0.35 to local cache
I1014 15:42:40.609284   36140 image.go:59] Checking for docker.io/kicbase/stable:v0.0.35 in local cache directory
I1014 15:42:40.609296   36140 image.go:62] Found docker.io/kicbase/stable:v0.0.35 in local cache directory, skipping pull
I1014 15:42:40.609300   36140 image.go:103] docker.io/kicbase/stable:v0.0.35 exists in cache, skipping pull
I1014 15:42:40.609320   36140 cache.go:150] successfully saved docker.io/kicbase/stable:v0.0.35 as a tarball
I1014 15:42:40.609327   36140 cache.go:161] Loading docker.io/kicbase/stable:v0.0.35 from local cache
I1014 15:42:40.609644   36140 cache.go:170] Downloading docker.io/kicbase/stable:v0.0.35 to local daemon
I1014 15:42:40.609843   36140 image.go:75] Checking for docker.io/kicbase/stable:v0.0.35 in local docker daemon
I1014 15:42:40.696759   36140 image.go:243] Writing docker.io/kicbase/stable:v0.0.35 to local daemon
I1014 15:42:48.524481   36140 cache.go:182] failed to download docker.io/kicbase/stable:v0.0.35, will try fallback image if available: writing daemon image: error loading image: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%!F(MISSING)var%!F(MISSING)run%!F(MISSING)docker.sock/v1.24/images/load?quiet=0": dial unix /var/run/docker.sock: connect: permission denied
W1014 15:42:48.524505   36140 out.go:239] ❗  minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.35, but successfully downloaded docker.io/kicbase/stable:v0.0.35 as a fallback image
E1014 15:42:48.524528   36140 cache.go:203] Error downloading kic artifacts:  failed to download kic base image or any fallback image
I1014 15:42:48.524542   36140 cache.go:208] Successfully downloaded all kic artifacts
I1014 15:42:48.524587   36140 start.go:364] acquiring machines lock for minikube: {Name:mkbd622808407e995359d10389220c8264ecc388 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1014 15:42:48.524979   36140 start.go:368] acquired machines lock for "minikube" in 370.998µs
I1014 15:42:48.525004   36140 start.go:93] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:docker.io/kicbase/stable:v0.0.35 Memory:3758 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.25.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/home/user:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet} &{Name: IP: Port:8443 KubernetesVersion:v1.25.2 ContainerRuntime:docker ControlPlane:true Worker:true}

**Comment by spowelljr** [comment]
Hi @pratheek2shiva, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
