### ISSUE TITLE
Can't start minikube on Windows 10 with HyperV

### ISSUE THREAD

**Issue by foxylion** [kubernetes/minikube#1514]
**Minikube version** (use `minikube version`): v0.19.0

**Environment**:
- **OS**: Windows 10 (1703, 15063.296)
- **VM Driver**): HyperV
- **ISO version**: minikube-v0.18.0.iso
- **Install tools**: -
- **Others**: -

**What happened**:
When trying to start a minikube instance using the HyperV vm driver it will hang indefinitely.

**What you expected to happen**:
minikube should startup normally.

**How to reproduce it** (as minimally and precisely as possible):
- Set up virtual switch (type external network with "allow mangement..." checked)
- Try to start a cluster:
```
minikube start --vm-driver hyperv --hyperv-virtual-switch=Minikube -v=9
```
- Hangs at connecting via SSH (exit status code 255)
- Debugging the SSH command executed by minikube results in the following output:
```
PS C:\Users\jakob> ssh -F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@10.1.1.149 -o IdentitiesOnly=yes -i C:\Users\jakob\.minikube\machines\minikube\id_rsa -p 22 -vvvv
OpenSSH_7.4p1, OpenSSL 1.0.2d 9 Jul 2015
Can't open user config file /dev/null: No such file or directory
```

I checked the host and ssh is up and running, so it is an issue calling the ssh binary.

Here is the full log output: https://gist.github.com/foxylion/4904ec3100fa42b48a766efe0670b383

**Comment by reza-ebrahimi** [comment]
https://github.com/kubernetes/minikube/issues/858#issuecomment-303968863

**Comment by gbraad** [comment]
@reza-ebrahimi These are unrelated issues....

**Comment by sanderkooger** [comment]
I have exactly the same issue with Minishift. Im able to start the box with the extvnet. It picks up an ip. Ssh from commandline is reachable but minishift ssh fails. 

Is there a know solution for the SSH issues under Win10 ?
