### ISSUE TITLE
RSRC_INSUFFICIENT_CONTAINER_MEMORY

### ISSUE THREAD

**Issue by Sajiyah-Salat** [kubernetes/minikube#15142]
### What Happened?

I have started using docker but to use k8s I need to install minikube. I am just a beginner in this field. when I run “minikube start” in the ubuntu terminal I get the following error.

Exiting due to RSRC_INSUFFICIENT_CONTAINER_MEMORY: docker only has 979MiB available, less than the required 1800MiB for Kubernetes
I have researched how to increase container memory. I didn’t get any solution. I have 7 Gb memory and 900+gb of hard disk

### Attach the log file

rofile "minikube" not found. Run "minikube profile list" to view all profiles.
👉  To start a cluster, run: "minikube start"

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
When you choose to run Docker in a virtual machine, you need to increase the memory of this VM to (at least) 2 GiB

https://docs.docker.com/desktop/settings/linux/

If you use the regular Docker Engine instead of Docker Desktop, it can use all the CPU and all the RAM of the machine.

https://docs.docker.com/engine/install/ubuntu/

**Comment by senthilanantha** [comment]
The error "docker only has ***MiB" memory indicates that the minikube is trying to start from qemu driver. If you notice further in same error output, it suggests alternate drivers. You may choose to start it with kvm if you have enough memory space.

In my case
![20221118_101157](https://user-images.githubusercontent.com/118501844/202618533-be0f7a81-33b8-4f51-8ce7-50d7809c5c27.jpg)

Ex: (in my case, refer the screenshot above)
$ minikube start --driver kvm2
