### ISSUE TITLE
Minikube Fails...

### ISSUE THREAD

**Issue by kmcowan** [kubernetes/minikube#15166]
### What Happened?

😄  minikube v1.27.1 on Darwin 12.5.1
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing hyperkit VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: IP address never found in dhcp leases file Temporary error: could not find an IP address for be:18:3b:17:4f:bf
🏃  Updating the running hyperkit "minikube" VM ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: IP address is not set

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IP address is not set

### Attach the log file

😄  minikube v1.27.1 on Darwin 12.5.1
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing hyperkit VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: IP address never found in dhcp leases file Temporary error: could not find an IP address for be:18:3b:17:4f:bf
🏃  Updating the running hyperkit "minikube" VM ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: IP address is not set

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IP address is not set

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by spowelljr** [comment]
Hi @kmcowan, it looks like you're trying to restart an existing HyperKit instance but it the old instance may no longer exist. Could you try running `minikube delete` and then try starting minikube again and see if that resolves your issue.

**Comment by spowelljr** [comment]
Hi @kmcowan, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
