### ISSUE TITLE
rror during connect: This error may indicate that the docker daemon is not running.

### ISSUE THREAD

**Issue by Olical22** [kubernetes/minikube#15176]
### What Happened?

rror during connect: This error may indicate that the docker daemon is not running.

### Attach the log file

error during connect: This error may indicate that the docker daemon is not running.: Get "http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.24/containers/minikube/json": open //./pipe/docker_engine: The system cannot find the file specified.

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!
