### ISSUE TITLE
Update docker version in minikube iso - possible?

### ISSUE THREAD

**Issue by harmon25** [kubernetes/minikube#1518]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
FEATURE REQUEST

**Minikube version** :
 v0.19.0

**Environment**: linux
- **OS** : debian jessie
- **VM Driver** : virtualbox
- **ISO version** : minikube-v0.18.0.iso
- **Install tools**: debian installer
- **Others**: N/A

**What happened**:
Am using the new [multistage build in docker](https://docs.docker.com/engine/userguide/eng-image/multistage-build/) but this does not work on the minikube iso as it is running docker v1.11.1.

It is in the edge docker release so not expecting this to be implemented in a minikube release anytime soon, but would it be possible to upgrade docker in the minikube-iso to ^17.05?

Have newer versions of docker been tested? 
Worry that would be quite the jump...

**Comment by dlorenc** [comment]
We're due for an update, but we probably can't go all the way to 17.05. We match what upstream kubernetes currently tests with, which will be lagging behind docker for a few releases.

**Comment by hayderimran7** [comment]
hello, is there any update to this?

**Comment by kilianc** [comment]
It would be nice to have at least `>= 1.13.0` os we can use `cache_from` in docker compose files.

**Comment by kilianc** [comment]
Is there a way to just `apt-get` docker and update it at our own risk?

**Comment by kilianc** [comment]
see https://github.com/kubernetes/minikube/pull/1542#issuecomment-318683859

> If you are stuck with this, you can preview the custom ISO with:
> 
>     $ minikube start --iso-url=https://storage.googleapis.com/minikube-builds/1542/minikube-testing.iso
> 
> Works perfectly for me! 🍻

**Comment by Vrtak-CZ** [comment]
Just FYI:

> Kubernetes 1.8 supports docker version 1.11.x, 1.12.x and 1.13.x

btw Docker 17.03 (is actually 1.13.x) has been validated for K8s 1.8 too.

**Comment by Place1** [comment]
I'm keen to try multi-stage builds so having docker 17.05+ would be nice :D

**Comment by medyagh** [comment]
We in github.com/k8guard  need multi-stage builds, is there any way to update the minikube's docker version manually?

**Comment by yairmark** [comment]
As of the 26th of October 2017 the newest version of the Minikube iso has docker 17.05-ce https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md#version-0230---10262017
