### ISSUE TITLE
Using minikube as Docker Desktop Replacement

### ISSUE THREAD

**Issue by carlospalmaroldan** [kubernetes/minikube#15184]
MacOs Big Sur
MacBook Pro (16-inch, 2019)
Processor 2,6 Ghz 6-Core Intel Core i7
Memory 16 GB 2667 MHz DDR4

Attempting to execute the following command:

minikube start --container-runtime=docker --vm=true

yields the following result:

bcp@river lib % minikube start --container-runtime=docker --vm=true
😄  minikube v1.26.1 on Darwin 11.6.3
✨  Using the docker driver based on existing profile

💣  Exiting due to PROVIDER_DOCKER_NOT_RUNNING: "docker version --format -" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
💡  Suggestion: Start the Docker service
📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by spowelljr** [comment]
Hi @carlospalmaroldan, what driver are you attempting to use? I see you have `--vm=true` but you previously starting minikube with the Docker driver so it's doing to try to it with Docker again. Try running `minikube delete` and then try starting minikube again and then it will try to use a VM driver.

**Comment by carlospalmaroldan** [comment]
Works like a charm. Thank you spowelljr!

**Comment by carlospalmaroldan** [comment]
It works
