### ISSUE TITLE
/tmp/minikube_addons_5e63cb8ceb2e7e06e33b8dd7a9dcbebc0ad5ec5a_0.log     

### ISSUE THREAD

**Issue by amnamek** [kubernetes/minikube#15198]
**Étapes pour reproduire le problème:** 

1.
2. 
3.

**Sortie complète de la commande `minikube logs`:**
<details>

</details>

**Sortie complète de la commande échouée:**
<details>

</details>

**Comment by spowelljr** [comment]
Closing due to https://github.com/kubernetes/minikube/issues/15199
