### ISSUE TITLE
X Exiting due to HOST_JUJU_LOCK_PERMISSION: Failed to save config: failed to acquire lock for /root/.minikube/profiles/minikube/config.json: {Name:mk270d1b5db5965f2dc9e9e25770a63417031943 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}: unable to open /tmp/juju-mk270d1b5db5965f2dc9e9e25770a63417031943: permission denied

### ISSUE THREAD

**Issue by amnamek** [kubernetes/minikube#15199]
**Étapes pour reproduire le problème:** 

1.
2. 
3.

**Sortie complète de la commande `minikube logs`:**
<details>

</details>

**Sortie complète de la commande échouée:**
<details>

</details>

**Comment by packetgeek** [comment]
I had this same issue on Ubuntu 22.04, with "minikube start --driver=docker".  However, once I rebooted the system, minikube started normally.
