### ISSUE TITLE
Invalid CPU configuration of command  when “minikube start”

### ISSUE THREAD

**Issue by oscarchan76** [kubernetes/minikube#15195]
### What Happened?

environment:
(1) minikube version: v1.27.1
commit: fe869b5d4da11ba318eb84a3ac00f336411de7ba

(2) docker version: 
Client: Docker Engine - Community
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:22:47 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:20:56 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

(3)operating system
GNU/LinuxLinux version 3.10.0-1160.49.1.el7.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) )

problem description:
1. Successfully construct a cluster using command as follows.

[#@# root]$ _minikube start --driver=docker --image-mirror-country='cn' --cpus='4' --memory='6400m' --kubernetes-version=v1.18.0 -p evaluation_
😄  Centos 7.9.2009 上的 [evaluation] minikube v1.27.1
✨  根据用户配置使用 docker 驱动程序
✅  正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
📌  Using Docker driver with root privileges
👍  Starting control plane node evaluation in cluster evaluation
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=4, Memory=6400MB) ...
🐳  正在 Docker 20.10.18 中准备 Kubernetes v1.18.0…
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

❗  /usr/bin/kubectl is version 1.23.0, which may have incompatibilites with Kubernetes 1.18.0.
    ▪ Want kubectl v1.18.0? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "evaluation" cluster and "default" namespace by default

2. Then view the configuration of the master node.
![image](https://user-images.githubusercontent.com/52748287/197387813-c97a9ce1-ae65-458a-bb9d-3d97e86d2519.png)

![image](https://user-images.githubusercontent.com/52748287/197387855-adf0a306-1e00-48fa-9d9f-ae35b7d68bad.png)

3. I found that the number of cpu and memory in master is different from the number of cpu and memory set by args _--cpus='4' --memory='6400m'_.  

4. In addition, this problem was not found under the driver of hyperkit (--driver=hyperkit) in MacOS system. So it is a driver problem?

5. So, i want to know how to address this problem. Thanks. 

### Attach the log file

❌  Exiting due to MK_USAGE: open log.txt: permission denied

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_logs_d805c586baabdff8ae08956d9c493040aa91bbb7_0.log

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
Currently the container driver does not set up the resource of the node correctly, it always shows the entire node.

It needs to make those resources "reserved", and not shown as included in the fake node created for kubernetes.

**Comment by afbjorklund** [comment]
Note that the limits on the container should still have correct values, this is about the resources on the node.

https://docs.docker.com/config/containers/resource_constraints/

**Comment by oscarchan76** [comment]
> Note that the limits on the container should still have correct values, this is about the resources booked on the node.
> 
> https://docs.docker.com/config/containers/resource_constraints/

Thanks. 

Actually, i found that resource of the node set up with args _--cpus='4' --memory='6144m'_ are valid by checking the container info.

1. Firstly, i check the resource limit of fake node (container) after building a fake master node using "_minikube start_".
![image](https://user-images.githubusercontent.com/52748287/197436295-4c8479cf-5221-4574-a1f4-88831991bd85.png)
![image](https://user-images.githubusercontent.com/52748287/197436296-825751c7-4270-4fbe-b700-d64514451c96.png)
2. The resource of node still not show the correct values set by command. But, in fact, the resource limit has already taken effect when i check the container info corresponding to the fake node.
![image](https://user-images.githubusercontent.com/52748287/197436999-b019ff76-d53b-462f-a0e7-76b256ffe8bb.png)
![image](https://user-images.githubusercontent.com/52748287/197437039-2ad2eab5-0952-472f-ae33-9f42c2d04cbb.png)

So, the resource limits on the container is right. Maybe this is a display problem. 

But ,i don't know that if this situation can affect the Pod scheduling.

**Comment by afbjorklund** [comment]
> But ,i don't know that if this situation can affect the Pod scheduling.

It does, but then again scheduling with a single node is not a puzzle...

In order to show the correct values, the "remaining" host resources need to be flagged as systemd reserved in the kubelet.

So if your host has 40 CPU but your node has 4 CPU, then kubelet needs a flag `--system-reserved=cpu=36` added.

The same also goes for memory (Ki) and ephemeralstorage (Ki)

**Comment by oscarchan76** [comment]
> > But ,i don't know that if this situation can affect the Pod scheduling.
> 
> It does, but then again scheduling with a single node is not a puzzle...
> 
> In order to show the correct values, the "remaining" host resources need to be flagged as system-reserved in the kubelet.
> 
> So if your host has 40 CPU but your node has 4 CPU, then kubelet needs a flag `--system-reserved=cpu=36` added.
> 
> The same also goes for memory (Ki) and ephemeralstorage (Ki)
> 
> Example:
> 
> ```
> 	"CPUs": 2,
> 	"Memory": 16000,
> 	"DiskSize": 20000,
> ```
> 
> `kubelet --system-reserved=cpu=30,memory=49386700Ki,ephemeral-storage=217251608Ki `
> 
> ```
> $ kubectl describe node | grep -A13 ^Capacity
> Capacity:
>   cpu:                32
>   ephemeral-storage:  237731608Ki
>   hugepages-1Gi:      0
>   hugepages-2Mi:      0
>   memory:             65770700Ki
>   pods:               110
> Allocatable:
>   cpu:                2
>   ephemeral-storage:  20000Mi
>   hugepages-1Gi:      0
>   hugepages-2Mi:      0
>   memory:             16000Mi
>   pods:               110
> ```

Can i set the resource of every node of a fake cluster（built by minikube）in a local physical host ？

As you show, Flag "--system-reserve" is just suitable for setting the resource limit of a physical host/node in a real cluster,  but not  suitable for other worker nodes(except for master).

**Comment by afbjorklund** [comment]
It is suitable for every node, but it needs to be added to the code - or it will be overwritten when the node is restarted...

The actual limits will be enforced by the cgroups, the kubernetes values is just for how many resources can be "booked"

But currently there is no way to set the disk quota for the ephemeral storage, unless running a separate Root dir for each.

If you want better isolation between the nodes (including kernel), then virtual machines would be better than containers.

**Comment by oscarchan76** [comment]
> It is suitable for every node, but it needs to be added to the code - or it will be overwritten when the node is restarted...
> 
> The actual limits will be enforced by the cgroups, the kubernetes values is just for how many resources can be "booked"
> 
> But currently there is no way to set the disk quota for the ephemeral storage, unless running a separate Root dir for each.
> 
> If you want better isolation between the nodes (including kernel), then virtual machines would be better than containers.

Thanks.

So, if i build a  cluster consists of a master  node and 8 worker nodes using minikube,  i need to enter each node using "minikube ssh", and then use the "kubelet --system-reserve" to set the resource reserved. 

If not, how to use flag " kubelet --system-reserved" to set resource reserved for one of nodes? And there is no kubelet service in a minikube node.

**Comment by afbjorklund** [comment]
It's a bug / feature, waiting to be addressed (in minikube).

The code is here: [pkg/minikube/bootstrapper/bsutil](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/bootstrapper/bsutil/kubelet.go)

> And there is no kubelet service in a minikube node.

It runs the regular kubelet.service, as set up by "start" ?

**Comment by oscarchan76** [comment]
> It's a bug / feature, waiting to be addressed (in minikube).
> 
> The code is here: [pkg/minikube/bootstrapper/bsutil](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/bootstrapper/bsutil/kubelet.go)
> 
> > And there is no kubelet service in a minikube node.
> 
> It runs the regular kubelet.service, as set up by "start" ?

Thanks.
