### ISSUE TITLE
/tmp/minikube_addons_5e63cb8ceb2e7e06e33b8dd7a9dcbebc0ad5ec5a_0.log     

### ISSUE THREAD

**Issue by amnamek** [kubernetes/minikube#15197]
**الأوامر المطلوبة لإعادة إظهار المشكلة**:

**النتيجة الكاملة للأمر الذي تعذّر تنفيذه**:<details>

</details>

**نتيجة الأمر `minikube logs`**: <details>

</details>

**إصدار نظام التشغيل المُستخدَم**:

**Comment by spowelljr** [comment]
Closing due to https://github.com/kubernetes/minikube/issues/15199
