### ISSUE TITLE
unable to start minikube

### ISSUE THREAD

**Issue by Vickydev95** [kubernetes/minikube#15215]
### What Happened?

Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: timed out waiting for the condition

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9857025/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/14202
