### ISSUE TITLE
golang application compiled with build flag GOAMD64=v3 can't be launched in k8s

### ISSUE THREAD

**Issue by zifter** [kubernetes/minikube#15213]
### What Happened?

I launched minikube with k8s version 1.24.4 and using virtualbox:

> minikube start --kubernetes-version=v1.24.4 --driver=virtualbox

I have deployed pod with application which is written in golang and built with flag GOAMD64=v3.
When pod is started I see the following error:

> This program can only be run on AMD64 processors with v3 microarchitecture support.

It means that complied golang application can't be run on the node.

Is it possible to deliver virtualbox image with supporting of amd64 v3 architecture level?

### Attach the log file

-

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by afbjorklund** [comment]
As far as I know, "[x86_64](https://en.wikipedia.org/wiki/X86-64) v3" is about AVX-2, so probably it is related to VirtualBox disabling this passthough

https://www.virtualbox.org/ticket/14262

It might be possible to re-enable it again, using some command-line flag to `VBoxManage`.

**Comment by afbjorklund** [comment]
Hmm, maybe it _wasn't_ AVX2 but some other CPU feature that is missing in the emulator.

```console
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ grep avx /proc/cpuinfo 
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 movbe popcnt aes xsave avx rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase avx2 invpcid rdseed clflushopt md_clear flush_l1d arch_capabilities
```

Need to step through the code, to see which one.

**Comment by afbjorklund** [comment]
Here is the `cpuid` from minikube VirtualBox: [cpuid.txt](https://github.com/kubernetes/minikube/files/9855687/cpuid.txt)

**Comment by afbjorklund** [comment]
https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level#architectural_considerations_for_rhel_9

> "We believe that x86-64-v2 is the appropriate choice for Red Hat Enterprise Linux 9. "

**Comment by zifter** [comment]
> Most likely you will need to recompile your code, to work in VirtualBox ?

Yes, it's like a one of the solution - to build with flag GOAMD64=v2 or without it all.

It's working in other drivers, but sometimes virtualbox it's preferred choice. If is no changes to change VirtualBox image - ok.

**Comment by afbjorklund** [comment]
> If is no changes to change VirtualBox image - ok.

It is not in the image, it is a runtime setting (or two) for the VirtualBox hypervisor...

Apparently it is masking some of the host CPU flags. It (v3) works OK in QEMU/KVM

The v4 (AVX512) did not work on my host either
