### ISSUE TITLE
minikube addons enable ingress

### ISSUE THREAD

**Issue by yomi40** [kubernetes/minikube#15217]
### What Happened?

 Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
 - /var/folders/r8/y0tdls9j6r965nxrxl7qxxbw0000gn/T/minikube_addons_0d0beeaa5c69dc10c8e06caf203d9780561f1745_0.log   

### Attach the log file

 minikube logs --file=log.txt

❌  Exiting due to GUEST_STATUS: state: unknown state "minikube": docker container inspect minikube --format=: exit status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

╭───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                       │
│    😿  If the above advice does not help, please let us know:                                                         │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                       │
│                                                                                                                       │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                │
│    Please also attach the following file to the GitHub issue:                                                         │
│    - /var/folders/r8/y0tdls9j6r965nxrxl7qxxbw0000gn/T/minikube_logs_3e0b8d5224939fa51841d85211c0767ed373f56e_0.log    │
│                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

macOS (Default)

### Driver

SSH

**Comment by spowelljr** [comment]
Hi @yomi40, it looks like your Docker instance is not running, could you ensure Docker is running and then start minikube again `minikube start` and then try enabling your addon.

**Comment by spowelljr** [comment]
Hi @yomi40, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
