### ISSUE TITLE
Exiting due to MK_ADDON_ENABLE: loading profile: cluster "minikube" does not exist

### ISSUE THREAD

**Issue by godfatherdemon** [kubernetes/minikube#15221]
### What Happened?

Log file created at: 2022/10/26 12:15:47
Running on machine: god-HP-Pavilion-Laptop-14-ec0013AU
Binary: Built with gc go1.19.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1026 12:15:47.184767   83332 out.go:296] Setting OutFile to fd 1 ...
I1026 12:15:47.185036   83332 out.go:348] isatty.IsTerminal(1) = true
I1026 12:15:47.185043   83332 out.go:309] Setting ErrFile to fd 2...
I1026 12:15:47.185052   83332 out.go:348] isatty.IsTerminal(2) = true
I1026 12:15:47.185196   83332 root.go:333] Updating PATH: /home/god/.minikube/bin
W1026 12:15:47.185345   83332 root.go:310] Error reading config file at /home/god/.minikube/config/config.json: open /home/god/.minikube/config/config.json: no such file or directory
I1026 12:15:47.186813   83332 out.go:177] 💡  ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
I1026 12:15:47.187873   83332 out.go:177] 
W1026 12:15:47.188679   83332 out.go:239] ❌  Exiting due to MK_ADDON_ENABLE: loading profile: cluster "minikube" does not exist
W1026 12:15:47.188700   83332 out.go:239] 
W1026 12:15:47.190420   83332 out.go:239] [31m╭───────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                             [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                             [31m│[0m
[31m│[0m    - /tmp/minikube_addons_7383bebb2d120658a22b45c2996863803ddcdbcd_0.log                  [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯[0m
I1026 12:15:47.191638   83332 out.go:177] 

### Attach the log file

Log file created at: 2022/10/26 12:15:47
Running on machine: god-HP-Pavilion-Laptop-14-ec0013AU
Binary: Built with gc go1.19.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1026 12:15:47.184767   83332 out.go:296] Setting OutFile to fd 1 ...
I1026 12:15:47.185036   83332 out.go:348] isatty.IsTerminal(1) = true
I1026 12:15:47.185043   83332 out.go:309] Setting ErrFile to fd 2...
I1026 12:15:47.185052   83332 out.go:348] isatty.IsTerminal(2) = true
I1026 12:15:47.185196   83332 root.go:333] Updating PATH: /home/god/.minikube/bin
W1026 12:15:47.185345   83332 root.go:310] Error reading config file at /home/god/.minikube/config/config.json: open /home/god/.minikube/config/config.json: no such file or directory
I1026 12:15:47.186813   83332 out.go:177] 💡  ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
I1026 12:15:47.187873   83332 out.go:177] 
W1026 12:15:47.188679   83332 out.go:239] ❌  Exiting due to MK_ADDON_ENABLE: loading profile: cluster "minikube" does not exist
W1026 12:15:47.188700   83332 out.go:239] 
W1026 12:15:47.190420   83332 out.go:239] [31m╭───────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                             [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                             [31m│[0m
[31m│[0m    - /tmp/minikube_addons_7383bebb2d120658a22b45c2996863803ddcdbcd_0.log                  [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯[0m
I1026 12:15:47.191638   83332 out.go:177] 

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @godfatherdemon, you don't have a running minikube instance. Try starting minikube with `minikube start` and then try enabling the ingress addon.

**Comment by spowelljr** [comment]
Hi @godfatherdemon, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by Aaqibshaikh20** [comment]
Exiting due to MK_USAGE: loading profile: cluster "minikube" does not exist
I have installed Docker and Minikube on the same Ubuntu VM. I have some Docker images stored locally and I want to run them using pod.yaml. However, when I try to run them using pod.yaml, I get an "image pull backup off" error. Can you please help me resolve this issue?
