### ISSUE TITLE
 - /tmp/minikube_logs_ebe9aace0e5288a4491f46755c7e4561b9f8bec9_0.log

### ISSUE THREAD

**Issue by bastosrafael** [kubernetes/minikube#15233]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

 - /tmp/minikube_logs_ebe9aace0e5288a4491f46755c7e4561b9f8bec9_0.log

</details>

**A saída do comando `minikube logs`**:<details>

</details>

**A versão do sistema operacional usado**:

**Comment by medyagh** [comment]
[bastosrafael](https://github.com/bastosrafael) the log file has not been attached, please drag and drop that file into this page
