### ISSUE TITLE
minikube podman-env complains about cri-o runtime spelling

### ISSUE THREAD

**Issue by wshallum** [kubernetes/minikube#15246]
### What Happened?

1. Start a cluster with `--container-runtime cri-o`
2. Run `minikube podman-env`
3. See an error message: `X Exiting due to MK_USAGE: The podman-env command is only compatible with the "crio" runtime, but this cluster was configured to use the "cri-o" runtime.`

It seems the code disagrees on how to spell CRI-O: 

https://github.com/kubernetes/minikube/blob/074e681975c6c82deeebd5317bf328e0f0fab512/pkg/minikube/cruntime/cruntime.go#L51-L54

vs

https://github.com/kubernetes/minikube/blob/074e681975c6c82deeebd5317bf328e0f0fab512/pkg/minikube/constants/constants.go#L59-L60

(checked here)

https://github.com/kubernetes/minikube/blob/074e681975c6c82deeebd5317bf328e0f0fab512/cmd/minikube/cmd/podman-env.go#L173-L176 

ValidRuntimes is used in the help message too, so it is misleading.

### Attach the log file

... do I really need a log file for this?

### Operating System

Windows

### Driver

Hyper-V

**Comment by jacobwhall** [comment]
Oof, we don't love GitHub bots that mark things as stale.

I just ran into this problem in Linux Mint. Steps to reproduce:
1. `minikube config set container-runtime cri-o`
2. `minikube start`
3. [`eval $(minikube podman-env)`](https://minikube.sigs.k8s.io/docs/handbook/pushing/#3-pushing-directly-to-in-cluster-cri-o-podman-env)

Produces this error:
```
❌  Exiting due to MK_USAGE: The podman-env command is only compatible with the "crio" runtime, but this cluster was configured to use the "cri-o" runtime.
```

**Comment by lednubr** [comment]
isn't just a matter of updating the help message? which command outputs "cri-o" for you?

if use **crio**, e.g: `minikube config set container-runtime crio`... everything works fine for me.

**Comment by jacobwhall** [comment]
@lednubr your solution of using "crio" instead of "cri-o" works for me.

I think this is a bug worth addressing. [The documentation says "cri-o"](https://minikube.sigs.k8s.io/docs/handbook/config/#runtime-configuration), and minikube happily starts regardless of whether "crio" or "cri-o" is specified. Running `eval $(minikube podman-env)` is not a good time for minikube to complain about this.

**Comment by jacobwhall** [comment]
Curiously, following @wshallum's steps does not reproduce this error for me. Running `minikube start --container-runtime cri-o` allows me to then run `eval $(minikube podman-env)` without issue. I wonder what might be causing that difference. In my experience, this issue only occurs when setting the container-runtime to "cri-o" using `minikube config ...`

**Comment by lednubr** [comment]
I was able to reproduce @wshallum steps, and the output was the same error. My suggestion would be https://github.com/kubernetes/minikube/pull/15908 and maybe adding a validation to "valid" --container-runtime options

**Comment by lednubr** [comment]
this two references are also misleading

https://github.com/search?q=repo%3Akubernetes%2Fminikube+container-runtime%3Dcri-o&type=code

**Comment by Woytek-Polnik** [comment]
> isn't just a matter of updating the help message? which command outputs "cri-o" for you?
> 
> if use **crio**, e.g: `minikube config set container-runtime crio`... everything works fine for me.

Yes 'crio' works - tho it is odd that minikube 'eats' both crio and cri-o while skaffold just one.

Anyways
Even setting that correctly will give you error at deploy or render
```
skaffold render
invalid skaffold config: getting minikube env: running [/usr/local/bin/minikube docker-env --shell none -p minikube --user=skaffold]
 - stdout: "false exit code 14\n"
 - stderr: "X Exiting due to MK_USAGE: The docker-env command is only compatible with the \"docker\" runtime, but this cluster was configured to use the \"crio\" runtime.\n"
 - cause: exit status 14
 ```
 
 Steps
 
 ```
 podman machine init --cpus 6 --memory 10000
podman machine start
podman system connection default podman-machine-default-root

minikube config set driver podman
minikube config set cpus 6
minikube config set memory 9678
minikube config set container-runtime crio

minikube start
skaffold deploy 
# Here you get the error
```
It is stupid and it is enough to rename context 'minikube' to anything else it would work.....
