### ISSUE TITLE
 ps

### ISSUE THREAD

**Issue by rmeindl** [kubernetes/minikube#1525]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Minikube version** (use `minikube version`):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by dlorenc** [comment]
Did you mean to open this?
