### ISSUE TITLE
dial tcp 127.0.0.1:41115 issue Minikube inside Docker

### ISSUE THREAD

**Issue by JayDew** [kubernetes/minikube#15260]
### What Happened?

I am trying to run Minikube inside Docker. According to this post, it should be possible to do so: 

https://stackoverflow.com/questions/53759814/docker-image-with-minikube-inside

(I use the exact same Dockerfile and commands)

When running
`minikube start --driver=docker --force --alsologtostderr
`

I get 

`I1101 14:53:05.954178      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused`

### Attach the log file

* 
* ==> Audit <==
* |---------|--------------------------------|----------|------|---------|---------------------|---------------------|
| Command |              Args              | Profile  | User | Version |     Start Time      |      End Time       |
|---------|--------------------------------|----------|------|---------|---------------------|---------------------|
| start   | --driver=docker --force        | minikube | root | v1.27.1 | 01 Nov 22 14:38 UTC |                     |
| start   | --driver=docker --force --v 3  | minikube | root | v1.27.1 | 01 Nov 22 14:43 UTC |                     |
| delete  |                                | minikube | root | v1.27.1 | 01 Nov 22 14:43 UTC | 01 Nov 22 14:44 UTC |
| start   | --driver=docker --force --v 3  | minikube | root | v1.27.1 | 01 Nov 22 14:44 UTC |                     |
| delete  | --all                          | minikube | root | v1.27.1 | 01 Nov 22 14:45 UTC | 01 Nov 22 14:45 UTC |
| start   | --driver=docker --force        | minikube | root | v1.27.1 | 01 Nov 22 14:47 UTC |                     |
|         | --alsologtostderr              |          |      |         |                     |                     |
| start   | --driver=docker --force        | minikube | root | v1.27.1 | 01 Nov 22 14:49 UTC |                     |
|         | --alsologtostderr              |          |      |         |                     |                     |
|---------|--------------------------------|----------|------|---------|---------------------|---------------------|

* 
* ==> Last Start <==
* Log file created at: 2022/11/01 14:49:36
Running on machine: docker-desktop
Binary: Built with gc go1.19.1 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1101 14:49:36.897802      20 out.go:296] Setting OutFile to fd 1 ...
I1101 14:49:36.898000      20 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1101 14:49:36.898018      20 out.go:309] Setting ErrFile to fd 2...
I1101 14:49:36.898029      20 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1101 14:49:36.898192      20 root.go:333] Updating PATH: /root/.minikube/bin
I1101 14:49:36.898912      20 out.go:303] Setting JSON to false
I1101 14:49:36.899642      20 start.go:116] hostinfo: {"hostname":"docker-desktop","uptime":233725,"bootTime":1667080452,"procs":4,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.49-linuxkit","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"guest","hostId":"64cc781c-1568-4e1e-8b5b-1dac6e2aad18"}
I1101 14:49:36.899746      20 start.go:126] virtualization:  guest
I1101 14:49:36.903236      20 out.go:177] * minikube v1.27.1 on Ubuntu 22.04 (amd64)
W1101 14:49:36.905700      20 out.go:239] ! minikube skips various validations when --force is supplied; this may lead to unexpected behavior
I1101 14:49:36.905799      20 notify.go:220] Checking for updates...
I1101 14:49:36.906347      20 config.go:180] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.25.2
I1101 14:49:36.907239      20 driver.go:362] Setting default libvirt URI to qemu:///system
I1101 14:49:37.090673      20 docker.go:137] docker version: linux-20.10.20
I1101 14:49:37.090769      20 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I1101 14:49:37.361195      20 info.go:265] docker info: {ID:KL5C:XEQS:QEKQ:VMWB:3GHU:VLXU:P2K2:LSDN:KPOW:DAEV:BESY:QMGK Containers:3 ContainersRunning:1 ContainersPaused:0 ContainersStopped:2 Images:2 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:68 OomKillDisable:false NGoroutines:97 SystemTime:2022-11-01 14:49:37.226287001 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:7 KernelVersion:5.15.49-linuxkit OperatingSystem:Docker Desktop OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:6 MemTotal:8076013568 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy:http.docker.internal:3128 HTTPSProxy:http.docker.internal:3128 NoProxy:hubproxy.docker.internal Name:docker-desktop Labels:[] ExperimentalBuild:false ServerVersion:20.10.20 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6 Expected:9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6} RuncCommit:{ID:v1.1.4-0-g5fd4c4d Expected:v1.1.4-0-g5fd4c4d} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Experimental:true Name:app Path:/usr/libexec/docker/cli-plugins/docker-app SchemaVersion:0.1.0 ShortDescription:Docker App Vendor:Docker Inc. Version:v0.9.1-beta3] map[Name:buildx Path:/usr/libexec/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.9.1-docker] map[Name:compose Path:/usr/libexec/docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.12.2] map[Name:scan Path:/usr/libexec/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.21.0]] Warnings:<nil>}}
I1101 14:49:37.361390      20 docker.go:254] overlay module found
I1101 14:49:37.366071      20 out.go:177] * Using the docker driver based on existing profile
I1101 14:49:37.367931      20 start.go:282] selected driver: docker
I1101 14:49:37.367962      20 start.go:808] validating driver "docker" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.25.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1101 14:49:37.368157      20 start.go:819] status for docker: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
W1101 14:49:37.368309      20 out.go:239] * The "docker" driver should not be used with root privileges. If you wish to continue as root, use --force.
W1101 14:49:37.368384      20 out.go:239] * If you are running minikube within a VM, consider using --driver=none:
W1101 14:49:37.368503      20 out.go:239] *   https://minikube.sigs.k8s.io/docs/reference/drivers/none/
I1101 14:49:37.368756      20 config.go:180] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.25.2
W1101 14:49:37.368909      20 out.go:239] * Tip: To remove this root owned cluster, run: sudo minikube delete
I1101 14:49:37.369001      20 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I1101 14:49:37.663002      20 info.go:265] docker info: {ID:KL5C:XEQS:QEKQ:VMWB:3GHU:VLXU:P2K2:LSDN:KPOW:DAEV:BESY:QMGK Containers:3 ContainersRunning:1 ContainersPaused:0 ContainersStopped:2 Images:2 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:68 OomKillDisable:false NGoroutines:97 SystemTime:2022-11-01 14:49:37.514672247 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:7 KernelVersion:5.15.49-linuxkit OperatingSystem:Docker Desktop OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:6 MemTotal:8076013568 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy:http.docker.internal:3128 HTTPSProxy:http.docker.internal:3128 NoProxy:hubproxy.docker.internal Name:docker-desktop Labels:[] ExperimentalBuild:false ServerVersion:20.10.20 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6 Expected:9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6} RuncCommit:{ID:v1.1.4-0-g5fd4c4d Expected:v1.1.4-0-g5fd4c4d} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Experimental:true Name:app Path:/usr/libexec/docker/cli-plugins/docker-app SchemaVersion:0.1.0 ShortDescription:Docker App Vendor:Docker Inc. Version:v0.9.1-beta3] map[Name:buildx Path:/usr/libexec/docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.9.1-docker] map[Name:compose Path:/usr/libexec/docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.12.2] map[Name:scan Path:/usr/libexec/docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.21.0]] Warnings:<nil>}}
I1101 14:49:37.663918      20 cni.go:95] Creating CNI manager for ""
I1101 14:49:37.663941      20 cni.go:169] CNI unnecessary in this configuration, recommending no CNI
I1101 14:49:37.663959      20 start_flags.go:317] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.2 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.25.2 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1101 14:49:37.673341      20 out.go:177] * Starting control plane node minikube in cluster minikube
I1101 14:49:37.675467      20 cache.go:120] Beginning downloading kic base image for docker with docker
I1101 14:49:37.677652      20 out.go:177] * Pulling base image ...
I1101 14:49:37.681602      20 preload.go:132] Checking if preload exists for k8s version v1.25.2 and runtime docker
I1101 14:49:37.681676      20 preload.go:148] Found local preload: /root/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.25.2-docker-overlay2-amd64.tar.lz4
I1101 14:49:37.681715      20 cache.go:57] Caching tarball of preloaded images
I1101 14:49:37.681685      20 image.go:75] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local docker daemon
I1101 14:49:37.682177      20 preload.go:174] Found /root/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.25.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I1101 14:49:37.682221      20 cache.go:60] Finished verifying existence of preloaded tar for  v1.25.2 on docker
I1101 14:49:37.682527      20 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I1101 14:49:37.802050      20 cache.go:147] Downloading gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local cache
I1101 14:49:37.802532      20 image.go:59] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local cache directory
I1101 14:49:37.802794      20 image.go:119] Writing gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local cache
I1101 14:50:25.950824      20 cache.go:150] successfully saved gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b as a tarball
I1101 14:50:25.950873      20 cache.go:161] Loading gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b from local cache
I1101 14:51:22.927360      20 cache.go:164] successfully loaded gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b from cached tarball
I1101 14:51:22.927385      20 cache.go:170] Downloading gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local daemon
I1101 14:51:22.927660      20 image.go:75] Checking for gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b in local docker daemon
I1101 14:51:23.119769      20 image.go:243] Writing gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b to local daemon
I1101 14:53:04.451321      20 cache.go:173] successfully downloaded gcr.io/k8s-minikube/kicbase:v0.0.35@sha256:e6f9b2700841634f3b94907f9cfa6785ca4409ef8e428a0322c1781e809d311b
I1101 14:53:04.451437      20 cache.go:208] Successfully downloaded all kic artifacts
I1101 14:53:04.451548      20 start.go:364] acquiring machines lock for minikube: {Name:mke11f63b5835bf422927bf558fccac7a21a838f Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1101 14:53:04.451871      20 start.go:368] acquired machines lock for "minikube" in 233.208µs
I1101 14:53:04.452028      20 start.go:96] Skipping create...Using existing machine configuration
I1101 14:53:04.452072      20 fix.go:55] fixHost starting: 
I1101 14:53:04.452729      20 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I1101 14:53:04.706026      20 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W1101 14:53:04.706293      20 fix.go:129] unexpected machine state, will restart: <nil>
I1101 14:53:04.713404      20 out.go:177] * Restarting existing docker container for "minikube" ...
I1101 14:53:04.717103      20 cli_runner.go:164] Run: docker start minikube
I1101 14:53:05.339619      20 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I1101 14:53:05.562791      20 kic.go:415] container "minikube" state is running.
I1101 14:53:05.563467      20 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I1101 14:53:05.760015      20 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I1101 14:53:05.760321      20 machine.go:88] provisioning docker machine ...
I1101 14:53:05.760377      20 ubuntu.go:169] provisioning hostname "minikube"
I1101 14:53:05.760450      20 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1101 14:53:05.952503      20 main.go:134] libmachine: Using SSH client type: native
I1101 14:53:05.953339      20 main.go:134] libmachine: &{{{<nil> 0 [] [] []} docker [0x7ecce0] 0x7efe60 <nil>  [] 0s} 127.0.0.1 41115 <nil> <nil>}
I1101 14:53:05.953625      20 main.go:134] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I1101 14:53:05.954178      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:08.955190      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:11.955888      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:14.956879      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:17.958009      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:20.961421      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:23.963710      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:26.964390      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:29.965251      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:32.966097      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:35.966999      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:38.967746      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:41.968818      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:44.969991      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:47.971454      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:50.974176      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:53.976447      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:56.978204      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:53:59.981642      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:02.983324      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:05.986784      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:08.988818      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:11.990679      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:14.993995      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:17.995475      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:20.999198      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:24.002215      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:27.003880      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:30.007417      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:33.009279      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:36.012757      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:39.014981      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:42.015868      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:45.018990      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:48.020106      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:51.023778      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:54.026742      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:54:57.028213      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:00.031496      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:03.033438      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:06.035396      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:09.037875      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:12.038850      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:15.039782      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:18.041085      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:21.044790      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:24.047526      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:27.048483      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:30.051763      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:33.053652      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:36.057090      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:39.059472      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:42.060466      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:45.063558      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:48.064890      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:51.067804      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:54.069953      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:55:57.071081      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:56:00.074244      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused
I1101 14:56:03.075521      20 main.go:134] libmachine: Error dialing TCP: dial tcp 127.0.0.1:41115: connect: connection refused

### Operating System

Ubuntu

### Driver

Docker

**Comment by JacobShirley95** [comment]
Hi there, did you manage to solve this issue? I am having the same problem. I'm running Minikube in Gitpod

**Comment by pmoros** [comment]
Hi! Though it has no relation to your issue, Minikube hung when using `minikube start` after I used  `minikube delete`. Using the `-force` flag you used finally made it work. Thank you so much!
