### ISSUE TITLE
start fail with macos13.0

### ISSUE THREAD

**Issue by ykk0612** [kubernetes/minikube#15276]
**重现问题所需的命令**：minikube start --driver=hyperkit --network-plugin=cni --cni='calico' --extra-config=kubelet.cgroup-driver=systemd --image-mirror-country='cn' --registry-mirror=https://registry.docker-cn.com --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --insecure-registry=harbor.k8s.local,registry.k8s.local --cpus='max' --container-runtime='containerd' --disk-size='50gb' --memory='8gb' --nfs-shares-root='/nfsshares' --nfs-share=/Volumes/data/DockerVolume

**失败的命令的完整输出**：<details>

😄  Darwin 13.0 上的 minikube v1.27.1
    ▪ MINIKUBE_HOME=/Volumes/system/minikube
✨  根据用户配置使用 hyperkit 驱动程序
🔑  'hyperkit' 驱动程序需要提升权限，将执行以下命令：

    $ sudo chown root:wheel /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit 
    $ sudo chmod u+s /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit 

❗  With --network-plugin=cni, you will need to provide your own CNI. See --cni flag as a user-friendly alternative
✅  正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=12, Memory=8192MB, Disk=51200MB) ...
🤦  StartHost failed, but will try again: creating host: create: Error with pre-create check: "docker-machine-driver-hyperkit needs to run with elevated permissions. Please run the following command, then try again: sudo chown root:wheel /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit && sudo chmod u+s /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit"
🔥  Creating hyperkit VM (CPUs=12, Memory=8192MB, Disk=51200MB) ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: creating host: create: Error with pre-create check: "docker-machine-driver-hyperkit needs to run with elevated permissions. Please run the following command, then try again: sudo chown root:wheel /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit && sudo chmod u+s /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit"

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: Error with pre-create check: "docker-machine-driver-hyperkit needs to run with elevated permissions. Please run the following command, then try again: sudo chown root:wheel /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit && sudo chmod u+s /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit"

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
</details>

**`minikube logs`命令的输出**： <details>

[logs.txt](https://github.com/kubernetes/minikube/files/9927444/logs.txt)
[minikube_logs_42f03617e71227008de6d8329679ed693d8ed812_0.log](https://github.com/kubernetes/minikube/files/9927445/minikube_logs_42f03617e71227008de6d8329679ed693d8ed812_0.log)
</details>

**使用的操作系统版本**：
macOS 13.0

**Comment by spowelljr** [comment]
@ykk0612 Did you run the following command?

@ykk0612 您是否运行了以下命令?
```
sudo chown root:wheel /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit && sudo chmod u+s /Volumes/system/minikube/.minikube/bin/docker-machine-driver-hyperkit
```

**Comment by spowelljr** [comment]
Run `minikube delete --all --purge` and that will clear out the machine driver and then try starting minikube again and it should ask for sudo password on the following start.

**Comment by spowelljr** [comment]
Hi @ykk0612, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
