### ISSUE TITLE
Minikube issue

### ISSUE THREAD

**Issue by ganeshsnp987** [kubernetes/minikube#15275]
### What Happened?

[logs.txt](https://github.com/kubernetes/minikube/files/9926191/logs.txt)
Please check. Minikube unable to start

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/9926196/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
`sudo: crictl: command not found`

Please install crictl, https://minikube.sigs.k8s.io/docs/drivers/none/
