### ISSUE TITLE
qemu with socket_vmnet not working on macos m1

### ISSUE THREAD

**Issue by csantanapr** [kubernetes/minikube#15300]
### What Happened?

Trying the new feature to avoid having `minikube tunnel`

Using macbook m1

Followed the instructions https://minikube.sigs.k8s.io/docs/drivers/qemu/
Install vmnet
```
git clone https://github.com/lima-vm/socket_vmnet.git && cd socket_vmnet
sudo make PREFIX=/opt/socket_vmnet install
```
Had problems dhcp_leases file not found then try workaround
```
make uninstall
```
reboot
```
make install
```

Then try again 
```
minikube delete --all
minikube start --driver=qemu --network=socket_vmnet
```

Made sure no weird DNS in host `/etc/resolv.conf`

### Attach the log file

Error
```
😄  minikube v1.28.0 on Darwin 12.6.1 (arm64)
✨  Using the qemu2 (experimental) driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating qemu2 VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in qemu2 ...
🤦  StartHost failed, but will try again: creating host: create: creating: IP address never found in dhcp leases file: failed to get IP address: could not find an IP address for 26:38:e8:5a:fc:7c
🔥  Creating qemu2 VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start qemu2 VM. Running "minikube delete" may fix it: creating host: create: creating: IP address never found in dhcp leases file: failed to get IP address: could not find an IP address for 72:47:f9:c2:48:b8

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: IP address never found in dhcp leases file: failed to get IP address: could not find an IP address for 72:47:f9:c2:48:b8
```
[log.txt](https://github.com/kubernetes/minikube/files/9944350/log.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by mprimeaux** [comment]
@csantanapr Thanks for opening the issue. 

I've been using Minikube 1.28.0 today on my Mac Studio (M1 Ultra) with the `--network socket_vmnet` option and it has been working without any noticeable issue.  

I am curious as to your local network configuration in that the logs appear to indicate there are no more DHCP leases available. Would you mind reviewing [this](https://minikube.sigs.k8s.io/docs/drivers/qemu/#2-vardbdhcpd_leases-errors) section and let me know if this helps?

Would you mind posting the output of `minikube config view` so I can investigate a bit further?

**Comment by csantanapr** [comment]
@mprimeaux @spowelljr 

I tried all workarounds, including all the ones mentioned in the doc like uninstalling and rebooting still doesn't work for me 😢

**Comment by mprimeaux** [comment]
> I tried all workarounds, including all the ones mentioned in the doc like uninstalling and rebooting still doesn't work for me 😢

@csantanapr Well, that's certainly less than ideal 😞 

Would you mind posting the output of `minikube config view` and also trying the following?

From the `socket_vmnet` repo root:

```shell
git clone https://github.com/lima-vm/socket_vmnet.git && cd socket_vmnet
sudo make PREFIX=/opt/socket_vmnet uninstall
sudo make PREFIX=/opt/socket_vmnet install BRIDGED=en0
```

I'm curious if bridged mode changes anything. Note, you might need to change the value `en0` if you're only on WiFi or have multiple ethernet adapters.

**Comment by csantanapr** [comment]
Hi @mprimeaux I'm using both wifi and ethernet, your saying to configure it with ethernet interface?

**Comment by csantanapr** [comment]
Tried again uninstall and install with BRIDGED=en0
```
🤦  StartHost failed, but will try again: creating host: create: creating: IP address never found in dhcp leases file: failed to get IP address: open /var/db/dhcpd_leases: no such file or directory
🔥  Creating qemu2 VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start qemu2 VM. Running "minikube delete" may fix it: creating host: create: creating: IP address never found in dhcp leases file: failed to get IP address: open /var/db/dhcpd_leases: no such file or directory

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: IP address never found in dhcp leases file: failed to get IP address: open /var/db/dhcpd_leases: no such file or directory

```

The `minikube config view` is empty

**Comment by mprimeaux** [comment]
Hi @csantanapr. Thanks for trying that option. I suspected you'd end up with the same failure. I'll debug a bit on my end.

**Comment by causton81** [comment]
Hello, I see this too on OSX Ventura. I watched the leases file while starting minikube and the MAC address it wants only shows up after minikube gives up on polling the leases file. I suspect something is keeping the file locked and preventing the DHCP daemon from writing the assignment?

`watch grep 'a6:fc:8b:db:0:a0' /var/db/dhcpd_leases`

**Comment by aelsnz** [comment]
Just raising here, but could it be that the issue is with `bootpd` not starting/running properly for ipv4 requests.  I have seen this issue and when digging more into the details it does seem as if `socket_vmnet` is working fine, but the DHCP address never gets assigned.  I had things working, then updated to latest macOS 13.x (13.3 and then 13.3.1) and in both cases I noticed that it appears `bootpd` is not assigning the DHCP address.  While testing with enable/disable ipv6 and restarting mac things seem to start working again without any changes to socket_vmnet.  - https://github.com/lima-vm/socket_vmnet/issues/18#issuecomment-1507898184

**Comment by relivvius** [comment]
It still does not work for me also, is there any update?

**Comment by mprimeaux** [comment]
Please try the following:

```shell
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add /usr/libexec/bootpd
sudo /usr/libexec/ApplicationFirewall/socketfilterfw --unblock /usr/libexec/bootpd
```

This has worked consistently for me and others. I'll update this comment with the related issue where this was identified. I believe @spowelljr may find it faster.

**Comment by iwinux** [comment]
@mprimeaux sorry to bring up an old issue: are these 2 commands the same as adding `bootpd` to the allow list in Settings Panel "Network -> Firewall"?

**Comment by mprimeaux** [comment]
@iwinux I believe this is the case as I do see bootp in the list of firewall entries configured to "Allow incoming connections".
