### ISSUE TITLE
Getting Minikube error while starting it

### ISSUE THREAD

**Issue by senthilkumaravelu** [kubernetes/minikube#15319]
### What Happened?

When i am trying to start minikube using below command

sudo minikube start --vm-driver=none

i am getting error and the log file is attached here

### Attach the log file

[](url)
[logs.txt.txt](https://github.com/kubernetes/minikube/files/9957231/logs.txt.txt)

### Operating System

Ubuntu

**Comment by tuanaac** [comment]
@senthilkumaravelu you need to install crictl => https://github.com/kubernetes-sigs/cri-tools#install-crictl
`sudo: crictl: command not found` 

You will find the list of requirements for driver=none under https://minikube.sigs.k8s.io/docs/drivers/none/#requirements
