### ISSUE TITLE
The kubernetes server version info is wrong (minikube v0.19.0 +kubernetes v1.7.0-alpha.2)

### ISSUE THREAD

**Issue by warmchang** [kubernetes/minikube#1532]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`): v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.18.0.iso

**What happened**: the kubenetes server version is wrong (the variable is not assigned properly).

> [root@appab-myproject ~]# kubectl get nodes
> NAME       STATUS    AGE       VERSION
> minikube   Ready     1m        v1.7.0-alpha.2
> [root@appab-myproject ~]# kubectl version
> Client Version: version.Info{Major:"1", Minor:"7+", GitVersion:"v1.7.0-alpha.2", GitCommit:"9c17779924ec849dc16e8fd17d121572c9b5c8ba", GitTreeState:"clean", BuildDate:"2017-04-20T00:14:29Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
> **Server Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}**
> [root@appab-myproject ~]# minikube version
> minikube version: v0.19.0
> 

**What you expected to happen**: Should return the right version info.

**Comment by r2d4** [comment]
This is a bug upstream.  See my comment here https://github.com/kubernetes/minikube/pull/1491#issue-228426332.

**Comment by warmchang** [comment]
@r2d4 It seems to have been fixed. Thank you.
