### ISSUE TITLE
Can not set --cni-bin-dir for packaged containernetworking-plugins on Ubuntu Focal when using cri-dockerd

### ISSUE THREAD

**Issue by ianw** [kubernetes/minikube#15320]
I am trying to update our CI jobs to use Ubuntu Focal and hitting issues with networking not starting.  After some fiddling, I believe the problem is coming down to ```cri-dockerd``` starting with the wrong CNI arguments.

On Ubuntu Focal, ```containernetworking-plugins``` is a system package and puts the binaries in ```/usr/lib/cni``` -- see https://packages.ubuntu.com/focal/amd64/containernetworking-plugins/filelist

We are downloading and installing ```cri-dockerd``` as described in https://github.com/Mirantis/cri-dockerd/blob/master/README.md

From what I can tell of https://github.com/kubernetes/minikube/blob/1ade1e23997b98227a436906ff3183247e79422b/pkg/minikube/cruntime/docker.go#L675 the gist of it is

```go

const (
	CNIBinDir   = "/opt/cni/bin"
...
)

func dockerConfigureNetworkPlugin(r Docker, cr CommandRunner, networkPlugin string) error {
	args := ""
	if networkPlugin == "cni" {
		args += " --cni-bin-dir=" + CNIBinDir
 ...

	const CRIDockerServiceConfFile = "/etc/systemd/system/cri-docker.service.d/10-cni.conf"

...
ExecStart=/usr/bin/cri-dockerd --container-runtime-endpoint fd:// --network-plugin={{.NetworkPlugin}}{{.ExtraArguments}}`))
```

i.e. it writes out an override configuration file for the service that hard-codes in ```--cn-bin-dir``` to ```/opt/cni/bin```, and then runs ```cri-dockerd``` from ```/usr/bin```

Firstly the upstream commands put ```cri-dockerd``` in ```/usr/local/bin``` -- this is easy enough but both sides should agree on where it goes

I can not see any way to override the ```--cni-bin-dir``` argument?  This is right for the packages provided by the Suse kubic package repository -- but on Ubuntu Focal the upstream package is used instead.

Should this be made to probe both locations, or somehow be provided by an argument?

**Comment by afbjorklund** [comment]
If we upgrade cri-dockerd, then we don't have to set the default values anymore...

https://github.com/Mirantis/cri-dockerd/commit/e2666520e25cb302b9b1d231a63699c2338b8567

But it is **all** handled by flags at the moment, there is no configuration file for it (yet)

* https://github.com/Mirantis/cri-dockerd/issues/102

**Comment by afbjorklund** [comment]
> Firstly the upstream commands put cri-dockerd in /usr/local/bin 

I think we talked about this earlier, it depends on if you use a binary package or if you do a manual installation.

* https://github.com/kubernetes/minikube/issues/15265

**Comment by afbjorklund** [comment]
> I can not see any way to override the --cni-bin-dir argument?

This might work, perhaps ? /etc/systemd/system/cri-docker.service.d/11-local.conf

I think systemd resolves them in alphabetical order, and that you can override twice ?

**Comment by afbjorklund** [comment]
> I'm not sure if I'm mixing kubic and Ubuntu packages in an unintended way ...

There has been some talk in kubernetes (upstream), if it should use standard location and not mandate weird `/opt` locations.

But since neither CRI nor CNI is part of the project anymore, but relying on third parties and committee, progress is slow...

We still have the problem that you can't install both podman3 and kubernetes at the same time, since the config conflicts.

Other runtimes have "solved" this by keeping their own copies of the CNI plugins and the CNI config, just like in DLL Hell.

**Comment by afbjorklund** [comment]
Like so: (`--pod-infra-container-image=registry.k8s.io/pause:3.8`)

* https://github.com/kubernetes/minikube/pull/14703
