### ISSUE TITLE
Update check_install_gh.sh to actually check the gh version and update as required.

### ISSUE THREAD

**Issue by ckannon** [kubernetes/minikube#15327]
### What Happened?

Currently check_install_gh doesn't actually check, it just reinstalls gh every time.. this means it can't be included in multiple scripts without reinstalling gh over and over. Also, it installed a pinned version instead of auto-updating to latest. Both of these artifacts should be fixed.

### Attach the log file

N/A

### Operating System

macOS (Default)

### Driver

Docker

https://github.com/kubernetes/minikube/issues/15327#tasklist-block-d61e4994-14ce-422d-9b3d-2db8aef996b3

**Comment by spowelljr** [comment]
For compatibility reasons I think we should install pinned version, but we should setup a GitHub Action like we have for a lot of other things that will create PRs to update the GH in the code for us. This will prevent us from auto updating to breaking changes without breaking our CI.
