### ISSUE TITLE
"minikube cp" dosnt work if you dont give full file name in destination 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15338]
### What Happened?

if you do 
```
$ minikube cp ~/Desktop/episode1/Final.mov /tmp/
```
it wont work

but if you do 
```
$ minikube cp ~/Desktop/episode1/Final.mov /tmp/Final.mov 
```
it works

we should either support it or let the user they need to specify the full destination file name

more logs 

```
$ minikube cp ~/Desktop/episode1/Final.mov /tmp/ --alsologtostderr
I1109 16:06:40.147264   39834 out.go:296] Setting OutFile to fd 1 ...
I1109 16:06:40.147539   39834 out.go:348] isatty.IsTerminal(1) = true
I1109 16:06:40.147562   39834 out.go:309] Setting ErrFile to fd 2...
I1109 16:06:40.147572   39834 out.go:348] isatty.IsTerminal(2) = true
I1109 16:06:40.147796   39834 root.go:334] Updating PATH: /Users/medya/.minikube/bin
I1109 16:06:40.148407   39834 mustload.go:65] Loading cluster: minikube
I1109 16:06:40.148626   39834 config.go:180] Loaded profile config "minikube": Driver=qemu2, ContainerRuntime=docker, KubernetesVersion=v1.25.3
I1109 16:06:40.149482   39834 host.go:66] Checking if "minikube" exists ...
I1109 16:06:40.149710   39834 ssh_runner.go:195] Run: stat -c "%s %y" /tmp/tmp
I1109 16:06:40.149722   39834 sshutil.go:53] new ssh client: &{IP:192.168.105.11 Port:22 SSHKeyPath:/Users/medya/.minikube/machines/minikube/id_rsa Username:docker}
I1109 16:06:40.176717   39834 ssh_runner.go:356] copy: skipping /tmp/tmp (exists)

```

**Comment by ayush14rastogi** [comment]
> ### What Happened?
> if you do
> 
> ```
> $ minikube cp ~/Desktop/episode1/Final.mov /tmp/
> ```
> 
> it wont work
> 
> but if you do
> 
> ```
> $ minikube cp ~/Desktop/episode1/Final.mov /tmp/Final.mov 
> ```
> 
> it works
> 
> we should either support it or let the user they need to specify the full destination file name
> 
> more logs
> 
> ```
> $ minikube cp ~/Desktop/episode1/Final.mov /tmp/ --alsologtostderr
> I1109 16:06:40.147264   39834 out.go:296] Setting OutFile to fd 1 ...
> I1109 16:06:40.147539   39834 out.go:348] isatty.IsTerminal(1) = true
> I1109 16:06:40.147562   39834 out.go:309] Setting ErrFile to fd 2...
> I1109 16:06:40.147572   39834 out.go:348] isatty.IsTerminal(2) = true
> I1109 16:06:40.147796   39834 root.go:334] Updating PATH: /Users/medya/.minikube/bin
> I1109 16:06:40.148407   39834 mustload.go:65] Loading cluster: minikube
> I1109 16:06:40.148626   39834 config.go:180] Loaded profile config "minikube": Driver=qemu2, ContainerRuntime=docker, KubernetesVersion=v1.25.3
> I1109 16:06:40.149482   39834 host.go:66] Checking if "minikube" exists ...
> I1109 16:06:40.149710   39834 ssh_runner.go:195] Run: stat -c "%s %y" /tmp/tmp
> I1109 16:06:40.149722   39834 sshutil.go:53] new ssh client: &{IP:192.168.105.11 Port:22 SSHKeyPath:/Users/medya/.minikube/machines/minikube/id_rsa Username:docker}
> I1109 16:06:40.176717   39834 ssh_runner.go:356] copy: skipping /tmp/tmp (exists)
> ```

can you please assign this issue to me.

**Comment by NimishKashyap** [comment]
I can work on this issue.

**Comment by Abhi149209** [comment]
@NimishKashyap do you need any help .

**Comment by NimishKashyap** [comment]
@Abhi149209 Yes please. I'm not sure about adding the test files for it. I've tried adding those but it is showing file not found error while testing.

**Comment by Bhargav-InfraCloud** [comment]
@medyagh Is the issue specific to any arch? I tried the following on `Ubuntu` and I don't see any failures.
```
ll ~/File
-rw-rw-r-- 1 bhargav-infracloud bhargav-infracloud 0 Nov 19 11:42 /home/bhargav-infracloud/File

minikube cp ~/File /tmp/ 
minikube cp ~/File multinode-cluster:/tmp/
```

The versions I tried on
```
minikube version: v1.28.0
commit: 986b1ebd987211ed16f8cc10aed7d2c42fc8392f

minikube version: v1.28.0
commit: a5de48aef96e543045f1ebf11ee120fa224dfdd5

minikube version: v1.28.0
commit: e8a13c9ad048065faef05c4ea8dc200e4fcd72d4
```

**Comment by Lokesh-Jawale** [comment]
Hi is this issue resolved? If not can I work on it?
