### ISSUE TITLE
Minikube release documentation is outdated

### ISSUE THREAD

**Issue by LalatenduMohanty** [kubernetes/minikube#1534]
**This a BUG REPORT**

The Minikube release documentation [1] is outdated. It still has information about building boot2docker ISO i.e .`deploy/iso/build.sh`. 

[1] https://github.com/kubernetes/minikube/blob/master/docs/contributors/releasing_minikube.md

**Minikube version** : NA
**Environment**: NA
- **OS** : NA

**Comment by r2d4** [comment]
Yes, that documentation should point to the new ISO documentation https://github.com/kubernetes/minikube/blob/master/docs/contributors/minikube_iso.md

Feel free to send a PR or we will change it eventually.

**Comment by LalatenduMohanty** [comment]
@r2d4 Sure. I am planning to send a PR.

**Comment by r2d4** [comment]
I think this is fixed @LalatenduMohanty? Let me know if you're still planning to send some updates.
