### ISSUE TITLE
Minikube's kubectl version mismatched with installed one

### ISSUE THREAD

**Issue by Tony-Sol** [kubernetes/minikube#15346]
### What Happened?

<img width="940" alt="Screenshot 2022-11-11 at 19 09 40" src="https://user-images.githubusercontent.com/33671815/201387075-4301bb37-dafc-4fd5-ad69-5134438eef24.png">

Looks like minikube cannot start because of fails versions check

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/9991687/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by medyagh** [comment]
@Tony-Sol Kubectl mismatch means u are having a different kubectl on ur laptop and minikube downlaoded a newer version
that shouldn't be a problem

I see in the logs:
```
  docker is currently using the stargz storage driver, consider switching to overlay2 for better performance
```

mind sharing why you use stargz storage driver?

**Comment by Tony-Sol** [comment]
Disabling this experimental feature helps to start minikube
<img width="952" alt="Снимок экрана 2022-11-14 в 16 13 20" src="https://user-images.githubusercontent.com/33671815/201669165-6909ee0f-02b1-4afb-aa9a-4493f5b725ef.png">

But still there is a problem of versions mismatch - why does minikube download another kubectl if it is already exist?

**Comment by Tony-Sol** [comment]
Also, it looks like minikube downloads older version of kubectl
