### ISSUE TITLE
minikube not able to download gcr images in Iran

### ISSUE THREAD

**Issue by MahmoodKamali** [kubernetes/minikube#15350]
### What Happened?

This is a big shame on Google due to blocking Minikube to Iranians for ridiculous reasons while this tool is free payment. I, as an Iranian, ask only one question. Why this tool is blocked?

SHAME ON YOU GOOGLE

### Attach the log file

no log

**Comment by medyagh** [comment]
[MahmoodKamali](https://github.com/MahmoodKamali) there is absolutely no block against anyone regardless of location or identity, do you mind sharing logs or the output message you get?

**Comment by MahmoodKamali** [comment]
Yes, there is. I cannot run the "minikube start" command without using a VPN connection as never starts. Interestingly, I have to run a VM in the German timezone or another country where I forward all internet traffic to avoid being caught by google servers to pull the required images. Moreover, by doing this, I was able to pull only kicbase/stable:v0.0.36 image, and when it comes to pulling the gcr.io/k8s-minikube/kicbase:v0.0.36 image it stuck, and when I terminate VPN connection it declares it was unable to pull that image, however, is able to build the container. Please, if it is possible share your email address with me to send you the related pics and logs as I could not find a way to do that here.

**Comment by MahmoodKamali** [comment]
Yes, there is and I explain it in detail on the Medium website. You can read it. Many thanks for your concern.

https://medium.com/@mahmoood/step-1-40e374b6f995

**Comment by medyagh** [comment]
> Yes, there is and I explain it in detail on the Medium website. You can read it. Many thanks for your concern.
> 
> https://medium.com/@mahmoood/step-1-40e374b6f995

Thank you for providing more context on this issue, 
minikbue is an open source project, and we do not have any restriction on anywhere, and our images are stored in GCR similar to other Kubernetes projects images. 

minikube team does not put any restriction on any one, in-fact we have added special feature to help users in countries with a national firewall to bypass the restriciton. (for example "image-mirror-country" or "registry-mirror"

Our users in china also have the same problem, Chinnese users sync minikube images into Alibaba cloud, and they could bypass the firewall, and I am curious if you set your country mirror to be China ? would it help for Iran as well ?

or you could sync the minikube images to a hosting that is available to Iran (similar to our chinnese users)

please let me know if this helps you

```
minikube delete --all --purge
minikube start --image-mirror-country=cn
```

to see the description of the flags checkout:

```
$ minikube start --help | grep mirror
    --image-mirror-country='':
	Country code of the image mirror to be used. Leave empty to use the global one. For Chinese mainland users, set it to cn.
	Alternative image repository to pull docker images from. This can be used when you have limited access to gcr.io. Set it to "auto" to let minikube decide one for you. For Chinese mainland users, you may use local gcr.io mirrors such as registry.cn-hangzhou.aliyuncs.com/google_containers
    --registry-mirror=[]:
	Registry mirrors to pass to the Docker daemon

```


Again I am sorry you are facing this issue, and if you know a way to fix this issue for users in Iran, and if you contribute that PR, I would be happy to review the PR !

**Comment by MahmoodKamali** [comment]
Million thanks for your replying, patience, and concerns, however, there was no change and it was as expected. I have updated the article to see what happened after your help. Regardless of your sympathy, I have to say, this is a really BIG BIG BIG shame on gcr.io to block Iranians' access to pulling an open-source docker image. It shows how the US government has real systematic discrimination against people who have nothing to do with any kind of political action. The question is what is inside the image that Iranians are not allowed to pull it?

**Comment by MahmoodKamali** [comment]
I am wondering why you don't put the "gcr.io/k8s-minikube/kicbase:v0.0.36" image on Dockerhub while Google insists to block Iran's IP due to a ridiculous excuse.

**Comment by MahmoodKamali** [comment]
For your information, AWS has totally blocked all its services to Iranians due to sanctions. We have no access to AWS, Azure, GCP, Cloudflare, and other cloud computing services. They are paid services and due to no international banking service access, it might be justified, however, I am confused why the Minikube is like them.
I solved the problem by asking a friend of mine who lives in Canada to get remote access, and then install Virtualbox, install a Ubuntu VM on it, Install all required packages of the Minikube, then zip the VM, uploaded to a public server, then copy it on my local machine, extract the zipped file, and finally import the VM on my Virtualbox and run the VM. Such a beautiful story. :))

Finally, I would like to say a million thanks for your concern and for following up on the issue. This is a situation that we have managed like what I have done.

Best regards,

**Comment by MahmoodKamali** [comment]
First of all thank @medyagh for following up on the issue which shows how he is dedicated and thank you for replying and making clear the situation. As you said exactly, our problem is the same but with a different perspective. When a service or a website is blocked by Iran's government is it easy to bypass, but when it is banned by the source, bypassing it, is a little bit challenging as many of them blocked Iran's traffic based on the Timezone, not region or IP.  gcr.io is blocked not only based on Timezone but also other factors that I have no idea about them.
For your solution, I should say, I tried it yesterday, however, there was no success and again service could not start as desired. I think there is some garbage on my OS and need a fresh install to solve it. I uploaded what happened to me on a Medium website that you can read or have done already maybe.

https://medium.com/@mahmoood/step-1-40e374b6f995

I will install a new OS and try your solution and update you and dear @medyagh.

**Comment by aminzakizebarjad** [comment]
The issue is that now the images are drawn from gcr.io to k8s.io, the service still resides into google cloud, making it hard to achieve the service.

**Comment by younesious** [comment]
I had the same problem. unfortunately. and with 403online, shekan or begzar and ... DNS not working at all. with some VPNs for slow conn speed and limitations doesn't working. I try nekory with some configs you can find them simply in Telegram channels and pay attention to change timezone into any country except Iran. if match with VPN config it would be better. You can test it with `nslookup dl.k8s.io` command.
