### ISSUE TITLE
Dashboard does not launch with different service cluster IP range

### ISSUE THREAD

**Issue by basilfx** [kubernetes/minikube#1536]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 17.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): VirtualBox 
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.18.0
- **Install tools**: None
- **Others**: None

**What happened**: I try to change the service cluster IP range (which works) using the `--extra-config` command line option suggested [here](https://github.com/kubernetes/minikube/issues/1323#issuecomment-293606503). However, with a clean setup, it does not launch the dashboard:

```
$ minikube dashboard
Waiting, endpoint for service is not ready yet...
...
...
Waiting, endpoint for service is not ready yet...
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Temporary Error: No endpoints for service are ready yet
Temporary Error: No endpoints for service are ready yet
...
...
Temporary Error: No endpoints for service are ready yet
Error validating service: Error getting service kubernetes-dashboard: Get https://192.168.99.100:8443/api/v1/namespaces/kube-system/services/kubernetes-dashboard: dial tcp 192.168.99.100:8443: getsockopt: connection refused
```

Also, running `kubectl proxy` and navigating to `http://localhost:8001/ui` shows the following:

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}
```

**What you expected to happen**:

The dashboard should open.

**How to reproduce it** (as minimally and precisely as possible):

`minikube stop && minikube delete && minikube start --extra-config=apiserver.ServiceClusterIPRange=172.66.0.0/24`

When ready, run `minikube dashboard`.

**Anything else do we need to know**:

It does work when I create a clean cluster using only `minikube start`.

**Comment by r2d4** [comment]
Can you run `minikube logs` and ensure that ServiceClusterIPRange is actually getting set?

**Comment by basilfx** [comment]
Got the following (using v0.19.1):

```bash
basilfx:~/ $ minikube logs | grep ServiceClusterIPRange
Jun 09 11:41:23 minikube localkube[3358]: I0609 11:41:23.345293    3358 localkube.go:119] Setting ServiceClusterIPRange to 172.66.0.0/24 on apiserver.
Jun 09 11:41:23 minikube localkube[3358]: I0609 11:41:23.345465    3358 localkube.go:119] Setting ServiceClusterIPRange to 172.66.0.0/24 on apiserver.

basilfx:~/ $ minikube dashboard                   
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
^C

basilfx:~/ $ kubectl get services --all-namespaces
NAMESPACE     NAME                   CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
default       kubernetes             172.66.0.1     <none>        443/TCP        11m
kube-system   kubernetes-dashboard   172.66.0.113   <nodes>       80:30000/TCP   11m

basilfx:~/ $ minikube version
minikube version: v0.19.1
basilfx:~/ $ 
```
