### ISSUE TITLE
Unable to start minikube 

### ISSUE THREAD

**Issue by niting-dremio** [kubernetes/minikube#15375]
### What Happened?

Unable to start minikube and it is failing with below error:

`Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.22.1:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.22.1
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk

stderr:
	[WARNING Swap]: running with swap on is not supported. Please disable swap
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
	[WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W1117 16:24:58.406517    2910 certs.go:489] WARNING: could not validate bounds for certificate apiserver-kubelet-client: the certificate has expired: NotBefore: 2021-09-19 05:23:59 +0000 UTC, NotAfter: 2022-09-20 05:24:01 +0000 UTC
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: x509: certificate has expired or is not yet valid: current time 2022-11-17T16:24:58Z is after 2022-09-20T05:24:01Z
To see the stack trace of this error execute with --v=5 or higher`

### Attach the log file

I am getting below error while collecting logs:

`minikube logs --file=logs.txt
E1117 21:58:22.942038   91264 logs.go:192] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes`

### Operating System

macOS (Default)

### Driver

N/A

**Comment by JaguarsCodehub** [comment]
#### I think the problem here is with your swap turning on every time your system boots, you can disable it using the following command to shut that down:

- Disable swap first 
```sudo swapoff -a```

This issue did exists in some previous versions of **kubernetes 1.11**

If the issue still doesn't resolves and if you are running a ``Ubuntu based system`` you can try adding the fail-swap-on flag to different location.

I guess the place to add the ```--fail-swap-on=false``` flag is in ```/etc/default/kubelet file;``` not in the systemd conf file itself.

**Comment by niting-dremio** [comment]
@JaguarsCodehub - I am using Mac.
