### ISSUE TITLE
K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed

### ISSUE THREAD

**Issue by AdamhDiaz** [kubernetes/minikube#15374]
### What Happened?

Using Mac M1 Monterry 12.6 minikube failed to start due to error location kubeadm, kubectl and kubelet under  .minikube/cache/linux/arm64/v1.25.3/

I downloaded the three files manually and minikube started normally. Looks like there are some download failures to grab these packages.

Initiating transfer...
I1117 11:06:54.263029   74039 ssh_runner.go:195] Run: sudo mkdir -p /var/lib/minikube/binaries/v1.25.3
I1117 11:06:54.268788   74039 download.go:101] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubeadm.sha256 -> /Users/USERNAME/.minikube/cache/linux/arm64/v1.25.3/kubeadm
I1117 11:06:54.268800   74039 download.go:101] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubectl.sha256 -> /Users/USERNAME/.minikube/cache/linux/arm64/v1.25.3/kubectl
I1117 11:06:54.268802   74039 download.go:101] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubelet?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubelet.sha256 -> /Users/USERNAME/.minikube/cache/linux/arm64/v1.25.3/kubelet
I1117 11:06:54.418244   74039 out.go:177] 
W1117 11:06:54.435528   74039 out.go:239] ❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubeadm.sha256 Dst:/Users/USERNAME/.minikube/cache/linux/arm64/v1.25.3/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x103546218 0x103546218 0x103546218 0x103546218 0x103546218 0x103546218 0x103546218] Decompressors:map[bz2:0x103546218 gz:0x103546218 tar:0x103546218 tar.bz2:0x103546218 tar.gz:0x103546218 tar.xz:0x103546218 tar.zst:0x103546218 tbz2:0x103546218 tgz:0x103546218 txz:0x103546218 tzst:0x103546218 xz:0x103546218 zip:0x103546218 zst:0x103546218] Getters:map[file:0x14000691ab0 http:0x1400066c910 https:0x1400066c960] Dir:false ProgressListener:0x103501d40 Insecure:false DisableSymlinks:false Options:[0x1017cafa0]}: invalid checksum: Error downloading checksum file: Get "https://storage.googleapis.com/kubernetes-release/release/v1.25.3/bin/linux/arm64/kubeadm.sha256": dial tcp [2607:f8b0:4004:83f::2010]:443: connect: no route to host

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10033379/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by LIZEJU** [comment]
update  minikube 
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
sudo install minikube-linux-amd64 /usr/local/bin/minikube
----now
[mini@node ~]$ minikube version
minikube version: v1.28.0
commit: 986b1ebd987211ed16f8cc10aed7d2c42fc8392f
----old
[mini@node ~]$ minikube version
minikube version: v1.18.1
commit: 511aca80987826051cf1c6527c3da706925f7909

**Comment by LIZEJU** [comment]
minikube image ls
registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5
registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v4
registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
registry.cn-hangzhou.aliyuncs.com/google_containers/metrics-scraper:v1.0.4
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.20.2
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.20.2
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.20.2
registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.20.2
registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.13-0
registry.cn-hangzhou.aliyuncs.com/google_containers/dashboard:v2.1.0
registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.7.0
