### ISSUE TITLE
Unable to provision VM when OpenSSH-Win32 is used

### ISSUE THREAD

**Issue by gbraad** [kubernetes/minikube#1537]
**Minikube version** (use `minikube version`):
v0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
Windows
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
Hyper-V (as tested)
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
not relevant for the issue
- **Install tools**:
`choco install openssh` (from https://github.com/PowerShell/Win32-OpenSSH)
- **Others**:

**What happened**:
When trying to start minikube with `openssh-win32` on path, the provisioning of the VM will fail because minikube is unable to communicate using ssh.

**What you expected to happen**:
Successful deployment

**How to reproduce it** (as minimally and precisely as possible):
```powershell
PS> choco install openssh  # or
PS> $env:PATH += "path to openssh-win32"
PS> .\minikube-windows-amd64.exe start --vm-driver hyperv --hyperv-virtual-switch "Wireless" -v 5
```

	Starting local Kubernetes v1.6.0 cluster...
	Starting VM...
	Running pre-create checks...
	Creating machine...
	(minikube) Downloading C:\Users\gbraad\.minikube\cache\boot2docker.iso from file://C:/Users/gbraad/.minikube/cache/iso/minikube-v0.18.0.iso...
	(minikube) Creating SSH key...
	(minikube) Creating VM...
	(minikube) Using switch "Wireless"
	(minikube) Creating VHD
	(minikube) Starting VM...
	(minikube) Waiting for host to start...
	Waiting for machine to be running, this may take a few minutes...
	Detecting operating system of created instance...
	Waiting for SSH to be available...
	E0530 15:51:33.740040   11324 start.go:119] Error starting host: Error creating host: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded.
	 Retrying.
	E0530 15:51:33.741971   11324 start.go:125] Error starting host:  Error creating host: Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

**Anything else do we need to know**:
Deployment succeeds using cygwin openssh or the native implementation

**Comment by gbraad** [comment]
Related issues:
  * https://github.com/minishift/minishift/issues/957
  * https://github.com/docker/machine#3104
  * https://github.com/PowerShell/Win32-OpenSSH#738

**Comment by gbraad** [comment]
This is a duplicate of: https://github.com/kubernetes/minikube/issues/1311, and should have been fixed by https://github.com/kubernetes/minikube/pull/1141 "Force libmachine to use Native Go SSH client"

**Comment by dlorenc** [comment]
Thanks for the detailed report. A quick look at the code leads me to believe #1141 should have fixed this, like you said. I don't see anything obvious missed by that. Do you have a pointer on where the provisioner is grabbing the wrong client type?

Making this configurable SGTM too.

**Comment by gbraad** [comment]
It seems that `openssh-win32` will work targeting the end-May release. This was caused due to "certain Unix specific elements in the command line (/dev/null) that are not mapped in the Windows port yet."  https://github.com/PowerShell/Win32-OpenSSH/issues/666

From the following comment: https://github.com/docker/machine/issues/4053#issuecomment-301509027 you can see that Docker Machine offers a `--native-ssh` option instead.

I will test this in more detail tomorrow and include the findings related to the current master of `openssh-win32`

**Comment by gbraad** [comment]
Should be resolved with the release of new version of win32-openssh. Will test and close...
