### ISSUE TITLE
Host-only adapter no-longer supported in VirtualBox, but causes IF_VBOX_NOT_VISIBLE exit.

### ISSUE THREAD

**Issue by pchambre** [kubernetes/minikube#15377]
### What Happened?

Running minikube start, I get:

👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
🔄  Restarting existing virtualbox VM for "minikube" ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: driver start: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

❌  Exiting due to IF_VBOX_NOT_VISIBLE: Failed to start host: driver start: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

However, on current versions of VirtualBox on OSX (6.x, 7.x) the Host-only Adapter is marked (DEPRECATED), and selecting it gives an error that it is no-longer supported. If I edit the VM and manually switch the network adapter to the new Host-only Network, that works, and I can start the VM.

Is Minikube not compatible with newer versions of VirtualBox on OSX?

Specific versions are Minikube 1.28, OSX 13.0.1, and VirtualBox 7.0.4.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10045161/log.txt)

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by gitdanyo** [comment]
My specific versions are Minikube 1.28, OS Monterey 12.6, and VirtualBox 7.0.4

Attempted multiple uninstall and clean install of 7.0.4. I noticed the install process never prompted to "allow" in the System Preferences > Security & Privacy. Uninstalled and installed VirtualBox 6.1 where it prompted me to "allow". 

`minikube start --driver=virtualbox` works successfully.

**Comment by spowelljr** [comment]
Duplicate if https://github.com/kubernetes/minikube/issues/15274

**Comment by spowelljr** [comment]
Closing this issue, please follow along with https://github.com/kubernetes/minikube/issues/15274
