### ISSUE TITLE
Add support for ipv6

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15396]
### What Happened?

minikube currently only supports IPV4, we would like to add support for IPV6

**Comment by sharifelgamal** [comment]
This issue definitely already exists: https://github.com/kubernetes/minikube/issues/8535

**Comment by medyagh** [comment]
> This issue definitely already exists: #8535

thanks for pointing it out, closing this in favor of https://github.com/kubernetes/minikube/issues/8535
