### ISSUE TITLE
Not able to start the minikube even after installing cri-dockerd 

### ISSUE THREAD

**Issue by vpuliyal** [kubernetes/minikube#15407]
### What Happened?

# sudo -E /usr/local/bin/minikube start --driver=none 
* minikube v1.28.0 on Redhat 8.6 (ppc64le)
! Both driver=none and vm-driver=none have been set.

    Since vm-driver is deprecated, minikube will default to driver=none.

    If vm-driver is set in the global config, please run "minikube config unset vm-driver" to resolve this warning.

* Using the none driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=48, Memory=63349MB, Disk=71645MB) ...

* Exiting due to NOT_FOUND_CRI_DOCKERD:

* Suggestion:

    The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd.

    Please install cri-dockerd using these instructions:

    https://github.com/Mirantis/cri-dockerd#build-and-install

Installed cri-dockerd using `https://github.com/Mirantis/cri-dockerd` link. 
[root@cloudalplp1 home]# which cri-dockerd
/usr/local/bin/cri-dockerd
########
Here I'm attaching minikube log file also. 
[log.txt](https://github.com/kubernetes/minikube/files/10089777/log.txt)

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10089821/log.txt)

### Operating System

Redhat/Fedora

**Comment by afbjorklund** [comment]
This is a bug in RHEL7 and RHEL8 (I _think_ it was fixed in RHEL9 ?), you have to install as /usr/bin/cri-dockerd

So, `sudo which cri-dockerd` fails. The test needs to consider this, just as it is doing for `crictl` at the moment...

**Comment by vpuliyal** [comment]
]# sudo -E /usr/local/bin/minikube start --driver=none --container-runtime=''
* minikube v1.28.0 on Redhat 8.6 (ppc64le)
! Both driver=none and vm-driver=none have been set.

    Since vm-driver is deprecated, minikube will default to driver=none.

    If vm-driver is set in the global config, please run "minikube config unset vm-driver" to resolve this warning.

* Using the none driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=48, Memory=63349MB, Disk=71645MB) ...
* OS release is Red Hat Enterprise Linux 8.6 (Ootpa)

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
time="2022-11-25T02:29:37-06:00" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯


[root@cloud cri-dockerd]# sudo crictl version
FATA[0000] unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused"
[root@cloud cri-dockerd]#

# sudo which cri-dockerd
/bin/cri-dockerd

**Comment by afbjorklund** [comment]
You might get more details from `sudo systemctl status cri-docker`

**Comment by vpuliyal** [comment]
# sudo crictl version
FATA[0000] unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused"
# sudo systemctl status cri-docker
● cri-docker.service - CRI Interface for Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/cri-docker.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
     Docs: https://docs.mirantis.com

**Comment by afbjorklund** [comment]
Maybe need to look at "crictl.socket" unit, or attempt a manual "sudo systemctl start cri-docker.service" to see the error.

**Comment by afbjorklund** [comment]
Seems happy enough, except that you will also need to configure CNI networks (minikube can do this)

**Comment by vpuliyal** [comment]
@afbjorklund thanks. It's working now 

# sudo -E /usr/local/bin/minikube start --driver=none --container-runtime=''
* minikube v1.28.0 on Redhat 8.6 (ppc64le)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Red Hat Enterprise Linux 8.6 (Ootpa)
    > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s                                                                            \
    > kubectl:  41.94 MiB / 41.94 MiB [-----------] 100.00% 80.59 MiB p/s 700ms
    > kubeadm:  40.88 MiB / 40.88 MiB [------------] 100.00% 21.64 MiB p/s 2.1s
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Configuring local host environment ...
*
! The 'none' driver is designed for experts who need to integrate with an existing VM
* Most users should use the newer 'docker' driver instead, which does not require root!
* For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/
*
! kubectl and minikube configuration will be stored in /root
! To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:
*
  - sudo mv /root/.kube /root/.minikube $HOME
  - sudo chown -R $USER $HOME/.kube $HOME/.minikube
*
* This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
* Verifying Kubernetes components...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Enabled addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Comment by afbjorklund** [comment]
Ignore all the output about drivers and users and configuration, it is also broken.

**Comment by afbjorklund** [comment]
All of this is _supposed_ to work out-of-the-box, but it is not being tested (and especially not on IBM/PPC)

Unfortunately, it is bound to break even worse soon since Kubernetes 1.26 does not support Docker - yet.
