### ISSUE TITLE
Erro no minikube

### ISSUE THREAD

**Issue by marcelo-medeiros** [kubernetes/minikube#15419]
minikube start --cpus=4 --memory=6g --addons=ingress 
😄  minikube v1.28.0 on Ubuntu 22.04
✨  Using the none driver based on existing profile
❗  The 'none' driver does not respect the --cpus flag
❗  The 'none' driver does not respect the --memory flag
❗  The 'none' driver does not respect the --cpus flag
❗  The 'none' driver does not respect the --memory flag
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 22.04.1 LTS

❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

**Comment by josedonizetti** [comment]
@marcelo-medeiros você ainda está tendo esse problema? Você poderia adicionar mais informações além do log? Qual seu OS? O que estava tentando fazer? Ta usando qual driver? (docker, kvm, qemu , etc?) Qual versão do minikube vocês está utlizando? Por favor! :)
