### ISSUE TITLE
Error during mount folder

### ISSUE THREAD

**Issue by gmarano** [kubernetes/minikube#15437]
### What Happened?

Hi,

after upgrade of my os when i launch command:
`minikube mount /home/minikube/src/ /home/minikube/src/`

I'm getting the following error:

> stderr:
> mount: /home/minikube/src: mount(2) system call failed: Bad address.

This is my environment info:

`minikube version`

> minikube version: v1.28.0
> commit: 986b1ebd987211ed16f8cc10aed7d2c42fc8392f

`docker version
`
> Client: Docker Engine - Community
>  Version:           20.10.21
>  API version:       1.41
>  Go version:        go1.18.7
>  Git commit:        baeda1f
>  Built:             Tue Oct 25 18:02:16 2022
>  OS/Arch:           linux/amd64
>  Context:           default
>  Experimental:      true
> 
> Server: Docker Engine - Community
>  Engine:
>   Version:          20.10.21
>   API version:      1.41 (minimum version 1.12)
>   Go version:       go1.18.7
>   Git commit:       3056208
>   Built:            Tue Oct 25 18:00:01 2022
>   OS/Arch:          linux/amd64
>   Experimental:     false
>  containerd:
>   Version:          1.6.10
>   GitCommit:        770bd0108c32f3fb5c73ae1264f7e503fe7b2661
>  runc:
>   Version:          1.1.4
>   GitCommit:        v1.1.4-0-g5fd4c4d
>  docker-init:
>   Version:          0.19.0
>   GitCommit:        de40ad0

`uname -r -s 
`
> Linux 5.15.0-4.70.5.2.el9uek.x86_64

`cat /proc/version`

> Linux version 5.15.0-4.70.5.2.el9uek.x86_64 (mockbuild@host-100-100-224-24) (gcc (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9.4.0.2), GNU ld version 2.35.2-17.0.1.el9) #2 SMP Wed Nov 16 05:19:51 PST 2022

`cat /etc/os-release`
> NAME="Oracle Linux Server"
> VERSION="9.1"
> ID="ol"
> ID_LIKE="fedora"
> VARIANT="Server"
> VARIANT_ID="server"
> VERSION_ID="9.1"
> PLATFORM_ID="platform:el9"
> PRETTY_NAME="Oracle Linux Server 9.1"
> ANSI_COLOR="0;31"
> CPE_NAME="cpe:/o:oracle:linux:9:1:server"
> HOME_URL="https://linux.oracle.com/"
> BUG_REPORT_URL="https://github.com/oracle/oracle-linux"
> 
> ORACLE_BUGZILLA_PRODUCT="Oracle Linux 9"
> ORACLE_BUGZILLA_PRODUCT_VERSION=9.1
> ORACLE_SUPPORT_PRODUCT="Oracle Linux"
> ORACLE_SUPPORT_PRODUCT_VERSION=9.1

Any suggestions?

Thank's a lot

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10123080/log.txt)

### Operating System

Other

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @gmarano, your mount command should be in the form of `minikube mount <source directory>:<target directory>`

`source directory` should be the path on your machine that you want to mount into minikube. I'm assuming your don't have the folder `/home/minikube/src/` on your machine.
