### ISSUE TITLE
site: Multi-node page has malformed YAML

### ISSUE THREAD

**Issue by boyadzhievb** [kubernetes/minikube#15436]
Bad YAML!

**Comment by spowelljr** [comment]
Hi @boyadzhievb, we need logs or some sort of output to assist you with your issue along with a better description of what you're experiencing, thanks.

**Comment by boyadzhievb** [comment]
![image](https://user-images.githubusercontent.com/49620107/206415679-ac9e0209-650d-4868-be26-c71a4edd93d1.png)

**Comment by spowelljr** [comment]
https://minikube.sigs.k8s.io/docs/tutorials/multi_node/
