### ISSUE TITLE
minikube start error

### ISSUE THREAD

**Issue by bobbyz007** [kubernetes/minikube#15451]
### What Happened?

justin@KLVC-WXX9:~$ minikube start
😄  minikube v1.28.0 on Ubuntu 20.04
✨  Automatically selected the docker driver
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.25.3 preload ...
    > preloaded-images-k8s-v18-v1...:  385.44 MiB / 385.44 MiB  100.00% 9.35 Mi
❗  minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.36, but successfully downloaded docker.io/kicbase/stable:v0.0.36 as a fallback image
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🐳  Preparing Kubernetes v1.25.3 on Docker 20.10.20 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.25.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.25.3
[preflight] Running pre-flight checks
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 5.15.0-54-generic
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: enabled
CGROUPS_BLKIO: enabled
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost minikube] and IPs [192.168.49.2 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [localhost minikube] and IPs [192.168.49.2 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
	- 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock logs CONTAINERID'

stderr:
W1202 11:24:34.295149    1135 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
	[WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
	[WARNING SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/5.15.0-54-generic\n", err: exit status 1
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

    ▪ Generating certificates and keys ...
    ▪ Booting up control plane

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10140694/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @bobbyz007, I see your having issue connecting to `gcr.io`

`minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.36, but successfully downloaded docker.io/kicbase/stable:v0.0.36 as a fallback image`

Are you behind a proxy or firewall or located in China perhaps?

**Comment by spowelljr** [comment]
Try adding `--image-mirror-country='cn'` to your start command. That will use images from Alibaba image registry to you'll be able to access them.

**Comment by oasiszeng** [comment]
# what should i do
## system: windows11
## docker 
## comand: minikube start --image-mirror-country=cn


![image](https://user-images.githubusercontent.com/61131784/209066554-a12d8afa-7b3f-4042-b40b-8cc7182ba295.png)

**Comment by oasiszeng** [comment]
open another window execute minikube status than get a tips "WARNING: Your kubectl is pointing to stale minikube-vm.
To fix the kubectl context, run `minikube update-context`", and run that. The frist error window is down and append some new message "🔎  Verifying Kubernetes components...
    ▪ Using image registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default" .

**Comment by bobbyz007** [comment]
> Try adding `--image-mirror-country='cn'` to your start command. That will use images from Alibaba image registry that you'll be able to access them.

It does not work either by adding `--image-mirror-country='cn'`, the same error.

**Comment by shenhuaxx** [comment]
Two ways to solve this problem.
1.adding  --kubernetes-version=v1.23.8.  the kubernetes version must less than v1.23.8.
2.docker pull gcr.io/k8s-minikube/kicbase:v0.0.36  must succeed.


To put it simply, only the kicbase image downloaded from gcr.io can support the startup of high-version kubernetes clusters

**Comment by bobbyz007** [comment]
@shenhuaxx I have tried the first way, it works.

so what's the difference between the following images?  is it not the same image? can you explain a bit more?  thx.
gcr.io/k8s-minikube/kicbase:v0.0.36
docker.io/kicbase/stable:v0.0.36

**Comment by shenhuaxx** [comment]
> @shenhuaxx I have tried the first way, it works.
> 
> so what's the difference between the following images? is it not the same image? can you explain a bit more? thx. gcr.io/k8s-minikube/kicbase:v0.0.36 docker.io/kicbase/stable:v0.0.36


The IMAGE ID of the two mirrors are the same, so there should be no other difference except the name.
I think the image name should be key. It may be that the higher version of minikube is not compatible with the image name "kicbase/stable".

**Comment by shenhuaxx** [comment]
> @shenhuaxx I have tried the first way, it works.
> 
> so what's the difference between the following images? is it not the same image? can you explain a bit more? thx. gcr.io/k8s-minikube/kicbase:v0.0.36 docker.io/kicbase/stable:v0.0.36


Maybe you can use docker tag to change "kicbase/stable" to "gcr.io/k8s-minikube/kicbase". Then start minikube "minikube start". I think it should be able to start successfully.

**Comment by bobbyz007** [comment]
@shenhuaxx I 'd tested that using docker tag to change to 'gcr.io/k8s-minikube/kicbase' does not work.

**Comment by ChenxMa** [comment]
> Two ways to solve this problem. 1.adding --kubernetes-version=v1.23.8. the kubernetes version must less than v1.23.8. 2.docker pull gcr.io/k8s-minikube/kicbase:v0.0.36 must succeed.
> 
> To put it simply, only the kicbase image downloaded from gcr.io can support the startup of high-version kubernetes clusters

I have tried the first way, it started download something like kubelet. However, the initialization failed again at the kubelet-check stage. The report is as same as  before.
