### ISSUE TITLE
E0601 12:26:22.871600    2896 start.go:133] Error starting host:  Error getting state for host: machine does not exist

### ISSUE THREAD

**Issue by mevam** [kubernetes/minikube#1545]
==>minikube start --vm-driver=virtualbox                                                  /cygdrive/h/minikube 1
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
E0601 12:26:22.871600    2896 start.go:127] Error starting host: Error getting state for host: machine does not exist.

 Retrying.
E0601 12:26:22.871600    2896 start.go:133] Error starting host:  Error getting state for host: machine does not exist
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
I used win8.1 on the use of minikube cluster to create the above problems, how to solve？

**Comment by aaron-prindle** [comment]
Can you post the output of 'minikube start --v=9 --vm-driver=virtualbox'

**Comment by birdchan** [comment]
I am on osx 10.12.5, but got the same error, here is my output. I have installed minikube, kubectl, and virtualbox v.5.1.22. 

Brians-MacBook-Pro:~ brian$ minikube start --v=9 --vm-driver=virtualbox
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
Found binary path at /usr/local/bin/minikube
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:58663
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetState
(minikube) DBG | COMMAND: /usr/local/bin/VBoxManage showvminfo minikube --machinereadable
(minikube) DBG | STDOUT:
(minikube) DBG | {
(minikube) DBG | }
(minikube) DBG | STDERR:
(minikube) DBG | {
(minikube) DBG | VBoxManage: error: Could not find a registered machine named 'minikube'
(minikube) DBG | VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
(minikube) DBG | VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2781 of file VBoxManageInfo.cpp
(minikube) DBG | }
E0604 20:30:12.179713   10446 start.go:127] Error starting host: Error getting state for host: machine does not exist.

 Retrying.
E0604 20:30:12.180521   10446 start.go:133] Error starting host:  Error getting state for host: machine does not exist
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:

**Comment by Quaiks** [comment]
You get this error if you delete the virtual machine without using the minikube cli.

Just execute `minikube delete minikube` and you willl be able to start a new one.

**Comment by dlorenc** [comment]
I don't think there's a ton we can do here. Maybe improve the error message?

**Comment by lbenevid** [comment]
$ rm -rf ~/.minikube
$ minikube start

**Comment by anixnoyal** [comment]
on windows 👍 

D:\kube>minikube delete
Deleting local Kubernetes cluster...
Machine deleted.

D:\kube>minikube start
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
Downloading Minikube ISO
 90.95 MB / 90.95 MB [==============================================] 100.00% 0s

**Comment by cies** [comment]
Fix totally works. I do think that this is a bug, as in that this kind of error can trigger a message telling you that you might have "forgotten" to delete your minikube before restarting it.

**Comment by zhangxiaoyu-zidif** [comment]
oh, user may delete this VM, so if we minikube start with this error, should minikube do some cleanup make restart automatically？
