### ISSUE TITLE
Setting config "cpus" to "max" from CLI fails

### ISSUE THREAD

**Issue by Tina-otoge** [kubernetes/minikube#15468]
### What Happened?

Setting "cpus" to "max" from the CLI fails, meanwhile setting it by editing the config file found at `~/.minikube/config/config.json` works.

Interestingly enough, setting "memory" to "max" using the same command does not yield any error.
```
$ minikube config set cpus max --alsologtostderr
I1205 15:43:32.945365   48216 out.go:296] Setting OutFile to fd 1 ...
I1205 15:43:32.945532   48216 out.go:348] isatty.IsTerminal(1) = true
I1205 15:43:32.945553   48216 out.go:309] Setting ErrFile to fd 2...
I1205 15:43:32.945573   48216 out.go:348] isatty.IsTerminal(2) = true
I1205 15:43:32.945726   48216 root.go:334] Updating PATH: /home/xxxx/.minikube/bin
I1205 15:43:32.950918   48216 out.go:177] 

W1205 15:43:32.956736   48216 out.go:239] ❌  Exiting due to MK_CONFIG_SET: set: strconv.Atoi: parsing "max": invalid syntax
❌  Exiting due to MK_CONFIG_SET: set: strconv.Atoi: parsing "max": invalid syntax
W1205 15:43:32.956774   48216 out.go:239] 
```

Output for the same command with `memory` instead of `cpus`, this one works successfully
```
minikube config set memory max --alsologtostderr
I1205 16:09:55.067815   79480 out.go:296] Setting OutFile to fd 1 ...
I1205 16:09:55.068394   79480 out.go:348] isatty.IsTerminal(1) = true
I1205 16:09:55.068418   79480 out.go:309] Setting ErrFile to fd 2...
I1205 16:09:55.068437   79480 out.go:348] isatty.IsTerminal(2) = true
I1205 16:09:55.068598   79480 root.go:334] Updating PATH: /home/xxxx/.minikube/bin
W1205 16:09:55.068987   79480 out.go:239] ❗  These changes will take effect upon a minikube delete and then a minikube start
❗  These changes will take effect upon a minikube delete and then a minikube start
```

I can confirm the setting is properly read, so there is no reason for the CLI to ignore it
This is what I get in the logs during the creation of the Minikube container without the config
```
Creating docker container (CPUs=2, Memory=8000MB) 
```
This is what I get when I edit the config file manually to add `"cpus": "max"` in it
```
Creating docker container (CPUs=8, Memory=8000MB) 
```

### Attach the log file

N/A, this is before running minikube itself so there are no minikube logs generated when running this command

Issue observed on minikube version 1.26.0 and 1.28.0

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Thanks for bringing this to our attention, I've created a PR to resolve this.
