### ISSUE TITLE
unable to delete node "minikube-m02": nodes "minikube-m02" not found

### ISSUE THREAD

**Issue by xinmans** [kubernetes/minikube#15475]
### What Happened?

root@unraid:~/homelab# minikube node list
minikube	192.168.50.17
minikube-m02
minikube-m03	192.168.50.144
root@unraid:~/homelab# minikube node delete minikube-m02
🔥  Deleting node minikube-m02 from cluster minikube
E1207 17:08:08.381296    7973 node.go:122] unable to delete node "minikube-m02": nodes "minikube-m02" not found

❌  Exiting due to GUEST_NODE_DELETE: nodes "minikube-m02" not found

### Attach the log file

minikube-m02 no ip

### Operating System

Other

### Driver

KVM2

**Comment by xinmans** [comment]
OS: 
Linux unraid 5.10.28-Unraid #1 SMP Thu Apr 15 02:04:16 CST 2021 x86_64 Intel(R) Core(TM) i3-8100B CPU @ 3.60GHz GenuineIntel GNU/Linux

**Comment by spowelljr** [comment]
Hi @xinmans, either minikube-m02 wasn't started correctly on initial start, or it later got deleted outside of minikube.

Could you try deleting the entire cluster via `minikube delete` and then try starting it again and see if `minikube node list` returns an IP for minikube-m02 immediately after startup. If it was working for a while and recently stopped it would seem the container got deleted by outside of minikube.

**Comment by xinmans** [comment]
I can't minikube delete,coz I have install a few services, any other solution?
