### ISSUE TITLE
minikube mount not working with Ubuntu 17.04/virtualbox

### ISSUE THREAD

**Issue by misteragile** [kubernetes/minikube#1548]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
v0.19.1

**Environment**:
- **OS** (e.g. from /etc/os-release):
Ubuntu 17.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
Virtualbox 5.1.22
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
minikube-v0.18.0.iso
- **Install tools**:
- **Others**:

**What happened**:
The use of "minikube mount /host-mount-path:/vm-mount-path" create effectively /vm-mount-path on minikube vm, but the dir is empty despite /host-mount-path dir is not.
A file created in /vm-mount-path is also not visible in /host-mount-path.

**What you expected to happen**:
I expect to make the example describe in the "Mouting Host Folders" page working.
https://github.com/kubernetes/minikube/blob/master/docs/host_folder_mount.md

**How to reproduce it** (as minimally and precisely as possible):
Here is one of the command I've tried with log level 10 :

~/kubernetes/k8s-local-dev$ minikube mount /home/jmb/kubernetes/k8s-local-dev/:/app --v=10
Found binary path at /usr/local/bin/minikube
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:37809
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .DriverName
Mounting /home/jmb/kubernetes/k8s-local-dev/ into /app on the minikubeVM
This daemon process needs to stay alive for the mount to still be accessible...
ufs starting
Found binary path at /usr/local/bin/minikube
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:46183
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/jmb/.minikube/machines/minikube/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /home/jmb/.minikube/machines/minikube/id_rsa -p 33013] /usr/bin/ssh <nil>}
About to run SSH command:
sudo umount /app;
SSH cmd err, output: exit status 32: umount: /app: not mounted

(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/jmb/.minikube/machines/minikube/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /home/jmb/.minikube/machines/minikube/id_rsa -p 33013] /usr/bin/ssh <nil>}
About to run SSH command:

sudo mkdir -p /app || true;
sudo mount -t 9p -o trans=tcp -o port=35089 -o uid=1001 -o gid=1001 192.168.99.1 /app;
sudo chmod 775 /app;
SSH cmd err, output: <nil>: mount: mount 192.168.99.1 on /app failed: Connection timed out

Thanks for your help !

**Comment by aaron-prindle** [comment]
It seems that for some reason the mount command is not finding the correct ip to run on or there is an issue with the connection.  Can you verify what network interface the VM 'minikube' was assigned (eg: vboxnet0, etc.) and post the information here?  Once you find the name of the interface, get the ip for the interface and then run `minikube mount --ip=<the-ip-you-found>` and see if that resolves the issue.

**Comment by misteragile** [comment]
I've tried what you proposed, the network interface is vboxnet0 and the ip address is the one used on the previous log. So "minikube mount --ip=192.168.99.1" didn't change anything.
But your comment made me remember that I have installed a firewall (ufw) at some point and an access to minikube was blocked by it !

So my problem is solved, thanks a lot for your time and your help !
Do you need me to change anything on this report so it is more accurate ?

**Comment by aaron-prindle** [comment]
Nice!  We should add some documentation about firewalls and how they can potentially block 'minikube mount'  Thanks for reporting this.

**Comment by yanhongwang** [comment]
Hello @aaron-prindle , 

Minikube version (use minikube version): **v0.20.0**

Environment:
    OS: **Windows 10**
    VM Driver: Virtualbox 5.1.22 r115126
    ISO version (minikube ssh cat /etc/VERSION): v0.20.0
------------------------------------------------------------------------------------------------------
In my windows base environment, I run a Linux Mint in Virtualbox. So I think  Linux Mint probably occupy "vboxnet0", so I use --ip flag to append minikube ip.
------------------------------------------------------------------------------------------------------
minikube --v=10 mount --ip 192.168.99.106 C:\Users\yan-hong.wang\test:/mount-9p

Mounting C:\Users\yan-hong.wang\test into /mount-9p on the minikube VM
This daemon process needs to stay alive for the mount to still be accessible...
ufs starting
2017/07/05 15:29:40 listen tcp 192.168.99.106:60754: bind: The requested address is not valid in its context.
SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x11336f0] <nil>  [] 0s} 127.0.0.1 60240 <nil> <nil>}
About to run SSH command:
sudo umount /mount-9p;
SSH cmd err, output: Process exited with status 32: umount: /mount-9p: not mounted

SSH binary not found, using native Go implementation
&{{{<nil> 0 [] [] []} docker [0x11336f0] <nil>  [] 0s} 127.0.0.1 60240 <nil> <nil>}
About to run SSH command:

sudo mkdir -p /mount-9p || true;
sudo mount -t 9p -o trans=tcp -o port=60754 -o uid=1001 -o gid=1001 192.168.99.106 /mount-9p;
sudo chmod 775 /mount-9p;
SSH cmd err, output: <nil>: mount: mount 192.168.99.106 on /mount-9p failed: Connection refused
-------------------------------------------------------------------------------------------------------

But,  **v0.18.0** works well for me. That meas it doesn't matter with firewall issue in my case.

Thanks very much.

**Comment by luck02** [comment]
+1 about adding some docs around ufw and minikube... Especially mount

**Comment by mans0954** [comment]
@JeanMichelBoeuf are you able to post instructions on how you configured ufw to resolve this problem? Thanks.

**Comment by JeanMichelBoeuf** [comment]
Actually, my protection profile on gufw was set on public and I have switch it back to home. 
If you need to create some rules for minikube only I guess you can check on the report tab of gufw which protocol and port minikube ip is using for "mount" command.
