### ISSUE TITLE
 not able to start minikube on aws linux

### ISSUE THREAD

**Issue by VenkateshChella** [kubernetes/minikube#15484]
### What Happened?

minikube start --vm-driver=none
 while applying the command getting the below error. 

### Attach the log file

* minikube v1.28.0 on Amazon 2 (arm64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Amazon Linux 2

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
time="2022-12-08T12:45:26Z" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Other

### Driver

Docker

**Comment by VenkateshChella** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/111426196/206531568-ff1bd8d8-af8f-4cdf-bc2a-49e1d53ece6c.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/111426196/206531568-ff1bd8d8-af8f-4cdf-bc2a-49e1d53ece6c.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/111426196/206531568-ff1bd8d8-af8f-4cdf-bc2a-49e1d53ece6c.png">

**Comment by VenkateshChella** [comment]
<img width="788" alt="image" src="https://user-images.githubusercontent.com/111426196/206531891-eb2acc1b-33a8-4053-92ce-3da22ea0ac3c.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/111426196/206531891-eb2acc1b-33a8-4053-92ce-3da22ea0ac3c.png">
<img width="788" alt="image" src="https://user-images.githubusercontent.com/111426196/206531891-eb2acc1b-33a8-4053-92ce-3da22ea0ac3c.png">

**Comment by VenkateshChella** [comment]
[root@ip-10-60-0-88 venkatesh.chella]# crictl version
FATA[0000] unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused"

**Comment by afbjorklund** [comment]
Similar to:
* #15407

Probably problems with the docker installation (including cri-dockerd), either permissions or paths ?

**Comment by markokirsch** [comment]
solved it by creating a symlink in /usr/bin to /usr/local/bin/cri-dockerd
