### ISSUE TITLE
minikube start --vm-driver=none is now working and giving m below erorr please help. i am newbie to this

### ISSUE THREAD

**Issue by EndGaurav** [kubernetes/minikube#15507]
### What Happened?

! StartHost failed, but will try again: creating host: create: precreate: exec: "docker": executable file not found in $PATH
* Running on localhost (CPUs=2, Memory=3929MB, Disk=7755MB) ...
* Failed to start none bare metal machine. Running "minikube delete" may fix it: creating host: create: precreate: exec: "docker": executable file not found in $PATH

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: exec: "docker": executable file not found in $PATH

### Attach the log file

* ==> Audit <==
* |--------------|------------------|----------|------|---------|---------------------|---------------------|
|   Command    |       Args       | Profile  | User | Version |     Start Time      |      End Time       |
|--------------|------------------|----------|------|---------|---------------------|---------------------|
| update-check |                  | minikube | root | v1.28.0 | 13 Dec 22 06:26 UTC | 13 Dec 22 06:26 UTC |
| license      |                  | minikube | root | v1.28.0 | 13 Dec 22 06:26 UTC | 13 Dec 22 06:26 UTC |
| options      |                  | minikube | root | v1.28.0 | 13 Dec 22 06:26 UTC | 13 Dec 22 06:26 UTC |
| start        | --vm-driver=none | minikube | root | v1.28.0 | 13 Dec 22 06:29 UTC |                     |
| start        | --vm-driver=none | minikube | root | v1.28.0 | 13 Dec 22 06:31 UTC |                     |
| delete       |                  | minikube | root | v1.28.0 | 13 Dec 22 06:32 UTC | 13 Dec 22 06:32 UTC |
| start        |                  | minikube | root | v1.28.0 | 13 Dec 22 06:32 UTC |                     |
| start        | --vm-driver=none | minikube | root | v1.28.0 | 13 Dec 22 06:33 UTC |                     |
|--------------|------------------|----------|------|---------|---------------------|---------------------|

*

### Operating System

None

### Driver

None

**Comment by afbjorklund** [comment]
It is a bug, it always requires a binary called "docker" in the PATH - even if it is not used at all.
