### ISSUE TITLE
Number for the log level verbosity (--v=...) only has an effect on log_file

### ISSUE THREAD

**Issue by dvorst** [kubernetes/minikube#15509]
### What Happened?

Setting the number for the log level verbosity (--v=[number]) has no effect on the amount of text printed in the **console**. It only has an effect on the amount of text written to the **log_file**.

Running the commands below, gives the same amount of verbosity in the console.
```
minikube stop
minikube --v=0 start
minikube stop
minikube --v=1000 start
```

This is also the case with other commands, for example, with image pull:
```
minikube image rm alpine
minikube image pull --v=0 alpine
minikube image rm alpine
minikube image pull --v=1000 alpine
```
Both 'pulls' result in no text being printed to the console.

On the other hand, when the log_file is set, then a different amount is logged:
```
minikube stop
minikube --v=0 --log_file=log1.txt start
minikube stop
minikube --v=1000 --log_file=log2.txt start
```
log1.txt contains 856 lines, whereas log2.txt contains 803 lines.

If this is the desired behavior, then please specify in the documentation (and `minikube options`) that the verbosity level only applies to the log_file. Currently it gives the impression that it also applies to the info printed in the console. I was for example, trying to determine why my `minikube image pull` was not working, which lead me to finding this issue.

### Attach the log file

N/A

### Operating System

Windows

### Driver

Docker

**Comment by afbjorklund** [comment]
Probably looking for the `--alsologtostderr` flag ?

**Comment by dvorst** [comment]
Thanks, that works.

However, I think that most people assume that the verbose flag has an effect on stdout, whereas in this case, it only has an effect on stderr. It might be a good idea to specify this in the docs (and `minikube options`) such that it is clearer what this command does. Namely, that the verbose flag needs to be used in conjunction with other flags such as `--log_file` or `--alsologtostderr` as it only has an effect on stderr and not stdout.
