### ISSUE TITLE
`sudo usermod` fails due to lack of interactive terminal 

### ISSUE THREAD

**Issue by kaylendog** [kubernetes/minikube#15512]
### What Happened?

The SSH driver fails to create a cluster using the Docker runtime. It attempts to add the SSH user to the docker group using sudo, but this fails immediately since the SSH session is not interactive, and no sudo password is passed using `-S`.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10230497/log.txt)

### Operating System

Other - Manjaro using kernel 5.15.81

### Driver

SSH

**Comment by afbjorklund** [comment]
Both the none and the generic/ssh driver expect to be able to run certain commands using `sudo`

**Comment by kaylendog** [comment]
> Both the none and the generic/ssh driver expect to be able to run certain commands using `sudo`

I'm guessing you'd recommend I create a user with passwordless sudo access and use that to access the remote machine?

**Comment by afbjorklund** [comment]
There is some work underway to allow Kubernetes as a user, but it is still in alpha (and not supported by Minikube)

https://kubernetes.io/docs/tasks/administer-cluster/kubelet-in-userns/

There is support for running privileged control plane system containers with rootless, but the default is the sudo...


https://minikube.sigs.k8s.io/docs/drivers/docker/ ("Rootless Docker")

**Comment by kaylendog** [comment]
In that case I'll close this since it's expected - it's probably worth adding what you said to the docs for both? I can't seem to find much info on this.

**Comment by afbjorklund** [comment]
Adding it to the documentation sounds like a good idea
