### ISSUE TITLE
Error: netavark: unable to append rule '-d 192.168.49.0/24 -j ACCEPT' to table 'nat': code: 4, msg: iptables v1.8.8 (nf_tables)

### ISSUE THREAD

**Issue by igalvarez** [kubernetes/minikube#15520]
### What Happened?

Running minikube on almalinux9 on WSL/windows.
Using podman driver rootless or root
When start minikube I get this error

israel@~]$ minikube start --driver=podman --container-runtime=containerd
😄  minikube v1.28.0 on Almalinux 9.1 (amd64)
    ▪ MINIKUBE_ROOTLESS=true
✨  Using the podman driver based on user configuration
📌  Using rootless Podman driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.25.3 preload ...
    > preloaded-images-k8s-v18-v1...:  638.52 MiB / 638.52 MiB  100.00% 10.65 M
E1215 13:46:52.472172   15780 cache.go:203] Error downloading kic artifacts:  not yet implemented, see issue #8426
🔥  Creating podman container (CPUs=2, Memory=2200MB) ...
🤦  StartHost failed, but will try again: creating host: create: creating: create kic node: create container: podman run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --network minikube --ip 192.168.49.2 --volume minikube:/var:exec --memory=2200mb --cpus=2 -e container=podman --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 --publish=127.0.0.1::32443 gcr.io/k8s-minikube/kicbase:v0.0.36: exit status 127
stdout:

stderr:
Error: netavark: unable to append rule '-d 192.168.49.0/24 -j ACCEPT' to table 'nat': code: 4, msg: iptables v1.8.8 (nf_tables):  RULE_APPEND failed (No such file or directory): rule in chain NETAVARK-8B7E83763057B

FInd logs attached

Thanks

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10237130/logs.txt)

### Operating System

Redhat/Fedora

### Driver

Podman

**Comment by afbjorklund** [comment]
Probably want to report this to Podman upstream, or try changing back to the CNI network backend

https://www.redhat.com/sysadmin/podman-new-network-stack
