### ISSUE TITLE
Minikube Wont start on Fedora 37 with Docker Driver because Kubelet process does not start

### ISSUE THREAD

**Issue by amolgautam25** [kubernetes/minikube#15524]
### What Happened?

Fresh Installation of Fedora 37. 
Installed Docker , and installed Minikube. 
Docker seems to work fine , but minikube fails to start. 

Reason: Cant connect to kubelet service. You may inspect logs further but from what i understand , kubelet service is not being installed correctly. I will attach logs to this issue. 

After installing minikube, and after multiple failed attempts for a cluster creation i get this:
`[gamol@gamol-z01 ~]$ systemctl enable kubelet.service
Failed to enable unit: Unit file kubelet.service does not exist.
`

`[gamol@gamol-z01 ~]$ journalctl -xeu kubelet` has no entries. 

Which makes me believe that kubelet service was not installed properly.

I am on Fedora 37. Have tried with latest patches as well. 

### Attach the log file

[minikube_error.log](https://github.com/kubernetes/minikube/files/10242341/minikube_error.log)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by amolgautam25** [comment]
[minikube_error.log](https://github.com/kubernetes/minikube/files/10242345/minikube_error.log)

**Comment by afbjorklund** [comment]
You need to run the systemd commands under `minikube ssh` (on the node), not on the host.

**Comment by afbjorklund** [comment]
Sure, the self-destruct feature makes it harder to get logs (before it is deleted)

But it is still normal that there is no kubelet service in the host (only in the minikube "node")

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/3552

**Comment by mnk** [comment]
I think this problem is related to Btrfs. I can reproduce the problem when doing a Fedora 37 install with default Btrfs setup, but when selecting Ext4 for the root file system during install, Minikube 1.28.0 works almost(https://github.com/kubernetes/minikube/issues/15573) as expected.

With Btrfs, kubelet fails to start with this error message:
```
minikube kubelet[14140]: E0102 16:22:03.156579   14140 run.go:74] "command failed" err="failed to set feature gates from initial flags-based config: cannot set feature gate LocalStorageCapacityIsolation to false, feature is locked to true"
```

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/pull/15336

**Comment by mnk** [comment]
A minikube built from master as of today, seems to work fine on Fedora 37 with Btrfs and Kubernetes v1.25.3.

Until we have a new minikube release, a workaround is to run with Kubernetes version < 1.25:
```
minikube start --kubernetes-version=v1.24.9
```

**Comment by amolgautam25** [comment]
Thanks for looking into the issue. 
It seems this has been resolved. minikube version `v1.29.0` works as expected on fedora 37.
