### ISSUE TITLE
Error wile installing minikube on ubuntu 22.04

### ISSUE THREAD

**Issue by rsjamwal** [kubernetes/minikube#15533]
### What Happened?

Got below error while installing minikube:

root@ip-172-31-43-117:~/cri-dockerd#
root@ip-172-31-43-117:~/cri-dockerd# minikube start --vm-driver=none
* minikube v1.28.0 on Ubuntu 22.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 22.04.1 LTS

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

root@ip-172-31-43-117:~/cri-dockerd#

### Attach the log file

root@ip-172-31-43-117:~/cri-dockerd# minikube logs --file=logs.txt --alsologtostderr
I1219 13:44:26.735379   14707 out.go:296] Setting OutFile to fd 1 ...
I1219 13:44:26.735534   14707 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1219 13:44:26.735551   14707 out.go:309] Setting ErrFile to fd 2...
I1219 13:44:26.735564   14707 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1219 13:44:26.735698   14707 root.go:334] Updating PATH: /root/.minikube/bin
W1219 13:44:26.735840   14707 root.go:311] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I1219 13:44:26.735977   14707 out.go:296] Setting OutFile to fd 8 ...
I1219 13:44:26.736000   14707 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1219 13:44:26.736012   14707 out.go:309] Setting ErrFile to fd 8...
I1219 13:44:26.736034   14707 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1219 13:44:26.739298   14707 out.go:177] *
I1219 13:44:26.741619   14707 out.go:177] * ==> Audit <==
I1219 13:44:26.744932   14707 out.go:177] * |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   |                  | minikube | root | v1.28.0 | 19 Dec 22 12:17 UTC |          |
| start   |                  | minikube | root | v1.28.0 | 19 Dec 22 12:18 UTC |          |
| profile | list             | minikube | root | v1.28.0 | 19 Dec 22 12:18 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.28.0 | 19 Dec 22 12:18 UTC |          |
| start   |                  | minikube | root | v1.28.0 | 19 Dec 22 12:19 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.28.0 | 19 Dec 22 12:19 UTC |          |
| start   | --driver=none    | minikube | root | v1.28.0 | 19 Dec 22 13:26 UTC |          |
| start   | --driver=docker  | minikube | root | v1.28.0 | 19 Dec 22 13:26 UTC |          |
| start   | --driver=none    | minikube | root | v1.28.0 | 19 Dec 22 13:26 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.28.0 | 19 Dec 22 13:38 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

I1219 13:44:26.747199   14707 out.go:177] *
I1219 13:44:26.748946   14707 out.go:177] * ==> Last Start <==
I1219 13:44:26.754197   14707 out.go:177] * Log file created at: 2022/12/19 13:38:56
Running on machine: ip-172-31-43-117
Binary: Built with gc go1.19.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1219 13:38:56.024517   14371 out.go:296] Setting OutFile to fd 1 ...
I1219 13:38:56.024690   14371 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1219 13:38:56.024695   14371 out.go:309] Setting ErrFile to fd 2...
I1219 13:38:56.024701   14371 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1219 13:38:56.024853   14371 root.go:334] Updating PATH: /root/.minikube/bin
W1219 13:38:56.024981   14371 root.go:311] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I1219 13:38:56.025174   14371 out.go:303] Setting JSON to false
I1219 13:38:56.025951   14371 start.go:116] hostinfo: {"hostname":"ip-172-31-43-117","uptime":7826,"bootTime":1671449310,"procs":112,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.0-1026-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec2933d5-c702-5c60-66f0-acad0a915a93"}
I1219 13:38:56.027161   14371 start.go:126] virtualization: xen guest
I1219 13:38:56.029897   14371 out.go:177] * minikube v1.28.0 on Ubuntu 22.04 (xen/amd64)
W1219 13:38:56.032826   14371 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I1219 13:38:56.032841   14371 notify.go:220] Checking for updates...
I1219 13:38:56.033884   14371 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.25.3
I1219 13:38:56.034176   14371 exec_runner.go:51] Run: systemctl --version
I1219 13:38:56.036358   14371 driver.go:365] Setting default libvirt URI to qemu:///system
I1219 13:38:56.039368   14371 out.go:177] * Using the none driver based on existing profile
I1219 13:38:56.041288   14371 start.go:282] selected driver: none
I1219 13:38:56.041302   14371 start.go:808] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.36@sha256:8debc1b6a335075c5f99bfbf131b4f5566f68c6500dc5991817832e55fcc9456 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.43.117 Port:8443 KubernetesVersion:v1.25.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1219 13:38:56.041399   14371 start.go:819] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I1219 13:38:56.041422   14371 start.go:1568] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I1219 13:38:56.041857   14371 cni.go:95] Creating CNI manager for ""
I1219 13:38:56.041871   14371 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I1219 13:38:56.041881   14371 start_flags.go:317] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.36@sha256:8debc1b6a335075c5f99bfbf131b4f5566f68c6500dc5991817832e55fcc9456 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.43.117 Port:8443 KubernetesVersion:v1.25.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I1219 13:38:56.044192   14371 out.go:177] * Starting control plane node minikube in cluster minikube
I1219 13:38:56.046257   14371 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I1219 13:38:56.046467   14371 cache.go:208] Successfully downloaded all kic artifacts
I1219 13:38:56.046487   14371 start.go:364] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I1219 13:38:56.046714   14371 start.go:368] acquired machines lock for "minikube" in 210.161µs
I1219 13:38:56.046730   14371 start.go:96] Skipping create...Using existing machine configuration
I1219 13:38:56.046737   14371 fix.go:55] fixHost starting: m01
W1219 13:38:56.046904   14371 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I1219 13:38:56.046913   14371 api_server.go:165] Checking apiserver status ...
I1219 13:38:56.046938   14371 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W1219 13:38:56.063846   14371 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I1219 13:38:56.063893   14371 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I1219 13:38:56.077220   14371 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W1219 13:38:56.077252   14371 fix.go:129] unexpected machine state, will restart: <nil>
I1219 13:38:56.079605   14371 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I1219 13:38:56.082490   14371 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I1219 13:38:56.082667   14371 start.go:300] post-start starting for "minikube" (driver="none")
I1219 13:38:56.082726   14371 start.go:328] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I1219 13:38:56.082761   14371 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I1219 13:38:56.093553   14371 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I1219 13:38:56.093585   14371 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I1219 13:38:56.093597   14371 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I1219 13:38:56.096787   14371 out.go:177] * OS release is Ubuntu 22.04.1 LTS
I1219 13:38:56.098452   14371 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I1219 13:38:56.098509   14371 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I1219 13:38:56.098534   14371 start.go:303] post-start completed in 15.856933ms
I1219 13:38:56.098543   14371 fix.go:57] fixHost completed within 51.806653ms
I1219 13:38:56.098551   14371 start.go:83] releasing machines lock for "minikube", held for 51.82631ms
I1219 13:38:56.099087   14371 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I1219 13:38:56.099208   14371 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
I1219 13:38:56.135962   14371 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I1219 13:38:56.407488   14371 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I1219 13:38:56.655427   14371 exec_runner.go:51] Run: sudo systemctl daemon-reload
I1219 13:38:56.927531   14371 exec_runner.go:51] Run: sudo systemctl restart docker
I1219 13:38:57.312297   14371 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I1219 13:38:57.583748   14371 exec_runner.go:51] Run: sudo systemctl daemon-reload
I1219 13:38:57.831355   14371 exec_runner.go:51] Run: sudo systemctl start cri-docker.socket
I1219 13:38:57.845440   14371 start.go:451] Will wait 60s for socket path /var/run/cri-dockerd.sock
I1219 13:38:57.845514   14371 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I1219 13:38:57.847173   14371 start.go:472] Will wait 60s for crictl version
I1219 13:38:57.847210   14371 exec_runner.go:51] Run: sudo crictl version
I1219 13:38:57.853694   14371 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I1219 13:39:08.900598   14371 exec_runner.go:51] Run: sudo crictl version
I1219 13:39:08.909940   14371 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I1219 13:39:30.522064   14371 exec_runner.go:51] Run: sudo crictl version
I1219 13:39:30.529347   14371 retry.go:31] will retry after 26.202601198s: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found
I1219 13:39:56.732603   14371 exec_runner.go:51] Run: sudo crictl version
I1219 13:39:56.743356   14371 out.go:177]
W1219 13:39:56.746140   14371 out.go:239] X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

W1219 13:39:56.746171   14371 out.go:239] *
W1219 13:39:56.747382   14371 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I1219 13:39:56.750345   14371 out.go:177]

I1219 13:44:26.757782   14707 out.go:177] *
I1219 13:44:26.759979   14707 out.go:309] Setting ErrFile to fd 2...
I1219 13:44:26.760090   14707 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1219 13:44:26.760108   14707 out.go:296] Setting OutFile to fd 1 ...
I1219 13:44:26.760161   14707 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I1219 13:44:26.760275   14707 mustload.go:65] Loading cluster: minikube
I1219 13:44:26.760746   14707 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.25.3
I1219 13:44:26.761104   14707 exec_runner.go:51] Run: systemctl --version
W1219 13:44:26.763483   14707 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I1219 13:44:26.763569   14707 api_server.go:165] Checking apiserver status ...
I1219 13:44:26.763662   14707 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W1219 13:44:26.786523   14707 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I1219 13:44:26.786587   14707 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
root@ip-172-31-43-117:~/cri-dockerd#

### Operating System

Ubuntu

### Driver

None

**Comment by sp7infinity** [comment]
Hey @rsjamwal, did you try out the solutions mentioned in the comments section of this issue: [https://github.com/kubernetes/minikube/issues/14676](url) ?

**Comment by rsjamwal** [comment]
This issue resolved after running below command:

rm /etc/containerd/config.toml
systemctl restart containerd
