### ISSUE TITLE
Error while installing docker in chocolety

### ISSUE THREAD

**Issue by Laxmikanthkr** [kubernetes/minikube#15531]
### What Happened?

Error: unknown flag: --driver-docker
See 'minikube start --help' for usage.
PS C:\WINDOWS\system32> minikube start --driver=docker
* minikube v1.28.0 on Microsoft Windows 11 Home Single Language 10.0.22000 Build 22000

! Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "hyperv" driver, which is incompatible with requested "docker" driver.
* Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=hyperv'
                                                                                                                        PS C:\WINDOWS\system32> minikube start --driver=hyperv                                                                  * minikube v1.28.0 on Microsoft Windows 11 Home Single Language 10.0.22000 Build 22000                                  * Using the hyperv driver based on existing profile                                                                     * Starting control plane node minikube in cluster minikube                                                              * Restarting existing hyperv VM for "minikube" ...
E1218 19:49:05.043574   19236 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation.
(0x8007000E). (Virtual machine ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

! StartHost failed, but will try again: driver start: exit status 1
* Restarting existing hyperv VM for "minikube" ...
E1218 19:49:11.981242   19236 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation.
(0x8007000E). (Virtual machine ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: driver start: exit status 1

X Exiting due to GUEST_PROVISION: Failed to start host: driver start: exit status 1
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

PS C:\WINDOWS\system32>

### Attach the log file

Error: unknown flag: --driver-docker
See 'minikube start --help' for usage.
PS C:\WINDOWS\system32> minikube start --driver=docker
* minikube v1.28.0 on Microsoft Windows 11 Home Single Language 10.0.22000 Build 22000

! Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "hyperv" driver, which is incompatible with requested "docker" driver.
* Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=hyperv'
                                                                                                                        PS C:\WINDOWS\system32> minikube start --driver=hyperv                                                                  * minikube v1.28.0 on Microsoft Windows 11 Home Single Language 10.0.22000 Build 22000                                  * Using the hyperv driver based on existing profile                                                                     * Starting control plane node minikube in cluster minikube                                                              * Restarting existing hyperv VM for "minikube" ...
E1218 19:49:05.043574   19236 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation.
(0x8007000E). (Virtual machine ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

! StartHost failed, but will try again: driver start: exit status 1
* Restarting existing hyperv VM for "minikube" ...
E1218 19:49:11.981242   19236 main.go:130] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation.
(0x8007000E). (Virtual machine ID 932D42BF-A3E7-4E48-8119-F226CA70ED1D)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: driver start: exit status 1

X Exiting due to GUEST_PROVISION: Failed to start host: driver start: exit status 1
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

PS C:\WINDOWS\system32>

### Operating System

Windows

### Driver

Docker

**Comment by sp7infinity** [comment]
Hey @Laxmikanthkr, look like there is a mismatch in the driver used to create the cluster, and the one used to run it.
> ! Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "hyperv" driver, which is incompatible with requested "docker" driver.

As mentioned in the suggestion of the log file,
> Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=hyperv'

Either first delete the existing cluster (`minikube delete`) and then try running it with docker (`minikube start --driver=docker`) if you already have docker installed, or run the cluster with hyperv (`minikube start --driver=hyperv`).
