### ISSUE TITLE
minikube start fails

### ISSUE THREAD

**Issue by spundun** [kubernetes/minikube#1554]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
minikube version: v0.19.1

**Environment**:
- **OS** (e.g. from /etc/os-release): Darwin Kernel Version 16.6.0 (Mac OS 10.12.5)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
xhyve (Trying to use xhyve but not working)
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
Not sure (haven't got to the point of creating ~/.minikube/machines/minikube/config.json)
- **Install tools**:
homebrew (although I overwrote the homebrew cask install of minikube with the curl command installation)
- **Others**:

**What happened**:
```
$ minikube start --vm-driver=xhyve
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
Downloading Minikube ISO
 89.51 MB / 89.51 MB [==============================================] 100.00% 0s
E0604 17:58:26.610619   42127 start.go:127] Error starting host: Error creating host: Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 4.3.26r98988\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads".

 Retrying.
E0604 17:58:26.613179   42127 start.go:133] Error starting host:  Error creating host: Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 4.3.26r98988\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
^C
```

**What you expected to happen**:
Something like a vm starting?

**How to reproduce it** (as minimally and precisely as possible):
install all dependencies using homebrew

**Anything else do we need to know**:

**Comment by spundun** [comment]
My confusion was that I had not installed Virtual Box and why was there error about Virtual Box when I wanted to use xhyve instead?

Turns out I had installed Virtual Box a long time ago and that was interfering here.

I wasn't planning to use it and it would be nice if aborting could be avoided here.

You can close this ticket one way or another.

who/spundun :)

**Comment by aaron-prindle** [comment]
It seems that VirtualBox version 4 or lower will cause issues with xhyve, this is the error checking code you were seeing:
 https://github.com/zchee/docker-machine-driver-xhyve/blob/b449807c6788d51d0bfe5e97424f000128745db6/xhyve/xhyve.go#L380-L394

Closing for now as the check seems necessary.

**Comment by DanTulovsky** [comment]
There is now Virtualbox 6, which is > 4 but fails the check as written.

**Comment by shekhargulati** [comment]
I have Virtualbox 6 installed but I till see the above message. I saw libmachine has fixed this issue https://github.com/machine-drivers/docker-machine-driver-xhyve/commit/ac3ea1fc547d647772e4002a67d29a4afd13f32f#diff-02daf5e7eb87b145bf7eb743921650ad. Hopefully, next version of minishift will pick the latest libmachine version

**Comment by afbjorklund** [comment]
The xhyve driver (`docker-machine-driver-xhyve`) is not included with minikube, so you can install the fixed version without waiting for a new version. Hopefully the documented brew version is updated too ?

https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#xhyve-driver

**Comment by rebeccaSimmonds19** [comment]
For those with v6 VB installed 
and macOS Mojave 10.14.4
if you use this command:
`minishift start --vm-driver=virtualbox`
as you start it then it will work.
