### ISSUE TITLE
Can we use two minikube profiles at the same time? 

### ISSUE THREAD

**Issue by Hemanthbhk** [kubernetes/minikube#15548]
### What Happened?

Can we use two minikube profiles at the same time? instead of switching the profiles, is there any feasibility or possibility to run and deploy for two profiles at time.

### Attach the log file

Can we use two minikube profiles at the same time? instead of switching the profiles, is there any feasibility or possibility to run and deploy for two profiles at time.

### Operating System

None

### Driver

None

**Comment by afbjorklund** [comment]
Each profile is a cluster (and context), so you are looking for some kind of multi-cluster solution it sounds like ?

**Comment by rogeriomm** [comment]
Here there is a script that create 2 clusters. They share a DNS server(BIND) on host, so both clusters can resolve names each other, so the clusters can be interconnected(TCP/IP & DNS)

https://github.com/rogeriomm/minikube-labtools-k8s

**Comment by nirs** [comment]
Here is a tool that manages multiple minikube profiles:
https://github.com/RamenDR/ramen/tree/main/test

It is part of the Ramen project since we need to manage multiple interconnected
clusters for testing disaster recovery, but the tool is really generic and can
be used elsewhere.

**Comment by nirs** [comment]
@kant777 minikube can create 2 independent clusters out of the box.

Try this:

    minikube start -p c1 &
    minikube start -p c2 &
    wait
    minikube profile list
    kubectl get deploy -A --context c1
    kubectl get deploy -A --context c2

**Comment by kant777** [comment]
@nirs that works!!

**Comment by kant777** [comment]
can close this issue!

**Comment by kant777** [comment]
@nirs How can a pod in one profile can talk to another pod in another profile?

**Comment by nirs** [comment]
In the same way users in different clusters access other clusters. For example if a pod on
one cluster can be exposed via a service on the public cluster ip, and pod another cluster
can access the other public service.

There are some examples here:
https://minikube.sigs.k8s.io/docs/handbook/accessing/

**Comment by kant777** [comment]
@nirs Thanks again for that. I was more trying to understand how that routing would work when I have two minikube ips (one for each profile). Imagine I have pod A in profile A(cluster A) and pod B in profile B(cluster B). podA calls the dns of podB it will first go to kube-dns of cluster A and it will be a miss then it goes to host DNS which should be able to forward to kubedns in cluster B and get it resolved. is that accurate?

**Comment by Hemanthbhk** [comment]
As per above comments , we can use two minikube profiles at the same time by following below: 

minikube can create 2 independent clusters out of the box.

Try this:

minikube start -p c1 &
minikube start -p c2 &
wait
minikube profile list
kubectl get deploy -A --context c1
kubectl get deploy -A --context c2
