### ISSUE TITLE
Not able to start minikube with Kubernetes 1.26 with containerd

### ISSUE THREAD

**Issue by slashben** [kubernetes/minikube#15554]
### What Happened?

I am not able to start Kubernetes 1.26 on Ubuntu with docker.

I am running it with:
```
$ cri-dockerd --version
cri-dockerd 0.3.0 (HEAD)
$ minikube start --driver=docker --kubernetes-version=1.26.0  --feature-gates='ValidatingAdmissionPolicy=true' --container-runtime=containerd --preload=false --extra-config=kubelet.cgroup-driver=systemd
😄  minikube v1.28.0 on Ubuntu 22.10
❗  Specified Kubernetes version 1.26.0 is newer than the newest supported version: v1.25.3. Use `minikube config defaults kubernetes-version` for details.
✨  Using the docker driver based on user configuration
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=7800MB) ...
📦  Preparing Kubernetes v1.26.0 on containerd 1.6.9 ...
```

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10313272/logs.txt)
[stdout.txt](https://github.com/kubernetes/minikube/files/10313274/stdout.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Seems like this is related to the `--feature-gates='ValidatingAdmissionPolicy=true'` parameter

**Comment by slashben** [comment]
Something has changed, it indeed works without the feature gate flag (it did not seem to work before, kube-proxy was in crash loop).

To make the full story, this is the working command with the feature flag working:
```minikube start --driver=docker --kubernetes-version=1.26.0 --extra-config=apiserver.runtime-config=admissionregistration.k8s.io/v1alpha1  --feature-gates='ValidatingAdmissionPolicy=true' --container-runtime=containerd```

This can be closed I guess
