### ISSUE TITLE
Archlinux package in AUR is out of date

### ISSUE THREAD

**Issue by kadel** [kubernetes/minikube#1555]
**Is this a BUG REPORT**:

Archlinux package in AUR hasn't been updated since 0.18.0 :-(

https://aur.archlinux.org/packages/minikube/

**Comment by r2d4** [comment]
Sorry, we've been slow to automate this.  I was waiting for the 0.19.1 to push and then was on vacation.  I'll update it today, and for future reference the installer package for archlinux is located in this repo at 
https://github.com/kubernetes/minikube/tree/master/installers/linux/archlinux

We are the only ones that can push it upstream to the AUR, but gladly accept PRs to update it or modify it here.

**Comment by kadel** [comment]
Great, Thank you. I wasn't sure if it's ok to send PR if I can't sync it with AUR.
I will do that next time :wink:

**Comment by r2d4** [comment]
I've automated the process here https://github.com/kubernetes/minikube/pull/1642

So future releases should be uploaded to the AUR immediately instead of manually maintained.
