### ISSUE TITLE
Error opening service: Could not find finalized endpoint

### ISSUE THREAD

**Issue by Dmitry1987** [kubernetes/minikube#1557]
Bug report:
minikube on windows 7, can't open endpoints of services. (minikube 1.18)

example:
```
kubectl get services --all-namespaces
NAMESPACE     NAME                   CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
default       kubernetes             10.0.0.1     <none>        443/TCP         33d
kube-system   kube-dns               10.0.0.10    <none>        53/UDP,53/TCP   33d
kube-system   kubernetes-dashboard   10.0.0.128   <nodes>       80:30000/TCP    33d
kube-system   tiller-deploy          10.0.0.232   <none>        44134/TCP       2d
```
```
minikube.exe service kubernetes-dashboard

Error opening service: Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found
```
```
kubectl get endpoints --all-namespaces
NAMESPACE     NAME                      ENDPOINTS                     AGE
default       kubernetes                10.0.2.15:8443                33d
kube-system   kube-controller-manager   <none>                        14m
kube-system   kube-dns                  172.17.0.2:53,172.17.0.2:53   33d
kube-system   kube-scheduler            <none>                        14m
kube-system   kubernetes-dashboard      172.17.0.4:9090               33d
kube-system   tiller-deploy                                           2d
```

did anyone encounter this before?

P.S.  because of 'external ssh' issue, i set my PATH=''  so minikube runs with no PATH and uses internal ssh so commands work (otherwise any command fails, even 'minikube status')

thanks!

**Comment by r2d4** [comment]
You'll need to specify the namespace also, since its not in the default namespace.

`$ minikube service kubernetes-dashboard -n kube-system`
or
`$ minikube service kubernetes-dashboard --namespace kube-system`

However, the dashboard also has the shortcut
`$ minikube dashboard`

**Comment by Shubham1409** [comment]
Hi,

I tried the above command but still not getting the appropriate result.
This is the log I am getting.

C:\Kube>minikube dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found

C:\Kube>minikube dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found

C:\Kube>minikube service kubernetes-dashboard -n kube-system
Error opening service: Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found

C:\Kube>minikube service kubernetes-dashboard --namespace kube-system
Error opening service: Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found

C:\Kube>kubectl get endpoints --all-namespaces
NAMESPACE                                 NAME                      ENDPOINTS        AGE
default                                        kubernetes                10.0.2.15:8443   46m
kube-system                    kube-controller-manager   <none>           40m
kube-system                            kube-scheduler            <none>           40m

**Comment by xubo245** [comment]
I also get the error ...

**Comment by Jianyi-Ren** [comment]
same error. Would love to know the solution.

**Comment by ROOBALJINDAL** [comment]
Same issue. Any resolution?

**Comment by Dmitry1987** [comment]
oh, my friend you're a real necromancer 🤣, July 2018 hehe.
I can suggest something that is called "K3s", not sure what it is but people use it to spin up quick dev setups, you might want to try.
