### ISSUE TITLE
How can I access minikube profile with different users on Linux？

### ISSUE THREAD

**Issue by Alivers** [kubernetes/minikube#15584]
### What Happened?

Thanks for your reading.
1. I run `minikube start` with user `deployer`, `minikube profile list / minikube ip` works correctly.
2. I want access profile created above with another linux user `aliver`, but it cannot find profile when I run `minikube ip/status` etc.
How can I make it?

### Attach the log file

user:   deployer 
```
deployer@dev-server:~$ minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
deployer@dev-server:~$ minikube profile list
|----------|-----------|---------|--------------|------|---------|---------|-------|--------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes | Active |
|----------|-----------|---------|--------------|------|---------|---------|-------|--------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.25.3 | Running |     1 | *      |
|----------|-----------|---------|--------------|------|---------|---------|-------|--------|
```

user: aliver
```
[aliver@dev-server ~ ]$ minikube status
🤷  Profile "minikube" not found. Run "minikube profile list" to view all profiles.
👉  To start a cluster, run: "minikube start"

[aliver@dev-server ~ ]$ minikube profile list

🤹  Exiting due to MK_USAGE_NO_PROFILE: No minikube profile was found.
💡  Suggestion:

    You can create one using 'minikube start'.
```

### Operating System

Other

### Driver

Docker

**Comment by nirs** [comment]
This does not sound like the right way, not sure why you need to create the profile
using another user, but this may work:

Make sure both users have same shared group (e.g, minikube), and create a directory
for keeping the minikube data:

    sudo mkdir /minikube    
    sudo chown deployer:minikube /minikube
    sudo chmod g+w /minikube

Define MINIKUBE_HOME in both users .bashrc

    export MINIKUBE_HOME=/minikube

Now `minikube profile list` running the `liver` user should see the profile
created by the `deployer` user.

You may have trouble depending on how minikube set the permissions on the
files.
