### ISSUE TITLE
minikube not removing old SSH keys

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#15592]
```
$ ssh-add -L | wc -l 
15
```
I have 15 keys, but 12 of them are `/Users/user/.minikube/machines/minikube/id_rsa`

minikube should clean these up as having many keys can cause `Too many authentication failures` when trying to SSH

**Comment by msagi** [comment]
@spowelljr I'm new to minikube but this does not seem to be a too complex issue. If you could give me a bit more details, I'd be happy to give this a try 😄

**Comment by spowelljr** [comment]
I'm not sure if this is replicable on Linux & Windows, but if you have a Mac with Docker Desktop (important) installed you do the following.

1. ssh-add -L | wc -l
       4
2. minikube start --driver docker
3. kubectl create deployment hello-minikube --image=kicbase/echo-server:1.0
4. kubectl expose deployment hello-minikube --type=NodePort --port=8080
5. minikube service hello-minikube
6. ssh-add -L | wc -l
       5
7. minikube delete
8. ssh-add -L | wc -l
       5
9. minikube start --driver docker
10. kubectl create deployment hello-minikube --image=kicbase/echo-server:1.0
11. kubectl expose deployment hello-minikube --type=NodePort --port=8080
12. minikube service hello-minikube
13. ssh-add -L | wc -l
       6
14. minikube delete
15. ssh-add -L | wc -l
       6

**Comment by medyagh** [comment]
so it prabably the tunnel that we have for Docker that adds a key and not cleans up after itself

**Comment by msagi** [comment]
thank you @spowelljr and @medyagh, perfect, I have a Mac with Docker Desktop 😄 so I can give this a try. Will ping @josedonizetti if I feel a bit lost 👍🏻 

/assign

**Comment by msagi** [comment]
Hi @spowelljr, I've tried to reproduce the issue with the steps provided, but unless I'm missing something, I couldn't reproduce it.

My config
```
MacBook Pro, 15-inch, 2018, macOS 13.2.1 (22D68)
Docker Desktop Version 4.16.2 (95914)
Minikube v1.29.0 on Darwin 13.2.1
Kubernetes v1.26.1 on Docker 23.0.1
```

When I follow the steps to reproduce the issue...
```
user@mac out % ssh-add -L | wc -l
# 1
user@mac out % ./minikube start --driver docker                                      
😄  minikube v1.29.0 on Darwin 13.2.1
✨  Using the docker driver based on user configuration
📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3885MB) ...
🐳  Preparing Kubernetes v1.26.1 on Docker 23.0.1 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
user@mac out % kubectl create deployment hello-minikube --image=kicbase/echo-server:1.0
deployment.apps/hello-minikube created
user@mac out % kubectl expose deployment hello-minikube --type=NodePort --port=8080  
service/hello-minikube exposed
user@mac out % ./minikube service hello-minikube                                       
|-----------|----------------|-------------|---------------------------|
| NAMESPACE |      NAME      | TARGET PORT |            URL            |
|-----------|----------------|-------------|---------------------------|
| default   | hello-minikube |        8080 | http://192.168.49.2:32288 |
|-----------|----------------|-------------|---------------------------|
🏃  Starting tunnel for service hello-minikube.
|-----------|----------------|-------------|------------------------|
| NAMESPACE |      NAME      | TARGET PORT |          URL           |
|-----------|----------------|-------------|------------------------|
| default   | hello-minikube |             | http://127.0.0.1:61354 |
|-----------|----------------|-------------|------------------------|
🎉  Opening service default/hello-minikube in default browser...
❗  Because you are using a Docker driver on darwin, the terminal needs to be open to run it.
user@mac out % ssh-add -L | wc -l
# 1
user@mac out % ./minikube delete                                                       
🔥  Deleting "minikube" in docker ...
🔥  Deleting container "minikube" ...
🔥  Removing /Users/user/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
user@mac out % ssh-add -L | wc -l
# 1
```

Connecting to your first comment, when I run `minikube delete` then my `/Users/user/.minikube/machines` folder is deleted.

@spowelljr, @josedonizetti please advise, if there something with my config, or am I missing something? 😄
