### ISSUE TITLE
Received error: Profile "minikube" not found. Run "minikube profile list" to view all profiles.

### ISSUE THREAD

**Issue by daniel-ewing** [kubernetes/minikube#15603]
### What Happened?

I received the error provided above when trying to execute:
`sudo minikube tunnel`

I followed these steps:
Installed minikube on Ubuntu 22.04.1 LTS with Kubernetes v1.25.3 on Docker 20.10.20 using:
`minikube start --driver=docker --memory=14.5g --cpus max`
Including:
`minikube addons enable dashboard`
`minikube addons enable helm-tiller`
`minikube addons enable ingress`
Created a helm deployment that used the ingress.
Added an entry to the /etc/hosts file mapping the minikube IP to the domain used in the values.yaml, e.g.:
`192.168.49.2 example.local`
Successfully tested connectivity from the host browser to the 'example.local' domain.

I wanted to use the hosts IP instead of the minikube IP, so I successfully executed:
`sudo minikube tunnel`

After that I closed the terminal where I executed the `tunnel` commend and deleted the minikube instance:
`minikube delete --all`

Later I repeated the above steps except I skipped the step mapping the minikube IP to the domain used in the values.yaml and went directly to trying to use the hosts IP via `tunnel`:
`sudo minikube tunnel`

At this point I received the error provided above.  The output from:
`minikube profile list`
Clearly shows the profile exists and is active:
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes | Active |
|----------|-----------|---------|--------------|------|---------|---------|-------|--------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.25.3 | Running |     1 | *      |

I tried to clean everything up and start over by following these steps:
`minikube delete --all`
`docker system prune --all --volumes`
`rm -r ~/.kube`
`rm -r ~/.minikube`
`minikube start --driver=docker --memory=14.5g --cpus max`
`minikube addons enable dashboard`
`minikube addons enable helm-tiller`
`minikube addons enable ingress`
Created a helm deployment that used the ingress.
`sudo minikube tunnel`

Once again:
administrator@ubuntu:~$ sudo minikube tunnel
[sudo] password for administrator: 
🤷  Profile "minikube" not found. Run "minikube profile list" to view all profiles.
👉  To start a cluster, run: "minikube start"
administrator@ubuntu:~$ minikube profile list
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes | Active |
|----------|-----------|---------|--------------|------|---------|---------|-------|--------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.25.3 | Running |     1 | *      |

In case they are helpful, please find attached:
`minikube logs --file=logs.txt`
And several other log files.

[logs.txt](https://github.com/kubernetes/minikube/files/10363808/logs.txt)
[minikube_addons_048a94165b8d577d942bad2b46a2abbc8d228011_0.log](https://github.com/kubernetes/minikube/files/10364059/minikube_addons_048a94165b8d577d942bad2b46a2abbc8d228011_0.log)
[minikube_addons_a0fb4d0415f8406bc448d7450f92d7f95950fa20_0.log](https://github.com/kubernetes/minikube/files/10364063/minikube_addons_a0fb4d0415f8406bc448d7450f92d7f95950fa20_0.log)
[minikube_addons_b933e91f65db59500f033ede456502703e98211a_0.log](https://github.com/kubernetes/minikube/files/10364065/minikube_addons_b933e91f65db59500f033ede456502703e98211a_0.log)

### Attach the log file

attached as file.

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
This has to do with you using sudo with some commands and not others. When you're not using `sudo` it's using the minikube home directory in `/home/administrator/.minikube, but when you use `sudo` it's looking for the minikube home directory in `/.minikube` resulting in no minikube profile being found. When not using the `none` driver no `sudo` commands should be required to be used. Try running `minikube tunnel` without `sudo` and that should resolve your issue.

**Comment by daniel-ewing** [comment]
TY!
