### ISSUE TITLE
Can't enable ingress addon 

### ISSUE THREAD

**Issue by saifxd7** [kubernetes/minikube#15601]
### What Happened?

I run the command 
`minikube addons enable ingress`

And I got the Error
💡  ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS

❌  Exiting due to HOST_SAVE_PROFILE: open <UserPath>\minikube\config.json: Access is denied.

### Attach the log file
...

### Operating System

Windows

### Driver

Docker

**Comment by abdelouahabb** [comment]
You need to start first your minikube

**Comment by saifxd7** [comment]
Thanks @abdelouahabb
But I delete local cluster of minikube
`minikube delete`
start a new cluster `minikube start`

Its working after this!
