### ISSUE TITLE
How to make two minikube clusters communicate with each other?

### ISSUE THREAD

**Issue by kant777** [kubernetes/minikube#15616]
### What Happened?

I have two minikube clusters(two separate profiles) running locally call it minikube cluster A and minikube Cluster B. Each of these cluster also have an ingress and a dns associated with it locally. The dns are `hello.dnsa` and `hello.dnsb` . I am able to do ping on both of them and nslookup just like this https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/#testing

I want pod A in cluster A to be able to communicate with pod B in cluster B. How can I do that? I logged into pod A cluster A and I did `telnet hello.dnsb 80` and it doesn't get connected because I suspect there is no route. similarly I logged into pod B of cluster B and did `telnet hello.dnsb 80` and it doesnt get connected. However If I do `telnet hello.dnsb 80` or `telnet hello.dnsb 80` from my host machine, telnet works!

Any simple way to solve this problem for now?

In a way my question is very similar to this except in my case both of the clusters are running locally https://github.com/kubernetes/minikube/issues/14278

### Attach the log file

minkube 

### Operating System

Ubuntu

### Driver

Docker

**Comment by rogeriomm** [comment]
https://github.com/rogeriomm/minikube-labtools-k8s/blob/master/install/src/minikube.go#L57
https://github.com/rogeriomm/minikube-labtools-k8s/blob/master/install/scripts/bind/named.conf.local
https://github.com/rogeriomm/minikube-labtools-k8s/blob/1605589721ec25b89a7d82ba47acbdf9b870733e/install/scripts/minikube-lib.sh#L80
https://github.com/rogeriomm/minikube-labtools-k8s/blob/1605589721ec25b89a7d82ba47acbdf9b870733e/install/scripts/minikube-lib.sh#L101

**Comment by kant777** [comment]
@rogeriomm I am using the default driver which is docker so I am trying to map some of your pointers to my environment..any suggestions?

**Comment by kant777** [comment]
1. Do these run on a host or inside the container?
2. I tried `sudo route -n add 10.112.0.0/12 192.168.49.2` on both host and inside the minikube container

I get the following error

```
route: netmask 000fffff doesn't make sense with host route
```
192.168.49.2 = minikube ip -p p1
10.112.0.0/12  = I used as a service cluster ip range for profile p1
