### ISSUE TITLE
Failed to pull image : rpc error: code = Unknown desc = context deadline exceeded

### ISSUE THREAD

**Issue by Rapter1990** [kubernetes/minikube#15626]
### What Happened?

I have a problem about deploying all spring boot microservices to Kubernetes.

I use minikube to open kubernetes dashboard through all these commands shown below.

    1 ) minikube start
    2 ) minikube dashboard

Next, I run `kubectl apply -f k8s` to deploy all services to Kubernetes.

I get errors shown below.

    Auth Service -> Failed to pull image "noyandocker/authservice": rpc error: code = Unknown desc = context deadline exceeded
    
    Api gateway -> Failed to pull image "noyandocker/apigateway": rpc error: code = Unknown desc = context deadline exceeded
    
    Config server -> Failed to pull image "noyandocker/configserver": rpc error: code = Unknown desc = context deadline exceeded
    
    Order Service -> Failed to pull image "noyandocker/orderservice": rpc error: code = Unknown desc = context deadline exceeded
    
    Payment Service -> Failed to pull image "noyandocker/paymentservice": rpc error: code = Unknown desc = context deadline exceeded
    
    Product Service -> Failed to pull image "noyandocker/productservice": rpc error: code = Unknown desc = Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on 192.168.65.2:53: read udp 192.168.49.2:59506->192.168.65.2:53: i/o timeout
    
    Mysql -> Show always "Pending" -> The selected container has not logged any messages yet.
    
    Eureka -> container "eureka" in pod "eureka-0" is waiting to start: trying and failing to pull image

Here is the screenshot folder :[Link][1]

Here is the docker hub : [Link][2]

Here is the repo : [Link][3]

How can I fix all these issues?

  [1]: https://drive.google.com/drive/folders/1nwPCDDIZ3_Go4YmJz5wG7rRF1pt7Bo4b?usp=share_link
  [2]: https://hub.docker.com/search?q=noyandocker
  [3]: https://github.com/Rapter1990/springbootmicroservicedailybuffer

### Attach the log file

I showed the error message above

### Operating System

Windows

### Driver

Docker

**Comment by eostis** [comment]
Same error when the image pulled is too big apparently:
`Failed to pull image "docker.io/semitechnologies/transformers-inference:distilbert-base-uncased": rpc error: code = Unknown desc = context deadline exceeded
`
Related to https://github.com/kubernetes/minikube/issues/14806 ?

**Comment by Rapter1990** [comment]
@eostis After I defined `imagePullPolicy `as `IfNotPresent `instead of `always `and then the issue disappeared.
