### ISSUE TITLE
How install  minikube in environment without  internet 

### ISSUE THREAD

**Issue by roham1371** [kubernetes/minikube#15641]
### What Happened?

Please help me
How install minikube in environment that internet is not found 

### Attach the log file

Help

### Operating System

Ubuntu

### Driver

Docker

**Comment by devarsh10** [comment]
Hey,
To install minikube you need:
1. Docker desktop up and running.
2. If possible Enable kuberneters (In docker desktop: Settings -> Kubernetes -> Enable K8s).
3. Then in terminal or windows powershell run minikube start. It will download required images needed to create the architecture. In which, internet is needed.

And then your minikube will up and running. Then you can use kubectl commands.

According to me, you cannot install minikube without internet.
But after installation you can use minikube start without internet. It'll work.

I hope, you get your required answer.
Regards,
Devarsh.
