### ISSUE TITLE
minikube v1.28.0 on Darwin 13.1 (arm64) - creating host: create: provisioning: ssh command error on Docker version 20.10.22, build 3a2c30b

### ISSUE THREAD

**Issue by nico-arianto** [kubernetes/minikube#15640]
### What Happened?

I0113 23:19:04.429817   11666 out.go:296] Setting OutFile to fd 1 ...
I0113 23:19:04.429955   11666 out.go:348] isatty.IsTerminal(1) = true
I0113 23:19:04.429960   11666 out.go:309] Setting ErrFile to fd 2...
I0113 23:19:04.429964   11666 out.go:348] isatty.IsTerminal(2) = true
I0113 23:19:04.430032   11666 root.go:334] Updating PATH: /Users/nico.arianto/.minikube/bin
I0113 23:19:04.431796   11666 out.go:303] Setting JSON to false
I0113 23:19:04.453037   11666 start.go:116] hostinfo: {"hostname":"Nicos-MacBook-Pro.local","uptime":2682,"bootTime":1673620462,"procs":534,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"13.1","kernelVersion":"22.2.0","kernelArch":"arm64","virtualizationSystem":"","virtualizationRole":"","hostId":"c965f711-6493-5f96-b5fa-2a6bb9c60df3"}
W0113 23:19:04.453169   11666 start.go:124] gopshost.Virtualization returned error: not implemented yet
I0113 23:19:04.461801   11666 out.go:177] 😄  minikube v1.28.0 on Darwin 13.1 (arm64)
😄  minikube v1.28.0 on Darwin 13.1 (arm64)
I0113 23:19:04.471831   11666 notify.go:220] Checking for updates...
I0113 23:19:04.472156   11666 config.go:180] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.25.3
I0113 23:19:04.472186   11666 driver.go:365] Setting default libvirt URI to qemu:///system
I0113 23:19:04.535444   11666 docker.go:137] docker version: linux-20.10.22
I0113 23:19:04.535557   11666 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I0113 23:19:04.660890   11666 info.go:266] docker info: {ID:UZN4:LEZX:XCSO:2GYV:2KUV:XX72:HJ4P:HO3C:BPMZ:A7JZ:RNXV:UCWU Containers:1 ContainersRunning:1 ContainersPaused:0 ContainersStopped:0 Images:15 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:60 OomKillDisable:false NGoroutines:58 SystemTime:2023-01-13 15:19:04.576611168 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:6 KernelVersion:5.15.49-linuxkit OperatingSystem:Docker Desktop OSType:linux Architecture:aarch64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:5 MemTotal:8232894464 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy:http.docker.internal:3128 HTTPSProxy:http.docker.internal:3128 NoProxy:hubproxy.docker.internal Name:docker-desktop Labels:[] ExperimentalBuild:false ServerVersion:20.10.22 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:9ba4b250366a5ddde94bb7c9d1def331423aa323 Expected:9ba4b250366a5ddde94bb7c9d1def331423aa323} RuncCommit:{ID:v1.1.4-0-g5fd4c4d Expected:v1.1.4-0-g5fd4c4d} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Name:buildx Path:/Users/nico.arianto/.docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-buildx] ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.10.0] map[Name:compose Path:/Users/nico.arianto/.docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-compose] ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.15.1] map[Name:dev Path:/Users/nico.arianto/.docker/cli-plugins/docker-dev SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-dev] ShortDescription:Docker Dev Environments Vendor:Docker Inc. Version:v0.0.5] map[Name:extension Path:/Users/nico.arianto/.docker/cli-plugins/docker-extension SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-extension] ShortDescription:Manages Docker extensions Vendor:Docker Inc. Version:v0.2.17] map[Name:sbom Path:/Users/nico.arianto/.docker/cli-plugins/docker-sbom SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-sbom] ShortDescription:View the packaged-based Software Bill Of Materials (SBOM) for an image URL:https://github.com/docker/sbom-cli-plugin Vendor:Anchore Inc. Version:0.6.0] map[Name:scan Path:/Users/nico.arianto/.docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-scan] ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.23.0]] Warnings:<nil>}}
I0113 23:19:04.670073   11666 out.go:177] ✨  Using the docker driver based on existing profile
✨  Using the docker driver based on existing profile
I0113 23:19:04.674333   11666 start.go:282] selected driver: docker
I0113 23:19:04.674339   11666 start.go:808] validating driver "docker" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.36@sha256:8debc1b6a335075c5f99bfbf131b4f5566f68c6500dc5991817832e55fcc9456 Memory:7803 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.25.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/Users:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I0113 23:19:04.674404   11666 start.go:819] status for docker: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0113 23:19:04.674517   11666 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I0113 23:19:04.799380   11666 info.go:266] docker info: {ID:UZN4:LEZX:XCSO:2GYV:2KUV:XX72:HJ4P:HO3C:BPMZ:A7JZ:RNXV:UCWU Containers:1 ContainersRunning:1 ContainersPaused:0 ContainersStopped:0 Images:15 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:60 OomKillDisable:false NGoroutines:58 SystemTime:2023-01-13 15:19:04.715543751 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:6 KernelVersion:5.15.49-linuxkit OperatingSystem:Docker Desktop OSType:linux Architecture:aarch64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:5 MemTotal:8232894464 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy:http.docker.internal:3128 HTTPSProxy:http.docker.internal:3128 NoProxy:hubproxy.docker.internal Name:docker-desktop Labels:[] ExperimentalBuild:false ServerVersion:20.10.22 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:9ba4b250366a5ddde94bb7c9d1def331423aa323 Expected:9ba4b250366a5ddde94bb7c9d1def331423aa323} RuncCommit:{ID:v1.1.4-0-g5fd4c4d Expected:v1.1.4-0-g5fd4c4d} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=default name=cgroupns] ProductLicense: Warnings:<nil> ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Name:buildx Path:/Users/nico.arianto/.docker/cli-plugins/docker-buildx SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-buildx] ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.10.0] map[Name:compose Path:/Users/nico.arianto/.docker/cli-plugins/docker-compose SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-compose] ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.15.1] map[Name:dev Path:/Users/nico.arianto/.docker/cli-plugins/docker-dev SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-dev] ShortDescription:Docker Dev Environments Vendor:Docker Inc. Version:v0.0.5] map[Name:extension Path:/Users/nico.arianto/.docker/cli-plugins/docker-extension SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-extension] ShortDescription:Manages Docker extensions Vendor:Docker Inc. Version:v0.2.17] map[Name:sbom Path:/Users/nico.arianto/.docker/cli-plugins/docker-sbom SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-sbom] ShortDescription:View the packaged-based Software Bill Of Materials (SBOM) for an image URL:https://github.com/docker/sbom-cli-plugin Vendor:Anchore Inc. Version:0.6.0] map[Name:scan Path:/Users/nico.arianto/.docker/cli-plugins/docker-scan SchemaVersion:0.1.0 ShadowedPaths:[/usr/local/lib/docker/cli-plugins/docker-scan] ShortDescription:Docker Scan Vendor:Docker Inc. Version:v0.23.0]] Warnings:<nil>}}
I0113 23:19:04.799632   11666 cni.go:95] Creating CNI manager for ""
I0113 23:19:04.799639   11666 cni.go:169] CNI unnecessary in this configuration, recommending no CNI
I0113 23:19:04.799651   11666 start_flags.go:317] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.36@sha256:8debc1b6a335075c5f99bfbf131b4f5566f68c6500dc5991817832e55fcc9456 Memory:7803 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.25.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.25.3 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/Users:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath:/opt/socket_vmnet/bin/socket_vmnet_client SocketVMnetPath:/var/run/socket_vmnet}
I0113 23:19:04.808996   11666 out.go:177] 👍  Starting control plane node minikube in cluster minikube
👍  Starting control plane node minikube in cluster minikube
I0113 23:19:04.812920   11666 cache.go:120] Beginning downloading kic base image for docker with docker
I0113 23:19:04.816997   11666 out.go:177] 🚜  Pulling base image ...
🚜  Pulling base image ...
I0113 23:19:04.826932   11666 preload.go:132] Checking if preload exists for k8s version v1.25.3 and runtime docker
I0113 23:19:04.826939   11666 image.go:76] Checking for gcr.io/k8s-minikube/kicbase:v0.0.36@sha256:8debc1b6a335075c5f99bfbf131b4f5566f68c6500dc5991817832e55fcc9456 in local docker daemon
I0113 23:19:04.826972   11666 preload.go:148] Found local preload: /Users/nico.arianto/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.25.3-docker-overlay2-arm64.tar.lz4
I0113 23:19:04.826978   11666 cache.go:57] Caching tarball of preloaded images
I0113 23:19:04.827060   11666 preload.go:174] Found /Users/nico.arianto/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.25.3-docker-overlay2-arm64.tar.lz4 in cache, skipping download
I0113 23:19:04.827067   11666 cache.go:60] Finished verifying existence of preloaded tar for  v1.25.3 on docker
I0113 23:19:04.827562   11666 profile.go:148] Saving config to /Users/nico.arianto/.minikube/profiles/minikube/config.json ...
I0113 23:19:04.893645   11666 image.go:80] Found gcr.io/k8s-minikube/kicbase:v0.0.36@sha256:8debc1b6a335075c5f99bfbf131b4f5566f68c6500dc5991817832e55fcc9456 in local docker daemon, skipping pull
I0113 23:19:04.893673   11666 cache.go:142] gcr.io/k8s-minikube/kicbase:v0.0.36@sha256:8debc1b6a335075c5f99bfbf131b4f5566f68c6500dc5991817832e55fcc9456 exists in daemon, skipping load
I0113 23:19:04.893682   11666 cache.go:208] Successfully downloaded all kic artifacts
I0113 23:19:04.893743   11666 start.go:364] acquiring machines lock for minikube: {Name:mkb58486eb4d13a923c6a69bb453947301a84272 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0113 23:19:04.893841   11666 start.go:368] acquired machines lock for "minikube" in 74.417µs
I0113 23:19:04.893868   11666 start.go:96] Skipping create...Using existing machine configuration
I0113 23:19:04.893873   11666 fix.go:55] fixHost starting: 
I0113 23:19:04.894144   11666 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0113 23:19:04.946007   11666 fix.go:103] recreateIfNeeded on minikube: state=Running err=<nil>
W0113 23:19:04.946057   11666 fix.go:129] unexpected machine state, will restart: <nil>
I0113 23:19:04.953116   11666 out.go:177] 🏃  Updating the running docker "minikube" container ...
🏃  Updating the running docker "minikube" container ...
I0113 23:19:04.957142   11666 machine.go:88] provisioning docker machine ...
I0113 23:19:04.957166   11666 ubuntu.go:169] provisioning hostname "minikube"
I0113 23:19:04.957267   11666 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0113 23:19:05.016262   11666 main.go:134] libmachine: Using SSH client type: native
I0113 23:19:05.016474   11666 main.go:134] libmachine: &{{{<nil> 0 [] [] []} docker [0x104a88a30] 0x104a8b4d0 <nil>  [] 0s} 127.0.0.1 50655 <nil> <nil>}
I0113 23:19:05.016486   11666 main.go:134] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0113 23:19:05.168474   11666 main.go:134] libmachine: SSH cmd err, output: Process exited with status 1: sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

I0113 23:19:05.168499   11666 machine.go:91] provisioned docker machine in 211.342875ms
I0113 23:19:05.168721   11666 ssh_runner.go:195] Run: sh -c "df -h /var | awk 'NR==2{print $5}'"
I0113 23:19:05.168795   11666 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0113 23:19:05.233111   11666 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:50655 SSHKeyPath:/Users/nico.arianto/.minikube/machines/minikube/id_rsa Username:docker}
I0113 23:19:05.344365   11666 ssh_runner.go:195] Run: sh -c "df -BG /var | awk 'NR==2{print $4}'"
I0113 23:19:05.353971   11666 fix.go:57] fixHost completed within 460.077542ms
I0113 23:19:05.354016   11666 start.go:83] releasing machines lock for "minikube", held for 460.1535ms
W0113 23:19:05.354048   11666 start.go:603] error starting host: provision: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
W0113 23:19:05.354308   11666 out.go:239] 🤦  StartHost failed, but will try again: provision: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

🤦  StartHost failed, but will try again: provision: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

I0113 23:19:05.354358   11666 start.go:618] Will try again in 5 seconds ...
I0113 23:19:10.355879   11666 start.go:364] acquiring machines lock for minikube: {Name:mkb58486eb4d13a923c6a69bb453947301a84272 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0113 23:19:10.356508   11666 start.go:368] acquired machines lock for "minikube" in 478.042µs
I0113 23:19:10.356700   11666 start.go:96] Skipping create...Using existing machine configuration
I0113 23:19:10.356728   11666 fix.go:55] fixHost starting: 
I0113 23:19:10.357945   11666 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0113 23:19:10.436804   11666 fix.go:103] recreateIfNeeded on minikube: state=Running err=<nil>
W0113 23:19:10.436838   11666 fix.go:129] unexpected machine state, will restart: <nil>
I0113 23:19:10.442234   11666 out.go:177] 🏃  Updating the running docker "minikube" container ...
🏃  Updating the running docker "minikube" container ...
I0113 23:19:10.449284   11666 machine.go:88] provisioning docker machine ...
I0113 23:19:10.449317   11666 ubuntu.go:169] provisioning hostname "minikube"
I0113 23:19:10.449419   11666 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0113 23:19:10.506486   11666 main.go:134] libmachine: Using SSH client type: native
I0113 23:19:10.506636   11666 main.go:134] libmachine: &{{{<nil> 0 [] [] []} docker [0x104a88a30] 0x104a8b4d0 <nil>  [] 0s} 127.0.0.1 50655 <nil> <nil>}
I0113 23:19:10.506644   11666 main.go:134] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0113 23:19:10.666097   11666 main.go:134] libmachine: SSH cmd err, output: Process exited with status 1: sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

I0113 23:19:10.666124   11666 machine.go:91] provisioned docker machine in 216.823541ms
I0113 23:19:10.666293   11666 ssh_runner.go:195] Run: sh -c "df -h /var | awk 'NR==2{print $5}'"
I0113 23:19:10.666376   11666 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0113 23:19:10.728366   11666 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:50655 SSHKeyPath:/Users/nico.arianto/.minikube/machines/minikube/id_rsa Username:docker}
I0113 23:19:10.838781   11666 ssh_runner.go:195] Run: sh -c "df -BG /var | awk 'NR==2{print $4}'"
I0113 23:19:10.848867   11666 fix.go:57] fixHost completed within 492.117625ms
I0113 23:19:10.848901   11666 start.go:83] releasing machines lock for "minikube", held for 492.35ms
W0113 23:19:10.849209   11666 out.go:239] 😿  Failed to start docker container. Running "minikube delete" may fix it: provision: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

😿  Failed to start docker container. Running "minikube delete" may fix it: provision: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

I0113 23:19:10.857700   11666 out.go:177] 

W0113 23:19:10.861797   11666 out.go:239] ❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

❌  Exiting due to GUEST_PROVISION: Failed to start host: provision: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?

W0113 23:19:10.861821   11666 out.go:239] 

W0113 23:19:10.862894   11666 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0113 23:19:10.872708   11666 out.go:177] 

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10412820/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by michaeljohn32** [comment]
This morning, I upgraded both minikube and docker to the versions listed in the title, and confirm that this issue exists.  I did `minikube delete` and the problem persists.

**Comment by michaeljohn32** [comment]
Downgrading to Docker 20.10.21, build 3056208 does allow minikube start up, so appears to be related to new docker features

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/15634

It's not the Docker version, but the Docker Desktop version

**Comment by nico-arianto** [comment]
Update: fixed in Docker Desktop 4.16.1 --> https://github.com/docker/for-mac/issues/6675
