### ISSUE TITLE
Unable to start minikube start --driver=docker

### ISSUE THREAD

**Issue by ashish-tiwari-11** [kubernetes/minikube#15643]
### What Happened?

while running minikube start --driver=docker its failing.

### Attach the log file

minikube logs --file=logs.txt
E0114 00:13:55.268113    7184 logs.go:192] command /bin/bash -c "sudo journalctl -u docker -n 60" failed with error: /bin/bash -c "sudo journalctl -u docker -n 60": Process exited with status 1
stdout:

stderr:
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
 output: "\n** stderr ** \nsudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n\n** /stderr **"
E0114 00:13:55.278519    7184 logs.go:192] command /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a" failed with error: /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a": Process exited with status 1
stdout:

stderr:
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
 output: "\n** stderr ** \nsudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\nsudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n\n** /stderr **"
E0114 00:13:55.287504    7184 logs.go:192] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.25.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.25.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
 output: "\n** stderr ** \nsudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n\n** /stderr **"
E0114 00:13:55.316223    7184 logs.go:192] command /bin/bash -c "sudo journalctl -u kubelet -n 60" failed with error: /bin/bash -c "sudo journalctl -u kubelet -n 60": Process exited with status 1
stdout:

stderr:
sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?
 output: "\n** stderr ** \nsudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n\n** /stderr **"

❗  unable to fetch logs for: Docker, container status, describe nodes, kubelet

### Operating System

Windows

### Driver

Docker

**Comment by tharun634** [comment]
Updating to [Docker v4.16.1](https://docs.docker.com/desktop/release-notes/#bug-fixes-and-enhancements) fixed it for me

**Comment by spowelljr** [comment]
As @tharun634 said, this was a regression with Docker Desktop 4.16.0, updating to 4.16.1 or greater will resolve this.
