### ISSUE TITLE
Failed to start minikube with qemu as driver and use socket_vmnet as network from Apple M1 Pro machine

### ISSUE THREAD

**Issue by nkjaneqiu** [kubernetes/minikube#15648]
### What Happened?

CMD: minikube start --driver=qemu --memory 4Gb --network=socket_vmnet
socket_vmnet is installed
Error:
Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
	- 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'crictl --runtime-endpoint unix:///var/run/cri-dockerd.sock logs CONTAINERID'

stderr:
W0114 07:21:06.260428    3306 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

### Attach the log file

[logs_all.txt](https://github.com/kubernetes/minikube/files/10416877/logs_all.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by mwei1us** [comment]
Had a similar issue yesterday. Resolved by unset DOCKER_HOST and switch to the correct docker context

unset DOCKER_HOST
docker context ls
docker context use <the correct one>
minikube start
