### ISSUE TITLE
Outdated description of minikube in upstream documentation

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#15651]
The "Learn Kubernetes Basic" section of the kubernetes.io website is getting an overhaul, in light of the Katacoda shutdown.

https://kubernetes.io/docs/tutorials/kubernetes-basics/

There is one "Hello, Minikube" tutorial, that is fairly identical to get "Getting Started" and might end up just getting moved...

https://kubernetes.io/docs/tutorials/hello-minikube/

Theoretically it would be possible to do _three_ different tutorials:

1) Hello, (Cloud) Minikube
  This would require that minikube had some way of starting new cloud instances (VMs). Currently, it does not.

2) Hello, (Docker) Minikube
  This would require that either docker or podman is installed, but it also means a more complex environment.

2) Hello, (Native) Minikube
  This is the current scenario. It uses a pre-allocated virtual machine, and then installs everything locally on it.

But most likely, they will just refer to each project's documentation:

* `minikube`: https://minikube.sigs.k8s.io/docs/

* `kind`: https://kind.sigs.k8s.io/docs/

* `kubeadm`: https://kubernetes.io/docs/reference/setup-tools/kubeadm/

So that the user can pick their preferred method and tool of deployment.

And the Kubernetes tutorial will start, when the cluster is already available ?

```
kubectl cluster-info
```

----

But then there is another section, "Create Cluster", that will need revising. It is based on an earlier definition of minikube.

https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/

I will break it down here, and then we can work with SIG Docs about updating it for next time (without Katacoda).

https://kubernetes.io/docs/tutorials/kubernetes-basics/create-cluster/cluster-intro/

Objectives
* Learn what a Kubernetes cluster is.
* **Learn what Minikube is.**
* Start a Kubernetes cluster using an online terminal.

Here is the section on what minikube is:

> A Kubernetes cluster can be deployed on either physical or virtual machines.

So far, so good.

> To get started with Kubernetes development, you can use Minikube.

This is currently breaking down, into three different paths to set up a "Learning Environment":

* "Getting Started" -> redirecting to https://kubernetes.io/docs/setup/ ?

  * "Learning Environment" -> redirecting to https://kubernetes.io/docs/tasks/tools/ ?

    * ~~kubectl~~
    * kind
    * **minikube**
    * kubeadm

The order of the tools here is a bit confusing, but anyway. Ignoring `kubectl`, they all need that.

* [Install kubectl on Linux](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux)
* [Install kubectl on macOS](https://kubernetes.io/docs/tasks/tools/install-kubectl-macos)
* [Install kubectl on Windows](https://kubernetes.io/docs/tasks/tools/install-kubectl-windows)

Since people always had problems with it, we integrated `minikube kubectl` for them. But anyway.

* https://github.com/kubernetes/minikube/issues/3645

> Minikube is a lightweight Kubernetes implementation that creates a VM on your local machine and deploys a simple cluster containing only one node.

Uh oh.

"lightweight Kubernetes implementation"

It was `localkube` that was the lightweight implementation, and it is now gone. There is now `k3s` for that, elsewhere.

"creates a VM on your local machine"

That is one option. You can also create a container, or you can just run everything on the current machine (localhost).

"deploys a simple cluster containing only one node"

Again, optional. The _recommendation_ is to only use one node and deploy on the control-plane. Just to get started.

The user is now faced with the overwhelming choice on _how_ to run their cluster, which they find a little confusing.

1. Minikube can still go the "VirtualBox" route, now using a bunch of different hypervisors, to create the VM (like before)
  This path is the best, if you don't have an already existing VM/Linux setup. It even comes with a customized OS image.

3. Minikube can use an existing Linux environment, and run the nodes as system containers (multi-node)
  This option is similar to using `kind`. `minikube start --driver=docker`

5. Minikube can use an existing Linux environment, and run the pods directly on the machine (single-node)
  This option is similar to using `kubeadm`. `minikube start --driver=none`

And that's only just the main three, then there are alternative setups like "podman" or "ssh" ("generic")

They will probably not be covered on any intro page, since they are advanced (and also somewhat buggy).

But all of them are still using minikube.

> Minikube is available for Linux, macOS, and Windows systems.

Still true.

> The Minikube CLI provides basic bootstrapping operations for working with your cluster, including start, stop, status, and delete. 

Also same.

> For this tutorial, however, you'll use a provided online terminal with Minikube pre-installed.

This will have to get revised to something like:

For this tutorial, however, you'll use a provided online terminal with **Kubernetes**  pre-installed.

At least with Killercoda, k8s is already running...

The alternative is to get an Ubuntu terminal, and install all of minikube / kind / kubeadm yourself.

**Comment by afbjorklund** [comment]
Related issues:

* #9803

* https://github.com/kubernetes/website/issues/31186

And also:

* https://github.com/kubernetes/website/pull/24533

* https://github.com/kubernetes/website/issues/36048

**Comment by afbjorklund** [comment]
So the new section is something like:

----

A Kubernetes cluster can be deployed on either physical or virtual machines.

**To get started with Kubernetes development, you can use Minikube or Kind or Kubeadm.**

1) yadda yadda yadda `minikube start`
2) yadda yadda yadda `kind create cluster`
3) yadda yadda yadda `kubeadm init`

For this tutorial, however, you'll use a provided online terminal with **Kubernetes** pre-installed.

Now that you know what Kubernetes is, let's go to the online tutorial and **use** our first cluster!

( [Start Interactive Tutorial](https://killercoda.com/examples/scenario/kubernetes-1node) )

```console
root@controlplane:~# kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:58:30Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"26", GitVersion:"v1.26.0", GitCommit:"b46a3f887ca979b1a5d14fd39cb1af43e7e5d12d", GitTreeState:"clean", BuildDate:"2022-12-08T19:51:45Z", GoVersion:"go1.19.4", Compiler:"gc", Platform:"linux/amd64"}
root@controlplane:~# kubectl cluster-info
Kubernetes control plane is running at https://172.30.1.2:6443
CoreDNS is running at https://172.30.1.2:6443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
root@controlplane:~# kubectl get nodes
NAME           STATUS   ROLES           AGE   VERSION
controlplane   Ready    control-plane   23d   v1.26.0
root@controlplane:~# 
```

Congratulations on completing the module

----

Without katacoda, without installation.

**Comment by afbjorklund** [comment]
The main problem with the kubeadm method (both minikube and kind uses kubeadm for the actual installation), is that there are a _lot_ of hidden requirements before the `kubeadm init` can run. And it can be a bit scary, for the first time user.

**Comment by medyagh** [comment]
I agree with @afbjorklund
