### ISSUE TITLE
 sudo crictl version: exit status 1

### ISSUE THREAD

**Issue by TzufBarOr** [kubernetes/minikube#15657]
### What Happened?

Hello everybody,
I have many times to start minikube on my Ubuntu VM. But always this error is shown:

❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

### Attach the log file

![Screenshot 2023-01-16 234952](https://user-images.githubusercontent.com/117042731/212770797-a392fbac-ff52-4bee-a3b0-22be71d33b33.png)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Did you install cri-tools ? What does `crictl version` say ?

**Comment by TzufBarOr** [comment]
commend crictl version is not foind.

![Screenshot 2023-01-17 225219](https://user-images.githubusercontent.com/117042731/213009842-9111693b-cb9f-48db-b114-363ae467b328.png)

**Comment by afbjorklund** [comment]
See https://github.com/kubernetes-sigs/cri-tools

**Comment by TzufBarOr** [comment]
Thank You, this issues solved!
