### ISSUE TITLE
Minikube

### ISSUE THREAD

**Issue by adletbcc** [kubernetes/minikube#15654]
### Что произошло?

minikube отказывается работать, после minikube start --driver=docker создается контейнер, но в дальнейшем отказывается работать. При попытке запустить сервис выйдает ошибку вы должны запустить minikube (minikube start). А он уже запущен, помогите решить проблему!

### Приложите логи

[logs.txt](https://github.com/kubernetes/minikube/files/10425139/logs.txt)

### Операционная система

macOS (Default)

### Драйвер

Docker

**Comment by medyagh** [comment]
@adletbcc have you tried 
minikube delete --all 
and then 
minikube start --force-systemd

**Comment by adletbcc** [comment]
Yeah, someone told me to just update docker, and it works! Thanks for your answer.
