### ISSUE TITLE
❌  Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for kubernetes.io/minikube-addons=registry pods: timed out waiting for the condition]

### ISSUE THREAD

**Issue by abdulfrfr** [kubernetes/minikube#15674]
### What Happened?

i tried running `minikube addons enable registery` and I got the error below...

### Attach the log file

[logs.txt`](https://github.com/kubernetes/minikube/files/10461458/logs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by niharika-kabra** [comment]
FACING SAME ISSUE
