### ISSUE TITLE
Minikube cannot start running Rootless Docker with CRI-O

### ISSUE THREAD

**Issue by q-seanworsley** [kubernetes/minikube#15676]
### What Happened?

minikube version: v1.28.0
Rootless Docker version: v20.10.22
Ubuntu 22.04.1 LTS

Run `minikube start --driver=docker --container-runtime=cri-o` with Rootless Docker. Cluster is started in NotReady Status. 
GetNodes:
```
NAME       STATUS     ROLES           AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME

minikube   NotReady   control-plane   110s   v1.25.3   192.168.49.2   <none>        Ubuntu 20.04.5 LTS   5.15.0-58-generic   cri-o://1.24.3
```
In the node description:
```
Ready            False   Fri, 20 Jan 2023 17:41:44 +0000   Fri, 20 Jan 2023 17:41:20 +0000   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/cni/net.d/. Has your network provider started?
```
[logs.txt](https://github.com/kubernetes/minikube/files/10468837/logs.txt)

Was under the impression that this is fully supported since this PR: https://github.com/kubernetes/minikube/pull/12900

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10468861/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by AkihiroSuda** [comment]
Does the master branch work for you? (works for me, on Ubuntu 22.10)

**Comment by q-seanworsley** [comment]
Hi @AkihiroSuda! Thanks for writing back.

Unfortunately running minikube built from master did not help. My full process:
1. Install Ubuntu 22.10 in VirtualBox
2. Install git, build-essential, go and other tools
3. clone minikube, and run `make` from repo.
4. Install `uidmap` package
5. Install Rootless Docker without packages, via curl: https://docs.docker.com/engine/security/rootless/#install
6. Enabled CPUSET etc: https://rootlesscontaine.rs/getting-started/common/cgroup2/#enabling-cpu-cpuset-and-io-delegation
7. Reboot
8. Run `~/minikube/out/minikube start --driver=docker --container-runtime=cri-o`
9. `kubectl get node -o wide`
```
NAME       STATUS     ROLES           AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME

minikube   NotReady   control-plane   36s   v1.26.1   192.168.49.2   <none>        Ubuntu 20.04.5 LTS   5.19.0-29-generic   cri-o://1.24.4
```

```
  Ready            False   Tue, 24 Jan 2023 12:36:43 +0000   Tue, 24 Jan 2023 12:36:16 +0000   KubeletNotReady              container runtime network not ready: NetworkReady=false reason:NetworkPluginNotReady message:Network plugin returns error: No CNI configuration file in /etc/cni/net.d/. Has your network provider started?
```

Installing `containernetworking-plugins` package and deleting/recreating the cluster did not fix the issue.

```
$ ./minikube version
minikube version: v1.28.0
commit: e7de6202d9d5a44a35b01d9104352d9f25bfa3ec
````
[logs1.txt](https://github.com/kubernetes/minikube/files/10489693/logs1.txt)
[log.txt](https://github.com/kubernetes/minikube/files/10489694/log.txt)
