### ISSUE TITLE
feature: minikube logs --last-start-only

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15700]
### What Happened?

minikube logs has a block that shows last start logs  and it is also availaable at ~/.minikube/logs/lastStart.logs

we should have a flag that shows the last start

```minikube logs --last-start-only```

### Attach the log file

n/a

### Operating System

None

### Driver

None

**Comment by nickmancari** [comment]
I could give this a shot.

**Comment by msagi** [comment]
I'm happy to help with this @nickmancari , @medyagh

**Comment by ibilalkayy** [comment]
What this issue is all about? I didn't understand it.
