### ISSUE TITLE
Abdulvoris

### ISSUE THREAD

**Issue by Abdulvorisjs** [kubernetes/minikube#15704]
### What Happened?

Abdulvoris

### Attach the log file

minikube logs --file=log.txt

### Operating System

Ubuntu

### Driver

Docker

**Comment by Abdulvorisjs** [comment]
first

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!
