### ISSUE TITLE
[macOS] Unable to install K8s v1.26.1

### ISSUE THREAD

**Issue by conradwt** [kubernetes/minikube#15727]
### What Happened?

I'm unable to install K8s v1.26.1 using the following command:

```zsh
minikube stop && minikube delete --all --purge && minikube start --kubernetes-version=v1.26.1
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10523406/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
@conradwt You have to update to minikube v1.29.0, your current version of minikube is not compatible with k8s v1.26.

**Comment by conradwt** [comment]
@spowelljr I guess I'll have to wait a little bit for MacPorts or gcloud to update their version of MiniKube to v1.29.0.  I'll close this issue for now and thanks for the feedback.

**Comment by spowelljr** [comment]
gcloud will come out with minikube v1.29.0 tomorrow
