### ISSUE TITLE
not able to set up ingress on minikube

### ISSUE THREAD

**Issue by Badawi02** [kubernetes/minikube#15737]
### What Happened?

![Screenshot from 2023-01-29 17-47-18](https://user-images.githubusercontent.com/96023421/215337996-b93c42ea-4624-43f8-919c-402d8b48ae38.png)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10530129/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by kundan2707** [comment]
@Badawi02 log you shared does not contain logs corresponding to this failure.

**Comment by kundan2707** [comment]
@Badawi02  you can refer to https://github.com/kubernetes/minikube/issues/13872#issuecomment-1081154915
similar issue might be present in your case too.

**Comment by ya-makariy** [comment]
Hello, I had the same problem in the morning, it was caused by the fact that the image of the ingress controller could not be pulled, now this problem is no longer reproduced

**Comment by spowelljr** [comment]
@ya-makariy The `controller:v1.2.1` image had a security vulnerability and the image seems to go in and out of availability at times. If you update minikube it will use the updated `controller:v1.5.1` image.

@Badawi02 if you run `kubectl get pods -A` you should see an ingress pod, then run `kubectl logs <ingress_pod_name>` and then upload the logs, thanks.

**Comment by kundan2707** [comment]
@Badawi02  do you have any update ? or we can close this issue

**Comment by Badawi02** [comment]
> @Badawi02  do you have any update ? or we can close this issue

u can close it
