### ISSUE TITLE
start fails when run from non-C:\ drive: open minikube.iso: The system cannot find the path specified.

### ISSUE THREAD

**Issue by mevam** [kubernetes/minikube#1574]
>>minikube start --vm-driver=virtualbox  
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
Downloading Minikube ISO
 89.51 MB / 89.51 MB  100.00% 0ss
E0611 12:27:47.593274    8356 start.go:127] **Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: open /Users/navy/.minikube/cache/iso/minikube-v0.18.0.iso: The system cannot find the path specified..**

 Retrying.
E0611 12:27:47.608522    8356 start.go:133] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: open /Users/navy/.minikube/cache/iso/minikube-v0.18.0.iso: The system cannot find the path specified.
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
>> go version   
go version go1.8.2 windows/amd64
>>
Run minikube failed on win 8.1. what should I do？Thanks.

**Comment by mevam** [comment]
>>minikube start --v=3                   /cygdrive/h/minikube 1
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
E0611 12:40:23.765630    4284 start.go:127] Error starting host: Error getting s                       tate for host: machine does not exist.

 Retrying.
E0611 12:40:23.765630    4284 start.go:133] Error starting host:  Error getting                        state for host: machine does not exist
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
>> minikube start --v=7                   /cygdrive/h/minikube 1
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
Found binary path at D:\Sware\minikube\minikube.exe
Launching plugin server for driver virtualbox
Plugin server listening at address 127.0.0.1:16672
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetState
(minikube) DBG | COMMAND: D:\Sware\VirtualBox\VBoxManage.exe showvminfo minikube                        --machinereadable
(minikube) DBG | STDOUT:
(minikube) DBG | {
(minikube) DBG | }
(minikube) DBG | STDERR:
(minikube) DBG | {
(minikube) DBG | VBoxManage.exe: error: Could not find a registered machine name                       d 'minikube'
(minikube) DBG | VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0                       x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
(minikube) DBG | VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid)                       .raw(), machine.asOutParam())" at line 2781 of file VBoxManageInfo.cpp
(minikube) DBG | }
E0611 12:40:36.420957    9060 start.go:127] Error starting host: Error getting s                       tate for host: machine does not exist.

 Retrying.
E0611 12:40:36.428003    9060 start.go:133] Error starting host:  Error getting                        state for host: machine does not exist
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
>>

**Comment by aaron-prindle** [comment]
I believe this issue is related to using a D: drive on windows as Minikube is by default stored on the C: drive.  Can you try running minikube with the MINIKUBE_HOME env var set to path on the D: drive?  For more information see #1310 as setting this should fix it: https://github.com/kubernetes/minikube/issues/1310#issuecomment-292229913

**Comment by r2d4** [comment]
ping @mevam 

We should add some documentation about this to our main windows docs

**Comment by cyluss** [comment]
@r2d4 I don't think it is documentation problem, it is bug. Please see 1310#issuecomment-303257241

**Comment by alastairs** [comment]
I ran into this same issue, with both minikube and my user profile on C:. I tried setting `MINIKUBE_HOME` as per @aaron-prindle's comment. I eventually pinned it down to the fact that my `pwd` was on D: - a simple `cd C:\` allowed `minikube start` to operate correctly.

![facepalm](https://media.giphy.com/media/yFQ0ywscgobJK/giphy.gif)

This has to be a bug @r2d4 - different behaviour depending on your `pwd`'s drive isn't solely a documentation issue.

**Comment by kylos101** [comment]
@alastairs this saved me from pulling out my remaining hair - thank you!

**Comment by kylos101** [comment]
@r2d4 Hi there, thank you so much for helping maintain Minikube! I am new to kubernetes, and Minikube is frickin' great. 

I wasn't able to run minikube until I CD'd to my C drive (kudos again to @alastairs) - chocolatey installed Minikube to my C drive. I work in F.

Can this issue be changed from a kind/documentation to some type of software change? Or should we create a new request? I am just looking to save future people the trouble, if possible.

**Comment by rmorrise** [comment]
This is a bug in how the ISO file path is generated. The drive letter needs to be included in the path.

**Comment by pxlphile** [comment]
Hi all, 
I can confirm this behavior (which almost drove me crazy until I found this issue). I run Minikube on a Windows 7 machine, and due to HDD space considerations I've set `MINIKUBE_HOME` to `D:\\minikube`.

Yes, double backslashes. The installation is a couple of months old and I don't remember why I had to put it this way. Anyhow, a change to D:\ (among a desperate iteration of `minikube delete` and minikube profile deletions) got it running for me.

**Comment by rmorrise** [comment]
This issue still trips me up every time I have to create a new minikube instance.

**Comment by manish1635** [comment]
If your environment is windows10 then Please set path as below.
set MINIKUBE_HOME=C:\Program Files\Kubernetes\Minikube

For more information, sharing steps which i did to run successfully:
C:\WINDOWS\system32>set MINIKUBE_HOME=C:\Program Files\Kubernetes\Minikube
C:\WINDOWS\system32>cd ..
C:\Windows>cd..
C:\>cd "Program Files"
C:\Program Files>cd Kubernetes
C:\Program Files\Kubernetes>cd Minikube
C:\Program Files\Kubernetes\Minikube>minikube start

**Comment by EmileTenhagen** [comment]
Minikube running on D:\
Set env. MINIKUBE_HOME=D:\Downloads

Problem when starting from command prompt in C:\
Change to D:\ en start minikube.

_C:\Windows\system32>minikube start
o   minikube v1.0.1 on windows (amd64)
@   Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: creating: open /Downloads/.minikube/cache/iso/minikube-v1.0.1.iso: Het systeem kan het opgegeven pad niet vinden.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

C:\Windows\system32>cd /D d:

D:\>minikube start
o   minikube v1.0.1 on windows (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.

!   Unable to start VM
X   Error:         [VM_DOES_NOT_EXIST] Error getting state for host: machine does not exist
i   Advice:        Your system no longer knows about the VM previously created by minikube. Run 'minikube delete' to reset your local state.
-   Related issues:
    - https://github.com/kubernetes/minikube/issues/3864

*   If the above advice does not help, please let us know:
-   https://github.com/kubernetes/minikube/issues/new

D:\>minikube delete
x   Deleting "minikube" from virtualbox ...
-   The "minikube" cluster has been deleted.

D:\>minikube start
o   minikube v1.0.1 on windows (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.99.101
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.06.3-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
@   Downloading kubeadm v1.14.1
@   Downloading kubelet v1.14.1
-   Pulling images required by Kubernetes v1.14.1 ...
-   Launching Kubernetes v1.14.1 using kubeadm ...
:   Waiting for pods: apiserver proxy etcd scheduler controller dns
-   Configuring cluster permissions ...
-   Verifying component health .....
+   kubectl is now configured to use "minikube"
=   Done! Thank you for using minikube!

D:\>_

**Comment by douglaswth** [comment]
I have a fix for this in docker/machine#4734 that at least works, but I am not quite sure if it is the best approach.

**Comment by douglaswth** [comment]
@tstromberg Oh! Haven't looked at this in a while, but another coworker was running into this issue so it's back on my radar. If you know of any way to poke the maintainers of docker/machine that might be helpful.

**Comment by tstromberg** [comment]
@douglaswth - Do you mind proposing the PR to https://github.com/machine-drivers/machine ? It's the fork of docker/machine that minikube uses, since docker/machine hasn't been seeing much activity.

@afbjorklund and @gbraad have approval rights there.

**Comment by douglaswth** [comment]
@tstromberg Okay, I've made machine-drivers/machine#22 for that.

**Comment by tstromberg** [comment]
I believe this was fixed in minikube v1.6: can someone please confirm on Windows?

**Comment by spdfnet** [comment]
I can confirm it working :)

**Comment by douglaswth** [comment]
@tstromberg Woohoo! It's working for me as well!
