### ISSUE TITLE
Wrong URL referenced for kubectl autocompletion

### ISSUE THREAD

**Issue by baptistepattyn** [kubernetes/minikube#15741]
On this page (https://minikube.sigs.k8s.io/docs/handbook/kubectl/) the following URI: https://kubernetes.io/docs/tasks/tools/included/optional-kubectl-configs-bash-linux/ is leading to nowhere. I looked around and I think this would be the correct URL https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#optional-kubectl-configurations-and-plugins

**Comment by afbjorklund** [comment]
It got deleted here:
* https://github.com/kubernetes/website/issues/38822

It is included from:
* https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/#enable-shell-autocompletion

```
### Enable shell autocompletion

kubectl provides autocompletion support for Bash, Zsh, Fish, and PowerShell, which can save you a lot of typing.

Below are the procedures to set up autocompletion for Bash, Fish, and Zsh.

{{< tabs name="kubectl_autocompletion" >}}
{{< tab name="Bash" include="included/optional-kubectl-configs-bash-linux.md" />}}
{{< tab name="Fish" include="included/optional-kubectl-configs-fish.md" />}}
{{< tab name="Zsh" include="included/optional-kubectl-configs-zsh.md" />}}
{{< /tabs >}}
```
