### ISSUE TITLE
error starting minikube

### ISSUE THREAD

**Issue by Assassin490** [kubernetes/minikube#15756]
Jan 31 01:02:08 minikube kubelet[2186]: E0131 01:02:08.345139    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"
Jan 31 01:02:08 minikube kubelet[2186]: E0131 01:02:08.565864    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"
Jan 31 01:02:08 minikube kubelet[2186]: E0131 01:02:08.667275    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"
Jan 31 01:02:08 minikube kubelet[2186]: E0131 01:02:08.787725    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"
Jan 31 01:02:08 minikube kubelet[2186]: E0131 01:02:08.848157    2186 eviction_manager.go:256] "Eviction manager: failed to get summary stats" err="failed to ge
t node info: node \"minikube\" not found"
Jan 31 01:02:08 minikube kubelet[2186]: E0131 01:02:08.907072    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"
Jan 31 01:02:09 minikube kubelet[2186]: E0131 01:02:09.182039    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"
Jan 31 01:02:09 minikube kubelet[2186]: E0131 01:02:09.845131    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"
Jan 31 01:02:10 minikube kubelet[2186]: E0131 01:02:10.005114    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"
Jan 31 01:02:10 minikube kubelet[2186]: E0131 01:02:10.148104    2186 kubelet.go:2448] "Error getting node" err="node \"minikube\" not found"

stderr:
W0131 00:43:55.584088    4239 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
        [WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by Assassin490** [comment]
[logs.txt](https://github.com/kubernetes/minikube/files/10562679/logs.txt)

**Comment by Assassin490** [comment]
thanks for the assistance, in fact I have tried to install from version 1.22 to 1.26 and in all of them it gives me the same error, regards

**Comment by Assassin490** [comment]
I even entered the container and I wanted to search for the file but it does not exist
root@minikube:/# ll /proc/sys/net/bridge/bridge-nf-call-iptables
ls: cannot access '/proc/sys/net/bridge/bridge-nf-call-iptables': No such file or directory
I have tried to create it, but I get the error that I do not have the permissions to create it

**Comment by medyagh** [comment]
hi @Assassin490 I noticed you are using a specific extra conifg 
"--extra-config=kubelet.cgroup-driver=systemd"

is there a reason for using that ? btw if so you might wanna try "minikube start --force-systemd" if your system has a not standard cgroup

**Comment by spowelljr** [comment]
Hi @Assassin490, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
