### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by devarsh10** [kubernetes/minikube#15757]
In minikube installation page:
![image](https://user-images.githubusercontent.com/83413047/215737233-08acdb77-a61c-4f71-be61-ac3802f3fc30.png)

This command line:
kubectl create deployment hello-minikube --image=kicbase/echo-server:1.0

is throwing this error:
error: failed to create deployment: Post "https://127.0.0.1:60400/apis/apps/v1/namespaces/default/deployments?fieldManager=kubectl-create&fieldValidation=Strict": EOF

If there's any mistake in this issue creation, it's mine.
Regards,
Devarsh.

**Comment by spowelljr** [comment]
Hi @devarsh10, that sounds like the context kubectl is pointing to is stale. Can you ensure minikube is still running? (`minikube profile list`). If it is try running `kubectl config use-context minikube` and that should reset your context to the minikube cluster.

**Comment by devarsh10** [comment]
Hey @spowelljr, minikube is running. And the deployment is created as well.
Thank you for replying.
So, should I close this issue now?

Regards.

**Comment by spowelljr** [comment]
Glad that solved your issue! I'll close the issue for you
