### ISSUE TITLE
minikube start 执行报错

### ISSUE THREAD

**Issue by Kizai** [kubernetes/minikube#15765]
**重现问题所需的命令**：
minikube start
**失败的命令的完整输出**：<details>
😄  minikube v1.29.0 on Ubuntu 20.04
❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
🐳  Preparing Kubernetes v1.26.1 on Docker 20.10.23 ...
❌  Unable to load cached images: loading cached images: stat /home/lemu-devops/.minikube/cache/images/amd64/gcr.io/k8s-minikube/storage-provisioner_v5: no such file or directory
    > kubectl.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubelet.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubectl:  16.27 MiB / 45.80 MiB [---->_________] 35.53% 2.83 MiB p/s 6.0s
    > kubelet:  14.16 MiB / 115.64 MiB [->___________] 12.25% 2.52 MiB p/s 5.8s
    > kubeadm:  28.60 MiB / 44.60 MiB [-------->_____] 64.12% 5.19 MiB p/s 5.7s

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl.sha256 Dst:/home/lemu-devops/.minikube/cache/linux/amd64/v1.26.1/kubectl.download Pwd: Mode:2 Umask:---------- Detectors:[0x3b856e8 0x3b856e8 0x3b856e8 0x3b856e8 0x3b856e8 0x3b856e8 0x3b856e8] Decompressors:map[bz2:0x3b856e8 gz:0x3b856e8 tar:0x3b856e8 tar.bz2:0x3b856e8 tar.gz:0x3b856e8 tar.xz:0x3b856e8 tar.zst:0x3b856e8 tbz2:0x3b856e8 tgz:0x3b856e8 txz:0x3b856e8 tzst:0x3b856e8 xz:0x3b856e8 zip:0x3b856e8 zst:0x3b856e8] Getters:map[file:0xc0005a2c00 http:0xc0006c32c0 https:0xc0006c3310] Dir:false ProgressListener:0x3b404d0 Insecure:false DisableSymlinks:false Options:[0x1baf460]}: unexpected EOF

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │

</details>

**`minikube logs`命令的输出**： <details>

    usages:
      - signing
      - authentication
nodeRegistration:
  criSocket: /var/run/cri-dockerd.sock
  name: "minikube"
  kubeletExtraArgs:
    node-ip: 192.168.49.2
  taints: []
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
apiServer:
  certSANs: ["127.0.0.1", "localhost", "192.168.49.2"]
  extraArgs:
    enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
controllerManager:
  extraArgs:
    allocate-node-cidrs: "true"
    leader-elect: "false"
scheduler:
  extraArgs:
    leader-elect: "false"
certificatesDir: /var/lib/minikube/certs
clusterName: mk
controlPlaneEndpoint: control-plane.minikube.internal:8443
etcd:
  local:
    dataDir: /var/lib/minikube/etcd
    extraArgs:
      proxy-refresh-interval: "70000"
kubernetesVersion: v1.26.1
networking:
  dnsDomain: cluster.local
  podSubnet: "10.244.0.0/16"
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  x509:
    clientCAFile: /var/lib/minikube/certs/ca.crt
cgroupDriver: cgroupfs
hairpinMode: hairpin-veth
runtimeRequestTimeout: 15m
clusterDomain: "cluster.local"
# disable disk resource management by default
imageGCHighThresholdPercent: 100
evictionHard:
  nodefs.available: "0%!"(MISSING)
  nodefs.inodesFree: "0%!"(MISSING)
  imagefs.available: "0%!"(MISSING)
failSwapOn: false
staticPodPath: /etc/kubernetes/manifests
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clusterCIDR: "10.244.0.0/16"
metricsBindAddress: 0.0.0.0:10249
conntrack:
  maxPerCore: 0
# Skip setting "net.netfilter.nf_conntrack_tcp_timeout_established"
  tcpEstablishedTimeout: 0s
# Skip setting "net.netfilter.nf_conntrack_tcp_timeout_close"
  tcpCloseWaitTimeout: 0s

I0201 16:14:58.833976 2337177 kubeadm.go:968] kubelet [Unit]
Wants=docker.socket

[Service]
ExecStart=
ExecStart=/var/lib/minikube/binaries/v1.26.1/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=remote --container-runtime-endpoint=/var/run/cri-dockerd.sock --hostname-override=minikube --image-service-endpoint=/var/run/cri-dockerd.sock --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=192.168.49.2

[Install]
 config:
{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:}
I0201 16:14:58.834009 2337177 ssh_runner.go:195] Run: sudo ls /var/lib/minikube/binaries/v1.26.1
I0201 16:14:58.839970 2337177 binaries.go:47] Didn't find k8s binaries: sudo ls /var/lib/minikube/binaries/v1.26.1: Process exited with status 2
stdout:

stderr:
ls: cannot access '/var/lib/minikube/binaries/v1.26.1': No such file or directory

Initiating transfer...
I0201 16:14:58.840014 2337177 ssh_runner.go:195] Run: sudo mkdir -p /var/lib/minikube/binaries/v1.26.1
I0201 16:14:58.845460 2337177 download.go:101] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubelet?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubelet.sha256 -> /home/lemu-devops/.minikube/cache/linux/amd64/v1.26.1/kubelet
I0201 16:14:58.845460 2337177 download.go:101] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubeadm.sha256 -> /home/lemu-devops/.minikube/cache/linux/amd64/v1.26.1/kubeadm
I0201 16:14:58.845460 2337177 download.go:101] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl.sha256 -> /home/lemu-devops/.minikube/cache/linux/amd64/v1.26.1/kubectl
I0201 16:15:07.767617 2337177 out.go:177] 
W0201 16:15:07.768851 2337177 out.go:239] ❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.26.1/bin/linux/amd64/kubectl.sha256 Dst:/home/lemu-devops/.minikube/cache/linux/amd64/v1.26.1/kubectl.download Pwd: Mode:2 Umask:---------- Detectors:[0x3b856e8 0x3b856e8 0x3b856e8 0x3b856e8 0x3b856e8 0x3b856e8 0x3b856e8] Decompressors:map[bz2:0x3b856e8 gz:0x3b856e8 tar:0x3b856e8 tar.bz2:0x3b856e8 tar.gz:0x3b856e8 tar.xz:0x3b856e8 tar.zst:0x3b856e8 tbz2:0x3b856e8 tgz:0x3b856e8 txz:0x3b856e8 tzst:0x3b856e8 xz:0x3b856e8 zip:0x3b856e8 zst:0x3b856e8] Getters:map[file:0xc0005a2c00 http:0xc0006c32c0 https:0xc0006c3310] Dir:false ProgressListener:0x3b404d0 Insecure:false DisableSymlinks:false Options:[0x1baf460]}: unexpected EOF
W0201 16:15:07.768878 2337177 out.go:239] 
W0201 16:15:07.769728 2337177 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0201 16:15:07.770657 2337177 out.go:177] 

==> Docker <==
-- Logs begin at Wed 2023-02-01 08:14:47 UTC, end at Wed 2023-02-01 08:16:36 UTC. --
Feb 01 08:14:49 minikube dockerd[532]: time="2023-02-01T08:14:49.329272208Z" level=info msg="Docker daemon" commit=6051f14 graphdriver(s)=overlay2 version=20.10.23
Feb 01 08:14:49 minikube dockerd[532]: time="2023-02-01T08:14:49.329323209Z" level=info msg="Daemon has completed initialization"
Feb 01 08:14:49 minikube systemd[1]: Started Docker Application Container Engine.
Feb 01 08:14:49 minikube dockerd[532]: time="2023-02-01T08:14:49.344031765Z" level=info msg="API listen on [::]:2376"
Feb 01 08:14:49 minikube dockerd[532]: time="2023-02-01T08:14:49.347757532Z" level=info msg="API listen on /var/run/docker.sock"
Feb 01 08:14:51 minikube systemd[1]: Stopping Docker Application Container Engine...
Feb 01 08:14:51 minikube dockerd[532]: time="2023-02-01T08:14:51.937181907Z" level=info msg="Processing signal 'terminated'"
Feb 01 08:14:51 minikube dockerd[532]: time="2023-02-01T08:14:51.938169176Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Feb 01 08:14:51 minikube dockerd[532]: time="2023-02-01T08:14:51.938758882Z" level=info msg="Daemon shutdown complete"
Feb 01 08:14:51 minikube systemd[1]: docker.service: Succeeded.
Feb 01 08:14:51 minikube systemd[1]: Stopped Docker Application Container Engine.
Feb 01 08:14:51 minikube systemd[1]: Starting Docker Application Container Engine...
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.027135175Z" level=info msg="Starting up"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.028704861Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.028730854Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.028765209Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.028775304Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.030331066Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.030344749Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.030355906Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.030362146Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.034082009Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.037236893Z" level=warning msg="Your kernel does not support CPU realtime scheduler"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.037259747Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.037267239Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.037426270Z" level=info msg="Loading containers: start."
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.092369707Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.121554010Z" level=info msg="Loading containers: done."
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.128849300Z" level=info msg="Docker daemon" commit=6051f14 graphdriver(s)=overlay2 version=20.10.23
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.128908571Z" level=info msg="Daemon has completed initialization"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.163959150Z" level=info msg="API listen on [::]:2376"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.169040234Z" level=info msg="API listen on /var/run/docker.sock"
Feb 01 08:14:52 minikube systemd[1]: Started Docker Application Container Engine.
Feb 01 08:14:52 minikube systemd[1]: Stopping Docker Application Container Engine...
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.261050800Z" level=info msg="Processing signal 'terminated'"
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.262051018Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Feb 01 08:14:52 minikube dockerd[844]: time="2023-02-01T08:14:52.262601603Z" level=info msg="Daemon shutdown complete"
Feb 01 08:14:52 minikube systemd[1]: docker.service: Succeeded.
Feb 01 08:14:52 minikube systemd[1]: Stopped Docker Application Container Engine.
Feb 01 08:14:52 minikube systemd[1]: Starting Docker Application Container Engine...
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.294618114Z" level=info msg="Starting up"
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.295834864Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.295851568Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.295869145Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.295876604Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.296570259Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.296582850Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.296595366Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock  <nil> 0 <nil>}] <nil> <nil>}" module=grpc
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.296603355Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.301519188Z" level=warning msg="Your kernel does not support CPU realtime scheduler"
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.301533893Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.301537564Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.301632676Z" level=info msg="Loading containers: start."
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.352410971Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.372432572Z" level=info msg="Loading containers: done."
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.380140694Z" level=info msg="Docker daemon" commit=6051f14 graphdriver(s)=overlay2 version=20.10.23
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.380176332Z" level=info msg="Daemon has completed initialization"
Feb 01 08:14:52 minikube systemd[1]: Started Docker Application Container Engine.
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.394450750Z" level=info msg="API listen on [::]:2376"
Feb 01 08:14:52 minikube dockerd[1032]: time="2023-02-01T08:14:52.397538930Z" level=info msg="API listen on /var/run/docker.sock"

==> container status <==
CONTAINER           IMAGE               CREATED             STATE               NAME                ATTEMPT             POD ID

==> describe nodes <==
E0201 16:16:36.686183 2346680 logs.go:193] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.26.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.26.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: /var/lib/minikube/binaries/v1.26.1/kubectl: command not found
 output: "\n** stderr ** \nsudo: /var/lib/minikube/binaries/v1.26.1/kubectl: command not found\n\n** /stderr **"

==> dmesg <==

==> kernel <==
 08:16:36 up 3 days, 23:46,  0 users,  load average: 2.29, 2.44, 2.02
Linux minikube 5.15.0-57-generic #63~20.04.1-Ubuntu SMP Wed Nov 30 13:40:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04.5 LTS"

==> kubelet <==
-- Logs begin at Wed 2023-02-01 08:14:47 UTC, end at Wed 2023-02-01 08:16:36 UTC. --
-- No entries --

❗  unable to fetch logs for: describe nodes

</details>

**使用的操作系统版本**：
ubuntu 20.04 LTS

**Comment by spowelljr** [comment]
Hi @Kizai, I'm assuming you're trying to run minikube from China, if that's correct run `minikube delete` and then run `minikube start --image-mirror-country='cn'`, that will download the artifacts from Chinese hosted servers that you can access.

-----

嗨@Kizai，我假设你正在尝试从中国运行 minikube，如果那是正确的运行 `minikube delete` 然后运行 ​​`minikube start --image-mirror-country='cn'`，这将下载工件来自您可以访问的中国托管服务器。
