### ISSUE TITLE
minikube addons enable ingress throws error

### ISSUE THREAD

**Issue by kavilakshmi** [kubernetes/minikube#15766]
### What Happened?

minikube addons enable ingress

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10556771/logs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @kavilakshmi, could you run `kubectl get pods -A` and you should see an ingress pod, then run `kubectl logs <ingress_pod_name>` and then upload the logs.

**Comment by kavilakshmi** [comment]
Installation of nginx was wrong on my side. I deleted all the services and restarted cluster, issue got resolved
