### ISSUE TITLE
Error on running `minikube start --vm-driver=none` as root

### ISSUE THREAD

**Issue by Qwestuha** [kubernetes/minikube#15779]
### Что произошло?

при запуске получаю ошибку sudo minikube start --vm-driver=none

### Приложите логи

root@evgeniy-VirtualBox:/home/evgeniy/cri-dockerd# cat logs.txt
*
* ==> Audit <==
* |---------|--------------------------------|----------|------|---------|---------------------|---------------------|
| Command |              Args              | Profile  | User | Version |     Start Time      |      End Time       |
|---------|--------------------------------|----------|------|---------|---------------------|---------------------|
| start   | --vm-driver=hyperkit           | minikube | root | v1.28.0 | 03 Feb 23 13:38 +08 |                     |
| delete  |                                | minikube | root | v1.28.0 | 03 Feb 23 13:39 +08 | 03 Feb 23 13:39 +08 |
| start   | --vm-driver=hyperkit           | minikube | root | v1.28.0 | 03 Feb 23 13:39 +08 |                     |
| delete  |                                | minikube | root | v1.28.0 | 03 Feb 23 13:39 +08 | 03 Feb 23 13:39 +08 |
| start   | --vm-driver=hyperkit           | minikube | root | v1.28.0 | 03 Feb 23 13:40 +08 |                     |
| start   |                                | minikube | root | v1.28.0 | 03 Feb 23 13:41 +08 |                     |
| start   |                                | minikube | root | v1.28.0 | 03 Feb 23 13:43 +08 |                     |
| start   |                                | minikube | root | v1.28.0 | 03 Feb 23 13:43 +08 |                     |
| start   | virtualbox                     | minikube | root | v1.28.0 | 03 Feb 23 13:43 +08 |                     |
| start   | --vm-driver=virtualbox         | minikube | root | v1.28.0 | 03 Feb 23 13:43 +08 |                     |
| start   | --cpus=1                       | minikube | root | v1.28.0 | 03 Feb 23 13:44 +08 |                     |
| start   | --cpus=2                       | minikube | root | v1.28.0 | 03 Feb 23 13:44 +08 |                     |
| start   | --driver=docker -n 4           | minikube | root | v1.28.0 | 03 Feb 23 13:46 +08 |                     |
| start   | --driver=docker -n 1           | minikube | root | v1.28.0 | 03 Feb 23 13:46 +08 |                     |
| start   | --driver=docker -n 2           | minikube | root | v1.28.0 | 03 Feb 23 13:46 +08 |                     |
| start   | --driver=docker -n 3           | minikube | root | v1.28.0 | 03 Feb 23 13:46 +08 |                     |
| start   | --driver=docker -n 4           | minikube | root | v1.28.0 | 03 Feb 23 13:46 +08 |                     |
| start   | --kubernetes-version v1.15.12  | minikube | root | v1.28.0 | 03 Feb 23 13:47 +08 |                     |
| start   | --kubernetes-version v1.16.0   | minikube | root | v1.28.0 | 03 Feb 23 13:47 +08 |                     |
| start   | --vm-driver=none               | minikube | root | v1.29.0 | 03 Feb 23 13:56 +08 |                     |
| start   | --vm-driver=none               | minikube | root | v1.29.0 | 03 Feb 23 13:56 +08 |                     |
| start   | --vm-driver=none               | minikube | root | v1.29.0 | 03 Feb 23 13:57 +08 |                     |
|         | --apiserver-ips 127.0.0.1      |          |      |         |                     |                     |
|         | --apiserver-name localhost     |          |      |         |                     |                     |
| start   | --vm-driver=hyperkit           | minikube | root | v1.29.0 | 03 Feb 23 14:19 +08 |                     |
| start   | --vm-driver=none               | minikube | root | v1.29.0 | 03 Feb 23 14:19 +08 |                     |
| start   | --vm-driver=hyperkit           | minikube | root | v1.29.0 | 03 Feb 23 14:26 +08 |                     |
| start   | --vm-driver=none               | minikube | root | v1.29.0 | 03 Feb 23 14:26 +08 |                     |
|---------|--------------------------------|----------|------|---------|---------------------|---------------------|

*
* ==> Last Start <==
* Log file created at: 2023/02/03 14:26:57
Running on machine: evgeniy-VirtualBox
Binary: Built with gc go1.19.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0203 14:26:57.402642    7841 out.go:296] Setting OutFile to fd 1 ...
I0203 14:26:57.402858    7841 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0203 14:26:57.402866    7841 out.go:309] Setting ErrFile to fd 2...
I0203 14:26:57.402885    7841 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0203 14:26:57.403428    7841 root.go:334] Updating PATH: /root/.minikube/bin
I0203 14:26:57.404189    7841 out.go:303] Setting JSON to false
I0203 14:26:57.406311    7841 start.go:125] hostinfo: {"hostname":"evgeniy-VirtualBox","uptime":1253,"bootTime":1675404364,"procs":147,"os":"linux","platform":"linuxmint","platformFamily":"debian","platformVersion":"20.3","kernelVersion":"5.4.0-135-generic","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"9dcb0fd1-95a1-424e-9b94-713aee2e9986"}
I0203 14:26:57.406525    7841 start.go:135] virtualization: kvm host
I0203 14:26:57.409953    7841 out.go:177] * minikube v1.29.0 on Linuxmint 20.3
W0203 14:26:57.411937    7841 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0203 14:26:57.412047    7841 notify.go:220] Checking for updates...
I0203 14:26:57.413821    7841 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.26.1
I0203 14:26:57.414800    7841 exec_runner.go:51] Run: systemctl --version
I0203 14:26:57.418337    7841 driver.go:365] Setting default libvirt URI to qemu:///system
I0203 14:26:57.420981    7841 out.go:177] * Using the none driver based on existing profile
I0203 14:26:57.423012    7841 start.go:296] selected driver: none
I0203 14:26:57.423023    7841 start.go:857] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:4200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0203 14:26:57.423122    7841 start.go:868] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0203 14:26:57.423141    7841 start.go:1617] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0203 14:26:57.424198    7841 cni.go:84] Creating CNI manager for ""
I0203 14:26:57.424222    7841 cni.go:157] "none" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
I0203 14:26:57.424241    7841 start_flags.go:319] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:4200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0203 14:26:57.426759    7841 out.go:177] * Starting control plane node minikube in cluster minikube
I0203 14:26:57.428528    7841 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0203 14:26:57.428781    7841 cache.go:193] Successfully downloaded all kic artifacts
I0203 14:26:57.428815    7841 start.go:364] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0203 14:26:57.428914    7841 start.go:368] acquired machines lock for "minikube" in 66.659µs
I0203 14:26:57.428937    7841 start.go:96] Skipping create...Using existing machine configuration
I0203 14:26:57.428944    7841 fix.go:55] fixHost starting: m01
W0203 14:26:57.429473    7841 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0203 14:26:57.429495    7841 api_server.go:165] Checking apiserver status ...
I0203 14:26:57.429570    7841 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0203 14:26:57.481679    7841 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0203 14:26:57.481742    7841 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0203 14:26:57.507702    7841 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0203 14:26:57.507714    7841 fix.go:129] unexpected machine state, will restart: <nil>
I0203 14:26:57.510860    7841 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I0203 14:26:57.516711    7841 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0203 14:26:57.516929    7841 start.go:300] post-start starting for "minikube" (driver="none")
I0203 14:26:57.517032    7841 start.go:328] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0203 14:26:57.517141    7841 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0203 14:26:57.535546    7841 main.go:141] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0203 14:26:57.535579    7841 main.go:141] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0203 14:26:57.535600    7841 main.go:141] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0203 14:26:57.561162    7841 out.go:177] * OS release is Linux Mint 20.3
I0203 14:26:57.563681    7841 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0203 14:26:57.587869    7841 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0203 14:26:57.588401    7841 start.go:303] post-start completed in 71.460291ms
I0203 14:26:57.588413    7841 fix.go:57] fixHost completed within 159.469904ms
I0203 14:26:57.588420    7841 start.go:83] releasing machines lock for "minikube", held for 159.497488ms
I0203 14:26:57.589142    7841 exec_runner.go:51] Run: cat /version.json
W0203 14:26:57.620761    7841 start.go:396] Unable to open version.json: cat /version.json: exit status 1
stdout:

stderr:
cat: /version.json: No such file or directory
I0203 14:26:57.620841    7841 exec_runner.go:51] Run: sh -c "stat /etc/cni/net.d/*loopback.conf*"
I0203 14:26:57.620845    7841 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
W0203 14:26:57.654344    7841 cni.go:208] loopback cni configuration skipped: "/etc/cni/net.d/*loopback.conf*" not found
I0203 14:26:57.654456    7841 exec_runner.go:51] Run: sudo mkdir -p /etc/systemd/system/cri-docker.service.d
I0203 14:26:57.683043    7841 exec_runner.go:151] cp: memory --> /etc/systemd/system/cri-docker.service.d/10-cni.conf (135 bytes)
I0203 14:26:57.683637    7841 exec_runner.go:51] Run: sudo cp -a /tmp/minikube2327445496 /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0203 14:26:57.709876    7841 exec_runner.go:51] Run: sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%!p(MISSING), " -exec sh -c "sudo mv {} {}.mk_disabled" ;
I0203 14:26:57.803721    7841 cni.go:258] no active bridge cni configs found in "/etc/cni/net.d" - nothing to disable
I0203 14:26:57.803742    7841 start.go:483] detecting cgroup driver to use...
I0203 14:26:57.803778    7841 detect.go:196] detected "cgroupfs" cgroup driver on host os
I0203 14:26:57.804078    7841 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0203 14:26:57.870027    7841 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml"
W0203 14:26:57.893978    7841 start.go:450] cannot ensure containerd is configured properly and reloaded for docker - cluster might be unstable: update sandbox_image: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml": exit status 2
stdout:

stderr:
sed: can't read /etc/containerd/config.toml: No such file or directory
I0203 14:26:57.893998    7841 start.go:483] detecting cgroup driver to use...
I0203 14:26:57.894076    7841 detect.go:196] detected "cgroupfs" cgroup driver on host os
I0203 14:26:57.894300    7841 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0203 14:26:57.944544    7841 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0203 14:26:58.610212    7841 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0203 14:26:59.255046    7841 docker.go:529] configuring docker to use "cgroupfs" as cgroup driver...
I0203 14:26:59.255108    7841 exec_runner.go:151] cp: memory --> /etc/docker/daemon.json (144 bytes)
I0203 14:26:59.255533    7841 exec_runner.go:51] Run: sudo cp -a /tmp/minikube1589769627 /etc/docker/daemon.json
I0203 14:26:59.291749    7841 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0203 14:26:59.893671    7841 exec_runner.go:51] Run: sudo systemctl restart docker
I0203 14:27:02.152421    7841 exec_runner.go:84] Completed: sudo systemctl restart docker: (2.2586726s)
I0203 14:27:02.152537    7841 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0203 14:27:02.781449    7841 exec_runner.go:51] Run: sudo systemctl unmask cri-docker.socket
I0203 14:27:03.422035    7841 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0203 14:27:04.027125    7841 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0203 14:27:04.647698    7841 exec_runner.go:51] Run: sudo systemctl restart cri-docker.socket
I0203 14:27:04.686964    7841 start.go:530] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0203 14:27:04.687116    7841 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0203 14:27:04.694657    7841 start.go:551] Will wait 60s for crictl version
I0203 14:27:04.694753    7841 exec_runner.go:51] Run: which crictl
I0203 14:27:04.701044    7841 out.go:177]
W0203 14:27:04.703457    7841 out.go:239] X Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

W0203 14:27:04.703507    7841 out.go:239] *
W0203 14:27:04.710279    7841 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0203 14:27:04.712927    7841 out.go:177]

### Операционная система

Ubuntu

### Драйвер

Docker

**Comment by IlyshaNil** [comment]
Do you install `crictl`?

**Comment by sftim** [comment]
/retitle Error on running `minikube start --vm-driver=none` as root
