### ISSUE TITLE
fix minikube mount --kill

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15778]
### What Happened?

minikube mount --kill should kill all already mount processes spwan by minikube

to reproduce
try to mount 3 different folders
minikube mount -p minikube /tmp:/a1 
minikube mount -p minikube /tmp:/a2
minikube mount -p minikube /tmp:/a3

and then 
minikube mount --kill=true

and expect there be no process

ps aux | grep "minikube mount"

### Attach the log file

n/a

### Operating System

None

### Driver

None

**Comment by x7upLime** [comment]
The issue comes from the fact that the kill flag relies on a mechanism(k8s.io/minikube/cmd/minikube/cmd.killMountProcess)
that expects the mounts to be mounted by k8s.io/minikube/pkg/minikube/node.configureMounts(),
which places a file containing the pid of a process in the localpath.Profile(profile).

Instead, `$ minikube mount` doesn't place anything,
and the code for the kill flag returns err==nil if the file is not present.

---

The code for `$minikube mount` just places a listening server and blocks until a ^C is issued,
or until kill request is received.. but there is currently no mechanism provided for the actual kill:  
If one calls a mount multiple times putting the process in background:
```
$ ps -ef | grep "minikube mount"
andrew   1215678 1210216  0 16:31 pts/2    00:00:00 minikube mount -p minikube /tmp:/a1
andrew   1215771 1210216  0 16:31 pts/2    00:00:00 minikube mount -p minikube /tmp:/a2
andrew   1215865 1210216  0 16:31 pts/2    00:00:00 minikube mount -p minikube /tmp:/a3
andrew   1232237 1228957  0 17:18 pts/6    00:00:00 minikube mount -p minikube /tmp:/a3
andrew   1232329 1228957  0 17:18 pts/6    00:00:00 minikube mount -p minikube /tmp:/a3
andrew   1232425 1228957  0 17:18 pts/6    00:00:00 minikube mount -p minikube /tmp:/a3
andrew   1232518 1228957  0 17:18 pts/6    00:00:00 minikube mount -p minikube /tmp:/a3
andrew   1232611 1228957  0 17:18 pts/6    00:00:00 minikube mount -p minikube /tmp:/a3
andrew   1232703 1228957  0 17:18 pts/6    00:00:00 minikube mount -p minikube /tmp:/a3
```

**Comment by x7upLime** [comment]
```
// cmd/minikube/cmd/mount.go -- 	Run: func(cmd *cobra.Command, args []string)
 		var wg sync.WaitGroup
+		pid := make(chan int)
 		if cfg.Type == nineP {
 			wg.Add(1)
-			go func() {
+			go func(pid chan int) {
+				pid <- os.Getpid()
 				out.Styled(style.Fileserver, "Userspace file server: ")
 				ufs.StartServer(net.JoinHostPort(bindIP, strconv.Itoa(port)), debugVal, hostPath)
 				out.Step(style.Stopped, "Userspace file server is shutdown")
 				wg.Done()
-			}()
+			}(pid)
 		}

// pkg/minikube/cluster/mount.go -- func Mount()
 		return &MountError{ErrorType: MountErrorUnknown, UnderlyingError: errors.Wrapf(err, "mount with cmd %s ", rr.Command())}
 	}
 
+	profile := viper.GetString("profile")
+	if err := lock.WriteFile(filepath.Join(localpath.Profile(profile), constants.MountProcessFileName), []byte(strconv.Itoa(pid)), 0o644); err != nil {
+		exit.Error(reason.HostMountPid, "Error writing mount pid", err)
+	}
+
 	klog.Infof("mount successful: %q", rr.Output())
 	return nil
 }

```

also relying on lock.Writefile as the configureMounts() implementation would not be enough:
we would overwrite the file each time,
so multiple calls to `$minikube mount` would makes us lose track of the previous active processes...
and `$ minikube mount --kill=true` would result in killing only the last one.
```
$ minikube mount -p minikube /tmp:/a1 &
$ minikube mount -p minikube /tmp:/a2 &
$ ps -ef | grep "minikube mount"
andrew   1268190 1268040  1 19:01 pts/6    00:00:00 minikube mount -p minikube /tmp:/a1
andrew   1268288 1268040  5 19:01 pts/6    00:00:00 minikube mount -p minikube /tmp:/a2

$ minikube mount --kill=true
$ ps -ef | grep "minikube mount"
andrew   1268190 1268040  0 19:01 pts/6    00:00:00 minikube mount -p minikube /tmp:/a1
```

Perhaps we could use a lock.AppendToFile()?
