### ISSUE TITLE
Minikube not starting

### ISSUE THREAD

**Issue by Mdrehanalam2020** [kubernetes/minikube#15773]
### What Happened?

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
time="2023-02-02T08:59:25Z" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰──────────────────────────────────────────────────────────────────────────────

### Attach the log file

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
time="2023-02-02T08:59:25Z" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

root@ip-172-31-46-10:~/cri-dockerd#

### Operating System

None

### Driver

None

**Comment by Mdrehanalam2020** [comment]
@Team anyone help here two day back it was working fine but from last 2 days i am getting above issue. please guide me the step, i tried so many time but getting same error, or let me know recent any changes happen in minikube??

**Comment by kundan2707** [comment]
/kind support
@Mdrehanalam2020  you can check similar raised issue in repo first . you might find some solution
