### ISSUE TITLE
minikube not starting as expected.

### ISSUE THREAD

**Issue by rohcha** [kubernetes/minikube#15796]
### What Happened?

Getting below error while i use minikube start

! StartHost failed, but will try again: provision: Temporary Error: NewSession: new client: new client: ssh: handshake failed: read tcp 127.0.0.1:57802->127.0.0.1:32787: read: connection reset by peer

X Exiting due to DRV_CP_ENDPOINT: failed to lookup ip for ""

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10675116/logs.txt)
[minikube_docker-env_d9ed1e7c3c20c7654323bd59db69953bc05a5299_0.log](https://github.com/kubernetes/minikube/files/10675118/minikube_docker-env_d9ed1e7c3c20c7654323bd59db69953bc05a5299_0.log)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by arnavdeshpande1** [comment]
This can be related to minikube files.
`rm -rf ~/.minikube & minikube start` 
try this command it should resolve the issue.
