### ISSUE TITLE
add ability to get json for "minikube sevice list"

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15827]
we already have json output for many of minikube commands, for example 
"minikube profile list -o=json" 

we have forgotten to implement it for "service list"

"minikube service list -o=json"

should be easy to follow other examples of doing it

**Comment by OmSaran** [comment]
Can I take a stab at this please?

**Comment by Sajiyah-Salat** [comment]
Hello @medyagh I have worked on minikube many times. It would be easy for me to make changes, however the repo is large enough can you please guide me to exact file location. Thank you.

**Comment by medyagh** [comment]
Hi both @OmSaran and @Sajiyah-Salat 
first PR come first review ! :) or if you like to cooperate that's fine too

here is the file to look at.
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/service_list.go

and if you want example of list json you can look at profile list -o=json
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/config/profile_list.go#L59

**Comment by OmSaran** [comment]
Thanks @medyagh, I've added a PR, would be great if you could review it! I also tested it locally and attached the before/after results in the PR
