### ISSUE TITLE
minikube tunnel should not be allowed to run twice

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15825]
### What Happened?

right now we can run minikube tunnel in two different terminals two times ! which makes no sense

(follow example of Loadbalancer in site)
https://minikube.sigs.k8s.io/docs/start/

we should tell user another instance of minikube tunnel is running and exit safely

### Attach the log file

na

### Operating System

None

### Driver

None

**Comment by OmSaran** [comment]
I'm a student at UT Austin taking the virtualization course and as part of it, can I take a stab at this?

**Comment by swastik959** [comment]
hi I want to contribute to this issue van you please explain it to me

**Comment by Sajiyah-Salat** [comment]
Hello @medyagh  we need to add a warning line saying " Two tunnels are running". Can you please guide me to exact file?

**Comment by OmSaran** [comment]
Hi @medyagh , what if a user wants to run a new tunnel on a new interface that was not tunneled by the older tunnel process? Would it make sense to have multiple tunnel processes running simultaneously in this case?

**Comment by OmSaran** [comment]
@medyagh I have created a PR (#15834) with the above mentioned approach, please review it.

**Comment by ashutosh887** [comment]
@medyagh Please check @here and let me know if I can help
