### ISSUE TITLE
Getting error on running “minikube start - vm-driver kvm2”

### ISSUE THREAD

**Issue by akhileshsooji028** [kubernetes/minikube#15838]
Facing this following error after running the "minikube start - vm-driver kvm2"
```
minikube v0.34.1 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

```

minikube installation reference linkL:- 
1. https://medium.com/@morgan_42683/kubernetes-on-your-local-manjaro-arch-7890904c8984
2. https://setevoy.medium.com/kubernetes-running-minikube-on-arch-linux-58a7d3b84887
3. https://www.howtoforge.com/learning-kubernetes-locally-via-minikube-on-linux-manjaro-archlinux/

Need little assistance to fill out the missing gap.

**Comment by p2c2e** [comment]
`This computer doesn't have VT-X/AMD-v enabled` - which indicates your system does not have Virtualization capabilities or is not enabled. Most recent systems have this - so, Taking a wild guess here ... 

Are you trying to play with minikube within a VM - say (for e.g) you are on Windows and using a Virtualbox setup within which you are trying minikube? ( See : https://docs.oracle.com/en/virtualization/virtualbox/7.0/user/BasicConcepts.html#settings-processor )
If above is true - you can try enable virtualization within the VM settings. This is not ideal (running a machine within a machine within ... )
