### ISSUE TITLE
unable to start minikube

### ISSUE THREAD

**Issue by mohittandon** [kubernetes/minikube#15832]
### What Happened?

[logs.txt](https://github.com/kubernetes/minikube/files/10714853/logs.txt)

### Attach the log file

i installed minikube using the following commnds in ubuntu 18.04 using aws ec2:-

sudo su

#Now install docker

sudo apt update && apt -y install docker.io

#install Kubectl

curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x ./kubectl && sudo mv ./kubectl /usr/local/bin/kubectl

#install Minikube

curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

minikube start --vm-driver=none
apt install conntrack
minikube start --vm-driver=none
minikube status

the last 3rd & 4th command i tried by changing the sequence , but very time getting the sam eerror as attached in logs file

root@ip-172-31-37-4:/home/ubuntu# minikube start --vm-driver=none
😄  minikube v1.29.0 on Ubuntu 18.04 (xen/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 18.04.6 LTS

❌  Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Ubuntu

### Driver

None

**Comment by scaleoutsean** [comment]
Work by the [docs](https://minikube.sigs.k8s.io/docs/start/) and it will work.

**Comment by mohittandon** [comment]
> Work by the [docs](https://minikube.sigs.k8s.io/docs/start/) and it will work.

is there anything else in my document missing, which is failing to make you understand the issue that is happening on my instance.......? I followed the instructions as per the documents, kindly let me know if we can connect to fix this.

**Comment by spowelljr** [comment]
It looks like crictl is missing from your system, if you run `which crictl` yourself what do you get? If it's not installed try installing it and then try again.

**Comment by scaleoutsean** [comment]
The requirement is documented in driver section for `none`:
https://minikube.sigs.k8s.io/docs/drivers/none/
