### ISSUE TITLE
Bump ISO Go version back up to 1.20 after buildroot fix

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#15841]
Bumped Go version back down to 1.19.5 from 1.20 due in https://github.com/kubernetes/minikube/pull/15752/commits/3006b3ea0aa9bf5e40414417b40cb7062a4a4ffd due to https://lore.kernel.org/buildroot/CA+h8R2rtcynkCBsz=_9yANOEguyPCOcQDj8_ns+cv8RS8+8t9A@mail.gmail.com/T/

**Comment by spowelljr** [comment]
I don't believe that buildroot has released a new version yet so I don't think any action is able to be taken yet.

https://buildroot.org/news.html

**Comment by XDRAGON2002** [comment]
Sure, I'll keep this issue on a tracking thread then.
