### ISSUE TITLE
`unknown flag: --apiserver-name` with `--kubernetes-version v1.5.1` even though it's documented in `minikube start --help`

### ISSUE THREAD

**Issue by nieldw** [kubernetes/minikube#1585]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Minikube version** (use `minikube version`): v0.19.1

**Environment**:
- **OS** (e.g. from /etc/os-release):
```
cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
PRETTY_NAME="Ubuntu 16.04.2 LTS"
```
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.18.0.iso
- **Install tools**:
- **Others**:

**What happened**:
`minikube start --help` documents the flag, `--apiserver-name`, but running something like `minikube start --apiserver-name test --kubernetes-version v1.5.1 --profile test` apparently completes successfully, but then `kubectl cluster-info` returns `The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?`

Looking at `minikube logs --profile test`
includes a line with `localkube[10462]: unknown flag: --apiserver-name`
and `systemd[1]: localkube.service: Main process exited, code=exited, status=2/INVALIDARGUMENT`

**What you expected to happen**:
Minikube to successfully start a cluster with name `test` and k8s version v1.5.1

**How to reproduce it** (as minimally and precisely as possible):
```
$ minikube start --apiserver-name test --kubernetes-version v1.5.1 --profile test
$ kubectl cluster-info
```

**Anything else do we need to know**:
Omitting `--apiserver-name` works as expected:
```
$ minikube start --kubernetes-version v1.5.1 --profile test
$ kubectl cluster-info
```

**Comment by r2d4** [comment]
Unfortunately, we added this feature recently, and it will only work in our published kubernetes versions >=1.5.3

We should document this much better, but here is the PR
https://github.com/kubernetes/minikube/pull/1245
