### ISSUE TITLE
Flake Bot PR commenter should Update the comment instead of making a new comment

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#15853]
minikube has a bot that comments how flaky a test failure on the PR is, but each different test run generates a new comment,
but it should Update the existing comment.
Example:
https://github.com/kubernetes/minikube/pull/15840#issuecomment-1429033912

this is the line that comments on the PRs 

https://github.com/medyagh/minikube/blob/99756bef0b9a90b9097668cb4e9c255f387cbadd/hack/jenkins/test-flake-chart/report_flakes.sh#L130

one way of doing it might be changing this
line 
```gh pr comment "https://github.com/kubernetes/minikube/pull/$PR_NUMBER" --body "$(cat $TMP_COMMENT)"```
to (add --edit-last)
```gh pr comment "https://github.com/kubernetes/minikube/pull/$PR_NUMBER" --edit-last --body "$(cat $TMP_COMMENT)"```

the only problem is the minikube-pr-bot also updates the Performance data too which means if the last data was Performance data, it will over-write it.... (example of the [performance PR comment](https://github.com/kubernetes/minikube/pull/15840#issuecomment-1428921908))

**Comment by spowelljr** [comment]
Instead we hide the previous comments now
