### ISSUE TITLE
Prevent users from modifying addons while cluster is paused

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#15857]
Currently you can try enabling/disabling an addon while the cluster is paused, but it will hang. We should prevent users from doing this and notify them that they can't perform this action while the cluster is paused and they should unpause the cluster if they wish to modify the addons.

Example:
```
$ minikube start
$ minikube pause
$ minikube addons enable gcp-auth
# hangs
```

**Comment by norshtein** [comment]
Hey @spowelljr , may I take this work item? 

I plan to add a check whether `kube-system` namespace is paused in `EnableOrDisableAddon`, that is adding `runtimePaused, err = cluster.CheckIfPaused(runner, []string{"kube-system"})` [here](https://github.com/kubernetes/minikube/blob/master/pkg/addons/addons.go#L281). If paused, then raise an error. Is this correct way to fix the issue?

**Comment by spowelljr** [comment]
@norshtein I believe that should work, that seems fine to me.

**Comment by ashutosh887** [comment]
I would like to work on this @spowelljr

**Comment by spowelljr** [comment]
@ashutosh887 There is already a Pr create for this issue by @norshtein https://github.com/kubernetes/minikube/pull/15868

**Comment by akstron** [comment]
Seems like no one is working on #15868 for a long time. I would like to work on this issue, if possible.
