### ISSUE TITLE
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.7:3128: connect: connection refused

### ISSUE THREAD

**Issue by radrad** [kubernetes/minikube#15858]
### What Happened?

I am trying to follow this tutorial: https://minikube.sigs.k8s.io/docs/handbook/registry/
to add docker registry on minikube on Windows 10. I have wsl enabled on my Windows Docker application and also enabled Kubernetes in that app. However I intend to use minikube.

I am running all of these commands from windows cmd prompt.

C:\WINDOWS\system32>minikube addons enable registry
* registry is an addon maintained by Google. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
 Registry addon with docker driver uses port 6672 please use that instead of default port 5000

E:\Terraform\Minikube>minikube profile list
|----------|-----------|---------|--------------     |------|---------|--------  -|-------|--------|
| Profile  | VM Driver | Runtime |      IP             | Port | Version | Status    | Nodes | Active |
|----------|-----------|---------|--------------     |------|---------|--------   -|-------|--------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.26.1 | Running |     1 | *      |
|----------|-----------|---------|--------------     |----- -|---------|--------   -|-------|--------|

I was trying to follow the last step and I ran this command (replacing port 5000 with 62214 as node in the message above)
_**docker run --rm -it --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:62214,reuseaddr,fork TCP:$(minikube ip):62214"**_

**I am getting this error on windows cmd prompt scree:
Unable to find image 'alpine:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.7:3128: connect: connection refused.**

I was also trying to do some other docker run comands with the same error.
C:\WINDOWS\system32>docker run -d -p 80:80 docker/getting-started
Unable to find image 'docker/getting-started:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": proxyconnect tcp: dial tcp 192.168.65.7:3128: connect: connection refused.
See 'docker run --help'.

What is going on? I uninstalled docker for windows and install it from clean state.
I noticed that kubernates failed to start in Docker desktop since it is enabled.
I am not sure itf this is related to the above problem

C:\WINDOWS\system32>docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc., v0.10.0)
  compose: Docker Compose (Docker Inc., v2.15.1)
  dev: Docker Dev Environments (Docker Inc., v0.0.5)
  extension: Manages Docker extensions (Docker Inc., v0.2.17)
  sbom: View the packaged-based Software Bill Of Materials (SBOM) for an image (Anchore Inc., 0.6.0)
  scan: Docker Scan (Docker Inc., v0.23.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 20.10.22
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 9ba4b250366a5ddde94bb7c9d1def331423aa323
 runc version: v1.1.4-0-g5fd4c4d
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.15.83.1-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.3GiB
 Name: docker-desktop
 ID: MJ6D:VU5Y:3MY93:SABA:LGPOE:3IIB:HJNG:OQZM:2DV4:BV5R:MPMW:Q4M1
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 No Proxy: hubproxy.docker.internal
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  hubproxy.docker.internal:5000
  127.0.0.0/8
 Live Restore Enabled: false

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10738541/logs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by zxzhang-cn** [comment]
I have encountered the same problem

**Comment by stalsbyt** [comment]
![image](https://user-images.githubusercontent.com/11820845/231796959-67e3c153-0f02-4647-b69d-23c55baa0d46.png)
Update to new version of Docker Desktop solve my same problem
