### ISSUE TITLE
Unable to install minikube with no access to docker hub

### ISSUE THREAD

**Issue by zadigus** [kubernetes/minikube#15860]
### What Happened?

I am working on a machine where access to index.docker.io (and all other official docker hub addresses) are blocked. The only way I am allowed to grab docker images is through our central artifactory server, which proxies gcr.io, docker hub, and many other docker registries. 

I am trying to run this:
```bash
minikube start --cpus=2 --image-repository=${DOCKER_REGISTRY} --registry-mirror=https://${DOCKER_REGISTRY}
```
However, that command seems to still connect to index.docker.io:
```
* minikube v1.25.2 on Ubuntu 20.04
* Using the docker driver based on existing profile
! You cannot change the CPUs for an existing minikube cluster. Please first delete the cluster.
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
    > index.docker.io/kicbase/sta...: 0 B [________________________] ?% ? p/s 
```
I tried many things but I have had no success so far. How should I proceed to install my minikube cluster when I have no access to docker hub and how should I pass my registry credentials to minikube so that it works?

### Attach the log file

* minikube v1.25.2 on Ubuntu 20.04
* Using the docker driver based on existing profile
! You cannot change the CPUs for an existing minikube cluster. Please first delete the cluster.
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
    > index.docker.io/kicbase/sta...: 0 B [________________________] ?% ? p/s 

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
You need to set the registry mirror also for the kicbase image, as used by the Docker driver.

The other settings are for the container runtime (Docker), running inside the cluster

**Comment by afbjorklund** [comment]
Probably that should also expect a mirror ?

Instead of having to set the `--base-image`

**Comment by zadigus** [comment]
The option you are talking about doesn't seem to work:
```bash
$ minikube start --cpus=2 --image-repository=${DOCKER_REGISTRY} --base-image=${DOCKER_REGISTRY}/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2                       * minikube v1.25.2 on Ubuntu 20.04
* Using the docker driver based on existing profile
! You cannot change the CPUs for an existing minikube cluster. Please first delete the cluster.
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
    > index.docker.io/kicbase/sta...: 0 B [________________________] ?% ? p/s ?^C
```
where ${DOCKER_REGISTRY} is a variable containing the hostname of my internal artifactory server, with port.

**Comment by afbjorklund** [comment]
Hmm, it might be trying `docker.io` as a fallback - the real error should be in the log

**Comment by zadigus** [comment]
Ok, in the log, I can see this:
```
I0215 08:25:24.642247 1819808 cache.go:148] Downloading <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 to local cache
I0215 08:25:24.642673 1819808 image.go:59] Checking for <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 in local cache directory
I0215 08:25:24.642720 1819808 image.go:119] Writing <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 to local cache
I0215 08:25:24.746024 1819808 cache.go:162] Loading <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 from local cache
I0215 08:25:24.746091 1819808 cache.go:172] failed to load <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2, will try remote image if available: tarball: open /home/lmichel/.minikube/cache/kic/amd64/kicbase_v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2.tar: no such file or directory
I0215 08:25:24.746101 1819808 cache.go:174] Downloading <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 to local daemon
I0215 08:25:24.746339 1819808 image.go:75] Checking for <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 in local docker daemon
I0215 08:25:25.700332 1819808 image.go:243] Writing <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2 to local daemon
I0215 08:25:25.744105 1819808 cache.go:182] failed to download <my-docker-registry>/k8s-minikube/kicbase:v0.0.30@sha256:02c921df998f95e849058af14de7045efc3954d90320967418a0d1f182bbc0b2, will try fallback image if available: getting remote image: GET https://<my-docker-registry>/artifactory/api/docker/docker-usaw-virtual-mdl/v2/token?scope=repository%!A(MISSING)k8s-minikube%!F(MISSING)kicbase%!A(MISSING)pull&service=<my-docker-registry>%!A(MISSING)7004: : Authentication is required
```
How can I tell minikube what the credentials of my internal artifactory server are?

**Comment by afbjorklund** [comment]
I think that is normally done with `docker login` ?

**Comment by zadigus** [comment]
Of course not, nothing in that minikube is normal. I am logged in my private docker registry (with `docker login`) and I still have the issue.

**Comment by afbjorklund** [comment]
Maybe only valid for doing a manual `docker pull`

**Comment by afbjorklund** [comment]
I think it needs a new feature, in order to do the necessary `crane auth` for downloading the kicbase image to the kic cache. After the introduction of the cache (for airgapped installation), getting the image is now a two-step process.
