### ISSUE TITLE
Is there a clever way to pre-download all the docker images relevant for minikube start in a cache?

### ISSUE THREAD

**Issue by zadigus** [kubernetes/minikube#15867]
### What Happened?

I have an amazon machine image where I would like to cache the necessary docker images to start minikube (kicbase, provisioner, etc.). Currently, I am trying to do this:
```
minikube start --cache-images --download-only --driver=docker --extra-config=kubeadm.ignore-preflight-errors=NumCPU --cpus=2 --force
```
but I don't want to start minikube. I just to download and cache everything that is relevant for subsequent runs of minikube on that image.

How can I achieve that in an automated way?

### Attach the log file

no logs

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
`minikube start --download-only`

This is supposed to download what you need, the kicbase image and the preload tarball. What didn't work ?

**Comment by zadigus** [comment]
I think it's fine. It was a docker configuration issue. Thanks for your help anyway.
