### ISSUE TITLE
Minikube is unable to find socket_vmnet

### ISSUE THREAD

**Issue by malik-hasan** [kubernetes/minikube#15871]
### What Happened?

I am trying to run minikube with qemu and socket_vmnet. Socket_vmnet is running, yet minikube cannot find it.

### Attach the log file

<img width="545" alt="image" src="https://user-images.githubusercontent.com/57687010/219473025-e6bd8879-277d-4ef2-9ff1-b50e61adf57c.png">

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by spowelljr** [comment]
What is your install path for socket_vmnet? You can override the paths minikube uses for socket_vmnet but using the `--socket-vmnet-client-path` & `--socket-vmnet-path` flags on start.
