### ISSUE TITLE
minikube is starting

### ISSUE THREAD

**Issue by girikumar415** [kubernetes/minikube#15878]
### What Happened?

[logs.txt](https://github.com/kubernetes/minikube/files/10767067/logs.txt)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10767080/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
It looks like you cert has expired, try running `minikube delete --all --purge` and then try starting minikube again and see if that resolves your issues.

**Comment by girikumar415** [comment]
Thanks alot spowelljr, it working fine. Why cert has expired firsttime?
