### ISSUE TITLE
 erro ao executar mais um nó no minikuibe

### ISSUE THREAD

**Issue by rsoaresv** [kubernetes/minikube#15879]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

</details>

**A saída do comando `minikube logs`**:<details>

</details>

**A versão do sistema operacional usado**:
[logs.txt](https://github.com/kubernetes/minikube/files/10767312/logs.txt)

**Comment by josedonizetti** [comment]
@rsoaresv Oi, tudo bem? Você poderia adicionar mais informações além do log? Qual seu OS? O que estava tentando fazer? Ta usando qual driver? (docker, kvm, qemu , etc?) Qual versão do minikube vocês está utlizando? Por favor! :)
