### ISSUE TITLE
Exiting due to RUNTIME_ENABLE: sudo systemctl restart docker: Process exited with status 1

### ISSUE THREAD

**Issue by monkythe7th** [kubernetes/minikube#15880]
### What Happened?

i was running minikube tutorial and minikube start output the following:

```
 minikube start --vm-driver=virtualbox
😄  minikube v1.29.0 on Darwin 10.15.4
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl restart docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/10767396/logs.txt)

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by afbjorklund** [comment]
Looks like the disk image on that virtual machine is broken, there are I/O errors everywhere.

The easiest workaround would be to `delete` it and `start` over.

**Comment by monkythe7th** [comment]
I updated my VirtualBox to 7.0.6. ran the `delete` and `start` commands again, and got a different issue.
