### ISSUE TITLE
Failed to start hyperv VM. Running "minikube delete" may fix it: config: failed to create VM switch minikube with adapter {572AFECC-E760-4C87-96CD-79E87E78A223}: exit status 1

### ISSUE THREAD

**Issue by drumondard** [kubernetes/minikube#15899]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

</details>

**A saída do comando `minikube logs`**:<details>

</details>

**A versão do sistema operacional usado**:

**Comment by josedonizetti** [comment]
@drumondard  Oi, tudo bem? Você poderia adicionar mais informações além do log? Qual seu OS? O que estava tentando fazer? Ta usando qual driver? (docker, kvm, qemu , etc?) Qual versão do minikube vocês está utlizando? Por favor! :)
