### ISSUE TITLE
Minikube fails to start on ubuntu 22.10 & ZFS, the same works nice on ext4

### ISSUE THREAD

**Issue by ophilon** [kubernetes/minikube#15903]
### What Happened?

I have 2 similar setups - newer on laptop: Ubuntu 22.10, ZFS, 16 GB, other in a cloud VM - ubuntu 20.04, ext4, 4GB. On both installed latest containerd.io Version: 1.6.18-1. The VM works nice, the newer setup fails, and fails also on a similar Debian 11 again on ZFS. Below logs from  Ubuntu 22.10

[mk1.29kub1.26.log](https://github.com/kubernetes/minikube/files/10803614/mk1.29kub1.26.log) 

### Attach the log file

I tried to make both setups as close as possible, the biggest difference is the ZFS.

### Operating System

Ubuntu

### Driver

Docker

**Comment by evertheylen** [comment]
I had similar issues (but on Arch). Minikube seems to really require overlay2 as the storage driver and nothing else. [This blog post](https://blog.chlc.cc/p/docker-and-zfs-a-tough-pair/) helped me. Essentially you just set up a "ZFS volume" and format it as ext4, docker is then able to use it's normal overlay2 storage driver without problems. (And according to the blog post, it is even faster than the zfs storage driver!)
