### ISSUE TITLE
Exiting due to RUNTIME_ENABLE: which crictl: exit status 1 stdout:

### ISSUE THREAD

**Issue by premdeshmukh** [kubernetes/minikube#15901]
### What Happened?

Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

This error occurred when i try to install minikube on 20.04 ubuntu 

### Attach the log file

* 
* ==> Audit <==
* |---------|-------------------------------|----------|------|---------|---------------------|---------------------|
| Command |             Args              | Profile  | User | Version |     Start Time      |      End Time       |
|---------|-------------------------------|----------|------|---------|---------------------|---------------------|
| start   | --vm-driver=none              | minikube | root | v1.29.0 | 22 Feb 23 08:09 UTC |                     |
| start   | --vm-driver=none --wait=false | minikube | root | v1.29.0 | 22 Feb 23 08:10 UTC |                     |
| start   | --vm-driver=none              | minikube | root | v1.29.0 | 22 Feb 23 08:13 UTC |                     |
| start   | --vm-driver=none              | minikube | root | v1.29.0 | 22 Feb 23 08:18 UTC |                     |
| config  | set driver none               | minikube | root | v1.29.0 | 22 Feb 23 08:20 UTC | 22 Feb 23 08:20 UTC |
| start   | --vm-driver=none              | minikube | root | v1.29.0 | 22 Feb 23 08:20 UTC |                     |
|---------|-------------------------------|----------|------|---------|---------------------|---------------------|

* 
* ==> Last Start <==
* Log file created at: 2023/02/22 08:20:18
Running on machine: ip-172-31-28-105
Binary: Built with gc go1.19.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0222 08:20:18.773166   21605 out.go:296] Setting OutFile to fd 1 ...
I0222 08:20:18.773353   21605 out.go:348] isatty.IsTerminal(1) = true
I0222 08:20:18.773358   21605 out.go:309] Setting ErrFile to fd 2...
I0222 08:20:18.773365   21605 out.go:348] isatty.IsTerminal(2) = true
I0222 08:20:18.773493   21605 root.go:334] Updating PATH: /root/.minikube/bin
I0222 08:20:18.773825   21605 out.go:303] Setting JSON to false
I0222 08:20:18.774556   21605 start.go:125] hostinfo: {"hostname":"ip-172-31-28-105","uptime":12216,"bootTime":1677041803,"procs":116,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.15.0-1028-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec2f38f5-9344-c47e-34bd-63990b1fdfd0"}
I0222 08:20:18.774611   21605 start.go:135] virtualization: xen guest
I0222 08:20:18.778681   21605 out.go:177] 😄  minikube v1.29.0 on Ubuntu 20.04 (xen/amd64)
W0222 08:20:18.781702   21605 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0222 08:20:18.781901   21605 notify.go:220] Checking for updates...
I0222 08:20:18.782515   21605 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.26.1
I0222 08:20:18.783342   21605 exec_runner.go:51] Run: systemctl --version
I0222 08:20:18.786552   21605 driver.go:365] Setting default libvirt URI to qemu:///system
I0222 08:20:18.788851   21605 out.go:177] ✨  Using the none driver based on existing profile
I0222 08:20:18.790852   21605 start.go:296] selected driver: none
I0222 08:20:18.790866   21605 start.go:857] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.28.105 Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0222 08:20:18.790970   21605 start.go:868] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0222 08:20:18.790992   21605 start.go:1617] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0222 08:20:18.791451   21605 cni.go:84] Creating CNI manager for ""
I0222 08:20:18.791469   21605 cni.go:157] "none" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
I0222 08:20:18.791482   21605 start_flags.go:319] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.28.105 Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0222 08:20:18.794211   21605 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0222 08:20:18.796276   21605 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0222 08:20:18.796464   21605 cache.go:193] Successfully downloaded all kic artifacts
I0222 08:20:18.796485   21605 start.go:364] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0222 08:20:18.796560   21605 start.go:368] acquired machines lock for "minikube" in 42.852µs
I0222 08:20:18.796577   21605 start.go:96] Skipping create...Using existing machine configuration
I0222 08:20:18.796583   21605 fix.go:55] fixHost starting: m01
W0222 08:20:18.796742   21605 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0222 08:20:18.796755   21605 api_server.go:165] Checking apiserver status ...
I0222 08:20:18.796777   21605 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0222 08:20:18.809581   21605 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0222 08:20:18.809628   21605 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0222 08:20:18.821788   21605 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0222 08:20:18.821800   21605 fix.go:129] unexpected machine state, will restart: <nil>
I0222 08:20:18.824398   21605 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0222 08:20:18.827212   21605 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0222 08:20:18.827349   21605 start.go:300] post-start starting for "minikube" (driver="none")
I0222 08:20:18.827381   21605 start.go:328] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0222 08:20:18.827413   21605 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0222 08:20:18.834449   21605 main.go:141] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0222 08:20:18.834464   21605 main.go:141] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0222 08:20:18.834475   21605 main.go:141] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0222 08:20:18.837009   21605 out.go:177] ℹ️  OS release is Ubuntu 20.04.5 LTS
I0222 08:20:18.838643   21605 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0222 08:20:18.838694   21605 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0222 08:20:18.838714   21605 start.go:303] post-start completed in 11.356013ms
I0222 08:20:18.838722   21605 fix.go:57] fixHost completed within 42.139659ms
I0222 08:20:18.838728   21605 start.go:83] releasing machines lock for "minikube", held for 42.160157ms
I0222 08:20:18.839059   21605 exec_runner.go:51] Run: cat /version.json
I0222 08:20:18.839220   21605 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
W0222 08:20:18.840183   21605 start.go:396] Unable to open version.json: cat /version.json: exit status 1
stdout:

stderr:
cat: /version.json: No such file or directory
I0222 08:20:18.840241   21605 exec_runner.go:51] Run: sh -c "stat /etc/cni/net.d/*loopback.conf*"
W0222 08:20:18.842389   21605 cni.go:208] loopback cni configuration skipped: "/etc/cni/net.d/*loopback.conf*" not found
I0222 08:20:18.842463   21605 exec_runner.go:51] Run: sudo mkdir -p /etc/systemd/system/cri-docker.service.d
I0222 08:20:18.854190   21605 exec_runner.go:144] found /etc/systemd/system/cri-docker.service.d/10-cni.conf, removing ...
I0222 08:20:18.854199   21605 exec_runner.go:207] rm: /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0222 08:20:18.854248   21605 exec_runner.go:151] cp: memory --> /etc/systemd/system/cri-docker.service.d/10-cni.conf (135 bytes)
I0222 08:20:18.854389   21605 exec_runner.go:51] Run: sudo cp -a /tmp/minikube3628732627 /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0222 08:20:18.861924   21605 exec_runner.go:51] Run: sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%!p(MISSING), " -exec sh -c "sudo mv {} {}.mk_disabled" ;
I0222 08:20:18.870329   21605 cni.go:258] no active bridge cni configs found in "/etc/cni/net.d" - nothing to disable
I0222 08:20:18.870341   21605 start.go:483] detecting cgroup driver to use...
I0222 08:20:18.870363   21605 detect.go:196] detected "cgroupfs" cgroup driver on host os
I0222 08:20:18.870484   21605 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0222 08:20:18.888607   21605 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml"
W0222 08:20:18.896575   21605 start.go:450] cannot ensure containerd is configured properly and reloaded for docker - cluster might be unstable: update sandbox_image: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml": exit status 2
stdout:

stderr:
sed: can't read /etc/containerd/config.toml: No such file or directory
I0222 08:20:18.896594   21605 start.go:483] detecting cgroup driver to use...
I0222 08:20:18.896617   21605 detect.go:196] detected "cgroupfs" cgroup driver on host os
I0222 08:20:18.896776   21605 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0222 08:20:18.912553   21605 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0222 08:20:19.133072   21605 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0222 08:20:19.370841   21605 docker.go:529] configuring docker to use "cgroupfs" as cgroup driver...
I0222 08:20:19.370866   21605 exec_runner.go:144] found /etc/docker/daemon.json, removing ...
I0222 08:20:19.370872   21605 exec_runner.go:207] rm: /etc/docker/daemon.json
I0222 08:20:19.370935   21605 exec_runner.go:151] cp: memory --> /etc/docker/daemon.json (144 bytes)
I0222 08:20:19.371060   21605 exec_runner.go:51] Run: sudo cp -a /tmp/minikube2266728376 /etc/docker/daemon.json
I0222 08:20:19.380049   21605 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0222 08:20:19.600523   21605 exec_runner.go:51] Run: sudo systemctl restart docker
I0222 08:20:19.852000   21605 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0222 08:20:20.080290   21605 exec_runner.go:51] Run: sudo systemctl unmask cri-docker.socket
I0222 08:20:20.319728   21605 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0222 08:20:20.546439   21605 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0222 08:20:20.792247   21605 exec_runner.go:51] Run: sudo systemctl restart cri-docker.socket
I0222 08:20:20.807800   21605 start.go:530] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0222 08:20:20.807860   21605 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0222 08:20:20.809417   21605 start.go:551] Will wait 60s for crictl version
I0222 08:20:20.809442   21605 exec_runner.go:51] Run: which crictl
I0222 08:20:20.812849   21605 out.go:177] 
W0222 08:20:20.814969   21605 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

W0222 08:20:20.814995   21605 out.go:239] 
W0222 08:20:20.816096   21605 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0222 08:20:20.817923   21605 out.go:177] 

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Did you install `crictl` ?

**Comment by alexdohmen** [comment]
Same issue here, crictl is installed
