### ISSUE TITLE
I have pulled kicbase image locally, why minikube complains it was unable to download.

### ISSUE THREAD

**Issue by bobbyz007** [kubernetes/minikube#15902]
### What Happened?

```apache
justin@KLVC-WXX9:~$ docker images
REPOSITORY                               TAG             IMAGE ID       CREATED         SIZE
gcr.io/k8s-minikube/kicbase              v0.0.37         01c0ce65fff7   3 weeks ago     1.15GB
```
when executing 'minikube start',  it complains minikube was unable to download kicbase, but kicbase already exists! so what's the problem?
```
❗  minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.37, but successfully downloaded docker.io/kicbase/stable:v0.0.37 as a fallback image

```

### Attach the log file

😄  minikube v1.29.0 on Ubuntu 20.04
✨  Automatically selected the docker driver
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
**_❗  minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.37, but successfully downloaded docker.io/kicbase/stable:v0.0.37 as a fallback image_**
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🐳  Preparing Kubernetes v1.26.1 on Docker 20.10.23 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Depending on how it was loaded (or pulled), sometimes the local image is missing the digest ?

    --base-image='gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15'

That can be worked around by using the tag instead, if there is no access to GCR to pull it...

    --base-image='gcr.io/k8s-minikube/kicbase:v0.0.37'

**Comment by medyagh** [comment]
@bobbyz007 do u mind sharing the exact command that you pulled it ? 

do you mind sharing the exact command and the output so we can see if the SHA for both of the one that minikube expects and what your docker pull gives u are the same
