### ISSUE TITLE
Provide feedback to user when Minikube is starting. 

### ISSUE THREAD

**Issue by LalatenduMohanty** [kubernetes/minikube#1591]
**FEATURE REQUEST**

`minikube start` should provide feedback to user about which hypervisor it is using and how much RAM and CPU it is using.

**Comment by LalatenduMohanty** [comment]
We have similar request in Minishift https://github.com/minishift/minishift/issues/485 cc @gbraad

**Comment by gbraad** [comment]
Mostly we need to properly deal with pre-flight checks. especially at the moment we (minishift) download the images first, and then possibly fail due to a missing driver. This is likely something also the case for minikube, and it gives the wrong 'user feedback'.

**Comment by r2d4** [comment]
Yes, this would be great

**Comment by LalatenduMohanty** [comment]
@gbraad @r2d4  I would suggest we create another issue to track the preflight checks. So that both does not have to be implemented at one go and can be handled separately.

**Comment by gbraad** [comment]
At the moment I have worked on feedback, like preflight checks before and after startHost(), I believe this can be abstracted and helpful for inclusion in minikube too

**Comment by gbraad** [comment]
@r2d4 @aaron-prindle We have implemented some of the tests as follows:




Memory check might be needed as experienced in #2070; We have created an issue on our end for this: https://github.com/minishift/minishift/issues/1384
