### ISSUE TITLE
Not able to start Minikube on Ubuntu 22.04 on AWS

### ISSUE THREAD

**Issue by rahulchauhan7874** [kubernetes/minikube#15910]
### What Happened?

10 to 12 times I have tried complete Minikube and support files installation but finally gives below error and not able to start Minikube.

root@ip-172-31-44-172:/home/ubuntu# minikube start --network-plugin=cni --cni=calico
* minikube v1.29.0 on Ubuntu 22.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 22.04.1 LTS
E0222 21:37:48.473912   10766 start.go:415] unable to disable preinstalled bridge CNI(s): failed to disable all bridge cni configs in "/etc/cni/net.d": sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%p, " -exec sh -c "sudo mv {} {}.mk_disabled" ;: exit status 1
stdout:

stderr:
find: ‘/etc/cni/net.d’: No such file or directory

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
E0222 21:38:26.241241   11274 remote_runtime.go:145] "Version from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""
time="2023-02-22T21:38:26Z" level=fatal msg="getting the runtime version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

### Attach the log file

root@ip-172-31-44-172:/home/ubuntu# minikube start --network-plugin=cni --cni=calico
* minikube v1.29.0 on Ubuntu 22.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 22.04.1 LTS
E0222 21:37:48.473912   10766 start.go:415] unable to disable preinstalled bridge CNI(s): failed to disable all bridge cni configs in "/etc/cni/net.d": sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%p, " -exec sh -c "sudo mv {} {}.mk_disabled" ;: exit status 1
stdout:

stderr:
find: ‘/etc/cni/net.d’: No such file or directory

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
E0222 21:38:26.241241   11274 remote_runtime.go:145] "Version from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""
time="2023-02-22T21:38:26Z" level=fatal msg="getting the runtime version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

### Operating System

Ubuntu

### Driver

None

**Comment by afbjorklund** [comment]
Sounds like there is a problem with cri-dockerd, you might want to check the systemd logs for that service.

**Comment by medyagh** [comment]
@rahulchauhan7874 minikube does not install depdenecies on None Driver, and you would need to install cri-docerd and crtictl correctly,

if you want fully managed one, you could use docker driver instead of none driver

simply install docker and then
minikube delete 
and 
minikube start --driver=docker
