### ISSUE TITLE
X Exiting due to RUNTIME_ENABLE: which crictl: exit status 1 stdout:

### ISSUE THREAD

**Issue by chintan9999** [kubernetes/minikube#15914]
### What Happened?

Hello,

I have followed https://github.com/Mirantis/cri-dockerd#build-and-install this guide completely and then I try to run following command:

minikube start --vm-driver=none. It gives me this error.

* minikube v1.29.0 on Ubuntu 18.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 18.04.6 LTS

X Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

I0223 02:43:47.958349   11702 detect.go:196] detected "cgroupfs" cgroup driver on host os
I0223 02:43:47.958476   11702 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0223 02:43:47.971991   11702 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml"
W0223 02:43:47.979132   11702 start.go:450] cannot ensure containerd is configured properly and reloaded for docker - cluster might be unstable: update sandbox_image: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml": exit status 2
stdout:

stderr:
sed: can't read /etc/containerd/config.toml: No such file or directory
I0223 02:43:47.979146   11702 start.go:483] detecting cgroup driver to use...
I0223 02:43:47.979166   11702 detect.go:196] detected "cgroupfs" cgroup driver on host os
I0223 02:43:47.979262   11702 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0223 02:43:47.993161   11702 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0223 02:43:48.145862   11702 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0223 02:43:48.297816   11702 docker.go:529] configuring docker to use "cgroupfs" as cgroup driver...
I0223 02:43:48.297840   11702 exec_runner.go:144] found /etc/docker/daemon.json, removing ...
I0223 02:43:48.297846   11702 exec_runner.go:207] rm: /etc/docker/daemon.json
I0223 02:43:48.297899   11702 exec_runner.go:151] cp: memory --> /etc/docker/daemon.json (144 bytes)
I0223 02:43:48.298007   11702 exec_runner.go:51] Run: sudo cp -a /tmp/minikube2740992494 /etc/docker/daemon.json
I0223 02:43:48.304925   11702 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0223 02:43:48.447825   11702 exec_runner.go:51] Run: sudo systemctl restart docker
I0223 02:43:48.714617   11702 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0223 02:43:48.870541   11702 exec_runner.go:51] Run: sudo systemctl unmask cri-docker.socket
I0223 02:43:49.034962   11702 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0223 02:43:49.161099   11702 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0223 02:43:49.308977   11702 exec_runner.go:51] Run: sudo systemctl restart cri-docker.socket
I0223 02:43:49.323526   11702 start.go:530] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0223 02:43:49.323588   11702 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0223 02:43:49.326029   11702 start.go:551] Will wait 60s for crictl version
I0223 02:43:49.326075   11702 exec_runner.go:51] Run: which crictl
I0223 02:43:49.332026   11702 out.go:177]
W0223 02:43:49.334315   11702 out.go:239] X Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

W0223 02:43:49.334341   11702 out.go:239] *
W0223 02:43:49.335425   11702 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0223 02:43:49.338507   11702 out.go:177]

### Operating System

Ubuntu

### Driver

None

**Comment by afbjorklund** [comment]
If you run `crictl version`, what does it say ?

```console
$ sudo crictl version
Version:  0.1.0
RuntimeName:  docker
RuntimeVersion:  20.10.12
RuntimeApiVersion:  v1
```

Currently the "none" driver in minikube requires the user to set up and configure their container runtime first.

**Comment by chintan9999** [comment]
Thanks for the update. Though, I have installed docker as container run time. should I need to explicitly installed any other cri-tools?

Does docker no longer supported as cri-tool by kubernetes?

**Comment by afbjorklund** [comment]
Before Kubernetes 1.24, the support for docker was included with the installation (called "dockershim").

After that, you need to make sure to install all the needed components:

docker, cri-dockerd, cri-tools, cni-plugins

Eventually minikube should be able to "provision" these as well, but right now it does not (only Docker).

**Comment by avigupta63** [comment]
cri-tools, cni-plugins how can i install these?

**Comment by chintan9999** [comment]
Thanks for your response @afbjorklund.

I can understand that docker and k8s, both are managed different way. 

Though, I would suggest that it would be very convenient if minikube can able to provision these altogether rather separate cri-tools and plugin installation.

For example, previous k8s versions like 1.21 or before, it was easy to work with docker as CRI for k8s compare to current version.

I hope something is being developed for this as well at other end.

**Comment by chintan9999** [comment]
@avigupta63 here is the link I used for cri-tools:

https://github.com/Mirantis/cri-dockerd

**Comment by afbjorklund** [comment]
> For example, previous k8s versions like 1.21 or before, it was easy to work with docker as CRI for k8s compare to current version.

This changed in 1.24, when upstream stopped supporting it (Docker)

But there is a backlog item, to improve the installation experience:

* https://github.com/kubernetes/minikube/issues/15460

Currently it is mostly affecting the "none" driver, for advanced users.

**Comment by afbjorklund** [comment]
Also, to be fair, it is not harder to install a cluster using docker than for instance containerd ?

You need to set up CRI and CNI, the main difference is that is now less of a "special case"

**Comment by sumitdahatonde** [comment]
stderr:
find: ‘/etc/cni/net.d’: No such file or directory
^[[A
X Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │

**Comment by avigupta63** [comment]
My minikube started with a error unable to disable bridges......when i check my nodes they weren't ready 
can u help me with this  @afbjorklund
