### ISSUE TITLE
linux 下安装minikube  start时报错downloading kubeadm: download failed

### ISSUE THREAD

**Issue by lisongzhan** [kubernetes/minikube#15929]
**重现问题所需的命令**：
minikube start --registry-mirror=https://registry.docker-cn.com/ --kubernetes-version=1.18.8
**失败的命令的完整输出**：<details>

[minikube@hecs-104288 ~]$ minikube start --registry-mirror=https://registry.docker-cn.com --kubernetes-version=1.18.8 
😄  Centos 8.5.2111 (amd64) 上的 minikube v1.18.1
🆕  Kubernetes 1.20.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.20.2
✨  根据现有的配置文件使用 docker 驱动程序
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🐳  正在 Docker 20.10.3 中准备 Kubernetes v1.18.8…

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubeadm.sha256 Dst:/home/minikube/.minikube/cache/linux/v1.18.8/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58] Decompressors:map[bz2:0x2db2d58 gz:0x2db2d58 tar.bz2:0x2db2d58 tar.gz:0x2db2d58 tar.xz:0x2db2d58 tbz2:0x2db2d58 tgz:0x2db2d58 txz:0x2db2d58 xz:0x2db2d58 zip:0x2db2d58] Getters:map[file:0xc000cf0a10 http:0xc000c1c760 https:0xc000c1c780] Dir:false ProgressListener:0x2d78370 Options:[0xfdf780]}: invalid checksum: Error downloading checksum file: bad response code: 404
</details>

**`minikube logs`命令的输出**： <details>
W0226 23:16:45.713261 1727026 out.go:191] ❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.18.8/bin/linux/amd64/kubeadm.sha256 Dst:/home/minikube/.minikube/cache/linux/v1.18.8/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58 0x2db2d58] Decompressors:map[bz2:0x2db2d58 gz:0x2db2d58 tar.bz2:0x2db2d58 tar.gz:0x2db2d58 tar.xz:0x2db2d58 tbz2:0x2db2d58 tgz:0x2db2d58 txz:0x2db2d58 xz:0x2db2d58 zip:0x2db2d58] Getters:map[file:0xc000cf0a10 http:0xc000c1c760 https:0xc000c1c780] Dir:false ProgressListener:0x2d78370 Options:[0xfdf780]}: invalid checksum: Error downloading checksum file: bad response code: 404
W0226 23:16:45.713305 1727026 out.go:191] 
W0226 23:16:45.713339 1727026 out.go:191] 😿  If the above advice does not help, please let us know: 
W0226 23:16:45.713365 1727026 out.go:191] 👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**使用的操作系统版本**：
Linux version 4.18.0-348.7.1.el8_5.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)) #1 SMP Wed Dec 22 13:25:12 UTC 2021

**Comment by seanjoe** [comment]
一样的错误，楼主解决了么
