### ISSUE TITLE
How to list all images that is needed for minikube to start?

### ISSUE THREAD

**Issue by drriguz** [kubernetes/minikube#15926]
### What Happened?

As described in [minikube FAQ](https://minikube.sigs.k8s.io/docs/faq/#i-am-in-china-and-i-encounter-errors-when-trying-to-start-minikube-what-should-i-do), for China mainland users, a registry might be specified in order to pull the gcr images.
It's awesome that there's already an option, ie `--image-mirror-country='cn' --kubernetes-version=v1.23.8` that will pull image from  a reigstry. However, newer versions of kubernetes won't work.

Also, minikube supports users to use another registry via `minikube start --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'`.

**My question is, how can I list all the images that is necessary for minikube to start?** If so, then I'll be able to pull them from gcr (via VPN) and push to my own registry, instead of synchronizing all images from gcr.io(like what is doing in `registry.cn-hangzhou.aliyuncs.com/google_containers`). I've already searched the code and did not found how images are determined.

Thanks in advance!

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/10832825/log.txt)

### Operating System

Windows

### Driver

Docker

**Comment by afbjorklund** [comment]
Sounds like a bug, all images _should_ use the mirror... Which one was missing ?
