### ISSUE TITLE
unable to start minikube 

### ISSUE THREAD

**Issue by Manvendra3107** [kubernetes/minikube#15938]
### What Happened?

when i run this code its me error like ,  ! StartHost failed, but will try again: creating host: create: precreate: exec:                                      "docker": executable file not found in $PATH
* Running on localhost (CPUs=2, Memory=3920MB, Disk=7755MB) ...
* Failed to start none bare metal machine. Running "minikube delete" may fix it:                                      creating host: create: precreate: exec: "docker": executable file not found in                                      $PATH

X Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: p                                     recreate: exec: "docker": executable file not found in $PATH

### Attach the log file

minikube start --driver=none (Its only for practice)

### Operating System

Ubuntu

### Driver

None

**Comment by afbjorklund** [comment]
See https://minikube.sigs.k8s.io/docs/drivers/none/
