### ISSUE TITLE
minikube not start

### ISSUE THREAD

**Issue by omnain11** [kubernetes/minikube#15958]
### What Happened?

 * If the above advice does not help, please let us know:                                       
 * https://github.com/kubernetes/minikube/issues/new/choose                               
                                                                                             
   * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    
                                                                                             

### Attach the log file

*
* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   |                  | minikube | root | v1.29.0 | 03 Mar 23 03:08 UTC |          |
| start   | --driver=none    | minikube | root | v1.29.0 | 03 Mar 23 03:12 UTC |          |
| start   | --driver=none    | minikube | root | v1.29.0 | 03 Mar 23 03:13 UTC |          |
| start   |                  | minikube | root | v1.29.0 | 03 Mar 23 03:13 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 03 Mar 23 03:17 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 03 Mar 23 03:18 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 03 Mar 23 03:27 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 03 Mar 23 03:28 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2023/03/03 03:28:53
Running on machine: ip-172-31-46-180
Binary: Built with gc go1.19.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0303 03:28:53.452483   12961 out.go:296] Setting OutFile to fd 1 ...
I0303 03:28:53.452696   12961 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0303 03:28:53.452702   12961 out.go:309] Setting ErrFile to fd 2...
I0303 03:28:53.452708   12961 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0303 03:28:53.452829   12961 root.go:334] Updating PATH: /root/.minikube/bin
W0303 03:28:53.452961   12961 root.go:311] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0303 03:28:53.453148   12961 out.go:303] Setting JSON to false
I0303 03:28:53.453880   12961 start.go:125] hostinfo: {"hostname":"ip-172-31-46-180","uptime":2116,"bootTime":1677812017,"procs":109,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.0-1028-aws","kernelArch":"x86_64","virtualizationSystem":"vbox","virtualizationRole":"host","hostId":"ec2ef202-66a2-7cea-4807-c9713738da0c"}
I0303 03:28:53.453943   12961 start.go:135] virtualization: vbox host
I0303 03:28:53.459438   12961 out.go:177] * minikube v1.29.0 on Ubuntu 22.04
W0303 03:28:53.465352   12961 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0303 03:28:53.465518   12961 notify.go:220] Checking for updates...
I0303 03:28:53.465771   12961 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.26.1
W0303 03:28:53.465832   12961 start.go:765] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I0303 03:28:53.465874   12961 driver.go:365] Setting default libvirt URI to qemu:///system
W0303 03:28:53.465899   12961 start.go:765] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I0303 03:28:53.470416   12961 out.go:177] * Using the none driver based on existing profile
"logs.txt" 113L, 19163B

### Operating System

Ubuntu

### Driver

None

**Comment by akdean** [comment]
It looks like you might be trying to run `minikube` as root for some reason, can you try with a non-root user.

**Comment by omnain11** [comment]
𝚃𝚑𝚊𝚗𝚔𝚜 𝚂𝚒𝚛 𝚈𝚘𝚞 𝚊𝚛𝚎 𝚊 𝚐𝚛𝚎𝚊𝚝 𝚙𝚎𝚛𝚜𝚘𝚗 𝚒𝚗 𝚝𝚑𝚎
𝚠𝚘𝚛𝚕𝚍 𝚊𝚗𝚍 𝚊𝚐𝚊𝚒𝚗... 𝚃𝚑𝚊𝚗𝚔𝚜
