### ISSUE TITLE
Not able to enable NGINX ingress controller  in minukube

### ISSUE THREAD

**Issue by priyabrat-mishra** [kubernetes/minikube#15953]
### What Happened?

Below is the error while trying to enable NGINX ingress controller in minikube .

PS C:\minikube> minikube addons enable ingress
* ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
  - Using image registry.k8s.io/ingress-nginx/controller:v1.5.1
  - Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
  - Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
* Verifying ingress addon...

X Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
*
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                             │
│    * If the above advice does not help, please let us know:                                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                                               │
│                                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                    │
│    * Please also attach the following file to the GitHub issue:                                             │
│    * - C:\Users\PMI141\AppData\Local\Temp\minikube_addons_f58bdde16d411cc7df63035e8654d0144210c786_0.log    │
│                                                                            
[minikube_addons_f58bdde16d411cc7df63035e8654d0144210c786_0.log](https://github.com/kubernetes/minikube/files/10871651/minikube_addons_f58bdde16d411cc7df63035e8654d0144210c786_0.log)
                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
[logs.txt](https://github.com/kubernetes/minikube/files/10871641/logs.txt)

### Attach the log file

I have attached the logs from minikube logs . Also below are the errors from ingress pods .

Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                From               Message
  ----     ------            ----               ----               -------
  Warning  FailedScheduling  11m                default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
  Warning  FailedScheduling  16m (x2 over 21m)  default-scheduler  0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..
PS C:\minikube> kubectl get pods -A

### Operating System

Windows

### Driver

Hyper-V

**Comment by hvojdani** [comment]
I have same issue on wsl2

**Comment by nkm269** [comment]
@hvojdani 
wow it worked..great..thank you so much
