### ISSUE TITLE
starting minikube with virutalbox driver on arm64 M1 mac

### ISSUE THREAD

**Issue by Vijay2112** [kubernetes/minikube#15965]
My minikube version: 

```
minikube version: v1.29.0
commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3
```

`minikube start --driver=virtualbox`
```

😄  minikube v1.29.0 on Darwin 13.2 (arm64)
✨  Using the virtualbox driver based on user configuration

❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'virtualbox' is not supported on darwin/arm64
```

I am using virtualbox for arm64 M1 host from: https://download.virtualbox.org/virtualbox/7.0.6/VirtualBox-7.0.6_BETA4-155176-macOSArm64.dmg

**Comment by afbjorklund** [comment]
VirtualBox only supports Intel virtual machines, so it is not useful for minikube when running on M1.

**Comment by Vijay2112** [comment]
But there’s beta version released for virtual box for m1 macs already. 

https://download.virtualbox.org/virtualbox/7.0.6/VirtualBox-7.0.6_BETA4-155176-macOSArm64.dmg

**Comment by afbjorklund** [comment]
I don't think it supports (or will ever support) ARM virtual machines, so you need to use another driver.

**Comment by gregkonush** [comment]
@afbjorklund I think @Vijay2112  is correctly pointing out that arm support already exists for Virtualbox

![image](https://user-images.githubusercontent.com/12027037/230675117-d5b9ebc3-80d8-493f-bceb-57b545f5fd62.png)

**Comment by torenware** [comment]
@gregkonush People testing the preview version are having a very bad time of it.  I'm hearing it's too buggy to use.
