### ISSUE TITLE
Minikube not starting 

### ISSUE THREAD

**Issue by Imsandarbh** [kubernetes/minikube#15968]
### What Happened?

root@user-ThinkBook-14-G2-ITL:/home/user# docker ps
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
root@user-ThinkBook-14-G2-ITL:/home/user# minikube start
😄  minikube v1.29.0 on Ubuntu 20.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 20.04.5 LTS
E0306 12:31:21.729126   42082 start.go:415] unable to disable preinstalled bridge CNI(s): failed to disable all bridge cni configs in "/etc/cni/net.d": sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%p, " -exec sh -c "sudo mv {} {}.mk_disabled" ;: exit status 1
stdout:

stderr:
find: ‘/etc/cni/net.d’: No such file or directory

❌  Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

### Attach the log file

Minikube is not working

### Operating System

Ubuntu

### Driver

Docker

**Comment by Chandranana** [comment]
@Imsandarbh Can u please tell what was the solution or workaround for this?
