### ISSUE TITLE
raspberryPI ?

### ISSUE THREAD

**Issue by joeblew99** [kubernetes/minikube#160]
Sorry but gotta ask :)

**Comment by luxas** [comment]
I'm working on it :)
Closing in favor for #5 

(If you want to run Kubernetes on Raspberry Pi, use my project here: https://github.com/luxas/kubernetes-on-arm)

**Comment by joeblew99** [comment]
Ok yes I see the multi-arch issue.

I will be able to help test as I also have access to arm64 from a data
Center in France if need be.

**Comment by luxas** [comment]
Great, thanks!
