### ISSUE TITLE
problème minikube

### ISSUE THREAD

**Issue by tchakpame** [kubernetes/minikube#16018]
### What Happened?

 Veuillez exécuter `minikube logs --file=logs.txt` et attachez logs.txt au problème GitHub.    │
 minikube v1.29.0 sur Ubuntu 20.04
    ▪ KUBECONFIG=/etc/kubernetes/admin.conf
✨  Utilisation du pilote virtualbox basé sur le profil existant
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
🏃  Mise à jour du VM virtualbox en marche "minikube" ...
🐳  Préparation de Kubernetes v1.26.1 sur Docker 20.10.23...
🤦  Impossible de redémarrer le cluster, va être réinitialisé : getting k8s client: client config: client config: context "minikube" does not exist
    ▪ Génération des certificats et des clés
    ▪ Démarrage du plan de contrôle ...
    ▪ Configuration des règles RBAC ...
🔗  Configuration de bridge CNI (Container Networking Interface)...

❌  Fermeture en raison de GUEST_START : Failed kubeconfig update: writing kubeconfig: Error writing file /etc/kubernetes/admin.conf: open /etc/kubernetes/admin.conf: permission denied

### Attach the log file

 minikube v1.29.0 sur Ubuntu 20.04
    ▪ KUBECONFIG=/etc/kubernetes/admin.conf
✨  Utilisation du pilote virtualbox basé sur le profil existant
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
🏃  Mise à jour du VM virtualbox en marche "minikube" ...
🐳  Préparation de Kubernetes v1.26.1 sur Docker 20.10.23...
🤦  Impossible de redémarrer le cluster, va être réinitialisé : getting k8s client: client config: client config: context "minikube" does not exist
    ▪ Génération des certificats et des clés
    ▪ Démarrage du plan de contrôle ...
    ▪ Configuration des règles RBAC ...
🔗  Configuration de bridge CNI (Container Networking Interface)...

❌  Fermeture en raison de GUEST_START : Failed kubeconfig update: writing kubeconfig: Error writing file /etc/kubernetes/admin.conf: open /etc/kubernetes/admin.conf: permission denied

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by afbjorklund** [comment]
`unset KUBECONFIG`
