### ISSUE TITLE
Local changes are lost with Qemu

### ISSUE THREAD

**Issue by danielepolencic** [kubernetes/minikube#16013]
### What Happened?

With the Qemu driver:

```
minikube start --no-kubernetes --container-runtime=containerd --driver=qemu
mininkube ssh touch hello.txt
minikube stop
minikube start
minikube ssh ls
// empty
```

With the Docker driver:

```
minikube start --no-kubernetes --container-runtime=containerd --driver=docker
mininkube ssh touch hello.txt
minikube stop
minikube start
minikube ssh ls
hello.txt
```

The same behaviour can be observed with the `minikube node stop <node>` command. The node that is stopped and uses the Qemu driver loses all local state.

### Attach the log file

minikube version: v1.29.0
commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3

### Operating System

macOS on M1

### Driver

QEMU

**Comment by afbjorklund** [comment]
Only certain directories are persisted, check with the documentation.

https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/

**Comment by danielepolencic** [comment]
Thank you. My bad, I dismissed it because it mentions PVs (and I use `--no-kubernetes`). However, this covers persistence for PVs AND VMs.

I noticed that this behaviour means we must reprovision the entire node every time it is restarted. Example: I'm installing a systemd unit: when I reboot, the file is not there anymore.
I guess the workaround is either a) using the docker driver or b) using qemu with the [sync scripts.](https://minikube.sigs.k8s.io/docs/handbook/filesync/)

Anything else that I'm missing?

**Comment by afbjorklund** [comment]
It could need some more documentation, perhaps. Most of it was on the Docker Machine side, before.

But there are some endpoints that you can use for setup, if your node needs non-kubernetes things...

`/var/lib/boot2docker/bootlocal.sh`

It will be run, after the disk is mounted.

**Comment by danielepolencic** [comment]
Spoiler alert: I'm actually running Kubernetes, but manually (e.g. following the same steps as minikube, but one by one, typing every single command).

> if your node needs non-kubernetes things...

I guess I can refer to this: https://github.com/boot2docker/boot2docker/blob/master/FAQ.md#local-customisation-with-persistent-partition
