### ISSUE TITLE
Minikube mount fails on Qemu/Docker

### ISSUE THREAD

**Issue by danielepolencic** [kubernetes/minikube#16014]
### What Happened?

```
minikube start --no-kubernetes --container-runtime=containerd --driver=qemu
mkdir /tmp/minikube
cd /tmp/minikube
touch hello.txt
minikube ssh
ls // -> I can see the hello.txt
minikube mount $PWD:/home/docker
📁  Mounting host path /tmp/arch into VM as /home/docker ...
    ▪ Mount type:   
    ▪ User ID:      docker
    ▪ Group ID:     docker
    ▪ Version:      9p2000.L
    ▪ Message Size: 262144
    ▪ Options:      map[]
    ▪ Bind Address: 192.168.105.1:63841
🚀  Userspace file server: ufs starting
✅  Successfully mounted /tmp/arch to /home/docker

📌  NOTE: This process must stay alive for the mount to be accessible ...
```

At this point, I can no longer SSH into minikube. In a new terminal:

```
minikube ssh
ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```

Stopping the mount does not solve the issue. I still keep getting the same error.

### Attach the log file

minikube ssh -v=8 --alsologtostderr
I0310 10:56:34.127751   91058 out.go:296] Setting OutFile to fd 1 ...
I0310 10:56:34.128040   91058 out.go:348] isatty.IsTerminal(1) = true
I0310 10:56:34.128052   91058 out.go:309] Setting ErrFile to fd 2...
I0310 10:56:34.128059   91058 out.go:348] isatty.IsTerminal(2) = true
I0310 10:56:34.128117   91058 root.go:334] Updating PATH: /Users/danielepolencic/.minikube/bin
I0310 10:56:34.128539   91058 mustload.go:65] Loading cluster: minikube
I0310 10:56:34.128795   91058 config.go:180] Loaded profile config "minikube": Driver=qemu2, ContainerRuntime=containerd, KubernetesVersion=v0.0.0
I0310 10:56:34.131409   91058 host.go:66] Checking if "minikube" exists ...
I0310 10:56:34.131849   91058 host.go:66] Checking if "minikube" exists ...
I0310 10:56:34.133154   91058 main.go:141] libmachine: Using SSH client type: native
I0310 10:56:34.133374   91058 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0x1053265d0] 0x105329070 <nil>  [] 0s} 192.168.105.29 22 <nil> <nil>}
W0310 10:56:34.158517   91058 out.go:239] ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
ssh: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### Operating System

macOS on a M1

### Driver

QEMU, Docker

**Comment by afbjorklund** [comment]
When you mount another directory over the home directory, you effectively remove the ssh keys needed for login:

```console
$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ pwd
/home/docker
$ ls -aR
.:
.  ..  .bash_history  .ssh

./.ssh:
.  ..  authorized_keys	authorized_keys2
$ logout

```



So you should use another directory for your mountpoint, such as `/mnt/arch`. And leave the `/home/docker` intact...

**Comment by danielepolencic** [comment]
Ha! Understood; thanks for clarifying.
