### ISSUE TITLE
403 when pulling registry.k8s.io inside minikube (docker driver)

### ISSUE THREAD

**Issue by jenwirth** [kubernetes/minikube#16028]
### What Happened?

Hi,

On one of our machines we are getting errors when running minikube. Further investigation tells us we are getting 403 errors when pulling image. However this only happens inside the minikube instance and not on the host:

```
host> docker pull registry.k8s.io/pause:3.6
3.6: Pulling from pause
fbe1a72f5dcd: Pull complete 
Digest: sha256:3d380ca8864549e74af4b29c10f9cb0956236dfb01c40ca076fb6c37253234db
Status: Downloaded newer image for registry.k8s.io/pause:3.6
registry.k8s.io/pause:3.6

```

Then within minikube 

```
minikube> docker pull registry.k8s.io/pause:3.6
Error response from daemon: error parsing HTTP 403 response body: 
```

This is the response:

```
minikube> curl -L https://registry.k8s.io/v2/pause/blobs/sha256:5d3b3e9a3c9380bd2e56f873bde8638d0f8e95f94a67c09b66f7f82d9f292ea1

<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>403 Forbidden</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Forbidden</h1>
<h2>Your client does not have permission to get URL <code>/v2/pause/blobs/sha256:5d3b3e9a3c9380bd2e56f873bde8638d0f8e95f94a67c09b66f7f82d9f292ea1</code> from this server.</h2>
<h2></h2>
</body></html>

```

It only happens on one machine in a set of 5.

### Attach the log file

E0311 08:52:06.150343   39426 logs.go:193] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.24.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.24.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Sounds like a proxy ?

**Comment by jenwirth** [comment]
We don't use a proxy and i checked inside minikube, no proxy has been set. I thought perhaps our IP was blacklisted, but that would not explain why it works on the host and only has a problem within a minikube container

**Comment by rparree** [comment]
@jenwirth I had the same problem today on two machines. Did you ever found out the reason? I was able to change the IP addresses of the two machines. However  to no avail.

**Comment by hsafe** [comment]
Hi there,
Had the same issue, the work around was to:
dig k8s.gcr.io
Then define a static /etc/hosts entry from the CNAME returned IP
Here is the [reference:](https://stackoverflow.com/questions/64229221/kubernetes-failed-to-pull-image-k8s-gcr-io)

**Comment by mariusleu** [comment]
The problem still persists with the newer `registry.k8s.io`. It turns out it always returns `403` when accessed via IPv6, so you'd have to disable IPv6 on that machine.
