### ISSUE TITLE
Minikube not start

### ISSUE THREAD

**Issue by rragul** [kubernetes/minikube#16027]
### What Happened?

minikube start 

😄  minikube v1.29.0 on Ubuntu 22.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 22.04.2 LTS

❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
time="2023-03-11T12:30:39+05:30" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

* 
* ==> Audit <==
* |----------------|-------------------------------------------------------------------------------------|----------|------|---------|-----------------------|-----------------------|
|    Command     |                                        Args                                         | Profile  | User | Version |      Start Time       |       End Time        |
|----------------|-------------------------------------------------------------------------------------|----------|------|---------|-----------------------|-----------------------|
| start          | --driver=docker                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:53 +0530 |                       |
| start          | --driver=docker                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:54 +0530 |                       |
| start          | --driver=docker                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:54 +0530 |                       |
| start          | --force                                                                             | minikube | root | v1.29.0 | 06 Mar 23 10:54 +0530 |                       |
| start          | --driver=docker --force                                                             | minikube | root | v1.29.0 | 06 Mar 23 10:55 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:55 +0530 | 06 Mar 23 10:55 +0530 |
| stop           |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:55 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:55 +0530 | 06 Mar 23 10:55 +0530 |
| profile        | list                                                                                | minikube | root | v1.29.0 | 06 Mar 23 10:55 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:55 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:56 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:56 +0530 | 06 Mar 23 10:56 +0530 |
| stop           |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:57 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:57 +0530 | 06 Mar 23 10:57 +0530 |
| start          | --force --driver=docker                                                             | minikube | root | v1.29.0 | 06 Mar 23 10:57 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 10:59 +0530 |                       |
| start          | --force --driver=docker                                                             | minikube | root | v1.29.0 | 06 Mar 23 10:59 +0530 |                       |
| start          | --memory=max --cpus=max                                                             | minikube | root | v1.29.0 | 06 Mar 23 10:59 +0530 |                       |
|                | --registry-mirror=https://registry.docker-cn.com,https://docker.mirrors.ustc.edu.cn |          |      |         |                       |                       |
| start          | --force --driver=none                                                               | minikube | root | v1.29.0 | 06 Mar 23 11:02 +0530 |                       |
| start          | --force --driver=none                                                               | minikube | root | v1.29.0 | 06 Mar 23 11:02 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 11:13 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 11:25 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 18:32 +0530 |                       |
| dashboard      |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 18:57 +0530 |                       |
| start          | --force                                                                             | minikube | root | v1.29.0 | 06 Mar 23 18:57 +0530 |                       |
| start          | --force                                                                             | minikube | root | v1.29.0 | 06 Mar 23 19:00 +0530 |                       |
| start          | --driver=docker                                                                     | minikube | root | v1.29.0 | 06 Mar 23 19:05 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 19:05 +0530 | 06 Mar 23 19:05 +0530 |
| start          | --driver=docker                                                                     | minikube | root | v1.29.0 | 06 Mar 23 19:05 +0530 |                       |
| start          | --driver=docker                                                                     | minikube | root | v1.29.0 | 06 Mar 23 19:05 +0530 |                       |
| start          | --force                                                                             | minikube | root | v1.29.0 | 06 Mar 23 19:05 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 19:22 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 19:25 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 20:47 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 06 Mar 23 21:19 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 07 Mar 23 08:52 +0530 |                       |
| stop           |                                                                                     | minikube | root | v1.29.0 | 07 Mar 23 08:55 +0530 | 07 Mar 23 08:55 +0530 |
| delete         |                                                                                     | minikube | root | v1.29.0 | 07 Mar 23 08:55 +0530 | 07 Mar 23 08:55 +0530 |
| start          | --driver=kvm2                                                                       | minikube | root | v1.29.0 | 07 Mar 23 08:56 +0530 |                       |
| start          | --driver=kvm2 --force                                                               | minikube | root | v1.29.0 | 07 Mar 23 08:56 +0530 |                       |
| start          | --driver=kvm2 --force                                                               | minikube | root | v1.29.0 | 07 Mar 23 08:59 +0530 |                       |
| start          | --driver=kvm2 --force                                                               | minikube | root | v1.29.0 | 07 Mar 23 08:59 +0530 | 07 Mar 23 09:00 +0530 |
| start          |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:33 +0530 |                       |
| start          | --force                                                                             | minikube | root | v1.29.0 | 11 Mar 23 11:33 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:33 +0530 | 11 Mar 23 11:33 +0530 |
| start          |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:34 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:35 +0530 | 11 Mar 23 11:35 +0530 |
| start          | --driver=kvm2                                                                       | minikube | root | v1.29.0 | 11 Mar 23 11:35 +0530 |                       |
| start          | --driver=docker                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:35 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:35 +0530 | 11 Mar 23 11:35 +0530 |
| start          | --driver=docker                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:36 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:36 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:36 +0530 | 11 Mar 23 11:36 +0530 |
| start          |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:36 +0530 |                       |
| delete         |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:36 +0530 | 11 Mar 23 11:36 +0530 |
| start          |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:36 +0530 |                       |
| update-context |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:54 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 11:54 +0530 |                       |
| start          |                                                                                     | minikube | root | v1.29.0 | 11 Mar 23 12:30 +0530 |                       |
| start          | --force                                                                             | minikube | root | v1.29.0 | 11 Mar 23 12:32 +0530 |                       |
|----------------|-------------------------------------------------------------------------------------|----------|------|---------|-----------------------|-----------------------|

* 
* ==> Last Start <==
* Log file created at: 2023/03/11 12:32:37
Running on machine: ragul
Binary: Built with gc go1.19.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0311 12:32:37.171307   46881 out.go:296] Setting OutFile to fd 1 ...
I0311 12:32:37.171432   46881 out.go:348] isatty.IsTerminal(1) = true
I0311 12:32:37.171435   46881 out.go:309] Setting ErrFile to fd 2...
I0311 12:32:37.171440   46881 out.go:348] isatty.IsTerminal(2) = true
I0311 12:32:37.171521   46881 root.go:334] Updating PATH: /root/.minikube/bin
I0311 12:32:37.171827   46881 out.go:303] Setting JSON to false
I0311 12:32:37.173399   46881 start.go:125] hostinfo: {"hostname":"ragul","uptime":8652,"bootTime":1678509506,"procs":392,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.19.0-35-generic","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"29d03938-f53e-0b46-bf7f-0af1b0ea5f11"}
I0311 12:32:37.173436   46881 start.go:135] virtualization: kvm host
I0311 12:32:37.174774   46881 out.go:177] 😄  minikube v1.29.0 on Ubuntu 22.04
W0311 12:32:37.175735   46881 out.go:239] ❗  minikube skips various validations when --force is supplied; this may lead to unexpected behavior
I0311 12:32:37.175812   46881 notify.go:220] Checking for updates...
I0311 12:32:37.175998   46881 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.26.1
I0311 12:32:37.176204   46881 exec_runner.go:51] Run: systemctl --version
I0311 12:32:37.177327   46881 driver.go:365] Setting default libvirt URI to qemu:///system
I0311 12:32:37.177997   46881 out.go:177] ✨  Using the none driver based on existing profile
I0311 12:32:37.178525   46881 start.go:296] selected driver: none
I0311 12:32:37.178533   46881 start.go:857] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:3900 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.8.153 Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0311 12:32:37.178584   46881 start.go:868] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0311 12:32:37.178594   46881 start.go:1617] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0311 12:32:37.179940   46881 cni.go:84] Creating CNI manager for ""
I0311 12:32:37.179949   46881 cni.go:157] "none" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
I0311 12:32:37.179955   46881 start_flags.go:319] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:3900 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.8.153 Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0311 12:32:37.181003   46881 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0311 12:32:37.181573   46881 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0311 12:32:37.181683   46881 cache.go:193] Successfully downloaded all kic artifacts
I0311 12:32:37.181694   46881 start.go:364] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0311 12:32:37.181731   46881 start.go:368] acquired machines lock for "minikube" in 29.666µs
I0311 12:32:37.181738   46881 start.go:96] Skipping create...Using existing machine configuration
I0311 12:32:37.181740   46881 fix.go:55] fixHost starting: m01
W0311 12:32:37.182087   46881 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0311 12:32:37.182096   46881 api_server.go:165] Checking apiserver status ...
I0311 12:32:37.182110   46881 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0311 12:32:37.196417   46881 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0311 12:32:37.196444   46881 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0311 12:32:37.204206   46881 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0311 12:32:37.204218   46881 fix.go:129] unexpected machine state, will restart: <nil>
I0311 12:32:37.204982   46881 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0311 12:32:37.206558   46881 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0311 12:32:37.206646   46881 start.go:300] post-start starting for "minikube" (driver="none")
I0311 12:32:37.206665   46881 start.go:328] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0311 12:32:37.206682   46881 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0311 12:32:37.212296   46881 main.go:141] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0311 12:32:37.212313   46881 main.go:141] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0311 12:32:37.212319   46881 main.go:141] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0311 12:32:37.212980   46881 out.go:177] ℹ️  OS release is Ubuntu 22.04.2 LTS
I0311 12:32:37.213487   46881 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0311 12:32:37.213510   46881 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0311 12:32:37.213521   46881 start.go:303] post-start completed in 6.870747ms
I0311 12:32:37.213525   46881 fix.go:57] fixHost completed within 31.785582ms
I0311 12:32:37.213528   46881 start.go:83] releasing machines lock for "minikube", held for 31.792908ms
I0311 12:32:37.213817   46881 exec_runner.go:51] Run: cat /version.json
I0311 12:32:37.213926   46881 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
W0311 12:32:37.214314   46881 start.go:396] Unable to open version.json: cat /version.json: exit status 1
stdout:

stderr:
cat: /version.json: No such file or directory
I0311 12:32:37.214344   46881 exec_runner.go:51] Run: sh -c "stat /etc/cni/net.d/*loopback.conf*"
W0311 12:32:37.215429   46881 cni.go:208] loopback cni configuration skipped: "/etc/cni/net.d/*loopback.conf*" not found
I0311 12:32:37.215478   46881 exec_runner.go:51] Run: sudo mkdir -p /etc/systemd/system/cri-docker.service.d
I0311 12:32:37.221329   46881 exec_runner.go:144] found /etc/systemd/system/cri-docker.service.d/10-cni.conf, removing ...
I0311 12:32:37.221336   46881 exec_runner.go:207] rm: /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0311 12:32:37.221373   46881 exec_runner.go:151] cp: memory --> /etc/systemd/system/cri-docker.service.d/10-cni.conf (135 bytes)
I0311 12:32:37.221466   46881 exec_runner.go:51] Run: sudo cp -a /tmp/minikube11277273 /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0311 12:32:37.227302   46881 exec_runner.go:51] Run: sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%!p(MISSING), " -exec sh -c "sudo mv {} {}.mk_disabled" ;
I0311 12:32:37.232923   46881 cni.go:258] no active bridge cni configs found in "/etc/cni/net.d" - nothing to disable
I0311 12:32:37.232931   46881 start.go:483] detecting cgroup driver to use...
I0311 12:32:37.232946   46881 detect.go:199] detected "systemd" cgroup driver on host os
I0311 12:32:37.233027   46881 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0311 12:32:37.244894   46881 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml"
I0311 12:32:37.250917   46881 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)restrict_oom_score_adj = .*$|\1restrict_oom_score_adj = false|' /etc/containerd/config.toml"
I0311 12:32:37.257121   46881 containerd.go:145] configuring containerd to use "systemd" as cgroup driver...
I0311 12:32:37.257144   46881 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)SystemdCgroup = .*$|\1SystemdCgroup = true|g' /etc/containerd/config.toml"
I0311 12:32:37.263061   46881 exec_runner.go:51] Run: sh -c "sudo sed -i 's|"io.containerd.runtime.v1.linux"|"io.containerd.runc.v2"|g' /etc/containerd/config.toml"
I0311 12:32:37.269286   46881 exec_runner.go:51] Run: sh -c "sudo sed -i '/systemd_cgroup/d' /etc/containerd/config.toml"
I0311 12:32:37.275724   46881 exec_runner.go:51] Run: sh -c "sudo sed -i 's|"io.containerd.runc.v1"|"io.containerd.runc.v2"|g' /etc/containerd/config.toml"
I0311 12:32:37.282064   46881 exec_runner.go:51] Run: sh -c "sudo rm -rf /etc/cni/net.mk"
I0311 12:32:37.287920   46881 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)conf_dir = .*$|\1conf_dir = "/etc/cni/net.d"|g' /etc/containerd/config.toml"
I0311 12:32:37.293910   46881 exec_runner.go:51] Run: sudo sysctl net.bridge.bridge-nf-call-iptables
I0311 12:32:37.299228   46881 exec_runner.go:51] Run: sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
I0311 12:32:37.304589   46881 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0311 12:32:37.643147   46881 exec_runner.go:51] Run: sudo systemctl restart containerd
I0311 12:32:37.694760   46881 start.go:483] detecting cgroup driver to use...
I0311 12:32:37.694786   46881 detect.go:199] detected "systemd" cgroup driver on host os
I0311 12:32:37.694902   46881 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0311 12:32:37.707415   46881 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0311 12:32:38.072386   46881 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0311 12:32:38.436097   46881 docker.go:529] configuring docker to use "systemd" as cgroup driver...
I0311 12:32:38.436116   46881 exec_runner.go:144] found /etc/docker/daemon.json, removing ...
I0311 12:32:38.436121   46881 exec_runner.go:207] rm: /etc/docker/daemon.json
I0311 12:32:38.436167   46881 exec_runner.go:151] cp: memory --> /etc/docker/daemon.json (143 bytes)
I0311 12:32:38.436258   46881 exec_runner.go:51] Run: sudo cp -a /tmp/minikube1692790957 /etc/docker/daemon.json
I0311 12:32:38.442258   46881 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0311 12:32:38.788471   46881 exec_runner.go:51] Run: sudo systemctl restart docker
I0311 12:32:39.638210   46881 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0311 12:32:39.958011   46881 exec_runner.go:51] Run: sudo systemctl unmask cri-docker.socket
I0311 12:32:40.324298   46881 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0311 12:32:40.678948   46881 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0311 12:32:41.020532   46881 exec_runner.go:51] Run: sudo systemctl restart cri-docker.socket
I0311 12:32:41.030470   46881 start.go:530] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0311 12:32:41.030495   46881 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0311 12:32:41.031269   46881 start.go:551] Will wait 60s for crictl version
I0311 12:32:41.031288   46881 exec_runner.go:51] Run: which crictl
I0311 12:32:41.031775   46881 exec_runner.go:51] Run: sudo /usr/local/bin/crictl version
I0311 12:32:43.055317   46881 exec_runner.go:84] Completed: sudo /usr/local/bin/crictl version: (2.02349702s)
I0311 12:32:43.055401   46881 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
time="2023-03-11T12:32:43+05:30" level=fatal msg="unable to determine runtime API version: rpc error: code = DeadlineExceeded desc = context deadline exceeded"
I0311 12:32:54.103883   46881 exec_runner.go:51] Run: sudo /usr/local/bin/crictl version
I0311 12:32:54.128824   46881 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
time="2023-03-11T12:32:54+05:30" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""
I0311 12:33:15.737570   46881 exec_runner.go:51] Run: sudo /usr/local/bin/crictl version
I0311 12:33:15.765347   46881 out.go:177] 
W0311 12:33:15.766045   46881 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
time="2023-03-11T12:33:15+05:30" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

W0311 12:33:15.766059   46881 out.go:239] 
W0311 12:33:15.766872   46881 out.go:239] [31m╭───────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                             [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0311 12:33:15.767655   46881 out.go:177] 

* 

### Operating System

Ubuntu

### Driver

KVM2

**Comment by afbjorklund** [comment]
Check that docker (including cri-dockerd) has been installed correctly, and that `crictl version` works OK

**Comment by rragul** [comment]
> Check that docker (including cri-dockerd) has been installed correctly, and that `crictl version` works OK ?
> 
> Sometimes this is caused by not using the packages, but something like `cp -a` to install the systemd units

crictl version
FATA[0000] unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused"
