### ISSUE TITLE
Minikube failed to start with Oracle Virtual Machine in Mac Os Ventura 13+

### ISSUE THREAD

**Issue by subhankar-banerjee** [kubernetes/minikube#16026]
### What Happened?

while run to start minikube from console getting below error ---

-- minikube start --driver=virtualbox
-- Oracle VM : 6.1 & 7.0
-- Minikube : 1.29.0

tried couple of times uninstall then install but didn't help...

### Attach the log file

😄  minikube v1.29.0 on Darwin 13.2.1
✨  Using the virtualbox driver based on user configuration
❗  Due to changes in macOS 13+ minikube doesn't currently support VirtualBox. You can use alternative drivers such as docker or hyperkit.
    https://minikube.sigs.k8s.io/docs/drivers/docker/
    https://minikube.sigs.k8s.io/docs/drivers/hyperkit/

    For more details on the issue see: https://github.com/kubernetes/minikube/issues/15274

💿  Downloading VM boot image ...
    > minikube-v1.29.0-amd64.iso....:  65 B / 65 B [---------] 100.00% ? p/s 0s
    > minikube-v1.29.0-amd64.iso:  276.35 MiB / 276.35 MiB  100.00% 4.95 MiB p/
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.26.1 preload ...
    > preloaded-images-k8s-v18-v1...:  397.05 MiB / 397.05 MiB  100.00% 4.93 Mi
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

❌  Exiting due to IF_VBOX_NOT_VISIBLE: Failed to start host: creating host: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
💡  Suggestion: Reboot to complete VirtualBox installation, verify that VirtualBox is not blocked by your system, and/or use another hypervisor
📘  Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by subhankar-banerjee** [comment]
can someone help on this issue

**Comment by afbjorklund** [comment]
It is missing support from upstream, use another driver

* https://github.com/kubernetes/minikube/issues/15274

**Comment by subhankar-banerjee** [comment]
is that Oracle Virtual Machine now stop working for K8s multi node cluster also  ?

**Comment by ged-flod** [comment]
If you are in macOS 13+ VirtualBox will not work so you can use docker instead.

### Overview

The Docker driver allows you to install Kubernetes into an existing Docker install.

### Usage

1. Delete the existing  "minikube" in VirtualBox:

```
minikube delete
```

2. Start a cluster using the docker driver:

```
minikube start --driver=docker
```

3. To make docker the default driver:

```
minikube config set driver docker
```
