### ISSUE TITLE
Minikube error

### ISSUE THREAD

**Issue by Parsu1508** [kubernetes/minikube#16030]
### What Happened?

* minikube v1.29.0 on Ubuntu 22.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 22.04.1 LTS

X Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

### Attach the log file

* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   |                  | minikube | root | v1.29.0 | 11 Mar 23 17:04 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 11 Mar 23 17:05 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 11 Mar 23 17:07 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 11 Mar 23 17:08 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 11 Mar 23 17:19 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 11 Mar 23 17:19 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.29.0 | 11 Mar 23 17:20 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2023/03/11 17:20:55
Running on machine: ip-172-31-12-224
Binary: Built with gc go1.19.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0311 17:20:55.828298   10035 out.go:296] Setting OutFile to fd 1 ...
I0311 17:20:55.828540   10035 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0311 17:20:55.828545   10035 out.go:309] Setting ErrFile to fd 2...
I0311 17:20:55.828551   10035 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0311 17:20:55.828682   10035 root.go:334] Updating PATH: /root/.minikube/bin
W0311 17:20:55.828803   10035 root.go:311] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0311 17:20:55.829004   10035 out.go:303] Setting JSON to false
I0311 17:20:55.829838   10035 start.go:125] hostinfo: {"hostname":"ip-172-31-12-224","uptime":1409,"bootTime":1678553846,"procs":115,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.0-1028-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec21c40d-c1a3-95a7-d08d-dade49f8a559"}
I0311 17:20:55.829900   10035 start.go:135] virtualization: xen guest
I0311 17:20:55.833154   10035 out.go:177] * minikube v1.29.0 on Ubuntu 22.04 (xen/amd64)
W0311 17:20:55.835698   10035 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0311 17:20:55.835815   10035 notify.go:220] Checking for updates...
I0311 17:20:55.836153   10035 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.26.1
I0311 17:20:55.836457   10035 exec_runner.go:51] Run: systemctl --version
I0311 17:20:55.838776   10035 driver.go:365] Setting default libvirt URI to qemu:///system
I0311 17:20:55.841142   10035 out.go:177] * Using the none driver based on existing profile
I0311 17:20:55.842814   10035 start.go:296] selected driver: none
I0311 17:20:55.842829   10035 start.go:857] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.12.224 Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Wor@@@

### Operating System

Ubuntu

### Driver

None

**Comment by afbjorklund** [comment]
Was the docker installation successful ? (including CRI and CNI)

https://minikube.sigs.k8s.io/docs/drivers/none/
