### ISSUE TITLE
"minikube image build" doesn't respect registry-creds

### ISSUE THREAD

**Issue by holograph** [kubernetes/minikube#16033]
### What Happened?

The builds kicked off by the `minikube image build` don't respect the registry credentials input via the [registry-creds](https://minikube.sigs.k8s.io/docs/tutorials/configuring_creds_for_aws_ecr/) add-on recommended in the documentation. This can be a problem if e.g. the build is based off of a base image that's on a private registry.

In fact, unless I'm missing something, there doesn't seem to be any way to provide credentials without resorting to injecting them via `docker login` (either via `docker-env` or SSH), and no way to parameterize the build container (e.g. with imagePullSecrets)? I'd be happy to lend a hand in testing or even implementing this, but this is a brand new code base (to me) in an unfamiliar language, so not promising anything...

(all of this of applies to the Docker driver in both Windows and MacOS)

### Attach the log file

No relevant logs

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
Listing expectations on the `minikube image` "framework" is still a good contribution, without code.

**Comment by holograph** [comment]
This isn't actually relevant to push, but just kicking off a build with `FROM <some_private_registry>/base:latest` already won't work without the appropriate credentials ahead of time. 

I did originally intend to just load the image, but ran into a separate issue (#16032 as it happens), but since I ended up resorting to `minikube docker-env` followed by `docker login` anyway, it made me realize how silly it is to build locally and then tar-transfer-untar between two local Docker contexts. I therefore perceive `minikube image build` as sort of a short-hand for the above process, retaining container runtime semantics as appropriate, and without having to train people on switching between Docker contexts (very confusing for some, apparently, in my experience).

**Comment by holograph** [comment]
Having a local registry (as you say, the localhost:5000 hack) is an extra complication that is arguably even harder to explain to relative newcomers than `minikube docker-env`. As for your final comment, I'm not sure what you mean by "if files are on the VM", but then I am fairly new to this stack 🤷

**Comment by afbjorklund** [comment]
I meant the config files with the credentials

**Comment by afbjorklund** [comment]
It would be nice if this could be done in an agnostic way, currently I think most local tools (docker, podman, nerdctl) just fall back to reading `~/.docker` files directly

**Comment by afbjorklund** [comment]
@holograph : I _think_ that if you use `minikube image pull --remote`, it will use the local credentials ?

That is, crane will pull the image from the registry with the default credentials and save it in the cache.
Then it will be loaded from the cache (as a tarball), transferred to the node, and loaded in the runtime.

`remote.Image(ref, remote.WithAuthFromKeychain(authn.DefaultKeychain), remote.WithPlatform(p))`

----

* https://pkg.go.dev/github.com/google/go-containerregistry/pkg/v1/remote#section-readme

* `crane`: https://github.com/google/go-containerregistry/blob/main/cmd/crane/cmd/auth.go

**Comment by afbjorklund** [comment]
> but since I ended up resorting to `minikube docker-env` followed by `docker login` anyway, it made me realize how silly it is to build locally and then tar-transfer-untar between two local Docker contexts. I therefore perceive `minikube image build` as sort of a short-hand for the above process, retaining container runtime semantics as appropriate, and without having to train people on switching between Docker contexts (very confusing for some, apparently, in my experience).

This was the idea behind `minikube image`, indeed. You shouldn't need Docker, in order to use Kubernetes...

* https://github.com/kubernetes/minikube/issues/4868

But people are very set in their ways, so I think we will be stuck with the legacy `minikube docker-env` too. :pensive: 

* https://github.com/kubernetes/minikube/issues/15389

**Comment by holograph** [comment]
@afbjorklund Unfortunately `image pull --remote` won't help, since it's a base image in a `FROM` clause that requires the credentials. In other words I'll have to manually build the base image stack and run pull on all of them -- not really practical.

As for `docker-env`, I think it's a wonderful tool that I'm very happy to have when debugging, but as you say - it should not be required for (relatively) basic usage patterns. The `minikube image login` approach seems reasonable, although perhaps integrating with registry-creds (since it's built-in to minikube anyway) would be cleaner... in any case I'd be happy to help test this - might even do more, but I don't make promises I'm not convinced I can keep :-)

**Comment by afbjorklund** [comment]
The main problem with `minikube docker-env` is keeping it working, when we are no longer using Docker anywhere.

And since the legacy TCP API is no longer recommended or even supported, there's all the fun of SSH connections...
