### ISSUE TITLE
 Segmentation fault with minikube installed with homebrew

### ISSUE THREAD

**Issue by fuzzylogical** [kubernetes/minikube#16031]
### What Happened?

Either I'm going crazy or something is wrong somewhere
I have installed minikube with homebrew and it keeps segmentation faulting and saying its this error in dmesg

15543 (minikube): Uhuuh, elf segment at 0000000000400000 requested but the memory is mapped already

Did some googling and I stumbled upon this gem
https://stackoverflow.com/questions/51656713/cannot-load-custom-elf-executable-in-gdb
which was saying that there is an error in some code somewhere because of this
https://github.com/torvalds/linux/commit/a4ff8e8620d3f4f50ac4b41e8067b7d395056843

apparently the memory address 0000000000400000 was mapped to something else already and its double mapping that address which seems silly on a fresh install of minikube.

I've installed this with homebrew on debian 10 system

and installed ==> minikube: stable 1.29.0 (bottled), HEAD

anyone able to help me out here?

### Attach the log file

N/A
I can't even get logs to output. it's failing from the startup

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
Does the normal debian package work any better ? Possibly related to go compiler.

https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb

**Comment by fuzzylogical** [comment]
looks like the debian package worked better. Couldn't tell you why though
since the dependencies used were the same
~$ ldd /usr/bin/minikube
        linux-vdso.so.1 (0x00007ffec115e000)
        libc.so.6 => /home/linuxbrew/.linuxbrew/opt/glibc/lib/libc.so.6
(0x00007f12c5ce0000)
        libpthread.so.0 =>
/home/linuxbrew/.linuxbrew/opt/glibc/lib/libpthread.so.0
(0x00007f12c5cdb000)
        /lib64/ld-linux-x86-64.so.2 =>
/home/linuxbrew/.linuxbrew/Cellar/glibc/2.35_1/lib64/ld-linux-x86-64.so.2
(0x00007f12c5ef6000)
I'm still not using go compiler at all :/

**Comment by afbjorklund** [comment]
> I'm still not using go compiler at all :/

Minikube is written in the Go language.

**Comment by afbjorklund** [comment]
I don't think running homebrew on debian oldstable is something that is tested regularly.
It tends to be a mix between the latest/greatest (`brew`) and an older operating system....

From the above, something like a mismatch between the go compiler and the linux kernel.
It could probably be fixed somehow, but someone would have to look into reproducing it.

**Comment by fuzzylogical** [comment]
that is a little frustrating. is there a regularly updated debian repo I
can add to my sources.list so I can regularly update my install if needed?
I don't actually know where you got that deb file from

**Comment by afbjorklund** [comment]
Sadly, no.

* #3110
