### ISSUE TITLE
minikube start version error on M1

### ISSUE THREAD

**Issue by emarkou** [kubernetes/minikube#16099]
### Problem
I tried to install minikube on a M1 laptop (Macbook  M1 Pro, Ventura 13.2.1) with 1/ brew and 2/ directly through 
```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-arm64
sudo install minikube-darwin-arm64
```
Installation seemed successful in both cases but whenever I run `minikube start` I get the following error, although I have installed the arm64 version. 

```
 ~ minikube start
😄  minikube v1.29.0 on Darwin 13.2.1 (arm64)
    ▪ MINIKUBE_IP=╭──────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                          │
│    You are trying to run the amd64 binary on an M1 system.                                               │
│    Please consider running the darwin/arm64 binary instead.                                              │
│    Download at https://github.com/kubernetes/minikube/releases/download/v1.29.0/minikube-darwin-arm64    │
│                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────╯
XXX.XXX.XX.X 
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container
🐳  Preparing Kubernetes v1.26.1 on Docker 20.10.23 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
``` 
I tried to uninstall, reinstall etc and it doesn't work. 

### Debugging info 
```
➜  ~ minikube version
minikube version: v1.29.0
commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3
```

Machine: Macbook  M1 Pro, Ventura 13.2.1

### Attach the log file

-- /stdout --
** stderr ** 
Error: No such network: minikube

** /stderr **
I0320 17:12:23.839020   70785 cli_runner.go:164] Run: docker network inspect bridge --format "{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{range .IPAM.Config}}{{.Subnet}}{{end}}","Gateway": "{{range .IPAM.Config}}{{.Gateway}}{{end}}","MTU": {{if (index .Options "com.docker.network.driver.mtu")}}{{(index .Options "com.docker.network.driver.mtu")}}{{else}}0{{end}}, "ContainerIPs": [{{range $k,$v := .Containers }}"{{$v.IPv4Address}}",{{end}}]}"
I0320 17:12:23.891570   70785 network.go:206] using free private subnet XXX.XXX.XX.0/24: &{IP:XXX.XXX.XX.0 Netmask:255.255.255.0 Prefix:24 CIDR:XXX.XXX.XX.0/24 Gateway:XXX.XXX.XX.1 ClientMin:XXX.XXX.XX.2 ClientMax:XXX.XXX.XX.254 Broadcast:XXX.XXX.XX.255 IsPrivate:true Interface:{IfaceName: IfaceIPv4: IfaceMTU:0 IfaceMAC:} reservation:0x140001dbd40}
I0320 17:12:23.891601   70785 network_create.go:123] attempt to create docker network minikube XXX.XXX.XX.0/24 with gateway XXX.XXX.XX.1 and MTU of 1500 ...
I0320 17:12:23.891690   70785 cli_runner.go:164] Run: docker network create --driver=bridge --subnet=XXX.XXX.XX.0/24 --gateway=XXX.XXX.XX.1 -o --ip-masq -o --icc -o com.docker.network.driver.mtu=1500 --label=created_by.minikube.sigs.k8s.io=true --label=name.minikube.sigs.k8s.io=minikube minikube
I0320 17:12:23.983114   70785 network_create.go:107] docker network minikube XXX.XXX.XX.0/24 created
I0320 17:12:23.983189   70785 kic.go:117] calculated static IP "XXX.XXX.XX.2" for the "minikube" container
I0320 17:12:23.983316   70785 cli_runner.go:164] Run: docker ps -a --format {{.Names}}
I0320 17:12:24.030919   70785 cli_runner.go:164] Run: docker volume create minikube --label name.minikube.sigs.k8s.io=minikube --label created_by.minikube.sigs.k8s.io=true
I0320 17:12:24.077052   70785 oci.go:103] Successfully created a docker volume minikube
I0320 17:12:24.077184   70785 cli_runner.go:164] Run: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 -d /var/lib
I0320 17:12:24.467923   70785 oci.go:107] Successfully prepared a docker volume minikube
I0320 17:12:24.467968   70785 preload.go:132] Checking if preload exists for k8s version v1.26.1 and runtime docker
I0320 17:12:24.467987   70785 kic.go:190] Starting extracting preloaded images to volume ...
I0320 17:12:24.468259   70785 cli_runner.go:164] Run: docker run --rm --entrypoint /usr/bin/tar -v /Users/eleni/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.26.1-docker-overlay2-arm64.tar.lz4:/preloaded.tar:ro -v minikube:/extractDir gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 -I lz4 -xf /preloaded.tar -C /extractDir
I0320 17:12:29.184264   70785 cli_runner.go:217] Completed: docker run --rm --entrypoint /usr/bin/tar -v /Users/eleni/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.26.1-docker-overlay2-arm64.tar.lz4:/preloaded.tar:ro -v minikube:/extractDir gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 -I lz4 -xf /preloaded.tar -C /extractDir: (4.715888s)
I0320 17:12:29.184303   70785 kic.go:199] duration metric: took 4.716299 seconds to extract preloaded images to volume
I0320 17:12:29.184501   70785 cli_runner.go:164] Run: docker info --format "'{{json .SecurityOptions}}'"
I0320 17:12:29.319926   70785 cli_runner.go:164] Run: docker run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --network minikube --ip XXX.XXX.XX.2 --volume minikube:/var --security-opt apparmor=unconfined --memory=8100mb --memory-swap=8100mb --cpus=2 -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 --publish=127.0.0.1::32443 gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15
I0320 17:12:29.637278   70785 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Running}}
I0320 17:12:29.691722   70785 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0320 17:12:29.742819   70785 cli_runner.go:164] Run: docker exec minikube stat /var/lib/dpkg/alternatives/iptables
I0320 17:12:29.832905   70785 oci.go:144] the created container "minikube" has a running status.
I0320 17:12:29.832932   70785 kic.go:221] Creating ssh key for kic: /Users/eleni/.minikube/machines/minikube/id_rsa...
I0320 17:12:29.975508   70785 kic_runner.go:191] docker (temp): /Users/eleni/.minikube/machines/minikube/id_rsa.pub --> /home/docker/.ssh/authorized_keys (381 bytes)
I0320 17:12:30.066701   70785 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0320 17:12:30.119419   70785 kic_runner.go:93] Run: chown docker:docker /home/docker/.ssh/authorized_keys
I0320 17:12:30.119436   70785 kic_runner.go:114] Args: [docker exec --privileged minikube chown docker:docker /home/docker/.ssh/authorized_keys]
I0320 17:12:30.207167   70785 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0320 17:12:30.252722   70785 machine.go:88] provisioning docker machine ...
I0320 17:12:30.252764   70785 ubuntu.go:169] provisioning hostname "minikube"
I0320 17:12:30.252906   70785 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0320 17:12:30.300140   70785 main.go:141] libmachine: Using SSH client type: native
I0320 17:12:30.300311   70785 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0x1029f5d30] 0x1029f87d0 <nil>  [] 0s} 127.0.0.1 53233 <nil> <nil>}
I0320 17:12:30.300316   70785 main.go:141] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0320 17:12:30.431179   70785 main.go:141] libmachine: SSH cmd err, output: <nil>: minikube

I0320 17:12:30.431276   70785 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0320 17:12:30.479762   70785 main.go:141] libmachine: Using SSH client type: native
I0320 17:12:30.479931   70785 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0x1029f5d30] 0x1029f87d0 <nil>  [] 0s} 127.0.0.1 53233 <nil> <nil>}
I0320 17:12:30.479944   70785 main.go:141] libmachine: About to run SSH command:

		if ! grep -xq '.*\sminikube' /etc/hosts; then
			if grep -xq '127.0.1.1\s.*' /etc/hosts; then
				sudo sed -i 's/^127.0.1.1\s.*/127.0.1.1 minikube/g' /etc/hosts;
			else 
				echo '127.0.1.1 minikube' | sudo tee -a /etc/hosts; 
			fi
		fi
I0320 17:12:30.602987   70785 main.go:141] libmachine: SSH cmd err, output: <nil>: 
I0320 17:12:30.602997   70785 ubuntu.go:175] set auth options {CertDir:/Users/eleni/.minikube CaCertPath:/Users/eleni/.minikube/certs/ca.pem CaPrivateKeyPath:/Users/eleni/.minikube/certs/ca-key.pem CaCertRemotePath:/etc/docker/ca.pem ServerCertPath:/Users/eleni/.minikube/machines/server.pem ServerKeyPath:/Users/eleni/.minikube/machines/server-key.pem ClientKeyPath:/Users/eleni/.minikube/certs/key.pem ServerCertRemotePath:/etc/docker/server.pem ServerKeyRemotePath:/etc/docker/server-key.pem ClientCertPath:/Users/eleni/.minikube/certs/cert.pem ServerCertSANs:[] StorePath:/Users/eleni/.minikube}
I0320 17:12:30.603020   70785 ubuntu.go:177] setting up certificates
I0320 17:12:30.603041   70785 provision.go:83] configureAuth start
I0320 17:12:30.603135   70785 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0320 17:12:30.651520   70785 provision.go:138] copyHostCerts
I0320 17:12:30.651636   70785 exec_runner.go:151] cp: /Users/eleni/.minikube/certs/ca.pem --> /Users/eleni/.minikube/ca.pem (1094 bytes)
I0320 17:12:30.651846   70785 exec_runner.go:151] cp: /Users/eleni/.minikube/certs/cert.pem --> /Users/eleni/.minikube/cert.pem (1139 bytes)
I0320 17:12:30.651932   70785 exec_runner.go:151] cp: /Users/eleni/.minikube/certs/key.pem --> /Users/eleni/.minikube/key.pem (1675 bytes)
I0320 17:12:30.652028   70785 provision.go:112] generating server cert: /Users/eleni/.minikube/machines/server.pem ca-key=/Users/eleni/.minikube/certs/ca.pem private-key=/Users/eleni/.minikube/certs/ca-key.pem org=eleni.minikube san=[XXX.XXX.XX.2 127.0.0.1 localhost 127.0.0.1 minikube minikube]
I0320 17:12:30.725511   70785 provision.go:172] copyRemoteCerts
I0320 17:12:30.725608   70785 ssh_runner.go:195] Run: sudo mkdir -p /etc/docker /etc/docker /etc/docker
I0320 17:12:30.725663   70785 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0320 17:12:30.772347   70785 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:53233 SSHKeyPath:/Users/eleni/.minikube/machines/minikube/id_rsa Username:docker}
I0320 17:12:30.862000   70785 ssh_runner.go:362] scp /Users/eleni/.minikube/certs/ca.pem --> /etc/docker/ca.pem (1094 bytes)
I0320 17:12:30.881133   70785 ssh_runner.go:362] scp /Users/eleni/.minikube/machines/server.pem --> /etc/docker/server.pem (1216 bytes)
I0320 17:12:30.899873   70785 ssh_runner.go:362] scp /Users/eleni/.minikube/machines/server-key.pem --> /etc/docker/server-key.pem (1679 bytes)
I0320 17:12:30.917835   70785 provision.go:86] duration metric: configureAuth took 314.775708ms
I0320 17:12:30.917846   70785 ubuntu.go:193] setting minikube options for container-runtime
I0320 17:12:30.917997   70785 config.go:180] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.26.1
I0320 17:12:30.918054   70785 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0320 17:12:30.963944   70785 main.go:141] libmachine: Using SSH client type: native
I0320 17:12:30.964099   70785 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0x1029f5d30] 0x1029f87d0 <nil>  [] 0s} 127.0.0.1 53233 <nil> <nil>}
I0320 17:12:30.964102   70785 main.go:141] libmachine: About to run SSH command:
df --output=fstype / | tail -n 1
I0320 17:12:31.088518   70785 main.go:141] libmachine: SSH cmd err, output: <nil>: overlay

I0320 17:12:31.088528   70785 ubuntu.go:71] root file system type: overlay
I0320 17:12:31.088644   70785 provision.go:309] Updating docker unit: /lib/systemd/system/docker.service ...
I0320 17:12:31.088731   70785 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0320 17:12:31.137910   70785 main.go:141] libmachine: Using SSH client type: native
I0320 17:12:31.138084   70785 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0x1029f5d30] 0x1029f87d0 <nil>  [] 0s} 127.0.0.1 53233 <nil> <nil>}
I0320 17:12:31.138133   70785 main.go:141] libmachine: About to run SSH command:
sudo mkdir -p /lib/systemd/system && printf %!s(MISSING) "[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
BindsTo=containerd.service
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket
StartLimitBurst=3
StartLimitIntervalSec=60

### Operating System

macOS (Default)

### Driver

N/A

**Comment by 2044smile** [comment]
@emarkou I'm having a similar error, have you solved it?
