### ISSUE TITLE
Issue with certificates when starting minikube

### ISSUE THREAD

**Issue by axyut** [kubernetes/minikube#16115]
### What Happened?

I installed minikube on my machine, tried starting it, set my user to docker group as suggested byminikube, started it again, then it could not find certificates /var/lib/minikube/certs.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/11029074/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by kundan2707** [comment]
@axyut  can you share detail steps and versions ?

**Comment by axyut** [comment]
minikube version: v1.29.0
kubernetes version: 1.26
I'm not receiving any error as of now and not been able to reproduce it.
I deleted the minikube server and started again with new.
