### ISSUE TITLE
Not for this project: minikube Cloud lab examples

### ISSUE THREAD

**Issue by et020598** [kubernetes/minikube#16125]
### What Happened?

The minikube labs on the cloud, like Cisco d-cloud, allow their members to exercise.
pods, services, configure map, storage, various os macOS, Windows, Linux.
application example or template for developers developing applications for beginners, mid-class, and advanced-class engineers.

### Attach the log file

Not available.

### Operating System

Ubuntu

### Driver

N/A

**Comment by spowelljr** [comment]
Could you please elaborate or provide a link to what you're talking about. As far as I'm aware we don't host or manage any minikube labs.

**Comment by et020598** [comment]
No, I could not demonstrate it.

I am a beginner to study minikube. That’s all.

I am trying build minikube in local.

Thanks for your reply.

 

 

Best Regards!

John Wu

**Comment by spowelljr** [comment]
I'm going to close this issue, but if you have any further questions feel free to post them.
