### ISSUE TITLE
Enable cgroup-v2 in minikube-iso image for qemu

### ISSUE THREAD

**Issue by koct9i** [kubernetes/minikube#16147]
Maybe it is a good time to use cgroup-v2 by default.

For now systemd option "systemd.legacy_systemd_cgroup_controller=yes" is hardcoded in kernel command line in isolinux.cfg

https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/board/minikube/x86_64/isolinux.cfg

**Comment by afbjorklund** [comment]
It would be a good idea, as part of the OS upgrade
