### ISSUE TITLE
Failed to start a minikube cluster on local machine

### ISSUE THREAD

**Issue by longqua69** [kubernetes/minikube#16155]
### What Happened?

I tried starting a minikube cluster on my local machine which uses WSL2 Ubuntu but got errors.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/11069283/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by kundan2707** [comment]
@longqua69  Can you provide detail steps and version of different components  you used?

**Comment by kundan2707** [comment]
@longqua69 can you check following:
please go to /etc/containerd/config.toml
change disabled_plugin to enabled_plugin

**Comment by longqua69** [comment]
@kundan2707 , I don't have such directory in my linux machine. Is there any more steps?
