### ISSUE TITLE
minikube addons enable ingress issue

### ISSUE THREAD

**Issue by jayadeep3** [kubernetes/minikube#16162]
### What Happened?

ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
  - Using image registry.k8s.io/ingress-nginx/controller:v1.5.1
  - Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
  - Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
* Verifying ingress addon...

X Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
* 
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    * Please also attach the following file to the GitHub issue:                             │
│    * - /tmp/minikube_addons_c872c5a7ad862af3917dc5fde85d6660878026a8_0.log 

### Attach the log file

/tmp/minikube_addons_c872c5a7ad862af3917dc5fde85d6660878026a8_0.log

### Operating System

Ubuntu

### Driver

None

**Comment by kundan2707** [comment]
@jayadeep3  have you installed minikube successfully?

**Comment by jayadeep3** [comment]
Not successfully installed

**Comment by kundan2707** [comment]
@jayadeep3  first try minikube installation with steps mentions in official documentation then try to enable ingress.

**Comment by jayadeep3** [comment]
It's ok @kundan2707 I will try and get back to you

**Comment by AggRag** [comment]
Hi, I am using an older version of minikube which is pulling ingress add on image from **k8s.gcr.io**, which has been already frozen by the Kubernetes community. Please suggest what changes should I do to my minikube cluster to avoid any future impacts because of this.
