### ISSUE TITLE
Minikube and Ingress on macOS arm64

### ISSUE THREAD

**Issue by UWEMAKAN** [kubernetes/minikube#16166]
### What Happened?

Setting up minikube and trying to enable ingress, I got the following errors.

minikube start --driver qemu --network socket_vmnet --cpus 4 --memory 8000
minikube addons enable ingress

### Attach the log file

💡  ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
    ▪ Using image registry.k8s.io/ingress-nginx/controller:v1.5.1
    ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
    ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
🔎  Verifying ingress addon...

❌  Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                         │
│    😿  If the above advice does not help, please let us know:                                                           │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                         │
│                                                                                                                         │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                  │
│    Please also attach the following file to the GitHub issue:                                                           │
│    - /var/folders/w9/fw1mjt2x1_s_hqy2gjdsh1bw0000gn/T/minikube_addons_41c645b2255e562f0e0feeb9e2a7f83c6ce0f8a5_0.log    │
│                                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

Log file created at: 2023/03/27 10:06:13
Running on machine: Uwems-MBP
Binary: Built with gc go1.19.5 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0327 10:06:13.514069   20758 out.go:296] Setting OutFile to fd 1 ...
I0327 10:06:13.514668   20758 out.go:348] isatty.IsTerminal(1) = true
I0327 10:06:13.514670   20758 out.go:309] Setting ErrFile to fd 2...
I0327 10:06:13.514675   20758 out.go:348] isatty.IsTerminal(2) = true
I0327 10:06:13.514773   20758 root.go:334] Updating PATH: /Users/username/.minikube/bin
W0327 10:06:13.515059   20758 root.go:311] Error reading config file at /Users/username/.minikube/config/config.json: open /Users/username/.minikube/config/config.json: no such file or directory
I0327 10:06:13.534831   20758 out.go:177] 💡  ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
I0327 10:06:13.554738   20758 config.go:180] Loaded profile config "minikube": Driver=qemu2, ContainerRuntime=docker, KubernetesVersion=v1.26.1
I0327 10:06:13.555017   20758 addons.go:65] Setting ingress=true in profile "minikube"
I0327 10:06:13.555033   20758 addons.go:227] Setting addon ingress=true in "minikube"
I0327 10:06:13.555551   20758 host.go:66] Checking if "minikube" exists ...
I0327 10:06:13.575992   20758 out.go:177]     ▪ Using image registry.k8s.io/ingress-nginx/controller:v1.5.1
I0327 10:06:13.594878   20758 out.go:177]     ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
I0327 10:06:13.613970   20758 out.go:177]     ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
I0327 10:06:13.632213   20758 addons.go:419] installing /etc/kubernetes/addons/ingress-deploy.yaml
I0327 10:06:13.632445   20758 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/ingress-deploy.yaml (16105 bytes)
I0327 10:06:13.632478   20758 sshutil.go:53] new ssh client: &{IP:192.168.105.11 Port:22 SSHKeyPath:/Users/username/.minikube/machines/minikube/id_rsa Username:docker}
I0327 10:06:13.671535   20758 ssh_runner.go:195] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.26.1/kubectl apply -f /etc/kubernetes/addons/ingress-deploy.yaml
I0327 10:06:13.940051   20758 addons.go:457] Verifying addon ingress=true in "minikube"
I0327 10:06:13.974990   20758 out.go:177] 🔎  Verifying ingress addon...
I0327 10:06:14.015329   20758 kapi.go:75] Waiting for pod with label "app.kubernetes.io/name=ingress-nginx" in ns "ingress-nginx" ...
I0327 10:06:14.023841   20758 kapi.go:86] Found 3 Pods for label selector app.kubernetes.io/name=ingress-nginx
I0327 10:06:14.023845   20758 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0327 10:12:14.002991   20758 kapi.go:107] duration metric: took 6m0.021355792s to wait for app.kubernetes.io/name=ingress-nginx ...
I0327 10:12:14.024090   20758 out.go:177] 
W0327 10:12:14.043950   20758 out.go:239] ❌  Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
W0327 10:12:14.043968   20758 out.go:239] 
W0327 10:12:14.047567   20758 out.go:239] [31m╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                                         [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                                                           [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                         [31m│[0m
[31m│[0m                                                                                                                         [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                  [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                                                           [31m│[0m
[31m│[0m    - /var/folders/w9/fw1mjt2x1_s_hqy2gjdsh1bw0000gn/T/minikube_addons_41c645b2255e562f0e0feeb9e2a7f83c6ce0f8a5_0.log    [31m│[0m
[31m│[0m                                                                                                                         [31m│[0m
[31m╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0327 10:12:14.066011   20758 out.go:177] 

Upon inspection of problems.log file, I find this log and I don't quite know how to resolve this.

* 
X Problems detected in kubelet:
  Mar 27 09:06:14 minikube kubelet[2097]: W0327 09:06:14.092350    2097 reflector.go:424] object-"ingress-nginx"/"ingress-nginx-admission": failed to list *v1.Secret: secrets "ingress-nginx-admission" is forbidden: User "system:node:minikube" cannot list resource "secrets" in API group "" in the namespace "ingress-nginx": no relationship found between node 'minikube' and this object
  Mar 27 09:06:14 minikube kubelet[2097]: E0327 09:06:14.092390    2097 reflector.go:140] object-"ingress-nginx"/"ingress-nginx-admission": Failed to watch *v1.Secret: failed to list *v1.Secret: secrets "ingress-nginx-admission" is forbidden: User "system:node:minikube" cannot list resource "secrets" in API group "" in the namespace "ingress-nginx": no relationship found between node 'minikube' and this object

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by kundan2707** [comment]
@UWEMAKAN  can you check minikube installation first?
check minikube status after installation. If all OK then enable ingress

**Comment by UWEMAKAN** [comment]
> @UWEMAKAN can you check minikube installation first? check minikube status after installation. If all OK then enable ingress

The installation is fine. I have been able to create deployments, services, config maps, secrets, etc. This issue starts when I try to enable ingress.

**Comment by kundan2707** [comment]
@UWEMAKAN  what is version of minikube for installation?

**Comment by UWEMAKAN** [comment]
@kundan2707  minikube version: v1.29.0
