### ISSUE TITLE
stderr: The IngressClass "nginx" is invalid: spec.controller: Invalid value: "k8s.io/ingress-nginx": field is immutable  waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

### ISSUE THREAD

**Issue by sharanabasavarajak** [kubernetes/minikube#16169]
### What Happened?

stderr:
The IngressClass "nginx" is invalid: spec.controller: Invalid value: "k8s.io/ingress-nginx": field is immutable
 waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

### Attach the log file

stderr:
The IngressClass "nginx" is invalid: spec.controller: Invalid value: "k8s.io/ingress-nginx": field is immutable
 waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

### Operating System

None

### Driver

None

**Comment by joachimbulow** [comment]
Did you resolve this issue?
