### ISSUE TITLE
Creating Services. curl timed out when doing curl http://$(minikube ip):32000

### ISSUE THREAD

**Issue by 1dropaflame** [kubernetes/minikube#16188]
### What Happened?

(WSL2, minikube 1.29, Windows 11, Calico plugin, Docker-Desktop 4.17 which uses Kubernetes 1.25.4, Kubernetes 1.26.1) 

I am trying to learn k8s and following along on my laptop (instructions from a CKAD demo by Sander Van Vugt).

I simply don't understand why curl timed out when doing `curl http://$(minikube ip):32000`.

minikube was launched with the command:

`minikube start --driver=docker --cni=calico
`
    $ k create deploy nginxsvc --image=nginx --replicas=3
    $ k expose deploy nginxsvc --port=80

Then I edited the service to change Service Type to NodePort.

 ```
   $ k get svc
    NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
    kubernetes ClusterIP 10.96.0.1 <none> 443/TCP 18d
    nginxsvc NodePort 10.103.11.225 <none> 80:32000/TCP 19m
    regular-encourager NodePort 10.102.236.129 <none> 8080:32058/TCP 15d
    
    $ curl http://$(minikube ip):32000
    curl: (28) Failed to connect to 192.168.49.2 port 32000: Connection timed out
    
    $ k describe svc nginxsvc
    
    Name: nginxsvc
    
    Namespace: default
    
    Labels: app=nginxsvc
    
    Annotations: <none>
    
    Selector: app=nginxsvc
    
    Type: NodePort
    
    IP Family Policy: SingleStack
    
    IP Families: IPv4
    
    IP: 10.103.11.225
    
    IPs: 10.103.11.225
    
    Port: <unset> 80/TCP
    
    TargetPort: 80/TCP
    
    NodePort: <unset> 32000/TCP
    
    Endpoints: 10.244.1.233:80,10.244.1.234:80,10.244.1.235:80
    
    Session Affinity: None
    
    External Traffic Policy: Cluster
    
    Events: <none>
    
    $ k get svc nginxsvc -o yaml
    apiVersion: v1
    kind: Service
    metadata:
      creationTimestamp: "2023-03-28T23:18:04Z"
      labels:
        app: nginxsvc
      name: nginxsvc
      namespace: default
      resourceVersion: "531373"
      uid: fcd7960e-8610-4099-a014-9b4ce94cdec2
    spec:
      clusterIP: 10.103.11.225
      clusterIPs:
      - 10.103.11.225
      externalTrafficPolicy: Cluster
      internalTrafficPolicy: Cluster
      ipFamilies:
      - IPv4
      ipFamilyPolicy: SingleStack
      ports:
      - nodePort: 32000
        port: 80
        protocol: TCP
        targetPort: 80
      selector:
        app: nginxsvc
      sessionAffinity: None
      type: NodePort
    status:
      loadBalancer: {}
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11103906/log.txt)

### Operating System

Windows

### Driver

Docker

**Comment by afbjorklund** [comment]
The minikube IP is not directly reachable, when using the Docker Desktop driver which has limited network capability.

Use `minikube tunnel`, as in docs

**Comment by 1dropaflame** [comment]
@afbjorklund I see "Running minikube on Linux with the Docker driver will result in no tunnel being created" over here https://minikube.sigs.k8s.io/docs/handbook/accessing/#using-minikube-service-with-tunnel
So is there no way to get it running?

**Comment by 1dropaflame** [comment]
@spowelljr 

I saw your reply in another issue which was closed.
I do have Docker Desktop and WSL2 running on Windows 11. Since I was unable to run any Network/Services/Ingress demos, I purged minikube from WSL.
Then I Installed VirtualBox 7 and then Ubuntu 22.04 inside it, and also minikube. 
But I get this error. I do not understand what to do since I already have virtual box installed:

```
dropaflame@1dropaflame:~$ minikube start --memory=6g --cpus=4 --vm-driver=docker --cni=calico

😄  minikube v1.29.0 on Ubuntu 22.04 (vbox/amd64)

❗  Both driver=virtualbox and vm-driver=docker have been set.
    Since vm-driver is deprecated, minikube will default to driver=virtualbox.
    If vm-driver is set in the global config, please run "minikube config unset vm-driver" to resolve this warning.
✨  Using the virtualbox driver based on user configuration
🤷  Exiting due to PROVIDER_VIRTUALBOX_NOT_FOUND: The 'virtualbox' provider was not found: unable to find VBoxManage in $PATH
💡  Suggestion: Install VirtualBox
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/
```

**Comment by 1dropaflame** [comment]
It works now.
Installed minikube 1.29 on virtualbox 7.7.

started minikube like this:

`minikube start --memory=4g --cpus=4 --driver=docker --cni=calico
`
Now the ingress demos work.
