### ISSUE TITLE
minikube start --vm-driver=virtualbox is not working on Mac OS Sierra

### ISSUE THREAD

**Issue by adityardesai** [kubernetes/minikube#1618]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
minikube version: v0.19.1

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac OS Sierra 10.12.5
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):"DriverName": "virtualbox"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): "Boot2DockerURL": "file:///Users/addesai/.minikube/cache/iso/minikube-v0.18.0.iso"
- **Install tools**:
- **Others**:

**What happened**:
When I run the command minikube start --vm-driver=virtualbox, I see the following error

```
Error setting up kubeconfig:  could not write to '/Users/adityardesai/.kube/config': failed to encode config: converting  to : type names don't match (Unknown, RawExtension), and no conversion 'func (runtime.Unknown, runtime.RawExtension) error' registered.
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
```

**What you expected to happen**:
I expect the kubernetes to start working without this error. 

**How to reproduce it** (as minimally and precisely as possible):
Start installing kubernetes from scratch on Mac OS and try to start it

**Anything else do we need to know**:

**Comment by darkowlzz** [comment]
@adityardesai is this still happening with minikube version: v0.20.0 ?
I am not able to reproduce it.

**Comment by hotcoder** [comment]
$ minikube start
Starting local Kubernetes v1.7.5 cluster...
Starting VM...


after this nothing is coming

**Comment by ColdHeat** [comment]
I have a similar issue. 

I deleted ~/.minikube and redownloaded the ISO but still seems stuck.

```
❯ minikube start --vm-driver=vmwarefusion
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Downloading Minikube ISO
 140.01 MB / 140.01 MB [============================================] 100.00% 0s
```

I do not see a VM in the Fusion library either.

**Comment by ColdHeat** [comment]
For me the issue was Fusion was being blocked from loading. 

https://superuser.com/questions/1256489/how-to-fix-vmware-fusion-pro-10-cannot-find-a-valid-peer-process-to-connect-to

**Comment by blind3dd** [comment]
I solved it, answered to the post out here:
https://superuser.com/questions/1295452/how-to-run-docker-in-virtualbox-mac-os-sierra/1317221#1317221

This is how you solve it:
basically kext disable, then firewall privacy and allow from anywhere click button in system preferences firewall, then VirtualBox reinstall process (update/reinstall, if fails don't worry), then 
unload and load Virtualbox plugins from "/Library/Application Support/VirtualBox" folder, (having selected allow from anywhere from kext step you'll be able to allow again, but this time from Oracle America during loading these plugins from VirtualBox folder.

Now,
minikube start --vm-driver=virtualbox

**Comment by chorwitt** [comment]
I found that simply running "rm -rf $HOME/.minikube" and then running "minikube start --vm-driver=virtualbox" fixed minikube not running for me.

**Comment by zgramana** [comment]
I had this issue on macOS 10.14 (Mojave) and resolved it by running the following commands:
```sh
rm -Rf ~/.minikube
brew install docker-machine-driver-hyperkit
sudo chown root:wheel /usr/local/opt/docker-machine-driver-hyperkit/bin/docker-machine-driver-hyperkit
sudo chmod u+s /usr/local/opt/docker-machine-driver-hyperkit/bin/docker-machine-driver-hyperkit
minikube start --vm-driver=hyperkit
```

**Comment by tstromberg** [comment]
If you do run into this - look at `~/.kube/config`, because something in there is corrupt, or at least not parseable by minikube.

If you want to be destructive:

`rm ~/.kube/config && minikube delete`

**Comment by zgramana** [comment]
I did quite a bit of digging, and it boiled down to Start never actually started and eventually found an error at `-v9` saying the OS could not be identified. AFAICT `.kube/config` looked normal, but that was just by eyeball so I could easily have missed something small (or invisible chars).
