### ISSUE TITLE
issue while starting the minikube

### ISSUE THREAD

**Issue by sasigowda** [kubernetes/minikube#16182]
### What Happened?

issue while starting the minikube

### Attach the log file

*
* ==> Audit <==
* |---------|-------------------|----------|------|---------|---------------------|---------------------|
| Command |       Args        | Profile  | User | Version |     Start Time      |      End Time       |
|---------|-------------------|----------|------|---------|---------------------|---------------------|
| start   | --force           | minikube | root | v1.29.0 | 29 Mar 23 05:14 UTC | 29 Mar 23 05:16 UTC |
| service | webapp-port --url | minikube | root | v1.29.0 | 29 Mar 23 05:31 UTC | 29 Mar 23 05:31 UTC |
| delete  |                   | minikube | root | v1.29.0 | 29 Mar 23 05:43 UTC | 29 Mar 23 05:43 UTC |
| start   | --driver=none     | minikube | root | v1.29.0 | 29 Mar 23 05:45 UTC |                     |
| start   | --driver=none     | minikube | root | v1.29.0 | 29 Mar 23 05:45 UTC |                     |
| start   | --driver=none     | minikube | root | v1.29.0 | 29 Mar 23 05:50 UTC |                     |
|---------|-------------------|----------|------|---------|---------------------|---------------------|

*
* ==> Last Start <==
* Log file created at: 2023/03/29 05:50:53
Running on machine: ip-172-31-17-33
Binary: Built with gc go1.19.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0329 05:50:53.623281   35703 out.go:296] Setting OutFile to fd 1 ...
I0329 05:50:53.623414   35703 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0329 05:50:53.623419   35703 out.go:309] Setting ErrFile to fd 2...
I0329 05:50:53.623425   35703 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0329 05:50:53.623533   35703 root.go:334] Updating PATH: /root/.minikube/bin
I0329 05:50:53.624502   35703 out.go:303] Setting JSON to false
I0329 05:50:53.625209   35703 start.go:125] hostinfo: {"hostname":"ip-172-31-17-33","uptime":2985,"bootTime":1680066068,"procs":115,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.0-1031-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec2fbb0d-1062-8848-80a3-77bfe7085651"}
I0329 05:50:53.625273   35703 start.go:135] virtualization: xen guest
I0329 05:50:53.628361   35703 out.go:177] * minikube v1.29.0 on Ubuntu 22.04 (xen/amd64)
I0329 05:50:53.631283   35703 notify.go:220] Checking for updates...
I0329 05:50:53.632065   35703 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.26.1
I0329 05:50:53.632928   35703 exec_runner.go:51] Run: systemctl --version
I0329 05:50:53.634965   35703 driver.go:365] Setting default libvirt URI to qemu:///system
I0329 05:50:53.637689   35703 out.go:177] * Using the none driver based on existing profile
I0329 05:50:53.639897   35703 start.go:296] selected driver: none
I0329 05:50:53.639909   35703 start.go:857] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0329 05:50:53.639997   35703 start.go:868] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0329 05:50:53.640017   35703 start.go:1617] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0329 05:50:53.640504   35703 cni.go:84] Creating CNI manager for ""
I0329 05:50:53.640517   35703 cni.go:157] "none" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
I0329 05:50:53.640527   35703 start_flags.go:319] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0329 05:50:53.644537   35703 out.go:177] * Starting control plane node minikube in cluster minikube
I0329 05:50:53.647027   35703 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0329 05:50:53.647239   35703 cache.go:193] Successfully downloaded all kic artifacts
I0329 05:50:53.647265   35703 start.go:364] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0329 05:50:53.647355   35703 start.go:368] acquired machines lock for "minikube" in 65.473µs
I0329 05:50:53.647374   35703 start.go:96] Skipping create...Using existing machine configuration
I0329 05:50:53.647381   35703 fix.go:55] fixHost starting: m01
W0329 05:50:53.648516   35703 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0329 05:50:53.648527   35703 api_server.go:165] Checking apiserver status ...
I0329 05:50:53.648557   35703 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0329 05:50:53.672835   35703 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0329 05:50:53.672884   35703 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0329 05:50:53.685417   35703 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0329 05:50:53.685432   35703 fix.go:129] unexpected machine state, will restart: <nil>
I0329 05:50:53.688197   35703 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I0329 05:50:53.691379   35703 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0329 05:50:53.691523   35703 start.go:300] post-start starting for "minikube" (driver="none")
I0329 05:50:53.691573   35703 start.go:328] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0329 05:50:53.691603   35703 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0329 05:50:53.704636   35703 main.go:141] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0329 05:50:53.704664   35703 main.go:141] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0329 05:50:53.704676   35703 main.go:141] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0329 05:50:53.708500   35703 out.go:177] * OS release is Ubuntu 22.04.2 LTS
I0329 05:50:53.710921   35703 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0329 05:50:53.710968   35703 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0329 05:50:53.710992   35703 start.go:303] post-start completed in 19.459679ms
I0329 05:50:53.711000   35703 fix.go:57] fixHost completed within 63.620238ms
I0329 05:50:53.711006   35703 start.go:83] releasing machines lock for "minikube", held for 63.642751ms
I0329 05:50:53.711377   35703 exec_runner.go:51] Run: cat /version.json
I0329 05:50:53.711504   35703 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
W0329 05:50:53.712563   35703 start.go:396] Unable to open version.json: cat /version.json: exit status 1
stdout:

stderr:
cat: /version.json: No such file or directory
I0329 05:50:53.712617   35703 exec_runner.go:51] Run: sh -c "stat /etc/cni/net.d/*loopback.conf*"
W0329 05:50:53.716034   35703 cni.go:208] loopback cni configuration skipped: "/etc/cni/net.d/*loopback.conf*" not found
I0329 05:50:53.716121   35703 exec_runner.go:51] Run: sudo mkdir -p /etc/systemd/system/cri-docker.service.d
I0329 05:50:53.726636   35703 exec_runner.go:151] cp: memory --> /etc/systemd/system/cri-docker.service.d/10-cni.conf (135 bytes)
I0329 05:50:53.726751   35703 exec_runner.go:51] Run: sudo cp -a /tmp/minikube1284274455 /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0329 05:50:53.735847   35703 exec_runner.go:51] Run: sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%!p(MISSING), " -exec sh -c "sudo mv {} {}.mk_disabled" ;
E0329 05:50:53.749558   35703 start.go:415] unable to disable preinstalled bridge CNI(s): failed to disable all bridge cni configs in "/etc/cni/net.d": sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%!p(MISSING), " -exec sh -c "sudo mv {} {}.mk_disabled" ;: exit status 1
stdout:

stderr:
find: ‘/etc/cni/net.d’: No such file or directory
I0329 05:50:53.749583   35703 start.go:483] detecting cgroup driver to use...
I0329 05:50:53.749605   35703 detect.go:199] detected "systemd" cgroup driver on host os
I0329 05:50:53.749713   35703 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0329 05:50:53.804853   35703 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml"
I0329 05:50:53.821014   35703 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)restrict_oom_score_adj = .*$|\1restrict_oom_score_adj = false|' /etc/containerd/config.toml"
I0329 05:50:53.835376   35703 containerd.go:145] configuring containerd to use "systemd" as cgroup driver...
I0329 05:50:53.835438   35703 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)SystemdCgroup = .*$|\1SystemdCgroup = true|g' /etc/containerd/config.toml"
I0329 05:50:53.847479   35703 exec_runner.go:51] Run: sh -c "sudo sed -i 's|"io.containerd.runtime.v1.linux"|"io.containerd.runc.v2"|g' /etc/containerd/config.toml"
I0329 05:50:53.859991   35703 exec_runner.go:51] Run: sh -c "sudo sed -i '/systemd_cgroup/d' /etc/containerd/config.toml"
I0329 05:50:53.870959   35703 exec_runner.go:51] Run: sh -c "sudo sed -i 's|"io.containerd.runc.v1"|"io.containerd.runc.v2"|g' /etc/containerd/config.toml"
I0329 05:50:53.880963   35703 exec_runner.go:51] Run: sh -c "sudo rm -rf /etc/cni/net.mk"
I0329 05:50:53.892564   35703 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)conf_dir = .*$|\1conf_dir = "/etc/cni/net.d"|g' /etc/containerd/config.toml"
I0329 05:50:53.902841   35703 exec_runner.go:51] Run: sudo sysctl net.bridge.bridge-nf-call-iptables
I0329 05:50:53.913554   35703 exec_runner.go:51] Run: sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
I0329 05:50:53.922738   35703 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0329 05:50:54.191059   35703 exec_runner.go:51] Run: sudo systemctl restart containerd
I0329 05:50:54.707442   35703 start.go:483] detecting cgroup driver to use...
I0329 05:50:54.707474   35703 detect.go:199] detected "systemd" cgroup driver on host os
I0329 05:50:54.707607   35703 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0329 05:50:54.730929   35703 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0329 05:50:54.994874   35703 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0329 05:50:55.234771   35703 docker.go:529] configuring docker to use "systemd" as cgroup driver...
I0329 05:50:55.234817   35703 exec_runner.go:151] cp: memory --> /etc/docker/daemon.json (143 bytes)
I0329 05:50:55.234945   35703 exec_runner.go:51] Run: sudo cp -a /tmp/minikube328598706 /etc/docker/daemon.json
I0329 05:50:55.245595   35703 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0329 05:50:55.503470   35703 exec_runner.go:51] Run: sudo systemctl restart docker
I0329 05:50:56.284551   35703 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0329 05:50:56.543136   35703 exec_runner.go:51] Run: sudo systemctl unmask cri-docker.socket
I0329 05:50:56.787137   35703 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0329 05:50:57.047121   35703 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0329 05:50:57.324770   35703 exec_runner.go:51] Run: sudo systemctl restart cri-docker.socket
I0329 05:50:57.348968   35703 start.go:530] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0329 05:50:57.349034   35703 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0329 05:50:57.350818   35703 start.go:551] Will wait 60s for crictl version
I0329 05:50:57.350845   35703 exec_runner.go:51] Run: which crictl
I0329 05:50:57.355174   35703 out.go:177]
W0329 05:50:57.358251   35703 out.go:239] X Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

W0329 05:50:57.358465   35703 out.go:239] *
W0329 05:50:57.359580   35703 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0329 05:50:57.362900   35703 out.go:177]

*

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Did you install crictl ?

https://minikube.sigs.k8s.io/docs/drivers/none/
