### ISSUE TITLE
Not able to start Minikube getting below error

### ISSUE THREAD

**Issue by sasan07** [kubernetes/minikube#16189]
### What Happened?

stderr:
find: ‘/etc/cni/net.d’: No such file or directory

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
E0329 17:46:16.255407   11784 remote_runtime.go:145] "Version from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""
time="2023-03-29T17:46:16Z" level=fatal msg="getting the runtime version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

### Attach the log file

[Logs.txt](https://github.com/kubernetes/minikube/files/11104007/Logs.txt)

### Operating System

Ubuntu

### Driver

None

**Comment by afbjorklund** [comment]
The `crictl version` must work, before minikube will work with the "none" driver.
Maybe check the status with `minikube ssh sudo systemctl status cri-docker`
