### ISSUE TITLE
Can't start minikube with docker driver on zfs

### ISSUE THREAD

**Issue by R-M-F-at-C-A** [kubernetes/minikube#16185]
### What Happened?

Similar to (unresolved) issue https://github.com/kubernetes/minikube/issues/10929

Running 
`minikube start` (or `minikube start --driver=docker`) gives

```
😄  minikube v1.29.0 on Ubuntu 22.04
    ▪ KUBECONFIG=[redacted]
✨  Using the docker driver based on user configuration
❗  docker is currently using the zfs storage driver, consider switching to overlay2 for better performance
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=11900MB) ...

❌  Exiting due to RUNTIME_ENABLE: sudo systemctl restart docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
```

Log.txt attached.

I've tried the suggestions at #10929:
```
docker system prune
minikube delete
minikube start --driver=docker
```
and
```
sudo systemctl unmask docker
sudo systemctl start docker
```

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/11099761/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by farnsworth** [comment]
Same problem here. Did you find any solution?
Only way I found to fix was to downgrade minikube to v1.27.0.

**Comment by JohSchillerEmnify** [comment]
Running into the same issue. I will try downgrading but in the long term there should be some solution to this. My logs look similar to yours. same errors with overlayfs

**Comment by Ed-Commodum** [comment]
I'm having the same issue, downgrading to 1.27.0 fixed the problem.

**Comment by software-engr-full-stack** [comment]
This may be related to the usage of docker and zfs as the underlying FS. It seems minikube doesn't work if docker is using zfs as the storage driver. You have to make docker use the overlay2 storage driver. To do that, see this https://blog.chlc.cc/p/docker-and-zfs-a-tough-pair/.

Basically: 1) stop the docker service, 2) create a zfs volume, 3) format that volume (btrfs type seems to work, if you're having issues, use ext4), 4) mount the zfs volume to /var/lib/docker or wherever your docker data is located, 5) start the docker service.

I was able to make this work with the latest version which is v1.31.0 at the time of this writing.
