### ISSUE TITLE
Minikube fails to start due to invalid certificate

### ISSUE THREAD

**Issue by leoneperdigao** [kubernetes/minikube#16183]
### What Happened?

I'm trying to execute a fresh installation of minikube with podman in my laptop. However, after installation, when I run `minikube start` it fails.

There is an issue with the clock in the minikube system. My current datetime is Wed Mar 29 11:38:10 CEST 2023 which is in the valid period of the certification, but it gets a wrong date "current time 2023-03-28T05:14:28Z".

### Attach the log file

```
stderr:
W0328 05:14:28.468066    2649 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/crio/crio.sock". Please update your configuration!
W0328 05:14:28.472391    2649 certs.go:521] WARNING: could not validate bounds for certificate CA: the certificate is not valid yet: NotBefore: 2023-03-28 09:32:39 +0000 UTC, NotAfter: 2033-03-26 09:32:39 +0000 UTC
	[WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
	[WARNING SystemVerification]: missing optional cgroups: hugetlb
	[WARNING SystemVerification]: missing required cgroups: cpuset
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
W0328 05:14:28.704674    2649 certs.go:521] WARNING: could not validate bounds for certificate ca: the certificate is not valid yet: NotBefore: 2023-03-28 09:32:39 +0000 UTC, NotAfter: 2033-03-26 09:32:39 +0000 UTC
W0328 05:14:28.704853    2649 certs.go:521] WARNING: could not validate bounds for certificate apiserver: the certificate is not valid yet: NotBefore: 2023-03-28 09:32:39 +0000 UTC, NotAfter: 2026-03-28 09:32:39 +0000 UTC
error execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: x509: certificate has expired or is not yet valid: current time 2023-03-28T05:14:28Z is before 2023-03-28T09:32:39Z
To see the stack trace of this error execute with --v=5 or higher
```

### Operating System

macOS (Default)

### Driver

Podman

**Comment by spowelljr** [comment]
What version of minikube are you using @leoneperdigao?

**Comment by leoneperdigao** [comment]
> What version of minikube are you using @leoneperdigao?

Latest, v1.24.3

**Comment by spowelljr** [comment]
I believe you're referencing the version of Kubernetes, not minikube, this is likely related to https://github.com/kubernetes/minikube/issues/16201. In the meantime, you can run `minikube delete --all --purge` which will delete all your minikube clusters and configs and then try starting minikube again and your issue should be rsolved.

**Comment by leoneperdigao** [comment]
I'm sorry, you are correct. I meant the version [v1.29.0](https://github.com/kubernetes/minikube/releases/tag/v1.29.0).

I already tried to delete all the configuration. Btw, this is a brand new installation and it failed in the first attempt to run.

**Comment by leoneperdigao** [comment]
I'm closing the issue since I didn't get help anyway.
