### ISSUE TITLE
 level=fatal msg="getting the runtime version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

### ISSUE THREAD

**Issue by Rajan251** [kubernetes/minikube#16198]
### What Happened?

stderr:
E0330 17:57:03.593552    6708 remote_runtime.go:145] "Version from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""
time="2023-03-30T17:57:03+05:30" level=fatal msg="getting the runtime version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

### Attach the log file

* 
* ==> Audit <==
* |----------------|------------------------|----------|------|---------|---------------------|---------------------|
|    Command     |          Args          | Profile  | User | Version |     Start Time      |      End Time       |
|----------------|------------------------|----------|------|---------|---------------------|---------------------|
| start          |                        | minikube | root | v1.29.0 | 30 Mar 23 15:27 IST |                     |
| start          |                        | minikube | root | v1.29.0 | 30 Mar 23 15:29 IST |                     |
| start          |                        | minikube | root | v1.29.0 | 30 Mar 23 15:37 IST |                     |
| start          | --alsologtostderr -v=4 | minikube | root | v1.29.0 | 30 Mar 23 15:38 IST |                     |
| service        | hello-minikube         | minikube | root | v1.29.0 | 30 Mar 23 16:33 IST |                     |
| stop           |                        | minikube | root | v1.29.0 | 30 Mar 23 16:34 IST |                     |
| delete         | --all                  | minikube | root | v1.29.0 | 30 Mar 23 16:34 IST | 30 Mar 23 16:34 IST |
| start          |                        | minikube | root | v1.29.0 | 30 Mar 23 16:35 IST |                     |
| config         | set driver none        | minikube | root | v1.29.0 | 30 Mar 23 16:36 IST | 30 Mar 23 16:36 IST |
| config         | set driver none        | minikube | root | v1.29.0 | 30 Mar 23 16:36 IST | 30 Mar 23 16:36 IST |
| start          |                        | minikube | root | v1.29.0 | 30 Mar 23 16:36 IST |                     |
| start          | --driver=none          | minikube | root | v1.29.0 | 30 Mar 23 17:56 IST |                     |
| update-context |                        | minikube | root | v1.29.0 | 30 Mar 23 17:57 IST |                     |
|----------------|------------------------|----------|------|---------|---------------------|---------------------|

* 
* ==> Last Start <==
* Log file created at: 2023/03/30 17:56:24
Running on machine: kali
Binary: Built with gc go1.19.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0330 17:56:24.438385    6079 out.go:296] Setting OutFile to fd 1 ...
I0330 17:56:24.438514    6079 out.go:348] isatty.IsTerminal(1) = true
I0330 17:56:24.438518    6079 out.go:309] Setting ErrFile to fd 2...
I0330 17:56:24.438524    6079 out.go:348] isatty.IsTerminal(2) = true
I0330 17:56:24.438629    6079 root.go:334] Updating PATH: /root/.minikube/bin
I0330 17:56:24.440193    6079 out.go:303] Setting JSON to false
I0330 17:56:24.450664    6079 start.go:125] hostinfo: {"hostname":"kali","uptime":1166,"bootTime":1680178019,"procs":264,"os":"linux","platform":"debian","platformFamily":"debian","platformVersion":"kali-rolling","kernelVersion":"6.1.0-kali5-amd64","kernelArch":"x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostId":"a2c28570-52b7-0000-0000-000000000000"}
I0330 17:56:24.450725    6079 start.go:135] virtualization: kvm host
I0330 17:56:24.451958    6079 out.go:177] 😄  minikube v1.29.0 on Debian kali-rolling
I0330 17:56:24.454661    6079 notify.go:220] Checking for updates...
W0330 17:56:24.454770    6079 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0330 17:56:24.455039    6079 config.go:180] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.26.1
I0330 17:56:24.456071    6079 exec_runner.go:51] Run: systemctl --version
I0330 17:56:24.461007    6079 driver.go:365] Setting default libvirt URI to qemu:///system
I0330 17:56:24.462125    6079 out.go:177] ✨  Using the none driver based on existing profile
I0330 17:56:24.462976    6079 start.go:296] selected driver: none
I0330 17:56:24.462986    6079 start.go:857] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.0.101 Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0330 17:56:24.463057    6079 start.go:868] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0330 17:56:24.463751    6079 cni.go:84] Creating CNI manager for ""
I0330 17:56:24.463760    6079 cni.go:157] "none" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
I0330 17:56:24.463767    6079 start_flags.go:319] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:192.168.0.101 Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0330 17:56:24.464878    6079 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0330 17:56:24.465811    6079 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0330 17:56:24.466551    6079 cache.go:193] Successfully downloaded all kic artifacts
I0330 17:56:24.466575    6079 start.go:364] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0330 17:56:24.466669    6079 start.go:368] acquired machines lock for "minikube" in 73.918µs
I0330 17:56:24.466679    6079 start.go:96] Skipping create...Using existing machine configuration
I0330 17:56:24.466683    6079 fix.go:55] fixHost starting: m01
W0330 17:56:24.467438    6079 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0330 17:56:24.467450    6079 api_server.go:165] Checking apiserver status ...
I0330 17:56:24.467480    6079 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0330 17:56:24.491848    6079 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0330 17:56:24.491892    6079 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0330 17:56:24.503507    6079 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0330 17:56:24.503520    6079 fix.go:129] unexpected machine state, will restart: <nil>
I0330 17:56:24.504816    6079 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0330 17:56:24.506623    6079 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0330 17:56:24.506761    6079 start.go:300] post-start starting for "minikube" (driver="none")
I0330 17:56:24.506810    6079 start.go:328] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0330 17:56:24.506837    6079 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0330 17:56:24.514339    6079 main.go:141] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0330 17:56:24.515616    6079 out.go:177] ℹ️  OS release is Kali GNU/Linux Rolling
I0330 17:56:24.516457    6079 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0330 17:56:24.516718    6079 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0330 17:56:24.516920    6079 start.go:303] post-start completed in 10.151847ms
I0330 17:56:24.516926    6079 fix.go:57] fixHost completed within 50.243248ms
I0330 17:56:24.516930    6079 start.go:83] releasing machines lock for "minikube", held for 50.255161ms
I0330 17:56:24.517227    6079 exec_runner.go:51] Run: cat /version.json
I0330 17:56:24.517935    6079 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
W0330 17:56:24.518093    6079 start.go:396] Unable to open version.json: cat /version.json: exit status 1
stdout:

stderr:
cat: /version.json: No such file or directory
I0330 17:56:24.518135    6079 exec_runner.go:51] Run: sh -c "stat /etc/cni/net.d/*loopback.conf*"
W0330 17:56:24.520730    6079 cni.go:208] loopback cni configuration skipped: "/etc/cni/net.d/*loopback.conf*" not found
I0330 17:56:24.520800    6079 exec_runner.go:51] Run: sudo mkdir -p /etc/systemd/system/cri-docker.service.d
I0330 17:56:24.528653    6079 exec_runner.go:144] found /etc/systemd/system/cri-docker.service.d/10-cni.conf, removing ...
I0330 17:56:24.528663    6079 exec_runner.go:207] rm: /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0330 17:56:24.528724    6079 exec_runner.go:151] cp: memory --> /etc/systemd/system/cri-docker.service.d/10-cni.conf (135 bytes)
I0330 17:56:24.528838    6079 exec_runner.go:51] Run: sudo cp -a /tmp/minikube3988080919 /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0330 17:56:24.535637    6079 exec_runner.go:51] Run: sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%!p(MISSING), " -exec sh -c "sudo mv {} {}.mk_disabled" ;
I0330 17:56:24.543740    6079 cni.go:258] no active bridge cni configs found in "/etc/cni/net.d" - nothing to disable
I0330 17:56:24.543757    6079 start.go:483] detecting cgroup driver to use...
I0330 17:56:24.543776    6079 detect.go:199] detected "systemd" cgroup driver on host os
I0330 17:56:24.543879    6079 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0330 17:56:24.566017    6079 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml"
I0330 17:56:24.573266    6079 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)restrict_oom_score_adj = .*$|\1restrict_oom_score_adj = false|' /etc/containerd/config.toml"
I0330 17:56:24.581249    6079 containerd.go:145] configuring containerd to use "systemd" as cgroup driver...
I0330 17:56:24.581289    6079 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)SystemdCgroup = .*$|\1SystemdCgroup = true|g' /etc/containerd/config.toml"
I0330 17:56:24.588982    6079 exec_runner.go:51] Run: sh -c "sudo sed -i 's|"io.containerd.runtime.v1.linux"|"io.containerd.runc.v2"|g' /etc/containerd/config.toml"
I0330 17:56:24.596551    6079 exec_runner.go:51] Run: sh -c "sudo sed -i '/systemd_cgroup/d' /etc/containerd/config.toml"
I0330 17:56:24.603835    6079 exec_runner.go:51] Run: sh -c "sudo sed -i 's|"io.containerd.runc.v1"|"io.containerd.runc.v2"|g' /etc/containerd/config.toml"
I0330 17:56:24.611165    6079 exec_runner.go:51] Run: sh -c "sudo rm -rf /etc/cni/net.mk"
I0330 17:56:24.618306    6079 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)conf_dir = .*$|\1conf_dir = "/etc/cni/net.d"|g' /etc/containerd/config.toml"
I0330 17:56:24.626410    6079 exec_runner.go:51] Run: sudo sysctl net.bridge.bridge-nf-call-iptables
I0330 17:56:24.633032    6079 exec_runner.go:51] Run: sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
I0330 17:56:24.639057    6079 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0330 17:56:24.999480    6079 exec_runner.go:51] Run: sudo systemctl restart containerd
I0330 17:56:25.105255    6079 start.go:483] detecting cgroup driver to use...
I0330 17:56:25.105285    6079 detect.go:199] detected "systemd" cgroup driver on host os
I0330 17:56:25.105387    6079 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0330 17:56:25.131685    6079 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0330 17:56:25.499241    6079 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0330 17:56:25.843041    6079 docker.go:529] configuring docker to use "systemd" as cgroup driver...
I0330 17:56:25.843066    6079 exec_runner.go:144] found /etc/docker/daemon.json, removing ...
I0330 17:56:25.843072    6079 exec_runner.go:207] rm: /etc/docker/daemon.json
I0330 17:56:25.843145    6079 exec_runner.go:151] cp: memory --> /etc/docker/daemon.json (143 bytes)
I0330 17:56:25.843275    6079 exec_runner.go:51] Run: sudo cp -a /tmp/minikube2202084233 /etc/docker/daemon.json
I0330 17:56:25.849828    6079 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0330 17:56:26.227969    6079 exec_runner.go:51] Run: sudo systemctl restart docker
I0330 17:56:27.069718    6079 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0330 17:56:27.443238    6079 exec_runner.go:51] Run: sudo systemctl unmask cri-docker.socket
I0330 17:56:27.810836    6079 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0330 17:56:28.167637    6079 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0330 17:56:28.523450    6079 exec_runner.go:51] Run: sudo systemctl restart cri-docker.socket
I0330 17:56:28.555211    6079 start.go:530] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0330 17:56:28.555274    6079 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0330 17:56:28.557392    6079 start.go:551] Will wait 60s for crictl version
I0330 17:56:28.557419    6079 exec_runner.go:51] Run: which crictl
I0330 17:56:28.558308    6079 exec_runner.go:51] Run: sudo /usr/bin/crictl version
I0330 17:56:30.866306    6079 exec_runner.go:84] Completed: sudo /usr/bin/crictl version: (2.307963697s)
I0330 17:56:30.866345    6079 retry.go:31] will retry after 11.04660288s: Temporary Error: sudo /usr/bin/crictl version: exit status 1
stdout:

stderr:
E0330 17:56:30.862770    6624 remote_runtime.go:145] "Version from runtime service failed" err="rpc error: code = Unavailable desc = connection closed before server preface received"
time="2023-03-30T17:56:30+05:30" level=fatal msg="getting the runtime version: rpc error: code = Unavailable desc = connection closed before server preface received"
I0330 17:56:41.913331    6079 exec_runner.go:51] Run: sudo /usr/bin/crictl version
I0330 17:56:41.950129    6079 retry.go:31] will retry after 21.607636321s: Temporary Error: sudo /usr/bin/crictl version: exit status 1
stdout:

stderr:
E0330 17:56:41.946688    6646 remote_runtime.go:145] "Version from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""
time="2023-03-30T17:56:41+05:30" level=fatal msg="getting the runtime version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""
I0330 17:57:03.560190    6079 exec_runner.go:51] Run: sudo /usr/bin/crictl version
I0330 17:57:03.598088    6079 out.go:177] 
W0330 17:57:03.600067    6079 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/bin/crictl version: exit status 1
stdout:

stderr:
E0330 17:57:03.593552    6708 remote_runtime.go:145] "Version from runtime service failed" err="rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""
time="2023-03-30T17:57:03+05:30" level=fatal msg="getting the runtime version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

W0330 17:57:03.600105    6079 out.go:239] 
W0330 17:57:03.602090    6079 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0330 17:57:03.603085    6079 out.go:177] 

### Operating System

Other

### Driver

None (Baremetal)

**Comment by afbjorklund** [comment]
There should be some more information available in `minikube ssh sudo systemctl status cri-dockerd`
