### ISSUE TITLE
 minikube start --driver=none (error)

### ISSUE THREAD

**Issue by prakash962930** [kubernetes/minikube#16196]
### What Happened?

root@ip-172-31-33-99:~/bin# minikube start --driver=none
* minikube v1.29.0 on Ubuntu 20.04 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 20.04.6 LTS

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo /usr/local/bin/crictl version: exit status 1
stdout:

stderr:
time="2023-03-30T06:06:40Z" level=fatal msg="unable to determine runtime API version: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial unix /var/run/cri-dockerd.sock: connect: connection refused\""

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                     

### Attach the log file

 minikube start --driver=none

### Operating System

None

### Driver

None

**Comment by pidumenk** [comment]
Hey, @prakash962930, 

Did you try this command `sudo -E minikube start --driver=none`?
