### ISSUE TITLE
Issue connecting to backend postgres service

### ISSUE THREAD

**Issue by shavo007** [kubernetes/minikube#1620]
**BUG REPORT ** 

**Minikube version** (use `minikube version`): 0.19.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 7
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**: kubectl, installed minikube-installer.exe
- **Others**:

**What happened**:

I am attempting to connect my frontend service to backend service (postgres)
**What you expected to happen**:
When I access the URI for front end app, that it renders correctly and connects to db

**How to reproduce it** (as minimally and precisely as possible):
Go to https://github.com/shavo007/pact-demo/tree/dev/k8s-resource-objects/kubernetes
Create the resource objects for both postgres and pact

`kubectl create -f ./kubernetes`

Open dashboard 

`~/minikube.exe dashboard`

Change the service type for pact to LoadBalancer and access the URI in browser.
Tail the pod logs for pact and you will see connection refused.

 Message from application: PG::ConnectionBad: could not translate host name "postgres" to address: Name or service not known

postgres is exposed as a service on port 5433.
I was under the assumption that pact can then connect to this service on host postgres. But it does not.

I think it is an issue with DNS but I am not sure. This is my first time to try and get k8s cluster working.

If you run the docker-compose file locally it works.

**Anything else do we need to know**:
If i ssh into pact container i can ping postgres.

**Comment by shavo007** [comment]
I installed nmap on pact pod and results are 
[4:02 PM] shane lee: nmap -p 5433 postgres
[4:02 PM] shane lee: Nmap scan report for postgres (10.0.0.118)
Host is up (0.00049s latency).
rDNS record for 10.0.0.118: postgres.default.svc.cluster.local
PORT     STATE SERVICE
5433/tcp open  pyrrho

**Comment by wstrange** [comment]
@shavo007 If you think this is dns issue, finding the kube-dns pod and killing it usually clears up any issues (kube will restart it).

But my guess is that this is a setup issue in your configuration - not so much a bug in minikube.

Does kubectl describe svc

show that the service is up, and that it has bound to an backend endpoint?

I'd suggest you try the slack kubernetes-users, or post in the google group

**Comment by shavo007** [comment]
fixed the issue. i have pushed the new changes to my branch. still not sure what was wrong with the config.

i was testing another application also and get unknownhostexception. dont ask me why but i increased the memory size of the cluster and recreated the deployments and it worked!!
