### ISSUE TITLE
minikube start command isn't working

### ISSUE THREAD

**Issue by maheshchandra6610** [kubernetes/minikube#16213]
### What Happened?

Upon running the below command:
minikube start --driver=none

The following error occurs:
😄  minikube v1.29.0 on Debian kali-rolling
✨  Using the none driver based on user configuration

🧯  The requested memory allocation of 1962MiB does not leave room for system overhead (total system memory: 1962MiB). You may face stability issues.
💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=1962mb'

👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=2, Memory=1962MB, Disk=80159MB) ...
ℹ  OS release is Kali GNU/Linux Rolling

❌  Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                            
[logs.txt](https://github.com/kubernetes/minikube/files/11132858/logs.txt)
                                                               │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

* 
* ==> Audit <==
* |---------|---------------|----------|------|---------|---------------------|----------|
| Command |     Args      | Profile  | User | Version |     Start Time      | End Time |
|---------|---------------|----------|------|---------|---------------------|----------|
| start   | --driver=none | minikube | root | v1.29.0 | 02 Apr 23 13:12 EDT |          |
|---------|---------------|----------|------|---------|---------------------|----------|

* 
* ==> Last Start <==
* Log file created at: 2023/04/02 13:12:46
Running on machine: kali
Binary: Built with gc go1.19.5 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0402 13:12:46.935357  218422 out.go:296] Setting OutFile to fd 1 ...
I0402 13:12:46.936179  218422 out.go:348] isatty.IsTerminal(1) = true
I0402 13:12:46.936186  218422 out.go:309] Setting ErrFile to fd 2...
I0402 13:12:46.936196  218422 out.go:348] isatty.IsTerminal(2) = true
I0402 13:12:46.936342  218422 root.go:334] Updating PATH: /root/.minikube/bin
W0402 13:12:46.937568  218422 root.go:311] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0402 13:12:46.939274  218422 out.go:303] Setting JSON to false
I0402 13:12:47.012716  218422 start.go:125] hostinfo: {"hostname":"kali","uptime":18686,"bootTime":1680436881,"procs":207,"os":"linux","platform":"debian","platformFamily":"debian","platformVersion":"kali-rolling","kernelVersion":"6.1.0-kali7-amd64","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"564d8c96-c4d2-4ac3-e30b-ba10ed7af8a3"}
I0402 13:12:47.012914  218422 start.go:135] virtualization:  
I0402 13:12:47.017696  218422 out.go:177] 😄  minikube v1.29.0 on Debian kali-rolling
W0402 13:12:47.021136  218422 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0402 13:12:47.021160  218422 notify.go:220] Checking for updates...
I0402 13:12:47.023190  218422 driver.go:365] Setting default libvirt URI to qemu:///system
I0402 13:12:47.025017  218422 out.go:177] ✨  Using the none driver based on user configuration
I0402 13:12:47.027107  218422 start.go:296] selected driver: none
I0402 13:12:47.027134  218422 start.go:857] validating driver "none" against <nil>
I0402 13:12:47.027154  218422 start.go:868] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0402 13:12:47.027749  218422 start_flags.go:305] no existing cluster config was found, will generate one from the flags 
I0402 13:12:47.029251  218422 out.go:177] 
W0402 13:12:47.030423  218422 out.go:239] 🧯  The requested memory allocation of 1962MiB does not leave room for system overhead (total system memory: 1962MiB). You may face stability issues.
W0402 13:12:47.031014  218422 out.go:239] 💡  Suggestion: Start minikube with less memory allocated: 'minikube start --memory=1962mb'
I0402 13:12:47.032983  218422 out.go:177] 
I0402 13:12:47.033919  218422 start_flags.go:386] Using suggested 1962MB memory alloc based on sys=1962MB, container=0MB
I0402 13:12:47.036753  218422 start_flags.go:899] Wait components to verify : map[apiserver:true system_pods:true]
I0402 13:12:47.037372  218422 cni.go:84] Creating CNI manager for ""
I0402 13:12:47.037390  218422 cni.go:157] "none" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
I0402 13:12:47.037397  218422 start_flags.go:314] Found "bridge CNI" CNI - setting NetworkPlugin=cni
I0402 13:12:47.037407  218422 start_flags.go:319] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:1962 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:}
I0402 13:12:47.038541  218422 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0402 13:12:47.039889  218422 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0402 13:12:47.039941  218422 lock.go:35] WriteFile acquiring /root/.minikube/profiles/minikube/config.json: {Name:mk270d1b5db5965f2dc9e9e25770a63417031943 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0402 13:12:47.055215  218422 cache.go:193] Successfully downloaded all kic artifacts
I0402 13:12:47.055279  218422 start.go:364] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0402 13:12:47.055423  218422 start.go:368] acquired machines lock for "minikube" in 124.617µs
I0402 13:12:47.055462  218422 start.go:93] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.37@sha256:8bf7a0e8a062bc5e2b71d28b35bfa9cc862d9220e234e86176b3785f685d8b15 Memory:1962 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.26.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP:} &{Name:m01 IP: Port:8443 KubernetesVersion:v1.26.1 ContainerRuntime:docker ControlPlane:true Worker:true}
I0402 13:12:47.055531  218422 start.go:125] createHost starting for "m01" (driver="none")
I0402 13:12:47.056682  218422 out.go:177] 🤹  Running on localhost (CPUs=2, Memory=1962MB, Disk=80159MB) ...
I0402 13:12:47.057524  218422 exec_runner.go:51] Run: systemctl --version
I0402 13:12:47.063287  218422 start.go:159] libmachine.API.Create for "minikube" (driver="none")
I0402 13:12:47.063345  218422 client.go:168] LocalClient.Create starting
I0402 13:12:47.064203  218422 main.go:141] libmachine: Creating CA: /root/.minikube/certs/ca.pem
I0402 13:12:47.190116  218422 main.go:141] libmachine: Creating client certificate: /root/.minikube/certs/cert.pem
I0402 13:12:47.398222  218422 client.go:171] LocalClient.Create took 334.863641ms
I0402 13:12:47.398267  218422 start.go:167] duration metric: libmachine.API.Create for "minikube" took 334.984635ms
I0402 13:12:47.398274  218422 start.go:300] post-start starting for "minikube" (driver="none")
I0402 13:12:47.398330  218422 start.go:328] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0402 13:12:47.398390  218422 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0402 13:12:47.607341  218422 main.go:141] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0402 13:12:47.610959  218422 out.go:177] ℹ️  OS release is Kali GNU/Linux Rolling
I0402 13:12:47.612860  218422 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0402 13:12:47.613084  218422 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0402 13:12:47.613173  218422 start.go:303] post-start completed in 214.886272ms
I0402 13:12:47.615421  218422 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0402 13:12:47.616008  218422 start.go:128] duration metric: createHost completed in 560.463461ms
I0402 13:12:47.616023  218422 start.go:83] releasing machines lock for "minikube", held for 560.589882ms
I0402 13:12:47.616674  218422 exec_runner.go:51] Run: cat /version.json
W0402 13:12:47.618629  218422 start.go:396] Unable to open version.json: cat /version.json: exit status 1
stdout:

stderr:
cat: /version.json: No such file or directory
I0402 13:12:47.618726  218422 exec_runner.go:51] Run: sh -c "stat /etc/cni/net.d/*loopback.conf*"
I0402 13:12:47.621392  218422 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
W0402 13:12:47.671291  218422 cni.go:208] loopback cni configuration skipped: "/etc/cni/net.d/*loopback.conf*" not found
I0402 13:12:47.671418  218422 exec_runner.go:51] Run: sudo mkdir -p /etc/systemd/system/cri-docker.service.d
I0402 13:12:47.689130  218422 exec_runner.go:151] cp: memory --> /etc/systemd/system/cri-docker.service.d/10-cni.conf (135 bytes)
I0402 13:12:47.689339  218422 exec_runner.go:51] Run: sudo cp -a /tmp/minikube1792557038 /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0402 13:12:47.704610  218422 exec_runner.go:51] Run: sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%!p(MISSING), " -exec sh -c "sudo mv {} {}.mk_disabled" ;
I0402 13:12:47.719942  218422 cni.go:258] no active bridge cni configs found in "/etc/cni/net.d" - nothing to disable
I0402 13:12:47.720209  218422 start.go:483] detecting cgroup driver to use...
I0402 13:12:47.720251  218422 detect.go:199] detected "systemd" cgroup driver on host os
I0402 13:12:47.720425  218422 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0402 13:12:47.996572  218422 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml"
I0402 13:12:48.081156  218422 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)restrict_oom_score_adj = .*$|\1restrict_oom_score_adj = false|' /etc/containerd/config.toml"
I0402 13:12:48.097720  218422 containerd.go:145] configuring containerd to use "systemd" as cgroup driver...
I0402 13:12:48.097772  218422 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)SystemdCgroup = .*$|\1SystemdCgroup = true|g' /etc/containerd/config.toml"
I0402 13:12:48.113907  218422 exec_runner.go:51] Run: sh -c "sudo sed -i 's|"io.containerd.runtime.v1.linux"|"io.containerd.runc.v2"|g' /etc/containerd/config.toml"
I0402 13:12:48.128713  218422 exec_runner.go:51] Run: sh -c "sudo sed -i '/systemd_cgroup/d' /etc/containerd/config.toml"
I0402 13:12:48.144146  218422 exec_runner.go:51] Run: sh -c "sudo sed -i 's|"io.containerd.runc.v1"|"io.containerd.runc.v2"|g' /etc/containerd/config.toml"
I0402 13:12:48.160026  218422 exec_runner.go:51] Run: sh -c "sudo rm -rf /etc/cni/net.mk"
I0402 13:12:48.174538  218422 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)conf_dir = .*$|\1conf_dir = "/etc/cni/net.d"|g' /etc/containerd/config.toml"
I0402 13:12:48.189805  218422 exec_runner.go:51] Run: sudo sysctl net.bridge.bridge-nf-call-iptables
I0402 13:12:48.203302  218422 exec_runner.go:51] Run: sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
I0402 13:12:48.215692  218422 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0402 13:12:48.777000  218422 exec_runner.go:51] Run: sudo systemctl restart containerd
I0402 13:12:49.118198  218422 exec_runner.go:84] Completed: curl -sS -m 2 https://registry.k8s.io/: (1.496772872s)
I0402 13:12:56.894474  218422 exec_runner.go:84] Completed: sudo systemctl restart containerd: (8.117431842s)
I0402 13:12:56.894493  218422 start.go:483] detecting cgroup driver to use...
I0402 13:12:56.894541  218422 detect.go:199] detected "systemd" cgroup driver on host os
I0402 13:12:56.894924  218422 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0402 13:12:56.931930  218422 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0402 13:12:57.489609  218422 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0402 13:12:58.038440  218422 docker.go:529] configuring docker to use "systemd" as cgroup driver...
I0402 13:12:58.049491  218422 exec_runner.go:151] cp: memory --> /etc/docker/daemon.json (143 bytes)
I0402 13:12:58.049758  218422 exec_runner.go:51] Run: sudo cp -a /tmp/minikube3445724001 /etc/docker/daemon.json
I0402 13:12:58.066183  218422 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0402 13:12:58.716365  218422 exec_runner.go:51] Run: sudo systemctl restart docker
I0402 13:13:27.923645  218422 exec_runner.go:84] Completed: sudo systemctl restart docker: (29.207253597s)
I0402 13:13:27.923693  218422 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0402 13:13:28.437923  218422 exec_runner.go:51] Run: sudo systemctl unmask cri-docker.socket
I0402 13:13:28.966268  218422 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0402 13:13:29.490758  218422 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0402 13:13:30.006944  218422 exec_runner.go:51] Run: sudo systemctl restart cri-docker.socket
I0402 13:13:30.072718  218422 start.go:530] Will wait 60s for socket path /var/run/cri-dockerd.sock
I0402 13:13:30.072818  218422 exec_runner.go:51] Run: stat /var/run/cri-dockerd.sock
I0402 13:13:30.076882  218422 start.go:551] Will wait 60s for crictl version
I0402 13:13:30.132585  218422 exec_runner.go:51] Run: which crictl
I0402 13:13:30.170107  218422 out.go:177] 
W0402 13:13:30.172500  218422 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: which crictl: exit status 1
stdout:

stderr:

W0402 13:13:30.172625  218422 out.go:239] 
W0402 13:13:30.176794  218422 out.go:239] [31m╭───────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                             [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                           [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    [31m│[0m
[31m│[0m                                                                                           [31m│[0m
[31m╰───────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0402 13:13:30.178201  218422 out.go:177] 

* 

### Operating System

Other

### Driver

None

**Comment by afbjorklund** [comment]
See https://minikube.sigs.k8s.io/docs/drivers/none/ for requirements
