### ISSUE TITLE
No dns service or dashboard after clean install of minikube

### ISSUE THREAD

**Issue by shavo007** [kubernetes/minikube#1622]
BUG REPORT

**Minikube version** (use `minikube version`):minikube version: v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release):macOS Sierra 10.12.5
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):v0.18.0
- **Install tools**:kubectl using bash
- **Others**:

**What happened**:
start the cluster. get cluster info and get no information about kube-dns or kube-dashboard

`kubectl  cluster-info`
Kubernetes master is running at https://192.168.99.104:8443

Only one pod

$ kubectl get pods  --namespace=kube-system
NAME                          READY     STATUS    RESTARTS   AGE
kube-addon-manager-minikube   1/1       Running   1          10m

Logs show:
kubectl  logs kube-addon-manager-minikube --namespace=kube-system
The connection to the server localhost:8080 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==

**What you expected to happen**:
Multiple services up and running and be able to access the dashboard. 

**How to reproduce it** (as minimally and precisely as possible):
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.18.0/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

start the cluster
`minikube start`

All I did was install minikube and I cant get anything to work! ;-)

I have spent days on this on mac and windows 7 and i cant get minikube working at all! 

**Anything else do we need to know**:

**Comment by dlorenc** [comment]
Does this repro on newer minikube releases? Could you attach the output of "minikube logs"?

**Comment by r2d4** [comment]
Any update @shavo007?

**Comment by shavo007** [comment]
Apologies. Give me a sec. I found the solution on another issue.

**Comment by shavo007** [comment]
Commented on #1451

Ran command below and worked!

VBoxManage modifyvm "minikube" --natdnshostresolver1 on

minikube start

kubectl cluster-info

Kubernetes master is running at https://192.168.99.104:8443
KubeDNS is running at https://192.168.99.104:8443/api/v1/proxy/namespaces/kube-system/services/kube-dns
kubernetes-dashboard is running at https://192.168.99.104:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

**Comment by mradmila** [comment]
I am hitting the same issue on minikube version: v0.24.1. Can someone please take a look? No virtualization deployment hits this issue, while vbox one is OK (for now). In my case it may have to do with creating/destroying local clusters.

**Comment by mradmila** [comment]
Checking the addon manager I get the following:

INFO: == Kubernetes addon manager started at 2018-01-17T00:18:19+0000 with ADDON_CHECK_INTERVAL_SEC=60 ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Failed to start /opt/namespace.yaml in namespace  at 2018-01-17T00:18:20+0000. 99 tries remaining. ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
Unable to connect to the server: dial tcp <ip>:8443: getsockopt: no route to host

**Comment by mradmila** [comment]
More info. I have ipv6 enabled, but minikube uses ipv4 without the listener on ipv4:

netstat -nap | grep 8443
tcp        0      0 127.0.0.1:53886         127.0.0.1:8443          ESTABLISHED -
tcp        0      0 127.0.0.1:53878         127.0.0.1:8443          ESTABLISHED -
tcp        0      0 127.0.0.1:53854         127.0.0.1:8443          ESTABLISHED -
tcp        0      0 127.0.0.1:53874         127.0.0.1:8443          ESTABLISHED -
tcp        0      0 127.0.0.1:53882         127.0.0.1:8443          ESTABLISHED -
_**tcp6       0      0 :::8443                 :::*                    LISTEN      -**_
tcp6       0      0 127.0.0.1:8443          127.0.0.1:53878         ESTABLISHED -
tcp6       0      0 127.0.0.1:8443          127.0.0.1:53882         ESTABLISHED -
tcp6       0      0 127.0.0.1:8443          127.0.0.1:53854         ESTABLISHED -
tcp6       0      0 127.0.0.1:8443          127.0.0.1:53874         ESTABLISHED -
tcp6       0      0 127.0.0.1:8443          127.0.0.1:53886         ESTABLISHED -
