### ISSUE TITLE
Minikube v1.30.0+ (with Go 1.20) do not run on Alpine Linux

### ISSUE THREAD

**Issue by Nuru** [kubernetes/minikube#16228]
### What Happened?

Minikube v1.29.0 ran under Alpine Linux, but v1.30.0 and v1.30.1 do not. Please either fix the build so that it works under Alpine or state your intention to not support Alpine. See https://github.com/golang/go/issues/59305#issuecomment-1495642594 for more information.

```bash
$ curl -sSL -o minikube https://github.com/kubernetes/minikube/releases/download/v1.30.0/minikube-linux-amd64
$ ls -l minikube 
-rw-r--r--    1 root     root      83945324 Apr  3 23:01 minikube
$ chmod a+x minikube 
$ ls -l minikube 
-rwxr-xr-x    1 root     root      83945324 Apr  3 23:01 minikube
$ ./minikube version
/bin/sh: ./minikube: not found
$ # Note: under Alpine, running a command that exists and getting
$ # a "not found" error usually indicates a missing dynamic library.
$ ldd minikube 
	/lib64/ld-linux-x86-64.so.2 (0x7f2f482ec000)
	libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7f2f482ec000)
	libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7f2f482ec000)
Error loading shared library libresolv.so.2: No such file or directory (needed by minikube)
Error relocating minikube: __res_search: symbol not found

$ cat /etc/os-release 
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.16.3
PRETTY_NAME="Alpine Linux v3.16"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://gitlab.alpinelinux.org/alpine/aports/-/issues"
```

## References
- https://github.com/golang/go/issues/59305
- https://github.com/golang/go/issues/59304

### Attach the log file

No log generated

### Operating System

Other

### Driver

None

**Comment by afbjorklund** [comment]
If you want to run on Alpine, I think you need to install the "glibc" compatibility package.

https://wiki.alpinelinux.org/wiki/Running_glibc_programs

Or better yet, use a version of minikube that has been built for it (and the musl library) ?

https://pkgs.alpinelinux.org/package/edge/testing/x86_64/minikube

**Comment by afbjorklund** [comment]
You can also resort to some hack like (with `gcompat` installed):

`ln -sf /lib64/ld-linux-x86-64.so.2 /usr/lib/libresolv.so.2`

**Comment by Nuru** [comment]
> If you want to run on Alpine, I think you need to install the glibc compatibility package.
> 
> https://wiki.alpinelinux.org/wiki/Running_glibc_programs
> 

I have the `glibc` compatibility package installed.

> Or better yet, use a version of minikube that has been built for it (and the musl library) ?
> 
> https://pkgs.alpinelinux.org/package/edge/testing/x86_64/minikube

There is no package there for v1.30.0, I expect because it takes its binaries from this repo's Release Assets, and this repo's release asset for v1.30.0 doesn't run on Alpine.

v1.30.1 also doesn't run on Alpine.

I am asking the maintainers of the build process to either fix their build so it works on Alpine (as did all the prior versions) or declare they are not going to support Alpine going forward, so we can have a clear answer to the question of are they going to continue to support Alpine.

**Comment by afbjorklund** [comment]
> I expect because it takes its binaries from this repo's Release Assets, and this repo's release asset for v1.30.0 doesn't run on Alpine.

It is built from source, so I think you need to request a new version in Alpine using the normal (Alpine) channels ?

https://git.alpinelinux.org/aports/tree/testing/minikube/APKBUILD

You can also install the `git` and `go` packages, and build a newer version of minikube yourself. (with `make`) ?

https://minikube.sigs.k8s.io/docs/contrib/building/binaries/

> I am asking the maintainers of the build process to either fix their build so it works on Alpine (as did all the prior versions) or declare they are not going to support Alpine going forward, so we can have a clear answer to the question of are they going to continue to support Alpine.

Once the glibc compatibility (in Alpine) is fixed to also include libresolv.so, then the glibc binaries will work again.

I don't that minikube will build or provide any binaries using musl for download, so they will continue to use glibc.

But if you want a "native" package, then `apk add minikube` is recommended.

It is in _testing_ repo, while you can find _docker_ in the "community" repository...

**Comment by afbjorklund** [comment]
This is the repository: https://git.adelielinux.org/adelie/gcompat

As per above, it needs at least `__res_search` from libresolv.so.2

**Comment by Nuru** [comment]
@afbjorklund I appreciate your effort at trying to solve the problem "how do I get minikube v1.30 to work on Apline?" However, that is not the problem I am interested in solving or the question I want answered.

Up until v1.30, I could install minikube on Alpine with

```bash
$ apk add libc6-compat
$ VERSION=1.29.0 # for example
$ curl -o /usr/local/bin/minikube -sSL https://github.com/kubernetes/minikube/releases/download/v${VERSION}/minikube-linux-amd64
$ chmod a+x /usr/local/bin/minikube
```

Starting with version v1.30.0 this no longer works. It also does not work if I substitute `gcompat` for `libc6-compat`. My question/request is will the build maintainers fix the build so that I can continue to install this way, or do I have to switch to finding some other way to install `minikube` on Alpine, such as building it myself or finding a prebuilt Alpine package in an Alpine package repository?

**Comment by afbjorklund** [comment]
It would be _possible_ to also build musl binaries of minikube, but right now there are no release jobs to do it.

**Comment by afbjorklund** [comment]
There should be some documentation provided, about the minimum OS requirements of the  binaries provided.
