### ISSUE TITLE
Create installer to remove the necessity for users to download additional binaries

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1623]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

The current installation process for minikube is:

1. Download and install a hypervisor driver (kvm, xhyve, hyper-v)
2. Set up hypervisor driver (setup qemu-kvm, root own xhyve driver, set switches on hyper-v)
3. Download and install minikube

We've tried in the past to vendor the drivers directly - unfortunately there were two issues:

1. xhyve driver - must have root permissions, calls the hyperkit CLI which os.Exits
2. kvm driver - dynamically linked against libvirt.so, which can't be statically linked

The feature request is that we change the installation process to include the non-virtualbox drivers for each OS, xhyve and kvm.  The extraction script will extract and set up the drivers correctly.
Then, the installation process would be

1. Download and extract minikube.tar
2. Run script to set up hypervisor driver

Of course, package managers could automate this process.

**Comment by aaron-prindle** [comment]
I'm going to start on this.  Does anyone have suggestions for examples of best practices for tar installation of multiple components?  Also libraries that might make package manager integration easier?

**Comment by aaron-prindle** [comment]
Potential items we could also bundle in the tar in the future:
addons container images
replace go-bindata assets with files that are stored in tar

**Comment by r2d4** [comment]
the items that we bundle with go-bindata should definitely just be included in the tar.  
- localkube
- addon YAMLs
- minikube iso image

Possibly image tarballs.  We might not actually want to bundle them in the minikube iso, since minishift will eventually want to move over to the minikube iso but not want our preseeded k8s images.

**Comment by aaron-prindle** [comment]
Talked offline with @dlorenc.  Initially we will bundle the drivers in a tar w/ the minikube binary and update our the install scripts to have driver installation.  The removal of go-bindata, bundling of other assets in a tar (iso, localkube, addons, etc.), and os specific installers is to be done later.

**Comment by tstromberg** [comment]
Closing, as we've decided to stick with the single binary approach for now: but allow the binary to download VM drivers as necessary.
