### ISSUE TITLE
Better Document Using Minikube With Automation To Avoid Pitfalls

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1626]
As users begin to use minikube in automated workflows, it might be important to consider how update text, etc. could accidentally return unexpected results.  We currently have the MINIKUBE_WANTUPDATENOTIFICATION=false env var to disable this, perhaps we should document this better or have some kind of "script-mode" flag that we recommend to disable things like bug reporting and update checking.  Just thinking of ways so that users don't have to first see the error but instead never encounter this behavior.

**Comment by sampowers** [comment]
I maintain an internal (for now?) script for downloading, installing dependencies of minikube and wrapping the startup, to inject custom options, deploy a custom kube-dns for supporting a cluster domain (do i still need this?), and to add imagePullSecrets to the default service account.  It's a lot of extra stuff.

One hurdle I've had is that addons can't be configured prior to the minikube startup.  It would be nice for scripting with minikube to be able to lay down the intended configuration before invoking minikube at all.  And maybe that just takes the form of managing ~/.minikube/config/config.json directly.

I'm doing a lot of extra stuff in this script https://gist.github.com/sampowers/4399646bd9375efff03611407733c0a2#file-minikube-curlbash-to-the-extreme-sh that I'm not sure if it should be done by minikube itself or if these are special concerns of our environment.  Anyway, scripting minikube has been relatively easy and good so far and I have few complaints.
