### ISSUE TITLE
error: no 'git' program on path: exec: "git": executable file not found in %PATH%

### ISSUE THREAD

**Issue by amit-pawar10** [kubernetes/minikube#16272]
### What Happened?

I have docker desktop and minikube and i am  trying to deploy kubeflow pipeline

I am following this documentation for deploying pipeline (This is my first time): https://www.kubeflow.org/docs/components/pipelines/v1/installation/localcluster-deployment/

This is the code from that link
# env/platform-agnostic-pns hasn't been publically released, so you will install it from master
set PIPELINE_VERSION=1.8.5

when i run this below command, i get the error.
kubectl apply -k "github.com/kubeflow/pipelines/manifests/kustomize/cluster-scoped-resources?ref=$PIPELINE_VERSION"

ERROR:
error: no 'git' program on path: exec: "git": executable file not found in %PATH%

I am not sure what the error, to fix i tried installing git and added it in environment variable path.

### Attach the log file

![image](https://user-images.githubusercontent.com/95141208/230725734-b64e4b3e-977e-44d0-b7d9-4e901b15ad11.png)

### Operating System

Windows

### Driver

Docker

**Comment by LJTian** [comment]
After installing git and adding environment variables, you need to reopen the terminal (it can also be triggered manually) to trigger the environment variables to take effect. After opening the terminal shell, enter the command "git verison", and the judgment will take effect. Hope this helps with your problem.
