### ISSUE TITLE
`machine-drivers/machine` minikube refactor

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#16279]
@afbjorklund I remember you talking in the past about essentially forking the [machine-drivers/machine](https://github.com/machine-drivers/machine) and removing all the stuff minikube doesn't use and just maintaining what we use. @x7upLime is interested in this as he was looking into improvements to the Docker provisioner.

Could you provide an outline of the process and any improvements you wanted this to resolve. Trying to centralize this info for others interested in this task.

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/16279

**Comment by afbjorklund** [comment]
Consider renaming the rpc binaries, from "docker-machine-driver-xxx" to "minikube-machine-driver-xxx"

To show that it is not actually meant to be used with `docker-machine`, but only with `minikube`...

Keep the separate binaries for linking purposes (shared libraries adding runtime dependencies)

Even though the minikube fork of configuring is currenly linking and hardcoding the flags anyway.

**Comment by afbjorklund** [comment]
@spowelljr : one thing to consider, is if you want to keep support for the legacy docker tcp socket ?

* https://github.com/kubernetes/minikube/issues/9229

if you remove the handling of the certificates and only support the ssh socket, it would simplify things...

None of the other container runtimes support `tcp://` sockets anyway, they are all using `unix://` now.

Some legacy API clients are **not** supporting the `ssh://` from Docker 18.03, and it hardcodes `docker`. :-(

So the usual workaround is to have the "machine" do the ssh tunneling of the unix socket now instead.

**Comment by afbjorklund** [comment]
So this refactoring last year didn't happen, all I managed to do was to merge the qemu driver...

Which was probably a mistake, so should revert that before it gets used in minikube (driver `v2`)

Apparently some docker-machine users are still using the gitlab fork, maybe have a look at that.

But it is also going EOL (in 2024), so it is "frozen" in the same way as Docker Machine was (2019)

**Comment by afbjorklund** [comment]
Add external driver repository: https://github.com/minikube-machine/machine-driver-qemu

Note that it contains the docker-machine driver (qemu), and not the minikube driver (qemu2)
