### ISSUE TITLE
Loosing Minikube cluster upon restarting my MAC

### ISSUE THREAD

**Issue by mounicachakiri** [kubernetes/minikube#16296]
### What Happened?

Mac OS: Big Sur V11.7.2 
Docker Desktop: v4.17.0
minikube version: v1.23.2 (commit: 0a0ad764652082477c00d51d2475284b5d39ceed)
minikube command used to start: minikube start --kubernetes-version=v1.21.14 --driver=docker --cpus=6 --memory="24000mb"
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/105314854/231537711-366df642-4af0-42c1-ab5f-1f4bde20f5d8.png">
Printing the current components.
```
`➜  ~ k get all -A
NAMESPACE     NAME                                   READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-558bd4d5db-tqsnx           1/1     Running   0          3m24s
kube-system   pod/etcd-minikube                      1/1     Running   0          3m30s
kube-system   pod/kube-apiserver-minikube            1/1     Running   0          3m30s
kube-system   pod/kube-controller-manager-minikube   1/1     Running   0          3m30s
kube-system   pod/kube-proxy-dd666                   1/1     Running   0          3m24s
kube-system   pod/kube-scheduler-minikube            1/1     Running   0          3m30s
kube-system   pod/storage-provisioner                1/1     Running   1          3m35s

NAMESPACE     NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)                  AGE
default       service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP                  3m39s
kube-system   service/kube-dns     ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP,9153/TCP   3m37s

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
kube-system   daemonset.apps/kube-proxy   1         1         1       1            1           kubernetes.io/os=linux   3m37s

NAMESPACE     NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns   1/1     1            1           3m37s

NAMESPACE     NAME                                 DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-558bd4d5db   1         1         1       3m24s`

```

After I deploy my Kubernetes components the resource usage from my docker desktop has been
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/105314854/231541871-df2b9207-e9d4-4ad4-8fb5-0c4d6e9b3171.png">

Restarted my Mac, which restarted my docker desktop and minikube is in stopped state
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/105314854/231544390-00578504-c5d6-41ca-b4d5-8df82a2cbd42.png">

```
minikube status

minikube
type: Control Plane
host: Stopped
kubelet: Stopped
apiserver: Stopped
kubeconfig: Stopped
```

Now when I start the minikube with the same command

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/105314854/231545376-cb84d621-21bd-4b2e-b10c-05fa962ced1d.png">

### Operating System

macOS (Default)

### Driver

Docker

**Comment by xzcxzcyy** [comment]
Same issue on v1.30.1.

```sh
Unable to restart cluster, will reset it: apiserver healthz: apiserver process never appeared.
```
