### ISSUE TITLE
Running minkube start failing with error message

### ISSUE THREAD

**Issue by kaushikvaibhav** [kubernetes/minikube#16318]
### What Happened?

I am running minkube on WSOL2 Ubuntu and it was working last 4 months. It started failing suddenly with attached message. I tried everything but did not work. Please help.

### Attach the log file

 docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --network minikube --ip 192.168.58.2 --volume minikube:/var --security-opt apparmor=unconfined --cpus=2 -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 --publish=127.0.0.1::32443 gcr.io/k8s-minikube/kicbase:v0.0.39@sha256:bf2d9f1e9d837d8deea073611d2605405b6be904647d97ebd9b12045ddfe1106: exit status 125
stdout:

stderr:
docker: Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted.
See 'docker run --help'.

❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --network minikube --ip 192.168.58.2 --volume minikube:/var --security-opt apparmor=unconfined --cpus=2 -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 --publish=127.0.0.1::32443 gcr.io/k8s-minikube/kicbase:v0.0.39@sha256:bf2d9f1e9d837d8deea073611d2605405b6be904647d97ebd9b12045ddfe1106: exit status 125
stdout:

stderr:
docker: Error response from daemon: NanoCPUs can not be set, as your kernel does not support CPU CFS scheduler or the cgroup is not mounted.
See 'docker run --help'.

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │

### Operating System

Ubuntu

### Driver

Docker

**Comment by MSpreckelsQS** [comment]
Hello there!
We just encountered the same problem yesterday and had a deeper look into it today. For us the error occurred because of the latest wsl2 kernel version (1.2, i think) , it seems there might be something broken there.
We tried multiple things to solve this like reinstalling minikube and docker or fiddling around with cgroup mounts.
 Ultimately, we solved the issue by manually downgrading wsl to a version that has an older kernel version [like 1.0.3](https://github.com/microsoft/WSL/releases/tag/1.0.3)

**Comment by jijosg** [comment]
> Hello there! We just encountered the same problem yesterday and had a deeper look into it today. For us the error occurred because of the latest wsl2 kernel version (1.2, i think) , it seems there might be something broken there. We tried multiple things to solve this like reinstalling minikube and docker or fiddling around with cgroup mounts. Ultimately, we solved the issue by manually downgrading wsl to a version that has an older kernel version [like 1.0.3](https://github.com/microsoft/WSL/releases/tag/1.0.3)

Thanks, this fixed the issue for me.

**Comment by mr-scripting** [comment]
I had the same problem and was able to solve it using this workaround. I hope it helps.

On powershell run as administrator:
```powershell
New-Item -Path $env:USERPROFILE\.wslconfig
notepad $env:USERPROFILE\.wslconfig
```
Paste the content bellow, this will ensure cgroups v1 is disabled
```
[wsl2]
kernelCommandLine = cgroup_no_v1=all
```

On wsl:

```bash
sudo vim /etc/fstab
```
Add the line bellow:
```
cgroup2 /sys/fs/cgroup cgroup2 rw,nosuid,nodev,noexec,relatime,nsdelegate 0 0
```
**Taken from:** https://stackoverflow.com/questions/73021599/how-to-enable-cgroup-v2-in-wsl2

My  Setup:

WSL version: 1.2.0.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.19044.2728

Linux md60s65c 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

minikube version: v1.29.0
commit: ddac20b4b34a9c8c857fc602203b6ba2679794d3
