### ISSUE TITLE
SHA256 for minikube-linux-amd64 0.20.0 are not correct

### ISSUE THREAD

**Issue by mortenlj** [kubernetes/minikube#1632]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): 0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): linux-amd64

**What happened**:

```
──╼ cat sums
591737b728745dbf01f634bf714353c416c2e56c39e2e0431910fa51783b7a19 minikube-darwin-amd64
f7d51f0b94f88650ced3ddb6e079f560e7ef142b8e4d53a5aee511ca1c2e3df4 minikube-linux-amd64
d4be02e5e7075943d6b4efca44c0ff56286f72236e2640d82010b944646612b7 minikube-windows-amd64.exe
──╼ sha256sum --check sums 
minikube-darwin-amd64: OK
minikube-linux-amd64: FAILED
minikube-windows-amd64.exe: OK
sha256sum: WARNING: 1 computed checksum did NOT match
```

This is the case for multiple downloaders on multiple machines, so it seems likely the checksums on github are wrong. If anyone can download files that match these checksums, please say so and close this issue.

**What you expected to happen**:

I expect the sums downloaded to match the sums generated.

**How to reproduce it** (as minimally and precisely as possible):

See above

**Anything else do we need to know**:

Would it be possible to make the sha256 files have the proper format so you can just pass them directly to sha256sum, instead of having to manually add the filename?

**Comment by r2d4** [comment]
So this is a result of https://github.com/kubernetes/minikube/issues/1630.  We re-uploaded the binaries built with the correct version of go.  f7d51f0b94f88650ced3ddb6e079f560e7ef142b8e4d53a5aee511ca1c2e3df4 should be the correct version, according to the github releases.

But we can make the sha256 files have the proper format so that they are easier to verify

**Comment by mortenlj** [comment]
I have tried downloading the binary again, from a completely different location (different machine, different OS, different ISP), and I get the exact same results:

```
$ wget -q https://github.com/kubernetes/minikube/releases/download/v0.20.0/minikube-linux-amd64
$ wget -q https://github.com/kubernetes/minikube/releases/download/v0.20.0/minikube-linux-amd64.sha256
$ sha256sum < minikube-linux-amd64
f7447a37332879b934bf7fcae97327367a5b92d33d12ea24301c212892efe326  -
$ cat minikube-linux-amd64.sha256 
f7d51f0b94f88650ced3ddb6e079f560e7ef142b8e4d53a5aee511ca1c2e3df4
```

**Comment by r2d4** [comment]
Sorry - I misread the checksums.  `f7447a37332879b934bf7fcae97327367a5b92d33d12ea24301c212892efe326` should be correct. I've updated the .sha256 file on the GCS bucket as well as the github release page. 

I'll add a PR shortly to address making the files the proper format for future releases.

**Comment by CrashenX** [comment]
Both the .sha256 file and the releases page still reflect the old checksum.
