### ISSUE TITLE
support a recent 1.7.0-beta.x release of kubernetes?

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/minikube#1633]
I'd love to be able to try out a new beta release of 1.7.x. It looks like the latest we can use in minikube is [1.7.0-alpha.2](https://github.com/kubernetes/minikube/blob/master/deploy/minikube/k8s_releases.json#L3) from  Apr 20. 

Any chance of a newer release please?

**Comment by jstrachan** [comment]
if it was as simple as submitting a PR against [this file](https://github.com/kubernetes/minikube/blob/master/deploy/minikube/k8s_releases.json#L3) I'd just do it but I'm guessing some localkube/binaries/images need to be downloadable first - so am not sure how I could help fix it

**Comment by r2d4** [comment]
Yes, I have an open PR that is for beta.1 that I will merge after I make a few fixes today.  https://github.com/kubernetes/minikube/issues/1584

**Comment by jstrachan** [comment]
@r2d4 awesome thanks!
