### ISSUE TITLE
minikube fails to start on m1 macos

### ISSUE THREAD

**Issue by bispaul** [kubernetes/minikube#16335]
### What Happened?

Failed to start docker container. Running "minikube delete" may fix it: provision: Temporary Error: transferring file to machine &{{/Users/<home>/.minikube/machines/server.pem /etc/docker server.pem 0640 } 0x1400074d470 <nil> 0x140006ea260}: sudo test -d /etc/docker && sudo scp -t /etc/docker && sudo touch -d "2023-04-17 13:48:24.74428863 +0530" /etc/docker/server.pem: Process exited with status 1

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/11247875/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by mariusraupach** [comment]
Hi @bispaul, did you enable the beta feature "Use containers for pulling..." in Docker Desktop?

I resolved the issue by disabling the feature.

**Comment by iSuslov** [comment]
@mariusraupach thank you! I can confirm that disabling this experimental feature fixes the problem.

**Comment by caerulescens** [comment]
@bispaul Is this still any issue for you? Are you able to confirm the workaround from @mariusraupach and @iSuslov? This should probably be closed.
