### ISSUE TITLE
Minikube failed to start in windows 

### ISSUE THREAD

**Issue by Lakhvinder25** [kubernetes/minikube#16330]
### What Happened?

 minikube v1.30.1 on Microsoft Windows 11 Home Single Language 10.0.22000.1817 Build 22000.1817
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🤦  StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

❌  Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
💡  Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3900
    ▪ https://github.com/kubernetes/minikube/issues/4730

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/11239020/logs.txt)

### Operating System

Windows

### Driver

VirtualBox

**Comment by muhm21cn** [comment]
I face the same problem in windows 11, and I'm sure the virtualization feature is enabled in BIOS since vmware and docker are works well.

**Comment by krishnaduttPanchagnula** [comment]
@muhm21cn can you share the logs?

**Comment by woifes** [comment]
I am new to minikube and wanted to start with it some days ago. It seems I have the same issue: Virtualization is activated (Docker Desktop and Vbox is working). But minikube wont start with the same error message (I am on Windows 10)
