### ISSUE TITLE
docker interface is created 

### ISSUE THREAD

**Issue by gennady-voronkov** [kubernetes/minikube#16368]
### What Happened?

I try to deploy minikube with parameters:
--container-runtime "containerd"
--driver "podman"
finaly it's successful, but when i go into podman container, interface is docker0 and uses 172.17.0.1/16, which the same with my internal network office.
actully it should not be used docker interface at all, as i use  containerd instead of docker.

### Attach the log file

$ ip a
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0

### Operating System

Ubuntu

### Driver

Podman

**Comment by ttecles** [comment]
I am trying to figure out how to change that IP too
