### ISSUE TITLE
kubernetes-dashboard errors should indicate that its not ready, rather than saying the service is not found .

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/minikube#1636]
**Minikube version** (use `minikube version`):** 

minikube version: v0.20.0
 
** What happened **

When starting the dashboard, you get validation errors imply there is something fundamentally broken, but really, its just that the dashboard pods aren't created yet.

```
➜  ~ minikube dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found
➜  ~ kubectl get services
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.0.0.1     <none>        443/TCP   1m
➜  ~ kubectl get pods
No resources found.
➜  ~ kubectl get pods --all-namespaces
NAMESPACE     NAME                          READY     STATUS              RESTARTS   AGE
kube-system   kube-addon-manager-minikube   1/1       Running             0          1m
kube-system   kube-dns-1301475494-nvlc2     0/3       ContainerCreating   0          30s
kube-system   kubernetes-dashboard-jhj1j    0/1       ContainerCreating   0          30s
```

**Expected Behaviour**

Instead, if we just printed "Could not find finalized endpoint for the dashboard, wait one minute and retry", it would be more accurate and intuitive for users on small or fresh  VMs that take a while to fire up new containers.

**Comment by r2d4** [comment]
Yeah, makes a lot of sense.  Looks like the current behavior is to wait for 120 seconds and then print an error if it hasn't come up by then.

https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/dashboard.go#L56

We could possibly do a better sanity check here - possibly that the replication controller has been created or that some of the pods are in `ContainerCreating`.
