### ISSUE TITLE
"minikube cache" will be deprecated

### ISSUE THREAD

**Issue by pguerin3** [kubernetes/minikube#16362]
### What Happened?

When I use:
```
minikube cache add container-registry.oracle.com/database/free
```
I get the warning:
```
"minikube cache" will be deprecated in upcoming versions, please switch to "minikube image load"
```
Would be nice for a reference to use minikube image load, instead of minikube cache, in the minikube cache documentation.
https://minikube.sigs.k8s.io/docs/commands/cache/

### Attach the log file

n/a

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by mcascone** [comment]
I just opened a PR to add this note: https://github.com/kubernetes/minikube/pull/16452
