### ISSUE TITLE
Issue with installing minikube on macos

### ISSUE THREAD

**Issue by fabinchristian** [kubernetes/minikube#16376]
### What Happened?

Not able to start minikube. Constantly receiving error.

### Attach the log file

fabin@Fabins-MBP ~ % minikube logs --file=logs.txt
E0426 01:46:10.978263   72236 logs.go:274] Failed to list containers for "kube-apiserver": docker: docker ps -a --filter=name=k8s_kube-apiserver --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0426 01:46:11.012726   72236 logs.go:274] Failed to list containers for "etcd": docker: docker ps -a --filter=name=k8s_etcd --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0426 01:46:11.037739   72236 logs.go:274] Failed to list containers for "coredns": docker: docker ps -a --filter=name=k8s_coredns --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0426 01:46:11.064239   72236 logs.go:274] Failed to list containers for "kube-scheduler": docker: docker ps -a --filter=name=k8s_kube-scheduler --format={{.ID}}: Process exited with status 1
stdout:

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by spowelljr** [comment]
Hi @fabinchristian, it looks like the Docker Engine running within minikube is not running. Could you upload the log file that was generated, thanks

**Comment by spowelljr** [comment]
Hi @fabinchristian, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
