### ISSUE TITLE
Incorrect versions of cri-dockerd installed on CI machines

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#16381]
When setting up the machine for the none integration tests we check if cri-dockerd is installed, if it is we don't do anything.

https://github.com/kubernetes/minikube/blob/768e62db1b18ef841e53e266b776abdf09c81db5/hack/jenkins/linux_integration_tests_none.sh#L73

This causes a problem as once cri-dockerd is installed on the machine it's not going to be updated and that version will continue to exist. This is currently causing issues as some machines have an old version installed (v0.2.1) but a change in v0.3.0 enabled support for Kubernetes v1.26+. So the tests on the machine fail as we're trying to run Kubernetes v1.26 on a cri-dockerd version that doesn't support it.

We need to check if it's installed, and if it is, does it match the version we expect, otherwise, install the latest version.

**Comment by afbjorklund** [comment]
I think these should be safe to upgrade, since those two versions are still backwards compatible.

But we see that some of the newer version of container runtimes, do not support the old CRI API anymore...
