### ISSUE TITLE
error installing minikube

### ISSUE THREAD

**Issue by shola007** [kubernetes/minikube#16406]
### What Happened?

sudo minikube start
* minikube v1.6.2 on Ubuntu 22.04 (xen/amd64)
* Selecting 'none' driver from user configuration (alternates: [])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing none VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.17.0 on Docker '23.0.3' ...
*
X Failed to setup kubeconfig: unable to acquire lock for {Name:mk19004591210340446308469f521c5cfa3e1599 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}: unable to open /tmp/juju-mk19004591210340446308469f521c5cfa3e1599: permission denied
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

### Attach the log file

sudo minikube start
* minikube v1.6.2 on Ubuntu 22.04 (xen/amd64)
* Selecting 'none' driver from user configuration (alternates: [])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing none VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.17.0 on Docker '23.0.3' ...
*
X Failed to setup kubeconfig: unable to acquire lock for {Name:mk19004591210340446308469f521c5cfa3e1599 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}: unable to open /tmp/juju-mk19004591210340446308469f521c5cfa3e1599: permission denied
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

### Operating System

Ubuntu

### Driver

None

**Comment by spowelljr** [comment]
Could you try running `sudo sysctl fs.protected_regular=0` and then try starting minikube again

**Comment by spowelljr** [comment]
Hi @shola007, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
