### ISSUE TITLE
Apply default mnikube labels to all nodes

### ISSUE THREAD

**Issue by marcellmartini** [kubernetes/minikube#16415]
### What Happened?

Minikube has a method called `kubeadm.applyNodeLabels()`, and the objective was to apply labels to all nodes, but it only applies labels to the primary node.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11369187/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by marcellmartini** [comment]
Hi @spowelljr, is there anything else that I have to do on this issue? Let me know if anything is missing. :smile:  :+1:

**Comment by spkane** [comment]
> Hello @spkane, it seems that setting custom labels on setup configurations might not be possible.

Ahh. That makes sense. I appreciate the clarification.

I was hoping that this was related to some config option that would apply these labels to the nodes during setup, but this helps explain why I couldn't figure it out.
