### ISSUE TITLE
Unable to install K8s 1.27.1 using Apple M1 (macOS 13.3.1)

### ISSUE THREAD

**Issue by conradwt** [kubernetes/minikube#16411]
### What Happened?

https://gist.github.com/conradwt/3dd2284df56b2b1d71a196a14ce062df

### Attach the log file

https://gist.github.com/conradwt/f19b00adea0ebe8b7509d9bb8ec49eb1

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @conradwt, it looks like you caught our v1.27.1 preload in a bad state, could you run `rm -rf ~/.minikube/cache/preloaded-tarball` to clear them out. Then run `minikube delete -p test-cluster` to delete your cluster and then try starting it again. If you want to downgrade your Kubernetes version you need to delete the cluster first.

**Comment by spowelljr** [comment]
I just tried v1.27.1 & v1.26.4 and the preloads look fine to me, make sure you run `minikube delete --all --purge` on both the machines to ensure your cached preloads are removed.
