### ISSUE TITLE
Minikube start

### ISSUE THREAD

**Issue by youngmind01** [kubernetes/minikube#16432]
### What Happened?

Exiting due to RUNTIME_ENABLE: Failed to enable container runtime: sudo systemctl restart cri-docker.socket: Process exited with status 1
stdout:

stderr:
Job failed. See "journalctl -xe" for details.

### Attach the log file

can't pull the log file

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
We've seen this has started occurring, if you try `minikube delete` and then try `minikube start` again does it resolve it?

**Comment by pushpendras21** [comment]
After minikube delete, executing minikube start, getting below error or issues
  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...

❌  Exiting due to RUNTIME_ENABLE: Failed to enable container runtime: sudo systemctl restart docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by spowelljr** [comment]
If you run `minikube ssh -- sudo systemctl status docker.service` could you upload the output

**Comment by JohSchillerEmnify** [comment]
Not the original poster but a very similar issue is mentioned here https://github.com/kubernetes/minikube/issues/16185
which i can confirm is happening on my machine too. 
the output of the requested command is: 
```
❯ minikube ssh -- sudo systemctl status docker.service
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Wed 2023-05-17 15:52:59 UTC; 1s ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 496 ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --labe
l provider=docker --insecure-registry 10.96.0.0/12 (code=exited, status=1/FAILURE)
   Main PID: 496 (code=exited, status=1/FAILURE)
        CPU: 106ms

May 17 15:52:59 minikube systemd[1]: docker.service: Scheduled restart job, restart counter is at 3.
May 17 15:52:59 minikube systemd[1]: Stopped Docker Application Container Engine.
May 17 15:52:59 minikube systemd[1]: docker.service: Start request repeated too quickly.
May 17 15:52:59 minikube systemd[1]: docker.service: Failed with result 'exit-code'.
May 17 15:52:59 minikube systemd[1]: Failed to start Docker Application Container Engine.

```
On the surface appears to be an issue with some rate limiting for the start request.

**Comment by chronicc** [comment]
minikube writes the storage-driver option both in the systemd file and in the `daemon.json` hence the process can not start.

```shell
dockerd[31088]: unable to configure the Docker daemon with file /etc/docker/daemon.json: the following directives are specified both as a flag and in the configuration file: storage-driver: (from flag: overlay2, from file: overlay2)
```

**Comment by prezha** [comment]
pr #17907 should fix the [original](https://github.com/kubernetes/minikube/issues/16432#issue-1695053498) problem reported

others mentioned here (about failing to restart the docker service) are probably unrelated to this one, and if so, should be in a separate issue
