### ISSUE TITLE
Unable to use buildx git context with docker-env and docker driver

### ISSUE THREAD

**Issue by Yeep** [kubernetes/minikube#16449]
### What Happened?

With minikube started using the Docker driver and the environment primed with:

`eval $(minikube -p minikube docker-env)`

I am unable to use the new-ish feature of Docker buildx to use a git repository as an additional context.

For example with the very simple Dockerfile

`FROM alpine AS base`

The docker build command

`docker buildx build --build-context base=https://github.com/kubernetes/minikube.git .`

Results in the error

```
------
 > [internal] load git source https://github.com/kubernetes/minikube.git:
------
ERROR: failed to solve: failed to load cache key: failed to init repo at /var/lib/docker/overlay2/2g1g0nug9ywqdhfi6telb4m1g/diff: exec: "git": executable file not found in $PATH
```

I think this is because the kicbase image doesn't contain the git command. Is there any workaround for this?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11405579/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
You could either install git on the node (with apt), or clone the repo on the host and mount it
