### ISSUE TITLE
Allow configuring kubernetes from `minikube config`

### ISSUE THREAD

**Issue by tristanpemble** [kubernetes/minikube#1644]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

It would be valuable to my team to be able to hardcode values that are passed to `--extra-config` flag into a configuration file. As far as I can tell, we are currently unable to do this with `minikube config` or the `~/.minikube/config/config.json`. Maybe it would use a different file (like `~/.minikube/config/kubernetes.json` or something)

**Comment by r2d4** [comment]
I think we originally didn't do this because viper had issues with parsing string slices, but I'm sure that has since been resolved.  We should definitely look into this now - the extra-config flag would be a prime candidate for the config file.

**Comment by sp-joseluis-ledesma** [comment]
I think this would be a nice feature and should not be rotten ^^
