### ISSUE TITLE
Can't start minikube

### ISSUE THREAD

**Issue by mosuqi69** [kubernetes/minikube#16455]
### What Happened?

Can't start minikube ubuntu 2204

[logs.txt](https://github.com/kubernetes/minikube/files/11410675/logs.txt)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/11410674/logs.txt)

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by JohSchillerEmnify** [comment]
related to  https://github.com/kubernetes/minikube/issues/16185
