### ISSUE TITLE
dashboard

### ISSUE THREAD

**Issue by EZEBUILO** [kubernetes/minikube#16457]
how do i add minikube dashboard

**Comment by iPraveenParihar** [comment]
You can open/enable dashboard add-on by using the command
`minikube dashboard`

Check - [minikube dashboard](minikube.sigs.k8s.io/docs/handbook/dashboard)

**Comment by EZEBUILO** [comment]
0s
##[debug]Evaluating condition for step: 'Build with Ant'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Build with Ant
##[debug]Loading inputs
##[debug]Loading env
Run ant -noinput -buildfile build.xml
##[debug]/usr/bin/bash -e /home/runner/work/_temp/a36db6bf-[1](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:1)a54-4[2](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:2)9b-ae[4](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:4)a-d4a8[7](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:7)e[8](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:8)d1eca.sh
Build failed
Buildfile: build.xml does not exist!
**Error: Process completed with exit code 1.**
##[debug]Finishing: Build with Ant

please how can i resolve this error

**Comment by EZEBUILO** [comment]
INFO] Compiling 1 source file with javac [debug release 17] to target\classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.818 s
[INFO] Finished at: 2023-07-18T10:59:56+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project demojenkins: Fatal error compiling: error: release version 17 not supported -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
'cmd' is not recognized as an internal or external command,
operable program or batch file.
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE

please how can i resolve this error
