### ISSUE TITLE
Invalid argument error during startup

### ISSUE THREAD

**Issue by ash2k** [kubernetes/minikube#1648]
**Minikube version** (use `minikube version`):
v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
Ubuntu trusty
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
none
- **Install tools**:
- **Others**:

**What happened**:
I'm trying to configure minikube to run during Travis CI build. It fails:
```shell
./minikube start --vm-driver=none --v=3 --use-vendored-driver --kubernetes-version=v1.7.0-alpha.2
Starting local Kubernetes v1.7.0-alpha.2 cluster...
Starting VM...
Creating CA: /home/travis/.minikube/certs/ca.pem
Creating client certificate: /home/travis/.minikube/certs/cert.pem
Moving files into cluster...
Downloading localkube binary
 107.29 MB / 107.29 MB [============================================] 100.00% 0s
E0624 13:48:42.946876    4388 start.go:155] Error updating cluster:  Error copying file to target location, do you have the correct permissions?: invalid argument
```

**What you expected to happen**:
It should start properly.

**How to reproduce it** (as minimally and precisely as possible):
See this build https://travis-ci.org/atlassian/smith/builds/246548706

**Comment by ash2k** [comment]
I've just cloned the repo and found the message string. It comes from this function:
```go
func CopyFileLocal(f CopyableFile) error {
	os.MkdirAll(f.GetTargetDir(), os.ModePerm) // <- ERROR NOT CHECKED
	targetPath := filepath.Join(f.GetTargetDir(), f.GetTargetName())
	os.Remove(targetPath) // <- ERROR NOT CHECKED
	target, err := os.Create(targetPath) // <- ERROR NOT CHECKED
	defer target.Close() // <- ERROR NOT CHECKED - see https://joeshaw.org/dont-defer-close-on-writable-files/

	perms, err := strconv.Atoi(f.GetPermissions())
	if err != nil {
		return errors.Wrap(err, "Error converting permissions to integer")
	}
	target.Chmod(os.FileMode(perms)) // <- ERROR NOT CHECKED
	if err != nil {
		return errors.Wrap(err, "Error changing file permissions")
	}

	_, err = io.Copy(target, f)
	if err != nil {
		return errors.Wrap(err, "Error copying file to target location, do you have the correct permissions?")
	}
	return nil
}
```
I guess the cause may be hidden in one of those places where error handling is not done properly...

**Comment by aaron-prindle** [comment]
Thanks for the suggestions! I will make these changes #1653.  I'm guessing that the issue here is that the `none` driver requires sudo as the k8s components it runs require elevated permissions when run on the host for the `none` driver.  We are going to add documentation for this soon.  This is not the case when running the components in a VM.
