### ISSUE TITLE
Build minikube use alternative registry

### ISSUE THREAD

**Issue by wiselyman** [kubernetes/minikube#1649]
In China , we have some issues with using minikube，so I replace  all`gcr.io/google-containers` with `registry.cn-hangzhou.aliyuncs.com/google-containers`,and build minikube myself.

The build process was very success,But It seems do not work。`kubectl get pod`->`no resources found`

Is there something wrong to finish this job?thanks!

**Comment by r2d4** [comment]
Can you try a `minikube logs` or `kubectl get pod --all-namespaces`?  By default there should be nothing running in the `default` namespace, only the `kube-system` namespace

**Comment by wiselyman** [comment]
@r2d4 you mean i did the right thing?
```
wangyunfeideMBP:out wangyunfei$ kubectl get pod --all-namespaces
NAMESPACE     NAME                          READY     STATUS             RESTARTS   AGE
kube-system   kube-addon-manager-minikube   1/1       Running            0          2m
kube-system   kube-dns-4152496403-244bc     0/3       ErrImagePull       0          1m
kube-system   kubernetes-dashboard-fmvc8    0/1       ImagePullBackOff   0          1m
```
but I already change the image of `kube-dns` and `kubernetes-dashboard` in `kube-dns-controller.yaml` and `dashboard-rc.yaml`

**Comment by wiselyman** [comment]
@r2d4 I perhaps find the reason，the registry `registry.cn-hangzhou.aliyuncs.com` do not have the latest images.I try now, if success，I will close the issue

**Comment by wiselyman** [comment]
@r2d4 thanks ,everything is ok, the reason is that registry registry.cn-hangzhou.aliyuncs.com do not have the latest images
