### ISSUE TITLE
Issue #12360 Not Fixed.  csi-hostpath-sc persistent volume permissions still 750 on multi node cluster

### ISSUE THREAD

**Issue by darint00** [kubernetes/minikube#16507]
### What Happened?

If minikube cluster has 2+ nodes the persistent volumes get mounted as  750.  So Only root can make modifications.  node (minikube) has 777 permissions but minikube-m02 and others have 750.  The csi-hostpath-sc has the same issue.

I'm using minkube v1.30.1

This makes it difficult to install helm charts/applications that need to use persistent volumes.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11482451/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by caerulescens** [comment]
@darint00 did you ever find a work around for this?
