### ISSUE TITLE
No external exposure of the secure api endpoint?

### ISSUE THREAD

**Issue by ggn06awu** [kubernetes/minikube#1650]
BUG REPORT 

**Minikube version**
v0.20.0

**Environment**:
- **OS**
NAME="Ubuntu"
VERSION="16.10 (Yakkety Yak)"

- **VM Driver** 
virtualbox

- **ISO version**
~.minikube/cache/iso/minikube-v0.20.0.iso

**What happened**:
I'm trying to prove out a CI / CD pipeline, but our Gitlab is hosted externally, so I want to provide the secure endpoint, rather than the insecure one through my network. I've found kubectl proxy can expose my API on port 8001, but this is highly insecure to leave open. There doesn't appear to be a way to expose https://192.168.99.100:8443 which carries the appropriate cert authentication. 

**What you expected to happen**:
kubectl proxy exposes if not both, only the secure API endpoint. 

**How to reproduce it** (as minimally and precisely as possible):
minikube start
kubectl proxy

**Anything else do we need to know**:
I know minikube isn't meant for production, but authentication ought to be part of the developers journey to production. This is also a use case where I feel i'm working as a developer, in developer mode, but can't work safely with my small Minikube machine outside of my immediate network. Have I missed something in the documentation?

**Comment by r2d4** [comment]
I'm not sure of what exactly we could do here.  Maybe an ssh tunnel and  set up the certs correctly?

**Comment by dlorenc** [comment]
Closing for now, I don't really see this as something we should handle in minikube itself.
