### ISSUE TITLE
minikube status kubectl entry always misconfigured for none driver

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1652]
For the `minikube --vm-driver=none` option, `minikube status` always shows that kubectl is misconfigured even when this is not the case.  We should fix this so that the kubectl entry is correct for the `none` driver.

**Comment by gabrielgrant** [comment]
this seems to still be the case in v0.30.0 -- the status command reports that kubectl is misconfigured:

```
$ minikube status
minikube: Running
cluster: Running
kubectl: Misconfigured: pointing to stale minikube-vm.
To fix the kubectl context, run minikube update-context
```

Despite kubectl working fine to connect to the minikube cluster:
```
$ kubectl get all
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   1d
```

Furthermore, following the advice to run `minikube update-context` actually seems to break the connection:

```
$ minikube update-context
Reconfigured kubeconfig IP, now pointing at 142.93.30.44
$ kubectl get all
Unable to connect to the server: x509: certificate is valid for 178.128.176.122, 10.96.0.1, 10.0.0.1, not 142.93.30.44
```

/remove-lifecycle rotten

**Comment by maistrotoad** [comment]
This is still very much alive on `minikube version: v1.7.3`

Including the advice to `minikube update-context`

after which there will be TLS issues with my helm and skaffold; `TLS handshake timeout`

**Comment by mfyuce** [comment]
As the "minikube status" output suggests "minikube update-context" fixes the problem
