### ISSUE TITLE
exit status 126

### ISSUE THREAD

**Issue by leebenson** [kubernetes/minikube#1655]
**BUG REPORT**

**Minikube version** (use `minikube version`):

v0.20.0

**Environment**:

- **OS** (e.g. from /etc/os-release):

macOS Sierra 10.12.6 beta

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):

> cat: /Users/leebenson/.minikube/machines/minikube/config.json: No such file or directory

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):

> cat: /Users/leebenson/.minikube/machines/minikube/config.json: No such file or directory

- **Install tools**:

I used `brew` to install, per your OS X instructions.

**What happened**:

Minikube fails to start:

> ➜  machines minikube start
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
E0627 16:10:25.115099   19876 start.go:127] Error starting host: Error creating host: Error executing step: Running precreate checks.
: exit status 126.

 Retrying.
E0627 16:10:25.116242   19876 start.go:133] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: exit status 126

**What you expected to happen**:

The VM to start and minikube to fire up.

**How to reproduce it** (as minimally and precisely as possible):

1. `brew cask install minikube`
2. `minikube start`

**Anything else do we need to know**:

I have Google Cloud CLI tools installed locally, with `kubectl` currently pointing to a server config. Could that have anything to do with it?

**Comment by cu12** [comment]
@leebenson I think a `minikube -v10 start` would provide some valuable information about your issue :)

**Comment by leebenson** [comment]
Thanks @cu12. I'm missing VBox locally. That should solve it.

**Comment by leebenson** [comment]
Although I do note in the docs:

> Minikube embeds VirtualBox and VMware Fusion drivers so there are no additional steps to use them

Shouldn't virtualbox have been installed automatically along with minikube?

**Comment by cu12** [comment]
It's about that Minikube works well with these virtual machines, but that doesn't mean that you don't have to install them.

**Comment by leebenson** [comment]
Understood. It's just that the docs say:

> However, other drivers require an extra binary to be present in the host PATH.

... which makes it sound like the driver _and_ software binaries are bundled with minikube.

**Comment by luxcn** [comment]
why docker ce don't nend vmbox,but Minikube need?
