### ISSUE TITLE
`minikube image build` does not fail on docker build error

### ISSUE THREAD

**Issue by WoodyWoodsta** [kubernetes/minikube#16576]
### What Happened?

If I run `minikube image build ...` and the docker build fails in minikube, the commandline returns with an exit code of 0, indicating that nothing went wrong.

I would have expected it to return a non-zero exit code if the docker build failed.

### Attach the log file

N/A

### Operating System

macOS (Default)

### Driver

Docker

**Comment by alexjorgef** [comment]
I'm using Minikube 1.30.1, same problem with Arch and docker driver.

**Comment by goldmann** [comment]
Affected as well:
```
$ minikube version
minikube version: v1.30.1
commit: 08896fd1dc362c097c925146c4a0d0dac715ace0
```

**Comment by alexjorgef** [comment]
Instead of using the Minikube cli (`minikube image build .`), using docker, error codes can be catch:

````sh
eval "$(minikube docker-env)"
docker buildx build .
eval "$(minikube docker-env --unset)"
```

**Comment by afbjorklund** [comment]
The main reason for this was that the code was copied from `minikube image load`, where a failure wasn't (as) fatal.

It will say which nodes failed to build in the verbose output, but I don't think it propagates the error code properly...
