### ISSUE TITLE
Running minikube under WSL2 Ubuntu 22.04 Image causes error: Exiting due to MK_USAGE: Sorry, you cannot use privileged ports on the host (below 1024): 80

### ISSUE THREAD

**Issue by davidfdr** [kubernetes/minikube#16621]
### What Happened?

Running the following under WSL2 Ubuntu 22.04 (Windows 11):
```bash
 minikube start --addons=ingress --ports=80:80,443:443 --driver=docker
```

Causes:
```
😄  minikube v1.30.1 on Ubuntu 22.04 (amd64)
✨  Using the docker driver based on user configuration

❌  Exiting due to MK_USAGE: Sorry, you cannot use privileged ports on the host (below 1024): 80
```

Running with sudo --force works ok:

```bash
sudo minikube start --addons=ingress --ports=80:80,443:443 --driver=docker --force
```

BUT I can't run with sudo privileges here.

### Attach the log file

❯ minikube start --addons=ingress --ports=80:80,443:443 --driver=docker
😄  minikube v1.30.1 on Ubuntu 22.04 (amd64)
✨  Using the docker driver based on user configuration

❌  Exiting due to MK_USAGE: Sorry, you cannot use privileged ports on the host (below 1024): 80

### Operating System

Ubuntu

### Driver

Docker

**Comment by rmsilva1973** [comment]
Hi. That's how unix systems work in general. You can't make a process bind to a port below 1024 with non-root user. It's not an issue with minikube.
