### ISSUE TITLE
just a feedback

### ISSUE THREAD

**Issue by clement2019** [kubernetes/minikube#16620]
### What Happened?

it is possible to have the docker driver installed while the minikube was installing , just like the kubectl configuration that came with it i didnt have to install that separately, like it could not installed i had to start my docker Deskstop locally on my machine. Its just an observation . but am fine with it.

secondly, although minikube worked but it kept on bringing this alert message 

You are trying to run the amd64 binary on an M1 system.                                               │
│    Please consider running the darwin/arm64 binary instead.                                              │
│    Download at https://github.com/kubernetes/minikube/releases/download/v1.30.1/minikube-darwin-arm64    │
│                            

### Attach the log file

none

### Operating System

macOS (Default)

### Driver

Docker

**Comment by caerulescens** [comment]
@clement2019 The error you're receiving indicates that you have installed the incorrect minikube binary for your computer processor's architecture type; your laptop has an Apple M1 processor which uses arm64 for its processor's instruction set, which is also known as aarch64. You installed the minikube binary for 64-bit x86 architecture processors. When Apple switched from purchasing Intel processors to designing their own chips, their processor's architecture type changed from 64-bit x86 (amd64) to 64-bit arm (arm64). Apple computers with M series processors need to install the darwin/arm64 minikube binary. You should use either [Homebrew](https://formulae.brew.sh/formula/minikube) or [MacPorts](https://ports.macports.org/port/minikube/) to manage your minikube installation, and you won't have this issue going forward.

You need to install `docker` and `minikube` to run `minikube start --driver=docker`; you also need to install the correct binary as I mentioned.

**Comment by caerulescens** [comment]
This is not an issue with `minikube`; an `amd64` binary was being run on `arm64` host.

/close
