### ISSUE TITLE
qemu: avoid retrying when there is permission errror

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#16647]
### What Happened?

here we should have detected the error type and avoid retrying

```
$ minikube start --driver=qemu
😄  minikube v1.30.1 on Darwin 13.4 (arm64)
✨  Using the qemu2 driver based on user configuration
🌐  Automatically selected the socket_vmnet network
👍  Starting control plane node minikube in cluster minikube
🔥  Creating qemu2 VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...- OUTPUT: 
ERROR: Failed to connect to "/var/run/socket_vmnet": Permission denied


🔥  Deleting "minikube" in qemu2 ...
🤦  StartHost failed, but will try again: creating host: create: creating: Failed to connect to "/var/run/socket_vmnet": Permission denied: exit status 1
🔥  Creating qemu2 VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...- OUTPUT: 
ERROR: Failed to connect to "/var/run/socket_vmnet": Permission denied


😿  Failed to start qemu2 VM. Running "minikube delete" may fix it: creating host: create: creating: Failed to connect to "/var/run/socket_vmnet": Permission denied: exit status 1

❌  Exiting due to PR_QEMU_SOCKET_VMNET_DENIED: Failed to start host: creating host: create: creating: Failed to connect to "/var/run/socket_vmnet": Permission denied: exit status 1
💡  Suggestion: socket_vmnet was installed with an incorrect group, delete this cluster 'minikube delete' and update the group 'sudo chown root:$(stat -f "%Sg" ~) /var/run/socket_vmnet' and try again.
```

### Attach the log file

n/a

### Operating System

None

### Driver

None

**Comment by ShardulPrabhu** [comment]
> $ minikube start --driver=qemu
> 😄  minikube v1.30.1 on Darwin 13.4 (arm64)
> ✨  Using the qemu2 driver based on user configuration
> 🌐  Automatically selected the socket_vmnet network
> 👍  Starting control plane node minikube in cluster minikube
> 🔥  Creating qemu2 VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...- OUTPUT: 
> ERROR: Failed to connect to "/var/run/socket_vmnet": Permission denied
> 
> 
> 🔥  Deleting "minikube" in qemu2 ...
> 🤦  StartHost failed, but will try again: creating host: create: creating: Failed to connect to "/var/run/socket_vmnet": Permission denied: exit status 1
> 🔥  Creating qemu2 VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...- OUTPUT: 
> ERROR: Failed to connect to "/var/run/socket_vmnet": Permission denied
> 
> 
> 😿  Failed to start qemu2 VM. Running "minikube delete" may fix it: creating host: create: creating: Failed to connect to "/var/run/socket_vmnet": Permission denied: exit status 1
> 
> ❌  Exiting due to PR_QEMU_SOCKET_VMNET_DENIED: Failed to start host: creating host: create: creating: Failed to connect to "/var/run/socket_vmnet": Permission denied: exit status 1
> 💡  Suggestion: socket_vmnet was installed with an incorrect group, delete this cluster 'minikube delete' and update the group 'sudo chown root:$(stat -f "%Sg" ~) /var/run/socket_vmnet' and try again.

try to run 

'''sudo chown root:$(stat -f "%Sg" ~) /var/run/socket_vmnet'''

**Comment by caerulescens** [comment]
@medyagh Is this still an issue? I ran `minikube start --driver=qemu2` on `Darwin 13.6.3 (arm64)` using `minikube v1.32.0`, and `socket_vmnet` was selected automatically. `minikube start --driver=qemu2 --network=socket_vmnet` works too. I think this can be closed unless I'm missing something here.
