### ISSUE TITLE
How minikube set to pass systemd.SdNotify?

### ISSUE THREAD

**Issue by jiangxiaobin96** [kubernetes/minikube#16657]
### What Happened?

How minikube set to pass systemd.SdNotify?
I found that my code blocked on `systemd.SdNotify` running on the minikube. `systemd.SdNotify` will confirm weather running on a systemd system, it seems that minikube runs like a VM. So I tried start command `minikube start --force --driver=docker --force-systemd` to enable systemd but it does not work. 

### Attach the log file

None

### Operating System

None

### Driver

None

**Comment by ShardulPrabhu** [comment]
If you want to use systemd inside the Minikube VM, you can try using the --docker-env flag to pass environment variables to the Docker daemon running inside the VM. 

`minikube start --driver=docker --docker-env=DOCKER_OPTS="--exec-opt native.cgroupdriver=systemd"`
