### ISSUE TITLE
Better mechanism needed for configuring VirtualBox driver versions

### ISSUE THREAD

**Issue by mm0** [kubernetes/minikube#16691]
Background
---
VirtualBox relies of the installation of "Guest Additions" drivers and utilities which are typically installed by using an installation script provided by VirtualBox.  These drivers, among other things, provide the ability to mount shared directories from host->guest.  Typically, the version of the Guest Additions installer should match the version of VirtualBox itself.
  
Problem 
---
Unfortunately, this version is currently being hardcoded into the build of the iso (see below), resulting in a potential mismatch of versions.  The version currently being used is and older 5.2.42, whereas VirtualBox latest stable version is 7.0.8. This can lead to instabilities.  Even more unfortunate is that it is impossible to manually upgrade the drivers as bzip2, make and dependencies are missing from the VM.  

https://github.com/kubernetes/minikube/blob/64588b21db4a1685dbb0246c4598289ad93dce3e/deploy/iso/minikube-iso/arch/x86_64/package/vbox-mount-service/vbox-mount-service.mk#L6

Temporary Solution
---
At the very least, include bzip2, make and the dependencies needed to upgrade the guest additions manually.

Permanent Solution
---
TBD

**Comment by afbjorklund** [comment]
Typically the VirtualBox additions were backwards-compatible, and kept at some old "LCM" version

**Comment by mm0** [comment]
> If you need any tools to manipulate the VM host, they can be installed through the `toolbox` command.

Thanks, these are device drivers though, can this be done in a persistent way using the toolbox?

**Comment by mm0** [comment]
> Typically the VirtualBox additions were backwards-compatible, and kept at some old "[LCD](https://en.wikipedia.org/wiki/Lowest_common_denominator)" version

Does this mean we can potentially just update VBOX_MOUNT_SERVICE_VERSION to a more recent version?

**Comment by afbjorklund** [comment]
As far as I know, the kernel extensions moved to the upstream version - and only the service remained.

**Comment by afbjorklund** [comment]
Bumping from 5.2.42 to 6.1.44 should be fine, going to 7.0 might exclude some current systems
