### ISSUE TITLE
getting error starting minikube 

### ISSUE THREAD

**Issue by vaidaman** [kubernetes/minikube#16696]
### What Happened?

❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.22.1:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.22.1
[preflight] Running pre-flight checks
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 5.3.0-1028-aws
DOCKER_VERSION: 20.10.8
DOCKER_GRAPH_DRIVER: overlay2
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: enabled
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority

stderr:
	[WARNING SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/5.3.0-1028-aws\n", err: exit status 1
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
W0613 06:20:32.215174    4525 certs.go:489] WARNING: could not validate bounds for certificate apiserver: the certificate has expired: NotBefore: 2021-09-12 13:21:49 +0000 UTC, NotAfter: 2022-09-13 13:21:49 +0000 UTC
error execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: x509: certificate has expired or is not yet valid: current time 2023-06-13T06:20:32Z is after 2022-09-13T13:21:49Z
To see the stack trace of this error execute with --v=5 or higher

### Attach the log file

jj

### Operating System

Ubuntu

### Driver

Docker

**Comment by vaidaman** [comment]
i didnt do anything special - just getting error starting minikube in that
specific environment

**Comment by kundan2707** [comment]
@vaidaman  can you reproduce it again?

**Comment by vaidaman** [comment]
i deleted the setup
cannot recreate anymore

**Comment by kundan2707** [comment]
closing as not reproducible.
