### ISSUE TITLE
Received error during create and deploy your first pod exercise within Coursera Container Orchestration using Kubernetes Coursera Project Network

### ISSUE THREAD

**Issue by JerramyBurns** [kubernetes/minikube#16705]
I received the error below "error restarting cluster" when running minikube start command. 

rhyme@ip-10-199-76-6:~/yml$ sudo minikube start --vm-driver=none
\U0001f604  minikube v1.2.0 on linux (amd64)
\U0001f4a1  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
\U0001f504  Restarting existing none VM for "minikube" ...
\u231b  Waiting for SSH access ...
\U0001f433  Configuring environment for Kubernetes v1.15.0 on Docker 19.03.6
    \u25aa kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
\U0001f504  Relaunching Kubernetes v1.15.0 using kubeadm ... 

\U0001f4a3  Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

**Comment by afbjorklund** [comment]
Please upgrade
