### ISSUE TITLE
DNS no longer working with with Kubernetes 1.3.3 after minikube upgrade

### ISSUE THREAD

**Issue by philipn** [kubernetes/minikube#1670]
**Minikube version** (use `minikube version`): v0.20.0

**Environment**: 
- **OS** (e.g. from /etc/os-release): OS X 10.12.5 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.20.0.iso
- **Install tools**:
- **Others**:

**What happened**:

When inside a pod, you cannot reach the `kubernetes` or `kubernetes.local` host.  Additionally, no `kube-dns` pod is started.

**What you expected to happen**:

I'm not sure whether or not a `kube-dns` pod is supposed to be started on Kubernetes 1.3.3, but this configuration was working prior to updating to a recent minikube version.

**How to reproduce it** (as minimally and precisely as possible):

1. Install latest minikube.
2. Enable Kubernetes 1.3.3 with `minikube config set kubernetes-version v1.3.3`
3. `minikube start`
4. Create a new deployment to test DNS with, e.g.:

Dockerfile:

```
FROM ubuntu:14.04
EXPOSE 8080
CMD exec /bin/bash -c "trap : TERM INT; sleep infinity & wait"
```

`docker build -t test-dns .`
`kubectl run test-dns --image=test-dns --port=8080`

Then:

`kubectl exec -i -t <test-dns pod> -- bash`

Inside the pod, the `kubernetes` and `kubenertes.default` names do not resolve.  Additionally, `kubectl get pods --all-namespaces` shows no kube-dns service.

As suggested in other issues, trying the virtualbox command `VBoxManage modifyvm "minikube" --natdnshostresolver1 on` makes no difference.

**Anything else do we need to know**:

Everything works fine when running with 1.6.4 (the out of box K8s default).

I'm not sure if 1.3.3 is still supported or not, or if older K8s versions should work in general. Should we expect them to break over time due to inevitable changes in the minikube architecture? If so, it might be good to disallow usage of older versions.

**Comment by r2d4** [comment]
@philipn I'm not sure what the backwards compatibility guarantees are for kube-dns, but the current version we bundle with the latest version (1.14.2) might not work with older kubes.  

You _could_ run `minikube addons disable kube-dns` and then run your own DNS configuration (something that k8s 1.3 supports).  You may also want to disable the other addons, such as `minikube addons disable dashboard` and run the appropriate version.  

This PR (https://github.com/kubernetes/minikube/pull/1527) is aimed at fixing this bad UX issue.  One idea is to bundle the addons with the kube-version we pull down, which I outlined here https://github.com/kubernetes/minikube/pull/1527#issuecomment-305247644

**Comment by philipn** [comment]
@r2d4 Thanks for the explanation! That's what I figured RE: compatibility.  I like the idea of bundling the addons with the kube version because it's more static.

It would be great if minikube upgrades never broke the underlying K8s installation, but if they had to, just knowing the upgrade would break the K8s install would be good enough.
