### ISSUE TITLE
unable to start minikube

### ISSUE THREAD

**Issue by Wellweke** [kubernetes/minikube#16719]
### What Happened?

It gives me the following result

Failed to enable container runtime: sudo systemctl restart docker: Process exited with status 1
stdout:

stderr:
Failed to restart docker.service: Unit docker.socket has a bad unit file setting.
See system logs and 'systemctl status docker.service' for details.

### Attach the log file

minikube start --driver=virtualbox

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by ShardulPrabhu** [comment]
try this
`sudo service docker restart`
