### ISSUE TITLE
[Feature Request] Support adding "Node" to minikube cluster

### ISSUE THREAD

**Issue by liuhewei** [kubernetes/minikube#1672]
Since many of K8s' features need be verified on a real "cluster" (multiple nodes), node-affinity as an example, I suggest that the Minikube provides an approach of adding node to the Minikube cluster.

For example, add a command "minikube add-node" to start a K8s Node and join the cluster. The backend handling can be similar with "minikube start" but only the binaries on Node, and then joins the cluster through "kubeadm join".

**Comment by r2d4** [comment]
Closing this in favor of #94.  We're tracking this feature request there.
