### ISSUE TITLE
worker node remains in NotReady state after reboot

### ISSUE THREAD

**Issue by bilalcaliskan** [kubernetes/minikube#16723]
### What Happened?

I have a minikube cluster with 1 master and 1 worker created by `virtualbox` driver.

Here is the version informations:
```
minikube version: v1.30.1
kubernetes version: v1.21.2
```

When i reboot the worker node, it stays in `NotReady` state. I assume that `kubelet` can not survive from something. Weird thing is that there is no `kubelet.service` systemd service on the VM created with virtualbox driver, so i can not restart or investigate the problem-causing situation.

I am trying the same scenario with `kvm2` driver right now.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11779314/log.txt)

### Operating System

Linux kali 6.1.0-kali9-amd64

### Driver

Virtualbox

**Comment by rodrigoaantunes** [comment]
I'm learning kubernetes and I'm having the same problem, is this a problem in minukube or it is a common behaviour in kubernetes?
