### ISSUE TITLE
Starting none driver w/ containerd w/o docker installed fails precheck

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#16722]
If you try doing as the title says you get the following:
```
$ minikube start --driver none --container-runtime=containerd
😄  minikube v1.30.1 on Debian 11.7 (kvm/amd64)
✨  Using the none driver based on user configuration
❗  Using the 'containerd' runtime with the 'none' driver is an untested configuration!
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=8, Memory=30095MB, Disk=9853MB) ...
🤦  StartHost failed, but will try again: creating host: create: precreate: exec: "docker": executable file not found in $PATH
🤹  Running on localhost (CPUs=8, Memory=30095MB, Disk=9853MB) ...
😿  Failed to start none bare metal machine. Running "minikube delete" may fix it: creating host: create: precreate: exec: "docker": executable file not found in $PATH

❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: precreate: exec: "docker": executable file not found in $PATH

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```

The cause is in:
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/minikube/machine/start.go#L135-L151

`runtime` is a private func in the none driver struct
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/drivers/none/none.go#L47-L53

So when the `Marshal` occurs, the runtime data doesn't get passed
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/minikube/machine/start.go#L143

In `NewHost`
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/minikube/machine/client.go#L98

Which calls
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/minikube/registry/drvs/none/none.go#L39

Which calls
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/drivers/none/none.go#L65

And since `Type` is not set, defaults to Docker CRI
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/minikube/cruntime/cruntime.go#L209-L213

So then
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/drivers/none/none.go#L81-L83

And since the runtime is now Docker calls
https://github.com/kubernetes/minikube/blob/ad4acb0186a20f83472c7810dd446f84b3f8765d/pkg/minikube/cruntime/docker.go#L110-L125

It actually skips the `cri-dockerd` and `dockerd` checks because nothing is passed in when the CRI is created so it defaults to `v0.0.0`.

**Comment by afbjorklund** [comment]
Right, it is the old bug in the minikube driver registry again (registering all drivers twice)

* https://github.com/kubernetes/minikube/issues/5549
