### ISSUE TITLE
/etc/docker/daemon.json content has been overwritten and unable to pull images.

### ISSUE THREAD

**Issue by wslky** [kubernetes/minikube#16733]
### What Happened?

I have configured Docker as follows.
```
cat > /etc/docker/daemon.json <<EOF
{
  "exec-opts": ["native.cgroupdriver=systemd"],
  "registry-mirrors": ["https://registry.cn-hangzhou.aliyuncs.com"]
}
EOF
```
When I run `minikube start --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --driver=none`, everything works fine, but I am unable to pull images correctly.

I checked the `/etc/docker/daemon.json` file, and the content has been changed to
```
{
"exec-opts": ["native.cgroupdriver=cgroupfs"],
"log-driver": "json-file",
"log-opts": {
        "max-size": "100m"
},
"storage-driver": "overlay2"
}
```
It is causing me to be unable to pull images.

### Attach the log file

Name:             nginx-pod
Namespace:        default
Priority:         0
Service Account:  default
Node:             master/192.168.31.106
Start Time:       Mon, 19 Jun 2023 13:34:06 -0400
Labels:           <none>
Annotations:      <none>
Status:           Pending
IP:               10.244.0.33
IPs:
  IP:  10.244.0.33
Containers:
  nginx:
    Container ID:   
    Image:          nginx:latest
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-d4rpv (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-d4rpv:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  18m                  default-scheduler  Successfully assigned default/nginx-pod to master
  Warning  Failed     13m                  kubelet            Failed to pull image "nginx:latest": rpc error: code = Canceled desc = context canceled
  Normal   Pulling    9m13s (x4 over 18m)  kubelet            Pulling image "nginx:latest"
  Warning  Failed     6m21s (x4 over 15m)  kubelet            Error: ErrImagePull
  Warning  Failed     6m21s (x2 over 10m)  kubelet            Failed to pull image "nginx:latest": rpc error: code = Unknown desc = error pulling image configuration: download failed after attempts=6: dial tcp 104.18.124.25:443: i/o timeout
  Warning  Failed     5m56s (x7 over 15m)  kubelet            Error: ImagePullBackOff
  Normal   BackOff    5m42s (x8 over 15m)  kubelet            Back-off pulling image "nginx:latest"
  Warning  Failed     109s (x2 over 15m)   kubelet            Failed to pull image "nginx:latest": rpc error: code = Unknown desc = error pulling image configuration: download failed after attempts=6: dial tcp 104.18.121.25:443: i/o timeout

### Operating System

Redhat/Fedora

### Driver

None
```[tasklist]
### Tasks
```

**Comment by acxxca** [comment]
so what happened？how to prevent Minikube from modifying /etc/docker/daemon.json?
