### ISSUE TITLE
DNS lookup not working when starting minikube with --dns-domain

### ISSUE THREAD

**Issue by soemeier** [kubernetes/minikube#1674]
**Minikube version** 0.19.1

**Environment**:
- **OS** MAC OS 10.11.4
- **VM Driver** virtualbox
- **ISO version** minikube-1.13.1-3.iso:
- **Install tools**:
- **Others**:

**What happened**:
If I start minikube with --dns-domain the dns entries that are registered are still registered with the domain cluster.local

**What you expected to happen**:
I would expect that the dns entries are registered with domain provided in the startup parameters.

**How to reproduce it** (as minimally and precisely as possible):
Start minikube with ```--dns-domain test.cluster.local```
do ```nslookup kubernetes.default.svc.test.cluster.local 10.0.0.1``` -> does not work
do ```nslookup kubernetes.default.svc.cluster.local 10.0.0.1``` -> works but is not expected to work

**Anything else do we need to know**:
To me it looks like this is caused by the hard coded cluster.local in https://github.com/kubernetes/minikube/blob/master/deploy/addons/kube-dns/kube-dns-controller.yaml

**Comment by r2d4** [comment]
Looks like we need to propagate the --dns-domain flag into the dns addon.  I think this should be doable on minikube start.

**Comment by adv-tsk** [comment]
Also if I start minikube with the `--extra-config=kubelet.ClusterDomain=mydomain.com` the dns records are still registered with the `cluster.local` suffix.

**Comment by iMartyn** [comment]
Given that modern distros claim `.local` for avahi (grmbl grmbl) changing the dns name is kinda important for routing into the cluster (It's not like we can use ELBs in minikube).  I feel this should be a high priority issue.

**Comment by reymont** [comment]
This is my work around. 

```sh
# enable dns
$ minikube stop
$ minikube addons enable kube-dns
$ minikube start
$ minikube addons list
$ eval $(minikube docker-env)

$ kubectl get svc kube-dns -n kube-system
NAME       TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)         AGE
kube-dns   ClusterIP   10.96.0.10   <none>        53/UDP,53/TCP   19d

$ minikube ssh
$ sudo vi /etc/resolv.conf
# add a line in resolv.conf
# nameserver 10.96.0.10

$ nslookup kube-dns.kube-system.svc.cluster.local
Server:    10.96.0.10
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kube-dns.kube-system.svc.cluster.local
Address 1: 10.96.0.10 kube-dns.kube-system.svc.cluster.local
```

**Comment by trobert2** [comment]
@reymont 
hod were you able to run `minikube addons enable kube-dns` after `minikube stop`?

```
$ minikube addons enable kube-dns
    minikube is not currently running so the service cannot be accessed
```

**Comment by reymont** [comment]
@trobert2 Yes, you are right. `minikube addons enable kube-dns` must execute after minikube start. I'm fix it. Thank you

**Comment by ddotpdot** [comment]
i can reproduce it with v 1.9.0 too.
The inter-pod communication doesn't work.
Inside the pod with a service named as infra-apps
nslookup infra-apps.default.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      infra-apps.default.svc.cluster.local
Address 1: 10.98.32.142 infra-apps.default.svc.cluster.local

**Comment by sunvooker** [comment]
when minikube ssh enter, then edit /etc/resolv.conf, 
then do any deployment change, will restore the nameserver to 10.0.2.3,  

anyone find it, so the method is invalid.

anyone have another.

**Comment by gitdr** [comment]
in your minikube VM:

Change /etc/systemd/resolved.conf
From:
#DNS=
To:
DNS=<IP of the DNS server>

then
sudo systemctl restart systemd-resolved

**Comment by jhgoodwin** [comment]
> in your minikube VM:
> 
> Change /etc/systemd/resolved.conf
> From:
> #DNS=
> To:
> DNS=
> 
> then
> sudo systemctl restart systemd-resolved

How do you get this sort of change to persist?  Ideally, I'd like to just copy the /etc/systemd/resolved.conf from the host.

**Comment by bparinas** [comment]
experienced the same error with minikube + win10

my workaround (followed @gitdr suggestion):

$ minikube ssh <-- git bash windows
$ sudo su - <-- within the minikube environment
# cat << EOF > /etc/systemd/resolved.conf
> [Resolve]
> DNS=8.8.8.8
> FallbackDNS=8.8.8.8 8.8.4.4
> EOF

# systemctl restart systemd-resolved

-hth

**Comment by ThisIsQasim** [comment]
I can confirm that this error still persists with the hyperkit driver on macOS. Edit systemd-resolved fixes it.

**Comment by vanyarock01** [comment]
The issue is relevant for minikube v1.12.3. [This](https://github.com/strimzi/strimzi-kafka-operator/issues/2824#issuecomment-613347654) way helped me.
```
minikube start --dns-domain='custom.domain' --extra-config='kubelet.cluster-domain=custom.domain'
```
