### ISSUE TITLE
Please provide proper package repository

### ISSUE THREAD

**Issue by dhs-rec** [kubernetes/minikube#16744]
### What Happened?

Installation instructions for Debian tell people to download a deb package and install it using `dpkg`, which is wrong in many ways:

- not having a proper package repository makes updates quite cumbersome
- using `dpkg` instead of `apt` or `apt-get` doesn't resolve dependencies

Please provide  a proper package repository and update installation instructions accordingly.

Thanks a lot.

### Attach the log file

N/A

### Operating System

Ubuntu

### Driver

N/A

**Comment by afbjorklund** [comment]
Unfortunately, the project was never able to host proper package repositories for apt and yum... 😔

* https://github.com/kubernetes/minikube/issues/3110

There might be some new possibilities, after Kubernetes moves everything to OBS
