### ISSUE TITLE
Cadvisor Metrics Label contain empty Strings as values (container="", image="",...)

### ISSUE THREAD

**Issue by Feederhigh5** [kubernetes/minikube#16742]
### What Happened?

I want to analyze the resource consumption (CPU, Network, Memory, I/O) on container level.
As far as I know, these metrics are generated by cadvisor and exposed at https://kubernetes.default.svc/api/v1/nodes/minikube/proxy/metrics/cadvisor. 

I check them through the following command: `kubectl get --raw /api/v1/nodes/minikube/proxy/metrics/cadvisor` 

My problem is, that the necessary container label (among others like image and name) are empty strings. That prevents me from analyzing the resource consumption per container.
For example:
```
container_network_receive_bytes_total{container="",id="/",image="",interface="bridge",name="",namespace="",pod=""} 2.90072711e+08 1687270944453
```
```
container_memory_working_set_bytes{container="",id="/kubepods/pod49686167-c619-4f80-bfd7-5bacc76e2e47",image="",name="",namespace="logging",pod="kibana-kibana-749869bc5c-4dgmt"} 4.0378368e+08 1687269135477
```

How do I configure cadvisor (or check if cadvisor is correctly configured)?
Do you have a suggestion how I could get these metrics?

I would highly appreciate help! If you need any more info, let me know.
Thank you :)

### Attach the log file

[minikube_log.txt](https://github.com/kubernetes/minikube/files/11801999/minikube_log.txt)

### Operating System

Windows

### Driver

Docker

**Comment by mdamour1976** [comment]
Seeing the same issue.  When using --kubernetes-version=v1.23.17 it works, so something changed between then and v1.24.x (and present).

**Comment by davidmirza408** [comment]
I am experiencing the same problem

**Comment by HarshitRaj** [comment]
Try containerd as the container runtime when starting minikube.
I believe K8 1.23+ or 1.24+ (not sure which exactly) but containerd has been the default container runtime.
In my local i was facing the same issue (default it took docker runtime), so i switched to containerd

minikube start --container-runtime=containerd
