### ISSUE TITLE
Fail to check files update in container using `hostPath` volume by `head` command

### ISSUE THREAD

**Issue by hanks** [kubernetes/minikube#1675]
BUG REPORT

**Minikube version** (use `minikube version`):
v0.20.0

**Environment**:
- **OS** : macOS 10.12.5
- **VM Driver**: virtualbox 5.1.22
- **ISO version** : minikube-v0.18.0.iso
- **kubectl**: client-v1.7.0, server-v1.6.4
- **base image**: alpine-3.6

**What happened**:
use `hostPath` to mount directory from macOS, and after modify some file, the latest file content in container can be shown with command `vi`, but when using `head` or `cat` command, it is still shown the old content. 

**What you expected to happen**:
`head` or `cat` command should show the latest content of file

**Anything else do we need to know**:
I use `minikube ssh` to check file mounted in the vm, both commands works correctly.

**Comment by aaron-prindle** [comment]
This is an issue with inotify.  We are tracking this here #1551.  Closing as dupe

**Comment by hasan-abdul-rahman** [comment]
@aaron-prindle in lieu of a fix for #1551 is there a way to force updating/reloading a specific file?
