### ISSUE TITLE
unblock firewall for macos one more time if it it is unblocked and macos still doesnt unblock

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#16776]
### What Happened?

unblock firewall for macos one more time if it it is unblocked and macos still doesnt unblock`

### Attach the log file

n/a

### Operating System

None

### Driver

None

**Comment by akosyakov** [comment]
> unblock firewall for macos one more time if it it is unblocked and macos still doesnt unblock`

@medyagh Hello 👋 sorry for asking out of the blue, but would it be possible to share how did you manage to reproduce such conditions?

**Comment by spowelljr** [comment]
@akosyakov You can look at the PR that implemented it https://github.com/kubernetes/minikube/pull/16789
