### ISSUE TITLE
Support rkt.

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#168]
Minikube should support building and running rkt containers.

**Comment by yifan-gu** [comment]
cc @kubernetes/sig-rktnetes

**Comment by tmrts** [comment]
I'm looking into it atm

**Comment by dlorenc** [comment]
Thanks @tmrts. Let me know if you need any help. Assuming rkt doesn't need any other dependencies, this will probably be pretty straightforward.

You'll have to grab a rkt binary in either [build.sh](https://github.com/kubernetes/minikube/blob/master/deploy/iso/build.sh) or the ISO build [Dockerfile](https://github.com/kubernetes/minikube/blob/master/deploy/iso/Dockerfile).

Then configure rkt to start at boot time, which can be done in the iso by adding a script to /etc/rc.d or something.

**Comment by dlorenc** [comment]
Any updates here @tmrts?

Anything I can do to help?

**Comment by dlorenc** [comment]
Bumping to 0.6 for now. Let me know if you won't have a chance to get to this one @tmrts

**Comment by tmrts** [comment]
@dlorenc I had to pause my work on it for issues regarding rktnetes/rkt, I'll be working on this one now :+1:

**Comment by dlorenc** [comment]
Any progress here @tmrts? Anything we can help with?

**Comment by s-urbaniak** [comment]
@dlorenc I have some progress here, we're working on it :-) I managed to install rkt in the initrd image (grows from to 37MB to 75MB, do you foresee a problem with this increase?

**Comment by dlorenc** [comment]
@s-urbaniak Awesome news!

My only concern with the size increase is that the initrd images are pretty heavily compressed. I did some experimenting awhile back on bundling more into the image and noticed that the decompression made boot time increase dramatically. Have you seen any increases there?

**Comment by s-urbaniak** [comment]
@dlorenc didn't notice dramatic increase in boot time. The only sort-of-showstopper I now have is, that the rkt-kubelet uses systemd/dbus to launch rkt containers. systemd is afaik not packaged in Tiny Core Linux.

@yifan-gu @euank As discussed, does it make sense to have a non-systemd/non-dbus version of rkt-kubelet?

**Comment by tmrts** [comment]
I investigated a minimal way to ship rkt and we can use tiny core linux or alpine linux (glibc doesn't work right away, needs manual installation) and install systemd/dbus onto those, if we need a version with systemd/dbus.

This is also partly related to boot2rkt

**Comment by s-urbaniak** [comment]
Some update for this: I managed to build a ~57MB big bootable systemd-as-pid1-based ISO image having rkt included using buildroot. I will be on vacation in the next two weeks, but after that I'll keep on making this work. The strategy then would be to use a different ISO for the rktnetes use case.

**Comment by dlorenc** [comment]
Thanks for the updates! If that new image works for the docker use-case as well, could we just use your image everywhere instead of the standard boot2docker image? We could write our own libmachine provisioner as well.

**Comment by s-urbaniak** [comment]
@dlorenc just fyi, resuming from this week. Yes, that could be possible, but I'd suggest to tackle a possible boot2docker alternative ISO in a separate issue once I have the complete cycle integrated. I am working on integrating the transfer of host generated SSH keys to the image now. I should hopefully have some progress soon.

Just FYI, here's the buildroot make config for my current (rkt) minikube ISO image: https://github.com/s-urbaniak/rktminikube. Once I am confident and validate everything this could be moved to the CoreOS org. I am also evaluating whether we also possibly could use the CoreOS ISO image.
