### ISSUE TITLE
Start minikube with a specific certificates

### ISSUE THREAD

**Issue by victory4software** [kubernetes/minikube#16805]
### What Happened?

After using my cluster I start facing issues in the certificates.

for example, if the certificate is expired we need to restart the cluster with the new certificate without losing all the data in the cluster.

### Attach the log file

minikube certificate api-server is expired

### Operating System

Ubuntu

### Driver

Docker

**Comment by aiyijing** [comment]
@victory4software Hi!  I don't know which version did you use? 
minikube should generate new one when  certificate is expired. You can restart cluster and all the data don't lose. 
there https://github.com/kubernetes/minikube/pull/16249
