### ISSUE TITLE
SIGSEGV starting localkube with `--vm-driver none`

### ISSUE THREAD

**Issue by iameli** [kubernetes/minikube#1680]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Minikube version** (use `minikube version`): v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 17.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): n/a
- **Install tools**: `minikube start --vm-driver none`
- **Others**:

**What happened**:
Localkube segfaulted. [Here's the full log from journalctl](https://gist.github.com/iameli/279fe00bbc0df9ecc4ca8c012d45837c). Y'all golang folks really know how to produce a big stack trace, and I'm not totally sure which bits are relevant, but here's the start:

```
Jul 09 14:19:27 skillet systemd[1]: Starting Localkube...
name = kubeetcd
data dir = /var/lib/localkube/etcd
member dir = /var/lib/localkube/etcd/member
heartbeat = 100ms
election = 1000ms
snapshot count = 10000
advertise client URLs = http://0.0.0.0:2379
restarting member fcf2ad36debdd5bb in cluster 7f055ae3b0912328 at commit index 7
fcf2ad36debdd5bb became follower at term 2
newRaft fcf2ad36debdd5bb [peers: [], term: 2, commit: 7, applied: 0, lastindex: 7, lastterm: 2]
starting server... [version: 3.0.17, cluster version: to_be_decided]
added member fcf2ad36debdd5bb [http://0.0.0.0:2380] to cluster 7f055ae3b0912328
set the initial cluster version to 3.0
enabled capabilities for version 3.0
localkube host ip address: 192.168.1.202
Starting apiserver...
Waiting for apiserver to be healthy...
W0709 14:19:27.998972    9841 authentication.go:362] AnonymousAuth is not allowed with the AllowAll authorizer.  Resetting AnonymousAuth to false. You should use a different authorizer
W0709 14:19:28.105722    9841 storage_codec.go:52] storage type "etcd2" does not support media type "application/vnd.kubernetes.protobuf", using "application/json"

(that line repeats lots of times, then...)

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f2c30ad8218]
runtime stack:
runtime.throw(0x3eec3db, 0x2a)
        /usr/local/go/src/runtime/panic.go:566 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:12 +0x2cc
goroutine 684 [syscall, locked to thread]:
runtime.cgocall(0x31ed880, 0xc4217aedf8, 0xc400000000)
        /usr/local/go/src/runtime/cgocall.go:131 +0x110 fp=0xc4217aedb0 sp=0xc4217aed70
net._C2func_getaddrinfo(0x7f29940008c0, 0x0, 0xc4212bb2f0, 0xc421536200, 0x0, 0x0, 0x0)
        ??:0 +0x68 fp=0xc4217aedf8 sp=0xc4217aedb0
net.cgoLookupIPCNAME(0xc42102c808, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:146 +0x37c fp=0xc4217aef18 sp=0xc4217aedf8
net.cgoIPLookup(0xc4215cbc20, 0xc42102c808, 0x9)
        /usr/local/go/src/net/cgo_unix.go:198 +0x4d fp=0xc4217aefa8 sp=0xc4217aef18
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4217aefb0 sp=0xc4217aefa8
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:208 +0xb4
```

**What you expected to happen**:
A local Kubernetes cluster, ideally

**How to reproduce it** (as minimally and precisely as possible):
```
minikube start --vm-driver none
journalctl -u localkube
```

**Anything else do we need to know**:
I know that `--vm-driver` none isn't exactly the recommended way to use minikube for local development, but I figured you'd want to know about a segfault

**Comment by iameli** [comment]
Fixed it locally by compiling using `netgo`, following the directions [here](https://github.com/prometheus/alertmanager/issues/267#issuecomment-203805157). Possibly something screwy about `getaddrinfo` on my machine? Scary thought.

**Comment by iameli** [comment]
Yeah, seems that a wide variety of things having to do with DNS are malfunctioning locally. Not an issue with minikube.

**Comment by ernstp** [comment]
I'm also running into this and I think it's a valid issue. Isn't this the static linking to glibc thing that talked about here and there regarding golang?
