### ISSUE TITLE
Error starting qemu2 VM

### ISSUE THREAD

**Issue by josetaylor06** [kubernetes/minikube#16814]
### What Happened?

Seems to be related to these dhcp connection attemps

0703 19:21:43.255376    5571 main.go:141] libmachine: STDERR: 
I0703 19:21:43.255402    5571 main.go:141] libmachine: DONE writing to /Users/jt/.minikube/machines/minikube/disk.qcow2.raw and /Users/jt/.minikube/machines/minikube/disk.qcow2
I0703 19:21:43.255407    5571 main.go:141] libmachine: Starting QEMU VM...
I0703 19:21:43.255474    5571 main.go:141] libmachine: executing: /usr/local/opt/socket_vmnet/bin/socket_vmnet_client /usr/local/var/run/socket_vmnet qemu-system-x86_64 -display none -accel hvf -m 4000 -smp 2 -boot d -cdrom /Users/jt/.minikube/machines/minikube/boot2docker.iso -qmp unix:/Users/jt/.minikube/machines/minikube/monitor,server,nowait -pidfile /Users/jt/.minikube/machines/minikube/qemu.pid -device virtio-net-pci,netdev=net0,mac=2a:f2:65:19:95:10 -netdev socket,id=net0,fd=3 -daemonize /Users/jt/.minikube/machines/minikube/disk.qcow2
I0703 19:21:43.875349    5571 main.go:141] libmachine: STDOUT: 
W0703 19:21:43.875375    5571 main.go:139] libmachine: STDERR: qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]
qemu-system-x86_64: warning: host doesn't support requested feature: CPUID.80000001H:ECX.svm [bit 2]

I0703 19:21:43.875388    5571 main.go:141] libmachine: Attempt 0
I0703 19:21:43.875418    5571 main.go:141] libmachine: Searching for 2a:f2:65:19:95:10 in /var/db/dhcpd_leases ...
I0703 19:21:43.875856    5571 main.go:141] libmachine: Found 1 entries in /var/db/dhcpd_leases!
I0703 19:21:43.875885    5571 main.go:141] libmachine: dhcp entry: {Name:minikube IPAddress:192.168.105.2 HWAddress:ee:fc:78:b8:e9:2a ID:1,ee:fc:78:b8:e9:2a Lease:0x64a4b22d}
I0703 19:21:45.876815    5571 main.go:141] libmachine: Attempt 1
I0703 19:21:45.876864    5571 main.go:141] libmachine: Searching for 2a:f2:65:19:95:10 in /var/db/dhcpd_leases ...
I0703 19:21:45.877055    5571 main.go:141] libmachine: Found 1 entries in /var/db/dhcpd_leases!
I0703 19:21:45.877070    5571 main.go:141] libmachine: dhcp entry: {Name:minikube IPAddress:192.168.105.2 HWAddress:ee:fc:78:b8:e9:2a ID:1,ee:fc:78:b8:e9:2a Lease:0x64a4b22d}
I0703 19:21:47.877748    5571 main.go:141] libmachine: Attempt 2
I0703 19:21:47.877777    5571 main.go:141] libmachine: Searching for 2a:f2:65:19:95:10 in /var/db/dhcpd_leases ...
I0703 19:21:47.877954    5571 main.go:141] libmachine: Found 1 entries in /var/db/dhcpd_leases!
I0703 19:21:47.877967    5571 main.go:141] libmachine: dhcp entry: {Name:minikube IPAddress:192.168.105.2 HWAddress:ee:fc:78:b8:e9:2a ID:1,ee:fc:78:b8:e9:2a Lease:0x64a4b22d}
I0703 19:21:49.878584    5571 main.go:141] libmachine: Attempt 3
I0703 19:21:49.878604    5571 main.go:141] libmachine: Searching for 2a:f2:65:19:95:10 in /var/db/dhcpd_leases ...
I0703 19:21:49.878742    5571 main.go:141] libmachine: Found 1 entries in /var/db/dhcpd_leases!
I0703 19:21:49.878754    5571 main.go:141] libmachine: dhcp entry: {Name:minikube IPAddress:192.168.105.2 HWAddress:ee:fc:78:b8:e9:2a ID:1,ee:fc:78:b8:e9:2a Lease:0x64a4b22d}
I0703 19:21:51.878980    5571 main.go:141] libmachine: Attempt 4

### Attach the log file

[minikube.log](https://github.com/kubernetes/minikube/files/11944269/minikube.log)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by josetaylor06** [comment]
I have tried 

minikube delete
minikube start

as shown in the logs

Thanks!

**Comment by lollipopman** [comment]
@josetaylor06 I am having the same issue on macOS ventura, were you able to resolve it?

**Comment by lollipopman** [comment]
@josetaylor06 after a bit of analysis I discovered the reason why this was failing for my use case was that qemu was taking over 60secs to start, which is the timeout for checking for dhcp. I hacked up a longer timeout in minikube's src, and it started successfully.

**Comment by josetaylor06** [comment]
> 

Hey @lollipopman, thanks for following up! I would've never guessed it. I'm glad you solved this for others who may run into the same issue. On my end, I just started using docker as the driver and haven't had a problem since but that is not a cure especially if for some reason I was required to use vbox for running the container.

Thanks for the reply and info!!!

**Comment by lollipopman** [comment]
@raghavendra-talur I have confirmed that your commit, 08233d033387502106c7f0fd9db2da79269df036, fixed the issue for me, so I think this issue can be closed, thanks!
