### ISSUE TITLE
Unable to start minikube into Coursera test platform

### ISSUE THREAD

**Issue by ldabb** [kubernetes/minikube#16810]
### What Happened?

See error in next text block

### Attach the log file

\u274c  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.22.1:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.22.1
[preflight] Running pre-flight checks
[preflight] The system verification failed. Printing the output from the verification:
KERNEL_VERSION: 5.3.0-1028-aws
DOCKER_VERSION: 20.10.8
DOCKER_GRAPH_DRIVER: overlay2
OS: Linux
CGROUPS_CPU: enabled
CGROUPS_CPUACCT: enabled
CGROUPS_CPUSET: enabled
CGROUPS_DEVICES: enabled
CGROUPS_FREEZER: enabled
CGROUPS_MEMORY: enabled
CGROUPS_PIDS: enabled
CGROUPS_HUGETLB: enabled
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority

stderr:
	[WARNING SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/5.3.0-1028-aws\n", err: exit status 1
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
W0703 12:27:40.570094    1919 certs.go:489] WARNING: could not validate bounds for certificate apiserver: the certificate has expired: NotBefore: 2021-09-12 13:21:49 +0000 UTC, NotAfter: 2022-09-13 13:21:49 +0000 UTC
error execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: x509: certificate has expired or is not yet valid: current time 2023-07-03T12:27:40Z is after 2022-09-13T13:21:49Z
To see the stack trace of this error execute with --v=5 or higher

### Operating System

None

### Driver

None

**Comment by kundan2707** [comment]
@ldabb  can you please describe steps that you have performed?

**Comment by spowelljr** [comment]
Hi @ldabb, it looks like you minikube certs are expired:
```
WARNING: could not validate bounds for certificate apiserver: the certificate has expired: NotBefore: 2021-09-12 13:21:49 +0000 UTC, NotAfter: 2022-09-13 13:21:49 +0000 UTC
error execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: x509: certificate has expired or is not yet valid: current time 2023-07-03T12:27:40Z is after 2022-09-13T13:21:49Z
```

This should be resolved in the latest version of minikube, what version are you using? `minikube version`

To resolve this you can delete all your clusters and minikube home directory with `minikube delete --all --purge`. Then try starting you minikube cluster again and the issue should be resolved.

**Comment by ldabb** [comment]
Dear @spowelljr, this is an error coming from a Coursera hands-on Lab. It is not a fault on my personal computer or VM, that I can fix autonomously. Every lab environment should be already up-to-date and well configured, in order to let students practice.

**Comment by ldabb** [comment]
Thanks for your support. Issue reported also on Coursera platform.

**Comment by Sammy210** [comment]
> Hi @ldabb, it looks like you minikube certs are expired:
> 
> ```
> WARNING: could not validate bounds for certificate apiserver: the certificate has expired: NotBefore: 2021-09-12 13:21:49 +0000 UTC, NotAfter: 2022-09-13 13:21:49 +0000 UTC
> error execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: x509: certificate has expired or is not yet valid: current time 2023-07-03T12:27:40Z is after 2022-09-13T13:21:49Z
> ```
> 
> This should be resolved in the latest version of minikube, what version are you using? `minikube version`
> 
> If you don't want to update the version of minikube you can resolve this by deleting all your clusters and minikube home directory with `minikube delete --all --purge`. Then try starting you minikube cluster again and the issue should be resolved.

Just to mention that I also experienced this same issue in Coursera labs and your response fixed it for me. 
Thanks.
