### ISSUE TITLE
无法启动minikube 

### ISSUE THREAD

**Issue by zhamghaoran** [kubernetes/minikube#16815]
**重现问题所需的命令**：
minikube start

**失败的命令的完整输出**：<details>
😄  minikube v1.30.1 on Ubuntu 22.04 (kvm/amd64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
❗  minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.39, but successfully downloaded docker.io/kicbase/stable:v0.0.39 as a fallback image
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🤦  StartHost failed, but will try again: creating host: create: bootstrapping certificates: Failed to decode PEM data
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: bootstrapping certificates: Failed to decode PEM data

❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: bootstrapping certificates: Failed to decode PEM data

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：ubuntu 22

**Comment by aiyijing** [comment]
@zhamghaoran  估计是 ~/.minikube/ 下的 证书损坏了， 运行 minikube delete --purge=true 清空数据，然后在minikube start 创建新的集群。😄

**Comment by tennessine** [comment]
Look look这个 https://github.com/kubernetes/minikube/issues/9849
