### ISSUE TITLE
Minikube >= 1.30.0 generates /etc/systemd/system/cri-docker.service.d/10-cnf.conf with wrong pause image on arm64 when using --driver=none

### ISSUE THREAD

**Issue by yjwong** [kubernetes/minikube#16823]
### What Happened?

When running minikube in a Ubuntu 22.04 LTS VM (arm64) with the following arguments:

```
minikube start --insecure-registry "0.0.0.0/0" --kubernetes-version=v1.24.15 --driver=none --extra-config=kubeadm.ignore-preflight-errors=SystemVerification
```

The Kubernetes cluster fails to start. This appears to be because of --pod-infra-container-image=registry.k8s.io/pause:test2 being passed in /etc/systemd/system/cri-docker.service.d/10-cni.conf. That pod infra container image appears to be 8 years old, and doesn't contain an arm64 manifest.

Downgrading to v1.29.0 makes it work, but requires cri-dockerd to be installed in `/usr/bin` instead of `/usr/local/bin`.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11960710/log.txt)

### Operating System

Ubuntu

### Driver

None (Baremetal)

**Comment by afbjorklund** [comment]
The same thing happens with the Docker driver on Mac, and makes the whole cluster unstable.

It is a bug with the fallback images for when newer k8s versions are not defined by minikube.

Upgrading minikube or downgrading kubernetes, are the known workarounds.

**Comment by afbjorklund** [comment]
The fallback code pulls this list of images, from https://k8s.gcr.io/v2/pause/tags/list

```json
  "tags": [
    "0.8.0",
    "1.0",
    "2.0",
    "3.0",
    "3.1",
    "3.2",
    "3.3",
    "3.4.1",
    "3.5",
    "3.6",
    "3.7",
    "3.8",
    "3.9",
    "go",
    "latest",
    "sha256-7031c1b283388d2c2e09b57badb803c05ebed362dc88d84b480cc47f72a21097.sig",
    "sha256-9001185023633d17a2f98ff69b6ff2615b8ea02a825adffa40422f51dfdcde9d.sig",
    "test",
    "test2"
  ]
```

* #14006

**Comment by spowelljr** [comment]
Easy to reproduce, go into `pkg/minikube/constants/constants_kubeadm_images.go` and remove a version.

Then run `minikube start --preload=false kubernetes-version=<version_remove>`

Only the etcd, pause, and coredns images are affected as we just pass the Kubernetes version itself to the rest of the images.

**Comment by spowelljr** [comment]
I have three ideas to solves this

### Solution 1
Grab the major.minor of the Kubernetes version, then look for the latest version in https://github.com/kubernetes/minikube/blob/55aa6b2d5196a4a4aab63070a4ba5513ab8635c5/pkg/minikube/constants/constants_kubernetes_versions.go#L23-L29

Take that version and then get the images from https://github.com/kubernetes/minikube/blob/55aa6b2d5196a4a4aab63070a4ba5513ab8635c5/pkg/minikube/constants/constants_kubeadm_images.go#L20-L35

We can't directly get the images from `KubeadmImages` as it's a map and unordered.

#### Pros
- Fastest

#### Cons
- Doesn't work if using on an older version of minikube where the major.minor doesn't exist in `ValidKubernetesVersions` or `KubeadmImages` yet

### Solution 2
Download the kubeadm binary to the host and run `kubeadm config images list` to get the images.

#### Pros
- Will work regardless of how new the Kubernetes version is

#### Cons
- Slowest, binary is ~50 MB so will add time to the first start

### Solution 3
minikube maintains a json file that contains the mappings of Kubernetes versions to images

#### Pros
- Fast

#### Cons
- minikube would have the maintain the files (although likely not much work, would be fully automated)
