### ISSUE TITLE
Cannot access minikube dashboard 

### ISSUE THREAD

**Issue by spnzig** [kubernetes/minikube#1682]
Is this a BUG REPORT or FEATURE REQUEST? : BUG REPORT

**Minikube version** : v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 12.04.5 LTS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "virtualbox"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): "Boot2DockerURL": "file:///home/nszig/.minikube/cache/iso/minikube-v0.20.0.iso"
- **Install tools**: 
- **Others**: 

**What happened**:
I have installed minikube and kubectl on Ubuntu. However i cannot access the dashboard both through the CLI and through the GUI.
http://127.0.0.1:8001/ui give the below error
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

And minikube dashboard on the CLI does not open the dashboard 

**What you expected to happen**:
I should be able to view the kubernetes dashboard

**How to reproduce it** (as minimally and precisely as possible):
Try the below on Ubuntu 12.04LTS 

- curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.20.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

- curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

- chmod +x ./kubectl

- sudo mv ./kubectl /usr/local/bin/kubectl

- minikube dashboard

Output:
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
.......
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet

http://127.0.0.1:8001/ui
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kubernetes-dashboard\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

**Anything else do we need to know**:
kubectl version: Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.0", GitCommit:"d3ada0119e776222f11ec7945e6d860061339aad", GitTreeState:"clean", BuildDate:"2017-06-29T23:15:59Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"dirty", BuildDate:"2017-06-22T04:31:09Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}

**minikube logs also reports the errors below:**
.....
Jul 10 08:46:12 minikube localkube[3237]: I0710 08:46:12.901880    3237 kuberuntime_manager.go:458] Container {Name:php-redis Image:gcr.io/google-samples/gb-frontend:v4 Command:[] Args:[] WorkingDir: Ports:[{Name: HostPort:0 ContainerPort:80 Protocol:TCP HostIP:}] EnvFrom:[] Env:[{Name:GET_HOSTS_FROM Value:dns ValueFrom:nil}] Resources:{Limits:map[] Requests:map[cpu:{i:{value:100 scale:-3} d:{Dec:<nil>} s:100m Format:DecimalSI} memory:{i:{value:104857600 scale:0} d:{Dec:<nil>} s:100Mi Format:BinarySI}]} VolumeMounts:[{Name:default-token-gqtvf ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath:}] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
Jul 10 08:46:14 minikube localkube[3237]: E0710 08:46:14.139555    3237 remote_runtime.go:86] RunPodSandbox from runtime service failed: rpc error: code = 2 desc = unable to pull sandbox image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v1/_ping: x509: certificate signed by unknown authority
.....

**Comment by r2d4** [comment]
Can you post the output of `kubectl get pods --all-namespaces`?  And possible a `kubectl describe` on the dashboard pod if you see it?

**Comment by spnzig** [comment]
`sanjana@RND-ITPU08:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS              RESTARTS   AGE
kube-system   kube-addon-manager-minikube             0/1       ContainerCreating   0          16h
kube-system   kubernetes-dashboard-2039414953-5mww0   0/1       ContainerCreating   0          16h
`

A describe on kubernetes-dashboard-* pod gives,
`the server doesn't have a resource type "kubernetes-dashboard-2039414953-5mww0"`

**Comment by spnzig** [comment]
I even upgraded to Ubuntu host to 16.04LTS. Still the same issue persists.
all the containers are in ContainerCreating state and when services are invoked, i get `Waiting, endpoint for service is not ready yet`...

**Comment by r2d4** [comment]
Are you behind a proxy?  It looks like the VM isn't able to reach out to the internet and pull the images.  If so, make sure you set the HTTP_PROXY or HTTPS_PROXY variables in `minikube start --docker-env`

**Comment by spnzig** [comment]
Though i didn't have specific proxy set, there were a few network accessibility issues which was blocking the image from being pulled. I was able to resolve this and get the dashboard up and running by using a VPN. Thanks for your help.

**Comment by spnzig** [comment]
Using a VPN for the install actually resolved the issue. But for some reasons i had to delete the minikube instance and restart it. But now even if the kubernetes-dashboard pod is with the status "Running" i get the same error.. "`Waiting, endpoint for service not ready yet"`

**Comment by vfxGer** [comment]
Still getting this problem.

**Comment by pavanbhosle** [comment]
I am getting the same issue. 
Inspite of setting proxy while starting minikube, I am still getting this error Please find the attachment sdhowing this problem.
![1](https://user-images.githubusercontent.com/37103675/37023731-d32330ae-214c-11e8-85c3-427748544c0a.PNG)

**Comment by grohan2002** [comment]
+1

**Comment by lokinell** [comment]
+1

`# loki @ Loki-iMac in ~/.minikube [18:12:24] C:146
$ minikube version
minikube version: v0.25.2

# loki @ Loki-iMac in ~/.minikube [18:13:03]
$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS              RESTARTS   AGE
default       kube-nginx9999-64f48c6857-t4mbk         0/1       ContainerCreating   0          3h
kube-system   kube-addon-manager-minikube             0/1       ContainerCreating   0          4h
kube-system   kubernetes-dashboard-5bd6f767c7-bvjmp   0/1       ContainerCreating   0          6m`

**Comment by diversys** [comment]
Same problem here
```
# minikube version
minikube version: v0.27.0
```
```
# kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   etcd-minikube                           1/1       Running   0          2h
kube-system   kube-addon-manager-minikube             1/1       Running   0          2h
kube-system   kube-apiserver-minikube                 1/1       Running   0          2h
kube-system   kube-controller-manager-minikube        1/1       Running   0          2h
kube-system   kube-dns-86f4d74b45-pt96w               3/3       Running   0          2h
kube-system   kube-proxy-t2j22                        1/1       Running   0          2h
kube-system   kube-scheduler-minikube                 1/1       Running   0          2h
kube-system   kubernetes-dashboard-7d5dcdb6d9-4nz6c   1/1       Running   0          1h
kube-system   storage-provisioner                     1/1       Running   0          2h
```
```
# minikube dashboard --logtostderr --v=2
I0517 16:51:54.368688   29842 notify.go:109] Checking for updates...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
```
```
# kubectl describe rc kubernetes-dashboard --namespace=kube-system
Error from server (NotFound): replicationcontrollers "kubernetes-dashboard" not found
```

**Comment by sachinlv** [comment]
+1

**Comment by mireczatko** [comment]
same here

**Comment by foamliu** [comment]
+1

**Comment by ctriple** [comment]
+1

**Comment by humbss** [comment]
+1

**Comment by helloworlde** [comment]
+1, So Why there have so many issues on Mac for minikube

**Comment by kayoubi** [comment]
+1

**Comment by Jianyi-Ren** [comment]
+1

**Comment by sunnypatel** [comment]
+1

**Comment by bunday** [comment]
+1

**Comment by k-santosh** [comment]
+1
minikube version: v0.28.0

**Comment by mandeinfo** [comment]
Dashboard and storage provisioner both remain in pending state. Any suggestions ? 
minikube version v0.28.0 / Windows 

kube-system   kubernetes-dashboard-5498ccf677-844s7   0/1       Pending   0          8h
kube-system   storage-provisioner                     0/1       Pending   0          8h

**Comment by james-liu** [comment]
+1

**Comment by jdleo** [comment]
+1 v0.23.0 (mac)

**Comment by Franco-Poveda** [comment]
+1

**Comment by jdleo** [comment]
fixed it by deleting cluster, and deleting minikube completely and and reinstalling to 0.28.2 through brew (on mac)

**Comment by scollier** [comment]
+1

```
$ minikube version
minikube version: v0.28.2
```

**Comment by e-yudkin** [comment]
Same thing, Linux Mint 18.2. 
Minikube version: v0.30.0

**Comment by Monte-Christo** [comment]
`minikube delete`
followed by 
`minikube start --vm-driver hyperv`
also worked for me under Win 10 Pro.

**Comment by anibalardid** [comment]
I fixed issue deleting .kube and .minikube directories from my home , maybe previous testing using virtualbox let some problems there.

try it ;)
