### ISSUE TITLE
minikube crashes

### ISSUE THREAD

**Issue by nuszxh** [kubernetes/minikube#16879]
I was doing "Container Orchestration using Kubernetes", here is the issue I encountered when I tried to start a kubernetes cluster: 

rhyme@ip-10-199-28-0:~/yml$ sudo minikube start --vm-driver=none
\U0001f604  minikube v1.2.0 on linux (amd64)c
\U0001f4a1  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
\U0001f504  Restarting existing none VM for "minikube" ...
\u231b  Waiting for SSH access ...
\U0001f433  Configuring environment for Kubernetes v1.15.0 on Docker 19.03.6
    \u25aa kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
\U0001f504  Relaunching Kubernetes v1.15.0 using kubeadm ... 

\U0001f4a3  Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

\U0001f63f  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
\U0001f449  https://github.com/kubernetes/minikube/issues/new
rhyme@ip-10-199-28-0:~/yml$

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by nuszxh** [comment]
Thanks for your reply. I run the command but didn't see the logs.txt file generated. Just cut and paste the screen output here: 

rhyme@ip-10-199-53-147:~/yml$ sudo minikube logs file=logs.txt 

==> coredns <==
.:53
2020-10-05T10:25:40.921Z [INFO] CoreDNS-1.3.1
2020-10-05T10:25:40.921Z [INFO] linux/amd64, go1.11.4, 6b56a9c
CoreDNS-1.3.1
linux/amd64, go1.11.4, 6b56a9c
2020-10-05T10:25:40.921Z [INFO] plugin/reload: Running configuration MD5 = 5d5369fbc12f985709b924e721217843
[INFO] SIGTERM: Shutting down servers then terminating

==> dmesg <==
[Jul20 02:47] MDS CPU bug present and SMT on, data leak possible. See https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/mds.html for more details.
[  +0.223713] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[  +0.758628] ACPI: PCI Interrupt Link [LNKD] enabled at IRQ 11
[  +0.048419] i8042: Warning: Keylock active
[  +0.528982] ena 0000:00:05.0: LLQ is not supported Fallback to host mode policy.
[ +10.149693] new mount options do not match the existing superblock, will be ignored
[  +0.605967] vboxdrv: loading out-of-tree module taints kernel.
[  +0.042596] VBoxNetFlt: Successfully started.
[  +0.034192] VBoxNetAdp: Successfully started.
[  +0.029508] VBoxPciLinuxInit
[Jul20 02:48] kauditd_printk_skb: 26 callbacks suppressed
[ +11.019998] kauditd_printk_skb: 5 callbacks suppressed

==> kernel <==
 03:30:33 up 42 min,  1 user,  load average: 0.07, 0.11, 0.17
Linux ip-10-199-53-147 4.15.0-1065-aws #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

==> kube-addon-manager <==
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2020-10-05T10:27:40+00:00 ==
INFO: Leader is ip-172-31-215-162
INFO: == Kubernetes addon ensure completed at 2020-10-05T10:28:38+00:00 ==
INFO: == Reconciling with deprecated label ==
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2020-10-05T10:28:40+00:00 ==
INFO: Leader is ip-172-31-215-162
INFO: == Kubernetes addon ensure completed at 2020-10-05T10:29:38+00:00 ==
INFO: == Reconciling with deprecated label ==
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==

---
Regards
Xinhuai

**Comment by nuszxh** [comment]
Jul 20 03:30:33 ip-10-199-53-147 kubelet[9292]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jul 20 03:30:33 ip-10-199-53-147 kubelet[9292]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jul 20 03:30:33 ip-10-199-53-147 kubelet[9292]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jul 20 03:30:33 ip-10-199-53-147 kubelet[9292]: I0720 03:30:33.746750    9292 server.go:425] Version: v1.15.0
Jul 20 03:30:33 ip-10-199-53-147 kubelet[9292]: I0720 03:30:33.747285    9292 plugins.go:103] No cloud provider specified.
Jul 20 03:30:33 ip-10-199-53-147 kubelet[9292]: E0720 03:30:33.755120    9292 bootstrap.go:263] Part of the existing bootstrap client certificate is expired: 2021-10-05 10:25:08 +0000 UTC
Jul 20 03:30:33 ip-10-199-53-147 kubelet[9292]: F0720 03:30:33.755409    9292 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jul 20 03:30:33 ip-10-199-53-147 systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jul 20 03:30:33 ip-10-199-53-147 systemd[1]: kubelet.service: Failed with result 'exit-code'.

==> storage-provisioner <==
E1005 10:32:29.578261       1 reflector.go:315] k8s.io/minikube/vendor/github.com/r2d4/external-storage/lib/controller/controller.go:411: Failed to watch *v1.PersistentVolumeClaim: Get https://10.96.0.1:443/api/v1/persistentvolumeclaims?resourceVersion=1&timeoutSeconds=505&watch=true: dial tcp 10.96.0.1:443: getsockopt: connection refused
E1005 10:32:29.578675       1 reflector.go:315] k8s.io/minikube/vendor/github.com/r2d4/external-storage/lib/controller/controller.go:379: Failed to watch *v1.StorageClass: Get https://10.96.0.1:443/apis/storage.k8s.io/v1/storageclasses?resourceVersion=354&timeoutSeconds=566&watch=true: dial tcp 10.96.0.1:443: getsockopt: connection refused
E1005 10:32:29.588851       1 reflector.go:315] k8s.io/minikube/vendor/github.com/r2d4/external-storage/lib/controller/controller.go:412: Failed to watch *v1.PersistentVolume: Get https://10.96.0.1:443/api/v1/persistentvolumes?resourceVersion=1&timeoutSeconds=357&watch=true: dial tcp 10.96.0.1:443: getsockopt: connection refused

**Comment by spowelljr** [comment]
Those logs aren't enough to go off of unfortunately, but there's another way to get the start logs. Delete your existing cluster with `minikube delete` and then try starting the cluster again, once it's failed there are verbose logs stored in `~/.minikube/log/lastStart.txt`. Could you upload that file once you've completed those steps.

**Comment by nuszxh** [comment]
Sorry, I didn't find a way to download the files from the workspace, and there is a length   limit here for the comment, so I didn't got time to paste all messages I received. When I tried again this morning and my session time out. I need to find ways to continue with this lesson. Will approach you again if I have any queries. Thanks!

**Comment by spowelljr** [comment]
Sounds good, I'll close this issue for now, but feel free to respond if another question arrises
