### ISSUE TITLE
Cant download kubernetes-version v1.6.4

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#1687]
**BUG REPORT **

**Minikube version** (use `minikube version`):
tried on both 
minikube version: v0.18.0
and 
minikube version: v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac Os 10.12.4
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
"DriverName": "virtualbox",

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
"Boot2DockerURL": "file:///Users/z001r9y/.minikube/cache/iso/minikube-v0.20.0.iso"
- **Install tools**:
- **Others**:

**What happened**:
minikube get-k8s-versions says 1.6.4 is available but when I try to download it, I get the following error :

```
$ minikube start --memory 4096 --kubernetes-version v1.6.4
Starting local Kubernetes cluster...
Starting VM...
SSH-ing files into VM...
Downloading localkube binary
E0712 16:53:51.672753   92371 start.go:144] Error updating cluster:  Error updating localkube from uri: Error attempting to download and cache localkube: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:
```

**What you expected to happen**:
To not error.

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
it work for 1.6.3 but not for 1.6.4

**Comment by r2d4** [comment]
The default version is v1.6.4, you can use it by just using `minikube start --memory 4096`. 

This is a valid bug that specifying the version break.  Since we haven't uploaded the version to the right place.

**Comment by r2d4** [comment]
This should be fixed @medyagh, sorry about that.

I've also added a PR that will make this more efficient by not reaching out to the internet to fetch the default versions of localkube.  The default version of localkube is already bundled with every minikube.
