### ISSUE TITLE
执行 kubectl 命令后 failed to close the audit log: invalid argument

### ISSUE THREAD

**Issue by yoohot** [kubernetes/minikube#16881]
**重现问题所需的命令**：
root@pc:~# kubectl get pod -nkube-system
NAME                               READY   STATUS    RESTARTS        AGE
coredns-787d4945fb-hcwst           1/1     Running   24 (132m ago)   3d21h
etcd-minikube                      1/1     Running   24 (132m ago)   3d21h
kube-apiserver-minikube            1/1     Running   25 (132m ago)   3d21h
kube-controller-manager-minikube   1/1     Running   25 (132m ago)   3d21h
kube-proxy-j4722                   1/1     Running   24 (132m ago)   3d21h
kube-scheduler-minikube            1/1     Running   24 (132m ago)   3d21h
metrics-server-6588d95b98-k94vs    1/1     Running   21 (130m ago)   2d20h
storage-provisioner                1/1     Running   36 (129m ago)   3d21h
E0714 11:43:02.773743 1417143 logFile.go:53] failed to close the audit log: invalid argument

最后一行输出下面的错误日志：
E0714 11:37:09.134052 1354881 logFile.go:53] failed to close the audit log: invalid argument

**使用的操作系统版本**：
ubuntu18.04
minikube: 
  client version:1.26.3
  server version:1.26.3

**Comment by yoohot** [comment]
在~/.minikube/logs/lastStart.txt 最后显示： 
1283 root.go:91] failed to log command end to audit: failed to convert logs to rows: failed to unmarshal "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00{\"specversion\":\"1.0\",\"id\":\"4d896b8b-3b08-4dc2-86ab-838c12515202\",\"source\":\"https://minikube.sigs.k8s.io/\",\"type\":\"io.k8s.sigs.minikube.audit\",\"datacontenttype\":\"application/json\",\"data\":{\"args\":\"--extra-config=apiserver.service-node-port-range=1-65535 --memory=max --cpus=max --listen-address=0.0.0.0 --force\",\"command\":\"start\",\"endTime\":\"\",\"id\":\"0dfe4219-0ebf-46e6-b721-d0c2c191a9fc\",\"profile\":\"minikube\",\"startTime\":\"12 Jul 23 14:39 CST\",\"user\":\"root\",\"version\":\"v1.30.1\"}}": invalid character '\x00' looking for beginning of value

**Comment by liangyuanpeng** [comment]
Could you provide some reproduce step for it?

**Comment by yoohot** [comment]
> Could you provide some reproduce step for it?

I'm not sure when and how did this problem appear.
i try to restart minikube and this problem  still exists.
1. root>  minikube stop
2. root> minikube start --extra-config=apiserver.service-node-port-range=1-65535 --max-memory=max --max-cpus=max \
--listen-address=0.0.0.0 --force
3. root> kubectl xxxx
....
E0714 11:37:09.134052 1354881 logFile.go:53] failed to close the audit log: invalid argument

**Comment by spowelljr** [comment]
Could you try removing the audit file `rm ~/.minikube/logs/audit.json`, that should resolve your issue. I'm not sure how you ran into that issue in the first place though. After deleting the file does the same thing happen again?

-----

您可以尝试删除审核文件“rm ~/.minikube/logs/audit.json”，这应该可以解决您的问题。我不确定你一开始是如何遇到这个问题的。删除文件后还会出现同样的情况吗？

**Comment by yoohot** [comment]
it works, thanks !

**Comment by spowelljr** [comment]
Glad that solved your issue!

-----

很高兴解决了您的问题！

**Comment by vakenbolt** [comment]
@spowelljr This worked for me too! Thanks for posting!

---
这对我也有用！谢谢发帖！
