### ISSUE TITLE
minikube启动ingress组件失败

### ISSUE THREAD

**Issue by sea-wyq** [kubernetes/minikube#16880]
**重现问题所需的命令**：
 minikube addons enable ingress

**失败的命令的完整输出**：<details>

❌  Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed0714 10:45:14.420001  676855 out.go:348] isatty.IsTerminal(1) = true
 out waiting for the condition]

</details>

**`minikube logs`命令的输出**： <details>
og file created at: 2023/07/14 10:45:14
Running on machine: DESKTOP-PVL03Q3
Binary: Built with gc go1.20.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0714 10:45:14.419849  676855 out.go:296] Setting OutFile to fd 1 ...
I0714 10:45:14.420001  676855 out.go:348] isatty.IsTerminal(1) = true
I0714 10:45:14.420004  676855 out.go:309] Setting ErrFile to fd 2...
I0714 10:45:14.420008  676855 out.go:348] isatty.IsTerminal(2) = true
I0714 10:45:14.420077  676855 root.go:336] Updating PATH: /home/wyq/.minikube/bin
W0714 10:45:14.420157  676855 root.go:312] Error reading config file at /home/wyq/.minikube/config/config.json: open /home/wyq/.minikube/config/config.json: no such file or directory
I0714 10:45:14.430105  676855 out.go:177] 💡  ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
I0714 10:45:14.437998  676855 config.go:182] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.26.3 
I0714 10:45:14.438015  676855 addons.go:66] Setting ingress=true in profile "minikube"
I0714 10:45:14.438020  676855 addons.go:228] Setting addon ingress=true in "minikube"
I0714 10:45:14.438067  676855 host.go:66] Checking if "minikube" exists ...
I0714 10:45:14.440176  676855 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0714 10:45:14.467081  676855 out.go:177]     ▪ Using image registry.k8s.io/ingress-nginx/controller:v1.7.0
I0714 10:45:14.475337  676855 out.go:177]     ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
I0714 10:45:14.483536  676855 out.go:177]     ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230312-helm-chart-4.5.2-28-g66a760794
I0714 10:45:14.491617  676855 addons.go:420] installing /etc/kubernetes/addons/ingress-deploy.yaml
I0714 10:45:14.491633  676855 ssh_runner.go:362] scp memory --> /etc/kubernetes/addons/ingress-deploy.yaml (16145 bytes)
I0714 10:45:14.492792  676855 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0714 10:45:14.507744  676855 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:32777 SSHKeyPath:/home/wyq/.minikube/machines/minikube/id_rsa Username:docker}
I0714 10:45:14.632993  676855 ssh_runner.go:195] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.26.3/kubectl apply -f /etc/kubernetes/addons/ingress-deploy.yaml
I0714 10:45:15.198541  676855 addons.go:464] Verifying addon ingress=true in "minikube"
I0714 10:45:15.220073  676855 out.go:177] 🔎  Verifying ingress addon...
I0714 10:45:15.240602  676855 kapi.go:75] Waiting for pod with label "app.kubernetes.io/name=ingress-nginx" in ns "ingress-nginx" ...
I0714 10:45:15.260610  676855 kapi.go:86] Found 3 Pods for label selector app.kubernetes.io/name=ingress-nginx
I0714 10:45:15.260620  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:15.771817  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:16.264562  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:16.767043  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:17.301848  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:17.771064  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:18.267730  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:18.764739  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:19.268361  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:19.771742  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:20.268143  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:20.766398  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:21.265658  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:21.776259  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:22.268380  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:22.765730  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:23.269235  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:23.769495  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0714 10:45:24.265486  676855 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]

</details>

**使用的操作系统版本**：ubuntu2.04

**Comment by spowelljr** [comment]
Could you run `kubectl get pods -n ingress-nginx`, you should see three pods
```
NAME                                        READY   STATUS      RESTARTS   AGE
ingress-nginx-admission-create-hhx62        0/1     Completed   0          104s
ingress-nginx-admission-patch-q5tsz         0/1     Completed   1          104s
ingress-nginx-controller-7799c6795f-jxghd   1/1     Running     0          104s
```

One of them should be stuck starting, then run `kubectl describe pods <pod_name> -n ingress-nginx` & `kubectl logs <pod_name> -n ingress-nginx` and upload the output here.

------

你可以运行`kubectl get pods -n ingress-nginx`，你应该看到三个 pod
```
NAME                                        READY   STATUS      RESTARTS   AGE
ingress-nginx-admission-create-hhx62        0/1     Completed   0          104s
ingress-nginx-admission-patch-q5tsz         0/1     Completed   1          104s
ingress-nginx-controller-7799c6795f-jxghd   1/1     Running     0          104s
```

其中之一应该卡在启动位置，然后运行`kubectl描述pods<pod_name> -n ingress-nginx`和`kubectl日志<pod_name>-n ingress-nginx`并在此处上传输出。
