### ISSUE TITLE
Mac m2: minikube not detected on PyCharm 

### ISSUE THREAD

**Issue by asmayonis1** [kubernetes/minikube#16884]
### What Happened?

- Install cloud code successfully 
- open Setting > Tools > cloud code > decencies > no minikube version detected 
- run terminal > minikube is found with version 1.30

### Attach the log file

[](url)

### Operating System

None

### Driver

None

**Comment by spowelljr** [comment]
This seems like an issue with Cloud Code, could you open the issue with them https://github.com/GoogleCloudPlatform/cloud-code-intellij/issues, thanks
