### ISSUE TITLE
minkube not started

### ISSUE THREAD

**Issue by SamarthAgarwal9** [kubernetes/minikube#16889]
### What Happened?

i try  many times but minkube nor supported driver of docker 

### Attach the log file

inikube logs --file=log.txt

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!
