### ISSUE TITLE
Exiting due to K8S_INSTALL_FAILED: updating control plane

### ISSUE THREAD

**Issue by jerryliOFjava** [kubernetes/minikube#16893]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

-----

感谢您分享您的经验！

您能否运行“minikube logs --file=logs.txt”并将文件拖放到此问题中。

这将有助于我们进一步定位问题，谢谢！
