### ISSUE TITLE
investigate if new cri-dockerd is broken

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#16909]
### What Happened?
test failing on Cri-dockerd

https://github.com/kubernetes/minikube/pull/16857#issuecomment-1633413391

here is chat conversation with @prezha 

```

medya
  [2:34 PM](https://kubernetes.slack.com/archives/D01DY6WK6LU/p1689629666369899)
https://github.com/kubernetes/minikube/pull/16857#issuecomment-1633413391

GitHubGitHub
[Kicbase/ISO: Update cri-dockerd from v0.3.3 to v0.3.4 by minikube-bot · Pull Request #16857 · kubernetes/minikube](https://github.com/kubernetes/minikube/pull/16857#issuecomment-1633413391)
The cri-dockerd project released a new version
This PR was auto-generated by make update-cri-dockerd-version using update-cri-dockerd-version.yml CI Workflow.
A minikube maintainer needs to checkou... (79 kB)
https://github.com/kubernetes/minikube/pull/16857#issuecomment-1633413391

[2:34](https://kubernetes.slack.com/archives/D01DY6WK6LU/p1689629674642919)
thats is the one,  but maybe it was a bad run
[2:34](https://kubernetes.slack.com/archives/D01DY6WK6LU/p1689629681571709)
can u check manually


predrag
  [4:10 PM](https://kubernetes.slack.com/archives/D01DY6WK6LU/p1689635442637049)
oh, that clarifies it
no problem
ok, so all the tests at [that point](https://github.com/kubernetes/minikube/pull/16857#issuecomment-1633413391) failed with the error: Internal error occurred: error executing command in container: http: invalid Host header
this looks like a known issue with the docker and go 1.20.6 (ie, https://github.com/docker/cli/issues/4437 and https://github.com/moby/moby/issues/45935), but we still use 1.20.5 to compile binaries (eg, https://github.com/kubernetes/minikube/blob/00d52dd7f5fa61400c4ae3ba5ee7fcd8b27cdfe0/Makefile#L37, https://github.com/kubernetes/minikube/blob/00d52dd7f5fa61400c4ae3ba5ee7fcd8b27cdfe0/.github/workflows/build.yml#L15, https://github.com/kubernetes/minikube/blob/00d52dd7f5fa61400c4ae3ba5ee7fcd8b27cdfe0/.github/workflows/master.yml#L17, https://github.com/kubernetes/minikube/blob/00d52dd7f5fa61400c4ae3ba5ee7fcd8b27cdfe0/.github/workflows/update-cri-dockerd-version.yml#L9, etc.)
subsequent tests had no failures of that kind and were within boundaries of expected issues - eg, https://github.com/kubernetes/minikube/pull/16857#issuecomment-1638774666
so i would say - yes, probably an intermittent issue, and we should probably continue avoiding updating to go 1.20.6 if it has some issues
GitHubGitHub
[Kicbase/ISO: Update cri-dockerd from v0.3.3 to v0.3.4 by minikube-bot · Pull Request #16857 · kubernetes/minikube](https://github.com/kubernetes/minikube/pull/16857#issuecomment-1633413391)
The cri-dockerd project released a new version
This PR was auto-generated by make update-cri-dockerd-version using update-cri-dockerd-version.yml CI Workflow.
A minikube maintainer needs to checkou... (79 kB)
https://github.com/kubernetes/minikube/pull/16857#issuecomment-1633413391

GitHubGitHub
[Compiling error: http: invalid Host header · Issue #4437 · docker/cli](https://github.com/docker/cli/issues/4437)
Description I am trying to build docker-cli from source for my freebsd 13.2 host system, because currently my whole docker toolchain over at freebsd is a mess. I am aware that I can compile docker-... (98 kB)
https://github.com/docker/cli/issues/4437

GitHubGitHub
[Golang client fails to attach to streams with "http: invalid Host header" with go1.20.6, go1.19.11 · Issue #45935 · moby/moby](https://github.com/moby/moby/issues/45935)
Description Since updating to Golang 1.20.6, the moby Golang client starts failing with http: invalid Host header errors when used against the default unix socket at least. Normal container operati... (82 kB)
```

could be related to 
https://github.com/moby/moby/issues/45935

**Comment by medyagh** [comment]
based on the comment above @prezha do you recommend not updating the cri-dockerd ? and is that tied to go version in our ISO or KIC base?

**Comment by afbjorklund** [comment]
Generally it seems like the Docker (and cri-dockerd) versions are bumped a little too aggressively on the ISO, it probably wants to be a little more laidback to not run into all the cutting edge bugs?

**Comment by prezha** [comment]
agree: given the number of upstream dependencies, we should probably not be so quick to jump on the latest releases - it might be ok for testing/betas for some time, but perhaps not as much for the regular releases

for this specific cri-dockerd issue, i think that both iso and kic base would be affected, so we would probably want to hold with the upgrade until it's resolved

for other cases in general, where eg, upgrading go version is involved, iso could be more "vulnerable" with compiling binaries from source, so additional care should be taken there

another thing we should keep in mind regarding potential inconsistencies b/w iso and kic base, where we use packages: newer packages are somewhat behind the latest "source" releases, and so we might end up with different versions/behaviour if we release too soon

example: the pr #16883 - "Kicbase/ISO: Update cri-o from v1.24.1 to v1.27.1", where we want to upgrade to the [latest](https://github.com/cri-o/cri-o/releases) cri-o `v1.27.1`, and if i'm not mistaken:
- for `iso`, we build from source and use the latest v1.27.1 from commit 65a8134d7c4722e1c39d0e1c473532a17c240682:
https://github.com/kubernetes/minikube/blob/e8e023853a3e4f719ef31ca18132324fc208cb04/deploy/iso/minikube-iso/package/crio-bin/crio-bin.mk#L7-L8
- but for `kicbase`, we pull the latest package from opensuse/kubic (which is [retired](https://kubic.opensuse.org/), btw):
https://github.com/kubernetes/minikube/blob/e8e023853a3e4f719ef31ca18132324fc208cb04/deploy/kicbase/Dockerfile#L209-L213
but the latest version there currently is `v1.27.0`:
http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable:/cri-o:/1.27/xUbuntu_22.04/amd64/
```
prezha@codex minikube (auto_bump_cri-o_version-085433c)]$ minikube ssh -p addons-300112
docker@addons-300112:~$ crio version
INFO[2023-07-15 00:02:30.463307602Z] Starting CRI-O, version: 1.27.0, git: unknown(clean)
Version:        1.27.0
GitCommit:      unknown
GitCommitDate:  unknown
GitTreeState:   clean
BuildDate:      2023-04-25T18:11:41Z
GoVersion:      go1.19
Compiler:       gc
Platform:       linux/amd64
Linkmode:       dynamic
BuildTags:
  apparmor
  seccomp
  containers_image_ostree_stub
  exclude_graphdriver_btrfs
  exclude_graphdriver_devicemapper
  containers_image_openpgp
LDFlags:          -s -w -X github.com/cri-o/cri-o/internal/pkg/criocli.DefaultsPath="" -X github.com/cri-o/cri-o/internal/version.buildDate=2023-04-25T18:11:41Z
SeccompEnabled:   true
AppArmorEnabled:  false
```
![Screenshot-2023 07 18-22 21 14](https://github.com/kubernetes/minikube/assets/6320846/89b0e566-0be2-4300-ba0f-39d54e231f60)

**Comment by afbjorklund** [comment]
> * we pull the latest package from opensuse/kubic (which is [retired](https://kubic.opensuse.org/), btw)

the Kubic project from opensuse is dead, but CRI-O still uses OBS and the project for their binaries

**Comment by prezha** [comment]
> The cri-dockerd release used 1.19.10, but now all the CI tests are failing with 1.19.11 (and go.mod still says 1.18)

looks like we use different go version from what they use:
https://github.com/kubernetes/minikube/blob/56075bec301844e581b039bc34034a0db9b4149f/.github/workflows/update-cri-dockerd-version.yml#L9

https://github.com/Mirantis/cri-dockerd/blob/e88b1605d08e943ed4cef61a1ed3982ec8f331bc/go.mod#L3

**Comment by afbjorklund** [comment]
if we want to use the latest/greatest go, then we need to backport the latest/greatest bugfixes as well

for ISO there still was some issues with the double bootstrap now needed, first to go1.17 then to go1.20

**Comment by prezha** [comment]
go v1 releases _usually_ keep the backwards compatibility promise, but sometimes (though, indeed rarely) - they fail

**Comment by afbjorklund** [comment]
Anyway, the suggested approach from cri-dockerd is not build it from source - but to install the binary releases

Many people are still building it from source, due to the old "driveby" instructions that were left by SIG docs to rot

**Comment by spowelljr** [comment]
> > The cri-dockerd release used 1.19.10, but now all the CI tests are failing with 1.19.11 (and go.mod still says 1.18)
> 
> looks like we use different go version from what they use:
> 
> https://github.com/kubernetes/minikube/blob/56075bec301844e581b039bc34034a0db9b4149f/.github/workflows/update-cri-dockerd-version.yml#L9
> 
> https://github.com/Mirantis/cri-dockerd/blob/e88b1605d08e943ed4cef61a1ed3982ec8f331bc/go.mod#L3

Just to clarify, this is just the version of the GitHub action, it just runs a go script that updates the version of kicbase in the code, doesn't actually build it. One of us build the artifacts manually and push them up to GCS.
