### ISSUE TITLE
same service works in minikube with k8s 1.5.1 but not in minikube with k8s 1.6.3 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#1690]
**BUG REPORT**:

**Minikube version** (use `minikube version`):
both
minikube version: v0.20.0
minikube version: v0.18.0

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOs 10.12.14
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtuablox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:

**What happened**:
I have a Kafka on minikube for [K8Guard](https://github.com/k8guard/k8guard-start-from-here)
however when I use my kafka image ( wurstmeister/kafka:0.10.2.0) on minikube with kuberntes 1.6.3 it gives me an error, that indicates the DNS resolving is not happening for the kubernetes service correctly.

I SSHed to the containers and I was able to dig the kafka service dns. but when I run the whole thing it will fail. (https://github.com/Shopify/sarama/issues/912)

I did extensive experiments, I am 100% sure the problem is not from Kafka image  and the problem is a change that has happend between 1.5.1 and 1.6.3:

1. I have pinned down the image tag (and it used to work)
2. It works in docker-compose.
3. it works in minikube with kuberentes 1.5.1
 
so the only place it doesnt work is minikube with kuberentes 1.6.3

here are my service and deployment files for my kafka if you are interested.

https://github.com/k8guard/k8guard-start-from-here/blob/master/minikube/core/kafka-svc.yaml

https://github.com/k8guard/k8guard-start-from-here/blob/master/minikube/core/kafka-deployment.yaml

**What you expected to happen**:
The kafka should had been accessable normally like in minikube with kuberentes 1.5.1.

**How to reproduce it** (as minimally and precisely as possible):
run my deployment and service file for kafka in k8guard in minikube with kuberentes 1.6.3 and also 1.5.3. you will see it wont work in 1.6.3

**Anything else do we need to know**:

**Comment by medyagh** [comment]
I confirm I was able to fix this issue by doing:
```
minikube ssh
sudo ip link set docker0 promisc on
```
this was mentioned in https://github.com/kubernetes/minikube/issues/1568

This confirms that this is a minikube bug. and needs to be fixed.

**Comment by r2d4** [comment]
I'm going to close this in favor of #1568.  We'll track it there.  I'll work on fixing this
