### ISSUE TITLE
EROOR DURING BUILD

### ISSUE THREAD

**Issue by EZEBUILO** [kubernetes/minikube#16903]
### What Happened?

0s
##[debug]Evaluating condition for step: 'Build with Ant'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Build with Ant
##[debug]Loading inputs
##[debug]Loading env
Run ant -noinput -buildfile build.xml
##[debug]/usr/bin/bash -e /home/runner/work/_temp/a36db6bf-[1](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:1)a54-4[2](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:2)9b-ae[4](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:4)a-d4a8[7](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:7)e[8](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:8)d1eca.sh
Build failed
Buildfile: build.xml does not exist!
_### Error: Process completed with exit code 1_.
##[debug]Finishing: Build with Ant

please how can i resolve this error

### Attach the log file

0s
##[debug]Evaluating condition for step: 'Build with Ant'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Build with Ant
##[debug]Loading inputs
##[debug]Loading env
Run ant -noinput -buildfile build.xml
##[debug]/usr/bin/bash -e /home/runner/work/_temp/a36db6bf-[1](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:1)a54-4[2](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:2)9b-ae[4](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:4)a-d4a8[7](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:7)e[8](https://github.com/EZEBUILO/demojesus/actions/runs/5579520181/jobs/10209421864#step:4:8)d1eca.sh
Build failed
Buildfile: build.xml does not exist!
Error: Process completed with exit code 1.
##[debug]Finishing: Build with Ant

please how can i resolve this error

### Operating System

Windows

### Driver

N/A

**Comment by spowelljr** [comment]
Could you elaborate on what command you're running? This doesn't look like usual minikube output.

**Comment by EZEBUILO** [comment]
The command is github/jenkins integration building with ant and json
plungin. The two failed

**Comment by spowelljr** [comment]
This looks like an ant issue `Buildfile: build.xml does not exist!` this doesn't seem to be related to minikube.

**Comment by EZEBUILO** [comment]
Is not minikube is an ant build command

**Comment by spowelljr** [comment]
This is the minikube project, you'd have to open an issue with the ant project.
