### ISSUE TITLE
Upgrade to Docker 1.13

### ISSUE THREAD

**Issue by zoidbergwill** [kubernetes/minikube#1691]
It would be awesome to use `--cache-from` with our 1+ GB PHP images.

As far as the k8s changelog goes, I see that 1.7 supports it.

Would I just need to make a PR like https://github.com/kubernetes/minikube/pull/1658 ?

**Comment by zoidbergwill** [comment]
Whoops, solved by https://github.com/kubernetes/minikube/pull/1542

**Comment by dlorenc** [comment]
Could you link to the kubernetes changelog? I see here: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG.md#external-dependency-version-information

Which doesn't say that 1.13 is supported. The tracking bug is still open afaict: https://github.com/kubernetes/kubernetes/issues/42926

**Comment by kilianc** [comment]
see https://github.com/kubernetes/minikube/pull/1542#issuecomment-318683859

> If you are stuck with this, you can preview the custom ISO with:
> 
>     $ minikube start --iso-url=https://storage.googleapis.com/minikube-builds/1542/minikube-testing.iso
> 
> Works perfectly for me! 🍻

**Comment by zoidbergwill** [comment]
Yeah, whoops, went down a rabbit hole and found those too, but never commented here. Nothing in the changelog and no progress on that issue. Hopefully 1.8 will support a couple newer versions.

**Comment by jgoclawski** [comment]
Update: Docker 1.13 and 17.03.2 have been "officially validated" for use with Kubernetes 1.8 in https://github.com/kubernetes/kubernetes/issues/42926

Changelog is being prepared in https://github.com/kubernetes/features/pull/408

**Comment by kilianc** [comment]
YAS!

![](https://s-media-cache-ak0.pinimg.com/originals/03/0e/88/030e8808f8c61d4145840f4ad2bd8629.jpg)

**Comment by nieldw** [comment]
FWIW, I wrote a short post about how to add an alternative docker client to connect to an older docker engine, like the one running in minikube at the moment. 

[Linux - Installing alternative versions of docker client](http://blog.bsg.co.za/2017/10/13/installing-alternative-versions-of-docker-client.html)

**Comment by r2d4** [comment]
This is fixed in the latest release
