### ISSUE TITLE
Regression in CNI auto select in v1.31.0

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#16911]
**Before:**
```
$ minikube start --driver docker --container-runtime=docker --version=v1.26.6
...
I0718 14:50:17.390765   41334 cni.go:157] "docker" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
...
```

**Now:**
```
$ minikube start --driver docker --container-runtime=docker --version=v1.26.6
...
I0718 14:49:13.457621   40145 cni.go:149] "docker" driver + "docker" runtime found, recommending kindnet
...
```

This is causing an increase in the time it takes to go from no cluster to a cluster created with an application deployed when using the docker driver and docker container runtime.

<img width="159" alt="Screenshot 2023-07-18 at 2 52 49 PM" src="https://github.com/kubernetes/minikube/assets/44844360/00ad0080-f10f-410e-95bd-6bb1969f4ffb">

Regression was introduced with https://github.com/kubernetes/minikube/pull/14780

**Comment by afbjorklund** [comment]
The old code had some weird path to choose a different CNI plugin for docker, just because it (used to) use dockershim.

Now it picks the same (slow) CNI plugin as for the other CRI runtimes... Maybe the default should be changed for all ?

**Comment by spowelljr** [comment]
Agreed, we should investigate into why we're using kindnet for non-docker runtimes on KIC.

**Comment by afbjorklund** [comment]
i.e. could be interesting to see what changing the default CNI plugin does to the startup time for containerd

**Comment by afbjorklund** [comment]
> Agreed, we should investigate into why we're using kindnet for non-docker runtimes on KIC.

I think that KIC has always kindnet, since it is based on kind (which has multi-node by default).
