### ISSUE TITLE
Unable to start minikube due to `invalid Host header` error

### ISSUE THREAD

**Issue by justinabrahms** [kubernetes/minikube#16949]
### What Happened?

When I try to start minikube, it errors due to a host header, then complains about not being able to rebuild b/c the container is in use.

Starting from a fresh minikube (e.g. `minikube delete`).. I run `minikube start --driver=docker --container-runtime cri-o` and it errors.

I'm running on nixos.

### Attach the log file

[logs2.txt](https://github.com/kubernetes/minikube/files/12157083/logs2.txt)

### Operating System

Other

### Driver

Docker

**Comment by poelzi** [comment]
I see the same

**Comment by justinabrahms** [comment]
This is an issue with docker on nixos. See issue here: https://github.com/NixOS/nixpkgs/issues/244159

This will be fixed in 23.05 when https://nixpk.gs/pr-tracker.html?pr=245179 lands, but there's a workaround for now at the bottom of the thread.
