### ISSUE TITLE
RSRC_INSUFFICIENT_CONTAINER_MEMORY

### ISSUE THREAD

**Issue by Karamlikith** [kubernetes/minikube#16958]
### What Happened?

I am not to run my minikube , and it is showing like this !!
⛔  Exiting due to RSRC_INSUFFICIENT_CONTAINER_MEMORY: docker only has 1771MiB available, less than the required 1800MiB for Kubernetes

### Attach the log file

I am not able to run this 👉 To start a cluster, run: "minikube start"

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Kubernetes needs 2 GiB memory, but at least 4 is recommended
