### ISSUE TITLE
The `NVIDIA GPU support` in readme is Not found

### ISSUE THREAD

**Issue by anda-ren** [kubernetes/minikube#16956]
### What Happened?

The doc claims there is `NVIDIA GPU support` ,but the link is not valid

> As well as developer-friendly features:
> 
> [Addons](https://minikube.sigs.k8s.io/docs/handbook/deploying/#addons) - a marketplace for developers to share configurations for running services on minikube
> [NVIDIA GPU support](https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/) - for machine learning
> [Filesystem mounts](https://minikube.sigs.k8s.io/docs/handbook/mount/)
> For more information, see the official [minikube website](https://minikube.sigs.k8s.io/)

![image](https://github.com/kubernetes/minikube/assets/89630947/359bb59a-7e48-4594-8011-b9943aa5f9ad)

### Attach the log file

![image](https://github.com/kubernetes/minikube/assets/89630947/359bb59a-7e48-4594-8011-b9943aa5f9ad)

### Operating System

None

### Driver

None

**Comment by afbjorklund** [comment]
It has been moved to https://minikube.sigs.k8s.io/docs/handbook/addons/nvidia/

commit cf976f6dd802dbc083259e64e8970cf2d95a62c5

` site/content/en/docs/{tutorials/nvidia_gpu.md => handbook/addons/nvidia.md}                        |   6 +--`

**Comment by anda-ren** [comment]
> It has been moved to https://minikube.sigs.k8s.io/docs/handbook/addons/nvidia/
> 
> commit [cf976f6](https://github.com/kubernetes/minikube/commit/cf976f6dd802dbc083259e64e8970cf2d95a62c5)
> 
> ` site/content/en/docs/{tutorials/nvidia_gpu.md => handbook/addons/nvidia.md} | 6 +--`

Thank you for point that out. I have raised a PR to fix the README hoping it will be merged.
