### ISSUE TITLE
accessing pod through nodeport in kubernetes in minikube from outside

### ISSUE THREAD

**Issue by premd91** [kubernetes/minikube#16952]
### What Happened?

not accessible showing.

### Attach the log file

not accessible showing.
![image](https://github.com/kubernetes/minikube/assets/133738728/00147a6a-0fb2-4a0e-a5fd-babeb52865df)

### Operating System

Ubuntu

### Driver

Docker

**Comment by kundan2707** [comment]
@premd91  information like  what steps you have taken pod status and all are missing.

**Comment by premd91** [comment]
Finally solved after a decade

**Comment by kundan2707** [comment]
closing as resolved
