### ISSUE TITLE
By default, minikube start --image-mirror-country cn command cannot be replaced with mirror images

### ISSUE THREAD

**Issue by CN-hao** [kubernetes/minikube#16950]
#### I tried to start minikube with Aliyun mirror images,but the kicbase image falls back to docker.

 ~/test  minikube start --image-mirror-country cn                                   
😄  Debian 10.10 上的 minikube v1.31.1
✨  自动选择 docker 驱动
✅  正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
📌  使用具有 root 权限的 Docker 驱动程序
👍  正在集群 minikube 中启动控制平面节点 minikube
🚜  正在拉取基础镜像 ...
    > index.docker.io/kicbase/sta...:  171.00 KiB / 447.62 MiB  0.04% 9.03 KiB ^C

### Attach the log file

I0725 12:21:44.886017  108046 image.go:177] daemon lookup for registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1: Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:v1.10.1
I0725 12:21:44.886112  108046 image.go:177] daemon lookup for registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9: Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9
I0725 12:21:44.886371  108046 image.go:177] daemon lookup for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.27.3: Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.27.3
I0725 12:21:44.886579  108046 image.go:177] daemon lookup for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.27.3: Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.27.3
I0725 12:21:44.886870  108046 image.go:177] daemon lookup for registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5: Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v5
I0725 12:21:44.886868  108046 image.go:177] daemon lookup for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.27.3: Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.27.3
I0725 12:21:44.887480  108046 image.go:177] daemon lookup for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.27.3: Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.27.3
I0725 12:21:44.887888  108046 image.go:177] daemon lookup for registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.7-0: Error response from daemon: No such image: registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.5.7-0
I0725 12:21:44.907153  108046 cache.go:150] Downloading registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 to local cache
I0725 12:21:44.907310  108046 image.go:63] Checking for registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 in local cache directory
I0725 12:21:44.907440  108046 image.go:118] Writing registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 to local cache
I0725 12:21:45.260897  108046 cache.go:169] failed to download registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631, will try fallback image if available: getting remote image: GET https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/kicbase/manifests/sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631: MANIFEST_UNKNOWN: manifest unknown; map[Name:google_containers/kicbase Revision:sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631]
I0725 12:21:45.260928  108046 image.go:79] Checking for docker.io/kicbase/stable:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 in local docker daemon
I0725 12:21:45.279149  108046 cache.go:150] Downloading docker.io/kicbase/stable:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 to local cache
I0725 12:21:45.279275  108046 image.go:63] Checking for docker.io/kicbase/stable:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 in local cache directory
I0725 12:21:45.279305  108046 image.go:118] Writing docker.io/kicbase/stable:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 to local cache
I0725 12:21:45.527874  108046 cache.go:162] opening:  /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/coredns_v1.10.1
I0725 12:21:45.530836  108046 cache.go:162] opening:  /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/pause_3.9
I0725 12:21:45.590239  108046 cache.go:162] opening:  /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver_v1.27.3
I0725 12:21:45.594672  108046 cache.go:162] opening:  /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/etcd_3.5.7-0
I0725 12:21:45.627275  108046 cache.go:162] opening:  /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy_v1.27.3
I0725 12:21:45.777056  108046 cache.go:162] opening:  /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager_v1.27.3
I0725 12:21:45.776946  108046 cache.go:162] opening:  /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner_v5
I0725 12:21:45.777375  108046 cache.go:162] opening:  /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler_v1.27.3
I0725 12:21:45.902955  108046 cache.go:157] /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/pause_3.9 exists
I0725 12:21:45.902982  108046 cache.go:96] cache image "registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9" -> "/home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/pause_3.9" took 1.018032675s
I0725 12:21:45.903000  108046 cache.go:80] save to tar file registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.9 -> /home/lwh/.minikube/cache/images/amd64/registry.cn-hangzhou.aliyuncs.com/google_containers/pause_3.9 succeeded

### Operating System

Deepin 20.09

### Driver

Docker

**Comment by brillience** [comment]
so how do you fix it?
