### ISSUE TITLE
minikube crash on M1 MacBook Pro

### ISSUE THREAD

**Issue by Jaff** [kubernetes/minikube#16961]
### What Happened?

Downloaded & installed per [Link](url):
```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-arm64
sudo install minikube-darwin-arm64 /usr/local/bin/minikube
```
Issued command to start:
```
minikube start --driver=docker
```
Observed result:
```
[1]    10215 segmentation fault  minikube start --driver=docker
``` 

### Attach the log file

[minikube_crash.log](https://github.com/kubernetes/minikube/files/12205507/minikube_crash.log)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
Looks like you have an old x86_64 binary left in the PATH: /Users/USER/*/minikube
