### ISSUE TITLE
inaccurate warning with Docker Desktop containerd integration

### ISSUE THREAD

**Issue by nicks** [kubernetes/minikube#16960]
### What Happened?

1. Start Docker Desktop
2. Go to settings -> features in development, and enable containerd integration
3. Start minikube with:

```
minikube start --driver=docker
```

Expected result:
No warnings

Actual result:

```
❗  docker is currently using the stargz storage driver, consider switching to overlay2 for better performance
```

Not sure why minikube dislikes the stargz storage driver? And typically, users wouldn't want to change the driver in docker desktop from stargz to overlay2?

### Attach the log file

n/a

### Operating System

macOS (Default)

### Driver

Docker

**Comment by rumpl** [comment]
Hi all, I work on the containerd integration and we are setting stargz as the default in docker desktop which uses overlay for normal images. 

Users on linux that enable the containerd image store would get overlay as the default containerd snapshotter and its name in that case is “overlayfs”.

**Comment by afbjorklund** [comment]
The warning is much older than the stargz changes, which should be added to the check (or remove it).

**Comment by rumpl** [comment]
IMO the best bet is to remove the check. There are many snapshotters and more to come, minikube can’t know them all.

**Comment by afbjorklund** [comment]
@rumpl : the main reason is for the preload, I'm not sure what the other "better performance" refers to...

commit 8ec8d1cd822cc79d9409e600fad5fec8a352ea14

* https://github.com/kubernetes/minikube/issues/7626

For the generic case, we might want to gather all of the "cache" (save) images into one single .tar.lz4 file ?

**Comment by afbjorklund** [comment]
> Users on linux that enable the containerd image store would get overlay as the default containerd snapshotter and its name in that case is “overlayfs”.

The containerd check was also using the docker check, so separated them:

* #16972

**Comment by afbjorklund** [comment]
I think it was checking the _wrong_ docker anyway, so now the preload is disabled for no particular reason...
The original issue was when using the "none" driver, not when using the "docker" driver

**Comment by spowelljr** [comment]
> I think it was checking the _wrong_ docker anyway, so now the preload is disabled for no particular reason... The original issue was when using the "none" driver, not when using the "docker" driver

I think this is contributing to the problem in https://github.com/kubernetes/minikube/issues/16425, there is obviously something wrong with preload=false and kubectl not being present on the machine, but the preload=false is being set when it seems like it shouldn't be, the cluster starts fine with the preload when using the stargz storage driver.
