### ISSUE TITLE
minikube deleting is hanging with v1.31.1

### ISSUE THREAD

**Issue by kashifest** [kubernetes/minikube#16975]
### What Happened?

minikube was started using kvm2 driver. Everything works fine until minikube delete command is issued . The command hangs forever. Only way to move forward is to restart libvirtd and then only minikube delete succeeds. 

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/12216040/log.txt)

### Operating System

Other

### Driver

KVM2

**Comment by rmsilva1973** [comment]
Hello. Can you try with the latest version to see if it still happens?

**Comment by kashifest** [comment]
> 

I am bumping the minikube in our CI. I will let you know if CI sees any hiccups.

**Comment by kashifest** [comment]
@rmsilva1973 we don't see the issue anymore with the new minikube version. Thanks for letting us know. This issue is good to close.
/close
