### ISSUE TITLE
minikube logs --file=logs.txt

### ISSUE THREAD

**Issue by gaddameedamahesh** [kubernetes/minikube#16984]
### What Happened?

minikube not getting started

### Attach the log file

❌  Exiting due to GUEST_START: failed to start node: Failed to check container runtime version: docker version --format <no value>: exit status 1
stdout:

stderr:
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/version": dial unix /var/run/docker.sock: connect: permission denied

### Operating System

Ubuntu

### Driver

None

**Comment by adilwahla** [comment]
I am also facing same kind of problem **Exiting due to K8S_INSTALL_FAILED**: for mine #16985
