### ISSUE TITLE
Is it possible to map `host.minikube.internal` to the docker desktop's VM instead of the actual host?

### ISSUE THREAD

**Issue by jalvespinto** [kubernetes/minikube#16989]
### What Happened?

I am running minikube with docker driver on the host where I have docker desktop installed and I am having trouble connecting to a service (postgres) that is running on a container inside docker desktop when using an ubuntu host, but it works fine if I am using macos. What I think it is going on is that, in the case of macos host, `host.minikube.internal` is mapping to the docker desktop VM, but, in the case of ubuntu, `host.minikube.internal` is mapping to the actual host (not docker desktop VM). Is it possible to map it to the VM (not to the host) when starting minikube (without having to edit /etc/hosts and iptables after starting it)?

### Attach the log file

On macos:
```
docker@minikube:~$ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.49.2	minikube
192.168.65.254	host.minikube.internal
192.168.49.2	control-plane.minikube.internal

docker@minikube:~$ sudo iptables -t nat -L DOCKER_OUTPUT
Chain DOCKER_OUTPUT (2 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             host.minikube.internal         tcp dpt:domain to:127.0.0.11:42949
DNAT       udp  --  anywhere             host.minikube.internal         udp dpt:domain to:127.0.0.11:34487
```
On ubuntu:
```
docker@minikube:~$ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
192.168.49.2	minikube
192.168.49.1	host.minikube.internal
192.168.49.2	control-plane.minikube.internal

docker@minikube:~$ sudo iptables -t nat -L DOCKER_OUTPUT
Chain DOCKER_OUTPUT (2 references)
target     prot opt source               destination         
DNAT       tcp  --  anywhere             192.168.65.2         tcp dpt:domain to:127.0.0.11:42949
DNAT       udp  --  anywhere            192.168.65.2         udp dpt:domain to:127.0.0.11:34487
```

### Operating System

None

### Driver

Docker

**Comment by afbjorklund** [comment]
There is no support for Docker Desktop on Linux in the network code, it assumes it is using Docker Engine.

https://github.com/kubernetes/minikube/blob/v1.31.1/pkg/drivers/kic/oci/network.go#L64
