### ISSUE TITLE
entering the command "minikube start --driver=hyperkit" get the result Error provisioning guest.

### ISSUE THREAD

**Issue by Delagrace** [kubernetes/minikube#17006]
### What Happened?

Fermeture en raison de GUEST_PROVISION : error provisioning guest: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for 6:c9:bf:58:e7:b6

### Attach the log file

Fermeture en raison de DRV_CP_ENDPOINT : Unable to get forwarded endpoint: failed to lookup ip for ""
💡  Suggestion : 

    Recréez le cluster en exécutant :
    minikube delete <no value>
    minikube start <no value>

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by caerulescens** [comment]
@Delagrace I am investigating `hyperkit` on `macos`, and I will report what I find.
