### ISSUE TITLE
Error generating signed cert: Unable to decode certificate.

### ISSUE THREAD

**Issue by deborasetton** [kubernetes/minikube#1702]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Minikube version** (use `minikube version`): v0.20.0

**Environment**:
- **OS**: Ubuntu 16.04.2 LTS
- **VM Driver**: kvm
- **ISO version**: v0.20.0

**What happened**: `minikube start --vm-driver=kvm` fails to start with the following error message:

```
Error configuring authentication:  Error generating certs: Error generating signed cert: Unable to decode certificate.
```

**What you expected to happen**: minikube should start successfully.

**Comment by deborasetton** [comment]
I ended up reinstalling everything so this error is not happening any more (for now, at least). Still, if anyone has any idea as to what the problem might have been, please leave a comment!, in case it happens again.

**Comment by danielfablius** [comment]
im having this issue too, is reinstalling everything means that u reinstall the OS too?

**Comment by deborasetton** [comment]
Hi @danielfablius, sorry for the delay! Yes, I reinstalled the OS too, but only because I was already going to do that anyway. So I went for the more drastic approach :)

Did you manage to find a way around this?
