### ISSUE TITLE
qemu not working on my M2 Mac

### ISSUE THREAD

**Issue by maitrid** [kubernetes/minikube#17020]
### What Happened?

It has "Unknown Error" when tried according to the instructions.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/12287082/logs.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by afbjorklund** [comment]
Looks like it tries to run the wrong architecture:

`Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: creating: qemu-system-x86_64: -accel hvf: Unknown Error: exit status 1`

That should have been aarch64

**Comment by caerulescens** [comment]
@maitrid The error you're receiving indicates that you have installed the incorrect minikube binary for your computer processor's architecture type; your laptop has an Apple M1 processor which uses arm64 for its processor's instruction set, which is also known as aarch64. You installed the minikube binary for 64-bit x86 architecture processors. When Apple switched from purchasing Intel processors to designing their own chips, their processor's architecture type changed from 64-bit x86 (amd64) to 64-bit arm (arm64). Apple computers with M series processors need to install the darwin/arm64 minikube binary. You should use either [Homebrew](https://formulae.brew.sh/formula/minikube) or [MacPorts](https://ports.macports.org/port/minikube/) to manage your minikube installation, and you won't have this issue going forward.

After installing the correct `minikube` binary, you can use `qemu2` driver and `socket_vmnet` network to get the essential `minikube` functionality on `macos` with m-series chips.

1. Install [qemu](https://formulae.brew.sh/formula/qemu).
2. Install [socket_vmnet](https://formulae.brew.sh/formula/socket_vmnet).
3. I think you will need to start the network like mentioned [here](https://minikube.sigs.k8s.io/docs/drivers/qemu/#install-socket_vmnet-via-brewhttpsbrewsh) in the docs.
4. Run `minikube start --driver=qemu2 --network=socket_vmnet`
5. Test `minikube tunnel` in a separate terminal window.

**Comment by caerulescens** [comment]
This is not an issue with `minikube`; an `amd64` binary is being run on `arm64` host.

/close
