### ISSUE TITLE
Getting error related to API Server while starting Minikube

### ISSUE THREAD

**Issue by ravishankar1jan** [kubernetes/minikube#17037]
### What Happened?

I have installed Minikube on MacBookPro-M2 however while starting Minikube it's throwing following error.

onfiguring bridge CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
E0810 15:28:14.303776    3054 start.go:219] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: non-retryable failure while getting "coredns" deployment scale: Get "https://10.0.2.15:8443/apis/apps/v1/namespaces/kube-system/deployments/coredns/scale": dial tcp 10.0.2.15:8443: i/o timeout
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://10.0.2.15:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 10.0.2.15:8443: i/o timeout]
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/12311555/log.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by pascalrobert** [comment]
I have the exact same problem on a MBP M1 Pro, macOS 14.4.1, when minikube is started with --network socket_vmnet
