### ISSUE TITLE
Unable to load cached images with Apple Silicon & Minikube v1.31.1 

### ISSUE THREAD

**Issue by conradwt** [kubernetes/minikube#17048]
### What Happened?

When I attempt to install K8s v1.27.4 with 

```zsh
minikube delete -p test-cluster && rm -rf ~/.minikube/cache/preloaded-tarball && minikube start --profile=test-cluster --kubernetes-version=v1.27.4 --alsologtostderr
```

I'm seeing the following issue within the logs:

```text
W0812 18:36:29.616444   12686 out.go:239] ❌  Unable to load cached images: loading cached images: stat /Users/conradwt/.minikube/cache/images/arm64/registry.k8s.io/kube-proxy_v1.27.4: no such file or directory
```

Finally, this appears to be an issue on Apple Silicon because things work as expected on my Intel MacBook Pro.  Further, I started having this issue with the release of K8s v1.26.4.  Thus, the latest release that I can install is K8s v1.26.3 at this time.

### Attach the log file

https://gist.github.com/conradwt/58479830fd57d1a0a079926c53b15301

### Operating System

macOS (Default)

### Driver

Docker

**Comment by conradwt** [comment]
I'm seeing a similar issue in regards to `etcd`:

```zsh
Unable to load cached images: loading cached images: stat /Users/conradwt/.minikube/cache/images/arm64/registry.k8s.io/etcd_3.5.10-0: no such file or directory
```

BTW, I'm using k8s v1.29.3.

Is there some underlying issue with downloading and caching images?

**Comment by afbjorklund** [comment]
It is a bug with the fallback images, when the preload is broken.

* https://github.com/kubernetes/minikube/pull/16925
