### ISSUE TITLE
Minikube failing to start

### ISSUE THREAD

**Issue by SeanTheFycking** [kubernetes/minikube#17040]
### What Happened?

![Screenshot 2023-08-10 at 21 09 26](https://github.com/kubernetes/minikube/assets/118750979/22fb1d27-4899-4845-aa24-a6df51e61c89)

### Attach the log file

E0810 21:06:57.353529   76691 logs.go:192] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.26.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.26.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1

### Operating System

macOS (Default)

### Driver

Docker

**Comment by rmsilva1973** [comment]
@SeanTheFycking  please attache logs.txt file to the issue.
