### ISSUE TITLE
Error starting minikube

### ISSUE THREAD

**Issue by srdegbe** [kubernetes/minikube#17047]
### What Happened?

[logs.txt](https://github.com/kubernetes/minikube/files/12328487/logs.txt)

### Attach the log file

Exiting due to RUNTIME_ENABLE: Failed to enable container runtime: sudo systemctl restart docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

### Operating System

None

### Driver

None

**Comment by rmsilva1973** [comment]
@srdegbe If you run "sudo systemctl restart docker" and "journalctl -xe" what's the output?
