### ISSUE TITLE
erorr 

### ISSUE THREAD

**Issue by Ahmed360L** [kubernetes/minikube#17045]
### What Happened?

when i type this command  minikube addons enable ingres
I get an error.

### Attach the log file

minikube addons enable ingres

❌  Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: ingres is not a valid addon

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_addons_59c9479b95d5e4c2717c42648e2efc46a304865c_0.log                  │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Other

### Driver

Docker

**Comment by Ahmed360L** [comment]
it is mint distro by the way

**Comment by rmsilva1973** [comment]
@Ahmed360L Please attach logs.txt to the issue. Also: what SO are you running on?
