### ISSUE TITLE
Error in Minikube delete

### ISSUE THREAD

**Issue by ozoz77** [kubernetes/minikube#17076]
### What Happened?

Using the minikube version 1.31.1 please follow these steps:

1- Install minikube on a new server, (without docker installed)
2-Test your installation with minikube start (that will create minikube environment with the default driver (in my case it was qemu2)
3- Install Docker
4- set MINIKUBE_HOME dir other than default directory (/home/$USER/.minikube),
5- start minikube with the "--driver docker" option
6- Gives an error with the prviouse drvier was qemu2, so please use minikube delete
7- Use minikube delete --purge --all 
8- Retry start with minikube start --driver docker
9- Same error occurs because the minikube delete command olny deletes the default MINIKUBE_HOME (/home/$USER/.minikube) but if the MINIKUBE_HOME has changed it does not remove the new path. and the minikube start continues to give errors.

After manually removing the MINIKUBE_HOME directory, the error has just gone...

Possible Solution
**Minikube delete has to delete the MINIKUBE_HOME path as well...

### Attach the log file

No log 

### Operating System

Ubuntu

### Driver

Docker

**Comment by caerulescens** [comment]
@ozoz77 I will attempt to verify your steps on Debian.
