### ISSUE TITLE
Macbook Pro M2 Max |  "Exiting due to DRV_UNSUPPORTED_OS: The driver 'virtualbox' is not supported on darwin/arm64"

### ISSUE THREAD

**Issue by pawankulaura** [kubernetes/minikube#17096]
pawan@Pawans-MacBook-Pro Downloads % where kubectl

/usr/local/bin/kubectl
pawankulaura@Pawans-MacBook-Pro Downloads % curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-arm64
sudo install minikube-darwin-arm64 /usr/local/bin/minikube

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 80.3M  100 80.3M    0     0  4752k      0  0:00:17  0:00:17 --:--:-- 5668k
pawan@Pawans-MacBook-Pro Downloads % minikube start
😄  minikube v1.31.2 on Darwin 13.3 (arm64)

✨  Automatically selected the virtualbox driver

❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'virtualbox' is not supported on darwin/arm64

**Comment by afbjorklund** [comment]
VirtualBox only supports amd64, so you need to use another driver.

**Comment by spowelljr** [comment]
Since VirtualBox doesn't support arm64 I'm going to close this issue
