### ISSUE TITLE
minikube not supported  virtualization by using VMware as hypervisors on linux.

### ISSUE THREAD

**Issue by AffanAminPK** [kubernetes/minikube#17104]
### What Happened?

![2023-08-21_16-11](https://github.com/kubernetes/minikube/assets/59292298/d5961129-8a42-40b9-8ee0-322a1a1fd7a8)

### Attach the log file

minikube start --driver vmware
* minikube v1.31.2 on Ubuntu 22.04
* Using the vmware driver based on user configuration

* Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in $PATH
* Suggestion: Install vmrun
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

### Operating System

Ubuntu

### Driver

VMware

**Comment by pshiki** [comment]
very interest, that in manjaro (installed vmware workstation pro hypervisor) minikube will started normally 
minikube start --driver=vmware
but in VMWare workstation GUI I don't visualize minikube created vm...
