### ISSUE TITLE
minikube addon ingress fails

### ISSUE THREAD

**Issue by lbu32** [kubernetes/minikube#17119]
### What Happened?

minikube addons enable ingress

is not possible: Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: context deadline exceeded]
W0824 11:06:20.371222  203679 out.go:239] 

### Attach the log file

I0824 11:06:16.369257  203679 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0824 11:06:16.865842  203679 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0824 11:06:17.369396  203679 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0824 11:06:17.871495  203679 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0824 11:06:18.365816  203679 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0824 11:06:18.869575  203679 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0824 11:06:19.365948  203679 kapi.go:86] Found 2 Pods for label selector app.kubernetes.io/name=ingress-nginx
I0824 11:06:19.365955  203679 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0824 11:06:19.868140  203679 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0824 11:06:20.353287  203679 kapi.go:107] duration metric: took 6m0.000970312s to wait for app.kubernetes.io/name=ingress-nginx ...
I0824 11:06:20.366281  203679 out.go:177] 
W0824 11:06:20.371125  203679 out.go:239] ❌  Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: context deadline exceeded]
W0824 11:06:20.371222  203679 out.go:239] 

### Operating System

Ubuntu

### Driver

None

**Comment by rmsilva1973** [comment]
Hello. Please run "minikube logs --file=log.txt" and attach (not paste) the generated log file to the issue.

**Comment by spowelljr** [comment]
Hi @lbu32, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by mnguyen081002** [comment]
#17372
