### ISSUE TITLE
Not able to install minikube help required .

### ISSUE THREAD

**Issue by PrabhanjanSangam** [kubernetes/minikube#17139]
### What Happened?

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 if i use this commnad then the final result is 
curl: (23) Failure writing output to destination
install: cannot stat 'minikube-linux-amd64': No such file or directory
if i run this command 
wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
i get the result as this 
HTTP request sent, awaiting response... 200 OK
Length: 86435564 (82M) [application/octet-stream]
minikube-linux-amd64: Permission denied

can u tell me what can I do ,I am new to this minikube tool.
If there is another command do tell.

### Attach the log file

minikube logs --file=log.txt
when  i ran this command this is what i got:
Command 'minikube' not found, did you mean:
  command 'minitube' from deb minitube (3.9.1-1)
Try: sudo apt install <deb name>

### Operating System
Ubuntu

### Driver

None

**Comment by PrabhanjanSangam** [comment]
I really want to learn more about minikube.

**Comment by rmsilva1973** [comment]
You seen to be trying to download minikube to a directory you don't have write permission too. Which directory are you in? Change to your home directory first with "cd ~"

**Comment by PrabhanjanSangam** [comment]
It worked ,Thank you
