### ISSUE TITLE
Minikube not starting. keeps giving error

### ISSUE THREAD

**Issue by Abbeydauda20** [kubernetes/minikube#17138]
### What Happened?

There seems to be a conflict between Virtualbox and hyperv, i have tried to delete virtualbox to ran the command afterwards but same result

### Attach the log file

* Failed to start hyperv VM. Running "minikube delete" may fix it: recreate: creating host: create: creating: exit status 1
! Startup with hyperv driver failed, trying with alternate driver virtualbox: Failed to start host: recreate: creating host: create: creating: exit status 1
E0825 16:42:49.545468    9680 main.go:137] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V encountered an error trying to access an object on computer 'ABBEY' because the object was not found. The object might have been deleted, or you might not have permission to perform
the task. Verify that the Virtual Machine Management service on the computer is running. If the service is running, try to perform the task again by using Run as Administrator.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVM

Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

! Failed to delete cluster minikube, proceeding with retry anyway.
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

X Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: recreate: creating host: create: creating: exit status 1

### Operating System

Windows

### Driver

Hyper-V

**Comment by rmsilva1973** [comment]
Hi! What were the exact commands you used to start minikube?

**Comment by thrishul1989** [comment]
use this command to start it minikube start --virtualbox-no-vtx-check

**Comment by spowelljr** [comment]
Hi @Abbeydauda20, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
