### ISSUE TITLE
Arrk linux we

### ISSUE THREAD

**Issue by Lyllt8** [kubernetes/minikube#17158]
git clone [url]

**Comment by rmsilva1973** [comment]
@Lyllt8 Hi. Can you explain what is the issue you're having?

**Comment by justinclift** [comment]
Note that this user appears to be a bot, creating issues with random text in repos. :frowning:

(found by them submitting multiple issues like this to the sqlitebrowser repos)

I've just reported this account to GitHub ("spammer").  Hopefully they'll nuke it.
