### ISSUE TITLE
Minikube start command is not working

### ISSUE THREAD

**Issue by sureshops111** [kubernetes/minikube#17155]
### What Happened?

root@ip-172-31-7-230:~# minikube start --vm-driver=none
😄  minikube v1.31.2 on Ubuntu 22.04 (xen/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 22.04.2 LTS

❌  Exiting due to RUNTIME_ENABLE: Failed to enable container runtime: sudo systemctl restart cri-docker: exit status 1
stdout:

stderr:
Job for cri-docker.service failed because the control process exited with error code.
See "systemctl status cri-docker.service" and "journalctl -xeu cri-docker.service" for details.

### Attach the log file

*
* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|---------------------|
| Command |       Args       | Profile  | User | Version |     Start Time      |      End Time       |
|---------|------------------|----------|------|---------|---------------------|---------------------|
| start   | --vm-driver=none | minikube | root | v1.31.2 | 30 Aug 23 04:02 UTC |                     |
| start   | --vm-driver=none | minikube | root | v1.31.2 | 30 Aug 23 04:03 UTC |                     |
| start   | --vm-driver=none | minikube | root | v1.31.2 | 30 Aug 23 04:05 UTC |                     |
| delete  |                  | minikube | root | v1.31.2 | 30 Aug 23 04:06 UTC | 30 Aug 23 04:06 UTC |
| start   | --vm-driver=none | minikube | root | v1.31.2 | 30 Aug 23 04:06 UTC |                     |
| start   | --vm-driver=none | minikube | root | v1.31.2 | 30 Aug 23 04:07 UTC |                     |
| start   | --vm-driver=none | minikube | root | v1.31.2 | 30 Aug 23 04:11 UTC |                     |
| start   |                  | minikube | root | v1.31.2 | 30 Aug 23 04:11 UTC |                     |
| stop    |                  | minikube | root | v1.31.2 | 30 Aug 23 04:13 UTC | 30 Aug 23 04:13 UTC |
| start   |                  | minikube | root | v1.31.2 | 30 Aug 23 04:13 UTC |                     |
| start   |                  | minikube | root | v1.31.2 | 30 Aug 23 04:13 UTC |                     |
| start   |                  | minikube | root | v1.31.2 | 30 Aug 23 04:17 UTC |                     |
| start   |                  | minikube | root | v1.31.2 | 30 Aug 23 04:19 UTC |                     |
| delete  |                  | minikube | root | v1.31.2 | 30 Aug 23 04:26 UTC | 30 Aug 23 04:26 UTC |
| start   | --driver=docker  | minikube | root | v1.31.2 | 30 Aug 23 04:26 UTC |                     |
| start   | --vm-driver=none | minikube | root | v1.31.2 | 30 Aug 23 04:27 UTC |                     |
|---------|------------------|----------|------|---------|---------------------|---------------------|

*
* ==> Last Start <==
* Log file created at: 2023/08/30 04:27:15
Running on machine: ip-172-31-7-230
Binary: Built with gc go1.20.7 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0830 04:27:15.753784   12644 out.go:296] Setting OutFile to fd 1 ...
I0830 04:27:15.753941   12644 out.go:348] isatty.IsTerminal(1) = true
I0830 04:27:15.753946   12644 out.go:309] Setting ErrFile to fd 2...
I0830 04:27:15.753953   12644 out.go:348] isatty.IsTerminal(2) = true
I0830 04:27:15.754183   12644 root.go:338] Updating PATH: /root/.minikube/bin
W0830 04:27:15.754316   12644 root.go:314] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0830 04:27:15.754504   12644 out.go:303] Setting JSON to false
I0830 04:27:15.755264   12644 start.go:128] hostinfo: {"hostname":"ip-172-31-7-230","uptime":1864,"bootTime":1693367772,"procs":113,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.19.0-1025-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec229114-9b3f-59b6-9e6f-40d0c605fa5f"}
I0830 04:27:15.755328   12644 start.go:138] virtualization: xen guest
I0830 04:27:15.758882   12644 out.go:177] 😄  minikube v1.31.2 on Ubuntu 22.04 (xen/amd64)
W0830 04:27:15.762191   12644 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0830 04:27:15.762380   12644 notify.go:220] Checking for updates...
I0830 04:27:15.763345   12644 config.go:182] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.27.4
I0830 04:27:15.763641   12644 exec_runner.go:51] Run: systemctl --version
I0830 04:27:15.766128   12644 driver.go:373] Setting default libvirt URI to qemu:///system
I0830 04:27:15.769002   12644 out.go:177] ✨  Using the none driver based on existing profile
I0830 04:27:15.771405   12644 start.go:298] selected driver: none
I0830 04:27:15.771412   12644 start.go:902] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.27.4 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:172.31.7.230 Port:8443 KubernetesVersion:v1.27.4 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP: SSHAuthSock: SSHAgentPID:0}
I0830 04:27:15.771498   12644 start.go:913] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0830 04:27:15.771520   12644 start.go:1670] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0830 04:27:15.772080   12644 cni.go:84] Creating CNI manager for ""
I0830 04:27:15.772094   12644 cni.go:158] "none" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
I0830 04:27:15.772114   12644 start_flags.go:319] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.27.4 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:172.31.7.230 Port:8443 KubernetesVersion:v1.27.4 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP: SSHAuthSock: SSHAgentPID:0}
I0830 04:27:15.775145   12644 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0830 04:27:15.777313   12644 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0830 04:27:15.777573   12644 start.go:365] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0830 04:27:15.777656   12644 start.go:369] acquired machines lock for "minikube" in 59.036µs
I0830 04:27:15.777711   12644 start.go:96] Skipping create...Using existing machine configuration
I0830 04:27:15.777724   12644 fix.go:54] fixHost starting:
W0830 04:27:15.777897   12644 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0830 04:27:15.777906   12644 api_server.go:166] Checking apiserver status ...
I0830 04:27:15.777935   12644 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0830 04:27:15.794843   12644 api_server.go:170] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0830 04:27:15.794880   12644 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0830 04:27:15.808038   12644 fix.go:102] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0830 04:27:15.808054   12644 fix.go:128] unexpected machine state, will restart: <nil>
I0830 04:27:15.815514   12644 out.go:177] 🔄  Restarting existing none bare metal machine for "minikube" ...
I0830 04:27:15.819353   12644 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0830 04:27:15.819514   12644 start.go:300] post-start starting for "minikube" (driver="none")
I0830 04:27:15.819553   12644 start.go:329] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0830 04:27:15.819593   12644 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0830 04:27:15.829951   12644 main.go:141] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0830 04:27:15.829979   12644 main.go:141] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0830 04:27:15.829990   12644 main.go:141] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0830 04:27:15.836593   12644 out.go:177] ℹ️  OS release is Ubuntu 22.04.2 LTS
I0830 04:27:15.839345   12644 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0830 04:27:15.839407   12644 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0830 04:27:15.839433   12644 start.go:303] post-start completed in 19.9095ms
I0830 04:27:15.839441   12644 fix.go:56] fixHost completed within 61.72362ms
I0830 04:27:15.839447   12644 start.go:83] releasing machines lock for "minikube", held for 61.781974ms
I0830 04:27:15.839808   12644 exec_runner.go:51] Run: sh -c "stat /etc/cni/net.d/*loopback.conf*"
I0830 04:27:15.840083   12644 exec_runner.go:51] Run: curl -sS -m 2 https://registry.k8s.io/
I0830 04:27:15.849219   12644 exec_runner.go:51] Run: sudo find /etc/cni/net.d -maxdepth 1 -type f -name *loopback.conf* -not -name *.mk_disabled -exec sh -c "grep -q loopback {} && ( grep -q name {} || sudo sed -i '/"type": "loopback"/i \ \ \ \ "name": "loopback",' {} ) && sudo sed -i 's|"cniVersion": ".*"|"cniVersion": "1.0.0"|g' {}" ;
I0830 04:27:15.874703   12644 cni.go:230] loopback cni configuration patched: "/etc/cni/net.d/*loopback.conf*" found
I0830 04:27:15.874784   12644 exec_runner.go:51] Run: sudo find /etc/cni/net.d -maxdepth 1 -type f ( ( -name *bridge* -or -name *podman* ) -and -not -name *.mk_disabled ) -printf "%!p(MISSING), " -exec sh -c "sudo mv {} {}.mk_disabled" ;
I0830 04:27:15.885275   12644 cni.go:259] no active bridge cni configs found in "/etc/cni/net.d" - nothing to disable
I0830 04:27:15.885290   12644 start.go:466] detecting cgroup driver to use...
I0830 04:27:15.885332   12644 detect.go:199] detected "systemd" cgroup driver on host os
I0830 04:27:15.885447   12644 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0830 04:27:15.906835   12644 exec_runner.go:51] Run: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml"
W0830 04:27:15.919103   12644 start.go:433] cannot ensure containerd is configured properly and reloaded for docker - cluster might be unstable: update sandbox_image: sh -c "sudo sed -i -r 's|^( *)sandbox_image = .*$|\1sandbox_image = "registry.k8s.io/pause:3.9"|' /etc/containerd/config.toml": exit status 2
stdout:

stderr:
sed: can't read /etc/containerd/config.toml: No such file or directory
I0830 04:27:15.919118   12644 start.go:466] detecting cgroup driver to use...
I0830 04:27:15.919150   12644 detect.go:199] detected "systemd" cgroup driver on host os
I0830 04:27:15.919252   12644 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0830 04:27:15.941925   12644 exec_runner.go:51] Run: which cri-dockerd
I0830 04:27:15.942980   12644 exec_runner.go:51] Run: sudo mkdir -p /etc/systemd/system/cri-docker.service.d
I0830 04:27:15.953911   12644 exec_runner.go:144] found /etc/systemd/system/cri-docker.service.d/10-cni.conf, removing ...
I0830 04:27:15.953925   12644 exec_runner.go:203] rm: /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0830 04:27:15.953981   12644 exec_runner.go:151] cp: memory --> /etc/systemd/system/cri-docker.service.d/10-cni.conf (195 bytes)
I0830 04:27:15.954112   12644 exec_runner.go:51] Run: sudo cp -a /tmp/minikube3254840142 /etc/systemd/system/cri-docker.service.d/10-cni.conf
I0830 04:27:15.964217   12644 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0830 04:27:16.202696   12644 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0830 04:27:16.460837   12644 docker.go:535] configuring docker to use "systemd" as cgroup driver...
I0830 04:27:16.460863   12644 exec_runner.go:144] found /etc/docker/daemon.json, removing ...
I0830 04:27:16.460870   12644 exec_runner.go:203] rm: /etc/docker/daemon.json
I0830 04:27:16.460931   12644 exec_runner.go:151] cp: memory --> /etc/docker/daemon.json (143 bytes)
I0830 04:27:16.461081   12644 exec_runner.go:51] Run: sudo cp -a /tmp/minikube1208422488 /etc/docker/daemon.json
I0830 04:27:16.472257   12644 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0830 04:27:16.723315   12644 exec_runner.go:51] Run: sudo systemctl restart docker
I0830 04:27:17.180936   12644 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0830 04:27:17.434919   12644 exec_runner.go:51] Run: sudo systemctl unmask cri-docker.socket
I0830 04:27:17.683143   12644 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0830 04:27:17.947208   12644 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0830 04:27:18.211188   12644 exec_runner.go:51] Run: sudo systemctl restart cri-docker.socket
I0830 04:27:18.241333   12644 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0830 04:27:18.479351   12644 exec_runner.go:51] Run: sudo systemctl restart cri-docker
I0830 04:27:18.582465   12644 out.go:177]
W0830 04:27:18.588696   12644 out.go:239] ❌  Exiting due to RUNTIME_ENABLE: Failed to enable container runtime: sudo systemctl restart cri-docker: exit status 1
stdout:

stderr:
Job for cri-docker.service failed because the control process exited with error code.
See "systemctl status cri-docker.service" and "journalctl -xeu cri-docker.service" for details.

W0830 04:27:18.588979   12644 out.go:239]
W0830 04:27:18.590069   12644 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0830 04:27:18.592403   12644 out.go:177]

### Operating System

None

### Driver

None

**Comment by afbjorklund** [comment]
> See "systemctl status cri-docker.service" and "journalctl -xeu cri-docker.service" for details.

Looks like a problem with cri-dockerd, verify with `crictl version` or something like that...

**Comment by thrishul1989** [comment]
try to restart thr machine and enable the container runtime using this commmand sudo systemctl restart cri-docker

**Comment by spowelljr** [comment]
Hi @sureshops111, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
