### ISSUE TITLE
Fail to enable ingress on Ubuntu VM - exiting due to MK_ADDON_ENABLE

### ISSUE THREAD

**Issue by EndyCZ** [kubernetes/minikube#17159]
### What Happened?

Hello, I have fresh VM instalation of Ubuntu 22 that I just donwloaded from ubuntu.com. I have updated all packages after installing the OS from image. Then I installed Docker. And then I installed minikube. Then I installed kubectl. Then I started the minikube using `minikube start`. So far so good. I was able to interact with cluster using kubectl and even start the minikube dashboard.

When enabling ingress I get

`❌  Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: context deadline exceeded]`

Attached are logs. 

Can you give me hints what am I doing wrong?

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/12481969/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by rmsilva1973** [comment]
Hi. Looking at the logs I saw a bunch of timeouts connecting to the ingress repo at https://us-west2-docker.pkg.dev. I suspect there seems to be a network connectivity issue between your machine and the repo (it may have been something transient). Are you able to do a "wget https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/ingress-nginx/kube-webhook-certgen/manifests/sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b" from your Ubuntu?

If you are able to do it, do you think you can do a "minikube delete" and try again?

**Comment by gsowjanya97** [comment]
Hi @rmsilva1973, I would like to contribute to this issue. But am new to open source contribution, can you tell me what I need to do for 'triage needs-information'

**Comment by rmsilva1973** [comment]
@gsowjanya97 Hi! As I understand (I'm not a maintainer) it's a label we apply to issues we began triaging but still need additional information to be able to reproduce (or even identify if it's really an issue).

That's what I'm used to on my scarce experience on github. On the README.md on the repo root there's also pointers to some triage meetups, altough I never attended to one myself.

**Comment by EndyCZ** [comment]
Hi @rmsilva1973, indeed that could be the problem. I am currently visiting china and  probably the firewall does not allow me to get the artifacts.

Here is the output

```console
$ wget https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/ingress-nginx/kube-webhook-certgen/manifests/sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b
--2023-09-04 07:42:38--  https://us-west2-docker.pkg.dev/v2/k8s-artifacts-prod/images/ingress-nginx/kube-webhook-certgen/manifests/sha256:543c40fd093964bc9ab509d3e791f9989963021f1e9e4c9c7b6700b02bfb227b
Resolving us-west2-docker.pkg.dev (us-west2-docker.pkg.dev)... 172.217.194.82, 2404:6800:4003:c04::52
Connecting to us-west2-docker.pkg.dev (us-west2-docker.pkg.dev)|172.217.194.82|:443... connected.

OpenSSL: error:0A000126:SSL routines::unexpected eof while reading
Unable to establish SSL connection.

```

Thanks for investigating. I am not sure if there are any hints how to install minikube in china then. 

I guess we can close this issue as we found the root cause of the problem.

**Comment by rmsilva1973** [comment]
@EndyCZ you're welcome. However only the author (and I think the maintainers perhaps) can close an issue. You can go ahead and do it. 👍

**Comment by spowelljr** [comment]
For more information, we have a FAQ entry on our website if trying to start minikube from China

https://minikube.sigs.k8s.io/docs/faq/#i-am-in-china-and-i-encounter-errors-when-trying-to-start-minikube-what-should-i-do
