### ISSUE TITLE
[1.28] After updating docker-desktop Minikube not able to start 

### ISSUE THREAD

**Issue by Omkar0114** [kubernetes/minikube#17157]
### What Happened?

In the last few days, I installed CRI-O and at that time I updated the docker desktop as getting a version compatibility error. Right now I want to run minikube with docker as runtime but am not able to start up minikube as giving `Exiting due to RUNTIME_ENABLE: sudo systemctl restart cri-docker: Process exited with status 1
` 
Thanks.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/12474841/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by medyagh** [comment]
[Omkar0114](https://github.com/Omkar0114) you are using a very old version of minikube ( v1.28.0 ), can you try with new version
and minikube deletre --all ?

**Comment by Omkar0114** [comment]
Oh. Sure I'll try a new version of minikube. First will delete the older version

**Comment by thrishul1989** [comment]
You can reomove the CRI-O or docker desktop anyone and try to start the minikube

can you tell me docker desktop your using in ubuntu or windows machine

**Comment by Omkar0114** [comment]
Hey @thrishul1989 I am using Docker Desktop on Ubuntu. I `minikube delete --all` and then download latest version of Ubuntu and right now works fine with `minikube start --container-runtime=docker`

**Comment by spowelljr** [comment]
Docker Desktop support on Linux wasn't added until v1.29.0, so I'm going to close this issue.
