### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by danilovpavel1996** [kubernetes/minikube#17160]
### What Happened?

(base) danilovpavel@Pauls-MacBook-Pro ~ % curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 81.2M  100 81.2M    0     0  9353k      0  0:00:08  0:00:08 --:--:-- 10.3M
(base) danilovpavel@Pauls-MacBook-Pro ~ % sudo install minikube-darwin-amd64 /usr/local/bin/minikube

Password:
(base) danilovpavel@Pauls-MacBook-Pro ~ % minikube start

😄  minikube v1.31.2 on Darwin 13.5.1
✨  Using the virtualbox driver based on existing profile

💣  Exiting due to PROVIDER_VIRTUALBOX_NOT_RUNNING: "/usr/local/bin/VBoxManage --version" returned: <nil>
💡  Suggestion: Restart VirtualBox, or upgrade to the latest version of VirtualBox
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

(base) danilovpavel@Pauls-MacBook-Pro ~ % minikube start
W0831 23:28:53.348735    9832 main.go:291] Unable to resolve the current Docker CLI context "default": context "default": context not found: open /Users/danilovpavel/.docker/contexts/meta/37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f/meta.json: no such file or directory
😄  minikube v1.31.2 on Darwin 13.5.1
✨  Using the virtualbox driver based on existing profile
❗  Due to changes in macOS 13+ minikube doesn't currently support VirtualBox. You can use alternative drivers such as docker or hyperkit.
    https://minikube.sigs.k8s.io/docs/drivers/docker/
    https://minikube.sigs.k8s.io/docs/drivers/hyperkit/

    For more details on the issue see: https://github.com/kubernetes/minikube/issues/15274

👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: Maximum number of retries (5) exceeded
🏃  Updating the running virtualbox "minikube" VM ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: Machine does not have a host-only adapter

❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Machine does not have a host-only adapter

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

(base) danilovpavel@Pauls-MacBook-Pro ~ % 

### Attach the log file

[Ieșire salvată Terminal.txt](https://github.com/kubernetes/minikube/files/12490168/Ie.ire.salvata.Terminal.txt)

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by rmsilva1973** [comment]
Hi! If you read the error message from the output you'll see this:

"Due to changes in macOS 13+ minikube doesn't currently support VirtualBox. You can use alternative drivers such as docker or hyperkit."

Try running with docker or hyperkit driver like suggested on the output. The output message provides the links to both of them.

**Comment by spowelljr** [comment]
Since minikube doesn't support VirtualBox on macOS 13+ I'm going to close this issue

**Comment by danilovpavel1996** [comment]
Thanks everybody !
