### ISSUE TITLE
 Failed to cache ISO on v1.31.2

### ISSUE THREAD

**Issue by ThabtiZahra** [kubernetes/minikube#17169]
### What Happened?

: Failed to cache ISO: unable to cache ISO:
  https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso?checksum=file:https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso.sha256 Dst:C:\Users\user\.minikube\cache\iso\amd64\minikube-v1.31.0-amd64.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8] Decompressors:map[bz2:0xc00058bdc8 gz:0xc00058be20 tar:0xc00058bdd0 tar.bz2:0xc00058bde0 tar.gz:0xc00058bdf0 tar.xz:0xc00058be00 tar.zst:0xc00058be10 tbz2:0xc00058bde0 tgz:0xc00058bdf0 txz:0xc00058be00 tzst:0xc00058be10 xz:0xc00058be28 zip:0xc00058be40 zst:0xc00058be50] Getters:map[file:0xc000756380 http:0xc001206190 https:0xc0012061e0] Dir:false ProgressListener:0x49c3370 Insecure:false DisableSymlinks:false Options:[0x1d41520]}: invalid checksum: Error downloading checksum file: bad response code: 404
  https://github.com/kubernetes/minikube/releases/download/v1.31.0/minikube-v1.31.0-amd64.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.31.0/minikube-v1.31.0-amd64.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.31.0/minikube-v1.31.0-amd64.iso.sha256 Dst:C:\Users\user\.minikube\cache\iso\amd64\minikube-v1.31.0-amd64.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8] Decompressors:map[bz2:0xc00058bdc8 gz:0xc00058be20 tar:0xc00058bdd0 tar.bz2:0xc00058bde0 tar.gz:0xc00058bdf0 tar.xz:0xc00058be00 tar.zst:0xc00058be10 tbz2:0xc00058bde0 tgz:0xc00058bdf0 txz:0xc00058be00 tzst:0xc00058be10 xz:0xc00058be28 zip:0xc00058be40 zst:0xc00058be50] Getters:map[file:0xc00138a090 http:0xc000e94b40 https:0xc000e94b90] Dir:false ProgressListener:0x49c3370 Insecure:false DisableSymlinks:false Options:[0x1d41520]}: stream error: stream ID 1; PROTOCOL_ERROR; received from peer
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.31.0-amd64.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.31.0-amd64.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.31.0-amd64.iso.sha256 Dst:C:\Users\user\.minikube\cache\iso\amd64\minikube-v1.31.0-amd64.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8] Decompressors:map[bz2:0xc00058bdc8 gz:0xc00058be20 tar:0xc00058bdd0 tar.bz2:0xc00058bde0 tar.gz:0xc00058bdf0 tar.xz:0xc00058be00 tar.zst:0xc00058be10 tbz2:0xc00058bde0 tgz:0xc00058bdf0 txz:0xc00058be00 tzst:0xc00058be10 xz:0xc00058be28 zip:0xc00058be40 

### Attach the log file

: Failed to cache ISO: unable to cache ISO:
  https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso?checksum=file:https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso.sha256 Dst:C:\Users\user\.minikube\cache\iso\amd64\minikube-v1.31.0-amd64.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8] Decompressors:map[bz2:0xc00058bdc8 gz:0xc00058be20 tar:0xc00058bdd0 tar.bz2:0xc00058bde0 tar.gz:0xc00058bdf0 tar.xz:0xc00058be00 tar.zst:0xc00058be10 tbz2:0xc00058bde0 tgz:0xc00058bdf0 txz:0xc00058be00 tzst:0xc00058be10 xz:0xc00058be28 zip:0xc00058be40 zst:0xc00058be50] Getters:map[file:0xc000756380 http:0xc001206190 https:0xc0012061e0] Dir:false ProgressListener:0x49c3370 Insecure:false DisableSymlinks:false Options:[0x1d41520]}: invalid checksum: Error downloading checksum file: bad response code: 404
  https://github.com/kubernetes/minikube/releases/download/v1.31.0/minikube-v1.31.0-amd64.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.31.0/minikube-v1.31.0-amd64.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.31.0/minikube-v1.31.0-amd64.iso.sha256 Dst:C:\Users\user\.minikube\cache\iso\amd64\minikube-v1.31.0-amd64.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8] Decompressors:map[bz2:0xc00058bdc8 gz:0xc00058be20 tar:0xc00058bdd0 tar.bz2:0xc00058bde0 tar.gz:0xc00058bdf0 tar.xz:0xc00058be00 tar.zst:0xc00058be10 tbz2:0xc00058bde0 tgz:0xc00058bdf0 txz:0xc00058be00 tzst:0xc00058be10 xz:0xc00058be28 zip:0xc00058be40 zst:0xc00058be50] Getters:map[file:0xc00138a090 http:0xc000e94b40 https:0xc000e94b90] Dir:false ProgressListener:0x49c3370 Insecure:false DisableSymlinks:false Options:[0x1d41520]}: stream error: stream ID 1; PROTOCOL_ERROR; received from peer
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.31.0-amd64.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.31.0-amd64.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.31.0-amd64.iso.sha256 Dst:C:\Users\user\.minikube\cache\iso\amd64\minikube-v1.31.0-amd64.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8 0x4a2f5e8] Decompressors:map[bz2:0xc00058bdc8 gz:0xc00058be20 tar:0xc00058bdd0 tar.bz2:0xc00058bde0 tar.gz:0xc00058bdf0 tar.xz:0xc00058be00 tar.zst:0xc00058be10 tbz2:0xc00058bde0 tgz:0xc00058bdf0 txz:0xc00058be00 tzst:0xc00058be10 xz:0xc00058be28 zip:0xc00058be40 zst:0xc00058be50] Getters:map[file:0xc000f26dc0 http:0xc0013e1090 https:0xc0013e10e0] Dir:false ProgressListener:0x49c3370 Insecure:false DisableSymlinks:false Options:[0x1d41520]}: invalid checksum: Error downloading checksum file: bad response code: 404

### Operating System

None

### Driver

None

**Comment by rmsilva1973** [comment]
Two things to address:

- What command did you use to start minikube?
- Run the command again adding "--alsologtostderr --file=logs.txt" and attach (not paste) the logs.txt file to the issue.

**Comment by spowelljr** [comment]
Hi @ThabtiZahra, this is a known issue with the v1.31.2 release, the ISO bucket for the GCS download link was incorrect. It should successfully download from GitHub though. Are you able to download it through your browser?

https://github.com/kubernetes/minikube/releases/download/v1.31.0/minikube-v1.31.0-amd64.iso

**Comment by asjayli** [comment]
> Hi @ThabtiZahra, this is a known issue with the v1.31.2 release, the ISO bucket for the GCS download link was incorrect. It should successfully download from GitHub though. Are you able to download it through your browser?
> 
> https://github.com/kubernetes/minikube/releases/download/v1.31.0/minikube-v1.31.0-amd64.iso

How should I use it after manually downloading? Please
minikube start or other?
