### ISSUE TITLE
facing minikube start error on Azure VM

### ISSUE THREAD

**Issue by atulkamble** [kubernetes/minikube#17168]
### What Happened?

Installed docker, kubernetes, kubectl, virtualbox, qemu

<img width="960" alt="minikube_error" src="https://github.com/kubernetes/minikube/assets/25535696/d60020b7-c459-4568-99ef-f29c6be66728">

### Attach the log file

E0903 05:55:28.506565   14173 logs.go:281] Failed to list containers for "kube-apiserver": docker: docker ps -a --filter=name=k8s_kube-apiserver --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0903 05:55:29.595361   14173 logs.go:281] Failed to list containers for "etcd": docker: docker ps -a --filter=name=k8s_etcd --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0903 05:55:31.494728   14173 logs.go:281] Failed to list containers for "coredns": docker: docker ps -a --filter=name=k8s_coredns --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0903 05:55:34.123401   14173 logs.go:281] Failed to list containers for "kube-scheduler": docker: docker ps -a --filter=name=k8s_kube-scheduler --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0903 05:55:34.892567   14173 logs.go:281] Failed to list containers for "kube-proxy": docker: docker ps -a --filter=name=k8s_kube-proxy --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0903 05:55:35.481080   14173 logs.go:281] Failed to list containers for "kube-controller-manager": docker: docker ps -a --filter=name=k8s_kube-controller-manager --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0903 05:55:35.973940   14173 logs.go:281] Failed to list containers for "kindnet": docker: docker ps -a --filter=name=k8s_kindnet --format={{.ID}}: Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0903 05:55:42.732009   14173 logs.go:195] command /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a" failed with error: /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a": Process exited with status 1
stdout:

stderr:
time="2023-09-03T05:55:41Z" level=fatal msg="listing containers: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 output: "\n** stderr ** \ntime=\"2023-09-03T05:55:41Z\" level=fatal msg=\"listing containers: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\"\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\n** /stderr **"

❗  unable to fetch logs for: container status

### Operating System

Ubuntu

### Driver

QEMU

**Comment by gsowjanya97** [comment]
Hi @atulkamble, so you've installed Ubuntu in a VirtualBox VM and running k8s there?

**Comment by atulkamble** [comment]
Hello @gsowjanya97, I have launched Azure Virtual Machine, connected through ssh, then installed Virtual box on top of that the tried minikube over there.

**Comment by gsowjanya97** [comment]
@atulkamble Ok, did you allow HTTPS and HTTP ports along with SSH in the Azure Network Security Group?

**Comment by atulkamble** [comment]
@gsowjanya97 yes.
