### ISSUE TITLE
MInikube with Hyperv install

### ISSUE THREAD

**Issue by Suhai-tech** [kubernetes/minikube#17171]
### What Happened?

minikube start --driver hyperv 
[logs.txt`](https://github.com/kubernetes/minikube/files/12507351/logs.txt)
 command is not running properly it is giving an error.

* minikube v1.31.2 on Microsoft Windows 11 Home Single Language 10.0.22621.2134 Build 22621.2134
* Using the hyperv driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) .../ E0904 01:14:56.134390   24048 main.go:137] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID A3BF12E4-69C0-4CA0-940F-B873418D972B)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine ID A3BF12E4-69C0-4CA0-940F-B873418D972B)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E). (Virtual machine ID A3BF12E4-69C0-4CA0-940F-B873418D972B)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

* Stopping node "minikube"  ...
* Deleting "minikube" in hyperv ...
! StartHost failed, but will try again: creating host: create: creating: exit status 1
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) .../ E0904 01:15:51.869130   24048 main.go:137] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID 094D97BD-21A7-4F35-A4CE-9C6E0C0286EE)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine ID 094D97BD-21A7-4F35-A4CE-9C6E0C0286EE)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E). (Virtual machine ID 094D97BD-21A7-4F35-A4CE-9C6E0C0286EE)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: creating: exit status 1

X Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: creating: exit status 1
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[logs.txt`](https://github.com/kubernetes/minikube/files/12507353/logs.txt)

### Operating System

Windows

### Driver

Hyper-V

**Comment by rmsilva1973** [comment]
From the output it seems your machine doesn't have enough memory to start a VM for running minikube. I assume you either have to free up memory by closing unneeded applications or but additional memory.

**Comment by spowelljr** [comment]
Hi @Suhai-tech, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
