### ISSUE TITLE
The connection to the server 127.0.0.1:59374 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by ashif1198** [kubernetes/minikube#17173]
### What Happened?

When i  run kubectl apply -f pod_name.yaml it shows me error :-
The connection to the server 127.0.0.1:59374 was refused - did you specify the right host or port?
Then i try to start minikube using minikube start cmd it will give me following error;
😄  minikube v1.31.2 on Debian 11.7 (amd64)
✨  Using the docker driver based on existing profile
🛑  The "docker" driver should not be used with root privileges. If you wish to continue as root, use --force.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
💡  Tip: To remove this root owned cluster, run: sudo minikube delete

❌  Exiting due to DRV_AS_ROOT: The "docker" driver should not be used with root privileges.

### Attach the log file

![Screenshot 2023-09-04 100318](https://github.com/kubernetes/minikube/assets/82199297/50b03d39-5868-4f58-be57-3ab57d81fb9e)

### Operating System

Windows

### Driver

None

**Comment by rmsilva1973** [comment]
The error message says **The "docker" driver should not be used with root privileges.** Perhaps you should try starting minikube with a regular user. Try this:

- Login with a regular (non-root) user
- Run "sudo minikube delete"
- Try starting minikube (still with regular user) with "minikube start"

**Comment by spowelljr** [comment]
Hi @ashif1198, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
