### ISSUE TITLE
How to use Flexvolumes in minikube?

### ISSUE THREAD

**Issue by Overv** [kubernetes/minikube#1719]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**Minikube version** (use `minikube version`): v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Hyper-V
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.20.0.iso
- **Install tools**: ...
- **Others**: ...

**What happened**: I want to use a flexvolume in minikube by installing a file in `/usr/libexec/kubernetes/kubelet-plugins/volume/exec/<vendor~driver>/driver`. I can do this using `minikube ssh`, but at that point the volume plugins have already been loaded and it's too late to add a new one. If I restart minikube after doing this, then the directory is cleared. I also tried to use the option to mount a host volume, but I can't create a directory in Windows with the `<vendor~driver>` name.

**What you expected to happen**: I'd like to know how to properly install a flexvolume in minikube.

**How to reproduce it** (as minimally and precisely as possible): See *What happened*.

**Anything else do we need to know**: ...

**Comment by r2d4** [comment]
You can restart kube without restarting the minikube VM with another `minikube start`.  Does that help?
As a longer term solution, we should probably make that directory persistent

**Comment by msnelling** [comment]
@Overv did you manage to get flexvolumes working in minikube? Did you find any documentation?

**Comment by Overv** [comment]
@msnelling I didn't get them working, I decided to use the `hack/local-up-cluster_up.sh` script in the [Kubernetes main repository](https://github.com/kubernetes/kubernetes) instead.
