### ISSUE TITLE
Question on insecure-registry in minikube config

### ISSUE THREAD

**Issue by bbergquist0930** [kubernetes/minikube#17209]
### What Happened?

If I set 
```
brett@brett-Precision-7740:~$ minikube config set insecure-registry "192.168.49.1"
brett@brett-Precision-7740:~$ minikube config view
- insecure-registry: 192.168.49.1
brett@brett-Precision-7740:~$ 
```
and then I do 
```
minikube start
```
The `insecure-registry` configuration is not passed to the docker daemon inside the node.
```
brett@brett-Precision-7740:~$ minikube ssh
docker@minikube:~$ docker info
Client: Docker Engine - Community
 Version:    24.0.4
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Docker Buildx (Docker Inc.)
    Version:  v0.11.1
    Path:     /usr/libexec/docker/cli-plugins/docker-buildx

Server:
 Containers: 19
  Running: 16
  Paused: 0
  Stopped: 3
 Images: 9
 Server Version: 24.0.4
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Using metacopy: false
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 3dce8eb055cbb6872793272b4f20ed16117344f8
 runc version: v1.1.7-0-g860f061
 init version: de40ad0
 Security Options:
  seccomp
   Profile: builtin
 Kernel Version: 5.4.0-162-generic
 Operating System: Ubuntu 22.04.2 LTS (containerized)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.55GiB
 Name: minikube
 ID: 84b155ef-6776-460c-9de6-70f1476166ae
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 No Proxy: control-plane.minikube.internal
 Labels:
  provider=docker
 Experimental: false
 Insecure Registries:
  10.96.0.0/12
  127.0.0.0/8
 Live Restore Enabled: false

docker@minikube:~$ 
```

If I use the `minikube start --insecure-registry="192.168.49.1"` that does gert passed to the Docker daemon in the node.

Should not the `config` value be passed to the `start`?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/12553467/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by chibby0ne** [comment]
Hi @bbergquist0930 thanks for submitting this issue, it was really straightforward to reproduce with your description.

I've looked a bit into this since I also experienced it in the past and I noticed that the reason it doesn't work as expected is because the argument passed to start command (`--insecure-registry`) actually gets set into the proper struct where it is forwarded to the docker daemon whilst the property `insecure-registry` set in the `minikube config` is not read at all by anyone or anything.

I've submitted a PR that handles it correctly. Let's hope this is fixed soon!
