### ISSUE TITLE
 when i run minikube service my-service --url i am getting following error

### ISSUE THREAD

**Issue by priya241302** [kubernetes/minikube#17208]
### What Happened?

minikube service my-service --url
http://192.168.64.5:30007

❌  Exiting due to SVC_UNREACHABLE: service not available: no running pod for service my-service found

╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                          │
│    😿  If the above advice does not help, please let us know:                                                            │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                          │
│                                                                                                                          │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                   │
│    Please also attach the following file to the GitHub issue:                                                            │
│    - /var/folders/rj/ptbd4m794hbfh0dz09s6zyb40000gn/T/minikube_service_f5b1ed1d10eb80188a93b6130bf10228f96b5c54_0.log    │
│                                                                                                                          │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/12550178/logs.txt)

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by henrikzhupani** [comment]
Check if the pod name (    spec: containers:  - name: **demo**)on Deployment yaml file,  matches (spec: selector: app: **demo**) name on Service yaml file
Making the binding for same name worked for me
