### ISSUE TITLE
minikube start failing

### ISSUE THREAD

**Issue by gonzaloint** [kubernetes/minikube#17204]
### What Happened?

I installed minikube, ran minikube start and got this message:

❌  Exiting due to RUNTIME_ENABLE: Failed to enable container runtime: sudo systemctl restart docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.

I'm in linux mint 21.1. The output of "systemctl status docker.service" and "journalctl -xeu docker.service" don't suggest that the docker service failed at any point. I've tryed: 
docker system prune; minikube delete; minikube start;
rebooting, restarting the docker service, use containerd as container runtime, that one resulted in other problems that migth have nothing to do.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/12543153/logs.txt)

### Operating System

Other

### Driver

Docker

**Comment by caerulescens** [comment]
@gonzaloint The file you attached is empty; could you attach the logs?
