### ISSUE TITLE
Unable to start minikube on Ubuntu 20.04 which is on VirtualBox on Windows Laptop

### ISSUE THREAD

**Issue by deepakts2013** [kubernetes/minikube#17227]
### What Happened?

I am trying to run minikube on Ubuntu 20.04 from https://www.osboxes.org/ubuntu/. On VirtualBox installed on Windows OS. 
We observed following retry with further loops : 
I0911 12:49:20.996610   13830 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0x80f160] 0x812200 <nil>  [] 0s} 127.0.0.1 37951 <nil> <nil>}
I0911 12:49:20.996627   13830 main.go:141] libmachine: About to run SSH command:
exit 0
I0911 12:50:36.088060   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:42272->127.0.0.1:37951: read: connection reset by peer
I0911 12:51:54.156814   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:60288->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:12.236833   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:37410->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:33.593650   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:55146->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:36.611909   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:57662->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:39.635337   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:57668->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:42.638051   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:57678->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:45.659014   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:39568->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:48.662281   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:39580->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:51.666686   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:39592->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:54.690210   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:39604->127.0.0.1:37951: read: connection reset by peer
I0911 12:53:57.709891   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:55310->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:00.734777   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:55318->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:03.738283   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:55334->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:06.752177   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:44554->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:09.774233   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:44566->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:12.796125   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:44578->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:15.821008   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33196->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:18.838968   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33210->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:21.852928   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33226->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:24.871791   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:43294->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:27.897375   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:43300->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:30.909572   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:43314->127.0.0.1:37951: read: connection reset by peer
I0911 12:54:41.331700   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
I0911 12:54:51.002529   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
I0911 12:54:57.815568   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
I0911 12:55:05.615653   13830 main.go:141] libmachine: Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

### Attach the log file

[minikube.log](https://github.com/kubernetes/minikube/files/12579176/minikube.log)

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by rmsilva1973** [comment]
@deepakts2013 Hi. Let me get it straight. Your laptop has Windows. You installed virtualbox on it and created a virtual machine running ubuntu 20.04. Then, inside this Ubuntu VM you are trying to start minikube using virtualbox.

1. Is that correct?
2. What happens when you try to start minikube with the docker driver?

**Comment by deepakts2013** [comment]
@rmsilva1973 : 
1. Is that correct?
Yes 

2. What happens when you try to start minikube with the docker driver?
Service kept looping indefinitely after handshake timeout
