### ISSUE TITLE
unable to setup minikube

### ISSUE THREAD

**Issue by parth721** [kubernetes/minikube#17238]
### What Happened?

when I start minikube after intallation its giving an error for kvm2 on zorin 16.3( based on ubuntu20.04 ). I done the setup many times. sometimes this setup becomes the issue. Need some help

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/12591920/log.txt)

### Operating System

Other

### Driver

KVM2

**Comment by parth721** [comment]
I tried by changing the latest k8s version with v-1.22.0 also. same error

* startHost failed
* failed to start kvm2 VM

**Comment by rmsilva1973** [comment]
@parth721 What's the output of the "**virsh net-info default**" ?

**Comment by parth721** [comment]
Hi @rmsilva1973 
it's giving me this
![Screenshot from 2023-09-23 22-32-53](https://github.com/kubernetes/minikube/assets/112557191/b27942b9-8a97-4828-a061-51c0ef7b97c9)
Somebody told me, the error arises due to miscofiguration of  k8s api-server at control plane level.
To fix this, I'm using an older version of kubernetes v1.23.x

I'm a relatively new with k8s & I would like to know why this error happens while using latest version of kubernetes ? I faced this thing twice & the issue got fixed by using an older version of k8s.

Have a great day

**Comment by caerulescens** [comment]
@parth721 That's interesting, I believe I've had this issue before. I have managed to get the default network into a bugged state multiple different ways. The solution is to delete the `default` network and recreate it, and that's how I managed to fix it on Debian. I have had no issues in Debian 10, 11, or 12 with starting `minikube` from a fresh os install (after setting up KVM correctly). I think you could also try to purge and reinstall KVM through `apt` maybe to recreate the default network configuration.

The official docs hint at [these steps](https://minikube.sigs.k8s.io/docs/drivers/kvm2/#troubleshooting-kvmlibvirt-networks) in (3)(1) where it is referring to "In case that the default libvirt network is missing or is unable to start/activate". @parth721 Have you tried these steps?

This should solve your problem; otherwise, I think you may to want to look deeper into the way that Zorin installs KVM.

**Comment by parth721** [comment]
Thank you @caerulescens. I tried this out & happy to inform that minikube with kvm2 driver works perfectly fine.

@caerulescens had you tried out k8s persistent Volumes & persistent volume claims for local storage, because I trying it out & got few questions related to how to apply it.

once again thank you & happy learning.

**Comment by caerulescens** [comment]
@parth721 That's great news. Close the issue when you can. 

---

If you're looking to use PVCs on `minikube` running 1 node, then you don't need to configure anything special as the `storage-provisioner` and `default-storageclass` are enabled by default; [there's a tutorial for this](https://minikube.sigs.k8s.io/docs/tutorials/local_path_provisioner/). I would recommend starting here before trying the CSI driver. 
```
minikube addons list -p minikube
|-----------------------------|----------|--------------|--------------------------------|
|         ADDON NAME          | PROFILE  |    STATUS    |           MAINTAINER           |
|-----------------------------|----------|--------------|--------------------------------|
| ambassador                  | minikube | disabled     | 3rd party (Ambassador)         |
| auto-pause                  | minikube | disabled     | minikube                       |
| cloud-spanner               | minikube | disabled     | Google                         |
| csi-hostpath-driver         | minikube | disabled     | Kubernetes                     |
| dashboard                   | minikube | disabled     | Kubernetes                     |
| default-storageclass        | minikube | enabled ✅   | Kubernetes                     |
| efk                         | minikube | disabled     | 3rd party (Elastic)            |
| freshpod                    | minikube | disabled     | Google                         |
| gcp-auth                    | minikube | disabled     | Google                         |
| gvisor                      | minikube | disabled     | minikube                       |
| headlamp                    | minikube | disabled     | 3rd party (kinvolk.io)         |
| helm-tiller                 | minikube | disabled     | 3rd party (Helm)               |
| inaccel                     | minikube | disabled     | 3rd party (InAccel             |
|                             |          |              | [info@inaccel.com])            |
| ingress                     | minikube | disabled     | Kubernetes                     |
| ingress-dns                 | minikube | disabled     | minikube                       |
| inspektor-gadget            | minikube | disabled     | 3rd party                      |
|                             |          |              | (inspektor-gadget.io)          |
| istio                       | minikube | disabled     | 3rd party (Istio)              |
| istio-provisioner           | minikube | disabled     | 3rd party (Istio)              |
| kong                        | minikube | disabled     | 3rd party (Kong HQ)            |
| kubeflow                    | minikube | disabled     | 3rd party                      |
| kubevirt                    | minikube | disabled     | 3rd party (KubeVirt)           |
| logviewer                   | minikube | disabled     | 3rd party (unknown)            |
| metallb                     | minikube | disabled     | 3rd party (MetalLB)            |
| metrics-server              | minikube | disabled     | Kubernetes                     |
| nvidia-device-plugin        | minikube | disabled     | 3rd party (NVIDIA)             |
| nvidia-driver-installer     | minikube | disabled     | 3rd party (Nvidia)             |
| nvidia-gpu-device-plugin    | minikube | disabled     | 3rd party (Nvidia)             |
| olm                         | minikube | disabled     | 3rd party (Operator Framework) |
| pod-security-policy         | minikube | disabled     | 3rd party (unknown)            |
| portainer                   | minikube | disabled     | 3rd party (Portainer.io)       |
| registry                    | minikube | disabled     | minikube                       |
| registry-aliases            | minikube | disabled     | 3rd party (unknown)            |
| registry-creds              | minikube | disabled     | 3rd party (UPMC Enterprises)   |
| storage-provisioner         | minikube | enabled ✅   | minikube                       |
| storage-provisioner-gluster | minikube | disabled     | 3rd party (Gluster)            |
| storage-provisioner-rancher | minikube | disabled     | 3rd party (Rancher)            |
| volumesnapshots             | minikube | disabled     | Kubernetes                     |
|-----------------------------|----------|--------------|--------------------------------|
```

When you have 2 or more nodes, you need to use the CSI driver, which requires enabling the `volumesnapshots` and `csi-hostpath-driver` (or custom CSI driver); [there's a tutorial for this](https://minikube.sigs.k8s.io/docs/tutorials/volume_snapshots_and_csi/). You can find more general documentation about persistent volumes [here](https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/).

**Comment by parth721** [comment]
Thanks you :) @caerulescens
