### ISSUE TITLE
bug report about   proxy

### ISSUE THREAD

**Issue by WanLinghao** [kubernetes/minikube#1723]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Minikube version** (use `minikube version`):
minikube version: v0.20.0

**Environment**:
- **OS** :ubuntu 16.04TLS
- **VM Driver** :virtualbox
- **ISO version** 
- **Install tools**:
- **Others**:

**What happened**:
try to start start minikube on http-proxy by 
$ minikube start --docker-env HTTP_PROXY=http://$YOURPROXY:PORT \
                 --docker-env HTTPS_PROXY=https://$YOURPROXY:PORT

but it doesn't work.
the docker daemon in minikube still connect Internet directly rather than by proxy.
**What you expected to happen**:

docker daemon use proxy 
**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by r2d4** [comment]
@WanLinghao Can you post the output of 

`$ minikube ssh -- systemctl show docker --property=Environment --no-pager`?

**Comment by WanLinghao** [comment]
@r2d4  output was 
 Environment=DOCKER_RAMDISK=yes

**Comment by WanLinghao** [comment]
@r2d4 what was the output supposed to be?

**Comment by r2d4** [comment]
The output should have showed your environment variables.  You'll need to `minikube delete` and then `minikube start --docker-env ...` for them to take effect
