### ISSUE TITLE
minikube fails to suggest rootless when `sudo` is missing

### ISSUE THREAD

**Issue by ambasta** [kubernetes/minikube#17245]
### What Happened?

On attempting to start minikube, if sudo is not installed, minikube exits with incorrect information and fails to suggest rootless.

```
💡  Suggestion: Add your user to the 'sudoers' file: 'ambasta ALL=(ALL) NOPASSWD: /usr/bin/podman' , or run 'minikube config set rootless true'
```

### Attach the log file

```
$ minikube start --driver podman --container-runtime cri-o
😄  minikube v1.30.1 on Gentoo 2.14
✨  Using the podman driver based on user configuration

💣  Exiting due to PROVIDER_PODMAN_NOT_RUNNING: exec: "sudo": executable file not found in $PATH
📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/podman/
```

### Operating System

Other

### Driver

Podman

**Comment by rmsilva1973** [comment]
@ambasta The output message specifically says "or run 'minikube config set rootless true'".  What's missing here?

**Comment by ambasta** [comment]
@rmsilva1973 The actual output is

```
$ minikube start --driver podman --container-runtime cri-o
😄  minikube v1.30.1 on Gentoo 2.14
✨  Using the podman driver based on user configuration

💣  Exiting due to PROVIDER_PODMAN_NOT_RUNNING: exec: "sudo": executable file not found in $PATH
📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/podman/
```

which doesn't suggest setting rootless at all

**Comment by rmsilva1973** [comment]
I think it could suggest using rootless. But I don't think it's reasonable to instruct the user to change sudoers since the message says it couldn't even find sudo executable. It looks more reasonable a message like this

💡  Suggestion: Add "sudo" to your $PATH (and configure sudoers), or run 'minikube config set rootless true'

**Comment by ambasta** [comment]
That would be fine as well. I just started using minikube, and I believe as a beginner, the `rootless` sugesstion would have saved a ton of time, specially on bespoke distributions where `sudo` isn't necessarily installed
