### ISSUE TITLE
minikube mount creates directory, but files are missing on mac

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/minikube#1725]
**Minikube version** (use `minikube version`):
minikube version: v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
`Mac OS Sierra (10.12.5)`
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
`"DriverName": "virtualbox",`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
`"Boot2DockerURL": "file:///Users/xxxx/.minikube/cache/iso/minikube-v0.20.0.iso"`
- **Install tools**:
- **Others**:

**What happened**:
- Run `minikube mount /Users/xxxx/demo:/demo2`
- Run `minikube ssh` in another tab
- /demo2 exists, but is empty (does not contain the files from the host)

**What you expected to happen**:
The files from the host to be present in the mounted directory

**How to reproduce it** (as minimally and precisely as possible):
See "What happened"

**Anything else do we need to know**:
Logs:
minikube mount /Users/xxxx/demo:/demo2 -v 8
Mounting /Users/xxxx/demo into /demo2 on the minikube VM
This daemon process needs to stay alive for the mount to still be accessible...
ufs starting
Using SSH client type: external
Using SSH private key: /Users/xxxx/.minikube/machines/minikube/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/xxxx/.minikube/machines/minikube/id_rsa -p 49768] /usr/local/bin/ssh <nil>}
About to run SSH command:
sudo umount /demo2;
SSH cmd err, output: exit status 32: umount: /demo2: not mounted

Using SSH client type: external
Using SSH private key: /Users/xxxx/.minikube/machines/minikube/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/xxxxx/.minikube/machines/minikube/id_rsa -p 49768] /usr/local/bin/ssh <nil>}
About to run SSH command:

sudo mkdir -p /demo2 || true;
sudo mount -t 9p -o trans=tcp -o port=58226 -o uid=1001 -o gid=1001 192.168.99.1 /demo2;
sudo chmod 775 /demo2;

**Comment by r2d4** [comment]
I just tried this and wasn't able to reproduce.

```
mrick-macbookpro2:~ mrick$ minikube mount $PWD:/demo2 --v 10
Mounting /Users/mrick into /demo2 on the minikube VM
This daemon process needs to stay alive for the mount to still be accessible...
ufs starting
Using SSH client type: external
Using SSH private key: /Users/mrick/.minikube/machines/minikube/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/mrick/.minikube/machines/minikube/id_rsa -p 65150] /usr/local/bin/ssh <nil>}
About to run SSH command:
sudo umount /demo2;
SSH cmd err, output: <nil>: 
Using SSH client type: external
Using SSH private key: /Users/mrick/.minikube/machines/minikube/id_rsa (-rw-------)
&{[-F /dev/null -o PasswordAuthentication=no -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none docker@127.0.0.1 -o IdentitiesOnly=yes -i /Users/mrick/.minikube/machines/minikube/id_rsa -p 65150] /usr/local/bin/ssh <nil>}
About to run SSH command:

sudo mkdir -p /demo2 || true;
sudo mount -t 9p -o trans=tcp -o port=65406 -o uid=1001 -o gid=1001 192.168.99.1 /demo2;
sudo chmod 775 /demo2;
2017/07/21 09:18:28 connected
2017/07/21 09:18:28 >>> 192.168.99.100:42856 Tversion tag 65535 msize 8192 version '9P2000.L'
2017/07/21 09:18:28 <<< 192.168.99.100:42856 Rversion tag 65535 msize 8192 version '9P2000'
2017/07/21 09:18:28 >>> 192.168.99.100:42856 Tattach tag 1 fid 0 afid 1000 uname 'nobody' nuname 0 aname ''
2017/07/21 09:18:28 <<< 192.168.99.100:42856 Rattach tag 1 aqid (716cf 65edce70 'd')
2017/07/21 09:18:28 >>> 192.168.99.100:42856 Tstat tag 1 fid 0
2017/07/21 09:18:28 <<< 192.168.99.100:42856 Rstat tag 1 st ('mrick' 'mrick' '5000' '' q (716cf 65edce70 'd') m d775 at 0 mt 1500653670 l 1360 t 0 d 0 ext )
2017/07/21 09:18:28 >>> 192.168.99.100:42856 Tstat tag 1 fid 0
2017/07/21 09:18:28 <<< 192.168.99.100:42856 Rstat tag 1 st ('mrick' 'mrick' '5000' '' q (716cf 65edce70 'd') m d775 at 0 mt 1500653670 l 1360 t 0 d 0 ext )
2017/07/21 09:18:28 >>> 192.168.99.100:42856 Twstat tag 1 fid 0 st ('' '' '' '' q (ffffffffffffffff ffffffff 'daAltL') m d775 at 1000 mt 1000 l 18446744073709551615 t 65535 d 1000 ext )
```

Not sure how to further debug this, maybe @aaron-prindle might have some insight.

**Comment by dlorenc** [comment]
Attaching some of the mount logs from after you try to 'cd' or 'ls' in the mounted directory might help. We can see the 9p messages there and maybe figure out what's going on.

**Comment by PawelWesolowski** [comment]
Had the same problem on version 0.27.0. In my case it helped to run `minikube update-context`
