### ISSUE TITLE
Unable to start minikube 

### ISSUE THREAD

**Issue by Viconz** [kubernetes/minikube#17267]
### What Happened?

C:\Windows\system32>minikube delete
* Removed all traces of the "minikube" cluster.

C:\Windows\system32>minikube start
* minikube v1.31.2 on Microsoft Windows 10 Pro 10.0.19044.2130 Build 19044.2130
* Automatically selected the virtualbox driver
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: VirtualBox is configured with multiple host-only adapters with the same name "HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2". Please remove one
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: VirtualBox is configured with multiple host-only adapters with the same name "HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2". Please remove one

X Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: precreate: VirtualBox is configured with multiple host-only adapters with the same name "HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2". Please remove one
*

### Attach the log file

C:\Windows\system32>minikube delete
* Removed all traces of the "minikube" cluster.

C:\Windows\system32>minikube start
* minikube v1.31.2 on Microsoft Windows 10 Pro 10.0.19044.2130 Build 19044.2130
* Automatically selected the virtualbox driver
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: VirtualBox is configured with multiple host-only adapters with the same name "HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2". Please remove one
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: VirtualBox is configured with multiple host-only adapters with the same name "HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2". Please remove one

X Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: precreate: VirtualBox is configured with multiple host-only adapters with the same name "HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2". Please remove one
*

### Operating System

Windows

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Hi @Viconz, as per the error message, have you tried removing on the of the Ethernet adapters?

`VirtualBox is configured with multiple host-only adapters with the same name "HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter https://github.com/kubernetes/minikube/issues/2". Please remove one`
