### ISSUE TITLE
issue in minikube dashboard start

### ISSUE THREAD

**Issue by MohSulta** [kubernetes/minikube#17294]
docker@ubuntu:~$ minikube dashboard start

X Exiting due to GUEST_STATUS: Unable to get machine status: state: unknown state "minikube": docker container inspect minikube --format=<no value>: exit status 1
stdout:

stderr:
Error response from daemon: No such container: minikube

**Comment by spowelljr** [comment]
Hi @MohSulta, it seems like either your Docker instance isn't running or you've manually deleted the minikube container. Ensure Docker is running `docker info` and then run `minikube start` again and then trying starting the dashboard again.
