### ISSUE TITLE
Large test binaries causing slow checkout with slow internet

### ISSUE THREAD

**Issue by lowang-bh** [kubernetes/minikube#17295]
### What Happened?

Those binary files take most size of the repo. And it is hard to pull in weak network env.
```
 13M	./test/integration/testdata/hyperkit-driver-version-1.11.0
 35M	./test/integration/testdata/hyperkit-driver-older-version
 38M	./test/integration/testdata/hyperkit-driver-without-version
 49M	./test/integration/testdata/kvm2-driver-older-version
 49M	./test/integration/testdata/kvm2-driver-without-version
```

### Attach the log file

no log

### Operating System

macOS (Default)

### Driver

None

**Comment by afbjorklund** [comment]
They should probably have been downloaded during the test, instead.

But it doesn't really matter now, since it is too late to remove them...

* 6ee291b07ae97dda2b9bef536975cae659d04a17

* 0cf4921c14bb55e525164be1f50654a088ed2782

Could be a good idea to avoid exporting them to the new git repositories.

i.e. when "hyperkit" and "kvm" drivers are broken out from minikube `cmd`

**Comment by lowang-bh** [comment]
> Could be a good idea to avoid exporting them to the new git repositories?

It seems they are introduced by those commit. Could we remove it from git repo? Those big files take too much time when clone repo, especially in waek network env.

**Comment by afbjorklund** [comment]
Unfortunately you cannot remove commits from git history, without rewriting.

**Comment by lowang-bh** [comment]
> Unfortunately you cannot remove commits from git history, without rewriting.
How about remove them in another new PR?

**Comment by afbjorklund** [comment]
It makes the checkout smaller, but will not change the size of the download (pull).

**Comment by spowelljr** [comment]
Most users aren't running integration tests so I think it makes sense to not have them included in the repo and store them in GCS. We'd need to have a func in the integration tests to download them before running the tests.
