### ISSUE TITLE
Pods Gone after Reboot

### ISSUE THREAD

**Issue by ZachHoiberg** [kubernetes/minikube#17290]
### What Happened?

My entire AWX deployment is gone following a reboot of the host machine, which occurred trying to resolve an expired certificate issue where minikube did not automatically renew its certs and was failing during operation.

Is there a way to restore this data?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/12690420/log.txt)

### Operating System

Other

### Driver

Docker

**Comment by jnfohr** [comment]
Dear Zach,
I'm facing the exact same issue, did you manage to restore your data in any way, and if so would you be so kind as to share your method here?

Regards,
Jean-Noel

**Comment by ZachHoiberg** [comment]
Jean,

The only solution we were able to find was to set the clock back on the BIOS of our VM, boot the VM without internet access to prevent NTP from syncing, and then the pods booted as normal, and the Web GUI was accessible. We then used this to migrate to AWX backed by k3s, outlined here: https://github.com/kurokobo/awx-on-k3s/

You may need to also set your PC time back as well, we were within 18 hours of the restore time, so our web browser was not throwing a fit.
