### ISSUE TITLE
error para conectar con kubectl

### ISSUE THREAD

**Issue by 358miguel** [kubernetes/minikube#17319]
**Los comandos necesarios para reproducir la incidencia**:

**El resultado completo del comando que ha fallado**: <details>

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by spowelljr** [comment]
Hi @358miguel, could you provide a description of the issue you're experiencing and some logs.

-----

Hola @358miguel, ¿podrías proporcionar una descripción del problema que estás experimentando y algunos registros?
