### ISSUE TITLE
cannot expose port 80 and 443

### ISSUE THREAD

**Issue by luatnd** [kubernetes/minikube#17313]
### What Happened?

My purpose is map port 80 & 443 from k8s inside minikube to my host machine MacOS.

I follow this tutorial:
https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

As I can see minukube container doesn't mount the port 80 & 443:
<img width="905" alt="image" src="https://github.com/kubernetes/minikube/assets/1859127/9ef5f520-20e8-4293-9daa-c4c2f3e66bb7">

As a result, I cannot reach the port 80 from my host machine:
```
telnet "$(minikube ip)" 80
Trying 192.168.49.2...
# hang forever
```

As investigated some closed issues, I tried this with no luck
```bash
minikube start   --ports=443 --ports=80
# Or
minikube start --addons=ingress --ports=80:80,443:443 --driver=docker
```

Tried with `docker run`:
```
docker run --hostname=minikube --env=container=docker --env=PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --volume=/lib/modules:/lib/modules:ro --volume=minikube:/var --network=minikube --privileged --workdir=/ -p 3222:22 -p 32376:2376 -p 32443 -p 5000 -p 8443 -p 443:443 -p 80:80   --restart=no --label='created_by.minikube.sigs.k8s.io=true' --label='mode.minikube.sigs.k8s.io=minikube' --label='name.minikube.sigs.k8s.io=minikube' --label='role.minikube.sigs.k8s.io=' --runtime=runc --memory="4194304000" -t -d gcr.io/k8s-minikube/kicbase:v0.0.40@sha256:8cadf23777709e43eca447c47a45f5a4635615129267ce025193040ec92a1631
```

So how can I map port 80 & 443 to host without using reverse proxy?

### Attach the log file

```
$ minikube version
minikube version: v1.31.1
commit: fd3f3801765d093a485d255043149f92ec0a695f
```

### Operating System

macOS (Default)

### Driver

Docker

**Comment by friedrich** [comment]
Try recreating the cluster:

```
minikube delete
minikube start --ports=80:80,443:443
```

According to a [comment](https://github.com/kubernetes/minikube/pull/9404#issuecomment-919268031) from the PR:

> It's important to note that the --ports option only applies when first creating the minikube docker container. If minikube start --ports=... is called when the minikube container already exists, then the option is ignored.
