### ISSUE TITLE
error when running minibue start `macos silicon`

### ISSUE THREAD

**Issue by charlie-goldenowl** [kubernetes/minikube#17316]
### What Happened?

error when running minibue start `macos silicon`

### Attach the log file

❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.26.1:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,NumCPU,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.26.1
[preflight] Running pre-flight checks

stderr:
W0928 07:20:22.759734    2769 initconfiguration.go:119] Usage of CRI endpoints without URL scheme is deprecated and can cause kubelet errors in the future. Automatically prepending scheme "unix" to the "criSocket" with value "/var/run/cri-dockerd.sock". Please update your configuration!
        [WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR KubeletVersion]: couldn't get kubelet version: cannot execute 'kubelet --version': executable file not found in $PATH
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @charlie-goldenowl, that's a very odd error message you're getting. 
`couldn't get kubelet version: cannot execute 'kubelet --version': executable file not found in $PATH`

Have you tried running `minikube delete` and then running `minikube start` again? Also, what's your full `minikube start` command, are you including other flags?

**Comment by charlie-goldenowl** [comment]
hi @spowelljr i've tried delete and start many time but seem not to work
![image](https://github.com/kubernetes/minikube/assets/111278605/ed1354dd-e547-424a-b559-7912f786118e)

![image](https://github.com/kubernetes/minikube/assets/111278605/25938f96-4ea7-4690-916b-4f0dffa17f9a)

**Comment by spowelljr** [comment]
Thanks for the update, you seem to be on a slightly old version of minikube, could you update to the latest version (v1.31.2) and try a delete and start cycle again.

**Comment by charlie-goldenowl** [comment]
awsome, thanks @spowelljr

**Comment by k1empka** [comment]
Hey! I have exactly the same issue with the **latest** version of minikube. I deleted and started minikube many times and it seems not work. Does anyone have an idea how to fix it? 🤔 

<img width="504" alt="Screenshot 2024-03-22 at 09 53 14" src="https://github.com/kubernetes/minikube/assets/22158001/6e76c1f1-4053-4555-865b-9fb026f8d336">
e issue.
<img width="2315" alt="Screenshot 2024-03-22 at 09 51 16" src="https://github.com/kubernetes/minikube/assets/22158001/29605b32-0b60-4dd2-8b76-3b5444a88749">
