### ISSUE TITLE
Failed to stop ssh-agent process: failed loading config: cluster "minikube" does not exist

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#17315]
If you try deleting minikube with there's not a cluster you got the following error:
```
$ minikube delete
🙄  "minikube" profile does not exist, trying anyways.
❌  Failed to stop ssh-agent process: failed loading config: cluster "minikube" does not exist
💀  Removed all traces of the "minikube" cluster.
```

That error message should not be displayed, seems like we're trying to load a cluster that doesn't exist. If the cluster doesn't exist we shouldn't try loading it.

**Comment by Songjf-ttk** [comment]
I will try to solve this issue

**Comment by Songjf-ttk** [comment]
I think I can find the problem and fix it

**Comment by tarishij17** [comment]
@spowelljr Is this issue fixed? Which minikube version is this cmd ran on? I'm not getting this error message in minikube version: v1.26.1

**Comment by spowelljr** [comment]
@tarishij17 This issue is not fixed, it was introduced in v1.30 or v1.31

**Comment by tarishij17** [comment]
PR for fixing this issue: https://github.com/kubernetes/minikube/pull/17713

**Comment by Bharadwajshivam28** [comment]
@spowelljr Hey can i work on this?

**Comment by mbelconis** [comment]
Any progress on this?  Ran into this issue myself today installing minikube on WSL2

**Comment by roma2341** [comment]
Same on Ubuntu 22.04.4
