### ISSUE TITLE
rootless: support `--container-runtime=docker`

### ISSUE THREAD

**Issue by AkihiroSuda** [kubernetes/minikube#17322]
Currently `--rootless` requires `--container-runtime` to be containerd or cri-o, due to:
- https://github.com/moby/moby/issues/46563

After fixing this issue, `--container-runtime` can be set to `docker` too.

PR for Docker:
- https://github.com/moby/moby/pull/46564

WIP PR for minikube:
- https://github.com/AkihiroSuda/minikube/commit/ec95bcfcbe9602006ff81f93a5600c15a509fcbc

**Comment by medyagh** [comment]
nice once that PR is merged and released in moby project I would be happy to see it in minikube too

**Comment by AkihiroSuda** [comment]
PR
- https://github.com/kubernetes/minikube/pull/17520
