### ISSUE TITLE
failed to verify certificate: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by dcokersept** [kubernetes/minikube#17333]
### What Happened?

X Exiting due to K8S_INSTALL_FAILED: Failed to update cluster: updating control plane: downloading binaries: downloading kubeadm: download failed: https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm?checksum=file:https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm?checksum=file:https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm.sha256 Dst:/root/.minikube/cache/linux/amd64/v1.27.4/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8] Decompressors:map[bz2:0xc000412090 gz:0xc000412098 tar:0xc000412040 tar.bz2:0xc000412050 tar.gz:0xc000412060 tar.xz:0xc000412070 tar.zst:0xc000412080 tbz2:0xc000412050 tgz:0xc000412060 txz:0xc000412070 tzst:0xc000412080 xz:0xc0004120a0 zip:0xc0004120b0 zst:0xc0004120a8] Getters:map[file:0xc000a81980 http:0xc000c26d20 https:0xc000c26d70] Dir:false ProgressListener:0x3f579a0 Insecure:false DisableSymlinks:false Options:[0x12d0880]}: invalid checksum: Error downloading checksum file: Get "https://cdn.dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm.sha256": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-10-01T10:19:01+05:30 is after 2021-09-30T14:01:15Z
*

### Attach the log file

While executing  minikube start  it is showing the error  as below
 minikube v1.31.2 on Oracle 7.2 (vbox/amd64)
! minikube skips various validations when --force is supplied; this may lead to unexpected behavior
* Using the docker driver based on existing profile
* The "docker" driver should not be used with root privileges. If you wish to continue as root, use --force.
* If you are running minikube within a VM, consider using --driver=none:
*   https://minikube.sigs.k8s.io/docs/reference/drivers/none/
* Tip: To remove this root owned cluster, run: sudo minikube delete
! docker is currently using the btrfs storage driver, setting preload=false
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Updating the running docker "minikube" container ...
* Preparing Kubernetes v1.27.4 on Docker 24.0.4 ...
  - kubelet.localStorageCapacityIsolation=false

X Exiting due to K8S_INSTALL_FAILED: Failed to update cluster: updating control plane: downloading binaries: downloading kubeadm: download failed: https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm?checksum=file:https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm?checksum=file:https://dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm.sha256 Dst:/root/.minikube/cache/linux/amd64/v1.27.4/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8] Decompressors:map[bz2:0xc000412090 gz:0xc000412098 tar:0xc000412040 tar.bz2:0xc000412050 tar.gz:0xc000412060 tar.xz:0xc000412070 tar.zst:0xc000412080 tbz2:0xc000412050 tgz:0xc000412060 txz:0xc000412070 tzst:0xc000412080 xz:0xc0004120a0 zip:0xc0004120b0 zst:0xc0004120a8] Getters:map[file:0xc000a81980 http:0xc000c26d20 https:0xc000c26d70] Dir:false ProgressListener:0x3f579a0 Insecure:false DisableSymlinks:false Options:[0x12d0880]}: invalid checksum: Error downloading checksum file: Get "https://cdn.dl.k8s.io/release/v1.27.4/bin/linux/amd64/kubeadm.sha256": tls: failed to verify certificate: x509: certificate has expired or is not yet valid: current time 2023-10-01T10:19:01+05:30 is after 2021-09-30T14:01:15Z
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Redhat/Fedora

### Driver

N/A

**Comment by spowelljr** [comment]
Hi @dcokersept, it looks like your cert inside minikube has expired, this should self update but it seems like it's not. Could you try purging all of minikube with `minikube delete --all --purge` and then try starting again, that should resolve the issue you're experiencing.
