### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by yozsoy** [kubernetes/minikube#17349]
you are telling that to install minikube, you need 2 CPUs or more. Which cpu do we need to apply the installation instructions? All of them? You dont mention this skey information in the instructions.

https://minikube.sigs.k8s.io/docs/start/

**Comment by afbjorklund** [comment]
The requirements are from upstream, they say "2 GiB RAM, 2 CPU" but mean VM memory and 2 vCPU.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
