### ISSUE TITLE
Error with Minikube Hyperkit

### ISSUE THREAD

**Issue by digitalcrest01** [kubernetes/minikube#17346]
### What Happened?

Error due to MK_CONFIG_SET: Set failed: run validations for "driver" with value of "hyperkit": [driver "hyperkit" is not supported]

### Attach the log file

- /var/folders/tx/g4gjlqxd7cgdwp2v05_sbz7h0000gn/T/minikube_config_559a34aefd80a1002cb956d65d32e9c1bcc8acb0_0.log 

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by spowelljr** [comment]
Hi @digitalcrest01, are you trying to run this on an M1 or M2 machine? Apple arm64 machines don't have HyperKit so you you'll have to use Docker or QEMU.

**Comment by caerulescens** [comment]
@digitalcrest01 `hyperkit` has `x86` specific code, and will not run on `arm64`; see https://github.com/moby/hyperkit/issues/303#issuecomment-875122919. It's being tracked here: https://github.com/moby/hyperkit/issues/310.

On m-series processors, you can use `qemu2` driver and `socket_vmnet` network to get the essential `minikube` functionality on `macos`.

1. Install [qemu](https://formulae.brew.sh/formula/qemu).
2. Install [socket_vmnet](https://formulae.brew.sh/formula/socket_vmnet).
3. I think you will need to start the network like mentioned [here](https://minikube.sigs.k8s.io/docs/drivers/qemu/#install-socket_vmnet-via-brewhttpsbrewsh) in the docs.
4. Run `minikube start --driver=qemu2 --network=socket_vmnet`
5. Test `minikube tunnel` in a separate terminal window.

**Comment by caerulescens** [comment]
I think this issue can be closed; I don't think `hyperkit` is going to be ported to `arm64` as it's being superseded by `qemu2` and the framework.virtualization.
