### ISSUE TITLE
The driver 'hyperv' is not supported on linux/amd64

### ISSUE THREAD

**Issue by hubertsvk** [kubernetes/minikube#17369]
### What Happened?

All HyperV features I have installed. Windows 11 22h2 , HyperV

hubka@hubka:~$ minikube start
* minikube v1.31.2 on Ubuntu 22.04 (hyperv/amd64)
* Unable to pick a default driver. Here is what was considered, in preference order:
* Alternatively you could install one of these drivers:
  - docker: Not installed: exec: "docker": executable file not found in $PATH
  - kvm2: Not installed: exec: "virsh": executable file not found in $PATH
  - podman: Not installed: exec: "podman": executable file not found in $PATH
  - qemu2: Not installed: exec: "qemu-system-x86_64": executable file not found in $PATH
  - virtualbox: Not installed: unable to find VBoxManage in $PATH

X Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/

hubka@hubka:~$ minikube start --driver=hyperv
* minikube v1.31.2 on Ubuntu 22.04 (hyperv/amd64)

X **Exiting due to DRV_UNSUPPORTED_OS: The driver 'hyperv' is not supported on linux/amd64**

### Attach the log file

hubka@hubka:~$ minikube logs --file=log.txt
* Profile "minikube" not found. Run "minikube profile list" to view all profiles.
  To start a cluster, run: "minikube start"
hubka@hubka:~$ minikube profile list

* Exiting due to MK_USAGE_NO_PROFILE: No minikube profile was found.
* Suggestion:

    You can create one using 'minikube start'.

### Operating System

Windows

### Driver

Hyper-V

**Comment by spowelljr** [comment]
Hi @hubertsvk, the problem looks like you're trying to access Hyper-V from WSL, but WSL is already inside Hyper-V. If you want to use Hyper-V you'd have to do so from your Windows host, otherwise you'd have to use a Linux supported option.

**Comment by hubertsvk** [comment]
@spowelljr thank for answer but I haven't WSL installed. I have Hyper-V role installed and one virtual machine ( I have w11 dev, rhel etc.) is ubuntu gen2.

**Comment by spowelljr** [comment]
I see, but that same still stands, we're not able to start a Hyper-V instance from within Hyper-V itself, you'll have to start minikube from your Windows host. To start minikube from your Ubuntu instance you'll have to use a Linux supported driver.
