### ISSUE TITLE
minikube addons enable ingress fails

### ISSUE THREAD

**Issue by mnguyen081002** [kubernetes/minikube#17372]
### What Happened?

minikube addons enable ingress 
💡  ingress is an addon maintained by Kubernetes. For any concerns contact minikube on GitHub.
You can view the list of minikube maintainers at: https://github.com/kubernetes/minikube/blob/master/OWNERS
    ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407
    ▪ Using image registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20230407
    ▪ Using image registry.k8s.io/ingress-nginx/controller:v1.8.1
🔎  Verifying ingress addon...

❌  Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: context deadline exceeded]

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/12833388/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by mnguyen081002** [comment]
##17119

**Comment by mnguyen081002** [comment]
Fixed it using this https://github.com/kubernetes/minikube/issues/13872#issuecomment-1645412818. I will still leave the issue because more explanation is needed

**Comment by stark-sim** [comment]
I guess it might be a network problem.
I have encountered the same error output, and I set ENV http_proxy and https_proxy to solve this problem eventually.
I have tried simply delete and restart minikube, didn't work thought.
