### ISSUE TITLE
While accessing minikube docker on putty with default credentials getting error access denied

### ISSUE THREAD

**Issue by siddique670** [kubernetes/minikube#17379]
### What Happened?

As per attached screenshot while accessing minikube docker on putty with default credentials getting error "Access denied"

**Credentials: - 
  UserName: - docker
  Pasowrd: - tcuser**

![image](https://github.com/kubernetes/minikube/assets/97210868/407c41e0-4315-4fde-9db7-a497c50cc450)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/12840249/logs.txt)

### Operating System

Windows

### Driver

VirtualBox

**Comment by siddique670** [comment]
Logs file is attached with Name **logs.txt**

**Comment by spowelljr** [comment]
Hi @siddique670, for security purposes, authenticating with a user and password has been removed from minikube. If you want to authenticate use the key in the minikube home folder.

`~/.minikube/machines/<profile_name>/id_rsa`

**Comment by siddique670** [comment]
@spowelljr After login with minikube ssh then after i did changed the password with passwd cmd manually then after able to take access by puty.

**Comment by spowelljr** [comment]
Glad you were able to make it work!
