### ISSUE TITLE
kubernetes-dashboard endpoint not found

### ISSUE THREAD

**Issue by spnzig** [kubernetes/minikube#1740]
** BUG REPORT **

**Minikube version** (use `minikube version`): v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu 16.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.20.0.iso
- **Install tools**:
- **Others**:  kubernetes-dashboard
kubectl create -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml

**What happened**:
```
minikube dashboard does not start 
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
.....
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet


```

**What you expected to happen**:
Bee able to access minikube dashboard

**How to reproduce it** (as minimally and precisely as possible):
minikube dashboard 

**Anything else do we need to know**:
I was able to successfully use the dashboard with VPN, but following the new install again (fresh install) doesnt work.
The endpoint for kubernetes-dashboard is not shown.
There are no errors in minikube logs

```
kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   kube-addon-manager-minikube             1/1       Running   0          11m
kube-system   kube-dns-1301475494-xtb3b               3/3       Running   0          8m
kube-system   kubernetes-dashboard-2039414953-dvv3m   1/1       Running   0          9m
kube-system   kubernetes-dashboard-2crsk              1/1       Running   0          8m
ps@ns-OptiPlex-7020:~$ kubectl get endpoints --all-namespaces
NAMESPACE     NAME                      ENDPOINTS                     AGE
default       kubernetes                10.0.2.15:8443                11m
kube-system   kube-controller-manager   <none>                        6m
kube-system   kube-dns                  172.17.0.4:53,172.17.0.4:53   8m
kube-system   kube-scheduler            <none>                        6m
kube-system   kubernetes-dashboard      <none>                        9m
`
```

**Comment by r2d4** [comment]
You don't need to create the dashboard yourself, the dashboard is created automatically on `minikube start`.
