### ISSUE TITLE
Unable to connect/or reach any svc.cluster.local on Ubuntu 20.04

### ISSUE THREAD

**Issue by stevenanthonyrevo** [kubernetes/minikube#17429]
### What Happened?

Minikube Community, 

I've ran into an issue with minikube v1.31.2. It seems this behavior is specific to linux.

I am unable to connect via DNS `service-name.namespace.svc.cluster.local:$nodeport` from within a deployment or service yaml?

I noticed Minikube on MacOs interacts differently with the docker-daemon then on linux. 

### Attach the log file

I1014 21:08:40.597852  125680 notify.go:220] Checking for updates...
I1014 21:08:40.598835  125680 config.go:182] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.27.4
I1014 21:08:40.599012  125680 driver.go:373] Setting default libvirt URI to qemu:///system
I1014 21:08:40.626305  125680 docker.go:121] docker version: linux-24.0.4:Docker Engine - Community
I1014 21:08:40.626388  125680 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I1014 21:08:40.880052  125680 start_flags.go:901] Wait components to verify : map[apiserver:true system_pods:true]
I1014 21:08:40.931587  125680 out.go:177] 📌  Using Docker driver with root privileges
I1014 21:08:40.987258  125680 cni.go:84] Creating CNI manager for ""
I1014 21:08:40.987311  125680 cni.go:158] "docker" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge

### Operating System

Ubuntu

### Driver

Docker

**Comment by Ruchira-R** [comment]
Hi @stevenanthonyrevo 

Did you find a solution around this? I am unable to do the same on my centos VM

**Comment by stevenanthonyrevo** [comment]
After some difficulties I decided to install microk8s on Ubuntu.

Works perfectly!



On Mar 27, 2024, at 7:03 AM, Ruchira-R ***@***.***> wrote:

﻿

Hi @stevenanthonyrevo<https://github.com/stevenanthonyrevo>

Did you find a solution around this? I am unable to do the same on my centos VM
