### ISSUE TITLE
Confusing kubectl version compatibility warning

### ISSUE THREAD

**Issue by Aseiide** [kubernetes/minikube#17440]
### What Happened?

# steps to reproduce the issue

1. execute `minikube start`

```
😄  minikube v1.31.2 on Darwin 13.4
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running hyperkit "minikube" VM ...
❗  This VM is having trouble accessing https://registry.k8s.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.27.4 on Docker 24.0.4 ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner

❗  /usr/local/bin/kubectl is version 1.24.1, which may have incompatibilities with Kubernetes 1.27.4.
    ▪ Want kubectl v1.27.4? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

2. execute minikube kubectl -- get pods -A

```
NAMESPACE     NAME                               READY   STATUS    RESTARTS       AGE
kube-system   coredns-5d78c9869d-6mb8m           1/1     Running   5 (13m ago)    30h
kube-system   etcd-minikube                      1/1     Running   2 (13m ago)    30h
kube-system   kube-apiserver-minikube            1/1     Running   3 (12m ago)    30h
kube-system   kube-controller-manager-minikube   1/1     Running   2 (13m ago)    30h
kube-system   kube-proxy-fpsgn                   1/1     Running   2 (13m ago)    30h
kube-system   kube-scheduler-minikube            1/1     Running   2 (13m ago)    30h
kube-system   storage-provisioner                1/1     Running   20 (13m ago)   30h
```

# issue

```
❗  /usr/local/bin/kubectl is version 1.24.1, which may have incompatibilities with Kubernetes 1.27.4.
    ▪ Want kubectl v1.27.4? Try 'minikube kubectl -- get pods -A'
```

The above warning appears, but `executing minikube kubectl -- get pods -A` only allows us to check the status of the pods and does not resolve the compatibility issue. 
This can confuse users about whether they should proceed to the next step or first resolve the compatibility issue.

# suggestion

How about changing the command to something like kubectl version --output=yaml to check the kubectl version?

like this↓
```
❗  /usr/local/bin/kubectl is version 1.24.1, which may have incompatibilities with Kubernetes 1.27.4.
    ▪ Want kubectl v1.27.4? Try 'kubectl version --output=yaml'
```

# environment

- OS: macOS Ventura13.4
- kubernetes: v1.27.4
- kubectl:

```
clientVersion:
  buildDate: "2022-05-24T12:26:19Z"
  compiler: gc
  gitCommit: 3ddd0f45aa91e2f30c70734b175631bec5b5825a
  gitTreeState: clean
  gitVersion: v1.24.1
  goVersion: go1.18.2
  major: "1"
  minor: "24"
  platform: darwin/amd64
kustomizeVersion: v4.5.4
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/12930254/log.txt)

### Operating System

None

### Driver

None

**Comment by afbjorklund** [comment]
Why yaml? User can continue to use `minikube kubectl --` if they want.

But we should link to the official kubectl installation docs too

**Comment by Aseiide** [comment]
@afbjorklund 
thank you for your reply.

> Why yaml?

I only knew the `kubectl version --output=yaml` command.
But now I know there is `kubectl version --short`.

> But we should link to the official kubectl installation docs too

Yes, I think so too.
I think we should link to the kubectl installation.

linux: https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/
macOS: https://kubernetes.io/docs/tasks/tools/install-kubectl-macos/
windows: https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/

**Comment by afbjorklund** [comment]
* #17430

**Comment by afbjorklund** [comment]
Note that `minikube kubectl` runs the command.

While `kubectl version` just outputs some text...

**Comment by Aseiide** [comment]
I see..
I'm a newbie and was confused the first time I used minikube, so I created this issue
