### ISSUE TITLE
Mac M2:  unable to inspect a not running container to get SSH port

### ISSUE THREAD

**Issue by AliciaZ429** [kubernetes/minikube#17443]
### What Happened?

It keep telling me:
  StartHost failed, but will try again: creating host: create: provisioning: get ssh host-port: unable to inspect a not running container to get SSH port

### Attach the log file

MacBook-Air-3:~ zhangyingqi$ minikube start
😄  minikube v1.31.2 on Darwin 13.6 (arm64)
✨  Automatically selected the docker driver
📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.27.4 preload ...
    > preloaded-images-k8s-v18-v1...:  327.74 MiB / 327.74 MiB  100.00% 61.90 M
🔥  Creating docker container (CPUs=2, Memory=1989MB) ...
✋  Stopping node "minikube"  ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: provisioning: get ssh host-port: unable to inspect a not running container to get SSH port

### Operating System

macOS (Default)

### Driver

Docker

**Comment by pnasrat** [comment]
I tried to reproduce on a Mac using the docker driver which works , but have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.
* Run `minikube logs --file logs.txt` and attach the logs.txt file
* The full output of `docker context ls` 
* The full output of `docker system info`
* The full output of `docker ps -a` 
* Run `docker logs  minikube | tee minikube-docker.log` and attach `minikube-docker.log` 

/triage needs-information
