### ISSUE TITLE
Minikube commands fail with error `Exiting due to DRV_CP_ENDPOINT: Unable to get forwarded endpoint: failed to lookup ip for ""`

### ISSUE THREAD

**Issue by munir0b0t** [kubernetes/minikube#17452]
### What Happened?

I am following the tutorial in https://kubernetes.io/docs/tutorials/hello-minikube/ on Archlinux laptop with docker. I did `minikube start` and the docker container has started up. But when I run `minikube dashboard`, I get the error 

```
❌  Exiting due to DRV_CP_ENDPOINT: Unable to get forwarded endpoint: failed to lookup ip for ""
💡  Suggestion: 

    Recreate the cluster by running:
    minikube delete <no value>
    minikube start <no value>

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_dashboard_e82743e0f55314733604a6150dcacabfbc842639_0.log               │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```

Deleting and restarting did not work, even after I restarted my entire machine.
When I run `minikube logs --file=logs.txt`, I get the same error. I have attached all the log files below.

Versions
* Linux: 6.5.7 
* Docker: 24.0.6
* minikube: 1.31.2

I'm not entirely sure what the issue is here since the only other reference I found to the error is on Windows. I can verify that the `minikube` container is running and I am able to log in to the container with `docker exec -it minikube bash` while the container is running.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/13058887/logs.txt)
[minikube_dashboard_e82743e0f55314733604a6150dcacabfbc842639_0.log](https://github.com/kubernetes/minikube/files/13058890/minikube_dashboard_e82743e0f55314733604a6150dcacabfbc842639_0.log)
[minikube_logs_273c584afb8f56625d862285474a6a21019a3238_0.log](https://github.com/kubernetes/minikube/files/13058891/minikube_logs_273c584afb8f56625d862285474a6a21019a3238_0.log)

### Operating System

Other

### Driver

Docker

**Comment by pnasrat** [comment]
I tried to reproduce but have been unable to do so. I setup a VM with arch linux from `Arch-Linux-x86_64-cloudimg-20231001.182377.qcow2`, installed docker using pacman, started the service (and added my user to docker group) then downloaded and started minikube and did not see the `DRV_CP_ENDPOINT` error when I ran `minikube dashboard`.

The error is raised in `ControlPlaneEndpoint` but what is notable from your error message is that the hostname printed by the error message is `""`, ie an empty string. If `net.LookupIP` is called with `""` it will error.  Hostname is set by checking the environment for DOCKER_HOST

@munir0b0t on your Archlinux laptop can you tell me what `env | grep DOCKER_HOST` shows.

**Comment by pnasrat** [comment]
Looking at the code, there may be some [valid values](https://github.com/moby/moby/blob/1f096174d614276845527790e556a6a3911ae99c/opts/hosts_test.go#L26) of DOCKER_HOST that the `minikube` host parsing may fail at. 


https://github.com/kubernetes/minikube/blob/bca8883d05f132614a5ce7779609f4e432d54aa2/pkg/minikube/driver/endpoint.go#L41
```go
		hostname := oci.DaemonHost(driverName)

		ips, err := net.LookupIP(hostname)
		if err != nil || len(ips) == 0 {
			return hostname, nil, port, fmt.Errorf("failed to lookup ip for %q", hostname)
		}

```

in `oci.DaemonHost` 

```
	if driver == Docker {
		if dh := os.Getenv(constants.DockerHostEnv); dh != "" {
			if u, err := url.Parse(dh); err == nil {
				if u.Host != "" {
					return u.Hostname()
				}
			}
		}
	}
	return DefaultBindIPV4
```

https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kic/oci/oci.go#L701

A simple reproducer using "tcp://:"  (that docker has as valid) shows a failure where we get a host but an empty hostname from the parsed URL

https://go.dev/play/p/l_rSOLHq0TW 

```
u.Host: ":"
u.Hostname() ""
```

**Comment by pnasrat** [comment]
Indeed with running `minikube start` with DOCKER_HOST="tcp://:" exported and docker configured for localhost access per https://docs.docker.com/config/daemon/remote-access/#configuring-remote-access-with-systemd-unit-file I get the`DRV_CP_ENDPOINT` error

```
❌  Exiting due to DRV_CP_ENDPOINT: Unable to get forwarded endpoint: failed to lookup ip for ""
```

**Comment by pnasrat** [comment]
Hmm @munir0b0t I'd still like to understand what it is about your config that is triggering the issue. Could you also check:

```
docker context ls
```

**Comment by pnasrat** [comment]
@munir0b0t hmm - so the way the docker driver works is there is a minikube docker container that within it is also running containers. For the docker driver  you can get what the node IP should be via docker inspect. Note that setting it to 127.0.0.1 won't work as that's not where the mapped port to the container through to the apiserver is (for comparison ` curl -I -k https://127.0.0.1:8443` would fail but `curl -I -k https://192.168.49.2:8443` responds from the host machine.

Can you do the below  can you try starting minikube after a purge delete and see if the config json still has no ip set in the node

```
minikube stop
minikube delete --purge --all
minikube start
```

```sh
docker inspect \
  -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' minikube
  192.168.49.2
```

If that doesn't return an IP address please attach the output of 

`docker network inspect minikube`

For comparison on my system it matches here ` jq '.["Nodes"]'  ~/.minikube/profiles/minikube/config.json `
```json
[
  {
    "Name": "",
    "IP": "192.168.49.2",
    "Port": 8443,
    "KubernetesVersion": "v1.28.3",
    "ContainerRuntime": "docker",
    "ControlPlane": true,
    "Worker": true
  }
]
```

**Comment by errisnil** [comment]
On ArchLinux specifically this happened to me when I was using tailscale with the following options: 
```sh
sudo tailscale up --exit-node=<something> --exit-node-allow-lan-access
```

Now if I run tailscale without an exit node like this:
```
sudo tailscale up --exit-node= --reset
```
or just have tailscale not running my minikube starts all well and good. I can access the dashboard as well.

Now I don't know networking well enough to understand exactly why transferring all internet traffic to an exit node would interfere with loopback ips which minikube is presumably using - but this has been my experience.

Maybe tailscale routes all traffic to the exit node - and maybe something other than tailscale is causing something similar on OP's system?

**Comment by daverussellaspire** [comment]
I appreciate this is an old thread, I came across this issue having deleted a cluster that was no longer compatible with the image.

The first issue I encountered was the following output after trying to start minikube (using kvm2 driver in my case)

```
minikube start --driver=kvm2 --profile=minikube
....
Image was not built for the current minikube version. To resolve this you can delete and recreate your minikube cluster using the latest images. Expected minikube version: v1.34.0 -> Actual minikube version: v1.35.0
```
So I ran minikube delete

Further issues and suggestions didn't work...

```
Exiting due to DRV_CP_ENDPOINT: failed to construct cluster server address: failed to lookup ip for ""
💡  Suggestion: 

    Recreate the cluster by running:
    minikube delete --profile=minikube
    minikube start --profile=minikube
```

Thank you to @pnasrat for his reply, 7 Nov, instead of using minikube delete, I used **--purge --all**.

```
minikube stop
minikube delete --purge --all
minikube start --driver=kvm2 --profile=minikube
```

Anyway, just wanted to say thank you.

**Comment by VictorioBerra** [comment]
Facing this exact same issue on a brand new Mint linux install on a modern Thinkpad using Docker. I dont have a `/etc/systemd/network/60-bridge.network` but networkctl shows a bunch of bridge devices. A lot of my command output was similar to @munir0b0t but I cant figure out how to "change the systemd match pattern" and fix it.
