### ISSUE TITLE
Ingress DNS - Outdated documentation?

### ISSUE THREAD

**Issue by RajaniCode** [kubernetes/minikube#17498]
Where is /etc/resolver/minikube-test in macOS Sonoma? Do you mean /etc/resolv.conf, which is not consulted for DNS hostname resolution?

Does the minikube addon ingress-dns work or is it work-in-progress? Where is sample/exmple for it?

```
rajaniapple@Rajanis-MacBook-Pro ~ % sw_vers                         
ProductName:		macOS
ProductVersion:		14.0
BuildVersion:		23A344
rajaniapple@Rajanis-MacBook-Pro ~ % arch                            
arm64
rajaniapple@Rajanis-MacBook-Pro ~ % ls /etc/resolver/                      
ls: /etc/resolver/: No such file or directory
rajaniapple@Rajanis-MacBook-Pro ~ % cat /etc/resolv.conf                   
#
# macOS Notice
#
# This file is not consulted for DNS hostname resolution, address
# resolution, or the DNS query routing mechanism used by most
# processes on this system.
#
# To view the DNS configuration used by this system, use:
#   scutil --dns
#
# SEE ALSO
#   dns-sd(1), scutil(8)
#
# This file is automatically generated.
#
```

**Comment by cirix** [comment]
Hi,
it works but you need to install the version. for the ARM64.
`minikube addons enable ingress-dns --images="IngressDNS=davidwincent/minikube-ingress-dns-arm64" --registries="IngressDNS=registry.hub.docker.com"`

and then in macosx system you should not edit the resolv.conf file. If you want to use ingress dns use the scutil to define a new dns resolver for the svc.cluster.local domain and then all services on your ingress definitions should be resolvable on the ip of the $(minikube ip) value.

br
\n\b
