### ISSUE TITLE
Icons of footer at minikube site requires updation

### ISSUE THREAD

**Issue by aj11anuj** [kubernetes/minikube#17547]
### What Happened?

1. Left icon redirects to Contributing guide and right icon redirects to roadmap. Do we really need these 2 icons at footer? Even if we need these 2 icons at footer then there arrangement and their icon can be arranged in a better way.
![Screenshot (830)](https://github.com/kubernetes/minikube/assets/116108975/10019c23-2a9b-47a9-92aa-5ce3f9f2342d)

2. There are 3 icons at left and 4 icons at right, I think there should be symmetrical no. of icons at both sides.
![Screenshot (832)](https://github.com/kubernetes/minikube/assets/116108975/318d92ce-4a48-4b05-9559-04f8f3d5335c)

3. There are 2 mailing list icons there (dev and user). It can also be arranged in a better way or with different icons.

I think these icons can be arranged in a better way like:-
1. `Dev mailing list` icon and `user mailing list` icon can be arranged at left bottom side.
2. `Contributing guide` and `roadmap` icon can be arranged at right bottom side.
3. `Twitter`, `Slack` and `Github` icon can be arranged at center, just above `"© 2023 The Kubernetes Authors -- All Rights Reserved"`

### Attach the log file

This issue doesn't requires log

### Operating System

None

### Driver

None

**Comment by ankur0904** [comment]
@aj11anuj Can I work on this issue?
