### ISSUE TITLE
Low limit on number of files on single directory level on mounted volume

### ISSUE THREAD

**Issue by sutasu** [kubernetes/minikube#1755]
BUG REPORT

**Minikube version**:
v0.20.0

**Environment**:
- **OS** : Ubuntu 16.04.2 LTS
- **VM Driver** :virtualbox
- **ISO version** :v0.18.0
- **Install tools**:
- **Others**:

**What happened**:

When number of files on the host on single directory level is bigger than 128, there is no access to that directory is on mounted volume in minikube.

**What you expected to happen**:
Have an access to the directories with number of files limited by filesystem or at least much bigger than 128

**How to reproduce it** (as minimally and precisely as possible):
$> mkdir -p /tmp/k8s-volume/vvv; rm -rf /tmp/k8s-volume/vvv/*; for ii in {0..129}; do touch /tmp/k8s-volume/vvv/$ii; done
$> minikube mount /tmp/k8s-volume/vvv:/vvv&
This daemon process needs to stay alive for the mount to still be accessible...
ufs starting
$> minikube ssh "ls -l /vvv"
total 0
ls: reading directory '/vvv': Unknown error 526
E0725 17:11:19.411816    6961 ssh.go:53] Error attempting to ssh/run-ssh-command: exit status 2

**Comment by aaron-prindle** [comment]
If you upgrade to the latest release of minikube v0.21.0 this should be fixable now.  In this release, there is now an '--msize' flag that you can configure which can configure.  The default value is has been doubled to be 262144 in the new release.  If you are still seeing this issues, pass in a larger value for the msize and rerun mount: `minikube mount --msize=524288`

**Comment by aaron-prindle** [comment]
Closing, fixed with #1705
