### ISSUE TITLE
Checa file

### ISSUE THREAD

**Issue by Lyllt8** [kubernetes/minikube#17584]
**Los comandos necesarios para reproducir la incidencia**:

**El resultado completo del comando que ha fallado**: <details>

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by justinclift** [comment]
Note that this user appears to be a bot, creating issues with random text in repos. :frowning:

(found by them submitting multiple issues like this to the sqlitebrowser repos)

I've just reported this account to GitHub ("spammer").  Hopefully they'll nuke it.

**Comment by justinclift** [comment]
> I've just reported this account to GitHub ("spammer"). Hopefully they'll nuke it.

Nope.  GitHub Support are no longer nuking bots doing nothing more than generate spam and waste people's time.  How far they've fallen.
