### ISSUE TITLE
Can not start minikube with the docker driver

### ISSUE THREAD

**Issue by UncleVic** [kubernetes/minikube#17587]
### What Happened?

I try to run minikube on Synology, and I'd like to run it with a docker driver.
After running the command `minikube start --driver=docker --wait=all` I have a downloaded image and a container `minikube' is running: 
```
CONTAINER ID   IMAGE                                          COMMAND                  CREATED         STATUS         PORTS                                                                                                                                     NAMES
2fa1443e9018   gcr.io/k8s-minikube/kicbase:v0.0.40            "/usr/local/bin/entr…"   7 minutes ago   Up 7 minutes   127.0.0.1:32817->22/tcp, 127.0.0.1:32816->2376/tcp, 127.0.0.1:32815->5000/tcp, 127.0.0.1:32814->8443/tcp, 127.0.0.1:32813->32443/tcp      minikube
```

but finally, I have an error

```
😄  minikube v1.31.2 on
✨  Using the docker driver based on user configuration
💨  For improved Docker performance, enable the overlay Linux kernel module using 'modprobe overlay'
❗  docker is currently using the btrfs storage driver, setting preload=false
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...

❌  Exiting due to RUNTIME_ENABLE: Failed to enable container runtime: sudo systemctl restart docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
``` 

As I understand, there aren't any permissions to run a command `docker ps`, but I'm sure that a current user has those permissions.

And some more.
I don't have a `docker.service` to run `systemctl restart docker`. The docker is installed as a Synology package.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/13295746/logs.txt)

### Operating System

Other

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @UncleVic, there is a transient issue with the docker restart that we haven't resolved yet, there's a small chance the docker restart will fail. If you run `minikube delete` and then try starting it again does it resolve your issue?

The docker commands are running inside minikube, minikube has its own docker instance it creates, you can ignore them.

**Comment by UncleVic** [comment]
Hi @spowelljr, I tried to delete and start it again - unsuccessful.

But, pay attention - when I start the same configuration on a Mac M1 with Docker Desktop - everything is ok.

**Comment by afbjorklund** [comment]
I don't think it works to run minikube docker with overlay2, on top of a docker with btrfs - without extra config.

**Comment by afbjorklund** [comment]
I thought that Synology was something like a NAS, not anything that you would typically run minikube on?

**Comment by pkorim** [comment]
> Hi @UncleVic, there is a transient issue with the docker restart that we haven't resolved yet, there's a small chance the docker restart will fail. If you run `minikube delete` and then try starting it again does it resolve your issue?
> 
> The docker commands are running inside minikube, minikube has its own docker instance it creates, you can ignore them.

I have the same issue. there is no docker.service on synology. it is only docker application and /var/run/docker.sock
this is owner by user root group root . 

thats why you get error by minikube start.
it tries to use the 
 docker version --format {{.Server.Os}}-{{.Server.Version}}:{{.Server.Platform.Name}}
 command.
 
I made chown :docker /var/run/docker.sock and the command worked.

you even dont have whereis usemod apt utilities. but you may manage user and groups by the package. (I created dcker group there)


I searched the docker related files over the whole volume and get this


$ find  /  -name docker 2> null
/sys/fs/cgroup/cpu/docker
/sys/fs/cgroup/cpuset/docker
/sys/fs/cgroup/blkio/docker
/sys/fs/cgroup/memory/docker
/sys/fs/cgroup/cpuacct/docker
/sys/fs/cgroup/freezer/docker
/sys/fs/cgroup/devices/docker
/sys/fs/cgroup/systemd/docker
/usr/local/bin/docker
/etc/docker
/run/docker
/volume1/@eaDir/docker
/volume1/@appstore/ContainerManager/usr/bin/docker
/volume1/@appdata/ContainerManager/docker
/volume1/homes/pkorim/git/bigdatacoourse/Global-rd/big-data-engineer/docker
/volume1/homes/pkorim/git/bigdatacoourse/big-data-engineer/docker
/volume1/docker
/volume1/web_packages/docker

$ find  /  -name docker.* 2> null
/run/docker.sock
/run/docker.pid
/run/lock/sharesnap/sharesnap_snapcount_lock/docker.lock
/volume1/@appstore/ContainerManager/conf/cron/docker.conf
/volume1/@appstore/ContainerManager/conf/syslog/docker.logrotate
/volume1/@appstore/ContainerManager/conf/syslog/docker.syslog-ng.conf
/volume1/@appstore/ContainerManager/config/docker.config
/volume1/@appstore/ContainerManager/ui/docker.js

as you can see ther is no docker.service here.
