### ISSUE TITLE
 default KVM network doesn't exist

### ISSUE THREAD

**Issue by rkachach** [kubernetes/minikube#17607]
### What Happened?

Minikube fails to create the kvm2 VM

```
* Using the kvm2 driver based on user configuration
* Downloading driver docker-machine-driver-kvm2:
* Downloading VM boot image ...
...
* Failed to start kvm2 VM. Running "minikube delete" may fix it: driver start: ensuring active networks: checking network default: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')

X Exiting due to PR_KVM_MISSING_NETWORK: Failed to start host: driver start: ensuring active networks: checking network default: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')
* Suggestion: Validate your KVM networks. Run: virt-host-validate and then virsh net-list --all
```

### Attach the log file

* Using the kvm2 driver based on user configuration
* Downloading driver docker-machine-driver-kvm2:
* Downloading VM boot image ...
E1113 11:36:09.474584 2279624 iso.go:90] Unable to download https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso?checksum=file:https://storage.googleapis.com/minikube-builds/iso/16971/minikube-v1.31.0-amd64.iso.sha256 Dst:/home/jenkins-build/.minikube/cache/iso/amd64/minikube-v1.31.0-amd64.iso.download Pwd: Mode:2 Umask:---------- Detectors:[0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8 0x3f9c8a8] Decompressors:map[bz2:0xc00061ded0 gz:0xc00061ded8 tar:0xc00061de70 tar.bz2:0xc00061de80 tar.gz:0xc00061de90 tar.xz:0xc00061dea0 tar.zst:0xc00061dec0 tbz2:0xc00061de80 tgz:0xc00061de90 txz:0xc00061dea0 tzst:0xc00061dec0 xz:0xc00061dee0 zip:0xc00061def0 zst:0xc00061dee8] Getters:map[file:0xc0005a88a0 http:0xc00100c190 https:0xc00100c1e0] Dir:false ProgressListener:<nil> Insecure:false DisableSymlinks:false Options:[]}: invalid checksum: Error downloading checksum file: bad response code: 404
* Downloading VM boot image ...
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.27.4 preload ...
* Creating kvm2 VM (CPUs=2, Memory=4096MB, Disk=10240MB) ...
! StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: creating network: default KVM network doesn't exist: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')
* Restarting existing kvm2 VM for "minikube" ...
* Failed to start kvm2 VM. Running "minikube delete" may fix it: driver start: ensuring active networks: checking network default: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')

X Exiting due to PR_KVM_MISSING_NETWORK: Failed to start host: driver start: ensuring active networks: checking network default: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')
* Suggestion: Validate your KVM networks. Run: virt-host-validate and then virsh net-list --all

### Operating System

Ubuntu

### Driver

KVM2

**Comment by rkachach** [comment]
@afbjorklund thanks for taking care of this. On the system where the installation failed I can see that the following files are being installed:

```
sudo apt install -y qemu-kvm libvirt-daemon-driver-qemu libvirt-clients libvirt-daemon-system runc python3

Reading package lists...
Building dependency tree...
Reading state information...
libvirt-clients is already the newest version (8.0.0-1ubuntu7.7).
libvirt-daemon-driver-qemu is already the newest version (8.0.0-1ubuntu7.7).
libvirt-daemon-system is already the newest version (8.0.0-1ubuntu7.7).
```
So not sure which package is missing from the above list!

**Comment by nusrath432** [comment]
I tried using KVM on minikube v1.32.0 on Ubuntu 22.04 as follows:
```
sudo virsh net-list --all
 Name          State    Autostart   Persistent
------------------------------------------------
 anaxnetwork   active   yes         yes
```

```
minikube start -p anax node 2 --driver=kvm2 --network=anaxnetwork --kvm-network=anaxnetwork
```
or
```
minikube start -p anax node 2 --driver=kvm2 --kvm-network=anaxnetwork
```
but it still looks for default network instead of my custom anaxnetwork

❌  Exiting due to PR_KVM_MISSING_NETWORK: Failed to start host: driver start: ensuring active networks: checking network default: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')

**Comment by nusrath432** [comment]
The following command seems to have worked now (no changes to KVM or Minikube):

```
$ minikube start -p anax --driver=kvm2 --network=anaxnetwork  --kvm-network=anaxnetwork --nodes=2
```

```
😄  [anax] minikube v1.32.0 on Ubuntu 22.04
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node anax in cluster anax
🔥  Creating kvm2 VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
📦  Preparing Kubernetes v1.28.3 on containerd 1.7.8 ...
❌  Unable to load cached images: loading cached images: stat /home/user/.minikube/cache/images/amd64/registry.k8s.io/kube-apiserver_v1.28.3: no such file or directory
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

👍  Starting worker node anax-m02 in cluster anax
🔥  Creating kvm2 VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ NO_PROXY=10.10.10.223
📦  Preparing Kubernetes v1.28.3 on containerd 1.7.8 ...
    ▪ env NO_PROXY=10.10.10.223
    > kubectl.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubelet.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubectl:  47.56 MiB / 47.56 MiB [------------] 100.00% 11.83 MiB p/s 4.2s
    > kubeadm:  46.77 MiB / 46.77 MiB [--------------] 100.00% 1.80 MiB p/s 26s
    > kubelet:  105.65 MiB / 105.65 MiB [------------] 100.00% 2.12 MiB p/s 50s
🔎  Verifying Kubernetes components...

❗  /usr/local/bin/kubectl is version 1.25.0, which may have incompatibilities with Kubernetes 1.28.3.
    ▪ Want kubectl v1.28.3? Try 'minikube kubectl -- get pods -A'
🏄  Done! kubectl is now configured to use "anax" cluster and "default" namespace by default

```

**Comment by rkachach** [comment]
@afbjorklund I'm still hitting this issue on our testing env, any recommendation to fix it? am I missing any package?

**Comment by rkachach** [comment]
Back to this, just in case somebody is facing a similar issue. I was able to workaround it by basically forcing the re-creation of the kvm network, this way I don't rely on having the default network pre-installed. Following is the bash function I used.

```
recreate_default_network(){

    # destroy any existing kvm default network
    if sudo virsh net-destroy default; then
	sudo virsh net-undefine default
    fi

    # let's create a new kvm default network
    sudo virsh net-define /usr/share/libvirt/networks/default.xml
    if sudo virsh net-start default; then
        echo "Network 'default' started successfully."
    else
        # Optionally, handle the error
        echo "Failed to start network 'default', but continuing..."
    fi

    # restart libvirtd service and wait a little bit for the service
    sudo systemctl restart libvirtd
}

```
