### ISSUE TITLE
Issue with LocalKube stopping intermittently

### ISSUE THREAD

**Issue by wardhane** [kubernetes/minikube#1762]
BUG REPORT
**Minikube version** :
`minikube version: v0.20.0`

**Environment**:
- **OS** : Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.20.0
- **Install tools**: minikube for windows.
- **Others**:
**What happened**:
Issue with Minikube using HyperV occasionally restarting and losing its configuration. Checking status shows that localKube is stopped.

**What you expected to happen**:
I expected Minikube to work consistently well.

**How to reproduce it** (as minimally and precisely as possible):
This happens intermittently, so the same steps fail to reproduce the issue. 
I launch Minikube using 
```
PS C:\> minikube start --vm-driver="hyperv" --memory=1024 --hyperv-virtual-switch="MiniKube_External" --v=7 --alsologtos
tderr
Starting local Kubernetes v1.6.4 cluster...
```
This command starts Minikube after a few minutes. Looking at HyperVManager I can see a minikube image with an assigned memory of 1024. 
I verify minikube is running by checking its status and then launching the dashboard. I deploy a few services. Say elastic.
After a few minutes the dashboard becomes unresponsive. On checking the minikube status, it says localkube stopped.
```
PS C:\> minikube status
minikube: Running
localkube: Stopped
kubectl: Misconfigured: pointing to stale minikube-vm.
To fix the kubectl context, run minikube update-context
PS C:\> minikube logs
-- No entries --
```

**Anything else do we need to know**:
Updating the kubectl context does not help. 
```
PS C:\> minikube update-context
Reconfigured kubeconfig IP, now pointing at 172.16.0.201
PS C:\> minikube dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: Get https://172.16.0.201:8443/api/v1/namespaces/kube-system/servi
ces/kubernetes-dashboard: dial tcp 172.16.0.201:8443: connectex: No connection could be made because the target machine actively refused it.
PS C:\> kubectl get nodes
Unable to connect to the server: dial tcp 172.16.0.201:8443: connectex: No connection could be made because the target machine actively refused it.
PS C:\> kubectl cluster-info
Kubernetes master is running at https://172.16.0.201:8443
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
PS C:\> kubectl cluster-info dump
Unable to connect to the server: dial tcp 172.16.0.201:8443: connectex: No connection could be made because the target machine actively refused it.
```
I tried ssh'ing into minikube and checking for zombie processes and I could not find any.

**Comment by wardhane** [comment]
linked to https://github.com/kubernetes/minikube/issues/1252

**Comment by wardhane** [comment]
Closing the issue. I resolved this by stopping minikube in Hyper-V, turning off dynamic memory and then restarting minikube. Minikube is more stable now and no hangs in the last 4 hrs.

**Comment by dimplerohara** [comment]
Hi, I am getting this issue in my environment as well. I am using Minikube version 0.22.0 and Kubectl version 1.7.5 using Hypervisor.
I used below command to start the kube cluster:
minikube start --kubernetes-version="v1.7.5" --vm-driver="hyperv" --hyperv-virtual-switch="My Virtual Switch" --v=7 --alsologtostderr

But it is up only for a fraction of second and is dead after that. Is there any way or any logs to find out the root cause? :(
Dimple.Rohara@LP-5CD73107TM MINGW64 /d/Docker
$ minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 172.20.10.4

Dimple.Rohara@LP-5CD73107TM MINGW64 /d/Docker
$ minikube status
minikube: Running
cluster: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 172.20.10.4

**Comment by JockDaRock** [comment]
looking at the Hyper-V VM for Docker-for-Windows, it appears they natively disable Dynamic Memory

**Comment by JockDaRock** [comment]
completing this request should fix the bug... https://github.com/kubernetes/minikube/issues/1766
