### ISSUE TITLE
Localkube stops running, how to debug?

### ISSUE THREAD

**Issue by justechn** [kubernetes/minikube#1763]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Minikube version** (use `minikube version`):
0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): macos sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.20.0.iso
- **Install tools**:
- **Others**:

**What happened**:
I have a couple devs that are having problems keeping localkube running. Every couple hours, to once a day or so it just stops. I don't know how to debug this. I have tried `minikube logs` but every time the logs are empty. I have looked in ~/.minikube/logs, but that is also empty.

**What you expected to happen**:
localkube should not stop running

**How to reproduce it** (as minimally and precisely as possible):
I don't know it is random and only happens to a few developers

**Anything else do we need to know**:

**Comment by DenisBiondic** [comment]
minikube logs actually does the same as ssh-ing to the machine and doing journalctl -u localkube. Currently, these logs are only saved in memory, perhaps persisting them to disk as well might be a good solution for debugging in the long run (perhaps minikube could implement this "persistent" logging as flag when doing `minikube start`?)

On top of this, I have encountered similar issues with Hyper-V, and I found out the problem by looking into Hyper-V logs instead (was a dynamic memory issue). Perhaps you should look into VirtualBox logs as well?

Third option that I have in my head is starting `minikube logs -f` (tail logs) in a terminal session and leaving this open until the problem occurs again.

**Comment by justechn** [comment]
Thanks for those tips. I will try them out. 

I also agree that minikube needs to have an option to persist the logs

**Comment by r2d4** [comment]
@justechn any update?  anything that could help us debug or reproduce?

**Comment by dlorenc** [comment]
Closing, could you reopen if you find more logs that could be helpful?
