### ISSUE TITLE
trouble running minikube

### ISSUE THREAD

**Issue by arujjval** [kubernetes/minikube#17657]
### What Happened?

it ran "minikube start" command and got this log file

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/13438707/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
H @arujjval, I'm curious, if you run `minikube delete` and then try running `minikube start` again does the issue resolve or do you get the same error?

**Comment by arujjval** [comment]
@spowelljr, I tried that but it got stuck there after I ran the command `minikube delete` as if nothing happened.

**Comment by spowelljr** [comment]
Where was it getting stuck? Could you run it again and add the `--alsologtostderr` flag to the command to get more verbose output.

**Comment by arujjval** [comment]
Thanks for closing the issue @spowelljr. It worked after I reinstalled it. And I totally forgot about the issue opened. So, no issues now.
