### ISSUE TITLE
使用`$ minikube start --image-mirror-country="cn"`命令出现“因 K8S_INSTALL_FAILED 错误而退出：Failed to update cluster: updating control plane: downloading binaries: downloading kubeadm: download failed:”错误

### ISSUE THREAD

**Issue by IronmanJay** [kubernetes/minikube#17661]
😄  Ubuntu 22.04 上的 minikube v1.32.0
✨  根据用户配置使用 docker 驱动程序
✅  正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
📌  使用具有 root 权限的 Docker 驱动程序
👍  正在集群 minikube 中启动控制平面节点 minikube
🚜  正在拉取基础镜像 ...
    > index.docker.io/kicbase/sta...:  453.90 MiB / 453.90 MiB  100.00% 178.39 
❗  minikube was unable to download registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.42, but successfully downloaded docker.io/kicbase/stable:v0.0.42 as a fallback image
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  正在 Docker 24.0.7 中准备 Kubernetes v1.28.3…

❌  因 K8S_INSTALL_FAILED 错误而退出：Failed to update cluster: updating control plane: downloading binaries: downloading kubeadm: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.28.3/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.28.3/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.28.3/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.28.3/bin/linux/amd64/kubeadm.sha256 Dst:/home/iie-iisd/.minikube/cache/linux/amd64/v1.28.3/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x46177c0 0x46177c0 0x46177c0 0x46177c0 0x46177c0 0x46177c0 0x46177c0] Decompressors:map[bz2:0xc0000158f0 gz:0xc0000158f8 tar:0xc0000157f0 tar.bz2:0xc000015800 tar.gz:0xc000015810 tar.xz:0xc000015820 tar.zst:0xc0000158b0 tbz2:0xc000015800 tgz:0xc000015810 txz:0xc000015820 tzst:0xc0000158b0 xz:0xc000015900 zip:0xc000015910 zst:0xc000015908] Getters:map[file:0xc003e010e0 http:0xc0036480f0 https:0xc003648140] Dir:false ProgressListener:0x45d7ae0 Insecure:false DisableSymlinks:false Options:[0x120d740]}: invalid checksum: Error downloading checksum file: bad response code: 404

╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                 │
│    😿  如果上述建议无法帮助解决问题，请告知我们：                                               │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                 │
│                                                                                                 │
│    请运行 minikube logs --file=logs.txt 命令，并将生成的 logs.txt 文件附加到 GitHub 问题中。    │
│                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯

**Comment by michaelwx1** [comment]
大佬，解决了吗？我也是这样
![image](https://github.com/kubernetes/minikube/assets/49359297/fce8fee9-cf95-4267-a090-3fdfdf9a02ed)

**Comment by iamrliu** [comment]
> 大佬，解决了吗？我也是这样 ![image](https://private-user-images.githubusercontent.com/49359297/290477163-fce8fee9-cf95-4267-a090-3fdfdf9a02ed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0NjAzMjgsIm5iZiI6MTcwNTQ2MDAyOCwicGF0aCI6Ii80OTM1OTI5Ny8yOTA0NzcxNjMtZmNlOGZlZTktY2Y5NS00MjY3LWEwOTAtM2ZkZmRmOWEwMmVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE3VDAyNTM0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjNWYzYTlhOTUyZDc0MDNmZDg4M2Y1ZjNhNTY2NmEzYWIxMWZhNzdlZGE5OWIyOTAzYWJlYTQyNzc2MmExYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w0UCWxcuyqcTFRz98M3u3RsVICJwIv7F-vRb4dx85PI)

me too,
have you fixed it ?

**Comment by IronmanJay** [comment]
`minikube start --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --kubernetes-version=v1.23.9 --memory 8192 --cpus 8`，指定仓库即可解决此问题！

**Comment by zengfann** [comment]
> `minikube start --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --kubernetes-version=v1.23.9 --memory 8192 --cpus 8`，指定仓库即可解决此问题！

感谢！

**Comment by 12wzy12** [comment]
> `minikube start --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --kubernetes-version=v1.23.9 --memory 8192 --cpus 8`，指定仓库即可解决此问题！

牛逼啊，zy

**Comment by heavenzhen999** [comment]
> > `minikube start --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --kubernetes-version=v1.23.9 --memory 8192 --cpus 8`，指定仓库即可解决此问题！
> 
> 感谢！

**Comment by 2054686334** [comment]
> `minikube start --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --kubernetes-version=v1.23.9 --memory 8192 --cpus 8`，指定仓库即可解决此问题！

```
hxp@master:~$ minikube start --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'
* Ubuntu 22.04 上的 minikube v1.34.0
* 自动选择 docker 驱动
* 正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
* 使用具有 root 权限的 Docker 驱动程序
* Starting "minikube" primary control-plane node in "minikube" cluster
* 正在拉取基础镜像 v0.0.45 ...
    > index.docker.io/kicbase/sta...:  487.90 MiB / 487.90 MiB  100.00% 2.02 Mi
! minikube was unable to download registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.45, but successfully downloaded docker.io/kicbase/stable:v0.0.45 as a fallback image
* Creating docker container (CPUs=2, Memory=2200MB) ...
* 正在 Docker 27.2.0 中准备 Kubernetes v1.31.0…

X 因 K8S_INSTALL_FAILED 错误而退出：Failed to update cluster: update primary control-plane node: downloading binaries: downloading kubeadm: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.31.0/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.31.0/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.31.0/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.31.0/bin/linux/amd64/kubeadm.sha256 Dst:/home/hxp/.minikube/cache/linux/amd64/v1.31.0/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x4eb7820 0x4eb7820 0x4eb7820 0x4eb7820 0x4eb7820 0x4eb7820 0x4eb7820] Decompressors:map[bz2:0xc00062bab0 gz:0xc00062bab8 tar:0xc00062ba60 tar.bz2:0xc00062ba70 tar.gz:0xc00062ba80 tar.xz:0xc00062ba90 tar.zst:0xc00062baa0 tbz2:0xc00062ba70 tgz:0xc00062ba80 txz:0xc00062ba90 tzst:0xc00062baa0 xz:0xc00062bac0 zip:0xc00062bad0 zst:0xc00062bac8] Getters:map[file:0xc001d93e30 http:0xc0004d2c80 https:0xc0004d2f00] Dir:false ProgressListener:0x4e44750 Insecure:false DisableSymlinks:false Options:[0x12e5e60]}: invalid checksum: Error downloading checksum file: bad response code: 404
```
又有这个问题了，绞尽脑汁无法解决

**Comment by wkjun** [comment]
仅支持minikube1.24.0 版本,
https://github.com/kubernetes/minikube/releases/tag/v1.24.0

`minikube start --image-mirror-country='cn' --cpus=4 --memory=4096mb`

支持的镜像仓库已经停止维护很久.
https://github.com/AliyunContainerService/minikube
