### ISSUE TITLE
ingress addon is failing in minikube

### ISSUE THREAD

**Issue by vnagalli117** [kubernetes/minikube#17673]
### What Happened?

ingress addon is failing in minikube

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/13485106/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by kundan2707** [comment]
Try this:
minikube delete --all
minikube start
minikube addons enable ingress
minikube addons list

**Comment by vnagalli117** [comment]
After restarting the server. enabled the ingress option in Minikube successfully.

You can close this case.

Thank you for your support.
