### ISSUE TITLE
Very unhelpful error messages

### ISSUE THREAD

**Issue by ohjames** [kubernetes/minikube#1767]
* libvirtd not running or user not added to libvirtd/libvirt group: `E0728 13:10:28.999295   29068 start.go:129] Error starting host: Error creating new host: dial tcp: missing address.`
* qemu not installed: `invalid argument: could not find capabilities for domaintype=kvm`

After solving those two problems I get:

* `Error creating host: Error creating machine: Error in driver during machine creation: [Code-55] [Domain-19] Requested operation is not valid: network 'default' is not active.`

The previous two I could eventually solve with googling + luck, but the latest one I'm lost on.

**Comment by ohjames** [comment]
That error message required me adding the argument `--kvm-network=docker-machines`.

Then I got a new cryptic error message which I eventually tracked down to `/etc/libvirt/qemu.conf`, the `group` or `user` has to have access to `/dev/kvm`.

All in all it took me more than 3 hours of googling and deciphering cryptic error messages to get `minikube create` to work.

**Comment by r2d4** [comment]
This error message is actually coming from https://github.com/dhiltgen/docker-machine-kvm.  We can send an upstream patch to fix it there.

I've also been maintaining another kvm-driver here https://github.com/r2d4/docker-machine-driver-kvm. This driver should create or enable the default network if its not.

**Comment by ohjames** [comment]
I had so many problems with that kvm driver, after hours of hacking I ended up with a VM that kubectl couldn't communicate with. I probably should have tried your driver. Ended up using vbox.

**Comment by r2d4** [comment]
Closing this, might be worthwhile to open up an issue upstream in the kvm driver.
