### ISSUE TITLE
Template addons and bundle with localkube

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1768]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  feature request

Currently, we bundle minikube addons such as DNS, heapster, registry-creds, and the dashboard into the minikube binary with `go-bindata`.  The issues with this approach are:

1. Addons cannot be templated https://github.com/kubernetes/minikube/issues/1674 https://github.com/kubernetes/minikube/issues/1747
We will need to eventually template the DNS addon if a user passes in a different DNS domain or service cidr.
2. Addons aren't versioned with the kubernetes distribution, but rather minikube, which can run many different versions.  This is a problem, since minikube will only have one version of an addon, and that version might not be compatible with all versions of kubernetes. https://github.com/kubernetes/minikube/pull/1527#issuecomment-305247644

Proposal:

Addons get bundled with the kubernetes distribution, in this case, localkube.  Not through `go-bindata`, but built from go templates in the code and scp'd into the VM under `/etc/kubernetes/manifests` (for the addon-manager) or the `/etc/kubernetes/addons` for the addons themselves.

Cons: 
1. Having a bunch of templating code is messy, more go code, no syntax highlighting.
2. Not all addons will need templating. In fact, kube-dns is the only one that needs templating.  In the future, if we support `hyperkube` backed minikube clusters, we will need to template parts of the control plane (apiserver, controller-manager) and the other components (proxy, etc.).   

I would be fine with a hybrid approach of only templating the essential addons (kube-dns, anything else we need) and leaving the rest in `deploy/addons`.  They can continue to be added with `go-bindata` or shipped with the minikube tar installation.  #1623

**Comment by donaldguy** [comment]
since its not explicitly mentioned in this ticket, I will state the perhaps obvious that this could be achieved by switching addons to [kubernetes/helm](https://github.com/kubernetes/helm) charts and minikube could include tiller by default as suggested in #1913 

obviously this would require making tiller something of a blessed addon, or localkube could attempt to implement enough of the tiller API to allow a subset of helm source to replace backend for minikube addon stuff

**Comment by timoreimann** [comment]
The addon version skew between Kubernetes and minikube is still a significant problem as far as I can tell. I believe the issue is still relevant.

/remove-lifecycle stale
