### ISSUE TITLE
Docs: drivers page does not list podman for MacOS

### ISSUE THREAD

**Issue by stephanwesten** [kubernetes/minikube#17682]
### What Happened?

I'm investigating minikube + podman as driver. My first google hit was: https://minikube.sigs.k8s.io/docs/drivers/

However podman is not listed for MacOS, afaik it is supported.

A bit more information on the driver concept would also be useful

### Attach the log file

n/a

### Operating System

None

### Driver

None

**Comment by afbjorklund** [comment]
Now that Podman Desktop accepted the minikube extension, maybe there will be some improved documentation for it.

* https://github.com/containers/podman-desktop/issues/4596

* https://podman-desktop.io/docs/minikube

It still has a lot of issues, though. And inherits some of the problems of Docker Desktop, with a strange internal VM etc...

* https://github.com/kubernetes/minikube/issues/8003

* [`is:issue is:open label:co/podman-driver`](https://github.com/kubernetes/minikube/issues?q=is%3Aissue+is%3Aopen+label%3Aco%2Fpodman-driver)
