### ISSUE TITLE
minikube stop should pause rather than lose state

### ISSUE THREAD

**Issue by craigbox** [kubernetes/minikube#177]
If I run minikube stop, the VM is powered off.  It would be nice if there was a 'suspend VM' option so I could restart with state.

**Comment by seh** [comment]
Does this explain why running _minikube start_ forgets about anything that had been running as of the most recent _minikube stop_, despite what [the documentation promises about retaining state](https://github.com/kubernetes/minikube#stopping-a-cluster)?

**Comment by jimmidyson** [comment]
@seh AFAIK pause/resume actually wouldn't exhibit this problem - the underlying problem is that / is running on tmpfs so is reset every time minikube starts the vm.

**Comment by dlorenc** [comment]
Sorry, yeah. https://github.com/kubernetes/minikube/pull/241 fixes the persistence issue. It'll go out in the next release of Minikube.

**Comment by jimmidyson** [comment]
@craigbox Does the persistent disk give you what you wanted via stop/start rather than pause/resume?

The problem I see with pause/resume is that docker machine, which minikube uses under the hood to among other things abstract away the virtualization details, doesn't support pause/resume. We'd have to write our own plugins to minikube for the supported virt providers, which is doable of course but only if worth the effort.

**Comment by craigbox** [comment]
It was just a FR, as it takes a while to boot on my MacBook Air. There's no immediate hurry at all if it's not supported in machine.

**Comment by jimmidyson** [comment]
How long does booting take for you? Wonder if there's anything we can do to improve that? I'd also like pause/resume too.

**Comment by craigbox** [comment]
About a minute.

**Comment by gtirloni** [comment]
I also noticed that `minikube start` after the VM is paused takes 50-100 seconds here.

Environment:

 * Fedora 25 x86_64 (kernel 4.9.14)
 * VirtualBox 5.1.18
 * minikube 0.17.1
 * minikube ISO 1.0.7
 * localkube v1.6.0-beta.3

The log files seem to indicate that locakube goes into full disruption mode following a NodeNotReady status, right after the machine is started again:

```
Mar 23 00:06:41 minikube systemd[1]: Time has been changed
Mar 23 00:06:41 minikube kernel: e1000: eth0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
Mar 23 00:06:41 minikube systemd-networkd[2199]: eth0: Gained carrier
Mar 23 00:06:41 minikube systemd-networkd[2199]: eth0: DHCPv4 address 10.0.2.15/24 via 10.0.2.2
Mar 23 00:06:41 minikube systemd-networkd[2199]: eth0: Configured
Mar 23 00:06:41 minikube localkube[24814]: I0323 00:06:41.897021   24814 event.go:217] Event(api.ObjectReference{Kind:"Node", Namespace:"", Name:"minikube", UID:"7df28ffc-0f4e-11e7-9ac1-08002755291c", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'NodeNotReady' Node minikube status 
is now: NodeNotReady
Mar 23 00:06:41 minikube localkube[24814]: I0323 00:06:41.928940   24814 replication_controller.go:322] Observed updated replication controller kube-dns-v20. Desired pod count change: 1->1
Mar 23 00:06:41 minikube localkube[24814]: I0323 00:06:41.929699   24814 nodecontroller.go:569] NodeController detected that all Nodes are not-Ready. Entering master disruption mode.
Mar 23 00:06:41 minikube localkube[24814]: I0323 00:06:41.937997   24814 replication_controller.go:322] Observed updated replication controller kubernetes-dashboard. Desired pod count change: 1->1
```
After all this process is finished (which includes starting/stopping Docker), it seems minikube is able to proceed with the next phases.

**Comment by gbraad** [comment]
I wonder how relevant this still is...

**Comment by craigbox** [comment]
Booting the VM still takes ~57 seconds for me, now on a MacBook Pro (13-inch, 2016, Four Thunderbolt 3 Ports)

**Comment by tstromberg** [comment]
This appears to be a long-fixed issue: stop should allow one to restart with state.
