### ISSUE TITLE
minicube wont start. seems to be because "certificate authority key already exists"

### ISSUE THREAD

**Issue by agatherer** [kubernetes/minikube#17705]
### What Happened?

I get the following:
 $ minikube start --vm = true

😄  minikube v1.32.0 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3800MB) ...
🤦  StartHost failed, but will try again: creating host: create: bootstrapping certificates: certificate authority key already exists
🔥  Creating docker container (CPUs=2, Memory=3800MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: bootstrapping certificates: certificate authority key already exists

❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: bootstrapping certificates: certificate authority key already exists

I think docker might have gotten corrupted and it seems to have a problem with a .cert in the .minicube directory but all my attempts to fix it have failed.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/13519696/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by pnasrat** [comment]
@agatherer 

I am trying to replicate using  ubuntu 22.04 host. 

There seems to be a mismatch and  it may be you have previously run minikube with the docker driver and are trying to switch to a vm based driver (kvm2/qemu)  as your command line specifies `--vm=true` but the logs specify that you are using the docker driver

If you want to move drivers can you try doing a stop, delete and purge and ensure the docker container is off then. Create a new minikube using vm by following these instructions to see if it fixes it. I also include the commands to kill/remove any old minikube containers using docker cli a. 

- `minikube stop`
- `docker stop minikube`
- `docker rm minikube`
- `minikube delete --purge --all`
- Then run `minikube start --vm=true`

If you don't wish to use kvm/qemu please follow the steps but start minikube with just `minikube start` after the purge/delete.

/kind support
/triage needs-information

**Comment by agatherer** [comment]
Thanks, this helped. As long as I don’t try to use a VM it works now. If I try to use a VM I get

 

$ minikube start --vm=true

😄  minikube v1.32.0 on Ubuntu 20.04

👎  Unable to pick a default driver. Here is what was considered, in preference order:

💡  Alternatively you could install one of these drivers:

    ▪ kvm2: Not installed: exec: "virsh": executable file not found in $PATH

    ▪ qemu2: Not installed: exec: "qemu-system-x86_64": executable file not found in $PATH

    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH

 

❌  Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/

 

I am trying to get away from using KVM. I had installed it while trying to fix an unrelated issue, but this turned out to be the wrong answer and I tried to reinstall virtualbox but now I get 

“the following packages have unmet dependencies” when I run the installer.

 

Thanks

alan

**Comment by pnasrat** [comment]
That error message means that you do not have any of the driver prerequisites to run VM based driver. As per the documentation minikube with the vm based drivers (vs docker or podman) requires additional packages from your distribution

See these docs: https://minikube.sigs.k8s.io/docs/drivers/kvm2/

For kvm2 driver on Jammy you need to do 

`sudo apt update -y && sudo apt install -y qemu-kvm virt-manager libvirt-daemon-system virtinst libvirt-clients bridge-utils` 

For further distribution specific details see the [Ubuntu libvirt docs](https://ubuntu.com/server/docs/virtualization-libvirt)

**Comment by caerulescens** [comment]
@agatherer See this: https://github.com/kubernetes/minikube/issues/18026#issuecomment-1912928053

**Comment by caerulescens** [comment]
Is this still an issue?

**Comment by agatherer** [comment]
Not for me. The suggestions provided seemed to fix it.
