### ISSUE TITLE
minikube start --driver=virtualbox --no-vtx-check

### ISSUE THREAD

**Issue by sow-bara** [kubernetes/minikube#17742]
**Étapes pour reproduire le problème:** 

1.minikube start --driver=virtualbox --no-vtx-check
2. 
3.

**Sortie complète de la commande `minikube logs`:**
<details>

</details>

**Sortie complète de la commande échouée:**
<details>

</details>

**Comment by tamilselvan1102** [comment]
@sow-bara 
please elaborate your issue in English
