### ISSUE TITLE
How can I add a second Minikube cluster to Argo CD?

### ISSUE THREAD

**Issue by snji** [kubernetes/minikube#17746]
### What Happened?

I have started two clusters minikube-1 and minikube-2, and argocd is deployed in the minikube-1 cluster.

 When I use `argocd cluster add` to add the minikube-2 cluster, an error is reported and the connection to the apiserver through 127.0.0.1 times out. What should I do? Can the argocd pod in minikub-1 access the apiserver of minikube-2?

### Attach the log file

Logs.txt not required

### Operating System

macOS (Default)

### Driver

Docker

**Comment by medyagh** [comment]
@snji have tried switching the context ?
kubectl config use-context ...

**Comment by snji** [comment]
> @snji have tried switching the context ? kubectl config use-context ...

Thanks. I refer to the doc https://wave-s.notion.site/minikube-argocd-4126495087164d66a3aa8629fd6ec138?pvs=4 which has solved the problem
