### ISSUE TITLE
Minikube mounting fails on Mac with Docker 4.26

### ISSUE THREAD

**Issue by sverrejb** [kubernetes/minikube#17753]
### What Happened?

Mounting using Docker 4.26.0 fails. Works as expected using 4.24.2. This is under macOS Sonoma 14.1.2.

```X Exiting due to GUEST_MOUNT: mount failed: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=49868,trans=tcp,version=9p2000.L 192.168.65.254 /data/import" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=49868,trans=tcp,version=9p2000.L 192.168.65.254 /data/import": Process exited with status 32
stdout:

stderr:
mount: /data/import: unknown filesystem type '9p'.
```

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/13613319/logs.txt)

### Operating System

macOS Sonoma 14.1.2.

### Driver

Docker 4.26.0

**Comment by afbjorklund** [comment]
It seems like they have removed the 9p filesystem driver from their VM, so needs a Docker Desktop bug.

**Comment by sverrejb** [comment]
To be clear, should I file a bug at Docker?

**Comment by afbjorklund** [comment]
> To be clear, should I file a bug at Docker?

If you want the 9p (minikube mount) option to be enabled in the kernel, I think so. Maybe it is done from LinuxKit ?

**Comment by spowelljr** [comment]
@sverrejb If you specify `--mount --mount-string <source>:<target>` during the `minikube start` command it uses Docker mounting and should work. Mounting after the container is created uses 9p and does seem to be failing.

**Comment by spowelljr** [comment]
Just tried on Docker Desktop 4.29.0 and 9p seems to be working again, so I'm going to close this issue, reopen if not solved.
