### ISSUE TITLE
etcd issue after windows 11 reboot

### ISSUE THREAD

**Issue by PKatBK** [kubernetes/minikube#17769]
### What Happened?

Running fresh installed minikube 1.32.0 on Windows 11 (installed via chocolatey)

When starting simple minikube env via 

`minikube start`

all is fine. 
Running 

`minikube stop`
`minikube start`

still everything works (kubectl get pods, ...)

If I reboot Windows with stopping minikube upfront ( `minikube stop` ), i can start minikube after the reboot and use kubernetes via kubectl.

If I reboot Windows without stopping minikube upfront, kubernetes will not start on the minikube node(s). (see attached logfile from minikube logs)

**Reproduce**
1. install minikube via chocolatey on Windows 11
2. run `minikube start`
3. run `kubectl get pods -A`
4. reboot your windows system
5. after the reboot try again to start minikube via `minikube start`

**Issue:**
I can see that my minikube node had ip address 172.24.202.84 before the reboot. 
After the reboot, `minikube profile list` still shows the ip 172.24.202.84. 
But if i login via `minikube ssh` and run `ifconfig` I can see, that the ip has changed. In my case to 172.24.202.85. When checking the logs of etcd, i can see, he still wants to bind to 172.24.202.84 and not the new ip, the node got assigned.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/13637868/logs.txt)

### Operating System

None

### Driver

None

**Comment by tamilselvan1102** [comment]
This discussion may help to resolve your issue #8728

**Comment by PKatBK** [comment]
> This discussion may help to resolve your issue #8728

Thanks, but deleting the minikube node and creating a new one could not be the solution. 
Yes this will work, but if you have to create after every reboot a new minikube node/cluster and deploy your workloads on it, this is something like a 90's windows solution...

**Comment by tamilselvan1102** [comment]
The issue is still exists and stop the cluster before shutting down would be the only solution.

**Comment by PKatBK** [comment]
Is it possible to register some shutdown process, so the cluster/vm's get shutdown at least when i shutdown windows?

**Comment by tamilselvan1102** [comment]
i think you need to write some script to do that job
