### ISSUE TITLE
minikube start fails on windows server 2019 with hyperv

### ISSUE THREAD

**Issue by azzid** [kubernetes/minikube#17768]
### What Happened?

```
C:\>minikube start --driver hyperv --hyperv-use-external-switch=true
* minikube v1.32.0 on Microsoft Windows Server 2019 Standard 10.0.17763.4974 Build 17763.4974
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Stopping node "minikube"  ...
* Powering off "minikube" via SSH ...
* Deleting "minikube" in hyperv ...
! StartHost failed, but will try again: creating host: create host timed out in 360.000000 seconds
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...^C
```

I can see the vm and the vSwitch getting created in the Hyper-V Manager, but the `minikube start`-command never figures out that the vm has been created/started.

### Attach the log file

[minikube.log](https://github.com/kubernetes/minikube/files/13637117/minikube.log)

### Operating System

Windows

### Driver

Hyper-V

**Comment by tamilselvan1102** [comment]
As per the [tutorial ](https://minikube.sigs.k8s.io/docs/drivers/hyperv/#enabling-hyper-v)  Hyper-V should be enabled

**Comment by tamilselvan1102** [comment]
if you convinced, please close the issue,

**Comment by azzid** [comment]
> if you convinced, please close the issue,

Am unfortunately unable to verify on the machine with the problem - but I did indeed install Minikube before Hyper-V so it is a valid guess as to where the problem lies.

Was able to get it working in windows 10 by doing the installations in the reverse order.
