### ISSUE TITLE
[Problem consultation] How is the minikube dashboard port exposed

### ISSUE THREAD

**Issue by summer-boythink** [kubernetes/minikube#17774]
### What Happened?

![Snipaste_2023-12-13_00-01-37](https://github.com/kubernetes/minikube/assets/57977288/3974827b-a70d-4b3e-90b5-48c9637dbb03)

When I used the `minikube dashboard` on the cloud server, I found that I could not access the `dashboard` using my local browser

I would like to ask if there is any method that comes with minikube or k8s to fulfill my above requirements

Thank you.

### Attach the log file

I don't think so for a while

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Rum minikube locally, or open a tunnel to the remote server using `ssh` and `-L`.

Exposing services on the public IP is a security concern, and not supported anymore.

**Comment by summer-boythink** [comment]
@afbjorklund  Thanks for your reply, I find similar functionality in https://docs.meshery.io/installation/kubernetes/minikube
