### ISSUE TITLE
ipset module not included in minikube

### ISSUE THREAD

**Issue by sands6** [kubernetes/minikube#1779]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Minikube version** (use `minikube version`):

**Environment**:
- **OS** (e.g. from /etc/os-release):
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:

**What happened**:
Because of missing ipset module cannot implement calico

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by erasmus74** [comment]
Agreed. This is the pull request that referenced this issue from an unrelated ticket, it was marked as fixed but was not. This is the BR to follow up.

https://github.com/kubernetes/minikube/issues/1779
