### ISSUE TITLE
Exiting due to DRV_CREATE_TIMEOUT: Failed to start host: creating host: create host timed out in 360.000000 seconds 

### ISSUE THREAD

**Issue by RafiIsaharov** [kubernetes/minikube#17794]
### What Happened?

* minikube v1.32.0 on Microsoft Windows 10 Enterprise 10.0.19045.3693 Build 19045.3693
* Automatically selected the hyperv driver 
* 
\ E1214 11:43:08.164105   23496 main.go:137] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create host timed out in 360.000000 seconds

X Exiting due to DRV_CREATE_TIMEOUT: Failed to start host: creating host: create host timed out in 360.000000 seconds
* Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
* Related issue: https://github.com/kubernetes/minikube/issues/7072

==============================================================
The Minikube is up and running, but it failed to obtain an IP from the Hyper-V default switch. 
From the log, IP was not returned by the command: 
"powershell.exe -NoProfile -NonInteractive ((Hyper-V\Get-VM minikube).networkadapters[0]).ipaddresses[0]"
 
after run command: "powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0])"

```
Name            IsManagementOs VMName   SwitchName     MacAddress   Status IPAddresses
----            -------------- ------   ----------     ----------   ------ -----------
Network Adapter False          minikube Default Switch 00155D04250A {Ok}   {}
```
                                            

### Attach the log file

[lastStart.txt](https://github.com/kubernetes/minikube/files/13673199/lastStart.txt)

### Operating System

Windows

### Driver

Hyper-V

**Comment by KIINGOFKEBAB** [comment]
@RafiIsaharov currently having the same problem, did you find any solutions ?
