### ISSUE TITLE
[Documentation] Readme.md should instruct how to install

### ISSUE THREAD

**Issue by rosskukulinski** [kubernetes/minikube#178]
Reading through the Readme, it would be great to have an ```installation``` section.  I understand there's ongoing work in that area (#12 #5), but at a minimum you can point people to the ```Installation``` section of [Releases](https://github.com/kubernetes/minikube/releases).

**Comment by dlorenc** [comment]
This was definitely on oversight on our part. I'll get some instructions in the main README.md. Thanks for the report!

**Comment by rosskukulinski** [comment]
Nice @dlorenc!  FWIW I've been playing with minikube today and it's working quite well.
