### ISSUE TITLE
Kubernetes-Security-Slam-2023

### ISSUE THREAD

**Issue by acumino** [kubernetes/minikube#17808]
Open tasks for the Kubernetes Security Slam 2023

**Release to Community Infrastructure:**
- ~~[x] Releases are being made via CI(task1)- https://github.com/kubernetes/minikube/issues/17807~~ Cloud-Build is for repos that release images, minikube is not a use case for it.
- ~~[x] Check that Images are Staged and Promoted Using Community Infra (task2)~~ Cloud-Build is for repos that release images, minikube is not a use case for it.

**Automate Security Documentation:**
- [x] Ensure SBOMs are Generated by Kubernetes BOM (task3) @sandipanpanda   https://github.com/kubernetes/minikube/pull/17816
- [ ] Ensure SLSA Attestations are Generated when Possible (task4) @acumino 
- [x] Ensure the Project has a VEX Feed (task5) https://github.com/kubernetes/minikube/pull/17809 https://github.com/kubernetes/minikube/pull/17810

**CLOMonitor: Secure Development Practices:**
- [x] Add OpenSSF badge @acumino https://github.com/kubernetes/minikube/pull/17811
      - Pin docker image to commit hash - https://github.com/kubernetes/minikube/pull/17813
- [x] Add `security-insights.yaml` @sandipanpanda  https://github.com/kubernetes/minikube/pull/17814
- [x] Add project to CLOMonitor / Run tests for Clomonitor (task 7) @acumino  https://github.com/cncf/clomonitor/pull/1379 https://github.com/cncf/clomonitor/pull/1385
- [x] Check for Binary Artifacts (task 8) @acumino (There is only one `.iso` file used in unit test)https://github.com/kubernetes/minikube/issues/17817
- [x] Review the code review (task 9) @prnvkv All changesets reviewed.
- [x] Docs and Best Practice check @acumino https://github.com/kubernetes/minikube/pull/17818
- [x] Dangerous Workflow (task 10) @sandipanpanda No dangerous workflow patterns detected.
- [ ] Security Insights (task 11) @acumino 
- [ ] Dependencies policy (task 12)  @prnvkv 
- [x] Dependency update tool (task 13) @sandipanpanda Dependabot is configured.
- [x] Token Permissions (task 15) @acumino https://github.com/kubernetes/minikube/pull/17812

<hr>

Follow-Ups:
- https://github.com/kubernetes/minikube/pull/17828

**Comment by ArangoGutierrez** [comment]
Cloud-Build is for repos that release images, `minikube` is not a use case for it

**Comment by acumino** [comment]
The release job is required to generate SBOMs and SLSA for each release. I am not able to find one.
@spowelljr Can you confirm that releases are done manually for `minikube`?

**Comment by acumino** [comment]
> The release job is required to generate SBOMs and SLSA for each release. I am not able to find one. @spowelljr Can you confirm that releases are done manually for `minikube`?

/cc @afbjorklund

**Comment by Foge9627** [comment]
56


تم الإرسال من Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Foge9627** [comment]
Ghh

تم الإرسال من Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by afbjorklund** [comment]
I'm not sure that reverting to _older_ versions of software, is a good way to _improve_ security.

**Comment by spowelljr** [comment]
> The release job is required to generate SBOMs and SLSA for each release. I am not able to find one. @spowelljr Can you confirm that releases are done manually for `minikube`?

Releases are currently run manually from a non-publicly accessible Jenkins instance. However we were asked to migrate the release process to a public space by the end of 2024.

**Comment by afbjorklund** [comment]
This seems like a (rather vague) long-term goal, and you don't need to tag maintainers - until it is actually urgent to do.?Otherwise it just seems like another of those drive-by initiatives...
