### ISSUE TITLE
The container used for tutorial is not compatible with arm64

### ISSUE THREAD

**Issue by tastyminerals** [kubernetes/minikube#17803]
### What Happened?

Following the multi-node tutorial: https://minikube.sigs.k8s.io/docs/tutorials/multi_node/
The `hello-deployment.yaml` cannot be run on arm64 system. After applying the deployment, it goes into a crash loop.

```
pavels@arch-experiments ~> kubectl get pods
NAME                     READY   STATUS             RESTARTS        AGE
hello-7bf57d9696-c82lm   0/1     CrashLoopBackOff   6 (4m31s ago)   10m
hello-7bf57d9696-cdpxh   0/1     CrashLoopBackOff   6 (4m28s ago)   10m
pavels@arch-experiments ~> kubectl logs hello-7bf57d9696-c82lm
exec /hello-from: exec format error
```

```
      containers:
        - name: hello-from
          image: pbitty/hello-from:latest
```
Since I am running minikube on mac with M1, could it be that the `latest` image is not compatible?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13684093/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
That image is 5 years old, so that is very likely. Better to use another image, like from the other tutorial.

`image: kicbase/echo-server`
