### ISSUE TITLE
Rework test to to remove `iso_test.iso`

### ISSUE THREAD

**Issue by acumino** [kubernetes/minikube#17817]
According to OpenSSF standard project should not have generated executable (binary) artifacts in the source repository.

Currently, https://github.com/kubernetes/minikube/blob/master/pkg/drivers/hyperkit/iso_test.iso is used in testing, Is it possible to rework the test?

Part of https://github.com/kubernetes/minikube/issues/17808
#SecuritySlam

**Comment by afbjorklund** [comment]
> According to OpenSSF standard project should not have generated executable (binary) artifacts in the source repository.

An iso file is not executable, anymore than a zip file. In this case it contains some text files (the file is 36 KiB).

```
├── test1.txt
└── test2
    └── test2.txt
```

There is other binary data, that would be more interesting to remove from the repo. But not for security...

* https://github.com/kubernetes/minikube/issues/17295
