### ISSUE TITLE
kube-dns does not start in minikube 0.21 with kuberenetes 1.5.3

### ISSUE THREAD

**Issue by julienbachmann** [kubernetes/minikube#1781]
**BUG REPORT:**

**Minikube version** (use `minikube version`): v0.21.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Macos 10.12.5
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.0.iso
- **Install tools**:
- **Others**:

**What happened**:
When I start minikube with `--kubernetes-version=v1.5.3`, the kube-dns pod is not started.

If I log the the kube-addon-manager (`kubectl --namespace kube-system logs kube-addon-manager-minikube`) I can see the following error:
```
INFO: == Executing apply to spin up new addon resources at 2017-08-04T14:07:07+0000 ==
configmap "kube-dns" created
error validating "/etc/kubernetes/addons/kube-dns-controller.yaml": error validating data: [found invalid field tolerations for v1.PodSpec, found invalid field optional for v1.ConfigMapVolumeSource]; if you choose to ignore these errors, turn validation off with --validate=false
```

**What you expected to happen**:
kube-dns should work even with kuberenetes 1.5.3

**How to reproduce it** (as minimally and precisely as possible):
Just launch minikibe like this:
```
minikube start --vm-driver=xhyve --memory=4096 --kubernetes-version=v1.5.3
```
then list the the kube system pods:
```
kubectl get pod -n kube-system
```
And you will see the kube-dns is not in the list.

**Anything else do we need to know**:

**Comment by r2d4** [comment]
This is a result of the second point I raise in this issue https://github.com/kubernetes/minikube/issues/1768.

For now, you can run your own kube-dns deployment by putting these two manifests https://github.com/kubernetes/minikube/tree/k8s-v1.5/deploy/addons/kube-dns in your `~/.minikube/addons` directory and running `minikube addons disable kube-dns` to disable the default kube-dns addon.

**Comment by julienbachmann** [comment]
👍 thanks for this workaround.

**Comment by bgehman** [comment]
Another issue with running kubernetes v1.5.3 on Minikube v0.21.0 is that if you restart your cluster and forget to specify `--kubernetes-version="v1.5.3"` on the start -- "something" gets upgraded and localkube will no longer start (even if you stop and restart the VM with the correct kubernetes-version setting).
