### ISSUE TITLE
minikube - hello-minikue image pull failure!

### ISSUE THREAD

**Issue by abhishekmv92** [kubernetes/minikube#17820]
### What Happened?

minikube installation page:-
![image](https://github.com/kubernetes/minikube/assets/19928071/f020af6d-ef83-4cba-a360-93594b87e8a6)

I have setup the minikube on my windows laptop. When i try to deploy simple service following the article https://minikube.sigs.k8s.io/docs/start/, i see that it is failing with error as below:-

**Error:- "Failed to pull image "kicbase/echo-server:1.0": Error response from daemon: Head "https://registry-1.docker.io/v2/kicbase/echo-server/manifests/1.0": Get "https://auth.docker.io/token?scope=repository%3Akicbase%2Fecho-server%3Apull&service=registry.docker.io": tls: failed to verify certificate: x509: certificate signed by unknown authority"**

![image](https://github.com/kubernetes/minikube/assets/19928071/41765177-40c0-4d25-bf32-66e6eb69c157)

When i try to install/setup minikube it is also saying like below:-
**! This VM is having trouble accessing https://registry.k8s.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/**

Could you please help me where it is going wrong.

### Attach the log file

Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  54s                default-scheduler  Successfully assigned default/hello-minikube-7f54cff968-bclkm to minikube
  Normal   BackOff    27s (x2 over 51s)  kubelet            Back-off pulling image "kicbase/echo-server:1.0"
  Warning  Failed     27s (x2 over 51s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    13s (x3 over 53s)  kubelet            Pulling image "kicbase/echo-server:1.0"
  Warning  Failed     12s (x3 over 52s)  kubelet            Failed to pull image "kicbase/echo-server:1.0": Error response from daemon: Head "https://registry-1.docker.io/v2/kicbase/echo-server/manifests/1.0": Get "https://auth.docker.io/token?scope=repository%3Akicbase%2Fecho-server%3Apull&service=registry.docker.io": tls: failed to verify certificate: x509: certificate signed by unknown authority
  Warning  Failed     12s (x3 over 52s)  kubelet            Error: ErrImagePull

### Operating System

Windows

### Driver

VirtualBox

**Comment by jhoeljp** [comment]
Hello, 

I had the same issue here and what solved it was creating a `docker context` specifically for minikube.
Follow the steps from this [post](https://github.com/kubernetes/minikube/issues/16788#issuecomment-1708459449) 
Then `kubectl delete deployment hello-minikube` and `kubectl create deployment hello-minikube --image=kicbase/echo-server:1.0` again and it should be pulling the image correctly now 👍
