### ISSUE TITLE
hj

### ISSUE THREAD

**Issue by WessamMohamed22** [kubernetes/minikube#17839]
### What Happened?

service not available: no running pod for service node-port-service found

### Attach the log file

W1220 03:56:01.479032    3944 main.go:291] Unable to resolve the current Docker CLI context "default": context "default": context not found: open C:\Users\dell\.docker\contexts\meta\37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f\meta.json: The system cannot find the path specified.

### Operating System

None

### Driver

None

**Comment by spowelljr** [comment]
It seems like your pods are not running for the service you're specifying, I'd recommend you run `kubectl get pods -A` to list all your pods and see which aren't running. Then you can use commands like `kubectl describe pods` & `kubectl logs` to get more information on why the pod is not running.
