### ISSUE TITLE
Minikube Start Command not working 

### ISSUE THREAD

**Issue by dhaneshdrsingh** [kubernetes/minikube#17843]
### What Happened?

E1220 16:56:39.235727    5038 status.go:376] failed to get storage capacity of /var: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
E1220 16:56:39.235779    5038 status.go:260] status error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
minikube
type: Control Plane
host: Error
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Configured

### Attach the log file

E1220 16:56:39.235727    5038 status.go:376] failed to get storage capacity of /var: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
E1220 16:56:39.235779    5038 status.go:260] status error: NewSession: new client: new client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
minikube
type: Control Plane
host: Error
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Configured

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!
