### ISSUE TITLE
minikube ingress addon can't be enabled

### ISSUE THREAD

**Issue by rubenlara** [kubernetes/minikube#17850]
### What Happened?

I tried to run `minikube addons enable ingress` and got an error message:

`X Terminiere aufgrund von MK_ADDON_ENABLE: enable failed: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: context deadline exceeded]`

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/13752567/logs.txt)
[minikube_addons_72857dffab89b6206069354909629325f2dffeff_0.log](https://github.com/kubernetes/minikube/files/13752574/minikube_addons_72857dffab89b6206069354909629325f2dffeff_0.log)

### Operating System

Windows

### Driver

N/A

**Comment by cirix** [comment]
Hi,
did you check if you have Defender firewall blocking out going calls? I have seen that and it was a problem of the local firewall chopping the outgoing connections and then the service was timing out. 

kr
Nik
