### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by Qwert-oiu** [kubernetes/minikube#17854]
after openning powershell as administrator and coping the path when i write the command minikube start this error happens (Program 'minikube.exe' failed to run: The specified executable is not a valid application for this OS platform.At
line:1 char:1
+ minikube start
+ ~~~~~~~~~~~~~~.
At line:1 char:1
+ minikube start
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
) what is the solution ,please?

**Comment by cirix** [comment]
Hi,
please can you elaborate if the minikube is in your $PATH? The above most likely indicates you don't have it in the path and the binary can't be found. If you explicitly call the executable with the full qualified path?

br
Nik
