### ISSUE TITLE
The default username and password for minikube is not working i.e docker and tcuser.

### ISSUE THREAD

**Issue by ksanjaykumar1** [kubernetes/minikube#17860]
### What Happened?

I am logging in using SSH but it says Permission denied. 

I use Ubuntu and I followed the following page for installation https://minikube.sigs.k8s.io/docs/start/. 

![Screenshot from 2023-12-26 16-49-47](https://github.com/kubernetes/minikube/assets/72605368/6ba77787-1aeb-49e7-aafa-abd798a05508)

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13771086/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by ksanjaykumar1** [comment]
I am currently able to log in using ssh key pair

`ssh -i ~/.minikube/machines/minikube/id_rsa docker@192.168.49.2`

**Comment by spowelljr** [comment]
Hi @ksanjaykumar1, logging in with user and password has been disabled for security reasons, SSH is currently the only way to login.

**Comment by ksanjaykumar1** [comment]
Oh okay, thanks.

**Comment by knQzx** [comment]
> I am currently able to log in using ssh key pair
> 
> `ssh -i ~/.minikube/machines/minikube/id_rsa docker@192.168.49.2`

god bless you ❤️

**Comment by masoud-maghsoudi** [comment]
```
minikube ssh 
```
is the easiest way

**Comment by gccoulter** [comment]
> I am currently able to log in using ssh key pair
> 
> `ssh -i ~/.minikube/machines/minikube/id_rsa docker@192.168.49.2`

I love you
