### ISSUE TITLE
Unclear Documentation on Windows nodes support / example

### ISSUE THREAD

**Issue by mrdalrymple** [kubernetes/minikube#17874]
### What Happened?

I have tried to launch a Windows image (mcr.microsoft.com/windows/servercore:ltsc2019), but see this error:

0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..

On Windows 11, started with: `minikube start --memory=max --cpus=max`

Used this nodeSelector: kubernetes.io/os: windows

I'm assuming this isn't supported yet or it's not documented on how to configure minikube to support both windows and linux nodes in its cluster.

I was struggling to find something on this in the docs; is this a supported scenario or will be supported?  Are there docs already showing how to make this work?

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13800419/log.txt)

### Operating System

Windows

### Driver

Docker

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/2015
