### ISSUE TITLE
Minikube + Containerd driver?

### ISSUE THREAD

**Issue by shinebayar-g** [kubernetes/minikube#17882]
### What Happened?

Hi. Does Minikube support containerd as a standalone driver? It's mentioned as one of the [possible runtimes](https://minikube.sigs.k8s.io/docs/runtimes/), but not [driver](https://minikube.sigs.k8s.io/docs/drivers/).
I was wondering if Minikube could support containerd as a driver alternative for Docker.

### Attach the log file

N/A

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
Minikube supports Docker and Podman, but not containerd. Neither does `kind`, with the same type of arguments:

* https://github.com/kubernetes-sigs/kind/issues/2317

The standard now is running containerd-in-docker, with crio-in-podman as some kind of experimental alternative...

Support cri-dockerd (for runtime) and supporting nerdctl (for driver) is becoming more of a maintenance burden.

**Comment by shinebayar-g** [comment]
Thanks for the answer. Container based options are not looking good.. Podman is experimental and Docker is restricted with license changes. Looks like I should look into other VM based alternatives for the time being.

**Comment by afbjorklund** [comment]
Especially the `minikube docker-env` is hard to support in the long run, even if we have a short term workaround.

There are also more people using Docker Desktop and Podman Desktop, instead of the more open alternatives.
It is possible to use Rancher Desktop for better containerd support, but then the default is to use k3s instead.

**Comment by afbjorklund** [comment]
> Podman is experimental and Docker is restricted with license changes.

Note that there are no license changes for Docker Engine, it is still Open Source. Same goes for Podman Engine.

**Comment by shinebayar-g** [comment]
Yeah but that's only available on Linux OS right?

**Comment by afbjorklund** [comment]
Minikube uses Docker Machine, for the others.

**Comment by shinebayar-g** [comment]
I am confused. What does that mean? How can I use that if I don't have Docker desktop installed on my MacOS for example?

```log
❯ minikube start --driver=docker
😄  [minikube-v1.25] minikube v1.32.0 on Darwin 14.2.1 (arm64)
🆕  Kubernetes 1.28.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.28.3
✨  Using the docker driver based on existing profile

💣  Exiting due to PROVIDER_DOCKER_NOT_RUNNING: "docker version --format <no value>-<no value>:<no value>" exit status 1: Cannot connect to the Docker daemon at unix:///Users/home/.docker/run/docker.sock. Is the docker daemon running?
💡  Suggestion: Start the Docker service
📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/
```

**Comment by afbjorklund** [comment]
As you mention, it is mostly used as the runtime for the Kubernetes cluster. Not as the engine for the node.

But in theory it is possible to run minikube-in-minikube, just that it is not a primary setup (out-of-the-box)
