### ISSUE TITLE
Load balancing tutorial step does not produce expected outcome

### ISSUE THREAD

**Issue by 01binary** [kubernetes/minikube#17886]
### What Happened?

# Summary

The [Load Balancing](https://minikube.sigs.k8s.io/docs/tutorials/kubernetes_101/module5/#step-2---load-balancing) tutorial step asserts that after scaling the application deployment to several pods and exposing the deployment via a service, then tunneling into the service by using `minikube service kubernetes-bootcamp`, the service mechanism in Kubernetes will send the traffic to a random pod each time the browser is refreshed.

I am seeing that only the last pod in the deployment responds, the others never see any traffic.

# Reproduction Steps

I followed these instructions:

- Have a deployment of kubernetes bootcamp container that's running a Node.js application
- The deployment has several pods all marked with "app" tag (`app=kubernetes-bootcamp`)
- The deployment is exposed through a service that should route the traffic to each pod (NodePort)
- I described the service, and it has several endpoints, one for each pod the app is running on
- I made the service accessible via `minikube service kubernetes-bootcamp`

Expected behavior for this tutorial step is refreshing the browser several times, and each time the traffic is routed to a random pod on the service.  You know this because it dumps the machine name.

Actual behavior is I am always hitting the last Endpoint in the service every time.

I am seeing this:

```
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-855d5cc575-wgp2b | v=1
```
...no matter how many times I refresh. The "Running on" name printed corresponds to the last pod in this deployment, and it's always the last pod.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13814867/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by wael-sadek** [comment]
@01binary , Could you try and use curl instead of using the browser ?
