### ISSUE TITLE
Access Minikube from outside server

### ISSUE THREAD

**Issue by entrymon** [kubernetes/minikube#17880]
### What Happened?

I have a remote physical server with public IP.

I installed minikube and started the server with docker

```
minikube start --memory=16384 --cpus=8 --nodes=6 --driver=docker  --force-systemd=true --extra-config kubeadm.ignore-preflight-errors=SystemVerification
```

Then installed istio ingress and load balancer and mysql using helm.

I am able to `kubectl exec -it mysql-primary-0` -- /bin/sh 

I ran minikube tunnel and it shows external IP as `127.0.0.1` 

Then i did IP routing using iptables to route all 3306 traffic on public IP to `127.0.0.1:3306`, 

```
sudo iptables -t nat -A PREROUTING -p tcp -d x.x.x.x  --dport 3306 -j DNAT --to-destination 127.0.0.1:3306
sudo iptables -A FORWARD -p tcp -d 127.0.0.1 --dport 3306 -m state --state NEW,ESTABLISHED,RELATED -j ACCEPT
sudo iptables -t nat -A POSTROUTING -d 127.0.0.1 -p tcp --dport 3306 -j SNAT --to-source x.x.x.x
sudo iptables -t nat -I OUTPUT -p tcp -d x.x.x.x --dport 3306 -j DNAT --to-destination 127.0.0.1:3306
```

this same setup works that i did for port 80 and 443 and it worked but is not working for mysql. 

I have tried to updated istio gateway to accept 3306 traffic and enabled tcp services too. This exact setup was working in previous minikube version few months back and started failing, don't have old version details but current I am on latest version. The only new thing in new setup is IP is 127.0.0.1 while in old used to get LB IP as 192xxx. Also no FW or blocking traffic on port 3306.

Please help.

### Attach the log file

NA

### Operating System

Ubuntu

### Driver

Docker

**Comment by xiozip** [comment]
@entrymon ну как удалось решить задачку?
