### ISSUE TITLE
This container is having trouble accessing https://registry.k8s.io

### ISSUE THREAD

**Issue by mueller-jens** [kubernetes/minikube#17894]
### What Happened?

I try to run minikube in a network, which uses Zscaler. Here I need to use custom certificates.
I added these certificates to the .minikube/certs directory, but I still get the message mentioned in the title.

I can see in the logfiles, that there are still certificate prooblems:
```
W0105 11:18:39.409707  192544 start.go:840] [curl -sS -m 2 https://registry.k8s.io/] failed: curl -sS -m 2 https://registry.k8s.io/: Process exited with status 60
stdout:

stderr:
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
If I try the command after the container is started, the command runs as expected. 
So I took a closer look into the logfiles and see, that the certificates are copied much later:

```
I0105 11:18:52.561160  192544 certs.go:437] found cert: /home/jens/.minikube/certs/home/jens/.minikube/certs/Zscaler.pem (1732 bytes)
I0105 11:18:52.561172  192544 certs.go:437] found cert: /home/jens/.minikube/certs/home/jens/.minikube/certs/ca-key.pem (1675 bytes)
I0105 11:18:52.561180  192544 certs.go:437] found cert: /home/jens/.minikube/certs/home/jens/.minikube/certs/ca.pem (1070 bytes)
I0105 11:18:52.561188  192544 certs.go:437] found cert: /home/jens/.minikube/certs/home/jens/.minikube/certs/cert.pem (1115 bytes)
I0105 11:18:52.561195  192544 certs.go:437] found cert: /home/jens/.minikube/certs/home/jens/.minikube/certs/key.pem (1675 bytes)
```
In my opinion the certificates should be copied, before the cur command is executed?

### Attach the log file

[log.log](https://github.com/kubernetes/minikube/files/13841364/log.log)

### Operating System

Ubuntu

### Driver

Docker

**Comment by mueller-jens** [comment]
Can this also be the reason that `minikube dashbord` runs in a 503  while `verifying` the proxy?

**Comment by SoufianeMoutaouakkil** [comment]
you need just to get the certificate of zscaller and cp it into minikube container and update-ca-certificates. here is the steps to follow:
1- run `minikube start` : will create the container. and eventuelly will show the warning.
2- run `docker cp /path/to/zscaler_cert.crt minikube:/usr/local/share/ca-certificates`: copy the certificates into the minikube container.
3- run `docker container exec -it minikube bash` : access minikube container
4- run `update-ca-certificates`: will add zscaller certificates

and restart the minikube and eventually you will not see the warning
