### ISSUE TITLE
Can't access external ip of kubernetes deploy on docker desktop in macOS

### ISSUE THREAD

**Issue by hoangdangduy** [kubernetes/minikube#17890]
### What Happened?

Hi all,

I am running Minikube on Docker in macOS to install Kubernetes locally. I am facing an issue can't access service Kubernetes by external IP. Service type is NodePort.
![Screenshot 2024-01-04 at 23 11 54](https://github.com/kubernetes/minikube/assets/8912039/6aa7037f-7094-4a94-ae19-cc60791c0598)

Version components I am using
1. kubectl:
```
Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.3
```
2. minikube

```minikube version: v1.32.0```

3. docker

```Docker version 24.0.7, build afdd53b```

I run command ```minikube service web-service```, I can access with http://127.0.0.1:54790 but http://192.168.49.2:31856 is no
![image](https://github.com/kubernetes/minikube/assets/8912039/4e7ec588-2817-4600-a069-ee19748b4607)

How to access http://192.168.49.2:31856 ?
Thanks for any help and reading.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13833608/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
NodePort is not directly accessible, due to network limitations in Docker Desktop

https://docs.docker.com/desktop/networking/#per-container-ip-addressing-is-not-possible
