### ISSUE TITLE
ZSH completion

### ISSUE THREAD

**Issue by vainikkaj** [kubernetes/minikube#1794]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Minikube version** (use `minikube version`):  v0.20.0

**Environment**:
- **OS** (e.g. from /etc/os-release): 16.04.3 LTS (Xenial Xerus)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.20.0.iso
- **Install tools**: ZSH

Cobra now has command hiearchy completion for ZSH in master. See spf13/cobra/pull/497
Even though it is still missing more advanced stuff, basic command compeletion for ZSH would be very useful.

**Comment by r2d4** [comment]
Yup this would be cool.  Even though we use cobra in minikube, we track the version from upstream kubernetes . So we'll have to wait until its updated upstream, so we avoid vendor merge conflicts all the time.

**Comment by msogrin** [comment]
Minikube ZSH completion is already implemented in https://github.com/zchee/go-zsh-completions/blob/master/src/_minikube, but it would have been useful to bring that work into Minikube itself.

**Comment by kenden** [comment]
It's in master, will be in the next release.
Related, easy way to enable the completion: https://github.com/robbyrussell/oh-my-zsh/pull/6436
