### ISSUE TITLE
❌  Unable to load cached images: loading cached images: stat /home/surface2/.minikube/cache/images/amd64/registry.k8s.io/kube-apiserver_v1.28.3: no such file or directory

### ISSUE THREAD

**Issue by PatMan70** [kubernetes/minikube#17947]
### What Happened?

minikube fail running docker desktop as driver on Debain 12

### Attach the log file

  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
🐳  Preparing Kubernetes v1.28.3 on Docker 24.0.7 ...
❌  Unable to load cached images: loading cached images: stat /home/surface2/.minikube/cache/images/amd64/registry.k8s.io/kube-apiserver_v1.28.3: no such file or directory
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.28.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,NumCPU,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.28.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'

stderr:
        [WARNING Swap]: swap is enabled; production deployments should disable swap unless testing the NodeSwap feature gate of the kubelet
        [WARNING SystemVerification]: missing optional cgroups: hugetlb
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image registry.k8s.io/kube-apiserver:v1.28.3: output: E0113 05:48:48.434312    4302 remote_image.go:242] "PullImage from image service failed" err="rpc error: code = Unknown desc = Error response from daemon: Head \"https://australia-southeast1-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-apiserver/manifests/v1.28.3\": dial tcp [2404:6800:4003:c01::52]:443: connect: cannot assign requested address" image="registry.k8s.io/kube-apiserver:v1.28.3"
time="2024-01-13T05:48:48Z" level=fatal msg="pulling image: rpc error: code = Unknown desc = Error response from daemon: Head \"https://australia-southeast1-docker.pkg.dev/v2/k8s-artifacts-prod/images/kube-apiserver/manifests/v1.28.3\": dial tcp [2404:6800:4003:c01::52]:443: connect: cannot assign requested address"
, error: exit status 1
        [ERROR ImagePull]: failed to pu

### Operating System

Other

### Driver

Docker

**Comment by jcubic** [comment]
I have the same error in Ubuntu 22.04

**Comment by par97** [comment]
hit the same issue.
