### ISSUE TITLE
How to replace the kubernetes controller manager container

### ISSUE THREAD

**Issue by hcs129** [kubernetes/minikube#1796]
I'm installing the BTrDB following the instruction in [https://docs.smartgrid.store/prerequisites.html#connecting-kubernetes-to-ceph](url).
For kubeadm

>  edit the file /etc/kubernetes/manifests/kube-controller-manager.json. In that file, change the specified image to btrdb/kubernetes-controller-manager-rbd:1.6.2

However, I cannot find the alternative configure file for minikube. What should I do.
I've read [https://github.com/kubernetes/minikube/pull/529](url), but still have no idea.

**Comment by r2d4** [comment]
You can set options on the controller manager with the `--extra-config=controller-manager.` 

See https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md for more information.
