### ISSUE TITLE
Exiting due to K8S_INSTALL_FAILED

### ISSUE THREAD

**Issue by JeffSG** [kubernetes/minikube#17960]
### What Happened?

Run below command
`minikube start --driver=docker --image-mirror-country=cn --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --alsologtostderr`
Got below error
`Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.20.2/bin/linux/amd64/kubeadm.sha256 Dst:C:\Users\Administrator\.minikube\cache\linux\v1.20.2/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x3b2c050 0x3b2c050 0x3b2c050 0x3b2c050 0x3b2c050 0x3b2c050 0x3b2c050] Decompressors:map[bz2:0x3b2c050 gz:0x3b2c050 tar.bz2:0x3b2c050 tar.gz:0x3b2c050 tar.xz:0x3b2c050 tar.zst:0x3b2c050 tbz2:0x3b2c050 tgz:0x3b2c050 txz:0x3b2c050 tzst:0x3b2c050 xz:0x3b2c050 zip:0x3b2c050 zst:0x3b2c050] Getters:map[file:0xc0007d83e0 http:0xc0004d3ae0 https:0xc0004d3b00] Dir:false ProgressListener:0x3ad7ea0 Options:[0x22f7a60]}: invalid checksum: Error downloading checksum file: bad response code: 404`

### Attach the log file

[lastStart.txt](https://github.com/kubernetes/minikube/files/13938324/lastStart.txt)

### Operating System

Windows

### Driver

Docker

**Comment by liangyuanpeng** [comment]
I think it's need to create a issue to https://github.com/kubernetes/minikube/issues

**Comment by JeffSG** [comment]
> I think it need to create a issue to https://github.com/kubernetes/minikube/issues

Isn't it here?

**Comment by liangyuanpeng** [comment]
@JeffSG Ohh, i put the wrong thing, i mean here https://github.com/AliyunContainerService/minikube/issues

**Comment by pigga** [comment]
看了这么久，好像没发现有解决方案了。阿里的仓库应该是太久了。好久没更新了，最新的 版本为1.23。所以最终的解决方案是啥？ so , what's the really result？
