### ISSUE TITLE
Cant' ssh into node due to docker container inspect took an unusually long time

### ISSUE THREAD

**Issue by Tusenka** [kubernetes/minikube#17961]
### What Happened?

**Steps to reproduce:**
Run:
`minikube ssh -n minikube`
**Expected:**
Ssh into Node
**Actual:** 
`Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 4.65778574s
`
![image](https://github.com/kubernetes/minikube/assets/7852737/274b513e-3e29-42f8-82a2-e28df987f6fa)

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13939013/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by iamprakash89** [comment]
Hello @Tusenka,

Please try the below steps for troubleshooting

**Could you please check the docker service is running fine?**
systemctl status docker.service

**Also verify the docker version which is upto date.**
docker --version

Please **review the doc https://minikube.sigs.k8s.io/docs/drivers/docker/** for more reference.
And provide the output of the above command

**user should have a secondary group** 
:~$ id user
uid=1001(user) gid=1001(user) groups=1001(user),27(sudo),999(docker)

Hope you started the minikube before running to ssh.
