### ISSUE TITLE
system getting hanged 

### ISSUE THREAD

**Issue by Rahuls961** [kubernetes/minikube#17982]
### What Happened?

while running the minikube system getting hanged. i have used VM with 3core CPU and 5GM RAM

### Attach the log file

NA

### Operating System

None

### Driver

None

**Comment by spowelljr** [comment]
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by T-Lakshmi** [comment]
@Rahuls961,
Are you still facing this issue? if yes, please update the logs as requested in [17982 comment](https://github.com/kubernetes/minikube/issues/17982#issuecomment-1901277987).

If it is resolved, please close the issue.
