### ISSUE TITLE
buildImageCmd does not remove temporary tar file

### ISSUE THREAD

**Issue by dr29bart** [kubernetes/minikube#17981]
### What Happened?

minikube version: v1.32.0
commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d

1. `touch Dockerfile dummy.txt`
 Dockerfile:
    ```
    FROM node:18-alpine
    WORKDIR /app
    COPY . .
    RUN yarn install --production
    CMD ["node", "src/index.js"]
    EXPOSE 3000
    ```
2. `TMP=$(pwd) minikube image build -t local_tar:latest . --alsologtostderr --v=2`
3. ls => 
    ```
    Dockerfile  build.983509327.tar  dummy.txt  minikube_image_04803775b4da902d594d6806ceb2f2a7b2472c3c_0.log
    ```

**Expected result:**
 _build.*.tar_ file is removed.

### Attach the log file

[minikube_image_04803775b4da902d594d6806ceb2f2a7b2472c3c_0.log](https://github.com/kubernetes/minikube/files/13969876/minikube_image_04803775b4da902d594d6806ceb2f2a7b2472c3c_0.log)

### Operating System

Windows

### Driver

Hyper-V

**Comment by afbjorklund** [comment]
The return code of `os.Remove` is never checked, apparently there is some DOS path issue here.
