### ISSUE TITLE
Minikube Image Load process is killed without loading docker image

### ISSUE THREAD

**Issue by lucian-cap** [kubernetes/minikube#17983]
### What Happened?

Executing the `minikube image load` command to load a locally built image into the container runtime in the cluster leads to the process being killed. The container is quite large (16.2GB) but if I use the Docker daemon in the minikube cluster via `eval $(minikube docker-env)` and build the images then everything works just fine. 

I am running Windows 11 with WSL2 (Ubuntu 22.04), using Docker Engine installed in WSL, 

Logs included below:
`I0118 07:29:38.907328  113509 out.go:296] Setting OutFile to fd 1 ...

I0118 07:29:38.907697  113509 out.go:348] isatty.IsTerminal(1) = true

I0118 07:29:38.907715  113509 out.go:309] Setting ErrFile to fd 2...

I0118 07:29:38.907727  113509 out.go:348] isatty.IsTerminal(2) = true

I0118 07:29:38.907828  113509 root.go:338] Updating PATH: /home/lucian/.minikube/bin

I0118 07:29:38.910323  113509 config.go:182] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.28.3

I0118 07:29:38.910645  113509 cache.go:107] acquiring lock: {Name:mk9d2423cbb3b42e30b10267c78183a202fa4c2a Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}

I0118 07:29:38.911163  113509 image.go:134] retrieving image: triton-server:latest

I0118 07:29:38.911185  113509 image.go:140] checking repository: index.docker.io/library/triton-server
W0118 07:29:39.317577  113509 image.go:147] remote: HEAD https://index.docker.io/v2/library/triton-server/manifests/latest: unexpected status code 401 Unauthorized (HEAD responses have no body, use GET for details)

I0118 07:29:39.317613  113509 image.go:148] short name: triton-server:latest

I0118 07:29:39.402658  113509 image.go:173] found index.docker.io/library/triton-server:latest locally: &{ref:{Repository:{Registry:{insecure:false registry:index.docker.io} repository:triton-server} tag:latest original:triton-server:latest} opener:0xc0004477a0 tarballImage:<nil> computed:false id:0xc000439260 configFile:<nil> once:{done:0 m:{state:0 sema:0}} err:<nil>}

I0118 07:29:39.402694  113509 cache.go:162] opening:  /home/lucian/.minikube/cache/images/amd64/triton-server_latest

Killed`

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13976593/log.txt)

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
Try saving the image to a file first (`docker save`), there are some issues with creating the tarball with minikube.

* https://github.com/kubernetes/minikube/issues/17785
