### ISSUE TITLE
Can't start static pod

### ISSUE THREAD

**Issue by Tusenka** [kubernetes/minikube#17984]
### What Happened?

**Steps to reproduce:**
ssh into node
`ssh node`
add file to static Pod Dirrectory
Static pos dirrectory is /etc/kubernetes/manifests/
![image](https://github.com/kubernetes/minikube/assets/7852737/d9fbecf8-5354-42d4-8aaf-c3a0fc7a06fa)
``` bash
mkdir -p /etc/kubernetes/manifests/
cat <<EOF >/etc/kubernetes/manifests/static-web.yaml
apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
EOF
```

restart kubelet
`systemctl restart kubelet
`
**Expected:** 
the static pod is runing
`kubectl get pods -A | grep static `

**Actual:**
no pod appears
`kubectl get pods -A | grep static `
![image](https://github.com/kubernetes/minikube/assets/7852737/d0a92604-bd2a-46b6-b8ce-71ef91713902)

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13977274/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Where are you creating the static pod file, on your host machine or inside the docker container?

**Comment by Tusenka** [comment]
o

> Where are you creating the static pod file, on your host machine or inside the docker container?

in the docker container

**Comment by rexeo-asia** [comment]
if anyone comes in the future,
1. docker exec -it minikube bash
2. cd /etc/kubernetes/manifests
3. vi your-static-pod.yml
4. paste and save
5. use crictl ps or exit and k get po
6. your pod will have name like > your-static-pod-minikube
