### ISSUE TITLE
Minikube not start

### ISSUE THREAD

**Issue by bakalgouri** [kubernetes/minikube#17990]
### What Happened?

minikube v1.2.0 on linux (amd64)
⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary.

⚠️  Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the none driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`

🔄  Restarting existing none VM for "minikube" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.20.2 on Docker 23.0.6
💾  Downloading kubeadm v1.20.2
💾  Downloading kubelet v1.20.2

💣  Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.20.2: failed to download: failed to download to temp file: failed to create validator: failed to create validator: failed to download checksum file: received status code 404

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

### Attach the log file

No

### Operating System

Other

### Driver

VMware

**Comment by spowelljr** [comment]
You're using an extremely old verison of minikube, please update the latest version, then run `minikube delete --all --purge` and then try starting minikube again.

**Comment by Ritikaa96** [comment]
Is your issue resolved after updating the minikube version @bakalgouri ?

**Comment by Ritikaa96** [comment]
As stated in minikube [documentation](https://minikube.sigs.k8s.io/docs/) : It Supports the latest Kubernetes release (+6 previous minor versions)
Also your error message clearly shows it has trouble install kubelet
> Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.20.2: failed to download:

**Comment by spowelljr** [comment]
Hi @bakalgouri, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
