### ISSUE TITLE
Configured to use unsecure cipher suites

### ISSUE THREAD

**Issue by murugan007** [kubernetes/minikube#17993]
### What Happened?

Not able to disable less secure cipher suites (des and 3des). Tried  using --tls-cipher-suites in etcd.yaml but that didn't solve the issue.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13988068/log.txt)

### Operating System

Redhat/Fedora

### Driver

Docker

**Comment by spowelljr** [comment]
I'm not too sure what you mean in regard to `tls-cipher-suites`, but your CNI binaries seem to be for a different OS/arch
```
netplugin failed with no error message: fork/exec /opt/cni/bin/bridge: exec format error
```

**Comment by murugan007** [comment]
Concerning "tls-cipher-suites" I have added "     - --tls-cipher-suites=required-cipher-suites" to file etcd.yaml to remove des/3des ciphers and I'm not sure if there is any other method available here.
