### ISSUE TITLE
Add a status command

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#18]
This should determine whether or not the cluster is running correctly.

**Comment by vishh** [comment]
Why is this necessary?

**Comment by dlorenc** [comment]
It's necessary at least for integration testing and possibly as a diagnostic for users. Eventually I'd like to have a test suite that actually calls things like:

minikube start
assert minikube status == Running
minikube stop
assert minikube status == Stopped
minikube delete
assert minikube status == Does Not Exist

etc.

If users get into trouble we can also ask them to attach the output of this command, which might help diagnose issues.

**Comment by vishh** [comment]
SGTM

**Comment by dlorenc** [comment]
Closed by #27
