### ISSUE TITLE
minikube nginx ingress controller installation failed

### ISSUE THREAD

**Issue by iamprakash89** [kubernetes/minikube#18002]
### What Happened?

Hello Team,

I am trying to install the nginx ingress controller on the minikube, however facing the issue. Logs are shared

**Version**
minikube version: v1.32.0
commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d

Distribution is **Ubuntu 22.04**

### Attach the log file

[logfile.txt](https://github.com/kubernetes/minikube/files/13995375/logfile.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by T-Lakshmi** [comment]
/retitle minikube nginx ingress constroller installation failed

**Comment by T-Lakshmi** [comment]
/retitle minikube nginx ingress controller installation failed

**Comment by T-Lakshmi** [comment]
@iamprakash89,
Can you share the steps that you executed for this?
