### ISSUE TITLE
 Unable to run command in terminal minikube service hello-minikube

### ISSUE THREAD

**Issue by lionwealth** [kubernetes/minikube#18022]
### What Happened?

Cannot connect to the Docker daemon at unix:///Users//.docker/run/docker.sock. Is the docker daemon running?

Unable to run command minikube service hello-minikube in terminal.

### Attach the log file

minikube service hello-minikube

### Operating System

macOS (Default)

### Driver

Docker

**Comment by T-Lakshmi** [comment]
@lionwealth,
Can you check docker process is running or not?
**ps -aux | grep docker**
