### ISSUE TITLE
Minikube is not working

### ISSUE THREAD

**Issue by Emkloud** [kubernetes/minikube#18032]
### What Happened?

Finding it difficult to use Minikube on my local computer.

### Attach the log file

        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
W0124 01:22:32.157028    6198 certs.go:524] WARNING: could not validate bounds for certificate apiserver-kubelet-client: the certificate has expired: NotBefore: 2022-12-21 06:52:08 +0000 UTC, NotAfter: 2024-01-19 20:19:24 +0000 UTC
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: x509: certificate has expired or is not yet valid: current time 2024-01-24T01:22:32Z is after 2024-01-19T20:19:24Z
To see the stack trace of this error execute with --v=5 or higher

### Operating System

None

### Driver

None

**Comment by caerulescens** [comment]
@Emkloud What operating system are you running? What driver are you using? Could you provide logs or more information?

**Comment by Emkloud** [comment]
Thank you for the responses. I got the issue resolved.
