### ISSUE TITLE
issue with "minikube service --url

### ISSUE THREAD

**Issue by AbedDX** [kubernetes/minikube#18037]
### What Happened?

my attempts were to fetch the nginx url by using minikube service-myapp.yaml --url
and i using ubuntu 22.04 WLS with docker desktop

### Attach the log file

[minikube_service_193ea190915448a3976ffda9ee1ff636d14907e5_0.log](https://github.com/kubernetes/minikube/files/14041880/minikube_service_193ea190915448a3976ffda9ee1ff636d14907e5_0.log)

### Operating System

Windows

### Driver

Docker

**Comment by T-Lakshmi** [comment]
@AbedDX,
Did you expose pod properly? Can you please share pod and svc yamls that you used here?
Thanks.

**Comment by AbedDX** [comment]
Thank for the help i manage to it working ^^

**Comment by Ritikaa96** [comment]
If the issue is resolved please close it using `/close`
