### ISSUE TITLE
Minikube cluster creation failure on Podman Desktop

### ISSUE THREAD

**Issue by xbabalov** [kubernetes/minikube#18039]
### What Happened?

When trying to create a Minikube cluster in Resources in Podman Desktop, I get a following error even while having a rootful podman machine running.

Steps to reproduce:
1. Install Podman Desktop
2. Install and initialize Podman with rootful machine
3. Install Minikube
4. Try to create a Minikube cluster

Screenshot:
![minikube error on rootful machine](https://github.com/kubernetes/minikube/assets/57829934/b822fe7c-be3a-4efd-b0f4-9afa5cbc5d03)

Error:
Error: Failed to create minikube cluster. E0125 05:58:08.614734 408 cache.go:189] Error downloading kic artifacts: not yet implemented, see issue #8426 ! StartHost failed, but will try again: driver start: start: podman start minikube: exit status 125 stdout: stderr: Error: no container with name or ID "minikube" found: no such container * Failed to start podman container. Running "minikube delete" may fix it: driver start: start: podman start minikube: exit status 125 stdout: stderr: Error: no container with name or ID "minikube" found: no such container X Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: driver start: start: podman start minikube: exit status 125 stdout: stderr: Error: no container with name or ID "minikube" found: no such container * ╭─────────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │ * If the above advice does not help, please let us know: │ │ https://github.com/kubernetes/minikube/issues/new/choose │ │ │ │ * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue. │ │ │ ╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[minikube_logs_12188603c5e9f28dcb94d82bb148706dd9bd0495_0.log](https://github.com/kubernetes/minikube/files/14053201/minikube_logs_12188603c5e9f28dcb94d82bb148706dd9bd0495_0.log)

### Operating System

Windows

### Driver

Podman

**Comment by ismaelhamed** [comment]
Same here

**Comment by wfschneider** [comment]
This was working for me last week but since I restarted my Mac I can no longer start minikube with podman.

**Comment by bobsira** [comment]
<img width="939" alt="podman error " src="https://github.com/kubernetes/minikube/assets/10998352/2d7b8913-2897-432b-9671-596493a600ad">

I am getting the following error when I run this on a windows machine: _Error: Failed to create minikube cluster. * Exiting due to PROVIDER_PODMAN_NOT_FOUND: The 'podman' provider was not found: exec: "podman": executable file not found in %PATH% * Suggestion: Install Podman * Documentation: https://minikube.sigs.k8s.io/docs/drivers/podman/_

However spinning up a cluster from the command line using this command: minikube start --driver=podman --container-runtime=cri-o   is a successful.

**Comment by alexnelsone** [comment]
For anyone who may be coming here that is experiencing this issue on an M series Mac and podman.  Running the following may clear up the issue with `Error: no container with name or ID "minikube" found: no such container`:

1. `minikube delete`
2. `minikube config set rootless true`
3. `minikube start --driver=podman --container-runtime=cri-o`

**Comment by odockal** [comment]
Still seeing the issue as of today.

**Comment by ranefattesingh** [comment]
For me on Fedora 43 this solution worked
`1. minikube delete`
`2. podman machine init`
`3. podman machine start`
`4. minikube config set rootless true`
`5. minikube start --driver=podman --container-runtime=cri-o`
