### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by elvine1982** [kubernetes/minikube#18049]
### What Happened?

* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...\ E0127 11:24:42.640537    8036 main.go:137] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E).
'minikube' failed to start. (Virtual machine ID 8286DFCE-CBB8-42D5-A582-DDD62C8ABBE9)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine ID 8286DFCE-CBB8-42D5-A582-DDD62C8ABBE9)
'minikube' could not initialize memory: Not enough memory resources are available to complete this operation. (0x8007000E). (Virtual machine ID 8286DFCE-CBB8-42D5-A582-DDD62C8ABBE9)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

### Attach the log file

Hi i need help

### Operating System

Windows

### Driver

Docker

**Comment by vacaramin** [comment]
**Increase Host System Memory(Windows)**  or **Reduce VM Memory Allocation(Minikube)**

**Comment by caerulescens** [comment]
Agree with @vacaramin; this should be closed.

**Comment by kundan2707** [comment]
@elvine1982 if resolved please close this.
