### ISSUE TITLE
Web site has broken link `Advanced Kubernetes policy tutorial`

### ISSUE THREAD

**Issue by eriksjolund** [kubernetes/minikube#18047]
### What Happened?

There is a broken link on
https://minikube.sigs.k8s.io/docs/handbook/network_policy/

I did

1. Start web browser Google Chrome
1. Go to https://minikube.sigs.k8s.io/docs/handbook/network_policy/
1. Click the link _Advanced Kubernetes policy tutorial_ (that points to 
   https://projectcalico.docs.tigera.io/security/tutorials/kubernetes-policy-advanced). The
   web browser is then redirected to https://docs.tigera.io/calico/latest/network-policy/tutorials/kubernetes-policy-advanced . The web page shows the text 
   ```
   Page Not Found
   We could not find what you were looking for.
   
   Please contact the owner of the site that linked you to the original URL and let them know their link is 
   broken.
   ```

### Attach the log file

I don't have minikube installed.

### Operating System

macOS (Default)

### Driver

N/A

**Comment by afbjorklund** [comment]
Probably moved here: (i.e. someone renamed their "tutorials" to "get-started/kubernetes-policy")

https://docs.tigera.io/calico/latest/network-policy/get-started/kubernetes-policy/kubernetes-policy-advanced

Just used the Search button
