### ISSUE TITLE
Raspberry Pi MiniKube Start Fail

### ISSUE THREAD

**Issue by uktricky** [kubernetes/minikube#18050]
### What Happened?

Docker already running on Pi with a few containers ...

$ curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 84.3M  100 84.3M    0     0  6740k      0  0:00:12  0:00:12 --:--:-- 6860k
$ sudo install minikube-linux-arm /usr/local/bin/minikube

tricky@PI4-DEV:~ $ minikube start
😄  minikube v1.32.0 on Raspbian 10.13 (arm)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🏃  Updating the running docker "minikube" container ...
❗  The image 'registry.k8s.io/kube-controller-manager:v1.28.3' was not found; unable to add it to cache.
❗  The image 'registry.k8s.io/kube-scheduler:v1.28.3' was not found; unable to add it to cache.
❗  The image 'registry.k8s.io/kube-proxy:v1.28.3' was not found; unable to add it to cache.
❗  The image 'registry.k8s.io/kube-apiserver:v1.28.3' was not found; unable to add it to cache.
🐳  Preparing Kubernetes v1.28.3 on Docker 24.0.7 ...
❌  Unable to load cached images: loading cached images: stat /home/tricky/.minikube/cache/images/arm/registry.k8s.io/kube-proxy_v1.28.3: no such file or directory

❌  Exiting due to K8S_INSTALL_FAILED: Failed to update cluster: updating control plane: downloading binaries: downloading kubelet: download failed: https://dl.k8s.io/release/v1.28.3/bin/linux/arm/kubelet?checksum=file:https://dl.k8s.io/release/v1.28.3/bin/linux/arm/kubelet.sha256: getter: &{Ctx:context.Background Src:https://dl.k8s.io/release/v1.28.3/bin/linux/arm/kubelet?checksum=file:https://dl.k8s.io/release/v1.28.3/bin/linux/arm/kubelet.sha256 Dst:/home/tricky/.minikube/cache/linux/arm/v1.28.3/kubelet.download Pwd: Mode:2 Umask:---------- Detectors:[0x3f5df78 0x3f5df78 0x3f5df78 0x3f5df78 0x3f5df78 0x3f5df78 0x3f5df78] Decompressors:map[bz2:0x540e4d8 gz:0x540e5c0 tar:0x540e530 tar.bz2:0x540e560 tar.gz:0x540e570 tar.xz:0x540e580 tar.zst:0x540e5a0 tbz2:0x540e560 tgz:0x540e570 txz:0x540e580 tzst:0x540e5a0 xz:0x540e5c8 zip:0x540e5d0 zst:0x540e5e0] Getters:map[file:0x7c7d260 http:0x7eff780 https:0x7eff7c0] Dir:false ProgressListener:0x3f45350 Insecure:false DisableSymlinks:false Options:[0xe7b3d0]}: invalid checksum: Error downloading checksum file: bad response code: 404

Raspberry is a Pi4 / 8gb mem with 500gb storage

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14077410/logs.txt)

### Operating System

Other

### Driver

Docker

**Comment by uktricky** [comment]
Guessing this might be down to the fact I am not running 64bit 

docker pull registry.k8s.io/kube-proxy:v1.28.3
v1.28.3: Pulling from kube-proxy
no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by uktricky** [comment]
Guessing this might be down to the fact I am not running 64bit

docker pull registry.k8s.io/kube-proxy:v1.28.3
v1.28.3: Pulling from kube-proxy
no matching manifest for linux/arm/v7 in the manifest list entries

**Comment by summer-boythink** [comment]
@uktricky Is there a good way to solve this?

**Comment by uktricky** [comment]
Only suggestion would be to use a 64 bit version of raspbian and try again - I just decided to spin up an Ubuntu VM instead

**Comment by afbjorklund** [comment]
Kubernetes stopped supporting arm32, with the release of 1.27, after issues with the go toolchain

* https://github.com/kubernetes/kubernetes/issues/115738

**Comment by afbjorklund** [comment]
Note: k3s might still support armv7

**Comment by summer-boythink** [comment]
@afbjorklund  @uktricky   Thank you for your help
