### ISSUE TITLE
Error starting cluster since MacOS 14.3

### ISSUE THREAD

**Issue by adietish** [kubernetes/minikube#18066]
### What Happened?

This startet to fail with the upgrade to MacOS 14.3. In 14.2.1 things worked (using qemu).
The driver doesn't seem to matter. Using qemu fails, too.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14110200/logs.txt)

### Operating System

macOS (Default)

### Driver

Podman

**Comment by caerulescens** [comment]
@adietish 

In the audit, it shows that you have `hyperkit`, and the binary you're using is `arm64`; the `hyperkit` driver is `x86` only, and it probably won't become possible to run `hyperkit` on `arm64`. You won't be able to use `hyperkit` on an Apple Silicon M-series processor. 

* https://github.com/moby/hyperkit/issues/310

---

The `podman` driver is experimental for `macos`, which can be seen [here](https://minikube.sigs.k8s.io/docs/drivers/) in the docs. I haven't used this driver yet, so I don't have any advice for you. 

---

I can confirm `minikube` `v1.32.0` using the `qemu` driver works for `Darwin 13.6.3 arm64` using `socket_vmnet` for the network. I have procrastinated an update to `14.1`, and I will update now and post back on results. 

Here's the steps:
1. Install [qemu](https://formulae.brew.sh/formula/qemu).
2. Install [socket_vmnet](https://formulae.brew.sh/formula/socket_vmnet).
3. You'll want to add `socket_vmnet` to your `$PATH` variable, which is mentioned in the post-install notes for `socket_vmnet`.
4. I think you will need to start the network like mentioned [here](https://minikube.sigs.k8s.io/docs/drivers/qemu/#install-socket_vmnet-via-brewhttpsbrewsh) in the docs.
5. Run `minikube start --driver=qemu2 --network=socket_vmnet`
6. Test `minikube tunnel` in a separate terminal window

**Comment by caerulescens** [comment]
I'm not able to update to `14.1` right now as it's a work computer and the update is held.

**Comment by caerulescens** [comment]
I never got around to this ticket
