### ISSUE TITLE
Minikube certificate expired

### ISSUE THREAD

**Issue by rdimroci** [kubernetes/minikube#18074]
### What Happened?

Minikube certificates have exipired but i need the pods already created. 

Minikube can not be started any more and the logs kubelet.service does not come up.

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14130421/logs.txt)

### Operating System

Redhat/Fedora

### Driver

None

**Comment by kundan2707** [comment]
AFAIK after certificate expiry you need to delete your minikube cluster that will only work.

**Comment by rdimroci** [comment]
Thank you Kumar, but i was trying to aviod that, as i have pods with configuration inside that will take a long time to reconfigure.
