### ISSUE TITLE
Unable  to start minikube with driver vmware or Install vmrun

### ISSUE THREAD

**Issue by ntatpj** [kubernetes/minikube#18088]
### What Happened?

PS C:\WINDOWS\system32> minikube start --driver vmware
* minikube v1.32.0 on Microsoft Windows 11 Home Single Language 10.0.22621.3007 Build 22621.3007
* Using the vmware driver based on user configuration

* Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in %PATH%
* Suggestion: Install vmrun
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

PS C:\WINDOWS\system32>  Install vmrun
Install : The term 'Install' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+  Install vmrun
+  ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>

### Attach the log file

PS C:\WINDOWS\system32> minikube start --driver vmware
* minikube v1.32.0 on Microsoft Windows 11 Home Single Language 10.0.22621.3007 Build 22621.3007
* Using the vmware driver based on user configuration

* Exiting due to PROVIDER_VMWARE_NOT_FOUND: The 'vmware' provider was not found: exec: "vmrun": executable file not found in %PATH%
* Suggestion: Install vmrun
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

PS C:\WINDOWS\system32>  Install vmrun
Install : The term 'Install' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+  Install vmrun
+  ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

PS C:\WINDOWS\system32>

### Operating System

Windows

### Driver

VMware

**Comment by drumdarway** [comment]
The vmrun.exe should be under C:\Program Files (x86)\VMware\VMware Workstation but setting up VMWare Workstation does not automatically add it to your system envrionment variable path.  Please add it to the system environment varialbe "path" and open a new terminal and run vmrun to see if added successfully.   Then try "minikube start --driver vmware" again.

**Comment by ntatpj** [comment]
The issue was that my laptop configured in windows.  Some windows OS ver do not support vmware or hyperv as hypervisor. I installed Docker and used docker as a hypervisor, this worked for me.
