### ISSUE TITLE
Nonspecific error message when trying to create a namespace with an already-existing name

### ISSUE THREAD

**Issue by ceridwen** [kubernetes/minikube#1808]
FEATURE REQUEST

**Minikube version** (use `minikube version`):

minikube version: v0.21.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac OS X 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.0.iso or testing
- **Install tools**: Installed with Homebrew.

**What happened**:
I'm using the Python client to create resources.  When I try to create a namespace when one already exists with the same name, using the following JSON:

```
{'body': {'apiVersion': 'v1',
          'kind': 'Namespace',
          'metadata': {'generateName': 'test-',
                       'labels': {'test': 'test'},
                       'name': 'test-0'}}}
```

I get a generic error message rather than a specific message saying the name already exists.

```
E           HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Wed, 09 Aug 2017 22:42:04 GMT', 'Content-Length': '301'})
E           HTTP response body: {
E             "kind": "Status",
E             "apiVersion": "v1",
E             "metadata": {},
E             "status": "Failure",
E             "message": "The POST operation against Namespace could not be completed at this time, please try again.",
E             "reason": "ServerTimeout",
E             "details": {
E               "name": "POST",
E               "kind": "Namespace"
E             },
E             "code": 500
```

**Anything else do we need to know**:

Tell me if this is an upstream problem.

**Comment by r2d4** [comment]
We're just running vanilla k8s - you might want to try to file an issue https://github.com/kubernetes-incubator/client-python or upstream.
