### ISSUE TITLE
Exiting due to SVC_UNREACHABLE: service not available: no running pod for service webapp-service found

### ISSUE THREAD

**Issue by ShubhamKakad3** [kubernetes/minikube#18081]
### What Happened?

i'm trying to run and this error is showing
Exiting due to SVC_UNREACHABLE: service not available: no running pod for service webapp-service found

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14136569/logs.txt)

### Operating System

None

### Driver

None

**Comment by kundan2707** [comment]
@ShubhamKakad3 have you checked if all controllers are working or not ?

**Comment by ShubhamKakad3** [comment]
thank you
