### ISSUE TITLE
Support multiple parallel versions?

### ISSUE THREAD

**Issue by deitch** [kubernetes/minikube#1809]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

**Minikube version** (use `minikube version`):
0.21.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
macOS 10.12.6

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
xhyve

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
0.23.0 (according to `config.json`; the `ssh` gives `TESTING`)

- **Install tools**:
brew

- **Others**:
If you run a higher version of k8s and then try to run a lower, it tries to run them locally and `localkube` fails to start with a `cluster cannot be downgraded` error. 

It would be useful if we could run multiple versions as independent VMs. Running `--kubernetes-version 1.7.0` would start an independent VM with its own version (i.e. fully immutable). I could run `1.6.4` as well without downgrade issues, or possibly even in parallel.

**Anything else do we need to know**:
Feature request.

**Comment by aaron-prindle** [comment]
This should be possible currently with the use of minikube profiles.  You should be able to start two independent versions of minikube using two different profiles:
minikube start --profile=v1.6.4 --kubernetes-version=v1.6.4
minikube start --profile=1.7.0 # default version right now is v1.7.0

**Comment by deitch** [comment]
Ah! Very nice. Can I save the profiles somehow for easier future usage? And can they run in parallel?
