### ISSUE TITLE
I'm encountering difficulties while attempting to integrate Jenkins with Minikube.

### ISSUE THREAD

**Issue by suryakalyan403** [kubernetes/minikube#18110]
### What Happened?

I recently installed Jenkins on a RedHat server and also set up Minikube on the same VM. However, when attempting to integrate Jenkins with Minikube, I encountered an issue. The specific error message is [insert error message]. Could someone please provide guidance or assistance on how to resolve this issue?
![jenkins-minikube-integration-issue](https://github.com/kubernetes/minikube/assets/99590270/ef817b5b-dfea-4a94-b6a3-92ed4b12f411)
Version Info
=========
Jenkins    : 2.426.3
Minikube : v1.32.0
 
Thanks in Advance 

### Attach the log file

-- Logs begin at Tue 2024-01-16 01:57:36 EST. --
Feb 06 08:37:10 raku-dev-env jenkins[992649]: 2024-02-06 13:37:10.698+0000 [id=7300]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: Found invalid crumb 8e9ad6dd41cabd004270138d2bac04fe08708def500a7bfa9cdc30021318d979. If you are calling this URL with a script, please use the API Token instead. More information: https://www.jenkins.io/redirect/crumb-cannot-be-used-for-script
Feb 06 08:37:10 raku-dev-env jenkins[992649]: 2024-02-06 13:37:10.698+0000 [id=7300]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: No valid crumb was included in request for /manage/descriptorByName/org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud/fillCredentialsIdItems by admin. Returning 403.
Feb 06 08:37:10 raku-dev-env jenkins[992649]: 2024-02-06 13:37:10.698+0000 [id=6862]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: Found invalid crumb 8e9ad6dd41cabd004270138d2bac04fe08708def500a7bfa9cdc30021318d979. If you are calling this URL with a script, please use the API Token instead. More information: https://www.jenkins.io/redirect/crumb-cannot-be-used-for-script
Feb 06 08:37:10 raku-dev-env jenkins[992649]: 2024-02-06 13:37:10.698+0000 [id=6862]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: No valid crumb was included in request for /manage/descriptorByName/org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud/fillCredentialsIdItems by admin. Returning 403.
Feb 06 08:37:14 raku-dev-env jenkins[992649]: 2024-02-06 13:37:14.205+0000 [id=6862]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: Found invalid crumb 8e9ad6dd41cabd004270138d2bac04fe08708def500a7bfa9cdc30021318d979. If you are calling this URL with a script, please use the API Token instead. More information: https://www.jenkins.io/redirect/crumb-cannot-be-used-for-script
Feb 06 08:37:14 raku-dev-env jenkins[992649]: 2024-02-06 13:37:14.205+0000 [id=6862]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: No valid crumb was included in request for /$stapler/bound/d4da48b6-2ea9-4c7a-9169-07c93c71cfd0/render by admin. Returning 403.
Feb 06 08:37:21 raku-dev-env jenkins[992649]: 2024-02-06 13:37:21.363+0000 [id=7301]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: Found invalid crumb 8e9ad6dd41cabd004270138d2bac04fe08708def500a7bfa9cdc30021318d979. If you are calling this URL with a script, please use the API Token instead. More information: https://www.jenkins.io/redirect/crumb-cannot-be-used-for-script
Feb 06 08:37:21 raku-dev-env jenkins[992649]: 2024-02-06 13:37:21.363+0000 [id=7301]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: No valid crumb was included in request for /$stapler/bound/8f6760b3-d09f-4a33-b40f-6cc61a79ca23/render by admin. Returning 403.
Feb 06 08:37:23 raku-dev-env jenkins[992649]: 2024-02-06 13:37:23.107+0000 [id=6862]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: Found invalid crumb 8e9ad6dd41cabd004270138d2bac04fe08708def500a7bfa9cdc30021318d979. If you are calling this URL with a script, please use the API Token instead. More information: https://www.jenkins.io/redirect/crumb-cannot-be-used-for-script
Feb 06 08:37:23 raku-dev-env jenkins[992649]: 2024-02-06 13:37:23.108+0000 [id=6862]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: No valid crumb was included in request for /descriptor/com.cloudbees.plugins.credentials.CredentialsSelectHelper/resolver/com.cloudbees.plugins.credentials.CredentialsSelectHelper$SystemContextResolver/provider/com.cloudbees.plugins.credentials.SystemCredentialsProvider$ProviderImpl/context/jenkins/addCredentials by admin. Returning 403.

Feb 06 10:18:36 raku-dev-env jenkins[992649]: 2024-02-06 15:18:36.270+0000 [id=7750]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: Found invalid crumb 461b4fccc3b6bfa0ac1387b564bd8d9c4af37cd3cb3fe8d27c337d82c29521a5. If you are calling this URL with a script, please use the API Token instead. More information: https://www.jenkins.io/redirect/crumb-cannot-be-used-for-script
Feb 06 10:18:36 raku-dev-env jenkins[992649]: 2024-02-06 15:18:36.270+0000 [id=7750]        WARNING        hudson.security.csrf.CrumbFilter#doFilter: No valid crumb was included in request for /manage/descriptorByName/org.csanchez.jenkins.plugins.kubernetes.KubernetesCloud/testConnection by admin. Returning 403.

### Operating System

Redhat/Fedora

### Driver

VirtualBox

**Comment by angyaljanos** [comment]
Hey @suryakalyan403,

As the error say there is a space in the url after the word "jenkins", could it be that you added that in the input field?
It doesnt seems like a Minikube problem to me, rather than a Jenkins configuration one.
