### ISSUE TITLE
driver "qemu" is not supported

### ISSUE THREAD

**Issue by arseniy-gl** [kubernetes/minikube#18126]
### What Happened?

minikube config set driver qemu --alsologtostderr
I0208 09:40:18.608659    1261 out.go:296] Setting OutFile to fd 1 ...
I0208 09:40:18.609371    1261 out.go:348] isatty.IsTerminal(1) = true
I0208 09:40:18.609380    1261 out.go:309] Setting ErrFile to fd 2...
I0208 09:40:18.609389    1261 out.go:348] isatty.IsTerminal(2) = true
I0208 09:40:18.609694    1261 root.go:338] Updating PATH: /Users/ars/.minikube/bin
W0208 09:40:18.610536    1261 root.go:314] Error reading config file at /Users/ars/.minikube/config/config.json: open /Users/ars/.minikube/config/config.json: no such file or directory
I0208 09:40:18.633139    1261 out.go:177] 

W0208 09:40:18.652965    1261 out.go:239] ❌  Exiting due to MK_CONFIG_SET: Set failed: run validations for "driver" with value of "qemu": [driver "qemu" is not supported]
❌  Exiting due to MK_CONFIG_SET: Set failed: run validations for "driver" with value of "qemu": [driver "qemu" is not supported]
W0208 09:40:18.652988    1261 out.go:239] 

W0208 09:40:18.655825    1261 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                         │
│    😿  If the above advice does not help, please let us know:                                                           │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                         │
│                                                                                                                         │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                  │
│    Please also attach the following file to the GitHub issue:                                                           │
│    - /var/folders/86/lqrns2y91g508rrl7mnyq0tc0000gn/T/minikube_config_4813fc251ece7ee6990cf80c6b54fea4a44a2050_0.log    │
│                                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                         │
│    😿  If the above advice does not help, please let us know:                                                           │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                         │
│                                                                                                                         │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                  │
│    Please also attach the following file to the GitHub issue:                                                           │
│    - /var/folders/86/lqrns2y91g508rrl7mnyq0tc0000gn/T/minikube_config_4813fc251ece7ee6990cf80c6b54fea4a44a2050_0.log    │
│                                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
I0208 09:40:18.675746    1261 out.go:177] 

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14205149/logs.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by afbjorklund** [comment]
You can try with "qemu2"
