### ISSUE TITLE
Upgrade Kubernetes versions

### ISSUE THREAD

**Issue by webwurst** [kubernetes/minikube#1812]
Kubernetes `v1.7` is three patch levels behind and `v1.6` four. There is a bugfix around providing metrics on `v1.7.3` I personally would like to try. Saw there is already https://github.com/kubernetes/minikube/pull/1784 for this, but hanging around for some days. :slightly_smiling_face:

**Comment by r2d4** [comment]
It should be up now with `minikube start --kubernetes-version 1.7.3`.  

1.7.2 is now also available

**Comment by dharmeshkakadia** [comment]
For anyone coming from google, you want `minikube start --kubernetes-version v1.7.3`
