### ISSUE TITLE
I0212 16:23:22.184446   16031 kubeconfig.go:135] verify returned: extract IP: read: could not read config: Error decoding config from data:  : Object 'Kind' is missing in ' ' I0212 16:23:22.189387   16031 out.go:177]  W0212 16:23:22.194554   16031 out.go:239] ❌  Exiting due to HOST_KUBECONFIG_UPDATE: update config: read: could not read config: Error decoding config from data:  : Object 'Kind' is missing in '

### ISSUE THREAD

**Issue by rosilva2018** [kubernetes/minikube#18157]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

</details>

**A saída do comando `minikube logs`**:<details>

</details>

**A versão do sistema operacional usado**:

**Comment by T-Lakshmi** [comment]
Hi @rosilva2018,
Could you please change the description to primary language(english), that will helpful for community members to understand about  the issue you are facing.
