### ISSUE TITLE
Unable to run MiniKube in Windows System

### ISSUE THREAD

**Issue by connectamitgupta** [kubernetes/minikube#18176]
### What Happened?

Minikube is already installed in my windows 11 system which is configured with docker. While trying to create cluster using **"minikube start"** command, it throws error..."❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: can't create with that IP, address already in use"

I searched through internet and found few workaround....as applied this command also "~/docker/config.json" and "minikube delete --profile=minikube", but still it is not solving the issue. Even i have tried reinstalling minikube in my machine. Please help me to resolve this issue.

### Attach the log file

:\Users\Dell> minikube start
😄  minikube v1.32.0 on Microsoft Windows 11 Pro 10.0.22621.3155 Build 22621.3155
✨  Automatically selected the docker driver
📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...

❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: can't create with that IP, address already in use

### Operating System

Windows

### Driver

Docker

**Comment by 12rashic** [comment]
Try with these 3 commands
<kbd>docker container prune </kbd>
<kbd>minikube delete  </kbd>

**Comment by connectamitgupta** [comment]
Thanks Rashi for your response. As i mentioned in my initial post that i have applied these tricks but not solved. it is still showing message.
**❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: can't create with that IP, address already in use**
