### ISSUE TITLE
Unable to start minikube with Parallels v.19. boot2docker distribution was removed from prlctl

### ISSUE THREAD

**Issue by AlexanderSkogorev** [kubernetes/minikube#18196]
### What Happened?

I was trying to start the minikube with parallels. It was not able to create the VM.

- MacOS Sonoma v.14.2.1 (23C71) (Intel processor)
- Parallels v.19
- prlctl v. 19.2.1 (54832)
- minikube v1.32.0

The command I was trying to run:

> minikube start --driver=parallels --container-runtime=containerd 

or

> minikube start --driver=parallels

Here is the main part of the logs:
> I0215 23:53:41.658451   70326 main.go:141] libmachine: executing: /usr/local/bin/prlctl --version
**> I0215 23:53:41.806603   70326 main.go:141] libmachine: executing: /usr/local/bin/prlctl create minikube --distribution boot2docker --dst /Users/username/.minikube/machines/minikube --no-hdd**
> I0215 23:53:41.942440   70326 client.go:171] LocalClient.Create took 1.303943536s
> I0215 23:53:43.943753   70326 start.go:128] duration metric: createHost completed in 3.326459651s
> I0215 23:53:43.943782   70326 start.go:83] releasing machines lock for "minikube", held for 3.326579339s
> W0215 23:53:43.943832   70326 start.go:691] error starting host: creating host: create: creating: exit status 255

So the minikube could not create the VM, but didn't stop the process.

Here is the output for the command from the logs:

> /usr/local/bin/prlctl create minikube --distribution boot2docker --dst /Users/mylocaluser/.minikube/machines/minikube --no-hdd
> **An incorrect value for --distribution is specified: boot2docker**
> The following values are allowed:
> win-311         	win-95          	win-98          	win-me
> win-nt          	win-2000        	win-xp          	win-2003
> win-vista       	win-2008        	win-7           	win-8
> win-2012        	win-8.1         	win-10          	win-2016
> win-2019        	win-2022        	win-11          	win
> rhel            	rhel7           	suse            	debian
> fedora-core     	fc              	xandros         	ubuntu
> elementary      	mandriva        	mandrake        	centos
> centos7         	psbm            	redhat          	opensuse
> linux-2.4       	linux-2.6       	linux           	mageia
> mint            	kali            	manjaro         	zorin
> macosx          	tiger           	macos-10.4      	leopard
> macos-10.5      	snowleopard     	macos-10.6      	freebsd
> freebsd-4       	freebsd-5       	freebsd-6       	freebsd-7
> freebsd-8       	freebsd         	chrome-1        	chrome
> msdos-6.22      	msdos           	os2-3           	os2-4
> os2-45          	ecomstation-1.1 	ecomstation-1.2 	os2
> netware-4       	netware-5       	netware-6       	netware
> solaris-9       	solaris-10      	solaris-11      	opensolaris
> solaris         	qnx             	openstep        	other

So, the issue occurs because the parallels command line tool (prlctl) does not support the boot2docker distribution.

I had to downgrade my Parallels Desktop to v.18 and it runs fine with it.

### Attach the log file

minikube logs

==> Audit <==
|---------|--------------------------------|----------|-------------------|---------|---------------------|---------------------|
| Command |              Args              | Profile  |       User        | Version |     Start Time      |      End Time       |
|---------|--------------------------------|----------|-------------------|---------|---------------------|---------------------|
| start   | --driver=parallels             | minikube | mylocaluser | v1.32.0 | 15 Feb 24 23:41 +07 |                     |
|         | --container-runtime=containerd |          |                   |         |                     |                     |
| delete  | --all                          | minikube | mylocaluser | v1.32.0 | 15 Feb 24 23:45 +07 | 15 Feb 24 23:45 +07 |
| start   | --driver=parallels             | minikube | root              | v1.32.0 | 15 Feb 24 23:46 +07 |                     |
|         | --container-runtime=containerd |          |                   |         |                     |                     |
| start   | --driver=parallels             | minikube | mylocaluser | v1.32.0 | 15 Feb 24 23:47 +07 |                     |
|         | --container-runtime=containerd |          |                   |         |                     |                     |
| start   | --driver=parallels             | minikube | mylocaluser | v1.32.0 | 15 Feb 24 23:48 +07 |                     |
|         | --container-runtime=containerd |          |                   |         |                     |                     |
| config  | set driver parallels           | minikube | mylocaluser | v1.32.0 | 15 Feb 24 23:52 +07 | 15 Feb 24 23:52 +07 |
| delete  | --all                          | minikube | mylocaluser | v1.32.0 | 15 Feb 24 23:52 +07 | 15 Feb 24 23:52 +07 |
| config  | set driver parallels           | minikube | mylocaluser | v1.32.0 | 15 Feb 24 23:52 +07 | 15 Feb 24 23:52 +07 |
| start   | --driver=parallels             | minikube | mylocaluser | v1.32.0 | 15 Feb 24 23:53 +07 |                     |
|         | --container-runtime=containerd |          |                   |         |                     |                     |
|---------|--------------------------------|----------|-------------------|---------|---------------------|---------------------|

==> Last Start <==
Log file created at: 2024/02/15 23:53:40
Running on machine: MacBook-Pro-mylocaluser
Binary: Built with gc go1.21.3 for darwin/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0215 23:53:40.402889   70326 out.go:296] Setting OutFile to fd 1 ...
I0215 23:53:40.403181   70326 out.go:348] isatty.IsTerminal(1) = true
I0215 23:53:40.403184   70326 out.go:309] Setting ErrFile to fd 2...
I0215 23:53:40.403189   70326 out.go:348] isatty.IsTerminal(2) = true
I0215 23:53:40.403379   70326 root.go:338] Updating PATH: /Users/mylocaluser/.minikube/bin
I0215 23:53:40.405333   70326 out.go:303] Setting JSON to false
I0215 23:53:40.440778   70326 start.go:128] hostinfo: {"hostname":"MacBook-Pro-Aleksandr-S.local","uptime":270174,"bootTime":1707745846,"procs":713,"os":"darwin","platform":"darwin","platformFamily":"Standalone Workstation","platformVersion":"14.2.1","kernelVersion":"23.2.0","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"2481da58-9501-586e-9e5e-3708990a0253"}
W0215 23:53:40.440892   70326 start.go:136] gopshost.Virtualization returned error: not implemented yet
I0215 23:53:40.462790   70326 out.go:177] 😄  minikube v1.32.0 on Darwin 14.2.1
I0215 23:53:40.505807   70326 notify.go:220] Checking for updates...
I0215 23:53:40.506432   70326 driver.go:378] Setting default libvirt URI to qemu:///system
I0215 23:53:40.528152   70326 out.go:177] ✨  Using the parallels driver based on user configuration
I0215 23:53:40.569812   70326 start.go:298] selected driver: parallels
I0215 23:53:40.569848   70326 start.go:902] validating driver "parallels" against <nil>
I0215 23:53:40.569911   70326 start.go:913] status for parallels: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0215 23:53:40.570334   70326 start_flags.go:309] no existing cluster config was found, will generate one from the flags
I0215 23:53:40.574308   70326 start_flags.go:394] Using suggested 6000MB memory alloc based on sys=65536MB, container=0MB
I0215 23:53:40.574494   70326 start_flags.go:913] Wait components to verify : map[apiserver:true system_pods:true]
I0215 23:53:40.574520   70326 cni.go:84] Creating CNI manager for ""
I0215 23:53:40.574528   70326 cni.go:146] "parallels" driver + "containerd" runtime found, recommending bridge
I0215 23:53:40.574539   70326 start_flags.go:318] Found "bridge CNI" CNI - setting NetworkPlugin=cni
I0215 23:53:40.574544   70326 start_flags.go:323] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.42@sha256:d35ac07dfda971cabee05e0deca8aeac772f885a5348e1a0c0b0a36db20fcfc0 Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:parallels HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.28.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:containerd CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/Users:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP: SSHAuthSock: SSHAgentPID:0 AutoPauseInterval:1m0s GPUs:}
I0215 23:53:40.574715   70326 iso.go:125] acquiring lock: {Name:mkccf8b8c3a289b45fd19d9cb40fdb370997e678 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0215 23:53:40.595317   70326 out.go:177] 👍  Starting control plane node minikube in cluster minikube
I0215 23:53:40.616229   70326 preload.go:132] Checking if preload exists for k8s version v1.28.3 and runtime containerd
I0215 23:53:40.616271   70326 preload.go:148] Found local preload: /Users/mylocaluser/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.28.3-containerd-overlay2-amd64.tar.lz4
I0215 23:53:40.616286   70326 cache.go:56] Caching tarball of preloaded images
I0215 23:53:40.616420   70326 preload.go:174] Found /Users/mylocaluser/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v18-v1.28.3-containerd-overlay2-amd64.tar.lz4 in cache, skipping download
I0215 23:53:40.616432   70326 cache.go:59] Finished verifying existence of preloaded tar for  v1.28.3 on containerd
I0215 23:53:40.616747   70326 profile.go:148] Saving config to /Users/mylocaluser/.minikube/profiles/minikube/config.json ...
I0215 23:53:40.616766   70326 lock.go:35] WriteFile acquiring /Users/mylocaluser/.minikube/profiles/minikube/config.json: {Name:mk49ba550a4613e2e67aba88b603323362a1f45f Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0215 23:53:40.617054   70326 start.go:365] acquiring machines lock for minikube: {Name:mk3ea1ebbcb0bce103e81d8474d722a5a94b57e1 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0215 23:53:40.617122   70326 start.go:369] acquired machines lock for "minikube" in 57.174µs
I0215 23:53:40.617138   70326 start.go:93] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.32.1-amd64.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.42@sha256:d35ac07dfda971cabee05e0deca8aeac772f885a5348e1a0c0b0a36db20fcfc0 Memory:6000 CPUs:2 DiskSize:20000 VMDriver: Driver:parallels HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.28.3 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:containerd CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.28.3 ContainerRuntime:containerd ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/Users:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP: SSHAuthSock: SSHAgentPID:0 AutoPauseInterval:1m0s GPUs:} &{Name: IP: Port:8443 KubernetesVersion:v1.28.3 ContainerRuntime:containerd ControlPlane:true Worker:true}
I0215 23:53:40.617183   70326 start.go:125] createHost starting for "" (driver="parallels")
I0215 23:53:40.638247   70326 out.go:204] 🔥  Creating parallels VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
I0215 23:53:40.638413   70326 start.go:159] libmachine.API.Create for "minikube" (driver="parallels")
I0215 23:53:40.638454   70326 client.go:168] LocalClient.Create starting
I0215 23:53:40.638559   70326 main.go:141] libmachine: Reading certificate data from /Users/mylocaluser/.minikube/certs/ca.pem
I0215 23:53:40.638615   70326 main.go:141] libmachine: Decoding PEM data...
I0215 23:53:40.638639   70326 main.go:141] libmachine: Parsing certificate...
I0215 23:53:40.638721   70326 main.go:141] libmachine: Reading certificate data from /Users/mylocaluser/.minikube/certs/cert.pem
I0215 23:53:40.638768   70326 main.go:141] libmachine: Decoding PEM data...
I0215 23:53:40.638776   70326 main.go:141] libmachine: Parsing certificate...
I0215 23:53:40.638798   70326 main.go:141] libmachine: executing: /usr/local/bin/prlctl --version
I0215 23:53:40.791059   70326 main.go:141] libmachine: executing: /usr/local/bin/prlsrvctl info --license
I0215 23:53:40.965386   70326 main.go:141] libmachine: Found Parallels Desktop version: &{%!!(MISSING)d(string=) %!!(MISSING)d(string=) [19 2 1] 3 %!!(MISSING)d(string=19.2.1)}, edition: pro
I0215 23:53:40.965437   70326 main.go:141] libmachine: executing: /usr/local/bin/prlsrvctl net info Shared
I0215 23:53:41.206654   70326 main.go:141] libmachine: IP address of Shared network adapter: 10.211.55.2
I0215 23:53:41.206887   70326 main.go:141] libmachine: All host interface addressess: [127.0.0.1/8 ::1/128 fe80::1/64 fe80::aede:48ff:fe00:1122/64 fe80::1c1d:7d78:e094:4a8a/64 2405:9800:b970:99a6:1ccc:9d21:285d:bc1d/64 2405:9800:b970:99a6:5904:4717:dce3:902d/64 192.168.1.200/24 fe80::f044:98ff:fef9:e903/64 fe80::f044:98ff:fef9:e903/64 fe80::ae22:f05d:f735:aefe/64 fe80::fa09:7461:e1b:f2d9/64 fe80::f8e3:e80:3a7c:548a/64 fe80::ce81:b1c:bd2c:69e/64 10.211.55.2/24 fe80::3c22:fbff:feb9:6f64/64 fdb2:2c26:f4e4::1/64 10.37.129.2/24 fe80::3c22:fbff:feb9:6f65/64 fdb2:2c26:f4e4:1::1/64]
I0215 23:53:41.206921   70326 main.go:141] libmachine: Parallels Shared network adapter is connected
I0215 23:53:41.207611   70326 main.go:141] libmachine: Downloading /Users/mylocaluser/.minikube/cache/boot2docker.iso from file:///Users/mylocaluser/.minikube/cache/iso/amd64/minikube-v1.32.1-amd64.iso...
I0215 23:53:41.395144   70326 main.go:141] libmachine: Creating SSH key...
I0215 23:53:41.395184   70326 main.go:141] libmachine: SSH key: /Users/mylocaluser/.minikube/machines/minikube/id_rsa
I0215 23:53:41.658435   70326 main.go:141] libmachine: Creating Parallels Desktop VM...
I0215 23:53:41.658451   70326 main.go:141] libmachine: executing: /usr/local/bin/prlctl --version
I0215 23:53:41.806603   70326 main.go:141] libmachine: executing: /usr/local/bin/prlctl create minikube --distribution boot2docker --dst /Users/mylocaluser/.minikube/machines/minikube --no-hdd
I0215 23:53:41.942440   70326 client.go:171] LocalClient.Create took 1.303943536s
I0215 23:53:43.943753   70326 start.go:128] duration metric: createHost completed in 3.326459651s
I0215 23:53:43.943782   70326 start.go:83] releasing machines lock for "minikube", held for 3.326579339s
W0215 23:53:43.943832   70326 start.go:691] error starting host: creating host: create: creating: exit status 255
I0215 23:53:43.944847   70326 main.go:141] libmachine: executing: /usr/local/bin/prlctl list minikube --output status --no-header
I0215 23:53:44.121498   70326 delete.go:82] Unable to get host status for minikube, assuming it has already been deleted: state: machine does not exist
W0215 23:53:44.121598   70326 out.go:239] 🤦  StartHost failed, but will try again: creating host: create: creating: exit status 255
I0215 23:53:44.121618   70326 start.go:706] Will try again in 5 seconds ...
I0215 23:53:49.122994   70326 start.go:365] acquiring machines lock for minikube: {Name:mk3ea1ebbcb0bce103e81d8474d722a5a94b57e1 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0215 23:53:49.123261   70326 start.go:369] acquired machines lock for "minikube" in 226.756µs
I0215 23:53:49.123308   70326 start.go:96] Skipping create...Using existing machine configuration
I0215 23:53:49.123327   70326 fix.go:54] fixHost starting:
I0215 23:53:49.123777   70326 main.go:141] libmachine: executing: /usr/local/bin/prlctl list minikube --output status --no-header
I0215 23:53:49.297583   70326 fix.go:102] recreateIfNeeded on minikube: state=Error err=machine does not exist
I0215 23:53:49.297641   70326 fix.go:107] machineExists: true. err=machine does not exist
W0215 23:53:49.297665   70326 fix.go:128] unexpected machine state, will restart: machine does not exist
I0215 23:53:49.319940   70326 out.go:177] 🔄  Restarting existing parallels VM for "minikube" ...
I0215 23:53:49.341873   70326 main.go:141] libmachine: executing: /usr/local/bin/prlsrvctl net info Shared
I0215 23:53:49.533330   70326 main.go:141] libmachine: IP address of Shared network adapter: 10.211.55.2
I0215 23:53:49.533644   70326 main.go:141] libmachine: All host interface addressess: [127.0.0.1/8 ::1/128 fe80::1/64 fe80::aede:48ff:fe00:1122/64 fe80::1c1d:7d78:e094:4a8a/64 2405:9800:b970:99a6:1ccc:9d21:285d:bc1d/64 2405:9800:b970:99a6:5904:4717:dce3:902d/64 192.168.1.200/24 fe80::f044:98ff:fef9:e903/64 fe80::f044:98ff:fef9:e903/64 fe80::ae22:f05d:f735:aefe/64 fe80::fa09:7461:e1b:f2d9/64 fe80::f8e3:e80:3a7c:548a/64 fe80::ce81:b1c:bd2c:69e/64 10.211.55.2/24 fe80::3c22:fbff:feb9:6f64/64 fdb2:2c26:f4e4::1/64 10.37.129.2/24 fe80::3c22:fbff:feb9:6f65/64 fdb2:2c26:f4e4:1::1/64]
I0215 23:53:49.533651   70326 main.go:141] libmachine: Parallels Shared network adapter is connected
I0215 23:53:49.533689   70326 main.go:141] libmachine: executing: /usr/local/bin/prlctl list minikube --output status --no-header
I0215 23:53:49.689987   70326 fix.go:56] fixHost completed within 566.643678ms
I0215 23:53:49.690041   70326 start.go:83] releasing machines lock for "minikube", held for 566.737834ms
W0215 23:53:49.690173   70326 out.go:239] 😿  Failed to start parallels VM. Running "minikube delete" may fix it: driver start: machine does not exist
I0215 23:53:49.711616   70326 out.go:177]
W0215 23:53:49.733303   70326 out.go:239] ❌  Exiting due to GUEST_DOES_NOT_EXIST: Failed to start host: driver start: machine does not exist
W0215 23:53:49.733404   70326 out.go:239] 💡  Suggestion: Run 'minikube delete' to delete the stale VM, or and ensure that minikube is running as the same user you are issuing this command with
W0215 23:53:49.733429   70326 out.go:239] 🍿  Related issues:
W0215 23:53:49.733486   70326 out.go:239]     ▪ https://github.com/kubernetes/minikube/issues/3864
W0215 23:53:49.733520   70326 out.go:239]     ▪ https://github.com/kubernetes/minikube/issues/6087
I0215 23:53:49.754215   70326 out.go:177]

❌  Exiting due to GUEST_DOES_NOT_EXIST: state: machine does not exist
💡  Suggestion: Run 'minikube delete' to delete the stale VM, or and ensure that minikube is running as the same user you are issuing this command with
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3864
    ▪ https://github.com/kubernetes/minikube/issues/6087

### Operating System

macOS (Default)

### Driver

Parallels

**Comment by afbjorklund** [comment]
Probably something for https://github.com/Parallels/docker-machine-parallels

Minikube isn't exactly using boot2docker anymore but is not in the "allowed" list.

**Comment by afbjorklund** [comment]
* https://github.com/Parallels/docker-machine-parallels/issues/111
