### ISSUE TITLE
minikube doesnt start and giving permission issue

### ISSUE THREAD

**Issue by sobintho** [kubernetes/minikube#18192]
### What Happened?

While launching minikube i am getting permission error.

* Creating qemu2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...| OUTPUT:
ERROR: Could not access KVM kernel module: Permission denied
qemu-system-x86_64: -accel kvm: failed to initialize kvm: Permission denied

* Deleting "minikube" in qemu2 ...
! StartHost failed, but will try again: creating host: create: creating: Could not access KVM kernel module: Permission denied
qemu-system-x86_64: -accel kvm: failed to initialize kvm: Permission denied: exit status 1
* Creating qemu2 VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...- OUTPUT:
ERROR: Could not access KVM kernel module: Permission denied
qemu-system-x86_64: -accel kvm: failed to initialize kvm: Permission denied

* Failed to start qemu2 VM. Running "minikube delete" may fix it: creating host: create: creating: Could not access KVM kernel module: Permission denied
qemu-system-x86_64: -accel kvm: failed to initialize kvm: Permission denied: exit status 1

X Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: creating: Could not access KVM kernel module: Permission denied
qemu-system-x86_64: -accel kvm: failed to initialize kvm: Permission denied: exit status 1
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

 ~$ minikube logs --file=logs.txt

In the lsmod i am able to see kvm_intel
lsmod | grep kvm
kvm_intel             368640  0
kvm                  1032192  1 kvm_intel

[logs.txt](https://github.com/kubernetes/minikube/files/14317575/logs.txt)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14317579/logs.txt)

### Operating System

Ubuntu

### Driver

KVM2

**Comment by sobintho** [comment]
When i tried in root mode.  i was getting error

**Comment by zhengtianbao** [comment]
Seems like a KVM incorrect permission problem, try to add your username to kvm group `usermod -a -G kvm username` may fixed this.
