### ISSUE TITLE
docker run error 'exec format error' on Apple silicon M2 on docker desktop 4.27.2

### ISSUE THREAD

**Issue by biscout42** [kubernetes/minikube#18217]
### What Happened?

I use Mac M2 Pro, MacOS Sonoma 14.3.1, Docker Desktop 4.27.2 with Rosetta enabled. 

```
docker run --platform linux/amd64 -it ubuntu:latest bash
```
leads to the error
```
exec /usr/bin/bash: exec format error
```

Same happens with `registry-creds` addon, which is also available only for `amd64`

If I remove minikube via `brew remove minikube` and clean docker `docker system prune -a` , following command works:

```
docker run --platform linux/amd64 -it ubuntu:latest bash

Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
01007420e9b0: Pull complete
Digest: sha256:f9d633ff6640178c2d0525017174a688e2c1aef28f0a0130b26bd5554491f0da
Status: Downloaded newer image for ubuntu:latest
root@956b98e29407:/#
```

Error started after updating Docker Desktop to version 4.27.2. While investigation [original issue in docker desktop](https://github.com/docker/for-mac/issues/7168) we found it is related to minikube. 

How-to reproduce:
* Install Docker Desktop `4.27.2 (137060)`
* run and delete minikube via
```
minikube start --cpus='8' --memory='16g' --disk-size '24g'
minikube stop
minikube delete
```
* then run `docker run --platform linux/amd64 -it ubuntu:latest bash`

### Attach the log file

```
* ==> Audit <==
* |---------|-------------------------------------------------------------|----------|---------|---------|---------------------|---------------------|
| Command |                            Args                             | Profile  |  User   | Version |     Start Time      |      End Time       |
|---------|-------------------------------------------------------------|----------|---------|---------|---------------------|---------------------|
| start   | --cpus=8 --memory=16g                                       | minikube | | v1.32.0 | 20 Feb 24 10:58 CET | 20 Feb 24 10:59 CET |
|         | --disk-size 24g                                             |          |         |         |                     |                     |
| stop    |                                                             | minikube | | v1.32.0 | 20 Feb 24 11:04 CET | 20 Feb 24 11:04 CET |
| delete  |                                                             | minikube | | v1.32.0 | 20 Feb 24 11:04 CET | 20 Feb 24 11:04 CET |
|---------|-------------------------------------------------------------|----------|---------|---------|---------------------|---------------------|
```

### Operating System

macOS (Default)

### Driver

Docker

**Comment by biscout42** [comment]
Hey @ofirbe , is it kinda chicken and egg problem? I mean: where community folks could rise an issue to make DD and minikube work happy together ❤️ ?

I mean [DD folks say](https://github.com/docker/for-mac/issues/7168#issuecomment-1940920332) it is minikube issue, and here I hear opposite. Please, advice.

**Comment by afbjorklund** [comment]
The reset of binfmt_misc is a minikube problem. It originated in ubuntu, but was inherited by kicbase.

It is not Dockers issue, just that their VM is hosting the shared kernel

**Comment by biscout42** [comment]
Ough, that explains why `gcr.io/k8s-minikube/kicbase-builds:v0.0.42-1703092832-17830` image works. Thanks, @afbjorklund , that makes sense.

Which `kicbase-builds` version would you suggest to use before the fix ends up in the `gcr.io/k8s-minikube/kicbase`?

**Comment by harshitrjpt** [comment]
I don't know about any fixes in the latest version, **but this issue is still happening on**

Apple M1 Pro, macOS 14.4
Docker Desktop 4.28.0 (139021)
minikube 1.32

**Comment by pre** [comment]
> I don't know about any fixes in the latest version, **but this issue is still happening on**
> 

The latest release is from November. 🤷🏻‍♂️

https://github.com/kubernetes/minikube/issues/18250

**Comment by afbjorklund** [comment]
https://github.com/kubernetes/minikube/releases/tag/v1.33.0-beta.0

**Comment by harshitrjpt** [comment]
> https://github.com/kubernetes/minikube/releases/tag/v1.33.0-beta.0

This beta release still has the issue (if you mentioned this release as a fix). PFA screenshot showing the issue in action.
![Uploading Screenshot 2024-03-29 at 12.22.53 AM.png…]()

**Comment by eveletspb** [comment]
same error
> > https://github.com/kubernetes/minikube/releases/tag/v1.33.0-beta.0
> 
> This beta release still has the issue (if you mentioned this release as a fix). PFA screenshot showing the issue in action. <img alt="Screenshot 2024-03-29 at 12 22 53 AM" width="1728" src="https://private-user-images.githubusercontent.com/31892897/317848794-5a0d6f51-ce77-4a79-8c90-67c1203067cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4OTczNTgsIm5iZiI6MTcxMTg5NzA1OCwicGF0aCI6Ii8zMTg5Mjg5Ny8zMTc4NDg3OTQtNWEwZDZmNTEtY2U3Ny00YTc5LThjOTAtNjdjMTIwMzA2N2NmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMxVDE0NTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxZTZhNGY4N2ViOTYwYzE1ZDRmZTBlM2EyNDk0YmNmMTg1YzRmMDkyYzkyMjkxMzU1ZjczMzY2ZDk4NGNlZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qb1KZuhFOa81FWST7Y5W5ahJHq62nmm6k91bjgyLDHo">

**Comment by nevotheless** [comment]
I've the same issue after installing the 1.33.0-beta.0 release via homebrew. I've previously removed the old minikube cluster and removed the package. 

Do we have to reset the docker desktop vm as well for this to work?

**Comment by dasumner** [comment]
I don't seem to be able to downgrade my way out of this.  I've tried going back to 4.26.1 as suggested by @ofirbe, but I still keep getting the error.  Is there a formula for Minikube/Docker Desktop that's known to work?

**Comment by adityasamant25** [comment]
> I don't seem to be able to downgrade my way out of this. I've tried going back to 4.26.1 as suggested by @ofirbe, but I still keep getting the error. Is there a formula for Minikube/Docker Desktop that's known to work?

There is, but it involves a `docker system prune`, that means it will wipe out all your docker images, containers and volumes.
So you will need to be 100% sure that you do not need any of your deployments on Docker Desktop anymore before trying it.
If there are important deployments, then don't follow these steps and you may need some other solution.

The details are here: https://github.com/docker/for-mac/issues/7168#issuecomment-1953859233

The commands that help me overcome this are:

1. `brew remove minikube`

2. `docker system prune -a`

3. Shutdown and restart Docker Desktop (Docker engine reboot).

4. Test that the below command runs successfully and you are able to exec into an ubuntu container for amd64 platform
`docker run --platform linux/amd64 -it ubuntu:latest bash`

5. `brew install minikube`

6. Start minikube using a very specific base image
`minikube start --base-image gcr.io/k8s-minikube/kicbase-builds:v0.0.42-1703092832-17830`

7. Try to run a Pod that uses a amd64 image on minikube, it is supposed to run.

**Comment by pre** [comment]
In our team, the [v1.33.0-beta.0](https://github.com/kubernetes/minikube/releases/tag/v1.33.0-beta.0) Release has fixed the exec format error with the newer kicbase image. 

However, an existing minikube cluster needs to be deleted and recreated after upgrading minikube.

**Comment by dasumner** [comment]
The newer base-image seems to have done the trick.  Thank you very much.

**Comment by nevotheless** [comment]
I've just more or less tried what @adityasamant25 did https://github.com/kubernetes/minikube/issues/18217#issuecomment-2066703619. 

Previous attempts didn't work for me since i never reset my docker system, which seems to also reset the `binfmt` shenanigans a previous minikube version setup which became incompatible. (Atleast that's my headcanon now). 

As of today a clean 
- Docker (Desktop on Mac) Version `26.0.0` and a clean via Homebrew installed 
- minikube Version `v1.33.0` using kicbase image `gcr.io/k8s-minikube/kicbase:v0.0.43` (which is default atm, i didn't put a custom image)

works again as intended.

**Comment by bkuhl** [comment]
I appear to be having this issue setting up minikube for the first time.

```
➜ minikube start            
😄  minikube v1.33.1 on Darwin 14.4.1 (arm64)
✨  Using the docker driver based on existing profile
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🚜  Pulling base image v0.0.44 ...
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=16300MB) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --name minikube-preload-sidecar --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.44@sha256:eb04641328b06c5c4a14f4348470e1046bbcf9c2cbc551486e343d3a49db557e -d /var/lib: exit status 1
stdout:

stderr:
exec /usr/bin/test: exec format error
```

 - Docker version 25.0.4-rd, build c4cd0a9
 - Docker Desktop v4.30

**Comment by bkuhl** [comment]
I encountered this error while running `minikube up` on an M1 for the first time (not a new machine, long history of using docker/compose) using the latest Minikube.  The `minikube delete && docker system prune -a` fixed it for me.

**Comment by biscout42** [comment]
I would close it, because it works 🎉 . Thanks the the team. 

Verified with
* Docker desktop `4.30.0`
* Minikube [1.33.1](https://github.com/kubernetes/minikube/releases/tag/v1.33.1)

To refresh system please use [suggestion](https://github.com/kubernetes/minikube/issues/18217#issuecomment-2066703619) from @adityasamant25
