### ISSUE TITLE
minikube mount fails for directories not belonging to current user

### ISSUE THREAD

**Issue by NGTOne** [kubernetes/minikube#1822]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Minikube version**:
minikube version: v0.21.0

**Environment**:
- **OS**: Ubuntu 16.04.2
- **VM Driver**: virtualbox
- **ISO version**: testing

**What happened**:

    Mounting /home/sebastian/code into /home/docker/src on the minikube VM
    This daemon process needs to stay alive for the mount to still be accessible...
    ufs starting
    ssh command error:
    command : 
    sudo mkdir -p /home/docker/src || true;
    sudo mount -t 9p -o trans=tcp,port=34143,dfltuid=1001,dfltgid=1001,version=9p2000.u,msize=262144 192.168.99.1 /home/docker/src;
    sudo chmod 775 /home/docker/src;
    err     : exit status 1
    output  : chmod: changing permissions of '/home/docker/src': Input/output error

**What you expected to happen**:
`/home/sebastian/code` gets mounted successfully into `/home/docker/src` on the minikube.

**How to reproduce it**:

    chown -R www-data /home/sebastian/code
    minikube mount /home/sebastian/code:/home/docker/src

**Comment by r2d4** [comment]
You'll need to run the `minikube mount` command as that user if you want to mount a folder owned by that user.
