### ISSUE TITLE
Minikube cluster using kvm2 driver is broken on linux/aarch64

### ISSUE THREAD

**Issue by nirs** [kubernetes/minikube#18238]
### What Happened?

Starting minikube using kvm2 driver times out getting an ip address. The VM
starts but drop into the UEFI shell.

Example command:

    minikube start --driver kvm2

The issue is using SATA cdrom - this is not supported in QEMU for linux/aarch64.

To reproduce install [Asahi Linux Fedora remix](https://asahilinux.org/) on a MacBook.

### Attach the log file

Logs are not relevant.

### Operating System

Redhat/Fedora

### Driver

KVM2

**Comment by afbjorklund** [comment]
Also there is a lack of Fedora testing in general, including other architectures such as x86_64

* https://github.com/kubernetes/minikube/issues/3552
