### ISSUE TITLE
Hit error in minikube mount: unknown filesystem type '9p'

### ISSUE THREAD

**Issue by cywang16** [kubernetes/minikube#18242]
### What Happened?

I use minikube in a CentOS VM with docker driver. I hit this error in
```
minikube mount .:/cmake
```
The log file is attached. Please help me to understand this error. Thanks.

### Attach the log file

[minikube_mount.txt](https://github.com/kubernetes/minikube/files/14397411/minikube_mount.txt)

### Operating System

Other

### Driver

Docker

**Comment by afbjorklund** [comment]
CentOS does not support 9p, so you will have to use another way to access your files (e.g. `minikube start --mount`)
