### ISSUE TITLE
Exiting Due To Guest Start when installing Minikube on Colima x86_64 on Mac M1

### ISSUE THREAD

**Issue by adamlwatson** [kubernetes/minikube#18258]
### What Happened?

I'm trying to install Minikube on a Colima x86_64 instalnce on a Mac M1. I'm starting the Colima instance using this configuration:

`colima start --cpu 4 --memory 10 --disk 100 --runtime docker --arch x86_64 --vm-type vz
`
Once the Colima instance is running and I verify the Docker Daemon is running, I then try to start Minikube using this configuration:

`minikube start --cpus 4 --memory 9G --disk-size 90G --driver docker --container-runtime docker
`

Toward the end of setup, I receive an error:

```
❌  Exiting due to GUEST_START: failed to start node: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.28.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,NumCPU,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 2
stdout:

stderr:
/var/lib/minikube/binaries/v1.28.3/kubeadm: 2: Syntax error: newline unexpected (expecting ")")

```

I've seen another issue that was similar to this, and have tried a `minikube delete --all --purge` to no avail.

I am able to spin up amd64 images under the Docker instance running on Colima x86_64 manually.

If I start minikube under a Colima instance that's set to the aarch64 archirtecture with Rosetta enabbled, the minikube installation works as expected... but then I can't seem to get any linux/amd64 images to run (of course).

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14426258/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by afbjorklund** [comment]
* https://github.com/kubernetes/minikube/issues/16530
