### ISSUE TITLE
Create a new Minikube Release (current latest version is broken with latest Docker Desktop for Mac)

### ISSUE THREAD

**Issue by pre** [kubernetes/minikube#18250]
### What Happened?

Create a new Minikube Release. Latest release is v1.32.0 from November 2023, and this version does not work with the latest Docker Desktop for Mac (ARM).

Docker Desktop for Mac v4.27.0 changed their amd64/arm64 emulation settings. The latest Docker Desktop version compatible with Minikube is v4.26.1.

There is a fix in 
* https://github.com/kubernetes/minikube/pull/17830

Which is dicussed in https://github.com/kubernetes/minikube/issues/18217
* https://github.com/kubernetes/minikube/issues/18217

### Attach the log file

exec /bin/sh: exec format error

### Operating System

macOS (Default)

### Driver

Docker

**Comment by hnsmn** [comment]
same `exec format error` problem here with minikube & docker on a MacBook Pro M3 Max.

**Comment by panuvuorinensapcom** [comment]
I also have the same `exec format error `. Works with Docker `v4.26.1`.

**Comment by afbjorklund** [comment]
https://github.com/kubernetes/minikube/releases/tag/v1.33.0-beta.0

**Comment by pre** [comment]
Initially it seems v1.33.0-beta.0 fixes the issue! I haven't seen the `exec format error` yet.

**Comment by nevotheless** [comment]
Howdy and thanks for the release! 👋🏽  How long does it usually stay in beta?

**Comment by spowelljr** [comment]
Since minikube 1.33 has been released this should be resolved, I'll close the issue but if it's not resolved for someone feel free to reopen
