### ISSUE TITLE
kuberentes-issue

### ISSUE THREAD

**Issue by Kamal-Basha** [kubernetes/minikube#18268]
### What Happened?

nothing

### Attach the log file

nothing

### Operating System

None

### Driver

Docker

**Comment by T-Lakshmi** [comment]
@Kamal-Basha,
Please provide details what you are facing the issue.

**Comment by T-Lakshmi** [comment]
Closing the issue as not planned.
@Kamal-Basha Feel free to reopen issue with necessary details if you still facing it.
