### ISSUE TITLE
Add flag do disable swap 

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/minikube#1827]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Please provide the following details:
**Environment**:  Minikube on Windows
**Minikube version** (use `minikube version`): 0.21
- **OS** (e.g. from /etc/os-release):
NAME=Buildroot
VERSION=2017.02
ID=buildroot
VERSION_ID=2017.02
PRETTY_NAME="Buildroot 2017.02"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
minikube-v0.23.0.iso

Hi,

we want to disable swap in Minikube to align Minikube to our production environments. The best way to do that is  (afaik):
````
minikube ssh "sudo bash -c 'if swapon |grep -q 0B; then swapoff -a; echo SUCCEEDED swap is off; else echo FAILED swap is already in use; fi'"
````

Could you add a flag to disable swap or maybe disable swap altogether if you decide it makes sense.

**Comment by r2d4** [comment]
@dlorenc @aaron-prindle what do you think about just disabling swap altogether?

**Comment by afbjorklund** [comment]
:+1: for disabling swap, seems to be required by `kubeadm` anyway ?

https://kubernetes.io/docs/setup/independent/install-kubeadm/

> Swap disabled. You **MUST** disable swap in order for the kubelet to work properly.

**Comment by afbjorklund** [comment]
This is the error from the kubeadm pre-flight:

`	[ERROR Swap]: running with swap on is not supported. Please disable swap`

Apparently kubelet 1.8.0+ doesn't really like it. (kubernetes/kubernetes@71e8c8eba43a0fade6e4edfc739b331ba3cc658a)

`Running with swap on is not supported, please disable swap!`
