### ISSUE TITLE
minikube start not working with docker

### ISSUE THREAD

**Issue by Satyabati** [kubernetes/minikube#18310]
### What Happened?

[lastStart.txt](https://github.com/kubernetes/minikube/files/14494618/lastStart.txt)

### Attach the log file

Not able to start minikube with docker

### Operating System

Windows

### Driver

Docker

**Comment by NithishKumar-4** [comment]
i have changed the driver its working fine now

**Comment by Satyabati** [comment]
do I need to take any update? Can you please guide me on the same?

**Comment by NithishKumar-4** [comment]
No, Thanks for your support

**Comment by T-Lakshmi** [comment]
@Satyabati, @NithishKumar-4,
Is there any issue still you arefacing in this?

**Comment by NithishKumar-4** [comment]
No issues, Thanks for the support it's working fine now.

**Comment by T-Lakshmi** [comment]
Thanks for the response, iam closing issue as resolved.
feel free to reopen if any further assistance equired.
