### ISSUE TITLE
 minikube start

### ISSUE THREAD

**Issue by ManojKumar1611** [kubernetes/minikube#18312]
### What Happened?

Unable to resolve the current Docker CLI context "default": context "default": context not found: open C:\Users\chinn\.docker\contexts\meta\37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f\meta.json: The system cannot find the path specified.
* minikube v1.32.0 on Microsoft Windows 11 Home Single Language 10.0.22631.3235 Build 22631.3235
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
! StartHost failed, but will try again: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\chinn\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Failed to start hyperv VM. Running "minikube delete" may fix it: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\chinn\.minikube\machines\minikube\config.json: The system cannot find the file specified.                                                                                                                                X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\chinn\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

### Attach the log file

![Screenshot (27)](https://github.com/kubernetes/minikube/assets/148075391/ad28e3be-6d67-406d-9af3-5dff070f34b6)

### Operating System

Windows

### Driver

Hyper-V

**Comment by T-Lakshmi** [comment]
Hi @ManojKumar1611,
Make sure you have sufficient memory available that mentioned [here](https://minikube.sigs.k8s.io/docs/start/) and try to reinstall with below commands:
minikube delete
minikube start

**Comment by ManojKumar1611** [comment]
i have sufficient of memory, but it doesn't work
![Screenshot (28)](https://github.com/kubernetes/minikube/assets/148075391/8ef9c26f-db8f-4b3b-844e-42c63ea7e119)

**Comment by T-Lakshmi** [comment]
Did you follow the below steps?

minikube delete
minikube start
