### ISSUE TITLE
 no running pod for service node--app found

### ISSUE THREAD

**Issue by ErAnujPratap** [kubernetes/minikube#18344]
### What Happened?

Exiting due to SVC_UNREACHABLE: service not available: no running pod for service node--app found
 😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_service_25dce44ca64be6889d7b07497d3c0094ba7937a9_0.log   

### Attach the log file

exec /usr/local/bin/docker-entrypoint.sh: exec format error

### Operating System

Ubuntu

### Driver

Docker

**Comment by T-Lakshmi** [comment]
@ErAnujPratap,
Make sure the selectors mentioned in the service manifest must match with the pod manifest labels.

**Comment by T-Lakshmi** [comment]
If you still facing issue, please share pod, service yaml manifest that you are working on.

**Comment by T-Lakshmi** [comment]
@ErAnujPratap,
As you not responded here since many days, iam assuming your issue got resolve. Hence closing this issue.
Please feel free to reopen the issue and update with details if you still facing any challenge related to this issue.
