### ISSUE TITLE
Addons folder per profile

### ISSUE THREAD

**Issue by sbueringer** [kubernetes/minikube#1835]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Please provide the following details:
**Environment**:  Minikube on Windows
**Minikube version** (use `minikube version`): 0.21
- **OS** (e.g. from /etc/os-release):
NAME=Buildroot
VERSION=2017.02
ID=buildroot
VERSION_ID=2017.02
PRETTY_NAME="Buildroot 2017.02"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
minikube-v0.23.0.iso

Hi,

we want to use different profiles with Minikube at the same time with differen addons. Because we deploy addons in the .minikube/addons folder we have problems with deploying different addons on different Minikube profiles.

Would it be possible to either add a flag for the addon folder (1) or use a unique addon folder per profile per default (2), i.e.:
 * Profile dev uses .minikube/addons_dev
 * Profile prod uses .minikube/addons_prod

**Comment by r2d4** [comment]
I agree.  This could possibly be fixed in parallel with minikube config get/set/view/unset, which doesn't respect the `--profile` command.

**Comment by lalomartins** [comment]
I have a client who uses nginx for ingress, and another who wants to use something else (still undecided, but something that supports grpc). Currently that's not possible with minikube short of some serious juggling, and that makes profiles a lot less useful than they should be.
