### ISSUE TITLE
X Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory * Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization. * Related issues:   - https://github.com/kubernetes/minikube/issues/3900   - https://github.com/kubernetes/minikube/issues/4730

### ISSUE THREAD

**Issue by shivshankar123ch** [kubernetes/minikube#18365]
X Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900
  - https://github.com/kubernetes/minikube/issues/4730

**Comment by T-Lakshmi** [comment]
> Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.

Which driver you are using to install minikube?
Please try with below command:

**minikube start --driver=`driver-name` --no-vtx-check**
Replace driver-name with the driver name you are using, you can eliminate --driver flag if you are using docker as driver.

**Comment by sunilgknair051** [comment]
Hello, I would like to answer this query and hope one of the maintainers then can close this issue. The virtualization needs to be enabled in the BIOS options. Enter your BIOS once you start your computer and then check for the virtualization option, if disabled then enable and save changes.
