### ISSUE TITLE
Rootful podman docs: asking for passwordless sudo is dangerous

### ISSUE THREAD

**Issue by awoimbee** [kubernetes/minikube#18360]
### Issue:
I want to use the rootful podman driver, because the rootless driver is incomplete (which is understandable).
But [the docs](https://minikube.sigs.k8s.io/docs/drivers/podman/) want me to enable passwordless sudo (without any warning about the security implications) !
This is privilege escalation 101, the docs should contain a warning.
![image](https://github.com/kubernetes/minikube/assets/22431493/6303f034-711f-4ada-a203-323988528656)

### Workaround:
So I use the KVM2 driver, which asks me for root access interactively.
![Screenshot from 2024-03-11 20-28-27](https://github.com/kubernetes/minikube/assets/22431493/45d20938-f640-4c19-af8e-1a2775b074fb)

Note:
The sudo prompt for the KVM2 driver on my system comes from polkit, I guess that's pretty standard since the [kvm2 driver docs](https://minikube.sigs.k8s.io/docs/drivers/kvm2/) has no note about root access ? Could the podman driver use polkit too ?

### Attach the log file

logs are not useful for this issue

### Operating System

Redhat/Fedora

### Driver

Podman

**Comment by afbjorklund** [comment]
Using `sudo` is the recommended root escalation from podman, instead of using a "podman" group (like docker does it)

The security implications is probably the same either way, but the documentation _could_ have a more clear warning text

https://docs.docker.com/engine/install/linux-postinstall/

https://projectatomic.io/blog/2015/08/why-we-dont-let-non-root-users-run-docker-in-centos-fedora-or-rhel/

**Comment by awoimbee** [comment]
Indeed, the first step is to add warnings to the docs.
Then I see multiple solutions:
* Allow interactive sudo when launching podman/docker commands: https://github.com/kubernetes/minikube/blob/375d9c6cbf6d33a1c20d91c886f7f19c5d8b52c2/pkg/drivers/kic/oci/cli_runner.go#L185
* Use polkit: in minikube, like https://github.com/freedomofpress/dangerzone/pull/56

For now I can use this work around (which asks for auth a million times, but works):
```shell
$ cat sudo
#!/bin/env sh

while [ "${1:0:1}" == "-" ]; do
    shift
done

pkexec "$@"
$ PATH="$(pwd):$PATH" minikube start --container-runtime=cri-o --embed-certs --kubernetes-version=v1.29.2 --driver=podman --memory=8192 --cpus=4 -v=2 --alsologtostderr
```

**Comment by afbjorklund** [comment]
Using polkit sounds like something that should be done by upstream Podman, in that case?

But they don't seem to have any solution since, except for using rootless instead...

**Comment by afbjorklund** [comment]
With regards to security:

qemu > kvm > podman > none
