### ISSUE TITLE
Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: metric-server is not a valid addon

### ISSUE THREAD

**Issue by ironcloud117** [kubernetes/minikube#18363]
### What Happened?

Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: metric-server is not a valid addon

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14570086/logs.txt)

### Operating System

None

### Driver

None

**Comment by T-Lakshmi** [comment]
#13872 is reported earlier for same error,
Going through the conversation #13872 may help you to resolve your issue.

**Comment by T-Lakshmi** [comment]
@ironcloud117,
Since we not heard any from you long time, I am assuming your issue has resolved and closing this issue.

> Going through the conversation https://github.com/kubernetes/minikube/issues/13872 may help you to resolve your issue.

Please follow #13872 if you are still facing this problem.
