### ISSUE TITLE
Minikube Container Running Image for Wrong Architecture

### ISSUE THREAD

**Issue by keyle56** [kubernetes/minikube#18378]
### What Happened?

I've just purchased a new Macbook with an M3 chip. I installed minikube and Docker but minikube is unable to start up. 

It seems to me that the issue is the minikube container being ran is not for the correct architecture. I see in the container logs `Detected x86_64 architecture`. But sometimes the container isn't able to be started at all so I could definitely be dealing with an intermittent issue and/or multiple problems.

Things I've tried:
- Running `minikube delete --purge` then `minikube start`
- Uninstalling and reinstalling both minikube and Docker

Here are the logs when I run `minikube start --alsologtostderr`:

[minikube-logs.pdf](https://github.com/kubernetes/minikube/files/14589061/minikube-logs.pdf)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14589015/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by kyleaebischer56** [comment]
Some additional context:

I've just tried running
```shell
rm -rf ~/.minikube
minikube delete --all --purge
docker system prune -a --volumes -f
```

and then restarted minikube with `minikube start`. But now it appears that the minikube container is unable to even startup. I do not see any containers running in Docker Desktop and in the minikube logs, I see this:
```
I0313 10:32:26.317929   42578 network_create.go:281] running [docker network inspect minikube] to gather additional debugging logs...
I0313 10:32:26.317940   42578 cli_runner.go:164] Run: docker network inspect minikube
W0313 10:32:26.353887   42578 cli_runner.go:211] docker network inspect minikube returned with exit code 1
I0313 10:32:26.353923   42578 network_create.go:284] error running [docker network inspect minikube]: docker network inspect minikube: exit status 1
stdout:
[]

stderr:
Error response from daemon: network minikube not found
I0313 10:32:26.353932   42578 network_create.go:286] output of [docker network inspect minikube]: -- stdout --
[]

-- /stdout --
** stderr ** 
Error response from daemon: network minikube not found
```

**Comment by dmvariphy** [comment]
Hey @keyle56 - just wanted to drop a note here since we've been troubleshooting this together.

It looks like this issue was caused by `DOCKER_DEFAULT_PLATFORM` being set to `linux/amd64`.  Once we `unset DOCKER_DEFAULT_PLATFORM` (see https://github.com/kubernetes/minikube/issues/13929#issuecomment-1118178982), we were able to get Minikube started.

**Comment by afbjorklund** [comment]
There should be a warning for that, similar to the one for downloading the wrong `minikube` program.
