### ISSUE TITLE
Slif save kts

### ISSUE THREAD

**Issue by Lyllt8** [kubernetes/minikube#18388]
https://prow.k8s.io/log?job=ci-aws-kops-eks-sandbox&id=1768362157306548224

**Comment by Lyllt8** [comment]
.k8s-prow-images.yaml

**Comment by Lyllt8** [comment]
Please contact Rosemoe by email 2073412493@qq.com if you need
additional information or have any questions

**Comment by T-Lakshmi** [comment]
@Lyllt8 ,

Its unable to understand what issue you are facing with mention details.
Please describe more more details about issue.
