### ISSUE TITLE
Exiting due to SVC_UNREACHABLE

### ISSUE THREAD

**Issue by Udhaitester** [kubernetes/minikube#18420]
### What Happened?

service not available: no running pod for service webapp-service found

### Attach the log file

>minikube service webapp-service
|-----------|----------------|-------------|---------------------------|
| NAMESPACE |      NAME      | TARGET PORT |            URL            |
|-----------|----------------|-------------|---------------------------|
| default   | webapp-service |        8081 | http://192.168.49.2:30100 |
|-----------|----------------|-------------|---------------------------|

❌  Exiting due to SVC_UNREACHABLE: service not availab

### Operating System

Windows

### Driver

Docker

**Comment by Ritikaa96** [comment]
It also seems like a support request. 
/kind support
