### ISSUE TITLE
How to use local swapfile as extra memory ?

### ISSUE THREAD

**Issue by leobenkel** [kubernetes/minikube#18444]
### What Happened?

my local `free -m` has 500G of swap memory available. 
I would like to leverage this memory for minikube, however when starting with `--memory "<BIG>"` it fails with `RSRC_OVER_ALLOC_MEM` mentioning my actual physical RAM.

Is there a way to either leverage the local swap ram ? or a way to create a swap space in minikube that my deployments can use ? (i am using helm)

Thank you
 

Ubuntu

### Driver

Docker

**Comment by medyagh** [comment]
the answer really depends on the implementaiton of the hypervisor

I see you use Docker, if docker can use SWAP files as memory, then we could add that functionality to minikube, so in this case do you know or have u already asked docker if they can do that?

**Comment by leobenkel** [comment]
no, i was more asking if it was possible to assign disk space to minikube and then minikube ssh into it to manually add swap. i've tried but without success.

**Comment by afbjorklund** [comment]
You can use `--force` to skip the warning, and start minikube anyway.

Since it is running Docker on Ubuntu, there is no hypervisor involved.

**Comment by leobenkel** [comment]
what do you mean by start anyway?

**Comment by afbjorklund** [comment]
... instead of exiting, after the warning message

**Comment by leobenkel** [comment]
im confused
