### ISSUE TITLE
`minikube image ls` does not return the same number of entries depending on `--format`

### ISSUE THREAD

**Issue by ErwanDL** [kubernetes/minikube#18452]
### What Happened?

Running `minikube image ls --format [json|yaml]` returns more images than running `minikube image ls --format [short|table]` (69 vs 26 images in my case).

I could not find any information in the documentation or online that explains this behaviour. Is it expected that the `json`/`yaml` formats return more entries than the `short`/`table` versions? If yes, could the logic behind which images are excluded from the short output be explained somewhere?

I cannot provide the exact output of the commands here for security reasons, but if a maintainer needs it I can provide it to them directly.

EDIT: upon further inspection, I realized that `--format [short|table]` excludes any entries that do have empty `repoTags` (in my case, some images only have `repoDigests`). Is this expected?

### Attach the log file

```
minikube version: v1.32.0
commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d
```
<redacted>

### Operating System

Ubuntu

### Driver

KVM2

**Comment by afbjorklund** [comment]
The list could probably default to showing the (short?) Ids instead, for images that don't have any repo tags.

Similar to the "<none>" stuff that you get in the `docker image list`, and like the output from `crictl images`

**Comment by ErwanDL** [comment]
> The list could probably default to showing the (short?) Ids instead, for images that don't have any repo tags.

That sounds good.

> Hmm, seems that the list is already doing some (broken) variant of this - wonder what that is all about
> ```
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> docker.io/library/<none>:<none>
> ```

In my case, I don't see such entries when running `minikube image ls --format short`. Images without a tag are simply not shown at all.

**Comment by Ritikaa96** [comment]
> minikube image ls --format

This is what i see as well and no change in number of images shown. so its just the format change
