### ISSUE TITLE
Add macvtap support/kmod

### ISSUE THREAD

**Issue by fabiand** [kubernetes/minikube#1845]
We - KubeVirt - would like to showcase KubeVirt in minikube.

To allow this we'll need the relevant kmods for macvtaps, otherwise we see:

```
2017-08-19 14:44:38.647+0000: 7372: error : virNetDevMacVLanCreate:403 : error creating macvtap interface macvtap0@eth0 (52:54:00:6d:90:a7): Operation not supported
```

**Comment by fabiand** [comment]
I checked the new iso, and it fixes the issue.

@r2d4 when will the new iso be released?

**Comment by r2d4** [comment]
https://github.com/kubernetes/minikube/pull/1851 will require a new ISO, so we'll probably release one after that.

**Comment by fabiand** [comment]
Cool, thanks.
