### ISSUE TITLE
[Question] Is there a way to cordon control-plane nodes by default?

### ISSUE THREAD

**Issue by anthony-S93** [kubernetes/minikube#18497]
If we start a multi-node cluster like so:
```txt
$ minikube start -n 5 -p some-cluster
```
The control-plane node in the cluster will not have `SchedulingDisabled` status by default. As a result, we have to run `kubectl cordon` manually to set that status. 

Is there a way to enable this by default?

**Comment by Ritikaa96** [comment]
It is not recommended to schedule pods on control plane Node. The control-plane node runs pods with critical services, thus by default, Kubernetes clusters don't schedule pods on the control-plane node for security reasons issues.

**Comment by anthony-S93** [comment]
> It is not recommended to schedule pods on control plane Node. The control-plane node runs pods with critical services, thus by default, Kubernetes clusters don't schedule pods on the control-plane node for security reasons issues.

Indeed. Which is why I'm asking this question in the first place. I'm asking for a way to have `SchedulingDisabled` automatically set for Control Plane nodes so that workloads will not get scheduled to them.

**Comment by Ritikaa96** [comment]
oh. I understand. I agree and the value of  " node-role.kubernetes.io/control-plane=" is empty.
This is the default behavior of Minikube as Minikube is not used in production level cluster creation is good for learning and dev/test environments.
We can taint the node manually by adding "NoSchedule" though if we want to make the master node unschedulable.

**Comment by anthony-S93** [comment]
> oh. I understand. I agree and the value of " node-role.kubernetes.io/control-plane=" is empty. This is the default behavior of Minikube as Minikube is not used in production level cluster creation is good for learning and dev/test environments. We can taint the node manually by adding "NoSchedule" though if we want to make the master node unschedulable.

Understood. And thank you for your response.

**Comment by Ritikaa96** [comment]
@anthony-S93 How about a flag in the beginning 
`minikube start -n 4 -p multinode --control-plane-unSchedulable
`

**Comment by Ritikaa96** [comment]
Even if i understand the reasoning behind the untainted control plane , if the NoSchedule is present by default, it will help in understanding the prod level work to new developers trying minikube.

**Comment by Rdxv** [comment]
Yeah I had this issue in minikube as well. I was trying to learn how hard antiAffinity works with replication redis and after making several other configs I ended up having one of the replicas scheduled on the control plane so I had to taint that node. 
Good learning material since they told me it's not supposed to happen in prod clusters.
