### ISSUE TITLE
install kubernetes v1.28.3 failed

### ISSUE THREAD

**Issue by lamanlu** [kubernetes/minikube#18496]
**重现问题所需的命令**：
minikube config defaults kubernetes-version
minikube start --image-mirror-country='cn' --kubernetes-version='v1.28.3'

**失败的命令的完整输出**：<details>
😄  Ubuntu 22.04 上的 minikube v1.32.0
✨  自动选择 docker 驱动
✅  正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
📌  使用具有 root 权限的 Docker 驱动程序
👍  正在集群 minikube 中启动控制平面节点 minikube
🚜  正在拉取基础镜像 ...
    > index.docker.io/kicbase/sta...:  453.90 MiB / 453.90 MiB  100.00% 3.74 Mi
❗  minikube was unable to download registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.42, but successfully downloaded docker.io/kicbase/stable:v0.0.42 as a fallback image
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  正在 Docker 24.0.7 中准备 Kubernetes v1.28.3…

❌  因 K8S_INSTALL_FAILED 错误而退出：Failed to update cluster: updating control plane: downloading binaries: downloading kubeadm: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.28.3/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.28.3/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.28.3/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.28.3/bin/linux/amd64/kubeadm.sha256 Dst:/home/laman/.minikube/cache/linux/amd64/v1.28.3/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x46177c0 0x46177c0 0x46177c0 0x46177c0 0x46177c0 0x46177c0 0x46177c0] Decompressors:map[bz2:0xc000639ca0 gz:0xc000639ca8 tar:0xc000639c50 tar.bz2:0xc000639c60 tar.gz:0xc000639c70 tar.xz:0xc000639c80 tar.zst:0xc000639c90 tbz2:0xc000639c60 tgz:0xc000639c70 txz:0xc000639c80 tzst:0xc000639c90 xz:0xc000639cb0 zip:0xc000639cc0 zst:0xc000639cb8] Getters:map[file:0xc002fad670 http:0xc003c321e0 https:0xc003c32230] Dir:false ProgressListener:0x45d7ae0 Insecure:false DisableSymlinks:false Options:[0x120d740]}: invalid checksum: Error downloading checksum file: bad response code: 404

╭─────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                 │
│    😿  如果上述建议无法帮助解决问题，请告知我们：                                               │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                 │
│                                                                                                 │
│    请运行 minikube logs --file=logs.txt 命令，并将生成的 logs.txt 文件附加到 GitHub 问题中。    │
│                                                                                                 │
╰─────────────────────────────────────────────────────────────────────────────────────────────────╯

</details>

**`minikube logs`命令的输出**： <details>
E0325 00:22:55.231762   21619 logs.go:195] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.28.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.28.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper
sudo: a password is required
 output: "\n** stderr ** \nsudo: a terminal is required to read the password; either use the -S option to read from standard input or configure an askpass helper\nsudo: a password is required\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes
</details>

**使用的操作系统版本**：
> lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

**Comment by lamanlu** [comment]
minikube version: v1.32.0
commit: 8220a6eb95f0a4d75f7f2d7b14cef975f050512d

**Comment by liangyuanpeng** [comment]
This is the issue for download file failed from aliyun, try to open it to https://github.com/AliyunContainerService/minikube/issues
