### ISSUE TITLE
Publish localkube to registry

### ISSUE THREAD

**Issue by thedrow** [kubernetes/minikube#1849]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**What happened**:
I can't pull the localkube docker image from Google Container Registry

**What you expected to happen**:
I want to run localkube locally using Docker without a VM so I expected to have the image published like hyperkube is.

**How to reproduce it** (as minimally and precisely as possible):
sudo docker pull gcr.io/k8s-minikube/localkube-image:1.7.4

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by r2d4** [comment]
Hey sorry, we just added the upload of the image to our release script a few days ago.  All future releases should be automatic, but I uploaded this one manually for now.

We don't have 1.7.4 merged yet (#1836), but you can get 1.7.3 at 

`gcr.io/k8s-minikube/localkube-image:v1.7.3`

**Comment by thedrow** [comment]
Great. Do you mind pushing 1.7.4 as well?

**Comment by r2d4** [comment]
Yeah, no problem.  v1.7.4 is there now too
