### ISSUE TITLE
logs.txt

### ISSUE THREAD

**Issue by venugopal-aadi** [kubernetes/minikube#18495]
### What Happened?

Exiting due to SVC_UNREACHABLE: service not available: no running pod for service springboot-demo-service found

### Attach the log file

logs.txt
/tmp/minikube_service_1f06abd94309f71cc906b1389e9f277e3f00e221_0.log

### Operating System

Ubuntu

### Driver

Docker
```[tasklist]
### Tasks
```

**Comment by T-Lakshmi** [comment]
@venugopal-aadi,

> Exiting due to SVC_UNREACHABLE: service not available: no running pod for service springboot-demo-service found

This error is because your service **springboot-demo-service** is unable to bind with any running pod due to mismatch with the seletors mentioned in service manifest. 

Please make sure **lables under pod** manifest must match with the **selector under service** manifest.

**Comment by T-Lakshmi** [comment]
@venugopal-aadi,
Since we not heard from you many day, i am assuming your issue has been resolved.
I am marking this issue as resolved now, please feel free to reopen it if you still facing the issue.
You can reopen anytime by commenting as "/reopen".
