### ISSUE TITLE
Dashboard enhancements (minikube IP instead of localhost, static port)

### ISSUE THREAD

**Issue by rdsubhas** [kubernetes/minikube#185]
Hi, not sure if this is the right place to file a bug on the Kubernetes Dashboard, but some suggestions:

- [ ] Dashboard URL links for all external endpoints are `localhost:<nodePort>`. But it would be good to use the minikube IP instead. Could be done by either using the current browser URL, or by providing the minikube IP as configuration to the dashboard.
- [x] Configure a static Dashboard nodePort rather than a random one each time the minikube VM is started.

Yeah I'm one lazy developer, but I find it an unnecessary hassle to fiddle with these URLs all the time 😃 I'd love to contribute to minikube, but would first like to know if this is a valid suggestion.

**Comment by dlorenc** [comment]
Hey,

Thanks for the bug report, and for discussing the changes ahead of time. I think both of these fixes would be great to have. Could you explain a little more how you're planning on implementing them?

For the first point, I think it would be tricky to configure the dashboard with minikube's IP because it can change between stop/starts. If it's possible to configure the dashboard to use the current browser hostname that would be great.

Using a static NodePort also seems like a good idea.

Let me know if you need any help making the changes, we'd be happy to have your contribution.

**Comment by rdsubhas** [comment]
Great! I'll then dig in to see how this can be implemented and report back...

**Comment by dlorenc** [comment]
Cool. I'd suggest starting here: https://github.com/kubernetes/minikube/tree/master/deploy/addons

**Comment by dlorenc** [comment]
Hey, have you had a chance to take a look at this yet? I don't mind making the changes, but don't want to step on your toes if you're working on this :)

**Comment by rdsubhas** [comment]
@dlorenc Sorry for the radio silence, I have raised a PR and set the port tentatively as `30000` (have to pick one in the nodePort range), please have a look and I'll follow up on the dashboard which is more complicated than I initially thought

**Comment by dlorenc** [comment]
Thanks for the first PR. Let me know if you have any ideas about the second one, or if I can help at all!

**Comment by rdsubhas** [comment]
Yep, just went through k8s/dashboard. The latest dashboard `v1.1.0-beta3` has quite a lot of UI changes. [This commit](https://github.com/kubernetes/dashboard/commit/6cc2410eea552f729484123dce9d23be0e591b3a) has now made only LoadBalancer Ingress endpoints as clickable external links, so the old nodePorts and localhost links are no longer present. This changes not only the dashboard service but also other application services.

Some options are:
- Add `externalIPs` as the VM IP to services. This works and shows a clickable link, but not possible to keep this up-to-date for every service as VM IP changes
- Implement an [Ingress Controller](https://github.com/kubernetes/contrib/tree/master/ingress/controllers) in minikube which always uses to the machine IP. Then all services defined as LoadBalancer will get a clickable link. This probably won't be a small change though.

Those are the two I know of, please let me know if I missed anything, or if there is any other way to probe...

**Comment by dlorenc** [comment]
Thanks for digging, and explaining those two options. I like the idea of an Ingress Controller, but I think that might fit in more closely with the work we're tracking in #198. Any thoughts there?

**Comment by dlorenc** [comment]
I'm going to close this for now. We got the low-hanging fruit.
