### ISSUE TITLE
minikube installation error 

### ISSUE THREAD

**Issue by sayedabdein00** [kubernetes/minikube#18526]
* Creating hyperv VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
E0328 11:45:11.931573   44452 main.go:137] libmachine: [stderr =====>] : Hyper-V\Get-VMSwitch : Hyper-V 
encountered an error trying to access an object on computer 'DESKTOP-99VD6NN' because 
the object was not found. The object might have been deleted. Verify that the Virtual Machine Management 
service on 
the computer is running.
At line:1 char:69
+ ...  [Text.Encoding]::UTF8; ConvertTo-Json @(Hyper-V\Get-VMSwitch|Select  ...
+                                              ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMSwitch
 
* Failed to start hyperv VM. Running "minikube delete" may fix it: recreate: creating host: create: 
precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this command 
to run. Check https://docs.docker.com/machine/drivers/hyper-v/

X Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: recreate: creating host: 
create: precreate: no External vswitch nor Default Switch found. A valid vswitch must be available for this 
command to run. Check https://docs.docker.com/machine/drivers/hyper-v/
* 
â•â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â
”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â
”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®
â”‚                                                                                             â”‚
â”‚    * If the above advice does not help, please let us know:                                 â”‚
â”‚      https://github.com/kubernetes/minikube/issues/new/choose                               â”‚
â”‚                                                                                             â”‚
â”‚    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    â”‚
â”‚                                                                                             â”‚
â•°â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•¯

**Comment by T-Lakshmi** [comment]
Which operating system you are using?
issue seems not with minikube, its with hyper-v.

**Comment by spowelljr** [comment]
Hi @sayedabdein00, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
