### ISSUE TITLE
unable to start minikube and run kubectl get pods

### ISSUE THREAD

**Issue by amit60829** [kubernetes/minikube#18537]
### What Happened?

E0329 13:24:24.389646   14251 logs.go:195] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.28.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.28.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
E0329 07:54:24.380010   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
E0329 07:54:24.380668   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
E0329 07:54:24.382607   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
E0329 07:54:24.383215   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
E0329 07:54:24.384987   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nE0329 07:54:24.380010   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nE0329 07:54:24.380668   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nE0329 07:54:24.382607   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nE0329 07:54:24.383215   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nE0329 07:54:24.384987   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodesE0329 13:24:24.389646   14251 logs.go:195] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.28.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.28.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
E0329 07:54:24.380010   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
E0329 07:54:24.380668   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
E0329 07:54:24.382607   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
E0329 07:54:24.383215   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
E0329 07:54:24.384987   21253 memcache.go:265] couldn't get current server API group list: Get "https://localhost:8443/api?timeout=32s": dial tcp 127.0.0.1:8443: connect: connection refused
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nE0329 07:54:24.380010   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nE0329 07:54:24.380668   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nE0329 07:54:24.382607   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nE0329 07:54:24.383215   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nE0329 07:54:24.384987   21253 memcache.go:265] couldn't get current server API group list: Get \"https://localhost:8443/api?timeout=32s\": dial tcp 127.0.0.1:8443: connect: connection refused\nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

### Attach the log file

E0329 13:24:54.482990   14295 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:58310/api?timeout=32s": EOF
E0329 13:25:04.498855   14295 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:58310/api?timeout=32s": EOF
E0329 13:25:14.527849   14295 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:58310/api?timeout=32s": EOF
E0329 13:25:24.545217   14295 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:58310/api?timeout=32s": EOF
E0329 13:25:34.559277   14295 memcache.go:265] couldn't get current server API group list: Get "https://127.0.0.1:58310/api?timeout=32s": EOF
Unable to connect to the server: EOF

### Operating System

Ubuntu

### Driver

None

**Comment by Ritikaa96** [comment]
In case of support queries please try StackOverflow, k8s slack channel and k8s Discussion threads. you will definitely find a solution.
