### ISSUE TITLE
Starting localkube fails locally because of missing configuration file

### ISSUE THREAD

**Issue by thedrow** [kubernetes/minikube#1855]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

Please provide the following details:

**Environment**: Linux

**Minikube version** (use `minikube version`): 0.21.0
- **OS** (e.g. from /etc/os-release): 16.04.3 LTS (Xenial Xerus)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): 0.23.0
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

**What happened**:
localkube failed to boot on my machine.
**What you expected to happen**:
localkube should boot and allow me to experiment with running k8s on my machine without a VM.

**How to reproduce it** (as minimally and precisely as possible):
Run
```
sudo docker run -d --volume=/:/rootfs:ro     --volume=/sys:/sys:rw     --volume=/var/lib/docker:/var/lib/docker:rw     --volume=/var/lib/kubelet:/var/lib/kubelet:rw     --volume=/var/run:/var/run:rw     --net=host     --pid=host     --privileged gcr.io/k8s-minikube/localkube-image:v1.7.3  /localkube start     --apiserver-insecure-address=0.0.0.0     --apiserver-insecure-port=8080     --logtostderr=true     --containerized
```
and inspect the logs
**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
The log contains the following error:
```
kubelet: Exit with error: failed to run Kubelet: invalid kubeconfig: stat /var/lib/localkube/kubeconfig: no such file or directory
```
Either there's a documentation bug in https://github.com/kubernetes/minikube/blob/master/deploy/docker/README.md or the localkube container should generate a default configuration somehow.

**Comment by r2d4** [comment]
This documentation needs to be updated since we've turned off insecure serving in localkube.  You'll need to mount in the kubeconfig and access on the secure serving port.  

I'll also open an issue to remove the    
```
 --apiserver-insecure-address=0.0.0.0 \
    --apiserver-insecure-port=8080 \
```

flags since they don't actually work anymore.
