### ISSUE TITLE
PR 1836 reverted vendor change of PR 1798

### ISSUE THREAD

**Issue by huguesalary** [kubernetes/minikube#1856]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

PR #1836 just canceled PR #1798

That is, PR #1798 updated the vendored `github.com/spf13/viper` from revision `7fb2782df3d83e0036cc89f461ed0422628776f4` to `25b30aa063fc18e48662b86996252eabdcf2f0c7`, to fix a bug reported in #1797

PR #1836 just reverted back to `7fb2782df3d83e0036cc89f461ed0422628776f4`

**Comment by r2d4** [comment]
Sorry I'll handle this.  I probably just didn't update before I sent that PR

**Comment by huguesalary** [comment]
Great, thanks!
