### ISSUE TITLE
Exiting due to GUEST_STATUS: Unable to get machine status: state: unknown state "minikube": docker container inspect minikube --format=<no value>: exit status 1

### ISSUE THREAD

**Issue by kevinrose42** [kubernetes/minikube#18568]
### What Happened?

I am following the tutorial here https://kubernetes.io/docs/tutorials/hello-minikube/ and when I get to the second step that says I need to run ```minikube dashboard``` it fails with:

```
$ minikube dashboard

❌  Exiting due to GUEST_STATUS: Unable to get machine status: state: unknown state "minikube": docker container inspect minikube --format=<no value>: exit status 1
stdout:


stderr:
permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/minikube/json": dial unix /var/run/docker.sock: connect: permission denied


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_dashboard_423420bd4a94feb40269b0c3b84c60fefec29f14_0.log               │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

```

I then tried to run ```minikube logs --file=logs.txt``` and that failed with the same error so I am unable to provide logs.

I can however provide minikube_dashboard_423420bd4a94feb40269b0c3b84c60fefec29f14_0.log if that helps.
[minikube_dashboard_423420bd4a94feb40269b0c3b84c60fefec29f14_0.log](https://github.com/kubernetes/minikube/files/14858774/minikube_dashboard_423420bd4a94feb40269b0c3b84c60fefec29f14_0.log)

### Attach the log file

[minikube_dashboard_423420bd4a94feb40269b0c3b84c60fefec29f14_0.log](https://github.com/kubernetes/minikube/files/14858778/minikube_dashboard_423420bd4a94feb40269b0c3b84c60fefec29f14_0.log)

### Operating System

Ubuntu

### Driver

Docker

**Comment by kevinrose42** [comment]
Hmmmm, well I "fixed" it.  I rebooted my Ubuntu machine and now it works, so fixed?

**Comment by T-Lakshmi** [comment]
@kevinrose42,

> permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/containers/minikube/json": dial unix /var/run/docker.sock: connect: permission denied

Seems you don't have permissions to access the docker daemon, Is your docker working with non-root user(without sudo)?
 if not, could you please follow [these instructions](https://docs.docker.com/engine/install/linux-postinstall/) to run docker without sudo?
 i hope his should fix the minikube dashboard issue as per logs.

**Comment by T-Lakshmi** [comment]
@kevinrose42,

> Hmmmm, well I "fixed" it. I rebooted my Ubuntu machine and now it works, so fixed?

I am assuming your issue has been resolved and closing the issue. Feel free to reopen if you still facing the issue.
