### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by DeadLoss1801** [kubernetes/minikube#18589]
### What Happened?

Exiting due to SVC_UNREACHABLE: service not available: no running pod for service mongo-express-service found

### Attach the log file

[Uploading logs.txt…]()

### Operating System

windows

### Driver

docker

**Comment by Ritikaa96** [comment]
I can't see any log file
/kind support

**Comment by Ritikaa96** [comment]
/triage duplicate 
Check https://github.com/kubernetes/minikube/issues/18495 for explaination

**Comment by DeadLoss1801** [comment]
[logs.txt](https://github.com/kubernetes/minikube/files/14915512/logs.txt)

**Comment by Ritikaa96** [comment]
I found this one error there : 
>>> Error reading config file at C:\Users\91902\.minikube\config\config.json: open C:\Users\91902\.minikube\config\config.json: The system cannot find the path specified.
Please make sure the folder and file is there and all the content is right

**Comment by spowelljr** [comment]
Hi @DeadLoss1801, could you show the commands you run after starting the minikube cluster that resulted in your running into this issue?
