### ISSUE TITLE
"minikube start" does not work on an old, old, old Macbook Air

### ISSUE THREAD

**Issue by jbla62** [kubernetes/minikube#18590]
### What Happened?

MacOS: 10.15.7
MacBook Air (13 Zoll, Mitte 2012)
VirtualBox: 7.0.14

During start the message "Host-only adapters are no longer supported".
When I change the second interface to "Host-only network" within VirtualBox it will be changed back to "Host-only adapter" during the next "minikube start".

The appended file "startup_log.txt" has been created with "minikube start --alsologtostderr > startup_log.txt 2>&1"

jbla@Johannes-Air ~ % minikube start
😄  minikube v1.32.0 auf Darwin 10.15.7
✨  Verwende den Treiber virtualbox basierend auf dem existierenden Profil
👍  Starte Control Plane Node minikube in Cluster minikube
🔄  Starte existierenden virtualbox VM für "minikube" ...
🤦  StartHost fehlgeschlagen, aber es wird noch einmal versucht: driver start: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: Host-only adapters are no longer supported!
VBoxManage: error: For your convenience a host-only network named 'Legacy vboxnet0 Network' has been created with network mask '255.255.255.0' and IP address range '192.168.59.100' - '192.168.59.254'.
VBoxManage: error: To fix this problem, switch to 'Host-only Network' attachment type in the VM settings.
VBoxManage: error:  (VERR_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.291699 VBoxHeadless: exiting
🔄  Starte existierenden virtualbox VM für "minikube" ...
😿  Start von virtualbox VM fehlgeschlagen. Das Ausführen von "minikube delete" könnte des Beheben: driver start: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: Host-only adapters are no longer supported!
VBoxManage: error: For your convenience a host-only network named 'Legacy vboxnet0 Network' has been created with network mask '255.255.255.0' and IP address range '192.168.59.100' - '192.168.59.254'.
VBoxManage: error: To fix this problem, switch to 'Host-only Network' attachment type in the VM settings.
VBoxManage: error:  (VERR_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.297488 VBoxHeadless: exiting

❌  Terminiere aufgrund von PR_VBOX_BLOCKED: Failed to start host: driver start: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: Host-only adapters are no longer supported!
VBoxManage: error: For your convenience a host-only network named 'Legacy vboxnet0 Network' has been created with network mask '255.255.255.0' and IP address range '192.168.59.100' - '192.168.59.254'.
VBoxManage: error: To fix this problem, switch to 'Host-only Network' attachment type in the VM settings.
VBoxManage: error:  (VERR_NOT_FOUND)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.297488 VBoxHeadless: exiting
💡  Vorschlag: Installieren Sie Virtualbox neu und verifizieren Sie, dass es nicht blockiert wurde: System Preferences -> Security & Privacy -> General -> Einige System-Software konnte nicht geladen werden
🍿  Verwandtes Issue: https://github.com/kubernetes/minikube/issues/4107

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/14897080/log.txt)
[startup_log.txt](https://github.com/kubernetes/minikube/files/14897081/startup_log.txt)

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by jbla62** [comment]
![Bildschirmfoto 2024-04-07 um 13 20 18](https://github.com/kubernetes/minikube/assets/159790568/a7f5767f-9dfc-4efb-a5cc-1783cef2cd48)

And I'm not shure if this is not a kind of mobbing. ;-)

**Comment by afbjorklund** [comment]
A known issue, unfortunately.

* https://github.com/machine-drivers/machine/issues/38

**Comment by jbla62** [comment]
Thank you very much! I didn't look for MacOS 13. I will use QEMU.

**Comment by jbla62** [comment]
Closed because it's a duplicate.
