### ISSUE TITLE
Minikube v1.32.0 does not run on OSX Sonoma v14.4.1

### ISSUE THREAD

**Issue by shaunster666** [kubernetes/minikube#18613]
minikube start yields this error:

“minikube” can’t be opened because Apple cannot check it for malicious software.

**Comment by Ci7rix** [comment]
You have to remove the quarantine flag by running : `sudo xattr -r -d com.apple.quarantine /path/to/minikube`

**Comment by shaunster666** [comment]
Many thanks!
Shaun


Sent from Yahoo Mail for iPhone


On Saturday, April 20, 2024, 7:54 AM, Max ***@***.***> wrote:




You have to remove the quarantine flag by running : sudo xattr -r -d com.apple.quarantine /path/to/minikube
