### ISSUE TITLE
error with enabling ingress on minikube

### ISSUE THREAD

**Issue by AjayKumar5000** [kubernetes/minikube#18633]
### What Happened?

After running command " minikube addons enable ingress" i'm getting below error 
Exiting due to MK_ADDON_ENABLE: enable failed: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: context deadline exceeded]
*

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/14965373/logs.txt)
[minikube_addons_f229260beb9d81c81fc02ad297432f98de5063c5_0.log](https://github.com/kubernetes/minikube/files/14965374/minikube_addons_f229260beb9d81c81fc02ad297432f98de5063c5_0.log)

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by kundan2707** [comment]
duplicate of #16828

**Comment by kundan2707** [comment]
closing as duplicate of #16828
