### ISSUE TITLE
Document the None driver

### ISSUE THREAD

**Issue by thedrow** [kubernetes/minikube#1864]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

**What happened**:
It took me ages and a repeated questions in kubernetes slack channel to find that there is a possibility to run minikube without a VM.

**What you expected to happen**:
I expected to find these details in the documentation and README file

**How to reproduce it** (as minimally and precisely as possible):
N/A
**Output of `minikube logs` (if applicable)**:
N/A
**Anything else do we need to know**:
Nope

**Comment by aaron-prindle** [comment]
Sorry about , not all of the driver documentation was updated.  Thanks for pointing this out, I have submitted a PR to update the docs.
