### ISSUE TITLE
Fail to startup minikube with virtualbox 

### ISSUE THREAD

**Issue by gmollema** [kubernetes/minikube#18652]
Hi I am trying to start minikube on my windows machine with virtualbox (7.0.16).

Can you please help, this is the log of the startup:

00:00:07.911947 VirtualBox VM 7.0.16 r162802 win.amd64 (Apr 12 2024 19:02:49) release log
00:00:07.911949 Log opened 2024-04-17T11:24:42.952861200Z
00:00:07.911949 Build Type: release
00:00:07.911953 OS Product: Windows 11
00:00:07.911954 OS Release: 10.0.22621
00:00:07.911954 OS Service Pack: 
00:00:08.221156 Firmware type: UEFI
00:00:08.222531 Secure Boot: VERR_PRIVILEGE_NOT_HELD
00:00:08.222610 Host RAM: 32502MB (31.7GB) total, 18886MB (18.4GB) available
00:00:08.222618 Executable: C:\Program Files\Oracle\VirtualBox\VirtualBoxVM.exe
00:00:08.222620 Process ID: 26812
00:00:08.222622 Package type: WINDOWS_64BITS_GENERIC
00:00:08.226456 Installed Extension Packs:
00:00:08.226541   None installed!
00:00:08.228718 Console: Machine state changed to 'Starting'
00:00:08.230676 Qt version: 5.15.2
00:00:08.246099 GUI: UIMediumEnumerator: Medium-enumeration finished!
00:00:08.273842 GUI: UIMediumEnumerator: Medium-enumeration finished!
00:00:08.339935 SUP: seg #0: R   0x00000000 LB 0x00001000
00:00:08.339946 SUP: seg #1: R X 0x00001000 LB 0x00179000
00:00:08.339950 SUP: seg #2: R   0x0017a000 LB 0x00051000
00:00:08.339953 SUP: seg #3: RW  0x001cb000 LB 0x00013000
00:00:08.339956 SUP: seg #4: R   0x001de000 LB 0x00011000
00:00:08.339959 SUP: seg #5: RW  0x001ef000 LB 0x00004000
00:00:08.339962 SUP: seg #6: R   0x001f3000 LB 0x00010000
00:00:08.339965 SUP: seg #7: R X 0x00203000 LB 0x00002000
00:00:08.339968 SUP: seg #8: R   0x00205000 LB 0x00007000
00:00:08.341876 SUP: Loaded VMMR0.r0 (C:\Program Files\Oracle\VirtualBox/VMMR0.r0) at 0xXXXXXXXXXXXXXXXX - ModuleInit at XXXXXXXXXXXXXXXX and ModuleTerm at XXXXXXXXXXXXXXXX using the native ring-0 loader
00:00:08.341907 SUP: VMMR0EntryEx located at XXXXXXXXXXXXXXXX and VMMR0EntryFast at XXXXXXXXXXXXXXXX
00:00:08.341910 SUP: windbg> .reload /f C:\Program Files\Oracle\VirtualBox/VMMR0.r0=0xXXXXXXXXXXXXXXXX
00:00:08.351265 Guest OS type: 'Linux26_64'
00:00:08.351871 fHMForced=true - No raw-mode support in this build!
00:00:08.354522 File system of 'C:\Users\Gijs\.minikube\machines\minikube\boot2docker.iso' (DVD) is ntfs
00:00:08.355683 File system of 'C:\Users\Gijs\.minikube\machines\minikube\disk.vmdk' is ntfs
00:00:08.704083 supR3HardenedErrorV: supR3HardenedScreenImage/LdrLoadDll: rc=VERR_LDRVI_NOT_SIGNED fImage=1 fProtect=0x0 fAccess=0x0 \Device\HarddiskVolume3\Windows\System32\NetSetupShim.dll: Not signed.
00:00:08.704171 supR3HardenedErrorV: supR3HardenedMonitor_LdrLoadDll: rejecting 'C:\Windows\System32\NetSetupShim.dll' (C:\Windows\System32\NetSetupShim.dll): rcNt=0xc0000190
00:00:08.704205 NetworkAttachmentType_HostOnly: Failed to get NetCfg, hrc=ERROR_TRUST_FAILURE/0x800706fe (0x800706fe)
00:00:08.704225 AssertLogRel D:\tinderboxa\win-7.0\src\VBox\Main\src-client\ConsoleImpl2.cpp(6502) int __cdecl Console::i_configNetwork(const char *,unsigned int,unsigned int,struct INetworkAdapter *,struct CFGMNODE *,struct CFGMNODE *,struct CFGMNODE *,bool,bool,struct UVM *,const struct VMMR3VTABLE *): !FAILED(hrc)
00:00:08.704230 hrc=ERROR_TRUST_FAILURE/0x800706fe
00:00:08.704608 Constructor failed with rc=VERR_MAIN_CONFIG_CONSTRUCTOR_COM_ERROR pfnCFGMConstructor=00007ff848cfd730
00:00:08.830484 VMSetError: D:\tinderboxa\win-7.0\src\VBox\VMM\VMMR3\VM.cpp(341) int __cdecl VMR3Create(unsigned int,const struct VMM2USERMETHODS *,unsigned __int64,void (__cdecl *)(struct UVM *,void *,int,const char *,unsigned int,const char *,const char *,char *) noexcept,void *,int (__cdecl *)(struct UVM *,struct VM *,const struct VMMR3VTABLE *,void *) noexcept,void *,struct VM **,struct UVM **); rc=VERR_MAIN_CONFIG_CONSTRUCTOR_COM_ERROR
00:00:08.830496 VMSetError: The configuration constructor in main failed due to a COM error. Check the release log of the VM for further details.
00:00:08.831499 ERROR [COM]: aRC=E_FAIL (0x80004005) aIID={6ac83d89-6ee7-4e33-8ae6-b257b2e81be8} aComponent={ConsoleWrap} aText={The configuration constructor in main failed due to a COM error. Check the release log of the VM for further details. (VERR_MAIN_CONFIG_CONSTRUCTOR_COM_ERROR)}, preserve=false aResultDetail=-6400
00:00:08.832300 Console: Machine state changed to 'PoweredOff'
00:00:08.839609 Power up failed (vrc=VERR_MAIN_CONFIG_CONSTRUCTOR_COM_ERROR, hrc=E_FAIL (0X80004005))
00:00:08.844878 GUI: UIMachineViewNormal::resendSizeHint: Restoring guest size-hint for screen 0 to 800x600
00:00:08.844913 ERROR [COM]: aRC=E_ACCESSDENIED (0x80070005) aIID={4680b2de-8690-11e9-b83d-5719e53cf1de} aComponent={DisplayWrap} aText={The console is not powered up (Display::setVideoModeHint)}, preserve=false aResultDetail=0
00:00:08.845187 GUI: Aborting startup due to power up progress issue detected...
00:00:08.860088 supR3HardenedErrorV: supR3HardenedScreenImage/LdrLoadDll: cached rc=VERR_LDRVI_NOT_SIGNED fImage=1 fProtect=0x0 fAccess=0x0 cHits=1 \Device\HarddiskVolume3\Windows\System32\DataExchange.dll
00:00:08.860138 supR3HardenedErrorV: supR3HardenedMonitor_LdrLoadDll: rejecting 'C:\WINDOWS\system32\dataexchange.dll' (C:\WINDOWS\system32\dataexchange.dll): rcNt=0xc0000190
00:00:08.863868 GUI: UICommon: Handling aboutToQuit request..
00:00:09.811739 GUI: UICommon: aboutToQuit request handled!

**Comment by SATHYA-NARAYANA** [comment]
<ul>
  <li>
    <p>I'm experiencing the same issue on my system.</p>
    <blockquote>
      <p>Even though I have sufficient RAM available, my system encountered a blue screen of death. </p>
    </blockquote>

<blockquote>
      <p>Interestingly, reverting back to the previous version of Oracle VirtualBox (7.0.14) resolved the issue for me. </p>
    </blockquote>

<blockquote>
      <p> It seems there might be an issue specific to the newer version of VirtualBox (7.0.16). </p>
    </blockquote>

<blockquote>
      <p> I am also looking forward to a resolution! </p>
    </blockquote>
  </li>
</ul>
