### ISSUE TITLE
taskbar widget/integration?

### ISSUE THREAD

**Issue by chino** [kubernetes/minikube#1866]
FEATURE REQUEST

Taskbar integration similar to what we see in:
- https://github.com/TheNewNormal/kube-solo-osx
- https://docs.docker.com/docker-for-mac/#general

Easy for people to get started, see status, update, change runtime configs, etc.

cc: @aaron-prindle, @eecue

**Comment by eecue** [comment]
I'm going to work on this, but I will only be helpful on the Mac OS side of things.

**Comment by zoidbergwill** [comment]
This and https://github.com/kubernetes/minikube/issues/1706 would be awesome for OSX, but I assume there isn't an easy way to do it for Windows/OSX/KDE/Gnome/et al.

**Comment by r2d4** [comment]
It could be possible to use something like https://github.com/electron/electron to create a cross platform frontend.  

@eecue Do you mind sending a PR with your design?  You can put it somewhere in `./docs/proposals`.  Might be good to agree on scope and design before you start working on it.

**Comment by eecue** [comment]
@r2d4 I will for sure send a PR. Not sure if I would have time to learn Electron

**Comment by r2d4** [comment]
No problem, I think any kind of integration would be welcomed.

**Comment by bcg62** [comment]
+1

**Comment by lc9900** [comment]
+1

**Comment by pgray** [comment]
+1

**Comment by eecue** [comment]
Here's a PR with the proposal @r2d4 https://github.com/kubernetes/minikube/pull/1869
