### ISSUE TITLE
Feature request: Reinitialize localkube without destroying VM.

### ISSUE THREAD

**Issue by joshk0** [kubernetes/minikube#1867]
This is a feature request.

In my Mac environment, I have the following build pattern:
* I start minikube, then populate tons of local images using the docker-env.
* I then start kubernetes pods which use those local images.
* I then want to napalm the state of Kubernetes, so I use minikube delete.
* This ends up trashing my local images too

I would love to have a way to keep my local images while completely resetting localkube to a pristine state. I could delete all the service objects, but that seems less nuclear than i would like.

**Comment by zoidbergwill** [comment]
Are you hoping to even update localkube without losing Docker state?

**Comment by joshk0** [comment]
That would be pretty sweet, but is not a requirement. I understand that the minikube ISO provides more of an appliance environment at this time, and won't want to adhere to promises that old Docker layer stores will always be backwards compatible.

**Comment by francisu** [comment]
@joshk0 don't know if you are responding to @zoidbergwill or the issue in general. +1000 on this issue as it's really a pain to rebuild everything if you have to destroy minikube (which is often the case), especially if you don't have a great network connection. I don't care about backwards compatibility with previous versions of minikube/docker.
