### ISSUE TITLE
kubeadm: Getting error while intialising kubeadm on ubuntu 22.04

### ISSUE THREAD

**Issue by Tanushriyt** [kubernetes/minikube#18694]
### What Happened?

 sudo kubeadm init --control-plane-endpoint=master-node --upload-certs
I0419 11:59:10.007878    8778 version.go:256] remote version is much newer: v1.30.0; falling back to: stable-1.29
[init] Using Kubernetes version: v1.29.4
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
W0419 11:59:10.953034    8778 checks.go:835] detected that the sandbox image "registry.k8s.io/pause:3.8" of the container runtime is inconsistent with that used by kubeadm. It is recommended that using "registry.k8s.io/pause:3.9" as the CRI sandbox image.
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local master-node] and IPs [10.96.0.1 192.168.1.36]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [localhost master-node] and IPs [192.168.1.36 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [localhost master-node] and IPs [192.168.1.36 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "super-admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI.
Here is one example how you may list all running Kubernetes containers by using crictl:
	- 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'crictl --runtime-endpoint unix:///var/run/containerd/containerd.sock logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

The status of kubelet and docker is active(running)
kubelet version is 1.29
there is no kubelet.log file inside /var/log any help?

### Attach the log file

there is no kubelet.log file 

### Operating System

Ubuntu

### Driver

Docker

**Comment by medyagh** [comment]
[Tanushriyt](https://github.com/Tanushriyt) I believe you are running kubeadm yourself?  a better place to ask question would be kubeadm project https://github.com/kubernetes/kubeadm

**Comment by kkshangla** [comment]
Use the following command and it will work
"sudo rm -rf /etc/containerd/config.toml"

**Comment by kkshangla** [comment]
Use the following commands and it will work.
sudo rm -rf /etc/containerd/config.toml
sudo sustemctl restart  containerd
sudo kubeadm init

**Comment by kkshangla** [comment]
Use the following commands and it will work.
sudo rm -rf /etc/containerd/config.toml
sudo systemctl restart containerd
sudo kubeadm init

**Comment by Naseerjamali** [comment]
You will have to comment 'disabled plugins' in /etc/containerd/config.toml and restart the containerd.
Even my kubeadm setup is crashing in Ubuntu 22.04 and 24.04 but works smoothly on 20.04.

**Comment by afbjorklund** [comment]
This is not a minikube issue, and it is already covered in the kubeadm documentation:

https://kubernetes.io/docs/setup/production-environment/container-runtimes/#containerd
