### ISSUE TITLE
Getting Error while trying to install minikube in windows 11 machine <! This VM is having trouble accessing https://registry.k8s.io>

### ISSUE THREAD

**Issue by KULDEEP-1234** [kubernetes/minikube#18713]
### What Happened?

[DxDiag.txt](https://github.com/kubernetes/minikube/files/15062375/DxDiag.txt)
[logs.txt](https://github.com/kubernetes/minikube/files/15062377/logs.txt)
[minikube_update-context_207303b36b811ceed1ea5ebfb776ec1b71682951_0.log](https://github.com/kubernetes/minikube/files/15062378/minikube_update-context_207303b36b811ceed1ea5ebfb776ec1b71682951_0.log)

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15062391/logs.txt)

### Operating System

Windows

### Driver

VirtualBox

**Comment by KULDEEP-1234** [comment]
Please help

**Comment by llegolas** [comment]
might be related to  https://github.com/kubernetes/minikube/issues/18705
