### ISSUE TITLE
Ingress DNS documentation lacks instruction for Linux OS systemd-resolved (relevant to Ubuntu)

### ISSUE THREAD

**Issue by gpelouze** [kubernetes/minikube#18727]
The [Ingress DNS documentation](https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/) has instruction for adding the `minikube ip` as a DNS server ("Installlation", step 3). Under the Linux tab, it provides instructions to do so for systems using `resolvconf` and `Network Manager`, but not [`systemd-resolved`](https://manpages.ubuntu.com/manpages/bionic/man8/systemd-resolved.service.8.html). This is relevant because it seems to be used by Ubuntu>=22.04 (`/etc/resolv.conf` starts with `# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).`)

On systems using `systemd-resolved`, the minikube IP can be added by running:

```shell
sudo mkdir /etc/systemd/resolved.conf.d
sudo tee /etc/systemd/resolved.conf.d/minikube.conf << EOF
[Resolve]
DNS=$(minikube ip)
Domains=~test
EOF
sudo systemctl restart systemd-resolved
```

I propose to create a PR to add this to the documentation.

**Comment by cirix** [comment]
Bare in mind that will not work for for everyone, for example on MacOSX you need to create a resolver for the domain you want. On top I think configuring the systemd-resolve tool to add entries is straightforward. I think what requires update is the fact that still it's referencing on the documentation to edit /etc/resolve.conf and in no *nix based system that file is now self managed. Is automatically generated. That needs to be maybe remarked.

**Comment by llegolas** [comment]
you need to restart systemd-resolved after that . 
But there are few (wrong) assumptions here. 
Firstly it assumes that minikube is running at the time systemd-resolved is (re)started and secondly it assumes that `$(minikube ip)` will fetch the IP of your instance without knowing which user you might be.

**Comment by medyagh** [comment]
if this step is required for the linux users, we should consider to add this to the Addon itself, to add this step automatically

**Comment by gpelouze** [comment]
@medyagh: this step is not required for all linux users, but depends on the system's DNS configuration. Here are the steps one should follow to address step 3 "Add the `minikube ip` as a DNS server" on any Linux distribution:

1. Determine the DNS setup. This can usually be done by looking at the first lines of `/etc/resolv.conf`. I know of three options (there might be more):
  - mentions resolvconf → use instructions "Linux OS with resolvconf" from the current Ingress DNS documentation
  - `# Generated by NetworkManager` → use instructions "Linux OS with Network Manager" from the current doc
  - `# This is /run/systemd/resolve/stub-resolv.conf managed by man:systemd-resolved(8).` → use instructions "Linux OS with systemd-resolved" from the linked PR. 
2. Start minikube (thanks @llegolas for identifying that it is missing from the doc)
3. Follow the instructions from the appropriate section

The current documentation does not explain clearly that one needs (1) to identify the DNS config, and (2) only apply the instructions for this config. Editing the `resolvconf` file is probably 

Automation sounds difficult and risk having unexpected consequences, as it would need correctly to handle any possible DNS configuration. (There is a related [TODO](https://github.com/kubernetes/minikube/blob/4ed3c9f7cf8977f56e2e5a126b61b0672b2fd6f0/site/content/en/docs/handbook/addons/ingress-dns.md?plain=1#L272) on the same page.) I think it outside of the scope o this issue. 

I will update the PR with @medyagh's comments and clarify the issues raised above (identify the right setup, and start minikube before applying the modifications).

**Comment by lackita** [comment]
I tried following this documentation, and it ended up meaning nothing _but_ my minikube dns server would resolve:

```
$ nslookup google.com
Server:         127.0.0.53
Address:        127.0.0.53#53
                                     
Non-authoritative answer:        
*** Can't find google.com: No answer
```

Poked around quite a bit in systemd-resolved documentation and couldn't quite figure out what the right settings should be.

**Comment by erindru** [comment]
Same problem as @lackita , following the instructions to add another DNS resolver worked for the Minikube `.test` domain but also broke global DNS resolution on my system.

Every lookup for normal internet domains would fail the first time and then work the second time. I was unable to figure out how to make `systemd-resolved` ignore the Minikube DNS for anything that didnt end in `.test`.

Using Fedora 40 / systemd-resolved

**Comment by mferretti** [comment]
Same as @lackita  and @erindru here on Ubuntu 24.04.
As long as ingress-dns is disabled everything works fine but as soon as I enable ingress-dns I can't seem to be able to resolve any host except *.test; even image pulling fails.
