### ISSUE TITLE
Kubernetes 101 tutorial does not mention incompatibility with ARM architecture

### ISSUE THREAD

**Issue by lodewijkvankeizerswaard** [kubernetes/minikube#18726]
### What Happened?

I tried to follow the [Kubernetes 101 tutorial](https://minikube.sigs.k8s.io/docs/tutorials/kubernetes_101/) on my Apple Silicon device. The image used in this tutorial, however, is not compatible with ARM architectures. 

The tutorial should make a quick mention of this incompatibility to avoid confusion among new users.

### Attach the log file

(irrelevant)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by lodewijkvankeizerswaard** [comment]
I updated the documentation on [a fork](https://github.com/lodewijkvankeizerswaard/minikube), under the impression that I would be able to create a pull request. However, I cannot.

**Comment by afbjorklund** [comment]
It was updated in the other deployment, unfortunately there is some duplication:

https://kubernetes.io/docs/tutorials/kubernetes-basics/deploy-app/deploy-intro/

The main issue is that the original tutorial image has not been updated in **years**...

```
REPOSITORY                                  TAG       IMAGE ID       CREATED       SIZE
gcr.io/google-samples/kubernetes-bootcamp   v1        8fafd8af70e9   7 years ago   211MB
```

**Comment by lodewijkvankeizerswaard** [comment]
Yes, I found the other deployment. It was what eventually got me on the right track. Thanks for the clarification. 

Although maintaining forks of the same content in parallel is suboptimal, it might still be a good idea to add this note. Do you accept pull requests, or should I consider "this" all I can do for the moment?

**Comment by afbjorklund** [comment]
A warning in the documentation, but better would be to rebuild the image - like we did for the "echoserver".

I'm not sure why they are still using node 6.3.1 instead of upgrading to a later version (currently 20.12.2 lts)

**Comment by afbjorklund** [comment]
@spowelljr : Can the new "bootcamp" image be hosted under `kicbase`, similar to the new echo-server ?

**Comment by spowelljr** [comment]
Sure, when I get a second I'll build and push the a multi arch image and update the tutorial

**Comment by afbjorklund** [comment]
Why are they using different registries ?

docker.io/kicbase/echo-server:1.0

gcr.io/k8s-minikube/kubernetes-bootcamp:v1

```
REPOSITORY                                  TAG           IMAGE ID       CREATED         SIZE
gcr.io/k8s-minikube/kubernetes-bootcamp     v1            5a13c01fb5e6   10 hours ago    246MB
gcr.io/google-samples/kubernetes-bootcamp   v1            8fafd8af70e9   7 years ago     211MB
kicbase/echo-server                         1.0           9056ab77afb8   23 months ago   4.94MB
k8s.gcr.io/echoserver                       1.4           a90209bb39e3   8 years ago     140MB
```

Shouldn't it gravitate towards registry.k8s.io ?

**Comment by spowelljr** [comment]
Adding to registry.k8s.io takes a few more steps but is doable

https://github.com/kubernetes/k8s.io/tree/main/registry.k8s.io#managing-kubernetes-container-registries

**Comment by afbjorklund** [comment]
Maybe that will be done by SIG Docs later, for the website.
