### ISSUE TITLE
minikube start --vm-driver=qemu --network=socket_vmne

### ISSUE THREAD

**Issue by MovingTowardsADream** [kubernetes/minikube#18731]
### What Happened?

minikube start --vm-driver=qemu --network=socket_vmne

Error:
🔎  Verifying Kubernetes components...
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://10.0.2.15:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 10.0.2.15:8443: i/o timeout]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15077163/logs.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by unicoooorn** [comment]
facing the same problem, any updates?
