### ISSUE TITLE
Failed to start minikube on Virtual Box

### ISSUE THREAD

**Issue by SunilKumarhsdev** [kubernetes/minikube#18730]
### What Happened?

PS C:\WINDOWS\system32> minikube start
W0423 17:59:45.371682    8992 main.go:291] Unable to resolve the current Docker CLI context "default": context "default": context not found: open C:\Users\Admin\.docker\contexts\meta\37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f\meta.json: The system cannot find the path specified.
* minikube v1.33.0 on Microsoft Windows 11 Pro 10.0.22631.3447 Build 22631.3447
* Using the virtualbox driver based on existing profile
* Starting "minikube" primary control-plane node in "minikube" cluster
* Updating the running virtualbox "minikube" VM ...
! This VM is having trouble accessing https://registry.k8s.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.30.0 on Docker 26.0.1 ...
! Unable to restart control-plane node(s), will reset cluster: <no value>
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Configuring bridge CNI (Container Networking Interface) ...

X Exiting due to GUEST_START: failed to start node: Failed kubeconfig update: decode kubeconfig from "C:\\Users\\Admin\\.kube\\config": decode data: : yaml: control characters are not allowed
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15076987/logs.txt)

### Operating System

Windows

### Driver

VirtualBox

**Comment by Ritikaa96** [comment]
I guess this https://github.com/kubernetes/minikube/issues/5907 issue discussion can help as the error in log is : 
```bash
decode kubeconfig from "C:\Users\Admin\.kube\config": decode data: : yaml: control characters are not allowed
```

**Comment by Ritikaa96** [comment]
> 

Please look at the comment below and let us know if the issue is resolved or not.
