### ISSUE TITLE
minikube start fails on ppc64le ubuntu 22.04 

### ISSUE THREAD

**Issue by Sapana-Khemkar** [kubernetes/minikube#18761]
### What Happened?

root@dotnet-ubuntu-2204-2:~# minikube start --driver=docker --force
* minikube v1.33.0 on Ubuntu 22.04 (ppc64le)
! minikube skips various validations when --force is supplied; this may lead to unexpected behavior
* Using the docker driver based on user configuration
* The "docker" driver should not be used with root privileges. If you wish to continue as root, use --force.
* If you are running minikube within a VM, consider using --driver=none:
*   https://minikube.sigs.k8s.io/docs/reference/drivers/none/
* Using Docker driver with root privileges
* Starting "minikube" primary control-plane node in "minikube" cluster
* Pulling base image v0.0.43 ...
* Creating docker container (CPUs=2, Memory=4000MB) ...

X Exiting due to RUNTIME_ENABLE: Failed to start container runtime: which crictl: Process exited with status 1
stdout:

stderr:

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/15130640/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by Sapana-Khemkar** [comment]
I updated kicbase dockerfile with below patch and built image on power vm. Used locally build base image using command minikube start --driver=docker --base-image=local/kicbase:latest --force then above issue get fixed.
```
[root@apic-team-vm1 minikube]# git diff
diff --git a/deploy/kicbase/Dockerfile b/deploy/kicbase/Dockerfile
index eb505a362..6877d0408 100644
--- a/deploy/kicbase/Dockerfile
+++ b/deploy/kicbase/Dockerfile
 @@ -195,7 +195,11 @@ RUN export ARCH=$(dpkg --print-architecture | sed 's/ppc64el/ppc64le/') && \
     if [ "$ARCH" != "ppc64le" ]; then \
         clean-install catatonit conmon cri-tools crun; \
     else \
-        clean-install conmon crun; \
+        clean-install conmon crun && \
+        export CRICTL_VERSION="v1.30.0" && \
+        curl -LO https://github.com/kubernetes-sigs/cri-tools/releases/download/$CRICTL_VERSION/crictl-$CRICTL_VERSION-linux-ppc64le.tar.gz && \
+        tar zxvf crictl-$CRICTL_VERSION-linux-ppc64le.tar.gz -C /usr/bin &&\
+        rm -f crictl-$CRICTL_VERSION-linux-ppc64le.tar.gz; \
     fi
```

**Comment by iv1111** [comment]
Hi, @mkumatag. Any way you could review this one? Thanks!
