### ISSUE TITLE
minikube none driver localkube process dying leaves minikube in inconsistent state

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1876]
For the none driver, as localkube is spawned as a binary it can die and minikube is left in an inconsistent state on next reboot.  This is happening to me with more frequency recently, unclear as to why.  Also there is no sign that is has died which could make it confusing for users trying to still interact with the cluster.  Should have better messaging or documentation around this.  we could also look into a daemon to monitor localkube.

**Comment by thedrow** [comment]
Do you mean next machine reboot? Because for me localkube always crashes.
Is this a different bug?
