### ISSUE TITLE
minikube version reports v0.19.0 after downloading v0.21.0

### ISSUE THREAD

**Issue by mattnworb** [kubernetes/minikube#1877]
I noticed after being prompted to download a new version that after installing it, the version reported is still 0.19.0. 

```
$ curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.21.0/minikube-darwin-amd64
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 81.9M  100 81.9M    0     0  18.0M      0  0:00:04  0:00:04 --:--:-- 18.8M

$ minikube version
minikube version: v0.19.0
```

Perhaps v0.21.0 is built with the wrong string, or the Cloud Storage bucket has the wrong object in it?

**Comment by mattnworb** [comment]
The checksum matches the sum from the [v0.21.0 release page](https://github.com/kubernetes/minikube/releases/tag/v0.21.0):

```
$ shasum -a 256 minikube
2a6960cfa2b5aed9fec8d8cbe357fa8f5776761ee5efa3dd26abccc894f4b453  minikube
```

**Comment by r2d4** [comment]
You're probably just using the minikube from your path.  If you try `chmod +x minikube && ./minikube version` it should show that the download is correct.  You'll need to add the downloaded minikube to your path. `chmod +x minikube && sudo mv minikube /usr/local/bin/`

**Comment by mattnworb** [comment]
D'oh, that is exactly it, thanks! A very silly mistake to make 😄
