### ISSUE TITLE
Can't run minikube on Mac M1. failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/6.5.0-10-generic\n", err: exit status 1

### ISSUE THREAD

**Issue by hrvadl** [kubernetes/minikube#18823]
### What Happened?

Hi, team!
Everything was ok, until recently, when it suddenly stopped working. I use Colima on Mac M1 and the docker driver to run minikube cluster. I've already tried to update/downgrade minikube as well as run it with different Kubernetes version. Also, I've tried to reinstall minikube, and recreate colima machine, but I'm still getting following error:

` failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/6.5.0-10-generic\n", err: exit status 1`

Colima machine:
```
❯ colima status
INFO[0000] colima is running using macOS Virtualization.Framework
INFO[0000] arch: aarch64
INFO[0000] runtime: docker
INFO[0000] mountType: virtiofs
INFO[0000] socket: unix:///Users/vadymhrashchenko/.colima/default/docker.sock
```

```
❯ printenv | grep DOCKER
DOCKER_HOST=unix:///Users/vadymhrashchenko/.colima/default/docker.sock
DOCKER_DEFAULT_PLATFORM=linux/amd64

```

```
⛵ minikube () ~
❯ minikube status
minikube
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Configured
```

```
❯ which minikube
/opt/homebrew/bin/minikube
```

<img width="1707" alt="image" src="https://github.com/kubernetes/minikube/assets/93580374/a18705a4-94f0-49c4-adae-1fcf6fa54cf1">

Could someone help me please, or point me in the right direction? Any help is appreciated. Thank you in advance.

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/15231577/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by hrvadl** [comment]
Hmmm, unsetting $DOCKER_DEFAULT_HOST variable helped
`# DOCKER_DEFAULT_PLATFORM=linux/amd64`
But is this really a root cause of issue? Could someone clarify?

**Comment by afbjorklund** [comment]
Setting DOCKER_DEFAULT_PLATFORM was indeed the root cause here.

The failed loading of the kernel modules message is probably unrelated.
