### ISSUE TITLE
Bug: Typo in the survey linked in releases

### ISSUE THREAD

**Issue by popey** [kubernetes/minikube#18824]
### What Happened?

👋 

The releases pages links to a survey: **"📣😀 Please fill out our [fast 5-question survey](https://forms.gle/Gg3hG5ZySw8c1C24A) so that we can learn how & why you use minikube, and what improvements we should make. Thank you! 💃🎉"**

If you click through to the survey, you'll notice the last question on the survey is:

"(Optional) If you would like a to be in touch, Please leave your email"

This makes no grammatical sense. Maybe a word was left out.

Perhaps:

"(Optional) If you would like an expert/consultant/sales-person to get in touch, please leave your email" maybe?

🙏 

### Attach the log file

N/A

### Operating System

macOS (Default)

### Driver

N/A

**Comment by xcarolan** [comment]
/unassign
This form is part of google docs and not in this respository.
