### ISSUE TITLE
CHANGE_MINIKUBE_NONE_USER=true has no effect

### ISSUE THREAD

**Issue by thedrow** [kubernetes/minikube#1883]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.21.0
- **OS** (e.g. from /etc/os-release): Ubuntu 17.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): None
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): N/A
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
Both `~/.minikube` and '~/.kube` and all the files under them are still owned by root

**What you expected to happen**:
I expected localkube to boot correctly on my machine with no permission issues when setting the CHANGE_MINIKUBE_NONE_USER correctly.

**How to reproduce it** (as minimally and precisely as possible):
export CHANGE_MINIKUBE_NONE_USER=true; sudo minikube start --vm-driver none;

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by r2d4** [comment]
I think you need to run `sudo -E` for sudo to capture your user env vars.

` -E, --preserve-env          preserve user environment when running command`

**Comment by thedrow** [comment]
Oh right. That's not very obvious. Why are we using an environment variable?
It'd be much more user friendly to provide a flag.

**Comment by thedrow** [comment]
See #1893
