### ISSUE TITLE
Coursera Project Error while executing sudo minikube start --vm-driver=none 

### ISSUE THREAD

**Issue by sunilkp1** [kubernetes/minikube#18876]
sudo minikube start --vm-driver=none
😄  minikube v1.2.0 on linux (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing none VM for "minikube" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 19.03.6
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 

💣  Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by spowelljr** [comment]
Hi @sunilkp1, it seems Coursera is using/recommending an extremely old version of minikube (v1.2.0). I'd recommend opening an issue with them to update the version of minikube to our latest release (v1.33.0). Feel free to install the latest version yourself by following our install instructions: https://minikube.sigs.k8s.io/docs/start/

**Comment by spowelljr** [comment]
Hi @sunilkp1, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
