### ISSUE TITLE
Error getting json from minikube version url

### ISSUE THREAD

**Issue by thedrow** [kubernetes/minikube#1887]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): 0.21
- **OS** (e.g. from /etc/os-release): Ubuntu 17.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): None
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

**What happened**:
minikube produces the following error:
```
E0825 10:50:46.379576   30549 notify.go:54] Error getting json from minikube version url: Error getting minikube version url via http: Get https://storage.googleapis.com/minikube/releases.json: dial tcp 172.217.16.176:443: getsockopt: connection refused
```
The file is accessible through the browser.

The error is misleading since the problem is with the driver name.

**What you expected to happen**:
The error "Invalid driver name" should be printed out to stderr.

**How to reproduce it** (as minimally and precisely as possible):
`sudo -E minikube start --vm-driver noneminikube version`

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by aaron-prindle** [comment]
We should validate flag args as well as positional arguments here.  This should return an error that the command is invalid.  We could use: https://github.com/spf13/cobra#positional-and-custom-arguments for this

**Comment by r2d4** [comment]
@thedrow is this still happening in 0.24.1?

**Comment by thedrow** [comment]
Now when I type the same command I did it simply starts a new local cluster.
The behavior is different but the result is still invalid. The command should error.
