### ISSUE TITLE
How Do You Set the QEMU Driver Flags From Minikube

### ISSUE THREAD

**Issue by Dala0** [kubernetes/minikube#18895]
### What Happened?

I am trying to get Minikube to start up a QEMU based x86 emulator on an ARM CPU under macOS.

It would be useful to access flags such as 'qemu-program', 'qemu-machine', and 'qemu-cpu'. I have been unable to work out how to do this from 'minikube start'.

1. Is 'minikube start' the correct place to set these flags? If so, what is the syntax?
2. If 'minikube start' is not the correct place to set the flags, where do you set them?

@afbjorklund
            

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/15321310/log.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by spowelljr** [comment]
Hi @Dala0, currently those fields are not configurable in minikube, they are automatically depending on the architecture of the machine. However allowing those field to be configurable on start using flags would be a good feature addition.

**Comment by spowelljr** [comment]
I created a quick 10 minute implementation: https://github.com/kubernetes/minikube/pull/18906

**Comment by nnzv** [comment]
Looking forward to seeing the new features in the next release.

**Comment by Dala0** [comment]
Wow, that was quick! Thank you.

@spowelljr

**Comment by afbjorklund** [comment]
Using the docker driver and qemu-user is faster:

* #16530

But hopefully there will "soon" be a new tutorial:

* #18726

**Comment by medyagh** [comment]
> > It would be useful to access flags such as 'qemu-program', 'qemu-machine', and 'qemu-cpu'. I have been unable to work out how to do this from 'minikube start'.
> 
> The flags are only available in `docker-machine`, minikube hardcodes all config in the driver "registry" - no plugins
> 
> > I am trying to get Minikube to start up a QEMU based x86 emulator on an ARM CPU under macOS.
> 
> This is not something that is supported in minikube, since it is too slow to run Kubernetes under emulation

@afbjorklund does that mean we need to modify the minikube-machine org code?

**Comment by afbjorklund** [comment]
> does that mean we need to modify the minikube-machine org code?

Not really, minikube has its own fork of all the drivers (e.g. "qemu2")

So there are different ways of setting the Config, whether Flags or not

https://github.com/minikube-machine/machine/blob/main/drivers/qemu/qemu.go#L199

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/registry/drvs/qemu2/qemu2.go#L117

**Comment by spowelljr** [comment]
@Dala0 @nnzv Sorry, just getting back to this now, you can test this out by downloading the following binary, let me know if it works for you.

https://storage.googleapis.com/minikube-builds/18906/minikube-darwin-arm64
