### ISSUE TITLE
Remove broken homebrew upgrade script from release script

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#18936]
### What Happened?

the current script is in jenkins and it fails and causes confusions

to prevent issues like this
https://github.com/kubernetes/minikube/issues/18923

**Comment by spowelljr** [comment]
Here's the link to the existing homebrew script

https://github.com/kubernetes/minikube/blob/master/hack/jenkins/release_update_brew.sh

**Comment by spowelljr** [comment]
After looking into it Homebrew itself creates the PR, looks like it's watching for new tags.

https://github.com/Homebrew/homebrew-core/pull/171593

**Comment by medyagh** [comment]
@xcarolan is this something you would be interested in ?

**Comment by xcarolan** [comment]
I'll take a look
/assign

**Comment by spowelljr** [comment]
As noted in https://github.com/kubernetes/minikube/issues/18936#issuecomment-2121160869, it looks like brew detects changes and auto creates update PRs, I don't think we need to do this.

**Comment by xcarolan** [comment]
No need to do this this as homebrew has this autromated

**Comment by spowelljr** [comment]
It'll reopen this, the broken homebrew script should still be removed from the release script.
