### ISSUE TITLE
the flake bot commenter should be more helpful

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#18937]
### What Happened?

currently the commenter if there too many tests in one environment lets say qemu tests all failed, it will spam the table and it will be hard to see Other Enviroments

Example
These are the flake rates of all failed tests.
|Environment|Failed Tests|Flake Rate (%)|
|---|---|---|
|[KVM_Linux_crio](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=KVM_Linux_crio)|TestAddons/parallel/Registry ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/KVM_Linux_crio.html#fail_TestAddons/parallel/Registry))|0.00 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=KVM_Linux_crio&test=TestAddons/parallel/Registry))|
|[KVM_Linux_crio](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=KVM_Linux_crio)|TestFunctional/parallel/ImageCommands/ImageLoadFromFile ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/KVM_Linux_crio.html#fail_TestFunctional/parallel/ImageCommands/ImageLoadFromFile))|4.58 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=KVM_Linux_crio&test=TestFunctional/parallel/ImageCommands/ImageLoadFromFile))|
|[Hyper-V_Windows](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=Hyper-V_Windows)|TestDockerFlags ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/Hyper-V_Windows.html#fail_TestDockerFlags))|4.82 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=Hyper-V_Windows&test=TestDockerFlags))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/CertSync ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/CertSync))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/CertSync))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/CpCmd ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/CpCmd))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/CpCmd))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/DashboardCmd ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/DashboardCmd))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/DashboardCmd))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/DockerEnv/bash ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/DockerEnv/bash))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/DockerEnv/bash))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/FileSync ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/FileSync))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/FileSync))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageBuild ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageBuild))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageBuild))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageListJson ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageListJson))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageListJson))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageListShort ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageListShort))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageListShort))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageListTable ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageListTable))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageListTable))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageListYaml ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageListYaml))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageListYaml))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageLoadDaemon ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageLoadDaemon))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageLoadDaemon))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageLoadFromFile ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageLoadFromFile))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageLoadFromFile))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageReloadDaemon ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageReloadDaemon))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageReloadDaemon))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageSaveToFile ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageSaveToFile))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageSaveToFile))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ImageCommands/ImageTagAndLoadDaemon ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ImageCommands/ImageTagAndLoadDaemon))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ImageCommands/ImageTagAndLoadDaemon))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/NodeLabels ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/NodeLabels))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/NodeLabels))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/NonActiveRuntimeDisabled ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/NonActiveRuntimeDisabled))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/NonActiveRuntimeDisabled))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/PersistentVolumeClaim ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/PersistentVolumeClaim))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/PersistentVolumeClaim))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ServiceCmd/DeployApp ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ServiceCmd/DeployApp))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ServiceCmd/DeployApp))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ServiceCmd/Format ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ServiceCmd/Format))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ServiceCmd/Format))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ServiceCmd/HTTPS ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ServiceCmd/HTTPS))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ServiceCmd/HTTPS))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ServiceCmd/JSONOutput ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ServiceCmd/JSONOutput))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ServiceCmd/JSONOutput))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ServiceCmd/List ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ServiceCmd/List))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ServiceCmd/List))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/ServiceCmd/URL ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/ServiceCmd/URL))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/ServiceCmd/URL))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/SSHCmd ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/SSHCmd))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/SSHCmd))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/StatusCmd ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/StatusCmd))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/StatusCmd))|
|[QEMU_macOS](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS)|TestFunctional/parallel/TunnelCmd/serial/AccessDirect ([gopogh](https://storage.googleapis.com/minikube-builds/logs/18896/34526/QEMU_macOS.html#fail_TestFunctional/parallel/TunnelCmd/serial/AccessDirect))|14.71 ([chart](https://gopogh-server-tts3vkcpgq-uc.a.run.app/?env=QEMU_macOS&test=TestFunctional/parallel/TunnelCmd/serial/AccessDirect))|
|More tests...|Continued...|

Too many tests failed - See test logs for more details.

To see the flake rates of all tests by environment, click [here](https://minikube.sigs.k8s.io/docs/contrib/test_flakes/).

------------------------------------------------------------------------------------------------------------------------------------------------------

I purpose if an enviroment has more than 10 failed test it should not include it in the Table
but AFTER the table it shoudl say

Qemu Macos Had TOO many Failured to be listted here is the link

### Attach the log file

n/na

### Operating System

None

### Driver

None

**Comment by medyagh** [comment]
the logic is inminikube/hack/jenkins/test-flake-chart/report_flakes.sh

and it is still using the Old Format ! that is using CSV files, we can implement that as part of gopogh itself so it gets the data from database instead of the csv

**Comment by medyagh** [comment]
@ComradeProgrammer one idea would be the Gopogh Server would have a handle for example /PRSummary/PRNumber/

and if we hit that it will return a MARKDOWN to comment on the PR

**Comment by ComradeProgrammer** [comment]
Considering that we do not have a root_job field in gopogh's database, may I suggest that we could using the easiest way to fix it: just rewriting the report_flake.sh with go and change the logic of changing the logic of generating message
