### ISSUE TITLE
The none driver should have an option to initialize all configuration in a specific folder

### ISSUE THREAD

**Issue by thedrow** [kubernetes/minikube#1893]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

**What happened**:
The none driver requires root permissions to configure itself.

**What you expected to happen**:
Since a CI worker is ephemeral we really don't care where the configuration is installed.
Furthermore, when running local tests with k8s we don't really want the kubelet to persist between reboots.
The CLI option should allow us to install the configuration into /tmp/ for example.

**Comment by r2d4** [comment]
I think this would really entail being able to specify a config file path (instead of `~/.minikube/config/config.json`.  I think thats a pretty useful feature.

**Comment by thedrow** [comment]
Mounting /var/lib/kubelet to /tmp/kubelet should also be possible.

**Comment by aaron-prindle** [comment]
The `none` driver is going to require root permissions even if the path is configurable.  We should be able to add configuration regarding where localkube/addons/etc. are moved.
