### ISSUE TITLE
Error after command "minicube start"

### ISSUE THREAD

**Issue by lewisfalide** [kubernetes/minikube#18939]
### What Happened?

Hello everyone. An error occurs when executing the "minicube start" command. The full log is below
I'm using a mac m1 (2020)

	[ERROR KubeletVersion]: couldn't get kubelet version: cannot execute 'kubelet --version': executable file not found in $PATH

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15388828/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by T-Lakshmi** [comment]
@lewisfalide,
Delete minikube and reinstall with below commands.

1. `minikube delete --all --purge`
2. `minikube start --driver=docker`

**Comment by T-Lakshmi** [comment]
/kind support

@lewisfalide,
Let us know if this resolves your issue to proceed further.
