### ISSUE TITLE
Suggestion: enable cmd line flags to define data dir/minikube home

### ISSUE THREAD

**Issue by ndlarsen** [kubernetes/minikube#18938]
### What Happened?

I am looking into the possibility of running minikube as a system service on my  Asustor AS6604T NAS.

Currently Minikube dumps a .minikube folder into the home directory of the executing user. 

This does not seem to be fully configurable thus requiring a home directory to be present for the executing user. So, if I were to write a service file executing `sudo -u minikube /usr/bin/minikube start`, this would require the user `minikube` to not just exist but also have a home directory created which in my opinion should be avoided for a system/service user.

I am aware that defining  the `MINIKUBE_HOME` environment variable will change the target directory. However, if I define `MINIKUBE_HOME=/var/lib/minikube`, a `/var/lib/minikube/.minikube` directory is created which is not entirely pretty and having to define the environment variable is a bit clunky. In addition to that, `MINIKUBE_HOME` is  not documented via `--help`.

It would be great if the location of this directory was configurable via a cmd line flag, e.g. `--data-dir, -d` which defaults to `/var/lib/minikube` if omitted and only creating the `.minikube` dir if overridden via e.g. a `--use-home-dir` flag. This removes the need for a present home directory for the executing user and is somewhat closer to adhering to the Linux Filesystem Hierarchy Standard.

Other than that, I love the product.

Regards.

### Attach the log file

not applicable

### Operating System

Ubuntu

### Driver

Docker

**Comment by afbjorklund** [comment]
Minikube is not intended to run as a system service, and it doesn't really follow the directory standard either.

* https://github.com/kubernetes/minikube/issues/4109
