### ISSUE TITLE
site: make tabbed view linkable

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#18956]
### What Happened?

for example in these pages we have Tabs
https://minikube.sigs.k8s.io/docs/start/
for example we have linux mac windows tabs here
https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/

when we click on the Active Tab we should be able to link to the Tab we want in order to give to another person, lets say I wanna only link to the Windows there should be a way to link to it regardless of the user click

### Attach the log file

n/a

### Operating System

None

### Driver

None

**Comment by rihib** [comment]
Hello, can I work on this issue?

**Comment by rihib** [comment]
@medyagh

**Comment by hritesh04** [comment]
can i work on this ?

**Comment by medyagh** [comment]
@hritesh04 sorry had to revert your PR while it looked good when selecting a tab but it was broken on the index see the preview

https://deploy-preview-18977--kubernetes-sigs-minikube.netlify.app/docs/start/

**Comment by spowelljr** [comment]
Hi @hritesh04, regarding the revert, I believe the issue is due to moving setting the default selection into an `else`:
```
const archParam = urlParams.get("arch");

//checks for query params and process each option one by one

if (archParam) {
    ...
} else {
    // auto-select the OS for user
    const btn = $(".option-button[data-quiz-id='/" + userOS + "']").first();
    btn.addClass("active");
    selectQuizOption(btn.attr("data-quiz-id"));
}
```

It seems that `archParam` is resulting to `true` when it shouldn't

**Comment by hritesh04** [comment]
hey @spowelljr ,
I think the issue was created when the site was accessed from a Mac. if do there was a issue on line 59 of quiz.js which i fixed and opened a pr for. Please check that #18982

**Comment by medyagh** [comment]
closed https://github.com/kubernetes/minikube/pull/18982
