### ISSUE TITLE
minikube start失败

### ISSUE THREAD

**Issue by yeegor0311** [kubernetes/minikube#18955]
执行:
minikube start --image-mirror-country=‘cn’ --base-image=‘anjone/kicbase’ --registry-mirror=https://x5keonuq.mirror.aliyuncs.com/ --kubernetes-version=1.29.2

**失败的命令的完整输出**：<details>
💣  更新 cluster 失败: updating control plane: downloading binaries: downloading kubectl: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.29.2/bin/linux/amd64/kubectl?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.29.2/bin/linux/amd64/kubectl.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.29.2/bin/linux/amd64/kubectl?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.29.2/bin/linux/amd64/kubectl.sha256 Dst:/Users/Aaron/.minikube/cache/linux/v1.29.2/kubectl.download Pwd: Mode:2 Detectors:[0x36aeec0 0x36aeec0 0x36aeec0 0x36aeec0 0x36aeec0 0x36aeec0] Decompressors:map[bz2:0x36aeec0 gz:0x36aeec0 tar.bz2:0x36aeec0 tar.gz:0x36aeec0 tar.xz:0x36aeec0 tbz2:0x36aeec0 tgz:0x36aeec0 txz:0x36aeec0 xz:0x36aeec0 zip:0x36aeec0] Getters:map[file:0xc00020b4a0 http:0xc0009e66c0 https:0xc0009e66e0] Dir:false ProgressListener:0x3679780 Options:[0x1865280]}: invalid checksum: Error downloading checksum file: bad response code: 404

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：MacOS

**Comment by medyagh** [comment]
@yeegor0311 

can you please try this

minikube start --image-mirror-country=cn

**Comment by JiangJungle** [comment]
> @yeegor0311
> 
> can you please try this
> 
> minikube start --image-mirror-country=cn

The command I used was   **minikube start --memory='48g' --image-mirror-country='cn' --cpus='10' --disk-size='200000mb'**.
The results I got were ：
：Failed to update cluster: update primary control-plane node: downloading binaries: downloading kubeadm: download failed: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.30.0/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.30.0/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.30.0/bin/linux/amd64/kubeadm?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.30.0/bin/linux/amd64/kubeadm.sha256 Dst:C:\Users\Jiang\.minikube\cache\linux\amd64\v1.30.0/kubeadm.download Pwd: Mode:2 Umask:---------- Detectors:[0x47a2a00 0x47a2a00 0x47a2a00 0x47a2a00 0x47a2a00 0x47a2a00 0x47a2a00] Decompressors:map[bz2:0xc0006528a0 gz:0xc0006528a8 tar:0xc000652850 tar.bz2:0xc000652860 tar.gz:0xc000652870 tar.xz:0xc000652880 tar.zst:0xc000652890 tbz2:0xc000652860 tgz:0xc000652870 txz:0xc000652880 tzst:0xc000652890 xz:0xc0006528b0 zip:0xc0006528c0 zst:0xc0006528b8] Getters:map[file:0xc00132f9c0 http:0xc0005e4be0 https:0xc0005e4c80] Dir:false ProgressListener:0x4708d30 Insecure:false DisableSymlinks:false Options:[0x10c80a0]}: **invalid checksum**: Error downloading checksum file: bad response code: 404

**_The checksum of kubeadm doesn't seem to be right_**

**Comment by ivanxu77** [comment]
你的启动命令中的单引号是中文单引号吧，你改成英文的试试

**Comment by JiangJungle** [comment]
> 你的启动命令中的单引号是中文单引号吧，你改成英文的试试

不是中文的

**Comment by JiangJungle** [comment]
我还发现一个问题，使用--registry-mirror无效啊，minikube start --registry-mirror=https://xxxxxx.mirror.aliyuncs.com/   ，但是minikube ssh进去cat /etc/docker/deamon.json 并没有这个参数

**Comment by JiangJungle** [comment]
我还发现一个问题，使用--registry-mirror无效啊，minikube start --registry-mirror=https://xxxxxx.mirror.aliyuncs.com/   ，但是minikube ssh进去cat /etc/docker/deamon.json 并没有这个参数

**Comment by liangyuanpeng** [comment]
download files from https://kubernetes.oss-cn-hangzhou.aliyuncs.com/kubernetes-release/release/v1.30.0/bin/linux/amd64/kubeadm failed,  try to open a issue to https://github.com/AliyunContainerService/minikube/issues

share the answer would be great if you're resolved it! @JiangJungle
