### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by mdkadir360** [kubernetes/minikube#18953]
### What Happened?

please solve this

### Attach the log file

[logs.txt`](https://github.com/kubernetes/minikube/files/15422006/logs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by T-Lakshmi** [comment]
@mdkadir360,
As per the attached logs, seems like issue with kubelet agent while starting cluster.

However attached logs are not enough to help you out in resolving the issue, could you please elaborate the issue with more information.
What you are trying to achieve and what issue you are facing?
