### ISSUE TITLE
X Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found

### ISSUE THREAD

**Issue by ericfgsilva** [kubernetes/minikube#18960]
### What Happened?

X Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found

### Attach the log file

[minikube_service_21d8563976e47bf64cb9b34a91838dfc5dd2eb5c_0.log](https://github.com/kubernetes/minikube/files/15445136/minikube_service_21d8563976e47bf64cb9b34a91838dfc5dd2eb5c_0.log)

### Operating System

Windows

### Driver

Hyper-V

**Comment by BerkAkipek** [comment]
Hey same problem in here there is my service file and compiled `successfuly.
`apiVersion: v1
kind: Service
metadata:
  name: go-rest-api-service
spec:
  selector:
    app: go-rest-api
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000`

**Comment by BerkAkipek** [comment]
Hey my friend i solved this issue now i changed targetPort to 8080 which is exposed port from my backend. Be sure to your exposed ports
