### ISSUE TITLE
minikube service hello-minikube --url

### ISSUE THREAD

**Issue by Vikas-hub17** [kubernetes/minikube#18986]
### What Happened?

X Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found

### Attach the log file

[minikube_service_c36eb15415f729bf5c10b8fc7a212aa5b23c44de_0.logs.txt](https://github.com/kubernetes/minikube/files/15480732/logs.txt)

### Operating System

Windows

### Driver

Docker

**Comment by T-Lakshmi** [comment]
This error is coming due to you are trying to map a service **hello-minikube ** with a pod which is not available.
Make sure **labels** mentioned in pod definition must be match with **selectors** under service definition.

**Comment by T-Lakshmi** [comment]
@Vikas-hub17,
If above suggestion is not helpful and if you still facing issue, share the service and deployment/pod definition files here.

**Comment by Vikas-hub17** [comment]
Can you share what should I exactly change to deploy k8s cluster?
