### ISSUE TITLE
feature request: support basic auth

### ISSUE THREAD

**Issue by nelson-cf** [kubernetes/minikube#1898]
The Ansible kubernetes module can only authenticate with basic authentication, not certs.  I'm sure there are other use cases for basic authentication against minikube.  It would be great if there was an option at startup where the kubernetes-api would be started with the flag:
--token-auth-file=MYBASICAUTHFILE

Kube documentation here:
https://kubernetes.io/docs/admin/authentication/#static-password-file

Thank you,
Nelson

**Comment by aaron-prindle** [comment]
You should be able to configure kubernetes using the extra-options flag documented here:
https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md
 I believe you the setting you want to use is here: https://godoc.org/k8s.io/kubernetes/pkg/kubeapiserver/options#BuiltInAuthenticationOptions

**Comment by nelson-cf** [comment]
Thank you for responding Aaron.  I had tried with the following extra-options, but had no luck. I'm the first to admit I might not be doing this right.  The ```<( echo "admin:password:100")``` is since it would be expecting a file rather than string.  Any help would be appreciated.
```
minikube start --extra-config apiserver.PasswordFile=<( echo "admin:password:100")

minikube start --extra-config apiserver.Authentication.PasswordFile=<( echo "admin:password:100")

minikube start --extra-config apiserver.Authentication.PasswordFileAuthenticationOptions.BasicAuthFile=<( echo "admin:password:100")
```

**Comment by southwolf** [comment]
@nelson-cf Any updates on that? Thanks.

**Comment by bewiwi** [comment]
I try with this:
```
--extra-config=apiserver.Authentication.PasswordFile.BasicAuthFile=/yourfile.csv
```
and it's works

**Comment by farrukhnajmi** [comment]
@bewiwi I am on windows 7 and the solution does not work for me.

I have the folloiwng in my csv file based on [this resource](https://kubernetes.io/docs/admin/authentication/#static-password-file):

```
admin,s3cr3t,100
```

My command to start in dos shell is:

```
  minikube start --extra-config=apiserver.Authentication.PasswordFile.BasicAuthFile=C:\Users\fnajmi\.minikube\basicauth.csv
```

I get the following error output:

```
C:\Users\fnajmi> minikube start --extra-config=apiserver.Authentication.PasswordFile.BasicAuthFile=C:\Users\fnajmi\.minikube\basicauth.csv
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0522 09:36:11.959707   17492 start.go:281] Error restarting cluster:  running cmd:
sudo kubeadm alpha phase certs all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase kubeconfig all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase controlplane all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase etcd local --config /var/lib/kubeadm.yaml
: Process exited with status 1
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
Y
```

Note that equivalent command in gitbash shell just hangs.

**Comment by silvam11** [comment]
Hello,
I have the same issue described by @farrukhnajmi. However, in my case minikube is running on a Ubuntu (17.10) VM. 

Below is the minikube version:
           minikube version: v0.26.0

Does anyone know how to solve it?

Thanks,
Mauro

**Comment by murphyki** [comment]
Seeing very same issue as @silvam11 

Looking at the apiserver docker container logs, my `users.csv` file is not found.

I'm using `minikube version: v0.27.0`

**Comment by belminf** [comment]
@murphyki did you ever figure out a way to get that file into the apiserver container? I have a similar problem which I'm trying to figure out.

**Comment by rajasaur** [comment]
Got this finally working. The pass-file needs to be located inside the apiserver container, not in the minikube vm, which is why it ends up in a loop when starting as it cannot find the file.

My solution is a bit hacky, but it works.
I have the basic auth file stored at /Users/raja/mini/minipass with the contents
password,admin,100

Now mount this path inside /var/lib/localkube/certs  (This path is shared between the minikube vm and the apiserver container).
`
minikube mount /Users/raja/mini/:/var/lib/localkube/certs/mini `

We can now start minikube pointing to the directory like
`minikube start  --extra-config=apiserver.basic-auth-file=/var/lib/localkube/certs/mini/minipass   --kubernetes-version=v1.10.0 --memory 6060 --cpus 4`

This mounts the file inside of the apiserver and now I can authenticate using Basic Auth.

**Comment by silvam11** [comment]
Thanks @rajasaur I will try too

**Comment by murphyki** [comment]
@belminf no, I had given up on it! but looks like @rajasaur has a fix. Thanks @rajasaur I will try it out as well.

**Comment by abhaybhargav** [comment]
@rajasaur - Your solution works for me. minikube 0.28.2. It didnt work for me in the 0.25 version. Thanks :)

**Comment by VatslavDS** [comment]
Don't fotget to create a volume Hostpath pointing to your  minikube / node path.
