### ISSUE TITLE
 Exiting due to GUEST_START

### ISSUE THREAD

**Issue by rohit200207** [kubernetes/minikube#18989]
### What Happened?

 ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://localhost:42091/apis/storage.k8s.io/v1/storageclasses": dial tcp 127.0.0.1:42091: connect: connection refused]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15483739/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by T-Lakshmi** [comment]
@rohit200207,
can you try with deleting minikube and reinstall it with below commands:
`minikube delete --all --purge`
`minikube start --driver=docker`

I hope this will resolve your issue.

**Comment by spowelljr** [comment]
We have a fix for this, going to close this as a duplicate of https://github.com/kubernetes/minikube/issues/19173 to centralize discussion, please follow there for updates, thank you!

**Comment by rohit200207** [comment]
[logs.txt](https://github.com/user-attachments/files/16141666/logs.txt)

**Comment by T-Lakshmi** [comment]
Hi @rohit200207,

Please follow the suggestion mentioned in [19173 comment](https://github.com/kubernetes/minikube/issues/19173#issuecomment-2209193041) to resolve your issue.

We closed this issue as it was already recorded under #19173 issue and we are working on it. Please follow there further updates on it.
Thank you.
