### ISSUE TITLE
Running minikube as normal user

### ISSUE THREAD

**Issue by zioalex** [kubernetes/minikube#1899]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**: Development laptop

**Minikube version** (use `minikube version`): minikube version: v0.21.0

- **OS** (e.g. from /etc/os-release): Sabayon/Linux
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "none"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): None
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

**What happened**:
I have start minikube as root. As I can see it must write /usr/local/bin/localkube . 

**What you expected to happen**:
I can run minikube from normal user

**How to reproduce it** (as minimally and precisely as possible):
> minikube start
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E0829 11:15:23.176550   28553 start.go:158] Error updating cluster:  error creating file at /usr/local/bin/localkube: open /usr/local/bin/localkube: permission denied

Running as root works properly:
> sudo minikube start
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by dlorenc** [comment]
When using the none driver you'll need root, since minikube runs the kubernetes system components directly on your machine.

You can see here for a similar discussion: https://github.com/kubernetes/kubeadm/issues/57

**Comment by zioalex** [comment]
In that bug, I do not see a direct connection with the problem I found. There the problem is regarding kubeadm while I am speaking about minikube.

Moreover though I do not specify  a driver a VM vbox machine is launched:
`VBoxManage list runningvms
"minikube" {93e8ac3f-9981-4fc0-851f-cf128400233d}
`

Also I didn't see this requirement specified.

**Comment by zioalex** [comment]
Confirmed that also without specifying the driver VirtualBox is used as default:
[
[machines_minikube_config.json.txt](https://github.com/kubernetes/minikube/files/1261699/machines_minikube_config.json.txt)

](url)

**Comment by dlorenc** [comment]
Sorry, to be more clear, kubeadm and minikube both setup a kubernetes cluster. If you run minikube with the "none" driver, it attempts to run all of the components directly on your machine with no VM. You will need minikube to run as root for that for the same reasons outlined in the kubeadm issue.

If you use minikube with the other drivers you will not need to run it as a root user.

**Comment by zioalex** [comment]
Hi @dlorenc,
okey if it is not using any driver it needs to be root. Got it.

But I found out that also without specifying the driver it launch a VM.

**Comment by zioalex** [comment]
I tried to run also with the vm-driver specified:
```> minikube start --vm-driver virtualbox
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E0829 23:26:00.144256   26670 start.go:158] Error updating cluster:  error removing file /usr/local/bin/localkube: remove /usr/local/bin/localkube: permission denied
```

Same error and the help states that virtualbox is the default:```
      --vm-driver string                VM driver is one of: [virtualbox kvm none] (default "virtualbox")

```

**Comment by zioalex** [comment]
BUMP^^^

**Comment by dlorenc** [comment]
I'm not sure I understand the question. The default driver should be virtualbox.

**Comment by zioalex** [comment]
Hi @dlorenc  , so if I do not specify the driver it use by default VirtualBox. From my understanding this shoud not require root.

So why it doesn't work from a normal user?

**Comment by ryanmt** [comment]
I just ran into this because a "None" driver machine was hiding.  Despite configuring "KVM" and running `minikube start --vm-driver=kvm`

`cat ~/.minikube/machines/minikube/config.json | grep Driver` showed it.

`minikube delete` allowed me to start over w/ the kvm driver I was expected without causing the error.

**Comment by zioalex** [comment]
Thanks Ryan,
I will try.

**Comment by crazytan** [comment]
Turns out running `minikube delete` solves the problem. Thanks!

**Comment by zlance** [comment]
I'm still seeing it with minikube 0.28 running on ubuntu guest.  'minikube delete' does not clean it up.

**Comment by moiseswar** [comment]
I was still seeing this error in v0.28.1 as well. Went back to version 0.26.1, and deleted the `~/.minikube/machines/` folder, and then re-ran `minikube start` as normal user. This worked for me.

**Comment by zlance** [comment]
@moiseswar hmmm, didn't workout for me.

**Comment by Tay-Sike** [comment]
`minikube delete` works on Windows 10 Pro with `minikube version: v0.30.0`
