### ISSUE TITLE
website: browser should detect Apple SIlicon (M) for the download page

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#19031]
### What Happened?

https://minikube.sigs.k8s.io/docs/start/

currently it auto detects Macos but it doe NOT detect the arch

<img width="939" alt="Screenshot 2024-06-04 at 10 55 11 AM" src="https://github.com/kubernetes/minikube/assets/4564227/fa509473-b2d3-41cf-94cc-598bf0d95bb2">

**Comment by medyagh** [comment]
@hritesh04 would you be interested ?

**Comment by spowelljr** [comment]
https://stackoverflow.com/q/65146751

Seems very browser specific, so will work from some but not all

**Comment by hritesh04** [comment]
i can work on this but i don't have a mac device to test if the solution will work. so i think its better if someone with a mac can work on it.

**Comment by MiirzaBaig** [comment]
I would like to take up this issue !

**Comment by medyagh** [comment]
@MiirzaBaig sure thing please let me know when it is ready

**Comment by MiirzaBaig** [comment]
@medyagh Alright, will let you know once its done!

**Comment by IC1101Virgo** [comment]
Hey @medyagh,
I am keen on contributing and found this issue. I have tested and found a clean solution kindly review my [PR](https://github.com/kubernetes/minikube/pull/19243).
