### ISSUE TITLE
logs.txt

### ISSUE THREAD

**Issue by ChayzZ47** [kubernetes/minikube#19032]
### What Happened?

errors

### Attach the log file

minikube logs --file=logs.txt

### Operating System

None

### Driver

None

**Comment by jsbiff** [comment]
This issue lacks any details - it's literally impossible for anyone to try to help you. Can you copy and paste the errors from your computer into the "What Happened"? Just saying errors doesn't tell anyone what errors.

Also, you didn't attach the log files, you just copied the command that minikube suggested you run to create the log files. If the log files were attached, people might be able to find the errors in the logs.

Currently, there's not enough information to start investigating your problem.

**Comment by T-Lakshmi** [comment]
@ChayzZ47,
Since we not heard anything from you long time, we are assuming your issue has been resolved and iam closing this issue.
Feel free to reopen with necessary details requested if you still facing this issue.
Thanks.
