### ISSUE TITLE
Kong addon missing a cluster scoped permission which causes ingress controller startup failure

### ISSUE THREAD

**Issue by gregwhorley** [kubernetes/minikube#19043]
### What Happened?

I followed the guide to install and setup an Ingress resource using the Kong addon: https://minikube.sigs.k8s.io/docs/handbook/addons/kong-ingress/

The addon install ran without any errors, but I noticed that the ingress pod was stuck in a crash loop. Checking the pod logs showed why:
`
E0609 19:09:31.007918       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
`
I was able to get it working by manually adding the necessary permissions to the `kong-ingress` cluster role resource.

```
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
  - get
```

### Attach the log file

time="2024-06-09T19:09:15Z" level=info msg="diagnostics server disabled"
time="2024-06-09T19:09:15Z" level=info msg="starting controller manager" commit=1bbc60b45b19e000ea9493109e62e3ebbd3a70ba logger=setup release=2.12.0 repo="https://github.com/Kong/kubernetes-ingress-controller.git"
time="2024-06-09T19:09:15Z" level=info msg="the ingress class name has been set" logger=setup value=kong
time="2024-06-09T19:09:15Z" level=info msg="getting enabled options and features" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="getting the kubernetes client configuration" logger=setup
W0609 19:09:15.135875       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2024-06-09T19:09:15Z" level=info msg="starting standalone health check server" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="getting the kong admin api client configuration" logger=setup
W0609 19:09:15.135939       1 client_config.go:618] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2024-06-09T19:09:15Z" level=info msg="tag filtering enabled" logger=setup tags="[\"managed-by-ingress-controller\"]"
time="2024-06-09T19:09:15Z" level=info msg="configuring and building the controller manager" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="building the manager runtime scheme and loading apis into the scheme" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="DB-less mode detected with service detection, enabling leader election" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="Initializing Dataplane Client" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="Running AdminAPIClientsManager loop" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="combined routes mode has been enabled"
time="2024-06-09T19:09:15Z" level=info msg="Starting Admission Server" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="admission webhook server disabled" component=admission-server
time="2024-06-09T19:09:15Z" level=info msg="Initializing Dataplane Synchronizer" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="Starting Status Updater" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="Initializing Dataplane address Discovery" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="falling back to a default address finder for UDP" logger=setup reason="no publish status address or publish service were provided"
time="2024-06-09T19:09:15Z" level=info msg="Starting Enabled Controllers" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="Required CustomResourceDefinitions are not installed, setting up a watch for them in case they are installed afterward" logger=controllers.Dynamic/KnativeV1Alpha1/Ingress
time="2024-06-09T19:09:15Z" level=info msg="Required CustomResourceDefinitions are not installed, setting up a watch for them in case they are installed afterward" logger=controllers.Dynamic/Gateway
time="2024-06-09T19:09:15Z" level=info msg="Required CustomResourceDefinitions are not installed, setting up a watch for them in case they are installed afterward" logger=controllers.Dynamic/HTTPRoute
time="2024-06-09T19:09:15Z" level=info msg="Add readiness probe to health server" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="starting telemetry manager"
time="2024-06-09T19:09:15Z" level=info msg="anonymous reports enabled" logger=setup
time="2024-06-09T19:09:15Z" level=info msg="Starting manager" logger=setup
I0609 19:09:15.163462       1 leaderelection.go:250] attempting to acquire leader lease kong/5b374a9e.konghq.com...
I0609 19:09:30.989548       1 leaderelection.go:260] successfully acquired lease kong/5b374a9e.konghq.com
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.IngressClass.netv1 source="kind source: *v1.IngressClass"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.IngressClass.netv1
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.Service source="kind source: *v1.Service"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.Service
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongAdminAPIService source="kind source: *v1.EndpointSlice"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.Secrets source="kind source: *v1.Secret"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.Secrets
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.KongAdminAPIService
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.TCPIngress source="channel source: 0x4000863c00"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.TCPIngress source="kind source: *v1.IngressClass"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.TCPIngress source="kind source: *v1beta1.TCPIngress"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.TCPIngress
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.IngressClassParameters source="kind source: *v1alpha1.IngressClassParameters"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.IngressClassParameters
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.UDPIngress source="channel source: 0x4000863b80"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.UDPIngress source="kind source: *v1.IngressClass"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.UDPIngress source="kind source: *v1beta1.UDPIngress"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.UDPIngress
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.Ingress.netv1 source="channel source: 0x4000863a00"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.EndpointSlice source="kind source: *v1.EndpointSlice"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.EndpointSlice
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongConsumer source="channel source: 0x4000863d40"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.Ingress.netv1 source="kind source: *v1.IngressClass"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongConsumer source="kind source: *v1.IngressClass"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongIngress source="kind source: *v1.KongIngress"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongClusterPlugin source="kind source: *v1.IngressClass"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongClusterPlugin source="kind source: *v1.KongClusterPlugin"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.KongClusterPlugin
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.Ingress.netv1 source="kind source: *v1.Ingress"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.Ingress.netv1
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongConsumer source="kind source: *v1.KongConsumer"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.KongConsumer
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongPlugin source="kind source: *v1.KongPlugin"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.KongPlugin
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.Dynamic/KnativeV1Alpha1/Ingress source="kind source: *v1.CustomResourceDefinition"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.Dynamic/KnativeV1Alpha1/Ingress
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.Dynamic/HTTPRoute source="kind source: *v1.CustomResourceDefinition"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.Dynamic/HTTPRoute
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.KongIngress
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongConsumerGroup source="channel source: 0x4000863dc0"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongConsumerGroup source="kind source: *v1.IngressClass"
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.KongConsumerGroup source="kind source: *v1beta1.KongConsumerGroup"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.KongConsumerGroup
time="2024-06-09T19:09:30Z" level=info msg="Starting EventSource" logger=controllers.Dynamic/Gateway source="kind source: *v1.CustomResourceDefinition"
time="2024-06-09T19:09:30Z" level=info msg="Starting Controller" logger=controllers.Dynamic/Gateway
W0609 19:09:31.007855       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0609 19:09:31.007918       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
time="2024-06-09T19:09:31Z" level=info msg="Starting workers" logger=controllers.EndpointSlice worker count=1
W0609 19:09:32.501313       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0609 19:09:32.501403       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
time="2024-06-09T19:09:34Z" level=info msg="successfully synced configuration to Kong" update_strategy=InMemory url="https://10.244.0.16:8444"
W0609 19:09:34.923224       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0609 19:09:34.923313       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
W0609 19:09:38.187402       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0609 19:09:38.187499       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
W0609 19:09:48.904994       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0609 19:09:48.905111       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
[controller-runtime] log.SetLogger(...) was never called; logs will not be displayed.
Detected at:
	>  goroutine 375 [running]:
	>  runtime/debug.Stack()
	>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x64
	>  sigs.k8s.io/controller-runtime/pkg/log.eventuallyFulfillRoot()
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/log/log.go:60 +0xf4
	>  sigs.k8s.io/controller-runtime/pkg/log.(*delegatingLogSink).Error(0x400052cac0, {0x1c328c0, 0x4000fa5000}, {0x19b5f1d, 0x3d}, {0x4000ed4820, 0x2, 0x2})
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/log/deleg.go:139 +0x44
	>  github.com/go-logr/logr.Logger.Error({{0x1c50d28?, 0x400052cac0?}, 0x1556580?}, {0x1c328c0, 0x4000fa5000}, {0x19b5f1d, 0x3d}, {0x4000ed4820, 0x2, 0x2})
	>  	/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:299 +0xb4
	>  sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1.1({0x1c4d3f0?, 0x40000a8f50?})
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:63 +0x25c
	>  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext.func2(0x4000f83dc0?, {0x1c4d3f0?, 0x40000a8f50?})
	>  	/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/loop.go:73 +0x58
	>  k8s.io/apimachinery/pkg/util/wait.loopConditionUntilContext({0x1c4d3f0, 0x40000a8f50}, {0x1c43d50?, 0x4000887660}, 0x1, 0x0, 0x4000a60400?)
	>  	/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/loop.go:74 +0x1ac
	>  k8s.io/apimachinery/pkg/util/wait.PollUntilContextCancel({0x1c4d3f0, 0x40000a8f50}, 0x62756b696e696d2f?, 0x65?, 0x4000b9aef8?)
	>  	/go/pkg/mod/k8s.io/apimachinery@v0.28.2/pkg/util/wait/poll.go:33 +0x74
	>  sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start.func1()
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:56 +0xb8
	>  created by sigs.k8s.io/controller-runtime/pkg/internal/source.(*Kind).Start in goroutine 300
	>  	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.2/pkg/internal/source/kind.go:48 +0x1c4
W0609 19:10:07.286248       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0609 19:10:07.286339       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
W0609 19:10:52.198876       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0609 19:10:52.198964       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
W0609 19:11:30.535733       1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
E0609 19:11:30.535827       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.2/tools/cache/reflector.go:229: Failed to watch *v1.CustomResourceDefinition: failed to list *v1.CustomResourceDefinition: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:kong:kong-serviceaccount" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for NetV1IngressClass caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass" logger=controllers.IngressClass.netv1
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongV1KongPlugin caches to sync: timed out waiting for cache to be synced for Kind *v1.KongPlugin" logger=controllers.KongPlugin
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongV1KongIngress caches to sync: timed out waiting for cache to be synced for Kind *v1.KongIngress" logger=controllers.KongIngress
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongV1Beta1KongConsumerGroup caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass" logger=controllers.KongConsumerGroup
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for DynamicCRDController caches to sync: timed out waiting for cache to be synced for Kind *v1.CustomResourceDefinition" logger=controllers.Dynamic/HTTPRoute
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for CoreV1Secret caches to sync: timed out waiting for cache to be synced for Kind *v1.Secret" logger=controllers.Secrets
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for DynamicCRDController caches to sync: timed out waiting for cache to be synced for Kind *v1.CustomResourceDefinition" logger=controllers.Dynamic/Gateway
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongV1Alpha1IngressClassParameters caches to sync: timed out waiting for cache to be synced for Kind *v1alpha1.IngressClassParameters" logger=controllers.IngressClassParameters
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for DynamicCRDController caches to sync: timed out waiting for cache to be synced for Kind *v1.CustomResourceDefinition" logger=controllers.Dynamic/KnativeV1Alpha1/Ingress
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongV1KongPlugin caches to sync: timed out waiting for cache to be synced for Kind *v1.KongPlugin"
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for NetV1Ingress caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass" logger=controllers.Ingress.netv1
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for CoreV1Service caches to sync: timed out waiting for cache to be synced for Kind *v1.Service" logger=controllers.Service
time="2024-06-09T19:11:30Z" level=info msg="Stopping and waiting for non leader election runnables"
time="2024-06-09T19:11:30Z" level=info msg="Stopping and waiting for leader election runnables"
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongV1KongConsumer caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass" logger=controllers.KongConsumer
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongAdminAPIEndpoints caches to sync: timed out waiting for cache to be synced for Kind *v1.EndpointSlice" logger=controllers.KongAdminAPIService
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongV1Beta1TCPIngress caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass" logger=controllers.TCPIngress
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongV1KongClusterPlugin caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass" logger=controllers.KongClusterPlugin
time="2024-06-09T19:11:30Z" level=error msg="Could not wait for Cache to sync" error="failed to wait for KongV1Beta1UDPIngress caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass" logger=controllers.UDPIngress
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongV1KongIngress caches to sync: timed out waiting for cache to be synced for Kind *v1.KongIngress"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongV1Beta1KongConsumerGroup caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for DynamicCRDController caches to sync: timed out waiting for cache to be synced for Kind *v1.CustomResourceDefinition"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for CoreV1Secret caches to sync: timed out waiting for cache to be synced for Kind *v1.Secret"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for DynamicCRDController caches to sync: timed out waiting for cache to be synced for Kind *v1.CustomResourceDefinition"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongV1Alpha1IngressClassParameters caches to sync: timed out waiting for cache to be synced for Kind *v1alpha1.IngressClassParameters"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for DynamicCRDController caches to sync: timed out waiting for cache to be synced for Kind *v1.CustomResourceDefinition"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for NetV1Ingress caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for CoreV1Service caches to sync: timed out waiting for cache to be synced for Kind *v1.Service"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongV1KongConsumer caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongAdminAPIEndpoints caches to sync: timed out waiting for cache to be synced for Kind *v1.EndpointSlice"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongV1Beta1TCPIngress caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongV1KongClusterPlugin caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass"
time="2024-06-09T19:11:30Z" level=error msg="error received after stop sequence was engaged" error="failed to wait for KongV1Beta1UDPIngress caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass"
time="2024-06-09T19:11:30Z" level=info msg="Shutdown signal received, waiting for all workers to finish" logger=controllers.EndpointSlice
time="2024-06-09T19:11:30Z" level=info msg="All workers finished" logger=controllers.EndpointSlice
time="2024-06-09T19:11:30Z" level=info msg="Stopping and waiting for caches"
time="2024-06-09T19:11:30Z" level=error msg="could not update kong admin" error="performing update for https://10.244.0.16:8444 failed: failed to verify kong readiness: making HTTP request: Get \"https://10.244.0.16:8444/status\": context canceled\nperforming update for https://10.244.0.16:8444 failed: failed to verify kong readiness: making HTTP request: Get \"https://10.244.0.16:8444/status\": context canceled" subsystem=dataplane-synchronizer
time="2024-06-09T19:11:30Z" level=info msg="context done: shutting down the proxy update server" subsystem=dataplane-synchronizer
time="2024-06-09T19:11:30Z" level=info msg="Stopping and waiting for webhooks"
time="2024-06-09T19:11:30Z" level=info msg="Stopping and waiting for HTTP servers"
time="2024-06-09T19:11:30Z" level=info msg="Wait completed, proceeding to shutdown the manager"
time="2024-06-09T19:11:30Z" level=info msg="stopping telemetry manager"
Error: failed to wait for NetV1IngressClass caches to sync: timed out waiting for cache to be synced for Kind *v1.IngressClass

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @gregwhorley, we had an existing issue for this that was fixed recently but it's not included in our latest release.

https://github.com/kubernetes/minikube/issues/19001

https://github.com/kubernetes/minikube/pull/19002

It will be included in our next release
