### ISSUE TITLE
Kubernetes apiserver not Running after starting minikube.

### ISSUE THREAD

**Issue by rannair** [kubernetes/minikube#19055]
### What Happened?

After starting minikube using command  **minikube start --driver=qemu**.  Api server dosent start.
**minikube status**             
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Stopped
kubeconfig: Configured

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/15781753/logs.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by Ritikaa96** [comment]
/kind support
`/.minikube/config/config.json: open /Users/ranjeetnair/.minikube/config/config.json: no such file or directory`
seems like config file cannot be found .

**Comment by Ritikaa96** [comment]
`ip6tables v1.8.9 (legacy): can't initialize ip6tables table `nat': Table does not exist (do you need to insmod?)`
I also saw this error in my system but this doesn't cause api-server issue neither any issue with minikube start.
