### ISSUE TITLE
minikube is not starting

### ISSUE THREAD

**Issue by oforiamet** [kubernetes/minikube#19072]
### What Happened?

minikube cannot start. I am using WSL 

### Attach the log file

[](url)
[Log.txt](https://github.com/user-attachments/files/15839113/Log.txt)

### Operating System

Windows

### Driver

None (Baremetal)

**Comment by mayankparihar98** [comment]
**What Happened?**

minikube cannot start. I am using WSL (Linux)

**Attach the log file**

[logs.txt](https://github.com/user-attachments/files/15846499/logs.txt)
[](url)

**Operating System**

Windows

Driver
Docker

**Comment by spowelljr** [comment]
Hi @oforiamet, you can't run minikube with the `none` driver on WSL because WSL doesn't use `systemd`, please try using the Docker driver.

**Comment by oforiamet** [comment]
Thanks
