### ISSUE TITLE
minikube /podman installation 

### ISSUE THREAD

**Issue by varsharanideshmane** [kubernetes/minikube#19081]
### What Happened?

❌  Exiting due to GUEST_STATUS: Unable to get control-plane node minikube host status: state: unknown state "minikube": sudo -n podman container inspect minikube --format={{.State.Status}}: exit status 125
stdout:

stderr:
time="2024-06-17T14:00:22+05:30" level=warning msg="Error validating CNI config file /etc/cni/net.d/minikube.conflist: [plugin bridge does not support config version \"1.0.0\" plugin portmap does not support config version \"1.0.0\" plugin firewall does not support config version \"1.0.0\" plugin tuning does not support config version \"1.0.0\"]"
Error: error inspecting object: no such container minikube

### Attach the log file

❌  Exiting due to GUEST_STATUS: Unable to get control-plane node minikube host status: state: unknown state "minikube": sudo -n podman container inspect minikube --format={{.State.Status}}: exit status 125
stdout:

stderr:
time="2024-06-17T14:00:22+05:30" level=warning msg="Error validating CNI config file /etc/cni/net.d/minikube.conflist: [plugin bridge does not support config version \"1.0.0\" plugin portmap does not support config version \"1.0.0\" plugin firewall does not support config version \"1.0.0\" plugin tuning does not support config version \"1.0.0\"]"
Error: error inspecting object: no such container minikube

### Operating System

Ubuntu

### Driver

None

**Comment by kundan2707** [comment]
This issue is with podman not minikube.
https://bugs.launchpad.net/ubuntu/+source/libpod/+bug/2024394

**Comment by kundan2707** [comment]
duplicate of  #17754
