### ISSUE TITLE
kvm2 cgroups v2

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/minikube#19105]
### What Happened?

Would like to test with cgroups v2 enabled

### Attach the log file

It seems to only support cgroups v1

### Operating System

Redhat/Fedora

### Driver

KVM2

**Comment by kundan2707** [comment]
Running with cggroups v2 is now by default 
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#cgroup-drivers
minikube should already be doing this.
I dont think there should be any issue.

**Comment by kfox1111** [comment]
Looks like its probably just switching the kvm image to use v2. Right now its v1. according to https://kubernetes.io/docs/concepts/architecture/cgroups/#check-cgroup-version tmpfs means v1.

```
minikube ssh -- stat -fc %T /sys/fs/cgroup/
tmpfs
```

**Comment by kundan2707** [comment]
It seems nthing to do on this now. closing it 
feel free to reopen whenever required

**Comment by kfox1111** [comment]
Um, still an issue. how do we reopen?
