### ISSUE TITLE
sealos增加节点报错  failed to join node 10.13.49.155:22 context deadline exceeded

### ISSUE THREAD

**Issue by Freudia01** [kubernetes/minikube#19107]
执行增加node节点命令：
sealos add --nodes 10.13.49.155  --pk=/root/.ssh/id_ed25519 --passwd=*****

在执行过程中报错：
error Applied to cluster error: failed to join node 10.13.49.155:22 context deadline exceeded
failed to join node 10.13.49.155:22 context deadline exceeded

然后退出执行过程

操作系统：Ubuntu 24.04 LTS

**Comment by liangyuanpeng** [comment]
@Freudia01  You need to open a issue at https://github.com/labring/sealos and not minikube.

**Comment by Freudia01** [comment]
wrong place
