### ISSUE TITLE
Using Multi-Control Plane - HA Clusters

### ISSUE THREAD

**Issue by ren-142326** [kubernetes/minikube#19113]
minikube ssh -p ha-demo -- 'sudo /var/lib/minikube/binaries/v1.28.4/kubectl --kubeconfig=/var/lib/minikube/kubeconfig logs -n kube-system pod/kube-vip-ha-demo'

[sudo] password for docker:

where password?

**Comment by victorguidi** [comment]
As far as I can understand, I believe you are calling a ssh command and passing a shell command to be executed once it sshs in the machine. That command is using sudo, which is the "admin" password to use commands that do not belong to the current user. 
Try using it the sudo password that is configured on the machine you ssh into, that it should work.

**Comment by ren-142326** [comment]
> As far as I can understand, I believe you are calling a ssh command and passing a shell command to be executed once it sshs in the machine. That command is using sudo, which is the "admin" password to use commands that do not belong to the current user. Try using it the sudo password that is configured on the machine you ssh into, that it should work.

I use wsl, I tried to use the root account password I set up, it doesn't work,

**Comment by victorguidi** [comment]
I see it, but what I meant was to to use the sudo password configured where the HA Cluster was configured, the ha-demo server I believe, have you tried this one too?

If this dont work, would be great if you provide some more info and logs of the steps you are executing

**Comment by prezha** [comment]
hi @ren-142326 instead of `v1.28.4` from the example, please use the kubernetes version that you installed your cluster with - you can find out `Version` from the `profile` command - eg:

`minikube profile list`
```
|---------|-----------|------------|----------------|------|---------|---------|-------|----------------|--------------------|
| Profile | VM Driver |  Runtime   |       IP       | Port | Version | Status  | Nodes | Active Profile | Active Kubecontext |
|---------|-----------|------------|----------------|------|---------|---------|-------|----------------|--------------------|
| ha-demo | docker    | containerd | 192.168.49.254 | 8443 | v1.31.1 | OKHAppy |     3 |                | *                  |
|---------|-----------|------------|----------------|------|---------|---------|-------|----------------|--------------------|
```

btw, pr #19722 aims to improve the docs and use the appropriate kubernetes version automatically
