### ISSUE TITLE
Advice user to use --gpus instead of gpu-addon on docker driver

### ISSUE THREAD

**Issue by sivanaikk** [kubernetes/minikube#19114]
### What Happened?

I am trying to integrate GPU with Minikube, My host machine is Windows and I am using docker desktop in wsl2 and trying to provision Minikube with the support of GPU.

I was able to integrate GPU with docker, 

` sudo docker run --rm --runtime=nvidia --gpus all ubuntu nvidia-smi`

![image](https://github.com/kubernetes/minikube/assets/60335740/a28fca93-9fcf-46c0-893f-b713fab3f952)

- Minikube start command 

`minikube start --driver=docker --addons=ingress --addons=nvidia-gpu-device-plugin`
![image](https://github.com/kubernetes/minikube/assets/60335740/47b66267-321e-472c-b433-0edd70e7d452)

![image](https://github.com/kubernetes/minikube/assets/60335740/cb21a949-ea4b-41aa-9697-507d20f934aa)

- Pod failing with the following error 
```

  Warning  FailedScheduling  45s   default-scheduler  0/1 nodes are available: 1 Insufficient nvidia.com/gpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
 ```

### Attach the log file

[log.txt](https://github.com/user-attachments/files/15927874/log.txt)

### Operating System

Windows

### Driver

Docker

### step I followed 

[Medium Link](https://medium.com/@sivanaikk0903/kubernetes-with-gpu-for-mlops-workloads-c684f8c8d41c)

**Comment by sivanaikk** [comment]
Thank you @medyagh. It's working now!

`minikube start --gpus all --driver=docker --addons=ingress`

![image](https://github.com/kubernetes/minikube/assets/60335740/159d7c69-a143-45a6-baa0-1bc6fa693c17)

**Comment by medyagh** [comment]
seems like we have 3 addons, 
two of them are for KVM and one is for docker, it is important that we figure out if we can merge some of them

| nvidia-device-plugin        | minikube | disabled     | 3rd party (NVIDIA)             |
| nvidia-driver-installer     | minikube | disabled     | 3rd party (Nvidia)             |
| nvidia-gpu-device-plugin    | minikube | disabled     | 3rd party (Nvidia)             |

**Comment by RamBITS-AI** [comment]
I'm starting work (PR - #19545) on this issue.

**Comment by RamBITS-AI** [comment]
Hi @medyagh - How do you think I can plan this merger of the 2 addons out? Are there any further tips or advice you could give me?
