### ISSUE TITLE
Automatically start Tiller on startup?

### ISSUE THREAD

**Issue by arschles** [kubernetes/minikube#1913]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

Please provide the following details:

**Environment**: all

**Minikube version** (use `minikube version`): v0.12.0
- **OS** (e.g. from /etc/os-release): macOS 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): `virtualbox`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.0.iso
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

**What happened**: `minikube start` started a valid Kubernetes cluster in a VirtualBox VM

**What you expected to happen**: I expected a valid Kubernetes cluster with Tiller (the Helm server-side component) installed, as well as necessary RBAC rules to enable tiller (in the case that minikube started an RBAC-enabled cluster). See [here](https://github.com/kubernetes-incubator/service-catalog/blob/master/docs/install-1.7.md#rbac) for the necessary RBAC rules

**How to reproduce it** (as minimally and precisely as possible): run `minikube start`, then run `helm list`. Observe the following error: 

```console
Error: could not find tiller
``` 

**Output of `minikube logs` (if applicable)**: not applicable

**Anything else do we need to know**: Helm is necessary to install the [service-catalog](https://github.com/kubernetes-incubator/service-catalog), and we need to provide a non-trivial amount of documentation for users to get Tiller installed and configured properly, before they can proceed. It would be very helpful for users to have Tiller pre-installed on Minikube, as this tool is a popular choice for first-time users. Also, it's worth noting that [acs-engine](https://github.com/azure/acs-engine) comes pre-installed with Tiller (and pre-configured).

**Comment by r2d4** [comment]
I think it would be reasonable to add helm/tiller as a configurable minikube addon.  @aaron-prindle has expressed some interest in this in the past.  WDYT?

**Comment by aaron-prindle** [comment]
SGTM.  As mentioned helm is used by many dev teams and first-time users standing up popular stacks, we should definitely make using it as simple as possible.  Having tiller as an addon makes a lot sense, I am not to sure about what the client/server compatibility is with helm, we'll have to investigate.

**Comment by bacongobbler** [comment]
Just clarifying, when you mean

> I am not to sure about what the client/server compatibility is with helm or what configuration we may want to add, we'll have to investigate.

Do you mean the compatibility between Tiller and Kubernetes? We publicize the roadmap [on github](https://github.com/kubernetes/helm/milestones?state=open). The latest release (v2.6.x) targets Kubernetes 1.7 compatibility, but we strive for backwards compatibility as far back as we can. For example we are still using Helm 2.6.x actively against kubernetes (minikube/ACS) 1.6 and 1.5 clusters. Generally we strive for compatibility with the latest two minor releases of Kubernetes per helm release, so 2.7 should have support for k8s 1.8 and hopefully k8s 1.7 as well. If Tiller happens to work on 1.6 and 1.5 clusters, that's awesome too.

Is that the answer you were looking for? :)

**Comment by aaron-prindle** [comment]
@bacongobbler Nice!  I was referring the the compatibility between the helm client and tiller server. I imagine the client/server are compatible across multiple version combinations (client v2 w/ server v1) but I'm not certain.  We've seen errors like this for kubectl-vX.X.X/kubernetes-vY.Y.Y in the past, just wanted to make sure that bundling Tiller couldn't break helm in some cases for users.

If someone from the helm team wants to add and maintain a Tiller addon for Minikube that would be awesome!   We have some documentation on adding an addon [here](https://github.com/kubernetes/minikube/blob/master/docs/contributors/adding_an_addon.md).
