### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by He-mant9** [kubernetes/minikube#19138]
### What Happened?

na

### Attach the log file

na

### Operating System

Ubuntu

### Driver

Docker

**Comment by Ritikaa96** [comment]
Hi there @He-mant9 , Please describe your issue in the description so that we can discuss it here.
/triage need-more-information

**Comment by Ritikaa96** [comment]
Hey @He-mant9 , Reminder: Please describe your issue .
If it doesn't exist anymore then you can close it using `/close`
