### ISSUE TITLE
convenient way to copy files automatically to minikube VM

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#1914]
Currently there are kubernetes options that require a path to a file configuration/certification.  Moving additional files into the minikube VM is currently non-trivial and it's possible that the file may not be present in the VM when localkube starts running.  For this use case, we should provide a convenience method for moving files into the VM on boot.  Possible implementations:
.minikube/files folder that is moved into the VM, similar to .minikube/addons (vm_path not easily configurable file to file with this)
minikube start flag: --ssh-file=<host_path>:<vm-path>

**Comment by r2d4** [comment]
+1 for `$MINIKUBE_HOME/files`

**Comment by viteksafronov** [comment]
All the files from `~/.minikube/files` are copying to `/files` directory of VM without preserving their folder structure. Is there a way to automatically copy my files into another location and specific directory, say `/etc/docker/certs.d`?

**Comment by r2d4** [comment]
It might be an interesting idea to let users specify a rootfs at ~/.minikube/files/. and move those files into the VM at root /, while preserving the folder structure.  

cc @aaron-prindle

**Comment by prageethw** [comment]
Guys,

currently, the files in  ~/.minikube/files get coppied  in to / (root) in VM.
is this a feature or defect?
cc: @aaron-prindle  @r2d4
