### ISSUE TITLE
Add automation generating images for for China mirror 

### ISSUE THREAD

**Issue by Bill-GaiPeng** [kubernetes/minikube#19141]
执行 :docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:latest
返回:Error response from daemon: manifest for registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase@sha256:eb04641328b06c5c4a14f4348470e1046bbcf9c2cbc551486e343d3a49db557e not found: manifest unknown: manifest unknown.

**Comment by medyagh** [comment]
@Bill-GaiPeng our images are supposed to be synced by 
https://github.com/kubernetes/minikube/actions/workflows/sync-minikube.yml

**Comment by medyagh** [comment]
@Bill-GaiPeng  we dont push latest, Why are you trying to pull latest if I specify the v0.0.44 it works
docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.44



$ docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.44
v0.0.44: Pulling from google_containers/kicbase
Digest: sha256:889a762d6dd17b44aef674ec5384fd510d3410ad3010943cefd16cc3388505be
Status: Downloaded newer image for registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.44
registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.44

**Comment by ComradeProgrammer** [comment]
Well currently I suggest we just do nothing and wait to see what will happen next.

I will try to illustrate the reason in the office hour. It is not convenient to explain it here.

**Comment by ComradeProgrammer** [comment]
I will talk about this with you in the office hour. Can't really talk about this here.

Basically I think perhaps it is time to depercate the alicloud image mirror, and figure out some other ways (e.g. tarballs) to implement this feature。

**Comment by ComradeProgrammer** [comment]
Update: after the conversation with Steven in minikube office hours, I am going to write an MEP  for this
