### ISSUE TITLE
Files disappear from VM after stopping then starting

### ISSUE THREAD

**Issue by ptrain** [kubernetes/minikube#1916]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**:

**Minikube version**: v0.21.0
- **OS**: OS X 10.11.16
- **VM Driver** : virtualbox
- **ISO version** : minikube-v0.23.0.iso

**What happened**:

Because NFS , 9p, and vboxfs are too slow for my use case, I am using rsync to
send files to the minikube VM. I have tried using two different locations: `/home/docker` and
`/services`.

I send the files with rsync, and then stop the vm, and start it again. Upon starting it, the files
are gone, no matter the location I use.

**What you expected to happen**:

I expect the files to still be present. 

**How to reproduce it**:

Create a file in the VM.
```shell
minikube ssh 'echo "lol" > lol.txt'
```

Verify that the file is there
```
minikube ssh 'ls /home/docker'
lol.txt
```

Stop the VM

```
minikube stop
```

Start the VM again

```
minikube start
```

Verify that the file is gone

```
minikube ssh 'ls /home/docker'
```

**Comment by ptrain** [comment]
Never mind, someone pointed me to the place in the docs that explains this.

**Comment by littleamigo** [comment]
Hi Adam, would you please link to the relevant doc or just paste the explanation? I'm having the same problem and would really appreciate your help.

**Comment by r2d4** [comment]
> The Minikube VM boots into a tmpfs, so most directories will not be persisted across reboots (minikube stop). However, Minikube is configured to persist files stored under the following directories in the minikube VM:

https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md
