### ISSUE TITLE
❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

### ISSUE THREAD

**Issue by rexsunny** [kubernetes/minikube#19173]
### What Happened?

I am using MacOS Chip: Apple M1
MacOS: 14.4.1 (23E224)

niyaaniyan@Niyas-MacBook-Pro Downloads % minikube start
😄  minikube v1.33.1 on Darwin 14.4.1 (arm64)
    ▪ MINIKUBE_ROOTLESS=true
✨  Using the qemu2 driver based on existing profile
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🏃  Updating the running qemu2 "minikube" VM ...
🐳  Preparing Kubernetes v1.30.0 on Docker 26.0.2 ...
🤦  Unable to restart control-plane node(s), will reset cluster: <no value>
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://localhost:53680/apis/storage.k8s.io/v1/storageclasses": dial tcp [::1]:53680: connect: connection refused]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never 
reported healthy: context deadline exceeded

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/16061371/logs.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by spowelljr** [comment]
It works on v1.32.0, but broke on v1.33.0, I'm thinking it might have been caused by an ISO config change?

**Comment by spowelljr** [comment]
Found the commit where the regression was introduced, but it's a big commit, so will need to figure out exactly what part cased the regression.

https://github.com/kubernetes/minikube/commit/ad7fb3992cbbbe5f1bc918adfc75588fab51bc22

**Comment by spowelljr** [comment]
PR for the fix is up, I'll include binaries once it's built so those who are experiencing the issue can use it until the next release.

https://github.com/kubernetes/minikube/pull/19191

**Comment by spowelljr** [comment]
Here are binaries for those experiencing this issue can use until the next release:

macOS arm64: https://storage.googleapis.com/minikube-builds/19191/minikube-darwin-arm64
macOS amd64: https://storage.googleapis.com/minikube-builds/19191/minikube-darwin-amd64
Linux amd64: https://storage.googleapis.com/minikube-builds/19191/minikube-linux-amd64
