### ISSUE TITLE
Exiting due to SVC_UNREACHABLE: service not available: no running pod for service cafe-front found

### ISSUE THREAD

**Issue by mohammedbilal98** [kubernetes/minikube#19174]
### What Happened?

I have created deployment.yaml file and service.yaml file.
 Created deploy and svc using apply cmd.
 I am getting error when ruuning cmd    "minikube service cafe-front --url " that svc is not reachable, also I am unable to get in on browser also.
When I am creating deploy and svc directly from cmd line "kubectl create deploy......"  kubectl expose deploy......    then it's running fine.

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/16062213/logs.txt)
[minikube_service_62d1a514cabede64e495f1a09f720f6d020abcb2_0.log](https://github.com/user-attachments/files/16062304/minikube_service_62d1a514cabede64e495f1a09f720f6d020abcb2_0.log)

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @mohammedbilal98, looking at your logs I see `no running pod for service cafe-front found`. Seems like you don't have any available pods. Could you run `minikube service list` and `kubectl get pods -A` and upload the output of those commands.

**Comment by mohammedbilal98** [comment]
Hi Steven,

Please find attached snap for minikube service list and kubectl get pods

**Comment by spowelljr** [comment]
Jo @mohammedbilal98, I don't see anything attached to your message, I think because you responded via email the attachments don't get included into the message.

**Comment by T-Lakshmi** [comment]
Hi @mohammedbilal98,
This is very common issue user face while binding service and pods. you must specify labels under pod metadata of your pod manifest and provide same labels under selectors of service manifest file.

For more details please refer issue #17092.

**Comment by T-Lakshmi** [comment]
closing this issue as a duplicate one.
/close
