### ISSUE TITLE
Error creating minikube directory

### ISSUE THREAD

**Issue by SaidiMohammed1** [kubernetes/minikube#19218]
### What Happened?

I0710 01:29:22.901695    4814 out.go:291] Setting OutFile to fd 1 ...
I0710 01:29:22.901920    4814 out.go:343] isatty.IsTerminal(1) = true
I0710 01:29:22.901939    4814 out.go:304] Setting ErrFile to fd 2...
I0710 01:29:22.901948    4814 out.go:343] isatty.IsTerminal(2) = true
I0710 01:29:22.902213    4814 root.go:338] Updating PATH: /usr/local/jdk-11.0.2/.minikube/bin
W0710 01:29:22.902347    4814 root.go:314] Error reading config file at /usr/local/jdk-11.0.2/.minikube/config/config.json: open /usr/local/jdk-11.0.2/.minikube/config/config.json: no such file or directory
I0710 01:29:22.905774    4814 out.go:177] 

W0710 01:29:22.908040    4814 out.go:239] ❌  Exiting due to HOST_HOME_MKDIR: Error creating minikube directory: mkdir /usr/local/jdk-11.0.2/.minikube: permission denied
❌  Exiting due to HOST_HOME_MKDIR: Error creating minikube directory: mkdir /usr/local/jdk-11.0.2/.minikube: permission denied
W0710 01:29:22.908057    4814 out.go:239] 

W0710 01:29:22.910299    4814 out.go:239] ╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_status_fda9c3fef358243a9ab294a976f3c7369f3d892e_0.log                  │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_status_fda9c3fef358243a9ab294a976f3c7369f3d892e_0.log                  │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
I0710 01:29:22.912676    4814 out.go:177] 

### Attach the log file

❌  Exiting due to HOST_HOME_MKDIR: Error creating minikube directory: mkdir /usr/local/jdk-11.0.2/.minikube: permission denied

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│    Please also attach the following file to the GitHub issue:                             │
│    - /tmp/minikube_logs_e35fdff86ae07dfec9f07a700bb4b1ce62cab6a5_0.log                    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Ubuntu

### Driver

Docker

**Comment by T-Lakshmi** [comment]
This is duplicate issue of #17289.

**Comment by T-Lakshmi** [comment]
@SaidiMohammed1,
This is basically permition denied issue to write access in directory mkdir /usr/local/jdk-11.0.2/
For solution see #17289 suggestions.

**Comment by T-Lakshmi** [comment]
Closing this as its duplicated one.
/close
