### ISSUE TITLE
How to set eviction policy on minikube cluster?

### ISSUE THREAD

**Issue by veqryn** [kubernetes/minikube#1922]
Minikube keeps deleting my images because the default eviction settings are a bit too aggressive.
I have large images that take a long time to download (hours), so this is really painful.  I would honestly rather minikube fall over or give errors, forcing me to cleanup images myself, rather than deleting certain images.

I've tried using the extra-config option, but when I do the following the minikube cluster won't start:
`minikube start --v=7 --alsologtostderr --vm-driver hyperv --disk-size 90g --memory 12288 --cpus 3 --hyperv-virtual-switch ExternalSwitch --mount --mount-string "C:\Users\xxx\workspace\go\src:/go/src" --extra-config=kubelet.EvictionSoft="memory.available<500Mi,nodefs.available<1Gi,imagefs.available<1Gi" --extra-config=kubelet.EvictionHard="memory.available<300Mi,nodefs.available<600Mi,imagefs.available<600Mi" --extra-config=kubelet.EvictionMinimumReclaim="memory.available=150Mi,nodefs.available=300Mi,imagefs.available=300Mi"`

What is the proper way to set the eviction-hard and eviction-soft settings?

**Comment by dlorenc** [comment]
I think you might want the kubelet garbage collection settings, not the eviction settings: https://kubernetes.io/docs/concepts/cluster-administration/kubelet-garbage-collection/#image-collection

Maybe I'm missing something though.

**Comment by r2d4** [comment]
Can you provide the output of `minikube logs`?

**Comment by veqryn** [comment]
Eviction settings are supposed to be the new garbage collection settings, but I could use either.

The logs were really long, and while cutting them down I think I found the problem: kubelet's require additional settings if you set the eviction thresholds.

This now works:

`minikube start --v=7 --alsologtostderr --vm-driver hyperv --disk-size 90g --memory 12288 --cpus 3 --hyperv-virtual-switch ExternalSwitch --mount --mount-string "C:\Users\cduncan\workspace\go\src:/go/src" --extra-config=kubelet.EvictionSoft="memory.available<500Mi,nodefs.available<1Gi,imagefs.available<1Gi" --extra-config=kubelet.EvictionHard="memory.available<300Mi,nodefs.available<600Mi,imagefs.available<600Mi" --extra-config=kubelet.EvictionMinimumReclaim="memory.available=150Mi,nodefs.available=300Mi,imagefs.available=300Mi" --extra-config=kubelet.EvictionSoftGracePeriod="memory.available=2m,nodefs.available=2m,imagefs.available=2m" --extra-config=kubelet.EvictionMaxPodGracePeriod="60"`

**Comment by MartinKosicky** [comment]
I don't understand why is it kubelet.EvictionSoft but not kubelet.eviction-soft  ...
