### ISSUE TITLE
Cluster deletion issues

### ISSUE THREAD

**Issue by hasues** [kubernetes/minikube#19246]
### What Happened?

Switched from podman to minikube.  Wasn't able to delete cluster.  This prevents creating a new cluster.

### Attach the log file

[minikube_stop_22c5024319685e038d4655ac968ace0a009b34c1_0.log](https://github.com/user-attachments/files/16232211/minikube_stop_22c5024319685e038d4655ac968ace0a009b34c1_0.log)

### Operating System

Ubuntu

### Driver

Docker

**Comment by medyagh** [comment]
@hasues there doesnt seem to be a podman container, 
```
stderr:
Error: no such container minikube
```
do you mind sharing

```podman ps ``
or ```podman ps -a ```

**Comment by hasues** [comment]
The issue was the containers were deleted underneath this when running.  Was migrating different engines (kvm, podman, docker), and this happened.

I found that deleting `$HOME/.minikube` fixed my issue.  This can be closed as it was caused by me, but I was seeking a way to fix it.

**Comment by hasues** [comment]
Removing $HOME/.minikube addressed my issue.
