### ISSUE TITLE
Docker client for minikube still uses docker v1 api

### ISSUE THREAD

**Issue by milehimikey** [kubernetes/minikube#1927]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**: MacOS

**Minikube version**: v0.22.0 
- **OS**:  10.12.6 
- **VM Driver**: virtualbox
- **ISO version**: testing
- **Install tools**: N/A
- **Others**:

**What happened**:
When using docker to pull images from a private registry (Artifactory) minikube's docker client is old and using v1 docker API. Docker's v1 API is no longer supported. This does not allow images to be pulled from the registry at all.

The docker environment:
`
$ eval $(minikube docker-env)
$ docker version
Client:
 Version:      17.06.1-ce
 API version:  1.24
 Go version:   go1.8.3
 Git commit:   874a737
 Built:        Thu Aug 17 22:53:38 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.12.6
 API version:  1.24 (minimum version )
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      linux/amd64
 Experimental: false
`

This registry is setup as an insecure registry:

`
$ minikube start --insecure-registry="private-registry.com:5001"
`

If I try to pull an image (The IP and registry name are obfuscated.):

`
$ docker pull private-registry.com:5001/workspace/r_base:latest
Pulling repository private-registry.com:5001/workspace/r_base
Error while pulling image: Get http://private-registry.com:5001/v1/repositories/workspace/r_base/images: dial tcp: lookup private-registry.com on 10.0.0.0: server misbehaving
`
Note the URI path is v1 which is causing this issue.

**Comment by richardwalsh** [comment]
I am also running into the same issue with `--insecure-registry` using the v1 URL instead of v2 on minikube version v0.22.3

**Comment by bacongobbler** [comment]
This is the docker client retrying the version APIs. First it tries /v2, then falls back to /v1. It's a red herring. The real issue is

> dial tcp: lookup private-registry.com on 10.0.0.0: server misbehaving

This log line tells you that your host uses DNS server 10.0.0.0 and that this DNS server is not working properly. It's quite likely that kube-dns on your minikube cluster is not working properly. I'd check into that.

**Comment by bacongobbler** [comment]
@richardwalsh any recollection on what error you were seeing on your end? Was it the same error?
