### ISSUE TITLE
Proposal: Separate cert should be generated for client auth

### ISSUE THREAD

**Issue by krancour** [kubernetes/minikube#1930]
Working on #1918, I've noticed that minikube uses a single certificate `~/.minikube/apiserver.crt` as the serving cert for the k8s apiserver _and_ for the client (kubectl) to authenticate to the apiserver.

While this works fine and is not a danger of any sort for a local development environment (which is ostensibly what minikube is for), it's not a good representation oh how things are done "in real life."

I'd like to propose that a separate certificate should be generated specifically for the purpose of client authentication.

After #1918 is merged, the amount of work required for this is almost trivial and I'd be happy to take on this work myself.

**Comment by r2d4** [comment]
This SGTM
