### ISSUE TITLE
Enable NVIDIA GPU graphics capabilities

### ISSUE THREAD

**Issue by chubei-urus** [kubernetes/minikube#19318]
### What Happened?

When I run GPU workload in minikube, compute workload works fine, but graphics workload won't work, because `libEGL_nvidia.so.0` cannot be found in the pod container.

According to [NVIDIA container toolkit documentation](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html#driver-capabilities), graphics drivers are not mounted by default, unless the environment variable `NVIDIA_DRIVER_CAPABILITIES` is set to include `graphics`. With patch https://github.com/chubei-urus/minikube/commit/418bbe9cf4ce8ef71c806703730b1f6a2265d8b5 the graphics workload also works.

### Attach the log file

[log.txt](https://github.com/user-attachments/files/16339850/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by medyagh** [comment]
Thank you for creating this issue, do you mind sharing an example of this Before After

**Comment by chubei-urus** [comment]
I'll try to find a minimal example

**Comment by medyagh** [comment]
we should also add an integration test that does NOT run by default and only if we specify it, and we run it ocassionally with a computer with GPU

**Comment by chubei-urus** [comment]
Thanks! I posted the example in #19345. If you see it fit I'll try to make an integration test.

**Comment by medyagh** [comment]
> Thanks! I posted the example in [#19345 (comment)](https://github.com/kubernetes/minikube/pull/19345#issuecomment-2257323608). If you see it fit I'll try to make an integration test.

that sounds like a good idea, if you can plz add that as integration test, and we could add a Condition in the test that if there is no nvidia gpu on the machine, it should skip the test
