### ISSUE TITLE
minikube start issue

### ISSUE THREAD

**Issue by quarantoo** [kubernetes/minikube#19324]
### What Happened?

actually i am trying to start the minikube but i am unable to start it please guide me

### Attach the log file

X Exiting due to GUEST_NOT_FOUND: Failed to start host: error loading existing host. Please try running [minikube delete], then run [minikube start] again: filestore "minikube": open C:\Users\SauravAnand\.minikube\machines\minikube\config.json: The system cannot find the file specified.

### Operating System

Windows

### Driver

None

**Comment by kundan2707** [comment]
seems duplicate of https://github.com/kubernetes/minikube/issues/14788
