### ISSUE TITLE
Error occoured while installing Minikube

### ISSUE THREAD

**Issue by Shahzaibdev78** [kubernetes/minikube#19327]
### What Happened?

While installing minikube on my localhost ubuntu i have faced an error which is mentiond in below screenshot please help me:
![Screenshot from 2024-07-25 17-22-38](https://github.com/user-attachments/assets/df9e4dd0-da19-4622-8cf1-6bd9e04c5d8f)

### Attach the log file

[log.txt](https://github.com/user-attachments/files/16377482/log.txt)

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by kundan2707** [comment]
@Shahzaibdev78 can you check ```curl registry.k8s.io ``` if it accessible.

**Comment by kundan2707** [comment]
configure your VM DNS to resolve registry.k8s.io
