### ISSUE TITLE
Error on Linux host in kubectl installation.

### ISSUE THREAD

**Issue by xavinux** [kubernetes/minikube#1932]
*Environment*: 

-minikube version: v0.22.0
-Linux: Centos 7
-VM Driver: none
-Install tools: Docker
-What happened: Error appears when trying to start a kubernetes cluster locally

Following the Linux Continous Integration with VM support:

curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl

export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true
mkdir $HOME/.kube || true
touch $HOME/.kube/config
export KUBECONFIG=$HOME/.kube/config
sudo -E ./minikube start --vm-driver=none

Get the following error:
**sudo: ./minikube: command not found**

Change to the directory where mnikube binaries files are located to solve this issue:

**cd /usr/local/bin/ 
sudo -E ./minikube start --vm-driver=none**

Have create a minikube.conf file like the following into the /etc/ directory:

export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true
mkdir $HOME/.kube || true
touch $HOME/.kube/config
export KUBECONFIG=$HOME/.kube/config
cd /usr/local/bin/
sudo -E ./minikube start --vm-driver=none
for i in {1..150} # timeout for 5 minutes
do
   ./kubectl get po &> /dev/null
   if [ $? -ne 1 ]; then
      break
  fi
  sleep 2
done

and then run the following command to start a local kubernetes cluster:

**source /etc/minikube.conf**

**Comment by r2d4** [comment]
I would assume your /usr/local/bin is not part of your root's PATH.  If you're running the none driver or minikube as root, you should have these files where root can run them or use an absolute path to the minikube binaries.

**Comment by xavinux** [comment]
Ok, thanks.
