### ISSUE TITLE
Issue while enabling ingress

### ISSUE THREAD

**Issue by Gani-23** [kubernetes/minikube#19333]
### What Happened?

Not sure, i just got notification to upload logs to GitHub issue. it was a bump ran command of 

``` 
minikube addons enable ingress
```

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/16400589/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by kundan2707** [comment]
concerned area
```
I0727 19:35:14.918391    4289 root.go:338] Updating PATH: /home/gani/.minikube/bin
W0727 19:35:14.918504    4289 root.go:314] Error reading config file at /home/gani/.minikube/config/config.json: open /home/gani/.minikube/config/config.json: no such file or directory
I0727 19:35:14.919065    4289 out.go:298] Setting JSON to false
```

**Comment by kundan2707** [comment]
@Gani-23 
Can you check existance of command with following command?
```
cat /home/gani/.minikube/config/config.json
```

**Comment by Gani-23** [comment]
> @Gani-23 Can you check existance of command with following command?
> 
> ```
> cat /home/gani/.minikube/config/config.json
> ```

gani@Eagleye:~$ cd .minikube/
gani@Eagleye:~/.minikube$ ls
addons  ca.pem    files                machines
cache   cert.pem  key.pem              profiles
ca.crt  certs     logs                 proxy-client-ca.crt
ca.key  config    machine_client.lock  proxy-client-ca.key
gani@Eagleye:~/.minikube$ cd profiles/
gani@Eagleye:~/.minikube/profiles$ ls
minikube
gani@Eagleye:~/.minikube/profiles$ cd minikube/
gani@Eagleye:~/.minikube/profiles/minikube$ ls
apiserver.crt           client.crt   proxy-client.crt
apiserver.crt.7fb57e3c  client.key   proxy-client.key
apiserver.key           config.json
apiserver.key.7fb57e3c  events.json
gani@Eagleye:~/.minikube/profiles/minikube$

**Comment by Gani-23** [comment]
![Screenshot 2024-07-30 080233](https://github.com/user-attachments/assets/60251f07-e0e5-441c-a506-92c503bb9326)

- There's config file in profile but not in the provided path

```
cat /home/gani/.minikube/config/config.json

```

**Comment by kundan2707** [comment]
@Gani-23  can you share steps followd while installation of minikube?

**Comment by Gani-23** [comment]
I reinstalled it again, this time it worked.
