### ISSUE TITLE
C:\Windows\System32>minikube start --driver=hyper

### ISSUE THREAD

**Issue by Abhayraj7ingh** [kubernetes/minikube#19350]
### What Happened?

C:\Windows\System32>minikube start --driver=hyperv
* minikube v1.33.1 on Microsoft Windows 11 Enterprise 10.0.22631.3880 Build 22631.3880
* Using the hyperv driver based on existing profile
* Starting "minikube" primary control-plane node in "minikube" cluster
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. Running "minikube delete" may fix it: provision: IP not found

X Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: provision: IP not found
*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

C:\Windows\System32>minikube logs --file=log.txt

X Exiting due to DRV_CP_ENDPOINT: Unable to get control-plane node minikube endpoint: failed to lookup ip for ""
* Suggestion:

    Recreate the cluster by running:
    minikube delete <no value>
    minikube start <no value>

### Operating System

Windows

### Driver

Hyper-V

**Comment by kundan2707** [comment]
@Abhayraj7ingh 
have you fixed issue by executing 
```minikube delete```
```minikube start```
