### ISSUE TITLE
 service not available: no running pod for service hello-minikube found

### ISSUE THREAD

**Issue by NMishra27** [kubernetes/minikube#19352]
### What Happened?

 Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found

### Attach the log file

[minikube_service_4910744035c3cabf9ca82106a88834095119b85e_0.log](https://github.com/user-attachments/files/16437000/minikube_service_4910744035c3cabf9ca82106a88834095119b85e_0.log)

### Operating System

Windows

### Driver

Docker

**Comment by kundan2707** [comment]
@NMishra27 can you share complete steps you followed for installation and service creation?
