### ISSUE TITLE
Not able to start minikube with --vm-driver=xhyve

### ISSUE THREAD

**Issue by moagarw** [kubernetes/minikube#1942]
BUG REPORT

Please provide the following details:
minikube version - v0.22.0
OS - macOS Sierra 10.12.6
Docker version 17.06.2-ce, build cec0b72
docker-machine-driver-xhyve HEAD-a2060c0

Command executed . - 
minikube start --memory=4096 --vm-driver=xhyve

Error shown - 
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Downloading Minikube ISO
 106.36 MB / 106.36 MB [============================================] 100.00% 0s
E0909 13:08:03.188906   38471 start.go:143] Error starting host: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string.

**Comment by yimeng** [comment]
same issue
minikube version: v0.22.0
10.12.6 (16G29)
 docker Version:      17.06.2-ce
/usr/local/Cellar/docker-machine-driver-xhyve/HEAD-a2060c0


I0911 13:59:03.424715   39054 cache_images.go:154] Attempting to cache image: gcr.io/google-containers/kube-addon-manager:v6.4-beta.2 at /Users/yimeng/.minikube/cache/images/gcr.io/google-containers/kube-addon-manager_v6.4-beta.2
 106.36 MB / 106.36 MB [============================================] 100.00% 0s
E0911 14:01:05.446758   39054 start.go:143] Error starting host: Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string.

 Retrying.
E0911 14:01:05.446783   39054 start.go:149] Error starting host:  Error creating new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:

**Comment by yimeng** [comment]
brew uninstall docker-machine-driver-xhyve
Uninstalling /usr/local/Cellar/docker-machine-driver-xhyve/HEAD-a2060c0... (3 files, 10.5MB)
➜  go brew install docker-machine-driver-xhyve

uninstall --head version
install 
docker-machine-driver-xhyve: stable 0.3.3 (bottled), HEAD

it works!

**Comment by Lookyan** [comment]
Yes, they broke compatibility in master. With current version of minikube we should use 0.3.3 driver.
May be we should write some info about it in docs.

**Comment by moagarw** [comment]
thanks @yimeng .. it worked :)
