### ISSUE TITLE
minikube status should return a value

### ISSUE THREAD

**Issue by bryanlarsen** [kubernetes/minikube#1944]
To facilitate scripting, `minikube status` should return a non-zero value if it's not running & correctly configured.

**Comment by r2d4** [comment]
Makes sense to me. Minikube status reports 3 statuses right now: the minikube VM, the cluster, and the kubeconfig context. It should probably return a non-zero value if any of these is misconfigured.

**Comment by mahdix** [comment]
I'll pick up this one.

**Comment by ulyssessouza** [comment]
Ops... Sorry @mahdix I didn't see that you were about to take this one. I just started and did a PR before seeing your post.

**Comment by mahdix** [comment]
No worries @ulyssessouza

**Comment by r2d4** [comment]
Fixed by #2121
