### ISSUE TITLE
No documentation on --vm-driver=none

### ISSUE THREAD

**Issue by cdrage** [kubernetes/minikube#1946]
The only indication about documentation is the README.md where it indicates that --vm-driver=none requires Docker.

However, running `docker ps --all` produces nothing..

Can we add some documentation to `docs/drivers.md`?

**Comment by timoreimann** [comment]
The none driver seems to be fairly unknown. Better documentation should help with that IMO.

/remove-lifecycle stale

**Comment by jglick** [comment]
Maybe because

```
WARNING: IT IS RECOMMENDED NOT TO RUN THE NONE DRIVER ON PERSONAL WORKSTATIONS
	The 'none' driver will run an insecure kubernetes apiserver as root that may leave the host vulnerable to CSRF attacks
```

**Comment by tstromberg** [comment]
Dupe of #2575 (choosing it because it has more comments)
