### ISSUE TITLE
Unable to start my minikube 

### ISSUE THREAD

**Issue by NamanGupta31** [kubernetes/minikube#19526]
### What Happened?

Hi,

Even after installing Minikube and kubectl and adding both to the environment variable path, I am encountering an issue while running minikube start. I have also installed Docker Desktop, but the issue persists.

I am attaching my log file for reference.
:))

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/16782639/logs.txt)

### Operating System

Windows

### Driver

None

**Comment by xcarolan** [comment]
Looks like a docker issue (is docker running?) try docker stats

**Comment by NamanGupta31** [comment]
The issue has been resolved now, it was more hypervisor issue. I uninstalled the virtual box and tick the hyper-v installed in my laptop, finally it worked. :))

**Comment by NamanGupta31** [comment]
Closing the issue now. Thanks
