### ISSUE TITLE
Registry proxy image not pullable

### ISSUE THREAD

**Issue by matzew** [kubernetes/minikube#19538]
### What Happened?

Starting minikue, I get:

```
Failed to pull image "gcr.io/k8s-minikube/kube-registry-proxy:0.0.6@sha256:b3fa0b2df8737fdb85ad5918a7e2652527463e357afff83a5e5bb966bcedc367": Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

doing a manual pull, like:
```
podman pull gcr.io/k8s-minikube/kube-registry-proxy:0.0.6
Trying to pull gcr.io/k8s-minikube/kube-registry-proxy:0.0.6...
Error: initializing source docker://gcr.io/k8s-minikube/kube-registry-proxy:0.0.6: reading manifest 0.0.6 in gcr.io/k8s-minikube/kube-registry-proxy: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
```

gove the same

### Attach the log file

Failed to pull image "gcr.io/k8s-minikube/kube-registry-proxy:0.0.6@sha256:b3fa0b2df8737fdb85ad5918a7e2652527463e357afff83a5e5bb966bcedc367": Error response from daemon: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication

### Operating System

Redhat/Fedora

### Driver

KVM2

**Comment by youngcm2** [comment]
https://github.com/kubernetes/minikube/issues/19535#issuecomment-2317318826

**Comment by spowelljr** [comment]
See https://github.com/kubernetes/minikube/issues/19541, this should now be resolved.
