### ISSUE TITLE
vmlinuz64: no such file or directory

### ISSUE THREAD

**Issue by valentin2105** [kubernetes/minikube#1953]
**What happened**:

I try to launch minikube with Xhyve VM, but it say, after downloaded the ISO : 

```
E0912 16:08:11.144278   73598 start.go:122] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: open /Users/Valentin/.minikube/machines/minikube/b2d-image/boot/vmlinuz64: no such file or directory
```
**What you expected to happen**:
Minikube launch properly

**How to reproduce it** (as minimally and precisely as possible):

Install Minikube v0.18.0 ou v0.22.1 and launch :  

`minikube start --vm-driver xhyve`

**Comment by r2d4** [comment]
What version of the xhyve driver are you using?

And if possible, what version of the minikube-iso are you using?

**Comment by valentin2105** [comment]
@r2d4 

I use `docker-machine-driver-xhyve/0.2.3`, Minikube `v0.22.1` and ISO `minikube-v0.23.3.iso`

Full error : 


```
 minikube start --vm-driver xhyve

 106.36 MB / 106.36 MB [============================================] 100.00% 0s
E0915 07:45:52.656073   70445 start.go:143] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: open /Users/Valentin/.minikube/machines/minikube/b2d-image/boot/vmlinuz64: no such file or directory.

 Retrying.
E0915 07:45:52.662745   70445 start.go:149] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: open /Users/Valentin/.minikube/machines/minikube/b2d-image/boot/vmlinuz64: no such file or directory
========================================================

```

**Comment by r2d4** [comment]
Can you try updating to the latest docker-machine-driver-xhyve and running a `minikube delete` and `minikube start --vm-driver xhyve`?

**Comment by valentin2105** [comment]
Thanks it work with `0.3.3` docker-machine-xhyve !! 
Thanks a lot.
