### ISSUE TITLE
Add documentation for this repo's kvm driver

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#1954]
ref #1828

**Comment by rubenv** [comment]
@r2d4 any quick instructions available anywhere? Would love to give the new KVM a go, but I have no idea where to start.

**Comment by r2d4** [comment]
@rubenv You can build it from the repo with `make install-kvm` (you will need to install the libvirt-dev package)

or you can grab it from any CI build

https://storage.googleapis.com/minikube-builds/PR_NUMBER/docker-machine-driver-kvm2

and put it in your path and set --vm-driver to kvm2

**Comment by rubenv** [comment]
@r2d4 do I still need the normal `docker-machine` binary?

**Comment by r2d4** [comment]
No, this should replace that one.
