### ISSUE TITLE
Cannot Make Secure Connection To GitHUb

### ISSUE THREAD

**Issue by ryanjbaxter** [kubernetes/minikube#1955]
**Environment**:

```
minikube version: v0.22.0

OS:
cat: /etc/os-release: No such file or directory

VM driver:
    "DriverName": "virtualbox",
```
```
ISO version
        "Boot2DockerURL": "file:///Users/ryanjbaxter/.minikube/cache/iso/minikube-v0.23.3.iso",
```

**What happened**:
Cannot make secure connection to github from container running on Minikube.  If I `cURL` from within the container I get this
```
/ # curl -v https://github.com
* Rebuilt URL to: https://github.com/
*   Trying 192.30.253.113...
* TCP_NODELAY set
* Connected to github.com (192.30.253.113) port 443 (#0)
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* Unknown SSL protocol error in connection to github.com:443
* Curl_http_done: called premature == 0
* Closing connection 0
curl: (35) Unknown SSL protocol error in connection to github.com:443
```

If I run the same container on Docker on my machine there is no problem running the above `cURL` command.

**What you expected to happen**:
Be able to make TLS connection.

**How to reproduce it** (as minimally and precisely as possible):
Run the container `ryanjbaxter/greeting-config-server` and ssh into the container and run the `cURL` command.

**Comment by ryanjbaxter** [comment]
Problem ended up being incorrect configuration with Istio Egress

**Comment by dolfelt** [comment]
@ryanjbaxter I'm having similar issues. What were the configuration issues you needed to fix the egress issues?

**Comment by ryanjbaxter** [comment]
@dolfelt read the section titled Calling external services directly here https://istio.io/docs/tasks/traffic-management/egress.html#calling-external-services-directly

**Comment by dolfelt** [comment]
@ryanjbaxter Ah yes, I'm able to get that working. Did you get the egress proxy working?

**Comment by ryanjbaxter** [comment]
I had to allow outgoing traffic for the given ip ranges like it described
