### ISSUE TITLE
minikube ssh doesn't recognize the end of transmission signal from standard input

### ISSUE THREAD

**Issue by pbochynski** [kubernetes/minikube#1957]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug

**Environment**: 

**Minikube version** (use `minikube version`): 0.22.0 & 0.22.1
- **OS** (e.g. from /etc/os-release): mac OS 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): testing
- **Install tools**: 
- **Others**:

**What happened**:
I have a script that copies some files to minikube machine. In general it is something like this:

    cat | minikube ssh "cat"

It worked with minikube 0.21.0. With 0.22.0 and 0.22.1 the ssh command waits for the end of input stream forever. It doesn't recognize that the file was already transmitted. The same happens with standard input.

**What you expected to happen**:

I expect that the minikube ssh process will exit after end of the transmission (Ctrl+D)

**How to reproduce it** (as minimally and precisely as possible):

    $ curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.22.0/minikube-darwin-amd64 &&  chmod +x minikube && sudo mv minikube /usr/local/bin/

    $ minikube delete
    $ sudo rm -Rf ~/.minikube
    $ minikube config set kubernetes-version v1.7.5
    $ minikube start  --vm-driver=xhyve
    
    $ cat | minikube ssh "cat"

Write couple of characters and type Ctrl+D. Nothing happens.
If you change version to 0.21.0 then after Ctrl+D command is finished.

**Comment by zakame** [comment]
Can replicate even on minikube 0.23, as I cannot use `docker save | minikube ssh docker load` pattern:

```
 ± docker save perl:5.26 | minikube ssh docker load                  
requested load from stdin, but stdin is empty
 ± 
```

**Comment by r2d4** [comment]
This is a result of moving over to using the "SSHRunner" which uses the native go ssh library rather than the libmachine ssh library
https://github.com/kubernetes/minikube/pull/1844

I'll have to investigate exactly what was added in the libmachine ssh library to capture the signal.

**Comment by r2d4** [comment]
#2110 will help

**Comment by piotrminkina** [comment]
> Can replicate even on minikube 0.23, as I cannot use `docker save | minikube ssh docker load` pattern:

@zakame Try this:
```
docker save perl:5.26 | (eval `minikube docker-env`; docker load)
```
