### ISSUE TITLE
Remove helm tiller add-on

### ISSUE THREAD

**Issue by tylerauerbeck** [kubernetes/minikube#19604]
### What Happened?

Helm v2 / Tiller are well past their deprecation date at this point. Is it worth removing the add-on at this point to further discourage its use?

https://github.com/kubernetes/minikube/tree/master/deploy/addons/helm-tiller

https://helm.sh/blog/helm-v2-deprecation-timeline/

### Attach the log file

N/A

### Operating System

None

### Driver

None

**Comment by medyagh** [comment]
Thats a good idea ! I would be happy to merge a PR that removes that

**Comment by tylerauerbeck** [comment]
@medyagh I'd be happy to take a swing at this. Just wanted to make sure I wasn't removing something I shouldn't before I dug into it!
