### ISSUE TITLE
Provide a way to disable storage provisioner in minikube

### ISSUE THREAD

**Issue by taherv** [kubernetes/minikube#1961]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.22.1
- **OS** (e.g. from /etc/os-release): OSX
- **VM Driver** xhyve
- **Kubernetes version** 1.7.5

**What happened**: Cannot use an external dynamic provisioner with minikube. I created my own storageclass, with a provisioner pod. But when I created a pvc which references my provisioner using the storageClassName attribute in its spec, my provisioner pod never gets called. Instead the default storage provisioner in localkube tries to process it and prints an error message : 
```
Sep 14 04:55:35 minikube localkube[2628]: E0914 04:55:35.527076    2628 controller.go:405] Claim "default/pure-claim": Unknown provisioner "pure-provisioner" requested in storage class "pure"
```
Here pure-claim is my claim name, "pure" is my storage class name, and "pure-provisioner" is my dynamic provisioner.
This log line comes from minikube code (not kubernetes code). It is from `vendor/github.com/r2d4/external-storage/lib/controller/controller.go` in minikube source tree.

Upon, more digging, I found the minikube starts a provisioner unconditionally at https://github.com/kubernetes/minikube/blob/e6da47f5a1cd3e4197455a84925790380f8415d6/cmd/localkube/cmd/start.go#L124

**What you expected to happen**: I should be able to use my dynamic provisioner by referencing it by storageclassname in my PVC. No other provisioners should even get called if they are not from this storage class.

**How to reproduce it** (as minimally and precisely as possible):
1. Create your own storage class, and deploy your own provisioner
2. Create a pvc which references your storage class
3. Wait, wait, wait ... your provisioner will never get called. Instead the default provisioner will keep throwing error messages about provisioner and class name mismatch .... see above for error message.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
https://github.com/kubernetes/minikube/pull/1289 says that it will disable the provisioner addon, but it is misnamed. It disables/removes **just the storage class**, and even that requires a minikube restart. The provisioner is started unconditionally in golang code, and there is no way to not run it in localkube.

How are we supposed to run dynamic provisioners in minikube 0.22 ? 
As far as I remember I was able to do it (dynamically provision my pvcs using my provisioner and my storageclass) in minikube 0.20 with kubernetes 1.6.x

**Comment by taherv** [comment]
FWIW, my provisioner is written based on the hostpath demo provisioner in github.com/kubernetes-incubator/external-storage/

**Comment by taherv** [comment]
Looking for pointers to which logging should I increase to get more diagnostics .....

**Comment by r2d4** [comment]
You're right, theres no way to actually stop the provisioner. We could add a flag to localkube to conditionally run or not run the provisioner.

**Comment by taherv** [comment]
Since the default storage class is an addon, and the provisioner only makes sense with a storage class (otherwise minikube doesnt remain a general system), it makes sense to "run" the storage provisioner only when the default-storageclass addon is enabled.

My request : 
a. Rename default-storageclass addon to "default-dynamicprovisioner"
b. When this addon is enabled, run the provisioner, and register the storage class with kubernetes
c. When this addon is disabled, stop the provisioner, and delete the storage class.
As far as running the storage provisioner is concerned, it should be just a Pod/ReplicationController, not embedded inside localkube. This ensures that enabling/disabling this addon does not require minikube restart.

**Comment by r2d4** [comment]
We initially didn't do (c) because we didn't want to increase startup time more than we needed to.  However, we recently added caching to all the images used in localkube, so we could revisit this and publish a container.  I think doing that would make this much simpler and more portable.  That would be more in line with the other addons that we offer anyways.
