### ISSUE TITLE
Minikube iso image build assumes GOPATH has only one path leading to make error: ‘multiple target patterns. Stop.’

### ISSUE THREAD

**Issue by filmil** [kubernetes/minikube#1963]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**What happened**:
minikube Makefile assumes $GOPATH contains only one path.  In reality, $GOPATH may contain
multiple colon-sepapated paths.  This confuses GNU Make and it barfs with `multiple target patterns. Stop.`

**What you expected to happen**:
It should be possible to build minikube regardless of what sits in GOPATH, as long as the setting is correct.

**How to reproduce it** (as minimally and precisely as possible):

export GOPATH=/some/dir/go:/some/other/dir/go
Then try to build the Minikube ISO image, for example.

**Comment by r2d4** [comment]
Good catch.  I would assume that its erroring on these rules

```makefile
$(GOPATH)/bin/go-bindata:
	GOBIN=$(GOPATH)/bin go get github.com/jteeuwen/go-bindata/...
```

```makefile

pkg/minikube/assets/assets.go: out/localkube $(GOPATH)/bin/go-bindata $(shell find deploy/addons -type f)
	$(GOPATH)/bin/go-bindata -nomemcopy -o pkg/minikube/assets/assets.go -pkg assets ./out/localkube deploy/addons/...
```

**Comment by filmil** [comment]
Well, I caught it only because I stepped on it. :)
