### ISSUE TITLE
How to setup addons on Windows?

### ISSUE THREAD

**Issue by CyberPartyZan** [kubernetes/minikube#19684]
### What Happened?

Hi everyone!

https://minikube.sigs.k8s.io/docs/handbook/addons/gcp-auth/

I'm trying to go through the Kubernetes tutorials and want to test minikube addons. I stuck on the one above, as I understand I should install "gcloud" SDK on my VM. But how to get access to the VM? "minikube ssh" enter some inside docker container, not the VM I need. Did I miss something? Or I need to configure gloud and other needed software on my host machine?

Anyway this tiny things (and maybe for someone obvious, but unfortunately not for me) are not covered by minikube Wiki.

I use Windows 11, so that's could be a problem. If it's easier to run minikube on Linux to not suffer from a lack of information in tutorials, please suggest me this way, because I can't make right decision by myself.

And sorry if I shouldn't report the issue here on GitHub, but Wiki page lead me here to make some feedback.

### Attach the log file

[log.txt](https://github.com/user-attachments/files/17088807/log.txt)

### Operating System

Windows

### Driver

Hyper-V

**Comment by spowelljr** [comment]
Hi @CyberPartyZan, you don't need to install anything on the VM. You just need to make sure you have `gcloud` installed on your Windows machine and that you're logged in. Then you can enable the gcp-auth addon on minikube start with `minikube start --addons=gcp-auth` or after you've already stated the cluster with `minikube addons enable gcp-auth` and the rest should be handled for you automatically.

**Comment by Ritikaa96** [comment]
Hey @CyberPartyZan if your question is answered then you can close this issue with `/close`
