### ISSUE TITLE
Stuck on Container Checkpointing – Need Guidance

### ISSUE THREAD

**Issue by binaryBard97** [kubernetes/minikube#19686]
### What Happened?

Actual behavior: When starting minikube with : 
`--extra-config=kubelet.feature-gates=ContainerCheckpoint=true`

` sudo journalctl -u kubelet | grep "ContainerCheckpoint"` returns nothing.

Expected behavior: 
`ContainerCheckpoint` to be enabled in `/var/lib/kubelet/config.yaml` and ` sudo journalctl -u kubelet | grep "ContainerCheckpoint"`  to return something.

And `sudo journalctl -u kubelet` logs shows an error : `
Sep 22 15:33:27 minikube kubelet[1133]: E0922 15:33:27.815325    1133 run.go:72] "command failed" err="failed to load kubelet config file, path: /var/lib/kubelet/config.yaml, error: failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file \"/var/lib/kubelet/config.yaml\", error: open /var/lib/kubelet/config.yaml: no such file or directory"`

but inside minikube cluster, the config is PRESENT at `/var/lib/kubelet
root@minikube:/var/lib/kubelet# `
but I do not see my feature gate enabled 

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/17090251/logs.txt)
[kubelet-logs.txt](https://github.com/user-attachments/files/17090252/kubelet-logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by binaryBard97** [comment]
I've tried both approaches, and I've attached the log file for the second method. However, I still don't see my feature gate enabled in `/var/lib/kubelet/config.yaml`

[log.txt](https://github.com/user-attachments/files/17137972/log.txt)

**Comment by spowelljr** [comment]
The kubelet feature flags are stored to a drop-in config file located at: `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`

```
$ minikube start --extra-config=kubelet.feature-gates=ContainerCheckpoint=true
😄  minikube v1.34.0 on Darwin 14.7 (arm64)
✨  Automatically selected the docker driver. Other choices: qemu2, ssh, vfkit (experimental)
📌  Using Docker Desktop driver with root privileges
👍  Starting "minikube" primary control-plane node in "minikube" cluster
🚜  Pulling base image v0.0.45-1727108449-19696 ...
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
🐳  Preparing Kubernetes v1.31.1 on Docker 27.3.1 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

$ minikube ssh -- sudo cat /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
[Unit]
Wants=docker.socket

[Service]
ExecStart=
ExecStart=/var/lib/minikube/binaries/v1.31.1/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/var/lib/kubelet/config.yaml --feature-gates=ContainerCheckpoint=true --hostname-override=minikube --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=192.168.49.2

[Install]
```

**Comment by binaryBard97** [comment]
Sorry and thanks! I know this isn't the right place, but I've been stuck for days and I'm new to Kubernetes.

**Comment by binaryBard97** [comment]
Hello,

I'm trying to update the CRI-O runtime to version 1.25 or higher. I need this for setting up my environment in Minikube to checkpoint containers, following the instructions in this [article](https://kubernetes.io/blog/2022/12/05/forensic-container-checkpointing-alpha/). The article mentions that version 1.25 of CRI-O supports forensic container checkpointing.

Could you please guide me on how to update the CRI-O runtime to the required version?

---
`minikube start --driver=docker --container-runtime=cri-o --extra-config=kubelet.feature-gates=ContainerCheckpoint=true`
`minikube ssh`
<img width="1003" alt="Screenshot 2024-09-28 at 9 56 32 PM" src="https://github.com/user-attachments/assets/a5363294-e0c4-4e62-9c5c-019da3f3e12b">

GitID: 5c35d75


Thanks.

**Comment by binaryBard97** [comment]
Hello,

I was able to update the CRI-O version, but I'm still stuck on my main goal, which is checkpointing a container. I've been working on this for the last two weeks. I know this might not be the best place to ask, but I'd really appreciate it if you could point me to where I might find some help.

I think I'm following all the right steps (or at least I hope so). Here's what I've done so far: 

- [ ] criu version 
<img width="278" alt="Screenshot 2024-09-29 at 6 51 59 PM" src="https://github.com/user-attachments/assets/0ffdc241-e07e-4e00-a0a3-057b1d4c382a">

- [ ] crio version
<img width="1257" alt="Screenshot 2024-09-29 at 6 52 17 PM" src="https://github.com/user-attachments/assets/d37df488-0ceb-49d3-8ac2-0dd2fc616c1e">

- [ ] criu enabled in `cd /etc/crio/crio.conf ` --> [crio.runtime] enable_criu_support = true
<img width="594" alt="Screenshot 2024-09-29 at 6 53 08 PM" src="https://github.com/user-attachments/assets/85c0cf9b-445b-4986-83a9-934ef80b01a8">

- [ ] checkpoint feature gate enabled in `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`
<img width="1665" alt="Screenshot 2024-09-29 at 6 53 39 PM" src="https://github.com/user-attachments/assets/efca3f68-215c-4489-b237-544b93cde57a">

- [ ] certificates present
- [ ] did 
```
kubectl proxy --port=10250
Starting to serve on 127.0.0.1:10250
```
- [ ] redis-pod.yaml
```
apiVersion: v1
kind: Pod
metadata:
  name: redis-p
  namespace: default
spec:
  containers:
    - name: redis-c
      image: docker.io/redis
      ports:
        - containerPort: 6379
```
- [ ] `k get pods -n default -o wide`
<img width="742" alt="Screenshot 2024-09-29 at 6 55 59 PM" src="https://github.com/user-attachments/assets/ff088295-2d8c-4d0d-a273-e57b6b81f66f">



BUT still CURL cmd fails:
<img width="754" alt="Screenshot 2024-09-29 at 6 54 48 PM" src="https://github.com/user-attachments/assets/c6a66560-50a5-40fc-85dd-d94011d6af01">

**Comment by binaryBard97** [comment]
not a minikube issue
