### ISSUE TITLE
can't start kube_apiserver successfully

### ISSUE THREAD

**Issue by louhuanbin** [kubernetes/minikube#19699]
### What Happened?

Error: Failed to create minikube cluster. E0924 11:27:57.328524 21064 cache.go:203] Error downloading kic artifacts: not yet implemented, see issue #8426 X Exiting due to RUNTIME_ENABLE: unknown network plugin: *

### Attach the log file

E0924 11:30:38.128704   25208 logs.go:192] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.24.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.24.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

### Operating System

Windows

### Driver

Podman

**Comment by spowelljr** [comment]
Hi @louhuanbin, based on the logs you've provided it looks like you're on an older version of minikube. Even though you got an error while trying to create the logs, those are just errors trying to grab logs from pods, but the log file itself should still have been generated (these errors are suppressed on mew minikube versions). Could you please upload the generated log file as there's not enough included in the ticket to go off of.

**Comment by spowelljr** [comment]
Hi @louhuanbin, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.
