### ISSUE TITLE
Run conformance tests in a CI system.

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#197]

**Comment by luxas** [comment]
+100, but we'd have to ignore the two flakes for now (until you've fixed them at HEAD)

**Comment by luxas** [comment]
cc @kubernetes/test-infra-maintainers 
Maybe a jenkins job would fix this?

**Comment by ixdy** [comment]
I think we're already running the conformance tests against GCE and GKE, though they aren't in their own separate build.

cc @kubernetes/sig-testing

**Comment by spxtr** [comment]
Do you mean conformance tests against minikube? If you can set up your own CI then we can gather your test results and display them on testgrid and the like. See the docs in kubernetes/test-infra.

**Comment by dlorenc** [comment]
Sounds good. I'll spin up some CI infra this week. We'll need physical Mac and Windows slaves.

**Comment by dlorenc** [comment]
I made some progress, but this isn't done yet. I'll keep working on it this week. I have a physical OSX machine ready to act as a Jenkins slave.

**Comment by dlorenc** [comment]
I have a Jenkins setup that's running the integration tests on OSX for both virtualbox and xhyve.

Next step is to publish the test results to the k8s testgrid and setup email notifications.

**Comment by luxas** [comment]
I'm interested in the Jenkins setup...
Is it possible to opensource it too?

**Comment by dlorenc** [comment]
It's just a Jenkins instance I have deployed behind our firewall (following the same procedures that the main Kubernetes Jenkins instance runs in). It runs on a Linux VM, and connects to a Mac Mini I have that's configured as a slave.

I'm not sure how to expose it externally in a safe way, but would be happy to if anyone can point me at a good method.

What in particular would you like to see open sourced?

**Comment by luxas** [comment]
Nothing special really, just wondering since I haven't set up jenkins myself yet
But I'm soon planning to set it up on Raspberry Pis
Just if there's some special config when CI-ing Kubernetes...

**Comment by spxtr** [comment]
We don't expose our Jenkins instances externally since they're a security nightmare. Instead, we configure our jobs to upload their test results to a public GCS bucket and all of our tools consume that.

**Comment by dlorenc** [comment]
@spxtr do you have any pointers to how (or if?) github webhooks are setup, with Jenkins behind a firewall?

**Comment by spxtr** [comment]
We poll github using the github pull request builder plugin. Our job configs are in [the test-infra repo](https://github.com/kubernetes/test-infra/tree/master/jenkins). To be perfectly honest, Jenkins has caused us a ton of pain, so if you can avoid using it then do so.

See [this doc](https://github.com/kubernetes/test-infra/blob/master/docs/federated_testing.md) for more info.

**Comment by dlorenc** [comment]
Thanks for the pointer!

Unfortunately we need to run e2e tests on physical machines (none of the other providers I've checked out support nested virtualization), so Jenkins appears to be our only option for now.

**Comment by dlorenc** [comment]
Tests are now running in Jenkins. I still have more cleanup to do, but closing for now.
