### ISSUE TITLE
Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found

### ISSUE THREAD

**Issue by jaiabbott** [kubernetes/minikube#19705]
### What Happened?

I am following Step 4 of the documentation https://minikube.sigs.k8s.io/docs/start/?arch=%2Fmacos%2Farm64%2Fstable%2Fbinary+download and it gives an error "https://minikube.sigs.k8s.io/docs/start/?arch=%2Fmacos%2Farm64%2Fstable%2Fbinary+download" while executing "kubectl get services hello-minikube"

### Attach the log file

Log file created at: 2024/09/25 15:31:18
Running on machine: C02HD3BQQ05N
Binary: Built with gc go1.22.5 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0925 15:31:18.655399   42087 out.go:345] Setting OutFile to fd 1 ...
I0925 15:31:18.656104   42087 out.go:397] isatty.IsTerminal(1) = true
I0925 15:31:18.656106   42087 out.go:358] Setting ErrFile to fd 2...
I0925 15:31:18.656109   42087 out.go:397] isatty.IsTerminal(2) = true
I0925 15:31:18.656467   42087 root.go:338] Updating PATH: /Users/SINGHWX/.minikube/bin
I0925 15:31:18.657648   42087 mustload.go:65] Loading cluster: minikube
I0925 15:31:18.658382   42087 config.go:182] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.31.0
I0925 15:31:18.658878   42087 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0925 15:31:18.679134   42087 host.go:66] Checking if "minikube" exists ...
I0925 15:31:18.679665   42087 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0925 15:31:18.695520   42087 api_server.go:166] Checking apiserver status ...
I0925 15:31:18.696394   42087 ssh_runner.go:195] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0925 15:31:18.696454   42087 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0925 15:31:18.710575   42087 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:65097 SSHKeyPath:/Users/SINGHWX/.minikube/machines/minikube/id_rsa Username:docker}
I0925 15:31:18.804129   42087 ssh_runner.go:195] Run: sudo egrep ^[0-9]+:freezer: /proc/2148/cgroup
W0925 15:31:18.811630   42087 api_server.go:177] unable to find freezer cgroup: sudo egrep ^[0-9]+:freezer: /proc/2148/cgroup: Process exited with status 1
stdout:

stderr:
I0925 15:31:18.811737   42087 ssh_runner.go:195] Run: ls
I0925 15:31:18.814569   42087 api_server.go:253] Checking apiserver healthz at https://127.0.0.1:65096/healthz ...
I0925 15:31:18.823496   42087 api_server.go:279] https://127.0.0.1:65096/healthz returned 200:
ok
I0925 15:31:18.823507   42087 host.go:66] Checking if "minikube" exists ...
I0925 15:31:18.823811   42087 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0925 15:31:18.869900   42087 service.go:214] Found service: &Service{ObjectMeta:{hello-minikube  default  0c11c0c7-af0d-4cc4-8aa4-1857419f1df0 991 0 2024-09-25 14:58:26 -0500 CDT <nil> <nil> map[app:hello-minikube] map[] [] [] [{kubectl-expose Update v1 2024-09-25 14:58:26 -0500 CDT FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":8080,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:8080,TargetPort:{0 8080 },NodePort:31616,AppProtocol:nil,},},Selector:map[string]string{app: hello-minikube,},ClusterIP:10.105.13.253,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.105.13.253],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,TrafficDistribution:nil,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0925 15:31:18.870957   42087 host.go:66] Checking if "minikube" exists ...
I0925 15:31:18.871132   42087 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0925 15:31:18.903489   42087 out.go:201] 
W0925 15:31:18.910385   42087 out.go:270] ❌  Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found
W0925 15:31:18.910393   42087 out.go:270] 
W0925 15:31:18.912803   42087 out.go:293] [31m╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                                                            [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                          [31m│[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                   [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                                                            [31m│[0m
[31m│[0m    - /var/folders/lr/g5p2mf797ns4bg1csblg19pc0000gq/T/minikube_service_533a182a0559351fc1399d159b6978096030941d_0.log    [31m│[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0925 15:31:18.920209   42087 out.go:201] 
Log file created at: 2024/09/25 15:47:55
Running on machine: C02HD3BQQ05N
Binary: Built with gc go1.22.5 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0925 15:47:55.745416   45958 out.go:345] Setting OutFile to fd 1 ...
I0925 15:47:55.745808   45958 out.go:397] isatty.IsTerminal(1) = true
I0925 15:47:55.745810   45958 out.go:358] Setting ErrFile to fd 2...
I0925 15:47:55.745813   45958 out.go:397] isatty.IsTerminal(2) = true
I0925 15:47:55.745944   45958 root.go:338] Updating PATH: /Users/SINGHWX/.minikube/bin
I0925 15:47:55.747814   45958 mustload.go:65] Loading cluster: minikube
I0925 15:47:55.748288   45958 config.go:182] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.31.0
I0925 15:47:55.749061   45958 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0925 15:47:56.033091   45958 host.go:66] Checking if "minikube" exists ...
I0925 15:47:56.033445   45958 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0925 15:47:56.322254   45958 api_server.go:166] Checking apiserver status ...
I0925 15:47:56.322410   45958 ssh_runner.go:195] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0925 15:47:56.322466   45958 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0925 15:47:56.597028   45958 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:65097 SSHKeyPath:/Users/SINGHWX/.minikube/machines/minikube/id_rsa Username:docker}
I0925 15:47:56.694108   45958 ssh_runner.go:195] Run: sudo egrep ^[0-9]+:freezer: /proc/2148/cgroup
W0925 15:47:56.702558   45958 api_server.go:177] unable to find freezer cgroup: sudo egrep ^[0-9]+:freezer: /proc/2148/cgroup: Process exited with status 1
stdout:

stderr:
I0925 15:47:56.703514   45958 ssh_runner.go:195] Run: ls
I0925 15:47:56.707348   45958 api_server.go:253] Checking apiserver healthz at https://127.0.0.1:65096/healthz ...
I0925 15:47:56.712942   45958 api_server.go:279] https://127.0.0.1:65096/healthz returned 200:
ok
I0925 15:47:56.712967   45958 host.go:66] Checking if "minikube" exists ...
I0925 15:47:56.713422   45958 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0925 15:47:56.831984   45958 service.go:214] Found service: &Service{ObjectMeta:{hello-minikube  default  e53b7e32-28f7-4947-badb-8ab478fa225a 3460 0 2024-09-25 15:46:04 -0500 CDT <nil> <nil> map[app:hello-minikube] map[] [] [] [{kubectl-expose Update v1 2024-09-25 15:46:04 -0500 CDT FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":8080,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:8080,TargetPort:{0 8080 },NodePort:30325,AppProtocol:nil,},},Selector:map[string]string{app: hello-minikube,},ClusterIP:10.103.12.50,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.103.12.50],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,TrafficDistribution:nil,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0925 15:47:56.832121   45958 host.go:66] Checking if "minikube" exists ...
I0925 15:47:56.832282   45958 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0925 15:47:56.863225   45958 out.go:201] 
W0925 15:47:56.868933   45958 out.go:270] ❌  Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found
W0925 15:47:56.868939   45958 out.go:270] 
W0925 15:47:56.870400   45958 out.go:293] [31m╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                                                            [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                          [31m│[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                   [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                                                            [31m│[0m
[31m│[0m    - /var/folders/lr/g5p2mf797ns4bg1csblg19pc0000gq/T/minikube_service_533a182a0559351fc1399d159b6978096030941d_0.log    [31m│[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0925 15:47:56.875095   45958 out.go:201] 
Log file created at: 2024/09/25 15:51:16
Running on machine: C02HD3BQQ05N
Binary: Built with gc go1.22.5 for darwin/arm64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0925 15:51:16.758717   46482 out.go:345] Setting OutFile to fd 1 ...
I0925 15:51:16.759783   46482 out.go:397] isatty.IsTerminal(1) = true
I0925 15:51:16.759785   46482 out.go:358] Setting ErrFile to fd 2...
I0925 15:51:16.759787   46482 out.go:397] isatty.IsTerminal(2) = true
I0925 15:51:16.759892   46482 root.go:338] Updating PATH: /Users/SINGHWX/.minikube/bin
I0925 15:51:16.761312   46482 mustload.go:65] Loading cluster: minikube
I0925 15:51:16.761583   46482 config.go:182] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.31.0
I0925 15:51:16.762052   46482 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I0925 15:51:16.791816   46482 host.go:66] Checking if "minikube" exists ...
I0925 15:51:16.792301   46482 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I0925 15:51:16.810897   46482 api_server.go:166] Checking apiserver status ...
I0925 15:51:16.811565   46482 ssh_runner.go:195] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0925 15:51:16.811706   46482 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0925 15:51:16.827201   46482 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:65097 SSHKeyPath:/Users/SINGHWX/.minikube/machines/minikube/id_rsa Username:docker}
I0925 15:51:16.927691   46482 ssh_runner.go:195] Run: sudo egrep ^[0-9]+:freezer: /proc/2148/cgroup
W0925 15:51:16.936855   46482 api_server.go:177] unable to find freezer cgroup: sudo egrep ^[0-9]+:freezer: /proc/2148/cgroup: Process exited with status 1
stdout:

stderr:
I0925 15:51:16.937109   46482 ssh_runner.go:195] Run: ls
I0925 15:51:16.940525   46482 api_server.go:253] Checking apiserver healthz at https://127.0.0.1:65096/healthz ...
I0925 15:51:16.949485   46482 api_server.go:279] https://127.0.0.1:65096/healthz returned 200:
ok
I0925 15:51:16.949495   46482 host.go:66] Checking if "minikube" exists ...
I0925 15:51:16.949827   46482 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0925 15:51:17.007800   46482 service.go:214] Found service: &Service{ObjectMeta:{hello-minikube  default  9a072ae2-0b47-4e22-9b47-e24a0e8732e0 3784 0 2024-09-25 15:50:53 -0500 CDT <nil> <nil> map[app:hello-minikube] map[] [] [] [{kubectl-expose Update v1 2024-09-25 15:50:53 -0500 CDT FieldsV1 {"f:metadata":{"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:externalTrafficPolicy":{},"f:internalTrafficPolicy":{},"f:ports":{".":{},"k:{\"port\":8888,\"protocol\":\"TCP\"}":{".":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{},"f:sessionAffinity":{},"f:type":{}}} }]},Spec:ServiceSpec{Ports:[]ServicePort{ServicePort{Name:,Protocol:TCP,Port:8888,TargetPort:{0 8888 },NodePort:30515,AppProtocol:nil,},},Selector:map[string]string{app: hello-minikube,},ClusterIP:10.99.151.0,Type:NodePort,ExternalIPs:[],SessionAffinity:None,LoadBalancerIP:,LoadBalancerSourceRanges:[],ExternalName:,ExternalTrafficPolicy:Cluster,HealthCheckNodePort:0,PublishNotReadyAddresses:false,SessionAffinityConfig:nil,IPFamilyPolicy:*SingleStack,ClusterIPs:[10.99.151.0],IPFamilies:[IPv4],AllocateLoadBalancerNodePorts:nil,LoadBalancerClass:nil,InternalTrafficPolicy:*Cluster,TrafficDistribution:nil,},Status:ServiceStatus{LoadBalancer:LoadBalancerStatus{Ingress:[]LoadBalancerIngress{},},Conditions:[]Condition{},},}
I0925 15:51:17.008819   46482 host.go:66] Checking if "minikube" exists ...
I0925 15:51:17.009045   46482 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0925 15:51:17.044794   46482 out.go:201] 
W0925 15:51:17.049623   46482 out.go:270] ❌  Exiting due to SVC_UNREACHABLE: service not available: no running pod for service hello-minikube found
W0925 15:51:17.049631   46482 out.go:270] 
W0925 15:51:17.051384   46482 out.go:293] [31m╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m│[0m    😿  If the above advice does not help, please let us know:                                                            [31m│[0m
[31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                          [31m│[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m│[0m    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.                                   [31m│[0m
[31m│[0m    Please also attach the following file to the GitHub issue:                                                            [31m│[0m
[31m│[0m    - /var/folders/lr/g5p2mf797ns4bg1csblg19pc0000gq/T/minikube_service_533a182a0559351fc1399d159b6978096030941d_0.log    [31m│[0m
[31m│[0m                                                                                                                          [31m│[0m
[31m╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
I0925 15:51:17.055593   46482 out.go:201] 

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @jaiabbott, could you run the following four commands and output the output for debugging:
```
$ kubectl get services hello-minikube
$ kubectl describe services hello-minikube
$ kubectl get pods -A
$ kubectl get pods -l "app=hello-minikube"
```

**Comment by jaiabbott** [comment]
Thanks for the looking in to the issue @spowelljr . Please find the command and corresponding output as follows.

$ kubectl get services hello-minikube
---------------------------------------------------------------------------------
NAME             TYPE       CLUSTER-IP    EXTERNAL-IP   PORT(S)          AGE
hello-minikube   NodePort   10.99.151.0   <none>        8888:30515/TCP   4d18h
---------------------------------------------------------------------------------
$ kubectl describe services hello-minikube
---------------------------------------------------------------------------------
Name:                     hello-minikube
Namespace:                default
Labels:                   app=hello-minikube
Annotations:              <none>
Selector:                 app=hello-minikube
Type:                     NodePort
IP Family Policy:         SingleStack
IP Families:              IPv4
IP:                       10.99.151.0
IPs:                      10.99.151.0
Port:                     <unset>  8888/TCP
TargetPort:               8888/TCP
NodePort:                 <unset>  30515/TCP
Endpoints:                10.244.0.9:8888,10.244.0.10:8888
Session Affinity:         None
External Traffic Policy:  Cluster
Internal Traffic Policy:  Cluster
Events:                   <none>
---------------------------------------------------------------------------------
$ kubectl get pods -A
---------------------------------------------------------------------------------
NAMESPACE     NAME                               READY   STATUS             RESTARTS        AGE
default       hello-minikube-645c66f89d-gc9q4    0/1     ImagePullBackOff   0               4d
default       hello-minikube-7d48979fd6-xp8kw    0/1     ErrImagePull       0               4d18h
kube-system   coredns-6f6b679f8f-ldwsc           1/1     Running            0               4d19h
kube-system   etcd-minikube                      1/1     Running            0               4d19h
kube-system   kube-apiserver-minikube            1/1     Running            0               4d19h
kube-system   kube-controller-manager-minikube   1/1     Running            0               4d19h
kube-system   kube-proxy-7mggq                   1/1     Running            0               4d19h
kube-system   kube-scheduler-minikube            1/1     Running            0               4d19h
kube-system   storage-provisioner                1/1     Running            1 (4d19h ago)   4d19h
---------------------------------------------------------------------------------
$ kubectl get pods -l "app=hello-minikube"
---------------------------------------------------------------------------------
NAME                              READY   STATUS             RESTARTS   AGE
hello-minikube-645c66f89d-gc9q4   0/1     ImagePullBackOff   0          4d
hello-minikube-7d48979fd6-xp8kw   0/1     ImagePullBackOff   0          4d18h
---------------------------------------------------------------------------------

**Comment by spowelljr** [comment]
I see you're getting `ImagePullBackOff` on your pods, that's why you're getting an error, could you run and upload the output of the following:
```
$ kubectl describe pods hello-minikube-645c66f89d-gc9q4
$ kubectl describe pods hello-minikube-7d48979fd6-xp8kw
```

**Comment by spowelljr** [comment]
It seems like your cluster is no longer running, you'd have to start the cluster again and try the command again.

**Comment by spowelljr** [comment]
Were you trying to reach `http://127.0.0.1:63526` while leaving the `minikube service hello-minikube` command running?

I just tried on my machine and it's working for me using the same steps I believe you're using:
```
Request served by hello-minikube-7d48979fd6-rjmw8

HTTP/1.1 GET /

Host: 127.0.0.1:55923
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Cache-Control: max-age=0
Connection: keep-alive
Sec-Ch-Ua: "Google Chrome";v="129", "Not=A?Brand";v="8", "Chromium";v="129"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36
```

Are you on a corporate device that may have firewalls or proxies blocking things?

**Comment by jaiabbott** [comment]
yes i am using a corporate device. I think you have given me enough information to debug. let me continue looking in to it. thanks you.
