### ISSUE TITLE
Using Multi-Control Plane - HA Clusters

### ISSUE THREAD

**Issue by FrankYu-USA** [kubernetes/minikube#19701]
my environment:   VMware player + Ubuntu with docker

while run "minikube ssh -p ha-demo -- 'sudo /var/lib/minikube/binaries/v1.28.4/kubectl --kubeconfig=/var/lib/minikube/kubeconfig logs -n kube-system pod/kube-vip-ha-demo'   "

system prompt: [sudo] password for docker:   

I check online, there are no sudo password for docker,    I have also add  User to Docker Group :
   sudo usermod -aG docker $USER
   newgrp docker

however, make no difference,  what step I have missed?

thank you.

**Comment by spowelljr** [comment]
Hi @FrankYu-USA, change the kubectl version `v1.28.4` to match the version of Kubernetes your cluster is using and that should resolve the sudo issues you're experiencing.

**Comment by prezha** [comment]
hi @FrankYu-USA, Steven is right, and you can find out `Version` from the `profile` command - eg:

`minikube profile list`
```
|---------|-----------|------------|----------------|------|---------|---------|-------|----------------|--------------------|
| Profile | VM Driver |  Runtime   |       IP       | Port | Version | Status  | Nodes | Active Profile | Active Kubecontext |
|---------|-----------|------------|----------------|------|---------|---------|-------|----------------|--------------------|
| ha-demo | docker    | containerd | 192.168.49.254 | 8443 | v1.31.1 | OKHAppy |     3 |                | *                  |
|---------|-----------|------------|----------------|------|---------|---------|-------|----------------|--------------------|
```

btw, pr #19722 aims to improve the docs and use the appropriate kubernetes version automatically
