### ISSUE TITLE
Kubectl is hitting a wrong API endpoint

### ISSUE THREAD

**Issue by roughbits01** [kubernetes/minikube#1973]
**BUG REPORT**:

Please provide the following details:

**Environment**:

- **Minikube version**: v0.21.0
- **OS**: Windows10
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.23.0.iso
- **Start command**:  minikube start --kubernetes-version v1.7.0 --memory=2048

**What happened**:
When I try to get a list of resources (for example, the list of nodes) using kubernetes-client (java client), it tries to access http://192.168.99.100:30000/api/v1/nodes so I get an error (404 Not Found) while the working endpoint is http://192.168.99.100:30000/api/v1/node (without the s).

Thank you in advance.

**Comment by roughbits01** [comment]
bump

**Comment by dlorenc** [comment]
This sounds like a bug with the java client. Could you open an issue on that repository?
