### ISSUE TITLE
Installing step should have docker user and group creation step as well

### ISSUE THREAD

**Issue by niharika1233** [kubernetes/minikube#19742]
### What Happened?

I was installing minikube and found that running minikube installation needs docker as a user and in group as well.

### Attach the log file

no such file for logs 

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @niharika1233, could you explain exactly what you mean. What command did you run? What error were you getting?

**Comment by niharika1233** [comment]
@spowelljr yes sir, let me just try to recreate the issue

**Comment by niharika1233** [comment]
Sir while running minikube, i found an error saying that i should not run docker as root, which required me to first add a group docker and then add a user to that docker group for the part of installation of minikube. We should either do two things 1> add a prerequisite to confirm user as docker and not root user 2> or the required steps for the docker

**Comment by spowelljr** [comment]
Adding a docker group and adding the user is part of the Docker install instructions: https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user

**Comment by niharika1233** [comment]
![image](https://github.com/user-attachments/assets/ca1e02d8-ff2a-4ca9-8a5c-314861c7b6c4)

Please see above image, instead I am going to run it as root now. 

![image](https://github.com/user-attachments/assets/607c8a82-9f17-4884-a3ae-efd9d1aff4d4)

Now to get rid of these errors i need to follow the steps for docker, now I believe at least we should tell people with a small link there and make docker user as prerequisite.

**Comment by spowelljr** [comment]
I'm not sure I understand what you're trying to suggest. Completely unrelated to minikube, when you install docker there are instructions to add your user to the docker group, as seen in https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user. It seems you accidentally missed that step, which is fine, and then when you try to start minikube we see that you forgot that step and output the following:
```
docker: Suggestion: Add your user to the 'docker' group: 'sudo usermod -aG docker $USER && newgrp docker' <https://docs.docker.com/engine/install/linux-postinstall/>
```
If you run the command we provided you it should resolve your issue, we don't support running minikube as root with the docker driver.

> I believe at least we should tell people with a small link there and make docker user as prerequisite

That's what the suggestion is telling your to do already.

**Comment by niharika1233** [comment]
The suggestion that you are giving on command line thanks for that, i think you can also include as prerequisites steps in the installation webpage

**Comment by LuBingtan** [comment]
Not sure if this PR https://github.com/kubernetes/minikube/pull/19925 can address the issue. @spowelljr PTAL
/assign
