### ISSUE TITLE
kubeadm should enable apiVersion batch/v2alpha1 and batch/v1beta1 for CronJob

### ISSUE THREAD

**Issue by ijl** [kubernetes/minikube#1977]
minikube 0.22.2 with `--bootstrapper=kubeadm` per #1903 does not support specifying `batch/v2alpha1` or `batch/v1beta1` for `apiVersion`, but this this is needed to deploy kind `CronJob`. This is ok if using localkube.

**Comment by ijl** [comment]
kubernetes 1.8 enables `batch/v1beta1` by default, so #2018 is sufficient.

**Comment by Morriz** [comment]
This is not sufficient for us who need to be able to run `v2alpha1`. Any idea how that is possible otherwise? I am using `gcr.io/google_containers/kube-state-metrics:v1.1.0` which is referring to the `v2alpha1` version and can't find it.
