### ISSUE TITLE
Proxy apiserver to localhost

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#198]
Vendor kubectl and run `kubectl proxy` in a goroutine in `minikube`, so the user may access apiserver at `localhost:8080`

**Comment by philips** [comment]
Love this idea.

**Comment by dlorenc** [comment]
Minikube doesn't run as a daemon, just as a CLI that exits upon completion. I think we'd need a type of proxy command that stays running to make this work.

**Comment by dlorenc** [comment]
@luxas did you have any more thoughts on this? Perhaps we could have a "minikube start-proxy" command to forward the apiserver and any NodePorts to localhost.

**Comment by luxas** [comment]
Yes, I was thinking about something like that. If we think we can, we may try to instruct users to run minikube start-proxy & as well, and sh willl put it into the background. If minikube is smart enough, it could provide an option to start-proxy to kill the process.

Maybe minikube proxy start and minikube proxy stop is better?

**Comment by dlorenc** [comment]
The complexity of having to track/monitor PIDs cross platform doesn't seem worth it to me, just letting it run in the foreground sounds good for a start.

**Comment by luxas** [comment]
Yeah, it was just an idea, nothing we should do right now.
Implementing a `start-proxy` command is fine for me

**Comment by jimmidyson** [comment]
It's definitely beneficial to have access to the API server from localhost but wondering if it's worth adding it to minikube considering users are very likely to have `kubectl` so could just run `kubectl proxy` ?

**Comment by vishh** [comment]
I agree with @jimmidyson! We can instead focus our energy on hiding the host vs VM networking issues.

**Comment by dlorenc** [comment]
+1` as well to just relying on kubectl proxy for now, and fixing the general case of this in #38.

**Comment by dlorenc** [comment]
Closing for now, using kubectl proxy should be basically the same.
