### ISSUE TITLE
minikube on win10 with Hyperv not started.

### ISSUE THREAD

**Issue by stefanstranger** [kubernetes/minikube#1988]
BUG REPORT:

When starting minikube on Windows 10 with Hyper-V the start hangs on "starting vm".

Command:
minikube start --vm-driver=hyperv --hyperv-virtual-switch=External -v 10

Output:
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minikube
 ).state
[stdout =====>] : Running

[stderr =====>] :
Waiting for SSH to be available...
Getting to WaitForSSH function...
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minikube
 ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM minikub
e ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
Error getting ssh command 'exit 0' : IP not found
Getting to WaitForSSH function...
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minikube
 ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM minikub
e ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
Error getting ssh command 'exit 0' : IP not found

Please provide the following details:

**Environment**:
- Windows 10
- Hyper-V
- External Virtual Switch HyperV
- minikube version: v0.22.1

**Comment by richardjharding** [comment]
so the issue with missing IP seems to be fixed with 0.22.2 but that still seems to have additional issues see #1945 and #1981

**Comment by stefanstranger** [comment]
I installed version v0.22.2 and I'm still getting the same error.

**Comment by ohdihe** [comment]
Getting the same error. 
**minikube version**: v0.25.0

Docker-machine has no errors either.
Any help would be greatly appreciated.

**Comment by DovydasNavickas** [comment]
Same here:

**minikube version**: v0.25.0

**Comment by paulorobles** [comment]
I'm seign the same behavior with minikube v0.25.0

Starting local Kubernetes v1.9.0 cluster...
Starting VM...
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minikube ).state
[stdout =====>] : Running

[stderr =====>] :
Waiting for SSH to be available...
Getting to WaitForSSH function...
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minikube ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] :
[stderr =====>] :
Error getting ssh command 'exit 0' : IP not found

**Comment by gbraad** [comment]
Please make sure you can have an IP address assigned on the external switch. Since it shows 'IP not found' it does not seem to get an answer for DHCP. Make sure the external switch is active on the same interface you are connected to on the network, or try using the "Default switch" instead.

**Comment by paulorobles** [comment]
I did now i'm getting a different error... im runing this command on Powershell as admin.
PS> .\minikube.exe start --vm-driver=hyperv --hyperv-virtual-switch=kubernetes -v 10
the error is:
_Error setting container-runtime options during provisioning ssh command error:
command : sudo systemctl -f restart crio
err     : Process exited with status 1
output  : Job for crio.service failed because the control process exited with error code.
See "systemctl status crio.service" and "journalctl -xe" for details._

Is there a way to troubleshoot from the minikube vm ?

**Comment by gbraad** [comment]
Closing issue. If this is still a problem, open a new issue against the latest version

**Comment by adamgit** [comment]
Same with version 0.32

... in my case I hadn't realisd there were multiple ethernet cards in my machine (built-in one on the motherboard I'd forgotten was there), and didn't notice that HyperV-Manager was by default creating switches on the built-in, disconnected, never-used, ethernet card.

This is still a bug, IMHO. Fixes needed:

1. Don't hang on the "Starting VM" stage! That should not happen! Minikube should *at least* output a message after - say - 30 seconds "Cannot find IP address."
2. Along with that warning message, minikube should provide some simple advice, e.g. when running the hyperv driver: "Have you created a Virtual Switch in HyperV-Manager, and is it configured on the correct ethernet card that connects you to the internet?"

**Comment by medchkir** [comment]
I have the same problem with v0.34.
Any one have an idea how to fix it ?

**Comment by thavlik** [comment]
Same problem. My machine has two network adapters.
