### ISSUE TITLE
 Cleanup ssh tunnels on SIGKILL

### ISSUE THREAD

**Issue by Enteee** [kubernetes/minikube#19893]
### What Happened?

This is very similar to: https://github.com/kubernetes/minikube/issues/10752

Minikube tunnel should terminate its child processes on SIGKILL as well.

### Attach the log file

minikube version: v1.33.1
commit: v1.33.1

### Operating System

Other

### Driver

Docker

**Comment by ljluestc** [comment]
```
#!/bin/bash

# Filename: supervisor.sh

# Start the Minikube tunnel in the background
minikube tunnel &
TUNNEL_PID=$!

echo "Minikube tunnel started with PID $TUNNEL_PID"

# Function to clean up child processes
cleanup() {
    echo "Terminating Minikube tunnel and its child processes..."
    kill -TERM "$TUNNEL_PID" 2>/dev/null
    wait "$TUNNEL_PID"
    exit 0
}

# Trap SIGTERM and SIGINT to perform cleanup
trap cleanup SIGTERM SIGINT

# Wait for the tunnel process to finish
wait "$TUNNEL_PID"

```

**Comment by Ritikaa96** [comment]
Hey @Enteee have you tried the above solution ? 
Also please check if this issue persists with latest version of minikube

**Comment by Enteee** [comment]
@Ritikaa96 the above script does not do what i was asking for. That's handling `SIGTERM SIGINT` not `SIGKILL`. But when i got back to this issue i realized what I was asking for is not really possible to implement. As `SIGKILL` can't be handled by the receiving process..

sorry for the spam.
