### ISSUE TITLE
Allow configuration of visible nvidia gpus

### ISSUE THREAD

**Issue by Enteee** [kubernetes/minikube#19908]
### What Happened?

Currently when `--gpus nvidia` is set `minikube` just  uses `--gpus all` as argument for the docker container. 

https://github.com/kubernetes/minikube/blob/e3cab8e05f40b659e699ea5d8221abcb2d2e43ba/pkg/drivers/kic/oci/oci.go#L195

 The nvidia driver allows many different options for the `--gpus` flag. (see [doc](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/docker-specialized.html#gpu-enumeration))

In my use case I have several GPUs available, but I would like to limit the gpus visible to minikube using `--gpus '"device=1,2"'`.

I see the following ways of implementing this:

* extend `minikube's --gpus=XXXX` so that if `XXXX` is not `all`,`nvidia` or `amd` we just call `docker --gpus=XXX ...`
* implement a generic way to set custom environment variables for the minikube container: This would allow me to set `NVIDIA_VISIBLE_DEVICES` which would then solve my use case

What do you think?
I could also contribute a pull request.

### Attach the log file

minikube version: v1.33.1
commit: v1.33.1

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment]
Hi @Enteee, thanks for reporting your issue and willing to be able to submit a PR! With the addition of AMD GPU support we need to to ensure to make flags compatilable with both NVIDIA and AMD, or we'll need to make the flag NVIDIA specific.

> extend minikube's --gpus=XXXX so that if XXXX is not all,nvidia or amd we just call docker --gpus=XXX

The problem seems that both NVIDIA and AMD have extra flags and fields provided when their respective flag is set. So we need to know both the GPU type and then which GPUs to use, so I'm thinking we may need an additional flag, but I'm open to discussion to come to the best solution.

**Comment by Enteee** [comment]
Hey @spowelljr , I understand that compatibility with AMD and NVIDIA is important.
That's why I tried simply forwarding a few environment variables if `--gpu nvidia` is set (see my patch above)

The problem with that is that it does not work :) For some reason `NVIDIA_VISIBLE_DEVICES` is ignored when I go through the kicbase entrypoint. Do you have an idea why?

**Comment by Enteee** [comment]
Ahh I think this has something to do with `--privileged`:

* this just prints one gpu:
```
NVIDIA_VISIBLE_DEVICES=1 docker run -ti --runtime nvidia --env NVIDIA_VISIBLE_DEVICES --entrypoint nvidia-smi gcr.io/k8s-minikube/kicbase:v0.0.45
```

* this prints all gpus:
```
NVIDIA_VISIBLE_DEVICES=1 docker run -ti --runtime nvidia --env NVIDIA_VISIBLE_DEVICES --entrypoint nvidia-smi  --privileged gcr.io/k8s-minikube/kicbase:v0.0.45
```

**Comment by Enteee** [comment]
Closing this, I don't think this is possible as long as minikube requires privileged containers.
The reason is that `NVIDIA_VISIBLE_DEVICES` is ignored by the nvidia runtime when run as `privileged`.

https://github.com/NVIDIA/nvidia-docker/issues/764
