### ISSUE TITLE
Kubernetes 1.7.6 in minikube release

### ISSUE THREAD

**Issue by ssakhuja57** [kubernetes/minikube#2003]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

Just wanted to know when kubernetes `1.7.6` will be available with minikube? The current latest version of minikube `v0.22.2` only has up to `1.7.5`. The new kubernetes version has a few fixes for log streams getting interrupted. Thanks!

**Comment by r2d4** [comment]
Should be coming up soon - you can actually try using `minikube start --kubernetes-version v1.7.6 --bootstrapper kubeadm` right now, but the kubeadm bootstrapper is still experimental.
