### ISSUE TITLE
Control kubernetes server version

### ISSUE THREAD

**Issue by sliranc** [kubernetes/minikube#201]
Is it possible to select the master version ?

**Comment by dlorenc** [comment]
This isn't currently possible. It's something we'd like to add in the future. Could you explain your use case a bit? It will help us prioritize this feature.

**Comment by sliranc** [comment]
We would like to try and use this for our application development running on k8s and we would like to set the version to the same version as our production clusters.

**Comment by dlorenc** [comment]
To everyone interested in this issue: What granularity of control do you need? Is the Kubernetes release sufficient (v1.2.2, v.1.2.3, v.1.3.0, etc.)? Or do you need the ability to run any commit?

**Comment by martinffx** [comment]
+1 

Certain applications that run on top of Kubernetes require a specific version to run. 

For example [Deis Workflow](https://www.deis.com) only supports v1.2

So being able to specify the version and probably being able to multiple clusters running different versions.

**Comment by martinffx** [comment]
even if minikube obeyed K8S_VERSION env variable

**Comment by dlorenc** [comment]
Here's roughly what I'm thinking:

- We'll add a flag to minikube start to control the version of kubernetes
- We'll add a minikube command to list the available localkube/k8s versions
- Minikube weekly releases will stay on the current k8s stable version by default (curl -sS https://storage.googleapis.com/kubernetes-release/release/stable.txt)
- Localkube in master will stay on the stable release as well
- We'll create a branch approximately every 2 weeks (tying these to alpha/beta releases where possible)
  - This branch will contain an updated and tested version of localkube
  - We'll publish a localkube binary from this branch, but never merge this branch to master

Here's what this might look like to use (assuming 1.3.0 is the latest default):

```shell
$ minikube get-kubernetes-versions
v1.2.5
v.1.3.0-alpha.1
v.1.3.0-alpha.2
v.1.3.0-beta.1
v.1.3.0-alpha.2
[v1.3.0]

$ minikube start
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.0", GitCommit:"abcdef", GitTreeState:"clean"}
$ minikube delete
$ minikube start --kubernetes-version=v1.2.5
$ kubectl version
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.5", GitCommit:"abcdef", GitTreeState:"clean"}
```

**Comment by MHBauer** [comment]
For development of kubernetes itself, I'd like it to get to the point that I have the kubernetes code checked out and modified (or on a named branch, etc), and you build and deploy that specific to me version.

**Comment by MHBauer** [comment]
I am also totally willing to help out on this (or anything else) with a little bit of guidance.

**Comment by dlorenc** [comment]
Awesome @MHBauer. I think @aaron-prindle has this one under control now, but I'll try to find something else you can help out with. I'm happy to help you get started :)

**Comment by r2d4** [comment]
Closing this as we've had it in since v0.8.0
