### ISSUE TITLE
Minikube waits indefinitely for vfkit on MacOS 15.2

### ISSUE THREAD

**Issue by cloudowski** [kubernetes/minikube#20104]
### What Happened?

After upgrade to MacOS 15.2 vfkit driver seems to stopped working. When I start a minikube instance it waits for the vm to start - there's no error, just an attempt to connect to the vm.

I have the latest vfkit version (0.6.0) and before the upgrade to 15.2 everything worked fine.

### Attach the log file

I1215 11:43:19.741674    3182 main.go:141] libmachine: Attempt 1
I1215 11:43:19.741711    3182 main.go:141] libmachine: Searching for 22:68:2d:34:5e:b8 in /var/db/dhcpd_leases ...
I1215 11:43:19.742224    3182 main.go:141] libmachine: Found 41 entries in /var/db/dhcpd_leases!
I1215 11:43:19.742263    3182 main.go:141] libmachine: dhcp entry: {Name:minikube IPAddress:192.168.94.42 HWAddress:22:68:2d:34:5e:b8 ID:1,22:68:2d:34:5e:b8 Lease:0x675ec0d7}
I1215 11:43:19.742282    3182 main.go:141] libmachine: Found match: 22:68:2d:34:5e:b8
I1215 11:43:19.742310    3182 main.go:141] libmachine: IP: 192.168.94.42
I1215 11:43:19.742325    3182 main.go:141] libmachine: Waiting for VM to start (ssh -p 22 docker@192.168.94.42)...

### Operating System

macOS (Default)

### Driver

vfkit

**Comment by afbjorklund** [comment]
You might want to file an issue with https://github.com/crc-org/vfkit, if it is always reproducible on macOS 15.2

**Comment by cloudowski** [comment]
Fixed, it was a problem with network access. After the upgrade to 15.2 the network access rules have changed (?) and everything launched from iTerm (i.e. minikube) was denied network access.
After allowing it from Security & Privacy settings everything started to work again.
