### ISSUE TITLE
Minikube v0.22.2 Heapster graphs missing in K8-Dashboard

### ISSUE THREAD

**Issue by bgehman** [kubernetes/minikube#2013]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

Please provide the following details:

**Environment**:

**Minikube version**:
`minikube version: v0.22.2`

- **OS**:
`Red Hat Enterprise Linux Workstation release 7.3 (Maipo)`

- **VM Driver**:
`kvm`

- **ISO version**:
`minikube-v0.23.4.iso`

- **Install tools**:
```
$ minikube start --memory 16384 --cpus 4 --disk-size 40g --vm-driver=kvm
$ minikube addons enable heapster
```

**What happened**:
Not seeing the memory/cpu graphs from heapster, inside the kubernetes dashboard

**What you expected to happen**:
Expect to see the memory / cpu graphs

**How to reproduce it** (as minimally and precisely as possible):
- Install minikube v0.22.2
- Run: `minikube addons enable heapster`

**Output of `minikube logs` (if applicable)**:
Didn't find anything of interest.  heapster & influxdb_grafana pods up and running fine.  Nothing of interest in their logs either.  Dashboard pod logs show:
```
[2017-09-27T17:56:50Z] Incoming HTTP/1.1 GET /api/v1/thirdpartyresource request from 172.17.0.1:34614: {}
[2017-09-27T17:56:50Z] Outcoming response to 172.17.0.1:34612 with 200 status code
Getting list of all pods in the cluster
Getting list of third party resources
[2017-09-27T17:56:50Z] Outcoming response to 172.17.0.1:34614 with 200 status code
[restful] 2017/09/27 17:56:50 log.go:26: No metric client provided. Skipping metrics.
[restful] 2017/09/27 17:56:50 log.go:26: No metric client provided. Skipping metrics.
Getting pod metrics
[2017-09-27T17:56:50Z] Outcoming response to 172.17.0.1:34616 with 200 status code 
```

Which imply no data...

**Anything else do we need to know**:
Worked in Minikube v0.21.0
Also, this works: `minikube addons open heapster` -- can drill in and see graph data.  The problem is specifically the kubernetes dashboard + heapster integration that seems to have been lost.

**Workaround**:
Use: `minikube addons open heapster` to open & view graph data directly in the Grafana portal.

**Comment by eacdy** [comment]
Seems happen in minikube 0.22.3

**Comment by r2d4** [comment]
Fixed in #2035

**Comment by bgehman** [comment]
@r2d4 Thanks! Anything I need to do on my end to pick up the updates, or wait for `0.22.4` ?

**Comment by r2d4** [comment]
You could take those yamls in the PR and just add them in your `~/.minikube/addons` directory and they will be ran automatically, or you can wait for the next release
