### ISSUE TITLE
Missing mounted file when using xhyve driver

### ISSUE THREAD

**Issue by hanks** [kubernetes/minikube#2014]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: 

**Minikube version** : v0.22.2
- **OS** : macOS Sierra 10.12.5 (16F73)
- **VM Driver** : xhyve
- **ISO version** : minikube-v0.23.4.iso
- **Install tools**:
- **Others**:

**What happened**:
Use the default mount setting, `alembic versions` directory on the host are mounted into `/Users/xxx`, but the number of files in vm is smaller than the number in the host. The directory in the host contains about total 644 (same filename with different ext, .py and .pyc) files, and filename length is average 30 character. The same directory in issue #1753. But in vm, there are only 630 files.

**What you expected to happen**:
Should mount all the files in the directory.

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by diegofaria** [comment]
I am experiencing the same Issue under VirtualBox unfortunately,
the strange part is that if you actually cat the name of the file that doesn't show...
the file is actually there. 👻

**Comment by georgecrawford** [comment]
A dupe of https://github.com/kubernetes/minikube/issues/1515?

**Comment by hanks** [comment]
@georgecrawford seems a dupe, close this one, thx
