### ISSUE TITLE
Minikube fails to start kube-dns

### ISSUE THREAD

**Issue by gregd72002** [kubernetes/minikube#2019]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:
* Amazon EC2 
* Linux ip-172-31-43-108 4.9.43-17.39.amzn1.x86_64 #1 SMP Fri Sep 15 23:39:41 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Environment variables**:
* CHANGE_MINIKUBE_NONE_USER=true
* KUBECONFIG=/home/ec2-user/.kube/config
* MINIKUBE_HOME=/home/ec2-user

**Minikube version** (use `minikube version`): minikube version: v0.22.2
- **OS** (e.g. from /etc/os-release): Amazon Linux AMI 2017.03
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): [none?]
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):

**What happened**:
After starting minikube (`sudo -E minikube start --memory 8000 --cpus 2 --vm-driver=none`)
kube-dns fails to start
`kube-system   po/kube-dns-910330662-qb464              1/3       CrashLoopBackOff   12         15m`

**What you expected to happen**:
kube-dns starts

**Output of `kubectl logs kube-dns-910330662-qb464 --namespace=kube-system -c kubedns`

```
I1001 14:32:09.527073     141 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

E1001 14:32:34.027299     141 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.ConfigMap: Get https://10.0.0.1:443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-dns&resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout

I1001 14:32:34.527053     141 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

I1001 14:32:35.027022     141 dns.go:174] Waiting for services and endpoints to be initialized from apiserver...

E1001 14:32:35.031767     141 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout

E1001 14:32:35.031827     141 reflector.go:199] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.0.0.1:443: i/o timeout
```

**Anything else do we need to know**:
**Output of `kubectl get all --all-namespaces`
```
kubectl get all --all-namespaces
NAMESPACE     NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns   1         1         1            0           15m

NAMESPACE     NAME                    DESIRED   CURRENT   READY     AGE
kube-system   rs/kube-dns-910330662   1         1         0         15m

NAMESPACE     NAME              DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
kube-system   deploy/kube-dns   1         1         1            0           15m

NAMESPACE     NAME                                     READY     STATUS             RESTARTS   AGE
kube-system   po/kube-addon-manager-ip-172-31-43-108   1/1       Running            6          15m
kube-system   po/kube-dns-910330662-qb464              1/3       CrashLoopBackOff   12         15m
kube-system   po/kubernetes-dashboard-qmgwx            0/1       CrashLoopBackOff   7          15m

NAMESPACE     NAME                      DESIRED   CURRENT   READY     AGE
kube-system   rc/kubernetes-dashboard   1         1         0         15m
```

**Comment by marco-jantke** [comment]
The same problem appears locally on my Mac. Same minikube version.

**Comment by Siilwyn** [comment]
@gregd72002 not sure but could this be the same issue as https://github.com/kubernetes/minikube/issues/2027?

**Comment by a4abhishek** [comment]
Problem still persist.
minikube version: `0.24.0`
Kubernetes version: Client: `1.9.3`, Server: `1.8.0`
OS: `Ubuntu 17.10`
VM-Driver: `none`

Find minikube logs [here](https://github.com/kubernetes/minikube/files/1829152/minikube-logs.txt).



/remove-lifecycle rotten

**Comment by Hartimer** [comment]
The very same thing happens to me. I have a slightly more recent EC2 image:

`Linux ip-172-31-34-27 4.9.77-31.58.amzn1.x86_64 #1 SMP Thu Jan 18 22:15:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Both the dashboard pod and the storage-provider also fail as a consequence (they get to running by eventually crash).

Dashboard:
```
2018/04/04 22:59:01 Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout
Refer to our FAQ and wiki pages for more information: https://github.com/kubernetes/dashboard/wiki/FAQ
```

Storage provisioner:
`F0404 22:59:11.144046       1 main.go:37] Error getting server version: Get https://10.96.0.1:443/version: dial tcp 10.96.0.1:443: i/o timeout`

Any ideas? @gregd72002 have you figured out the problem?

**Comment by malagant** [comment]
We had success when disabling selinux.
