### ISSUE TITLE
README.md issue due to helloworld image not found

### ISSUE THREAD

**Issue by pwittrock** [kubernetes/minikube#202]
This command fails because the image is not found

```sh
kubectl run hello-minikube --image=helloworld --hostport=8000 --port=8080 --generator=run-pod/v1
```

**Comment by dlorenc** [comment]
Hey,

Sorry, I'm just catching up from vacation. I think this is a documentation issue - the user is supposed to build the hello world image but we don't do a good job of explaining how to do that.

We were trying to keep samples out of this repo, and I'm not quite sure of another way to make this more clear without adding some actual sample code the user can build and run. Do you have any opinions here, @pwittrock?

One idea would be to leave out the build from the quickstart, and just reference a pre-built docker image. Are you aware of any that already exist that would be appropriate?

**Comment by dlorenc** [comment]
@pwittrock and I chatted offline, we decided the best course of action is to change the quickstart to just use a pre-built example.
