### ISSUE TITLE
minikube + kubernetes + windows error retrieving pods

### ISSUE THREAD

**Issue by aadir7** [kubernetes/minikube#2023]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
minikube version: v0.22.2

- **OS** (e.g. from /etc/os-release):
Windows 7
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
 "DriverName": "virtualbox",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
"Boot2DockerURL": "file://C:/Users/egikmnq/DOCUME~1/MOBAXT~1/home/.minikube/cache/iso/minikube-v0.23.4.iso"

- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

"Boot2DockerURL": "file://C:/Users/egikmnq/DOCUME~1/MOBAXT~1/home/.minikube/cache/iso/minikube-v0.23.4.iso",

**What happened**:
When trying to retrieve pods details.
#kubectl get pods 
**What you expected to happen**:
The newly created POD should be visible
But i get the following error
"Unable to connect to the server: dial tcp 192.168.99.100:8443: connectex: No connection could be made because the target machine actively refused it."

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

Oct 02 14:44:11 minikube localkube[8177]: starting server... [version: 3.1.5, cluster version: to_be_decided]
Oct 02 14:44:11 minikube localkube[8177]: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
Oct 02 14:44:11 minikube localkube[8177]: set the initial cluster version to 3.1
Oct 02 14:44:11 minikube localkube[8177]: enabled capabilities for version 3.1
Oct 02 14:44:11 minikube localkube[8177]: 8e9e05c52164694d is starting a new election at term 1407
Oct 02 14:44:11 minikube localkube[8177]: 8e9e05c52164694d became candidate at term 1408
Oct 02 14:44:11 minikube localkube[8177]: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 1408
Oct 02 14:44:11 minikube localkube[8177]: 8e9e05c52164694d became leader at term 1408
Oct 02 14:44:11 minikube localkube[8177]: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 1408
Oct 02 14:44:11 minikube localkube[8177]: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
Oct 02 14:44:11 minikube localkube[8177]: I1002 14:44:11.754128    8177 etcd.go:58] Etcd server is ready
Oct 02 14:44:11 minikube localkube[8177]: ready to serve client requests
Oct 02 14:44:11 minikube localkube[8177]: localkube host ip address: 10.0.2.15
Oct 02 14:44:11 minikube localkube[8177]: Starting apiserver...
Oct 02 14:44:11 minikube localkube[8177]: Waiting for apiserver to be healthy...
Oct 02 14:44:11 minikube localkube[8177]: I1002 14:44:11.757595    8177 server.go:112] Version: v1.7.5
Oct 02 14:44:11 minikube localkube[8177]: W1002 14:44:11.759617    8177 authentication.go:368] AnonymousAuth is not allowed with the AllowAll authorizer.  Resetting AnonymousAuth to false. You should use a different authorizer
Oct 02 14:44:11 minikube localkube[8177]: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
Oct 02 14:44:12 minikube localkube[8177]: [restful] 2017/10/02 14:44:12 log.go:33: [restful/swagger] listing is available at https://10.0.2.15:8443/swaggerapi
Oct 02 14:44:12 minikube localkube[8177]: [restful] 2017/10/02 14:44:12 log.go:33: [restful/swagger] https://10.0.2.15:8443/swaggerui/ is mapped to folder /swagger-ui/
Oct 02 14:44:12 minikube localkube[8177]: I1002 14:44:12.757765    8177 ready.go:32] Performing healthcheck on https://localhost:8443/healthz
Oct 02 14:44:12 minikube localkube[8177]: E1002 14:44:12.758790    8177 ready.go:58] Error performing healthcheck: Get https://localhost:8443/healthz: dial tcp 127.0.0.1:8443: getsockopt: connection refused
Oct 02 14:44:13 minikube localkube[8177]: I1002 14:44:13.760495    8177 ready.go:32] Performing healthcheck on https://localhost:8443/healthz
Oct 02 14:44:13 minikube localkube[8177]: E1002 14:44:13.775573    8177 ready.go:58] Error performing healthcheck: Get https://localhost:8443/healthz: dial tcp 127.0.0.1:8443: getsockopt: connection refused
Oct 02 14:44:14 minikube localkube[8177]: I1002 14:44:14.763495    8177 ready.go:32] Performing healthcheck on https://localhost:8443/healthz
Oct 02 14:44:14 minikube localkube[8177]: E1002 14:44:14.766243    8177 ready.go:58] Error performing healthcheck: Get https://localhost:8443/healthz: dial tcp 127.0.0.1:8443: getsockopt: connection refused

**Anything else do we need to know**:

**Comment by mikeroskywalker** [comment]
I had a quite similar issue.  My host OS is Windows 7

Finally I got it resolved by downgrading the minikube to  v0.19..1 and using kubectl v 1.6.0

minikube v 0.19.1 has issues to work with kubectl v1.8
```
error: group map[:0xc08239a2a0 authentication.k8s.io:0xc08239a380 batch:0xc08239a700 rbac.authorization.k8s.io:0xc0820cb
b20 componentconfig:0xc08239a7e0 extensions:0xc08239a8c0 policy:0xc0820cbab0 federation:0xc082349dc0 apps:0xc08239a310 a
uthorization.k8s.io:0xc08239a4d0 autoscaling:0xc08239a540 certificates.k8s.io:0xc08239a770 storage.k8s.io:0xc0820cbb90]
is already registered
```

**Comment by r2d4** [comment]
This is fixed in the latest version of minikube.

**Comment by ydd2018** [comment]
遇到同样的问题，
c:\k8s>kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp 192.168.99.100:8443: connectex: No connection could be made because the target machine actively refused it.

这个有没有最终解决的
