### ISSUE TITLE
Cross-platform build broken?

### ISSUE THREAD

**Issue by uromahn** [kubernetes/minikube#2030]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: Ubuntu 16.04 running in a VirtualBox VM with Mac OS X as host
latest master branch from Github
go 1.8.3

**Minikube version** (use `minikube version`): N/A
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.3 LTS (Xenial Xerus)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): N/A
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): N/A
- **Install tools**: N/A
- **Others**: N/A
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

**What happened**:
When I run the command `BUILD_IN_DOCKER=y make cross` the build starts but then fails with the following output:

```
pkg-config --cflags libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt
Package libvirt was not found in the pkg-config search path.
Perhaps you should add the directory containing `libvirt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libvirt' found
Package libvirt was not found in the pkg-config search path.
Perhaps you should add the directory containing `libvirt.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libvirt' found
...
... many lines omitted
...
pkg-config: exit status 1
Makefile:296: recipe for target 'out/docker-machine-driver-kvm2' failed
make: *** [out/docker-machine-driver-kvm2] Error 2
```

**What you expected to happen**: the build completes successfully with all binaries located in /out

**How to reproduce it** (as minimally and precisely as possible): follow the instructions in https://github.com/kubernetes/minikube/blob/master/docs/contributors/build_guide.md and then in https://github.com/kubernetes/minikube/blob/master/docs/contributors/releasing_minikube.md

**Output of `minikube logs` (if applicable)**: N/A

**Anything else do we need to know**:

**Comment by r2d4** [comment]
Ah, we should probably move the drivers out of the `cross` rule.  If you inspect the rule definition, it builds the cross platform minikube binaries as well as the hyperkit and kvm (libvirt) drivers.  The hyperkit driver builds in a container, but the kvm driver doesn't and requires libvirt-dev to be installed.
