### ISSUE TITLE
[feature request, kind of] Create official minikube image on dockerhub

### ISSUE THREAD

**Issue by imaia** [kubernetes/minikube#2036]
Please, add a official minikube docker image on docker hub so that it is easy to run it on docker based environments, like rancheros.

**Comment by r2d4** [comment]
There are images published on GCR for localkube

```
gcr.io/k8s-minikube/localkube-image
gcr.io/k8s-minikube/localkube-image-dind
```

And some more specifics on how to run them here https://github.com/kubernetes/minikube/tree/master/deploy/docker
