### ISSUE TITLE
Unable to Run Minikube on Windows 10 with Hyper - v

### ISSUE THREAD

**Issue by VenkateshSrini** [kubernetes/minikube#2042]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG
 I have created an Hyper - V virtual switch and from the network properties I see that it has Internet access. Now go ahead and create a minikube with this virtual machine. It worked till the end where I could see the VM is configured to work with Kubectl. Then when I check the status using 
**Minikube status** I get the following
 _Minikube running 
cluster stopped_

Then I typed the command **kubectl cluster-info**
_Kubernetes master is running at https://192.168.0.110:8443
error: group map[certificates.k8s.io:0xc0823c21c0 extensions:0xc0823c2310 storage.k8s.io:0xc0823c2460 federation:0xc0823
0b810 apps:0xc08230bd50 authorization.k8s.io:0xc08230bf10 batch:0xc0823c2150 componentconfig:0xc0823c2230 policy:0xc0823
c2380 rbac.authorization.k8s.io:0xc0823c23f0 :0xc08230bce0 authentication.k8s.io:0xc08230bdc0 autoscaling:0xc08230bf80]
is already registered_

Now when I hit the url  https://192.168.0.110:8443 I get the output
 _Site does not exist_
 

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):v0.22.2
- **OS** (e.g. from /etc/os-release): Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Hyper V (external switch)
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):0.23.4
- **Install tools**:
- **Others**:

**Comment by hirsim** [comment]
dupe of #1981 

The issues is probably resolved in version 0.22.3.
Can you try again with version [0.22.3](https://github.com/kubernetes/minikube/releases/tag/v0.22.3)?

**Comment by VenkateshSrini** [comment]
Hi,
Now I see that the cluster is also running.  I typed the command **kubectl cluster-info**. The output is as below
_Kubernetes master is running at https://192.168.0.111:8443
error: group map[authentication.k8s.io:0xc082307dc0 extensions:0xc0823be310 rbac.authorization.k8s.io:0xc0823be3f0 stora
ge.k8s.io:0xc0823be460 batch:0xc0823be150 certificates.k8s.io:0xc0823be1c0 componentconfig:0xc0823be230 federation:0xc08
2307810 :0xc082307ce0 apps:0xc082307d50 authorization.k8s.io:0xc082307f10 autoscaling:0xc082307f80 policy:0xc0823be380]
is already registered_
I tried accessing the URL **https://192.168.0.111:8443/api/v1/proxy/names%20paces/kube-system/services/kubernetes-dashboard**
**I get Unauthorized error.**

I tried accessing the url **https://192.168.0.111:8443**
then also getting unauthorized error. 

Please help as I think I'm in  the last step of setting up the minikube on my windows 10 machine

**Comment by VenkateshSrini** [comment]
Hi,
I found a solution for this
1) For kubectl related errors we need to download the latest kubectl from google.
2) For Dashboad  issues I tried kubectl dashboard and it worked.

Thanks a ton
