### ISSUE TITLE
Provide a way to test out minikube-iso with minishift

### ISSUE THREAD

**Issue by praveenkumar** [kubernetes/minikube#2045]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

We recently implemented flag to consume minikube-iso for minishift, an integration test should be added which will take minishift nightly complied binary for different platform and perform to prevent any breakage due to a new patch in iso. 

Please label it accordingly.

**Comment by praveenkumar** [comment]
Updated Master builds for minishift http://artifacts.ci.centos.org/minishift/minishift/master/latest/

**Comment by r2d4** [comment]
@praveenkumar or @budhrg should I assign one of you this issue?

**Comment by praveenkumar** [comment]
@matt please assign to me, I do need some discussion with you around it to implementation side though, will catch-up on slack soon.

**Comment by praveenkumar** [comment]
This is already in so I am closing this issue now.
