### ISSUE TITLE
Autoscale not working in Minikube

### ISSUE THREAD

**Issue by nupurbansal8** [kubernetes/minikube#2046]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a BUG REPORT 

**Environment**:

**Minikube version** (use `minikube version`): v0.22.2
- **OS** (e.g. from /etc/os-release): Ubuntu 16.10
- **VM Driver** : virtualbox
- **ISO version** :  "Boot2DockerURL": "file:///home/nupur/.minikube/cache/iso/minikube-v0.23.4.iso"

**What happened**: I ran a deployment by the name of user on minikube and autoscaled it by following command:
kubectl autoscale deployment user --cpu-percent=30 --min=1 --max=10
Then I ran a load on the service created by hitting it. 
Then I used the following command to check CPU usage:
kubectl get hpa 
Result I got : 
NAME      REFERENCE         TARGETS           MINPODS   MAXPODS   REPLICAS   AGE
user       Deployment/user    <unknown> / 30%        1                  10                   1          1h

Also, even after load the number of pods did not increase.Command I used to check:
kubectl get deployments user

Result obtained:
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
user                1                1                    1                       1           19m

**What you expected to happen**: I expected the current CPU usage to be shown in % instead of <unknown> and also the number of pods to increase.

**How to reproduce it** (as minimally and precisely as possible):
These are the only steps I followed.

**Output of `minikube logs` (if applicable)**: Small trace of logs:
Oct 09 11:38:46 minikube localkube[2960]: store.index: compact 28076
Oct 09 11:38:46 minikube localkube[2960]: I1009 11:38:46.409099    2960 compact.go:159] etcd: compacted rev (28076), endpoints ([http://localhost:2379])
Oct 09 11:38:46 minikube localkube[2960]: finished scheduled compaction at 28076 (took 30.169738ms)
Oct 09 11:38:59 minikube localkube[2960]: E1009 11:38:59.441098    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:39:13 minikube localkube[2960]: E1009 11:39:13.804959    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:39:29 minikube localkube[2960]: E1009 11:39:29.450360    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:39:43 minikube localkube[2960]: E1009 11:39:43.808416    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:39:59 minikube localkube[2960]: E1009 11:39:59.456271    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:40:13 minikube localkube[2960]: E1009 11:40:13.813876    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:40:29 minikube localkube[2960]: E1009 11:40:29.462952    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:40:43 minikube localkube[2960]: E1009 11:40:43.817203    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:40:59 minikube localkube[2960]: E1009 11:40:59.469884    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:41:13 minikube localkube[2960]: E1009 11:41:13.824497    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:41:29 minikube localkube[2960]: E1009 11:41:29.476999    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:41:43 minikube localkube[2960]: E1009 11:41:43.833467    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:41:59 minikube localkube[2960]: E1009 11:41:59.483697    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:42:13 minikube localkube[2960]: E1009 11:42:13.840935    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:42:29 minikube localkube[2960]: E1009 11:42:29.486468    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:42:43 minikube localkube[2960]: E1009 11:42:43.848882    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:42:59 minikube localkube[2960]: E1009 11:42:59.494085    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:43:13 minikube localkube[2960]: E1009 11:43:13.854653    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:43:29 minikube localkube[2960]: E1009 11:43:29.499116    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/pdp: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)
Oct 09 11:43:43 minikube localkube[2960]: E1009 11:43:43.861336    2960 horizontal.go:206] failed to compute desired number of replicas based on listed metrics for Deployment/default/user: failed to get cpu utilization: unable to get metrics for resource cpu: failed to get pod resource metrics: the server could not find the requested resource (get services http:heapster:)

**Comment by dlorenc** [comment]
Are you running the heapster addon? I think you'll need that to use autoscaling.

**Comment by nupurbansal8** [comment]
Yes I ran the heapster addon also. But still could not autoscale the deployment.

But I have got the reason for the error now. When deploying I had to define the cpu resource requests also. This solved the issue.
