### ISSUE TITLE
`minikube config get` should exit with non-zero code for missing config

### ISSUE THREAD

**Issue by georgecrawford** [kubernetes/minikube#2047]
**Minikube version** v0.22.3
- **OS** (e.g. from /etc/os-release): OS X 10.12.5
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.4.iso

```bash
$ minikube config get nonsense; echo $?
specified key could not be found in config
0
```

IMHO, this should exit `1` or some other non-zero code, to show the config key is not found. I'm not sure what's desired with, for example `minikube config get cpus` when that key is not currently set, but ideally, I'd also like it to return a non-zero code. Otherwise it makes bootstrapping `minikube start` a bit hard.

**Comment by r2d4** [comment]
Absolutely.  Cobra, the CLI framework, has argument validation functions built in that we can invoke.  We should do this.

**Comment by ulyssessouza** [comment]
Can I take this one?

**Comment by r2d4** [comment]
Its yours!
