### ISSUE TITLE
MiniKube start 

### ISSUE THREAD

**Issue by rhooley1** [kubernetes/minikube#2048]
Mac
minikube version: v0.22.3
OSx Sierra
virtual box
.minikube/cache/iso/minikube-v0.23.5.iso
Used brew

```


**What happened**:
When I try to start minikube I get the following error:


Starting local Kubernetes v1.7.5 cluster...
Starting VM...
E1009 14:31:46.751382   86216 start.go:146] Error starting host: Error starting stopped host: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
.

 Retrying.
E1009 14:31:46.753798   86216 start.go:152] Error starting host:  Error starting stopped host: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by r2d4** [comment]
Can you try running it with `--v 10 --logtostderr`? and post those logs here

**Comment by dlorenc** [comment]
Please re-open with logs.

**Comment by ohenak** [comment]
I have the same setup as above.

I am running into the exact same problem, here is the log after using `--v 10 --logtostderr`

I1020 13:44:25.048618   51830 notify.go:109] Checking for updates...
I1020 13:44:26.407541   51830 cache_images.go:226] Attempting to cache image: gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64:1.14.4 at /Users/hokho/.minikube/cache/images/gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64_1.14.4
I1020 13:44:26.407594   51830 cache_images.go:226] Attempting to cache image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.6.3 at /Users/hokho/.minikube/cache/images/gcr.io/google_containers/kubernetes-dashboard-amd64_v1.6.3
I1020 13:44:26.407600   51830 cache_images.go:226] Attempting to cache image: gcr.io/google_containers/k8s-dns-kube-dns-amd64:1.14.4 at /Users/hokho/.minikube/cache/images/gcr.io/google_containers/k8s-dns-kube-dns-amd64_1.14.4
I1020 13:44:26.407679   51830 cache_images.go:226] Attempting to cache image: gcr.io/google-containers/kube-addon-manager:v6.4-beta.2 at /Users/hokho/.minikube/cache/images/gcr.io/google-containers/kube-addon-manager_v6.4-beta.2
I1020 13:44:26.407738   51830 cluster.go:67] Machine exists!
I1020 13:44:26.407701   51830 cache_images.go:226] Attempting to cache image: gcr.io/google_containers/k8s-dns-sidecar-amd64:1.14.4 at /Users/hokho/.minikube/cache/images/gcr.io/google_containers/k8s-dns-sidecar-amd64_1.14.4
I1020 13:44:26.407732   51830 cache_images.go:226] Attempting to cache image: gcr.io/google_containers/pause-amd64:3.0 at /Users/hokho/.minikube/cache/images/gcr.io/google_containers/pause-amd64_3.0
I1020 13:44:26.407858   51830 cache_images.go:77] Successfully cached all images.
COMMAND: /usr/local/bin/VBoxManage showvminfo minikube --machinereadable
STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="32a9e1ec-66f9-446c-85da-2442cf06b252"
CfgFile="/Users/hokho/.minikube/machines/minikube/minikube/minikube.vbox"
SnapFldr="/Users/hokho/.minikube/machines/minikube/minikube/Snapshots"
LogFldr="/Users/hokho/.minikube/machines/minikube/minikube/Logs"
hardwareuuid="32a9e1ec-66f9-446c-85da-2442cf06b252"
memory=2048
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="poweroff"
VMStateChangeTime="2017-10-19T06:47:28.000000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="/Users/hokho/.minikube/machines/minikube/boot2docker.iso"
"SATA-ImageUUID-0-0"="06942dcc-dbe6-47e9-8cb6-437cd0aef706"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/Users/hokho/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="33cd734e-ac30-43a8-b1af-17586b52fdf5"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="080027D30C2B"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,55759,,22"
hostonlyadapter2="vboxnet0"
macaddress2="0800274C990F"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="coreaudio"
audio_in="false"
audio_out="false"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="Users"
SharedFolderPathMachineMapping1="/Users"
videocap="off"
videocapscreens=0
videocapfile="/Users/hokho/.minikube/machines/minikube/minikube/minikube.webm"
videocapres=1024x768
videocaprate=512
videocapfps=25
videocapopts=
GuestMemoryBalloon=0
}
STDERR:
{
}
I1020 13:44:26.765910   51830 cluster.go:74] Machine state:  Stopped
COMMAND: /usr/local/bin/VBoxManage showvminfo minikube --machinereadable
STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="32a9e1ec-66f9-446c-85da-2442cf06b252"
CfgFile="/Users/hokho/.minikube/machines/minikube/minikube/minikube.vbox"
SnapFldr="/Users/hokho/.minikube/machines/minikube/minikube/Snapshots"
LogFldr="/Users/hokho/.minikube/machines/minikube/minikube/Logs"
hardwareuuid="32a9e1ec-66f9-446c-85da-2442cf06b252"
memory=2048
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="poweroff"
VMStateChangeTime="2017-10-19T06:47:28.000000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="/Users/hokho/.minikube/machines/minikube/boot2docker.iso"
"SATA-ImageUUID-0-0"="06942dcc-dbe6-47e9-8cb6-437cd0aef706"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/Users/hokho/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="33cd734e-ac30-43a8-b1af-17586b52fdf5"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="080027D30C2B"
cableconnected1="on"
nic1="nat"
nictype1="82540EM"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,55759,,22"
hostonlyadapter2="vboxnet0"
macaddress2="0800274C990F"
cableconnected2="on"
nic2="hostonly"
nictype2="82540EM"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="coreaudio"
audio_in="false"
audio_out="false"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="Users"
SharedFolderPathMachineMapping1="/Users"
videocap="off"
videocapscreens=0
videocapfile="/Users/hokho/.minikube/machines/minikube/minikube/minikube.webm"
videocapres=1024x768
videocaprate=512
videocapfps=25
videocapopts=
GuestMemoryBalloon=0
}
STDERR:
{
}
COMMAND: /usr/local/bin/VBoxManage list hostonlyifs
STDOUT:
{
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

}
STDERR:
{
}
Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
Found: vboxnet0
COMMAND: /usr/local/bin/VBoxManage list dhcpservers
STDOUT:
{
NetworkName:    HostInterfaceNetworking-vboxnet0
IP:             192.168.99.6
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes

}
STDERR:
{
}
Removing orphan DHCP servers...
COMMAND: /usr/local/bin/VBoxManage list hostonlyifs
STDOUT:
{
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

}
STDERR:
{
}
Adding/Modifying DHCP server "192.168.99.6" with address range "192.168.99.100" - "192.168.99.254"...
COMMAND: /usr/local/bin/VBoxManage list dhcpservers
STDOUT:
{
NetworkName:    HostInterfaceNetworking-vboxnet0
IP:             192.168.99.6
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes

}
STDERR:
{
}
COMMAND: /usr/local/bin/VBoxManage modifyvm minikube --nic2 hostonly --nictype2 82540EM --nicpromisc2 deny --hostonlyadapter2 vboxnet0 --cableconnected2 on
STDOUT:
{
}
STDERR:
{
}
COMMAND: /usr/local/bin/VBoxManage modifyvm minikube --natpf1 delete ssh
STDOUT:
{
}
STDERR:
{
}
COMMAND: /usr/local/bin/VBoxManage modifyvm minikube --natpf1 ssh,tcp,127.0.0.1,55782,,22
STDOUT:
{
}
STDERR:
{
}
COMMAND: /usr/local/bin/VBoxManage startvm minikube --type headless
STDOUT:
{
Waiting for VM "minikube" to power on...
}
STDERR:
{
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
}
Checking vm logs: /Users/hokho/.minikube/machines/minikube/minikube/Logs/VBox.log
E1020 13:44:27.979022   51830 start.go:146] Error starting host: Error starting stopped host: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
.

 Retrying.
E1020 13:44:27.979076   51830 start.go:152] Error starting host:  Error starting stopped host: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by ohenak** [comment]
BTW, I am using VirtualBox 5.2.0 r118431 on Mac.

**Comment by woto** [comment]
Hmmm yesterday  i've got working minikube, today got same error. Digging on this.
Sorry for bad English.

**Comment by woto** [comment]
Oh its helps https://github.com/kubernetes/minikube/issues/1379

**Comment by kaman86** [comment]
Any updates on this? Im running into a similar issue

**Comment by afbjorklund** [comment]
@kaman86 : please open a new bug report

**Comment by woodcockjosh** [comment]
I updated VirtualBox and this fixed this error for me
