### ISSUE TITLE
Minikube misreports status if bootstrapped with kubeadm

### ISSUE THREAD

**Issue by jberkus** [kubernetes/minikube#2056]
**Environment**:

**Minikube version**: v0.22.3
- **OS**: Fedora 25 (Workstation Edition)
- **VM Driver**: kvm
- **ISO version**: minikube-v0.23.5.iso
- **Install tools**: kubeadm
- **Others**:

**What happened**:

1. Start minikube with `minikube start --vm-driver kvm --network-plugin cni  --kubernetes-version v1.8.0 --bootstrapper kubeadm`
2. run `minikube status`
3. Minikube reports:

```
minikube: Running
cluster: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.42.190
```

4. Minikube is actually running and the cluster is started and running.

This is a problem because our automated testing scripts check for minikube starting, and because of the misreporting see it as failed, and error out.

**What you expected to happen**:

`minikube status` should report:

```
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.42.190

```

**How to reproduce it** (as minimally and precisely as possible):

See steps above.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by r2d4** [comment]
This is kind of a bug - status and logs actually require the `--bootstrapper` flag also.  We can definitely be smarter about this and check both and return the right status.

**Comment by jberkus** [comment]
The problem with requiring --bootstrapper on "status" is that 3rd-party CICD tools aren't going to check for it.  So it would be nice to do it automatically.

**Comment by r2d4** [comment]
The best way that I do it now is to configure the bootstrapper with `minikube config set`

`minikube config set bootstrapper kubeadm`

Then you can just 

```
minikube start
minikube status
minikube logs
```

**Comment by jberkus** [comment]
+1 awesome!

Leaving this open to see if it's possible for us to handle status automatically though.

**Comment by jberkus** [comment]
I'm currently unable to test this because I'm having some unrelated issues with Minikube+KVM.  Has any work been done to make support of alternate bootstrappers automatic?

/remove-lifecycle rotten

**Comment by jberkus** [comment]
Figured out the memory problem and was able to test with 1.9.3.

The reporting issue appears to be fixed, AFAICT.  Both "status" and "logs" work correctly.

Thanks to whomever fixed this!

/close
