### ISSUE TITLE
Stop supporting the vmwarefusion driver

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#2058]
We don't currently run any integration tests on the vmwarefusion driver.  There are no devs currently working on supporting this driver, so we should stop supporting it.

**Comment by nikolay** [comment]
@r2d4 Please, don't! It is superior to VirtualBox in terms of performance and it cost is less than a (Starbucks) coffee per month! Well, when you release docker-machine-driver-hyperkit, then it would be a different story and you can even drop VirtualBox support on macOS and nobody will even notice!

**Comment by anfernee** [comment]
agree @nikolay. If you guys accept #2118, then it's a different story. I (and/or someone in our team) can help support this driver. but please don't throw it away!

**Comment by gbraad** [comment]
We have the same issue at minishift, and we will be dropping support of VMware too.

**Comment by dougm** [comment]
Seconding @anfernee , we're on the same team and I can also help support the driver.

**Comment by dlorenc** [comment]
A good place to start would be to look through open issues tagged with vmwarefusion as the driver and try to tackle some of them:
https://github.com/kubernetes/minikube/issues?q=is%3Aissue+is%3Aopen+label%3Adriver%2Fvmwarefusion

**Comment by mikeroySoft** [comment]
Product manager for Fusion here... Can we help?

**Comment by gbraad** [comment]
Please check discussion on the PR. We, Minishift and minimize, discussed
that it might be a better idea to move the driver to a different
organisation we have set up. Details are on the PR. This will make
maintenance easier as a shared effort.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by gbraad** [comment]
Link to the comment:
https://github.com/kubernetes/minikube/pull/2118#issuecomment-358735768

We will still setup CI, but in a fixed/stable version for minikube. While
we will try to create CI for each PR in the org for development purpose.

The reasoning is that each driver in minikube is expected to have a certain
quality that we can not guarantee at the moment. We have limited bandwidth,
so we rather give this responsibility to the developers of the driver.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]
