### ISSUE TITLE
how to change vm time zone

### ISSUE THREAD

**Issue by du2016** [kubernetes/minikube#2061]
how to change vm time zone,when the vm start,it set the same time to my local,but not my local timezone

**Comment by alejandrodnm** [comment]
I'm having the same problem, it's happening with the `vmware` driver. The timezone it's set to UTC but the time is my localtime, @du2016 did you manage to fix it? When using `virtualbox` it works fine. 

I changed the date manually but that's more like a workaround than a solution.

**Comment by du2016** [comment]
@alejandrodnm i have change source code: copy timezone file to localtime before vm start, then build myself

**Comment by efengx** [comment]
I also encountered the same problem, if using minikube in different countries how to ensure that the hyperkit uses the specified time zone

**Comment by alejandrodnm** [comment]
I ended up with this, that I found in some other issue 

``` 
λ ➜ alias minikube-date
minikube-date='DSTR=$(date -u); minikube ssh "sudo date --set=\"$DSTR\""'
```

**Comment by balopat** [comment]
I just ran into this as well - this can cause issues with docker builds against minikube's docker daemon, e.g. from skaffold: 
`"E: Release file for http://archive.ubuntu.com/ubuntu/dists/bionic-updates/InRelease is not valid yet (invalid for another 1h 54min 32s). Updates for this repository will not be applied."`

**Comment by tstromberg** [comment]
@balopat I believe your issue is actually #4264 - not timezone related, but system clock related.

**Comment by tstromberg** [comment]
The VM time zone is UTC. If you really really want to change it to your local time zone, run this on your host:

```
mkdir -p ~/.minikube/files/etc
cp /etc/localtime  ~/.minikube/files/etc
```

Every subsequent run of `minikube start` will override the timezone with what you have specified in ~/.config/minikube/files/etc/localtime.
