### ISSUE TITLE
Minikube stable version mismatch?

### ISSUE THREAD

**Issue by dkamenda** [kubernetes/minikube#2063]
As per https://github.com/kubernetes/minikube/releases the current stable release of minikube is v0.22.3 but it mismatches the version I get through my scripting:

`$ curl -s https://storage.googleapis.com/minikube/releases/stable.txt`
0.16.0

I am not sure whether stable.txt file is relevant or in charge, but since the actual download link still refers to storage.googleapis.com (i.e. https://storage.googleapis.com/minikube/releases/v0.22.3/minikube-linux-amd64) I'd expect it to contain "0.22.3" rather tahn "0.16.0".

**Comment by dkamenda** [comment]
Ok, I got it. @r2d4 , thanks for the explanation.

**Comment by r2d4** [comment]
Removed

**Comment by a4abhishek** [comment]
@r2d4 Even https://storage.googleapis.com/minikube/latest seems to be removed. Now where to find the latest stable release of minikube as I am facing [issues](https://github.com/kubernetes/minikube/issues/2496) with minikube 0.25.0
