### ISSUE TITLE
DNS Not working in minikube, having issues attempting to manually deploy kube-dns

### ISSUE THREAD

**Issue by akvsh** [kubernetes/minikube#2075]
**Minikube version** (use `minikube version`):  v0.19.1
- **OS** (e.g. from /etc/os-release): OS X 10.11.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "virtualbox",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.5

**What happened**:
I am using `minikube start --memory 4096 --kubernetes-version v1.5.2` to create my minikube env and I was having some issues while trying to set up an elasticsearch cluster and decided to do some DNS Diagnosis as seen in the [docs](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/#troubleshooting-tips). I realized I had kube-dns issues because i got the following messages while troubleshooting

```
$ kubectl exec -ti busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10

nslookup: can't resolve 'kubernetes.default'

$ kubectl exec busybox cat /etc/resolv.conf
search default.svc.cluster.local svc.cluster.local cluster.local
nameserver 10.0.0.10
options ndots:5

$ kubectl get pods --namespace=kube-system -l k8s-app=kube-dns
No resources found.
```
The kube-dns service is also up but has no exposed endpoints. I tried to manually deploy by using the `kube-dns-controller.yaml` file but when trying to create it I got the message:

```
error: error validating "kube-dns-controller.yaml": error validating data: [found invalid field tolerations for v1.PodSpec, found invalid field optional for v1.ConfigMapVolumeSource]; if you choose to ignore these errors, turn validation off with --validate=false
```

Not sure what else to try here, I was thinking it might be a version issue related to my k8s version (possibly doesn't have the fields introduced yet) but did not find any information on this. What should i be looking into? Thanks!

EDIT:
`minikube addons list` even shows that kube-dns is enabled so I'm not sure why I am still having issues

```
minikube addons list
- dashboard: enabled
- default-storageclass: enabled
- kube-dns: enabled
- registry: disabled
- addon-manager: enabled
- ingress: disabled
- registry-creds: disabled
- heapster: disabled
```

**Comment by akvsh** [comment]
Turns out that it was an issue with the kubernetes version. Upgrading to v1.6.0 seemed to get kube-dns working again.

**Comment by srflaxu40** [comment]
How did you upgrade?
