### ISSUE TITLE
--mount-string and --mount not working properly

### ISSUE THREAD

**Issue by danielmischler** [kubernetes/minikube#2080]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.22.3
- **OS** (e.g. from /etc/os-release): MacOS 10.11.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.5
- **Install tools**:
- **Others**:

**What happened**:
The following command does not mount the test folder unless there is a vm with profile 'minikube' present:
```
minikube start --profile test --mount-string test:/mnt/test --mount
```

**What you expected to happen**:
The mounting should happen independently of the presence of a vm with a profile 'minikube'.

**How to reproduce it** (as minimally and precisely as possible):
Does not work:
```
minikube delete --profile minikube
minikube delete --profile test
minikube start --profile test --mount-string test:/mnt/test --mount
```

Does work:
```
minikube delete --profile minikube
minikube delete --profile test
minikube start --profile minikube
minikube stop --profile minikube
minikube start --profile test --mount-string test:/mnt/test --mount
```

**Comment by nevishs** [comment]
I am having the same issue.

when starting the minikube, nothing is mounted, I am not able to see the mounted data.
minikube start --profile test --mount-string test:/data/test --mount

when starting the minikube without a profile, it works, I can see the mounted data.
minikube start --mount-string test:/data/test --mount
