### ISSUE TITLE
Error starting host:  Error creating host: Error executing step: Creating VM

### ISSUE THREAD

**Issue by Penglq** [kubernetes/minikube#2086]
Docker version 17.09.0-ce, build afdb6d4
minikube version: v0.22.3
docker-machine version 0.12.2, build 9371605

E1019 12:17:07.439340   96008 start.go:152] Error starting host:  Error creating host: Error executing step: Creating VM.
: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by dlorenc** [comment]
Looks like your virtualbox installation isn't setup correctly: https://ubuntuforums.org/showthread.php?t=1198060

**Comment by Penglq** [comment]
Thank you,let me have a try.
