### ISSUE TITLE
make fails on memory allocation

### ISSUE THREAD

**Issue by imorti** [kubernetes/minikube#209]
So I get this is an allocation issue. What I don't know is how to fix this. I have plenty of RAM so the 4GB requirement shouldn't be an issue. 

# k8s.io/minikube/cmd/localkube
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

Makefile:57: recipe for target 'out/localkube' failed
make: *** [out/localkube] Error 2
make: *** [out/localkube] Error 2

**Comment by dlorenc** [comment]
Hey,

Sorry you had trouble building. What type of system are you building on?

If you're on OSX, how is Docker installed? Could you run:
docker run --rm gcr.io/google_containers/kube-cross:v1.6.2-1 free -m

**Comment by imorti** [comment]
Yes, OSX. Installed (for shame) the Docker for MAC beta. Raised memory to 5GB to be safe and now have this: 
CGO_ENABLED=1 go build -ldflags="-X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitCommit=760c563c7257dd7f9044073a2956a2bca1b455e7 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitVersion=v1.3.0-alpha.5-330-g760c563 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitTreeState=clean -X k8s.io/minikube/pkg/version.version=v0.3.0 -s -w -extldflags '-static'" -o ./out/localkube ./cmd/localkube
# k8s.io/minikube/vendor/github.com/jmespath/go-jmespath
fatal error: freespan into cached span

runtime stack:
runtime.throw(0x87dd40, 0x19)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.(*mcentral).freeSpan(0xd86070, 0x7f8aae2dade0, 0x29, 0xc8219d4000, 0xc8219d5130, 0xd76100, 0x100000000)
	/usr/local/go/src/runtime/mcentral.go:155 +0x3e
runtime.(*mspan).sweep(0x7f8aae2dade0, 0xf00000000, 0x200000b01)
	/usr/local/go/src/runtime/mgcsweep.go:319 +0x613
runtime.sweepone(0x431b02)
	/usr/local/go/src/runtime/mgcsweep.go:112 +0x23e
runtime.gosweepone.func1()
	/usr/local/go/src/runtime/mgcsweep.go:124 +0x21
runtime.systemstack(0xc82001a000)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 3 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc820026f58 sp=0xc820026f50
runtime.gosweepone(0x0)
	/usr/local/go/src/runtime/mgcsweep.go:125 +0x3d fp=0xc820026f80 sp=0xc820026f58
runtime.bgsweep(0xc82004e000)
	/usr/local/go/src/runtime/mgcsweep.go:66 +0xb6 fp=0xc820026fb8 sp=0xc820026f80
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc820026fc0 sp=0xc820026fb8
created by runtime.gcenable
	/usr/local/go/src/runtime/mgc.go:191 +0x53

goroutine 1 [runnable]:
cmd/compile/internal/gc.bvandnot(0x2, 0xc820c7a240, 0x1, 0x15, 0x2, 0xc820c7a240, 0x1, 0x15, 0xc800000002, 0xc821fe4a9c, ...)
	/usr/local/go/src/cmd/compile/internal/gc/bv.go:60
cmd/compile/internal/gc.livenessprologue(0xc82004e150)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:1065 +0x5a7
cmd/compile/internal/gc.liveness(0xc82073f320, 0xc821728c60, 0xc822071680, 0xc822071700)
	/usr/local/go/src/cmd/compile/internal/gc/plive.go:1785 +0x2e2
cmd/compile/internal/gc.compile(0xc82073f320)
	/usr/local/go/src/cmd/compile/internal/gc/pgen.go:541 +0xdf2
cmd/compile/internal/gc.funccompile(0xc82073f320)
	/usr/local/go/src/cmd/compile/internal/gc/dcl.go:1450 +0x1c0
cmd/compile/internal/gc.Main()
	/usr/local/go/src/cmd/compile/internal/gc/lex.go:472 +0x2116
cmd/compile/internal/amd64.Main()
	/usr/local/go/src/cmd/compile/internal/amd64/galign.go:127 +0x58d
main.main()
	/usr/local/go/src/cmd/compile/main.go:32 +0x395

**Comment by dlorenc** [comment]
What version of Docker For Mac are you on? I just did a quick build with it and everything worked. That error looks like a crash in the go compiler.

**Comment by imorti** [comment]
Version 1.12.0-rc2-beta16 (build: 9493)
f615be9fb245904fbdf1aa0cad251d418c869428 

go version go1.6.2 darwin/amd64

MAC OSX 10.11.5

**Comment by imorti** [comment]
Yup! Issue with GOPATH. Thanks.

**Comment by eddumelendez** [comment]
@imorti I am getting the same error. Can you share the solution? Thanks in advance.
