### ISSUE TITLE
Expose update check

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#2094]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

It would be useful for some downstream tooling to be able to script out checking for updates.  Possibly through a `minikube update-check` command.

Maybe something like this?
```
$ minikube update-check
CurrentVersion: v0.22.3
LatestVersion: v0.22.4

CurrentISOVersion: v0.23.5
LatestISOVersion: v0.23.5
```

cc @coollog @loosebazooka

**Comment by mahdix** [comment]
I will pick up this one.

**Comment by mahdix** [comment]
https://github.com/kubernetes/minikube/pull/2139
