### ISSUE TITLE
Upgrade to go 1.9

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#2095]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

https://github.com/kubernetes/kubernetes/pull/51375

**Comment by dlorenc** [comment]
cc @priyawadhwa

**Comment by r2d4** [comment]
Things to update

- [ ] Build images: https://github.com/kubernetes/minikube/blob/master/Makefile#L25-L26
- [ ] Travis

Bonus:
- [ ] Build slaves:  I believe that the iso build doesn't fully build in a container, possibly due to some weird makefile magic.  We probably should just fix this.
