### ISSUE TITLE
problem with cluster after Enableing CustomMetrics in minikube

### ISSUE THREAD

**Issue by tesi-nahid** [kubernetes/minikube#2097]
Hello Guys,
I have kubernete  v1.0.7 and minikube v1.0.6,I made cluster on my kubernete with kubctl commands ,I inserted command of "$ minikube start --extra-config kubelet.EnableCustomMetrics=true  " ,but after that my "kubectl " on my kubernetes is not working and gives me error that it can not find the master ,Did I lost my cluster on my kubernetes V1.0.7 ?

**Comment by tesi-nahid** [comment]
/@minikube

**Comment by r2d4** [comment]
Can you provide the output of `minikube logs`?

**Comment by tesi-nahid** [comment]
I deleted minikube , I thought maybe minikube is not letting my cluster of kubernetes on machine to work.before ,minikube was showing master is using v1.0.6 (which was minikube version )and node is using v1.0.7 (it was the version on kubernet on machin) .

**Comment by tesi-nahid** [comment]
I solved the problem,in fact I had two cluster(command:kubectl config view)  one minikube and one my own cluster,so I deleted minikube cluster and its context and I changed "current cluster" to my own cluster (command: kubectl config current-context)  ,now kubectl get is working and my cluster and everything is there
