### ISSUE TITLE
minikube commands fail when kubeconfig context not set to minikube

### ISSUE THREAD

**Issue by coollog** [kubernetes/minikube#2100]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

Please provide the following details:

**Environment**: bash 4.4.12, kubectl v1.7.6

**Minikube version**: v0.22.3
- **OS**: Mac OS X 10.12.6
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.23.5.iso

**What happened**:

`minikube service` and `minikube dashboard` fail when `kubectl config current-context` is not minikube.

**What you expected to happen**:

The `minikube` commands should run in the `minikube` kubeconfig context.

**How to reproduce it** (as minimally and precisely as possible):

```
$ minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100

$ kubectl config current-context
my_gke_context

$ minikube service my_service
Error opening service: Could not find finalized endpoint being pointed to by my_service: Error getting kubernetes client: getting clientset: Error creating new client from kubeConfig.ClientConfig(): No Auth Provider found for name "gcp"
```

**Comment by r2d4** [comment]
The code for new-ing up the kube client is here https://github.com/kubernetes/minikube/blob/master/pkg/minikube/service/service.go#L64-L78

We probably need to specify the minikube context there.

**Comment by mahdix** [comment]
I will pick up this one.

**Comment by mahdix** [comment]
PR: https://github.com/kubernetes/minikube/pull/2128
I tested it on Ubuntu and Mac OS before/after change and it seems to be working as expected (When you change current context of Kubectl, still minikube works on minikube context)
