### ISSUE TITLE
Error during delete of xhyve VM

### ISSUE THREAD

**Issue by coderanger** [kubernetes/minikube#2102]
**Environment**:

**Minikube version**: 0.22.3
- **OS**: macOS 10.13
- **VM Driver**: xhyve
- **ISO version**: N/A
- **Install tools**: Homebrew
- **Others**:

**What happened**:

Was trying to delete my VM and restart with a new kubernetes version. The delete failed with this error:

```bash
$ minikube delete
Deleting local Kubernetes cluster...
Errors occurred deleting machine:  unexpected EOF
remove /Users/coderanger/.minikube/machines/minikube/root-volume.sparsebundle/bands/909: permission denied
```

Trying to delete again just gives `open /Users/coderanger/.minikube/machines/minikube/config.json: no such file or directory`.

Trying to continue on resulted in this:

```bash
$ minikube start --kubernetes-version=v1.8.0
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
E1020 17:20:41.429333   24489 start.go:146] Error starting host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: Error loading host from store: open /Users/coderanger/.minikube/machines/minikube/config.json: no such file or directory.

 Retrying.
E1020 17:20:41.431126   24489 start.go:152] Error starting host:  Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: Error loading host from store: open /Users/coderanger/.minikube/machines/minikube/config.json: no such file or directory
```

**What you expected to happen**:

Delete should only remove the config.json after all other steps succeed.

**How to reproduce it** (as minimally and precisely as possible):

Not sure.

**Anything else do we need to know**:

I'm guessing the workaround is just to delete `~/.minikube` or maybe `~/.minikube/machines` or similar?

**Comment by coderanger** [comment]
This might be because xhyve is running setuid so the disk files end up owned by root, minikube would need to use sudo or route the delete via something in the xhyve driver to do the cleanup.

**Comment by DJO3** [comment]
I encountered the same issue. Looks to be a permission issue with docker-machine-driver-xhyve. Not sure if it was caused by update to macOS 10.13 or minikube v0.23.0. This related issue provides a viable workaround: 

https://github.com/kubernetes/minikube/issues/708#issuecomment-324239350
