### ISSUE TITLE
Minikube vmdriver none start fails

### ISSUE THREAD

**Issue by kozikow** [kubernetes/minikube#2103]
**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.22.3
- **OS** (e.g. from /etc/os-release): Arch Linux
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): none

**What happened**:
vmdriver=none version of minikube fails to start.  When running `minikube status` it reports "minikube: Stopped". There are exceptions when looking at `minikube logs`. Running `kubectl get pods` returns: "The connection to the server 127.0.0.1:8443 was refused - did you specify the right host or port?"

**What you expected to happen**:
Minikube cluster starts as expected

**How to reproduce it** (as minimally and precisely as possible):

export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true
mkdir $HOME/.kube || true
touch $HOME/.kube/config
export KUBECONFIG=$HOME/.kube/config
sudo -E minikube start --vm-driver=none

**Output of `minikube logs` (if applicable)**:
Full logs:  https://drive.google.com/file/d/0B9P9V4RHDRkkbXFMcmx6cnBoNkk/view?usp=sharing . Part that looks suspicious: https://gist.github.com/kozikow/3319aefac7dbd655702cafc3b0bf8357 .

**Anything else do we need to know**:
Binaries I  used:
`curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube`
`curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.0/bin/linux/amd64/kubectl && chmod +x kubectl`
`sudo gsutil cp gs://minikube/k8sReleases/v1.8.0/localkube-linux-amd64 /usr/local/bin/localkube && chmod +x localkube`

**Comment by r2d4** [comment]
Im guessing this is the issue fixed in https://github.com/kubernetes/minikube/pull/2050
https://github.com/kubernetes/minikube/issues/1947

Can you try using `--kubenertes-version https://storage.googleapis.com/minikube-builds/2050/localkube`? and see if that works

**Comment by kozikow** [comment]
Suggestion by r2d4 helped.

**Comment by kozikow** [comment]
After solving this issue I have another: https://github.com/kubernetes/minikube/issues/2104
