### ISSUE TITLE
Make a release to support Kubernets 1.8

### ISSUE THREAD

**Issue by andyxning** [kubernetes/minikube#2105]
When should minikube make a release to support Kubernetes 1.8.

/cc @easeway @r2d4

**Comment by joan38** [comment]
I there any blocker on this?
We are currently sitting between 2 chair with this issue https://github.com/kubernetes/kubernetes/issues/53309

**Comment by r2d4** [comment]
@joan38 that issue has been fixed in the current version of minikube. 

You can also start using kubernetes 1.8 right away today with minikube with the `--kubernetes-version v1.8.0` flag. We will release a version with 1.8 as the default soon.

**Comment by joan38** [comment]
That’s great, thanks mate!
