### ISSUE TITLE
Kubectl is not able to connect to kubernetes API Server.

### ISSUE THREAD

**Issue by ahmi01** [kubernetes/minikube#2106]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:
k8s 1.7.5
**Minikube version** (use `minikube version`):
v0.22.3
- **OS** (e.g. from /etc/os-release):
Windows 7 Enterprise
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
VirtualBox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
0.23.5
- **Install tools**:
kubectl
- **Others**:
Nothing
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

**What happened**:
Not able to connect to Server.
C:\Users\eaadmad>kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.5", GitCommi
t:"17d7182a7ccbb167074be7a87f0a68bd00d58d97", GitTreeState:"clean", BuildDate:"2
017-08-31T09:14:02Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"windows/amd6
4"}
Unable to connect to the server: dial tcp 192.168.99.103:8443: connectex: A conn
ection attempt failed because the connected party did not properly respond after
 a period of time, or established connection failed because connected host has f
ailed to respond. 

**What you expected to happen**:
Expect connectivity to Server
C:\Users\eaadmad>minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.103

**How to reproduce it** (as minimally and precisely as possible):
Install minikube with minikube start --vm-driver=virtualbox
run kubectl version

**Output of `minikube logs` (if applicable)**:
Attached is the log file
[Logs.txt](https://github.com/kubernetes/minikube/files/1405457/Logs.txt)

**Anything else do we need to know**:
One of the thing that has happened is I re-installed minikube as machine got hanged and I need to remove VM from virtualbox.

**Comment by ahmi01** [comment]
This issue is apparently due to firewall settings on my machine. This works once i am on corporate network.

**Comment by alexcpn** [comment]
For anybody who faces it; Please check if your proxy is interfering, by disabling proxy settings

 unset http_proxy
 unset https_proxy
