### ISSUE TITLE
Add the option to set namespace in kubectl context (or stop deleting it!)

### ISSUE THREAD

**Issue by viteksafronov** [kubernetes/minikube#2117]
Currently minikube saves its context without any namespace. So I must add `-n mynamespace` to each `kubectl` command every time.
I would like to have an option to store my namespace in minikube config file which will be saved in kubectl context on `minikube start`. Currently if I modify the context by hands, these modifications are being lost on next `minikube start`.

**Comment by ngraf** [comment]
:+1:

**Comment by ngraf** [comment]
/remove-lifecycle stale

This improvement is still worth it and should not be closed.

**Comment by ngraf** [comment]
/remove-lifecycle stale

This improvement is still worth it and should not be closed.

**Comment by tstromberg** [comment]
Help wanted!

**Comment by priyawadhwa** [comment]
If anyone is interested in working on this issue, please assign yourself by commenting `/assign`. I'd be happy to review any PRs!

**Comment by medyagh** [comment]
I would accept a PR that adds a flag for minikube start or minikube update-context to specify namesapce

**Comment by medyagh** [comment]
@viteksafronov  I would be happy to review the PR for this feature and thanks for letting us know about this problem

**Comment by sharifelgamal** [comment]
This a good idea. Help wanted!
