### ISSUE TITLE
Getting encryption related error

### ISSUE THREAD

**Issue by harish-myaccount** [kubernetes/minikube#212]
Followed the installation instructions

$ minikube start
Starting local Kubernetes cluster...
Kubernetes is available at https://192.168.99.100:443

On opening above url, getting SSL related error
![screenshot from 2016-06-22 09-52-00](https://cloud.githubusercontent.com/assets/592646/16254608/4c270102-385f-11e6-8f5c-80ff6cfe2413.png)

**Comment by dlorenc** [comment]
Thanks for the report. I think the output message is a little unclear, which we should fix. The kubernetes API server is available at that endpoint, and it requires some special certificate configuration to talk to.

We automatically configure kubectl correctly so it knows how to talk to that endpoint, but there's no reason to hit that URL with a browser. We should change the output message to make that clear.

If you want to talk to the cluster, kubectl is automatically setup at this point.

If you want to see the dashboard, use: `minikube dashboard` and it will open your browser to that URL.

Let me know if this helps!

**Comment by harish-myaccount** [comment]
https://chromium.googlesource.com/chromium/src/+/90b6605758feea9d4f2a56ad3f6992e1e868b445/components/security_interstitials/core/browser/resources/interstitial_v2.js#43

typed 'badidea' and got 'Unauthorised' message

However,
minikube dashboard command worked.

Thanks
