### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by andrei-dascalu** [kubernetes/minikube#2120]
Hello!

When trying to install minikube on MacOSX (Sierra, 10.12.6, Python 3.6.2), I am getting the following result

```
➜  ~ brew cask install minikube
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3878, done.
remote: Compressing objects: 100% (3861/3861), done.
remote: Total 3878 (delta 29), reused 577 (delta 13), pack-reused 0
Receiving objects: 100% (3878/3878), 1.32 MiB | 0 bytes/s, done.
Resolving deltas: 100% (29/29), done.
Tapped 0 formulae (3,887 files, 4.2MB)
==> Creating Caskroom at /usr/local/Caskroom
==> Satisfying dependencies
All Formula dependencies satisfied.
==> Downloading https://storage.googleapis.com/minikube/releases/v0.22.3/minikub
######################################################################## 100.0%
==> Verifying checksum for Cask minikube
==> Installing Cask minikube
==> Linking Binary 'minikube-darwin-amd64' to '/usr/local/bin/minikube'.
Error: Command failed to execute!

==> Failed command:
/usr/bin/xattr -w com.apple.metadata:kMDItemAlternateNames ("minikube") /usr/local/Caskroom/minikube/0.22.3/minikube-darwin-amd64

==> Standard Output of failed command:


==> Standard Error of failed command:
  File "/usr/bin/xattr", line 31
    continue
           ^
TabError: inconsistent use of tabs and spaces in indentation


==> Exit status of failed command:
#<Process::Status: pid 80269 exit 1>
```

I'm not entirely sure where this issue belongs here, but I would appreciate any pointers.

Thanks!

**Comment by r2d4** [comment]
Thanks for opening this issue.  Seems a bit odd, I'll have to try to reproduce it.  The cask template is auto-updated from this template

https://github.com/kubernetes/minikube/blob/master/installers/darwin/brew-cask/minikube.rb.tmpl

by this script

https://github.com/kubernetes/minikube/blob/master/hack/jenkins/release_update_installers.sh#L49-L78

**Comment by andrei-dascalu** [comment]
@r2d4 hello, I've managed to work around the issue by manually 'downgrading' to Python 2.6

I could still get the error with Python 2.7 (not sure if I missed something at that stage).

strangely, this happened only on doing the cask install of minikube (brew had no issues with other tools). Right now I have the feeling of a conflict between xattr as used by Python < 3.x and the one for Python 2.

**Comment by woodcockjosh** [comment]
The issue is as @andrei-dascalu suggested. It is assuming python2. I recently updated to python 3. Fixed this by downgrading `ln -sf $(which python2) $(which python)`
