### ISSUE TITLE
v0.23.0 Error on startup

### ISSUE THREAD

**Issue by dsandersAzure** [kubernetes/minikube#2127]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): 0.23
- **OS**: Ubuntu 16.04.3 LTS (Xenial Xerus)
- **VM Driver**: virtualbox
- **ISO version**: minikube-v1.0.6.iso
- **Install tools**: curl
- **Others**:

**What happened**:
$ minikube start
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
E1027 09:10:05.464544    5773 start.go:150] Error starting host: Temporary Error: Error configuring auth on host: Temporary Error: ssh command error:
command : sudo systemctl -f restart docker
err     : Process exited with status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2017-10-27 08:44:36 EDT; 28min ago
     Docs: https://docs.docker.com
 Main PID: 1643 (dockerd)
    Tasks: 29
   Memory: 145.4M
      CPU: 4.910s
   CGroup: /system.slice/docker.service
           ├─1643 /usr/bin/dockerd -H fd://
           └─1686 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcon

**What you expected to happen**:
Successful startup

**How to reproduce it** (as minimally and precisely as possible):
Install v0.23.0

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
Reverted back to 0.22.3 okay

**Comment by DustinChaloupka** [comment]
From `journalctl -xe`:

**Comment by dsandersAzure** [comment]
Thanks @DustinChaloupka that worked for me and my 0.23 minikube environment is now up and working. Cheers!

**Comment by r2d4** [comment]
This makes sense, you'll have to delete and start your minikube VM again after this upgrade, since we've updated the docker version and the docker daemon binary name changed to `dockerd`
