### ISSUE TITLE
Can't get URL for a service deployed to non-default minikube profile

### ISSUE THREAD

**Issue by zaa** [kubernetes/minikube#2129]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version**: v0.22.3
- **OS**: Mac OS X
- **VM Driver**: VirtualBox
- **ISO version**: minikube-v0.23.5.iso

**What happened**:

1. created a custom minikube profile and deployed a service to the minikube cluster (with service type == NodePort).
2. tried to get url of the service using `minikube -p profile-name service --url service-name` command and got an error that server is not reachable (while `minikube -p profile-name status` shows that the server is running).
3. The error message contained a message that minikube failed to reach ip address of the default minikube, while I was trying to get url of the service deployed to the custom minikube profile.

Cursory look into https://github.com/kubernetes/minikube/blob/master/pkg/minikube/service/service.go#L69-L70 shows that minikube does not handle custom profiles correctly, it always sets the kubernetes profile name to 'minikube', instead of the one allocated to the minikube profile.

**What you expected to happen**:
Get url of the service

**How to reproduce it** (as minimally and precisely as possible):
see above

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by ulyssessouza** [comment]
Can I have this one?

**Comment by r2d4** [comment]
SGTM @ulyssessouza
