### ISSUE TITLE
Kubernetes Version

### ISSUE THREAD

**Issue by martinffx** [kubernetes/minikube#213]
How do you control what version kubernetes is run?

I need version 1.2 but minikube runs version 1.3

**Comment by dlorenc** [comment]
Hey,

Right now minikube only runs one version of Kubernetes, which is currently v1.3.0-beta.1. We'd like to add the ability to select the Kubernetes server version. That work is tracked in #201. Would you mind +1'ing that issue, and adding some details about your use-case?

**Comment by dlorenc** [comment]
Closing as a duplicate.
