### ISSUE TITLE
[none driver] minikube delete should delete all service objects and stop all K8s containers.

### ISSUE THREAD

**Issue by joshk0** [kubernetes/minikube#2133]
This is a feature request.

When I run `minikube delete` on Linux, it's not a supported operation.

Similar to #1867, what I would expect is that it deletes all Kubernetes pods and prevents new ones from being scheduled. It then shuts down the localkube Etcd and then wipes it out completely so that when we run `minikube start` again, it's like it's starting for the very first time.

**Comment by r2d4** [comment]
I'm going to rename this bug since its only for the `--none` driver case.  In all other cases the VM is completely destroyed.

**Comment by ulyssessouza** [comment]
If I understood well it's already corrected by https://github.com/kubernetes/minikube/pull/1774/commits/10e6e6ade1f30f2a2106df323dca04f0a25bc132

At least I see the containers being suppressed.
Isn't it?
