### ISSUE TITLE
Brew Formula for Minikube

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#2141]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

We currently have a brew _cask_ installer, which installs from a pre-built binary.  However, we can create a real brew formula for minikube now that we no longer include (and therefore don't cross build) localkube with go-bindata.

I think the formula should be pretty straightforward and would be very similar to existing go formula.

**Comment by budhrg** [comment]
@r2d4 , I think we can close this issue right?
I can see cask file https://github.com/caskroom/homebrew-cask/blob/master/Casks/minikube.rb .

**Comment by r2d4** [comment]
Currently the cask just downloads the prebuilt binary.  Now that we don't package localkube anymore, we can just build from source and have a real _brew_ formula instead of just a cask.

**Comment by ymesika** [comment]
If no one is working on creating a build formulae I can propose myself as an assignee.. Have a recent experience generating a formulae for another tool.

**Comment by tstromberg** [comment]
Still needed.

**Comment by afbjorklund** [comment]
Currently we ship the _same_ Linux binary everywhere: elf, tgz, deb, rpm

We might do the same for Darwin, that is leave it as a brew "cask" (binary)

**Comment by plod** [comment]
it okay if I have a crack at this?

**Comment by medyagh** [comment]
> it okay if I have a crack at this?

yes you could have this issue ! :)

**Comment by commitay** [comment]
I've opened a PR for a `minikube` formula: https://github.com/Homebrew/homebrew-core/pull/45603

**Comment by tstromberg** [comment]
Before we close this, we'll need to insure that our release scripts release to brew rather than cask: 

* https://github.com/kubernetes/minikube/blob/master/hack/jenkins/release_update_brew.sh
* https://github.com/kubernetes/minikube/blob/master/installers/darwin/brew-cask/minikube.rb.tmpl

@commitay @issyl0 - are either of you interested in taking a crack at updating our release scripts?

**Comment by afbjorklund** [comment]
I thought distros was supposed to pull (new releases) rather than push (from vendor) ? Especially if it is no longer our binary, but something they build. But not sure how Brew normally operates.

**Comment by issyl0** [comment]
@tstromberg I don't currently have enough spare time to help with this bigger piece of work, sorry!
