### ISSUE TITLE
Delay in resolving a new service

### ISSUE THREAD

**Issue by vishal-biyani** [kubernetes/minikube#2145]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

**Minikube version** (use `minikube version`): v0.22.1
- **OS** (e.g. from /etc/os-release): MacOS Sierra 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.20.0.iso
- **Install tools**: NA
- **Others**: NA

**What happened**:
When you create a Kubernetes service (With ClusterIP type) - the service is not reachable for a good 5-10 seconds initially. The same works well in a cluster for example in GKE.

**What you expected to happen**:
The service should respond within a few seconds

**How to reproduce it** (as minimally and precisely as possible):
Create a service for a pod/deployment and try hitting the service.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

Initially, the service returns the errors:
```
Connection to 10.0.0.67 failed
The remote host or network may be down. Please try the request again.
```

At this time I checked a few things related to service:
```
# nslookup svc-nodejs-f5c62081-9f76-11e7-80f9-080027fc9519.fission-function.svc.cluster.local
nslookup: can't resolve '(null)': Name does not resolve

Name:      svc-nodejs-f5c62081-9f76-11e7-80f9-080027fc9519.fission-function.svc.cluster.local
Address 1: 10.0.0.67 svc-nodejs-f5c62081-9f76-11e7-80f9-080027fc9519.fission-function.svc.cluster.local

```
In Another POD tried hitting the service IP and by name but did not get response:
```
curl http://svc-nodejs-f5c62081-9f76-11e7-80f9-080027fc9519.fission-function.svc.cluster.local
^C

curl http://10.0.0.67
^C
```

After about 10-20 seconds, the service responds.

**Comment by aaron-prindle** [comment]
Is this on a cold start of minikube or has it been running for some time?  Minikube's DNS will take an additional ~20-30 seconds to startup on some networks as it has to initialize the kube-dns pod.  To see if you are waiting on the kube-dns pod, you can look at all the default addon pods by running:
`kubectl get pod -n kube-system`

**Comment by vishal-biyani** [comment]
Thanks @aaron-prindle it does not appear only on cold start of Minikube. It happens the moment I create a new service (Or delete an old one and create a new one). Based on your feedback I looked through Kube-DNS logs and I see some delay in updating of DNS. Even after the update is logged, it takes a few seconds for the service to start responding. Is there some configuration which can be tweaked to change the frequency of DNS updates?

```
$kubectl -n kube-system logs -f kube-dns-910330662-bt4bh -c kubedns
I1103 07:57:07.317229       1 sync_configmap.go:118] ConfigMap kube-system:kube-dns was updated
W1103 08:07:05.324603       1 reflector.go:319] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: watch of *v1.ConfigMap ended with: too old resource version: 1794569 (1794698)
I1103 08:07:06.331589       1 sync_configmap.go:118] ConfigMap kube-system:kube-dns was updated


W1103 08:20:06.340634       1 reflector.go:319] k8s.io/dns/vendor/k8s.io/client-go/tools/cache/reflector.go:94: watch of *v1.ConfigMap ended with: too old resource version: 1795350 (1795725)
I1103 08:20:07.348915       1 sync_configmap.go:118] ConfigMap kube-system:kube-dns was updated
```
