### ISSUE TITLE
How to actually stop/delete minikube

### ISSUE THREAD

**Issue by stychu** [kubernetes/minikube#2146]
Please provide the following details:

**Environment**: linux

**Minikube version** (use `minikube version`):  v0.22.3

**What happened**:

I want to delete minikube and stop all k8s containers but Im unable to do it.
I've run minikube delete didin't helped. Everytime I do run `docker stop $(docker ps -q --filter name=k8s); docker rm $(docker ps -aq --filter name=k8s)` it spins up new containers

**What you expected to happen**:
Able to stop all containers and cleanup images from my local docker / remove minikube

**Comment by aaron-prindle** [comment]
Can you see what the status of the systemd unit running localkube is?  It seems this process is still running the kubelet and re-initializing those containers
'systemctl status localkube'

**Comment by aaron-prindle** [comment]
friendly ping @stychu

**Comment by sherzodv** [comment]
@aaron-prindle That's right. localkube is active and looks like it keeps the containers alive. I'm new to minikube, but I expected from `minikube stop` to actually stop everything.

**Comment by sherzodv** [comment]
I was wrong. after `minikube stop`  `ps aux | grep localkube` gives nothing. But all containers are still up and running.

**Comment by Speedy1991** [comment]
Had the same problem. The containers are started by the _localkube_ service. Running
```
systemctl stop localkube
docker rm -f $(docker ps -aq --filter name=k8s)
```
just worked fine for me

**Comment by voor** [comment]
Stopping `localkube` and removing images, but then restarting `localkube` it's spitting out errors like this:

```
Apr 06 15:52:49 redacted.hostname localkube[30493]: E0406 15:52:49.381347   30493 kubelet_volumes.go:128] Orphaned pod "5fe08a97-39c5-11e8-a0ee-080027c9d234" found, but volume paths are still present on disk : There were a total of 3 errors similar to this. Turn up verbosity to see them.
```

**Comment by caub** [comment]
I started removing minikube, I only kept the /usr/local/bin/minikube command, I don't think it matters

But I still have docker containers running on reboot, related to minikube:
```
caub@ins:~$ d ps
CONTAINER ID        IMAGE                        COMMAND             CREATED             STATUS              PORTS               NAMES
7d3984489a09        k8s.gcr.io/pause-amd64:3.1   "/pause"            12 seconds ago      Up 11 seconds                           k8s_POD_kube-scheduler-minikube_kube-system_ea66a171667ec4aaf1b274428a42a7cf_1
f71639669d60        k8s.gcr.io/pause-amd64:3.1   "/pause"            12 seconds ago      Up 11 seconds                           k8s_POD_kube-controller-manager-minikube_kube-system_a773829dd0dc9cfcb93d910823a6b96e_1
9539de5d8894        k8s.gcr.io/pause-amd64:3.1   "/pause"            12 seconds ago      Up 11 seconds                           k8s_POD_kube-apiserver-minikube_kube-system_9344320a58287bb47ab09d551d2485f0_1
518112ab19d9        k8s.gcr.io/pause-amd64:3.1   "/pause"            12 seconds ago      Up 11 seconds                           k8s_POD_etcd-minikube_kube-system_511a10f280d647f775de1628a57d333f_1
caub@inspiron:~$ systemctl list-units | grep kube
kubelet.service                                                                                             loaded active running   kubelet: The Kubernetes Node Agent                                                                    
caub@ins:~$ minikube stop
Stopping local Kubernetes cluster...
Error stopping machine:  Error loading host: minikube: Error loading host from store: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
caub@ins:~$ systemctl status localkube
Unit localkube.service could not be found.
caub@ins:~$ docker rm -f $(docker ps -aq --filter name=k8s)
8578c7b1bea8
e183a5235e1b
287efaf5a9e1
c6db9cdfb12a
7d3984489a09
f71639669d60
9539de5d8894
518112ab19d9
```
same thing after rebooting, those containers are restarted

**Comment by umartunes** [comment]
Found a hack:

**Comment by madkote** [comment]
hi, having same issue with minikube v1.9.0

```
minikube start --driver=docker
minikube status
minikube stop
...
docker ps
>>> here are k8s containers
docker kill $(docker ps -q)
>>> here are k8s containers AGAIN
```

**Comment by tstromberg** [comment]
@madkote - does it happen in minikube v1.9.2?
