### ISSUE TITLE
pod is not ready,status is ContainerCreating

### ISSUE THREAD

**Issue by sandylss** [kubernetes/minikube#2148]
hi,
now I am trying to deployment minikube in my computer,but i met some error,the pod is not ready ,i don't find the reason.

_****Environment**:**_
 ubuntu16.04.3 LTS, GNU/Linux 4.4.0-75-lowlatency x86_64
docker is 17.03.1-ce
minikube version: v0.23.0

# **_### OS_**
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

## _VM Driver_
"DriverName": "virtualbox",

**_ISO version_**
"Boot2DockerURL": "file:///home/lab931/.minikube/cache/iso/minikube-v0.23.6.iso"

I was follew the official document to install in my computer.
when i use  'kubectl run kubernetes-bootcamp --image=docker.io/jocatalin/kubernetes-bootcamp:v1 --port=8080' run a pod,the pod is not ready,status is ContainerCreating.
## **_i use kubectl describe pod,the resoult is_** 

Name:           kubernetes-bootcamp-6c74779b45-hds56
Namespace:      default
Node:           minikube/192.168.99.100
Start Time:     Thu, 02 Nov 2017 18:56:22 +0800
Labels:         pod-template-hash=2730335601
                run=kubernetes-bootcamp
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"kubernetes-bootcamp-6c74779b45","uid":"76de8fa5-bfbc-11e7-a474-0...
Status:         Pending
IP:             
Created By:     ReplicaSet/kubernetes-bootcamp-6c74779b45
Controlled By:  ReplicaSet/kubernetes-bootcamp-6c74779b45
Containers:
  kubernetes-bootcamp:
    Container ID:   
    Image:          docker.io/jocatalin/kubernetes-bootcamp:v1
    Image ID:       
    Port:           8080/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-j2lv7 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  default-token-j2lv7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-j2lv7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                  Age   From               Message
  ----     ------                  ----  ----               -------
  Normal   Scheduled               16s   default-scheduler  Successfully assigned kubernetes-bootcamp-6c74779b45-hds56 to minikube
  Normal   SuccessfulMountVolume   15s   kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-j2lv7"
  Warning  FailedCreatePodSandBox  0s    kubelet, minikube  Failed create pod sandbox.
  Warning  FailedSync              0s    kubelet, minikube  Error syncing pod

### ## **_## i found Failed create pod sandbox,but don't know why.

i try to deploy other pod,the result is the same。

## **_i also ues kubectl --v=8 logs $name to see the logs as follows:_**_**

I1102 19:43:13.446429    3515 loader.go:357] Config loaded from file /home/lab931/.kube/config
I1102 19:43:13.448879    3515 cached_discovery.go:119] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/servergroups.json
I1102 19:43:13.450252    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/apiregistration.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.450606    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/extensions/v1beta1/serverresources.json
I1102 19:43:13.450735    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/apps/v1beta1/serverresources.json
I1102 19:43:13.450869    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/apps/v1beta2/serverresources.json
I1102 19:43:13.450920    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/authentication.k8s.io/v1/serverresources.json
I1102 19:43:13.450971    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/authentication.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.451035    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/authorization.k8s.io/v1/serverresources.json
I1102 19:43:13.451099    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/authorization.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.451169    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/autoscaling/v1/serverresources.json
I1102 19:43:13.451232    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/autoscaling/v2beta1/serverresources.json
I1102 19:43:13.451290    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/batch/v1/serverresources.json
I1102 19:43:13.451345    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/batch/v1beta1/serverresources.json
I1102 19:43:13.451403    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/batch/v2alpha1/serverresources.json
I1102 19:43:13.451466    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/certificates.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.451537    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/networking.k8s.io/v1/serverresources.json
I1102 19:43:13.451598    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/policy/v1beta1/serverresources.json
I1102 19:43:13.451674    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1/serverresources.json
I1102 19:43:13.451782    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.451856    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1alpha1/serverresources.json
I1102 19:43:13.451911    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/settings.k8s.io/v1alpha1/serverresources.json
I1102 19:43:13.451968    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/storage.k8s.io/v1/serverresources.json
I1102 19:43:13.452023    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/storage.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.452083    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/admissionregistration.k8s.io/v1alpha1/serverresources.json
I1102 19:43:13.452140    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/apiextensions.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.452453    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/v1/serverresources.json
I1102 19:43:13.452660    3515 cached_discovery.go:119] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/servergroups.json
I1102 19:43:13.452728    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/apiregistration.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.452871    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/extensions/v1beta1/serverresources.json
I1102 19:43:13.452969    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/apps/v1beta1/serverresources.json
I1102 19:43:13.453096    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/apps/v1beta2/serverresources.json
I1102 19:43:13.453150    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/authentication.k8s.io/v1/serverresources.json
I1102 19:43:13.453200    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/authentication.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.453263    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/authorization.k8s.io/v1/serverresources.json
I1102 19:43:13.453325    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/authorization.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.453394    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/autoscaling/v1/serverresources.json
I1102 19:43:13.453454    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/autoscaling/v2beta1/serverresources.json
I1102 19:43:13.453524    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/batch/v1/serverresources.json
I1102 19:43:13.453584    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/batch/v1beta1/serverresources.json
I1102 19:43:13.453644    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/batch/v2alpha1/serverresources.json
I1102 19:43:13.453711    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/certificates.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.453771    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/networking.k8s.io/v1/serverresources.json
I1102 19:43:13.453829    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/policy/v1beta1/serverresources.json
I1102 19:43:13.453903    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1/serverresources.json
I1102 19:43:13.453976    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.454052    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/rbac.authorization.k8s.io/v1alpha1/serverresources.json
I1102 19:43:13.454104    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/settings.k8s.io/v1alpha1/serverresources.json
I1102 19:43:13.454159    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/storage.k8s.io/v1/serverresources.json
I1102 19:43:13.454212    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/storage.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.454272    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/admissionregistration.k8s.io/v1alpha1/serverresources.json
I1102 19:43:13.454335    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/apiextensions.k8s.io/v1beta1/serverresources.json
I1102 19:43:13.454614    3515 cached_discovery.go:72] returning cached discovery info from /home/lab931/.kube/cache/discovery/192.168.99.100_8443/v1/serverresources.json
I1102 19:43:13.456210    3515 round_trippers.go:414] GET https://192.168.99.100:8443/api/v1/namespaces/default/pods/kubernetes-bootcamp
I1102 19:43:13.456224    3515 round_trippers.go:421] Request Headers:
I1102 19:43:13.456233    3515 round_trippers.go:424]     Accept: application/json, */*
I1102 19:43:13.456243    3515 round_trippers.go:424]     User-Agent: kubectl/v1.8.2 (linux/amd64) kubernetes/bdaeafa
I1102 19:43:13.475416    3515 round_trippers.go:439] Response Status: 404 Not Found in 19 milliseconds
I1102 19:43:13.475430    3515 round_trippers.go:442] Response Headers:
I1102 19:43:13.475440    3515 round_trippers.go:445]     Content-Type: application/json
I1102 19:43:13.475448    3515 round_trippers.go:445]     Content-Length: 206
I1102 19:43:13.475455    3515 round_trippers.go:445]     Date: Thu, 02 Nov 2017 11:43:13 GMT
I1102 19:43:13.475605    3515 request.go:836] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"kubernetes-bootcamp\" not found","reason":"NotFound","details":{"name":"kubernetes-bootcamp","kind":"pods"},"code":404}
I1102 19:43:13.476638    3515 helpers.go:207] server response object: [{
  "metadata": {},
  "status": "Failure",
  "message": "pods \"kubernetes-bootcamp\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-bootcamp",
    "kind": "pods"
  },
  "code": 404
}]
F1102 19:43:13.476665    3515 helpers.go:120] Error from server (NotFound): pods "kubernetes-bootcamp" not found

Can someone tell me why ？
thank u~

**Comment by aaron-prindle** [comment]
Can you verify that the network in your VM is working properly?  Something like the output of:
`minikube ssh -- ping google.com`

**Comment by sandylss** [comment]
google.com is firewall-ed, but I can ping other websites

> minikube ssh -- ping baidu.com
> PING baidu.com (220.181.57.217): 56 data bytes
> 64 bytes from 220.181.57.217: seq=0 ttl=63 time=2.358 ms
> 64 bytes from 220.181.57.217: seq=1 ttl=63 time=1.895 ms
> 64 bytes from 220.181.57.217: seq=2 ttl=63 time=1.977 ms
> 64 bytes from 220.181.57.217: seq=3 ttl=63 time=1.873 ms
> 64 bytes from 220.181.57.217: seq=4 ttl=63 time=1.961 ms
> 64 bytes from 220.181.57.217: seq=5 ttl=63 time=1.828 ms

ping lo

> minikube ssh -- ping 127.0.0.1
> PING 127.0.0.1 (127.0.0.1): 56 data bytes
> 64 bytes from 127.0.0.1: seq=0 ttl=64 time=0.039 ms
> 64 bytes from 127.0.0.1: seq=1 ttl=64 time=0.050 ms
> 64 bytes from 127.0.0.1: seq=2 ttl=64 time=0.037 ms
> 64 bytes from 127.0.0.1: seq=3 ttl=64 time=0.032 ms

ping eth0

> minikube ssh -- ping 172.16.1.110
> PING 172.16.1.110 (172.16.1.110): 56 data bytes
> 64 bytes from 172.16.1.110: seq=0 ttl=63 time=0.219 ms
> 64 bytes from 172.16.1.110: seq=1 ttl=63 time=0.194 ms

Is there anything wrong?
thank you ~

**Comment by r2d4** [comment]
If you're behind a firewall, you should make sure to pass HTTP_PROXY and/or HTTPS_PROXY env variables to the docker daemon with `minikube start --docker-env`

https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

**Comment by dlorenc** [comment]
Did the http proxy vars work for you?

**Comment by wenpengfei** [comment]
@sandylss  Is this issue resolved?

**Comment by jmjava** [comment]
I am seeing the same issue using 1.8.0 and hyperv driver.

**Comment by dragonlayout** [comment]
@sandylss I saw you also use virtualbox, and inside the minikube vm, the docker try to use access the host's proxy address, so inside the vm, the proxy is change to another one.(In my opinion)
You can see the detail explanation in this link -> [Beginner having trouble with docker behind company proxy](https://forums.docker.com/t/beginner-having-trouble-with-docker-behind-company-proxy/3968).
This one real save my day.

**Comment by sandylss** [comment]
I have resolved this problem ,the reason is the kube-system pods don't run,so I pre-download the necessary images like gcr.io/google_containers/pause-amd64 etc,then the pods run .thank u all, I will closed the issues.

**Comment by kotocean** [comment]
@sandylss 能说一下具体怎么解决的吗？

**Comment by kotocean** [comment]
@sandylss  Can you tell me how to solve it? Now, there's the same problem.

**Comment by sandylss** [comment]
@kotocean 
If pre-download the images doesn't work ,you can try use `minikube ssh` into the minikube ,then download the imgaes.

**Comment by eric-chao** [comment]
@sandylss 
I pre-download the gcr.io... images out of the VirtualBox and minikube vm, but my minikube does not work yet, could you help me please?

**Comment by eric-chao** [comment]
@sandylss thanks a lot.
Resolved.
details as below:

**$ kubectl version**
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"6e937839ac04a38cac63e6a7a306c5d035fe7b0a", GitTreeState:"clean", BuildDate:"2017-09-28T22:57:57Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.0", GitCommit:"0b9efaeb34a2fc51ff8e4d34ad9bc6375459c4a4", GitTreeState:"clean", BuildDate:"2017-11-29T22:43:34Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}

**docker images inside minikube vm**
$ docker images
REPOSITORY                                             TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kubernetes-dashboard-amd64    v1.8.0              55dbc28356f2        5 weeks ago         119MB
gcr.io/k8s-minikube/storage-provisioner                v1.8.0              4689081edb10        7 weeks ago         80.8MB
gcr.io/k8s-minikube/storage-provisioner                v1.8.1              4689081edb10        7 weeks ago         80.8MB
gcr.io/google_containers/k8s-dns-sidecar-amd64         1.14.5              fed89e8b4248        3 months ago        41.8MB
gcr.io/google_containers/k8s-dns-kube-dns-amd64        1.14.5              512cd7425a73        3 months ago        49.4MB
gcr.io/google_containers/k8s-dns-dnsmasq-nanny-amd64   1.14.5              459944ce8cc4        3 months ago        41.4MB
gcr.io/google_containers/kubernetes-dashboard-amd64    v1.6.3              691a82db1ecd        5 months ago        139MB
gcr.io/google-containers/kube-addon-manager            v6.4-beta.2         0a951668696f        6 months ago        79.2MB
gcr.io/google_containers/pause-amd64                   3.0                 99e59f495ffa        20 months ago       747kB

**Comment by DanielRamosAcosta** [comment]
> Can you verify that the network in your VM is working properly? Something like the output of: `minikube ssh -- ping google.com`

@aaron-prindle I can't ping `google.com` from minikube, but I'm not behind a proxy. Yet I can reach google.com with the IP.

Any ideas?

**Comment by IamGabrielWu** [comment]
I met the same problem.
Below are the logs after run `minikube logs`

`Jun 12 13:39:39 minikube localkube[3020]: E0612 13:39:39.308470    3020 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Jun 12 13:39:39 minikube localkube[3020]: E0612 13:39:39.308498    3020 kuberuntime_manager.go:647] createPodSandbox for pod "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Jun 12 13:39:39 minikube localkube[3020]: E0612 13:39:39.309055    3020 pod_workers.go:186] Error syncing pod c4c3188325a93a2d7fb1714e1abf1259 ("kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)"), skipping: failed to "CreatePodSandbox" for "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)\" failed: rpc error: code = Unknown desc = failed pulling image \"gcr.io/google_containers/pause-amd64:3.0\": Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"`

gcr.io is blocked in China.
here is the link https://blog.csdn.net/yuanlulu/article/details/78441370  hope everyone who understand Chinese find it useful.
