### ISSUE TITLE
minikube doesn't start

### ISSUE THREAD

**Issue by zhezhang** [kubernetes/minikube#2149]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

Please provide the following details:

**Environment**: 

**Minikube version** (use `minikube version`): 
- **OS** (e.g. from /etc/os-release): macOS 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.6
- **Install tools**: curl
- **Others**:

**What happened**: Received the error "E1102 14:37:47.382123   39735 start.go:256] Error setting up kubeconfig:  could not read config: Error decoding config from data: 
: Object 'Kind' is missing in '"

**What you expected to happen**: minikube start --vm-driver=xhyve

**How to reproduce it** (as minimally and precisely as possible):

> zzhang:~ zzhang$ curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.23.0/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 39.2M  100 39.2M    0     0  19.9M      0  0:00:01  0:00:01 --:--:-- 19.9M
zzhang:~ zzhang$ minikube start --vm-driver=xhyve
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
E1102 14:40:09.223967   39811 start.go:256] Error setting up kubeconfig:  could not read config: Error decoding config from data: 
: Object 'Kind' is missing in '
'

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by kairen** [comment]
Which version of `kubectl` using on your environment?

**Comment by zhezhang** [comment]
@kairen 
> Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.2", GitCommit:"bdaeafa71f6c7c04636251031f93464384d54963", GitTreeState:"clean", BuildDate:"2017-10-24T21:07:53Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by ramonPires** [comment]
@zhezhang I had the same problem, and I found the solution here : https://github.com/kubernetes/minikube/issues/2131#issuecomment-340426586 , seems like a bug.

**Comment by richardson-marc** [comment]
this is an old issue; I had a similar error when I had an old .kube/config which specified an IP address which did was unreachable; presumably that came from a previous kubernetes exercise run on another network...
