### ISSUE TITLE
Add support for running with Docker for Mac and Windows

### ISSUE THREAD

**Issue by preillyme** [kubernetes/minikube#215]
It would be nice if we could support Docker for Mac and Windows.

**Comment by jstrachan** [comment]
or we could try get hyperkube to run inside Docker for Mac and Windows as a regular docker container? 
http://kubernetes.io/docs/getting-started-guides/docker/

**Comment by zoidbergwill** [comment]
[`kubernetes-anywhere`](https://github.com/kubernetes/kubernetes-anywhere)
has some ways to run Kubernetes on Docker for Mac, but it'd be awesome to
get `hyperkube` properly working on Docker for Mac.

**Comment by preillyme** [comment]
Looks like I can access the VM easy enough.

```
$ ls -l ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty
lrwxr-xr-x  1 preilly  staff  12 Jun 22 11:27 /Users/preilly/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/tty -> /dev/ttys000
$ screen /dev/ttys000
[detached]
```

This should be fairly easy to do...

**Comment by dlorenc** [comment]
Hey,

Running minikube inside a system based on Docker for Mac is definitely on our roadmap. We're tracking this work over in https://github.com/kubernetes/minikube/issues/99. Would you mind posting your work over there, and closing this as a duplicate?

**Comment by preillyme** [comment]
Thanks @dlorenc didn't see the other issue. Now closing..... I've got https://github.com/kubernetes/minikube/issues/99 problems and a kube ain't one. 👍

**Comment by mpseidel** [comment]
@preillyme what happened to the `and Windows` part of the issue :) ?

**Comment by chicagobuss** [comment]
Agreed, there should be a new issue for Docker for Windows support - ideally something that works nicely from within the new Windows Subsystem for Linux, as well.
