### ISSUE TITLE
minikube start -h does not document units of RAM for --memory flag

### ISSUE THREAD

**Issue by kylegong** [kubernetes/minikube#2151]
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.23.0

**What happened**:
I ran:

minikube start -h

For the --memory flag, it says:

--memory int                      Amount of RAM allocated to the minikube VM (default 2048)

**What you expected to happen**:

It should say the units of RAM, e.g. Megabytes, which is what I think this is, but I'm not sure.

**How to reproduce it** (as minimally and precisely as possible):

minikube start -h

**Comment by r2d4** [comment]
It is MB.  We should add this to the helptext.
