### ISSUE TITLE
Add deletion of deployment to Quickstart console output in README

### ISSUE THREAD

**Issue by futureperfect** [kubernetes/minikube#2152]
Given that some fraction of the user base for minikube is users new to Kubernetes using it as a vehicle for learning, I think it would be valuable to augment the Quickstart section of the README to include removal of the `hello-minikube` deployment. Something to the effect of:

```
~ % kubectl delete deployment hello-minikube                                           
deployment "hello-minikube" deleted
```
That way someone testing out their deployment but still learning the toolset isn't left with a loose deployment when they later on run `minikube start` that could interact with subsequent tutorials in unexpected ways. If that sounds reasonable, I'd be happy to submit a patch.

**Comment by r2d4** [comment]
Absolutely, we'd accept a PR for that.  You also might want to change the quickstart at https://github.com/kubernetes/website/blob/master/docs/getting-started-guides/minikube.md

**Comment by futureperfect** [comment]
@r2d4 Thanks for the pointer! Per your suggestion I've made the analogous issue and associated PR for the kubernetes/website project.
