### ISSUE TITLE
kubectl not found on a mac

### ISSUE THREAD

**Issue by dgdosen** [kubernetes/minikube#216]
Hi all;

I'm trying to run minikube on a mac (with virtualbox), and while I have it installed and running, but when I try to run `kubectl` from the command line, I get a `command not found: kubectl` error.

I can see the new vm in VirtualBox running after I enter `minikube start` and can even open the dashboard.  

What I cannot do is get kubectl to run. 

I've also run `eval $(minikube docker-env)` - but still no kubectl.

Any ideas?

**Comment by runseb** [comment]
@dgdosen you need to install it separately

```
wget https://storage.googleapis.com/kubernetes-release/release/v1.2.0/bin/darwin/amd64/kubectl
chmod +x kubectl
```

put it in your PATH somewhere

**Comment by aaron-prindle** [comment]
@runseb is correct.  An alternative method for installing `kubectl` would be to install gcloud from the instructions on this link:
[https://cloud.google.com/sdk/docs/quickstart-mac-os-x](https://cloud.google.com/sdk/docs/quickstart-mac-os-x)
And then running:
`gcloud components install kubectl`

**Comment by dgdosen** [comment]
Thanks for the quick feedback!  I'll PR a change to the readme.

**Comment by dlorenc** [comment]
See #83 as well.

**Comment by jatins** [comment]
@aaron-prindle Where does `gcloud components install kubectl` install the kubectl executable?

**Comment by phs** [comment]
I came here because `brew cask install minikube` currently fails to also provide a `kubectl`.  In that case you may want the CLI from brew:

```
brew install kubernetes-cli
```

**Comment by xMarkusSpringerx** [comment]
@phs `brew install kubernetes-cli` worked for me

**Comment by phs** [comment]
`brew cask` users [should now](https://github.com/caskroom/homebrew-cask/pull/35367) pull in `kubernetes-cli` automatically.

**Comment by darkn3rd** [comment]
I tried `gcloud components install kubectl`, but it is not linked anywhere.  It looks like it is an older version, `1.8.6`.  Homebrew currently has `1.10.2`.

**Comment by ggtmtmgg** [comment]
If you tried `gcloud components install kubectl` and got `command not found: kubectl` error, you can solve it by linking like `$ ln -s /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin/kubectl /usr/local/bin/`.
