### ISSUE TITLE
minikube fails to start cluster

### ISSUE THREAD

**Issue by queszama** [kubernetes/minikube#2169]
I am new to Kubernetes and was trying to build a cluster using minikube. While trying to start the cluster using minikube , it fails with the following error

`minikube start --vm-driver=kvm
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Downloading Minikube ISO
 140.01 MB / 140.01 MB [============================================] 100.00% 0s
E1107 12:30:30.581841   13820 start.go:150] Error starting host: Error creating host: Error with pre-create check: "Unable to connect to kvm driver, did you add yourself to the libvirtd group?`

I have already added the user to libvirt group. 
      `` $ id
        uid=1010(zaman) gid=1011(zaman) `groups=1011(zaman),498(libvirt)`

OS information is as follows:
`$` cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
$ minikube version
minikube version: `v0.23.0`

Other information as follows: 
`VM` Driver:  KVM 
docker-machine-driver-kvm-centos7 Version: v0.10.0/`

Please suggest .

**Comment by queszama** [comment]
This is resolved now as libvirtd was not running. The documentation has not mentioned to start the libvirtd service . 
https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm-driver

Now I am seeing the following error 

[blaskar@CAR-LNXSUPQ-002 ~]$ minikube start --vm-driver=kvm
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
`E1107` 23:05:52.127575    6677 start.go:150] Error starting host: Error creating host: Error with pre-create check: "virError(Code=43, Domain=19, Message='Network not found: no network with matching name `'default'')".`

**Comment by r2d4** [comment]
You should enable the default network using `virsh -c qemu:///system net-start default`

**Comment by queszama** [comment]
It is failing to start default network , can see it does not exist 

$ sudo virsh -c qemu:///system net-start default
error: failed to get network 'default'
error: Network not found: no network with matching name 'default'

$ sudo virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 docker-machines      active     yes           yes

**Comment by queszama** [comment]
This is resolved after I created a default network . But now it is giving different error

But now getting the following error

$ minikube start --vm-driver=kvm
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
E1108 02:25:56.289555   16262 start.go:150] Error starting host: Error getting state for host: unexpected EOF.

I am seeing lots of issues and had to do lots of workarounds which are not documented in minikube installation guide. 

[blaskar@CAR-LNXSUPQ-002 ~]$  egrep -c '(vmx|svm)' /proc/cpuinfo
0

Is it because I am doing the test on VM host  ? If that is the case what should I use for --vm-driver option . 

Please clarify

**Comment by r2d4** [comment]
If you're running minikube on a vm, you need to use the none driver.

**Comment by dlorenc** [comment]
Closing, looks like a none-driver issue.
