### ISSUE TITLE
registry-creds doesn't work in kube-system

### ISSUE THREAD

**Issue by neverfox** [kubernetes/minikube#2170]
Please provide the following details:

**Minikube version** (use `minikube version`): v0.23.0
- **OS** (e.g. from /etc/os-release): OS X 10.12.6 (16G29)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.6

**What happened**:
deployment with ECR image into kube-system namespace results in no basic auth credentials failure

**What you expected to happen**: Successful image pull

**How to reproduce it** (as minimally and precisely as possible):
`minikube addons configure registry-creds` - Fill in ECR info
`minikube addons enable registry-creds`
Also restarting registry-creds pod to ensure latest secret is used.
Verify that secret contains proper info (yes)
Also successfully deploy image to default namespace to prove this is a namespace issue.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
logs from registry-creds mention "Finished processing secret for namespace kube-public" and "Finished processing secret for namespace default" but not kube-system

**Comment by r2d4** [comment]
Currently the secrets are only generated for the default namespace.  We'll need to fix this in the upstream registry-creds repo https://github.com/upmc-enterprises/registry-creds

**Comment by KaoruDev** [comment]
Passing in the namespace works for me. I.e.:

`kubectl create secret docker-registry ...auth stuff... -n my_namespace`
