### ISSUE TITLE
Question - Kubernetes 1.8.1 and deployment/RBAC

### ISSUE THREAD

**Issue by alexellis** [kubernetes/minikube#2173]
Question - when/how do we get minikube support for Kubernetes 1.8.1 and deployments/RBAC?

**What happened**:

The transition from Kubernetes 1.7 to 1.8.x seems to be causing issues for our project [openfaas/faas-netes](https://github.com/openfaas/faas-netes). Since the upgrade to 1.8.0 I can no longer use deployments in the namespace `apps/v1beta1` auth is also broken in the namespace `rbac.authorization.k8s.io/v1beta1`.

With Kubernetes 1.8.1 the fix is to move everything to:

```
apps/v1beta2
rbac.authorization.k8s.io/v1
```

In Kubernetes 1.8.0 with Minikube the same configuration gives strange errors like this:

```
Error from server (BadRequest): error when creating "faas.yml": the API version in the data (apps/v1beta2) does not match the expected API version (apps/v1beta1)
```

It's unfortunate that updating a cluster means maintaining two or three sets of configuration files for each Kubernetes version - 1.7, 1.8.0 and 1.8.1. I'm not sure how we fix this but in the meantime it would be good to have Kubernetes 1.8.1 available for `minikube`.

I'm not sure how to support this configuration.

```
$ minikube get-k8s-versions
The following Kubernetes versions are available: 
	- v1.8.0

$ Darwin alexr.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"darwin/amd64"}
```

**Comment by r2d4** [comment]
You can get 1.8.1 and RBAC with `minikube config set bootstrapper kubeadm`, which will eventually be the default option.

With kubeadm, the `get-k8s-versions` is ignored.  For a lengthier explanation, see https://github.com/kubernetes/minikube/issues/2156#issuecomment-341921701

**Comment by r2d4** [comment]
I'm going to close this, since I don't think we plan on supporting RBAC by default in localkube.  You can use the kubeadm bootstrapper, which will be the default in 1.9.
