### ISSUE TITLE
CHANGE_MINIKUBE_NONE_USER is incomplete

### ISSUE THREAD

**Issue by TonyApuzzo** [kubernetes/minikube#2176]
BUG REPORT

Please provide the following details:

**Environment**:

minikube version: v0.23.0

OS:
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

VM driver:
    "DriverName": "none",

**What happened**:

When using CHANGE_MINIKUBE_NONE_USER the configuration files are not correctly set up for use by the calling user.  The only thing that using this environment variable does is cause the .minikube and .kube folders that are under /root to be owned by the calling user.  It doesn't move the configuration nor does it configure the paths correctly once the configurations are moved.

**What you expected to happen**:
I would expect minikube to be operational with the ~/.minikube and ~/.kube folders configured correctly under the calling user's home folder (not root).
I would expect `minikube` and `kubectl` commands to work after starting minikube.

**How to reproduce it** (as minimally and precisely as possible):
```
sudo -i env CHANGE_MINIKUBE_NONE_USER=true minikube start --vm-driver=none
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

To be clear, this is what I have to do to get minikube operational on a fresh CentOS server:
```bash
# On root's path doesn't include /usr/local/bin, which will nerf `minikube start` later
sudo ln -s /usr/local/bin/kubectl /usr/local/sbin/
sudo ln -s /usr/local/bin/minikube /usr/local/sbin/

# Run minikube start twice to get the service registered
sudo -i env CHANGE_MINIKUBE_NONE_USER=true minikube start --vm-driver=none --alsologtostderr
sudo -i env CHANGE_MINIKUBE_NONE_USER=true minikube start --vm-driver=none --alsologtostderr

# This will now show localkube enabled and running
systemctl status localkube.service

# Config files have been set to the correct user but are still in the wrong place
sudo mv /root/.minikube /root/.kube $HOME

# The paths in .kube/config are wrong
sed -i~ "s,/root/,$HOME/," $HOME/.kube/config 

# Now everything is hunky-dory!
kubectl version --short
systemctl status localkube
minikube status
```

**Comment by r2d4** [comment]
You need to set both the KUBECONFIG and MINIKUBE_HOME env vars additionally to get that behavior. 

I agree, these env vars might be able to be collapsed into a single one.  

```
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true
export KUBECONFIG=$HOME/.kube/config
```

**Comment by TonyApuzzo** [comment]
Ah! That is awesome. I only know about CHANGE_MINIKUBE_NONE_USER because of what `minikube start --vm-driver=none` prints out a description of doing the chown / mv and that this can done automatically with the env varible.

It would really help if the admonition that prints when you start with 'none' drive would tell you about the other environment variables.

Thanks, I'll close this issue since it is really a documentation issue not a bug.
