### ISSUE TITLE
Add a KubeVirt add-on

### ISSUE THREAD

**Issue by fabiand** [kubernetes/minikube#2178]
KubeVirt provides adds a virtualization API to Kubernetes in order to launch regular virtual machines.

This request is about adding KubeVirt as an add-on to minikube, based on the work in https://github.com/kubevirt/kubevirt/pull/562.

Once this PR is merged, we can import manifests from the official releases in order to deploy KubeVirt in minikube.

**Comment by r2d4** [comment]
I think this sounds reasonable.

**Comment by fabiand** [comment]
We'll pick this up shortly again.

**Comment by gbraad** [comment]
This add-on would also need changes to the CentOS ISO, or we should be able
to set a requirement of needs `SupportsVirtualization` as provisioner flags?

**Comment by fabiand** [comment]
We'll need KVM support in the ISO, but besides that I'm not aware of any specific host feature we need.

Did you have anything specific in mind?

**Comment by gbraad** [comment]
The current ISO does not come with libvirt installed...

During the provisioning phase, we can collect information about the ISO to
make sure certain features are available. Juts a thought... as we do this
for the Static IP functionality.

**Comment by fabiand** [comment]
@gbraad you know - the cool thing is - kubevirt is _cloud-native_ (we love this term, do we?) ;)

All dependencies - except for certain kernel features - are delivered as containers - including libvirt.

**Comment by gbraad** [comment]
Whoops, thought this was the Minishift repo... (changing message)

**Comment by fabiand** [comment]
KubeVirt now has an operator which should ease deployment and removal:
https://github.com/kubevirt/user-guide/blob/master/administration/intro.adoc#2-alternative-flow-aka-operator-flow

/reopen

**Comment by tstromberg** [comment]
Anyone interested in creating an addon for this? PR's welcome!

Documentation: https://minikube.sigs.k8s.io/docs/contributing/addons/

**Comment by fabiand** [comment]
Nice to see the documentation. I'll ask around if there is a volunteer

**Comment by tstromberg** [comment]
This is still an issue AFAIK. Help wanted!

**Comment by fabiand** [comment]
Yes. Today it's much simpler than a year ago. However, we need somebody to
write the basic plugin. volunteers are welcome.

**Comment by sharifelgamal** [comment]
This is still an outstanding issue.
