### ISSUE TITLE
DNS is not working, because the kube-dns service is invalid

### ISSUE THREAD

**Issue by patrikerdes** [kubernetes/minikube#2188]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Environment**:

**Minikube version** (use `minikube version`): latest commit in `master` ([10f2bb578d15c6941f5de78a36ff35a53cc8520f](https://github.com/kubernetes/minikube/commit/10f2bb578d15c6941f5de78a36ff35a53cc8520f))
- **OS** (e.g. from /etc/os-release): macOS 10.13.1
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.5.iso
- **Install tools**:
- **Others**:

**What happened**: The kube-dns service does not start

**What you expected to happen**: That the kube-dns service starts up

**How to reproduce it** (as minimally and precisely as possible):
```
make
out/minikube start
kubectl -n kube-system get service
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
In the log of the addon-manager:
```
$ kubectl logs kube-addon-manager-minikube --namespace=kube-system
...
The Service "kube-dns" is invalid: spec.clusterIP: Invalid value: "10.96.0.10": provided IP is not in the valid range. The range of valid IPs is 10.0.0.0/24
...
```

**Comment by patrikerdes** [comment]
Seems to be related to this commit: https://github.com/kubernetes/minikube/commit/fc105d3328f576750adc52da934f81ad172bb236

**Comment by r2d4** [comment]
If you are building from HEAD, you need to run either with `--kubernetes-version=file:///path/to/localkube` or `bootstrapper=kubeadm`

**Comment by patrikerdes** [comment]
Thanks, it's working with kubeadm.

**Comment by spiralman** [comment]
I am having this same issue using Minikube downloaded following the official instructions, version 0.24.0:

OS (e.g. from /etc/os-release): macOS 10.13.1
VM Driver (e.g. cat ~/.minikube/machines/minikube/config.json | grep DriverName): virtualbox
ISO version (e.g. cat ~/.minikube/machines/minikube/config.json | grep -i ISO or minikube ssh cat /etc/VERSION): minikube-v0.23.5.iso

Note that the minikube ISO does not match the minikube version I'm running. I've tried deleting my VM, deleting my ~/.minikube directory, and re-creating from scratch, but am still having this problem.

**Comment by spiralman** [comment]
Upgrading minikube to version `0.24.1` resolved the issue. Thanks for the quick fix!
