### ISSUE TITLE
kubeadm should enable apiVersion batch/v2alpha1 and batch/v1beta1 for CronJob

### ISSUE THREAD

**Issue by Morriz** [kubernetes/minikube#2190]
Reopening #1977 since this is not sufficient for us who need to be able to run `v2alpha1`. Any idea how that is possible otherwise?

I am using `gcr.io/google_containers/kube-state-metrics:v1.1.0` which is referring to the `v2alpha1` version and can't find it. I tried to rebuild that image for the newer version but failed. I would love to be able to use the old alpha version now, instead of waiting for the new image.

**Comment by ijl** [comment]
@Morriz I think you can now configure kubeadm as in #2037. This was't possible when the original issue was opened.

**Comment by r2d4** [comment]
Correct, you should be able to configure the apiserver with 

`--extra-config=apiserver.runtime-config=api/all=false,api/v1=true --bootstrapper=kubeadm`

**Comment by r2d4** [comment]
Closing this, let us know if you're still having trouble.
