### ISSUE TITLE
Expose --cgroup-driver kubelet option

### ISSUE THREAD

**Issue by iaguis** [kubernetes/minikube#2192]
We're trying to make [rktlet](https://github.com/kubernetes-incubator/rktlet) work on minikube.

As a first step, I was trying to run it manually inside the minikube VM but it didn't work because rktlet requires `--cgroup-driver=systemd` to work and, AFAIK there's no way to configure minikube to run localkube with that option.

Does exposing the option make sense? Should it be added only to localkube and we'd just set it to `systemd` if/when the `--container-runtime=rkt` option switches to rktlet?

**Comment by r2d4** [comment]
You should be able to toggle it with the --extra-config flag, which modifies the values on the kubeletconfig struct (for localkube)
https://godoc.org/k8s.io/kubernetes/pkg/kubelet/apis/kubeletconfig

For localkube, you would use
`--extra-config=kubelet.CgroupDriver=systemd`

Or for the kubeadm bootstrapper, you can pass the flag directly: 
`--extra-config=kubelet.cgroup-driver=system`

**Comment by iaguis** [comment]
Thanks, that's what I was looking for.
I should've read the [docs](https://github.com/kubernetes/minikube/blob/v0.23.0/docs/configuring_kubernetes.md) 😅. Sorry about that!
