### ISSUE TITLE
VirtualBox support for virtio-net network adapter

### ISSUE THREAD

**Issue by ijl** [kubernetes/minikube#2196]
I'd like to add support for the virtualbox driver to use the virtio-net network adapter. This is to improve performance.

minikube should probably just default to virtio-net given we know we're using a Linux 2.6.25+ kernel. See the VBoxManage docs: https://www.virtualbox.org/manual/ch06.html. The default in docker machine is currently `defaultHostOnlyNictype     = "82540EM"`, which docs note supports Windows.

If changing the default isn't acceptable or it should be configurable, it seems consistent to support this usage: `minikube start --vm-driver=virtualbox --virtualbox-network=virtio-net`. There's an existing, similar `--kvm-network` flag.

**Comment by r2d4** [comment]
I think its reasonable to make it the default as long as it works across all platforms.  If it doesn't work for a particular platform (windows?) then I still think its reasonable to add it as a flag.

**Comment by chancez** [comment]
I never even thought about this, but this is likely to be a huge improvement. Any thoughts on making it possible to specify the network adapter type via a flag or config option? Might be nice to be able to use the intel NICs as well.
