### ISSUE TITLE
Custom Resource Definition (CRD) not working with minikube 0.23.0

### ISSUE THREAD

**Issue by secat** [kubernetes/minikube#2199]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:

**Minikube version** : 0.23.0
- **OS** : Windows 10
- **VM Driver** : virtualbox 5.1.18
- **ISO version** : minikube-v0.23.6.iso
- **Install tools**:
- **Others**: kubernetes version 1.8.0

**What happened**:

I installed the istio control plane (https://github.com/istio/istio/blob/master/install/kubernetes/istio.yaml) which includes several CRD resources. It works fine at the beginning. 

By example:
```
$ kubectl get rules.config.istio.io --all-namespaces
NAMESPACE      NAME       KIND
istio-system   promhttp   rule.v1alpha2.config.istio.io
istio-system   promtcp    rule.v1alpha2.config.istio.io
istio-system   stdio      rule.v1alpha2.config.istio.io
```
However after a while the CRD are not present anymore from the `apiserver` standpoint.

Following the same example above:
```
$ kubectl get rules.config.istio.io --all-namespaces
No resources found.
```

It works fine with **minikube 0.22.3**.

**What you expected to happen**:

The CRD resources created that are not deleted should be reachable by the apiserver and should not disapear.

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by r2d4** [comment]
I haven't been able to reproduce this developing CRDs on minikube.  Are you doing a start/stop or anything else to help reproduce it?  We did upgrade to kubernetes 1.8 from 0.22.3->0.23.0 so its very possible theres something there.

Can you reproduce it with `--bootstrapper kubeadm` or just with localkube?

**Comment by secat** [comment]
Currently I am on localkube, I will try the `--bootstrapper kubeadm` option.

**Comment by secat** [comment]
@r2d4 Minikube hangs when using the `--bootstrapper kubeadm` option.

Is there a way to retrieve the `apiserver` logs on minikube?

I get errors like these ones when using CRD after 1 or 2 days:
```
Error from server (Timeout): the server was unable to return a response in the time allotted, but may still be processing the request (get prometheuses.monitoring.coreos.com)
```
