### ISSUE TITLE
Parallels Desktop Support

### ISSUE THREAD

**Issue by pnovotnak** [kubernetes/minikube#220]
I use Parallels on my laptop, so I'd like to add Parallels driver support via the [Parallels docker-machine driver](https://github.com/Parallels/docker-machine-parallels).

**Comment by dlorenc** [comment]
Hey,

We're trying to settle on a relatively small driver base that will address all needs. Would you mind commenting over on https://github.com/kubernetes/minikube/issues/261 with any of the benefits parallels has?
