### ISSUE TITLE
Stupid question: Why not on top of vagrant?

### ISSUE THREAD

**Issue by mrusu91** [kubernetes/minikube#2200]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):FEATURE REQUEST

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release):
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
```

echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
I'm just wandering why not make minikube a vagrant provisioner. Vagrant already has support for common providers, has support for rsync and NFS.

I didn't looked too deep into minikube's code, I believe it also does some state/file management and also manages k8s upgrades, but k8s upgrade mgmt can be offloaded to kubeadm.

I'm also aware of  vm-driver=none which is a nice thing and that logic could be the same(sort of) like the 'post-boot' provisioning of the VM

**Comment by r2d4** [comment]
* No dependency on vagrant
* We build minikube on top of a lot of the work done in docker-machine, which is written in Go and therefore easily usable by other Go projects.  
* More granular control over the provisioning and boot process
* docker-machine also had a very similar goal (provisioning a minimal machine with a container runtime) vs. provisioning all sorts of machines.
* The goal is to hide the VM as much as possible, except for power users with a deep understanding to configure things.
* we already utilize kubeadm to do much of the kubernetes setup.
* Native hypervisor support on macOS

There are probably other reasons, but naturally minikube extended a lot of the work done in docker-machine and evolved to its current state.  If you still have questions on the minikube architecture, feel free to post on the #minikube slack and I'd be happy to answer any of your questions.
