### ISSUE TITLE
ingress session affinity cookies not set

### ISSUE THREAD

**Issue by patriot1burke** [kubernetes/minikube#2206]
Is this a BUG REPORT or FEATURE REQUEST? (choose one): BUG REPORT

Environment:

Minikube version : 0.23.0

OS : OSX 10.13.1
VM Driver : virtualbox
ISO version : minikube-v0.23.6.iso
Install tools:
Others: kubernetes version 1.8.0
What happened:

I do not see any session affinity cookies set in browser.

$ minikube addons enable ingress

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/affinity: cookie
    ingress.kubernetes.io/session-cookie-hash: sha1
    ingress.kubernetes.io/session-cookie-name: route
    kubernetes.io/ingress.class: nginx
  creationTimestamp: 2017-11-17T21:49:33Z
  generation: 6
  name: app
  namespace: default
  resourceVersion: "297266"
  selfLink: /apis/extensions/v1beta1/namespaces/default/ingresses/app
  uid: 32c2b99b-cbe1-11e7-9c0c-080027566197
spec:
  rules:
  - host: foo.bar
    http:
      paths:
      - backend:
          serviceName: hello-node
          servicePort: 8080
status:
  loadBalancer:
    ingress:
    - ip: 192.168.99.100

**Comment by jpconver** [comment]
I'm having the same issue, I reported an issue to kubernetes/ingress-nginx but I'm not sure if this problem is caused by some issue in minikube ->[](https://github.com/kubernetes/ingress-nginx/issues/2252)
