### ISSUE TITLE
how can i specified external-etcd-endpoints in 1.8.0

### ISSUE THREAD

**Issue by niuhp** [kubernetes/minikube#2210]
how can i init kubeneter cluster with kubeadm , i have all images in myrepo.com/google_containers and etcd cluster (http://etcd1:2379,http://etcd2:2379,http://etcd3:2379), i have installed kubeadm、kubectl、kubelet、docker

**Comment by dlorenc** [comment]
Could you re-open this issue on the kubeadm repo?
https://github.com/kubernetes/kubeadm
