### ISSUE TITLE
kube-dns pod is not deleted when you disable it with `minikube addons disable kube-dns`

### ISSUE THREAD

**Issue by ysim** [kubernetes/minikube#2214]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

- **Minikube version** (use `minikube version`): `v0.23.0`
- **OS** (e.g. from /etc/os-release): OS X 10.13.1
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): `virtualbox`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): `minikube-v0.23.6.iso`
- **Install tools**:
- **Others**:

**What happened**:

Once minikube is started with the default configuration, disabling kube-dns with `minikube addons disable kube-dns` does not actually terminate the kube-dns service, even though it still shows up as `disabled` when you run `minikube addons list`. 

**What you expected to happen**:

kube-dns should be fully shut down. 

**How to reproduce it** (as minimally and precisely as possible):

- Start Minikube with the above environment
- `minikube addons disable kube-dns`
- `minikube addons list` - `kube-dns` is "disabled"; however it is still running as a pod/service

**Comment by r2d4** [comment]
The addons command will only disable the addon on subsequent creations of a minikube VM.  It won't have any effect on a running cluster.  You'll need to do a minikube delete and another minikube start to see the kube-dns deployment gone.

**Comment by ysim** [comment]
Aha, okay, thanks for the clarification! When I saw that it was disabled when I ran `minikube addons list` I just assumed the changes took effect immediately. 

Does this also apply to enabling addons? i.e. are they only enabled upon the VM being recreated?

**Comment by r2d4** [comment]
I believe addons should be enabled immediately, since the addon-manager continuously looks for new addons, but keeps little state on the the currently running addons.
