### ISSUE TITLE
Move localkube to kubernetes/kubernetes

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#222]

**Comment by dlorenc** [comment]
We should probably fix the DNS server first. #55

**Comment by luxas** [comment]
Yes, and maybe #123 
For those who are interested, this is what we have to do before you may choose k8s version #201

**Comment by dlorenc** [comment]
To be clear we could support #201 without moving localkube to kubernetes. It depends on the granularity at which people need to be able to set their k8s version. We could easily publish localkube builds for every kubernetes point release.

**Comment by aaron-prindle** [comment]
#558

**Comment by luxas** [comment]
Closing this... I don't think we should do it anymore, minikube should use localkube separately
