### ISSUE TITLE
v0.23.0 has empty hash in GitHub release notes

### ISSUE THREAD

**Issue by jedsmith** [kubernetes/minikube#2228]
On the [releases page](https://github.com/kubernetes/minikube/releases), minikube releases have historically included a SHA256 sum of the ISO for verification purposes. The latest release, [v0.23.0](https://github.com/kubernetes/minikube/releases/tag/v0.23.0), has an empty SHA256 field:

    $ openssl sha256 minikube.iso
    SHA256(minikube.iso)=

While [v0.22.3](https://github.com/kubernetes/minikube/releases/tag/v0.22.3), by contrast, has a hash:

    $ openssl sha256 minikube.iso
    SHA256(minikube.iso)=
    7f0766b20c237fbaa5bdbcb0a08dbc5cc839343b7862e882f2a9f79ac1c18826

**Comment by r2d4** [comment]
Thanks for pointing this out.  This is one hole in our release process.  We usually add the iso sha256 as a parameter to our release job instead of calculate it directly.  We should really just populate it automatically like we do everything else.

**Comment by dlorenc** [comment]
Added the SHA manually.
