### ISSUE TITLE
hyperkit driver - unable to find file /boot/bzimage

### ISSUE THREAD

**Issue by huguesalary** [kubernetes/minikube#2236]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Environment**: Mac OS X El Capitan

**Minikube version** (use `minikube version`): N/A
- **OS**: Mac OS X El Capitan
- **VM Driver**: hyperkit
- **ISO version**: v17.11.0-ce

**What happened**:

This bug report is about the hyperkit driver, but I'm using the `docker-machine` binary not `minikube`.

**What you expected to happen**:

The hyperkit driver doesn't seem to work with docker-machine (Maybe it isn't intended to?)

Basically, typing `docker-machine -D create --driver hyperkit` will fail with

`Error creating machine: Error in driver during machine creation: unable to find file /boot/bzimage
`

Looking at the source code, it seems to assume the presence of 

`/boot/bzimage`, `/boot/initrd`, `/isolinux/isolinux.cfg`

I checked my ISO (`v17.11.0-ce`), and fair enough, those files are missing. Which I assume is because Minikube doesn't use the same ISO as docker-machine.

Here's the full output: 

```
Docker Machine Version:  0.13.0, build 9ba6da9
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:52485
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(flag-lookup) Calling .GetMachineName
(flag-lookup) Calling .DriverName
(flag-lookup) Calling .GetCreateFlags
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:52491
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(hyperkit) Calling .GetMachineName
(hyperkit) Calling .DriverName
(hyperkit) Calling .GetCreateFlags
(hyperkit) Calling .SetConfigFromFlags
Running pre-create checks...
(hyperkit) Calling .PreCreateCheck
(hyperkit) Calling .GetConfigRaw
Creating machine...
(hyperkit) Calling .Create
(hyperkit) DBG | local Boot2Docker ISO version:  v17.11.0-ce
(hyperkit) Copying /Users/hugues/.docker/machine/cache/boot2docker.iso to /Users/hugues/.docker/machine/machines/hyperkit/boot2docker.iso...
(hyperkit) DBG | 2017/11/29 17:00:28 [INFO] Creating ssh key...
(hyperkit) DBG | 2017/11/29 17:00:29 [INFO] Creating raw disk image...
(hyperkit) DBG | Writing magic tar header
(hyperkit) DBG | Writing SSH key tar header
Error creating machine: Error in driver during machine creation: unable to find file /boot/bzimage
notifying bugsnag: [Error creating machine: Error in driver during machine creation: unable to find file /boot/bzimage]
```

**Comment by dlorenc** [comment]
Yeah sorry, this isn't intended to work with docker-machine, or more specifically with generic ISO images.

**Comment by dlorenc** [comment]
Going to close this, but I'm still interested in hearing about the use case. Why do you want to use this driver with docker machine?

**Comment by huguesalary** [comment]
I originally simply wanted to test the `hyperkit` driver, without deleting my current minikube cluster (since `minikube` doesn't allow you to create multiple clusters, which by the way, hint hint feature request!).

I also planned on creating a `docker-machine` with this driver because I wanted to compile `minikube` with it since  the `docker-machine` using `xhyve` that I used in the past to compile `minikube` stopped working.

I've been using `xhyve` (and submitting PR's to) for the longest time, but it's obviously being faded out in favor of `hyperkit`, which is great since `hyperkit` is maintained and `xhyve` isn't. So I was going to evaluate `hyperkit` vs `xhyve` and potentially starting implementing a few features I need for my personal use.

**Comment by dlorenc** [comment]
Ah, some good news then - you can run multiple minikube instances at the same time. Check out "profiles". On my phone so I can't find a better link, but here's some code: https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/config/profile.go

**Comment by dlorenc** [comment]
cc @aaron-prindle

**Comment by huguesalary** [comment]
Ha great! I somehow never noticed the profile subcommand.

Wouldn't there be a use case for making the `hyperkit` driver also available to docker-machine? 

As I see it, `xhyve` is fading out rapidly and soon enough the only choice left for docker-machine users will be `virtualbox` and `vmware`.

**Comment by dlorenc** [comment]
Yeah possibly - my understanding though is that machine itself is also being phased out though.

**Comment by huguesalary** [comment]
Interesting. I wasn't aware of this. Do you happen to know where you read this?

**Comment by chaimleib** [comment]
> As I see it, xhyve is fading out rapidly and soon enough the only choice left for docker-machine users will be virtualbox and vmware.

[`docker-machine-parallels`](https://github.com/Parallels/docker-machine-parallels) is another option.

```
brew install docker-machine-parallels
```

It booted a few seconds faster than `virtualbox`, and even than Docker for Mac (which uses `hyperkit`, right?).
