### ISSUE TITLE
Can't create a hyperkit machine

### ISSUE THREAD

**Issue by zoidbergwill** [kubernetes/minikube#2238]
Please provide the following details:

**Environment**: 

**Minikube version** (use `minikube version`): 0.24.0
- **OS** (e.g. from /etc/os-release): OSX El Capitan
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.5.iso
- **Install tools**:
- **Others**:

**What happened**:

Tried to create a VM with the hyperkit driver, got:

```
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
E1130 10:55:04.195417   45354 start.go:150] Error starting host: Error starting stopped host: Kernel /Users/william/.minikube/machines/minikube/bzimage does not exist.

 Retrying.
E1130 10:55:04.196806   45354 start.go:156] Error starting host:  Error starting stopped host: Kernel /Users/william/.minikube/machines/minikube/bzimage does not exist
```
Other times I get:

```
E1130 11:06:53.805272   45952 start.go:150] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: making disk image: truncate /Users/william/.minikube/machines/minikube/minikube.rawdisk: no space left on device.

 Retrying.
E1130 11:06:53.806668   45952 start.go:156] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: making disk image: truncate /Users/william/.minikube/machines/minikube/minikube.rawdisk: no space left on device
```

**What you expected to happen**:

Successful creation

**How to reproduce it** (as minimally and precisely as possible):

`minikube start --vm-driver hyperkit`

**Output of `minikube logs` (if applicable)**:

```
F1130 11:07:24.078756   46013 logs.go:50] Error getting cluster bootstrapper: getting localkube bootstrapper: getting ssh client: Error dialing tcp via ssh client: dial tcp :22: getsockopt: connection refuse
```

:/

**Anything else do we need to know**:

**Comment by huguesalary** [comment]
` /Users/william/.minikube/machines/minikube/minikube.rawdisk: no space left on device.`

How much disk space do you have left? Apparently, none.

Check with `df -h` and copy/paste the output here.

**Comment by zoidbergwill** [comment]
I had lots of spare disk on my machine. Will link in a sec.

**Comment by zoidbergwill** [comment]
Ahhh, so maybe this was all an error on my side and the following error message was throwing me off:

```
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
E1130 10:55:04.195417   45354 start.go:150] Error starting host: Error starting stopped host: Kernel /Users/william/.minikube/machines/minikube/bzimage does not exist.

 Retrying.
E1130 10:55:04.196806   45354 start.go:156] Error starting host:  Error starting stopped host: Kernel /Users/william/.minikube/machines/minikube/bzimage does not exist
```

I double checked disk free and changed the size of the minikube VM's disk to fit and now it's all happy.

**Comment by amencarini** [comment]
Hi @zoidbergwill, when you say you changed the size of the minikube's VM disk, where did you change it? I'm experiencing the same problem and am not sure where to operate.

**Comment by zoidbergwill** [comment]
When creating the minikube VM, I used:

```
minikube start --vm-driver hyperkit --disk-size 10g
```
