### ISSUE TITLE
Docker version downgraded after v0.24.0

### ISSUE THREAD

**Issue by bah2830** [kubernetes/minikube#2243]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.24.0
- **OS** (e.g. from /etc/os-release): Mac OS High Sierra 10.13.1
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.23.5.0 or minikube-v0.24.0 (v0.23.6 seems to work)
- **Install tools**: 
- **Others**:

**What happened**:
After updating to minkube 0.24.0 the docker version has been downgraded to 1.12

**What you expected to happen**: 
Remain the same or higher than what was in v0.23.0 (17.06)

**How to reproduce it** (as minimally and precisely as possible): start a new minikube VM
 
Looking at the source it looks like 17.06 should still be used but the ISO is not. It looks like the makefile downgraded the ISO from 23.6 to 23.5 in https://github.com/kubernetes/minikube/commit/30667cb406029b1e74562c9196b522adfa916540

**Comment by r2d4** [comment]
I just sent a PR for this, sorry about that.

**Comment by bah2830** [comment]
No worries. I can run with `--iso-url https://storage.googleapis.com/minikube/iso/minikube-v0.23.6.iso` for now. I was about to open the PR myself when I saw yours.

Thanks

**Comment by r2d4** [comment]
Fixed with 0.24.1 https://github.com/kubernetes/minikube/releases/tag/v0.24.1
