### ISSUE TITLE
HyperV startup failed error starting host

### ISSUE THREAD

**Issue by yaleman** [kubernetes/minikube#2255]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Environment**:

**Minikube version** : v0.24.1
- **OS** (e.g. from /etc/os-release): Windows 10 Pro
- **VM Driver** : hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):  minikube-v0.23.6
- **Install tools**: manual download and chocolatey tried
- **Others**:

**What happened**: Tried running `minikube.exe start --hyperv-virtual-switch base --vm-driver hyperv -v 7` and it failed

**What you expected to happen**: Minikube should start for the first time

**How to reproduce it** (as minimally and precisely as possible): run the command above

**Output of `minikube logs` (if applicable)**:
```E:\Minikube>minikube.exe start --hyperv-virtual-switch base --vm-driver hyperv -v 7
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM


[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Start-VM minikube
[stdout =====>] :
[stderr =====>] : Start-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Start-VM minikube
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.StartVM


E1201 23:16:48.643261   14168 start.go:150] Error starting host: Error starting stopped host: exit status 1.

 Retrying.
E1201 23:16:48.653249   14168 start.go:156] Error starting host:  Error starting stopped host: exit status 1
```

**Anything else do we need to know**: I have docker installed but the docs say that shouldn't interfere.

**Comment by JonJam** [comment]
I get the same as well.

**Comment by ajarv** [comment]
May be it will help  to remove the .minikube  or .kube folders in %USERPROFILE%

**Comment by Teklie** [comment]
> I had the same as well.
> 
> I got round it by deleting the .minikube folder in my User Account, as detailed here: http://www.dotjson.uk/minikube-w10/

Thanks @JonJam . Deleting the .minikube folder helped out :)
