### ISSUE TITLE
Setting max open files value

### ISSUE THREAD

**Issue by balboah** [kubernetes/minikube#2265]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature
**Minikube version**: v0.24.1
- **OS**: MacOS
- **VM Driver**: virtualbox
- **ISO version**: v0.23.6

To better match the environment on GCP and to support running the same set of services, I need to set the max open files (ulimit -n) of the docker daemon.

As I couldn't find a built in way to do this I'm requesting for such a setting to exist or a higher number of allowed open files. Google is currently setting this to 1048576.

Specifically the dockerd param `--default-ulimit=nofile=102400:102400` solved it on an ubuntu based host.

**Comment by gtirloni** [comment]
Have you tried `minikube start --docker-opt` ?

```
$ minikube start --docker-opt="default-ulimit=nofile=102400:102400"
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

$ minikube ssh "ps axw | grep docker"
 2846 ?        Ssl    0:08 /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=virtualbox --insecure-registry 10.96.0.0/12 --default-ulimit=nofile=102400:102400
 2877 ?        Ssl    0:00 docker-containerd -l unix:///var/run/docker/libcontainerd/docker-containerd.sock --metrics-interval=0 --start-timeout 2m --state-dir /var/run/docker/libcontainerd/containerd --shim docker-containerd-shim --runtime docker-runc
...
```

**Comment by balboah** [comment]
@gtirloni awesome, that fixes my issue. Thanks!
I'll leave it up to someone else to decide if it's still a valid thing to set as the default :)

**Comment by lrascao** [comment]
Adding a note here for the future generations. If you're seeing ridiculous `rebar3` compile times when building Erlang docker images with `buildkit` then this is the fix you'll need. BuildKit will try and set a gigantic value for the ulimit, `erl_child_setup` will then use this as argument for initialization and take up 5m of your time for every `rebar3` command.
