### ISSUE TITLE
Update Homebrew version to .24.1

### ISSUE THREAD

**Issue by bah2830** [kubernetes/minikube#2267]
Can we get homebrew updated to the latest release (0.24.1)? Current cask version is 0.24.0

Some of us are currently using workarounds to get the docker version and DNS working again. But for anybody not aware they will be meet with a nonworking environment if installed or updated through homebrew.

**Comment by robcresswell** [comment]
https://github.com/caskroom/homebrew-cask/blob/master/Casks/minikube.rb

It looks like it already is updated? Its a cask though, so you'll need an explicit `brew cask upgrade minikube` IIRC.

**Comment by robcresswell** [comment]
I just tried installing it locally and see: 
```
$ minikube version
minikube version: v0.24.1
```

**Comment by bah2830** [comment]
Oh sorry please ignore me. I didn't `brew update` first. Closing issue

**Comment by robcresswell** [comment]
Happens to everyone. Glad it's resolved 👍
