### ISSUE TITLE
Unable to set CORS allowed origin list

### ISSUE THREAD

**Issue by astefanutti** [kubernetes/minikube#2268]
**Environment**:

**Minikube version**: v0.23.0
- **OS**: Mac OS X
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.23.6.iso

**What happened**:

When starting Minikube with the `--extra-config=apiserver.GenericServerRunOptions.CorsAllowedOriginList=.*` option, CORS requests fail with the following error message:

```
Failed to load http://minikube:30000/api/v1/namespaces: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://minikube' is therefore not allowed access. The response had HTTP status code 404. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

**What you expected to happen**:

Requests matching the allowed origin URLs should not return 404.

**How to reproduce it** (as minimally and precisely as possible):

```
minikube start --extra-config=apiserver.GenericServerRunOptions.CorsAllowedOriginList=.*
```

**Comment by owennewo** [comment]
@astefanutti The following works for me:
`minikube --extra-config apiserver.cors-allowed-origins=["http://*"] start`

I had the similar problem on minikube v0.26.1 where my angular 6 client (on http://localhost:4200) was trying to make a request to api server (through kubectl proxy i.e. http://localhost:8001/api/v1/namespaces)

After starting minikube with the above I can see the cors in the response headers:
```Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization, X-Requested-With, If-Modified-Since
Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE, PATCH
Access-Control-Allow-Origin: http://localhost:4200
Access-Control-Expose-Headers: Date```

I think you can/should /close this issue

**Comment by astefanutti** [comment]
@owennewo thanks a lot for the info! Let me close this then.
