### ISSUE TITLE
minikube start hangs on Staring local Kubernetes cluster...

### ISSUE THREAD

**Issue by davidje** [kubernetes/minikube#227]
Ubuntu 14.04 LTS 

There doesn't seem to be a way to get it to tell me why its hanging?

Tried on three separate boxes

```
$ minikube start --v=999 --logtostderr
Starting local Kubernetes cluster...
I0626 12:10:22.128266    4422 cluster.go:59] Machine exists!
I0626 12:13:26.738461    4422 cluster.go:59] Machine exists!
I0626 12:16:31.367349    4422 cluster.go:59] Machine exists!
E0626 12:19:36.055509    4422 start.go:64] Error starting host:  Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded


```

**Comment by dlorenc** [comment]
Thanks for the report, sorry to see you're having issues. Could you try passing: --show-libmachine-logs as well, and send the output?

It looks like the machine is getting created fine, but not starting. Do you have vt-x support enabled in your BIOS? Sometimes you can see what's happening if you open up the Virtualbox app, and click on the "minikubeVM" entry.

**Comment by davidje** [comment]
```
$ minikube start --v=999 --logtostderr  --show-libmachine-logs
Starting local Kubernetes cluster...
I0626 13:00:33.540944    5109 cluster.go:59] Machine exists!
(minikubeVM) VM not in restartable state
(minikubeVM) Waiting for an IP...
I0626 13:03:38.194524    5109 cluster.go:59] Machine exists!
(minikubeVM) VM not in restartable state
(minikubeVM) Waiting for an IP...
I0626 13:06:42.847510    5109 cluster.go:59] Machine exists!
(minikubeVM) VM not in restartable state
(minikubeVM) Waiting for an IP...
E0626 13:09:47.487488    5109 start.go:64] Error starting host:  Error starting stopped host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
```

**Comment by dlorenc** [comment]
Could you attach the output of this command (to verify you have vt-x enabled)?

`$ cat /proc/cpuinfo | grep 'vmx\|svm'`

**Comment by dlorenc** [comment]
Hey @davidje, were you able to get past this ever?

**Comment by dlorenc** [comment]
Hey,

I'm going to close this for now, please reopen if you can repro again!

**Comment by dkassab** [comment]
I'm having the same issue 
`dkassab@ubuntu:~$ minikube start --logtostderr --show-libmachine-logs
E0722 15:09:24.891108    3564 notify.go:54] Get https://storage.googleapis.com/minikube/releases.json: dial tcp: lookup storage.googleapis.com on 127.0.1.1:53: server misbehaving
Starting local Kubernetes cluster...
I0722 15:09:24.891267    3564 cluster.go:60] Machine exists!
I0722 15:09:24.994614    3564 cluster.go:60] Machine exists!
I0722 15:09:25.061297    3564 cluster.go:60] Machine exists!
E0722 15:09:25.116630    3564 start.go:74] Error starting host:  Error getting state for host: machine does not exist
`

**Comment by dlorenc** [comment]
It looks like your machine is having trouble connecting to GCS. Are you able to curl storage.googleapis.com ?

**Comment by dkassab** [comment]
When I do curl storage.googleapis.com, I get "MissingSecurityHeader" error and the description is "Authorization"

**Comment by davidje** [comment]
My issue was caused by a limitation in VirtualBox that does not allow running a virtual machine within a virtual machine.  KVM supports this and I was able to get this to work by changing to the KVM driver.

**Comment by btipling** [comment]
I had this problem after I created a "my-nginx" service as described in the [k8s quickstart guide](http://kubernetes.io/docs/user-guide/quick-start/). Specifically the command:

`kubectl expose deployment my-nginx --target-port=80 --type=LoadBalance`

failed and resulted in failures with regard to minikube's ip address not responding. I could no longer start or stop services with ssh not responding. I resolved the problem with `minikube delete`.

**Comment by Rev1408** [comment]
Hi,
I have the same issue and I am using KVM.
Error starting host: Error getting state for host: machine does not exist
I could do minikube delete to get it working, but is there a way to resolve this issue with out deleting the VM everytime

**Comment by r2d4** [comment]
@Rev1408 make sure you are using the latest version of the KVM driver.  start/stop was an issue in versions earlier than 0.8.2 I believe.

**Comment by Rev1408** [comment]
@r2d4 I have 0.7.0, that's what is preferred in by kubernetes docs
https://github.com/kubernetes/minikube/blob/master/DRIVERS.md#kvm-driver

**Comment by r2d4** [comment]
Sorry, thats out of date - we should update it.

**Comment by Rev1408** [comment]
ok, thanks!!

**Comment by slatunje** [comment]
I was having similar issue and can confirm that `minikube delete` and `rm -rf ~/.minikube` worked for me also, as suggested by @btipling
