### ISSUE TITLE
KVM/KVM2 driver removes existing network named "docker-machines" whether used or not

### ISSUE THREAD

**Issue by scottslowe** [kubernetes/minikube#2278]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): 0.24.1
- **OS** (e.g. from /etc/os-release): Fedora 27 Workstation Edition
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm2
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): 0.23.6
- **Install tools**:
- **Others**:

**What happened**:
I ran `minikube start --vm-driver kvm2 --kvm-network docker-machines` to connect to a pre-existing KVM/Libvirt network. The command failed (I'll open a separate issue for that), and when I ran `minikube delete` then it removed the "docker-machines" network (which was pre-existing before I ran Minikube).

For further testing, I recreated the "docker-machines" network (and made sure the "default" network was available), and ran `minikube --vm-driver kvm2`. This should have attached to the "default" network, since no other network was specified. When I ran `minikube delete`, the existing "docker-machines" network was removed, even though Minikube was not using it.

As a final test, I ran `minikube start --vm-driver kvm2 --kvm-network default` to explicitly instruct Minikube to use the "default" network. When I ran `minikube delete`, the pre-existing "docker-machines" network was removed, even though Minikube was not using it.

**What you expected to happen**:
I expected Minikube to leave the pre-existing KVM/Libvirt network in place, especially when Minikube was not using that network.

**How to reproduce it** (as minimally and precisely as possible):
1. Ensure an existing KVM/Libvirt network exists (use `virsh net-create` or similar to create).
2. Run `minikube start --vm-driver kvm2 --kvm-network <name of pre-existing network>`.
3. Run `minikube delete` to remove the Kubernetes cluster. Any pre-existing networks named "docker-machines" will be removed.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
I understand that Minikube re-uses some aspects of Docker Machine under the covers, but this behavior is counter-intuitive. Docker Machine itself does not remove networks when machines are removed. I can _sort of_ understand the "docker-machines" network getting removed by Minikube when Minikube is instructed to use that network, but having Minikube remove that network even when it is not using it is counter-intuitive and unexpected.

**Comment by r2d4** [comment]
Minikube does reuse that network and deletes it upon a minikube delete.  If this matters for you, you can always specify the network with --kvm-network flag and it will create a new one and leave the docker-machine network alone.  

What is your use case for running docker-machine and minikube on linux?

**Comment by lowescott** [comment]
@r2d4 One of the things I noted is that even when you do specify a network using `--kvm-network`, the "docker-machines" network still gets deleted (see the notes under "What happened" above). Given Minikube's reliance on pieces/components from Docker Machine I can understand if there isn't a workaround; at the very least, though, it should be documented so that users understand the ramifications. It should also be documented that using `--kvm-network` does _not_ (apparently, based on my testing) remove the reliance/dependence on the "docker-machines" network.

As for a use case, I can fully see times when I may need to use one or the other of the two tools for testing, although probably not at the same time (one potential use for Docker Machine on Linux is to test different versions of the Docker Engine, for example).

**Comment by r2d4** [comment]
Fair enough, its definitely possible that the kvm2 driver doesn't yet respect the kvm-network flag.  We should do two things here - create a new libvirt network, and respect the kvm-network flag.

**Comment by dlorenc** [comment]
Took a quick look - there are two issues I think.

There are two actual networks in play - the private network and the "kvm network". The private network is hardcoded to be "docker-machines", the other one is called "default".

The kvm2 driver should already support the --kvm-network flag, but that's not the PrivateNetwork, which is hardcoded. I'll swap that to be "minikube-net", which it looks like we meant to do already.

**Comment by lowescott** [comment]
@dlorenc That sounds ideal, thanks.

**Comment by scottslowe** [comment]
Looks like the fix for this issue was merged in #2305, closing this issue.
