### ISSUE TITLE
configmap values created --from-file aren't set in shell (eg. echo $MY_VAR returns blank) but do appear when I run the env command

### ISSUE THREAD

**Issue by bw2** [kubernetes/minikube#2295]
BUG REPORT

**Environment**:

- **Minikube version** (use `minikube version`): minikube version: v0.23.0
- **OS** (e.g. from /etc/os-release):   Darwin 16.7.0
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.6.iso

**What happened**:

I'm running 

```
kubectl create configmap all-settings --from-file=all-settings.properties
```
where all-settings.properties looks like:
```
CLUSTER_NAME=minikube
CLOUD_PROVIDER=local
..
```

Then in my config I have:
```
kind: Deployment
apiVersion: extensions/v1beta1
..
      containers:
      - name: my-container
        envFrom:
          - configMapRef:
              name: all-settings
```
This deploys a Docker image that starts with

`FROM debian:jessie`

When I deploy to minikube and open a bash shell inside the pod, I can run `env` and see the keys/values as expected:

 ```
CLUSTER_NAME=minikube
CLOUD_PROVIDER=local
..
```

but if I echo any of these vars  (eg. `echo $CLUSTER_NAME`) or use them in my scripts, the variable doesn't appear to be set - it returns blank. 
I can, though, echo vars that are set by kubernetes (such as *_PORT or *_HOST) and also vars that are set one-by-one in the deployment config `env:` section - for example

```
        env:
        - name: CLUSTER_NAME
          value: "{{ CLUSTER_NAME }}"
```

If I run /bin/sh, I still see the same thing - the vars are listed in `env` but I can't echo them or use them in my script.

**What you expected to happen**:

since I'm seeing the values when I run `env`, I expected to be able to use them on the command line and in my scripts, but the vars don't appear to exist outside of `env`.

**Comment by mattnworb** [comment]
> When I deploy to minikube and open a bash shell inside the pod

For completeness, what command are you running to open the shell?

**Comment by bw2** [comment]
I'm running

kubectl exec -it $POD_NAME -- /bin/bash

**Comment by r2d4** [comment]
Does this work on a GKE or cluster other than minikube?  It doesn't seem specific to minikube

**Comment by bw2** [comment]
I'm not sure..

**Comment by mattnworb** [comment]
Here is what I get on minikube v0.23.0, VirtualBox, minikube-v0.23.6.iso, OS X 10.12.6:

```
$ cat /tmp/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  containers:
  - name: shell
    image: ubuntu
    args:
    - sh
    - -c
    - "while true; echo $FOOBAR; do sleep 5; done"
    env:
    - name: FOOBAR
      value: blah

$ kubectl apply -f /tmp/pod.yaml
pod "shell" created

$ kubectl get pods
NAME      READY     STATUS    RESTARTS   AGE
shell     1/1       Running   0          10s

$ kubectl logs pod/shell
blah
blah
blah
blah

$> kubectl exec -it shell bash
root@shell:/# echo $FOOBAR
blah
root@shell:/# env | grep FOOBAR
FOOBAR=blah
root@shell:/# exit
```

**Comment by mattnworb** [comment]
d'oh, I read your description of the initial problem wrong, sorry about that, I tested something different.

**Comment by mattnworb** [comment]
I get the same behavior in minikube and on GKE:

```
$ cat /tmp/settings.properties
CLUSTER_NAME=minikube
FOO=BAR

$ kubectl create configmap settings --from-file=/tmp/settings.properties
configmap "settings" created

$ kubectl get configmap settings
NAME       DATA      AGE
settings   1         1s

$ kubectl get configmap settings -o yaml
apiVersion: v1
data:
  settings.properties: |
    CLUSTER_NAME=minikube
    FOO=BAR
kind: ConfigMap
metadata:
  creationTimestamp: 2017-12-14T20:01:23Z
  name: settings
  namespace: default
  resourceVersion: "12604"
  selfLink: /api/v1/namespaces/default/configmaps/settings
  uid: 8f683ceb-e109-11e7-8cb6-08002710bdeb

# now using envFrom:
$ cat /tmp/pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: shell
spec:
  containers:
  - name: shell
    image: ubuntu
    args:
    - sh
    - -c
    - "while true; echo foo is $FOO; do sleep 5; done"
    envFrom:
    - configMapRef:
        name: settings

$ kubectl create -f /tmp/pod.yaml
Using cluster testing-us-central1
pod "shell" created
mattbrown/kubernetes u+2!tsunami * $> CLUSTER_GROUP=testing REGION=us-central1 gke-
$ kubectl logs pod/shell
foo is
foo is

$ kubectl exec -it shell bash
root@shell:/# env | grep CLUSTER
settings.properties=CLUSTER_NAME=minikube
root@shell:/# env | grep FOO
FOO=BAR
root@shell:/# exit
exit
```

Note that the first entry in the file has been turned into an environment variable where the name of one of the keys in the configmap is present:

```
root@shell:/# env | grep CLUSTER
settings.properties=CLUSTER_NAME=minikube
```

This might have more to do with how `envFrom` behaves when the config map has a structure like it does in this example.

**Comment by AmazingTurtle** [comment]
Experiencing the same issue on GKE according to
https://edenmal.moe/2017/08/31/GitLab-Kubernetes-Running-CI-Runners-in-Kubernetes/

I did `set -ex; env` and variables are there according to logs. But from inside the script I'm unable to resolve these like ${GITLAB_CI_TOKEN}

**Comment by avoidik** [comment]
@AmazingTurtle I think in your case the problem is how `run.sh` script gets executed, what if you try to replace `#!/bin/bash` with `#!/usr/bin/env bash`?

Another thing to try is to replace
```
        command:
        - /scripts/run.sh
```
with:
```
        command: ["/bin/bash"]
        args: ["/scripts/run.sh"]
```

**Comment by bw2** [comment]
I don't think this has been fixed yet. I'm still seeing it in

**Minikube version** (use `minikube version`): v0.28.1
- **OS** (e.g. from /etc/os-release): MacOS 10.12.6 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): .minikube/cache/iso/minikube-v0.28.1.iso

**Comment by bw2** [comment]
The issue appears as if vars set in the env section
```
  env:
        - name: CLUSTER_NAME
          value: "{{ CLUSTER_NAME }}"
```
 behave like they were "exported" and so can be accessed from python scripts, etc. (eg.
but vars set with envFrom:
```
envFrom:
  - configMapRef:
        name: all-settings
```
behave like env vars that weren't exported, and so can be seen by running `env` in a shell, but can't be accessed within scripts. Also for some reason they're not accessible within entrypoint.sh

**Comment by sandyfox** [comment]
/remove-lifecycle stale

I still see the issue

**Comment by ObviousDWest** [comment]
> The issue appears as if vars set in the env section
> 
> ```
>   env:
>         - name: CLUSTER_NAME
>           value: "{{ CLUSTER_NAME }}"
> ```
> 
> behave like they were "exported" and so can be accessed from python scripts, etc.
> but vars set with envFrom:
> 
> ```
> envFrom:
>   - configMapRef:
>         name: all-settings
> ```
> 
> weren't exported. The envFrom vars show up if you run `env` in a shell, but their values can't be accessed within scripts. Also for some reason they're not accessible from within entrypoint.sh when the docker image/pod is starting up.

This is screwing me up as well. Data from an envFrom configMap shows up in the container as a local environment variable, not an *exported* environment variable. Those values, then, cannot be used in child processes. What is the reasoning for this? Is there a flag, or option to make envFrom create exported variables instead?

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ObviousDWest** [comment]
Ok. This probably needs more explanation. Environment variables are supposed to be exported and thus inherited by child processes. Local shell variables that have not been exported are *not* environment variables. So what am I seeing that make me claim configMap is not "exporting"?

In a deployment which uses envFrom, I can do one or the other these commands:
1)          command: [ "sh", "-c", "printenv"] # Does not print configMap as env vars.
2)          command: [ "printenv" ] # prints configMap contents as env vars

The only difference I see in 1) is that a child process is printing the variables. When I exec into either pod, I see the variables (which are, perhaps applied during the exec). So how are things getting "lost" in 1)? 

(This is a super-simple example. My real code spawns java and uses spring boot to read application.properties with environment variables overriding, and container variables substituted on the commandline, like jmx port)

**Comment by ObviousDWest** [comment]
Ok. I worked out *my* issue. Turns out that "sh" strips out envVars that contain dots (used for spring boot's application.properties). I switched to "bash", and things are working as expected; variables are passed on to the child processes.
