### ISSUE TITLE
Minikube stops responding after a few minutes

### ISSUE THREAD

**Issue by kwaazaar** [kubernetes/minikube#2298]
**Environment**:
Windows 10 - 1709, using HyperV
**Minikube version** (use `minikube version`):
Minikube 0.23.0

- **OS** (e.g. from /etc/os-release):
Not a clue how to SSH into minikube

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
HyperV

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
0.23.6 iso

- **Install tools**:
?

**What happened**:
After succesfully starting minikube and deploying my solution using kubectl (all without problems), suddenly I cannot connect anymore.

**What you expected to happen**:
Kubectl returns errors:
C:\data\src\kubedemo\src [master ≡ +0 ~1 -0 !]> kubectl get pods
Unable to connect to the server: dial tcp 192.168.1.62:8443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has
failed to respond.

**How to reproduce it** (as minimally and precisely as possible):
Not sure, but if my solution is the cause, you can find it here: https://github.com/kwaazaar/kubedemo
I deploy it using kubectl create -f src\votingapi.deploy.yml

**Output of `minikube logs` (if applicable)**:
No entries (so I have no clue what the cause is).

**Anything else do we need to know**:
No.

**Comment by kwaazaar** [comment]
The logs while minikube is still working:
[minikube.log](https://github.com/kubernetes/minikube/files/1548493/minikube.log)

**Comment by r2d4** [comment]
Can you provide some logs after its failed?  You should still be able to run `minikube logs`

**Comment by kwaazaar** [comment]
After it stops working, minikube logs simply reports "no entries".

**Comment by RaymondArias** [comment]
Do you have Dynamic Memory Enabled on your Minikube Hyper-V VM?
I had the same issue but after I disabled Dynamic Memory I have not had that problem

https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperv-driver

![dynamic memory](https://user-images.githubusercontent.com/15129320/34425041-523e42fc-ebdd-11e7-9e33-c6e54c14c21c.PNG)

**Comment by kwaazaar** [comment]
@RaymondArias Thanks, that did the job! With Dynamic Memory disabled it keeps running like it should!
