### ISSUE TITLE
Unable to mount with kvm2 driver

### ISSUE THREAD

**Issue by blazed** [kubernetes/minikube#2303]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):  v0.24.1
- **OS** (e.g. from /etc/os-release): Arch Linux
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm2
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.23.6
- **Install tools**:
- **Others**:

**What happened**:
When trying to use `minikube mount` the following error occurs
`Error getting the host IP address to use from within the VM:  Error, attempted to get host ip address for unsupported driver`

**What you expected to happen**:
Host map to be mounted in VM

**How to reproduce it** (as minimally and precisely as possible):
Bootstrap with kvm2 driver and try to mount.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
I suppose it's the same error as https://github.com/kubernetes/minikube/pull/2270 but for the kvm2 driver.

**Comment by r2d4** [comment]
Yes this is a bug, and we need an entry for the kvm2 driver and network in that switch statement.
