### ISSUE TITLE
Enable sharing via NFS for the hyperkit driver

### ISSUE THREAD

**Issue by mo-hit** [kubernetes/minikube#2310]
It would be great to support sharing via NFS with the hyperkit driver. Was previously using a fork of minikube by betabrand for the nfs sharing support with the xhyve driver (https://github.com/betabrand/minikube/tree/betabrand-minikubev0.24.0-nfs-virtio). After upgrading to use the hyperkit driver and latest kubernetes we are needing the nfs sharing support to use minikube as our local development environment. Since the hyperkit driver is built inside of the minikube project (and we don't have to rely on https://github.com/zchee/docker-machine-driver-xhyve, I have written a small change that ports the changes to the minikube project. 
First time contributer / noob go programmer here so any tips would be helpful. I noticed a small change to the viper driver that was in head that kinda broke my change, any advice around that would be amazing. Also any advice you can give around code organization in the driver package would be awesome. 
PR is here: 
https://github.com/kubernetes/minikube/pull/2309

**Comment by r2d4** [comment]
ref #2309
