### ISSUE TITLE
Support credentials in cache command

### ISSUE THREAD

**Issue by natevecc** [kubernetes/minikube#2319]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug Report

Please provide the following details:

**Environment**: Mac

**Minikube version**: v0.24.1
- **OS**: OSX 10.11.6
- **VM Driver**: hyperkit
- **ISO version**: v0.23.6
- **Install tools**:
- **Others**:

**What happened**: tried to cache an image from docker hub that requires creds to access
`minikube cache add [companyName]/[image]:latest`
```
Error caching and loading images: caching images: caching image /Users/natevecc/.minikube/cache/images/[companyName]/[image]_latest: copying image: Error initializing image from source docker://[companyName]/[image]:latest: errors:
denied: requested access to the resource is denied
unauthorized: authentication required
```

**What you expected to happen**: to pull the image and cache it as it does for images without authorization

**How to reproduce it**: create a private image on docker hub and try and cache it using `minikube cache add`. It should throw an auth error.

**Comment by r2d4** [comment]
I think we need to update the version of containers/image that we are vendoring.  We fixed this issue upstream for a different project.

**Comment by prat0318** [comment]
Any updates on this? My use-case is pulling image from aws ECR registry

**Comment by ehbello** [comment]
Hello, does anyone know if there is any workaround for this issue?

**Comment by dlorenc** [comment]
> Hello, does anyone know if there is any workaround for this issue?

We've changed the library used to cache docker images in minikube to this one: https://github.com/google/go-containerregistry. I believe this should now be supported, provided you configure the correct docker credential helper for your private images.

**Comment by dlorenc** [comment]
What version of minikube are you seeing this in?

**Comment by ehbello** [comment]
I use the latest version of minikube, currently v0.28.

I realize that I get a different error message so it couldn't be related to this issue.

`$ minikube cache add [companyName]/[imageName]:[tagName]
Error caching and loading images: caching images: caching image /home/ehbello/.minikube/cache/images/[companyName]/[imageName]_[tagName]: copying image: Error initializing image from source docker://[companyName]/[imageName]:[tagName]: pinging docker registry returned: error pinging repository, response code 404`

Note that a docker pull of that reference works flawlessly.

However, I only get this error against my private repository powered by Nexus. If you consider it, I will open a new issue after debugging my problem better.

**Comment by dlorenc** [comment]
Ah yeah, it could be an issue with Nexus not working correctly with the library we're using.

**Comment by Dbzman** [comment]
I don't think it's Nexus specific. We see the same error on v0.28 now and we use Artifactory as a private Docker registry.

**Comment by ehbello** [comment]
A valid workaround could be this script:
```
#!/bin/sh
set -eu
  
ref=${1?"Usage: $0 <image_ref>"}
target="${HOME}/.minikube/cache/images/${ref/:/_}"
  
mkdir -p $(dirname ${target})
docker pull ${ref}
docker save ${ref} -o ${target}
```
