### ISSUE TITLE
deb package should (at most) Recommend: virtualbox, not Depend on it

### ISSUE THREAD

**Issue by tv42** [kubernetes/minikube#2321]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): bug report

Please provide the following details:

**Minikube version** (use `minikube version`): v0.24.1
- **OS** (e.g. from /etc/os-release): Ubuntu 17.10

**What happened**:

`sudo dpkg -i minikube*.deb` refused to install because I don't have `virtualbox` installed.

**What you expected to happen**:

That it let me use the `kvm2` driver.

**Anything else do we need to know**:

If you want to keep a Depends:, and all the possible drivers are packaged in Debian/Ubuntu, you could use a `Depends: virtualbox | foo | bar` to let the user decide which one to use.

**Comment by r2d4** [comment]
I agree - the template which we build the deb package is here
https://github.com/kubernetes/minikube/blob/master/installers/linux/deb/minikube_deb_template/DEBIAN/control

PRs gladly accepted.
