### ISSUE TITLE
EFK addon not working on windows

### ISSUE THREAD

**Issue by AceHack** [kubernetes/minikube#2330]
minikube version: v0.24.1
Windows 10 1709 Build 16299.125
Hyper-V
minikube-v0.23.6.iso

**What happened**:
elasticsearch-logging failed to start

Back-off restarting failed container 
Error syncing pod 

**What you expected to happen**:
expected all efk services to be healthy

**How to reproduce it** (as minimally and precisely as possible):
minikube start --vm-driver=hyperv --hyperv-virtual-switch=Wireless
minikube addons open efk
minikube stop
minikube start --vm-driver=hyperv --hyperv-virtual-switch=Wireless

**Output of `minikube logs` (if applicable)**:
+ export NODE_NAME=elasticsearch-logging-chcmx 
+ NODE_NAME=elasticsearch-logging-chcmx 
+ export NODE_MASTER=true 
+ NODE_MASTER=true 
+ export NODE_DATA=true 
+ NODE_DATA=true 
+ export HTTP_PORT=9200 
+ HTTP_PORT=9200 
+ export TRANSPORT_PORT=9300 
+ TRANSPORT_PORT=9300 
+ export MINIMUM_MASTER_NODES=1 
+ MINIMUM_MASTER_NODES=1 
+ chown -R elasticsearch:elasticsearch /data 
+ ./bin/elasticsearch_logging_discovery 
+ exec su elasticsearch -c ./bin/es-docker 
Killed

**Comment by AceHack** [comment]
Tried to disable and got

minikube addons disable efk
[error disabling addon deploy/addons/efk/elasticsearch-rc.yaml: %!s(MISSING): Process exited with status 1]

**Comment by kairen** [comment]
@AceHack The EFK needs to use more RAM in your environment, you can increase RAM as the following command:
```sh
$ minikube version
minikube version: v0.24.1

$ minikube start --memory 4096
$ minikube addons enable efk
$ kubectl get po,svc -n kube-system
NAME                             READY     STATUS    RESTARTS   AGE
po/elasticsearch-logging-n85mj   1/1       Running   0          3m
po/fluentd-es-p8rnc              1/1       Running   0          3m
po/kibana-logging-48l4n          1/1       Running   0          3m
po/kube-addon-manager-minikube   1/1       Running   0          19m
po/kube-dns-86f6f55dd5-2rtn2     3/3       Running   0          18m
po/kubernetes-dashboard-9wttf    1/1       Running   1          18m
po/storage-provisioner           1/1       Running   0          19m

NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
svc/elasticsearch-logging   ClusterIP   10.108.172.241   <none>        9200/TCP         3m
svc/kibana-logging          NodePort    10.103.132.51    <none>        5601:30003/TCP   3m
svc/kube-dns                ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP    18m
svc/kubernetes-dashboard    NodePort    10.106.189.21    <none>        80:30000/TCP     18m

# Take a few minutes because Kibana and Elasticsearch initing
$ minikube addons open efk
```

![Imgur](https://i.imgur.com/ENgi6xM.png)

**Comment by AceHack** [comment]
I tried this and elastic search now starts but never fully comes up and keep restarting.

**Comment by AceHack** [comment]
+ export NODE_NAME=elasticsearch-logging-4qd2k 
+ NODE_NAME=elasticsearch-logging-4qd2k 
+ export NODE_MASTER=true 
+ NODE_MASTER=true 
+ export NODE_DATA=true 
+ NODE_DATA=true 
+ export HTTP_PORT=9200 
+ HTTP_PORT=9200 
+ export TRANSPORT_PORT=9300 
+ TRANSPORT_PORT=9300 
+ export MINIMUM_MASTER_NODES=1 
+ MINIMUM_MASTER_NODES=1 
+ chown -R elasticsearch:elasticsearch /data 
+ ./bin/elasticsearch_logging_discovery 
+ exec su elasticsearch -c ./bin/es-docker 
Killed

**Comment by AceHack** [comment]
It made it a much longer way after a reboot but still crashes.

https://gist.github.com/AceHack/69995678b0c66ff70f7ed45110b31c98

**Comment by Tkanos** [comment]
Its not only windows that are impacted, I have the same issue on a Mac.

**Comment by razic** [comment]
did anyone ever figure this out? i started my minikube with 4gb but elasticsearch is contstantly dying
