### ISSUE TITLE
Can't run minikube on CoreOS, because /usr/local/bin/ is read-only file system

### ISSUE THREAD

**Issue by khs1994** [kubernetes/minikube#2348]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.24.1
- **OS** (e.g. from /etc/os-release): CoreOS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:

```bash
Moving files into cluster...
E1221 11:51:22.138748    4849 start.go:223] Error updating cluster:  error creating file at /usr/local/bin/localkube: open /usr/local/bin/localkube: read-only file system
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by khs1994** [comment]
Must mv `localkube` to `/opt/bin`

**Comment by sjayaram0212** [comment]
I am facing the same issue.   Is there a way we can change the location of localkube from /usr/local/bin to something else ?

minikube start --vm-driver none
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Password:
Getting VM IP address...
Moving files into cluster...
E0103 04:33:30.225163   59853 start.go:223] Error updating cluster:  error creating file at /usr/local/bin/localkube: open /usr/local/bin/localkube: read-only file system

**Comment by ramaganapa** [comment]
I am facing this issue. And wondering on providing a PR on below lines.

Introduced a new environment variable "LOCALKUBE_BASE_DIR". Which if set will be used instead or "/usr/local/bin" to set localkube.

I am not sure if using env variable is the right way for such overrides. But, minikube seems to be using a fair amount of env variables for such things (eg: MINIKUBE_HOME, CHANGE_MINIKUBE_NONE_USER etc). So thought of going ahead with it.

I have the fixes and tested it locally. Wanted to get feedback on the approach before creating a pull request.

**Comment by prat0318** [comment]
I am also facing the same issue:
```
E0308 04:58:44.256675   24255 start.go:158] Error updating cluster:  error creating file at /usr/local/bin/localkube: open /usr/local/bin/localkube: permission denied
```

**Comment by voor** [comment]
Is there a reason that minikube essentially *installs* localkube, instead of just letting us install localkube?  It's not just the localkube executable, it also creates a systemd unit file, right?

**Comment by mfilotto** [comment]
Any update on this one ?

**Comment by SeanSingh** [comment]
This is still an issue and it appears the fix was never merged.
This would still be useful:
Introduce a new environment variable "LOCALKUBE_BASE_DIR". Which if set will be used instead or "/usr/local/bin" to set localkube.
/remove-lifecycle rotten
