### ISSUE TITLE
--apiserver-name should change apiserver name, not CA name

### ISSUE THREAD

**Issue by alahijani** [kubernetes/minikube#2361]
**BUG REPORT**

Please provide the following details:

**Environment**:

**OS**: Ubuntu 16.04.3 LTS

**VM driver**: virtualbox

**ISO version**: minikube-v0.23.6.iso, also tried minikube-v0.24.0.iso

**What happened**:

Command line parameter `--apiserver-name` is advertised as useful "if you want to make the apiserver available from outside the machine". For that to work, you would expect it to change the subject name of `apiserver.crt`. But in practice it changes the issuer/CA name which is not very useful for making the apiserver accessible outside the machine.

Also I can't think of a common scenario where changing the CA name would be desired.

```
$ minikube start --apiserver-name=minikube.example.com
...

$ openssl x509 -noout -issuer -subject -in ~/.minikube/ca.crt
issuer= /CN=minikube.example.com
subject= /CN=minikube.example.com

$ openssl x509 -noout -issuer -subject -in ~/.minikube/apiserver.crt
issuer= /CN=minikube.example.com
subject= /O=system:masters/CN=minikube

$ openssl x509 -noout -issuer -subject -in ~/.minikube/client.crt
issuer= /CN=minikube.example.com
subject= /O=system:masters/CN=minikube-user
```

**What you expected to happen**:

```
$ openssl x509 -noout -issuer -subject -in ~/.minikube/ca.crt
issuer= /CN=minikubeCA
subject= /CN=minikubeCA

$ openssl x509 -noout -issuer -subject -in ~/.minikube/apiserver.crt
issuer= /CN=minikubeCA
subject= /O=system:masters/CN=minikube.example.com

$ openssl x509 -noout -issuer -subject -in ~/.minikube/client.crt
issuer= /CN=minikubeCA
subject= /O=system:masters/CN=minikube-user
```
**How to reproduce it** (as minimally and precisely as possible):

```
$ minikube start --apiserver-name=minikube.example.com
$ IPAddress=$(cat ~/.minikube/machines/minikube/config.json | grep '"IPAddress":' | grep -o '[0-9\.]*')
$ curl https://minikube.example.com:8443 --cacert ~/.minikube/ca.crt --resolve minikube.example.com:8443:$IPAddress
curl: (51) SSL: certificate subject name (minikube) does not match target host name 'minikube.example.com'
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by greglanthier** [comment]
This sounds at least tangentially related issue #1974.

Minikube may not support providing additional SANs for the apiserver certificates.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lichen2013** [comment]
I tested with my patch, the cert is updated as expected.

`openssl x509 -noout -issuer -subject -in .minikube/apiserver.crt`

> issuer= /CN=minikubeCA
> subject= /O=system:masters/CN=devops1.fyre.ibm.com


But when I try to reach my cluster with the apiserver-name I give, still get the same error. 

Error message from kubectl:

> Unable to connect to the server: x509: certificate is valid for kubernetes.default.svc.cluster.local, kubernetes.default.svc, kubernetes.default, kubernetes, localhost, not devops1.fyre.ibm.com


The log shows:

> Jan 08 22:33:37 devops1.fyre.ibm.com localkube[9506]: http: TLS handshake error from 9.111.44.219:61689: remote error: tls: bad certificate

**Comment by lichen2013** [comment]
@greglanthier  I think SANs are supported.
For example, this is part of the output of my apiserver.crt

`openssl x509 -in apiserver.crt -text -noout`


```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 2 (0x2)
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=minikubeCA
        Validity
            Not Before: Jan  9 07:42:34 2018 GMT
            Not After : Jan  9 07:42:34 2019 GMT
        Subject: O=system:masters, CN=devops1.fyre.ibm.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    ...
                Exponent: 65537 (0x10001)
        X509v3 extensions:
            X509v3 Key Usage: critical
                Digital Signature, Key Encipherment
            X509v3 Extended Key Usage:
                TLS Web Server Authentication, TLS Web Client Authentication
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Subject Alternative Name:
                DNS:kubernetes.default.svc.cluster.local, DNS:kubernetes.default.svc, DNS:kubernetes.default, DNS:kubernetes, DNS:localhost, IP Address:9.30.230.59, IP Address:10.96.0.1, IP Address:10.0.0.1
    Signature Algorithm: sha256WithRSAEncryption
         ...


```

**Comment by haizaar** [comment]
> But when I try to reach my cluster with the apiserver-name I give, still get the same error.

@lichen2013, I guess that's because modern browsers [deprecated](https://textslashplain.com/2017/03/10/chrome-deprecates-subject-cn-matching/) usage of `Subject CN` matching and only check Subject Alternative Names.


I'd personally love to see `--apiserver-name=` argument adding its value to Subject Alternative Name field of the apiserver.crt.

It will be also great to be able to specify this argument several times to allow adding multiple names.

**Comment by lichen2013** [comment]
@haizaar Thanks for the info.
I have updated my PR, and tests with
```
./minikube start --apiserver-name=devops1.fyre.ibm.com --vm-driver=none --apiserver-names=www.1111.com --apiserver-names=www.2222.com --apiserver-names=www.3333.com --apiserver-names=www.444.com --apiserver-ips=192.168.10.1 --apiserver-ips=192.168.10.2 --apiserver-ips=192.168.10.3
```

The SANs part of cert is updated as expected.
