### ISSUE TITLE
registry addon: persistent data

### ISSUE THREAD

**Issue by quantonganh** [kubernetes/minikube#2365]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

Please provide the following details:

**Environment**:

**Minikube version**: 0.24.1
- **OS**: Mac OS X 10.13.1 
- **VM Driver**: virtualbox
- **ISO version**: 0.23.6
- **Install tools**:
- **Others**:

**What happened**:
- enable registry addon
- push an image
- restart minikube
- pull that image again:
```
❯❯❯❯ docker pull docker.for.mac.localhost:5000/grpc-k8s-api
Using default tag: latest
Error response from daemon: manifest for docker.for.mac.localhost:5000/grpc-k8s-api:latest not found
```
Logs:
>time="2017-12-28T02:33:40Z" level=error msg="response completed with error" err.code="manifest unknown" err.detail="unknown tag=latest" err.message="manifest unknown" go.version=go1.7.3 http.request.host="localhost:5000" http.request.id=a05897f8-5735-41af-af58-3724b5afb978 http.request.method=GET http.request.remoteaddr=172.17.0.1 http.request.uri="/v2/grpc-k8s-api/manifests/latest" http.request.useragent="docker/17.06.0-ce go/go1.8.3 git-commit/02c1d87 kernel/4.9.13 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)" http.response.contenttype="application/json; charset=utf-8" http.response.duration=1.599365ms http.response.status=404 http.response.written=96 instance.id=6854d9ad-16f6-49f4-b192-b8dd570926fc vars.name=grpc-k8s-api vars.reference=latest version=v2.6.1
172.17.0.5 - - [28/Dec/2017:02:33:40 +0000] "GET /v2/grpc-k8s-api/manifests/latest HTTP/1.0" 404 96 "" "docker/17.06.0-ce go/go1.8.3 git-commit/02c1d87 kernel/4.9.13 os/linux arch/amd64 UpstreamClient(Go-http-client/1.1)"

**What you expected to happen**:
The registry data should be persistent between restart.

**How to reproduce it** (as minimally and precisely as possible):
- enable `registry` addon:
```
❯❯❯❯ minikube addons enable registry
registry was successfully enabled
```
- expose it by creating a DaemonSet: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry
```
❯❯❯❯ kubectl create -f kube-registry-proxy.yml
daemonset "kube-registry-proxy" created
```
- add `docker.for.mac.localhost:5000` into insecure registried list in Docker Preferences
- append `docker.for.mac.localhost` to the first line of `/etc/hosts` in minikube VM:
```
$ cat /etc/hosts
127.0.0.1	localhost	docker.for.mac.localhost
127.0.1.1	minikube
```
- forward port:
```
❯❯❯❯ kubectl port-forward --namespace kube-system registry-kpjmj 5000:5000
```
- push an image:
```
docker push docker.for.mac.localhost:5000/grpc-k8s-api
```
- restart minikube:
```
minikube stop
minikube start
```
- pull that image:
```
❯❯❯❯ docker pull docker.for.mac.localhost:5000/grpc-k8s-api
Using default tag: latest
Error response from daemon: manifest for docker.for.mac.localhost:5000/grpc-k8s-api:latest not found
```
**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

The reason is:

```
  {
    "Type": "volume",
    "Name": "242c156d62067978ac727ca13ff06421eac4a479ecae362796d9c6e52fe3eb34",
    "Source": "/var/lib/docker/volumes/242c156d62067978ac727ca13ff06421eac4a479ecae362796d9c6e52fe3eb34/_data",
    "Destination": "/var/lib/registry",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
```

After restaring, registry container will be recreated as another name, and the volume will be mounted from a different source:

```
  {
    "Type": "volume",
    "Name": "61cfe13b5d880931d6e05329b7df4d2603be106af13cc1504d1cd4d3064bed3d",
    "Source": "/var/lib/docker/volumes/61cfe13b5d880931d6e05329b7df4d2603be106af13cc1504d1cd4d3064bed3d/_data",
    "Destination": "/var/lib/registry",
    "Driver": "local",
    "Mode": "",
    "RW": true,
    "Propagation": ""
  },
```

As a workaround, I have to disable registry addon, then create ReplicationController, Service manually, and use `hostPath` to keep data to be persistent:

```
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        ports:
      volumes:
      - name: image-store
        hostPath:
          path: /data/registry/
```

https://blog.hasura.io/sharing-a-local-registry-for-minikube-37c7240d0615

**Comment by joelhandwell** [comment]
this can be improved by providing out-of the box local registry which can be pointed via localhost:5000 or something.

**Comment by philippeboyd** [comment]
How has this not been addressed? What's the point of having a Registry if data is not persisted throughout Minikube restarts?

**Comment by fredex42** [comment]
I came across this issue as I, too, was surprised that I lost the images following a restart of minikube.  My temporary solution was to set up a PVC to store the data and patch the replicationcontroller to use it. I've been able to pull an image successfully after restarting the registry pod:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    name: registry-persistence
    stack: containerised-platform
    stage: KUBE
  name: registry-data
  namespace: kube-system
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
```

With this PVC applied, I ran:

```bash
kubectl -n kube-system patch replicationcontrollers registry --type json -p '[{"op": "add","path":"/spec/template/spec/volumes", "value": [{"name": "registry-data", "persistentVolumeClaim": {"claimName": "registry-data"}}]}, {"op": "add", "path":"/spec/template/spec/containers/0/volumeMounts","value":[{"mountPath": "/var/lib/registry", "name": "registry-data"}]}]'
```

to patch the container to use it.

Posting in case anyone else finds it helpful
