### ISSUE TITLE
Set vm.max_map_count from 'minikube start'

### ISSUE THREAD

**Issue by antel0pe** [kubernetes/minikube#2367]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST  
  - I'd like to have the ability to set vm.max_map_count when running `minikube start`  
    Example: `minikube start --max-map-count 262144`

Elasticsearch requires that the vm.max_map_count be set to at least 262144, and right now, per [this](https://github.com/kubernetes/minikube/issues/1306) issue, the only way to do this is to start Minikube, run this command:  
```
minikube ssh 'echo "sysctl -w vm.max_map_count=262144" | sudo tee -a /var/lib/boot2docker/bootlocal.sh'
```
and then restart Minikube.  

It would be very nice to just be able to set this at `minikube start`.

**Comment by jeffgreenca** [comment]
@antel0pe I see you closed this but I'm not clear on the resolution here... can you clarify as I am encountering the same issue

**Comment by blinktag** [comment]
I had this same issue, when trying to get elasticsearch running in minikube, and was able to solve it using _initContainers_ in my k8s deployment definition like here: https://github.com/giantswarm/kubernetes-elastic-stack/blob/28e517da737065bbb700a963f64ea3e7838b2aed/manifests-all.yaml#L114

**Comment by bluelurker** [comment]
> I had this same issue, when trying to get elasticsearch running in minikube, and was able to solve it using _initContainers_ in my k8s deployment definition like here: https://github.com/giantswarm/kubernetes-elastic-stack/blob/28e517da737065bbb700a963f64ea3e7838b2aed/manifests-all.yaml#L114

That's interesting. But is this 


> I had this same issue, when trying to get elasticsearch running in minikube, and was able to solve it using _initContainers_ in my k8s deployment definition like here: https://github.com/giantswarm/kubernetes-elastic-stack/blob/28e517da737065bbb700a963f64ea3e7838b2aed/manifests-all.yaml#L114

That's clever!

**Comment by bluelurker** [comment]
> I had this same issue, when trying to get elasticsearch running in minikube, and was able to solve it using _initContainers_ in my k8s deployment definition like here: https://github.com/giantswarm/kubernetes-elastic-stack/blob/28e517da737065bbb700a963f64ea3e7838b2aed/manifests-all.yaml#L114

That's clever!
