### ISSUE TITLE
Persistent cluster support

### ISSUE THREAD

**Issue by yissachar** [kubernetes/minikube#237]
According to the README:

> The minikube stop command can be used to stop your cluster. This command shuts down the minikube virtual machine, but preserves all cluster state and data. Starting the cluster again will restore it to it's previous state.

In practice this doesn't seem to be the case:

1. `minikube start`
2. Create some Kubernetes resources 
3. Resources show up in `kubectl` and in Dashboard UI
4. `minikube stop`
5. `minikube start`
6. None of the previously created resources exist

I'm on OS X and using Minikube 0.4

**Comment by dlorenc** [comment]
Thanks for the report. It looks like the /var/lib/localkube/etcd directory is getting wiped out during the restart.
