### ISSUE TITLE
Describe and document profile usage

### ISSUE THREAD

**Issue by timoreimann** [kubernetes/minikube#2371]
**Is this a BUG REPORT or FEATURE REQUEST?**: _Feature request_

Support for multiple profiles was added a while ago. However, it is not clear to me how to use them properly, and documentation does not seem to be available.

My general understanding is that profiles can be used to run multiple environments within a single minikube instance. The use case I have in mind is to have one profile for running [traefik](https://github.com/containous/traefik) integration tests and another one for arbitrary, individual usages. I'd like to be able to switch between these when needed.

Here's a list of things I tried and questions I had but couldn't completely understand:

- I changed the profile via `minikube profile foobar`. Apart from the acknowledgement on the shell, however, there is no indication of anything like an environment change. Is anything else happening in the background?
- If I stop minikube and start it again, I can see that the context changed to the new profile. Is this the way it's supposed to be used, or is there some other workflow I should follow?
- What happens when I pass the `--profile` CLI switch? Is this equivalent to running `minikube profile <profile>` prior to the actual command I want to execute?
- How do I determine the currently active profile?
- How do I delete a profile?
- What information is contained in a profile?
- How do profiles and VM driver instances (e.g., Virtualbox machines) relate to each other?

**Environment**:

**Minikube version**: v0.24.1
- **OS**: Mac
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.23.6.iso

**Anything else do we need to know**:

I'd be happy to contribute documentation given someone can provide some feedback to my questions.

Thanks.

**Comment by r2d4** [comment]
cc @aaron-prindle

**Comment by tommyknows** [comment]
Hi,
This is definitely necessary. I can't seem to find anything about the relationship between vm-drivers and profiles, like:
Are profiles working with every vm-driver?
Right now, `vm-driver=none` does not seem to work (which kinda makes sense, but is not documented anywhere), and `vm-driver=kvm2` does not work (see issue https://github.com/kubernetes/minikube/issues/2274).

**Comment by gumaflux** [comment]
Still necessary.

/remove-lifecycle stale

**Comment by tstromberg** [comment]
Help wanted!

**Comment by gumaflux** [comment]
Happy to chip in. @timoreimann

**Comment by ihcsim** [comment]
I posted a write-up on what I've learned about profiles [here](https://medium.com/@ihcsim/using-minikube-profiles-def2477e968a). Let me know if it aligns with your experience. Welcome all feedback and corrections.

**Comment by tstromberg** [comment]
It isn't perfect, but profiles are now documented:

https://minikube.sigs.k8s.io/docs/reference/commands/profile/
