### ISSUE TITLE
kubernetes v1.9.0 fails to come up after restart (kubeadm)

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#2378]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version**
v0.24.1
- **OS**
Ubuntu 16.04.3 LTS
- **VM Driver**
virtualbox
- **ISO version**
minikube-v0.23.6.iso
- **Install tools**:
--bootstrapper kubeadm
- **Others**:
--kubernetes-version v1.9.0

**What happened**:
After a restart, some pods fail to start.

**What you expected to happen**:
It was running just fine, before restart.

**How to reproduce it** (as minimally and precisely as possible):
minikube start --bootstrapper kubeadm --kubernetes-version=v1.9.0
minikube stop
minikube start --bootstrapper kubeadm --kubernetes-version=v1.9.0

**Output of `minikube logs` (if applicable)**:
-- No entries --

**Anything else do we need to know**:

The kube-proxy log says:
`error: open /var/lib/kube-proxy/config.conf: no such file or directory`

**Comment by n-sviridenko** [comment]
The same issue. Did somebody find a resolution?

**Comment by afbjorklund** [comment]
It is the "config.conf" file that goes missing from the kube-system/kube-proxy ConfigMap after reboot.

**Comment by afbjorklund** [comment]
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/bootstrapper/kubeadm/util.go#L178
