### ISSUE TITLE
Support KVM docker-machine driver

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#238]
I have a (nearly) working fork of minikube that supports [KVM Docker Machine driver](https://github.com/dhiltgen/docker-machine-kvm). However there is one problem: it requires cgo & linking to libvirt (from https://github.com/rgbkrk/libvirt-go). I assume that would be a deal breaker but would appreciate it if you think of any way we could support this. libvirt/kvm is a much better option for Linux IMO than virtualbox which I know lots of people have problems with.

`docker-machine` uses the kvm driver via the [plugin architecture](https://github.com/docker/machine/issues/1626) so that it does not need to be compiled in. Is this a better approach for supporting all the drivers docker machine supports?

**Comment by dlorenc** [comment]
Cool!

cgo is a little painful but probably doesn't need to be a dealbreaker. @luxas, what do you think?

We could also use multiple binaries like docker-machine does, but that complicates the setup. Once we get a real installer this option could get a lot more viable, though.

**Comment by jimmidyson** [comment]
As discussed in #242 it seems that libmachine will execute the plugin binary if available so no need to compile in with cgo :) Works for me nicely... just put `docker-machine-driver-kvm` in my PATH, specify kvm driver et voila.
