### ISSUE TITLE
Upgrade localkube past 1.8.0 (1.8.5 preferred)

### ISSUE THREAD

**Issue by adamdecaf** [kubernetes/minikube#2386]
**Minikube version**: `v0.24.1`
- **OS**: OSX 10.11.6
- **ISO version**: v1.8.0

**What happened**:

I'm running into https://github.com/kubernetes/kubernetes/issues/53379, which [seems to have been fixed in v1.8.5](https://github.com/kubernetes/kubernetes/issues/53379#issuecomment-347305399). 

Minikube is unable to download v1.8.5 because it's not [listed in the version manifest downloaded](https://storage.googleapis.com/minikube/k8s_releases.json)

**What you expected to happen**:

Following the [prometheus-operator guide](https://coreos.com/operators/prometheus/docs/latest/user-guides/getting-started.html) should have worked.

**Comment by r2d4** [comment]
We've upgraded it to 1.9.0 at HEAD. We won't be maintaining it after that, and you should use `--bootstrapper kubeadm` instead

**Comment by adamdecaf** [comment]
Alright, thanks. I was able to get my manifests working on 1.8.0.

**Comment by dmick** [comment]
If this is true (support of >1.8.0 requires --bootstrapper kubeadm), should we not 1) make the default --bootstrapper be kubeadm, or 2) document that --bootstrapper kubeadm is required for 1.8+, or 3) both?

This is a particular issue for kubernetes noobs (like me) who do not understand what the differences in bootstrapping methods might imply, or that I might want to change them.  Luckily I happened on this bug, but...

**Comment by r2d4** [comment]
There is an issue tracking it here 

https://github.com/kubernetes/minikube/issues/2134

The only change to end users is how you use the `--extra-config` flag, which we'll be sure to document heavily. Otherwise, there should be no visible changes on the user side

**Comment by dmick** [comment]
Tnx

**Comment by afbjorklund** [comment]
We added 1.8.4 - 1.8.5 - 1.8.6, using something like #2368 to make it more user friendly (than `--iso-url`)
