### ISSUE TITLE
'scp -t' command not exists on mac os

### ISSUE THREAD

**Issue by kricen** [kubernetes/minikube#2393]
environment: mac os
issue            : when start the minikube ,i occur a problem that the scp command don't have the param of -t .
![image](https://user-images.githubusercontent.com/12679710/34599142-d9e4b674-f22b-11e7-82be-76974e61f0d8.png)

**Comment by dlorenc** [comment]
That command is actually supposed to run inside the VM, where scp -t should exist. Could you provide the full logs with --v=10?

**Comment by r2d4** [comment]
ping @kricen, any update?
