### ISSUE TITLE
Load balance round robin not work on windows 10 w/o ssh to minikube

### ISSUE THREAD

**Issue by pencil001** [kubernetes/minikube#2408]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Not sure

Please provide the following details:

**Environment**: Windows 10

**Minikube version**: v0.24.1
- **OS**: Windows 10 version: 1709 internal version: 16299.192
- **VM Driver**: HyperV
- **ISO version**: %HOMEPATH%/.minikube/cache/iso/minikube-v0.23.6.iso
- **Install tools**:
- **Others**:

**What happened**:

I have deployed 4 pods in the cluster:
```
λ  kubectl get pods -o wide
NAME                                   READY     STATUS    RESTARTS   AGE       IP           NODE
kubernetes-bootcamp-6db74b9f76-fwjhs   1/1       Running   0          17m       172.17.0.4   minikube
kubernetes-bootcamp-6db74b9f76-p8ck7   1/1       Running   0          14s       172.17.0.5   minikube
kubernetes-bootcamp-6db74b9f76-tk6c2   1/1       Running   0          14s       172.17.0.7   minikube
kubernetes-bootcamp-6db74b9f76-vp2j8   1/1       Running   0          14s       172.17.0.6   minikube
```
Then I create a service:
```
λ  kubectl.exe get services
NAME                  TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
kubernetes            ClusterIP   10.96.0.1      <none>        443/TCP          51m
kubernetes-bootcamp   NodePort    10.108.19.62   <none>        8080:31658/TCP   7s
```
Then I get the service url:
```
λ  minikube.exe service kubernetes-bootcamp --url
http://10.0.0.11:31658
```
At last I run the **curl** command serveral times, it always get the same output.
```
 Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-6db74b9f76-fwjhs | v=1
```

But when I ssh to the minikube, and run the same **curl** commands serveral times. It will be ok.
```
λ  minikube.exe ssh

$ curl http://10.0.0.11:31658
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-6db74b9f76-tk6c2 | v=1
$ curl http://10.0.0.11:31658
Hello Kubernetes bootcamp! | Running on: kubernetes-bootcamp-6db74b9f76-fwjhs | v=1
```

Is this a bug? 

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by daniel-shukuya** [comment]
Hi, im having exactly the same issue.
Anyone have an idea what is the problem?
