### ISSUE TITLE
read logs via kubectl when journald log-driver is configured 

### ISSUE THREAD

**Issue by andrewgdavis** [kubernetes/minikube#2418]
This is a Feature Request

Currently running:
minikube version: v0.24.1
"DriverName": "virtualbox",
"Boot2DockerURL": "file:///Users/me/.minikube/cache/iso/minikube-v0.23.6.iso",

**What happened**:
Unable to read logs via `kubectl logs` with journald log-driver configured.  Error message is:
```
Error response from daemon: configured logging driver does not support reading
```

**What you expected to happen**:
Logs would be able to be read via `kubectl logs`
[note that they are available via journalctl]

**How to reproduce it** (as minimally and precisely as possible):
```
minikube start --docker-opt log-driver=journald
```
Then launch a pod that has data go to stdout and issue `kubectl logs $pod`
```
kubectl logs foo-76f44c5545-mbqqd
Error response from daemon: configured logging driver does not support reading
```

**Comment by Cryptophobia** [comment]
This seems to still be an issue for me on minikube 0.28

**Comment by Cryptophobia** [comment]
/remove-lifecycle stale

This is still a great feature to have in order to test different log-drivers and writing logs via journald.

**Comment by Cryptophobia** [comment]
So this bug should probably be moved to kubectl so different log-drivers can be supported with kubectl when using on minikube cluster?

**Comment by tstromberg** [comment]
This apparently is no longer an issue in minikube 1.6 / Kubernetes v1.17.
