### ISSUE TITLE
Proposal: add freshpod as an addon

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/minikube#2420]
I'd like to propose a new addon: **https://github.com/GoogleCloudPlatform/freshpod/**

**What:**
> freshpod listens to the docker image events from the host docker.sock and deletes Pods running on Minikube when their images are updated.

**Why:**

> This add-on vastly improves the refactor-build-run cycle on Minikube for me.
> I can simply run a command to `docker build` my app when any of my .py files are updated:
>
>     $ find . -name '*.py' | entr docker build -t myapp .
>
> and freshpod automatically kills pods running the myapp:latest image (with ~1s downtime at most). Therefore,
> I think freshpod this solves in an elegant way by eliminating the steps such as having to run a
> `kubectl delete pods -l app=foo` every time after rebuilding an image on Minikube’s docker-engine.

**How:** I propose we should bundle this add-on with Minikube as _disabled-by-default_.
It's written in Go and has minimal mem/CPU requirements. It uses watch/streaming APIs from
kube-apiserver and the docker engine, therefore has minimal load footprint. This way someone
can install Minikube and run this to start rolling:

    minikube addons enable freshpod

If you support this idea, please hit 👍 , otherwise I'd love to hear concerns about it.

**Comment by r2d4** [comment]
Added in #2423
