### ISSUE TITLE
Is this key in 'constants.go' a secret, and is it OK to keep it there?

### ISSUE THREAD

**Issue by Byron-TW** [kubernetes/minikube#2422]
Please have a look at the URL in the `constants.go` file:

https://github.com/kubernetes/minikube/blob/08f4677511af75330c567845b0b3fbfc8852cee2/pkg/minikube/constants/constants.go#L126

The 'key' portion of the query-string looks like it is a secret, and I wonder if it should be visible to everyone.

As of this writing, it is also present in the most recent commit.

Thanks for the clarification

**Comment by r2d4** [comment]
This is intentional.  This is just for users who have opted in to error reporting. Its just a project identifier. cc @aaron-prindle
