### ISSUE TITLE
Dashboard 1.8 is not compatible with K8s<1.8

### ISSUE THREAD

**Issue by msogrin** [kubernetes/minikube#2429]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): 0.24.0
- **OS** (e.g. from /etc/os-release): Mac OS X (but the issue is platform independent)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**: Dashboard doesn't load correctly, with symptoms identical to https://github.com/kubernetes/dashboard/issues/2693

**What you expected to happen**: Dashboard loads correctly

**How to reproduce it** (as minimally and precisely as possible): 
- start Minikube with `minikube start --kubernetes-version=v1.7.5` or any version less than `1.8`.
- open dashboard with `minikube dashboard`

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**: The issue is described in https://github.com/kubernetes/dashboard/issues/2661#issuecomment-350983654:

> Check https://github.com/kubernetes/dashboard/wiki/Compatibility-matrix. Dashboard 1.8 is not compatible with Kubernetes <1.8. It will not work because of rbac.authorization.k8s.io/v1 API that we are using, it was registered in Kubernetes 1.8. Please update Kubernetes or use an older version of Dashboard (not recommended).

**Suggested solutions**: Automatically load the compatible kubernetes-dashboard version, depending on `--kubernetes-version` value.

OR Remove K8s versions less than 1.8 from `minikube get-k8s-versions`, and thus don't allow to use unsupported K8s version.

**Comment by afbjorklund** [comment]
Maybe something in combination with #1527, to pick the right version ?

**Comment by msogrin** [comment]
k8s versions 1.7 and earlier are not as important as they were 3 months ago.
