### ISSUE TITLE
Proposal: minikube mount in background

### ISSUE THREAD

**Issue by tyranron** [kubernetes/minikube#2431]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

**What happened**:
`minikube mount` runs mount in foreground.

**What you expected to happen**:
Ability to run mount in background. And a convenient way to stop it when necessary.

**Comment by r2d4** [comment]
You can start minikube mount in the background with `minikube start --mount`.  Is this sufficient for your use case?

**Comment by tyranron** [comment]
@r2d4 nope, unfortunately.

`minikube start` is quite a heavy operation. More convenient workflow during local development is to run Minikube once, and then play with it in different projects. Most of my projects are PHP/JavaScript projects, so rebuilding Docker image and redeploying it to Minikube on every source code change is not so comfortable as just mount the whole project dir into the Pod.
Things become more painful when you're playing with multiple projects at the same time. Restarting minikube every time for yet another project to consider their mounts - is not handy at all.

Currently I have the following workaround in my project's `Makefile`:
```makefile
minikube-mount-pid = $(word 1,$(shell ps | grep -v grep \
                                         | grep 'minikube mount' \
                                         | grep 'my-project'))
minikube-release = $(if $(call eq,$(release),),dev-my-project,$(release))

# Stop project in Minikube development environment
# and remove all related Kubernetes specs.
#
# Usage:
#	make minikube.down [release=(dev-my-project|<release-name>)]

minikube.down:
ifneq ($(minikube-mount-pid),)
	kill $(minikube-mount-pid)
endif
ifneq ($(shell helm list | grep '$(minikube-release)'),)
	helm delete --purge $(minikube-release)
endif


# Run project in development environment based on Minikube (local Kubernetes).
#
# Usage:
#	make minikube.up [release=(dev-my-project|<release-name>)]

minikube.up:
ifeq ($(minikube-mount-pid),)
	minikube mount "$(PWD):/mount/my-project" &
endif
	helm upgrade --install -f .helm/dev.values.yml $(minikube-release) \
		.helm/charts/my-project
```

This allows any project to mount at any time for comfortable development without messing with Minikube restarts.

It would be nice to have something like `minikube mount start <local-dir>:<host-dir>` /  `minikube mount stop <local-dir>:<host-dir>` instead of `minikube start ... &` and messing with `ps`/`grep`/`kill`.

**Comment by viteksafronov** [comment]
This feature would be very helpful, but why don't you want just to mount, say, the whole home (or another) directory to minikube at start?

**Comment by tyranron** [comment]
@viteksafronov the reasons may vary... from paranoidal (don't want to expose all my home files to third-party environments), to practical (not all projects may be located in home).

The common idea is to not force developer to use specific filesystem layout to develop with Minikube, but rather give tools for comfortable development independently from filesystem.

**Comment by r2d4** [comment]
That sounds good to me. 

We already have the code for this, its just a matter of exposing the behavior as subcommands.

Create mount in background
https://github.com/kubernetes/minikube/blob/69fc158ce86e8fd113cd42ae616c8009454fe212/cmd/minikube/cmd/start.go#L275-L299

Delete mount by PID
https://github.com/kubernetes/minikube/blob/69fc158ce86e8fd113cd42ae616c8009454fe212/cmd/util/util.go#L238-L252

**Comment by msgongora** [comment]
@tyranron take a look to [my fork](https://github.com/msgongora/minikube/tree/v0.25.0-detach). I'll rather a better approach/design like @r2d4 proposed previously but since I'm still learning about minikube architecture, [this](https://github.com/msgongora/minikube/commit/49f07c8620f6a165aad74f1103ec02368bb3d52f) was the best I could do. In the meantime, you can compile it and use `mount-detach` command.

**Comment by Jokero** [comment]
Yeah, it will be nice to have a way to easily mount several directories at the same time not in foreground

**Comment by bcho** [comment]
@r2d4 will this feature continue to be valid?

**Comment by cglacet** [comment]
Is this still not possible? What I really need is the ability to mount several folders, maybe that's not the only way I could achieve this.

**Comment by nolatone** [comment]
Minikube sets permissions for all subdirs to one uid, apparently 9P doesn't translate UIDs from the host to the client mount like NFS for example, and this breaks services in my pods.

To deal with this I have to use multiple mounts each with different --uid  to support Persistent Volumes for kafka, zookeeper, and other services running with minikube.

**Comment by omninonsense** [comment]
This is still an issue today. Like some people said, earlier, using `--mount` and `--mount-string` to `start`  is not always a great option (and I'm not sure how we'd mount more thing), and having multiple foreground processes for mounts is also less than ideal.

/reopen

**Comment by roblappcoupa** [comment]
Is it not possible to mount in the background? What about multiple mounts? If that's not supported, then I guess it's back to Docker Desktop :(
