### ISSUE TITLE
Error when starting minikube on the Mac with the hyperkit driver

### ISSUE THREAD

**Issue by parhamdoustdar** [kubernetes/minikube#2433]
The following is a bug.

**Environment**:

**Minikube version** (use `minikube version`): v0.24.1
- **OS** (e.g. from /etc/os-release): Darwin x86_64
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.6.iso

**What happened**: When running `minikube start --vm-driver=hyperkit`, I get an error saying:

`E0115 15:29:12.531514   44736 start.go:156] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: making disk image: truncate /Users/pdoustdar/.minikube/machines/minikube/minikube.rawdisk: no space left on device`

**What you expected to happen**: I expected the machine to be created and provisioned successfully.

**How to reproduce it** (as minimally and precisely as possible):

1. install the specified software versions.
2. Run `minikube start --vm-driver=hyperkit`.

**Comment by msogrin** [comment]
> no space left on device

@parhamdoustdar can you verify how much free disk space you have?

**Comment by parhamdoustdar** [comment]
Yes, sure!

I have 28.9 GB free.

**Comment by msogrin** [comment]
I think minikube attempts to reserve 64 GB of disk, so 28.9 GB free might indeed cause the "no space left on device" error.

Can you try running `minikube start --vm-driver=hyperkit --disk-size=10g`? (choose a number that's less than 28.9 GB here)

**Comment by parhamdoustdar** [comment]
Thanks, that worked. I thought the error was not talking about my actual disk, and talking about the VM disk.

Thanks a lot for the quick replies.

**Comment by alanjds** [comment]
Would be nice to have a more descriptive error message, saying "Cannot allocate a 64 disk".
