### ISSUE TITLE
Kubernetes 1.9 with CSI support

### ISSUE THREAD

**Issue by lpabon** [kubernetes/minikube#2434]
QUESTION:

I am working on a tutorial for Kubernetes with CSI (Container Storage Interface) support, and I am wondering if the following is possible in minikube:
1. Support for 1.9
2. Support to set feature gates and runtime-config to enable alpha features (or enable all features)
3. Support for mount propagation in the kernel of the VM which is used

**Comment by r2d4** [comment]
1) 1.9 is supported at HEAD, and we are planning a release soon
2) Yes, you can do this through the `--feature-gates` convenience flag or through `--extra-config` to `minikube start`
3) There is a `minikube mount` command, or you can use the built in mounting with virtualbox (vboxfs) or hyperkit.  Alternatively, you can also set up NFS or SSHFS between the host and VM.

**Comment by lpabon** [comment]
Thanks @r2d4 . This may be a stupid question, but when I built minikube on head, it is looking for a 'localkube-v1.9.0'. Is there way to download one from a CI build?

**Comment by lpabon** [comment]
Ok, I got it working by doing a `make out/localkube` and then linking it from `~/.minikube`. Looks as follows:

```
(kubernetes) lpabon@localhost : ~/git/golang/kubernetes/src/k8s.io/minikube
$ ls -al /home/lpabon/.minikube/cache/localkube/
total 151816
drwxrwxr-x. 2 lpabon lpabon        85 Jan 19 14:42 .
drwxrwxr-x. 5 lpabon lpabon        48 Jan 18 13:22 ..
-rw-------. 1 lpabon lpabon 155452040 Jan 18 13:25 localkube-v1.8.0
-rw-------. 1 lpabon lpabon        65 Jan 18 13:25 localkube-v1.8.0.sha256
lrwxrwxrwx. 1 lpabon lpabon        68 Jan 19 14:42 localkube-v1.9.0 -> /home/lpabon/git/golang/kubernetes/src/k8s.io/minikube/out/localkube
```

I tried to see if there was a flag to point to the localkube, but I couldn't find one, so the sym link above works.

**Comment by r2d4** [comment]
You can use `--kubernetes-version=file:///path/to/localkube` to specify a custom localkube file.

There are CI builds for every PR https://github.com/kubernetes/minikube/blob/master/docs/contributors/ci_builds.md
