### ISSUE TITLE
Not able to access a private repo as .docker/config needs to go in root home directory

### ISSUE THREAD

**Issue by MikeCoutts** [kubernetes/minikube#244]
Following the kuberneties guide http://kubernetes.io/docs/user-guide/images/#using-a-private-registry I setup the config.json file with my authentication credentials for an internally hosted docker repo. However, not clear where this file needs to go within the MiniKube VM to satisfy the instruction:

"copy your local .docker/config.json to the home directory of root on each node"

**Comment by dlorenc** [comment]
Hey,

Thanks for the report, we should definitely figure out how to do this, and document it. "The home directory of root" is "/root" in the minikube VM. I haven't tried putting a .docker/config.json there yet, but it might just work.

If you get a chance, could you reply back and let me know if that worked?

**Comment by dlorenc** [comment]
Actually I got this working, the right directory to put the file into is /home/docker.

**Comment by dlorenc** [comment]
I think we'll probably want to recommend using an [ImagePullSecret](http://kubernetes.io/docs/user-guide/images/#specifying-imagepullsecrets-on-a-pod) though, it should be easier than copying a file around.

**Comment by MikeCoutts** [comment]
I tried /root/config.json and /root/.docker/config.json and now /home/docker/config.json and they all come back with "FailedScheduling no nodes available to schedule pods" in the describe so perhaps this is a different issue here (the image I'm trying to pull is pretty large, I can try and setup a much smaller one to see if that's the issue.

I did also try with the imagePullSecret and agree that would be better, but got the same result.

**Comment by dlorenc** [comment]
Ah, I tried with a .dockercfg. Could you try putting the config.json in /home/docker/.docker?

**Comment by dlorenc** [comment]
But yeah, that error seems unrelated. Whats in the pod you're trying to schedule? That seems like a resource issue. Maybe you're asking for more CPU/RAM than the VM has?

**Comment by MikeCoutts** [comment]
/home/docker/.docker is where the docker login put the original config.json file so I think this is related related to image size (900MB CentOS/JMeter might just be too much for MiniKube). Going off company network now but when I get back I'll try and push something like a buzybox to our internal repo and see if I can get it back.

**Comment by MikeCoutts** [comment]
OK back on this with a fresh minikube and a buzyboxplus image and definitely getting the right error now ErrImagePull: "unauthorized: authentication required". I'll try putting the config.json file in different locations to see if I can get this to work

**Comment by MikeCoutts** [comment]
OK with /home/docker/.docker/config.json in place as per the new documentation #245 I am able to pull from a private repository, but agree that this should really be done with an ImagePullSecret, which i can try tomorrow.

**Comment by dlorenc** [comment]
Great, let me know if you have any luck.

**Comment by MikeCoutts** [comment]
Confirming that the instructions "Specifying ImagePullSecrets on a Pod" at http://kubernetes.io/docs/user-guide/images/ is working for MiniKube 0.4.0 with a private repository. Image pulled and started correctly.

MikeC.

**Comment by dlorenc** [comment]
Great. I'll close this out for now, please reopen or open a new issue if you have any other trouble!
