### ISSUE TITLE
eval $(minikube docker-env) for driver type none

### ISSUE THREAD

**Issue by pemmasanikrishna** [kubernetes/minikube#2443]
When the minikube is start with driver type none, then when eval $(minikube docker-env) is issued , its throwing exception `"'none' driver does not support 'minikube docker-env' command"`.
So, how to use local images when using no driver.

minikube version: v0.24.1

**Comment by r2d4** [comment]
This is intended behavior. While using the none driver, the host docker daemon will be used, so you can access it without any special environment variables.

**Comment by MartinKosicky** [comment]
This brings me to my question... why I am not able to use local docker images then?  That I locally built with docker-build...
