### ISSUE TITLE
README broken link

### ISSUE THREAD

**Issue by juliusakula** [kubernetes/minikube#2452]
Sorry for skipping the template, this issue is very straightforward..

In the README.md ["Interacting with your cluster" section -- ](https://github.com/kubernetes/minikube/blob/master/README.md#kubectl) , there is a broken link to what I assume would be more information on the "kubectl context". The [existing link to kubernetes.io is a 404](https://kubernetes.io/docs/user-guide/kubectl/v1.7/#-em-set-context-em-).. I could not find the appropriate link to replace. Possible fix to remove this hyperlink in the README altogether

**Comment by juliusakula** [comment]
Also broken link to `redspread` at the very bottom

**Comment by r2d4** [comment]
The first `kubectl context` link should link to https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#-em-set-context-em-

As for the redspread link, I think it is OK to keep the text but remove the link, as they were acquired by CoreOS.
