### ISSUE TITLE
Shipping KVM2 driver with minikube

### ISSUE THREAD

**Issue by abitrolly** [kubernetes/minikube#2462]
**FEATURE REQUEST**

KVM2 needs to be installed separately - https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver. Why is it impossible to embed it like KVM?

Also, an explanation why KVM2 is better will be welcome.

**Comment by deknos** [comment]
yep, same with me, for the kvm-driver either. this is very confusing

**Comment by deknos** [comment]
Well i have a working solution. It would really help if there is a --test-environment to show which privileges and binaries are needed. like creating networks via virsh, needing docker-machine-driver-kvm2 and so on.

Here's my working solution:
* debian stretch, purge any virtualbox, install libvirt* packages, these are not any more longer libvirt-bin but packages in different packages and virt-manager is helpful as well. restart for eventual vbox modules.
* install docker-ce from the community.
* get docker-machine-driver-kvm2 from the other repository as mentioned in the docs.
* sudo minikube start --vm-driver=kvm2 # without sudo you can set it up but you WONT get to the pod later in my experience
* sudo kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.4 --port=8080

and so on as described in https://kubernetes.io/docs/getting-started-guides/minikube/#quickstart with sudo.

Now that i have a working environment i look into it, which privileges are needed in fact, so i do not need sudo all the time.   perhaps it helps someone else.

**Comment by afbjorklund** [comment]
The KVM and KVM2 drivers are getting merged, so that there is a common and supported "libvirt" driver...

Hopefully this should make for a more smooth installation experience, in the future. Including "qemu" driver.

**Comment by afbjorklund** [comment]
The new driver is here: https://github.com/machine-drivers/docker-machine-driver-libvirt

I don't think it has all the fixes from KVM2 in yet though, and it is still being called KVM...

**Comment by ILMostro** [comment]
If that's the new driver, where's the old one? I don't see other branches on that repo; yet, the last commit there was a year ago.
Is the kvm2 driver only available as a binary download?

**Comment by tstromberg** [comment]
Closing in preference to #1623
