### ISSUE TITLE
Minikube cannot reach dashboard after installation

### ISSUE THREAD

**Issue by HofmT** [kubernetes/minikube#2463]
**BUG REPORT**

**Environment**: Windows 10

**Minikube version**: v0.24.1
- **VM Driver**: Virtualbox
- **ISO version**: minikube-v0.23.6.iso

**What happened**:
When I start minikube and I try to reach the dashboard there is a warning about an insecure connection. When I make an exception for dashboard I reach the dashboard but it displays an error like this:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "Unauthorized",
  "reason": "Unauthorized",
  "code": 401
}

**How to reproduce it** (as minimally and precisely as possible):
I just installed minikube via the minikube.exe. Installation ran seamlessly.

**Comment by lazzarello** [comment]
I suspect this is related to the breaking changes between the 1.7 and 1.8 dashboard default configuration.

**Comment by lazzarello** [comment]
0.25.0 with kube ISO 1.9 works for me

**Comment by HofmT** [comment]
@abhinav-chittora Yes, I tried it. Issue still occurs. I also cannot run any _kubectl_ command such as _kubectl cluster-info_. It then says: _Unable to connect to the server: Service Unavailable_

**Comment by abhinav-chittora** [comment]
Please paste the output of `kubectl config view`
