### ISSUE TITLE
Downloads for localkube v1.9.0 are missing from GCS

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#2472]
These are OK:

https://storage.googleapis.com/minikube/k8sReleases/v1.8.0/localkube-linux-amd64
https://storage.googleapis.com/minikube/k8sReleases/v1.8.0/localkube-linux-amd64.sha256

These are not:

https://storage.googleapis.com/minikube/k8sReleases/v1.9.0/localkube-linux-amd64
https://storage.googleapis.com/minikube/k8sReleases/v1.9.0/localkube-linux-amd64.sha256

This means that minikube 0.25 is broken in the default configuration (see #2468 and #2471 - et al)

Have to use `--kubernetes-version=v1.8.0` or `--bootstrapper kubeadm` options, to make it start.

----

Seems like only the JSON file* was updated, but not the actual releases ? Procedure outlined in:
https://github.com/kubernetes/minikube/blob/master/docs/contributors/releasing_localkube.md

* https://storage.googleapis.com/minikube/k8s_releases.json

**Comment by afbjorklund** [comment]
Looks like they (the v1.9.0 localkube) are available from here:

https://github.com/kubernetes/minikube/releases/download/v0.25.0/localkube
https://github.com/kubernetes/minikube/releases/download/v0.25.0/localkube.sha256

Which means that this should work too, even if not easy to guess:

`minikube start --kubernetes-version=https://github.com/kubernetes/minikube/releases/download/v0.25.0/localkube`

**Comment by dstroot** [comment]
Using `kubectl proxy` and `http://http://localhost:8001/ui` I get this result:

```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://172.17.0.2:9090/'
```

**Comment by afbjorklund** [comment]
@dstroot : sounds like a http/https confusion, what does `minikube dashboard` do ?

**Comment by r2d4** [comment]
Sorry for the confusion, this should be fixed now.  I pushed localkube to the right location and verified locally that it works.

**Comment by r2d4** [comment]
Please reopen if there are still issues

**Comment by rayterrill** [comment]
Confirmed working on v0.25.0 on Win10/Virtualbox.

**Comment by dstroot** [comment]
@afbjorklund - thanks for the reply.  `minikube dashboard` works!  I have always just ran `kubectl proxy` and that still seems broken.

**Comment by montera82** [comment]
any update why GET http://127.0.0.1:8001/ui
returns 
```
Error: 'tls: oversized record received with length 20527'
Trying to reach: 'https://172.17.0.2:9090/'
```

**Comment by mamartinez724** [comment]
Still not working, same problem. I tried deleting the .minikube directory and it didn't work 
Ubuntu 16.04 Server & Vitrualbox

**Comment by markroxor** [comment]
Installing version `0.25` from [releases](https://github.com/kubernetes/minikube/releases). SOLVED IT!!.
Try `curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.25.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/`
