### ISSUE TITLE
Minikube efk plugin kibana cannot connect to elasticsearch-logging

### ISSUE THREAD

**Issue by rcplane** [kubernetes/minikube#2482]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.24.1
- **OS** (e.g. from /etc/os-release): Mac OS X 10.11.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.6.iso
- **Install tools**: recent install
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**: minikube addons enable efk
minikube addons open efk

ID | Status
-- | --
ui settings | Elasticsearch plugin is red
plugin:kibana@5.6.2 | Ready
plugin:elasticsearch@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
...

minikube ssh

$ ping 192.168.99.100:9200
PING 192.168.99.100:9200 (192.168.99.100): 56 data bytes
64 bytes from 192.168.99.100: seq=0 ttl=64 time=0.053 ms
64 bytes from 192.168.99.100: seq=1 ttl=64 time=0.074 ms

$ ping elasticsearch-logging:9200
ping: bad address 'elasticsearch-logging:9200'

**What you expected to happen**: clean output as pictured https://github.com/kubernetes/minikube/pull/2147

**How to reproduce it** (as minimally and precisely as possible): minikube start
minikube addons enable efk
minikube addons open efk

**Output of `minikube logs` (if applicable)**:
Not sure if relevant.
Jan 29 22:12:50 minikube localkube[3225]: E0129 22:12:50.956111    3225 healthcheck.go:317] Failed to start node healthz on 0: listen tcp: address 0: missing port in address
Jan 29 22:13:50 minikube localkube[3225]: E0129 22:13:50.957077    3225 healthcheck.go:317] Failed to start node healthz on 0: listen tcp: address 0: missing port in address

**Anything else do we need to know**: Is there a more favored combination of logging stack technologies I should pursue?

**Comment by javajon** [comment]
/reopen

I get the seemingly same issue with Minikube 0.28.2 with VirtualBox 5.2.18 on Windows 10 after:

"minikube addons enable efk"

All EFK resources appear running and OK, except "error
elasticsearch-logging" ReplicationController is reporting "Back-off restarting failed container"

Kibana dashboard reports:

ID | Status
-- | --
ui settings | Elasticsearch plugin is red
plugin:kibana@5.6.2 | Ready
plugin:elasticsearch@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:xpack_main@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:graph@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:reporting@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:searchprofiler@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:ml@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:tilemap@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:watcher@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:grokdebugger@5.6.2 | Ready
plugin:upgrade@5.6.2 | Unable to connect to Elasticsearch at http://elasticsearch-logging:9200.
plugin:console@5.6.2 | Ready
plugin:metrics@5.6.2 | Ready
plugin:timelion@5.6.2 | Ready

Minikube log reports:

Sep 11 00:54:16 minikube kubelet[2889]: I0911 00:54:16.971433    2889 kuberuntime_manager.go:757] checking backoff for container "elasticsearch-logging" in pod "elasticsearch-logging-gd4dr_kube-system(a0ff2505-b4a7-11e8-9546-08002796e4fa)"
Sep 11 00:54:16 minikube kubelet[2889]: I0911 00:54:16.972037    2889 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-gd4dr_kube-system(a0ff2505-b4a7-11e8-9546-08002796e4fa)
Sep 11 00:54:16 minikube kubelet[2889]: E0911 00:54:16.972122    2889 pod_workers.go:186] Error syncing pod a0ff2505-b4a7-11e8-9546-08002796e4fa ("elasticsearch-logging-gd4dr_kube-system(a0ff2505-b4a7-11e8-9546-08002796e4fa)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-gd4dr_kube-system(a0ff2505-b4a7-11e8-9546-08002796e4fa)"
