### ISSUE TITLE
Minikube v0.25.0 Windows 10, VirtualBox 5.2.6, Error starting host, Exit Status 1

### ISSUE THREAD

**Issue by ahusmc** [kubernetes/minikube#2489]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

Please provide the following details:

**Environment**:
Windows 10, Version 1607, Build 14393.2007
VirtualBox Version 5.2.6 r120293 (Qt5.6.2)
**Minikube version** (use `minikube version`):
minikube version: v0.25.0 (I've added C:\Program Files (x86)\Kubernetes\Minikube to my path variable).
- **OS** (e.g. from /etc/os-release):
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): 
virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):

ISO won't download (Network connectivity is good)
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
E0130 11:14:03.059177   12444 start.go:159] Error starting host: Error starting stopped host: exit status 1.

Minikube won't start, ISO does not download.
**What you expected to happen**:
Minikube starts, IS downloads, Minikube rocks.
**How to reproduce it** (as minimally and precisely as possible):
Install minikube-installer.exe, drop kubectl.exe in Minikube dir, add  C:\Program Files (x86)\Kubernetes\Minikube to my path variable, minikube start, minikube rocks....
**Output of `minikube logs` (if applicable)**:
No minikube logs being generated in C:\Program Files (x86)\Kubernetes\Minikube
**Anything else do we need to know**:
E0130 11:14:03.060604   12444 start.go:165] Error starting host:  Error starting stopped host: exit status 1

Also, no Minikube VM is being generated in VirtualBox.

**Comment by ahusmc** [comment]
Ping

**Comment by ewth126** [comment]
try to delete  C:/${user}/.minikube/ 。
