### ISSUE TITLE
dashboard start error

### ISSUE THREAD

**Issue by lovelivestyle1102** [kubernetes/minikube#2499]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release):
windows10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
C:\Users\superuser>minikube ssh cat /etc/VERSION
v0.23.6

- **Install tools**:

- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
C:\Users\superuser>minikube version
minikube version: v0.24.1

echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
C:\Users\superuser>minikube dashboard
Waiting, endpoint for service is not ready yet...
.
.
.

**What you expected to happen**:
start dashboard success

**How to reproduce it** (as minimally and precisely as possible):
when i enter minikube dashboard

**Output of `minikube logs` (if applicable)**:
ng for connection (Client.Timeout exceeded while awaiting headers)
Feb 02 06:37:03 minikube localkube[8170]: E0202 06:37:03.496878    8170 kuberuntime_manager.go:632]
createPodSandbox for pod "hello-minikube-7844bdb9c6-8fmd7_default(cfba93a5-07de-11e8-9d2c-080027216
b2)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-
md64:3.0": Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while wai
ing for connection (Client.Timeout exceeded while awaiting headers)
Feb 02 06:37:03 minikube localkube[8170]: E0202 06:37:03.497004    8170 pod_workers.go:182] Error s
ncing pod cfba93a5-07de-11e8-9d2c-0800272167b2 ("hello-minikube-7844bdb9c6-8fmd7_default(cfba93a5-0
de-11e8-9d2c-0800272167b2)"), skipping: failed to "CreatePodSandbox" for "hello-minikube-7844bdb9c6
8fmd7_default(cfba93a5-07de-11e8-9d2c-0800272167b2)" with CreatePodSandboxError: "CreatePodSandbox
or pod \"hello-minikube-7844bdb9c6-8fmd7_default(cfba93a5-07de-11e8-9d2c-0800272167b2)\" failed: rp
 error: code = Unknown desc = failed pulling image \"gcr.io/google_containers/pause-amd64:3.0\": Er
or response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for conne
tion (Client.Timeout exceeded while awaiting headers)"
Feb 02 06:37:09 minikube localkube[8170]: E0202 06:37:09.500916    8170 remote_runtime.go:92] RunPo
Sandbox from runtime service failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/
oogle_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: net/http: re
uest canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
Feb 02 06:37:09 minikube localkube[8170]: E0202 06:37:09.501124    8170 kuberuntime_sandbox.go:54]
reatePodSandbox for pod "kube-addon-manager-minikube_kube-system(7b19c3ba446df5355649563d32723e4f)"
failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64
3.0": Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting
or connection (Client.Timeout exceeded while awaiting headers)
Feb 02 06:37:09 minikube localkube[8170]: E0202 06:37:09.501370    8170 kuberuntime_manager.go:632]
createPodSandbox for pod "kube-addon-manager-minikube_kube-system(7b19c3ba446df5355649563d32723e4f)
 failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd6
:3.0": Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting
for connection (Client.Timeout exceeded while awaiting headers)
Feb 02 06:37:09 minikube localkube[8170]: E0202 06:37:09.501578    8170 pod_workers.go:182] Error s
ncing pod 7b19c3ba446df5355649563d32723e4f ("kube-addon-manager-minikube_kube-system(7b19c3ba446df5
55649563d32723e4f)"), skipping: failed to "CreatePodSandbox" for "kube-addon-manager-minikube_kube-
ystem(7b19c3ba446df5355649563d32723e4f)" with CreatePodSandboxError: "CreatePodSandbox for pod \"ku
e-addon-manager-minikube_kube-system(7b19c3ba446df5355649563d32723e4f)\" failed: rpc error: code =
nknown desc = failed pulling image \"gcr.io/google_containers/pause-amd64:3.0\": Error response fro
 daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Ti
eout exceeded while awaiting headers)"
Feb 02 06:37:16 minikube localkube[8170]: I0202 06:37:16.711736    8170 trace.go:76] Trace[85488479
: "List /apis/batch/v1/jobs" (started: 2018-02-02 06:37:15.996046076 +0000 UTC m=+779.843078926) (t
tal time: 715.517478ms):
**Anything else do we need to know**:
how can i do ? can i use proxy?

**Comment by abhinav-chittora** [comment]
@lovelivestyle1102 : Are you behind proxy? Are you able to pull docker images from gcr.io repository?

**Comment by lovelivestyle1102** [comment]
I can't get  the message from grc.io, where can i replace this url?

**Comment by looztra** [comment]
Behind a proxy you have to:

- set `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` according to your proxy urls
- start minikube with some extra flags : `minikube start --docker-env HTTP_PROXY=$HTTP_PROXY --docker-env HTTPS_PROXY=$HTTPS_PROXY`


Please note (but you are maybe already aware of that):

- you are not using the latest minikube version which is `v0.25.0`
- your iso version (v0.23.6) is not in sync with your minikube version (v0.24.1). It does not seem mandatory to have them in sync but when facing troubles it's not a bad idea to get them updated. You can get the iso in sync with you minikube version by running `minikube cache delete` before running `minikube start`
