### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by rfussien** [kubernetes/minikube#2503]
Hello,

Sounds like it should be `$ source <(minikube completion zsh) # for zsh users`.
Isn't it ?
https://github.com/kubernetes/minikube/blob/c76b21039339d14aec19310911508bd2286f2265/cmd/minikube/cmd/completion.go#L44

**Comment by adolphlwq** [comment]
Yes, you can fix it and make a PR

**Comment by rfussien** [comment]
Sure. #2507
