### ISSUE TITLE
Failed pulling image "gcr.io/google_containers/pause-amd64:3.0"

### ISSUE THREAD

**Issue by vasily-kirichenko** [kubernetes/minikube#2514]
Windows 10 behind a corporate HTTP(S) proxy.

```
kubectl get po --all-namespaces
NAMESPACE     NAME                          READY     STATUS              RESTARTS   AGE
kube-system   kube-addon-manager-minikube   0/1       ContainerCreating   0          25m
```
```
minikube logs
```
> ...
Feb 05 10:31:19 minikube localkube[3149]: E0205 10:31:19.542703    3149 pod_workers.go:186] Error syncing pod c4c3188325a93a2d7fb1714e1abf1259 ("kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)"), skipping: failed to "CreatePodSandbox" for "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)\" failed: rpc error: code = Unknown desc = failed pulling image \"gcr.io/google_containers/pause-amd64:3.0\": Error response from daemon: Get https://gcr.io/v2/: dial tcp 173.194.221.82:443: getsockopt: connection refused"

`HTTP_PROXY` and `HTTPS_PROXY` env vars are set properly, other tools works OK. Maybe it's necessary to pass proxy settings to Minikube somehow?

**Comment by vasily-kirichenko** [comment]
https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

**Comment by KeithTt** [comment]
Same error, but I do `minikube stop` and start with `minikube start --docker-env=HTTP_PROXY=http://127.0.0.1:1087 --docker-env=HTTPS_PROXY=https://127.0.0.1:1087`, it do not work...

And I pull the image `gcr.io/google_containers/pause-amd64:3.0` manually...

**Comment by boynanboy** [comment]
how to fix it

**Comment by losymear** [comment]
@boynanboy Have you resolved this?
