### ISSUE TITLE
minikube completion (zsh|bash) takes 0.5s to execute: make it faster.

### ISSUE THREAD

**Issue by Frederick888** [kubernetes/minikube#2516]
Originally reported in robbyrussell/oh-my-zsh#6436

```
$ time minikube completion zsh
...
...
minikube completion zsh  0.17s user 0.04s system 43% cpu 0.488 total
```

I'm not using a particularly crappy machine (quad core i7) and I think half a second could be considered noticeable in terms of the launching time of a shell.

The script for `minikube` has ~1,600 lines and it takes ~0.5s to print it out.
In comparison, the script for `rustup` has ~1,000 lines and it takes only ~0.003s.
```
$ time rustup completions zsh
...
...
rustup completions zsh  0.00s user 0.00s system 91% cpu 0.003 total
```
Got no idea why it's so slow though. I think it makes sense to take up to 0.01s (and it does on @kenden's macbook).

**Environment**:

- **Minikube version**: `v0.25.0`
- **OS**: ArchLinux (`4.14.15-1-ARCH #1 SMP PREEMPT Tue Jan 23 21:49:25 UTC 2018 x86_64 GNU/Linux`)
- **VM Driver**: `virtualbox`
- **ISO version**: `minikube-v0.23.6.iso`
- **Terminal**: Konsole/Yakuake

**Comment by r2d4** [comment]
We use https://github.com/spf13/cobra for autogenerating the shell completion. No one is actively working on speeding this command up, but if you want to investigate it or speed it up, we'd be happy to accept contributions either here (or I'm sure spf13/cobra would also happily accept contributions)

**Comment by kenden** [comment]
@Frederick888 Could you time `$ time minikube completion bash` to check if it's a problem with https://github.com/spf13/cobra itself or with the wrapper to get it to work with zsh?

If it is working fast for you, then it's probably not a cobra issue.
[This PR](https://github.com/spf13/cobra/pull/646) to get zsh code completion directly from cobra might help in this case.
If bash autocomplete is also slow, that's indeed a bug in the cobra bash autocomplete code, would you report it there?

**Comment by Frederick888** [comment]
@kenden I installed kops from https://aur.archlinux.org/packages/kops-bin/ and actually it's far faster than minikube

```
$ time minikube completion bash > /dev/null
minikube completion bash > /dev/null  0.17s user 0.03s system 39% cpu 0.484 total
$ time kops completion bash > /dev/null
kops completion bash > /dev/null  0.10s user 0.01s system 128% cpu 0.082 total
```

**Comment by kenden** [comment]
If minikube bash completion is slow, but not kops bash completion it could point to how cobra is used in Minikube.
Here are the functions in minikube, kops and kubectl:
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/completion.go#L94
https://github.com/kubernetes/kops/blob/master/cmd/kops/completion.go#L140
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubectl/cmd/completion.go#L130
Nothing obvious jumps at me, and without being able to reproduce it, it's tricky.

Try to to add:
```go
	if len(boilerPlate) == 0 {
		boilerPlate = defaultBoilerPlate
	}
```
at the beginning of `GenerateBashCompletion()`, then build and test?

**Comment by kenden** [comment]
Oh wait, could you first time other minikube commands? I suspect they could all be slow for you.

**Comment by kenden** [comment]
I found a way to reproduce the issue on my system:
- rename the .zshrc file
`$ mv ~/.zshrc ~/.zshrc.bak`
- start a new command line 
- use minikube commands
  ```
   $ time minikube completion bash
   minikube completion bash  0.02s user 0.01s system 0% cpu 30.037 total
   $ time minikube config view
   minikube config view  0.02s user 0.02s system 0% cpu 30.032 total
   ```
So, indeed, it seems to be a problem with all minikube commands. 
@Frederick888 Can you confirm?

- I didn't get the issue with other programs:
```
helm completion bash  0.06s user 0.02s system 112% cpu 0.069 total
kubectl completion bash  0.08s user 0.04s system 37% cpu 0.332 total
```

**Comment by Frederick888** [comment]
@kenden I also renamed zshrc and tested in a new shell:
```
FredArch% time minikube completion bash > /dev/null
minikube completion bash > /dev/null  0.09s user 0.02s system 24% cpu 0.451 total
FredArch% time minikube config view > /dev/null    
minikube config view > /dev/null  0.11s user 0.01s system 24% cpu 0.485 total
FredArch% time kubectl completion bash > /dev/null 
kubectl completion bash > /dev/null  0.10s user 0.02s system 130% cpu 0.093 total
```
