### ISSUE TITLE
Link to registry addon in the documentation is dead

### ISSUE THREAD

**Issue by thedrow** [kubernetes/minikube#2520]
Where is the new link now?

**Comment by r2d4** [comment]
Looks like its been removed upstream 
https://github.com/kubernetes/kubernetes/pull/58564

We can either mirror that readme here or link to the manifests themselves in this repo
https://github.com/kubernetes/minikube/tree/ec1b443722227428bd2b23967e1b48d94350a5ac/deploy/addons/registry

Either SGTM
