### ISSUE TITLE
Add command `minikube list-drivers`

### ISSUE THREAD

**Issue by anfernee** [kubernetes/minikube#2527]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): feature request

Please provide the following details: `minikube list-drivers` will give you a list of drivers that are available on the host. Basically you have an idea of what driver you could add to `minikube start --vm-driver=xxx`.

```
$ minikube list-drivers
Driver          State             Plugin
virtualbox    enabled         docker-machine-driver-virtualbox
vmware       enabled         <builtin>
hyperkit       disabled        docker-machine-driver-hyperkit <missing>
```

**Comment by afbjorklund** [comment]
As long as the list of "supported" (allowed) drivers is hard-coded, might as well show that instead...
i.e. it has nothing to do with what drivers are available on the host, more about what minikube can use

**Comment by afbjorklund** [comment]
@anfernee : Something like this:
```
$ minikube start --help | grep vm-driver
      --vm-driver string                VM driver is one of: [virtualbox kvm kvm2 none] (default "virtualbox")
```
But with some kind of driver "check" ?

**Comment by gbraad** [comment]
The mapping is currently still coded. This is also an issue on our
(minishift) end.

**Comment by afbjorklund** [comment]
AFAIK, libmachine has some kind of path function:
https://github.com/docker/machine/blob/master/libmachine/drivers/plugin/localbinary/plugin.go#L100

But it also needs to play nice with the "builtin" drivers:
https://github.com/kubernetes/minikube/blob/master/pkg/drivers/drivers.go#L37

**Comment by anfernee** [comment]
thanks for the pointer to the code @afbjorklund 

I think we need some kind of list command, `--help` also gives you that, but it buried in too much information. also it's better if it tells you what are available plugins. Now, if you run a plugin that is not builtin and not available in PATH, minikube crashes. 

```
$ minikube start --vm-driver kvm2
Starting local Kubernetes v1.9.0 cluster...
Starting VM...
E0212 10:49:34.215714    9570 start.go:159] Error starting host: Error creating new host: Driver "kvm2" not found. Do you have the plugin binary "docker-machine-driver-kvm2" accessible in your PATH?.

 Retrying.
E0212 10:49:34.215859    9570 start.go:165] Error starting host:  Error creating new host: Driver "kvm2" not found. Do you have the plugin binary "docker-machine-driver-kvm2" accessible in your PATH?
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
n

```

**Comment by anfernee** [comment]
@gbraad can you provide the link for minikube issue? thanks!

**Comment by gbraad** [comment]
@anfernee 'issue' was used here to indicate a general problem. not specifically a tracked issue.
