### ISSUE TITLE
Minikube mount fails silently

### ISSUE THREAD

**Issue by RoBorg** [kubernetes/minikube#2529]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

Please provide the following details:

**Minikube version**: v0.25.0
- **OS**: Windows 10
- **VM Driver**: Hyper-v
- **ISO version**: v0.23.6

**What happened**:
Mounted directory is empty on the minikube machine but no errors are visible

**What you expected to happen**:
Minikube should show an error (and preferably exit)

**How to reproduce it**:
Run `minikube mount -v10 C:\my-project:/projects/my-project`

```
Mounting C:\my-project into /projects/my-project on the minikube VM
This daemon process needs to stay alive for the mount to still be accessible...
ufs starting
```
Sometimes minikube fails to create the mount properly, but there's no indication of this from the command unless you run in verbose mode, e.g. `minikube mount -v10 .....`

It should display an error message and probably exit as it doesn't seem to retry at all.

**Comment by cz8s** [comment]
I had the same problem.
Realized it was the firewall on my mac that dropped the connection.
But the line on how to reproduce really helped finding the issue. <3

**Comment by marburps** [comment]
I have the same issue on Windows 10 OS.
