### ISSUE TITLE
minikube ingress addon deletes user configuration

### ISSUE THREAD

**Issue by bryanlarsen** [kubernetes/minikube#2531]
To reproduce:

`kubectl -n kube-system edit cm nginx-load-balancer-conf`

make some changes, for instance, set "hsts": "false".

Restart.

Notice changes are gone.   Swear loudly.

The ingress addon isn't configurable either.

The helm chart works and is properly configurable.

**Comment by r2d4** [comment]
The ingress addon configmap happens to be named the same as yours ,`nginx-load-balancer-conf`.  We should probably update it to be prefixed with `minikube-` so this doesnt happen in the future.

**Comment by r2d4** [comment]
https://github.com/kubernetes/minikube/blob/master/deploy/addons/ingress/ingress-configmap.yaml

**Comment by bryanlarsen** [comment]
You're setting the --configmap parameter on the ingress controller to point to your configuration.   So editing your configuration is the only way to change the configuration of the ingress controller.

**Comment by r2d4** [comment]
Looks like I came to the same conclusion before but never fixed it, sorry about that.

dupe of https://github.com/kubernetes/minikube/issues/2165
PR with fix https://github.com/kubernetes/minikube/pull/2537
