### ISSUE TITLE
Post v0.24.1 release tag is missing Windows binary checksum

### ISSUE THREAD

**Issue by budhram** [kubernetes/minikube#2536]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUD REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): Post `v0.24.1`.

**What happened**:

The checksum of Windows binary is missing from release page.
See 
![screenshot from 2018-02-10 13-58-26](https://user-images.githubusercontent.com/1132451/36060218-1545d8c8-0e6b-11e8-9ae2-986a3ba82c00.png)

**What you expected to happen**:

The checksum of Windows binary should present in release page.

/cc Any idea @r2d4 what had happened here?

**Comment by afbjorklund** [comment]
Looks like https://github.com/kubernetes/minikube/blob/master/hack/jenkins/release_github_page.sh#L115

The checksum is available in the README, just that the sha256 file is never uploaded and .exe is missing?

**Comment by budhrg** [comment]
> The checksum is available in the README, just that the sha256 file is never uploaded and .exe is missing?

Same case with newly released v0.25.2 https://github.com/kubernetes/minikube/releases/tag/v0.25.2

**Comment by pxlphile** [comment]
Hi Minikube Team, this issue is still current. I would like to download the checksums as well as the binary for Windows from the release page and compare hashes afterwards. I would really like to avoid to parse READMEs.

Is there a way I can help with this issue?
