### ISSUE TITLE
dashboard as root: Unsupported authorisation protocol / cannot open display: localhost:10.0

### ISSUE THREAD

**Issue by farooqte96** [kubernetes/minikube#2548]
Hi i just installed minikube on a remote linux machine (Ubuntu 16.04 server version). I am able to start minikube but to see running deployments, **minikube dashboard** command is  reporting some errors like unsupported authorization protocol, missing modules (chrome browser, mozilla etc.). Can anyone tell me how to fix this issue so i can see dashboard on my local pc by accessing : http://192.140.127.45:30000

minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.140.127.45
kubectl cluster-info
Kubernetes master is running at https://192.140.127.45:8443
**root@yx-lab2: minikube dashboard**

Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Opening kubernetes dashboard in default browser...
MobaXterm X11 proxy: Unsupported authorisation protocol
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Broadway display type not supported: localhost:10.0
Error: cannot open display: localhost:10.0
MobaXterm X11 proxy: Unsupported authorisation protocol
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Broadway display type not supported: localhost:10.0
Error: cannot open display: localhost:10.0
MobaXterm X11 proxy: Unsupported authorisation protocol
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Broadway display type not supported: localhost:10.0
Error: cannot open display: localhost:10.0
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: chromium-browser: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: google-chrome: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 771: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://192.140.127.45:30000'

minikube version: v0.25.0
cat /etc/os-release 
NAME="Ubuntu"
VERSION="16.04.3 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.3 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

grep DriverName ~/.minikube/machines/minikube/config.json
    "DriverName": "none",

**Comment by dlorenc** [comment]
What browser do you have installed? The minikube dashboard command works by calling "xdg-open" with the correct URL, which is supposed to open your browser to the right page. 

From that error, it looks like xdg-open is trying to open many different browsers but is unable to find any installed ones.

**Comment by farooqte96** [comment]
Thanks @dlorenc for addressing my query. I am using firefox. I reinstalled it and after some troubleshooting i am able to get minikube dashboard command running correctly but in browser dashboard is not shown instead "unable to connect" message is displayed on http://195.148.127.245:30000/. It also returns some error messages related to permission of configuration files. Do you understand whats the issue here?

minikube dashboard
Waiting, endpoint for service is not ready yet...
Opening kubernetes dashboard in default browser...
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/tufailm1/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/tufailm1/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied

![minikube](https://user-images.githubusercontent.com/29800341/36283770-25d6d9f2-12ae-11e8-9983-aa489ee58260.png)

**Comment by pavankjadda** [comment]
I too have the same issue

**Comment by steventarver** [comment]
I am seeing this issue as well on Macbook Pro (latest 10.13..3) - with k8s version 1.7.5. I updated VirtualBox to latest, deleted ~/.minikube, and downloaded v0.25.2.

```bash
ᐅ minikube start --kubernetes-version v1.7.5
#...
ᐅ kubectl get pods --all-namespaces
NAMESPACE     NAME                          READY     STATUS    RESTARTS   AGE
kube-system   kube-addon-manager-minikube   1/1       Running   0          35m
kube-system   kube-dns-3693656504-0zvlq     3/3       Running   0          35m
ᐅ minikube addons list
- addon-manager: enabled
- coredns: disabled
- dashboard: enabled
- default-storageclass: enabled
- efk: disabled
- freshpod: disabled
- heapster: disabled
- ingress: disabled
- kube-dns: enabled
- registry: disabled
- registry-creds: disabled
- storage-provisioner: enabled
ᐅ minikube addons enable dashboard
dashboard was successfully enabled
ᐅ kubectl get pods --all-namespaces
NAMESPACE     NAME                          READY     STATUS    RESTARTS   AGE
kube-system   kube-addon-manager-minikube   1/1       Running   0          36m
kube-system   kube-dns-3693656504-0zvlq     3/3       Running   0          36m
ᐅ minikube dashboard
Waiting, endpoint for service is not ready yet...
#...
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
```

In earlier minikube versions - I would clearly see the dashboard pod listed in kubectl.
Haven't found any dashboard mentions, or other interesting things in the minikube logs.
I `minikube delete` and then started v1.9.4 and the dashboard worked fine.
Still scratching head...
Hope this info helps

**Comment by RobertDiebels** [comment]
Same issue.

Driver: HyperV
Minikube version: v0.25.0

Command executed: `minikube dashboard`

**Comment by Ankk98** [comment]
I am also getting similar error:

```
Waiting, endpoint for service is not ready yet...
Opening kubernetes dashboard in default browser...
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by ankk98.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by ankk98.)
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /run/user/1000/gdm/Xauthority which is owned by ankk98.)
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: chromium-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: google-chrome: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 851: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://192.168.99.100:30000'
root@ankk98-linux:/home/ankk98# minikube stop
Stopping local Kubernetes cluster...
Machine stopped.
```
I think this might be because i am doing this as a superuser.
But to run docker I needs to be superuser according to my knowledge.
I am a beginner so I might have wrong knowledge.
Help!

**Comment by Ankk98** [comment]
Yeah
Found the problem!
Actually, I was running my terminal as a superuser so my it was not able to access browsers.
Running as a simple user solved the issue.

Also 
The issue of "Waiting, the endpoint for service is not ready yet..." was because it node not started.
So you need to wait for some time depending on the system and try again to solve this problem.
Meanwhile, you can check
`kubectl get pod`
Wait until the you see it running and check again.

**Comment by ml1268** [comment]
**Environment:**

- Minikube version : v0.28.1
- OS : Darwin 17.7.0 Darwin Kernel Version 17.7.0 RELEASE_X86_64 x86_64
- VM Driver : virtualbox
- ISO version : v0.28.1

**Issue**
dashboard is not work
```

host$ minikube dashboard
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
```
**What you expected to happen:**
get it to work.

**How to reproduce it :**
1. git clone https://github.com/kubernetes/minikube
2. mv ./minikube $GOPATH/src/k8s.io/minikube && cd $GOPATH/src/k8s.io/minikube
3. git checkout aliyun-v0.28.1
4. make
5. minikube start

**Output of minikube logs:**

```
Sep 17 08:11:41 minikube kubelet[2830]: E0917 08:11:41.106207    2830 pod_workers.go:186] 
Error syncing pod 0eee2be7-ba1f-11e8-8cad-080027e3272d ("kubernetes-dashboard-685cfbd9f6-px2t4_kube-system(0eee2be7-ba1f-11e8-8cad-080027e3272d)"), 
skipping: failed to "StartContainer" for "kubernetes-dashboard" with CrashLoopBackOff: "Back-off 5m0s restarting failed 
container=kubernetes-dashboard pod=kubernetes-dashboard-685cfbd9f6-px2t4_kube-system(0eee2be7-ba1f-11e8-8cad-080027e3272d)"

```

**Anything else:**

```
host$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS             RESTARTS   AGE
default       nginx-6778d667d5-4mxpj                  1/1       Running            0          32m
default       nginx-6778d667d5-bmhxl                  1/1       Running            0          14m
default       nginx-6778d667d5-pc5hz                  1/1       Running            0          14m
kube-system   etcd-minikube                           1/1       Running            0          5h
kube-system   kube-addon-manager-minikube             1/1       Running            0          5h
kube-system   kube-apiserver-minikube                 1/1       Running            0          5h
kube-system   kube-controller-manager-minikube        1/1       Running            0          6h
kube-system   kube-dns-b4bd9576-rn772                 3/3       Running            0          6h
kube-system   kube-proxy-n2vsz                        1/1       Running            0          6h
kube-system   kube-scheduler-minikube                 1/1       Running            0          5h
kube-system   kubernetes-dashboard-685cfbd9f6-px2t4   0/1       CrashLoopBackOff   26         6h
kube-system   storage-provisioner                     1/1       Running            0          6h


```
```
host$ kubectl get deployments --all-namespaces
NAMESPACE     NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
default       nginx                  3         3         3            3           41m
kube-system   kube-dns               1         1         1            1           6h
kube-system   kubernetes-dashboard   1         1         1            0           6h

```

**Comment by tstromberg** [comment]
Closing due to user error, but this is really our fault for not mentioning early that minikube should not be run as root. Opened #3138 to address that.
