### ISSUE TITLE
Minikube 0.25 - Ubuntu 17.10 - Unable to stop minikube

### ISSUE THREAD

**Issue by stephenpope** [kubernetes/minikube#2549]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: Ubuntu 17.10 running in HyperV

**Minikube version** : v0.25.0
- **OS**: Ubuntu 17.10 (Artful Aardvark)
- **VM Driver** : none
- **ISO version**: Not found
- **Install tools**: None
- **Others**:

**What happened**:
```
sudo minikube stop
Stopping local Kubernetes cluster...
Error stopping machine:  Error stopping host: minikube: Failed to stop localkube\x2c.service: Unit localkube\x2c.service not loaded.
Failed to stop kubelet.service: Unit kubelet.service not loaded.
: exit status 5
```
**What you expected to happen**:

Stop the cluster.

**How to reproduce it** (as minimally and precisely as possible):
```
(fresh from Ubuntu Server 17.10 Iso Install + apt-get dist-upgrade + sudo reboot)
curl -fsSL get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo usermod -aG docker your-user

curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl

sudo mv kubectl /usr/local/bin/

export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true
mkdir $HOME/.kube || true
touch $HOME/.kube/config

export KUBECONFIG=$HOME/.kube/config
sudo -E minikube start --vm-driver=none
sudo minikube stop
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

Ubuntu VM is inside HyperV on Windows10

**Comment by stephenpope** [comment]
This fixed the issue. Thank you for the quick work ! :)

**Comment by AGutan** [comment]
@stephenpope did you build the minikube with the updated pr yourself? to get the update. 
i.e. how did you update the minikube with the fix?

**Comment by stephenpope** [comment]
@AGutan I found you can download builds of specific checkins from the CI so I grabbed the #2550 fix from : https://storage.googleapis.com/minikube-builds/2550/minikube-linux-amd64

**Comment by ctyjrsy** [comment]
sorry I am new to this whole ecosystem, where do you put the binary once you download? in the path?

**Comment by tebb** [comment]
@ctyjrsy

The following worked for me on Ubuntu 16.04.

You may need to prefix some commands with 'sudo' and supply your password if you get permissions problems.

1) Find where your existing minikube executable/binary is using something like:

locate minikube
or
which minikube

My minikube was in /usr/local/bin directory.

2) Save that existing minikube executable binary, for example:

cd /your-to-your-directory-containing-minikube
mv minikube minikube.wontStop

3) Download the patched binary into the same directory (which is probably in your path) from the link given by @stephenpope (Thank you)

cd /path-to-your-directory-containing-minikube
wget https://storage.googleapis.com/minikube-builds/2550/minikube-linux-amd64    (or use curl)
mv minikube-linux-amd64 minikube

4) Make the file executable (if not already)

chmod +x minikube

5) Check if minikube will stop now.

minikube stop

**Comment by cog-qlik** [comment]
I'm still getting this error even with `v0.25.2`. I rolled back to the version posted above by @stephenpope and it started working again.

**Comment by vikkio88** [comment]
@tebb solution worked for me on ubuntu16.04

**Comment by georgecrawford** [comment]
I'm also seeing this in v0.25.2. @dlorenc Can you confirm that your fix is working and is included in this latest release? Thanks.

**Comment by daniel347x** [comment]
Just mentioning that without the patched version linked by @tebb, minikube is unusable for me.  I hope this fix is pushed out urgently.

**Comment by wi-ski** [comment]
I would really like this to happen ASAP. Thank you all :)

**Comment by wi-ski** [comment]
Please <3

**Comment by pilchkinstein-gtv** [comment]
@stephenpope / @tebb solution also worked for me on ubuntu16.04 - I was unable to start the cluster without this patched version
