### ISSUE TITLE
Problems setting option max-concurrent-uploads for the docker daemon

### ISSUE THREAD

**Issue by TobiasXy** [kubernetes/minikube#2557]
**BUG REPORT**

**Environment**:

- **Minikube version**: v0.25.0
- **OS**: Windows 10
- **VM Driver**: hyperv
- **ISO version**: v0.23.6

**What happened**:
I am reusing the docker daemon of minikube using `minikube docker-env | Invoke-Expression` in the Windows Powershell. Today I tried to `docker push` an image to my remote repository.
It didn't really work, probably because my upload speed isn't that great (I first found this issue: [docker push uses too much of my bandwidth](https://github.com/moby/moby/issues/13342) ). Because of that I tried to find a way to set the option "max-concurrent-uploads" for the docker daemon as suggested in one of the last comments there.

As I understood it, for the minikube docker daemon you can use the --docker-opt argument of the `minikube start` command to set options like that (am I wrong?).

So I stopped minikube (`minikube stop`) and started it again with the following command; `minikube start --vm-driver hyperv --hyperv-virtual-switch "Minikube" --alsologtostderr --docker-opt max-concurrent-uploads=1` (the only change is the added `--docker-opt max-concurrent-uploads=1`).

**What you expected to happen**:

The command seems to succeed and minikube starts normally. But when I run `docker push` again it still tries to upload multiple layers at once and if I run `minikube ssh` followed by `ps aux | grep docker` I get that output (truncated to the probably relevant line):

> root      2688  0.8  2.8 677544 58156 ?        Ssl  19:31   0:16 /usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=hyperv --insecure-registry 10.96.0.0/12

**How to reproduce it** (as minimally and precisely as possible):

1. Start minikube on Windows with `--docker-opt max-concurrent-uploads=1` option
2. In the powershell run `minikube docker-env | Invoke-Expression`
3. Run `docker push some.remote.repo/some/image`
4. Watch docker try to upload multiple layers at once

**Anything else do we need to know**:

It is totally possible that I misundestood something or used something incorrectly, but right now it seems to be a minikube bug to me(?)

**Comment by remoe** [comment]
"--docker-opt max-concurrent-uploads=1" works with minikube 0.29.
