### ISSUE TITLE
Docs: incorrect command argument in /docs/networking.md

### ISSUE THREAD

**Issue by alimac** [kubernetes/minikube#2559]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**What happened**:

In the Networking FAQ - https://github.com/kubernetes/minikube/blob/master/docs/networking.md - the following command is listed:

```
kubectl get service $SERVICE --output='jsonpath="{.spec.ports[0].NodePort}"'
```

It uses the `NodePort` attribute, but in JSON output this attribute is `nodePort`, so the output is `""` instead of being the port number.

This is a small thing, but as a new user, it tripped me up. Happy to submit a PR with a fix.

**Comment by r2d4** [comment]
We'd happily accept any documentation fixes like this!
