### ISSUE TITLE
Change in behavior of minikube for certificate generation

### ISSUE THREAD

**Issue by ahawtho** [kubernetes/minikube#2560]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: CoreOS vbox guest on MacOS host

**Minikube version** (use `minikube version`): v0.25.0
- **OS** (e.g. from /etc/os-release):
    NAME="Container Linux by CoreOS"
    ID=coreos
    VERSION=1649.0.0
    VERSION_ID=1649.0.0
    BUILD_ID=2018-01-05-0906
    PRETTY_NAME="Container Linux by CoreOS 1649.0.0 (Ladybug)"
    ANSI_COLOR="38;5;75"
    HOME_URL="https://coreos.com/"
    BUG_REPORT_URL="https://issues.coreos.com"
    COREOS_BOARD="amd64-usr"
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): N/A
- **Install tools**:
- **Others**:

**What happened**: We have a scripted install for onboarding developers. Minikube doesn't support a predictable, fixed IP address for the guest VM, but we use a fixed IP address so we can provide DNS names for easier routing to apps in the cluster. With v0.24.1, our script would successfully install minikube on the guest, map the guest port 8443 to the host and developers could connect to their cluster with kubectl using the generated kubeconfig from minikube. With v0.25.0, the setup completes successfully, but when developers try to connect to the cluster with kubectl, they receive invalid certificate errors. 

**What you expected to happen**: We expected kubectl to connect to the cluster without any certificate errors.

**How to reproduce it** (as minimally and precisely as possible): I'll run through these steps to ensure they reproduce, but it should be relatively straightforward:
1. Install [vagrant](https://www.vagrantup.com/intro/getting-started/install.html)
2. Clone the [coreos-vagrant repository](https://github.com/coreos/coreos-vagrant)
3. Copy the config.rb.sample to config.rb and add the following lines to the config.rb file:

````
$share_home=true
$forwarded_ports = { 8443 => 8443 }
````

4. Run 'vagrant up' in the coreos-vagrant directory
5. Run 'vagrant ssh' in the coreos-vagrant directory
6. On the CoreOS guest, download the minikube executable
7. Use the 'none' vm-driver to install minikube.
8. Copy the resulting minikube kubeconfig to your home directory on your host (the dir should be shared on the guest).
9. Exit from the CoreOS guest
10. Run kubectl --kubeconfig=```<minikube kubeconfig>``` get pods --all-namespaces

I think you'll see a certificate error. If you do these steps with v0.24.1 of minikube, I think you'll be able to list the pods.

**Output of `minikube logs` (if applicable)**: N/A

**Anything else do we need to know**:
We believe the reason for the change of behavior is because of [this commit](https://github.com/kubernetes/minikube/commit/fcdd1404e877c0a40ff68576cefbbf2162a64b9e) . GetIP() used to return the 127.0.0.1 address, which is what minikube would use when creating the certificates. When it was changed to return the result of calling GetIP(), it began returning one of the IP addresses of one of the interfaces on our guest. We're using VirtualBox, which in our case, has a NAT interface, through which all external traffic is routed, and a "host-only" interface, which is how our host communicates to the guest. The problem is that GetIP() returns the IP of the NAT interface due to its association with the default gateway route, and VirtualBox networking does not allow the host to communicate to the IP of the NAT interface.

My understanding is that this was done to become compatible with kubeadm. I'd like to support that change, so I don't want to do anything to undermine it here. It's not immediately clear to me how the changes I'm suggesting below would affect that work, but I'm hoping you can offer some insight/guidance on that.

One way to address our issue for us is to allow an env var or minikube option to specify the IP returned by GetIP, and return that from GetIP() instead of invoking ChooseBindAddress() [on line 76](https://github.com/kubernetes/minikube/blob/fcdd1404e877c0a40ff68576cefbbf2162a64b9e/pkg/drivers/none/none.go#L76) .

Another possible solution is to add the IP address associated with all local interfaces to the certificate, including the loopback. I believe this might be the most backwards compatible.

If either of those or another idea sounds like a reasonable approach, one of our team can write up the change.

**Comment by r2d4** [comment]
Can you elaborate on why you're using the none driver instead of kubeadm directly?

**Comment by ahawtho** [comment]
Mostly development inertia combined with a limited amount of project development. We had initially begun development with minikube while kubeadm was still quite new. We were hoping to remain on the most current version of minikube, but this change in behavior makes it difficult.
