### ISSUE TITLE
minikube using hyperkit fails to restart on macOS due to stale PID-file after a reboot/shutdown

### ISSUE THREAD

**Issue by ssdowd** [kubernetes/minikube#2561]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: macOS Sierra 10.12.6

**Minikube version** (use `minikube version`): v0.25.0
- **OS** (e.g. from /etc/os-release): macOS Sierra 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.25.1.iso
- **Install tools**: N/A (homebrew)
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:  Run `minikube -p proj start --log_dir /Users/XXX/.minikube/logs --loglevel 0  --vm-driver=hyperkit --memory 6144`.  Never completes (waited 45 minutes). Output is
```
Starting local Kubernetes v1.9.0 cluster...
Starting VM...
```

**What you expected to happen**: return with a shell prompt and have `minikube -p proj status` return Running instead of Stopped

**How to reproduce it** (as minimally and precisely as possible): Reboot mac while minikube is running, then do the start command above.

**Output of `minikube logs` (if applicable)**:
does not return anything, also hangs.  Log file (~/.minikube/logs/minikube.[hostname].[user].log.INFO.[timestamp]) contains:
```
I0221 09:34:16.706330   48704 cluster.go:74] Skipping create...Using existing machine configuration
I0221 09:34:16.706963   48704 cache_images.go:79] Successfully cached all images.
I0221 09:34:16.963453   48704 cluster.go:83] Machine state:  Stopped
```

**Anything else do we need to know**:

**Comment by blaketastic2** [comment]
I'm seeing the same thing. Restarting mac while minikube is running is exactly the steps I used to reproduce. If I "minikube stop" before the restart, everything is fine. There seems to be no way to recover other than blasting away the minikube envrionment.

**Comment by stevesloka** [comment]
I found if you use Virtualbox driver it works fine, not sure what's specific to Hyperkit, but now my minikubes survive reboots.

**Comment by lowang-bh** [comment]
I'm seeing the same thing. Restarting mac while minikube is running is what I usually do, and it hang every time. If I "minikube stop" before the restart, everything is fine.

**Comment by stevesloka** [comment]
Still an issue!

**Comment by TimZaman** [comment]
same here

**Comment by viteksafronov** [comment]
The issue is caused by stale hyperkit.pid file which is not removed if machine was rebooted without `minikube stop` command. Removing this file allows to start VM.

**Comment by gbraad** [comment]
Just like I added this to the xhyve driver, it should check on startup for the existence of this file and verify if the current process matches the name of the PID found. This is what caused issues for xhyve, as the PID was an actual running process, just not the same/related.

**Comment by aashish-chaubey** [comment]
@ssdowd Any solution on this, I am still facing this issue!
Please help.

**Comment by ssdowd** [comment]
@aashish-chaubey I gave up on minikube/hyperkit and switched to docker desktop for mac.

**Comment by aashish-chaubey** [comment]
@ssdowd I figured out the solution to this in my case. I was behind a firewall, just disabled it and it worked!
