### ISSUE TITLE
Query service url by service, port

### ISSUE THREAD

**Issue by unixunion** [kubernetes/minikube#2567]
FEATURE REQUEST

Sometimes services expose multiple ports, and I would like to query the service url for a known spec.port by adding a --port option to service cmd which returns the Service url for the specified spec.Port. e.g

    $> minikube service myservice --port 8080 --url
    http://192.168.99.103:31604
    
**Environment**: OSX

**Minikube version**: v0.25.0
- **OS** MacOSX 10.11
- **VM Driver** virtualbox:
- **ISO version** v0.25.0
- **Install tools**:
- **Others**:

**Anything else do we need to know**:

I have implemented this in a feature [here](https://github.com/unixunion/minikube). I have added a new argument int32 port, which should be 0 to preserve the current behavior, and if non-zero, will return service URL(s) where spec.Port == port. 

Additionally, my services are not always HTTP, so would it be beneficial to anyone to also add a --suppress-http arg to just get IP:PORT? I use minikube for spinning up dependencies for integration-tests, hence the need to query for a specific service.

**Comment by hal58th** [comment]
I agree with all of your points and also don't have just HTTP or HTTPS services.

**Comment by tstromberg** [comment]
@unixunion - This sounds good. I would be happy to review any pull request you have.
