### ISSUE TITLE
Minikube release with 1.9.3

### ISSUE THREAD

**Issue by ryanmcnamara** [kubernetes/minikube#2576]
Would be nice to get a minikube release that uses a later mainline kubernetes version than 1.9.0 (released 2 months ago). 
1.9.3 is the latest at this time.

In general, how much is minikube expected to lag mainline kubernetes?

**Comment by dlorenc** [comment]
Hey,

Yeah we definitely need to get a 1.9.3 build out. Sorry for the delay!
