### ISSUE TITLE
localkube consumes a lot ram and file descriptors (leak?) 

### ISSUE THREAD

**Issue by codr1** [kubernetes/minikube#2579]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**minikube version: v0.25.0** 
- **NAME="CentOS Linux VERSION="7 (Core)"** 
- **VM Driver** : none
- **ISO version**: NA
**What happened**:
I tried starting minikube with some very basic params

minikube start --memory 1024 --vm-driver none --disk-size 5G 

Within 5 minutes, I see this in top
23274 root      20   0 17.053g 3.299g  12408 S  25.2 89.1   5:52.27 localkube      

if I let it go, it will invoke the OOM killer shortly.  The VM we are running on has 4Gigs of RAM.

**What you expected to happen**:
I expect to use less RAM.  Even the Virtual memory allocation - starting at 10G and exploding from there looks like an overkill.

**How to reproduce it** (as minimally and precisely as possible):
This is a fresh install.  Nothing fancy.

**Comment by codr1** [comment]
I see errors like this in the logs.  Lots of them.:

Unable to read manifest path "/etc/kubernetes/manifests": unable to create inotify: inotify_init: too many open files

ulimit -a says:
[root@localhost ~]# ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 31206
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 65535
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 65535
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited

**Comment by codr1** [comment]
Some lsof debugging later and it is certain that it is locakube that is eating all these file descriptors...

**Comment by codr1** [comment]
OK.  So we are down to this:
Feb 27 18:26:15 localhost.localdomain localkube[640]: kubelet: Exit with error: failed to run Kubelet: failed to create kubelet: misconfiguration: kubelet cgroup driver: "cgroupfs" is different from docker cgroup driver: "systemd"

I added the following to the startup line of localkube.service file.  No dice
--extra-config=kubelet.CgroupDriver=systemd

**Comment by codr1** [comment]
...no.  Actually it is now fixed.  However if you delete minikube and then start it again - the file gets reset.  I think this is a bug that really needs to be fixed.

**Comment by dlorenc** [comment]
Thanks for the detailed debugging! To be clear, the "kubelet.Cgroupdriver=systemd" flag fixed this for you? We should be able to hardcode that in the localkube setup here easily enough: https://github.com/kubernetes/minikube/blob/master/pkg/localkube/kubelet.go#L42

Would you like to send a PR?

**Comment by dlorenc** [comment]
Wait, actually I just saw that you're using the none driver, so it's likely that this is caused by a mismatch in the way docker is configured on your host and the way it normally runs in the stanard minikube ISO. (the docker cgroup driver).

In this case the best fix may just be documentation. We can't support every possible host configuration with the none driver automatically, that's what --extra-config is for.

**Comment by codr1** [comment]
@dlorenc  - you are right.  I have setup my own KVM running Centos7 (common enough setup).  I don't know much about the source.  But can you do something like 
`docker info |grep -i cgroup 
and get the driver?   

I will try to see if I can hack something over the weekend, but your input would be appreciated.
