### ISSUE TITLE
minikube start on vmware fusion hangs 

### ISSUE THREAD

**Issue by weaselchops** [kubernetes/minikube#2581]
**BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** : version: v0.25.0
- **OS** : Sierra 10.12.6
- **VM Driver** : vmwarefusion
- **ISO version** : v0.25.1
- **Install tools**: brew
- **Others**:

**What happened**:
New install from brew hangs/takes a very long time "**executing:**"
```
$ minikube -v10 start --vm-driver=vmwarefusion

#### Snipped ####

Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet2.leases
Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
IP found in DHCP lease table: 192.168.164.228
Got an ip: 192.168.164.228
Creating Tar key bundle...
executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser directoryExistsInGuest /Users/$USER/.minikube/machines/minikube/minikube.vmx /var/lib/boot2docker
executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser CopyFileFromHostToGuest /Users/$USER/.minikube/machines/minikube/minikube.vmx /Users/$USER/.minikube/machines/minikube/userdata.tar /home/docker/userdata.tar
executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser runScriptInGuest /Users/$USER/.minikube/machines/minikube/minikube.vmx /bin/sh sudo sh -c "tar xvf /home/docker/userdata.tar -C /home/docker > /var/log/userdata.log 2>&1 && chown -R docker:staff /home/docker"
```
The "executing:" task seem to be moving...but is taking nearly 30 mins so far!

**What you expected to happen**:
CPU and memory are fine. Can't see any load
**How to reproduce it** (as minimally and precisely as possible):
Tried Vmware fusion version 7 and 10
minikube -v10 start --vm-driver=vmwarefusion
**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
I have done a "rm -rf .minikube/" and tried again... same result

**Comment by weaselchops** [comment]
[fulllog.txt](https://github.com/kubernetes/minikube/files/1763990/fulllog.txt)
Full v10 log attached

**Comment by weaselchops** [comment]
After nearly 40 minutes!!! ...
`executing: /Applications/VMware Fusion.app/Contents/Public/vmrun -gu docker -gp tcuser runScriptInGuest /Users/nigelc/.minikube/machines/minikube/minikube.vmx /bin/sh [ ! -d /Users ]&& sudo mkdir /Users; sudo mount --bind /mnt/hgfs//Users /Users || [ -f /usr/local/bin/vmhgfs-fuse ]&& sudo /usr/local/bin/vmhgfs-fuse -o allow_other .host:/Users /Users || sudo mount -t vmhgfs -o uid=$(id -u),gid=$(id -g) .host:/Users /Users
executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
setting hostname "minikube"
executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
MAC address in VMX: 00:0c:29:25:27:8c
Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet1/dhcpd.conf
Following IPs found map[00:50:56:c0:00:01:192.168.52.1]
Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet2/dhcpd.conf
Following IPs found map[00:50:56:c0:00:02:192.168.135.1]
Trying to find IP address in configuration file: /Library/Preferences/VMware Fusion/vmnet8/dhcpd.conf
Following IPs found map[00:50:56:c0:00:08:192.168.164.1]
Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet1.leases
Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet2.leases
Trying to find IP address in leases file: /var/db/vmware/vmnet-dhcpd-vmnet8.leases
IP found in DHCP lease table: 192.168.164.228
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x1437850] 0x1437800  [] 0s} 192.168.164.228 22 <nil> <nil>}
About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Error dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

**Comment by weaselchops** [comment]
Looks a bit like #2126 But was meant to be fixed.

**Comment by mikeroySoft** [comment]
Does the VM have connectivity / an IP if you open up the console from the Fusion UI?
Also, try bouncing the network services:

cd /Applications/VMware\ Fusion.app/Contents/Library/
./vmnet-cli --stop
./vmnet-cli --configure
./vmnet-cli --start

**Comment by weaselchops** [comment]
From the console I could see I had an IP, which I could ping from the host.
Did a stop/reconfigure/start.. some problem.
The vmrun is still taking forever....and fails with ssh key issue

**Comment by weaselchops** [comment]
Digging a bit deeper....
`$ /Applications/VMware\ Fusion.app/Contents/Public/vmrun -T fusion -gu docker -gp tcuser runScriptInGuest /Users/$USER/.minikube/machines/minikube/minikube.vmx /bin/sh "/bin/ls"
Error: The VMware Tools are not running in the virtual machine: /Users/nigelc/.minikube/machines/minikube/minikube.vmx`

I saw this myself with Vagrant recently: https://github.com/hashicorp/vagrant/issues/9004
The bento/centos-7 image had a fix. More info here: https://github.com/chef/bento/issues/747 (but not sure if relevant)

Also if I log onto the Kube image and try starting vmtoolsd manually, causes a core dump!
same with a systemctl restart

**Comment by mshahat** [comment]
a similar observation here!

**Comment by tstromberg** [comment]
This looks to be a dupe of #2126
