### ISSUE TITLE
minikube not added to PATH: installer uses setx.exe which runcates PATHs longer than 1024 chars

### ISSUE THREAD

**Issue by mmckenz** [kubernetes/minikube#2587]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.25.0
- **OS** (e.g. from /etc/os-release): Windows 10 Enterprise
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.25.1.iso
- **Install tools**: Windows Installer
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**: Installed minikube using the Windows Installer. The update_path.bat script used setx.exe to add minikube's installation path to my system PATH variable. My system PATH is over 1024 chars long so setx.exe destructively truncated it. I had to restore my system PATH from registry backups.

**What you expected to happen**: minikube is installed without destructively changing my system PATH.

**How to reproduce it** (as minimally and precisely as possible): Start with a system PATH environment variable > 1024 chars. Run the minikube Windows installer.

**Output of `minikube logs` (if applicable)**: N/A

**Anything else do we need to know**: N/A

**Comment by stefanjarina** [comment]
Same happened to me:

**Minikube version**: 0.28.2
- **OS**: Windows 10 Pro 1803 (OS build 17134.228)
- **VM Driver**: Hyper-V

I use a PATH in windows that is rather modular, e.g.:
```
PATH = C:\Windows;C:\Windows\system32;%PATH_TOOLS_MS%;%PATH_TOOLS_HW;%PATH_TOOLS_CODE%
PATH_TOOLS_MS = C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x64;
PATH_TOOLS_HW = C:\Program Files\Razer Chroma SDK\bin;C:\Program Files (x86)\Razer Chroma SDK\bin;C:\Program Files\Intel\iCLS Client\;
PATH_TOOLS_CODE = C:\Python37-32\Scripts\;C:\Python37-32\;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\erl9.2\bin;C:\Program Files (x86)\Elixir\bin;C:\Program Files\heroku\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files\Microsoft VS Code\bin;D:\Programy\ngrok;C:\vagrant\bin;C:\PostgreSQL\pg10\bin;E:\Programy\kotlin-compiler-1.2.61\kotlinc\bin;C:\Go\bin;C:\Program Files\MariaDB 10.3\bin;C:\kubernetes\minikube\bin;
```
etc. This is basically to avoid PATH longer than 4096 characters which is not working on Windows...

After running the minikube-installer.exe I spent some time debugging why my system is not working properly only to discover in huge shock that it efectivelly destroyed my PATH and it converted it to something like:
```
PATH = C:\Windows;C:\Windows\system32;C:\Python37-32\Scripts\;C:\Python37-32\;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\PuTTY\;C:\Program Files\dotnet\;C:\Program Files\Git\cmd;C:\Program Files\R
```
Didn't even add minikube installation into PATH.
It also removed the references to variables (%PATH_TOOLS_***%) as an addition to truncating part of my PATH, so it seems it first extends the PATH to it's full form, then truncate it (WHAT???)

If I wouldn't have PATH split into smaller variables, installer would wipe 3/4 of my PATH and I would have to play with registries to fix it...
Thankfully for me it only destroyed the variable references and thus I was able to reconstruct PATH easily...

**Comment by tstromberg** [comment]
AFAIK, this is still an issue. I'd be happy to approve any PR's which fix the behavior though. Help wanted!

**Comment by tstromberg** [comment]
Some more context:

https://superuser.com/questions/387619/overcoming-the-1024-character-limit-with-setx

The file that needs to be modified is installers/windows/update_path.bat. It's unclear which approach is the most sane one, as they all seem to require an additional dependency.

**Comment by Vaskinn** [comment]
A good temporary fix, probably without introducing dependencies, would be to detect when the path will be to long, and not try to set it but instead show instructions on what to add manually to the path. 
That will prevent the installer from destroying the system of people that have a long path.

**Comment by ssargent** [comment]
Is this still a thing?  I know as of 0.35 it was, but was this fixed in 1.0.0?  I didn't use the installer for that.  Would it be possible to use powershell for this on windows?  I'm not sure if that gets around the problem somehow, or if that falls under the category of additional dependencies.  But I'm happy to look into it if that's possibly in play.

**Comment by tstromberg** [comment]
@ssargent - Yes, this is still a thing that exists. Patches are very welcome for this issue. Let me know if I can help in any way.

**Comment by blueelvis** [comment]
@tstromberg - I will pick this up. Instead of using a Batch file for Windows, cannot we incorporate a PowerShell file? PowerShell is installed on all systems by default from Windows 7+

Also, I couldn't find any documentation on the minimum requirement of Windows Operating System for Minikube (I believe it is Windows 8+ as per [here](https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/tools/install-minikube.md). There is a line which says that).

Additionally, I couldn't find any documentation on how the installers are generated?

**Comment by tstromberg** [comment]
@blueelvis - Thanks! My preference would be to continue to support Windows 7 and higher if possible. 

https://github.com/kubernetes/minikube/tree/master/installers/windows contains the code used in the installer.

https://github.com/kubernetes/minikube/blob/master/Makefile#L288 shows the steps used to make the installer. 

I very much look forward to your PR!
