### ISSUE TITLE
localkube failed pulling image: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by land-pack** [kubernetes/minikube#2592]
**FEATURE REQUEST** :

  I try to follow the official [documentation](https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/), when I try to following command , its get me a error as title.

**Environment**:

**Minikube version** (use `minikube version: v0.25.0`):
- **OS** (OS X 10.13.3):
- **VM Driver** ("DriverName": "virtualbox"):
- **ISO version** ("Boot2DockerURL": "file:///Users/frank/.minikube/cache/iso/minikube-v0.25.1.iso",):
- **Install tools** (brew install XXX):
- **Others**:

**What happened**:

**What you expected to happen**:
I should see my dashboard by visit http://127.0.0.1:9090

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

> Mar 08 07:46:13 minikube localkube[13195]: E0308 07:46:13.792574   13195 kuberuntime_manager.go:647] createPodSandbox for pod "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

**Anything else do we need to know**:
I have google for a while but nothing help for now! I have try to search all [issue](https://github.com/kubernetes/minikube/issues),but no answer can help me fix this! anybody help ?

**Comment by grll** [comment]
@land-pack I am experiencing the same issue with minikube v0.26.1 and hyperkit driver on OSX. Did you solve it ?

**Comment by TaylorBenner** [comment]
+1

**Comment by land-pack** [comment]
@grll No, I try it on Linux platform instead of Mac OX.

**Comment by tstromberg** [comment]
Closing open localkube issues, as localkube was long deprecated and removed from the last two minikube releases. I hope you were able to find another solution that worked out for you - if not, please open a new PR.
