### ISSUE TITLE
Add fuse-sshfs package to ISO

### ISSUE THREAD

**Issue by praveenkumar** [kubernetes/minikube#2599]
Currently, minikube iso doesn't have fuse-sshfs package support as of now and `sshfs` command is not yet part of it. Recently docker-machine also added support for sshfs so might be good idea to add this package and also minishift have now PR to support sshfs.

**Comment by praveenkumar** [comment]
@r2d4 Can you assign this to me, will take of this.

**Comment by LalatenduMohanty** [comment]
Here is the PR in minishift to add SSHFS for hostfolder https://github.com/minishift/minishift/pull/2093

**Comment by praveenkumar** [comment]
Merged by #2600
