### ISSUE TITLE
Where should we set Environment="KUBELET_EXTRA_ARGS=--feature-gates=DevicePlugins=true"  in minikube

### ISSUE THREAD

**Issue by yoshihingis** [kubernetes/minikube#2605]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
 Only Question

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):0.24.1
- **OS** (e.g. from /etc/os-release):Ubuntu16.04LTS 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):--VM-driver=none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):Kubernetes version=1.8 ,Nvidia-docker V2
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
I used minikube and nvidia-docker V1, I could create GPU pod.
Now I tried to create GPU pod by minikube and nvidia-docker2.
But we set "Environment="KUBELET_EXTRA_ARGS=--feature-gates=DevicePlugins=true",when we use nvidia-docker2.
If we use kubeadm, we set it at /etc/systemd/system/kubelet.service.d/10-kubeadm.conf.
But I think that minikube does not use kubeadm.
Hence I want to known where I have to set "Environment="KUBELET_EXTRA_ARGS=--feature-gates=DevicePlugins=true"?

I'd really appreciate it if you will give me any advices soon.

**Comment by aclowkey** [comment]
@fabiand  didn't work for me..

**Comment by aclowkey** [comment]
@fabiand I solved this by adding --default-runtime=nvidia to the docker service conf.

**Comment by mindprince** [comment]
Hello,
I have a PR that adds GPU support to minikube: #2936. It would be really helpful if people on this thread try it out. The instructions are in the PR.
Thank you!
