### ISSUE TITLE
Change default docker IP? 

### ISSUE THREAD

**Issue by dwjohnston** [kubernetes/minikube#2607]
I'm using minikube and docker-machine running on VirtualBox. 

I have an unfortunate situation where the corporate proxy IP has the same host as the default docker ip. ie. 172.17.X.X. 

For docker machine - I fix this by editing my docker toolbox `start.sh` to run: 

```
  "${DOCKER_MACHINE}" create -d virtualbox $PROXY_ENV --engine-opt bip=172.18.0.1/16 "${VM}" 
```

My current solution for minikube is just: 

```
minikube ssh
ifconfig docker0 172.18.0.1 netmask 255.255.0.0
```

Is there a better way I can do this? (ie passing in as an argument on `minikube start`)?

**Comment by dwjohnston** [comment]
Add this flag:  `-- docker-opt bip=172.18.0.1/16` to your minikube start command.

**Comment by matsch01** [comment]
This doesn't work for me. I start minikube like this:

minikube start --docker-opt bip=172.18.0.1/16

I get the following output:

😄  minikube v1.7.3 on Darwin 10.15.3
✨  Using the hyperkit driver based on existing profile
⌛  Reconfiguring existing host ...
🔄  Starting existing hyperkit VM for "minikube" ...
🐳  Preparing Kubernetes v1.17.3 on Docker 19.03.6 ...
    ▪ opt bip=172.18.0.1/16
🚀  Launching Kubernetes ...
🌟  Enabling addons: dashboard, default-storageclass, ingress, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

But when I ssh into minikube, the docker0 bridge network is still 172.17.0.1:

$ ifconfig
docker0   Link encap:Ethernet  HWaddr 02:42:BA:93:95:03
  inet addr:172.17.0.1  Bcast:172.17.255.255  Mask:255.255.0.0
  UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
   RX packets:2672 errors:0 dropped:0 overruns:0 frame:0
   TX packets:2998 errors:0 dropped:0 overruns:0 carrier:0
   collisions:0 txqueuelen:0
   RX bytes:1313269 (1.2 MiB)  TX bytes:3109385 (2.9 MiB)

I've also tried adding /etc/docker/daemon.json. This didn't work either.

Can you please confirm that setting --docker-opt bip=172.18.0.1/16 is in fact suppose to change the subnet of the docker0 network?
