### ISSUE TITLE
minikube: Property name WantShowDriverDeprecationNotification not found

### ISSUE THREAD

**Issue by mykaul** [kubernetes/minikube#2615]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release):
NAME=Fedora
VERSION="27 (Workstation Edition)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
    "DriverName": "kvm2",

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
       "Boot2DockerURL": "file:///home/ykaul/.minikube/cache/iso/minikube-v0.25.1.iso",
        "ISO": "/home/ykaul/.minikube/machines/minikube/boot2docker.iso",

- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
[ykaul@ykaul bin]$ minikube version
minikube version: v0.25.0



**What happened**:
I'm trying to remove the warning about kvm driver being deprecate (I honestly don't see the difference between it and kvm2 ?), but:
[ykaul@ykaul bin]$ minikube config set WantShowDriverDeprecationNotification false
Property name WantShowDriverDeprecationNotification not found


**What you expected to happen**:
I expected the property to found.

**How to reproduce it** (as minimally and precisely as possible):
I'm just running the command, as shown in the deprecation warning.

**Output of `minikube logs` (if applicable)**:
[ykaul@ykaul bin]$ minikube logs
F0319 13:18:13.239139   17017 logs.go:50] Error getting cluster bootstrapper: getting localkube bootstrapper: getting ssh client: Error creating new ssh host from driver: Error getting ssh host name for driver: Driver "kvm2" not found. Do you have the plugin binary accessible in your PATH?

**Anything else do we need to know**:
Where is the KVM2 driver being developed?

**Comment by afbjorklund** [comment]
Contrary to what the "documentation" says, there is no support in `config` for this...

Also, it showed the wrong name - should be: `ShowDriverDeprecationNotification`
