### ISSUE TITLE
Minikube: no release since Jan 26 (0.25.0)

### ISSUE THREAD

**Issue by attila123** [kubernetes/minikube#2620]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
N/A

The last release of Minikube (0.25.0) is almost two months old (in the world of CD this seems to be bit too long time). I am sure there were many improvements since then, so I think it would be beneficial to have a new release.
(For example I had a problem with 0.25.0, which was fixed meanwhile (https://github.com/kubernetes/minikube/pull/2550), but not released yet.)
I read that I can download newer builds e.g.
https://storage.googleapis.com/minikube-builds/PR_NUMBER/minikube-linux-amd64 but it does not feel like the real thing...

**Comment by fabiand** [comment]
I'm happy to help if something is missing.

**Comment by r2d4** [comment]
We did a security patch release. We still need to iron out some issues with the none driver before transitioning to kubeadm fully. The main blocker is that we currently require the none driver to run on systemd based OSes for kubeadm, and we should drop this requirement.

**Comment by svenstaro** [comment]
I suppose this can be closed now.

**Comment by afbjorklund** [comment]
@svenstaro : I think this ticket is talking about 0.26

**Comment by attila123** [comment]
Sorry guys, I only took a look at the changelog in master sometimes, not in the releases/tags, I think (my bad).
Unfortunately v0.25.2 still has some critical issues (for my use-case):
- https://github.com/kubernetes/minikube/issues/2642 (configMap volume issue) - would need newer k8s in Minikube than the v1.9.4 - this one is not implemented yet.
- #2550 (cannot stop minikube when using the none driver) - this one is already fixed.
Until these issues are fixed, my best bet is to use https://storage.googleapis.com/minikube-builds/2550/minikube-linux-amd64 (which contains the fix for #2550).

**Comment by attila123** [comment]
BTW, @r2d4 the changelog for v0.25.2 contains a little bug, it still shows 0.25.1 (https://github.com/kubernetes/minikube/commit/67a6b02320bf14757bcaa4396c4bf8dd01600e81). Thanks for the release anyway.

**Comment by afbjorklund** [comment]
@attila123 : if you are using `kubeadm` bootstrapper (the default), you don't need to wait for another localkube. you should be able to select the latest version yourself (using `--kubernetes-version`)

I was working on something that outputted the latest version, rather than that hardcoded JSON one...
Basically: `curl https://storage.googleapis.com/kubernetes-release/release/stable.txt`

**Comment by afbjorklund** [comment]
Basically the maintenance "branch" (if you want to call it that), is missing a couple of important backports.
And no, I hadn't tried it with the "none" driver - there might be some quirks left to iron out for that setup...
