### ISSUE TITLE
start.go:234:: Error updating cluster:  generating kubeadm cfg: parsing kubernetes version: parsing kubernetes version: strconv.ParseUint: parsing "": invalid syntax

### ISSUE THREAD

**Issue by andres-lowrie** [kubernetes/minikube#2624]
**Is this a BUG REPORT**

**Environment**:

**Minikube version** : 0.25.0
- **OS** : Mac OSX Sierra
- **VM Driver** :virtualbox
- **ISO version** : minikube-v0.25.1.iso
- **Install tools**: 
- **Others**:

**What happened**:

Tried to start cluster with version 1.9.4

**What you expected to happen**:

The cluster to start normally

**How to reproduce it** (as minimally and precisely as possible):

```
➜  minikube start --kubernetes-version 1.9.4
Starting local Kubernetes 1.9.4 cluster...
Starting VM...
Downloading Minikube ISO
 142.22 MB / 142.22 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
E0321 09:58:55.643116   51234 start.go:234] Error updating cluster:  generating kubeadm cfg: parsing kubernetes version: parsing kubernetes version: strconv.ParseUint: parsing "": invalid syntax
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
```

**Anything else do we need to know**:

**Comment by andres-lowrie** [comment]
So it looks like the issue was a _pebkac_ one 😂 

I was passing `1.9.4` and not `v.1.9.4` so the start subcommand

I'll see myself out 😂

**Comment by kplimack** [comment]
I hit this, too. Would be nice if kubectl corrected it and/or if the help page said so
