### ISSUE TITLE
Fix release automation/docs

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#2632]
Our last two releases have caused problems. Let's fix up the automation/docs to prevent this in the future.

Ref #2629 #2630

**Comment by afbjorklund** [comment]
We missed to cherry-pick the major/minor fix into the 0.25 "branch" (which I can't seem to find ?)

This means that 0.25.2/1.9.4 also has the same issue (#2593) as 0.25.0/1.9.0 originally had (#2505)

**Comment by afbjorklund** [comment]
Also #2536
