### ISSUE TITLE
How to set up mirror-registry 

### ISSUE THREAD

**Issue by lli-hiya** [kubernetes/minikube#2638]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

- **Minikube version** (use `minikube version`): minikube version: v0.22.2

- **OS** (e.g. from /etc/os-release): Mac Sierra 10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.4.iso
- **Install tools**:
- **Others**:

**What happened**:

I am trying to set up a mirror-registry: https://docs.docker.com/registry/recipes/mirror/, and it works fine when I set this up in local docker. I can test this mirror-registry by `docker pull <image>`. 

However, when I want to test this in minikube, I find that it is not so straightforward. More specifically, I need to configure docker daemon (inside of minikube) to point to my mirror registry. I tried running `minikube start --registry-mirror "xxx" --insecure-registry "yyy"` and then `minikube ssh & docker info`, which doesn't show any of the setttings configured.  I also tried to update `~/.minikube/machines/minikube/config.json` directly, followed by `minikube start` to pick up the change. This time, the `minikube ssh & docker log` shows that `insecure-registry` is updated, but still `registry-mirror` is not. 

I'd like to know what is the correct way to set up these two options?

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by gzcf** [comment]
To set up mirror-registry, 

```
minikube ssh
sudo mkdir -p /etc/docker
sudo tee /etc/docker/daemon.json <<-'EOF'
{
  "registry-mirrors": ["xxx"]
}
EOF
sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by kerbylane** [comment]
I'm trying to set this up.  What are your "xxx" and "yyy" values?  Neither `host.docker.internal` (from the Docker docs) or `gateway.docker.internal:3129` from my instance work as either of those.
