### ISSUE TITLE
Update build bot to use "minikube" AUR instead of "minikube-bin"

### ISSUE THREAD

**Issue by svenstaro** [kubernetes/minikube#2640]
I'm writing to inform you that I renamed the AUR package to minikube-bin. I've given you a heads-up in the package comments but there was no response. It is common to give users the information in the package name if they are installing from source or whether they are installing a binary straight from upstream.

This issue exists so you can update your build scripts to point at this new name. Furthermore it would be nice if you could provide a package built from source at the now-vacant minikube name in the AUR.

**Comment by svenstaro** [comment]
The minikube-bot account recreated the original minikube package with the same content. Please stop that and instead co-maintain minikube-bin.

**Comment by svenstaro** [comment]
@aaron-prindle please have a look.

**Comment by afbjorklund** [comment]
@tstromberg : we should clean this naming convention up in our own (BR*) packages, as well.. Currently it is just confused, which ones are downloaded as binary (i.e. `*-bin`) and which are built from source....

\* https://github.com/kubernetes/minikube/tree/master/deploy/iso/minikube-iso/package
