### ISSUE TITLE
minikube setup with kvm

### ISSUE THREAD

**Issue by alnhk** [kubernetes/minikube#2648]
Hello.,
The environment detail is : 
1. Xeon E5-2690 2.9GHZ and this is oracle exalogic
2. I created one virtual machine with CENTOS 7 running
3. I already setup clustered kubernetes and i am able to get result on "get nodes" as well as "get pods --all-namespaces"
4. I want to install minikube because i need to setup and use zalenium (instruction - [link ](https://zalando.github.io/zalenium/#kubernetes) )

Can you please advice which type should i use ?I mean, running  "minikube start --vm-driver kvm" or "minikube --vm-driver kvm2" did not succeed and throws an exception, yes we cannot use "minikube start" as we are not going to use virtualbox. Yes i followed this instruction with installing [minikube  drivers readme](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md) 

E0325 02:50:02.541841    3320 start.go:165] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] **invalid argument: could not find capabilities for domaintype=kvm** 

E0325 02:50:02.541841    3320 start.go:165] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: [Code-8] [Domain-44] **invalid argument: could not find capabilities for domaintype=kvm2**

Please help us to get minikube installed on this type of environment which is almost same as vmware.

**Comment by afbjorklund** [comment]
If you already have a VM set up, you can use "minikube --vm-driver none" to install locally on it.

Unfortunately the documentation is missing (#2575)

**Comment by alnhk** [comment]
Yes, i did that using "--vm-driver none", this blew off the certificates and eventually everything including "kubectl get nodes" or "kubectl get pod --all-namespaces" failed with certificate issue (related to "x509: certificate signed by unknown authority"). Can you please tell how to solve this.

**Comment by alnhk** [comment]
And yes, we are heavily behind the proxy. what is the latest version of minikube  ? i am using 0.25.2 with latest kubernetes 1.96.

**Comment by afbjorklund** [comment]
@alnhk : you mean that you already installed kubernetes, and then installed minikube on top of that ?
the actual error sounds like it didn't get the IP of the VM quite right, and thus generated certs for wrong

You can give the IP explicitly, using `--apiserver-ips`

**Comment by gbraad** [comment]
You use self-signed certificates, so the CA is of course not recognized.
Were did you get this issue... As you likely need to force to trust this.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by alnhk** [comment]
@afbjorklund : yes installed minikube on top of that. So, i can specify --apiserver-ips to "minikube  start..." ?

**Comment by alnhk** [comment]
the port 8443 which was supposed to be started by localkube process failed with below: Is there any other immediate fix ? Yes, i ran "minikube logs", it threw below exception : 

Mar 26 07:56:23 k8-master localkube[10344]: F0326 07:56:23.170621   10344 etcd.go:53] Error starting up etcd: listen tcp 127.0.0.1:2380: bind: address already in use
Mar 26 07:56:23 k8-master systemd[1]: localkube.service: main process exited, code=exited, status=255/n/a
Mar 26 07:56:23 k8-master systemd[1]: Failed to start Localkube.
Mar 26 07:56:23 k8-master systemd[1]: Unit localkube.service entered failed state.
Mar 26 07:56:23 k8-master systemd[1]: localkube.service failed.

**Comment by alnhk** [comment]
@afbjorklund @gbraad  -please advice for resolution.

**Comment by afbjorklund** [comment]
To me it sounds like you are trying to run two kubernetes at once, not really sure why you'd need that...

Normally you would start up a new VM for minikube, or deploy that "zalenium" on your regular cluster ?

**Comment by alnhk** [comment]
Here's what I am doing : 
1. yum install kubeadm docker (whch installs all dependencies)
2. kubeadm init  --apiserver-advertise-address=<hostname>  --pod-network-cidr=10.244.0.0/16
3. fix the ~/.kube/config 
4. export the path of admin.conf
5. run "kubeadm join...." on 3 nodes
6. able to run "kubectl get nodes" and "kubectl get pods --all-namespaces"
5. /etc/systemd/system/localkube.service.d/override.conf
 [Service]
Environment='GODEBUG=netdns=go'
6. minikube start --vmdriver=none --apiserver-ips=<ip of master node>
7. after that , port 8443 and "localkube" fails to start with "Error starting up etcd: listen tcp 127.0.0.1:2380: bind: address already in use".

I am trying to deploy zalenium as defined in the instruction - https://zalando.github.io/zalenium/

Please correct me about the steps i tried.
