### ISSUE TITLE
minikube docker-env not Working on Windows

### ISSUE THREAD

**Issue by thedarkdestructor** [kubernetes/minikube#2650]
Executing **`minikube docker-env`** does not work as expected.

I open a promt as administrator. I execute the command and I get the following.
```
> minikube docker-env
SET DOCKER_TLS_VERIFY=1
SET DOCKER_HOST=tcp://192.168.1.20:2376
SET DOCKER_CERT_PATH=C:\Users\...\.minikube\certs
SET DOCKER_API_VERSION=1.23
REM Run this command to configure your shell:
REM @FOR /f "tokens=*" %i IN ('minikube docker-env') DO @%i
```

Then I try to configure the shell as suggested by the output of the command with

`@FOR /f "tokens=*" %i IN ('minikube docker-env') DO @%i`

But after that if I try to execute any docker command on my pront I get the command not found message from the pront.

Could this be releated to #2347? The solution proposed there does not work for me...

**Comment by thedarkdestructor** [comment]
Am I the only one getting this problem on Windows??

**Comment by budhrg** [comment]
I am able to reproduce too
```
C:\Users\budhram>@FOR /f "tokens=*" %i IN ('minikube docker-env') DO @%i

C:\Users\budhram>docker images
error during connect: Get https://[fe80::215:5dff:fec1:3415]:2376/v1.23/images/json: dial tcp [fe80::215:5dff:fec1:3415]:2376: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

Docker Host is coming as `DOCKER_HOST=tcp://[fe80::215:5dff:fec1:3415]:2376` (IPv6) address.
cc @r2d4

**Comment by thedarkdestructor** [comment]
I am using virtualbox. I would like to keep using virtualbox. To me is not clear if docker need to be installed in the host for using docker-env... do yo have docker installed on your host?

**Comment by budhrg** [comment]
> I am using virtualbox. I would like to keep using virtualbox. To me is not clear if docker need to be installed in the host for using docker-env... do yo have docker installed on your host?

It was when I was using HyperV. Now, unable to even install "Docker for windows" with VirtualBox.
![no_virtualbox_support](https://user-images.githubusercontent.com/1132451/37900591-4d90bdec-310c-11e8-8b87-1b877a31802e.PNG)

How did you install docker client?

**Comment by budhrg** [comment]
> How did you install docker client?

Oops Wrong question. 

I am able to connect to docker daemon inside VM.
```
C:\Users\budhram>docker version
Client:
 Version:      17.09.0-ce
 API version:  1.23
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:45:38 2017
 OS/Arch:      linux/amd64
 Experimental: false

C:\Users\budhram>docker images
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kubernetes-dashboard-amd64         v1.8.1              e94d2f21bc0c        3 months ago        121MB
gcr.io/google-containers/kube-addon-manager   v6.5                d166ffa9201a        4 months ago        79.5MB
gcr.io/k8s-minikube/storage-provisioner       v1.8.1              4689081edb10        4 months ago        80.8MB
k8s.gcr.io/k8s-dns-sidecar-amd64              1.14.5              fed89e8b4248        6 months ago        41.8MB
k8s.gcr.io/k8s-dns-kube-dns-amd64             1.14.5              512cd7425a73        6 months ago        49.4MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64        1.14.5              459944ce8cc4        6 months ago        41.4MB
gcr.io/google_containers/pause-amd64          3.0                 99e59f495ffa        23 months ago       747kB
```
So, the issue I was getting in HyperV is different issue :)

**Comment by budhrg** [comment]
@thedarkdestructor , what is your docker client version? If it is not ` 17.09.0-ce`, can you try updating to it and retry?

**Comment by thedarkdestructor** [comment]
It is not possible to have both vmware and virtualbox installed at the same time.  So, is it possible to use docker-env with this configuration:
- minikube
- Virtual box
- NO docker installed in host. It is not possible to have both docker and VirtualBox: docker is using hyperv and there is conflict with VirtualBox installation.

**Comment by budhrg** [comment]
> NO docker installed in host. 

Only Docker client is needed for `docker-env`.  

> It is not possible to have both docker and VirtualBox: docker is using hyperv and there is conflict with VirtualBox installation.

Yes, it is possible to have both Docker and VirtualBox installed.

**Comment by thedarkdestructor** [comment]
Is not possible to have both Docker and VirtualBox installed in windows without incurring in conflicts. You have a clear example of this on the image you posted in the previous post.

![image](https://user-images.githubusercontent.com/4816982/37956045-8f098198-31aa-11e8-97e2-4ee2be17c5e8.png)

**hyperv and vmware are not compatible having one disable the other**

What you mean by docker client? Can you provide a download link?

**Comment by budhrg** [comment]
>What you mean by docker client? Can you provide a download link?

It seems "Docker for windows".exe comes with client and server binary.

See below:
```
PS C:\Users\budhram> docker version
docker : The term 'docker' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was
included, verify that the path is correct and try again.
At line:1 char:1
+ docker version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (docker:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
### Install "Docker for Windows.exe" binary (Note I am not starting it through Menu which wil start Docker daemon)
```
PS C:\Users\budhram> docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:40:09 2017
 OS/Arch:      windows/amd64
error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.32/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
```
##### Error is obvious since I don't have daemon.

Now, do `minikube docker-env`.
