### ISSUE TITLE
Unable to get minikube dashboard

### ISSUE THREAD

**Issue by sudipto92** [kubernetes/minikube#2654]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.25.0
- **OS** (e.g. from /etc/os-release): Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.25.1.iso
- **Install tools**: kubectl
- **Others**:
**What happened**:
When i am executing below command it should open minikube dashboard:
minikube dashboard

**What you expected to happen**:
Kubernete dashboard should open

**How to reproduce it** (as minimally and precisely as possible):
1. minikube start --vm-driver hyperv --hyperv-virtual-switch "VS" -v 7
2. minikube dashboard

**Output of `minikube logs` (if applicable)**:
[a.log](https://github.com/kubernetes/minikube/files/1851021/a.log)

**Anything else do we need to know**:
When i am executing command: *kubectl get pods --all-namespaces*
o/p:
NAMESPACE     NAME                          READY     STATUS              RESTARTS   AGE
kube-system   kube-addon-manager-minikube   0/1       ContainerCreating   0          1h

**Comment by johnhampton** [comment]
I'm having the same issue under MacOS with the hyperkit driver.

**Comment by jasonmacdonald** [comment]
Same here

**Comment by NsLib** [comment]
```
NAMESPACE NAME READY STATUS RESTARTS AGE
kube-system kube-addon-manager-minikube 0/1 ContainerCreating 0 1h
```

This means your kubernetes cluster didn't ready to serve, and you need to use the following command to diagnose why it choked at `ContainerCreating` state.

```
kubectl describe pod kube-addon-manager-minikube -n kube-system
```

**Comment by geertschuring** [comment]
I also can't reach the dashboard. On MacOS with virtualbox. I get 404 errors.

**Comment by sudipto92** [comment]
I am waiting for solution... Please help

**Comment by tstromberg** [comment]
sudipto92  - What kind of behavior/error were you seeing when you tried to access the dashboard? I'm not sure what's going on here yet, but I did see these suspicious errors:

Mar 27 07:52:38 minikube localkube[3322]: I0327 07:52:38.014514    3322 handler.go:160] kube-aggregator: GET "/api/v1/namespaces/kube-system/services/kubernetes-dashboard" satisfied by nonGoRestful
Mar 27 07:52:38 minikube localkube[3322]: I0327 07:52:38.015468    3322 pathrecorder.go:247] kube-aggregator: "/api/v1/namespaces/kube-system/services/kubernetes-dashboard" satisfied by prefix /api/
Mar 27 07:52:38 minikube localkube[3322]: I0327 07:52:38.016403    3322 handler.go:150] kube-apiserver: GET "/api/v1/namespaces/kube-system/services/kubernetes-dashboard" satisfied by gorestful with webservice /api/v1
Mar 27 07:52:38 minikube localkube[3322]: I0327 07:52:38.023646    3322 wrap.go:42] GET /api/v1/namespaces/kube-system/services/kubernetes-dashboard: (9.909ms) 404 [[minikube/v1.9.0 (windows/amd64) kubernetes/925c127] 10.10.182.221:51857]

**Comment by tstromberg** [comment]
minikube v0.30.0 has drastically changed how the dashboard is managed: please try upgrading to it, and open a new issue if anything is seen.
