### ISSUE TITLE
Provide external IP via kubectl

### ISSUE THREAD

**Issue by amouat** [kubernetes/minikube#2655]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT
(Maybe FEATURE REQUEST!)
Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.25.1
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm2
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.25.1.iso

I want to programatically get the external IP of minikube via kubectl. First attempt:

```
kubectl get nodes -o wide
NAME       STATUS    AGE       VERSION   EXTERNAL-IP   OS-IMAGE            KERNEL-VERSION
minikube   Ready     4d        v1.9.4    <none>        Buildroot 2017.11   4.9.64
```

Second attempt:

```
$ kubectl get nodes -o json -o jsonpath='{.items[0].metadata.annotations}'
map[node.alpha.kubernetes.io/ttl:0 volumes.kubernetes.io/controller-managed-attach-detach:true]
```

**What you expected to happen**:

Expected `kubectl get nodes` to contain external-ip.
Expected annotations to include ".kubernetes.io/provided-node-ip" as per https://github.com/kubernetes/minikube/issues/544#issuecomment-339711805.

**How to reproduce it** (as minimally and precisely as possible):

Run `kubectl get nodes -o json` and inspect results.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

The external-ip is really helpful for scripting tooling that works on both minikube and a complete k8s install.

**Comment by balboah** [comment]
the **provided-node-ip** annotation seems to be available in > v0.25.0 if you run with:
`--bootstrapper localkube --kubernetes-version v1.8.0`
