### ISSUE TITLE
minikube 0.25.2   add node (vm_driver=none)?

### ISSUE THREAD

**Issue by alnhk** [kubernetes/minikube#2658]
Hello.,

I am using minikube 0.25.2, here's steps to reproduce : 
- minikube start --kubernetes-version="v1.9.4"  --vm-driver=none --apiserver-ips=xx.xx.xx.xx
>>Cluster is built
>> i am able to get result of "minikube status" as well as "kubectl get nodes"

WHat is the instruction to scale up the node in this cluster ? I tried using : 
kubeadm token create --print-join-command (on master)
on node, i executed above result and getting  : 
[discovery] Created cluster-info discovery client, requesting info from "https://xx.xx.xx.xx:8443"
[discovery] Failed to request cluster info, will try again: [Unauthorized]
[discovery] Failed to request cluster info, will try again: [Unauthorized]

Please advice resolution to scale up the node ?

**Comment by gbraad** [comment]
@alnhk please see #2565 and #2539

**Comment by alnhk** [comment]
@gbraad  :  is this #2539 based on "--vm-driver=none" ? i am using minikube 0.25.2, i dont see the flag "minikube node add..." available...correct me if i am wrong

**Comment by alnhk** [comment]
@gbraad : i followed #2539, "minikube node add..." returns unknown...can you please confirm if this #2539 is outdated ?

[root@k8-master minikube]# ./out/minikube node add add k8-node
**Error: unknown command** "node" for "minikube"
Run 'minikube --help' for usage.
[root@k8-master minikube]#

**Comment by gbraad** [comment]
This is still under development and is certainly not part of the current release
