### ISSUE TITLE
minikube --mount is broken on OS X

### ISSUE THREAD

**Issue by MadWombat** [kubernetes/minikube#2661]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

bug report

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):  v0.25.2
- **OS** (e.g. from /etc/os-release): OS X 10.13.3
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.25.1.iso
- **Install tools**: None, manually downloaded and installed latest minikube and driver
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:

The xhyve VM driver used to mount /Users in /Users in minikube VM. Since it is deprecated, I switched to hyperkit driver that does not provide the same default mount. So I tried to use minikube's --mount flag to simulate the same thing. I started minikube as `minikube start --mount --mount-string /Users:/Users`. When the cluster has started, I tried `minikube ssh ls /Users` and got `ls: cannot access '/Users': Input/output error`.

**What you expected to happen**:

/Users to be accessible to minikube VM

**How to reproduce it** (as minimally and precisely as possible):

Same way I did. Start minikube as a regular "Admin" user on OS X with `--mount`  and `--mount-string /Users:/Users` flags (I think just --mount should suffice, but I am not sure) and use `minikube ssh` to verify that the mount is not really accessible.

**Comment by NsLib** [comment]
It probably caused by file permission, since `/Users` directory is owned by `root:admin`, minikube cannot access it in vm.

**Comment by MadWombat** [comment]
Well, those permissions are a default on OS X, so it should be handled with a bit more grace than throwing an I/O error on access. A message saying mount on OS X is not supported, a suggestion on permission adjustment or something.

**Comment by NsLib** [comment]
I've submitted a PR #2671

**Comment by haf** [comment]
Was this ever fixed?

How are the permissions supposed to be set?

**Comment by jondkelley** [comment]
> Was this ever fixed?
> How are the permissions supposed to be set?

Agreed, this issue is still an apparent bug to me and seems like the maintainers just silently closed this one without remarks...
