### ISSUE TITLE
Windows installer defaults installing 64-bit binaries into 32-bit directory (x86)

### ISSUE THREAD

**Issue by rakslice** [kubernetes/minikube#2670]
Please provide the following details:

**Environment**:

Windows 10 Pro 1709 (build 16299.309) 64-bit US English

**Minikube version** (use `minikube version`):

v0.25.2

**What happened**:

Installer proposed default install directory `C:\Program Files (x86)\Kubernetes\Minikube`

**What you expected to happen**:

Installer should propose `C:\Program Files\Kubernetes\Minikube` (or the corresponding system directory as appropriate on other regional Windows variants)

**Comment by rakslice** [comment]
See http://nsis.sourceforge.net/Reference/$PROGRAMFILES

**Comment by rakslice** [comment]
Issue is still present in v0.28.0

**Comment by tstromberg** [comment]
This is still an issue AFAIK, and I would more than happy to review any PR's which fix the issue. Help wanted!
