### ISSUE TITLE
Is there any use of systemd-resolved for minikube iso by default?

### ISSUE THREAD

**Issue by praveenkumar** [kubernetes/minikube#2672]
Currently, minikube iso have `systemd-resolved` service running by default and it binds with the port `53`. As part of minishift, we are trying to start a local dnsmasq which can serve to this port and provide offline resolver for routes. 

If there is no direct use case of this service I will try to send a PR which disable it from the boot and check if all the test case passes as expected.

**Comment by gbraad** [comment]
Ref https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html
