### ISSUE TITLE
Overwrite default registry

### ISSUE THREAD

**Issue by mycroftmih** [kubernetes/minikube#2674]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.25.2
- **OS** (e.g. from /etc/os-release): Fedora 27 (Workstation Edition)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.25.1
- **Install tools**:
- **Others**:

**What happened**:
I want to use a private registry, without explicitly writing the private registry name in the image path.

**What you expected to happen**:
start as: minikube start --registry myregistry.net

curent: kubectl run --image=myregistry.net/nginx
desired: kubectl run --image=nginx (to be pulled from myregistry.net)

**Anything else do we need to know**:
The redhat docker fork has a feature to overwrite the default docker.io registry, but here is not the case since we don't use it in minikube.
The solution would be cri-o since it has the --registry flag that can do the job.

**Comment by NsLib** [comment]
Take a look at this: https://github.com/moby/moby/issues/11815

![image](https://user-images.githubusercontent.com/2672226/38294269-e47001fc-381c-11e8-94e0-2b8bcc140dda.png)

**Comment by mycroftmih** [comment]
It should make sense that a user who wants to change the defaut registry,
he may very well know how to build his own ubuntu image and push it to his own registry. 

I'm not asking for something that's not on the market now, I'm just asking for a shortcut, like --insecure-registry.
