### ISSUE TITLE
Failure when trying to scp files into Minikube VM

### ISSUE THREAD

**Issue by chirangaalwis** [kubernetes/minikube#2678]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
A Bug report

**Environment**:

**Minikube version** (use `minikube version`): v0.25.2
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS (Xenial Xerus)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.25.1

**What happened**:
I am using the defined version of Minikube in the defined environment.

It is required for me to upload a tarfile (produced using `docker save` of certain Docker images) into the Minikube VM. Hence, I attempted the following two methods:

- Using `scp` command manually.
I tried using the following `scp -i $(minikube ssh-key) <tarfile> docker@$(minikube ip):/home/docker`.
This attempt failed with a `packet_write_wait: Connection to 192.168.99.100 port 22: Broken pipe lost connection` error.
- Using `~/.minikube/files` folder as defined, [here](https://github.com/kubernetes/minikube/issues/1914).
This attempt also fails as follows:

```
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E0405 13:51:12.443681    7960 start.go:234] Error updating cluster:  Error running scp command: sudo scp -t / output: : wait: remote command exited without exit status or exit signal
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:

```
**Note**:
I have setup a `~/.ssh/config` file with following content:
```
Host *
    ServerAliveInterval 300
    ServerAliveCountMax 2
```

**What you expected to happen**: Successfully upload the tarfile from my local machine into the Minikube VM.

**How to reproduce it** (as minimally and precisely as possible): Follow steps defined in two methods under **What happened** section.

**Anything else do we need to know**:
If the steps I'm following are incorrect, please direct to the correct steps in achieving the above.

**Comment by pbaker7** [comment]
I have this exact same problem. I need to move docker images onto the VM as part of an installation process. The images are about 5GB in total, and when I try to move them using .minikube/files, or scp I get the same symptoms. We are moving other files using the .minikube/files technique, so my guess is that it is a size issue.

**Comment by tstromberg** [comment]
@pbaker7 - Do you mind opening a new issue that mentions this one? I suspect you may actually have a different environment from the original author here. I can always de-dupe it if not.

**Comment by yongyct** [comment]
any resolutions for this? i am also facing the same issue
