### ISSUE TITLE
How is DNS working without any DNS related pods?

### ISSUE THREAD

**Issue by colemickens** [kubernetes/minikube#268]
I just downloaded `0.4.0` and deployed a local cluster.

I was going to file an issue for not knowing how to run DNS, but then I noticed the `kube-dns` service already existed. There are no `kube-dns` related pods running, but yet DNS works in the cluster. How is this possible?

**Comment by dlorenc** [comment]
Hey,

DNS works today by running the kube2sky code in-process. You can see that here: https://github.com/kubernetes/minikube/blob/master/pkg/localkube/dns.go

We're probably going to switch this to a kube-dns pod model though. See https://github.com/kubernetes/minikube/issues/55 for more details.
