### ISSUE TITLE
Disable automatic checkpoints when using Hyper-V

### ISSUE THREAD

**Issue by F21** [kubernetes/minikube#2683]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  Feature Request

I've recently started using minikube with Hyper-V on my Windows 10 machine, since Docker for Windows has a hard requirement on Hyper-V. Hyper-V enables automatic checkpoints by default, however, because automatic checkpoints are created on bootup, it takes a while during boot and shutdown to merge the checkpoints.

I don't think there is too much benefit having automatic checkpoints enabled for the minikube VM. It might be a good idea to disable the automatic checkpoints setting when creating the VM in Hyper-V.

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.25.2
- **OS** (e.g. from /etc/os-release): Windows 10 64-bit 1709 (latest updates)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Hyper-V
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.25.1
- **Install tools**: Docker for Windows, skaffold
- **Others**:

**Comment by r2d4** [comment]
Hey thanks for the issue. I think we can disable this feature.

**Comment by gbraad** [comment]
You can change the behaviour using the hyperv manager. At the moment I can not recall if the driver supported this. It is part of libmachine, so @r2d4 this would be one of those improvements we can put on our wishlist.
