### ISSUE TITLE
Question: How do I find out why kubernetes-dashboard runs on port 30000?

### ISSUE THREAD

**Issue by vladiibine** [kubernetes/minikube#2686]
I've installed minikube and kubernetes according to this page
https://kubernetes.io/docs/getting-started-guides/minikube/

Got to this section:
https://kubernetes.io/docs/getting-started-guides/minikube/#dashboard

Ran this command, and got the output:
``` 
$ minikube dashboard --url                                                                                                         
http://192.168.99.102:30000
```

So the dashboard runs on port 3000. I was trying to find how the dashboard is deployed on the local cluster. 

What I did to figure this out:
1. I searched through all kubernetes object configurations (nodes, pods, services) and found nothing mentioning 30000.
2. I looked inside the yaml file referred to by the dashboard github page
https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml  -> still no 30000 there
3. I went through all relevant files that were opened when running the command `minikube dashboard --url` -> no 30000 there either (Don't think I missed anything, but I only checked the files which seemed relevant). I did this with `strace`
4. I cloned the dashboard repository, and searched for 30000 there -> nothing

So, can you help me understand how the dashboard is deployed on the local minikube cluster?

I know this is not an issue. I'm basically only trying to understand how minikube/kubernetes works. But if you could give me a hint, it would still be awesome.

Thanks a lot!

**Comment by afbjorklund** [comment]
It is called a Service [NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport):

`deploy/addons/dashboard/dashboard-svc.yaml:    nodePort: 30000`

**Comment by vladiibine** [comment]
Thanks a lot! :)

I can't check now, but I will do it later. I'm closing the issue now because I trust the advice, and also as not to forget about it.
