### ISSUE TITLE
minicube startup issue: VT-X/AMD-v

### ISSUE THREAD

**Issue by phanikishorelanka** [kubernetes/minikube#2687]
I am getting an error when i am starting minikube. i confirm that the Intel virtualization and VT-D are enabled from my desktop, I am not sure how to resolve this in the Centos, Please assist. its blocking me. 

[root@docker ~]# minikube start
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
E0408 01:56:02.671317    1713 start.go:159] Error starting host: Error creating host: Error executing step: Running precreate checks.
: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory.

 Retrying.
E0408 01:56:02.671774    1713 start.go:165] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
[root@docker ~]# ^C
[root@docker ~]#

**Comment by gbraad** [comment]
Make sure you have enabled Virtualization from your BIOS. Marking as invalid as this is essential for Minikube to function; it needs to be able to start a VM using KVM. If this is an issue, consider using VirtualBox.

You could consider using `msr-tools` to verify if the extensions are really enabled: https://stackoverflow.com/questions/11116704/check-if-vt-x-is-activated-without-having-to-reboot-in-linux
