### ISSUE TITLE
 kubectl get pod: The connection to the server localhost:8080 was refused

### ISSUE THREAD

**Issue by jsaalfeld** [kubernetes/minikube#2689]
First of all: I'm not sure where the Issue is coming from, if it is a kubectl problem or a minikube problem, but I'm thankful for every hint in every direction

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): installed the latest deb-package from the releases page `v0.25.2`
- **OS** (e.g. from /etc/os-release): Debian sid - `4.15.0-2-amd64`
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): `minikube-v0.25.1`
- **Install tools**:
   * kubectl installed via `apt-get install kubernetes-client` : `Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7+8e15523423554", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}`
    * virtualbox installed via `apt-get install virtualbox`: `5.2.8`

**What happened**: I followed the tutorial from https://kubernetes.io/docs/getting-started-guides/minikube
```
[0|user@hooholo:~]# minikube start                                                 
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
[0|user@hooholo:~]# kubectl config use-context minikube
Switched to context "minikube".
[0|user@hooholo:~]# kubectl cluster-info
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[0|user@hooholo:~]# kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.4 --port=8080 
error: failed to discover supported resources: Get http://localhost:8080/api: dial tcp [::1]:8080: getsockopt: connection refused
[1|user@hooholo:~]#  kubectl get pod     
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[1|user@hooholo:~]# kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/user/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/user/.minikube/client.crt
    client-key: /home/user/.minikube/client.key
[0|user@hooholo:~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.7+8e15523423554", GitCommit:"8e1552342355496b62754e61ad5f802a0f3f1fa7", GitTreeState:"not a git tree", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

```

**What you expected to happen**: I expected to get the kubectl server version, while entering `kubectl version`

**How to reproduce it** (as minimally and precisely as possible): 
```
minikube start
kubectl config use-context minikube
kubectl version
```

**Comment by antonin07130** [comment]
same problem here after a while minikube stops beeing accessible. 
```The connection to the server 192.168.39.181:8443 was refused - did you specify the right host or port?```

**Comment by tstromberg** [comment]
Closing as obsolete, as we haven't seen this issue in a long time.

**Comment by flanger001** [comment]
This helped me https://github.com/kubernetes/kubernetes/issues/44665

**Comment by mirekphd** [comment]
Seems to me the port at the end of `clusters.cluster.server` value is completely ignored... once I changed the API server and port (in the SSH tunnel) from `localhost:16443` to `localhost:8080` i.e. to the port hard-coded in `kubectl` (sorry, it would seem), all started working (for `microk8s`).
