### ISSUE TITLE
Travis should build for darwin

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#269]
In https://github.com/kubernetes/minikube/pull/262, travis marked a commit as green even though it wouldn't have built on darwin. We should at least do a "GOOS=darwin GOARCH=amd64 make" somewhere in travis to be sure minikube compiles.

**Comment by jimmidyson** [comment]
We'll probably have to build on OS X too to make sure it works - have never done this on travis but seems possible - https://docs.travis-ci.com/user/osx-ci-environment/

**Comment by dlorenc** [comment]
I have some physical mac minis I'm working to add to a Jenkins setup as slaves. My understanding is that the travis environment for OSX doesn't support virtualization.

**Comment by dlorenc** [comment]
We now have this in Jenkins.
