### ISSUE TITLE
Ask for administrator elevation using UAC when using hyper-v on Windows

### ISSUE THREAD

**Issue by F21** [kubernetes/minikube#2693]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

It would be nice if minikube can pop up a UAC dialogue to elevate to admin permissions when starting a hyper-v VM. 

This would help avoid the issue where things don't appear to work if minikube is run from a shell that does not have administrator privileges. In addition, I tend to avoid running my shells as the administrator for security purposes, so having minikube requesting elevation would be super useful.

**Environment**:

**Minikube version** (use `minikube version`): 0.25.2
- **OS** (e.g. from /etc/os-release): Windows 10 1709 (latest updates) 64-bit
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Hyper-V
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): 0.25.1
- **Install tools**: n/a
- **Others**: n/a

**Comment by gbraad** [comment]
... you can make your user a member of the Hyper-V Administrators group to avoid this problem.
We have described this as part of the Minishift documentation at: https://github.com/minishift/minishift/blob/master/docs/source/getting-started/setting-up-driver-plugin.adoc#hyper-v-driver

**Comment by gbraad** [comment]
You could use `runas` to accomodate , else we would have to make minikube aware of the user. I would not prefer this. Besides, as mentioned in the previous message, it is not Administrator per we we need, but hyperv admin rights. In minishift we check for this. Try this and perhaps we can port this back to minikube.

**Comment by EagleIJoe** [comment]
This is a docker-machine issue, which I have fixed via the following PR: https://github.com/docker/machine/pull/4557

I ran into this using minikube and minishift and tracked it down to docker-machine.

**Comment by tstromberg** [comment]
Based on the comments, I suspect this just needs a new release based on a more recent docker/machine.

**Comment by tstromberg** [comment]
I believe this was addressed by v0.32. Please reopen if this is not the case!
