### ISSUE TITLE
none: Add support for non-systemd Linux distributions

### ISSUE THREAD

**Issue by andyxning** [kubernetes/minikube#2704]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT
  - With latest v0.26.0, `minikube start --vm-driver=none --kubernetes-version=v1.8.0 --logtostderr` failed to start on travis ci. For more info: https://travis-ci.org/kubernetes/kube-state-metrics/jobs/365005727

**Comment by asymmetric** [comment]
The [same thing](https://circleci.com/gh/kinvolk/habitat-operator/48) is happeninng on CircleCI.

It seems to be due to minikube expecting to find `systemctl`, which is not there on the CircleCi Ubuntu Trusty box at least (and I suspect on the Travis boxes either).

**Comment by dlorenc** [comment]
I think you'll need to pass --bootstrapper=localkube to work with the none driver in environments that don't have system for now.

**Comment by andyxning** [comment]
@dlorenc Is this the recommended way to work around systemd or this is a regression bug?

**Comment by dlorenc** [comment]
It's a bit of a regression caused by the switch from localkube to kubeadm by default. Kubeadm with the none driver requires systemd.

The other problem here is that travis only supports up to Ubuntu 14.04, and systemd was added in 16.04.

**Comment by andyxning** [comment]
@dlorenc seems we force use `--bootstrapper=localkube` is fine and it is ok even travis later bump Ubuntu from 14.04 to 16.04 if we have no strong dependency on kubeadm features.

**Comment by fabiand** [comment]
We are also experiencing this.

It sounds like travis will need some time to provide an image with systemd.
Thus I wonder if minikube could at least do a check if systemd is present, to output a warning if the kubeadm bootstrapper is used.

This would at least highlight the problem.

I am not sure what the right fix is tho (wait for travis update or fix it in minikube).

**Comment by andyxning** [comment]
@dlorenc @r2d4 @aaron-prindle

**Comment by andyxning** [comment]
Ping @dlorenc @r2d4 @aaron-prindle Any suggestions? Pinning on an old version of minikube is not so good from a long run perspective.

**Comment by andyxning** [comment]
Friendly ping.~

**Comment by gbraad** [comment]
You do know they are in a different timezone?

**Comment by andyxning** [comment]
Ping @dlorenc @r2d4 @aaron-prindle

**Comment by dlorenc** [comment]
The current options are to use an older version of minikube, force it to use the localkube bootstrapper or run it in an environment with systemd. Localkube is going to be deleted before the next Kubernetes release, so finding an environment with systemd will be the best option going forward.

**Comment by tstromberg** [comment]
To repeat what I said in #3174:

I agree that this situation sucks, but it's also not yet a top priority for us. If you end up finding a workable solution, I would love to hear about it and would happily review a patch for the issue.

**Comment by EvertonSA** [comment]
I was able to get it running by running `minikube start --vm-driver=none --extra-config=kubelet.cgroup-driver=systemd`
CentOS 7 machine running on OTC

**Comment by andyxning** [comment]
Ubuntu 16.04 is now the default ubuntu distribution version: https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment

**Comment by codebling** [comment]
The switch suggested above did not work for me on minikube 1.4.0. 
As a quick fix if you're not running systemd,
```
sudo touch /usr/bin/systemctl
sudo chmod a+r /usr/bin/systemctl
```
It's just an empty script, which only works because it returns a non-zero exit code, effectively bypassing the attempt to start `dockerd`. You'll need to manually start `dockerd` first.

I gave up on what I was trying when I ran into more issues but it got me past that hurdle

**Comment by medyagh** [comment]
this is still a feature that havent been implemented

not same but related in a way https://github.com/kubernetes/minikube/issues/4172

**Comment by medyagh** [comment]
related https://github.com/kubernetes/minikube/issues/6954

we still need to do this ! anyone interested ?

**Comment by prietyc123** [comment]
We need to pass ```--bootstrapper=localkube``` to work with the none driver in environments to start minikube like ```minikube start --vm-driver=none --bootstrapper=localkube --kubernetes-version=v1.10.0``` . While doing this it should be kept in mind that we are using the older version of minikube which comes before ```v0.26+``` and kubernetes version which support ```--bootstrapper=localkube``` .

**Comment by afbjorklund** [comment]
Support for `localkube` and `v1.10.0` has been suspended (in 2018), suggest looking at `k3s` if you want something similar for modern kubernetes versions. Minikube now uses `kubeadm` and `v1.18.0`.

**Comment by tstromberg** [comment]
We fixed this by adding support for OpenRC.
