### ISSUE TITLE
kubeadm with None driver deletes other local docker images

### ISSUE THREAD

**Issue by bh4rtp** [kubernetes/minikube#2705]
The minikube 0.26.0 was installed successfully. But there is a serious problem. On my ubuntu 16.04 virtualbox vm, I have pulled k8s images for minikube dashboard. After running `sudo -E minikube start --vm-driver=none`, all the docker images including my private images such as hyperledger fabric are deleted without any notification!!

**Comment by bh4rtp** [comment]
the docker images are deleted when running `minikube dashboard`, not `minikube start`.

**Comment by antonyisoardi** [comment]
Yeah I had something like this as well, except it's not when you start dashboard or start Minikube.

I reverted to 0.25 and everything went back to normal.

**Comment by bh4rtp** [comment]
i am using 0.25.0. yesterday, all my local docker images were deleted too. feel strange.

**Comment by altairpearl** [comment]
I am also seeing this, although I'm using minikube V0.28.0. Any update on this issue?

**Comment by dlorenc** [comment]
My guess is that this is the kubelet image garbage collector. It's probably unavoidable when using the none driver - the kubelet assumes full control over the machine and docker daemon.

**Comment by tstromberg** [comment]
It would be nice if kubeadm, or at least ourselves, could detect this possibility and prompt the user rather than quietly deleting everything.

**Comment by bhack** [comment]
Can we interact with https://github.com/kubernetes/kubernetes/issues/68930 to find a solution?

**Comment by zhangmingld** [comment]
> It would be nice if kubeadm, or at least ourselves, could detect this possibility and prompt the user rather than quietly deleting everything.

we add some code in kubelet that user can specify a list of image that garbage will ignore here 
maybe it can fix this
https://github.com/kubernetes/kubernetes/pull/68549

**Comment by tstromberg** [comment]
FWIW, If this was indeed caused by the kubelet reaping disk space, I believe this was fixed by #3671
