### ISSUE TITLE
docker-env http_proxy: Get 192.168.39.49:8443/api/v1/nodes/minikube: Service Unavailable

### ISSUE THREAD

**Issue by julienfr112** [kubernetes/minikube#2706]
`minikube start --vm-driver="kvm2" --docker-env="http_proxy=$http_proxy" --docker-env="https_proxy=$https_proxy" start`

 Error starting cluster:  timed out waiting to unmark master: getting node minikube: Get https://192.168.39.49:8443/api/v1/nodes/minikube: Service Unavailable

minikube version: v0.26.0
OS
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
"DriverName": "kvm2",
"Boot2DockerURL": "file:///home/julien/.minikube/cache/iso/minikube-v0.26.0.iso",
        "ISO": "/home/julien/.minikube/machines/minikube/boot2docker.iso",

**Comment by gdamberg** [comment]
Same result for me, using virtualbox

```
minikube start --docker-env "HTTPS_PROXY=http://proxy:808" --docker-env 
"HTTP_PROXY=http://proxy:808"  --docker-env "NO_PROXY=localhost,127.0.0.1,192.168.0.0/16"

Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
150.53 MB / 150.53 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.10.0
Downloading kubelet v1.10.0
Finished Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0411 11:52:58.268126    4720 start.go:276] Error starting cluster:  timed out waiting to unmark master: getting node minikube: Get https://192.168.99.100:8443/api/v1/nodes/minikube: Service Unavailable
================================================================================
```
workaround:
```
export NO_PROXY="$NO_PROXY,192.168.0.0/16";minikube start --docker-env "HTTPS_PROXY=http://proxy:808" --docker-env 
"HTTP_PROXY=http://proxy:808"  --docker-env "NO_PROXY=localhost,127.0.0.1,192.168.0.0/16"
```

**Comment by alobaidizt** [comment]
Thanks @gdamberg!! Your solution has solved my problem. Can you please explain your solution?

**Comment by gdamberg** [comment]
@alobaidizt `export NO_PROXY="$NO_PROXY,192.168.0.0/16"`- make sure that I have set the no_proxy env variable in the current shell. 


`minikube start --docker-env "HTTPS_PROXY=http://proxy:808" --docker-env 
"HTTP_PROXY=http://proxy:808"  --docker-env "NO_PROXY=localhost,127.0.0.1,192.168.0.0/16"` - start minikube and pass the same no_proxy setting to docker

Specifying 192.168.0.0/16 as the range of ipaddresses that shouldnt go through the Proxy as this is the range (I think) that minikube generate its ip in (and i'm certain that I dont have anything else in that range)

**Comment by alobaidizt** [comment]
Thanks @gdamberg!
