### ISSUE TITLE
Minikube 0.26.0 fails to start with RBAC enabled

### ISSUE THREAD

**Issue by wfhartford** [kubernetes/minikube#2712]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

Please provide the following details:

**Environment**:

```
minikube version: v0.26.0

OS:
NAME="Linux Mint"
VERSION="18.3 (Sylvia)"
ID=linuxmint
ID_LIKE=ubuntu
PRETTY_NAME="Linux Mint 18.3"
VERSION_ID="18.3"
HOME_URL="http://www.linuxmint.com/"
SUPPORT_URL="http://forums.linuxmint.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/linuxmint/"
VERSION_CODENAME=sylvia
UBUNTU_CODENAME=xenial

VM driver:
    "DriverName": "kvm2",

ISO version
        "Boot2DockerURL": "file:///home/wesley/.minikube/cache/iso/minikube-v0.26.0.iso",
        "ISO": "/home/wesley/.minikube/machines/minikube/boot2docker.iso",
```

**What happened**:
Minikube start command (`minikube start --vm-driver kvm2 --extra-config=apiserver.Authorization.Mode=RBAC`) hangs for a very long time at `Starting cluster components...` then outputs some error logs, see https://gist.github.com/wfhartford/aa3b701199ee307522b244f008da3b65

**What you expected to happen**:
Minikube should start with RBAC enabled. Version v0.25.2 behaves as expected.

**How to reproduce it** (as minimally and precisely as possible):
`minikube start --vm-driver kvm2 --extra-config=apiserver.Authorization.Mode=RBAC`

**Output of `minikube logs` (if applicable)**:
[minikube-logs.txt.gz](https://github.com/kubernetes/minikube/files/1900351/minikube-logs.txt.gz)

**Anything else do we need to know**:

**Comment by the-redback** [comment]
Since minikube 26.0, `kubeadm` is the default bootstrapper for minikube.

For `kubeadm`, the extra-config `key:value` pair is slightly different. 
It is mentioned in  [documentation of minikube](https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md#kubeadm-bootstrapper.).

In this case, the correct command will be: 

```console
$ minikube start \
    --vm-driver kvm2 \
    --extra-config=apiserver.authorization-mode=RBAC
```

Furthermore, in `kubeadm`, the default authorization mode has already been set to `RBAC` and `Node`. 
So, you can skip providing `extra-config` flag for RBAC enabled minikube.

```console
$ minikube start --vm-driver kvm2
```

**Comment by wfhartford** [comment]
Thank you, that revised command works for me.

The documentation you linked to includes the older command in the examples section.

**Comment by fr3dm4n** [comment]
I ran into the same error.  Its strange how an obsolete option can block the cluster setup. :thinking:

**Comment by chrissound** [comment]
TBH this should not be closed.

Ideally we should validate / report an error if this parameter is NOT VALID.
And secondly the logs surely should say something more descriptive than just "node "minikube" not found".
