### ISSUE TITLE
Minikube 0.26.0 - config set vm-driver none error

### ISSUE THREAD

**Issue by BenHall** [kubernetes/minikube#2727]
```
$ minikube config set vm-driver none
[Driver none is not supported]
```

This worked within 0.26.0 and `minikube start --vm-driver=none` is accepted.

**Comment by BenHall** [comment]
I believe it's because "None" is missing from the constants.  

https://github.com/kubernetes/minikube/blob/b27a989c86969549e3eb2924b1105e9eee55ba01/pkg/minikube/constants/constants.go#L49-L57

**Comment by afbjorklund** [comment]
Curiosly, it only says "used in gendocs" ?

**Comment by BenHall** [comment]
Back tracking it a little and how I go there.

https://github.com/kubernetes/minikube/blob/37fd0f0a29f4c96e509d990bace0b1391d210635/cmd/minikube/cmd/config/validations.go#L32-L39

https://github.com/kubernetes/minikube/blob/0bf5166e1453ae7bbf16f98e801582762247815a/cmd/minikube/cmd/config/config.go#L50

**Comment by afbjorklund** [comment]
Just saying - that comment is wrong...

**Comment by pauldamian** [comment]
Hey guys,
I've just installed minikube v.0.28 on Windows and I want to use it with Docker, so I've started it using vm-driver none, but it keeps failing, saying that it is not supported:
```
C:\Users\Paul>minikube version
minikube version: v0.28.0

C:\Users\Paul>minikube start --vm-driver=none
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
F0622 15:02:14.986424    3140 cluster.go:212] Unsupported driver: none
```

Is there some configuration that I overlooked?
