### ISSUE TITLE
ServiceNodePortRange blocks minikube from starting

### ISSUE THREAD

**Issue by carlos-gi** [kubernetes/minikube#2733]
BUG REPORT

When we try to start minikube with the ServiceNodePortRange parameter never gets completed:
minikube start --extra-config=apiserver.ServiceNodePortRange=1-50000

**Environment**:
MacOS High Sierra Version 10.13.4
Minikube installed with brew:
brew cask install minikube

Minikube version installed by brew: v0.26
**Minikube version** v0.26
- **OS** : MacOS High Sierra Version 10.13.4
- **VM Driver** : "virtualbox"
- **ISO version** : "file:///Users/cmora/.minikube/cache/iso/minikube-v0.26.0.iso"
- **Install tools**: brew cask install minikube

**What happened**:
The start never gets completed, it breaks after 10 minutes:
$ minikube start --extra-config=apiserver.ServiceNodePortRange=1-50000
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0417 10:28:46.813981   34989 start.go:281] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition

**What you expected to happen**:
It should start allowing nodePorts in the specified range

**How to reproduce it** :
Execute on the Mac High Sierra:
    brew cask install minikube
    minikube start --extra-config=apiserver.ServiceNodePortRange=1-50000

**Comment by techadrian** [comment]
Hello,
I am facing the same issue on Windows 10 and minikube version: v0.26.1 . Managed to reproduce the exact behaviour as explained above on MacOS.
