### ISSUE TITLE
minikube status is broken

### ISSUE THREAD

**Issue by PI-Victor** [kubernetes/minikube#2743]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:
MacOS
**Minikube version** (use `minikube version`):
minikube version: v0.26.0
- **OS** 
 System Version: macOS 10.13.3 (17D102)
      Kernel Version: Darwin 17.4.0
- **VM Driver** hyperkit
- **ISO version**  Boot2DockerURL": ~/.minikube/cache/iso/minikube-v0.26.0.iso

**What happened**:
minikube status is is broken

```
 ~/.minikube: minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.64.34
 ~/.minikube: minikube status
E0418 09:53:35.972462   26020 status.go:85] Error cluster status: Error: Unrecognized output from ClusterStatus: Running
~/.minikube: minikube status
E0418 09:53:39.347545   26049 status.go:85] Error cluster status: Error: Unrecognized output from ClusterStatus: Running
DEHER1M1971 ~/.minikube
```

**What you expected to happen**:

minikube status outputs its proper status

**How to reproduce it** (as minimally and precisely as possible):

minikube status

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

I did some debugging and this is caused because [this check](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/bootstrapper/kubeadm/kubeadm.go#L72) -  mostly returns an empty string.

**Comment by OlafSzmidt** [comment]
Bump. Seeing this too.

**Comment by numbsafari** [comment]
Seems to only happen intermittently for me. Also on minikube v0.26.0.

**Comment by numbsafari** [comment]
I can confirm this also happens with v0.27.0 on MacOS.

**Comment by ivanbrennan** [comment]
I'm seeing in minikube v0.26.0 on NixOS too.

**Comment by Goorzhel** [comment]
v0.27.0, Void Linux. I use that distro to avoid systemctl, on which [the line referenced by OP](https://github.com/kubernetes/minikube/blob/4e63f34e2686e9359a839f209a52156c86abcc50/pkg/minikube/bootstrapper/kubeadm/kubeadm.go#L72) relies.

**Comment by undermink** [comment]
Seeing this on gentoo, too. (minikube version: v0.27.0, openrc instead of systemd)

**Comment by aaron-prindle** [comment]
fixed with https://github.com/kubernetes/minikube/pull/2894, closing
