### ISSUE TITLE
Minikube won't start on Win10/VirtualBox

### ISSUE THREAD

**Issue by markku63** [kubernetes/minikube#2746]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug report

Please provide the following details:

**Environment**: Windows 10 Professional, VirtualBox 5.2.8

**Minikube version** (use `minikube version`): v0.26.0

- **OS** (e.g. from /etc/os-release): Windows 10 Pro version 1709 build 16299.371
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):  v0.26.0

**What happened**:
[minikube_errors.txt](https://github.com/kubernetes/minikube/files/1923811/minikube_errors.txt)

**What you expected to happen**:
Normal start without errors

**How to reproduce it** (as minimally and precisely as possible):
minikube delete
minikube start

**Output of `minikube logs` (if applicable)**:
[minikube_log.txt](https://github.com/kubernetes/minikube/files/1923970/minikube_log.txt)

**Comment by jackdw-concur** [comment]
I see the same type of issues with 0.26.0, which I didn't see with any of the previous versions.  Can include any logs files if needed.

**Comment by markku63** [comment]
I updated Windows 10 to version 1803, Virtualbox to version 5.2.10 and minikube to version 0.26.1, and now Minikube starts normally. Closing this issue.

**Comment by jeetdighe** [comment]
I am experiencing same issue on Win 10 Enterprise ,Virtual box 5.2.24 and minikube 1.0.0 ,

Result Code: | E_FAIL (0x80004005)
-- | --
Component: | MachineWrap
Interface: | IMachine {85cd948e-a71f-4289-281e-0ca7ad48cd89}
