### ISSUE TITLE
Error executing in Docker Container: 137 on 4GB

### ISSUE THREAD

**Issue by theothermike** [kubernetes/minikube#275]
During testing of porting a Docker app to Kubernetes/Minikube for a nodejs app, I am re-installing the nodejs modules inside the only running running container (with a locally mapped hostPath). 

I start the container with 'sleep 3600'
and then exec -ti bash into it

About 30 seconds into doing anything (whether module install or not), it drops me out and restarts with error:

error: error executing remote command: error executing command in container: Error executing in Docker Container: 137

After googling, I see this could be related to memory usage, so I re-created the minikube with --memory=4096, which should be much more than enough (for example, we also use Docker Machine to develop, which is just 2GB and have never had memory issues, regularly running 10 containers), but it still happens consistently after about 20-30 seconds of doing anything inside the container

using 0.4.0 release, downloaded today

**Comment by dlorenc** [comment]
Hey,

Sorry you're having trouble. Could you provide the command you're trying to run? The package.json might be useful so I can reproduce the issue.

**Comment by theothermike** [comment]
docker image is 'node:4'

simply running npm install

below is relevant package.json depdencies/devDependencies

 "dependencies": {
    "async": "0.9.0",
    "bcrypt": "~0.8.5",
    "big.js": "~3.1.3",
    "csv": "^0.4.6",
    "curry": "0.0.4",
    "db-migrate": "0.6.4",
    "decamelize": "^1.2.0",
    "dot": "^1.0.3",
    "elasticsearch": "^10.1.3",
    "enumify": "^1.0.4",
    "jsonschema": "^1.0.2",
    "libphonenumber": "0.0.9",
    "lodash": "^4.11.2",
    "mixpanel": "~0.3.1",
    "moment": "~2.10.3",
    "moment-timezone": "^0.4.0",
    "node-slack": "0.0.7",
    "node-uuid": "1.4.1",
    "nodemailer": "0.7.1",
    "pg": "4.4.2",
    "pg-parse-float": "0.0.1",
    "postmark": "^1.0.0",
    "prompt": "1.0.0",
    "q": "~1.4.1",
    "restify": "^4.0.4",
    "shopify-node-api": "^1.6.2",
    "sprintf-js": "^1.0.3",
    "ssl-root-cas": "^1.1.10",
    "stripe": "^4.0.0",
    "url": "~0.11.0",
    "ursa": "^0.9.1",
    "validator": "~3.41.3"
  },
  "devDependencies": {
    "eslint": "2.5.3",
    "form-data": "^1.0.0-rc4",
    "mocha": "1.18.2",
    "mocha-eslint": "2.0.2",
    "should": "~7.0.1",
    "stripe-mock-data": "^1.0.3"
  },

there are two private git repo's I omitted, but if the above works, it might be worhtwhile trying adding some like:

    "some-project": "git+ssh://git@bitbucket.org:some/project.git",

**Comment by dlorenc** [comment]
@aaron-prindle, can you try to repro this?

**Comment by dlorenc** [comment]
Hey,

I tried the following and was unable to repro:

```shell
kubectl run node --image=node:4 --command -- sleep 3600
 # kubectl get pods to find the pod name...
kubectl exec -it node-1799918556-za2ab bash
```

Then I ran a bunch of npm commands, waited for awhile and never got bumped with that error.

Could you see if this still reproduces with minikube 0.5? Re-open if you're still having trouble.

**Comment by dmcnaught** [comment]
I'm seeing this error, and it seems like it's when my exec readiness probe fails.
