### ISSUE TITLE
not able to start minikube  on mac

### ISSUE THREAD

**Issue by anhtv08** [kubernetes/minikube#2753]
Hi,
I am trying to setup minikube on my mac machine

Below are environment:
```
nhs-MBP:~ anhtrang$ minikube version
minikube version: v0.26.1
anhs-MBP:~ anhtrang$ echo "";

anhs-MBP:~ anhtrang$ echo "OS:";
OS:
anhs-MBP:~ anhtrang$ cat /etc/os-release
cat: /etc/os-release: No such file or directory
anhs-MBP:~ anhtrang$ echo "";

anhs-MBP:~ anhtrang$ echo "VM driver":
VM driver:
anhs-MBP:~ anhtrang$ grep DriverName ~/.minikube/machines/minikube/config.json
    "DriverName": "virtualbox",
anhs-MBP:~ anhtrang$ echo "";

anhs-MBP:~ anhtrang$ echo "ISO version";
ISO version
anhs-MBP:~ anhtrang$ grep -i ISO ~/.minikube/machines/minikube/config.json
        "Boot2DockerURL": "file:///Users/anhtrang/.minikube/cache/iso/minikube-v0.26.0.iso",
```

Got following error:

```
nhs-MBP:~ anhtrang$ Starting local Kubernetes v1.10.0 cluster...
-bash: Starting: command not found
anhs-MBP:~ anhtrang$ Starting VM...
-bash: Starting: command not found
anhs-MBP:~ anhtrang$ E0420 08:24:57.963653   81977 start.go:159] Error starting host: Temporary Error: Error configuring auth on host: OS type not recognized.
```

Please advise

**Comment by mgdevstack** [comment]
Not able to start minikube 0.26.1, 0.26.0 and 0.25.2. Till yesterday all were working good. What kind of precreate checks run ?

Error:
`E0421 00:07:25.299335   69121 start.go:159] Error starting host: Error creating host: Error executing step: Running precreate checks.`

![image](https://user-images.githubusercontent.com/8110509/39068065-a370cf04-44f8-11e8-9757-a352b0c24edc.png)

**Comment by AishSundar** [comment]
/assignee @BenTheElder 
/cc @krzyzacy 

The vendors trying to write conformance tests seem to be blocked a lot on getting clusters up and running via Minikube. Is there a workaround or solution to help them be more productive. Can either of you please look at the error and advise a better developer workflow for them? Thanks.

**Comment by AishSundar** [comment]
Is there any alternative to Minikube that they can use for testing during development? Can the run their cases against a GKE cluster?

**Comment by mati865** [comment]
The same error on Arch Linux since upgrading to 0.26.x.

**Comment by johnhamelink** [comment]
I'm also experiencing this on Arch with the KVM2 driver

**Comment by fabriziocucci** [comment]
Same issue on macOS Sierra (version 10.12.6) with minikube `0.26.1`.

I had to downgrade minikube to `0.25.2`:
```bash
brew cask uninstall minikube
brew cask install https://raw.githubusercontent.com/caskroom/homebrew-cask/c899e526fa6e9211be92c4454ff9a7bb410622bc/Casks/minikube.rb
```

**Comment by nicknovitski** [comment]
I was able to start clusters with 0.26.1 and the hyperkit driver.  High Sierra 10.13.4.

**Comment by hongsw** [comment]
```
rm -rf ~/.minikube
minikube start --logtostderr --v=3
```

!! DO NOT KILL minikube by CTRL-C 
MUST use 

`
minikube stop
`

ref. https://medium.com/@maumribeiro/troubleshooting-annoying-issues-with-minikube-34486955fc54

**Comment by charlseo** [comment]
Tried with 0.34.1 still not working so rolled back to 0.25.2 and it's fine.
