### ISSUE TITLE
Retain folder structure when copying files from ~/.minikube/files

### ISSUE THREAD

**Issue by vinceho** [kubernetes/minikube#2768]
**Environment**:

- **Minikube version**: v0.26.1
- **OS**: Ubuntu 16.04
- **VM Driver**: virtualbox
- **ISO version**: v0.26.0

**What happened**:
When Minikube copies files onto the VM from ~/.minikube/files, the folder structure is not retained.

**What you expected to happen**:
On the host:
```
~/.minikube/files$ find . | sort
.
./abc
./abc/1.txt
./def
./def/2.txt
./def/ghi
./def/ghi/3.txt
```

However, when the VM is provisioned, all the files are put onto the first directory with content.
```
$ minikube ssh find /abc
/abc
/abc/3.txt
/abc/2.txt
/abc/1.txt
```

I expect the copied files to match the structure on my host.

**How to reproduce it**:
1. Create a nested folder structure in `~/.minikube/files` with some files.
    ```
    cd ~/.minikube/files
    mkdir -p {abc,def/ghi}
    touch abc/1.txt
    touch def/2.txt
    touch def/ghi/3.txt
    ```

2. Start Minikube with `minikube start --kubernetes-version v1.10.0 --bootstrapper=kubeadm`.

3. After completion, check the VM for the files with `minikube ssh find /abc`.

**Comment by sslavic** [comment]
This issue is even worse on Windows:

- directories on VM get flattened compared to the source, as if Windows path separator `\` just gets ignored/removed for directories
- additionally destination is also not consistent with when minikube is run on Mac - instead of root `/`, files end up in `/home/docker` subdirectory.

E.g. `C:\Users\foo\.minikube\files\foo\bar\baz.txt` would end up in `/home/docker/foobar/baz.txt`

BTW copying of `~/.minikube/files` to VM was added via https://github.com/kubernetes/minikube/issues/1914 / https://github.com/kubernetes/minikube/pull/1917

**Comment by mmhelm** [comment]
The function parameter `vmpath` gets overwritten in the `filepath.Walk` function.
```
func addMinikubeDirToAssets(basedir, vmpath string, assets *[]CopyableFile) error {
    err := filepath.Walk(basedir, func(hostpath string, info os.FileInfo, err error) error {
        ...
        if !isDir {
            if vmpath == "" {
                ...
                vmpath = filepath.Join("/", rPath)
            }
            ...
            f, err := NewFileAsset(hostpath, vmpath, filepath.Base(hostpath), permString)
            ...
            *assets = append(*assets, f)
        }
        ...
    })
    ...
}
```
Thus after one iteration `vmpath` is never updated again and all `FileAsset`s get the same target path. Fixed it in #3075 but I didn't focus on the issue on Windows @sslavic described above.

**Comment by smiron** [comment]
Any idea how to solve this on windows?

**Comment by darkedges** [comment]
Does not work via git-bash on windows either.

My file structure
`$MINIKUBE_HOME\.minikube\files\etc\ssl\certs\xxx.pem` get squashed to `/home/docker/etcsslcerts/xxx.pem`

I am expecting to find the file in `/etc/ssl/certs/xxx.pem`

**Comment by mmhelm** [comment]
@darkedges Could you please check if it works with pull request #3075?

**Comment by darkedges** [comment]
Will have a look. Having some issues building via docker on windows.

**Comment by darkedges** [comment]
@mmhelm It does not appear to work, directories are still squashed into the home directory.

**Comment by darkedges** [comment]
This seems to resolve it for me, https://github.com/kubernetes/minikube/pull/3258 will try and work out the CLA problem.

In essenc convert the path to unix format via 
```
rPath = filepath.ToSlash(rPath)
vmpath = path.Join("/", rPath)
```

**Comment by gclawes** [comment]
I'm seeing a very similar issue on 0.30.0:
```
~ $ find ~/.minikube/files
/Users/gralaw/.minikube/files
/Users/gralaw/.minikube/files/etc
/Users/gralaw/.minikube/files/etc/ssl
/Users/gralaw/.minikube/files/etc/ssl/certs
/Users/gralaw/.minikube/files/etc/ssl/certs/ca-certificates.crt
/Users/gralaw/.minikube/files/etc/profile.d
/Users/gralaw/.minikube/files/etc/profile.d/proxy.sh
```
```
$ ls -lah /etc/profile.d
total 316K
drwxr-xr-x  2 root root    0 Dec  3 17:00 .
drwxr-xr-x 30 root root    0 Dec  3 17:00 ..
-rwxr-xr-x  1 root root 305K Dec  3 17:00 ca-certificates.crt
-rw-r--r--  1 root root  513 Dec  3 17:00 proxy.sh
-rw-r--r--  1 root root   10 Oct  5 20:05 umask.sh
```

**Comment by tstromberg** [comment]
Can someone confirm if this bug still exists in v0.33.1? There have been some recent changes to Windows file handling.

**Comment by feniix** [comment]
@tstromberg I can confirm that still exists in 0.33.1

**Comment by darkedges** [comment]
Works with 1.0.0 for me

```
C:\Users\NIrving\.minikube\files>minikube version
minikube version: v1.0.0

C:\Users\NIrving\.minikube\files>dir /s /b
C:\Users\NIrving\.minikube\files\etc
C:\Users\NIrving\.minikube\files\etc\profile.d
C:\Users\NIrving\.minikube\files\etc\ssl
C:\Users\NIrving\.minikube\files\etc\profile.d\test.txt
C:\Users\NIrving\.minikube\files\etc\ssl\test.txt

C:\Users\NIrving\.minikube\files>minikube ssh
                         _             _
            _         _ ( )           ( )
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ ls -la
total 0
drwxr-xr-x 3 docker docker 0 Mar 31 21:00 .
drwxr-xr-x 3 root   root   0 Mar 26 03:03 ..
drwx------ 2 docker docker 0 Mar 31 21:00 .ssh
$ ls -l /etc/profile.d
total 4
-rw-r--r-- 1 root root  0 Mar 31 21:01 test.txt
-rw-r--r-- 1 root root 10 Mar 26 02:15 umask.sh
$ ls -l /etc/ssl/test.txt
-rw-r--r-- 1 root root 0 Mar 31 21:01 /etc/ssl/test.txt
````

**Comment by darkedges** [comment]
But fails with v0.33.1

```
C:\Users\NIrving\Downloads>minikube-windows-amd64.exe version
minikube version: v0.33.1
C:\Users\NIrving\Downloads>minikube ssh
                         _             _
            _         _ ( )           ( )
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ ls
etcprofile.d
```
