### ISSUE TITLE
Unable to start minikube on OSX(Behind proxy)

### ISSUE THREAD

**Issue by lokeshmadan** [kubernetes/minikube#2771]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.25.2
- **OS** (e.g. from /etc/os-release): MACOS Sierra 10.12.6 (16G1212)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.25.1.iso

**What happened**:
I am trying to install minikube(I am on cisco vpn and sitting behind the proxy). I have installed minikube and kubectl(Verified by running kubectl and minikube commands). 

 While trying to build machine using below command it falls on the face.

Command :  minikube start --vm-driver=xhyve --docker-env http_proxy=http://my-proxy:80 --docker-env https_proxy=http://my-proxy:80 --docker-env no_proxy=192.168.99.0/24,127.0.0.1,localhost,*.local-domain,*.corp-local-domain.com --docker-env --alsologtostderr

Error : 

W0427 09:53:18.501562   18789 root.go:148] Error reading config file at /Users/me/.minikube/config/config.json: open /Users/me/.minikube/config/config.json: no such file or directory
I0427 09:53:18.503919   18789 notify.go:109] Checking for updates...
There is a newer version of minikube available (v0.26.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.26.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
I0427 09:53:18.771163   18789 cache_images.go:292] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.1 at /Users/me/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.8.1
I0427 09:53:18.771197   18789 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.5 at /Users/me/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.5
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
I0427 09:53:18.771352   18789 cluster.go:70] Machine does not exist... provisioning new machine
I0427 09:53:18.771362   18789 cluster.go:71] Provisioning machine with config: {MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v0.25.1.iso Memory:2048 CPUs:2 DiskSize:20000 VMDriver:xhyve XhyveDiskDriver:ahci-hd DockerEnv:[http_proxy=http://my-proxy:80 https_proxy=http://my-proxy:80 no_proxy=192.168.99.0/24,127.0.0.1,localhost,*.local-domain,*.corp-local-domain.com] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID:}
Downloading Minikube ISO
I0427 09:53:18.771425   18789 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.5 at /Users/me/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.5
I0427 09:53:18.771449   18789 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.5 at /Users/me/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0427 09:53:18.771465   18789 cache_images.go:292] Attempting to cache image: gcr.io/google-containers/kube-addon-manager:v6.5 at /Users/me/.minikube/cache/images/gcr.io/google-containers/kube-addon-manager_v6.5
I0427 09:53:18.771477   18789 cache_images.go:292] Attempting to cache image: k8s.gcr.io/pause-amd64:3.0 at /Users/me/.minikube/cache/images/k8s.gcr.io/pause-amd64_3.0
I0427 09:53:18.771173   18789 cache_images.go:292] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.0 at /Users/me/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.0
 17.28 MB / 142.22 MB [=====>------------------------------------]  12.15% 2m40s^C
me-mac:Desktop me$ minikube start --vm-driver=hyperkit --docker-env http_proxy=http://my-proxy:80 --docker-env https_proxy=http://my-proxy:80 --docker-env no_proxy=192.168.99.0/24,127.0.0.1,localhost,*.local-domain,*.corp-local-domain.com --alsologtostderr
W0427 09:54:02.575160   19013 root.go:148] Error reading config file at /Users/me/.minikube/config/config.json: open /Users/me/.minikube/config/config.json: no such file or directory
I0427 09:54:02.576182   19013 cache_images.go:292] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.0 at /Users/me/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.0
I0427 09:54:02.576209   19013 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.5 at /Users/me/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.5
I0427 09:54:02.576182   19013 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.5 at /Users/me/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0427 09:54:02.576212   19013 cache_images.go:292] Attempting to cache image: gcr.io/google-containers/kube-addon-manager:v6.5 at /Users/me/.minikube/cache/images/gcr.io/google-containers/kube-addon-manager_v6.5
I0427 09:54:02.576224   19013 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.5 at /Users/me/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.5
Starting local Kubernetes v1.9.4 cluster...
I0427 09:54:02.576182   19013 cache_images.go:292] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.1 at /Users/me/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.8.1
Starting VM...
I0427 09:54:02.576239   19013 cache_images.go:292] Attempting to cache image: k8s.gcr.io/pause-amd64:3.0 at /Users/me/.minikube/cache/images/k8s.gcr.io/pause-amd64_3.0
I0427 09:54:02.576339   19013 cache_images.go:79] Successfully cached all images.
I0427 09:54:02.576343   19013 cluster.go:70] Machine does not exist... provisioning new machine
I0427 09:54:02.576352   19013 cluster.go:71] Provisioning machine with config: {MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v0.25.1.iso Memory:2048 CPUs:2 DiskSize:20000 VMDriver:xhyve XhyveDiskDriver:ahci-hd DockerEnv:[http_proxy=http://my-proxy:80 https_proxy=http://my-proxy:80 no_proxy=192.168.99.0/24,127.0.0.1,localhost,*.local-domain,*.corp-local-domain.com] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID:}
Downloading Minikube ISO
 142.22 MB / 142.22 MB [============================================] 100.00% 0s
E0427 09:57:56.889681   19013 start.go:159] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91.

 Retrying.
E0427 09:57:56.890895   19013 start.go:165] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
Temporary Error: Could not find an IP address for 9a:be:d0:f6:9a:91
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
Y

When i typed : minikube logs -f , i got below output

F0427 10:58:35.685596   24280 logs.go:50] Error getting cluster bootstrapper: getting localkube bootstrapper: getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**What you expected to happen**:

kubetnetes cluster should have been created

**How to reproduce it** (as minimally and precisely as possible):

Running above commands

**Output of `minikube logs` (if applicable)**:
F0427 10:58:35.685596   24280 logs.go:50] Error getting cluster bootstrapper: getting localkube bootstrapper: getting ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Anything else do we need to know**:

**Comment by dlorenc** [comment]
Can you try this with the hyperkit driver? The xhyve one is no longer maintained.

**Comment by lokeshmadan** [comment]
@dlorenc  : Thanks for the comment. I have tried both with hyperkit and xhyve, but got same response. I Should have updated with logs.
