### ISSUE TITLE
minikube install via yum: cannot execute binary file

### ISSUE THREAD

**Issue by GitBytes** [kubernetes/minikube#2772]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: CentOS Linux release 7.4.1708 (Core) (Kernel ver. 3.10.0-514.36.5.el7.x86_64)

**Minikube version**: 0.24.0-1.el7.centos
- **OS**: CentOS Linux release 7.4.1708 (Core)
- **VM Driver**: virtualbox
- **ISO version**: N/A
- **Install tools**: yum
- **Others**: Installed via repo provided [here](https://copr.fedorainfracloud.org/coprs/antonpatsev/minikube-rpm/) referenced from [here in the README](https://github.com/kubernetes/minikube#other-ways-to-install)

**What happened**:
 * Added referenced yum repository via link from the README
 * Installed minikube from yum repository
 * attempted to run the minikube binary per instructions

**What you expected to happen**:
```bash
~]$ /usr/local/bin/minikube
Minikube is a CLI tool that provisions and manages single-node Kubernetes clusters optimized for development workflows.
crop...
```

**How to reproduce it** (as minimally and precisely as possible):
```bash
~]$ wget https://copr.fedorainfracloud.org/coprs/antonpatsev/minikube-rpm/repo/epel-7/antonpatsev-minikube-rpm-epel-7.repo
~]$ sudo yum clean all
crop..
~]$ sudo yum install -y minikube
crop...
~]$ which minikube
/usr/local/bin/minikube
~]$ /usr/local/bin/minikube
-bash: /usr/local/bin/minikube: cannot execute binary file
~]$ sudo /usr/local/bin/minikube
-bash: /usr/local/bin/minikube: cannot execute binary file
```

**Output of `minikube logs` (if applicable)**:
```bash
-bash: /usr/local/bin/minikube: cannot execute binary file
```

**Anything else do we need to know**:
Not that I am aware of.

**Comment by dlorenc** [comment]
I don't think we publish an official yum package, but this looks like an issue with that installer. I'm going to close this here, see the list of officially maintained installers here:
https://github.com/kubernetes/minikube#other-ways-to-install
