### ISSUE TITLE
`minikube service --url --https` flags don't play well together

### ISSUE THREAD

**Issue by paultiplady** [kubernetes/minikube#2773]
BUG REPORT
**Environment**:

- **Minikube version** (use `minikube version`): v0.25.0
- **OS**: MacOS 10.11.6
- **VM Driver**:  "virtualbox"
- **ISO version**: minikube-v0.25.1.iso

**What happened**:
When exposing a service which has both `http` and `https` ports, `minikube service servicename --url` returns one valid and one invalid URL.

If I run `minikube service servicename`, then I unambiguously get directed to the HTTP port in the browser. And if I run `minikube service servicename --https`, then I get directed to the HTTPS port. This is as expected.

If I run `minikube service servicename --url`, then I get this:

```
http://192.168.99.100:32088
http://192.168.99.100:30006
```

One of these is the http port, one is https. I believe we should only return the http port here.

Likewise if I run `minikube service servicename --url --https`, then the output is even more clearly unexpected:

```
https://192.168.99.100:32088
https://192.168.99.100:30006
```

It's the same two URLs, just with the https scheme in the URL.

This behaviour makes it impossible for me to programmatically select the http or https port, for example to load the correct URL into a test script. And in each case, one of the URLs is actually invalid.

**What you expected to happen**:

Running `minikube service servicename --url` should only return the http URL. 

Running `minikube service servicename --url --https` should only return the https URL.

OR if returning both when running without `--https`, they should at least have the correct scheme so that they can be correctly used.

**How to reproduce it**:

Run `minikube service servicename --url` with a service that exposes both http and https ports.

**Comment by Manouchehri** [comment]
I'm still running into the same issue. Can you reopen this @paultiplady?
