### ISSUE TITLE
minikube v0.26.1 start command fails on windows

### ISSUE THREAD

**Issue by afattahi54** [kubernetes/minikube#2775]
Get a fresh copy of  `minikube  v0.26.1` on windows 10 build 1703 and running below command

`````
minikube start
`````

generates this error

`````
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 150.53 MB / 150.53 MB [============================================] 100.00% 0s
E0429 14:12:39.630396    8604 start.go:159] Error starting host: Error creating host: Error executing step: Creating VM.
: open /Users/myuser/.minikube/cache/iso/minikube-v0.26.0.iso: The system cannot find the path specified..

`````
I am on windows and `/Users/myuser/.minikube/cache/iso/minikube-v0.26.0.iso` is not a correct path ! 

The iso `minikube-v0.26.0.iso` downloaded at `C:\Users\myuser\.minikube\cache\iso`
The Oracle VM version is 5.2.8

**Comment by DickChesterwood** [comment]
Which directory are you in when launching? I've noticed odd things happen if you're in a different drive to the location of the minikube exe (eg installed in C but currently on command line on drive D).

Are you launching from powershell, cmd or cygwin?
