### ISSUE TITLE
Minikube helm fails

### ISSUE THREAD

**Issue by clanstyles** [kubernetes/minikube#2778]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): ```BUG REPORT```

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): ```minikube version: v0.26.1```
- **OS** (e.g. from /etc/os-release): ```Debian GNU/Linux (Jesse)```
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):     "DriverName": "virtualbox",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):         "Boot2DockerURL": "file:///home/styles/.minikube/cache/iso/minikube-v0.26.0.iso",

- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):

**What happened**: Trying to delete a helm release just hangs.

**What you expected to happen**: Delete the release.

**How to reproduce it** (as minimally and precisely as possible): 
```helm install --name database stable/cockroachdb```
Wait for everything to come up
```helm delete database -debug```

**Output of `minikube logs` (if applicable)**:

```
helm delete services --debug
[debug] Created tunnel using local port: '49192'

[debug] SERVER: "localhost:49192"
```
**Anything else do we need to know**:

It seems to hang on tunneling back into the cluster.

**Comment by dlorenc** [comment]
This sounds like a helm bug, not a minikube one. Is there anymore info that makes yout hink this has to do with minikube?
