### ISSUE TITLE
vmwarefusion mount: attempted to get host ip address for unsupported driver

### ISSUE THREAD

**Issue by smebberson** [kubernetes/minikube#2789]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Bug report.

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.25.2
- **OS** (e.g. from /etc/os-release): MacOS v10.13.4 (17E199)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): vmwarefusion
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.25.1
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:

I ran `minikube mount ~/Developer/project/folder/:/mnt/project/folder` and got the error:
```
E0507 15:39:28.242867   24753 mount.go:113] Error getting the host IP address to use from within the VM:  Error, attempted to get host ip address for unsupported driver
```

**What you expected to happen**:

I expected it to work properly.

**How to reproduce it** (as minimally and precisely as possible):

Start minikube on MacOS with VMWare Fusion with:

- minikube start --vm-driver=vmwarefusion
- minikube mount ~/Developer/project/folder/:/mnt/project/folder

**Output of `minikube logs` (if applicable)**:

N/A

**Anything else do we need to know**:

Looks like it needs to be implemented here https://github.com/kubernetes/minikube/blob/f5d945597d46b17bd6a6683206801e540113de9b/pkg/minikube/cluster/cluster.go#L299

**Comment by cmbernard333** [comment]
I am bumping this issue. I am also seeing it and I am unable to start my minikube machine.

```executing: /Applications/VMware Fusion.app/Contents/Library/vmrun -gu docker -gp tcuser runScriptInGuest /Users/christianbernard/.minikube/machines/minikube/minikube.vmx /bin/sh [ ! -d /Users ]&& sudo mkdir /Users; sudo mount --bind /mnt/hgfs//Users /Users || [ -f /usr/local/bin/vmhgfs-fuse ]&& sudo /usr/local/bin/vmhgfs-fuse -o allow_other .host:/Users /Users || sudo mount -t vmhgfs -o uid=$(id -u),gid=$(id -g) .host:/Users /Users
E0606 12:19:50.159198     868 start.go:159] Error starting host: Error creating host: Error executing step: Creating VM.```

**Comment by fenos** [comment]
I confirm this behaviour as well, it just crashes, without being able to start.
Same stack trace as @cmbernard333
