### ISSUE TITLE
minikube delete does not asks for confirmation in case when /data has files

### ISSUE THREAD

**Issue by pucerpocok** [kubernetes/minikube#2794]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:
**Minikube version**: v0.26.1
**OS**: 
    Arch Linux
**VM Driver**:
    none
**ISO version**: 

**What happened**:
/data folder got deleted even when non minikube related files are there

**What you expected to happen**:
Either an error message telling me that the folder is not empty, or only those files are deleted which were put there by minikube.

**How to reproduce it** (as minimally and precisely as possible):
- Create a /data folder, and put there a file.
- Start minikube with vm-driver: none
- Execute "minikube delete".
- File in step1 is not there anymore

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

=========== old report ===========
Hi!
When minikube is started with vm-driver none (minikube start --vm-driver none)
it uses the /data folder for storing files.
But if that folder is existent, and has some files in it there is only some warnings in the log files.
Unfortunately I didn't know this, and I had a /data drive with a lot of files.
So it would be useful to increase the level of warning to error, or prompting for a confirmation when minikube delete is called.
(Also if there are other such folders, it would be good to include them in these checks.)

Thanks in advance!

**Comment by sorrowless** [comment]
Got the same just a couple minutes ago. Believe that's a critical bug, cause it deletes files from non-temporary directory which user can have before minikube installation.
