### ISSUE TITLE
--extra-config=apiserver.authorization-mode=RBAC causes minikube start to hang: unknown flag: --Authorization.Mode

### ISSUE THREAD

**Issue by wallrj** [kubernetes/minikube#2798]
The documentation at:
 * https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md#examples

Says:
 
> To set the AuthorizationMode on the apiserver to RBAC, you can use: --extra-config=apiserver.authorization-mode=RBAC.

But this causes Minikube to hang.

```
minikube start -v 10 --extra-config=apiserver.Authorization.Mode=RBAC
...
Setting up kubeconfig...
Starting cluster components...
^C

```

The API server no longer accepts that command line argument:

```
$ minikube ssh
$ docker logs 9f3405f5237a
Error: unknown flag: --Authorization.Mode
Usage:
  kube-apiserver [flags]

...
```

```
$ minikube version
minikube version: v0.26.1
```

```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.6", GitCommit:"6260bb08c46c31eea6cb538b34a9ceb3e406689c", GitTreeState:"clean", BuildDate:"2017-12-21T06:34:11Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by debtcollapse** [comment]
I ran into this same issue after upgrading to v0.26.1. 

This workaround fixed it for me: `--extra-config=apiserver.authorization-mode=RBAC`.

**Comment by jpiccaluga** [comment]
This issue is still present in last release v28.2 . IS it possible to fix it?
Last working version was v25.2

**Comment by mukgupta** [comment]
+1

**Comment by jpiccaluga** [comment]
In fact the flag  --extra-config=apiserver.Authorization.Mode=RBAC is no longuer valide after version v25.2.
You must use --extra-config=apiserver.authorization-mode=RBAC instead of --extra-config=apiserver.Authorization.Mode=RBAC. 

IMHO it would have been preferable to deprecated the old flag before to make it unusable.

**Comment by tstromberg** [comment]
Obsolete: documentation was updated, RBAC is default.
