### ISSUE TITLE
Support for Windows

### ISSUE THREAD

**Issue by vishh** [kubernetes/minikube#28]
Minikube should eventually run on Windows.

**Comment by rodcloutier** [comment]
I can help with testing and maybe working on this issue if needed

**Comment by dlorenc** [comment]
Awesome. There are a few areas I know won't work today (but should be easyish to fix). I'll add links here  to those spots.

**Comment by dlorenc** [comment]
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/constants/constants.go#L28
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/env.go

are two places we'll need to make changes.

**Comment by rodcloutier** [comment]
I am making progress compiling on Windows. I currently have the following error when trying to start a cluster:

```
E0530 23:54:39.800444   17436 start.go:58] Error starting host:  Error creating new host: Driver "virtualbox" not found. Do you have the plugin binary accessible in your PATH?
```
Any idea to fix this? Isn't the virtualbox plugin native to libmachine?

**Comment by dlorenc** [comment]
Thank for the help!

Unfortunately none of the plugins are fully "native" anymore. Machine uses an inter-process RPC system to communicate with plugins, so there's an extra process involved no matter what.

Some of the plugins are compiled into the machine binary, so they're available without any extra installation, but it's at least an extra process getting started.

Basically, if something is a "native" plugin, machine attempts to execute "docker-machine" again. In that second execution, the machine binary acts as a virtualbox driver. In our case, we're not "docker-machine", but we have to pretend to be.

Here are some pointers to the areas of the code that handle this.
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/main.go#L25
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/machine/client.go#L29

This is how libmachine decides what to execute:
https://github.com/docker/machine/blob/master/libmachine/drivers/plugin/localbinary/plugin.go#L102

**Comment by rodcloutier** [comment]
Thanks for the info.

I now have minikube working on Windows!

Turns out that the communication with the plugins is quite sensitive to the output: the ip is sent through the stdout which I had changed while debugging. 

I ran into the minor issue that three is no support to exclude the current machine ip from the proxy when using the `docker-env` command,  as in `docker-machine env --no-proxy default`. I will most likely enter a new issue to fix this since I need it. 

Incoming PR when I can free some time.

**Comment by dlorenc** [comment]
Nice! Thanks for the help. We should also be able to add a hyper-v driver pretty easily for Windows. I think that should be as simple as adding another case statement here:
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/machine/client.go#L33

And then using hyperv instead of virtualbox here:
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cluster/cluster.go#L217

That could be a flag or just the default for Windows.

**Comment by luxas** [comment]
I think it should be both a flag `--vm-driver` or something, and that hyper-v should be the default

**Comment by vishh** [comment]
Why do we need a flag? Why not  support just `hyper-V`?

**Comment by luxas** [comment]
@vishh In case the user wants to use virtualbox on windows or some other provider on Mac for example. It would be great to let the user choose virtualization provider, and I think it is doable when we're using docker-machine as the abstraction.

**Comment by vishh** [comment]
AFAIK, the plan is to move away from virtualization if possible. I don't
think we want to build a docker-machine clone in the case of `minikube`. We
want to provide a single, well tests, and reliable way to run kubernetes
apps locally. That is using VMs today. It can native in the future. So I'd
like to avoid adding explicit additional dependencies on VMs if possible.

**Comment by dlorenc** [comment]
I haven't tried it yet, but Docker for Windows also uses hyper-v. There's no way to actually get away from virtualization here.

I agree that we shouldn't be cloning docker machine, though. Supporting hyper-v might improve the windows experience considerably though, so we should consider it. I guess the question is whether or not we'd support virtualbox AND hyper-v on windows, or just hyper-v.

**Comment by luxas** [comment]
If we decide to only support hyper-v on windows I'm fine with that, otherwise there's need for a flag. 

Vish, I agree that we should aim to get out of the virtualization trap when running on linux, but on mac and windows we have to use virtualization. As I said above, we might want to support only one vm provider at the same time. Probably hyper-v on windows and hyperkit on mac. But these are long-term goals...

**Comment by vishh** [comment]
By getting rid of virtualization, I meant not running a single VM. Instead
run a light weight VM similar to what docker is doing now.

**Comment by dlorenc** [comment]
My understanding is that the lightweight VM for Windows is still hyper-v. I think we're on the same page for where we want to go with OSX, which is hyperkit/xhyve instead of virtualbox. Windows is a little less clear to me though.

**Comment by vishh** [comment]
FYI:
https://msdn.microsoft.com/en-us/virtualization/windowscontainers/about/about_overview

There is an on-going effort to get kubernetes to work with native windows
containers. That might take a while. Just from a UX perspective, we might
be better off not exposing knobs for now, just to keep the testing surface
minimal.

**Comment by rodcloutier** [comment]
@vishh Although it might be nice to have Windows native containers there will still be a need for Docker support with virtualization if you want to run Linux based container on a Windows machine.

**Comment by rodcloutier** [comment]
I am trying to enable Windows support for the env command but while trying to emulate and reuse what Docker machine is doing, I came across the fact that our vendor libmachine is not complete. Is it intentionnal? What are the procedure to update it?

**Comment by dlorenc** [comment]
Godep only pulls in the code that's used. If you do a godep restore, then start using the missing pieces, then godep save the extra code will make it into vendor.

**Comment by alexbrand** [comment]
This is great, I would love to be able to use minikube on Windows. Is there anything I can help with?

**Comment by dlorenc** [comment]
@rodcloutier was working on this. Rodrigue, have you made any progress? Anything @alexbrand can help with?

**Comment by rodcloutier** [comment]
I am actually preparing a PR with Windows support fully working. I still need to test a little and revise if any documentation is needed. Do we have any support for automated build on Windows?

**Comment by dlorenc** [comment]
I *almost* have a CI system setup to run tests on physical Macs and Windows machines.

**Comment by jeremypulcifer** [comment]
@rodcloutier Let me know if you need a test monkey for this. I'm anxious to get this in my quiver!

**Comment by alexbrand** [comment]
@rodcloutier Same here. Would be happy to help test this out.

**Comment by omallassi** [comment]
@rodcloutier  Can also help/test. I am currently trying to compile 0.5.0 of minikube on windows 7 / boot2docker using cygwin but got the following error 
```
docker run -w /go/src/k8s.io/minikube -e IN_DOCKER=1 -v /cygdrive/c/Users/omallassi/minikube:/go/src/k8s.io/minikube gcr.io/google_containers/kube-cross:v1.6.2-1 make out/localkube
make: *** No rule to make target 'out/localkube'.  Stop.
```
I have run 
```
docker run -w /go/src/k8s.io/minikube -e IN_DOCKER=1 -v /cygdrive/c/Users/minikube:/go/src/k8s.io/minikube golang:1.6 cat Makefile
cat: Makefile: No such file or directory
```

Could be related to the shared folder in boot2docker but not clear...

**Comment by jimmidyson** [comment]
FYI I have Windows builds for a fork https://github.com/jimmidyson/minishift for OpenShift that users are reporting works fine, with the few issues as detailed above related to env vars. Everything else seems to work great so minikube is really close to Windows support. Yay!

**Comment by adfernandes** [comment]
One important point for some of us who are stuck on Windows 7 without Hyper-V... please do not assume that Hyper-V is present on Windows! I know, I know... Windows 7 is ancient and should be put out to pasture, but sadly that is not my decision to make...

**Comment by jimmidyson** [comment]
I think we're going to keep virtualbox support on all OSes for those in your position. We should be able to detect appropriate defaults based on what's available on the host.

**Comment by jianlianggao** [comment]
Hi,
Has anyone got the error like me?
Starting local Kubernetes cluster...
E0721 17:26:20.440554   12096 start.go:76] Error starting host:  Error starting stopped host: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

I have VirtualBox 5.0.16 installed.
I appreciate any help.
Cheers,
Jianliang

**Comment by pcm32** [comment]
@jimmidyson the binary that you facilitated runs fine for me on Windows 10 Pro (v1511), VirtualBox 5.0.16. Haven't got into any issues so far. Up to this point, I have tried deploying k8s services, replication controllers, pods, jobs, bring down stuff, pv's, pvc's (hostPath), get pod logs, etc. without any problems. I do notice though that the response time to kubectl (running on PowerShell) commands is much larger (so, slower) than on my mac running mini-kube. I got the kubectl binary from 
```
https://storage.googleapis.com/kubernetes-release/release/v1.3.1/bin/windows/amd64/kubectl.exe
```
I'll report if I get any problems.

**Comment by jimmidyson** [comment]
@pcm32 Thanks for the feedback!

@dlorenc Sounds like we could put out an experimental Windows release in 0.7? What do you think?

**Comment by jimmidyson** [comment]
@rodcloutier How's your PR coming along? I don't see there is too much stuff to change, the basic functionality of Kubernetes in a VM is sound, just updating a few little bits of minikube commands to work on Windows OK. If you're busy with other things now I don't mind picking this up.

**Comment by dlorenc** [comment]
0.7 sounds good! We have a Windows machine ready to hook up to our CI system as well, so we can start running e2e tests on Windows soon.

**Comment by rodcloutier** [comment]
@jimmidyson I am currently away on vacation. Feel free to scavenge my branch (https://github.com/rodcloutier/minikube/tree/Windows_support)  to bring anything useful. I think the Makefile portion seems to be now already covered. The env command might be worth bringing to the next release. Since I am still having trouble getting the godeps working properly with the current Makefile and the temp GOPATH and MKGOPATH command, the dependencies might not be  up to date.
