### ISSUE TITLE
Unable to start cluster on Windows 10 with latest version of minikube.

### ISSUE THREAD

**Issue by ardz** [kubernetes/minikube#2804]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: Windows 10

**Minikube version** (use `minikube version`): 0.26.1
- **OS** (e.g. from /etc/os-release):d
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Hyper-V
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.26.0
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:

trying to start cluster, following error shows, virtual machine is running in hyper-V manager:

```
PS C:\WINDOWS\system32> minikube start --vm-driver hyperv --hyperv-virtual-switch "Default Switch"
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0511 15:26:08.056795    6496 start.go:276] Error starting cluster:  kubeadm init error sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  running command: : running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI
 output: [init] Using Kubernetes version: v1.10.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
[certificates] Using the existing ca certificate and key.
                                                                                                        [WARNING Swap]: running with swap on is not supported. Please disable swap
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
failure loading apiserver certificate: the certificate is not valid yet
                                                          : running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI
.: Process exited with status 1
```

**What you expected to happen**:

cluster to start with no errors?

**How to reproduce it** (as minimally and precisely as possible):

Install latest version of docker, minikube and run above command?

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

```
PS C:\WINDOWS\system32> minikube dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: Get https://172.20.162.219:8443/api/v1/namespaces/kube-system/services/kubernetes-dashboard: dial tcp 172.20.162.219:8443: connectex: No connection could be made because the target machine actively refused it.
PS C:\WINDOWS\system32>
```
It started the first time, but as soon as I stopped and started the cluster again the error appears?

![image](https://user-images.githubusercontent.com/6310248/39931632-e6099812-5535-11e8-8157-c3a31655b6f4.png)

Ok, for anyone else experiencing this issue; downgrading to the previous version allowed me to start the cluster but the dashboard refused to work. Eventually found that version 0.25.2 was the version which worked for me (with the dashboard as well):

![image](https://user-images.githubusercontent.com/6310248/39999566-48d18822-5781-11e8-9186-bdb11f73a981.png)

Guessing this should be left open as a bug?

**Comment by jgilfoil** [comment]
Failed for me with similar error on a fresh install on windows 10.

https://pastebin.com/edit/DWLSkej7

**Comment by vmattos-ciandt** [comment]
I'm facing the same error using minikube 0.27.0, 0.26.1 and 0.26.0, all using Ubuntu 16.04 and virtualbox. In first fresh installation `minikube start` worked fine, but after a `minikube stop` this error started to show up and never returned to work.

`curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.27.0/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40.7M  100 40.7M    0     0   9.9M      0  0:00:04  0:00:04 --:--:--  9.9M
minikube start --vm-driver=virtualbox
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 150.53 MB / 150.53 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.10.0
Downloading kubelet v1.10.0
Finished Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0608 08:55:51.757383   28167 start.go:276] Error starting cluster:  kubeadm init error sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  running command: : running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI 
 output: [init] Using Kubernetes version: v1.10.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
	[WARNING Swap]: running with swap on is not supported. Please disable swap
Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
failure loading ca certificate: the certificate is not valid yet
: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI 
.: Process exited with status 1
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
Y

minikube logs 
-- Logs begin at Fri 2018-06-08 11:55:13 UTC, end at Fri 2018-06-08 11:56:00 UTC. --
Jun 08 11:55:37 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 08 11:55:38 minikube kubelet[3371]: Flag --allow-privileged has been deprecated, will be removed in a future version
Jun 08 11:55:38 minikube kubelet[3371]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:38 minikube kubelet[3371]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:38 minikube kubelet[3371]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:38 minikube kubelet[3371]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:38 minikube kubelet[3371]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:38 minikube kubelet[3371]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:38 minikube kubelet[3371]: Flag --cadvisor-port has been deprecated, The default will change to 0 (disabled) in 1.12, and the cadvisor port will be removed entirely in 1.13
Jun 08 11:55:38 minikube kubelet[3371]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:38 minikube kubelet[3371]: I0608 11:55:38.002427    3371 feature_gate.go:226] feature gates: &{{} map[]}
Jun 08 11:55:38 minikube kubelet[3371]: F0608 11:55:38.616436    3371 server.go:218] unable to load client CA file /var/lib/localkube/certs/ca.crt: open /var/lib/localkube/certs/ca.crt: no such file or directory
Jun 08 11:55:38 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 08 11:55:38 minikube systemd[1]: kubelet.service: Unit entered failed state.
Jun 08 11:55:38 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 08 11:55:48 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 08 11:55:48 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 08 11:55:48 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 08 11:55:48 minikube kubelet[3492]: Flag --allow-privileged has been deprecated, will be removed in a future version
Jun 08 11:55:48 minikube kubelet[3492]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:48 minikube kubelet[3492]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:48 minikube kubelet[3492]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:48 minikube kubelet[3492]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:48 minikube kubelet[3492]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:48 minikube kubelet[3492]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:48 minikube kubelet[3492]: Flag --cadvisor-port has been deprecated, The default will change to 0 (disabled) in 1.12, and the cadvisor port will be removed entirely in 1.13
Jun 08 11:55:48 minikube kubelet[3492]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:48 minikube kubelet[3492]: I0608 11:55:48.798390    3492 feature_gate.go:226] feature gates: &{{} map[]}
Jun 08 11:55:48 minikube kubelet[3492]: W0608 11:55:48.806514    3492 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Jun 08 11:55:48 minikube kubelet[3492]: I0608 11:55:48.806546    3492 server.go:376] Version: v1.10.0
Jun 08 11:55:48 minikube kubelet[3492]: I0608 11:55:48.806570    3492 feature_gate.go:226] feature gates: &{{} map[]}
Jun 08 11:55:48 minikube kubelet[3492]: I0608 11:55:48.806630    3492 plugins.go:89] No cloud provider specified.
Jun 08 11:55:48 minikube kubelet[3492]: F0608 11:55:48.806649    3492 server.go:233] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jun 08 11:55:48 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 08 11:55:48 minikube systemd[1]: kubelet.service: Unit entered failed state.
Jun 08 11:55:48 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 08 11:55:58 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 08 11:55:58 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 08 11:55:58 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 08 11:55:59 minikube kubelet[3583]: Flag --allow-privileged has been deprecated, will be removed in a future version
Jun 08 11:55:59 minikube kubelet[3583]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:59 minikube kubelet[3583]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:59 minikube kubelet[3583]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:59 minikube kubelet[3583]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:59 minikube kubelet[3583]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:59 minikube kubelet[3583]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:59 minikube kubelet[3583]: Flag --cadvisor-port has been deprecated, The default will change to 0 (disabled) in 1.12, and the cadvisor port will be removed entirely in 1.13
Jun 08 11:55:59 minikube kubelet[3583]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 08 11:55:59 minikube kubelet[3583]: I0608 11:55:59.039849    3583 feature_gate.go:226] feature gates: &{{} map[]}
Jun 08 11:55:59 minikube kubelet[3583]: W0608 11:55:59.049101    3583 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Jun 08 11:55:59 minikube kubelet[3583]: I0608 11:55:59.049223    3583 server.go:376] Version: v1.10.0
Jun 08 11:55:59 minikube kubelet[3583]: I0608 11:55:59.049276    3583 feature_gate.go:226] feature gates: &{{} map[]}
Jun 08 11:55:59 minikube kubelet[3583]: I0608 11:55:59.049356    3583 plugins.go:89] No cloud provider specified.
Jun 08 11:55:59 minikube kubelet[3583]: F0608 11:55:59.049377    3583 server.go:233] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jun 08 11:55:59 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 08 11:55:59 minikube systemd[1]: kubelet.service: Unit entered failed state.
Jun 08 11:55:59 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.`

As soon as I found a solution for this I'll share here.
Regards, 
Vinicius
