### ISSUE TITLE
minikube error while start with kvm2 

### ISSUE THREAD

**Issue by nitinmahawadiwar** [kubernetes/minikube#2810]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:
CentOS 7
**Minikube version** (use `minikube version`): minikube version: v0.26.1 (tried with 25.2 & 26.0 as well)
- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):  "DriverName": "kvm2", ( tried with virtualbox as well)
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
 "Boot2DockerURL": "file:///root/.minikube/cache/iso/minikube-v0.26.0.iso",
        "ISO": "/root/.minikube/machines/minikube/boot2docker.iso",

- **Install tools**: virtualbox, and other tools & drivers
- **Others**: docker & JDK 1.8 (not sure what exactly you need here)
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version: 

echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
I used to have working minikube with 25.2 version, I restarted the VM and all off a sudden entire minikube setup is broken, 
when I restarted, first it gave this error
1) minikube start --vm-driver=kvm2
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
E0515 10:42:58.971926   23909 start.go:159] Error starting host: Error starting stopped host: Error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2018-05-15T05:12:58.689967Z qemu-kvm: -drive file=/root/.minikube/machines/minikube/boot2docker.iso,format=raw,if=none,id=drive-scsi0-0-0-2,readonly=on: could not open disk image /root/.minikube/machines/minikube/boot2docker.iso: Could not open '/root/.minikube/machines/minikube/boot2docker.iso': Permission denied').

 Retrying.
E0515 10:42:58.973380   23909 start.go:165] Error starting host:  Error starting stopped host: Error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2018-05-15T05:12:58.689967Z qemu-kvm: -drive file=/root/.minikube/machines/minikube/boot2docker.iso,format=raw,if=none,id=drive-scsi0-0-0-2,readonly=on: could not open disk image /root/.minikube/machines/minikube/boot2docker.iso: Could not open '/root/.minikube/machines/minikube/boot2docker.iso': Permission denied')
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false

2) then I did minikube delete & removed the /root/.minikube folder, next time when ever I starting, its throwing following error.
minikube start --vm-driver kvm2
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 150.53 MB / 150.53 MB [============================================] 100.00% 0s
E0514 20:48:46.181657    8082 start.go:159] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: Error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: failed to initialize KVM: Device or resource busy').

 Retrying.
E0514 20:48:46.182359    8082 start.go:165] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: Error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: failed to initialize KVM: Device or resource busy')
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================

If I start with minikube start (without specifying kvm2), it hangs after downloading the ISO, when looked into VirtualBox's logs, it shows "emR3Debug: rc=VERR_VMX_UNEXPECTED_INTERRUPTION_EXIT_TYPE"

**What you expected to happen**:
minikube start should start the cluster.

**How to reproduce it** (as minimally and precisely as possible):
minikube start --vm-driver kvm2 and its throwing the error.

**Output of `minikube logs` (if applicable)**:
F0514 20:56:25.392760    8979 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error creating new ssh host from driver: Error getting ssh host name for driver: host is not running

**Anything else do we need to know**:
I have already executed a) minikube delete & b) rm -rf /root/.minikube folder several times, upgraded driver libs, rebooted the server.
The same setup was working a week before.
my kubectl version is Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
docker version : Server Version: 18.03.0-ce

**Comment by snedi** [comment]
Have you installed the kvm2 driver itself as mentioned [here](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver) ? You need to have
`docker-machine-driver-kvm2` in your `/usr/local/bin/`

**Comment by nitinmahawadiwar** [comment]
Hello Denis ,
Thank you for your suggestion. Time being, I was able to restore to prev version of my setup from the VM snapshot. Right now, minikube 25.2 is running fine with kubectl 1.10. 
I shall definitely try your suggestion as soon as my setup goes down.
You may close the ticket for now.
