### ISSUE TITLE
fail to start minikube with vm-driver none

### ISSUE THREAD

**Issue by craynic** [kubernetes/minikube#2811]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release): CentOS Linux release 7.3.1611 (Core) 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**: 
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```
I follow the readme to install `minikube start --vm-driver=none`.
Wait too long with no response.
Kubelet logs say it failed to reach API server.
I see containers for controller api-server scheduler are created, but they cannot be started and then be deleted. 

> [root@localhost ~]# docker ps -a
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
ef433b77f70c        ad86dbed1555                 "kube-controller-man…"   3 minutes ago       Created                                 k8s_kube-controller-manager_kube-controller-manager-minikube_kube-system_7089b1f15da809ed92c826593eb2f561_11
dea2eebf9ff1        704ba848e69a                 "kube-scheduler --ad…"   3 minutes ago       Created                                 k8s_kube-scheduler_kube-scheduler-minikube_kube-system_31cf0ccbee286239d451edb6fb511513_12
03e1919530b3        af20925d51a3                 "kube-apiserver --ad…"   4 minutes ago       Created                                 k8s_kube-apiserver_kube-apiserver-minikube_kube-system_a0d8330cecfe20a4f75fa0949d54dc4a_11
59531ec9aae3        52920ad46f5b                 "etcd --peer-client-…"   4 minutes ago       Created                                 k8s_etcd_etcd-minikube_kube-system_5238155334b2599e291d23ffc8d26b17_11
eb1fb6bf847e        9c16409588eb                 "/opt/kube-addons.sh"    5 minutes ago       Created                                 k8s_kube-addon-manager_kube-addon-manager-minikube_kube-system_3afaf06535cc3b85be93c31632b765da_33
0b9f83bdba4d        k8s.gcr.io/pause-amd64:3.1   "/pause"                 36 minutes ago      Up 36 minutes                           k8s_POD_kube-scheduler-minikube_kube-system_31cf0ccbee286239d451edb6fb511513_0
934772e9cb5e        k8s.gcr.io/pause-amd64:3.1   "/pause"                 36 minutes ago      Up 36 minutes                           k8s_POD_kube-controller-manager-minikube_kube-system_7089b1f15da809ed92c826593eb2f561_0
ba924f9ec0df        k8s.gcr.io/pause-amd64:3.1   "/pause"                 36 minutes ago      Up 36 minutes                           k8s_POD_kube-apiserver-minikube_kube-system_a0d8330cecfe20a4f75fa0949d54dc4a_0
00d1895b88cb        k8s.gcr.io/pause-amd64:3.1   "/pause"                 36 minutes ago      Up 36 minutes                           k8s_POD_etcd-minikube_kube-system_5238155334b2599e291d23ffc8d26b17_0
5095907a069e        k8s.gcr.io/pause-amd64:3.1   "/pause"                 36 minutes ago      Up 36 minutes                           k8s_POD_kube-addon-manager-minikube_kube-system_3afaf06535cc3b85be93c31632b765da_2
[root@localhost ~]# docker start 03e1919530b3
Error response from daemon: linux mounts: Could not find source mount of /etc/pki
Error: failed to start containers: 03e1919530b3

**Comment by craynic** [comment]
I use `-b localkube` to use localkube to avoid this problem. Not solve it.

**Comment by joshk0** [comment]
You could also download to Docker 17.12
