### ISSUE TITLE
helm with None driver: dial tcp 10.96.0.1:443: getsockopt: no route to host

### ISSUE THREAD

**Issue by snedi** [kubernetes/minikube#2814]
**BUG REPORT**

**Environment**:

**Minikube version** : v0.26.1
- **OS** : CentOS Linux 7 (Core)
- **VM Driver** : none
- **ISO version** : cannot find
- **Install tools**:
- **Others**:
kubectl version: v1.10.0
helm version: v2.8.2

**What happened**:
`helm ls` throws an error
```sh
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: getsockopt: no route to host
```
**What you expected to happen**:
I expect to see the list of deployments

**How to reproduce it** (as minimally and precisely as possible):
become root, then
1. `minikube start --vm-driver=none`
after all pods are running
2. `helm init`
3. `helm ls`
4. try `kubectl get po -n kube-system` - all pods are created and running

There is a question what is happening to helm and why is it not connecting to the cluster as well as kubectl?

**Comment by imdad000** [comment]
helm ls throws an error

Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%3DTILLER: dial tcp 10.96.0.1:443: getsockopt: no route to host

**Comment by sbuvaneshkumar** [comment]
Same here.

```bash=
[root@dhcp182-229 ~]# kubectl cluster-info
Kubernetes master is running at https://10.10.182.229:8443
KubeDNS is running at https://10.10.182.229:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
[root@dhcp182-229 ~]# helm ls
Error: Get https://10.96.0.1:443/api/v1/namespaces/kube-system/configmaps?labelSelector=OWNER%!D(MISSING)TILLER: dial tcp 10.96.0.1:443: connect: no route to host

[root@dhcp182-229 ~]# kubectl get po
NAME    READY   STATUS    RESTARTS   AGE
nginx   1/1     Running   0          13m
```
