### ISSUE TITLE
apiserver.Features.EnableSwaggerUI causes kube-proxy failure

### ISSUE THREAD

**Issue by ray1888** [kubernetes/minikube#2816]
Environment
- Minikube version:0.26.0
- OS:Ubuntu 16.04 LTS
- VM Driver: Virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**: apt-get(by ubuntu ppa)
- **Others**:

What happened:
i have follow the  issue https://github.com/kubernetes/minikube/issues/1509, to use command to 
start swagger-ui
```
minikube start --extra-config=apiserver.Features.EnableSwaggerUI=true
```

but the error Message is like this 
```
 ~ sudo minikube start --extra-config=apiserver.Features.EnableSwaggerUI=true
[sudo] ray 的密码： 
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
^[2

E0516 17:09:51.222767    6600 start.go:281] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
```

so how can i use swagger-ui to check api usage on minikube?

**Comment by kairen** [comment]
The following workaround can fix it:
```sh
$ minikube start  --extra-config=apiserver.enable-swagger-ui=true
```
