### ISSUE TITLE
minikube fails to load cached images into VM due to incorrect path

### ISSUE THREAD

**Issue by mlgibbons** [kubernetes/minikube#2826]
Environment: Windows 10 & Windows 7
Minikube version: 0.26.1
OS :Windows
VM Driver: virtual-box
ISO version: 0.26.0

On running minikube "start" minikube fails to load the images into the docker daemon before "kubeadm init" due to it using an incorrect path in the "docker load" command 

e.g. "docker load -i \tmp\pause-amd64_3.0". The "\\"s should be "/"s. 

I0519 14:53:59.629114   11168 ssh_runner.go:58] Run: sudo rm -f /tmp/kube-addon-manager_v6.5
I0519 14:53:59.629114   11168 ssh_runner.go:58] Run: sudo rm -f /tmp/kube-proxy-amd64_v1.10.0
I0519 14:53:59.629114   11168 ssh_runner.go:58] Run: sudo rm -f /tmp/k8s-dns-dnsmasq-nanny-amd64_1.14.4
I0519 14:53:59.629114   11168 ssh_runner.go:58] Run: sudo rm -f /tmp/k8s-dns-sidecar-amd64_1.14.4
I0519 14:53:59.629114   11168 ssh_runner.go:58] Run: sudo rm -f /tmp/etcd-amd64_3.0.17
I0519 14:53:59.629114   11168 ssh_runner.go:58] Run: sudo rm -f /tmp/kube-scheduler-amd64_v1.10.0
I0519 14:53:59.629114   11168 ssh_runner.go:58] Run: sudo rm -f /tmp/kube-controller-manager-amd64_v1.10.0
I0519 14:53:59.654505   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.655481   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.656457   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.658410   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.659388   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.659388   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.661342   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.662318   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.668177   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.668177   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.673059   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.675012   11168 ssh_runner.go:58] Run: sudo mkdir -p /tmp
I0519 14:53:59.942578   11168 ssh_runner.go:58] Run: docker load -i \tmp\pause-amd64_3.0
I0519 14:54:04.254899   11168 ssh_runner.go:58] Run: docker load -i \tmp\k8s-dns-sidecar-amd64_1.14.4
I0519 14:54:04.280288   11168 ssh_runner.go:58] Run: docker load -i \tmp\k8s-dns-dnsmasq-nanny-amd64_1.14.4
I0519 14:54:04.777337   11168 ssh_runner.go:58] Run: docker load -i \tmp\kube-scheduler-amd64_v1.10.0
I0519 14:54:04.870107   11168 ssh_runner.go:58] Run: docker load -i \tmp\k8s-dns-kube-dns-amd64_1.14.4
I0519 14:54:06.542890   11168 ssh_runner.go:58] Run: docker load -i \tmp\kube-addon-manager_v6.5
I0519 14:54:06.677649   11168 ssh_runner.go:58] Run: docker load -i \tmp\storage-provisioner_v1.8.0
I0519 14:54:08.404140   11168 ssh_runner.go:58] Run: docker load -i \tmp\kube-controller-manager-amd64_v1.10.0
I0519 14:54:08.621904   11168 ssh_runner.go:58] Run: docker load -i \tmp\kube-proxy-amd64_v1.10.0
I0519 14:54:08.789867   11168 ssh_runner.go:58] Run: docker load -i \tmp\kube-apiserver-amd64_v1.10.0
I0519 14:54:09.280080   11168 ssh_runner.go:58] Run: docker load -i \tmp\kubernetes-dashboard-amd64_v1.8.1

**Comment by ivan-section-io** [comment]
Should be fixed by PR #2824

**Comment by mlgibbons** [comment]
Excellent. Cheers.
