### ISSUE TITLE
minikube start caches incorrect images

### ISSUE THREAD

**Issue by mlgibbons** [kubernetes/minikube#2827]
Environment: Windows 10 & Windows 7
Minikube version: 0.26.1
OS :Windows
VM Driver: virtual-box
ISO version: 0.26.0

mk only dynamically generates the image names for the four static pods (scheduler, api-server, controller-manager and proxy) correctly appending the k8s version to them. 

Unfortunately, the versions for the other pods are hard-coded and are incorrect for v1.8.x, v1.9.x and v1.10.x. where the versions required differ and are not keyed on k8s version. 

The result is that "kubeadm init" has to download images even if the pre-caching had been successful. This causes problems for disconnected operation or when operating in a restricted environment.

See these links for background info - https://github.com/kubernetes/minikube/blob/master/pkg/minikube/constants/constants.go and https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#config-file

**Comment by ivan-section-io** [comment]
There's already an issue #2679 (+PR #2822) for the "latest" version - it's fairly trivial.

It's slightly more involved to cater to recognizing dependencies for differing versions, but shouldn't be a problem.

@mlgibbons Would you be happy if we steer this issue towards a "cached images are incorrect **for alternate k8s versions**"?

From a fix perspective: I guess one of the first steps may to be discover the specific versions required, and also if there's way to source/determine that without having to manually discover & hard code everything each time.

**Comment by mlgibbons** [comment]
Hi. Thanks for pointing out those links. Short term I agree that the updating of the versions is the expedient thing. Longer term, if possible, dynamic determination of the versions would be the correct solution. I would suggest short term changing the code to explicit static lists for specific versions including the current one (1.8, 1.9, 1.10.0 etc) as documented or discovered and then raising an enhancement issue to switch to making these dynamic longer term. I'm happy to do both if you'd like. Happy also to have the thread title steered in that direction. Cheers.

**Comment by ivan-section-io** [comment]
I think it'd certainly help the implementer to have those resources spelt out.
Whilst the required images should be explicitly stated in kubeadm's source (e.g. https://github.com/kubernetes/kubernetes/blob/release-1.10/cluster/addons/dns/kube-dns.yaml.base), the project has changed structure, names & components enough across versions that I don't think we can't simply compare that file path across versions.
The most reliable and expedient option may be to simply start each version (including dashboard/add-ons) and record the `docker images` listing against each version number.
Given that the current approach is a "static" list - a more comprehensive static list seems like an improvement to me.

**Comment by mlgibbons** [comment]
Changes made in https://github.com/kubernetes/minikube/pull/2845 to handle 1.8.x, 1.9.x and 1.10.x and default to existing generic list.

**Comment by mlgibbons** [comment]
Closed https://github.com/kubernetes/minikube/pull/2845 and opened https://github.com/kubernetes/minikube/pull/2849
