### ISSUE TITLE
start --network-plugin=cni: The cni flag doesn't seem to have any effect in kubelet.

### ISSUE THREAD

**Issue by aanm** [kubernetes/minikube#2828]
Please provide the following details:

**Environment**:

- **Minikube version** (use `minikube version`):
`v0.26.1` (`v.0.27.0` seems to suffer from the same issue)

- **OS** (e.g. from /etc/os-release): `Fedora 27 (Twenty Seven) x86_64`
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): `virtualbox`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): `iso/minikube-v0.26.0.iso`

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
Run minikube with `minikube start --network-plugin=cni`

The `cni` flag doesn't seem to have any effect in kubelet.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

this seems to work `minikube start  --network-plugin=cni --extra-config=kubelet.network-plugin=cni`

**Comment by anitgandhi** [comment]
I'm seeing the same thing with ` minikube start --network-plugin=cni --extra-config=kubelet.network-plugin=cni --vm-driver=none` , Ubuntu 17.10, minikube v0.28

An excerpt from `journalctl -xfu kubelet`: 

```
Unable to update cni config: No networks found in /etc/cni/net.d
```

I don't see anything in `/opt/cni/bin` either

**Comment by aanm** [comment]
@anitgandhi you need to install a cni plugin after minikube has started.

**Comment by anitgandhi** [comment]
Ah. I guess mistakenly assumed at least the loopback plugin would have come with the image. I ended up using kubeadm directly anyway and got the CNI I wanted (cilium) up and running anyway, so I'm all set. Thanks @aanm !
