### ISSUE TITLE
dashboard: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found

### ISSUE THREAD

**Issue by sureshpothineni** [kubernetes/minikube#2830]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Minikube version (use minikube version): 0.25.0

Please provide the following details:

**Environment**:

- **OS** (e.g. from /etc/os-release): MAC OS 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.25.1
- **Install tools**: kubernetes
- **Others**:

**What happened**:
I typed minikube dashboard.

**What you expected to happen**:
I expected the dashboard to open on my browser

**How to reproduce it** (as minimally and precisely as possible):
Install minikube with the kubernetes distribution and type minikube dashboard.

**Output of `minikube logs` (if applicable)**:
Attached minikube_logs
[minikube_logs.txt](https://github.com/kubernetes/minikube/files/2028960/minikube_logs.txt)

**Anything else do we need to know**:
These are the logs I got:

suresh$ minikube --logtostderr dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found

**Comment by PeterSun15629150864** [comment]
May 22 22:42:34 minikube localkube[2599]: E0522 22:42:34.061725    2599 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
you pull gcr.io/google_containers/pause-amd64:3.0 failed
