### ISSUE TITLE
Cannot pull images from AWS ECR: no basic auth credentials (v0.27.0 minikube)

### ISSUE THREAD

**Issue by ptaillard** [kubernetes/minikube#2833]
**Environment**:

- **Minikube version** : 0.27.0
- **OS** (e.g. from /etc/os-release): MacOS 10.12.6 High Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.26.0
- **Install tools**: homebrew

**What happened**:
I cannot pull images from the ECR registry: "no basic auth credentials" error

**What you expected to happen**:
I expected to pull the image from the ECR registry after having configured registry-creds with my ID, KEY, TOKEN and AWS Region, and activating the registry-creds addon and using PullSecrets

**How to reproduce it** (as minimally and precisely as possible):
 `minikube start`
`minikube addons configure registry-creds` => configure only with AWS ECR
`minikube addons enable registry-creds`
`kubectl create -f deployment.yaml`
=> The error occured: cannot start the container due to **no basic auth credentials** error.

`kubectl get secrets --all-namespaces` => we can see that the secret created is in **kube-system** and called **registry-creds-ecr**. I never found the **awsecr-cred** name for the secret as mentioned in the documentation https://github.com/upmc-enterprises/registry-creds

deployement.yaml content:
> apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: <APP>
    spec:
      containers:
        - name: adserver-test
          image: <MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/<IMAGE_TO_PULL>:latest
          command: ["/bin/bash"]
          env:
            - name: TMN_ENVIRONMENT
              value: "qa"
      imagePullSecrets:
        - name: registry-creds-ecr

**Output of `minikube logs` (if applicable)**:

> May 23 09:53:31 minikube kubelet[3443]: W0523 09:53:31.388519    3443 kubelet_pods.go:878] Unable to retrieve pull secret default/registry-creds-ecr for default/adserver-deployment-654f4668bf-l97n8 due to secrets "registry-creds-ecr" not found.  The image pull may not succeed.

> May 23 09:53:31 minikube kubelet[3443]: I0523 09:53:31.388628    3443 kuberuntime_manager.go:513] Container {Name:adserver-test Image:<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/adserver:latest Command:[/bin/bash] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[{Name:TMN_ENVIRONMENT Value:qa ValueFrom:nil}] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-27gpt ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:Always SecurityContext:nil Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.

> May 23 09:53:32 minikube kubelet[3443]: E0523 09:53:32.229556    3443 remote_image.go:108] PullImage "<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/adserver:latest" from image service failed: rpc error: code = Unknown desc = Error response from daemon: Get https://<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/v2/adserver/manifests/latest: no basic auth credentials

> May 23 09:53:32 minikube kubelet[3443]: E0523 09:53:32.229585    3443 kuberuntime_image.go:51] Pull image "<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/adserver:latest" failed: rpc error: code = Unknown desc = Error response from daemon: Get https://<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/v2/adserver/manifests/latest: no basic auth credentials

> May 23 09:53:32 minikube kubelet[3443]: E0523 09:53:32.229627    3443 kuberuntime_manager.go:733] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: Get https://<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/v2/adserver/manifests/latest: no basic auth credentials

> May 23 09:53:32 minikube kubelet[3443]: E0523 09:53:32.229648    3443 pod_workers.go:186] Error syncing pod 1d7cad94-5e6f-11e8-962c-0800278cf469 ("adserver-deployment-654f4668bf-l97n8_default(1d7cad94-5e6f-11e8-962c-0800278cf469)"), skipping: failed to "StartContainer" for "adserver-test" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: Get https://<MY_ACCOUNT_ID_REMOVED_HERE>.dkr.ecr.us-east-1.amazonaws.com/v2/adserver/manifests/latest: no basic auth credentials"

**Comment by ptaillard** [comment]
Ok, I will do that,
Thanks

**Comment by krichter722** [comment]
https://github.com/upmc-enterprises/registry-creds/issues/65
