### ISSUE TITLE
LoadBalancer support

### ISSUE THREAD

**Issue by AmazingTurtle** [kubernetes/minikube#2834]
Regarding this issue here https://github.com/kubernetes/minikube/issues/384 I found there is a `minikube service` command. But this doesn't help.

I installed stable/openvpn using helm on minikube v0.25.2 (kubernetes v1.8.0): https://github.com/kubernetes/charts/tree/master/stable/openvpn

According to guides in the previous link there is a script to generate a client key (which needs a service ip to work).

```
$ kubectl get svc vpn-openvpn
NAME          TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
vpn-openvpn   LoadBalancer   10.99.53.147   <pending>     443:30822/TCP   18m
```

As you can see, the external ip is pending. What's the point of using minikube then, when you can only play around but not really use the important functionalities of k8s?

 I don't want hacky workarounds, especially if it comes to larger scale deployments with multiple services - there has to be a solution.

*This is a must-have-feature and I don't see why nobody seems to care a bit.*

**Comment by elsonrodriguez** [comment]
@AmazingTurtle this is a hack, but I've updated this to work with newer versions of minikube:
https://github.com/elsonrodriguez/minikube-lb-patch

Basically just uses a route to make cluster-ips accessible, and then runs a small loop to assign all LoadBalancer IPs to ClusterIPs.

**Comment by andrewsav-datacom** [comment]
@dlorenc so this referenced doc is "rotten" now. Does this mean that you are no longer planning working on it soon, as you mentioned earlier? Or do I misunderstand the lifecycle?

**Comment by tstromberg** [comment]
I believe balopat is working on this?

**Comment by bhack** [comment]
A temporary workaround https://github.com/knative/serving/blob/master/docs/creating-a-kubernetes-cluster.md#loadbalancer-support-in-minikube.

Any official solution here?

**Comment by jcrossley3** [comment]
@bhack I actually found that workaround by following links referenced in this issue. :)

**Comment by bhack** [comment]
Is the closure of the loop :smile:. Is there any possible solutions.

**Comment by bhack** [comment]
@balopat Is there also a solution in minikube tunnel to use the coredns name resolution? i.e. with Traefik, but I think could involve other ingresses, from the official documentation with minikube you need to add [every service hostname mapping in `/etc/hosts`](https://github.com/containous/traefik/blob/master/docs/user-guide/kubernetes.md#submitting-an-ingress-to-the-cluster). 
So I'am guessing if `minikube tunnel` could solve something related to coredns with systemd-resolvconf on the host to let solve this hostnames. What do you think?

**Comment by AmazingTurtle** [comment]
The temporary workaround does not work for windows. Can you provide an `route add` equivalent for windows that works? @bhack

**Comment by bhack** [comment]
@AmazingTurtle I've not a windows machine but I think it is quite similar. Another solution to resolve internal service names from the host: https://blog.heptio.com/configuring-your-linux-host-to-resolve-a-local-kubernetes-clusters-service-urls-a8c7bdb212a7

**Comment by bhack** [comment]
@balopat With `systemd-resolved` we need to have a global set on the host like:

```
[Resolve]
DNS=10.96.0.10
Domains=~svc.cluster.local
```
If could have a dedicated virtual network interface for minkube we could assign this entry on that specific interface.

**Comment by balopat** [comment]
@AmazingTurtle have a look at this: https://github.com/kubernetes/minikube/blob/157eeeff2219afde6f085f515a5283476af6c280/docs/tunnel.md#windows

@bhack that does sound cool, but I didn't plan with that yet in the first version. It could be an interesting follow-up if we figure out a cross platform way for it and also managing /etc/resolv.conf, systemd-resolved seems like needs a bit more research to have a good UX. Maybe we could just document it in the output of `minikube tunnel` as a starter?

**Comment by bhack** [comment]
@balopat I really don't know what is the status of interface costrained dns on Win and Mac. 
For sure systemd resolved is the solution form Linux for x interface dns but with the default minikube start we don't have a dedicate interface (virtual or not) for minikube right?

**Comment by balopat** [comment]
I am going to close this, as `minikube tunnel` solves the `<pending>` part.  @bhack we can open another issue for the automated DNS management and continue the discussion there.
