### ISSUE TITLE
crio: no registries configured while trying to pull an unqualified image Error: ImageInspectError

### ISSUE THREAD

**Issue by younss** [kubernetes/minikube#2835]
**BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: MacOS / Darwin Kernel Version 17.4.0:
**Minikube version** : v0.27.0
- **OS** :
                 NAME=Buildroot
                 VERSION=2017.11
                 ID=buildroot
                 VERSION_ID=2017.11
                 PRETTY_NAME="Buildroot 2017.11"

- **VM Driver** : virtualbox
- **ISO version** : v0.26.0
- **Install tools**: brew
- **Others**:

**What happened**:
Depoyment failed of a new app.

Get this error after deploying new app
`` Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
Error: ImageInspectError ``

**What you expected to happen**:
Deployment Success
**How to reproduce it** (as minimally and precisely as possible):
1. start minikube with cri-o container 
 ``` minikube start --container-runtime=cri-o```
2. start dashboard
3. CREATE AN APP 
     use information from Edx LinuxFoundationX: LFS158x:

- The application name is webserver
- The Docker image to use is nginx:alpine, where alpine is the image tag
- The replica count, or the number of Pods, is 3

4. click on Deploy

**Output of `minikube logs` (if applicable)**:
``
May 24 03:45:23 minikube kubelet[3510]: E0524 03:45:23.049191    3510 pod_workers.go:186] Error syncing pod 4afe6d44-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-h5smx_default(4afe6d44-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:45:23 minikube kubelet[3510]: E0524 03:45:23.050697    3510 pod_workers.go:186] Error syncing pod 4afbeca2-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-sx45d_default(4afbeca2-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:45:34 minikube kubelet[3510]: I0524 03:45:34.046942    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:45:34 minikube kubelet[3510]: E0524 03:45:34.049012    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:34 minikube kubelet[3510]: E0524 03:45:34.049053    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:34 minikube kubelet[3510]: E0524 03:45:34.049096    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:34 minikube kubelet[3510]: E0524 03:45:34.049158    3510 pod_workers.go:186] Error syncing pod 4afdf8c8-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-28q6w_default(4afdf8c8-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:45:35 minikube kubelet[3510]: I0524 03:45:35.048280    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:45:35 minikube kubelet[3510]: E0524 03:45:35.049753    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:35 minikube kubelet[3510]: E0524 03:45:35.049783    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:35 minikube kubelet[3510]: E0524 03:45:35.049822    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:35 minikube kubelet[3510]: E0524 03:45:35.049846    3510 pod_workers.go:186] Error syncing pod 4afe6d44-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-h5smx_default(4afe6d44-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:45:38 minikube kubelet[3510]: I0524 03:45:38.047109    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:45:38 minikube kubelet[3510]: E0524 03:45:38.049437    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:38 minikube kubelet[3510]: E0524 03:45:38.049473    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:38 minikube kubelet[3510]: E0524 03:45:38.049510    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:38 minikube kubelet[3510]: E0524 03:45:38.049532    3510 pod_workers.go:186] Error syncing pod 4afbeca2-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-sx45d_default(4afbeca2-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:45:48 minikube kubelet[3510]: I0524 03:45:48.046850    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:45:48 minikube kubelet[3510]: E0524 03:45:48.048361    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:48 minikube kubelet[3510]: E0524 03:45:48.048389    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:48 minikube kubelet[3510]: E0524 03:45:48.048425    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:48 minikube kubelet[3510]: E0524 03:45:48.048448    3510 pod_workers.go:186] Error syncing pod 4afdf8c8-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-28q6w_default(4afdf8c8-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:45:49 minikube kubelet[3510]: I0524 03:45:49.047447    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:45:49 minikube kubelet[3510]: I0524 03:45:49.047447    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:45:49 minikube kubelet[3510]: E0524 03:45:49.049236    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:49 minikube kubelet[3510]: E0524 03:45:49.049270    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:49 minikube kubelet[3510]: E0524 03:45:49.049305    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:49 minikube kubelet[3510]: E0524 03:45:49.049332    3510 pod_workers.go:186] Error syncing pod 4afe6d44-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-h5smx_default(4afe6d44-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:45:49 minikube kubelet[3510]: E0524 03:45:49.049999    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:49 minikube kubelet[3510]: E0524 03:45:49.050015    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:49 minikube kubelet[3510]: E0524 03:45:49.050036    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:45:49 minikube kubelet[3510]: E0524 03:45:49.050902    3510 pod_workers.go:186] Error syncing pod 4afbeca2-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-sx45d_default(4afbeca2-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:46:00 minikube kubelet[3510]: I0524 03:46:00.046708    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:46:00 minikube kubelet[3510]: E0524 03:46:00.048786    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:00 minikube kubelet[3510]: E0524 03:46:00.049075    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:00 minikube kubelet[3510]: E0524 03:46:00.049286    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:00 minikube kubelet[3510]: E0524 03:46:00.049515    3510 pod_workers.go:186] Error syncing pod 4afdf8c8-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-28q6w_default(4afdf8c8-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:46:02 minikube kubelet[3510]: I0524 03:46:02.047318    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:46:02 minikube kubelet[3510]: E0524 03:46:02.048272    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:02 minikube kubelet[3510]: E0524 03:46:02.048304    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:02 minikube kubelet[3510]: E0524 03:46:02.048345    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:02 minikube kubelet[3510]: E0524 03:46:02.048367    3510 pod_workers.go:186] Error syncing pod 4afbeca2-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-sx45d_default(4afbeca2-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
May 24 03:46:03 minikube kubelet[3510]: I0524 03:46:03.051793    3510 kuberuntime_manager.go:513] Container {Name:webserver Image:nginx:alpine Command:[] Args:[] WorkingDir: Ports:[] EnvFrom:[] Env:[] Resources:{Limits:map[] Requests:map[]} VolumeMounts:[{Name:default-token-l42cj ReadOnly:true MountPath:/var/run/secrets/kubernetes.io/serviceaccount SubPath: MountPropagation:<nil>}] VolumeDevices:[] LivenessProbe:nil ReadinessProbe:nil Lifecycle:nil TerminationMessagePath:/dev/termination-log TerminationMessagePolicy:File ImagePullPolicy:IfNotPresent SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*false,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,} Stdin:false StdinOnce:false TTY:false} is dead, but RestartPolicy says that we should restart it.
May 24 03:46:03 minikube kubelet[3510]: E0524 03:46:03.052646    3510 remote_image.go:83] ImageStatus "nginx:alpine" from image service failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:03 minikube kubelet[3510]: E0524 03:46:03.052677    3510 kuberuntime_image.go:87] ImageStatus for image {"nginx:alpine"} failed: rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:03 minikube kubelet[3510]: E0524 03:46:03.052770    3510 kuberuntime_manager.go:733] container start failed: ImageInspectError: Failed to inspect image "nginx:alpine": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image
May 24 03:46:03 minikube kubelet[3510]: E0524 03:46:03.052797    3510 pod_workers.go:186] Error syncing pod 4afe6d44-5f01-11e8-926b-080027b5cfd2 ("webserver-74b684cccd-h5smx_default(4afe6d44-5f01-11e8-926b-080027b5cfd2)"), skipping: failed to "StartContainer" for "webserver" with ImageInspectError: "Failed to inspect image \"nginx:alpine\": rpc error: code = Unknown desc = no registries configured while trying to pull an unqualified image"
``
**Anything else do we need to know**:

**Comment by afbjorklund** [comment]
I added a basic container registry configuration (e2a1f5754796b571ba10eb0a927a84e7bae90c1c) , for podman (#2757) to work:

```
[registries.search]
registries = ['docker.io']

[registries.insecure]
registries = []

```
It should probably have gone into a separate PR.

/remove-lifecycle stale

**Comment by afbjorklund** [comment]
After merging 2aa4927e7829a76286a67404c70d616e3b18f3e5, this now works fine...
Images outside docker.io still need prefixing.

After creating the deployment, you can verify the images being used:
```
$ sudo crictl images nginx:alpine
IMAGE                     TAG                 IMAGE ID            SIZE
docker.io/library/nginx   alpine              315798907716a       19MB
$ 
```
