### ISSUE TITLE
Failed to install longhorn, iscsiadm/open-iscsi is missing

### ISSUE THREAD

**Issue by ston3o** [kubernetes/minikube#2846]
**Minikube version**: v0.26.1
- **OS**: Arch Linux
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.26.0.iso

**What happened**:

When I try to install [longhorn](https://github.com/rancher/longhorn). I have this error : 

```
ERRO[0000] Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host
FATA[0000] Error starting manager: Environment check failed: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output nsenter: failed to execute iscsiadm: No such file or directory           
, error exit status 1
```

**What you expected to happen**:

open-iscsi installed on minikube.

**How to reproduce it**:

```bash
kubectl create -f https://raw.githubusercontent.com/rancher/longhorn/master/deploy/longhorn.yaml
kubectl -n longhorn-system logs -f longhorn-manager-tbps9
```

**Anything else do we need to know**:

This Issue is related to another [closed issue](https://github.com/kubernetes/minikube/issues/1174).

**Comment by lshmouse** [comment]
@johackim 

The reason is that minikube run in docker and there is no open-iscsi package that longhorn required (https://longhorn.io/docs/0.8.0/install/requirements/) in the minikube container. So just installing the open-iscsi in the minikube docker container will solve this issue, eg:
```
minikube ssh "sudo apt-get update;sudo apt-get install -y open-iscsi"
```
