### ISSUE TITLE
sudo scp -t /usr/bin output: : wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by TheBlackReverand** [kubernetes/minikube#2854]
Hi

I juste start with Kubernetes and I don't found help with that SCP problems :\

I can't start Minikube

Thanks for your help.

**Environment**: CentOS 7.5.1804 (Linux 3.10.0-862.3.2.el7.x86_64 x86_64)

**Minikube version** : 0.27.0
- **OS** : CentOS 7
- **VM Driver** : virtualbox
- **ISO version** : .minikube/cache/iso/minikube-v0.26.0.iso
- **Others**:
```
$ minikube status
minikube: Stopped
cluster: 
kubectl: 
```
**What happened**: Minikube not start. SCP error in "Moving files into cluster..." step

**What you expected to happen**: Minikube start :)

**How to reproduce it** (as minimally and precisely as possible):
$ minikube start

**Output of `minikube logs` (if applicable)**:
```
F0530 10:30:06.872480   13564 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error dialing tcp via ssh client: dial tcp 127.0.0.1:35516: getsockopt: connection refused
```

**Anything else do we need to know**:
```
$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E0530 10:05:05.628703   12653 start.go:234] Error updating cluster:  downloading binaries: transferring kubeadm file: &{BaseAsset:{data:[] reader:0xc4200aabd0 Length:0 AssetName:/home/admin/.minikube/cache/v1.10.0/kubelet TargetDir:/usr/bin TargetName:kubelet Permissions:0641}}: Error running scp command: sudo scp -t /usr/bin output: : wait: remote command exited without exit status or exit signal

$ kubectl cluster-info
Kubernetes master is running at http://localhost:8080

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by thejaswimanju** [comment]
Even I am facing similar issue
[manjunbm@dhcp-9-193-98-34 ~]$ minikube start --vm-driver=none
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E0906 15:16:01.951317    6771 start.go:258] Error updating cluster:  downloading binaries: transferring kubeadm file: &{BaseAsset:{data:[] reader:0xc4202623f0 Length:0 AssetName:/home/manjunbm/.minikube/cache/v1.10.0/kubeadm TargetDir:/usr/bin TargetName:kubeadm Permissions:0641}}: error creating file at /usr/bin/kubeadm: open /usr/bin/kubeadm: permission denied

Where you able to fix this issue ??

**Comment by petermetz** [comment]
I resolved this by deleting the cluster and recreating it from scratch like this:
```sh
minikube delete; minikube start;
```

**Comment by tstromberg** [comment]
My best guess here is that VirtualBox stopped the guest VM in the middle of the scp transfer. If you encounter this again, please attach the output of the following commands to this bug:

```shell
VBoxManage list vms
minikube logs
```

And if you can find it, a VirtualBox log: https://blogs.oracle.com/scoter/virtualbox-log-files-v2 

Thanks!
