### ISSUE TITLE
minikube start panic on macOS with "runtime error: slice bounds out of range" error

### ISSUE THREAD

**Issue by praveendhac** [kubernetes/minikube#2855]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

`$ minikube start --extra-config=apiserver.Authorization.Mode=Node --extra-config=apiserver.Authentication.OIDC.IssuerURL=http://192.168.99.1:5556/dex --extra-config=apiserver.Authentication.OIDC.UsernameClaim=email --extra-config=apiserver.Authentication.OIDC.ClientID="praveend_client_id"
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 150.53 MB / 150.53 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.10.0
Downloading kubelet v1.10.0
Finished Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
panic: runtime error: slice bounds out of range

goroutine 1984 [running]:
bytes.(*Buffer).ReadFrom(0xc4202965b0, 0x30a9790, 0xc42029a300, 0x2df20b0, 0xc4202965b0, 0x3620cec401)
	/usr/local/go/src/bytes/buffer.go:210 +0x2b4
io.copyBuffer(0x293af60, 0xc4202965b0, 0x30a9790, 0xc42029a300, 0x0, 0x0, 0x0, 0x2046de0, 0x0, 0x30a9790)
	/usr/local/go/src/io/io.go:386 +0x2bb
io.Copy(0x293af60, 0xc4202965b0, 0x30a9790, 0xc42029a300, 0xc42029a300, 0xc420ccafb0, 0x1)
	/usr/local/go/src/io/io.go:362 +0x68
k8s.io/minikube/vendor/golang.org/x/crypto/ssh.(*Session).stdout.func1(0xc420e19020, 0xc420ccafb0)
	/go/src/k8s.io/minikube/vendor/golang.org/x/crypto/ssh/session.go:511 +0x85
k8s.io/minikube/vendor/golang.org/x/crypto/ssh.(*Session).start.func1(0xc4208d2120, 0xc420790d70)
	/go/src/k8s.io/minikube/vendor/golang.org/x/crypto/ssh/session.go:383 +0x27
created by k8s.io/minikube/vendor/golang.org/x/crypto/ssh.(*Session).start
	/go/src/k8s.io/minikube/vendor/golang.org/x/crypto/ssh/session.go:382 +0x121`

Please provide the following details:

**Environment**:
**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release):
$ system_profiler SPSoftwareDataType
Software:
System Software Overview:
System Version: macOS 10.13.3 (17D47)
Kernel Version: Darwin 17.4.0
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "virtualbox"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.26.0.iso
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
Executed `minikube start --extra-config=apiserver.Authorization.Mode=Node --extra-config=apiserver.Authentication.OIDC.IssuerURL=http://192.168.99.1:5556/dex --extra-config=apiserver.Authentication.OIDC.UsernameClaim=email --extra-config=apiserver.Authentication.OIDC.ClientID="praveend_client_id"`
and saw the trace after an hour or so.

**What you expected to happen**:
Should handle out of bounds and throw proper error message.

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:
Attached, [minikube_crash.txt](https://github.com/kubernetes/minikube/files/2054335/minikube_crash.txt)
**Anything else do we need to know**:

**Comment by dlorenc** [comment]
I haven't been able to reproduce this. Can you do it consistently?

**Comment by praveendhac** [comment]
This is an intermittent issue, couldn't reproduce on a consistent basis.
