### ISSUE TITLE
Minikube 0.5.0 : cannot validate certificate for 192.168.99.101 because it doesn't contain any IP SANs

### ISSUE THREAD

**Issue by lbroudoux** [kubernetes/minikube#286]
Hi,
starting today with a brand new install of Minikube 0.5.0 and Kubectl 1.3.0 (my machine is running ubuntu 14.04 64 bits).

Just start Minikube with `minikube start` and everything seems to run fine (Vbox machine is created and started) but contacting the cluster seems impossible due to certificate issue:

```shell
laurent@ponyo:~$kubectl cluster-info
Unable to connect to the server: x509: cannot validate certificate for 192.168.99.101 because it doesn't contain any IP SAN
```

`kubectl config view` runs fine and outputs the following config

```shell
laurent@ponoy:~$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/laurent/.minikube/apiserver.crt
    server: https://192.168.99.101:443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/laurent/.minikube/apiserver.crt
    client-key: /home/laurent/.minikube/apiserver.key
```

Any clue on this issue ? Is there any extra step before starting minikube regarding cert provisionning ? Is there any pointer on how to solve that ?

Thank you for help,

**Comment by dlorenc** [comment]
Hey,

Sorry you ran into trouble! Could you run this command:

openssl x509 -in ~/.minikube/apiserver.crt -text

And look through the output for the section that says:
`X509v3 Subject Alternative Name:`

and paste the following line? For me it looks like:

```shell
            X509v3 Subject Alternative Name:
                DNS:kubernetes.default.svc.cluster.local, DNS:kubernetes.default.svc, DNS:kubernetes.default, DNS:kubernetes, IP Address:192.168.99.100, IP Address:10.0.0.1
```

**Comment by lbroudoux** [comment]
Hi,
thank you for your comment. I run the command and got quite the same result here:

```
X509v3 Subject Alternative Name:
       DNS:kubernetes.default.svc.cluster.local, DNS:kubernetes.default.svc, DNS:kubernetes.default, DNS:kubernetes, IP Address:192.168.99.101, IP Address:10.0.0.1
```
IP Address is 192.168.99.101 instead of 192.168.99.100 in your case but seems coherent with my cluster config.

I have pursued investigations and found that I have some trouble with my corporate proxy. When unsetting all env vars (lowercase and uppercase), I am now able to run `kubectl` commands. However, when proxy is disabled before launching minikube startup, kubernetes has trouble starting/syncing the kubernetes-dashboard pod...

So for now, I have to 2 deal with 2 terminals: one having proxy settings and start/stopping minikube, one having no proxy settings and issuing kubectl commands.

**Comment by dlorenc** [comment]
Thanks again for confirming this is a proxy issue. I'll make this a dup of #336, where we're tracking making minikube work behind proxies.

**Comment by monktastic** [comment]
Nothing in #336 helped me figure this out, but the solution for me was:

minikube start --docker-env http_proxy=http://proxy-example.com:80/  --docker-env https_proxy=... --docker-env no_proxy=...
