### ISSUE TITLE
`make test` failed on Mac

### ISSUE THREAD

**Issue by stantonxu** [kubernetes/minikube#2860]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

This is a BUG

Please provide the following details:

**Environment**:
**Minikube version** (use `minikube version`): v0.27.0
- **OS** (e.g. from /etc/os-release): macOS 10.12.4 Sierra
- **Others**: Go 1.10.2

**What happened**:

`make` works fine on Mac, but when running `make test`, it shows the below error

./test.sh
Running go tests...
\# k8s.io/minikube/cmd/minikube/cmd
cmd/minikube/cmd/start.go:322: Println arg list ends with redundant newline
FAIL	k8s.io/minikube/cmd/minikube/cmd [build failed]
make: *** [test] Error 2

**Comment by dlorenc** [comment]
I'm unable to repro this on minikube at HEAD with go 1.10.1. 

There's no fmt.Println at line 322, which commit are you at?
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start.go#L322

**Comment by stantonxu** [comment]
@dlorenc , thanks for checking out. I just synced my fork of the minikube code, and retested it. The original issue seems gone, I cannot reproduce it too. (by the way, it is not line 322 any longer since somebody checked in some more code later after I submitted the issue, it is line 339 of the new start.go now. Anyway, the problem is no longer there, weird.)

With that being said, I encountered a new problem when I ran `make test` just now. Here is the error.

```
\# k8s.io/minikube/vendor/github.com/google/certificate-transparency/go/x509
vendor/github.com/google/certificate-transparency/go/x509/root_darwin.go:73: cannot use nil as type _Ctype_CFDataRef in assignment
FAIL	k8s.io/minikube/pkg/localkube [build failed]
make: *** [test] Error 2
```

**Comment by stantonxu** [comment]
I just created PR #2869 for this new problem.

**Comment by stantonxu** [comment]
The root cause of this issue is that the current minikube dep `cfssl` version is not compatible with Go 1.10, due to its dep `google/certificate-transparency` problem https://github.com/google/certificate-transparency-go/issues/131

So `make test` succeeds with Go 1.9, but fails with Go 1.10

Kubernetes has a PR to update `cfssl`, https://github.com/kubernetes/kubernetes/pull/60373

When will minikube be compatible with Go 1.10? Any plan?

**Comment by stantonxu** [comment]
OK. I will close it. Thanks @dlorenc

**Comment by stantonxu** [comment]
Closing the issue, duplicated with https://github.com/kubernetes/minikube/issues/2770, addressed by https://github.com/kubernetes/minikube/pull/2777

**Comment by stantonxu** [comment]
@dlorenc , I looked into your https://github.com/kubernetes/minikube/pull/3014, seems for `cloudflare`, you only removed the package `log` under `cfssl`, the other packages under `cfssl` are still there. It still has the dependency on `google/certificate-transparency-go`, so the `make test` will still fail.

I reopen this issue till we have this problem figured out.

**Comment by stantonxu** [comment]
Problem is resolved by removing `cloudflare`.
