### ISSUE TITLE
can minikube on windows work with docker for windows container images inside pods?

### ISSUE THREAD

**Issue by pmaheshgupta** [kubernetes/minikube#2868]
I am working with .net framework apps, I want to containerize with docker for windows and orchestrate with kubernetes.

for playing around I installed minikube but found it is running on linux image, when I create virtual nodes and create pods can I able to deploy docker for windows container image in it?

if it doesn't work what are the other options I can work with ?

**Comment by dlorenc** [comment]
Minikube currently only supports linux containers. I'm not aware of any other options.
