### ISSUE TITLE
kubelet and docker fail to start up again after VM restart

### ISSUE THREAD

**Issue by awh** [kubernetes/minikube#2874]
Author of [kured](https://github.com/weaveworks/kured) here; it would streamline my testing enormously if, after the minikube VM is rebooted via `systemctl reboot`, kubelet etc came back up automatically without having to manually run `minikube start` again from the host. Is there a reason it doesn't do that, other than there's not really been a need for it previously?

**Comment by awh** [comment]
I've found the problem. The kubelet & docker unit files are copied to `/lib/systemd/system`, a directory which is not backed by the persistent disk - they're disappearing on reboot.

**Comment by tstromberg** [comment]
I can confirm this is still an issue in v0.33.1.

**Comment by tstromberg** [comment]
Apparently this is by design: one must run "minikube start" to restart the VM properly. Much of this reason is because the root filesystem is temporary.

We can revisit this behavior once #3512 is resolved, but it will be quite some time.
