### ISSUE TITLE
service: allow per-service configuration of protocol (mongodb:// for example)

### ISSUE THREAD

**Issue by p-jaya** [kubernetes/minikube#2885]
This is a feature request.  In summary I'd like to be able to configure the output of `minikube service` to allow more accurate information to be displayed for our developers.

**Environment**:

**Minikube version** (use `minikube version`): v0.27.0
- **OS**: macOS 10.13.4
- **VM Driver**: virtualbox
- **ISO version**: v0.26.0
- **Install tools**: n/a
- **Others**: n/a

**What happened**:

Using mongodb as an example, but this applies to any external service you'd like to expose that isn't http.

1. Create a mongodb deployment
2. Create a mongodb service
3. Now list your running services as follows:

```
$ minikube service list --namespace default
|-------------|----------------------|--------------------------------|
|  NAMESPACE  |         NAME         |              URL               |
|-------------|----------------------|--------------------------------|
| default     | mongodb              | http://192.168.99.102:30321    |
|-------------|----------------------|--------------------------------|
```

**What you expected to happen**:

It'd be great if there were a way of configuring the service endpoint to display as `mongodb://<ip>:<port>` and be configurable on a service-by-service basis.

Very happy to submit a pull request for this although I could use some help in identifying an appropriate place to add it since this would be my first contribution.

**Comment by dlorenc** [comment]
Can you get this to work using the `--format` flag to "minikube service"?

**Comment by p-jaya** [comment]
@dlorenc that would only work for a single service though I believe.  If you had, for example, an http service and a mongo service running you'd want differing schemes for both.

**Comment by dlorenc** [comment]
Hmm, is there any way to detect from the service itself what protocol to use? I don't think it would be a very good idea to force users to configure this themselves.

**Comment by dlorenc** [comment]
Maybe I'm misunderstanding - for a single service example like you showed, you can do that with the --format flag. Does that make sense?

**Comment by p-jaya** [comment]
Updated my earlier comment to make it a bit clearer I hope

**Comment by nslater** [comment]
I have a service configured to expose two ports. one uses HTTP and the other uses the PostgreSQL wire protocol. so I am running into this issue too

instead of adding something to Minikube, would it make sense to change the column name to `NETWORK ADDRESS` and drop the `http://` prefix?

the `http://` is not required even for HTTP services, because the HTTP protocol is inferred by every HTTP client I am aware of

**Comment by tstromberg** [comment]
This appears somewhat related to #3112
