### ISSUE TITLE
Network 'minikube-net' is not active after reboot

### ISSUE THREAD

**Issue by fbaldo31** [kubernetes/minikube#2895]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Environment**: Linux
**Minikube version** (use `minikube version`): v0.27.0
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm2
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.26.0

**What happened**:
minikube stop
(reboot the system)
minikube start

Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E0612 19:00:45.564326    4938 start.go:159] Error starting host: Error starting stopped host: Error creating VM: virError(Code=55, Domain=19, Message='Requested operation is not valid: network 'minikube-net' is not active').

 Retrying.
E0612 19:00:45.565725    4938 start.go:165] Error starting host:  Error starting stopped host: Error creating VM: virError(Code=55, Domain=19, Message='Requested operation is not valid: network 'minikube-net' is not active')

**What you expected to happen**:
I don't know if it is a minikube issue or linked to kvm, but i would be great to avoid connect to virsh and 
start manually minikube-net

**How to reproduce it** (as minimally and precisely as possible):
minikube stop
(reboot the system)
minikube start

**Anything else do we need to know**:
I use kvm2 driver and the problem is still there after the new qemu update.

**Comment by dlorenc** [comment]
I think this might have been fixed recently in the kvm2 driver. Could you make sure you have the most recent version of the driver? You can get one from here: https://github.com/kubernetes/minikube/releases

**Comment by dlorenc** [comment]
Any luck trying this out @fbaldo31?

**Comment by tdavis** [comment]
Experiencing the same thing here, just downloaded the latest blob for `docker-machine-driver-kvm2`. Even after nuking `~/.minikube` (something that usually fixes these random transient errors) and restarting it, same issue. Well, `virsh net-list` doesn't include `minikube-net` so I guess the error has a point?

**Comment by tdavis** [comment]
Some [people](https://bugzilla.redhat.com/show_bug.cgi?id=1348434) decided that it's alright if stopping `firewalld` (a common occurrence for anybody using QEMU user-mode networking for unrelated VMs) silently breaks `libvirtd` networking. So, `systemctl restart libvirtd` and try again.

I don't think minikube can fix this because even invoking the appropriate `virsh` commands won't work until it's restarted. Software is pretty great.

**Comment by dlorenc** [comment]
Thanks @tdavis, I agree this should probably be closed here. Please re-open if you can repro still @fbaldo31

**Comment by ramanjk** [comment]
[root@k8slab ~]# virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes
 minikube-net         active     no            yes
                        By default minikube-net Auto-start is no,hence we unable to start the minikube after reboot,,even i used kvm2,,,it is the bug in kvm..expecting to fix this in further updates

**Comment by andrewhowdencom** [comment]
Hitting a similar issue, the following sequence of commands "seems" to fix it:

```
systemctl restart libvirtd
minikube delete
minikube start --vm-driver=kvm2
```

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by ramanjk** [comment]
The better way is follow below,eliminates the each time after reboot issue.
Go to virsh prompt.
#virsh
#net-start minikube-net
#net-list
if u observed minikube-net autorestart option is no,then execute below command.
#net-autorestart minikube-net

**Comment by bartjkdp** [comment]
@ramanjk you probably mean:

```
net-autostart minikube-net
```
