### ISSUE TITLE
hyperkit driver memory configuration problem

### ISSUE THREAD

**Issue by weisjohn** [kubernetes/minikube#2896]
**Is this a BUG REPORT or FEATURE REQUEST?** BUG Report

Please provide the following details:

**Environment**:  MBP 2017, macOS High Sierra

**Minikube version** (use `minikube version`): `minikube version: v0.27.0`
- **OS** (e.g. from /etc/os-release): `$ uname -a # Darwin Johns-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Mon Mar  5 22:24:32 PST 2018; root:xnu-4570.51.1~1/RELEASE_X86_64 x86_64`
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): `hyperkit`
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):` v0.26.0`
- **Install tools**: `brew`

**What happened**:

I started `minikube` via `minikube start --memory 4096 --cpus 4 --disk-size 80g`

**What you expected to happen**:

I expected hyperkit to take all of the memory allocated in the command.

```bash
$ ps aux | grep minikube
root             26578  31.6 11.7  6426356 1967572 s001  S    11:24AM 163:16.05 /usr/local/bin/hyperkit -A -u -F /Users/johnweis/.minikube/machines/minikube/hyperkit.pid -c 2 -m 2048M -s 0:0,hostbridge -s 31,lpc -s 1:0,virtio-net -U 74ee3860-6db6-11e8-b43d-8c85906fdb62 -s 2:0,virtio-blk,/Users/johnweis/.minikube/machines/minikube/minikube.rawdisk -s 3,ahci-cd,/Users/johnweis/.minikube/machines/minikube/boot2docker.iso -s 4,virtio-rnd -l com1,autopty=/Users/johnweis/.minikube/machines/minikube/tty,log=/Users/johnweis/.minikube/machines/minikube/console-ring -f kexec,/Users/johnweis/.minikube/machines/minikube/bzimage,/Users/johnweis/.minikube/machines/minikube/initrd,earlyprintk=serial loglevel=3 user=docker console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes base host=minikube
```

The relevant section is `/usr/local/bin/hyperkit -A -u -F /Users/johnweis/.minikube/machines/minikube/hyperkit.pid -c 2 -m 2048M`

Notice, hyperkit is only taking 2 Gb of memory on the argument line and only 2 CPUs. This is confirmed in Activity Monitor:

![screen shot 2018-06-12 at 1 54 13 pm](https://user-images.githubusercontent.com/12034/41307785-1ff93566-6e48-11e8-880b-bdc4352ac8c5.png)

**How to reproduce it** (as minimally and precisely as possible):

1. install minikube
2. install hyperkit driver
3. `minikube stop && minikube start --memory 4096 --cpus 4 --disk-size 80g`
4. `ps aux | grep minikube`
5. Observe arguments

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by weisjohn** [comment]
Perhaps this isn't a bug but rather how `minikube start` works. I started the machine via the `--vm` flag but didn't send in the `cpus` and `memory`  arguments, but then after stopping and starting the minikube machine again, it didn't automatically use those new arguments. 

But, after modifying `~/.minikube/machines/minikube/config.json` with those values, `stop` and `start` have the intended effect.

Sorry for the noise.

**Comment by MadhukaHarith92** [comment]
I tried to update resources for a profile using `minikube config set` command. However, this is a global configuration and not specific to a profile. This is not a proper solution. It should be possible to update resources per profile.
