### ISSUE TITLE
Build and release iso

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#29]
This should have a fixed version of docker and other dependencies. We can release it separately (via GCS download) or maybe use go-bindata to pack it all up into the CLI binary.

**Comment by dlorenc** [comment]
One example of customizing b2d images: https://github.com/skippbox/boot2k8s

**Comment by dlorenc** [comment]
Looks like GKE is still using Docker 1.9.1. I suggest we match the Docker version in GKE to ease testing/compatibility.

**Comment by luxas** [comment]
Sounds good to follow GKE docker version.
Is it worthwhile to have a test with docker-on-the-edge anyway?
I think we should have that too

**Comment by dlorenc** [comment]
Some initial work done here: #41

**Comment by dlorenc** [comment]
I propose a lightweight minikube-version to iso-version mapping:

We'll publish a versions.json file in the same storage bucket as the isos. minikube CLIs will have this URL hardcoded. The file will look like this:

```
{
  "$VERSION1": {
    "ISOURL": "$SOMEISOURL"
  },
  "$VERSION2": {
    "ISOURL": "$SOMEISOURL"
  },
}
```

Minikube will download this file, and use it's own hardcoded version (via -X flags to go build) to determine the ISO URL. If downloading or parsing this file fails, minikube will use a default value. If minikube is run with the --iso-url flag, it will skip this step and download the file passed in that flag.

Releasing a new iso will consist of uploading it and changing the json file.

Any thoughts?

**Comment by dlorenc** [comment]
Design prototyped here: https://github.com/kubernetes/minikube/compare/master...dlorenc:isoversion

Any thoughts? cc @luxas @aaron-prindle

**Comment by ethernetdan** [comment]
We should probably include a signature with each version or at least a hash

**Comment by dlorenc** [comment]
Ah yeah, we can validate it client side as well. I'll add that to the PR.

**Comment by dlorenc** [comment]
Closing this out. We don't currently verify the SHA during download, but we publish it so a user could if they want to. We can use a new issue if we want to improve that later.
