### ISSUE TITLE
Running `minikube delete` breaks `minikube start`

### ISSUE THREAD

**Issue by ConnorDoyle** [kubernetes/minikube#290]
Deleting a running cluster seemed to break minikube.

```
[~]$ minikube start --show-libmachine-logs=true --stderrthreshold=0
Starting local Kubernetes cluster...
I0707 11:41:38.472798   13936 cluster.go:60] Machine exists!
I0707 11:41:38.730192   13936 cluster.go:60] Machine exists!
I0707 11:41:38.784298   13936 cluster.go:60] Machine exists!
E0707 11:41:38.849506   13936 start.go:70] Error starting host:  Error getting state for host: machine does not exist
```

Removing the local state (`~/.minikube/`) fixed the issue in my local environment (OS X + Virtualbox).

**Comment by daikaixian** [comment]
hi~
please help me.
I have the same problem with yours.
But I am using minikube on centos.

How shou I fix the bug :Error starting host:  Error getting state for host: machine does not exist

**Comment by dlorenc** [comment]
Hey, until we track down and fix the issue you can just run:
minikube delete 
rm -rf ~/.minikube

Then start

**Comment by daikaixian** [comment]
thx.
really thx.
it works

**Comment by aronchick** [comment]
Just FYI - you can get this error message (putting here for SEO purposes):

```

**Comment by aaron-prindle** [comment]
I believe we have fixed this now.  Please reopen if this issue persists.

**Comment by imorti** [comment]
I'm still getting this issue in 0.9.0.

**Comment by taylorzr** [comment]
Got this on v0.14 on a mac.

**Comment by justinfx** [comment]
Same issue on OSX Sierra + virtualbox. It seems I always have to delete the ~/.minikube directory after stopping minikube. It will then redownload the latest iso and start again

**Comment by brthor** [comment]
Hitting this in OSX 10.12.6, minikube version v0.22.3, installed via homebrew cask.

`minikube delete` causes machine doesn't exist errors on subsequent `minikube start` calls.

`rm -rf ~/.minikube` solves the problem

**Comment by hawksight** [comment]
in my case, using `vm-driver xyhyve` - had to `sudo rm -rf ~/.minikube` as some files root owned.
Installed from cask, minikube version - 0.23.0.

**Comment by manikantag** [comment]
Issue there with **0.24.1** too. Ideally it would be better if minikube creates new VM from already cached ISO files when running `minikube start` after `minikube delete`.

minikube: 0.24.1
Kubernetes: 1.8
Win 10 Pro x64
Virtualbox 5.1.30

**Comment by ehlxr** [comment]
i have the same problem when reinstall minikube on my mac.
resolve it by `rm -rf ~/.minikube`

**Comment by jtuttle** [comment]
I just had this problem with minikube 0.26.1. Looking at the verbose output, it hangs on:
```
Successfully loaded all cached images
```

**Comment by joel-ecc** [comment]
It turned out the culprit was the `Security & Privacy` setting in `macOS` prevented `VirtualBox` from installed properly. This worked for me: 

1. remove existing `virtualbox` by trash it && delete all virtualbox related files/folder under `~/Library/`
2. reinstall it with latest version (if macOS is used, make sure check `allow` button in the `Security & Privacy`.
3. `minikube delete` 
4. `rm -rf ~/.minikube`
5.  `minikube start` --> it should download

Good luck!

**Comment by ibrahimelement** [comment]
Had the same issue on Windows 10. Following a crash (of-which has been reported) minikube was unable to delete the cluster using `minikube delete`. I had to delete the entire configuration store after killing headless VBox instances.

**Comment by EhizDanny** [comment]
pls what is the equivalence of  `rm -rf ~/.minikube` on windows
