### ISSUE TITLE
v0.28.0 - `kubectl exec -it` terminal dimensions not exported

### ISSUE THREAD

**Issue by alanbrent** [kubernetes/minikube#2906]
**Environment**:

**Minikube version**: v0.28.0
- **OS**: macOS 10.13.5
- **VM Driver**: hyperkit
- **ISO version**: minikube-v0.28.0.iso

**What happened**: When running `kubectl exec -it $POD -- bash`, the resulting terminal session had COLUMNS=80, rather than the current size of my Terminal.app window.

**What you expected to happen**: I expected the terminal dimensions to be the same as my current Terminal.app window.

**How to reproduce it**: While in a terminal window where `$COLUMNS` > 80, use minikube v0.28.0 to spin up an environment, jump into a terminal and run `echo $COLUMNS`. Then move back to (e.g.) v0.25.2 and do it again.

**Anything else do we need to know**: 

- This problem was a common annoyance in all ways of running Kubernetes, until it was fixed about a year ago. According to https://github.com/kubernetes/kubernetes/issues/47990#issuecomment-324026975, the fix was actually in `kubelet`. Perhaps something changed in how the `kubelet` is being executed in minikube v0.28.0 that has caused this issue to reappear?
- I'm using the `kubeadm` bootstrapper. I tested this across various versions of Kubernetes, all had the same problem.
- When I switched back to v0.25.2, things worked correctly again.
    - caveat here is that _sometimes_ it does not bring the dimensions over, but exiting out and jumping back into a terminal pretty much always fixes it

**Comment by afbjorklund** [comment]
Most likely this is a Docker issue: https://github.com/moby/moby/issues/35407

Should try with Docker 18.06 (or cri-o), to see if the same issue still exists...

Workaround:
``` console
eval $(resize)
```

**Comment by alanbrent** [comment]
Another workaround I've found is simply to resize your terminal window, or if you're in `tmux` you can zoom out and in. I'm going to go ahead and close this.
