### ISSUE TITLE
Do not include /etc/cni/net.d/k8s.conf in rootfs by default

### ISSUE THREAD

**Issue by brb** [kubernetes/minikube#2907]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

Currently, minikube ships with [/etc/cni/net.d/k8s.conf](https://github.com/kubernetes/minikube/blob/v0.28.0/deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/usr/libexec/kubernetes/kubelet-plugins/net/exec/k8s.conf) in rootfs.

When using minikube with other CNI network providers, e.g. Weave Net, kubelet might use the config when starting pods till the provider has provisioned its CNI config, which results in some pods being attached to `mybridge` instead of the `weave` bridge. Some manual steps are required to prevent from this happening: https://github.com/weaveworks/weave/issues/3124#issuecomment-397820940.

Instead of shipping `k8s.conf` inside rootfs, I suggest to add a param to `minikube start` which would trigger provisioning of `k8s.conf`.

If this makes sense to you, I'm happy to open a PR.

**Comment by dlorenc** [comment]
This sgtm. Let me know when you send the PR!
