### ISSUE TITLE
Log status periodically while starting minikube

### ISSUE THREAD

**Issue by vishh** [kubernetes/minikube#291]
As of now `minikube start` hangs for a while after outputting `Starting local Kubernetes cluster...`
A user doesn't know what is happening under the covers and whether they are supposed to wait or re run the command.

**Comment by jimmidyson** [comment]
We could just default libmachine logs to true as that at least shows most of what's going on at a level that isn't over verbose?

**Comment by aaron-prindle** [comment]
Fixed with: #1091
