### ISSUE TITLE
localhost in dns

### ISSUE THREAD

**Issue by david-andersson** [kubernetes/minikube#2917]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: Ubuntu 16.04

**Minikube version** (use `minikube version`): 0.28
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): None
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**: When trying to start minikube etcd fails to start. This is because it is trying to bind to an external IP address. It is doing that because I'm on a corporate network and nslookup localhost returns an IP address, which is the IP address that etcd is trying to bind to.

**What you expected to happen**: For etcd to use 127.0.0.1 or for it to use the ip of the machine.

**How to reproduce it** (as minimally and precisely as possible): minikube start with a network that resolves localhost to an external IP address.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by david-andersson** [comment]
I have figured out a way to get around this. The idea is to spoof the localhost dns lookup on your machine. On ubuntu I did it using dnsmasq. I also had to add an entry with the default domain added (eg. not only localhost but, for example, localhost.HOME) if your machine is configured to automatically add that.

Hopefully this will be fixed at some point...

**Comment by tstromberg** [comment]
This issue is further elaborated upon in #2967
