### ISSUE TITLE
Switch `current-context` in kube config to `minikube` after `minikube start`

### ISSUE THREAD

**Issue by vishh** [kubernetes/minikube#292]
To make the experience complete, a user should be able to run `kubectl` commands against minikube cluster after they run `minikube start`.

**Comment by luxas** [comment]
And likewise switch back to `default` when `minikube stop`
+ document it :)

**Comment by jimmidyson** [comment]
Not sure about setting it back again afterwards, changing to a different context could be unexpected & don't really want users accidentally issuing `kubectl delete` against a prod cluster without knowing their running against it.
