### ISSUE TITLE
virtualbox 5.2: The host-only adapter we just created is not visible.

### ISSUE THREAD

**Issue by KowalczykBartek** [kubernetes/minikube#2931]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:  

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release): macOS Hight Sierra 10.13.5
- **VM Driver** : "DriverName": "virtualbox"
- **ISO version** : "Boot2DockerURL": "file:///Users/i316755/.minikube/cache/iso/minikube-v0.28.0.iso"
- **Install tools**:  
VBoxManage --version : 5.2.12r122591
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):

**What happened**:
error occurred 

**What you expected to happen**:
minikube starts. 

**How to reproduce it** (as minimally and precisely as possible):
Install minikube and start.

**Output of `minikube logs` (if applicable)**:
```
minikube start                                                 
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 153.08 MB / 153.08 MB [============================================] 100.00% 0s
E0624 19:52:09.221837   34682 start.go:168] Error starting host: Error creating host: Error executing step: Creating VM.
: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue.

 Retrying.
E0624 19:52:09.222559   34682 start.go:174] Error starting host:  Error creating host: Error executing step: Creating VM.
: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================

```
**Anything else do we need to know**:
happens on previous versions as well.

**Comment by dlorenc** [comment]
See here for some more context: https://github.com/docker/machine/issues/4066

Did you recently upgrade your virtualbox installation? It's possible you might need to uninstall/reinstall.

**Comment by KowalczykBartek** [comment]
hmm, but docker works as charm :) 

> Did you recently upgrade your virtualbox installation? It's possible you might need to uninstall/reinstall.

I installed virtualbox from scratch - so I just installed newest version, I will try to downgrade.

**Comment by KowalczykBartek** [comment]
same with 5.2.8

**Comment by KowalczykBartek** [comment]
I was able to run newest of minikube (on OSX) with following config 
- OSX version : Hight Sierra 10.13.5 
- VirtualBox (Version 5.2.18)

**Comment by YongX** [comment]
> I was able to run newest of minikube (on OSX) with following config
> 
> * OSX version : Hight Sierra 10.13.5
> * VirtualBox (Version 5.2.18)

this works for me. I downgrade from 5.2.20 to 5.2.18
