### ISSUE TITLE
[bug] Release notes Osx installion instructions not mention homebrew alternative

### ISSUE THREAD

**Issue by tsm91** [kubernetes/minikube#2933]
**Is this a BUG REPORT**

**What happened**:
release log info does not output homebrew instructions

**What you expected to happen**:
<img width="913" alt="screen shot 2018-06-25 at 19 33 56" src="https://user-images.githubusercontent.com/4459551/41866006-286ec76c-78af-11e8-9e63-0141141abbae.png">

**How to reproduce it** (as minimally and precisely as possible):
https://github.com/kubernetes/minikube/releases/tag/v0.28.0 check Installion instructions section

**Comment by aaron-prindle** [comment]
fixed, closing
