### ISSUE TITLE
minikube doesn't work with Docker Toolbox (VBoxManage not found in path)

### ISSUE THREAD

**Issue by shivrajjadhav733** [kubernetes/minikube#2935]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: 
I have Windows-7 machine. I have installed Docker Toolbox (which installed Oracle Virtual Box version: 5.2.8r121009)
C:\Users>VBoxManage -version
5.2.8r121009

When I launch virtual box and check version of linux using command: cat /proc/version
Linux version 4.9.93-boot2docker (root@eb591e1ad697) (gcc version 6.3.0 20170516 (Debian 6.3.0-18+deb9u1) ) #1 SMP Thu May 10 16:27:54 UTC 2018

**Minikube version** (use `minikube version`):v0.28.0

- **OS** (e.g. from /etc/os-release): 
NAME=Boot2Docker
VERSION=18.05.0-ce
ID=boot2docker
ID_LIKE=tcl
VERSION_ID=18.05.0-ce
PRETTY_NAME="Boot2Docker 18.05.0-ce (TCL 8.2.1); HEAD : b5d6989 - Thu May 10 16:35:28 UTC 2018"
ANSI_COLOR="1;34"
HOME_URL="http://boot2docker.io"
SUPPORT_URL="https://github.com/boot2docker/boot2docker"
BUG_REPORT_URL="https://github.com/boot2docker/boot2docker/issues"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): No such file or directory
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): No such file or directory
- **Install tools**:
- **Others**:

**What happened**: 
1. I installed kubectl using curl:
curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl

Then as per instructions on https://kubernetes.io/docs/tasks/tools/install-kubectl/ I made kubectl executable and moved to PATH.

2. Then I went to https://github.com/kubernetes/minikube/ and went to Installation section for linux to install minikube. 
That installed minikube version: v0.28.0
See below details:
```
docker@default:/home/kubernetes$ curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube
 /usr/local/bin/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 40.8M  100 40.8M    0     0  2039k      0  0:00:20  0:00:20 --:--:-- 2373k
docker@default:/home/kubernetes$ minikube version
minikube version: v0.28.0
docker@default:/home/kubernetes$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 153.08 MB / 153.08 MB [============================================] 100.00% 0s
E0625 21:25:20.969504    6371 start.go:168] Error starting host: Error creating host: Error executing step: Running precreate checks.
: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path.

 Retrying.
E0625 21:25:20.975760    6371 start.go:174] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
```
 

**What you expected to happen**:
minikube should start properly without any error.

**How to reproduce it** (as minimally and precisely as possible):
1. Get windows docker toolbox and install on windows 7
2. start docker quickstart terminal
3.  ssh docker@192.168.99.100
4. install-kubectl 
5. install minikube
6. start minikube

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by shivrajjadhav733** [comment]
https://stackoverflow.com/questions/51033585/windows-docker-virtualbox-kubernetes-kubectl-minikube-start-issue

**Comment by dixonjose** [comment]
I have same error.
Do we have any fix for this

**Comment by bubthegreat** [comment]
Did you install virtualbox on the docker image itself?  Regardless of whether or not virtualbox is installed as a part of the docker toolbox on the windows host OS, you'll still need to have virtualbox on the docker image that you're installing the minikube on.

Try adding an `apt-get install virtualbox` before you run `minikube start` and see if that helps - I had the same error message on a VM (Ubuntu 16.04) and installing virtualbox got me sorted.

**Comment by tstromberg** [comment]
Docker Toolbox is in maintenace mode, so I'm not sure it's worth trying to make the two compatible.

As a workaround, find where VBoxManage is installed, and add it to your path. minikube might work then.
