### ISSUE TITLE
Minikube fails to detect the Intel's "i3 350M" Processor's virtualization state, which is enabled. 

### ISSUE THREAD

**Issue by sau29** [kubernetes/minikube#2940]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release):
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube@minikube-VirtualBox:~$ minikube version
minikube version: v0.28.0
minikube@minikube-VirtualBox:~$ echo "";

minikube@minikube-VirtualBox:~$ echo "OS:";
OS:
minikube@minikube-VirtualBox:~$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-poli                                                      cy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
minikube@minikube-VirtualBox:~$ echo "";

minikube@minikube-VirtualBox:~$ echo "VM driver":
VM driver:
minikube@minikube-VirtualBox:~$ grep DriverName ~/.minikube/machines/minikube/co                                                      nfig.json
grep: /home/minikube/.minikube/machines/minikube/config.json: No such file or di                                                      rectory
minikube@minikube-VirtualBox:~$ echo "";

minikube@minikube-VirtualBox:~$ echo "ISO version";
ISO version
minikube@minikube-VirtualBox:~$ grep -i ISO ~/.minikube/machines/minikube/config                                                      .json
grep: /home/minikube/.minikube/machines/minikube/config.json: No such file or di                                                      rectory
minikube@minikube-VirtualBox:~$
```

**What happened**:
Minikube doesn't work with Intel's "i3 350M" Processor, even though the processor has support for virtualization and is enabled too. During starting of Minikube, error is stating that VT-x/AMD-v is not enabled.

I am using Windows-7, and have installed Ubuntu in Oracle's VirtualBox, and in that I was installing Minikube.

**What you expected to happen**:
Installation of Minikube in Oracle VirtualBox, especially when I have support of virtualization and is enabled, minikube shouldn't have thrown this error(mentioned below).

**How to reproduce it** (as minimally and precisely as possible):
1. Have a system(preferably windows, as I am also using the same) but processor is what playing a major role here.
2. I am using "i3 350M" intel's processor which has support for Virtualization, and which is enabled too. Processor Virtualization details:
https://ark.intel.com/products/43529/Intel-Core-i3-350M-Processor-3M-Cache-2_26-GHz
Intel® Virtualization Technology (VT-x) ‡	Yes
3. Have installed Oracle VirtualBox, and have Ubuntu installed on it.
4. In the process of installing minikube, when executed "minikube start" got following errors:
minikube@minikube-VirtualBox:~$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 153.08 MB / 153.08 MB [============================================] 100.00% 0s
E0627 15:44:04.208103    5925 start.go:168] Error starting host: Error creating host: Error executing step: Running precreate checks.
: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory.

 Retrying.
E0627 15:44:04.209262    5925 start.go:174] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
minikube@minikube-VirtualBox:~$

**Output of `minikube logs` (if applicable)**:
Mentioned above.

**Anything else do we need to know**:

**Comment by dlorenc** [comment]
This looks like a bug in the virtualbox driver. Could you file this issue over there in https://github.com/docker/machine
