### ISSUE TITLE
minikube hangs at "Starting cluster components..." with minikube v0.28.0 with Windows Server 2016 and Hyper-V

### ISSUE THREAD

**Issue by paulinalei** [kubernetes/minikube#2949]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:
Windows Server 2016
**Minikube version** (use `minikube version`): v0.28.0
- **OS** (e.g. from /etc/os-release):
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Hyper-V
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.28.0.iso
- **Install tools**:
- **Others**:

**What happened**: minikube hangs at "Starting cluster components..."

**What you expected to happen**: minikube to start the cluster

**How to reproduce it** (as minimally and precisely as possible): 
Install kubectl, Hyper-V, and minikube.
Run with command `minikube start --vm-driver=hyperv --hyperv-virtual-switch=(internal switch)`

**Output of `minikube logs` (if applicable)**:
This is the last log that was outputted before hanging.
Log outputted by adding flags `--logtostderr -v5`

`Starting cluster components...
I0629 09:34:16.895277    8000 ssh_runner.go:80] Run with output: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=Fil
eAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI`

**Anything else do we need to know**:
I've deleted the .kubectl and .minikube directories and tried to restart, but it still hangs.

I've deleted kubectl.exe and minikube.exe and redownloaded to see if that would change any behavior.

I can't run `minikube stop` or `minikube delete`. I have to manually delete minikube using Hyper-V manager.

Sometimes it exits with "Process existed with error status 1" or will randomly work. However, more often exits with error status.

**Comment by navono** [comment]
I have the same problem.
Environment:
OS: Win10 1803(17134.112)
Minikube version: v0.28.0

**Comment by paulinalei** [comment]
In case anyone else has same issue:

I eventually got it working my reconnecting the internal switch, deleting the .kube and .minikube directories and rerunning.

**Comment by magick93** [comment]
Hi @paulinalei 

Are you able to explain what you mean by 
> reconnecting the internal switch

Thanks
