### ISSUE TITLE
Make it easier to use PSP (PodSecurityPolicy) clusters

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/minikube#2950]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
FEATURE REQUEST

Creating a PSP enabled cluster involved multiple steps. Will be make sense to add some `--enable-psp` flag to `minikube start` command to automatically perform those steps?

**Comment by kairen** [comment]
You can enable support for pod security policies by starting Minikube with the following command (note the `PodSecurityPolicy` option at the end):
```sh
minikube start --extra-config=apiserver.GenericServerRunOptions.AdmissionControl=NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,ResourceQuota,DefaultTolerationSeconds,PodSecurityPolicy
```

**Comment by tamalsaha** [comment]
Additional RBAC is needed to make things work. This is what I do now: https://github.com/appscodelabs/tasty-kube/tree/master/minikube/1.10/psp

**Comment by kfox1111** [comment]
In a related note, I was trying to do the same thing for testing psp in prep for enabling it on one of our clusters. I just hit a roadblock on creating the test user.

I minikube sshed, then sudo su -'ed, then tried to create a user cert for the test user:
# kubeadm alpha phase kubeconfig user --client-name testuser
couldn't create a kubeconfig; the CA files couldn't be loaded: couldn't load the certificate file /etc/kubernetes/pki/ca.crt: open /etc/kubernetes/pki/ca.crt: no such file or directory

Seems strange. Were certs generated other then the standard kubeadm way?
