### ISSUE TITLE
[Docs] Adding new driver docs

### ISSUE THREAD

**Issue by BrendanBall** [kubernetes/minikube#2953]
The dev docs for adding a new driver at [Adding new driver](https://github.com/kubernetes/minikube/blob/master/docs/contributors/adding_driver.md) are out of date. I followed them trying to add an LXD driver (see [PR 2926](https://github.com/kubernetes/minikube/pull/2926)) which is apparently the wrong thing to do. 

pinging @anfernee seen as you are referenced in the outdated docs.

**Comment by dlorenc** [comment]
cc @gbraad @praveenkumar
