### ISSUE TITLE
start hangs when --extra-config=apiserver.ServiceNodePortRange set (kube-apiserver CrashLoopBackOff)

### ISSUE THREAD

**Issue by IBMRob** [kubernetes/minikube#2962]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** : Ubuntu 16.04
- **VM Driver**: virtualbox
- **ISO version** : minikube-v0.28.0
- **Install tools**: Completly clean OS install.
- **Others**:

**What happened**:

Starting minikube with `minikube start --cpus 4 --disk-size 60g --memory 6144 --extra-config=apiserver.ServiceNodePortRange=80-32000 -v 10` hangs at `Starting cluster components`

**What you expected to happen**:

Minikube start up.

**How to reproduce it** (as minimally and precisely as possible):

Create VM with Ubuntu 16.04 LTS
Update VM to with latest patches
Install VirtualBox
Install Kubectl
Install Minikube 
Start Minikube

**Output of `minikube logs` (if applicable)**:
```
....
Jul 05 09:14:59 minikube kubelet[2776]: E0705 09:14:59.495253    2776 pod_workers.go:186] Error syncing pod 621213a6f3059728c13bfa6df5aa07d3 ("kube-apiserver-minikube_kube-system(621213a6f3059728c13bfa6df5aa07d3)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-minikube_kube-system(621213a6f3059728c13bfa6df5aa07d3)"
Jul 05 09:14:59 minikube kubelet[2776]: E0705 09:14:59.813319    2776 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.99.100:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&limit=500&resourceVersion=0: dial tcp 192.168.99.100:8443: getsockopt: connection refused
Jul 05 09:14:59 minikube kubelet[2776]: E0705 09:14:59.868084    2776 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460: Failed to list *v1.Node: Get https://192.168.99.100:8443/api/v1/nodes?fieldSelector=metadata.name%3Dminikube&limit=500&resourceVersion=0: dial tcp 192.168.99.100:8443: getsockopt: connection refused
Jul 05 09:14:59 minikube kubelet[2776]: E0705 09:14:59.896238    2776 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.99.100:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.99.100:8443: getsockopt: connection refused
```

**Comment by IBMRob** [comment]
Note this is exactly the same error I see when running it natively on my MacoS machine as well. Same version of Minikube also hangs at `Starting cluster components`

**Comment by abdennour** [comment]
Same issue with my MacOS when specifying "memory" and "cpus" options: `minikube --memory 8192 --cpus 2 start`. 
However, it works fine with a simple start `minikube start`

**Comment by scheung38** [comment]
Not really, with even the latest Mac High Sierra with 

$ minikube start also takes ages

Sometimes after 20 mins it will connect, sometimes after 30 mins it will, then sometimes after 30 mins hangs....

**Comment by aclowkey** [comment]
Getting the same issue on Ubuntu..Deleting and restarting doesn't work..

**Comment by kaelzhang** [comment]
Encounter this problem every time when I upgrade, reinstall or even slightly touch minikube !!

Really helpless with the error.

Is there any official instructions about this problem, and more hints to the tty to tell us what to do next?

**Comment by shimron** [comment]
same error with minikube v0.28.2 on macOS 10.13.6

**Comment by geropl** [comment]
For me (Ubuntu 16.04, minikube v0.28.2, kubectl v1.11.0) leaving out `--extra-config=apiserver.ServiceNodePortRange` did the trick.
`minikube start` works but `minikube start --extra-config=apiserver.ServiceNodePortRange=80-32767` does not.

**Comment by mkm177** [comment]
I am having the same issue on MacOS High Sierra (v10.13.6). 
minikube 0.28.2, Kubectl v1.11.0.
Neither `minikube start`, nor `minikube start ----vm-driver=virtualbox ` work.

**Comment by owenallenaz** [comment]
Switching to `--extra-config=apiserver.service-node-port-range=80-32767` worked for me. Thanks for the tip!

**Comment by tstromberg** [comment]
Closing in preference to the more general issue of invalid apiserver flags causing havoc: #3532

**Comment by maktas** [comment]
I am having the same issue on Windows 10 (full version: 10.0.18362 N/A Build 18362).
minikube v1.12.1, Kubectl: v1.18.3
Neither minikube start, nor minikube start ----vm-driver=virtualbox  work.

After several failure messages like "failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff", minikube start commands eventually fail with: "Unfortunately, an error has occurred: timed out waiting for the condition" message.
