### ISSUE TITLE
Unable to enable AppArmor in minikube (works in minishift)

### ISSUE THREAD

**Issue by zhangtbj** [kubernetes/minikube#2969]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): 
BUG REPORT

Please provide the following details:

**Environment**:
Both Mac and Ubuntu

**What happened**:
I tried from minikube 0.28 - 0.23, they all don't work
After I `minikube start` a kubernetes cluster. the apparmor should be enabled by default.
But after I `minikube ssh` to the node and check, the apparmor is not installed and enabled.
And when I deploy any kube app, then I `kube exec` to access the pod of the kube app, I also cannot see the apparmor is enabled in the pod. But I tried minishift today, they enable by default.

I also found we can enable it like this:
https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md

But I tried:
`minikube start --feature-gates=AppArmor=true` and `minikube start --feature-gates AppArmor=true`, they all don't work.

**What you expected to happen**:
after `minikube start`, the apparmor should be enabled by default.

Or can you please tell me how to enable `apparmor` for my minikube?

Thanks a lot!

**Comment by tstromberg** [comment]
This now works in v0.33:

```
minikube start --feature-gates AppArmor=true --vm-driver=kvm2
Starting local Kubernetes v1.13.2 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
Verifying kubelet health ...
Verifying apiserver health ...
Kubectl is now configured to use the cluster.
Loading cached images from config file.


Everything looks great. Please enjoy minikube!
```
