### ISSUE TITLE
xhyve: Machine didn't return an IP after 120 seconds, aborting

### ISSUE THREAD

**Issue by sonnyrajagopalanhpe** [kubernetes/minikube#2971]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

 BUG REPORT

Please provide the following details:

**Environment**: Mac OS 10.13.6

**Minikube version** (use `minikube version`): v0.28.0

- **OS** (e.g. from /etc/os-release): MacOS 10.13.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
"DriverName": "xhyve",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):  
 "Boot2DockerURL": "file:///Users/admin/.minikube/cache/iso/minikube-v0.28.0.iso"
- **Install tools**: Followed instructions in https://kubernetes.io/docs/tutorials/hello-minikube/
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:

minikube start --vm-driver=xhyve
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
WARNING: The xhyve driver is now deprecated and support for it will be removed in a future release.
Please consider switching to the hyperkit driver, which is intended to replace the xhyve driver.
See https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver for more information.
To disable this message, run [minikube config set WantShowDriverDeprecationNotification false]
Downloading Minikube ISO
 153.08 MB / 153.08 MB [============================================] 100.00% 0s
E0710 14:10:27.027116    7959 start.go:168] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting.

 Retrying.
E0710 14:10:27.027889    7959 start.go:174] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
**What you expected to happen**:

I expected to start the minikube cluster.

**How to reproduce it** (as minimally and precisely as possible):
Follow instructions on "hello minikube" on a mac 10.13.6.

**Output of `minikube logs` (if applicable)**:

F0710 14:16:02.311037    8348 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found for MAC  in DHCP leases

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
Just curious, does this work with the hyperkit driver?

**Comment by tstromberg** [comment]
obsoleting because xhyve is deprecated.
