### ISSUE TITLE
Add HyperKit instructions to accessing_etcd.md file.

### ISSUE THREAD

**Issue by dfee** [kubernetes/minikube#2972]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Neither?

OK – so if you look at the history of this file: https://github.com/kubernetes/minikube/commits/master/docs/accessing_etcd.md @franzbeltran seems to have initially said that you should access minikube's host (the actual computer) with the ip address `192.168.99.1` (apparently [when using `hyperkit`](https://github.com/kubernetes/minikube/pull/2062/commits/ff93bcf02977dc8579e73c0d57afa5cfc4431788)).

@franzbeltran then updated the documentation, removing that IP address, and adding in (instead) `10.0.2.2` which is indeed correct for a [`virtualbox` driver](https://github.com/kubernetes/minikube/commit/9d9a581f090b1e7c67248b04b6c578d3cb6764d8#diff-af5d0d8b28ccb0d9205a9ed524f49871).

I've switched from `virtualbox` -> `hyperkit` and was lucky enough to find the first IP address when combing through the issues, so why was it removed?

**Comment by tstromberg** [comment]
No idea. You are welcome to add it back if you like.
