### ISSUE TITLE
Allow minikube.iso download to be resumeable

### ISSUE THREAD

**Issue by abdouskamel** [kubernetes/minikube#2973]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

**Environment**:

- **Minikube version**: v0.28.0
- **OS**: Debian GNU/Linux 9 (stretch)

Hello everybody, I installed Minikube yesterday and executed `minikube start`, after that it starts downloading Minikube.ISO. I had an internet connection problem, than I was obliged to re-execute  `minikube start`. I excepted it to continue the downloading from where it stopped, but it restarted from the beginning. The same happened when downloading kubelet.

I would like to suggest restarting the download from the point of interruption. I would like to work on this issue, and I dig a little in the code, but I don't know if it is related to Minikube itself, or Docker, or the server that provides the ISO.

So i'll be glad if someone more experienced want to work on this, or guide me to work on it.

Thank you.

**Comment by tstromberg** [comment]
The library allows for this - I'm not sure what's going on here. :)

**Comment by tstromberg** [comment]
Fixed in v1.3.0.
