### ISSUE TITLE
start with --vm-driver=none: Some fatal errors occurred: [ERROR Port-8443]: Port 8443 is in use

### ISSUE THREAD

**Issue by mulargui** [kubernetes/minikube#2975]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

Please provide the following details:

**Environment**:
**Minikube version** (use `minikube version`): v0.28.0
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.4 LTS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): none
- **Install tools**: na
- **Others**: installing minikube locally in a ubuntu VM hosted in windows 10 and started using vagrant

**What happened**:
An error occurred during minikube startup.
**What you expected to happen**:
Minikube should start.
**How to reproduce it** (as minimally and precisely as possible):
[runk8s2.sh.txt](https://github.com/kubernetes/minikube/files/2190435/runk8s2.sh.txt)
**Output of `minikube logs` (if applicable)**:
[minikube.output.txt](https://github.com/kubernetes/minikube/files/2190428/minikube.output.txt)
**Anything else do we need to know**:

**Comment by mulargui** [comment]
minikube logs
F0712 22:02:06.571965   25185 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting api client: Error loading host from store: open /home/vagrant/.minikube/machines/minikube/config.json: permission denied

**Comment by mulargui** [comment]
btw,
I believe the core of this issue is that .minikube directory is created owned by root whereas .kube and all others are created under the vagrant user (the user I logged in)
vagrant@ubuntu-bionic:~$ ll
total 48
drwxr-xr-x  7 vagrant vagrant 4096 Jul 24 15:55 ./
drwxr-xr-x  4 root    root    4096 Jul 18 22:49 ../
-rw-------  1 vagrant vagrant  182 Jul 19 21:43 .bash_history
-rw-r--r--  1 vagrant vagrant  220 Jun 30 18:58 .bash_logout
-rw-r--r--  1 vagrant vagrant 3771 Jun 30 18:58 .bashrc
drwx------  2 vagrant vagrant 4096 Jul 18 22:49 .cache/
drwx------  3 vagrant vagrant 4096 Jul 18 22:49 .gnupg/
drwxrwxr-x  2 vagrant vagrant 4096 Jul 18 23:01 .kube/
drwxr-xr-x 10 root    root    4096 Jul 18 23:02 .minikube/
-rw-r--r--  1 vagrant vagrant  807 Jun 30 18:58 .profile
drwx------  2 vagrant vagrant 4096 Jul 18 22:49 .ssh/
-rw-rw-r--  1 vagrant vagrant  683 Jul 24 15:55 output

vagrant@ubuntu-bionic:~$ ll .mini*
total 80
drwxr-xr-x 10 root    root    4096 Jul 18 23:02 ./
drwxr-xr-x  7 vagrant vagrant 4096 Jul 24 15:55 ../
drwxr-xr-x  2 root    root    4096 Jul 18 23:01 addons/
-rw-r--r--  1 root    root    1298 Jul 18 23:02 apiserver.crt
-rw-------  1 root    root    1675 Jul 18 23:02 apiserver.key
-rw-r--r--  1 root    root    1066 Jul 18 23:02 ca.crt
-rw-------  1 root    root    1679 Jul 18 23:02 ca.key
drwxr-xr-x  5 root    root    4096 Jul 18 23:01 cache/
drwxr-xr-x  2 root    root    4096 Jul 18 23:01 certs/
-rw-r--r--  1 root    root    1103 Jul 18 23:02 client.crt
-rw-------  1 root    root    1679 Jul 18 23:02 client.key
drwxr-xr-x  2 root    root    4096 Jul 18 23:01 config/
drwxr-xr-x  2 root    root    4096 Jul 18 23:01 files/
drwxr-xr-x  2 root    root    4096 Jul 18 23:01 logs/
drwxr-xr-x  3 root    root    4096 Jul 18 23:01 machines/
drwx------  3 root    root    4096 Jul 18 23:01 profiles/
-rw-r--r--  1 root    root    1074 Jul 18 23:02 proxy-client-ca.crt
-rw-------  1 root    root    1675 Jul 18 23:02 proxy-client-ca.key
-rw-r--r--  1 root    root    1103 Jul 18 23:02 proxy-client.crt
-rw-------  1 root    root    1675 Jul 18 23:02 proxy-client.key
vagrant@ubuntu-bionic:~$

**Comment by 345paul** [comment]
With regards to the root ownership of the files in .minikube directory, I get the same problem.

According to the code in this file (https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start.go) it will change ownership of everything in the .minikube directory to your current user provided the CHANGE_MINIKUBE_NONE_USER environment variable exists.

The code in start.go calls into the function MaybeChownDirRecursiveToMinikubeUser (https://github.com/kubernetes/minikube/blob/master/pkg/util/utils.go), which tests for the CHANGE_MINIKUBE_NONE_USER again and the SUDO_USER environment variable (which should be set if running 'minikube start' with sudo).  However, didn't work for me so instead I manually changed the ownership using the guidance in the start.go code (which interestingly is printed out if CHANGE_MINIKUBE_NONE_USER is NOT set):

	sudo chown -R $USER $HOME/.minikube
	sudo chgrp -R $USER $HOME/.minikube

I now have problems connecting to the cluster with port 8443, but that's another issue.  The above commands did at least get rid of the permission denied errors.

**Comment by 345paul** [comment]
I ended up using the localkube bootstrapper when starting minikube and my problems went away, which I guess is not the best answer, but for now it works for me.

**Comment by mulargui** [comment]
@345paul,
I followed your recommendations and at least minikube start was able to complete (with errors). It turns out that it creates a new ~/.minikube/machines/minikube/config.json as root and later on it can't access it. 
I'm interested to follow your path with localkube and defer to later to solve the start issue. I don't have /usr/local/bin/localkube, how do you proceed?

**Comment by 345paul** [comment]
Hi, I added --bootstrapper=localkube to the minikube start command line.

**Comment by mulargui** [comment]
It worked, at least it completed with no errors. I observed now I only run 2 containers whereas before were about 8. I'll start submitting jobs and see how it goes. thank you for your help.

**Comment by tstromberg** [comment]
We do a terrible job of delivering the error message, but the crux of it is that there is already a None VM running:

[preflight] Some fatal errors occurred:
        [ERROR Port-8443]: Port 8443 is in use
        [ERROR Port-10251]: Port 10251 is in use
        [ERROR Port-10252]: Port 10252 is in use

Since there is no isolation between None configurations, it breaks.

**Comment by Behoston** [comment]
I had same issue when I upgraded minikube from 0.25 to 0.31. 

I fixed it killing localkube: https://github.com/kubernetes/minikube/issues/2146#issuecomment-363361092
then minikube statrs normally

**Comment by jsravn** [comment]
I'm not sure why, but in the last few days this started failing for me. `CHANGE_MINIKUBE_NONE_USER` has stopped working. Any ideas?

**Comment by madkote** [comment]
hi, having same issue with minikube v1.9.0
```
minikube start --driver=docker
minikube status
minikube stop
...
docker ps
>>> here are k8s containers
docker kill $(docker ps -q)
>>> here are k8s containers AGAIN
```
