### ISSUE TITLE
Hung at ContainerCreating: Error response from daemon: Get https://gcr.io/v2/: net/http: TLS handshake timeout"

### ISSUE THREAD

**Issue by AurelHugon** [kubernetes/minikube#2978]
**Environment**: 

**Minikube version** : v0.25.2
- **OS** :  Windows 10
- **VM Driver** : hyperv
- **ISO version** :  v0.25.1
- **Install tools**: chocolate
- **Others**:

**What happened**: The kube-addon-manager-minikube hangs on ContainerCreating

**What you expected to happen**: I exepct it to have the Running status and to have access to the Dashboard

**How to reproduce it** (as minimally and precisely as possible): 
Execute the following command (Minikube being the networking interface i defined in Hyperv) :
minikube start --vm-driver hyperv --hyperv-virtual-switch "Minikube"

**Output of `minikube logs` (if applicable)**:
See below file :
[minikube.txt](https://github.com/kubernetes/minikube/files/2192987/minikube.txt)

**Anything else do we need to know**:
I'm working behind my firm's firewall.

**Comment by tstromberg** [comment]
I suspect that HyperV is not routing HTTPS requests through your corporate proxy properly, but I'm really not sure how to recommend investigating this further just yet. Have you tried any non-minikube VM's with HyperV?

**Comment by gbraad** [comment]
@tstromberg docker machine will take the HTTP(S)_PROXY, NO_PROXY and set them for the docker environment, but they would also need to be applied to the ISO. we have modified some of the code on our end for this... (and including the lowercase variants). We will experience some issues.

@AurelHugon can you explain which variables you have set in your environment?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
