### ISSUE TITLE
Feature: Add option to disable setting current-context to minikube

### ISSUE THREAD

**Issue by chancez** [kubernetes/minikube#2979]
Feature request:

Have an option to disable the functionality in https://github.com/kubernetes/minikube/pull/294

I often start minikube primary to access the docker daemon, and I also have minikube's config setup correctly in a separate kubeconfig file. Whenever I run minikube start, it means I have to either change my $KUBECONFIG before starting the VM or modify the current-context after running minikube start, which is super annoying.

I propose adding a `--no-modify-current-context` flag to `minikube start`.

**Comment by tstromberg** [comment]
There is a `--keep-context` flag to `minikube start` which I believe appears to do what you want. Please re-open if this doesn't help.
