### ISSUE TITLE
shared folders cannot be mounted on OSX

### ISSUE THREAD

**Issue by kgignatyev-inspur** [kubernetes/minikube#2981]
**Is this a BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
minikube version: v0.28.0
- **OS** (e.g. from /etc/os-release):
OSX 10.13.6 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
"DriverName": "virtualbox",

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
 "Boot2DockerURL": "file:///Users/kgignatyev/.minikube/cache/iso/minikube-v0.28.0.iso",

**What happened**:

Host shared folder is not mounted

**What you expected to happen**:

Users folder to be mounted

**How to reproduce it** (as minimally and precisely as possible):

try to reach shared folder from host

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

It looks like virtualbox guest additions installation fails, when I mounted guest additions and tried to install them I got:

./VBoxLinuxAdditions.run 
Verifying archive integrity... All good.
Uncompressing VirtualBox 5.2.14 Guest Additions for Linux........
bzip2 not found.  Please install: bzip2 tar; and try again.

**Comment by dlorenc** [comment]
This should be fixed by #2986
