### ISSUE TITLE
Debian package should include the kvm driver (docker-machine-driver-kvm2)

### ISSUE THREAD

**Issue by marcominetti** [kubernetes/minikube#2982]
**Is this a BUG REPORT or FEATURE REQUEST?**: FEATURE REQUEST

The minikube-XXX-.deb package is intended to be used on debian systems. To simplify setup and usage of kvm2 driver, it could be include within the package (maybe provided through private debian repository). Thus the installation and upgrade of minikube will be more convenient.

Please provide the following details:

**Environment**: Linux

**Minikube version**: 0.27 and 0.28
- **OS** : Ubuntu 18.04
- **VM Driver**: KVM2

**What happened**:
I need to install and maintain (upgrade) docker-machine-driver-kvm2 manually as sudoer.

**What you expected to happen**:
Installing/upgrading the minikube through debian package, the docker-machine-driver-kvm2 is installed/upgraded accordingly.

**Comment by idvoretskyi** [comment]
+1, I second this.

**Comment by nmabhinandan** [comment]
+1

**Comment by afbjorklund** [comment]
I suppose removing the .deb altogether is another option ? Then it could be packaged _properly_ downstream instead, using PPA or some similar means. And then wouldn't have to defend the lack of .rpm etc (#402)

**Comment by afbjorklund** [comment]
If we packaged kvm2 as debs, maybe that could avoid versioning issues: #3437

**Comment by mgabeler-lee-6rs** [comment]
/remove-lifecycle rotten

This is still very desirable for Debian-based systems.

**Comment by afbjorklund** [comment]
@mgabeler-lee-6rs : note that virtualbox is still the default driver

Added some .deb packaging now, but it is not a hard dependency

**Comment by mgabeler-lee-6rs** [comment]
Given vbox as the default driver, `Suggests` seems like the right relation, yes.

Thanks for this!

**Comment by afbjorklund** [comment]
Most likely we will need to set up our own apt repository for this to work...

Similar to what is available for kubeadm (but **not** for `bionic`, just yet?)

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/#installing-kubeadm-kubelet-and-kubectl

```shell
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-xenial main
EOF
```

We also need to fix minikube build so that it actually builds it for `xenial`.

Currently there is a bug (#4555), so it bypasses docker and uses host. ☹

**Comment by idvoretskyi** [comment]
> Most likely we will need to set up our own apt repository for this to work...

It's a great idea.

**Comment by justaugustus** [comment]
Linking the conversation in #wg-k8s-infra, so that context doesn't lost on apt/yum repos: https://kubernetes.slack.com/archives/CCK68P2Q2/p1562665049225800

**Comment by afbjorklund** [comment]
@justaugustus : thanks for the link, but wasn't sure about the full context of the request
i.e. if minikube was to be included in the main repo, or set up a similar one for the project

We will start producing the packages for next release, so there should be some made for 1.3.0
Of course we already have the `minikube` packages, this was for `docker-machine-driver-kvm2`

**Comment by afbjorklund** [comment]
Packages are now available:

https://storage.googleapis.com/minikube/releases/v1.3.0/docker-machine-driver-kvm2_1.3.0.deb

https://storage.googleapis.com/minikube/releases/v1.3.0/docker-machine-driver-kvm2-1.3.0.rpm

No support for apt or yum yet.
