### ISSUE TITLE
V0.28 on brand new Macbook Pro, minikube start --vm-driver=hyperkit hangs

### ISSUE THREAD

**Issue by joannbrereton** [kubernetes/minikube#2983]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release): Mac OSX 10.13.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):     "DriverName": "hyperkit",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.28.0
- **Install tools**: brew cask install minikube 
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
```
$ minikube start --vm-driver=hyperkit
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 153.08 MB / 153.08 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.10.0
Downloading kubelet v1.10.0
Finished Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
```
**What you expected to happen**:
Expected  to come back to shell prompt.  But it hung.

**How to reproduce it** (as minimally and precisely as possible):
Out of the box Mac OSX High Sierra, use brew install instructions on page https://kubernetes.io/docs/tutorials/hello-minikube/#before-you-begin

**Output of `minikube logs` (if applicable)**:
minikube logs command also hangs

**Anything else do we need to know**:

**Comment by joannbrereton** [comment]
I seemed to have solved this by uninstalling, then reinstalling minikube.

**Comment by tangzhiyi11** [comment]
this work https://github.com/kubernetes/minikube/issues/2753#issuecomment-385191669
