### ISSUE TITLE
Kubernetes 1.11?

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/minikube#2988]
Thanks for all the hardwork folks. Any schedule for 1.11 release?

**Comment by dlorenc** [comment]
Ref #2990 should be out later today/tomorrow morning.

**Comment by dlorenc** [comment]
Fixed with #2990 and release 0.28.1

**Comment by tamalsaha** [comment]
@dlorenc , one quick question with the 0.28.1 release, I have to use `minikube start --kubernetes-version=v1.11.0` to get a 1.11 cluster. `minikube start` creates a 1.10 cluster. Should be default version be upgraded to 1.11 cluster?

**Comment by dlorenc** [comment]
We'll be following this up with a 0.29 release shortly, that will switch the default version.

**Comment by tamalsaha** [comment]
Cool! Thanks.

**Comment by wallyqs** [comment]
Not sure if reported already but `minikube get-k8s-versions` does not display v1.11 either

```
$ minikube version
minikube version: v0.28.1

$ minikube get-k8s-versions
The following Kubernetes versions are available when using the localkube bootstrapper: 
	- v1.10.0
	- v1.9.4
	- v1.9.0
	- v1.8.0
...
```

**Comment by kfox1111** [comment]
Any update on this?

**Comment by tamalsaha** [comment]
@kfox1111 , I just use `minikube start --kubernetes-version=v1.11.3`. Works for me.

**Comment by kfox1111** [comment]
I can confirm that does work.

So, I've been recommending users use minikube, but if it out of the box is going to choose older versions, it takes more effort for me to educate my users on how to properly deploy it to function like a recent Kubernetes.

Could we update the --kubernetes-version to default to downloading and using whatever's at https://storage.googleapis.com/kubernetes-release/release/stable.txt ?

**Comment by mrbobbytables** [comment]
I have been making the same suggestion to users regarding starting with the `--kubernetes-version` flag, but with 1.12 slated for release on the 27th it'd be great if the default version was limited to 1 release behind upstream.

**Comment by kfox1111** [comment]
how about minikube provided its own version url? then the minikube project can update the default separate from the kubernetes project's latest? Then we can debate what  the best default policy should be elsewhere? :)

**Comment by afbjorklund** [comment]
> The following Kubernetes versions are available **when using the localkube bootstrapper**
