### ISSUE TITLE
version: consider moving to 1.0

### ISSUE THREAD

**Issue by philips** [kubernetes/minikube#2995]
minikube has been a recommended stable tool for many releases of Kubernetes. Is there any reason to not start making 1.0+ releases? Maybe even tracking Kubernetes releases?

If not what are the milestones for doing that?

**Comment by dlorenc** [comment]
Nope, we should probably bump to v1 soon. I think tracking k8s would be a bit confusing because each version of minikube tends to support several k8s versions, though.

**Comment by philips** [comment]
I don't think all components that minikube relies on need to be "1.0" for
this project to go 1.0.

In this particular case though: Beta in Kubernetes for kubeadm essentially
means that the project is ready to use but doesn't have final API stability
guarantees. And given the spin up / tear down method used by minikube I
don't think this is a concern.

**Comment by tstromberg** [comment]
I agree.

The only milestone that comes to mind for 1.0 is rock-solid stability. We could measure this in a lot of ways, such as <1% integration test flakiness, and/or that the top 5 errors that users encounter are directly actionable. 

Either way, I think 1.0 would be a great Christmas or New Year's gift to minikube users.

**Comment by afbjorklund** [comment]
I would probably have used 0.29.1 rather than 0.30 - but hey, it's only numbers...
It would be neat if the cri-o functionality could be restored before 1.0, though ?

**Comment by afbjorklund** [comment]
Added #3296 (for cri-o)

**Comment by afbjorklund** [comment]
This is now closed, kubeadm is out of beta and cri-o works!

https://github.com/kubernetes/minikube/releases/tag/v1.0.0
