### ISSUE TITLE
Support kubernetes dashboard.

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#3]

**Comment by dharmit** [comment]
This can be achieved once you've configured the `kubectl` binary as mentioned [here](https://github.com/kubernetes/minikube#run-instructions). 

I downloaded the [yaml file](https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml), uncommented [line 50](https://github.com/kubernetes/dashboard/blob/master/src/deploy/kubernetes-dashboard.yaml#L50) to use appropriate IP-Port combination, and [proxy](https://github.com/kubernetes/dashboard#usage) it. It worked fine.

**Comment by dlorenc** [comment]
Thanks for trying this out!

**Comment by dlorenc** [comment]
Ref: https://github.com/kubernetes/kubernetes/issues/23727

**Comment by dlorenc** [comment]
Update: I tried it and it doesn't work. We need to include the cluster internal IP (10.0.0.1) in the cert we generate. Sending a PR, then we can close this!

**Comment by vishh** [comment]
@dlorenc Can we run the dashboard by default?

**Comment by luxas** [comment]
Yes, we should have it by default, with a flag to disable

**Comment by dlorenc** [comment]
What's the best way to run this by default? Just create the pod/deployment directly from minikube or pass it as a flag to the APIServer at startup time somehow? Maybe as an addon?

**Comment by vishh** [comment]
Run it as an addon. Have minikube create the dashboard.

**Comment by dlorenc** [comment]
Looks like we first need to bootstrap the addon-manager, then we can enable this as an addon. I'll close this bug since we support it now, and open others to track the next work items.
