### ISSUE TITLE
Instructions for installing Minikube on a GCP VM?

### ISSUE THREAD

**Issue by cyberbeast** [kubernetes/minikube#3002]
I am trying to install Minikube on a GCP vm. The VM is complaining that the computer doesn't have VT-X/AMD-v enabled. Are there any specific instructions to be followed to set up Minikube on GCP?

**Comment by dlorenc** [comment]
I think you'll need to make sure you've enabled nested virtualization on the VM here: https://cloud.google.com/compute/docs/instances/enable-nested-virtualization-vm-instances
