### ISSUE TITLE
minikube cluster never start with minikube start -p <name> option

### ISSUE THREAD

**Issue by ervikrant06** [kubernetes/minikube#3007]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**: 

**Minikube version** (use `minikube version`):v0.28.0
- **OS** (e.g. from /etc/os-release):
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): Not able to login.
- **Install tools**: NA
- **Others**: NA
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:

minikube never starts with `-p <name>` option. I need to work on federation feature. 

~~~
$ minikube start -p minikube1
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0723 18:04:36.704626   51909 start.go:294] Error starting cluster:  kubeadm init error sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  running command: : running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI
.: Process exited with status 1
~~~

**What you expected to happen**:
minikube should be able to start multiple instances without any issue. 

**How to reproduce it** (as minimally and precisely as possible):
Try to start minikube vm using -p <name> option. 

**Output of `minikube logs` (if applicable)**:
NA

**Anything else do we need to know**:
Deleted the existing default minikube before starting the new minikube using `-p <name>` option. Also ensure that context is deleted for the default minikube.

**Comment by ervikrant06** [comment]
Just to make it clear that I am able to start the minikube without any issue if I am not passing `-p` flag.

**Comment by balopat** [comment]
Yes, this is a bug, I ran into it as well.

**Comment by dvasdekis** [comment]
kubectl also crashes after stopping a named node - I believe this is related. To reproduce at terminal in OSX:
`minikube start; minikube start -p "minion-01"; kubectl get all`
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.96.0.1    <none>        443/TCP   9m
`minikube stop -p "minion-01"; kubectl get all`
No resources found.
Unable to connect to the server: ...

**Comment by ervikrant06** [comment]
Good to know that I am not the only one hitting this issue. Can anyone please look into this issue?

**Comment by ervikrant06** [comment]
It's working with latest version of minikube.
~~~
$ minikube version
minikube version: v0.28.2
~~~

**Comment by ravindraSB** [comment]
I am hitting this again on 1.7.3
