### ISSUE TITLE
Migrate from docker/machine to machine-drivers/machine

### ISSUE THREAD

**Issue by philips** [kubernetes/minikube#3019]
FYI, docker-machine is going into maintenance mode. So, this project will likely need to maintain a fork or do something else: https://github.com/docker/machine/issues/4537

**Comment by gbraad** [comment]
@philips We are already discussing this with @dlorenc and the rest of the Minikube team. For the moment we have a fork we work from and will investigate a long-term solution. Let's continue the discussion here: https://github.com/machine-drivers/machine/issues/4

**Comment by afbjorklund** [comment]
Since minishift has already changed, maybe minikube should do the same ?

https://github.com/minishift/minishift/pull/2652

Still using the same machine revision, though. So it is mostly the URL for now.

https://github.com/docker/machine/compare/v0.15.0...machine-drivers:1903531
