### ISSUE TITLE
Fedora: "dnf install minikube" installs gzip file instead of ELF binary

### ISSUE THREAD

**Issue by enzo1004** [kubernetes/minikube#3020]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

My computer : 
xxxx@localhost yum.repos.d]# uname -a
Linux localhost.localdomain 4.17.7-100.fc27.x86_64 #1 SMP Tue Jul 17 16:29:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I've minikube installed on my PC from  https://copr.fedorainfracloud.org/coprs/antonpatsev/minikube-rpm/repo/fedora-27/antonpatsev-minikube-rpm-fedora-27.repo

xxxx@localhost yum.repos.d]# which minikube
/usr/local/bin/minikube

**_I can't run  the commant : minikube start 
xxxx@localhost yum.repos.d]# minikube version
-bash: /usr/local/bin/minikube : impossible to execute the binary file : Exec format error_**

Please, help !

**Comment by dlorenc** [comment]
> I've minikube installed on my PC from https://copr.fedorainfracloud.org/coprs/antonpatsev/minikube-rpm/repo/fedora-27/antonpatsev-minikube-rpm-fedora-27.repo

I have no idea what that repo is, but the bug seems to be a packaging error in that process. Where did you find that link?

**Comment by remyabel** [comment]
That COPR repo is outdated and not very high quality. There are other similar COPR repos that just copy the precompiled binary. Instead, I would recommend just following the [build instructions I've put on my site](https://linuxguideandhints.com/fedora/kubernetes.html):

```
#!/bin/bash

export GOPATH=$(go env GOPATH)
export GOBIN=$GOPATH/bin

# go get will not work here, minikube expects to have a certain directory structure
if [ -n "$(find $GOPATH/src/k8s.io/minikube -maxdepth 0 -empty)" ]
then
    git clone https://github.com/kubernetes/minikube.git $GOPATH/src/k8s.io/minikube
fi
cd $GOPATH/src/k8s.io/minikube
git checkout -- .
git checkout $(git describe --abbrev=0 --tags)
make clean
make && make drivers

cp out/minikube $GOBIN
cp out/docker-machine-driver-kvm2 $GOBIN
```

This will checkout the latest tag, build and put it in `$GOBIN`, which you should add to your `$PATH`. You may also need to apply this patch:

```
diff --git a/Makefile b/Makefile
index 42b571bfd..8da3cf0b1 100755
--- a/Makefile
+++ b/Makefile
@@ -173,7 +173,7 @@ depend: out/minikube.d out/test.d out/docker-machine-driver-hyperkit.d out/stora
 all: cross drivers e2e-cross

 .PHONY: drivers
-drivers: out/docker-machine-driver-hyperkit out/docker-machine-driver-kvm2
+drivers: out/docker-machine-driver-kvm2

 .PHONY: integration
 integration: out/minikube
```

Feel free to make your own COPR repo based off these instructions, but I have no interest in maintaining an RPM myself.

**Comment by tstromberg** [comment]
Closing, since that repo isn't managed by us - still hasn't updated past 0.24!

**Comment by remyabel** [comment]
Wouldn't it be more appropriate to keep it open until, i.e there's a PR that either removes the link or changes it to a more up-to-date repo?
