### ISSUE TITLE
Ingress kills off active, long running tcp connections.

### ISSUE THREAD

**Issue by idcmp** [kubernetes/minikube#3039]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**: Linux
**Minikube version** (use `minikube version`): 0.28.2
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): the "none" driver

**What happened**:

Active, long lived connections through the nginx ingress were being killed off after approximately 40 seconds, even though my Ingress configuration has all the proper timeouts set to much, much longer.

**What you expected to happen**:

My connections should stay open.

**How to reproduce it** (as minimally and precisely as possible):

telnet to 80, or openssl s_client to 443 and slowly fill in an HTTP header, or ask for keep-alives, regardless of your action your connection will be closed.

**Anything else do we need to know**:

The closing stems from the workers being shutdown by the ingress controller, the timeout for this can be extended with "worker-shutdown-timeout" in the configmap of kube-system/nginx-load-balancer-conf.  However, there's no good, easy way to configure this value when installing the addon. It'd be cool to pass it in with "configure" or if the ingress was installed as a helm chart and the value was just templated.

**Comment by tstromberg** [comment]
Is this using the ingress minikube addon?
