### ISSUE TITLE
http://localhost:8001/ui does not redirect to dashboard

### ISSUE THREAD

**Issue by abdennour** [kubernetes/minikube#3041]
**Environment**:

**Minikube version** (use `minikube version`): v0.28.1
- **OS** : macOS Sierra v10.12.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.28.1.iso

**What happened**:

After running `kubectl proxy`, `http://localhost:8001/ui` shows the following in the browser:

![image](https://user-images.githubusercontent.com/1788384/43621162-ab400820-96de-11e8-949f-306d6110af49.png)

**What you expected to happen**:

- `http://localhost:8001/ui` should redirect to `http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kubernetes-dashboard/proxy/#!/overview`

![image](https://user-images.githubusercontent.com/1788384/43621333-76f8b87c-96df-11e8-88c6-93fc5c6423e0.png)

**How to reproduce it** (as minimally and precisely as possible):

- run `kubectl proxy`
- navigate to `http://localhost:8001/ui` through the browser or `curl http://localhost:8001/ui`

**Comment by tstromberg** [comment]
The /ui shortcut on the apiserver was deprecated in Kubernetes: https://github.com/kubernetes/dashboard/issues/3042

The new way to do this in minikube is: "minikube dashboard"
