### ISSUE TITLE
crictl within VM fails with "connection is unavailable" due to missing /etc/crictl.yaml

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#3043]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

** Details**

When configuring CRI-O as the container runtime, we should configure crictl to use it by default.

``` console
$ cat /etc/crictl.yaml
runtime-endpoint: unix:///var/run/dockershim.sock
image-endpoint: unix:///var/run/dockershim.sock
```
``` console
$ cat /etc/crictl.yaml
runtime-endpoint: unix:///var/run/crio/crio.sock
image-endpoint: unix:///var/run/crio/crio.sock
```

Otherwise using `crictl` will give an error, or maybe some ugly looking deprecation warning etc.

``` console
$ sudo crictl version
FATA[0000] getting the runtime version failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
$ sudo crictl -r /var/run/crio/crio.sock version
W0803 12:03:56.591607   15155 util_unix.go:75] Using "/var/run/crio/crio.sock" as endpoint is deprecated, please consider using full url format "unix:///var/run/crio/crio.sock".
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.10.0
RuntimeApiVersion:  v1alpha1

```

**Comment by afbjorklund** [comment]
Related to #3024

**Comment by tstromberg** [comment]
Confirmed. When this is used:

minikube start \
         --network-plugin=cni \
         --container-runtime=cri-o \
         --bootstrapper=kubeadm --vm-driver=kvm2

crictl version fails within "minikube ssh":

FATA[0000] getting the runtime version failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable 

This fixes it:

cat > /etc/crictl.yaml
runtime-endpoint: unix:///var/run/crio/crio.sock
image-endpoint: unix:///var/run/crio/crio.sock

**Comment by afbjorklund** [comment]
Sadly this needs to be set up by the provisioner, which I am not even sure _knows_ the runtime...

**Comment by afbjorklund** [comment]
@tstromberg : should be fixed now...

Note that you will still get the error above, unless you remember to run: **sudo** crictl version

``` console
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ crictl version
FATA[0000] getting the runtime version failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
$ sudo crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.10.0
RuntimeApiVersion:  v1alpha1
$ 
```

At least it doesn't segfault anymore, when running `crictl version` ? Always something...
