### ISSUE TITLE
Modification time in mounted volumes set to 1970-01-01

### ISSUE THREAD

**Issue by Diggsey** [kubernetes/minikube#3044]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version**
v0.28.0
- **OS**
Windows 10
- **VM Driver**
virtualbox
- **ISO version** ?

**What happened**:
- Mounted host directory into minikube, either via startup options or the `minikube mount` command.
- Entered the VM, via `minikube ssh`
- Ran `stat` on a file in the mounted directory
- Gave modification date of 1970

**What you expected to happen**:
- Gave actual modification date

**Anything else do we need to know**:
The built in virtualbox drivers are *far* superior to the minikube options: I would much prefer to use them if it were possible. The 9p driver has crippled my ability to use minikube due to multiple bugs and performance issues, whereas the virtualbox drivers have many years of development gone into them, and are particularly well suited to dealing with the differences between windows/linux hosts.

**Comment by ngoozeff** [comment]
This is still present in v0.30.0 & also affects Hyper-V (as it's due to a bug in the third_party/go9p server).

Maintainers, are you open to a patch in third_party/go9p/ufs_windows.go to resolve this? At the moment the code to set mtime and atime is commented out in that file.

**Comment by tstromberg** [comment]
@ngoozeff - We would love a patch for this issue.

**Comment by ngoozeff** [comment]
@tstromberg - great, I'll get started on the CLA process. Do you have any requirements around test cases etc I should be aware of?

**Comment by tstromberg** [comment]
@ngoozeff - That's a great question.

There is a strong preference for the PR to include a unit test that currently breaks, but would not break with the newly included change. I'm not that familiar with the code here, so I'm not sure how feasible it is.

It would also be useful to have a real-world integration test, by adding a functional test to:

https://github.com/kubernetes/minikube/blob/master/test/integration/mount_test.go

That way we won't accidentally reintroduce this issue sometime in the future.

**Comment by tstromberg** [comment]
Apparently fixed at head.
