### ISSUE TITLE
Failed to create symbolic link on mount: Operation not permitted

### ISSUE THREAD

**Issue by jpswade** [kubernetes/minikube#3057]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: OSX

**Minikube version** (use `minikube version`): v0.28.2
- **OS** (e.g. from /etc/os-release): Mac OS X High Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): .minikube/cache/iso/minikube-v0.28.1.iso
- **Install tools**:

**What happened**:

ln: failed to create symbolic link 'test1': Operation not permitted

**What you expected to happen**:

I would expect the symbolic link to create without a problem.

**How to reproduce it** (as minimally and precisely as possible):

```
docker run --rm -it \
    --volume ${PWD}:/usr/src/test \
    --workdir /usr/src/test \
    node:latest \
    bash
```

```
root@deca1a6f4779:/usr/src/test# touch test
root@deca1a6f4779:/usr/src/test# ln -s test test1
ln: failed to create symbolic link 'test1': Operation not permitted
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
On second thought, I suspect this is related to 9p mounts with Hyperkit, but I'd still like help on a repro case.
