### ISSUE TITLE
Upgrade toolbox image away from EOL'd Fedora 24

### ISSUE THREAD

**Issue by nixpanic** [kubernetes/minikube#3058]
**Is this a BUG REPORT**

Please provide the following details:

**Environment**:
minikube built from the master branch

**Minikube version**: v0.28.2
- **OS** (e.g. from /etc/os-release): Fedora 28 (x86_64)
- **VM Driver**: kvm2
- **ISO version**: 0.28.1

**What happened**:
`minikube ssh toolbox` downloaded an old unmaintained Fedora 24 image.

**What you expected to happen**:
Get a current and maintained toolbox image.

**How to reproduce it**:
`minikube ssh toolbox`

**Output of `minikube logs` (if applicable)**:

```
$ ./out/minikube ssh toolbox
Downloading sha256:d489011951f [=============================] 74.8 MB / 74.8 MB
successfully removed aci for image: "sha512-5e5ee85b9a286335820021e54b1685db3a8ebf2aea2403edddae013641ecf9ae"
rm: 1 image(s) successfully removed
Spawning container docker-fedora-24 on /var/lib/toolbox/docker-fedora-24.
Press ^] three times within 1s to kill container.
[root@minikube ~]# cat /etc/fedora-release 
Fedora release 24 (Twenty Four)
```

**Anything else do we need to know**:

Fedora 24 has been End-Of-Life for a while now. Current Fedora releases are listed on https://fedoraproject.org/wiki/Releases

**Comment by kauedg** [comment]
I'd like to take this one

**Comment by kauedg** [comment]
> **Is this a BUG REPORT**
> 
> Please provide the following details:
> 
> **Environment**:
> minikube built from the master branch
> 
> **Minikube version**: v0.28.2
> 
>     * **OS** (e.g. from /etc/os-release): Fedora 28 (x86_64)
> 
>     * **VM Driver**: kvm2
> 
>     * **ISO version**: 0.28.1
> 
> 
> **What happened**:
> `minikube ssh toolbox` downloaded an old unmaintained Fedora 24 image.
> 
> **What you expected to happen**:
> Get a current and maintained toolbox image.
> 
> **How to reproduce it**:
> `minikube ssh toolbox`
> 
> **Output of `minikube logs` (if applicable)**:
> 
> ```
> $ ./out/minikube ssh toolbox
> Downloading sha256:d489011951f [=============================] 74.8 MB / 74.8 MB
> successfully removed aci for image: "sha512-5e5ee85b9a286335820021e54b1685db3a8ebf2aea2403edddae013641ecf9ae"
> rm: 1 image(s) successfully removed
> Spawning container docker-fedora-24 on /var/lib/toolbox/docker-fedora-24.
> Press ^] three times within 1s to kill container.
> [root@minikube ~]# cat /etc/fedora-release 
> Fedora release 24 (Twenty Four)
> ```
> 
> **Anything else do we need to know**:
> 
> Fedora 24 has been End-Of-Life for a while now. Current Fedora releases are listed on https://fedoraproject.org/wiki/Releases

I'd like to take this issue as my first. Already fixed it locally.

**Comment by kauedg** [comment]
I'd like to take this issue as my first. Already fixed it locally. @nixpanic  @tstromberg
