### ISSUE TITLE
get-k8s-versions: dial tcp: lookup storage.googleapis.com: no such host

### ISSUE THREAD

**Issue by cloudpathshala** [kubernetes/minikube#3062]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release): 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:

I am trying to run command PS C:\> .\minikube.exe get-k8s-versions but it is not showing version. Rather it is showing below error.

PS C:\>
PS C:\>
PS C:\> .\minikube.exe get-k8s-versions
E0810 10:47:41.502406    2752 kubernetes_versions.go:39] Error getting json via http with url: https://storage.googleapis.com/minikube/k8s_releases.json: Error getting json from url: https://storage.googleapis.com/minikube/k8s_releases.json via http: Get https://storage.googleapis.com/minikube/k8s_releases.json: dial tcp: lookup storage.googleapis.com: no such host
PS C:\>

**What you expected to happen**:
It should show kubernetes versions

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by psreed** [comment]
Looks as though your host is having an issue reaching the URL where the version list is stored:  https://storage.googleapis.com/minikube/k8s_releases.json ... if you pop that URL into a web browser, do you see the list?

I see the list on my Windows machine using both a browser to that URL and my "minikube get-k8s-versions" through PowerShell. I get the list as expected, although the list is a bit out of date having 1.10.0 as the newest version...

**Comment by tstromberg** [comment]
Does this work?

"ping storage.googleapis.com"

**Comment by tstromberg** [comment]
Closing this as it appears to be a host configuration issue. If ping works, please re-open.

**Comment by shenbakeshkishore** [comment]
similar issue, ping works, want to know if there any limit in making tcp connections to a file hosted in a storage of a particular Google cloud account?
