### ISSUE TITLE
hyperv: Too many retries waiting for SSH to be available / target machine actively refused it.

### ISSUE THREAD

**Issue by vivinjoseph9** [kubernetes/minikube#3069]
minikube version: v0.28.2

kubectl version : Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.3", GitCommit:"2bba0127d85d5a46ab4b778548be28623b32d0b0", GitTreeState:"clean", BuildDate:"2018-05-21T09:17:39Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"windows/amd64"}
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

OS : windows 10

minikube logs : F0813 14:52:15.753035   14752 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found

docker : 18.06.0 (Community edition for windows)

vm driver : Hyper-V

Have followed the steps as per -  https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c.

Expecting the cluster to start running normally.

But instead getting the following error:

C:\>minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E0813 14:28:30.508122   22044 start.go:174] Error starting host: Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded.

 Retrying.
E0813 14:33:32.996420   22044 start.go:174] Error starting host: Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded.

Please help on how to resolve this, have checked various guides however none could help me resolve the issue.

**Comment by Mikerr1111** [comment]
I have seen this issue before it has to with a docker default. I provide some links and docs below that address and fix your issue.
https://forums.docker.com/t/using-docker-for-windows-docker-machine-create/8032/4

https://docs.docker.com/machine/drivers/hyper-v/

https://docs.docker.com/machine/get-started/

**Comment by tstromberg** [comment]
Agreed, this seems like a HyperV virtual switch issue. Is your Virtual Switch defined on a wireless device, by any chance? I ask because it sounds similar to #2866

**Comment by gbraad** [comment]
@tstromberg As mentioned on that issue, Wifi does not have to cause issues... but in this issue I can see they also mention Docker for Windows (D4W) which can be configured with LCOW... and this can cause issues in the network stack.

There is too little information about the actual setup... while from the linked document I can see an External switch is setup, I am not sure if this is realy correct for the OP.

@vivinjoseph9 does the issue still exist?

**Comment by AlanCarlyle** [comment]
I had problems similar to this well doing an upgrade to v0.31.0 using Chocolatey. The advice I gave here https://github.com/kubernetes/minikube/issues/3430#issuecomment-449619994 might help.

Basically  clear the DNS cache with a ```ipconfig /flushdns```  after (and before) creating the minikube virtual switch. (Also might consider uninstalling stale hyper-v network interfaces first).

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
