### ISSUE TITLE
Missing docker.service.d/10-machine.conf file in /etc/systemd/system/ in minikube ssh (version v0.28.2)

### ISSUE THREAD

**Issue by Saipranany** [kubernetes/minikube#3070]
**Is this a BUG REPORT 

In v.0.28.0 version of minikube the global conf file in docker.service.d/10-machine.conf was missing which is present in minikube version v0.20.0.
Just have clarify if the file was replaced with some other name or location. 
OR it was missing because of some conf issue 
Environment : -
Windows 10 
In Virtual Box 
Expected 
Presence of docker.service.d/10-machine.conf in /etc/systemd/system/ in minikube ssh

**Comment by tstromberg** [comment]
Do you mind elaborating what side effect you are seeing due to this file being missing?

**Comment by Saipranany** [comment]
while starting the minikube i gave some proxy parameters and in the older version i used to unset them in minikube ssh in that 10-machine.conf file but when it comes to the latest version i cant find the file in the mentioned location (/etc/systemd/system/). I have followed the latest documentation of docker for setting the proxy using ENV variable but cant find any ways to unset .

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Consider using `--docker-env` to set the proxy environment: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

Thank you for opening the issue!
