### ISSUE TITLE
efk: "Kibana did not load properly" because of missing SERVER_BASEPATH

### ISSUE THREAD

**Issue by broeser** [kubernetes/minikube#3071]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Environment**:
Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux

**Minikube version** (use `minikube version`): v.0.28.0
- **OS** (e.g. from /etc/os-release): Debian GNU/Linux 9 (stretch)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):

**What happened**: When opening the kibana dashboard via proxy, it displayed
"Kibana did not load properly. Check the server output for more information."
in a big red box

**What you expected to happen**:
The Kibana dashboard to load

**How to reproduce it** (as minimally and precisely as possible):
- enable the efk addon
- kubectl proxy
- Open http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kibana-logging/proxy/app/kibana in a browser

**Anything else do we need to know**:
The SERVER_BASEPATH environment variable was missing. I could fix the issue on my system by adapting the kibana-logging replication controller by adding this:
SERVER_BASEPATH: /api/v1/namespaces/kube-system/services/kibana-logging/proxy

However I believe, the plugin should work out of the box via proxy

**Comment by tstromberg** [comment]
Is this with the efk addon?

**Comment by tstromberg** [comment]
I wasn't able to replicate this, but I didn't get the proxy to work either:

http://127.0.0.1:8001/api/v1/namespaces/kube-system/services/kibana-logging/proxy/ for me renders:

```
Error: 'dial tcp 172.17.0.6:5601: connect: connection refused'
Trying to reach: 'http://172.17.0.6:5601/
```

The logs for the pod seem OK though:

`{"type":"log","@timestamp":"2019-01-23T23:29:05Z","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for graph, ml, kibana, stateSessionStorageRedirect, timelion and status_page. This may take a few minutes"}`

It's unclear to me if this is behaving as expected, or if a problem still exists. How did you see the SERVER_BASEPATH error?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
