### ISSUE TITLE
Upgrade minikube to kubernetes 1.10.5 to address backoffLimit bug

### ISSUE THREAD

**Issue by rmorrise** [kubernetes/minikube#3074]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Critical bug in kubernetes v1.10.x
See: https://github.com/kubernetes/kubernetes/issues/62382

Please provide the following details:

**Environment**:
Win64

**Minikube version** (use `minikube version`): 0.28.2
- **OS** (e.g. from /etc/os-release): Windows 7
- **VM Driver** virtualbox
- **ISO version** 0.28.1
- **Install tools**: Manual download
- **Others**: Kubernetes client 1.10.2, server 1.10.0

**What happened**:

When a job pod fails, kubernetes ignores `backoffLimit` and creates an infinite number of pods. See:
https://github.com/kubernetes/kubernetes/issues/62382

**What you expected to happen**:

The job should stop creating pods after reaching the backoff limit.

**How to reproduce it** (as minimally and precisely as possible):
Create a failing job with `.spec.backoffLimit` set to 3

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
Fixed in Kubernetes `1.10.5`

**Comment by rmorrise** [comment]
Thank you!

**Comment by dlorenc** [comment]
Until we get a release with this out, you should be able to specify version 1.10.5 on your own:

```shell
$ minikube start --kubernetes-version=v1.10.5
Starting local Kubernetes v1.10.5 cluster...
Starting VM...
```

**Comment by Ark-kun** [comment]
Still not fixed in latest minikube release. This bug seems critical to me.

**Comment by tstromberg** [comment]
Obsolete, since we're at v1.13.2 nowadays.
