### ISSUE TITLE
Change deprecated "aufs" docker storage driver

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#3078]
The AUFS storage driver is deprecated (for `overlay2`), so should be changed in the client code.

The minikube.iso already uses the new driver, so there should be no impact for most users ?

See https://github.com/boot2docker/boot2docker/issues/1326

And https://github.com/docker/machine/pull/4558

**Comment by dlorenc** [comment]
This SGTM

**Comment by afbjorklund** [comment]
It might be possible to not choose _anything_, but let Docker decide - haven't tried it though.

**Comment by afbjorklund** [comment]
The reason why this "works" at the moment, is because the buildroot provisioner _ignores_ StorageDriver:

https://github.com/kubernetes/minikube/blob/master/vendor/github.com/docker/machine/libmachine/provision/boot2docker.go#L153

https://github.com/kubernetes/minikube/blob/master/pkg/provision/buildroot.go#L92

Since we upgraded buildroot Docker CE from the supported 17.03.3 to 17.12.1, we get overlay2 by default:

> [17.09.0-ce (2017-09-26)](https://docs.docker.com/release-notes/docker-ce/#17090-ce-2017-09-26)
> ...
> Runtime
>     Graphdriver: promote overlay2 over aufs [moby/moby#34430](https://github.com/moby/moby/pull/34430)

But should still update the minikube machine code to match the docker machine code (change above)

``` diff
--- a/pkg/minikube/machine/client.go
+++ b/pkg/minikube/machine/client.go
@@ -110,7 +110,7 @@ func (api *LocalClient) NewHost(driverName string, rawDriver []byte) (*host.Host
                                ServerKeyPath:    filepath.Join(api.GetMachinesDir(), "server-key.pem"),
                        },
                        EngineOptions: &engine.Options{
-                               StorageDriver: "aufs",
+                               StorageDriver: "overlay2",
                                TLSVerify:     true,
                        },
                        SwarmOptions: &swarm.Options{},

```

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/machine/client.go
