### ISSUE TITLE
README.md: Add Kubernetes as a requirement

### ISSUE THREAD

**Issue by knweiss** [kubernetes/minikube#308]
IMHO the "Requirements" section in `README.md` should explicitly list **Kubernetes** as a requirement (e.g. for `kubectl`) which is a substantial download.

**Comment by knweiss** [comment]
Ah, I've just noticed #83 and #216. Maybe the `kubectl` download link in #83 should be listed in the requirements instead.

**Comment by dlorenc** [comment]
We added a section to the docs on how to install kubectl. Eventually we'd like to just install it for the user :)
