### ISSUE TITLE
efk: CrashLoopBackOff: Back-off 5m0s restarting failed container=elasticsearch-logging

### ISSUE THREAD

**Issue by bennettellis** [kubernetes/minikube#3085]
BUG REPORT

**Environment**: running Kubernetes and Minikube

**Minikube version**:v0.28.2
- **OS**: Virtual Ubuntu 18.04 Server 
- **VM Driver**: *NONE*
- **ISO version**: 'none' driver does not support 'minikube ssh' command
- **Install tools**: Terraform
- **Others**: minikube start --vm-driver=none --memory=8096
minikube addons enable efk

**What happened**: Went to <IP>:30003 to access Kibana console. Always displays red status with many of the related services "unreachable"

ID | Status
-- | --
ui settings | Elasticsearch plugin is red
plugin:kibana@5.6.2 | Ready
plugin:elasticsearch@5.6.2 | Request Timeout after 3000ms
plugin:xpack_main@5.6.2 | Request Timeout after 3000ms
plugin:graph@5.6.2 | Request Timeout after 3000ms
plugin:reporting@5.6.2 | Request Timeout after 3000ms
plugin:searchprofiler@5.6.2 | Request Timeout after 3000ms
plugin:ml@5.6.2 | Request Timeout after 3000ms
plugin:tilemap@5.6.2 | Request Timeout after 3000ms
plugin:watcher@5.6.2 | Request Timeout after 3000ms
plugin:grokdebugger@5.6.2 | Ready
plugin:upgrade@5.6.2 | Request Timeout after 3000ms
plugin:console@5.6.2 | Ready
plugin:metrics@5.6.2 | Ready
plugin:timelion@5.6.2 | Ready

**What you expected to happen**: Access a beautiful Kibana console without errors

**How to reproduce it** (as minimally and precisely as possible):
minikube start --vm-driver=none --memory=8096
minikube addons enable efk
Access Kibana console in browser
Observe Kibana state

**Output of `minikube logs`**:
*seems like there's a lot of this in my minikube logs when I grep for 'failed'*:
Aug 18 13:07:42 ip-10-0-101-161 kubelet[22782]: E0818 13:07:42.884907   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:07:53 ip-10-0-101-161 kubelet[22782]: I0818 13:07:53.884560   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:07:53 ip-10-0-101-161 kubelet[22782]: E0818 13:07:53.884589   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:08:05 ip-10-0-101-161 kubelet[22782]: I0818 13:08:05.884563   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:08:05 ip-10-0-101-161 kubelet[22782]: E0818 13:08:05.884595   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:08:19 ip-10-0-101-161 kubelet[22782]: I0818 13:08:19.884521   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:08:19 ip-10-0-101-161 kubelet[22782]: E0818 13:08:19.884552   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:08:33 ip-10-0-101-161 kubelet[22782]: I0818 13:08:33.884580   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:08:33 ip-10-0-101-161 kubelet[22782]: E0818 13:08:33.884609   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:08:46 ip-10-0-101-161 kubelet[22782]: I0818 13:08:46.884836   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:08:46 ip-10-0-101-161 kubelet[22782]: E0818 13:08:46.884869   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:08:59 ip-10-0-101-161 kubelet[22782]: I0818 13:08:59.884556   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:08:59 ip-10-0-101-161 kubelet[22782]: E0818 13:08:59.884585   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:09:12 ip-10-0-101-161 kubelet[22782]: I0818 13:09:12.884722   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:09:12 ip-10-0-101-161 kubelet[22782]: E0818 13:09:12.884752   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:09:26 ip-10-0-101-161 kubelet[22782]: I0818 13:09:26.884885   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:09:26 ip-10-0-101-161 kubelet[22782]: E0818 13:09:26.884913   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:09:42 ip-10-0-101-161 kubelet[22782]: I0818 13:09:42.884966   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:09:42 ip-10-0-101-161 kubelet[22782]: E0818 13:09:42.885000   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"
Aug 18 13:09:55 ip-10-0-101-161 kubelet[22782]: I0818 13:09:55.884560   22782 kuberuntime_manager.go:767] Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)
Aug 18 13:09:55 ip-10-0-101-161 kubelet[22782]: E0818 13:09:55.884589   22782 pod_workers.go:186] Error syncing pod be766374-a2e1-11e8-a61c-0e7cf5041436 ("elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"), skipping: failed to "StartContainer" for "elasticsearch-logging" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=elasticsearch-logging pod=elasticsearch-logging-8xscd_kube-system(be766374-a2e1-11e8-a61c-0e7cf5041436)"

**Anything else do we need to know**: Again, using --vm-driver=*none*, and wondering if the lack of ssh support is related to the failures I'm seeing, and if so, is there a workaround for minikube with --vm-driver=none. The reason I'm using that driver is because I'm building a prototype for a single machine k83 cluster wherein all services used by the solution are deployed to the minikube cluster. The final solution will be deployed to a physical server rather than virtual server, but because it's virtual for the purposes of this testing, I cannot use the default (vbox) or other virtualization driver. If it's related to lack of ssh support, is there a workaround for that?

**Comment by bennettellis** [comment]
**Update:**
 seems that after some time of cycling with status looking like this:

error
elasticsearch-logging-j69bg
kube-system
minikube
Waiting: CrashLoopBackOff
16
an hour
Back-off restarting failed container 

It finally changes to "Running" state.

In the browser, the console started the setup process, but then within a few minutes bounced back to the RED state and the container went back into CrashLoopBackOff state.

I have 16GB RAM and 4 cores on this box with a 30GB storage device. Nothing else was running in the K8s cluster besides the minikube node itself, and as mentioned above, I started minikube with --memory=8096 so it doesn't seem like I am hitting some memory or resource issue, right?

**Comment by bennettellis** [comment]
*Update:*
After reading around quite a while, realized that I probably needed to set the env for ES_JAVA_OPTS as suggested a few places. I edited my elasticsearch replication controller that was deployed automatically by enabling the EFK addon and added an "env" section:
```
{
  "name": "ES_JAVA_OPTS",
  "value": "-Xms1024m -Xmx1024m"
}

And now it seems to be up, at least for now.  Question I have is why is this the default setting for this minikube addon.  This will literally break EVERY TIME. Seems like the YAML file here:

**Comment by tstromberg** [comment]
If this env variable is required, would love to see this fixed in the addon itself. Happy to review any PR's which attempt it.

**Comment by bennettellis** [comment]
I think I remember submitting a PR for that...can't say for sure.




On Wed, Jan 23, 2019 at 6:46 PM -0500, "Thomas Strömberg" <notifications@github.com> wrote:












If this env variable is required, would love to see this fixed in the addon itself. Happy to review any PR's which attempt it.
