### ISSUE TITLE
failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF

### ISSUE THREAD

**Issue by vivinjoseph9** [kubernetes/minikube#3097]
Minikube: v0.25.0

Kubectl: Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.0", GitCommit:"91e7b4fd31fcd3d5f436da26c980becec37ceefe", GitTreeState:"clean", BuildDate:"2018-06-27T20:17:28Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"windows/amd64"}

OS: Windows 10

Docker: Docker for windows - Version 18.06.0-ce-win72 

GoVersion: go1.10.2

vm driver : Hyper-V

Tried to run a sample program on minikube to check whether if can be used for local testing,

Ran the example given under the client-go library:
https://github.com/kubernetes/client-go/tree/master/examples/in-cluster-client-configuration

Added all necessary dependencies using "dep".
->"go build" led to the program being complied successfully

Docker image was created using the dockerfile provided in the examples, and all the steps mentioned in the Readme file.

->Docker image was also created.

->Using the "kubectl run" command and using the above mentioned image, the deployment was created.

-> "kubectl get deployments" command showed the nothing to be wrong

Expected: pod to be wrong with out any errors and the able to retrieve the pods

Actual:
-> "kubectl get pods" command showed the pod and its status as "CrashLoopBackoff"

-> i checked the logs to find out the cause and it showed the below:
"log : failed to get container status {"" ""}: rpc error: code = OutOfRange desc = EOF"

**Comment by tstromberg** [comment]
Do you mind sharing your "minikube start" command?

Also, the output of "minikube ssh "journalctl -u kubelet"  would be useful here.

**Comment by tstromberg** [comment]
Also, please share the logs for:

```shell
kubectl describe pod <name of crashing pod>
```
