### ISSUE TITLE
Cannot use private registry using private CA

### ISSUE THREAD

**Issue by vinz486** [kubernetes/minikube#311]
`$ minikube ssh`
`$ sudo -s`
`# docker login my.private.registry`
`Username: username`
`Password: `
`Error response from daemon: Get https://my.private.registry/v1/users/: x509: certificate signed by unknown authority`

I followed almost all tips about how setup private CA in the system, nothing seems working.

Where I need to put my ca.cert?

Thank you.

**Comment by dlorenc** [comment]
Hey,

I think you need to copy the cert into the VM. The location should be:

/etc/docker/certs.d/<hostname>

from here: https://docs.docker.com/engine/security/certificates/

**Comment by dlorenc** [comment]
Any luck with this?

**Comment by vinz486** [comment]
Yes. It's working.

Thank you.

(I was missing the subdomain part in /cert.d/ directory)

**Comment by dlorenc** [comment]
Cool, thanks!

**Comment by floridoo** [comment]
BTW: a handy one-liner for scripts:
```bash
cat <certificatefile> | minikube ssh "sudo mkdir -p /etc/docker/certs.d/<domain> && sudo tee /etc/docker/certs.d/<domain>/ca.crt"
```
