### ISSUE TITLE
failed pulling image: Get https://k8s.gcr.io/v2/: Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by WhoisZihan** [kubernetes/minikube#3115]
BUG REPOR

I know this is the same as [#2018](https://github.com/kubernetes/minikube/issues/2018), but with latest version it still doesn't work and I can only start with `--bootstrapper=localkube`, other bootstrappers never work.

**Minikube version** : v0.28.2
- **OS** : Ubuntu 16.04.5 LTS (Xenial Xerus)
- **VM Driver** : kvm2 (But virtualbox does not work either)
- **ISO version** : minikube-v0.28.1.iso, boot2docker.iso
- **Install tools**:
     * kubectl version: v1.11.2
     * kubeadm version: v1.10.0
     * kubelet version: v1.10.0
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

VM driver:
    "DriverName": "kvm2",

ISO version
        "Boot2DockerURL": "file:///home/fma/.minikube/cache/iso/minikube-v0.28.1.iso",
        "ISO": "/home/fma/.minikube/machines/minikube/boot2docker.iso",
```

**What happened**:
The command `minikube start --vm-driver kvm2 --bootstrapper=kubeadm` will get stuck at `Starting cluster components...`. By checking `minikube logs`, I find it gets refused when trying to connect to `127.0.0.1:8443: getsockopt: connection refused`

**What you expected to happen**:
It starts normally.

**How to reproduce it** (as minimally and precisely as possible):
1. Download `minikube v0.28.2` and `kubelet v1.11.2`
2. type `minikube start --vm-driver kvm2 --bootstrapper=kubeadm`
3. Waiting for it to get stuck

**Output of `minikube logs` (if applicable)**:
Here is part of it
> Sep 05 12:24:15 minikube kubelet[2686]: E0905 12:24:15.468704  2686 pod_workers.go:186] Error syncing pod 31cf0ccbee286239d451edb6fb511513 ("kube-scheduler-minikube_kube-system(31cf0ccbee286239d451edb6fb511513)"), skipping: failed to "CreatePodSandbox" for "kube-scheduler-minikube_kube-system(31cf0ccbee286239d451edb6fb511513)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-scheduler-minikube_kube-system(31cf0ccbee286239d451edb6fb511513)\" failed: rpc error: code = Unknown desc = failed pulling image \"k8s.gcr.io/pause-amd64:3.1\": Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)"
> 
> Sep 05 12:24:15 minikube kubelet[2686]: E0905 12:24:15.608771    2686 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: getsockopt: connection refused

**Anything else do we need to know**:
1. I can start with `--bootstrapper=localkube` but not with kubeadm, will it be the issue of RBAC?
2. I can do `ping k8s.io`, but I can NOT `ping k8s.gcr.io`, will this cause start failure too?
3. I also tried specifying `--kubernetes-version=v1.9.4`, but not working either.

**Comment by tstromberg** [comment]
Do you mind attaching a full log file? There seems to be two main issues here:

- Unable to deploy kube-scheduler because it can't access k8s.gcr.io.
- The apiserver isn't running (:8443 connect refused)

The second can be many things. The first is indicative of a connectivity failure to GCR: is this minikube instance running within China, by any chance? 

We should find a way to install minikube so that it doesn't require external connectivity.
