### ISSUE TITLE
Unstable DNS with None driver: Can't find mysql-server.default.svc.cluster.local: No answer

### ISSUE THREAD

**Issue by MartinKosicky** [kubernetes/minikube#3116]
BUG REPORT

**Environment**:
Ubuntu 16.04 in virtual box

**Minikube version** (use `minikube version`):  v0.28.2
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **Install tools**: manual install using wget according to the welcome page

**What happened**:
The lookup works only rarely and if it does it's slow

**What you expected to happen**:
I expect the lookup is always working and fast (its just on the same machine)

**How to reproduce it** (as minimally and precisely as possible):
I install a fresh minikube. Install helm in minikube. Minikube is start with --vm-driver=none on ubuntu 16.04.  I install a mysql server using 

`helm install --name mysql-server stable/mysql`

then I make a test:
`kubectl run -ti -i fff2 --image=busybox`
`$nslookup mysql-server.default.svc.cluster.local`

The nslookup I make several times, most of the times I get:
> nslookup mysql-server.default.svc.cluster.local
  Server:		10.96.0.10
  Address:	10.96.0.10:53
  *** Can't find mysql-server.default.svc.cluster.local: No answer

 Sometimes i actually get an answer but it's only rarely.

minikube started with  
`sudo minikube start --vm-driver=none`

**Comment by tstromberg** [comment]
Just to clarify, what was the "minikube start" command you used?

**Comment by tstromberg** [comment]
kubectl get svc --namespace=kube-system
Do you mind sharing the output of:

```
kubectl get ep kube-dns --namespace=kube-system

kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name | head -1) -c kubedns

kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name | head -1) -c dnsmasq

kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name | head -1) -c sidecar
```

Thanks!

**Comment by MartinKosicky** [comment]
Sorry I will try to post as soon as I got the system working... currently the dns-kube wont start the kubedns... or it's not ready as I get 
`Warning  Unhealthy              3m (x7 over 4m)  kubelet, minikube  Readiness probe failed: Get http://172.17.0.4:8081/readiness: dial tcp 172.17.0.4:8081: getsockopt: connection refused
`

also dashboard keeps failing as it can't connect to api server https://10.96.0.1:443/version but the kube-api-server pod seems to be running,  it's like the connection doesnt work at all :\

**Comment by MartinKosicky** [comment]
Ok I got it all working... it was the iptables created were dropping packets to my api-server probabbly by the kube-proxy.

The kube-proxy created these rules:
`
Chain KUBE-SERVICES (1 references)
num  target     prot opt source               destination         
1    REJECT     udp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns has no endpoints */ udp dpt:domain reject-with icmp-port-unreachable
2    REJECT     tcp  --  anywhere             10.96.0.10           /* kube-system/kube-dns:dns-tcp has no endpoints */ tcp dpt:domain reject-with icmp-port-unreachable
3    REJECT     tcp  --  anywhere             10.99.226.168        /* kube-system/kubernetes-dashboard: has no endpoints */ tcp dpt:http reject-with icmp-port-unreachable
`

so i was unable to do anything with this so I added a global accept to the INPUT chain at the front of the list 
`
sudo iptables -I INPUT  -p tcp -j ACCEPT
`

which is enough for me for now
