### ISSUE TITLE
kubernetes 1.4.0: downloading kubeadm received invalid status code: 404

### ISSUE THREAD

**Issue by triodan** [kubernetes/minikube#3119]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

Please provide the following details:

**Environment**:

**Minikube version**: v0.28.2
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.1
- **VM Driver**): virtualbox
- **ISO version**: minikube-v0.28.1.iso
- **Install tools**: Downloaded direct from GCS

**What happened**:

Trying to create a kubernetes 1.4.0 cluster using minikube fails because the kubeadm binary cannot be downloaded (code 404 instead of 200)

**What you expected to happen**:

Successful creation of kubernetes cluster v.1.4.0

**How to reproduce it** (as minimally and precisely as possible):

On a fresh minikube installation:
```
>minikube start --kubernetes-version v1.4.0
Starting local Kubernetes v1.4.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.4.0
E0906 13:57:42.039985   32655 start.go:258] Error updating cluster:  downloading binaries: downloading kubeadm: Error downloading kubeadm v1.4.0: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:

* received invalid status code: 404 (expected 200)
```

**Output of `minikube logs` (if applicable)**:

```
-- Logs begin at Thu 2018-09-06 06:54:07 UTC, end at Thu 2018-09-06 07:03:15 UTC. --
-- No entries --
```

**Comment by tstromberg** [comment]
I suspect this may be because kubeadm 1.4.0 is no longer available for download at that site. It's 2 years old at this point :(

We can do a better job about detecting versions which will no longer work.
