### ISSUE TITLE
kubelet: unknown flag: --bootstrap-kubeconfig on old k8s versions (1.6)

### ISSUE THREAD

**Issue by Sicaine** [kubernetes/minikube#3120]
BUG REPORT

**Environment**:
**Minikube version** (use `minikube version`): v0.28.2, v0.27.0, v0.26.0
- **OS** (e.g. from /etc/os-release): MacOS 10.13.6
- **VM driver**: "DriverName": "virtualbox",
- **ISO version** "Boot2DockerURL": "file:///Users/d073468/.minikube/cache/iso/minikube-v0.27.0.iso (also, v026.0.iso etc.)

**What happened**: Hang on 'Starting Cluster Components' when starting v1.6.4 kubernetes cluster. Logfile shows hint of unkown flag on kubelet: "unkown flag: --bootstrap-kubeconfig"

**What you expected to happen**: minikube starting normally

**How to reproduce it** (as minimally and precisely as possible): Make sure everything is clean, than start with specific version: minikube start --kubernetes-version v1.6.4

**Output of `minikube logs` (if applicable)**:
Sep 06 11:56:47 minikube systemd[1]: kubelet.service: Unit entered failed state.
Sep 06 11:56:47 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Sep 06 11:56:58 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Sep 06 11:56:58 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Sep 06 11:56:58 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Sep 06 11:56:58 minikube kubelet[4129]: unknown flag: --bootstrap-kubeconfig
Sep 06 11:56:58 minikube kubelet[4129]: Usage of /usr/bin/kubelet:

**Comment by tstromberg** [comment]
Sorry to hear about this being broken.

We should explicitly call-out which versions we support and fail early for combinations we know are not going to work. Kubernetes 1.6.4 is now 487 days old, and probably not possible for us to support unless someone provides patches to do so.

My guess is that --bootstrap-kubeconfig was added sometime within the last year, and we ended up finding it useful.

**Comment by Sicaine** [comment]
@tstromberg i'm just surprised that there is no versioning in between. I'm absolutely fine if Kubernetes in 1.6 runs on/with software which is similar old.

**Comment by tstromberg** [comment]
Closing, as Kubernetes v1.11.7 is the oldest supported version as per the Kubernetes versions policy.
