### ISSUE TITLE
kube-dns CrashLoopBackOff,  Liveness probe failed: getsockopt: no route to host

### ISSUE THREAD

**Issue by rlords** [kubernetes/minikube#3130]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Environment**:
Debian 9.5 minikube --vm-driver=none w/ docker
**Minikube version** (use `minikube version`):
- **OS**: Debian 9.5
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- **VM Driver**: v0.28.2

**What happened**:
minikube docker DNS server keeps getting in a crash loop back

**What you expected to happen**:
It to load properly and work.

**Output of `minikube logs` (if applicable)**:

root@id5086:~# kubectl -n kube-system describe pod kube-dns-86f4d74b45-59dsd
Name:           kube-dns-86f4d74b45-59dsd
Namespace:      kube-system
Node:           minikube/151.155.165.86
Start Time:     Thu, 13 Sep 2018 07:17:46 -0600
Labels:         k8s-app=kube-dns
                pod-template-hash=4290830601
Annotations:    <none>
Status:         Running
IP:             151.155.164.1
Controlled By:  ReplicaSet/kube-dns-86f4d74b45
Containers:
  kubedns:
    Container ID:  docker://ac24bf4be9448810813a18b2ab29a923256e2feb8f125da29d6f624e0fd1f647
    Image:         k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.8
    Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-kube-dns-amd64@sha256:6d8e0da4fb46e9ea2034a3f4cab0e095618a2ead78720c12e791342738e5f85d
    Ports:         10053/UDP, 10053/TCP, 10055/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      --domain=cluster.local.
      --dns-port=10053
      --config-dir=/kube-dns-config
      --v=2
    State:          Running
      Started:      Thu, 13 Sep 2018 07:54:02 -0600
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Thu, 13 Sep 2018 07:47:56 -0600
      Finished:     Thu, 13 Sep 2018 07:48:57 -0600
    Ready:          False
    Restart Count:  10
    Limits:
      memory:  170Mi
    Requests:
      cpu:      100m
      memory:   70Mi
    Liveness:   http-get http://:10054/healthcheck/kubedns delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:  http-get http://:8081/readiness delay=3s timeout=5s period=10s #success=1 #failure=3
    Environment:
      PROMETHEUS_PORT:  10055
    Mounts:
      /kube-dns-config from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-dhj49 (ro)
  dnsmasq:
    Container ID:  docker://6e1dc4daecb100210b37db61e0e4a3442baa5e83555782796f413c37463e36eb
    Image:         k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8
    Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64@sha256:93c827f018cf3322f1ff2aa80324a0306048b0a69bc274e423071fb0d2d29d8b
    Ports:         53/UDP, 53/TCP
    Host Ports:    0/UDP, 0/TCP
    Args:
      -v=2
      -logtostderr
      -configDir=/etc/k8s/dns/dnsmasq-nanny
      -restartDnsmasq=true
      --
      -k
      --cache-size=1000
      --no-negcache
      --log-facility=-
      --server=/cluster.local/127.0.0.1#10053
      --server=/in-addr.arpa/127.0.0.1#10053
      --server=/ip6.arpa/127.0.0.1#10053
    State:          Running
      Started:      Thu, 13 Sep 2018 07:52:24 -0600
    Last State:     Terminated
      Reason:       Error
      Exit Code:    137
      Started:      Thu, 13 Sep 2018 07:45:06 -0600
      Finished:     Thu, 13 Sep 2018 07:47:16 -0600
    Ready:          True
    Restart Count:  10
    Requests:
      cpu:        150m
      memory:     20Mi
    Liveness:     http-get http://:10054/healthcheck/dnsmasq delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /etc/k8s/dns/dnsmasq-nanny from kube-dns-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-dhj49 (ro)
  sidecar:
    Container ID:  docker://1743abc9591a01a566e96d154c088eb8b07b7541af15ecd9c4b17020438215e5
    Image:         k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.8
    Image ID:      docker-pullable://k8s.gcr.io/k8s-dns-sidecar-amd64@sha256:23df717980b4aa08d2da6c4cfa327f1b730d92ec9cf740959d2d5911830d82fb
    Port:          10054/TCP
    Host Port:     0/TCP
    Args:
      --v=2
      --logtostderr
      --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,SRV
      --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,SRV
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Thu, 13 Sep 2018 07:50:29 -0600
      Finished:     Thu, 13 Sep 2018 07:52:09 -0600
    Ready:          False
    Restart Count:  11
    Requests:
      cpu:        10m
      memory:     20Mi
    Liveness:     http-get http://:10054/metrics delay=60s timeout=5s period=10s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-dns-token-dhj49 (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  kube-dns-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-dns
    Optional:  true
  kube-dns-token-dhj49:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kube-dns-token-dhj49
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                 From               Message
  ----     ------                 ----                ----               -------
  Normal   Scheduled              36m                 default-scheduler  Successfully assigned kube-dns-86f4d74b45-59dsd to minikube
  Normal   SuccessfulMountVolume  36m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "kube-dns-config"
  Normal   SuccessfulMountVolume  36m                 kubelet, minikube  MountVolume.SetUp succeeded for volume "kube-dns-token-dhj49"
  Normal   Pulled                 36m                 kubelet, minikube  Container image "k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8" already present on machine
  Normal   Created                36m                 kubelet, minikube  Created container
  Normal   Started                36m                 kubelet, minikube  Started container
  Normal   Created                36m                 kubelet, minikube  Created container
  Normal   Pulled                 36m                 kubelet, minikube  Container image "k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.8" already present on machine
  Normal   Started                36m                 kubelet, minikube  Started container
  Normal   Started                35m (x2 over 36m)   kubelet, minikube  Started container
  Normal   Created                35m (x2 over 36m)   kubelet, minikube  Created container
  Warning  Unhealthy              35m (x2 over 35m)   kubelet, minikube  Liveness probe failed: Get http://x.x.x.x:10054/metrics: dial tcp x.x.x.x:10054: getsockopt: no route to host
  Warning  Unhealthy              35m (x2 over 35m)   kubelet, minikube  Liveness probe failed: Get http://x.x.x.x:10054/healthcheck/dnsmasq: dial tcp x.x.x.x:10054: getsockopt: no route to host
  Warning  BackOff                26m (x22 over 33m)  kubelet, minikube  Back-off restarting failed container
  Warning  Unhealthy              11m (x54 over 36m)  kubelet, minikube  Readiness probe failed: Get http://x.x.x.x:8081/readiness: dial tcp x.x.x.x:8081: getsockopt: no route to host
  Normal   Pulled                 6m (x10 over 36m)   kubelet, minikube  Container image "k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.8" already present on machine
  Warning  BackOff                1m (x86 over 27m)   kubelet, minikube  Back-off restarting failed container

**Anything else do we need to know**:
So I am just starting to learn about Kubernetes, Docker, minikube, etc. All I'm trying to do is go through the quickstart guide for minikube. I'm trying to run this on another computer I have through VM Ware esxi vm with Debian. I've been looking around online for an answer, but I can't seem to figure anything out. I've tried to set the iptables correctly. I've even tried getting rid of the iptables. I've tried setting the default bridge for docker as suggested. I'm using the lastest docker-ce, kubernetes, and minikube. I'm using the very base install of Debian (no GUI, only SSH server package installed). Is there some setting I'm supposed to do to get it running? Any help would be appreciated.

**Comment by tstromberg** [comment]
Do you mind mentioning your minikube start command line?

**Comment by rlords** [comment]
I ended up just switching linux distros and it is working fine now.
