### ISSUE TITLE
Error in driver during machine creation: getting ip during machine start: host is not running.

### ISSUE THREAD

**Issue by nitinmahawadiwar** [kubernetes/minikube#3137]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):v0.28.2

- **OS** (e.g. from /etc/os-release): CentOS7
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):"kvm2"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): 
 "Boot2DockerURL": "file:///root/.minikube/cache/iso/minikube-v0.28.1.iso",
        "ISO": "/root/.minikube/machines/minikube/boot2docker.iso",

- **Install tools**: minikube, kubectl
- **Others**: docker
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version :  v0.28.2
echo "";
echo "OS:";
cat /etc/os-release
echo "";
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
echo "VM driver": kvm2
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";kvm2
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
"Boot2DockerURL": "file:///root/.minikube/cache/iso/minikube-v0.28.1.iso",
        "ISO": "/root/.minikube/machines/minikube/boot2docker.iso",

```

**What happened**:
getting following error
minikube start --vm-driver kvm2
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 160.27 MB / 160.27 MB [============================================] 100.00% 0s
E0918 19:48:48.051664   18548 start.go:174] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: getting ip during machine start: host is not running.

 Retrying.
E0918 19:48:48.052528   18548 start.go:180] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: getting ip during machine start: host is not running
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================

**What you expected to happen**:
start successfully

**How to reproduce it** (as minimally and precisely as possible):
downloaded minikube, kvm2 drivers, ran "minikube start --vm-driver kvm2" command , and getting above error.
I have already tried "minikube delete", "rm -rf /root/.minikube" and "rm -rf /root/.kube" folders several times.
**Output of `minikube logs` (if applicable)**:
-none, please let me know how to retrieve these logs
**Anything else do we need to know**:
-none

**Comment by nitinmahawadiwar** [comment]
I had 3 VMs on which minikube v 28 was working smoothly, restarted all VMs and later the problem has started.

**Comment by spitfire88** [comment]
Is minikube-net running?
`virsh net-list` should list it as active. Make sure Autostart is enabled as well by running `virsh net-autostart minikube-net`.

**Comment by nitinmahawadiwar** [comment]
Thank you for your response.
Yes, minikube-net is running and showing active as well. Autostart is enabled.
after verification, I have again executed "minikube delete" and then rm -rf on root/.minikube & .kube folders.
I am getting same error.

# minikube start --vm-driver kvm2
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
E0919 12:11:51.006940    2434 start.go:159] Error starting host: Error starting stopped host: getting ip during machine start: host is not running.

 Retrying.
E0919 12:11:51.007883    2434 start.go:165] Error starting host:  Error starting stopped host: getting ip during machine start: host is not running
================================================================================

**Comment by nitinmahawadiwar** [comment]
I was testing it with older version, either 26 or 24, but installed latest version with
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.28.2/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/

also, the kvm2 driver was already upgraded using following link 
https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver

sudo yum install libvirt-daemon-kvm qemu-kvm
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * epel: mirrors.aliyun.com
Package libvirt-daemon-kvm-3.9.0-14.el7_5.7.x86_64 already installed and latest version
Package 10:qemu-kvm-1.5.3-156.el7_5.5.x86_64 already installed and latest version
Nothing to do

getting same error.

**Comment by tstromberg** [comment]
This sounds like a VM environment issue, but I'm not sure what it might be. Do you mind sharing the output of:

virsh list --all

Thanks!

**Comment by nitinmahawadiwar** [comment]
Thank you.
this is the output
virsh list --all
 Id    Name                           State
----------------------------------------------------
 9     vm01                           paused
 16    Nitin                          paused
 17    minikube                       paused
 -     vm02                           shut off
 -     vm03                           shut off
 -     vm031                          shut off

I may have to agree with you on your observation, i.e. VM environment issue. 
I tried to execute docker-machine create --driver kvm2 vmname and getting same error, 
"Error creating machine: Error in driver during machine creation: getting ip during machine start: host is not running"
Surprise is, this was working before, and all of a sudden it stopped working after VM reboot. 
Do you mind to guide me on any pointers on this,

**Comment by gbraad** [comment]
When you do not get an IP, it might b the default network is not available/enabled, or you are using a VPN for instance. Is this the case?


It is also not advised to interact with the minikube VM using docker machine. However, you can inspec with virt-manager what happens with the VM. Did it start, can you login from the console for instance?

**Comment by nitinmahawadiwar** [comment]
Thank you for your recommendation. 
default network is enabled, active. I am new to virt-manager will explore and try to debug with the VM.
thanks once again.

**Comment by nitinmahawadiwar** [comment]
I could not get the minikube started with kvm, so ultimately removed everything specific to KVM and now things are working with VirtualBox on same environment.

**Comment by dongwangdw** [comment]
The kvm2 still there. I think this is a bug. It should be fixed.
