### ISSUE TITLE
minikube should fail early if executed as root

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3138]
This is a bad practice, and could address some awkward connectivity and authentication issues, like #2548

**Comment by SimonBaeumer** [comment]
@tstromberg Hey Thomas! 
First of all thank you and the team for this great project!
I noticed that you added the `help wanted` image in the `README.md` and would like to start working on this issue, and hopefully some more :+1:

The implementation in my head would be to check if `minikube` was started as `root` and exit it with an error message.
And some questions:
 - Would it make sense to allow root execution if a flag is passed to `minikube`, i.e. `--root`?
 - Is preventing administrator execution on windows a thing?

**Comment by tstromberg** [comment]
@SimonBaeumer - I agree. It would be preferable to have an escape hatch, like --running-as-root-is-dangerous.

I'm not really worried about Windows in this case, it doesn't have the side effect of being very confusing about profile ownership.

We'll need to get #3760 resolved first.
