### ISSUE TITLE
Make minikube offline-friendly by default (needs testing)

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3144]
We get many bug reports where users have issues accessing the internet due to proxy issues. I'm trying to collect them here:

https://github.com/kubernetes/minikube/issues?utf8=%E2%9C%93&q=label%3Afailed%2Finternet-access

This somewhat goes along with #1623 - but requires making sure we test that minikube works offline.

**Comment by gbraad** [comment]
This might be a point of discussion for our next meeting; we also have a
topic to enable complete offline use. We have worked on integrating DNS
(first as dnsmasq, but will move to use coredns) from the host, cching
images, etc. It is off-topic to dfiscuss here, but networking (proxy,
offline use) is likely the biggest hurdle... and one of the shortcoming
with docker/machine (which they tried to fix with vpnkit)

**Comment by tstromberg** [comment]
Documented: https://github.com/kubernetes/minikube/blob/master/docs/offline.md
