### ISSUE TITLE
Document the cni and cri requirements (for "none")

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#3150]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

**Summary**

Document/verify the new requirements of kubeadm, that was added in Kubernetes v1.11.0:

* kubernetes-cni (>= 0.6.0)
* cri-tools (>=1.11.0)

These tools have already been added to the Minikube ISO (see 41fdd53e1add6dd0173223da838ed0bdcd799845 and fbd620a01032f747e05df1c63a88ab900e7b7596)

**Related**

kubernetes/release#573 rpm/deb
kubernetes/minikube#3132 k8s v1.11.0

**Comment by afbjorklund** [comment]
Note that versions < 1.11 were happy with just Docker, so this requirement should be versioned.

**Comment by bhack** [comment]
https://github.com/kubernetes/kubernetes/pull/64611

**Comment by afbjorklund** [comment]
CRI is now mentioned on the [install page](https://kubernetes.io/docs/setup/independent/install-kubeadm/) (but not CNI just yet), but the link seems to be broken:

https://kubernetes.io/docs/setup/cri.md

Should probably have been something like: (as mentioned, it is already included in the packages)

https://kubernetes.io/docs/tasks/debug-application-cluster/crictl/#installing-crictl

**Comment by afbjorklund** [comment]
Slightly modified version of the kubeadm Container Linux instructions should probably work:

```
CNI_VERSION="v0.6.0"
mkdir -p /opt/cni/bin
curl -L "https://github.com/containernetworking/plugins/releases/download/${CNI_VERSION}/cni-plugins-amd64-${CNI_VERSION}.tgz" | tar -C /opt/cni/bin -xz
```

```
CRICTL_VERSION="v1.11.1"
mkdir -p /usr/local/bin
curl -L "https://github.com/kubernetes-incubator/cri-tools/releases/download/${CRICTL_VERSION}/crictl-${CRICTL_VERSION}-linux-amd64.tar.gz" | tar -C /usr/local/bin -xz
```

**Comment by afbjorklund** [comment]
The link above was supposed to be: https://kubernetes.io/docs/setup/cri/

**Comment by afbjorklund** [comment]
Apparently (v1.12.0-alpha.0-2228-g95eb821) this requirement has been lifted, not required for docker.
It is still required when using another container runtime though, but the "preflight" will check for it...

We already have an option for the CNI configuration, and there is no mandatory check for it either.
So closing this issue, can still add more documentation and more checks if the need for them arise.
