### ISSUE TITLE
Add runtime-config setting to minucube start

### ISSUE THREAD

**Issue by slaskawi** [kubernetes/minikube#316]
Hi!

I would like to test new alpha APIs and in order to do that I need to specify additional `--runtime-config` parameters (e.g. `api/all`). Currently I'm not able to do that.

Probably the best option would be to add it to `minucube start` command.

Thanks
Sebastian

**Comment by dlorenc** [comment]
@MHBauer this one could be a good feature to get started with. Let me know if you're interested.

**Comment by dlorenc** [comment]
I think this is obsolete now, we solved it by just always enabling all APIs :). Let me know if there is anything else you'd like to pass in runtime-config.

**Comment by anukul** [comment]
From the 1.16 [changelog](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md#deprecations-and-removals):
>- API
> 
>   - The following APIs are no longer served by default:
> 
>     - All resources under `apps/v1beta1` and `apps/v1beta2` - use `apps/v1` instead
>     - `daemonsets`, `deployments`, `replicasets` resources under `extensions/v1beta1` - use `apps/v1` instead
>     - `networkpolicies` resources under `extensions/v1beta1` - use `networking.k8s.io/v1` instead
>     - `podsecuritypolicies` resources under `extensions/v1beta1` - use `policy/v1beta1` instead
> 
>     Serving these resources can be temporarily re-enabled using the `--runtime-config` apiserver flag.
> 
>     - `apps/v1beta1=true`
>     - `apps/v1beta2=true`
>     - `extensions/v1beta1/daemonsets=true,extensions/v1beta1/deployments=true,extensions/v1beta1/replicasets=true,extensions/v1beta1/networkpolicies=true,extensions/v1beta1/podsecuritypolicies=true`
>
