### ISSUE TITLE
minikube_0.28-2.deb installs minikube v0.28.0

### ISSUE THREAD

**Issue by massenz** [kubernetes/minikube#3165]
**BUG REPORT**

Please provide the following details:

**Environment**:

- **Minikube version**: 0.28.2
- **OS** (e.g. from /etc/os-release): Ubuntu 18.04.1 LTS
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- **VM Driver**: Virtualbox
- **ISO version**: "file:///home/marco/.minikube/cache/iso/minikube-v0.28.0.iso",
- **Install tools**: sudo dpkg -i minikube_0.28-2.deb

**What happened**:
Nothing much:
```
$ sudo dpkg -i minikube_0.28-2.deb
(Reading database ... 602388 files and directories currently installed.)
Preparing to unpack minikube_0.28-2.deb ...
Unpacking minikube (0.28-2) over (0.28-2) ...
Setting up minikube (0.28-2) ...

$ minikube version                
minikube version: v0.28.0
```

**What you expected to happen**: minikube version to be 0.28.2

**How to reproduce it** (as minimally and precisely as possible): see above.

**Anything else do we need to know**:
I had stopped (but not deleted) the VM (but I'm hoping this should have nothing to do with the binary version?)

**Comment by tstromberg** [comment]
Just to make sure, can you run this?

```shell
whereis minikube
```

and:

```shell
stat /usr/bin/minikube
```

The .deb installs minikube into /usr/bin/minikube, which for me shows:

```shell
$ /usr/bin/minikube version
minikube version: v0.28.2
```

**Comment by massenz** [comment]
Ah - ok that explains it: has the location changed since 0.28.0?
In my system, it was on `/usr/local/bin/minikube` which comes in my `$PATH` before `/usr/bin`

I cannot remember whether I installed via the `deb` or manually copied the binary, but of course, removing the `/usr/loca/bin` one fixes the issue.

Thanks!
