### ISSUE TITLE
Allow set `ImageRepository` for kubeadm init

### ISSUE THREAD

**Issue by bcho** [kubernetes/minikube#3166]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Please provide the following details:

**Environment**:

```
minikube version: v0.28.2

OS:
cat: /etc/os-release: No such file or directory

VM driver:
    "DriverName": "hyperkit",

ISO version
        "Boot2DockerURL": "file:///path/to/.minikube/cache/iso/minikube-v0.28.1.iso",
```

Can the kubeadm bootstrapper adds a configuration option support for [`ImageRepository`][kubeadmin_init], which enables setting different image base repository. This feature will help developers who are having difficulties to connect to k8s.gcr.io (namely, China), as long as they can set the repository prefix to self managed proxies.

[kubeadmin_init]: https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/#custom-images

**Comment by dlorenc** [comment]
cc @tstromberg
