### ISSUE TITLE
DNS service resolution does not work when resolving ones own pod

### ISSUE THREAD

**Issue by bdirito** [kubernetes/minikube#3170]
Bug

Please provide the following details:

**Environment**:

```
minikube version: v0.28.2

OS:
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

VM driver:
    "DriverName": "virtualbox",

ISO version
        "Boot2DockerURL": "file:///home/bdirito/.minikube/cache/iso/minikube-v0.28.1.iso",

```

**What happened**:
Services have a dns entry exposed for use within the cluster, both `<service_name>` for use inside the namespace and `<service_name>.<namespace>.svc.cluster.local` for use anywhere.

Actions from within the pod that this service points to will timeout if they try to use either of these two dns entries.

Other pods work as expected.
**What you expected to happen**:
Dns resolutions should work from any pod
**How to reproduce it** (as minimally and precisely as possible):
```
kubectl run --port 80 --image nginx nginx
kubectl expose deploy nginx
kubectl exec -it `kubectl get po | grep nginx | awk '{print $1}'` bash
apt-get update && apt-get install curl
curl localhost # asserting that curl / nginx works
curl nginx # < failure here
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
Failure also happens with the `nginx.<namespace>.svc.cluster.local` dns style.
The same reproduction works if run in amazon eks.

**Comment by tstromberg** [comment]
This now appears to be fixed DNS:

```
root@nginx-57867cc648-tqgbj:/# nslookup nginx
Server:		10.96.0.10
Address:	10.96.0.10#53

Name:	nginx.default.svc.cluster.local
Address: 10.101.235.156
```

However, this IP is not routable from inside the nginx pod:

```
/# ping nginx
PING nginx.default.svc.cluster.local (10.101.235.156) 56(84) bytes of data.
^C
--- nginx.default.svc.cluster.local ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1021ms
```

**Comment by tstromberg** [comment]
FYI - I believe the routing issue is covered by #2460
