### ISSUE TITLE
qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory'

### ISSUE THREAD

**Issue by Hitvz** [kubernetes/minikube#3173]
BUG REPORT :
the info is：
`E0927 06:33:12.927784   49777 start.go:165] Error starting host:  Error starting stopped host: Error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2018-09-27T06:33:12.689642Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory') `

**Environment**:

minikube version: v0.25.2
os:ubuntu 18.04 -- in the vmware and memory 752mb

i search this issues , answer is memory too low . i not get the information with kvm memory need in the offical website . so how many memory kvm need to start minikube?

**Comment by tstromberg** [comment]
2GB by default. You can adjust this setting using `--memory` down to 1.5GB, but failures might happen:

```shell
minikube help start | grep memory
      --memory int                     Amount of RAM allocated to the minikube VM in MB (default 2048)
```

Just curious, what's does this command output on your machine?

```shell
grep "^Mem" /proc/meminfo
```

**Comment by afbjorklund** [comment]
@tstromberg : note that the default is 2G memory + 1G swap (some of which is actually being used!)

**Comment by Hitvz** [comment]
thx，i will up to memory in vmware.
