### ISSUE TITLE
Remove references to "get-k8s-versions" in minikube documentation

### ISSUE THREAD

**Issue by javajon** [kubernetes/minikube#3179]
**BUG REPORT**:

Please provide the following details:

**Environment**:
Windows 10

**Minikube version** : v0.29.0
- **OS**: Windows 10
- **VM Driver** cat ~/.minikube/machines/minikube-jenkins/config.json | grep DriverName
    "DriverName": "virtualbox

**What happened**:

```
minikube get-k8s-versions
Error: unknown command "get-k8s-versions" for "minikube"
Run 'minikube --help' for usage.
```

**What you expected to happen**:

Show list of versions like in previous versions.  I did not see a ticket to remove it and it's still [documented here](https://kubernetes.io/docs/setup/minikube/#specifying-the-kubernetes-version)

**How to reproduce it** (as minimally and precisely as possible):

```
minikube get-k8s-versions
```

Install Windows exe from 0.29.0 release

**Comment by javajon** [comment]
Suspect it no longer works because "localkube bootstrapper" was removed.  However, the documentation lacks that information and people reading this or have existing instructions, scripts tutorials with calls to this will have questions. Perhaps the fix is just a documentation change.  Release notes said localkube was removed but did not note this other downstream consequence.

#2156

**Comment by tstromberg** [comment]
Also sent out an update to the k8s website:

https://github.com/kubernetes/website/pull/10423

Thank you Jonathan for bringing this to our attention!

**Comment by afbjorklund** [comment]
Maybe you should consider a new version, that lists the kubernetes (`kubeadm`) versions ?
