### ISSUE TITLE
minikube start should check disk space

### ISSUE THREAD

**Issue by phillipp** [kubernetes/minikube#318]
I just discovered minikube and thought I give kubernetes a spin. After spending two hours collecting all the (undocumented) required ubuntu packages I discovered that `kubectl start` fills my disk (5.6 GB remaining). I wonder 

a) if this is expected
b) why it is not documented and/or checked before starting the setup?

I don't think you can expect that everybody has lots of free disk space on dev machines...?

Besides: how much is required? I would have to resize partitions and I don't want to do it twenty times just to try minikube/kubernetes...

**Comment by dlorenc** [comment]
Hey, we currently create a 20gb disk for minikube to run in. In the next release we'll have a flag to control the size of this disk. I think whether this disk actually allocates all 20gb at start is driver-specific.

We should document this and check it before attempting to create the disk.

**Comment by jimmidyson** [comment]
AFAIK most virt providers will create a sparse disk image so should only use space that is actually written in the VM. That reduces the actual disk space used but can grow up to the specified disk size, defaults to 20GB but overrideable in latest release.

The largest amount of disk space in minikube will likely be docker images & there isn't anything we can do about that.

Agree we should check disk space, which means we need to check the partition/disk where the VM disk image will be created. Not sure if that is that driver dependent, but assume it could be. We can warn the user if disk space is looking like it's not enough.

**Comment by tristanz** [comment]
Is there a known workaround for the 20GB limit?  This make it hard to develop stacks with large images.

**Comment by jimmidyson** [comment]
You can configure disk size on start - check out `minikube start --help` for the appropriate flag.

**Comment by aaron-prindle** [comment]
Closing, we support the `minikube start --disk-size` flag which can configure the disk size of the minikube VM on start
