### ISSUE TITLE
minikube looks for minikube.iso in wrong path

### ISSUE THREAD

**Issue by netcho** [kubernetes/minikube#3181]
**BUG REPORT**

When trying to create a new cluster on Windows minikube looks for minikube.iso in the following path:

/Users/kaloyan/.minikube/cache/iso/minikube-v0.29.0.iso

Please provide the following details:

**Environment**: Windows 10 x64 build 17134

**Minikube version**: v0.29.0
- **OS** :
- **VM Driver**: hyperv
- **ISO version**: minikube-v0.29.0.iso

**What happened**:

The installation failed with the following error message: 

Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E0928 10:04:52.786004    3832 start.go:168] Error starting host: Error creating host: Error executing step: Creating VM.
: open /Users/kaloyan/.minikube/cache/iso/minikube-v0.29.0.iso: The system cannot find the path specified..

 Retrying.
E0928 10:04:52.788014    3832 start.go:174] Error starting host:  Error creating host: Error executing step: Creating VM.
: open /Users/kaloyan/.minikube/cache/iso/minikube-v0.29.0.iso: The system cannot find the path specified.
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: n

**What you expected to happen**:

I expected the cluster to start

**How to reproduce it**:

1. Delete .minikube directory
2. Download the latest release for windows x64
3. Issue the command: minikube start --vm-driver hyperv --hyperv-virtual-switch "Default Switch" --memory 4096 --disk-size 8g

**Anything else do we need to know**:
The file path which describes where the iso is located seems to me malformed. Here is a link to the config.json generated by the start command: [https://pastebin.com/kieSXePU](https://pastebin.com/kieSXePU)

**Comment by tstromberg** [comment]
Maybe I'm missing something, but I don't see the malformed path, unless you count the usage of / instead of \. I'll see if I can replicate this. 

In the mean time, can you attach the output of "minikube logs"?

**Comment by davidovich** [comment]
I have experimented this, and there is a workaround: change the working dir to be the on same drive as the %USERPROFILE% (or %HOME% if you have that).

@tstromberg on Windows, the path is preceded by a drive letter, `C:\`, `D:\`. It is not present in this issue and that is why there is a problem. The problem is somewhere in the hyperv driver from docker/machine.

I think there is a duplicate issue here somewhere.

**Comment by netcho** [comment]
Result from minikube logs:

F0929 02:03:22.799202   10056 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error creating new ssh host from driver: Error getting ssh host
name for driver: Host is not running

**Comment by afbjorklund** [comment]
Probably the same issue as #1574

**Comment by tstromberg** [comment]
Dupe of #1574
