### ISSUE TITLE
GPU passthrough with optimus

### ISSUE THREAD

**Issue by bhack** [kubernetes/minikube#3193]
I want to collect here any effort to use GPU passthrough with optimus on Minikube.
This probably could be useful on laptop for alternate docker host and minikube GPU use without be constrained to change the drivers and reboot or to use the GPU in Minikube only with `vm-driver=none`.

Some info related to optimus passthrough:
https://gist.github.com/Misairu-G/616f7b2756c488148b7309addc940b28

**Comment by tstromberg** [comment]
There doesn't seem to be much activity here - let's move any optimus related hints to documentation.
