### ISSUE TITLE
minikube dashboard host checking

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3208]

**Comment by fbdabhishek** [comment]
minikube is not running in production for any one and its only for learning and prototyping, who is going to do DNS attacks if its not on a public domain.

**Comment by serain** [comment]
@bhishekarora you would target developers using minikube, and from there pwn the things the developers have access to.

1. phish employees who you know are likely to be using minikube locally. just get them to click a link.
2. run a waterhole on a website you control (i.e. "Getting started with Kubernetes using Minikube" or "Explore the latest Kubernetes features with Minikube")

one thing to note is that this issue allowed trivial VM escape, so you would gain full access to the host OS (and developer passwords, private keys etc.)

full disclosure: I'm the nerd who reported this issue
