### ISSUE TITLE
Propagate HTTP proxy config into VM

### ISSUE THREAD

**Issue by cvila84** [kubernetes/minikube#3242]
**BUG REPORT**

**Minikube version** (use `minikube version`): v0.30.0
- **OS** (e.g. from /etc/os-release): Windows
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.30.0

**What happened**:
`minikube start --kubernetes-version v1.10.8 --docker-env HTTP_PROXY=xxx --docker-env HTTPS_PROXY=xxx --docker-env NO_PROXY=xxx` is failing in timeout during kubeadm command execution

```
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

.: Process exited with status 1
```
**What you expected to happen**:
minikube starts normally

**Anything else do we need to know**:
The faulty command is `kubeadm alpha phase addon kube-dns`. I replayed it inside the minikube VM to have more logs : 
```
$ sudo kubeadm alpha phase addon kube-dns
unable to get URL "https://dl.k8s.io/release/stable-1.10.txt": Get https://dl.k8s.io/release/stable-1.10.txt: dial tcp 23.236.58.218:443: getsockopt: connection timed out
```
kubeadm is trying to download a file (that actually contains the exact version of kubernetes) but since HTTP proxy settings are not set in VM (they are only set for docker engine through `--docker-env` parameters), this is failing. I found that if you add `--kubernetes-version`, no download is done and the command succeeds:
```
$ sudo kubeadm alpha phase addon kube-dns --kubernetes-version v1.10.8
[addons] Applied essential addon: kube-dns
```
So a fix could be to propagate the `--kubernetes-version` passed to `minikube start` to `kubeadm alpha phase addon kube-dns` command.

**Comment by ldcastell** [comment]
This issue is really annoying, will be awesome to see the fix go through :)

**Comment by tstromberg** [comment]
@llsousa - That sounds reasonable. As a further iteration, it would be nice if we supported detecting the proxy from the environment, and automatically configured minikube appropriately.

"minikube start" should just work in every environment possible. If failing that, it should inform the user on the appropriate action necessary to fix the issue.

**Comment by AdamKong** [comment]
See this is the same issue? this is on win10, with virtualbox Ubuntu OS.

C:\Windows\system32>minikube start
o   minikube v0.34.0 on windows (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.99.130
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
@   Downloading kubelet v1.13.3
@   Downloading kubeadm v1.13.3
!   Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.13.3: failed to download: failed to download to temp file: failed to create validator: failed to create validator: failed to download checksum file: Get https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubeadm.sha1: read tcp 192.168.1.107:52462->216.58.200.48:443: wsarecv: An existing connection was forcibly closed by the remote host.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

Anyone can offer me a temp solution? Thanks much!

**Comment by tstromberg** [comment]
@AdamKong - Your issue seems different, as the error is from outside of the VM environment. I'm pretty sure you just need to tell minikube about your proxy: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

**Comment by tstromberg** [comment]
I haven't heard any more user complaints on this, so I think we've done a good enough job on this. Closing until someone opens something more specific.
