### ISSUE TITLE
none: minikube dashboard --url outputs nothing (v0.28.2)

### ISSUE THREAD

**Issue by ghost** [kubernetes/minikube#3246]
**Environment**:
minikube version: v0.28.2
OS:
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

**What happened**:
I used the command "minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0 \
    --extra-config=controller-manager.cluster-signing-cert-file="/var/lib/localkube/certs/ca.crt" \
    --extra-config=controller-manager.cluster-signing-key-file="/var/lib/localkube/certs/ca.key" \
    --vm-driver=none" and "minikube start --vm-driver=none" to install minikube !
minikube was installed OK ! but didn't install related pods of the addons-manager and the dashboard  !  then i followed some guild at the kubernets official website ! input command " kubectl create -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/recommended/kubernetes-dashboard.yaml" to deploy dashboard for minikube ! and then the dashboard was deployed well !but i input command "minikube dashboard --url" to check dashboard url !but still output nothing !
The following screenshot was detailed pods install status of the  kube-system namespace !
root@seliius07751:/etc/kubernetes# kubectl get pods -n kube-system 
NAME                                    READY     STATUS    RESTARTS   AGE
etcd-minikube                           1/1       Running   0          7m
kube-apiserver-minikube                 1/1       Running   0          8m
kube-controller-manager-minikube        1/1       Running   0          8m
kube-dns-86f4d74b45-bhtzl               3/3       Running   0          8m
kube-proxy-dpf4p                        1/1       Running   0          8m
kube-scheduler-minikube                 1/1       Running   2          7m
kubernetes-dashboard-7b9c7bc8c9-9rklg   1/1       Running   0          10s
tiller-deploy-664858687b-xtg6p          1/1       Running   0          8m

**What you expected to happen**:
Maybe two weeks ago ! I use above commands to install minikube ! and the dashboard always was deployed by default !
**How to reproduce it** (as minimally and precisely as possible):
1. stop and delete pre-installed minikube 
minikube stop;minikube delete 
2. delete some file about minikube 
rm -rf /home/.mikube /home/.kube
rm -rf /etc/kubernetes/
3. reinstall minikube 
minikube start --vm-driver=none or 
minikube start --memory=8192 --cpus=4 --kubernetes-version=v1.10.0 \
    --extra-config=controller-manager.cluster-signing-cert-file="/var/lib/localkube/certs/ca.crt" \
    --extra-config=controller-manager.cluster-signing-key-file="/var/lib/localkube/certs/ca.key" \
    --vm-driver=none" and "minikube start --vm-driver=none

**Comment by tstromberg** [comment]
What does `kubectl version` output on your machine?

I ask because I noticed that kubectl with a very old (July 2017) had an issue with showing the URL for the new dashboard setup.

**Comment by shenjieyao** [comment]
I think maybe my kubectl version not very old ! The following content is my kubectl version detailed message ! 

Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.3", GitCommit:"a4529464e4629c21224b3d52edfe0ea91b072862", GitTreeState:"clean", BuildDate:"2018-09-09T18:02:47Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tstromberg** [comment]
I'm curious if this is still seen with minikube v0.30.0 - we changed the way the dashboard is accessed, by plumbing it through kubectl proxy.

**Comment by shenjieyao** [comment]
i don't know why that time dashboard didn't automatic deployment !  but after i made some times to clear minikube configuration and images ! then dashboard can be automatic installed !  so you can close this issue !
