### ISSUE TITLE
docker-env support for Windows paths in WSL shell

### ISSUE THREAD

**Issue by cryptable** [kubernetes/minikube#3248]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): FEATURE REQUEST

Please provide the following details:

**Environment**: Windows 10 with Windows Subsystem for Linux (Ubuntu 16.04.4 LTS)

**Minikube version** (use `minikube version`): v0.30.0
- **OS** (e.g. from /etc/os-release): Windows 10 with Windows Subsystem for Linux (Ubuntu 16.04.4 LTS)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.30.0
- **Install tools**: Chocolatey
- **Others**:

**What happened**:

```
>minikube docker-env --shell bash
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.2.42:2376"
export DOCKER_CERT_PATH=**"C:\Users\goobligoog\.minikube\certs"**
export DOCKER_API_VERSION="1.35"
# Run this command to configure your shell:
# eval $(minikube docker-env)
```

**What you expected to happen**:

```
>minikube docker-env --shell bash
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.2.42:2376"
export DOCKER_CERT_PATH=**"/mnt/c/Users/goobligoog/.minikube/certs"**
export DOCKER_API_VERSION="1.35"
# Run this command to configure your shell:
# eval $(minikube docker-env)
```

**How to reproduce it** (as minimally and precisely as possible):
see above

**Output of `minikube logs` (if applicable)**:
Not applicable

**Anything else do we need to know**:
Would be nice to have a command as follows:

```
>minikube docker-env --shell wsl
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://192.168.2.42:2376"
export DOCKER_CERT_PATH=**"/mnt/c/Users/goobligoog/.minikube/certs"**
export DOCKER_API_VERSION="1.35"
# Run this command to configure your shell:
# eval $(minikube docker-env --shell wsl)
```

Just and idea! So you can reuse your Linux development on Windows 10 with WSL and reuse it as a command:
```
eval $(minikube docker-env --shell wsl)
```

Maybe you can detect if your under WSL on Windows 10

**Comment by tstromberg** [comment]
PR's welcome!

**Comment by medyagh** [comment]
@cryptable  have you tried with latest version of minikube I believe it must have been fixed by the PR that added WSL support

https://github.com/kubernetes/minikube/issues/5392

**Comment by medyagh** [comment]
since latest version of minikube we disallow running the .exe binary in WSL, inside WLS plz use the Linux Binary
