### ISSUE TITLE
none: why does minikube start overwrite kubeadm and kubectl?

### ISSUE THREAD

**Issue by davidrusling** [kubernetes/minikube#3249]
minikube version: v0.30.0
avid@sleeper:~$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux buster/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

As per the title, I installed kubeadm, kubectl and kubetel.  I built minikube from scratch (via a git clone) but when I run it it overwrites these utilities.  I can trawl through the sources, but the versions of kubectl etc that are being built when I build minikube are arm64 executables, so I'm unsure what's happening.  However, I have verified that 'minikube start' overwrites the installed utilities.

Any help would be useful

Kind regards, David

**Comment by afbjorklund** [comment]
Same as #3228 (although the wrong architecture seems like a problem with your build environment)

**Comment by tstromberg** [comment]
Are you using --vm-driver=none? If so, this is a documented behavior: https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

The behavior of #3228 would be nice.

**Comment by tstromberg** [comment]
The answer here is basically that Kubernetes requires matching versions of kubeadm and kubectl to start appropriately.

I'm not opposed to a PR that changes the binary locations were somewhere else, like /usr/local/minikube/xxx.
