### ISSUE TITLE
Pods hanging on ContainerCreating with ImagePullSecrets based auth

### ISSUE THREAD

**Issue by hironroy** [kubernetes/minikube#325]
When creating pods that are based off images housed in my Google Container Registry (having authenciated via an ImagePullSecret) -- the pod creation hangs on `ContainerCreating`. This happens uniformly with any image I try to use from the private image registry.

**kubectl describe pods nimbus**
`Name:		nimbus
Namespace:	default
Node:		minikubevm/10.0.2.15
Start Time:	Tue, 12 Jul 2016 19:57:34 -0400
Labels:		app=nimbus
Status:		Pending
IP:		
Controllers:	<none>
Containers:
  nimbus:
    Container ID:	
    Image:		us.gcr.io/test-crawl-1344/storm-nimbus
    Image ID:		
    Port:		6627/TCP
    QoS Tier:
      cpu:		BestEffort
      memory:		BestEffort
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Environment Variables:
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-mhdag:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-mhdag
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  3m		3m		1	{default-scheduler }			Normal		Scheduled	Successfully assigned nimbus to minikubevm
  3m		3m		1	{kubelet minikubevm}	spec.containers{nimbus}	Normal		Pulling		pulling image "us.gcr.io/test-crawl-1344/storm-nimbus"
`

**From `> minikube logs`**
`E0712 23:57:34.995364    1607 runtime.go:58] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:52
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:40
/usr/local/go/src/runtime/asm_amd64.s:472
/usr/local/go/src/runtime/panic.go:443
/usr/local/go/src/runtime/panic.go:62
/usr/local/go/src/runtime/sigpanic_unix.go:24
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/github.com/docker/engine-api/client/image_pull.go:36
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/kube_docker_client.go:316
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/instrumented_docker.go:131
<autogenerated>:42
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/docker.go:214
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/docker.go:228
<autogenerated>:29
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/dockertools/docker_manager.go:853
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/container/serialized_image_puller.go:139
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/container/serialized_image_puller.go:63
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:86
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:87
/usr/local/google/home/dlorenc/go/src/k8s.io/minikube/_gopath/src/k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:49
/usr/local/go/src/runtime/asm_amd64.s:1998
`

**Comment by dlorenc** [comment]
Hey,

I don't think ImagePullSecrets work with gcr.io. How did you create the secret?

**Comment by hironroy** [comment]
I tried both the direct base-64 encoding a docker conf and declaring a secret & also using `kubectl create secret docker-registry`. Both approaches resulted in eliminating the 403 errors and associated `PullImageErrors` that occur in the absence of authentication:

http://stackoverflow.com/questions/36283660/creating-image-pull-secret-for-google-container-registry-that-doesnt-expire

**Comment by dlorenc** [comment]
Ah, thanks for the pointer. I didn't know it was possible to configure long-lived GCR auth that way. I'll give it a try, from the stacktrace it looks like a bug in docker/engine-api that's since been fixed. But we're using the same version of that library as core k8s, so I'm not sure why we'd be hitting this if standard kubernetes 1.3 isn't (maybe it is, I'll try to repro there as well).

**Comment by hironroy** [comment]
Ok, thanks for your help! Let me know if there's any other information that could help you.

Just FYI for anyone else who's encountering this issue -- directly configuring the docker instance in the VM/node by copying over a valid `~/dockercfg.json` or `~/.docker/config.json` (as detailed here: http://kubernetes.io/docs/user-guide/images/#configuring-nodes-to-authenticate-to-a-private-repository) works as expected.

**Comment by dlorenc** [comment]
Hey, I haven't been able to get the service account method to work in GKE or minikube yet. Have you gotten it to work in another cluster?

**Comment by hironroy** [comment]
I haven't. I'm just running minikube and GKE, so the minikube is the only place I've tried the `imagePullSecret` approach.

**Comment by dlorenc** [comment]
Hey, I just gave the steps in https://github.com/kubernetes/minikube/issues/321 a try and everything seems to work. Could you give this a try with those steps and reopen if it still fails?
