### ISSUE TITLE
Running minikube in an offline environment 

### ISSUE THREAD

**Issue by aashish-sheshadri** [kubernetes/minikube#3251]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):0.25.2
- **OS** (e.g. from /etc/os-release):RHEL 7
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):VBox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):0.25.1
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver:"; 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
Running minikube offline continues to pull images. 
**What you expected to happen**:
Be able to run minikube offline.
**How to reproduce it** (as minimally and precisely as possible):
Load docker images/update the cache folder with necessary images and run offline. 
Cache was copied from an online system to an offline system.
**Output of `minikube logs` (if applicable)**:
Oct 13 19:09:37 minikube localkube[3219]: E1013 19:09:37.692803    3219 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.0.2.3:53: server misbehaving
Oct 13 19:09:37 minikube localkube[3219]: E1013 19:09:37.692996    3219 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.0.2.3:53: server misbehaving
Oct 13 19:09:37 minikube localkube[3219]: E1013 19:09:37.693114    3219 kuberuntime_manager.go:647] createPodSandbox for pod "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.0.2.3:53: server misbehaving
Oct 13 19:09:37 minikube localkube[3219]: E1013 19:09:37.693371    3219 pod_workers.go:186] Error syncing pod c4c3188325a93a2d7fb1714e1abf1259 ("kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)"), skipping: failed to "CreatePodSandbox" for "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)\" failed: rpc error: code = Unknown desc = failed pulling image \"gcr.io/google_containers/pause-amd64:3.0\": Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.0.2.3:53: server misbehaving"
Oct 13 19:09:57 minikube localkube[3219]: E1013 19:09:57.525257    3219 healthcheck.go:317] Failed to start node healthz on 0: listen tcp: address 0: missing port in address
Oct 13 19:10:04 minikube localkube[3219]: I1013 19:10:04.654409    3219 controller.go:538] quota admission added evaluator for: {extensions deployments}
Oct 13 19:10:04 minikube localkube[3219]: I1013 19:10:04.658444    3219 controller.go:538] quota admission added evaluator for: {extensions replicasets}
Oct 13 19:10:04 minikube localkube[3219]: I1013 19:10:04.660367    3219 event.go:218] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"eg3", UID:"976fa4b5-cf1b-11e8-a2aa-080027f42608", APIVersion:"extensions", ResourceVersion:"422", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set eg3-8584c8cbfd to 1
Oct 13 19:10:04 minikube localkube[3219]: I1013 19:10:04.667972    3219 event.go:218] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"eg3-8584c8cbfd", UID:"9770407f-cf1b-11e8-a2aa-080027f42608", APIVersion:"extensions", ResourceVersion:"423", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: eg3-8584c8cbfd-ljsd9
Oct 13 19:10:04 minikube localkube[3219]: I1013 19:10:04.797119    3219 reconciler.go:217] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-xnvwr" (UniqueName: "kubernetes.io/secret/97712577-cf1b-11e8-a2aa-080027f42608-default-token-xnvwr") pod "eg3-8584c8cbfd-ljsd9" (UID: "97712577-cf1b-11e8-a2aa-080027f42608")
Oct 13 19:10:13 minikube localkube[3219]: E1013 19:10:13.795152    3219 remote_runtime.go:92] RunPodSandbox from runtime service failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.0.2.3:53: read udp 10.0.2.15:46807->10.0.2.3:53: i/o timeout
Oct 13 19:10:13 minikube localkube[3219]: E1013 19:10:13.795198    3219 kuberuntime_sandbox.go:54] CreatePodSandbox for pod "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.0.2.3:53: read udp 10.0.2.15:46807->10.0.2.3:53: i/o timeout
Oct 13 19:10:13 minikube localkube[3219]: E1013 19:10:13.795210    3219 kuberuntime_manager.go:647] createPodSandbox for pod "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" failed: rpc error: code = Unknown desc = failed pulling image "gcr.io/google_containers/pause-amd64:3.0": Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.0.2.3:53: read udp 10.0.2.15:46807->10.0.2.3:53: i/o timeout
Oct 13 19:10:13 minikube localkube[3219]: E1013 19:10:13.795246    3219 pod_workers.go:186] Error syncing pod c4c3188325a93a2d7fb1714e1abf1259 ("kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)"), skipping: failed to "CreatePodSandbox" for "kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)" with CreatePodSandboxError: "CreatePodSandbox for pod \"kube-addon-manager-minikube_kube-system(c4c3188325a93a2d7fb1714e1abf1259)\" failed: rpc error: code = Unknown desc = failed pulling image \"gcr.io/google_containers/pause-amd64:3.0\": Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 10.0.2.3:53: read udp 10.0.2.15:46807->10.0.2.3:53: i/o timeout"

**Anything else do we need to know**:
> minikube ssh "docker images"
REPOSITORY                                    TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kubernetes-dashboard-amd64         v1.8.1              e94d2f21bc0c        10 months ago       121MB
gcr.io/google-containers/kube-addon-manager   v6.5                d166ffa9201a        11 months ago       79.5MB
gcr.io/k8s-minikube/storage-provisioner       v1.8.0              4689081edb10        11 months ago       80.8MB
k8s.gcr.io/k8s-dns-sidecar-amd64              1.14.5              fed89e8b4248        12 months ago       41.8MB
k8s.gcr.io/k8s-dns-kube-dns-amd64             1.14.5              512cd7425a73        12 months ago       49.4MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64        1.14.5              459944ce8cc4        12 months ago       41.4MB
k8s.gcr.io/pause-amd64                        3.0                 99e59f495ffa        2 years ago         747kB

**Comment by afbjorklund** [comment]
Similar to #3144

**Comment by aashish-sheshadri** [comment]
I figured it out. I did not realize it was looking for the pause-amd64 image under gcr.io/google-containers/ as well. 

I loaded this image and now the set up works fine offline.

**Comment by bwplotka** [comment]
Hi all! Is there any way to delete the VM and run `minikube start` in offline mode, once you did minikube start --cached-image from same machine previously? 

My use case is to recreate whole minikube frequently in offline mode (demo purposes). If  the only thing, are docker images, then it is doable by caching images on host docker registry right (host to minikube VM)? Anyone tried something like this? Would that be difficult to achieve? (:
