### ISSUE TITLE
Run minikube e2e tests on Prow

### ISSUE THREAD

**Issue by donmccasland** [kubernetes/minikube#3256]
FEATURE REQUEST

Description:
Currently e2e platform tests are run by a jenkins host sitting under a coworker's desk here in SF.  We are working on changes that will allow us to run those same tests in Prow and report results into TestGrid.  This Issue is the placeholder for the work on that effort.

**Comment by tstromberg** [comment]
I understand there hasn't been much time to work on this. Any updates to share?

**Comment by tstromberg** [comment]
Closing as infeasible.
