### ISSUE TITLE
CHANGE_MINIKUBE_NONE_USER is missing in docs/env_vars.md

### ISSUE THREAD

**Issue by ensonic** [kubernetes/minikube#3259]
BUG REPORT

https://github.com/kubernetes/minikube#linux-continuous-integration-without-vm-support
uses CHANGE_MINIKUBE_NONE_USER but docs/env_vars.md does not document what it actually does.

**Comment by tstromberg** [comment]
This is now part of https://github.com/kubernetes/minikube/blob/master/docs/env_vars.md

Thanks for reporting the omission!
