### ISSUE TITLE
Kubernetes Dashboard shows "???" over the places

### ISSUE THREAD

**Issue by mumoshu** [kubernetes/minikube#326]
Running `minikube dashboard` opens up my browser and shows the dashboard with "???" over the places like:

![image](https://cloud.githubusercontent.com/assets/22009/16798074/4ef98086-4925-11e6-859f-dba39271e507.png)

At a first glance, maybe, a locale issue in kubernetes dashboard?
I don't know how I can drill-down to the root cause though.

I'm not sure if it relates but I'm using minikube v0.5.0.

**Comment by dlorenc** [comment]
Yeah I'm guessing this is a bug in the dashboard. Could you run:

`kubectl get pods --namespace=kube-system`

to find the dashboard pod, then run:

`kubectl logs DASHBOARD_POD --namespace=kube-system`

to see if there are any errors in the dashboard? Otherwise you'll probably have to reopen this in the kubernetes/dashboard repo and see if they can help you out.

**Comment by mumoshu** [comment]
Thanks for taking your time.
I have run the command but nothing looks suspicious to me:

```
$ kubectl logs kubernetes-dashboard-vj9e5 --namespace kube-system
Starting HTTP server on port 9090
Creating API server client for https://10.0.0.1:443
Successful initial request to the apiserver, version: v1.3.0
Creating in-cluster Heapster client
Getting application global configuration
Application configuration {"serverTime":1468397793226}
Incoming HTTP/1.1 GET /api/v1/workload request from 172.17.0.1:51600
Getting lists of all workloads
Getting pod metrics
Outcoming response to 172.17.0.1:51600 with 201 status code
Getting application global configuration
Application configuration {"serverTime":1468397796310}
Incoming HTTP/1.1 GET /api/v1/workload request from 172.17.0.1:51594
Getting lists of all workloads
Getting pod metrics
Outcoming response to 172.17.0.1:51594 with 201 status code
```

**Comment by mumoshu** [comment]
I have just opened a new issue replicating this on the kubernetes/dashboard repo.

**Comment by bryk** [comment]
This is problem in the Dashboard UI. Something with internationalization. Closing this one.
