### ISSUE TITLE
Obsolete "The 'none' driver will run an insecure kubernetes apiserver" warning?

### ISSUE THREAD

**Issue by ensonic** [kubernetes/minikube#3263]
BUG REPORT

Please provide the following details:

**Environment**:
minikube git HEAD

**What happened**:
Minikube emits this warning when using vm-driver=none
https://github.com/kubernetes/minikube/blob/ae9f4b20c7fcb7a89fc65e6eab0fb716f4d1a4ed/cmd/minikube/cmd/start.go#L341_L346

This pull request imho addressed the warning
https://github.com/kubernetes/minikube/pull/1694

**What you expected to happen**:
Not seeing the warning anymore.

If you agree I can send a follow PR to remove the warning and make the option that can be used to suppress the warning a dummy (let me know if you have a different policy for handling obsolete settings).

**Comment by tstromberg** [comment]
I believe the intent of the warning is still legitimate, even if the specific wording is out of date. I've added a note in the documentation outlining some possible issues:

https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md#should-vm-drivernone-be-used-on-a-personal-development-machine-no

Perhaps we should update the error message to simply point to there?

**Comment by ensonic** [comment]
Yes, please. The recent addition of the vmdriver=node docs are a great step. I's said the warning itself is not sufficient, explaining the 'why' is important for people to understand.

**Comment by tstromberg** [comment]
Fixed in v0.34.0.
