### ISSUE TITLE
minikube dashboard

### ISSUE THREAD

**Issue by ngohuongbn** [kubernetes/minikube#3269]
I have just installed minikube v0.30.0. After I run minikube start, I access dasboard by minikube dahboard but not success. Please help me to fix this error.

root@nvh19:~# minikube dashboard
Opening http://127.0.0.1:43089/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/ in your default browser...
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/nvh/.Xauthority which is owned by nvh.)
[6906:6906:1024/161308.169094:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
Running Firefox as root in a regular user's session is not supported.  ($XAUTHORITY is /home/nvh/.Xauthority which is owned by nvh.)
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: iceweasel: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: seamonkey: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: mozilla: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: epiphany: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: konqueror: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: chromium-browser: not found
[6934:6934:1024/161308.245656:ERROR:zygote_host_impl_linux.cc(89)] Running as root without --no-sandbox is not supported. See https://crbug.com/638180.
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: www-browser: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: elinks: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 778: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://127.0.0.1:43089/api/v1/namespaces/kube-system/services/http:kubernetes-dashboard:/proxy/'
failed to open browser: exit status 3

**Comment by bokjo** [comment]
@ngohuongbn try to execute the command with user:  **nvh** not **root**...
Also, have you tried to copy and paste the link in the browser manually?

**Comment by balopat** [comment]
+1 to try @bokjo's suggestion: minikube dashboard is trying to open a browser window - but you are running it as root. The root user seemingly is not setup to use the browser.
