### ISSUE TITLE
sudo -E minikube start --vm-driver=none does not change directory owner when CHANGE_MINIKUBE_NONE_USER=true

### ISSUE THREAD

**Issue by hidekazuna** [kubernetes/minikube#3277]
BUG REPORT

**Environment**:
- **Minikube version** (use `minikube version`):v0.30.0
- **OS** (e.g. from /etc/os-release): 18.04.1 LTS (Bionic Beaver)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:

**What happened**:
sudo -E minikube start --vm-driver=none ends with an error.
```shell
ubuntu@u1804:~$ sudo -E minikube start --vm-driver=none
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.10.0
Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
Finished Downloading kubelet v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E1026 05:34:36.554940   25621 start.go:297] Error starting cluster:  timed out waiting to elevate kube-system RBAC privileges: creating clusterrolebinding: Post https://172.16.1.4:8443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: Gateway Timeout
```

$HOME/.kube and $HOME/.minikube owner are not changed even if 
CHANGE_MINIKUBE_NONE_USER=true.

**What you expected to happen**:

When CHANGE_MINIKUBE_NONE_USER=true, $HOME/.kube and $HOME/.minikube owner are changed from root to $HOME_USER

**How to reproduce it** (as minimally and precisely as possible):
Follow the URL: https://github.com/kubernetes/minikube#linux-continuous-integration-without-vm-support

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
Related issue: #3138
