### ISSUE TITLE
"minikube start" ignores bad --iso-url path

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3282]
If you pass --iso-url with a nonexistent path, "minikube start" ignores your request and moves on as if no flag was passed. Not a very good user experience.

Example:

```shell
minikube start -v=10 --alsologtostderr --vm-driver=kvm2 \
  --iso-url=file://$GOPATH/src/k8s.io/minikube/out/minikube.iso   
```

Seen in v0.30.0.

**Comment by Twister915** [comment]
Implemented a fix for this in #3287
