### ISSUE TITLE
minikube-darwin-amd64 causing too many CPU wakeups

### ISSUE THREAD

**Issue by parasyte** [kubernetes/minikube#3291]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version**: v0.30.0
- **OS**: macOS 10.12.6
- **VM Driver**: `hyperkit` [9ef4ebd](https://github.com/moby/hyperkit/commit/9ef4ebddf87f8b1c16eb088fcdc2d76b17eb27b6)
- **ISO version**: v0.30.0
- **Install tools**: `brew cask install minikube`

**What happened**:

Minikube will not start. The following can be found in Console.app:

```
default	12:26:38.075690 -0700	kernel	process minikube-darwin-amd64[23629] caught waking the CPU 45005 times over ~3 seconds, averaging 14497 wakes / second and violating a limit of 45000 wakes over 300 seconds.
default	12:26:38.075813 -0700	symptomsd	Received CPU wakes trigger:
  minikube-darwin-amd64[23629] () woke the CPU 45005 times over 3.10 seconds (average 14497/sec), violating a CPU wakes limit of 45000 over 300 seconds.
default	12:26:38.076072 -0700	symptomsd	AFSM: receiving symptom with key: com.apple.symptoms.resource_notify.cpu_wakes_trigger
default	12:26:38.076215 -0700	symptomsd	Processing RESOURCE_NOTIFY trigger: ResourceNotifyTriggerExcessCPUWake
default	12:26:38.099139 -0700	symptomsd	  4 total reports for the day is still under the limit of 25.
default	12:26:38.099981 -0700	symptomsd	  Found DiagUsageStats for RESOURCE_NOTIFY of EXC_CPU_WAKE : NON-FATAL (minikube-darwin-amd64) - <DiagnosticCaseUsage: 0x7fd7d7a2e0c0> (entity: DiagnosticCaseUsage; id: 0xec0000cb <x-coredata://F9843FF7-A1C2-4566-BC5B-FEB97E27EE8C/DiagnosticCaseUsage/p944> ; data: {
    casesAccepted = 2;
    casesSeen = 2;
    domain = "RESOURCE_NOTIFY";
    "interarrival_mean" = "878.4385919570923";
    "interarrival_var" = 0;
    lastAccepted = "2018-11-01 19:20:29 +0000";
    lastSeen = "2018-11-01 19:20:29 +0000";
    process = "minikube-darwin-amd64";
    subtype = "NON-FATAL";
    type = "EXC_CPU_WAKE";
})
default	12:26:38.100016 -0700	symptomsd	  2 reports for minikube-darwin-amd64 is still under the limit of 5. Allowing report.
default	12:26:38.100101 -0700	symptomsd	Updating RESOURCE_NOTIFY aggregate report statistics.
default	12:26:38.100659 -0700	symptomsd	Updating RESOURCE_NOTIFY report statistics for RESOURCE_NOTIFY : EXC_CPU_WAKE : NON-FATAL : minikube-darwin-amd64
default	12:26:38.117642 -0700	symptomsd	  Generating report for excess CPU wake
default	12:26:39.204921 -0700	spindump	Saved wakeups_resource.diag report for <private> to <private>
```

**What you expected to happen**:

Minikube should not trigger excessive CPU wakeups. The host kernel will send a resource violation when this happens, and minikube stops doing everything.

**How to reproduce it** (as minimally and precisely as possible):

It seems to happen pretty often on macOS Sierra and High Sierra. But it is very inconsistent. The CPU wakeups monitor is triggered more often after the OS has been running for a few days and sleeping at night. E.g. a laptop that is closed while not in use.

If it happens at all, the above log lines will appear when minikube is started.

**Anything else do we need to know**:

I was able to workaround the issue by disabling the task wakeups monitor. E.g. execute in the recovery-mode shell:

```bash
nvram boot-args='task_wakeups_monitor_rate=0'
```

**Comment by tstromberg** [comment]
Interesting! I honestly have no idea why this is the case, but we should definitely investigate. Thank you for the report!

**Comment by erulabs** [comment]
Is this perhaps not minikube related, but hyperkit / Kubernetes? Lots of related reports about CPU usage on OSX https://github.com/kubernetes/minikube/issues/3207

**Comment by tstromberg** [comment]
Thank you for sharing your experience!

This issue appears to mostly be a duplicate of #3207, so I will close this in preference to that issue so that we may centralize the information around it. If you feel that this is not in fact a duplicate, please feel free to re-open this issue.
