### ISSUE TITLE
the "none" driver does not use correct container runtime

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#3295]
BUG REPORT

Currently the "none" driver is hardcoded to look for docker: cb8d3c027cd9839fce836418ec59e0442a4a0896

It should look at the `--container-runtime`, and adjust accordingly...

(From #3153)

**Comment by tstromberg** [comment]
@afbjorklund appears to be working on this.

**Comment by jayunit100** [comment]
any updates here ?

**Comment by afbjorklund** [comment]
As long as you use `--container-runtime=cri-o`, it should work now.
