### ISSUE TITLE
Unable to access pod after running it

### ISSUE THREAD

**Issue by anuribs** [kubernetes/minikube#330]
I am running kubernetes via minikube. I have created a container by `kubectl run nginx --image=nginx --port=80` and exposed it by ` kubectl expose deployment nginx --port=80`. The cluster ip (kubectl get services) is 10.0.0.12. However when I do curl 10.0.0.12 I dont get a response. The pod nginx is running. Does anyone know how to fix this?Thanks.

**Comment by jimmidyson** [comment]
By default `expose` only creates a `ClusterIP` service so only available inside the cluster. In the Quickstart part of the [README.md](https://github.com/kubernetes/minikube#quickstart) we recommend you run `kubectl expose deployment nginx --type=NodePort` to create a `NodePort` service which you will be able to access in the way you specified above.

**Comment by anuribs** [comment]
I did so but still no response. The new cluster ip is now 10.0.0.196 ; and even a ping to this IP doesnt work. I also typed http://10.0.0.196:80/ in my browser and still no response.

**Comment by jimmidyson** [comment]
So looks like you're trying to access via the service IP rather than the node IP - try running `minikube service nginx` & see if that opens in your browser correctly. You should see that it uses the host IP (same as `minishift ip`) rather than the service IP, which is again only accessible (routable) inside the VM (just as it is in a production cluster only routeable inside the cluster)

**Comment by anuribs** [comment]
Works now! I wasn't aware of this command "minikube service"; couldn't find it in the documentation.  Thanks anyway :-)

**Comment by jimmidyson** [comment]
Which docs? It's in https://github.com/kubernetes/minikube/blob/master/docs/minikube_service.md & linked from https://github.com/kubernetes/minikube/blob/master/docs/minikube.md. It's new in 0.5.0.

**Comment by anuribs** [comment]
Sorry, looks like I overlooked it. Thanks anyway!

**Comment by jimmidyson** [comment]
No worries - glad it worked for you!

**Comment by dlorenc** [comment]
Please re-open this if it causes any more trouble!

**Comment by anuribs** [comment]
How do I expose a pod from another namespace? I am trying to do "kubectl expose deployment nginx   --type=NodePort --namespace=example" but doesn't work.

**Comment by dlorenc** [comment]
That looks basically correct. Does 'nginx' show up if you run:

`kubectl get deployments --all-namespaces`?

**Comment by anuribs** [comment]
yes it is there.

**Comment by dlorenc** [comment]
What error do you get running the command?

**Comment by anuribs** [comment]
error: couldn't find port via --port flag or introspection
See 'kubectl expose -h' for help and examples.

**Comment by jimmidyson** [comment]
What's the output of `kubectl get deployment nginx --namespace=example -o yaml`?
