### ISSUE TITLE
Failed to start minikube in vSphere VM ( installed CentOS 7) -virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor

### ISSUE THREAD

**Issue by rogerlee6411** [kubernetes/minikube#3301]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one)

**Environment**:
vSphere 6.5 VM with install CentOS 7 
Install Docker 
Install minikube 0.30.0

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release):
[root@myxxx .minikube]# sudo cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
[root@myxxx .minikube]# cat ~/.minikube/machines/minikube/config.json | grep DriverName
    "DriverName": "kvm2",

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
[root@myxxx .minikube]# cat ~/.minikube/machines/minikube/config.json | grep -i ISO
        "Boot2DockerURL": "file:///root/.minikube/cache/iso/minikube-v0.30.0.iso",
        "ISO": "/root/.minikube/machines/minikube/boot2docker.iso",

**What happened**:
[root@myxxx .minikube]# minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E1106 23:01:15.832586   10599 start.go:168] Error starting host: Error starting stopped host: Error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2018-11-06T15:01:15.217685Z qemu-kvm: error: failed to set MSR 0x38d to 0x0
qemu-kvm: /builddir/build/BUILD/qemu-2.10.0/target/i386/kvm.c:1809: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.').

[root@myxxx .minikube]# kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.1", GitCommit:"4ed3216f3ec431b140b1d899130a69fc671678f4", GitTreeState:"clean", BuildDate:"2018-10-05T16:46:06Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 10.0.48.115:6443 was refused - did you specify the right host or port?

**What you expected to happen**:
minikube can start to run single cluster service 
**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by balopat** [comment]
This seems like a dupe of https://github.com/kubernetes/minikube/issues/2968.
Can you provide more data on your nested virtualization setup?

**Comment by markllama** [comment]
This is rather a dupe of https://github.com/kubernetes/minikube/issues/3546  

PR to fix: https://github.com/kubernetes/minikube/pull/3586

**Comment by afbjorklund** [comment]
Why are we doing nested virtualization, rather than just running `kubeadm`  directly on Fedora ?
(alternatively setting up a docker machine with VMware beside it, whichever is easiest/suitable)

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
