### ISSUE TITLE
Better DNS support with vm=none

### ISSUE THREAD

**Issue by bhack** [kubernetes/minikube#3304]
How we could better support coredns name resolving?
For systemd  we could use something like:
https://github.com/kubernetes/minikube/issues/2834#issuecomment-426839863

For docker containers that consume Minikube services we could suggest to to use `--dns=` option to point to coredns ip.

/cc @balopat

**Comment by tstromberg** [comment]
I'm still unsure about what this bug is about? What exactly are you asking about? The ability to resolve names from CoreDNS onto the host running minikube?

**Comment by bhack** [comment]
Yes cause I don't know if new tunnel modality will cover https://blog.heptio.com/configuring-your-linux-host-to-resolve-a-local-kubernetes-clusters-service-urls-a8c7bdb212a7

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
