### ISSUE TITLE
Option to skip kubeadm preflight checks

### ISSUE THREAD

**Issue by maingoh** [kubernetes/minikube#3320]
**FEATURE REQUEST**

Since a new docker version has been released and is not validated, the preflight checks raise an error and prevent minikube to start. This would be nice if we could add a custom `--ignore-preflight-errors` to kubeadm, currently hardcoded here:
https://github.com/kubernetes/minikube/blob/ae9f4b20c7fcb7a89fc65e6eab0fb716f4d1a4ed/pkg/minikube/constants/constants.go#L149
Also eventually override or remove the default ones depending on the environnement.

- **Minikube version**: v0.28.2
- **OS** : Ubuntu 18.04.1 
- **VM Driver**: none

**Comment by balopat** [comment]
This sounds like a good idea for advanced usage, since the issue is going to be around for a while. 
cc #3323

**Comment by thomas-riccardi** [comment]
It's indeed related to #3323: the fix (https://github.com/kubernetes/kubernetes/pull/71001) will probably only be included in kubernetes >= 1.13: since kubeadm provides a facility to ignore preflight errors there is no strict need to backport the fix to earlier kubernetes versions.

**Comment by afbjorklund** [comment]
Probably only valid for the "none" driver, since the various `minikube.iso` are supposed to pass checks.

Note that there are already quite a long list of "supported" ignores, such as that pesky old swap partition...

**Comment by tstromberg** [comment]
FWIW, I'd be happy to review any PR which introduces this option.

**Comment by marcosdiez** [comment]
@tstromberg your wishes came true. here is the PR: https://github.com/kubernetes/minikube/pull/3879

It actually allows one to pass generic commands to kubeadm

so this is what has to be executed:

`sudo -E minikube start --vm-driver=none --kubernetes-version v1.11.8 --extra-config kubeadm.ignore-preflight-errors=SystemVerification`

**Comment by jbcpollak** [comment]
For anyone running into issues with @marcosdiez 's solution, there is a small typo. You need to include an `=` as shown below:

```
sudo minikube start --vm-driver=none --extra-config=kubeadm.ignore-preflight-errors=SystemVerification
```

**Comment by tstromberg** [comment]
This was fixed a while back: `--extra-config kubeadm.ignore-preflight-errors=SystemVerification`
