### ISSUE TITLE
minikube start failed downloading ISO 

### ISSUE THREAD

**Issue by Royco1** [kubernetes/minikube#3344]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT 
<!--

 I am trying to run minikube behind a proxy with the following settings:

minikube start --vm-driver=kvm2 --docker-env http_proxy=$http_proxy --docker-env https_proxy=$https_proxy --docker-env no proxy=$no_proxy

minikube fails to download ISO and gets stuck on "downloading minikube iso".

the proxies are 100% correct and should absolutely work. I've seen other issues  about this where people got answers of "it's a network/proxy configuration problem ".  Well here it isn't.

ERROR:
_______________________________________________________________________________________________________________
Downloading Minikube ISO
E1115 10:33:40.250673    3362 start.go:168] Error starting host: Error attempting to cache minikube ISO from URL: Error downloading Minikube ISO: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout.

 Retrying.
E1115 10:33:40.251080    3362 start.go:174] Error starting host:  Error attempting to cache minikube ISO from URL: Error downloading Minikube ISO: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.30.0.iso: dial tcp 216.58.210.16:443: i/o timeout
_______________________________________________________________________________________________________________

**Environment**:

minikube version: v0.30.0
_______________________________________________________________________________________________________________
- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
_______________________________________________________________________________________________________________

**What happened**:

minikube start failed downloading iso

**What you expected to happen**:
should be able to download the iso since there is no problem at all with any network configuration

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
I am behind corp proxy using http and https proxies and custom DNS servers.

**Comment by Royco1** [comment]
nvm it got solved after a few retries

**Comment by balopat** [comment]
Thank you, I'll close this then :)
