### ISSUE TITLE
minikube GitHub permissions cleanup

### ISSUE THREAD

**Issue by cblecker** [kubernetes/minikube#3345]
Hey minikube team!

I'd like to help clean up some of the github permissions to this repo.

Right now there are the following teams with permissions to this repo:
- @kubernetes/minikube-admins - admin access
- @kubernetes/minikube-maintainers - write access

And in addition, there are the following collaborators with direct write permission:
- @aaron-prindle
- @balopat
- @gbraad
- @minikube-bot
- @r2d4
- @tstromberg

I'd like to propose the following changes:
- @r2d4 is a member of the @kubernetes org, and can be added to @kubernetes/minikube-maintainers, and then have direct access removed. This is cleaner to manage permissions via team membership.
- @aaron-prindle, @balopat, @gbraad, and @tstromberg can also be added to @kubernetes/minikube-maintainers if they are still active with the project, but they should go through the [community membership process](https://git.k8s.io/community/community-membership.md#member) first, to be added to the @kubernetes github org.

How does this sound? Please let me know 😄.

cc: @kubernetes/owners

**Comment by r2d4** [comment]
I'm no longer working on this project so feel free to remove all my minikube permissions.

**Comment by cblecker** [comment]
@r2d4 Understood. This is now done.

**Comment by balopat** [comment]
Thank you for this @cblecker! 
Myself and @tstromberg are actively maintaining minikube, we will go through the membership process.

**Comment by cblecker** [comment]
@aaron-prindle Done!

@balopat Sounds good! Thank you!

**Comment by luxas** [comment]
I'm no longer working on minikube so feel free to remove my permissions as well. Thanks!

**Comment by cblecker** [comment]
@luxas Done!

**Comment by tstromberg** [comment]
Thanks for bringing this up! I've just filed the membership application: https://github.com/kubernetes/org/issues/289

**Comment by balopat** [comment]
I filed mine too: https://github.com/kubernetes/org/issues/290

**Comment by cblecker** [comment]
I've added you both to @kubernetes/minikube-maintainers.

Still left:
- Is @gbraad still actively involved with minikube?
- Is @minikube-bot still used as a bot in this repo?
- Can someone review the membership of @kubernetes/minikube-admins and @kubernetes/minikube-maintainers to ensure they are up to date?

**Comment by tstromberg** [comment]
@cblecker thanks for checking in on this:

- @gbraad is still involved
- @minikube-bot is still used

- @kubernetes/minikube-admins 
  - @dlorenc and @vishh should stay
  - @pwittrock can be removed (inactive since 2017)
  - I should probably be added to this group. I'd be happy to commit to ensuring the groups are kept in sync if added.

- @kubernetes/minikube-maintainers looks reasonable. We're onboarding @priyawadhwa and @afbjorklund but they still need to fill out https://github.com/kubernetes/community/blob/master/community-membership.md#member

Thank you again!

**Comment by cblecker** [comment]
We now actually define these in yaml:
https://github.com/kubernetes/org/blob/39ba9bb6358462a1015c0107bdcbb0ab2928df5b/config/kubernetes/org.yaml#L1722-L1738

If you would like to open an PR, I can approve it.. otherwise I can open one on your behalf!

If @gbraad is still involved, he should go through the membership process too, so we can remove direct collaborators.

**Comment by priyawadhwa** [comment]
I just opened an issue with my membership application: https://github.com/kubernetes/org/issues/407

Please let me know if there's anything else I need to do! :)

**Comment by afbjorklund** [comment]
And here is mine: https://github.com/kubernetes/org/issues/409

**Comment by tstromberg** [comment]
@cblecker - I've cleaned up the collaborators list so that it only contains our bot. Can this issue be closed?

**Comment by cblecker** [comment]
Yes, thank you!
/close
