### ISSUE TITLE
sometimes starting an uncleanly stopped instance results /var/lib/docker mounted on rootfs

### ISSUE THREAD

**Issue by balopat** [kubernetes/minikube#3348]
**BUG REPORT**

**Environment**:

**Minikube version** (use `minikube version`): v0.29.0
- **OS** (e.g. from /etc/os-release): MacOSX
- **VM Driver** : virtualbox
- **ISO version** : v0.29.0

**What happened**:
The minikube VM was shutdown in an unclean way as my machine restarted. 
After that `minikube start` hangs at "Starting cluster components...". 
checked where `/var/lib/docker` was mounted and it was on rootfs. 

```
$ cd /var/lib/docker
$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
rootfs             0     0     0    - /

``` 
**What you expected to happen**:

Normally `/var/lib/docker` is mounted on `/dev/sda1`: 
```
$ cd /var/lib/docker
$ df -h .
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        17G  1.3G   14G   9% /var/lib/docker
```

**How to reproduce it** (as minimally and precisely as possible):
Not sure. It sometimes happens, and sometimes it doesn't but repro would be probably something like this: 
1. minikube start
2. unclean shutdown (kill vm)
3. minikube start

**Anything else do we need to know**:

Based on my research this is also what's happening when you run `minikube start` again after minikube is started (https://github.com/kubernetes/minikube/issues/3284). This behavior stops docker from creating new containers due to lack of disk space.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
