### ISSUE TITLE
service: add port name attribute

### ISSUE THREAD

**Issue by kriswuollett** [kubernetes/minikube#3351]
Feature Request: Add port name to service struct used in `minikube service`.

The expected usage is being able to run something like the following in a script to get the URL of a specific named port:

```
minikube service service-name --url --format "{{.Name}} {{.IP}}:{{.Port}}" \
    | grep myPortName
```

This request seems like a prerequisite for and a partial substitute for the #2885 feature request. But it differs in that it does not make the assumption that the name of the port is equivalent to a protocol in a URL.

**Comment by palash25** [comment]
Hi :wave: I would like to take a crack at this, will be sending a PR soon. :smile:

**Comment by palash25** [comment]
Hi :wave: I am new to the k8s ecosystem and would like to take a crack at this.

Just one query, the term port name is kind of confusing, I hope you folks are talking about adding the port numbers of the nodes to the struct, right?

**Comment by bwplotka** [comment]
Hi, just bumbed into this issue as well. 

I think this feature will allow hacks like this:
 > minikube service service-name --format "{{.Name}} {{.IP}}:{{.Port}}" \
    | grep myPortName

but what about something more native like `minikube service <service> --port <port-name|number>`? I think it's often the case for service to have larger number of ports. Right now for my purposes I need to create separate service per each exposed by pod port ): Can help with some PR as well if that change would be desired!

**Comment by arnaudjardine** [comment]
Hi @palash25, have you done something yet for that feature? I find it quite helpful and I've implemented it locally so if you don't have the time to do it I can do a PR for that. 
Thanks.

**Comment by palash25** [comment]
Hi @arnaudjardine I couldn't make time for this, so feel free to submit your PR.
