### ISSUE TITLE
accessing ClusterIP: Failed to connect to w.x.y.z port 80: Operation timed out

### ISSUE THREAD

**Issue by MondherS** [kubernetes/minikube#3355]
**BUG REPORT** :

**Environment**:

**Minikube version** (v0.30.0):
- **OS** (MacOS 10.13.4):
- **VM Driver** (virtualbox):
- **ISO version** (minikube-v0.30.0.iso):
- **Docker version** (18.09.0, build 4d60db4): 
- **VurtualBox version** (5.2.22 r126460): 

**What happened**: I have the "connection refused" issue when trying to curl the application. Here are the steps I did

$ minikube start --insecure-registry="127.0.0.1:5000" --kubernetes-version v1.11.0
Starting local Kubernetes v1.11.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
$ kubectl get pods
NAME                        READY   STATUS    RESTARTS   AGE
my-nginx-59497d7745-7lbt4   1/1     Running   2          59m
my-nginx-59497d7745-8xlwr   1/1     Running   2          59m
$ kubectl get svc
NAME         TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.96.0.1      <none>        443/TCP   1d
my-nginx     ClusterIP   10.101.7.107   <none>        80/TCP    32m
$ curl http://10.101.7.107:80
curl: (7) Failed to connect to 10.101.7.107 port 80: Operation timed out 

I have made the same test using --kubernetes-version v1.12.0 option and without this option (default value : 1.10.0) but the result is the same.

**What you expected to happen**:
Display nginx welcome page

**Output of `minikube logs` (if applicable)**:
[nginx.log](https://github.com/kubernetes/minikube/files/2601916/nginx.log)

**Comment by abdennour** [comment]
Just hearing from the [k8s office hours](https://www.youtube.com/watch?v=9p5JZYAJuM4) that Docker 18 is not 100% supported. 
So it may be the issue.
The office hours session is live.

**Comment by robidangy** [comment]
Hi Abdennour,

Thank you Abdennour, I changed the docker version

**New Docker version** : 18.06.0-ce-mac70 (26399)

I have the same bug :-(

[minikube-1.11.3.logs.txt](https://github.com/kubernetes/minikube/files/2605992/minikube-1.11.3.logs.txt)
[minikube-1.12.0.logs.txt](https://github.com/kubernetes/minikube/files/2605993/minikube-1.12.0.logs.txt)

**Comment by MondherS** [comment]
Hi Abdennour,

I made the test using old docker version

**Docker version** : 18.06.0-ce-mac70 (26399)

But still have the bug 
[minikube-1.11.3.logs.txt](https://github.com/kubernetes/minikube/files/2606019/minikube-1.11.3.logs.txt)
[minikube-1.12.0.logs.txt](https://github.com/kubernetes/minikube/files/2606020/minikube-1.12.0.logs.txt)

**Comment by abdennour** [comment]
Hello Mondher,
The following comments will help you:
- https://github.com/kubernetes/kubernetes/issues/60987#issuecomment-416250765
- https://github.com/kubernetes/kubernetes/issues/60987#issuecomment-420520055

**Comment by pradeepsixer** [comment]
Looks like the curl command is run from your host machine. Is that the case? If so, it won't be able to reach the cluster IP.

**Comment by tstromberg** [comment]
You will need to use `minikube service` or `minikube tunnel` to access these IP's.
