### ISSUE TITLE
"kubectl cp" on large file causes crash: eviction manager: attempting to reclaim imagefs

### ISSUE THREAD

**Issue by michalzubkowicz** [kubernetes/minikube#3358]
**BUG REPORT**:

Please provide the following details:

**Environment**:

minikube version: v0.30.0

OS:
PRETTY_NAME="Deepin 15"
NAME="Deepin"
VERSION_ID="15.7"
VERSION="15.7"
ID=deepin
HOME_URL="https://www.deepin.org/"
BUG_REPORT_URL="http://feedback.deepin.org/feedback/"

VM driver:
    "DriverName": "virtualbox",

ISO version
        "Boot2DockerURL": "file:///home/q/.minikube/cache/iso/minikube-v0.30.0.iso",

**What happened**:
I've tried to copy large file (20GB) into pod, then minikube crashes and I cannot do any action by kubectl, only delete and create of minikube helpes.
The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port? I think it's something to PVC, because even importing file into database directly does the same. 

**What you expected to happen**:
File should be copied

**How to reproduce it** (as minimally and precisely as possible):
Create for example cluster following these instructions:
https://kubernetes.io/docs/tasks/run-application/run-replicated-stateful-application/#deploy-mysql
Change size of volume claim

Try to copy file into cluster:
kubectl cp ./BIGFILE.sql mysql-0:/var/lib/mysql/restore.sql

**Output of `minikube logs` (if applicable)**:
See attached file
[logs.txt.gz](https://github.com/kubernetes/minikube/files/2603348/logs.txt.gz)

**Comment by michalzubkowicz** [comment]
@tstromberg 
Yes. It's probably caused by low disk space I was copying 25GB file inside

**Comment by tstromberg** [comment]
Not much we can do here other than make it easier to debug. Opened #3574 to help with the latter.
