### ISSUE TITLE
VBoxManage: Failed to replace `minikube.vbox` (Sharing violation, file is being used by another process.

### ISSUE THREAD

**Issue by swapnil-taksande** [kubernetes/minikube#3360]
Retrying.
E1123 23:48:18.153818    9336 start.go:174] Error starting host:  Error creating host: Error executing step: Creating VM.
: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe storagectl minikube --name SATA --add sata --hostiocache on failed:
VBoxManage.exe: error: Failed to replace 'C:\Users\Administrator\.minikube\machines\minikube\minikube\minikube.vbox' with 'C:\Users\Administrator\.minikube\machines\minikube\minikube\minikube.vbox-tmp': -114 (Sharing violation, file is being used by another process.).
VBoxManage.exe: error: F:\tinderbox\win-5.2\src\VBox\Main\src-server\MachineImpl.cpp[10136] (long __cdecl Machine::i_saveSettings(bool *,int))
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component SessionMachine, interface IMachine, callee IUnknown
VBoxManage.exe: error: Context: "SaveSettings()" at line 1281 of file VBoxManageStorageController.cpp

**Comment by tstromberg** [comment]
This is an error from Windows and Virtualbox, explaining that there is another program running with this file open:

```
C:\Users\Administrator.minikube\machines\minikube\minikube\minikube.vbox
```

You may want to use https://docs.microsoft.com/sv-se/sysinternals/downloads/process-explorer to see which other process has that file open. https://superuser.com/questions/117902/find-out-which-process-is-locking-a-file-or-folder-in-windows has some further instructions on how to do so.

It seems possible that two minikube processes are running, but it should generally error out in other ways if this is attempted. Any ideas what it might be?
