### ISSUE TITLE
Document uninstall procedures

### ISSUE THREAD

**Issue by G-Harmon** [kubernetes/minikube#3372]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature Request

There doesn't seem to be documentation on how to properly uninstall minikube. #1043 has a bunch of different sets of commands, depending on what OS and shell you're using.

I ran into the problem of an incompatibility between a year-old version of minikube and current (v30). It took a long time to figure out how to clear out all of minikube's old state, before finding I needed to delete ~/.minikube (linux).

**Comment by amruthar** [comment]
Need this one for mess-proof uninstallation without the risks of trial and errors!
