### ISSUE TITLE
[minikube-docker-daemon] Error response from daemon: client is newer than server

### ISSUE THREAD

**Issue by skukreti** [kubernetes/minikube#338]
On attempting to run any docker command after setting the environment to use the default docker environment, I get the following error:

```bash
$ docker ps
Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)
```

I understand that this means that the client (docker cli) version should match the server (minikube docker daemon) version.  Does minikube have a "docker cli" or a command to upgrade the docker daemon on the minikube VM?

**Comment by dlorenc** [comment]
Hey,

Sorry, minikube only currently supports 1.11.1 on the server, which is what is supported by Kubernetes 1.3. Depending on your platform you can grab the correct binary here: 
https://docs.docker.com/engine/installation/binaries/

**Comment by yissachar** [comment]
I've found [DVM](https://github.com/getcarina/dvm) to be very helpful when you have multiple Docker environments on different version (as you likely will when using Minikube). With DVM you can easily switch between client versions to match whatever server you want to communicate with.

**Comment by dlorenc** [comment]
Nice pointer @yissachar. We should add a pointer to our docs about this.

**Comment by dlorenc** [comment]
This should be mostly fixed with #475

**Comment by Dishwasha** [comment]
You should be able to ```export DOCKER_API_VERSION=1.23``` on your host.  See https://docs.docker.com/engine/reference/commandline/cli/#/environment-variables.

**Comment by loxal** [comment]
@Dishwasha worked nice but what is the correct approach to fix this issue? Do I need to stop all containers and restart them to make sure that a new docker server version is running? What is if the client has version `1.666.breaking-api-change` which might prevent from restarting a docker container?
