### ISSUE TITLE
creating a resource for .yml file but in status it shows(Imagepullbackoff)

### ISSUE THREAD

**Issue by raj664** [kubernetes/minikube#3404]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.30.0

- **OS** (e.g. from /etc/os-release):Ubuntu 18.04.1 LTS

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):v0.30.0

- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):Minikube & kubectl

```
CCCCC@XXXX:~/kubernetes$ kubectl get pods
NAME                              READY   STATUS             RESTARTS   AGE
hello-minikube-7b68fff7fd-ggtsx   0/1     ImagePullBackOff   0          16m

               

  node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason                 Age                   From               Message
  ----     ------                 ----                  ----               -------
  Normal   Scheduled              15m                   default-scheduler  Successfully assigned hello-minikube-7b68fff7fd-ggtsx to minikube
  Normal   SuccessfulMountVolume  15m                   kubelet, minikube  MountVolume.SetUp succeeded for volume "default-token-brdl8"
  Normal   Pulling                13m (x4 over 15m)     kubelet, minikube  pulling image "gcr.io/google_contianer/echoserver:1.4"
  Warning  Failed                 13m (x4 over 15m)     kubelet, minikube  Failed to pull image "gcr.io/google_contianer/echoserver:1.4": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/google_contianer/echoserver/manifests/1.4: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
  Warning  Failed                 13m (x4 over 15m)     kubelet, minikube  Error: ErrImagePull
  Normal   BackOff                5m18s (x41 over 15m)  kubelet, minikube  Back-off pulling image "gcr.io/google_contianer/echoserver:1.4"
  Warning  Failed                 25s (x62 over 15m)    kubelet, minikube  Error: ImagePullBackOff


```

**What happened**:(Take a replication controller and and expose it as a new Kubernetes Service)
 minikube service hello-minikube --url
http://192.168.99.101:30836

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
I think there is a typo in your image name. The log shows "gcr.io/google_contianer" instead of "gcr.io/google_container".

 Warning  Failed                 13m (x4 over 15m)     kubelet, minikube  Failed to pull image "gcr.io/google_contianer/echoserver:1.4": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/google_contianer/echoserver/manifests/1.4: unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication
