### ISSUE TITLE
none: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by peng-w** [kubernetes/minikube#3420]
This is a BUG REPORT 

**Environment**:
The win10 operating system installs vmware to run centos

**Minikube version** (use `minikube version`):
v0.30.0

- **OS** (e.g. from /etc/os-release):
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
"DriverName": "none"

- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
cat ~/.minikube/machines/minikube/config.json | grep -i ISO : nothing
minikube ssh cat /etc/VERSION : 'none' driver does not support 'minikube ssh' command

- **Install tools**: nothing
- **Others**: nothing

**What happened**:
minikube start hangs on Starting
![bug](https://user-images.githubusercontent.com/6479081/49571423-2fe72480-f974-11e8-8ba3-1fe9f9a35952.png)

**What you expected to happen**:
Start and access 8443 correctly,I don't know how to check an error.

**How to reproduce it** (as minimally and precisely as possible):
-- Logs begin at Thu 2018-12-06 09:22:22 CST, end at Thu 2018-12-06 16:04:34 CST. --
Dec 06 09:22:25 57 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 06 09:22:25 57 systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Dec 06 09:22:26 57 kubelet[777]: Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a future version. Providing --kubeconfig enables API server mode, omitting --kubeconfig enables standalone mode unless --require-kubeconfig=true is also set. In the latter case, the legacy default kubeconfig path will be used until --require-kubeconfig is removed.
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.838646     777 feature_gate.go:220] feature gates: &{{} map[]}
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.840505     777 controller.go:114] kubelet config controller: starting controller
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.840555     777 controller.go:118] kubelet config controller: validating combination of defaults and flags
Dec 06 09:22:26 57 kubelet[777]: W1206 09:22:26.869774     777 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.888743     777 server.go:182] Version: v1.9.0
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.888839     777 feature_gate.go:220] feature gates: &{{} map[]}
Dec 06 09:22:26 57 kubelet[777]: W1206 09:22:26.889001     777 server.go:280] --require-kubeconfig is deprecated. Set --kubeconfig without using --require-kubeconfig.
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.890146     777 plugins.go:101] No cloud provider specified.
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.940891     777 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.943106     777 container_manager_linux.go:242] container manager verified user specified cgroup-root exists: /
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.943154     777 container_manager_linux.go:247] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>} {Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>}]} ExperimentalQOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s}
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.943456     777 container_manager_linux.go:266] Creating device plugin manager: false
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.944974     777 kubelet.go:290] Adding manifest path: /etc/kubernetes/manifests
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.945113     777 kubelet.go:313] Watching apiserver
Dec 06 09:22:26 57 kubelet[777]: E1206 09:22:26.957865     777 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.204.57:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&limit=500&resourceVersion=0: dial tcp 192.168.204.57:8443: getsockopt: connection refused
Dec 06 09:22:26 57 kubelet[777]: E1206 09:22:26.958561     777 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://192.168.204.57:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.204.57:8443: getsockopt: connection refused
Dec 06 09:22:26 57 kubelet[777]: E1206 09:22:26.959809     777 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://192.168.204.57:8443/api/v1/nodes?fieldSelector=metadata.name%3Dminikube&limit=500&resourceVersion=0: dial tcp 192.168.204.57:8443: getsockopt: connection refused
Dec 06 09:22:26 57 kubelet[777]: W1206 09:22:26.968484     777 kubelet_network.go:139] Hairpin mode set to "promiscuous-bridge" but kubenet is not enabled, falling back to "hairpin-veth"
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.968597     777 kubelet.go:571] Hairpin mode set to "hairpin-veth"
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.975012     777 client.go:80] Connecting to docker on unix:///var/run/docker.sock
Dec 06 09:22:26 57 kubelet[777]: I1206 09:22:26.976409     777 client.go:109] Start docker client with request timeout=2m0s
Dec 06 09:22:26 57 kubelet[777]: E1206 09:22:26.976911     777 kube_docker_client.go:91] failed to retrieve docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Dec 06 09:22:26 57 kubelet[777]: W1206 09:22:26.977045     777 kube_docker_client.go:92] Using empty version for docker client, this may sometimes cause compatibility issue.
Dec 06 09:22:26 57 kubelet[777]: error: failed to run Kubelet: failed to create kubelet: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Dec 06 09:22:26 57 systemd[1]: kubelet.service: main process exited, code=exited, status=1/FAILURE
Dec 06 09:22:26 57 systemd[1]: Unit kubelet.service entered failed state.
Dec 06 09:22:26 57 systemd[1]: kubelet.service failed.
Dec 06 09:22:37 57 systemd[1]: kubelet.service holdoff time over, scheduling restart.
Dec 06 09:22:37 57 systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 06 09:22:37 57 systemd[1]: Starting kubelet: The Kubernetes Node Agent...
Dec 06 09:22:37 57 kubelet[1167]: Flag --require-kubeconfig has been deprecated, You no longer need to use --require-kubeconfig. This will be removed in a future version. Providing --kubeconfig enables API server mode, omitting --kubeconfig enables standalone mode unless --require-kubeconfig=true is also set. In the latter case, the legacy default kubeconfig path will be used until --require-kubeconfig is removed.
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.493109    1167 feature_gate.go:220] feature gates: &{{} map[]}
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.493286    1167 controller.go:114] kubelet config controller: starting controller
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.493295    1167 controller.go:118] kubelet config controller: validating combination of defaults and flags
Dec 06 09:22:37 57 kubelet[1167]: W1206 09:22:37.504516    1167 cni.go:171] Unable to update cni config: No networks found in /etc/cni/net.d
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.512302    1167 server.go:182] Version: v1.9.0
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.512543    1167 feature_gate.go:220] feature gates: &{{} map[]}
Dec 06 09:22:37 57 kubelet[1167]: W1206 09:22:37.512645    1167 server.go:280] --require-kubeconfig is deprecated. Set --kubeconfig without using --require-kubeconfig.
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.512666    1167 plugins.go:101] No cloud provider specified.
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.589712    1167 server.go:428] --cgroups-per-qos enabled, but --cgroup-root was not specified.  defaulting to /
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.590244    1167 container_manager_linux.go:242] container manager verified user specified cgroup-root exists: /
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.590264    1167 container_manager_linux.go:247] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:docker CgroupsPerQOS:true CgroupRoot:/ CgroupDriver:cgroupfs KubeletRootDir:/var/lib/kubelet ProtectKernelDefaults:false NodeAllocatableConfig:{KubeReservedCgroupName: SystemReservedCgroupName: EnforceNodeAllocatable:map[pods:{}] KubeReserved:map[] SystemReserved:map[] HardEvictionThresholds:[{Signal:memory.available Operator:LessThan Value:{Quantity:100Mi Percentage:0} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.1} GracePeriod:0s MinReclaim:<nil>} {Signal:nodefs.inodesFree Operator:LessThan Value:{Quantity:<nil> Percentage:0.05} GracePeriod:0s MinReclaim:<nil>} {Signal:imagefs.available Operator:LessThan Value:{Quantity:<nil> Percentage:0.15} GracePeriod:0s MinReclaim:<nil>}]} ExperimentalQOSReserved:map[] ExperimentalCPUManagerPolicy:none ExperimentalCPUManagerReconcilePeriod:10s}
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.590502    1167 container_manager_linux.go:266] Creating device plugin manager: false
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.590743    1167 kubelet.go:290] Adding manifest path: /etc/kubernetes/manifests
Dec 06 09:22:37 57 kubelet[1167]: I1206 09:22:37.591117    1167 kubelet.go:313] Watching apiserver
Dec 06 09:22:37 57 kubelet[1167]: E1206 09:22:37.599271    1167 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:465: Failed to list *v1.Service: Get https://192.168.204.57:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.204.57:8443: getsockopt: connection refused
Dec 06 09:22:37 57 kubelet[1167]: E1206 09:22:37.599041    1167 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:474: Failed to list *v1.Node: Get https://192.168.204.57:8443/api/v1/nodes?fieldSelector=metadata.name%3Dminikube&limit=500&resourceVersion=0: dial tcp 192.168.204.57:8443: getsockopt: connection refused
Dec 06 09:22:37 57 kubelet[1167]: E1206 09:22:37.600732    1167 reflector.go:205] 

**Output of `minikube logs` (if applicable)**:
[minikube_logs.txt](https://github.com/kubernetes/minikube/files/2652255/minikube_logs.txt)

**Comment by peng-w** [comment]
[root@57 ~]# cat ~/.minikube/machines/minikube/config.json 
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "",
        "MachineName": "minikube",
        "SSHUser": "",
        "SSHPort": 0,
        "SSHKeyPath": "",
        "StorePath": "/root/.minikube",
        "SwarmMaster": false,
        "SwarmHost": "",
        "SwarmDiscovery": "",
        "URL": ""
    },
    "DriverName": "none",
    "HostOptions": {
        "Driver": "",
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": null,
            "Dns": null,
            "GraphDir": "",
            "Env": null,
            "Ipv6": false,
            "InsecureRegistry": [
                "10.96.0.0/12"
            ],
            "Labels": null,
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": false,
            "RegistryMirror": null,
            "InstallURL": ""
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Agent": false,
            "Master": false,
            "Host": "",
            "Image": "",
            "Strategy": "",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": null,
            "ArbitraryJoinFlags": null,
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "/root/.minikube",
            "CaCertPath": "/root/.minikube/certs/ca.pem",
            "CaPrivateKeyPath": "/root/.minikube/certs/ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/root/.minikube/machines/server.pem",
            "ServerKeyPath": "/root/.minikube/machines/server-key.pem",
            "ClientKeyPath": "/root/.minikube/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "/root/.minikube/certs/cert.pem",
            "ServerCertSANs": null,
            "StorePath": "/root/.minikube"
        }
    },
    "Name": "minikube"
}

**Comment by tstromberg** [comment]
It seems like docker isn't running for some reason, and the kubelet is failing because of that. 

It'd be nice if we had better detection and error handling around this case, however.

**Comment by rafalwrzeszcz** [comment]
I'm facing same issue. Since I use Docker across multiple tools connecting over TCP, I don't have Unix socket, my Docker daemon is listening on TCP port. Using `minikube start --vm-driver none --docker-opt "DOCKER_HOST=tcp://172.17.0.1:2375"` doesn't help.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

When you do so, please include the output of: `docker version`.

Thank you for opening the issue!
