### ISSUE TITLE
LB Round Robin Behavior does not work as expected

### ISSUE THREAD

**Issue by aronchick** [kubernetes/minikube#343]
Using the following image (https://hub.docker.com/r/aronchick/hello-node/), set up either through the UI or the CLI, I would expect that the pod round-robined for every time I hit the service endpoint.

```
$ kubectl run hello-node --image=aronchick/hello-node:1.1 --port=8080 \
--replicas=5 --expose=true --port=8080
```

```
$ while true; do curl http://<IP ADDRESS>:<PORT>/hn; sleep 1; done
Hi from: hello-devnation-l60ni
Hi from: hello-devnation-f80r9
Hi from: hello-devnation-dwax4
Hi from: hello-devnation-dwax4
Hi from: hello-devnation-y8tba
Hi from: hello-devnation-dwax4
^C
```

I would have expected this to round robin more evenly.

Further, Chrome, I can't get it to round robin at all; in Firefox, when i force refresh, it at least round robins a little (similarly to the curl example).

**Comment by jimmidyson** [comment]
I assume the pods are always up & satisfying any readiness checks for the duration of the test?

If you run this on a full Kubernetes cluster do you see more even round robin behaviour?

AFAIK round robin LB is done via iptables, configured by Kubernetes service proxy. There is nothing specific in minikube that I can think of that would change behaviour of this as opposed to the full blown Kubernetes install, which uses the same components as minikube bundles in localkube. I would have also expected the curl examples to be more round robinish that shown, as that's a pretty small sample, I wonder if you could run it for more iterations (say 1000) & count each individual response to see if it's within variance.

I wouldn't expect the chrome/firefox to show round robin behaviour without force refresh btw. They will open a persistent connection (via HTTP Keep-Alives) to the first server they are routed to by the service proxy. I assume the difference you're seeing between firefox & chrome is that firefox reconnects on force refresh, whereas chrome doesn't (I don't know that, just from your observations above). If you really want to have requests round robin then you will need to ensure your server sends a `Connection: Close` header back to disable HTTP Keep-Alives (you probably don't want to do that as opening a connection is expensive, hence the widespread use of Keep-Alives :smile:).

**Comment by aronchick** [comment]
In a full k8s cluster, it works great, yep.

In a larger sample, it generally evens out, but it's not close to being
'round robin' - runs of 3-5 are not uncommon.\

It's just a demo, so I don't mind some expense - I'd rather show round
robining better.

**Comment by vhosakot** [comment]
I followed https://kubernetes.io/docs/tutorials/stateless-application/hello-minikube/ and see the same behavior.  I see somewhat round robin-ish behavior when I use curl and do force-refresh in FireFox, but do not see round robin in the Safari browser.

This is what I did to force-refresh in FireFox to see robin-ish behavior:

1. Press shift key, refresh the page.
2. Release shift key.
3. Repeat step 1.

```
$ while true; do curl 192.168.64.2:30250; sleep 2; done
    <P><h1>Response from hello-node-4260806887-rtvps</h1></P>
    <P><h1>Response from hello-node-4260806887-c6004</h1></P>
    <P><h1>Response from hello-node-4260806887-rtvps</h1></P>
    <P><h1>Response from hello-node-4260806887-c6004</h1></P>
    <P><h1>Response from hello-node-4260806887-q47cr</h1></P>
    <P><h1>Response from hello-node-4260806887-k2m3n</h1></P>
    <P><h1>Response from hello-node-4260806887-k2m3n</h1></P>
    <P><h1>Response from hello-node-4260806887-q47cr</h1></P>
    <P><h1>Response from hello-node-4260806887-q47cr</h1></P>
    <P><h1>Response from hello-node-4260806887-c6004</h1></P>
    <P><h1>Response from hello-node-4260806887-rtvps</h1></P>
    <P><h1>Response from hello-node-4260806887-q47cr</h1></P>
```

I think Safari is behaving like Chrome using cache/persistent connection/keep-alives.

**Comment by dlorenc** [comment]
Closing, it looks like this has to do with keep alive behavior.

**Comment by svenkata** [comment]
Kubernetes --type=LoadBalancer is working like a sticky session. 

http://www.techiesinfo.com

**Comment by MaciejLisCK** [comment]
> Closing, it looks like this has to do with keep alive behavior.

I had the same problem.
After adding to my application response header "Connection: close", the traffic indeed go to different pods but it does not looks like round robin. Same pods sometimes are used few times in the row.
