### ISSUE TITLE
nested hyperv hangs at "sudo /usr/bin/kubeadm alpha phase addon kube-dns"

### ISSUE THREAD

**Issue by jknopp** [kubernetes/minikube#3430]
**BUG REPORT**

**Environment**:
I am running minikube on a Windows 10 Enterprise VM inside of Hyper-V with nested virtualization enabled. The host is also running Windows 10 Enterprise.

I have disabled "Dynamic Memory" on the minikube VM.

I have configured the follow Virtual Switch in the nested Hyper-V instance:
![image](https://user-images.githubusercontent.com/3979197/49689567-1b279f80-fae0-11e8-824d-875b63eb1dee.png)

I have also played around with making the switch type "Internal" based on some suggestions in other issues but didn't have any luck.

**Minikube version**: v0.30.0
- **OS**: Windows 10 Enterprise
- **VM Driver**: hyperv
- **ISO version**: v0.30.0
- **Install tools**: Hyper-V Manager 10.0.15063.0, 
- **Others**:
kubectl: Major:"1", Minor:"10", GitVersion:"v1.10.3"

**What happened**:
```
minikube start --vm-driver "hyperv" --hyperv-virtual-switch "Minikube" --disk-size 10g --memory
4096 --v 9999 --alsologtostderr

Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Waiting for host to start...
Waiting for SSH to be available...
Detecting the provisioner...
Setting Docker configuration on the remote daemon...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
```

System specifically hangs on:
```
[stderr =====>] :
I1208 12:02:33.588295     136 config.go:125] Using kubeconfig:  C:\Users\jknopp/.kube/config
I1208 12:02:33.599270     136 ssh_runner.go:80] Run with output:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifes
ts --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=
FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-mani
fests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml
 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-pre
flight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns
```

**What you expected to happen**:
Not to hang.

**How to reproduce it** (as minimally and precisely as possible):
[output.txt](https://github.com/kubernetes/minikube/files/2659980/output.txt)

**Output of `minikube logs` (if applicable)**:
[minikube.logs.txt](https://github.com/kubernetes/minikube/files/2659969/minikube.logs.txt)

**Anything else do we need to know**:
If I stop minikube and retry again with the same VM, it doesn't "hang" on creating the cluster components, but it also doesn't complete the step. I get a "connectex: No connection could be made because the target machine actively refused it." error over and over.

[second pass output.txt](https://github.com/kubernetes/minikube/files/2659985/second.pass.output.txt)

Also while trying to get this to work based on others issues posted here, I played around with my Network Adapter settings in Windows. During 1 attempt I was able to get the cluster to launch and the only thing I could tell that was different was a IPv4 address was assigned rather than the usual IPv6 address:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: C:\Users\jknopp\.minikube\ca.crt
    server: https://192.168.137.64:8443
  name: minikube

```
However, after a system restart to ensure I could reproduce it working, I was not successful and DNS went back to issuing an IPv6 address. I have tried temporarily disabling IPv6 on my Network Adapters however, that was unsuccessful (as others have reported) nor, do I think that's really the best solution anyway.

**Comment by AlanCarlyle** [comment]
I  cleared (uninstalled) my stale hyperv virtual network interfaces (most of them) using Device Manager when I started getting a problem similar to this. 

After doing in did a ```ipconfig /flushdns``` then created the new minikube virtual switch just as you did.

These steps *(and some other hopefully non-essential mucking about)* and I had a nice IP4 address rather than an IP6 one when I started up minikube.

I was upgrading to Minikube v0.31.0 at the time.

**Comment by spoirierfr** [comment]
Hello, 
Any update on this issue ?
I face the same issue 
Error message : Error starting host: Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.

**Comment by tstromberg** [comment]
Thanks for thde bug report! I believe there is a real HyperV issue here, probably related to networking, but possibly due to the VM.

That said, the underlying components have changed so much since v0.30.0 that the way it fails will be completely unrecognizable to this one, so I'm going to mark this issue as obsolete and hope that a newer issue will take over.

If you do see this with minikube v1.0.0, please attach the output of "minikube logs". That would help immensely, now that the logs contain dmesg output.
