### ISSUE TITLE
restart: kubeadm fails with --extra-config=apiserver.basic-auth-file

### ISSUE THREAD

**Issue by paulhopkins11** [kubernetes/minikube#3438]
BUG REPORT

**Environment**:

```
OS:
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

VM driver:
    "DriverName": "virtualbox",

ISO version
        "Boot2DockerURL": "file:///home/paulhopkins/.minikube/cache/iso/minikube-v0.30.0.iso",
```

**What happened**:
Minikube failed to start when configured for basic authentication

**What you expected to happen**:
vm to start in the same way as without basic auth configured

**How to reproduce it** (as minimally and precisely as possible):
First I start minikube with the following
```
minikube --cpus 6 --memory 10000 --alsologtostderr start --kubernetes-version="v1.13.0" --vm-driver=virtualbox
```
Once running I then use minikube ssh and create the file `/var/lib/minikube/certs/mini/users.csv` with the contents `somepassword,johndoe,johndoe123,developers`

ie.
```
$ ls -lat /var/lib/minikube/certs/mini/users.csv
-rw-r--r-- 1 root root 43 Dec  9 21:31 /var/lib/minikube/certs/mini/users.csv
$ more /var/lib/minikube/certs/mini/users.csv 
somepassword,johndoe,johndoe123,developers
```
I then minikube stop and restart as follows
```
minikube --cpus 6 --memory 10000 --alsologtostderr start --kubernetes-version="v1.13.0" --vm-driver=virtualbox \
--extra-config=apiserver.basic-auth-file=/var/lib/minikube/certs/mini/users.csv
```
This resulted in the following error

```
I1209 21:33:34.716833    7099 ssh_runner.go:57] Run: sudo mkdir -p /var/lib/minikube/certs/
I1209 21:33:34.775015    7099 ssh_runner.go:57] Run: sudo rm -f /var/lib/minikube/certs/proxy-client.key
I1209 21:33:34.820764    7099 ssh_runner.go:57] Run: sudo mkdir -p /var/lib/minikube/certs/
I1209 21:33:34.878749    7099 ssh_runner.go:57] Run: sudo rm -f /var/lib/minikube/kubeconfig
I1209 21:33:34.928998    7099 ssh_runner.go:57] Run: sudo mkdir -p /var/lib/minikube
Connecting to cluster...
Setting up kubeconfig...
I1209 21:33:35.231167    7099 config.go:125] Using kubeconfig:  /home/paulhopkins/.kube/config
Starting cluster components...
I1209 21:33:35.235662    7099 ssh_runner.go:57] Run: 
sudo kubeadm alpha phase certs all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase kubeconfig all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase controlplane all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase etcd local --config /var/lib/kubeadm.yaml

E1209 21:33:35.268920    7099 start.go:302] Error restarting cluster:  running cmd: 
sudo kubeadm alpha phase certs all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase kubeconfig all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase controlplane all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase etcd local --config /var/lib/kubeadm.yaml
: Process exited with status 1
```

I can still ssh into minikube and kubeadm.yaml is as follows:

```
$ sudo more /var/lib/kubeadm.yaml 
apiEndpoint:
  advertiseAddress: 192.168.99.107
  bindPort: 8443
apiVersion: kubeadm.k8s.io/v1alpha3
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: minikube
  taints: []
---
apiServerExtraArgs:
  basic-auth-file: "/var/lib/minikube/certs/mini/users.csv"
  enable-admission-plugins: "Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"

apiVersion: kubeadm.k8s.io/v1alpha3
certificatesDir: /var/lib/minikube/certs/
clusterName: kubernetes
controlPlaneEndpoint: localhost:8443
etcd:
  local:
    dataDir: /data/minikube
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12$ 
```

**Output of `minikube logs` (if applicable)**:

Dec 10 16:08:14 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Dec 10 16:08:14 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 10 16:08:24 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Dec 10 16:08:24 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 19.
Dec 10 16:08:24 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 10 16:08:24 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 10 16:08:24 minikube kubelet[3200]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 10 16:08:24 minikube kubelet[3200]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 10 16:08:24 minikube kubelet[3200]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 10 16:08:24 minikube kubelet[3200]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 10 16:08:24 minikube kubelet[3200]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 10 16:08:24 minikube kubelet[3200]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 10 16:08:24 minikube kubelet[3200]: Flag --allow-privileged has been deprecated, will be removed in a future version
Dec 10 16:08:24 minikube kubelet[3200]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 10 16:08:24 minikube kubelet[3200]: I1210 16:08:24.519513    3200 server.go:407] Version: v1.13.0
Dec 10 16:08:24 minikube kubelet[3200]: I1210 16:08:24.519701    3200 plugins.go:103] No cloud provider specified.
Dec 10 16:08:24 minikube kubelet[3200]: F1210 16:08:24.519772    3200 server.go:261] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Dec 10 16:08:24 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Dec 10 16:08:24 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
I tried to replicate this today using minikube v0.33.1, but wasn't able to. I was hoping to, because more recent releases do a better job of revealing error messages. Can you confirm whether or not it still breaks for you?

```
$ minikube start --extra-config=apiserver.basic-auth-file=/var/lib/minikube/certs/mini/users.csv
$ minikube ssh 
  mkdir -p /var/lib/minikube/certs/mini
  cat > /var/lib/minikube/certs/mini/users.csv
  somepassword,johndoe,johndoe123,developers
  ^D
$ minikube stop
$ minikube ssh
```

NOTE: This tested against Kubernetes v1.13.2.  If kubeadm fails, these logs would be great:

`minikube logs`
`minikube ssh 'docker logs $(docker ps -a -f name=k8s_kube-api --format={{.ID}})'`

Thanks!

**Comment by tstromberg** [comment]
I tried to replicate with v1.4, but no such luck. 

If it helps for getting files into place without ssh, we now document file sync: 

https://minikube.sigs.k8s.io/docs/tasks/sync/
