### ISSUE TITLE
0.31.0 start throws E1212 19:15:18.580331  25180 start.go:210] Error parsing version semver:  Version string empty

### ISSUE THREAD

**Issue by gowrisankar22** [kubernetes/minikube#3447]
0.31.0 start throws E1212 19:15:18.580331  25180 start.go:210] Error parsing version semver:  Version string empty but installation is successful on windows with virtualbox. what is was that error ?

C:\Users\ss\Desktop>minikube-windows-amd64.exe start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 178.87 MB / 178.87 MB [============================================] 100.00% 0s
Getting VM IP address...
E1212 19:15:18.580331   25180 start.go:210] Error parsing version semver:  Version string empty
Moving files into cluster...
Downloading kubelet v1.10.0
Downloading kubeadm v1.10.0
Finished Downloading kubeadm v1.10.0
Finished Downloading kubelet v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
Verifying kubelet health ...
Verifying apiserver health ...Kubectl is now configured to use the cluster.
Loading cached images from config file.

Everything looks great. Please enjoy minikube!

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release): windows
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):v0.31.0.iso",

**Comment by nnt** [comment]
I am getting the same error message on Mac with minikube v0.31.0 and hyperkit v0.20180403-17-g3e954c

**Comment by alexsomesan** [comment]
Getting this on macOS too.

**Comment by milindrao** [comment]
Same problem.  Windows 10 Enterprise. And unlike the OP, my start is hanging trying to download kubelet and kubeadm

**Comment by mFarghaly** [comment]
I am getting the same error

`minikube start --vm-driver=kvm2 --kubernetes-version=v1.12.0`

output

```
Starting local Kubernetes v1.12.0 cluster...
Starting VM...
Getting VM IP address...
E1213 11:48:35.150827    7795 start.go:210] Error parsing version semver:  Version string empty
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
Verifying kubelet health ...
Verifying apiserver health ...Kubectl is now configured to use the cluster.
Loading cached images from config file.


Everything looks great. Please enjoy minikube!

```

**Comment by Nethminiromina** [comment]
Same issue.

```
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
E1213 15:58:51.195217    4215 start.go:210] Error parsing version semver:  Version string empty
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Machine exists, restarting cluster components...
Verifying kubelet health ...
Verifying apiserver health ....Kubectl is now configured to use the cluster.
Loading cached images from config file.


Everything looks great. Please enjoy minikube!
```

But minkube is running correctly

```
$ sudo minikube status

host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100
```

**Comment by balopat** [comment]
Got it - https://github.com/kubernetes/minikube/commit/ed8f7124a03bae34103ca9d082fdcb86c4bccd08#diff-ed78cd81495af3964aba5fbc898c33a2R164 @priyawadhwa can you have a look at this, please?

**Comment by alexsomesan** [comment]
@balopat this happens to me consistently on macOS with minikube v0.31.0 when trying to boot up a v1.13.0 K8S cluster. 
I do have the version correctly filled in `config.json` and I did check for funny characters and whitespace directly around it - there is none.

**Comment by priyawadhwa** [comment]
@alexsomesan minikube was overwriting the config file on "minikube start" which caused this error to log, #3450 should fix it once merged

**Comment by alexsomesan** [comment]
Thanks, that makes my day sunnier. I'll watch #3450 then.
