### ISSUE TITLE
kube-apiserver-minikube pod killed

### ISSUE THREAD

**Issue by igieon** [kubernetes/minikube#3449]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):0.31.0
- **OS** (e.g. from /etc/os-release):windows
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):v0.31.0
- **Install tools**:
- **Others**:

**What happened**:
- Everything works as expected only when we starts several pods and minikube machine gets load around 40 (via top). Commands:
CONTAINER ID        NAME                                                                                        CPU %               MEM USAGE / LIMIT   MEM %               NET I/O             BLOCK I/O           PIDS
4b20a416c10f        k8s_kube-apiserver_kube-apiserver-minikube_kube-system_eff47bbbf0bee0c766c4cf6ec26b0e45_0   0.00%               0B / 0B             0.00%               0B / 0B             0B / 0B             0
^C
docker logs -f 4b20a416c10f
Error: No such container: 4b20a416c10f

So kube apiserver disapear and i dont know why so kubenetes doesnt work
and 
**What you expected to happen**:
Kubeadmin doesnd killed
**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by balopat** [comment]
Hi, can you check disk space as well? `df -h` after `minikube ssh`? This might be a diskPressure related eviction.

**Comment by igieon** [comment]
Hi, Currently i don;t have access to that laptop where is running but disk space is not isseu in config i have 
 "disk-size": "60g". Tommorow i will post what is diska space there. What is interesting if i deploy pod 1 by 1 i get cluster running.

**Comment by igieon** [comment]
Hello so i simulated on my machine where thi never occure before. 
I change my config co 2 cores form 3 and set in virtualbox execution cap to 70%. In minikube top runnig and when i hit load over 40 apiserver container disapear. What i need to check to provide more info

**Comment by balopat** [comment]
By disk I meant the rootfs as well the 60G will have an effect only on /dev/vda1 disk in the VM. 
What is the workload doing when you're hitting 40% CPU? Can you provide kubelet logs (`minikube logs`)? That can be super useful to look for errors. Does the API server recover when you decrease the load?

**Comment by igieon** [comment]
It's not cpu 40% but load. And I start several pods with spring boot app without cpu limit.

**Comment by igieon** [comment]
df -h:
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        7.6G     0  7.6G   0% /dev
tmpfs           7.7G     0  7.7G   0% /dev/shm
tmpfs           7.7G   18M  7.7G   1% /run
tmpfs           7.7G     0  7.7G   0% /sys/fs/cgroup
tmpfs           7.7G   44K  7.7G   1% /tmp
/dev/sda1        51G  7.9G   40G  17% /mnt/sda1
/c/Users        476G  236G  240G  50% /c/Users

**Comment by igieon** [comment]
OK so i try it again and change virtualbox configuraiton to 4 cores 90% cap. Minikube start all pods running . Here is uploaded  minikube log for sucessfull start:
[ok.log](https://github.com/kubernetes/minikube/files/2678202/ok.log)
and then i execute minikube stop change cpu cores to 2 cap 70% and after some time apiserver container disapear here is logs
[error.log](https://github.com/kubernetes/minikube/files/2678206/error.log)

I

**Comment by igieon** [comment]
Ok probably i found the reason why took so much time to start. I have several liveness probes when i disable it on spring boot probes minikube stabilize and come up after time.  So problem was with liveness problem. Another question is any way to say in starting minikube start only specific namespaces like kube-system ?

**Comment by igieon** [comment]
I am closing this issue. Its happen because of liveness probe which cause instability of our minikube, after removing liveness probes minkube start and also restarts apiserver
