### ISSUE TITLE
Document "none" driver behavior of overwriting kubeadm

### ISSUE THREAD

**Issue by ppbrown** [kubernetes/minikube#3457]
** BUG REPORT**:

Please provide the following details:

**Environment**: Ubuntu 18

**Minikube version** (use `minikube version`): v0.31.0
- **OS** (e.g. from /etc/os-release): Ubuntu
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):none
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:

**What happened**:
I already have version 1.13 of kubeadm in my $PATH. specifically /snap/bin/kubeadm, because of ubuntu snap packages.
However, minikube insists on downloading a raw binary of kubeadm.. 1.10   and putting it in /usr/bin

Even if I have a SYMLINK /usr/bin/kubeadm -> /snap/bin/kubead, minikube blows it away and puts the older binary there.

**What you expected to happen**:
Don't download anything??

**How to reproduce it** (as minimally and precisely as possible):

minikube start 

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
The user experience here is poor, but:

- minikube downloads the version of kubeadm that aligns with the version of kubernetes you are trying to run
- minikube assumes in none mode that it has full control of the VM: https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

**Comment by ppbrown** [comment]
How does it judge "the version of kubernetes"?
(but reguardless of answer, I still consider this a "bug". If there is a version instaled, it should use it, IMO.
 at minimum, there needs to be an "--accept-system-installed" flag or something)

**Comment by tstromberg** [comment]
minikube has to fetch and invoke kubeadm that matches what you've specified with minikube --kubernetes-version: the default differs between minikube releases, but in v0.31.0 it's v1.10.0. 

The coupling is unfortunately rather tight between kubeadm and the version it's installing for the moment, so we have to fetch the exact version that matches. For example, v1.13, which you've mentioned, is incompatible with minikube in this release (#3460).

I fully recognize that the 'none' experience isn't ideal. It was designed around the assumption of complete control over the system it's running in. I hope to add some lighter weight VM-free options this year.

**Comment by tstromberg** [comment]
Fixed:

https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

```
With the none driver, minikube will overwrite the following system paths:

/usr/local/bin/kubeadm - Updated to match the exact version of Kubernetes selected
/usr/local/bin/kubectl - Updated to match the exact version of Kubernetes selected
/etc/kubernetes - configuration files
```
