### ISSUE TITLE
minikube fails with v1.13.0: kubeadm commands need to be updated

### ISSUE THREAD

**Issue by Th3G4mbl3r** [kubernetes/minikube#3460]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.31.0
- **OS** (e.g. from /etc/os-release): Mac OS Mojave 10.14.1 (18B75)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "virtualbox"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): "Boot2DockerURL": "file:///Users/Th3G4mbl3r/.minikube/cache/iso/minikube-v0.30.0.iso"
- **Install tools**:

Using curl.

Minikube: Upgraded from 0.30.0 to 0.31.0 using the following command: curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.31.0/minikube-darwin-amd64 && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube

Kubectl: Installed using curl. 

kubectl version: Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}

- **Others**:

**What happened**: minikube cluster refuses to start. Errors out during kubeadm steps. Error message as follows:

"Machine exists, restarting cluster components...
E1216 14:12:56.177300    3297 start.go:348] Error restarting cluster:  running cmd:
sudo kubeadm alpha phase certs all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase kubeconfig all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase controlplane all --config /var/lib/kubeadm.yaml &&
sudo /usr/bin/kubeadm alpha phase etcd local --config /var/lib/kubeadm.yaml
: Process exited with status 1"

**What you expected to happen**: Cluster to start successfully.

**How to reproduce it** (as minimally and precisely as possible): minikube start --kubernetes-version v1.13.0

**Output of `minikube logs` (if applicable)**: 

**Anything else do we need to know**: The error seems to be because the command being issues at this step to initialise the kubernetes control is broken. **In version 1.13.0, we need to use `kubeadm init phase` instead of `kubeadm alpha phase`.**

Also, the switch controlplane in the 3rd command needs to change to control-plane.

**Comment by Th3G4mbl3r** [comment]
realised there was a problem with my minikube where the above upgrade did not upgrade the iso to v0.31.0 iso as well. so manually downloaded the iso and moved into cache directory. and still the same error.

Output for minikube iso - "Boot2DockerURL": "file:///Users/Th3G4mbl3r/.minikube/cache/iso/minikube-v0.31.0.iso",

Error seen is still exactly the same. So basically need to fix the kubeadm commands to follow the correct syntax for v1.13.0 onwards.

**Comment by tstromberg** [comment]
Marking this as high priority - since 1.13.x should be made the default ASAP. Thanks for the tip on kubeadm init vs kubeadm alpha.

**Comment by marshalslee** [comment]
CENTOS7 
minikube 0.30

[root@localhost ~]# minikube start --kubernetes-version v1.13.0
Starting local Kubernetes v1.13.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.13.0
Downloading kubelet v1.13.0
E1220 15:31:37.695452   15222 start.go:254] Error updating cluster:  downloading binaries: downloading kubeadm: Error downloading kubeadm v1.13.0: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:

* received invalid status code: 404 (expected 200)
