### ISSUE TITLE
kvm2: status asks for root password 3 times (use virConnectOpenReadOnly?)

### ISSUE THREAD

**Issue by amezin** [kubernetes/minikube#3467]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**: kvm2 driver, Arch Linux, GNOME

**Minikube version** (use `minikube version`): v0.31.0
- **OS** (e.g. from /etc/os-release): Arch Linux
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm2
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.31.0
- **Install tools**: AUR https://aur.archlinux.org/packages/minikube-bin
- **Others**: user not added into libvirt group

**What happened**:
`minikube status` produces 3 password prompts (with the message "System policy prevents management of local virtualized systems")

**What you expected to happen**:
No password prompts, because `org.libvirt.unix.monitor` polkit action is allowed without authentication (`status` should be a read-only action, right?)
`$ cat /usr/share/polkit-1/actions/org.libvirt.unix.policy`:
```
<policyconfig>
    <action id="org.libvirt.unix.monitor">
      <description>Monitor local virtualized systems</description>
      <message>System policy prevents monitoring of local virtualized systems</message>
      <defaults>
        <!-- Any program can use libvirt in read-only mode for monitoring,
             even if not part of a session -->
        <allow_any>yes</allow_any>
        <allow_inactive>yes</allow_inactive>
        <allow_active>yes</allow_active>
      </defaults>
    </action>

    <action id="org.libvirt.unix.manage">
      <description>Manage local virtualized systems</description>
      <message>System policy prevents management of local virtualized systems</message>
      <defaults>
        <!-- Any program can use libvirt in read/write mode if they
             provide the root password -->
        <allow_any>auth_admin_keep</allow_any>
        <allow_inactive>auth_admin_keep</allow_inactive>
        <allow_active>auth_admin_keep</allow_active>
      </defaults>
    </action>
</policyconfig>
```

In the worst case (`org.libvirt.unix.manage` is unavoidable), I expect only one password prompt.

**How to reproduce it** (as minimally and precisely as possible):
`$ minikube status`

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
Interesting. I'll have to look into this, since minikube doesn't prompt for a password at all - I'm curious what is underneath.

**Comment by tstromberg** [comment]
OK. FWIW, I haven't seen this behavior yet with kvm2, but it entirely depends on the environment. I imagine you are correct about using virConnectOpenReadOnly. 

Help wanted!

**Comment by afbjorklund** [comment]
I suppose adding the user to the root-equivalent `libvirt` group would also "fix" the problem ?

https://wiki.archlinux.org/index.php/Libvirt

**Comment by michelesr** [comment]
> I suppose adding the user to the root-equivalent libvirt group would also "fix" the problem ?

It doesn't. If you add yourself to an admin group like `wheel` polkit will ask for your password instead of root password but `minikube status` will still prompt for the password 3 times.

**Comment by michelesr** [comment]
@afbjorklund adding the user to the `libvirt` group does indeed allow you to run minikube commands without providing the password, but that's more a workaround, as you might still want the password to be asked, just not 3 times and not for read only actions.

**Comment by afbjorklund** [comment]
The current minikube assumes that the user is added to both `libvirt` and `docker` group (in VM, or none).
That's not ideal, from a security point of view. But there is no other means to provide authorization provided.

Ubuntu has the same setup:
https://help.ubuntu.com/lts/serverguide/libvirt.html

> In a terminal enter:
    sudo adduser $USER libvirt

This of course also implies that user already has sudo, we use that for doing some other setup.
Including installing minikube in the first place, we only provide instructions for how to do it as root.

`sudo install minikube-linux-amd64 /usr/local/bin/minikube`

----

Also https://blog.wikichoon.com/2016/01/qemusystem-vs-qemusession.html

We default to using root and ` qemu:///system` session. Unfortunate, but so be it.

It would still be good to avoid using those privileges, when not strictly necessary...

So patches to improve it would be welcome, similar to how we warn for sudo now ?

**Comment by michelesr** [comment]
> The current minikube assumes that the user is added to both libvirt and docker group (in VM, or none).

Is the `docker` group required to run minikube with the `kvm2` driver, or just when you use the `none` driver?

**Comment by afbjorklund** [comment]
> Is the `docker` group required to run minikube with the `kvm2` driver, or just when you use the `none` driver?

It is required, but **within** the VM (not on the host). With the none driver, the host is the VM as well.

**Comment by tstromberg** [comment]
Closing, as there is an implicit assumption that the user is in the correct `libvirt` access group. It's not worth trying to work around it.

**Comment by abdelouahabb** [comment]
maybe i am late to the party, but just `sudo usermod -aG libvirt $USER` , restart or disconnect your session and you should run it with kvm without problems
