### ISSUE TITLE
[Feature request]: Sharing host docker credentials with Minikube

### ISSUE THREAD

**Issue by paultiplady** [kubernetes/minikube#3469]
I hit a somewhat confusing UX issue when working with Skaffold and Minikube, which could perhaps be improved.

When the kube context is pointing to minikube, skaffold will use minikube’s docker daemon for the build. This is great because it means the built images are in minikube already.

However, using the "out-of-the-box" config, multi-stage images fail to build.

If I have an image that uses `FROM gcr.io/myrepo/otherimage`, minikube can’t pull that image from the repo. This occurs even if I’ve added `imagePullSecrets` in k8s that let me pull from the `gcr.io/myrepo` repository inside my k8s namespace.

The only option I've found here is to ssh onto minikube and do a `docker login` there. But this isn't the standard documented approach in Minikube (according to the docs here: https://github.com/kubernetes/minikube/blob/master/docs/insecure_registry.md). It would at least be great to flesh out those docs to cover this case.

However I posted this inquiry on the #skaffold slack and @balopat suggested I raise here, as it might be possible to mount the host's `.docker/config` to solve this issue automatically.

They provided this experimental test:

"""
I like the mounting idea, but from a quick experiment it is tricky due to permissions and it doesn’t work still, even if I mount under root’s home folder.
I mounted ~/.docker and ~/.config under /root/.docker and /root/.config and trying to push using sudo docker push …

```
The push refers to repository [gcr.io/myrepo/test-image]
ece4f9fdef59: Pushing [==================================================>]  3.584kB
ad5345cbb119: Pushing [>                                                  ]  534.4kB/53.85MB
ef68f6734aa4: Preparing 
denied: Access denied.
```
"""

**Environment**:
```
minikube version: v0.30.0

OS:
MacOS 10.14 (18A391)

VM driver:
    "DriverName": "hyperkit",

ISO version
        "Boot2DockerURL": "file:///Users/paul/.minikube/cache/iso/minikube-v0.30.0.iso",
```

**Comment by r2d4** [comment]
I'm pretty sure this should work and I tried on my setup.

Skaffold may use the docker daemon in the minikube VM but uses the authn on the host by parsing the host .docker/config and attaching those credentials on the pull/push from the vendored client.

So it should be as simple as

```
gcloud auth login
gcloud auth configure-docker
minikube start
skaffold dev
```

**Comment by paultiplady** [comment]
@r2d4 circling back on this one as I've just set up a fresh Minikube VM (v0.35.0) and hit this again.

I've done `gcloud auth configure-docker` on my host, and can do a `docker pull us.gcr.io/my-project/my-image`.

My cluster can't pull that image.

Is there some way for me to debug this and verify what docker config has been mounted on my Minikube host?

SSH'ing in I just see a `.ssh` in `/home/docker/`, I don't see a `/home/docker/.docker/` directory. So it doesn't look like the host's config has been mounted.

Could this be a hyperkit issue?

It sounds like you're expecting the host's `~/.docker/config.json` file to provide Minikube with authorization on the GCR repo, but that seems to be at odds with the required setup in https://github.com/kubernetes/minikube/blob/da2b1b00b1955c544720f38e2f438ce355a4df9a/docs/insecure_registry.md#private-container-registries - am I understanding your expectation correctly?

Thanks!

**Comment by ndarilek** [comment]
Hitting this myself and would appreciate some guidance. Host Docker credentials don't appear to make it into Minikube. What, specifically, should be happening, and what specific actions trigger sharing of credentials? Is it specific to `skaffold dev`? Presumably I wouldn't want my registry credentials leaked everywhere I run `skaffold run`.

I tried creating $HOME/.docker in my Minikube VM, adding config.json from my local machine, then restarting Docker. I still can't pull the image. Everything works locally, but not within Minikube.
