### ISSUE TITLE
Create /etc/crictl.yaml when running containerd

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#3472]
@fvoznika was trying to start minikube with the containerd backend in #3471 -- after upgrading `minikube start` worked, but `crictl pull gcr.io/some/image` did not.  Fabricio was able to get it to work after running 

`sudo crictl config runtime-endpoint unix:///run/containerd/containerd.sock` 

to create `/etc/crictl.yaml`

Perhaps minikube should run this command automatically when using the containerd runtime to generate `/etc/crictl.yaml`.

Also, thanks @fvoznika for providing this info :)

**Comment by afbjorklund** [comment]
Sounds similar to #3194
