### ISSUE TITLE
Make docker client talk to talk to docker for Mac daemon instead of the one in minikube VM

### ISSUE THREAD

**Issue by jatins** [kubernetes/minikube#348]
I ran `eval $(minikube docker-env)` so that Docker client can communicate with the minikube Docker daemon. How will I undo the same so that my client can talk to docker for Mac daemon?

There should probably a note for the same in docs.

**Comment by dlorenc** [comment]
Good question! We should document this. You can either close your terminal and create a new one, or you can run:

```shell
unset DOCKER_HOST
unset DOCKER_TLS_VERIFY
unset DOCKER_CERT_PATH
```

**Comment by dlorenc** [comment]
Let's add a "--unset" flag to minikube docker-env to unset these automatically.

**Comment by dlorenc** [comment]
We now have the --unset flag to docker-env.
