### ISSUE TITLE
--nfs-share: Don't start if there is export rule with subnet

### ISSUE THREAD

**Issue by antonmarin** [kubernetes/minikube#3481]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.27.0
- **OS** (e.g. from /etc/os-release): macos 10.13.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperkit
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.26.0.iso
- **Install tools**:
- **Others**:

**What happened**:
```
E1221 10:30:35.671209    5837 start.go:165] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: Export verification failed:
getaddrinfo() failed for 192.168.64.0/24
exports:1: couldn't get address for host: 192.168.64.0/24
exports:1: no valid hosts found for export
```

**What you expected to happen**:
Successful start

**How to reproduce it** (as minimally and precisely as possible):
Add smth like `/db_data 192.168.64.0/24 -alldirs` to /etc/exports and run `minikube start --vm-driver hyperkit --nfs-share /any_folder`

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
Just to clarify - the issue here is that the /etc/exports line is valid, but that the hyperkit driver wants to parse it but cannot?

**Comment by antonmarin** [comment]
If i understood right, so yes. Line in /etc/exports valid and targets minikube host, but minikube host doesnt exists so it fails

**Comment by tstromberg** [comment]
Related:

#5108 #4324
