### ISSUE TITLE
Creating another node within minikube 

### ISSUE THREAD

**Issue by anuribs** [kubernetes/minikube#349]
I know that minikube creates a single node(minikubeVM with boot2docker.iso) when started. Is it possible to create a second node (with some other .iso file also) in minikube?

**Comment by yissachar** [comment]
See https://github.com/kubernetes/minikube/issues/94

**Comment by dlorenc** [comment]
Yeah, this looks like a dup of #94. We only support one node currently. Could you explain the use-case in #94?
