### ISSUE TITLE
 running command: : Process exited with status 2

### ISSUE THREAD

**Issue by liu-xuewen** [kubernetes/minikube#3491]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

Please provide the following details:
![image](https://user-images.githubusercontent.com/29445066/50383408-fc372900-06ed-11e9-9ea5-5e763009cf4b.png)

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release):
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver:"; 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```
![image](https://user-images.githubusercontent.com/29445066/50383414-0c4f0880-06ee-11e9-8250-1b90c5c9cda4.png)

**What happened**:
 running command: : Process exited with status 2
**What you expected to happen**:
success
**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by lnsyyj** [comment]
macos same issues
`yujiangdeMBP-13:~ yujiang$ rm -rf ~/.minikube/machines/minikube/
yujiangdeMBP-13:~ yujiang$ minikube start
Starting local Kubernetes v1.12.4 cluster...
Starting VM...
Downloading Minikube ISO
 178.88 MB / 178.88 MB [============================================] 100.00% 0s
Getting VM IP address...
E1224 01:32:46.938527    1227 start.go:211] Error parsing version semver:  Version string empty
Moving files into cluster...
Downloading kubelet v1.12.4
Downloading kubeadm v1.12.4
Finished Downloading kubeadm v1.12.4
Finished Downloading kubelet v1.12.4
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
E1224 01:46:03.934313    1227 start.go:343] Error starting cluster:  kubeadm init error 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI 
 running command: : Process exited with status 2
`

**Comment by neurostream** [comment]
Incorporating the observation by @tvollmer (  also behind MITM-style corp SSL proxy here ), was able to get a clean _minikube start_ on MacOS with _hyperkit_ .

I suppose this is because _kubeadm_ pulls down its containers and other goodies it needs from the inner bootstrapping VM - which didn't have the same MITM corp proxy trust that my outer workstation terminal has ( which is why it gets past the initial "Downloading Minikube ISO" part).

```
curl -kROL https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit
sudo install -o root -g wheel -m 4755 docker-machine-driver-hyperkit /usr/local/bin/

minikube stop && minikube delete && rm -rf ~/.minikube && rm -rf ~/.kube
minikube cache delete
minikube start --vm-driver=hyperkit --bootstrapper=kubeadm
```

**Comment by Mis2** [comment]
I am not on corp network, still running the same error. Minikube v0.32.0 in ubuntu 16.04.

**Comment by mijklgps** [comment]
so am i

**Comment by mijklgps** [comment]
minikube start
---------------------------------------------------------------------------------------------------------------
Starting local Kubernetes v1.12.4 cluster...
Starting VM...
Downloading Minikube ISO
 178.88 MB / 178.88 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubelet v1.12.4
Downloading kubeadm v1.12.4
Finished Downloading kubeadm v1.12.4
Finished Downloading kubelet v1.12.4
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
E0102 10:22:30.149014   47900 start.go:343] Error starting cluster:  kubeadm init error
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI
 running command: : Process exited with status 2
---------------------------------------------------------------------------------------------------------------
 minikube logs
---------------------------------------------------------------------------------------------------------------
Version: v1.12.4
Jan 02 02:29:24 minikube kubelet[3594]: I0102 02:29:24.080004    3594 plugins.go:99] No cloud provider specified.
Jan 02 02:29:24 minikube kubelet[3594]: F0102 02:29:24.080072    3594 server.go:262] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jan 02 02:29:24 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jan 02 02:29:24 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by mijklgps** [comment]
# minikube start

Starting local Kubernetes v1.12.4 cluster...
Starting VM...
Downloading Minikube ISO
 178.88 MB / 178.88 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubelet v1.12.4
Downloading kubeadm v1.12.4
Finished Downloading kubeadm v1.12.4
Finished Downloading kubelet v1.12.4
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
E0102 10:22:30.149014   47900 start.go:343] Error starting cluster:  kubeadm init error
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI
 running command: : Process exited with status 2


# minikube logs


Version: v1.12.4
Jan 02 02:29:24 minikube kubelet[3594]: I0102 02:29:24.080004    3594 plugins.go:99] No cloud provider specified.
Jan 02 02:29:24 minikube kubelet[3594]: F0102 02:29:24.080072    3594 server.go:262] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jan 02 02:29:24 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jan 02 02:29:24 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by Tianny** [comment]
Same as I. How to resolve it ?

**Comment by tstromberg** [comment]
minikube v0.33 does a slightly better job showing the reasons for kubeadm failures. Does someone mind retrying this on a newer release?

**Comment by tstromberg** [comment]
Also - I suspect this may be related to proxy/firewall issues. It's difficult to tell without additional logs from the person who opened this.

**Comment by tstromberg** [comment]
@liu-xuewen - do you mind attempting this with minikube v0.33.1, and attach the output of:

`minikube logs`

and:

`minikube ssh 'docker logs $(docker ps -a -f name=k8s_kube-api --format={{.ID}})'`

Thank you for the bug report!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
