### ISSUE TITLE
Allow setting `extra-config` in config file

### ISSUE THREAD

**Issue by therc** [kubernetes/minikube#3504]
minikube v0.32.0

`extra-config` is a verbose command line flag. Unfortunately, it can't be persisted in the minikube configuration file. Perhaps this is deliberate, perhaps it's an omission or perhaps there's a technical reason why it can't be easily implemented.

**Comment by opncow** [comment]
Just stumbled upon this, too. Would be nice to be able to set it permanently via the minikube configuration file.

**Comment by opncow** [comment]
Still not possible afaik.

**Comment by jfoy** [comment]
https://github.com/kubernetes/minikube/issues/5729

**Comment by otherguy** [comment]
/remove-lifecycle rotten
/reopen

Still not possible afaik.
