### ISSUE TITLE
brew cask installs 0.26.1

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/minikube#3513]
Installed minikube:

`brew cask install minikube`

It installs version 0.26.1:

```
minikube version
minikube version: v0.26.1
```

This is almost a year old release. When will this be updated to the latest release?

It is critical, particularly because of the CVE: https://github.com/kubernetes/minikube#newsflash

**Comment by tstromberg** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/minikube.rb  specifies v0.32.0.

Do you mind running `brew update` to ensure that you have the latest files locally?

**Comment by arun-gupta** [comment]
PEBKAC closing the issue
