### ISSUE TITLE
Update DOCKER_API_VERSION to latest stable (1.39)

### ISSUE THREAD

**Issue by justinruggles** [kubernetes/minikube#3519]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

FEATURE REQUEST

The latest stable version of the Docker Engine API is 1.39. It includes some nice features like the `docker build --ssh` option.  Minikube is using latest stable Docker Engine, but it is only using Docker API 1.35.

https://github.com/kubernetes/minikube/blob/9a7b0b91aad20b7a938cd7ba0db203864227ff7f/pkg/minikube/constants/constants.go#L141

Please provide the following details:

**Environment**:

```
minikube version: v0.32.0
OS: MacOS 10.12.6
VM driver: virtualbox
ISO version: v0.28.1
```

**What happened**:

Even if I attempt to override `DOCKER_API_VERSION` with 1.39, it still only uses 1.35.

**What you expected to happen**:

To be able to use the latest stable API version, or at least allow setting it when starting minikube.

**How to reproduce it** (as minimally and precisely as possible):

```
2019-01-09 09:44:53 ~$ minikube start --docker-env DOCKER_API_VERSION=1.39
Starting local Kubernetes v1.12.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Machine exists, restarting cluster components...
Verifying kubelet health ...
Verifying apiserver health ....Kubectl is now configured to use the cluster.
Loading cached images from config file.


Everything looks great. Please enjoy minikube!
2019-01-09 09:46:23 ~$ eval $(minikube docker-env)
2019-01-09 09:48:33 ~$ export DOCKER_API_VERSION=1.39
2019-01-09 09:48:42 ~$ docker version
Client: Docker Engine - Community
 Version:           18.09.0
 API version:       1.35 (downgraded from 1.39)
 Go version:        go1.10.4
 Git commit:        4d60db4
 Built:             Wed Nov  7 00:47:43 2018
 OS/Arch:           darwin/amd64
 Experimental:      false

Server:
 Engine:
  Version:          17.12.1-ce
  API version:      1.35 (minimum version 1.12)
  Go version:       go1.9.4
  Git commit:       7390fc6
  Built:            Tue Feb 27 22:20:43 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by tstromberg** [comment]
Thanks for the feedback! This seems easy enough to address - PR's are welcome!

**Comment by afbjorklund** [comment]
If this constant is needed at all (?), it should probably follow whatever is in `minikube.iso`

https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/docker-bin/docker-bin.mk#L7

`DOCKER_BIN_VERSION = 18.06.1-ce`
(not sure why it was using the ancient ISO above, as the later ones are _supposed_ to use API 38)

https://docs.docker.com/develop/sdk/#api-version-matrix

But best would probably be to remove it altogheter, and let the docker client/server sort it out... ?

``` console
$ eval $(minikube docker-env | grep -v DOCKER_API_VERSION)
$ docker version
Client:
 Version:           18.09.1
 API version:       1.38 (downgraded from 1.39)
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:35:23 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       e68fc7a
  Built:            Tue Aug 21 17:28:38 2018
  OS/Arch:          linux/amd64
  Experimental:     false

```
It will downgrade gracefully, to whatever least common denominator of API version exists...

----

It might not even be used at all, if not using docker CRI ?

``` console
$ minikube docker-env
# The docker service is currently not active
```

So minikube probably doesn't need to get involved here ?

**Comment by afbjorklund** [comment]
@justinruggles : note that 1.35 is your server API version, so you need to upgrade that (ISO) as well

But that means that kubernetes needs to support it (18.09), which it should do in later versions: #3323

minikube:
- [X] Upgrade Kubernetes to 1.13 (DONE)
- [ ] Upgrade Docker CE to 18.09 (TODO)
 
kubeadm: https://kubernetes.io/docs/setup/cri/

The hard-coded API constant _should_ have been 38 already now, and should be 39 (or removed) later.

Workaround is to use a separate `docker-machine` VM for your builds, instead of the `minikube` VM

**Comment by afbjorklund** [comment]
See #4180 (and actually minikube was using API 38, even though the variable said API 35)
