### ISSUE TITLE
Const DefaultDiskSize is Defined But Not Implemented for All Drivers

### ISSUE THREAD

**Issue by barry-schneider** [kubernetes/minikube#3530]
The const [DefaultDiskSize](https://github.com/kubernetes/minikube/blob/e6b60fb38c9c59550cabec160043ef00fec9fe85/pkg/minikube/constants/constants.go#L110) is defined but implemented for all drivers.  Is this constant used if no driver is specific? Please implement. Thanks

**Comment by Zyqsempai** [comment]
@barry-schneider Actually, it's used https://github.com/kubernetes/minikube/search?q=DefaultDiskSize&unscoped_q=DefaultDiskSize

**Comment by barry-schneider** [comment]
I will update the questsion
