### ISSUE TITLE
Minikube logo proposal

### ISSUE THREAD

**Issue by mies** [kubernetes/minikube#355]
Hi all,

We're big fans of minikube at Wercker and have created a few logo designs for it.

Would be awesome if you all could let us know through 👍  which version you like best.

![minikube-logo-proposal](https://cloud.githubusercontent.com/assets/19435/16920763/4db0d48e-4d0f-11e6-933d-0ebd1c40fcae.png)

/cc @dlorenc

**Comment by mies** [comment]
![version1](https://cloud.githubusercontent.com/assets/19435/16920850/960d3376-4d0f-11e6-91c3-ea0599d784b0.png)

**Comment by mies** [comment]
![version2](https://cloud.githubusercontent.com/assets/19435/16920860/9e08434a-4d0f-11e6-8908-81c62d614756.png)

**Comment by mies** [comment]
![version3](https://cloud.githubusercontent.com/assets/19435/16920868/a758a5c0-4d0f-11e6-9c29-a4de129ef4c3.png)

**Comment by mies** [comment]
![version4](https://cloud.githubusercontent.com/assets/19435/16920885/b12a8c1c-4d0f-11e6-83ff-2229f3373614.png)

**Comment by dlorenc** [comment]
Thanks @mies! Let's leave this open for a few more days then go with the winner. Let's say Monday, July 25th?

**Comment by mies** [comment]
@dlorenc sounds like a plan!

**Comment by uzzer** [comment]
Logos 1-3 have too much small details and will be corrupted on small resolution output (small screen, poor print, etc.) and unreadable from long distance. I bet for "4" and it would be nice to simplify anchor sign.

_With love from [Wercker public](https://werckerpublic.slack.com/archives/wercker/p1468999117000082)_

**Comment by yissachar** [comment]
I think 4 is the only one that doesn't relate to the Minikube project goals (unless I'm missing something - what does the anchor signify?). It also has a bevel effect which doesn't match up nicely with the flatness of the main Kubernetes logo.

I'd probably prefer 1 if only the internal cube was shown, and the rest was just a flat color fill. From a messaging standpoint it ticks all the boxes (mini, cube, k8s in a box), but I don't like the current aesthetics.

**Comment by jimmidyson** [comment]
I also am a bit confused by the anchor (I do understand the meaning of kubernetes as helmsman but why the anchor?).

1 & 2 are closest to what I would like to see.

**Comment by yissachar** [comment]
Here's an attempt at what I meant in my previous comment. Ignore the poor color matching (I just used the same blue from the Kubernetes main logo), etc. I am not a graphic designer, and this is not meant as a real proposal, just for illustration purposes.

![minikube-logo-altered](https://cloud.githubusercontent.com/assets/2190867/16994514/a7bb0e60-4e75-11e6-9adb-dcace55fbbb3.png)

**Comment by martamarszal** [comment]
Hi all, actually some time ago we created a very similar issue https://github.com/kubernetes/minikube/issues/176
Based on the github and Twitter votes we had two winner logos. I was suppose to submit a pull request for both. I'm going to do that now. 
Maybe you guys submit your winner logo as well :)

Or should we do another poll with all the best logos?

**Comment by dlorenc** [comment]
I created another issue to vote between the two, thanks for the PRs @martamarszal !
