### ISSUE TITLE
Add apiserver logs to "minikube logs" command

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3550]
This way users can see flag misconfiguration errors.

**Comment by tstromberg** [comment]
Here's the command for the docker runtime:

`minikube ssh 'docker logs $(docker ps -a -f name=k8s_kube-api --format={{.ID}})'

It's unclear yet how to handle this for containerd and CRIO.

**Comment by afbjorklund** [comment]
Should probably be using `crictl` for this, it is a mandatory requirement (nowadays) and is supposed to know how to talk to different CRI ? However, it doesn't have the `--format` option available

**Comment by afbjorklund** [comment]
`sudo crictl logs $(sudo crictl ps -a --name kube-apiserver | tail -n +2 | cut -f1 -d' ')`

**Comment by afbjorklund** [comment]
@tstromberg : using podman wouldn't really help for docker, just like docker wouldn't help for cri-o
