### ISSUE TITLE
Provide an easy way to give static files to apiserver

### ISSUE THREAD

**Issue by surajssd** [kubernetes/minikube#3559]
**Is this a BUG REPORT or FEATURE REQUEST?**:

`FEATURE REQUEST`.

**Environment**:

```
minikube version: v0.33.1

OS:
NAME="Ubuntu"
VERSION="16.04.5 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.5 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

VM driver:
    "DriverName": "kvm2",

ISO version
        "Boot2DockerURL": "file:///home/surajd/.minikube/cache/iso/minikube-v0.33.1.iso",
        "ISO": "/home/surajd/.minikube/machines/minikube/boot2docker.iso",
```

**What happened**:

The process to provide static files to apiserver running inside minikube can be very tricky. Please add a simpler way to provide files to apiserver. So if I want to provide a normal flag that has data as string it is very easy, for example to provide the flag `--authorization-mode=RBAC` to apiserver I just have to add `--extra-config=apiserver.authorization-mode=RBAC` to `minikube start`. But what if the value of the flag is a path to a file? How do I provide that? For that I have to follow a two step process where I have to start the minikube normally then, make file availble in `/var/lib/minikube/certs`. This particular location because this dir is mounted inside the apiserver pod at the same location.

Then stop minikube and restart it again by adding the flag, for example I wanted to provide apiserver flag `--encryption-provider-config=/var/lib/minikube/certs/encryptionconfig.yaml`, started minikube with `--extra-config=apiserver.encryption-provider-config=/var/lib/minikube/certs/encryptionconfig.yaml`.

Above steps I have followed from https://suraj.io/post/apiserver-in-minikube-static-configs/

**What you expected to happen**:

I want an easier way to make the configs available in minikube.

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

Detailed steps in https://suraj.io/post/apiserver-in-minikube-static-configs/

**Comment by tstromberg** [comment]
This is now documented: https://github.com/kubernetes/minikube/blob/master/docs/syncing-files.md

Thank you for your patience! Please re-open this issue and/or make changes to the documentation if it is not sufficient.
