### ISSUE TITLE
minikube does not work properly if VirtualBox machine called 'boot2docker-vm' exists

### ISSUE THREAD

**Issue by leibowitz** [kubernetes/minikube#356]
Just FYI, I had an ancient boot2docker-vm machine in VirtualBox and minikube start would succeed but nothing would actually be set up properly.

Using `minikube start` would output the regular:
```
Starting local Kubernetes cluster...
Kubernetes is available at https://192.168.99.101:8443.
Kubectl is now configured to use the cluster.
```
But running ```kubectl get pods --all-namespaces``` would return
```
NAMESPACE     NAME                             READY     STATUS              RESTARTS   AGE
kube-system   kube-addon-manager-boot2docker   0/1       ContainerCreating   0          21s
```

Even when running with `--vm-driver="xhyve"`, the behavior is the same. 

Running `minikube dashboard --url` for example would return
```
E0718 17:59:53.370850    7455 dashboard.go:45] Error accessing the kubernetes dashboard (is minikube running?): Error:  Error getting kubernetes-dashboard service: services "kubernetes-dashboard" not found
```

I found out the issue was I already had a VM in VirtualBox called 'boot2docker-vm' prior to installing minikube. After renaming that VM, everything worked.

Feel free to close the issue, just wanted to post it here as a reference for anyone having the same issue and wondering why

For reference, I'm using 
VirtualBox 5.0.24 r108355
minikube v0.6.0
Mac OS X 10.10.5 (Yosemite)
kubectl v1.3.0

**Comment by dlorenc** [comment]
There must be something else to this, I run boot2docker/machine and minikube at the same time on my laptop.

**Comment by leibowitz** [comment]
Maybe a coincidence. All I did was a full clone of the "boot2docker-vm" machine (to "boot2docker-vm Clone"), and deleted the "boot2docker-vm" one. After that doing `minikube start` followed by `kubectl get pods --all-namespaces` started returning a different output (the same as what the doc says):
```
NAMESPACE     NAME                            READY     STATUS    RESTARTS   AGE
kube-system   kube-addon-manager-minikubevm   1/1       Running   4          1m
kube-system   kubernetes-dashboard-jq7qk      1/1       Running   4          1m
```

and `minikube dashboard --url` finally returned the dashboard url successfully

Like I said, feel free to close the issue. It's really just in case someone faces the same problem (if that ever happens).

**Comment by leibowitz** [comment]
I tried simply cloning it back to "boot2docker-vm", but everything still works. So yeah, something else at play. Not sure what exactly. Well, closing then as I can't reproduce

**Comment by benhuang-zh** [comment]
Hi leibowitz,
I have same issue. I open VirtualBox just can find "minikubeVM". Could you share where can find "boot2docker-vm"?

**Comment by imorti** [comment]
so at this point I'd do a few things: 
1. Use Docker for MAC as it's now out. 
2. If in VirtualBox you don't see ```minikubeVM``` then something is wrong. 
3. What happens when you run ```minikube status```?

**Comment by benhuang-zh** [comment]
I am using ubuntu.

It seems missing some steps in minikube start.
ben@ubuntu:~$ minikube start
Starting local Kubernetes cluster...
Kubernetes is available at https://192.168.99.100:8443.
Kubectl is now configured to use the cluster.

ben@ubuntu:~$ minikube status
Running

run docker ps in vm, just has headers:
CONTAINER ID        IMAGE         COMMAND           CREATED        STATUS         PORTS  NAMES

**Comment by dlorenc** [comment]
@benhuang-zh can you explain what you're looking for? More containers should show up in "docker ps" after a minute or so.

**Comment by benhuang-zh** [comment]
@dlorenc I try to find out why my minikube can't work properly.

**Comment by snspmr** [comment]
E0314 12:56:47.629478   17628 start.go:165] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path 
plz help me????

**Comment by snspmr** [comment]
#minikube status 
minikube: 
cluster: 
kubectl:
