### ISSUE TITLE
dial tcp <ip>:8443: connectex: No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by liijuun** [kubernetes/minikube#3562]
win10 home + virtualbox

minikube version: v0.33.1

docker version
Client:
 Version:       18.03.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    0520e24302
 Built: Fri Mar 23 08:31:36 2018
 OS/Arch:       windows/amd64
 Experimental:  false
 Orchestrator:  swarm

Server: Docker Engine - Community
 Engine:
  Version:      18.09.1
  API version:  1.39 (minimum version 1.12)
  Go version:   go1.10.6
  Git commit:   4c52b90
  Built:        Wed Jan  9 19:41:57 2019
  OS/Arch:      linux/amd64
  Experimental: false

failed log:

I0121 14:43:59.784647    1828 ssh_runner.go:101] SSH: sudo kubeadm init phase control-plane all --config /var/lib/kubeadm.yaml
I0121 14:43:59.809444    1828 utils.go:224] > [control-plane] Using manifest folder "/etc/kubernetes/manifests"
I0121 14:43:59.809444    1828 utils.go:224] > [control-plane] Creating static Pod manifest for "kube-apiserver"
I0121 14:43:59.818409    1828 utils.go:224] > [control-plane] Creating static Pod manifest for "kube-controller-manager"
I0121 14:43:59.818869    1828 utils.go:224] > [control-plane] Creating static Pod manifest for "kube-scheduler"
I0121 14:43:59.818869    1828 ssh_runner.go:101] SSH: sudo kubeadm init phase etcd local --config /var/lib/kubeadm.yaml
I0121 14:43:59.842182    1828 utils.go:224] > [etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
I0121 14:44:00.866500    1828 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.99.102:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: dial tcp 192.168.99.102:8443: connectex: No connection could be made because the target machine actively refused it.]
I0121 14:44:02.372552    1828 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.99.102:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: dial tcp 192.168.99.102:8443: connectex: No connection could be made because the target machine actively refused it.]
I0121 14:44:03.873949    1828 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.99.102:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: dial tcp 192.168.99.102:8443: connectex: No connection could be made because the target machine actively refused it.]

**Comment by tstromberg** [comment]
The Windows machine has a network configuration that is preventing it from accessing the API server running at https://192.168.99.102:8443. This is typically caused by a firewall or proxy. If that's the case, can you turn it off or configure it to allow these packets?

Let me know what you find. Thanks!

**Comment by liijuun** [comment]
@tstromberg i still have same problem after shutdown firewall.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by s709t** [comment]
yes, it exists, and is happening to me

**Comment by mettaramesh** [comment]
@tstromberg  i'm running minikube on virtualbox. I'm facing exact scenario as above and logs also are same. seems this issue still persists.  i did full cleanup and did a fresh cluster. after some 50 seconds are soo, i'm getting this error:

OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
minikube  version :  v1.4.0 
virtual box : 6.0
* Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...


```
$ kubectl get all
Unable to connect to the server: http2: server sent GOAWAY and closed the connection; LastStreamID=69, ErrCode=NO_ERROR, debug=""
Unable to connect to the server: dial tcp 192.168.99.102:8443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 192.168.99.102:8443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 192.168.99.102:8443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: dial tcp 192.168.99.102:8443: connectex: No connection could be made because the target machine actively refused it.
Unable to connect to the server: net/http: TLS handshake timeout
Unable to connect to the server: net/http: TLS handshake timeout
Error from server: rpc error: code = Unavailable desc = transport is closing
Unable to connect to the server: unexpected EOF
Unable to connect to the server: read tcp 192.168.99.1:52053->192.168.99.102:8443: wsarecv: An existing connection was forcibly closed by the remote host.
```

**Comment by tstromberg** [comment]
@mettaramesh - Thanks for the update . Do you mind upgrading to a more recent release of minikube and including the output of `minikube start` and `minikube logs`?
