### ISSUE TITLE
vboxmanage Errors, even though using vm-driver=none 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/minikube#3563]
**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release):

ubuntu 16

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):

none 

**What happened**:

VBoxManage errors occured even though launching with `--vm-driver=none`

**What you expected to happen**:

Expected either a failure due to local dependencies, or success, but definetly expected no virtualbox specific errors.

**How to reproduce it** (as minimally and precisely as possible):

- Install VirtualBox on a linux machine.
- Disable HardwareVirtualization
- Try to install minikube with . `vm-driver=none`

**Output of `minikube logs` (if applicable)**:

TBD

**Anything else do we need to know**:

TBD

@john-gram for details to this issue.

**Comment by jayunit100** [comment]
presumeably an init check that happens if vbox is detected that is unnecessary when using `local` or non vbox options.  easily slips by because its probably rare that someone runs w/ `local` after already installing virtualbox :).

**Comment by tstromberg** [comment]
What version of minikube was this seen on?

**Comment by jayunit100** [comment]
this was 0.28.0.  If this has been fixed, then feel free to close thanks .   @john-gram ?
