### ISSUE TITLE
Update podman to v1.0.0

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3568]
It's out: https://podman.io/

It will require updating podman.mk, podman.hash, and going through https://github.com/kubernetes/minikube/blob/master/docs/contributors/minikube_iso.md

**Comment by afbjorklund** [comment]
Some of the required steps were done in the podman PR: #2757

**Comment by phoenixking25** [comment]
I got the idea that for this there would be changes first to change the version in `podman.mk` to `v1.0.0` and another to change hash, but can anyone help me in how to get new hash to update.

**Comment by afbjorklund** [comment]
phoenixking25: will make a PR for this shortly (it needs some other fixes too), but basically `sha256sum`.

**Comment by afbjorklund** [comment]
Also need a better place to store the default registries, probably was not a good idea to include them in crio.

`WARN[0000] unable to find /etc/containers/registries.conf. some podman (image shortnames) commands may be limited `

Maybe we should add a "containers-common", or perhaps generate it at run-time like with `crictl.yaml` ?

``` toml
[registries.search]
registries = ['docker.io']

[registries.insecure]
registries = []
```

**Comment by afbjorklund** [comment]
Scratch that, might as well keep the `registries.conf` with the already existing `policy.json` file.
