### ISSUE TITLE
minikube output should include version/platform/arch

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3569]
This is very useful for bug reports.

**Comment by tstromberg** [comment]
Related PR: #3537

**Comment by afbjorklund** [comment]
Maybe we can use this to output something similar to the bug template ?

https://github.com/kubernetes/minikube/blob/master/.github/ISSUE_TEMPLATE#L31:L40

Adding cri and k8s version is probably not a bad idea either, for reports.
