### ISSUE TITLE
addons enable: display pod status, and block until pods are up by default

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3577]
"addons enable" is very optimistic in assuming that the addon works great. We should display pod status and block until the pods launched by the addon appear to be healthy.

**Comment by medyagh** [comment]
@tstromberg did you mean that enabling addon should actually does the enabling ? (currently it does on the next minikube start)
```
$ minikube addons enable helm-tiller
✅  helm-tiller was successfully enabled
```
