### ISSUE TITLE
vbox/macos: "service hello-minikube" does not return

### ISSUE THREAD

**Issue by davecramer** [kubernetes/minikube#3587]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
minikube version: v0.33.1
- **OS** (e.g. from /etc/os-release):
macos 10.14.2
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
virtutalbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
v0.33.1
- **Install tools**:
- **Others**:
**What happened**:
minikube service hello-minikube does not return

**What you expected to happen**:
I expected it to return with the service

**How to reproduce it** (as minimally and precisely as possible):
install minikube, start it run the hello-minikube deployment

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

**Comment by davecramer** [comment]
Yes, that is how I started it.
kubectl get pod
NAME                              READY     STATUS    RESTARTS   AGE
hello-minikube-6fd785d459-2txbf   1/1       Running   0          1h

minikube service --v=2 --alsologtostderr service hello-minikube
W0125 12:46:42.867947   53278 root.go:146] Error reading config file at /Users/davec/.minikube/config/config.json: open /Users/davec/.minikube/config/config.json: no such file or directory
I0125 12:46:42.868710   53278 notify.go:121] Checking for updates...
Please specify a service name.

kubectl get services
NAME             TYPE       CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
hello-minikube   NodePort   10.108.53.70   <none>        8080:31953/TCP   1h

**Comment by hammadbinarif** [comment]
I am getting the same error

After executing on Windows 10 / MiniKube with Virtualbox.

minikube service --v=2 --alsologtostderr service first-deployment

W0905 11:29:57.956933   72272 root.go:254] Error reading config file at C:\Users\John\.minikube\config\config.json: open C:\Users\John\.minikube\config\config.json: The system cannot find the file specified.
I0905 11:29:57.962796   72272 notify.go:124] Checking for updates...
* You must specify a service name

**Comment by tstromberg** [comment]
@hammadbinarif - I believe you might have a separate issue. I think your command-line may be off: it should be:

`minikube service first-deployment --alsologtostderr -v=2`

**Comment by hammadbinarif** [comment]
> @hammadbinarif - I believe you might have a separate issue. I think your command-line may be off: it should be:
> 
> `minikube service first-deployment --alsologtostderr -v=2`
> 
> I see that I mentioned the wrong command-line a few comments back.
> 
> If the service command still isn't returning, please share the output of `minikube status`. Thanks!

Thanks. This solved my issue
