### ISSUE TITLE
host-only cidr conflicts with the network address of a host interface

### ISSUE THREAD

**Issue by dgmdevelopment** [kubernetes/minikube#3594]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug

Please provide the following details:

**Environment**:
Linux

**Minikube version** (use `minikube version`): 0.33.1
- **OS** (e.g. from /etc/os-release):  
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox 
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): "Boot2DockerURL": "file:///root/.minikube/cache/iso/minikube-v0.33.1.iso",

- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver:"; 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
Starting local Kubernetes v1.13.2 cluster...
Starting VM...
E0125 20:03:31.508584   22686 start.go:205] Error starting host: Error starting stopped host: Error setting up host only network on machine start: host-only cidr conflicts with the network address of a host interface.

 Retrying.
E0125 20:03:31.508984   22686 start.go:211] Error starting host:  Error starting stopped host: Error setting up host only network on machine start: host-only cidr conflicts with the network address of a host interface

minikube failed :( exiting with error code 1

**What you expected to happen**:
minikube to start without error

**How to reproduce it** (as minimally and precisely as possible):
minikube start

**Output of `minikube logs` (if applicable)**:
F0125 20:04:48.372810   22799 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting ssh client: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

**Anything else do we need to know**:
tried to reinstall kubectl and virtualbox, and still got same issue.

**Comment by tstromberg** [comment]
Thanks for the bug report! The error message could definitely be improved here, but I think I understand what's going on here. 

With Virtualbox, minikube sets up VM's in 192.168.9.1/24. If the error message is correct, it so happens that your Ubuntu machine has an interface that is also configured for the same IP range. You can verify this by using:

`ip a | grep 192.168.9.`

So, to use minikube, you'll need to specify a non-conflicting network. Depending on how your interface is configured, it could be another part of 192.168.0.0, such as:

`minikube start --host-onlly-cidr=192.168.99.1/24`

Or perhaps another RFC 1918 network altogether:

`minikube start --host-onlly-cidr=172.16.0.1/24`

Please let me know if this helps, as I'd like to see about getting the error message improvedf if this is the case. Thank you!

**Comment by dgmdevelopment** [comment]
Hi, thanks for the reply. Indeed, you were right it was conflicting with my lan ip of 192.168.99.1, which is my router setup IP. 
So, i decided to start fresh.  nothing important was in the cluster.   I removed the .minikube folder, and also re moved all the docker containers listed under bridge interfaces. Then, reinstalled per the directions 
`https://kubernetes.io/docs/tasks/tools/install-minikube/#linux`
did
`minikube start --host-only-cidr=172.16.0.1/24`
and 
`minikube status` shows
`host: Running`
`kubelet: Running`
`apiserver: Running`
`kubectl: Correctly Configured: pointing to minikube-vm at 172.16.0.100`

But when i try 
`minikube dashboard` 
i get 
`
Enabling dashboard ...
Verifying dashboard health ...
Launching proxy ...
F0128 17:49:41.125014    4594 dashboard.go:87] kubectl proxy: readByteWithTimeout: EOF
goroutine 1 [running]:
k8s.io/minikube/vendor/github.com/golang/glog.stacks(0xc0001ef000, 0xc000122620, 0x57, 0xdc)
	/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:766 +0xd4
k8s.io/minikube/vendor/github.com/golang/glog.(*loggingT).output(0x200dda0, 0xc000000003, 0xc0004fc160, 0x1f85316, 0xc, 0x57, 0x0)
	/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:717 +0x306
k8s.io/minikube/vendor/github.com/golang/glog.(*loggingT).printf(0x200dda0, 0x3, 0x1395e0d, 0x11, 0xc00060fbb0, 0x1, 0x1)
	/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:655 +0x14b
k8s.io/minikube/vendor/github.com/golang/glog.Fatalf(0x1395e0d, 0x11, 0xc00060fbb0, 0x1, 0x1)
	/go/src/k8s.io/minikube/vendor/github.com/golang/glog/glog.go:1145 +0x67
k8s.io/minikube/cmd/minikube/cmd.glob..func5(0x1ffaf80, 0x202c230, 0x0, 0x0)
	/go/src/k8s.io/minikube/cmd/minikube/cmd/dashboard.go:87 +0x5a6
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x1ffaf80, 0x202c230, 0x0, 0x0, 0x1ffaf80, 0x202c230)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:757 +0x2cc
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1ffbdc0, 0x0, 0x202c200, 0xc00014bf48)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:843 +0x2fd
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x1ffbdc0, 0x0, 0x0)
	/go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:791 +0x2b
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/go/src/k8s.io/minikube/cmd/minikube/cmd/root.go:103 +0x2d
main.main()
	/go/src/k8s.io/minikube/cmd/minikube/main.go:41 +0x92`

 Hope this helps!  Thank you!

**Comment by dgmdevelopment** [comment]
I switched my OS to Linux mint, 19.1, cinnamon, using virtualbox 6.0, and now everything is working with
 
`minikube start --host-only-cidr=172.16.0.1/24`

It pulled down the ISO, started minikube fine and I'm up and running in the dashboard as well. 
I dont know what was wrong in my former version of Ubuntu, but all good now.  Thanks Kubernetes team!
