### ISSUE TITLE
Feature Request: Istio addon

### ISSUE THREAD

**Issue by wstrange** [kubernetes/minikube#3597]
FEATURE REQUEST

Istio is becoming very popular for it's service mesh and ingress features. It is now available on GKE as a managed service.  It would be a really nice addon for minikube.

**Comment by himani93** [comment]
Hi, can I work on this as my first contribution to minikube. Thanks

**Comment by tstromberg** [comment]
@himani93 excellent! Please let me know if there is anything I can do to help. 

(I'd assign the bug to you, but something is getting in the way with my GitHub permissions)

**Comment by ashishranjan738** [comment]
@himani93 are you working on it i was thinking to give it a try ? cc @tstromberg

**Comment by gbraad** [comment]
IIRC you can not assign a task to a non project member. I would suggest for
you to sync and see if you can work on this together... a PR proposal can
also always come without any notion. It is not a conclusive state to be
assigned. Try to post regular updates to show people you are working on it.

**Comment by fenglixa** [comment]
@himani93 are you still working on this?  I would like to provide PR for this ticket. Thanks
BR
-Francis

**Comment by himani93** [comment]
@fenglixa Sure, please go ahead.

**Comment by medyagh** [comment]
@fenglixa are you still working on this ?

**Comment by fenglixa** [comment]
OK, I will try this recently. @medyagh , do you have any deadline for this ticket?
Have investigated before, the effort to support istio on minikube is not as simply as my original thought. 
-Feng

**Comment by priyawadhwa** [comment]
@fenglixa are you still interested in adding support for Istio? If so, I can assign you to this issue, and am happy to look at any PRs or help in any way.

**Comment by fenglixa** [comment]
@priyawadhwa, sorry for that, I am busy on another trunk recently, though I am so interesting on this ticket. 
I am happy if anyone else could help provide PR on this issue.  Thanks.

BR
-Feng
