### ISSUE TITLE
vbox mac: Could not find matching IP for MAC address 0800271b78eb

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3608]
- minikube v0.33.1
- macOS 10.4.1
- virtualbox 6.0.0

...
/usr/local/bin/minikube -v=8 --alsologtostderr  start
Starting local Kubernetes v1.13.2 cluster...
[verbose.log](https://github.com/kubernetes/minikube/files/2813887/verbose.log)
Starting VM...
I0130 10:09:55.164149   28619 cluster.go:74] Skipping create...Using existing machine configuration
COMMAND: /usr/local/bin/VBoxManage showvminfo minikube --machinereadable
...
natnet1="nat"
macaddress1="080027E3CB28"
cableconnected1="on"
...
I0130 10:09:55.267724   28619 cluster.go:86] Machine state:  Running
...
ip addr show
SSH cmd err, output: <nil>: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:e3:cb:28 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 81942sec preferred_lft 81942sec
    inet6 fe80::a00:27ff:fee3:cb28/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1b:78:eb brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe1b:78eb/64 scope link 
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0

SSH returned: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:e3:cb:28 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 81942sec preferred_lft 81942sec
    inet6 fe80::a00:27ff:fee3:cb28/64 scope link 
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:1b:78:eb brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe1b:78eb/64 scope link 
       valid_lft forever preferred_lft forever
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
```

**Comment by tstromberg** [comment]
So, in this case, the MAC address is actually associated to eth1, which has no IP address.  So, there is a mismatch between what MAC address Virtualbox expects the interface to be associated to, and which one it's actually associated to. 

This may be related to #3572 - and it is quite possible that I used a newer version of minikube to setup this VM initially.

**Comment by afbjorklund** [comment]
But `eth1` seems to be correct one, the question is more why VirtualBox didn't assign it an IP ?

The `eth0` is the internal interface, so it can only access the private NAT network (10.0.2.x)

> * **NAT Network**. A NAT network is a type of internal network that allows outbound connections.

You want the host-only interface, that will show a public IP address (normally 192.168.99.x)

> * **Host-only networking**. This can be used to create a network containing the host and a set of virtual machines, without the need for the host's physical network interface. Instead, a virtual network interface, similar to a loopback interface, is created on the host, providing connectivity among virtual machines and the host.

See https://www.virtualbox.org/manual/ch06.html

Maybe we need better VirtualBox startup logs ?

**Comment by tstromberg** [comment]
@afbjorklund - probably because the MAC address no longer matched expectations, due to #3572
