### ISSUE TITLE
minikube start command hangs at Downloading kubeadm v1.10.0 & Downloading kubelet v1.10.0

### ISSUE THREAD

**Issue by vivkv** [kubernetes/minikube#3618]
**Is this a BUG REPORT or FEATURE REQUEST?** : **BUG REPORT**

**Environment**:

Ubuntu running on VmWare workstation 14 pro running on windows 10

**Minikube version** :  v0.28.2

- **OS** (e.g. from /etc/os-release):  
NAME="Ubuntu"
VERSION="12.04.4 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.4 LTS)"
VERSION_ID="12.04"

- **VM Driver** :
"DriverName": "virtualbox",

- **ISO version** :
"Boot2DockerURL": "file:///home/vivek/.minikube/cache/iso/minikube-v0.28.1.iso",

   minikube ssh cat /etc/VERSION : v0.28.1

**What happened**:

Trying to run command **minikube start** and it hangs at **Downloading kubeadm v1.10.0** & **Downloading kubelet v1.10.0**

**What you expected to happen**:

Those packages should get downloaded and message should come for finished download also command should proceed further initializing the clusters. When I try to start minikube from virtualbox manually, a login prompt is coming for minikube that means it is booting properly. Although this command minikube start is not working.

**How to reproduce it** :
Was following these steps at [tutorial](https://matthewpalmer.net/kubernetes-app-developer/articles/install-kubernetes-ubuntu-tutorial.html)

1. Booted Ubuntu in Vmware workstation pro on my windows 10 machine.
2. Installed VirtualBox 5 from apt-get.
3. Downloaded extension packs and opened it in VirtualBox and installed it.
4. Installed kubectl and minikube.
5. minikube start.

**Output of 'minikube start' **:
 Link for verbose output : [output log](https://drive.google.com/file/d/1eUix8fak07a9MZNFXUJWnO3lCdGKFNOR/view?usp=sharing)

**Comment by tstromberg** [comment]
Do you mind trying this with minikube v0.33? I don't suspect it will fix the issue, but it should give us a better log message.

Altogether this sounds like a networking issue related to the nested VM's. Why use VMware and then VirtualBox underneath it? I recommend just running minikube on Windows.

**Comment by vivkv** [comment]
Hi @tstromberg 

I upgraded my Ubuntu to Ubuntu 14, and issued the same command- **minikube start**, it worked this time.

**Output :**  
```
vivek@ubuntu:~$ minikube start
There is a newer version of minikube available (v0.33.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.33.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading kubelet v1.10.0
Downloading kubeadm v1.10.0
Finished Downloading kubeadm v1.10.0
Finished Downloading kubelet v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0206 08:27:01.311522    4706 start.go:305] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
```

**Then,**
```
vivek@ubuntu:~ $ minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
vivek@ubuntu:~ $ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
```

**Comment by tstromberg** [comment]
Thanks for the update! I'm going to mark this as obsolete, since it references a fairly old minikube release at this point.

**Comment by muellert** [comment]
I have the same problem with minikube 1.0.0 and kubernetes 1.14.0, just downloaded today. I am using the kvm2 driver, also downloaded today (ie, nothing obsolete here).

**Comment by amitgaware** [comment]
Same issue with me on Windows10 today.
It hangs at below step

:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
@   Downloading kubeadm v1.14.0
@   Downloading kubelet v1.14.0

**Comment by AyanGhatak** [comment]
Same occuring to me on macOS.

minikube start
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 6.84 MB / 142.88 MB [==>----------------------------------------]   4.79% 1m52s

Remained at this position stucked

**Comment by technomage** [comment]
I seem to have the same issue.  I installed Minikube and Hyperkit driver from macports and updated the Hyperkit driver to the latest.  The messages for downloading Kubernetes v1.14.0 and then creating the kyperkit vm, and then downloading Minikube ISO are intermixed with messages about no matching credentials falling back to anonymous.  Then it shows a download progress lounge that hangs about 622KB into a 142MB download.
