### ISSUE TITLE
vmware: dialing TCP: ssh: handshake failed / Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by CaledoniaProject** [kubernetes/minikube#3620]
Running latest version, I have multiple issues with minikube and it's not working at all. The command line is:

```
https_proxy=http://192.168.154.200:6666 minikube start --docker-env http_proxy=http://192.168.154.200:6666 --docker-env https_proxy=http://192.168.154.200:6666 --docker-env no_proxy=192.168.154.0/24 --vm-driver=vmwarefusion -v=10 --alsologtostderr
```

#### 1. weird config file location issue

This is the first error message I encountered:

```
W0204 21:36:13.423240    4392 root.go:146] Error reading config file at /Users/XX/.minikube/config/config.json: open /Users/XX/.minikube/config/config.json: no such file or directory
```

Clearly the file is generated and saved at `~/.minikube/machines/minikube/config.json`, was it a backward compatible feature?

#### 2. SSH login issue

I got tons of ssh errors:

```
dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
I had to login with password `tcuser` and add the key to authorized_keys, WTF?

#### 3. kube is not started at all

Installation is finally completed, now I started to get this:

```
I0204 21:37:22.674386    4392 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.154.163:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: Service Unavailable]
I0204 21:37:23.177517    4392 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: minikube/v0.0.0 (darwin/amd64) kubernetes/$Format" 'https://192.168.154.163:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy'
```

Inside the VM:

```
$ curl 127.0.0.1:8443
curl: (7) Failed to connect to 127.0.0.1 port 8443: Connection refused
```

What should I do?

**Comment by gbraad** [comment]
Maybe you have messed up your SSH settings. Check local settings or if you
might a stray binary on path provided by something like brew, etc.

**Comment by balopat** [comment]
1. Changing the driver after you created a machine won't change a thing - if the machine was created with vmwarefusion, it will stay that way, even if you run `--vm-driver=xhyve`, you'll have to remove the machine with `minikube delete` and recreate it with `minikube start`. 

2. Sometimes it takes a long time on my mac to the cluster to stabilize - not sure why yet - the roundtripper  messages flow for a couple of minutes - it's worthwile waiting until the very end - minikube will either fail or succeed - can you rerun and see if it fails? 

3. If there is failure, I would start looking into your docker proxy setup - logging onto the VM, what is the output of the following commands? 

```
docker ps -a 
docker run hello-world 
```

**Comment by balopat** [comment]
> ```
> dialing TCP: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], > no supported methods remain
> ```

This is odd - I haven't seen it in the logs - how did you get this exactly?

**Comment by CaledoniaProject** [comment]
@gbraad @balopat I don't have a stray binary. But I have ~/.ssh/config in place to determine which ssh private key to use. And minikube used the wrong key. 

So all ssh command should add `-i ~/.minikube/machines/minikube/id_rsa` explicitly.

**Comment by CaledoniaProject** [comment]
Oh, it's already in the command line, weird

**Comment by CaledoniaProject** [comment]
Anyway, here's my ssh/config, 192.168 is the vmnet in use

```
Host 192.168.*
   StrictHostKeyChecking no
   UserKnownHostsFile=/dev/null
   ControlMaster no
   IdentityFile ~/.ssh/trusted/id_rsa
```

**Comment by CaledoniaProject** [comment]
I might figured it out:

1. I forget to start the proxy, so the first run on `docker pull` failed
2. I started minikube again, it did not attempt to pull the docker image again.

**Comment by CaledoniaProject** [comment]
Still not working. Failed at the RBAC stage:

```
I0205 16:37:16.517251    1190 loader.go:359] Config loaded from file /Users/XXX/.kube/config
I0205 16:37:16.523612    1190 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: minikube/v0.0.0 (darwin/amd64) kubernetes/$Format" 'https://192.168.64.7:8443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings/minikube-rbac?timeout=1m0s'
```

port 8443 is up in the VM:

```
$ curl -k 'https://192.168.64.7:8443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings?timeout=1m0s'
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "clusterrolebindings.rbac.authorization.k8s.io is forbidden: User \"system:anonymous\" cannot list resource \"clusterrolebindings\" in API group \"rbac.authorization.k8s.io\" at the cluster scope",
  "reason": "Forbidden",
  "details": {
    "group": "rbac.authorization.k8s.io",
    "kind": "clusterrolebindings"
  },
  "code": 403
}
```

Attached complete log: [log.txt](https://github.com/kubernetes/minikube/files/2831340/log.txt)

**Comment by tstromberg** [comment]
Possibly a dupe of #3242

**Comment by balopat** [comment]
What kind of proxy are you running? It would be useful to know the details of your setup so that we can repro this.

**Comment by tstromberg** [comment]
Also related to #3145

**Comment by CaledoniaProject** [comment]
It's a squid proxy running on a remote server.

**Comment by CaledoniaProject** [comment]
I should start minikube with --docker-env only, removing the `http_proxy=XXX` env on minikube itself solved this problem.
