### ISSUE TITLE
Use kubernetes-incubator/external-storage for dynamic provisioning (deprecate r2d4 storage-provisioner)

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/minikube#3628]
It looks like we use r2d4's fork of https://github.com/kubernetes-incubator/external-storage/ ....  for the dynamic provisioner, should we be using the canonical upstream ?

**Comment by afbjorklund** [comment]
Yikes, `This branch is 19 commits ahead, 1480 commits behind kubernetes-incubator:master.`

On the other hand, it seems to have moved (or at least the `lib` directory, and the "leaderelection")

https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner

https://github.com/kubernetes/client-go/tree/master/tools/leaderelection

----
Definitely something to consider, when updating to the new CSI standard... ? (for 1.13 and beyond)

https://github.com/kubernetes-csi/drivers/tree/master/pkg/hostpath

**Comment by tstromberg** [comment]
Sounds good to me! I'll happily approve a PR that does this.

**Comment by jayunit100** [comment]
The move to CSI might be a better way to do this... given that external-storage is deprecated.

**Comment by tstromberg** [comment]
This is now done in minikube's source code:

https://github.com/kubernetes/minikube/blob/master/pkg/storage/storage_provisioner.go

I believe that the `gcr.io/k8s-minikube/storage-provisioner` Docker image needs to rebuilt using this updated source code for this to be fully complete.

**Comment by medyagh** [comment]
We still need to do this issue ! I would be happy to review any prototype with https://github.com/rancher/local-path-provisioner

**Comment by priyawadhwa** [comment]
I'm going to close this issue, as it seems that this has been done and the storage provisioner image has been upgraded since.

If anyone thinks this issue should remain open , please reopen this issue by including /reopen in your comment.
