### ISSUE TITLE
none: minikube delete should call kubeadm reset

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3637]
This would allow the none driver to mostly clean up after itself.

**Comment by afbjorklund** [comment]
Sounds like a good idea! For some reason, that API is missing from the bootstrapper...

It goes straight for `DeleteHost`, which of course is rather useless without any host.

``` go
func (d *Driver) Remove() error {
        return nil
}
```

Any good idea, what rhymes with `StartCluster` (and where StopCluster is misleading) ?

Maybe `DeleteCluster` ? That way it would match StartHost/DeleteHost for naming.

**Comment by tstromberg** [comment]
DeleteCluster sounds good to me.
