### ISSUE TITLE
Add `minikube create` CLI command

### ISSUE THREAD

**Issue by janslow** [kubernetes/minikube#364]
It would be useful to have separate commands for creating a new minikube machine and starting an existing one.

For example, by copying the `docker-machine` CLI, having a `minikube create` command which is used to create a new machine and accepts configuration arguments (such as CPU/memory options) and a `minikube start` command which just starts an existing stopped machine.

This would make it obvious when a machine does not already exist, so a user knows that they need to set up port forwarding/NAT configuration etc. (if desired), as opposed to minikube silently creating a new machine and the user not knowing a new one has been created until they realise they need to reapply VirtualBox configuration.

**Comment by dlorenc** [comment]
Could you explain a little more about what configuration settings you create in Virtualbox before the VM gets started?

**Comment by janslow** [comment]
Most commonly I use NAT port forwarding from a k8s service node port to my host machine, both because I have a development SSL certificate for my host machine and so I can access it from other development machines.

Secondly, changing the NAT CIDR to something other than 10.0.2.0/24, as that is a subnet we run internal services on within our organisation, but is the default subnet for VirtualBox NAT cards in slot 1, so it's easier to change it to a less common subnet (however, this has to be changed per VM, whilst it is powered off).

The final VM modification I've used is changing the host-only interface, so that I can use a specific browser running in a VM to communicate with a server running in a k8s cluster. I now avoid this by port forwarding to the host machine, so this is no longer something I have to do.

Of course, this can all be done manually checking if the VM exists before starting, but it's a bit of a pain compared to the docker-machine workflow of explicitly creating a machine before starting it.

One final point is that I have also been caught out by running `minikube start --memory=X` when a machine already exists (so the flag is silently ignored). This would not be an issue if there were separate commands, as a command like `--memory` would not be present on the `start` command (unless the start command could change the memory of an existing machine).

**Comment by janslow** [comment]
Also, this would be a lot closer to the workflow of Docker Machine, which I expect is a fairly commonly used tool by minikube/k8s users

**Comment by ereOn** [comment]
Any news on this ?

I personally like that idea, mostly because it would allow us to define the number of CPUs used by the virtual machine.

**Comment by budhrg** [comment]
Any update on it @r2d4 @aaron-prindle

**Comment by r2d4** [comment]
I'm open to the idea, but we'd need a full design proposal first before someone starts to work on it.  I wouldn't be able to implement it myself, but I'd happily review any proposal and implementations.

**Comment by mrbobbytables** [comment]
I bumped into a use case where this functionality would be quite helpful. With regard to virtualbox, I wanted to set a parameter via `VBoxManage modifyvm` (specifically  `--natdnshostresolver1 on`). However, this can only be changed when the VM is in a stopped state. 

Currently you must start the instance, stop the instance, change the setting, then start it again. 

Being able to create the system without powering it on would allow me to run the `VBoxManage modifyvm` command without having to turn it off and back on again.
