### ISSUE TITLE
Add WAIT cmd implementation.

### ISSUE THREAD

**Issue by Zyqsempai** [kubernetes/minikube#3644]
**Is this a FEATURE REQUEST** 

I will be glad to implement `wait` command in minikube.
Do we have any objections? Or problems related to this topic?

**Comment by Zyqsempai** [comment]
If it's okey and we are good to go, assign it on me;)

**Comment by afbjorklund** [comment]
@Zyqsempai : What is a "wait" command ? Do you have a PR to go with it ?

https://github.com/kubernetes/minikube/tree/master/docs/contributors

**Comment by Zyqsempai** [comment]
My bad guys. Opened by mistake. Sorry.
