### ISSUE TITLE
Add automatic download of kubectl

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#3645]
Currently we are pushing the install of `kubectl` to the user, with varying results (and long docs).

```
========================================
kubectl could not be found on your path. kubectl is a requirement for using minikube
To install kubectl, please run the following:

curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.13.3/bin/linux/amd64/kubectl && chmod +x kubectl && sudo cp kubectl /usr/local/bin/ && rm kubectl

To disable this message, run the following:

minikube config set WantKubectlDownloadMsg false
========================================
```

It would be more user-friendly to offer a wrapper to download and start the proper os/arch binary:

``` console
$ minikube kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

This also picks the right version (eventually), and offers to use more than one version.

If the user prefers to install and use their own `kubectl`, they just avoid this command...

**Comment by afbjorklund** [comment]
@tstromberg

**Comment by afbjorklund** [comment]
Note that I didn't have to do anything above, just wait a bit - while the `kubectl`download happened.

i.e. I didn't have "kubectl" installed anywhere when I ran the command, yet it completed successfully.

**Comment by nzoueidi** [comment]
I would like to work on this issue.

**Comment by RA489** [comment]
@afbjorklund Is it still open ? if yes i would like to help.

**Comment by afbjorklund** [comment]
@RA489 : I want to make it download the current kubernetes version (instead of the default), but other than that I think #3646 is more or less what is needed ? Perhaps clean up the duplicated code a bit, test on Win.

**Comment by afbjorklund** [comment]
Updated the implementation, now it has some better download information and exit code...
Also respecting the current profile kubernetes version (if any) and removed code duplication.
