### ISSUE TITLE
Disable audio driver in VirtualBox

### ISSUE THREAD

**Issue by terrywang** [kubernetes/minikube#3664]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report (in fact, enhancement request)

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.33.1
- **OS** (e.g. from /etc/os-release): 
NAME=Buildroot
VERSION=2018.05
ID=buildroot
VERSION_ID=2018.05
PRETTY_NAME="Buildroot 2018.05"
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.33.1.iso
- **Install tools**: `brew cask install minikube`
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver:"; 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
`minikube start` creates new VirtualBox VM with audio support enabled which is NOT required for minikube use case, it is considered extra emulation (hardware - PCI device) overhead.

No kernel module loaded for the device (could be the way the custom minikube kernel is built, device driver could be compiled as modules). However, the device is still emulated ->  as shown below as `00:05.0` in BDF notation form.

```
$ uname -a
Linux minikube 4.15.0 #1 SMP Fri Jan 18 22:39:33 UTC 2019 x86_64 GNU/Linux
$ lspci -k
00:00.0 Class 0600: 8086:1237
00:03.0 Class 0200: 1af4:1000 virtio-pci
00:02.0 Class 0300: 80ee:beef
00:05.0 Class 0401: 8086:2415
00:08.0 Class 0200: 1af4:1000 virtio-pci
00:0d.0 Class 0106: 8086:2829 ahci
00:01.0 Class 0601: 8086:7000
00:04.0 Class 0880: 80ee:cafe vboxguest
00:07.0 Class 0680: 8086:7113
```

**What you expected to happen**:
When `minikube start` creates new VirtualBox VMs, Audio support should be disabled (`--audio none`.

**How to reproduce it** (as minimally and precisely as possible):
`minikube start` on macOS or Linux, VirtualBox as VM driver.

In VirtualBox GUI, for the minikube VM, Settings - Audio, `Enable Audio` is ticked. Host Audio type `CoreAudio`, controller type `ICH AC97`.

The same can be checked by using `VBoxManage showvminfo minikube`

VBoxManage showvminfo minikube
```bash
...
Audio:                       enabled (Driver: CoreAudio, Controller: AC97, Codec: STAC9700)
Audio playback:              disabled
Audio capture:               disabled
...
```

Audio support can be disabled by using `VBoxManage modifyvm minikube --audio none`

**Output of `minikube logs` (if applicable)**: NA

**Anything else do we need to know**:

I was able locate the relevant code from the repo [`vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go`](https://github.com/kubernetes/minikube/blob/master/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go), attempted to add 1 line of code

```go
# git diff HEAD^ HEAD
diff --git a/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go b/vendor/github.com/docker/machine/driver
index 3d79e4e..d26bcd1 100644
--- a/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go
+++ b/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go
@@ -400,6 +400,7 @@ func (d *Driver) CreateVM() error {
                "--largepages", "on",
                "--vtxvpid", "on",
                "--accelerate3d", "off",
+               "--audio", "none",
                "--boot1", "dvd"}

        if runtime.GOOS == "windows" && runtime.GOARCH == "386" {
``` 

Build the binary for macOS (using `make cross` on Linux), was able to start a new VM but `--audio none` didn't seem to take effect.

More digging pointed me to the following block

```go
	if err := d.vbm(modifyFlags...); err != nil {
		return err
	}
```
and [`vbm.go`](https://github.com/kubernetes/minikube/blob/master/vendor/github.com/docker/machine/drivers/virtualbox/vbm.go). New to Go (hello world level lol) so it's hard for me to figure all out in minutes, will appreciate some guidance as I want to help improve this bit.

> NOTE: The same practice was widely adopted when making Vagrant base boxes. Disable any hardware which is not required for running headless VMs.

**Comment by afbjorklund** [comment]
While this sounds like a reasonable change, it should be handled upstream in libmachine.
The suggested patch looks OK, so if you can make that into a PR that would be great!

Possibly the same change should be made to our in-tree KVM driver ("kvm2"), haven't looked.

**Comment by terrywang** [comment]
Build again on my home NAS and it seemed to work fine, not sure what happened last time I ran `make cross` on an EC2 instance.

> NOTE: I added some flavour to `minikube version` just to make sure it uses the correct binary to create new VirtualBox VM.

```
 ./minikube-darwin-amd64 start
😄  minikube v0.33.1 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 181.48 MB / 181.48 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.109
🐳  Configuring Docker as your container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.13.3
💾  Downloading kubelet v1.13.3
🚜  Pulling images used by Kubernetes v1.13.3 ...
🚀  Launching Kubernetes v1.13.3 using kubeadm ...
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
```
The minikube VM created now is with Audio support disabled, great. No more unnecessary emulation overhead.

```bash
Name:                        minikube
Groups:                      /
Guest OS:                    Linux 2.6 / 3.x / 4.x (64-bit)
...
Memory size                  2048MB
CPU exec cap:                100%
HPET:                        enabled
CPUProfile:                  host
Chipset:                     piix3
Firmware:                    BIOS
Number of CPUs:              2
PAE:                         enabled
Long Mode:                   enabled
Triple Fault Reset:          disabled
APIC:                        enabled
Nested VT-x/AMD-V:           disabled

3D Acceleration:             disabled
2D Video Acceleration:       disabled
...
Audio:                       disabled
Audio playback:              disabled
Audio capture:               disabled
```

Will go ahead, follow the process to create a PR.

**Comment by medyagh** [comment]
I wonder if this PR code in vendor folder was removed after switching to go.mod 
Anyways we shouldn't have had code in vendor folder but third_party

**Comment by tstromberg** [comment]
Closing as the issue has to be handled upstream in `libmachine`.

**Comment by afbjorklund** [comment]
@terrywang : The code is located here:
https://github.com/docker/machine/blob/master/drivers/virtualbox/virtualbox.go#L380_L403
