### ISSUE TITLE
kubeadm init: wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by akmabrouk** [kubernetes/minikube#3668]
My setup is:
latest virtualbox installed on command line on ubuntu 16.04 under vmware workstation
latest minikube installed
latest kubectl installed

# minikube start
Starting local Kubernetes v1.13.2 cluster...
Starting VM...
Downloading Minikube ISO
181.48 MB / 181.48 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
E0213 19:33:46.698223 13508 start.go:376] Error starting cluster: kubeadm init:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI

[init] Using Kubernetes version: v1.13.2
[preflight] Running pre-flight checks
[WARNING Swap]: running with swap on is not supported. Please disable swap
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'

: wait: remote command exited without exit status or exit signal

minikube failed :( exiting with error code 1

Can anyone help please? Much appreciated

**Comment by tstromberg** [comment]
So, something killed kubeadm. Maybe "minikube ssh dmesg" might reveal it?

Any reason why you are running two layers of virtualization? It's both slightly exotic, and error-prone to do so. I feel like you would get better results running minikube on Windows.

**Comment by akmabrouk** [comment]
Thank you tstromberg, Maybe I am not sure if minikube is to be setup it should be on linux on a baremetal rather than the VM. Is this how it should be? I can it setup  on windows but I have most of my work on ubuntu on vmware workstation.

**Comment by tstromberg** [comment]
@akmabrouk - It seems like what you are doing should work, but for some reason it crashed. Do you mind trying with minikube v0.34. If it fails, please attach the output of `minikube ssh dmesg` and `minikube logs`. Thanks!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
