### ISSUE TITLE
Use minikube on my ubuntu vm on virtualbox

### ISSUE THREAD

**Issue by akmabrouk** [kubernetes/minikube#3685]
Hi
Is it possible to use minikube on ubuntu vm on virtualbox and does this mean I still need to install  another virualbox for linux which means 2 virtuabox layers? When it is said: "minikube on linux" do they mean linux installed on a baremetal not a VM? I am kind of confused here.

Your guidance would be much appreciated. Thanks you

**Comment by afbjorklund** [comment]
What are you trying to do ? Do you have something else in this ubuntu VM, like a favorite text editor or something like that. Or why don't you install minikube on the host that is running virtualbox ?

There's currently some issues with running nested virtualization, so it is better off avoided if possible. If you prefer to install the VM yourself, you could install `kubeadm` directly rather than use `minikube`.

**Comment by tstromberg** [comment]
When the documentation says `minikube on Linux`, it assumes bare metal. VirtualBox 6.0 however does have some support for nested VM's. Perhaps you could try it and let us know how it works?

**Comment by ihor-sviziev** [comment]
Hi,

I have the same issue. I have Win 10 as a host, virtual machine with Ubuntu where right now I have all needed environment for development (IDE) + check outed projects + docker, and  All needed servers right now running using docker-compose. I'd like to try move my services to kubernetes, so locally I need minikube.

Is it ok to ise vm driver "none" in this case? or it's better to run minikube on win10 and connect to it from 2nd virtual machine?

**Comment by tstromberg** [comment]
In a nutshell, avoid nested VM's when possible. If you can just run `minikube` directly on your host, it will work much better than running it from inside a VM.

If you must run minikube in a VM, consider using `--vm-driver=none`. Thanks!

**Comment by rnmulchandani** [comment]
Hello Everyone,

I have Windows 10 host. On top of it, I am running Ubuntu 18.04 VM using Hyper-V. I have all my development set up on this Ubuntu 18.04 VM. 
I am trying to install Minikube on this Ubutun VM which is running in Hyper-V.
When I run command `sudo minikube start --vm-driver=none` it gets stuck at downloading stuck at download kubeadm v1.15.3.
Please help me with this. The reason behind running on VM is I have all my development environment set up.

**Comment by asoltesz** [comment]
@rnmulchandani The Docker driver may be of help for this situation. That runs Minikube in Docker, so it sould work OK in your VM.
