### ISSUE TITLE
Have CI build kvm2 in a way that works with old Ubuntu releases

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3689]
```
jenkins@ubuntu-testing:~$ docker-machine-driver-kvm2
docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt-lxc.so.0: version `LIBVIRT_LXC_2.0.0' not found (required by docker-machine-driver-kvm2)
docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_2.2.0' not found (required by docker-machine-driver-kvm2)
docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_3.0.0' not found (required by docker-machine-driver-kvm2)
docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_1.3.3' not found (required by docker-machine-driver-kvm2)
docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_2.0.0' not found (required by docker-machine-driver-kvm2)
```

**Comment by tstromberg** [comment]
The symptom here is:

`E0215 11:44:27.175949   26338 start.go:205] Error starting host: Error creating new host: dial tcp: missing address.`

AKA #3206

**Comment by afbjorklund** [comment]
Technically `debian:jessie` would work too, but vox populi seems to be `ubuntu:16.04`.

I think we can just "borrow" the build procedure from `docker-machine-driver-kvm`, no ?

* https://github.com/dhiltgen/docker-machine-kvm/blob/master/Makefile#L10

* https://github.com/dhiltgen/docker-machine-kvm/blob/master/Dockerfile.ubuntu16.04

**Comment by afbjorklund** [comment]
Actually that Makefile/Dockerfile was quite horrible, so we should write our own...

It builds it inside the container image, and deletes/rebuilds everything every time.

**Comment by gbraad** [comment]
Rebuild is expected from CI. Caching in that case is a no-no. Personally
also not for local builds...

**Comment by afbjorklund** [comment]
It rebuild the build machine every time... That is only needed when changing OS versions and Go versions, not every commit.

**Comment by tstromberg** [comment]
Building from the oldest non-EOL'd Ubuntu version seems reasonable to me. At the moment, that would be Ubuntu 14.05, but iEOL's in April, so I would rather us just start with 16.04.

The actual technical details of the Makefile aren't that important to me, so long as we are able to build it in under 10 minutes.

**Comment by afbjorklund** [comment]
@tstromberg : It takes around 30 seconds to build, on my laptop.

Slightly longer if we cannot store the docker image between runs ?
For now I just put it "next to" the already existing `buildroot-image`:

``` Makefile
REGISTRY?=gcr.io/k8s-minikube
...
ISO_BUILD_IMAGE ?= $(REGISTRY)/buildroot-image
KVM_BUILD_IMAGE ?= $(REGISTRY)/kvm-build-image
```

See [Dockerfile](https://github.com/kubernetes/minikube/blob/f07a8739caf1df7afae7a6e05a998ecfa603692a/installers/linux/Dockerfile) (`ubuntu:16.04` + libvirt-dev curl git gcc + golang)

**Comment by waja** [comment]
This issue was fixed in which way?
