### ISSUE TITLE
Support for alpha APIs

### ISSUE THREAD

**Issue by vishh** [kubernetes/minikube#369]
With the latest version of minikube, all alpha APIs aren't supported. 

```shell
error validating data: API version "apps/v1alpha1" isn't supported, only supports API versions ["componentconfig/v1alpha1" "batch/v1" "autoscaling/v1" "authorization.k8s.io/v1beta1" "v1" "metrics/v1alpha1" "extensions/v1beta1"];
```

Given that minikube is a dev tool, I'd prefer enabling all APIs by default.

**Comment by jimmidyson** [comment]
Is there a nice flag to enable all APIs at once or do they each need to be specified?

**Comment by jimmidyson** [comment]
Ah we can do this in localkube instead.
