### ISSUE TITLE
Support config file for minikube options

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#371]
Add a `minikube config` subcommand that allows user to specify minikube config & reused across start/stop/delete.

**Comment by dlorenc** [comment]
This'll be a good starter project for @r2d4.

**Comment by r2d4** [comment]
@jimmidyson how might you imagine this working?  Do you think it should be analogous to docker-machine like suggested in #370 or something simpler such as passing in a --config-path or env variable?

**Comment by r2d4** [comment]
We merged the `minikube config get/set/unset` PR a few days ago (ref #545).  Not sure if this exactly addressed this issue but feel free to reopen if you had something else in mind.  

Additionally, I'm planning to document all the current configuration options (config file, env vars, flags) for 0.10.0.

**Comment by eljefedelrodeodeljefe** [comment]
@r2d4 I think this rather referred to writing a yaml file to the filesystem. If this is already possible, the docs are not indicating it , as far as I can see.

**Comment by r2d4** [comment]
@eljefedelrodeodeljefe the `minikube config` command writes configuration to `~/.minikube/config/config.json`.  You can edit this file directly if you want.

**Comment by eljefedelrodeodeljefe** [comment]
is it possible to write and load it in your current working directory? Otherwise I'd kindly suggest it as feature, since one could version control it. Say in demo applications or tools on top of minikube.

**Comment by ermik** [comment]
@r2d4 where is the full list of config options? I'm having helluva lot of trouble trying to get RBAC and Istio up and running...
