### ISSUE TITLE
Kube Proxy not starting with 0.34.1

### ISSUE THREAD

**Issue by BenHall** [kubernetes/minikube#3710]
Trying to upgrade Katacoda to use the new 0.34.1 release at https://www.katacoda.com/courses/kubernetes/launch-single-node-cluster

This uses the no vm driver approach. It gets to "Waiting for kube-proxy to come back up ..." and then times out.

The odd thing is, it looks like the node has started.
```
$ kubectl get nodes
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     <none>    5s        v1.13.3
```

Steps to reproduce:

```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.34.1/minikube-linux-amd64 && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube
minikube config unset bootstrapper
minikube version
minikube start
```

**Comment by afbjorklund** [comment]
How far does it get, with the `kube-proxy' restart ? Do you have a log somewhere ?

**Comment by BenHall** [comment]
It looks like it was due to a left over minikube installation. A clean install did the job! Sorry for the problem,
