### ISSUE TITLE
`Minikube VM` is missing a Netfilter `xt_socket` module required for Transparent Proxying (TPROXY)

### ISSUE THREAD

**Issue by yskopets** [kubernetes/minikube#3713]
Transparent Proxying (TPROXY) is a feature of Linux Kernel that is used by Service Meshes, such as Istio or Kong, to "intercept" traffic in a side car process.

According to [Kernel documentation](https://www.kernel.org/doc/Documentation/networking/tproxy.txt), Transparent Proxying requires 2 `Netfilter` modules to be present:
1. `NETFILTER_XT_TARGET_TPROXY`
2. `NETFILTER_XT_MATCH_SOCKET`

At the moment, `Minikube VM` comes only with `NETFILTER_XT_TARGET_TPROXY ` module and is missing `NETFILTER_XT_MATCH_SOCKET`.

### How to reproduce

1. `minikube ssh`
2. `sudo iptables -t mangle -N TPROXY_ISSUE`
3. `sudo iptables -t mangle -A TPROXY_ISSUE -p tcp -m socket -j RETURN`

The last command will fail with an error message `iptables: No chain/target/match by that name.`

### Reproducible on

v0.33.1

**Comment by yskopets** [comment]
I've prepared a PR to fix it - https://github.com/kubernetes/minikube/pull/3712

**Comment by afbjorklund** [comment]
I think providing support for Istio is on the wish list, so if the kernel config change fixes that...

https://istio.io/docs/setup/kubernetes/

For some reason this setting was removed with the kernel upgrade, but doesn't say why ?

https://github.com/kubernetes/minikube/commit/3c6a8092538ab7e663343b55c1b71977d1d53ebe#diff-d1db7663ff9bd132f85fefa0f4ebdc3aL187

**Comment by afbjorklund** [comment]
We will add this to the next ISO build/release. Hopefully it doesn't break anything else.

**Comment by yskopets** [comment]
Thank you!
