### ISSUE TITLE
Support adding resource manifests to import on startup

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#372]
Adding a new string slice flag such as `--manifest` (or something else that makes sense) to create resources from manifests on startup. The flag should accept a local file, directory or URL, just like `kubectl create -f` does.

This is especially useful for demo environments, as well as app developers that would allow users to spin up a local environment pre-configured with apps from manifests.

**Comment by dstroot** [comment]
This is a very cool idea.

**Comment by jimmidyson** [comment]
In combo with #374 I can see this being really useful for a lot of things.

**Comment by dlorenc** [comment]
This is a cool idea but I'm slightly weary of baking too much of kubectl into minikube. Maybe we could shell out to kubectl after?

**Comment by jimmidyson** [comment]
Agreed.

**Comment by dlorenc** [comment]
We sort of have this now with the support for custom addons, but you have to specify that your yamls are `kubernetes.io/cluster-service: "true"` for the addon manager to pick them up.

**Comment by dlorenc** [comment]
I think we can technically do this now with the minikube homedir addons feature. Closing.
