### ISSUE TITLE
Make virtualbox DNS settings configurable

### ISSUE THREAD

**Issue by chancez** [kubernetes/minikube#3720]
#3453 change the default behavior and as a result, I believe I am seeing breakage as a result. If these items were configurable I believe it would allow me to more easily validate the issue is related, and bypass the current values that are problematic.

As it it is currently, it seems even if I attempt to change the value of this setting, minikube will overwrite it.

**Comment by taravkov** [comment]
Agree, please make them configurable.

**Comment by cvila84** [comment]
Agree, as activating the DNS proxy (through HostDNSResolver=true or DNSProxy=true) on NAT sometimes lead to silent crashes which prevents any DNS requests to be done (https://github.com/kubernetes/minikube/issues/3606#issuecomment-505014348)
