### ISSUE TITLE
failed to pull image k8s.gcr.io/kube-apiserver:v1.13.3: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by JayneJacobs** [kubernetes/minikube#3722]
[minikube start ] The exact command used, including all options and flags.

minikube v0.34.1 on darwin (amd64)
Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
 "minikube" IP address is 192.168.99.100
 Configuring Docker as the container runtime ...
Preparing Kubernetes environment ...
 Pulling images required by Kubernetes v1.13.3 ...
 Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout: 
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.13.3": output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
: Process exited with status 1
Launching Kubernetes v1.13.3 using kubeadm ... 
Error starting cluster: kubeadm init: 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI 

[init] Using Kubernetes version: v1.13.3
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING Swap]: running with swap on is not supported. Please disable swap
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.13.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.13.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.13.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.13.3: output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.2.24: output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.2.6: output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

: Process exited with status 1

Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
 https://github.com/kubernetes/minikube/issues/new
PASML-335382:~ jjacob151$ kubeadm config images pull ] The full output of the command that failed
[Kubernetes v1.13.3 minikube v0.34.1 ] The version of minikube used
[ macOS High Sierra 10.13.6] The operating system name and version used
[ ] The output of `minikube logs`, if applicable.

Please write what's happening in minikube versus your expectations below this line:
--> It does not work on my mac
 Process exited with status 1

**Comment by tstromberg** [comment]
Hello Jayne! I'm sorry to hear that it isn't working. Please include:

[ ] The exact command used, including all options and flags.
[ ] The full output of the command that failed
[ ] The version of minikube used
[ ] The operating system name and version used
[ ] The output of `minikube logs`, if applicable.

Thanks!

**Comment by JayneJacobs** [comment]
I think I did that above

**Comment by JayneJacobs** [comment]
[minikube start ] The exact command used, including all options and flags.
[Kubernetes v1.13.3 minikube v0.34.1 ] The version of minikube used
[ macOS High Sierra 10.13.6] The operating system name and version used
[ ] The output of `minikube logs`, if applicable. (sorry where are these?)

**Comment by tstromberg** [comment]
Sorry, I can see that our new issue template is confusing. Most of the initial issue text was hidden (fixed).

Anyways - I've attempted to document a solution here: 

https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md#x509-certificate-signed-by-unknown-authority

Do you mind checking it out? I'd like to improve the text to the point to where it's something we can automatically recommend to our users. Thank you!

**Comment by JayneJacobs** [comment]
Thank you, I did this without the proxy and all is well.

**Comment by RunningDogLG** [comment]
Is this problem solved？

**Comment by tstromberg** [comment]
@RunningDogLG - It sounds like it. If you are running into this, please check the instructions at https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md#x509-certificate-signed-by-unknown-authority

**Comment by tstromberg** [comment]
I'm going to leave this open until we can update the error messages so that it leads folks directly to the documentation.

**Comment by JayneJacobs** [comment]
Thank you
