### ISSUE TITLE
Emoji/icons are too large on my terminal

### ISSUE THREAD

**Issue by jsravn** [kubernetes/minikube#3724]
![screenshot from 2019-02-20 15-39-17](https://user-images.githubusercontent.com/522123/53103531-b77d1200-3525-11e9-824d-9716e13c0cba.png)

Please fix this, or remove the icons. It makes minikube unusable for me recently. On gnome-terminal 3.30.2.

**Comment by tstromberg** [comment]
Ouch! That looks very painful, and completely unintentional. Terminal applications do not have the ability to control font sizes, but we do offer a way to turn off this feature:

https://github.com/kubernetes/minikube/blob/master/docs/env_vars.md#example-disabling-emoji
What distribution of Linux is this on, and what version of it?

I thought I've seen everything. I did find one mention of someone running arch linux experiencing this in another application:
https://www.reddit.com/r/archlinux/comments/81wyq2/giant_emoji_in_terminal/

**Comment by afbjorklund** [comment]
You can use `MINIKUBE_IN_COLOR=false` to disable color output (including emojis)

Or maybe just increase your font size to 180pt or whatever would match those icons 😀

**Comment by jsravn** [comment]
Haha, thanks guys. It was pretty funny when I saw this the first time. A giant hand showed up on my terminal (the wait icon I think?).

It is indeed the bitmap scaling which I've disabled, since it can make bitmap fonts blurry. I don't think I've used bitmap fonts in a while though, so I may just enable that again.

**Comment by shanesveller** [comment]
Guess I'm setting that environment variable for the rest of time. Not a fan of the new emoji in the output. Would be really, really nice to not sacrifice all color to avoid that particular aesthetic.

**Comment by afbjorklund** [comment]
AFAIK, minikube doesn't use any color in the output ? Maybe we should split the configuration variables, one for color (text) and one for emoji (icons). That way you could have colored text output - without emojis.

Note that on older platforms the emoji will be shown in black-and-white, so there's no color here...
![minikube-start](https://user-images.githubusercontent.com/10364051/53223545-fae49700-3671-11e9-846e-d69da18adc7b.png)

**Comment by intelfx** [comment]
Who got the clever idea of adding emoji into the output, anyway?..

**Comment by afbjorklund** [comment]
@intelfx: There is an ASCII version available as well.
```
$ export MINIKUBE_IN_COLOR=false
$ minikube start --container-runtime=cri-o --cache-images
o   minikube v0.34.1 on linux (amd64)
$   Caching images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.99.100
-   Configuring CRI-O as the container runtime ...
-   Preparing Kubernetes environment ...
:   Waiting for image caching to complete ...
-   Pulling images required by Kubernetes v1.13.3 ...
-   Launching Kubernetes v1.13.3 using kubeadm ... 
-   Configuring cluster permissions ...
-   Verifying component health .....
+   kubectl is now configured to use "minikube"
=   Done! Thank you for using minikube!
```

The main suggestion here was to split "color" and "emoji" configuration into two variables...

**Comment by afbjorklund** [comment]
Did so in #3773

**Comment by huguesalary** [comment]
What is the meaning of those ASCII symbols (and emojis...)? This seems quite random and unusual for a command line tool.

**Comment by jakebasile** [comment]
These symbols provide no meaning whatsoever to an end user, and should be removed entirely or an option provided to disable them. In the meantime, I'll probably alias `minikube` to something that cleans up this inane output.

**Comment by DarinDouglass** [comment]
I agree with @jakebasile, these emotes feel arbitrary and don't add any real meaning.

I understand the desire for some additional severity info (i.e. `info`, `debug`, etc) but the current prefixes don't provide any _additional_ meaning. In fact they're usually redundant: a whale emote when talking about Docker? A running man emote when talking about "running" the vm?

At best they're redundant information. At worst they're eyesores added to _every_ line.

**Comment by intelfx** [comment]
Seconded @jakebasile and @DarinDouglass.

These emotes are not just redundant information, they're _misinformation_ because they are _not_ related to the text content in any meaningful way (they represent neither severity nor category of the message). That, and they severely clutter the text output, distracting the operator (and, if you are using sophisticated color schemes like Solarized, the issue gets further exaggerated because these emojis will be _brighter_ than the text).

Please either provide an option to completely disable _both_ emoji and ASCII prefixes without impacting the rest of the tool's functionality, or (better) replace them with something _meaningful_ (e. g. prefixes tied to the message severity).

**Comment by afbjorklund** [comment]
Should probably open a _new_ issue, rather than continuing on this one (on icon size). But here we are....

The prefixes are _supposed_ to have a meaning, but like you mention they are are mostly focused on style at the moment. Maybe we should indeed add a severity/category before the (optional) style emoji/prefix.

For reference, here is an example of the same styles when printed out as text:

```
[happy] minikube v1.0.0 on linux (amd64)
[caching] Downloading Kubernetes v1.14.0 images in the background ...
[tip] Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
[running] Re-using the currently running virtualbox VM for "minikube" ...
[waiting] Waiting for SSH access ...
[connectivity] "minikube" IP address is 192.168.99.103
[CRI-O] Configuring CRI-O as the container runtime ...
[CRI-O] Version of container runtime is 1.13.1
[waiting] Waiting for image downloads to complete ...
[copying] Preparing Kubernetes environment ...
[pulling] Pulling images required by Kubernetes v1.14.0 ...
[restarting] Relaunching Kubernetes v1.14.0 using kubeadm ... 
[waiting-pods] Waiting for pods: apiserver etcd scheduler controller
[reconfiguring] Updating kube-proxy configuration ...
[verifying-noline] Verifying component health .....
[kubectl] kubectl is now configured to use "minikube"
[ready] Done! Thank you for using minikube!
```

They could probably be grouped further, a bit too many when not displaying in "style".

In the meantime we can just make it opt-out, I'm thinking a `MINIKUBE_NO_STYLE` environment variable that will just disable the prefix altogether and just show the text. Maybe revisit with severity/category later.

**Comment by DarinDouglass** [comment]
@afbjorklund You're right, it probably should have gone into a new issue; that's my bad.

**Comment by afbjorklund** [comment]
As for the original issue, I'm not sure if there _is_ a way to detect that bitmap scaling has been turned off ?

**Comment by afbjorklund** [comment]
Please open a new issue about making the output format acceptable, not going to disable the style.

@tstromberg suggestion:
```
- top level item
  * second level item
! error/warning item
```

**Comment by jakebasile** [comment]
Created https://github.com/kubernetes/minikube/issues/4157

**Comment by tstromberg** [comment]
Thank you for sharing your experience. It's been a good one to learn from.

In the end, I don't believe we should implement detection for the too-large-emoji issue, as it isn't exactly trivial. If you run into this, please set `MINIKUBE_IN_STYLE=0` in your environment, or a non-color `TERM` setting.

Thank you again for raising this issue.
