### ISSUE TITLE
minikube crashed

### ISSUE THREAD

**Issue by Kabiche** [kubernetes/minikube#3728]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

**Comment by shashivj** [comment]
Did a new install of minikube on Mac, when trying to start, it crashed, here are the steps,
f018982d6238:~ jeripots$ minikube start
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.14.0
💾  Downloading kubelet v1.14.0
🚜  Pulling images required by Kubernetes v1.14.0 ...
🚀  Launching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver
💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition
😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objects passed to apply
    error: no objects passed to apply
    error: no objects passed to apply

**Comment by SujitNandan** [comment]
sudo minikube start -p WithoutVM --vm-driver=none
😄  minikube v1.2.0 on linux (amd64)
🔄  Restarting existing none VM for "WithoutVM" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.7
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new


uname -a 
Linux SLT-LTP-163 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

cat /etc/issue
Ubuntu 18.04.2 LTS \n \l
minikube version: v1.2.0

Before this i tried to install JenkinsX in minikube but midway Api server failed to respond and even on restarting minikube api-server in not running
