### ISSUE TITLE
Add option to skip VM driver PreCreateCheck

### ISSUE THREAD

**Issue by thewilli** [kubernetes/minikube#3729]
**Environment**: Windows 10 Version 10.0.16299.904
**Minikube**: v0.34.1

The supported drivers provide a `PreCreateCheck()` method that is [invoked](https://github.com/kubernetes/minikube/blob/9cf86a7302bcc9c12974918be18d5cc337e442c0/pkg/minikube/machine/client.go#L172) by minikube in order to ensure the driver works properly and its prerequisites are fulfiled.
Unfortunately those prerequisites are not without flaws. The one implemented in the [hyperv driver](https://github.com/docker/machine/blob/5bc065d6eb72a0fccaf04e162ff3e723b7dc5b09/drivers/hyperv/hyperv.go#L161) invokes some [PowerShell](https://github.com/docker/machine/blob/5bc065d6eb72a0fccaf04e162ff3e723b7dc5b09/drivers/hyperv/powershell.go#L88
) as part of its checks. The one listed before checks if the user is part of the Hyper-V Administrators group. While this check is a good idea, it does not work if the computer joined a domain and cannot reach its Domain Controller. Therefore, when e.g. working in Home Office or in the train without network connectivity at all, I cannot use minikube in this setup.

Please add an option to skip (or ignore failing) `PreCreateCheck`s.

The minishift project is doing [something similar](https://github.com/minishift/minishift/issues/1541#issuecomment-335749702) specific to hyperv, but I'd propose to just add a general `I-know-what-I'm-doing`-option to continue when those checks failed.

**Comment by tstromberg** [comment]
This sounds like a great idea, and I would be happy to review any PR that implements it.

**Comment by thewilli** [comment]
> This sounds like a great idea, and I would be happy to review any PR that implements it.

@tstromberg okay, I'm on it. One question, though: I added a new configuration parameter to `Cobra`. This parameter, `ignore-vm-driver-precheck` (pretty long but self-explanatory) need to be accessed [here](https://github.com/kubernetes/minikube/blob/8cae13f5d4315e53434c4f4cdf74b0e747419fdc/pkg/minikube/machine/client.go#L172) (package *k8s.io/minikube/pkg/minikube/machine*). I have to use `Viper` in order to access the configuration parameter to not break the existing interfaces - there's no access to the corresponding config objects there.

My approach works, but I can't define the configurational key (i.e. flag name) next to [the others](https://github.com/kubernetes/minikube/blob/8cae13f5d4315e53434c4f4cdf74b0e747419fdc/cmd/minikube/cmd/start.go#L57-L87). This would lead to circular imports.

Is there any other location to put this constant, or do you have another idea on how to solve this?

**Comment by tstromberg** [comment]
Flags should only be referenced in the main package, so I think we'll need to pass it into Create somehow. I agree that it isn't very straightforward: I can't think of a way to do this without modifying `libmachine` to accept a new value in the `Host` struct, or adding a specific flag to the hyperv driver.

Here is an example of the latter approach: https://github.com/kubernetes/minikube/pull/3734

To mimic this particular case, we would need to modify the upstream hyperv driver we use: 
https://github.com/machine-drivers/machine/blob/master/drivers/hyperv/hyperv.go

**Comment by priyawadhwa** [comment]
@thewilli are you still interested in implementing this issue?
