### ISSUE TITLE
Support autoupdate rather than just update notification

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#373]
Implemented this in minishift (minikube fork for OpenShift) & it works great, in place auto update if later version is found.

**Comment by dlorenc** [comment]
We should think through this to make sure it will work when we get multiple binaries.

**Comment by jimmidyson** [comment]
If we're packaging up multiple binaries then we need to put them all into one downloadable package somehow. That could be a tar ball, zip, or a binary that extracts the bundled binaries on start. I kinda like this last idea personally but I'm not precious about it.

**Comment by dlorenc** [comment]
I think I'd prefer we move to a tarball from go-bindata for binaries, especially when we start to bundle unrelated things like kubectl.

**Comment by philipn** [comment]
Will there be a way to pin the Kubernetes version that minikube runs, in this case?  We want to have exact parity between our local development version and our production kubernetes cluster (which doesn't auto-update).
