### ISSUE TITLE
Failed to update cluster: downloading binaries: copy: error removing file /u/usr/bin/kubelet: permission denied

### ISSUE THREAD

**Issue by Shukoorb4u** [kubernetes/minikube#3730]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

**Comment by tstromberg** [comment]
My apologies for this not working as expected. Do you mind sharing:

* [ ]  How to replicate the error, including the exact command-lines used.
* [ ]  The full output of the command that failed
* [ ]  The operating system name and version used

My suspicion is that this is Linux with the none driver, which sadly at the moment must be executed as root.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
