### ISSUE TITLE
Enables support for connection tracking zones (CONFIG_NF_CONNTRACK_ZONES) in the guest VM 

### ISSUE THREAD

**Issue by jojimt** [kubernetes/minikube#3731]
The mini-kube VM currently has 
"# CONFIG_NF_CONNTRACK_ZONES is not set"

I have a need to use this feature and would like to update the VM image. Is there a recommended way to do this? Is there a way to include this feature by default? Any guidance is appreciated.

**Comment by afbjorklund** [comment]
That looks like a kernel configuration, so needs a new ISO built - with that change applied.
What is the feature used for, and why do you need it ? What are the downsides of enabling it ?

https://github.com/kubernetes/minikube/blob/master/docs/contributors/minikube_iso.md

**Comment by jojimt** [comment]
Thanks for the pointer. Let me try that. 
`What is the feature used for, and why do you need it ? What are the downsides of enabling it ?`

I am testing a firewall plugin that requires it. As for downside, it might use a small amount of additional memory. I can't think of anything else.

**Comment by tstromberg** [comment]
I'm OK with reviewing a PR that includes this change.

**Comment by jojimt** [comment]
I am running into an issue with the kernel version while building it. I have:

**ubuntu@ip-172-31-36-92:~/go/src/minikube$ uname -a
Linux ip-172-31-36-92 4.16.14-041614-generic #201806051643 SMP Tue Jun 5 16:45:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux**

which is what the Makefile seems to call for:

**ubuntu@ip-172-31-36-92:~/go/src/minikube$ grep KERNEL Makefile 
KERNEL_VERSION ?= 4.16.14**

However, I get 
**ubuntu@ip-172-31-36-92:~/go/src/minikube$ make linux-menuconfig
make -C ./out/buildroot/output/build/linux-4.16.14/ menuconfig
make[1]: *** out/buildroot/output/build/linux-4.16.14/: No such file or directory.  Stop.

ubuntu@ip-172-31-36-92:~/go/src/minikube$ ls out/buildroot/output/build/linux-
linux-4.15/         linux-headers-4.15/**

If I edit the Makefile to change the version to 4.15, I am able to proceed. But, it looks like I am downgrading the kernel in the process which is not the intent.

Any ideas?

**Comment by jojimt** [comment]
@tstromberg any suggestions on how to get the build to linux-4.16.14?

**Comment by jojimt** [comment]
It turns out that https://github.com/kubernetes/minikube/pull/2986 actually downgraded the kernel to 4.15, but left the Makefile and apparently the linux_defconfig still at 4.16.14. So, I will proceed with 4.15.

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube, and if the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!
