### ISSUE TITLE
Getting error in minikube start

### ISSUE THREAD

**Issue by ankitacroit09** [kubernetes/minikube#3738]
If this is a bug report, please include:

 minikube start --memory 16384 --vm-driver="virtualbox" --disk-size 40g --docker-env HTTP_PROXY=http://10.144.1.10:8080/ --docker-env HTTPS_PROXY=http://10.144.1.10:8080/  --docker-env "NO_PROXY=localhost,127.0.0.1,192.168.0.0/16"
There is a newer version of minikube available (v0.34.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.34.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
o   minikube v0.34.0 on windows (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=16384MB, Disk=40000MB) ...
@   Downloading Minikube ISO ...
 181.48 MB / 181.48 MB  100.00% 0ssss
!   Unable to start VM: create: creating: open /Users/anksaxen/.minikube/cache/iso/minikube-v0.33.1.iso: The system cannot find the path specified.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by afbjorklund** [comment]
Sounds like #1574, it currently needs to run everything from `C:\`

**Comment by ankitacroit09** [comment]
Thanks Its work for me after move everything to C drive and set the environment variable to same C drive folder
