### ISSUE TITLE
Add `minikube bundle` subcommand to create self-contained distributables for demos, tutorials, etc

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#374]
This can create a self-contained distributable that you can specify what resources to import on startup, any extra files (e.g. custom binaries) required, etc so the user has a specified pre-configured Kubernetes install.

**Comment by dlorenc** [comment]
Can you clarify what you mean by "resources to import"? Is this just saving the ISO's state out somewhere, or is there more to it?

**Comment by srounce** [comment]
Write a script?

**Comment by jimmidyson** [comment]
> Images built on Linux won't run on a Mac

Are you talking about docker images? They run cross platform, thanks to docker engine running in a Linux vm on non-Linux machines.

If you're taking about custom binaries that might be unnecessary, but think it's worth considering. We're already thinking of bundling kubectl which is architecture specific, as is minikube itself.

**Comment by jimmidyson** [comment]
By resources to import I do really mean yaml files that can be imported at startup. Don't think it makes sense to save the state of the VM but it could very possibly require scripts to run to configure the bundled package.

**Comment by srounce** [comment]
> Are you talking about docker images? They run cross platform, thanks to docker engine running in a Linux vm on non-Linux machines.

Sorry, was late when I posted, brain was fried, yes I meant **binaries**.

What I was trying to say was that: If anything that isn't in a container will have to be built for each target. Why not provide a script to download binary dependencies + start the cluster + create resources from YAML? That way the target platform can be detected at runtime and catered for appropriately. 

Something like `$ minikube persist <filename>`, which, as well as automatically downloading correct binaries, gets all valid resource names, and then loops through them running equivalent of `$ kubectl get --namespace=<ns> -o yaml <type> <name>` and then concatenates all output into a string  ($KUBECONFIG). The script would end in something along the lines of: `cat $KUBECONFIG | kubectl -f -`. (Hope this makes sense?)

If I get time later I'll see if I can come up with a rudimentary go implementation for the (hazy) outline above.

In my mind demo/tutorial/etc. environments should be _totally_ configuration based, not reliant on some special unicorn disc image. Kubernetes affords the user idempotency in this sense, would it not be best to leverage it?

**Comment by jimmidyson** [comment]
That sounds good to me. I think you're right that we should be trying to totally rely on standard Kubernetes processes, configuration based, not reliant on binaries. In fact any shortcomings we find in Kubernetes while working on this for minikube could very well lead to changes in Kubernetes to cater for it (off the top of my head I can't think of what might be missing, but I'm sure we'll hit stuff).

I wonder if this is really a dupe of #372 after this discussion?

**Comment by dlorenc** [comment]
I like the idea of a "lexpor" type command that saves cluster state in a file. Would it make more sense in kubectl though, instead of minikube? It seems useful for all clusters.
