### ISSUE TITLE
"Other ways to install" link broken.

### ISSUE THREAD

**Issue by mdegans** [kubernetes/minikube#3740]
Following the link to "other ways to install" from the [official documentation](https://kubernetes.io/docs/tasks/tools/install-minikube/) leads [a broken link](https://github.com/kubernetes/minikube#other-ways-to-install). The #other-ways-to-install fragment does not exist as expected.

**Comment by afbjorklund** [comment]
Here is the source:
https://github.com/kubernetes/website/blob/master/content/en/docs/tasks/tools/install-minikube.md#linux

As far as I know there are currently **no** other ways to install _documented_, just the raw binary ?

There used to be a deb and a txz produced, but they both have some minor issues at the moment.

* https://github.com/kubernetes/minikube/releases/download/v0.34.1/minikube_0.34-1.deb

* https://aur.archlinux.org/packages/minikube-bin

The new link is:
https://github.com/kubernetes/minikube#installation

But it doesn't have the "other ways to install" content.

**Comment by afbjorklund** [comment]
We need to provide a deb (or two) for the `kvm2` driver, as well as something for apt's sources...

When that is done, the Linux instructions _could_ be something like `sudo apt install minikube`.

Instead of the current mess: [docs/drivers.md#kvm2-driver](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver)

I suppose one _could_ make an rpm and a repo, given demand ?

**Comment by mdegans** [comment]
Thank you. I found the .deb and also a wildly out of date snap package that probably shouldn't be in snapcraft anymore.

In any case I just installed the static binary in my ~/bin and that worked.

Personally, so long as there is an update notification, I don't really care about the packaging so much. I usually like to do a single user install if I can anyway.

**Comment by afbjorklund** [comment]
We don't document the `~/bin` installation at all. Maybe we should, it's better than the `/usr/local/bin`.
But different distros have some quirks about their default PATH, if it includes ~/bin and ~/.local/bin ?

**Comment by mdegans** [comment]
I know Ubuntu 18 uses it's default ~/.profile to add both you mentioned to PATH if they exist. I am not sure about other distros. Maybe it would be enough to mention that any path works fine, not just /use/local/bin. It's what I assumed anyway.

From what I remember, /usr/local/bin isn't in Ubuntu's default PATH anyway so an install there won't work without modifying PATH. If only all the distros could agree on where things go :/

**Comment by afbjorklund** [comment]
The weird thing is that Ubuntu now only adds it conditionally, if it exists when you start a **new** shell...
So if you happily do a `mkdir bin`, you will have a hard time finding out why it wasn't added.

``` bash
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi
```

But `/usr/local/bin` _should_ be in the user's PATH, although it is not in `root`'s PATH on CentOS
Main downside is that you have to be root (or sudo) to install to it, instead of just a regular user.

**Comment by mdegans** [comment]
I just double checked with a new user. /usr/local/bin is in my PATH. I must have imagined it not being there by default.

I just tested `debian:jessie-slim` and `debian:stretch-slim` in docker and both have the conditional PATH addition in `~/.profile` for `~/bin` but not for `~/.local/bin` like in Ubuntu 18.

Just tested ubuntu. 14.04 has the conditional add for `~/bin`.

16.04 does:
```
# set PATH so it includes user's private bin directories
PATH="$HOME/bin:$HOME/.local/bin:$PATH"
```
For some reason, canonical seems to have switched back to the conditional for 18.04. a new ~/.profile looks like:
```
...
# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi
```
