### ISSUE TITLE
"logs" command should not complain about an unexpected crash when a pod is missing

### ISSUE THREAD

**Issue by torbenmoeller** [kubernetes/minikube#3743]
I tried Ubuntu 18.10 as well as 18.04LTS. It's a fresh installation of Ubuntu and i installed docker, then kubectl and then minkube. All according to the Installation and Quickstart pages. A complete history of all commands I used:  [history.txt](https://github.com/kubernetes/minikube/files/2898129/history.txt)
The error message are
`failed: running command: No container was found matching "k8s_coredns_coredns"`
and
`User "system:kube-scheduler" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope`
[minkube logs.txt](https://github.com/kubernetes/minikube/files/2898128/minkube.logs.txt)

**Comment by afbjorklund** [comment]
Seems like you after reading the documentation decided to use `sudo minikube start --vm-driver=none`

Is your docker installation working as normal, i.e. can you pull images like `k8s.gcr.io/coredns:1.2.6` ?

What did the main console look like ?

**Comment by torbenmoeller** [comment]
Docker works perfectly. I tried Jenkins and the hello-world.
> sudo docker run k8s.gcr.io/coredns:1.2.6

gives the follwing output
```
.:53
2019-02-24T17:14:06.104Z [INFO] CoreDNS-1.2.6
2019-02-24T17:14:06.104Z [INFO] linux/amd64, go1.11.2, 756749c
CoreDNS-1.2.6
linux/amd64, go1.11.2, 756749c
```

**Comment by tstromberg** [comment]
My guess here is that CoreDNS was crashlooping because it had a port conflict with dnsmasq, common with Ubuntu and the none driver, since you can only run one DNS server at a time.

The error message when a pod missing is terrible though. It should instead say:

"Pod is missing: try kubectl <xxx> for more information" (or it should just run kubectl automatically).

**Comment by tstromberg** [comment]
Also, I believe the `User "system:kube-scheduler" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope` message is a race condition and a red herring here.

**Comment by torbenmoeller** [comment]
You're right, everything works correctly on Debian.

**Comment by tstromberg** [comment]
Thank you! I've verified that this no longer occurs with the v1.0.0 release. Please re-open if you run into this again.
