### ISSUE TITLE
Can't get minikube start -p kubert --vm-driver=kvm2 to start

### ISSUE THREAD

**Issue by itsmike-austin** [kubernetes/minikube#3746]
If this is a bug report, please include:

- [x] How to replicate the error, including the exact command-lines used.
- [x] The full output of the command that failed
- [x] The operating system name and version used

**Comment by itsmike-austin** [comment]
Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

Installed all required libraries. Reset bios to enable and/or disable virtualization. No change.

minikube start --vm-driver=kvm2
😄  minikube v0.34.1 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: creating domain: Error defining domain xml: 
<domain type='kvm'>
  <name>minikube</name> 
  <memory unit='MB'>2048</memory>
  <vcpu>2</vcpu>
  <features>
    <acpi/>
    <apic/>
    <pae/>
    <kvm>
      <hidden state='on'/>
    </kvm>
  </features>
  <cpu mode='host-passthrough'/>
  <os>
    <type>hvm</type>
    <boot dev='cdrom'/>
    <boot dev='hd'/>
    <bootmenu enable='no'/>
  </os>
  <devices>
    <disk type='file' device='cdrom'>
      <source file='/home/artwork/.minikube/machines/minikube/boot2docker.iso'/>
      <target dev='hdc' bus='scsi'/>
      <readonly/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='default' io='threads' />
      <source file='/home/artwork/.minikube/machines/minikube/minikube.rawdisk'/>
      <target dev='hda' bus='virtio'/>
    </disk>
    <interface type='network'>
      <source network='default'/>
      <mac address='e8:7f:98:ba:6e:2b'/>
      <model type='virtio'/>
    </interface>
    <interface type='network'>
      <source network='minikube-net'/>
      <mac address='a4:ab:bc:e9:c8:0a'/>
      <model type='virtio'/>
    </interface>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <rng model='virtio'>
      <backend model='random'>/dev/random</backend>
    </rng>
    
  </devices>
</domain>
: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

@Prod-001:~$ uname -a
Linux Prod-001 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Intel® Core™ i7-3770K CPU @ 3.50GHz × 8 
GeForce GTX 960/PCIe/SSE2
15.6 GiB

kvm module loaded

I followed the installation instructions for kubectl and minikube including using apt to install the kvm2 driver. Got minikube -p kubert --vm-driver=none to almost work. Downloaded iso, etc. but then it crashed with the same error.

What additional information is required? Thank you for your help

**Comment by itsmike-austin** [comment]
minikube start -p kubert --vm-driver=kvm2
minikube start -p kubert --vm-driver=kvm2
😄  minikube v0.34.1 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: creating domain: Error
[junk.log](https://github.com/kubernetes/minikube/files/2898819/junk.log)

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

$ uname -a
Linux Prod-001 4.15.0-42-generic #45-Ubuntu SMP Thu Nov 15 19:32:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Intel® Core™ i7-3770K CPU @ 3.50GHz × 8
GeForce GTX 960/PCIe/SSE2
15.6 GiB

Tried enable and disable virtualization in bios. No difference.

**Comment by afbjorklund** [comment]
Do you have KVM installed and working properly ? Can you install `cpu-checker` and run `kvm-ok` ?

``` console
$ sudo apt install cpu-checker
$ kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used
```

**Comment by itsmike-austin** [comment]
$ kvm-ok
INFO: /dev/kvm exists
KVM acceleration can be used


$ modinfo kvm
filename:       /lib/modules/4.15.0-42-generic/kernel/arch/x86/kvm/kvm.ko
license:        GPL
author:         Qumranet
srcversion:     70E329E00A3A3BD070FF874
depends:        irqbypass
retpoline:      Y
intree:         Y
name:           kvm
vermagic:       4.15.0-42-generic SMP mod_unload 
signat:         PKCS#7
signer:         
sig_key:        
sig_hashalgo:   md4
parm:           ignore_msrs:bool
parm:           report_ignored_msrs:bool
parm:           min_timer_period_us:uint
parm:           kvmclock_periodic_sync:bool
parm:           tsc_tolerance_ppm:uint
parm:           lapic_timer_advance_ns:uint
parm:           vector_hashing:bool
parm:           halt_poll_ns:uint
parm:           halt_poll_ns_grow:uint
parm:           halt_poll_ns_shrink:uint

**Comment by itsmike-austin** [comment]
The issue was a passed parameter coming out of BIOS of a gigabyte board. Resetting the advanced virtualization parameters was not reflected on page 0 during the boot cycle. Forcing an old BIOS onto the system and then installing the upgrade and drivers reset the parameter. Reloading default parameters did not clear the issue. Debugging minikube with go to track the issue backwards was interesting.
