### ISSUE TITLE
Setting nvidia-container-runtime when starting minikube 

### ISSUE THREAD

**Issue by maingoh** [kubernetes/minikube#3749]
*Feature Request*

If we want to use the GPU in minikube with `--vm-driver=none` (for networking reason we cannot use a VM), we currently need to default the nvidia container runtime on the host. We had some troubles when defaulting the runtime, especially when building the images. 
So I would like to set it only for minikube and not the whole docker daemon, just like we can when doing `docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi`. I saw there is an option `--container-runtime` but it does not support the nvidia runtime and I am not sure it is the good flag. 

We probably need a `--docker-runtime` flag ? How complicated would it be to provide this feature ?

**Comment by afbjorklund** [comment]
Can you try `--docker-opt default-runtime=nvidia` ? As you say, it is still `-container-runtime docker`

**Comment by maingoh** [comment]
I tried with minikube 1.0.0 without success. I started minikube with:
```
minikube start \
     --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf \
     --vm-driver=none
     --docker-opt default-runtime=nvidia
```

It starts well, but when creating a pod with `kubectl run test-gpu --image nvidia/cuda:9.0-base --restart=Never sleep infinity`, I exec into the container and `nvidia-smi` is not found. The same works when setting setting up the default-runtime in `/etc/docker/daemon.json`. I also tried with a `--docker-opt config-file=path_to_modified_daemon.json` and it doesn't work (like if the docker-opt is ignored ?).

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by chrisroat** [comment]
I believe this is still an open question.   I think it would substantially lower the barrier to entry for those who want to use a GPU with minikube.

Is the right approach to allow `--driver` to support a new option like `nvidia-docker`, or is a new flag needed?

**Comment by joysn71** [comment]
I set nvidia runtime in Dockers /etc/docker/daemon.json, and I can use GPU in Docker containers. 
But when I use driver "none" and setup a Minukube cluster, it is not working. Even worse, Minikube seems to throw out the nvidia runtime from daemon.json. Just noticed and verified that, after many hours looking elsewhere.
