### ISSUE TITLE
Waiting for kube-proxy ...  exec: "ionice": executable file not found

### ISSUE THREAD

**Issue by Th3G4mbl3r** [kubernetes/minikube#3750]
If this is a bug report, please include:

- [x] How to replicate the error, including the exact command-lines used. - minikube start
- [x] The full output of the command that failed 

minikube start
😄  minikube v0.34.1 on darwin (amd64)
👍  minikube will upgrade the local cluster from Kubernetes 1.13.2 to 1.13.3
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.13.3
💾  Downloading kubelet v1.13.3
🚜  Pulling images required by Kubernetes v1.13.3 ...
🔄  Relaunching Kubernetes v1.13.3 using kubeadm ...
⌛  Waiting for kube-proxy to come back up ...

Hangs at this point....

- [x] The operating system name and version used

Mac OSX v 10.14.3

When trying to start my minikube cluster it fails to start as it hangs at waiting for kube-proxy to come back up stage.

Output from minikube logs:

Feb 25 11:05:46 minikube kubelet[2919]: E0225 11:05:46.250618    2919 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: failed to exec du - exec: "ionice": executable file not found in $PATH, rootInodeErr: failed to exec cmd [ionice -c3 nice -n 19 find /var/lib/docker/overlay2/690ff7b7bdb1f3d2cbb4019df94518f8ba10d034e7e03fc6851a196ed30bd36c/diff -xdev -printf .] - exec: "ionice": executable file not found in $PATH; stderr: , extraDiskErr: failed to exec du - exec: "ionice": executable file not found in $PATH
Feb 25 11:06:02 minikube kubelet[2919]: E0225 11:06:02.385519    2919 fsHandler.go:121] failed to collect filesystem stats - rootDiskErr: failed to exec du - exec: "ionice": executable file not found in $PATH, rootInodeErr: failed to exec cmd [ionice -c3 nice -n 19 find /var/lib/docker/overlay2/37e69180e9a66d87dac87a8cbf4b5aa2b03615e407317dc7e06e8f686dbc23ab/diff -xdev -printf .] - exec: "ionice": executable file not found in $PATH; stderr: , extraDiskErr: failed to exec du - exec: "ionice": executable file not found in $PATH
💣  Error getting machine logs: unable to fetch logs for: k8s_coredns_coredns

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by Th3G4mbl3r** [comment]
hmmm... interesting. i moved .minikube to .minikube.bak. Then tried creating a new cluster which failed. So deleted the .minikube and moved back .minikube.bak to troubleshoot further. And now the cluster boots up fine.

**Comment by tstromberg** [comment]
The `ionice` errors come from running a VM created by an old version of minikube (v0.30 or earlier?),  but should be harmless. We fixed the kube-proxy issue in v0.35.0. Sorry about it not working for you!
