### ISSUE TITLE
CHANGE_MINIKUBE_NONE_USER env variable not setting config.json ownership

### ISSUE THREAD

**Issue by max-10001** [kubernetes/minikube#3751]
Description
Even after setting the CHANGE_MINIKUBE_NONE_USER env variable the config.json is still owned by root.
```
export CHANGE_MINIKUBE_NONE_USER=true
sudo -E minikube start --vm-driver=none 
sudo ls -lrt  /home/ubuntu/.minikube/machines/minikube/config.json 
```
Output
`-rw------- 1 root root 2123 Feb 25 15:33 /home/ubuntu/.minikube/machines/minikube/config.json`

minikube version: v0.34.1
OS: ubuntu 16.04 on EC2(AWS)

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube, and if the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!
