### ISSUE TITLE
documentation: use a case-sensitive disk image when building the ISO on mac

### ISSUE THREAD

**Issue by kwngo** [kubernetes/minikube#3752]
**Environment**
macOS

When running `make out/minikube.iso` the build fails I'm having an issue with buildroot. The failure seems to be caused by `/bin/sh: 1: cannot create /mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.os: File exists`.

```
rm -f /mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.os; > /mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.os
rm -f /mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.o; > /mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.o
/bin/sh: 1: cannot create /mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.os: File exists
make[5]: *** [/mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.os] Error 2
make[5]: *** Waiting for unfinished jobs....
../Makerules:920: recipe for target '/mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.os' failed
make[5]: Leaving directory '/mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/gnulib'
Makefile:215: recipe for target 'gnulib/subdir_lib' failed
make[4]: *** [gnulib/subdir_lib] Error 2
make[4]: Leaving directory '/mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e'
Makefile:9: recipe for target 'all' failed
make[3]: Leaving directory '/mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build'
make[3]: *** [all] Error 2
package/pkg-generic.mk:223: recipe for target '/mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/.stamp_built' failed
make[2]: *** [/mnt/out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/.stamp_built] Error 2
make[2]: Leaving directory '/mnt/out/buildroot'
make[1]: *** [minikube_iso] Error 2
Makefile:127: recipe for target 'minikube_iso' failed
make[1]: Leaving directory '/mnt'
make: *** [out/minikube.iso] Error 2
Makefile:151: recipe for target 'out/minikube.iso' failed
make: *** [out/minikube.iso] Error 2
```

**Comment by afbjorklund** [comment]
I think this build error is when building on a case-insensitive filesystem such as HFS.

I have _three_ of these files:
```
out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.oS
out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.os
out/buildroot/output/build/glibc-glibc-2.27-57-g6c99e37f6fb640a50a3113b2dbee5d5389843c1e/build/gnulib/stamp.o
```

On such a file system, the first two paths will map to *the same file* (and therefore fail)

The workaround is to create a disk image for the buildroot, formatted as case-sensitive:

https://support.apple.com/en-am/guide/disk-utility/create-a-disk-image-dskutl11888/mac

**Comment by afbjorklund** [comment]
@kwngo : are you using a Mac ?

**Comment by kakwong** [comment]
> @kwngo : are you using a Mac ?

Yep I am

**Comment by afbjorklund** [comment]
Thought I would double-check, since it said "Ubuntu 18.04" above

**Comment by kwngo** [comment]
Thanks, got it running in vagrant but I can play around with it for macos and add to the docs if that'd be useful 😄

**Comment by afbjorklund** [comment]
Most likely we should be using a volume for this on the Mac, rather than faking a volume mount...

**Comment by afbjorklund** [comment]
On second thought, a local volume would probably have the exact same case-insensitive problems.

So it seems like mounting a disk _just for the buildroot_ is the best approach - I do that on Linux too...

**Comment by afbjorklund** [comment]
Use something like this:

https://gist.github.com/dixson3/8360571

On Linux, I just use this:

`sudo mount -o bind /media/... out/buildroot`

**Comment by afbjorklund** [comment]
We should probably just document this workaround (use a case-sensitive disk image) and move on.

**Comment by medyagh** [comment]
> We should probably just document this workaround (use a case-sensitive disk image) and move on.

I would be happy to review any PR that adds this to the documentation.

**Comment by medyagh** [comment]
if anyone interested to add this to the docs ! this is a good first issue

**Comment by medyagh** [comment]
> We should probably just document this workaround (use a case-sensitive disk image) and move on.

I would be voting for this solution, what should be in the documentation ?

**Comment by afbjorklund** [comment]
There was some code in the gist, but someone needs to verify it (on a mac): https://github.com/kubernetes/minikube/issues/3752#issuecomment-478220260

The alternative is building the whole thing in a Linux VM, but that's like giving up (on Darwin)

**Comment by afbjorklund** [comment]
I prefer that it would be scripted (CLI), but otherwise you can do the same thing from the GUI

https://support.apple.com/guide/disk-utility/create-a-disk-image-dskutl11888/mac

**Comment by tstromberg** [comment]
https://minikube.sigs.k8s.io/docs/contrib/building/iso/ now defaults to building this image with Docker.

**Comment by cjheppell** [comment]
I'm not sure this should've been closed.

I just tried to build the minikube iso on MacOS and hit the exact same issue (this was being built in the docker container):

```
rm -f /mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/build/localedata/stamp.o; > /mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/build/localedata/stamp.o
/bin/sh: 1: cannot create /mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/build/localedata/stamp.os: File exists
../Makerules:854: recipe for target '/mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/build/localedata/stamp.os' failed
make[5]: *** [/mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/build/localedata/stamp.os] Error 2
make[5]: *** Waiting for unfinished jobs....
make[5]: Leaving directory '/mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/localedata'
Makefile:259: recipe for target 'localedata/subdir_lib' failed
make[4]: *** [localedata/subdir_lib] Error 2
make[4]: Leaving directory '/mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d'
Makefile:9: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/build'
package/pkg-generic.mk:266: recipe for target '/mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/.stamp_built' failed
make[2]: *** [/mnt/out/buildroot/output/build/glibc-2.30-73-gd59630f9959b0bb8991964758ab854ff4378b20d/.stamp_built] Error 2
make[2]: Leaving directory '/mnt/out/buildroot'
make[1]: *** [minikube_iso] Error 2
Makefile:248: recipe for target 'minikube_iso' failed
make[1]: Leaving directory '/mnt'
make: *** [out/minikube.iso] Error 2
Makefile:274: recipe for target 'out/minikube.iso' failed
make: *** [out/minikube.iso] Error 2
```

Presumably the workaround of creating a case-sensitive is still required, even when building in Docker?

**Comment by jandubois** [comment]
> Presumably the workaround of creating a case-sensitive fs is still required, even when building in Docker?

@cjheppell Yes, it is because the local filesystem is just mounted into the container. It is not using an independent volume.

I just filed a PR (#10506) to add a `make case-sensitive-build-dir` target to automate this.
