### ISSUE TITLE
Minikube fails to start with time out error

### ISSUE THREAD

**Issue by AmulyaJagadeesh** [kubernetes/minikube#3754]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
- [x] The full output of the command that failed
- [x] The operating system name and version used

**Comment by tstromberg** [comment]
Not enough information. If you are still suffering a timeout issue, I encourage you to try with minikube v0.35.0. If it doesn't work, please include the command executed and the output of the command in your bug report. Thanks!
