### ISSUE TITLE
kvm2: storage.googleapis.com/releases/latest/docker-machine-driver-kvm2.sha256 is 2 years out of date

### ISSUE THREAD

**Issue by brennen** [kubernetes/minikube#3756]
I can't really find any documentation on this file, but it seems worth surfacing since the [docs on driver installation](https://github.com/kubernetes/minikube/blob/master/docs/drivers.md) reference the storage.googleapis.com path for `docker-machine-driver-kvm2` itself, rather than GitHub releases or some other source.  I assume this is an artifact that just isn't getting built / published but still lingers from an earlier version of the process:

```
$ curl --silent -I 'https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2' | grep last-modified
last-modified: Sat, 16 Feb 2019 22:17:00 GMT

$ curl --silent -Iq 'https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2.sha256' | grep last-modified
last-modified: Wed, 29 Nov 2017 23:08:34 GMT
```

At any rate, the published hash definitely doesn't line up with that of the binary.  A test case (apologies for the verbosity, this is just extracted from some hacky setup scripting I'm working on):

```sh
#!/bin/sh

CURL_COMMAND="curl --fail --silent --show-error"

# Grab a thing from a Google Storage URL and check its SHA256:
checked_gstorage_download () {
  source_url="$1"
  target_file="$2"
  sha256_file="$target_file.sha256"

  $CURL_COMMAND --location --output "$target_file" "$source_url"
  $CURL_COMMAND --output "$sha256_file" "$source_url.sha256"

  echo "Expected sha256sum:"
  cat "$sha256_file"

  echo "Actual sha256sum:"
  sha256sum "$target_file"

  if sha256sum "$target_file" | grep --file="$sha256_file" --fixed-strings; then
    return 0
  fi
  return 1
}

KVM2_URL='https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2'
echo "Installing kvm2 driver from:"
echo "$KVM2_URL"
if checked_gstorage_download "$KVM2_URL" /tmp/docker-machine-driver-kvm2; then
  echo "Matching sha256sum for docker-machine-driver-kvm2"
else
  echo "Error: sha256 mismatch"
  exit 1
fi
```

Output on my Debian Stretch system:

```
brennen@inertia 18:51:40 ~/code/wmf/local-charts (improve_debian_prereq 0/4) ▣ ./test_hash.sh
Installing kvm2 driver from:
https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
Expected sha256sum:
e1cafeacb90e453181877d03cfbbd2972e2c75c695588efea4efa1a887167812
Actual sha256sum:
e15ba8584b8c46f914b9e2e4f9f333134f904e1f5c039dddb217e2a70f57fc02  /tmp/docker-machine-driver-kvm2
Error: sha256 mismatch
zsh: exit 1     ./test_hash.sh
```

**Comment by afbjorklund** [comment]
The artifact is still published, but the checksum is **not** updated:

https://github.com/kubernetes/minikube/blob/master/Makefile#L210

https://github.com/kubernetes/minikube/blob/master/hack/jenkins/release_github_page.sh#L112

i.e. only minikube and the ISO have checksums, not the drivers...

**Comment by afbjorklund** [comment]
@tstromberg : Deleting the existing old files sounds like a first step.

Then look at revisiting the procedure, for the upcoming 1.0 releases...

It's not like we actually _verify_ (nor sign) the checksum, as part of install ?

``` bash
curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2 \
  && sudo install docker-machine-driver-kvm2 /usr/local/bin/
```

**Comment by brennen** [comment]
I will mention as an aside that an actual signature I could verify would definitely be a nice-to-have, though of course that's out of the scope of this issue.  (I'm trying to verify checksums for everything, but that doesn't seem to be a guarantee of much beyond "congratulations, `curl` got the whole binary".)
