### ISSUE TITLE
vhost-net support in minikube iso for kubevirt

### ISSUE THREAD

**Issue by karmab** [kubernetes/minikube#3762]
i d like to have vhost-net support in minikube iso as it's needed in kubevirt in order to use minikube

**Comment by karmab** [comment]
addressed in https://github.com/kubernetes/minikube/pull/3758

**Comment by afbjorklund** [comment]
Another approach: https://kubevirt.io/2018/Hello-KubeVirt-on-Minikube.html

**Comment by karmab** [comment]
hello @afbjorklund , yeah we can workaround the issue using emulation mode in kubevirt, but beeing able to use nested virt along with vhost-net would provide a better end user experience
