### ISSUE TITLE
https://github.com/kubernetes/minikube/issues/new

### ISSUE THREAD

**Issue by rajesh2887** [kubernetes/minikube#3764]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

**Comment by tstromberg** [comment]
Closing due to lack of information.

**Comment by ZoryDeMarker** [comment]
virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

**Comment by valasyam** [comment]
hello i got an error i want to rectify that:
💣  Unable to start VM: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
