### ISSUE TITLE
Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

### ISSUE THREAD

**Issue by amitshowry** [kubernetes/minikube#3775]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

**Comment by tstromberg** [comment]
Please supply more information! I also encourage you to try with minikube v0.35.0, as it helps with many of the earlier crashes.

**Comment by ZoryDeMarker** [comment]
I am using v0.35.0 on centos 7and have that same error.

Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
@ZoryDeMarker - Please open a new bug with details. That particular message is shown for any error encountered.
