### ISSUE TITLE
mini kubecrashed at start

### ISSUE THREAD

**Issue by Thegrinch1985** [kubernetes/minikube#3776]
😄  minikube v0.34.1 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by nish-8099** [comment]
It does not find VM. See [docs](https://kubernetes.io/docs/tasks/tools/install-minikube/#install-a-hypervisor). 

If VM is already installed, try to start `minikube` with `--vm-driver=VirtualBox` argument. (You can replace VirtualBox with Hypervisor installed on your machine)

Hope it helps.

**Comment by nish8099** [comment]
It does not find VM. See [docs](https://kubernetes.io/docs/tasks/tools/install-minikube/#install-a-hypervisor). 

If VM is already installed, try to start `minikube` with `--vm-driver=VirtualBox` argument. (You can replace VirtualBox with Hypervisor installed on your machine)

Hope it helps.

**Comment by tstromberg** [comment]
Note: minikube v0.35.0 will no longer show the bug report URL for this common case.

**Comment by PenelopeFudd** [comment]
I had this problem today; the cause was that I had installed the snap version of minikube, and it couldn't find VBoxManage in the snap's path.  Fixed by removing the snap (snap remove minikube) and downloading the minikube binary instead.

**Comment by banyejinghungui** [comment]
I just installed virtualbox in the system (ubuntu 20) and it works

sudo apt install virtualbox

**Comment by iravivarma** [comment]
Thank you this works
