### ISSUE TITLE
Minikube doesn't start on Windows 10

### ISSUE THREAD

**Issue by Shehanka** [kubernetes/minikube#3781]
If this is a bug report, please include:

- [x] The exact command-lines used.
`minikube start`

- [x] The full output of the command that failed
`o   minikube v0.34.1 on windows (amd64)`
`>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...`
`!   Unable to start VM: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path`

`*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:`
`-   https://github.com/kubernetes/minikube/issues/new`

- [x] The operating system name and version used
OS - Windows 10
Version - 10.0.17134 Build 17134

**Comment by afbjorklund** [comment]
DId you install VirtualBox ?

**Comment by Shehanka** [comment]
Yes already

**Comment by josefkorbel** [comment]
Is it in your PATH?

**Comment by Shehanka** [comment]
Yah, but somehow now it's working

**Comment by yahorsi** [comment]
Comment on installing on windows:

When reading docs here:
https://kubernetes.io/docs/tasks/tools/install-minikube/ 

You suppose you don't need VirtualBox  as you user Hyper-V, but, steps described in the doc's above makes you fail with the error message topic started has posted. Then you google and come here and https://github.com/kubernetes/minikube/issues/3776. Then you run minikube -h and don't see --vm-driver

So docs for windows needs to be updated a little

**Comment by Leon-Africa** [comment]
**Solution:**

Go to "Hyper-V Manager" in Windows. (Search from TaskBar)
Once in Hyper-V Manager go to "Virtual Switch Manager" on right panel
Select "New Virtual Network switch" 
Select "External" for Network Type
Select Create Virtual Switch (name the switch "Primary Virtual Switch")
Click Apply the OK

After that open Powershell as admin (I got error with cmd) and run command:

**minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"**

![minikube](https://user-images.githubusercontent.com/16097992/58877971-7672cd00-86d2-11e9-98fe-ef9e622a2864.PNG)


After that you just run: **minikube start**

To check that all is in order run:
minikube status
minikube ip

Main Reference: https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c

**Comment by LennyCastaneda** [comment]
That Medium article was good but still Minikube is still failing in my Windows 10 machine

![Screen Shot 2019-06-17 at 6 19 42 PM](https://user-images.githubusercontent.com/9893446/59646601-835cdb00-912c-11e9-92c0-5eec8593fafd.png)

**Comment by LennyCastaneda** [comment]
![Screen Shot 2019-06-17 at 6 21 32 PM](https://user-images.githubusercontent.com/9893446/59646673-c323c280-912c-11e9-8c2d-35f09ca46b94.png)

**Comment by bgopalakr** [comment]
here is what I did to make it work. I am behind corporate firewall
1. Open Hyper-V Manager
2. Stop and Delete the VM which created by Windows
3. Create a new Virtual Switch
4. then start minikube as mentioned in previous post using hyperv driver.

My case since VM already on Hyper-v was stopping new VM creation. Second problem was, Virtual switch i created I selected my wireless network instead of LAN (my machine is connected through LAN and Wifi)

**Comment by Ja-k** [comment]
I have done all the above, for short period of time everything goes well but suddenly minikube crushes in the middle of pods creation phase and when I check "**minikube status**" or "**kubectl version**" in server part says "**Unable to connect to server**!!!!!"

**Comment by Farouk19** [comment]
I had the same issue, just running Powershell as administrator and it worked.

**Comment by tiagotele** [comment]
I follows the @Farouk19 comment and it worked as well. However I did a restart on my console app(Conemu) and it was working well.

**Comment by LQss11** [comment]
In case you couldn't manage to fix the issue you can follow the [minikube docs for HyperV driver][1].
>This is valid only for Windows10 Pro users.

You can verify that it says:
```
--hyperv-virtual-switch: ... Defaults to first found
```
So if you already have a Default external switch, there is no need to create a new one you will only need to run `as adminstrator`:
```sh
minikube start --driver=hyperv 
```

In case you had some issue you can try to delete with purge flag the minikube VM then restart it:
```sh
minikube delete --all --purge 
``` 

else you could troubleshoot running:
```sh
minikube start --alsologtostderr -v=7
```

Also if you already have a docker engine running on your computer you can select docker as your driver by running:
```sh
minikube start --driver=docker
```

  [1]: https://minikube.sigs.k8s.io/docs/drivers/hyperv/
