### ISSUE TITLE
hyperv is not stopping when using minikube  stop

### ISSUE THREAD

**Issue by csuryac** [kubernetes/minikube#3782]
If this is a bug report, please include:

- [ ] How to replic:\windows\system32>minikube stop
:   Stopping "minikube" in hyperv ...
:   Stopping "minikube" in hyperv ...
:   Stopping "minikube" in hyperv ...
:   Stopping "minikube" in hyperv ...
:   Stopping "minikube" in hyperv ...
!   Unable to stop VM: Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1ate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

**Comment by tstromberg** [comment]
Dupe of #3492
