### ISSUE TITLE
minikube crashed when starting

### ISSUE THREAD

**Issue by gitsoso** [kubernetes/minikube#3784]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
I am trying to install helm on minikube. but minikube not start and stay up due to proxy related alerts

cloud_user@sobomawokoma2c:~$ sudo minikube start
😄  minikube v0.34.1 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.5 LTS"

**Comment by tstromberg** [comment]
Please install VirtualBox. 

NOTE: This no longer outputs a scary warning in v0.35.0.

**Comment by SRamY** [comment]
Hi Please anyone help me on the below error,




                                                                                                                                                                        
                                                                                                                                                                        * minikube v1.2.0 on windows (amd64)
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0722 18:35:42.754161    4724 start.go:559] StartHost: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

X Unable to start VM
* Error:         [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
* Advice:        Install VirtualBox, ensure that VBoxManage is executable and in path, or select an alternative value for --vm-driver
* Documentation: https://www.virtualbox.org/wiki/Downloads
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3784
  - https://github.com/kubernetes/minikube/issues/3776

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by danny8002** [comment]
for windows 10 with hyperv, 'hyperv' should be explicitly specified since minikube use VirtualBox by default.
`minikube start --vm-driver=hyperv  `
