### ISSUE TITLE
vmwarefusion: image pull: Error processing tar file(exit status 1): operation not supported

### ISSUE THREAD

**Issue by prahaladdarkin** [kubernetes/minikube#3786]
Downloaded minikube 0.34 and attempt to start Kubernetes cluster. 

- [x] How to replicate the error, including the exact command-lines used.
Command run - ` minikube start --vm-driver=vmwarefusion --extra-config=apiserver.Authorization.Mode=RBAC`
- [x] The full output of the command that failed
`prahaladd-a01:istio prahaladd$ minikube start --vm-driver=vmwarefusion --extra-config=apiserver.Authorization.Mode=RBAC
😄  minikube v0.34.1 on darwin (amd64)
⚠️  The vmwarefusion driver is deprecated and support for it will be removed in a future release.
				Please consider switching to the new vmware unified driver, which is intended to replace the vmwarefusion driver.
				See https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#vmware-unified-driver for more information.
				To disable this message, run [minikube config set WantShowDriverDeprecationNotification false]
🔥  Creating vmwarefusion VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 172.16.65.136
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
    ▪ apiserver.Authorization.Mode=RBAC
💾  Downloading kubeadm v1.13.3
💾  Downloading kubelet v1.13.3
🚜  Pulling images required by Kubernetes v1.13.3 ...
❌  Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout: [config/images] Pulled k8s.gcr.io/kube-apiserver:v1.13.3
[config/images] Pulled k8s.gcr.io/kube-controller-manager:v1.13.3
[config/images] Pulled k8s.gcr.io/kube-scheduler:v1.13.3

stderr: failed to pull image "k8s.gcr.io/kube-proxy:v1.13.3": output: v1.13.3: Pulling from kube-proxy
73e3e9d78c61: Already exists
0c440f353724: Pulling fs layer
5764bbd93c04: Pulling fs layer
0c440f353724: Verifying Checksum
0c440f353724: Download complete
5764bbd93c04: Verifying Checksum
5764bbd93c04: Download complete
failed to register layer: Error processing tar file(exit status 1): operation not supported
, error: exit status 1
: Process exited with status 1
🚀  Launching Kubernetes v1.13.3 using kubeadm ...
💣  Error starting cluster: kubeadm init:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI

[init] Using Kubernetes version: v1.13.3
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING Swap]: running with swap on is not supported. Please disable swap
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.13.3: output: v1.13.3: Pulling from kube-proxy
73e3e9d78c61: Already exists
0c440f353724: Pulling fs layer
5764bbd93c04: Pulling fs layer
0c440f353724: Verifying Checksum
0c440f353724: Download complete
5764bbd93c04: Verifying Checksum
5764bbd93c04: Download complete
failed to register layer: Error processing tar file(exit status 1): operation not supported
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.2.24: output: 3.2.24: Pulling from etcd
8c5a7da1afbc: Pulling fs layer
0d363128e48e: Pulling fs layer
1ba5e77f0f6e: Pulling fs layer
8c5a7da1afbc: Verifying Checksum
8c5a7da1afbc: Download complete
8c5a7da1afbc: Pull complete
1ba5e77f0f6e: Verifying Checksum
1ba5e77f0f6e: Download complete
0d363128e48e: Verifying Checksum
0d363128e48e: Download complete
failed to register layer: Error processing tar file(exit status 1): operation not supported
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new`

- [ ] The operating system name and version used
Mac OS High Sierra, 10.13.6

**Comment by afbjorklund** [comment]
Sounds like a Docker problem, there are some Moby issues that look similar ?

**Comment by tstromberg** [comment]
I wasn't able to replicate this using VMware Fusion 11.0.2 and macOS 10.14.3. It sounds very much like a corrupted downloads of images.

Do you mind checking if adding `--cache-images` changes the behavior at all? This way the images are downloaded from outside the VM rather than inside.

**Comment by logopk** [comment]
I have the same problem.

I’m running homebrew,docker and minikube without admin and sudo rights. Mabe that’s an issue?

**Comment by tstromberg** [comment]
@logopk - Do you mind checking if `minikube start --cache-images` works around this issue?

**Comment by logopk** [comment]
It didn't help ...
`$ minikube start --cache-images
😄  minikube v0.35.0 on darwin (amd64)
🤹  Caching images in the background ...
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
2019/03/11 07:48:35 Unable to read "/Users/<red>/.docker/config.json": open /Users/<red>/.docker/config.json: no such file or directory
2019/03/11 07:48:35 No matching credentials were found, falling back on anonymous
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running vmware VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 172.16.185.134
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💣  Failed to update cluster: loading cached images: loading cached images: loading image /Users/<red>/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: transferring cached image: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
`

**Comment by tstromberg** [comment]
Do you mind trying again with the latest minikube release and including the output of:

`minikube start --alsologtostderr -v=8`
`minikube logs`

That should help us sort what's going on here. My theory is that either sshd is being killed, or the virtual network is flaky.

**Comment by logopk** [comment]
Hi @tstromberg,
verbosity on this has been overwhelming, so I removed the output. Apparently it starts now without error...

😄  minikube v1.1.0 on darwin (amd64)

⚠️  Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the vmware driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`

🔄  Restarting existing vmware VM for "minikube" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.14.2 on Docker 18.06.2-ce
🔄  Relaunching Kubernetes v1.14.2 using kubeadm ... 
⌛  Verifying: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"

Do you still need more detailed output?

**Comment by tstromberg** [comment]
Nope. I'm going to blame this one on the deprecated `vmwarefusion` driver. If someone else runs into this with the `vmware` driver, please let me know the version of VMware used.

**Comment by tstromberg** [comment]
If you run into this, please use the newer `vmware` driver:

https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

Thanks!
