### ISSUE TITLE
Error downloading kubeadm v1.13.3: checksum validation failed

### ISSUE THREAD

**Issue by er-ankit** [kubernetes/minikube#3792]
Facing error while starting minikube

**OS:** Windows 10
**Tool used:** Windows Powershell
**Minikube version:** v0.34.1
**kubectl verison:** v1.13.0

**Command Used:**  .\minikube start --vm-driver="virtualbox"

**Output of command:**
o   minikube v0.34.1 on windows (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.99.100
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
@   Downloading kubeadm v1.13.3
@   Downloading kubelet v1.13.3
!   Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.13.3: failed to download: failed to download to temp file: checksum validation failed

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
Thanks for the bug report!

I suspect this was a temporary download issue, but don't have any way to tell what happened here. DO you mind trying with minikube v0.35.0 to see if the issue is consistent?

**Comment by er-ankit** [comment]
The issue was fixed by turning off SSL.
Hence closing it.
