### ISSUE TITLE
unable to cache ISO: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by quiditich** [kubernetes/minikube#3793]
Hello,

I have an issue when trying to start minkube.

When I execute minikube start, I get the below error:

[root@andreiPC ~]# minikube start
o   minikube v0.34.1 on linux (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
!   Unable to start VM: unable to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

[root@andreiPC ~]# minikube start --v 10 --logtostderr
I0301 09:41:20.251363   17190 notify.go:121] Checking for updates...
W0301 09:41:20.855008   17190 notify.go:55] Error getting json from minikube version url: error with http GET for endpoint https://storage.googleapis.com/minikube/releases.json: Get https://storage.googleapis.com/minikube/releases.json: x509: certificate has expired or is not yet valid
o   minikube v0.34.1 on linux (amd64)
I0301 09:41:20.856920   17190 start.go:579] Saving config:
{
    "MachineConfig": {
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso",
        "Memory": 2048,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "virtualbox",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.13.3",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": false,
        "EnableDefaultCNI": false
    }
}
I0301 09:41:20.857389   17190 cluster.go:70] Machine does not exist... provisioning new machine
I0301 09:41:20.857408   17190 cluster.go:71] Provisioning machine with config: {MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso Memory:2048 CPUs:2 DiskSize:20000 VMDriver:virtualbox ContainerRuntime:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] XhyveDiskDriver:ahci-hd DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: GPU:false}
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
I0301 09:41:22.348637   17190 start.go:351] StartHost: unable to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
I0301 09:41:22.348749   17190 utils.go:114] non-retriable error: unable to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
W0301 09:41:22.348869   17190 exit.go:85] Unable to start VM: unable to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
!   Unable to start VM: unable to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v0.34.0.iso: x509: certificate has expired or is not yet valid

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

Any ideas? 

Thank you.

**Comment by tstromberg** [comment]
I'm pretty sure your system clock is way off. What does the output of the `date` command look like?

Also, don't run minikube as root unless you really need to.

**Comment by quiditich** [comment]
Hello,

As I can see, hour is fine:

andrei@andrei-VirtualBox:~$ date
Mon Mar 11 09:09:28 EET 2019

When I try to run minikube as a non privileged user, I receive the following:

andrei@andrei-VirtualBox:~$ minikube start
There is a newer version of minikube available (v0.35.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.35.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
o   minikube v0.34.1 on linux (amd64)
!   Unable to load config: open /home/andrei/.minikube/profiles/minikube/config.json: permission denied


When I try to run minikube as a privileged user, I receive the following:

andrei@andrei-VirtualBox:~$ sudo minikube start
There is a newer version of minikube available (v0.35.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.35.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
o   minikube v0.34.1 on linux (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
!   Unable to start VM: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
The non-privileged error is because you've previously run minikube as root. You can fix it by running:

`chown -R andrei ~/.minikube`

The privileged error you see appears to be either an old bug, or a real issue. Do you mind trying again with a newer release of minikube (v1.1)? 

If you continue to get a `certificate has expired or is not yet valid` error, please send me the output of:

`curl -v  https://storage.googleapis.com/`

Thanks!

**Comment by quiditich** [comment]
Hello Thomas,

I solved the issue running following commands:

1. minikube config set vm-driver none
2. systemctl enable docker
3. systemctl start docker
4. minikube start

It seems that only solution was to run minikube in a docker container.

Thank you for your help
Andrei
