### ISSUE TITLE
Unable to restart with apiserver.enable-admission-plugins="PodSecurityPolicy": timeout

### ISSUE THREAD

**Issue by MrMic** [kubernetes/minikube#3795]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.

=> First start:

$> minikube start --extra-config=apiserver.enable-admission-plugins="PodSecurityPolicy"
😄  minikube v0.34.1 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.30 MB / 184.30 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.108
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
    ▪ apiserver.enable-admission-plugins=PodSecurityPolicy
🚜  Pulling images required by Kubernetes v1.13.3 ...
🚀  Launching Kubernetes v1.13.3 using kubeadm ...
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!

- [ ] The full output of the command that failed
=> I stop minikube and try to restart:

$>minikube start --extra-config=apiserver.enable-admission-plugins="PodSecurityPolicy"
😄  minikube v0.34.1 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.108
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
    ▪ apiserver.enable-admission-plugins=PodSecurityPolicy
🚜  Pulling images required by Kubernetes v1.13.3 ...
🔄  Relaunching Kubernetes v1.13.3 using kubeadm ...
⌛  Waiting for kube-proxy to come back up ...
💣  Error restarting cluster: restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

- [ ] The operating system name and version used
Mac OSX: 10.14.3 Mojave
Minikube: 0.34.1
Kubernetes: 1.13.3

-  But if i restart with no option, it is OK:

$>minikube start
😄  minikube v0.34.1 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.108
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.3 ...
🔄  Relaunching Kubernetes v1.13.3 using kubeadm ...
⌛  Waiting for kube-proxy to come back up ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!

Thanks for any help and fixing it.
Rgds,

**Comment by tstromberg** [comment]
Do you mind providing the output of `minikube logs`?

I wasn't able to start a PSP cluster locally due to #3818 - I wouldn't be surprised if this is somewhat related, but I'd like to make the issue easier to debug.

**Comment by tstromberg** [comment]
Marking as dupe of #3818.
