### ISSUE TITLE
none: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition

### ISSUE THREAD

**Issue by elkinforero** [kubernetes/minikube#3797]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.

sudo minikube start --vm-driver=none
😄  minikube v0.34.1 on linux (amd64)
🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

⚠️  kubectl and minikube configuration will be stored in /home/tid
⚠️  To use kubectl or minikube commands as your own user, you may
⚠️  need to relocate them. For example, to overwrite your own settings:

    ▪ sudo mv /home/tid/.kube /home/tid/.minikube $HOME
    ▪ sudo chown -R $USER /home/tid/.kube /home/tid/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running none VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.0.241
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.3 ...
🔄  Relaunching Kubernetes v1.13.3 using kubeadm ... 
⌛  Waiting for kube-proxy to come back up ...
💣  Error restarting cluster: restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition

- [ ] The full output of the command that failed
😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

- [ ] The operating system name and version used
Ubuntu 18.04

**Comment by tstromberg** [comment]
Do you mind trying again with minikube v0.35.0? The error should look very different, if it happens at all.

**Comment by kl09** [comment]
Have the same error.
[minikube-logs.txt](https://github.com/kubernetes/minikube/files/2976535/minikube-logs.txt)

**Comment by marcosdiez** [comment]
Hi! I had a similar problem and my solution is here: https://github.com/kubernetes/minikube/pull/4052
Could you please try yourself and comment if the solution works for you as well ? Thank you!

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube, and if the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!
