### ISSUE TITLE
failed to register layer: Error processing tar file(exit status 1): operation not supported , error: exit status 1

### ISSUE THREAD

**Issue by srinivasankr** [kubernetes/minikube#3803]
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

**Comment by tstromberg** [comment]
Do you mind including a bit more detail, such as the command-line used and the full output of the error? Thanks!

**Comment by tstromberg** [comment]
Closing as dupe of #3786
