### ISSUE TITLE
Windows 10 failed when launched from root of D:

### ISSUE THREAD

**Issue by kmarf** [kubernetes/minikube#3806]
Windows 10 x64 1809
Downloaded minikube-windows-amd64.exe 
Copied to D:
Renamed to minikube.exe
Open command prompt
Run minikube start
o   minikube v0.34.1 on windows (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
!   Unable to start VM: create: creating: open /Users/Me/.minikube/cache/iso/minikube-v0.34.0.iso: The system cannot find the path specified.
*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
So uploaded this to let you know it worked fine when I copied EXE to C: then ran minikube start -p test
:)

**Comment by kmarf** [comment]
C:\>minikube start -p test
o   minikube v0.34.1 on windows (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "test" IP address is 192.168.99.100
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
@   Downloading kubeadm v1.13.3
@   Downloading kubelet v1.13.3
-   Pulling images required by Kubernetes v1.13.3 ...
-   Launching Kubernetes v1.13.3 using kubeadm ...
-   Configuring cluster permissions ...
-   Verifying component health .....
+   kubectl is now configured to use "test"
i   For best results, install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/
=   Done! Thank you for using minikube!

**Comment by afbjorklund** [comment]
Duplicate, #1574

Unfortunately you will have to run it from `C:\` for now.
