### ISSUE TITLE
Minikube unable to start vm on Centos 7 on AMD processor

### ISSUE THREAD

**Issue by anewton81** [kubernetes/minikube#3808]
Hello,

I have installed minikube v0.34.1 on linux (amd64), command line "minikube start"

I am running the latest fully patched Centos 7.6, but kernel version 3.10.0-862.el7.x86_64 (the initial kernel version from Centos 7.5 install ISO, along with kernel-devel and kernel-headers of the same version because the kernels kernel-3.10.0-957+ constantly hang on my machine due to nouveau video driver issues with my nVidia card).  VirtualBox configured just fine with this kernel version.

When I do "minikube start", here is the result:
=====
# minikube start
😄  minikube v0.34.1 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.30 MB / 184.30 MB [============================================] 100.00% 0s
💣  Unable to start VM: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
=====
This error message is incorrect, the virtual technology _IS_ turned on in the BIOS.  The lscpu command verifies this:
=====
# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    8
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            23
Model:                 8
Model name:            AMD Ryzen 7 2700X Eight-Core Processor
Stepping:              2
CPU MHz:               2200.000
CPU max MHz:           3700.0000
CPU min MHz:           2200.0000
BogoMIPS:              7399.24
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             64K
L2 cache:              512K
L3 cache:              8192K
NUMA node0 CPU(s):     0-15
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb hw_pstate sme retpoline_amd vmmcall fsgsbase bmi1 avx2 smep bmi2 rdseed adx smap clflushopt sha_ni xsaveopt xsavec xgetbv1 clzero irperf xsaveerptr ibpb arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov succor smca
=====
The only thing I can see is that lscpu is reporting "AMD-V" and the error message says there is no "AMD-v".  Is there a lettercase issue in the test in minikube?

Help appreciated, thank you.  Please let me know if I need to provide additional information.

**Comment by afbjorklund** [comment]
Duplicate, #3706

**Comment by anewton81** [comment]
Thanks
