### ISSUE TITLE
Expose ingress hosts with mDNS

### ISSUE THREAD

**Issue by calind** [kubernetes/minikube#3821]
This is a feature request for exposing ingresses when using `minikube tunnel`.

The hosts can be exposed by having minikube answer for mDNS requests for domains ending in `.local` with the IPs set in the ingress status.

**Comment by calind** [comment]
This can be implemented as a stand-alone controller running with host netowrk. Do you think that this can make it to the addons?

**Comment by tstromberg** [comment]
I think so. I'd be happy to review any PR's which make this happen.

**Comment by woodcockjosh** [comment]
I would rather not have to run `minikube tunnel` to access a host $(minikube ip) which is already available. What if I have several minikube instances? I have to run `minikube tunnel` for every host? Instead I would propose that the ingress resources be made available on the host os and mapped to the appropriate minikube ip. https://github.com/kubernetes/minikube/issues/5494

**Comment by woodcockjosh** [comment]
Ingress DNS addon provides a DNS server for ingress resources on the host OS: https://github.com/kubernetes/minikube/pull/5507

**Comment by priyawadhwa** [comment]
@woodcockjosh has this issue been resolved by #5507?
