### ISSUE TITLE
Rename minikube clusterrolebindings to be hierarchical 

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/minikube#3825]
This is a minor issue but as security and threat modelling becomes more important, id like to fix minikube to be a better example of a how to make a transparent secure deployment policy -  right now our minikube rolebindings are a little raw looking:

```
➜  /tmp kubectl get clusterrolebindings
NAME                                                   AGE
cluster-admin                                          11d
kubeadm:kubelet-bootstrap                              11d
```

Suggestion: 

Simlar to `system:` and so on, it seems like we should make the minikube rolebindings named hierarchichally, so that minikube is a canonical system for representing how to model security policies for demos etc... 

```
kubeadm:kubelet-bootstrap                              11d
kubeadm:node-autoapprove-bootstrap                     11d
kubeadm:node-autoapprove-certificate-rotation          11d
kubeadm:node-proxier                                   11d
```

**Comment by tstromberg** [comment]
That seems reasonable, and I would be happy to review any PR's which make this happen. Thank you for the suggestion!

**Comment by RA489** [comment]
I can take a look

**Comment by tstromberg** [comment]
Still an issue in v1.4. Help wanted!

It's unclear to me what the best name to use for our naked roles is:

```
cluster-admin                                          69m
kubernetes-dashboard                                   69m
minikube-rbac                                          69m
storage-provisioner                                    69m
```

**Comment by priyawadhwa** [comment]
Still currently an issue if anyone is interested in working on this!

There's some documentation around naming and cluster role bindings [here](https://kubernetes.io/docs/reference/access-authn-authz/rbac/) which could be useful. 


From that documentation:
```
Across the entire cluster, grant the permissions in the cluster-admin ClusterRole to a user named “root”:

kubectl create clusterrolebinding root-cluster-admin-binding --clusterrole=cluster-admin --user=root
```
so I think renaming `cluster-admin` to `cluster-admin-binding` may be acceptable.
