### ISSUE TITLE
CRI-O not working, it thinks im trying to run docker.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/minikube#3829]
x-ref #3798  , but i think it is a broader issue, because im running w `vm-driver=none`.

It looks like CRI-O out of the box on 0.35 tries to use  docker instead.

**Comment by jayunit100** [comment]
oh wait, this is a dupe of https://github.com/kubernetes/minikube/issues/3295 , closing

**Comment by afbjorklund** [comment]
CRI-O is supposed to be working, but maybe hasn't been tested fully with `none` driver ?
