### ISSUE TITLE
Use a more appropriate logging directory than /tmp

### ISSUE THREAD

**Issue by tv42** [kubernetes/minikube#3837]
It seems https://github.com/kubernetes/minikube/issues/468 has resurfaced again.
Running on Ubuntu 18.04.2, my $TMPDIR is ~/tmp.

```
tv@dark ~$ cd ~/tmp
tv@dark ~/tmp$ rm -rf minikube.*
tv@dark ~/tmp$ minikube version
minikube version: v0.35.0
tv@dark ~/tmp$ ls minikube.*
minikube.INFO@  minikube.dark.tv.log.INFO.20190309-173745.15058
tv@dark ~/tmp$ 
```

Also, needing to log to display the version number is a bit silly on its own...

**Comment by afbjorklund** [comment]
It is `console.go` that is doing the INFO logging for the version command.
``` go
	glog.Infof("Setting OutFile to fd %d ...", w.Fd())
	glog.Infof("isatty.IsTerminal(%d) = %v\n", fd, isT)
	glog.Infof("Setting ErrFile to fd %d...", w.Fd())
	glog.Infof("isatty.IsTerminal(%d) = %v\n", fd, isT)
```

**Comment by afbjorklund** [comment]
Apparently this happens in main, even _before_ we call the root command:
```
	console.SetOutFile(os.Stdout)
	console.SetErrFile(os.Stderr)
	cmd.Execute()
```

**Comment by tstromberg** [comment]
This behavior comes from using `glog`. It wouldn't be terrible if the output went elsewhere, so I'd be happy to approve any PR's that change this.
