### ISSUE TITLE
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

### ISSUE THREAD

**Issue by yzmedipally** [kubernetes/minikube#3845]
$ minikube start
o   minikube v0.35.0 on windows (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 184.42 MB / 184.42 MB  100.00% 0ss
!   Unable to start VM: create: creating: Unable to start the VM: D:\Softwares\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'D:\Softwares\cygwin64\home\Yugandhar\.minikube\machines\minikube\minikube\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

**Comment by tstromberg** [comment]
Sorry to hear that it failed. What version of VirtualBox are you running? It may be possible that VirtualBox 6.0.4 may fix this if you are not already running it.

To help solve this - Do you mind adding the output of: `minikube start --alsologtostderr -v=9`?

Thank you!

**Comment by NephelimDK** [comment]
Hi
Not sure if OP ever returned the requested log output
I am seeing the same issue on my machine which is a Windows 10 Enterprise with newest minikube and virtual box installed
This is the output from the `minikube start --alsologtostderr -v=9` operation
[VBoxHardening.log](https://github.com/kubernetes/minikube/files/3172492/VBoxHardening.log)

Also this is the output from the sc.exe operation that was suggested in the log:

`sc.exe query vboxdrv`

```SERVICE_NAME: vboxdrv
        TYPE               : 1  KERNEL_DRIVER
        STATE              : 1  STOPPED
        WIN32_EXIT_CODE    : 2  (0x2)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
```
Regards
Jon

**Comment by tstromberg** [comment]
@NephelimDK - It sounds like the VirtualBox kernel driver (VboxDrv.sys) stopped, which isn't something minikube should manage.

ttps://stackoverflow.com/questions/34778147/cannot-boot-windows-guest-in-virtualbox-without-kernel-module-error has a workaround, which is to run the following command as an administrator:

`sc.exe start vboxdrv`

I suggest uninstalling Virtualbox, rebooting, and reinstalling Virtualbox. Then open `msinfo32.exe` and visit Software Environment\System Drivers, and look at the state of `vboxdrv`.
