### ISSUE TITLE
Make MAC address settable

### ISSUE THREAD

**Issue by geiseri** [kubernetes/minikube#3848]
I use the `kvm2` driver on debian linux but when I create a new minikube instance I do not get the  ability to specify the IP or macaddress for the `--kvm-network` interface.  

This is annoying because I need to take the extra step of `minikube ssh` and check the IP address of `eth0`. 

It would be nice to be able to supply a static address of some sort so I can have a DHCP reservation or a well-known address.  One other option would be to offer the IP address of `eth0` as an option for `minikube ip`.  Thanks for minikube, its very nice for small deployments who do not want to fight the battle of the entire stack.

**Comment by tstromberg** [comment]
IP setting is covered in #2938 

I'll leave this issue open for setting the MAC address. Help wanted!

**Comment by tstromberg** [comment]
On second thought - I'm not convinced yet about adding the ability to set a MAC address. I just don't see the use case. Do you mind clarifying?

Making the IP settable is entirely reasonable.

**Comment by tstromberg** [comment]
Closing due to lack of updates. I'm not yet convinced of the necessity here, so I don't think we are likely to solve it. 

If someone provides a PR - I'd be OK with merging it.
