### ISSUE TITLE
status: "Error getting ssh host name for driver: IP not found"

### ISSUE THREAD

**Issue by zbelghali** [kubernetes/minikube#3849]
`minikube` command-line used:
minikube status
  - The full output of the command that failed
Error getting bootstrapper: getting kubeadm bootstrapper: command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - The output of the "minikube logs" command
  - Which operating system version was used
  Windows 10

**Comment by zbelghali** [comment]
$Minikube status 
On Windows 10
Error getting bootstrapper: getting kubeadm bootstrapper: command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found

**Comment by tstromberg** [comment]
This seems related to #3583

**Comment by tstromberg** [comment]
Can you confirm whether or not minikube v1.1 has the same issue?

Also, which hypervisor were you using?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by IvankaTashkova** [comment]
Hi! I'm experiencing the same issue! 

`minikube logs` output : 
X command runner
* Error:         [IP_NOT_FOUND] getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
* Advice:        The minikube VM is offline. Please run 'minikube start' to start it again.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3849
  - https://github.com/kubernetes/minikube/issues/3648

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new

`minikube status` : 
X Error getting bootstrapper
* Error:         [IP_NOT_FOUND] getting kubeadm bootstrapper: command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
* Advice:        The minikube VM is offline. Please run 'minikube start' to start it again.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3849
  - https://github.com/kubernetes/minikube/issues/3648

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new

I'm trying to Install Kubernetes with minikube. Unfortunately, I get every known error by now!  
minikube version v1.2.0

**Comment by zbelghali** [comment]
I figured it out a while ago. What OS are you running?

**Comment by IvankaTashkova** [comment]
Windows 10

**Comment by zbelghali** [comment]
Ok, same here. So here is what worked for me. 

-- I'm using MS HyperV.

Here are the steps:

*** RUN AS ADMIN ***

--In PowerShell run the following:
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All

-- In Hyper-V manager, in Settings, Add a Virtual Switch to Network Adapter. Call the new switch to something like "minikube1"

-- Once that's done:
run the following (*** RUN AS ADMIN ***)
minikube start -p minikube1 --vm-driver "hyperv" --hyperv-virtual-switch "minikube" --disk-size 10g --memory 4096 --v 

then to confirm it's running, run:
minikube status -p minikube1

**Comment by garimagupta779** [comment]
Not working
