### ISSUE TITLE
Unable to start VM: Error getting state for host: machine does not exist

### ISSUE THREAD

**Issue by Nikjz** [kubernetes/minikube#3864]
I tried executing minikube start and got the following error - 

C:\Users\Nikhil Singh>minikube start
o   minikube v0.35.0 on windows (amd64)
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
!   Unable to start VM: Error getting state for host: machine does not exist

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

 

Windows 10

**Comment by tstromberg** [comment]
I think what's happened here is that you have an old minikube configuration laying around, but have deleted the underlying VM in Virtualbox. 

You should be able to get passed this by running `minikube delete` to delete the old minikube config and then `minikube start` will be able to create a new configuration and VM.

Please let me know if this helps!

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube and run `minikube delete` to remove the previous cluster state.

If the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!

**Comment by CloudCrusader** [comment]
I manually removed a VM called minikube from Hyper-V on W10 Enterprise 1903 , 
running the 'minikube delete' command results in error.

> [stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".

running the 'minikube delete -p minikube' results in same error.
(minikube v1.2.0)

**Comment by wildanr** [comment]
I'm using Windows 10, minikube version v1.5.2, with Virtual Box and facing this problem after several attempt of minikube stop, minikube delete, deleting .minikube, and repeat.

After several minutes of frustration, I finally get it to work by simply restarting the computer.

**Comment by msalaslo** [comment]
I was using Windows 10 + minikube v1.5.2 and was facing the same issue. 
After upgrading minikube to v1.12.1 and executing:
```
minikube delete
minikube start 
```
everything worked fine.
