### ISSUE TITLE
Expose pod-network-cidr on kubeadm

### ISSUE THREAD

**Issue by ozdanborne** [kubernetes/minikube#3865]
Getting Calico working in Kubernetes / Minikube can be tricky because you need to set the pod network cidr on multiple components (apiserver, controller-manager, and proxy) individually.

Kubeadm has made this easier by tying all three of those flags to a single "high-level" flag - `--pod-network-cidr`.

Now that minikube is using kubeadm under the hood, could we expose the `--pod-network-cidr` flag on it?

After a brief look at the code, I think we'd just need to template this value: https://github.com/kubernetes/minikube/blob/3714bbd787f977b3d3a8b5460a249aff901e0f64/pkg/minikube/bootstrapper/kubeadm/templates.go#L84

**Comment by tstromberg** [comment]
This sounds like a great idea, and I would be happy to approve any PR's that make it so. Help wanted!

**Comment by 11janci** [comment]
I would like to take this if no objections

**Comment by hswong3i** [comment]
With my latest founding we could run minikube + flannel without `kubeadm --pod-network-cidr`, see

* https://github.com/alvistack/ansible-role-minikube/blob/afdf7b937a26e3e52e2cc68beab86cb6909022d4/tasks/main.yml#L90
* https://github.com/alvistack/ansible-role-minikube/blob/afdf7b937a26e3e52e2cc68beab86cb6909022d4/molecule/ubuntu-18.04/playbook.yml#L34

From https://github.com/coreos/flannel/blob/master/Documentation/troubleshooting.md#kubernetes-specific what we really needed are kubelet's `--pod-cidr=<cidr>` and controller-manager's `--allocate-node-cidrs=true --cluster-cidr=<cidr>`, so something like this:

```
minikube start \
    --extra-config=controller-manager.allocate-node-cidrs=true \
    --extra-config=controller-manager.cluster-cidr=10.233.64.0/18 \
    --extra-config=kubeadm.ignore-preflight-errors=FileContent--proc-sys-net-bridge-bridge-nf-call-iptables,SystemVerification \
    --extra-config=kubelet.cgroup-driver=systemd \
    --extra-config=kubelet.network-plugin=cni \
    --extra-config=kubelet.pod-cidr=10.233.64.0/18 \
    --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf \
    --kubernetes-version=v1.14.1 \
    --network-plugin=cni \
    --vm-driver=none

curl -skL https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml > /tmp/kube-flannel.yml
sed -i 's/10.244.0.0\/16/10.233.64.0\/18/g' /tmp/kube-flannel.yml
kubectl apply -f /tmp/kube-flannel.yml
```
