### ISSUE TITLE
open <user>.minikube\machines\minikube\config.json: The system cannot find the file specified.

### ISSUE THREAD

**Issue by goodwinmcd** [kubernetes/minikube#3866]
Command:
`minikube start`
Returns
> o   minikube v0.35.0 on windows (amd64)
> !   Unable to start VM: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore: open C:\Users\goodw\.minikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> *   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> -   https://github.com/kubernetes/minikube/issues/new

minikube delete
> !   Failed to delete cluster: open C:\Users\goodw\.minikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> *   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> -   https://github.com/kubernetes/minikube/issues/new

I've tried deleting the .minikube file manually and no luck. Says I require permission from DESKTOP-UTI3DC7/username to make changes to this folder. I'm assuming that's the VM? It seems like minikube is in some half installed state and I would like to just start from scratch again. 

`minikube logs`
returns 
> !   api load: filestore: open C:\Users\goodw\.minikube\machines\minikube\config.json: The system cannot find the file specified.
> 
> *   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> -   https://github.com/kubernetes/minikube/issues/new

Using windows 10 pro. 

I tried to start minikubes originally with 
`minikube start  vm-driver=hyperv  hyperv-virtual-switch=my_network_switch`
It seemed to have made the cluster but then hung. And then I couldn't run any minikube commands. 

Let me know if there is any other information I can provide.

**Comment by tstromberg** [comment]
Two issues:

- Is it possible that minikube was started with elevated privileges (Administrator Rights) before? It may be that running it in the same manner now might help. 

The permissions should all be outside the VM - if you grant yourself privileges locally in Windows, it should also address this problem.

One quirk I notice here is that the path is listed as `C:\Users\goodw.minikube\` instead of `C:\Users\goodw\.minikube\`. That seems like a bug, if true.

**Comment by goodwinmcd** [comment]
Hey, thanks for the quick response. I believe I originally tried running the `minikube start` command without privileges and ran into a access issues. So I reran it with admin rights. All the commands in the original post were run with administrator rights. 

That was a typo. The file is in `C:\Users\goodw\.minikube\`.

**Comment by idrobinson** [comment]
Hi, I have just reached a halt due to this issue. I am running Win 10 Enterprise. I have Hyper-V feature enabled. I am running Docker Desktop ok. I have created an External Virtual Switch (via the Hyper-V manager). I ran Windows Powershell (admin) from the menu gained via a right click on the Start icon. In that I ran the command: minikube start --vm-driver hyperv
I got the error above, that it could not find the config.json file. Now minikube appears to have a hubg cluster which never goes away (whatever I try). I cannot use minikube delete or any minikube cmd (like status). I am working in a commercial situation and am now stuck. I would appreciate a fix soon, perhaps there is a tag priority/important-now ? ;-)
Any response would be welcome. I am also here to help with any details or actions that I can.

**Comment by idrobinson** [comment]
I have arrived at the office and this thread is the first thing that I have looked at. I see no comments yet. Can there at least be a comment posted to say that this has been read?
There are labels attached to this issue: if you wish more evidence or information - ask me.

This morning the cmd produces:

PS C:\WINDOWS\system32> minikube start --vm-driver hyperv
* minikube v1.1.0 on windows (amd64)
E0529 09:25:49.543546   35484 start.go:529] StartHost: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore: open C:\Users\ianro\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Unable to start VM: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore: open C:\Users\ianro\.minikube\machines\minikube\config.json: The system cannot find the file specified.

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

and then:

PS C:\WINDOWS\system32> minikube delete

X Failed to delete cluster: open C:\Users\ianro\.minikube\machines\minikube\config.json: The system cannot find the file specified.

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

Yes, it is unexpected, not sure if you love to hear from me ;-) (or do you hear at all?).

**Comment by johnnyfrx** [comment]
All I can add right now is "Me Too"!

**Comment by goodwinmcd** [comment]
Yup, never solved the issue. Started pursuing alternative cluster management software.

**Comment by tstromberg** [comment]
Raising the priority on this. Could someone who runs into this please share the output of:

`minikube start <options> --alsologtostderr -v=8`

I suspect the bug is here, but I can't figure it out. Help wanted!

https://github.com/kubernetes/minikube/blob/db37c03063359eb0955b95f4b16cfecfdb7e9a2f/pkg/minikube/constants/constants.go#L110

**Comment by afbjorklund** [comment]
All of the example output above looks broken, like it "forgot" to add the directory when joining ?

`open C:\Users\goodw.minikube\machines\minikube\config.json: The system cannot find the file specified.`

`open C:\Users\ianro.minikube\machines\minikube\config.json: The system cannot find the file specified.`

So it looks like something goes horribly wrong in the "filepath.Join" call, on the Windows platform ?

**Comment by afbjorklund** [comment]
Cannot reproduce, works fine in Wine.

``` go
func main() {
	path := filepath.Join(homedir.HomeDir(), ".minikube")
	fmt.Printf("Join: %s\n", path)
}
```
Some noise, but the filepath.join is OK:

``` console
$ GOOS=windows go run join.go 
err:winedevice:ServiceMain driver L"WineBus" failed to load
fixme:process:SetProcessPriorityBoost (0xffffffffffffffff,1): stub
Join: C:\users\anders\.minikube
$ GOOS=linux go run join.go 
Join: /home/anders/.minikube

```

**Comment by idrobinson** [comment]
This may be silly, but don't the errors above miss out a '\' between the user foldere and the initial .minicube folder? e.g. shouldn't C:\Users\ianro.minikube\... be C:\Users\ianro\.minikube\ ?
If so, is the join at fault or the params into the join at fault? Is the issue this simple?

**Comment by AyushiHarkawat** [comment]
Hi, I was also facing the same issue and was not able to delete the .minikube folder manually as well.
On deleting .minikube folder It deleted all the files but was not able to delete the **machine**  folder under **.minikube**.

So I found a workaround of this issue:
1. First I did shut down the Virtual machine that I created in the Hyper-V Manager and then delete that machine so it deleted all the virtual machine under the **machine** folder.
2. And following that, I was successfully able to delete the .minikube folder manually.
3. Finally, I ran the initial command: minikube start --vm-driver hyperv --hyperv-virtual-switch="<Virtual_Switch_name>" and it was successful.

Hopefully, it helps!

**Comment by idrobinson** [comment]
Well, things have improved. I used the steps above (1-3 AyushiHarkawat), added step 2.5 Turn Hyper-V back on again (Docker Desktop won't run without it).
It is true that after manually deleting the .minikube folder minikube and the VM did attempt to be installed and created. But the start failed. The initial default RAM was 2048. I increased this to 6144 but still it would not start - not enough memory. Anyone have ideas for how much RAM is actually required? I have 8192 in total, so the limit is close.

**Comment by idrobinson** [comment]
PS C:\WINDOWS\system32> minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch" --memory=4096 --alsologtostderr -v=8
>>
W0617 13:14:52.171285   22292 root.go:151] Error reading config file at C:\Users\ianro\.minikube\config\config.json: open C:\Users\ianro\.minikube\config\config.json: The system cannot find the file specified.
I0617 13:14:52.175382   22292 notify.go:128] Checking for updates...
* minikube v1.1.1 on windows (amd64)
I0617 13:14:52.663283   22292 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.1.1.iso
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at C:\Users\ianro\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\etcd_3.3.10
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.14.3 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.14.3
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.14.3 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.14.3
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.10.1
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.14.3 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.14.3
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\coredns_1.3.1
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.14.3 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.14.3
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0
I0617 13:14:52.666285   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13
I0617 13:14:52.667286   22292 cache_images.go:305] Attempting to cache image: k8s.gcr.io/pause:3.1 at C:\Users\ianro\.minikube\cache\images\k8s.gcr.io\pause_3.1
I0617 13:14:52.667286   22292 start.go:721] Saving config:
{
    "MachineConfig": {
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.1.1.iso",
        "Memory": 4096,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "hyperv",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "Primary Virtual Switch",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "Hidden": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.14.3",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    }
}
I0617 13:14:52.695284   22292 cluster.go:95] Skipping create...Using existing machine configuration
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0617 13:14:52.705288   22292 cache_images.go:302]
I0617 13:14:53.373284   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0617 13:14:53.472282   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13
I0617 13:14:53.664282   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0
I0617 13:14:53.677282   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\coredns_1.3.1
I0617 13:14:53.684282   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.10.1
I0617 13:14:53.689282   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.14.3
I0617 13:14:53.699285   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.14.3
I0617 13:14:53.702290   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0617 13:14:53.702290   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.14.3
I0617 13:14:53.718284   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.14.3
I0617 13:14:53.738282   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13
I0617 13:14:53.738282   22292 cache_images.go:329] OPENING:  \\?\Volume{14fda315-5c1e-4a53-9a93-fe9ed841b05a}\Users\ianro\.minikube\cache\images\k8s.gcr.io\etcd_3.3.10
[stdout =====>] : Off

[stderr =====>] :
I0617 13:14:55.289286   22292 cluster.go:114] Machine state:  Stopped
* Restarting existing hyperv VM for "minikube" ...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minikube
[stdout =====>] :
[stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Ran out of memory (0x8007000E).
'minikube' failed to start. (Virtual machine ID C7916CFA-3CE3-4787-B1F3-3FA4EE78DC95)
Not enough memory in the system to start the virtual machine minikube with ram size 4192 megabytes. (Virtual machine
ID C7916CFA-3CE3-4787-B1F3-3FA4EE78DC95)
'minikube' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID
C7916CFA-3CE3-4787-B1F3-3FA4EE78DC95)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM


E0617 13:14:57.165347   22292 start.go:529] StartHost: start: exit status 1
I0617 13:14:57.166349   22292 utils.go:122] non-retriable error: start: exit status 1
W0617 13:14:57.167347   22292 exit.go:100] Unable to start VM: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

An example...

**Comment by idrobinson** [comment]
By the way, it is the GitHub markdown that is taking out the folder slash in something like:
 C:\Users\ianro\.minikube\config\config.json
It didn't happen here, but it does in what I posted above. The line here was taken from that block, near the top. You can see that the \ is missing there but present here. So don't consider that this is where the error is, it is a red herring. :-)

**Comment by knumchoke** [comment]
In my case.
I am running minikube in windows using Hyper-V. I also stuck at this error and cannot create new cluster with same name as deleted (but minikube start <cluster_name> work because the <cluster_name> folder inside 'C:\Users\username\.minikube' were not existed.)

And when I tried to remove the 'C:\Users\username\.minikube' folder and its sub, the windows pop-up told me that Hyper-V is using some file and it cannot be remove. This make me noticed something. So, it come to my solution to fix this.
1. Stop Hyper-V service.
2. remove 'C:\Users\username\.minikube' and 'C:\Users\username\.kube'
3. run `minikube start --vm-driver hyperv --hyperv-virtual-network <hyperv-ext-net> --logtostderr` again to start a new cluster

And now my minikube cluster is working.

**Comment by tuckerthomas** [comment]
If you're on Windows and trying to user Hyper-V make sure `systeminfo` outputs:
```
Hyper-V Requirements:     VM Monitor Mode Extensions: Yes
                          Virtualization Enabled In Firmware: Yes
                          Second Level Address Translation: Yes
                          Data Execution Prevention Available: Yes
```
I was getting:
```
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\tucker\.minikube\machines\minikube\config.json: The system cannot find the file specified.
```
I did a bios update recently and it defaulted VT-d off and that was causing the config file error since the VMs weren't starting. For example, `Virtualization Enabled In Firmware: Yes` was set to `No`.

Anyway, **make sure VT-d is enabled in your BIOS** if you've done an upgrade recently or haven't checked. Then open Hyper-V and delete any VMs minikube tried to make and do a `minikube delete`. After that, I did `minikube start --vm-driver hyperv` and its working like a charm.

**Comment by szymczakk** [comment]
Hi, maybe it will help someone but in my case my "host" does not had enough memory to start minukube VM (I had 3gb with dynamic allocation).

What I've done to find it out:
1. `minikube start`
2. just after creating my VM I stopped minikube
3. in hyperv manager I tried to run "minikube" VM on my own and get info that I dont have enough memory.

Hope it will help someone.

**Comment by Srinivas289** [comment]
ran into same issue on windows, got over this, by
delete and start.

If you see error while deleting, go to Hyper-V Manager (through start) and remove minikube Virtual Machine, and try a delete couple of times.

**Comment by tstromberg** [comment]
This no longer occurs in minikube v1.9.
