### ISSUE TITLE
Unable to start VM: looking up domain: virError(Code=0, Domain=0, Message='Missing error'

### ISSUE THREAD

**Issue by ferozpuri** [kubernetes/minikube#3867]
Hi

I am using centos 7, i am trying to setup minikube. i am getting error after i start minikube start command

this is error i am getting right now

> Unable to start VM: Error getting state for host: getting connection: looking up domain: virError(Code=0, Domain=0, Message='Missing error')

**Comment by tstromberg** [comment]
Since I can't see the full output of your start command, I can't tell, but running `minikube delete` may or may not work around this issue. This message may indicate that minikube found an old VM configuration, but the underlying VM is gone. If this does not fix your problem, do you mind providing the full output of `minikube start --alsologtostderr -v=8`? 

Also, I am curious about the output of:

`libvirtd --version`

and:

`virt-host-validate`

Thanks for the bug report!

**Comment by ferozpuri** [comment]
Thank for your response @tstromberg 
Its not work for me, I working on centos 7 vm.  here is complete error

> [root@kubemaster ~]# minikube start --vm-driver=kvm2

> o   minikube v0.35.0 on linux (amd64)
> i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
> !   Unable to start VM: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')
> 
> *   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> -   https://github.com/kubernetes/minikube/issues/new

**Comment by afbjorklund** [comment]
Sounds like libvirt is not working completely, on your VM ?

**Comment by ferozpuri** [comment]
@afbjorklund , I have verified the status of service libvirt, this working fine. Please see below

> [root@kubemaster ~]# systemctl status libvirtd.service

●

>  libvirtd.service - Virtualization daemon
>    Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
>    Active: active (running) since Wed 2019-03-13 17:20:24 PKT; 5h 44min ago
>      Docs: man:libvirtd(8)
>            https://libvirt.org
>  Main PID: 6103 (libvirtd)
>     Tasks: 19 (limit: 32768)
>    CGroup: /system.slice/libvirtd.service
>            ├─ 6103 /usr/sbin/libvirtd
>            ├─10547 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/minikube-net.conf --leasefile-ro --dhcp-script=...
>            └─10549 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/minikube-net.conf --leasefile-ro --dhcp-script=...
> 
> Mar 13 17:33:16 kubemaster dnsmasq-dhcp[10547]: DHCP, IP range 192.168.39.2 -- 192.168.39.254, lease time 1h
> Mar 13 17:33:16 kubemaster dnsmasq-dhcp[10547]: DHCP, sockets bound exclusively to interface virbr0
> Mar 13 17:33:16 kubemaster dnsmasq-dhcp[10547]: read /var/lib/libvirt/dnsmasq/minikube-net.hostsfile
> Mar 13 17:33:16 kubemaster libvirtd[6103]: 2019-03-13 12:33:16.881+0000: 6105: error : virCapabilitiesDomainDataLoo...pe=kvm
> Mar 13 17:33:16 kubemaster libvirtd[6103]: 2019-03-13 12:33:16.881+0000: 6105: error : virCapabilitiesDomainDataLoo...pe=kvm
> Mar 13 17:33:26 kubemaster libvirtd[6103]: 2019-03-13 12:33:26.282+0000: 6103: error : virNetSocketReadWire:1806 : ... error
> Mar 13 17:34:36 kubemaster libvirtd[6103]: 2019-03-13 12:34:36.026+0000: 6103: error : virNetSocketReadWire:1806 : ... error
> Mar 13 17:54:32 kubemaster libvirtd[6103]: 2019-03-13 12:54:32.664+0000: 6103: error : virNetSocketReadWire:1806 : ... error
> Mar 13 21:00:57 kubemaster libvirtd[6103]: 2019-03-13 16:00:57.254+0000: 6103: error : virNetSocketReadWire:1806 : ... error
> Mar 13 21:09:45 kubemaster libvirtd[6103]: 2019-03-13 16:09:45.646+0000: 6103: error : virNetSocketReadWire:1806 : ... error
> Hint: Some lines were ellipsized, use -l to show in full.

**Comment by afbjorklund** [comment]
Does it work OK for creating other VMs, for instance `docker-machine` or something ?

`docker-machine create -d kvm`

https://github.com/dhiltgen/docker-machine-kvm/#quick-start-instructions

As per above, you probably want to delete the previous minikube VM before trying again.

**Comment by ferozpuri** [comment]
@afbjorklund , so nice of you. I am unable to run docker-machine commands, but i have already installed docker at my centos machine. any help please?

**Comment by afbjorklund** [comment]
If you are unable to run docker-machine with kvm, and unable to run minikube with kvm2 -
then I would say it looks like something is wrong with your libvirt installation. Try VirtualBox ?

**Comment by tstromberg** [comment]
@ferozpuri - Please attach the output of:

`libvirtd --version`

and:

`virt-host-validate`

Also, please see if `minikube delete` fixes your problem, as it could just be related to a VM no longer existing.

Thanks!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by aissarmurad** [comment]
`minikube delete` works for me
