### ISSUE TITLE
precreate: VirtualBox is configured with multiple host-only adapters with the same IP

### ISSUE THREAD

**Issue by gitpop** [kubernetes/minikube#3870]
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

Output of the command:
$ minikube start
o   minikube v0.35.0 on linux (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
!   Unable to start VM: create: precreate: VirtualBox is configured with multiple host-only adapters with the same IP "192.168.99.1". Please remove one

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

$ minikube logs
!   api load: filestore: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
hyang@UB33:~$

**Comment by afbjorklund** [comment]
Did you try addressing the configuration issue ?

`VirtualBox is configured with multiple host-only adapters with the same IP "192.168.99.1". Please remove one`

**Comment by gitpop** [comment]
Thank you. You are right. I used the VirtualBox tool to remove all the dangling host virtual adapters then it worked. I noticed that these virboxnet#  interfaces are left over after "minikube delete" . The delete command removed the vms but didn't clean up the interfaces.  I repeated a couple of times of start and delete, the virtual interfaces that created by minikube always left there without cleanup.

**Comment by medyagh** [comment]
@gitpop I am curious, are you running this on a cloud VM ? like compute engine ?

**Comment by medyagh** [comment]
for anyone who might search for this issue, I was able to fix it this way:

I was able to get rid of them this way
first get list of adaptors with the ip :

```
vboxmanage list -l hostonlyifs | grep 192.168.99.1 -5 | grep -w "Name:" |  awk '{$1=""; print $0}'

```
and remove each returned vboxnet
```vboxmanage hostonlyif remove INSERTNAME```


I confirm this issue exists, on the virtualbox test box we have more than 21 left over adapters

```
 vboxmanage list -l hostonlyifs | grep -w "Name:" |  awk '{$1=""; print $0}'
 vboxnet21
 vboxnet19
 vboxnet12
 vboxnet20
 vboxnet18
 vboxnet7
 vboxnet1
 vboxnet10
 vboxnet14
 vboxnet6
 vboxnet15
 vboxnet9
 vboxnet8
 vboxnet17
 vboxnet16
 vboxnet5
 vboxnet3
 vboxnet13
 vboxnet2
 vboxnet4
 vboxnet11
 vboxnet0

```

**Comment by medyagh** [comment]
@gitpop  would this help ?
```
vboxmanage list -l hostonlyifs | grep 192.168.99.1 -5 | grep -w "Name:" |  awk '{$1=""; print $0}'

```
and remove each returned vboxnet
```vboxmanage hostonlyif remove INSERTNAME```


I confirm this issue exists, on the virtualbox test box we have more than 21 left over adapters

```
 vboxmanage list -l hostonlyifs | grep -w "Name:" |  awk '{$1=""; print $0}'
 vboxnet21
 vboxnet19
 vboxnet12
 vboxnet20
 vboxnet18
 vboxnet7
 vboxnet1
 vboxnet10
 vboxnet14
 vboxnet6
 vboxnet15
 vboxnet9
 vboxnet8
 vboxnet17
 vboxnet16
 vboxnet5
 vboxnet3
 vboxnet13
 vboxnet2
 vboxnet4
 vboxnet11
 vboxnet0

```

**Comment by medyagh** [comment]
or if you want it in one command 

"vboxmanage list -l hostonlyifs | grep 192.168.99.1 -5 | grep -w "Name:" |  awk '{$1=""; print $0}'  | xargs -l vboxmanage hostonlyif remove"

**Comment by rootsongjc** [comment]
Remove one of the boxes with the same IP address, that will solve this problem.

**Comment by tstromberg** [comment]
Closing as there is a workaround.

**Comment by Pictor13** [comment]
> or if you want it in one command, one important thing I noticed, you have to deleted it with the same user that runs minikube.
> 
> ```
> vboxmanage list -l hostonlyifs | grep 192.168.99.1 -5 | grep -w "Name:" |  awk '{$1=""; print $0}'  | xargs -l vboxmanage hostonlyif remove
> ```

After removing the vboxnet interfaces I get now:

```
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: creating: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet2 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet2 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
```

Any suggestion for fixing?

**Comment by bgshacklett** [comment]
@Pictor13  Per the documentation (https://minikube.sigs.k8s.io/docs/drivers/virtualbox/):
> On Linux, Mac OS X and Oracle Solaris with VirtualBox >= 6.1.28, [only IP addresses in the 192.68.56.0/21 range are allowed for host-only networking by default](https://www.virtualbox.org/manual/ch06.html#network_hostonly). Passing a disallowed value to --host-only-cidr will result in a VirtualBox access denied error: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available).

I was able to fix this by setting my VM Driver in my config, rather than passing it on the command line:
```
minikube config set vm-driver virtualbox
minikube delete
minikube start
```

For some reason, this chose the documented default range of `192.168.59.1/24`, rather than `192.168.99.1/24`, which it was choosing when I passed the `vm-driver` argument on the command line. Perhaps the default is calculated differently when the `vm-driver` option is passed?

**Comment by qeeera** [comment]
If you use Docker Toolbox you need do:
1. open Virtualbox->File->Host Network Manager
2. If you see a lot of adapters, remove some of them. (5-8)
3.Run Docker Quickstart
