### ISSUE TITLE
Unable to start VM

### ISSUE THREAD

**Issue by jq** [kubernetes/minikube#3871]
follow https://www.kubeflow.org/docs/started/getting-started-minikube/
Environment:
Minikube version : v0.35
OS : macOS Mojave 10.14 (18A391)
VM Driver : VirtualBox 6.0
ISO version : minikube-v0.35.iso
./setup-minikube.sh
Unable to start VM: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
minikube start gave same error

**Comment by jq** [comment]
tried vmware fusion 11, can't start the minikube too

**Comment by VitorLuizC** [comment]
How did you solved this error?
