### ISSUE TITLE
efk: Discover times out, more info says: "Error: Request Timeout after 30000ms"

### ISSUE THREAD

**Issue by seanleblanc** [kubernetes/minikube#3874]
I'm trying to use EFK on minikube on OSX. Is there any kind of how-to on how this should work? It seems all the pods come up (in kube-system namespace). 

Then, I go to kibana-logging endpoint (minikube-ip:30003 in this case), and I need to set up an index. I do that, then go to discover, and it times out after 30 seconds? If I expand the "More info" at the top, it says Error: Request Timeout after 30000ms 
  at http://192.168.99.101:30003/bundles/kibana.bundle.js?v=15543:12:4431
  at http://192.168.99.101:30003/bundles/kibana.bundle.js?v=15543:12:4852

**Comment by tstromberg** [comment]
Are you using the EFK addon?

If so, we don't have any specific documentation that I'm aware of, but I did find this article: https://medium.com/@jbsazon/aggregated-kubernetes-container-logs-with-fluent-bit-elasticsearch-and-kibana-5a9708c5dd9a

I'm not sure about the error you are seeing, but it doesn't sound like it should behave that w ay.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
