### ISSUE TITLE
Ability to add disks to the minikube VM on Hyperkit?

### ISSUE THREAD

**Issue by leseb** [kubernetes/minikube#3883]
While adding extra disks with the kvm2 driver is easy, I couldn't find anything to add disks on `hyperkit`. Anyone already doing this perhaps?

Thanks!

**Comment by tstromberg** [comment]
`minikube mount` might help here. Is there something else you are trying to do with the disks?

**Comment by tstromberg** [comment]
Also, do you mind mentioning where you saw something about adding disks with kvm2? It would help me understand a bit better what you are comparing against. Thanks!

**Comment by leseb** [comment]
@tstromberg thanks for the reply. I basically trying to add more disks to my VM so they can be consumed by my pods.
For kvm2, you can simply do:

```
 sudo qemu-img create -f raw $IMAGE 30G
sudo virsh attach-disk rook $IMAGE vdb --cache none --persistent
```

And you will get more disks attached.

Makes sense?

**Comment by tstromberg** [comment]
Evidently hyperkit supports this:

https://github.com/linuxkit/linuxkit/blob/master/docs/platform-hyperkit.md#disks

It might be nice to add something to minikube to pass this kind of thing in.

**Comment by BlaineEXE** [comment]
I plan to start some work to try to add functionality into minikube to allow creating extra disks. I anticipate that I will only have the ability to do so for some backends, notably with hyperkit and vbox as I am on Mac. Using the docker machine backend likely won't be able to support this option at all. Is this okay? Are there examples of features that aren't supported by all backends I might use as reference?

I wonder if an alternate option might be to implement it as an addon. Does anyone have any suggestions?

/reopen
/remove-lifecycle rotten
