### ISSUE TITLE
Support for multiple architectures (beyond amd64)

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#3890]
Back in '16 when the project was started, there was discussions about multiple architectures (#5)

But in the the end it was decided to focus on `amd64`, mosty because of the hypervisors (~#955~).
Other architectures were better off handled by kubeadm, than supported by minikube (localkube)

Now things have changed a bit, and we might consider more architectures - like e.g. ARM ?

Kubernetes supports:
* **amd64**
* arm
* arm64
* ppc64le
* s390x

for the binaries.

I'm not sure which of these make sense as desktop systems, so I think it will be mostly `arm64`.

---

I added support for cross-compiling for [any](https://golang.org/doc/install/source#environment) Go architecture in #3887 - just like current OS cross.

If we get some hypervisor-less installation going, we _could_ consider supporting another arch.
But for now, you are still better off using `kubeadm` directly on these - use them with `kubectl` .

Added this story, since there were some discussions ongoing in older PR:  #2171 #2455 #2881

The main issue is how to test anything but amd64 in CI, given the current existing infrastructure.
Before that testing is in place, there can't really be any official support for any other architecture.

**Comment by afbjorklund** [comment]
See also this document, for the bigger picture:
https://github.com/kubernetes/community/blob/master/contributors/design-proposals/multi-platform.md

**Comment by Pensu** [comment]
+1 for this. Since #3368 is merged, now the kubeadm and kubelet binaries are downloaded according to the ARCH minikube is running on. Kubeadm is already supported on multiple-archs. 

It might not be feasible to support all the hypervisors on all the archs, but there could be a base line like `none` driver to skip VM creation part.

**Comment by afbjorklund** [comment]
@Pensu : that is what I meant with hypervisor-less, currently we _only_ support install minikube on VMs - where the `none` driver is mostly for user-supplied VMs using some other hypervisor and/or driver...

This still makes the situation on these architectures "unknown", since we have no idea what kind of VM will be used ? The use case of running the kubernetes master locally with minikube is **not** well explored.


This document tries to describe the current situation:
https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

**Comment by Pensu** [comment]
@afbjorklund Yeah, I agree. Probably we can standardise the VM type and config(like CPU, memory etc) somehow?

**Comment by afbjorklund** [comment]
The default VM size is pretty well standardised, it is the minimum requires of Kubernetes - 2 CPU, 2G RAM:

https://kubernetes.io/docs/setup/independent/install-kubeadm/#before-you-begin

We are probably going to relax this to 1 vCPU and 1G RAM for minions*, but the master node needs twice.

* for multi-node, where you join additional minikube nodes beyond the first one

**Comment by tstromberg** [comment]
This has somewhat landed with the s390x support. That said, we don't push release binaries out for anything other than amd64.

What is the exit criteria for this issue?

**Comment by afbjorklund** [comment]
I was thinking `arm64`, but then again who uses virtualization on that platform ? Can close it with `s390x`.

**Comment by salamani** [comment]
On s390x it is used without virtualization with option none.

**Comment by PeteLawler** [comment]
> I was thinking `arm64`, but then again who uses virtualization on that platform ? 
I've just been toying with building debian arm64 on RPi so I can get a 64bit mongodb going for simple testing and was looking to use minikube over microk8s. I'm open to being convinced I'm on the totally wrong approach, but yeah to answer your question - me, I'm crazy enough to create my own use case hehe.

**Comment by tstromberg** [comment]
Closing in lieu of more specific architecture requests. Adding support for other architectures is now a trivial Makefile change.
