### ISSUE TITLE
Is it possible to run minikube in Virtualbox (running on Mac) VM?

### ISSUE THREAD

**Issue by shouhong** [kubernetes/minikube#390]
I have a Virtualbox running on Mac. Then I created a ubuntu14 VM in the Virtualbox. Is it possible to run minikube in this ubuntu14 VM?

I tried and it did not work because the ubuntu14 VM's "VT-X/AMD-v" is not enabled. How to enable a Virtualbox VM's "VT-X/AMD-v"? Note: My Virtualbox is running on Mac, not on Windows/Linux.

**Comment by jimmidyson** [comment]
You would need to enable nested or passthrough virtualization to do this. Not sure exactly how to do this on a Mac with virtualbox.

Why do you want to do this?

**Comment by shouhong** [comment]
minikube can run on Mac and Linux. For Mac, I can run it well. Now I want to test running minikube on Linux. So I created a Linux VM in VirtualBox and encountered the above problem.

**Comment by jimmidyson** [comment]
I & many others run it on Linux & it works fine :) Nested virtualization can be a problem, but not one that minikube will solve for you I'm afraid. I'm going to close this as, unless I'm missing something, I don't think it's something that we need to support. Please feel free to send in a PR with docs on how to enable if you figure it out.

FYI I found https://www.virtualbox.org/ticket/4032 which is really old ticket which, of I read it correctly, says nested virtualization is still not implemented in virtualbox.
