### ISSUE TITLE
Unable to start VM: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

### ISSUE THREAD

**Issue by nekooei** [kubernetes/minikube#3900]
I am using Centos 7 VPS
I run this command
`minikube start --cpus 1 --memory 1024 --kubernetes-version v1.13.0`
but the result is : 

> 😄  minikube v0.35.0 on linux (amd64)
> 🔥  Creating virtualbox VM (CPUs=1, Memory=1024MB, Disk=20000MB) ...
> 💣  Unable to start VM: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
> 
> 😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> 👉  https://github.com/kubernetes/minikube/issues/new

also I run `lscpu | grep Virtualization` and the result is: 
`Virtualization type:   full`

my cpu model is
![image](https://user-images.githubusercontent.com/12533428/54557160-c1345100-49cf-11e9-9331-abd47da78c0d.png)

**Comment by afbjorklund** [comment]
Looks like your VMware doesn't have nested virtualization supported fully ?

**Comment by nekooei** [comment]
how can i check that ?

**Comment by tstromberg** [comment]
Do you mind trying this:

`minikube start --no-vtx-check`

It's hard to check from here if it's due to the new upstream checks in place, or if things might actually work.  Also, I suspect that passing in that small amount of memory might yield further issues down the line.

**Comment by nekooei** [comment]
Thanks, this works for me

**Comment by MateuszZiolek** [comment]
well i have next step issu
`root@debiandev:/home/x# lscpu | grep Virtualization
Virtualization type:   full
root@debiandev:/home/x# minikube start --no-vtx-check
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.631564 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
`

**Comment by darrylsepeda** [comment]
> Do you mind trying this:
> 
> `minikube start --no-vtx-check`
> 
> It's hard to check from here if it's due to the new upstream checks in place, or if things might actually work. Also, I suspect that passing in that small amount of memory might yield further issues down the line.

Hi @tstromberg, I tried your suggestion but encounter an error:
```
minikube start --no-vtx-check
😄  minikube v1.0.1 on linux (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.759580 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

Do you know what is this about? I'm trying to run kubernetes in VPS.

**Comment by gbraad** [comment]
Your provider would need to offer 'Nested virtualization' or
virtualization passthrough.

On Sun, May 12, 2019 at 6:13 PM Darryl <notifications@github.com> wrote:
>
> Do you mind trying this:
>
> minikube start --no-vtx-check
>
> It's hard to check from here if it's due to the new upstream checks in place, or if things might actually work. Also, I suspect that passing in that small amount of memory might yield further issues down the line.
>
> Hi @tstromberg, I tried your suggestion but encounter an error:
>
> minikube start --no-vtx-check
>
>   minikube v1.0.1 on linux (amd64)
>
> 🤹  Downloading Kubernetes v1.14.1 images in the background ...
>
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
>
>
>
>   Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
>
> VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
>
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
>
>
>
> Details: 00:00:00.759580 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
>
>
>
>   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
>
>   https://github.com/kubernetes/minikube/issues/new
>
> Do you know what is this about? I'm trying to run kubernetes in VPS.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by rakeshnambiar** [comment]
I am facing the same issue on AWS Ubuntu 18. 

```
ubuntu@ip-172-31-12-250:~$ lscpu | grep Virtualization
Virtualization type: full
Please check your BIOS, and ensure that you are running without HyperV or other nested virtualization that may interfere
```

So should I choose the EC2 instance which supports this?

**Comment by ankushgarg28794** [comment]
Hi Team,

I am getting the below error while running the below mentioned command. I am running this command on centos 7 and bios settings is also enabled . Please help and provide the resolution.

[root@localhost kubernates]# minikube start --no-vtx-check
* minikube v1.2.0 on linux (amd64)
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary.
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0703 10:46:25.289226    6346 start.go:559] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.707013 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

X Unable to start VM
* Error:         [VBOX_VERR_VMX_NO_VMX] create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.707013 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
* Advice:        Please check your BIOS, and ensure that you are running without HyperV or other nested virtualization that may interfere
* Related issues:
  - https://github.com/kubernetes/minikube/issues/1994

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new
[root@localhost kubernates]# lscpu | grep Virtualization
Virtualization type:   full

**Comment by WesleyCharlesBlake** [comment]
also getting the same issues:

```
$ minikube start
😄  minikube v1.2.0 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0723 13:38:57.444511    3837 start.go:559] StartHost: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

💣  Unable to start VM
❌  Error:         [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
💡  Advice:        In some environments, this message is incorrect. Try 'minikube start --no-vtx-check'
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3900

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new
```

Check virtualisation :
```
$ lscpu | grep -i virt
Virtualisation:      AMD-V
```

BIOS has virtualisation enabled

running with `--no-vtx-check` flag works:
```
$ minikube start --no-vtx-check
😄  minikube v1.2.0 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
```
For more context, just trying to run minikube on my local machine.

This issue only crept up for me on minikube `v1.2.0`

**Comment by breezyraj** [comment]
Hi,

I am also facing the same error, below are the configuration
**OS** -               ubuntu(Running  as guest in Windows machine)
**VMX enabled**:  lscpu | grep -i virt
                            Virtualization type: full
**minikube version**: v1.3.0

I tried below options but no luck
**sudo minikube start --vm-driver=none
sudo minikube start --no-vtx-check**

**LOG:**
sudo minikube start --no-vtx-check
😄  minikube v1.3.0 on Ubuntu 18.04
⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0818 13:17:11.848294   19057 start.go:723] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.285078 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

💣  Unable to start VM
❌  Error: [VBOX_VERR_VMX_NO_VMX] create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Kinldy help me if any configuartion

**Comment by aamir200** [comment]
I am facing same issue

**Comment by kefimo** [comment]
I am facing same issue: 
Configuration:
VPS :
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
...
Hypervisor vendor:   KVM
Virtualization type: full
...

> minikube start --no-vtx-check
😄  minikube v1.3.1 on Ubuntu 18.04
⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
E0914 15:09:08.092043   22698 start.go:723] StartHost: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.374049 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

💣  Unable to start VM
❌  Error: [VBOX_VERR_VMX_NO_VMX] start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.374049 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
💡  Suggestion: Please check your BIOS, and ensure that you are running without HyperV or other nested virtualization that may interfere
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/1994

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

>

**Comment by rikirenz** [comment]
Hey Guys I am facing the same issue:

```
► minikube start            
😄  minikube v0.34.1 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.234112 Power up failed (vrc=VERR_VMX_MSR_ALL_VMX_DISABLED, rc=NS_ERROR_FAILURE (0X80004005))

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

**Comment by nsit-karan** [comment]
Facing same issue and none of the workarounds suggested seem to work.

**Comment by afbjorklund** [comment]
@nsit-karan : please open a new issue, about your nested vmware problem

**Comment by gillespiejim78** [comment]
I am having the same issue on a Windows 10 Home machine. Virtualization is enabled, and I am able to run other VMs using VirtualBox.

> C:\Users\gille>minikube start
> * minikube v1.8.1 on Microsoft Windows 10 Home 10.0.19577 Build 19577
> * Using the virtualbox driver based on existing profile
> * Downloading VM boot image ...
> * Creating virtualbox VM (CPUs=2, Memory=4057MB, Disk=20000MB) ...
> *
> X Unable to start VM. Please investigate and run 'minikube delete' if possible
> * Error: [VBOX_VTX_DISABLED] creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
> * Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=none'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
> * Related issues:
>   - https://github.com/kubernetes/minikube/issues/3900
>   - https://github.com/kubernetes/minikube/issues/4730


I have tried using the --no-vtx-check, and I end up getting a timeout. Looking at the VM in VirtualBox, it appears to be stuck at "Booting the kernel."


> C:\Users\gille>minikube start --no-vtx-check
> * minikube v1.8.1 on Microsoft Windows 10 Home 10.0.19577 Build 19577
> * Using the virtualbox driver based on existing profile
> * Downloading VM boot image ...
> * Creating virtualbox VM (CPUs=2, Memory=4057MB, Disk=20000MB) ...
> *
> X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create > host timed out in 120.000000 seconds
> *
> * minikube is exiting due to an error. If the above message is not useful, open an issue:
>   - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by amitranjan02051988** [comment]
Is this issue reolved ? I am getting the same error

**Comment by afbjorklund** [comment]
@amitranjan02051988 : please open a new issue

**Comment by gillespiejim78** [comment]
@amitranjan02051988 are you using Windows 10 Home? If so, feel free to add on to #6952

**Comment by calmaa1** [comment]
Got the same error after updating my windows to enable WSL 2. 

Turned out Hyper-V feature has been turned ON and is now conflicting with virtualbox.

reference: https://support.microsoft.com/en-us/help/3204980/virtualization-applications-do-not-work-together-with-hyper-v-device-g

**Comment by onichandame** [comment]
still seeing this issue on Windows 10 Pro ver.2004. `--no-vtx-check` did the trick. Maybe [this issue](https://github.com/docker/machine/issues/4709) is relevant?

**Comment by ParagNetApp** [comment]
Despite of enabling VT-D in the bios I get the message VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)

c:\work>minikube start --driver=virtualbox  --disk-size=40000mb --no-vtx-check
* minikube v1.12.2 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the virtualbox driver based on user configuration
* minikube 1.14.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.14.0
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

* Downloading VM boot image ...
    > minikube-v1.12.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.12.2.iso: 173.73 MiB / 173.73 MiB [] 100.00% 3.44 MiB p/s 51s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v5-v1.18.3-docker-overlay2-amd64.tar.lz4: 510.91 MiB
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=40000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: VMMR0_DO_NEM_INIT_VM failed: VERR_NEM_MISSING_KERNEL_API_2 (VERR_NEM_MISSING_KERNEL_API_2).
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.877441 Power up failed (vrc=VERR_VMX_NO_VMX, rc=E_FAIL (0X80004005))
* Failed to start virtualbox VM. "minikube start" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\paragp\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\paragp\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by dharlequin** [comment]
My minikube has been existing fine in VirtualBox on Windows 10 probably for a week.

Then right while I was working with minikub and kubectl, it just stopped responding, I was getting timeouts. And it could not properly start or stop. I tried deleting it, and now I can't start it back on VirtualBox. I get the same error as people here, that I have to enable virtialization:

`minikube start --vm-driver=virtualbox
😄  minikube v1.17.0 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🤦  StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

❌  Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
💡  Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3900
    ▪ https://github.com/kubernetes/minikube/issues/4730`

Tried rebooting and upgrading VirtualBox. Does not help.

**Comment by YonathanGuez** [comment]
> I am having the same issue on a Windows 10 Home machine. Virtualization is enabled, and I am able to run other VMs using VirtualBox.
> 
> > C:\Users\gille>minikube start
> > 
> > * minikube v1.8.1 on Microsoft Windows 10 Home 10.0.19577 Build 19577
> > * Using the virtualbox driver based on existing profile
> > * Downloading VM boot image ...
> > * Creating virtualbox VM (CPUs=2, Memory=4057MB, Disk=20000MB) ...
> > 
> > 
> > X Unable to start VM. Please investigate and run 'minikube delete' if possible
> > 
> > * Error: [VBOX_VTX_DISABLED] creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
> > * Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=none'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
> > * Related issues:
> >   
> >   * #3900
> >   * #4730
> 
> I have tried using the --no-vtx-check, and I end up getting a timeout. Looking at the VM in VirtualBox, it appears to be stuck at "Booting the kernel."
> 
> > C:\Users\gille>minikube start --no-vtx-check
> > 
> > * minikube v1.8.1 on Microsoft Windows 10 Home 10.0.19577 Build 19577
> > * Using the virtualbox driver based on existing profile
> > * Downloading VM boot image ...
> > * Creating virtualbox VM (CPUs=2, Memory=4057MB, Disk=20000MB) ...
> > 
> > 
> > X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create > host timed out in 120.000000 seconds
> > *
> > 
> > * minikube is exiting due to an error. If the above message is not useful, open an issue:
> >   
> >   * https://github.com/kubernetes/minikube/issues/new/choose

Hey , I had a same issue , i try something it s work for me :
i specified where i need to install minikube on windows 10 (in my virtualbox)
1) First i did the purge of old version of minikube :
 minikube delete --all --purge
2) i installed minikube without vtx : 
minikube start --driver=virtualbox --no-vtx-check
3) i checked my status: 
minikube status
------------------
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
timeToStop: Nonexistent

**Comment by DrazicTW** [comment]
I am using minikube on a newly launched EC2 - Ubuntu 18.04, I met the same errors, here's what I did to fix:

0. `sudo minikube start --no-vtx-check` and got original errors.

1. `sudo minikube start --vm-driver=none` and got new errors:

    😄  minikube v1.20.0 on Ubuntu 18.04
    ✨  Using the none driver based on user configuration

    ❌  Exiting due to GUEST_MISSING_CONNTRACK: Sorry, Kubernetes 1.20.2 requires conntrack to be installed in root's path
    
2. Then I type `sudo apt-get install -y conntrack`

3. Try again `sudo minikube start --vm-driver=none` and got succeed messages.

**Comment by jandalpetr** [comment]
Hi, @tstromberg, thanks
`minikube start --no-vtx-check`
This works to me on localy on Windows 10 Pro

λ  minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

**Comment by IT-sukesh** [comment]
! StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

X Exiting due to HOST_VIRT_UNAVAILABLE: Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.

**Comment by SAND171** [comment]
> Do you mind trying this:
> 
> `minikube start --no-vtx-check`
> 
> It's hard to check from here if it's due to the new upstream checks in place, or if things might actually work. Also, I suspect that passing in that small amount of memory might yield further issues down the line.

thanks............worked for me

**Comment by Cheroo35** [comment]
minikube start --no-vtx-check

this command worked for me

**Comment by Lanata07** [comment]
> Do you mind trying this:
> 
> `minikube start --no-vtx-check`
> 
> It's hard to check from here if it's due to the new upstream checks in place, or if things might actually work. Also, I suspect that passing in that small amount of memory might yield further issues down the line.

It works for me :)

**Comment by Noorjahan153** [comment]
It's works for me .Thank you

**Comment by cmhanmandlu** [comment]
> Do you mind trying this:
> 
> `minikube start --no-vtx-check`
> 
> It's hard to check from here if it's due to the new upstream checks in place, or if things might actually work. Also, I suspect that passing in that small amount of memory might yield further issues down the line.

it works for me, thanks

**Comment by anye-web** [comment]
> Do you mind trying this:
> 
> `minikube start --no-vtx-check`
> 
> It's hard to check from here if it's due to the new upstream checks in place, or if things might actually work. Also, I suspect that passing in that small amount of memory might yield further issues down the line.

**Comment by NithyaNallasamy** [comment]
this command worked for me as well...thanks 

minikube start --no-vtx-check

**Comment by MalleshgopiS** [comment]
> this command worked for me as well...thanks
> 
> minikube start --no-vtx-check

Thanks its working
