### ISSUE TITLE
Proposal: use etcdadm for etcd v3.

### ISSUE THREAD

**Issue by jayunit100** [kubernetes/minikube#3904]
This is just a proposal :) , open to ideas pro/con.   I think we may be able to help with this, or implement it entirely,  if this is approved in general by interested parties in the minikube world.

Etcdadm is now a part of the CNCF https://github.com/kubernetes-sigs/etcdadm, and provides a declarative way to run operations like `create cluster` and so on.  It might be a good way to decouple minikube from etcd deployment, and also a good way to plumb options  for changing the way etcd is installed via minikube over time.

cc @dlipovetsky

**Comment by afbjorklund** [comment]
What would it be used for ? To replace the current kubeadm installation (the 220M image) of etcd ?
> The goal of etcdadm is to make it easy to operate an etcd cluster. It downloads a specific etcd release, installs the binary, configures a systemd service, generates certificates, calls the etcd API to add (or remove) a member, and verifies that the new member is healthy.

**Comment by afbjorklund** [comment]
I'm not sure minikube is about "cluster". We should at least make sure to have node clusters, before that.

**Comment by jayunit100** [comment]
Agree, the `create cluster` part isn't valuable to minikube per se, but the fact that it installs etcd in a way that is more useful from a pedagogical perspective might be valueable.

**Comment by tstromberg** [comment]
I'm still not understanding the benefit for minikube here, as well as your motivation for asking. Do you mind clarifying how this helps both projects?

**Comment by tstromberg** [comment]
After discussing with the other maintainers, we will continue to call kubeadm to initialize and modify the  Kubernetes environment. At the moment, there doesn't appear to be much benefit to minikube calling etcdadm directly - at least not enough to warrant the additional support complexity required. This may change when we begin supporting multi-node clusters.

Thanks for opening this issue, as it allowed me to learn more about etcdadm.
