### ISSUE TITLE
Error downloading kubelet v1.13.4: read: connection reset by peer

### ISSUE THREAD

**Issue by ldpereira-123** [kubernetes/minikube#3909]
Facing error while starting minikube

OS: Xubuntu
Tool used: Linux
Minikube version: v0.35.0
kubectl verison: v1.13.4

Command Used: minikube start

Output of command:
minikube start
o   minikube v0.35.0 on linux (amd64)
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running virtualbox VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.99.100
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
@   Downloading kubelet v1.13.4

!   Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.13.4: failed to download: failed to download to temp file: failed to copy contents: read tcp 192.168.211.148:38460->172.217.29.240:443: read: connection reset by peer

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
This means that a firewall is blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.

See: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

**Comment by tstromberg** [comment]
minikube v1.0 now says:

"A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy."

And points the user to: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md
