### ISSUE TITLE
Add an option to disable downloading binaries

### ISSUE THREAD

**Issue by chrismgray** [kubernetes/minikube#3923]
Command line (not run as root):

`minikube --vm-driver=none start --kubernetes-version v1.13.4`

Output:

```
kubernetes-version v1.13.4 
😄  minikube v0.35.0 on linux (amd64)
🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing none VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.1.144
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💣  Failed to update cluster: downloading binaries: copy: error removing file /usr/bin/kubeadm: remove /usr/bin/kubeadm: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

Feature request: add a flag (e.g. `no-download-binaries`) to disable downloading the binaries.

**Comment by tstromberg** [comment]
For what it's worth, this would fail a little bit later, as the none driver requires root access to function.

**Comment by chrismgray** [comment]
Yeah, that's becoming clear.  I think this tool might not really fit in with my environment.  I am trying to run it with the none driver to avoid setting up a VM, but the assumption seems to be that you are using a VM (at least according to the comments on #3718).

**Comment by afbjorklund** [comment]
That is currrently the case, but there are other projects (like [kind](https://github.com/kubernetes-sigs/kind)) that run kubernetes without virtual machines (or external hosts). The `none` driver isn't really good at that, at least not currently...
https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md
