### ISSUE TITLE
Move hyperkit driver upstream

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3939]
There are currently 3 different versions of the hyperkit driver a user may have:

- Docker for Mac
- machine-drivers, when installed by brew
- minikube, when installed by curl

Let's reduce the count by 1 by upstreaming our changes. This does not mean that we should not be attempting to manage a hyperkit binary, as it's difficult to tell which one we're getting. Ours of course, is the best *wink*.

**Comment by afbjorklund** [comment]
https://github.com/moby/hyperkit

https://github.com/machine-drivers/docker-machine-driver-hyperkit/tree/master/pkg/hyperkit

https://github.com/kubernetes/minikube/tree/master/pkg/drivers/hyperkit

**Comment by tstromberg** [comment]
Will this land in time for the v1.4.0 release on Sep 16th?

**Comment by sharifelgamal** [comment]
https://github.com/machine-drivers/docker-machine-driver-hyperkit/pull/13

**Comment by priyawadhwa** [comment]
Closing this as I don't think we are doing this anymore.
