### ISSUE TITLE
Docs for Minikube DNS integration on MacOS

### ISSUE THREAD

**Issue by paultiplady** [kubernetes/minikube#3941]
Apologies if I'm missing a link somewhere. Are there docs around how to set up DNS on MacOS to use the cluster's coredns?

I've found https://stevesloka.com/access-minikube-services-from-host/ which seems to be the right approach, though it's mostly covering stuff that is superseded by `minikube tunnel`. 

https://github.com/kubernetes/minikube/blob/master/docs/tunnel.md gives a lot of detail on `minikube tunnel`, but doesn't mention DNS.

**Comment by tstromberg** [comment]
The good news is that minikube v1.1 now includes this feature. The bad news is that it isn't documented yet. =)
