### ISSUE TITLE
Unable to apply storage-provisioner.yaml due to yaml to JSON conversion error.

### ISSUE THREAD

**Issue by Raajev** [kubernetes/minikube#3956]
I tried to apply the storage-provisioner.yaml file but there is error related to YAML to JSON Conversion.

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/minikube/master/deploy/addons/storage-provisioner/storage-provisioner.yaml
serviceaccount/storage-provisioner unchanged
clusterrolebinding.rbac.authorization.k8s.io/storage-provisioner unchanged
error: error parsing https://raw.githubusercontent.com/kubernetes/minikube/master/deploy/addons/storage-provisioner/storage-provisioner.yaml: error converting YAML to JSON: yaml: line 13: did not find expected key`
 
It seems issue is with the "Image" key:
` image: {{default "gcr.io/k8s-minikube" .ImageRepository}}/storage-provisioner:v1.8.1`

I was able to apply after changing the double quotes as below.
`image: "{{default gcr.io/k8s-minikube .ImageRepository}}/storage-provisioner:v1.8.1"`

But i am not sure if it will produce the same result. I am new to this so any help will be appreciated.
OS: Ubuntu 18.04.1

I was able apply by changing the image key as
`image: "gcr.io/k8s-minikube/storage-provisioner:v1.8.1"`

**Comment by tstromberg** [comment]
Was this using the v0.35 release of minikube?

I suspect this may be related to #3714 - where we recently added templating for the ImageRepository change.

**Comment by afbjorklund** [comment]
Maybe we should change the name of the files, to something like ".yaml.in" ?

https://github.com/kubernetes/minikube/pull/3714/files#diff-3f76927d4f10cf3ea76430a71c27d122

To show that it is not a YAML file anymore, but instead a template file for Go.

**Comment by tstromberg** [comment]
@afbjorklund - I'm not picky on the actual filename, but agree that it should no longer be .yaml since it requires template processing.

@laozc - any thoughts?

**Comment by Raajev** [comment]
> 
> 
> Maybe we should change the name of the files, to something like ".yaml.in" ?
> 
> https://github.com/kubernetes/minikube/pull/3714/files#diff-3f76927d4f10cf3ea76430a71c27d122
> 
> To show that it is not a YAML file anymore, but instead a template file for Go.
> 
> For most users, it should read: `image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1`

It worked for me. Thanks !

**Comment by tstromberg** [comment]
In minikube v1.1, the files were renamed to .yaml.tmpl to avoid this confusion. Thanks for opening this bug report!
