### ISSUE TITLE
  Error getting config: open ~/.minikube/profiles/minikube/config.json: permission denied

### ISSUE THREAD

**Issue by sneekavelli** [kubernetes/minikube#3964]

**Comment by balopat** [comment]
Thank you for opening this issue @sneekavelli - can you provide more information - did this error message prevent minikube from starting?

**Comment by sneekavelli** [comment]
Yes on my mac os version el capitan

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by tstromberg** [comment]
It sounds like some files in ~/.minikube may have the wrong permissions. Can you share the output of:

 `ls -la ~/.minikube/profiles/minikube/config.json`

Thanks!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by alikemalagirman** [comment]
Hi, I also face the same problem in my minikube installation on Ubuntu 19.04 disco.

(ls -la ~/.minikube/profiles/minikube/config.json) command returns the output:
-rw
