### ISSUE TITLE
Validate presence of kubectl

### ISSUE THREAD

**Issue by ramitsurana** [kubernetes/minikube#397]
Hi,
I just installed the minikube and got this error while running the kubectl not found even though it says kubectl is configured to use with the cluster.My machine configuration:
- Ubuntu Linux 16.04
- Virtual Box

![kubectl](https://cloud.githubusercontent.com/assets/8342133/17127706/40359d1e-5325-11e6-8ae0-c4c5af7dd801.png)

**Comment by jimmidyson** [comment]
I've reopened because I think minikube should check if kubectl is on the path, & either offer to download or display link to download location.

**Comment by ramitsurana** [comment]
@jimmidyson Nice.I have a created a PR for the same at https://github.com/kubernetes/minikube/pull/398
But might needs some refactoring before merging

**Comment by jberkus** [comment]
I would argue that it should just install kubectl.  Providing users with a URL, which then requires them to look up their platform, and curl another URL, in order  to install a binary isn't user-friendly.

**Comment by ramitsurana** [comment]
@jberkus That's a nice idea.Maybe we can create a separate file in golang so that we can use it while installing kubectl for different operating systems.

**Comment by aaron-prindle** [comment]
Ref: #783

**Comment by aaron-prindle** [comment]
Closing, minikube now validates the presence of kubectl with #783
