### ISSUE TITLE
Unable to enable dashboard: dial tcp 127.0.0.1:22: connect: connection refused

### ISSUE THREAD

**Issue by GiovanniColonni** [kubernetes/minikube#3971]
i use : minikube dashboard (with root permission)

the output of command : 
 Unable to enable dashboard: [command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused]

 SO= ubuntu 18.04 
i don't know how to solve it, thanks

**Comment by balopat** [comment]
can you please confirm what driver are you using? Is it `--vm-driver=none`?

**Comment by tstromberg** [comment]
I suspect you are right about the none driver: The dashboard command is not available with the none driver. That said, this error message is terrible and needs fixing.

**Comment by tstromberg** [comment]
Closing, as this behavior shouldn't exist in v1.4.
