### ISSUE TITLE
Host folder sharing on kvm2

### ISSUE THREAD

**Issue by dvejmz** [kubernetes/minikube#3973]
Hi, first off here are my minikube details to give you some context.

**OS**: `Linux dev.localdomain 4.20.16-200.fc29.x86_64 #1 SMP Thu Mar 14 15:10:22 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
**minikube version**: `minikube version: v0.35.0`
**minikube Kubernetes version**
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:37:52Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

Since host folder sharing [is not properly implemented on the kvm2 driver at the moment](https://kubernetes.io/docs/setup/minikube/#mounted-host-folders), filesystem access operations 1 or 2 orders of magnitude slower than in the host. This is due to the set of mount options used

```
192.168.39.1 on /mounted/dir type 9p (rw,relatime,sync,dirsync,dfltuid=1001,dfltgid=1001,access=any,msize=65536,trans=tcp,noextend,port=40263)
```

Block allocation in an unmounted dir
```
dd if=/dev/zero of=test count=100000 bs=65536
100000+0 records in
100000+0 records out
6553600000 bytes (6.6 GB, 6.1 GiB) copied, 2.61516 s, 2.5 GB/s
```
Block allocation in a mounted dir
```
dd if=/dev/zero of=test count=100000 bs=65536
100000+0 records in
100000+0 records out
6553600000 bytes (6.6 GB, 6.1 GiB) copied, 49.7161 s, 132 MB/s
```

Even though `minikube mount` takes a couple of parameters (such as `msize` or `9p-version`), passing them through does not alter the actual mount entry that gets created at all.

Since I couldn't see any open issues discussing this or anything on your roadmap, I'd just like to ask what are your plans towards implementing host file sharing on kvm2? Is this something you'd be looking to do short-term, mid-term...? And if not, anything you recommend to mitigate the slowness problem? Some way to override these options?

Thanks

**Comment by afbjorklund** [comment]
There's some other issues with 9p (in general, and the Go implementation in particular).
But there is no other readily available solution, seems like virtio-vsock  is not yet here yet

The workaround that was added after discussing the matter (in https://github.com/dhiltgen/docker-machine-kvm/issues/2)
was to use `sshfs` and just leave the files on the VM. It doesn't work for all use cases, but...


Maybe we should look at adding NFS ? Probably going to need that for multi-node anyway.

Also, I'm still not fully convinced that exporting the home folder _by default_ is a good idea ?

**Comment by dvejmz** [comment]
Thanks for your reply @afbjorklund . Even the latest release of minikube (1.0), which allegedly supports passing in arbitrary mount commands, seems to ignore everything, which is probably due to the issues you pointed out with the underlying Go implementation of the mount type.

I think I'll drop host folder sharing on kvm for the time being and use [Skaffold](https://skaffold.dev), which does support hot reloading via real-time filesystem syncing.

Thanks for your advice. This issue can be closed now.
