### ISSUE TITLE
Unable to start VM: create: precreate: The character device /dev/vboxdrv does not exist

### ISSUE THREAD

**Issue by yrmmout** [kubernetes/minikube#3974]
minikube v0.35.0 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💣  Unable to start VM: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-generic.\n\n\t You will not be able to start VMs until this problem is fixed.\n5.2.18_Ubuntur123745". Please upgrade at https://www.virtualbox.org

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

Think you

**Comment by tstromberg** [comment]
It sounds like VirtualBox is not completely installed.  Could you try uninstalling it and installing it again?

You may also want to take the time to upgrade VirtualBox to 6.0: https://www.virtualbox.org/wiki/Downloads

**Comment by balopat** [comment]
friendly ping @yrmmout - does reinstalling VirtualBox help?

**Comment by akanurlan0** [comment]
> friendly ping @yrmmout - does reinstalling VirtualBox help?
Faced the same issue, reinstallation didn't help. I am running ubuntu 18.04, tried virtualbox 6.0 and 5.2 both. 

``
Unable to start VM: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The vboxdrv kernel module is not loaded. Either there is no module\n         available for the current kernel (4.15.0-46-generic) or it failed to\n         load. Please recompile the kernel module and install it by\n\n           sudo /sbin/vboxconfig\n\n         You will not be able to start VMs until this problem is fixed.\n6.0.4r128413". Please upgrade at https://www.virtualbox.org
``

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by ajit555db** [comment]
I disabled the "secured boot" option on my host machine.

https://askubuntu.com/questions/900118/vboxdrv-sh-failed-modprobe-vboxdrv-failed-please-use-dmesg-to-find-out-why

**Comment by SohailKhanPAK** [comment]
Just about half an hour ago i faced same problem but i followed that 2 lines and i got the solution 
try it !!  

sudo apt-get update
sudo apt-get upgrade

**Comment by yrmmout** [comment]
Thank you  (merci)

Le mar. 6 août 2019 à 19:43, Sohail Khan <notifications@github.com> a
écrit :

**Comment by John-Dormevil** [comment]
Try to:
- Deactivate Secure Boot from your bios system;
- Then run `sudo /sbin/vboxconfig` in case you install and use virtualbox 6+
- Then `minikube start`

**Comment by skemuel007** [comment]
The code below is added to your /etc/apt/sources.list
`echo "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian $(lsb_release -sc) contrib" | sudo tee /etc/apt/sources.list`

Add these keys with 
`wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | sudo apt-key add -`
`wget -q https://www.virtualbox.org/download/oracle_vbox.asc -O- | sudo apt-key add -`

To install VirtualBox, do
`sudo apt-get update`
`sudo apt-get install virtualbox-6.1`

For more details visit https://www.virtualbox.org/wiki/Linux_Downloads

**Comment by ecourtial** [comment]
To solve the issue I had to mix the solutions presenteed above:
- Install VB6.1
- Disable SecureBoot.

**Comment by kullwindergit** [comment]
Facing same issue even after disabling 'secure boot' on below environment
Ubuntu 18.04.5 (as windows subsystem for linux)
minikube version: 1.16.0
virtualbox 5.2.42

**Comment by kullwindergit** [comment]
followed: https://tecadmin.net/install-virtualbox-on-ubuntu-18-04/ to attempt installation of virtualbox 6.1 but at the end of install process throws error:

This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.

There were problems setting up VirtualBox.  To re-start the set-up process, run
  /sbin/vboxconfig
as root.  If your system is using EFI Secure Boot you may need to sign the
kernel modules (vboxdrv, vboxnetflt, vboxnetadp, vboxpci) before you can load
them. Please see your Linux system's documentation for more information.

This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.

There were problems setting up VirtualBox.  To re-start the set-up process, run
  /sbin/vboxconfig
as root.  If your system is using EFI Secure Boot you may need to sign the
kernel modules (vboxdrv, vboxnetflt, vboxnetadp, vboxpci) before you can load
them. Please see your Linux system's documentation for more information.

This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.
This system is currently not set up to build kernel modules.
Please install the Linux kernel "header" files matching the current kernel
for adding new hardware support to the system.

There were problems setting up VirtualBox.  To re-start the set-up process, run

$ /sbin/vboxconfig
as root.  If your system is using EFI Secure Boot you may need to sign the
kernel modules (vboxdrv, vboxnetflt, vboxnetadp, vboxpci) before you can load
them. Please see your Linux system's documentation for more information.
