### ISSUE TITLE
Download our own hyperkit driver if the installed one is missing or incompatible

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3975]
There are 3 implementations of docker-machine-driver-hyperkit, that all install to the same path:

- The version that ships with Docker for Desktop
- The machine-drivers fork (last updated in March 2018, which brew installs)
- The minikube fork (last updated 19 days ago)

Any 3 of these versions may be an ancient and/or incompatible release with breaking bugs. Most hyperkit bugs are due to users not using the minikube fork. My rough idea is:

- Upstream our hyperkit driver
- Add versioning to the driver (binary --version)
- If version is compatible, use it!
- If the version is incompatible, fetch a new version into ~/.minikube and ask for sudo access to chmod it, and use it instead.

**Comment by tstromberg** [comment]
Related: #3939

**Comment by tstromberg** [comment]
Related - but not a blocker: #5180

**Comment by tstromberg** [comment]
Will this land in time for the v1.4.0 release on Sep 16th?

**Comment by josedonizetti** [comment]
@tstromberg Yes, I'm returning to Brazil this weekend. Will have my OSX to work on this.
