### ISSUE TITLE
docker-env="http_proxy=http://127.0.0.1:3128": connect: connection refused

### ISSUE THREAD

**Issue by onderson** [kubernetes/minikube#3977]
**I am running;**

minikube start --vm-driver="kvm" --docker-env="http_proxy=http://127.0.0.1:3128" --docker-env="https_proxy=http://127.0.0.1:3128" start

**The output:**
😄  minikube v0.35.0 on linux (amd64)
⚠️  The kvm driver is deprecated and support for it will be removed in a future release.
				Please consider switching to the kvm2 driver, which is intended to replace the kvm driver.
				See https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver for more information.
				To disable this message, run [minikube config set WantShowDriverDeprecationNotification false]
🔥  Creating kvm VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s

📶  "minikube" IP address is 192.168.42.254
🌐  Found network options:
    ▪ HTTP_PROXY=http://127.0.0.1:3128
    ▪ HTTPS_PROXY=http://127.0.0.1:3128
    ▪ NO_PROXY=localhost,127.0.0.1,192.168.42.174
🐳  Configuring Docker as the container runtime ...
    ▪ env http_proxy=http://127.0.0.1:3128
    ▪ env https_proxy=http://127.0.0.1:3128
✨  Preparing Kubernetes environment ...
💾  Downloading kubelet v1.13.4
💾  Downloading kubeadm v1.13.4
🚜  Pulling images required by Kubernetes v1.13.4 ...
❌  Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout: 
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.13.4": output: Error response from daemon: Get https://k8s.gcr.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
, error: exit status 1
: Process exited with status 1
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
💣  Error starting cluster: kubeadm init: 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI 

[init] Using Kubernetes version: v1.13.4
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING Swap]: running with swap on is not supported. Please disable swap
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.13.4: output: Error response from daemon: Get https://k8s.gcr.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.13.4: output: Error response from daemon: Get https://k8s.gcr.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.13.4: output: Error response from daemon: Get https://k8s.gcr.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.13.4: output: Error response from daemon: Get https://k8s.gcr.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.2.24: output: Error response from daemon: Get https://k8s.gcr.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.2.6: output: Error response from daemon: Get https://k8s.gcr.io/v2/: proxyconnect tcp: dial tcp 127.0.0.1:3128: connect: connection refused
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Minikube logs:**

==> kubelet <==
-- Logs begin at Tue 2019-03-26 13:19:37 UTC, end at Tue 2019-03-26 14:13:58 UTC. --
Mar 26 14:13:28 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 276.
Mar 26 14:13:28 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Mar 26 14:13:28 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Mar 26 14:13:28 minikube kubelet[5991]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:28 minikube kubelet[5991]: Flag --allow-privileged has been deprecated, will be removed in a future version
Mar 26 14:13:28 minikube kubelet[5991]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:28 minikube kubelet[5991]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:28 minikube kubelet[5991]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:28 minikube kubelet[5991]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:28 minikube kubelet[5991]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:28 minikube kubelet[5991]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:28 minikube kubelet[5991]: I0326 14:13:28.674037    5991 server.go:407] Version: v1.13.4
Mar 26 14:13:28 minikube kubelet[5991]: I0326 14:13:28.674543    5991 plugins.go:103] No cloud provider specified.
Mar 26 14:13:28 minikube kubelet[5991]: F0326 14:13:28.674661    5991 server.go:261] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Mar 26 14:13:28 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Mar 26 14:13:28 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Mar 26 14:13:38 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Mar 26 14:13:38 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 277.
Mar 26 14:13:38 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Mar 26 14:13:38 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Mar 26 14:13:38 minikube kubelet[6004]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:38 minikube kubelet[6004]: Flag --allow-privileged has been deprecated, will be removed in a future version
Mar 26 14:13:38 minikube kubelet[6004]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:38 minikube kubelet[6004]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:38 minikube kubelet[6004]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:38 minikube kubelet[6004]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:38 minikube kubelet[6004]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:38 minikube kubelet[6004]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:38 minikube kubelet[6004]: I0326 14:13:38.944454    6004 server.go:407] Version: v1.13.4
Mar 26 14:13:38 minikube kubelet[6004]: I0326 14:13:38.944746    6004 plugins.go:103] No cloud provider specified.
Mar 26 14:13:38 minikube kubelet[6004]: F0326 14:13:38.944864    6004 server.go:261] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Mar 26 14:13:38 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Mar 26 14:13:38 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Mar 26 14:13:49 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Mar 26 14:13:49 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 278.
Mar 26 14:13:49 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Mar 26 14:13:49 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Mar 26 14:13:49 minikube kubelet[6017]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:49 minikube kubelet[6017]: Flag --allow-privileged has been deprecated, will be removed in a future version
Mar 26 14:13:49 minikube kubelet[6017]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:49 minikube kubelet[6017]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:49 minikube kubelet[6017]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:49 minikube kubelet[6017]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:49 minikube kubelet[6017]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:49 minikube kubelet[6017]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Mar 26 14:13:49 minikube kubelet[6017]: I0326 14:13:49.183647    6017 server.go:407] Version: v1.13.4
Mar 26 14:13:49 minikube kubelet[6017]: I0326 14:13:49.183889    6017 plugins.go:103] No cloud provider specified.
Mar 26 14:13:49 minikube kubelet[6017]: F0326 14:13:49.184001    6017 server.go:261] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Mar 26 14:13:49 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Mar 26 14:13:49 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Platform:**
Ubuntu 18.04 on VMWare

Afterwards, i tried to access https://k8s.gcr.io/v2/ on mozilla and i got;

> errors	
> 0	
> code	"UNAUTHORIZED"
> message	"Unauthorized access."

Is this a misconfiguration or a small bug?

**Comment by onderson** [comment]
I have to mention that i am behind corporate proxy.

**Comment by tstromberg** [comment]
You'll need to adjust this line with a non-localhost IP:

` --docker-env="https_proxy=http://127.0.0.1:3128"`

Docker is running inside the VM, so this IP won't work, as it points to squid running inside the VM rather than on your host. You could try using the IP of your workstation instead, or an alternative host that is accessible from inside the VM.

**Comment by onderson** [comment]
That makes sense. I should have thought it. Thanks for the suggestion. I will try and update the issue soon.
but i am wondering one point. minishift is also applying something similar (and which is i am not sure how) and it is working with it. @gbraad , what's the difference? could you please share any insight?

Thanks.

**Comment by onderson** [comment]
@tstromberg, it seems when proxy configuration in docker is made with web proxy requiring authecation, somehow it is not working as there are issues in minishift as well, (as it is cross-referenced here in https://github.com/minishift/minishift/issues/2983). CNTLM over web proxy with authentication and sole web proxy with auhtentication seem not working for me. not sure what to do at the moment.

**Comment by onderson** [comment]
This section resolves the problem i have.
https://kubernetes.io/docs/setup/minikube/#starting-a-cluster.
