### ISSUE TITLE
Provide troubleshooting guide

### ISSUE THREAD

**Issue by maklemenz** [kubernetes/minikube#399]

**Comment by jimmidyson** [comment]
Good idea. Fancy making a start on one & sending in a PR?

**Comment by maklemenz** [comment]
I just installed minikube and ran `minikube start --cpus=8 --memory=8192 --vm-driver=kvm`
I used `minikube ssh` to take a look into the VM and `kubectl get svc --all-namespaces` to see the services. After that I tried `minikube ssh` again:

    ssh.go:39] Error attempting to ssh into machine:  dial tcp: missing address

	$ minikube status
	status.go:40] Error getting machine status: dial tcp: missing address

	$ minikube start
	Starting local Kubernetes cluster...
	start.go:74] Error starting host:  Error loading existing host: dial tcp: missing address

	$ minikube stop
	Stopping local Kubernetes cluster...
	Error stopping machine:  dial tcp: missing address

	$ minikube logs
	Error getting machine logs: dial tcp: missing address

	$ minikube dashboard
	dashboard.go:45] Error accessing the kubernetes dashboard (is minikube running?): Error:  dial tcp: missing address

	$ minikube delete
	Deleting local Kubernetes cluster...
	Errors occurred deleting machine:  dial tcp: missing address

Only a reboot helped and the VM was gone - had to create a new one. I don't think I should start a troubleshooting guide with "reboot your laptop and start from the beginning"

Anyway, it looks like you guys created something awesome

**Comment by jimmidyson** [comment]
> I don't think I should start a troubleshooting guide with "reboot your laptop and start from the beginning"

Haha no that would not be a good start.

I'm really not sure what happened with your set up - not experienced that at all. Looks like the VM got deleted somehow.

**Comment by dlorenc** [comment]
We should also include/link to this from a default issue template.

**Comment by dlorenc** [comment]
I think we have this covered.
