### ISSUE TITLE
how can I configure kube-scheduler in minikube?

### ISSUE THREAD

**Issue by 15050050972** [kubernetes/minikube#3993]
I want configure a special kube-scheduler in minikube. 
I'm following this article in minikube (https://github.com/AliyunContainerService/gpushare-scheduler-extender/blob/master/docs/install.md#2-modify-scheduler-configuration)
In step2 modify-scheduler-configuration, I must specify a kube-scheduler with a yaml, how can I do this? 

First, I try to execute the command `kubectl create -f kube-scheduler.yaml`, but the pod startup failure.
Then ,I read the following link
https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/#options,
and this link https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md,

So I try to execute the command `minikube start --extra-config=scheduler.config=kube-scheduler.yaml`,  But the pod/kube-scheduler-minikube status is **CrashLoopBackOff**,

I don't think I used the `--extra-config` command properly, please give me some help. thanks very much

**Comment by balopat** [comment]
Hi - I don't think it is easy to replace in minikube the kube-scheduler definition. 
However for GPU enablement did you check out https://github.com/kubernetes/minikube/blob/master/docs/gpu.md?
