### ISSUE TITLE
disabling heapster after enabling crashes minikube

### ISSUE THREAD

**Issue by eliot1785** [kubernetes/minikube#4001]
Versioning information below. I was just going through the Hello Minikube tutorial so I hadn't done much with it at all. As per the tutorial, I enabled the heapster addon which worked successfully. Then I tried to disable it as per the tutorial and got the following message:

```
C:\Users\Mark>minikube addons disable heapster
!   disable failed: [disabling addon deploy/addons/heapster/influx-grafana-rc.yaml: Process exited with status 1]
```

The other thing that might be notable is that `minikube addons enable heapster` didn't actually create any heapster pods or services for me (the tutorial suggests that those pods would be created, but they weren't available in the output of `kubectl get pod,svc -n kube-system`)

I'm using Minikube 0.35.0 on Windows 10 with VirtualBox. Here are my kubectl and Kubernetes versions:

```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:53:57Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by tstromberg** [comment]
Thanks for the bug report! Do you mind checking if minikube v1.0.0 has the same failure? It includes an update to the heapster addon: https://github.com/kubernetes/minikube/pull/3826

If it continues to fail, can you include the output of:

`minikube addons disable heapster --alsologtostderr -v=8`

That should give us a bit more to go on as to why it failed. The error message we currently give here isn't helpful at all :(

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
