### ISSUE TITLE
Error kubeconfig status: Kubeconfig does not have a record of the machine cluster

### ISSUE THREAD

**Issue by aakarshg** [kubernetes/minikube#4019]
minikube status

```
E0328 20:30:50.419672    4841 status.go:104] Error kubeconfig status: Kubeconfig does not have a record of the machine cluster
host: Running
kubelet: Running
apiserver: Running
kubectl: Misconfigured: pointing to stale minikube-vm.
To fix the kubectl context, run minikube update-context
```

Fedora 29 was used with latest minikube 1.0.0

**Comment by balopat** [comment]
Hi, did you try running `minikube update-context`?

**Comment by tstromberg** [comment]
AFAIK, this state should never happen. I'm really curious what's going on here.

**Comment by jeffvance** [comment]
ditto for me:
```
$ uname -a
Linux localhost.localdomain 4.19.7-300.fc29.x86_64 #1 SMP Wed Dec 5 22:21:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ mk version
minikube version: v1.0.1
$ mk update-context

💣  update config: Kubeconfig does not have a record of the machine cluster
```

**Comment by tstromberg** [comment]
@jeffvance - What happens if you type:

` grep  -- "- name" ~/.kube/config`

I'm reaching here - but was the VM started using another user like via `sudo` by any chance?

**Comment by jeffvance** [comment]
@tstromberg : 
```
$ grep -- "- name" ~/.kube/config
- name: kubernetes-admin
- name: minikube
```

**Comment by harryge00** [comment]
How did you start the minikube?
I have run 
```
sudo minikube start
```

And when I run `minikube status`, it report the same error. 
I have to run `sudo minikube status`

**Comment by tstromberg** [comment]
Closing. The basic issue here is that kubectl and minikube only know about the clusters started by the user: if you use sudo, that's root.

To prevent confusion, minikube v1.4 will exit if you try to use something other than the `none` driver as root.
