### ISSUE TITLE
Minikube Installer For Linux

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#402]
We are attempting to create a local installer for Minikube on all of our supported platforms and would appreciate any feedback on best practices as to how this should be designed.  Right now, we are considering the following approach:
Create a bin directory in ~/.minikube:
~/minikube
  --/bin/kubectl
  --/bin/minikube
  --/bin/drivers

Then link (via symlink, etc.) the above into the path of the user with a method that is OS specific and points to the correct minikube binary (linux os --> minikube-linux-amd64).  We will create a .deb, .rpm, .dmg, and .msi to do the above.

Right now our goal is to put the minikube binary on the path of the user in a way that is extensible to multiple binaries/dependencies (kubectl, etc.), easy to maintain for all OSs, and is as fast/simple as possible.

**Comment by aaron-prindle** [comment]
Building on: #12

**Comment by jimmidyson** [comment]
Distro packages should not be installed into a user's home directory. Packages are installed as root remember. If we're providing installers then we should follow proper file locations, e.g. /use/bin, /etc, etc

**Comment by ramitsurana** [comment]
@aaron-prindle Try using https://github.com/jordansissel/fpm

**Comment by r2d4** [comment]
Looks like someone has already added it to the arch user repository https://aur.archlinux.org/packages/minikube/

**Comment by aaron-prindle** [comment]
Here is a write-up detailing the steps I used to my first concept for how to a create a .deb installer for minikube:
https://gist.github.com/aaron-prindle/cfd23148460b24c5f49e8ceecd8ec4b0
Any suggestions on how to improve this or alternative methods would be appreciated.  

I also attempted to use to use [dh-make-golang](https://github.com/Debian/dh-make-golang) in conjunction with [this guide](https://people.debian.org/~stapelberg/2015/07/27/dh-make-golang.html)

but was not able to properly build the package getting the error:
aprindle@aprindle:~/dh-make-gopath/go/bin/minikube$ gbp buildpackage --git-pbuilder
Base directory /var/cache/pbuilder/base.cow does not exist
gbp:error: Couldn't run 'git-pbuilder': git-pbuilder returned 1

**Comment by dlorenc** [comment]
cc @stephenmw

**Comment by zoidbergwill** [comment]
I think using `fpm` might making supporting more than Debian-based OSes easier?

**Comment by r2d4** [comment]
Closing, we now have a deb and arch linux AUR package
