### ISSUE TITLE
Unable to access NodePort service

### ISSUE THREAD

**Issue by goyalnikhil02** [kubernetes/minikube#4024]

**Comment by goyalnikhil02** [comment]
Intially i was facing the issue while starting the minikube.
**" Sorry that minikube crashed. If this was unexpected, we would love to hear from you:"**
So i follow the solution mention in #3882 says simple .
Solved after doing sudo minikube delete, rm -rf ~/.kube ~/.minikube, then started over.

after that solution new issue is now  coming.

Now it is not accessible from by browser.
minikube ip have also changed ,so i try with new ip but still it is not accessible

**logs:**
rnd-nb-scl1344@RND-NB-SCL1344:~$ kubectl get all
NAME               READY   STATUS    RESTARTS   AGE
pod/queue          1/1     Running   2          11d
pod/webapp-lqkfp   1/1     Running   1          7d13h
pod/webapp-mbkwl   1/1     Running   1          7d13h

NAME                      TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/fleetman-queue    NodePort    10.102.168.18   <none>        8161:30010/TCP   11d
service/fleetman-webapp   NodePort    10.97.159.188   <none>        80:30080/TCP     11d
service/kubernetes        ClusterIP   10.96.0.1       <none>        443/TCP          15d

NAME                     DESIRED   CURRENT   READY   AGE
replicaset.apps/webapp   2         2         2       11d
rnd-nb-scl1344@RND-NB-SCL1344:~$ kubectl get svc --all-namespaces
NAMESPACE     NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
default       fleetman-queue    NodePort    10.102.168.18   <none>        8161:30010/TCP   11d
default       fleetman-webapp   NodePort    10.97.159.188   <none>        80:30080/TCP     11d
default       kubernetes        ClusterIP   10.96.0.1       <none>        443/TCP          15d
kube-system   kube-dns          ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP    15d

**Comment by tstromberg** [comment]
If you run `minikube service fleetman-webapp`, what happens?

**Comment by goyalnikhil02** [comment]
solved .Thanks

**Comment by dhinkris** [comment]
facing the same issue. @goyalnikhil02  how did you solved it

**Comment by iDhruv22** [comment]
me too
