### ISSUE TITLE
stop: VBoxManage.exe: error: Invalid machine state: Stopping

### ISSUE THREAD

**Issue by QasimRRizvi** [kubernetes/minikube#4031]
Command: minikube stop
Error: 
!   Unable to stop VM: Temporary Error: Stop: minikube: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe controlvm minikube acpipowerbutton failed:
VBoxManage.exe: error: Invalid machine state: Stopping
VBoxManage.exe: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component ConsoleWrap, interface IConsole, callee IUnknown
VBoxManage.exe: error: Context: "PowerButton()" at line 631 of file VBoxManageControlVM.cpp

Temporary Error: Stop: minikube: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe controlvm minikube acpipowerbutton failed:
VBoxManage.exe: error: Invalid machine state: Stopping
VBoxManage.exe: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component ConsoleWrap, interface IConsole, callee IUnknown
VBoxManage.exe: error: Context: "PowerButton()" at line 631 of file VBoxManageControlVM.cpp

Temporary Error: Stop: minikube: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe controlvm minikube acpipowerbutton failed:
VBoxManage.exe: error: Invalid machine state: Stopping
VBoxManage.exe: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component ConsoleWrap, interface IConsole, callee IUnknown
VBoxManage.exe: error: Context: "PowerButton()" at line 631 of file VBoxManageControlVM.cpp

Temporary Error: Stop: minikube: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe controlvm minikube acpipowerbutton failed:
VBoxManage.exe: error: Invalid machine state: Stopping
VBoxManage.exe: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component ConsoleWrap, interface IConsole, callee IUnknown
VBoxManage.exe: error: Context: "PowerButton()" at line 631 of file VBoxManageControlVM.cpp

Temporary Error: Stop: minikube: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe controlvm minikube acpipowerbutton failed:
VBoxManage.exe: error: Invalid machine state: Stopping
VBoxManage.exe: error: Details: code VBOX_E_INVALID_VM_STATE (0x80bb0002), component ConsoleWrap, interface IConsole, callee IUnknown
VBoxManage.exe: error: Context: "PowerButton()" at line 631 of file VBoxManageControlVM.cpp

OS: windows 10

**Comment by tstromberg** [comment]
Thanks for the bug report! 

I don't think there is anything we can do to fix this, but do you mind letting us know what version of VirtualBox this was?

**Comment by QasimRRizvi** [comment]
@tstromberg I'm using version 6.0.4 r128413

**Comment by tstromberg** [comment]
Closing, as this issue originates entirely from VirtualBox. I'd upgrade to v6.0.12, run `minikube delete`, and move on.
