### ISSUE TITLE
Hung downloading ISO (network contention with image pull)

### ISSUE THREAD

**Issue by bcbrockway** [kubernetes/minikube#4035]
My minikube hangs when downloading the ISO using Minikube 1.0.0:

```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
chmod +x minikube
sudo mv minikube /usr/local/bin
minikube start                                                        
😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
2019/04/02 11:03:47 No matching credentials were found, falling back on anonymous
💿  Downloading Minikube ISO ...
2019/04/02 11:03:47 No matching credentials were found, falling back on anonymous
2019/04/02 11:03:47 No matching credentials were found, falling back on anonymous
2019/04/02 11:03:47 No matching credentials were found, falling back on anonymous
2019/04/02 11:03:47 No matching credentials were found, falling back on anonymous
2019/04/02 11:03:47 No matching credentials were found, falling back on anonymous
 1.11 MB / 142.88 MB [>------------------------------------------]   0.78% 2m33s
```

* OS: Ubuntu 18.04
* Minikube: 1.0.0

Tried with v0.35.0 and I do not have this issue:

```
sudo cp ~/Downloads/minikube-linux-amd64-0.35.0 /usr/local/bin/minikube
minikube start
😄  minikube v0.35.0 on linux (amd64)
💥  Kubernetes downgrade is not supported, will continue to use v1.14.0
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 26.91 MB / 184.42 MB [======>-----------------------------------]  14.59% 2m21s
```

**Comment by sagarkoshti1991** [comment]
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.35.0/minikube-linux-amd64 && chmod +x minikube && sudo cp minikube /usr/local/bin/ && rm minikube
Worked for me.
Reference: https://github.com/kubernetes/minikube/releases/tag/v0.35.0

**Comment by jonpharry** [comment]
I have the same issue with minikube 1.0.0 running under kvm2 on Centos 7.

I also run without issue using 0.35 (albeit with 0.31 docker-machine-kvm2 to avoid hidden config issue) so this appears to be a 1.0.0 issue.

**Comment by jonpharry** [comment]
I was able to work around by manually downloading `https://storage.googleapis.com/minikube/iso/minikube-v1.0.0.iso` and placing in `~/.minikube/cache/iso`

All of the other downloads required during initial startup worked fine.  It appears issue is limited to the initial download of the minikube ISO.

**Comment by itamarst** [comment]
This is happening to me on Fedora 29.

**Comment by lucasyvas** [comment]
Happening on Ubuntu 18.04 on kvm2. There is no way to get it to work I can find... totally busted.

**Comment by tstromberg** [comment]
Thanks for the bug report! 

I believe that the root cause here is we're trying to download too much (7 Linux images simultaneously!), and some networks don't deal with this well. 

This should eventually unhang.  

You can test my root cause theory by using:

`minikube start --cache-images=false`

This will end up serializing the image downloads.

**Comment by jonpharry** [comment]
I can confirm that on a faster network the hand does eventually clear and minikube starts successfully.

**Comment by tstromberg** [comment]
Here's the plan:

- Complete the ISO download first, before container images are pulled. We need it to start the VM anyways. While the VM is starting, we'll be downloading additional container images.
- Verify that ISO downloads are retryable and resumable

Look for a PR to be sent out in the next day on this.

**Comment by locojuhi** [comment]
I've just installed virtualbox, kubectl and minikube... but when I run minikube start it freeze when is downloading the minikube iso

smile minikube v1.0.0 on linux (amd64)
🤹 Downloading Kubernetes v1.14.0 images in the background ...
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
fire Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
cd Downloading Minikube ISO ...
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
2019/04/22 22:19:13 No matching credentials were found, falling back on anonymous
2.25 MB / 142.88 MB [>------------------------------------------] 1.57% 9m36s

I haven't found any solution so far... any suggestion?

**Comment by grrowl** [comment]
@locojuhi read above, running `minikube start --cache-images=false` works around the issue
