### ISSUE TITLE
Sorry that minikube crashed

### ISSUE THREAD

**Issue by zhonghe987** [kubernetes/minikube#4041]

**Comment by ashutoshbhatt1** [comment]
After installing minikube from using `brew cask install minikube` command when you want to start minikube services using `minikube start` I see the same error 
![Screen Shot 2019-04-03 at 8 15 51 AM](https://user-images.githubusercontent.com/35776394/55481787-bb05bd80-55e8-11e9-9a4c-f698563e5569.png)

**Comment by ashutoshbhatt1** [comment]
I think i know VirtualBox is not installed in my environment after installing it is fixed. `Minikube` starts fine.

**Comment by ashutoshbhatt1** [comment]
After installing virtualbox still same issue
![Screen Shot 2019-04-03 at 8 40 11 AM](https://user-images.githubusercontent.com/35776394/55483418-243b0000-55ec-11e9-8e01-de7e07753037.png)

**Comment by tstromberg** [comment]
Closing due to lack of info.
