### ISSUE TITLE
sed: can't read /etc/containerd/config.toml: No such file or directory (--image-repository?)

### ISSUE THREAD

**Issue by zhonghe987** [kubernetes/minikube#4042]

**Comment by tstromberg** [comment]
Closing due to lack of information.

**Comment by tonnyone** [comment]
environment: 
system: CentOS Linux release 7.6.1810 
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.90.75
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 17.12.1-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.14.0 ...
-   Launching Kubernetes v1.14.0 using kubeadm ...

!   Error starting cluster: kubeadm init:
sudo sed -i 's/k8s.gcr.io/registry.cn-hangzhou.aliyuncs.com\/google_containers/g' /etc/containerd/config.toml &&
sudo sed -i 's/registry-1.docker.io/registry.docker-cn.com/g' /etc/containerd/config.toml &&
sudo systemctl restart containerd &&
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI


: running command:
sudo sed -i 's/k8s.gcr.io/registry.cn-hangzhou.aliyuncs.com\/google_containers/g' /etc/containerd/config.toml &&
sudo sed -i 's/registry-1.docker.io/registry.docker-cn.com/g' /etc/containerd/config.toml &&
sudo systemctl restart containerd &&
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI

 output: sed: can't read /etc/containerd/config.toml: No such file or directory
: running command:
sudo sed -i 's/k8s.gcr.io/registry.cn-hangzhou.aliyuncs.com\/google_containers/g' /etc/containerd/config.toml &&
sudo sed -i 's/registry-1.docker.io/registry.docker-cn.com/g' /etc/containerd/config.toml &&
sudo systemctl restart containerd &&
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI

**Comment by tstromberg** [comment]
What was the `minikube start` command used? I would like to reproduce this problem.

**Comment by tstromberg** [comment]
NOTE: I'm pretty sure this is related to use of `--image-repository`, which does not have much in the way of integration testing yet.

**Comment by userkk** [comment]
I also encountered the same problem，fuck zhe GFW

**Comment by tstromberg** [comment]
I suspect this error occurs when --image-repository is used in combination with --container-runtime=containerd, but have no confirmation of this yet. Help wanted!

**Comment by tonnyone** [comment]
I start command is this ： `minikube start --vm-driver=none`

**Comment by afbjorklund** [comment]
Normally (on on the minikube OS), the configuration file is installed with the containerd package:

https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/containerd-bin/containerd-bin.mk#L44:L46

However, on other platforms (such as `none` driver) that might not be the case - and thus missing.

Probably the script has to "touch" it or, or use some other way of making sure that it is populated ?

**Comment by tstromberg** [comment]
We're having trouble reproducing this issue so far. Does anyone else have a command-line to share which reproduces this bug?

**Comment by tstromberg** [comment]
Any luck reproducing this?

**Comment by tonnyone** [comment]
my dockder file path was configed start like 

ExecStart=/usr/bin/dockerd \
        --registry-mirror=https://xxxxx.mirror.aliyuncs.com \
        --insecure-registry=XXXXX:5000 \
        --graph /home/docker-store
is this make sence?

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
