### ISSUE TITLE
 Unable to start VM: WARNING: The vboxdrv kernel module is not loaded.

### ISSUE THREAD

**Issue by jainVish** [kubernetes/minikube#4043]

**Comment by balopat** [comment]
hi @jainVish, can you try to upgrade your virtualbox installation?

**Comment by tstromberg** [comment]
NOTE: This error is a sign of a failed VirtualBox installation. The solution is to reinstall VirtualBox. We should direct users to do so.

**Comment by frankmeten** [comment]
> NOTE: This error is a sign of a failed VirtualBox installation. The solution is to reinstall VirtualBox. We should direct users to do so. This may help isolate the specific failure as well:
> 
> `sudo modprobe vboxdrv`


CentOS 7 can reference the following link

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Kernel_Administration_Guide/sect-signing-kernel-modules-for-secure-boot.html

**Comment by John-Dormevil** [comment]
Try to:
- Deactivate Secure Boot from your bios system;
- Then run `sudo /sbin/vboxconfig` in case you install and use virtualbox 6+
- Then `minikube start`

**Comment by pythonInRelay** [comment]
I know this is closed, but I just wanted to say. The problem for me was a few missing packages, and then all I really needed to do was just reboot my machine and everything worked perfectly. I just installed a couple of packages, namely these ones:

`community/virtualbox 6.1.22-3 [installed]
community/virtualbox-ext-vnc 6.1.22-3 [installed]
community/virtualbox-guest-iso 6.1.22-1 [installed]
community/virtualbox-guest-utils 6.1.22-3 [installed]
community/virtualbox-host-dkms 6.1.22-3 [installed]
community/virtualbox-sdk 6.1.22-3 [installed]
chaotic-aur/linux-tkg-muqss 5.12.15-178 [installed]
chaotic-aur/virtualbox-ext-oracle 6.1.22-1 [installed]
chaotic-aur/virtualbox-meta 2-1 [installed]`

Rebooted my machine and no problem.

**Comment by OkabeRitarou** [comment]
Thanks @pythonInRelay
