### ISSUE TITLE
Allow configuring REGISTRY_STORAGE_DELETE_ENABLED for the registry addon

### ISSUE THREAD

**Issue by carroarmato0** [kubernetes/minikube#4044]
When enabling the Registry Addon, a docker registry is created in the cluster with defaults.

The defaults allow a user to push images to the private registry, not removing them.

The registry container needs to be spun up with the following environment variable: 
```
REGISTRY_STORAGE_DELETE_ENABLED=true
```

**Proposal**
Allow configuring the option similarly to how the registry-creds can be configured.

**Comment by balopat** [comment]
Thanks for filing this! It sounds completely reasonable to me.

**Comment by tstromberg** [comment]
This was fixed in v1.4. REGISTRY_STORAGE_DELETE_ENABLED=true is now the default.

**Comment by JohnGalt1717** [comment]
I wouldn't call this fixed. Now the default behavior is that on every restart of the computer the registry is empty

We need to be able configure this at the command line and configure a path for the volume mount for the storage.
