### ISSUE TITLE
ConfigMap got pruned when I try to create a ConfigMap in kube-system

### ISSUE THREAD

**Issue by solacens** [kubernetes/minikube#4050]
## Problem I found

When I tried to apply a new ConfigMap into kube-system of minikube, it will be disappeared after some time (maybe ~30s).

I noticed that the minikube addons manager is trying to kill resources but I am quite sure my ConfigMap doesn't really matter with the addons manager.

Now I have to disable the addons manager to keep my ConfigMap survive.

I'm wondering if better solution can be given.

## The exact command-lines used so that we can replicate the issue

[Related files](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/fluentd-elasticsearch)
`kubectl apply -n kube-system -f fluentd-es-configmap.yaml`

## Which operating system version was used

macOS `10.14.3`
minikube `v1.0.0`

**Comment by solacens** [comment]
Likely related to the label. See docs [here](https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager).

```yaml
labels:
    addonmanager.kubernetes.io/mode: Reconcile
```

My bad, putting it down incase someone may find it useful.

**Comment by tstromberg** [comment]
Thanks for the update!
