### ISSUE TITLE
Kubernetes persistent volume with minikube ScaleIOVolumeSource

### ISSUE THREAD

**Issue by papiveron** [kubernetes/minikube#4055]
Hello,

I'm fighting since many hours setting my k8s pods on my `minikube` single node, at persistent volume creation stage.

This command always ends with error, even if I copy/paste the example spec from `kubernetes` documentation :

    $kubectl apply -f pv-volume.yml

                                                                                    

> error: SchemaError(io.k8s.api.core.v1.ScaleIOVolumeSource): invalid
> object doesn't have additional properties

    $cat pv-volume.yml
    kind: PersistentVolume
    apiVersion: v1
    metadata:
      name: task-pv-volume
      labels:
        type: local
    spec:
      storageClassName: manual
      capacity:
        storage: 10Gi
      accessModes:
        - ReadWriteOnce
      hostPath:
        path: "/mnt/data"

I can't figure out why kubectl obliges me to specify `ScaleIO` in my spec, while I'm using local volume.

I've the same error specifying `storagaClassName` to `standard`

Any idea about what can be the problem?

My versions :

    $minikube version
    minikube version: v1.0.0

    $kubectl version
    Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:38:32Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
    Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-25T15:45:25Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

Thanks

**Comment by papiveron** [comment]
I've stoped `minikube` and restart it and now having this erro : 

```error: SchemaError(io.k8s.api.node.v1beta1.RuntimeClassList): invalid object doesn't have additional properties```

**Comment by papiveron** [comment]
I remove minikube and reinstall it from scratch, and now get the error when trying :
```error: SchemaError(io.k8s.api.extensions.v1beta1.ScaleStatus): invalid object doesn't have additional properties```

**Comment by papiveron** [comment]
I was going from error to error, then try to create another object such as secrets and the same issue.

Then 

- I removed kubectl in turn, and reinstall it,
- I stop mikube and start it again

It's now working, I can actually run my kube commands without errors

**Comment by balopat** [comment]
Hi @papiveron, it looks like the kubectl upgrade was the key to your solution, 1.10 client version was trying to talk to 1.14 - and the mismatch in API version can explain the weirdness in the error messages. Closing as it is resolved now, and not minikube related.

**Comment by tstromberg** [comment]
Related feature request: #3329
