### ISSUE TITLE
vbox: downloading binaries: write tcp: write: broken pipe

### ISSUE THREAD

**Issue by radhikapc** [kubernetes/minikube#4056]
OS: MacOS High Sierra 10.13.6, VirtualBox 6.0 (Version 6.0.4 r128413 (Qt5.6.3))

Minikube start command failed with the following message:

😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
❌  Unable to load cached images: loading cached images: loading image /Users/radhikap/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.14.0: transferring cached image: wait: remote command exited without exit status or exit signal
💾  Downloading kubelet v1.14.0
💾  Downloading kubeadm v1.14.0

💣  Failed to update cluster: downloading binaries: copy: pre-copy: NewSession: write tcp 127.0.0.1:55087->127.0.0.1:55060: write: broken pipe

**Comment by tstromberg** [comment]
Thanks for the bug report! I'm sorry that minikube did not work for you here.

Do you mind attaching the output of `minikube logs`? It sounds like either the VirtualBox VM or VirtualBox networking is not stable on this machine, and it would help me determine which one it is.

Is this VirtualBox 6.0.4? Earlier revisions of 6.0.x have some networking stability issues: https://www.virtualbox.org/wiki/Changelog

As a temporary workaround, you can try with the hyperkit driver: https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver

**Comment by radhikapc** [comment]
==> dmesg <==
[  +5.002722] hpet1: lost 318 rtc interrupts
[  +5.001179] hpet1: lost 318 rtc interrupts
[  +5.000985] hpet1: lost 318 rtc interrupts
[  +5.000994] hpet1: lost 318 rtc interrupts
[  +5.004788] hpet1: lost 319 rtc interrupts
[  +5.000360] hpet1: lost 318 rtc interrupts
[  +5.001262] hpet1: lost 318 rtc interrupts
[  +5.000847] hpet1: lost 318 rtc interrupts
[  +5.000613] hpet1: lost 318 rtc interrupts
[Apr 4 23:18] hpet1: lost 318 rtc interrupts
[  +5.001889] hpet1: lost 318 rtc interrupts
[  +5.001451] hpet1: lost 318 rtc interrupts
[  +5.002862] hpet1: lost 318 rtc interrupts
[  +5.002305] hpet1: lost 319 rtc interrupts
[  +5.001743] hpet1: lost 318 rtc interrupts
[  +5.003262] hpet1: lost 318 rtc interrupts
[  +5.002912] hpet1: lost 318 rtc interrupts
[  +5.000646] hpet1: lost 318 rtc interrupts
[  +5.002255] hpet1: lost 318 rtc interrupts
[  +5.002440] hpet1: lost 318 rtc interrupts
[  +5.001388] hpet1: lost 319 rtc interrupts
[Apr 4 23:19] hpet1: lost 318 rtc interrupts
[  +5.001758] hpet1: lost 318 rtc interrupts
[  +5.000901] hpet1: lost 318 rtc interrupts
[  +5.001165] hpet1: lost 318 rtc interrupts
[  +5.002019] hpet1: lost 318 rtc interrupts
[  +5.001259] hpet1: lost 318 rtc interrupts
[  +5.001615] hpet1: lost 318 rtc interrupts
[  +5.001409] hpet1: lost 318 rtc interrupts
[  +5.001901] hpet1: lost 318 rtc interrupts
[  +5.002787] hpet1: lost 319 rtc interrupts
[  +5.000885] hpet1: lost 319 rtc interrupts
[  +5.001745] hpet1: lost 318 rtc interrupts
[Apr 4 23:20] hpet1: lost 318 rtc interrupts
[  +5.001630] hpet1: lost 318 rtc interrupts
[  +5.003830] hpet1: lost 318 rtc interrupts
[  +5.000552] hpet1: lost 318 rtc interrupts
[  +5.003567] hpet1: lost 319 rtc interrupts
[  +5.002167] hpet1: lost 318 rtc interrupts
[  +5.003483] hpet1: lost 318 rtc interrupts
[  +5.003734] hpet1: lost 318 rtc interrupts
[  +5.003283] hpet1: lost 318 rtc interrupts
[  +5.001922] hpet1: lost 320 rtc interrupts
[  +5.001703] hpet1: lost 318 rtc interrupts
[  +5.003046] hpet1: lost 318 rtc interrupts
[Apr 4 23:21] hpet1: lost 318 rtc interrupts
[  +5.003802] hpet1: lost 318 rtc interrupts
[  +5.001982] hpet1: lost 319 rtc interrupts
[  +5.004349] hpet1: lost 319 rtc interrupts
[  +5.005550] hpet1: lost 318 rtc interrupts

==> kernel <==
 23:21:27 up  1:03,  0 users,  load average: 0.00, 0.00, 0.00
Linux minikube 4.15.0 #1 SMP Tue Mar 26 02:53:14 UTC 2019 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Thu 2019-04-04 22:18:38 UTC, end at Thu 2019-04-04 23:21:27 UTC. --
-- No entries --

**Comment by tstromberg** [comment]
Just curious - has anyone repeated this with minikube v1.1?I We did some work to make file copies more robust, but I'm not convinced that it would have addressed this problem.

**Comment by aa7955** [comment]
I have the same issue with 1.1.

**Comment by mycryptonite** [comment]
Same issue with 1.2 as well. Using Virtualbox 6.0.4.

**Comment by mycryptonite** [comment]
Same issue with 1.2 as well. Using Virtualbox 6.0.4.

**Comment by tstromberg** [comment]
@radhikapc: I believe this issue is now addressed by minikube v1.4, as it changes the backing location of where images are stored. If you still see this issue with minikube v1.4 or higher, please reopen this issue by commenting with `/reopen`

Thank you for reporting this issue!

**Comment by delmendo** [comment]
/reopen 
I'm having this problem with Ubuntu 19.10 - Vritualbox 6 and 5.2 - Minikube 1.5.2 & 1.6.0.beta1
