### ISSUE TITLE
Verifying component health always fails with non-default --apiserver-port

### ISSUE THREAD

**Issue by moduspwnens** [kubernetes/minikube#4057]
System: macOS 10.14.4
minikube version: 1.0.0
Command: minikube start --apiserver-port=6443

When I do this, it always fails in the "Verifying component health" stage. However, kubectl works as expected and the cluster seems to be in good health.

I'm not super familiar with golang, but it appears that the function being called to verify the apiserver's health is here:
https://github.com/kubernetes/minikube/blob/58a704521a9faf9fe496ccdaed2ac529c1693e58/cmd/minikube/cmd/start.go#L561

It's calling a "GetAPIServerStatus" method and passing in only the IP address of the apiserver. The function itself is here:

https://github.com/kubernetes/minikube/blob/89ab0be3b0c7a60b96793128850a98441966b96f/pkg/minikube/bootstrapper/kubeadm/kubeadm.go#L126

And for the port to use, it looks like it may be referencing a constant declared here as 8443:
https://github.com/kubernetes/minikube/blob/8ba53c6b0b6487e212a86a07f58a6b43ee8cf6e5/pkg/util/constants.go#L27

Presumably it should only reference the constant if the user didn't specify the API server port. Although again, my experience with golang is small.

**Comment by moduspwnens** [comment]
$ minikube start --apiserver-port=6443
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.99.165
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🚀  Launching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health ..................................
💣  apiserver checks failed: Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: WRN: == Error getting default service account, runable to recognize "STDIN": Get https://loetry in 0.5 second ==c
    error: unable to reWRN: == Errocognize "STr getting defDIN": Get https://locaault serviclhost:8443/api?timeout=32e account, rs: dial tcp etry in 0.5 second ==
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused

**Comment by tstromberg** [comment]
Sorry to hear about this, but good catch! We'll definitely want to add `--apiserver-port` to our integration tests to make sure this doesn't break again in the future.

Help wanted!
