### ISSUE TITLE
Checking if hardware virtualization is enabled failed: open U:....VBox.log: The system cannot find the path specified.

### ISSUE THREAD

**Issue by jtoepfer** [kubernetes/minikube#4062]
[VBox.log](https://github.com/kubernetes/minikube/files/3047910/VBox.log)

PS C:\Tools\minicube> .\minikube.exe start
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Restarting existing virtualbox VM for "minikube" ...

!   Unable to start VM: start: Checking if hardware virtualization is enabled failed: open U:\.minikube\machines\minikube\minikube\Logs\VBox.log: The system cannot find the path specified.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
PS C:\Tools\minicube> .\minikube.exe stop
:   Stopping "minikube" in virtualbox ...
-   "minikube" stopped.

1.) I don't know why it's trying to write to the U: drive.
2.) Being a new user of Minikube, i'm not sure where to begin to diagnose this problem.

**Comment by tstromberg** [comment]
Thank you for the bug report! This does indeed seem weird. I don't have an explanation just yet, but a couple of ideas:

# First, try upgrading Virtualbox to v6.0
# Then run `minikube delete` 
# If this doesn't fix `minikube start`, then try adding `--no-vtx-check` to the options.

If you don't mind, please report back to let me know what helps. I'd like to make sure we can direct future users to the same path of resolution. Thanks!

**Comment by jtoepfer** [comment]
I'm still getting that strange error cannot write to the U:\...VBox.log, so I'm looking into what profiles were setup on this latop.  But I tried your suggestion here is the result.  I downloaded the latest Virtualbox, and also tried to delete the cluster and recreate.

!   Unable to start VM: start: Checking if hardware virtualization is enabled failed: open U:\.minikube\machines\minikub
e\minikube\Logs\VBox.log: The system cannot find the path specified.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
PS C:\Tools\minicube> .\minikube.exe start --no-vtx-check
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running virtualbox VM for "minikube" ...
:   Waiting for SSH access ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running virtualbox VM for "minikube" ...
:   Waiting for SSH access ...
PS C:\Tools\minicube> .\minikube.exe stop
:   Stopping "minikube" in virtualbox ...
-   "minikube" stopped.
PS C:\Tools\minicube> .\minikube.exe delete
x   Deleting "minikube" from virtualbox ...
-   The "minikube" cluster has been deleted.
PS C:\Tools\minicube> .\minikube.exe start -p localvm
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s

!   Unable to start VM
X   Error:         [NON_C_DRIVE] create: creating: open /.minikube/cache/iso/minikube-v1.0.0.iso: The system cannot find
 the path specified.
i   Advice:        Run minikube from the C: drive.
-   Related issues:
    - https://github.com/kubernetes/minikube/issue/1574

*   If the above advice does not help, please let us know:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by jtoepfer** [comment]
More details.  I did removed the vm using delete command and then I deleted my .minikube folder (starting over).  I also setup a local parameter in my environment variables called HARDDISK and set that to C:, which I found some person on MSDN corrected a problem.  With those changes, I also installed cygwin.  So in my testing I found that I am able to run start in cgwin, but in windows powershell I still get the error below.  At this point i'm staying with cygwin since it works, but at this point I would bet it is a configuration issue on my laptop or windows profile.

PS C:\Tools\minikube> .\minikube.exe start
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s

!   Unable to start VM
X   Error:         [NON_C_DRIVE] create: creating: open /.minikube/cache/iso/minikube-v1.0.0.iso: The system cannot find
 the path specified.
i   Advice:        Run minikube from the C: drive.
-   Related issues:
    - https://github.com/kubernetes/minikube/issue/1574

*   If the above advice does not help, please let us know:
-   https://github.com/kubernetes/minikube/issues/new
