### ISSUE TITLE
Setting node name via kubeadm extra config leads to a crash

### ISSUE THREAD

**Issue by simleo** [kubernetes/minikube#4063]
I tried setting the k8s node name with `minikube start --extra-config=kubeadm.node-name=foo`, but minikube crashed with a timeout. The kubelet logs contain `node "minikube" not found`, which is probably due to this line in `pkg/minikube/bootstrapper/kubeadm/versions.go`:

```
NewUnversionedOption(Kubelet, "hostname-override", constants.DefaultNodeName),
```

I was able to make it work with:

```
minikube start --extra-config=kubeadm.node-name=foo --extra-config=kubelet.hostname-override=foo
```

This took me by surprise, since I was expecting the `kubeadm` setting to affect the `kubelet` one in absence of any explicit settings for the latter. Maybe this just needs some extra docs, since the above workaround is available. Or perhaps a top-level `--node-name` option for `minikube start` that ensures a consistent handling of the flag in the various components.

**Comment by tstromberg** [comment]
When possible, we should avoid flags that cause crashes, especially when it's easy to do the right thing. I do like your idea of a `--node-name` flag to minikube. Help wanted!

**Comment by tstromberg** [comment]
It's unclear to me whether we should add a mechanism to set the node name outside of the `-p` (profile) feature. That said, I'm not sure if profiles currently sets a node name or not.

Regardless, we should do better than crashing.
