### ISSUE TITLE
Facing TLS handshake timeout exception after setting http proxy while starting minikube

### ISSUE THREAD

**Issue by hiteshsardana99** [kubernetes/minikube#4065]
Hi all,

I am trying to start minikube on my bare metal ubuntu 16.04 machine with http proxy. But facing TLS handshake timeout exception while starting.

Command for starting minikube :-

`minikube start --docker-env=HTTP_PROXY=$HTTP_PROXY --docker-env HTTPS_PROXY=$HTTPS_PROXY  --docker-env NO_PROXY=$no_proxy --vm-driver=none`

$HTTP_PROXY, $HTTPS_PROXY ,$no_proxy etc these variable are having proxy value that is perfectly fine. 

**Prerequisite for minikube** 
I have successfully installed docker and able to pull image after adding proxy for docker. 

I have tried so many time but always facing below issue

```
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 172.19.63.10
-   Configuring Docker as the container runtime ...
    - env HTTP_PROXY=[http_proxy_is_confidential]/
    - env HTTPS_PROXY=[https_proxy_is_confidential]/
    - env NO_PROXY=127.0.0.1,localhost,[system_ip_is_confidential]
-   Version of container runtime is 18.09.2
:   Waiting for image downloads to complete ...
E0408 21:24:06.969728   29129 start.go:209] Error caching images:  Caching images for kubeadm: caching images: caching image /root/.minikube/cache/images/k8s.gcr.io/etcd_3.3.10: fetching remote image: Get https://k8s.gcr.io/v2/: proxyconnect tcp: net/http: TLS handshake timeout
-   Preparing Kubernetes environment ...
X   Unable to load cached images: loading cached images: loading image /root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: stat /root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory
@   Downloading kubeadm v1.14.0
@   Downloading kubelet v1.14.0

!   Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.14.0: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubelet: proxyconnect tcp: net/http: TLS handshake timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubelet: proxyconnect tcp: net/http: TLS handshake timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubelet: proxyconnect tcp: net/http: TLS handshake timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubelet: proxyconnect tcp: net/http: TLS handshake timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubelet: proxyconnect tcp: net/http: TLS handshake timeout

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

```

Note :- http proxy , https proxy and system ip from above code is hided by me. Do not consider it as an error.

I feel minikube is not able to use this proxy. I need to change some other things as well. 

I have added config.json file as well at /root/.docker location.

config.json file content 

```
  "proxies": {
    "default": {
      "httpProxy": "http_proxy_is_confidential",
      "HTTP_PROXY": "http_proxy_is_confidential",
      "NO_PROXY":"127.0.0.1,localhost,system_ip_is_confidential",
      "no_proxy":"127.0.0.1,localhost,system_ip_is_confidential"
    }
  },
  "credsStore" : "pass"
}
~
```

Please help me out from this issue.

**Comment by tstromberg** [comment]
Based on the output, it seems that minikube (outside of docker) is not noticing the environment variables being set. If you type "echo $HTTP_PROXY", what happens?

**Comment by hiteshsardana99** [comment]
I am getting the values of $HTTP_PROXY, $HTTPS_PROXY, $no_proxy variables.  And the proxy that I have used is perfectly fine. According to me, minikube is not able to use this proxy for performing its operations. Is there any other configuration that I have to set for using proxy in minikube?

**Comment by michtoen** [comment]
In your output it seems minikube is missing the env settings.

<pre>
minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Restarting existing hyperv VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.215.84
o   Found network options:
    - HTTP_PROXY=http://<PROXY>
    - HTTPS_PROXY=http://<PROXY>
    - NO_PROXY=localhost,10.96.0.1,10.0.2.15,192.168.215.84
-   Configuring Docker as the container runtime ...
    - env HTTP_PROXY=http://<PROXY>
    - env HTTPS_PROXY=http://<PROXY>
    - env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.68.99.1/24,192.168.214.1/24,192.168.215.1/24
-   Version of container runtime is 18.06.2-ce
</pre>

Note the line "Found network options:" with the 2 proxy settings. Following that line are the proxy used by minikube, which should be come by the env settings.

The proxy settings which starts with a "- env ..." are only used by the VM. So, if that output is really like that, minikube itself was not able to find proxy settings in the current enviroment settings. You have to ensure that in your bash / script the proxy settings are visible.

**Comment by tstromberg** [comment]
I agree with @michtoen - based on the output, it seems like you've specified --docker-env environment variables, which works for docker, but not minikube. 

The HTTPS_PROXY environment variable will need to be set. When it is, it will be listed under "Found network options". Please see https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md for help.
