### ISSUE TITLE
Unable to start VM: start: exit status 1 (OutOfMemory)

### ISSUE THREAD

**Issue by YZWLEO** [kubernetes/minikube#4067]
[stderr =====>] :
I0409 10:07:29.107329   14084 cluster.go:92] Machine state:  Stopped
:   Restarting existing hyperv VM for "minikube" ...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minikube
[stdout =====>] :
[stderr =====>] : Hyper-V\Start-VM : “minikube”无法启动。
系统内存不足，无法启动虚拟机 minikube。
无法初始化内存: Ran out of memory (0x8007000E)。
“minikube”无法启动。(虚拟机 ID 050C6E0B-D7A6-47F2-B19D-705D4AB19125)
系统内存不足，无法启动虚拟机 minikube，需要内存大小 6144 MB。(虚拟机 ID 050C6E0B-D7A6-47F2-B19D-705D4AB19125)
“minikube”无法初始化内存: Ran out of memory (0x8007000E)。(虚拟机 ID 050C6E0B-D7A6-47F2-B19D-705D4AB19125)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

I0409 10:07:41.931331   14084 start.go:384] StartHost: start: exit status 1
I0409 10:07:41.956329   14084 utils.go:122] non-retriable error: start: exit status 1
W0409 10:07:41.998339   14084 exit.go:99] Unable to start VM: start: exit status 1

!   Unable to start VM: start: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
This problem is raised when HyperV runs out of memory: You'll need more RAM on your system, or to specify a lower `--memory` value to minikube.

We could definitely stand to make this more userfriendly, so I'm tagging this issue as requiring a proper solution message.
