### ISSUE TITLE
kvm2: Add support for LIBVIRT_DEFAULT_URI 

### ISSUE THREAD

**Issue by youdX** [kubernetes/minikube#4069]
LIBVIRT_DEFAULT_URI=qemu+tcp://127.0.0.1:16509/system minikube start --vm-driver kvm2

```
😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.

💣  Unable to start VM: Error getting state for host: getting connection: getting domain: 
Error connecting to libvirt socket.  Have you set up libvirt correctly?

# Install libvirt and qemu-kvm on your system, e.g.
# Debian/Ubuntu (for older Debian/Ubuntu versions, you may have to use libvirt-bin instead of libvirt-clients and libvirt-daemon-system)
$ sudo apt install libvirt-clients libvirt-daemon-system qemu-kvm
# Fedora/CentOS/RHEL
$ sudo yum install libvirt-daemon-kvm qemu-kvm

# Add yourself to the libvirt group so you don't need to sudo
# NOTE: For older Debian/Ubuntu versions change the group to [libvirtd]
$ sudo usermod -a -G libvirt $(whoami)

# Update your current session for the group change to take effect
# NOTE: For older Debian/Ubuntu versions change the group to [libvirtd]
$ newgrp libvirt

Visit https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver for more information.
: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

Archlinux, Linux clx 4.19.34-1-lts #1 SMP Sat Apr 6 19:41:19 CEST 2019 x86_64 GNU/Linux

A fix might have to be done here, taking in an environment variable or some new flag:

> pkg/drivers/kvm/domain.go:143:	conn, err := libvirt.NewConnect(qemusystem)
> pkg/drivers/kvm/kvm.go:85:	qemusystem                = "qemu:///system"

**Comment by youdX** [comment]
A workaround could be to do like this: sudo socat -d -d -d -lf socat.log UNIX-LISTEN:/var/run/libvirt/libvirt-sock,fork,user=someuser,group=someuser TCP4:127.0.0.1:16509

**Comment by tstromberg** [comment]
The kvm2 driver should be sudo-less, so I'm not a big fan of the socat approach.

That said, I would be happy to review any PR which fixes this that does not require root. Help wanted!

**Comment by josedonizetti** [comment]
@afbjorklund I'm working on this issue here. Basically allowing the user to pass a flag `--kvm-qemu-uri`. This allows one to pass the URI for a remote qemu. But this also allows one to pass URI for `qemu:///session`, which I saw is a problem you commented on https://github.com/kubernetes/minikube/issues/4288.

Do we still want to support remote QEMUS? Or based on the problems you described, we want to force the use for `qemu://system` only. Or maybe we want to validate the URL, and as long as the user passes the system URI (remote or local) we allow, but for session one we fail the start.

WDYT?

**Comment by afbjorklund** [comment]
As long as the default still works, I have no problem with allowing advanced users to override with e.g. `MINIKUBE_LIBVIRT_DEFAULT_URI`. But the result won't be "supported" as such, especially if it is just some root-equivalent hack similar to docker.sock.

I also don't want to support remote KVM, there are a _lot_ of other options if you want to run Kubernetes in a cloud ? We just need something that can spin up a VM locally, similar to the "good ole" VirtualBox. And preferrably without using [SLIRP networking](https://wiki.qemu.org/Documentation/Networking#User_Networking_.28SLIRP.29)...
