### ISSUE TITLE
Make --extra-config "Unknown component" error message user-friendly

### ISSUE THREAD

**Issue by marcellmajor** [kubernetes/minikube#4070]
minikube start --kubernetes-version v1.6.0 --vm-driver virtualbox  --memory 4096 --network-plugin=cni --host-only-cidr 172.17.17.1/24 \
>     --extra-config=kubelet.PodCIDR=192.168.0.0/16 \
>     --extra-config=proxy.ClusterCIDR=192.168.0.0/16 \
>     --extra-config=controller-manager.ClusterCIDR=192.168.0.0/16 \
>     --extra-config=controller-manager.CIDRAllocatorType=RangeAllocator \
>     --extra-config=controller-manager.AllocateNodeCIDRs=true
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.6.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=3, Memory=4096MB, Disk=20000MB) ...
📶  "minikube" IP address is 172.17.17.101
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
    ▪ kubelet.PodCIDR=192.168.0.0/16
    ▪ proxy.ClusterCIDR=192.168.0.0/16
    ▪ controller-manager.ClusterCIDR=192.168.0.0/16
    ▪ controller-manager.CIDRAllocatorType=RangeAllocator
    ▪ controller-manager.AllocateNodeCIDRs=true

💣  Failed to update cluster: generating kubeadm cfg: generating extra component config for kubeadm: Unknown component map[scheduler:scheduler kubeadm:kubeadm kubelet: apiserver:apiServer controller-manager:controllerManager].  Valid components and kubeadm config are map[apiserver:apiServer controller-manager:controllerManager scheduler:scheduler kubeadm:kubeadm kubelet:]

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
FWIW, my guess here is the --extra-config=proxy flag.
