### ISSUE TITLE
Waiting for an IP...  An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by liadlev** [kubernetes/minikube#4073]
hi guys,
im trying to run " minikube start --no-vtx-check --v=8" and i get this error :

`$ minikube start --no-vtx-check --v=8
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
Reading certificate data from C:\cygwin64\home\itaym\.minikube\certs\ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from C:\cygwin64\home\itaym\.minikube\certs\cert.pem
Decoding PEM data...
Parsing certificate...
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
STDOUT:
{
6.0.4r128413
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
STDOUT:
{
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            23af20bc-b22e-4570-988b-e21a2c994775
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::3958:afd8:90eb:6a2c
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:21
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            4d223fb7-fc51-480c-8b16-3b978441cbc9
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::eca2:e7a2:710a:6b9e
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

}
STDERR:
{
}
Downloading C:\cygwin64\home\itaym\.minikube\cache\boot2docker.iso from file://C:/cygwin64/home/itaym/.minikube/cache/iso/minikube-v1.0.0.iso...
Creating VirtualBox VM...
Creating SSH key...
Creating disk image...
Creating 20000 MB hard disk image...
Writing magic tar header
Writing SSH key tar header
Calling inner createDiskImage
&{C:\Program Files\Oracle\VirtualBox\VBoxManage.exe [C:\Program Files\Oracle\VirtualBox\VBoxManage.exe convertfromraw stdin C:\cygwin64\home\itaym\.minikube\machines\minikube\disk.vmdk 20971520000 --format VMDK] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}
Starting command
Copying to stdin
Filling zeroes
Closing STDIN
Waiting on cmd
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe createvm --basefolder C:\cygwin64\home\itaym\.minikube\machines\minikube --name minikube --register
STDOUT:
{
Virtual machine 'minikube' is created and registered.
UUID: 42d6dae4-a1c5-43fc-92ed-cfb5c4ead5a6
Settings file: 'C:\cygwin64\home\itaym\.minikube\machines\minikube\minikube\minikube.vbox'
}
STDERR:
{
}
VM CPUS: 2
VM Memory: 2048
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 2 --memory 2048 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 on --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --nic1 nat --nictype1 virtio --cableconnected1 on
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe storagectl minikube --name SATA --add sata --hostiocache on
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium C:\cygwin64\home\itaym\.minikube\machines\minikube\boot2docker.iso
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe storageattach minikube --storagectl SATA --port 1 --device 0 --type hdd --medium C:\cygwin64\home\itaym\.minikube\machines\minikube\disk.vmdk
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestproperty set minikube /VirtualBox/GuestAdd/SharedFolders/MountPrefix /
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe guestproperty set minikube /VirtualBox/GuestAdd/SharedFolders/MountDir /
STDOUT:
{
}
STDERR:
{
}
setting up shareDir '\\?\c:\Users' -> 'c/Users'
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe sharedfolder add minikube --name c/Users --hostpath \\?\c:\Users --automount
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe setextradata minikube VBoxInternal2/SharedFoldersEnableSymlinksCreate/c/Users 1
STDOUT:
{
}
STDERR:
{
}
Starting the VM...
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="42d6dae4-a1c5-43fc-92ed-cfb5c4ead5a6"
CfgFile="C:\\cygwin64\\home\\itaym\\.minikube\\machines\\minikube\\minikube\\minikube.vbox"
SnapFldr="C:\\cygwin64\\home\\itaym\\.minikube\\machines\\minikube\\minikube\\Snapshots"
LogFldr="C:\\cygwin64\\home\\itaym\\.minikube\\machines\\minikube\\minikube\\Logs"
hardwareuuid="42d6dae4-a1c5-43fc-92ed-cfb5c4ead5a6"
memory=2048
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="poweroff"
VMStateChangeTime="2019-04-10T12:55:28.044000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\cygwin64\home\itaym\.minikube\machines\minikube\boot2docker.iso"
"SATA-ImageUUID-0-0"="2d43ff60-ee16-4d0f-b582-1364ea84867f"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\cygwin64\home\itaym\.minikube\machines\minikube\disk.vmdk"
"SATA-ImageUUID-1-0"="8d00ef31-3909-49b7-b473-5f9dcb041565"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800275B6F12"
cableconnected1="on"
nic1="nat"
nictype1="virtio"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
nic2="none"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="dsound"
audio_in="off"
audio_out="off"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="\\\\?\\c:\\Users"
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\cygwin64\\home\\itaym\\.minikube\\machines\\minikube\\minikube\\minikube.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
}
STDERR:
{
}
Check network to re-create if needed...
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
STDOUT:
{
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            23af20bc-b22e-4570-988b-e21a2c994775
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::3958:afd8:90eb:6a2c
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:21
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            4d223fb7-fc51-480c-8b16-3b978441cbc9
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::eca2:e7a2:710a:6b9e
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

}
STDERR:
{
}
Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
Found: VirtualBox Host-Only Ethernet Adapter #2
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list dhcpservers
STDOUT:
{
NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
IP:             192.168.56.100
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.56.101
upperIPAddress: 192.168.56.254
Enabled:        Yes
Global options:
   1:255.255.255.0

NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2
IP:             192.168.99.6
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes
Global options:
   1:255.255.255.0

}
STDERR:
{
}
Removing orphan DHCP servers...
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
STDOUT:
{
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            23af20bc-b22e-4570-988b-e21a2c994775
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::3958:afd8:90eb:6a2c
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:21
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            4d223fb7-fc51-480c-8b16-3b978441cbc9
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::eca2:e7a2:710a:6b9e
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

}
STDERR:
{
}
Adding/Modifying DHCP server "192.168.99.21" with address range "192.168.99.100" - "192.168.99.254"...
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list dhcpservers
STDOUT:
{
NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
IP:             192.168.56.100
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.56.101
upperIPAddress: 192.168.56.254
Enabled:        Yes
Global options:
   1:255.255.255.0

NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2
IP:             192.168.99.6
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes
Global options:
   1:255.255.255.0

}
STDERR:
{
}
Windows might ask for the permission to configure a dhcp server. Sometimes, such confirmation window is minimized in the taskbar.
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe dhcpserver modify --netname HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2 --ip 192.168.99.21 --netmask 255.255.255.0 --lowerip 192.168.99.100 --upperip 192.168.99.254 --enable
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --nic2 hostonly --nictype2 virtio --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter #2 --cableconnected2 on
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --natpf1 delete ssh
STDOUT:
{
}
STDERR:
{
VBoxManage.exe: error: Code E_INVALIDARG (0x80070057) - One or more arguments are invalid (extended info not available)
VBoxManage.exe: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1866 of file VBoxManageModifyVM.cpp
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --natpf1 ssh,tcp,127.0.0.1,59815,,22
STDOUT:
{
}
STDERR:
{
}
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless
STDOUT:
{
Waiting for VM "minikube" to power on...
VM "minikube" has been successfully started.
}
STDERR:
{
}
Waiting for an IP...
Getting to WaitForSSH function...
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8359b0] 0x835980  [] 0s} 127.0.0.1 59815 <nil> <nil>}
About to run SSH command:
exit 0
Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:59817->127.0.0.1:59815: wsarecv: An existing connection was forcibly closed by the remote host.
`

i have windows 10 Home ,using VM virtual box, firewall is disabled.
looks like this error is due to ssh problem.

**Comment by tstromberg** [comment]
Thank you for the bug report! I don't yet fully understand this code path, but the error seems to be raised by vendor/github.com/docker/machine/libmachine/ssh/client.go

My best guess here is some sort of VM stability issue: I can't imagine a firewall blocking packets to localhost. Does `minikube logs` happen to work for you to get more information?

Is this problem reproducible if you run `minikube delete` and `minikube start` again?

**Comment by liadlev** [comment]
this is the outpout of minikube logs:
minikube logs

!   command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new


i tried several times using minikube delete and start

**Comment by algakzru** [comment]
@liadlev Have you found a workaround ? I have similar issue here #4487.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube & Virtualbox, please feel free to re-open it. 

Thank you for opening the issue!
