### ISSUE TITLE
hyperv: no External vswitch found. A valid vswitch must be available for this command to run

### ISSUE THREAD

**Issue by alexpolgithub** [kubernetes/minikube#4074]
minikube start --vm-driver=hyperv -v 10

PS C:\WINDOWS\system32> minikube start --vm-driver=hyperv -v 10
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 142.80 MB / 142.88 MB [============================================]  99.94% 0s
 142.88 MB / 142.88 MB [============================================] 100.00% 0sCreating CA: C:\Users\somuser\.minikube\certs\ca.pem
Creating client certificate: C:\Users\someuser\.minikube\certs\cert.pem
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Module -ListAvailable hyper-v).Name | Get-Unique
[stdout =====>] : Hyper-V

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("S-1-5-32-578")
[stdout =====>] : False

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
[stdout =====>] : True

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive [Console]::OutputEncoding = [Text.Encoding]::UTF8; (Hyper-V\Get-VMSwitch -SwitchType External).Name
[stdout =====>] :
[stderr =====>] :

!   Unable to start VM: create: precreate: no External vswitch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

Windows 10

**Comment by tstromberg** [comment]
This issue just needs to get added to the list of known solutions so that it doesn't say that the crash was unexpected.

On a related note, I've opened #4079 because HyperV users shouldn't need to configure networking, as other VM drivers do not have this requirement.
