### ISSUE TITLE
Related issues link gives 404 (typo)

### ISSUE THREAD

**Issue by weissne** [kubernetes/minikube#4077]
When I tried to start with minikube I got an error stating "Unable to start the VM"
The error contained a "Related issues" link which doesn't exist (return code 404).

Link: 
https://github.com/kubernetes/minikube/issue/3900

Complete print out:
root@ubuntu18-4:~# sudo minikube start --memory 4096 --cpus=4 --disk-size 100g --insecure-registry="devart01:8081"
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
>   Creating virtualbox VM (CPUs=4, Memory=4096MB, Disk=100000MB) ...
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous
2019/04/11 09:56:59 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/11 09:56:59 No matching credentials were found, falling back on anonymous

!   Unable to start VM
X   Error:         [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
i   Advice:        In some environments, this message is incorrect. Try 'minikube start --no-vtx-check'
-   Related issues:
    - https://github.com/kubernetes/minikube/issue/3900

*   If the above advice does not help, please let us know:
-   https://github.com/kubernetes/minikube/issues/new
root@ubuntu18-4:~#

Thanks

**Comment by afbjorklund** [comment]
Fixed in PR #4048 

Correct link: `https://github.com/kubernetes/minikube/issues/3900`

**Comment by tstromberg** [comment]
Thanks for the bug report! This issue is fixed at head, but let's leave this bug open until v1.0.1 to prevent dupes.

**Comment by tstromberg** [comment]
v1.0.1 now incorporates this fix.
