### ISSUE TITLE
Hyper-V: Use the "Default Switch" (NAT based) by default

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4079]
Manually configuring HyperV networks is painful and a cause of many user issues. We should just create the network automatically, as with other VM drivers.

**Comment by medyagh** [comment]
That should be do-able, Microsoft has instructions to create virtual switch in command line 
https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/connect-to-network

the only tricky part I see is, deciding which adaptor to connect the switch to ( WIFI, Ethernet, other virtual interfaces)

**Comment by tstromberg** [comment]
This would address many bugs, such as #3963

**Comment by laozc** [comment]
PR machine-drivers/machine#18 addressed the issue to use the default switch when not specified.

**Comment by tstromberg** [comment]
Once https://github.com/machine-drivers/machine/pull/18 is merged, I believe this can be addressed by repinning the version of the machine-drivers we import.

I believe this can be landed by v1.4.0 (Sep 16)

**Comment by tstromberg** [comment]
Update: https://github.com/machine-drivers/machine/pull/18 is looking good, waiting on review by @gbraad - the end is near!

**Comment by tstromberg** [comment]
This landed with #5311

**Comment by gbraad** [comment]
Sorry for the delay.

Since minikube does not enforce any minimum version of Windows, there is a possibility of a localization issue. We decided to merge nonetheless and fix this later if proving to be an issue.
