### ISSUE TITLE
EC2 - Unable to start minikube k8s-app=kube-proxy: timed out waiting

### ISSUE THREAD

**Issue by nvkkgithub** [kubernetes/minikube#4083]
root@XXXXXXXXX:~# minikube start --vm-driver=none
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Restarting existing none VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is XXXXXXXXX
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.09.2
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.14.0 ...
:   Relaunching Kubernetes v1.14.0 using kubeadm ...
:   Waiting for pods: apiserver proxy
!   Error restarting cluster: wait: waiting for k8s-app=kube-proxy: timed out waiting for the condition

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
X   Problems detected in "kube-addon-manager":
    - error: no objects passed to apply
    - error: no objects passed to apply
    - error: no objects passed to apply

**Comment by tstromberg** [comment]
Thanks for the bug report! Do you mind including the output of `minikube logs`

I suspect kube-proxy isn't playing well with the kernel used in your ec2 image.

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube and run `minikube delete` to remove the previous cluster state.

If the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!
