### ISSUE TITLE
minikube crashed

### ISSUE THREAD

**Issue by phelepno** [kubernetes/minikube#4085]
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy
💣  Error restarting cluster: wait: waiting for k8s-app=kube-proxy: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objecINFO: == Successfuts passed to apply
    error: no objects passed to apply
    error: no objects passed to apply

kindly guide me what config is missing here.

**Comment by phelepno** [comment]
Issue resolved now , as this is related to Minikube version issue.
I was using the latest one (minikube v1.0.0) and struggling with the error so, I come down to below version 
minikube version: v0.35.0
and everything starts working fine.

**Comment by richardgragasin** [comment]
I also faced similar issue. what i did is i reinstall minikube and remove minikube folder on machines directory. you can find the path below. 
C:\Users\User\.minikube\machines\minikube

**Comment by sidh0073** [comment]
I'm facing issue
Details: 00:00:02.639508 Power up failed (vrc=VERR_VMX_MSR_ALL_VMX_DISABLED, rc=E_FAIL (0X80004005))

X Unable to start VM: start: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.639508 Power up failed (vrc=VERR_VMX_MSR_ALL_VMX_DISABLED, rc=E_FAIL (0X80004005))

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
