### ISSUE TITLE
Unable to evaluate output of `docker-env`: Command 'docker' not found

### ISSUE THREAD

**Issue by staticdev** [kubernetes/minikube#4089]
Fresh installed minikube on Ubuntu 18.10:
```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube
sudo cp minikube /usr/local/bin && rm minikube
```

* How to reproduce the error (just 3 commands):
`minikube start`

😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
📯  Updating kube-proxy configuration ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!

```
eval $(minikube docker-env)
docker ps
```

I get in respose:

> Command 'docker' not found, but can be installed with:
> 
> sudo snap install docker     # version 18.06.1-ce, or
> sudo apt  install docker.io
> 
> See 'snap info docker' for additional versions.

**Comment by staticdev** [comment]
I've confirmed docker is a requirement to run minikube. So it is a documentation issue.

**Comment by afbjorklund** [comment]
You need _a_ container runtime, there are several to choose from. Docker is the default.

**Comment by afbjorklund** [comment]
Note that what we document is installing `kubectl`, and using that to talk to the cluster.
Using `docker' and `docker-env` is an advanced topic, and not available everywhere...

As a workaround you can use `minikube ssh`, and then run the commands on the VM ?
But anyway, you don't absolutely need a docker client - but should be documented anyway.

**Comment by staticdev** [comment]
I think there should be a: Install a container runtime such as [Docker](https://docs.docker.com/install/) even before install `kubectl` since the main purpose is container orchestration and minikube doesn't come by default with a runtime.

**Comment by afbjorklund** [comment]
Well, there is a runtime (or three) on the VM - it just doesn't come with a _local_ runtime ? What could be needed, however, is a better way to build new images, than doing it directly on the control plane node.

The current approach is more of a hack, and I guess it could mention that you need to install docker:
https://github.com/kubernetes/minikube/blob/master/docs/reusing_the_docker_daemon.md

(Mirrored at: https://kubernetes.io/docs/setup/minikube/#use-local-images-by-re-using-the-docker-daemon)

As long as we recommend that approach, we should add a link to: https://docs.docker.com/install/
And probably mention that you only need the Docker _client_, not the entire daemon and everything.

**Comment by afbjorklund** [comment]
If you want to do other interaction with the [CRI](https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/) directly, the recommend approach is now `crictl`:

``` console
$ minikube ssh -- sudo crictl ps
```

That will work for _all_ of the runtimes, including Docker. But it doesn't have a local/remote client/server.

It would perhaps be interesting to see if there are any more uses of a local docker, **not** covered by crictl ?

**Comment by tstromberg** [comment]
> I've confirmed docker is a requirement to run minikube. So it is a documentation issue.

As someone who does not have docker installed, I can definitely say docker is not a requirement to run minikube.  As afbjorklund mentions, we do however include it within the minikube VM.

**Comment by tstromberg** [comment]
Closing, as minikube doesn't actually invoke docker.

**Comment by staticdev** [comment]
@tstromberg minikube doesn't invoke docker, but it's documentation (https://kubernetes.io/docs/tasks/tools/install-minikube/) is misleading with this information without saying installing docker on the host machine is a prerequisite to run this commands...

**Comment by afbjorklund** [comment]
Documenting it on the `docker-env` page makes sense. Probably can leave the details on _how_, to Docker Inc.
