### ISSUE TITLE
minikube update upgraded kubernetes to 1.14 and now crashes minikube start

### ISSUE THREAD

**Issue by fatdrag0n** [kubernetes/minikube#4094]
Hello,

I downloaded latest minikube and replaced my old minikube on my ubuntu 18 and it also upgraded my kubernetes but something went wrong and now fails to start minikube, 

```

sudo minikube start
😄  minikube v1.0.0 on linux (amd64)
👍  minikube will upgrade the local cluster from Kubernetes 1.10.0 to 1.14.0
🤹  Downloading Kubernetes v1.14.0 images in the background ...

⚠️  Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using th      e none driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-dri      ver=virtualbox`
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`

🔄  Restarting existing none VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.2.112
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
2019/04/13 06:18:19 No matching credentials were found, falling back on anonymous
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.09.2
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.14.0
💾  Downloading kubelet v1.14.0
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ...

💣  Error restarting cluster: running cmd: sudo kubeadm init phase kubeconfig all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase kubeconfig all --config /var/lib/kubeadm.yaml: exit status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objects passed to apply
    error: no objects passed to apply
    error: no objects passed to apply

```
I also tried with vm-driver=none
```
 sudo minikube start --vm-driver=none
😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing none VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.2.112
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.09.2
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ...

💣  Error restarting cluster: running cmd: sudo kubeadm init phase kubeconfig all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase kubeconfig all --config /var/lib/kubeadm.yaml: exit status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

```
logs

`sudo minikube logs
==> dmesg <==
[  +0.000043] ACPI Exception: Could not find/resolve named package element: LNKC (20170831/dspkginit-381)
[  +0.000106] ACPI Exception: Could not find/resolve named package element: LNKB (20170831/dspkginit-381)
[  +0.000044] ACPI Exception: Could not find/resolve named package element: LNKC (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKD (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKA (20170831/dspkginit-381)
[  +0.000103] ACPI Exception: Could not find/resolve named package element: LNKC (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKD (20170831/dspkginit-381)
[  +0.000044] ACPI Exception: Could not find/resolve named package element: LNKA (20170831/dspkginit-381)
[  +0.000043] ACPI Exception: Could not find/resolve named package element: LNKB (20170831/dspkginit-381)
[  +0.000102] ACPI Exception: Could not find/resolve named package element: LNKD (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKA (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKB (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKC (20170831/dspkginit-381)
[  +0.000102] ACPI Exception: Could not find/resolve named package element: LNKA (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKB (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKC (20170831/dspkginit-381)
[  +0.000042] ACPI Exception: Could not find/resolve named package element: LNKD (20170831/dspkginit-381)
[  +0.087066] pci 0000:00:01.0: MSI quirk detected; subordinate MSI disabled
[  +1.527856] i8042: Failed to disable AUX port, but continuing anyway... Is this a SiS?
[  +0.000033] i8042: If AUX port is really absent please use the 'i8042.noaux' option
[  +0.855657] r8169 0000:03:00.0: can't disable ASPM; OS doesn't have ASPM control
[  +0.000624] r8169 0000:04:00.0: can't disable ASPM; OS doesn't have ASPM control
[  +0.001905] ACPI Warning: SystemIO range 0x0000000000000B00-0x0000000000000B08 conflicts with OpRegion 0x0000000000000B00-0x0000000000000B0F (\SOR1) (20170831/utaddress-247)
[  +0.052392] resource sanity check: requesting [mem 0x000c0000-0x000dffff], which spans more than pnp 00:07 [mem 0x000d1000-0x000d3fff]
[  +0.000039] caller pci_map_rom+0x5d/0xf0 mapping multiple BARs
[Apr13 07:21] print_req_error: I/O error, dev fd0, sector 0
[ +28.483878] print_req_error: I/O error, dev fd0, sector 0
[  +1.613333] systemd[1]: Configuration file /lib/systemd/system/kubelet.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
[  +0.016517] systemd[1]: Configuration file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
[Apr13 07:22] EXT4-fs (sdb2): warning: mounting unchecked fs, running e2fsck is recommended
[ +18.140516] new mount options do not match the existing superblock, will be ignored
[ +25.129455] kauditd_printk_skb: 13 callbacks suppressed
[Apr13 07:27] print_req_error: I/O error, dev fd0, sector 0
[ +23.212763] print_req_error: I/O error, dev fd0, sector 0
[Apr13 07:32] print_req_error: I/O error, dev fd0, sector 0
[ +23.243491] print_req_error: I/O error, dev fd0, sector 0
[Apr13 07:33] print_req_error: I/O error, dev fd0, sector 0
[Apr13 07:34] print_req_error: I/O error, dev fd0, sector 0
[ +23.208796] print_req_error: I/O error, dev fd0, sector 0
[Apr13 07:35] print_req_error: I/O error, dev fd0, sector 0
[ +36.640316] print_req_error: I/O error, dev fd0, sector 0
[Apr13 07:45] print_req_error: I/O error, dev fd0, sector 0
[ +23.195390] print_req_error: I/O error, dev fd0, sector 0
[Apr13 07:46] print_req_error: I/O error, dev fd0, sector 0
[Apr13 07:57] print_req_error: I/O error, dev fd0, sector 0
[ +23.180258] print_req_error: I/O error, dev fd0, sector 0
[Apr14 02:31] print_req_error: I/O error, dev fd0, sector 0
[ +23.712526] print_req_error: I/O error, dev fd0, sector 0
[Apr14 02:34] print_req_error: I/O error, dev fd0, sector 0
[ +23.128361] print_req_error: I/O error, dev fd0, sector 0

==> kernel <==
 02:35:11 up 19:14,  1 user,  load average: 0.68, 0.39, 0.16
Linux itclab1 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

==> kube-addon-manager <==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp [::1]:8443: connect: connection refused
WRN: == Failed to start /opt/namespace.yaml in namespace  at 2019-04-14T02:33:35+00:00. 92 tries remaining. ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==
The connection to the server localhost:8443 was refused - did you specify the right host or port?
WRN: == Error getting default service account, retry in 0.5 second ==

==> kubelet <==
-- Logs begin at Wed 2018-08-15 08:47:48 UTC, end at Sun 2019-04-14 02:35:11 UTC. --
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.043997   20359 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192.168.2.112:8443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.080362   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.180616   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.280837   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.381102   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.481343   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.581629   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.627403   20359 controller.go:115] failed to ensure node lease exists, will retry in 7s, error: Get https://192.168.2.112:8443/apis/coordination.k8s.io/v1beta1/namespaces/kube-node-lease/leases/minikube?timeout=10s: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.681865   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.782099   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.882261   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:08 itclab1 kubelet[20359]: E0414 02:35:08.982510   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.003367   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.2.112:8443/api/v1/pods?fieldSelector=spec.nodeName%!D(MISSING)minikube&limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.004426   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Get https://192.168.2.112:8443/api/v1/nodes?fieldSelector=metadata.name%!D(MISSING)minikube&limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.005492   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get https://192.168.2.112:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.038641   20359 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://192.168.2.112:8443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.044872   20359 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192.168.2.112:8443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.082766   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.183013   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.283227   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.383465   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.483618   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.583824   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.684118   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.784358   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.884541   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:09 itclab1 kubelet[20359]: E0414 02:35:09.984769   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.004171   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.2.112:8443/api/v1/pods?fieldSelector=spec.nodeName%!D(MISSING)minikube&limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.005191   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Get https://192.168.2.112:8443/api/v1/nodes?fieldSelector=metadata.name%!D(MISSING)minikube&limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.006199   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get https://192.168.2.112:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.039490   20359 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://192.168.2.112:8443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.045730   20359 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192.168.2.112:8443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.084975   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.185274   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.285523   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.385705   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.486007   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.586254   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.686498   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.786684   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.886818   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:10 itclab1 kubelet[20359]: E0414 02:35:10.986974   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:11 itclab1 kubelet[20359]: E0414 02:35:11.005152   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.2.112:8443/api/v1/pods?fieldSelector=spec.nodeName%!D(MISSING)minikube&limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:11 itclab1 kubelet[20359]: E0414 02:35:11.006073   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Get https://192.168.2.112:8443/api/v1/nodes?fieldSelector=metadata.name%!D(MISSING)minikube&limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:11 itclab1 kubelet[20359]: E0414 02:35:11.006768   20359 reflector.go:126] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get https://192.168.2.112:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:11 itclab1 kubelet[20359]: E0414 02:35:11.040367   20359 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://192.168.2.112:8443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:11 itclab1 kubelet[20359]: E0414 02:35:11.046708   20359 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.RuntimeClass: Get https://192.168.2.112:8443/apis/node.k8s.io/v1beta1/runtimeclasses?limit=500&resourceVersion=0: dial tcp 192.168.2.112:8443: connect: connection refused
Apr 14 02:35:11 itclab1 kubelet[20359]: E0414 02:35:11.087166   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:11 itclab1 kubelet[20359]: E0414 02:35:11.187423   20359 kubelet.go:2244] node "minikube" not found
Apr 14 02:35:11 itclab1 kubelet[20359]: E0414 02:35:11.287598   20359 kubelet.go:2244] node "minikube" not found
`

**Comment by fatdrag0n** [comment]
Not sure what I did! but I tried many different things and remove the cluster and then starte with vm driver none, but I get reliablity ..what driver should I use, do I need to use virtualbox?

` sudo minikube start --vm-driver=none
😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.2.112
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.09.2
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🚀  Launching Kubernetes v1.14.0 using kubeadm ...
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

⚠️  kubectl and minikube configuration will be stored in /home/ben
⚠️  To use kubectl or minikube commands as your own user, you may
⚠️  need to relocate them. For example, to overwrite your own settings:

    ▪ sudo mv /home/ben/.kube /home/ben/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
`

**Comment by tstromberg** [comment]
I'm not sure what happened here yet, but you should be able to workaround this by running `minikube delete`.

**Comment by fatdrag0n** [comment]
Yea. ..I was able to recreate the cluster
but where is the slave? I thought it would be master, slave and workers and etc. with minikube!

**Comment by fatdrag0n** [comment]
All good. First few app deployments tests seem to be working:

sudo kubectl get deploy,po,svc
NAME                                        READY   UP-TO-DATE   AVAILABLE   AGE
deployment.extensions/deployment-example    3/3     3            3           8m2s
deployment.extensions/kubernetes-bootcamp   1/1     1            1           41h

NAME                                      READY   STATUS    RESTARTS   AGE
pod/deployment-example-6b6b8cbb5b-7blkk   1/1     Running   0          8m2s
pod/deployment-example-6b6b8cbb5b-g49km   1/1     Running   0          8m2s
pod/deployment-example-6b6b8cbb5b-l9x5p   1/1     Running   0          8m2s
pod/kubernetes-bootcamp-b94cb9bff-7f4m7   1/1     Running   0          41h

NAME                      TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
service/kubernetes        ClusterIP      10.96.0.1       <none>        443/TCP        4d22h
service/service-example   LoadBalancer   10.109.93.161   <pending>     80:30631/TCP   2m6s
