### ISSUE TITLE
coredns in error / CrashLoopBackOff

### ISSUE THREAD

**Issue by goyalnikhil02** [kubernetes/minikube#4096]
kube-system    coredns-86c58d9df4-qk56b                  0/1     Error              451        15d
kube-system    coredns-86c58d9df4-zwnjq                  0/1     CrashLoopBackOff   463        15d

How to fix this issue.
minikube dashboard is also not working.
It this the reason for above ?
Error:
503 Service Unavailable from Dashboard UI

**Comment by tstromberg** [comment]
Hey @goyalnikhil02 - Do you mind providing:

- The full `minikube start` command you are using
- What operating system you are on
- The output of `kubectl describe pod <name of coredns pod> -n kube-system`

In this case, <name of coredns pod> would be either coredns-86c58d9df4-qk56b or coredns-86c58d9df4-zwnjq

Thanks!

**Comment by champly** [comment]
@tstromberg 
i meet same trouble

- Ubuntu 19.04
- Linux champly 5.0.0-13-generic #14-Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- i use `sudo minikube start --vm-driver=none` to start

``` bash
# champly @ champly in ~/tmp/k8s [16:16:24] 
$ kubectl get pods --all-namespaces                        
NAMESPACE     NAME                                    READY   STATUS             RESTARTS   AGE
kube-system   coredns-fb8b8dccf-hn8ft                 0/1     CrashLoopBackOff   1          20s
kube-system   coredns-fb8b8dccf-l4xmp                 0/1     CrashLoopBackOff   1          10s
kube-system   etcd-minikube                           1/1     Running            0          49m
kube-system   kube-addon-manager-minikube             1/1     Running            0          49m
kube-system   kube-apiserver-minikube                 1/1     Running            0          49m
kube-system   kube-controller-manager-minikube        1/1     Running            0          49m
kube-system   kube-proxy-9t847                        1/1     Running            0          50m
kube-system   kube-scheduler-minikube                 1/1     Running            0          49m
kube-system   kubernetes-dashboard-79dd6bfc48-zkppc   1/1     Running            4          50m
kube-system   storage-provisioner                     1/1     Running            0          50m

# champly @ champly in ~/tmp/k8s [16:16:30] 
$ kubectl describe pod coredns-fb8b8dccf-hn8ft -n kube-system                          
Name:               coredns-fb8b8dccf-hn8ft
Namespace:          kube-system
Priority:           2000000000
PriorityClassName:  system-cluster-critical
Node:               minikube/10.12.194.50
Start Time:         Fri, 10 May 2019 16:16:10 +0800
Labels:             k8s-app=kube-dns
                    pod-template-hash=fb8b8dccf
Annotations:        <none>
Status:             Running
IP:                 172.17.0.5
Controlled By:      ReplicaSet/coredns-fb8b8dccf
Containers:
  coredns:
    Container ID:  docker://1771f6668316e325dc4ea173964a6fe56714ee90c6e11e31e5c11c9441875182
    Image:         k8s.gcr.io/coredns:1.3.1
    Image ID:      docker-pullable://k8s.gcr.io/coredns@sha256:02382353821b12c21b062c59184e227e001079bb13ebd01f9d3270ba0fcbf1e4
    Ports:         53/UDP, 53/TCP, 9153/TCP
    Host Ports:    0/UDP, 0/TCP, 0/TCP
    Args:
      -conf
      /etc/coredns/Corefile
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 10 May 2019 16:16:30 +0800
      Finished:     Fri, 10 May 2019 16:16:31 +0800
    Ready:          False
    Restart Count:  2
    Limits:
      memory:  170Mi
    Requests:
      cpu:        100m
      memory:     70Mi
    Liveness:     http-get http://:8080/health delay=60s timeout=5s period=10s #success=1 #failure=5
    Readiness:    http-get http://:8080/health delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /etc/coredns from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from coredns-token-lfhbr (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      coredns
    Optional:  false
  coredns-token-lfhbr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  coredns-token-lfhbr
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  beta.kubernetes.io/os=linux
Tolerations:     CriticalAddonsOnly
                 node-role.kubernetes.io/master:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  40s                default-scheduler  Successfully assigned kube-system/coredns-fb8b8dccf-hn8ft to minikube
  Normal   Pulled     20s (x3 over 39s)  kubelet, minikube  Container image "k8s.gcr.io/coredns:1.3.1" already present on machine
  Normal   Created    20s (x3 over 39s)  kubelet, minikube  Created container coredns
  Normal   Started    20s (x3 over 39s)  kubelet, minikube  Started container coredns
  Warning  BackOff    12s (x5 over 37s)  kubelet, minikube  Back-off restarting failed container

```

**Comment by champly** [comment]
> @tstromberg
> 我遇到同样的麻烦
> 
> * Ubuntu 19.04
> * Linux champly 5.0.0-13-generic [＃14](https://github.com/kubernetes/minikube/issues/14) -Ubuntu SMP Mon Apr 15 14:59:14 UTC 2019 x86_64 x86_64 x86_64 GNU / Linux
> * 我`sudo minikube start --vm-driver=none`用来开始
> 
> ```shell
> ＃ champly @ champly在〜/ TMP / K8S [十六点16分24秒]
> $ kubectl get pods --all-namespaces                        
> NAMESPACE NAME READY STATUS RESTARTS AGE
> kube-system coredns-fb8b8dccf-hn8ft 0/1 CrashLoopBackOff 1 20s
> kube-system coredns-fb8b8dccf-l4xmp 0/1 CrashLoopBackOff 1 10s
> kube-system etcd-minikube 1/1跑0 49米
> kube-system kube-addon-manager-minikube 1/1运行0 49米
> kube-system kube-apiserver-minikube 1/1跑步0 49米
> kube-system kube-controller-manager-minikube 1/1运行0 49m
> kube-system kube-proxy-9t847 1/1运行0 50米
> kube-system kube-scheduler-minikube 1/1运行0 49米
> kube-system kubernetes-dashboard-79dd6bfc48-zkppc 1/1 Running 4 50m
> kube-system storage-provisioner 1/1运行0 50米
> 
> ＃ champly @ champly在〜/ TMP / K8S [16时16分30秒]
> $ kubectl描述pod coredns-fb8b8dccf-hn8ft -n kube-system                          
> 名称：coredns-fb8b8dccf-hn8ft
> 命名空间：kube-system
> 优先级：2000000000
> PriorityClassName：系统群集关键
> 节点：minikube / 10.12.194.50
> 开始时间：2019年5月10日星期五16:16:10 +0800
> 标签：k8s-app = kube-dns
>                     荚模板哈希= fb8b8dccf
> 注释：         <无>
> 状态：正在运行
> IP：172.17.0.5
> 受控制：ReplicaSet / coredns-fb8b8dccf
> 集装箱：
>   coredns：
>     货柜编号：docker：// 1771f6668316e325dc4ea173964a6fe56714ee90c6e11e31e5c11c9441875182
>     图片：k8s.gcr.io/coredns:1.3.1
>     图片ID：docker-pullable：//k8s.gcr.io/coredns@sha256：02382353821b12c21b062c59184e227e001079bb13ebd01f9d3270ba0fcbf1e4
>     端口：53 / UDP，53 / TCP，9153 / TCP
>     主机端口：0 / UDP，0 / TCP，0 / TCP
>     ARGS：
>       -conf
>       的/ etc / coredns / COREFILE
>     州：等待
>       原因：CrashLoopBackOff
>     最后状态：终止
>       原因：错误
>       退出代码：1
>       开始于：2019年5月10日星期五16:16:30 +0800
>       完成时间：星期五，2019年5月10日16:16:31 +0800
>     准备好了：错了
>     重启次数：2
>     限制：
>       记忆：170Mi
>     要求：
>       cpu：100米
>       记忆：70Mi
>     活力：http-get http：//：8080 / health delay = 60s timeout = 5s period = 10s ＃ success = 1＃failure = 5 
>     准备就绪：http-get http：//：8080 / health delay = 0s timeout = 1s period = 10s ＃ success = 1＃failure = 3 
>     环境：   <无>
>     坐骑：
>       来自config-volume（ro）的/ etc / coredns
>       来自coredns-token-lfhbr（ro）的/var/run/secrets/kubernetes.io/serviceaccount
> 条件：
>   输入状态
>   初始化为True 
>   准备好了 
>   ContainersReady False 
>   PodScheduled True 
> 卷：
>   配置卷：
>     键入：ConfigMap（由ConfigMap填充的卷）
>     名称：coredns
>     可选：   false
>   coredns-令牌lfhbr：
>     类型：秘密（由秘密填充的卷）
>     SecretName：coredns-token-lfhbr
>     可选：     false
> QoS等级：Burstable
> 节点选择器：beta.kubernetes.io/os=linux
> 容忍度：CriticalAddonsOnly
>                  node-role.kubernetes.io/master:NoSchedule
>                  node.kubernetes.io/not-ready:NoExecute 为 300S
>                  node.kubernetes.io/unreachable:NoExecute 为 300S
> 事件：
>   从消息中键入Reason Age
>   ---- ------ ---- ---- -------
>   正常计划40秒默认计划程序已成功将kube-system / coredns-fb8b8dccf-hn8ft分配给minikube
>   正常拉动20s（x3超过39s）kubelet，minikube集装箱图像“ k8s.gcr.io/coredns:1.3.1 ”已存在于机器上
>   正常创建20s（x3超过39s）kubelet，minikube创建容器coredns
>   正常开始20s（x3超过39s）kubelet，minikube开始容器coredns
>   警告BackOff 12s（x5超过37秒）kubelet，minikube Back-off重启失败的容器
> ```
@tstromberg 
[ #3511](https://github.com/kubernetes/minikube/issues/3511#issuecomment-461664952)已经解决了我的问题

**Comment by champly** [comment]
i meet the same trouble, i use this to resolve
[ #3511]( https://github.com/kubernetes/minikube/issues/3511#issuecomment-461664952)

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by conanswp** [comment]
I meet the same trouble. After update docker from docker-ensgine to docker-ce and use command `minikube --driver=none start --extra-config=kubelet.resolv-conf=/etc/resolv.conf` solve this problem.
