### ISSUE TITLE
We support Virtualbox starting with version 5. Your VirtualBox install is ""

### ISSUE THREAD

**Issue by Jonathan-7** [kubernetes/minikube#4099]
Whenever I run minikube start I get the following error:
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "". Please upgrade at https://www.virtualbox.org

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

I'm using Virtualbox 6.0.4 and minikube  v1.0.0 on Windows 10
I've tried running normal and elevated cmd and powershell prompts, vboxmanage is in the path

**Comment by afbjorklund** [comment]
It is trying to run `VBoxManage --version`. For some reason it returns nothing, without an error.

When you run the command, what does it output ? Where is it is located, i.e. where in the paths

**Comment by Jonathan-7** [comment]
here is the output @afbjorklund 
PS C:\Users\username> Get-Command vboxmanage

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Application     VBoxManage.exe                                     6.0.4.2... C:\Program Files\Oracle\VirtualBox\VBo...


PS C:\Users\username> vboxmanage --version
6.0.4r128413
PS C:\Users\username> minikube start
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "". Please upgrade at https://www.virtualbox.org

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by Jonathan-7** [comment]
@afbjorklund 
the full path is C:\Program Files\Oracle\VirtualBox\VBoxManage.exe
![image](https://user-images.githubusercontent.com/19592133/56161292-12306880-5fc1-11e9-98c4-451103ddb7e7.png)

**Comment by afbjorklund** [comment]
Seems related to https://github.com/docker/machine/issues/4559

**Comment by tstromberg** [comment]
If someone runs into this, I'd be curious about the output of:

`minikube start --alsologtostderr -v=8`

**Comment by medyagh** [comment]
there hasn't been any evidence that we still have this issue. closing . please reopen if not solved.

**Comment by tgonda-discovery** [comment]
`I1210 11:19:35.277801    4308 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
I1210 11:19:35.381057    4308 main.go:110] libmachine: STDOUT:
{
}
I1210 11:19:35.381057    4308 main.go:110] libmachine: STDERR:
{
}
* Retriable failure: create: precreate: We support Virtualb`
