### ISSUE TITLE
Fetch Kubernetes images using tag@hash rather to prevent invalid downloads

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4104]
Currently, if a user uses --image-repository, they may end up with images that do not match the official Kubernetes ones.

We should use digests or some other mechanism to prevent mirror poisoning.

**Comment by tstromberg** [comment]
kubeadm evidently supports tag@hash fetches. We should consider using this for *all* image pulls.

**Comment by medyagh** [comment]
this should be an easy add, I would be happy to review any PR that does this

**Comment by prasadkatti** [comment]
While this would prevent mirror poisoning, it would also prevent people from experimenting with custom images (ref. #8421). Since most people use minikube as a dev environment, if we implement this we might want to provide users to ability to opt out.
