### ISSUE TITLE
The link to the issues is wrong

### ISSUE THREAD

**Issue by silvionetto** [kubernetes/minikube#4106]
minikube start

!   Unable to start VM
X   Error:         [NON_C_DRIVE] create: creating: open /minikube/.minikube/cach
e/iso/minikube-v1.0.0.iso: The system cannot find the path specified.
i   Advice:        Run minikube from the C: drive.
-   Related issues:
    - https://github.com/kubernetes/minikube/issue/1574

*   If the above advice does not help, please let us know:
-   https://github.com/kubernetes/minikube/issues/new

The error is in the URL should be "issues" instead of "issue"

Windows 7

**Comment by afbjorklund** [comment]
Duplicate, #4077

It will be fixed in 1.0.1
