### ISSUE TITLE
Staring minikube with virtual box on Mojave fails with 0x80004005

### ISSUE THREAD

**Issue by domschoen** [kubernetes/minikube#4107]

**Comment by domschoen** [comment]
Here the details of the configuration:
- Mac Mini 2018
- OSX: mac OS Mojave 10.14.4
- VirtualBox: 6.0.6 - 130049- OSX
I tried some of the suggested solutions like reinstalling Virtual Box etc but nothing work. That's way I have created a new issued because it may be specific to my configuration

**Comment by tstromberg** [comment]
Thanks for the bug report! Do you mind providing the output of:

`minikube start --alsologtostderr -v=8`

This seems to be a rather general error code with many possibilities:

- https://apple.stackexchange.com/questions/323960/virtualbox-ns-error-failure-0x80004005-mac
- https://forums.virtualbox.org/viewtopic.php?f=8&t=90147
- https://stackoverflow.com/questions/52689672/virtualbox-ns-error-failure-0x80004005-macos
- https://apple.stackexchange.com/questions/343705/virtualbox-app-would-no-longer-runs

The general gist appears that something, either MacOS or Symantec, is preventing VirtualBox from opening. Could you uninstall VirtualBox, then install it again, and then go to "System Preferences -> Security & Privacy -> General" and ensure that it does not say "Some system software was blocked from loading"? See the image here: https://apple.stackexchange.com/questions/343705/virtualbox-app-would-no-longer-runs

This seems entirely fixable, but if it isn't, there is also the hyperkit VM driver we could use. Thank you!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by ecourtial** [comment]
For me the issue was coming from a bad update of VirtualBox on Ubuntu. The driver was too old despite the VB update.
I had to remove virtual box and virtualbox-dkms and reinstall virtual box.

**Comment by Mohitduklan** [comment]
Worked just by reinstalling virtualbox using cli
