### ISSUE TITLE
 sudo eval $(minikube docker-env): config.json: permission denied

### ISSUE THREAD

**Issue by venkatsurabhi** [kubernetes/minikube#4108]
I am not able to run : sudo eval $(minikube docker-env)  in my local machine 
Error: /home/username/.minikube/machines/minikube/config.json: permission denied
OS: Ubuntu 16.04

**Comment by tstromberg** [comment]
This seems like a permissions issue. What happens if you run:

`sudo file /home/username/.minikube/machines/minikube/config.json`

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
