### ISSUE TITLE
LoadBalancer Service has pending IP address

### ISSUE THREAD

**Issue by Industrial** [kubernetes/minikube#4113]
Hi!

I have read https://github.com/kubernetes/minikube/issues/2834 but that does not solve my issue:

When I run `kubectl expose deployment test-deployment-nginx --type=LoadBalancer --name=nginx-example`

and then look at the services with `kubectl get svc` then:

```
NAME            TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
kubernetes      ClusterIP      10.96.0.1     <none>        443/TCP        23h
nginx-example   LoadBalancer   10.96.11.32   <pending>     80:31378/TCP   3h10m
```

You can see it does not get an external IP.

For this reason the `minikube service nginx-example` does not work. I get a connection error.

**Comment by dvdmuckle** [comment]
`minikube` does not come with anything that can spin up a service type of `LoadBalancer`. You can install something like `metallb` to enable this. https://metallb.universe.tf/tutorial/minikube/

**Comment by afbjorklund** [comment]
@dvdmuckle : `minikube tunnel` does provide a LoadBalancer, but for some reason it's not working here

**Comment by tstromberg** [comment]
@Industrial - What happens when you run `minikube tunnel`?

**Comment by tstromberg** [comment]
Also, do you mind providing the full output of `minikube service nginx-example` - you mentioned it returns a connection error.

**Comment by tstromberg** [comment]
@balopat - Mind chiming in here? Is <pending> the normal state for a service until the tunnel is started?

**Comment by Industrial** [comment]
The solution is to use `minikube tunnel`. This was not apparent for me following guide, docs, etc, up to the point of making the ticket.

**Comment by BenedictAdamson** [comment]
> `minikube` does not come with anything that can spin up a service type of `LoadBalancer`.

And I guess even doing `minikube addons enable ingress` does not spin up that service, either (?)

**Comment by abdabughazaleh** [comment]
First of all, make sure from the listening port in your application and what port are you set when writing the command after that execute the `minikube tunnel` command.
