### ISSUE TITLE
[VBOX_NOT_FOUND] create: precreate: VBoxManage not found

### ISSUE THREAD

**Issue by kevinsingapore** [kubernetes/minikube#4117]
envirorment: kvm manchine
os : centos7.5
when use "./minikube start", errors as follows:

`o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
 142.88 MB / 142.88 MB [============================================] 100.00% 0s

!   Unable to start VM
X   Error:         [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
i   Advice:        Install VirtualBox, ensure that VBoxManage is executable and in path, or select an alternative value for --vm-driver
-   Documentation: https://www.virtualbox.org/wiki/Downloads
-   Related issues:
    - https://github.com/kubernetes/minikube/issue/3784
    - https://github.com/kubernetes/minikube/issue/3776

*   If the above advice does not help, please let us know: 
-   https://github.com/kubernetes/minikube/issues/new`

i want to get some help, how to deal with it?

**Comment by hpandeycodeit** [comment]
@kevinsingapore looks like you are missing config.json file from your docker installation. Try Reinstalling the docker and then run the minikube again.

**Comment by perrywang** [comment]
> envirorment: kvm manchine
> os : centos7.5
> when use "./minikube start", errors as follows:
> 
> `o minikube v1.0.0 on linux (amd64)
> $ Downloading Kubernetes v1.14.0 images in the background ...
> 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> 
> > Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
> > @   Downloading Minikube ISO ...
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 2019/04/19 00:59:30 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
> > 2019/04/19 00:59:30 No matching credentials were found, falling back on anonymous
> > 142.88 MB / 142.88 MB [============================================] 100.00% 0s
> 
> ! Unable to start VM
> X Error: [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
> i Advice: Install VirtualBox, ensure that VBoxManage is executable and in path, or select an alternative value for --vm-driver
> 
> * Documentation: https://www.virtualbox.org/wiki/Downloads
> * Related issues:
>   
>   * https://github.com/kubernetes/minikube/issue/3784
>   * https://github.com/kubernetes/minikube/issue/3776
> 
> * If the above advice does not help, please let us know:
> 
> * [https://github.com/kubernetes/minikube/issues/new`](https://github.com/kubernetes/minikube/issues/new%60)
> 
> i want to get some help, how to deal with it?  

on linux you don't need to use default virtualbox driver. You can use kvm2 or none driver types. 
https://github.com/kubernetes/minikube/blob/master/docs/drivers.md
https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md
if you using none driver maybe you need install docker.

**Comment by tstromberg** [comment]
@kevinsingapore - Please install Virtualbox, which is what the "advice" section is trying to convey. Do you have a recommendation on how I could improve the error message?
