### ISSUE TITLE
Unable to start VM: create: precreate

### ISSUE THREAD

**Issue by ZHAOSUJI** [kubernetes/minikube#4120]

**Comment by viralkasundra** [comment]
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

**Comment by tstromberg** [comment]
@ZHAOSUJI - Thank you for sharing your experience! If you don't mind, could you please add:

*  The exact command-lines used so that we can replicate the issue
*  The full output of the command that failed
*  Which operating system version was used

Thank you!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
