### ISSUE TITLE
Document which versions of Kubernetes are supported by minikube

### ISSUE THREAD

**Issue by yinzara** [kubernetes/minikube#4121]
Because `minikube get-k8s-versions` was removed with 0.30.0, issue #1201 should be reopened.

**Comment by tstromberg** [comment]
All supported release of Kubernetes can be used. There is no specific version list.

That said, there is room for us to document this.

**Comment by tstromberg** [comment]
We've documented it: https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md#selecting-a-kubernetes-version

**Comment by sbuvaneshkumar** [comment]
> We've documented it: https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md#selecting-a-kubernetes-version

This link seems to be outdated and no more available.

**Comment by tstromberg** [comment]
See: https://minikube.sigs.k8s.io/docs/handbook/config/#selecting-a-kubernetes-version
