### ISSUE TITLE
service hello-world: services "hello-world" not found

### ISSUE THREAD

**Issue by stream2stream** [kubernetes/minikube#4125]
HI Guys

We are learning kubernetes by running through the online tutorial https://kubernetes.io/docs/tutorials/hello-minikube/.  We've been using the Windows 10 version.  All works well except for the command kubectl service <service name>, the exact command being kubectl service hello-world.  

Whenever we run this command we get the following error
<see attached file>
![image](https://user-images.githubusercontent.com/13823717/56470899-ad06c800-6443-11e9-921b-903b809d947e.png)

Any help would be useful

Thanks  Sel

**Comment by tstromberg** [comment]
Hey @stream2stream!

First, my apologies for the error message here. It isn't very useful. It's basically saying that the pod didn't schedule. Do you mind providing the output of:

- `kubectl get services`
- `kubectl get pods`
- `kubectl describe pod <name of hello-node name shown in the previous line>`

Thanks!

**Comment by stream2stream** [comment]
Hi Thomas

Thanks for the response, the outputs as requested are as follows
- kubectl get services
![image](https://user-images.githubusercontent.com/13823717/56595699-03603c00-65e7-11e9-8b12-53d87f1858d7.png)

-kubectl get pods
![image](https://user-images.githubusercontent.com/13823717/56595752-238ffb00-65e7-11e9-80b6-af9ac8c0de8a.png)

- kubectl describe pod <pod name>
See file attached
[kubectl-describe-pob-hello-node-78cd77d68f-bvgnl.txt](https://github.com/kubernetes/minikube/files/3108410/kubectl-describe-pob-hello-node-78cd77d68f-bvgnl.txt)

Thanks

Sel

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
