### ISSUE TITLE
reuse vbox: "minikube start" failed at "Waiting for pods: apiserver" (timeout finally)

### ISSUE THREAD

**Issue by DY-Ong** [kubernetes/minikube#4127]
Environment: macOS Mojave 10.14.4, VirtualBox 6.0.6

$ minikube start
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver
💣  Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objects passed to apply
    error: no objects passed to apply
    error: no objects passed to apply

**Comment by jaruizes** [comment]
Same issue for me. 

I'm behind a proxy but I'm setting proxy options in "minkube start" as [documentation says](https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md):

`minikube start --docker-env HTTP_PROXY=${http_proxy} --docker-env HTTPS_PROXY=${http_proxy} --docker-env NO_PROXY=localhost,127.0.0.1,192.168.99.0/24,192.168.39.0/24`

**Comment by jaruizes** [comment]
Solved adding minikube ip to "no_proxy" environment variable, not in "docker-env". That means:

`export NO_PROXY=localhost,127.0.0.1,192.168.99.0/24,192.168.39.0/24
minikube start`

**Comment by tstromberg** [comment]
@DY-Ong - If you run `minikube delete` and then 'minikube start', does this happen again?

If so, can you attach the output of `minikube logs`? Thanks!

@jaruizes - I've opened #4130 to handle this case. Thanks for mentioning it!

**Comment by DY-Ong** [comment]
Thank you all so much.

Yesterday I re-installed my "Docker for Mac" because of some other problems. Today I reissued the "minikube start"  command to see what will happen before I do some rescue actions as suggested. Magically it works ! 

I did nothing but only re-installed my Docker.
The messages shown in terminal screen were:
===========================
$ minikube start
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
📯  Updating kube-proxy configuration ...
🤔  Verifying component health ......
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
================================= (end of message) ======

**Comment by jingyahu** [comment]
Thanks a lot. I had the same issue in MacOS. 
Update docker to the latest version do help to solve the issue.
