### ISSUE TITLE
hyperkit: MINIKUBE_PROFILE environment variable is not working

### ISSUE THREAD

**Issue by perrywang** [kubernetes/minikube#4135]
**Problem**
following doc https://github.com/kubernetes/minikube/blob/master/docs/env_vars.md
`minikube supports passing environment variables instead of flags for every value listed in minikube config list`
The environment variable `export MINIKUBE_PROFILE=xxx` should has same result like --profile=xxx arg. 
Currently only --profile is working and MINIKUBE_PROFILE variable ignored. And also even --profile still has a small error output like below after `minikube start --profile=xxx` successfully
`💣  Error getting host: Machine does not exist for api.Exists(minikube)`
All the things work fine with virtualbox driver.
**Environment**
macOS Mojave + minikube 1.0.0

**Comment by RA489** [comment]
```
root@openstack-nti-6:/home/ubuntu# MINIKUBE_ENABLE_PROFILING=1 minikube start
2019/05/06 09:23:04 profile: trace enabled, /tmp/profile803220605/trace.out
😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.108
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
📯  Updating kube-proxy configuration ...
🤔  Verifying component health ......
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
2019/05/06 09:26:05 profile: trace disabled, /tmp/profile803220605/trace.out

```

**Comment by dpandhi-git** [comment]
Started testing this issue both works fine for me, @perrywang can you add more details I would like to work on this

`[dpandhi ~]$  MINIKUBE_PROFILE=intg-test minikube start
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🏃  Re-using the currently running virtualbox VM for "intg-test" ...
⌛  Waiting for SSH access ...
📶  "intg-test" IP address is 192.168.99.106
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
📯  Updating kube-proxy configuration ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "intg-test"
🏄  Done! Thank you for using minikube!
[dpandhi ~]$  minikube version
minikube version: v1.0.1
[dpandhi ~]$  minikube stop
✋  Stopping "minikube" in virtualbox ...
🛑  "minikube" stopped.
[dpandhi ~]$  minikube start --profile=intg-test
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🏃  Re-using the currently running virtualbox VM for "intg-test" ...
⌛  Waiting for SSH access ...
📶  "intg-test" IP address is 192.168.99.106
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
📯  Updating kube-proxy configuration ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "intg-test"
🏄  Done! Thank you for using minikube!`

**Comment by perrywang** [comment]
closing it for my mistake.  I am using sudo to execute but lost -E option to reserve environment variables
