### ISSUE TITLE
How to pass --cloud-provider=aws into minikube?

### ISSUE THREAD

**Issue by ponprathip** [kubernetes/minikube#4138]
Whether minikube can be started with cloud-provider as aws ? i.e whether we can start kubelet that is packaged with minikube with --cloud-provider=aws flag?

**Comment by afbjorklund** [comment]
It is intended to be run locally, there are a lot of other options to run on cloud providers...

Probably should work using the "none" provider, but it is not very well documented.

**Comment by tstromberg** [comment]
Just curious - what are you trying to accomplish?

I don't know if it will work, but I believe this option can be passed in using `--extra-config` argument, though I'm not really sure what to pass in exactly. https://blog.scottlowe.org/2018/09/28/setting-up-the-kubernetes-aws-cloud-provider/ seemed to have some guidance on what it looks like in the configuration file.

Reading `pkg/minikube/bootstrapper/kubeadm/templates.go` might help you to figure out how to map this into the minikube system. Thanks!

**Comment by ponprathip** [comment]
Thanks @afbjorklund @tstromberg . Will try the option suggested and get back
I am trying to remove the aws ecs based orchestration with k8s orchestration leveraging other aws feature which our system uses

**Comment by vinicyusmacedo** [comment]
I tried `--extra-config` here, in my case I'm testing GCE.

`minikube start --extra-config=apiServer.cloud-provider=gce --extra-config=controllerManager.cloud-provider=gce` 
This one didn't work, yielding this error:

```
E0511 19:27:47.269120   18361 start.go:258] Error updating cluster:  generating kubeadm cfg: generating extra component config for kubeadm: Unknown component map[apiserver:apiServerExtraArgs controller-manager:controllerManagerExtraArgs scheduler:schedulerExtraArgs kubelet:].  Valid components and kubeadm config are map[controller-manager:controllerManagerExtraArgs scheduler:schedulerExtraArgs kubelet: apiserver:apiServerExtraArgs]
```

This one worked:

`minikube start --extra-config=apiserver.cloud-provider=gce --extra-config=controller-manager.cloud-provider=gce` (notice that `apiserver` is not camelCase and `controller-manager` is separated by a dash).

**Comment by tstromberg** [comment]
Thank you @vinicyusmacedo !
