### ISSUE TITLE
Directories not persisted across reboots

### ISSUE THREAD

**Issue by Nalum** [kubernetes/minikube#414]
I've got mongodb running on minikube but when I `minikube stop` and then `minikube start` all the data that was in mongodb is lost. I have the pod mounting a host volume located at `/data/mdb`. The same thing is happening with elasticsearch.

I am opening this issue at the request of @dlorenc on the slack channel.

**Comment by jimmidyson** [comment]
Only dirs under /mnt/sda1 will persist. You can either change your hostPath declaration or symink /data to /mnt/sda1/data perhaps?

**Comment by dlorenc** [comment]
Yeah, we should probably create a simple to use persisted directory (maybe /data?), and document it. Any opinions on which to use?

**Comment by jimmidyson** [comment]
Host paths are discouraged in general. Wonder if we can set up a persistent volume (even if that is a hostPath PV) via minikube to make this a bit more transparent to users?

**Comment by Nalum** [comment]
Thanks. I just found this discussion about pv and pvc: https://github.com/kubernetes/minikube/issues/2

**Comment by Nalum** [comment]
@jimmidyson @dlorenc: Is `/mnt/sda1` mounted from the host system onto the cluster vm?

**Comment by dlorenc** [comment]
No, it's just a disk that is persisted across "minikube stop" commands, but not "minikube delete". On some systems "/Users" is automatically mounted in from the host, but not everywhere yet. We're making that more consistent before documenting it.
