### ISSUE TITLE
mac/vbox: Get https://k8s.gcr.io/v2/: read udp [::1]:51732->[::1]:53: read: connection refused

### ISSUE THREAD

**Issue by Th3G4mbl3r** [kubernetes/minikube#4140]
-- The exact command-lines used so that we can replicate the issue --
minikube start

--    *  The full output of the command that failed --

😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
E0423 23:42:43.473498   16537 start.go:209] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/Th3G4mbl3r/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13: fetching remote image: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on [::1]:53: read udp [::1]:51732->[::1]:53: read: connection refused
✨  Preparing Kubernetes environment ...
❌  Unable to load cached images: loading cached images: loading image /Users/Th3G4mbl3r/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.14.0: stat /Users/Th3G4mbl3r/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.14.0: no such file or directory
💾  Downloading kubeadm v1.14.0
💾  Downloading kubelet v1.14.0

💣  Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.14.0: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubeadm: dial tcp: lookup storage.googleapis.com on [::1]:53: read udp [::1]:55087->[::1]:53: read: connection refused
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubeadm: dial tcp: lookup storage.googleapis.com on [::1]:53: read udp [::1]:52126->[::1]:53: read: connection refused
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubeadm: dial tcp: lookup storage.googleapis.com on [::1]:53: read udp [::1]:57870->[::1]:53: read: connection refused
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubeadm: dial tcp: lookup storage.googleapis.com on [::1]:53: read udp [::1]:51749->[::1]:53: read: connection refused
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.0/bin/linux/amd64/kubeadm: dial tcp: lookup storage.googleapis.com on [::1]:53: read udp [::1]:62435->[::1]:53: read: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

--    *  Which operating system version was used --

Mac OS v10.14.4

-- Possible issue description and diagnosis --

Looking at the error messages, i can see that the error is happening because minikube is trying to work on ipv6 interfaces while it should be working using ipv4 interface. This was the default behavior in v0.35 and it was all working until i upgrade to minikube v1.0.

**Comment by Th3G4mbl3r** [comment]
Output of ifconfig:

lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> mtu 16384
        options=1203<RXCSUM,TXCSUM,TXSTATUS,SW_TIMESTAMP>
        inet 127.0.0.1 netmask 0xff000000
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x1
        inet 127.94.0.1 netmask 0xff000000
        inet 127.94.0.2 netmask 0xff000000
        nd6 options=201<PERFORMNUD,DAD>
gif0: flags=8010<POINTOPOINT,MULTICAST> mtu 1280
stf0: flags=0<> mtu 1280
XHC0: flags=0<> mtu 0
XHC20: flags=0<> mtu 0
XHC1: flags=0<> mtu 0
en10: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ether ac:de:48:00:11:22
        inet6 fe80::aede:48ff:fe00:1122%en10 prefixlen 64 scopeid 0x7
        nd6 options=201<PERFORMNUD,DAD>
        media: autoselect
        status: active
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ether 78:4f:43:5e:a7:6b
        inet 10.10.200.3 netmask 0xff000000 broadcast 10.255.255.255
        media: autoselect
        status: active
p2p0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 2304
        ether 0a:4f:43:5e:a7:6b
        media: autoselect
        status: inactive
awdl0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1484
        ether fe:20:0d:38:63:5b
        inet6 fe80::fc20:dff:fe38:635b%awdl0 prefixlen 64 scopeid 0xa
        nd6 options=201<PERFORMNUD,DAD>
        media: autoselect
        status: active
en4: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
        options=60<TSO4,TSO6>
        ether d2:00:6c:49:37:05
        media: autoselect <full-duplex>
        status: inactive
en2: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
        options=60<TSO4,TSO6>
        ether d2:00:6c:49:37:04
        media: autoselect <full-duplex>
        status: inactive
en3: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
        options=60<TSO4,TSO6>
        ether d2:00:6c:49:37:01
        media: autoselect <full-duplex>
        status: inactive
en1: flags=8963<UP,BROADCAST,SMART,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
        options=60<TSO4,TSO6>
        ether d2:00:6c:49:37:00
        media: autoselect <full-duplex>
        status: inactive
wc6: flags=863<UP,BROADCAST,SMART,RUNNING,SIMPLEX> mtu 1500
        ether 00:02:55:11:19:76
        inet 169.254.169.171 netmask 0xffff0000 broadcast 169.254.255.255
        media: 1000baseT (<unknown type>)
bridge0: flags=8822<BROADCAST,SMART,SIMPLEX,MULTICAST> mtu 1500
        options=63<RXCSUM,TXCSUM,TSO4,TSO6>
        ether d2:00:6c:49:37:00
        Configuration:
                id 0:0:0:0:0:0 priority 0 hellotime 0 fwddelay 0
                maxage 0 holdcnt 0 proto stp maxaddr 100 timeout 1200
                root id 0:0:0:0:0:0 priority 0 ifcost 0 port 0
                ipfilter disabled flags 0x2
        member: en1 flags=3<LEARNING,DISCOVER>
                ifmaxaddr 0 port 14 priority 0 path cost 0
        member: en2 flags=3<LEARNING,DISCOVER>
                ifmaxaddr 0 port 12 priority 0 path cost 0
        member: en3 flags=3<LEARNING,DISCOVER>
                ifmaxaddr 0 port 13 priority 0 path cost 0
        member: en4 flags=3<LEARNING,DISCOVER>
                ifmaxaddr 0 port 11 priority 0 path cost 0
        media: <unknown type>
        status: inactive
utun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 2000
        inet6 fe80::1693:631f:7ef8:2ed7%utun0 prefixlen 64 scopeid 0x11
        nd6 options=201<PERFORMNUD,DAD>
vboxnet0: flags=8842<BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
        ether 0a:00:27:00:00:00

Based on this, it is trying to perform dns resolution using localhost interface lo0 ipv6 address.

**Comment by Th3G4mbl3r** [comment]
If it helps, my virtualbox version is Version 6.0.6 r130049 (Qt5.6.3). And even removing the existing v0.35. profile away and getting minikube to start a new one does not work. same problem

**Comment by Th3G4mbl3r** [comment]
Based on the error, the problem is that it is looking for a  DNS server at ::1:53 for name resolution. But that is my loopback interface on my mac. Any suggestion on how to ensure minikube uses the right DNS server configured on the laptop. And my DNS resolution is working fine as is internet connectivity. Tested it by going to those URLs using curl and it worked properly.

**Comment by tstromberg** [comment]
Any chance you are running from China or a network that does not have access to Google? If so, it may be possible to use --image-repository. 

You can confirm DNS resolution of the Google Container Registry using:

`host k8s.gcr.io`

**Comment by Th3G4mbl3r** [comment]
No, i am running from Singapore. And the DNS resolution works. As i said i am able to use curl to query the exact download endpoint and actually download the file from the same command window. The problem is that for some reason minikube is trying to use IPv6 and reaching out ::1:53 which is not a valid DNS server and therefore no connection can be made to that port. ::1 is my loopback interface on mac.

Output of ping command:

➜ “ “ping k8s.gcr.io
PING googlecode.l.googleusercontent.com (74.125.130.82): 56 data bytes
64 bytes from 74.125.130.82: icmp_seq=0 ttl=47 time=6.304 ms
64 bytes from 74.125.130.82: icmp_seq=1 ttl=47 time=3.247 ms
64 bytes from 74.125.130.82: icmp_seq=2 ttl=47 time=4.010 ms
64 bytes from 74.125.130.82: icmp_seq=3 ttl=47 time=4.477 ms
^C
--- googlecode.l.googleusercontent.com ping statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 3.247/4.510/6.304/1.125 ms

**Comment by Th3G4mbl3r** [comment]
Figured out the issue. On macos Mojave, for some reason my /etc/resolv.conf file was deleted off by the last OS update. And so the name resolution would not work for minikube. 

I manually created to make this work for now.

But on Mac OS, use of /etc/resolv.conf is not recommended. Instead we should be using the MAC OS name resolution process which uses /etc/resolver instead.

**Comment by Th3G4mbl3r** [comment]
@tstromberg is the above information sufficient? As i said boils down to how DNS resolution should be attempted in macos. We should be using the native mechanism instead of /etc/resolv.conf.

**Comment by Th3G4mbl3r** [comment]
@tstromberg please let me know what addition information is needed for the triage.

**Comment by tstromberg** [comment]
Interesting. minikube actually doesn't have any control over which resolver library it uses - it's up to Go.

Here's a related bug: https://github.com/golang/go/issues/12524

I'm not sure there is anything we can do with this configuration quirk. It is admittedly quite esoteric. I'll at least make sure it gets included in the solutions database though. Thanks for the bug report!
