### ISSUE TITLE
KUBECONFIG environment variable leads to error: Kubeconfig does not have a record of the machine cluster

### ISSUE THREAD

**Issue by ulrichmeyer** [kubernetes/minikube#4145]
root@debian:~# kubectl config current-context 
minikube
root@debian:~# kubectl config view 
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://xxxxxxxx
  name: gke_xxxxxxxxxxx_europe-west3-a_kubia
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://xxxxxxxxx
  name: gke_xxxxxxxxx_europe-west3-a_kubtra
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://xxxxxxxxx
  name: kubernetes
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    server: https://10.0.2.15:8443
  name: minikube
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://xxxxxxxxxx
  name: myfm_dhc_int
- cluster:
    certificate-authority-data: DATA+OMITTED
    server: https://xxxxxxxxxx
  name: myfm_dhc_prod
contexts:
- context:
    cluster: kubernetes
    namespace: butis-int
    user: admin
  name: butis-integration
- context:
    cluster: kubernetes
    namespace: butis-prod
    user: admin
  name: butis-production
- context:
    cluster: gke_xxxxxxx_europe-west3-a_kubia
    user: gke_xxxxxxxxx_europe-west3-a_kubia
  name: gke_xxxxxxxx_europe-west3-a_kubia
- context:
    cluster: gke_xxxxxxxxx_europe-west3-a_kubtra
    user: gke_xxxxxxxxxx_europe-west3-a_kubtra
  name: gke_xxxxxxxxx_europe-west3-a_kubtra
- context:
    cluster: minikube
    namespace: myfm
    user: minikube
  name: minikube
- context:
    cluster: minikube
    namespace: myfm
    user: minikube
  name: myfm_development
- context:
    cluster: myfm_dhc_int
    namespace: myfm
    user: myfm_admin_int
  name: myfm_integration
- context:
    cluster: myfm_dhc_prod
    namespace: myfm
    user: myfm_admin_prod
  name: myfm_production
current-context: minikube
kind: Config
preferences: {}
users:
- name: admin
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: gke_xxxxxxxxx_europe-west3-a_kubia
  user:
    auth-provider:
      config:
        access-token:xxxxxxxxxxxxxxx
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\ume\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2019-01-02 17:42:00"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: gke_xxxxxxxxx_europe-west3-a_kubtra
  user:
    auth-provider:
      config:
        access-token: xxxxxxxxxxxx
        cmd-args: config config-helper --format=json
        cmd-path: C:\Users\ume\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin\gcloud.cmd
        expiry: "2019-03-18T18:19:36Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
- name: minikube
  user:
    client-certificate: /root/.minikube/client.crt
    client-key: /root/.minikube/client.key
- name: myfm_admin_int
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
- name: myfm_admin_prod
  user:
    client-certificate-data: REDACTED
    client-key-data: REDACTED
root@debian:~# 

root@debian:~# env | grep KUBECONFIG
KUBECONFIG=:/root/myhost/myhome/.kube/config_dhc:/root/.kube/config

root@debian:~# minikube status
E0424 15:59:21.833202   28744 status.go:110] Error kubeconfig status: Kubeconfig does not have a record of the machine cluster
minikube failed :( exiting with error code -1

root@debian:~# unset KUBECONFIG
root@debian:~# env | grep KUBECONFIG

root@debian:~# kubectl config current-context 
minikube
root@debian:~# kubectl config view 
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    server: https://10.0.2.15:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: myfm
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /root/.minikube/client.crt
    client-key: /root/.minikube/client.key
root@debian:~# 

root@debian:~# minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 10.0.2.15

root@debian:~# cat /root/.kube/config 
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /root/.minikube/ca.crt
    server: https://10.0.2.15:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: myfm
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /root/.minikube/client.crt
    client-key: /root/.minikube/client.key
root@debian:~# 

root@debian:~# minikube status
E0424 16:17:12.351860   21394 status.go:110] Error kubeconfig status: Kubeconfig does not have a record of the machine cluster
minikube failed :( exiting with error code -1

N.A.

debian 9 stretch

**Comment by tstromberg** [comment]
Thanks for the bug report! Does this cause `start` to fail, or just `status`?

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
