### ISSUE TITLE
Suggest removal of old `beta` keyword in storageclass.yaml

### ISSUE THREAD

**Issue by redmcg** [kubernetes/minikube#4148]
This is an issue proposing a pull request (as requested in the Contributing guidelines) - but the PR is pretty simple.

In [storageclass.yaml](https://github.com/kubernetes/minikube/blob/1924610ccc6dbf5f1c701bc23de9cfe4eaada8c8/deploy/addons/storageclass/storageclass.yaml#L7), the `is-default-class` annotation is still using the old `beta` variant:
`    storageclass.beta.kubernetes.io/is-default-class: "true"`

The proposal it to remove the `beta` keyword.

**Comment by tstromberg** [comment]
Sounds great. Please open a PR at your leisure.

**Comment by keramiozsoy** [comment]
Hi I deleted , #4153

**Comment by redmcg** [comment]
I'll close this and follow #4153. Please re-open if the preference is to track via an issue as well as PR.
