### ISSUE TITLE
Windows "kubectl current-context" is not setup properly on "minikube start"

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#415]
When attempting to run `minikube start` on Windows the context is not setup properly for kubectl:
```
PS C:\Users\aprindle\Downloads> .\minikube.exe start
Starting local Kubernetes cluster...
Kubernetes is available at https://192.168.99.100:8443.
Kubectl is now configured to use the cluster.
PS C:\Users\aprindle\Downloads> kubectl.exe get po
Unable to connect to the server: dial tcp 127.0.0.1:8080: ConnectEx tcp: No connection could be made because the target
machine actively refused it.
```

This is because the context is empty after `minikube start`:
```
PS C:\Users\aprindle\Downloads> kubectl config view minikube
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []
```

Kubectl works properly if I then manually update the context.  I will investigate why this might be the case.

**Comment by aaron-prindle** [comment]
Didn't repro, please reopen if you encounter this.

**Comment by wasimbloch** [comment]
I am able to reproduce this issue. Any suggestions?
PS C:\> .\kubectl config view minikube
apiVersion: v1
clusters: []
contexts:
- context:
    cluster: minikube
    user: ""
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users: []

**Comment by PierrickI3** [comment]
Usually, this means that the path to the config file is not set.
To fix this, run `set KUBECONFIG="C:\Users\Administrator\.kube\config"` (change the path accordingly with your username). 
Then run `kubectl config set-context minikube` to set the context.

**Comment by Yan-Ou** [comment]
Unfortunately the kubectl config set-context didn't fix the problem.
