### ISSUE TITLE
Feature Request - unset current-context after minikube stop

### ISSUE THREAD

**Issue by davidmnoriega** [kubernetes/minikube#4154]
Working with multiple kube clusters, it is useful to have the context in my shell prompt, and I can use the `kubectl` command to switch between them. If `minikube start` automatically sets the current context to itself, why not then unset it on `minikube stop`?

**Comment by tstromberg** [comment]
Great idea! I love this idea and would be happy to review any PR which implements it.  Thank you for the suggestion.
