### ISSUE TITLE
Release 0.7.1

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#416]

**Comment by shouhong** [comment]
There is a change for v0.7.1 "Added a insecure-registry flag to minikube start to support insecure docker registries.". Can you please give an example of how to use this "insecure-registry" flag?

**Comment by aaron-prindle** [comment]
The `--insecure-registry` flag is passed through to libmachine when provisioning the VM.  It should act exactly as docker-machine's `--engine-insecure-registry`.  
An example use of the flag would be:
minikube start --insecure-registry <url-to-insecure-registry>
minikube start --insecure-registry registry.myco.com

**Comment by dlorenc** [comment]
This is out, right?

**Comment by aaron-prindle** [comment]
Yes it is:
https://github.com/kubernetes/minikube/releases/tag/v0.7.1
