### ISSUE TITLE
Support buildah

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#4166]
I added a previous ticket about `buildah` (PR #3225), but it timed out...

When we upgrade to Podman 1.2, we should include support for buildah (for building images).
Probably by including `buildah` next to `podman`, especially if "podman build" doesn't work...

It will share the runc and the cni plugins with podman and with cri-o.

No real plan yet on how to support building images from host, except for using `minikube ssh`.
But it will do as a start. Could even run buildah in a container, but then it's hard to share images.

**Comment by afbjorklund** [comment]
Depends on #4181

**Comment by tstromberg** [comment]
Any update?

**Comment by afbjorklund** [comment]
Decided to push official support for BuildKit and Buildah to a later version, but didn't add to 1.5

**Comment by afbjorklund** [comment]
I think it will be enough with `podman build` for now. Can revisit buildah later, if required.
