### ISSUE TITLE
hyperv: waiting for k8s-app=kube-proxy: timed out waiting for the condition

### ISSUE THREAD

**Issue by haiyangxinxin** [kubernetes/minikube#4175]
minikube.exe start

PS C:\WINDOWS\system32> minikube.exe start
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running hyperv VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 10.0.230.123
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.06.2-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.14.0 ...
X   Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.0": output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
: Process exited with status 1
:   Relaunching Kubernetes v1.14.0 using kubeadm ...
:   Waiting for pods: apiserver proxy
!   Error restarting cluster: wait: waiting for k8s-app=kube-proxy: timed out waiting for the condition

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
X   Problems detected in "kube-addon-manager":
    - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
    - error: no objects passed to apply
    - error: no objects passed to apply
PS C:\WINDOWS\system32>
PS C:\WINDOWS\system32>

window10 專業版

otherwise :
failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.0": output: Error response from
 but my minikube vm is include this image:
PS C:\WINDOWS\system32> minikube.exe ssh
                         _             _
            _         _ ( )           ( )
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ docker images
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
nginx                                     latest              27a188018e18        13 days ago         109MB
k8s.gcr.io/kube-proxy                     v1.14.0             5cd54e388aba        5 weeks ago         82.1MB
k8s.gcr.io/kube-scheduler                 v1.14.0             00638a24688b        5 weeks ago         81.6MB
k8s.gcr.io/kube-controller-manager        v1.14.0             b95b1efa0436        5 weeks ago         158MB
k8s.gcr.io/kube-apiserver                 v1.14.0             ecf910f40d6e        5 weeks ago         210MB
k8s.gcr.io/kube-addon-manager             v9.0                119701e77cbc        3 months ago        83.1MB
k8s.gcr.io/coredns                        1.3.1               eb516548c180        3 months ago        40.3MB
k8s.gcr.io/kubernetes-dashboard-amd64     v1.10.1             f9aed6605b81        4 months ago        122MB
k8s.gcr.io/etcd                           3.3.10              2c4adeb21b4f        5 months ago        258MB
k8s.gcr.io/k8s-dns-sidecar-amd64          1.14.13             4b2e93f0133d        7 months ago        42.9MB
k8s.gcr.io/k8s-dns-kube-dns-amd64         1.14.13             55a3c5209c5e        7 months ago        51.2MB
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64    1.14.13             6dc8ef8287d3        7 months ago        41.4MB
k8s.gcr.io/pause                          3.1                 da86e6ba6ca1        16 months ago       742kB
gcr.io/k8s-minikube/storage-provisioner   v1.8.1              4689081edb10        17 months ago       80.8MB
$

**Comment by sharifelgamal** [comment]
Can you attach the output of `minikube logs`?

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube, and if the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!
