### ISSUE TITLE
virtualbox: kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by johnwangemory** [kubernetes/minikube#4179]
I attempted to start minikube on my Mac (10.11.6), I got errors as below

$ minikube start
😄  minikube v1.0.1 on darwin (amd64)
💿  Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
🤹  Downloading Kubernetes v1.14.1 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 1.11.1
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
❌  Unable to load cached images: loading cached images: loading image /Users/myid/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.14.1: transferring cached image: pre-copy: NewSession: ssh: rejected: administratively prohibited (open failed)
💾  Downloading kubeadm v1.14.1
💾  Downloading kubelet v1.14.1
🚜  Pulling images required by Kubernetes v1.14.1 ...
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ... 
⌛  Waiting for pods: apiserver
💣  Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: error when applying patch:
    error: error when applying patch:
    error: error when applying patch:

I appreciate it if I can get help.

**Comment by tstromberg** [comment]
Interesting. Can you attach the output of `minikube logs`?

I suspect you'll be able to work around this issue by using `minikube delete`, but I'm really curious about the ssh issue above as well. Very strange.

**Comment by lbd24** [comment]
Same here, Mac Mojave (10.14.4). Minikube logs output attached. I'm doing beginner's training on lynda, so total n00b here.

$ minikube start
😄  minikube v1.0.1 on darwin (amd64)
💿  Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubelet v1.14.1
💾  Downloading kubeadm v1.14.1
🚜  Pulling images required by Kubernetes v1.14.1 ...
🚀  Launching Kubernetes v1.14.1 using kubeadm ...
⌛  Waiting for pods: apiserver

💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objectWRs N:pa =ss= edError ge ttting defauo ltapply
    error: no objects WRN: passed t== Eo arrpporly
[minikube-logs.txt](https://github.com/kubernetes/minikube/files/3143063/minikube-logs.txt)

**Comment by kj4z** [comment]
Also seeing this behavior on Ubuntu with a clean installation.  "minikube delete" followed by "minikube start" produces the same outcome.

[logs.txt](https://github.com/kubernetes/minikube/files/3153648/logs.txt)

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube and run `minikube delete` to remove the previous cluster state.

If the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!
