### ISSUE TITLE
Replaces current .kube

### ISSUE THREAD

**Issue by dnascimento** [kubernetes/minikube#418]
If ~/.kube exists, e.g. production cluster, it is replaced by minikube without any warning. 

I had backups but many don't. A small detail with big impact

**Comment by dlorenc** [comment]
Can you explain a little more? We shouldn't be replacing anything. Minikube adds entries to .kube/config, but it shouldn't be deleting or replacing anything.

**Comment by dnascimento** [comment]
I'm using OSX

**Comment by dnascimento** [comment]
I just installed Minikube and my .kube/config was replaced by Minikube's
config

On Jul 27, 2016 16:32, "dlorenc" <notifications@github.com> wrote:

Can you explain a little more? We shouldn't be replacing anything. Minikube
adds entries to .kube/config, but it shouldn't be deleting or replacing
anything.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/kubernetes/minikube/issues/418#issuecomment-235753156>,
or mute the thread

**Comment by dlorenc** [comment]
Do you happen to have the contents of the config from before and after?

**Comment by dlorenc** [comment]
Not sure if there's anything we can do here, but let's close this out by the 0.8 milestone.

**Comment by dlorenc** [comment]
Friendly ping. I just double checked that on my system the existing .kube entries are all preserved.

**Comment by dnascimento** [comment]
Hi @dlorenc , I double checked now too. It keeps the .kube. Somehow it was replaced but I can't replicate. I will close this issue.
