### ISSUE TITLE
Upgrade Docker to 18.09 (and containerd)

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#4180]
While Kubernetes still recommends* using 18.06, some people are using the minikube Docker daemon for other purposes (such as building) and could benefit from upgrading to 18.09.

https://kubernetes.io/docs/setup/cri/#docker

> Version 18.06.2 is recommended, but 1.11, 1.12, 1.13, 17.03 and 18.09 are known to work as well. Keep track of the latest verified Docker version in the Kubernetes release notes.

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#kubernetes-v114-release-notes

> The list of validated docker versions has changed. 1.11.1 and 1.12.1 have been removed. The current list is 1.13.1, 17.03, 17.06, 17.09, 18.06, 18.09.

As a part of this upgrade, we can stop using `docker-runc` and `docker-containerd`/`docker-containerd-ctr` and instead use the regular `runc` and `containerd`/`ctr`.

## 18.06.3-ce
```
docker/
docker/docker
docker/docker-containerd
docker/docker-containerd-ctr
docker/docker-containerd-shim
docker/dockerd
docker/docker-init
docker/docker-proxy
docker/docker-run
```

## 18.09.5
```
docker/
docker/containerd
docker/containerd-shim
docker/ctr
docker/docker
docker/dockerd
docker/docker-init
docker/docker-proxy
docker/runc

```

**Comment by tstromberg** [comment]
Related issue: #3519

**Comment by afbjorklund** [comment]
> Related issue: #3519

Can't we just delete the DOCKER_API_VERSION environment variable, I don't see why it is useful ?

The API will be upgraded automatically with the daemon, and downgraded gracefully with the client...

**Comment by afbjorklund** [comment]
Most likely, this also means that we need upgrade `runc` and `containerd` which we currently build.
(one day we should probably remove that misleading `-bin` from the package names, but whatever)

These are the versions that docker bundles (with 18.09.5):
```
runc version 1.0.0-rc6+dev
commit: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
spec: 1.0.1-dev

containerd github.com/containerd/containerd v1.2.5 bb71b10fd8f58240ca47fbb579b9d1028eea7c84
```

And these are the versions minikube has:
```
# HEAD as of 2019-02-13
RUNC_MASTER_VERSION = 0a012df867a2d525f62a146d8ebdf2e6ab8a5ad5

CONTAINERD_BIN_VERSION = v1.2.0
CONTAINERD_BIN_COMMIT = c4446665cb9c30056f4998ed953e6d4ff22c7c39
```

That `-master` is probably redundant at best, and misleading at worst (since it has a fixed revision)
Normally one uses name such as `-dev` or `-head` or `-master` for things that build straight off HEAD

**Comment by afbjorklund** [comment]
Should probably change to 18.09.6 ? (2019-05-06)

https://docs.docker.com/engine/release-notes/#18096
