### ISSUE TITLE
Add fast-path for restarting a cluster when the configuration is unchanged

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4184]
If the specified configuration is identical to the current configuration:

- If VM is running, skip setup and block until pods are healthy. This should be instantanteous.
- If VM is not running, start VM, reconfigure any IP's necessary, and block until pods are healthy.

#3293 was trying to solve this, but the logic to assert that the configuration was the same was never implemented. I feel that this would be a huge performance benefit for our users.

**Comment by tstromberg** [comment]
Deferring for another release. Doing a prototype, I find that at best there is currently 20% savings for VM's not running, though a lot of savings if there is not. 

One problem is that stopped VM's are rebooted at start :( I'm not sure if this is limited to libmachine or not.

**Comment by medyagh** [comment]
this could solved by Pause command.

**Comment by tstromberg** [comment]
Fixed.
