### ISSUE TITLE
Shorten `minikube start` output

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4187]
`minikube start` has gotten to be overly verbose in a default configuration: 15 lines of output, or 1 message for every 10 seconds of runtime.

I feel like we should be able to get down to roughly half this total (~8 lines) without degrading the user experience substantially.  Here is what head currently looks like:

```
😄  minikube v1.0.1 on linux (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.39.240
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
🚀  Launching Kubernetes v1.14.1 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
```
Here is a strawman proposal, at 7 lines:

```
😄 minikube v1.1.0 on CentOS Linux (amd64)
🔥 Creating kvm2 VM (2 CPUs, 2GB RAM, 20GB disk)
🐳 Configuring environment for Kubernetes v1.14.1 on Docker v18.03
🚜 Pulling images ...
🚀 Launching Kubernetes ... 
⌛ Waiting for: apiserver proxy etcd scheduler controller dns
🏄 Done! kubectl is now configured to use "minikube"
```

This equates to 1 message every 21 seconds of runtime, which is far less spammy.

**Comment by hpandeycodeit** [comment]
@tstromberg is this open to work on?

**Comment by tstromberg** [comment]
@hpandeycodeit - Yes! PR's welcome.

**Comment by afbjorklund** [comment]
Some of this ouput looks _longer_, like addition the distribution to the OS version ? :-)

Also, there's some rounding going on there in our default 19.5GB disk image size.
Then again I always wondered why it was "odd" like that, why not an even 20480M

Some standardization there would be good, not sure if we should go all in on [gibibyte](https://en.wikipedia.org/wiki/Gibibyte) ?
