### ISSUE TITLE
How to run apiserver in verbose mode?

### ISSUE THREAD

**Issue by itsvikasgupta** [kubernetes/minikube#4201]
I am running minikube v1.0.1 on Mac OS High Sierra using VirtualBox 6.0.6. Is it possible to run the kubernetes api-server in minikube with maximum log verbosity?

    $ minikube start --v 4

didn't work for me. When I exec into the api-server container and do ps, the api-server commandline didn't have --v=4 in it. So, minikube is not passing the --v = 4 down to the api-server.

Thanks.

**Comment by tstromberg** [comment]
Correct, the verbose flag is not plumbed through, and I'm not altogether sure if it should be.

I haven't actually tried it, but this example from https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md#kubeadm might work:

`minikube start --extra-config=apiserver.v=10`

If you use `minikube logs`, you can see recent apiserver logs.

Let me know if this helps.

**Comment by Sheshagiri** [comment]
Came here with the same question but for kubelet.
```
Jun 17 17:53:08 minikube kubelet[3927]: E0617 17:53:08.324691    3927 kubelet_volumes.go:140] Orphaned pod "2e710cc4-9128-11e9-b163-000c29bcc19e" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
```
when I started my minikube with `minikube start --extra-config=kubelet.v=10` I see a ton of logs from kubelet in minikube logs.
