### ISSUE TITLE
Darwin: waiting for component=kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by suhasjog** [kubernetes/minikube#4202]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by suhasjog** [comment]
in ~ at ☸️  minikube
  minikube start
😄  minikube v1.0.1 on darwin (amd64)
👍  minikube will upgrade the local cluster from Kubernetes 1.9.0 to 1.14.1
💿  Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
🤹  Downloading Kubernetes v1.14.1 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.101
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 17.09.0-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.14.1
💾  Downloading kubelet v1.14.1
🚜  Pulling images required by Kubernetes v1.14.1 ...
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ...
⌛  Waiting for pods: apiserver

💣  Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: nKubernetes addon ensure completed ao objects t 2019-05-03T20:21:18+00:00 ==

in ~ at ☸️  minikube took 10m 49s

**Comment by suhasjog** [comment]
[crash.log](https://github.com/kubernetes/minikube/files/3143481/crash.log)

**Comment by tstromberg** [comment]
Thanks for the bug report! I'm betting this is related to there being a drastic version upgrade from your old VM:

`minikube will upgrade the local cluster from Kubernetes 1.9.0 to 1.14.1`

and this log entry:

```
May 03 20:28:54 minikube kubelet[25261]: E0503 20:28:54.217791   25261 server.go:711] Starting health server failed: listen tcp 127.0.0.1:10248: bind: address already in use
May 03 20:28:54 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
May 03 20:28:54 minikube systemd[1]: kubelet.service: Unit entered failed state.
May 03 20:28:54 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
```

I suggest runnning `minikube delete`. The new cluster should setup just fine.
