### ISSUE TITLE
open /Users/.../minikube-v1.0.1.iso: El sistema no puede encontrar la ruta especificada.

### ISSUE THREAD

**Issue by Roberto2883** [kubernetes/minikube#4208]
o   minikube v1.0.1 on windows (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: creating: open /Users/Home/.minikube/cache/iso/minikube-v1.0.1.iso: El sistema no puede encontrar la ruta especificada.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

Windows 10 Pro

**Comment by tstromberg** [comment]
Any chance you are running minikube from something other than the C:\ drive?

If so, this is a dupe of #1574

**Comment by tstromberg** [comment]
This issue appears to be a duplicate of #1574, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!
