### ISSUE TITLE
Wait until dashboard is available on `minikube dashboard`

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#421]
So users don't try to access dashboard before it's actually started...

**Comment by aaron-prindle** [comment]
Should `minikube start` wait or should the minikube dashboard command prompt the user that the dashboard is not up yet?

**Comment by dlorenc** [comment]
I'd lean toward the latter, and maybe add a warning to start that mentions things might not be ready right away. What do you think?

**Comment by jimmidyson** [comment]
:+1:

**Comment by dlorenc** [comment]
Also this should probably handle all services, in the `minikube service` command as well.

**Comment by dlorenc** [comment]
Orthogonally, we should also try to speed up the start time. The addon-manager is around 250mb, which contributes a lot to this. I've been following https://github.com/kubernetes/kubernetes/issues/23233 which is tracking improving that, but the timing/plan isn't clear.

We have a few options:
* Help/wait for that revamp
* Stop using the addon manager and just start our addons manually
* Reimplement only the portions of the addon-manager we need in localkube.

**Comment by dlorenc** [comment]
Should be done with #428
