### ISSUE TITLE
minikube always modify virtualbox hostonly adapter dhcp configuration

### ISSUE THREAD

**Issue by perrywang** [kubernetes/minikube#4210]
**problem**
minikube code modify existing dhcp server configuration lowerip and upperip.
With some circumstance we need set same lowerip and upperip to get a predicted single VM ip. But the minikube code logic `src/k8s.io/minikube/vendor/github.com/docker/machine/drivers/virtualbox/virtualbox.go`
is always changing it to 192.168.99.100 ~ 192.168.99.254. 
Could team expose args to indicate whether changing dhcp configuration to provide more flexibility?

**Comment by tstromberg** [comment]
Our preference would be for minikube to have a predictable VM IP between restarts (#951).

We also have a feature request for making IP's settable: #2938

Do these issues cover what you are asking for, or are you looking for something different?

**Comment by perrywang** [comment]
@tstromberg thanks so much. I believe 
mac as dhcp clientidentity fixed my problem.
