### ISSUE TITLE
Create HostPath persistent volume by default

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#422]
Having a host path PV would abstract away the VM's filesystem while still allowing users to persist data across restarts of the VM.

**Comment by dlorenc** [comment]
We've documented how to use PVCs here: https://github.com/kubernetes/minikube/blob/master/README.md#persistent-volumes

I agree it would be cool to create one by default, especially if we can get it persisted across reboots.

**Comment by andrewgdavis** [comment]
... but its slow.  see https://github.com/kubernetes/minikube/issues/419  for details.

**Comment by dlorenc** [comment]
We have the /data directory now, we can create a hostpath volume in it. I wonder if the addon-manager can do that for us.

**Comment by dlorenc** [comment]
It looks like it can create PersistentVolumes: https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/addon-manager

**Comment by aaron-prindle** [comment]
HostPath dynamic provisioning should solve this use case.  This was added recently via this commit: #1199
Closing.
