### ISSUE TITLE
help message when 'minikube start' is wrong.

### ISSUE THREAD

**Issue by Guojunzhou-git** [kubernetes/minikube#4223]
💣  Unable to start VM
❌  Error:         [VM_DOES_NOT_EXIST] Error getting state for host: machine does not exist
💡  Advice:        Your system no longer knows about the VM previously created by minikube. Run 'minikube delete' to reset your local state.
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issue/3864

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new

eh, issue-3864's url lost a char 's'....

**Comment by RA489** [comment]
@Guojunzhou-git  Do you mind including:

The exact command-lines used so that we can replicate the issue
The output of the "minikube logs" command
Which operating system version was used

**Comment by tstromberg** [comment]
Marking as obsolete: This was fixed in minikube v1..0.1.
