### ISSUE TITLE
Failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.0"

### ISSUE THREAD

**Issue by Guojunzhou-git** [kubernetes/minikube#4224]
sudo minikube start
Password:
There is a newer version of minikube available (v1.0.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.0.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
2019/05/08 15:49:46 Unable to read "/Users/sing/.docker/config.json": open /Users/sing/.docker/config.json: no such file or directory
2019/05/08 15:49:46 No matching credentials were found, falling back on anonymous
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
E0508 15:50:47.526832   42731 start.go:209] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/sing/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.14.0: fetching remote image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: i/o timeout
✨  Preparing Kubernetes environment ...
❌  Unable to load cached images: loading cached images: loading image /Users/sing/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.14.0: stat /Users/sing/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.14.0: no such file or directory
🚜  Pulling images required by Kubernetes v1.14.0 ...
❌  Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout: 
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.0": output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
: Process exited with status 1
🚀  Launching Kubernetes v1.14.0 using kubeadm ... 

💣  Error starting cluster: kubeadm init: 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI 

[init] Using Kubernetes version: v1.14.0
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.14.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.14.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.14.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.14.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.3.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by Guojunzhou-git** [comment]
minikube logs:


==> dmesg <==
[May 8 07:50] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[ +22.696138] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +9.539462] systemd-fstab-generator[1288]: Ignoring "noauto" for root device
[  +0.005586] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:35 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000003] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +0.426575] vboxguest: loading out-of-tree module taints kernel.
[  +0.013798] vgdrvHeartbeatInit: Setting up heartbeat to trigger every 2000 milliseconds
[  +0.002603] vboxguest: misc device minor 57, IRQ 20, I/O port d020, MMIO at 00000000f0000000 (size 0x400000)
[  +0.000430] vboxvideo: Unknown symbol ttm_bo_mmap (err 0)
[  +0.000015] vboxvideo: Unknown symbol ttm_bo_global_release (err 0)
[  +0.000006] vboxvideo: Unknown symbol ttm_pool_unpopulate (err 0)
[  +0.000004] vboxvideo: Unknown symbol ttm_bo_manager_func (err 0)
[  +0.000003] vboxvideo: Unknown symbol ttm_bo_global_init (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_default_io_mem_pfn (err 0)
[  +0.000007] vboxvideo: Unknown symbol ttm_bo_device_release (err 0)
[  +0.000013] vboxvideo: Unknown symbol ttm_bo_kunmap (err 0)
[  +0.000004] vboxvideo: Unknown symbol ttm_bo_del_sub_from_lru (err 0)
[  +0.000008] vboxvideo: Unknown symbol ttm_bo_device_init (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_init_mm (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_dma_acc_size (err 0)
[  +0.000004] vboxvideo: Unknown symbol ttm_tt_init (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_kmap (err 0)
[  +0.000007] vboxvideo: Unknown symbol ttm_bo_add_to_lru (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_unref (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_mem_global_release (err 0)
[  +0.000003] vboxvideo: Unknown symbol ttm_mem_global_init (err 0)
[  +0.000010] vboxvideo: Unknown symbol ttm_bo_init (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_validate (err 0)
[  +0.000008] vboxvideo: Unknown symbol ttm_tt_fini (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_eviction_valuable (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_pool_populate (err 0)
[  +0.286538] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +0.002001] VBoxService 5.1.38 r122592 (verbosity: 0) linux.amd64 (May  9 2018 12:22:30) release log
              00:00:00.001554 main     Log opened 2019-05-08T07:50:36.096310000Z
[  +0.000082] 00:00:00.001683 main     OS Product: Linux
[  +0.000044] 00:00:00.001733 main     OS Release: 4.15.0
[  +0.000043] 00:00:00.001776 main     OS Version: #1 SMP Tue Mar 26 02:53:14 UTC 2019
[  +0.000091] 00:00:00.001819 main     Executable: /usr/sbin/VBoxService
              00:00:00.001820 main     Process ID: 2030
              00:00:00.001820 main     Package type: LINUX_64BITS_GENERIC
[  +0.000081] 00:00:00.001947 main     5.1.38 r122592 started. Verbose level = 0
[ +10.991180] systemd-fstab-generator[2286]: Ignoring "noauto" for root device
[ +13.319150] systemd-fstab-generator[2543]: Ignoring "noauto" for root device
[  +0.091302] systemd-fstab-generator[2552]: Ignoring "noauto" for root device
[May 8 07:52] NFSD: Unable to end grace period: -110

==> kernel <==
 08:00:17 up 10 min,  0 users,  load average: 0.06, 0.21, 0.19
Linux minikube 4.15.0 #1 SMP Tue Mar 26 02:53:14 UTC 2019 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Wed 2019-05-08 07:50:35 UTC, end at Wed 2019-05-08 08:00:17 UTC. --
May 08 07:59:53 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 52.
May 08 07:59:53 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 08 07:59:53 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
May 08 07:59:54 minikube kubelet[3463]: Flag --allow-privileged has been deprecated, will be removed in a future version
May 08 07:59:54 minikube kubelet[3463]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 07:59:54 minikube kubelet[3463]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 07:59:54 minikube kubelet[3463]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 07:59:54 minikube kubelet[3463]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 07:59:54 minikube kubelet[3463]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 07:59:54 minikube kubelet[3463]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 07:59:54 minikube kubelet[3463]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 07:59:54 minikube kubelet[3463]: I0508 07:59:54.049872    3463 server.go:417] Version: v1.14.0
May 08 07:59:54 minikube kubelet[3463]: I0508 07:59:54.050160    3463 plugins.go:103] No cloud provider specified.
May 08 07:59:54 minikube kubelet[3463]: F0508 07:59:54.050246    3463 server.go:265] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
May 08 07:59:54 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
May 08 07:59:54 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
May 08 08:00:04 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
May 08 08:00:04 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 53.
May 08 08:00:04 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 08 08:00:04 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
May 08 08:00:04 minikube kubelet[3475]: Flag --allow-privileged has been deprecated, will be removed in a future version
May 08 08:00:04 minikube kubelet[3475]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:04 minikube kubelet[3475]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:04 minikube kubelet[3475]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:04 minikube kubelet[3475]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:04 minikube kubelet[3475]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:04 minikube kubelet[3475]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:04 minikube kubelet[3475]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:04 minikube kubelet[3475]: I0508 08:00:04.307229    3475 server.go:417] Version: v1.14.0
May 08 08:00:04 minikube kubelet[3475]: I0508 08:00:04.307517    3475 plugins.go:103] No cloud provider specified.
May 08 08:00:04 minikube kubelet[3475]: F0508 08:00:04.307607    3475 server.go:265] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
May 08 08:00:04 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
May 08 08:00:04 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
May 08 08:00:14 minikube systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
May 08 08:00:14 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 54.
May 08 08:00:14 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
May 08 08:00:14 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
May 08 08:00:14 minikube kubelet[3487]: Flag --allow-privileged has been deprecated, will be removed in a future version
May 08 08:00:14 minikube kubelet[3487]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:14 minikube kubelet[3487]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:14 minikube kubelet[3487]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:14 minikube kubelet[3487]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:14 minikube kubelet[3487]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:14 minikube kubelet[3487]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:14 minikube kubelet[3487]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
May 08 08:00:14 minikube kubelet[3487]: I0508 08:00:14.554708    3487 server.go:417] Version: v1.14.0
May 08 08:00:14 minikube kubelet[3487]: I0508 08:00:14.555111    3487 plugins.go:103] No cloud provider specified.
May 08 08:00:14 minikube kubelet[3487]: F0508 08:00:14.555202    3487 server.go:265] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
May 08 08:00:14 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
May 08 08:00:14 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by Kingonion** [comment]
It seems you can't connect to `k8s.gcr.io`. In china, you can try to pull images from mirrors. `sudo minikube start --registry-mirror registry.cn-hangzhou.aliyuncs.com/google_containers`

**Comment by Guojunzhou-git** [comment]
> It seems you can't connect to `k8s.gcr.io`. In china, you can try to pull images from mirrors. `sudo minikube start --registry-mirror registry.cn-hangzhou.aliyuncs.com/google_containers`

Thanks for your help. 


syf:~ sing$ sudo minikube start --registry-mirror registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=virtualbox
Password:
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...

💣  Failed to enable container runtime: command failed: sudo systemctl start docker
stdout: 
stderr: Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
> It seems you can't connect to `k8s.gcr.io`. In china, you can try to pull images from mirrors. `sudo minikube start --registry-mirror registry.cn-hangzhou.aliyuncs.com/google_containers`

This advice is not quite correct:

- The correct flag is `--image-repository`
- Please do not use `sudo` for minikube unless absolutely necessary.

The correct command here should be:

`minikube start --image-mirror-country=cn`

**Comment by rajeshsoro** [comment]
Hi Team ,
i am trying to run the commad on my test server its failed with following errors.
server is running with o.s 
[root@MAV-UDSF-1 etc]# cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

[root@MAV-UDSF-1 ~]# kubeadm init --pod-network-cidr=10.244.0.0/16
[init] Using Kubernetes version: v1.15.0
[preflight] Running pre-flight checks
        [WARNING HTTPProxy]: Connection to "https://10.1.36.96" uses proxy "http://10.1.20.57:80". If that is not intended, adjust your proxy settings
        [WARNING HTTPProxyCIDR]: connection to "10.96.0.0/12" uses proxy "http://10.1.20.57:80". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
        [WARNING HTTPProxyCIDR]: connection to "10.244.0.0/16" uses proxy "http://10.1.20.57:80". This may lead to malfunctional cluster setup. Make sure that Pod and Services IP ranges specified correctly as exceptions in proxy configuration
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.15.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.15.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.15.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.15.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.3.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

Pleaese help me to resolve this issue ASAP.

**Comment by wangzhipeng** [comment]
@rajeshsoro  kubeadm init --image-repository registry.aliyuncs.com/google_containers

**Comment by heiying5573** [comment]
> > It seems you can't connect to `k8s.gcr.io`. In china, you can try to pull images from mirrors. `sudo minikube start --registry-mirror registry.cn-hangzhou.aliyuncs.com/google_containers`
> 
> This advice is not quite correct:
> 
> * The correct flag is `--image-repository`
> * Please do not use `sudo` for minikube unless absolutely necessary.
> 
> The correct command here should be:
> 
> `minikube start --image-mirror-country=cn`

niubility
