### ISSUE TITLE
/Users is not accessible in the VM (xhyve)

### ISSUE THREAD

**Issue by raeesbhatti** [kubernetes/minikube#423]
As far as I understand, `/Users` (on Mac OS) should be accessible inside the VM, so that, we can have `hostPath` shared between the VM and host but it is not.
### Steps to reproduce
1. Install latest minikube
2. Start minikube: `minikube start --vm-driver=xhyve`
3. `minikube ssh 'ls /'`

**Comment by raeesiqbal** [comment]
`minikube version`: `minikube version: v0.7.1`

**Comment by dlorenc** [comment]
This is an xhyve-driver specific issue. I think we need to turn on 9p file-sharing here:
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cluster/cluster_darwin.go#L50

@r2d4: this should be a good starter bug. Once we get this working for all supported drivers we should add an e2e test for it.

**Comment by r2d4** [comment]
Once https://github.com/Homebrew/homebrew-core/pull/3638 is merged, we can test with the new version of docker-xhyve-driver

**Comment by zchee** [comment]
@dlorenc @r2d4 I still not understand all of the minikube sources, but yes.
It needs that variable to `true`.
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cluster/cluster_darwin.go#L50

and, In my code are hard-coded, but maybe minikube is possible to change the mount directory.
https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L66
https://github.com/zchee/docker-machine-driver-xhyve/blob/master/xhyve/xhyve.go#L188

**Comment by dlorenc** [comment]
This should be fixed in the next release.
