### ISSUE TITLE
registry-mirror: Job for docker.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by Guojunzhou-git** [kubernetes/minikube#4231]
sudo minikube start --registry-mirror registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=virtualbox
Password:
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...

💣  Failed to enable container runtime: command failed: sudo systemctl start docker
stdout: 
stderr: Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by Guojunzhou-git** [comment]
syf:~ sing$ sudo systemctl start docker
Password:
sudo: systemctl: command not found

**Comment by Guojunzhou-git** [comment]
syf:~ sing$ docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 0
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: NOUR:TXST:AFP2:KKBB:VNRQ:KXDC:UB6W:XDD6:PFUR:DTT2:FEYV:VFYB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 25
 Goroutines: 51
 System Time: 2019-05-09T03:12:29.717042311Z
 EventsListeners: 2
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

**Comment by Guojunzhou-git** [comment]
E0509 11:13:03.823683    3427 logs.go:155] Failed to list containers for "kube-apiserver": Process exited with status 1
E0509 11:13:03.901616    3427 logs.go:155] Failed to list containers for "coredns": Process exited with status 1
E0509 11:13:03.986491    3427 logs.go:155] Failed to list containers for "kube-scheduler": Process exited with status 1
E0509 11:13:04.065041    3427 logs.go:155] Failed to list containers for "kube-proxy": Process exited with status 1
E0509 11:13:04.147637    3427 logs.go:155] Failed to list containers for "kube-addon-manager": Process exited with status 1
E0509 11:13:04.237711    3427 logs.go:155] Failed to list containers for "kubernetes-dashboard": Process exited with status 1
E0509 11:13:04.319003    3427 logs.go:155] Failed to list containers for "storage-provisioner": Process exited with status 1
==> dmesg <==
[May 9 03:03] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[May 9 03:04] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +9.511647] systemd-fstab-generator[1290]: Ignoring "noauto" for root device
[  +0.004398] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:35 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000003] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +0.439445] vboxguest: loading out-of-tree module taints kernel.
[  +0.018295] vgdrvHeartbeatInit: Setting up heartbeat to trigger every 2000 milliseconds
[  +0.001474] vboxguest: misc device minor 57, IRQ 20, I/O port d020, MMIO at 00000000f0000000 (size 0x400000)
[  +0.000778] vboxvideo: Unknown symbol ttm_bo_mmap (err 0)
[  +0.000014] vboxvideo: Unknown symbol ttm_bo_global_release (err 0)
[  +0.000005] vboxvideo: Unknown symbol ttm_pool_unpopulate (err 0)
[  +0.000005] vboxvideo: Unknown symbol ttm_bo_manager_func (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_global_init (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_default_io_mem_pfn (err 0)
[  +0.000008] vboxvideo: Unknown symbol ttm_bo_device_release (err 0)
[  +0.000012] vboxvideo: Unknown symbol ttm_bo_kunmap (err 0)
[  +0.000004] vboxvideo: Unknown symbol ttm_bo_del_sub_from_lru (err 0)
[  +0.000007] vboxvideo: Unknown symbol ttm_bo_device_init (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_init_mm (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_dma_acc_size (err 0)
[  +0.000004] vboxvideo: Unknown symbol ttm_tt_init (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_kmap (err 0)
[  +0.000007] vboxvideo: Unknown symbol ttm_bo_add_to_lru (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_unref (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_mem_global_release (err 0)
[  +0.000003] vboxvideo: Unknown symbol ttm_mem_global_init (err 0)
[  +0.000010] vboxvideo: Unknown symbol ttm_bo_init (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_validate (err 0)
[  +0.000008] vboxvideo: Unknown symbol ttm_tt_fini (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_eviction_valuable (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_pool_populate (err 0)
[  +0.260139] VBoxService 5.1.38 r122592 (verbosity: 0) linux.amd64 (May  9 2018 12:22:30) release log
              00:00:00.002451 main     Log opened 2019-05-09T03:04:13.210373000Z
[  +0.000094] 00:00:00.002624 main     OS Product: Linux
[  +0.000048] 00:00:00.002678 main     OS Release: 4.15.0
[  +0.000045] 00:00:00.002724 main     OS Version: #1 SMP Thu Apr 25 20:51:48 UTC 2019
[  +0.000108] 00:00:00.002769 main     Executable: /usr/sbin/VBoxService
              00:00:00.002770 main     Process ID: 2026
              00:00:00.002770 main     Package type: LINUX_64BITS_GENERIC
[  +0.000090] 00:00:00.002919 main     5.1.38 r122592 started. Verbose level = 0
[  +0.020890] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +8.156963] systemd-fstab-generator[2283]: Ignoring "noauto" for root device
[May 9 03:06] NFSD: Unable to end grace period: -110

==> kernel <==
 03:13:04 up 9 min,  0 users,  load average: 0.00, 0.29, 0.31
Linux minikube 4.15.0 #1 SMP Thu Apr 25 20:51:48 UTC 2019 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Thu 2019-05-09 03:04:12 UTC, end at Thu 2019-05-09 03:13:04 UTC. --
-- No entries --

**Comment by tstromberg** [comment]
My apologies for the bad experience here. Do you mind sharing the output of:

`minikube ssh systemctl status docker.service`

`minikube ssh cat /usr/lib/systemd/system/docker.service`

This should help us figure out what's going on. Thank you!

**Comment by tstromberg** [comment]
I was able to duplicate this issue:

```
● docker.service - Docker Application Container Engine
   Loaded: loaded (/usr/lib/systemd/system/docker.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-05-16 19:15:28 UTC; 1min 44s ago
     Docs: https://docs.docker.com
  Process: 2348 ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=virtualbox --insecure-registry 10.96.0.0/12 --registry-mirror registry.cn-hangzhou.aliyuncs.com/google_containers (code=exited, status=1/FAILURE)
 Main PID: 2348 (code=exited, status=1/FAILURE)

May 16 19:15:28 minikube systemd[1]: Starting Docker Application Container Engine...
May 16 19:15:28 minikube systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
May 16 19:15:28 minikube systemd[1]: docker.service: Failed with result 'exit-code'.
May 16 19:15:28 minikube systemd[1]: Failed to start Docker Application Container Engine.
ssh: Process exited with status 3
```

Using `journalctl -xe` I see:

```
-- Unit docker.service has begun starting up.
May 16 19:15:28 minikube dockerd[2348]: Status: invalid argument "registry.cn-hangzhou.aliyuncs.com/google_containers" for "--registry-mirror" flag: invalid mirror: unsupported scheme "" in "registry.cn-hangzhou.aliyuncs.com/google_containers"
May 16 19:15:28 minikube dockerd[2348]: See 'dockerd --help'., Code: 125
May 16 19:15:28 minikube systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
May 16 19:15:28 minikube systemd[1]: docker.service: Failed with result 'exit-code'.
May 16 19:15:28 minikube systemd[1]: Failed to start Docker Application Container Engine.
```

I believe you want to use `--image-repository` instead of `--registry-mirror` in this case. I'll open an issue to make this easier to debug and add flag validation.
