### ISSUE TITLE
Migrate from dep to Go Modules

### ISSUE THREAD

**Issue by myhro** [kubernetes/minikube#4234]
Hi,

I've been working on migrating minikube's current dependency management [from Go dep to Go modules][1], mainly because I like to build projects with `git clone`/`make` and forgetting about `GOPATH`. It ended up simplifying the build infrastructure a bit, so I thought about upstreaming the changes.

The only reference to Go modules I found is [this comment from last September][2] on issue #3037, related to the last `godep` to `dep` migration.

Hence the question: are you interested in this change? If so, I'll prepare a proper pull request (e.g. updating the related documentation).

Regards,
Tiago.

[1]: https://github.com/myhro/minikube/commits/go-mod
[2]: https://github.com/kubernetes/minikube/issues/3037#issuecomment-420875747

**Comment by tstromberg** [comment]
Yes! I would very much like to see minikube migrate to Go Modules, but haven't had a chance to prioritize it. I think the timing is right now, as other Kubernetes components have begun making the jump.

Please feel free to assign me as a reviewer for any PR's that make this happen.

**Comment by myhro** [comment]
@tstromberg That's great. Thanks!

I'm having trouble to pass the CLA check on the related PR, so I'll assign it to you as soon as this is fixed.
