### ISSUE TITLE
mount failed: mkdir: cannot create directory '/mnt/data': File exists

### ISSUE THREAD

**Issue by dionizh** [kubernetes/minikube#4239]
When stopping a minikube mount process with ctrl+C, then try to remount the same disk again, minikube crashed with the following message:

Mounting host path /mnt/scratch/dzhong/redis into VM as /mnt/data ...
o   Mount options:
    - Type:     9p
    - UID:      docker
    - GID:      docker
    - Version:  9p2000.L
    - MSize:    262144
    - Mode:     755 (-rwxr-xr-x)
    - Options:  map[]
@   Userspace file server: ufs starting

!   mount failed: mkdir: cannot create directory '/mnt/data': File exists
: Process exited with status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

Mount command run is a simple:
minikube mount /mnt/scratch/dzhong/redis:/mnt/data

I have to stop minikube, and start it again, for the mount to work.

Running the latest version of minikube and kubectl on centos7.

thanks
dioni

**Comment by RA489** [comment]
@dionizh can you paste exact command line used?

**Comment by dionizh** [comment]
Hi I have given the command line above:
minikube mount /mnt/scratch/dzhong/redis:/mnt/data

**Comment by tstromberg** [comment]
What version of minikube is this with?

**Comment by dionizh** [comment]
It is minikube v1.0.1.
Going to check the output of those when I run into the issue again.

**Comment by tstromberg** [comment]
I can confirm that this happens in v1.1 if a process is still using the old mountpoint. We should output a clearer error when this occurs. 

To reproduce:

- Run `minikube mount`
- In a `minikube ssh` session, cd to the mount directory.
- Hit Ctrl-C on the `minikube mount` process
- Re-run `minikube mount` and watch it fail.

**Comment by dionizh** [comment]
Thank you. That does sound like what I did.

**Comment by fenglixa** [comment]
I reproduced this issue, and I would like to provide a PR to fix this issue.
Append my investigation & solution here:
1.  "|| true" is  in the umount command. It will lead to "force Unmount" will be never called, should be code error.
2. Current "force Unmount" cannot work if mount point is busy.

After address 1, the message will be more clearer to point the mount point is busy.
Error will be gone for this case if 2 is addressed.

@tstromberg  any comments?  Thanks a lot!

BR
-Francis

**Comment by tstromberg** [comment]
Sounds good. I'd be happy to review any PR that makes the failure reason
more obvious. It may be possible that we can't make umount -f work, but we
can at least do a better job of telling the user why the mount failed.

**Comment by fenglixa** [comment]
Thanks @tstromberg PR #4393 wish you could help review, any comments are welcome.

**Comment by fenglixa** [comment]
This issue could be closed by fixes #4393
/close
