### ISSUE TITLE
What minikube functions/features use "kube-addon-manager-minikubevm" pod?

### ISSUE THREAD

**Issue by shouhong** [kubernetes/minikube#424]
By default minikube will create a pod named "kube-addon-manager-minikubevm". What minikube functions/features will use this pod?

In my environment it cannot be started because the host cannot connect to google. But I can use "minikube" and "kubectl" commands without problem. So I'm wondering if I can use the K8S cluster created by minikube without this pod?

**Comment by dlorenc** [comment]
The addon-manager pod is responsible for creating cluster addons. The only addon we use right now is the dashboard, but we'll probably add more in the future.

Right now, everything in the cluster will work correctly except for the dashboard.

**Comment by dlorenc** [comment]
Feel free to re-open this if you have any other questions.
