### ISSUE TITLE
minikube crash

### ISSUE THREAD

**Issue by aditama2019** [kubernetes/minikube#4246]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by aditama2019** [comment]
minikube start --vm-driver kvm2 

out put
 </devices>
</domain>
: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by RA489** [comment]
@aditama2019  Do you mind attaching
1. Which operating system version was used?
2. The output of the "minikube logs" command?

**Comment by tstromberg** [comment]
Dupe of #4247
