### ISSUE TITLE
Failed to start minikube in Ubuntu 1.4.04 + VirtualBox 1.5.2

### ISSUE THREAD

**Issue by PavelPrischepa** [kubernetes/minikube#425]
I've met the following issue:
```
Failed to open a session for the virtual machine minikubeVM.

The virtual machine 'minikubeVM' has terminated unexpectedly during startup with exit code 1 (0x1).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: MachineWrap
Interface: IMachine {b2547866-a0a1-4391-8b86-6952d82efaa0}
````

**Comment by aaron-prindle** [comment]
@PavelPrischepa 
Does your virtualbox installation work outside of minikube?  In investigating the NS_ERROR_FAILURE (0x80004005) error it seems that it typically comes from virtualbox not being installed/compiled correctly.  What version of virtualbox are you running on?   This can be be found from the GUI in the Help->About section or from the CLI w/ `vboxmanage --version`.  Also what operating system are you using?

I would recommend reinstalling virtualbox from https://www.virtualbox.org/wiki/Downloads for your operating system.

**Comment by dlorenc** [comment]
Please reopen with the info @aaron-prindle asked for if you get a chance!
