### ISSUE TITLE
downloading binaries: proxyconnect tcp: tls: oversized record received with length 20527

### ISSUE THREAD

**Issue by javakishore** [kubernetes/minikube#4252]
I am trying to start minikube cluster in Ubuntu VM. I am behind the http proxy. I am getting the below error.
osboxes@osboxes:$ sudo minikube start --docker-env http_proxy=$http_proxy --docker-env https_proxy=$https_proxy
o   minikube v1.0.1 on linux (amd64)
>   Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 10.0.2.15
-   Configuring Docker as the container runtime ...
    - env http_proxy=http://10.1.2.3:8080
    - env https_proxy=http://10.1.2.3:8080
-   Version of container runtime is 18.09.5
-   Preparing Kubernetes environment ...
X   Unable to load cached images: loading cached images: loading image /home/osboxes/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: stat /home/osboxes/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory
@   Downloading kubeadm v1.14.1
@   Downloading kubelet v1.14.1

!   Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.14.1: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubeadm: proxyconnect tcp: tls: oversized record received with length 20527
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubeadm: proxyconnect tcp: tls: oversized record received with length 20527
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubeadm: proxyconnect tcp: tls: oversized record received with length 20527
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubeadm: proxyconnect tcp: tls: oversized record received with length 20527
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.1/bin/linux/amd64/kubeadm: proxyconnect tcp: tls: oversized record received with length 20527

**Comment by RA489** [comment]
@javakishore Do you mind attaching the output of minikube logs when this failure happens?

**Comment by tstromberg** [comment]
While you have specified --docker-env overrides, you actually need to set the HTTP_PROXY and HTTPS_PROXY environment variables to tell minikube about your proxy, as per:

https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

I've now updated the doc to mention this specific issue. Please let me know if this helps.
