### ISSUE TITLE
vbox on VMware: copying kubeadm: copy: pre-copy: NewSession: EOF

### ISSUE THREAD

**Issue by recepayaz** [kubernetes/minikube#4256]
Hi, I have ubuntu vmware on windows 10 home edition and trying to launch minikube but getting the following error. Please see full logs in the attachment

recep@ubuntu:~$ uname  -a

Linux ubuntu 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

recep@ubuntu:~$ minikube  start -v=8
😄  minikube v1.0.1 on l
[minikube.log](https://github.com/kubernetes/minikube/files/3179800/minikube.log)
inux (amd64)
💿  Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
Creating CA: /home/recep/.minikube/certs/ca.pem
Creating client certificate: /home/recep/.minikube/certs/cert.pem
COMMAND: /usr/bin/VBoxManage --version
STDOUT:
{
5.2.18_Ubuntur123745
}
STDERR:
{
}
COMMAND: /usr/bin/VBoxManage list hostonlyifs
...
...
...
...
...
..

📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
❌  Unable to load cached images: loading cached images: loading image /home/recep/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: Docker load /tmp/storage-provisioner_v1.8.1: NewSession: EOF
💾  Downloading kubelet v1.14.1
💾  Downloading kubeadm v1.14.1

💣  Failed to update cluster: downloading binaries: copying kubeadm: copy: pre-copy: NewSession: EOF

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

Please advice.
[minikube.log](https://github.com/kubernetes/minikube/files/3179804/minikube.log)

**Comment by tstromberg** [comment]
Do you mind attaching the output of `minikube logs`?

Apparently, something is blocking SSH access to the VM, at least as far as scp is concerned. Normal ssh apparently worked.  It may not help, but do you mind checking if upgrading to VirtualBox 6.0+ helps?

**Comment by recepayaz** [comment]
hi here is the output:
recep@ubuntu:~$ minikube logs

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: ssh: handshake failed: read tcp 127.0.0.1:38308->127.0.0.1:44925: read: connection reset by peer

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
recep@ubuntu:~$ virtualbox 


I will try to upgrade it.

**Comment by recepayaz** [comment]
@tstromberg nope , upgrade did not work either :(

**Comment by tstromberg** [comment]
Hmm.. It seems possible that your host just can't access the VirtualBox network interface, though I'm not experienced enough with it yet to say why. The especially confounding part here is that the error is through accessing localhost.


Can you share the complete output of `minikube start --alsologtostderr -v=8` and `minikube status` with the update?

I'm curious also what it says if you use the minikube IP listed in `minikube status` to connect: `ssh -vvv <ip>`

I wonder if `sudo iptables -S` shows anything interesting, but I really can't imagine what might be going on here, other than perhaps not routing packets to vboxnet0.

In the mean time, you can likely workaround this problem by using the kvm2 driver, but I'm still baffled by the issue altogether: https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver

**Comment by tstromberg** [comment]
I read now that you are using a nested VM: VirtualBox on top of VMware? Is that even supported? KVM2 on top of VMware may work, but it also might fail spectacularly.

I would personally just run minikube on top of Windows. It should support VirtualBox and VMware directly there without the nesting. If you run into any issues there, definitely open a bug.

**Comment by recepayaz** [comment]
hehe :) fair enough,
thanks
