### ISSUE TITLE
vbox: Cannot handle settings version '1.2-macosx'.

### ISSUE THREAD

**Issue by rmanansa** [kubernetes/minikube#4258]
**The exact command to reproduce the issue**:
brew update && brew install kubectl && brew cask install docker minikube virtualbox
minikube start

**The full output of the command that failed**:
minikube v1.0.1 on darwin (amd64)
💿  Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

💣  Unable to start VM: create: precreate: /usr/local/bin/VBoxManage list hostonlyifs failed:
VBoxManage: error: Failed to create the VirtualBox object!
VBoxManage: error: Error in /Users/rmanansala/Library/VirtualBox/VirtualBox.xml (line 3) -- Cannot handle settings version '1.2-macosx'.
VBoxManage: error: /Users/vbox/tinderbox/6.0-mac-rel/src/VBox/Main/src-server/VirtualBoxImpl.cpp[624] (nsresult VirtualBox::init())
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component VirtualBoxWrap, interface IVirtualBox

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:
Ramils-Home-Laptop:google-cloud-sdk rmanansala$ minikube logs

💣  api load: filestore: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
**The operating system version**:
MacOS Sierra
Version 10.12.6

**Comment by rmanansa** [comment]
1.  Open the VirtualBox.xml file. e.g. 
/Users//Library/VirtualBox/VirtualBox.xml 

$> vi /Users/rmanan/Library/VirtualBox/VirtualBox.xml

2.  Change this value from 1.2-macosx to 1.3-macosx
<VirtualBox xmlns="http://www.virtualbox.org/" version="1.2-macosx">

3.  Start minikube 

$> minikube start

**Comment by tstromberg** [comment]
Thank you for sharing your experience! This sounds like a VirtualBox upgrade issue, that you solved perfectly.

My guess is that removing `/Users/rmanansala/Library/VirtualBox/VirtualBox.xml` would have had the same effect. Will close now that there is a solution.
