### ISSUE TITLE
none: sudo systemctl start docker: exit status 1 (sudoers specifies that root is not allowed to sudo)

### ISSUE THREAD

**Issue by gouravbansal11** [kubernetes/minikube#4259]
**minikube start --vm-driver=none --logtostderr**:

**ExecStart=/usr/bin/kubelet --allow-privileged=true --authorization-mode=Webhook --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --cgroup-driver=cgroupfs --client-ca-file=/var/lib/minikube/certs/ca.crt --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --container-runtime=docker --fail-swap-on=false --hostname-override=minikube --kubeconfig=/etc/kubernetes/kubelet.conf --pod-manifest-path=/etc/kubernetes/manifests

[Install]
@   Downloading kubeadm v1.14.1
@   Downloading kubelet v1.14.1
W0515 17:44:47.267078    2766 exit.go:99] Failed to update cluster: downloading binaries: copying kubeadm: copy: error creating file at /usr/bin/kubeadm: open /usr/bin/kubeadm: permission denied

!   Failed to update cluster: downloading binaries: copying kubeadm: copy: error creating file at /usr/bin/kubeadm: open /usr/bin/kubeadm: permission denied
**:

**sudo minikube start --vm-driver=none --logtostderr**:

**I0515 17:49:16.038651    3141 exec_runner.go:39] Run: systemctl is-active --quiet service containerd
I0515 17:49:16.047809    3141 exec_runner.go:39] Run: sudo systemctl stop containerd
W0515 17:49:16.052929    3141 cruntime.go:111] disable failed: running command: sudo systemctl stop containerd: exit status 1
I0515 17:49:16.052948    3141 exec_runner.go:39] Run: systemctl is-active --quiet service containerd
W0515 17:49:16.059533    3141 docker.go:74] disableOthers: containerd is still active
I0515 17:49:16.059547    3141 exec_runner.go:39] Run: sudo systemctl start docker
W0515 17:49:16.064307    3141 exit.go:99] Failed to enable container runtime: running command: sudo systemctl start docker: exit status 1

!   Failed to enable container runtime: running command: sudo systemctl start docker: exit status 1

**When i tried to install all the setup with root user(which is not recommended) it try to start docker with sudo command and failed as sudo is not allowed for root user. So trying with other user and logs attached below
Attached the logs of docker installation and kubectl and minikuber**
[minikube.log](https://github.com/kubernetes/minikube/files/3182519/minikube.log)

**Comment by tstromberg** [comment]
The none driver currently assumes sudo.

I'm surprised that the root user is not allowed to use sudo - I've never seen that configuration. Do you mind sharing the output of: `sudo sudo ls`?

**Comment by gouravbansal11** [comment]
[root@gouravba02lx ~]# sudo sudo ls
sudo: sudoers specifies that root is not allowed to sudo
[root@gouravba02lx ~]# sudo ls
sudo: sudoers specifies that root is not allowed to sudo
[root@gouravba02lx ~]#

**Comment by tstromberg** [comment]
Interesting. This seems like a very peculiar configuration of /etc/sudoers. Is this a configuration that you may have modified?

We could add a check to only call sudo if necessary, but it's invasive enough that I would like to see if others are affected first.

**Comment by gouravbansal11** [comment]
Nope. I didn't made any changes in this file.

**Comment by afbjorklund** [comment]
It should be enabled by default: https://git.centos.org/rpms/sudo/blob/c7/f/SOURCES/sudoers

```
## Allow root to run any commands anywhere
root	ALL=(ALL) 	ALL

## Allows people in group wheel to run all commands
%wheel	ALL=(ALL)	ALL
```

So it looks like a local configuration.

**Comment by afbjorklund** [comment]
We should probably make the `none` driver use sudo, rather than root user ? See #3718
