### ISSUE TITLE
MiniKube in EC2

### ISSUE THREAD

**Issue by ColinHebert** [kubernetes/minikube#426]
Is there a way to get MiniKube to work in EC2?

We would like to use it within our CI system to make sure our tools are interacting properly with Kubernetes.
When the recommended method to run Kubernetes locally was with a docker container, we could do that easily. But MiniKube currently requires virtualisation which is not possible under EC2.

A good behaviour would be similar to what docker-machine supports, with multiple drivers, one of them being AWS/EC2.

**Comment by dlorenc** [comment]
Hey,

Using the Docker-based setup is probably your best bet for now. We're unlikely to add support for any "remote" drivers, as that would make the work we're planning around networking and storage a lot harder.

Eventually we are planning on a "no-vm" type driver for linux systems, that work is currently discussed here: #261. I think that driver would let you run minikube on an EC2. Would that work for this use-case?

**Comment by ColinHebert** [comment]
Hi @dlorenc , thanks for the info.

The follow up question would be, according to http://kubernetes.io/docs/getting-started-guides/docker/ MiniKube is now the recommended way of doing local testing; does that mean that in the long run the docker option will become undocumented/deprecated completely?

Should both options be maintained?

**Comment by dlorenc** [comment]
That's definitely a fair question :)

I don't think the support status of the Docker-solution has changed (or is going to change anytime soon). My understanding is that it isn't owned right now though, which is why we've started recommended minikube over that one.

Just to double check, would a "native" Linux driver for minikube work for this use case?

**Comment by ColinHebert** [comment]
Yeah I think that a native system would work. Basically the restriction is in EC2 (or other cloud solutions) you are already running in a VM, so you can't rely on a solution using virtualisation.

**Comment by dlorenc** [comment]
Cool. I'll close this out for the issue about future drivers we want to support.

#261

**Comment by Awan** [comment]
Here is Terraform code which creates an EC2 with minikube installed. https://github.com/Awan/minikube-ec2.git
