### ISSUE TITLE
Customize Hyper-V machine name

### ISSUE THREAD

**Issue by FranklinYu** [kubernetes/minikube#4261]
When Hyper-V driver is used, the virtual machine will be called `minikube`. Note that the VM is configured with bridge switch, so the domain name will be broadcasted in LAN. However, if two machines in a LAN both starts a Minikube, they will have same DNS name. It would be useful if user can specify the machine name, like

```
minikube start --hyperv-vm-name minikube-frank
```

I think this is Hyper-V specific because it’s the only Type-1 Hypervisor officially supported.

**Comment by tstromberg** [comment]
It sounds like HyperV should likely just respect the name passed in via --profile, which is intended to allow you to have multiple VM's on the same host by a given name.

I'm still surprised about other machines on a LAN seeing a minikube host by name. That seems unintentional.

**Comment by FranklinYu** [comment]
I have verified on another machine (running Ubuntu) that `minikube` is available as DNS name across the LAN. This is the expected behavior for Bridge Switch. The VM also gots an IP address in LAN (so it’s side-by-side with the “host”).

And the `--profile` worked. By the way, is there anywhere documenting *all* the command-line options? We have `minikube --help` but it would be helpful to have something online.

**Comment by tstromberg** [comment]
My preference here is that users use --profile to set the name of the VM, though I could understand if we have to add some sort of broadcast name. 

Is there a problem with both users sharing a DNS name? Is anyone actually using the DNS name?

I've opened #4271 to address the documentation bit.

**Comment by FranklinYu** [comment]
I’ll re-open this issue when I find a use-case of DNS name.
