### ISSUE TITLE
Document all "start" options on the minikube website

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4271]
So that our options are more discoverable.

**Comment by blueelvis** [comment]
Can I take this task? Where should the documentation be located?

**Comment by tstromberg** [comment]
@blueelvis - Yes! 

https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md has a start to it.  Feel free to add to it, rewrite the doc, and/or rename the file if a better name is more appropriate. I think this would be very very helpful.

**Comment by blueelvis** [comment]
@tstromberg - I will start my work on this and submit a PR shortly. I think a separate document would be best. That way, once there is a website for Minikube Documentation, it will be easy to segregate.

**Comment by tstromberg** [comment]
@blueelvis - any progress on this?

I ask because I will begin moving docs to https://minikube.sigs.k8s.io next week. Thankfully, the markdown files should not change!

**Comment by blueelvis** [comment]
@tstromberg - Yea, I should be able to submit a PR before this weekend. 

Clicking on that Docs link is giving 404. It's not fully integrated?

**Comment by medyagh** [comment]
lets make sure there is a link from old to new location, since in our Problem Advice code we URL to our docs
