### ISSUE TITLE
restart: waiting for component=kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by ljmwaugh** [kubernetes/minikube#4272]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:
minikube start
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ...
⌛  Waiting for pods: apiserver
💣  Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objects passed to appt-token-pbnl8 ==
    error: no objects pINFO: == Kubassed to apply

**The output of the `minikube logs` command**:
[minikube.log](https://github.com/kubernetes/minikube/files/3188490/minikube.log)

**The operating system version**:
Mojave 10.14.4

**Comment by tstromberg** [comment]
Do you mind running `minikube status` for me as well? I'm curious if it recovered. 

It isn't clear to me what happened yet, but you can likely workaround it by using `minikube delete`.

**Comment by ljmwaugh** [comment]
minikube status
host: Running
kubelet: Running
apiserver: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.102

**Comment by ljmwaugh** [comment]
That is after I had done a minikube stop, then minikube delete, then minikube start again.  I waited overnight then did minikube status.

**Comment by tstromberg** [comment]
Thanks! Do you mind checking if the minikube v1.1.0 release fixes this? We refactored this particular health check to be more robust. Hope it helps!

**Comment by tstromberg** [comment]
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube and run `minikube delete` to remove the previous cluster state.

If the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!

**Comment by ljmwaugh** [comment]
hi, I installed the v1.1.0 release as requested.
I did a minikube delete first to make sure I was starting fresh.
then did a minikube start, it took a very long time but eventually it crashed.  It never started successfully as you can see in the files.
I'm attaching the console output and the log output.  Please let me know if there is other information that would be helpful.
[minikube-logs.txt](https://github.com/kubernetes/minikube/files/3218805/minikube-logs.txt)
[minikube_crash_console.txt](https://github.com/kubernetes/minikube/files/3218806/minikube_crash_console.txt)

**Comment by ljmwaugh** [comment]
minikube status
host: Running
kubelet: Running
apiserver: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.104

**Comment by kaelzhan** [comment]
@ljmwaugh  I met the same problem with you, and finally I found this is a network problem, I used a vpn, so I can't route to the local k8s cluster. Maybe you can check your network too.

**Comment by ljmwaugh** [comment]
@kaelzhan thanks for the hint.  that was my problem.
