### ISSUE TITLE
delete: remove VBox.log: The process cannot access the file because it is being used by another process.

### ISSUE THREAD

**Issue by anton-haldin** [kubernetes/minikube#4286]
Hi 
It is great to use minukube. Thank you. 
But looks like sometimes minikube is not able to delete cluster on Windows 10 with VirtualBox. I think potential cause can be slow work of VirtualBox: file with logs are still in use when minikube is trying to clean up resource in file system.
Please find detail below. All steps to reproduce in attached txt file.

**The exact command to reproduce the issue**:
minikube delete

**The full output of the command that failed**:
C:\Windows\system32>minikube delete
x   Deleting "minikube" from virtualbox ...

!   Failed to delete cluster: remove C:\Users\Anton\.minikube\machines\minikube\minikube\Logs\VBox.log: The process cannot access the file because it is being used by another process.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:
C:\Windows\system32>minikube logs

!   api load: filestore: open C:\Users\Anton\.minikube\machines\minikube\config.json: The system cannot find the file specified.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**The operating system version**:
Microsoft Windows [Version 10.0.17763.475]

This issue looks like https://github.com/kubernetes/minikube/issues/4137 but I don't know shweta9651's previous commands.

Oracle VirtualBox Version 5.2.8 r121009 (Qt5.6.2)
[minikube_crash_clean.txt](https://github.com/kubernetes/minikube/files/3193724/minikube_crash_clean.txt)

**Comment by anton-haldin** [comment]
Removing or moving directory  ~/.minikube/machines/minikube helps  to return back to initial state of minikube, state after installation.

**Comment by tstromberg** [comment]
Interesting. I suspect than on Windows, you may need to run `minikube stop` before `minikube delete`. Do you mind testing this theory?

If that fixes it, we should just make that step automatic.

**Comment by halmai** [comment]
I have the same problem and tried this:

```
> minikube stop
*
X Unable to stop VM: open C:\Users\Csongor Halmai\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```
and then
```
> minikube delete
* Removing C:\Users\Csongor Halmai\.minikube\machines\minikube ...
*
X Unable to remove machine directory: remove C:\Users\Csongor Halmai\.minikube\machines\minikube\minikube\Snapshots\0113C205-19E6-4E44-9903-D0AA9C750A39.vmcx: The process cannot access the file because it is being used by another process.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```
This seems to be show-stopper for me. :(

**Comment by tstromberg** [comment]
@halmai - I've moved your issue to #7300 - as it affects a different hypervisor
