### ISSUE TITLE
error execution phase kubeconfig/admin: a kubeconfig file "/etc/kubernetes/admin.conf" exists already but has got the wrong CA cert

### ISSUE THREAD

**Issue by dineshtailor** [kubernetes/minikube#4287]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by vikaschoudhary16** [comment]
Version: 0.30.0 and 1.1.0
I am also hitting this. First time, command ran fine:
```
 minikube start --vm-driver=none --extra-config=kubelet.cgroup-driver=systemd --kubernetes-version v1.12.0 --v 5  --alsologtostderr
```
But when i retried after `minikube delete`, always getting  this error. I have tried even removing all the state:
```
rm  -rf /etc/kubernetes
rm -rf ~/.kube && rm -rf ~/.minikube && rm -rf /var/lib/minikube
```
Still no luck.

**Comment by sharifelgamal** [comment]
Looks like #2857 reported the same issue. I'm not sure if it's been fixed in the meantime.

**Comment by vikaschoudhary16** [comment]
unfortunately, [work-around/solution](https://github.com/kubernetes/minikube/issues/2857#issuecomment-393698335) suggested there, does not work for me.

Thanks a lot for replying. Looking forward for further inputs/hints.

**Comment by vikaschoudhary16** [comment]
I have figured out solution for this problem. I had to run:
```
minikube config set embed-certs true
```
NOTE: This is supported only post 0.30.0

**WHAT WAS THE ISSUE:**
kubeconfig file created by minikube was not having `client-certificate-data:` and kubeadm was expecting this to be non-empty and was failing from here
https://github.com/kubernetes/kubernetes/blob/release-1.12/cmd/kubeadm/app/phases/kubeconfig/kubeconfig.go#L271

Instead, minikube was setting `certificate-authority` in the kubeconfig.admin, which is actually file path.

By running above command, minikube initializes `certificate-authority-data:`


I am not sure why others are not facing this issue

**Comment by tstromberg** [comment]
@dineshtailor - Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
