### ISSUE TITLE
xhyve: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string

### ISSUE THREAD

**Issue by anmolbabu** [kubernetes/minikube#4291]
**The exact command to reproduce the issue**:
minikube start --vm-driver=xhyve

**The full output of the command that failed**:

minikube start --vm-driver=xhyve
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
⚠️  The xhyve driver is deprecated and support for it will be removed in a future release.
Please consider switching to the hyperkit driver, which is intended to replace the xhyve driver.
See https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver for more information.
To disable this message, run [minikube config set WantShowDriverDeprecationNotification false]
🔥  Creating xhyve VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

💣  Unable to start VM: new host: json: cannot unmarshal bool into Go struct field Driver.Virtio9p of type []string

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:
minikube logs

💣  api load: filestore: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
**The operating system version**:
Mac OS mojave 10.14.3

**Comment by ianmiell** [comment]
I get this also; it seemed to happen after an upgrade to docker-machine-driver-xhyve to 0.4.0

**Comment by ianmiell** [comment]
Workaround:

```
brew unlink docker-machine-driver-xhyve
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7310c563d662ddbe094f46f9600cad30ad3551a6/Formula/docker-machine-driver-xhyve.rb
```

**Comment by zekaguilar** [comment]
It works, thanks !

**Comment by wen-fei** [comment]
> I have VBox 6 on MacOS 10.14.5
> Another error:
> -- Starting Minishift VM ..... FAIL E0530 00:19:08.848817 9655 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.8r130520\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads". Retrying.
> Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.8r130520\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"

anyone knows how to solve this problem?

**Comment by wen-fei** [comment]
> > I have VBox 6 on MacOS 10.14.5
> > Another error:
> > -- Starting Minishift VM ..... FAIL E0530 00:19:08.848817 9655 start.go:494] Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.8r130520\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads". Retrying.
> > Error starting the VM: Error creating the VM. Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.8r130520\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"
> 
> anyone knows how to solve this problem?

see [issue213](https://github.com/machine-drivers/docker-machine-driver-xhyve/issues/213)

**Comment by AdilBNC** [comment]
> Workaround:
> 
> ```
> brew unlink docker-machine-driver-xhyve
> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7310c563d662ddbe094f46f9600cad30ad3551a6/Formula/docker-machine-driver-xhyve.rb
> ```

Do not forget:
sudo chown root:wheel /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
sudo chmod u+s /usr/local/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

**Comment by tstromberg** [comment]
Closing as there is no longer support for xhyve.

**Comment by alexmuntean** [comment]
> Workaround:
> 
> ```
> brew unlink docker-machine-driver-xhyve
> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/7310c563d662ddbe094f46f9600cad30ad3551a6/Formula/docker-machine-driver-xhyve.rb
> ```

this one works for me also. thanks buddy :*

**Comment by pnasrat** [comment]
I think xhyve is known broken eg it has been removed in minikube kubernetes/minikube#4291 and the minishift docs probably need to be updated to reflect that. 

Can you try using `minikube start --vm-driver=virtualbox` rather than xhyve.
