### ISSUE TITLE
(pre-1.0) Hung on Starting cluster components...

### ISSUE THREAD

**Issue by dalisoft** [kubernetes/minikube#4292]
Minikube hangs on `Starting cluster components...` and just does not work.
I tried with VirtualBox and Hyperkit.
With VirtualBox exits with code 1.
With Hyperkit hangs. What i can do make it work?
Or there any faster alternative?

Thanks

**The exact command to reproduce the issue**: `minikube start`

**The full output of the command that failed**:
```sh
dalisoft-MBP:~ dalisoft$ minikube start --vm-driver hyperkit
There is a newer version of minikube available (v1.0.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.0.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
Starting local Kubernetes v1.13.2 cluster...
Starting VM...
Downloading Minikube ISO
 181.48 MB / 181.48 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.13.2
Downloading kubelet v1.13.2
Finished Downloading kubeadm v1.13.2
Finished Downloading kubelet v1.13.2
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
```

**The output of the `minikube logs` command**: [Here](https://pastebin.com/cs864BZE)

**The operating system version**: macOS 10.13.6 (Latest High Sierra update)

**Comment by tstromberg** [comment]
That looks like a very old version of minikube. Do you mind running `minikube delete`, upgrading to v1.1.0, and trying again?

I also recommend installing the latest hyperkit driver from us:

`curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit \
&& sudo install -o root -g wheel -m 4755 docker-machine-driver-hyperkit /usr/local/bin/`

Let me know how this works out for you. Thank you for opening an issue!

**Comment by tstromberg** [comment]
NOTE: This is possibly a dupe of #3503

**Comment by dalisoft** [comment]
Thanks. I'll waited more than 12 hours and then it worked. Maybe this happen because of my machine. I also upgraded and becomes faster. Anyway it worked, thank you
