### ISSUE TITLE
vbox on vmware: Stuck on "Creating virtualbox VM" / Error dialing TCP: ssh: handshake failed: read tcp

### ISSUE THREAD

**Issue by harsha-nemani-reva** [kubernetes/minikube#4293]
When i start the minikube, it is always stuck at creating VM line. 
I am using VMWare on Windows 10. Hyper-V is disabled. 

**The exact command to reproduce the issue**:
sudo minikube start

**The full output of the command that failed**:
![image](https://user-images.githubusercontent.com/50824276/58007117-2fe47680-7b07-11e9-8326-ec0a84dd55a7.png)

**The output of the `minikube logs` command**:

**The operating system version**:
Ubuntu 18.04

**Comment by tstromberg** [comment]
Is VirtualBox compatible with running on top of VMware?

You may want to just try running minikube on Windows with the vmware or virtualbox drivers.

**Comment by tstromberg** [comment]
For further debugging, do you mind sharing the result of:

`minikube start --alsologtostderr -v=8'

Thanks.

**Comment by RA489** [comment]
@harsha-nemani-reva IMO you can use either vmware or virtualbox when Hyper-v is disabled.

**Comment by harsha-nemani-reva** [comment]
Hey @tstromberg.

I dont know if virtualbox is compatible to run on top of Vmware.
The below file shows the complete logs on terminal.
[https://drive.google.com/open?id=1Zt2F4s-dH1Q7Lc8v9FxMSikxrql46oz2](url)

But notable part being:

>  Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
> Found: vboxnet0
> COMMAND: /usr/bin/VBoxManage list dhcpservers
> STDOUT:
> {
> NetworkName:    HostInterfaceNetworking-vboxnet0
> IP:             192.168.99.16
> NetworkMask:    255.255.255.0
> lowerIPAddress: 192.168.99.100
> upperIPAddress: 192.168.99.254
> Enabled:        Yes
> 
> }
> STDERR:
> {
> }
> Removing orphan DHCP servers...
> COMMAND: /usr/bin/VBoxManage list hostonlyifs
> STDOUT:
> {
> Name:            vboxnet0
> GUID:            786f6276-656e-4074-8000-0a0027000000
> DHCP:            Disabled
> IPAddress:       192.168.99.1
> NetworkMask:     255.255.255.0
> IPV6Address:     
> IPV6NetworkMaskPrefixLength: 0
> HardwareAddress: 0a:00:27:00:00:00
> MediumType:      Ethernet
> Wireless:        No
> Status:          Down
> VBoxNetworkName: HostInterfaceNetworking-vboxnet0
> 
> }
> STDERR:
> {
> }
> Adding/Modifying DHCP server "192.168.99.6" with address range "192.168.99.100" - "192.168.99.254"...
> COMMAND: /usr/bin/VBoxManage list dhcpservers
> STDOUT:
> {
> NetworkName:    HostInterfaceNetworking-vboxnet0
> IP:             192.168.99.16
> NetworkMask:    255.255.255.0
> lowerIPAddress: 192.168.99.100
> upperIPAddress: 192.168.99.254
> Enabled:        Yes
> 
> }
> STDERR:
> {
> }
> COMMAND: /usr/bin/VBoxManage dhcpserver modify --netname HostInterfaceNetworking-vboxnet0 --ip 192.168.99.6 --netmask 255.255.255.0 --lowerip 192.168.99.100 --upperip 192.168.99.254 --enable
> STDOUT:
> {
> }
> STDERR:
> {
> }
> COMMAND: /usr/bin/VBoxManage modifyvm minikube --nic2 hostonly --nictype2 virtio --nicpromisc2 deny --hostonlyadapter2 vboxnet0 --cableconnected2 on
> STDOUT:
> {
> }
> STDERR:
> {
> }
> COMMAND: /usr/bin/VBoxManage modifyvm minikube --natpf1 delete ssh
> STDOUT:
> {
> }
> STDERR:
> {
> VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
> VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1872 of file VBoxManageModifyVM.cpp
> }
> COMMAND: /usr/bin/VBoxManage modifyvm minikube --natpf1 ssh,tcp,127.0.0.1,39697,,22
> STDOUT:
> {
> }
> STDERR:
> {
> }
> COMMAND: /usr/bin/VBoxManage startvm minikube --type headless
> STDOUT:
> {
> Waiting for VM "minikube" to power on...
> VM "minikube" has been successfully started.
> }
> STDERR:
> {
> }
> Checking vm logs: /home/reva/.minikube/machines/minikube/minikube/Logs/VBox.log
> Waiting for an IP...
> Getting to WaitForSSH function...
> Using SSH client type: native
> &{{{<nil> 0 [] [] []} docker [0x83b580] 0x83b550  [] 0s} 127.0.0.1 39697 <nil> <nil>}
> About to run SSH command:
> exit 0
> Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:51590->127.0.0.1:39697: read: connection reset by peer
> Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:51594->127.0.0.1:39697: read: connection reset by peer
> Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:51596->127.0.0.1:39697: read: connection reset by peer
> Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:51598->127.0.0.1:39697: read: connection reset by peer
> Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:51600->127.0.0.1:39697: read: connection reset by peer
> Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:51604->127.0.0.1:39697: read: connection reset by peer
> Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:51606->127.0.0.1:39697: read: connection reset by peer
>

**Comment by harsha-nemani-reva** [comment]
I have also tried to run it on Windows. But i still faced the similar issue.

![KubernetedError](https://user-images.githubusercontent.com/50824276/58372094-66225b80-7f36-11e9-8894-f8f2a590c159.JPG)
![KubernetesSSHError](https://user-images.githubusercontent.com/50824276/58372095-66baf200-7f36-11e9-94d0-cf9592fafd04.JPG)


Thank You.

**Comment by tstromberg** [comment]
As far as the original issue, I think VirtualBox on top of VMware is an unsupported configuration.

As far as the latter, try minikube v1.4: you no longer have to provide an external switch.

**Comment by sahilshaikh89** [comment]
I am trying the same, something like Nested Virtualization. 

After digging further, I was able to get around this same issue by using below command
$sudo minikube start --vm-driver=none
