### ISSUE TITLE
Could not read from boot medium error on OSX and Ubuntu

### ISSUE THREAD

**Issue by dastergon** [kubernetes/minikube#431]
In a clean OSX (10.11.6) environment I executed `minikube start` and the process stuck in the start phase:

    $ minikube start
    Starting local Kubernetes cluster...

I opened VirtualBox to check the status of the `minikubeVM` and I noticed the following error message:

    FATAL: Could not read from the boot medium! System halted.

minikube version: 0.7.1
VirtualBox version: 5.1.2
OSX version: 10.11.6

**Comment by dlorenc** [comment]
Sorry you had trouble. Hopefully we can help here! Could you paste/attach the output of:
`minikube start --show-libmachine-logs`
and:
`cat ~/.minikube/machines/minikubeVM/minikubeVM/Logs/VBox.log`

**Comment by dastergon** [comment]
Hi @dlorenc,

Here is the output of the executed commands:
```
$ minikube start --show-libmachine-logs
Starting local Kubernetes cluster...
Waiting for SSH to be available...
```
For the second command, I pasted the output on gist since it is too verbose:

     $ cat ~/.minikube/machines/minikubeVM/minikubeVM/Logs/VBox.log
https://gist.github.com/dastergon/5c6a19a20d0dd1efa547643969114e5f

**Comment by dadicool** [comment]
I can confirm that the issue is also present on my (completely unrelated) setup which uses the same versions reported above. If it's any help, using `--vm-driver=vmwarefusion` or `--vm-driver=xhyve` leads to the same exact failure scenario (no boot medium found). As a side note, in my case, I am running docker-machine 0.8.0.

**Comment by dpjeca** [comment]
I also meet this problem on my machine yesterday.

minikube version: 0.7.1
VirtualBox version: 5.1.2
Ubuntu version: 16.04.1

**Comment by r2d4** [comment]
Sorry you were having trouble running minikube.  From @dastergon's Vbox log it seems like virtualbox is having trouble mounting the ISO needed to boot.  

Can you run these commands and verify that those files exist?

`$ shasum ~/.minikube/cache/iso/minikube-0.5.iso` 
`$ shasum ~/.minikube/machines/minikubeVM/boot2docker.iso `

Both files should be present and the output of those commands should be
`75982c8278d02dabfbfa605d176814da34360a33`

**Comment by dadicool** [comment]
Here's what I get with minikube 0.7.1 and running in the last 5 mins :
```
MacBook-Pro:~ dali$ shasum ~/.minikube/machines/minikubeVM/boot2docker.iso
f0e6b52ce5cb1292a156052db9c8c9e9c4313ba2  /Users/dali/.minikube/machines/minikubeVM/boot2docker.iso
MacBook-Pro:~ dali$ shasum ~/.minikube/cache/iso/minikube-0.5.iso
f0e6b52ce5cb1292a156052db9c8c9e9c4313ba2  /Users/dali/.minikube/cache/iso/minikube-0.5.iso
```

this is after starting minikube with : `minikube start --vm-driver=virtualbox --show-libmachine-logs`

**Comment by r2d4** [comment]
That doesn't match any of the releases for the ISO.  Its possible that the iso download might have failed somehow - can you do a `du -h ~/.minikube/cache/iso/minikube-0.5.iso`?  It should return 36M (the size of the iso).

For a fix, you can delete the ISO and minikube will redownload a correct one (hopefully) `rm ~/.minikube/cache/iso/minikube-0.5.iso`

This is the link for the release ISO that minikube should download https://storage.googleapis.com/minikube/minikube-0.5.iso

**Comment by dadicool** [comment]
OK, that solved it for me. Somehow the minikube-0.5.iso file was corrupted (it was just 48KB). Not sure how this happened ... Thanks for helping me track this down.

**Comment by dastergon** [comment]
I can confirm that is working now that I removed the old ISO file.
