### ISSUE TITLE
More Addons

### ISSUE THREAD

**Issue by stevesloka** [kubernetes/minikube#432]
I'm trying to deploy the registry add-on, I've put the yaml files in the add-on pod path which gets picked up and works, but when I restart minikube, it seems the path is wiped and my add goes missing. 

Is there a way to keep add-ons or specify which one's get added dynamically? Happy to contribute back with some guidance.

**Comment by dlorenc** [comment]
I thought we had an issue for allowing users to configure addons, but I can't seem to find it right now. This is definitely something we want to do :)

I'm not sure the best way to integrate this into the CLI surface, what did you have in mind?

**Comment by wstrange** [comment]
I'd love to see heapster add on as well. 

I can file a seperate issue if appropriate

**Comment by stevesloka** [comment]
I like how Kubernetes on Arm does it (https://github.com/luxas/kubernetes-on-arm/tree/master/addons), but for now, let me look through code and see why my add-ons are removed. That's a good first step, then can discuss maybe the add-on thing. I could see not wanting everything turned on all the time.

**Comment by dlorenc** [comment]
I think it's just that most of the filesystem is booted as tmpfs right now so it gets wiped during a restart. We have to add individual paths to be mounted and persisted on a real disk.

Adding the add-ons directory would solve your problem, but still wouldn't be a great experience for most users.

**Comment by dlorenc** [comment]
Nice, I like the kubernetes-on-arm model too. We could combine that with the "minikube config get/set" work @r2d4 is currently working on.

**Comment by dlorenc** [comment]
cc @aaron-prindle

**Comment by stevesloka** [comment]
Ok very cool @dlorenc, if I can help out any please let me know.

**Comment by aaron-prindle** [comment]
I am working on adding configurable/custom add ons to minikube.  Right now my plan is to create a ~/.minikube/addons directory and the addons in this directory will be placed into the minikubeVM's '/etc/kubernetes/addons/' on start as the current add ons are.  Configuring the add ons will be a later step which will build on top of @r2d4 `minikube config` command and will filter the addons in this directory.  Please let me know if you have any feedback/suggestions.  Thanks.

**Comment by aaron-prindle** [comment]
Also I am considering mounting this addons directory into the vm and then having kubernetes monitor this ~/.minikube/addons directory as though it were the /etc/kubernetes/addons.  Then configuration of addons will be commands that move files in and out of this addons directory.

**Comment by aaron-prindle** [comment]
Please comment if you have addons you're interested in.

**Comment by aaron-prindle** [comment]
Closing, feel free to open up a feature request for specific addons.
