### ISSUE TITLE
Add NFS support to "minikube mount"

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4324]
"minikube mount" only supports 9pfs at the moment. It wouldn't be difficult to add NFS support, which is much faster.

On platforms where NFS is supported, it should be the default, as 9p has many issues.

**Comment by pswica** [comment]
Could I help out with this? I'm still a bit new to open source but would love to give this a shot, or at least play some part getting this feature on minikube. Any guidance would be greatly appreciated.

**Comment by teejae** [comment]
@tstromberg Do you have examples on Linux of what the NFS mount line should look like? I could give this a shot as well. I'm on a Mac, but lots of my coworkers are on Linux, and I wanna help them out.

**Comment by tstromberg** [comment]
@teejae - Linux uses `/etc/exports` - for some examples, see: http://nfs.sourceforge.net/nfs-howto/ar01s03.html

If you or anyone else implements this for macOS, that would be a great start. 

It's worth noting that the hyperkit driver has some hacky unstable support for doing NFS, but conceptually, this should be possible across hypervisors. This may help you get started:

https://github.com/kubernetes/minikube/blob/a817bffab1752e8956f68a88cf2548f2dc2932e9/pkg/drivers/hyperkit/driver.go#L428

**Comment by medyagh** [comment]
we still wanna do this, and this still a help wanted issue

**Comment by medyagh** [comment]
this is still a Wanted issue
