### ISSUE TITLE
http: TLS handshake error from 127.0.0.1:49888: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by shashankharsh** [kubernetes/minikube#4329]
Please help me to resolve this issue. Thank you!  👍 

root@ip-172-31-0-125:~# minikube start --vm-driver=none --memory 16000 --cpus 6 --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf  --bootstrapper=kubeadm --disk-size 64g
* minikube v1.1.0 on linux (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Re-using the currently running none VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.14.2 on Docker 18.06.1-ce
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
* Unable to load cached images: loading cached images: loading image /root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: stat /root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory
* Relaunching Kubernetes v1.14.2 using kubeadm ...

X Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
* Problems detected in "kube-apiserver":
  - I0523 06:05:26.694337       1 log.go:172] http: TLS handshake error from 127.0.0.1:49884: remote error: tls: bad certificate
  - I0523 06:05:26.698120       1 log.go:172] http: TLS handshake error from 127.0.0.1:49886: remote error: tls: bad certificate
  - I0523 06:05:26.703478       1 log.go:172] http: TLS handshake error from 127.0.0.1:49888: remote error: tls: bad certificate

**Comment by tstromberg** [comment]
Do you mind attaching the output of `minikube logs`? I can't quite tell what endpoint the apiserver is trying to talk to from this small excerpt.

Any chance that Docker on your system is configured to use an HTTP/HTTPS proxy?

**Comment by shashankharsh** [comment]
Thanks for gave interest in that. Actually yesterday I Resolved it! I just restarted the minikube, and yes everything works fine.
