### ISSUE TITLE
`minikube kubectl` --arguments and stdin for `apply -f -` not possible

### ISSUE THREAD

**Issue by Doqnach** [kubernetes/minikube#4333]
**The exact command to reproduce the issue**:

1. `$ minikube kubectl version --short`
2. `$ echo "foo:" | minikube kubectl apply -f -`
3. `$ echo "foo:" | minikube kubectl -- apply -f -`
4. `$ echo "foo:" | minikube kubectl apply -- -f -`
5. `$ minikube -- kubectl version --short`

**The full output of the command that failed**:

1. `Error: unknown flag: --short`
2. `Error: unknown shorthand flag: 'f' in -f`
3. `error: no objects passed to apply`
4. `error: no objects passed to apply`
5. `minikube version: v1.1.0`

**The expected output of the command that failed**:

1. Just like `minikube kubectl -- version --short`:
    ```
    Client Version: v1.11.8
    Server Version: v1.11.8 
    ```
2. Just like `echo "foo:" | kubectl apply -f -`:
    `error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`
3. Just like `echo "foo:" | kubectl apply -f -`:
    `error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`
4. Just like `echo "foo:" | kubectl apply -f -`:
    `error: error validating "STDIN": error validating data: [apiVersion not set, kind not set]; if you choose to ignore these errors, turn validation off with --validate=false`
5. Just like `minikube kubectl -- version --short`:
    ```
    Client Version: v1.11.8
    Server Version: v1.11.8 
    ```

**The output of the `minikube logs` command**:

**The operating system version**:

* MacOS
* vmdriver=hyperkit
* kubectl version v1.11.8 on v1.11.8 k8s cluster, installed via `minikube kubectl`

**Comment by afbjorklund** [comment]
You will need to use a single -- to terminate the minikube arguments, before you can start to add the ones for the kubectl

`minikube -- kubectl --version`

**Comment by hpandeycodeit** [comment]
` minikube -- kubectl --version ` is not giving me any results. Just the minikube list of commands.

**Comment by Doqnach** [comment]
```
$ minikube -- kubectl version --short
minikube version: v1.1.0
$ minikube kubectl -- version --short
Client Version: v1.11.8
Server Version: v1.11.8
```

The second command is what I expect to get but that notation doesn't work for `apply -f -`.

**Comment by GavinOsborn** [comment]
`minikube kubectl version -- --short` worked fine in this instance.
But it's not a great experience.

**Comment by Doqnach** [comment]
But it does not work for `kubectl apply -f -` so that doesn't help me much. There should be one notation that works for all of it obviously.

I think, that of my original post, version 3 would be the best option because it gives the most flexibility (e.g.: aliasing `minikube --profile some-profile-name kubectl --`). That one has the STDIN problem though, which might be a separate bug actually.

**Comment by afbjorklund** [comment]
> I think, that of my original post, version 3 would be the best option because it gives the most flexibility (e.g.: aliasing `minikube --profile some-profile-name kubectl --`). That one has the STDIN problem though, which might be a separate bug actually.

Will look into this bug, looks like an oversight:
``` go
		c := exec.Command(path, args...)
		c.Stdout = os.Stdout
		c.Stderr = os.Stderr
		if err := c.Run(); err != nil {
```
i.e. there is no "os.Stdin" passed to the command.
