### ISSUE TITLE
Failed to setup certs: rm: cannot remove '/var/lib/minikube/certs/ca.crt': Input/output error

### ISSUE THREAD

**Issue by a8765439** [kubernetes/minikube#4342]
minikube.exe start
* minikube v1.1.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Re-using the currently running virtualbox VM for "minikube" ...
* Waiting for SSH access ...
* Found network options:
  - NO_PROXY=192.168.99.100
* Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
  - env NO_PROXY=192.168.99.100
* Unable to load cached images: loading cached images: loading image C:\Users\kosaraju\.minikube\cache\images\k8s.gcr.io\pause_3.1: Docker load /tmp/pause_3.1:
command failed: docker load -i /tmp/pause_3.1
stdout:
stderr: mkdir /var/lib/docker/tmp/docker-import-966771295: input/output error
: Process exited with status 1

X Failed to setup certs: pre-copy: command failed: sudo rm -f /var/lib/minikube/certs/ca.crt
stdout:
stderr: rm: cannot remove '/var/lib/minikube/certs/ca.crt': Input/output error
: Process exited with status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

C:\Users\kosaraju\Downloads\kubernetes>minikube.exe start
* minikube v1.1.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Re-using the currently running virtualbox VM for "minikube" ...
* Waiting for SSH access ...
* Found network options:
  - NO_PROXY=192.168.99.100
* Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
  - env NO_PROXY=192.168.99.100
* Unable to load cached images: loading cached images: loading image C:\Users\kosaraju\.minikube\cache\images\k8s.gcr.io\pause_3.1: Docker load /tmp/pause_3.1:
command failed: docker load -i /tmp/pause_3.1
stdout:
stderr: mkdir /var/lib/docker/tmp/docker-import-262131182: input/output error
: Process exited with status 1

X Failed to setup certs: pre-copy: command failed: sudo rm -f /var/lib/minikube/certs/ca.crt
stdout:
stderr: rm: cannot remove '/var/lib/minikube/certs/ca.crt': Input/output error
: Process exited with status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

windows version : windows 10 home

**Comment by tstromberg** [comment]
My best guess is that the virtualbox VM disk is corrupt. Do you mind attaching the output of `minikube logs`?

I believe that `minikube delete` will fix this problem. Do you mind trying? If so, I'll make sure minikube automatically recommends that step as a solution.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
