### ISSUE TITLE
minikube_iso failed: crio-bin-1.14.1: <file> already exists and is not an object file

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4345]
As seen at https://storage.googleapis.com/minikube-builds/logs/4340/build.txt

```
/usr/bin/make -C pause
make[3]: Entering directory '/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/pause'
/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/host/bin/x86_64-minikube-linux-gnu-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2  -static -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -c -o pause.o pause.c
/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/host/bin/x86_64-minikube-linux-gnu-gcc -o ../bin/pause pause.o -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -O2  -static 
make[3]: Leaving directory '/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/pause'
go build -i  -tags "btrfs_noversion exclude_graphdriver_devicemapper libdm_no_deferred_remove exclude_graphdriver_btrfs containers_image_ostree_stub seccomp   containers_image_ostree_stub" -o bin/crio github.com/cri-o/cri-o/cmd/crio
go build github.com/cri-o/cri-o/vendor/github.com/hashicorp/golang-lru/simplelru: build output "/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/_output/pkg/linux_amd64/github.com/cri-o/cri-o/vendor/github.com/hashicorp/golang-lru/simplelru.a" already exists and is not an object file
Makefile:107: recipe for target 'bin/crio' failed
make[2]: *** [bin/crio] Error 1
make[2]: *** Waiting for unfinished jobs....
( cd conmon && /var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/bin/crio-config )
make[2]: Leaving directory '/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1'
package/pkg-generic.mk:223: recipe for target '/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/.stamp_built' failed
make[1]: *** [/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/.stamp_built] Error 2
make[1]: Leaving directory '/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot'
Makefile:123: recipe for target 'minikube_iso' failed
make: *** [minikube_iso] Error 2
Build step 'Execute shell' marked build as failure
```

**Comment by tstromberg** [comment]
Also seen at https://storage.googleapis.com/minikube-builds/logs/4321/build.txt

``
go build github.com/cri-o/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/types: build output "/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/_output/pkg/linux_amd64/github.com/cri-o/cri-o/vendor/k8s.io/kubernetes/pkg/kubelet/types.a" already exists and is not an object file
Makefile:116: recipe for target 'conmon/config.h' failed
make[2]: *** [conmon/config.h] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:107: recipe for target 'bin/crio' failed
make[2]: *** [bin/crio] Error 1
make[2]: Leaving directory '/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1'
package/pkg-generic.mk:223: recipe for target '/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/.stamp_built' failed
make[1]: *** [/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot/output/build/crio-bin-v1.14.1/.stamp_built] Error 2
make[1]: Leaving directory '/var/lib/jenkins/go/src/k8s.io/minikube/out/buildroot'
Makefile:123: recipe for target 'minikube_iso' failed
make: *** [minikube_iso] Error 2
Build step 'Execute shell' marked build as failure
```

#4340 #4321

**Comment by afbjorklund** [comment]
Apparently this happens because we are trying to run the build jobs in parallel...
There is some kind of bug in `go build -i`, that makes this fail for the dependencies.

The default will be to run the crio-bin package build with `make -j 1` instead.
That will avoid the parallellism (the default is 2 * CPU), and make the build stable.

**Comment by afbjorklund** [comment]
Hopefully this issue will be gone, once we move to cri-o 1.15 (#4703)

https://github.com/cri-o/cri-o/pull/2283
