### ISSUE TITLE
Add support for Kata containers

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4347]
Similar to the gvisor addon included in minikube, minikube should also add support for https://katacontainers.io/

The use of nested VM's might cause compatibility issues for some hypervisors, but if any incompatibilities are discovered, should can just identify those and error out. Similar to how gvisor errors out if a non-containerd runtime is requested.

Help wanted!

**Comment by tstromberg** [comment]
Related PR: #4340

**Comment by amshinde** [comment]
@priyawadhwa I see that you added support for gvisor addon, can you provide some guidance for what would be required to do the same for Kata.  
I had a look at your PR for adding gvisor support, and a lot of the setup for Kata is done with `kata-deploy` component that we have come up with. Document for setting up kata with minikube and kata-deploy  can be found here : https://github.com/kata-containers/documentation/pull/445

**Comment by tstromberg** [comment]
@priyawadhwa is on holiday this week, but will be back next week sometime. 

Also, we plan to release minikube v1.1.1 once Kubernetes v1.14.3 is available in roughly a week. This  should include #4340 which will make life easier. We're open to any and all suggestions on how to make minikube easier for Kata to work with.

**Comment by tstromberg** [comment]
@grahamwhaley @amshinde @egernst - Is there anything we can be doing from the minikube side to make it easier to support Kata? I'm really eager to see Kata get built-in and would be happy to help get the ball rolling any way that I can.

Also, if someone would like this issue to be assigned to them, just say the word. 

I'm at KubeCon Shanghai today in case any Kata folks would like to speak further in person.

**Comment by bergwolf** [comment]
@tstromberg @egernst  Sorry just saw this and Kubecon Shanghai has ended several hours ago. IIRC we need some addition to minikube's kernel config to support kata containers. @grahamwhaley has done some work enabling minikube+kata before. Could you share your steps/changes?

**Comment by grahamwhaley** [comment]
@bergwolf - kernel config was done over on #4340 - kata-deploy and kata work with minikube today - but, you have to install them yourselves. On this ticket we are discussing adding kata as a first class citizen to minikube, so it can be installed with the minikube installer, like gvisor can with minikube today.

afaiu, what we need to do is assess how near kata-deploy is to the method used for gvisor (they look similar), and get down and do the work :-)  Available engineering time is the main blocker right now - it just has not trickled up to the top of anybodies 'todo' list yet..  (it is on my list, but not at the top I'm afraid :-( )

**Comment by tstromberg** [comment]
@gramahwhaley - Thanks for the update! Please feel free to chase me down if you have any questions.

**Comment by tstromberg** [comment]
Just checking in to see if there is anything I can to do to help this feature come into fruition. Thanks!

**Comment by egernst** [comment]
@grahamwhaley - any interest in picking this up?

**Comment by grahamwhaley** [comment]
well, yes, it interests me to fix, but I'm not sure it will ever reach the top of my todo pile :-(

**Comment by grahamwhaley** [comment]
@egernst - were you trying to pick this up recently? Any updates or preliminary data?

**Comment by medyagh** [comment]
is there still interest to do this ?
@afbjorklund 
@tstromberg grahamwhaley

**Comment by afbjorklund** [comment]
@medyagh : not interested, sorry

**Comment by grahamwhaley** [comment]
iirc, the last discussion @egernst and I had centered around the fact that Kata is still developing reasonably fast, and we were mildly concerned that any direct kata-integration might rot and go stale/out of date pretty fast. If we based the integration around a pull/install of [kata-deploy](https://github.com/kata-containers/packaging/tree/master/kata-deploy) that would probably help, but then I'd really like to have minikube/kata up and running in a CI somewhere (either minikube or Kata) so we could detect any divergence and breakage before it ended up with end users...

Ultimately, the [kata minikube install guide](https://github.com/kata-containers/documentation/blob/master/install/minikube-installation-guide.md) exists today. I would really like to see a Kata/minikube CI still, as occasionally we (I) do have to go fix the integration as things move on, and I only find out if I happen to run into the issue or a user reports it.

@tstromberg - we can probably close this Issue for now - I don't think anybody has the time and resource to do the integration at present.
