### ISSUE TITLE
downloading binaries: kubeadm.sha1: unexpected EOF

### ISSUE THREAD

**Issue by philentso** [kubernetes/minikube#4357]
# Dear all, to run "minikube start" following error,please help me?

```
# minikube start
##  minikube v1.1.0 on linux (amd64)
## Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...


## Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
## E0527 12:01:39.974104    6897 start.go:384] Error caching images:  Caching images for ## kubeadm: caching images: caching image /root/.minikube/cache/images/k8s.gcr.io/coredns_1.3.1: fetching remote image: Get https://k8s.gcr.io/v2/: net/http: TLS handshake timeout
##  Unable to load cached images: loading cached images: loading image /root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: stat /root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory
##  Downloading kubeadm v1.14.2
## Downloading kubelet v1.14.2
##  X Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.14.2: failed to download: failed to download to temp file: failed to create validator: failed to create validator: failed to download checksum file: Get https://storage.googleapis.com/kubernetes-release/release/v1.14.2/bin/linux/amd64/kubeadm.sha1: unexpected EOF

## Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
```

**Comment by godzoco** [comment]
yes,i am too

minikube v1.1.0 on linux (amd64)
* using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing none VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
* Unable to load cached images: loading cached images: loading image /root/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner_v1.8.1: stat /root/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner_v1.8.1: no such file or directory
* Relaunching Kubernetes v1.14.2 using kubeadm ...

**Comment by vfrrjq** [comment]
I am experiencing exactly the same trouble...

**Comment by medyagh** [comment]
are you using a proxy by chance ? does passing the proxy to the docker-env solve the problem ? similar to this issue https://github.com/kubernetes/minikube/issues/3517#issuecomment-455117274

**Comment by philentso** [comment]
Thanks for everyone , now is ok...

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
