### ISSUE TITLE
--registry-mirror: sudo systemctl start docker: exit status 1

### ISSUE THREAD

**Issue by cwdelphi** [kubernetes/minikube#4361]
[root@instance-0pasyxpp cw]# minikube start -p cw --vm-driver=none --registry-mirror=https://registry.docker-cn.co
o   minikube v1.0.1 on linux (amd64)
:   Restarting existing none VM for "cw" ...
:   Waiting for SSH access ...
-   "cw" IP address is 192.168.0.24
-   Configuring Docker as the container runtime ...

!   Failed to enable container runtime: running command: sudo systemctl start docker: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
[root@instance-0pasyxpp cw]#

**Comment by cwdelphi** [comment]
[root@instance-0pasyxpp cw]# docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77156
 Built:             Sat May  4 02:34:58 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 02:02:43 2019
  OS/Arch:          linux/amd64
  Experimental:     false
[root@instance-0pasyxpp cw]# docker images
REPOSITORY                                                               TAG                 IMAGE ID            CREATED             SIZE
registry.cn-hangzhou.aliyuncs.com/cw2018/gobase                          0.0.2               0be7e2400edf        13 days ago         1.61GB
registry.cn-hangzhou.aliyuncs.com/cw2018/gobase                          0.0.1               ccbbb3602c92        13 days ago         1.61GB
registry.cn-hangzhou.aliyuncs.com/fc_webide/ide-agent-core               e170cef             cd26df975146        2 weeks ago         73MB
registry.cn-hangzhou.aliyuncs.com/cw2018/centos-ssh-cloud9               v1                  3145ce4c5f03        2 weeks ago         1.13GB
hub.baidubce.com/openedge/openedge-agent                                 0.1.3               dc1f39730172        2 weeks ago         16.7MB
inportb/httphot                                                          latest              590273a2152d        2 weeks ago         10.8MB
rancher/server                                                           latest              d4fb2bbe38af        3 weeks ago         1.09GB
registry.cn-hangzhou.aliyuncs.com/fc_webide/ide-agent-tunnel-connector   e170cef             69f5fcc854ee        6 weeks ago         12.6MB
aliyunfc/runtime-nodejs8                                                 build               74710be88af9        7 weeks ago         1.52GB
rancher/lb-service-haproxy                                               v0.9.11             eb4e543833f5        7 weeks ago         344MB
centos                                                                   latest              9f38484d220f        2 months ago        202MB
registry.cn-hangzhou.aliyuncs.com/fc_webide/ide-env-terminal-base        895ef32             0aeb6349f904        2 months ago        521MB
rancher/scheduler                                                        v0.8.6              fbedeaddc3e9        4 months ago        248MB
rancher/agent                                                            v1.2.11             1cc7591af4f5        10 months ago       243MB
rancher/net                                                              v0.13.17            f170c38e3763        10 months ago       311MB
rancher/dns                                                              v0.17.4             678bde0de4d2        10 months ago       249MB
rancher/healthcheck                                                      v0.3.8              ce78cf69cc0b        10 months ago       391MB
rancher/metadata                                                         v0.10.4             02104eb6e270        10 months ago       251MB
rancher/network-manager                                                  v0.7.22             13381626c510        10 months ago       256MB
dannydirect/tinyproxy                                                    latest              dd0720b7fae1        11 months ago       8.38MB
iron/go                                                                  dev                 bc624028dcfb        11 months ago       538MB
kdelfour/cloud9-docker                                                   latest              c75f6cd12329        15 months ago       848MB
iron/functions-ui                                                        0.0.2               9382f66a4ca7        16 months ago       233MB
iron/functions                                                           latest              cc5c9e99a2a7        16 months ago       120MB
iron/go                                                                  latest              ed7df0451f6c        16 months ago       4.7MB
rancher/net                                                              holder              665d9f6e8cc1        2 years ago         267MB
iron/hello                                                               latest              f4dd2a73dac8        2 years ago         12.1MB
uifd/ui-for-docker                                                       latest              965940f98fa5        2 years ago         8.1MB
registry.cn-hangzhou.aliyuncs.com/fc_webide/jq                           1.4                 784d73347673        4 years ago         6.11MB
[root@instance-0pasyxpp cw]#

**Comment by afbjorklund** [comment]
What does `sudo systemctl start docker` say ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
