### ISSUE TITLE
DOCKER_API_VERSION does not match version in VM image

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4363]
Currently we hardcode DOCKER_API_VERSION show to users who run `minikube docker-env`.

If a user starts an older VM image, we incorrectly advertise the DOCKER_API_VERSION it supports. We shouldn't hardcode the value.

The workaround we recommend at the moment is that users run `minikube delete` in order to create a newer VM version. We may also want to warn users if they start minikube from a VM where the Docker version is older than expected.

See related Skaffold bug: https://github.com/GoogleContainerTools/skaffold/issues/2187

The error users notice is:

`docker build: Error response from daemon: client version 1.39 is too new. Maximum supported API version is 1.38`

**Comment by afbjorklund** [comment]
The suggestion was to just delete the environment variable, the daemon will handle the API negotation.

**Comment by tstromberg** [comment]
I like that approach. No additional coding required!

**Comment by tstromberg** [comment]
Related: https://github.com/minishift/minishift/issues/1655
