### ISSUE TITLE
`minikube dashboard` > "Settings" gives 403 forbidden

### ISSUE THREAD

**Issue by Doqnach** [kubernetes/minikube#4367]
**The exact command to reproduce the issue**:

1. `minikube dashboard`
2. In the left menu, navigate to "Settings"

**The full output of the command that failed**:

![image](https://user-images.githubusercontent.com/25537191/58537432-2b991700-81f3-11e9-8621-e0fb2a500aa2.png)

**The operating system version**:

MacOS 10.14.5, minikube v1.1.0, cluster kubernetes v1.11.8, hyperkit

Possibly related? https://github.com/kubernetes/dashboard/issues/2787

**Comment by medyagh** [comment]
are you using a HTTP_PROXY or HTTPS_PROXY ?

**Comment by medyagh** [comment]
could you please paste the output of `minikube start` and also `minikube logs`

**Comment by tstromberg** [comment]
This sounds like https://github.com/kubernetes/dashboard/issues/2694 and/or https://github.com/kubernetes/dashboard/issues/2787

One workaround may be to `--disable-settings-authorizor=true` to the dashboard command line. If anyone tries this and it works, feel free to send a PR out.

**Comment by fenglixa** [comment]
I would like to verify it and provide PR for this ticket. Thanks

**Comment by Doqnach** [comment]
This has been released with v1.1.1, so can be closed as fixed.
