### ISSUE TITLE
How to expose NodePorts 1-65535?

### ISSUE THREAD

**Issue by fangyanping** [kubernetes/minikube#4368]
![图片](https://user-images.githubusercontent.com/35328825/58546915-f7e0e000-8238-11e9-84c8-68d8ce9c1857.png)

in fact,i did this
![图片](https://user-images.githubusercontent.com/35328825/58547050-41c9c600-8239-11e9-8fec-c025838bc971.png).

however,it didn't work

**Comment by fangyanping** [comment]
how do i expose nodeport range under 30000

**Comment by tstromberg** [comment]
I've added some documentation for this:

https://github.com/kubernetes/minikube/blob/master/docs/networking.md#increasing-the-nodeport-range

Please let me know if it helps. Thanks!
