### ISSUE TITLE
Final Logo Proposal

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#437]
We've had two different logo proposals now, and each have had some time to get votes. We've decided to take the top logo from each proposal and have one last vote. Same as last time, I'll post the two as separate comments, upvote the one you like!

**Comment by dlorenc** [comment]
**Option 2 From https://github.com/kubernetes/minikube/issues/355**
![](https://cloud.githubusercontent.com/assets/19435/16920860/9e08434a-4d0f-11e6-8908-81c62d614756.png)

**Comment by dlorenc** [comment]
**Option D From https://github.com/kubernetes/minikube/issues/176**
![](https://cloud.githubusercontent.com/assets/13485544/15856464/d75bfa8a-2cb5-11e6-96d6-979f826c2e91.png)

**Comment by martamarszal** [comment]
Hi, when are you planning to close the voting and finalise?

**Comment by dlorenc** [comment]
I'll close this out tonight.

**Comment by dlorenc** [comment]
Thanks everyone! Closing this out.

**Comment by martamarszal** [comment]
Thanks! It's great to see more and more design for opensource projects. 
Congrats to the guys from Wercker for delivering the  winning logo.
