### ISSUE TITLE
macos/vbox: The machine 'minikube' is already locked for a session (or being unlocked)

### ISSUE THREAD

**Issue by prasadram** [kubernetes/minikube#4377]
OS: MacOS 
OS Version : 10.14.5   
Minikube Version: v1.0.1
Most of the time minikube didn't worked for the second time as in every time i will do the below process to make it work
```
minikube delete
rm -f ~/.minikube
minikube start 
```
If i restart my machine or when it went to sleep then start up it will never worked for me 
with simple `minikube start` , i always had to start from scratch
And each time i used to get different errors like apiserver timed out, ...
Today i got below error if anyone knows how to solve this please let me know ?

Unable to start VM: create: creating: /usr/local/bin/VBoxManage modifyvm minikube --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 2 --memory 8192 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 on --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd failed:
VBoxManage: error: The machine 'minikube' is already locked for a session (or being unlocked)
VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 531 of file VBoxManageModifyVM.cpp

**Comment by tstromberg** [comment]
I can't speak for that particular error message, but running `rm -rf ~/.minikube` will definitely drive some hypervisors crazy. Please do not do that. `minikube delete` should be enough.

If you don't mind, can you check if upgrading minikube to v1.1.0 and virtualbox to 6.0.8 helps at all?

If not, please attach the output of: `minikube start --alsologtostderr -v=8`. Thank you for sharing!

**Comment by tstromberg** [comment]
I'm pretty sure this error occurs because VirtualBox has a VM running, but minikube does not know about it because all state was removed due to the removal of ~/.minikube.

The workaround I recommend is to use the VirtualBox UI to delete the VM, and then issue "minikube start" again.

As I mentioned before, I do not recommend ever deleting ~/.minikube, as it can leave dangling VM state.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
