### ISSUE TITLE
Add `--version` to kvm2 driver

### ISSUE THREAD

**Issue by josedonizetti** [kubernetes/minikube#4387]
Lots of the issues related to kvm2 driver are due to old versions of the driver. When a user installs minikube for the first time, the driver is installed by hand, and as the time passes the user only remembers to upgrade minikube, but not the driver itself.

By having a `--version` on the driver it would simplify the communication on reported issues because we would be able to know exactly what version of the driver is running. Also, we could use such a mechanism in minikube to report an error for the user to upgrade the driver.

I'm willing to work on this. What do you think? Does it make sense?

**Comment by tstromberg** [comment]
Yes, this would be great.

Would it be too much trouble to add it for hyperkit as well? It suffers from the same problem.

**Comment by josedonizetti** [comment]
@tstromberg No trouble at all. I’ll add it to both. Are we using specific version for it? Like 0.0.1? Or basing then o minikube version?

**Comment by tstromberg** [comment]
I recommend starting by basing the version on what minikube is at.

Eventually we will push the hyperkit driver back upstream in #3939 - but upstream is currently at v1.0.0 and we shouldn't have a problem preserving the version number when we eventually make that happen.
