### ISSUE TITLE
Migrate user docs to Hugo-based site

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4388]
The minikube docs directory has been good enough up until now, but it lacks structure and isn't localizable. 

See request for sub-project website here: https://github.com/kubernetes/org/issues/855

**Comment by tstromberg** [comment]
https://minikube.sigs.k8s.io/ is now live. The first thing to get ported will be the contrib docs, but I'm running into some issues with defining the menus properly.

**Comment by afbjorklund** [comment]
@tstromberg : it's hard to tell the _scope_ of this feature (for the 1.3.0 timeframe)

Is it just going to fix the 404, or will there be some actual content added as well ?

https://minikube.sigs.k8s.io/docs

> 404 Page Not Found
