### ISSUE TITLE
Add support for VM-free deployments using Podman

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4390]
See #4389 

Podman is not yet as popular as Docker, but it's important to keep our options open and our code base abstractions clean. This may turn out to be a popular option for CentOS/RedHat VM's.

**Comment by medyagh** [comment]
I am working on it. currently the https://github.com/kubernetes/minikube/pull/5530 is the blocker.

**Comment by tstromberg** [comment]
Still an issue in minikube v1.6. We probably won't get to it until Q2 2020.

**Comment by medyagh** [comment]
This is ready and will be merged soon
