### ISSUE TITLE
Question: How can I get the IP address of a container using kubectl ?

### ISSUE THREAD

**Issue by sanemoginr** [kubernetes/minikube#4397]
Hello,

I am running minikube v1.1.0 and have a deployment of 4 applications (containers) in 1 pod 
How can I get the IP address of each container ?

with the command :
_kubectl get pods -o wide_

I am getting the internal IP address of the pod but not of the containers inside:
NAME                 READY    STATUS    RESTARTS   AGE         IP           NODE       NOMINATED    NODE 
my-deployment   4/4       Running        4            3h94m   172.17.0.4 minikube  <none> <none>

thank you,

**Comment by tstromberg** [comment]
Containers don't have an IP address by default. You'll want to use `minikube service` or `minikube tunnel` to get endpoint information.
