### ISSUE TITLE
Does kvm2 need two networks?

### ISSUE THREAD

**Issue by josedonizetti** [kubernetes/minikube#4400]
The kvm2 driver now uses two networks by default. The default network that comes with the libvirt installation, and also creates a private one `minikube-net`. The flag `--kvm-network` supports passing a custom network that is used instead of the default one that comes with libvirt.

This puzzles me. Does minikube actually need two networks? Why does it only support a custom one for the default option, what if I wanted to use custom for the private network as well?

Those are things I'm currently investigating. Opening an issue to keep the discussion on the community and also to add whatever I learn here.

**Comment by medyagh** [comment]
@josedonizetti do we still need to investigate this ?
