### ISSUE TITLE
Way to switch cluster is wrong

### ISSUE THREAD

**Issue by umiyosh** [kubernetes/minikube#441]
The way to switch cluster described as README.md is wrong. I couldn't switch a cluster.
it should be revised as below.

https://github.com/kubernetes/minikube#kubectl

``` diff
+ kubectl config use-context minikube
- kubectl config set-context minikube
```

**Comment by dlorenc** [comment]
Thanks for the report! Would you like to send a PR to fix this? We can take care of it if you'd like.

**Comment by umiyosh** [comment]
OK. I'll send PR later.
