### ISSUE TITLE
Don't work sudo minikube dashboard

### ISSUE THREAD

**Issue by ESSch** [kubernetes/minikube#4411]
**The exact command to reproduce the issue**:
$ sudo minikube dashboard

**The full output of the command that failed**:
[sudo] password for essh: 
E0603 05:10:49.639623   18907 dashboard.go:64] Error excluding IP from proxy: IP  is blank. 

💣  Error getting machine status: state: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:
$ sudo minikube logs

💣  command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: machine in unknown state: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The operating system version**:
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide the `vm-driver` you are using ? (KVM or virtualbox or none)

and also is there a reason you are running it as sudo ?

**Comment by ESSch** [comment]
Hello. Thank you for conversation.

I fix:
1. set 8.8.8.8
2. replace 20G (default) to 5G of disk
3(!). minikube delete
4. miinikube start
5. The minikube is working.

Also, I have a problem: ImagePullBackOff
1. I run: docker login
2. I add version to image
3. docker pull nginx:1.15
4(!). minikube delete
5. minikube start
