### ISSUE TITLE
kvm2: Unable to start VM: new host: dial tcp: missing address

### ISSUE THREAD

**Issue by ngmariusz** [kubernetes/minikube#4416]
 minikube start --vm-driver kvm2                                              
😄  minikube v1.1.0 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0603 12:25:26.294796   22993 start.go:529] StartHost: new host: dial tcp: missing address

💣  Unable to start VM: new host: dial tcp: missing address

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**CONTEX**
Ubuntu 16.04

Docker version 18.09.6, build 481bc77

minikube version: v1.1.0

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ngmariusz** [comment]
--alsologtostderr -v=8                     ⏎ 
W0603 16:37:17.418572   19860 root.go:151] Error reading config file at /home/md/.minikube/config/config.json: open /home/md/.minikube/config/config.json: no such file or directory
I0603 16:37:17.418996   19860 notify.go:128] Checking for updates...
😄  minikube v1.1.0 on linux (amd64)
I0603 16:37:17.654722   19860 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso
I0603 16:37:17.655069   19860 start.go:721] Saving config:
{
    "MachineConfig": {
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso",
        "Memory": 2048,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "kvm2",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": [
            "NO_PROXY=localhost,127.0.0.0/8,::1"
        ],
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "Hidden": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.14.2",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    }
}
I0603 16:37:17.655447   19860 cache_images.go:307] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at /home/md/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1
I0603 16:37:17.655456   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/pause:3.1 at /home/md/.minikube/cache/images/k8s.gcr.io/pause_3.1
I0603 16:37:17.655579   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.14.2 at /home/md/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.14.2
I0603 16:37:17.655651   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.14.2 at /home/md/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.14.2
I0603 16:37:17.655973   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.14.2 at /home/md/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.14.2
I0603 16:37:17.656230   19860 cluster.go:76] Machine does not exist... provisioning new machine
I0603 16:37:17.656414   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at /home/md/.minikube/cache/images/k8s.gcr.io/coredns_1.3.1
I0603 16:37:17.656550   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at /home/md/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I0603 16:37:17.655450   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.14.2 at /home/md/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.14.2
I0603 16:37:17.656656   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at /home/md/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0603 16:37:17.656713   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at /home/md/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
I0603 16:37:17.656746   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at /home/md/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I0603 16:37:17.656808   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at /home/md/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
I0603 16:37:17.656836   19860 cache_images.go:307] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at /home/md/.minikube/cache/images/k8s.gcr.io/etcd_3.3.10
I0603 16:37:17.656942   19860 cluster.go:77] Provisioning machine with config: {MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso Memory:2048 CPUs:2 DiskSize:20000 VMDriver:kvm2 ContainerRuntime:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] XhyveDiskDriver:ahci-hd DockerEnv:[NO_PROXY=localhost,127.0.0.0/8,::1] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: GPU:false Hidden:false NoVTXCheck:false}
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
Found binary path at /usr/local/bin/docker-machine-driver-kvm2
Launching plugin server for driver kvm2
Plugin server listening at address 
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt-lxc.so.0: version `LIBVIRT_LXC_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_2.2.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_3.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_1.3.3' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
E0603 16:37:17.675849   19860 start.go:529] StartHost: new host: dial tcp: missing address
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
I0603 16:37:17.676772   19860 utils.go:122] non-retriable error: new host: dial tcp: missing address
W0603 16:37:17.677051   19860 exit.go:100] Unable to start VM: new host: dial tcp: missing address

**Comment by josedonizetti** [comment]
@ngmariusz can you check your installed virsh version: `virsh --version`?

**Comment by ngmariusz** [comment]
sure @josedonizetti !   
 virsh --version                                                              
1.3.1
hope that helps anyhow

**Comment by 3ZA** [comment]
@ngmariusz try thishttps://github.com/kubernetes/minikube/issues/3437#issuecomment-449408316

**Comment by afbjorklund** [comment]
This is due to #4555

**Comment by afbjorklund** [comment]
As a workaround, please use an older `docker-machine-driver-kvm2` (0.30.0)

https://github.com/kubernetes/minikube/releases/download/v0.30.0/docker-machine-driver-kvm2

**Comment by SelvamArul** [comment]
@afbjorklund Hi, I am facing a similar issue. The details are the same as #13395 and # 17864

```
uname -a
Linux flanders 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
```
kubectl version --client -ojson
{
  "clientVersion": {
    "major": "1",
    "minor": "29",
    "gitVersion": "v1.29.3",
    "gitCommit": "6813625b7cd706db5bc7388921be03071e1a492d",
    "gitTreeState": "clean",
    "buildDate": "2024-03-15T00:08:19Z",
    "goVersion": "go1.21.8",
    "compiler": "gc",
    "platform": "linux/amd64"
  },
  "kustomizeVersion": "v5.0.4-0.20230601165947-6ce0bf390ce3"
}
```
```
systemctl status docker
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: active (running) since Tue 2024-04-02 15:29:53 CEST; 1h 18min ago
     Docs: https://docs.docker.com
 Main PID: 2711 (dockerd)
    Tasks: 27
   CGroup: /system.slice/docker.service
           ├─2711 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
           └─3393 /usr/bin/docker-proxy -proto tcp -host-ip 127.0.0.1 -host-port 41043 -container-ip 172.18.0.3 -container-port 6443

Apr 02 15:29:50 flanders dockerd[2711]: time="2024-04-02T15:29:50.318393778+02:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 names
Apr 02 15:29:50 flanders dockerd[2711]: time="2024-04-02T15:29:50.318429193+02:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::884
Apr 02 15:29:50 flanders dockerd[2711]: time="2024-04-02T15:29:50.377722562+02:00" level=info msg="No non-localhost DNS nameservers are left in resolv.conf. Using default external servers: [nameserver 8.8.8.8 names
Apr 02 15:29:50 flanders dockerd[2711]: time="2024-04-02T15:29:50.377803360+02:00" level=info msg="IPv6 enabled; Adding default IPv6 external servers: [nameserver 2001:4860:4860::8888 nameserver 2001:4860:4860::884
Apr 02 15:29:53 flanders dockerd[2711]: time="2024-04-02T15:29:53.531244985+02:00" level=info msg="Loading containers: done."
Apr 02 15:29:53 flanders dockerd[2711]: time="2024-04-02T15:29:53.597120759+02:00" level=warning msg="WARNING: No swap limit support"
Apr 02 15:29:53 flanders dockerd[2711]: time="2024-04-02T15:29:53.597246091+02:00" level=info msg="Docker daemon" commit=659604f graphdriver=overlay2 version=24.0.2
Apr 02 15:29:53 flanders dockerd[2711]: time="2024-04-02T15:29:53.597690076+02:00" level=info msg="Daemon has completed initialization"
Apr 02 15:29:53 flanders dockerd[2711]: time="2024-04-02T15:29:53.679183588+02:00" level=info msg="API listen on /run/docker.sock"
Apr 02 15:29:53 flanders systemd[1]: Started Docker Application Container Engine.
```
I am attaching my [log file](https://github.com/kubernetes/minikube/files/14838642/logs.txt) for reference.
