### ISSUE TITLE
Usability: check addon status before disable.

### ISSUE THREAD

**Issue by fenglixa** [kubernetes/minikube#4417]
Usability issue. While disable an addon, should message to user the addon is not enabled, but not a disabled failed crash message as below:
 
**The exact command to reproduce the issue**:
minikube addons disable heapster

**The full output of the command that failed**:
 ✘ > ~/Documents/GitHub/minikube_fengli > > master > minikube addons disable heapster
✅  heapster was successfully disabled
 ~/Documents/GitHub/minikube_fengli > > master > minikube addons disable heapster

💣  disable failed: [disabling addon deploy/addons/heapster/influx-grafana-rc.yaml.tmpl: Process exited with status 1]
😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:

 ✘ > ~/Documents/GitHub/minikube_fengli > > master > minikube logs |tail
2019/06/03 13:28:04 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:28:34 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:29:04 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:29:34 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:30:04 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:30:34 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:31:04 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.
2019/06/03 13:31:34 Metric client health check failed: the server is currently unable to handle the request (get services heapster). Retrying in 30 seconds.

==> storage-provisioner <==

**The operating system version**:
MAC OS

**Comment by dpandhi-git** [comment]
would like to work on it
