### ISSUE TITLE
DNS Resolution not working within pod

### ISSUE THREAD

**Issue by Fabian-K** [kubernetes/minikube#442]
Hi all,

I experience an issue with the dns resolution of services. I have a service "web-app" up and running which exposes one named port "http" with the protocol "TCP". The "web-app" service is not exposed to the outside.
```json
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "web-app"
  },
  "spec": {
    "selector": {
      "service": "web-app"
    },
    "ports": [
      {
        "protocol": "TCP",
        "port": 80,
        "targetPort": 80,
        "name": "http"
      }
    ]
  }
}
```

Furthermore, I have a "gateway" service which is based on nginx and exposed to the outside. The definition is again rather simple:
```json
{
  "kind": "Service",
  "apiVersion": "v1",
  "metadata": {
    "name": "gateway"
  },
  "spec": {
    "selector": {
      "service": "gateway"
    },
    "type":"NodePort",
    "ports": [
      {
        "protocol": "TCP",
        "port": 80,
        "targetPort": 80,
        "name": "http"
      }
    ]
  }
}
```

The configuration of nginx simply proxies the incoming requests to the (internal) web-app service
```
server {
    listen       80;

    location / {
        proxy_pass http://_http._TCP.web-app.default.svc.cluster.local;
    }
}
```

With this setup, the gateway pod does not start and fails with the log entry  
```
[emerg] 1#1: host not found in upstream "_http._TCP.web-app.default.svc.cluster.local" in /etc/nginx/conf.d/default.conf:7.
```

I first assumed that somehow the configuration/dns string was wrong, however I can verify that using a busybox pod as described in https://github.com/kubernetes/kubernetes/blob/master/build/kube-dns/README.md#how-do-i-test-if-it-is-working
```
kubectl exec busybox -- nslookup _http._TCP.web-app.default.svc.cluster.local
Server:    10.0.0.10
Address 1: 10.0.0.10

Name:      _http._TCP.web-app.default.svc.cluster.local
Address 1: 10.0.0.101
```
I´m thankfull for every hint.
Thanks!

**Comment by dlorenc** [comment]
What's in your NGINX container? Just to verify, can you run the same "nslookup" command from there? What about a "curl"?

**Comment by Fabian-K** [comment]
Thanks @dlorenc for the quick reply. The gateway nginx container is nothing but the plain nginx image configured with the posted configuration. It´s sole purpose is to serve as a reverse proxy.

Unfortunately, I can only run nslookup from within the nginx container tomorrow -> I´ll update this issue. Do you also mean a curl from within the gateway container?

**Comment by dlorenc** [comment]
Yeah, an nslookup and curl from inside the gateway container (instead of a new busybox one). Let me know when you have a chance!

I ask about the container because there have been some bugs in older versions of alpine-based containers when working with Kubernetes DNS. Would you mind sharing the Dockerfile you used, so we can try to repro?

**Comment by dlorenc** [comment]
Giving to @r2d4 to try to repro once you share the Dockerfile.

**Comment by Fabian-K** [comment]
Hi,

the Dockerfile is rather simple, I only added the RUN command to have curl and nslookup.
```
FROM nginx
COPY src/main/docker/default.conf /etc/nginx/conf.d/default.conf
RUN apt-get update && apt-get install -y dnsutils curl
```
the default.conf is as already posted, however, I have to comment out the location section. Otherwise, the pod does not start (error message: "host not found in upstream...")
```
server {
    listen       80;

    location / {
        proxy_pass http://_http._TCP.web-app.default.svc.cluster.local;
    }
}
```
Here are nslookup and curl from within the gateway container
```
kubectl exec gateway-avmg7 -- nslookup _http._TCP.web-app.default.svc.cluster.local
Server:         10.0.0.10
Address:        10.0.0.10#53

_http._TCP.web-app.default.svc.cluster.local    canonical name = web-app.default.svc.cluster.local.
Name:   web-app.default.svc.cluster.local
Address: 10.0.0.38
```
```
kubectl exec gateway-avmg7 -- curl _http._TCP.web-app.default.svc.cluster.local
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: _http._TCP.web-app.default.svc.cluster.local
error: error executing remote command: error executing command in container: Error executing in Docker Container: 6
```
Interestingly, curl works for web-app.default.svc.cluster.local.
```
kubectl exec gateway-avmg7 -- curl web-app.default.svc.cluster.local
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1521  100  1521    0     0   108k      0 --:--:-- --:--:-- --:--:--  114k
<!DOCTYPE html>
<html lang="en">
<head>
  <base href="/">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
```
It however does not work if I use web-app.default.svc.cluster.local as proxy_pass. This results in a 504 gateway timeout.
```
2016/08/03 08:35:47 [error] 5#5: *7 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.17.0.1, server: , request: "GET / HTTP/1.1", upstream: "http://10.0.0.38:80/", host: "192.168.99.100:30840"
```
Let me know if you need more information or if I can try something different!

**Comment by Fabian-K** [comment]
I did a quick test and replaced nginx with apache as a reverse proxy. This works, if http://web-app.default.svc.cluster.local/ is used, however http://_http._TCP.web-app.default.svc.cluster.local/ fails with 

```Reason: DNS lookup failure for: _http._tcp.web-app.default.svc.cluster.local```

Might this be related to the fact that the protocol needs to be specified capitalized (only accepted values for kubernetes are TCP and UDP, tcp is rejected) and somehow the lookup is case sensitive?

**Comment by dlorenc** [comment]
Can you link to the documentation you found about the protocol/named port in the DNS hostnames?

**Comment by r2d4** [comment]
The only thing about named ports I found was a snippet underneath "DNS" 

> Kubernetes also supports DNS SRV (service) records for named ports. If the "my-service.my-ns" Service has a port named "http" with protocol TCP, you can do a DNS SRV query for "_http._tcp.my-service.my-ns" to discover the port number for "http".

http://kubernetes.io/docs/user-guide/services/

These unit tests might provide a little more into how these work

https://github.com/kubernetes/kubernetes/blob/v1.3.3/test/e2e/dns.go#L337
https://github.com/kubernetes/kubernetes/blob/v1.3.3/pkg/dns/dns_test.go#L248

@Fabian-K I was able to reproduce your issue on minikube just as you describe, however I haven't gotten a chance to try it on a remote kubernetes cluster.  It seems like this could be an kubernetes issue.

**Comment by Fabian-K** [comment]
I found it on the following page https://github.com/kubernetes/kubernetes/blob/master/build/kube-dns/README.md#srv-records:

```
SRV Records are created for named ports that are part of normal or Headless Services. For each named port, the SRV record would have the form _my-port-name._my-port-protocol.my-svc.my-namespace.svc.cluster.local
```

I might find time today to test it on a remote cluster... If so I´ll keep you updated!

**Comment by Fabian-K** [comment]
I just tried it wit a remote cluster on GCP (1.3.3) and it also failed. Looks like this is an kubernetes issue

**Comment by jimmidyson** [comment]
To the original nginx proxy question, SRV discovery is only supported by the licenced (non-oss) nginx plus. See https://www.nginx.com/blog/dns-service-discovery-nginx-plus/ for details.

Curl does not try to resolve SRV records AFAIK. I'd expect to be able to request only hostnames that are IP addresses or resolvable A records & CNAMEs. 

You should be able to just use the name of the service only, mysvc, or mysvc.namespace.

**Comment by Fabian-K** [comment]
@jimmidyson thanks for pointing that out! Up to now I wasn´t aware of the difference.

**Comment by jimmidyson** [comment]
@Fabian-K Are you happy to close this issue or do you still have some outstanding query?

BTW SRV records are awesome & woefully under supported IMO.

**Comment by Fabian-K** [comment]
No, thanks to all for the support!
