### ISSUE TITLE
Provide solution message for unnecessary sudo

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4420]
Running minikube with "sudo" privileges is not necessary in some cases causes issues. (such as host env vars)

We need to provide a solution message (warning) not to run minikube in sudo:

"Please don't run minikube as root or with "sudo" privileges. It isn't necessary."

**Comment by djmgit** [comment]
@medyagh I would like to work on this.
I am new to kube contribution, any hints and pointers will be of great help :)

**Comment by medyagh** [comment]
Awesome @djmgit  ! Thank you for offering to help,  yes please. 

I look forward to review your PR :)

**Comment by medyagh** [comment]
@dragon3 I suggest using golang "os/user" std lib package:
here are things u can do :

```
u, err := user.Current()
// check for errors
// check if u.Username is root , then add a console warning with a right emoji (check the start cmd for the example console warnings) 
```

**Comment by medyagh** [comment]
@djmgit one more detail is, the sudo is required for --vm-driver hyperv so the message should not warn users who are using hyperv

**Comment by djmgit** [comment]
@medyagh thanks a lot for the pointers, I will send a PR ASAP

**Comment by djmgit** [comment]
@medyagh I have submitted a PR for this. Let me know what changes need to be made.
