### ISSUE TITLE
hyperv: Failed to start docker.service: Unit docker.service is masked

### ISSUE THREAD

**Issue by shwetanshu21** [kubernetes/minikube#4425]
I ran the following command as administrator on Powershell in C:\k8s where kubectl and minikube are placed . I am getting error "Unit docker.service is masked." The memory is unset from dynamic and is fixed at 2048 MB. I tired connecting to VM minikube and unmasking the service but it did not work. 

**Command that failed**
PS C:\k8s> minikube start --kubernetes-version="v1.14.0" --vm-driver="hyperv" --hyperv-virtual-switch="OSwitch" --docker-env http_proxy="http://proxy:port/" --docker-env https_proxy="http://proxy:port/" --docker-env NO_PROXY="localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24" --v=10 --a
lsologtostderr

**The full output of the command that failed**:
[stderr =====>] :
I0605 04:47:35.926244   12732 ssh_runner.go:101] SSH: systemctl is-active --quiet service containerd
I0605 04:47:35.988246   12732 ssh_runner.go:101] SSH: systemctl is-active --quiet service crio
I0605 04:47:36.001243   12732 ssh_runner.go:101] SSH: sudo systemctl stop crio
I0605 04:47:36.239546   12732 ssh_runner.go:101] SSH: systemctl is-active --quiet service crio
I0605 04:47:36.257530   12732 ssh_runner.go:101] SSH: sudo systemctl start docker
I0605 04:47:36.273531   12732 utils.go:240] ! Failed to start docker.service: Unit docker.service is masked.
W0605 04:47:36.274530   12732 exit.go:100] Failed to enable container runtime: command failed: sudo systemctl start docker
stdout:
stderr: Failed to start docker.service: Unit docker.service is masked.
: Process exited with status 1

X Failed to enable container runtime: command failed: sudo systemctl start docker
stdout:
stderr: Failed to start docker.service: Unit docker.service is masked.
: Process exited with status 1

**The output of the `minikube logs` command**:
==> dmesg <==
[Jun 5 08:01] smpboot: 128 Processors exceeds NR_CPUS limit of 64
[  +0.000000] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[  +0.016430] * Found PM-Timer Bug on the chipset. Due to workarounds for a bug,
              * this clock source is slow. Consider trying other clock sources
[Jun 5 08:02] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +0.472097] systemd-fstab-generator[1225]: Ignoring "noauto" for root device
[  +0.006770] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:35 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000003] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +0.171554] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
[  +5.774101] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +0.442386] vboxguest: loading out-of-tree module taints kernel.
[  +0.005871] vboxguest: PCI device not found, probably running on physical hardware.
[Jun 5 08:03] systemd-fstab-generator[2534]: Ignoring "noauto" for root device
[Jun 5 08:04] systemd-fstab-generator[2904]: Ignoring "noauto" for root device
[  +7.510395] NFSD: Unable to end grace period: -110
[Jun 5 08:14] systemd-fstab-generator[3481]: Ignoring "noauto" for root device
[Jun 5 08:15] systemd-fstab-generator[3831]: Ignoring "noauto" for root device
[Jun 5 08:17] systemd-fstab-generator[3961]: Ignoring "noauto" for root device
[Jun 5 08:36] systemd-fstab-generator[4282]: Ignoring "noauto" for root device
[Jun 5 08:37] systemd-fstab-generator[4633]: Ignoring "noauto" for root device
[Jun 5 08:46] systemd-fstab-generator[5045]: Ignoring "noauto" for root device
[Jun 5 08:47] systemd-fstab-generator[5395]: Ignoring "noauto" for root device

==> kernel <==
 08:58:27 up 56 min,  1 user,  load average: 0.00, 0.01, 0.00
Linux minikube 4.15.0 #1 SMP Tue May 21 00:14:40 UTC 2019 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Wed 2019-06-05 04:02:10 UTC, end at Wed 2019-06-05 08:58:27 UTC. --
-- No entries --

*minikube ssh systemctl status docker.service output*
● docker.service
   Loaded: masked (/usr/lib/systemd/system/docker.service; masked; vendor preset
: enabled)
   Active: inactive (dead)

**The operating system version**:

Windows 10 Enterprise

**Comment by tstromberg** [comment]
I have no idea why the docker service would be masked in systemd. To my knowledge, minikube doesn't use this state, so it is very strange to me:

https://askubuntu.com/questions/710420/why-are-some-systemd-services-in-the-masked-state

This awkward state can be worked around by using `minikube delete`. Is it repeatable?

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
