### ISSUE TITLE
Process exited with status 137 from signal KILL /  io.Copy failed: EOF

### ISSUE THREAD

**Issue by urs4uall** [kubernetes/minikube#4426]
Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
* Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
* Unable to load cached images: loading cached images: loading image C:\Users\admin\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13: Docker load /tmp/k8s-dns-sidecar-amd64_1.14.13: command failed: docker load -i /tmp/k8s-dns-sidecar-amd64_1.14.13
stdout:
stderr: : Process exited with status 137 from signal KILL
* Downloading kubeadm v1.14.2
* Downloading kubelet v1.14.2
E0605 17:05:59.649754   14036 ssh_runner.go:198] io.Copy failed: EOF
E0605 17:05:59.874216   14036 ssh_runner.go:198] io.Copy failed: EOF
E0605 17:05:59.874216   14036 ssh_runner.go:198] io.Copy failed: EOF
E0605 17:05:59.874216   14036 ssh_runner.go:198] io.Copy failed: EOF
E0605 17:05:59.874216   14036 ssh_runner.go:198] io.Copy failed: EOF
E0605 17:05:59.874216   14036 ssh_runner.go:198] io.Copy failed: EOF
E0605 17:05:59.874216   14036 ssh_runner.go:198] io.Copy failed: EOF

X Failed to update cluster: downloading binaries: copying kubeadm: copy: pre-copy: NewSession: EOF

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
This was fixed in minikube v1.1.1. Please upgrade.

https://github.com/kubernetes/minikube/issues/1766
