### ISSUE TITLE
Anyone have document on how to install Kubernetes on Windows server 2012 R2 Hypervisor

### ISSUE THREAD

**Issue by sneevand** [kubernetes/minikube#4429]
Hi Guys,

We do have Windows server 2012 R2 and existing VM, they use Hyper Visor, Now i want to use HyperV on it an install Ubuntu in order to install kebernetes.

How can i achieve it?

Regards,

Navin

**Comment by medyagh** [comment]
better support for hyperV is on our roadmap, I am actually working on setting up our integration tests for windows hyperv. 

link to current doc.
https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperv-driver


so while we have some documentation, for sure we can use all the help out there for make it better.
please do share your experience by making issue

**Comment by medyagh** [comment]
@sneevand so you don't have to install ubuntu on windows to install minikube.
for hyperv you need to do the follow:
- enable hyperv (most windows machine come with hyperv enabled)
- install minikube 
- create a virtual switch as explained https://docs.docker.com/machine/drivers/hyper-v/ 
(scroll down to example with screenshots)
- start minikube by 
"minikube start --vm-driver hyperv --hyperv-virtual-switch=switch-name"

the switch name is the one you created.

**Comment by tstromberg** [comment]
As far as I know, our standard Windows installation docs should cover this case: https://kubernetes.io/docs/tasks/tools/install-minikube/
