### ISSUE TITLE
Missing file /var/db/dhcpd_leases prevents creation of new Minikube cluster on OS X

### ISSUE THREAD

**Issue by corvus-ch** [kubernetes/minikube#4435]
**The exact command to reproduce the issue**:

minikube start --disk-size 35g --memory 8 --vm-driver hyperkit

**The full output of the command that failed**:

😄  minikube v1.1.0 on darwin (amd64)
👍  minikube will upgrade the local cluster from Kubernetes 1.14.1 to 1.14.2
💿  Downloading Minikube ISO ...
 131.28 MB / 131.28 MB [============================================] 100.00% 0s
🔥  Creating hyperkit VM (CPUs=2, Memory=8MB, Disk=35000MB) ...
E0606 07:22:40.742736   68350 start.go:529] StartHost: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory

💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory
Temporary Error: open /var/db/dhcpd_leases: no such file or directory

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp :22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The operating system version**:

macOS Mojave 10.14.5

**Comment by corvus-ch** [comment]
This is another variant of the same issue as in #4437. The VM got created with 8MB of memory instead of 8192MB (8GB). The following command worked:

```
minikube start --disk-size 35g --memory 8192 --vm-driver hyperkit 
```

**Comment by sharifelgamal** [comment]
@corvus-ch Does the solution posited in #4437 help with this error as well?

**Comment by corvus-ch** [comment]
@sharifelgamal I would not call that a solution but correct usage. But yes, having some sanity check for the memory will also help to prevent this issue.

**Comment by sharifelgamal** [comment]
ok, I'll roll this issue into the other one under a more general memory sanity check heading.
