### ISSUE TITLE
Virtualbox 6 prevents usage of Minikube with xhyve

### ISSUE THREAD

**Issue by corvus-ch** [kubernetes/minikube#4436]
**The exact command to reproduce the issue**:

minikube start --disk-size 35g --memory 8192 --vm-driver xhyve

**The full output of the command that failed**:

😄  minikube v1.1.0 on darwin (amd64)
⚠️  The xhyve driver is deprecated and support for it will be removed in a future release.
Please consider switching to the hyperkit driver, which is intended to replace the xhyve driver.
See https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyperkit-driver for more information.
To disable this message, run [minikube config set WantShowDriverDeprecationNotification false]
🔥  Creating xhyve VM (CPUs=2, Memory=8192MB, Disk=35000MB) ...
E0606 07:31:25.918496   68743 start.go:529] StartHost: create: Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.8r130520\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"

💣  Unable to start VM: create: Error with pre-create check: "Virtual Box version 4 or lower will cause a kernel panicif xhyve tries to run. You are running version: 6.0.8r130520\n\n\t Please upgrade to version 5 at https://www.virtualbox.org/wiki/Downloads"

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:

💣  api load: filestore: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The operating system version**:

macOS Mojave 10.14.5

**Comment by medyagh** [comment]
@corvus-ch Thanks for filling this bug, have you confirmed the source of the problem is having virtualbox 6 ? would downgrading virtualbox to 5 solve the problem?

**Comment by corvus-ch** [comment]
Yes, downgrading to VirtualBox 5.2.30 worked.

So the actual issue is that the implementation and the wording of the output do not match. While the output suggests, that Virtualbox and newer are fine, the implementation seems to require the Virtualbox version to be equal to 5 (not having VirtualBox installed is also fine).

Is there evidence that the xhyve driver not only has issues with Virtualbox 4 but 6 too and the only version of Virtualbox which can coexist would be 5?

**Comment by medyagh** [comment]
Unfortunately we have deprecated xhyve driver and we don't have integration tests for it, if I could replicate the issue on my own machine I could investigate more, is there any reason you could not use other drivers such as hyperkit or virtualbox?

**Comment by corvus-ch** [comment]
No, nothing is preventing me from using Hyperkit or Virtualbox. I can live with the fact that xhyve can used alongside Virtualbox if it is version 5. If it is left like this, I suggest to at least change the wording in the output?

**Comment by medyagh** [comment]
I agree, we could definitely provide a better message than this. I will add this to our backlog. thank you so much for taking the time to provide details on this issue. :)

**Comment by tstromberg** [comment]
Closed because xhyve support was removed from minikube.
