### ISSUE TITLE
Add memory size sanity checking

### ISSUE THREAD

**Issue by corvus-ch** [kubernetes/minikube#4437]
**The exact command to reproduce the issue**:

minikube start --disk-size 35g --memory 8 --vm-driver virtualbox

**The full output of the command that failed**:

😄  minikube v1.1.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=8MB, Disk=35000MB) ...
^C

I exited the command after around 10 minutes.

**The output of the `minikube logs` command**:

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The operating system version**:

macOS Mojave 10.14.5

**Comment by corvus-ch** [comment]
I checked the VMs console with the Vritualbox UI.  <img width="378" alt="Screenshot 2019-06-06 at 08 08 09" src="https://user-images.githubusercontent.com/794584/59010867-16476c80-8833-11e9-9e6d-0ef5a4962ef4.png">

**Comment by medyagh** [comment]
Thank you so much for reporting this, would you mind running the start command with this option and share the output ?

minikube start --alsologtostderr -v=8

**Comment by medyagh** [comment]
I just noticed you are creating the VM with  `Memory=8MB` I think that is why it wont boot did you mean 8G ?

**Comment by medyagh** [comment]
We need a better solution message, to warn the user when the RAM is too low.
I noticed our command line option doesn't take --memory 8g  as a valid option and it expects you enter in MB.

I would be happy to review any PR that helps to give a better solution message and user experience for the user.

**Comment by corvus-ch** [comment]
Thanks for looking into this. Indeed, I intended to create the VM with 8GB and I can confirm that the following command yielded the expected result:

```
minikube start --disk-size 35g --memory 8192 --vm-driver virtualbox
```

My suggestion would be to print out a warning if the memory low or even exit early if it is ridiculously low as it was inn my case.

**Comment by blueelvis** [comment]
@medyagh - I will pick this up. Do we know what the recommended memory size is? Or what is the lowest range of memory with which minikube can run?

**Comment by afbjorklund** [comment]
Currently at least 512M is required to boot, we set 2048M for a master node.
Possibly could get away with 1024M for multinode, but not many apps then.

**Comment by afbjorklund** [comment]
The default ISO doesn't even boot with 512M, so it would need switching if so.
And 1024M is not enough to start Kubernetes successfully, so 2048M is default. 

The question is more if we are trying to catch a typo, or trying to prevent things ?
In the usage example above, we were just trying to prevent accidentally using 8M.

**Comment by tddorgtfo** [comment]
The default is 2048MB:
https://github.com/kubernetes/minikube/blob/247efdea15eba7e478da1fdaed0ac402d262fcab/pkg/minikube/constants/constants.go#L124-L125

Although a minimum disk size is maintained (2000MB), these doesn't appears to be a minimum memory size.  Perhaps the validation can be less than 3 digits, assuming 1-99MB would always be a typo.

It also would be good for it to take --memory Xg to be consistent with the behavior of -disk-size.

**Comment by afbjorklund** [comment]
> It also would be good for it to take --memory Xg to be consistent with the behavior of --disk-size.

That is what is being proposed in #4463, but there seems to be some issues with the implementation.
