### ISSUE TITLE
Ubuntu: error for minikube cache add images 

### ISSUE THREAD

**Issue by fenglixa** [kubernetes/minikube#4438]
**The exact command to reproduce the issue**:
$ minikube cache add ubuntu:16.04

**The full output of the command that failed**:
$ minikube cache add ubuntu:16.04

💣  Failed to cache and load images: Error creating new ssh host from driver: Error getting ssh host name for driver: driver does not support ssh commands

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:
None
**The operating system version**:
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04

**Comment by fenglixa** [comment]
Checked the code. Why the logic of return error directly if the driver is none?

- none.go:
```go
// GetSSHHostname returns hostname for use with ssh
func (d *Driver) GetSSHHostname() (string, error) {
	return "", fmt.Errorf("driver does not support ssh commands")   =====>>> Here
}

// GetSSHPort returns port for use with ssh
func (d *Driver) GetSSHPort() (int, error) {
	return 0, fmt.Errorf("driver does not support ssh commands")
}
```

**Comment by fenglixa** [comment]
Modified minikube code locally and setup password-less to localhost. I workarounded this issue:
```
$ ssh-copy-id -i ~/.ssh/id_rsa.pub 127.0.0.1
... ...
$ /opt/minikube# out/minikube cache add ubuntu:16.04
$ /opt/minikube# out/minikube cache list
ubuntu:16.04
```

**Comment by afbjorklund** [comment]
This can be fixed by switching runner for the none driver, run the load command locally instead of over ssh. It can also skip the copy step.

**Comment by afbjorklund** [comment]
Also note that caching is now disabled by default for the `none` driver, since the container runtime storage is persistent anyway.
