### ISSUE TITLE
Path errors on Windows setup

### ISSUE THREAD

**Issue by dmonson** [kubernetes/minikube#4445]
C:\>minikube start --vm-driver hyperv --hyperv-virtual-switch minikube --v 9999
There is a newer version of minikube available (v1.1.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.1.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
o   minikube v1.0.1 on windows (amd64)
@   Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
$   Downloading Kubernetes v1.14.1 images in the background ...
\>   Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
Creating CA: C:\minikube_home\\.minikube\certs\ca.pem
Creating client certificate: C:\minikube_home\\.minikube\certs\cert.pem
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Module -ListAvailable hyper-v).Name | Get-Unique
[stdout =====>] : Hyper-V

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("S-1-5-32-578")
[stdout =====>] : True

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive [Console]::OutputEncoding = [Text.Encoding]::UTF8; (Hyper-V\Get-VMSwitch).Name
[stdout =====>] : Default Switch
DockerNAT
minikube

[stderr =====>] :
Downloading C:\minikube_home\\.minikube\cache\boot2docker.iso from file://C:/minikube_home/.minikube/cache/iso/minikube-v1.0.1.iso...

!   Unable to start VM: create: creating: open /minikube_home/.minikube/cache/iso/minikube-v1.0.1.iso: The system cannot find the file specified.

**The output of the `minikube logs` command**:
!   command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running

**The operating system version**:
systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299

Attempted this with the new version of the binary also (v1.1.0) with the same results.  The path translation fails to preserve the drive name.

**Comment by dmonson** [comment]
Well, it appears that the relative path "/minikube_home" works from the command line, as long as the command is invoked from the drive where the path exists.  This means that running "minikube start ..." from D:\\> will have different behavior than from C:\\>, even if the ENV VAR contains MINIKUBE_HOME=C:\minikube_home.  Blame this one on the monkey sitting at my keyboard.

**Comment by blueelvis** [comment]
@dmonson - This is indeed a bug and is related to #1574 .
