### ISSUE TITLE
Prefix informational messages with the current timestamp

### ISSUE THREAD

**Issue by codeforester** [kubernetes/minikube#4447]
It is great if minikube puts a timestamp in its informational messages by default.

**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:
😄  minikube v1.1.0 on darwin (amd64)
💿  Downloading Minikube ISO ...
 131.28 MB / 131.28 MB [============================================] 100.00% 0s
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

🐳  Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
💾  Downloading kubeadm v1.14.2
💾  Downloading kubelet v1.14.2
🚜  Pulling images ...
🚀  Launching Kubernetes ...
[the last step has been hanging for a long time and I am not sure when exactly it started]

**The output of the `minikube logs` command**:
N/A

**The operating system version**:
macOS 10.14.5

**Comment by djmgit** [comment]
@tstromberg @medyagh I would love to take this up.

**Comment by afbjorklund** [comment]
I think this needs to be optional, but we _could_ write timestamps into a log file...
Alternatively we could revisit timeouts, and print some informational messages ?

**Comment by djmgit** [comment]
@afbjorklund One use case for this feature might be detecting steps which are taking abnormally large amount of time. Timestamps would help us identify which step is taking the longest time.
Also I agree that it can be present as a optional flag (like verbosity or something like that).
Printing to log is also a nice idea, but would not be printing to terminal be more explicit?

**Comment by tstromberg** [comment]
I'd rather not pollute the output by default: I don't feel that it is important to your average user unless something is broken. If you need to see timestamps, you can use the `--alsologtostderr` flag. 

As we've done a fair bit around tuning the timeouts already, I would rather see this step provide more specific feedback.

That said, we could definitely improve the documentation around the `--alsologtostderr` flag.

**Comment by tstromberg** [comment]
Closing: if you need timestamps, issue --alsologtostderr.
