### ISSUE TITLE
Missing checksums in release.json

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#445]
As detailed in https://github.com/kubernetes/minikube/blob/master/RELEASING.md#add-the-version-to-the-releasesjson-file seems like the checksums are missing from 0.7+ releases.

/cc @aaron-prindle

**Comment by aaron-prindle** [comment]
@jimmidyson 
The sha256 checksums were uploaded to GCS but they were not linked to the release though.  I have now linked them from the release and changed the checksum notes of the release to use the new checksums.  Please let me know if anything additional needs to be done, thanks!

**Comment by aaron-prindle** [comment]
Sorry I think I misunderstood originally, I have a PR for this now

**Comment by jimmidyson** [comment]
Thanks!
