### ISSUE TITLE
Virtualbox Unable to start VM: create: precreate: exit status 126  😿  

### ISSUE THREAD

**Issue by 189174944** [kubernetes/minikube#4451]
Unable to start VM: create: precreate: exit status 126

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by aidagha** [comment]
I had the same issue. I fixed it by installing Virtualbox 5.2 (https://www.virtualbox.org/wiki/Download_Old_Builds_5_2).

It seems like others also faced this issue ( for example here https://github.com/kubernetes/minikube/issues/4088)

It would be nice to have a solution message to advise the users to install the VM driver. I would be happy to make a PR for this if you agree, @medyagh @tstromberg.

**Comment by medyagh** [comment]
@189174944 could you confirm if that advice helped you?

**Comment by tstromberg** [comment]
If you run into this again, please add `-v=8 --alsologtostderr` to your command-line. It should reveal the VirtualBox failure reason.

**Comment by tstromberg** [comment]
@aidagha - I'm not convinced that a downgrade is the correct answer, but updating `err_map.go` to point users to these issues would be helpful. The root cause here is a broken VirtualBox installation.
