### ISSUE TITLE
regenerate kubeconfig

### ISSUE THREAD

**Issue by matti** [kubernetes/minikube#4452]
after `rm ~/.kube/config` how to regenerate the file without recreating the minikube machine?

**Comment by medyagh** [comment]
I am not sure if there is a way, does minikube stop and start help ? I am curious could you share why you had to delete your config file ? Is there something we could imrpoved so you don't have to delete your config file ?

**Comment by matti** [comment]
okay, `minikube start` does regenerate the file - I had just set `KUBECONFIG` wrong.

```
export KUBECONFIG=konfig
rm konfig
minikube start
# konfig is generated
```

**Comment by pires** [comment]
```
minikube update-context
```

**Comment by muthukumars** [comment]
if you have more than one cluster in minikube running, then you need to specify the -p as minikube -p {cluster name}  update-context
