### ISSUE TITLE
Power up failed (vrc=VINF_SUCCESS, rc=NS_ERROR_FAILURE (0X80004005))

### ISSUE THREAD

**Issue by stephen-newman** [kubernetes/minikube#4453]
**The exact command to reproduce the issue**:
minikube start
**The full output of the command that failed**:
😄  minikube v1.1.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.

🔄  Restarting existing virtualbox VM for "minikube" ...
E0609 20:58:02.440386    2132 start.go:529] StartHost: start: Unable to start the VM: exit status 1
Details: 00:00:00.032790 Power up failed (vrc=VINF_SUCCESS, rc=NS_ERROR_FAILURE (0X80004005))

💣  Unable to start VM: start: Unable to start the VM: exit status 1
Details: 00:00:00.032790 Power up failed (vrc=VINF_SUCCESS, rc=NS_ERROR_FAILURE (0X80004005))

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
**The output of the `minikube logs` command**:
💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:51496: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The operating system version**:
macos high sierra 10.13.6

**Comment by tstromberg** [comment]
Hey stephen. It seems like the old VM state in Virtualbox may be corrupt. Do you mind checking if `minikube delete` fixes your issue?

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!

**Comment by itsmeGaffoor** [comment]
X error provisioning host: Failed to start host: driver start: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Could not open the medium 'C:\Users\Gaffoor\.minikube\machines\minikube\disk.vmdk'.
VBoxManage.exe: error: VMDK: inconsistency between grain table and backup grain table in 'C:\Users\Gaffoor\.minikube\machines\minikube\disk.vmdk' (VERR_VD_VMDK_INVALID_HEADER).
VBoxManage.exe: error: VD: error VERR_VD_VMDK_INVALID_HEADER opening image file 'C:\Users\Gaffoor\.minikube\machines\minikube\disk.vmdk' (VERR_VD_VMDK_INVALID_HEADER)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MediumWrap, interface IMedium

Details: 00:00:00.766960 Power up failed (vrc=VINF_SUCCESS, rc=E_FAIL (0X80004005))
