### ISSUE TITLE
Add ability in Make to build specific platforms

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#4458]
**The exact command to reproduce the issue**:
`make cross`

**The operating system version**:
`Windows 10 Enterprise`

I am doing development on Windows in addition to `Bash for Windows`. As of now, running `make cross` compiles the binaries for every platform i.e. `Linux`, `Mac` & `Windows`. We need to have the ability to build for a targeted platform. For example for me, it doesn't make sense to build the Mac binaries as well while trying to build the Windows binaries to test.

**Comment by afbjorklund** [comment]
Did you try `make out/minikube-windows-amd64.exe` ?

The "cross" target is just a phony target building all of them.

``` make
.PHONY: cross
cross: out/minikube-linux-$(GOARCH) out/minikube-darwin-amd64 out/minikube-windows-amd64.exe

```

**Comment by blueelvis** [comment]
I have not tried out that but what I did is that on my local, I just edited out the required executables in `cross` and then did compilation.

I was thinking if we could add 2 more targets in addition to cross to build specific platforms only? One for Windows and another one for Mac?

**Comment by afbjorklund** [comment]
We have three make targets today:
- out/minikube-linux-amd64
- out/minikube-darwin-amd64
- out/minikube-windows-amd64.exe

Do you need shorter aliases (phony targets, like "cross"), or what is the suggestion made here ?

**Comment by blueelvis** [comment]
@afbjorklund - You got me. I would like to see target specific aliases (phony targets) as well like `make windows`, `make darwin`, `make linux`, `make all` etc. What do you think? I think it would be much easier while developing on 1 platform.

**Comment by afbjorklund** [comment]
The `all` target already exists (also builds the drivers), and I suppose we could add aliases.

``` make
linux: out/minikube-linux-$(GOARCH)
darwin: out/minikube-darwin-amd64
windows: out/minikube-windows-amd64.exe

```
