### ISSUE TITLE
kvm2: unable to set user and group to '65534:992' on <iso>: Success

### ISSUE THREAD

**Issue by sjug** [kubernetes/minikube#4467]
**The exact command to reproduce the issue**:
```
$ sudo minikube start --vm-driver kvm2
```

**The full output of the command that failed**:
```
😄  minikube v1.1.1 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0611 11:31:32.516453   27643 start.go:529] StartHost: create: Error creating machine: Error in driver during machine creation: Error creating VM: virError(Code=38, Domain=24, Message='unable to set user and group to '65534:992' on '/root/.minikube/machines/minikube/boot2docker.iso': Success')

💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: Error creating VM: virError(Code=38, Domain=24, Message='unable to set user and group to '65534:992' on '/root/.minikube/machines/minikube/boot2docker.iso': Success')

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

**The output of the `minikube logs` command**:
```
💣  command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: host is not running
```

**The operating system version**:
`Linux ryzen 5.1.7-arch1-1-custom #1 SMP PREEMPT Thu Jun 6 07:40:25 EDT 2019 x86_64 GNU/Linux`

**Comment by sjug** [comment]
Also annoyingly after it fails to create it is unable to delete...

```
[user@host path]$ sudo minikube delete
🔥  Deleting "minikube" from kvm2 ...

💣  Failed to delete cluster: destroying running domain: virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

**Comment by afbjorklund** [comment]
Why sudo ?

**Comment by sjug** [comment]
Same error occurs without `sudo`, no difference except the path.

**Comment by afbjorklund** [comment]
UID 65534 is `nobody`, so there is something wrong with the libvirt configuration.

Check /etc/libvirt/qemu.conf

```
# Whether libvirt should dynamically change file ownership
# to match the configured user/group above. Defaults to 1.
# Set to 0 to disable file ownership changes.
#dynamic_ownership = 1

```

Similar to https://bugs.archlinux.org/task/58894

**Comment by tstromberg** [comment]
FWIW, the latest kvm2 driver should handle network cleanup better. I also concur: do not use root to run minikube, it causes more problems than it's worth.

Do you mind running: `virt-host-validate` and `groups`?

**Comment by tstromberg** [comment]
Please confirm if setting `dynamic_ownership = 0` fixes the issue, as @afbjorklund suggested.

**Comment by tomncooper** [comment]
I can confirm that setting `dynamic_ownership = 0` fixes this issue for me.

**Comment by medyagh** [comment]
@sjug could you please confirm if the solution also works for you?

**Comment by tstromberg** [comment]
Closing as a workaround appears to have been found.

**Comment by BETLOG** [comment]
After some messing around I just noticed that (sans workaround) virt-manager REQUIRES the file be located in /var/lib/libvirt/images before they will not throw errors similar to OP.
As a filthy casual I like to keep my VM images in userspace.
