### ISSUE TITLE
Doc: Add documentation for security whitelist for VMWare Fusion 11 on mac  

### ISSUE THREAD

**Issue by alisondy** [kubernetes/minikube#4470]
On a fresh install of Vmware Fusion 11 Minikube, and Docker-machine vms will fail to start.
This is due to mac blocking starts
**The exact command to reproduce the issue**:
minikube start -p aaa --vm-driver=vmware -v 10  
**The full output of the command that failed**:
<img width="964" alt="Screen Shot 2019-06-12 at 5 37 11 PM" src="https://user-images.githubusercontent.com/19580905/59325869-bc660b80-8d38-11e9-9a81-d468b7e58e09.png">
**The output of the `minikube logs` command**:
n/a
**The operating system version**:
Mojave 10.14.4
**The Fix**
Security & Privacy
Clicking allow, if a is blocked from opening prompt is displayed.
If this prompt isn't displayed, create a vm using fusion, and it should fail on vmmon kernel driver not being loaded.
Then navigate to security & privacy under mac preferences, and there should be a prompt to give vmware fusion more access
**Action**
Document this under https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#vmware-unified-driver

I would do this but I'm pressed for time at this current moment.

**Comment by medyagh** [comment]
Great finding!  Thank you for taking the time to create this issue. we will definitely update our documentation.

**Comment by tstromberg** [comment]
Fusion now has it's own docs page. Do you mind clicking "Edit this page" and adding what you've discovered to the troubleshooting area?

https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

**Comment by alisondy** [comment]
Just saw this now, Will see to it

**Comment by medyagh** [comment]
@alisondy  are you still interested to do this ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
