### ISSUE TITLE
Feature Request - unset current-context after minikube stop -- only if minikube is current context

### ISSUE THREAD

**Issue by jdanlewis** [kubernetes/minikube#4476]
#4154 added unsetting the current context upon `minikube stop`. This is handy, but unexpected if current context is not minikube. Perhaps unsetting the context should only occur if the current context is still minikube?

**Comment by medyagh** [comment]
Thats a good idea ! I agree, I would be happy to review any PR that implements this feature.

**Comment by djmgit** [comment]
@medyagh I would love to work on this.
So existing current context in kube config file (the path set in KUBECONFIG variable) needs to e checked and unset only if the existing value is minikube on firing the stop command right?

**Comment by tstromberg** [comment]
I believe this can be closed now with the v1.2.0 release. Please say `/reopen` to reopen it if this is not the case.
