### ISSUE TITLE
Unable to start minikube with --extra-config 'apiserver.cors-allowed-origins=["http://*"]' on mac

### ISSUE THREAD

**Issue by jwausle** [kubernetes/minikube#4477]
**Complete cmd+output**:

```
$ minikube --vm-driver=hyperkit --extra-config 'apiserver.cors-allowed-origins=["http://*"]' -v 10 start
* minikube v1.1.1 on darwin (amd64)
* Creating hyperkit VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:57386
...
* Configuring environment for Kubernetes v1.14.3 on Docker 18.09.6
Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
Launching plugin server for driver hyperkit
Plugin server listening at address 127.0.0.1:57463
() Calling .GetVersion
Using API Version  1
() Calling .SetConfigRaw
() Calling .GetMachineName
(minikube) Calling .GetSSHHostname
(minikube) Calling .GetSSHPort
(minikube) Calling .GetSSHKeyPath
(minikube) Calling .GetSSHUsername
  - apiserver.cors-allowed-origins=["http://*"]
(minikube) Calling .GetURL
* Pulling images ...
* Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: error converting YAML to JSON: yaml: line 4: did not find expected key
: Process exited with status 1
* Launching Kubernetes ...

X Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
error converting YAML to JSON: yaml: line 4: did not find expected key

: Process exited with status 1
```

**Output minikube logs**:

[minikube-logs.txt](https://github.com/kubernetes/minikube/files/3283106/minikube-logs.txt)

**The operating system version**:

> macos 10.14.5 (mojave)

**Comment by objectiveous** [comment]
I've seen similar issues. 

minikube start --extra-config=apiserver.v=10 --vm-driver hyperkit --extra-config 'apiserver.cors-allowed-origins=["http://*"]'                    /default ⎈
😄  minikube v1.2.0 on darwin (amd64)
🔥  Creating hyperkit VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
    ▪ apiserver.v=10
    ▪ apiserver.cors-allowed-origins=["http://*"]
🚜  Pulling images ...
❌  Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: error converting YAML to JSON: yaml: line 4: did not find expected key
: Process exited with status 1
🚀  Launching Kubernetes ...

💣  Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
error converting YAML to JSON: yaml: line 4: did not find expected key

: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
I bet this issue is due to a lack of quoting when we generate the kubeadm YAML. 

The fix is likely to be adding double quotes around {{$val}} for the different kubeadm templates, such as:

https://github.com/kubernetes/minikube/blob/24ad1d82b9b49864dd03791432451e66c66522d1/pkg/minikube/bootstrapper/kubeadm/templates.go#L125

If you have a chance, give it a try and I'll be happy to review the PR. Help wanted!

**Comment by objectiveous** [comment]
It was indeed an issue w/ quotes. The following worked: 

```minikube start --extra-config=apiserver.v=10 --vm-driver hyperkit --extra-config "apiserver.cors-allowed-origins=["http://localhost:3000"]"```

Unfortunately, I'm unable to open a PR to fix this (long story).

**Comment by jwausle** [comment]
One hint regarding `http://*` allowed redirections. The asterix must escaped on cmdline (`http://\*`) 

```
minikube start --extra-config=apiserver.v=10 --vm-driver hyperkit --extra-config "apiserver.cors-allowed-origins=["http://\*"]"
```

**Comment by tstromberg** [comment]
Closing as a workaround appears to have been found.

**Comment by tstromberg** [comment]
Related: #4806

**Comment by luchaoqi** [comment]
> One hint regarding `http://*` allowed redirections.
> 
> ```
> # The asterix '*' must escaped '\'on cmdline => 'http://\*'
> minikube start \
>    --vm-driver hyperkit \
>    --extra-config "apiserver.cors-allowed-origins=["http://\*"]" 
> ```
> 
> @tstromberg
> 
> * it's possible to start  `minikube` from kubeadm-template?
> * it's possible to generate kubeadm-template from `minikube` command.

Thanks for the hint. I have been searching for a solution to access the apiserver for days and it works like a charm!
