### ISSUE TITLE
Improve integration: Add container name to busybox  

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4478]
Currently the integration test busybox container doesn't have a name,

https://github.com/kubernetes/minikube/blob/eb96756744a309bd303672f15ee992bd1ae93741/test/integration/testdata/busybox.yaml#L4

we could add a contant name to it, like this one: https://k8s.io/examples/admin/dns/busybox.yaml

```
metadata:
  name: busyboxtest
  namespace: default
spec:
  containers:
  - name: busyboxtest
```

so we don't have to have a function to look up busy box containers like this:

https://github.com/kubernetes/minikube/blob/6bc6c3fe876f55534360bc1a8aa30e1722f388ce/test/integration/cluster_dns_test.go#L64

```
func busyBoxPod(t *testing.T, c kubernetes.Interface, kr *util.KubectlRunner) string {
	if _, err := kr.RunCommand([]string{"create", "-f", filepath.Join(*testdataDir, "busybox.yaml")}); err != nil {
		t.Fatalf("creating busybox pod: %s", err)
	}
	// TODO(tstromberg): Refactor WaitForBusyboxRunning to return name of pod.
	if err := util.WaitForBusyboxRunning(t, "default"); err != nil {
		t.Fatalf("Waiting for busybox pod to be up: %v", err)
	}

	pods, err := c.CoreV1().Pods("default").List(metav1.ListOptions{LabelSelector: "integration-test=busybox"})
	if err != nil {
		t.Fatalf("list error: %v", err)
	}
	if len(pods.Items) == 0 {
		t.Fatal("Expected a busybox pod to be running")
	}
	return pods.Items[0].Name

```

**Comment by nanikjava** [comment]
@medyagh just want to check whether this is still needed ? happy to work on this.
