### ISSUE TITLE
Minikube Installer For Windows

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#449]
The initial draft of the Minikube Windows Installer is here:
https://gist.github.com/aaron-prindle/fb0c545b3fa2cc747137505de89817d7

Please let me know if you have comments on the design, how it can be improved, etc. Thanks!

**Comment by aaron-prindle** [comment]
The initial draft of the Minikube Windows Installer is here:
https://gist.github.com/aaron-prindle/fb0c545b3fa2cc747137505de89817d7

**Comment by Fabian-K** [comment]
what about checking for kubectl as well and (optionally) installing it?

**Comment by dlorenc** [comment]
Nice! Is there any way to build the msi from a non-Windows machine? Maybe we could automate it using appveyor or something?

It would be annoying to need to use several different platforms during a single release. If appveyor doesn't work, we could probably automate doing it on a Windows GCE VM.

**Comment by dlorenc** [comment]
I agree with @Fabian-K, we should attempt to bundle kubectl as well.

**Comment by rodcloutier** [comment]
I am building the msg from a Mac machine. I think it can build on Linux.
Can we close this issue based on #557 and open a new one for adding kubectl?
