### ISSUE TITLE
Same issue  iam getting

### ISSUE THREAD

**Issue by jogeswar18** [kubernetes/minikube#4496]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by jogeswar18** [comment]
Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0615 07:15:00.026376    8527 start.go:529] StartHost: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

X Unable to start VM
* Error:         [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
* Advice:        Install VirtualBox, ensure that VBoxManage is executable and in path, or select an alternative value for --vm-driver
* Documentation: https://www.virtualbox.org/wiki/Downloads
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3784
  - https://github.com/kubernetes/minikube/issues/3776

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by medyagh** [comment]
Could you please make sure if virtualbox is installed on your computer??

**Comment by ravalanup** [comment]
Can this be configured to work with Hyper-V ?

**Comment by ravalanup** [comment]
Update:
`minikube start --vm-driver="hyperv"`

This worked fine for windows 10 with hyper v

**Comment by afbjorklund** [comment]
Original issue was for VirtualBox, not Hyper-V...

But apparently @jogeswar18 sorted it out. Closing.
