### ISSUE TITLE
Minikube Installer For Mac

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#450]

**Comment by dastergon** [comment]
Could you elaborate on the installer part? Do you aim to package minikube using DMG or a formula for homebrew?

**Comment by r2d4** [comment]
I think we are just trying to support a homebrew formula for now.

Some good guys have added a homebrew cask formula already (https://github.com/caskroom/homebrew-cask/pull/23227).

You can install this by doing a 
`homebrew cask install minikube`

As far as a regular homebrew formula, the minikube build process on mac requires building localkube in a docker container, which is not trivial to do in a brew formula.  So I'm still looking into that.  You can track a previous discussion of that at https://github.com/Homebrew/homebrew-core/pull/2417

**Comment by dlorenc** [comment]
Let's get this added to our docs and release process so we keep it up to date.

**Comment by dlorenc** [comment]
Closing this out as we now have this documented.
