### ISSUE TITLE
e2e test should summerize how long each test took

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4502]
It would be nice to have a summarize of how long each test took at the end of each e2e test. for the following use cases:

-  to collect over time how long it takes to start -stop-restart minikube on different drivers. to see the impact of refactor, new features on minikube start speed
- to diagnose the integration tests that take too long, to figure out which tests took longest, without eyeballing tens of thousands of lines .

**Comment by tstromberg** [comment]
I'm not sure this is going to be terribly useful in the new parallelized world. Feel free to re-open if you disagree.
