### ISSUE TITLE
Vbox: Unable to start minikube in windows 10 1903 with virtual box

### ISSUE THREAD

**Issue by technomage** [kubernetes/minikube#4509]
**The exact command to reproduce the issue**:
minikube start --cpus=6 --memory-20000 --no-vtx-check
**The full output of the command that failed**:
C:\Users\mlatt\cog>minikube start --cpus=6 --memory=20000 --no-vtx-check
* minikube v1.1.1 on windows (amd64)
* Downloading Minikube ISO ...
 131.29 MB / 131.29 MB [============================================] 100.00% 0s
* Creating virtualbox VM (CPUs=6, Memory=20000MB, Disk=20000MB) ...
2019/06/17 09:37:19 Unable to read "C:\\Users\\mlatt\\.docker\\config.json": open C:\Users\mlatt\.docker\config.json: The system cannot find the file specified.
2019/06/17 09:37:19 No matching credentials were found, falling back on anonymous
2019/06/17 09:37:19 Unable to read "C:\\Users\\mlatt\\.docker\\config.json": open C:\Users\mlatt\.docker\config.json: The system cannot find the file specified.
2019/06/17 09:37:19 No matching credentials were found, falling back on anonymous
2019/06/17 09:37:19 Unable to read "C:\\Users\\mlatt\\.docker\\config.json": open C:\Users\mlatt\.docker\config.json: The system cannot find the file specified.
2019/06/17 09:37:19 Unable to read "C:\\Users\\mlatt\\.docker\\config.json": open C:\Users\mlatt\.docker\config.json: The system cannot find the file specified.
2019/06/17 09:37:19 No matching credentials were found, falling back on anonymous
2019/06/17 09:37:19 No matching credentials were found, falling back on anonymous
E0617 09:37:38.578432   19344 start.go:529] StartHost: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.687980 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))

X Unable to start VM: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.687980 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:

X command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**The operating system version**:
Windows 10 1903

**Comment by medyagh** [comment]
Thank you for taking the time to create this issue, I suspect this be a virtualbox network adapter issue,
do you mind pasting the output of 

```vboxmanage list -l hostonlyifs ```

**Comment by technomage** [comment]
Hyper-V was disabled, but with 1903 it enabled Windows Containers which appears to also interfere with VirtualBox.  When I disabled that as well then the VM started normally.

**Comment by JoseFdri** [comment]
@technomage  how did you disable windows containers ?

**Comment by technomage** [comment]
In add/remove feature it is a separate check box not under Hyper-V

**Comment by alok555** [comment]
Had the same problem; disabling containers solved the problem. @technomage thanks for the solution.

**Comment by Jaanesh** [comment]
C:\Software\Kubernetes>minikube.exe start
* minikube v1.1.1 on windows (amd64)
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E1111 10:27:26.426231   36008 start.go:529] StartHost: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.865831 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))

X Unable to start VM: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.865831 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by Jaanesh** [comment]
I was able to start minikube previously... but I am getting the above error suddenly now a days..
not sure what is going wrong..
Could anyone help to resolve it pleas?

**Comment by alok555** [comment]
I disabled windows containers and then it started working again fine:

![image](https://user-images.githubusercontent.com/8073013/68571597-9e294680-0463-11ea-8533-2d456d08fb90.png)

**Comment by dizzastuh** [comment]
Having the same issue, except there does not appear to be hyper-v or containers options for me (running windows 10 home edition)

![image](https://user-images.githubusercontent.com/52610852/68608987-d6d41a80-0479-11ea-88ac-49b78049096f.png)

**Comment by technomage** [comment]
dizzastuh, I am not sure home has virtualization, which is required for minikube.

**Comment by dizzastuh** [comment]
Ah, actually minikube does with with home. Issue resolved itself after a hard system reboot or two.

**Comment by alex-pi** [comment]
I'm seeing the same issue. I checked and it doesn't seem I have anything related to hyper-v enabled.

Any advice is welcome.

```
 minikube start
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
* Automatically selected the virtualbox driver
* Downloading VM boot image ...
    > minikube-v1.11.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.11.0.iso: 174.99 MiB / 174.99 MiB [] 100.00% 22.03 MiB p/s 9s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4: 526.01 MiB
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.322239 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))
* Failed to start virtualbox VM. "minikube start" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\alejanpi\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\alejanpi\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

```
PS C:\Program Files\Oracle\VirtualBox> .\VBoxManage.exe list -l hostonlyifs
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            254fd171-be44-4ec9-9cfc-1b7888bb7c6b
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::5c87:87aa:d48c:12bf
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:56
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            96894250-d559-4c8a-9166-37e99e568bbb
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::6d63:40f0:8ebb:9148
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:5c
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
```

![image](https://user-images.githubusercontent.com/1214034/85073000-9ced9400-b17f-11ea-86cc-a816e1277f91.png)

![image](https://user-images.githubusercontent.com/1214034/85073162-ea6a0100-b17f-11ea-8500-5f77c51e9aa8.png)
