### ISSUE TITLE
hyperv : Hyper-v commands have to be run as an Administrator

### ISSUE THREAD

**Issue by Raj27Borra** [kubernetes/minikube#4511]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

```
 Unable to start VM: create: precreate: Hyper-v commands have to be run as an Administrator  * Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

```
**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by medyagh** [comment]
Thanks for taking the time to create this issue, to me it sounds like you need to run your powershel as adminstrator, could you please run your powershell as admin ?

**Comment by medyagh** [comment]
I think issues like this could be handled with a better formatted error message and skip crashing with a good solution message. I would be happy to review a PR

**Comment by blueelvis** [comment]
I will pick this up and submit a PR shortly.

/assign

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by schguille** [comment]
> **The exact command to reproduce the issue**:
> 
> **The full output of the command that failed**:
> 
> ```
>  Unable to start VM: create: precreate: Hyper-v commands have to be run as an Administrator  * Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> ```
> 
> **The output of the `minikube logs` command**:
> 
> **The operating system version**:

ejecuta como administrador el powershell
