### ISSUE TITLE
Not able to start minikube on linux

### ISSUE THREAD

**Issue by rajashekarkristappa** [kubernetes/minikube#4517]
This is the error i'm getting while running minikube start

* minikube v1.1.1 on linux (amd64)
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0618 16:08:02.790131   13019 start.go:529] StartHost: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

X Unable to start VM
* Error:         [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Advice:        In some environments, this message is incorrect. Try 'minikube start --no-vtx-check'
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900

**Comment by medyagh** [comment]
Thank you for taking the time to create this issue, I am curious have you tried the advise in the minikube output ? 

```
Advice: In some environments, this message is incorrect. Try 'minikube start --no-vtx-check'
```

**Comment by naveen-marthala** [comment]
how to enable AMD-V in a machine I ssh-ed into. this is an aws ec2 machine.

**Comment by tstromberg** [comment]
For AWS2 EC2 or other virtual instances, please use `--driver=docker`.
