### ISSUE TITLE
Minukube on windows error

### ISSUE THREAD

**Issue by shashankmjain** [kubernetes/minikube#452]
Hi,
When I launch minikube on windows 8.1 via VirtualBox . The process gets stuck here,

Starting local Kubernetes cluster...
I0804 07:44:13.389326    8988 cluster.go:68] Machine exists!
I0804 07:44:13.550309    8988 cluster.go:76] Machine state:  Stopped
(minikubeVM) Check network to re-create if needed...
(minikubeVM) Waiting for an IP...
I0804 07:47:25.150275    8988 cluster.go:68] Machine exists!
I0804 07:47:25.326280    8988 cluster.go:76] Machine state:  Running
Waiting for SSH to be available...

**Comment by dlorenc** [comment]
Hey, do you mind attaching the contents of $HOME/.minikube/machines/minikubeVM/minikubeVM/Logs/VBox.log

but switch it to the Windows HOMEDIR :)

**Comment by shashankmjain** [comment]
I deleted and then tried it via git bash shell rather then windows command line. It works fine.
Not sure why it fails with windows command line

**Comment by dlorenc** [comment]
@aaron-prindle has been looking into this too.

**Comment by aaron-prindle** [comment]
It fails on Windows CLI as cmd/Powershell do not have ssh binary by default.  This causes docker machine to use the go-native ssh binary which fails on ipv6 addresses.  This has been addressed in this PR:
#625

**Comment by aaron-prindle** [comment]
Fixed with: #1141
