### ISSUE TITLE
Show information about the linux distribution running

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#4523]
When provisioning a host with libmachine, or running locally with the none driver,
it can be useful to show information about which linux distribution is running.

There is a file in `systemd`, that contains this information: `/etc/os-release`.
And libmachine already has functions to parse this and to retrieve it from host.

https://www.freedesktop.org/software/systemd/man/os-release.html

We are probably just going to use the `PRETTY_NAME` parameter, for simplicity.

Examples:

* "Provisioned with Buildroot 2018.05.3"

* "Running on Ubuntu 16.04.6 LTS"

We _could_ show the kernel version (`uname`) as well, but GOOS just says "linux".

Examples:

* Linux 4.15.0 x86_64

* Linux 4.4.0-150-generic x86_64

**Comment by Stephanies56-bullshitlistof568923** [comment]
Hello please help me figure things out

**Comment by afbjorklund** [comment]
Here is the final version:

**virtualbox**

```
😄  minikube v1.2.0 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
ℹ️  Provisioned with Buildroot 2018.05.3
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
```

**none**

```
😄  minikube v1.2.0 on linux (amd64)
🤹  Running on localhost (CPUs=4, Memory=7800MB, Disk=138379MB) ...
ℹ️  Distribution is Ubuntu 16.04.6 LTS
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.8
```

Including the info fixes.
