### ISSUE TITLE
Hyperv: This computer is running Hyper-V. VirtualBox won't boot 

### ISSUE THREAD

**Issue by swasharm** [kubernetes/minikube#4527]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:
```
Error:         [VM_BOOT_FAILED_HYPERV_ENABLED] create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
```
**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by medyagh** [comment]
Thank you for sharing your experience! 

Are you trying to start minikube on a machine with hyper-v enabled?

in that case you need to either disable hyperv on your computer or use the hyperv driver.
https://github.com/kubernetes/minikube/blob/master/docs/drivers.md

**Comment by tstromberg** [comment]
Working as intended, as Hyper-V generally does not allow other virtualization technologies.

NOTE: You may have better luck with a newer version of VirtualBox.

**Comment by filiphagan** [comment]
> Thank you for sharing your experience!
> 
> Are you trying to start minikube on a machine with hyper-v enabled?
> 
> in that case you need to either disable hyperv on your computer or use the hyperv driver.
> https://github.com/kubernetes/minikube/blob/master/docs/drivers.md

The link is not working anymore. The issue is ongoing on version 1.22 on Windows 10
