### ISSUE TITLE
hyperv: precreate: Powershell was not found in the path

### ISSUE THREAD

**Issue by muthunkl** [kubernetes/minikube#4542]
when i execute (minikube start --vm-driver=hyperv) system shows system shows 
minikube v1.1.1 on windows (amd64)
* Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0620 19:37:56.372171   16728 start.go:529] StartHost: create: precreate: Powershell was not found in the path

X Unable to start VM: create: precreate: Powershell was not found in the path

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by muthunkl** [comment]
could you please help me to resolve this

**Comment by sharifelgamal** [comment]
Could you provide the full output of `minikube logs`? It would give us more information to debug the issue. Also, make sure powershell is in your path.

**Comment by muthunkl** [comment]
Thanks Sharifelgamal,

now its working fine.

i did the below changes
i updated  Powershell path in the environment variable.

**Comment by sharifelgamal** [comment]
I'm glad it's working! I'll close out this issue.

**Comment by abhinavo1** [comment]
> Thanks Sharifelgamal,
> 
> now its working fine.
> 
> i did the below changes
> i updated Powershell path in the environment variable.
update the environement variable to which path can you please share
