### ISSUE TITLE
Trandalation file load error

### ISSUE THREAD

**Issue by djmgit** [kubernetes/minikube#4549]
**The exact command to reproduce the issue**:

Any minikube command

for example:
``` minikube profile```

All minikube commands are throwing the error :
```E0621 12:57:44.947127    1086 translate.go:80] Failed to load transalation file for [locale]: open pkg/minikube/translate/translations/[respective_locale_file].json: no such file or directory.``` before proceeding further.

Is there not a better way to deal with this error rather than displaying it with every minikube command.
**The operating system version**:
ubuntu 18.04

**Comment by djmgit** [comment]
@medyagh @afbjorklund views?

**Comment by afbjorklund** [comment]
It's actually worse than just spewing error messages, it is also failing to compile the translations into the `minikube` binary (the only thing that we are actually installing) and then looking for a random runtime file: 
`Failed to load transalation file for sv-SE: open pkg/minikube/translate/translations/sv-SE.json: no such file or directory`

Oh, and the error message has a typo.

**Comment by sharifelgamal** [comment]
I'll suppress the error, since we can't be expected to have every translation file for every locale yet. I'll add the translation files into the binary early next week.

**Comment by afbjorklund** [comment]
@sharifelgamal : Thanks, the error is gone
