### ISSUE TITLE
Insecure registry flag explanation

### ISSUE THREAD

**Issue by moondev** [kubernetes/minikube#455]
I think there needs to be more detail on how the insecure-registry flag works.

I have an insecure registry running in the cluster. It's binded to localhost:5000 via kube-proxy. I have it running behind a k8s service in the default namespace: `local-registry.default:5000`

If I start minikube with `minikube start --insecure-registy=local-registry.default:5000`, does this mean when I launch an app via the dashboard I can specify local images via `local-registry.default:5000/nginx` ? It works when I specify it in the format `localhost:5000/nginx`

**Comment by dlorenc** [comment]
Hey,

I don't think you'll be able to use the registry via a service hostname. The insecure registry flag is about telling Docker what registries it can access. Internal service DNS only works for components that run inside Kubernetes AFAIK.

**Comment by moondev** [comment]
Thanks @dlorenc that makes sense.
