### ISSUE TITLE
Windows 7 Error restarting cluster for RBAC and kubeadm

### ISSUE THREAD

**Issue by caleb-delta** [kubernetes/minikube#4554]
Hi all, I am trying to start minikube on a Windows 7 machine in RBAC mode as I am working through a tutorial.

In the tutorial they pass this command
``
minikube start --extra-config=controller-manager.ClusterSigningCertFile="/var/lib/localkube/certs/ca.crt" --extra-config=controller-manager.ClusterSigningKeyFile="/var/lib/localkube/certs/ca.kwy" --extra-config=apiserver.Authorization.Mode=RBAC
``

As I am on windows I assumed I might be able to change the paths to the files below.

Without the extra-config parameters everything works fine. 

``
minikube start --extra-config=controller-manager.ClusterSigningCertFile="C:\Users\myuser\.minikube\certs\ca.pem" --extra-config=controller-manager.ClusterSigningKeyFile="C:\Users\myuser\.minikube\certs\key.pem" --extra-config=apiserver.Authorization.Mode=RBAC
``
 Unfortunately it seems to always seem to throw the error below. 

``
X Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml
stdout:
stderr: error converting YAML to JSON: yaml: line 9: did not find expected hexdecimal number
: Process exited with status 1
``

**Comment by tstromberg** [comment]
I suspect that this tutorial is very very old: some of these flags haven't been available in minikube for over a year now. I think you should just be able to use `minikube start`. I highly encourage you to also be on a recent release of minikube if you are not already (v1.2.0). 

As far as the strange error: the paths given reference points within a Linux VM, so leave them as /. \ is a special way to represent hexademical numbers in strings. Hope this helps!
