### ISSUE TITLE
Failed to generate config: unknown runtime type: "rkt"

### ISSUE THREAD

**Issue by yoursmanish** [kubernetes/minikube#4561]
C:\users\nuser>minikube start --network-plugin=cni --enable-default-cni --container-runtime=rkt
* minikube v1.1.1 on windows (amd64)

X Failed to generate config: unknown runtime type: "rkt"

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by afbjorklund** [comment]
Support for rkt has been removed, both from kubernetes and from minikube.

**Comment by tstromberg** [comment]
As @afbjorklund mentioned, rkt support was deprecated in Kubernetes v1.10.0, and thus support was removed in minikube v1.0.0. You can still download v0.35.0 if you need to simulate a legacy rkt cluster.
