### ISSUE TITLE
kvm2 driver: Allow use of storage pools (to allow storing disks on ZFS)

### ISSUE THREAD

**Issue by ivucica** [kubernetes/minikube#4564]
[Currently](https://github.com/kubernetes/minikube/blob/2d85a7ffbcd0545e2777a802894fcc924d197c3c/pkg/minikube/drivers/kvm2/driver.go) the kvm2 driver uses an unconfigurable file path inside the `MINIKUBE_HOME` as the persistent storage.

Please consider allowing the use of libvirt storage pools. This would allow use of ZFS zvol block devices as the storage backend for Minikube. [Example of setting up ZFS zvols for libvirt](http://empt1e.blogspot.com/2014/08/zfs-support-in-libvirt.html).

**Comment by tstromberg** [comment]
Seems reasonable. PR's welcome!

**Comment by nanikjava** [comment]
Shouldn't this be possible by just setting the MINIKUBE_HOME as the mounted path of the zfs pool ?

**Comment by medyagh** [comment]
I would be happy to review a PR that will implement this feature

**Comment by bjd2385** [comment]
Can this not be re-opened? Would be happy to work on this.

**Comment by bjd2385** [comment]
I've written a hacky work-around bash script that migrates the disk to your storage pool and updates the templates -

https://github.com/bjd2385/minikube/blob/06e0307a8364950458ed66d7caf68aa92c46586a/scripts/start-new.sh

Works for now, but it'd be so much better if this were implemented in minikube.
