### ISSUE TITLE
delete operation should delete profiles/<profile> folder rather than only delete config.json file

### ISSUE THREAD

**Issue by perrywang** [kubernetes/minikube#4570]
**Problem**
delete operation should delete whole folder profiles/\<profile\>
**The exact command to reproduce the issue**:
execute minikube delete, only profiles/\<profile\>/config.json get deleted and an empty folder profiles/\<profile\> left.

**Comment by tstromberg** [comment]
That sounds fully reasonable. I'd be happy to review any PR that makes it happen.

`cmd/minikube/cmd/delete.go` is the file that requires an update. After it deletes the profile, it should calculate the directory and attempt to remove it.

**Comment by fenglixa** [comment]
I would like to provide PR for this issue. Thanks @tstromberg @perrywang

**Comment by LuChenjing** [comment]
As complementary,
For minikube vm driver "none" in Linux, the whole folder profiles/<profile> will be deleted after executing "minikube delete",
but for minikube vm driver "virtualbox" in Windows, it won't be deleted, and also the config.json file inside. Only the "disk.vmdk" and <profile> folder in machines/profile/ will be removed.

**Comment by kumarom** [comment]
@medyagh shouldn't we also cleanup stale context/user/cluster from `~/.kube/config` ? Or is it already taken care of..
