### ISSUE TITLE
current-context "" PS1 N/A:N/A after minikube stop

### ISSUE THREAD

**Issue by den-is** [kubernetes/minikube#4577]
**The exact command to reproduce the issue**:
`minikube stop`

**The operating system version**:
linux/macos

Stopping minikube resets `.kube/config` `current-context: ""`

This is how it looks when you use [kube-ps1](https://github.com/jonmosco/kube-ps1) terminal addon:
```
~
(⎈ |N/A:N/A) ❯
```

Maybe it is possible to make `minikube` remember previous context in his `~/.minikube/xxx` and switch back to it automatically after stop ?

**Comment by medyagh** [comment]
Thank you for creating this issue, we have an open PR that will address this issue. https://github.com/kubernetes/minikube/pull/4485
