### ISSUE TITLE
Update ingress-nginx to latest release

### ISSUE THREAD

**Issue by dimara** [kubernetes/minikube#4578]
Minikube currently uses [ingress-nginx 0.23.0](https://github.com/kubernetes/minikube/blob/master/deploy/addons/ingress/ingress-dp.yaml.tmpl#L90). In this release the `x-forwarded-prefix`  annotation is broken (see https://github.com/kubernetes/ingress-nginx/issues/3733). This should be fixed with `0.24.0` (see https://github.com/kubernetes/ingress-nginx/pull/3786).

The above fix is not backwards compatible and requires modifying the annotation, i.e., pass the actual prefix instead of a boolean "true", but I guess this is better than not working at all, right?
 
Is there any reason not to update ingress-nginx to the latest release, i.e., [0.24.1](
https://github.com/kubernetes/ingress-nginx/releases/tag/nginx-0.24.1)?

**Comment by medyagh** [comment]
I don't see any reason not to upgrade. I would be happy to review any PR that fixes this.

**Comment by medyagh** [comment]
@minikube-bot OK to test
