### ISSUE TITLE
Windows: Driver "virtualbox" not found, because of misnamed .exe file.

### ISSUE THREAD

**Issue by abourget** [kubernetes/minikube#458]
Folks, I had the same issue saying:

```
Driver "virtualbox" not found. Do you have the plugin binary accessible in your PATH?
```

(same as cited in https://github.com/kubernetes/minikube/issues/28)

It turns our that the binary must be named `minikube.exe` and _not_ `minikube` as cited here: https://github.com/kubernetes/minikube/releases/tag/v0.7.1

When doing `exec.LookPath` [here](https://github.com/docker/machine/blob/master/libmachine/drivers/plugin/localbinary/plugin.go#L115), it seems it won't find itself if not `.exe`.

I guess we should change the release notes not to confuse more people.

**Comment by aaron-prindle** [comment]
Thank you very much for pointing this out.  I just updated all releases that have Windows (v0.7.1 and v0.7.0) with the instruction to rename the `minikube.exe`

**Comment by dlorenc** [comment]
I think this is fixed now, closing.
