### ISSUE TITLE
Better solution message when service doesn't exists

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4599]
Currently if user tries to get a service that doesn't exist we crash and ask users to create an issue for this  crash, it is better to advise them to make sure the service they are requesting been deployed.

```
$ minikube service -p p1 web2 --url

💣  Error opening service: Could not find finalized endpoint being pointed to by web2: Temporary Error: Error getting service web2: services "web2" not found
Temporary Error: Error getting service web2: services "web2" not found
Temporary Error: Error getting service web2: services "web2" not found
Temporary Error: Error getting service web2: services "web2" not found

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

I recommend using our `problem` package. https://github.com/kubernetes/minikube/blob/master/pkg/minikube/problem/err_map.go

**Comment by aidagha** [comment]
I am interested in taking this issue. This is gonna be my first issue if you guide me.
