### ISSUE TITLE
Remove localkube dep on weave

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#46]

**Comment by ethernetdan** [comment]
This can be down by:
* removing the script downloading and running weave 
* removing [this](https://github.com/kubernetes/minikube/blob/9ee08289c35662c3eccf09ba33ae057ffe34abb2/pkg/localkube/kubelet.go#L55) line.

I've tested this configuration and it seems to work

**Comment by dlorenc** [comment]
Working on this in my auth branch, but it could be separated.
https://github.com/dlorenc/minikube/tree/auth

Hope to have a PR ready for review later today.

**Comment by dlorenc** [comment]
Closed with #48
