### ISSUE TITLE
Etcd is not properly stopped.

### ISSUE THREAD

**Issue by Random-Liu** [kubernetes/minikube#460]
When stopping etcd, it tries to close all client listeners: https://github.com/kubernetes/minikube/blob/32e4c9d26b761231e986a374c66e568b18e3391f/pkg/localkube/etcd.go#L122.

However, the client listeners are not set when starting etcd: https://github.com/kubernetes/minikube/blob/32e4c9d26b761231e986a374c66e568b18e3391f/pkg/localkube/etcd.go#L98

**Comment by dlorenc** [comment]
Thanks for the report! I'll take this one.
