### ISSUE TITLE
[Feature Request] Minikube should read lowercase http_proxy too

### ISSUE THREAD

**Issue by dfang** [kubernetes/minikube#4600]
**The exact command to reproduce the issue**:
`minikube start`

**The full output of the command that failed**:

not failed, this is for better usability,  for many reasons, users in china must use proxy to pull image from gcr.io ....

currently most applications(curl, wget, git etc) read lowercase http_proxy env, or read both lowercase and uppercase, maybe minikube should support read lowercase http_proxy too if HTTP_PROXY not set but http_proxy is set ....

related issue: https://github.com/kubernetes/minikube/issues/2453

**The operating system version**:

macOS 10.14.5

minikube 1.2.0

**Comment by medyagh** [comment]
Thank you for reporting this issue, I will make sure this is resolved.

**Comment by dfang** [comment]
@medyagh Thanks for your quick response,

i think these issues (https://github.com/kubernetes/minikube/issues/4167, https://github.com/kubernetes/minikube/issues/4594) is related to usability too, 

because proxy, dns, registry mirrors have impact on pulling images, that is usability,  i really heard many people complains that. There are so many issues about pulling images failed, hyperkit: tcp: lookup k8s.gcr.io read: connection refused .... i'm also always struggling on this from last year, sometimes i made it work, sometimes didn't ... and minikube updates... anyway many bad experiences on minikube, switched to docker for mac for a while, now switched back as minikube have load balancer and multi-profile support, so i wish minikube team could improve usability ...

let me know if you need any logs for diagnosis
