### ISSUE TITLE
Minikube connection to internal registry is refused

### ISSUE THREAD

**Issue by kameshsampath** [kubernetes/minikube#4604]
When I try to push images to internal registry from container (build via Tekton piplines) I get a connection refused error. This is working well with minikube v1.1.1.

**The exact command to reproduce the issue**:
Following https://github.com/kameshsampath/minikube-helpers/tree/master/registry/README.adoc.

**The full output of the command that failed**:
```[build-greeter-jvm : buildah-build-push] Head http://dev.local/v2/rhdevelopers/pipeline-greeter/blobs/sha256:9ce2ac72ea3a3f426d08fe7ed892b6983f6ded93b9f82d8f87b8083760f26bec: dial tcp 10.111.212.82:80: connect: connection refused```

**The output of the `minikube logs` command**:

When I inspected registry logs I got this 

```registry-p8bmz registry 10.1.0.20 - - [25/Jun/2019:08:54:32 +0000] "HEAD /v2/rhdevelopers/pipeline-greeter/blobs/sha256:49d9522d5abfe1bf7e9646b02e1125fec6376add018a3a1a9a5ab875a3e52b68 HTTP/1.1" 404 157 "" "Buildah/1.7"```

**The operating system version**:
- `minikube version: v1.2.0`
- `macOS Mojave 10.14.5`
- vm-driver: `hyperkit` or `virtualbox`

Related: https://github.com/kubernetes/minikube/issues/4553

**Comment by castlemilk** [comment]
I've found the issue gets resolved if you remove the `registry-proxy`. when you enable the registry addon, it creates a `Service` which is loadbalancing across both the `registry-proxy` and the `registry`. Configuration is here: https://github.com/kubernetes/minikube/blob/master/deploy/addons/registry/

**Comment by kameshsampath** [comment]
thanks @castlemilk - I suspected the same let me try deleting the daemonset

**Comment by tstromberg** [comment]
I can't tell from #4627 - do we think this issue has been fixed now?

If not, what is required to do so?

**Comment by kumarom** [comment]
@tstromberg I think #4627 resolves this issue as well..

**Comment by castlemilk** [comment]
I was experiencing the exact same issue with Tekton, the merged changes in https://github.com/kubernetes/minikube/pull/4639, should hopefully resolve this and ensure testing validates connectivity from outside the minikube cluster (on port 5000) as well as internal access to the registry (on port 80)

**Comment by kumarom** [comment]
@tstromberg @castlemilk @kameshsampath and others, I think #4805 should fix this issue.

**Comment by kameshsampath** [comment]
Thanks all for fixing this looking for the next release of minikube to check this out

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicolaferraro** [comment]
Deleting the daemonset isn't really a workaround, as it gets recreated by the addon. Does anyone know a proper workaround until the fix gets released?

**Comment by kameshsampath** [comment]
Nicola Staying with 1.1.1 ;)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicolaferraro** [comment]
> Nicola Staying with 1.1.1 ;) Get Outlook for iOS<https://aka.ms/o0ukef>
> […](#)
> ________________________________ From: Nicola Ferraro <notifications@github.com> Sent: Tuesday, July 30, 2019 6:10:05 AM To: kubernetes/minikube <minikube@noreply.github.com> Cc: Kamesh Sampath <kamesh.sampath@hotmail.com>; Mention <mention@noreply.github.com> Subject: Re: [kubernetes/minikube] Minikube connection to internal registry is refused (#4604) Deleting the daemonset isn't really a workaround, as it gets recreated by the addon. Does anyone know a proper workaround until the fix gets released? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkubernetes%2Fminikube%2Fissues%2F4604%3Femail_source%3Dnotifications%26email_token%3DAAHHMIPV7LWIQAXSDDCEONDQB5TD3A5CNFSM4H3OMJVKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3CE4MQ%23issuecomment-516181554&data=02%7C01%7C%7Cbeb646916787401cc31008d7147182d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637000350064089960&sdata=1uQHUprTmgrLuBglGg9RoHhkMNEPFkMuNopUAl1njUw%3D&reserved=0>, or mute the thread<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHHMIKRRUZVLT3FIBTTOGLQB5TD3ANCNFSM4H3OMJVA&data=02%7C01%7C%7Cbeb646916787401cc31008d7147182d8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637000350064109976&sdata=EXGLxZ2WEB9ZmWe7pMANSk6gp7gP95k%2BOaWMl6ahoII%3D&reserved=0>.

That's a good idea ;)

**Comment by tstromberg** [comment]
Has anyone tested this with v1.3.1? I'm curious if this issue can be closed.

**Comment by kameshsampath** [comment]
Am doing some work with 1.3 this week will let you all know if it works.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tstromberg** [comment]
Any luck confirming whether or not this issue still exists with v1.3.1?

**Comment by kameshsampath** [comment]
@tstromberg  - still same issue :(  , if you can deploy the demo https://github.com/kameshsampath/pipeline-helloworld after enabling https://github.com/kameshsampath/minikube-helpers/registry you will see it just times out at the stage of pushing the image to local registry. I tried 1.3.1, 1.2.0 both same result. Works as usual with 1.1.1

**Comment by castlemilk** [comment]
Not sure about those repos, but I can successfully make requests to the internal registry now via say: `curl http://registry.kube-system`.

Try setting your Tekton `PipelineResource` as follows:

```yaml
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: helloworld-image
spec:
  type: image
  params: 
  - name: url
    value: "registry.kube-system:80/tutorial/helloworld"
```

**Comment by kameshsampath** [comment]
@castlemilk  ah thats a good tip . I was simply aliasing the same via my helper.

**Comment by Javatar81** [comment]
@castlemilk I checked your example with Minikube 1.3.1  (registry add-on enabled and registry-proxy active) and Tekton 0.6.0. It worked and uses the registry service. It is important setting port 80 in the url (it does not work without setting any port) because this matches the registry service port.

**Comment by kameshsampath** [comment]
My registry helper was to avoid those port spec via alisases, but dont know why they do not work on 1.3; need to revisit soon to fix if any issues.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by tstromberg** [comment]
I can't tell from the comments - was there a resolution found here?

**Comment by kameshsampath** [comment]
@castlemilk - were able to use the image without setting insecure-regsitry in minkube start ?
when run the command like ` kubectl run greeter --image=registry.kube-system:80/rhdevelopers/knative-tutorial-greeter` I get image pull backoff and describing the pod I get the error 

```
Events:
  Type     Reason     Age        From               Message
  ----     ------     ----       ----               -------
  Normal   Scheduled  <unknown>  default-scheduler  Successfully assigned knativetutorial/greeter-78bbb96d8d-4xfk4 to minikube
  Normal   Pulling    11s        kubelet, minikube  Pulling image "registry.kube-system:80/rhdevelopers/knative-tutorial-greeter"
  Warning  Failed     11s        kubelet, minikube  Failed to pull image "registry.kube-system:80/rhdevelopers/knative-tutorial-greeter": rpc error: code = Unknown desc = Error response from daemon: Get https://registry.kube-system:80/v2/: dial tcp: lookup registry.kube-system on 192.168.64.1:53: no such host
  Warning  Failed     11s        kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    11s        kubelet, minikube  Back-off pulling image "registry.kube-system:80/rhdevelopers/knative-tutorial-greeter"
  Warning  Failed     11s        kubelet, minikube  Error: ImagePullBackOff
```

**Comment by kameshsampath** [comment]
@tstromberg  @castlemilk  - I am able to run with `localhost:5000/<image-name>` but when using `registry-kubesystem:80/<image-name>` result in lookup errors :(.

**Comment by kameshsampath** [comment]
@tstromberg - I feel I still need to use my registry helper https://github.com/kameshsampath/minikube-helpers/tree/master/registry to make it resolve the `registry.kube-system` dns name to go to `registry.kube-system.svc.cluster.local`. It works with vm-driver `virtualbox`

**Comment by medyagh** [comment]
@kameshsampath  have you tried with other drivers? could you tell me what your helper does, is there any way we could integrate into minikube?

**Comment by kameshsampath** [comment]
@medyagh  - i see that my helper consistently working with 1.4.0 with both hyperkit and virtualbox. 

This is what my helper does 

1. Define a list of dns names (via configmap) that you wish to you use for internal registry e.g. dev.local, example.com 
2. Run a daemonset to add dns names to `/etc/hosts` of the node matching the `CLUSTER-IP` of registry in `kube-system` that was enabled via addons
3. Finally patch the coredns to resolve the dns names to registry.kube-system.cluster.local address 

After these 3 you can now push and pull  to the internal registry using the custom domain names. 

>  is there any way we could integrate into minikube?

I was thinking to make this an `addon`, so we can easily enable/disable this ?

**Comment by medyagh** [comment]
@kameshsampath  that is a good idea ! please feel free to make a PR for it !

**Comment by medyagh** [comment]
@kameshsampath  do you still have interests to make a PR for this ?

**Comment by kameshsampath** [comment]
Yes I am interested, since am bit busy with other priorities its taking sometime to push it back.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kameshsampath** [comment]
@medyagh  - I have the initial draft for the addon, lets discuss this addon in new issue for clarity

**Comment by tstromberg** [comment]
@kameshsampath - PR looks good, but could use a quick README file so that users understand what it is actually doing.

**Comment by kameshsampath** [comment]
@tstromberg  - thinking where is the right place to add that, just in the addons folder ?

I also got another question on whats the best practice to do the following while disabling the addon:

1.  I patch the coreDNS CM,  wondering if there is way I could do a merge like kubectl does so that if we disable addon the update is reversed ? 

2. The /etc/hosts files get updated for entries, just thinking that we need to remove them while disabling

**Comment by kameshsampath** [comment]
@tstromberg  - updates done on the PR.  thanks

**Comment by kameshsampath** [comment]
@tstromberg  - I think this issue has popped up again with 1.8.2,  after applying the `registry-aliases` addon or https://github.com/kubernetes/minikube/tree/master/deploy/addons/registry-aliases, then tying to push image from within a pod fails with 404 :(. Any thoughts ?

**Comment by tstromberg** [comment]
No thoughts, but a 404 does sound like a very different than "connection refused".

**Comment by tstromberg** [comment]
Anyone still running into this with minikube v1.10.x?

**Comment by kameshsampath** [comment]
I am not having that issue anymore

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sharifelgamal** [comment]
OK, looks like this is safe to close. Please reopen if the issue return.
