### ISSUE TITLE
wip: hyperv: Powershell was not found in the path

### ISSUE THREAD

**Issue by purushothamb11** [kubernetes/minikube#4606]
I am installing kubernetes in windows 10 with HyperV as VM-Drive, but when running minikube start it shows error unable to start vm, can any one help me in running minikube.
 
![kubeerror](https://user-images.githubusercontent.com/26902669/60176280-82fec700-9833-11e9-9e32-97e166f6561e.JPG)

**Comment by sharifelgamal** [comment]
Make sure Powershell is in your PATH. It's required to start minikube with HyperV.

**Comment by tstromberg** [comment]
I think the error is pretty clear here, but we could have a better solution message. Marking it as such.

**Comment by blueelvis** [comment]
I wonder how is it possible that Powershell is not in PATH on the system. I wonder if there is something wrong with the system because Powershell by default is always in Path...
