### ISSUE TITLE
certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error

### ISSUE THREAD

**Issue by vraj4** [kubernetes/minikube#4613]
Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap

: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
 output: [init] Using Kubernetes version: v1.15.0
[preflight] Running pre-flight checks
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[WARNING Hostname]: hostname "minikube" could not be reached
	[WARNING Hostname]: hostname "minikube": lookup minikube on 127.0.0.53:53: server misbehaving
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/var/lib/minikube/certs/"
[certs] Using existing front-proxy-ca certificate authority
[certs] Using existing front-proxy-client certificate and key on disk
[certs] Using existing etcd/ca certificate authority
[certs] Using existing etcd/server certificate and key on disk
[certs] Using existing etcd/healthcheck-client certificate and key on disk
[certs] Using existing apiserver-etcd-client certificate and key on disk
[certs] Using existing etcd/peer certificate and key on disk
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error
: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
.: exit status 1

**Comment by sharifelgamal** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

The exact command-lines used, so that we may replicate the issue
The full output of the command that failed
The full output of the "minikube logs" command
Which operating system version was used
This will help us isolate the problem further. Thank you!

**Comment by vraj4** [comment]
I was using Ubuntu 18.04 virtual machine using Virtual box. The minikube cluster was working fine unless I had an issue with kubectl. Started throwing an error everytime when I try to run kubectl, I see this error:
root@vikhna:~# kubectl get pod
The connection to the server 10.0.2.15:8443 was refused - did you specify the right host or port?
Wiped off the VM and did a clean install of Ubuntu 18.04. Then I see this issue,
root@vikhna:/home/vikhna# minikube start --vm-driver=none
😄  minikube v1.2.0 on linux (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing none VM for "minikube" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
root@vikhna:/home/vikhna# minikube delete
🔄  Uninstalling Kubernetes v1.15.0 using kubeadm ...
🔥  Deleting "minikube" from none ...
💔  The "minikube" cluster has been deleted.
root@vikhna:/home/vikhna# minikube start --vm-driver=none
😄  minikube v1.2.0 on linux (amd64)
🔥  Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🚜  Pulling images ...
🚀  Launching Kubernetes ... 

💣  Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap

: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
 output: [init] Using Kubernetes version: v1.15.0
[preflight] Running pre-flight checks
	[WARNING Swap]: running with swap on is not supported. Please disable swap
	[WARNING Hostname]: hostname "minikube" could not be reached
	[WARNING Hostname]: hostname "minikube": lookup minikube on 127.0.0.53:53: server misbehaving
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/var/lib/minikube/certs/"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [minikube localhost] and IPs [10.0.2.15 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [minikube localhost] and IPs [10.0.2.15 127.0.0.1 ::1]
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.
[kubelet-check] It seems like the kubelet isn't running or healthy.
[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
.: exit status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new


Below the full output of minikube logs:
root@vikhna:~# minikube logs
==> dmesg <==
[Jun26 18:51] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[  +7.107683] systemd[1]: Configuration file /lib/systemd/system/kubelet.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
[  +0.032470] systemd[1]: Configuration file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.
[  +9.377855] vgdrvHeartbeatInit: Setting up heartbeat to trigger every 2000 milliseconds
[  +0.000352] vboxguest: misc device minor 55, IRQ 20, I/O port d040, MMIO at 00000000f1400000 (size 0x400000)
[  +2.623711] [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send log
[  +0.001095] [drm:vmw_host_log [vmwgfx]] *ERROR* Failed to send log
[Jun26 18:52] kauditd_printk_skb: 22 callbacks suppressed
[ +20.609338] vboxvideo: module is from the staging directory, the quality is unknown, you have been warned.
[  +0.917268] 22:52:42.592851 main     VBoxService 6.0.8 r130520 (verbosity: 0) linux.amd64 (May 13 2019 15:50:07) release log
              22:52:42.592862 main     Log opened 2019-06-26T22:52:42.592023000Z
[  +0.000071] 22:52:42.592977 main     OS Product: Linux
[  +0.000043] 22:52:42.593022 main     OS Release: 4.18.0-24-generic
[  +0.000043] 22:52:42.593065 main     OS Version: #25~18.04.1-Ubuntu SMP Thu Jun 20 11:13:08 UTC 2019
[  +0.000062] 22:52:42.593108 main     Executable: /opt/VBoxGuestAdditions-6.0.8/sbin/VBoxService
              22:52:42.593110 main     Process ID: 1658
              22:52:42.593112 main     Package type: LINUX_64BITS_GENERIC
[  +0.002474] 22:52:42.595594 main     6.0.8 r130520 started. Verbose level = 0
[  +0.001128] 22:52:42.596720 main     vbglR3GuestCtrlDetectPeekGetCancelSupport: Supported (#1)
[  +0.043626] 22:52:42.640326 main     Error: Failed to become guest control master: VERR_VERSION_MISMATCH
[  +0.000217] 22:52:42.640562 main     Error: Service 'control' failed to initialize: VERR_VERSION_MISMATCH
[  +0.000656] 22:52:42.640692 main     Session 0 is about to close ...
[  +0.000051] 22:52:42.641273 main     Stopping all guest processes ...
[  +0.000130] 22:52:42.641407 main     Closing all guest files ...
[  +0.000046] 22:52:42.641457 main     Ended.
[Jun26 18:53] [drm:vmw_sou_crtc_page_flip [vmwgfx]] *ERROR* Page flip error -16.

==> kernel <==
 03:25:30 up  8:34,  1 user,  load average: 0.04, 0.08, 0.13
Linux vikhna 4.18.0-24-generic #25~18.04.1-Ubuntu SMP Thu Jun 20 11:13:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Wed 2019-06-26 16:34:40 EDT, end at Thu 2019-06-27 03:25:30 EDT. --
Jun 27 03:25:01 vikhna systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2990.
Jun 27 03:25:01 vikhna systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 27 03:25:01 vikhna systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 27 03:25:01 vikhna kubelet[32014]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:01 vikhna kubelet[32014]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:01 vikhna kubelet[32014]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:01 vikhna kubelet[32014]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:01 vikhna kubelet[32014]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:01 vikhna kubelet[32014]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:01 vikhna kubelet[32014]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:01 vikhna kubelet[32014]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:01 vikhna kubelet[32014]: I0627 03:25:01.240123   32014 server.go:425] Version: v1.15.0
Jun 27 03:25:01 vikhna kubelet[32014]: I0627 03:25:01.240693   32014 plugins.go:103] No cloud provider specified.
Jun 27 03:25:01 vikhna kubelet[32014]: F0627 03:25:01.240972   32014 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jun 27 03:25:01 vikhna systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 27 03:25:01 vikhna systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 27 03:25:11 vikhna systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 27 03:25:11 vikhna systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2991.
Jun 27 03:25:11 vikhna systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 27 03:25:11 vikhna systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 27 03:25:11 vikhna kubelet[32064]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:11 vikhna kubelet[32064]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:11 vikhna kubelet[32064]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:11 vikhna kubelet[32064]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:11 vikhna kubelet[32064]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:11 vikhna kubelet[32064]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:11 vikhna kubelet[32064]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:11 vikhna kubelet[32064]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:11 vikhna kubelet[32064]: I0627 03:25:11.486732   32064 server.go:425] Version: v1.15.0
Jun 27 03:25:11 vikhna kubelet[32064]: I0627 03:25:11.487302   32064 plugins.go:103] No cloud provider specified.
Jun 27 03:25:11 vikhna kubelet[32064]: F0627 03:25:11.488502   32064 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jun 27 03:25:11 vikhna systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 27 03:25:11 vikhna systemd[1]: kubelet.service: Failed with result 'exit-code'.
Jun 27 03:25:21 vikhna systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Jun 27 03:25:21 vikhna systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 2992.
Jun 27 03:25:21 vikhna systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Jun 27 03:25:21 vikhna systemd[1]: Started kubelet: The Kubernetes Node Agent.
Jun 27 03:25:21 vikhna kubelet[32113]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:21 vikhna kubelet[32113]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:21 vikhna kubelet[32113]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:21 vikhna kubelet[32113]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:21 vikhna kubelet[32113]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:21 vikhna kubelet[32113]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:21 vikhna kubelet[32113]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:21 vikhna kubelet[32113]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jun 27 03:25:21 vikhna kubelet[32113]: I0627 03:25:21.739283   32113 server.go:425] Version: v1.15.0
Jun 27 03:25:21 vikhna kubelet[32113]: I0627 03:25:21.739797   32113 plugins.go:103] No cloud provider specified.
Jun 27 03:25:21 vikhna kubelet[32113]: F0627 03:25:21.739970   32113 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Jun 27 03:25:21 vikhna systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Jun 27 03:25:21 vikhna systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by bionicles** [comment]
having this issue currently with minikube on ubuntu 16.04 @tstromberg

**Comment by guilleojeda** [comment]
I was also experiencing this issue, and I solved it with the steps in [this comment](https://github.com/kubernetes/minikube/issues/4835#issuecomment-532483752)

To save you the trouble of following the link, the idea is to make sure you remove everything related to kube, which can be done with the following commands:
kubeadm reset
sudo apt-get purge kubeadm kubectl kubelet kubernetes-cni kube*
sudo apt-get autoremove
sudo rm -rf ~/.kube
sudo rm -rf ~/.minikube
sudo rm -rf /var/lib/minikube
sudo rm -rf /var/lib/kubelet
sudo rm -rf /var/lib/localkube
sudo rm -rf /data/minikube
sudo rm -rf /var/lib/kubeadm.yaml

After that, `minikube start` worked like a charm.

**Comment by raboof** [comment]
`minikube delete --all` did the trick for me
