### ISSUE TITLE
hyperv: Error configuring auth on host: Too many retries waiting for SSH to be available

### ISSUE THREAD

**Issue by zy0016** [kubernetes/minikube#4617]
C:\Users\Administrator>minikube start
* minikube v1.2.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Re-using the currently running hyperv VM for "minikube" ...
* Waiting for SSH access ...
E0627 10:26:38.891693    3332 start.go:559] StartHost: Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Re-using the currently running hyperv VM for "minikube" ...
* Waiting for SSH access ...
E0627 10:30:56.248841    3332 start.go:559] StartHost: Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Re-using the currently running hyperv VM for "minikube" ...
* Waiting for SSH access ...
E0627 10:35:05.937540    3332 start.go:559] StartHost: Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

X Unable to start VM: Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

C:\Users\Administrator>

**Comment by tstromberg** [comment]
Is there any chance there is a VPN preventing your host from talking to your guest? 

If so, try turning it off first.

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!

**Comment by nooruzb** [comment]
i have the same issue
