### ISSUE TITLE
Unable to load cached images: loading cached images

### ISSUE THREAD

**Issue by akaQin** [kubernetes/minikube#4618]
```bash
minikube start \
  --docker-env=HTTP_PROXY=10.0.0.19:1087 \
  --docker-env HTTPS_PROXY=10.0.0.19:1087 \
  --docker-env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24

😄  minikube v1.2.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
    ▪ env HTTP_PROXY=10.0.0.19:1087
    ▪ env HTTPS_PROXY=10.0.0.19:1087
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24
E0627 14:38:35.258509   12247 start.go:403] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/qinlong/.minikube/cache/images/k8s.gcr.io/pause_3.1: fetching remote image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: i/o timeout
❌  Unable to load cached images: loading cached images: loading image /Users/qinlong/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: stat /Users/qinlong/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory
💾  Downloading kubelet v1.15.0


💣  Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.15.0: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: net/http: TLS handshake timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 172.217.24.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 172.217.24.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 172.217.24.16:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 172.217.24.16:443: i/o timeout

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

**Comment by xijiz** [comment]
兄弟，你解决了吗

**Comment by xijiz** [comment]
> ```shell
> minikube start \
>   --docker-env=HTTP_PROXY=10.0.0.19:1087 \
>   --docker-env HTTPS_PROXY=10.0.0.19:1087 \
>   --docker-env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24
> 
> 😄  minikube v1.2.0 on darwin (amd64)
> 🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
> 🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
>     ▪ env HTTP_PROXY=10.0.0.19:1087
>     ▪ env HTTPS_PROXY=10.0.0.19:1087
>     ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24
> E0627 14:38:35.258509   12247 start.go:403] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/qinlong/.minikube/cache/images/k8s.gcr.io/pause_3.1: fetching remote image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: i/o timeout
> ❌  Unable to load cached images: loading cached images: loading image /Users/qinlong/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: stat /Users/qinlong/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory
> 💾  Downloading kubelet v1.15.0
> 
> 
> 💣  Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.15.0: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:
> 
> * Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: net/http: TLS handshake timeout
> * Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 172.217.24.16:443: i/o timeout
> * Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 172.217.24.16:443: i/o timeout
> * Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 172.217.24.16:443: i/o timeout
> * Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 172.217.24.16:443: i/o timeout
> 
> 😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> 👉  https://github.com/kubernetes/minikube/issues/new
> ```

兄弟，你解决了吗

**Comment by muwednesday** [comment]
兄弟，国内怎么安装啊

**Comment by xijiz** [comment]
我加了代理，然后一顿操作，莫名其妙就安装好了

**Comment by xijiz** [comment]
好像要先minikube delete，然后加sudo minikube  start

**Comment by muwednesday** [comment]
我按不上，没办法只能用阿里云的了。https://yq.aliyun.com/articles/221687
不过貌似能翻墙的话，直接用GKE安装集群好一些，免费使用一年~

**Comment by gangganghong** [comment]
minikube start --vm-driver=virtualbox
😄  minikube v1.3.1 on Darwin 10.15.1
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running virtualbox "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E0109 09:45:39.006936   92021 start.go:558] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/cg/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.15.2: fetching remote image: Get https://k8s.gcr.io/v2/: dial tcp 64.233.187.82:443: i/o timeout
❌  Unable to load cached images: loading cached images: loading image /Users/cg/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.15.2: stat /Users/cg/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.15.2: no such file or directory
🔄  Relaunching Kubernetes using kubeadm ...
^@^@
💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
chugangdeMacBook-Pro:eureka-server cg$ minikube delete
🔥  Deleting "minikube" in virtualbox ...
💔  The "minikube" cluster has been deleted.
chugangdeMacBook-Pro:eureka-server cg$ minikube start --vm-driver=virtualbox
😄  minikube v1.3.1 on Darwin 10.15.1
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E0109 10:16:37.340574   92454 start.go:558] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/cg/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13: fetching remote image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: i/o timeout
❌  Unable to load cached images: loading cached images: loading image /Users/cg/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: stat /Users/cg/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: no such file or directory
🚜  拉取镜像 ...
🚀  正在启动 Kubernetes ...
^@^@
💣  Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
[init] Using Kubernetes version: v1.15.2
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.3.10: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
	[ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`

: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by zhenglinhui** [comment]
try with it !
`minikube start --image-mirror-country='cn' --driver docker`
