### ISSUE TITLE
Add integration tests for all vm drivers

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4633]
It would be nice to have integration tests that only tests the functionality of VM drivers. in different scenarios.

( just an empty VM without installing kubelet or anyhting ) to test following
 - start, stop, delete
- start, start, delete
- start, delete, start
- ...

We could make integration tests for VM drivers to be triggered only if the driver package been changed.

**Comment by josedonizetti** [comment]
I was considering adding tests to the kvm driver using the test driver.
```
The test driver is a dummy hypervisor for test purposes. The URIs supported are:
test:///default connects to a default set of host definitions built into the driver.
```

This would be pretty simple once we merge: https://github.com/kubernetes/minikube/pull/4401

**Comment by medyagh** [comment]
this doesn't seem to be needed anymore.
