### ISSUE TITLE
Add documentation for qemu uri on kvm2 driver

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4635]
it would be nice to have a doc, showing minikube running with qemu uri.

would be even better to have an example showing it working on the cloud.
Related: https://github.com/kubernetes/minikube/commit/9dfe660c64ed9ac5d76650868bde29272211c582

**Comment by josedonizetti** [comment]
You can assign it to me. I'll create a simple tutorial running minikube on GCE with the remote qemu uri.

**Comment by medyagh** [comment]
Wonderful, thank you so much !

**Comment by afbjorklund** [comment]
Cloud ? I don't think we support running in the cloud, it was more for weird local setups...

**Comment by josedonizetti** [comment]
Yeah, it seems cloud isn't supported. The `--kvm-qemu-uri` works fine for connecting, but unfortunately some dependencies are only available locally, so it fails to create the KVM machine, for example:

https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kvm/domain.go#L56
https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kvm/domain.go#L62

When the XML template is sent to the qemu remote instance those files have the local paths, and doesn't exist in the remote.

**Comment by josedonizetti** [comment]
@medyagh any thoughts on this? Is this something we want to make possible?
