### ISSUE TITLE
Add documentation for virtualbox DNS settings 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4636]
We need to document the options added by PR https://github.com/kubernetes/minikube/pull/4619 by @cvila84 for virtualbox DNS settings in the docs 
 --dns-proxy and
 --host-dns-resolve

**Comment by cvila84** [comment]
I can help. I took a look to https://github.com/kubernetes/minikube/tree/master/docs but it is not very clear to me what we can document here regarding start options

**Comment by cvila84** [comment]
https://github.com/kubernetes/minikube/pull/4647 adds a new cli_commands.md, maybe we can document here once the PR is merged ?

**Comment by tstromberg** [comment]
The documentation isn't pretty, but https://minikube.sigs.k8s.io/docs/reference/commands/start/ now includes these flags.
