### ISSUE TITLE
Support for Hyper-V on Windows

### ISSUE THREAD

**Issue by raeesbhatti** [kubernetes/minikube#465]
I have Hyper-V enabled on my Windows for Docker. When I try to run minkube cluster, it says that I have to disable Hyper-V for VirtualBox to work or use Hyper-V as the driver but Hyper-V is not supported by minikube.
```
Starting local Kubernetes cluster...
E0809 14:08:01.300772    8324 start.go:78] Error starting host:  Error creating. Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"
```

I purpose that Hyper-V be supported by minikube as the default driver for Windows.

**Comment by jimmidyson** [comment]
We can easily enable hyperv, will send in a PR soon-ish unless someone else gets there soon. As for making it default, please comment on #270

**Comment by dlorenc** [comment]
We're still doing some testing here, we should get it in soon.

**Comment by dlorenc** [comment]
ref https://github.com/kubernetes/minikube/pull/476

**Comment by raeesbhatti** [comment]
Wohoooo!!! @dlorenc can you please make a new release with this update!

**Comment by dlorenc** [comment]
We'll try to get a release out early next week. In the meantime we have a CI job that does builds at each PR. You can grab this commit here: (467 is the PR id)

https://storage.googleapis.com/minikube-builds/467/minikube-windows-amd64.exe

**Comment by dlorenc** [comment]
We should add some hyper-v docs to the drivers documentation page. I think @aaron-prindle had to do some manual configuration with the virtual switch.

**Comment by jacktheruck** [comment]
We're waiting for new release with this update!
Also you're making install VM box a requirement for toolbox running and we don't need it while we have hyper-v installed. Please slove this problem cause no one want to waste some space on non-used apps.

**Comment by dlorenc** [comment]
We're going to cut 0.9 later today!

**Comment by rodcloutier** [comment]
Any progress on this? Is it supported with 0.12?

**Comment by raeesbhatti** [comment]
@rodcloutier It was supposed to be fixed but there are some new issues with minikube, some are probably not related to Hyper-V but some are.
Take a look at #754 , #747 and #518

**Comment by melvincabatuan** [comment]
I have a similar issue on Windows 10 pro:

$ docker-machine create -d virtualbox default
Running pre-create checks...
Error with pre-create check: "This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)"

Without the vtx check though, it's stuck on '(default) Waiting for an IP...'

$ docker-machine create -d virtualbox --virtualbox-no-vtx-check default
Running pre-create checks...
Creating machine...
(default) Copying C:\Users\cobalt\.docker\machine\cache\boot2docker.iso to C:\Users\cobalt\.docker\machine\machines\default\boot2docker.iso...
(default) Creating VirtualBox VM...
(default) Creating SSH key...
(default) Starting the VM...
(default) Check network to re-create if needed...
(default) Waiting for an IP...

**Comment by jsdev** [comment]
=(

**Comment by wasimbloch** [comment]
Any update on this? I would like to run Minikube on Windows 10 64 bit machine with Hyper-V (not VirtualBox). Thanks

**Comment by odannyboy000** [comment]
Is Hyper-V supported yet? I get the error: "The connection to the server localhost:8080 was refused - did you specify the right host or port?" with a clean install of kubectl and docker-ce

**Comment by aaron-prindle** [comment]
Yes, it is currently supported. If you can post a new github issue with some information on your virtual switch configuration and how you attempted to start minikube we can help investigate the issue that you are having.

**Comment by reza-ebrahimi** [comment]
I think no, it doesnot supported yet, 
https://github.com/kubernetes/minikube/issues/1523

**Comment by srivathsah** [comment]
@aaron-prindle You have mentioned minikube is supported with Hyper-V , however I am not able to use it with the latest release that was done only yesterday. I still get hyper-v not a valid driver message , What am I missing

**Comment by mreddimasi** [comment]
@srivathsah I used the following command on Windows 10 Pro, this is with version 0.20.0 of minikube

> minikube start --vm-driver=hyperv --hyperv-virtual-switch="Primary Virtual Switch"

You would need to replace the "Primary Virtual Switch" with whatever you have, hope this helps.

**Comment by stanspotts** [comment]
I'm running 0.20.0 and have Hyper-V and the added virtual switch, but when I try to start it still thinks I'm using VirtualBox:
$ minikube start --vm-driver=hyperv --hyperv-virtual-switch="Primary Virtual Switch"
Starting local Kubernetes v1.6.4 cluster...
Starting VM...
E0720 12:33:22.991955   10436 start.go:127] Error starting host: Error starting stopped host: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.200078 Power up failed (vrc=VERR_VMX_NO_VMX, rc=E_FAIL (0X80004005)).

 Retrying.
E0720 12:33:22.994888   10436 start.go:133] Error starting host:  Error starting stopped host: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
