### ISSUE TITLE
Takes 95 seconds to stop a xhyve VM

### ISSUE THREAD

**Issue by ahmetb** [kubernetes/minikube#4660]
A simple `minikube stop` just took 95 seconds.

This is a relatively fresh/empty VM. I only ran:

- `minikube start --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock`

- `minikube addons enable gvisor`

- `kubectl logs`

- `minikube stop` (took 95s.)

**The exact command to reproduce the issue**: `minikube stop` (xhyve driver)

**The full output of the command that ~~failed~~ took too long**:
<details><summary><code>Output</code></summary><br><pre>
[23:31:16] ~ $ minikube stop
✋  Stopping "minikube" in xhyve ...
🛑  "minikube" stopped.
[23:32:51] ~ $ <--
</pre></details>

**The output of the `minikube logs` command**:
<details><summary><code>minikube logs</code></summary><br><pre>
N/A – host stopped
</pre></details>

**The operating system version**: 10.14.5 (18F132)
**minikube version**: 1.2
**minikube addons:** gvisor

**Comment by medyagh** [comment]
Thank you for creating this issue, 95 seconds is not acceptable for waiting to stop. Btw I am curious is there a specific reason to use xhyve driver ?  We have depricated support for that driver. But I am curious if there is any advantage of using xhyve to hyperkit ?

**Comment by ahmetb** [comment]
Mostly gMac compliance I think. Or maybe I’ve been using minikube since far too long. I should try the hyperkit option. Thanks.

**Comment by medyagh** [comment]
We are working on VM free minikube for all platforms, with that coming it will speed up super fast !

**Comment by ahmetb** [comment]
That sounds dope but I have no idea how would it work :P

**Comment by tstromberg** [comment]
For "gmac compliance", I suggest just installing hyperkit from brew.

**Comment by ahmetb** [comment]
Yeah, I think we can close this I suspect xhyve is going to be removed.
