### ISSUE TITLE
minikube VM on Hyper-V is in "Shutting Down" state since 30+ minutes

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#4661]
**The exact command to reproduce the issue**:
Ensure that there is no cluster already on the machine.
`.\minikube-windows-amd64.exe start --vm-driver=hyperv --hyperv-virtual-switch="Default Switch" --v=8 `
`.\minikube-windows-amd64.exe stop`

**The full output of the command that failed**:
<details><summary><code>
Output
</code></summary><br><pre>
PS C:\utilities> .\minikube-windows-amd64.exe stop
* Stopping "minikube" in hyperv ...
* Stopping "minikube" in hyperv ...
* Stopping "minikube" in hyperv ...
* Stopping "minikube" in hyperv ...
* Stopping "minikube" in hyperv ...

X Unable to stop VM: Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
</pre></details>

**The output of the `minikube logs` command**:
<details><summary><code>minikube logs</code></summary><br><pre>
PS C:\utilities> .\minikube-windows-amd64.exe logs

X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
</pre></details>

**The operating system version**:
Windows 10 Enterprise.

The VM in Hyper-V has been in Shutting down state since 35 minutes -
![image](https://user-images.githubusercontent.com/6985763/60497064-b88f2e80-9cd1-11e9-84e7-f5a335a56b1d.png)

This seems as if something has blocked the shutting down process inside the `minikube` virtual machine. I haven't seen this happening with any other Linux machines.

I have the following questions as well -

- Do we know what is the username/password to login to the `minikube` virtual machine so that I can check the logs?
- How many times does Minikube retry and for many seconds does it wait?
- Do we have a logic to force turn off the VM if the VM is still in Shutting down phase?

Related to #2914

-Pranav

**Comment by blueelvis** [comment]
Also, I just noticed that the VM created by minikube is Gen 1. Is there any reason why we are creating a Gen 1 VM? I have the Docker installed on my machine as well (as you can see from the above screenshot) and that is a Gen 2 Virtual Machine. 

Seems like minikube VM is a `boot2docker` VM which is now in maintenance mode. Are there any plans to migrate to a newer one?

**Comment by michaelbaranov** [comment]
I use solution from here for shutting down minikube https://github.com/kubernetes/minikube/issues/2914#issuecomment-401562007

**Comment by blueelvis** [comment]
I was just typing this. I did the following and it worked as well but we need to have some fall back where if the Hypervisor call doesn't return back in few minutes, we should shut down from within the VM itself.
```
minikube ssh
sudo shutdown
```
That shut down the machine after a minute.

**Comment by tstromberg** [comment]
This issue appears to be a duplicate of #2914, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!
