### ISSUE TITLE
Add option to delete all profiles 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4668]
minikube should have an option to delete all profiles with one command.

`minikube delete --all`

**Comment by marekschwarz** [comment]
I would like to take a look at this

**Comment by josedonizetti** [comment]
@marekschwarz Cool! You might want to take a look on @medyagh  comment here: https://github.com/kubernetes/minikube/issues/4598#issuecomment-508197175

**Comment by marekschwarz** [comment]
Maybe we should develop a dedicated profiles „api“, to keep all the logic for profile-related stuff (like create, delete, getStatus, ...) in one place.

**Comment by tstromberg** [comment]
This shipped as part of v1.5.0.
