### ISSUE TITLE
Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.2.0: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:

### ISSUE THREAD

**Issue by apupier** [kubernetes/minikube#4670]
**The exact command to reproduce the issue**:

(note you have to create the Hyper-V external switch named ExternalVirtualSwitch, be on WIndows 10 and have Hyper-V enabled)

```
minikube config set vm-driver hyperv && minikube config set hyperv-virtual-switch ExternalVirtualSwitch
minikube profile camelk
minikube config set kubernetes-version 1.2.0
minikube config set memory 4000
minikube config set cpus 4
minikube config set disk-size 20g
minikube start -p camelk --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
```

**The full output of the command that failed**:
<details><summary><code>Output</code></summary><br><pre>
* minikube v1.2.0 on windows (amd64)
* Downloading Minikube ISO ...
 129.33 MB / 129.33 MB [============================================] 100.00% 0s
* Creating hyperv VM (CPUs=4, Memory=4000MB, Disk=20000MB) ...
* Configuring environment for Kubernetes v1.2.0 on Docker 18.09.6
E0703 08:27:30.640988    3680 start.go:403] Error caching images:  Caching images for kubeadm: caching images: caching image C:\Users\Aurelien Pupier\.minikube\cache\images\k8s.gcr.io\kube-controller-manager-amd64_v1.2.0: MANIFEST_UNKNOWN: Manifest with tag 'v1.2.0' has media type 'application/vnd.docker.distribution.manifest.v1+prettyjws', but client accepts 'application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json'.
  - apiserver.enable-admission-plugins=LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook
* Unable to load cached images: loading cached images: loading image C:\Users\Aurelien Pupier\.minikube\cache\images\k8s.gcr.io\kube-controller-manager-amd64_v1.2.0: CreateFile C:\Users\Aurelien Pupier\.minikube\cache\images\k8s.gcr.io\kube-controller-manager-amd64_v1.2.0: The system cannot find the file specified.
* Downloading kubeadm v1.2.0
* Downloading kubelet v1.2.0

X Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.2.0: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:

* received invalid status code: 404 (expected 200)

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

</pre></details>

**The output of the `minikube logs` command**:
<details><summary><code>minikube logs</code></summary><br><pre>
==> dmesg <==
[Jul 3 06:26] smpboot: 128 Processors exceeds NR_CPUS limit of 64
[  +0.000000] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[  +0.017045] * Found PM-Timer Bug on the chipset. Due to workarounds for a bug,
              * this clock source is slow. Consider trying other clock sources
[Jul 3 06:27] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +0.425322] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
[  +0.430243] systemd-fstab-generator[1251]: Ignoring "noauto" for root device
[  +0.003646] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:35 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000003] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +2.874992] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +0.846707] vboxguest: loading out-of-tree module taints kernel.
[  +0.004735] vboxguest: PCI device not found, probably running on physical hardware.
[ +12.174897] systemd-fstab-generator[2634]: Ignoring "noauto" for root device
[Jul 3 06:29] NFSD: Unable to end grace period: -110

==> kernel <==
 06:34:02 up 7 min,  0 users,  load average: 0.07, 0.09, 0.06
Linux camelk 4.15.0 #1 SMP Sun Jun 23 23:02:01 PDT 2019 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Wed 2019-07-03 06:27:09 UTC, end at Wed 2019-07-03 08:27:08 UTC. --
-- No entries --

</pre></details>

**The operating system version**:

Windows 10

**Comment by apupier** [comment]
<details><summary><code>output with --v=7</code></summary><br><pre>
minikube start -p camelk --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook" --v=7
* minikube v1.2.0 on windows (amd64)
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
* Re-using the currently running hyperv VM for "camelk" ...
* Waiting for SSH access ...
Waiting for SSH to be available...
Getting to WaitForSSH function...
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:
exit 0
SSH cmd err, output: <nil>:
Detecting the provisioner...
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:
cat /etc/os-release
SSH cmd err, output: <nil>: NAME=Buildroot
VERSION=2018.05.3
ID=buildroot
VERSION_ID=2018.05.3
PRETTY_NAME="Buildroot 2018.05.3"

found compatible host: buildroot
setting hostname "camelk"
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:
sudo hostname camelk && echo "camelk" | sudo tee /etc/hostname
SSH cmd err, output: <nil>: camelk

[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:

                if ! grep -xq '.*\scamelk' /etc/hosts; then
                        if grep -xq '127.0.1.1\s.*' /etc/hosts; then
                                sudo sed -i 's/^127.0.1.1\s.*/127.0.1.1 camelk/g' /etc/hosts;
                        else
                                echo '127.0.1.1 camelk' | sudo tee -a /etc/hosts;
                        fi
                fi
SSH cmd err, output: <nil>:
set auth options {CertDir:C:\Users\Aurelien Pupier\.minikube CaCertPath:C:\Users\Aurelien Pupier\.minikube\certs\ca.pem CaPrivateKeyPath:C:\Users\Aurelien Pupier\.minikube\certs\ca-key.pem CaCertRemotePath:/etc/docker/ca.pem ServerCertPath:C:\Users\Aurelien Pupier\.minikube\machines\server.pem ServerKeyPath:C:\Users\Aurelien Pupier\.minikube\machines\server-key.pem ClientKeyPath:C:\Users\Aurelien Pupier\.minikube\certs\key.pem ServerCertRemotePath:/etc/docker/server.pem ServerKeyRemotePath:/etc/docker/server-key.pem ClientCertPath:C:\Users\Aurelien Pupier\.minikube\certs\cert.pem ServerCertSANs:[] StorePath:C:\Users\Aurelien Pupier\.minikube}
setting up certificates
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
generating server cert: C:\Users\Aurelien Pupier\.minikube\machines\server.pem ca-key=C:\Users\Aurelien Pupier\.minikube\certs\ca.pem private-key=C:\Users\Aurelien Pupier\.minikube\certs\ca-key.pem org=Aurelien Pupier.camelk san=[192.168.1.33 localhost]
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Setting Docker configuration on the remote daemon...
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:
sudo mkdir -p /lib/systemd/system && printf %s "[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target  minikube-automount.service docker.socket
Requires= minikube-automount.service docker.socket

[Service]
Type=notify

# DOCKER_RAMDISK disables pivot_root in Docker, using MS_MOVE instead.
Environment=DOCKER_RAMDISK=yes


# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
# The base configuration already specifies an 'ExecStart=...' command. The first directive
# here is to clear out that command inherited from the base configuration. Without this,
# the command from the base configuration and the command specified here are treated as
# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
# will catch this invalid input and refuse to start the service with an error like:
#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=hyperv --insecure-registry 10.96.0.0/12
ExecReload=/bin/kill -s HUP $MAINPID

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
" | sudo tee /lib/systemd/system/docker.service
SSH cmd err, output: <nil>: [Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
After=network.target  minikube-automount.service docker.socket
Requires= minikube-automount.service docker.socket

[Service]
Type=notify

# DOCKER_RAMDISK disables pivot_root in Docker, using MS_MOVE instead.
Environment=DOCKER_RAMDISK=yes


# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
# The base configuration already specifies an 'ExecStart=...' command. The first directive
# here is to clear out that command inherited from the base configuration. Without this,
# the command from the base configuration and the command specified here are treated as
# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
# will catch this invalid input and refuse to start the service with an error like:
#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=hyperv --insecure-registry 10.96.0.0/12
ExecReload=/bin/kill -s HUP

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target

setting minikube options for container-runtime
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:
sudo mkdir -p /etc/sysconfig && printf %s "
CRIO_MINIKUBE_OPTIONS='--insecure-registry 10.96.0.0/12 '
" | sudo tee /etc/sysconfig/crio.minikube
SSH cmd err, output: <nil>:
CRIO_MINIKUBE_OPTIONS='--insecure-registry 10.96.0.0/12 '

[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:
sudo systemctl daemon-reload
SSH cmd err, output: <nil>:
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:
sudo systemctl -f restart crio
SSH cmd err, output: <nil>:
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
Using SSH client type: native
&{{{<nil> 0 [] [] []} docker [0x8799d0] 0x8799a0 <nil>  [] 0s} 192.168.1.33 22 <nil> <nil>}
About to run SSH command:
date +%s.%N
SSH cmd err, output: <nil>: 1562138154.745083100

[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
* Configuring environment for Kubernetes v1.2.0 on Docker 18.09.6
E0703 09:15:58.148054    6712 start.go:403] Error caching images:  Caching images for kubeadm: caching images: caching image C:\Users\Aurelien Pupier\.minikube\cache\images\k8s.gcr.io\kube-proxy-amd64_v1.2.0: MANIFEST_UNKNOWN: Manifest with tag 'v1.2.0' has media type 'application/vnd.docker.distribution.manifest.v1+prettyjws', but client accepts 'application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json'.
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM camelk ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM camelk ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.1.33

[stderr =====>] :
  - apiserver.enable-admission-plugins=LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook
* Unable to load cached images: loading cached images: loading image C:\Users\Aurelien Pupier\.minikube\cache\images\k8s.gcr.io\kube-controller-manager-amd64_v1.2.0: CreateFile C:\Users\Aurelien Pupier\.minikube\cache\images\k8s.gcr.io\kube-controller-manager-amd64_v1.2.0: The system cannot find the file specified.
* Downloading kubeadm v1.2.0

X Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.2.0: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:

* received invalid status code: 404 (expected 200)

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
</pre></details>

**Comment by apupier** [comment]
I have soem files named "kube-proxy-amd64_v1.2.0.892830980.tmp" which might be related to the mentioned C:\Users\Aurelien Pupier\.minikube\cache\images\k8s.gcr.io\kube-proxy-amd64_v1.2.0

here the file (inside a zip to be able to attach it to the github issue)
[kube-proxy-amd64_v1.2.0.892830980.tmp.zip](https://github.com/kubernetes/minikube/files/3353695/kube-proxy-amd64_v1.2.0.892830980.tmp.zip)

**Comment by apupier** [comment]
the interesting part seems to be:
`E0703 09:15:58.148054    6712 start.go:403] Error caching images:  Caching images for kubeadm: caching images: caching image C:\Users\Aurelien Pupier\.minikube\cache\images\k8s.gcr.io\kube-proxy-amd64_v1.2.0: MANIFEST_UNKNOWN: Manifest with tag 'v1.2.0' has media type 'application/vnd.docker.distribution.manifest.v1+prettyjws', but client accepts 'application/vnd.docker.distribution.manifest.v2+json,application/vnd.oci.image.manifest.v1+json,application/vnd.docker.distribution.manifest.list.v2+json,application/vnd.oci.image.index.v1+json'.`

if i understand well, i have a Docker version which is too recent to support the format of the image.
Here are the versions that I have for Docker:

![image](https://user-images.githubusercontent.com/1105127/60573320-c3040380-9d77-11e9-9558-59f793966d6d.png)

**Comment by apupier** [comment]
damn, I made a typo on the kubernetes version to use, effectively, i specified a 1.2.0 version which is quite old, with 1.12.0 it is going further.

Sorry for disturbance

**Comment by afbjorklund** [comment]
Oops, wrong issue (4610 became 4670). Please ignore.
