### ISSUE TITLE
-vm-driver=none: flag: strconv.Atoi: parsing "m-driver=none": invalid syntax

### ISSUE THREAD

**Issue by zaheer032** [kubernetes/minikube#4671]
I am trying to run minikube on Ubuntu 18.04 Oracle Virtual box following the blog @ https://medium.com/@vovaprivalov/setup-minikube-on-virtualbox-7cba363ca3bc

**The exact command to reproduce the issue**:
sudo minikube start -vm-driver=none

**The full output of the command that failed**:
sudo minikube start -vm-driver=none
Error: invalid argument "m-driver=none" for vm-driver=none: strconv.Atoi: parsing "m-driver=none": invalid syntax

<details><summary><code>Output</code></summary><br><pre>

</pre></details>

**The output of the `minikube logs` command**:
Command : minikube logs -f
There is a newer version of minikube available (v1.2.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.2.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
F0703 14:32:50.587779   22601 logs.go:50] Error getting cluster bootstrapper: getting localkube bootstrapper: getting api client: Error loading host from store: Host does not exist: "minikube"

<details><summary><code>minikube logs</code></summary><br><pre>

</pre></details>

**The operating system version**:

Ubuntu 18.04

**Comment by medyagh** [comment]
Thank you for taking the time to create this issue, do you mind upgrading your minikube to the latest version ?

could you try with --vm-driver instead of -vm-driver ?

**Comment by javazos** [comment]
nn

**Comment by javazos** [comment]
I got the same problems when trying to start the minikube  in Oracle virtual box in linux, but after run delete, then run start with --vm-driver=no , it is working.

xxxx@ThinkPadT470s:~$ sudo minikube start --vm-driver=none
😄  minikube v1.2.0 on linux (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing none VM for "minikube" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.7
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ...

**Comment by tstromberg** [comment]
The error message here is terrible, but the issue is that the blog article is incorrectly specifying -vm-driver (single leading dash) instead of --vm-driver (double leading dash).
 

I will admit that the error message is difficult to understand:


```
Error: invalid argument "m-driver=none" for "-v, --v" flag: strconv.Atoi: parsing "m-driver=none": invalid syntax
```
