### ISSUE TITLE
Windows virtualbox: Error: Call to WHvSetupPartition failed

### ISSUE THREAD

**Issue by donguty** [kubernetes/minikube#4672]
* minikube v1.2.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing virtualbox VM for "minikube" ...
E0703 11:09:18.045350   10228 start.go:559] StartHost: start: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Call to WHvSetupPartition failed: ERROR_SUCCESS (Last=0xc000000d/87) (VERR_NEM_VM_CREATE_FAILED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.010039 Power up failed (vrc=VERR_NEM_VM_CREATE_FAILED, rc=E_FAIL (0X80004005))

X Unable to start VM: start: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Call to WHvSetupPartition failed: ERROR_SUCCESS (Last=0xc000000d/87) (VERR_NEM_VM_CREATE_FAILED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.010039 Power up failed (vrc=VERR_NEM_VM_CREATE_FAILED, rc=E_FAIL (0X80004005))

**Comment by medyagh** [comment]
Thank you for taking the time to create this issue, I am curious your virtualbox version is 6 ? could you please try with virtualbox 5.2 ? https://www.virtualbox.org/wiki/Download_Old_Builds_5_2 and see if the problem still exists?

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

- Your version of VirtualBox
- The full output of `minikube start --alsologtostderr -v=8`

Please feel free to do so at any point. Thank you for sharing your experience!

**Comment by srikanta72** [comment]
virtual box- Version 6.0.12
Tried with hyperv- on
tried with hyperv-off

same error.

There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "ed64790a-e86b-4177-b60c-341e3a777b57", "--type", "headless"]

Stderr: VBoxManage.exe: error: Call to WHvSetupPartition failed: ERROR_SUCCESS (Last=0xc000000d/87) (VERR_NEM_VM_CREATE_FAILED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

**Comment by srikanta72** [comment]
Scenario to create: 
create a vagrant file 
run the vagrant file to create cenos/7 with virtualbox.

**Comment by BoGnY** [comment]
Starting from Virtualbox 6.x HyperV is supported, but is default disabled as is it an experimental feature.

This is the solution to [enable that feature](https://superuser.com/a/1489744).

If you have existing machine, after "global" command you have to start even specific command for all machine already existing 👍

**Comment by yelvert** [comment]
Getting this same issue. Tried the things mentioned here https://www.wintips.org/fix-virtualbox-error-call-to-whvsetuppartition-failed-error-success/, no dice
