### ISSUE TITLE
kvm2: Minikube v1.2.0 startup error

### ISSUE THREAD

**Issue by kubesure** [kubernetes/minikube#4679]
Error while starting Minikube,

Minikube v1.2.0
```
virsh --version 1.3.1
------------------------------------------------------------------------------------------
 sudo systemctl status libvirtd.service
â libvirt-bin.service - Virtualization daemon
   Loaded: loaded (/lib/systemd/system/libvirt-bin.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2019-07-04 10:39:11 IST; 42min ago
     Docs: man:libvirtd(8)
           http://libvirt.org
 Main PID: 4569 (libvirtd)
   CGroup: /system.slice/libvirt-bin.service
           ââ4569 /usr/sbin/libvirtd
           ââ5021 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
           ââ5022 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper

Jul 04 10:39:31 ip-172-31-39-79 dnsmasq[5021]: started, version 2.75 cachesize 150
Jul 04 10:39:31 ip-172-31-39-79 dnsmasq[5021]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inoti
Jul 04 10:39:31 ip-172-31-39-79 dnsmasq-dhcp[5021]: DHCP, IP range 192.168.122.2 -- 192.168.122.254, lease time 1h
Jul 04 10:39:31 ip-172-31-39-79 dnsmasq-dhcp[5021]: DHCP, sockets bound exclusively to interface virbr0
Jul 04 10:39:31 ip-172-31-39-79 dnsmasq[5021]: reading /etc/resolv.conf
Jul 04 10:39:31 ip-172-31-39-79 dnsmasq[5021]: using nameserver 172.31.0.2#53
Jul 04 10:39:31 ip-172-31-39-79 dnsmasq[5021]: read /etc/hosts - 7 addresses
Jul 04 10:39:31 ip-172-31-39-79 dnsmasq[5021]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
Jul 04 10:39:31 ip-172-31-39-79 dnsmasq-dhcp[5021]: read /var/lib/libvirt/dnsmasq/default.hostsfile
Jul 04 10:40:42 ip-172-31-39-79 systemd[1]: Started Virtualization daemon.
```
------------------------------------------------------------------------------------------------

minikube logs 
------------------------------------------------------------------------------------------------
```
* minikube v1.2.0 on linux (amd64)
* Creating kvm2 VM (CPUs=4, Memory=12MB, Disk=20000MB) ...
E0704 10:47:47.994476    5142 start.go:559] StartHost: new host: dial tcp: missing address

X Unable to start VM: new host: dial tcp: missing address
```

**Comment by medyagh** [comment]
could you please confirm you have the latest minikuber's kvm2 driver?

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2 \
  && sudo install docker-machine-driver-kvm2 /usr/local/bin/

```

**Comment by medyagh** [comment]
in your logs I see 
``` Creating kvm2 VM (CPUs=4, Memory=12MB, Disk=20000MB) ```

12 MB memory is too low, the minimum is 2000 MB, could you please start minikube with at 2GB ram ?
we have a PR merged that will be in the next release, that will prevent users starting minikube in with very low ram

**Comment by kubesure** [comment]
minikube start --memory=12384 --cpus=4 --kubernetes-version=v1.14.2
* minikube v1.2.0 on linux (amd64)
* Creating kvm2 VM (CPUs=4, Memory=12384MB, Disk=20000MB) ...
E0704 11:40:12.020975    5312 start.go:559] StartHost: new host: dial tcp: missing address

X Unable to start VM: new host: dial tcp: missing address

have the latest version installed. same error. 
curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2 \
  && sudo install docker-machine-driver-kvm2 /usr/local/bin/

 lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial

**Comment by kubesure** [comment]
work without a VM.  

minikube start --vm-driver none

**Comment by josedonizetti** [comment]
@kubesure Could you provide the output of some other commands? pls

```
virsh net-list --all
virsh list --all 
minikube start --kubernetes-version=v1.14.2 -v7
```

**Comment by afbjorklund** [comment]
Sadly, this error: `new host: dial tcp: missing address`

Normally means that kvm2 is unable to find libvirt symbols.

See #4295

**Comment by kubesure** [comment]
virsh net-list --all
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 default              active     yes           yes

virsh list --all
 Id    Name                           State
----------------------------------------------------

sudo minikube start --kubernetes-version=v1.14.2 -v7
* minikube v1.2.0 on linux (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Re-using the currently running none VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.14.2 on Docker 18.06.1-ce
* Relaunching Kubernetes v1.14.2 using kubeadm ...
* Configuring local host environment ...

! The 'none' driver provides limited isolation and may reduce system security and reliability.
! For more information, see:
  - https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

! kubectl and minikube configuration will be stored in /home/ubuntu
! To use kubectl or minikube commands as your own user, you may
! need to relocate them. For example, to overwrite your own settings:

  - sudo mv /home/ubuntu/.kube /home/ubuntu/.minikube $HOME
  - sudo chown -R $USER $HOME/.kube $HOME/.minikube

* This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
* Verifying: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube"

**Comment by kubesure** [comment]
Tried kvm2 driver with k8s v1.14.2 

```
sudo sudo minikube  start --kubernetes-version=v1.14.2 -v7 --vm-driver kvm2
* minikube v1.2.0 on linux (amd64)
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary.
* Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
Found binary path at /usr/local/bin/docker-machine-driver-kvm2
Launching plugin server for driver kvm2
Plugin server listening at address
E0705 10:44:03.309021    6688 start.go:559] StartHost: new host: dial tcp: missing address
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt-lxc.so.0: version `LIBVIRT_LXC_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_2.2.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_3.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_1.3.3' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)

X Unable to start VM: new host: dial tcp: missing address

```

**Comment by medyagh** [comment]
please dont run kvm with sudo

**Comment by afbjorklund** [comment]
> DBG | /usr/local/bin/docker-machine-driver-kvm2: /usr/lib/x86_64-linux-gnu/libvirt.so.0: version `LIBVIRT_1.3.3' not found (required by /usr/local/bin/docker-machine-driver-kvm2)

This means that it is due to #4555. As a workaround, please use [docker-machine-driver-kvm2](https://github.com/kubernetes/minikube/releases/download/v1.0.0/docker-machine-driver-kvm2) 1.0.0
