### ISSUE TITLE
profile's kube-context should have a "minikube-" prefix

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4680]
I have been thinking, if we should make minikube kube contexts have a minikube- prefix to them, so the user knows it was created by minikube ?

let say if I create a minikube profile named dev, or test, 
I might have a GKE cluster or another cluster named test or dev, I wouldn't be sure which kube context belongs to minikube. and would be harder to clean up !

I would love to know others opinions on this.

**Comment by josedonizetti** [comment]
Definitely useful! I see the same problem in other parts as well, for example, KVM domains when listed have the profile name, if you have other domains you don't easily know which are from minikube and which aren't.

**Comment by afbjorklund** [comment]
Sounds good to me

**Comment by medyagh** [comment]
good ! I will add this to the backlog ! I would be happy to review the PR for it

**Comment by kairen** [comment]
@medyagh SGTM! I would like to work on this.

**Comment by medyagh** [comment]
awesome ! it is yours. please feel free to ask me questions if needed help.

**Comment by josedonizetti** [comment]
@kairen are you doing the KVM change too? if not I'll handle it.

**Comment by kairen** [comment]
@josedonizetti Yes, I will also deal with it. Additionally, I think other VM drivers also need to add this change if that driver has the same problem.

**Comment by medyagh** [comment]
@kairen are you still interested in doing this ?
