### ISSUE TITLE
Question: no node-provided-ip annotation on node

### ISSUE THREAD

**Issue by boskiv** [kubernetes/minikube#4690]
Regarding to 
https://github.com/kubernetes/minikube/issues/544
and
https://github.com/joonix/k8s-externalip/blob/master/main.go

I'm expecting to find the minikube external IP address in node annotation.
`.kubernetes.io/provided-node-ip`

Is it a bug? or there is an option how to get it there?

**The exact command to reproduce the issue**:

`kubectl describe node`

**The full output of the command that failed**:

```
➜  helm kubectl describe node
Name:               minikube
Roles:              master
Labels:             beta.kubernetes.io/arch=amd64
                    beta.kubernetes.io/os=linux
                    kubernetes.io/arch=amd64
                    kubernetes.io/hostname=minikube
                    kubernetes.io/os=linux
                    node-role.kubernetes.io/master=
Annotations:        kubeadm.alpha.kubernetes.io/cri-socket: /var/run/dockershim.sock
                    node.alpha.kubernetes.io/ttl: 0
                    volumes.kubernetes.io/controller-managed-attach-detach: true
CreationTimestamp:  Fri, 05 Jul 2019 11:19:46 +0300
```
**The operating system version**:
OSX

➜  helm minikube version
minikube version: v1.2.0
OSX: 10.14.5 (18F132)

**Comment by tstromberg** [comment]
minikube currently does not set any node annotations. If one would be helpful to you, I'd be happy to accept a PR that adds one.

**Comment by medyagh** [comment]
@boskiv  do you have a use case for adding that annotation that would make a case for higher priority to work on it ?

**Comment by boskiv** [comment]
> @boskiv do you have a use case for adding that annotation that would make a case for higher priority to work on it ?

It was needed to automation tools that expose to client external IP to connect.

For example, we have a service inside Kubernetes that should register another service with an external address. Like a service discovery. It should come to "consul" and register with own external address. So the client can find it after.
In this case, the service should able to make a request to the Kubernetes API and get node external address. That does not work with Minikube.

**Comment by tstromberg** [comment]
I looked into this a little bit, and the best I could find was this mention on https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/well_known_annotations.go

```
// AnnotationProvidedIPAddr is a node IP annotation set by the "external" cloud provider.
	// When kubelet is started with the "external" cloud provider, then
	// it sets this annotation on the node to denote an ip address set from the
	// cmd line flag (--node-ip). This ip is verified with the cloudprovider as valid by
	// the cloud-controller-manager
	AnnotationProvidedIPAddr = "alpha.kubernetes.io/provided-node-ip"
```

In our case, there is no external cloud provider, so there is no IP added there automatically. That said, I would be open to a PR adding this annotation to minikube.

My gut instinct says this would go in `pkg/minikube/node/node.go`, but @medyagh may have a better idea.

**Comment by sharifelgamal** [comment]
Help still wanted.

/remove-lifecycle rotten
