### ISSUE TITLE
virtualbox: Could not find a registered machine named 'minikube'

### ISSUE THREAD

**Issue by celian-garcia** [kubernetes/minikube#4694]
Hello ! and thanks for the work ;)

**The exact command to reproduce the issue**:
Each of these commands are run on windows 10 with powershell as administrator.
```bash
minikube start 
minikube stop
(Restart windows)
minikube start -v=10
```

**The full output of the command that failed**:
<details><summary><code>Output</code></summary><br><pre>
minikube start -v=10
o   minikube v0.35.0 on windows (amd64)
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
STDOUT:
{
}
STDERR:
{
VBoxManage.exe: error: Could not find a registered machine named 'minikube'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2834 of file VBoxManageInfo.cpp
}
!   Unable to start VM: Error getting state for host: machine does not exist

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
</pre></details>

**The output of the `minikube logs` command**:
<details><summary><code>minikube logs</code></summary><br><pre>

</pre></details>

**The operating system version**:
Windows 10

**Comment by celian-garcia** [comment]
I found a workaround which is as simple as making this command before minikube start
```bash
VBoxManage registervm C:\Users\<my user>\.minikube\machines\minikube\minikube\minikube.vbox
```
But the issue is here anyway

**Comment by tstromberg** [comment]
Hi @celian-garcia!

As you noticed, minikube does not react very well if an old configuration is found, but the VM associated to it is missing. It's unclear if newer versions would have handled this better. You found an interesting workaround! 

I normally recommend users run `minikube delete` if the two are no longer in sync. We should make sure minikube suggests the same.

**Comment by celian-garcia** [comment]
Yeah I searched a lot in issues before posting this one and noticed the problems in start in Windows and the solution.
But the ``minikube delete`` was removing all my cluster and I wanted to keep all my microservices + Kong Gateway intact ^^.

Hope my workaround will help you to debug this ! 

I'll follow the versions up to see if something is better in the future.

**Comment by tstromberg** [comment]
Sounds like you found an interesting workaround.

In general, `minikube start` and `minikube delete` should do the right thing. Registering VM's shouldn't be necessary. Thanks for the feedback!
