### ISSUE TITLE
Unsupported driver: none (on Linux!)

### ISSUE THREAD

**Issue by Faisal16292** [kubernetes/minikube#4696]

**Comment by Faisal16292** [comment]
F0711 22:12:31.947378    9111 cluster.go:391] Unsupported driver: none

**Comment by afbjorklund** [comment]
The "none" driver is only supported on Linux, what is your platform ?

**Comment by Faisal16292** [comment]
ubuntu linux

**Comment by afbjorklund** [comment]
That is strange, can you post the full output of the command you used ?

Normally it is something like: `sudo minikube start --vm-driver=none`

**Comment by Faisal16292** [comment]
sudo minikube start --vm-driver=none using this command shows error which i mentioned

**Comment by tstromberg** [comment]
Do you mind providing the full output of the `minikube start` command? It does seem rather weird.

**Comment by medyagh** [comment]
@Faisal16292 I am curious are you still having this issue ?

**Comment by medyagh** [comment]
@Faisal16292 I am closing this issue, please feel free to reopen with more info and logs if issue still exists.

**Comment by zatamine** [comment]
Same error here 
Command line: `minikube start --vm-driver=none`
Error : `F1023 18:32:27.966948   14956 cluster.go:391] Unsupported driver: none`

> Ubuntu 18.04 
> minikube installed using `snap`

**Comment by NarasimhaAthreya** [comment]
Do you have any soultions for this ?
Should I need to go with any VMs instead ? It is waste of system resource if I run VM though I have linux machine to run.

**Comment by NarasimhaAthreya** [comment]
> Same error here
> Command line: `minikube start --vm-driver=none`
> Error : `F1023 18:32:27.966948 14956 cluster.go:391] Unsupported driver: none`
> 
> > Ubuntu 18.04
> > minikube installed using `snap`

There is an offical documentation which says minikube installed through snap will not work. It requries deb package to run.

"If you’re using the none driver in Debian or a derivative, use the .deb packages for Docker rather than the snap package, which does not work with Minikube. You can download .deb packages from Docker."

But I have docker installed through .deb still it is not working.

**Comment by afbjorklund** [comment]
@NarasimhaAthreya : do you see the same output, do you have any more verbose logs ?

**Comment by Bouhmidovsky** [comment]
Hi all,
I am running the same command on a VM (virtualbox) using Debian 9 as OS.
Has anyone any idea about the issue ?

**Comment by afbjorklund** [comment]
> Hi all,
> I am running the same command on a VM (virtualbox) using Debian 10 as OS.
> Has anyone any idea about the issue ?

Please open a new ticket, not sure it makes much sense to run your own VM
in VirtualBox instead of just using the provided ISO - but it should still work...
