### ISSUE TITLE
Add command for installing kubectl program

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#4697]
Currently we either run `kubectl` for the user, or ask them to find the download themselves.

Since we already have a versioning and caching mechanism, we could also do it for them ?

So the `minikube kubectl` could grow two new options, one `--install` and one `--prefix`.

Where the prefix would default to `/usr/local` (needs sudo), but you _could_ use e.g. `$HOME`

```
sudo minikube kubectl --install
```

```
minikube kubectl --install --prefix=$HOME
```

Note that for the second usage, the user would need to make sure to include it in $PATH.

Some distributions do it by default, while some use `~/bin` and some use `~/.local/bin`...

----

Reference #4684 and #3645

And also https://kubernetes.io/docs/tasks/tools/install-kubectl/ of course, including packages:

```
sudo apt-get install -y kubectl
```

```
su -c "yum install -y kubectl"
```

**Comment by josedonizetti** [comment]
Wonder if instead, we should support a `minikube install`? I really like the idea of removing the complexity of installation, but why stop at `kubectl`? 
There are other dependencies we could also install. Like `docker-driver-machine-kvm2` or `docker-driver-machine-hyperkit`, maybe support a `--upgrade` flag.

**Comment by afbjorklund** [comment]
Mostly because we install those other components on the VM ? And I don't want to install `docker`.

The drivers are a special case, wonder if we shouldn't just bundle them (like the virtualbox one) ?
But yeah, downloading those are needed - but probably automatically, rather than a command.

We should use the same functions underneath, but not sure if we need a `minikube install` cmd.

----

Note that there are benefits to _not_ install kubectl too, such as having multiple versions available.

We could also do some half-way approach, by printing the path to the `kubectl` (but not run it) ?

**Comment by josedonizetti** [comment]
That's true, it wouldn't make sense to install docker or podman. And an `install` sounds too generic, better to stick with improving kubectl,  I like both new flags ideas `--install` and `--prefix`.

**Comment by afbjorklund** [comment]
Typical usage:

``` console
$ minikube kubectl --install
💣  Failed to write kubectl: open /usr/local/bin/kubectl: permission denied
$ sudo minikube kubectl --install
$ 
```

or alternatively:

``` console
$ install $(minikube kubectl --path) /usr/local/bin
install: cannot remove '/usr/local/bin/kubectl': Permission denied
$ sudo install $(minikube kubectl --path) /usr/local/bin
$ 
```

The main plan for the machine drivers is to provide them as packages and improve documentation.
I think that ultimately we want to improve packaging for minikube, so it matches the other platforms ?

https://github.com/kubernetes/minikube#installation

* `brew cask install minikube`

* `choco install minikube`

* `sudo apt install minikube` or
`su -c "yum install minikube"`

Then we would also get some modern features like _compression_ or _checksums_... Imagine that. ☺️
But I suppose we could also consider using the already provided .tar.gz (no XZ yet) and SHA512 ?

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.15.md#client-binaries

* 41M	kubectl-linux-amd64
* 13M	kubernetes-client-linux-amd64.tar.gz

**Comment by afbjorklund** [comment]
Request declined
