### ISSUE TITLE
Minikube 

### ISSUE THREAD

**Issue by AdilAkhtarZia** [kubernetes/minikube#4708]
adilakhter@adilakhter-HP-EliteBook-8470p:~$ minikube start
😄  minikube v1.2.0 on linux (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
E0708 05:47:19.440506    3656 start.go:559] StartHost: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

💣  Unable to start VM: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by beachcoder25** [comment]
Same issue here:

😄  minikube v1.2.0 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0709 11:21:49.579154   19197 start.go:559] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.769162 Power up failed (vrc=VERR_VMX_MSR_ALL_VMX_DISABLED, rc=NS_ERROR_FAILURE (0X80004005))

💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.769162 Power up failed (vrc=VERR_VMX_MSR_ALL_VMX_DISABLED, rc=NS_ERROR_FAILURE (0X80004005))

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Frustrated as this is the most basic step in the setup, but have no idea how to resolve...**

**Comment by AbdullahBM** [comment]
After reading errors it seems you have not enabled VT-x / vertualization on your machine. So restart you PC, go to the BIOS and enable VT-x / vertualization here. Save it and try start minikube again.

**Comment by afbjorklund** [comment]
@beachcoder25 : please open new issues for different problems, thanks.

You might want to check the VirtualBox documentation, on how to set it up.

**Comment by AdilAkhtarZia** [comment]
> After reading errors it seems you have not enabled VT-x / vertualization on your machine. So restart your PC, go to the BIOS and enable VT-x / vertualization mode there. Save it and try start minikube again.

after enabling, this error is 
occurring

**Comment by afbjorklund** [comment]
@AdilAkhtarZia : sorry for the noise above, it seems like something is wrong with your existing VM

You might want to delete it and start over ?

**Comment by AdilAkhtarZia** [comment]
> @AdilAkhtarZia : sorry for the noise above, it seems like something is wrong with your existing VM
> 
> You might want to delete it and start over ?

it's working .. thanks
