### ISSUE TITLE
Validate cached ISO

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#471]
One of the causes of #431 is that an iso file can sometime be corrupted and then cached.  While I'm not exactly sure why this would happen - (e.g. downloading behind proxy, storage.googleapis.com down), This causes all subsequent minikube starts to fail.  There are a few ways I think we can try to remedy a corrupt ISO thats being cached:

1. Check a hash against the release versions of minikube-iso 
What versions do we check?  We would need to start keeping track of the release SHAs like we do for the binary.  We might need to make sure users are using up to date versions of the ISOs.

2. Check the error on the http call requesting the ISO https://github.com/kubernetes/minikube/blob/v0.7.1/pkg/minikube/cluster/cluster.go#L310
This isn't a great solution because it won't catch the times where we get a status 200 but not an ISO (afaik ISOs can be any format so I'm not sure how to detect one besides the above method).

**Comment by dlorenc** [comment]
We should stick the SHAs into a json somewhere, and validate that way.

**Comment by dlorenc** [comment]
Maybe also clear the cache if the VM failed to start for any reason.
