### ISSUE TITLE
Error starting kubernetes cluster using minikube on Mac

### ISSUE THREAD

**Issue by zonghaishang** [kubernetes/minikube#4710]
➜  ~ minikube start
😄  minikube v1.2.0 on darwin (amd64)

⚠️  Ignoring --vm-driver=hyperkit, as the existing "minikube" VM was created using the none driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=hyperkit`
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`

🔄  Restarting existing none VM for "minikube" ...
⌛  Waiting for SSH access ...

💣  Failed to enable container runtime: running command: sudo systemctl start docker: exit status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

➜  ~ uname -a
Darwin localhost 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64

**Comment by afbjorklund** [comment]
The none driver doesn't work on Mac, you will have to delete the VM and start over

Same as #4498

**Comment by medyagh** [comment]
We are working on adding support for vm free minikube on all platforms, please stay tuned !
https://github.com/kubernetes/minikube/issues/4389

**Comment by afbjorklund** [comment]
It will be VM free on Linux at least, but on Mac and Win it will instead use Docker's VM.

**Comment by zonghaishang** [comment]
I have tried `minikube delete -p minikube` & `minikube delete`， It still reports the same error. 

@afbjorklund 
> The none driver doesn't work on Mac, you will have to delete the VM and start over
what should I do ？

**Comment by afbjorklund** [comment]
I was assuming that you wanted to change drivers to hyperkit ?

`minikube start --vm-driver=hyperkit`

If you deleted the old one, there should be no more "none"...

**Comment by zonghaishang** [comment]
I deleted the cache file(`~/.minikube`) and the minikube took effect.

**Comment by zonghaishang** [comment]
`step1` : remove cache file `~/.minikube`
`step2`: minikube start -p minikube --vm-driver=hyperkit

```
➜  ~ minikube start -p minikube --vm-driver=hyperkit
😄  minikube v1.2.0 on darwin (amd64)
💿  Downloading Minikube ISO ...
 129.33 MB / 129.33 MB [============================================] 100.00% 0s
🔥  Creating hyperkit VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
💾  Downloading kubelet v1.15.0
💾  Downloading kubeadm v1.15.0
🚜  Pulling images ...
🚀  Launching Kubernetes ...
⌛  Verifying: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"
➜  ~ kubectl cluster-info
Kubernetes master is running at https://192.168.64.3:8443
KubeDNS is running at https://192.168.64.3:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

**Comment by zonghaishang** [comment]
@afbjorklund thanks.

**Comment by zonghaishang** [comment]
close it now.

**Comment by aws-adjustmentbureau** [comment]
I also found a way to mitigate the error. I changed the VM driver to VirtualBox instead of hyperkit

**Comment by dguyhasnoname** [comment]
Step I followed to fix it:
```
Sat Jun 13 08:34 PM IST: kubernetes.docker.internal:6443: service$ minikube start --cpus=4 --memory=4096 --disk-size=30g --vm-driver=hyperkit  --extra-config=apiserver.authorization-mode=RBAC
😄  minikube v1.11.0 on Darwin 10.15.5
💥  The existing "" VM was created using the "" driver, and is incompatible with the "hyperkit" driver.
👉  To proceed, either:

1) Delete the existing "" cluster using: 'minikube delete -p '

* or *

2) Start the existing "" cluster using: 'minikube start -p  --driver='

💣  Exiting.

Sat Jun 13 08:35 PM IST: kubernetes.docker.internal:6443: service$ minikube delete -p minikube & minikube delete
[1] 4400
🔥  Removing /Users/mukund/.minikube/machines/minikube ...
🔥  Removing /Users/mukund/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.
💀  Removed all traces of the "minikube" cluster.
[1]+  Done                    minikube delete -p minikube

Sat Jun 13 08:36 PM IST: kubernetes.docker.internal:6443: service$ minikube start --cpus=4 --memory=4096 --disk-size=30g --vm-driver=hyperkit  --extra-config=apiserver.authorization-mode=RBAC
😄  minikube v1.11.0 on Darwin 10.15.5
✨  Using the hyperkit driver based on user configuration
💾  Downloading driver docker-machine-driver-hyperkit:
    > docker-machine-driver-hyperkit.sha256: 65 B / 65 B [---] 100.00% ? p/s 0s
    > docker-machine-driver-hyperkit: 10.90 MiB / 10.90 MiB  100.00% 3.67 MiB p
🔑  The 'hyperkit' driver requires elevated permissions. The following commands will be executed:

    $ sudo chown root:wheel /Users/mukund/.minikube/bin/docker-machine-driver-hyperkit 
    $ sudo chmod u+s /Users/mukund/.minikube/bin/docker-machine-driver-hyperkit 


Password:
💿  Downloading VM boot image ...
    > minikube-v1.11.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.11.0.iso: 174.99 MiB / 174.99 MiB [ 100.00% 16.00 MiB p/s 11s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4: 191.81 MiB
```
