### ISSUE TITLE
virtualbox 6.0.8: The vboxdrv kernel module is not loaded

### ISSUE THREAD

**Issue by ghostman8877** [kubernetes/minikube#4711]
Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0708 18:43:14.899457    9017 start.go:559] StartHost: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The vboxdrv kernel module is not loaded. Either there is no module\n         available for the current kernel (4.18.0-25-generic) or it failed to\n         load. Please recompile the kernel module and install it by\n\n           sudo /sbin/vboxconfig\n\n         You will not be able to start VMs until this problem is fixed.\n6.0.8r130520". Please upgrade at https://www.virtualbox.org

💣  Unable to start VM
❌  Error:         [VBOX_KERNEL_MODULE_NOT_LOADED] create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The vboxdrv kernel module is not loaded. Either there is no module\n         available for the current kernel (4.18.0-25-generic) or it failed to\n         load. Please recompile the kernel module and install it by\n\n           sudo /sbin/vboxconfig\n\n         You will not be able to start VMs until this problem is fixed.\n6.0.8r130520". Please upgrade at https://www.virtualbox.org
💡  Advice:        Run 'sudo modprobe vboxdrv' and reinstall VirtualBox if it fails.
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/4043
Help me pls!

**Comment by AbdullahBM** [comment]
Try start minikube without VM. Write below command (write sudo if necessary):

minikube start --vm-driver=none

For this command, minikube won't require VM instance. Instead it makes your machine as a worker/master node.

**Comment by afbjorklund** [comment]
@AbdullahBM : note that there are some severe limitations of the none driver
https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

**Comment by tstromberg** [comment]
Hey @ghostman8877 - 

Your VirtualBox installation failed to build the appropriate kernel driver. Please try installing VirtualBox 6.0.10 to see if the process fixes your issue. If it isn't successful for whatever reason, please try the `kvm2` driver .

https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver

Thank you!

**Comment by John-Dormevil** [comment]
Try to:
- Deactivate Secure Boot from your bios system;
- Then run `sudo /sbin/vboxconfig` in case you install and use virtualbox 6+
- Then `minikube start`

**Comment by adarshaJha** [comment]
when i run `sudo minikube start --vm-driver=none` it gives me this error ( ubuntu 16.0.4)
```
💣  Error starting cluster: cmd failed: sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap

: running command: sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
 output: [init] Using Kubernetes version: v1.16.2
[preflight] Running pre-flight checks
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING Swap]: running with swap on is not supported. Please disable swap
	[WARNING FileExisting-ebtables]: ebtables not found in system path
	[WARNING FileExisting-socat]: socat not found in system path
	[WARNING SystemVerification]: this Docker version is not on the list of validated versions: 19.03.4. Latest validated version: 18.09
	[WARNING Hostname]: hostname "minikube" could not be reached
	[WARNING Hostname]: hostname "minikube": lookup minikube on 127.0.1.1:53: no such host
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
	[WARNING Port-10250]: Port 10250 is in use
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10251]: Port 10251 is in use
	[ERROR Port-10252]: Port 10252 is in use
	[ERROR Port-2380]: Port 2380 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
: running command: sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
.: exit status 1

```

**Comment by ErKriti** [comment]
> Try to:
> 
>     * Deactivate Secure Boot from your bios system;
> 
>     * Then run `sudo /sbin/vboxconfig` in case you install and use virtualbox 6+
> 
>     * Then `minikube start`

Does it help someone? I am also facing the same issue on Windows 10 Home Ubuntu 18.04 and VirtualBox 6.1
