### ISSUE TITLE
minikube crashed virtualbox after update

### ISSUE THREAD

**Issue by leonbr0wn** [kubernetes/minikube#4714]
I grabbed v1.2 to upgrade 0.34. As it was "upgrading" I got guru meditation state and loss of access to the VM (and the  virtualbox GUI).

I searched for removing minikube and decided to delete the contents of ~/.minikube. I wish I hadn't; now VirtualBox is as broken as minikube for me.

**Comment by afbjorklund** [comment]
Sometimes VirtualBox goes into a strange state, and decides to corrupt .config/VirtualBox/VirtualBox.xml
Fortunately it usually saves a copy as "VirtualBox.xml-prev", that can be used to restore some of it...

Anyway, deleting `~/.minikube` shouldn't affect VirtualBox except for making some VMs inaccessible perhaps (the ones that were residing in that folder). But the "guru meditation state" sounds unrelated.

**Comment by leonbr0wn** [comment]
Unrelated indeed. After a full restart (ie crash) Oracle VM VirtualBox Manager was able to finalize any clean up and wipe the slate.
