### ISSUE TITLE
Oracle VM: how to enable virtualization 

### ISSUE THREAD

**Issue by sgsumit** [kubernetes/minikube#4721]
Problem with enabling virtualization in ubuntu machine in oracle Vm

**Comment by AbdullahBM** [comment]
Restart your PC, go to BIOS  and then enable Vertualization there.

**Comment by afbjorklund** [comment]
@AbdullahBM : restarting doesn't really work, when running in a VM.

**Comment by afbjorklund** [comment]
Enabling nested virtualization in VirtualBox ("Oracle" ?) is normally not what you want to do.

If you create a new VM just for minikube, you can run it with the `none` VM driver (and `sudo`)
See https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

Or you can let minikube create the VM for you ?

**Comment by tstromberg** [comment]
This seems like a better question for Oracle.

https://help.ubuntu.com/community/KVM/Installation documents what commands you can run in Ubuntu to validate that virtualization is enabled. Once Ubuntu is happy (`virt-host-validate` is a great way to confirm), minikube should be happy.

Please re-open if this does not turn out to be helpful.
