### ISSUE TITLE
Failed to update cluster: downloading binaries: copying kubeadm: copy: error creating file at /usr/bin/kubeadm: open /usr/bin/kubeadm: permission denied

### ISSUE THREAD

**Issue by jstaffor** [kubernetes/minikube#4722]
[jstaffor@jstaffor kub]$ sudo minikube start --vm-driver=none
😄  minikube v1.2.0 on linux (amd64)
🔥  Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.06.0-ce
💾  Downloading kubeadm v1.15.0
💾  Downloading kubelet v1.15.0

💣  Failed to update cluster: downloading binaries: copying kubeadm: copy: error creating file at /usr/bin/kubeadm: open /usr/bin/kubeadm: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by afbjorklund** [comment]
Same as #3718 ?

Why does root not have write access to /usr/bin ? Sounds a bit odd. Which linux distribution ?

**Comment by jstaffor** [comment]
Ok, I've just rerun the command and it was successful in that it has progressed past the point of fail (reported above)  :+1: 

Description :
This package contains the NodeSource NodeJS repository
GPG key as well as configuration for yum.
Name        : epel-release
Version     : 7
Release     : 11
Architecture: noarch
Install Date: Tue 21 May 2019 15:18:05 IST
Group       : System Environment/Base
Size        : 24834
License     : GPLv2
Signature   : RSA/SHA256, Mon 02 Oct 2017 18:52:02 IST, Key ID 6a2faea2352c64e5
Source RPM  : epel-release-7-11.src.rpm
Build Date  : Mon 02 Oct 2017 18:45:58 IST
Build Host  : buildvm-ppc64le-05.ppc.fedoraproject.org
Relocations : (not relocatable)
Packager    : Fedora Project
Vendor      : Fedora Project
URL         : http://download.fedoraproject.org/pub/epel
Summary     : Extra Packages for Enterprise Linux repository configuration

**Comment by jstaffor** [comment]
Success: "Done! kubectl is now configured to use "minikube""

**Comment by rzr** [comment]
IMHO, /usr/local should be used and not /usr/bin , which should be used by package manager for system...

**Comment by afbjorklund** [comment]
@rzr: that is #3718

Minikube does not use the package manager for installing kubeadm yet
