### ISSUE TITLE
feature-gates=Auditing=true: no matches for kind "Policy" in version "audit.k8s.io/v1beta1"

### ISSUE THREAD

**Issue by yashbhutwala** [kubernetes/minikube#4723]
**The exact command to reproduce the issue**:
`minikube start --feature-gates=Auditing=true`

**The output of the `minikube logs` command**:
```
unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kinddeployment.ex "Policy" in version "audittensions/defau.k8s.io/v1beta1"
```

**The operating system version**:
```
😄  minikube v1.2.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
🚜  Pulling images ...
🚀  Launching Kubernetes ...
⌛  Verifying: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"
```

**Comment by RA489** [comment]
@yashbhutwala I tried this on Linux 16.04 with Kubernetes v1.15.0 on Docker 18.09.7 but it works fine for me.

**Comment by RA489** [comment]
@yashbhutwala I am not able to reproduce your issue can you copy paste the environment you used Os etc ?

**Comment by yashbhutwala** [comment]
@RA489 

```
> uname -a
Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
```

**Comment by RA489** [comment]
@yashbhutwala Thanks! for detailed information.

**Comment by fenglixa** [comment]
@yashbhutwala  could you append the content of file "/etc/kubernetes/addons/audit-policy.yaml"? 
I used same platform:  Darwin 18.6.0 + Kubernetes v1.15.0 and Docker 18.09.6, without the issue you mentioned

**Comment by yashbhutwala** [comment]
@fenglixa here you go:
```
$ cat /etc/kubernetes/addons/audit-policy.yaml
apiVersion: audit.k8s.io/v1beta1
kind: Policy
rules:
- level: Metadata
```


Also, this is a different error about the same thing I got:

```
💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
    error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kINFO: == Kubernetes addon manager started at 2019ind "Policy" in version "audit.k8s.io/v-07-12T12:55:08+00:00 with ADDON_CHECK_INTERVAL_SEC=60 ==
    error: unable to recINFO: == Successfully started /opt/namespace.yaml inognize "/etc namespace  at 2019-07-12T12:55:09+00:00
```

**Comment by yashbhutwala** [comment]
@fenglixa what are you doing to set yours up?

**Comment by tstromberg** [comment]
I wonder if the Auditing is an obsolete feature gate? It's not mentioned here:

https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/

**Comment by tstromberg** [comment]
Anyone figure out if Auditing is still a thing?

**Comment by fenglixa** [comment]
I have not found the correct steps to enable auditing, another ticket is also related it #4488
 
I tested to use below CLI, try to enable auditing, but failed:
===============================

cat <<EOF > ~/.minikube/addons/audit-policy.yaml
# Log all requests at the Metadata level.
apiVersion: audit.k8s.io/v1
kind: Policy
rules:
- level: Metadata
EOF


minikube start \
--feature-gates=AdvancedAuditing=true \
--extra-config=apiserver.authorization-mode=RBAC \
--extra-config=apiserver.Audit.LogOptions.Path=/var/log/apiserver/audit.log \
--extra-config=apiserver.Audit.PolicyFile=/etc/kubernetes/addons/audit-policy.yaml




minikube start \
--feature-gates=Auditing=true \
--extra-config=apiserver.audit-log-path=/var/log/apiserver/audit.log \
--extra-config=apiserver.audit-policy-file='/etc/kubernetes/addons/audit-policy.yaml'


minikube start \
--feature-gates=AdvancedAuditing=true  \
--extra-config=apiserver.audit-log-path=/var/log/apiserver/audit.log



minikube start \
--extra-config=apiserver.feature-gates="AdvancedAuditing=true" \
--extra-config=apiserver.audit-log-path=/var/log/apiserver/audit.log


 ✘  ~/Documents/GitHub/minikube_fengli   master  minikube logs |grep audit
error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
error: unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"
t-policy.yaml": no matches for kind "Policy" in version "audit.k8s.cluiosterrolebindin/v1g.rbac.abetuthorizatia1"on.k8s.io
unable to recognize "/etc/kubernetes/addons/audit-policy.yaml": no matches for kind "Policy" in version "audit.k8s.io/v1beta1"

**Comment by medyagh** [comment]
we need to document it as mentioned in https://github.com/kubernetes/minikube/issues/4488

I will close this duplicate
