### ISSUE TITLE
param behave as kubelet's pod-infra-container-image 

### ISSUE THREAD

**Issue by wangweihong** [kubernetes/minikube#473]
When i used kubectl create pod ,always fail for

>  `image pull failed for gcr.io/google_containers/pause-amd64:3.0`

, I found a solution from [26873](https://github.com/kubernetes/kubernetes/issues/26873) , It need to  change  kubelet's pod-infra-container-image parameter .
Is minikube has param behave as kubelete's pod-infra-container-image parameter ?

**Comment by dlorenc** [comment]
Hey,

Thanks for the report. To support this we'd need to add a flag or config setting that gets passed into localkube, and change localkube to support this flag.

**Comment by dlorenc** [comment]
We'll consolidate this into the bigger issue of running minikube without internet access: #391

**Comment by Rev1408** [comment]
was this done, how to specify pod-infra-container-image in minikube
