### ISSUE TITLE
Minikube VM deleted via Hyper-V Manager now cannot create or delete minikube

### ISSUE THREAD

**Issue by baynezy** [kubernetes/minikube#4731]
I was having trouble with `minikube stop` and, it turns out foolishly, I thought that I could just start again with the whole thing by deleting the VM in Hyper-V Manager. However, now no `minikube` commands work. It may be related to #4459 

**The exact command to reproduce the issue**:
`minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"`

**The full output of the command that failed**:<details>
```
* minikube v1.2.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing hyperv VM for "minikube" ...
E0710 18:10:30.698752   21484 start.go:559] StartHost: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
```

</details>

**The output of the `minikube logs` command**:<details>
```
X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
```

</details>

**The operating system version**:
Windows 10 Pro Version 1803

**Comment by NotYourOracle** [comment]
I created an empty VM called minikube with no hard drive, reran 'minikube.exe delete' and it deleted. It wants to delete an object called minikube, it doesn't care if its the original one.

**Comment by baynezy** [comment]
@NotYourOracle - you clearly are my oracle. That worked perfectly thanks.
