### ISSUE TITLE
MinikubeRunner Copy function doesn't work and is unused

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#4735]
I was trying to use the MinikubeRunner [Copy](https://github.com/kubernetes/minikube/blob/master/test/integration/util/util.go#L68) function in an integration test, and nothing is copied over (because the `cat` command doesn't run anything!)

```golang
cmd := exec.Command("/bin/bash", "-c", path, "ssh", "--", fmt.Sprintf("cat >> %s", filepath.Join(f.GetTargetDir(), f.GetTargetName())))

```

It also doesn't seem like this function is used anywhere, so maybe removing it would be the best solution?

**Comment by afbjorklund** [comment]
The `Copy` is required by the [Runner](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/command/command_runner.go#L28) interface, but the implementation does seem a bit weird...

**Comment by khayamgondal** [comment]
@priyawadhwa @afbjorklund is it still open? I can work on it.

**Comment by medyagh** [comment]
@khayamgondal yes it is open and I would be happy to assign it to you. please let me know if you need any help !

**Comment by khayamgondal** [comment]
cool, you can put my name on it. I ll get back to you for the questions once I setup the envionrment.

**Comment by khayamgondal** [comment]
I think accidenlty you put your name on it:)

**Comment by medyagh** [comment]
Oops. Added you.

**Comment by khayamgondal** [comment]
@medyagh The goal here is to change the function's implementation to make copy work?

**Comment by medyagh** [comment]
Closing this issue since we ended up removing this unused code.
