### ISSUE TITLE
Update docker-env to export DOCKER_API_VERSION

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/minikube#474]
If you've got a different docker client to that in minikube's boot2docker.iso, any docker commands return the dreaded:

    Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.23)

If we export the `DOCKER_API_VERSION` env var in `docker-env` with the appropriate API version then this error won't be thrown. Docker seems to work fine too...

**Comment by wstrange** [comment]
I have also used Docker Version manager (brew install dvm) to manage this problem

I am not 100% sure setting the API_VERSION is always going to work?
