### ISSUE TITLE
none:  sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 

### ISSUE THREAD

**Issue by akshay-r-1996** [kubernetes/minikube#4742]
OS: RHEL 7.2
Minikube version: 1.12
Kubectl version: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
VM-Driver: None (Because I'm running on AWS instance)
Exact command to replicate this:

sudo -E ./minikube start --vm-driver=none
* minikube v1.2.0 on linux (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing none VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.7
* Relaunching Kubernetes v1.15.0 using kubeadm ...

X Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by afbjorklund** [comment]
Seems like there is an unclean previous installation, if you don't care about the contents of the cluster you might want to use `sudo kubeadm reset` (or use a new VM). Otherwise, the log from `kubeadm` is needed.

**Comment by akshay-r-1996** [comment]
How to uninstall kubectl and minikube completely ( Including configuration files) ?

**Comment by afbjorklund** [comment]
> How to uninstall kubectl and minikube completely ( Including configuration files) ?

Answered in the other issue: #4765 

Did running `kubeadm reset` and doing `minikube start` help anything for this VM ?

**Comment by akshay-r-1996** [comment]
I tried that, but it didn't work.

**Comment by afbjorklund** [comment]
The verbose minikube log might have some more clues. `minikube -v5`

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide the output of:

`sudo -E ./minikube start --vm-driver=none --alsologtostderr -v=5`

This will help us isolate the problem further. Thank you!

**Comment by akshay-r-1996** [comment]
The issue is resolved, I had exported some wrong file in kubeconfig, I uninstalled the kubectl and reinstalled it got resolved. Thanks for helping me out.
