### ISSUE TITLE
E0714 06:11:42.285508   12236 start.go:559] StartHost: start: exit status 1

### ISSUE THREAD

**Issue by Sdator** [kubernetes/minikube#4753]
My system Windows 10
PowerShell version 5.0
The following is the error message.
======================================
```powershell
PS C:\Windows\system32>minikube start --vm-driver hyperv --hyperv-virtual-switch="Docker" -p "K8S"
* minikube v1.2.0 on windows (amd64)
* Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0714 06:06:49.516226    2500 start.go:559] StartHost: create: creating: open /Users/Air/.minikube/cache/iso/minikube-v1.2.0.iso: The system cannot find the path specified.

X Unable to start VM
* Error:         [NON_C_DRIVE] create: creating: open /Users/Air/.minikube/cache/iso/minikube-v1.2.0.iso: The system cannot find the path specified.
* Advice:        Run minikube from the C: drive.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/1574

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new
```
==========================================================
$MINIKUBE_HOME=$env:USERPROFILE + "\\.minikube"
[Environment]::SetEnvironmentVariable('MINIKUBE_HOME', $MINIKUBE_HOME, "User")

I solved this error by setting MINIKUBE_HOME. When I run the command again, another error is reported.
===========================================================
```powershell
PS C:\Windows\system32> minikube start --vm-driver hyperv --hyperv-virtual-switch="Docker" -p "K8S"
* minikube v1.2.0 on windows (amd64)
* Restarting existing hyperv VM for "K8S" ...
E0714 06:11:42.285508   12236 start.go:559] StartHost: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
```

**Comment by tstromberg** [comment]
Thank you for sharing your experience! If you don't mind, could you please run `minikube delete` and attempt the same thing again with additional logging:

`minikube start --vm-driver hyperv --hyperv-virtual-switch="Docker" -p "K8S" --alsologtostderr -v=8`

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment]
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!
