### ISSUE TITLE
hyperv: vswitch "minikube" not found

### ISSUE THREAD

**Issue by shadabkhan921** [kubernetes/minikube#4754]

**Comment by shadabkhan921** [comment]
Unable to provide MiniKube in Windows


X Unable to start VM: create: precreate: vswitch "minikube" not found

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
Please see note here about creating a network switch:

https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyper-v-driver

Admittedly, the user experience here is terrible. #4079 will address this.
