### ISSUE TITLE
Does kube-bench run on minikube?

### ISSUE THREAD

**Issue by Avy4140** [kubernetes/minikube#4764]
Can I Run Kube bench on my Minikube?

**Comment by tstromberg** [comment]
I'm not sure anyone has tried to make instructions for it - but I don't see why it wouldn't work.

Any luck with it yourself?

**Comment by Avy4140** [comment]
Still no luck for me but I need to do it. If you get something please let me know I’m still researching on the same.

**Comment by tstromberg** [comment]
I believe the answer is "Yes", but I also still haven't seen a tutorial to make it work. If someone else out there is willing to look into it, I'd like to see it added to https://minikube.sigs.k8s.io/docs/tutorials/

**Comment by nanikjava** [comment]
FYI : @tstromberg ran kube-bench on 'master' branch and here is the output https://gist.github.com/nanikjava/71ef16e6558253a082f466803fd5b9d9

**Comment by medyagh** [comment]
@Avy4140 @nanikjava  it seems like kube-bench runs on minikube just fine  ? I am closing this issue, please feel free if you have any other questions.
