### ISSUE TITLE
Host name ' ' contains bad letter

### ISSUE THREAD

**Issue by ashwini-git** [kubernetes/minikube#4766]
while following steps to install KVM2 driver - following code generates error as "Host name '' contains bad letter.

curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2 \
  && sudo install docker-machine-driver-kvm2 /usr/local/bin/

virsh version available on my Azure Ubuntu VM   is 4.0.0

Please let me know if you can help , i am working on to setup Minikube into Azure NV6 promo VM.

**Comment by afbjorklund** [comment]
Hmm, curl not working ? Does wget work better ?

`wget https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2`

Maybe some kind of proxy issue in Azure perhaps

**Comment by ashwini-git** [comment]
wget worked as expected. Thanks
