### ISSUE TITLE
pkg/util: TestTeePrefix has race conditition

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#4767]
There is something unsafe going on, with the use of `Scanner` in TeePrefix:

[Build #7345](https://travis-ci.org/kubernetes/minikube/builds/559008902) failed: 

```
--- FAIL: TestTeePrefix (0.00s)
    utils_test.go:197: output="", want: "goo\ng\r\n\r\nle"
    utils_test.go:203: log="", want: "(:goo)(:g)(:le)"
```

Reproducer:

`GO111MODULE=on go test -race ./pkg/util/utils.go ./pkg/util/utils_test.go`

WARNING: DATA RACE

**Comment by afbjorklund** [comment]
Still there, but moved to pkg/minikube/command/ssh_runner_test.go

/remove-lifecycle stale

**Comment by medyagh** [comment]
@afbjorklund 
hopefully this was fixed by https://github.com/kubernetes/minikube/pull/8335

please reopen if it is not
