### ISSUE TITLE
macOS: waiting for k8s-app=kube-dns: timed out waiting for the condition

### ISSUE THREAD

**Issue by ragagit** [kubernetes/minikube#4771]
When trying to start the latest version of Minikube on macOS High Sierra 10.13.6 it crashes. I used to have an older version that was working but it was one year old so it was updated. I uninstalled and reinstalled minikube ( using brew cask install minikube ) but the same result. This happens on my work Mac.However I have another Mac at home no previous installation ob mink and seems to be working. 

![Screen Shot 2019-07-14 at 3 51 34 PM](https://user-images.githubusercontent.com/8247934/61301174-66f6a180-a7b1-11e9-9fa1-b8d090947047.png)

**Comment by butuzov** [comment]
Running same `minikube` version. No problems observed.

![image](https://user-images.githubusercontent.com/651824/61471303-38342300-a98b-11e9-967b-939515b1fb35.png)

Try to remove context and VirtualBox machine manually or upgrade Docker...

**Comment by tstromberg** [comment]
Hey @ragagit - sorry that you are running into this issue. Do you mind attaching the output of these two commands:

`minikube logs`
`sudo lsof -i UDP:53`

I am also curious if `minikube delete` works around the issue. Thanks for the report!

**Comment by ragagit** [comment]
The minikube delete worked. Thanks for your prompt reply. Sorry I should have said so. Thanks again!
