### ISSUE TITLE
Prototype Docker deployment model

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4772]
Tracking work for initial work toward #4389

**Comment by afbjorklund** [comment]
Was there any branch (or WIP) connected with this PR ?

**Comment by afbjorklund** [comment]
This WIP seems somewhat related: #5188

**Comment by tstromberg** [comment]
I'm going to call this prototyped for purposes of v1.4.0. Let's aim to get the code moved to kubernetes/minikube with a design doc in and have it merged for v1.5.0.
