### ISSUE TITLE
hyperv reuse: StartHost: start: exit status 1 (VM does not exist!)

### ISSUE THREAD

**Issue by ankitajaiswal1989** [kubernetes/minikube#4775]
After running the below command, the minikube is not able to start the k8 cluster
minikube start --vm-driver=hyperv --hyperv-virtual-switch=PrimaryVirtualSwitch

* minikube v1.2.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing hyperv VM for "minikube" ...
E0716 21:44:07.247579   15332 start.go:559] StartHost: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
Do you mind adding the following flags:

`-v=8 --alsologtosderr`

That should provide the additional output we need to solve the issue.

**Comment by Sergey123456** [comment]
PS D:\> minikube start -v=8 --vm-driver hyperv --cpus 4 --memory=4096 --hyperv-virtual-switch "ExternalSwitch"
* minikube v1.2.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM


* Restarting existing hyperv VM for "minikube" ...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minikube
[stdout =====>] :
[stderr =====>] : Hyper-V\Start-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.StartVM


E0716 21:26:09.149826    1592 start.go:559] StartHost: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
The root cause here is that the "minikube" VM was deleted from Hyper-V, from outside the `minikube` command. 

The workaround here is to run `minikube delete`

If we could fix #3206 - this would be a much better user experience.

**Comment by tstromberg** [comment]
This should be improved now.
