### ISSUE TITLE
Many local commands block on network.

### ISSUE THREAD

**Issue by warpfork** [kubernetes/minikube#479]
The online version check, placed in the default `PreRun` hooks in the command parser, makes many operations that should be purely local (and consistently _fast_) into potentially long-blocking calls.

Expected: commands like `minikube stop` should be able to stop a local VM immediately.  It should not depend on whether I'm on flaky cafe wifi ;)

This may accumulate into a significant performance problem if one scripts a series of interactions with minikube -- a half-dozen minikube commands multiplied by a network latency that varies between ~0s and ~15s (my life right now, I know, I know, but it's true) makes what should be a fast and beautiful user story into several minutes of waiting.

Can I disable version checking with a flag or env var of some kind, so my script over $n minikube commands doesn't need to make $n identical network requests?

**Comment by heavenlyhash** [comment]
Related, previously: https://github.com/kubernetes/minikube/issues/408

**Comment by r2d4** [comment]
You can add a `WantUpdateNotification: false` to a `~/.minikube/config/config.yml` to disable version checking

**Comment by heavenlyhash** [comment]
Awesome, that's a solution to my issues.  Thanks!

I just checked doing it in both `config.yml` and `config.json` and it works in either place.

Is this also settable by flag or env var, if I'm writing a script for other people to use, and don't want to alter their homedir contents?

**Comment by r2d4** [comment]
Glad that worked for you.  As far as the flag/env, its not possible right now but we could consider that for a future release.  

I'll let @dlorenc and @aaron-prindle weigh in on that.

**Comment by dlorenc** [comment]
Yeah it makes sense to me, viper allows binding env vars, right?

**Comment by jimmidyson** [comment]
Yep - viper is super flexible & would support automatic binding something like `MINIKUBE_WANTUPDATENOTIFICATION`. Just a case of enabling it.

**Comment by zoidbergwill** [comment]
Having it only check occasionally would also be useful, and would make scripts faster the majority of the time too?

Python's `pip` does a similar thing:

```
$ cat virtualenv/pip-selfcheck.json                                                                                                                                                                                                             
{"last_check":"2016-08-12T14:56:49Z","pypi_version":"8.1.2"}
```

**Comment by dlorenc** [comment]
Yes, we should make the version check asynchronous. The check should only happen once every 24 hours already, but if you run many commands at the same time it's possible they'd all do the check.

**Comment by aaron-prindle** [comment]
Ref: #671
