### ISSUE TITLE
Investigate: config.ReadConfig()  seems to be not used

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4795]
https://github.com/kubernetes/minikube/blob/4178c4486d29c3616560f21f2fd85e1c677e1333/pkg/minikube/config/config.go#L73

```
// ReadConfig reads in the JSON minikube config
func ReadConfig() (MinikubeConfig, error) {
	f, err := os.Open(constants.ConfigFile)
	if err != nil {
		if os.IsNotExist(err) {
			return make(map[string]interface{}), nil
		}
		return nil, fmt.Errorf("open %s: %v", constants.ConfigFile, err)
	}
	defer f.Close()

	m, err := decode(f)
	if err != nil {
		return nil, fmt.Errorf("decode %s: %v", constants.ConfigFile, err)
	}

	return m, nil
}

```

**Comment by medyagh** [comment]
it worth noting, 

we have two places for config now
one for profiles
` ~/.minikube/profiles/p1/config.json`

and one that seems to be global:
` ~/.minikube/config/config.json`

the second one seems to be global, and is used for caching images.

**Comment by medyagh** [comment]
related
`./out/minikube config view ` does not respect profile

**Comment by tstromberg** [comment]
Is this obsolete? As best as I can tell, `config.ReadConfig` is used in a handful of locations.
