### ISSUE TITLE
[NON_C_DRIVE] when run from C:\ but user config is on different drive

### ISSUE THREAD

**Issue by shreyasp91** [kubernetes/minikube#4802]
Unable to get Minikube start even when I do it from C: Drive

I run the below command and receive the below error 

C:\Kubernetes>minikube start
* minikube v1.2.0 on windows (amd64)
* Downloading Minikube ISO ...
 129.33 MB / 129.33 MB [============================================] 100.00% 0s
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0718 09:14:58.371558   12332 start.go:559] StartHost: create: creating: open /.minikube/cache/iso/minikube-v1.2.0.iso: The system cannot find the path specified.

X Unable to start VM
* Error:         [NON_C_DRIVE] create: creating: open /.minikube/cache/iso/minikube-v1.2.0.iso: The system cannot find the path specified.
* Advice:        Run minikube from the C: drive.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/1574

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new

+ After some digging in I found the .minikube folder is getting created on the :H network drive, this is my company provided PC, i'm not sure if its has anything to do with permission.
+ when ever I open the windows CMD its start with H: and I navigate to C: and run the command, yet for some reason the .minikube gets created in :H.

![image](https://user-images.githubusercontent.com/53029363/61428152-8cfd7c80-a93e-11e9-814d-1b942fb9fc1e.png)

![image](https://user-images.githubusercontent.com/53029363/61428528-15305180-a940-11e9-9125-081d6485b5e1.png)

+ I'm new to this, just started to learn K8s, any help on this is deeply appreciated.

Version :- Windows 10

Regards,
Shreyas

**Comment by tstromberg** [comment]
Hey @shreyasp91 - I'm sorry to hear that this is not working correctly on your machine. I think you may have found a situation I wasn't aware of. Do you mind trying this for me:

`setx MINIKUBE_HOME=C:\\Kubernetes\\.minikube`

And running `minikube <your arguments> --alsologtostderr -v=8`

If that doesn't work, try:

`setx MINIKUBE_HOME=/Kubernetes/.minikube`

I imagine other people are running into this, so I would really like to see this get fixed soon.

**Comment by shreyasp91** [comment]
Hi @tstromberg ,

 Thank you so much, I ran "setx MINIKUBE_HOME C:\\Kubernetes\\.minikube" and it worked like a charm.

Regards,
Shreyas

[minikube install verbose.txt](https://github.com/kubernetes/minikube/files/3413720/minikube.install.verbose.txt)

**Comment by tstromberg** [comment]
I haven't tried - but as far as I know, this is still an issue in v1.4.
