### ISSUE TITLE
Detect --extra-config issues immediately rather than waiting 10 minutes

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4806]
If a user feeds bad data into apiserver, the apiserver crashes immediately with messages that can be found using `minikube logs --problems`. 

```
 ~  minikube logs --problems                                  Thu 18 Jul 2019 09:29:35 AM PDT
❌  Problems detected in "kube-apiserver":
    error: invalid audit log mode 777, allowed modes are "batch,blocking,blocking-strict"
❌  Problems detected in "kube-addon-manager":
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
```

This makes experimentation hard. Instead of telling users about it immediately, we currently make them wait ~8 minutes. We can do better :)

**Comment by tstromberg** [comment]
Example command-line:

`minikube start --extra-config=apiserver.audit-dynamic-configuration=true --extra-config=apiserver.audit-policy-file=- --extra-config=apiserver.audit-log-path=- --extra-config=apiserver.audit-log-mode=777 --extra-config=apiserver.audit-log-maxage=5 --extra-config=apiserver.audit-log-maxbackup=5 --feature-gates=DynamicAuditing=true`

**Comment by tstromberg** [comment]
See #4488 and any of these issues for inspiration:

https://github.com/kubernetes/minikube/issues?utf8=✓&q=label%3Acause%2Fapiserver-flags+

**Comment by olivierlemasle** [comment]
This delay before failure is actually due to Kubeadm. I logged an issue there, that was closed because it's not currently possible: https://github.com/kubernetes/kubeadm/issues/1690

**Comment by tstromberg** [comment]
Still an issue in minikube v1.6. 

When we are waiting for the apiserver to become healthy, it would be nice to notice these failures and surface them in real time. Help wanted!
