### ISSUE TITLE
cluster_test is slow and is making unnecessary socket calls.

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4810]
cluster_test takes 6 minutes to run in travis:

`ok  	k8s.io/minikube/pkg/minikube/cluster	360.314s	coverage: 50.6% of statements`

I happened to strace it locally and notice that it was making socket calls. Probably for a health check.

**Comment by afbjorklund** [comment]
I think this is fixed in PR #4525 with 428929d7f50318ee638ad72bced0271c2d2db744

Seems like it was trying to set the VM clock, using SSH commands (that all time out) ?

**Comment by afbjorklund** [comment]
Fixed in 2b49a8d8d9a4ac0ac0b040fa738cc2bac66d7beb
