### ISSUE TITLE
error: yaml: line 2: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by Avy4140** [kubernetes/minikube#4815]
Asarma-M15MBP:~ asarma$ curl -LO https://k8s.io/examples/application/wordpress/mysql-deployment.yaml
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 185 100 185 0 0 671 0 --:--:-- --:--:-- --:--:-- 672
100 1238 100 1238 0 0 2009 0 --:--:-- --:--:-- --:--:-- 2009
Asarma-M15MBP:~ asarma$ curl -LO https://k8s.io/examples/application/wordpress/wordpress-deployment.yaml
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 185 100 185 0 0 1019 0 --:--:-- --:--:-- --:--:-- 1022
100 1323 100 1323 0 0 3165 0 --:--:-- --:--:-- --:--:-- 3165
Asarma-M15MBP:~ asarma$ nano kustomization.yaml
Asarma-M15MBP:~ asarma$ kubectl apply -k ./
error: yaml: line 2: mapping values are not allowed in this context
Asarma-M15MBP:~ asarma$
Im trying to Add resource configs for MySQL and WordPress and getting this error on my minikube. What can be the issue?

**Comment by afbjorklund** [comment]
Make sure to check the YAML files for syntax, a tool like `yamllint` might help with this.

It seems like there is something wrong a start of your document, maybe a curly dash or so ?

**Comment by tstromberg** [comment]
Closing as this bug is with the YAML input, and minikube isn't involved in the parsing.

**Comment by pranky89** [comment]
You might have done what most people did, simply copy pasting what's mentioned, including EOF and cat commands in the yaml file which isn't going to work. What actually needs to go in kustomization.yaml is this :

**--- 
resources: 
  - mysql-deployment.yaml
  - wordpress-deployment.yaml**

**Comment by iamamjad** [comment]
i believe this work with me ... 


secretGenerator:
- name: mysql-pass
  literals:
  - password=root
  
--- 
resources: 
  - mysql-deployment.yaml
  - wordpress-deployment.yaml

**Comment by afbjorklund** [comment]
So the real issue is here:
https://kubernetes.io/docs/tutorials/stateful-application/mysql-wordpress-persistent-volume/#create-a-kustomization-yaml

Where the command to run (`cat`) is mistaken for text to enter using an editor (`nano`)
