### ISSUE TITLE
hyperkit: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

### ISSUE THREAD

**Issue by LuckyLeavell2** [kubernetes/minikube#4822]
I attempt to add a driver for VMware Fusion 8 and then tried to remove it even uninstalling and reinstalling minikube.  

Extracted logs:
Luckys-MacBook-Pro:~ lucky$ minikube start --vm-driver hyperkit
😄  minikube v1.2.0 on darwin (amd64)
🔥  Creating hyperkit VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0719 13:49:52.386241   35261 start.go:559] StartHost: new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s

💣  Unable to start VM
❌  Error:         [DRIVER_CRASHED] new host: Error attempting to get plugin server address for RPC: Failed to dial the plugin server in 10s
💡  Advice:        The VM driver exited with an error, and may be corrupt. Run 'minikube start' with --alsologtostderr -v=8 to see the error
📘  Documentation: https://github.com/kubernetes/minikube/blob/master/docs/drivers.md

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new
Luckys-MacBook-Pro:~ lucky$ minikube start --alsologtostderr -v=8
I0719 13:50:24.546517   35300 notify.go:128] Checking for updates...
😄  minikube v1.2.0 on darwin (amd64)
I0719 13:50:25.570788   35300 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso
I0719 13:50:25.570974   35300 start.go:753] Saving config:
{
    "MachineConfig": {
        "KeepContext": false,
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso",
        "Memory": 2048,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "vmware",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "Hidden": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.15.0",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    }
}
I0719 13:50:25.571301   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.15.0 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.15.0
I0719 13:50:25.571336   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0719 13:50:25.571400   35300 cache_images.go:285] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at /Users/lucky/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1
I0719 13:50:25.571628   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I0719 13:50:25.571715   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
I0719 13:50:25.571461   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.15.0 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.15.0
I0719 13:50:25.571526   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.15.0 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.15.0
I0719 13:50:25.571548   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.15.0 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.15.0
I0719 13:50:25.571557   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I0719 13:50:25.571566   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/pause:3.1 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/pause_3.1
I0719 13:50:25.571602   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/etcd_3.3.10
I0719 13:50:25.571632   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/coredns_1.3.1
I0719 13:50:25.571694   35300 cache_images.go:285] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at /Users/lucky/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
I0719 13:50:25.574465   35300 cluster.go:90] Machine does not exist... provisioning new machine
I0719 13:50:25.574684   35300 cluster.go:91] Provisioning machine with config: {KeepContext:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso Memory:2048 CPUs:2 DiskSize:20000 VMDriver:vmware ContainerRuntime:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] XhyveDiskDriver:ahci-hd DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: GPU:false Hidden:false NoVTXCheck:false}
🔥  Creating vmware VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0719 13:50:25.575445   35300 start.go:559] StartHost: new host: Driver "vmware" not found. Do you have the plugin binary "docker-machine-driver-vmware" accessible in your PATH?
I0719 13:50:25.576842   35300 utils.go:123] non-retriable error: new host: Driver "vmware" not found. Do you have the plugin binary "docker-machine-driver-vmware" accessible in your PATH?
W0719 13:50:25.576941   35300 exit.go:100] Unable to start VM: new host: Driver "vmware" not found. Do you have the plugin binary "docker-machine-driver-vmware" accessible in your PATH?

💣  Unable to start VM: new host: Driver "vmware" not found. Do you have the plugin binary "docker-machine-driver-vmware" accessible in your PATH?

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by afbjorklund** [comment]
Where did you put the driver binary ? Somewhere like `/usr/local/bin` perhaps ?

> "Do you have the plugin binary "docker-machine-driver-vmware" accessible in your PATH?"

Or did you want to *stop* using vmware, and set another driver in your config ?

`minikube config`

**Comment by LuckyLeavell2** [comment]
Neither.  I am very new to kubernetes and was taking an introductory  course in it from SkillSoft. At first it complained because it could not find VirtualBox (because it is not installed on my MacBook). I could not find any list of appropriate values for the vm-driver and tried by guessing  "fusion" and then "vmware" by guessing. Other than Fusion, I had no additional driver installed.

From your reply, I need to download docker-machine-driver-vmware (from Docker?).  Would I then set vm-driver to docker-machine-driver-vmware after moving docker-machine-driver-vmware to /usr/local/bin (where the other executables mininikube are installed)? (I wanted to use Fusion because I am a VMware admin and run an ESXi server at home.)

**Comment by afbjorklund** [comment]
If you don't want to use VirtualBox, you need to download and install a driver for VMware.

Unfortunately, I am not aware which one is the best at the moment, there's also "fusion" ?

I _think_ this is the one you want, `docker-machine-driver-vmware`:

* https://github.com/machine-drivers/docker-machine-driver-vmware

> The VMware unified driver will eventually replace the existing vmwarefusion driver. The new unified driver supports both VMware Fusion (on macOS) and VMware Workstation (on Linux and Windows)

**Comment by LuckyLeavell2** [comment]
I downloaded the docker machine driver VMware for Mac OS-X above and did the following to install it:

chmod +x docker-machine-driver-vmware_darwin_amd64.dms
sudo mv docker-machine-driver-vmware_darwin_amd64.dms /usr/local/bin
sudo chown root:wheel /usr/local/bin/docker-machine-driver-vmware_darwin_amd64.dms
sudo chmod u+s  /usr/local/bin/docker-machine-driver-vmware_darwin_amd64.dms

ls -l /usr/local/bin
total 112752
lrwxr-xr-x  1 lucky  staff        28 Jul 19 09:24 brew -> /usr/local/Homebrew/bin/brew
lrwxr-xr-x  1 lucky  staff        54 Jun 30  2018 docker -> /Applications/Docker.app/Contents/Resources/bin/docker
lrwxr-xr-x  1 lucky  staff        62 Jun 30  2018 docker-compose -> /Applications/Docker.app/Contents/Resources/bin/docker-compose
lrwxr-xr-x  1 lucky  staff        77 Jun 30  2018 docker-credential-osxkeychain -> /Applications/Docker.app/Contents/Resources/bin/docker-credential-osxkeychain
lrwxr-xr-x  1 lucky  staff        62 Jun 30  2018 docker-machine -> /Applications/Docker.app/Contents/Resources/bin/docker-machine
-rwsr-xr-x  1 root   wheel       219 Jul 19 13:45 docker-machine-driver-hyperkit
-rwsr-xr-x@ 1 root   wheel   7679696 Jul 20 09:10 docker-machine-driver-vmware_darwin_amd64.dms
lrwxr-xr-x  1 lucky  staff        67 Jun 30  2018 hyperkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
-rwxr-xr-x  1 lucky  staff  48591648 Jul 19 09:05 kubectl
lrwxr-xr-x  1 lucky  staff        56 Jul 19 13:44 minikube -> /usr/local/Caskroom/minikube/1.2.0/minikube-darwin-amd64
lrwxr-xr-x  1 lucky  staff        54 Jun 30  2018 notary -> /Applications/Docker.app/Contents/Resources/bin/notary
lrwxr-xr-x  1 lucky  staff        65 Jun 30  2018 vpnkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.vpnkit

minikube config set vm-driver docker-machine-driver-vmware_darwin_amd64.dms

💣  Set failed: [driver "docker-machine-driver-vmware_darwin_amd64.dms" is not supported]

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

What am I doing wrong?

**Comment by LuckyLeavell2** [comment]
I also tried this:

minikube start --vm-driver docker-machine-driver-vmware_darwin_amd64.dms
😄  minikube v1.2.0 on darwin (amd64)
🔥  Creating docker-machine-driver-vmware_darwin_amd64.dms VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💡  unsupported driver: docker-machine-driver-vmware_darwin_amd64.dms

**Comment by tstromberg** [comment]
@LuckyLeavell2 - I believe this issue is now addressed by minikube v1.4, as it detects malfunctioning drivers. If you still see this issue with minikube v1.4 or higher, please reopen this issue by commenting with `/reopen`

We've also improved documentation on how to install the vmware driver: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

Hope this helps. Thank you for reporting this issue!
