### ISSUE TITLE
Add some Docker Machine documentation

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#4829]
Since Minikube uses **Docker Machine** to create and provision the VM,
it could be nice to have some more "advanced" docs on (lib)machine ?

We used to have a reference to https://github.com/docker/machine,
but it's not posted anymore on our new website (for some reason).

Also, some of the user docs are available on https://docs.docker.com/

And some non-official drivers live on https://github.com/machine-drivers

----

I think these are quite nice, and could serve as "inspiration" for minikube docs:

https://docs.docker.com/toolbox/overview/
* https://docs.docker.com/toolbox/toolbox_install_mac/
* https://docs.docker.com/toolbox/toolbox_install_windows/

https://docs.docker.com/machine/overview/
* https://docs.docker.com/machine/install-machine/
* https://docs.docker.com/machine/get-started/

It also needs some technical documentation, but most of that is yet to be written...

The focus will be on these drivers:

* `virtualbox` (default) - all
* `generic` (remote) - all
* `none` (local) - linux

And on these future-proof drivers:

* `kvm2` (libvirt) - linux
* `hyperkit` - darwin
* `hyperv` - windows

**Comment by RA489** [comment]
@afbjorklund can we create separate documentation on Docker Machine?

**Comment by RA489** [comment]
we can place docker_machine.md file here wdyt?
https://github.com/kubernetes/minikube/tree/master/docs

**Comment by afbjorklund** [comment]
It's mostly about writing, I don't think we lack a place to put it (in the README and the docs)

The upstream docs live in this monster repository: https://github.com/docker/docker.github.io

* https://github.com/docker/docker.github.io/tree/master/toolbox

* https://github.com/docker/docker.github.io/tree/master/machine

**Comment by afbjorklund** [comment]
@tstromberg : this was the issue were we can clear up things about "generic" and "none".

As long as we are using libmachine we should keep the upstream driver names in the code, but we can of course introduce some aliases and start referring to them with different names in minikube ?

https://docs.docker.com/machine/drivers/ (basically: virtualbox, hyper-v)

I did some initial attempts at describing these, will see if I can find those lines and add them here. Both drivers are really small, and the Driver API isn't all that big to start with (slightly unfortunately).

https://godoc.org/github.com/docker/machine/libmachine/drivers#Driver

Since github.com/docker/machine is frozen, it's very unlikely that anything will change there. 😔

**Comment by nanikjava** [comment]
@afbjorklund Happy to help out in writing documentation for this. Do you have any idea what specifically will be needed ? as there are few URL that was discussed here so bit lost and will need bit of direction on this.

**Comment by afbjorklund** [comment]
/remove-lifecycle rotten

More and more of libmachine is getting rewritten now, but still useful to have it documented...
