### ISSUE TITLE
How to config kubernetes apiserver?

### ISSUE THREAD

**Issue by BlankCHN** [kubernetes/minikube#4831]
I want to expose apiserver by http , and I want to use port 8080. How to config ?

**Comment by medyagh** [comment]
@BlankCHN 
you could specify a custom API port using  `--apiserver-port 8080` to minikube start.

for more info please checkout `minikube start --help`, please let me know if that helps you

**Comment by tstromberg** [comment]
Closing as this appears to be solved. Please reopen if not.
