### ISSUE TITLE
minikube dashboard failed with 503 

### ISSUE THREAD

**Issue by IvankaTashkova** [kubernetes/minikube#4836]
`minikube dashboard` verifying proxy failed with this error:
Temporary Error: unexpected response code: 503

`minikube version: v1.2.0`

* Additional info: the error message is shown more than once

**Comment by medyagh** [comment]
I am curious, is your network behind a proxy or a vpn ?

**Comment by IvankaTashkova** [comment]
I'm using a proxy. Is that the problem?
