### ISSUE TITLE
minikube addons disable failed: Process exited with status 1

### ISSUE THREAD

**Issue by IvankaTashkova** [kubernetes/minikube#4837]
Following this tutorial: https://kubernetes.io/docs/tutorials/hello-minikube/

`minikube addons disable heapster`

X disable failed: [disabling addon deploy/addons/heapster/influx-grafana-rc.yaml.tmpl: Process exited with status 1]

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

`minikube version: v1.2.0`

I can provide `minikube logs` if you need

**Comment by medyagh** [comment]
Hi @IvankaTashkova Thank you for taking the time to create this issue, yes please, could you please provide the minikibe logs and also your minikube start options ( do you use default driver ) ?

**Comment by IvankaTashkova** [comment]
[minikube-logs.txt](https://github.com/kubernetes/minikube/files/3420486/minikube-logs.txt)

I'm using Hyper-V. 

`minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch`
