### ISSUE TITLE
minikube kubelet[2773]: unknown flag: --bootstrap-kubeconfig

### ISSUE THREAD

**Issue by tomjdon05** [kubernetes/minikube#4838]
**The exact command to reproduce the issue**:
minikube.exe start --kubernetes-version="v1.6.0"

**The full output of the command that failed**:<details>

: Process exited with status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
* Problems detected in "kubelet":
  - Jul 22 17:39:03 minikube kubelet[2773]: unknown flag: --bootstrap-kubeconfig
</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:  Windows 10 Enterprise Version 1803 
OS build 17134.885

**Comment by tstromberg** [comment]
Sorry: minikube only supports Kubernetes v1.10+ and newer: 

You may have luck with an old minikube release from roughly the same time that v1.6 was released: https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md#selecting-a-kubernetes-version
