### ISSUE TITLE
logs hangs / kubectl: Unauthorized - you must be logged in

### ISSUE THREAD

**Issue by ahopkins** [kubernetes/minikube#4839]
**The exact command to reproduce the issue**:

    kubectl get pods

**The full output of the command that failed**:

    error: You must be logged in to the server (Unauthorized)

**The output of the `minikube logs` command**:

There isn't. It just hangs after this:

```
There is a newer version of minikube available (v1.2.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.2.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
```

**The operating system version**:

    Linux thebrewery 5.1.3-arch1-1-ARCH #1 SMP PREEMPT Thu May 16 20:59:36 UTC 2019 x86_64 GNU/Linux

---

This is related to #4353 

I have been having this issue for a **LONG** time. Basically, every time my machine goes to sleep, I need to manually kill my virtualbox machine, and restart `minikube`. Annoying, and it is a time killer.

Following @tstromberg [advice](https://github.com/kubernetes/minikube/issues/4353#issuecomment-512101209), I am opening a new issue.

I executed:

     kubectl config view --minify | grep /.minikube | xargs stat

Here is the output:

```
stat: cannot stat 'certificate-authority:': No such file or directory
  File: /home/adam/.minikube/ca.crt
  Size: 1066      	Blocks: 8          IO Block: 4096   regular file
Device: 10302h/66306d	Inode: 8131832     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    adam)   Gid: (  985/   users)
Access: 2019-07-22 21:20:59.615642904 +0300
Modify: 2019-07-07 21:54:18.756465959 +0300
Change: 2019-07-07 21:54:18.756465959 +0300
 Birth: 2019-07-07 21:54:18.756465959 +0300
stat: cannot stat 'client-certificate:': No such file or directory
  File: /home/adam/.minikube/client.crt
  Size: 1103      	Blocks: 8          IO Block: 4096   regular file
Device: 10302h/66306d	Inode: 8131837     Links: 1
Access: (0644/-rw-r--r--)  Uid: ( 1000/    adam)   Gid: (  985/   users)
Access: 2019-07-22 21:20:59.615642904 +0300
Modify: 2019-07-21 09:48:24.287550237 +0300
Change: 2019-07-21 09:48:24.287550237 +0300
 Birth: 2019-07-07 21:54:19.043145480 +0300
stat: cannot stat 'client-key:': No such file or directory
  File: /home/adam/.minikube/client.key
  Size: 1679      	Blocks: 8          IO Block: 4096   regular file
Device: 10302h/66306d	Inode: 8131842     Links: 1
Access: (0600/-rw-------)  Uid: ( 1000/    adam)   Gid: (  985/   users)
Access: 2019-07-22 21:20:59.615642904 +0300
Modify: 2019-07-21 09:48:24.287550237 +0300
Change: 2019-07-21 09:48:24.287550237 +0300
 Birth: 2019-07-07 21:54:19.043145480 +0300
```

As a side note, I also cleaned up the command to get rid of the `stat: cannot stat 'certificate-authority:': No such file or directory`:

```
kubectl config view --minify | grep /.minikube | cut -d ':' -f 2 | xargs stat
```

This is also related to #4481. In response to @tstromberg  request there, I can stop my machine manually, start and everything works fine. That is.... until I allow the machine to sleep again.

When I am in this "unauthorized" state, I cannot hit **ANY** `minikube` command. Everything hangs.

**Comment by tstromberg** [comment]
Do you mind sharing the command-line & output you used for starting minikube?

Also, the full output of `minikube logs` would be nice. I'm surprised about it hanging.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by ashwinchandran13** [comment]
@tstromberg The issue still exits even on v1.7.2. Any update on any solution?
