### ISSUE TITLE
Unable to connect to the server: Gateway Time-out

### ISSUE THREAD

**Issue by cherylhan** [kubernetes/minikube#485]
I dont know why？when i use the comman  kubectl get pods --all-namespaces 。
it shows that  Unable to connect to the server: Gateway Time-out
centos 7   memory 1g

**Comment by r2d4** [comment]
Hi, sorry you were having trouble.  Can you provide a little more information to help us debug?  

- Version of minikube
- VM driver 

Additionally, Can you do `minikube ssh` and get into the VM?  If so, what is the output of `docker ps` in the VM?

**Comment by cherylhan** [comment]
Veision of minikube  0.7.1  sorry i dont konw what is VM driver？
there are some trouble

1.Kubernetes cluster...


E0815 09:03:28.134615   14254 start.go:78] Error starting host:  Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

 2.minikube ssh 
 E0815 09:28:08.524608   16247 ssh.go:39] Error attempting to ssh into machine:  exit status 255

**Comment by cherylhan** [comment]
@r2d4 Starting local Kubernetes cluster...
E0815 18:43:24.707876   53489 start.go:88] Error configuring authentication:  connection is shut down

**Comment by cherylhan** [comment]
@r2d4  --vm-driver="virtualbox"

**Comment by cherylhan** [comment]
@r2d4  do i need iptables？ i use centos7   i dont open iptables。

**Comment by dlorenc** [comment]
You shouldn't need IP tables at all.

**Comment by dlorenc** [comment]
Did you manage to get past this?

**Comment by cherylhan** [comment]
@dlorenc  Probably related to my company's proxy, left the company's 8080 port, rather than apiserver 8080

**Comment by SriharshaAngadi** [comment]
@cherylhan  Can you please elaborate how did you fix this issue? I am facing the same problem with my minikube over corporate proxy. Its just that it is over windows
