### ISSUE TITLE
start_stop_delete_test: `config current-context` run against minikube instead of kubectl

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4854]
the following code is not right ! it is using a minikube runner to run a kubectl config command !

https://github.com/kubernetes/minikube/blob/9dfe660c64ed9ac5d76650868bde29272211c582/test/integration/start_stop_delete_test.go#L105

This needs to be fixed

```

			// running this command results in error when the current-context is not set
			if err := r.Run("config current-context"); err != nil {
				t.Logf("current-context is not set to minikube")
			}

````

**Comment by tstromberg** [comment]
Was this fixed?

**Comment by medyagh** [comment]
> Was this fixed?

no I will add it to the kubeconfig PR

**Comment by medyagh** [comment]
Done
