### ISSUE TITLE
UI: reduce repetitive icon for same warning (if using existing driver)

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4855]
Currently it shows as : 
```
$ ./out/minikube start 
😄  minikube v1.2.0 on darwin (amd64)


⚠️  Ignoring --vm-driver=virtualbox, as the existing "delete" VM was created using the hyperkit driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p delete`


🏃  Re-using the currently running hyperkit VM for "delete" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 
⌛  Verifying: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use delete
```

there is no need for 3 warning signs, one is enough as it is related to same warning.

**Comment by RA489** [comment]
@medyagh I think if we can combine these two warnings to one. WDYT?
⚠️  Ignoring --vm-driver=virtualbox, as the existing "delete" VM was created using the hyperkit driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`

**Comment by RA489** [comment]
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p delete`
@medyagh we can ignore this warning! suggestions?

**Comment by afbjorklund** [comment]
I think that we need all three, there seem to be a lot of people struggling with this ?

They want to use Hyper-V, they forget to tell Minikube. So they create half a VirtualBox one,
and then it is in the way when eventually switching to Hyper-V. Thus, they need to delete it...

Then again, the main people seem to be people not reading **anything**, before "start".

**Comment by RA489** [comment]
@afbjorklund I agree +1 in that case we can close this issue.

**Comment by RA489** [comment]
@medyagh can we close this issue as per @afbjorklund comments. wdyt?

**Comment by afbjorklund** [comment]
I think the better fix would be something similar to #4846, to use the "right" VM driver in the first place ?

And maybe we should recommend `minikube config set vm-driver`, so that `minikube start` "works" ?

**Comment by medyagh** [comment]
the issue I created this for was the number of Warning Icons, I agree with the message but I think there should be only one Warning Icon
and the second and third line should have empty icon.

I also like the idea of advising them to set it through 
minikube config set vm-driver

**Comment by afbjorklund** [comment]
Ah, OK - so it was more of a UX thing. Thought you meant the actual context ;-)

Maybe there should one BIG icon (as per ~#3724~), that should get their attention!

**Comment by afbjorklund** [comment]
A "preflight" might also be a good idea

**Comment by medyagh** [comment]
> A "preflight" might also be a good idea
> 
> ```
>  __                 
> /  \        _______________ 
> |  |       /               \
> @  @       | It looks      |
> || ||      | like you      |
> || ||   <--| are starting  |
> |\_/|      | a hypervisor. |
> \___/      \_______________/
> ```

I actually like that better than Warning ! because I see this message myself a lot, and I dont like minikube showing warning icon to me, for a normal thing I do a lot ! I am down for an ASCI art like you did.

and also I like Anders suggestion to advice the user to Config Set it. anyone who wants to pick this issue up, I recommend having an indented UI for this. so they know this is all related to this one situation.

**Comment by blueelvis** [comment]
Just FYI, by default on Windows, emoji's are not displayed on PowerShell. There is a workaround for enabling unicode support IMO.

-Pranav

**Comment by afbjorklund** [comment]
@medyagh sorry for hijacking your issue

📎 Should make sure to label jokes

**Comment by tstromberg** [comment]
Closing as we've decided to get rid of this warning altogether (#4998)
