### ISSUE TITLE
Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: proxyconnect tcp: EOF

### ISSUE THREAD

**Issue by kewenchao** [kubernetes/minikube#4858]
keke@keke:~$ minikube start --registry-mirror=https://registry.docker-cn.com
😄  minikube v1.2.0 on linux (amd64)
💿  Downloading Minikube ISO ...

💣  Failed to cache ISO
❌  Error:         [ISO_DOWNLOAD_FAILED] https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: proxyconnect tcp: EOF
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: proxyconnect tcp: EOF
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: proxyconnect tcp: EOF
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: proxyconnect tcp: EOF
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: proxyconnect tcp: EOF
💡  Advice:        A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
📘  Documentation: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3922

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
It appears that no proxy environment variable is configured. Did you try following https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md ?

**Comment by tstromberg** [comment]
Related: #4774

**Comment by tstromberg** [comment]
Related: #4774
