### ISSUE TITLE
VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

### ISSUE THREAD

**Issue by arnabvampire1** [kubernetes/minikube#4859]
If this is a bug report, please include:

  The exact command-lines used.
minikube start

  The full output of the command that failed
o minikube v0.34.1 on windows (amd64)
> Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
! Unable to start VM: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
- https://github.com/kubernetes/minikube/issues/new

  The operating system name and version used
OS - Windows 10
Version - 10.0.17134 Build 17134

Solution:

**Remove/delete minikube folder on machines directory**

find similar to this path:
C:\Users\User.minikube\machines\

and then reinstall minikube.
After i reinstall minikube tried to start it again and works fine for me

**Comment by blueelvis** [comment]
Did you install Virtualbox after installing minikube? Or was it installed already?

**Comment by tstromberg** [comment]
The only way I could imagine this error firing is if VirtualBox is not in PATH. I'm not sure what else to do about it.
