### ISSUE TITLE
Refactor logging messages/More default output

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#486]
This issue is two part:
- Enhance output to show the user that minikube is doing something
- Refactor existing logging messages to be more helpful

For the first part, we could show the user a loading indicator (.....) or spinny wheel or change some of the info levels logs to be output by default.  

For the second part, we can refactor some of the logs that run with the start command to be more useful.
Some sample output from #459, 

```
I0815 10:36:26.070738    9076 cluster.go:68] Machine exists!
I0815 10:36:26.155255    9076 cluster.go:76] Machine state:  Error
I0815 10:36:26.155755    9076 cluster.go:68] Machine exists!
I0815 10:36:26.236771    9076 cluster.go:76] Machine state:  Error
E0815 10:36:26.236771    9076 start.go:78] Error starting host:  Error getting state for host: machine does not exist
```

**Comment by dlorenc** [comment]
Ref #291
