### ISSUE TITLE
parallels: `minikube mount`: attempted to get host ip address for unsupported driver

### ISSUE THREAD

**Issue by dcecile** [kubernetes/minikube#4862]
Running `minikube mount` with the parallels driver gives this error message:

```
💣  Error getting the host IP address to use from within the VM: Error, attempted to get host ip address for unsupported driver
```

According to [the docs](https://github.com/kubernetes/minikube/blob/master/docs/host_folder_mount.md), this is preferred over relying on driver-specific mounting.

It's an issue for me right now because I can't figure out how to get share folders enabled through the Parallels UI to show up on the Minikube VM.

**Comment by afbjorklund** [comment]
How to get the host IP is unfortunately **not** covered by libmachine API at the moment...
That is: how to get the address of the host running minikube, as seen from inside the VM.

There is a workaround in minikube, but it needs driver-specific code in order to do it:

[pkg/minikube/cluster/cluster.go#GetVMHostIP](https://github.com/kubernetes/minikube/blob/e22b605e725e3bf0a2438c748b76f8e97ef680b5/pkg/minikube/cluster/cluster.go#L484_L524)

So it needs an entry for parallels, how to find it ?

If you know the command, then please add it here.

**Comment by dcecile** [comment]
@afbjorklund It seems like the command [might not work properly](https://stackoverflow.com/questions/17896984/how-to-get-the-ip-address-used-by-a-parallels-vm-from-the-host), and that the reliable way to do it is to install Parallels Tools inside the VM first then remotely execute `ip address show dev eth1 | grep ...`. Equivalently, we could use `minikube ssh` to do remote execution of `ip address`. (I tested that `minikube ssh` works with Parallels.)

Actually it seems like the libmachine API might support getting the host IP now: [Driver.GetIP](https://godoc.org/github.com/docker/machine/libmachine/drivers#BaseDriver.GetIP)

- The `Driver` is accessible as `host.driver` after running [`cluster. CheckIfHostExistsAndLoad`](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cluster/cluster.go#L541)
- For the Parallels driver, it's the exact same code path as `minikube ssh`, since [Minikube `cluster.CreateSSHShell`](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cluster/cluster.go#L558) calls [libmachine API `Host.CreateSSHClient`](https://github.com/docker/machine/blob/master/libmachine/host/host.go#L72) which calls [Parallels `Driver.GetSSHHostname`](https://github.com/Parallels/docker-machine-parallels/blob/master/parallels_darwin.go#L323) which ends up calling [Parallels `Driver.GetIP`](https://github.com/Parallels/docker-machine-parallels/blob/master/parallels_darwin.go#L304)

Do you think that it would work to use `Driver.GetIP`?

**Comment by afbjorklund** [comment]
As long as you get the **host** IP and not just the machine IP, it should be fine.
The only driver using `GetIP` is VMware, and then replaces the last digit with "1".

For instance, for the default VirtualBox the machine IP starts at 192.168.99.100
And the `vboxnet0` interface (hostonlyadapter2) normally gets adress 192.168.99.1

**Comment by tstromberg** [comment]
This sounds reasonable. PR's welcome!

**Comment by tstromberg** [comment]
This would require adding parallels support to pkg/minikube/cluster/cluster.go#GetVMHostIP - probably a 1-line fix at most. Help wanted!

**Comment by sharifelgamal** [comment]
Help still wanted!

/remove-lifecycle rotten

**Comment by legal90** [comment]
Hi all,
Here is the fix for this issue: https://github.com/kubernetes/minikube/pull/8259
