### ISSUE TITLE
Autocompletion support for minikube on Windows/PowerShell

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#4865]
PowerShell has auto-completion features for the native cmdlets. Lets see if we can have some support for auto-completion on Windows/PowerShell for minikube.

**Comment by tstromberg** [comment]
Sounds like a nice feature to have!

**Comment by medyagh** [comment]
@blueelvis are you interested to pick up this one ?

**Comment by blueelvis** [comment]
@medyagh - Yes, I am interested in picking this up once I fix the other major bugs. You have anything in mind for this?


/assign

**Comment by dzmitry-lahoda** [comment]
@blueelvis where is documentation about `pwsh` feature about this? what is branch for this? i  hope you will have pwsh module with build and release cycle(like other pro modules) so it is possible to add new apis continously (ease of contribute)

**Comment by blueelvis** [comment]
@dzmitry-lahoda - I haven't started working on this as of now. Working on some other things but don't worry, I have this in my mind. If you have any further ideas, do post here :)

**Comment by medyagh** [comment]
would be dope to see this :)

**Comment by dzmitry-lahoda** [comment]
there could be idea to generate pwsh module from linux stuff which allows auto completion in sh. but that could lead to non idiomatic api. so better to setup module with whole pipeline (test, validate, publish) and sketch most important API manually. if that works and good, proceed with generator. and i pretty sure there would be some complex cases are not mapped 1-1 to pwsh (like structured output or variables piping)

**Comment by priyawadhwa** [comment]
Hey @blueelvis, are you still working on this?
