### ISSUE TITLE
issue with minikube start --vm-driver hyperv --hyperv-virtual-switch External"

### ISSUE THREAD

**Issue by naresh-maven** [kubernetes/minikube#4880]
I'm trying to get minikube working on Windows 10 Pro, on my laptop

executing:
minikube start --vm-driver=hyperv --hyperv-virtual-switch="Primary Virtual Switch"
* minikube v1.2.0 on windows (amd64)
* Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0726 18:19:31.872558    1300 start.go:559] StartHost: create: precreate: vswitch "Primary Virtual Switch" not found

X Unable to start VM: create: precreate: vswitch "Primary Virtual Switch" not found

Additionally:
Docker for Windows is installed and running.

**Comment by sharifelgamal** [comment]
Could you check your HyperV Manager and make sure you have a virtual switch called "Primary Virtual Switch?" You might have to create it, as detailed https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#hyper-v-driver.

**Comment by tstromberg** [comment]
This will display the appropriate value to use:

`Get-VMSwitch -SwitchType External`

**Comment by tstromberg** [comment]
@naresh-maven I believe this issue is now addressed by minikube v1.4, as it no longer requires `--hyperv-virtual-switch` to be passed in. If you still see this issue with minikube v1.4 or higher, please reopen this issue by commenting with `/reopen`

Thank you for reporting this issue!
