### ISSUE TITLE
make "active profile name" clear in  minikube output 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4890]
Here is a bit of confusing scenario:

set minikube profile to p1
```
minikube profile p1
```

then forget about it ( and a couple days try this )

``` /minikube start --vm-driver=hyperkit```

I would like the output to tell me that I am using a profile other than main one (minikube)

```
😄  minikube v1.2.0 on darwin (amd64)
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
ℹ️  Provisioned with Buildroot 2018.05.3
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
⌛  Verifying: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use p1
```

since I had set the profile a few days ago I totally forgot I was not using minikube main profile, and it added to my confusion ! I think the good place to show the profile name is the fist line .
```
😄  minikube (p1) v1.2.0 on darwin (amd64)
```

or we could prepend the profile name to all the output messages

```
😄  [p1] minikube v1.2.0 on darwin (amd64)
🔥  [p1] Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
ℹ️  [p1] Provisioned with Buildroot 2018.05.3
🐳  [p1] Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
🚜  [p1]  Pulling images ...
🚀  [p1] Launching Kubernetes ... 
⌛  [p1]  Verifying: apiserver proxy etcd scheduler controller dns
🏄  [p1]  Done! kubectl is now configured to use p1
```

the second one is more noisy but more clear ! it is a good topic to discuss which one users would prefer ! (maybe be make it configurable for advanced users)

also

the output of "minikube profile list" should have a star next to the active profile

the current minikube profile list shows this:

```
$ ./out/minikube profile list
|----------|-----------|----------------|-----------|--------------------|
| Profile  | VM Driver |     NodeIP     | Node Port | Kubernetes Version |
|----------|-----------|----------------|-----------|--------------------|
| minikube | hyperkit  | 192.168.64.102 |      8443 | v1.15.0            |
| p1       | hyperkit  | 192.168.64.117 |      8443 | v1.15.0            |
|----------|-----------|----------------|-----------|--------------------|

```

but we need to add a * to the active profile to match the  kubectl config get-contexts we can add a new column in the first called "Current" or "Active" with a * in it if it is the current profile

the same goes for other commands for example if I am runing

```
 $ ./out/minikube ssh -- ls -lah
total 0
drwxr-xr-x 3 docker docker 60 Jul 27 20:19 .
drwxr-xr-x 3 root   root   60 Jun 24 06:25 ..
drwx------ 2 docker docker 80 Jul 27 20:19 .ssh
```

I like to know which minikube ssh this connecting too.
maybe one line the begging say:
"(p1) : "

Bonous:

add the same behaviour to
minikube stop, and minikube status !

**Comment by medyagh** [comment]
@loqutus it is yours, please let me know if you need any help !

**Comment by tstromberg** [comment]
I prefer the first-line parenthesis approach better than repeating the profile name on every line.

**Comment by sakshamkhanna** [comment]
Hi, I don't see any progress on the issue.
If work is not underway, I'd like to pick it up

**Comment by loqutus** [comment]
sure, you can take it.

**Comment by sakshamkhanna** [comment]
@medyagh minikube stop already displays the profile that is active. I don't think more information is required here
```
C:\Users\Saksham>minikube profile
p1

C:\Users\Saksham>minikube stop
* Stopping "p1" in virtualbox ...
* "p1" stopped.
```

**Comment by sakshamkhanna** [comment]
blocking activity until #5044 gets resolved

**Comment by medyagh** [comment]
> blocking activity until #5044 gets resolved

issue resolved :)

**Comment by medyagh** [comment]
@sakshamkhanna are you still interested to work on this ?
