### ISSUE TITLE
waiting for apiserver: timed out - when dynamic audit backend flags set

### ISSUE THREAD

**Issue by minishri** [kubernetes/minikube#4903]
**Steps to to reproduce**
_1. Start minikube with `minikube start`
2. Set an audit policy file in /var/lib/minikube/config
3. `minikube ssh` change the kube-apiserver.yaml in /etc/kubernetes/manifests and add the flags to enable dynamic audit backend.  Mount the audit config path as a volume into the apiserver container. Wait for the apiserver pod to get restarted
4. Stop minikube with `minikube stop`
5.  Start minikube again_

**minikube start **
(after you have enabled the dynamic audit backend kube-apiserver flags as [here](https://kubernetes.io/docs/tasks/debug-application-cluster/audit/#audit-policy):

**The full output of the command that failed**:<details>

```
minikube v1.2.0 on darwin (amd64)
Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
Restarting existing virtualbox VM for "minikube" ...
Waiting for SSH access ...
Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
Relaunching Kubernetes v1.15.0 using kubeadm ...

Error restarting cluster: waiting for apiserver: timed out waiting for the condition
```

</details>

**Mac OSX 10.14.6,  minikube 1.2.3, Kubernetes v1.15.0, docker 18.09.6**:

_VirtualBox already installed  using default vm driver virtualbox (6.0.2)_

However, on retrying I got the following errors log.  I checked System Preferences -> Security&Privacy -> General and saw no warnings, can see VirtualBox added to the Accessibility list.  Completely removing virtualbox app and reinstalling it and `rm -rf ~/.minikube` still did not help.  

```
reating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0728 16:13:56.346905   18403 start.go:559] StartHost: create: creating: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: UUID {6dc53d67-b448-4caf-8386-e20f41926777} of the medium '/Users/minishri/.minikube/machines/minikube/disk.vmdk' does not match the value {14641650-e9d1-48b6-914b-345276184226} stored in the media registry ('/Users/minishri/Library/VirtualBox/VirtualBox.xml')
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium

Details: 00:00:00.027619 Power up failed (vrc=VINF_SUCCESS, rc=NS_ERROR_FAILURE (0X80004005))

💣  Unable to start VM
❌  Error:         [VBOX_BLOCKED] create: creating: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: UUID {6dc53d67-b448-4caf-8386-e20f41926777} of the medium '/Users/minishri/.minikube/machines/minikube/disk.vmdk' does not match the value {14641650-e9d1-48b6-914b-345276184226} stored in the media registry ('/Users/minishri/Library/VirtualBox/VirtualBox.xml')
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MediumWrap, interface IMedium

Details: 00:00:00.027619 Power up failed (vrc=VINF_SUCCESS, rc=NS_ERROR_FAILURE (0X80004005))
💡  Advice:        Reinstall VirtualBox and verify that it is not blocked: System Preferences -> Security & Privacy -> General -> Some system software was blocked from loading
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/4107
```

Added VirtualBox to the 'Full Disk Access' in System Preferences -> Security&Privacy -> Privacy (needs admin rights on your mac)

Then removed .minikube folder again and retried 'minikube start'.  Now the cluster comes up but I am yet to reapply the dynamic audit backend flags...

**Comment by tstromberg** [comment]
This error doesn't have to do with the flags, but it sounds like it was due to a corrupt or mismatched VM, and thus fixable by using `minikube delete`.

Please do not run `rm -Rf ~/.minikube` - it causes minikube to be unable to track what the hypervisor state is.

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by minishri** [comment]
I will close this issue now , after increasing the minikube VM to 4 CPUs and 8GB mem, the issue is not seen.
