### ISSUE TITLE
virtual machine has terminated unexpectedly - NS_ERROR_FAILURE (0x80004005)

### ISSUE THREAD

**Issue by ankit45621** [kubernetes/minikube#4908]
Hi,

I am trying to `minikube start` but i am getting below error:

😄  minikube v1.2.0 on linux (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
E0729 16:27:15.466915    6913 start.go:559] StartHost: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

💣  Unable to start VM: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by sharifelgamal** [comment]
It looks like VirtualBox failed to create the minikube VM. You might need to update or reinstall VirtualBox to fix an error like this. What OS are you using?

**Comment by ankit45621** [comment]
@sharifelgamal I also reinstall virtualBox same issue i am facing. I am using ubuntu 16.5

**Comment by atulksigma** [comment]
I am facing same issue on Ubuntu 18.04.3 LTS with virtualbox Version 6.0.10 r132072 (Qt5.9.5) and minikube 1.3.1

**Comment by tstromberg** [comment]
@ankit45621 I believe this issue is now addressed by minikube v1.4, as it should detect the condition and then recommend a reinstallation of VirtualBox+reboot. This issue is typically caused by a mismatch of VirtualBox kernel and userland.

If you still see this issue with minikube v1.4 or higher, please reopen this issue by commenting with `/reopen`

Thank you for reporting this issue!

**Comment by yoshino** [comment]
minikube version is

```
$ minikube version                                                    
minikube version: v1.6.2
```

virtualBox version is

```
$  VBoxManage -v                                                                                                  ~
6.1.2r135662
```

same error :cry: 

```
$ minikube start                                                                                                 ~
😄  minikube v1.6.2 on Ubuntu 19.04
✨  Automatically selected the 'virtualbox' driver (alternates: [none])
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

**Comment by yoshino** [comment]
I can minkube-start by kvm on Ubuntu 19.04.

```
$ minikube start --vm-driver=kvm2
```


kvm ref: https://help.ubuntu.com/community/KVM/Installation
