### ISSUE TITLE
Add better 'minikube status' output

### ISSUE THREAD

**Issue by mheese** [kubernetes/minikube#491]
It seems to be that `localkube` is crashing inside of the VM for me from time to time. While I haven't found a way to debug why that is the case (I currently suspect it happens when I wake up my laptop from sleep), I would appreciate if the `minikube status` command would output `Error` or similar instead of just `Running`.

I had to do a `minikube ssh` first and figure out that the localkube process died instead.

**Comment by dlorenc** [comment]
Thanks, we should definitely do this.

**Comment by dlorenc** [comment]
For getting the status, what do you think about changing the startup to write to a pid file, then check the status like this: https://github.com/fhd/init-script-template/blob/master/template#L26
