### ISSUE TITLE
Failed to start kvm when virtualbox is running 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4913]
I saw this error on integeration tests for the https://github.com/kubernetes/minikube/pull/4857 PR, @josedonizetti found out through these related issues that you can not run KVM and virtualbox at the same time.

Related: 
- https://www.agix.com.au/kvm-error-ioctlkvm_create_vm-failed-16-device-or-resource-busy/
- https://github.com/CanonicalLtd/multipass/issues/6
- https://tech.blog.sue.ss.it/2014/09/linux-kvm-error-ioctlkvm_create_vm-failed-16-device-or-resource-busy/

```
Unable to start VM: create: Error creating machine: Error in driver during machine creation: error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
 08:52:59 | ! failed to initialize KVM: Device or resource busy')
 08:52:59 | ! * 
 08:52:59 | ! X Unable to start VM: create: Error creating machine: Error in driver during machine creation: error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: ioctl(KVM_CREATE_VM) failed: 16 Device or resource busy
 08:52:59 | ! failed to initialize KVM: Device or resource busy')
 08:52:59 | ! * 
 08:52:59 | ! * Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
 08:52:59 | !   - https://github.com/kubernetes/minikube/issues/new/choose

```

**Comment by medyagh** [comment]
Also related error on the virtualbox part 

```
15:57:28 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:28 | ! VBoxManage: error: VirtualBox can’t operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15
```

<details>
<summary>
+ Full log
</summary>
<pre>
Started by upstream project "[8mha:////4NGhUwoSlzKp6t8AQLvb63Jzd9w8scWd3UmWXaeS7tsRAAAAnR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAzuEgZB/az8JH2n0syclHjnovziYn0A9i4RNsYAAAA=[0mBuild_Cross" build number [8mha:////4PDTaZrqigRF8/yeXKR33eUSXuhPl0uLigwZeMe6IY+CAAAAoR+LCAAAAAAAAP9b85aBtbiIQTGjNKU4P08vOT+vOD8nVc83PyU1x6OyILUoJzMv2y+/JJUBAhiZGBgqihhk0NSjKDWzXb3RdlLBUSYGJk8GtpzUvPSSDB8G5tKinBIGIZ+sxLJE/ZzEvHT94JKizLx0a6BxUmjGOUNodHsLgAyWEgZR/az8JH2n0syclHjnovziYn1zU2NjAF5U5JbKAAAA[0m7533
++ echo 'error: killing hung kubectl processes ...'
error: killing hung kubectl processes ...
++ ps -f -p 14546 17768
...
15:57:07 | ! ERROR: logging before flag.Parse: I0729 15:57:07.364037 1383 notify.go:124] Checking for updates...
15:57:07 | > ! "minikube" cluster does not exist
15:57:07 | > * The "minikube" cluster has been deleted.
...
15:57:22 | ! }
15:57:22 | ! STDERR:
15:57:22 | ! {
15:57:22 | ! VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
15:57:22 | ! VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1884 of file VBoxManageModifyVM.cpp
15:57:22 | ! }
15:57:24 | ! }
15:57:24 | ! STDERR:
15:57:24 | ! {
15:57:24 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:24 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:24 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:24 | ! }
15:57:24 | ! Checking vm logs: /home/jenkins/minikube-integration/linux-amd64-virtualbox-master-32523-396a65a1015ec4be4e65c674e069eba3d551394d/.minikube/machines/minikube/minikube/Logs/VBox.log
15:57:26 | ! ERROR: logging before flag.Parse: E0729 15:57:26.369586 1400 start.go:678] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
15:57:26 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:26 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:26 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:26 | ! Details: 00:00:02.136742 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
15:57:26 | ! ERROR: logging before flag.Parse: I0729 15:57:26.369663 1400 utils.go:127] non-retriable error: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
15:57:26 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:26 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:26 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:26 | ! Details: 00:00:02.136742 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
15:57:26 | ! ERROR: logging before flag.Parse: W0729 15:57:26.369857 1400 exit.go:99] Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
15:57:26 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:26 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:26 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:26 | ! Details: 00:00:02.136742 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
15:57:26 | ! * 
15:57:26 | ! X Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
15:57:26 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:26 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:26 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:26 | ! Details: 00:00:02.136742 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
15:57:26 | ! * 
15:57:26 | ! * Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
15:57:26 | ! - https://github.com/kubernetes/minikube/issues/new/choose
--- FAIL: TestDocker (19.14s)
docker_test.go:47: start: exit status 70
stdout: * minikube v1.2.0 on linux (amd64)
...
}
STDERR:
{
VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not available)
VBoxManage: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at line 1884 of file VBoxManageModifyVM.cpp
}
...
}
STDERR:
{
VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
}
Checking vm logs: /home/jenkins/minikube-integration/linux-amd64-virtualbox-master-32523-396a65a1015ec4be4e65c674e069eba3d551394d/.minikube/machines/minikube/minikube/Logs/VBox.log
ERROR: logging before flag.Parse: E0729 15:57:26.369586 1400 start.go:678] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.136742 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
ERROR: logging before flag.Parse: I0729 15:57:26.369663 1400 utils.go:127] non-retriable error: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.136742 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
ERROR: logging before flag.Parse: W0729 15:57:26.369857 1400 exit.go:99] Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.136742 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
* 
X Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.136742 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
* 
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
...
15:57:26 | > * Tip: Use 'minikube start -p ' to create a new cluster, or 'minikube delete' to delete this one.
15:57:26 | ! ERROR: logging before flag.Parse: I0729 15:57:26.869784 2000 cluster.go:117] Machine state: Stopped
15:57:26 | > * Restarting existing virtualbox VM for "minikube" ...
15:57:28 | ! ERROR: logging before flag.Parse: E0729 15:57:28.321639 2000 start.go:678] StartHost: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
15:57:28 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:28 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:28 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:28 | ! Details: 00:00:00.599997 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
15:57:28 | ! ERROR: logging before flag.Parse: I0729 15:57:28.321704 2000 utils.go:127] non-retriable error: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
15:57:28 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:28 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:28 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:28 | ! Details: 00:00:00.599997 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
15:57:28 | ! ERROR: logging before flag.Parse: W0729 15:57:28.321841 2000 exit.go:99] Unable to start VM: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
15:57:28 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:28 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:28 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:28 | ! Details: 00:00:00.599997 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
15:57:28 | ! * 
15:57:28 | ! X Unable to start VM: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
15:57:28 | ! VBoxManage: error: VT-x is being used by another hypervisor (VERR_VMX_IN_VMX_ROOT_MODE).
15:57:28 | ! VBoxManage: error: VirtualBox can't operate in VMX root mode. Please disable the KVM kernel extension, recompile your kernel and reboot (VERR_VMX_IN_VMX_ROOT_MODE)
15:57:28 | ! VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
15:57:28 | ! Details: 00:00:00.599997 Power up failed (vrc=VERR_VMX_IN_VMX_ROOT_MODE, rc=NS_ERROR_FAILURE (0X80004005))
15:57:28 | ! * 
15:57:28 | ! * Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
15:57:28 | ! - https://github.com/kubernetes/minikube/issues/new/choose
--- FAIL: TestFunctional (1.95s)
util.go:130: Error running command: start --vm-driver=virtualbox --v=10 --logtostderr --alsologtostderr --v=2 . Output: * minikube v1.2.0 on linux (amd64)
* Tip: Use 'minikube start -p ' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing virtualbox VM for "minikube" ...
...
15:57:29 | > * Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
</pre>
</details>

**Comment by RA489** [comment]
@medyagh @josedonizetti While debugging this issue i am getting below output.

> root@openstack-nti-18:/home/ubuntu# minikube start --vm-driver=virtualbox
> 😄  minikube v1.2.0 on linux (amd64)
> ⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary.
> 
> ⚠️  Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the none driver.
> ⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
> ⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`
> 
> 🔄  Restarting existing none VM for "minikube" ...
> ⌛  Waiting for SSH access ...
> 🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.7
> 🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 
> ⌛  Verifying: apiserver proxy etcd scheduler controller dns
> 🏄  Done! kubectl is now configured to use "minikube"
> root@openstack-nti-18:/home/ubuntu# minikube start --vm-driver=kvm2
> 😄  minikube v1.2.0 on linux (amd64)
> ⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary.
> 
> ⚠️  Ignoring --vm-driver=kvm2, as the existing "minikube" VM was created using the none driver.
> ⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=kvm2`
> ⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`
> 
> 🏃  Re-using the currently running none VM for "minikube" ...
> ⌛  Waiting for SSH access ...
> 🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.7
> 🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 
> ⌛  Verifying: apiserver proxy etcd scheduler controller dns
> 🏄  Done! kubectl is now configured to use "minikube"
>

**Comment by afbjorklund** [comment]
> found out through these related issues that you can not run KVM and virtualbox at the same time.

I knew this ☺️ Just didn't know it was an issue. One at a time (without any reboot) is fine, though.

**Comment by josedonizetti** [comment]
@nanikjava Apprently I cannot assign it to you, but this is the issue I spoke about.

**Comment by nanikjava** [comment]
Runnin virtualbox and kvm2 after that yields the following error

I1017 18:42:56.617946   27638 main.go:107] libmachine: Launching plugin server for driver kvm2
I1017 18:42:56.632933   27638 main.go:107] libmachine: Plugin server listening at address 127.0.0.1:44691
I1017 18:42:56.633162   27638 main.go:107] libmachine: () Calling .GetVersion
I1017 18:42:56.633627   27638 main.go:107] libmachine: Using API Version  1
I1017 18:42:56.633647   27638 main.go:107] libmachine: () Calling .SetConfigRaw
I1017 18:42:56.633892   27638 main.go:107] libmachine: () Calling .GetMachineName
I1017 18:42:56.633996   27638 main.go:107] libmachine: (kvm) Calling .GetState
💣  Unable to get the status of the cluster.

I've enabled the logging (inside golog) go get more logging. 

So the code is supposed to be doing it's job correctly.

**Comment by nanikjava** [comment]
@medyagh so does this mean this is still an issue ? as from my testing minikube exit after it detect that KVM is not able to startup as 'Device or Resource busy'

**Comment by josedonizetti** [comment]
@nanikjava do we get the same message if doing the other way around? first kvm, then virtualbox?

**Comment by nanikjava** [comment]
@josedonizetti When KVM runs first and then Virtualbox it gets stuck trying to connect to 127.0.0.1 port 34207



> I1018 18:02:16.866907    7782 main.go:107] libmachine: Checking vm logs: /home/nanik/.minikube/machines/nanikvirtualbox/nanikvirtualbox/Logs/VBox.log
> I1018 18:02:16.868494    7782 main.go:107] libmachine: Waiting for an IP...
> I1018 18:02:16.868510    7782 main.go:107] libmachine: Getting to WaitForSSH function...
> I1018 18:02:16.868577    7782 main.go:107] libmachine: Using SSH client type: native
> I1018 18:02:16.868743    7782 main.go:107] libmachine: &{{{<nil> 0 [] [] []} docker [0xed0540] 0xed0510 <nil>  [] 0s} 127.0.0.1 34207 <nil> <nil>}
> I1018 18:02:16.868757    7782 main.go:107] libmachine: About to run SSH command:
> exit 0
> I1018 18:03:32.707305    7782 main.go:107] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33038->127.0.0.1:34207: read: connection reset by peer
> I1018 18:04:51.405462    7782 main.go:107] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33048->127.0.0.1:34207: read: connection reset by peer
> I1018 18:06:09.484929    7782 main.go:107] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33058->127.0.0.1:34207: read: connection reset by peer
> I1018 18:07:28.528378    7782 main.go:107] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33118->127.0.0.1:34207: read: connection reset by peer
> I1018 18:08:46.767847    7782 main.go:107] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33128->127.0.0.1:34207: read: connection reset by peer
> I1018 18:10:05.452337    7782 main.go:107] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33132->127.0.0.1:34207: read: connection reset by peer
> I1018 18:11:23.530606    7782 main.go:107] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33142->127.0.0.1:34207: read: connection reset by peer
> I1018 18:12:43.233888    7782 main.go:107] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:33144->127.0.0.1:34207: read: connection reset by peer

**Comment by nanikjava** [comment]
@josedonizetti @medyagh Is this something that need to be fixed ? What kind of check would be appropriate for this scenario ?

**Comment by priyawadhwa** [comment]
@nanikjava I think it would be reasonable to check if either kvm/virtualbox is already running & log a warning to the user if that's the case.

**Comment by mcortinas** [comment]
I tried start kvm and virtualbox and I can not do it at the same time. I received the errors commented before. What's the workaround?

**Comment by afbjorklund** [comment]
>  What's the workaround?

Stop all libvirt/KVM virtual machines before starting VirtualBox. Stop all VBox virtual  machines before starting KVM.
