### ISSUE TITLE
Integration Scripts: install consistent version of tools in integration tests

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4914]
We need to have same version for the following tools for integration tests:

- golang
- kubectl version
- virtualbox
- docker
- libvirt

**Comment by sharifelgamal** [comment]
Do we know what specific version of these we want to pin to?

**Comment by afbjorklund** [comment]
I think we have pinned `go version` to 1.12.7 in most places soon, maybe not `go test` though.

Most likely we want to use the very _same_ version of `kubectl` client as we have on the server ?

But why do we need to pin the docker client version ?

Not sure even the docker daemon version matters...

**Comment by medyagh** [comment]
@afbjorklund this ticket is targeted toward integration tests tools not building ones.
 
@sharifelgamal here is more context:

There should be shell scripts that each job calls to install tools required, 
for example  :
the file https://github.com/kubernetes/minikube/blob/master/hack/jenkins/linux_integration_tests_virtualbox.sh
should call a script call linux_integration_tests_virtualbox.sh

that checks if that specific version of virtualbox exists if not, install them.

same other job types:
- linux_integration_tests_kvm.sh
- linux_integration_tests_none.sh
- linux_integration_tests_virtualbox.sh 
- osx_integration_tests_hyperkit.sh
- osx_integration_tests_virtualbox.sh

**Comment by tstromberg** [comment]
Add `crictl` to this list.

**Comment by tstromberg** [comment]
This still exists.
