### ISSUE TITLE
Need someone to push the kvm-build-image

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#4919]
Currently we rebuild the docker image every time, not very efficient ?

https://storage.googleapis.com/minikube-builds/logs/4918/build.txt
```
docker pull gcr.io/k8s-minikube/kvm-build-image || make gcr.io/k8s-minikube/kvm-build-image
Using default tag: latest
Pulling repository gcr.io/k8s-minikube/kvm-build-image
Error: Status 405 trying to pull repository k8s-minikube/kvm-build-image: "v1 Registry API is disabled. If you are not explicitly using the v1 Registry API, it is possible your v2 image could not be found. Verify that your image is available, or retry with `dockerd --disable-legacy-registry`. See https://cloud.google.com/container-registry/docs/support/deprecation-notices"
make[1]: Entering directory '/var/lib/jenkins/go/src/k8s.io/minikube'
docker build --build-arg "GO_VERSION=1.12.5" -t gcr.io/k8s-minikube/kvm-build-image -f installers/linux/kvm/Dockerfile installers/linux/kvm/
Sending build context to Docker daemon  3.072kB

Step 1/6 : FROM gcr.io/gcp-runtimes/ubuntu_16_0_4
 ---> 3b704c5ce2c0
Step 2/6 : RUN apt-get update && apt-get install -y --no-install-recommends 		gcc 		libc6-dev 		make 		pkg-config 		curl 		libvirt-dev 		git 	&& rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 2c6d74c65400
Step 3/6 : ARG GO_VERSION
 ---> Using cache
 ---> b6f780a93879
Step 4/6 : RUN curl -sSL https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz | tar -C /usr/local -xzf -
 ---> Using cache
 ---> 1d18819875f5
Step 5/6 : ENV GOPATH /go
 ---> Using cache
 ---> 17c3ecc9ab8d
Step 6/6 : ENV PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/go/bin
 ---> Using cache
 ---> 91d694948545
Successfully built 91d694948545
Successfully tagged gcr.io/k8s-minikube/kvm-build-image:latest

gcr.io/k8s-minikube/kvm-build-image successfully built
```
Need someone with permissions, to push the image to `gcr.io/k8s-minikube`

Preferrably _after_ the go version has been updated to 1.12.7:  #4917

----

Also my `docker pull` check was bad, should check for a _local_ image first.

Something like I do elsewhere: `docker inspect -f '{{.Id}} {{.RepoTags}}'`

**Comment by afbjorklund** [comment]
Added #4921 for the second part, getting the build image in a consistent fashion.

**Comment by medyagh** [comment]
@afbjorklund how often are we gonna do this ? do you want someone for one manual push ?

**Comment by medyagh** [comment]
I could do that manually but preferably if you create a script in hacks/jenkins/ I can make a jenkins job out of it that we can run on demand

**Comment by afbjorklund** [comment]
To be honest I don't know how we did the `buildroot-image`, but not very often - like twice a year ?
They're based on Ubuntu LTS releases, so depends on how anxious we are about security updates:

FROM ubuntu:18.04

FROM ~ubuntu:16.04~ gcr.io/gcp-runtimes/ubuntu_16_0_4


@josedonizetti was suggesting to add a version - rather than just use `latest` like we do today.
But that was mostly for the `kvm-build-image` since we add a go version, to all the apt packages.

**Comment by afbjorklund** [comment]
Seems like we never pushed the other image either:

```
$ docker pull gcr.io/k8s-minikube/buildroot-image
Using default tag: latest
Error response from daemon: manifest for gcr.io/k8s-minikube/buildroot-image:latest not found
```

I'm not even sure that we **use** Docker for the building the ISO ?

---

Seems like some of the jenkins hacks just bypass the make targets:

```bash
set -e
${ARGS} make release-iso
```

```Makefile
.PHONY: release-iso
release-iso: minikube_iso checksum

```
i.e. it doesn't use out/minikube.iso and doesn't set BUILD_IN_DOCKER

**Comment by afbjorklund** [comment]
@medyagh : we can fix this for _next_ time, don't have to push anything now
