### ISSUE TITLE
Error configuring authentication: connection is shut down

### ISSUE THREAD

**Issue by cherylhan** [kubernetes/minikube#493]
i use virtualbox to run minikube   when i input minikube start，it shows that
Error configuring authentication: connection is shut down

**Comment by cherylhan** [comment]
this is the log  i have some question

1.i use centos install a virtualbox5.1 than start the service
2.i visit http://kubernetes.io/docs/getting-started-guides/minikube/
3.i had set local proxy


0815 13:08:08.437542   26488 pod_workers.go:183] Error syncing pod ea594ade-62c9-11e6-a57e-46b5af4532ee, skipping: failed to "StartContainer" for "kubernetes-dashboard" with ImagePullBackOff: "Back-off pulling image \"gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0\""
2016-08-15 13:08:12.937171 E | v2http: got unexpected response error (etcdserver: request timed out)
E0815 13:08:12.942928   26488 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
I0815 13:08:12.943712   26488 trace.go:61] Trace "Update /api/v1/nodes/minikubevm/status" (started 2016-08-15 13:08:05.789655407 +0000 UTC):
[18.235µs] [18.235µs] About to convert to expected version
[60.549µs] [42.314µs] Conversion done
[64.336µs] [3.787µs] About to store object in database
[7.154019902s] [7.153955566s] END
E0815 13:08:12.944011   26488 errors.go:63] apiserver received an error that is not an unversioned.Status: client: etcd cluster is unavailable or misconfigured
E0815 13:08:12.944277   26488 event.go:198] Server rejected event '&api.Event{TypeMeta:unversioned.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:api.ObjectMeta{Name:"kubernetes-dashboard-ianew.146af7b10651d171", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"2495", Generation:0, CreationTimestamp:unversioned.Time{Time:time.Time{sec:0, nsec:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*unversioned.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]api.OwnerReference(nil), Finalizers:[]string(nil)}, InvolvedObject:api.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"kubernetes-dashboard-ianew", UID:"ea594ade-62c9-11e6-a57e-46b5af4532ee", APIVersion:"v1", ResourceVersion:"1031", FieldPath:"spec.containers{kubernetes-dashboard}"}, Reason:"BackOff", Message:"Back-off pulling image \"gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0\"", Source:api.EventSource{Component:"kubelet", Host:"minikubevm"}, FirstTimestamp:unversioned.Time{Time:time.Time{sec:63606857367, nsec:0, loc:(*time.Location)(0x5873360)}}, LastTimestamp:unversioned.Time{Time:time.Time{sec:63606863272, nsec:816630640, loc:(*time.Location)(0x5873360)}}, Count:348, Type:"Normal"}': 'client: etcd cluster is unavailable or misconfigured' (will not retry!)
E0815 13:08:12.944739   26488 kubelet.go:2873] Error updating node status, will retry: client: etcd cluster is unavailable or misconfigured
2016-08-15 13:08:14.204978 E | v2http: got unexpected response error (etcdserver: request timed out) [merged 2 repeated lines in 1.26s]
F0815 13:08:14.281232   26488 kube2sky.go:404] Failed to mutate etcd for 10s using mutator: 0x5e7410

**Comment by r2d4** [comment]
@cherylhan Are you able to hit gcr.io through your proxy?  Try to see if you can even `ping gcr.io` as it seems that kubernetes is having trouble pulling the container image.

**Comment by cherylhan** [comment]
@r2d4 
 [root@localhost etc]# ping gcr.io
PING gcr.io (64.233.189.82) 56(84) bytes of data.

**Comment by cherylhan** [comment]
Error updating node status, will retry: client: etcd cluster is unavailable or misconfigured
  do i need  to install etcd?

**Comment by dlorenc** [comment]
Hey,

How do you have a local proxy setup? Could you try running both:

curl https://gcr.io/v2/google_containers/kubernetes-dashboard/tags/list

and 
minikube ssh "curl https://gcr.io/v2/google_containers/kubernetes-dashboard/tags/list"

(I'd expect the second one to fail if you're behind an HTTP proxy).

Did you pass the proxy environment variables to minikube start?

**Comment by dlorenc** [comment]
Ping @cherylhan :)

**Comment by dlorenc** [comment]
Closing this out. Please re-open with more information.
