### ISSUE TITLE
`minikube status` should not exit non-zero

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4932]
if minikube is not running and you do minikube status, it exists 1. I dont think it is an Error if you want your status to be not running !

```
 $ minikube status  --format={{.Host}}
 $ echo $?
1
```

this has caused weird error handling in integration tests

the same story goes if the status is stopped, the status command is returning 1:

$ ./out/minikube status --format={{.Host}}
Stopped
$ echo $?
1

**Comment by tstromberg** [comment]
I feel like 'stopped' should still return an error code, but a well defined one that differentiates between a general failure, 'stopped', and a failed cluster.

Thoughts?
