### ISSUE TITLE
minikube delete got "unrecognized option '--value'"

### ISSUE THREAD

**Issue by xieyanker** [kubernetes/minikube#4939]
Hello, I start a k8s cluster by use minikube on my linux os, `minikube start --vm-driver=none`, but it seems that not normal when I run `minikube delete`.

**The exact command to reproduce the issue**:
> minikube delete

**The full output of the command that failed**:
```shell
root@inserver-inspurclouddev-391-10:~/k8s-image-tars# minikube delete    
* Uninstalling Kubernetes v1.15.1 using kubeadm ...
* Deleting "minikube" in none ...
E0801 15:28:18.425271   17341 none.go:234] Temporary Error: for "sudo systemctl show -p SubState --value kubelet" : running command: sudo systemctl show -p SubState --value kubelet
.: exit status 1
* 
X Failed to delete cluster: expected to kubelet to be dead but it got : {"systemctl: unrecognized option '--value'\n" '\x00' "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00" '\x00'}
* 
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

**The operating system version**:
4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by afbjorklund** [comment]
It got added c60330078111eb559f21f288edcd11e861fef9c2, apparently it needs a newer systemd.

@medyagh : would it be possible to use something more portable ? Like parse the flag in the output

```console
$ sudo systemctl show -p SubState kubelet
SubState=dead
$ sudo systemctl show -p SubState --value kubelet
systemctl: okänd flagga "--value"
```

**Comment by xieyanker** [comment]
@afbjorklund Thanks for your reply, it works when use `sudo systemctl show -p SubState kubelet`.

**Comment by tstromberg** [comment]
@xieyanker - Which version of minikube are you using? Did you build minikube from source?

**Comment by medyagh** [comment]
Thanks @xieyanker for creating this issue ! I will update the command with 
`sudo systemctl show -p SubState kubelet`

Thanks @afbjorklund

**Comment by xieyanker** [comment]
@tstromberg I build minikube from the latest source, and my ubuntu version is 16.04.

**Comment by xieyanker** [comment]
@medyagh OK, thanks!
