### ISSUE TITLE
Push localkube 1.3.4

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#494]
Looks like this is missing from the prod releases.

**Comment by aaron-prindle** [comment]
The file was uploaded, the k8s_releases.json file was not updated to reflect this.  I have uploaded the file and now get the correct output:

$ ~/go/src/k8s.io/minikube$ m get-k8s-versions
The following Kubernetes versions are available: 
        - v1.3.4
        - v1.3.3
        - v1.3.0

**Comment by aaron-prindle** [comment]
Closing as I believe this is resolved now. Please reopen if that is not the case, thanks.
