### ISSUE TITLE
gvisor integration test missing testing failed event

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4943]
we have a func 

`waitForFailedCreatePodSandBoxEvent` which is unused ! and currently we don't test gvisor failed event in case of disabling it.

https://github.com/kubernetes/minikube/blob/9916d7a4387787f522b3881f30c7effb1a61f432/test/integration/util/util.go#L405

We need improve the gvisor integration test

**Comment by ianlewis** [comment]
@medyagh I'm not sure this part of the test was all that important anyway. I cleaned up the integration tests a bit in #4494 and removed this bit. Do you think anything more is needed?
