### ISSUE TITLE
apiserver: timed out waiting for the condition (after power outage)

### ISSUE THREAD

**Issue by cpu100** [kubernetes/minikube#4945]
Minikube fail to start after the PC unexpectedly loses power or is kicked: 

```
PS C:\Windows\system32> minikube.exe start
* minikube v1.2.0 on windows (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing virtualbox VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
* Relaunching Kubernetes v1.15.0 using kubeadm ...

X Error restarting cluster: waiting for apiserver: timed out waiting for the condition

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
* Problems detected in "kube-addon-manager":
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: net/http: TLS handshake timeout
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
```

I fell into this accident several times. I had to `minikube delete`, `minikube start`, then redeploy my development environment. This is very troublesome, is there a better solution?

**Comment by tstromberg** [comment]
minikube is designed to recover from most cases, but I'm sure there are edge cases we have not yet discovered.

Next time this happens, do you mind including the output of `minikube logs` and `kubectl get po -A`?

**Comment by chartheory** [comment]
[journalctl.log](https://github.com/kubernetes/minikube/files/3458209/journalctl.log)
The log is a bit too long, I have uploaded it. @tstromberg

**Comment by tstromberg** [comment]
@cpu100 - I looked at the journalctl logs, but it didn't have the information I was looking for. If you get a chance, could you please upgrade to minikube v1.3.1 and include the output of:

`minikube ssh "docker ps -a"`
`minikube logs

These would be very helpful in debugging the issue.

**Comment by cpu100** [comment]
This phenomenon should be very simple to reproduce，try `taskkill /F /IM VBoxHeadless.exe`, I think it will 99.9% run into the wrong state.

**Comment by cpu100** [comment]
If it can't be reproduced, I can try the new version again.

**Comment by tstromberg** [comment]
I tried twice, but was not able to reproduce with minikube v1.4.0-beta.0:

`minikue start...`
`sudo killall VBoxHeadless`

It's possibly that we accidentally fixed this issue, or at least that it's difficult to reproduce on my environment (VirtualBox 6.0.0, macOS 10.14.6). Do you mind trying minikube v1.4.0-beta.0, but set `--kubernetes-version=v1.15.0` for consistency with your current environment.

https://github.com/kubernetes/minikube/releases

**Comment by cpu100** [comment]
Tested on minikube v1.2.0、v1.3.0、v1.3.0, this issue can no be reproduced again, maybe some fixes came with the downloadable resources. thanks a lot.
