### ISSUE TITLE
pkg/proxy/config/api.go:30

### ISSUE THREAD

**Issue by cherylhan** [kubernetes/minikube#495]
i use minikube to run when i check the log，i meet this issue！
pkg/proxy/config/api.go:30: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused

**Comment by dlorenc** [comment]
Hey,

Which log did you check? Is this from "minikube logs"? Did you see any problems resulting from this?

**Comment by dlorenc** [comment]
Ping :)

**Comment by dlorenc** [comment]
Closing this out. Please re-open with more information!
