### ISSUE TITLE
504 error running minikube on Windows with HTTP proxy

### ISSUE THREAD

**Issue by federicovagnoni** [kubernetes/minikube#4955]
Hi!
I'm trying to use learn Kubernetes, so I tried Minikube on Windows (10, 64-bit). The problem is I'm behind an HTTP Proxy. The Proxy is already set up in Windows, I always log in when I open up a Firefox session.

I followed the instruction in http_proxy.md setting up the 3 env variables (HTTP_PROXY, HTTPS_PROXY and NO_PROXY). I found out, thanks to another issue, that I had to set HTTPS_PROXY equal as HTTP_PROXY (I think because of the proxy itself somehow). 

Anyway I'm trying to do the minikube quickstart tutorial with the hello-minikube but I'm not able to reach the service. I always got error 504.

What am I doing wrong? Thank you very much

**Comment by federicovagnoni** [comment]
I launch this command to create the minikube VM:

`minikube start --profile kubes  --docker-env http_proxy="%HTTP_PROXY%" --docker-env https_proxy="%HTTPS_PROXY%" --docker-env no_proxy="%NO_PROXY%"`

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs` (please upgrade to minikube v1.3.0 if possible, it will give more information)

For what it's worth, I don't think it's necessary to add the `--docker-env` arguments any longer. minikube will automatically add them if the proxy variables are set.

Thank you for sharing your experience!

**Comment by eepurichandra** [comment]
Did you find any solutions for this issue @federicovagnoni ?
I am also facing same issue on ubuntu.
I have added my minikube ip to no_proxy also

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

My advice would be to check the output of `kubectl get po -A`

Thank you for opening the issue!
