### ISSUE TITLE
Minikube does not start up in offline scenario

### ISSUE THREAD

**Issue by Homan13** [kubernetes/minikube#4957]
I have been working on getting Minikube to start up in an offline environment, and am using the following guidance;

https://github.com/kubernetes/minikube/blob/master/docs/offline.md

I have tried pulling both the cache directory, as well as tarring up the entire .minikube directory from a previous successful build; in both cases Minikube is still reaching out to try and grab the ISO files from official Google sites.

**The exact command to reproduce the issue**: When I start Minikube, I have pulled in both the cache directory, or in another case the entire .minikube directory, then run minikube start. The expected output should be for Minikube to pull the cached iso files.

**The full output of the command that failed**:<details>
 minikube start
* minikube v1.2.0 on linux (amd64)
* minikube will upgrade the local cluster from Kubernetes 1.14.2 to 1.15.0
* Downloading Minikube ISO ...

X Failed to cache ISO
* Error:         [ISO_DOWNLOAD_FAILED] https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: dial tcp 64.233.177.128:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: dial tcp 64.233.177.128:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: dial tcp 64.233.177.128:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: dial tcp 64.233.177.128:443: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/minikube/iso/minikube-v1.2.0.iso: dial tcp 64.233.177.128:443: i/o timeout
* Advice:        A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
* Documentation: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3922

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**: RHEL 7.6

**Comment by tstromberg** [comment]
For some reason minikube doesn't think you have a local ISO matching the default for the v1.2.0 release. Do you mind running these commands:

```
ls -la ~/.minikube/cache/iso/ 
sha256sum ~/.minikube/cache/iso/minikube-v1.2.0.iso
```

Alternatively, you can select --iso-url, but having a mismatched ISO version might cause complications.

**Comment by Homan13** [comment]
Sure can, here you go;

ls -la 
drwxr-x---. 2 vlabadmin vlabadmin       115 Aug  2 13:16 .
drwxr-x---. 5 vlabadmin vlabadmin        46 Jul 30 09:30 ..
-rw-------. 1 vlabadmin vlabadmin 137656320 Jul 30 09:28 minikube-v1.1.0.iso
-rw-------. 1 vlabadmin vlabadmin         0 Aug  1 16:19 .tmp-minikube-v1.2.0.iso770066608
-rw-------. 1 vlabadmin vlabadmin         0 Aug  2 13:16 .tmp-minikube-v1.2.0.iso972772891

sha256
e18e760e447c9ef3da6b5a527ef1080fb8ef7efe91fc9acb1989eb3975d09a6f  /home/vlabadmin/.minikube/cache/iso/minikube-v1.1.0.iso

So yeah, looks like I have a mismatch in versions. I think I know why actually, I've been using v1.1 to install on the machine, then it must be grabbing updated stuff. This should hopefully be an easy fix. Thanks for the quick response!

**Comment by Homan13** [comment]
Confirmed, closing issue.
