### ISSUE TITLE
Use configured DNS domain in bootstrapper kubeadm templates

### ISSUE THREAD

**Issue by Eelis** [kubernetes/minikube#4963]
The following two lines specify `cluster.local`, but if minikube was started with `--dns-domain bla`, that domain should probably be used instead.

https://github.com/kubernetes/minikube/blob/ae9f406b3852802b14c6b797a51d41eedd6d85b1/pkg/minikube/bootstrapper/kubeadm/templates.go#L87

https://github.com/kubernetes/minikube/blob/ae9f406b3852802b14c6b797a51d41eedd6d85b1/pkg/minikube/bootstrapper/kubeadm/templates.go#L141

**Comment by Eelis** [comment]
The effect of this bug is that `networking/dnsDomain` in the `ClusterConfiguration` entry in the `kubeadm-config` ConfigMap is set incorrectly.

**Comment by medyagh** [comment]
@bhanu011 are you still working on this ?

**Comment by bhanu011** [comment]
@medyagh yes.

**Comment by tstromberg** [comment]
Excellent! Please let me know if there is anything I could help with.

**Comment by tstromberg** [comment]
@bhanu011 - Will this be ready in time for the v1.4.0 release on Sep 16?

**Comment by tstromberg** [comment]
Any update?

**Comment by nanikjava** [comment]
@tstromberg @bhanu011 is this ticket being worked on ? happy to take and run with this. Thanks

**Comment by medyagh** [comment]
@nanikjava it is yours ! please let me know if you need any help

**Comment by nanikjava** [comment]
Thanks @medyagh

**Comment by nanikjava** [comment]
Check on /var/tmp/minikube/kubeadm.yaml inside minikube using ssh for testing the the --dns-domain flag

without using the flag
**********************

apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
......
......
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
.....
.....
kubernetesVersion: v1.16.0
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12
---


with the flag --dns-domain bla.blah.blah
****************************************

          
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
......
......
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
.....
.....
kubernetesVersion: v1.16.0
networking:
  dnsDomain: bla.blah.blah
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12
---

**Comment by nanikjava** [comment]
Pull request submitted https://github.com/kubernetes/minikube/pull/5566

**Comment by Eelis** [comment]
Awesome, thanks @nanikjava! This fix makes my life a lot easier. :)
