### ISSUE TITLE
Minikube takes very long time after the message 'Done! kubectl is now configured to use "minikube"'

### ISSUE THREAD

**Issue by CodingSpiderFox** [kubernetes/minikube#4970]
When it seems that installation hast finished, my terminal is still blocked for a few minutes after the following message:

![Selection_001](https://user-images.githubusercontent.com/25173078/62410898-a06e4000-b5ec-11e9-9272-89793beacec6.png)

**Comment by tstromberg** [comment]
It looks like this is being run within a script, are you sure it's blocked on minikube? The only explicit call made after this message is printed is:

`_, err := exec.LookPath("kubectl")`

If minikube is running, do you mind sharing the output of:

`strace -f -p <minikube pid>`

**Comment by CodingSpiderFox** [comment]
You're right I'm running it from a script.

I will check that next time

**Comment by CodingSpiderFox** [comment]
It's good now with the new version of minikube (1.3)
