### ISSUE TITLE
minikube crash after restart os

### ISSUE THREAD

**Issue by yrong** [kubernetes/minikube#4975]
- after restart os and open terminal:

`The docker host is currently not running`

-  os info

`
➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
`

-  minikube version
`
➜  ~ minikube version
minikube version: v1.2.0
`

-  kubectl version
`
➜  ~ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
`

-  kubectl config

`
➜  ~ kubectl config view
apiVersion: v1
clusters:
cluster:
    certificate-authority: /home/ronyang/.minikube/ca.crt
    server: https://192.168.99.100:8443
  name: minikube
contexts:
context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: ""
kind: Config
preferences: {}
users:
 name: minikube
  user:
    client-certificate: /home/ronyang/.minikube/client.crt
    client-key: /home/ronyang/.minikube/client.key
`

- after delete minikube

`
 ~ minikube delete
🔥  Deleting "minikube" from virtualbox ...
💔  The "minikube" cluster has been deleted.
`

-  and open new terminal

`
Error getting host: Machine does not exist for api.Exists(minikube)
Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

`

**Comment by afbjorklund** [comment]
This is "normal", if you have a non-existent and run the `docker-env` command:

```
$ minikube status
host: 
kubelet: 
apiserver: 
kubectl: 
$ minikube delete
🙄  "minikube" cluster does not exist
🙄  "minikube" profile does not exist
$ minikube docker-env

💣  Error getting host: Machine does not exist for api.Exists(minikube)

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

It needs a better error message to be shown, and it is definitely not a "crash"...

To get the machine back again (after deletion), you run another `minikube start`.

**Comment by afbjorklund** [comment]
It is the `CheckIfHostExistsAndLoad` that returns an _error_ (not a `bool`) if it is non-existing:

```go
	if !exists {
		return nil, errors.Errorf("Machine does not exist for api.Exists(%s)", machineName)
	}
```

This should probably find some other way of saying "everything was fine, but host is not there"

**Comment by yrong** [comment]
make sense
