### ISSUE TITLE
VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1).

### ISSUE THREAD

**Issue by AshwinDora** [kubernetes/minikube#4976]
**My Oracle virtual box (6.0.10) is exiting when I run the 'minikube start' command. Below is the VBoxHardening.log towards the end file content showing some problem. Please provide me some clue to resolve this.**:  My operating system is windows 10.

The error I get in cmd prompt when i run 'minikube start' is - 
--------------------------------------------------------------------
<details>
* minikube v1.2.0 on windows (amd64)
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0804 09:35:55.167282   15820 start.go:559] StartHost: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1).  
More details may be available in 'C:\cygwin64\home\Doraa\.minikube\machines\minikube\min ikube\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

X Unable to start VM
             * Error:         [VBOX_HARDENING] create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:                                             VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\cygwin64\home\Doraa\.minikube\machines\minikube\min ikube\Logs\VBoxHardening.log'
    VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

* Advice:        Disable real-time anti-virus software, reboot, and reinstall VirtualBox if the problem continues.                                                                                                 * Documentation: https://forums.virtualbox.org/viewtopic.php?f=25&t=82106                                                                                                                                          * Related issues:
                  - https://github.com/kubernetes/minikube/issues/3859
  - https://github.com/kubernetes/minikube/issues/3910

                        * If the above advice does not help, please let us know:
- https://github.com/kubernetes/minikube/issues/new

</details>
------------------------------------------------------------------------------------------

**Below is the VBoxHardening.log towards the end file content showing some problem **:<details>
39f8.5258: \SystemRoot\System32\privman64.dll:
39f8.5258:     CreationTime:    2017-06-22T16:52:44.000000000Z
39f8.5258:     LastWriteTime:   2017-06-22T16:52:44.000000000Z
39f8.5258:     ChangeTime:      2019-08-04T03:13:22.783874200Z
39f8.5258:     FileAttributes:  0x20
39f8.5258:     Size:            0x39100
39f8.5258:     NT Headers:      0xf8
39f8.5258:     Timestamp:       0x594be02a
39f8.5258:     Machine:         0x8664 - amd64
39f8.5258:     Timestamp:       0x594be02a
39f8.5258:     Image Version:   0.0
39f8.5258:     SizeOfImage:     0x3a000 (237568)
39f8.5258:     Resource Dir:    0x38000 LB 0x578
39f8.5258:     [Version info resource found at 0x80! (ID/Name: 0x1; SubID/SubName: 0x0)]
39f8.5258:     [Raw version resource data: 0x380a0 LB 0x37c, codepage 0x4e4 (reserved 0x0)]
39f8.5258:     ProductName:     PowerBroker for Windows
39f8.5258:     ProductVersion:  7.3.0.0
39f8.5258:     FileVersion:     7.3.0.0
39f8.5258:     FileDescription: BeyondTrust PowerBroker for Windows DLL
39f8.5258: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume2\Program Files\Oracle\VirtualBox'
39f8.5258: Calling main()
39f8.5258: SUPR3HardenedMain: pszProgName=VBoxHeadless fFlags=0x0
39f8.5258: supR3HardenedWinInitAppBin(0x0): '\Device\HarddiskVolume2\Program Files\Oracle\VirtualBox'
39f8.5258: '\Device\HarddiskVolume2\Program Files\Oracle\VirtualBox\VBoxHeadless.exe' has no imports
39f8.5258: supHardenedWinVerifyImageByHandle: -> 24202 (\Device\HarddiskVolume2\Program Files\Oracle\VirtualBox\VBoxHeadless.exe)
39f8.5258: SUPR3HardenedMain: Respawn #2
39f8.5258: Error (rc=-5640):
39f8.5258: More than one thread in process
39f8.5258: Error -5640 in supR3HardenedWinReSpawn! (enmWhat=1)
39f8.5258: More than one thread in process
39f8.5258: '\Device\HarddiskVolume2\Windows\System32\ntdll.dll' has no imports
39f8.5258: supHardenedWinVerifyImageByHandle: -> 0 (\Device\HarddiskVolume2\Windows\System32\ntdll.dll)
39f8.5258: supR3HardenedWinVerifyCacheInsert: \Device\HarddiskVolume2\Windows\System32\ntdll.dll
39f8.5258: supR3HardenedMonitor_LdrLoadDll: pName=C:\windows\System32\ntdll.dll (Input=ntdll.dll, rcNtResolve=0xc0150008) *pfFlags=0x0 pwszSearchPath=0000000000000801:<flags> [calling]
39f8.5258: supR3HardenedMonitor_LdrLoadDll: returns rcNt=0x0 hMod=00007ffbc3730000 'C:\windows\System32\ntdll.dll'
3078.6bc: supR3HardNtChildWaitFor[1]: Quitting: ExitCode=0x1 (rcNtWait=0x0, rcNt1=0x0, rcNt2=0x103, rcNt3=0x103, 48 ms, the end);
</details>

**The operating system version**: Windows 10

**Comment by blueelvis** [comment]
Hi!

Thanks for reporting this issue! Could you please try the following -
- Could you please provide the output of `minikube logs`?
- Could you please try deleting the VM, deleting the ".minikube" folder and try again?
- Instead of trying to run it from Cygwin, can you try running it from a PowerShell prompt with Administrator privileges?

**Comment by AshwinDora** [comment]
@blueelvis 
 ->  I have provided the minikube error message and the VBoxHardening.log in my issue. Is there any other logs of minikube that you are looking for ?
-> W.R.T VM I have upgraded from 5.0.10 to 6.0.10 and deleted the .minikube folder multiple times still no luck.
-> W.R.T powershell I have read in so many places that its not compatible with virtual box and thats why used cygwin.

**Comment by tstromberg** [comment]
These forum posts appear to have some related information:

* https://forums.virtualbox.org/viewtopic.php?f=6&t=88639
* https://forums.virtualbox.org/viewtopic.php?f=6&t=68869&start=15

@AshwinDora -It appears that there is some anti-virus or security software that is interfering with VirtualBox functioning properly on your machine. My advice is:

- Try running minikube from a  PowerShell or `cmd.exe` window running as the Administrator.  For example: https://www.isunshare.com/windows-10/2-ways-to-run-command-prompt-as-administrator-in-win-10.html
- Try disabling the "BeyondTrust PowerBroker" software on your machine. Alternatively, https://forums.virtualbox.org/viewtopic.php?f=6&t=88639#p455263 has instructions on how you can configure PowerBroker to work with VirtualBox.
- Try disabling any anti-virus software you have.

Also, do you mind including the output of `minikube start` in your environment? I want to make sure we can point other users to this issue if they run into a similar problem. Thanks!

**Comment by atulksigma** [comment]
I am facing this issue on Ubuntu Bionic (18.4). Below is the startup command output

> (base) ➜  ~ minikube start 
> 
> 😄  minikube v1.3.1 on Ubuntu 18.04
> 🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
> E0829 16:04:22.318631   29308 start.go:723] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
> VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
> 
> 💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
> VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
> 
> 
> 😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> 👉  https://github.com/kubernetes/minikube/issues/new/choose
> 

I have tried deleting the .minikube folder, deleting VMs from virtualbox interface as also minikube delete.

Its a virtualbox Version 6.0.10 r132072 (Qt5.9.5) on Ubunto 18.04.3 LTS with minikube version v1.3.1 (commit: ca60a424ce69a4d79f502650199ca2b52f29e631) and kubectl version as below

> Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
> The connection to the server localhost:8080 was refused - did you specify the right host or port?
> 

There are 2 virtual box interfaces - vboxnet0 and vboxnet1. Could this be an error?

Below is minikube logs output

> 💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused
>
> 😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> 👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
@AshwinDora - Do you mind trying with minikube v1.4?

Also, I'm curious if this only happens when you are using minikube from Cygwin, or if it happens from PowerShell.

**Comment by dblees** [comment]
**minikube version**
- minikube version: v1.4.0
- commit: 7969c25a98a018b94ea87d949350f3271e9d64b6

**minikube start**
- X Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
- VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
- VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**minikube logs**
- api load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

**Comment by medyagh** [comment]
@dblees   do you mind trying with latest version of virtualbox 6.1  and also latest version of minikube ?

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
