### ISSUE TITLE
none: apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by wuchuwei** [kubernetes/minikube#4977]
下面是执行后的结果。错误很明显。但我不知道为什么其它人可以成功。
请问我是哪里做错了。
[root@k8s ~]# minikube start --vm-driver=none
* minikube v1.2.0 on linux (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing none VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.15.0 on Docker 19.03.1
* Relaunching Kubernetes v1.15.0 using kubeadm ... 
X Error restarting cluster: waiting for apiserver: timed out waiting for the condition
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

操作步骤：install docker->curl minikube->install minikube /usr/local/bin -> minikube start --vm-driver=none
我的本意是在不用kvm等其它虚拟化层来运行kubernetes的组件。
我的运行环境是lxc->centos7上的

**Comment by tstromberg** [comment]
Do you mind upgrading to minikube v1.3.0 and sharing the output of `minikube logs`?

**Comment by wuchuwei** [comment]
> Do you mind upgrading to minikube v1.3.0 and sharing the output of `minikube logs`?

I don't mind.

**Comment by wuchuwei** [comment]
my change docker service  to Using cgroupfs 

- root@localhost ~]# systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; disabled; vendor preset: disabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since 日 2019-08-18 18:02:58 CST; 13min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 29708 (kubelet)
   CGroup: /system.slice/kubelet.service
           └─29708 /usr/bin/kubelet --authorization-mode=Webhook --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --c...

8月 18 18:16:38 localhost.localdomain kubelet[29708]: E0818 18:16:38.505032   29708 reflector.go:125] k8s.io/kubernetes/pkg/...fused
8月 18 18:16:38 localhost.localdomain kubelet[29708]: E0818 18:16:38.582744   29708 kubelet.go:2248] node "minikube" not found
8月 18 18:16:38 localhost.localdomain kubelet[29708]: E0818 18:16:38.682893   29708 kubelet.go:2248] node "minikube" not found
8月 18 18:16:38 localhost.localdomain kubelet[29708]: E0818 18:16:38.705214   29708 reflector.go:125] k8s.io/client-go/infor...fused
8月 18 18:16:38 localhost.localdomain kubelet[29708]: E0818 18:16:38.783041   29708 kubelet.go:2248] node "minikube" not found
8月 18 18:16:38 localhost.localdomain kubelet[29708]: E0818 18:16:38.883185   29708 kubelet.go:2248] node "minikube" not found
8月 18 18:16:38 localhost.localdomain kubelet[29708]: E0818 18:16:38.906187   29708 reflector.go:125] k8s.io/client-go/infor...fused
8月 18 18:16:38 localhost.localdomain kubelet[29708]: E0818 18:16:38.983367   29708 kubelet.go:2248] node "minikube" not found
8月 18 18:16:39 localhost.localdomain kubelet[29708]: E0818 18:16:39.023624   29708 controller.go:115] failed to ensure node...fused
8月 18 18:16:39 localhost.localdomain kubelet[29708]: E0818 18:16:39.083533   29708 kubelet.go:2248] node "minikube" not found
Hint: Some lines were ellipsized, use -l to show in full.

minikube logs ouput:
-- Logs begin at 一 2019-08-05 18:29:41 CST, end at 日 2019-08-18 18:13:16 CST. --
8月 18 18:13:13 localhost.localdomain kubelet[29708]: E0818 18:13:13.334867   29708 kubelet.go:2248] node "minikube" not found
8月 18 18:13:13 localhost.localdomain kubelet[29708]: E0818 18:13:13.435019   29708 kubelet.go:2248] node "minikube" not found
8月 18 18:13:13 localhost.localdomain kubelet[29708]: E0818 18:13:13.502251   29708 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp [::1]:8443: connect: connection refused

**Comment by tstromberg** [comment]
Those logs don't look like the output of `minikube logs` ... they are missing the `dmesg` output for one.  I'd be really curious to see what the output of `docker ps -a` is in this environment. Thanks!

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by wuchuwei** [comment]
Tstromberg, thank you very much.
The problem is docker not pull docker images
