### ISSUE TITLE
Changing VM hardware (memory, cores) has no effect after provisioning

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#4979]
Pretty sure this would be the case with other drivers as well.
**The exact command to reproduce the issue**:
```
.\minikube-windows-amd64.exe start --vm-driver=hyperv --hyperv-virtual-switch="Default Switch" --memory=1700
.\minikube-windows-amd64.exe start --vm-driver=hyperv --hyperv-virtual-switch="Default Switch" --memory=1500 --cpus=1
```

The cluster initially gets provisioned with the memory and CPU but if I start it again with new parameters, the VM is just started with the original values as you can see from the below screenshot -
![image](https://user-images.githubusercontent.com/6985763/62427882-88470f80-b717-11e9-9e2b-0785e3708027.png)

I think this should be configurable. The only thing which should not be configurable in size is the hard disk size.

**The operating system version**:
Windows 10 Enterprise.

Pretty sure this would be applicable across all drivers and all the operating systems.

**Comment by tstromberg** [comment]
I'm not sure if the machine drivers infrastructure allows on-the-fly hardware changing. I'm also not sure if there is a way we can detect whether the current VM has the correct hardware settings.

What we can do however is compare the current VM config with the previously saved one, and recreate the VM, preserving the new disk if at all possible. If preserving the disk isn't possible, we should prompt the user or require them to add a flag for deletion.

**Comment by afbjorklund** [comment]
Normally you would change this in the machine JSON file, and then restart the machine...

I think minikube could do the same thing with the config, after the Load but before the Save ?

**Comment by afbjorklund** [comment]
This probably depends a lot on the driver... Some create external config, some pass parameters.

If it _does_ create an external object, then it does need the aforementioned synchronization step.

**Comment by sharifelgamal** [comment]
This is probably still worth looking at.

**Comment by priyawadhwa** [comment]
Hey @blueelvis --

Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
