### ISSUE TITLE
X Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.15.0: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

### ISSUE THREAD

**Issue by xuanyuanyu168** [kubernetes/minikube#4982]
X Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.15.0: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 216.58.200.48:443: connect: connection refused
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 216.58.200.48:443: connect: connection refused
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 216.58.200.48:443: connect: connection refused
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 216.58.200.48:443: connect: connection refused
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet: dial tcp 216.58.200.48:443: connect: connection refused

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
root@ubuntu:~# ls

**Comment by tstromberg** [comment]
It sounds like your host does not have access to download Kubernetes binaries from Google Cloud Storage. Is it possible that you are running this from a machine in China?

See: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

**Comment by tstromberg** [comment]
Related: #5020
