### ISSUE TITLE
Enabling RBAC ?

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/minikube#499]
Hi folks, how can we enable RBAC in minikube so we can use Role, RoleBinding objects...etc to test the alpha RBAC feature ?
thanks

**Comment by runseb** [comment]
In the same token, it does not seem that we can create ThirdPartyResource objects. Is that enabled in the API server ?

**Comment by dlorenc** [comment]
We don't currently set the Authorization mode in apiserver.go, but we would need to make this configurable via a flag to enable RBAC.

**Comment by dlorenc** [comment]
Looks like ThirdPartyResources need this to work: https://github.com/kubernetes/kubernetes/pull/28414

**Comment by runseb** [comment]
@dlorenc where would you like to keep track of feature requests like this ? and would you prefer I open a separate issue for supporting ThirdPartyResource ?

**Comment by dlorenc** [comment]
This is a fine place to track the feature requests. We have a 1.4 alpha build coming out soon that should have the upstream fix for ThirdPartyResources, no need to open another bug.

**Comment by dlorenc** [comment]
ref #512

**Comment by dlorenc** [comment]
This is now possible and documented in the README.md here: https://github.com/kubernetes/minikube#examples

Let me know if it works!

**Comment by thomasfricke** [comment]
I tried it, and I could not bootstrap the RBAC. How can I use this from scratch?

**Comment by brancz** [comment]
I created a minikube cluster like this as described in the [examples section](https://github.com/kubernetes/minikube#examples):

```
$ minikube start --vm-driver=virtualbox --kubernetes-version=v1.5.2 --memory=4096 --extra-config=apiserver.GenericServerRunOptions.AuthorizationMode=RBAC --extra-config=apiserver.GenericServerRunOptions.AuthorizationRBAC,SuperUser=minikube
```

Then tried to create a bundle of resources and received the following:

```
$ kubectl create -f bundle.yaml 
Error from server (Forbidden): error when creating "bundle.yaml": the server does not allow access to the requested resource (post serviceaccounts)
error validating "bundle.yaml": error validating data: the server does not allow access to the requested resource; if you choose to ignore these errors, turn validation off with --validate=false
```

**Comment by rongutierrez** [comment]
I'm also running into the same issue as @brancz

**Comment by Hashfyre** [comment]
Currently the documentation is here: https://github.com/kubernetes/minikube/blob/master/docs/configuring_kubernetes.md
