### ISSUE TITLE
[1.13] Add wait=false as a minikube config

### ISSUE THREAD

**Issue by BenHall** [kubernetes/minikube#4990]
Great to see `minikube start --wait=false` added which I think will help with #4588

It would also be extremely helpful if this could be set using `minikube config` so false can be the default value.

**Comment by tstromberg** [comment]
+1 Sounds like a great idea!

**Comment by tstromberg** [comment]
With the improved wait behavior and timings in minikube v1.6 this is probably less of a priority, but it's still an issue.
