### ISSUE TITLE
Remove "Ignoring --vm-driver" warning

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#4998]
Related to #4855 and #4614

This warning is noisy and is always doing the wrong thing. It's raised in two scenarios:

## 1. User has an existing non-virtualbox VM and runs `minikube start` - sees warning.

The user has not specified a --vm-driver here. We should quietly do what the user wants and resume their existing VM.

## 2. User has specified an existing VM, and runs `minikube start --vm-driver=xxx`

The user has explicitly specified a VM driver. We should error and exit, rather than ignoring their request.

Implementation wise, the most obvious way to do this is change the default driver to `auto`. If they have an existing config, the automatic default is to use that driver. If not, we can stick with `virtualbox` and build toward "best available".

**Comment by tstromberg** [comment]
@RA489 - Will this issue be resolved in time for v1.4.0 (Sep 16?)

**Comment by RA489** [comment]
@tstromberg yeah, sure
