### ISSUE TITLE
Multiple platform support

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#5]
Server platforms for `linux/amd64`, `linux/arm`, `linux/arm64`, `linux/ppc64le`
Client platforms for `windows/amd64`, `darwin/amd64` + the above

@dlorenc @vishh

**Comment by dlorenc** [comment]
We could create a libmachine driver for qemu/libvirt to run ARM VMs on non-arm hosts. Some work on this was already done here:
https://github.com/docker/machine/issues/504

**Comment by luxas** [comment]
I didn't mean we should provide a VM for `arm|arm64|ppc64le`
For those platforms, we should provide the docker (or host) solution only.

So for `linux/amd64, linux/arm, linux/arm64, linux/ppc64le`:
minikube client -> (docker) -> minikube server

For `linux/amd64, windows/amd64, darwin/amd64`
minikube client -> libmachine -> virtualbox/hyperv -> linux vm -> minikube server

**Comment by luxas** [comment]
This isn't for the 0.1 release, but the release after. Therefore marking as P2

**Comment by dlorenc** [comment]
Is there anything you want to do here for 0.2.0? I'm hoping to cut it tomorrow.

**Comment by luxas** [comment]
No, feel free to move it to v0.3.

Right now I'm writing a multiarch proposal (will cc you), which should be in before v1.3, so I haven't time to fix this before tomorrow.

**Comment by luxas** [comment]
OK, I've too much to do atm...
I've made progress with these things, but I have no PR for this yet

**Comment by luxas** [comment]
As we decided to go the VM route fully for minikube (no dockerized mode etc.), we can effectively only have it on amd64, which is ok

kubeadm supports other platforms instead, check that out!

(Also ref the multiarch doc: https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/multi-platform.md)
