### ISSUE TITLE
How to use GPU in Minikube?

### ISSUE THREAD

**Issue by warf34** [kubernetes/minikube#5005]
I want to use GPU in Minikube

i run Minikube on Virtualbox
`minikube start --disk-size 50g --memory 8192 --cpus 4`

and i have applied pod
`kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/1.0.0-beta/nvidia-device-plugin.yml`

when I check the GPU
`kubectl get nodes "-o=custom-columns=NAME:.metadata.name,GPU:.status.allocatable.nvidia\.com/gpu"`

result is
```
NAME       GPU
minikube   <none>
```
 how to use GPU in Minikube?

i installed
cuda 10.0
docker version: 1.40
nvidia-docker version: 2.0.3
minikube version: v1.3.0
kubectl version: 1.15.1

**Comment by afbjorklund** [comment]
Did you look at https://github.com/kubernetes/minikube/blob/master/docs/gpu.md ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by edernucci** [comment]
> Did you look at https://github.com/kubernetes/minikube/blob/master/docs/gpu.md ?

404 Not Found :-(

**Comment by MichaelMitchellM** [comment]
https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/
