### ISSUE TITLE
Change Linux kernel to 4.19 or 4.14 (LTS)

### ISSUE THREAD

**Issue by reegnz** [kubernetes/minikube#5007]
## Current state
Current Linux kernel version is 4.15.0. The 4.15 branch is unmaintained.

## Desired change
We should change to an LTS kernel version (eg. 4.14.x or 4.19.x).
Ideally we should also follow up on kernel security updates on each minikube release, so that we do not compromise the security of our users minikube machines.

## Reasoning
I am using some security tokens (AWS and GitHub access keys) from within minikube even during development. Although these are revokable tokens, some security issues might still result in a scenario where these tokens get leaked with the help of an already mitigated and published CVE in the Linux kernel.

Reducing the attack-surface of the Linux kernel used in minikube helps with this situation.

**Comment by reegnz** [comment]
Looking at the projected EOL dates: https://www.kernel.org/releases.html

Staying with 4.14 would be the best from a stability point of view, as there they project updating it until 2024.
4.19 is also updated until 4.19, so that also seems like a safe bet, but that means a shift to an 5.4 LTS needs to be done next year. 
I say the 4.14 branch is a safer bet.

**Comment by afbjorklund** [comment]
We are going to update to Linux 4.19, as part of the update to Buildroot 2019.02 (LTS)

And I agree that we should look at updating these things (kernel and distro) more often.

**Comment by afbjorklund** [comment]
> I say the 4.14 branch is a safer bet.

We are trying to make a trade-off between the latest/greatest and the stable/supported requirements.

So some want Linux 5 and some want "good old" 4.14, some want Docker 19 and some want 18.06

**Comment by reegnz** [comment]
Yeah, but hopefully it's no biggie to upgrade again.
Although I saw that there was a downgrade from 4.16 to 4.15 because of some vboxsf module compile issue, but I hope that can be fixed with upgrading to a newer guest-additions version.

**Comment by medyagh** [comment]
@afbjorklund have some works on the way that would pave our way to upgrade linux

**Comment by afbjorklund** [comment]
The new buildroot version now comes with linux 4.19.76

**Comment by tstromberg** [comment]
Closing since this is fixed at head.
