### ISSUE TITLE
C:\Users\<user>\.minikube: Access is denied.

### ISSUE THREAD

**Issue by dgonzamo13** [kubernetes/minikube#5008]
I can't remove the content of this folder, also minikube can't start...

Error on Windows 10:
*
X Error creating minikube directory: mkdir C:\Users\<user>\.minikube: Access is denied.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
This sounds like a permissions issue: perhaps minikube was started with elevated permissions? 

@sharifelgamal mentioned he has run into something similar.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by tAnboyy** [comment]
> I can't remove the content of this folder, also minikube can't start...
> 
> Error on Windows 10: * X Error creating minikube directory: mkdir C:\Users<user>.minikube: Access is denied. *
> 
> * Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
>   
>   * https://github.com/kubernetes/minikube/issues/new/choose

Faced the same error.
Fixed it by changing id_rsa file settings. Properties -> Security -> Advanced -> Enable inheritance.
