### ISSUE TITLE
Update --disable-driver-mounts default to false

### ISSUE THREAD

**Issue by deepdad** [kubernetes/minikube#5012]
Please remove the standard Shared Folder on VirtualBox and guide users how and when to use it. The shared folder isn't used by the Hello minikube tutorial. It can easily be forgotten while users start deploying apps that generate outgoing traffic. I don't know how hard it is to then start uploading data from the default shared folder, but I think it could involve merely a docker image with elevated user rights.

DisableDriverMounts bool               // Only used by virtualbox

**Comment by deepdad** [comment]
I would also use a no outgoing egress on all namespaces to be turned off as part of hello minikube: you seem to need outgoing traffic for basic execution. I see a lot of traffic run off from images that are parts of tutorials. I don't know what that is about, probably usage monitoring but that's still odd and never mentioned.

**Comment by afbjorklund** [comment]
It _used_ to be controlled by a flag: `minikube start --disable-driver-mounts`

However, for some reason this flag is now missing from `v1.3.0` options ?

**Comment by afbjorklund** [comment]
Suggest bringing the flag back for `v1.3.1`, consider flipping it for a future release perhaps

**Comment by afbjorklund** [comment]
Actually it got lost in the merge conflict resolution: 1b83a89df3e6229b8f6b666f39d5d1a74241fd61 by @tstromberg 

Sadly git doesn't show these (merge commits) properly, when doing the pick-axe.

**Comment by deepdad** [comment]
What pods and stuff have sudo privilege ?

**Comment by afbjorklund** [comment]
> After installing minikube with sudo, is running $minikube actually doing $sudo minikube

It _might_ (for the `none` driver), but normally it will do that **in the VM** - and not on the host.

However, it will not be for re-running minikube itself but for commands like `sudo kubeadm`

We warn against running minikube as root (or sudo), there should be no need for that.

You still enough administrator privileges to use the hypervisor, but that is another story...

**Comment by tstromberg** [comment]
Related: #5019

**Comment by medyagh** [comment]
we will not do this issue, till we have a solution for non-9p mounts
