### ISSUE TITLE
Binary size has increased after 1.3 release (15mb)

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#5013]
The binary size from v1.2.0 to v1.3.0 has increased by almost 15MB which is quite a lot. If this trend continues, it won't be long before we hit the 100MB mark.

Creating this issue to keep track of this. Needs further investigation.

**Comment by afbjorklund** [comment]
Sizes:
```
39216	minikube-v1.0.0
40756	minikube-v1.1.0
40840	minikube-v1.2.0
54452	minikube-v1.3.0
```

**Comment by afbjorklund** [comment]
Early analysis seems like most of the size increase comes from `github.com/hashicorp/go-getter`

Mostly because it has some large dependencies for alternative storage, such as AWS and GCS.

**Comment by medyagh** [comment]
ah.. at this point I am purposing removing go-getter...

**Comment by medyagh** [comment]
I feel guilty for adding go-getter to replace our own download mechanism, since they had a better retry logic for downloading and resumming but it seems like I added a bunch of issues, such as breaking progress bar, and adding binary size.

**Comment by medyagh** [comment]
@tstromberg what do you think

**Comment by medyagh** [comment]
I will pick up a task to replace come up with a better download strategy across all minikube

**Comment by afbjorklund** [comment]
The size of the minikube is still _largely_ irrelevant, compared to the rest of the downloads:

```
132M	iso/minikube-v1.3.0.iso
39M	v1.15.2/kubeadm
41M	v1.15.2/kubectl
115M	v1.15.2/kubelet
325M	total
```

And then there is some additional 828M of images to be pulled, most of them in `etcd`.

```
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
k8s.gcr.io/kube-controller-manager   v1.15.2             9f5df470155d        2 days ago          159MB
k8s.gcr.io/kube-proxy                v1.15.2             167bbf6c9338        2 days ago          82.4MB
k8s.gcr.io/kube-scheduler            v1.15.2             88fa9cb27bd2        2 days ago          81.1MB
k8s.gcr.io/kube-apiserver            v1.15.2             34a53be6c9a7        2 days ago          207MB
k8s.gcr.io/coredns                   1.3.1               eb516548c180        6 months ago        40.3MB
k8s.gcr.io/etcd                      3.3.10              2c4adeb21b4f        8 months ago        258MB
k8s.gcr.io/pause                     3.1                 da86e6ba6ca1        19 months ago       742kB
```

**Comment by medyagh** [comment]
link to @afbjorklund 's anlaysis
```
https://gist.github.com/afbjorklund/635893ee8be7c6523e2c8c6f9e821572
```

**Comment by afbjorklund** [comment]
After removing github.com/aws/aws-sdk-go/aws and cloud.google.com/go/storage:

`46836	out/minikube-linux-amd64`

So 10M gone, but 5M left.

**Comment by afbjorklund** [comment]
We might make another attempt at this, for the next release (`v1.5.0`)

```
39216	minikube-v1.0.0
40756	minikube-v1.1.0
40840	minikube-v1.2.0
54452	minikube-v1.3.0
56108	minikube-v1.4.0
```

It's still far from rumored 100M, and still only 5% of the total download.

**Comment by afbjorklund** [comment]
@blueelvis : I am inclined to close this. Basically nobody cares about 15M.

```
56M	out/minikube-linux-amd64
```

If they did, it would be easier to "fix" that by adding compression instead...

```
36M	out/minikube-linux-amd64.tar.gz
```

**Comment by afbjorklund** [comment]
Still has some way to go before 100M:

![minikube-sizes](https://user-images.githubusercontent.com/10364051/67619249-7bf3bf80-f7f9-11e9-9a17-826e447963fb.png)

**Comment by blueelvis** [comment]
Yeah, feel free to close this issue. This is in no way a blocker but just a
placeholder to ensure that we are mindful of the sizes as well.

Thanks,
Pranav

**Comment by priyawadhwa** [comment]
It seems that this issue can be closed, feel free to reopen if needed!
