### ISSUE TITLE
Remove heapster addon - it's retired.

### ISSUE THREAD

**Issue by deepdad** [kubernetes/minikube#5017]
https://github.com/kubernetes-retired/heapster

"RETIRED: Heapster is now retired. See the deprecation timeline for more information on support. We will not be making changes to Heapster.

The following are potential migration paths for Heapster functionality:

For basic CPU/memory HPA metrics: Use metrics-server.

For general monitoring: Consider a third-party monitoring pipeline that can gather Prometheus-formatted metrics. The kubelet exposes all the metrics exported by Heapster in Prometheus format. One such monitoring pipeline can be set up using the Prometheus Operator, which deploys Prometheus itself for this purpose.

For event transfer: Several third-party tools exist to transfer/archive Kubernetes events, depending on your sink. heptiolabs/eventrouter has been suggested as a general alternative."

**Comment by deepdad** [comment]
RETIRED: Heapster is now retired. See the deprecation timeline for more information on support. We will not be making changes to Heapster.

The following are potential migration paths for Heapster functionality:

For basic CPU/memory HPA metrics: Use metrics-server.

For general monitoring: Consider a third-party monitoring pipeline that can gather Prometheus-formatted metrics. The kubelet exposes all the metrics exported by Heapster in Prometheus format. One such monitoring pipeline can be set up using the Prometheus Operator, which deploys Prometheus itself for this purpose.

For event transfer: Several third-party tools exist to transfer/archive Kubernetes events, depending on your sink. heptiolabs/eventrouter has been suggested as a general alternative.

**Comment by tstromberg** [comment]
This will require removing `deploy/addons/heapster` and the handful of references to heapster in our code base. PR's welcome.

**Comment by kaihendry** [comment]
Just tried minikube in Arch today and I'm hitting `Error from server (NotFound): the server could not find the requested resource (get services http:heapster:)` when running `kubectl top pod`. Was expecting some feature parity with Docker.

So how is one supposed to get basic pod usage stats out in the interim?

**Comment by hypnoglow** [comment]
@kaihendry You need to install [metrics-server](https://github.com/kubernetes-incubator/metrics-server) to your cluster.
