### ISSUE TITLE
tunnel on macOS: application sending entire HTML page (packet loss?)

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5022]
@priyawadhwa had a demo at SF Kubernetes yesterday where the application sent traffic properly using port forwarding, but with `minikube tunnel`, only the page title loaded. It seemed like a packet loss issue.

@priyawadhwa - do you mind sharing the command-lines we can use to replicate it?

**Comment by medyagh** [comment]
cc: @priyawadhwa
