### ISSUE TITLE
Option to turn off emoji

### ISSUE THREAD

**Issue by northys** [kubernetes/minikube#5024]
Is there any way to turn off all those emojis in console output? I've grown already and it feels like playing with toys which have to be cute so babies love them.

**The exact command to reproduce the issue**:

`minikube start`

**The full output of the command that failed**:<details>

😄  minikube v1.3.0 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**: Ubuntu 18.04

**Comment by maxstreese** [comment]
afaik `export MINIKUBE_IN_STYLE=false`

**Comment by northys** [comment]
@maxstreese cool, thanks
