### ISSUE TITLE
minikube dashboard service not found

### ISSUE THREAD

**Issue by wangweihong** [kubernetes/minikube#503]
When I use`minikube dashborad` command, I got 
> kiongf@youruncloud:~/k8s/project$ minikube dashboard
> E0818 14:23:21.505243    3125 dashboard.go:45] Error accessing the kubernetes dashboard (is minikube running?): Error:  Error getting kubernetes-dashboard service: services "kubernetes-dashboard" not found

I find the reason is the pod `kube-addon-manager-minikubevm` and ` kubernetes-dashboard-*` which namespace are `kube-system`  wait in `ImangePullBackOff` state.  
These pods try to pull image from "gcr.io" and fail for GFW. 
 
I login to `minikubevm` and pull these images from my private registry, and retag them.
docker@minikubeVM:~$ docker images
REPOSITORY                                             TAG                 IMAGE ID            CREATED             SIZE
gcr.io/google_containers/kubernetes-dashboard-amd64    v1.1.0              d023c050c065        4 weeks ago         58.65 MB
gcr.io/google-containers/kube-addon-manager-amd64      v2                  a876fb07f9c2        12 weeks ago        231.1 MB
gcr.io/google_containers/pause-amd64                   3.0                 99e59f495ffa        3 months ago        746.9 kB

 Pod  `kube-addon-manager-minikubevm` work well, however, pod ` kubernetes-dashboard-*` always try to pull `gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0` : 

>   2m		2m		1	{kubelet minikubevm}						Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "kubernetes-dashboard" with ErrImagePull: "image pull failed for gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0, this may be because there are no credentials on this request.  details: (An error occurred trying to connect: Post http://%2Fvar%2Frun%2Fdocker.sock/images/create?fromImage=gcr.io%2Fgoogle_containers%2Fkubernetes-dashboard-amd64&tag=v1.1.0: EOF)"

**Comment by dlorenc** [comment]
Which version of minikube are you using? Could you attach the contents of /etc/kubernetes/addons/dashboard-rc.yaml from inside the minikube VM?

**Comment by wangweihong** [comment]
@dlorenc  
 hi dlorenc, I'm using `minikube version: v0.7.1`.
This is my /etc/kubernetes/addons/dashboard-rc.yaml
# This file should be kept in sync with cluster/addons/dashboard/dashboard-controller.yaml

> apiVersion: v1
> kind: ReplicationController
> metadata:
>   name: kubernetes-dashboard
>   namespace: kube-system
>   labels:
>     app: kubernetes-dashboard
>     version: v1.1.0
>     kubernetes.io/cluster-service: "true"
> spec:
>   replicas: 1
>   selector:
>     app: kubernetes-dashboard
>     version: v1.1.0
>     kubernetes.io/cluster-service: "true"
>   template:
>     metadata:
>       labels:
>         app: kubernetes-dashboard
>         version: v1.1.0
>         kubernetes.io/cluster-service: "true"
>     spec:
>       containers:
>       - name: kubernetes-dashboard
>         # ARCH will be replaced with the architecture it's built for. Check out the Makefile for more details
>         image: gcr.io/google_containers/kubernetes-dashboard-amd64:v1.1.0
>         imagePullPolicy: Always
>         ports:
>         - containerPort: 9090
>           protocol: TCP
>         livenessProbe:
>           httpGet:
>             path: /
>             port: 9090
>           initialDelaySeconds: 30
>           timeoutSeconds: 30
>

**Comment by wangweihong** [comment]
I try to edit `kubernetes-dashboard` rc  and remove `imagePullPolicy:Always` of container ` kubernetes-dashboard`   . and now It works. So I think this is the reason.

**Comment by r2d4** [comment]
@wangweihong this was fixed in v0.8.0 by #429 

I'm going to close this but feel free to reopen if you experience the same problem on v0.8.0

Thanks!
