### ISSUE TITLE
The virtual machine has terminated unexpectedly during startup: NS_ERROR_FAILURE (0x80004005)

### ISSUE THREAD

**Issue by HeeZJee** [kubernetes/minikube#5031]
😄  minikube v1.3.0 on Ubuntu 18.04
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
E0810 01:45:24.503989   20359 start.go:723] StartHost: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

💣  Unable to start VM: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
https://github.com/hashicorp/vagrant/issues/8687 had some solutions.

My easiest suggestion would be to reinstall the latest VirtualBox and reboot.

**Comment by HeeZJee** [comment]
😄  minikube v1.3.0 on Ubuntu 18.04
⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0812 00:33:37.446629   25309 start.go:723] StartHost: create: creating: /usr/bin/VBoxManage storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium /home/heezjee/.minikube/machines/minikube/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/home/heezjee/.minikube/machines/minikube/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/home/heezjee/.minikube/machines/minikube/boot2docker.iso"

💣  Unable to start VM: create: creating: /usr/bin/VBoxManage storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium /home/heezjee/.minikube/machines/minikube/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/home/heezjee/.minikube/machines/minikube/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/home/heezjee/.minikube/machines/minikube/boot2docker.iso"


😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by HeeZJee** [comment]
now it's showing above error.
i tried it with virtuabox-6.0, 5.0, 4.0 and even i tried kvm2 Virtual Machine.
but still it isn't working locally.
its only working without with VM with below command.
`sudo minikube start --vm-driver=none`
I can't use it locally, still don't know why?
Please Sir! help me out.

**Comment by jukben** [comment]
The same issue for me

```
✓ minikube start
😄  minikube v1.3.0 on Darwin 10.14.5
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0813 15:26:38.791049    6105 start.go:723] StartHost: create: creating: /usr/local/bin/VBoxManage storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/jukben/.minikube/machines/minikube/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/Users/jukben/.minikube/machines/minikube/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 191 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/Users/jukben/.minikube/machines/minikube/boot2docker.iso"

💣  Unable to start VM: create: creating: /usr/local/bin/VBoxManage storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium /Users/jukben/.minikube/machines/minikube/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/Users/jukben/.minikube/machines/minikube/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 191 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/Users/jukben/.minikube/machines/minikube/boot2docker.iso"


😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
```

**Comment by tstromberg** [comment]
@jukben - The VERR_NOT_SUPPORTED issue is due to #4992 - please follow the resolution steps there. It seems like the ISO download was corrupted.

Marking as closed as the original issue was resolved.
