### ISSUE TITLE
Inconsistant behaviour of 'minikube profile'

### ISSUE THREAD

**Issue by sakshamkhanna** [kubernetes/minikube#5044]
`minikube profile` shows inconsistent behaviour in the following scenarios

### 1. After deleting .minikube/ and .kube/ (purging all profiles)
```
$ minikube profile
* minikube
```
```
$ minikube profile list
* No minikube profile was found. you could create one using: `minikube start`
```
```
$ minikube status
host:
kubelet:
apiserver:
kubectl:
```
```
$ minikube stop
! "minikube" VM does not exist, nothing to stop
```
```
$ minikube delete
! "minikube" cluster does not exist
* The "minikube" cluster has been deleted.
```

### 2. After creating (but not starting) profile p1
```
$ minikube profile p1
* minikube profile was successfully set to p1
```
```
$ minikube profile
* p1
```
```
$ minikube profile list
* No minikube profile was found. you could create one using: `minikube start`
```
```
$ minikube status
host:
kubelet:
apiserver:
kubectl:
```

### 3. After starting profile p1
```
$ minikube start
* [p1] minikube v1.3.0 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Downloading VM boot image ...
    minikube-v1.3.0.iso.sha256: 65 B / 65 B [=====================] 100.00% 0s
    minikube-v1.3.0.iso: 131.07 MiB / 131.07 MiB [================] 100.00% 4s
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
* Downloading kubeadm v1.15.2
* Downloading kubelet v1.15.2
* Pulling images ...
* Launching Kubernetes ...
* Waiting for: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "p1"
```
```
$ minikube profile
* p1
```
```
$ minikube profile list
|---------|------------|----------------|-----------|--------------------|
| Profile | VM Driver  |     NodeIP     | Node Port | Kubernetes Version |
|---------|------------|----------------|-----------|--------------------|
| p1      | virtualbox | 192.168.99.110 |      8443 | v1.15.2            |
|---------|------------|----------------|-----------|--------------------|
```
```
$ minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.110
```

### 4. After stopping profile p1
```
$ minikube stop
* Stopping "p1" in virtualbox ...
* "p1" stopped.
```
```
$ minikube profile
* p1
```
```
$ minikube profile list
|---------|------------|----------------|-----------|--------------------|
| Profile | VM Driver  |     NodeIP     | Node Port | Kubernetes Version |
|---------|------------|----------------|-----------|--------------------|
| p1      | virtualbox | 192.168.99.110 |      8443 | v1.15.2            |
|---------|------------|----------------|-----------|--------------------|
```
```
$ minikube status
host: Stopped
kubelet:
apiserver:
kubectl:
profile: p1
```

### 5. After deleting profile p1
```
$ minikube delete
! "p1" cluster does not exist
* The "p1" cluster has been deleted.
```
```
$ minikube profile
* minikube
```
```
$ minikube profile list
* No minikube profile was found. you could create one using: `minikube start`
```

### `minikube profile`
At first glance, the trigger for writing a new profile to disk seems to be when the profile is started with `minikube start` rather than when the profile is created be `minikube profile p1`

What this results in is inconsistent outputs between `minikube profile` and `minikube profile list`
* Profile `p1` is created but not started. `minikube profile` shows `p1` but `minikube profile list` doesn't
* In absence of all profiles, `minikube profile` shows `minikube` but `minikube status` and `minikube profile list` don't show anything
* After stopping a profile p1 by `minikube stop`, it shows up in `minikubbe profile list` while a profile that hasn't been started even once, does not.

This is a bit cofusing for someone who hasn't spent time trying to figure out why this behaviour occurs

### `minikube delete`
Also, `minikube delete` command's output is self-contradictory

## Expected Resolution
* Profiles should start appearing in `minikube profile list` as soon as they are created, regardless of whether they have been started or not. Maybe we can have an indicator of profiles that are running vs profiles that aren't in `minikube profile list`
OR
`minikube profile list` should display clearly that it is listing only those profiles that have been started at least once

* `minikube delete`'s output should me clearer

 ## Environment:
* OS: 
```
windows amd64
```
* minikube
```
$ minikube version
minikube version: v1.3.0
commit: 43969594266d77b555a207b0f3e9b3fa1dc92b1f
```

**Comment by tstromberg** [comment]
@medyagh might have more insight here.

**Comment by medyagh** [comment]
Thank you so much for creating this issue ! this seems like we need to make an empty dir folder once user sets the minikube profile to the one that doesn't exists

**Comment by medyagh** [comment]
@sakshamkhanna I believe this issue has has been solved by this PR . 
https://github.com/kubernetes/minikube/pull/5068

please feel free to re-open this issue if that is not the case !
