### ISSUE TITLE
rkt is not supported !

### ISSUE THREAD

**Issue by MrMic** [kubernetes/minikube#5047]
minikube start \
    --network-plugin=cni \
    --enable-default-cni \
    --container-runtime=rkt
😄  minikube v1.3.0 on Darwin 10.14.6

💣  Failed to generate config: unknown runtime type: "rkt"

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

============ 8< ----------------------- >8==============
minikube  version
minikube version: v1.3.0
commit: 43969594266d77b555a207b0f3e9b3fa1dc92b1f

Thanks for fixing that.
Any help would be welcome.
Rgds,

**Comment by afbjorklund** [comment]
Support for rkt has been removed, in later versions of minikube (and Kubernetes). Was it needed for something special, not covered by the available runtimes ?

**Comment by MrMic** [comment]
In fact, I just to give it a  Try.

**Comment by afbjorklund** [comment]
Maybe it needs a notice, for a while

**Comment by tstromberg** [comment]
Sorry :( rkt support was dropped before minikube v1.0, and doesn't appear in the minikube docs any more.

**Comment by afbjorklund** [comment]
These docs mention rkt:
https://kubernetes.io/docs/setup/learning-environment/minikube/#starting-a-cluster-on-alternative-container-runtimes
