### ISSUE TITLE
Getting started page on website gives 404

### ISSUE THREAD

**Issue by gromag** [kubernetes/minikube#5054]
**The exact command to reproduce the issue**:

The following link returns a 404 https://minikube.sigs.k8s.io/docs/getting-started/
I would expect installation instructions instead as per link under the Installation section of the README page of this repo.

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by RA489** [comment]
@gromag https://minikube.sigs.k8s.io/docs/start/

**Comment by tstromberg** [comment]
Fixed. Thank you for reporting this!
