### ISSUE TITLE
 Error restarting cluster: waiting for apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by manukoli1986** [kubernetes/minikube#5059]
Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
* Problems detected in "kube-addon-manager":
  - error: Wunable to recognize "STDIN": Get https://RlN: == Error getting default service account, retry in 0.5 second ==
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by manukoli1986** [comment]
I have fixed the problem after reinstalling.

Regards
Mayank

**Comment by manukoli1986** [comment]
I have fixed the problem after reinstalling.
