### ISSUE TITLE
kvm flaky test: start delete : "Domain not found"

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5061]
as seen in this full loig: https://storage.googleapis.com/minikube-builds/logs/5003/KVM_Linux.txt for testGvisorRestart 
https://github.com/kubernetes/minikube/blob/master/test/integration/containerd_test.go#L43-L88

The error message:

```
 cluster.go:117] Machine state:  Error
        E0809 17:42:46.026979    7554 start.go:757] StartHost: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'TestContainerd'')

I0809 17:42:46.027051    7554 utils.go:127] non-retriable error: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'TestContainerd'')

W0809 17:42:46.027130    7554 exit.go:99] Unable to start VM: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'TestContainerd'')

X Unable to start VM: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'TestContainerd'')
```

### More detailed log  :

<details>
<pre>

--- FAIL: TestContainerd (0.00s)
    --- FAIL: TestContainerd/GvisorRestart (1504.14s)
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
            * Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
            Running pre-create checks...
            Creating machine...
            (TestContainerd) Creating KVM machine...
            (TestContainerd) KVM machine creation complete!
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        minikube_runner.go:140: temporary error: running command: -p=TestContainerd start --vm-driver=kvm2  --wait=false --v=10 --logtostderr  --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock . Output: 
            * [TestContainerd] minikube v1.3.0 on Debian 9.9
        containerd_test.go:53: failed to start minikube (for profile TestContainerd) failed : exit status 70
            stdout: * [TestContainerd] minikube v1.3.0 on Debian 9.9
             
            stderr: I0809 17:42:45.831947    7554 notify.go:124] Checking for updates...
            I0809 17:42:45.954734    7554 start.go:225] hostinfo: {"hostname":"kvm-integration-slave4","uptime":932941,"bootTime":1564464824,"procs":205,"os":"linux","platform":"debian","platformFamily":"debian","platformVersion":"9.9","kernelVersion":"4.9.0-9-amd64","virtualizationSystem":"kvm","virtualizationRole":"host","hostid":"ae41e7f6-8b8e-4d40-b77d-1ebb5a2d5fdb"}
            I0809 17:42:45.955397    7554 start.go:235] virtualization: kvm host
            I0809 17:42:45.988334    7554 downloader.go:59] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso
            I0809 17:42:45.988458    7554 start.go:928] Saving config:
            {
                "MachineConfig": {
                    "KeepContext": false,
                    "EmbedCerts": false,
                    "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso",
                    "Memory": 2000,
                    "CPUs": 2,
                    "DiskSize": 20000,
                    "VMDriver": "kvm2",
                    "ContainerRuntime": "containerd",
                    "HyperkitVpnKitSock": "",
                    "HyperkitVSockPorts": [],
                    "DockerEnv": null,
                    "InsecureRegistry": null,
                    "RegistryMirror": null,
                    "HostOnlyCIDR": "192.168.99.1/24",
                    "HypervVirtualSwitch": "",
                    "KVMNetwork": "default",
                    "KVMQemuURI": "qemu:///system",
                    "KVMGPU": false,
                    "KVMHidden": false,
                    "DockerOpt": [
                        "containerd=/var/run/containerd/containerd.sock"
                    ],
                    "DisableDriverMounts": false,
                    "NFSShare": [],
                    "NFSSharesRoot": "/nfsshares",
                    "UUID": "",
                    "NoVTXCheck": false,
                    "DNSProxy": false,
                    "HostDNSResolver": true
                },
                "KubernetesConfig": {
                    "KubernetesVersion": "v1.15.2",
                    "NodeIP": "",
                    "NodePort": 8443,
                    "NodeName": "minikube",
                    "APIServerName": "minikubeCA",
                    "APIServerNames": null,
                    "APIServerIPs": null,
                    "DNSDomain": "cluster.local",
                    "ContainerRuntime": "containerd",
                    "CRISocket": "",
                    "NetworkPlugin": "cni",
                    "FeatureGates": "",
                    "ServiceCIDR": "10.96.0.0/12",
                    "ImageRepository": "",
                    "ExtraOptions": null,
                    "ShouldLoadCachedImages": true,
                    "EnableDefaultCNI": true
                }
            }
            I0809 17:42:45.988719    7554 cluster.go:98] Skipping create...Using existing machine configuration
            I0809 17:42:45.988791    7554 cache_images.go:286] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1
            I0809 17:42:45.988786    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
            I0809 17:42:45.988798    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.15.2 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.15.2
            I0809 17:42:45.988855    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.15.2 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.15.2
            I0809 17:42:45.988857    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
            I0809 17:42:45.988868    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.15.2 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.15.2
            I0809 17:42:45.988848    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.15.2 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.15.2
            I0809 17:42:45.988879    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
            I0809 17:42:45.988887    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
            I0809 17:42:45.988877    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/coredns_1.3.1
            I0809 17:42:45.988885    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
            I0809 17:42:45.989411    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/pause:3.1 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/pause_3.1
            I0809 17:42:45.989391    7554 cache_images.go:286] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at /home/jenkins/minikube-integration/linux-amd64-kvm2-5003-29686-f0f4352bb1ed8a24f003d5ccc709cad716e125f4/.minikube/cache/images/k8s.gcr.io/etcd_3.3.10
            I0809 17:42:45.989497    7554 cache_images.go:83] Successfully cached all images.
            Found binary path at /home/jenkins/workspace/KVM_Linux_integration/out/docker-machine-driver-kvm2
            Launching plugin server for driver kvm2
            Plugin server listening at address 127.0.0.1:38907
            () Calling .GetVersion
            Using API Version  1
            () Calling .SetConfigRaw
            () Calling .GetMachineName
            (TestContainerd) Calling .DriverName
            (TestContainerd) Calling .GetState
            I0809 17:42:46.026888    7554 cluster.go:117] Machine state:  Error
            E0809 17:42:46.026979    7554 start.go:757] StartHost: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'TestContainerd'')
            I0809 17:42:46.027051    7554 utils.go:127] non-retriable error: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'TestContainerd'')
            W0809 17:42:46.027130    7554 exit.go:99] Unable to start VM: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'TestContainerd'')
            * 
            X Unable to start VM: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'TestContainerd'')
            * 
            * Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
              - https://github.com/kubernetes/minikube/issues/new/choose
FAIL
</pre>
</details>

**Comment by medyagh** [comment]
CC: @josedonizetti

**Comment by josedonizetti** [comment]
I'm investigating this.

**Comment by tstromberg** [comment]
Haven't seen lately.
