### ISSUE TITLE
proxy: Get https://storage.googleapis.com/....iso.sha256: Bad Request

### ISSUE THREAD

**Issue by pbalane** [kubernetes/minikube#5076]
**The exact command to reproduce the issue**:
Steps to Reproduce
1) Installed minikube
2) Executed minikube start command
3) resulted in below error
4) SET HTTP_PROXY   HTTPS_PROXY  AND  NO_PROXY

**The full output of the command that failed**:<details>
C:\Installables\kubernatisminikube\Minikube>minikube.exe start
* minikube v1.3.1 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Downloading VM boot image ...
*
X Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso.sha256: Bad Request
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\Installables\kubernatisminikube\Minikube>

</details>

**The output of the `minikube logs` command**:<details>

C:\Installables\kubernatisminikube\Minikube>minikube.exe logs
*
X Error getting config: CreateFile C:\Users\FA46AK\.minikube\profiles\minikube\config.json: The system cannot find the path specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:

Windows 10

**Comment by tstromberg** [comment]
It appears that the HTTPS_PROXY you have selected is rejecting the HTTP request. Are you sure you have the correct value for it?

**Comment by tstromberg** [comment]
Closing, as minikube appears to be pointing to a proxy which can't access storage.googleapis.com.
