### ISSUE TITLE
site issues on mobile: screenshot aspect ratio & font sizes

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5078]
Mentioned by @medyagh 

![Screenshot_20190814-090956](https://user-images.githubusercontent.com/101424/63037323-bfce5e00-be73-11e9-9380-ca3b0876f2d9.png)

**Comment by pop** [comment]
I can take this if you want.

**Comment by tstromberg** [comment]
Yes please! That would be wonderful :)

**Comment by afbjorklund** [comment]
Might want to update to 1.4.0 too ?

I made a nice animated B/W version for my demo (mostly as a fallback)

Made it run in 30 secs, by speed up...

**Comment by medyagh** [comment]
@pop its yours now !

**Comment by nanikjava** [comment]
Interested to take over this if the original assignee is not working on this ?

**Comment by pop** [comment]
@nanikjava sure! I pretty easily got the screenshot aspect ratio fixed, but the minikube logo had a bad aspect ratio that I was not able to fix, so unfortunately I only have a partial fix for this problem.

@medyagh feel free to assign this to @nanikjava. I don't think I have time to troubleshoot the logo aspect ratio any time soon.

**Comment by nanikjava** [comment]
Following are the screenshots applying the fix

_**Mobile (Android)**_

![device-2019-10-09-194501](https://user-images.githubusercontent.com/883406/66465897-742fdd80-eacd-11e9-9136-38608d38df95.png)

_**Web Firefox**_
![Screenshot from 2019-10-09 19-44-34](https://user-images.githubusercontent.com/883406/66465898-742fdd80-eacd-11e9-83c7-f1098ca32224.png)

**Comment by nanikjava** [comment]
@medyagh @tstromberg  PR created https://github.com/kubernetes/minikube/pull/5575

**Comment by nanikjava** [comment]
To test and run locally use the following command from minikube root directory

 cd site && ../out/hugo/hugo serve --bind=<your_computer_ip> --baseURL=http://<your_computer_ip>  -p 8080   --disableFastRender   --navigateToChanged   --ignoreCache   --buildFuture 

Using the above command will allow your phone (assuming it's connecting to the same network as your computer) to access the minikube website -- http://<your_computer_ip>:8080
