### ISSUE TITLE
macOS: `brew install` should be `brew cask install`

### ISSUE THREAD

**Issue by yacn** [kubernetes/minikube#5081]
When following the installation guide for macOS, it says to install using `brew` with `brew install minikube`. However, `minikube` is cask now so the correct command is `brew cask install minikube`. Not a big issue since the failed command tells you what to try but seems like it might be worth updating.

#### `brew install minikube`

```
Error: No available formula with the name "minikube"
Found a cask named "minikube" instead. Try
  brew cask install minikube
```

**Comment by afbjorklund** [comment]
Basically "cask" is brew-speak for binary, for things that it cannot (or don't want to) build from source.

**Comment by medyagh** [comment]
This make a good first issue to fix the doc !

**Comment by Patil2099** [comment]
@yacn Can I work on this?
