### ISSUE TITLE
windows : kill command not working

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5084]
TestFunctional/group/Mounting

```
          fn_mount.go:59: Failed to kill mount command: TerminateProcess: Access is denied.
```
as seen in https://storage.googleapis.com/minikube-builds/logs/5082/Hyper-V_Windows.txt

the cmd.Kill() returns "Access is denied"

it seems to be a golang issue that Cmd.Process.Start() on Windows have wrong Pid  https://groups.google.com/forum/#!topic/Golang-Nuts/gWPT_BxWISg

and even people skip the test on windows ! https://go.googlesource.com/go/+/master/src/cmd/dist/test.go?autodive=0%2F#511

at fn_mount.go:59: `err := cmd.Process.Kill()`

It looks like cmd.Process is returning the incorrect PID.

**Comment by medyagh** [comment]
https://github.com/charlievieth/winutil/blob/e4ec236014ee4626b38c21ce200544f9d5ac45bf/winutil.go

**Comment by medyagh** [comment]
https://github.com/miaia/daemon/blob/569d5a85309dd8f0dd460782603f2a8ab658f9e9/daemon_windows.go

**Comment by tstromberg** [comment]
As it stands, I suspect this may miss the v1.4.0 release (Sep 16).

@sharifelgamal - did you have any new insights for this issue?

**Comment by sharifelgamal** [comment]
This was fixed with https://github.com/kubernetes/minikube/pull/5285
