### ISSUE TITLE
Due to multiple CVEs and fds leak, need to upgrade golang to 1.12.9

### ISSUE THREAD

**Issue by warmchang** [kubernetes/minikube#5087]
Due to multiple CVEs and fds leak, need to upgrade golang to 1.12.9

xref:
https://github.com/golang/go/issues/33405
https://github.com/golang/go/commit/047a326569a5d75c2f5c1fd49fccb4da623b038a
https://groups.google.com/forum/#!topic/golang-announce/65QixT3tcmg
https://github.com/golang/go/issues?q=milestone%3AGo1.12.9+label%3ACherryPickApproved
https://groups.google.com/forum/#!topic/golang-announce/oeMaeUnkvVE

**Comment by tstromberg** [comment]
@medyagh has some ideas on this.

**Comment by medyagh** [comment]
I am on it

**Comment by afbjorklund** [comment]
Also update build image to `k8s.gcr.io/kube-cross:v1.12.8-1`

**Comment by warmchang** [comment]
https://github.com/golang/go/issues/33424#issuecomment-521827711
https://github.com/kubernetes/kubernetes/issues/79912#issuecomment-521826756
https://github.com/golang/go/milestone/110?closed=1

go1.12.9 please. :smile:

**Comment by afbjorklund** [comment]
The title is misleading. Go 1.12.9 is **not** a security release, but a feature release (same as 1.12.8)
We should probably upgrade anyway, but.

**Comment by warmchang** [comment]
> The title is misleading. Go 1.12.9 is **not** a security release, but a feature release (same as 1.12.7)
> We should probably upgrade anyway, but.

Just list the features we care about:
`go1.12.9 = go1.12.8 + fds leak bug fixes = go1.12.7 + CVEs fixes + fds leak bug fixes`

minikube use go1.12.7 now, that's why bump to go1.12.9 will include all of these.

**Comment by afbjorklund** [comment]
Yes, sounds good.

**Comment by afbjorklund** [comment]
We should upgrade again (to 1.12.9) before the 1.4.0 release, when go1.12.9 is available everywhere.
