### ISSUE TITLE
Unable to start VM: start: exit status 1

### ISSUE THREAD

**Issue by vinhladn** [kubernetes/minikube#5088]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=7` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
