### ISSUE TITLE
Custom Addons docs should be more detailed

### ISSUE THREAD

**Issue by guibirow** [kubernetes/minikube#5091]
The [docs for custom addons](https://minikube.sigs.k8s.io/docs/tasks/addons/#custom-addons) should have more information how to setup the addons.

it simply states:

> If you would like to have minikube properly start/restart custom addons, place the addon(s) you wish to be launched with minikube in the .minikube/addons directory. Addons in this folder will be moved to the minikube VM and launched each time minikube is started/restarted.

But does not show how an Addon looks like, what is the composition of an addon and so on.

**Comment by tstromberg** [comment]
Agreed, this guide should link to https://minikube.sigs.k8s.io/docs/contributing/addons/

**Comment by guibirow** [comment]
Cool, I didn't see this one, can I submit the PR to link these guides?
