### ISSUE TITLE
Downgrade warning is unhelpful and confusing

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5097]
When a user wants to run against an older version of Kubernetes, but have already run `minikube start` with the default version, we show them the warning, and ignore their request:

`Kubernetes downgrade is not supported, will continue to use v1.15.2`

Instead, we should exit with a compatibility error that tells the user exactly what is going on and how to workaround it. Something like:

```
Error: You have selected version v1.12.0, but your existing "minikube" cluster is
running version v1.15.2. Non-destructive downgrades are not supported, but you
can proceed by selecting one of these options:

* Run `minikube delete -p minikube` to delete the existing cluster
* Run `minikube start -p <new name>` to start a new cluster with a different name
* Run `minikube start --kubernetes-version=v1.15.2` or newer to continue using
this cluster.
```

Thoughts?

**Comment by tstromberg** [comment]
If anyone wants to implement this, here's where to start:

https://github.com/kubernetes/minikube/blob/21256ccb9de7d0dc08afc893ff122837e98a736b/cmd/minikube/cmd/start.go#L821

Using `exit.WithCode(exit.Config, "message")` seems reasonable.

**Comment by Doqnach** [comment]
I would make a small modification there:

```
Error: You have selected version {{NEW_OLDER_VERSION:v1.12.0}}, but your existing cluster for profile "{{CURRENT_PROFILE:minikube}}" is running version {{CURRENT_NEWER_VERSION:v1.15.2}}. Non-destructive downgrades are not supported, but you can proceed by performing one of the following options:

* Run `minikube start [-p {{CURRENT_PROFILE}}] --kubernetes-version={{CURRENT_NEWER_VERSION:v1.15.2}}` or newer to continue using this cluster
* Run `minikube start -p <new name> --kubernetes-version={{NEW_OLDER_VERSION:v1.12.0}}` to start a new cluster with a different name
* Run `minikube delete -p {{CURRENT_PROFILE}}` to delete the existing cluster first, and `minikube start [-p {{CURRENT_PROFILE}}] --kubernetes-version={{NEW_OLDER_VERSION:v1.12.0}}` to start a new cluster under the same name
```

Where `[-p {{CURRENT_PROFILE}}]` would only have to appear if the current profile was not the default "minikube".

**Comment by phillipahereza** [comment]
@tstromberg can I work on this?
