### ISSUE TITLE
Adding third-party packages to the ISO without a Makefile

### ISSUE THREAD

**Issue by frankmeten** [kubernetes/minikube#5098]
I want add a third party package -mlflow ( https://github.com/mlflow/mlflow/blob/master/CONTRIBUTING.rst ) to minikube. 
According section "Adding third-party packages" in https://minikube.sigs.k8s.io/docs/contributing/iso/, the package should have a makefile exists.
But mlflow has no makefile, so the problem is, generally speak, how could we Adding third-party packages which is non-C language such
as Java, Python, Ruby etc. language based that no makefile exists.

**Comment by frankmeten** [comment]
and conda https://conda.io/projects/conda/en/latest/user-guide/install/index.html

**Comment by tstromberg** [comment]
I'm curious, what is the use case you are trying to address by adding these packages into the ISO?

The other packages are prerequisites for Kubernetes, VM helpers, or system debugging tools. It's not typical for users to use `minikube ssh` for things other than debugging: other tools are typically deployed within Docker containers.

**Comment by frankmeten** [comment]
> I'm curious, what is the use case you are trying to address by adding these packages into the ISO?
> 
> The other packages are prerequisites for Kubernetes, VM helpers, or system debugging tools. It's not typical for users to use `minikube ssh` for things other than debugging: other tools are typically deployed within Docker containers.

My ultimate goal is to generate a .ISO or .VHDX(Windows HyperV) file that the tinier the better, and encapuslate kubernets, machine learning packages(conda mlflow tensorflow) into it. With the iso or vhdx file, multiple VM can be created easily and fastly. 

I have read Chapter 17
Adding new packages to Buildroot of
https://buildroot.org/downloads/manual/manual.pdf, it just descibes how add package form source code. Could I add package that I only have binary format media?

**Comment by tstromberg** [comment]
Hey @frankmeten 

https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/vbox-guest/vbox-guest.mk is an example where we download a binary to put into the minikube ISO. 

To add a third-party package to the ISO, we do currently require a Makefile to download the binary and copy it to the appropriate place. If you plan to build a custom minikube ISO for Machine Learning, I would suggest pursuing a similar course. 

Alternatively, you may find it easier to build a standard ISO usable in Hyper-V or other virtualization systems that includes your tools, and runs minikube with the none driver to avoid issues with nested virtualization: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

Hope this helps!

**Comment by tstromberg** [comment]
Closing because at least for now, Makefiles are required for buildroot. 

It's still possible to copy files directly into the ISO filesystem.
