### ISSUE TITLE
ssh onto node

### ISSUE THREAD

**Issue by shmish111** [kubernetes/minikube#51]
An issue with documentation I guess, how can I ssh onto the machine that minikube starts?

This is an issue when using private docker repos for example as I need to login to docker hub on the node that minikube will pull images on.

**Comment by shmish111** [comment]
Closing this as I managed to login using docker@host with password tcuser

**Comment by dlorenc** [comment]
I'll reopen this until we get it documented. In most cases users shouldn't need SSH, but it's one of those things where when you need it, you *really* need it.
