### ISSUE TITLE
host-only cidr conflicts with the network address of a host interface

### ISSUE THREAD

**Issue by szymonpk** [kubernetes/minikube#510]
**Minikube version**
v0.8.0

**Environment**:
- **OS**: Gentoo
- **VM Driver**: virtualbox
- **Docker version**: 1.12.0
- **VirtualBox**: 5.0.26

**What happened**:
I'm trying to run `minikube start --cpus=2 --memory=4096`
```
Starting local Kubernetes cluster...
E0823 12:26:56.482798   11817 start.go:83] Error starting host: Error creating. Error creating machine: Error in driver during machine creation: host-only cidr conflicts with the network address of a host interface. Retrying.
E0823 12:31:57.568838   11817 start.go:83] Error starting host: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded. Retrying.
```
**What you expected to happen**:
I would like to see sth like this:
```
Starting local Kubernetes cluster...
Kubernetes is available at https://192.168.99.100:8443.
Kubectl is now configured to use the cluster.
```

**How to reproduce it**:
It happens always on my Linux machine.

**Anything else do we need to know**:
Output of `ip a`, `wlp1s0` is my primary network interface, I know issue is in [this](https://github.com/kubernetes/minikube/blob/d74ce773cf9e6152c3bbe3bdde304e159f27ba44/vendor/github.com/docker/machine/drivers/virtualbox/network.go#L383) function, however I'm not sure host ip interferes with any interface ip except `vboxnet0` which is virtualbox interface.

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 brd 127.255.255.255 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: wlp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a4:34:d9:8c:e2:f9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.11.26/24 brd 192.168.11.255 scope global wlp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::5c1f:5481:44b8:580b/64 scope link 
       valid_lft forever preferred_lft forever
3: enp0s31f6: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc pfifo_fast state DOWN group default qlen 1000
    link/ether f8:ca:b8:4d:5e:e9 brd ff:ff:ff:ff:ff:ff
6: vboxnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.1/24 brd 192.168.99.255 scope global vboxnet0
       valid_lft forever preferred_lft forever
    inet 192.168.99.100/24 brd 192.168.99.255 scope global secondary vboxnet0
       valid_lft forever preferred_lft forever
    inet6 fe80::aca7:69d4:eddf:a9b9/64 scope link 
       valid_lft forever preferred_lft forever
```

**Comment by szymonpk** [comment]
It works with `--host-only-cidr="192.168.99.1/26"` which is half of default network.

**Comment by duelle** [comment]
@szymonpk Where do you add the `--host-only-cidr="192.168.99.1/26"` parameter to make it work?

**Comment by jimmidyson** [comment]
@duelle It's a flag to `minishift start --host-only-cidr="192.168.99.1/26"`

**Comment by duelle** [comment]
Unfortunately this seems to be no workaround for me. 
`minishift start --host-only-cidr="192.168.99.1/26"` 
also fails with
`Error starting host: Error starting stopped host: host-only cidr conflicts with the network address of a host interface.`

**Comment by habutre** [comment]
Same error here. I've tried `--host-only-cidr` flag also without success

**Comment by dlorenc** [comment]
Looks like we might need to pick up this fix from upstream: https://github.com/docker/machine/pull/3597/files

**Comment by habutre** [comment]
building minikube from `HEAD` works like a charm!
Thx everyone involved.

**Comment by kalyanamp** [comment]
minikube start --host-only-cidr="192.168.99.1/26"

**Comment by tofanelli** [comment]
Hey guys... how this issue has been going?

I just installed Docker on a fresh Windows 8.1 x64 installation (2 weeks old) and I'm getting this error

![image](https://user-images.githubusercontent.com/5512922/44242285-2193b380-a19f-11e8-972b-7abdfc84ea0f.png)

Steps done so far
- uninstalled and installed again
- restarted the machine
- Tried to run on a elevated prompt start.sh
- changed "HostOnlyCIDR": to my ip address
none of them worked

Using latest Docker Toolbox version with windows 8.1 x64 fully updated.

**Comment by szymonpk** [comment]
`--host-only-cidr` should not include network/IP address of any of your interfaces

**Comment by tofanelli** [comment]
@szymonpk ... yes, i wasn't using my network range... my network is 10.0.0.0/8 and I used the same on Docker Docs, 192.168.99.1/24, and many others and none of them worked... =\
