### ISSUE TITLE
Update notification has wrong URL

### ISSUE THREAD

**Issue by shouptech** [kubernetes/minikube#5101]
The upgrade notification displays a URL like this: 
https://github.com/kubernetes/minikube/releases/tag/v/1.3.1
The correct URL should be: 
https://github.com/kubernetes/minikube/releases/tag/v1.3.1

There's an extra slash between v and 1.3

**The exact command to reproduce the issue**:
This happens when my shell (zsh) loads the tab completion.

**The full output of the command that failed**:<details>
  minikube 1.3.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.3.1

</details>

**The output of the `minikube logs` command**:<details>
N/A

</details>

**The operating system version**:
Linux <> 5.0.0-21-generic #22+system76-Ubuntu SMP Tue Jul 16 19:57:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tstromberg** [comment]
Hum. How on earth did that happen?

Spoiler alert: I broke it in a refactor:
https://github.com/kubernetes/minikube/commit/3d7c657eaf5b408a7776c0221ca75b04e9d77ec9

**Comment by tstromberg** [comment]
Thank you for opening an issue rather than just letting this bug sit and aggravate future users =)
