### ISSUE TITLE
Add branding to distribution

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#5105]
Currently we ship the distribution with an unmodified `/etc/os-release` like so:

```Makefile
	( \
		echo "NAME=Buildroot"; \
		echo "VERSION=$(BR2_VERSION_FULL)"; \
		echo "ID=buildroot"; \
		echo "VERSION_ID=$(BR2_VERSION)"; \
		echo "PRETTY_NAME=\"Buildroot $(BR2_VERSION)\"" \
	) >  $(TARGET_DIR)/usr/lib/os-release
```

But we do our own configuration and modification, to the basic Buildroot system.

The libmachine upstream boot2docker.iso does this, and looks something like:

```console
docker@default:~$ cat /etc/os-release 
NAME=Boot2Docker
VERSION=19.03.1
ID=boot2docker
ID_LIKE=tcl
VERSION_ID=19.03.1
PRETTY_NAME="Boot2Docker 19.03.1 (TCL 10.1)"
ANSI_COLOR="1;34"
HOME_URL="https://github.com/boot2docker/boot2docker"
SUPPORT_URL="https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/"
BUG_REPORT_URL="https://github.com/boot2docker/boot2docker/issues"
```

The original distribution (in our case "buildroot") ends up under "ID_LIKE".

Also the Linux version gets a suffix, to indicate custom kernel configuration.

```console
docker@default:~$ uname -r
4.14.134-boot2docker
```

----

We could do our own branding here, and advertise minikube and ISO version ?

```
NAME=minikube
VERSION=1.3.0
ID=minikube
ID_LIKE=buildroot
VERSION_ID=1.3.0
PRETTY_NAME="minikube 1.3.0 (Buildroot 2018.05.3)"
HOME_URL="https://github.com/kubernetes/minikube"
```

https://www.freedesktop.org/software/systemd/man/os-release.html

**Comment by priyawadhwa** [comment]
If anybody is interested in working on this issue, we would love some help. Feel free to assign yourself by commenting `/assign` and I'll be happy to review any PRs.

**Comment by afbjorklund** [comment]
We can consider doing this for Buildroot 2020.02 LTS, it's not a big **code** change - just a decision

**Comment by afbjorklund** [comment]
I don't think we will do this, but could consider it for #11056

**Comment by sharifelgamal** [comment]
I'm actually in favor of this, I would approve a PR that makes that change.
