### ISSUE TITLE
install minicube on ubuntu(a vm on vmware)

### ISSUE THREAD

**Issue by rajeshramt** [kubernetes/minikube#5111]
I have created a ubuntu16 server on my vmware server and trying to install minicube in it. But I'm getting the following error 

minikube start
😄  minikube v1.3.1 on Ubuntu 16.04
⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
E0817 11:44:55.825972    2146 start.go:723] StartHost: start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.183069 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

💣  Unable to start VM
❌  Error: [VBOX_VERR_VMX_NO_VMX] start: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.183069 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
💡  Suggestion: Please check your BIOS, and ensure that you are running without HyperV or other nested virtualization that may interfere
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/1994

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by afbjorklund** [comment]
If you really want to run a VM in a VM (nested virtualization), changes are you need to do some more VMware configuration first. Otherwise you could create two VMs: one for Ubuntu, one for minikube ?

**Comment by tstromberg** [comment]
For nested VM configurations, consider using the none driver: 

https://minikube.sigs.k8s.io/docs/reference/drivers/none/

There isn't much else we can do otherwise to make VMware compatible with VirtualBox: https://superuser.com/questions/1147113/running-virtual-box-vm-inside-vmware-vm-windows-server-2008

**Comment by tstromberg** [comment]
FWIW, I'm also disappointed that minikube (gopsutil) didn't detect that it was running within a VMware VM here: otherwise we could have had it automatically suggest the none driver.

**Comment by tstromberg** [comment]
One possibility: improve the solution message to mention the none driver, if run on Linux.

**Comment by rajeshramt** [comment]
thanks guys.... let me check your suggestions, I'll let you know the status soon :)
