### ISSUE TITLE
Cannot start minikube on Mac OS 10.14.4

### ISSUE THREAD

**Issue by jxxcarlson** [kubernetes/minikube#5113]
**minikube start**:

**The full output of the command that failed**:<details>

😄  minikube v1.3.1 on Darwin 10.14.4
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0817 17:35:51.210295    1607 start.go:723] StartHost: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

💣  Unable to start VM
❌  Error: [VBOX_HOST_ADAPTER] create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
💡  Suggestion: Reboot to complete VirtualBox installation, and verify that VirtualBox is not blocked by your system
📘  Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3614
    ▪ https://github.com/kubernetes/minikube/issues/4222

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
$ minikube logs

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**: Mac OS  10.14.4

**Comment by medyagh** [comment]
@jxxcarlson  thanks for taking the time to create this issue, I am curious, have you already tried the suggestion in the output ?

```
Suggestion: Reboot to complete VirtualBox installation, and verify that VirtualBox is not blocked by your system
📘 Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start
```

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
