### ISSUE TITLE
Update notice disable suggestion breaks eval $(docker-env)

### ISSUE THREAD

**Issue by Eelis** [kubernetes/minikube#5114]
**The exact command to reproduce the issue**:

    $ rm ~/.minikube/last_update_check
    $ eval $(minikube docker-env)   
    ⚠️  minikube 1.3.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.3.1
    zsh: command not found: 💡

The problem is that `minikube docker-env` prints the

    💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

notification to stdout.

**Comment by medyagh** [comment]
I am curious, does it break only once or it will break again and again ?

**Comment by Eelis** [comment]
Only once. After the first time, the file exists and `minikube docker-env` no longer outputs any announcements, and `eval $(minikube docker-env)` succeeds.

**Comment by afbjorklund** [comment]
I think it will "break" every 24 hours, as per the `ReminderWaitPeriodInHours` ?

The thing that _really_ annoyed me before was when you tried to disable it:

```console
$ minikube config set WantUpdateNotification false
⚠️  There is a newer version of minikube available (v1.3.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.3.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
```
Which was solved by `2>/dev/null` (and some swearing), "good enough"

```console
$ minikube config set WantUpdateNotification false
⚠️  minikube 1.3.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.3.1
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'
```

But I think printing the advertisement to stderr will be enough for a fix to this.

```go
		out.ErrT(out.WarningType, `minikube {{.version}} is available! Download it: {{.url}}`, out.V{"version": latestVersion, "url": url})
		out.T(out.Tip, "To disable this notice, run: 'minikube config set WantUpdateNotification false'")
```

i.e. use `ErrT` also for the tip ?

**Comment by tstromberg** [comment]
Yes, this should be fixed. Anyone game for doing so?

- This warning should go to stderr. I'd argue that all warnings should.
- This warning should only be displayed during `minikube start` (which isn't designed to be parsed)

**Comment by Zyqsempai** [comment]
I will take this one.

**Comment by RA489** [comment]
@Zyqsempai Any update on this?

**Comment by Zyqsempai** [comment]
@RA489 I will open a PR today

**Comment by Eelis** [comment]
Very nice, thanks for this!
