### ISSUE TITLE
uninstaller should be able to delete VM's

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#5118]
As of now, running the uninstaller of `minikube` just removes the folder in which `minikube` was installed. This should have the capability to do a clean uninstall of the minikube. Probably have an option to do a `Clean Uninstall` in which it removes the following -

1. Stops & deletes the Virtual machines created by Minikube (Possibly for all the profiles available)
2. Removes the `.minikube` folder in "C:\Users\USER_NAME"

EDIT -- I believe this should apply for the chocolatey installer as well.

**Comment by tstromberg** [comment]
Sounds like a great idea!

**Comment by blueelvis** [comment]
That's why we provide the user with the option to do a clean uninstall as well :)

I have seen that option with a lot of uninstallers where they ask if you would like to remove the data or not.

**Comment by tstromberg** [comment]
It seems reasonable to have as an option.

**Comment by tstromberg** [comment]
@blueelvis - was this ever fixed on Windows? I feel like I saw a PR for this.
