### ISSUE TITLE
Minikube not starting after using 

### ISSUE THREAD

**Issue by rehanrafiqq** [kubernetes/minikube#5120]
As suggested I have used the following command 

docker ps -A
sudo journalctl -u docker -n 500 

but still Minikube did not start with 
minikube start --vm-driver=virtualbox

![Screenshot from 2019-08-18 03-42-07](https://user-images.githubusercontent.com/53755061/63218013-58155d00-c16a-11e9-9dc8-cb67072035dc.png)
**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by medyagh** [comment]
it seems like you first tried to run minikube in none driver and then with virtualbox ?

do you mind trying to see if this solves the problem:

minikube delete
minikube start

**Comment by afbjorklund** [comment]
Same as #5099. Please use text rather than screenshots, thanks!
