### ISSUE TITLE
Site: add link to external tutorials based on minikube 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5126]
There are many good blogs posts and tutorials that are based on minikube.

@afbjorklund mentioned this in the slack channel: https://quarkus.io/guides/kubernetes-guide.html#deploying-the-application-in-kubernetes

I create this issue to collect most interesting tutorials, and I would accept PRs that add links to these tutorials to somewhere in the site.

**Comment by RA489** [comment]
@medyagh we can add the link  either https://minikube.sigs.k8s.io/docs/examples/ or somewhere in Tutorial section(https://minikube.sigs.k8s.io/docs/tutorials/) wdyt?

**Comment by medyagh** [comment]
we could have a new page under tutorials called
`External Tutorials`

**Comment by medyagh** [comment]
@RA489 any updates?

**Comment by RA489** [comment]
@medyagh Thanks for your feedback i will file a PR  keeping new page under tutorials asap.
