### ISSUE TITLE
Add automatic bugreporting/bugtracking

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#513]
When using looking at docker-machine I noticed they used bugsnag for automatic bug reporting/monitoring.  I just wanted to get thoughts/opinions on whether we should do this and if so how to go about it.  

Also could potentially be a minikube command that sends stored logs or has a prompt to fill in by user. (`minikube feedback/bugsend`)

**Comment by dlorenc** [comment]
Makes sense. There are a few options to checkout: bugsnag, sentry, raygun

**Comment by dlorenc** [comment]
Also: https://cloud.google.com/error-reporting/

**Comment by steren** [comment]
Hi, I am Google Stackdriver Error Reporting Product Manager.
I encourage you to take a look at our [report API](https://cloud.google.com/error-reporting/reference/rest/v1beta1/projects.events/report) which can be called using a simple POST request and API key. 
Stackdriver Error Reporting supports Go stack traces

To better understand how errors are grouped, you can read https://cloud.google.com/error-reporting/docs/grouping.

**Comment by dlorenc** [comment]
Thanks @steren! Do you have any docs on how the `message` field is parsed? It seems that not all plain text gets handled correctly, messages have to be stack traces. It would be nice to know how that parsing works.

**Comment by steren** [comment]
My last link might answer this: https://cloud.google.com/error-reporting/docs/grouping#grouping

If the message does not contain a stack trace, then the grouping is performed using the first message tokens and context.reportLocation.

**Comment by dlorenc** [comment]
ah, great! I got it to work. Initially I tried sending reports using only the `message` field, and the requests were successful (response code 200), but none of the events showed up in the dashboard. Setting the `context.reportLocation` information works.

**Comment by aaron-prindle** [comment]
This was added with #533 and #582.  Closing.
