### ISSUE TITLE
Cannot run "sudo minikube start --vm-driver=none" Ubuntu 18.04

### ISSUE THREAD

**Issue by mytuanZ** [kubernetes/minikube#5134]
**The exact command to reproduce the issue**: sudo minikube start --vm-driver=none

**The full output of the command that failed**:<details>
* minikube v1.3.1 on Ubuntu 18.04
* Running on localhost (CPUs=4, Memory=1970MB, Disk=25067MB) ...
E0819 17:43:58.393924    2933 start.go:723] StartHost: create: precreate: exec: "docker": executable file not found in $PATH
*
X Unable to start VM: create: precreate: exec: "docker": executable file not found in $PATH
*
</details>

**The output of the `minikube logs` command**:<details>
X api load: filestore: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
*
</details>

**The operating system version**: Ubuntu Server 18.04

**Comment by afbjorklund** [comment]
You need to install Docker, in order to use the `none` driver (with the docker container runtime)

**Comment by mytuanZ** [comment]
I installed Docker and got a new error message, I will update the logs later.
Thank you for your support.

**Comment by mytuanZ** [comment]
Update error message after installing Docker.
- Exact command: sudo minikube start --vm-driver=none
- Output of command:
 X Failed to enable container runtime: running command: sudo systemctl start docker: exit status 5
- The output of the minikube logs command:
* ==> Docker <==
* -- Logs begin at Mon 2019-08-19 16:09:44 UTC, end at Tue 2019-08-20 11:49:46 UTC. --
* -- No entries --
*
* ==> container status <==
* sudo: crictl: command not found
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              P                                                                ORTS               NAMES
*
* ==> dmesg <==
* [Aug20 11:43] core: CPUID marked event: 'cpu cycles' unavailable
* [  +0.000187] core: CPUID marked event: 'instructions' unavailable
* [  +0.000204] core: CPUID marked event: 'bus cycles' unavailable
* [  +0.000186] core: CPUID marked event: 'cache references' unavailable
* [  +0.000202] core: CPUID marked event: 'cache misses' unavailable
* [  +0.000191] core: CPUID marked event: 'branch instructions' unavailable
* [  +0.000210] core: CPUID marked event: 'branch misses' unavailable
* [  +0.029646]    #2
* [  +0.004201]    #3
* [  +2.759879] piix4_smbus 0000:00:07.3: SMBus Host Controller not enabled!
* [  +0.589286] sd 2:0:0:0: [sda] Assuming drive cache: write through
* [  +6.620879] new mount options do not match the existing superblock, will be ignored
* [  +1.185341] aufs aufs_fill_super:912:mount[1571]: no arg
* [  +0.018468] overlayfs: missing 'lowerdir'
* [Aug20 11:44] kauditd_printk_skb: 26 callbacks suppressed
* [  +0.944844] aufs au_opts_verify:1623:dockerd[1915]: dirperm1 breaks the protection by the permissio                                                                n bits on the lower branch
* [Aug20 11:46] kauditd_printk_skb: 14 callbacks suppressed
* [Aug20 11:47] kauditd_printk_skb: 19 callbacks suppressed
*
* ==> kernel <==
*  11:49:47 up 6 min,  1 user,  load average: 1.09, 0.69, 0.31
* Linux u2 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* PRETTY_NAME="Ubuntu 18.04 LTS"
*
* ==> kubelet <==
* -- Logs begin at Mon 2019-08-19 16:09:44 UTC, end at Tue 2019-08-20 11:49:47 UTC. --
* -- No entries --

For more information:
- When I use this command: sudo systemctl start docker
- Output of above command: Failed to start docker.service: Unit docker.service not found.

**Comment by afbjorklund** [comment]
Still problem with your install:
`Failed to start docker.service: Unit docker.service not found.`

**Comment by tstromberg** [comment]
Closing because a resolution was posed: docker needs a systemd service to be installed.
