### ISSUE TITLE
vbox: 'minikube' has terminated unexpectedly during startup with exit code -1073741502 (0xc0000142)

### ISSUE THREAD

**Issue by hetaJ** [kubernetes/minikube#5142]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>

VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

X Unable to start VM: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code -1073741502 (0xc0000142)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
windosws 10 enterprise

**Comment by tstromberg** [comment]
What version of VirtualBox is this?

Are you able to check if VirtualBox is functioning outside of minikube?

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
