### ISSUE TITLE
sudo minikube tunnel: error getting host status for minikube: machine does not exist

### ISSUE THREAD

**Issue by dcortesf** [kubernetes/minikube#5146]
**The exact command to reproduce the issue**:
minikube start --memory=16384 --cpus=4 --kubernetes-version=v1.14.2
sudo minikube tunnel

**The full output of the command that failed**:<details>
error starting tunnel: error creating tunnel: unable to determine cluster info: error getting host status for minikube: machine does not exist

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
MacOS Mojave 10.14.6
minikube version: v1.3.1

**Comment by tstromberg** [comment]
I suspect this is because you are running the tunnel as `sudo`. The root user doesn't see the same minikube configuration as your personal user.

Perhaps we should display a warning?

**Comment by danielinclouds** [comment]
I had the same problem and I can confirm that running without sudo is fixing it.

**Comment by tstromberg** [comment]
Sounds like the culprit was found: each user only sees the minikube instances that it created.
