### ISSUE TITLE
vbox: minikube start is failing on Ubuntu 19.04

### ISSUE THREAD

**Issue by parveenksofc** [kubernetes/minikube#5147]
Getting below mentioned error while starting my minikube on Ubuntu 19.04.
No firewall on my ubuntu host and with Virtual box.

XXXX@ubuntu:~ $ minikube delete
🔥  Deleting "minikube" in virtualbox ...
💔  The "minikube" cluster has been deleted.
XXXX@ubuntu:~ $ 
XXXX@ubuntu:~$ minikube start
😄  minikube v1.3.1 on Ubuntu 19.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E0820 11:07:42.134527   20208 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe
E0820 11:07:42.156881   20208 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe
E0820 11:07:42.156952   20208 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe
E0820 11:07:42.157513   20208 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe
E0820 11:07:42.157544   20208 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe
E0820 11:07:42.157555   20208 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe
E0820 11:07:42.157565   20208 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe
E0820 11:07:42.160209   20208 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe
❌  Unable to load cached images: loading cached images: loading image /home/XXXX/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: transferring cached image: wait: remote command exited without exit status or exit signal

💣  Failed to update cluster: downloading binaries: copying kubeadm: copy: pre-copy: NewSession: write tcp 127.0.0.1:41902->127.0.0.1:38661: write: broken pipe

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
XXXX@ubuntu:~ $ 
XXXX@ubuntu:~ $ minikube logs

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:38661: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
XXXX@ubuntu:~$
XXXX@ubuntu:~$ virtualbox --help
Oracle VM VirtualBox VM Selector v6.0.6_Ubuntu
(C) 2005-2019 Oracle Corporation
All rights reserved.

No special options.

If you are looking for --startvm and related options, you need to use VirtualBoxVM.
parveensharma@ubuntu:~$

**Comment by sharifelgamal** [comment]
Could you upgrade to the latest virtualbox (6.0.10), then run `minikube delete` and see if it still fails in the same way? `ssh` isn't coming up properly.

**Comment by parveenksofc** [comment]
Thanks.

Okay I am trying to upgrade Vbox but was able to ssh in minikube VM from host Ubuntu post creating a test user to see if ssh is with any issue.

```
XXXX@ubuntu:~$ ssh test@127.0.0.1 -p 41589
test@127.0.0.1's password: 
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ ^C
$ exit
logout
Connection to 127.0.0.1 closed.
XXXX@ubuntu:~$ 
```

**Comment by parveenksofc** [comment]
Updated Virtualbox to 6.0.10
Tried 2 iteration of minikube start for no luck.
No firewall on host machine as well. As mentioned earlier I was able to SSH in minikube VM post creating a test user in it.

What I am missing here!!

```
XXXX@ubuntu:~$ virtualbox --help
Oracle VM VirtualBox VM Selector v6.0.10
(C) 2005-2019 Oracle Corporation
All rights reserved.

No special options.

If you are looking for --startvm and related options, you need to use VirtualBoxVM.
XXXX@ubuntu:~$ 
XXXX@ubuntu:~$ minikube delete
🔥  Deleting "minikube" in virtualbox ...
💔  The "minikube" cluster has been deleted.
XXXX@ubuntu:~$ 
XXXXa@ubuntu:~$ rm -rf ~/.minikube
XXXX@ubuntu:~$ minikube start
😄  minikube v1.3.1 on Ubuntu 19.04
💿  Downloading VM boot image ...
minikube-v1.3.0.iso.sha256: 65 B / 65 B [--------------------] 100.00% ? p/s 0s
minikube-v1.3.0.iso: 131.07 MiB / 131.07 MiB [-----] 100.00% 1.56 MiB p/s 1m24s
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E0820 14:56:55.482395   34434 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer
E0820 14:56:55.598907   34434 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer
E0820 14:56:55.482171   34434 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer
E0820 14:56:55.599146   34434 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer
E0820 14:56:55.600197   34434 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer
E0820 14:56:55.600254   34434 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer
E0820 14:56:55.600293   34434 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer
E0820 14:56:55.600759   34434 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer
❌  Unable to load cached images: loading cached images: loading image /home/XXXX/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.15.2: transferring cached image: wait: remote command exited without exit status or exit signal
💾  Downloading kubeadm v1.15.2
💾  Downloading kubelet v1.15.2

💣  Failed to update cluster: downloading binaries: copying kubeadm: copy: pre-copy: NewSession: write tcp 127.0.0.1:43892->127.0.0.1:46463: write: connection reset by peer

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

XXXX@ubuntu:~$ minikube logs

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:46463: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
XXXX@ubuntu:~$ minikube start
😄  minikube v1.3.1 on Ubuntu 19.04
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E0820 15:04:02.923782   35124 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43966->127.0.0.1:46463: write: connection reset by peer
E0820 15:04:02.965120   35124 ssh_runner.go:198] io.Copy failed: EOF
E0820 15:04:02.965133   35124 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43966->127.0.0.1:46463: write: connection reset by peer
E0820 15:04:02.965144   35124 ssh_runner.go:198] io.Copy failed: write tcp 127.0.0.1:43966->127.0.0.1:46463: write: connection reset by peer
❌  Unable to load cached images: loading cached images: loading image /home/XXXX/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13: deleting temp docker image location: NewSession: ssh: unexpected packet in response to channel open: <nil>

💣  Failed to update cluster: downloading binaries: copying kubeadm: copy: pre-copy: NewSession: write tcp 127.0.0.1:43966->127.0.0.1:46463: write: connection reset by peer

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
parveensharma@ubuntu:~$ minikube logs

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:46463: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
XXXX@ubuntu:~$ 

XXXX@ubuntu:~$ sudo ps awux | grep -i iptab
XXXX+  35582  0.0  0.0  17612   916 pts/0    R+   15:13   0:00 grep --color=auto -i iptab
XXXX@ubuntu:~$ sudo ps awux | grep -i firewa
XXXX+  35585  0.0  0.0  17612   912 pts/0    R+   15:14   0:00 grep --color=auto -i firewa
XXXX@ubuntu:~$ 
```

**Comment by parveenksofc** [comment]
Hi,

In order to further providing evidences I executed:

```
XXXXX@ubuntu:~$ ( minikube -v=9 start | tee -a /tmp/minikube_start_logs2 )  2>&1 | tee -a /tmp/minikube_start_logs1
```

I am attaching both the files for complete logs i.e. minikube_start_logs[1,2].

[minikube_start_logs.zip](https://github.com/kubernetes/minikube/files/3525285/minikube_start_logs.zip)

Please do let me know if there is anything needs from my end.

**Comment by parveenksofc** [comment]
Please update.

**Comment by parveenksofc** [comment]
Please help here. 

What else I can try.... Or it is broken ok Ubuntu 19.04?

**Comment by afbjorklund** [comment]
Can you start other VMs successfully, for instance 'docker-machine create default` ?

There seems to be something wrong with your networking for VirtualBox, the NAT

**Comment by parveenksofc** [comment]
@afbjorklund Thanks.

Where to start VM!! In side the minikube Vbox ?

**Comment by afbjorklund** [comment]
No, I meant if VirtualBox works fine on your machine otherwise ? (outside Minikube)

**Comment by parveenksofc** [comment]
Yes.

As I mentioned I was able to SSH in the minukube Vbox from my host machine after creating a test user.

```
XXXX@ubuntu:~$ ssh test@127.0.0.1 -p 41589
test@127.0.0.1's password: 
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ ^C
$ exit
logout
Connection to 127.0.0.1 closed.
XXXX@ubuntu:~$ 
```

**Comment by afbjorklund** [comment]
Hmm, I don't see why there should be any difference between test@ and the default user docker@ ?

**Comment by parveenksofc** [comment]
Is there anything I can provide to further investigate.

**Comment by sharifelgamal** [comment]
Could you update to minikube 1.4 and try again? This might have been fixed with it.

**Comment by sharifelgamal** [comment]
Hopefully it's ok if I close this, it's been some time since we were last updated. If you upgrade to minikube 1.5.1 and still see the problem feel free to reopen this bug with `/reopen` and give us the details from the new minikube run.
