### ISSUE TITLE
Incorrect tabs on macOS getting started guide

### ISSUE THREAD

**Issue by praveensastry** [kubernetes/minikube#5157]
Additional tab with title 'Brew' is added which is causing the incorrect tab active index 
<img width="649" alt="Screen Shot 2019-08-21 at 10 30 08 pm" src="https://user-images.githubusercontent.com/501335/63431885-43371300-c463-11e9-8d5a-0bf5d86bb254.png">

**Comment by medyagh** [comment]
ah ! good catch !
