### ISSUE TITLE
kubeadm.go: apiserver status: Stopped

### ISSUE THREAD

**Issue by robotsp** [kubernetes/minikube#5167]
**The exact command to reproduce the issue**:
I install minikube on Centos 7, and run ./minikube start --registry-mirror=https://registry.docker-cn.com --vm-driver="none"   --v=3 --alsologtostderr.

**The full output of the command that failed**:<details>

I0822 13:29:29.896181   89080 kubeadm.go:385] apiserver status: Stopped, err: <nil>
I0822 13:29:30.196147   89080 kubeadm.go:143] https://10.125.164.134:8443/healthz response: Get https://10.125.164.134:8443/healthz: dial tcp 10.125.164.134:8443: connect: connection refused <nil>
I0822 13:29:30.196179   89080 kubeadm.go:385] apiserver status: Stopped, err: <nil>
I0822 13:29:30.496310   89080 kubeadm.go:143] https://10.125.164.134:8443/healthz response: Get https://10.125.164.134:8443/healthz: dial tcp 10.125.164.134:8443: connect: connection refused <nil>

</details>

**The output of the `minikube logs` command**:<details>

* Aug 22 13:57:58 b2b-qa-bigu-cdh-server-0 kubelet[123466]: E0822 13:57:58.605238  123466 event.go:249] Unable to write event: 'Patch https://localhost:8443/api/v1/namespaces/kube-system/events/etcd-minikube.15bd0066187ac16c: dial tcp [::1]:8443: connect: connection refused' (may retry after sleeping)
* Aug 22 13:57:58 b2b-qa-bigu-cdh-server-0 kubelet[123466]: E0822 13:57:58.675433  123466 reflector.go:125] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&limit=500&resourceVersion=0: dial tcp [::1]:8443: connect: connection refused
* Aug 22 13:57:58 b2b-qa-bigu-cdh-server-0 kubelet[123466]: E0822 13:57:58.684445  123466 kubelet.go:2248] node "minikube" not found
* Aug 22 13:57:58 b2b-qa-bigu-cdh-server-0 kubelet[123466]: E0822 13:57:58.784828  123466 kubelet.go:2248] node "minikube" not found
* Aug 22 13:57:58 b2b-qa-bigu-cdh-server-0 kubelet[123466]: E0822 13:57:58.875293  123466 reflector.go:125] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.CSIDriver: Get https://localhost:8443/apis/storage.k8s.io/v1beta1/csidrivers?limit=500&resourceVersion=0: dial tcp [::1]:8443: connect: connection refused
* Aug 22 13:57:58 b2b-qa-bigu-cdh-server-0 kubelet[123466]: E0822 13:57:58.884995  123466 kubelet.go:2248] node "minikube" not found
* Aug 22 13:57:58 b2b-qa-bigu-cdh-server-0 kubelet[123466]: E0822 13:57:58.985248  123466 kubelet.go:2248] node "minikube" not found

</details>

**The operating system version**:

Centos 7.4

Thanks!

**Comment by tstromberg** [comment]
Hi @robotsp! Thank you for the bug report.

Do you mind including the full output of the `minikube start` command? I cannot tell from this bug report what version of minikube you are running on, and what error minikube displayed.

Also, the output of this commands would be quite useful:

`docker ps -a`

Thank you!

**Comment by robotsp** [comment]
minikube start:

[root@b2b-qa-bigu-cdh-server-0 bin]# ./minikube start
* minikube v1.3.1 on Centos 7.4.1708
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
* Downloading VM boot image ...
* 
X Failed to cache ISO
* Error: [DOWNLOAD_IO_TIMEOUT] https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso.sha256: dial tcp 216.58.200.48:443: i/o timeout
* Suggestion: A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
* Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3846
* 
* If the above advice does not help, please let us know: 
  - https://github.com/kubernetes/minikube/issues/new/choose

docker ps -a

[root@b2b-qa-bigu-cdh-server-0 bin]# docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                    PORTS                    NAMES
0442e9667896        k8s.gcr.io/pause:3.1   "/pause"                 32 hours ago        Up 32 hours                                        k8s_POD_kube-scheduler-minikube_kube-system_abfcb4f52e957b11256c1f6841d49700_0
d841551fdb57        k8s.gcr.io/pause:3.1   "/pause"                 32 hours ago        Up 32 hours                                        k8s_POD_kube-controller-manager-minikube_kube-system_ee64e541bb4d363d421723c0b41350a3_0
5b0a7078e2c4        k8s.gcr.io/pause:3.1   "/pause"                 32 hours ago        Up 32 hours                                        k8s_POD_kube-apiserver-minikube_kube-system_916a8125060ca39bc9e7f2bda203939b_0
64e3026be670        k8s.gcr.io/pause:3.1   "/pause"                 32 hours ago        Up 32 hours                                        k8s_POD_etcd-minikube_kube-system_4205e0c977ec2de4445e48ea518a5cc1_0
23b0524b5b4a        k8s.gcr.io/pause:3.1   "/pause"                 32 hours ago        Up 32 hours                                        k8s_POD_kube-addon-manager-minikube_kube-system_65a31d2b812b11a2035f37c8a742e46f_0
731c1918df5f        registry               "/entrypoint.sh /etc…"   4 days ago          Up 4 days                 0.0.0.0:5000->5000/tcp   registry
a2f8e4dace45        centos:6               "/bin/bash"              4 days ago          Exited (127) 4 days ago                            test01

**Comment by sharifelgamal** [comment]
Looks like you can't download our ISO from GCS, we have a bug open (#4774) that will allow everyone to download ISOs from Github directly. 

Closing this as a dupe.
