### ISSUE TITLE
ip: Error getting IP: Host is not running (confusing multi-profile text)

### ISSUE THREAD

**Issue by pjhavariotis** [kubernetes/minikube#5170]
Although minikube is started succesfully, something is going wrong with the IP retrieval.
Please find below the exact minikube start command:
```
minikube start -p minikube2 --vm-driver hyperv --hyperv-virtual-switch "Default Switch" --docker-env http_proxy=http://wsa.central.nbg.gr:8080 --docker-env https_proxy=http://wsa.central.nbg.gr:8080 --docker-env no_proxy=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24                                                                                                                                                                         * [minikube2] minikube v1.3.1 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362                                                                                                                                                      * Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...                                                                                                                                                                               * Found network options:
  - HTTP_PROXY=http://wsa.central.nbg.gr:8080
! You appear to be using a proxy, but your NO_PROXY environment does not include the minikube IP (192.168.119.133). Please see https://minikube.sigs.k8s.io/docs/reference/networking/proxy/ for more details
  - HTTPS_PROXY=http://wsa.central.nbg.gr:8080
  - NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24
  - http_proxy=http://wsa.central.nbg.gr:8080
  - https_proxy=http://wsa.central.nbg.gr:8080
  - no_proxy=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24
* Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
  - env http_proxy=http://wsa.central.nbg.gr:8080
  - env https_proxy=http://wsa.central.nbg.gr:8080
  - env no_proxy=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24
* Pulling images ...
* Launching Kubernetes ...
* Waiting for: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube2"
```

**The exact command to reproduce the issue**:
minikube ip

**The full output of the command that failed**:<details>
*
X Error getting IP: Host is not running
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
</details>

**The output of the `minikube logs` command**:<details>
*
X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2496 Mhz
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             el;Greek
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+02:00) Athens, Bucharest
Total Physical Memory:     8.086 MB
Available Physical Memory: 1.709 MB
Virtual Memory: Max Size:  9.366 MB
Virtual Memory: Available: 2.604 MB
Virtual Memory: In Use:    6.762 MB
Page File Location(s):     C:\pagefile.sys
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB4495620
                           [02]: KB4497727
                           [03]: KB4498523
                           [04]: KB4503308
                           [05]: KB4506933
                           [06]: KB4503293
Network Card(s):           4 NIC(s) Installed.
                           [01]: Array Networks SSL VPN Adapter
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [02]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.119.129
                           [03]: Intel(R) Ethernet Connection (2) I219-V
                                 Connection Name: Ethernet
                                 DHCP Enabled:    No
                                 IP address(es)
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Primary Virtual Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 10.1.97.5
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by tstromberg** [comment]
I believe this is correct, albeit the error message is confusing.

You have started minikube using `-p minikube2`, which names the cluster `minikube2`. To look up the IP or logs for this cluster name, you will need to similarly add `-p minikube2`, such as:

`minikube ip -p minikube2`

or

`minikube logs -p minikube2`

Otherwise it is trying to look up the IP or logs for a cluster named `minikube`. Please let me know if this helps.

**Comment by tstromberg** [comment]
To improve this, it would be nice if the error message specifically said something like:

`The cluster named "minikube" is currently not running. Use "minikube start" to start it.`.

**Comment by pjhavariotis** [comment]
Thanks for the help!
