### ISSUE TITLE
Users directory is not shared with Hyper-V VM

### ISSUE THREAD

**Issue by raeesbhatti** [kubernetes/minikube#518]
**Minikube version** (use `minikube version`): `minikube version: v0.8.0`

**Environment**:
- **OS**: Windows 10 Professional 64bit
- **VM Driver**: `hyperv`
- **Docker version**: `Docker version 1.11.1, build 5604cbe`

**What happened**:
The user home directory `C:/Users/myuser` is not shared with the minikube VM.

**What you expected to happen**:
The user home directory should have been shared with the VM.

**How to reproduce it** (as minimally and precisely as possible):
Start minikube with `hyperv` driver and try to access the user directory from the VM.

**Anything else do we need to know**:
This is a follow up on https://github.com/kubernetes/minikube/pull/467 and https://github.com/kubernetes/minikube/issues/465

**Comment by numbsafari** [comment]
Experiencing the same issue.

**Comment by r2d4** [comment]
@numbsafari you should make sure that you using the latest xhyve driver https://github.com/zchee/docker-machine-driver-xhyve/releases/tag/v0.2.3

The behavior for the xhyve driver was only added in v0.2.3

**Comment by numbsafari** [comment]
Got it. I think I'm having some other issue related to `homebrew cask`, which is how I've been installing minikube. For some reason, it's not picking up on the 0.8.0 release.

**Comment by dlorenc** [comment]
@raeesbhatti it looks like hyper-v doesn't come with any built in folder host to guest folder sharing. We'll have to implement something for this ourselves.

**Comment by raeesbhatti** [comment]
@dlorenc Docker for Windows has an option to share drives with the VM. I think it would be better to ask them for help. Maybe @FrenchBen can share some insight!

**Comment by raeesbhatti** [comment]
"The Linux VM used for Docker for Windows uses SMB/CIFS mounting of the host filesystem." excerpt from Docker for Windows docs.

**Comment by FrenchBen** [comment]
@raeesbhatti that's exactly right - there's a bit of magic to make work though :P

**Comment by raeesbhatti** [comment]
Is there going to be a fix for this in the near future? Or nobody is interested?

**Comment by dlorenc** [comment]
We'd definitely like to fix this, we just don't have much Windows expertise :( 

I'm happy to help out any way I can if someone wants to give this a try.

**Comment by aaron-prindle** [comment]
We have recently added a `minikube mount /path/to/dir` command that should mount a specified host directory into the minikubeVM.  This command works with hyperv.

**Comment by aaron-prindle** [comment]
Closing as the `minikube mount` command is now the recommended way to mount dirs in minikube and this is not driver specific.
