### ISSUE TITLE
Add --dry-run flag to surface configuration warnings

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5181]
For embedding within an API, it would be handy to have a dry run mode to surface issues a user may have with the current configuration. For example:

- Warning if the user will need sudo permissions
- `minikube start --dry-run`
- Resource warnings (RAM, CPU)

Basically, anything that would normally cause `minikube start` to exit due to an invalid configuration should do so and output why - and do so quickly.

**Comment by tstromberg** [comment]
This is still required.

**Comment by medyagh** [comment]
my undrestanding of this issue, it should not start any Vm or machine, but does all the checks!  I would be happy to review the PR for it.

**Comment by nanikjava** [comment]
Happy to take this on.

/assign @nanikjava

**Comment by sharifelgamal** [comment]
I believe this is still needed.
