### ISSUE TITLE
hyperv: vswitch "minikube v switch" not found

### ISSUE THREAD

**Issue by karthigaadass** [kubernetes/minikube#5184]
**The exact command to reproduce the issue**:
minikube start --vm-driver hyperv --hyperv-virtual-switch "minikube v switch"

**The full output of the command that failed**:<details>

E0823 11:44:20.076363   14848 start.go:723] StartHost: create: precreate: vswitch "minikube v switch" not found
*
X Unable to start VM: create: precreate: vswitch "minikube v switch" not found
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
Do you mind sharing th output of: 

`Get-VMSwitch -SwitchType External`

That should show the appropriate value to use.

Related: #4079

**Comment by tstromberg** [comment]
@karthigaadass -  I believe this issue is now addressed by minikube v1.4, as it no longer requires `--hyperv-virtual-switch` to be passed in. If you still see this issue with minikube v1.4 or higher, please reopen this issue by commenting with `/reopen`

Thank you for reporting this issue!
