### ISSUE TITLE
Windows 10 + VirtualBox + Minikube CPU optimization

### ISSUE THREAD

**Issue by cpu100** [kubernetes/minikube#5185]
I stumbled upon that VirtualMachinePlatform-Feature-Related causes more CPU useless computing when I tried [WSL2](https://docs.microsoft.com/en-us/windows/wsl/wsl2-install). Even if this feature is not enabled, it can result in kube-apiserver taking up 5 to 10 times more CPU resources than normal. You need to manually enable and disable it again, and the CPU will return to normal.

After some commands and reboots, I found that my CPU was green again:
```
# windows powershell
Enable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
Disable-WindowsOptionalFeature -Online -FeatureName VirtualMachinePlatform
```

**Comment by tstromberg** [comment]
@cpu100 - Thank you for sharing! Was this with VirtualBox or Hyper-V as a driver?

Also, how were you measuring the CPU resources of the apiserver?

This sounds like it might be good advice to add to the related troubleshooting doc of whichever driver you were using.

**Comment by cpu100** [comment]
I create the cluster with command  `minikube start` without additional arguments, the VirtualBox default driver is used, not Hyper-V.

**Comment by cpu100** [comment]
I measuring the CPU resources roughly by `minikube ssh "docker stats"` .
I found that containers with prefix `k8s_kube-apiserver_*` uses most of the CPU resources, which causes the host CPU usage to increase.

**Comment by cpu100** [comment]
My windows version is `1903 (18362.295)` .

**Comment by cpu100** [comment]
I also used `microk8s`, which also has the same CPU performance issues and can be solved with the same steps.

**Comment by tstromberg** [comment]
Thanks!

**Comment by priyawadhwa** [comment]
Hey @cpu100 are you still seeing this issue?

If so, could you please try upgrading to VirtualBox 6.1 and the [latest release](https://minikube.sigs.k8s.io/docs/start/) of Minikube? Please let us know if that does or doesn't work for you.
