### ISSUE TITLE
docs: remove or replace /concepts boilerplate

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5189]
seems to be a boilerplate leftover
https://minikube.sigs.k8s.io/docs/concepts/

**Comment by tstromberg** [comment]
I'd prefer to see this section get filled in than be deleted. It's the perfect place to document to provide an overall idea of how and why minikube works the way it does.

**Comment by nanikjava** [comment]
@tstromberg Does populating the page with content from my website https://kubernetes.onrender.com/post/howminikubeworks/ be suitable ? if it is than happy to copy over my for the concepts page, or perhaps renamed it something else rather than concept to accomodate ?

Let me know.

**Comment by priyawadhwa** [comment]
Closing, resolved by #5862
