### ISSUE TITLE
examples doc uses deprecated "kubectl run" cmd

### ISSUE THREAD

**Issue by dlorch** [kubernetes/minikube#5190]
**The exact command to reproduce the issue**:

kubectl run hello-minikube --image=k8s.gcr.io/echoserver:1.4 --port=8080

From https://github.com/kubernetes/minikube/blob/master/site/content/en/docs/Examples/_index.md

**The full output of the command that failed**:<details>

kubectl run --generator=deployment/apps.v1 is DEPRECATED and will be removed in a future version. Use kubectl run --generator=run-pod/v1 or kubectl create instead.
deployment.apps/hello-minikube created

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

Darwin macintosh.home 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64

**Suggested fix**:

kubectl run hello-minikube --generator=run-pod/v1 --image=k8s.gcr.io/echoserver:1.4 --port=8080

**Comment by tstromberg** [comment]
Thank you for bringing this up instead of quietly ignoring the issue.

**Comment by rajalokan** [comment]
If they want start using `kubectl create`, does this mean we are not supposed to run only `Pod`. For some example or explanation purpose, it makes sense to create only `Pod` resource. Which is why it makes sense to have `kubectl run` command.

**Comment by RA489** [comment]
@dlorch Your suggested fix doesn't create deployment but just a pod and if you try to expose you will get an error while executing this command

```
$ kubectl expose deployment hello-minikube --type=NodePort
Error from server (NotFound): deployments.extensions "hello-minikube" not found
```

**Comment by RA489** [comment]
@dlorch Please try this as workaround.

`kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4`

**Comment by RA489** [comment]
Expose it as a Service use this command
`kubectl expose deployment hello-minikube --port=8080`

**Comment by domix** [comment]
hello @RA489, are you still working on this? looks like it's almost done.

**Comment by RA489** [comment]
@domix yeah i think its done

**Comment by medyagh** [comment]
@RA489 do you have a PR for this ? or did we merge a PR for this ?

**Comment by RA489** [comment]
@medyagh I think it has been done! if not i can file PR for it.

**Comment by medyagh** [comment]
@RA489 I dont see any PR for it. you could have it !

**Comment by RA489** [comment]
@medyagh sure i will file a PR for it then.
