### ISSUE TITLE
Failed to delete cluster: exit status 126

### ISSUE THREAD

**Issue by mcooling** [kubernetes/minikube#5192]
**The exact command to reproduce the issue**:
$ minikube delete

**The full output of the command that failed**:<details>

Deleting "minikube" in virtualbox ...

💣  Failed to delete cluster: exit status 126

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
Hey @mcooling - do you mind sharing the output of:

`minikube delete --alsologtostderr -v=8`

That should provide us with enough clues to go on.

**Comment by mcooling** [comment]
Sure. Here you go..

command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
[23:06:40] marccooling:~ $ minikube delete --alsologtostderr -v=8
I0825 08:41:57.336722    1773 notify.go:124] Checking for updates...
🔥  Deleting "minikube" in virtualbox ...
COMMAND: /usr/local/bin/VBoxManage showvminfo minikube --machinereadable
STDOUT:
{
}
STDERR:
{
/usr/local/bin/VBoxManage: line 2: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage: No such file or directory
/usr/local/bin/VBoxManage: line 2: exec: /Applications/VirtualBox.app/Contents/MacOS/VBoxManage: cannot execute: No such file or directory
}
W0825 08:41:57.773021    1773 exit.go:99] Failed to delete cluster: exit status 126

💣  Failed to delete cluster: exit status 126

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
My interpretation: VirtualBox is no longer installed in `/Applications/VirtualBox`, but there is still a wrapper (`/usr/local/bin/VBoxManage`) that assumes it is there. Does that seem possible?

My suggestion: reinstall VirtualBox.

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
