### ISSUE TITLE
minikube service could handle multiple-ports-per-service better

### ISSUE THREAD

**Issue by mathuin** [kubernetes/minikube#5200]
**The exact command to reproduce the issue**:
1.  Create a service with two ports in the spec, perhaps for Minecraft.
2. Run `minikube service nothing-minecraft`.

**The full output of the command that failed**:<details>
Strictly speaking, the command does not fail.  It's just not very helpful.
```
|-----------|-------------------|--------------------------------|
| NAMESPACE |       NAME        |              URL               |
|-----------|-------------------|--------------------------------|
| default   | nothing-minecraft | http://192.168.99.100:32225    |
|           |                   | http://192.168.99.100:32412    |
|-----------|-------------------|--------------------------------|
```

This could be improved by adding a column for the service port name:

```
|-----------|-------------------|--------|--------------------------------|
| NAMESPACE |       NAME        |  PORT  |              URL               |
|-----------|-------------------|--------|--------------------------------|
| default   | nothing-minecraft | server | http://192.168.99.100:32225    |
|           |                   | dynmap | http://192.168.99.100:32412    |
|-----------|-------------------|--------|--------------------------------|
```

I'm not sure if this column should always be there or only when there is more than one service.  I have no preference, myself.

It would also be nice to specify the port on the command line for those wishing to open a URL in their default browser -- wouldn't do much good to open the Minecraft server port, for instance, but browsing the dynmap service would be helpful.
</details>

**The output of the `minikube logs` command**:<details>
Not relevant
</details>

**The operating system version**:
Not relevant

**Comment by tstromberg** [comment]
Sounds reasonable to me.

**Comment by 11janci** [comment]
Hi, I'd like to work on this

**Comment by 11janci** [comment]
Pls see the above PR, I currently show the new column always as I personally think it is not worth it adding a flag just for this and don't see any harm having it. Pls let me know if you'd like to change that behaviour (might be worth hiding it when empty)
