### ISSUE TITLE
vbox on Digital Ocean: StartHost: start: Maximum number of retries (5) exceeded

### ISSUE THREAD

**Issue by jsbilgi** [kubernetes/minikube#5206]
**The exact command to reproduce the issue**:
minikube start --vm-driver=none

**The full output of the command that failed**:<details>
* minikube v1.3.1 on Ubuntu 18.04
*

! Ignoring --vm-driver=none, as the existing "minikube" VM was created using the virtualbox driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=none`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`
*

* Starting existing virtualbox VM for "minikube" ...
E0827 11:29:51.589160    6128 start.go:723] StartHost: start: Maximum number of retries (5) exceeded
*
X Unable to start VM: start: Maximum number of retries (5) exceeded
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
root@Docker-Usergrid-Temp:~# virt-what
kvm

root@Docker-Usergrid-Temp:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.3 LTS
Release:        18.04
Codename:       bionic

root@Docker-Usergrid-Temp:~# lscpu
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              1
On-line CPU(s) list: 0
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
Stepping:            4
CPU MHz:             2294.608
BogoMIPS:            4589.21
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            25344K
NUMA node0 CPU(s):   0
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves pku ospke md_clear

</details>

**The operating system version**:

root@Docker-Usergrid-Temp:~# uname -a
Linux Docker-Usergrid-Temp 4.15.0-52-generic #56-Ubuntu SMP Tue Jun 4 22:49:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by medyagh** [comment]
I am guessing you had first tried to start the minikube with default driver ( Virtualbox) then it got ignored! 


That's weird that it got ignored even when you set your minikube profile!

Do you mind trying if minikube delete solves the problem ?

And second if I didn't . You could do the nuke option.
Delete ~/. minikube

**Comment by afbjorklund** [comment]
Why run VirtualBox on a cloud provider ? Must be better ways...

**Comment by tstromberg** [comment]
The conflation of drivers (none vs virtualbox) has been fixed in minikube v1.4.
