### ISSUE TITLE
"failed to cache ISO" Error while starting minikube on windows 10

### ISSUE THREAD

**Issue by vivporwal** [kubernetes/minikube#5214]
**The exact command to reproduce the issue**:
C:\> minikube start --docker-env http://usernamexx:pswdxx@xx.xx.xx.xx:pppp --docker-env https://usernamexx:psswdxx@xx.xx.xx.xx:pppp

Note: obfuscating proxy IPs 
</details>

**The output of the `minikube logs` command**:<details>
**The full output of the command that failed**:<details>
* minikube v1.3.1 on Microsoft Windows 10 Enterprise 10.0.16299 Build 16299
* Downloading VM boot image ...
*
X Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso.sha256: proxyconnect tcp: EOF
*
</details>

**The operating system version**:
Microsoft Windows 10 Enterprise 10.0.16299 Build 16299

**Comment by tstromberg** [comment]
You will need to tell minikube about the proxy that is required to access the internet, by using the `http_proxy` and `https_proxy` environment variables:

https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

On the plus side, it will pass the correct configuration to docker as well.

Please let me know if this helps!

**Comment by tstromberg** [comment]
Closing as a workaround has been provided.

Also related: #4774
