### ISSUE TITLE
kvm2: infinite wait after "OS type not recognized" error

### ISSUE THREAD

**Issue by staticdev** [kubernetes/minikube#5215]
**The exact command to reproduce the issue**:
minikube start  --vm-driver=kvm2

**The full output of the command that failed**:<details>
Very strange behavior:
1- it starts with `Error checking driver: exit status 1`
2- it downloads ISO 1.3.0 instead of 1.3.1 than 
3- Waiting for host provisioned is taking lots of minutes... than give OS error. BUT I've been running last versions of minikube until 1.2.0 and got no problems with OS detection. 

minikube start --vm-driver=kvm2
😄  minikube v1.3.1 on Ubuntu 19.04
⚠️  Error checking driver version: exit status 1
👍  Upgrading from Kubernetes 1.15.0 to 1.15.2
💿  Downloading VM boot image ...
minikube-v1.3.0.iso.sha256: 65 B / 65 B [--------------------] 100.00% ? p/s 0s
minikube-v1.3.0.iso: 131.07 MiB / 131.07 MiB [-------] 100.00% 5.00 MiB p/s 26s
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running kvm2 "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
E0827 20:57:07.379558    5311 start.go:723] StartHost: Temporary Error: Error configuring auth on host: OS type not recognized
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running kvm2 "minikube" VM ...
⌛  Waiting for the host to be provisioned ...

</details>

**The output of the `minikube logs` command**:<details>
💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp :22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Ubuntu 19.04

**Comment by afbjorklund** [comment]
"OS type not recognized" means that docker machine provisioning failed. Possibly due to SSH timeout.

**Comment by medyagh** [comment]
@staticdev  do you happen to be using VPN ?

**Comment by staticdev** [comment]
@medyagh no. Just pure Ubuntu.

**Comment by medyagh** [comment]
@staticdev sorry being no help here, but I am curious  do you still have this issue even with the newest version ?

**Comment by staticdev** [comment]
@medyagh my tests today:

> $ minikube start --vm-driver=kvm2
> ⚠️  minikube 1.5.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.5.2
> 💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'
> 😄  minikube v1.3.1 on Ubuntu 19.10
> ⚠️  Error checking driver version: exit status 1
> 💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
> 🔄  Starting existing kvm2 VM for "minikube" ...
> ⌛  Waiting for the host to be provisioned ...
> 🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
> 🔄  Relaunching Kubernetes using kubeadm ... 
> ⌛  Waiting for: apiserver proxy etcd scheduler controller dns
> 🏄  Done! kubectl is now configured to use "minikube"

Please note I still used the old version 1.3.1 in the same machine, with same PODs. Also note the link for new version is broken: https://github.com/kubernetes/minikube/releases/tag/v**/**1.5.2 there is a spare '/'.

Then `minikube stop` and installed newest version on my Ubuntu with:
```sh
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
&& chmod +x minikube
sudo cp minikube /usr/local/bin && rm minikube
```

Finally another try:

> minikube start --vm-driver=kvm2
> 😄  minikube v1.5.2 on Ubuntu 19.10
> 💾  Downloading driver docker-machine-driver-kvm2:
>     > docker-machine-driver-kvm2.sha256: 65 B / 65 B [-------] 100.00% ? p/s 0s
>     > docker-machine-driver-kvm2: 13.87 MiB / 13.87 MiB  100.00% 44.57 KiB p/s 
> 👍  Upgrading from Kubernetes 1.15.2 to 1.16.2
> 💿  Downloading VM boot image ...
>     > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
>     > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [ 100.00% 1.21 MiB p/s 1m58s
> 💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
> 🔄  Starting existing kvm2 VM for "minikube" ...
> ⌛  Waiting for the host to be provisioned ...
> 🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.8' ...
> 💾  Downloading kubelet v1.16.2
> 💾  Downloading kubeadm v1.16.2
> 🚜  Pulling images ...
> 🔄  Relaunching Kubernetes using kubeadm ... 
> ⌛  Waiting for: apiserver
> 🏄  Done! kubectl is now configured to use "minikube"

The error seems to vanish, I will make more tests. Another strange fact I noticed is that I was running v1.5.2 and it downloaded IMG v1.5.1.

**Comment by priyawadhwa** [comment]
Hey @staticdev thanks for testing with the new version. The ISO for minikube v.1.5.2 is actually meant to be v1.5.1 since it hasn't been updated since v1.5.1 (totally agree that that's confusing!)

Please let us know if the update has resolved your issue.

**Comment by tstromberg** [comment]
Please re-open if you see this issue again.
