### ISSUE TITLE
Unauthorized to kubernetes-dashboard?

### ISSUE THREAD

**Issue by ahmetalpbalkan** [kubernetes/minikube#522]
- OS: Mac OS X
- `minikube v0.8.0` 
- `brew install kubernetes-cli` (v1.3.5).

```
$ minikube start --> worked
$ minikube ip
192.168.99.100

$ kubectl cluster-info

Kubernetes master is running at https://192.168.99.100:8443
kubernetes-dashboard is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
```

So I click https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

After passing invalid TLS cert error I just get `Unauthorized` message on the response body for the dashboard. How does the dashboard work with minikube?

**Comment by r2d4** [comment]
The `minikube dashboard` command will open up the dashboard

**Comment by ahmetalpbalkan** [comment]
@r2d4 ah thanks! Though it would be nice UX-wise if kubectl was aware of this somehow.

**Comment by avogt-sundn** [comment]
In case your server has no x11 display, use ````minikube dashboard --url```` to learn the url to open:

       [root@localhost ~]# minikube dashboard --url
       http://192.168.99.100:30000

if you use virtualbox, open a port forward with:

        vboxmanage  controlvm minikube natpf1 rule2,tcp,,30000,,30000

if you use centos open the local firewall:

         firewall-cmd --zone=public --add-port=30000/tcp --permanent
         firewall-cmd --reload

Now you should be able to open from a remote browser with the public ip of your host (server)

        http://<public-ip>:30000/
