### ISSUE TITLE
How to use an external CA such as OpenStack Magnum with minikube

### ISSUE THREAD

**Issue by piersharding** [kubernetes/minikube#5221]
Hi - I am trying to create a simple driver for OpenStack Magnum for creating minikube (single node) clusters, and have a problem with trying to use an external CA (the Magnum CA which is used by the other Kubernetes cluster drivers so that openstack commands can issue KUBECONFIG etc.).  I thought that taking the ca.key and ca.crt generated by the external CA and putting them in $HOME/.minikube/ might enable me to override the minikube generated one but I am stuck on the below described error.

Any advice or help much appreciated - there is probably a 'right way' of passing in a predetermined CA to kubeadm but I haven't been able to find it yet.

Thanks,
Piers.

files in $HOME/.minikube after `minikube start` is run are:
```
ls -latr ~/.minikube
total 16
drwx------.  5 root root  150 Aug 28 01:20 ..
-r--------.  1 root root 1705 Aug 28 05:29 ca.key
-rw-r--r--.  1 root root 1046 Aug 28 05:29 ca.crt
drwxr-xr-x.  2 root root    6 Aug 28 05:29 logs
drwxr-xr-x.  2 root root    6 Aug 28 05:29 files
drwxr-xr-x.  2 root root    6 Aug 28 05:29 config
drwxr-xr-x.  2 root root    6 Aug 28 05:29 addons
drwx------.  3 root root   22 Aug 28 05:29 profiles
drwxr-xr-x.  3 root root   22 Aug 28 05:29 machines
drwxr-xr-x.  2 root root   69 Aug 28 05:29 certs
drwxr-xr-x.  4 root root   32 Aug 28 05:29 cache
-rw-------.  1 root root 1679 Aug 28 05:31 proxy-client-ca.key
-rw-r--r--.  1 root root 1074 Aug 28 05:31 proxy-client-ca.crt
```

**The exact command to reproduce the issue**:
```
minikube start --v=7 --wait=true --apiserver-port=6443 --extra-config=kubelet.resolv-conf=/etc/resolv.conf --extra-config=kubelet.cgroup-driver=systemd --apiserver-ips=10.0.0.60 --apiserver-ips=192.168.88.236 --apiserver-ips=192.168.88.235 --apiserver-ips=10.0.0.227 --apiserver-ips=127.0.0.1 --apiserver-ips=10.0.0.1 --apiserver-ips=10.96.0.1 --apiserver-names=localhost --vm-driver=none
```

**The full output of the command that failed**:<details>
😄  minikube v1.3.1 on Fedora 29 (kvm/amd64)
🤹  Running on localhost (CPUs=2, Memory=3942MB, Disk=39922MB) ...
Creating CA: /root/.minikube/certs/ca.pem
Creating client certificate: /root/.minikube/certs/cert.pem
Couldn't set key VERSION_CODENAME, no corresponding struct field found
Couldn't set key PLATFORM_ID, no corresponding struct field found
Couldn't set key LOGO, no corresponding struct field found
Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key DOCUMENTATION_URL, no corresponding struct field found
Couldn't set key REDHAT_BUGZILLA_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_BUGZILLA_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
Couldn't set key OSTREE_VERSION, no corresponding struct field found
ℹ️   OS release is Fedora 29.20190708.0 (Atomic Host)
🐳  Preparing Kubernetes v1.15.2 on Docker 1.13.1 ...
    ▪ kubelet.resolv-conf=/etc/resolv.conf
    ▪ kubelet.cgroup-driver=systemd
💾  Downloading kubeadm v1.15.2
💾  Downloading kubelet v1.15.2

💣  Failed to setup certs: Error generating certs: Error generating signed apiserver serving cert: Error parsing prive key: decodedSignerKey.Bytes: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
==> Docker <==
-- Logs begin at Wed 2019-08-28 01:17:08 UTC, end at Wed 2019-08-28 05:31:45 UTC. --
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.546575       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.546719       1 clientconn.go:960] grpc: addrConn.transportMonitor exits due to: context canceled
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.546789       1 clientconn.go:960] grpc: addrConn.transportMonitor exits due to: context canceled
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.546803       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.546825       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.546852       1 clientconn.go:960] grpc: addrConn.transportMonitor exits due to: context canceled
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.546929       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.546962       1 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.547007       1 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.562051       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: []
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.562124       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.562435       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.562400       1 clientconn.go:960] grpc: addrConn.transportMonitor exits due to: context canceled
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.562541       1 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.592334       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: []
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.592410       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.592742       1 clientconn.go:960] grpc: addrConn.transportMonitor exits due to: context canceled
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.592790       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.593037       1 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.626386       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: []
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.626502       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: I0828 05:28:35.626587       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.626510       1 clientconn.go:960] grpc: addrConn.transportMonitor exits due to: context canceled
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: W0828 05:28:35.627671       1 clientconn.go:1251] grpc: addrConn.createTransport failed to connect to {127.0.0.1:2379 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused". Reconnecting...
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: time="2019-08-28T05:28:35.639043628Z" level=warning msg="732c3e3daed8ab5f9eefabe4abc9302269074d186b050a2693b23e1e40856d4f cleanup: failed to unmount secrets: invalid argument"
Aug 28 05:28:35 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: time="2019-08-28T05:28:35.790982807Z" level=warning msg="8371daaebdb07d1a86647c8a1da9fb798ea0ab6b3ddd2009d15849e4ec14612b cleanup: failed to unmount secrets: invalid argument"
Aug 28 05:28:36 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: time="2019-08-28T05:28:36.005868133Z" level=warning msg="a76c8d82ae0dfb604a1700f249c9885e3378d8c9d26d4301fb30dd68c1434f0d cleanup: failed to unmount secrets: invalid argument"
Aug 28 05:28:36 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: time="2019-08-28T05:28:36.217659630Z" level=warning msg="67e0bc924e55e04c08a546ddae2628524e1c4f6dc8630918965c8046d5a80c73 cleanup: failed to unmount secrets: invalid argument"
Aug 28 05:28:36 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: time="2019-08-28T05:28:36.422454179Z" level=warning msg="273285690eee8634c1053c39ea538a1e92627769540e8e10b8b1413822356771 cleanup: failed to unmount secrets: invalid argument"
Aug 28 05:28:36 minikube-z2voh4hnkl44-master-0.novalocal dockerd-current[2637]: time="2019-08-28T05:28:36.623369498Z" level=warning msg="7bdb93ac6dfeeb684aa34132581b5c6b14bc4d7e856ba070cb288925ac56e36c cleanup: failed to unmount secrets: invalid argument"

==> container status <==
sudo: crictl: command not found
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> dmesg <==
[ +16.761920] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.038940] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.293389] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.070031] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +5.144054] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Aug28 02:09] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.329175] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.072427] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.088902] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.027655] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.153072] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.409058] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.071498] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.280593] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.025590] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Aug28 02:10] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Aug28 02:41] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.080977] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.238542] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.110842] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.062707] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.049422] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.271200] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.183442] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.134116] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +1.069695] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Aug28 02:42] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[Aug28 05:00] hrtimer: interrupt took 8295629 ns
[Aug28 05:27] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)
[  +0.245435] SELinux: mount invalid.  Same superblock, different security settings for (dev mqueue, type mqueue)

==> kernel <==
 05:31:46 up  4:14,  2 users,  load average: 0.45, 0.53, 0.54
Linux minikube-z2voh4hnkl44-master-0.novalocal 5.1.16-200.fc29.x86_64 #1 SMP Wed Jul 3 16:03:17 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Fedora 29.20190708.0 (Atomic Host)"

==> kubelet <==
-- Logs begin at Wed 2019-08-28 01:17:08 UTC, end at Wed 2019-08-28 05:31:46 UTC. --
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 41.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22120]: F0828 05:31:44.979432   22120 server.go:253] unable to load client CA file /var/lib/minikube/certs/ca.crt: open /var/lib/minikube/certs/ca.crt: no such file or directory
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 28 05:31:44 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: kubelet.service: Failed with result 'exit-code'.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 42.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: Started kubelet: The Kubernetes Node Agent.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal kubelet[22139]: F0828 05:31:45.734960   22139 server.go:253] unable to load client CA file /var/lib/minikube/certs/ca.crt: open /var/lib/minikube/certs/ca.crt: no such file or directory
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Aug 28 05:31:45 minikube-z2voh4hnkl44-master-0.novalocal systemd[1]: kubelet.service: Failed with result 'exit-code'.

</details>

**The operating system version**:
Fedora-AtomicHost-29-20190708.0.x86_64 from https://dl.fedoraproject.org/pub/alt/atomic/stable/Fedora-29-updates-20190708.0/AtomicHost/x86_64/images/Fedora-AtomicHost-29-20190708.0.x86_64.qcow2

**Comment by afbjorklund** [comment]
Weird that the error message was obfuscated, missing an "at".
`Error parsing private key: decodedSignerKey.Bytes`

But it sems like `x509.ParseCertificate` does not like your cert.
https://golang.org/pkg/crypto/x509/#ParseCertificate

**Comment by piersharding** [comment]
Hi  @afbjorklund  -  thanks for taking a look.
I think I have at least solved it in part.  The keys generated by the Magnum CA are in PKCS8 format - I have converted it to the expected PKCS1 format with `openssl rsa -in  ${cert_dir}/ca-pkcs8.key -out  ${cert_dir}/ca.key`  (found something about it here https://stackoverflow.com/questions/20065304/differences-between-begin-rsa-private-key-and-begin-private-key).
This has enabled me to now successfully run `minikube start` and get the KUBECONFIG credentials via `openstack coe cluster config`.
 
Thanks,
Piers.
