### ISSUE TITLE
Minikube VM crashed due to VBoxManage code NS_ERROR_FAILURE (0x80004005)

### ISSUE THREAD

**Issue by atulksigma** [kubernetes/minikube#5227]
**The exact command to reproduce the issue**: 
'minikube delete' followed by 'minikube start' 

**The full output of the command that failed**:<details>
> (base) ➜  ~ minikube delete
> 🔥  Deleting "minikube" in virtualbox ...
> 💔  The "minikube" cluster has been deleted.
> (base) ➜  ~ minikube start 
> 😄  minikube v1.3.1 on Ubuntu 18.04
> 🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
> E0829 17:02:21.051902    7516 start.go:723] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
> VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
> 
> 💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
> VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
> 
> 😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> 👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**The output of the `minikube logs` command**:<details>
> (base) ➜  ~ minikube logs
> 💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused
> 
> 😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> 👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**The operating system version**: Ubuntu Bionic 18.04.3 LTS

**Comment by atulksigma** [comment]
I am running it on HP 440 Laptop where virtualization technology is enabled in BIOS. I have tried deleting .minikube folder as also system restart and virtualbox reinstall. I had managed to run it earlier in Ubuntu 16.4 LTS on same machine. In between, I have upgraded machine to Ubuntu 18.04 and then trying again today only.

System has two network interfaces for virtualbox, vboxnet0 (enabled, 192.168.99.1/24) and vboxnet1 (diasbled, 192.168.33.1/24).

![image](https://user-images.githubusercontent.com/17249013/63938139-b9e69880-ca81-11e9-8d82-b85450017d79.png)

Virtualbox (Version 6.0.10 r132072 (Qt5.9.5)) GUI starts fine and shows no error.

**Comment by atulksigma** [comment]
When I tried to create a new ubuntu VM in virtualbox 6.01, I was getting error related to mismtached kernal module for virtulabox installation like the issue described in https://askubuntu.com/questions/837427/virtualbox-kernel-modules-do-not-match-this-version-of-virtualbox 
 
I removed all the virtualbox packages through below command
> sudo apt-get remove --purge 'virtualbox*'

Afterwards, I ran "sudo apt-get install virtualbox" which brought in Virtualbox 5.2.* . Minikube is working now. Maintainers can close the ticket now as I do not have enough time to pursue RCA for inconsitency between minikube 1.3.1 and virtualbox 6.0.10 on Ubuntu 18.04 LTS.

**Comment by tstromberg** [comment]
I'm bummed that you had to fight VirtualBox, but glad to hear that you got it sorted out. Thanks for sharing!
