### ISSUE TITLE
brew command(s) for installing the hyperkit driver needs to be changed

### ISSUE THREAD

**Issue by dougpagani** [kubernetes/minikube#5231]
`brew install hyperkit` will not work alone because minikube needs additionally on $PATH: `docker-machine-driver-hyperkit`. Invoking together:

`brew install docker-machine-driver-hyperkit`
`brew install hyperkit` 

It will work as intended.

https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/#hyperkit-installation

**Comment by tstromberg** [comment]
This is intentional - and related to #3939

minikube has shipped it's own more robust hyperkit driver for a number of years, which isn't found in brew. This is why the installation documentation recommends installing the binary directly: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/#driver-installation

We are working on upstreaming our changes so that the version in brew gets all of the necessary reliability improvements and can be recommended once again for general use.

**Comment by gWOLF3** [comment]
@tstromberg 

it's a bit confusing, as of right now - the home brew formulae for installing this driver actually does not point to minikube: https://formulae.brew.sh/formula/docker-machine-driver-hyperkit. 

Instead, it redirects to `https://github.com/machine-drivers/docker-machine-driver-hyperkit` , which is not an official repo, and it not even very actively maintained, still on version `1.0`. This may be a good thing to report to homebrew, as would be nice to have an "official" package released from minikube, if indeed you are the team which is maintaining future releases of this package.

**Comment by gWOLF3** [comment]
Btw- these docs you referenced, where do they recommend installing the docker-machine-driver binary directly? https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/#driver-installation

All i see is homebrew install instructions for hyperkit, and nothing about the additional machine driver package.

**Comment by gWOLF3** [comment]
Another thing to note:

when creating hyperkit vm with docker-machine from latest `docker-machine-driver-hyperkit` from minikube (installed with curl command v1.4) : I get the below error:

`Error creating machine: Error in driver during machine creation: extracting kernel: unable to find file /boot/bzimage`

HOWEVER, when using brew install, which points to bit "outdated binary" as referenced before... I actually get further, but run into the DHCP config error... 

This seems interesting, and it seems like support for docker machine command line is not supported.

**Comment by HafidElhafa** [comment]
Error: hyperkit: An unsatisfied requirement failed this build
