### ISSUE TITLE
MountVolume.SetUp failed for volume: couldn't propagate object cache: timed out waiting for the condition

### ISSUE THREAD

**Issue by BZM708** [kubernetes/minikube#5235]
< I have a problem after exposing an image in kubernetes.  As soon as I checked the minikube dashboard an error occurred. Later on when I back to minikube dashboard later it was working fine without error. >

**kubectl expose deployment hello-node --type=LoadBalancer --port=8080**:

from minikube dashboard this error was found on the pod for the image I exposed:

MountVolume.SetUp failed for volume "default-token-kd9zk" : couldn't propagate object cache: timed out waiting for the condition

<this error is gone later - Why did this happen?>

minikube version: v1.2.0
ubuntu 18.04

**Comment by tstromberg** [comment]
I'm not sure. Do you mind upgrading to minikube v1.3.1, and including the output of `minikube logs`?

**Comment by BZM708** [comment]
I used this syntax to install latest minikube in ubuntu:

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_1.3.1.deb \
 && sudo dpkg -i minikube_1.3.1.deb

However I am still stuck with the old version of minikube.

**Comment by Teeina** [comment]
Faced a similiar problem while installing other services. Installing Minikube with the latest code:
 curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
   && sudo install minikube-linux-amd64 /usr/local/bin/minikube

Any ideas on the problem? Thanks

**Comment by tstromberg** [comment]
I'm still unclear if this is a red herring or not. I imagine this step should retry?

That said, we should get to the bottom of this. Help wanted!

**Comment by tstromberg** [comment]
As best as I can tell, this is a relatively benign bug, as the operation is retried. It may represent a loaded down apiserver.

Related upstream issue: https://github.com/kubernetes/kubernetes/issues/70044

**Comment by srflaxu40** [comment]
Does not work on minikube 1.5 or k8s 1.16 either

**Comment by srflaxu40** [comment]
I don't think the custom image stuff is working at all.  Even if I do a `docker tag` on the official image it still croaks

**Comment by korablin** [comment]
still relative with minikube 1.5.1
