### ISSUE TITLE
Upgrade Toolbox fedora version

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#5239]
Currently we are using `fedora:29`, should upgrade to `fedora:30` (or even `fedora:latest`)

```
TOOLBOX_DOCKER_IMAGE=fedora
TOOLBOX_DOCKER_TAG=29
```
We could also merge rkt/podman/systemd-nspawn with upstream, or at least get the bug fixes:

https://github.com/coreos/toolbox
https://coreos.com/os/docs/latest/install-debugging-tools.html

---

Can do this with #5237 
Similar issue to ~#3058~

_I think we will keep with Fedora 30 and using systemd-nspawn, rather than latest and podman_
https://en.wikipedia.org/wiki/Fedora_version_history (this has the same life-span as the other LTS)

**Comment by afbjorklund** [comment]
We might also bring back docker support, for environments where podman is not available.

https://github.com/coreos/toolbox/commit/35fe466b20a4fa743a43b5f96369a58bdb05b932

``` diff
-	docker pull "${TOOLBOX_DOCKER_IMAGE}:${TOOLBOX_DOCKER_TAG}"
-	docker create --name=${machinename} "${TOOLBOX_DOCKER_IMAGE}:${TOOLBOX_DOCKER_TAG}" /bin/true
-	docker export ${machinename} | sudo tar -x -C "${machinepath}" -f -
-	docker rm ${machinename}
-	sudo touch ${osrelease}
+	riid=$(rkt --insecure-options=image fetch "docker://${TOOLBOX_DOCKER_IMAGE}:${TOOLBOX_DOCKER_TAG}")
+	sudo rkt image extract --overwrite --rootfs-only "${riid}" "${machinepath}"
+	rkt image rm "${riid}"
+	sudo touch "${osrelease}"
```

Could also consider contributing the podman support upstream, even if they have moved on.

``` diff
@@ -50,17 +50,13 @@
 	sudo chown "${USER}:" "${machinepath}"
 
 	if [[ -n "${have_docker_image}" ]]; then
-		riid=$(sudo --preserve-env rkt --insecure-options=image fetch "docker://${TOOLBOX_DOCKER_IMAGE}:${TOOLBOX_DOCKER_TAG}")
-		sudo --preserve-env rkt image extract --overwrite --rootfs-only "${riid}" "${machinepath}"
-		sudo --preserve-env rkt image rm "${riid}"
+		piid=$(sudo --preserve-env podman pull "docker://${TOOLBOX_DOCKER_IMAGE}:${TOOLBOX_DOCKER_TAG}")
+		pcid=$(sudo --preserve-env podman create "${piid}")
+		mnt=$(sudo --preserve-env podman mount "${pcid}")
+		sudo --preserve-env rsync -ax "${mnt}"/ "${machinepath}"/
+		sudo --preserve-env podman unmount "${pcid}"
+		sudo --preserve-env podman rm "${pcid}"
+		sudo --preserve-env podman rmi "${piid}"
 	else
 		echo "Error: No toolbox filesystem specified." >&2
 		exit 1
```

It is a bit uncertain how many are using `toolbox` with minikube anyway ?

Something seems broken after the rootfs->tmpfs upgrade, will investigate...

**Comment by tstromberg** [comment]
I'm open to the toolbox removal: I suspect it is rarely used, in part because it's spent such a long duration broken.

That said, I'll also accept PR's to upgrade it. If we are to keep this feature, it should get an integration test, even if it's just a simple assertion that one can run toolbox & install a yum package.

**Comment by afbjorklund** [comment]
> Something seems broken after the rootfs->tmpfs upgrade, will investigate...

The error was after upgrading systemd (237 -> 240), **not** after upgrading filesystem.

Upgrading the toolbox worked fine, should just tidy up the scripts and create a PR.

```
$ toolbox
Spawning container docker-fedora-30 on /var/lib/toolbox/docker-fedora-30.
Press ^] three times within 1s to kill container.
[root@minikube ~]# more /etc/fedora-release 
Fedora release 30 (Thirty)
[root@minikube ~]# logout
Container docker-fedora-30 exited successfully.
$ 
```

Will look at the other systemd failure when doing the buildroot upgrade (#5237)

Something about `systemd-nspawn` and system bus, not the `--share-system`
