### ISSUE TITLE
[make] Failed to connect to git.apache.org

### ISSUE THREAD

**Issue by xmnlab** [kubernetes/minikube#5245]
**The exact command to reproduce the issue**:

'make'

v1.3.1

**The full output of the command that failed**:<details>

```
go: git.apache.org/thrift.git@v0.0.0-20180902110319-2566ecd5d999: git fetch -f origin refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /mnt/sda1/storage/miniconda/conda-bld/minikube_1567440363550/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/pkg/mod/cache/vcs/83dba939f95a790e497d565fc4418400145a1a514f955fa052f662d56e920c3e: exit status 128:
        fatal: no es posible acceder 'https://git.apache.org/thrift.git/':Failed to connect to git.apache.org port 443: Expiró el tiempo de conexión

```

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

Linux 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by alexeadem** [comment]
same issue
can't connect to go: finding git.apache.org/thrift.git v0.0.0-20180902110319-2566ecd5d999

**Comment by alexeadem** [comment]
Fixed by
diff --git a/go.mod b/go.mod
index d1e861707..83ce03416 100644
--- a/go.mod
+++ b/go.mod
@@ -83,6 +83,7 @@ require (
 )
 
 replace (
+       git.apache.org/thrift.git => github.com/apache/thrift v0.0.0-20180902110319-2566ecd5d999
        k8s.io/api => k8s.io/kubernetes/staging/src/k8s.io/api v0.0.0-20190623232353-8c3b7d7679cc
        k8s.io/apiextensions-apiserver => k8s.io/kubernetes/staging/src/k8s.io/apiextensions-apiserver v0.0.0-20190623232353-8c3b7d7679cc
        k8s.io/apimachinery => k8s.io/kubernetes/staging/src/k8s.io/apimachinery v0.0.0-20190623232353-8c3b7d7679cc

**Comment by xmnlab** [comment]
thanks for the feedback @alexeadem !

I fixed that using the same approach 

- https://github.com/conda-forge/staged-recipes/pull/9394/files#diff-4048bd13e6e1d967022842c648548802
- https://github.com/conda-forge/staged-recipes/pull/9394/files#diff-cc47793fbfd5030414e4b40743e13d20

I can open a PR for that as well.
