### ISSUE TITLE
ignore-preflight-errors

### ISSUE THREAD

**Issue by laosuaidami** [kubernetes/minikube#5246]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by tstromberg** [comment]
感谢您的报告。 您能否提供以下信息，以便我们为您提供帮助：

- **重现问题所需的命令**
- **失败的命令的完整输出*
- **`minikube logs`命令的输出**

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
