### ISSUE TITLE
Expose release_notes helper as go sub-module

### ISSUE THREAD

**Issue by corneliusweig** [kubernetes/minikube#5252]
The release notes script in https://github.com/kubernetes/minikube/blob/3c0dc9d878aba31c93087ffbcb924008f75b737c/hack/release_notes/listpullreqs.go#L1 is a very useful helper. I found various copies of this on github, but I think it originates from here. Now we would like to use this script in `krew.dev` as well (see https://github.com/kubernetes-sigs/krew/pull/326). However, we can't really maintain this and we would not receive updates if we copy the script into our repository.

Would you therefore be open to expose this helper as a sub-module, so that it can be installed with `go get github.com/kubernetes/minikube/hack/release_notes` as a standalone tool? This would mean to make the `org` and `repo` variable configurable with CLI flags. I'd be happy take that up.

**Comment by tstromberg** [comment]
I believe @balopat was the original author.

I agree about the tools usefulness. I'd be happy to accept any changes to it, but I personally think it should just be forked and brought into it's own GitHub repo in some random project to accept improvements in. Interested in inheriting it?

**Comment by corneliusweig** [comment]
@balopat If you are the original author, do you have a preference where this tool should live? I can move it to my github space, but I don't want to steal your work :eyes:

**Comment by tstromberg** [comment]
@balopat - any thoughts?

**Comment by balopat** [comment]
Hey @cornelius, thank you for offering to maintain this piece of code, that is great! Feel free to move it to your own Github space, I'd love to have a small credit that it was originally written by me for minikube and Skaffold, if that's not a big problem. Otherwise I am more than happy to actually use it from your fork and contribute there!

**Comment by corneliusweig** [comment]
Hey @balopat, that's awsome! I played a little with `git filter-branch` so that all the original commits are preserved. It currently sits in a private repo which you should have received an invite to. If this looks good to you, I'm happy to go forward and make this public.

**Comment by tstromberg** [comment]
@corneliusweig - Let me know when your repo is public so that we can point minikube to it as well. Thank you!
