### ISSUE TITLE
  kubectl proxy: proxy start: fork/exec /usr/local/bin/kubectl: exec format error

### ISSUE THREAD

**Issue by ihml** [kubernetes/minikube#5256]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
I think you may have a  corrupt or invalid copy of kubectl installed. Do you mind sharing the output of the following commands:

- `uname -a`
- `file /usr/local/bin/kubectl`
- `/usr/local/bin/kubectl version --client`

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

**Comment by adi2c** [comment]
-bash: /usr/local/bin/kubectl: cannot execute binary file: Exec format error


how to resolve
