### ISSUE TITLE
v0.35.0 w/ proxy: Waiting for pods: apiserver!   Error restarting cluster

### ISSUE THREAD

**Issue by abhishekkarigar** [kubernetes/minikube#5257]
$ minikube start --vm-driver=virtualbox --docker-env HTTP_PROXY=http://x.x.x.x:8080 --docker-env HTTPS_PROXY=http://x.x.x.x:8080

minikube version: v0.35.0

**output**:

Waiting for pods: apiserver!   Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

**Comment by tstromberg** [comment]
v0.35.0 is quite old. Do you mind upgrading your version of minikube to v1.3.1 or higher, running `minikube delete`, and see if the issue still occurs?

If so, please attach the output of:

`minikube logs`

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
