### ISSUE TITLE
Error: connection reset by peer

### ISSUE THREAD

**Issue by imathews** [kubernetes/minikube#526]
**Minikube version** (use `minikube version`):
0.7.1

**Environment**:
- **OS**: OSX 10.11.6
- **VM Driver**: virtualbox
- **Docker version**: 1.11.1
- **kubectl version**: 1.3.0
- **Install tools**: OS X binary package

**What happened**:
After minikube has been running for ~15min (and I've been running `kubectl logs -f <POD>`), I get the error 

```
error: read tcp 192.168.99.1:55694->192.168.99.100:8443: read: connection reset by peer
```

After this, kubectl cannot connect to the minikube cluster, and I have to run `minikube start` to reconnect it. Somewhat bizarrely, when I now get the pods of this cluster, I see that several of them have "Completed", but there's no information in their logs that would have explained why the process has exited:

```
NAME                            READY     STATUS      RESTARTS   AGE
app-3673095501-uyfel            1/1       Running     0          31m
nginx-42881224-hz99r            0/1       Completed   0          31m
postgres-2157035252-7n01i       1/1       Running     0          31m
redis-master-3335561757-7z5m1   0/1       Completed   0          31m
redis-slave-4068038548-55ick    0/1       Completed   0          31m
redis-slave-4068038548-mxe26    0/1       Completed   0          31m
```

Most bizarrely, this is only happening on my computer; two of my colleagues' computers, in identical environments (and with comparable specs), aren't having this problem at all. I tried upgrading to minikube 0.8 / kubectl 1.3.5, but the problem persisted. I imagine this has something to do with the setup of my particular machine, but am at a loss for how to go about debugging this — any ideas / help would be greatly appreciated. 

**How to reproduce it** (as minimally and precisely as possible):
This is the tricky part, as I can't seem to reproduce it outside of my machine, and even then it's somewhat random. I should note that I run `minikube start --memory=2048 --cpus=2` to get things up and running.

**Comment by imathews** [comment]
@dlorenc, see attached. Looking through the logs, I'm wondering if this has something to do with volumes?

[bin_minikube_logs.txt](https://github.com/kubernetes/minikube/files/438170/bin_minikube_logs.txt)

**Comment by dlorenc** [comment]
Is this still an issue? Sorry for the delay.

**Comment by jack-evans** [comment]
that error you're seeing: 
```
error: read tcp 192.168.99.1:55694->192.168.99.100:8443: read: connection reset by peer
```
I was getting loads whenever I was doing a `docker pull` within the minikube environment however after looking online it seems to be a VirtualBox issue. I downgraded my VirtualBox from 5.1.18 to 5.0.20 (everyone said this version was working) and my issue was fixed.

What version are you running?
