### ISSUE TITLE
Get https:/ /k8s.gcr.io/v2/: dconnectex: failed because the connected party did not properly respond

### ISSUE THREAD

**Issue by javaora** [kubernetes/minikube#5279]
**重现问题所需的命令**：
minikube start
**失败的命令的完整输出**：<details>
C:\Windows\system32>minikube start
* minikube v1.3.1 on Microsoft Windows 7 Enterprise Service Pack 1 6.1.7601 Buil
d 7601
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E0906 10:29:05.347128   63532 start.go:558] Error caching images:  Caching image
s for kubeadm: caching images: caching image C:\Users\robin\.minikube\cache\imag
es\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13: fetching remote image: Get https:/
/k8s.gcr.io/v2/: dial tcp 64.233.188.82:443: connectex: A connection attempt fai
led because the connected party did not properly respond after a period of time,
 or established connection failed because connected host has failed to respond.
* Unable to load cached images: loading cached images: loading image C:\Users\ro
bin\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1: Creat
eFile C:\Users\robin\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisio
ner_v1.8.1: The system cannot find the file specified.
* 拉取镜像 ...
* 正在启动 Kubernetes ...
*
X Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/l
ib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifest
s,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-sched
uler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvaila
ble--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-ku
bernetes-manifests-etcd.yaml,Port-10250,Swap
[init] Using Kubernetes version: v1.15.2
[preflight] Running pre-flight checks
        [WARNING Service-Docker]: docker service is not enabled, please run 'sys
temctl enable docker.service'
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup
 driver. The recommended driver is "systemd". Please follow the guide at https:/
/kubernetes.io/docs/setup/cri/
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 's
ystemctl enable kubelet.service'
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your inte
rnet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config
 images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.15.
2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: req
uest canceled while waiting for connection (Client.Timeout exceeded while awaiti
ng headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manag
er:v1.15.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/
http: request canceled while waiting for connection (Client.Timeout exceeded whi
le awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.15.
2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: req
uest canceled while waiting for connection (Client.Timeout exceeded while awaiti
ng headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.15.2: o
utput: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request
 canceled while waiting for connection (Client.Timeout exceeded while awaiting h
eaders)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Er
ror response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled
 while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.3.10: output:
Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request cancel
ed while waiting for connection (Client.Timeout exceeded while awaiting headers)

, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.3.1: output
: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canc
eled while waiting for connection (Client.Timeout exceeded while awaiting header
s)
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with
`--ignore-preflight-errors=...`

: Process exited with status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear fro
m you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
windows 7 & virtual box 6

**Comment by tstromberg** [comment]
我相信中国的伟大防火墙可能会干扰您访问Kubernetes图像。

您可以使用以下命令配置代理：https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

要测试代理是否有效，您可以尝试：

env http_proxy=<address> https_proxy=<address> curl https://k8s.gcr.io/robots.txt

请让我知道这可不可以帮你。
