### ISSUE TITLE
MiniKube and NetworkPolicy

### ISSUE THREAD

**Issue by andrewkrug** [kubernetes/minikube#528]
Hello,
I believe this is a feature request.  Can you add a flag to minikube deployment to allow the addition of network overlays like weave, calico, romana, canal etc... Currently this is the only feature not available in the stack that I have available in a full CoreOS deployment.  

That would be the bees knees in terms of developing apples to apples with kubernetes full stacks.

**Comment by aaron-prindle** [comment]
Could you clarify what the current issue is with using weave, calico, etc. on Minikube and perhaps what this flag would need to do in order to get these tools to work?  Sorry, I am not too familiar with the network overlay projects you mentioned.  Thanks!

**Comment by andrewkrug** [comment]
Weave / Calico ( really calico is what I want ) can both be installed by hand.  But this would be painful for developers.  Since Calico is a first class kubernetes citizen via integration with Network Policy it would be awesome to have available in minikube.

Sure. In the core-os configuration see the use case https://github.com/coreos/coreos-kubernetes/blob/master/multi-node/generic/controller-install.sh around line 184.  It's basically a modification to controller and workers that stands up a different networking service.

**Comment by aaron-prindle** [comment]
Closing, minikube now supports the --network-plugin flag
