### ISSUE TITLE
VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes 

### ISSUE THREAD

**Issue by amitkhomane** [kubernetes/minikube#5282]
**The exact command to reproduce the issue**: minikube start

**The full output of the command that failed**:<details>
😄  minikube v1.3.1 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0906 17:33:32.193811   14439 start.go:723] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.314377 Power up failed (vrc=VERR_VMX_MSR_ALL_VMX_DISABLED, rc=NS_ERROR_FAILURE (0X80004005))

💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.314377 Power up failed (vrc=VERR_VMX_MSR_ALL_VMX_DISABLED, rc=NS_ERROR_FAILURE (0X80004005))

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
**ubuntu 18.04**   4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tstromberg** [comment]
What kind of machine is this on? Virtualization appears to be disabled in BIOS - you will need to enable it for VirtualBox to function:

`VBoxManage: error: VT-x is disabled in the BIOS for all CPU modes `

Alternatively, if Ubuntu is already running within a VM, you may use the `none` driver: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

**Comment by amitkhomane** [comment]
Yes, thank you for solution. This been resolved now.
