### ISSUE TITLE
The vboxdrv kernel module is not loaded.

### ISSUE THREAD

**Issue by rsurendraidexcel** [kubernetes/minikube#5291]
rsurendra@idexcel.internal@laplen024:~$ minikube start
😄  minikube v1.3.1 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0907 17:32:48.164258   21267 start.go:723] StartHost: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The vboxdrv kernel module is not loaded. Either there is no module\n         available for the current kernel (5.0.0-27-generic) or it failed to\n         load. Please recompile the kernel module and install it by\n\n           sudo /sbin/vboxconfig\n\n         You will not be able to start VMs until this problem is fixed.\n6.0.12r133076". Please upgrade at https://www.virtualbox.org

💣  Unable to start VM
❌  Error: [VBOX_DRV_NOT_LOADED] create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The vboxdrv kernel module is not loaded. Either there is no module\n         available for the current kernel (5.0.0-27-generic) or it failed to\n         load. Please recompile the kernel module and install it by\n\n           sudo /sbin/vboxconfig\n\n         You will not be able to start VMs until this problem is fixed.\n6.0.12r133076". Please upgrade at https://www.virtualbox.org
💡  Suggestion: Run 'sudo modprobe vboxdrv' and reinstall VirtualBox if it fails.
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/4043

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
It appears that VirtualBox is not fully installed. Did you attempt the suggestion it provided?

`Run 'sudo modprobe vboxdrv' and reinstall VirtualBox if it fails.`

If so, I'm curious what the outcome of the command was.

**Comment by John-Dormevil** [comment]
Try to:
- Deactivate Secure Boot from your bios system;
- Then run `sudo /sbin/vboxconfig` in case you install and use virtualbox 6+
- Then `minikube start`

**Comment by tstromberg** [comment]
We've improved the advice in minikube v1.4 when this occurs:

`Reinstall VirtualBox and reboot. Alternatively, try the kvm2 driver: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/`

Hopefully this helps.
