### ISSUE TITLE
StartHost: create: bootstrapping certificates: Failed to decode PEM data

### ISSUE THREAD

**Issue by qasimgit** [kubernetes/minikube#5293]
$ minikube start
😄  minikube v1.3.1 on Ubuntu 19.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0908 11:40:08.350190    2398 start.go:723] StartHost: create: bootstrapping certificates: Failed to decode PEM data

💣  Unable to start VM: create: bootstrapping certificates: Failed to decode PEM data

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by qasimgit** [comment]
$ minikube start
😄  minikube v1.3.1 on Ubuntu 19.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0908 11:40:08.350190    2398 start.go:723] StartHost: create: bootstrapping certificates: Failed to decode PEM data

💣  Unable to start VM: create: bootstrapping certificates: Failed to decode PEM data

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by qasimgit** [comment]
how to resolve this i already reinstall ubuntu and reintall minikube and docker

**Comment by tstromberg** [comment]
Do you mind sharing the output of:

`minikube start --alsologtostderr -v=8`

I'm curious what certificate it's breaking on.

**Comment by qasimgit** [comment]
this is the output of     $ minikube start --alsologtosderr -v=8


(output)

$ minikube start --alsologtostderr -v=8
I0908 19:16:42.490031    4576 notify.go:124] Checking for updates...
I0908 19:16:43.138736    4576 start.go:224] hostinfo:
{"hostname":"qasim-Satellite-C55t-B","uptime":15921,"bootTime":1567954282,"procs":292,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"19.04","kernelVersion":"5.0.0-13-generic","virtualizationSystem":"kvm","virtualizationRole":"host","hostid":"993cd73a-642d-46b0-8689-22b934dc451f"}
I0908 19:16:43.139518    4576 start.go:234] virtualization: kvm host
😄  minikube v1.3.1 on Ubuntu 19.04
I0908 19:16:43.140068    4576 downloader.go:59] Not caching ISO, using
https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso
I0908 19:16:43.140160    4576 start.go:922] Saving config:
{
    "MachineConfig": {
        "KeepContext": false,
        "MinikubeISO": "
https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso",
        "Memory": 2000,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "virtualbox",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "",
        "KVMNetwork": "default",
        "KVMQemuURI": "qemu:///system",
        "KVMGPU": false,
        "KVMHidden": false,
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "NoVTXCheck": false,
        "DNSProxy": false,
        "HostDNSResolver": true
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.15.2",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    }
}
I0908 19:16:43.140386    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/kube-controller-manager:v1.15.2 at
/home/qasim/.minikube/cache/images/
k8s.gcr.io/kube-controller-manager_v1.15.2
I0908 19:16:43.140390    4576 cache_images.go:286] Attempting to cache
image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at
/home/qasim/.minikube/cache/images/
gcr.io/k8s-minikube/storage-provisioner_v1.8.1
I0908 19:16:43.140527    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.140555    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/kube-apiserver:v1.15.2 at
/home/qasim/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.15.2
I0908 19:16:43.140595    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/kube-scheduler:v1.15.2 at
/home/qasim/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.15.2
I0908 19:16:43.140567    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.140670    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.140694    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.140700    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at
/home/qasim/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I0908 19:16:43.140771    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.140799    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.140945    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/pause:3.1 at /home/qasim/.minikube/cache/images/
k8s.gcr.io/pause_3.1
I0908 19:16:43.140996    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at
/home/qasim/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I0908 19:16:43.141012    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/kube-proxy:v1.15.2 at /home/qasim/.minikube/cache/images/
k8s.gcr.io/kube-proxy_v1.15.2
I0908 19:16:43.141078    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.141107    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.141129    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at
/home/qasim/.minikube/cache/images/
k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
I0908 19:16:43.141193    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.141219    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.141240    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.141267    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.141367    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/etcd:3.3.10 at /home/qasim/.minikube/cache/images/
k8s.gcr.io/etcd_3.3.10
I0908 19:16:43.141389    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.141415    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.141440    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/coredns:1.3.1 at /home/qasim/.minikube/cache/images/
k8s.gcr.io/coredns_1.3.1
I0908 19:16:43.141500    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.140675    4576 cluster.go:93] Machine does not exist...
provisioning new machine
I0908 19:16:43.141620    4576 cluster.go:94] Provisioning machine with
config: {KeepContext:false MinikubeISO:
https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso Memory:2000
CPUs:2 DiskSize:20000 VMDriver:virtualbox ContainerRuntime:docker
HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[]
RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch:
KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false
Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[]
NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false
HostDNSResolver:true}
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
I0908 19:16:43.141106    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at
/home/qasim/.minikube/cache/images/
k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0908 19:16:43.141543    4576 cache_images.go:286] Attempting to cache
image: k8s.gcr.io/kube-addon-manager:v9.0 at
/home/qasim/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
I0908 19:16:43.141595    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.142148    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.142184    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
Reading certificate data from /home/qasim/.minikube/certs/ca.pem
Decoding PEM data...
I0908 19:16:43.142389    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.142429    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.142544    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.142571    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.142612    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.142664    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:43.142740    4576 main.go:80] stdlog: keychain.go:109 Unable to
read "/home/qasim/.docker/config.json": open
/home/qasim/.docker/config.json: permission denied
I0908 19:16:43.142784    4576 main.go:80] stdlog: options.go:52 No matching
credentials were found, falling back on anonymous
I0908 19:16:44.152931    4576 cache_images.go:310] OPENING:
 /home/qasim/.minikube/cache/images/k8s.gcr.io/coredns_1.3.1
I0908 19:16:44.156695    4576 cache_images.go:310] OPENING:
 /home/qasim/.minikube/cache/images/
k8s.gcr.io/kube-controller-manager_v1.15.2
I0908 19:16:44.211484    4576 cache_images.go:310] OPENING:
 /home/qasim/.minikube/cache/images/
k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
I0908 19:16:44.478502    4576 cache_images.go:310] OPENING:
 /home/qasim/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.15.2
I0908 19:16:44.727472    4576 cache_images.go:310] OPENING:
 /home/qasim/.minikube/cache/images/
gcr.io/k8s-minikube/storage-provisioner_v1.8.1
I0908 19:16:44.849646    4576 cache_images.go:310] OPENING:
 /home/qasim/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I0908 19:16:45.009614    4576 cache_images.go:310] OPENING:
 /home/qasim/.minikube/cache/images/
k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I0908 19:16:45.013449    4576 cache_images.go:310] OPENING:
 /home/qasim/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
E0908 19:16:45.142534    4576 start.go:723] StartHost: create:
bootstrapping certificates: Failed to decode PEM data
I0908 19:16:45.143423    4576 utils.go:127] non-retriable error: create:
bootstrapping certificates: Failed to decode PEM data
W0908 19:16:45.143528    4576 exit.go:99] Unable to start VM: create:
bootstrapping certificates: Failed to decode PEM data

💣  Unable to start VM: create: bootstrapping certificates: Failed to
decode PEM data

😿  Sorry that minikube crashed. If this was unexpected, we would love to
hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

(kindly please get me solve this issue is shall be thankful to you)
Kind Regards

**Comment by tstromberg** [comment]
I'm not sure which PEM file libmachine is trying to verify at this point. Do you mind sharing the output of:

`grep "^--" ~/.minikube/certs/*.pem`

I'd also be curious if this workaround works:

`minikube delete`
`rm -Rf ~/.minikube/certs`

Thanks for the additional information!

**Comment by qasimgit** [comment]
now this comes

$ minikube start

😄  minikube v1.3.1 on Ubuntu 19.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0909 08:07:28.783842   17281 start.go:723] StartHost: create: precreate:
VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is
in the path

💣  Unable to start VM
❌  Error: [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make
sure VirtualBox is installed and VBoxManage is in the path
💡  Suggestion: Install VirtualBox, ensure that VBoxManage is executable
and in path, or select an alternative value for --vm-driver
📘  Documentation: https://www.virtualbox.org/wiki/Downloads
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3784
    ▪ https://github.com/kubernetes/minikube/issues/3776

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
@qasimgit - The error suggests that you should install VirtualBox. Have you done so?

**Comment by medyagh** [comment]
@qasimgit it appears to me your issue was solved and the second issue was virtualbox not being installed .

in the next version of minikube we will notify user nicer that they dont have the virtualbox or other hypervisor installed in more elegant way.

**Comment by yganchev** [comment]
@tstromberg Thanks a for providing this hint here. It helped me a lot!

**Comment by dobrevavictoria** [comment]
@tstromberg Thank you so much for the workaround! I had the same problem (with installed virtualbox and kvm drivers) and the commands you shared resolved it!
```
minikube delete
rm -Rf ~/.minikube/certs
```
