### ISSUE TITLE
Erro no minikube start

### ISSUE THREAD

**Issue by daavelar** [kubernetes/minikube#5298]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

</details>

**A saída do comando `minikube logs`**:<details>

</details>

**A versão do sistema operacional usado**:

**Comment by tstromberg** [comment]
Ainda não tenho uma maneira clara de replicar esse problema. Você se importa de adicionar alguns detalhes adicionais? Aqui estão informações adicionais que seriam úteis:

* A linha de comando exata `minikube start` usada
* A saída completa do comando `minikube start`, de preferência com` --alsologtostderr -v=8` para registro extra.
  * A saída completa dos `minikube logs`

Obrigado por compartilhar sua experiência!

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
