### ISSUE TITLE
Auto install helm

### ISSUE THREAD

**Issue by woodcockjosh** [kubernetes/minikube#5302]
Consider adding a feature to auto install helm. For example:

`minikube start -p hellokube --with-helm`

Helm is becoming a tool that is more and more used. Having to remember install it after each time a new minikube instance is launched is pretty annoying. Its like having to install composer after installing php or installing npm after installing node. While I can agree that not everyone uses helm it is used often enough to justify an option to auto install it.

**Comment by afbjorklund** [comment]
Can you do it as an add-on ?

**Comment by woodcockjosh** [comment]
Yes I suppose we could

**Comment by tstromberg** [comment]
I agree that it would be nice to have an --addons flag for startup, but I'm not sure about auto-installation of a host-side software package.

**Comment by afbjorklund** [comment]
Same old binary sadness as ever, as in: https://git.io/get_helm.sh

I know that Tiller is going away soon, but maybe you still need to run `helm init` anyway.

**Comment by woodcockjosh** [comment]
#5363 tested on darwin and linux both with virtualbox. I think the addon approach as @tstromberg suggested is a good solution while helm is still using tiller. @afbjorklund I could be wrong but since this is just installing tiller in the cluster I'm not sure that the host architecture matters.

**Comment by afbjorklund** [comment]
> @afbjorklund I could be wrong but since this is just installing tiller in the cluster I'm not sure that the host architecture matters.

Well, the architecture of tiller still matters but the deployment should take care of that (choosing the right image, normally `amd64`)

What I meant is that it is not really useful without also installing `helm`, and then the user is subject to the normal problem of installing binaries.

**Comment by tstromberg** [comment]
Does #5503 + the helm-tiller addon effectively solve this issue?

**Comment by woodcockjosh** [comment]
Closed with `helm-tiller` addon https://github.com/kubernetes/minikube/pull/5363
