### ISSUE TITLE
gvisor addon crashloop: open /tmp/gvisor/gvisor-containerd-shim.toml: no such file or directory

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5305]
While working on an integration test refactor, I noticed that the integration tests are broken at head. I was able to replicate the breakage using a basic command-line:

```
make
% ./out/minikube start --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock
😄  minikube v1.4.0-beta.0 on Debian rodete
🔥  Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
Running pre-create checks...
Creating machine...
...
📦  Preparing Kubernetes v1.16.0-beta.1 on containerd 1.2.8 ...
    ▪ opt containerd=/var/run/containerd/containerd.sock
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver etcd scheduler controller
🏄  Done! kubectl is now configured to use "minikube"
```

Then:

`minikube addons enable gvisor`

Gives you a pod that looks like this:

```
kube-system   gvisor                                  0/1     CrashLoopBackOff   4          2m14s
```

Pod logs show:

```
2019/09/09 20:30:53 Storing default config.toml at /tmp/config.toml
2019/09/09 20:30:53 Copying gvisor-containerd-shim.toml...
2019/09/09 20:30:53 copying config files: copying gvisor-containerd-shim.toml: getting contents of deploy/addons/gvisor/gvisor-containerd-shim.toml: open /tmp/gvisor/gvisor-containerd-shim.toml: no such file or directory
```

This host has no speciial cached images.. `minikube cache list` returns empty.

As an aside, I think that minikube as a team is a bit confused about how to properly handle integration testing gvisor. I get the feeling that we may be pre-release testing gvisor, by virtue of the docker build that happens in `common.sh`. It feels wrong to me?

/cc @ianlewis

**Comment by ianlewis** [comment]
Arg, OK. I'll do this as soon as I can.

**Comment by ianlewis** [comment]
I assume common.sh is this one? -> https://github.com/kubernetes/minikube/blob/master/hack/jenkins/common.sh

I don't think we are pre-release testing gVisor itself. The docker build in common.sh only builds the gvisor-addon binary AFAICT which should be fine. The gvisor-addon uses a fixed runsc version for the addon.

This may be just something that I missed in the integration tests logs for my PR. It's really hard to read the logs for those things and there are a lot of flaky tests so it's hard to trust them.

**Comment by ianlewis** [comment]
@tstromberg Do you have a link to where they are failing?

The gvisor-addon doesn't use gvisor-containerd-shim.toml anymore so I'm thinking it's using an old version of the gvisor-addon Docker image? A gvisor-addon image built since https://github.com/kubernetes/minikube/commit/cb5ebed001ba66ef84e99296d6e2dea406c3556f shouldn't produce this error message.

**Comment by busser** [comment]
This is still an issue in v1.4.0.

@ianlewis It looks to me like you're right: minikube is using an old version of the gvisor-addon Docker image. Building a new image from cb5ebed001ba66ef84e99296d6e2dea406c3556f (when you updated the gvisor addon) or from 8e138a7eea5546e61aead4e84f53a27fb5f2f298 (master at time of writing) fixes the issue for me.

I was only able to test this on my local machine.

How is the public gcr.io/k8s-minikube/gvisor-addon:latest image supposed to be updated?

**Comment by tstromberg** [comment]
@priyawadhwa - How does one update `gcr.io/k8s-minikube/gvisor-addon:latest`?

This should probably have user documentation on https://minikube.sigs.k8s.io/docs/contributing/ - I'd be happy to help make that happen if I can get the gist of the process.

**Comment by priyawadhwa** [comment]
So the gvisor addon basically starts a [pod](https://github.com/kubernetes/minikube/blob/master/deploy/addons/gvisor/gvisor-pod.yaml.tmpl) which enables gvisor on cluster. The pod runs an image built from [minikube/cmd/gvisor](https://github.com/kubernetes/minikube/tree/master/cmd/gvisor), and most of the code lives in [minikube/pkg/gvisor](https://github.com/kubernetes/minikube/tree/master/pkg/gvisor).

I just looked through and it looks like there isn't any sort of release pipeline set up for the gvisor image :fearful: There's a Makefile rule [push-gvisor-addon-image](https://github.com/kubernetes/minikube/blob/master/Makefile#L470) which I thought was called somewhere, but it looks like it isn't. Also somewhat related, I'd copied the structure of [push-storage-provisioner-image](https://github.com/kubernetes/minikube/blob/master/Makefile#L454), and it looks like there isn't any sort of release set up there.

I can definitely help set up some sort of release pipeline & write the docs, would you know what the easiest way to release the image might be? We use GCB triggers in Skaffold, but I'm not sure if that's an option here.

**Comment by tstromberg** [comment]
@priyawadhwa - Thanks for the feedback. I've pushed a new image and created a PR to add a doc based on the information you have provided. It is relatively rare for the gvisor packages to get updated, so in lieu of an automatic workflow being available, I'm OK with manual pushes in the short term. That said, GCB triggers would probably work just fine here.

I'll need to check to see if the new push resolves the problem we've been seeing.

**Comment by tstromberg** [comment]
Looks like a new image is all that it took. Thank you @priyawadhwa !
```
2019/09/26 00:03:34 Storing default config.toml at /tmp/config.toml
2019/09/26 00:03:34 Copying containerd config.toml with gvisor...
2019/09/26 00:03:34 Stopping rpc-statd.service...
2019/09/26 00:03:34 Restarting containerd...
2019/09/26 00:03:34 Starting rpc-statd...
2019/09/26 00:03:34 containerd restart complete
2019/09/26 00:03:34 gvisor successfully enabled in cluster
```
