### ISSUE TITLE
minikube ; Unable to load cached images: loading cached images: loading image /Users/mvensky/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.15.0

### ISSUE THREAD

**Issue by mvensky** [kubernetes/minikube#5306]
have been running minikube on Mac OS High Sierra using minikube start/stop/delete.

After a most recent shutdown, the above error started happening.

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.

Thank you for sharing your experience!

**Comment by mvensky** [comment]
Hello Thomas,

I totally understand; it was probably something with my local install 
that somehow got corrupted. A delete/reinstall fixed the problem. I wish 
I could be more helpful.

**Comment by tstromberg** [comment]
Thank you for the update!
