### ISSUE TITLE
v0.35 none: waiting for component=kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by arun0704** [kubernetes/minikube#5313]

**Comment by arun0704** [comment]
[root: /root]$ time minikube  start  --vm-driver none  --memory 4960 --kubernetes-version v1.13.4 --v=7 --extra-config=kubelet.cgroup-driver=cgroupfs --extra-config=apiserver.runtime-config=admissionregistration.k8s.io/v1alpha1=true
😄  minikube v0.35.0 on linux (amd64)
🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

⚠️  kubectl and minikube configuration will be stored in /root
⚠️  To use kubectl or minikube commands as your own user, you may
⚠️  need to relocate them. For example, to overwrite your own settings:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🔥  Creating none VM (CPUs=2, Memory=4960MB, Disk=20000MB) ...
Reading certificate data from /root/minikube/.minikube/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from /root/minikube/.minikube/certs/cert.pem
Decoding PEM data...
Parsing certificate...
📶  "minikube" IP address is 10.136.199.53
🌐  Found network options:
    ▪ HTTP_PROXY=10.158.100.6:8080
    ▪ HTTPS_PROXY=10.158.100.6:8080
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,10.53.32.237,dockerregistry.ims.nokia.com
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
    ▪ kubelet.cgroup-driver=cgroupfs
    ▪ apiserver.runtime-config=admissionregistration.k8s.io/v1alpha1=true
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

real	11m33.322s
user	0m5.953s
sys	0m2.340s

**Comment by tstromberg** [comment]
This is a really ancient version of minikube. Do you mind trying with v1.3.1, running `sudo minikube delete`, and then attaching the output of `minikube logs` if startup fails?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
