### ISSUE TITLE
docu: broken link

### ISSUE THREAD

**Issue by frederik-b** [kubernetes/minikube#5339]
**The exact command to reproduce the issue**:
go to https://github.com/kubernetes/minikube/blob/master/docs/offline.md and click the link

**The full output of the command that failed**:<details>
```
Not found
Oops! This page doesn't exist. Try going back to our home page.
```

</details>

**Comment by tstromberg** [comment]
Thanks for the report! This is now fixed: https://github.com/kubernetes/minikube/blob/master/docs/offline.md
