### ISSUE TITLE
minikube root volume full due to emptyDir

### ISSUE THREAD

**Issue by mikebryant** [kubernetes/minikube#535]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`):  v0.8.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 14.04.4
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikubeVM/config.json | grep DriverName`):virtualbox
- **Docker version** (e.g. `docker -v`): Docker version 1.12.0, build 8eab29e

**What happened**:
The minikube VM root volume ran out of space due to a large emptydir (~600MB)

**What you expected to happen**:
I expected to be able to store at least 15G or so of data, as the default VM disk size is 20GB

**How to reproduce it** (as minimally and precisely as possible):
Use an emptydir volume and write lots of data from a pod

**Anything else do we need to know**:
It looks like /var/lib/kubelet is kept on the root volume, and that's where kubelet stores emptydirs. Either the root volume needs to be bigger, or this needs to be symlinked onto the /mnt/sda1 volume, like docker etc.

**Comment by dlorenc** [comment]
We should put /var/lib/kubelet on the root dir.

**Comment by dlorenc** [comment]
ref #511
