### ISSUE TITLE
certs should be per-profile

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5353]
`SetupCerts` is not profile aware, and very racy.

It constantly overwrites the certificates every time you run `minikube start`, which is bad if two are started at the same time. We should make it so that clusters are updated to use per-profile certs to avoid raciness.

**Comment by tstromberg** [comment]
This has a WIP PR: https://github.com/kubernetes/minikube/pull/4968

**Comment by Kane-eNote** [comment]
I was running into this issue while trying to let users create their own test clusters at a shared box.

Is there a similar issue for the following files, which need to be separated as well?
```
/tmp/juju-kubeconfigUpdate
/tmp/juju-kube-config
```

In addition, is it safe using a shared user for now (e.g. via `sudo -u <user> minikube ...`) to manage different "profiles"?
As far as I understood from the code (from `juju/mutex_flock`), these files only get used for locking temporarily, correct?
May I also ask why these temporary files never actually seem to get deleted?
