### ISSUE TITLE
delete should be able to delete the `.minikube` folder (w/ a flag)

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#5358]
From https://github.com/kubernetes/minikube/pull/4980#issuecomment-531568673

`minikube delete` should have a switch/flag to delete the `.minikube` folder as well. This should ask for confirmation and display a warning before proceeding ahead.

/assign

**Comment by tstromberg** [comment]
I personally don't agree with this issue, but it's worth discussing. My main issue with it is:

- `minikube delete` is for deleting single clusters.
- `~/.minikube` is shared configuration and data files

Apps typically don't delete their own state folders except as part of uninstallation.

**Comment by blueelvis** [comment]
Agreed. Let's discuss. This could be added to the installation/uninstallation steps for sure.

Regarding the delete, I believe that we should have the flag. Nothing that the user will be defaulted to.

**Comment by SlurmMcKenzie** [comment]
In Apt Package Management (Debian) you have an extra option for deleting configuration: <code>--purge</code>. Would that fit?

**Comment by tstromberg** [comment]
@SlurmMcKenzie - Yes, that seems like a better behavior. I'd be happy to see a similar --purge flag to `minikube delete`.
