### ISSUE TITLE
status on git bash: Error getting host status: state: Failed to find the VM status

### ISSUE THREAD

**Issue by zaidqureshi2** [kubernetes/minikube#5359]
I installed minikube on my windows machine enabled with Hyper V. I already have docker installed on my computer. 

I started the minikube with the following command in *PowerShell*: `minikube start --vm-driver=hyperv --hyperv-virtual-switch "Default Switch" --memory=4096`

Please note I used the Default Switch instead of creating a new switch.

After the installation, in powershell:

<details>
PS C:\WINDOWS\system32> minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 172xxxxxxx

PS C:\WINDOWS\system32> minikube version
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
</details>

The issue I am having is when I run commands like `minikube status` or `minikube docker-env` or `minikube dashboard` they fail from Gitbash:
<details>

$ minikube status                                                                *                                                                                X Error getting host status: state: Failed to find the VM status                 *                                                                                * Sorry that minikube crashed. If this was unexpected, we would love to hear fro m you:                                                                             - https://github.com/kubernetes/minikube/issues/new/choose
--

$ minikube docker-env                                                            *                                                                                X Error getting host status: state: Failed to find the VM status                 *                                                                                * Sorry that minikube crashed. If this was unexpected, we would love to hear fro m you:                                                                             - https://github.com/kubernetes/minikube/issues/new/choose
--
</details>

But when I run those commands through powershell, they are successful.

<details>
PS C:\WINDOWS\system32> minikube docker-env
$Env:DOCKER_TLS_VERIFY = "1"
$Env:DOCKER_HOST = "tcp://172.17.205.130:2376"
$Env:DOCKER_CERT_PATH = "C:\Users\zqureshi\.minikube\certs"
# Run this command to configure your shell:
# & minikube docker-env | Invoke-Expression
</details>

Is this because I did the initialization through Powershell instead of Gitbash?

**Comment by tstromberg** [comment]
I wonder if your Git Bash process doesn't have high enough privileges to talk to Hyper-V?

Do you mind sharing this output?

` minikube docker-env --alsologtostderr -v=8`

**Comment by medyagh** [comment]
@zaidqureshi2 do you still have this issue ? if yes, do you mind please sharing the info tstromberg asked ?

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
