### ISSUE TITLE
Support in VM and pods for VRF (kernel module)

### ISSUE THREAD

**Issue by bradmwalker** [kubernetes/minikube#5360]
I'm porting a virtualized network testbed from a system container. A correct migration requires moving the network pod's interface and routes into a non-default VRF. A large number of network namespaces compose the virtual net. bradmwalker/wanmap#48

VRF is enabled in Ubuntu 18.04+ and Fedora 29+.

**The exact command to reproduce the issue**:
minikube ssh
$ zcat /proc/config.gz | grep CONFIG_NET_VRF

$ sudo ip link add vrf-cluster type vrf
RTNETLINK answers: Operation not supported

[brad@x220 ~]$ minikube version
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631

Minikube VM is freshly created with kvm2 driver.

**Comment by tstromberg** [comment]
Sounds good. Do you mind sending a PR over to enable this?

Example PR: https://github.com/kubernetes/minikube/pull/4340
Documentation: https://minikube.sigs.k8s.io/docs/contributing/iso/

**Comment by sharifelgamal** [comment]
This is still a good idea.
