### ISSUE TITLE
Increase survey visibility

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5365]
- Our surveys used to get ~5 responses per week until our new site launched a month ago
- Our average is now 0-1 responses per week: https://docs.google.com/spreadsheets/d/1o_QpUw_9amxrJCZ_RGC7Eo3yLWe5yFCGQ09JG655flc/edit#gid=594766049
- Traffic indications suggest that minikube usage has increased over this time

**Comment by blueelvis** [comment]
Just curious. How do you know that minikube usage has increased over this time? We don't have any kind of telemetry, right?

**Comment by tstromberg** [comment]
@blueelvis - The best we have for telemetry is download counts. I don't have good stats on the files stored in GCS, but we do for GitHub.

https://www.somsubhra.com/github-release-stats/

**Comment by medyagh** [comment]
I believe this issue was solved by the PR.
please re-open if not resolved.
