### ISSUE TITLE
hyperv: StartHost: start: exit status 1

### ISSUE THREAD

**Issue by WilsonGadekar** [kubernetes/minikube#5366]
I installed minikube and checked the version it is able to show it. but when i am trying to start minikube with the hyper-virtual-switch created it's giving the below error.

Command - 
minikube start - vm-driver hyperv - cpus 2 - memory=4096 - hyperv-virtual-switch "Minikube"

Output - 
* minikube v1.3.1 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
*

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the hyperv driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`
*

* Starting existing hyperv VM for "minikube" ...
E0916 22:36:02.875964   12860 start.go:723] StartHost: start: exit status 1
*
X Unable to start VM: start: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

OS - Windows 10

**Comment by blueelvis** [comment]
@WilsonGadekar - Thanks for reporting this issue!

Could you please try the following?
1. Delete the folder `%USERPROFILE%/.minikube`
2. Try running the command again - `minikube start --vm-driver hyperv --cpus 2 --memory=4096 --hyperv-virtual-switch "Minikube"`

**Comment by tstromberg** [comment]
@blueelvis - IMHO, deleting `.minikube` should not be done except in extreme circumstances. Doing so can result in minikube and the VM manager being out of sync with one another.

Based on the output, I believe the failure here is in part because there are spaces after the `-` in the command line. Please try sharing the output of:

`minikube start -vm-driver hyperv -cpus 2 -memory=4096 -hyperv-virtual-switch "Minikube" --alsologtostderr -v=8`

and:

`Get-VMSwitch`

Thank you!

**Comment by WilsonGadekar** [comment]
I ran the command you shared -  
minikube start -vm-driver hyperv -cpus 2 -memory=4096 -hyperv-virtual-switch "Minikube" --alsologtostderr -v=8

below is the output

Error: invalid argument "m-driver" for "-v, --v" flag: strconv.Atoi: parsing "m-driver": invalid syntax


Options:
      --apiserver-ips=[]: A set of apiserver IP Addresses which are used in the generated certificate for kubernetes.  This can be used if you want to make the apiserver available from outside the machine
      --apiserver-name='minikubeCA': The apiserver name which is used in the generated certificate for kubernetes.  This can be used if you want to make the apiserver available from outside the machine
      --apiserver-names=[]: A set of apiserver names which are used in the generated certificate for kubernetes.  This can be used if you want to make the apiserver available from outside the machine
      --apiserver-port=8443: The apiserver listening port
      --cache-images=true: If true, cache docker images for the current bootstrapper and load them into the machine. Always false with --vm-driver=none.
      --container-runtime='docker': The container runtime to be used (docker, crio, containerd)
      --cpus=2: Number of CPUs allocated to the minikube VM
      --cri-socket='': The cri socket path to be used
      --disable-driver-mounts=false: Disables the filesystem mounts provided by the hypervisors
      --disk-size='20000mb': Disk size allocated to the minikube VM (format: <number>[<unit>], where unit = b, k, m or g)
      --dns-domain='cluster.local': The cluster dns domain name used in the kubernetes cluster
      --dns-proxy=false: Enable proxy for NAT DNS requests (virtualbox)
      --docker-env=[]: Environment variables to pass to the Docker daemon. (format: key=value)
      --docker-opt=[]: Specify arbitrary flags to pass to the Docker daemon. (format: key=value)
      --download-only=false: If true, only download and cache files for later use - don't install or start anything.
      --enable-default-cni=false: Enable the default CNI plugin (/etc/cni/net.d/k8s.conf). Used in conjunction with "--network-plugin=cni"
      --extra-config=: A set of key=value pairs that describe configuration that may be passed to different components.
                The key should be '.' separated, and the first part before the dot is the component to apply the configuration to.
                Valid components are: kubelet, kubeadm, apiserver, controller-manager, etcd, proxy, scheduler
                Valid kubeadm parameters: ignore-preflight-errors, dry-run, kubeconfig, kubeconfig-dir, node-name, cri-socket, experimental-upload-certs, certificate-key, rootfs, pod-network-cidr
      --feature-gates='': A set of key=value pairs that describe feature gates for alpha/experimental features.
      --host-dns-resolver=true: Enable host resolver for NAT DNS requests (virtualbox)
      --host-only-cidr='192.168.99.1/24': The CIDR to be used for the minikube VM (only supported with Virtualbox driver)
      --hyperkit-vpnkit-sock='': Location of the VPNKit socket used for networking. If empty, disables Hyperkit VPNKitSock, if 'auto' uses Docker for Mac VPNKit connection, otherwise uses the specified VSock.
      --hyperkit-vsock-ports=[]: List of guest VSock ports that should be exposed as sockets on the host (Only supported on with hyperkit now).
      --hyperv-virtual-switch='': The hyperv virtual switch name. Defaults to first found. (only supported with HyperV driver)
      --image-mirror-country='': Country code of the image mirror to be used. Leave empty to use the global one. For Chinese mainland users, set it to cn
      --image-repository='': Alternative image repository to pull docker images from. This can be used when you have limited access to gcr.io. Set it to "auto" to let minikube decide one for you. For Chinese mainland users, you may use local gcr.io mirrors such as registry.cn-hangzhou.aliyuncs.com/google_containers
      --insecure-registry=[]: Insecure Docker registries to pass to the Docker daemon.  The default service CIDR range will automatically be added.
      --iso-url='https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso': Location of the minikube iso
      --keep-context=false: This will keep the existing kubectl context and will create a minikube context.
      --kubernetes-version='v1.15.2': The kubernetes version that the minikube VM will use (ex: v1.2.3)
      --kvm-gpu=false: Enable experimental NVIDIA GPU support in minikube
      --kvm-hidden=false: Hide the hypervisor signature from the guest in minikube
      --kvm-network='default': The KVM network name. (only supported with KVM driver)
      --kvm-qemu-uri='qemu:///system': The KVM QEMU connection URI. (works only with kvm2 driver on linux)
      --memory='2000mb': Amount of RAM allocated to the minikube VM (format: <number>[<unit>], where unit = b, k, m or g)
      --mount=false: This will start the mount daemon and automatically mount files into minikube
      --mount-string='C:\Users\Aaru:/minikube-host': The argument to pass the minikube mount command on start
      --network-plugin='': The name of the network plugin
      --nfs-share=[]: Local folders to share with Guest via NFS mounts (Only supported on with hyperkit now)
      --nfs-shares-root='/nfsshares': Where to root the NFS Shares (defaults to /nfsshares, only supported with hyperkit now)
      --no-vtx-check=false: Disable checking for the availability of hardware virtualization before the vm is started (virtualbox)
      --registry-mirror=[]: Registry mirrors to pass to the Docker daemon
      --service-cluster-ip-range='10.96.0.0/12': The CIDR to be used for service cluster IPs.
      --uuid='': Provide VM UUID to restore MAC address (only supported with Hyperkit driver).
      --vm-driver='virtualbox': VM driver is one of: [virtualbox vmwarefusion hyperv vmware]
      --wait=true: Wait until Kubernetes core services are healthy before exiting

Usage:
  minikube start [flags] [options]

Use "minikube start options" for a list of global command-line options (applies to all commands).

**Comment by WilsonGadekar** [comment]
> 
> 
> @WilsonGadekar - Thanks for reporting this issue!
> 
> Could you please try the following?
> 
>     1. Delete the folder `%USERPROFILE%/.minikube`
> 
>     2. Try running the command again - `minikube start --vm-driver hyperv --cpus 2 --memory=4096 --hyperv-virtual-switch "Minikube"`

How can i delete `%USERPROFILE%/.minikube'???

**Comment by tstromberg** [comment]
@WilsonGadekar - it looks like my advice was bad. All of our flags need double dashes, even on Windows. Do you mind upgrading to minikube v1.4 and trying this command:

`minikube start --vm-driver hyperv --cpus 2 --memory=4096 --alsologtostderr -v=1`

NOTE: There is no need to specify an external switch now, which is probably where minikube was failing before.

**Comment by medyagh** [comment]
@WilsonGadekar  are you still having this issue ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
