### ISSUE TITLE
"docker-machine-driver-hyperkit": executable file not found in $PATH

### ISSUE THREAD

**Issue by hpandeycodeit** [kubernetes/minikube#5367]
**The exact command to reproduce the issue**:

minikube start --vm-driver=hyperkit

**The full output of the command that failed**:<details>

```
minikube start --vm-driver=hyperkit
😄  minikube v1.3.1 on Darwin 10.14.5
⚠️  Error checking driver version: exec: "docker-machine-driver-hyperkit": executable file not found in $PATH
💿  Downloading VM boot image ...
minikube-v1.3.0.iso.sha256: 65 B / 65 B [--------------------] 100.00% ? p/s 0s
minikube-v1.3.0.iso: 131.07 MiB / 131.07 MiB [-------] 100.00% 26.05 MiB p/s 5s
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0916 11:14:44.625229   35742 start.go:723] StartHost: new host: Driver "hyperkit" not found. Do you have the plugin binary "docker-machine-driver-hyperkit" accessible in your PATH?

💣  Unable to start VM
❌  Error: [HYPERKIT_NOT_FOUND] new host: Driver "hyperkit" not found. Do you have the plugin binary "docker-machine-driver-hyperkit" accessible in your PATH?
💡  Suggestion: Please install the minikube hyperkit VM driver, or select an alternative --vm-driver
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

</details>

**The output of the `minikube logs` command**:<details>

 minikube logs

💣  api load: filestore: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
office-5-51:Downloads hpandey$ docker machine ls
docker: 'machine' is not a docker command.
See 'docker --help'

</details>

**The operating system version**:

macOS Mojave 10.14.5

**hyperkit is present in the PATH**

**Comment by tstromberg** [comment]
hyperkit may be installed, but it sounds like `docker-machine-driver-hyperkit` isn't installed. Please install it first: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/

Related: #5354

**Comment by hpandeycodeit** [comment]
@tstromberg thanks for the reference. Somehow I missed the driver installation. We can close this one out. :)

**Comment by tstromberg** [comment]
This also won't happen in minikube v1.4. Thanks for the followup!
