### ISSUE TITLE
Remove all single-package constants from constants package

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5375]
If a constant is only used by a single package, let the constant live there instead of the `constants` package.

For example, flag constants should probably only live in `cmd`.

**Comment by u5surf** [comment]
@tstromberg 
Hi, I’ll try this issue.

**Comment by tstromberg** [comment]
@u5surf: Thank you! That's great news. I look forward to seeing your PR!

/assign u5surf

**Comment by tstromberg** [comment]
@u5surf - any luck? :)

**Comment by u5surf** [comment]
@tstromberg 
I'm working in progress beside my main job

**Comment by u5surf** [comment]
@tstromberg 
Can I erase unused constant?
e.g `DefaultUfsPort`
```
$ grep -rn DefaultUfsPort .
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/udev/rules.d/80-net-setup-link.rules: Too many levels of symbolic links
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/systemd/system/getty.target.wants/getty@tty1.service: No such file or directory
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/var/run/crio.sock: No such file or directory
./pkg/minikube/constants/constants.go:212:	// DefaultUfsPort is the default port of UFS
./pkg/minikube/constants/constants.go:213:	DefaultUfsPort = "5640"
```

**Comment by u5surf** [comment]
@tstromberg 
For example `MinikubeEnvPrefix`, which use only `cmd` package, I prefer to make a constraint defined file like `/cmd/minikube/cmd/constants.go`.  WDYT?
```
$ grep -rn MinikubeEnvPrefix .
./cmd/minikube/cmd/start.go:142:        viper.SetEnvPrefix(constants.MinikubeEnvPrefix)
./cmd/minikube/cmd/root_test.go:100:            if strings.HasPrefix(env, constants.MinikubeEnvPrefix) {
./cmd/minikube/cmd/root_test.go:146:    return constants.MinikubeEnvPrefix + "_" + strings.ToUpper(name)
./cmd/minikube/cmd/root.go:260: viper.SetEnvPrefix(constants.MinikubeEnvPrefix)
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/udev/rules.d/80-net-setup-link.rules: Too many levels of symbolic links
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/systemd/system/getty.target.wants/getty@tty1.service: No such file or directory
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/var/run/crio.sock: No such file or directory
```

**Comment by u5surf** [comment]
@tstromberg 
Following `gvisor` constants,
```
const (
  // GvisorFilesPath is the path to the gvisor files saved by go-bindata
  GvisorFilesPath = "/tmp/gvisor"

  // GvisorConfigTomlTargetName is the go-bindata target name for the gvisor config.toml
  GvisorConfigTomlTargetName = "gvisor-config.toml"
)
```
which use `gvisor` package and  `./pkg/minikube/assets/addons.go`
```
$ grep -rn GvisorFilesPath .
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/udev/rules.d/80-net-setup-link.rules: Too many levels of symbolic links
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/etc/systemd/system/getty.target.wants/getty@tty1.service: No such file or directory
grep: ./deploy/iso/minikube-iso/board/coreos/minikube/rootfs-overlay/var/run/crio.sock: No such file or directory
./pkg/minikube/constants/constants.go:294:      // GvisorFilesPath is the path to the gvisor files saved by go-bindata
./pkg/minikube/constants/constants.go:295:      GvisorFilesPath = "/tmp/gvisor"
./pkg/minikube/assets/addons.go:327:                    constants.GvisorFilesPath,
./pkg/gvisor/enable.go:175:     src := filepath.Join(constants.GvisorFilesPath, asset.GetTargetName())
```
Such the constants have better been redefined in ` givisor ` package.
When the constants use, we import the `gvisor` package. (In the above example, it should be imported in addons.go which suppose to use the constants.)

**Comment by tstromberg** [comment]
> DefaultUfsPort

Yes, please delete any unused constants.

> @tstromberg
> For example `MinikubeEnvPrefix`, which uses only `cmd` package, I prefer to make a constraint defined file like `/cmd/minikube/cmd/constants.go`. WDYT?

Yes, that sounds like a good approach, as `MinikubeEnvPrefix` is shared among multiple files within the `cmd` package.

> Such the constants have better been redefined in `givisor` package.
> When the constants use, we import the `gvisor` package. (In the above example, it should be imported in addons.go which suppose to use the constants.)

Yes, that is precisely what I was going to suggest. It sounds like we are on the same page =)
