### ISSUE TITLE
minikube issue

### ISSUE THREAD

**Issue by arvindpathare** [kubernetes/minikube#5379]
[root@k8s-master ~]# minikube start
* minikube v1.3.1 on Centos 7.6.1810
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
*

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the kvm2 driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`
*

E0917 11:09:19.605635   15870 start.go:723] StartHost: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')
*
X Unable to start VM: Error getting state for host: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
[root@k8s-master ~]# minikube status
*
X Error getting host status: state: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by arvindpathare** [comment]
getting this issue on centos7

**Comment by tstromberg** [comment]
Using the kvm2 driver as root is unsupported, and will cause an instant exit in the next minikube release. Do you mind seeing if it runs properly when run as a non-root user?

**Comment by tstromberg** [comment]
Fixed in v1.4.
