### ISSUE TITLE
Unable to start Hper-v for minikube ,please help,

### ISSUE THREAD

**Issue by AnushAhmad** [kubernetes/minikube#5391]
Starting existing hyperv VM for "minikube" ...
E0918 19:21:22.349100   10896 start.go:723] StartHost: start: exit status 1
*
X Unable to start VM: start: exit status 1

**Comment by tstromberg** [comment]
Hi Anush!

Do you mind trying with minikube v1.4? I believe we have addressed this. If not, could you please include the output of:

`minikube start --alsologtostderr -v=8`

Thank you!

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with minikube v1.5.0.beta-0
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.

Thank you for sharing your experience!
