### ISSUE TITLE
feature: set ingress class for ingress plugin (for traefik)

### ISSUE THREAD

**Issue by woodcockjosh** [kubernetes/minikube#5394]
If someone is using a different ingress class, like `traefik`, then the ingress configurations won't work. We should be able to set the ingress class for the ingress plugin to resolve this with an option like `--ingress-class={{ default 'nginx' .IngressClass }}` as described here: https://kubernetes.github.io/ingress-nginx/user-guide/multiple-ingress/

**Comment by tstromberg** [comment]
There isn't currently a way to pass options into addons, but that's something we should consider when we revamp them.

In the mean time, perhaps we could have an traefik or ingress-traefik addon?

**Comment by woodcockjosh** [comment]
I will think about how to create a traefik addon

**Comment by woodcockjosh** [comment]
Going to table this for now
