### ISSUE TITLE
hyperv: cannot use "fe80::215:5dff:fe01:10d" as the bind address for the API Server

### ISSUE THREAD

**Issue by spimentel1201** [kubernetes/minikube#5396]
**Los comandos necesarios para reproducir la incidencia**:

**El resultado completo del comando que ha fallado**: <details>

</details>

**El resultado del comando `minikube logs`**: <details>

X Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
cannot use "fe80::215:5dff:fe01:10d" as the bind address for the API Server

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by tstromberg** [comment]
Creo que este problema es un duplicado del n. ° 3963, y se puede solucionar actualizando a minikube v1.4 que utiliza el "Interruptor predeterminado" de Hyper-V. ¿Te importaría probarlo por nosotros?

**Comment by tstromberg** [comment]
Marking as duplicate of #3963
