### ISSUE TITLE
PR bot: Add CPU load impact

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5398]
As part of the roadmap item "Reduce guest VM overhead by 50%", I would like to see an integration test that both our CI and developers can run that generates:

- A graph of load average impact for minikube start + 60 seconds of idle afterwards.
- An approximate idle load impact score, for instance: (mean minikube idle average - mean pre-start average). 

An additional enhancement would be generating the statistics in a way that demonstrates VM overhead versus VM+Kubernetes overhead.

**Comment by tstromberg** [comment]
Related: #3207

It would be nice to see this mature to eventually give us feedback on whether or not a PR has a negative or positive performance improvement.

**Comment by tstromberg** [comment]
Also related: #4622

**Comment by priyawadhwa** [comment]
As part of this, we are adding a PR bot to:
- [ ] Compare time for `minikube start` across three runs
- [ ] Compare binary sizes via [build-size](https://github.com/afbjorklund/build-size)

**Comment by sharifelgamal** [comment]
Opened #6095 for the binary size diff.
