### ISSUE TITLE
Update notifier points to unexisting Github page

### ISSUE THREAD

**Issue by carroarmato0** [kubernetes/minikube#5416]
The minikube's update notifier displays the following url: 

`⚠️  minikube 1.4.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.4.0
`

This takes you to a 404 page on Github.

The correct URL should have been  

`⚠️  minikube 1.4.0 is available! Download it: 
https://github.com/kubernetes/minikube/releases/tag/v1.4.0
`

Current version
`
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631
`
System
`
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=19.04
DISTRIB_CODENAME=disco
DISTRIB_DESCRIPTION="Ubuntu 19.04"
`

**Comment by tstromberg** [comment]
Thanks for the heads up! We fixed this embarrassing issue in v1.4, so you shouldn't see it again: #5101
