### ISSUE TITLE
permission denied while accessing kubeconfig

### ISSUE THREAD

**Issue by dedanmsafari** [kubernetes/minikube#5417]
minikube start --vm-driver=virtualbox
😄  minikube v1.4.0 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ HTTP_PROXY=http://172.16.63.3:3128
    ▪ HTTPS_PROXY=http://172.16.63.3:3128
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
    ▪ http_proxy=172.16.63.3:3128
    ▪ https_proxy=http://172.16.63.3:3128/
    ▪ no_proxy=localhost,127.0.0.0/8,::1
🐳  Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...
    ▪ env HTTP_PROXY=http://172.16.63.3:3128
    ▪ env HTTPS_PROXY=http://172.16.63.3:3128
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
    ▪ env HTTP_PROXY=172.16.63.3:3128
    ▪ env HTTPS_PROXY=http://172.16.63.3:3128/
    ▪ env NO_PROXY=localhost,127.0.0.0/8,::1

💣  Failed to setup kubeconfig: Error reading file "/home/msafari/.kube/config": open /home/msafari/.kube/config: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we wo

**Comment by dedanmsafari** [comment]
Any idea on how i can access the  /.kube/config file?

**Comment by tstromberg** [comment]
My guess is that the .kube directory, or at least the config file is owned by another user. Possibly due to previous use of `sudo`. This should do the trick:

`sudo chown -R $USER /home/msafari/.kube`

If not, do you mind sharing the output of:

`ls -la /home/msafari/.kube`

Please let me know if this helps.

**Comment by dedanmsafari** [comment]
total 20
drwxr-x---  4 msafari root    4096 Ful 21 11:00 .
drwxrwxrwx 30 msafari msafari 4096 Ful 21 10:57 ..
drwxr-x---  3 msafari root    4096 Ful 14 11:18 cache
-rw-------  1 msafari root     427 Ful 21 19:34 config
drwxr-x---  3 msafari root    4096 Ful 21 10:57 http-cache

**Comment by dedanmsafari** [comment]
it does not change. the config file has read and write permissions but i cant access it

**Comment by sharifelgamal** [comment]
What happens if you run `cat /home/msafari/.kube/config`?
