### ISSUE TITLE
Windows installer: /SD (completely silent mode) doesn't work

### ISSUE THREAD

**Issue by dzmitry-lahoda** [kubernetes/minikube#5418]
1. Download https://storage.googleapis.com/minikube/releases/latest/minikube-installer.exe
2. Run with silent parameters http://www.silentinstall.org/nsis
Expected: No  message box.
Actual: Message box is shown

UPDATE: `/S` mode seems to work, but not `/SD`. So seems to be simple fix.

**Comment by tstromberg** [comment]
Sounds reasonable. I personally know nothing about NSIS, so help wanted :) 

Source code is here: https://github.com/kubernetes/minikube/tree/master/installers/windows

/cc @blueelvis

**Comment by blueelvis** [comment]
@dzmitry-lahoda - I just tried the `/S` on my machine and it seems to be doing the installation completely silently (Tried deleting the files & they came back). Is there a reason why you want the `/SD` switch while the same functionality can be achieved by `/S` switch?

**Comment by dzmitry-lahoda** [comment]
consistency with other windows installers based on nsis would be preferable. /s - shows error message. /sd - does not show message even if error.  it would be fine for /s to have a bug - no error message in case of error. or /sd to have a bug - show error message in case of error. but not searching github by /sd does no work and nor usage of /s instead of /sd for future compatibility reasons.  as i see the situation.

**Comment by tstromberg** [comment]
If anyone knows NSIS, help wanted. =) I did some cursory reading, and suspect that this may just be the matter of defining a default popup for message boxes in:

https://github.com/kubernetes/minikube/blob/master/installers/windows/minikube.nsi 

The other possibility is that the jenkins build server uses `makensis` v2.51 (the default in Debian 9). That said, /sd as a flag is like 13 years old, so it's probably unrelated.
