### ISSUE TITLE
kvm2: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/minikube#5423]
**The exact command to reproduce the issue**: 
`minikube start --vm-driver=kvm2`

**The full output of the command that failed**:<details>
😄  minikube v1.4.0 on Debian rodete
🔥  Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...
🚜  Pulling images ...
❌  Unable to pull images, which may be OK: running cmd: sudo env PATH=/var/lib/minikube/binaries/v1.16.0:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml: command failed: sudo env PATH=/var/lib/minikube/binaries/v1.16.0:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml
stdout: 
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.16.0": output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher
: Process exited with status 1
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"
</details>

A system restart fixes this, but we should look into what's happening.

**Comment by dsebastien** [comment]
I have the same issue with VirtualBox.
I'm really wondering what causes this and have no clue where to start looking..

**Comment by tstromberg** [comment]
This bug is reflective of the hypervisor bridge interface not being able to route packets to the internet. v1.5.0 does a better job of detecting and warning about the condition.

@dsebastien - I suggest opening a separate bug for virtualbox.
