### ISSUE TITLE
v1.3.1: hyperv: StartHost: start: exit status 1

### ISSUE THREAD

**Issue by pakrrx** [kubernetes/minikube#5435]
**The exact command to reproduce the issue**:
C:\Users\pabbathianandkumar>minikube start
! minikube 1.4.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.4.0
* To disable this notice, run: 'minikube config set WantUpdateNotification false'
* minikube v1.3.1 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
*

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the hyperv driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`
*

* Starting existing hyperv VM for "minikube" ...
E0923 10:40:00.115261    3608 start.go:723] StartHost: start: exit status 1
*
X Unable to start VM: start: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\Users\pabbathianandkumar>minikube start
* minikube v1.3.1 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
*

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the hyperv driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`
*

* Starting existing hyperv VM for "minikube" ...
E0923 10:52:13.171328   12416 start.go:723] StartHost: start: exit status 1
*
X Unable to start VM: start: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\Users\pabbathianandkumar>

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Winows 10 Enterprise

**Comment by tstromberg** [comment]
@pakrrx - I believe we may have fixed this issue in minikube v1.4. Do you mind trying to upgrade and reporting back?

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
