### ISSUE TITLE
Fail to create and start on Windows 10 and HyperV

### ISSUE THREAD

**Issue by fxa76** [kubernetes/minikube#5437]
**The exact command to reproduce the issue**:
 minikube start --vm-driver hyperv --hyperv-virtual-switch "vSwitchMinikube"

**The full output of the command that failed**:
minikube start --vm-driver hyperv --hyperv-virtual-switch "vSwitchMinikube"
* minikube v1.4.0 sur Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Downloading VM boot image ...
    > minikube-v1.4.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.4.0.iso: 135.73 MiB / 135.73 MiB [ 100.00% 1.32 MiB p/s 1m43s
* Création d'une VM hyperv (CPUs=2, Mémoire=2000MB, Disque=20000MB)...
* Retriable failure: create: creating: exit status 1
* Suppression de "minikube" sur hyperv...
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\FXA\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\FXA\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\FXA\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X Unable to start VM: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\FXA\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
minikube logs
*
X api load: filestore "minikube": open C:\Users\FXA\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
minikube v1.4.0 sur Microsoft Windows 10 Pro 10.0.18362 Build 18362

**Comment by medyagh** [comment]
Hi @fxa76 Thank you for taking the time to report this issue, 


I am curious if this would solve your issue 
first delete by 
```minikube delete```

and then start without specifying the switch and let it auto detect.

```minikube start --vm-driver hyperv ```

**Comment by fxa76** [comment]
It does sometimes... it seems to be more robust when specifying the hyperv-virtual-switch-parameter but still seems to fail quite often...

minikube delete
minikube start --vm-driver hyperv --hyperv-virtual-switch "vSwitchMinikube"

**Comment by sharifelgamal** [comment]
Sounds like this is an issue regardless of which switch is getting used. Could you add `-v=8 --alsologtostderr` to your failing `minikube start` command? It'll give us a lot more information to go on for debugging the issue.

**Comment by danztensai** [comment]
happen to me too,
`minikube delete `

then
`
minikube start --vm-driver=hyperv --kubernetes-version v1.15.4 
`

i've delete .minikube folder on users windows and try to minikube start again even wihout --kuberntes-version

**Comment by Aankhen** [comment]
I had the same issue. The failing invocation:
```
Z:\> minikube start -p learning --vm-driver=virtualbox
* [learning] minikube v1.5.1 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: open /Users/A/.minikube/cache/iso/minikube-v1.5.1.iso: The system cannot find the path specified.
```

Note the path (`/Users/A/.minikube/cache/iso/minikube-v1.5.1.iso`). It ought to start with `C:/`, i.e. the drive my profile folder is on. The same invocation works if I first switch:

```
C:\> minikube start -p learning --vm-driver=virtualbox
* [learning] minikube v1.5.1 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.16.2 on Docker 18.09.9 ...
* Pulling images ...
* Launching Kubernetes ...
* Waiting for: apiserver
* Done! kubectl is now configured to use "learning"
```

**Comment by nguyen190887** [comment]
I got the same issue. I did change `MINIKUBE_HOME` to `D:\Minikube` and when I ran `minikube start` command, I got the `The system cannot find the path specified.` error for `iso` file.

```
PS C:\Windows\system32> minikube start --vm-driver hyperv
* minikube v1.5.2 on Microsoft Windows 10 Pro 10.0.17134 Build 17134
  - MINIKUBE_HOME=D:\Minikube
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: open /Minikube/.minikube/cache/iso/minikube-v1.5.1.iso: The system cannot find the path specified.
E1105 06:33:25.723236   17544 main.go:106] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
```

Then I tried to switch to `D:\` (the drive containing `iso` file) in my PowerShell, ran the command again and it worked 🚀 
```
PS D:\> minikube start --vm-driver hyperv
* minikube v1.5.2 on Microsoft Windows 10 Pro 10.0.17134 Build 17134
  - MINIKUBE_HOME=D:\Minikube
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
* Downloading kubeadm v1.16.2
* Downloading kubelet v1.16.2
* Pulling images ...
* Launching Kubernetes ...
```

Hope this helps 😃

**Comment by brainfull** [comment]
On my side, everytime I call 'minikube delete' I also delete automatically %userprofile%/.minikube. It resolves a lot of weird behavior and doesn't create unwanted side effect, at least for me.

**Comment by medyagh** [comment]
@brainfull it worth noting you could also do minikube delete --all --purge

**Comment by medyagh** [comment]
@brainfull  I haven't heard from you I will close this issue, please feel free to reopen
I also suggest to try our new driver docker with latest version of minikbue
```
minikube start --vm-driver=docker
```
