### ISSUE TITLE
minikube docker-env includes update notice instructions

### ISSUE THREAD

**Issue by retracile** [kubernetes/minikube#5446]
Under certain conditions, minikube commands will output a notice that "minikube X.Y.Z is available! Download it: ..." as well as instructions on how to disable that notice.  Unfortunately, that includes `minikube docker-env`, and the instructions are sent to stdout.  This means that when a new version of minikube is made available, the next execution of minikube docker-env outputs the update notice instructions, which then gets executed, yielding an error message.

For instance, given a `bin/dockerw` script with
```
#!/bin/bash -x
# Thin wrapper around 'docker' that pulls in the minikube environment so you
# don't have to pollute your primary shell with it.
eval $(minikube docker-env)
docker "$@"
```
the update notice instructions cause this:
```
./bin/dockerw image list
++ minikube docker-env
⚠️  minikube 1.4.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.4.0
💣  The docker host is currently not running
+ eval $'�\237\222�' To disable this notice, run: ''\''minikube' config set WantUpdateNotification 'false'\'''
++ $'�\237\222�' To disable this notice, run: 'minikube config set WantUpdateNotification false'
./bin/dockerw: line 4: 💡: command not found
+ docker image list
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

(In the example above, I didn't have minikube running yet; the error about "The docker host is currently not running" is the expected output in this case, and is not relevant to the bug in question.)

`minikube docker-env` needs to send the update notice instructions 
```
💡 To disable this notice, run: 'minikube config set WantUpdateNotification false'
```
to stderr instead of stdout.

This is with minikube 1.3.1; I cannot test the latest version of minikube for this issue because it only triggers this behavior when there is a newer version of minikube available to download.

**Comment by tstromberg** [comment]
Good news - we've fixed this in v1.4 as part of #5344. The notice will only be output as part of "minikube start".

Thanks for checking in on this issue. It should never have worked this way, IMHO.
