### ISSUE TITLE
virtualbox: Unable to start VM: Maximum number of retries (5) exceeded

### ISSUE THREAD

**Issue by evanfietz** [kubernetes/minikube#5449]
**The exact command to reproduce the issue**:
fietz@ubuntu:~$ minikube start --logtostderr  -v 8

**The full output of the command that failed**:<details>
```
fietz@ubuntu:~$ minikube delete
🔥  Deleting "minikube" in virtualbox ...
💔  The "minikube" cluster has been deleted.
fietz@ubuntu:~$ minikube start --logtostderr  -v 8
I0924 12:02:33.172231    9746 notify.go:125] Checking for updates...
I0924 12:02:33.597704    9746 start.go:236] hostinfo: {"hostname":"ubuntu","uptime":1685,"bootTime":1569346468,"procs":391,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.0.0-29-generic","virtualizationSystem":"kvm","virtualizationRole":"host","hostid":"1e9ecb51-2c50-4b68-958c-0d65df61f1d3"}
I0924 12:02:33.598176    9746 start.go:246] virtualization: kvm host
😄  minikube v1.4.0 on Ubuntu 18.04
I0924 12:02:33.598691    9746 downloader.go:59] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.4.0.iso
I0924 12:02:33.598951    9746 profile.go:66] Saving config to /home/fietz/.minikube/profiles/minikube/config.json ...
I0924 12:02:33.598956    9746 cache_images.go:295] CacheImage: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> /home/fietz/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1
I0924 12:02:33.599002    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1 exists
I0924 12:02:33.599026    9746 cache_images.go:297] CacheImage: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> /home/fietz/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1 completed in 70.475µs
I0924 12:02:33.599041    9746 cache_images.go:82] CacheImage gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> /home/fietz/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1 succeeded
I0924 12:02:33.599056    9746 cache_images.go:295] CacheImage: k8s.gcr.io/kube-proxy:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.16.0
I0924 12:02:33.599072    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.16.0 exists
I0924 12:02:33.599101    9746 cache_images.go:295] CacheImage: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0924 12:02:33.599119    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13 exists
I0924 12:02:33.599127    9746 cache_images.go:297] CacheImage: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13 completed in 29.64µs
I0924 12:02:33.599137    9746 cache_images.go:82] CacheImage k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13 succeeded
I0924 12:02:33.599153    9746 cache_images.go:295] CacheImage: k8s.gcr.io/kube-scheduler:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.16.0
I0924 12:02:33.599172    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.16.0 exists
I0924 12:02:33.599183    9746 cache_images.go:297] CacheImage: k8s.gcr.io/kube-scheduler:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.16.0 completed in 31.795µs
I0924 12:02:33.599197    9746 cache_images.go:82] CacheImage k8s.gcr.io/kube-scheduler:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.16.0 succeeded
I0924 12:02:33.599210    9746 cache_images.go:295] CacheImage: k8s.gcr.io/kube-controller-manager:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.16.0
I0924 12:02:33.599223    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.16.0 exists
I0924 12:02:33.599234    9746 cache_images.go:297] CacheImage: k8s.gcr.io/kube-controller-manager:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.16.0 completed in 26.077µs
I0924 12:02:33.599243    9746 cache_images.go:82] CacheImage k8s.gcr.io/kube-controller-manager:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.16.0 succeeded
I0924 12:02:33.599254    9746 cache_images.go:295] CacheImage: k8s.gcr.io/kube-apiserver:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.16.0
I0924 12:02:33.599267    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.16.0 exists
I0924 12:02:33.599278    9746 cache_images.go:297] CacheImage: k8s.gcr.io/kube-apiserver:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.16.0 completed in 25.826µs
I0924 12:02:33.599289    9746 cache_images.go:82] CacheImage k8s.gcr.io/kube-apiserver:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.16.0 succeeded
I0924 12:02:33.599301    9746 cache_images.go:295] CacheImage: k8s.gcr.io/pause:3.1 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/pause_3.1
I0924 12:02:33.599313    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/pause_3.1 exists
I0924 12:02:33.599322    9746 cache_images.go:297] CacheImage: k8s.gcr.io/pause:3.1 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/pause_3.1 completed in 22.807µs
I0924 12:02:33.599330    9746 cache_images.go:82] CacheImage k8s.gcr.io/pause:3.1 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/pause_3.1 succeeded
I0924 12:02:33.599341    9746 cache_images.go:295] CacheImage: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I0924 12:02:33.599353    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13 exists
I0924 12:02:33.599361    9746 cache_images.go:297] CacheImage: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13 completed in 22.018µs
I0924 12:02:33.599370    9746 cache_images.go:82] CacheImage k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13 succeeded
I0924 12:02:33.599381    9746 cache_images.go:295] CacheImage: k8s.gcr.io/coredns:1.6.2 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/coredns_1.6.2
I0924 12:02:33.599393    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/coredns_1.6.2 exists
I0924 12:02:33.599401    9746 cache_images.go:297] CacheImage: k8s.gcr.io/coredns:1.6.2 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/coredns_1.6.2 completed in 22.118µs
I0924 12:02:33.599435    9746 cache_images.go:82] CacheImage k8s.gcr.io/coredns:1.6.2 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/coredns_1.6.2 succeeded
I0924 12:02:33.599416    9746 cache_images.go:297] CacheImage: k8s.gcr.io/kube-proxy:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.16.0 completed in 29.278µs
I0924 12:02:33.599456    9746 cache_images.go:82] CacheImage k8s.gcr.io/kube-proxy:v1.16.0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.16.0 succeeded
I0924 12:02:33.599424    9746 cache_images.go:295] CacheImage: kubernetesui/dashboard:v2.0.0-beta4 -> /home/fietz/.minikube/cache/images/kubernetesui/dashboard_v2.0.0-beta4
I0924 12:02:33.599475    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/kubernetesui/dashboard_v2.0.0-beta4 exists
I0924 12:02:33.599495    9746 cache_images.go:297] CacheImage: kubernetesui/dashboard:v2.0.0-beta4 -> /home/fietz/.minikube/cache/images/kubernetesui/dashboard_v2.0.0-beta4 completed in 73.012µs
I0924 12:02:33.599505    9746 cache_images.go:82] CacheImage kubernetesui/dashboard:v2.0.0-beta4 -> /home/fietz/.minikube/cache/images/kubernetesui/dashboard_v2.0.0-beta4 succeeded
I0924 12:02:33.599431    9746 cache_images.go:295] CacheImage: k8s.gcr.io/kube-addon-manager:v9.0.2 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0.2
I0924 12:02:33.599533    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0.2 exists
I0924 12:02:33.599544    9746 cache_images.go:297] CacheImage: k8s.gcr.io/kube-addon-manager:v9.0.2 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0.2 completed in 115.546µs
I0924 12:02:33.599560    9746 cache_images.go:82] CacheImage k8s.gcr.io/kube-addon-manager:v9.0.2 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0.2 succeeded
I0924 12:02:33.599587    9746 cache_images.go:295] CacheImage: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I0924 12:02:33.599601    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13 exists
I0924 12:02:33.599612    9746 cache_images.go:297] CacheImage: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13 completed in 26.601µs
I0924 12:02:33.599623    9746 cache_images.go:82] CacheImage k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13 succeeded
I0924 12:02:33.599635    9746 cache_images.go:295] CacheImage: k8s.gcr.io/etcd:3.3.15-0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/etcd_3.3.15-0
I0924 12:02:33.599662    9746 cache_images.go:301] /home/fietz/.minikube/cache/images/k8s.gcr.io/etcd_3.3.15-0 exists
I0924 12:02:33.599671    9746 cache_images.go:297] CacheImage: k8s.gcr.io/etcd:3.3.15-0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/etcd_3.3.15-0 completed in 38.442µs
I0924 12:02:33.599682    9746 cache_images.go:82] CacheImage k8s.gcr.io/etcd:3.3.15-0 -> /home/fietz/.minikube/cache/images/k8s.gcr.io/etcd_3.3.15-0 succeeded
I0924 12:02:33.599695    9746 cache_images.go:89] Successfully cached all images.
I0924 12:02:33.599413    9746 lock.go:41] attempting to write to file "/home/fietz/.minikube/profiles/minikube/config.json" with filemode -rw-------
I0924 12:02:33.599970    9746 cluster.go:93] Machine does not exist... provisioning new machine
I0924 12:02:33.599983    9746 cluster.go:94] Provisioning machine with config: {KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.4.0.iso Memory:2000 CPUs:2 DiskSize:20000 VMDriver:virtualbox ContainerRuntime:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true}
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
I0924 12:02:33.701542    9746 main.go:104] libmachine: Downloading /home/fietz/.minikube/cache/boot2docker.iso from file:///home/fietz/.minikube/cache/iso/minikube-v1.4.0.iso...
I0924 12:02:34.063612    9746 main.go:104] libmachine: Creating VirtualBox VM...
I0924 12:02:34.063631    9746 main.go:104] libmachine: Creating SSH key...
I0924 12:03:06.676189    9746 main.go:104] libmachine: Starting the VM...
I0924 12:03:06.847379    9746 main.go:104] libmachine: Check network to re-create if needed...
I0924 12:03:07.714855    9746 main.go:104] libmachine: Waiting for an IP...
🔄  Retriable failure: create: creating: Maximum number of retries (5) exceeded
🔥  Deleting "minikube" in virtualbox ...
W0924 12:07:22.339137    9746 exit.go:101] Unable to start VM: create: creating: Maximum number of retries (5) exceeded

💣  Unable to start VM: create: creating: Maximum number of retries (5) exceeded

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
fietz@ubuntu:~$ 
```

**The output of the `minikube logs` command**:<details>

fietz@ubuntu:~$ minikube logs

💣  api load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
fietz@ubuntu:~$ 

**The operating system version**:
 Ubuntu 18.04.3 LTS

**Comment by tstromberg** [comment]
Thank you for your feedback! 

Sadly, we've messed up and neither the error message or the logs here are very useful at all for some reason. We'll need to get to the root of tha.t Do you mind sharing the output of:

* `vboxmanage -version`
* `vboxmanage showvminfo minikube`

Also, see if there are any logs in `~/.VirtualBox/Machines/minikube/Logs`

**Comment by tstromberg** [comment]
Related: #5453

**Comment by evanfietz** [comment]
vboxmanage -version
6.0.12r133076

vboxmanage showvminfo minikube
Name:                        minikube
Groups:                      /
Guest OS:                    Linux 2.6 / 3.x / 4.x (64-bit)
UUID:                        93b5f58b-2322-49e1-8e6c-77845a3a9e99
Config file:                 /home/fietz/.minikube/machines/minikube/minikube/minikube.vbox
Snapshot folder:             /home/fietz/.minikube/machines/minikube/minikube/Snapshots
Log folder:                  /home/fietz/.minikube/machines/minikube/minikube/Logs
Hardware UUID:               93b5f58b-2322-49e1-8e6c-77845a3a9e99
Memory size                  2000MB
Page Fusion:                 disabled
VRAM size:                   8MB
CPU exec cap:                100%
HPET:                        enabled
CPUProfile:                  host
Chipset:                     piix3
Firmware:                    BIOS
Number of CPUs:              2
PAE:                         enabled
Long Mode:                   enabled
Triple Fault Reset:          disabled
APIC:                        enabled
X2APIC:                      disabled
Nested VT-x/AMD-V:           disabled
CPUID Portability Level:     0
CPUID overrides:             None
Boot menu mode:              disabled
Boot Device 1:               DVD
Boot Device 2:               DVD
Boot Device 3:               HardDisk
Boot Device 4:               Not Assigned
ACPI:                        enabled
IOAPIC:                      enabled
BIOS APIC mode:              APIC
Time offset:                 0ms
RTC:                         UTC
Hardw. virt.ext:             enabled
Nested Paging:               enabled
Large Pages:                 enabled
VT-x VPID:                   enabled
VT-x unr. exec.:             enabled
Paravirt. Provider:          Default
Effective Paravirt. Prov.:   KVM
State:                       aborted (since 2019-09-25T15:05:23.671000000)
Monitor count:               1
3D Acceleration:             disabled
2D Video Acceleration:       disabled
Teleporter Enabled:          disabled
Teleporter Port:             0
Teleporter Address:          
Teleporter Password:         
Tracing Enabled:             disabled
Allow Tracing to Access VM:  disabled
Tracing Configuration:       
Autostart Enabled:           disabled
Autostart Delay:             0
Default Frontend:            
Storage Controller Name (0):            SATA
Storage Controller Type (0):            IntelAhci
Storage Controller Instance Number (0): 0
Storage Controller Max Port Count (0):  30
Storage Controller Port Count (0):      30
Storage Controller Bootable (0):        on
SATA (0, 0): /home/fietz/.minikube/machines/minikube/boot2docker.iso (UUID: a6fa0f27-fa7d-4912-b086-40c208873f59)
SATA (1, 0): /home/fietz/.minikube/machines/minikube/disk.vmdk (UUID: 894016ce-28b4-49f6-92d6-3a15febe1136)
NIC 1:                       MAC: 080027EC444C, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: virtio, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 46683, guest ip = , guest port = 22
NIC 2:                       MAC: 0800278BD590, Attachment: Host-only Interface 'vboxnet0', Cable connected: on, Trace: off (file: none), Type: virtio, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 3:                       disabled
NIC 4:                       disabled
NIC 5:                       disabled
NIC 6:                       disabled
NIC 7:                       disabled
NIC 8:                       disabled
Pointing Device:             PS/2 Mouse
Keyboard Device:             PS/2 Keyboard
UART 1:                      disabled
UART 2:                      disabled
UART 3:                      disabled
UART 4:                      disabled
LPT 1:                       disabled
LPT 2:                       disabled
Audio:                       enabled (Driver: PulseAudio, Controller: AC97, Codec: STAC9700)
Audio playback:              disabled
Audio capture:               disabled
Clipboard Mode:              disabled
Drag and drop Mode:          disabled
VRDE:                        disabled
OHCI USB:                    disabled
EHCI USB:                    disabled
xHCI USB:                    disabled

USB Device Filters:

<none>

Bandwidth groups:  <none>

Shared folders:

Name: 'hosthome', Host path: '/home' (machine mapping), writable, auto-mount

Capturing:                   not active
Capture audio:               not active
Capture screens:             
Capture file:                /home/fietz/.minikube/machines/minikube/minikube/minikube.webm
Capture dimensions:          1024x768
Capture rate:                512kbps
Capture FPS:                 25kbps
Capture options:             

Guest:

Configured memory balloon size: 0MB


There doesn't appear to be a ~/.VirtualBox folder in my home dir

Thanks!

**Comment by medyagh** [comment]
@evanfietz  I wonder if you have the same problem in the latest version ?

btw, since you are using ubuntu, I would recommend using kvm driver. which preferred way for linux. 

https://minikube.sigs.k8s.io/docs/start/linux/#hypervisor-setup

**Comment by evanfietz** [comment]
Hello,

I’m not sure as I gave up on Minicube and just built a three node K8 cluster.

Thanks for checking in!

Regards,

Evan

Evan Fietz
Solutions Engineer

NetApp
403.862.9461 Mobile Phone
fietz@netapp.com<mailto:name@netapp.com>

[signature_56566682]<https://www.netapp.com/us/campaigns/gmq-primary-storage-report/index.aspx?ref_source=esignature&cid=33105>
