### ISSUE TITLE
logs no longer include libmachine commands, making hyperv impossible to debug

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5453]
We used to have logs for Hyper-V and Virtualbox machine drivers that showed each command run. Where'd they go?

**Comment by tstromberg** [comment]
git bisect to the rescue!

**Comment by tstromberg** [comment]
any luck?

**Comment by sharifelgamal** [comment]
not really, it's definitely in libmachine, but that really hasn't changed so maybe it's how we call it?
