### ISSUE TITLE
Minikube crash when use vm-driver=none

### ISSUE THREAD

**Issue by spqa** [kubernetes/minikube#5458]
**The exact command to reproduce the issue**:
sudo minikube start  --vm-driver=none

**The full output of the command that failed**:<details>
😄  minikube v1.4.0 on Arch 18.1.0

💣  Failed to save config: error acquiring lock for /root/.minikube/profiles/minikube/config.json: unable to open /tmp/juju-minikube-config-json: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
💣  Error getting config: stat /root/.minikube/profiles/minikube/config.json: no such file or directory

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
OS: Manjaro 18.1.0 Juhraya
 ██████████████████  ████████     Kernel: x86_64 Linux 5.1.21-1-MANJARO
 ██████████████████  ████████     Uptime: 3h 19m
 ████████            ████████     Packages: 1450
 ████████  ████████  ████████     Shell: zsh 5.7.1
 ████████  ████████  ████████     Resolution: 1920x1080
 ████████  ████████  ████████     DE: KDE 5.61.0
 ████████  ████████  ████████     WM: KWin
 ████████  ████████  ████████     Disk: 603G / 1.2T (54%)
 ████████  ████████  ████████     CPU: Intel Core i7-6700HQ @ 8x 3.5GHz [47.0°C]
 ████████  ████████  ████████     GPU: Intel Corporation HD Graphics 530 (rev 06)
 ████████  ████████  ████████     RAM: 7762MiB / 15912MiB

**Comment by medyagh** [comment]
Thanks for taking the time to create this issue, I am curious what is the permisison on the config file

do you mind sharing the output of?
```
ls -lah /root/.minikube/profiles/minikube/config.json
```

**Comment by medyagh** [comment]
also I forgot to ask, are you running sudo as the root user ?

**Comment by spqa** [comment]
Sorry for wasting your time, it worked after reboot
