### ISSUE TITLE
Get rid of python scripts in build process

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5461]
We have a python script that checks if there is license boilerplate in every file in the repo.
that was initially copied from kuberntes project. 

https://github.com/kubernetes/minikube/blob/master/hack/boilerplate/boilerplate.py

we need to get rid of it, because it would be nicer to have everything in go.
also reduce the dependency installation during each build / PR.  currently we have to spin up a python vm in travis just for this script .

https://github.com/kubernetes/minikube/blob/master/.travis.yml#L10

it would be a good -first issue to translate this python script to a a go run script.

**Comment by RickyRajinder** [comment]
Hi, I can work on this.

**Comment by tstromberg** [comment]
@RickyRajinder - Excellent! Please feel free to send a PR at any time. If you have any questions, please feel free to ask them here or in the #minikube Slack channel.

**Comment by duohedron** [comment]
I created a pull request for this issue. (#5544) I still needs to pass the cla/linuxfoundation check, but you can already review it.

**Comment by Jukie** [comment]
@RickyRajinder are you still working on this? If not I'll pick this up.

**Comment by nanikjava** [comment]
@duohedron I've also written the porting of the boilerplate Python tool in Go https://github.com/nanikjava/boilerplate 

Tested your implementation but it's not giving any output. The Python tool output

/minikube/cmd/minikube/main.go
/minikube/pkg/minikube/assets/assets.go
/minikube/pkg/minikube/translate/translations.go

and also getting the same output with my

**Comment by duohedron** [comment]
@nanikjava I think the issue was with the default path where the boilerplate files were looked for. I fixed it and tested on my machine and also on the tracis-ci pipeline. If it still not giving you the proper input please let me know some more details and I will fix it.

**Comment by nanikjava** [comment]
@medyagh so not to waste what I've written and tested thought I will submit PR for this fix https://github.com/kubernetes/minikube/pull/5557
