### ISSUE TITLE
Minikube unable to start using the xhyve driver

### ISSUE THREAD

**Issue by bala0409** [kubernetes/minikube#5481]
😄  minikube v1.4.0 on Darwin 10.14.6
💣  The driver 'xhyve' is not supported on darwin
C02Y83T8JGH5:manifests C5287199$ minikube start
😄  minikube v1.4.0 on Darwin 10.14.6
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: precreate: exit status 126
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: precreate: exit status 126
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: precreate: exit status 126
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: precreate: exit status 126

**Comment by afbjorklund** [comment]
The "xhyve" driver has been deprecated and removed in minikube v1.3.0 (exchanged for hyperkit), so you will need to switch to another driver (and recreate the VM). This can be done using `minikube config set vm-driver hyperkit`.

**Comment by AndrewGumenyuk** [comment]
As I assume, you can close it. It's expected behavior for "xhyve" driver
