### ISSUE TITLE
vmware: stuck on libmachine: Waiting for VM to come online...

### ISSUE THREAD

**Issue by aflat** [kubernetes/minikube#5482]
**The exact command to reproduce the issue**:
minikube --vm-driver=vmware start --alsologtostderr -v10

**The full output of the command that failed**:<details>
first hangs here:
I0927 11:56:30.625922   47145 main.go:104] libmachine: Creating SSH key...
I0927 11:56:30.725501   47145 main.go:104] libmachine: Creating VM...
I0927 11:56:30.746983   47145 main.go:104] libmachine: Starting minikube...
I0927 11:56:31.375766   47145 main.go:104] libmachine: Waiting for VM to come online...

then I kill the process, and run the start command again, and I get:

I0927 11:49:01.687348   46780 cluster.go:149] configureHost: &{plugin:0xc0002804b0 heartbeatDoneCh:0xc00077c120 Client:0xc000764210}
I0927 11:49:01.687718   46780 cluster.go:171] Configuring auth for driver vmware ...
I0927 11:49:01.687760   46780 main.go:104] libmachine: Waiting for SSH to be available...

</details>

**The output of the `minikube logs` command**:<details>
since it hasn't started yet, there are no logs

</details>

**The operating system version**: 
macOS Mojave 10.14.6
vmware fusion pro 11.1

11:45 $ minikube version
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6

Minikube installed via homebrew, The minikube VM starts in vmware, and I am able to login. I'm also able to ssh into it via the command line. I did run the command here

https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

I have disabled the vpn for this test, but fails with it and without

I try to start it first, and it hangs bringing it up, I waited, then killed, and minikube start again, and now it can't ssh in.

**Comment by tstromberg** [comment]
Thanks for the feedback!

Just curious: if you run `minikube delete` and then `minikube start --vm-driver=vmware` with the VPN off, does this still happen?

My guess so far is some kind of driver network interface connectivity issue.

**Comment by aflat** [comment]
Yup tried that still hit the same issue

**Comment by medyagh** [comment]
@aflat I have no idea how to help with vmware issues, but I wonder if the issue would be solved by upgrading your vmware driver to 11.5 ?

and another question, has it ever worked before and stopped working ? or it never worked before?

**Comment by dsoudakov** [comment]
I faced the same issue on Windows 10 E using hyperv. I also created a virtual switch called minikube and used this command line to run:

**Comment by aflat** [comment]
Upgraded to 11.5, still the same issue. This is the first time I have ever installed it, so I've never had it working.

**Comment by medyagh** [comment]
hm... sorry to hear that, while I dont know the answer how to help, I am curious is there any reason not to use other drivers? such as hyperkit ?
