### ISSUE TITLE
1.0: Job for docker.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by rzou99** [kubernetes/minikube#5490]
minikube start
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.101
🐳  Configuring Docker as the container runtime ...

💣  Failed to enable container runtime: command failed: sudo systemctl restart docker
stdout:
stderr: Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment]
v1.0 is . old - Do you mind trying upgrade to minikube v1.4.0, and first running "minikube delete"?

**Comment by medyagh** [comment]
@rzou99 do you still have this issue ? do you mind trying with the latest version of minikube?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
