### ISSUE TITLE
Output tables for commands should be the same as kubectl tables

### ISSUE THREAD

**Issue by woodcockjosh** [kubernetes/minikube#5493]
**The exact command to reproduce the issue**:
`minikube profile list`

**The full output of the command that failed**:<details>
```bash
|----------|------------|----------------|-----------|--------------------|
| Profile  | VM Driver  |     NodeIP     | Node Port | Kubernetes Version |
|----------|------------|----------------|-----------|--------------------|
| minikube | virtualbox | 192.168.99.169 |      8443 | v1.16.0            |
|----------|------------|----------------|-----------|--------------------|
```

</details>

**The operating system version**:
```bash
minikube version
minikube version: v1.4.0
commit: 90bf0f8ec57f051ac014d3b0db6d9051475874d6
```

Why don't we use a regular table like kubectl uses without pipe separators? It makes it harder to wrap scripts around minikube when we are doing this. I would expect something like this instead: 
```text
PROFILE   VM DRIVER   NODEIP          NODE PORT  KUBERNETES VERSION       
minikube  virtualbox  192.168.99.169  8443       v1.16.0
```

**Comment by woodcockjosh** [comment]
This issue needs to be resolved before I can open a PR https://github.com/olekukonko/tablewriter/issues/129

**Comment by medyagh** [comment]
while I agree to match kubernetes style as much possible, changing this would be a breaking change,

but I purpose ! having the option for the users to have the output in different ways

- json (this is actually important for people who build tools on top of minikube)
- no table
- table
- custom format, we already support this but needs more documentation and examples and maybe unify it across all commands.

**Comment by woodcockjosh** [comment]
Yea, I wanted to build something on top of minikube and I saw this really crazy table output and thought. Why don't I just help them become normal :-D. Anyway. The breaking change part I'm not really following. You mean if people built a tool that wraps the shell command? Ok fine you're right but we have to live with that table format forever? gah. I personally would be fine if you just had a json format for now as it would solve my use case.

**Comment by tstromberg** [comment]
I personally am OK with breaking users who parse stdout of commands unless they have defined a `--format` parameter.

Related: #5080 - it sounds like we should have an analogous issue for profile.

**Comment by medyagh** [comment]
I would happily review a PR that addresses this issue, having json output would make a lot of people happy !
