### ISSUE TITLE
Ingress - Could not resolve host error

### ISSUE THREAD

**Issue by shintoantony** [kubernetes/minikube#5496]
Hi , 

Minikube version : v1.4.0

Issue : The host which is exposed as ingress is having the error ; could not resolve host <hostnam>

The hostname is add wit the minikube ip in /etc/hosts 

Can some one tell me what is this issue ?

The ingress is mapped to a 10 series ip address rather than minikube ip.

Thanks

**Comment by woodcockjosh** [comment]
@shintoantony can you lease provide example code and configurations?

**Comment by shintoantony** [comment]
@woodcockjosh 

I have used helm charts 

values.yaml
  replicaCount: 1
  image:
    repository: dockerfile
    tag: v5
    pullPolicy: IfNotPresent
  service:
    type: NodePort
    port: 2206
  ingress:
    enabled: true
    path: /
    hosts:
      - jm.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"


ingress.yml

{{- if .Values.ingress.enabled -}}
{{- $fullName := include "java-app.fullname" . -}}
{{- $serviceName := include "java-app.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}-ing
  labels:
{{ include "java-app.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /status
            backend:
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
        {{- end }}
  {{- end }}

/etc/hosts
192.168.99.118 jm.example.com

minikube ip  : 192.168.99.118

**Comment by woodcockjosh** [comment]
@shintoantony My recommendation would be to first ask this question in the [kubernetes slack workspace in the #m](https://kubernetes.slack.com/app_redirect?channel=minikube) to confirm that this is a problem with minikube. Presently it looks like a configuration issue. When I add an entry in `/etc/hosts/` for `192.168.99.169 jm.example.com` then I run ` http://jm.example.com` I get: 
```
<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>openresty/1.15.8.1</center>
</body>
</html>
```
Which means the host name is resolving.

**Comment by shintoantony** [comment]
@woodcockjosh 

you are correct. Let me check in minikube slack channel.I am not a member of this slack . I may need an invitation i believe . Will you be able to do that for me 

Thanks

**Comment by woodcockjosh** [comment]
@shintoantony anyone can join

**Comment by shintoantony** [comment]
The issue is fixed . The host entry was made to the Windows machine. 
Thanks @woodcockjosh
