### ISSUE TITLE
proposal: add host OS addon hooks

### ISSUE THREAD

**Issue by woodcockjosh** [kubernetes/minikube#5498]
In order to provide a richer and more simplified development experience, some addons may be better equipped if they can be integrated with capabilities that run on the Host OS. 

The hooks would be ran as part of the addon lifecycle: 
- pre enable
- post enable
- pre disable
- post disable

## Example use cases:
- Running a service on the Host OS that updates resolver configuration files or the `/etc/hosts` file with ingress resources in a cluster so that DNS can be resolved. This would utilize the `post-enable` hook which would start service on the host OS and a `pre-disable` hook which would stop the service on the host OS. See https://github.com/kubernetes/minikube/issues/5494
- Richer integration with 3rd part tools that run on the Host OS like skaffold and integrated development environments like intelliJ
- Creation of an integrated debuging client that allows debugging of k8s resources with a step-by-step debugger like xdebug

## Options
- run as sudo: Whether or not to run the hook with sudo permissions. This would require the user to enter their sudo password after running `minikube addon enable`

## Other considerations
These hooks could also open the door for contributors to start to create "external addons" which would be an addon that can be used with minikube but not part of the minikube codebase. Very similar to how helm enables you to create plugins which are not a part of helm through the use of hooks.

**Comment by woodcockjosh** [comment]
https://github.com/kubernetes/minikube/pull/5505

**Comment by woodcockjosh** [comment]
Use case addon for this webhook: https://github.com/kubernetes/minikube/pull/5507

**Comment by tstromberg** [comment]
Closing as this proposal appears to be on hold.
