### ISSUE TITLE
Localkube should vendor kube-dns instead of the current kube2sky solution

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#55]
Ref: https://github.com/kubernetes/kubernetes/pull/23930

**Comment by luxas** [comment]
kubernetes/kubernetes#23930 was merged :)
Let's update Godeps and write a new DNSServer

**Comment by dlorenc** [comment]
FYI I started updating godeps, but got blocked on a k8s.io/kubernetes appc/spec incompatibility. We'll need this PR to get merged before we can continue: https://github.com/appc/spec/pull/607

**Comment by luxas** [comment]
Yes, I also started updating to head, and hit the same error.

**Comment by luxas** [comment]
I started to think if it's easier to deploy DNS as an addon instead of built-in in the binary...
That way we would be much more compatible with "real" solutions. Also, the new DNS solution uses `dnsmasq` for caching (I think), and it might be easier to just deploy them together as a Pod.

@dlorenc WDYT? Our localkube code would also get cleaner...

**Comment by dlorenc** [comment]
@luxas I'm concerned about the size of the image that people would have to pull. Any idea how large it is?

**Comment by luxas** [comment]
~50MB. That's quite much.
But anyway, I'm concerned about the `dnsmasq` dep... (Although it might be a soft dep)

**Comment by dlorenc** [comment]
I'm going to move this out of the milestone. We should come up with a plan here soon. Running as a pod might be the right approach.

**Comment by luxas** [comment]
I'm leaning against going with the "official" kube-dns solution.
Then we won't have any compability problems. 

I've already added a flag, --enable-dns which you may just set to false when adding the manifest

**Comment by philips** [comment]
It would be nice to make the kube-dns container smaller or something. The problem I see with not using the normal add-on is it makes the minikube cluster "more special". 

For example this debugging guide doesn't work: https://coreos.com/kubernetes/docs/latest/network-troubleshooting.html#first-stop-dns-debugging

**Comment by philips** [comment]
Thoughts @ethernetdan ?

**Comment by dlorenc** [comment]
+1 on switching to the standard DNS addon model.

**Comment by philips** [comment]
@dlorenc another datapoint is today during my k8s workshop at LinuxCon EU someone asked about how to replace the DNS implementation and I was using minikube so I had to say "On a normal k8s cluster you can do that, minikube is special"

**Comment by ethernetdan** [comment]
+1 for add-on - minikube should mirror best practices where possible

I was able to get the kube-dns executable down to 28mb from 42mb by omitting symbol and debug info with `make kube-dns GOLDFLAGS="--s -w"`
