### ISSUE TITLE
proposal: Remove repetitive addon configurations

### ISSUE THREAD

**Issue by woodcockjosh** [kubernetes/minikube#5501]
There are a lot of repetitive configurations in: 
[addons.go](https://github.com/kubernetes/minikube/blob/668146d10238d7a35e2fe918239cfadb2c413773/pkg/minikube/assets/addons.go)

Instead of providing a list of configurations via`MustBinAsset` we can create a class that is able to generate a list of `MustBinAsset` classes based on the plugin name. We can also include a class that generates the addons so that the map key is always the the same as the plugin name. 
1. If the file ends in .tpl then it is a template
2. The default directory is `vmpath.GuestAddonsDir`
3. The default permissions are `0644`
4. The default plugin directory with the files in it is `deploy/addons/`
5. By default the plugin is disabled. This can be overwritten in the new class to be true.
6. They keyname of the map that its generated is the same as the plugin name. 

This would look something like this: 
```go
var AddOnConfig = new AddOnConfigs();
AddOnConfig.Add(new DefaultAddonConfig("dashboard");
AddOnConfig.Add(new DefaultAddonConfig("default-storageclass", map[string]interface{}{"enabled": true});
// etc, etc, etc
var Addons = AddOnConfig.GetMap();
```

To take this a step further we can eliminate contributors having to create an entry in this file all together if we create an optional file inside each addon directory of `config.json` with a value of
```json
{"enabled": true }
```

**Comment by tstromberg** [comment]
This seems a reasonable approach, but my preference is that we skip this intermediate step and head straight for what you insinuate at the end: make it easier for developers to create addons by eliminating the necessity for them to modify `addons.go` at all.

I have some thoughts around addons (hence why it is coyly called out in the 2020 roadmap), and would love to work with you on a more ambitious proposal. I would like a much richer 3rd party ecosystem, which will require it to be trivial for developers to add/update addons. Basically, something modeled more closely on other open source packaging systems.

- A `minikube addons update` command to pull down recent addon changes
- Support for standard `kubectl apply` YAML files. 
- Support for resource hints (this addon requires 2 CPU's, 4096MB of memory)
- Metadata with description & ownership info

There is certainly more pie-in-the-sky possibilities, like variants and plumbing configuration in, but I'd rather defer to a second iteration.

Thoughts?

**Comment by woodcockjosh** [comment]
I guess you have thought about it more than me. I can only defer to my own experience in creating an addon. In consideration of potentially a larger scale effort it might be preferable to ditch the word addon for plugin as I believe this word is more commonly used and could be a migration path for backwards compatibility. For example `plugin` can be used as an alias for the `addon` command but support additional features. I would love to help you with such an effort but wouldn't want to impede any milestones as I am somewhat of a newbie to go.

**Comment by woodcockjosh** [comment]
Tabling this to focus on more comprehensive refactoring of addons as discussed in office hours
