### ISSUE TITLE
Cannot enable addons if minikube instance is not running

### ISSUE THREAD

**Issue by woodcockjosh** [kubernetes/minikube#5510]
**The exact command to reproduce the issue**:
```bash
minikube addons enable ingress
```

**The full output of the command that failed**:<details>
💣  minikube is not running, so the service cannot be accessed
</details>

**The output of the `minikube logs` command**:<details>

💣  api load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Mac OS 10.14.6

Maybe this is part of the minikube design but since addons are not tied to any 1 particular machine why does a machine have to be running in order to enable an addon? At least I think the error message should say something like `In order to enable an addon at least 1 machine must be running` however I think this should be fixed so that addons can be enabled without having a machine running.

**Comment by medyagh** [comment]
Thanks for creating this issue,
the lease  we could provide a better solution message ( please start minikube before enabling addons)

**Comment by medyagh** [comment]
long term would be nice to allow enabling addons even if it is stopped

**Comment by woodcockjosh** [comment]
wahoo!
