### ISSUE TITLE
hyperv: Unable to start VM: create: creating: exit status 1

### ISSUE THREAD

**Issue by clombardo1** [kubernetes/minikube#5515]
**The exact command to reproduce the issue**:
<details>
PS C:\WINDOWS\system32> minikube start
</details>

**The full output of the command that failed**:
<details>
* minikube v1.4.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
*
X Unable to start VM: create: creating: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32>
</details>

**The output of the `minikube logs` command**:<details>
PS C:\WINDOWS\system32> minikube logs
*
X api load: filestore "minikube": open C:\Users\clombardo\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32>
</details>

**The operating system version**:
Microsoft Windows 10 Pro Version 10.0.18362 Build 18362

**Comment by tstromberg** [comment]
Related: #5453

**Comment by sharifelgamal** [comment]
@clombardo1 Could you retry this running the newest version of minikube and with the `--alsologtostderr` parameter? We added some debugging that could be helpful.

**Comment by priyawadhwa** [comment]
Hey @clombardo1 -- 

Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
