### ISSUE TITLE
Use the minikube IP for the hostname

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#5528]
Currently libmachine sets the IP of the current host to 127.0.1.1, matching Debian:

/etc/hostname
```
minikube
```

/etc/hosts
```
127.0.0.1   localhost
127.0.1.1   minikube
```

https://github.com/docker/machine/blob/v0.16.1/libmachine/provision/generic.go#L39_L65

----

https://www.debian.org/doc/manuals/debian-reference/ch05.en.html#_the_hostname_resolution

> The IP address 127.0.1.1 in the second line of this example may not be found on some other Unix-like systems. The Debian Installer creates this entry for a system without a permanent IP address as a workaround for some software (e.g., GNOME) as documented in the bug #719621.
> 
> The <host_name> matches the hostname defined in the "/etc/hostname".
> 
> **For a system with a permanent IP address, that permanent IP address should be used here instead of 127.0.1.1.**

So we should really be using the same IP address as `minikube ip` uses, for /etc/hosts.

**Comment by medyagh** [comment]
Sounds reasonable. Only thing we need to make sure, if minikube ip changes, it updates the hosts file too.

**Comment by sharifelgamal** [comment]
Yeah, this is something we eventually want to do.

**Comment by prasadkatti** [comment]
So I guess this needs to happen only for the VM-based drivers and only for the ones that use the Ubuntu provisioner, right? I am using the hyperkit driver and that seems to use the buildroot provisioner.

**Comment by medyagh** [comment]
@afbjorklund  after @tstromberg adding host aias to /etc/hosts do we still need to do this ?
