### ISSUE TITLE
start/delete fails: open C:\Users\.minikube\machines\minikube\config.json: The system cannot find the file specified.

### ISSUE THREAD

**Issue by vivekwpatil** [kubernetes/minikube#5529]
I downloaded minikube in my windows 7 laptop. I installed it successfully. but when I try to run below command, it fails with below message. I tried minikube delete command also but it also fails. Not sure how to proceed . Please help,

$ minikube start
* minikube v1.4.0 on Microsoft Windows 7 Enterprise Service Pack 1 6.1.7601 Build 7601
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\\.minikube\machines\minikube\config.jso
n: The system cannot find the file specified.
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run 

[minikube start] again.: filestore "minikube": open C:\Users\\.minikube\machines\minikube\config.jso
n: The system cannot find the file specified.
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\\.minikube\machines\minikube\config.jso
n: The system cannot find the file specified.
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\\.minikube\machines\minikube\config.jso
n: The system cannot find the file specified.
*
X Unable to start VM: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\\.minikube\machines\minikube\config.js
on: The system cannot find the file specified.

**Comment by woodcockjosh** [comment]
Looks like the same problem as here https://github.com/kubernetes/minikube/issues/5509. Try deleting `C:\Users\.minikube\machines\minikube\` then run `minikube start` again.

**Comment by vivekwpatil** [comment]
Thanks. It starts after manually deleting that folder. I suppose minikube delete command should be  taking care of this operation.

**Comment by woodcockjosh** [comment]
I think this can also occur if you run `start minikube` then cancel the command after the json file is created but before the machine instance is created.

**Comment by tstromberg** [comment]
Do you mind sharing what the error was when you ran `minikube delete`?

**Comment by tstromberg** [comment]
minikube appears to be doing a very weird thing with the path here (not surprising on Windows). Note that there is no actual home directory mentioned in the path.

**Comment by vivekwpatil** [comment]
when I try `minikube delete` it also tries to locate same config file and fails.

**Comment by medyagh** [comment]
@vivekwpatil I am wondering are you running the minikube command while you are in C:\ drive ?

**Comment by brainfull** [comment]
On my side, everytime I call 'minikube delete' I also delete automatically %userprofile%/.minikube. It resolves a lot of weird behavior and doesn't create unwanted side effect, at least for me.
