### ISSUE TITLE
Storage-provisioner not found when using image-repository

### ISSUE THREAD

**Issue by Atvo** [kubernetes/minikube#5539]
**Overview of the issue**:
In the company I work for we use a firewall to block connections to public repositories. Instead, we use proxied repositories to connect to any 3rd party libraries. In the case of minikube this simply means that I pass the image-repository argument when starting a cluster. However, this doesn't work perfectly, because it can't find the storage-provisioner image, which isn't located in the same repository.

**The exact command to reproduce the issue**:
 minikube start --iso-url="http://repository.company.com/github/kubernetes/minikube/releases/download/v1.4.0/minikube-v1.4.0.iso" --image-repository="k8s-gcr-io.repository.company.com"

**The full output of the command that failed**:<details>
! minikube v1.4.0 on Microsoft Windows 10 Enterprise 10.0.16299 Build 16299
* Using image repository k8s-gcr-io.repository.company.com
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E1004 09:03:00.107970   17492 cache_images.go:79] CacheImage k8s-gcr-io.repository.company.com/storage-provisioner:v1.8.1 -> C:\Users\username\\.minikube\cache\images\k8s-gcr-io.repository.company.com\storage-provisioner_v1.8.1 failed: MANIFEST_UNKNOWN: "The named manifest is not known to the registry."
E1004 09:03:59.747316   17492 cache_images.go:79] CacheImage kubernetesui/dashboard:v2.0.0-beta4 -> C:\Users\username\\.minikube\cache\images\kubernetesui\dashboard_v2.0.0-beta4 failed: fetching image: Get https://index.docker.io/v2/: dial tcp 34.201.202.217:443: i/o timeout
* Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...
E1004 09:04:09.147345   17492 start.go:706] Error caching images:  Caching images for kubeadm: caching images: caching image C:\Users\username\\.minikube\cache\images\k8s-gcr-io.repository.company.com\storage-provisioner_v1.8.1: MANIFEST_UNKNOWN: "The named manifest is not known to the registry."
* Unable to load cached images: loading cached images: loading image C:\Users\username\\.minikube\cache\images\k8s-gcr-io.repository.company.com\storage-provisioner_v1.8.1: CreateFile C:\Users\username\\.minikube\cache\images\k8s-gcr-io.repository.company.com\storage-provisioner_v1.8.1: The system cannot find the file specified.
* Pulling images ...
* Launching Kubernetes ...
* Waiting for: apiserver proxy etcd scheduler controller dns
* Done! kubectl is now configured to use "minikube"

</details>

**The output of the `minikube logs` command**:<details>
* Oct 04 06:06:46 minikube kubelet[3249]: E1004 06:06:46.265557    3249 remote_image.go:113] PullImage "k8s-gcr-io.repository.company.com/storage-provisioner:v1.8.1" from image service failed: rpc error: code = Unknown desc = Error response from daemon: manifest for k8s-gcr-io.repository.company.com/storage-provisioner:v1.8.1 not found
* Oct 04 06:06:46 minikube kubelet[3249]: E1004 06:06:46.265593    3249 kuberuntime_image.go:50] Pull image "k8s-gcr-io.repository.company.com/storage-provisioner:v1.8.1" failed: rpc error: code = Unknown desc = Error response from daemon: manifest for k8s-gcr-io.repository.company.com/storage-provisioner:v1.8.1 not found
* Oct 04 06:06:46 minikube kubelet[3249]: E1004 06:06:46.265720    3249 kuberuntime_manager.go:783] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: manifest for k8s-gcr-io.repository.company.com/storage-provisioner:v1.8.1 not found
* Oct 04 06:06:46 minikube kubelet[3249]: E1004 06:06:46.265761    3249 pod_workers.go:191] Error syncing pod 9a449d1c-4701-40be-819f-ab0c0b978cf1 ("storage-provisioner_kube-system(9a449d1c-4701-40be-819f-ab0c0b978cf1)"), skipping: failed to "StartContainer" for "storage-provisioner" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: manifest for k8s-gcr-io.repository.company.com/storage-provisioner:v1.8.1 not found"

</details>

**The operating system version**:
Windows 10

By checking the source code it seems that if the user gives the image-repository argument, minikube assumes that all the images are located in that repository. Is there any way to work around this issue (e.g. by passing multiple repositories)? I know that I could set the Docker environment variables for proxy information, but this isn't recommended (and it seems to result in much slower download speeds as well).

PS. I'm also unable to download the dashboard image, but this isn't an issue for me.

**Comment by tstromberg** [comment]
Have you tried adding the storage provisioner to this registry?

**Comment by Atvo** [comment]
> 
> 
> Have you tried adding the storage provisioner image to this registry?
> 
> The storage provisioner is specific to minikube, hence it probably not existing in your companies mirror already.

I asked the admins of the registry but apparently that is not an option.

**Comment by tstromberg** [comment]
I'm not sure there is anything we can do here: if the container image isn't available, it isn't possible to run this pod.

Is there an alternative you recommend?

**Comment by Atvo** [comment]
No I guess not. My wish would be that it would be possible to submit a list of repositories from where the images would be downloaded. But I do realize this is a quite specific issue, and I don't expect that many are affected by this, so fixing this has probably quite low priority.

BTW, I'm still able to use Minikube by using proxies, but it isn't an optimal solution.

**Comment by tstromberg** [comment]
@Atvo - is there a different repository that would have this image that you could use?

As far as I know, the underlying image pull code in Kubernetes doesn't allow for multiple repositories, but we could hard-code something for a repository to pull this specific addon from.

**Comment by priyawadhwa** [comment]
Hey @Atvo, are you still seeing this issue?

**Comment by Atvo** [comment]
> 
> 
> Hey @Atvo, are you still seeing this issue?

Hi, I've moved to using a proper Kubernetes cluster instead of Minikube

**Comment by tstromberg** [comment]
Closing, as the fix is to make sure that the image repository contains all of the images used by minikube.
