### ISSUE TITLE
none: start timeout  k8s-app=kube-dns

### ISSUE THREAD

**Issue by anthonma** [kubernetes/minikube#5540]
I'm trying to run a Kubernetes cluster with minikube, but minikube seems to start not properly.

When I execute the comand minikube start --memory=4096 --kubernetes-version=v1.15.4 --vm-driver=none I get an error saying: Error: [DNS_TIMEOUT] witing for k8s-app=kube-dns: timed out waiting for condition.
The cluster starts but when I look at the pods with kubectl get pods --all-namespaces there are some pods pending and two evicted:
![pods](https://user-images.githubusercontent.com/55550413/66198103-f9655d80-e69b-11e9-9fe1-1a4314e276e9.PNG)

### OS:
Centos 7 vm

### minikube version
v1.4.0

### Steps to reproduce:
execute minikube start --memory=4096 --kubernetes-version=v1.15.4 --vm-driver=none

### Output of failing command:
![minikube_ERROR](https://user-images.githubusercontent.com/55550413/66197717-4ac11d00-e69b-11e9-84ca-813acb347f30.PNG)

**Comment by afbjorklund** [comment]
Did you disable SELinux, `setenforce 0` ?

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

**Comment by priyawadhwa** [comment]
Hey @anthonma, are you still seeing this issue?

**Comment by anthonma** [comment]
The problem is that the VM has not enough disk space. But since I probably will use another VM, I will close this issue.
