### ISSUE TITLE
vbox win8: Error restarting cluster: waiting for apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by Kriss007** [kubernetes/minikube#5553]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>
C:\Users\kr>minikube start
* minikube v1.4.0 on Microsoft Windows 8 Pro 6.2.9200 Build 9200
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube dele
te' to delete this one.
* Using the running virtualbox "minikube" VM ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...
* Relaunching Kubernetes using kubeadm ...
*
X Error restarting cluster: waiting for apiserver: timed out waiting for the con
dition
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear fro
m you:
  - https://github.com/kubernetes/minikube/issues/new/choose

**The output of the `minikube logs` command**:<details>
* Oct 07 12:51:20 minikube kubelet[23013]: E1007 12:51:20.596615   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:20 minikube kubelet[23013]: E1007 12:51:20.601845   23013 kubelet
_node_status.go:94] Unable to register node "minikube" with API server: Post htt
ps://localhost:8443/api/v1/nodes: dial tcp 127.0.0.1:8443: connect: connection r
efused
* Oct 07 12:51:20 minikube kubelet[23013]: E1007 12:51:20.699313   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:20 minikube kubelet[23013]: E1007 12:51:20.800862   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:20 minikube kubelet[23013]: E1007 12:51:20.804869   23013 reflect
or.go:123] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list
*v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dmi
nikube&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection
 refused
* Oct 07 12:51:20 minikube kubelet[23013]: E1007 12:51:20.902773   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.003134   23013 reflect
or.go:123] k8s.io/kubernetes/pkg/kubelet/kubelet.go:450: Failed to list *v1.Serv
ice: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dia
l tcp 127.0.0.1:8443: connect: connection refused
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.006194   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.108618   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.202496   23013 reflect
or.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CS
IDriver: Get https://localhost:8443/apis/storage.k8s.io/v1beta1/csidrivers?limit
=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.214756   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.316063   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.403538   23013 reflect
or.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.Ru
ntimeClass: Get https://localhost:8443/apis/node.k8s.io/v1beta1/runtimeclasses?l
imit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused

* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.416897   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.518122   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.603719   23013 reflect
or.go:123] k8s.io/kubernetes/pkg/kubelet/kubelet.go:459: Failed to list *v1.Node
: Get https://localhost:8443/api/v1/nodes?fieldSelector=metadata.name%3Dminikube
&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refus
ed
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.619120   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.720058   23013 kubelet
.go:2267] node "minikube" not found
* Oct 07 12:51:21 minikube kubelet[23013]: E1007 12:51:21.809794   23013 reflect
or.go:123] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list
*v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dmi
nikube&limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection
 refused

**The operating system version**: -- Windows 8 Pro

**Comment by tstromberg** [comment]
The output of `minikube logs` seems to be incomplete. Do you mind checking if `minikube delete` fixes the issue for you?

If not, please share the complete output of:

`minikube start --alsologtostderr -v=1`
`minikube logs`

Thank you!

**Comment by Kriss007** [comment]
Yes.

**Comment by tstromberg** [comment]
@Kriss007 - Do you mind upgrading to the latest minikube and sharing the output of:

`minikube delete`
`minikube start --alsologtostderr`

Thanks! 

My suspicion here is that  the VirtualBox network interface is not functioning properly,  which is something that minikube v1.5.x does a much better job of noticing. Also, check if you have a VPN or unusual firewall configuration.

**Comment by priyawadhwa** [comment]
Hey @Kriss007 , hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

I'd recommend upgrading to the [latest version](https://minikube.sigs.k8s.io/docs/start/windows/) of minikube and running:

```
minikube delete
minikube start --alsologtostderr
```

if that fails again, please open a new issue and include the output from the failed command. Thank you!
