### ISSUE TITLE
minikube stop working after upgrade to macOs Catalina

### ISSUE THREAD

**Issue by franxois** [kubernetes/minikube#5568]
**The exact command to reproduce the issue**:

minikube version

**The full output of the command that failed**:<details>

Original message in french
```
Impossible d’ouvrir « minikube-darwin-amd64 » car le développeur ne peut pas être vérifié.
macOS ne peut pas vérifier que cette app ne contient aucun logiciel malveillant.
Homebrew Cask a téléchargé ce fichier le 20 septembre 2019 depuis github.com.

```

That says Unable to open minikube because macOS can't verify this app

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

This appends just after upgrade to macOS Catalina  10.15

minikube installed with `brew cask`

**Comment by afbjorklund** [comment]
Taking “closed” to a whole new level...

> Mac apps, installer packages, and kernel extensions that are signed with Developer ID must also be notarized by Apple in order to run on macOS Catalina.

Guess minikube has to get a Developer ID for the App Store ?

**Comment by afbjorklund** [comment]
The “open anyway” button has now been removed:
https://support.apple.com/en-us/HT202491

**Comment by franxois** [comment]
I don't have the open anyway button in settings but it look like I added an exception by using a first time "open with" Terminal.app on the binary in finder. 
Now I can run minikube

**Comment by tdensmore** [comment]
Also using `sudo spctl --master-disable` should allow most command line binaries to work

![image](https://user-images.githubusercontent.com/469399/66485286-934f5080-ea76-11e9-9ad3-97be079d59ce.png)

http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/

**Comment by myersg86** [comment]
[Allow apps from anywhere](http://osxdaily.com/2016/09/27/allow-apps-from-anywhere-macos-gatekeeper/) and `sudo spctl --master-disable` disable protections that can potentially leave a Mac vulnerable to malware, and should be avoided if at all possible. This is not an ideal solution.

After taking the following steps, I now seem to have an "Open anyways" option now, allowing running individual applications without disabling secure defaults.

Here's what I did, not sure if all steps are relevant:

- Switch `spctl` off and on:
```bash
sudo spctl --master-disable
sudo spctl --master-enable
```
- Set "Allow apps downloaded from: **App Store**" in Security and Privacy
- Reboot

**Comment by benjma** [comment]
![Screen Shot 2019-10-11 at 5 52 03 pm](https://user-images.githubusercontent.com/322797/66630561-4030f580-ec50-11e9-8ab0-a9b6b148386b.png)

Maybe, "Allow Anyway" just for "minikube-darwin-amd64"

**Comment by findpritish** [comment]
**Switch spctl off**

`sudo spctl --master-disable`

`brew cask install minikube`
`minikube start`

**Switch spctl off**

`sudo spctl --master-enable`

**Comment by afbjorklund** [comment]
I'm not sure how this "new" Apple requirement can be integrated into minikube release process:

https://developer.apple.com/developer-id/

https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution

Maybe @tstromberg can take a look at if and how such a workflow could be added to the CI ?

**Comment by edreams** [comment]
sudo chown root:wheel /Users/chile/.minikube/bin/docker-machine-driver-hyperkit 
sudo chmod u+s /Users/chile/.minikube/bin/docker-machine-driver-hyperkit

**Comment by tstromberg** [comment]
Related: #5792

**Comment by pre** [comment]
Came here to document that my issue in Catalina was that hyperkit requires Docker for Mac. Withtout it, minikube either hangs (using `minikube start -p profile`) or crashes (`minikube start`).
My installation didn't even get to the "minikube was blocked" security message. 

My problem was solved by launching Docker for Mac which then asked security privileges for itself. After that, minikube was able to start.

Related: https://github.com/kubernetes/minikube/issues/5811#issuecomment-565573483

**Comment by mjgallag** [comment]
New version of `hyperkit` with Cataline fix is finally available on `Homebrew`, see https://github.com/Homebrew/homebrew-core/pull/50655 & https://github.com/moby/hyperkit/issues/267 for details.
