### ISSUE TITLE
detect connectivity problem to image repository before start

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5570]
rather than spinning up minikube and wait and retry and then crashing it would be nicer,
if minikube tries to ping or check the network connectivity to gcr (or whatever image repository specified) and if it there is no network connection minikube should nicely not continue and recommend the user to start with correct image-repos options 

related:

https://github.com/kubernetes/minikube/issues/5531

**Comment by brennerm** [comment]
Not sure if that check is properly executable. Think about a case where the machine that runs minikube is not able to reach the registry but by using e.g. the --kvm-qemu-uri or --kvm-network flag the VM would eventually be able to.

In this case you would still need to start the VM and execute the check afterwards. Alternatively you could execute the check locally and make it skippable with a flag. Let me know what you think.
