### ISSUE TITLE
hyperv: Retriable failure: create: creating: exit status 1 / retry fails to delete

### ISSUE THREAD

**Issue by jeff2u** [kubernetes/minikube#5580]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

C:\Users\jlim>minikube start --vm-driver hyperv --hyperv-virtual-switch "minikube v switch"
* minikube v1.4.0 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Downloading VM boot image ...
    > minikube-v1.4.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.4.0.iso: 135.73 MiB / 135.73 MiB  100.00% 219.62 KiB p/s 10m3
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\jlim\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\jlim\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\jlim\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X Unable to start VM: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\jlim\.minikube\machines\minikube\config.json: The system cannot find the file specified.

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by ThomasSchoenbeck** [comment]
I was facing this issue as well until i started a command prompt with administrator privileges.

**Comment by meauses** [comment]
> I was facing this issue as well until i started a command prompt with administrator privileges.

I started with a elevated command prompt, but I'm still getting the error.

**Comment by tstromberg** [comment]
@jeff2u - Do you mind upgrading to minikube v1.5.x and including the output of:

`minikube start  --alsologtostderr -v=1`

We added some debugging information  which will help.

**Comment by brainfull** [comment]
On my side, everytime I call 'minikube delete' I also delete automatically %userprofile%/.minikube. It resolves a lot of weird behavior and doesn't create unwanted side effect, at least for me.

**Comment by priyawadhwa** [comment]
Hey @jeff2u are you still seeing this issue?

**Comment by medyagh** [comment]
@jeff2u I will close this issue, please feel free to reopen
I also suggest to try our new driver docker, 
```
minikube start --vm-driver=docker
```
