### ISSUE TITLE
hyperkit macOS catalina: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

### ISSUE THREAD

**Issue by ashkan-leo** [kubernetes/minikube#5594]
I am unable to start minikube with hyperkit on mac OS Catalina. I was able to run minikube before upgrading to Catalina.

**The exact command to reproduce the issue**:

`minikube stop && minikube delete && minikube start --vm-driver=hyperkit`

**The full output of the command that failed**:<details>

✋  Stopping "minikube" in virtualbox ...
🛑  "minikube" stopped.
🔥  Deleting "minikube" in virtualbox ...
💔  The "minikube" cluster has been deleted.
😄  minikube v1.4.0 on Darwin 10.15
🔥  Creating hyperkit VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Deleting "minikube" in hyperkit ...
E1010 22:01:41.581336   38132 main.go:100] libmachine: (minikube) Error reading pid file: open /Users/ashkanaleali/.minikube/machines/minikube/hyperkit.json: no such file or directory
🔥  Creating hyperkit VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Deleting "minikube" in hyperkit ...
E1010 22:01:49.012099   38132 main.go:100] libmachine: (minikube) Error reading pid file: open /Users/ashkanaleali/.minikube/machines/minikube/hyperkit.json: no such file or directory
🔥  Creating hyperkit VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Deleting "minikube" in hyperkit ...
E1010 22:01:58.676325   38132 main.go:100] libmachine: (minikube) Error reading pid file: open /Users/ashkanaleali/.minikube/machines/minikube/hyperkit.json: no such file or directory
🔥  Creating hyperkit VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Deleting "minikube" in hyperkit ...
E1010 22:02:14.547227   38132 main.go:100] libmachine: (minikube) Error reading pid file: open /Users/ashkanaleali/.minikube/machines/minikube/hyperkit.json: no such file or directory

💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

💣  api load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**: mac OS 10.15

**Comment by nanikjava** [comment]
Try deleting the /Users/ashkanaleali/.minikube directory and start minikube again and see if that helps

**Comment by ashkan-leo** [comment]
I deleted that directory. It didn't help.

**Comment by derekbelrose** [comment]
Stock Catalina without disabling any security measures and a fresh install with `brew install minikube`. When running `minikube config set vm-driver hyperkit` I get the following error:

"minikube-darwin-amd64" cannot be opened because the developer cannot be verified.

**Comment by tstromberg** [comment]
I suspect there is some kind of Catalina-specific permissions issue going on, but it could also be some other kind of API mismatch. I don't have a Catalina host to check against yet.

**Comment by medyagh** [comment]
I think this is related to https://github.com/kubernetes/minikube/issues/5610
and there is a upstream PR in hyperkit that seems to be addressing hyperkit issue on catalina https://github.com/moby/hyperkit/pull/263

**Comment by medyagh** [comment]
@ashkan-leo 
I myself get this error, I suspect this is related to the latest verison of Docker
```
 $ docker version
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false
```

do you mind sharing the version of docker"

**Comment by medyagh** [comment]
@ashkan-leo @natebrunette
do you mind sharing also your hyperkit version ?

```
hyperkit -v
```

one thing I noticed brew upgrade did NOT upgrade my hyperkit version ! which made debugging this issue more complicated.

**Comment by natebrunette** [comment]
@medyagh I forgot to mention, I built hyperkit from master and all of my issues are resolved (re: #5610)

**Comment by medyagh** [comment]
Excellent @natebrunette thank you so much for getting back to me !

I also confirm that upgrading both my docker and hyperkit driver fixed my issue too.
here are the versions on my mac machine:

```
$ hyperkit -v
hyperkit: v0.20190201-11-gc0dd46

Homepage: https://github.com/docker/hyperkit
License: BSD
```
$ docker version
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
```

it worth noting that brew upgrade failed to upgrade my hyperkit. so I had to manually delete it.
anyone else has the issue here are the commands :

```
brew uninstall hyperkit
rm $(which hyperkit)
brew install hyerpkit
hyperkit -v
```

also make sure you download latest version of docker desktop from https://www.docker.com/products/docker-desktop

**Comment by natebrunette** [comment]
so the new release is already tagged?

**Comment by fredsted** [comment]
Neither HyperKit version `0.20190201` nor `0.20190802` works on my machine. 

Using minikube 1.5.2, hyperkit 0.20190802 and macOS 10.15.0

**Comment by mjgallag** [comment]
Since it's been a few months now I'm trying to get a release tagged so we can get this update into Homebrew, see https://github.com/moby/hyperkit/issues/267.

**Comment by mjgallag** [comment]
New version of `hyperkit` with Cataline fix is finally available on `Homebrew`, see https://github.com/Homebrew/homebrew-core/pull/50655 & https://github.com/moby/hyperkit/issues/267 for details.

**Comment by BoKleynen** [comment]
I seem to also get this problem on the latest version of hyperkit when my mac's internet sharing is turned on

**Comment by mglidden** [comment]
Hmm... I also had internet sharing turned on and got this issue. I wonder if that's the root cause of the issue? None of my co-workers were running into it.

**Comment by tstromberg** [comment]
I ran into this today, and strangely enough, re-running minikube got past the issue. This was with `hyperkit: v0.20190802-4-g97f091`.

**Comment by cglacet** [comment]
Still having this message on the latest version (I also have internet sharing over wifi on). Any solution for this?

**Comment by medyagh** [comment]
@cglacet do you mind sharing output with latest verison of minikube?

**Comment by cglacet** [comment]
@medyagh I think I found a solution the other time, but I can't find it again (I think I just switched to virtualbox).

Here is the output I have:

```bash
❯ minikube start --memory 2048
😄  minikube v1.17.1 on Darwin 11.0.1
🆕  Kubernetes 1.20.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.20.2
✨  Using the hyperkit driver based on existing profile
💿  Downloading VM boot image ...
    > minikube-v1.17.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.17.0.iso: 212.69 MiB / 212.69 MiB [] 100.00% 41.53 MiB p/s 5s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.19.2 preload ...
    > preloaded-images-k8s-v8-v1....: 487.14 MiB / 487.14 MiB  100.00% 55.65 Mi
🔄  Restarting existing hyperkit VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔄  Restarting existing hyperkit VM for "minikube" ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1


❌  Exiting due to PR_HYPERKIT_VMNET_FRAMEWORK: Failed to start host: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

💡  Suggestion: Hyperkit networking is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --driver
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6028
    ▪ https://github.com/kubernetes/minikube/issues/5594
```

* minikube: 1.17.1
* hyperkit 0.20200908

**Comment by frnhr** [comment]
Same in 2021 on BigSur 😞 

```
$ docker -v
Docker version 20.10.2, build 2291f61
$ hyperkit -v
hyperkit: 0.20200908

Homepage: https://github.com/docker/hyperkit
License: BSD

$ minikube start --driver=hyperkit
😄  minikube v1.17.1 on Darwin 11.2.1
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🔥  Deleting "minikube" in hyperkit ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Creating hyperkit VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
😿  Failed to start hyperkit VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1


❌  Exiting due to PR_HYPERKIT_VMNET_FRAMEWORK: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

💡  Suggestion: Hyperkit networking is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --driver
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6028
    ▪ https://github.com/kubernetes/minikube/issues/5594
```

**Comment by sharifelgamal** [comment]
I'll reopen this and leave it open for discoverability.

**Comment by zosocanuck** [comment]
> Hmm... I also had internet sharing turned on and got this issue. I wonder if that's the root cause of the issue? None of my co-workers were running into it.

Ran into the same problem and turning off Internet Sharing on macOS Monterrey resolved the issue.

**Comment by TimekillerTK** [comment]
> Try deleting the /Users/ashkanaleali/.minikube directory and start minikube again and see if that helps

This fixed it for me.

I had the same issue `getting MAC address from UUID: vmnet: error from vmnet.framework: -1` after updating a bunch of packages on my system.

**Comment by cglacet** [comment]
@gabizou Yes I think that was the issue, I'll have to double check next time it happens :)

A colleague just got into the same issue, **turning internet sharing off solved the issue** for her.
