### ISSUE TITLE
minikube "developer cannot be verified" in macOS Catalina

### ISSUE THREAD

**Issue by derekbelrose** [kubernetes/minikube#5599]
**The exact command to reproduce the issue**:
`minikube config set vm-driver hyperkit`

**The full output of the command that failed**:<details>
"minikube-darwin-amd64" cannot be opened because the developer cannot be verified.

macOS cannot verify this app is free from malware."

</details>

**The output of the `minikube logs` command**:<details>
➜  sa_test git:(master) minikube config set vm-driver hyperkit
[1]    3562 killed     minikube config set vm-driver hyperkit

</details>

**The operating system version**:
macOS Catalina 10.15

**Comment by derekbelrose** [comment]
This is a fresh install of macOS Catalina and I have not disabled any security mechanisms in the operating system.  minikube was installed with `brew install minikube`

**Comment by derekbelrose** [comment]
I was able to work around this by:

1) Open terminal.app
2) type `open /usr/local/Caskroom/minikube/1.4.0/minikube-darwin-amd64`
3) Click ok in the resulting dialog.

**Comment by ashkan-leo** [comment]
You can also verify the executables yourself by going to system preference-> security->allow anyway.
Every time an unsigned binary is executed you need to do this. It’s extremely annoying.

**Comment by afbjorklund** [comment]
Duplicate, #5568

**Comment by derekbelrose** [comment]
@ashkan-leo I don't have the "Allow anyway" button under system preferences -> security

**Comment by ashkan-leo** [comment]
The button only appears when you get the error message that the app can’t be verified. It will disappear after sometime

**Comment by derekbelrose** [comment]
Right,  it didn't appear.

I'll close, apparently I'm the only one experiencing this issue.

**Comment by edreams** [comment]
sudo chown root:wheel /Users/chile/.minikube/bin/docker-machine-driver-hyperkit 
sudo chmod u+s /Users/chile/.minikube/bin/docker-machine-driver-hyperkit
