### ISSUE TITLE
Update default kubernetes version to v1.16.1

### ISSUE THREAD

**Issue by karuppiah7890** [kubernetes/minikube#5606]
As Kubernetes has released it recently https://github.com/kubernetes/kubernetes/releases/tag/v1.16.1 . I can work on this and raise a PR

**Comment by karuppiah7890** [comment]
I just noticed it's already there in code. Just not released 😅 Closing the issue!

**Comment by afbjorklund** [comment]
It’s just the default version, you can override it using a parameter/config.
