### ISSUE TITLE
Minikube dashboard assumes kubectl is set to the minikube context

### ISSUE THREAD

**Issue by yissachar** [kubernetes/minikube#563]
**Minikube version**: v0.9.0

**What happened**:

Running `minikube dashboard` when the `kubectl` context is not set to the minikube context does not open the dashboard in the browser.

**What you expected to happen**:

`minikube dashboard` should open the dashboard in the browser or output an error error explaining that the `kubectl context` needs to be changed.

**How to reproduce it** (as minimally and precisely as possible):

`kubectl config use-context some-other-context`
`minikube dashboard` Opens the browser to the wrong port. If the other context is offline, instead it will result in an eventual timeout.
`kubectl config use-context minikube`
`minikube dashboard` Now the dashboard will open properly in the browser

**Comment by dlorenc** [comment]
Ouch! Yeah we should fix this.

**Comment by nlamirault** [comment]
Using version 0.10.0 it works.

```
$ kubectl config view
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/nlamirault/.minikube/ca.crt
    server: https://192.168.99.103:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    namespace: development
    user: minikube
  name: dev
- context:
    cluster: minikube
    user: minikube
  name: minikube
- context:
    cluster: minikube
    namespace: production
    user: minikube
  name: prod
current-context: dev
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/nlamirault/.minikube/apiserver.crt
    client-key: /home/nlamirault/.minikube/apiserver.key
```

In context "dev", this command works : 

```
$ minikube dashboard
```

And switching *minikube* context it works too.

```
$ kubectl config use-context minikube
switched to context "minikube".
$ ./minikube dashboard
Opening kubernetes dashboard in default browser...
Created new window in existing browser session.
```

**Comment by yissachar** [comment]
@nlamirault Your example works because in both contexts you are using the minikube cluster. If your `dev` context was using a different cluster (that pointed to a different server), this would not work, even in 0.10.0
