### ISSUE TITLE
excludeIP error: ExcludeIP() requires IP or CIDR as a param

### ISSUE THREAD

**Issue by nkemakolam** [kubernetes/minikube#5631]
E1015 16:50:30.673328   15432 dashboard.go:88] Error excluding IP from proxy: ExcludeIP() requires IP or CIDR as a param
eter
*
X Error getting machine status: state: Failed to find the VM status

**Comment by priyawadhwa** [comment]
Hey @nkemakolam thanks for opening this issue. Could you please provide the following information so we can help resolve this:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
* The output of `grep NodeIP ~/.minikube/profiles/minikube/config.json`

Thanks so much!

**Comment by tstromberg** [comment]
I suspect that the config may reference an empty IP, and represent a failed minikube setup.

Do you mind sharing the output of `minikube status` as well?

**Comment by medyagh** [comment]
@nkemakolam  do you still have this issue ?

**Comment by NullYing** [comment]
> I suspect that the config may reference an empty IP, and represent a failed minikube setup.
> 
> Do you mind sharing the output of `minikube status` as well?

You are right

![image](https://user-images.githubusercontent.com/10618381/69508012-7f50a700-0f6f-11ea-9f82-6272d62daf06.png)

**Comment by NullYing** [comment]
It work now

![image](https://user-images.githubusercontent.com/10618381/69508428-a3f94e80-0f70-11ea-8c09-a0adb01e1d0d.png)

**Comment by userwebsky** [comment]
I had the same. Time is the solution. Three minutes later ...

```
>minikube dashboard
E1214 10:11:10.368019   11984 dashboard.go:90] Error excluding IP from proxy: ExcludeIP() requires IP or CIDR as a parameter
* Verifying dashboard health ...

>minikube status
host: Running
kubelet:
apiserver: Stopped
kubeconfig: Configured
```

Three minutes later ...

```
>minikube status
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

>minikube dashboard
* Verifying dashboard health ...
* Launching proxy ...
* Verifying proxy health ...
* Opening http://127.0.0.1:61577/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
```

**Comment by priyawadhwa** [comment]
Hey @NullYing I'm glad it's working for you now! I'm going to go ahead and close this issue, but if you run into any more errors feel free to reopen at any time by including `/reopen` in your comment or by opening a new issue. Thank you!
