### ISSUE TITLE
Dashboard does not show CPU or memory usage

### ISSUE THREAD

**Issue by cmdedj** [kubernetes/minikube#5642]
![image](https://user-images.githubusercontent.com/19429921/66984579-8ae9bc00-f0ed-11e9-995d-a83ee2a8bbb2.png)
why i cant see any cpu or memory usage graph on dashboard?

**Comment by cmdedj** [comment]
Dashboard v2.0.0-beta4+0.gf232c589

minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:49Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.0", GitCommit:"2bd9643cee5b3b3a5ecbd3af49d09018f0773c77", GitTreeState:"clean", BuildDate:"2019-09-18T14:27:17Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}

**Comment by cmdedj** [comment]
~/Desktop/kubernetes-in-action/Chapter05   master ●  kubectl get pods --all-namespaces
NAMESPACE              NAME                                         READY   STATUS    RESTARTS   AGE
default                kubia-cfqg2                                  1/1     Running   0          15h
default                kubia-d8n4w                                  1/1     Running   0          15h
default                kubia-dx9sd                                  1/1     Running   0          15h
kube-system            coredns-5644d7b6d9-vjvnp                     1/1     Running   5          9d
kube-system            coredns-5644d7b6d9-xgq5g                     1/1     Running   5          9d
kube-system            etcd-minikube                                1/1     Running   5          9d
kube-system            kube-addon-manager-minikube                  1/1     Running   5          9d
kube-system            kube-apiserver-minikube                      1/1     Running   5          9d
kube-system            kube-controller-manager-minikube             1/1     Running   5          9d
kube-system            kube-proxy-6k7p2                             1/1     Running   5          9d
kube-system            kube-scheduler-minikube                      1/1     Running   5          9d
kube-system            nginx-ingress-controller-57bf9855c8-zv6zp    1/1     Running   0          14h
kube-system            registry-kptrf                               1/1     Running   1          41h
kube-system            registry-proxy-tgstn                         1/1     Running   1          41h
kube-system            storage-provisioner                          1/1     Running   7          9d
kubernetes-dashboard   dashboard-metrics-scraper-76585494d8-pwjrt   1/1     Running   5          9d
kubernetes-dashboard   kubernetes-dashboard-57f4cb4545-5ktp6        1/1     Running   7          9d

**Comment by govargo** [comment]
I investigated this problem.
when I enabled the metrics-server addon, I could get CPU & Merory Usage.
I think indicating CPU & Merory Usage need the metrics-server pod as tstromberg mentioned.

<img width="1151" alt="スクリーンショット 2019-10-25 19 36 14" src="https://user-images.githubusercontent.com/44902466/67565577-b52c2100-f760-11e9-916c-34c0b2947be6.png">

Had we better enable the metrics-server addon automatically when we enable dashbord addons?
Or we should output warning about metrics-server when we enable dashbord addons?

Do you have any idea?

**Comment by cmdedj** [comment]
yes, when i enable the metrics-server addon, it worked.
and i think you should enable the metrics-server addon automatically,
Otherwise it may cause trouble for novices

thank you for your help

**Comment by nanikjava** [comment]
> @cmdedj Thank you for your comment.
> 
> @tstromberg May I work on this?(When dashboard is enabled, we also enable metrics-server automatically)

I think if you do know how to fix it then feel free to assign the ticket to yourself and submit PR

**Comment by govargo** [comment]
@nanikjava Than you for your advice. I will work on this.

**Comment by govargo** [comment]
Now metrics-server is not working in minikube v1.5.x.
See #5859.

**Comment by wingsofovnia** [comment]
Fixed by #5932
`brew upgrade minikube` upgrades minikube to 1.6.2 that includes the fix.

**Comment by medyagh** [comment]
seems like this issue was fixed. please re open if still have this issue.

**Comment by cglacet** [comment]
For those like me who don't know how to do, you just need to run these commands:

```bash
❯ minikube addons enable metrics-server
🌟  The 'metrics-server' addon is enabled
❯ minikube stop 
❯ minikube stop
✋  Stopping node "minikube"  ...
🛑  1 nodes stopped.
❯ minikube start
😄  minikube v1.14.0 on Darwin 10.15.7
...
❯ minikube dashboard
```

It worked for me at least.
