### ISSUE TITLE
Failed to cache ISO: open .netrc: permission denied

### ISSUE THREAD

**Issue by stanleynguyen** [kubernetes/minikube#5643]
I just freshly installed minikube to try it out in my Mac but have not managed to start 
```bash
stanleynguyen@macair:~ $ minikube version
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6
stanleynguyen@macair:~ $ minikube start
😄  minikube v1.4.0 on Darwin 10.14.6
💿  Downloading VM boot image ...

💣  Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.4.0.iso: invalid checksum: Error downloading checksum file: Error parsing netrc file at "/Users/stanleynguyen/.netrc": open /Users/stanleynguyen/.netrc: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

It seems that because minikube is asking for access to my `.netrc` file but I don't think it's supposed to have access to such file with sensitive info like my passwords

I still tried running it in superuser mode anyway, and faced with another problem
```bash
stanleynguyen@macair:~ $ sudo minikube start
Password:
😄  minikube v1.4.0 on Darwin 10.14.6
🛑  The "virtualbox" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --vm-driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
```

**Note**: I have virtualbox installed in my local as VM environment (I also used this for Docker)

**The operating system version**: MacOS Mojave 10.14.6

**Comment by tstromberg** [comment]
It seems like the network library minikube uses accesses  .netrc, and raises an error if it cannot: https://github.com/hashicorp/go-getter/blob/master/netrc.go

As a workaround, you can manually download the ISO:

`curl -L https://storage.googleapis.com/minikube/iso/minikube-v1.4.0.iso >  ~/.minikube/cache/iso/minikube-v1.4.0.iso`

Like most network commands, curl also references your .netrc, but it is nice enough to fail.

**Comment by stanleynguyen** [comment]
Thanks @tstromberg :smile: how do you think we should go about solving this? I will take this issue

**Comment by afbjorklund** [comment]
Why is it a bug that it reads user configuration from the home directory ? I don't see why it is.

**Comment by stanleynguyen** [comment]
@afbjorklund Since the ISO is public, I don't think it's necessary to read `.netrc` 🤔

**Comment by afbjorklund** [comment]
Oh, it's not _used_ at all (each entry has a machine token anyway). Just wondered why it was "bad" ?
It's a standard configuration file, so read-protecting it is a bit strange... Better to move/rename it, if so.

**Comment by stanleynguyen** [comment]
My `.netrc` has always been read protected from the start though. I don't know what the convention out there is but it makes sense to me as this file contains some of my passwords to cloud services (heroku, etc.)

**Comment by nanikjava** [comment]
Perhaps having another way to download the .iso when the first way of downloading it failed ?

**Comment by stanleynguyen** [comment]
Yea I'm thinking of using https://github.com/cavaliercoder/grab as fallback

**Comment by tstromberg** [comment]
I'd rather not import two different HTTP libraries.

I believe the workaround is to either rename your `.netrc` or use the following invocation to tell it to ignore your netrc file:

`env NETRC=/nonexistent minikube start`

I would also argue that storing plain-text passwords in a local file is bad news, and that `.netrc` is an outdated idea not suited for a world where private/public key cryptography is king. `.netrc` files served us well for the last 40 years, and will die a slow death, just like `.rhosts` did before it.

**Comment by tstromberg** [comment]
If you would like to see this get fixed, please open an issue with upstream:

https://github.com/hashicorp/go-getter/issues/new

Once fixed there, we can upgrade which go-getter version we point to.

**Comment by naveeniitbhu** [comment]
@stanleynguyen How did you resolve this issue? I am facing the issue with minikube 1.7.0.

**Comment by stanleynguyen** [comment]
> It seems like the network library minikube uses accesses .netrc, and raises an error if it cannot: https://github.com/hashicorp/go-getter/blob/master/netrc.go
> 
> As a workaround, you can manually download the ISO:
> 
> `curl -L https://storage.googleapis.com/minikube/iso/minikube-v1.4.0.iso > ~/.minikube/cache/iso/minikube-v1.4.0.iso`
> 
> Like most network commands, curl also references your .netrc, but it is nice enough to fail.

@naveeniitbhu u can follow the above comment to work around

**Comment by afbjorklund** [comment]
Did you open a bug report upstream yet ? Looks like a library issue...

**Comment by stanleynguyen** [comment]
@afbjorklund https://github.com/hashicorp/go-getter/issues/221 was opened for this

**Comment by afbjorklund** [comment]
I added an implementation (even wrote a test case).

Most likely it would be better to keep the secret file somewhere else and use $NETRC for accessing it, but then again we can just ignore the contents instead of throwing a "permission denied" error...

Upstream looks comatose, but maybe we can cherry-pick.

**Comment by irtaza909** [comment]
> It seems like the network library minikube uses accesses .netrc, and raises an error if it cannot: https://github.com/hashicorp/go-getter/blob/master/netrc.go
> 
> As a workaround, you can manually download the ISO:
> 
> `curl -L https://storage.googleapis.com/minikube/iso/minikube-v1.4.0.iso > ~/.minikube/cache/iso/minikube-v1.4.0.iso`
> 
> Like most network commands, curl also references your .netrc, but it is nice enough to fail.

i did as u mantioned  after downloading iso now i start minikube by command "minkube start" but it again stuck on downloading VM boot image.
