### ISSUE TITLE
Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open machines\minikube\config.json: The system cannot find the file specified.

### ISSUE THREAD

**Issue by wasimahmadpk** [kubernetes/minikube#5645]
**The exact command to reproduce the issue**:
Minikube start

**The full output of the command that failed**:<details>

minikube v1.4.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\Waseem\.minikube\machines\minikube\config.json: The system cannot find the file specified.

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Windows 10

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.

Thank you for sharing your experience!

**Comment by wasimahmadpk** [comment]
Hi,

Thank you for your response

I got it fixed by disabling hypervisor. Then I deleted the .kube and
.minikube folders. I enabled the hypervisor again. After that when I tried
minikube start, it worked for me.

Regards, Wasim

**Comment by nanikjava** [comment]
@wasimahmadpk If the issue had resolved for you can we close this ticket ?. Thanks

**Comment by wasimahmadpk** [comment]
Hi,

Yes I got it fixed yesterday

Thank you

Regards
Wasim
