### ISSUE TITLE
any chance of a new release please?

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/minikube#565]
we could really do with this change: https://github.com/kubernetes/minikube/commit/6fe48afbe757aebc8a0edfbef1b65bd1c7fe2213 so that we can detect minikube and setup PersistentVolumes correctly in gofabric8 (https://github.com/fabric8io/gofabric8/issues/152)

**Comment by dlorenc** [comment]
Just opened #566 for this. We usually release mid-week. If you'd like to do some testing with this  change, you can use our CI builds at:

```shell
$ gsutil ls gs://minikube-builds/546/
gs://minikube-builds/546/e2e-darwin-amd64
gs://minikube-builds/546/e2e-linux-amd64
gs://minikube-builds/546/localkube
gs://minikube-builds/546/minikube-darwin-amd64
gs://minikube-builds/546/minikube-linux-amd64
gs://minikube-builds/546/minikube-windows-amd64.exe
gs://minikube-builds/546/testdata/
```

546 is the PR that change was merged in. You can get these via a URL at:
`https://storage.googleapis.com/minikube-builds/546/<binary>`
