### ISSUE TITLE
Failed to setup kubeconfig: could not read config: Error decoding config from data: apiVersion: v1

### ISSUE THREAD

**Issue by jshahid21** [kubernetes/minikube#5650]
**The exact command to reproduce the issue**: 
minikube start

**The full output of the command that failed**:<details>
😄  minikube v1.4.0 on Darwin 10.13.6
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...

💣  Failed to setup kubeconfig: could not read config: Error decoding config from data: apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVT0xSMVJiOTBkWFZIbmJhSkM5c05mTk5zbFlJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUJoTUNWVk14RGpBTUJnTlZCQWdUQlZSbGVHRnpNUTh3RFFZRFZRUUhFd1pCZFhOMAphVzR4RHpBTkJnTlZCQW9UQms5eVlXTnNaVEVNTUFvR0ExVUVDeE1EVDBSWU1ROHdEUVlEVlFRREV3WkxPRk1nClEwRXdIaGNOTVRrd01USXpNakExTVRBd1doY05NalF3TVRJeU1qQTFNVEF3V2pCZU1Rc3dDUVlEVlFRR0V3SlYKVXpFT01Bd0dBMVVFQ0JNRlZHVjRZWE14RHpBTkJnTlZCQWNUQmtGMWMzUnBiakVQTUEwR0ExVUVDaE1HVDNKaApZMnhsTVF3d0NnWURWUVFMRXdOUFJGZ3hEekFOQmdOVkJBTVRCa3M0VXlCRFFUQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMdkRDNk16M0pXcnViR043QzROWGJwNGJpL0UzN0crM1NBZk41Tm4KTGl3d05wQnZIN3dwTTZPNEw2M3UvTGdHbG5DOXJPTVBqb3B3dUdBZmRzalpwNDNSdHVXUmx0MGYwZkNaanluYgpxZ1VOSVA5aHBvTkcyUlFpaWFhSlVlQzR5NUhabXAvb05lRlNYNE9GUVI1TDVyNjFhNVhoSUI0SDJPeE9wSFNDCmQ5RHVTTFdwK1lrdmdIR21UT3FlYk5jaHU2NUZtTWloT0JXdDEwb3lPU3YydTh3cVFhbFFLeXpMaWM4UmRlcFQKOWFSWmRTcVA4WHlIRmlvczJSa0xHbnVPTDc5TUpVRG96T3hxNVBHb1lUdFBVOHRsVkdYUFNOS0w1RkxEdlZ6UwpVN2dSbGtSdFVveXB5Uk9palNqVTRseEJvdFJsaExjV1h2d0Y5bmhHclRDODdUMENBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGT01LeGJmQ0JrS2EKMUE1NHNYcXdIUnJEWkxubU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0tvZERJejl3cUpFWVdCN004T1dmcQp0Ynk3Z1RzNVZWTDRoZlN6TWlZSnlwMTNJMUVRTkFZdnBseDFuaEtGVUlvUGNvUHNCUE1kYmlrTm1nbE9XRDZpClhKWkprdVBFN0tyVS9LZ3RmaDJVVFQ4dEkrNFBkcEllcVBWNGM3eVpZRkZyNHUzNjJSNU53RTFNVkYvZ0VmRy8KT2tnSlA3RVpycnJPdHVxMkIvQzNWejFMaVNpbUt5QlRaR0NoQmRRWDBoTGhDVnV2eWZKeDNaRTc4QzhQZjhxUQpiMkY1UW5iQ2c2aTR2RUwzN3E5THk3Mmh1WnJONDVnVWw4UjhndHhWSHZqQXhZR3hvcjBySzFQcUNJWFNydk1QCno3cStKcmhjSlZPUzlvU3RIQWtyRzhUWmozV3JjM25Oa2YzdWI1UVEwb040UmVPWjVocFg4WjZSWlBZYXo3M3QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://c4tiyztmrrd.us-ashburn-1.clusters.oci.oraclecloud.com:6443
  name: cluster-c4tiyztmrrd
contexts:
- context:
    cluster: cluster-c4tiyztmrrd
    user: user-c4tiyztmrrd
  name: context-c4tiyztmrrd
current-context: context-c4tiyztmrrd
kind: ""
users:
- name: user-c4tiyztmrrd
  user:
    token: eyJoZWFkZXIiOnsiQXV0aG9yaXphdGlvbiI6WyJTaWduYXR1cmUgYWxnb3JpdGhtPVwicnNhLXNoYTI1NlwiLGhlYWRlcnM9XCJkYXRlIChyZXF1ZXN0LXRhcmdldCkgaG9zdCBjb250ZW50LWxlbmd0aCBjb250ZW50LXR5cGUgeC1jb250ZW50LXNoYTI1NlwiLGtleUlkPVwib2NpZDEudGVuYW5jeS5vYzEuLmFhYWFhYWFhang2amhwaWpvZHZqc2ZsNXVicmlsZHUzbzVjd3RoZTNrZXV5anFrazZoYzM1c2hmYm9ncS9vY2lkMS51c2VyLm9jMS4uYWFhYWFhYWFhNXY3NzRmcm8yNmpscG4zanl3bXRwYXB6ZnRlZ3RyNGI0MzVyNXBrYjdxbjRzb3lsdHdhLzVjOjk3OmE5OjNkOjgzOmMxOjM4OmEwOjllOjIxOmFhOjkxOjc2OmRhOjEwOjdmXCIsc2lnbmF0dXJlPVwiQnlYS0xET3RXUlZyL1pFcCtvS0ZBb2hWRFpaV0JOUmN6R1RkN2NUczArbkk0WEpXd0p4bTFyVTBoN1Nhd0ozeDVmaEJyZ1FLbnpmbEtaREdVSDVOcHhrZWd1MXY4dHZha0dGOHN5elpYM0FEbmhhTHUxNm1teEVuT3BYY2tQTEFhZEtFbVFBbzE1SGVXUnJkZm9lRXpiSy9LNms3S1U3V0VGc1laQUhSOTdlN2pyNExWNExaVXltdFRnMFB1RE9WUmJqMmRIamhiRGoxMmdjd3duK2FpaWJMRzgwYnV6QXZ2dEQzV3F0TW9KWVcyblZyaFU4MUFoOFhscy9rbzVaSDhwWW1uNU0wdkt3OXVjSGxUUGJGWnIybnA4RGNiY1k5OUdVL3BvUWhXNjVJM2IxQVdCQVluaWVWWUU4NEllRDFaM21ra2E1cjRObDlVL3BTRDBXQmJ3PT1cIix2ZXJzaW9uPVwiMVwiIl0sIkNvbnRlbnQtTGVuZ3RoIjpbIjIiXSwiQ29udGVudC1UeXBlIjpbImFwcGxpY2F0aW9uL2pzb24iXSwiRGF0ZSI6WyJXZWQsIDIzIEphbiAyMDE5IDIxOjE2OjUzIEdNVCJdLCJYLUNvbnRlbnQtU2hhMjU2IjpbIlJCTnZvMVd6WjRvUlJxMFc5K2hrbnBUN1Q4SWY1MzZERU1CZzloeXEvNG89Il19LCJib2R5Ijp7InRva2VuVmVyc2lvbiI6IjEuMC4wIiwiZXhwaXJhdGlvbiI6MjU5MjAwMDAwMDAwMDAwMH0sImhvc3QiOiJjb250YWluZXJlbmdpbmUudXMtYXNoYnVybi0xLm9yYWNsZWNsb3VkLmNvbSIsInJlcXVlc3RfdXJpIjoiLzIwMTgwMjIyL2NsdXN0ZXJzL29jaWQxLmNsdXN0ZXIub2MxLmlhZC5hYWFhYWFhYWFlM3dpeWp2Z3kzdG1tbGNtZnNkY3l6cmdtMndtbnp2Z2F6Z216bGZnYzR0aXl6dG1ycmQva3ViZWNvbmZpZy9jb250ZW50In0=
: Object 'Kind' is missing in 'apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURqRENDQW5TZ0F3SUJBZ0lVT0xSMVJiOTBkWFZIbmJhSkM5c05mTk5zbFlJd0RRWUpLb1pJaHZjTkFRRUwKQlFBd1hqRUxNQWtHQTFVRUJoTUNWVk14RGpBTUJnTlZCQWdUQlZSbGVHRnpNUTh3RFFZRFZRUUhFd1pCZFhOMAphVzR4RHpBTkJnTlZCQW9UQms5eVlXTnNaVEVNTUFvR0ExVUVDeE1EVDBSWU1ROHdEUVlEVlFRREV3WkxPRk1nClEwRXdIaGNOTVRrd01USXpNakExTVRBd1doY05NalF3TVRJeU1qQTFNVEF3V2pCZU1Rc3dDUVlEVlFRR0V3SlYKVXpFT01Bd0dBMVVFQ0JNRlZHVjRZWE14RHpBTkJnTlZCQWNUQmtGMWMzUnBiakVQTUEwR0ExVUVDaE1HVDNKaApZMnhsTVF3d0NnWURWUVFMRXdOUFJGZ3hEekFOQmdOVkJBTVRCa3M0VXlCRFFUQ0NBU0l3RFFZSktvWklodmNOCkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMdkRDNk16M0pXcnViR043QzROWGJwNGJpL0UzN0crM1NBZk41Tm4KTGl3d05wQnZIN3dwTTZPNEw2M3UvTGdHbG5DOXJPTVBqb3B3dUdBZmRzalpwNDNSdHVXUmx0MGYwZkNaanluYgpxZ1VOSVA5aHBvTkcyUlFpaWFhSlVlQzR5NUhabXAvb05lRlNYNE9GUVI1TDVyNjFhNVhoSUI0SDJPeE9wSFNDCmQ5RHVTTFdwK1lrdmdIR21UT3FlYk5jaHU2NUZtTWloT0JXdDEwb3lPU3YydTh3cVFhbFFLeXpMaWM4UmRlcFQKOWFSWmRTcVA4WHlIRmlvczJSa0xHbnVPTDc5TUpVRG96T3hxNVBHb1lUdFBVOHRsVkdYUFNOS0w1RkxEdlZ6UwpVN2dSbGtSdFVveXB5Uk9palNqVTRseEJvdFJsaExjV1h2d0Y5bmhHclRDODdUMENBd0VBQWFOQ01FQXdEZ1lEClZSMFBBUUgvQkFRREFnRUdNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGT01LeGJmQ0JrS2EKMUE1NHNYcXdIUnJEWkxubU1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ0tvZERJejl3cUpFWVdCN004T1dmcQp0Ynk3Z1RzNVZWTDRoZlN6TWlZSnlwMTNJMUVRTkFZdnBseDFuaEtGVUlvUGNvUHNCUE1kYmlrTm1nbE9XRDZpClhKWkprdVBFN0tyVS9LZ3RmaDJVVFQ4dEkrNFBkcEllcVBWNGM3eVpZRkZyNHUzNjJSNU53RTFNVkYvZ0VmRy8KT2tnSlA3RVpycnJPdHVxMkIvQzNWejFMaVNpbUt5QlRaR0NoQmRRWDBoTGhDVnV2eWZKeDNaRTc4QzhQZjhxUQpiMkY1UW5iQ2c2aTR2RUwzN3E5THk3Mmh1WnJONDVnVWw4UjhndHhWSHZqQXhZR3hvcjBySzFQcUNJWFNydk1QCno3cStKcmhjSlZPUzlvU3RIQWtyRzhUWmozV3JjM25Oa2YzdWI1UVEwb040UmVPWjVocFg4WjZSWlBZYXo3M3QKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://c4tiyztmrrd.us-ashburn-1.clusters.oci.oraclecloud.com:6443
  name: cluster-c4tiyztmrrd
contexts:
- context:
    cluster: cluster-c4tiyztmrrd
    user: user-c4tiyztmrrd
  name: context-c4tiyztmrrd
current-context: context-c4tiyztmrrd
kind: ""
users:
- name: user-c4tiyztmrrd
  user:
    token: eyJoZWFkZXIiOnsiQXV0aG9yaXphdGlvbiI6WyJTaWduYXR1cmUgYWxnb3JpdGhtPVwicnNhLXNoYTI1NlwiLGhlYWRlcnM9XCJkYXRlIChyZXF1ZXN0LXRhcmdldCkgaG9zdCBjb250ZW50LWxlbmd0aCBjb250ZW50LXR5cGUgeC1jb250ZW50LXNoYTI1NlwiLGtleUlkPVwib2NpZDEudGVuYW5jeS5vYzEuLmFhYWFhYWFhang2amhwaWpvZHZqc2ZsNXVicmlsZHUzbzVjd3RoZTNrZXV5anFrazZoYzM1c2hmYm9ncS9vY2lkMS51c2VyLm9jMS4uYWFhYWFhYWFhNXY3NzRmcm8yNmpscG4zanl3bXRwYXB6ZnRlZ3RyNGI0MzVyNXBrYjdxbjRzb3lsdHdhLzVjOjk3OmE5OjNkOjgzOmMxOjM4OmEwOjllOjIxOmFhOjkxOjc2OmRhOjEwOjdmXCIsc2lnbmF0dXJlPVwiQnlYS0xET3RXUlZyL1pFcCtvS0ZBb2hWRFpaV0JOUmN6R1RkN2NUczArbkk0WEpXd0p4bTFyVTBoN1Nhd0ozeDVmaEJyZ1FLbnpmbEtaREdVSDVOcHhrZWd1MXY4dHZha0dGOHN5elpYM0FEbmhhTHUxNm1teEVuT3BYY2tQTEFhZEtFbVFBbzE1SGVXUnJkZm9lRXpiSy9LNms3S1U3V0VGc1laQUhSOTdlN2pyNExWNExaVXltdFRnMFB1RE9WUmJqMmRIamhiRGoxMmdjd3duK2FpaWJMRzgwYnV6QXZ2dEQzV3F0TW9KWVcyblZyaFU4MUFoOFhscy9rbzVaSDhwWW1uNU0wdkt3OXVjSGxUUGJGWnIybnA4RGNiY1k5OUdVL3BvUWhXNjVJM2IxQVdCQVluaWVWWUU4NEllRDFaM21ra2E1cjRObDlVL3BTRDBXQmJ3PT1cIix2ZXJzaW9uPVwiMVwiIl0sIkNvbnRlbnQtTGVuZ3RoIjpbIjIiXSwiQ29udGVudC1UeXBlIjpbImFwcGxpY2F0aW9uL2pzb24iXSwiRGF0ZSI6WyJXZWQsIDIzIEphbiAyMDE5IDIxOjE2OjUzIEdNVCJdLCJYLUNvbnRlbnQtU2hhMjU2IjpbIlJCTnZvMVd6WjRvUlJxMFc5K2hrbnBUN1Q4SWY1MzZERU1CZzloeXEvNG89Il19LCJib2R5Ijp7InRva2VuVmVyc2lvbiI6IjEuMC4wIiwiZXhwaXJhdGlvbiI6MjU5MjAwMDAwMDAwMDAwMH0sImhvc3QiOiJjb250YWluZXJlbmdpbmUudXMtYXNoYnVybi0xLm9yYWNsZWNsb3VkLmNvbSIsInJlcXVlc3RfdXJpIjoiLzIwMTgwMjIyL2NsdXN0ZXJzL29jaWQxLmNsdXN0ZXIub2MxLmlhZC5hYWFhYWFhYWFlM3dpeWp2Z3kzdG1tbGNtZnNkY3l6cmdtMndtbnp2Z2F6Z216bGZnYzR0aXl6dG1ycmQva3ViZWNvbmZpZy9jb250ZW50In0=
'

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**The output of the `minikube logs` command**:<details>
==> Docker <==
-- Logs begin at Thu 2019-10-17 19:43:14 UTC, end at Thu 2019-10-17 19:45:36 UTC. --
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563043044Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563145515Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563227186Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563263490Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563295880Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563327469Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563364642Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563396163Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563426691Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563553747Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563637793Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563920171Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.563967114Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564061188Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564097724Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564130186Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564160497Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564190036Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564219207Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564252985Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564283087Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564360261Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564429614Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564463928Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564499319Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564532400Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564646676Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564699007Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.564730398Z" level=info msg="containerd successfully booted in 0.007037s"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.570006620Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000047ad0, READY" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.574155664Z" level=info msg="systemd-resolved is running, so using resolvconf: /run/systemd/resolve/resolv.conf"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575234608Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575276896Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575385474Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575455558Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575533122Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000153000, CONNECTING" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575393124Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575591777Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575748437Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000153000, READY" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575804021Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575836619Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575875438Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001532e0, CONNECTING" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.575992741Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001532e0, READY" module=grpc
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.589307643Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.589531951Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.589553213Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.589560779Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.589567407Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.589574065Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.589582677Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.589882392Z" level=info msg="Loading containers: start."
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.652288372Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.748714289Z" level=info msg="Loading containers: done."
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.757449795Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.757920764Z" level=warning msg="failed to retrieve docker-init version: exec: \"docker-init\": executable file not found in $PATH"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.774802662Z" level=info msg="Docker daemon" commit=039a7df9ba graphdriver(s)=overlay2 version=18.09.9
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.775002728Z" level=info msg="Daemon has completed initialization"
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.784994020Z" level=info msg="API listen on /var/run/docker.sock"
Oct 17 19:43:27 minikube systemd[1]: Started Docker Application Container Engine.
Oct 17 19:43:27 minikube dockerd[2391]: time="2019-10-17T19:43:27.785144247Z" level=info msg="API listen on [::]:2376"

==> container status <==
time="2019-10-17T19:45:38Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> dmesg <==
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_default_io_mem_pfn (err 0)
[  +0.000006] vboxvideo: Unknown symbol ttm_bo_device_release (err 0)
[  +0.000011] vboxvideo: Unknown symbol ttm_bo_kunmap (err 0)
[  +0.000003] vboxvideo: Unknown symbol ttm_bo_del_sub_from_lru (err 0)
[  +0.000006] vboxvideo: Unknown symbol ttm_bo_device_init (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_init_mm (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_dma_acc_size (err 0)
[  +0.000003] vboxvideo: Unknown symbol ttm_tt_init (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_kmap (err 0)
[  +0.000006] vboxvideo: Unknown symbol ttm_bo_add_to_lru (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_unref (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_mem_global_release (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_mem_global_init (err 0)
[  +0.000009] vboxvideo: Unknown symbol ttm_bo_init (err 0)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_validate (err 0)
[  +0.000007] vboxvideo: Unknown symbol ttm_tt_fini (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_eviction_valuable (err 0)
[  +0.000001] vboxvideo: Unknown symbol ttm_pool_populate (err 0)
[  +0.219139] hpet1: lost 685 rtc interrupts
[  +0.031235] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +0.015753] hpet1: lost 1 rtc interrupts
[  +0.000600] VBoxService 5.1.38 r122592 (verbosity: 0) linux.amd64 (May  9 2018 12:22:30) release log
              00:00:00.000808 main     Log opened 2019-10-17T19:43:19.336376000Z
[  +0.000055] 00:00:00.000906 main     OS Product: Linux
[  +0.000040] 00:00:00.000949 main     OS Release: 4.15.0
[  +0.000038] 00:00:00.000988 main     OS Version: #1 SMP Wed Sep 18 07:44:58 PDT 2019
[  +0.000055] 00:00:00.001027 main     Executable: /usr/sbin/VBoxService
              00:00:00.001027 main     Process ID: 2044
              00:00:00.001028 main     Package type: LINUX_64BITS_GENERIC
[  +0.000040] 00:00:00.001083 main     5.1.38 r122592 started. Verbose level = 0
[  +5.032979] hpet1: lost 278 rtc interrupts
[  +5.001533] hpet1: lost 318 rtc interrupts
[  +2.433240] systemd-fstab-generator[2298]: Ignoring "noauto" for root device
[  +7.570865] hpet_rtc_timer_reinit: 69 callbacks suppressed
[  +0.000001] hpet1: lost 318 rtc interrupts
[  +5.000347] hpet1: lost 318 rtc interrupts
[  +5.002864] hpet1: lost 318 rtc interrupts
[  +5.000742] hpet1: lost 318 rtc interrupts
[  +5.002815] hpet1: lost 319 rtc interrupts
[  +5.002825] hpet1: lost 318 rtc interrupts
[Oct17 19:44] hpet1: lost 318 rtc interrupts
[  +5.003959] hpet1: lost 318 rtc interrupts
[  +5.004122] hpet1: lost 319 rtc interrupts
[  +5.003711] hpet1: lost 318 rtc interrupts
[  +5.001964] hpet1: lost 318 rtc interrupts
[  +5.001472] hpet1: lost 318 rtc interrupts
[  +5.002484] hpet1: lost 318 rtc interrupts
[  +5.001346] hpet1: lost 318 rtc interrupts
[  +5.001213] hpet1: lost 318 rtc interrupts
[  +5.001456] hpet1: lost 318 rtc interrupts
[  +5.001469] hpet1: lost 319 rtc interrupts
[  +5.001385] hpet1: lost 318 rtc interrupts
[Oct17 19:45] hpet1: lost 318 rtc interrupts
[  +5.002524] hpet1: lost 318 rtc interrupts
[  +5.001823] hpet1: lost 318 rtc interrupts
[  +2.946342] NFSD: Unable to end grace period: -110
[  +2.054498] hpet1: lost 318 rtc interrupts
[  +5.001239] hpet1: lost 318 rtc interrupts
[  +5.001249] hpet1: lost 318 rtc interrupts
[  +5.000996] hpet1: lost 318 rtc interrupts

==> kernel <==
 19:45:38 up 2 min,  0 users,  load average: 0.43, 0.36, 0.15
Linux minikube 4.15.0 #1 SMP Wed Sep 18 07:44:58 PDT 2019 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2018.05.3"

==> kubelet <==
-- Logs begin at Thu 2019-10-17 19:43:14 UTC, end at Thu 2019-10-17 19:45:38 UTC. --
-- No entries --

**The operating system version**:
macOS High Sierra Version 10.13.6 (17G8037)

**Comment by jshahid21** [comment]
Issue was resolved by changing the ~/.kube/config file "Kind:" field from blank/no entry to Config.

**Comment by stantonxu** [comment]
In my case, the field was already "Kind: Config" when I saw the problem. So this doesn't work.
