### ISSUE TITLE
ssh: up button does not pull up bash history on Windows

### ISSUE THREAD

**Issue by zd-dalibor** [kubernetes/minikube#5666]
When I stop my minkube with `minikube stop` command and then I try to relaunch it with `minikube start` I got totally fresh vm.

Is there commands for standard shutdown/restart/power on/power off without touching vm file system. Can I use vm tools interface for this functionality (hyper-v manager for example)

![image](https://user-images.githubusercontent.com/226822/67149982-317eba00-f2b2-11e9-8f7c-e019df784503.png)

**Comment by tstromberg** [comment]
Interesting - this shouldn't happen, and diverges from the behavior seen with other hypervisors.

Help wanted.

**Comment by tstromberg** [comment]
Also, if it matters, suspend/resume is part of our 2020 roadmap: #5452

**Comment by zd-dalibor** [comment]
After every minikube stop & start, when I try to ssh to minikube vm, I got message that RSA key fingerprint is changed and old ssh private key did not working (new ssh key is  generated). I am using Hyper-V.

**Comment by afbjorklund** [comment]
This is "normal", libmachine doesn't save host keys. The workaround is `ignoring` ssh host keys:

```go
		"-o", "StrictHostKeyChecking=no",
		"-o", "UserKnownHostsFile=/dev/null",
```

However, the user keys _should_ be the same. They are stored client-side, and uploaded to the VM.

**Comment by zd-dalibor** [comment]
@afbjorklund 
Ok, This is my mistake, vm is not recreated, only host key is not preserved after shutdown.

But there is another problem. `minikube ssh`  command starts embedded ssh agent where arrow keys does not work. I cannot, for example, go through bash history. I think also other special keys do not work like `insert`, `home`, `end` ... With command `minikube ssh --native-ssh=false` I also have the same problems.

Because of this I try to use native ssh agent `C:\Windows\System32\OpenSSH\ssh.exe` with `minikupe ip` and `minikube ssh-key`, but also facing with problems that private key is not secured enough and unknown host key.

With putty there are also the same problem with host key and privet key must be converted to ppk format.

**Comment by medyagh** [comment]
@zd-dalibor glad to see you found the root cause, I will rename this issue to to the newest comment.

it would be nice to have minikbue ssh have history

**Comment by sharifelgamal** [comment]
This is still an open issue. Help wanted!

**Comment by zd-dalibor** [comment]
Bash history exists but, I think that ssh client implementation in go language does not recognize the arrow keys. When I use putty client instead of "minikube ssh" command up and down keys traverse through bash history

**Comment by tstromberg** [comment]
The up arrow appears to work for me on macOS, both with `--native-ssh=false` and `--native--sh=true`.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by prasy-loyola** [comment]
Still happens with the latest version of minikube on windows 10
```
minikube version: v1.12.1
commit: 5664228288552de9f3a446ea4f51c6f29bbdd0e0-dirty
```
When I get a shell using `minikube ssh`, the `arrow keys`,  `home`, `end` keys don't work.

**Comment by Guerric-P** [comment]
Issue confirmed here too

**Comment by r4j4h** [comment]
I find that with `--native-ssh=false` you can type `export TERM=linux` once inside ssh and then things work as expected

**Comment by CC007** [comment]
I pivoted away from minikube due to this and a couple of other issues, like minikube not being accessible after a windows restart, without a minikube stop + start. This also seems to screw up the deployments for me. Switched to kubespray and never had any of these issues.

**Comment by biergit** [comment]
Why is this issue closed?
