### ISSUE TITLE
Add support for running on arm64 (aarch64)

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#5667]
For instance on the Raspberry Pi, using the `none` driver (localhost).

Note that you will need more than 1G of memory, or use a swap file.

No virtualization on this platform, but works OK with `generic` driver.

That is, work on the laptop and use ssh to connect to the "bare metal".

**Comment by afbjorklund** [comment]
```console
# minikube start --vm-driver=none
😄  minikube v1.4.1 on Fedora 30 (/arm64)
🤹  Running on localhost (CPUs=4, Memory=953MB, Disk=29198MB) ...
ℹ️   OS release is Fedora 30 (Server Edition)
🐳  Preparing Kubernetes v1.16.1 on Docker 18.09.9 ...
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://minikube.sigs.k8s.io/docs/reference/drivers/none/

⚠️  kubectl and minikube configuration will be stored in /root
⚠️  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
⌛  Waiting for: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"
```

* https://www.raspberrypi.org/products/raspberry-pi-3-model-b/

* https://fedoraproject.org/wiki/Architectures/ARM/Raspberry_Pi

* https://download.docker.com/linux/static/stable/aarch64/

* https://docs.docker.com/config/daemon/systemd/

**Comment by nanikjava** [comment]
This is going to be interesting. 

I've got ODROID XU4 (https://www.hardkernel.com/shop/odroid-xu4-special-price/)  and it has 2GB RAM and can run Kernel 4.14 LTS

Interested to help out to make it run on the ODROID board. 

Thanks

**Comment by afbjorklund** [comment]
The dedicated boards are probably a better match, all the Raspberry Pi (except for the latest model 4) have either 512M or 1G of memory. And this is **not** enough for running `kubeadm` (only for `localkube`)

While you _can_ add swap, that is not a sustainable (nor efficient) way to run. Better to get a dedicated distribution, such as k3s ? There is also some ongoing issue with the CPU usage of k8s in general:

``` console
[root@localhost ~]# 
Message from syslogd@localhost at Oct 19 23:10:15 ...
 kernel:thermal thermal_zone0: critical temperature reached (80 C), shutting down
Connection to fedora closed by remote host.
```

So that was the main reason for avoiding the 32-bit arm and going straight for the 64-bit arm only. There are other projects targeting the `armv6` and `armv7`, this was only about the `armv8` CPUs.

For now this only involves _compiling_ `minikube` binary for `arm64` as well as for `amd64`: #5665
I don't know if there will be a dedicated Buildroot for it, such as the current `minikube.iso` for VM ?

---

Too much trouble with supporting all the different arm boards:
* https://fedoraproject.org/wiki/Architectures/ARM/exynos

So **if** there is one, it is more likely to target the Raspberry Pi 4:
https://www.raspberrypi.org/products/raspberry-pi-4-model-b/

>    * Broadcom BCM2711 SoC, with quad-core ARM Cortex-A72 1.5 GHz processor
>    * 1GB, 2GB, or 4GB of LPDDR4 SDRAM
>    * Full-throughput Gigabit Ethernet
>    * Dual-band 802.11ac wireless networking

See https://elinux.org/RPi_HardwareHistory#Raspberry_Pi_4_Model_B

The computer itself is $35, but you _need_ a power supply $8 and memory card $8.
(running with a low power supply or slow memory card is not a fun experience...)

And of course, the _real_ use for these is when you run multi-node.

I can highly recommend reading this site (and thesis) about the particular subject,
why you would ever want to do such a cumbersome thing: **https://kubecloud.io/**

**Comment by afbjorklund** [comment]
It is possible to use CRI-O instead of Docker, but unfortunately the fedora `cri-o` package is buggy...
The 1-13-1.14 have issues and 1.15 is hidden (https://bugzilla.redhat.com/show_bug.cgi?id=1754170)

```console
# dnf module enable cri-o:1.14
# dnf install cri-o
# systemctl start crio
    Invalid character(s) found in prerelease "module_f30"
```

Newer packages:

* https://koji.fedoraproject.org/koji/packageinfo?packageID=24240

  * https://koji.fedoraproject.org/koji/buildinfo?buildID=1401278

Ugly workaround:
``` console
# dnf install https://kojipkgs.fedoraproject.org//packages/cri-o/1.15.2/1.module_f30+6830+9be88745/aarch64/cri-o-1.15.2-1.module_f30+6830+9be88745.aarch64.rpm
# perl -p0e "s/\.module_f30/.alpha.0.30/g;s/\+6830/.6830/g;s/\+9be88745/.90088745/g" -i /usr/bin/crio
```

But except for the semver issue, it seems to work correctly:

```
# minikube start --vm-driver=none --container-runtime=crio
😄  minikube v1.4.1 on Fedora 30 (/arm64)
🤹  Running on localhost (CPUs=4, Memory=953MB, Disk=29198MB) ...
ℹ️   OS release is Fedora 30 (Server Edition)
🎁  Preparing Kubernetes v1.16.1 on CRI-O 1.15.2-1.alpha.0.30.6830.90088745 ...
```

Hopefully the packaging can be fixed, for a better experience ?

**Comment by afbjorklund** [comment]
If you prefer Debian over Fedora, this OS distribution should work:
https://blog.hypriot.com/post/building-a-64bit-docker-os-for-rpi3/

Haven't tried it myself. But the regular (32-bit) HypriotOS works fine...
See also https://wiki.debian.org/Arm64Port with the upstream details.

**Comment by cheeseandcereal** [comment]
Is there any way we could get the coredns and storage-provisioner containers to have a built arm64 version? Currently tried to get minikube v1.5.2 working (for the most part), but with a big blocker on those 2 containers:

```$ sudo minikube start --vm-driver=none
😄  minikube v1.5.2 on Ubuntu 18.04 (/arm64)
🤹  Running on localhost (CPUs=4, Memory=7706MB, Disk=19680MB) ...
ℹ️   OS release is Ubuntu 18.04.3 LTS
E1211 01:41:40.233292   29899 cache_images.go:80] CacheImage k8s.gcr.io/coredns-arm64:1.6.2 -> /home/ubuntu/.minikube/cache/images/k8s.gcr.io/coredns-arm64_1.6.2 failed: MANIFEST_UNKNOWN: "Failed to fetch \"1.6.2\" from request \"/v2/coredns-arm64/manifests/1.6.2\"."
E1211 01:41:40.258059   29899 cache_images.go:80] CacheImage gcr.io/k8s-minikube/storage-provisioner-arm64:v1.8.1 -> /home/ubuntu/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner-arm64_v1.8.1 failed: MANIFEST_UNKNOWN: "Failed to fetch \"v1.8.1\" from request \"/v2/k8s-minikube/storage-provisioner-arm64/manifests/v1.8.1\"."
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.7' ...
E1211 01:41:40.351631   29899 start.go:799] Error caching images:  Caching images for kubeadm: caching images: caching image /home/ubuntu/.minikube/cache/images/k8s.gcr.io/coredns-arm64_1.6.2: MANIFEST_UNKNOWN: "Failed to fetch \"1.6.2\" from request \"/v2/coredns-arm64/manifests/1.6.2\"."
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
❌  Unable to load cached images: loading cached images: loading image /home/ubuntu/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner-arm64_v1.8.1: stat /home/ubuntu/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner-arm64_v1.8.1: no such file or directory```

**Comment by sharifelgamal** [comment]
@cheeseandcereal This might be fixed in minikube 1.6.1, could you upgrade your minikube version and retry?

**Comment by cheeseandcereal** [comment]
Nope, still getting the errors. Checking the actual docker repository reveals that the images it's trying to pull (`k8s.gcr.io/coredns-arm64:1.6.5` and `gcr.io/k8s-minikube/storage-provisioner-arm64:v1.8.1`) are legitimately not in the repo; they need to be built and pushed.

`k8s.gcr.io/coredns:1.6.5` and `gcr.io/k8s-minikube/storage-provisioner:v1.8.1` exist in the repository, but they are not multi-architecture manifests (they are only `amd64` containers)

Minikube output:
```
😄  minikube v1.6.1 on Ubuntu 18.04 (/arm64)
✨  Selecting 'none' driver from user configuration (alternates: [])
🤹  Running on localhost (CPUs=4, Memory=7706MB, Disk=49448MB) ...
ℹ️   OS release is Ubuntu 18.04.3 LTS
🐳  Preparing Kubernetes v1.17.0 on Docker '18.09.7' ...
E1217 01:30:45.780807    1339 cache_images.go:85] CacheImage k8s.gcr.io/coredns-arm64:1.6.5 -> /home/ubuntu/.minikube/cache/images/k8s.gcr.io/coredns-arm64_1.6.5 failed: MANIFEST_UNKNOWN: "Failed to fetch \"1.6.5\" from request \"/v2/coredns-arm64/manifests/1.6.5\"."
E1217 01:30:45.807433    1339 cache_images.go:85] CacheImage gcr.io/k8s-minikube/storage-provisioner-arm64:v1.8.1 -> /home/ubuntu/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner-arm64_v1.8.1 failed: MANIFEST_UNKNOWN: "Failed to fetch \"v1.8.1\" from request \"/v2/k8s-minikube/storage-provisioner-arm64/manifests/v1.8.1\"."
E1217 01:30:45.807533    1339 start.go:841] Error caching images:  Caching images for kubeadm: caching images: caching image /home/ubuntu/.minikube/cache/images/k8s.gcr.io/coredns-arm64_1.6.5: MANIFEST_UNKNOWN: "Failed to fetch \"1.6.5\" from request \"/v2/coredns-arm64/manifests/1.6.5\"."
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
❌  Unable to load cached images: loading cached images: loading image gcr.io/k8s-minikube/storage-provisioner-arm64:v1.8.1: stat /home/ubuntu/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner-arm64_v1.8.1: no such file or directory`
```

**Comment by afbjorklund** [comment]
I don't have any permissions to push images, but it would be nice if they could be provided...

**Comment by afbjorklund** [comment]
From what I can tell, there _should_ be multi-arch image for most of these releases:

https://hub.docker.com/r/coredns/coredns/tags

coredns / coredns : 1.6.5

| DIGEST       | OS/ARCH       | COMPRESSED SIZE |
| ------------ | ------------- | --------------- |
| 608ac7ccba5c | linux/amd64   | 12.62 MB        |
| 940ee9dbac91 | linux/arm     | 11.77 MB        |
| 8e2f327692ba | linux/arm64   | 11.49 MB        |
| d7e8326e88e7 | linux/ppc64le | 11.16 MB        |
| a74672cb43e2 | linux/s390x   | 12.2 MB         |

https://hub.docker.com/layers/coredns/coredns/1.6.5/images/sha256-608ac7ccba5ce41c6941fca13bc67059c1eef927fd968b554b790e21cc92543c

```
coredns/coredns                                           1.6.5               70f311871ae1        7 weeks ago         41.6MB
k8s.gcr.io/coredns                                        1.6.5               70f311871ae1        7 weeks ago         41.6MB
```

So we should probably drop the "ArchTag" for these ?

**Comment by afbjorklund** [comment]
The request for storage-provisioner is in #6007 - wonder what is needed for multi-arch ?

https://kubernetes.io/docs/concepts/containers/images/#building-multi-architecture-images-with-manifests

`Usage:  docker manifest create MANIFEST_LIST MANIFEST [MANIFEST...]`

https://docs.docker.com/engine/reference/commandline/manifest/

**Comment by afbjorklund** [comment]
> So we should probably drop the "ArchTag" for these ?

The request for coredns is in #6243, see also #6252

**Comment by afbjorklund** [comment]
> Hopefully the packaging can be fixed, for a better experience ?

CRI-O on Fedora is _finally_ fixed, in [updates-testing-modular](https://bodhi.fedoraproject.org/updates/FEDORA-MODULAR-2019-24636b4ff9)

**Comment by afbjorklund** [comment]
Now available here:
https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm64

**Comment by kamikaze** [comment]
> 
> 
> Now available here:
> https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm64

but it still pulls wrong images which results in:

> $ ./minikube-linux-arm64 start
> * minikube v1.8.1 on Gentoo 2.7 (arm64)
> * Automatically selected the docker driver
> * Creating Kubernetes in docker container with (CPUs=2) (4 available), Memory=2200MB (3755MB available) ...
> *
> X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create: > creating: prepare kic ssh: apply authorized_keys file ownership, output
> ** stderr **
> Error response from daemon: Container 8e01619e12b1b291d3c790998789af681834c5da49009f69427854b85775ba3e is not running
> ** /stderr **: chown docker:docker /home/docker/.ssh/authorized_keys: exit status 1
> stdout:
> stderr:
> Error response from daemon: Container 8e01619e12b1b291d3c790998789af681834c5da49009f69427854b85775ba3e is not running

and docker logs:
> standard_init_linux.go:211: exec user process caused "exec format error"

docker container ls -a:
> 8e01619e12b1        gcr.io/k8s-minikube/kicbase:v0.0.7   "/usr/local/bin/entr…"   15 minutes ago      Exited (1) 14 minutes ago                       minikube

**Comment by afbjorklund** [comment]
afaik it was **not** tested with the “docker” driver (KIC), only with the “none” driver

Please open a new issue, we should have a warning when trying to use ISO or KIC on non-amd64 platforms

**Comment by medyagh** [comment]
@kamikaze  thank you so much for reporting this issue !  and sorry about that bug. that should be an easy fix
I created a new issue for this, please track the update here
https://github.com/kubernetes/minikube/issues/7039
