### ISSUE TITLE
Show progress when downloading images during `minikube start`

### ISSUE THREAD

**Issue by kubesure** [kubernetes/minikube#5669]
**The exact command to reproduce the issue**:
minikube start --vm-driver=kvm2 --alsologtostderr -v=8

**The full output of the command that failed**:<details>
[minikube-wait-forever.txt](https://github.com/kubernetes/minikube/files/3747791/minikube-wait-forever.txt)

</details>

**The output of the `minikube logs` command**:<details>

[wait-forever-minikube-logs.txt](https://github.com/kubernetes/minikube/files/3747796/wait-forever-minikube-logs.txt)

</details>

**The operating system version**:

Linux dell-Latitude-3400 5.0.0-31-generic #33~18.04.1-Ubuntu SMP Tue Oct 1 10:20:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by afbjorklund** [comment]
Logs look happy enough, maybe it just took a long time to download all the k8s images ?

k8s.gcr.io/coredns_1.6.2 completed in 1m20.200450506s
k8s.gcr.io/kube-scheduler_v1.16.0 completed in 6m11.137268171s
k8s.gcr.io/kube-apiserver_v1.16.0 completed in 7m20.288675351s

Still missing etcd, which is the biggest image. And there was no more output whatsoever ?

``` console
$ ~/.minikube/cache/v1.16.0/kubeadm config images listk8s.gcr.io/kube-apiserver:v1.16.2
k8s.gcr.io/kube-controller-manager:v1.16.2
k8s.gcr.io/kube-scheduler:v1.16.2
k8s.gcr.io/kube-proxy:v1.16.2
k8s.gcr.io/pause:3.1
k8s.gcr.io/etcd:3.3.15-0
k8s.gcr.io/coredns:1.6.2

```

**Comment by kubesure** [comment]
No more output. These are the complete logs after the process completed.

**Comment by woodcockjosh** [comment]
Also having this problem. It actually never starts for me
```shell script
minikube start
```

**Comment by priyawadhwa** [comment]
Hey @kubesure, if you run `minikube start --download-only` it should download the necessary images. Afterwards, when you run `minikube start` it hopefully won't take forever.

Please let us know if this works, or if you still see some issues!

**Comment by kubesure** [comment]
@priyawadhwa executed ```minikube start --vm-driver=kvm2 --alsologtostderr -v=8``` without executing ```minikube start --download-only```  the long wait issue did not occur, this is maybe because I has created a minikube cluster with a none driver and images would have got downloaded. 

Also, the CoreDNS issue https://coredns.io/plugins/loop/#troubleshooting did not occur with KVM driver cluster which is cool.  In none driver I used ```sudo minikube start --extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf``` to resolve the CrashLoopBackOff.

This issue is resolved.
