### ISSUE TITLE
Insufficient memory / CPU?

### ISSUE THREAD

**Issue by aliakhtar** [kubernetes/minikube#567]
My laptop has 60+ GB of ram, and a 4-core i7 cpu. But when I try to create a deployment using 1 cpu and 1Gi as the memory / cpu requests, I get told there's insufficient CPU and memory. What gives?

Ubuntu 16.04, virtualbox.

**Comment by dlorenc** [comment]
Hey,

The minikube VM is configured by default to only use 1gb of memory. You can pass more during minikube start with the --memory flag. Note that you'll need to stop/start minikube for this to take effect.

**Comment by aliakhtar** [comment]
Thanks. And the CPU?

**Comment by dlorenc** [comment]
Same thing, we start with 1 CPU by default. --cpus= will get you more.

**Comment by r2d4** [comment]
You can run `minikube start -h` to display this helptext

https://github.com/kubernetes/minikube/blob/master/docs/minikube_start.md

**Comment by aliakhtar** [comment]
I'm 'guessing' that the memory is is specified in Mb but it would be useful to have that listed more clearly in the help text

**Comment by giorgiosironi** [comment]
Running:
```
minikube stop && minikube start --cpus 4 --memory 8192
```
in Minikube `v0.14.0` does not change the capacity of `kubectl describe nodes`, which stays at `cpu: 2`, the current default. Maybe there is something else to recreate too?

**Comment by uschmann** [comment]
minikube start --memory 4096 
Does not increase the memory for my machine.

I am on a mac using virtualbox as a virtualisation-driver.

If i take a look in the virtualbox settings of the VM i can see that memory is still at 2gb.

Any idea?

**Comment by aaron-prindle** [comment]
@uschmann Was a minikube VM already running?  If there is already a minikube VM running, the memory won't be changed as this is done on creation of the VM.  You will have to run a `minikube delete; minikube start --memory 4096` to have the increased memory.  We have an issue tracking this bug here:  https://github.com/kubernetes/minikube/issues/1147

**Comment by gsccheng** [comment]
@uschmann or to set as default you can do something like this and restart Minikube:
`minikube config set memory <memory>`

**Comment by easternbloc** [comment]
You do indeed have to `delete` before any edited config is reflected 😞

**Comment by dturanski** [comment]
On OS/X Virtualbox, I found the minikube memory setting was having no effect. I had to change it in VB.

**Comment by skhatri** [comment]
I did this on my mac

```
minikube stop
minikube delete
minikube --memory 8192 --cpus 2 start
```

**Comment by PavelSosin** [comment]
Finally, I had to delete entire minikube cluster to enlarge my minikube node to accommodate more Eclipse Che workspaces. Fortunately, it was only results of investigations but I spent few days to accumulate these results. Could you propose another way to manage minikube node size, even, via re-configuration of Oracle V-Box VM manually?

**Comment by losymear** [comment]
If you are using VirtualBox, you can first change the momory for that vm , then reconfig and restart. Look at [this](https://superuser.com/questions/926339/how-to-change-the-ram-allocated-to-an-os-in-virtualbox).

**Comment by alecholmez** [comment]
I used:
```
minikube config set memory 8192
minikube config set cpus 2
```
Seemed to persist my changes as well

**Comment by IvanBoyko** [comment]
Yes, it saves new values in config file:

```
$ cat ~/.minikube/config/config.json 
{
    "cpus": 4,
    "dashboard": true,
    "memory": 4096
}

```

**Comment by muratzorer** [comment]
You dont have to _delete_ minikube vm just to reconfigure some specs. Use the cli command of your hypervisor to reconfigure. For virtualbox:
```bash
$ minikube stop
$ VBoxManage modifyvm "minikube" --cpus 4 --memory 8196
$ minikube start -p mini --memory=8196 --cpus=4 --kubernetes-version=v1.13.0 \
    --vm-driver=virtualbox
```

**Comment by duffytilleman** [comment]
If you're on a mac using the hyperkit driver, here's a workaround to change memory or cpu without deleting your vm:

`minikube stop`
edit `$HOME/.minikube/machines/minikube/config.json`, change `"Driver.CPU"` and/or `"Driver.Memory"`
`minikube start`

**Comment by nikkirs** [comment]
This is due to insufficient RAM. Set RAM to 2gb.
`minikube start --memory=2gb`

**Comment by cglacet** [comment]
I confirm that the most simple method works on recent version:

```bash
❯ minikube delete
❯ minikube start --cpus 2 --memory 2048
😄  minikube v1.14.0 on Darwin 10.15.7
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
```

Which is confirmed by VirtualBox GUI: 

<img width="644" alt="Screenshot 2020-10-20 at 13 36 47" src="https://user-images.githubusercontent.com/28622118/96580916-4e8d0500-12d9-11eb-95d3-00eeb6c3f0cc.png">

**Comment by priyawadhwa** [comment]
Thanks @cglacet for sharing! If anyone else is seeing this, please open a new issue.

**Comment by LucasOliveiraS** [comment]
In the current version: **minikube version: v1.20.0**. I can't get the RAM down to 2GB. I tried to modify the total RAM directly by the virtualbox cli, but the minikube breaks and does not start the cluster again.

**Comment by XDavidT** [comment]
> I did this on my mac
> 
> ```
> minikube stop
> minikube delete
> minikube --memory 8192 --cpus 2 start
> ```

It's important to mark, when you delete a cluster, all your data will be erased.

**Comment by GregWasHere** [comment]
"max" value can also come in handy
```sh
minikube --memory max --cpus max start
# --memory='': Amount of RAM to allocate to Kubernetes (format: <number>[<unit>], where unit = b, k, m or g). Use "max" to use the maximum amount of memory.
# --cpus='2': Number of CPUs allocated to Kubernetes. Use "max" to use the maximum number of CPUs.
```

**Comment by EricoCartmanez** [comment]
<img width="856" alt="Screenshot 2021-09-07 at 4 00 14 PM" src="https://user-images.githubusercontent.com/37179870/132349006-48ff76a9-c4e5-4b1f-92ac-e5f50e712eab.png">


> "max" value can also come in handy
> 
> ```shell
> minikube --memory max --cpus max start
> # --memory='': Amount of RAM to allocate to Kubernetes (format: <number>[<unit>], where unit = b, k, m or g). Use "max" to use the maximum amount of memory.
> # --cpus='2': Number of CPUs allocated to Kubernetes. Use "max" to use the maximum number of CPUs.
> ```

Any ideas why I get that?..

<img width="856" alt="Screenshot 2021-09-07 at 4 00 14 PM" src="https://user-images.githubusercontent.com/37179870/132349074-422b2c08-8140-4da9-ad0e-ca9fae1edb43.png">
