### ISSUE TITLE
X Unable to start VM: start: exit status 1

### ISSUE THREAD

**Issue by ghd258** [kubernetes/minikube#5673]
minikube start --vm-driver=hyperv
* minikube v1.4.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing hyperv VM for "minikube" ...
* Retriable failure: start: exit status 1
* Deleting "minikube" in hyperv ...
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing hyperv VM for "minikube" ...
* Retriable failure: start: exit status 1
* Deleting "minikube" in hyperv ...
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing hyperv VM for "minikube" ...
* Retriable failure: start: exit status 1
* Deleting "minikube" in hyperv ...
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing hyperv VM for "minikube" ...
* Retriable failure: start: exit status 1
* Deleting "minikube" in hyperv ...
E1021 16:53:15.149556   10404 cache_images.go:79] CacheImage k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.159558   10404 cache_images.go:79] CacheImage gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> C:\Users\Administrator\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1 failed: fetching image: Get https://gcr.io/v2/: dial tcp 74.125.204.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.160558   10404 cache_images.go:79] CacheImage k8s.gcr.io/kube-scheduler:v1.16.0 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.16.0 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.165556   10404 cache_images.go:79] CacheImage k8s.gcr.io/kube-controller-manager:v1.16.0 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.16.0 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.203557   10404 cache_images.go:79] CacheImage k8s.gcr.io/etcd:3.3.15-0 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\etcd_3.3.15-0 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.337557   10404 cache_images.go:79] CacheImage k8s.gcr.io/kube-apiserver:v1.16.0 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.16.0 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.372558   10404 cache_images.go:79] CacheImage k8s.gcr.io/coredns:1.6.2 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\coredns_1.6.2 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.400558   10404 cache_images.go:79] CacheImage k8s.gcr.io/kube-addon-manager:v9.0.2 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0.2 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.432558   10404 cache_images.go:79] CacheImage k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.470558   10404 cache_images.go:79] CacheImage k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 16:53:15.495557   10404 cache_images.go:79] CacheImage k8s.gcr.io/pause:3.1 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\pause_3.1 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
*
X Unable to start VM: start: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\Users\Administrator>

**Comment by ghd258** [comment]
PS C:\Users\Administrator> minikube start
* minikube v1.4.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E1021 17:00:57.205704    7208 cache_images.go:79] CacheImage k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.205704    7208 cache_images.go:79] CacheImage k8s.gcr.io/kube-apiserver:v1.16.0 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.16.0 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.290713    7208 cache_images.go:79] CacheImage k8s.gcr.io/kube-addon-manager:v9.0.2 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0.2 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.291687    7208 cache_images.go:79] CacheImage k8s.gcr.io/pause:3.1 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\pause_3.1 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.369830    7208 cache_images.go:79] CacheImage k8s.gcr.io/kube-controller-manager:v1.16.0 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.16.0 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.402830    7208 cache_images.go:79] CacheImage k8s.gcr.io/kube-scheduler:v1.16.0 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.16.0 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.463018    7208 cache_images.go:79] CacheImage k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.492347    7208 cache_images.go:79] CacheImage k8s.gcr.io/etcd:3.3.15-0 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\etcd_3.3.15-0 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.539348    7208 cache_images.go:79] CacheImage gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> C:\Users\Administrator\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1 failed: fetching image: Get https://gcr.io/v2/: dial tcp 74.125.204.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.578344    7208 cache_images.go:79] CacheImage k8s.gcr.io/coredns:1.6.2 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\coredns_1.6.2 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E1021 17:00:57.604347    7208 cache_images.go:79] CacheImage k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> C:\Users\Administrator\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13 failed: fetching image: Get https://k8s.gcr.io/v2/: dial tcp 108.177.97.82:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
* Found network options:
  - NO_PROXY=192.168.99.101
  - no_proxy=192.168.99.101
* Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...

**Comment by ghd258** [comment]
X Error starting cluster: cmd failed: sudo env PATH=/var/lib/minikube/binaries/v1.16.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
[init] Using Kubernetes version: v1.16.0
[preflight] Running pre-flight checks
        [WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.16.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.16.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.16.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.16.0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.3.15-0: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.6.2: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

: Process exited with status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by priyawadhwa** [comment]
Hey @ghd258 could you try again with the latest version of MInikube? [v1.5.1](https://github.com/kubernetes/minikube/releases/tag/v1.5.1) was just released and may have some fixes for some of the networking issues you faced.

If it doesn't work, could you please provide the output of `minikube start --logtostderr`. Thanks!
