### ISSUE TITLE
Remove inaccurate documentation from kubernetes.io/

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5686]

**Comment by tstromberg** [comment]
Upstream issue: https://github.com/kubernetes/website/issues/15969

**Comment by tstromberg** [comment]
On hold, as I'm waiting to hear back from https://github.com/kubernetes/website/issues/15969

**Comment by tstromberg** [comment]
I'll be working on this issue this week.

**Comment by tstromberg** [comment]
I think we're nearly done with the install doc. Next up will be the usage doc.

**Comment by afbjorklund** [comment]
There was some confusion between docker and podman added in https://github.com/kubernetes/website/issues/19218

**Comment by priyawadhwa** [comment]
It seems like this issue has been resolved in https://github.com/kubernetes/website/issues/15969  by https://github.com/kubernetes/website/pull/24533
