### ISSUE TITLE
tiller link is broken

### ISSUE THREAD

**Issue by davidthewatson** [kubernetes/minikube#5698]
This link is broken:

https://minikube.sigs.k8s.io/docs/tasks/deploy/addons/helm-tiller/README.md

in this page:

https://minikube.sigs.k8s.io/docs/tasks/addons/

**Comment by nanikjava** [comment]
This has been fixed and it's live. The correct url now is https://minikube.sigs.k8s.io/helm-tiller/readme/

Can we please close this ticket.

Thanks

**Comment by medyagh** [comment]
thanks @nanikjava closed.
