### ISSUE TITLE
service: --format flag missing?

### ISSUE THREAD

**Issue by jroper** [kubernetes/minikube#5699]
It used to be possible to do this:

```
export MY_SERVICE_HOST=$(minikube service my-service --format "{{.IP}}:{{.Port}}")
```

And then you'd have the host name and port, without a prefixed scheme, and this is useful because not everything is http or https. Since the `--format` option was removed, this is no longer possible.

In the meantime, this seems to be the most expedient way for a script to get a `hostname:port` string:

```
export MY_SERVICE_HOST=$(minikube ip):$(kubectl get service my-service -o "jsonpath={.spec.ports[0].nodePort}")
```

**Comment by tstromberg** [comment]
As far as I know, minikube `--format` wasn't removed, though I will note that it no longer appears  `minikube help`. It's definitely there though:

`serviceCmd.PersistentFlags().StringVar(&serviceURLFormat, "format", defaultServiceFormatTemplate, "Format to output service URL in. This format will be applied to each url individually and they will be printed one at a time.")`

Were you getting an error message trying to use that command?

Possibly related: #5117

**Comment by priyawadhwa** [comment]
Hey @jroper I just tried running 

```
kubectl run busybox --image busybox -- sleep 1000
kubectl expose deploy/busybox --port 8080 --type NodePort
minikube service busybox --format "{{.IP}}:{{.Port}}"
```

and got the expected output
```
|-----------|---------|-------------|---------------------|
| NAMESPACE |  NAME   | TARGET PORT |         URL         |
|-----------|---------|-------------|---------------------|
| default   | busybox |             | 192.168.39.40:31302 |
|-----------|---------|-------------|---------------------|
192.168.39.40:31302
```

from Minikube build @ HEAD.

I'm going to close this issue as it seems the `--format` flag is working as expected. The main issue is that it doesn't appear in help text, but I think that should be covered by #5117. If you think this has been closed in error, please reopen at any time!
