### ISSUE TITLE
unable to create/update the DNS service: etcdserver: request timed out (resource exhaustion?)

### ISSUE THREAD

**Issue by nikhilgithub** [kubernetes/minikube#5701]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>

* minikube v1.4.0 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Using the running hyperv "minikube" VM ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...
* Relaunching Kubernetes using kubeadm ...
*
X Error restarting cluster: addon phase: command failed: sudo env PATH=/var/lib/minikube/binaries/v1.16.0:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml
stdout: [addons]: Migrating CoreDNS Corefile

stderr: error execution phase addon/coredns: unable to create/update the DNS service: etcdserver: request timed out
To see the stack trace of this error execute with --v=5 or higher
: Process exited with status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
* Problems detected in kube-addon-manager [f7d859c13518]:
  - error: no matches for kind "DaemonSet" in version "apps/v1"

</details>

**The output of the `minikube logs` command**:<details>

Logs are attached in file.
[minikube_logs.txt](https://github.com/kubernetes/minikube/files/3761839/minikube_logs.txt)

</details>

**The operating system version**:

Windows 10[1803] 64bit V5.3

**Comment by nikhilgithub** [comment]
This happens after installing below crds for knative:

 kubectl apply --selector knative.dev/crd-install=true \
   --filename https://github.com/knative/serving/releases/download/v0.9.0/serving.yaml \
   --filename https://github.com/knative/eventing/releases/download/v0.9.0/release.yaml \
   --filename https://github.com/knative/serving/releases/download/v0.9.0/monitoring.yaml

After running these commands api server got stopped.

**Comment by tstromberg** [comment]
My best guess is that your cluster has run out of resources and that services are timing out.

https://github.com/knative/docs/blob/master/docs/install/Knative-with-Minikube.md mentions that you will need at least  `--memory=8192 --cpus=6`

Here's one sign in your logs that things are in bad shape:

`  10:25:28 up 11:39,  0 users,  load average: 46.59, 44.70, 44.75`

The other is this apiserver crash that I can't see the full backtrace for:

```
*       /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/wrap.go:51 +0x105
* net/http.HandlerFunc.ServeHTTP(0xc00777cfe0, 0x7b04720, 0xc00a5b1490, 0xc00b263e00)
*       /usr/local/go/src/net/http/server.go:1995 +0x44
* k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.(*APIServerHandler).ServeHTTP(0xc00778b500, 0x7b04720, 0xc00a5b1490, 0xc00b263e00)
*       /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:189 +0x51
* net/http.serverHandler.ServeHTTP(0xc00137a4e0, 0x7b04720, 0xc00a5b1490, 0xc00b263e00)
*       /usr/local/go/src/net/http/server.go:2774 +0xa8
* net/http.initNPNRequest.ServeHTTP(0xc00519d880, 0xc00137a4e0, 0x7b04720, 0xc00a5b1490, 0xc00b263e00)
*       /usr/local/go/src/net/http/server.go:3323 +0x8d
* k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).runHandler(0xc00dbf9b00, 0xc00a5b1490, 0xc00b263e00, 0xc00c0ee7e0)
*       /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:2125 +0x89
* created by k8s.io/kubernetes/vendor/golang.org/x/net/http2.(*serverConn).processHeaders
*       /workspace/anago-v1.16.0-rc.2.1+2bd9643cee5b3b/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/golang.org/x/net/http2/server.go:1859 +0x4f4
```

Do you mind sharing the output of `kubectl descrribe node` and `minikube status`?

**Comment by nikhilgithub** [comment]
kubectl describe:
error: You must specify the type of resource to describe. Use "kubectl api-resources" for a complete list of supported resources.


minikube status
host:
kubelet:
apiserver:
kubectl:

**Comment by priyawadhwa** [comment]
Hey @nikhilgithub, do you still see this error when you increases the memory/cpu with `--memory=8192 --cpus=6` on `minikube start`?
