### ISSUE TITLE
Change Minikube Home

### ISSUE THREAD

**Issue by anthonma** [kubernetes/minikube#5703]
I'm trying to run a kubernetes cluster with minikube on a linux vm.
Since the root directory has no space left I want to change the location of the .minikube and .kube folders.
I tried to set the MINIKUBE_HOME variable via
````
export MINIKUBE_HOME=/data/amartin/
````
Afterwards I'm executing:
````
sudo minikube start --memory=5120 --kubernetes-version=v1.15.4 --vm-driver=none
````
The command terminates with an error:
````
Error: [DNS_TIMEOUT] waiting for k8s-app=kube-dns: timed out waiting for the condition
````
The cluster is created nevertheless, but at the wrong location.

**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

![minikube_timeout](https://user-images.githubusercontent.com/55550413/67390698-7601a280-f59d-11e9-9873-3a5c616caa53.PNG)

</details>

**The output of the `minikube logs` command**:<details>

![minikube_logs](https://user-images.githubusercontent.com/55550413/67390714-7ac65680-f59d-11e9-960a-2cbf4b0d51b3.PNG)

</details>

**The operating system version**:
Centos / Red Hat 7.5

**Comment by afbjorklund** [comment]
You need to use `sudo MINIKUBE_HOME=/data/amartin minikube`, in order to preserve env variables.

But there could be other side effects of `/root` not having any space, so you should probably fix that.

**Comment by afbjorklund** [comment]
Another problem is that the config will be owned by owned by root, so you will _always_ need sudo.

However, I'm not sure the home has anything to do with the startup failure... SELinux is more likely.

**Comment by anthonma** [comment]
I will close this issue for now, because the environment I use will probably change. If there should be the same or a similar problem, I will reopen it or create a new issue.
