### ISSUE TITLE
minikube: RunContainerError

### ISSUE THREAD

**Issue by zhangxiaoyu-zidif** [kubernetes/minikube#5704]
**The exact command to reproduce the issue**:
when use the latest minikube and execute minikube start, it will show container created failed, this is because of https://success.docker.com/article/error-oci-runtime-create-failed-docker-1809

**The full output of the command that failed**:<details>
when to describe pod
```shell
  Warning  FailedScheduling  7m32s  default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
  Warning  FailedScheduling  109s   default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.
  Normal   Scheduled         104s   default-scheduler  Successfully assigned default/mount-pod to minikube
  Normal   Pulling           103s   kubelet, minikube  Pulling image "busybox"
  Normal   Pulled            93s    kubelet, minikube  Successfully pulled image "busybox"
  Normal   Created           93s    kubelet, minikube  Created container main
  Warning  Failed            93s    kubelet, minikube  Error: failed to start container "main": Error response from daemon: OCI runtime create failed: open /var/run/docker/runtime-runc/moby/main/state.json: no such file or directory: unknown
```

</details>
**The output of the `minikube logs` command**:<details>
</details>

**The operating system version**:
macOS

 ➤ minikube version                                                                             
minikube version: v1.1.1
Kubernetes version: 1.14.8
docker version: 18.09.6

**Comment by afbjorklund** [comment]
The referenced issue doesn't seem to have anything to do with the reported error ?

**Comment by afbjorklund** [comment]
Can you please try again with a newer version of minikube, `v1.1.1` is not the latest.

**Comment by zhangxiaoyu-zidif** [comment]
@afbjorklund 
minikube version                                                                                                                             
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6

this version works fine. All problems are done. Thanks!

**Comment by nanikjava** [comment]
Can we close this issue as the OP indicate that upgrading minikube to v1.4.0 fixes the problem.
