### ISSUE TITLE
Download rpm version 1.4 does not work

### ISSUE THREAD

**Issue by kmplngj** [kubernetes/minikube#5709]
**The exact command to reproduce the issue**:
Go to https://minikube.sigs.k8s.io/docs/start/linux/
Switch tab to _Fedora/Red Hat (rpm)_
Copy command to Terminal

**The full output of the command that failed**:<details>
curl: (7) Failed to connect to storage.googleapis.com port 443: Connection refused
</details>

**The operating system version**:
Fedora 30

**Comment by afbjorklund** [comment]
As a fallback solution, all binaries are also available at GitHub

https://github.com/kubernetes/minikube/releases/download/v1.4.0/minikube-1.4.0.rpm

**Comment by afbjorklund** [comment]
The download works from here though. Wonder if there is a proxy involved here somewhere ?

https://storage.googleapis.com/minikube/releases/latest/minikube-1.4.0.rpm

**Comment by kmplngj** [comment]
My mistake. PiHole blocked the google domain.
