### ISSUE TITLE
Failed to save config profiles/minikube/config.json

### ISSUE THREAD

**Issue by kalyanvajrapu8** [kubernetes/minikube#5715]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:
```
Failed to save config: error acquiring lock for /home/kalyan2smiles/.minikube/profiles/minikube/config.json: unable to open /tmp/juju-minikube-config-json: permission deni ed
```

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by kalyanvajrapu8** [comment]
how to set the path

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
@kalyanvajrapu8  I haven't heard from you, are you still having this issue ?

**Comment by gaetan1903** [comment]
I have the same issue .

The command: sudo minikube start --vm-driver=none disk_size=2g 
The output:
 sudo minikube start --vm-driver=none disk_size=1g                                                                                                               70 ↵
🙄  minikube v1.5.2 on Arch rolling

💣  Failed to save config: error acquiring lock for /root/.minikube/profiles/minikube/config.json: unable to open /tmp/juju-minikube-config-json: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by gaetan1903** [comment]
I solved mine, 
I delete all minikube file in the /tmp 

Maybe it's caused by first installation that I am stopped

**Comment by kalyanvajrapu8** [comment]
Thanks Getha,
Let me try and inform

**Comment by tstromberg** [comment]
I believe we fixed this in minikube v1.6.1. Can anyone here confirm?

**Comment by kalyanvajrapu8** [comment]
Thanks i will inform u after done task

**Comment by shahbaz-aslam2** [comment]
minikube v1.7.3 on Ubuntu 18.04
💣  Unable to load config: stat: stat /home/shahbaz/.minikube/profiles/minikube/config.json: permission denied

**Comment by gaetan1903** [comment]
@shahbaz-aslam2  try to delete all files on /tmp..

**Comment by rakovets** [comment]
> minikube v1.7.3 on Ubuntu 18.04
>  Unable to load config: stat: stat /home/shahbaz/.minikube/profiles/minikube/config.json: permission denied

@gaetan1903 is right. You can use commands:
```sh
sudo rm -rf /tmp/juju-mk*
sudo rm -rf /tmp/minikube.*
```

**Comment by waqas-cs** [comment]
$ sudo minikube start --vm-driver=none
😄  minikube v1.11.0 on Debian kali-rolling (vbox/amd64)
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube

❌  [JUJU_LOCK_DENIED] error provisioning host Failed to save config: failed to acquire lock for /root/.minikube/profiles/minikube/config.json: {Name:mk270d1b5db5965f2dc9e9e25770a63417031943 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}: unable to open /tmp/juju-mk270d1b5db5965f2dc9e9e25770a63417031943: permission denied
💡  Suggestion: Run 'sudo sysctl fs.protected_regular=0', or try a driver which does not require root, such as '--driver=docker'
⁉   Related issue: https://github.com/kubernetes/minikube/issues/6391

**What the issue please guide me, I have installed minikube but its not gonna be start**
