### ISSUE TITLE
minikube does not work on windows 10

### ISSUE THREAD

**Issue by pnisbettmtc** [kubernetes/minikube#5726]
I downloaded minikube added the minikube.exe location to my system path.
I added a KUBECONFIG environment variable -> C:\users\pnisbett\.kube\config
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>

C:\Users\pnisbett\kubernetes>minikube delete
* Failed to delete cluster: load: filestore "minikube": open C:\Users\pnisbett\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* You may need to manually remove the "minikube" VM from your hypervisor
* Removing C:\Users\pnisbett\.minikube\machines\minikube ...
* The "minikube" cluster has been deleted.

C:\Users\pnisbett\kubernetes>minikube start
* minikube v1.4.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
  - KUBECONFIG=C:\users\pnisbett\.kube\config
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\pnisbett\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Retriable failure: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\pnisbett\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X Unable to start VM: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\pnisbett\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

C:\Users\pnisbett\kubernetes>minikube logs
*
X api load: filestore "minikube": open C:\Users\pnisbett\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Windows 10

**Comment by pnisbettmtc** [comment]
This has been resolved.
I uninstalled docker . I reran minikube start and it installed.
Knowing that you can't install Minikube if Docker is already installed would have saved a lot of time. Perhaps put that in the instructions.

**Comment by tstromberg** [comment]
@pnisbettmtc - minikube  should coexist peacefully with Docker. I'm not actually sure what went wrong here.

**Comment by pnisbettmtc** [comment]
Thanks for looking at it.

Further experience with Minikube has convinced me it is pretty flakey technology. It crashes regularly with a message that I have to delete the VM (currently running in virtual box on a different windows10 computer that has a lot more memory). Obviously,every time I delete the Minikube VM ,I have to re install everything again on that Minikube machine/pod again.

It is a very frustrating experience.
-Paul
