### ISSUE TITLE
Changing service cidr range breaks DNS resolution

### ISSUE THREAD

**Issue by jgoeres** [kubernetes/minikube#5727]
Our company intranet uses large parts of the 10.0.0.1/8 subnet. Alas, the default service CIDR range used by minikube (resp. kubeadm?) is 10.96.0.*. To avoid problems, I wanted to change pod and service CIDR range with these two options passed to minikube start:

--service-cluster-ip-range='172.20.0.0/14' --extra-config=kubelet.pod-cidr=172.16.0.0/14 

The VM seemed to startup fine, but after deploying our application, I noticed that the DNS names of services could not be resolved by our pods, e.g.

    nslookup our-service
    nslookup: can't resolve '(null)': Name does not resolve

I checked /etc/resolv.conf inside the pod, and indeed, it still pointed to the default IP of the kubedns service, i.e., 10.96.0.10. I would expect that changing the service CIDR range would also take care of that.
Looking for a workaround, I tried using extra-config also for the service-cidr range, i.e.,

    --extra-config=kubelet.pod-cidr=172.16.0.0/14 --extra-config=kubelet.service-cidr=172.20.0.0/14

Now the minikube start would fail cause kubelet wouldn't start: 

    [...]
    Oct 25 11:40:15 minikube kubelet[24917]: F1025 11:40:15.308498   24917 server.go:156] unknown flag: --service-cidr
    Oct 25 11:40:15 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
    [...]
.

**Comment by medyagh** [comment]
@jgoeres  thanks for creating this issue ! this does seem to be a bug. I would love minikube to be able to create service in CIDR ranges that works well for everyone including corp networks !

I would be happy to review any PR to fix this issue !

**Comment by evankanderson** [comment]
I was able to repro this with in January with v1.6.2:

```shell
minikube start --keep-context --kubernetes-version=1.16.6 --memory=2536mb --service-cluster-ip-range=10.64.0.0/16 --vm-driver=vmware -p newerkube
```

```shell
kubectl run my-shell --rm -i --tty --image cosmintitei/bash-curl -- bash
```

```shell
bash-4.4# cat /etc/resolv.conf 
nameserver 10.96.0.10
search default.svc.cluster.local svc.cluster.local cluster.local
options ndots:5
```

**Comment by dmvk** [comment]
Same isssue here on macOS with the latest version.
