### ISSUE TITLE
Not all parameters available in "minikube start" have a corresponding setting in "minikube config", and for those that do, some don't seem to work

### ISSUE THREAD

**Issue by jgoeres** [kubernetes/minikube#5729]
The problem in this issue was brought up by me in https://github.com/kubernetes/minikube/issues/5706
but as requested I am opening a new issue for that.
When trying to replace a "minikube start" command with a lot of params with a simple "minikube start" (i.e., without params) plus setting "minikube config" accordingly, I noticed that not all parameters available in "minikube start" have corresponding settings in "minikube config", e.g.
--extra-config
--apiserver-{name|names|port|ips} (Not that I stictly needed those for my use case, but someone might...)

Further, some settings that do exist in "minikube config" don't seem to work, e.g.,

    $ minikube config set memory 12G
    *
    X Set failed: [memory:strconv.Atoi: parsing "12G": invalid syntax]

while 

    --memory 12g 

worked fine.

Same problem with

    $ minikube config set insecure-registry myinsecureregistry:12345
    *
    X Set failed: [Cannot enable/disable invalid addon insecure-registry]

As before, the corresponding "minikube start" switch 

    minikube config set insecure-registry myinsecureregistry:12345 

works.

Maybe I am using "minikube config" incorrectly, but other settings (cpus, disk-size) worked when used that way, e.g.

$ minikube config set disk-size 30G
! These changes will take effect upon a minikube delete and then a minikube start

$ minikube config set cpus 4
! These changes will take effect upon a minikube delete and then a minikube start

**Comment by medyagh** [comment]
You pointed out a shortcoming of minikube ! and I agree we need to fix it !

we could either make sure any start args automaticly get saved to config or we update the config items that should be listed.


either way I would be happy to review a PR that fixes this.

**Comment by PabloCamino** [comment]
Should this issue be labeled as an enhancement request instead of bug so it doesn't go closed without a fix?

**Comment by medyagh** [comment]
we still need to make this happen. I agree @PabloCamino this is a feature request.

**Comment by otherguy** [comment]
@medyagh  is there a corresponding feature request ticket to track this already?
