### ISSUE TITLE
Add Integration test for "cache" command for non-docker runtimes

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5733]
we don't have any integration test for "minikube cache add" command .

we need basic test for cache, that would cover docker, crictl, ...

**Comment by afbjorklund** [comment]
Note that `crictl` is used for **all** CRI runtimes (i.e. everyone but Docker), not only CRI-O.

Today it is only the "load" part of the caching that is handled by the runtime, the "cache" (or download) part is handled by the `github.com/google/go-containerregistry` library (for all container runtimes).

https://github.com/google/go-containerregistry

But the "add" command does both: cache and load

In general we could need more tests for using Docker with [cri-tools](https://github.com/kubernetes-sigs/cri-tools), even if not required...

Eventually even Docker will use the Container Runtime Interface, and then it would be good to have a test for it. Basically making sure that the `Manager` interface works, without using `docker` commands.

----
BTW: The error message for `minikube cache add` is rather useless:

```console
$ minikube cache add busybox

💣  Failed to cache and load images: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

The helpful libmachine message isn't really going to fix the minikube machine.
