### ISSUE TITLE
beautify mininikube emojis !

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5734]
I feel like there could be a brush up on the minikube emojis, 

## minikube delete
its kind of weird in one emoji we have breaking heart and the one after is fire...

```
🔥  Removing /root/.minikube/machines/minikube ...
💔  The "minikube" cluster has been deleted.
🔥  Successfully deleted profile "minikube"
```
this specially looks weird when deleting multiple profiles

## minikube stop
also for minikube stop (tested on none driver) I see two stop icons, which one of them is redundant

```
$ sudo ./out/minikube stop
✋  Stopping "minikube" in none ...
✋  Stopping "minikube" in none ...
🛑  "minikube" stopped.
```

I would be happy to review any PR that makes deleting minikube more beautiful

**Comment by afbjorklund** [comment]
> also for minikube stop (tested on none driver) I see two stop icons

I think it only gets 5 seconds in order to `StopHost`.

This is OK for pulling the plug on a VM, but `none` doesn't support stop.
Instead it is doing a graceful stop of all the running containers instead...

And that probably takes longer, so it does a retry ?

**Comment by afbjorklund** [comment]
> I would be happy to review any PR that makes deleting minikube more beautiful

So do you mean "swap for other random emojis", or do you envision a custom font or something ?

https://github.com/kubernetes/minikube/blob/v1.5.0/pkg/minikube/out/style.go#L51_L116

**Comment by afbjorklund** [comment]
Think most of these were designed by @tstromberg

**Comment by nicolereineke** [comment]
Has the team considered FontAwesome as a source of additional emojis ?  (https://fontawesome.com/icons?d=gallery&m=free) 
We could maintain the existing icons that are working, and as we need new ones, we can easily (and free) phase them in by adding Creative Commons Attribution.

In this instance, the trash or minus icon could easily meet the needs.
 https://fontawesome.com/icons/trash-alt?style=regular

If the concern is a need for maintaining the black outline and color scheme, I can contribute colorized versions in .svg or other format required.

**Comment by afbjorklund** [comment]
@nicolereineke : how would you use custom fonts or icons in the terminal ?
Normally it just uses Unicode characters, which can render like anything...

Like so: (`'\U0001f5d1'`) 🗑️ https://emojipedia.org/wastebasket/
These can appear in black-and-white, or maybe not at all (ASCII)

**Comment by nicolereineke** [comment]
It took setup, but we are able to add new fonts to terminal as described
here:
https://link.medium.com/zZtqdFoKf2

 the color change on the icon font requires css, so that would only be
applicable to the documentation display or other online/GUI  user
interfaces

Just an idea. I’m new to terminal interfaces, so open to being wrong.

**Comment by afbjorklund** [comment]
Ah, interesting concept : ”patching” your favorite font with your favorite icons... Haven’t tried it, but the idea itself sounds novel enough to try.

https://www.nerdfonts.com/

Not sure how minikube (or go in general) could interact with this, so there are compatibility issues left to sort out. Like “use it if available”

**Comment by afbjorklund** [comment]
This is actually quite simple to use, just use a different code point:
https://github.com/ryanoasis/nerd-fonts/wiki/Icon-Names-in-Shell

![docker-patched](https://user-images.githubusercontent.com/10364051/70395413-9a56f880-19fe-11ea-9581-9e24bb282911.png)

^ @medya

It does look awful with a non-patched font, so needs to be checked...
But this makes all of those extra icons available, for an alternate "style".

Thanks!

**Comment by afbjorklund** [comment]
Actually it can probably look quite weird, even with the nerd font.

![start-icon](https://user-images.githubusercontent.com/10364051/70396130-65e73a80-1a06-11ea-80c2-108851894f87.png)

There is no guarantee that the icons look OK, next to the emoji.

In this case it ended up "too small", so looks worse than the previous:

![start-emoji](https://user-images.githubusercontent.com/10364051/70396142-7d262800-1a06-11ea-9cb2-2edfbda93c59.png)

Probably needs some better holistic approach, before changing bits ?

----

For this test, I just changed a single one:

```diff
@@ -97,7 +99,7 @@ var styles = map[StyleEnum]style{
        Mounting:         {Prefix: "📁  "},
        Celebrate:        {Prefix: "🎉  "},
        ContainerRuntime: {Prefix: "🎁  "},
-       Docker:           {Prefix: "🐳  "},
+       Docker:           {Prefix: "🐳  ", Icon: "  "},
        CRIO:             {Prefix: "🎁  "}, // This should be a snow-flake, but the emoji has a strange width on macOS
        Containerd:       {Prefix: "📦  "},
        Permissions:      {Prefix: "🔑  "},
```

It will show as missing ([]), in the wrong font...

Probably should be written as `\ue7b0` instead.

**Comment by afbjorklund** [comment]
The [Nerd Fonts "cheat sheet"](https://www.nerdfonts.com/cheat-sheet) lists the available icons:

![nerd-fonts-cheat-sheet](https://user-images.githubusercontent.com/10364051/70396459-70570380-1a09-11ea-94b1-f51e47db2c06.png)

For instance the icon above is called `fa_trash_o` (or `\uf014`)

https://fontawesome.com/v4.7.0/icon/trash-o

`# Font Awesome (version 4.7.0, 675 icons, 111 aliases)`

----

And of course the [Emojipedia](https://emojipedia.org/) shows the Unicode emojis...

**Comment by afbjorklund** [comment]
Here is the appearance when using icons:
![minikube-icons](https://user-images.githubusercontent.com/10364051/70635188-ca3b1180-1c33-11ea-96b9-0225fd2b57d4.png)

As compared with the normal using emoji:
![minikube-emoji](https://user-images.githubusercontent.com/10364051/70635240-de7f0e80-1c33-11ea-9664-f92ce7e3d107.png)

There is an environment variable to toggle between them...

In order for it to work, it needs a "[Nerd Fonts](https://www.nerdfonts.com/font-downloads)" font chosen.

**Comment by afbjorklund** [comment]
Choosing names instead of icons, made it harder to compare with emojis.
Could keep it as an alternative for later (?), used raw `rune` literals for now:

```
''
const human rune = '\uf7e5'
```

**Comment by afbjorklund** [comment]
As noted in the PR, here is a comparison between the emojis and the icons:

![nerdfonts](https://user-images.githubusercontent.com/10364051/70866422-c4ae3600-1f69-11ea-9801-588bbc9d8b0b.png)

[nerdfonts.txt](https://github.com/kubernetes/minikube/files/3965188/nerdfonts.txt)
[nerdfonts.pdf](https://github.com/kubernetes/minikube/files/3965210/nerdfonts.pdf)

**Comment by afbjorklund** [comment]
@nicolereineke : it looks like we will stick with the emojis, since mixing/matching emojis looks weird - especially on the newer platforms where emojis are in color (but icons are still shown in black/white)

Theoretically one could add color to minikube, but I think this issue has been hi-jacked long enough...
@medyagh: feel feel to clarify what you wanted to get done, change an emoji or avoid two "stop"s ?

1)
> 💔  The "minikube" cluster has been deleted.
> 🔥  Successfully deleted profile "minikube"

2)

> ✋  Stopping "minikube" in none ...
> ✋  Stopping "minikube" in none ...

**Comment by afbjorklund** [comment]
@medyagh : can we close this ?

```
🔥  Deleting "minikube" in virtualbox ...
💀  Removed all traces of the "minikube" cluster.
```

**Comment by sdaitzman** [comment]
🔥
