### ISSUE TITLE
Change in machine name leaves two configurations under ~/.minikube/machines

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#574]
BUG REPORT 

**Minikube version** (use `minikube version`): v0.9.0

**Environment**:
- **OS** (e.g. from /etc/os-release): linux
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikubeVM/config.json | grep DriverName`): kvm (we should also change this issue template to   `cat ~/.minikube/machines/minikube/config.json | grep DriverName` as now it will give us the wrong configuration)

**What happened**:
changing the name of the minikube VM #546 led minikube to create a new folder (and possibly an additional machine?) 
```
-> ls ~/.minikube/machines/
minikube  minikubeVM  server-key.pem  server.pem
```

**What you expected to happen**:
Only one folder filled with the single minikube configuration

**How to reproduce it** (as minimally and precisely as possible):
Have an installation prior to minikube v0.9.0 and then upgrade to current version

Not affecting any functionality, but after an upgrade from an older version, minikube might have created an additional virtual machine.  Even if it hasn't, the configuration still might confuse some users if they looked or were trying to debug.

Whats the best way to clean up these files automatically?  We could go ahead and delete all other configurations in that folder except for the one which we are reading.

**Comment by dlorenc** [comment]
Ah whoops. That's not good.

I'd rather not add one-time use code to handle deletions/cleanups, but I'm not sure what else to do. Just document it?

**Comment by jimmidyson** [comment]
That's not good. Sorry about that!

**Comment by r2d4** [comment]
I'm going to just leave this here as documentation but close as "won't fix" for now.  Shouldn't affect anyone going forward and anyone who is confused can look to this issue for reference.

The configuration currently used is in `~/.minikube/machines/minikube`
