### ISSUE TITLE
CI isn't adding test results to PR's

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5740]
I see the tests running in Jenkins, but it isn't being added to the PR.

It's as if `minikube_set_pending.sh` isn't being run.

/cc @medyagh @sharifelgamal

**Comment by tstromberg** [comment]
example: https://github.com/kubernetes/minikube/pull/5737

**Comment by sharifelgamal** [comment]
We now require the `ok-to-test` label to be on a PR in order to show test results. Using the `/ok-to-test` command in a comment on a PR should be enough to add the label and kick the tests off.
