### ISSUE TITLE
unable to retrieve container logs for docker

### ISSUE THREAD

**Issue by lubocheng** [kubernetes/minikube#5752]
**重现问题所需的命令**：
minikube运行一段时间后,在资源占用不高的情况下docker无端退出,屡试不爽
**失败的命令的完整输出**：<details>

##### kubectl logs wordpress-65cf7dd448-qn26h
`unable to retrieve container logs for docker://a3c4149b2e0f62dfcfff74dbc6376033d05fdd329d366716d79e692c4`
</details>

**`minikube logs`命令的输出**： <details>
==> Docker <==
-- Logs begin at Sun 2019-10-27 09:01:48 UTC, end at Sun 2019-10-27 15:54:58 UTC. --
Oct 27 11:24:21 minikube dockerd[2354]: sync.runtime_notifyListWait(0xc001ded150, 0x0)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/runtime/sema.go:510 +0xef
Oct 27 11:24:21 minikube dockerd[2354]: sync.(*Cond).Wait(0xc001ded140)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/sync/cond.go:56 +0x94
Oct 27 11:24:21 minikube dockerd[2354]: github.com/docker/docker/pkg/ioutils.(*BytesPipe).Read(0xc001ded100, 0xc0018e0000, 0x800, 0x4000, 0x4000, 0x4000, 0x2)
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/pkg/ioutils/bytespipe.go:134 +0x27a
Oct 27 11:24:21 minikube dockerd[2354]: github.com/docker/docker/daemon/logger.(*Copier).copySrc(0xc001ded180, 0x1b09518, 0x6, 0x7fe1f07a2168, 0xc001ded100)
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/daemon/logger/copier.go:81 +0x95c
Oct 27 11:24:21 minikube dockerd[2354]: created by github.com/docker/docker/daemon/logger.(*Copier).Run
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/daemon/logger/copier.go:48 +0x111
Oct 27 11:24:21 minikube dockerd[2354]: goroutine 1888 [IO wait, 140 minutes]:
Oct 27 11:24:21 minikube dockerd[2354]: internal/poll.runtime_pollWait(0x7fe1ec6e86f8, 0x72, 0xc000bb3c48)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/runtime/netpoll.go:173 +0x68
Oct 27 11:24:21 minikube dockerd[2354]: internal/poll.(*pollDesc).wait(0xc000ce6e58, 0x72, 0xffffffffffffff01, 0x28fe8a0, 0x3a2cc50)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9c
Oct 27 11:24:21 minikube dockerd[2354]: internal/poll.(*pollDesc).waitRead(0xc000ce6e58, 0xc0014e8001, 0x8000, 0x8000)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f
Oct 27 11:24:21 minikube dockerd[2354]: internal/poll.(*FD).Read(0xc000ce6e40, 0xc0014e8000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/internal/poll/fd_unix.go:169 +0x17b
Oct 27 11:24:21 minikube dockerd[2354]: os.(*File).read(0xc0014423d0, 0xc0014e8000, 0x8000, 0x8000, 0x40da6d, 0xc0014e8000, 0xc000bb3d50)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/os/file_unix.go:249 +0x50
Oct 27 11:24:21 minikube dockerd[2354]: os.(*File).Read(0xc0014423d0, 0xc0014e8000, 0x8000, 0x8000, 0xc0009a6000, 0x2606760, 0x261d760)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/os/file.go:108 +0x6b
Oct 27 11:24:21 minikube dockerd[2354]: github.com/docker/docker/vendor/github.com/containerd/fifo.(*fifo).Read(0xc000ce6a20, 0xc0014e8000, 0x8000, 0x8000, 0x0, 0x8000, 0x8000)
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/vendor/github.com/containerd/fifo/fifo.go:159 +0x17d
Oct 27 11:24:21 minikube dockerd[2354]: io.copyBuffer(0x28f7e80, 0xc001be6b20, 0x7fe1f07a2188, 0xc000ce6a20, 0xc0014e8000, 0x8000, 0x8000, 0xc0007bef40, 0x24be360, 0xc001c05960)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/io/io.go:402 +0x127
Oct 27 11:24:21 minikube dockerd[2354]: io.CopyBuffer(0x28f7e80, 0xc001be6b20, 0x7fe1f07a2188, 0xc000ce6a20, 0xc0014e8000, 0x8000, 0x8000, 0xc000bb3f40, 0x441d01, 0xc000c5ef60)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/io/io.go:375 +0x84
Oct 27 11:24:21 minikube dockerd[2354]: github.com/docker/docker/pkg/pools.Copy(0x28f7e80, 0xc001be6b20, 0x7fe1f07a2188, 0xc000ce6a20, 0xc000ce6a20, 0x1, 0x0)
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/pkg/pools/pools.go:81 +0xa6
Oct 27 11:24:21 minikube dockerd[2354]: github.com/docker/docker/container/stream.(*Config).CopyToPipe.func1.1(0x28f7e80, 0xc001be6b20, 0x7fe1f07a2120, 0xc000ce6a20, 0xc0001bb440)
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/container/stream/streams.go:121 +0x73
Oct 27 11:24:21 minikube dockerd[2354]: created by github.com/docker/docker/container/stream.(*Config).CopyToPipe.func1
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/container/stream/streams.go:120 +0x86
Oct 27 11:24:21 minikube dockerd[2354]: goroutine 1889 [IO wait, 140 minutes]:
Oct 27 11:24:21 minikube dockerd[2354]: internal/poll.runtime_pollWait(0x7fe1ec6e69a0, 0x72, 0xc0007eb448)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/runtime/netpoll.go:173 +0x68
Oct 27 11:24:21 minikube dockerd[2354]: internal/poll.(*pollDesc).wait(0xc001b16198, 0x72, 0xffffffffffffff01, 0x28fe8a0, 0x3a2cc50)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9c
Oct 27 11:24:21 minikube dockerd[2354]: internal/poll.(*pollDesc).waitRead(0xc001b16198, 0xc0021e0001, 0x8000, 0x8000)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3f
Oct 27 11:24:21 minikube dockerd[2354]: internal/poll.(*FD).Read(0xc001b16180, 0xc0021e0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/internal/poll/fd_unix.go:169 +0x17b
Oct 27 11:24:21 minikube dockerd[2354]: os.(*File).read(0xc001824d88, 0xc0021e0000, 0x8000, 0x8000, 0x4595a0, 0x7fe1f5379000, 0xc0007eb550)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/os/file_unix.go:249 +0x50
Oct 27 11:24:21 minikube dockerd[2354]: os.(*File).Read(0xc001824d88, 0xc0021e0000, 0x8000, 0x8000, 0xc0009a6000, 0x2606760, 0x261d760)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/os/file.go:108 +0x6b
Oct 27 11:24:21 minikube dockerd[2354]: github.com/docker/docker/vendor/github.com/containerd/fifo.(*fifo).Read(0xc000ce6ba0, 0xc0021e0000, 0x8000, 0x8000, 0x0, 0x8000, 0x8000)
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/vendor/github.com/containerd/fifo/fifo.go:159 +0x17d
Oct 27 11:24:21 minikube dockerd[2354]: io.copyBuffer(0x28f7e80, 0xc001be6b00, 0x7fe1f07a2188, 0xc000ce6ba0, 0xc0021e0000, 0x8000, 0x8000, 0xc0007bef40, 0x24be360, 0xc001c05980)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/io/io.go:402 +0x127
Oct 27 11:24:21 minikube dockerd[2354]: io.CopyBuffer(0x28f7e80, 0xc001be6b00, 0x7fe1f07a2188, 0xc000ce6ba0, 0xc0021e0000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
Oct 27 11:24:21 minikube dockerd[2354]:         /usr/local/go/src/io/io.go:375 +0x84
Oct 27 11:24:21 minikube dockerd[2354]: github.com/docker/docker/pkg/pools.Copy(0x28f7e80, 0xc001be6b00, 0x7fe1f07a2188, 0xc000ce6ba0, 0xc000ce6ba0, 0x0, 0x45e551)
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/pkg/pools/pools.go:81 +0xa6
Oct 27 11:24:21 minikube dockerd[2354]: github.com/docker/docker/container/stream.(*Config).CopyToPipe.func1.1(0x28f7e80, 0xc001be6b00, 0x7fe1f07a2120, 0xc000ce6ba0, 0xc0001bb440)
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/container/stream/streams.go:121 +0x73
Oct 27 11:24:21 minikube dockerd[2354]: created by github.com/docker/docker/container/stream.(*Config).CopyToPipe.func1
Oct 27 11:24:21 minikube dockerd[2354]:         /go/src/github.com/docker/docker/container/stream/streams.go:120 +0x86

==> container status <==

==> dmesg <==
[  +5.005804] hpet1: lost 318 rtc interrupts
[Oct27 15:50] hpet1: lost 318 rtc interrupts
[  +5.003500] hpet1: lost 318 rtc interrupts
[  +5.005521] hpet1: lost 319 rtc interrupts
[  +5.005325] hpet1: lost 318 rtc interrupts
[  +5.002478] hpet1: lost 318 rtc interrupts
[  +5.007625] hpet1: lost 319 rtc interrupts
[  +5.006250] hpet1: lost 318 rtc interrupts
[  +5.002277] hpet1: lost 318 rtc interrupts
[  +5.001545] hpet1: lost 318 rtc interrupts
[  +5.003582] hpet1: lost 319 rtc interrupts
[  +5.005189] hpet1: lost 318 rtc interrupts
[  +4.997989] hpet1: lost 318 rtc interrupts
[Oct27 15:51] hpet1: lost 318 rtc interrupts
[  +5.001048] hpet1: lost 318 rtc interrupts
[  +5.003786] hpet1: lost 318 rtc interrupts
[  +5.000335] hpet1: lost 318 rtc interrupts
[  +5.003729] hpet1: lost 319 rtc interrupts
[  +5.006086] hpet1: lost 318 rtc interrupts
[  +5.005420] hpet1: lost 318 rtc interrupts
[  +5.006324] hpet1: lost 319 rtc interrupts
[  +5.008157] hpet1: lost 318 rtc interrupts
[  +4.999430] hpet1: lost 318 rtc interrupts
[  +5.003602] hpet1: lost 318 rtc interrupts
[  +5.000867] hpet1: lost 318 rtc interrupts
[Oct27 15:52] hpet1: lost 319 rtc interrupts
[  +5.006399] hpet1: lost 318 rtc interrupts
[  +5.006236] hpet1: lost 318 rtc interrupts
[  +5.005472] hpet1: lost 319 rtc interrupts
[  +5.003787] hpet1: lost 318 rtc interrupts
[  +5.004802] hpet1: lost 318 rtc interrupts
[  +4.999739] hpet1: lost 319 rtc interrupts
[  +5.003213] hpet1: lost 318 rtc interrupts
[  +5.003153] hpet1: lost 318 rtc interrupts
[  +5.000660] hpet1: lost 318 rtc interrupts
[  +5.004749] hpet1: lost 319 rtc interrupts
[  +5.004979] hpet1: lost 318 rtc interrupts
[Oct27 15:53] hpet1: lost 318 rtc interrupts
[  +5.003292] hpet1: lost 318 rtc interrupts
[  +5.002186] hpet1: lost 318 rtc interrupts
[  +5.003619] hpet1: lost 319 rtc interrupts
[  +5.003809] hpet1: lost 318 rtc interrupts
[  +5.005789] hpet1: lost 318 rtc interrupts
[  +5.001971] hpet1: lost 318 rtc interrupts
[  +5.006518] hpet1: lost 319 rtc interrupts
[  +4.999522] hpet1: lost 317 rtc interrupts
[  +5.001954] hpet1: lost 319 rtc interrupts
[  +5.002889] hpet1: lost 318 rtc interrupts
[  +5.003335] hpet1: lost 318 rtc interrupts
[Oct27 15:54] hpet1: lost 318 rtc interrupts
[  +5.001797] hpet1: lost 318 rtc interrupts
[  +5.005753] hpet1: lost 318 rtc interrupts
[  +5.005192] hpet1: lost 319 rtc interrupts
[  +5.004996] hpet1: lost 318 rtc interrupts
[  +5.005367] hpet1: lost 318 rtc interrupts
[  +5.004270] hpet1: lost 319 rtc interrupts
[  +5.006786] hpet1: lost 318 rtc interrupts
[  +5.000920] hpet1: lost 318 rtc interrupts
[  +5.006060] hpet1: lost 318 rtc interrupts
[  +5.003644] hpet1: lost 319 rtc interrupts

==> kernel <==
 15:54:59 up  6:54,  0 users,  load average: 0.29, 0.34, 0.52
Linux minikube 4.15.0 #1 SMP Wed Sep 18 07:44:58 PDT 2019 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2018.05.3"

==> kubelet <==
-- Logs begin at Sun 2019-10-27 09:01:48 UTC, end at Sun 2019-10-27 15:54:59 UTC. --
Oct 27 15:54:44 minikube kubelet[3138]: E1027 15:54:44.703308    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:44 minikube kubelet[3138]: E1027 15:54:44.705264    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:44 minikube kubelet[3138]: E1027 15:54:44.705365    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:45 minikube kubelet[3138]: E1027 15:54:45.707202    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:45 minikube kubelet[3138]: E1027 15:54:45.707350    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:45 minikube kubelet[3138]: E1027 15:54:45.707372    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:46 minikube kubelet[3138]: E1027 15:54:46.711190    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:46 minikube kubelet[3138]: E1027 15:54:46.711441    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:46 minikube kubelet[3138]: E1027 15:54:46.711490    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:46 minikube kubelet[3138]: I1027 15:54:46.840897    3138 kubelet.go:1839] skipping pod synchronization - [container runtime is down, PLEG is not healthy: pleg was last seen active 4h30m25.968206s ago; threshold is 3m0s, Container runtime not ready: RuntimeReady=false reason:DockerDaemonNotReady message:docker: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
Oct 27 15:54:47 minikube kubelet[3138]: E1027 15:54:47.514461    3138 remote_runtime.go:277] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:47 minikube kubelet[3138]: E1027 15:54:47.514668    3138 kuberuntime_container.go:340] getKubeletContainers failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:47 minikube kubelet[3138]: E1027 15:54:47.516335    3138 remote_runtime.go:277] ListContainers with filter &ContainerFilter{Id:,State:nil,PodSandboxId:,LabelSelector:map[string]string{},} from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:47 minikube kubelet[3138]: E1027 15:54:47.516438    3138 kuberuntime_container.go:340] getKubeletContainers failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:47 minikube kubelet[3138]: E1027 15:54:47.517144    3138 kubelet.go:1274] Container garbage collection failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:47 minikube kubelet[3138]: E1027 15:54:47.713817    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:47 minikube kubelet[3138]: E1027 15:54:47.714876    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:47 minikube kubelet[3138]: E1027 15:54:47.715116    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:48 minikube kubelet[3138]: E1027 15:54:48.719011    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:48 minikube kubelet[3138]: E1027 15:54:48.719142    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:48 minikube kubelet[3138]: E1027 15:54:48.719167    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.319367    3138 remote_image.go:71] ListImages with filter nil from image service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.319565    3138 kuberuntime_image.go:134] ListImages failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.319615    3138 eviction_manager.go:246] eviction manager: failed to get summary stats: failed to get imageFs stats: failed to get image stats: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.416118    3138 kubelet.go:2198] Container runtime not ready: RuntimeReady=false reason:DockerDaemonNotReady message:docker: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.725043    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.725206    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.725239    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.827811    3138 remote_runtime.go:81] Version from runtime service failed: rpc error: code = Unknown desc = failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:49 minikube kubelet[3138]: E1027 15:54:49.827896    3138 kuberuntime_manager.go:266] Get remote runtime version failed: rpc error: code = Unknown desc = failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:50 minikube kubelet[3138]: E1027 15:54:50.727811    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:50 minikube kubelet[3138]: E1027 15:54:50.728073    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:50 minikube kubelet[3138]: E1027 15:54:50.728112    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:51 minikube kubelet[3138]: E1027 15:54:51.731239    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:51 minikube kubelet[3138]: E1027 15:54:51.731373    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:51 minikube kubelet[3138]: E1027 15:54:51.731398    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:51 minikube kubelet[3138]: I1027 15:54:51.841270    3138 kubelet.go:1839] skipping pod synchronization - [container runtime is down, PLEG is not healthy: pleg was last seen active 4h30m30.968589769s ago; threshold is 3m0s, Container runtime not ready: RuntimeReady=false reason:DockerDaemonNotReady message:docker: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
Oct 27 15:54:52 minikube kubelet[3138]: E1027 15:54:52.733875    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:52 minikube kubelet[3138]: E1027 15:54:52.733964    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:52 minikube kubelet[3138]: E1027 15:54:52.733985    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:53 minikube kubelet[3138]: E1027 15:54:53.739041    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:53 minikube kubelet[3138]: E1027 15:54:53.739153    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:53 minikube kubelet[3138]: E1027 15:54:53.739175    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:54 minikube kubelet[3138]: E1027 15:54:54.417910    3138 kubelet.go:2198] Container runtime not ready: RuntimeReady=false reason:DockerDaemonNotReady message:docker: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:54 minikube kubelet[3138]: E1027 15:54:54.744595    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:54 minikube kubelet[3138]: E1027 15:54:54.745301    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:54 minikube kubelet[3138]: E1027 15:54:54.745415    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:55 minikube kubelet[3138]: E1027 15:54:55.748157    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:55 minikube kubelet[3138]: E1027 15:54:55.748355    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:55 minikube kubelet[3138]: E1027 15:54:55.748392    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:56 minikube kubelet[3138]: E1027 15:54:56.750263    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:56 minikube kubelet[3138]: E1027 15:54:56.752400    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:56 minikube kubelet[3138]: E1027 15:54:56.752573    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:56 minikube kubelet[3138]: I1027 15:54:56.841779    3138 kubelet.go:1839] skipping pod synchronization - [container runtime is down, PLEG is not healthy: pleg was last seen active 4h30m35.969100928s ago; threshold is 3m0s, Container runtime not ready: RuntimeReady=false reason:DockerDaemonNotReady message:docker: failed to get docker version: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?]
Oct 27 15:54:57 minikube kubelet[3138]: E1027 15:54:57.756186    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:57 minikube kubelet[3138]: E1027 15:54:57.756291    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:57 minikube kubelet[3138]: E1027 15:54:57.756313    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:58 minikube kubelet[3138]: E1027 15:54:58.759625    3138 remote_runtime.go:182] ListPodSandbox with filter nil from runtime service failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:58 minikube kubelet[3138]: E1027 15:54:58.759786    3138 kuberuntime_sandbox.go:210] ListPodSandbox failed: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Oct 27 15:54:58 minikube kubelet[3138]: E1027 15:54:58.759818    3138 generic.go:205] GenericPLEG: Unable to retrieve pods: rpc error: code = Unknown desc = Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

</details>

**使用的操作系统版本**：
`lsb_release -a`
`No LSB modules are available.
Distributor ID:	Deepin
Description:	Deepin 15.11
Release:	15.11
Codename:	stable
`
`uname -a`
`Linux lbc-PC 5.2.2-19.07.22.amdgpu.ubuntu #1 SMP Mon Jul 22 23:27:46 CEST 2019 x86_64 GNU/Linux
`

**Comment by medyagh** [comment]
@lubocheng  what driver do you use ? do you mind sharing the full miikube start args?

**Comment by medyagh** [comment]
@lubocheng any chance that it is because you need to pass the name space for the container ?

```kubectl logs my-pod  -n my-namespce```

?

**Comment by lubocheng** [comment]
> @lubocheng any chance that it is because you need to pass the name space for the container ?
> 
> `kubectl logs my-pod -n my-namespce`
> 
> ?

1. if you use minikube without namespace then default namespace is set, so this is not the cause 
2. by the way, the last few days i didn't find this error any more, and no idea why 😱

**Comment by medyagh** [comment]
@lubocheng if you dont mind I will close this issue, please feel free to re-open if you can re-produce the error again .
