### ISSUE TITLE
Add documentation for configuring AWS Elastic Container Registry

### ISSUE THREAD

**Issue by peteryhwong** [kubernetes/minikube#5753]
**The exact command to reproduce the issue**:

```
minikube start
minikube addons configure registry-creds
minikube addons enable registry-creds
```
**The full output of the command that failed**:<details>

😄  minikube v1.5.0 on Darwin 10.15
✨  Automatically selected the 'hyperkit' driver (alternates: [virtualbox])
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.16.2 on Docker 18.09.9 ...
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver proxy etcd scheduler controller dns
🏄  Done! kubectl is now configured to use "minikube"

Do you want to enable AWS Elastic Container Registry? [y/n]: y
-- Enter AWS Access Key ID: my-access-key
-- Enter AWS Secret Access Key: my-secret-key
-- (Optional) Enter AWS Session Token:
-- Enter AWS Region: ap-southeast-1
-- Enter 12 digit AWS Account ID (Comma separated list): my-account-id
-- (Optional) Enter ARN of AWS role to assume:

Do you want to enable Google Container Registry? [y/n]: n

Do you want to enable Docker Registry? [y/n]: n
❌  ERROR creating `registry-creds-ecr` secret: Temporary Error: secrets "registry-creds-ecr" not found
❌  ERROR creating `registry-creds-gcr` secret: Temporary Error: secrets "registry-creds-gcr" not found
⚠️  ERROR creating `registry-creds-dpr` secret
✅  registry-creds was successfully configured
✅  registry-creds was successfully enabled

</details>

**The output of the `minikube logs` command**:

No logs output due to the command `minikube addons configure registry-creds`
Following are the output due to the command `minikube addons enable registry-creds`

```
Oct 28 04:05:00 minikube kubelet[2947]: I1028 04:05:00.411350    2947 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-wrmh7" (UniqueName: "kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-default-token-wrmh7") pod "registry-creds-69f86f67f7-5zxnr" (UID: "23240816-32bf-4532-946e-0e8a4fe2567e")
Oct 28 04:05:00 minikube kubelet[2947]: I1028 04:05:00.413010    2947 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "gcr-creds" (UniqueName: "kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds") pod "registry-creds-69f86f67f7-5zxnr" (UID: "23240816-32bf-4532-946e-0e8a4fe2567e")
Oct 28 04:05:00 minikube kubelet[2947]: E1028 04:05:00.513737    2947 secret.go:198] Couldn't get secret kube-system/registry-creds-gcr: secret "registry-creds-gcr" not found
Oct 28 04:05:00 minikube kubelet[2947]: E1028 04:05:00.517650    2947 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\" (\"23240816-32bf-4532-946e-0e8a4fe2567e\")" failed. No retries permitted until 2019-10-28 04:05:01.017604162 +0000 UTC m=+1099.455026157 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"gcr-creds\" (UniqueName: \"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\") pod \"registry-creds-69f86f67f7-5zxnr\" (UID: \"23240816-32bf-4532-946e-0e8a4fe2567e\") : secret \"registry-creds-gcr\" not found"
Oct 28 04:05:01 minikube kubelet[2947]: E1028 04:05:01.117915    2947 secret.go:198] Couldn't get secret kube-system/registry-creds-gcr: secret "registry-creds-gcr" not found
Oct 28 04:05:01 minikube kubelet[2947]: E1028 04:05:01.118015    2947 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\" (\"23240816-32bf-4532-946e-0e8a4fe2567e\")" failed. No retries permitted until 2019-10-28 04:05:02.117992994 +0000 UTC m=+1100.555414905 (durationBeforeRetry 1s). Error: "MountVolume.SetUp failed for volume \"gcr-creds\" (UniqueName: \"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\") pod \"registry-creds-69f86f67f7-5zxnr\" (UID: \"23240816-32bf-4532-946e-0e8a4fe2567e\") : secret \"registry-creds-gcr\" not found"
Oct 28 04:05:02 minikube kubelet[2947]: E1028 04:05:02.127740    2947 secret.go:198] Couldn't get secret kube-system/registry-creds-gcr: secret "registry-creds-gcr" not found
Oct 28 04:05:02 minikube kubelet[2947]: E1028 04:05:02.127938    2947 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\" (\"23240816-32bf-4532-946e-0e8a4fe2567e\")" failed. No retries permitted until 2019-10-28 04:05:04.127903919 +0000 UTC m=+1102.565325851 (durationBeforeRetry 2s). Error: "MountVolume.SetUp failed for volume \"gcr-creds\" (UniqueName: \"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\") pod \"registry-creds-69f86f67f7-5zxnr\" (UID: \"23240816-32bf-4532-946e-0e8a4fe2567e\") : secret \"registry-creds-gcr\" not found"
Oct 28 04:05:04 minikube kubelet[2947]: E1028 04:05:04.148766    2947 secret.go:198] Couldn't get secret kube-system/registry-creds-gcr: secret "registry-creds-gcr" not found
Oct 28 04:05:04 minikube kubelet[2947]: E1028 04:05:04.149954    2947 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\" (\"23240816-32bf-4532-946e-0e8a4fe2567e\")" failed. No retries permitted until 2019-10-28 04:05:08.149925491 +0000 UTC m=+1106.587347430 (durationBeforeRetry 4s). Error: "MountVolume.SetUp failed for volume \"gcr-creds\" (UniqueName: \"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\") pod \"registry-creds-69f86f67f7-5zxnr\" (UID: \"23240816-32bf-4532-946e-0e8a4fe2567e\") : secret \"registry-creds-gcr\" not found"
Oct 28 04:05:08 minikube kubelet[2947]: E1028 04:05:08.178367    2947 secret.go:198] Couldn't get secret kube-system/registry-creds-gcr: secret "registry-creds-gcr" not found
Oct 28 04:05:08 minikube kubelet[2947]: E1028 04:05:08.179466    2947 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\" (\"23240816-32bf-4532-946e-0e8a4fe2567e\")" failed. No retries permitted until 2019-10-28 04:05:16.17943591 +0000 UTC m=+1114.616857824 (durationBeforeRetry 8s). Error: "MountVolume.SetUp failed for volume \"gcr-creds\" (UniqueName: \"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\") pod \"registry-creds-69f86f67f7-5zxnr\" (UID: \"23240816-32bf-4532-946e-0e8a4fe2567e\") : secret \"registry-creds-gcr\" not found"
Oct 28 04:05:16 minikube kubelet[2947]: E1028 04:05:16.244690    2947 secret.go:198] Couldn't get secret kube-system/registry-creds-gcr: secret "registry-creds-gcr" not found
Oct 28 04:05:16 minikube kubelet[2947]: E1028 04:05:16.245514    2947 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\" (\"23240816-32bf-4532-946e-0e8a4fe2567e\")" failed. No retries permitted until 2019-10-28 04:05:32.245480191 +0000 UTC m=+1130.682902111 (durationBeforeRetry 16s). Error: "MountVolume.SetUp failed for volume \"gcr-creds\" (UniqueName: \"kubernetes.io/secret/23240816-32bf-4532-946e-0e8a4fe2567e-gcr-creds\") pod \"registry-creds-69f86f67f7-5zxnr\" (UID: \"23240816-32bf-4532-946e-0e8a4fe2567e\") : secret \"registry-creds-gcr\" not found"
```

**The operating system version**:

macOS Catalina 10.15
minikube version: v1.5.0
commit: d1151d93385a70c5a03775e166e94067791fe2d9

**Comment by mmonbr** [comment]
@peteryhwong did you manage to fix this? I'm getting the same error

**Comment by paul-theorem** [comment]
Same issue, which is a hard blocker.  This is what I see:

Do you want to enable Docker Registry? [y/n]: n
❌  ERROR creating `registry-creds-ecr` secret: Temporary Error: secrets "registry-creds-ecr" not found
❌  ERROR creating `registry-creds-gcr` secret: Temporary Error: secrets "registry-creds-gcr" not found
⚠️  ERROR creating `registry-creds-dpr` secret
✅  registry-creds was successfully configured

The other issue is that it appears to fail to properly configure, then states "successfully configured."

I was getting a different error w/ registry creds on 1.4.0 - in the logs of the registry-creds pod.  
ERROR: logging before flag.Parse: E1101 15:56:39.393718       1 reflector.go:199] github.com/upmc-enterprises/registry-creds/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:kube-system:default" cannot list resource "namespaces" in API group "" at the cluster scope

That error is unrelated, but it is what i'm trying to fix.  I guess i'm going to try to blow away .minikube - which is a pain in the ass.  Will advise if that solves the issue.

**Comment by paul-theorem** [comment]
Actually - i was able to fix the issue by creating the secrets by hand, and then re-running configure. It appears to be a small defect in that configure expects to overwrite rather than create. 

Create empty secrets, then re-configure:

$ kubectl -n kube-system create secret generic registry-creds-ecr
secret/registry-creds-ecr created
$ kubectl -n kube-system create secret generic registry-creds-gcr
secret/registry-creds-gcr created
$ kubectl -n kube-system create secret generic registry-creds-dpr
secret/registry-creds-dpr created

...

Do you want to enable AWS Elastic Container Registry? [y/n]: y
-- Enter AWS Access Key ID: xxxxxxxxxxxxxxx
-- Enter AWS Secret Access Key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
-- (Optional) Enter AWS Session Token: 
-- Enter AWS Region: us-west-1
-- Enter 12 digit AWS Account ID (Comma separated list): xxxxxxxxxxxx
-- (Optional) Enter ARN of AWS role to assume: 

Do you want to enable Google Container Registry? [y/n]: n

Do you want to enable Docker Registry? [y/n]: n
✅  registry-creds was successfully configured

**Comment by medyagh** [comment]
@paul-theorem 
Thank you so much for telling us about this work arround !

this could be added to our website under the tutorials ! I would be happy to review any PR that adds this to our website.


and @peteryhwong thank you for creating this issue I bet a lots of other people have the same question and you helped in making their lives easier !
