### ISSUE TITLE
virtualbox: io.Copy failed: EOF

### ISSUE THREAD

**Issue by DaneeLee** [kubernetes/minikube#5754]
**minikube start**：

**失败的命令的完整输出**：<details>
[root@localhost ~]# minikube start
* minikube v1.3.1 on Centos 7.6.1810
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
* Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing virtualbox VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
E1028 16:12:12.787883   19169 ssh_runner.go:198] io.Copy failed: EOF
E1028 16:12:12.787570   19169 ssh_runner.go:198] io.Copy failed: EOF
* 
X Failed to update cluster: downloading binaries: copying kubeadm: copy: wait: remote command exited without exit status or exit signal
* 
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
Centos 7，VirtualBox 5

**Comment by tstromberg** [comment]
您介意使用minikube v1.5.0，如果失败，则共享`minikube ssh dmesg`的输出？

我怀疑VM可能内存不足。

**Comment by medyagh** [comment]
@DaneeLee are you still having this issue ?

**Comment by tstromberg** [comment]
Please try upgrading to VirtualBox v6.1. Thank you!
