### ISSUE TITLE
none: Minikube - v1.5.0 cant start in ubuntu-18.04.3 LTS

### ISSUE THREAD

**Issue by navihr** [kubernetes/minikube#5756]
**sudo minikube start --vm-driver=none**:

**The full output of the command that failed**:minikube v1.5.0 on Ubuntu 18.04
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing none VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
💣  minikube is unable to connect to the VM: dial tcp 192.168.0.4:22: connect: connection refused

This is likely due to one of two reasons:

- VPN or firewall interference
- none network configuration issue

Suggested workarounds:

- Disable your local VPN or firewall software
- Configure your local VPN or firewall to allow access to 192.168.0.4
- Restart or reinstall none
- Use an alternative --vm-driver

**ubuntu-18.04.3 LTS**:

**Comment by navihr** [comment]
already my firewall is disabled.

**Comment by tstromberg** [comment]
Looks like an inverted if statement. I'll send a PR out to fix this.
