### ISSUE TITLE
k8s container DNS doesn't seem to DNS resolve localhost

### ISSUE THREAD

**Issue by jeremyje** [kubernetes/minikube#5769]
If I run a container with 2 processes where they talk to each other within the container they don't seem to be able to talk to each other if the client uses `tcp://localhost`.

**The exact command to reproduce the issue**:

I created a small repository for this, https://github.com/jeremyje/ffmpeg-k8s-dns-repro.

```bash
minikube start
kubectl apply -f https://raw.githubusercontent.com/jeremyje/ffmpeg-k8s-dns-repro/master/deploy.yaml
```
This will create a batch job that runs a bunch of pods with different client/server connection configurations.

**The full output of the command that failed**:<details>

```
[tcp @ 0x55555596bd00] Failed to resolve hostname localhost: Name or service not known
Failed to open progress URL "tcp://localhost:10000": Input/output error
Failed to set value 'tcp://localhost:10000' for option 'progress': Input/output error
Error parsing global options: Input/output error
2019/10/29 08:30:52 
ffmpeg has closed.
2019/10/29 08:30:52 cannot call ffmpeg exit status 1
```

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
 minikube v1.5.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362

**Comment by medyagh** [comment]
@jeremyje the containers that wanna talk to each other local host need to be in same pod, in your yaml file I don't see a pod !


in your repo the Kind for the containers are "Job"  and I believe you meant to use "Pod"

here is an example of Pod, I wonder if that helps ?
https://github.com/kubernetes/examples/blob/master/staging/podsecuritypolicy/rbac/pod.yaml

**Comment by jeremyje** [comment]
> @jeremyje the containers that wanna talk to each other local host need to be in same pod, in your yaml file I don't see a pod !
> 
> in your repo the Kind for the containers are "Job" and I believe you meant to use "Pod"
> 
> here is an example of Pod, I wonder if that helps ?
> https://github.com/kubernetes/examples/blob/master/staging/podsecuritypolicy/rbac/pod.yaml

The two processes that are talking to each other live in the same docker container. The go app opens a TCP port and then shells out to ffmpeg to talk to that port. 
https://github.com/jeremyje/ffmpeg-k8s-dns-repro/blob/master/main.go#L71

**Comment by medyagh** [comment]
Ah, any chance that you may need to expose the ports ?
 https://github.com/jeremyje/ffmpeg-k8s-dns-repro/blob/master/Dockerfile
