### ISSUE TITLE
add  assets.go-e to gitignore

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5770]
while working on PR and running integration tests I keep seeing this file modified and wants to be commited

``` pkg/minikube/assets/assets.go-e```

and I have to keep deleting it manually, we probably want to gitignore it, unless there is a reason ?

**Comment by afbjorklund** [comment]
@medyagh I think this file comes for my elite workaround for the fact that GNU sed and BSD sed are ever so slightly different... Ignore it
