### ISSUE TITLE
minikube status throws error

### ISSUE THREAD

**Issue by selvakumar1975** [kubernetes/minikube#5774]
Error getting bootstrapper
* Error: [SSH_TCP_FAILURE] getting kubeadm bootstrapper: command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp [fe80::215:5dff:fe72:8900]:22: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
* Suggestion: Your host is failing to route packets to the minikube VM. If you have VPN software, try turning it off or configuring it so that it does not re-route traffic to the VM IP. If not, check your VM environment routing options.
* Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/vpn/

Note : i am not connected to VPN.  

Please help.

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue what driver or start args ...
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
@selvakumar1975 are you still having the issue ?

**Comment by selvakumar1975** [comment]
Hi&nbsp;Thanks for asking. My system corrupted. I could not able to check it again. I am waiting for new system to install again.Regards,Selvakumar RFrom: Medya Ghazizadeh &lt;notifications@github.com&gt;Sent: Tue, 05 Nov 2019 04:17:08To: kubernetes/minikube &lt;minikube@noreply.github.com&gt;Cc: selvakumar1975 &lt;selva_rang@rediffmail.com&gt;, Mention &lt;mention@noreply.github.com&gt;Subject: Re: [kubernetes/minikube] minikube status throws error (#5774)&nbsp;@selvakumar1975 are you still having the issue ?
&mdash;You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by medyagh** [comment]
@selvakumar1975 no worries, please feel free to update this issue anytime you have more information.

**Comment by medyagh** [comment]
@selvakumar1975 if you don't mind I will close this issue. please reopen once you have more info

**Comment by tstromberg** [comment]
FYI - this sounds like #3963
