### ISSUE TITLE
discuss: change minikube wait.PollImmediate to exponential retry

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5781]
while reading minikube code, I noticed we poll for a pod to be on every 300 millseconds, up to 3 minutes, I believe this is gonna put a toll on the api server.

for example:
```
err := wait.PollImmediate(time.Millisecond*300, time.Minute*3, func() (bool, error) ...
```

I am curious what would be the difference, if we use an expontential retry instead ?

**Comment by tstromberg** [comment]
Before discussion, this should probably get data to make an informed decision on:

- What is the load impact
- What is the timing impact

Only then can we determine the trade-off.

**Comment by medyagh** [comment]
close this till I have an answer for those questions
