### ISSUE TITLE
Minikube delete shows garbage characters

### ISSUE THREAD

**Issue by tanmaymohan** [kubernetes/minikube#5785]
**The exact command to reproduce the issue**:

sudo minikube delete

**The full output of the command that failed**:<details>

🔄  Uninstalling Kubernetes v1.16.0 using kubeadm ...
🔥  Deleting "minikube" in none ...
💔  The "minikube" cluster has been deleted.

💣  update config
❌  Error: [NON_C_DRIVE] Error getting kubeconfig status: could not read config: Error decoding config from data: ELF>?"@@xop@8
                                               @/.@@@@@???@?@@@xx  @ @-/-/@/@o@o(Hj(Hj?????????h?N
???????@?@?????????P?tdt?t?t?llQ?tdR?td???????/lib64/ld-linux-x86-64.so.2GNUSGoI_YnXmdJEWIVqw29tDPO/YddiJL0gKXHBPKS2KPDW/d7347AHfNKHdEpuH4Xgp/TJsujzr3RDRyk_v7L3SwGNU?t?d????F??k?ՏN??%/?? ?(
                             C (??0?@	)?D
                                           $??2 r"̀?@/2679=?ABDFIJMNOQSUW\]^_abcd*0??ꌁ?5C0t????$??ȏʙ?-?=???ؓ??a??^?Դ???t?d?s??Hx???>	9?C?r>1??5j+QRk	C֬5???Q?f??-
   :?
     I???n??
            ??SK?܍?6??}?? 5k?|?qXs'W??|??3?K??+?oN??????Z?????2b??u??`)?Ҵ??vCE?? ;H???b?_??????Jr??<??5??j??1E????.??? ?{~Nq?xH????@U?B"YP9d?-o9f.o9?p/o5??8oN?1o6??9o0?4UZ 0oF6/o0?6o-(P.o:???`9o-OP1o)V?9o]`?B06o??.o9??0????Op6o4oF??8o? ?????2o6g08oPI :o+P6o??7oL?P2ov8??E^?.o:;?E?`G??.?????p3o?'@o??8oQH?1o???6o[?p0oW??"@+z@/o+??4o?M@3o%?`G?{?/oe??0o+?@5o?'3o$@4UP?X?libpthread.so.0nanosleeppthread_attr_getstacksizepthread_sigmaskpthread_cond_waitpthread_mutex_lock__errno_locationpthread_mutex_unlockpthread_detachpthread_attr_initpthread_attr_destroypthread_cond_broadcastlibc.so.6sigfillsetabortsigemptysetsigaddsetfputcstderrfwritesigismember__libc_start_mainvfprintf__libc_csu_fini_cgo_95ad17b43a57_Cfunc_cfmakeraw_cgo_7e1b3c2abc8d_C2func_getnameinfocrosscall_amd64x_cgo_mmap_cgo_3298b262a8f6_Cfunc_mygetpwuid_r_cgo_3298b262a8f6_Cfunc_mygetgrouplist_cgo_7e1b3c2abc8d_Cfunc_getnameinfox_cgo_setenv_cgo_topofstackfatalfx_cgo_unsetenv_cgo_3298b262a8f6_Cfunc_mygetpwnam_r_cgo_sys_thread_startx_cgo_inittls_edatax_cgo_notify_runtime_init_done_cgo_95ad17b43a57_C2func_tcgetattr_cgo_7e1b3c2abc8d_Cfunc_freeaddrinfox_cgo_threadentryx_cgo_set_context_functionx_cgo_munmap_cgo_release_context_cgo_3298b262a8f6_Cfunc__Cmalloc_cgo_7e1b3c2abc8d_Cfunc_getaddrinfo__data_start_cgo_95ad17b43a57_Cfunc_tcsetattrx_cgo_sigaction__gmon_start___cgo_7e1b3c2abc8d_C2func_getaddrinfo_cgo_panic_IO_stdin_used_cgo_3298b262a8f6_Cfunc_realloc__libc_csu_init_cgo_3298b262a8f6_Cfunc_mygetgrgid_r_cgo_wait_runtime_init_done_end_cgo_7e1b3c2abc8d_Cfunc_gai_strerror__bss_startx_cgo_init_cgo_3298b262a8f6_Cfunc_freecrosscall2x_cgo_sys_thread_create_cgo_3298b262a8f6_Cfunc_mygetgrnam_r_cgo_get_context_functionx_cgo_thread_start_cgo_3298b262a8f6_Cfunc_sysconf_cgo_95ad17b43a57_C2func_tcsetattr_cgo_try_pthread_create_cgo_yieldx_cgo_callers_cgo_95ad17b43a57_Cfunc_tcgetattrGLIBC_2.3.2GLIBC_2.2.50ri	ui	?ui	???????.?? ??(??0??8??@??H??P?X??	`??
h??
   p??
???????????????????????????Ƞ?Р?ؠ?????????????!??"??# ??$(??%0??&8??'@??(H??)P??*X??+`??,h??-H?H???H??t??H???5???%??@?%??h??????%??h??????%??h??????%??h?????%??h?????%??h?????%??h?????%??h?p????%???`????%??h	?P????%??h
?@????%??h
          ?0????%??h
?????%r?h?????%j?h??????%b?h??????%Z?h??????%R?h??????%J?h?????%B?h?????%:?h?????%2?h?????%*?h?p????%"?h?`????%?h?P????%?h?@????%
?h0????%?h? ????%?~?h?????%?~?h?????%?~?h??????%?~?h

</details>

**The output of the `minikube logs` command**:<details>

No logs found 

</details>

**The operating system version**:

Ubuntu 18.04.3 LTS on t2.medium EC2(AWS) - 2 core 4gb ram

**Comment by tstromberg** [comment]
I believe this was fixed in minikube v1.5.x. Do you mind upgrading to the latest release and checking?

**Comment by tstromberg** [comment]
Specifically, I suspect this may be a duplicate of #5513

**Comment by tanmaymohan** [comment]
Ah , yeah #5499 it is. 

Upgrade to v1.5.1 fixes it
