### ISSUE TITLE
FR: detect imposed systemd-resolve resolve.conf 

### ISSUE THREAD

**Issue by gattytto** [kubernetes/minikube#5808]
coredns crashes if /etc/resolv.conf is a symlink to systemd-resolve daemon and has "127.0.0.53" inside it.

it's already in the docs on the "loop plugin" troubleshooting section, if you get a loop check there's no symlink. So it'd be time saving to avoid having to use the -extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf flag in this situation and have minikube prompt or just pass the right resolv.conf

**Comment by medyagh** [comment]
@gattytto is there any way you could provide me commands to repeat and replicate it for myself?

**Comment by gattytto** [comment]
@medyagh create a vm or lxc container (with config to run Minikube) with Debian 10 or ubuntu,make sure systemd-resolve is present on the system and /etc/resolv.conf is a symlink to systemd resolve file and it contains a single loop entry (something like nameserver 127.0.1.53) then start Minikube, at the end coredns will crash with a dns loop

**Comment by medyagh** [comment]
@josedonizetti any idea on this ?

**Comment by tstromberg** [comment]
Is this repeatable with minikube v1.7.0?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by gattytto** [comment]
everything works as expected now

![image](https://user-images.githubusercontent.com/407397/76813324-5716dd80-67d6-11ea-854b-c262e2d3b872.png)
