### ISSUE TITLE
`docker ps` can't see minikube containers on macOS

### ISSUE THREAD

**Issue by pan3793** [kubernetes/minikube#5810]
I'm using minikube v1.5.2 (installed via `brew install minikube`) on Darwin 10.14.6, with docker 19.03.4 (installed via `brew cask install docker`).

After I run `minikube start`, everything seems good, the log shows 'hyperkit' driver was selected, and `minikube dashboard` works fun.

But, when I use `docker ps`, I can't see the container created by minikube, and my docker version  is 19.03.4, but I checked the `minikube start` log, there is a line `正在 Docker '18.09.9' 中准备 Kubernetes v1.16.2…`.

Does it means the minikube run in an isolated docker daemon? 
If yes, how can I access this docker daemon via `docker` command? 
Can I use the exist docker daemon rather create a new one?

**Comment by govargo** [comment]
@pan3793 

> Does it means the minikube run in an isolated docker daemon?

Yes. minikube start virtual machine(such like virtualbox, hyperkit, etc...).
And minikube build kubernetes container on its virtual machine.

If you want to confirm docker, you can do by following step.

1. ssh virtual machine by `minikube ssh`.
2. you can exec docker command in that virtual machine.

**Comment by govargo** [comment]
And you can choice your customized environment.

See, none driver link.
https://minikube.sigs.k8s.io/docs/reference/drivers/none/

But there are issue about none driver.

**Comment by pan3793** [comment]
@govargo Thanks for your clear explanation, it seems that I misunderstood the document before.
