### ISSUE TITLE
Minikube fails to detect VPN on virtualbox "host-only adapter we just created is not visible"

### ISSUE THREAD

**Issue by Linzhs** [kubernetes/minikube#5817]
Mac OS 10.14.4 (18E226)

VirtualBox 6.0.14 r133895

start minikube

~  minikube start
⚠️  minikube 1.5.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v/1.5.2
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'
😄  minikube v1.3.1 on Darwin 10.14.4
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
E1102 19:49:36.417471   26432 start.go:723] StartHost: start: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

💣  Unable to start VM
❌  Error: [VBOX_HOST_ADAPTER] start: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
💡  Suggestion: Reboot to complete VirtualBox installation, and verify that VirtualBox is not blocked by your system
📘  Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3614
    ▪ https://github.com/kubernetes/minikube/issues/4222

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/

**Comment by medyagh** [comment]
@Linzhs I wonder if you are using a vpn or corp network ?


Additionally, it seems like our Advice is out dated and we need a better solution message.

and my other question is, could you please try with hyperkit driver and check if you stlil have the same problem if you use hyperkit instead of virtualbox ?
here are steps to install hyperkit
https://minikube.sigs.k8s.io/docs/start/macos/

**Comment by dmitrytokarev** [comment]
Turning off VPN and reboot fixed this issue for me.
```
macOS Version 10.14.6 (18G1012)
VirtualBox Version v6.0.14
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
```

**Comment by medyagh** [comment]
@dmitrytokarev thanks for updating the issue, there are some work arrounds for making minikube work for VPN, it is per corp network. if you find a way for your specific corp , please feel free to share with us.

we have a logic to detect the Corp network and VPNs to warn the user before they start the VM, I wonder why we missed this one ? could u share with us what kind of vpn or settings you are using?

@tstromberg the Validate Network seems to have missed to detect the VPN in this case. it seems like we could improve the error message and let the user know they are behind a VPN.

**Comment by tstromberg** [comment]
This error is raised before the network checks, as the network checks are  run against the VM, and in this case, StartHost failed because it had no network interface to attach to.

Would updating the suggestion to include disabling the VPN be sufficient in this case?

**Comment by medyagh** [comment]
Yes I 

> This error is raised before the network checks, as the network checks are run against the VM, and in this case, StartHost failed because it had no network interface to attach to.
> 
> Would updating the suggestion to include disabling the VPN be sufficient in this case?

Yes I think we could update the solution message. that would be sufficient.

**Comment by Linzhs** [comment]
@medyagh Hi, Thanks!

 I haven’t noticed that the VPN prompt was shown in the running error message. The error message I mentioned above was triggering when running  minikube start in the network environment (the company - Hong Kong route and personal VPN).

Now I try to use the Hyperkit carried by Docker Desktop installing under Mac as the vm driver (the following command) , and the minikube gets started successfully.

Thank you very much.

**Comment by medyagh** [comment]
@Linzhs  glad to see your issue was solved, btw you could also use our new docker driver

minikube start --vm-driver=docker
