### ISSUE TITLE
how to supply custom config map

### ISSUE THREAD

**Issue by frank-dspeed** [kubernetes/minikube#5820]
how can i supply a custom config map for the coreos dns service?

**Comment by medyagh** [comment]
@frank-dspeed do you mean in your own app or do you mean as you want to customize minikube's dns ?

**Comment by frank-dspeed** [comment]
@medyagh first of all when i would ask that for my own app then i would open a issue in my own app's repo :) i don't found the configMap used for coredns in this files i have no idea where it takes its settings from.

**Comment by frank-dspeed** [comment]
A little bit more background why its needed to modify it. There are Routers for example the in Germany often used fritz.box which blocks dns resolution of internal network ips via the internet. As a result nip.io don't dies what it should do as it simply gets no dns response :)

Then there is systemd i don't want to deepdive into the world of dns today but overall the most easy setup and fix for such setups to run minikube is simply configure minikube to use a other dns.

at present it has even a more wide bug in the form of automatic add extra extension /run/systemd/resolv.conf and when you add a other one manual it still wants to load the systemd one.

The only solution to configure minikube dns in the right way is to supply nameservers via configMap to coredns

**Comment by nanikjava** [comment]
@frank-dspeed will this steps help https://minikube.sigs.k8s.io/docs/tasks/sync/ ?

**Comment by frank-dspeed** [comment]
@nanikjava nope that will not help but i think its time to replace minikube with my own software stack so i am able to deploy kubernetes with more confidence local.

i am using vm-driver=none so sync is not my problem but i understand that my problem is out of scope for this software maybe.
