### ISSUE TITLE
Build CRI and CNI from source ?

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#5822]
Currently we are downloading binaries for crictl and for cni and cni-plugins:

https://github.com/kubernetes-sigs/cri-tools/releases/

https://github.com/containernetworking/cni/releases/
https://github.com/containernetworking/plugins/releases/

Should we build these packages locally, from the source code, instead ?

**Comment by priyawadhwa** [comment]
@afbjorklund is there an advantage to building these packages locally as opposed to downloading them?

**Comment by afbjorklund** [comment]
@priyawadhwa : the advantage is that we _know_ what goes into them, and are OK if upstream stops building them

**Comment by afbjorklund** [comment]
Just to prove a point, podman now requires CNI spec 0.4.0 and CNI 0.7.0 does not have binaries...
