### ISSUE TITLE
dashboard service is not running: Temporary Error: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found

### ISSUE THREAD

**Issue by asynclox** [kubernetes/minikube#5825]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by lmorse** [comment]
I am also seeing this issue.  I am on an MacBook Pro with Mojave Version 10.14.6.  
Here is my output ...
```
$ minikube start
😄  minikube v1.5.2 on Darwin 10.14.6
✨  Automatically selected the 'hyperkit' driver (alternates: [virtualbox])
💾  Downloading driver docker-machine-driver-hyperkit:
    > docker-machine-driver-hyperkit.sha256: 65 B / 65 B [---] 100.00% ? p/s 0s
    > docker-machine-driver-hyperkit: 10.79 MiB / 10.79 MiB  100.00% 2.78 MiB p
🔑  The 'hyperkit' driver requires elevated permissions. The following commands will be executed:
    $ sudo chown root:wheel /Users/lmorse/.minikube/bin/docker-machine-driver-hyperkit 
    $ sudo chmod u+s /Users/lmorse/.minikube/bin/docker-machine-driver-hyperkit 
Password:
💿  Downloading VM boot image ...
    > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [-] 100.00% 3.09 MiB p/s 47s
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
⚠️  VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
💾  Downloading kubeadm v1.16.2
💾  Downloading kubelet v1.16.2
🚜  Pulling images ...
❌  Unable to pull images, which may be OK: running cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml\"": Process exited with status 1
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver
🏄  Done! kubectl is now configured to use "minikube"
$ minikube dashboard
🔌  Enabling dashboard ...
🤔  Verifying dashboard health ...
💣  dashboard service is not running: Temporary Error: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found
```
I am attaching the output for `minikube logs`
[minikube_logs_output.txt](https://github.com/kubernetes/minikube/files/3933104/minikube_logs_output.txt)

**Comment by AldiT** [comment]
I have the same problem! 
`$ minikube start
* Verifying dashboard health ...
X dashboard service is not running: Temporary Error: Error getting service kubernetes-dashboard: services "kubernetes-dashboard" not found
`

On windows 10

**Comment by priyawadhwa** [comment]
Hey @asynclox @AldiT I recently fixed a bug with dashboard. Could you update to the latest release of minikube and let us know if that fixes it for you?

https://minikube.sigs.k8s.io/docs/start/

**Comment by AldiT** [comment]
Hi @priyawadhwa ,
I fixed it on my machine, I completely forgot about my comment here!
If it helps anyone else, my problem was: two different versions ambiguity (installed minikube from two different sources), and firewall network related problems, which are irrelevant for this thread. So as far as I am concerned, you may close this thread!
Thanks!

**Comment by priyawadhwa** [comment]
Hey @AldiT thank you! I'll go ahead and close this issue then, @asynclox if you continue to see this issue feel free to reopen this thread by including `/reopen` in your comment.
