### ISSUE TITLE
UI confusion: minikube iso version is different that minikube version

### ISSUE THREAD

**Issue by MKruger777** [kubernetes/minikube#5826]
It seems like the minikube iso versions echoed during "minikube start" are not matching the binary version downloaded (in this case v1.5.2).

After getting minikube with curl:
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v1.5.2/minikube-linux-amd64 \
  && chmod +x minikube

I ran "minikube start" which in turn then returned the following output:

😄  minikube v1.5.2 on Ubuntu 18.04
✨  Automatically selected the 'virtualbox' driver (alternates: [none])
💿  Downloading VM boot image ...
    > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [-] 100.00% 21.44 MiB p/s 7s
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...

Within the "Downloading VM boot image ..." step, the iso (well, the name at least) seems to refer to minikube-v1.5.1
Maybe this is expected? if so my apologies in advance :- )

Kind regards,
Morné

**Comment by butuzov** [comment]
Checkout releases https://github.com/kubernetes/minikube/releases

No iso found for 1.5.2 at all.

**Comment by afbjorklund** [comment]
The ISO is not always updated

**Comment by MKruger777** [comment]
Thanks, guys! Well, I guess then there is no need to panic.

**Comment by butuzov** [comment]
should this issue be closed then?

**Comment by medyagh** [comment]
I believe we could close this issue, however I acknowldge, for an end user it might be a bit weird to see a different version. however it doesn't seem to affect anything !

**Comment by medyagh** [comment]
I would be down to any PR that would make the UI experience a bit better without loosing debugging information

**Comment by afbjorklund** [comment]
We use to only do ISO updates for the major versions (1.0, 1.1, 1.2) and only do program updates for minor versions. But with 1.5.0 we had issues with systemd, so had to release a 1.5.1 ISO to fix them...

**Comment by tstromberg** [comment]
Closing this. I don't think there is any clear action going forward. We either hide the URL, or make it confusing :(
