### ISSUE TITLE
create documentation for vmware driver on Windows

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5830]
our site currently only has vmware docs for mac os: https://minikube.sigs.k8s.io/docs/start/macos/

we need to add documents to the site for vmware on windows.
https://minikube.sigs.k8s.io/docs/start/windows/

**Comment by KaenDagger** [comment]
I would like to take this. Please assign this to me

**Comment by KaenDagger** [comment]
I could do update for linux as well

**Comment by RA489** [comment]
@KaenDagger Any update on this?

**Comment by KaenDagger** [comment]
I removed my assignment from this issue.

**Comment by sharifelgamal** [comment]
Help is still wanted here. The new URL for vmare docs is https://minikube.sigs.k8s.io/docs/drivers/vmware/

/lifecycle frozen

**Comment by Aut0R3V** [comment]
I would like to work on this. 
/assign

**Comment by Aut0R3V** [comment]
@sharifelgamal I've added a pull request, please go through it and recommend any required changes.
