### ISSUE TITLE
File sync (scp) not working properly

### ISSUE THREAD

**Issue by nanikjava** [kubernetes/minikube#5835]
Tried the instruction to sync file from local machine to vm

> https://minikube.sigs.k8s.io/docs/tasks/sync/ 

**Test scenario**

Add new entry into resolv.conf inside `$HOME/.minikube/files/etc/resolv.conf `

```
nameserver 1.1.1.1
nameserver 8.8.8.8
```
After running `minikube start` the file /etc/resolv.conf inside the VM is not updated. Tested using kvm2 VM

Also tried adding a new file `$HOME/.minikube/files/etc/` but cannot see it being copied over.

**Comment by nanikjava** [comment]
From investigation scp is using `-t` flag where it should  be using `-r `

**Comment by medyagh** [comment]
thank for you digging in to this feature,

how about we write an integration test for this ? basicly create a file "helloworld.txt" and put in the minkube home files and expect it to be there?

**Comment by medyagh** [comment]
@nanikjava  do you mind sharing on which platofrm/driver and version you tried it ?

I tried it on mac os with hyperkit driver and it seems to be working

here is what I see:
```
medya@~/workspace/minikube (clean_cron) $ mkdir -p ~/.minikube/files/etc
medya@~/workspace/minikube (clean_cron) $ echo nameserver 8.8.8.8 > ~/.minikube/files/etc/helloword.txt
medya@~/workspace/minikube (clean_cron) $ minikube start

(minikube starting ...)
```

checking with minikube ssh 
```
$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ cat /etc/h
helloword.txt  hostname       hosts          
$ cat /etc/h
helloword.txt  hostname       hosts          
$ cat /etc/helloword.txt 
nameserver 8.8.8.8
```

**Comment by nanikjava** [comment]
@medyagh Used kvm2 for testing and when the the VM was running when doing the minikube start again.

Tested without the -r  option it did not copied the files and when the option is put in it copied the file perfectly.

**Comment by medyagh** [comment]
thanks for updating, I would be happy to review a PR if there be an integration test so we can verify this on all platforms 

I suggest adding a new test to the functional test, called file_sync
here https://github.com/kubernetes/minikube/blob/master/test/integration/functional_test.go

the test should compare the files in the hosts's minikube home files folder and inside minikube VM

**Comment by nanikjava** [comment]
Cool will do. Will work on the integration test.

**Comment by nanikjava** [comment]
PR for review https://github.com/kubernetes/minikube/pull/5865

**Comment by sharifelgamal** [comment]
@nanikjava is anything else needed to close this?

**Comment by nanikjava** [comment]
> @nanikjava is anything else needed to close this?

PR has been reviewed and merged. So it's all good to close it. Thanks

**Comment by sharifelgamal** [comment]
Thanks!
