### ISSUE TITLE
feature: minikube should not crash if service or namespace doesn't exist.

### ISSUE THREAD

**Issue by bjkowalski** [kubernetes/minikube#5836]
I am running minikube version v1.5.2.  

I discovered that if I specify an undefined "namespace" with the namespace option on the service command an error is reported but there is also a message that says "mini9kube crashed".

**The exact command to reproduce the issue**:
`minikube service newservice -n unknown --url`

**The full output of the command that failed**:<details>
$ minikube service newservice -n unknown --url

💣  Error opening service: Service newservice was not found in "unknown" namespace. You may select another namespace by using 'minikube service newservice -n <namespace>: Temporary Error: Error getting service newservice: services "newservice" not found

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
[minikube.log](https://github.com/kubernetes/minikube/files/3811276/minikube.log)

</details>

**The operating system version**:
Linux bj-XPS-13-9360 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by medyagh** [comment]
ah ! thanks for reporting it ! 

I see that we have a nicely worded error message however it is not acceptable that we Crash ! 
you are right !

we should exit without crashing with a nice message that the service doesnt exist.

this should be an easy fix, I would be happy to review any PR that fixes this !

**Comment by medyagh** [comment]
@rajula96reddy are you still working on it ?

**Comment by rajula96reddy** [comment]
@medyagh  Yeah! I am working on it and I am gonna finish this soon. Probably today or tomorrow. I am really sorry, I got stuck with some stuff and couldn't finish it earlier.
