### ISSUE TITLE
Expose etcd from localkube

### ISSUE THREAD

**Issue by tiaanl** [kubernetes/minikube#584]
I'm running a tool that manages parts of Kubernetes and it stores some data in etcd.  I've been using the same etcd the masters are using for convenience.

So i'd like to have access to the etcd running on the minikube vm, but the address is hard coded to `127.0.0.1:2379`.

I was thinking of adding a flag to localkube like `--etcd-address=0.0.0.0:2379`.  This of course would not be the only change as the address would come from minikube as well as other services should then also know the new address.

Is this even feasible or a good idea?

**Comment by dlorenc** [comment]
Hey,

Have you considered running a separate etcd instance inside the Kubernetes cluster? There's a doc here that might help:

https://github.com/coreos/etcd/tree/master/hack/kubernetes-deploy

**Comment by tiaanl** [comment]
@dlorenc This was the way I initially used it.  It works very well if you add persistent storage of course.  Other than my own, I can still think of reasons why exposing the internal etcd might be useful.

**Comment by jimmidyson** [comment]
Using the kubernetes etcd directly is discouraged. You might look at third party resources if you want to write to the same etcd but go through the API server. Otherwise, running separate etcd is probably the way to go.

**Comment by tiaanl** [comment]
@jimmidyson I've been thinking of using third party resources.  Does make sense not to share the etcd with kubernetes.  Although afaik CoreOS setup would install flannel and then use the same etcd as kubernetes for it's configs, so I "assumed" it would be ok.

On a side note, if you have a 5 node HA etcd cluster running in production for instance, would you still not share etcd?  Is it a bad idea because of performance or that third party apps might "corrupt" data?

**Comment by dlorenc** [comment]
@tiaanl I'm going to close this out for now, I don't think there's anything actionable on our side. Feel free to hop into slack if you have any more questions!

**Comment by skormos-lv** [comment]
@tiaanl Did you ever find a solution? It seems kind of strange that you can access the server in a proper K8s install, but not here. Considering there are several tools that are built on the assumption that the state of the cluster is available via ETCd, why the analogous functionality is not available in minikube makes it a complete non-starter for me.

**Comment by dlorenc** [comment]
etcd should be exposed inside the cluster. Could you try accessing it over http://localhost:2379?

This issue was about being able to modify that address to allow access from *outside* the cluster.

**Comment by skormos-lv** [comment]
@dlorenc Immensely appreciate your quick response, and apologize for the possibly naive questions, but where should I curl the address from? I've tried from inside a pod, but it's connection refused. I tried both localhost and 127.0.0.1. From inside the pod wouldn't make sense, since that would be the container deployed (however I tried it anyway).

**Comment by tiaanl** [comment]
@skormos-lv  I ended up running another instance of etcd as a pod in the cluster and exposing that one over nodeport.  You should be able to access the etcd directly if you run the curl from within a pod running inside the cluster.  So run something like a vanilla `ubuntu:16.04` image in the cluster, `kubectl exec -it <pod-id>` and then running your curl from there (After installing curl of course)

Exposing the internal etcd does make a lot of sense in a few cases (especially testing something), but I guess it would encourage bad practice.

**Comment by skormos-lv** [comment]
@tiaanl Thanks for the response. When you suggest I should be able to access etcd from a container, using what address? I tried `curl http://localhost:2379` which is a request to the local container, so I get "connection refused".

**Comment by dlorenc** [comment]
D'oh, I think you're right. You can curl etcd from the host VM (minikube ssh), but not inside a pod itself.

We can probably expose it similarly to how we used to expose DNS inside the cluster. We'd have to create an endpoint and a service mapping to the port on the VM itself.

**Comment by dlorenc** [comment]
Could you explain the use-case for connecting to the cluster's etcd instance directly, vs going through the API server?

**Comment by skormos-lv** [comment]
The application we have is reloaded via confd, which uses etcd as its data store.

**Comment by dlorenc** [comment]
Does confd need to use the same etcd cluster as kubernetes? Or can it use it's own? In general it's not recommended to store other data inside the same etcd cluster as kubernetes.

**Comment by skormos-lv** [comment]
confd on its own does not write to etcd, only reads, and relies on updates from etcd in order to properly update. So no data other than what's written by Kubernetes or Minikube is supposed to exist there anyway.

**Comment by Chrislevi** [comment]
Any news?

**Comment by mooperd** [comment]
+1 - easy access to the database would be very useful when developing various k8s stuff.
