### ISSUE TITLE
Filesystem mounts when --vm-driver=none

### ISSUE THREAD

**Issue by kgersen** [kubernetes/minikube#5843]
The `Driver mounts` section of the `Filesystem mounts` documentation (
https://minikube.sigs.k8s.io/docs/tasks/mount/#driver-mounts ) doesn't specify any information for the 'none' driver (aka when using the host Docker).

Are 9P mounts the only option or can we use native Docker host mounts ? if so the documentation needs to be updated. If not may be add an issue for to add native Docker host mounts ?

label:area/mount 
label:co/none-driver

**Comment by medyagh** [comment]
none driver doesn't have mount, and I believe you don't need to mount it to the host, since minikube is already running on the host.

**Comment by sharifelgamal** [comment]
That piece of documentation is specifically talking about mounting your filesystem into the guest VM, something does doesn't apply to the `none` driver. We don't support mounting into docker.
