### ISSUE TITLE
fix minikube service retry logic (takes 35s)

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5846]
`minikube service list` takes 0.138s  (less than a 1 second)
see :
```
$ time minikube service list
|----------------------|---------------------------|--------------|-----|
|      NAMESPACE       |           NAME            | TARGET PORT  | URL |
|----------------------|---------------------------|--------------|-----|
| default              | kubernetes                | No node port |
| kube-system          | kube-dns                  | No node port |
| kubernetes-dashboard | dashboard-metrics-scraper | No node port |
| kubernetes-dashboard | kubernetes-dashboard      | No node port |
|----------------------|---------------------------|--------------|-----|

real	0m0.164s
user	0m0.068s
sys	0m0.065s
```

but if you try to access a Not-existing service

```
time minikube service newservice -n unknown --url

real    0m35.885s
user    0m0.115s
sys     0m0.092s
```

it takes 35 seconds !

that is a flaw ! we could easily search for the list in list of services first and then if it exists go through the Retry logic.

I also noticed the `service` package needs a lot of clean up and refactor !

**Comment by nanikjava** [comment]
will take this one @medyagh

**Comment by medyagh** [comment]
@priyawadhwa could we have a step in minikube perf bot to measure service ?

**Comment by priyawadhwa** [comment]
@medyagh that should be possible, but I think might require some additional thought! I'm guessing we wouldn't need to measure service time for every PR, so we might want some way of telling the bot what to measure for each PR.

**Comment by tstromberg** [comment]
This now takes 0.17s.
