### ISSUE TITLE
'make' fails with "running gcc failed: exit status 1"  

### ISSUE THREAD

**Issue by budhrg** [kubernetes/minikube#585]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`):
master branch with commit `3b2fce49e245c1e661b19763c053d91a82b859ff`

**Environment**:
- **OS** (e.g. from /etc/os-release):   Fedora 24

**What happened**:
`make` command failed.

**What you expected to happen**:
`make` command should have exit properly and produced binary `minikube`.

**How to reproduce it** (as minimally and precisely as possible):
Perform `make` in above mentioned OS.

**Anything else do we need to know**:
My error logs:
```
➜  minikube git:(master) make
if [ ! -e /home/budhram/gowork/src/k8s.io/minikube/_gopath/src/k8s.io ]; then mkdir -p /home/budhram/gowork/src/k8s.io/minikube/_gopath/src/k8s.io && ln -s -f /home/budhram/gowork/src/k8s.io/minikube /home/budhram/gowork/src/k8s.io/minikube/_gopath/src/k8s.io; fi
CGO_ENABLED=1 go build -ldflags="-X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitCommit=b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitVersion=v1.3.5 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitTreeState=clean -X k8s.io/minikube/pkg/version.version=v0.9.0 -s -w -extldflags '-static'" -o ./out/localkube ./cmd/localkube
# _/home/budhram/gowork/src/k8s.io/minikube/cmd/localkube
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

Makefile:53: recipe for target 'out/localkube' failed
make: *** [out/localkube] Error 2
```

I had both "gcc", "gcc-c++" libraries
```
➜  minikube git:(master) rpm -qa gcc
gcc-6.1.1-3.fc24.x86_64
➜  minikube git:(master) rpm -qa gcc-c++
gcc-c++-6.1.1-3.fc24.x86_64
```

**Comment by dlorenc** [comment]
Hey, It looks like you're on a fedora system. Do the steps in this bug here help:
https://github.com/kubernetes/minikube/issues/236

**Comment by budhrg** [comment]
@dlorenc , I verified it and found that we need to have two packages installed for Fedora system as mentioned in https://github.com/kubernetes/minikube/issues/236.

In my case I need to install `glibc-static`.

```
dnf install @development-tools
dnf install glibc-static
```

Closing the issue now.
