### ISSUE TITLE
minikube ip * X Error getting IP: Host is not running

### ISSUE THREAD

**Issue by jkpeai** [kubernetes/minikube#5856]
**The exact command to reproduce the issue**:
C:\Users\Samba>
minikube update-context
*
X Error host driver ip status: getting IP: Host is not running
C:\Users\Samba>minikube ip
*
X Error getting IP: Host is not running
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\Users\Samba>

C:\Users\Samba>minikube logs
*
X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\Users\Samba>

C:\Users\Samba>minikube version
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631

C:\Users\Samba>

**Comment by medyagh** [comment]
@jkpeai is your minikube running ?can you share the output of minikube status ?

and also I noticed your minikube is outdated, do you mind giving it a try with the latest version ?

**Comment by medyagh** [comment]
@jkpeai  are you still having this issue ? do you mind sharing more info ?

**Comment by priyawadhwa** [comment]
Hey @jkpeai, hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
