### ISSUE TITLE
Add search to site: generate hugo site search index

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5863]
good first issue for someone with js, hugo skills.

currently we are using a web based search google search, https://minikube.sigs.k8s.io/
code here https://github.com/kubernetes/minikube/tree/master/site

 ideally would be great if we use a static search index. so as the user types in the search it shows the right page.
like if they search "China" should bring up all the md files with word china in it.
or if search gvisor, it should bring up all pages with word gvisor in them.

There are some libraries out there. but I have not studied them, here is an example: ( feel free to find your own lib that works)
- https://www.npmjs.com/package/hugo-search-index

Level 2 (maybe not for the good-first issue picker) :
- need to add a step to our build process so whenever the .MD files change a new site index should be generated . (on first iteration of this PR I would accept it if it generates the site index on each build )

**Comment by tstromberg** [comment]
What is the issue you are trying to solve?

**Comment by medyagh** [comment]
we already did this
