### ISSUE TITLE
driver's PreCreateCheck() is not used 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5867]
I added debugging statements, at appears no where in the code we are using them !

for hyperkit driver
```

// PreCreateCheck is called to enforce pre-creation steps
func (d *Driver) PreCreateCheck() error {
	fmt.Println("inside PreCreate hyperkit")
	return d.verifyRootPermissions()
}

```

for none driver
```
// PreCreateCheck checks for correct privileges and dependencies
func (d *Driver) PreCreateCheck() error {
	return d.runtime.Available()
}

```

**Comment by andylibrian** [comment]
Is it a good first issue? I am interested to contribute.

**Comment by afbjorklund** [comment]
Hmm, it looks to me that it _is_ being called ?

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/machine/client.go#L183

Most likely it went back to default, when removed.

```go
// PreCreateCheck is called to enforce pre-creation steps
func (d *BaseDriver) PreCreateCheck() error {
        return nil
}
```

**Comment by priyawadhwa** [comment]
As Anders pointed out, this code is being called now, so I'm going to close this issue
