### ISSUE TITLE
minikube crashed

### ISSUE THREAD

**Issue by saiMWEB** [kubernetes/minikube#5882]
**The exact command to reproduce the issue**:
minikube start --wait=false
**The full output of the command that failed**:<details>

 Problems detected in kube-addon-manager:
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp [::1]:8443: connect: connection refused
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp [::1]:8443: connect: connection refused
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: net/http: TLS handshake timeout

</details>

**The output of the `minikube logs` command**:<details>

 Problems detected in kube-addon-manager:
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp [::1]:8443: connect: connection refused
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp [::1]:8443: connect: connection refused
  - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: net/http: TLS handshake timeout</details>

**The operating system version**:
minikube v1.3.0 on Ubuntu 18.04

**Comment by tstromberg** [comment]
Do you mind upgrading to minikube v1.5.2 and sharing the complete output of `minikube start --wait=false`?

Thanks!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
