### ISSUE TITLE
minikube service: Error opening service: Service hello-world was not found

### ISSUE THREAD

**Issue by deepzymr** [kubernetes/minikube#5883]
**The exact command to reproduce the issue**:
minikube service hello-world --url

**The full output of the command that failed**:<details>

💣  Error opening service: Service hello-world was not found in "default" namespace. You may select another namespace by using 'minikube service hello-world -n <namespace>: Temporary Error: Error getting service hello-world: services "hello-world" not found

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
ubuntu 16.04 - xenial

**Comment by priyawadhwa** [comment]
Hey @deepzymr thanks for opening this bug. Could you confirm that the service is running by providing the output of:

- `kubectl get svc --all-namespaces`

**Comment by sharifelgamal** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it.

Thank you for opening the issue!

**Comment by Wang-Cankun** [comment]
I encountered a same issue in Windows; the reason is probably two Kubernetes have been started: one from ```minikube start``` in PowerShell and one from the Docker desk app. After I stopped the Kubernetes instance in Docker app settings and restart minikube in PowerShell, the issue gone.

**Comment by zky001** [comment]
> I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it.
> 
> Thank you for opening the issue!

I meet same error in another way

**Comment by bzdgn** [comment]
The same error, 

I'm using **Windows 10 Pro**, running **minikube** the currently latest version: **1.26.1**

Followed the steps;

minikube start
kubectl create deployment hello-node --image=registry.k8s.io/echoserver:1.4

Then I tried to create service;

```
>minikube service

X Exiting due to MK_USAGE: You must specify service name(s) or --all
```

Here is the output of dashboard;

![image](https://user-images.githubusercontent.com/1220904/190456670-e504aa5c-3c35-4bfb-8f43-11775b48b80c.png)

The node and the pod is visible on kubectl command and the namespaces;
```
C:\>kubectl get nodes
NAME       STATUS   ROLES           AGE   VERSION
minikube   Ready    control-plane   24m   v1.24.3

C:\>kubectl get pods
NAME                          READY   STATUS    RESTARTS   AGE
hello-node-7c7c59b7cb-4sjd9   1/1     Running   0          19m

C:\>kubectl get svc --all-namespaces
NAMESPACE              NAME                        TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
default                kubernetes                  ClusterIP   10.96.0.1        <none>        443/TCP                  25m
kube-system            kube-dns                    ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   25m
kubernetes-dashboard   dashboard-metrics-scraper   ClusterIP   10.106.165.228   <none>        8000/TCP                 24m
kubernetes-dashboard   kubernetes-dashboard        ClusterIP   10.110.124.118   <none>        80/TCP                   24m
```

Using default namespace not working;

```
>minikube service hello-node -n kubernetes

X Exiting due to SVC_NOT_FOUND: Service 'hello-node' was not found in 'kubernetes' namespace.
You may select another namespace by using 'minikube service hello-node -n <namespace>'. Or list out all the services using 'minikube service list'
```

Here is the list of service;

```
>minikube service list
|----------------------|---------------------------|--------------|-----|
|      NAMESPACE       |           NAME            | TARGET PORT  | URL |
|----------------------|---------------------------|--------------|-----|
| default              | kubernetes                | No node port |
| kube-system          | kube-dns                  | No node port |
| kubernetes-dashboard | dashboard-metrics-scraper | No node port |
| kubernetes-dashboard | kubernetes-dashboard      | No node port |
|----------------------|---------------------------|--------------|-----|
```

**Comment by bzdgn** [comment]
It's also possible to forget to expose the deployment if you get this error message;

`kubectl expose deployment hello-node --type=LoadBalancer --port=8080`

**Comment by riyas-tk** [comment]
Hi,

I am getting the same error while running `minikube service hello-node` following the minikube [doc](https://kubernetes.io/docs/tutorials/hello-minikube/)
