### ISSUE TITLE
Inconsistent behavior listing profiles in json when none exist

### ISSUE THREAD

**Issue by cheeseandcereal** [kubernetes/minikube#5898]
Using minikube version 1.5.2 tested on Linux and Windows 10 with the same behavior:

The command `minikube profile list -o json` provides inconsistent behavior whether or not the `$MINIKUBE_HOME/profiles` folder exists or not.

When `$MINIKUBE_HOME/profiles` does not exist, the command outputs: `{"error":{"Op":"open","Path":"/root/.minikube/profiles","Err":2}}` and minikube exits with status 1

When that folder does exist, the command outputs: `{"invalid":[],"valid":[]}` with exit status 0 (as expected).

This seems like undesirable behavior, especially because `minikube profile list` (without json output) is consistent in both scenarios, outputting the generic ```* No minikube profile was found. You can create one using `minikube start`.``` error message and exiting with status code 64 regardless of whether the `$MINIKUBE_HOME/profiles` folder exists or not

Example of full replication output in bash:
```
root@d3a5e2df82d8:/# minikube profile list
* No minikube profile was found. You can create one using `minikube start`.
root@d3a5e2df82d8:/# echo $?
64
root@d3a5e2df82d8:/# minikube profile list -o json
{"error":{"Op":"open","Path":"/root/.minikube/profiles","Err":2}}
root@d3a5e2df82d8:/# echo $?
1
root@d3a5e2df82d8:/# mkdir ~/.minikube/profiles
root@d3a5e2df82d8:/# minikube profile list
* No minikube profile was found. You can create one using `minikube start`.
root@d3a5e2df82d8:/# echo $?
64
root@d3a5e2df82d8:/# minikube profile list -o json
{"invalid":[],"valid":[]}
root@d3a5e2df82d8:/# echo $?
0
```

Minikube should probably ensure that the `$MINIKUBE_HOME/profiles` folder exists (and create it if missing) before the profile list operation in order to provide consistent, expected behavior.

**Comment by priyawadhwa** [comment]
Hey @cheeseandcereal thanks for opening this issue. Definitely agree the behavior is a bit confusing and could be improved.

WDYT of outputting:

`* No minikube profile was found. You can create one using 'minikube start'.` to STDOUT
`{"invalid":[],"valid":[]}` for `-o json`
and exit code 0

for both cases (when `$MINIKUBE_HOME/profiles` exists and when it doesn't`)?

If you, or anyone else would be interested in submitting a PR for this, that would be great! You can assign yourself to this issue by commenting `/assign`.
