### ISSUE TITLE
vbox: (unknown start error)

### ISSUE THREAD

**Issue by hilner** [kubernetes/minikube#5903]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

</details>

**A saída do comando `minikube logs`**:<details>

</details>

**A versão do sistema operacional usado**:

SATA-ImageUUID-0-0"="5c284f9f-887d-4a92-8cea-4090107eded3"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/home/suporte/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="fe93fa74-ed15-4c6c-88ea-f834c5964e59"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
bridgeadapter1="enp5s0f0"
macaddress1="080027FD3F42"
cableconnected1="on"
nic1="bridged"
nictype1="virtio"
nicspeed1="0"
hostonlyadapter2="vboxnet1"
macaddress2="080027863E0F"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="pulse"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="hosthome"
SharedFolderPathMachineMapping1="/home"
VRDEActiveConnection="off"
VRDEClients=0
vcpenabled="off"
vcpscreens=0
vcpfile="/home/suporte/.minikube/machines/minikube/minikube/minikube.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=1
GuestAdditionsVersion="5.2.32 r132056"
GuestAdditionsFacility_VirtualBox Base Driver=50,1573653043609
GuestAdditionsFacility_VirtualBox System Service=800,1573653043779
GuestAdditionsFacility_Seamless Mode=0,1573653043609
GuestAdditionsFacility_Graphics Mode=0,1573653043609
}
I1113 11:08:40.967475   28328 main.go:110] libmachine: STDERR:
{
}
🔥  Deleting "minikube" in virtualbox ...
I1113 11:08:40.967569   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage showvminfo minikube --machinereadable
I1113 11:08:41.020800   28328 main.go:110] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="7479b6cf-8687-4002-83a8-e4860b5ed845"
CfgFile="/home/suporte/.minikube/machines/minikube/minikube/minikube.vbox"
SnapFldr="/home/suporte/.minikube/machines/minikube/minikube/Snapshots"
LogFldr="/home/suporte/.minikube/machines/minikube/minikube/Logs"
hardwareuuid="7479b6cf-8687-4002-83a8-e4860b5ed845"
memory=2000
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2019-11-13T13:50:20.232000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="/home/suporte/.minikube/machines/minikube/boot2docker.iso"
"SATA-ImageUUID-0-0"="5c284f9f-887d-4a92-8cea-4090107eded3"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/home/suporte/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="fe93fa74-ed15-4c6c-88ea-f834c5964e59"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
bridgeadapter1="enp5s0f0"
macaddress1="080027FD3F42"
cableconnected1="on"
nic1="bridged"
nictype1="virtio"
nicspeed1="0"
hostonlyadapter2="vboxnet1"
macaddress2="080027863E0F"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="pulse"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="hosthome"
SharedFolderPathMachineMapping1="/home"
VRDEActiveConnection="off"
VRDEClients=0
vcpenabled="off"
vcpscreens=0
vcpfile="/home/suporte/.minikube/machines/minikube/minikube/minikube.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=1
GuestAdditionsVersion="5.2.32 r132056"
GuestAdditionsFacility_VirtualBox Base Driver=50,1573653043609
GuestAdditionsFacility_VirtualBox System Service=800,1573653043779
GuestAdditionsFacility_Seamless Mode=0,1573653043609
GuestAdditionsFacility_Graphics Mode=0,1573653043609
}
I1113 11:08:41.020906   28328 main.go:110] libmachine: STDERR:
{
}
I1113 11:08:41.020956   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage controlvm minikube poweroff
I1113 11:08:41.218955   28328 main.go:110] libmachine: STDOUT:
{
}
I1113 11:08:41.218981   28328 main.go:110] libmachine: STDERR:
{
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
}
I1113 11:08:41.219011   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage unregistervm --delete minikube
I1113 11:08:41.364002   28328 main.go:110] libmachine: STDOUT:
{
}
I1113 11:08:41.364020   28328 main.go:110] libmachine: STDERR:
{
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
}
W1113 11:08:41.389311   28328 exit.go:101] Unable to start VM: start: Maximum number of retries (5) exceeded

💣  Unable to start VM: start: Maximum number of retries (5) exceeded

**Comment by tstromberg** [comment]
The actual error message was cut-off by the retry. Do you mind attaching the brief output of:

`minikube start`

Thanks!

**Comment by sharifelgamal** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it.

Thank you for opening the issue!
