### ISSUE TITLE
vbox: erro start:  libmachine: Error dialing TCP: dial tcp: connect: connection refused

### ISSUE THREAD

**Issue by hilner** [kubernetes/minikube#5904]
**Os comandos necessários para reproduzir o problema**:
 
**A saída completa do comando que apresentou falha**: <details>

</details>

**A saída do comando `minikube logs`**:<details>

</details>

**A versão do sistema operacional usado**:

minikube start --logtostderr
I1113 10:50:18.549874   28328 notify.go:125] Checking for updates...
I1113 10:50:19.260758   28328 start.go:251] hostinfo: {"hostname":"flad128127","uptime":180195,"bootTime":1573472824,"procs":404,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"16.04","kernelVersion":"4.4.0-142-generic","virtualizationSystem":"kvm","virtualizationRole":"host","hostid":"da043bbb-21b9-4580-bbc9-709b2241fa85"}
I1113 10:50:19.261142   28328 start.go:261] virtualization: kvm host
😄  minikube v1.5.2 on Ubuntu 16.04
I1113 10:50:19.294943   28328 start.go:547] selectDriver: flag="", old=&{{false false https://storage.googleapis.com/minikube/iso/minikube-v1.5.1.iso 2000 2 20000 virtualbox docker  [] [HTTP_PROXY=http://www-mirrordf:80 NO_PROXY=192.168.99.101] [] [] 192.168.99.1/24  default qemu:///system false false <nil> [] false [] /nfsshares  false false true} {v1.16.2 192.168.99.102 8443 minikube minikubeCA [] [] cluster.local docker    10.96.0.0/12  [] true false}}
I1113 10:50:19.294976   28328 start.go:293] selected: virtualbox
I1113 10:50:19.295169   28328 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.5.1.iso
I1113 10:50:19.295222   28328 profile.go:82] Saving config to /home/suporte/.minikube/profiles/minikube/config.json ...
I1113 10:50:19.295260   28328 lock.go:41] attempting to write to file "/home/suporte/.minikube/profiles/minikube/config.json.tmp297063587" with filemode -rw-------
I1113 10:50:19.295455   28328 cluster.go:101] Skipping create...Using existing machine configuration
I1113 10:50:19.295505   28328 cache_images.go:296] CacheImage: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> /home/suporte/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1
I1113 10:50:19.295521   28328 cache_images.go:296] CacheImage: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I1113 10:50:19.295531   28328 cache_images.go:296] CacheImage: k8s.gcr.io/etcd:3.3.15-0 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/etcd_3.3.15-0
I1113 10:50:19.295549   28328 cache_images.go:296] CacheImage: k8s.gcr.io/coredns:1.6.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/coredns_1.6.2
I1113 10:50:19.295559   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/etcd_3.3.15-0 exists
I1113 10:50:19.295561   28328 cache_images.go:296] CacheImage: k8s.gcr.io/kube-proxy:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.16.2
I1113 10:50:19.295571   28328 cache_images.go:296] CacheImage: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
I1113 10:50:19.295551   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13 exists
I1113 10:50:19.295582   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1 exists
I1113 10:50:19.295583   28328 cache_images.go:298] CacheImage: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13 completed in 75.411µs
I1113 10:50:19.295588   28328 cache_images.go:298] CacheImage: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1 completed in 20.233µs
I1113 10:50:19.295594   28328 cache_images.go:83] CacheImage k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13 succeeded
I1113 10:50:19.295594   28328 cache_images.go:296] CacheImage: k8s.gcr.io/kube-controller-manager:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.16.2
I1113 10:50:19.295609   28328 cache_images.go:296] CacheImage: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
I1113 10:50:19.295533   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1 exists
I1113 10:50:19.295620   28328 cache_images.go:296] CacheImage: k8s.gcr.io/kube-addon-manager:v9.0 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
I1113 10:50:19.295562   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/coredns_1.6.2 exists
I1113 10:50:19.295631   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0 exists
I1113 10:50:19.295633   28328 cache_images.go:296] CacheImage: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I1113 10:50:19.295651   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13 exists
I1113 10:50:19.295656   28328 cache_images.go:298] CacheImage: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13 completed in 27.542µs
I1113 10:50:19.295662   28328 cache_images.go:83] CacheImage k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13 succeeded
I1113 10:50:19.295568   28328 cache_images.go:298] CacheImage: k8s.gcr.io/etcd:3.3.15-0 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/etcd_3.3.15-0 completed in 39.591µs
I1113 10:50:19.295670   28328 cache_images.go:83] CacheImage k8s.gcr.io/etcd:3.3.15-0 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/etcd_3.3.15-0 succeeded
I1113 10:50:19.295586   28328 cache_images.go:296] CacheImage: k8s.gcr.io/kube-scheduler:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.16.2
I1113 10:50:19.295679   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.16.2 exists
I1113 10:50:19.295683   28328 cache_images.go:298] CacheImage: k8s.gcr.io/kube-scheduler:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.16.2 completed in 102.778µs
I1113 10:50:19.295688   28328 cache_images.go:83] CacheImage k8s.gcr.io/kube-scheduler:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.16.2 succeeded
I1113 10:50:19.295599   28328 cache_images.go:83] CacheImage k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1 succeeded
I1113 10:50:19.295632   28328 cache_images.go:298] CacheImage: k8s.gcr.io/coredns:1.6.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/coredns_1.6.2 completed in 86.417µs
I1113 10:50:19.295707   28328 cache_images.go:83] CacheImage k8s.gcr.io/coredns:1.6.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/coredns_1.6.2 succeeded
I1113 10:50:19.295622   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13 exists
I1113 10:50:19.295716   28328 cache_images.go:298] CacheImage: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13 completed in 111.372µs
I1113 10:50:19.295723   28328 cache_images.go:83] CacheImage k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13 succeeded
I1113 10:50:19.295610   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.16.2 exists
I1113 10:50:19.295730   28328 cache_images.go:298] CacheImage: k8s.gcr.io/kube-controller-manager:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.16.2 completed in 139.703µs
I1113 10:50:19.295735   28328 cache_images.go:83] CacheImage k8s.gcr.io/kube-controller-manager:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.16.2 succeeded
I1113 10:50:19.295577   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.16.2 exists
I1113 10:50:19.295743   28328 cache_images.go:298] CacheImage: k8s.gcr.io/kube-proxy:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.16.2 completed in 186.737µs
I1113 10:50:19.295748   28328 cache_images.go:83] CacheImage k8s.gcr.io/kube-proxy:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.16.2 succeeded
I1113 10:50:19.295602   28328 cache_images.go:296] CacheImage: k8s.gcr.io/kube-apiserver:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.16.2
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
I1113 10:50:19.295760   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.16.2 exists
I1113 10:50:19.295609   28328 cache_images.go:296] CacheImage: k8s.gcr.io/pause:3.1 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/pause_3.1
I1113 10:50:19.295777   28328 cache_images.go:302] /home/suporte/.minikube/cache/images/k8s.gcr.io/pause_3.1 exists
I1113 10:50:19.295783   28328 cache_images.go:298] CacheImage: k8s.gcr.io/pause:3.1 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/pause_3.1 completed in 177.819µs
I1113 10:50:19.295789   28328 cache_images.go:83] CacheImage k8s.gcr.io/pause:3.1 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/pause_3.1 succeeded
I1113 10:50:19.295776   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage showvminfo minikube --machinereadable
I1113 10:50:19.295621   28328 cache_images.go:298] CacheImage: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> /home/suporte/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1 completed in 120.335µs
I1113 10:50:19.295838   28328 cache_images.go:83] CacheImage gcr.io/k8s-minikube/storage-provisioner:v1.8.1 -> /home/suporte/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1 succeeded
I1113 10:50:19.295766   28328 cache_images.go:298] CacheImage: k8s.gcr.io/kube-apiserver:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.16.2 completed in 167.63µs
I1113 10:50:19.295851   28328 cache_images.go:83] CacheImage k8s.gcr.io/kube-apiserver:v1.16.2 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.16.2 succeeded
I1113 10:50:19.295637   28328 cache_images.go:298] CacheImage: k8s.gcr.io/kube-addon-manager:v9.0 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0 completed in 21.74µs
I1113 10:50:19.295891   28328 cache_images.go:83] CacheImage k8s.gcr.io/kube-addon-manager:v9.0 -> /home/suporte/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0 succeeded
I1113 10:50:19.295898   28328 cache_images.go:90] Successfully cached all images.
I1113 10:50:19.350831   28328 main.go:110] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="7479b6cf-8687-4002-83a8-e4860b5ed845"
CfgFile="/home/suporte/.minikube/machines/minikube/minikube/minikube.vbox"
SnapFldr="/home/suporte/.minikube/machines/minikube/minikube/Snapshots"
LogFldr="/home/suporte/.minikube/machines/minikube/minikube/Logs"
hardwareuuid="7479b6cf-8687-4002-83a8-e4860b5ed845"
memory=2000
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="poweroff"
VMStateChangeTime="2019-11-13T13:50:03.567000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="/home/suporte/.minikube/machines/minikube/boot2docker.iso"
"SATA-ImageUUID-0-0"="5c284f9f-887d-4a92-8cea-4090107eded3"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/home/suporte/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="fe93fa74-ed15-4c6c-88ea-f834c5964e59"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
bridgeadapter1="enp5s0f0"
macaddress1="080027FD3F42"
cableconnected1="on"
nic1="bridged"
nictype1="virtio"
nicspeed1="0"
hostonlyadapter2="vboxnet1"
macaddress2="080027863E0F"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="pulse"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="hosthome"
SharedFolderPathMachineMapping1="/home"
vcpenabled="off"
vcpscreens=0
vcpfile="/home/suporte/.minikube/machines/minikube/minikube/minikube.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
}
I1113 10:50:19.350924   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.350968   28328 cluster.go:113] Machine state:  Stopped
🔄  Starting existing virtualbox VM for "minikube" ...
I1113 10:50:19.351033   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage showvminfo minikube --machinereadable
I1113 10:50:19.405428   28328 main.go:110] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="7479b6cf-8687-4002-83a8-e4860b5ed845"
CfgFile="/home/suporte/.minikube/machines/minikube/minikube/minikube.vbox"
SnapFldr="/home/suporte/.minikube/machines/minikube/minikube/Snapshots"
LogFldr="/home/suporte/.minikube/machines/minikube/minikube/Logs"
hardwareuuid="7479b6cf-8687-4002-83a8-e4860b5ed845"
memory=2000
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="poweroff"
VMStateChangeTime="2019-11-13T13:50:03.567000000"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="/home/suporte/.minikube/machines/minikube/boot2docker.iso"
"SATA-ImageUUID-0-0"="5c284f9f-887d-4a92-8cea-4090107eded3"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/home/suporte/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="fe93fa74-ed15-4c6c-88ea-f834c5964e59"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
bridgeadapter1="enp5s0f0"
macaddress1="080027FD3F42"
cableconnected1="on"
nic1="bridged"
nictype1="virtio"
nicspeed1="0"
hostonlyadapter2="vboxnet1"
macaddress2="080027863E0F"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="pulse"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="hosthome"
SharedFolderPathMachineMapping1="/home"
vcpenabled="off"
vcpscreens=0
vcpfile="/home/suporte/.minikube/machines/minikube/minikube/minikube.webm"
vcpwidth=1024
vcpheight=768
vcprate=512
vcpfps=25
GuestMemoryBalloon=0
}
I1113 10:50:19.405554   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.405605   28328 main.go:110] libmachine: Check network to re-create if needed...
I1113 10:50:19.405620   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage list hostonlyifs
I1113 10:50:19.458205   28328 main.go:110] libmachine: STDOUT:
{
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:0800:27ff:fe00:0001
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

}
I1113 10:50:19.458238   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.458776   28328 main.go:110] libmachine: Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
I1113 10:50:19.458787   28328 main.go:110] libmachine: Found: vboxnet1
I1113 10:50:19.458796   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage list dhcpservers
I1113 10:50:19.491811   28328 main.go:110] libmachine: STDOUT:
{
NetworkName:    HostInterfaceNetworking-vboxnet0
IP:             192.168.56.100
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.56.101
upperIPAddress: 192.168.56.254
Enabled:        Yes

NetworkName:    HostInterfaceNetworking-vboxnet1
IP:             192.168.99.4
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes

}
I1113 10:50:19.491836   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.491880   28328 main.go:110] libmachine: Removing orphan DHCP servers...
I1113 10:50:19.491890   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage list hostonlyifs
I1113 10:50:19.544323   28328 main.go:110] libmachine: STDOUT:
{
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

Name:            vboxnet1
GUID:            786f6276-656e-4174-8000-0a0027000001
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80:0000:0000:0000:0800:27ff:fe00:0001
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:01
MediumType:      Ethernet
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet1

}
I1113 10:50:19.544352   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.544422   28328 main.go:110] libmachine: Adding/Modifying DHCP server "192.168.99.20" with address range "192.168.99.100" - "192.168.99.254"...
I1113 10:50:19.544433   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage list dhcpservers
I1113 10:50:19.578356   28328 main.go:110] libmachine: STDOUT:
{
NetworkName:    HostInterfaceNetworking-vboxnet0
IP:             192.168.56.100
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.56.101
upperIPAddress: 192.168.56.254
Enabled:        Yes

NetworkName:    HostInterfaceNetworking-vboxnet1
IP:             192.168.99.4
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes

}
I1113 10:50:19.578380   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.578432   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage dhcpserver modify --netname HostInterfaceNetworking-vboxnet1 --ip 192.168.99.20 --netmask 255.255.255.0 --lowerip 192.168.99.100 --upperip 192.168.99.254 --enable
I1113 10:50:19.719895   28328 main.go:110] libmachine: STDOUT:
{
}
I1113 10:50:19.719909   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.719927   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage modifyvm minikube --nic2 hostonly --nictype2 virtio --nicpromisc2 deny --hostonlyadapter2 vboxnet1 --cableconnected2 on
I1113 10:50:19.812912   28328 main.go:110] libmachine: STDOUT:
{
}
I1113 10:50:19.812929   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.813142   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage modifyvm minikube --natpf1 delete ssh
I1113 10:50:19.913400   28328 main.go:110] libmachine: STDOUT:
{
}
I1113 10:50:19.913418   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:19.913432   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage modifyvm minikube --natpf1 ssh,tcp,127.0.0.1,25336,,22
I1113 10:50:20.005593   28328 main.go:110] libmachine: STDOUT:
{
}
I1113 10:50:20.005608   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:20.005620   28328 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage startvm minikube --type headless
I1113 10:50:20.245252   28328 main.go:110] libmachine: STDOUT:
{
Waiting for VM "minikube" to power on...
VM "minikube" has been successfully started.
}
I1113 10:50:20.245268   28328 main.go:110] libmachine: STDERR:
{
}
I1113 10:50:20.245280   28328 main.go:110] libmachine: Checking vm logs: /home/suporte/.minikube/machines/minikube/minikube/Logs/VBox.log
I1113 10:50:20.246551   28328 main.go:110] libmachine: Waiting for an IP...
I1113 10:50:20.246571   28328 main.go:110] libmachine: Getting to WaitForSSH function...
I1113 10:50:20.246742   28328 main.go:110] libmachine: Using SSH client type: native
I1113 10:50:20.265840   28328 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x7a75b0] 0x7a7580 <nil>  [] 0s} 127.0.0.1 25336 <nil> <nil>}
I1113 10:50:20.265865   28328 main.go:110] libmachine: About to run SSH command:
exit 0
I1113 10:50:20.265983   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:23.266248   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:26.266591   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:29.266887   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:32.267129   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:35.267497   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:38.267757   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:41.268009   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:44.268269   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:47.268579   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:50.268898   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:53.269179   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:56.269486   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:50:59.269771   28328 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:25336: connect: connection refused
I1113 10:51:02.270039   28328 mai

**Comment by tstromberg** [comment]
I didn't actually see the final error message with startup? Is it just continued "connection refused" messages,  or does it output something different eventually?

I noticed your machine can run the `kvm2` driver. You may have better luck with it: 
https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/

**Comment by medyagh** [comment]
@hilner  do you mind trying with latest verison of virtualbox ( there is a new release of vbox) or perferably with KVM ?

**Comment by Asarew** [comment]
i'm having the same exact issue. i installed the latest version of virtualbox, and also KVM. but nothing seem to work for me :(

I nuked my ~.minikube folder and attempted a fresh start multiple times but i get the same error every time.

**Comment by LindaLawton** [comment]
I am having the same issue unfortunately for me this is my first time running this so all i have done is the following.

>choco install minikube -y
>minikube start --vm-driver=hyperv

I cant do a minikube delete either as i am getting the same TCP error there as well.

@Asarew  I dont know what you mean by different virtual box would you mind being a little more clear with which command i should use.

I have had docker running on my machine for months its not a hyperv issue.

**Comment by medyagh** [comment]
@Asarew sorry to heard that ! do you happen to use a VPN or proxy or a corp network setup that is different than standard?
