### ISSUE TITLE
minikube wont ready with command 'minikube start'

### ISSUE THREAD

**Issue by zzzhy** [kubernetes/minikube#5905]
**The exact command to reproduce the issue**:
minikube start --cache-images --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --cpus 4 --memory 12680

**The full output of the command that failed**:<details>
💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared
Problems detected in kube-addon-manager ["792bb2ae3606"]:
    error: error pruning namespaced object /v1, Kind=Service: Get https://localhost:8443/api/v1/namespaces/kube-system/services?labelSelector=kubernetes.io%2Fcluster-service%21%3Dtrue%2Caddonmanager.kubernetes.io%2Fmode%3DReconcile: dial tcp 127.0.0.1:8443: connect: connection refused

</details>

**The output of the `minikube logs` command**:<details>

😄  minikube v1.5.2 on Darwin 10.15.1
✅  Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running virtualbox "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
🔄  Relaunching Kubernetes using kubeadm ...

💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-addon-manager ["792bb2ae3606"]:
    error: error pruning namespaced object /v1, Kind=Service: Get https://localhost:8443/api/v1/namespaces/kube-system/services?labelSelector=kubernetes.io%2Fcluster-service%21%3Dtrue%2Caddonmanager.kubernetes.io%2Fmode%3DReconcile: dial tcp 127.0.0.1:8443: connect: connection refused
</details>

**The operating system version**:
Mac Catalina 10.15.1 (19B88)

**Comment by zzzhy** [comment]
when recreate minikube vm, it turns out working fine !

**Comment by priyawadhwa** [comment]
hey @zzzhy, thanks for opening this! looks like the apiserver didn't come up. I'll go ahead and close this issue since it seems restart solved your issue.

**Comment by tstromberg** [comment]
Possibly related PR: #5916

**Comment by tstromberg** [comment]
I believe we fixed this with #5916 which was merged into minikube v1.6. If you run into this issue and are not specifically using the 'none' driver, please try with the latest release of minikube. If it still exists, open a new issue.
