### ISSUE TITLE
Use Github projects and replace lgtm.co with Github review approvals

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#591]
Github announced a ton of new features [1] yesterday including the projects tab as well as changes to code reviews.  Opening up this issue to see what the other maintainers think of using projects to track issues and possibly replacing LGTM.co with github code review approvals.  

[1] The announcement of the features
https://github.com/blog/2256-a-whole-new-github-universe-announcing-new-tools-forums-and-features

**Comment by jimmidyson** [comment]
:+1: Loads of potentially good stuff to use here & agree we should move from lgtm to github code review approvals which have worked great for me so far on other projects.

**Comment by philips** [comment]
yes!
