### ISSUE TITLE
Lock files should be per-user!

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#5911]
I was running into this issue while trying to let users create their own test clusters at a shared box.

Is there a similar issue for the following files, which need to be separated as well?
```
/tmp/juju-kubeconfigUpdate
/tmp/juju-kube-config
```

In addition, is it safe using a shared user for now (e.g. via `sudo -u <user> minikube ...`) to manage different "profiles"?
As far as I understood from the code (from `juju/mutex_flock`), these files only get used for locking temporarily, correct?
May I also ask why these temporary files never actually seem to get deleted?

_Originally posted by @enote-kane in https://github.com/kubernetes/minikube/issues/5353#issuecomment-544565261_

**Comment by enote-kane** [comment]
Hi @tstromberg , thank you for addressing this issue.

Just for clarification: Does this mean that it should be possible now to run multiple minikube profiles managed by different users concurrently?
