### ISSUE TITLE
minikube requires docker upgrade to v19.03+ to address issues with chown on COPY

### ISSUE THREAD

**Issue by harsimranmaan** [kubernetes/minikube#5913]
**The exact command to reproduce the issue**:
Have a docker file with 
COPY --chown=${USER}:${GROUP} FILENAME .

docker build fails within minikube context.
**The full output of the command that failed**:
unable to convert uid/gid chown string to host mapping: can't find uid for user ${USER}: no such user: ${USER}

**The output of the `minikube logs` command**:
docker info | grep "Server Version"
 Server Version: 18.09.9
which does not have the docker fix

**The operating system version**: macOS 10.14.6

Relates https://github.com/moby/moby/issues/35018

**Comment by afbjorklund** [comment]
Probably want to use uid/gid meanwhile, or add the user to the container image proper

**Comment by harsimranmaan** [comment]
The user is already part of the container image.

**Comment by afbjorklund** [comment]
Think that I misunderstood, the problem is not uid vs name - the problem is using environment variables in a (mostly static) Dockerfile. The output above is the _actual_ error message and not something censored...

**Comment by afbjorklund** [comment]
Anyway, as I wrote in the PR we can upgrade Docker daemon but I want do it with the new k8s 1.17 and we should upgrade runc/containerd at the same time (as bundled with it)

**Comment by harsimranmaan** [comment]
Let me know if you'd like me to update the PR with new components. I think the tests might be a bit brittle as they have been failing for same reasons on different PRs. Is this something I should worry about?
