### ISSUE TITLE
hyperv: fails to connect to host after changing network connection/location

### ISSUE THREAD

**Issue by telefoontoestel** [kubernetes/minikube#5921]
**The exact command to reproduce the issue**:
minikube ip

**The full output of the command that failed**:
<details>
No output. Command fails and freezes
</details>

**The output of the `minikube logs` command**:
<details>
No entries in the log during until restart
</details>

**The operating system version**:
Windows 10 Pro (fully updated) with Hyper-V

**Steps to reproduce**
Setup a minikube with `minikube start` and deploy one or more pods. Now go to a different location with an entirely different network (e.g. start at business location and change to home location). Try to connect to the pods again. This fails and all minikube commands fail too now.

**Note**
The network address range at the business location is 192.168.1.0/24 and the home location is at 192.168.2.0/24. Maybe that is relevant in the issue.

**Comment by medyagh** [comment]
@telefoontoestel I have not heared any updates on this issue, I will close this please feel free to re-open
