### ISSUE TITLE
kubectl reports kube-addon-manager-minikube ImagePullBackOff after minikube start

### ISSUE THREAD

**Issue by davidthewatson** [kubernetes/minikube#5924]
I'm trying to start minikube with hyperkit on macos mojave behind corporate proxy. I've done this before on this machine on this network. However, I've had to reinstall from brew and I'm afraid the new version can't get out through the proxy despite what are obviously correct proxy settings from the debug output. It's weird because I can get out from ```minikube ssh``` with curl or wget.

    minikube start

```
$ minikube start
* minikube v1.5.2 on Darwin 10.14.6
* Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Found network options:
  - HTTP_PROXY=http://proxy.dog.com:80
  - HTTPS_PROXY=http://proxy.dog.com:80
  - NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24,192.168.64.0/24
  - http_proxy=http://proxy.dog.com:80
  - https_proxy=http://proxy.dog.com:80
! VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
* Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
  - env HTTP_PROXY=http://proxy.dog.com:80
  - env HTTPS_PROXY=http://proxy.dog.com:80
  - env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24,192.168.64.0/24
  - env HTTP_PROXY=http://proxy.dog.com:80
  - env HTTPS_PROXY=http://proxy.dog.com:80
* Pulling images ...
* Unable to pull images, which may be OK: running cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml\"": Process exited with status 1
* Launching Kubernetes ... 
* Waiting for: apiserver
* Done! kubectl is now configured to use "minikube"
```

[minikube.txt](https://github.com/kubernetes/minikube/files/3852601/minikube.txt)

macos 10.14.6 mojave

**Comment by priyawadhwa** [comment]
Hey @davidthewatson thanks for opening this issue. This is the same bug as #5891, & it seems that issue was closed because the issuer switched from hyperkit to virtualbox.

What is the output of:

minikube ssh 'sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml'

?

**Comment by pandey4u** [comment]
Omwindows 10 desktop using Hyper-V

Hello PriyaWadhwa, similar issue on the HyperV windows 10 desktop behind proxy.

C:\WINDOWS\system32>kubectl get pods --namespace kube-system
NAME                               READY   STATUS         RESTARTS   AGE
coredns-5644d7b6d9-5w74z           1/1     Running        2          56m
coredns-5644d7b6d9-mnmxm           1/1     Running        2          56m
etcd-minikube                      1/1     Running        2          55m
**kube-addon-manager-minikube        0/1     ErrImagePull   0          56m**
kube-apiserver-minikube            1/1     Running        2          55m
kube-controller-manager-minikube   1/1     Running        2          55m
kube-proxy-8rnz4                   1/1     Running        2          56m
kube-scheduler-minikube            1/1     Running        2          55m

**Comment by pandey4u** [comment]
I RAN this command on the minikubew container 

sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml


failed to pull image "k8s.gcr.io/kube-apiserver:v1.16.2": output: Error response from daemon: Get https://k8s.gcr.io/v2/: remote error: tls: handshake failure
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher

**Comment by pandey4u** [comment]
I1121 17:31:19.304749    6247 initconfiguration.go:190] loading configuration from "/var/tmp/minikube/kubeadm.yaml"
I1121 17:31:19.308855    6247 feature_gate.go:216] feature gates: &{map[]}
exit status 1
output: Error response from daemon: Get https://k8s.gcr.io/v2/: remote error: tls: handshake failure
, error
k8s.io/kubernetes/cmd/kubeadm/app/util/runtime.(*DockerRuntime).PullImage
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/util/runtime/runtime.go:165
k8s.io/kubernetes/cmd/kubeadm/app/cmd.PullControlPlaneImages
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/config.go:469
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdConfigImagesPull.func1
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/config.go:441
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337
failed to pull image "k8s.gcr.io/kube-apiserver:v1.16.2"
k8s.io/kubernetes/cmd/kubeadm/app/cmd.PullControlPlaneImages
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/config.go:470
k8s.io/kubernetes/cmd/kubeadm/app/cmd.NewCmdConfigImagesPull.func1
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/cmd/config.go:441
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).execute
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:830
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:914
k8s.io/kubernetes/vendor/github.com/spf13/cobra.(*Command).Execute
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/vendor/github.com/spf13/cobra/command.go:864
k8s.io/kubernetes/cmd/kubeadm/app.Run
        /workspace/anago-v1.16.2-beta.0.19+c97fe5036ef3df/src/k8s.io/kubernetes/_output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/app/kubeadm.go:50
main.main
        _output/dockerized/go/src/k8s.io/kubernetes/cmd/kubeadm/kubeadm.go:25
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

**Comment by yrjyrj123** [comment]
I have the same problem with VMware.

**Comment by worlvlhole** [comment]
I have similar issue but behind NO proxy. 

```
* minikube v1.5.2 on Microsoft Windows 10 Education 10.0.18362 Build 18362
* Automatically selected the 'hyperv' driver (alternates: [virtualbox])
* Creating hyperv VM (CPUs=4, Memory=8092MB, Disk=20000MB) ...
! VM may be unable to resolve external DNS records
! VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
* Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
* Pulling images ...
* Unable to pull images, which may be OK: running cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml\"": Process exited with status 1
```

**Comment by orefalo** [comment]
Same issue, hyperkit

**Comment by spursy** [comment]
**I use virtualbox, I encounter the same issue**
```
~ minikube start --docker-env HTTP_PROXY=$http_proxy --docker-env HTTPA_PROXY=$https_proxy --docker-env NO_PROXY=$NO_PROXY --vm-driver=virtualbox
😄  minikube v1.5.2 on Darwin 10.14.6
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
    ▪ http_proxy=http://127.0.0.1:7890
    ▪ https_proxy=http://127.0.0.1:7890
⚠️  VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
    ▪ env HTTP_PROXY=http://127.0.0.1:7890
    ▪ env HTTPA_PROXY=http://127.0.0.1:7890
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🚜  Pulling images ...
❌  Unable to pull images, which may be OK: running cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml\"": Process exited with status 1
🚀  Launching Kubernetes ...
⌛  Waiting for: apiserver
🏄  Done! kubectl is now configured to use "minikube"
```

**Comment by orefalo** [comment]
Well, I've since experimented since my last post.

I tried to use dnsmasq, minikube's ingress-dns addon: No success.  Lately I am exploring an undocumented command: `minikube tunnel`. Will post about it soon.

In the meantime, this script helped.

```
#!/bin/bash
# minikube-update-hosts
# A script to update your /etc/hosts file from minikube ingest records
#
# Installation
# ------------
# curl -L https://gist.github.com/jacobtomlinson/4b835d807ebcea73c6c8f602613803d4/raw/minikube-update-hosts.sh > /usr/local/bin/minikube-update-hosts
# chmod +x /usr/local/bin/minikube-update-hosts

INGRESSES=$(kubectl --context=minikube --all-namespaces=true get ingress -o jsonpath='{.items[*].spec.rules[*].host}')

MINIKUBE_IP=$(minikube ip)

HOSTS_ENTRY="$MINIKUBE_IP $INGRESSES"

if grep -Fq "$MINIKUBE_IP" /etc/hosts > /dev/null
then
    sudo sed -i '' "s/^$MINIKUBE_IP.*/$HOSTS_ENTRY/" /etc/hosts
    echo "Updated hosts entry"
else
    echo "$HOSTS_ENTRY" | sudo tee -a /etc/hosts
    echo "Added hosts entry"
fi
```

Regarding the issue above, either something is blocking the image pull or the dns is off.  Look for firewalls and/or DNS setup.

**Comment by medyagh** [comment]
@davidthewatson 
@orefalo thanks for updating this issue, do you mind sharing if you managed to solve the issue ?

**Comment by orefalo** [comment]
I did. Sorry for late reply

**Comment by medyagh** [comment]
great ! glad to hear that solved the problem
