### ISSUE TITLE
Unable to stop VM: open config.json: The system cannot find the file specified.

### ISSUE THREAD

**Issue by umathivagit** [kubernetes/minikube#5930]
minikube stop

X Unable to stop VM: open C:\Users\Uday\.minikube\machines\minikube\config.json: The system cannot find the 
file specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

Windows 10

**Comment by RA489** [comment]
@umathivagit can you please copy paste exact command and environments you are using?

**Comment by brainfull** [comment]
unfortunately it happens too often, the only reliable fix I found for now is to always delete the whole %userprofile%/.minikube directory

**Comment by tstromberg** [comment]
If `config.json` is missing, we should be erroring in such a way that says something like:

`exit.WithCode(exit.Conflict, "Unable to stop cluster, as it does not exist")`

I'm a little confused, because `StopHost` used to be able to catch this error appropriately.

**Comment by umathivagit** [comment]
> unfortunately it happens too often, the only reliable fix I found for now is to delete the whole %userprofile%/.minikube directory
> 
> this often happens because of retriable failure : see #5884 #5941
> 
> also add comments in #5072 for better windows support

Yes that worked...thanks..

**Comment by tstromberg** [comment]
Do you mind checking to see if this is still the case in minikube v1.7.0?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
