### ISSUE TITLE
Retriable failure: create: precreate Error // The character device /dev/vboxdrv does not exist

### ISSUE THREAD

**Issue by ZCJ** [kubernetes/minikube#5931]
I have been using minikube for a long time and never had issues - I have recently upgraded to ubuntu 19.10 and since then I am unable to start minikube.
virtualbox-dkms is installed (as recommended in the message below) and security boot is disabled as per #3974

**The exact command to reproduce the issue**: minikube start 

**The full output of the command that failed**:<details>

minikube v1.5.2 on Ubuntu 19.10
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-oem.\n\n\t You will not be able to start VMs until this problem is fixed.\n6.0.14_Ubuntur132055". Please upgrade at https://www.virtualbox.org
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-oem.\n\n\t You will not be able to start VMs until this problem is fixed.\n6.0.14_Ubuntur132055". Please upgrade at https://www.virtualbox.org
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-oem.\n\n\t You will not be able to start VMs until this problem is fixed.\n6.0.14_Ubuntur132055". Please upgrade at https://www.virtualbox.org
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-oem.\n\n\t You will not be able to start VMs until this problem is fixed.\n6.0.14_Ubuntur132055". Please upgrade at https://www.virtualbox.org

💣  Unable to start VM
❌  Error: [VBOX_DEVICE_MISSING] create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-oem.\n\n\t You will not be able to start VMs until this problem is fixed.\n6.0.14_Ubuntur132055". Please upgrade at https://www.virtualbox.org
💡  Suggestion: Reinstall VirtualBox and reboot. Alternatively, try the kvm2 driver: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3974
</details>

**The output of the `minikube logs` command**:<details>

api load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

docker-machine ls
NAME   ACTIVE   DRIVER   STATE   URL   SWARM   DOCKER   ERRORS
</details>

**The operating system version**: ubuntu 19.10

**Comment by tstromberg** [comment]
If VirtualBox is failing, there is not much we can do to make it work. Can you confirm that VirtualBox works for starting another VM? 

If so, minikube should function properly.

**Comment by ZCJ** [comment]
I think there is an issue with virtualbox and ubuntu 19.10

**Comment by ZCJ** [comment]
command (sudo modprobe vboxdrv) from [this link ](https://askubuntu.com/questions/1189888/how-to-install-virtualbox-on-ubuntu-19-10-secure-boot-not-enabled) fixed it for me
