### ISSUE TITLE
mount: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter

### ISSUE THREAD

**Issue by smallwenzi** [kubernetes/minikube#5939]
minikube.exe mount E:/docker/testk8s:/testk8s
X Error getting the host IP address to use from within the VM: Error getting VM/
Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Ad
apter #2

**Comment by tstromberg** [comment]
I've seen this happen once myself about 9 months ago, but wasn't able to replicate it. Do you mind running:

`minikube ssh "ifconfig -a"`

Thanks!
