### ISSUE TITLE
minikube failed to start -> Waiting for apiserver process

### ISSUE THREAD

**Issue by LLOUIS03** [kubernetes/minikube#5943]
My environment:

OS: Ubuntu 18.04.3 LTS

I run command:

minikube start --vm-driver=none --alsologtostderr -v=8

Outputs:
minikube version: v1.5.2, Ubuntu 18.04.3 LTS

The output is: 
I1118 20:54:34.726370   14383 kubeadm.go:665] kubelet v1.16.2 config:
[Unit]
Wants=docker.socket

[Service]
ExecStart=
ExecStart=/var/lib/minikube/binaries/v1.16.2/kubelet --authorization-mode=Webhook --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --cgroup-driver=cgroupfs --client-ca-file=/var/lib/minikube/certs/ca.crt --cluster-dns=10.96.0.10 --cluster-domain=cluster.local --config=/var/lib/kubelet/config.yaml --container-runtime=docker --fail-swap-on=false --hostname-override=minikube --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=10.0.2.15 --pod-manifest-path=/etc/kubernetes/manifests --resolv-conf=/run/systemd/resolve/resolv.conf

[Install]
I1118 20:54:34.726392   14383 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "pgrep kubelet && sudo systemctl stop kubelet"
I1118 20:54:34.743991   14383 exec_runner.go:74] (ExecRunner) Non-zero exit: /bin/bash -c "pgrep kubelet && sudo systemctl stop kubelet": exit status 1 (17.551095ms)
W1118 20:54:34.744057   14383 kubeadm.go:670] unable to stop kubelet: command failed: /bin/bash -c "pgrep kubelet && sudo systemctl stop kubelet"
stdout: 
stderr: : exit status 1 command: "/bin/bash -c \"pgrep kubelet && sudo systemctl stop kubelet\"" output: ""
I1118 20:54:34.744150   14383 cache_binaries.go:74] Not caching binary, using https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubeadm
I1118 20:54:34.744155   14383 cache_binaries.go:74] Not caching binary, using https://storage.googleapis.com/kubernetes-release/release/v1.16.2/bin/linux/amd64/kubelet
I1118 20:54:34.744170   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/cache/v1.16.2/kubeadm -> /var/lib/minikube/binaries/v1.16.2/kubeadm
I1118 20:54:34.744172   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/cache/v1.16.2/kubelet -> /var/lib/minikube/binaries/v1.16.2/kubelet
I1118 20:54:35.061065   14383 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo systemctl daemon-reload && sudo systemctl start kubelet"
I1118 20:54:35.975884   14383 certs.go:75] acquiring lock: {Name:setupCerts Clock:{} Delay:15s Timeout:0s Cancel:<nil>}
I1118 20:54:35.976180   14383 certs.go:83] Setting up /home/luis/.minikube for IP: 10.0.2.15
I1118 20:54:35.976442   14383 crypto.go:69] Generating cert /home/luis/.minikube/client.crt with IP's: []
I1118 20:54:35.980559   14383 crypto.go:157] Writing cert to /home/luis/.minikube/client.crt ...
I1118 20:54:35.981628   14383 lock.go:41] attempting to write to file "/home/luis/.minikube/client.crt" with filemode -rw-r--r--
I1118 20:54:36.521919   14383 crypto.go:165] Writing key to /home/luis/.minikube/client.key ...
I1118 20:54:36.521999   14383 lock.go:41] attempting to write to file "/home/luis/.minikube/client.key" with filemode -rw-------
I1118 20:54:36.522403   14383 crypto.go:69] Generating cert /home/luis/.minikube/apiserver.crt with IP's: [10.0.2.15 10.96.0.1 10.0.0.1]
I1118 20:54:36.529235   14383 crypto.go:157] Writing cert to /home/luis/.minikube/apiserver.crt ...
I1118 20:54:36.529265   14383 lock.go:41] attempting to write to file "/home/luis/.minikube/apiserver.crt" with filemode -rw-r--r--
I1118 20:54:37.888820   14383 crypto.go:165] Writing key to /home/luis/.minikube/apiserver.key ...
I1118 20:54:44.818701   14383 lock.go:41] attempting to write to file "/home/luis/.minikube/apiserver.key" with filemode -rw-------
I1118 20:54:44.819002   14383 crypto.go:69] Generating cert /home/luis/.minikube/proxy-client.crt with IP's: []
I1118 20:54:46.094429   14383 crypto.go:157] Writing cert to /home/luis/.minikube/proxy-client.crt ...
I1118 20:54:46.094480   14383 lock.go:41] attempting to write to file "/home/luis/.minikube/proxy-client.crt" with filemode -rw-r--r--
I1118 20:54:46.247018   14383 crypto.go:165] Writing key to /home/luis/.minikube/proxy-client.key ...
I1118 20:54:46.247094   14383 lock.go:41] attempting to write to file "/home/luis/.minikube/proxy-client.key" with filemode -rw-------
I1118 20:54:46.789229   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/ca.crt -> /var/lib/minikube/certs/ca.crt
I1118 20:54:46.789380   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/ca.key -> /var/lib/minikube/certs/ca.key
I1118 20:54:46.789466   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/apiserver.crt -> /var/lib/minikube/certs/apiserver.crt
I1118 20:54:46.789493   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/apiserver.key -> /var/lib/minikube/certs/apiserver.key
I1118 20:54:46.789561   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/proxy-client-ca.crt -> /var/lib/minikube/certs/proxy-client-ca.crt
I1118 20:54:46.789601   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/proxy-client-ca.key -> /var/lib/minikube/certs/proxy-client-ca.key
I1118 20:54:46.789624   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/proxy-client.crt -> /var/lib/minikube/certs/proxy-client.crt
I1118 20:54:46.789642   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/proxy-client.key -> /var/lib/minikube/certs/proxy-client.key
I1118 20:54:46.790017   14383 vm_assets.go:82] NewFileAsset: /home/luis/.minikube/ca.crt -> /usr/share/ca-certificates/minikubeCA.pem
I1118 20:54:46.791675   14383 exec_runner.go:42] (ExecRunner) Run:  openssl version
I1118 20:54:46.796587   14383 exec_runner.go:42] (ExecRunner) Run:  sudo test -f /etc/ssl/certs/minikubeCA.pem
I1118 20:54:46.804030   14383 exec_runner.go:42] (ExecRunner) Run:  openssl x509 -hash -noout -in /usr/share/ca-certificates/minikubeCA.pem
I1118 20:54:46.808746   14383 exec_runner.go:42] (ExecRunner) Run:  sudo test -f /etc/ssl/certs/b5213941.0
🔄  Relaunching Kubernetes using kubeadm ... 
I1118 20:54:46.817363   14383 kubeadm.go:436] RestartCluster start
I1118 20:54:46.817419   14383 exec_runner.go:42] (ExecRunner) Run:  sudo test -d /data/minikube
I1118 20:54:46.825554   14383 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo test -d /data/minikube: exit status 1 (8.080631ms)
I1118 20:54:46.825615   14383 kubeadm.go:229] /data/minikube skipping compat symlinks: command failed: sudo test -d /data/minikube
stdout: 
stderr: : exit status 1
I1118 20:54:46.825650   14383 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml"
I1118 20:54:46.994362   14383 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase kubeconfig all --config /var/tmp/minikube/kubeadm.yaml"
I1118 20:54:48.412607   14383 exec_runner.go:68] (ExecRunner) Done: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase kubeconfig all --config /var/tmp/minikube/kubeadm.yaml": (1.418210606s)
I1118 20:54:48.412650   14383 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase control-plane all --config /var/tmp/minikube/kubeadm.yaml"
I1118 20:54:48.583093   14383 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase etcd local --config /var/tmp/minikube/kubeadm.yaml"
I1118 20:54:48.694138   14383 kubeadm.go:496] Waiting for apiserver process ...
I1118 20:54:48.694215   14383 exec_runner.go:42] (ExecRunner) Run:  sudo pgrep kube-apiserver
I1118 20:54:48.711806   14383 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo pgrep kube-apiserver: exit status 1 (17.539216ms)
W1118 20:54:48.711968   14383 kubeadm.go:502] pgrep apiserver: command failed: sudo pgrep kube-apiserver
stdout: 
stderr: : exit status 1 cmd: sudo pgrep kube-apiserver
I1118 20:54:49.012735   14383 exec_runner.go:42] (ExecRunner) Run:  sudo pgrep kube-apiserver
I1118 20:54:49.041602   14383 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo pgrep kube-apiserver: exit status 1 (28.808764ms)
W1118 20:54:49.041655   14383 kubeadm.go:502] pgrep apiserver: command failed: sudo pgrep kube-apiserver
stdout: 
stderr: : exit status 1 cmd: sudo pgrep kube-apiserver
I1118 20:54:49.332086   14383 exec_runner.go:42] (ExecRunner) Run:  sudo pgrep kube-apiserver
I1118 20:54:49.354256   14383 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo pgrep kube-apiserver: exit status 1 (22.079013ms)
W1118 20:54:49.354306   14383 kubeadm.go:502] pgrep apiserver: command failed: sudo pgrep kube-apiserver
stdout: 
stderr: : exit status 1 cmd: sudo pgrep kube-apiserver
I1118 20:54:49.612700   14383 exec_runner.go:42] (ExecRunner) Run:  sudo pgrep kube-apiserver
I1118 20:54:49.630745   14383 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo pgrep kube-apiserver: exit status 1 (17.984732ms)
W1118 20:54:49.630837   14383 kubeadm.go:502] pgrep apiserver: command failed: sudo pgrep kube-apiserver
stdout: 
stderr: : exit status 1 cmd: sudo pgrep kube-apiserver
I1118 20:54:49.918266   14383 exec_runner.go:42] (ExecRunner) Run:  sudo pgrep kube-apiserver
I1118 20:54:49.934834   14383 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo pgrep kube-apiserver: exit status 1 (16.496009ms)
W1118 20:54:49.935034   14383 kubeadm.go:502] pgrep apiserver: command failed: sudo pgrep kube-apiserver
stdout: 
stderr: : exit status 1 cmd: sudo pgrep kube-apiserver
I1118 20:54:50.214129   14383 exec_runner.go:42] (ExecRunner) Run:  sudo pgrep kube-apiserver
I1118 20:54:50.237783   14383 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo pgrep kube-apiserver: exit status 1 (23.572351ms)
W1118 20:54:50.237863   14383 kubeadm.go:502] pgrep apiserver: command failed: sudo pgrep kube-apiserver

**Comment by tstromberg** [comment]
Do you mind sharing the output of `minikube logs`? I suspect the kubelet configuration provided is incompatible with your host configuration.

**Comment by zhangxpp** [comment]
same error on CentOS Linux release 7.7.1908 (Core), kernel 5.3.9-1.el7.elrepo.x86_64
docker 18.09.3


I1122 15:42:31.226015    4142 kubeadm.go:229] /data/minikube skipping compat symlinks: command failed: sudo test -d /data/minikube
stdout: 
stderr: : exit status 1
I1122 15:42:31.226043    4142 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase certs all --config /var/tmp/minikub
e/kubeadm.yaml"
I1122 15:42:32.911425    4142 exec_runner.go:68] (ExecRunner) Done: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase certs all --config /var/tmp/minikub
e/kubeadm.yaml": (1.685345593s)
I1122 15:42:32.911450    4142 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase kubeconfig all --config /var/tmp/mi
nikube/kubeadm.yaml"
I1122 15:42:33.504040    4142 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase control-plane all --config /var/tmp
/minikube/kubeadm.yaml"
I1122 15:42:33.563811    4142 exec_runner.go:42] (ExecRunner) Run:  /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase etcd local --config /var/tmp/miniku
be/kubeadm.yaml"
I1122 15:42:33.634675    4142 kubeadm.go:496] Waiting for apiserver process ...
I1122 15:42:33.634710    4142 exec_runner.go:42] (ExecRunner) Run:  sudo pgrep kube-apiserver
I1122 15:42:33.653814    4142 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo pgrep kube-apiserver: exit status 1 (19.081073ms)
W1122 15:42:33.653839    4142 kubeadm.go:502] pgrep apiserver: command failed: sudo pgrep kube-apiserver
stdout: 
stderr: : exit status 1 cmd: sudo pgrep kube-apiserver

**Comment by zhangxpp** [comment]
this prolem is fixed via modifying host configuration. 

echo "1" >/proc/sys/net/bridge/bridge-nf-call-iptables

**Comment by zhangxpp** [comment]
> same error on CentOS Linux release 7.7.1908 (Core), kernel 5.3.9-1.el7.elrepo.x86_64
> docker 18.09.3
> 
> I1122 15:42:31.226015 4142 kubeadm.go:229] /data/minikube skipping compat symlinks: command failed: sudo test -d /data/minikube
> stdout:
> stderr: : exit status 1
> I1122 15:42:31.226043 4142 exec_runner.go:42] (ExecRunner) Run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase certs all --config /var/tmp/minikub
> e/kubeadm.yaml"
> I1122 15:42:32.911425 4142 exec_runner.go:68] (ExecRunner) Done: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase certs all --config /var/tmp/minikub
> e/kubeadm.yaml": (1.685345593s)
> I1122 15:42:32.911450 4142 exec_runner.go:42] (ExecRunner) Run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase kubeconfig all --config /var/tmp/mi
> nikube/kubeadm.yaml"
> I1122 15:42:33.504040 4142 exec_runner.go:42] (ExecRunner) Run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase control-plane all --config /var/tmp
> /minikube/kubeadm.yaml"
> I1122 15:42:33.563811 4142 exec_runner.go:42] (ExecRunner) Run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase etcd local --config /var/tmp/miniku
> be/kubeadm.yaml"
> I1122 15:42:33.634675 4142 kubeadm.go:496] Waiting for apiserver process ...
> I1122 15:42:33.634710 4142 exec_runner.go:42] (ExecRunner) Run: sudo pgrep kube-apiserver
> I1122 15:42:33.653814 4142 exec_runner.go:74] (ExecRunner) Non-zero exit: sudo pgrep kube-apiserver: exit status 1 (19.081073ms)
> W1122 15:42:33.653839 4142 kubeadm.go:502] pgrep apiserver: command failed: sudo pgrep kube-apiserver
> stdout:
> stderr: : exit status 1 cmd: sudo pgrep kube-apiserver

this prolem is fixed via modifying host configuration.

echo "1" >/proc/sys/net/bridge/bridge-nf-call-iptables

**Comment by LLOUIS03** [comment]
@zhangxpp this configuration resolver the problem thank
