### ISSUE TITLE
update-context not working when using KUBECONFIG

### ISSUE THREAD

**Issue by lucanaldini** [kubernetes/minikube#5944]
**The exact command to reproduce the issue**:
➜ sudo -i env CHANGE_MINIKUBE_NONE_USER=true MINIKUBE_HOME=/home/somewhere KUBECONFIG=/tmp/.somewhereelse/config minikube start --vm-driver=none
...
➜ KUBECONFIG=/tmp/.somewhereelse/config minikube start
...
➜ KUBECONFIG=/tmp/.somewhereelse/config minikube status
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured
➜ KUBECONFIG=/tmp/.somewhereelse/config minikube update-context

**The full output of the command that failed**:
💣  update config: Kubeconfig does not have a record of the machine cluster
😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**The output of the `minikube logs` command**:
No new logs are logged when `update-context` is run.

**The operating system version**:
centos 7

If I run `KUBECONFIG=/tmp/.somewhereelse/config kubectx`, `minikube` context is present though.
The idea was to run `minikube update-context` (without the KUBECONFIG env variable) so that my default kubectx would know about `minikube` context too. But that fails too with the same output pasted above.

**Comment by govargo** [comment]
I will work on this(if someone don’t take)

It may take time to complete this.

/assign

**Comment by medyagh** [comment]
this is being worked on by  @govargo
