### ISSUE TITLE
Update dashboard to v2.0.0-beta6

### ISSUE THREAD

**Issue by Comonut** [kubernetes/minikube#5948]
Minikube is currently using dashboard release v2.0.0-beta4 which is quite buggy (for example I faced this one https://github.com/kubernetes/dashboard/issues/4399 )

Given that Minikube is using a beta release - wouldn't it be useful to always use the newest beta dashboard release until there is a stable one?

**Comment by Comonut** [comment]
Found https://github.com/kubernetes/minikube/pull/5934 , so I take that this is in progress and closing the issue

**Comment by tstromberg** [comment]
Thanks for bringing this to our attention. I'm going to leave this one open until the PR gets merged.
