### ISSUE TITLE
Typo in OSX installation curl line for v0.10.0 GitHub Release

### ISSUE THREAD

**Issue by ikester** [kubernetes/minikube#596]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG

**Minikube version** (use `minikube version`):
0.10.0

**Environment**:
Not relevant

**What happened**:
In the GitHub Release for v0.10.0 (https://github.com/kubernetes/minikube/releases/tag/v0.10.0) the Installation line under OSX has a typo in it. It currently reads:
`curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.10.0minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/`
(it's missing a slash ("/") between v0.10.10 and qinikube-darwin...

**What you expected to happen**:
The line should be:
`curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.10.0/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/`

**Comment by aaron-prindle** [comment]
Thank you for catching this, it has been resolved now.  Closing.
