### ISSUE TITLE
minikube config emits no such file config.json when setting container-runtime

### ISSUE THREAD

**Issue by danmack** [kubernetes/minikube#5961]
**The exact command to reproduce the issue**:

Below, setting configuration options for my minikube environment.  Minikube is not running when performing these commands.

(tensor) ~  > minikube config set cpus 6                 
⚠️  These changes will take effect upon a minikube delete and then a minikube start
(tensor) ~  > minikube config set memory 8192
⚠️  These changes will take effect upon a minikube delete and then a minikube start
(tensor) ~  > minikube config set container-runtime crio 

💣  Set failed: [config.Load: stat /Users/mack/.minikube/profiles/minikube/config.json: no such file or directory]

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**The full output of the command that failed**:<details>

💣  Set failed: [config.Load: stat /Users/mack/.minikube/profiles/minikube/config.json: no such file or directory]

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

(tensor) ~  > minikube logs

💣  Error getting config: stat /Users/mack/.minikube/profiles/minikube/config.json: no such file or directory

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**The operating system version**:

macOS 10.15.1 (Catalina)

**Comment by afbjorklund** [comment]
This is a bug in the `IsContainerdRuntime` function, which tries to do `config.Load`

Which seems to be invalid, as that function is only supposed to be used with gvisor.

Introduced in 043c45ddf489e736ffaad434138a33b19b1aa8a4

@RA489 ?

**Comment by afbjorklund** [comment]
Have no idea why this "crashes" on (allegedly) invalid configuration.

It would be enough with the "💣  Set failed:", once validation is correct.

**Comment by danmack** [comment]
Wow thanks for quick turnaround - one question - does the fix deal with the fact that apparently you can pass in both "crio" and "cri-o" as values for the runtime ?

**Comment by afbjorklund** [comment]
It should allow for both, just didn't add multiple test cases.
