### ISSUE TITLE
minikube cache add, doesn't add to other profiles unless restart

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5974]
Here is how to reproduce:

### start two minikube profiles
```
minikube start
minikube start -p p1
```

### tag an image and add it to the cache
```
medya@~ $ docker tag alpine justforfun
medya@~ $ minikube cache add justforfun
```

### ssh into minikube and see the images

```
medya@~ $ minikube ssh -p p1 docker images | grep justforfun
medya@~ $ minikube ssh -p minikube docker images | grep justforfun
justforfun                                latest              965ea09ff2eb        5 weeks ago         5.55MB

```

as we see the cached image was loaded to minikube profile but not p1

however if we restart p1, it will pick up the cached image

**Comment by medyagh** [comment]
What I suggest is this

- minikube start load all the images in global cache
- minikube cache add be be bound to a profile only ! and if you add an image using this command only be lodaded from that profile (as opposed to to all profiles on restart)

**Comment by afbjorklund** [comment]
It's probably fine if it loads to the current profile only, but confusing if it does load to the others but isn't visible right away... That sounds like a bug, or at least something that was unintended ?

**Comment by medyagh** [comment]
hm...for the PR I tried to keep the current behaviour.

**Comment by tstromberg** [comment]
@medyagh - was this fixed?

**Comment by sharifelgamal** [comment]
This is fixed.
