### ISSUE TITLE
KVM: looking up domain

### ISSUE THREAD

**Issue by kingsudhu** [kubernetes/minikube#5983]
Error getting host status ❌  Error: [KVM2_NO_DOMAIN] state: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'') 💡  Suggestion: The VM that minikube is configured for no longer exists. Run 'minikube delete'

**Comment by medyagh** [comment]
@kingsudhu can you try `minikube delete --all --purge` and then try start again?

**Comment by medyagh** [comment]
@kingsudhu  do you still have this issue ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
