### ISSUE TITLE
Linux documentation updates for OpenSUSE

### ISSUE THREAD

**Issue by Dxvid** [kubernetes/minikube#5986]
OpenSUSE virtualization link needs updating to the new one with '-' instead of '.' :

[https://doc.opensuse.org/documentation/leap/virtualization/html/book.virt/cha-vt-installation.html](https://doc.opensuse.org/documentation/leap/virtualization/html/book.virt/cha-vt-installation.html)

Please add install instructions for OpenSUSE and SUSE:

`curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-1.5.2.rpm && sudo snapper create --description "minikube-1.5.2" --command "rpm -ivh minikube-1.5.2.rpm" --cleanup-algorithm number`

Explanation:
snapper create --command is a wrapper around a command that creates snapshots for easy uninstall and diff. It's the standard way of installing rpms these days since btrfs became default fs a few years back. The old way (same as RedHat) still works but is less handy in case of problems.

**Comment by afbjorklund** [comment]
The minikube package only installs one single binary, so it is unlikely to require a btrfs snapshot.
Wouldn't you normally use something like `zypper`, to install dependencies and do stuff like this ?

Would prefer to not complicate the basic readme with too complex instructions, if at all possible.
I guess one could expand different distributions and file systems, in the advanced documentation.

**Comment by Dxvid** [comment]
In SUSE and OpenSUSE both YAST and zypper and transactional-update are preconfigured to create snapshots. rpm however isn't configured to create snapshots, so whenever I do rpm installs I use snapper create to get snapshots. However you have a point in making instructions simple and user friendly.
It's OK with me if you want to leave it out. If so then maybe you could just add SUSE & OpenSUSE to the Fedora & RedHat tab. But if you want to make the tab less wide you can write Red Hat / SUSE to make people understand it's compatible with both rpm distro worlds. People will then understand it's compatible with CentOs, OpenSUSE, Oracle Linux and Fedora.
However if you leave out SUSE, one cannot be sure it's compatible as Oracle creates rpms which are made incompatible with SUSE and people therefore are suspicious after having downloaded Java rpms before.
