### ISSUE TITLE
Start  --kubernetes-version="v1.3.5" does not work.

### ISSUE THREAD

**Issue by kramarz** [kubernetes/minikube#599]
**Minikube version**: 0.10.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- **VM Driver**: virtualbox

**What happened**:
```
$minikube start  --kubernetes-version="v1.3.5"
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.
$kubectl cluster-info
The connection to the server 192.168.99.102:8443 was refused - did you specify the right host or port?
```

**What you expected to happen**:
As explained in help  `--kubernetes-version="v1.3.5"` should be valid option, as it used to be in 0.9.0 
and as it stated in `$ minikube help start`
`--kubernetes-version="v1.3.5+$Format:%h$": The kubernetes version that the minikube VM will (ex: v1.2.3) 
 OR a URI which contains a localkube binary (ex: https://storage.googleapis.com/minikube/k8sReleases/v1.3.0/localkube-linux-amd64)`

**How to reproduce it** (as minimally and precisely as possible):
Execute `minikube start  --kubernetes-version="v1.3.5"`

**Anything else do we need to know**:
I know it is default, but i want to have it in my setup script so future updates don't change it. 
As a workaroud I have copied value from help "v1.3.5+\$Format:%h\$" and it works but I have no idea what it means. Providing documentation in help for this syntax would be enough for fixing this issue.

**Comment by brancz** [comment]
Getting the same with `v1.4.0-beta.2`

**Comment by webwurst** [comment]
When using `minikube start --vm-driver kvm --memory 2048 --kubernetes-version="v1.3.5"` with minikube `v0.10.0` the following error shows up:

```
$ minikube logs
==> /var/lib/localkube/localkube.err <==

==> /var/lib/localkube/localkube.out <==
unknown flag: --node-ip
Usage of /usr/local/bin/localkube:
      --alsologtostderr[=false]: log to standard error as well as files
      --apiserver-address=0.0.0.0: The address the apiserver will listen securely on
      --apiserver-insecure-address=127.0.0.1: The address the apiserver will listen insecurely on
[...]
```

**Comment by webwurst** [comment]
ref #532

**Comment by r2d4** [comment]
Thanks for the detailed report.  I've opened up a PR to fix this issue.  We were always passing --node-ip to the kubelet, which previous versions of kubernetes don't know about so it was breaking.  The proposed fix is to only pass it in if specified.  This will fix the 1.3.5, 1.3.6, and beta releases.  We haven't released a 1.3.7 localkube version so that still wont work :)

We can do a 0.10.1 release later today to address this.  Sorry about the inconvenience!

**Comment by jimmidyson** [comment]
Technically it's a problem with localkube, not kubernetes. The node IP being valid is used by a number of tools so I've proposed that we pass the node IP if the flag is valid for that version of kubernetes.

**Comment by r2d4** [comment]
So I've fixed the 1.3.x releases, however theres still a bug I'm working on with the 1.4.0-betas.  I'm always working on a patch for 0.10.1 release, but in the meantime, you can get these immediately by doing a `rm -r ~/.minikube/cache/localkube` and then the fixed versions are as follows

`minikube start --kubernetes-version=v1.3.3`
`minikube start --kubernetes-version=v1.3.4`
`minikube start --kubernetes-version=v1.3.5`
`minikube start --kubernetes-version=v1.3.6`
`minikube start --kubernetes-version=v1.3.7`

**Comment by r2d4** [comment]
Fixed the beta issue.  You should now be able to run 

`minikube start --kubernetes-version=v1.4.0-beta.8`

These will be documented in the patch

**Comment by Starefossen** [comment]
Looking forward to start playing around with the latest v1.4.0 beta on Minikube 0.10 😄

**Comment by dlorenc** [comment]
I think this is fixed now.
