### ISSUE TITLE
VBoxManage: error: Details: code NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by snimje** [kubernetes/minikube#5994]
minikube start
😄  minikube v1.5.2 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=4, Memory=16384MB, Disk=20000MB) ...
🔄  Retriable failure: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

🔥  Deleting "minikube" in virtualbox ...
🔥  Creating virtualbox VM (CPUs=4, Memory=16384MB, Disk=20000MB) ...
🔄  Retriable failure: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

🔥  Deleting "minikube" in virtualbox ...
🔥  Creating virtualbox VM (CPUs=4, Memory=16384MB, Disk=20000MB) ...
🔄  Retriable failure: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

🔥  Deleting "minikube" in virtualbox ...
🔥  Creating virtualbox VM (CPUs=4, Memory=16384MB, Disk=20000MB) ...
🔄  Retriable failure: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

🔥  Deleting "minikube" in virtualbox ...

💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@snimje I am curious, are you running in a corp environment ? 

I have a feeling this might be related to the way virtualbox handles dns, there is a new flag that we recently merged, 

for start command:
```
      --host-only-nic-type='virtio': NIC Type used for host only network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
      --hyperv-virtual-switch='': The hyperv virtual switch name. Defaults to first found. (hyperv driver only)
      --nat-nic-type='virtio': NIC Type used for host only network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
```

I wonder if that would help you (the code is on master)

and additionally, I am curious, is there any reason you dont use an alternative driver ? if you are on linux KVM and if you are on mac, hyperkit are better alternatrives.

**Comment by snimje** [comment]
Thanks for your reply. I had to enable VTx in system BIOS to get passed
this error. Minikube installed now.

**Comment by sharifelgamal** [comment]
Feel free to reopen this issue if this becomes a problem again.
