### ISSUE TITLE
none: waiting for apiserver: apiserver process never appeared

### ISSUE THREAD

**Issue by sahaaditya62** [kubernetes/minikube#5995]
I1128 13:37:37.802794   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.312422164Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
I1128 13:37:37.802811   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.312552677Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
I1128 13:37:37.802827   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313112975Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
I1128 13:37:37.802843   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313151478Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
I1128 13:37:37.802858   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313211134Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
I1128 13:37:37.802873   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313227934Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
I1128 13:37:37.802888   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313257556Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
I1128 13:37:37.802903   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313276048Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
I1128 13:37:37.802920   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313288372Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
I1128 13:37:37.802935   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313301074Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
I1128 13:37:37.802951   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313312924Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
I1128 13:37:37.802987   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313325315Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
I1128 13:37:37.803015   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313336878Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
I1128 13:37:37.803074   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313435465Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
I1128 13:37:37.803095   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313471139Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
I1128 13:37:37.803112   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313486017Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
I1128 13:37:37.803129   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313499620Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
I1128 13:37:37.803145   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313685458Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
I1128 13:37:37.803159   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313740580Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
I1128 13:37:37.803173   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.313756461Z" level=info msg="containerd successfully booted in 7.669565s"
I1128 13:37:37.803188   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.315780751Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006de820, READY" module=grpc
I1128 13:37:37.803210   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.340808244Z" level=info msg="systemd-resolved is running, so using resolvconf: /run/systemd/resolve/resolv.conf"
I1128 13:37:37.803224   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.342339650Z" level=info msg="parsed scheme: \"unix\"" module=grpc
I1128 13:37:37.803238   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.342613310Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
I1128 13:37:37.803251   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.343021718Z" level=info msg="parsed scheme: \"unix\"" module=grpc
I1128 13:37:37.803266   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.352308448Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
I1128 13:37:37.803286   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.352645299Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
I1128 13:37:37.803301   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.352686593Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
I1128 13:37:37.803317   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.352739312Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0008de5f0, CONNECTING" module=grpc
I1128 13:37:37.803332   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.352898090Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0008de5f0, READY" module=grpc
I1128 13:37:37.803348   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.352921936Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
I1128 13:37:37.803365   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.352933202Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
I1128 13:37:37.803380   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.353013454Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0008de8c0, CONNECTING" module=grpc
I1128 13:37:37.803395   11604 ssh_runner.go:205] > Nov 28 07:35:41 minikube dockerd[2072]: time="2019-11-28T07:35:41.353148055Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0008de8c0, READY" module=grpc
I1128 13:37:37.803409   11604 ssh_runner.go:205] > Nov 28 07:35:57 minikube dockerd[2072]: time="2019-11-28T07:35:57.484832356Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
I1128 13:37:37.803445   11604 ssh_runner.go:205] > Nov 28 07:35:57 minikube dockerd[2072]: time="2019-11-28T07:35:57.485843834Z" level=warning msg="Your kernel does not support cgroup blkio weight"
I1128 13:37:37.803460   11604 ssh_runner.go:205] > Nov 28 07:35:57 minikube dockerd[2072]: time="2019-11-28T07:35:57.485940362Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
I1128 13:37:37.803475   11604 ssh_runner.go:205] > Nov 28 07:35:57 minikube dockerd[2072]: time="2019-11-28T07:35:57.486021387Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
I1128 13:37:37.803489   11604 ssh_runner.go:205] > Nov 28 07:35:57 minikube dockerd[2072]: time="2019-11-28T07:35:57.486117489Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
I1128 13:37:37.803507   11604 ssh_runner.go:205] > Nov 28 07:35:57 minikube dockerd[2072]: time="2019-11-28T07:35:57.486190602Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
I1128 13:37:37.803525   11604 ssh_runner.go:205] > Nov 28 07:35:57 minikube dockerd[2072]: time="2019-11-28T07:35:57.486258184Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
I1128 13:37:37.803538   11604 ssh_runner.go:205] > Nov 28 07:35:57 minikube dockerd[2072]: time="2019-11-28T07:35:57.486872375Z" level=info msg="Loading containers: start."
I1128 13:37:37.803560   11604 ssh_runner.go:205] > Nov 28 07:36:10 minikube dockerd[2072]: time="2019-11-28T07:36:10.123776350Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
I1128 13:37:37.803591   11604 ssh_runner.go:205] > Nov 28 07:36:34 minikube dockerd[2072]: time="2019-11-28T07:36:34.359251862Z" level=info msg="Loading containers: done."
I1128 13:37:37.803613   11604 ssh_runner.go:205] > Nov 28 07:36:34 minikube dockerd[2072]: time="2019-11-28T07:36:34.368602385Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
I1128 13:37:37.803630   11604 ssh_runner.go:205] > Nov 28 07:36:34 minikube dockerd[2072]: time="2019-11-28T07:36:34.968959101Z" level=info msg="Docker daemon" commit=039a7df9ba graphdriver(s)=overlay2 version=18.09.9
I1128 13:37:37.803644   11604 ssh_runner.go:205] > Nov 28 07:36:34 minikube dockerd[2072]: time="2019-11-28T07:36:34.969217053Z" level=info msg="Daemon has completed initialization"
I1128 13:37:37.803660   11604 ssh_runner.go:205] > Nov 28 07:36:38 minikube dockerd[2072]: time="2019-11-28T07:36:38.242816092Z" level=info msg="API listen on /var/run/docker.sock"
I1128 13:37:37.803671   11604 ssh_runner.go:205] > Nov 28 07:36:38 minikube systemd[1]: Started Docker Application Container Engine.
I1128 13:37:37.803683   11604 ssh_runner.go:205] > Nov 28 07:36:38 minikube dockerd[2072]: time="2019-11-28T07:36:38.244196784Z" level=info msg="API listen on [::]:2376"
W1128 13:37:37.807452   11604 exit.go:101] Error restarting cluster: waiting for apiserver: apiserver process never appeared

💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by afbjorklund** [comment]
Do you have SELinux enabled ?

**Comment by afbjorklund** [comment]
See also #5532

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by medyagh** [comment]
@sahaaditya62 haven't heard any update, I will close this issue, please feel free to reopen if still have the same issue with newer version
