### ISSUE TITLE
Adopt GPT instead of MBR to allow for >2TB partitions

### ISSUE THREAD

**Issue by jsbraich** [kubernetes/minikube#5997]
Minikube VM appears to be using msdos partitioning to partition /dev/vda, which has 2TB limit, and cannot create partition greater than that.  Could this be changed to use gpt?

I have a test environment for which 6TB on a single server is being allocated to minikube from which only 2TB is being used (due to msdos partition table limit), and would like to use all 6TB by vda1 partition. Any thoughts?

- minikube version: v1.3.1 (--vm-driver=kvm2)
- kvm version: qemu-kvm-1.5.3-167.el7_7.1
- Host machine: CentOS 7

Regards,
-jagdeep

**Comment by afbjorklund** [comment]
“That’s a pretty big laptop you have there” - don’t think that anyone has tried with such a size before. Not sure if Buildroot even supports GPT, but you could set the VM up yourself ? (and then run minikube on it, using e.g. the generic driver)

**Comment by afbjorklund** [comment]
There are more details at: http://www.linux-kvm.org/page/OVMF

I'm not sure if this feature would be widely used, and if it can be implemented without disturbing the "normal" kvm2 driver workflow. But if it can, we could perhaps make it into an option eventually.

**Comment by jsbraich** [comment]
Thanks for your response, just wondering if gpt becomes the default partitioning scheme in minikube, how would it effect the kvm2 driver workflow.

**Comment by afbjorklund** [comment]
Like if one would need to have a patched qemu/kvm, or if it would stop working with bios or something ? For minikube we normally just deliver an ISO image to boot from and create an empty disk image at runtime, so don't really "partition" much. Your particular use case would probably be better served by mounting an additional data partition, since it is unlikely that the 6T is needed for container images...

Unfortunately we don't really have a good way to do so in a hypervisor-agnostic fashion just yet.

**Comment by afbjorklund** [comment]
Besides serial services and network interfaces, my libvirt creates two disks for me:

1)
-device lsi,id=scsi0,bus=pci.0,addr=0x4
-drive file=/home/anders/.minikube/machines/minikube/boot2docker.iso,format=raw,if=none,id=drive-scsi0-0-2,readonly=on
-device scsi-cd,bus=scsi0.0,scsi-id=2,drive=drive-scsi0-0-2,id=scsi0-0-2,bootindex=1

2)
-drive file=/home/anders/.minikube/machines/minikube/minikube.rawdisk,format=raw,if=none,id=drive-virtio-disk0,aio=threads
-device virtio-blk-pci,scsi=off,bus=pci.0,addr=0x5,drive=drive-virtio-disk0,id=virtio-disk0,bootindex=2

But the only input is the devices XML:

```XML
    <disk type='file' device='cdrom'>
      <source file='{{.ISO}}'/>
      <target dev='hdc' bus='scsi'/>
      <readonly/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='default' io='threads' />
      <source file='{{.DiskPath}}'/>
      <target dev='hda' bus='virtio'/>
    </disk>
```

So what would be needed here is what libvirt configuration to use, to switch from BIOS to UEFI ?

Probably it could also need some changes to libmachine, to create the disk image differently...

**Comment by afbjorklund** [comment]
Most likely something other than `fdisk` is needed, to create the disk image:

https://github.com/kubernetes/minikube/blob/master/deploy/iso/minikube-iso/package/automount/minikube-automount

``` sh
            # Add the data partition
            (echo n; echo p; echo 1; echo ; echo ; echo w) | fdisk $UNPARTITIONED_HD
```

If I understand correctly, this would have to use `gdisk`instead (for GPT) ?

But maybe it is enough to just add a configuration parameter, that we can do...

https://github.com/boot2docker/boot2docker/blob/master/files/init.d/autoformat

```
	echo >&2 "Partitioning $device"
	{
		# use GPT (wave of the future and all that)
		echo g

		# add a swap partition (so Docker doesn't complain about it missing)
		echo n; echo 2; echo; echo +1000M
		echo t; echo 19

		# rest of the disk for boot2docker data
		echo n; echo 1; echo; echo

		# write it!
		echo w
	} | fdisk "$device" > /dev/null
```

**Comment by jsbraich** [comment]
Yes, that is what I had to do to get around 2TB limitation.  Good thing is that 
`fdisk from util-linux 2.32` is already compiled with gpt so this small fix worked for me using kvm2, which partitioned my disk `/dev/vda1` for 6TB.  I hope this patch would also work on any other hypervisor.

````bash
diff --git a/deploy/iso/minikube-iso/package/automount/minikube-automount b/deploy/iso/minikube-iso/package/automount/minikube-automount
index 0327276b4..dd2ae56bd 100755
--- a/deploy/iso/minikube-iso/package/automount/minikube-automount
+++ b/deploy/iso/minikube-iso/package/automount/minikube-automount
@@ -29,7 +29,7 @@ if [ ! -n "$BOOT2DOCKER_DATA" ]; then
             # Let kernel re-read partition table
             partprobe
             # Add the data partition
-            (echo n; echo p; echo 1; echo ; echo ; echo w) | fdisk $UNPARTITIONED_HD
+            (echo g; echo n; echo p; echo 1; echo ; echo ; echo w) | fdisk $UNPARTITIONED_HD
             # Let kernel re-read partition table
             partprobe
             # wait for the partition to actually exist, timeout after about 5 seconds
@@ -57,7 +57,7 @@ if [ ! -n "$BOOT2DOCKER_DATA" ]; then
                 if [ $NON_NUL == 0 ]; then
                     # Create the partition, format it and then mount it
                     echo "NEW VMware boot2docker managed disk image ($UNPARTITIONED_HD): formatting it for use"
-                    (echo n; echo p; echo 1; echo ; echo ; echo w) | fdisk $UNPARTITIONED_HD
+                    (echo g; echo n; echo p; echo 1; echo ; echo ; echo w) | fdisk $UNPARTITIONED_HD
                     BOOT2DOCKER_DATA=`echo "${UNPARTITIONED_HD}1"`
                     mkfs.ext4 -i 2048 -L $LABEL $BOOT2DOCKER_DATA
                 else
````

**Comment by afbjorklund** [comment]
As per above, you don't need primary/secondary (the `'p'`) anymore after switching to GPT:

```
$ sudo fdisk /dev/vda

Welcome to fdisk (util-linux 2.33).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.


Command (m for help): g
Created a new GPT disklabel (GUID: 5C859EA1-2277-C044-805F-EFB2FF73460A).
The old dos signature will be removed by a write command.

Command (m for help): n
Partition number (1-128, default 1): p
Value out of range.
Partition number (1-128, default 1): 1
First sector (2048-39062466, default 2048): 
Last sector, +/-sectors or +/-size{K,M,G,T,P} (2048-39062466, default 39062466): 

```

But it would still require a lot of testing, so that it works OK with all the hypervisors.
