### ISSUE TITLE
Cannot start minikube: Permission Denied w/o sudo, kvm-as-root-error when w/ sudo

### ISSUE THREAD

**Issue by netikras** [kubernetes/minikube#5998]
It's a freshly downloaded minikube 1.5.2.
Frankly I don't feel like granting a non-privileged user r/w permissions to /etc/systemd/* . Could you maybe do the open()/remove() with sudo or something?

**The exact command to reproduce the issue**:
minikube start
sudo minikube start

**The full output of the command that failed**:<details>

netikras@netikras-xps: received$ minikube start
😄  minikube v1.5.2 on Linuxmint 19.1
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing kvm VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.2 on Docker '19.03.5' ...
💣  Failed to update cluster: copy: error removing file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf: remove /etc/systemd/system/kubelet.service.d/10-kubeadm.conf: permission denied
😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

netikras@netikras-xps: received$ sudo minikube start
😄  minikube v1.5.2 on Linuxmint 19.1
🛑  The "kvm" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --vm-driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/
netikras@netikras-xps: received$ echo $?
77
netikras@netikras-xps: received$ sudo minikube status
host: Stopped
kubelet: 
apiserver: 
kubeconfig: 

</details>

**The output of the `minikube logs` command**:<details>

netikras@netikras-xps: received$ sudo minikube logs
==> Docker <==
-- Logs begin at Tue 2019-10-08 00:24:14 EEST, end at Fri 2019-11-29 14:05:55 EET. --
lapkr. 29 13:56:36 netikras-xps dockerd[19092]: time="2019-11-29T13:56:36.403351294+02:00" level=info msg="Loading containers: start."
lapkr. 29 13:56:36 netikras-xps dockerd[19092]: time="2019-11-29T13:56:36.893515869+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
lapkr. 29 13:56:37 netikras-xps dockerd[19092]: time="2019-11-29T13:56:37.047365877+02:00" level=info msg="Loading containers: done."
lapkr. 29 13:56:37 netikras-xps dockerd[19092]: time="2019-11-29T13:56:37.174088197+02:00" level=info msg="Docker daemon" commit=633a0ea838 graphdriver(s)=overlay2 version=19.03.5
lapkr. 29 13:56:37 netikras-xps dockerd[19092]: time="2019-11-29T13:56:37.174360849+02:00" level=info msg="Daemon has completed initialization"
lapkr. 29 13:56:37 netikras-xps dockerd[19092]: time="2019-11-29T13:56:37.268821533+02:00" level=info msg="API listen on /var/run/docker.sock"
lapkr. 29 13:56:37 netikras-xps systemd[1]: Started Docker Application Container Engine.
lapkr. 29 13:57:32 netikras-xps systemd[1]: Stopping Docker Application Container Engine...
lapkr. 29 13:57:32 netikras-xps dockerd[19092]: time="2019-11-29T13:57:32.505035155+02:00" level=info msg="Processing signal 'terminated'"
lapkr. 29 13:57:32 netikras-xps dockerd[19092]: time="2019-11-29T13:57:32.508665261+02:00" level=info msg="Daemon shutdown complete"
lapkr. 29 13:57:32 netikras-xps systemd[1]: Stopped Docker Application Container Engine.
lapkr. 29 13:57:32 netikras-xps systemd[1]: Starting Docker Application Container Engine...
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.839468393+02:00" level=info msg="Starting up"
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.840629516+02:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.844983888+02:00" level=info msg="parsed scheme: \"unix\"" module=grpc
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.845256490+02:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.845434898+02:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.845460571+02:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.846971297+02:00" level=info msg="parsed scheme: \"unix\"" module=grpc
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.847011698+02:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.847062744+02:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.847094288+02:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.852992152+02:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.926539267+02:00" level=warning msg="Your kernel does not support swap memory limit"
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.926576327+02:00" level=warning msg="Your kernel does not support cgroup rt period"
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.926587161+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
lapkr. 29 13:57:32 netikras-xps dockerd[19733]: time="2019-11-29T13:57:32.926854024+02:00" level=info msg="Loading containers: start."
lapkr. 29 13:57:33 netikras-xps dockerd[19733]: time="2019-11-29T13:57:33.263809853+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
lapkr. 29 13:57:33 netikras-xps dockerd[19733]: time="2019-11-29T13:57:33.370015017+02:00" level=info msg="Loading containers: done."
lapkr. 29 13:57:33 netikras-xps dockerd[19733]: time="2019-11-29T13:57:33.469618631+02:00" level=info msg="Docker daemon" commit=633a0ea838 graphdriver(s)=overlay2 version=19.03.5
lapkr. 29 13:57:33 netikras-xps dockerd[19733]: time="2019-11-29T13:57:33.469759905+02:00" level=info msg="Daemon has completed initialization"
lapkr. 29 13:57:33 netikras-xps dockerd[19733]: time="2019-11-29T13:57:33.525279573+02:00" level=info msg="API listen on /var/run/docker.sock"
lapkr. 29 13:57:33 netikras-xps systemd[1]: Started Docker Application Container Engine.
lapkr. 29 13:58:25 netikras-xps dockerd[19733]: time="2019-11-29T13:58:25.339563751+02:00" level=info msg="Processing signal 'terminated'"
lapkr. 29 13:58:25 netikras-xps systemd[1]: Stopping Docker Application Container Engine...
lapkr. 29 13:58:25 netikras-xps dockerd[19733]: time="2019-11-29T13:58:25.342436806+02:00" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
lapkr. 29 13:58:25 netikras-xps dockerd[19733]: time="2019-11-29T13:58:25.344520354+02:00" level=info msg="Daemon shutdown complete"
lapkr. 29 13:58:25 netikras-xps systemd[1]: Stopped Docker Application Container Engine.
lapkr. 29 13:58:25 netikras-xps systemd[1]: Starting Docker Application Container Engine...
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.754905119+02:00" level=info msg="Starting up"
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.760570820+02:00" level=info msg="detected 127.0.0.53 nameserver, assuming systemd-resolved, so using resolv.conf: /run/systemd/resolve/resolv.conf"
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.766547680+02:00" level=info msg="parsed scheme: \"unix\"" module=grpc
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.768343530+02:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.768794500+02:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.769325805+02:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.780191997+02:00" level=info msg="parsed scheme: \"unix\"" module=grpc
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.780253472+02:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.780300544+02:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.780332892+02:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.790827157+02:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.881098279+02:00" level=warning msg="Your kernel does not support swap memory limit"
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.881137823+02:00" level=warning msg="Your kernel does not support cgroup rt period"
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.881151758+02:00" level=warning msg="Your kernel does not support cgroup rt runtime"
lapkr. 29 13:58:25 netikras-xps dockerd[20396]: time="2019-11-29T13:58:25.881833180+02:00" level=info msg="Loading containers: start."
lapkr. 29 13:58:26 netikras-xps dockerd[20396]: time="2019-11-29T13:58:26.097455611+02:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
lapkr. 29 13:58:26 netikras-xps dockerd[20396]: time="2019-11-29T13:58:26.167633108+02:00" level=info msg="Loading containers: done."
lapkr. 29 13:58:26 netikras-xps dockerd[20396]: time="2019-11-29T13:58:26.253127999+02:00" level=info msg="Docker daemon" commit=633a0ea838 graphdriver(s)=overlay2 version=19.03.5
lapkr. 29 13:58:26 netikras-xps dockerd[20396]: time="2019-11-29T13:58:26.253280676+02:00" level=info msg="Daemon has completed initialization"
lapkr. 29 13:58:26 netikras-xps systemd[1]: Started Docker Application Container Engine.
lapkr. 29 13:58:26 netikras-xps dockerd[20396]: time="2019-11-29T13:58:26.309643834+02:00" level=info msg="API listen on /var/run/docker.sock"

==> container status <==
sudo: crictl: command not found
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS                  PORTS               NAMES
76d1c2108f48        gradle              "/bin/sh"           4 days ago          Exited (0) 3 days ago                       gallant_liskov
78d74c37f51a        gradle:alpine       "/bin/sh"           5 days ago          Exited (0) 4 days ago                       fervent_kowalevski
e4b66da295cb        gradle:alpine       "/bin/bash"         5 days ago          Created                                     fervent_tharp
a18f097e9e67        gradle:alpine       "gradle"            5 days ago          Exited (0) 5 days ago                       gallant_faraday

==> dmesg <==
[  +0,000008] IRQ 133: no longer affine to CPU2
[  +0,000008] IRQ 135: no longer affine to CPU2
[  +0,000007] IRQ 136: no longer affine to CPU2
[  +0,027831] IRQ 126: no longer affine to CPU3
[  +0,009787]  cache: parent cpu1 should not be sleeping
[  +0,000796]  cache: parent cpu2 should not be sleeping
[  +0,000780]  cache: parent cpu3 should not be sleeping
[  +0,976939] usb usb1: root hub lost power or was reset
[  +0,000005] usb usb2: root hub lost power or was reset
[  +0,216139] nvme nvme0: Shutdown timeout set to 8 seconds
[  +0,924655] done.
[lapkr.15 03:34] Bluetooth: hci0: last event is not cmd complete (0x0f)
[  +0,000046] Bluetooth: hci0: inquiry failed: status 0x0c
[ +14,852901] Bluetooth: hci0: last event is not cmd complete (0x0f)
[lapkr.15 05:35] Suspending console(s) (use no_console_suspend to debug)
[  +0,229005] wlp58s0: failed to remove key (1, ff:ff:ff:ff:ff:ff) from hardware (-22)
[  +0,000489] wlp58s0: failed to remove key (2, ff:ff:ff:ff:ff:ff) from hardware (-22)
[  +1,384664] IRQ 131: no longer affine to CPU1
[  +0,019908] IRQ 136: no longer affine to CPU2
[  +0,031918] IRQ 126: no longer affine to CPU3
[  +0,008204]  cache: parent cpu1 should not be sleeping
[  +0,000828]  cache: parent cpu2 should not be sleeping
[  +0,000772]  cache: parent cpu3 should not be sleeping
[  +0,977168] usb usb1: root hub lost power or was reset
[  +0,000005] usb usb2: root hub lost power or was reset
[  +0,217302] nvme nvme0: Shutdown timeout set to 8 seconds
[  +0,912924] done.
[lapkr.15 05:50] Suspending console(s) (use no_console_suspend to debug)
[  +0,228205] wlp58s0: failed to remove key (1, ff:ff:ff:ff:ff:ff) from hardware (-22)
[  +0,000095] wlp58s0: failed to remove key (2, ff:ff:ff:ff:ff:ff) from hardware (-22)
[  +1,406530] IRQ 126: no longer affine to CPU1
[  +0,024141] IRQ 131: no longer affine to CPU2
[  +0,000013] IRQ 136: no longer affine to CPU2
[  +0,027970] IRQ 132: no longer affine to CPU3
[  +0,000012] IRQ 133: no longer affine to CPU3
[  +0,000009] IRQ 134: no longer affine to CPU3
[  +0,000009] IRQ 135: no longer affine to CPU3
[  +0,009170]  cache: parent cpu1 should not be sleeping
[  +0,000856]  cache: parent cpu2 should not be sleeping
[  +0,000797]  cache: parent cpu3 should not be sleeping
[  +0,968654] usb usb1: root hub lost power or was reset
[  +0,000005] usb usb2: root hub lost power or was reset
[  +0,217147] nvme nvme0: Shutdown timeout set to 8 seconds
[  +1,030456] done.
[lapkr.15 05:59] systemd: 50 output lines suppressed due to ratelimiting
[lapkr.15 06:02] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,208894] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,358371] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,097802] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,040520] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,252841] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +6,123980] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,017684] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,000345] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,000006] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,008346] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,015626] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,000013] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,165581] iwlwifi 0000:3a:00.0: Too many chunks: 20
[  +0,216847] iwlwifi 0000:3a:00.0: Too many chunks: 20

==> kernel <==
 14:05:55 up 19 days,  4:51,  1 user,  load average: 0,48, 0,91, 1,31
Linux netikras-xps 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Linux Mint 19.1"

==> kubelet <==
-- Logs begin at Tue 2019-10-08 00:24:14 EEST, end at Fri 2019-11-29 14:05:55 EET. --
-- No entries --

</details>

**The operating system version**:
Linux Mint 19.1

**Comment by netikras** [comment]
Then I tried a temporary workaround until this issue is sorted out, but noooo, minikube kas more tricks up it's sleeve!

```
netikras@netikras-xps: received$ sudo chown -R netikras.netikras /etc/systemd/system/kubelet.service.d/
netikras@netikras-xps: received$ minikube start
😄  minikube v1.5.2 on Linuxmint 19.1
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing kvm VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.2 on Docker '19.03.5' ...

💣  Failed to update cluster: copy: error removing file /lib/systemd/system/kubelet.service: remove /lib/systemd/system/kubelet.service: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
netikras@netikras-xps: received$ 
```

**Comment by netikras** [comment]
Let's try to use the hint and bypass the kvm driver. Gues what! Minikube :: me -- 3 :: 0

```
netikras@netikras-xps:~/received$ sudo minikube start --vm-driver=none
😄  minikube v1.5.2 on Linuxmint 19.1
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing none VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.2 on Docker '19.03.5' ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🔄  Relaunching Kubernetes using kubeadm ... 
<lots of waiting and waiting and waiting.... Then my patience ran out, I hit ^C and looked at syslog>
^C

```

syslog flooded with entries:


```
Nov 29 14:28:27 netikras-xps systemd[1]: kubelet.service: Failed with result 'exit-code'.
Nov 29 14:28:28 netikras-xps systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Nov 29 14:28:28 netikras-xps systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 188.
Nov 29 14:28:28 netikras-xps systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Nov 29 14:28:28 netikras-xps systemd[1]: Started kubelet: The Kubernetes Node Agent.
Nov 29 14:28:28 netikras-xps kubelet[1407]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:28 netikras-xps kubelet[1407]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:28 netikras-xps kubelet[1407]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:28 netikras-xps kubelet[1407]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:28 netikras-xps kubelet[1407]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:28 netikras-xps kubelet[1407]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:28 netikras-xps kubelet[1407]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:28 netikras-xps kubelet[1407]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:28 netikras-xps kubelet[1407]: F1129 14:28:28.818876    1407 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Nov 29 14:28:28 netikras-xps systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Nov 29 14:28:28 netikras-xps systemd[1]: kubelet.service: Failed with result 'exit-code'.
Nov 29 14:28:29 netikras-xps systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Nov 29 14:28:29 netikras-xps systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 189.
Nov 29 14:28:29 netikras-xps systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Nov 29 14:28:29 netikras-xps systemd[1]: Started kubelet: The Kubernetes Node Agent.
Nov 29 14:28:29 netikras-xps kubelet[1440]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:29 netikras-xps kubelet[1440]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:29 netikras-xps kubelet[1440]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:29 netikras-xps kubelet[1440]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:29 netikras-xps kubelet[1440]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:29 netikras-xps kubelet[1440]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:29 netikras-xps kubelet[1440]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:29 netikras-xps kubelet[1440]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 29 14:28:29 netikras-xps kubelet[1440]: F1129 14:28:29.680429    1440 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Nov 29 14:28:29 netikras-xps systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Nov 29 14:28:29 netikras-xps systemd[1]: kubelet.service: Failed with result 'exit-code'.
Nov 29 14:28:30 netikras-xps systemd[1]: kubelet.service: Service hold-off time over, scheduling restart.
Nov 29 14:28:30 netikras-xps systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 190.
Nov 29 14:28:30 netikras-xps systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Nov 29 14:28:30 netikras-xps systemd[1]: Started kubelet: The Kubernetes Node Agent.

```

**Comment by afbjorklund** [comment]
Sorry that minikube didn't work out for you, there should be no need for sudo or to use the none driver.

It is not clear from the logs above, why the initial kvm VM was not able to update the kubelet.service (inside the VM). It should not be needed to do any further modification to the **host** configuration.

> Failed to update cluster: copy: error removing file /etc/systemd/system/kubelet.service.d/10-kubeadm.conf: remove /etc/systemd/system/kubelet.service.d/10-kubeadm.conf: permission denied

But since this wasn't the first start, maybe there was more information available in the initial run ? Like if the permissions somehow ended up wrong after the `kubeadm` run. So need verbose logs from that.

> Starting existing kvm VM for "minikube" ...

**Comment by netikras** [comment]
@afbjorklund That's allright. Though I have nuked minikube from my system and set up a k8s cluster using kubeadm out of my lappy and a few RPis. I'm just saying that to be clear that I no longer have minikube on my lappy. I still have a /var/log/syslog for that day and I _think_ I still have an /etc/kubernetes_BAK1 (as it was clashing with k8s instalation later on) in case you need anything from them.

FTR:

```
netikras@netikras-xps:~$ kvm --version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.20)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
netikras@netikras-xps:~$ sudo dpkg -l | grep qemu
ii  ipxe-qemu                                                   1.0.0+git-20180124.fbe8c52d-0ubuntu2.2       all          PXE boot firmware - ROM images for qemu
ii  ipxe-qemu-256k-compat-efi-roms                              1.0.0+git-20150424.a25a16d-0ubuntu2          all          PXE boot firmware - Compat EFI ROM images for qemu
ii  qemu                                                        1:2.11+dfsg-1ubuntu7.20                      amd64        fast processor emulator
ii  qemu-block-extra:amd64                                      1:2.11+dfsg-1ubuntu7.20                      amd64        extra block backend modules for qemu-system and qemu-utils
ii  qemu-kvm                                                    1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU Full virtualization on x86 hardware
ii  qemu-slof                                                   20170724+dfsg-1ubuntu1                       all          Slimline Open Firmware -- QEMU PowerPC version
ii  qemu-system                                                 1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries
ii  qemu-system-arm                                             1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries (arm)
ii  qemu-system-common                                          1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries (common files)
ii  qemu-system-mips                                            1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries (mips)
ii  qemu-system-misc                                            1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries (miscellaneous)
ii  qemu-system-ppc                                             1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries (ppc)
ii  qemu-system-s390x                                           1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries (s390x)
ii  qemu-system-sparc                                           1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries (sparc)
ii  qemu-system-x86                                             1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU full system emulation binaries (x86)
ii  qemu-user                                                   1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU user mode emulation binaries
ii  qemu-utils                                                  1:2.11+dfsg-1ubuntu7.20                      amd64        QEMU utilities
netikras@netikras-xps:~$ 

```

**Comment by afbjorklund** [comment]
That's OK, installing a kubernetes cluster with `kubeadm` is what minikube does anyway.

Glad to hear it worked out for you in the end.
