### ISSUE TITLE
none Ubuntu 18.04: apiserver process never appeared

### ISSUE THREAD

**Issue by drmason13** [kubernetes/minikube#5999]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>
$ minikube version
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
$ minikube start
😄  minikube v1.5.2 on Ubuntu 18.04
👍  Upgrading from Kubernetes 1.8.0 to 1.16.2
💿  Downloading VM boot image ...
    > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [-] 100.00% 4.33 MiB p/s 33s
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running virtualbox "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.2 on Docker '17.06.0-ce' ...
💾  Downloading kubeadm v1.16.2
💾  Downloading kubelet v1.16.2
🚜  Pulling images ...
🔄  Relaunching Kubernetes using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**The output of the `minikube logs` command**:
is here: https://gist.github.com/drmason13/46a70ad118a2be4686e6f8b5312e808d

**The operating system version**:
Linux 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64

I saw another similar-ish issue #5451 as the problem there was also api-server not working and was inspired to try the following:

`minikube start --vm-driver=none --apiserver-ips 127.0.0.1 --apiserver-name localhost --alsologtostderr -v=8`

that eventually output: `🏄  Done! kubectl is now configured to use "minikube"
I1129 17:48:58.706880   11164 start.go:536] kubectl: 1.16.3, cluster: 1.16.2 (minor skew: 0)`

So I can try again:
```
$ kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node
deployment.apps/hello-node created
```

Hope that helps figure out why `minikube start` by itself didn't work

**Comment by drmason13** [comment]
Sorry, i wasn't very clear: the second "file" in the linked gist is the output of the second minkube start (`--vm-driver=none`)

**Comment by tstromberg** [comment]
It's difficult to tell from this if ` --apiserver-ips 127.0.0.1 --apiserver-name localhost` made it work, or if you were just lucky on the subsequent run.

**Comment by sharifelgamal** [comment]
@drmason13 could you double check and see if adding these extra parameters was really the reason the second run was successful?

**Comment by drmason13** [comment]
I'll try but I'm away from that particular setup for a while :/

**Comment by priyawadhwa** [comment]
Hey @drmason13 any update here?

**Comment by drmason13** [comment]
running `minikube start` again I got:

```
🎉  minikube 1.7.3 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.7.3
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

🙄  minikube v1.5.2 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
🚜  Pulling images ...
🚀  Launching Kubernetes ... 
⌛  Waiting for: apiserver
🏄  Done! kubectl is now configured to use "minikube"
```

Deleted that and tried another time.. same result. I don't appear to be able to reproduce my original issue.

**Comment by tstromberg** [comment]
Thank you for the update!
