### ISSUE TITLE
Use GOVENDOREXPERIMENT=1 from the start

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#6]
Use `godep` with `GOVENDOREXPERMIENT` set to `1`. 
Store files in `vendor/` (makes `godep` used only when adding/removing deps)
Also, require `go1.6+` for building

**Comment by dlorenc** [comment]
I think we can close this. The initial work uses godep and go 1.6, so GOVENDOREXPERMIENT=1 by default :)
