### ISSUE TITLE
none on CentOS 8: waiting for apiserver: apiserver process never appeared

### ISSUE THREAD

**Issue by ss-1** [kubernetes/minikube#6014]
**sudo /home/ss1/bin/minikube start --vm-driver=none**:

*** minikube v1.5.2 on Centos 8.0.1905
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing none VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.16.2 on Docker '19.03.5' ...
* Relaunching Kubernetes using kubeadm ...
1*
X Error restarting cluster: waiting for apiserver: apiserver process never appeared
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
**:<details>

</details>

*** ==> Docker <==
* -- Logs begin at Wed 2019-12-04 11:49:12 PST, end at Wed 2019-12-04 12:13:33 PST. --
* Dec 04 11:49:13 sskube systemd[1]: Starting Docker Application Container Engine...
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.871399083-08:00" level=info msg="Starting up"
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.878088263-08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.878126563-08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.878151763-08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.878166263-08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.888298833-08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.888314433-08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.888325933-08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.888332233-08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.895439712-08:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.911328965-08:00" level=warning msg="Your kernel does not support cgroup blkio weight"
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.911345965-08:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
* Dec 04 11:49:13 sskube dockerd[915]: time="2019-12-04T11:49:13.911819463-08:00" level=info msg="Loading containers: start."
* Dec 04 11:49:14 sskube dockerd[915]: time="2019-12-04T11:49:14.512720486-08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Dec 04 11:49:14 sskube dockerd[915]: time="2019-12-04T11:49:14.601931622-08:00" level=info msg="Loading containers: done."
* Dec 04 11:49:14 sskube dockerd[915]: time="2019-12-04T11:49:14.662401143-08:00" level=info msg="Docker daemon" commit=633a0ea graphdriver(s)=overlay2 version=19.03.5
* Dec 04 11:49:14 sskube dockerd[915]: time="2019-12-04T11:49:14.662711842-08:00" level=info msg="Daemon has completed initialization"
* Dec 04 11:49:14 sskube dockerd[915]: time="2019-12-04T11:49:14.695133046-08:00" level=info msg="API listen on /var/run/docker.sock"
* Dec 04 11:49:14 sskube systemd[1]: Started Docker Application Container Engine.
*
* ==> container status <==
* sudo: crictl: command not found
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
*
* ==> dmesg <==
* [Dec 4 11:49] Spectre V2 : Using retpoline on Skylake-generation processors may not fully mitigate the vulnerability.
* [  +0.000000] Spectre V2 : Add the "spectre_v2=ibrs" kernel boot flag to enable IBRS on Skylake systems that need full mitigation.
* [  +0.021840] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
* [  +0.006514] * Found PM-Timer Bug on the chipset. Due to workarounds for a bug,
*               * this clock source is slow. Consider trying other clock sources
* [  +0.796836] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
* [  +3.750952] Unstable clock detected, switching default tracing clock to "global"
*               If you want to keep using the local clock, then add:
*                 "trace_clock=local"
*               on the kernel command line
* [  +3.514530] systemd: 13 output lines suppressed due to ratelimiting
* [  +0.420384] systemd[1]: Failed to insert module 'ip_tables': Operation not permitted
* [  +0.499108] piix4_smbus 0000:00:07.3: SMBus base address uninitialized - upgrade BIOS or use force_addr=0xaddr
*
* ==> kernel <==
*  12:13:33 up 24 min,  2 users,  load average: 0.06, 0.30, 0.24
* Linux sskube 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* PRETTY_NAME="CentOS Linux 8 (Core)"
*
* ==> kubelet <==
* -- Logs begin at Wed 2019-12-04 11:49:12 PST, end at Wed 2019-12-04 12:13:33 PST. --
* Dec 04 12:13:26 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:26 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 920.
* Dec 04 12:13:26 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:26 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:26 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:26 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:27 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:27 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 921.
* Dec 04 12:13:27 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:27 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:27 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:27 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:27 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:27 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 922.
* Dec 04 12:13:27 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:27 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:27 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:27 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:28 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:28 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 923.
* Dec 04 12:13:28 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:28 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:28 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:28 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:29 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:29 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 924.
* Dec 04 12:13:29 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:29 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:29 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:29 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:30 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:30 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 925.
* Dec 04 12:13:30 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:30 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:30 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:30 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:30 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:30 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 926.
* Dec 04 12:13:30 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:30 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:30 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:30 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:31 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:31 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 927.
* Dec 04 12:13:31 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:31 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:31 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:31 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:32 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:32 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 928.
* Dec 04 12:13:32 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:32 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:32 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:32 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 04 12:13:33 sskube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 04 12:13:33 sskube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 929.
* Dec 04 12:13:33 sskube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:33 sskube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 04 12:13:33 sskube systemd[1]: kubelet.service: Main process exited, code=exited, status=203/EXEC
* Dec 04 12:13:33 sskube systemd[1]: kubelet.service: Failed with result 'exit-code'.
**:<details>

</details>

**Centos-8**:

**Comment by afbjorklund** [comment]
According to kubeadm documentation, CentOS currently needs to have SELinux disabled

`setenforce 0`

**Comment by tstromberg** [comment]
Are you able to confirm if disabling SELinux makes minikube work?

**Comment by ss-1** [comment]
I will confirm sometime this week and let you know. Thank you very much for
researching the problem.

**Comment by ss-1** [comment]
That fixed it. Thanks!

**Comment by tstromberg** [comment]
Excellent. I'll see if I can get a solution message added for this then.
