### ISSUE TITLE
VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED

### ISSUE THREAD

**Issue by ghazanfar1395** [kubernetes/minikube#6019]
VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED

@k8s-ci-robot  @minikube-bot

**Comment by medyagh** [comment]
hi @ghazanfar1395 

thanks for creating this issue, can you share more info,
1- are you trying to run minikube inside a VM?
2- which os, platform and driver are you trying to use ?
3- have you enabled the VT-X in your bios ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
