### ISSUE TITLE
kvm2:  new host: dial tcp: missing address

### ISSUE THREAD

**Issue by hpraveent** [kubernetes/minikube#6023]
ubuntu@k8s-master:~$ minikube start
* minikube v1.5.2 on Ubuntu 18.04
* Downloading driver docker-machine-driver-kvm2:
    > docker-machine-driver-kvm2.sha256: 65 B / 65 B [-------] 100.00% ? p/s 0s
    > docker-machine-driver-kvm2: 13.87 MiB / 13.87 MiB  100.00% 66.20 MiB p/s
* Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: new host: dial tcp: missing address
* Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: new host: dial tcp: missing address
* Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: new host: dial tcp: missing address
* Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: new host: dial tcp: missing address
*
X Unable to start VM: new host: dial tcp: missing address
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
Do you mind including the output of:

* `minikube start --alsologtostderr -v=8`
* `$HOME/.minikube/bin/docker-machine-driver-kvm2 version`

I suspect the `docker-machine-driver-kvm2` binary is crashing, but I don't have any reason why that may be happening.

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

**Comment by willbush** [comment]
If you're seeing this error in NixOS:

```
❯ minikube start --disk-size=10g --extra-disks=3 --driver kvm2
😄  minikube v1.33.0 on Nixos 24.05
    ▪ MINIKUBE_WANTUPDATENOTIFICATION=false
✨  Using the kvm2 driver based on user configuration
💾  Downloading driver docker-machine-driver-kvm2:
    > docker-machine-driver-kvm2-...:  65 B / 65 B [---------] 100.00% ? p/s 0s
    > docker-machine-driver-kvm2-...:  13.45 MiB / 13.45 MiB  100.00% 1.35 GiB
💿  Downloading VM boot image ...
    > minikube-v1.33.0-amd64.iso....:  65 B / 65 B [---------] 100.00% ? p/s 0s
    > minikube-v1.33.0-amd64.iso:  314.16 MiB / 314.16 MiB  100.00% 85.50 MiB p
👍  Starting "minikube" primary control-plane node in "minikube" cluster
💾  Downloading Kubernetes v1.30.0 preload ...
    > preloaded-images-k8s-v18-v1...:  342.90 MiB / 342.90 MiB  100.00% 89.08 M
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=10240MB) ...
🤦  StartHost failed, but will try again: new host: dial tcp: missing address
🔥  Creating kvm2 VM (CPUs=2, Memory=6000MB, Disk=10240MB) ...
😿  Failed to start kvm2 VM. Running "minikube delete" may fix it: new host: dial tcp: missing address

❌  Exiting due to DRV_MISSING_ADDRESS: Failed to start host: new host: dial tcp: missing address
💡  Suggestion: The machine-driver specified is failing to start. Try running 'docker-machine-driver-<type> version'
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6023
    ▪ https://github.com/kubernetes/minikube/issues/4679

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯


~
❯ $HOME/.minikube/bin/docker-machine-driver-kvm2 version
Could not start dynamically linked executable: /home/will/.minikube/bin/docker-machine-driver-kvm2
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
```

Just add the package [docker-machine-kvm2](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=docker-machine-kvm2).

Delete `$HOME/.minikube/bin/docker-machine-driver-kvm2` or `minikube delete --purge` and try again which fixed it for me.

**Comment by chibby0ne** [comment]
@willbush this worked beautifully! Thanks for writing the workaround! :clap:

**Comment by devinrsmith** [comment]
Is there a way to configure or build minikube such that it won't try to download the pre-built `docker-machine-driver-kvm2`?
