### ISSUE TITLE
extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy: too many open files

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes/minikube#6027]
Trying to enable PodSecurityPolicy Admission controller leads to 'too many open files' error. Cluster creation does not complete.

Have followed suggestions to put psp.yaml in appropriate location in .minikube folder as suggested on: https://github.com/kubernetes/minikube/issues/3818

Here are relevant details:

Minikube version: 
-------------------
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty

kubectl version:
-----------------
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T19:09:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

Command used:
-----------------
minikube start --extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy --alsologtostderr -v=5

Truncated Output of above command:
---------------------------------------
lse Uncompressed:false Trailer:map[] Request:0xc0011a7600 TLS:0xc0012e0a50}
I1206 10:12:52.946595   66598 kubeadm.go:514] apiserver status: Running, err: <nil>
W1206 10:12:52.946660   66598 kubeadm.go:525] get kubernetes client: client config: client config: Error loading config file "/Users/kulkade/.kube/config": open /Users/kulkade/.kube/config: too many open files
I1206 10:12:53.441398   66598 kubeadm.go:168] https://192.168.99.100:8443/healthz response: Get https://192.168.99.100:8443/healthz: dial tcp 192.168.99.100:8443: socket: too many open files <nil>
I1206 10:12:53.441426   66598 kubeadm.go:514] apiserver status: Stopped, err: <nil>

Partial minikube logs:
-----------------------

==> kube-apiserver ["0a2c8a0f017c"] <==
I1206 16:04:58.192578       1 client.go:361] parsed scheme: "endpoint"
I1206 16:04:58.192692       1 endpoint.go:66] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
I1206 16:04:58.200580       1 client.go:361] parsed scheme: "endpoint"
I1206 16:04:58.200673       1 endpoint.go:66] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
I1206 16:04:58.227158       1 client.go:361] parsed scheme: "endpoint"
I1206 16:04:58.227203       1 endpoint.go:66] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
I1206 16:04:58.241333       1 client.go:361] parsed scheme: "endpoint"
I1206 16:04:58.241399       1 endpoint.go:66] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
I1206 16:04:58.248352       1 client.go:361] parsed scheme: "endpoint"
I1206 16:04:58.248437       1 endpoint.go:66] ccResolverWrapper: sending new addresses to cc: [{https://127.0.0.1:2379 0  <nil>}]
W1206 16:04:58.343401       1 genericapiserver.go:404] Skipping API batch/v2alpha1 because it has no resources.
W1206 16:04:58.358574       1 genericapiserver.go:404] Skipping API node.k8s.io/v1alpha1 because it has no resources.
W1206 16:04:58.401574       1 genericapiserver.go:404] Skipping API rbac.authorization.k8s.io/v1alpha1 because it has no resources.
W1206 16:04:58.409292       1 genericapiserver.go:404] Skipping API scheduling.k8s.io/v1alpha1 because it has no resources.
W1206 16:04:58.417354       1 genericapiserver.go:404] Skipping API storage.k8s.io/v1alpha1 because it has no resources.
W1206 16:04:58.430224       1 genericapiserver.go:404] Skipping API apps/v1beta2 because it has no resources.
W1206 16:04:58.430332       1 genericapiserver.go:404] Skipping API apps/v1beta1 because it has no resources.
I1206 16:04:58.437266       1 plugins.go:158] Loaded 11 mutating admission controller(s) successfully in the following order: NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,PodSecurityPolicy,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,MutatingAdmissionWebhook,RuntimeClass.
I1206 16:04:58.437471       1 plugins.go:161] Loaded 8 validating admission controller(s) successfully in the following order: LimitRanger,ServiceAccount,PodSecurityPolicy,Priority,PersistentVolumeClaimResize,ValidatingAdmissionWebhook,RuntimeClass,ResourceQuota.

==> kube-scheduler ["cdd16000d016"] <==
W1206 15:45:28.729990       1 authentication.go:199] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:kube-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
W1206 15:45:28.729998       1 authentication.go:200] Continuing without authentication configuration. This may treat all requests as anonymous.
W1206 15:45:28.730042       1 authentication.go:201] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
I1206 15:45:28.736046       1 server.go:143] Version: v1.16.2
I1206 15:45:28.736297       1 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
W1206 15:45:28.766404       1 authorization.go:47] Authorization is disabled
W1206 15:45:28.766434       1 authentication.go:79] Authentication is disabled
I1206 15:45:28.766507       1 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
I1206 15:45:28.766956       1 secure_serving.go:123] Serving securely on 127.0.0.1:10259
I1206 15:45:28.968490       1 leaderelection.go:241] attempting to acquire leader lease  kube-system/kube-scheduler...
I1206 15:45:45.824819       1 leaderelection.go:251] successfully acquired lease kube-system/kube-scheduler
E1206 15:57:17.909896       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Node: Get https://localhost:8443/api/v1/nodes?allowWatchBookmarks=true&resourceVersion=346259&timeout=8m17s&timeoutSeconds=497&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused
E1206 15:57:17.910479       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1beta1.CSINode: Get https://localhost:8443/apis/storage.k8s.io/v1beta1/csinodes?allowWatchBookmarks=true&resourceVersion=345260&timeout=7m8s&timeoutSeconds=428&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused
E1206 15:57:17.910894       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.StorageClass: Get https://localhost:8443/apis/storage.k8s.io/v1/storageclasses?allowWatchBookmarks=true&resourceVersion=345260&timeout=6m29s&timeoutSeconds=389&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused
E1206 15:57:17.911012       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.PersistentVolume: Get https://localhost:8443/api/v1/persistentvolumes?allowWatchBookmarks=true&resourceVersion=345260&timeout=6m59s&timeoutSeconds=419&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused

==> kube-scheduler ["5910e6a25dd1"] <==
I1206 16:04:55.470014       1 serving.go:319] Generated self-signed cert in-memory
W1206 16:05:00.398301       1 authentication.go:262] Unable to get configmap/extension-apiserver-authentication in kube-system.  Usually fixed by 'kubectl create rolebinding -n kube-system ROLEBINDING_NAME --role=extension-apiserver-authentication-reader --serviceaccount=YOUR_NS:YOUR_SA'
W1206 16:05:00.398436       1 authentication.go:199] Error looking up in-cluster authentication configuration: configmaps "extension-apiserver-authentication" is forbidden: User "system:kube-scheduler" cannot get resource "configmaps" in API group "" in the namespace "kube-system"
W1206 16:05:00.398457       1 authentication.go:200] Continuing without authentication configuration. This may treat all requests as anonymous.
W1206 16:05:00.398473       1 authentication.go:201] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
I1206 16:05:00.417381       1 server.go:143] Version: v1.16.2
I1206 16:05:00.417482       1 defaults.go:91] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
W1206 16:05:00.421312       1 authorization.go:47] Authorization is disabled
W1206 16:05:00.421326       1 authentication.go:79] Authentication is disabled
I1206 16:05:00.421335       1 deprecated_insecure_serving.go:51] Serving healthz insecurely on [::]:10251
I1206 16:05:00.421792       1 secure_serving.go:123] Serving securely on 127.0.0.1:10259
E1206 16:05:00.508171       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.Service: services is forbidden: User "system:kube-scheduler" cannot list resource "services" in API group "" at the cluster scope
E1206 16:05:00.543532       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
E1206 16:05:00.543992       1 reflector.go:123] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:236: Failed to list *v1.Pod: pods is forbidden: User "system:kube-scheduler" cannot list resource "pods" in API group "" at the cluster scope
E1206 16:05:00.544187       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:kube-scheduler" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
E1206 16:05:00.545666       1 reflector.go:123] k8s.io/client-go/informers/factory.go:134: Failed to list *v1beta1.CSINode: csinodes.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "csinodes" in API group "storage.k8s.io" at the cluster scope
I1206 16:05:01.623878       1 leaderelection.go:241] attempting to acquire leader lease  kube-system/kube-scheduler...
I1206 16:05:18.462049       1 leaderelection.go:251] successfully acquired lease kube-system/kube-scheduler

==> kube-proxy ["7a5e4cb75939"] <==
W1206 15:45:32.703515       1 server_others.go:329] Flag proxy-mode="" unknown, assuming iptables proxy
I1206 15:45:32.730137       1 node.go:135] Successfully retrieved node IP: 192.168.99.100
I1206 15:45:32.730168       1 server_others.go:149] Using iptables Proxier.
W1206 15:45:32.731524       1 proxier.go:287] clusterCIDR not specified, unable to distinguish between internal and external traffic
I1206 15:45:32.732571       1 server.go:529] Version: v1.16.2
I1206 15:45:32.736131       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I1206 15:45:32.736161       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I1206 15:45:32.736623       1 conntrack.go:83] Setting conntrack hashsize to 32768
I1206 15:45:32.753095       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I1206 15:45:32.753144       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I1206 15:45:32.753531       1 config.go:131] Starting endpoints config controller
I1206 15:45:32.753573       1 shared_informer.go:197] Waiting for caches to sync for endpoints config
I1206 15:45:32.753605       1 config.go:313] Starting service config controller
I1206 15:45:32.753615       1 shared_informer.go:197] Waiting for caches to sync for service config
I1206 15:45:32.855090       1 shared_informer.go:204] Caches are synced for service config 
I1206 15:45:32.855138       1 shared_informer.go:204] Caches are synced for endpoints config 
E1206 15:57:17.987034       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: Get https://localhost:8443/api/v1/services?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=345260&timeout=7m1s&timeoutSeconds=421&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused
E1206 15:57:17.987270       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Endpoints: Get https://localhost:8443/api/v1/endpoints?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=346251&timeout=8m35s&timeoutSeconds=515&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused
E1206 15:57:18.997960       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: Get https://localhost:8443/api/v1/services?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=345260&timeout=9m18s&timeoutSeconds=558&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused
E1206 15:57:18.998163       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Endpoints: Get https://localhost:8443/api/v1/endpoints?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=346251&timeout=5m43s&timeoutSeconds=343&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused
W1206 15:57:23.371660       1 reflector.go:299] k8s.io/client-go/informers/factory.go:134: watch of *v1.Service ended with: too old resource version: 345260 (346262)
W1206 15:57:23.373028       1 reflector.go:299] k8s.io/client-go/informers/factory.go:134: watch of *v1.Endpoints ended with: too old resource version: 346251 (346262)
E1206 16:03:06.603130       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Service: Get https://localhost:8443/api/v1/services?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=346262&timeout=5m36s&timeoutSeconds=336&watch=true: dial tcp 127.0.0.1:8443: connect: connection refused
E1206 16:03:06.603182       1 reflector.go:280] k8s.io/client-go/informers/factory.go:134: Failed to watch *v1.Endpoints: Get https://localhost:8443/api/v1/endpoints?allowWatchBookmarks=true&labelSelector=%21service.kubernetes.io%2Fheadless%2C%21service.kubernetes.io%2Fservice-proxy-name&resourceVersion=346773&timeout=7m53s&timeoutSeconds=4

Any suggestions to resolve the issue? Will temporarily using previous version of Minikube help?

**Comment by tstromberg** [comment]
PSP's require a bit more configuration. Do you mind trying this tutorial and reporting back if it helps? 

https://minikube.sigs.k8s.io/docs/tutorials/using_psp/

**Comment by tstromberg** [comment]
Related: #2950

**Comment by devdattakulkarni** [comment]
@tstromberg Sure! 

Btw, I was able to get PSPs to run using an earlier version of Minikube (I think 0.35 -- will update once I get a chance to login to my work machine). 

I think this issue might be a regression in the current version of Minikube.

**Comment by tstromberg** [comment]
minikube doesn't do anything specific with PSP's  or other audit policies, but it could very well be that the Kubernetes version used by v0.35 and the one used by default in v1.5.2 have different behaviors.

Please let me know if you find anything else out about it.

**Comment by devdattakulkarni** [comment]
I see. 

Here is the minikube and Kubernetes version for which PSPs worked.

Minikube: minikube-0.35.0

txaumacl17: kulkade$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3", GitCommit:"b3cbbae08ec52a7fc73d334838e18d17e8512749", GitTreeState:"clean", BuildDate:"2019-11-13T11:23:11Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by priyawadhwa** [comment]
Hey @devdattakulkarni looking through the [v1.16 CHANGELOG](https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.16.md) for kubernetes it seems that there was a change to the PSP API:

```
podsecuritypolicies resources under `extensions/v1beta1` - use `policy/v1beta1` instead
```

does your PSP specify `extensions/v1beta1` and the `apiVersion`? That might explain why it works with older versions of minikube (kubernetes 1.13) and not the newer one (kubernetes 1.16)
