### ISSUE TITLE
Unable to start VM: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

### ISSUE THREAD

**Issue by imorti** [kubernetes/minikube#6028]
**The exact command to reproduce the issue**:
```minikube start```

`Unable to start VM: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1`

**The full output of the command that failed**:<details>

Unable to start VM: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by zedtux** [comment]
I have it too.

**Comment by tstromberg** [comment]
This is likely a dupe of #5594 - what version of macOS are you on?

**Comment by zedtux** [comment]
I'm running macOS Catalina 10.15.2 and D4M 2.1.7.0 (channel edge).

**Comment by tstromberg** [comment]
If `--vm-driver` is not specified, minikube defaults to hyperkit, so it's likely related.

Interesting that you are already on bleeding edge versions though.

**Comment by imorti** [comment]
yeah I'm on Catalina. Will pass in ```--vm-driver``` from now on. Thanks.

**Comment by medyagh** [comment]
@imorti glad to see the issue solved, I will close this, please feel free to re-open
