### ISSUE TITLE
sch_netem kernel module missing for network emulation (tc netem)

### ISSUE THREAD

**Issue by LaumiH** [kubernetes/minikube#6033]
**The exact command to reproduce the issue**: 
*Application based*: Run a container like debian in priviledged mode in a pod and one pod that uses the [netem](http://man7.org/linux/man-pages/man8/tc-netem.8.html) network emulation linux tool, in my case [pumba](https://github.com/alexei-led/pumba). Pumba has no effect trying to mess with the network of the debian container. Pumba uses netem.

*modprobe*: Try to run `minikube ssh` and then `modprobe -n sch_netem`, which says netem module is missing.

*With netem on a priviledged debian container in minikube*: Get a bash in the debian container and try to modify the eth0 virtual interface by changing `qdisc` to `netem loss` (which is essentially what pumba does). The command is `tc qdisc add dev eth0 root netem loss random 100%`.

A related issue, and the environment in which I found out this is not working, is described [here](https://github.com/litmuschaos/litmus/issues/979). This is a minikube specific issue, as it works with other kubeadm based clusters and GKE and others. It also works locally on a laptop just with docker images.

**The full output of the command that failed**:<details>
* `modprobe -n sch_netem` -> `modprobe: FATAL: Module sch_netem not found in directory /lib/modules/4.19.76`
* `tc qdisc add dev eth0 root netem loss random 100` -> `invalid qdisc name`
</details>

**The operating system version**: 
* 5.4.1-2-MANJARO
* minikube version: v1.5.2
  commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad

**Additional info**
I just wanted to let you know this issue exists. Maybe we can do something about it, as minikube is a great environment for starting with chaos engineering, and not being able to mess with the network (in this way) is a big drawback. Also it took me quite some time to figure this out, as I had no access to other clusters :D.

**Comment by tstromberg** [comment]
Sounds reasonable. Here are the docs for adding a new kernel module to the ISO if anyone is interested in seeing this through:

https://minikube.sigs.k8s.io/docs/contributing/iso/#adding-kernel-modules

**Comment by LaumiH** [comment]
Going to PR the change as soon as my slow network is willing to clone the repo ... 
Apply `minikube ssh` and `tc qdisc add dev eth0 root netem loss random 100%` to see how magnificently it works. But don't cry when the ssh connection fails because of 100% network loss ^^.
