### ISSUE TITLE
virtualbox: open iso/minikube-v1.5.1.iso.download: permission denied

### ISSUE THREAD

**Issue by haseeebmalik** [kubernetes/minikube#6037]
input :
**    minikube start --vm-driver=virtualbox
             **:

output :
**    minikube v1.5.2 on Ubuntu 18.04
💿  Downloading VM boot image ...
    > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s

💣  Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.5.1.iso: open /home/haseeb/.minikube/cache/iso/minikube-v1.5.1.iso.download: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
**:<i also have virtualbox install but every time i start minikube it give me the same error.kindy help.....thanks>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
This appears to be a local file permissions issue. Can you share the output of the following commands:

* `id`
* `ls -lad /home/haseeb/.minikube/cache/iso/`
* `touch /home/haseeb/.minikube/cache/iso/.test`

Thank you!

**Comment by haseeebmalik** [comment]
Thanks you actually my issue is solved .The reason behind my problem is i
had installed virtualbox on dualboot..then later i uninstall virtualbox and
install KVM ,which runs fine.

**Comment by tstromberg** [comment]
Thank you for the update!
