### ISSUE TITLE
how to use minikube addons open

### ISSUE THREAD

**Issue by 13567436138** [kubernetes/minikube#6054]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>
[root@localhost ~]# minikube addons open dashboard
X This addon does not have an endpoint defined for the 'addons open' command.
You can add one by annotating a service with the label kubernetes.io/minikube-addons-endpoint:dashboard

```
[root@localhost ~]# kubectl describe svc kubernetes-dashboard  -n kubernetes-dashboard 
Name:              kubernetes-dashboard
Namespace:         kubernetes-dashboard
Labels:            addonmanager.kubernetes.io/mode=Reconcile
                   k8s-app=kubernetes-dashboard
                   kubernetes.io/minikube-addons=dashboard
                   kubernetes.io/minikube-addons-endpoint=dashboard
Annotations:       kubectl.kubernetes.io/last-applied-configuration:
                     {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"labels":{"addonmanager.kubernetes.io/mode":"Reconcile","k8s-app":"kubern...
                   kubernetes.io/minikube-addons-endpoint: dashboard
                   label: kubernetes.io/minikube-addons-endpoint:dashboard
Selector:          k8s-app=kubernetes-dashboard
Type:              ClusterIP
IP:                10.96.84.166
Port:              <unset>  80/TCP
TargetPort:        9090/TCP
Endpoints:         172.17.0.6:9090
Session Affinity:  None
Events:            <none>
```

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
I agree, the documentation for `addons open` is not very good: https://minikube.sigs.k8s.io/docs/reference/commands/addons/

For the dashboard, you may use `minikube dashboard` to  open the correct URL.
