### ISSUE TITLE
💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared

### ISSUE THREAD

**Issue by davix** [kubernetes/minikube#6055]
**The exact command to reproduce the issue**:
minikube start --image-repository='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'

**The full output of the command that failed**:<details>
➜  ~ minikube start --image-repository='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'
🎉  minikube 1.6.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.6.0
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

🙄  minikube v1.5.2 on Darwin 10.14.6
✅  Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
⚠️  VM may be unable to resolve external DNS records
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
💾  Downloading kubelet v1.16.2
💾  Downloading kubeadm v1.16.2
🔄  Relaunching Kubernetes using kubeadm ...

💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
➜  ~ minikube logs
==> Docker <==
-- Logs begin at Mon 2019-12-09 08:24:20 UTC, end at Wed 2019-12-11 08:06:23 UTC. --
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429062134Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429146279Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429250412Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429299621Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429390624Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429438393Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429478475Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429520308Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429558862Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429595973Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429734930Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.429905639Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430200715Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430255024Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430314595Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430353791Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430398172Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430434353Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430469883Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430506510Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430546932Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430582936Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430618733Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430688988Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430730517Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430769955Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.430806380Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.431008783Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.431085096Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.431126189Z" level=info msg="containerd successfully booted in 0.007098s"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.434130738Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00012dc80, READY" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.443968930Z" level=info msg="systemd-resolved is running, so using resolvconf: /run/systemd/resolve/resolv.conf"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.444919076Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.445036379Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.445252135Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.445406146Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.445286000Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.445541844Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.445624743Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005bca90, CONNECTING" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.445869115Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005bca90, READY" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.445961739Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.446002793Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.446056795Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005bcd70, CONNECTING" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.446173661Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005bcd70, READY" module=grpc
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.460715704Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.461321240Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.461353489Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.461388916Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.461400189Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.461407943Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.461415410Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.461984281Z" level=info msg="Loading containers: start."
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.533907102Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.589710933Z" level=info msg="Loading containers: done."
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.607389655Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.617035524Z" level=info msg="Docker daemon" commit=039a7df9ba graphdriver(s)=overlay2 version=18.09.9
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.617198783Z" level=info msg="Daemon has completed initialization"
Dec 09 08:24:28 minikube systemd[1]: Started Docker Application Container Engine.
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.631692363Z" level=info msg="API listen on /var/run/docker.sock"
Dec 09 08:24:28 minikube dockerd[2415]: time="2019-12-09T08:24:28.631935760Z" level=info msg="API listen on [::]:2376"

==> container status <==
time="2019-12-11T08:06:25Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> dmesg <==
[  +5.003241] hpet1: lost 318 rtc interrupts
[  +0.262673] systemd-fstab-generator[3435]: Ignoring "noauto" for root device
[  +4.738659] hpet1: lost 319 rtc interrupts
[  +5.006369] hpet1: lost 319 rtc interrupts
[  +5.007656] hpet1: lost 318 rtc interrupts
[  +4.999077] hpet1: lost 318 rtc interrupts
[  +5.003683] hpet1: lost 319 rtc interrupts
[Dec11 08:02] hpet1: lost 318 rtc interrupts
[  +5.001667] hpet1: lost 318 rtc interrupts
[  +5.001384] hpet1: lost 319 rtc interrupts
[  +5.003034] hpet1: lost 318 rtc interrupts
[  +5.002435] hpet1: lost 318 rtc interrupts
[  +5.002163] hpet1: lost 319 rtc interrupts
[  +5.017437] hpet1: lost 319 rtc interrupts
[  +5.001174] hpet1: lost 319 rtc interrupts
[  +5.002694] hpet1: lost 318 rtc interrupts
[  +5.002344] hpet1: lost 318 rtc interrupts
[  +5.004221] hpet1: lost 319 rtc interrupts
[  +5.004063] hpet1: lost 320 rtc interrupts
[Dec11 08:03] hpet1: lost 318 rtc interrupts
[  +5.005046] hpet1: lost 318 rtc interrupts
[  +5.002485] hpet1: lost 319 rtc interrupts
[  +5.000384] hpet1: lost 320 rtc interrupts
[  +5.005729] hpet1: lost 318 rtc interrupts
[  +5.005005] hpet1: lost 319 rtc interrupts
[  +5.005254] hpet1: lost 319 rtc interrupts
[  +5.004531] hpet1: lost 318 rtc interrupts
[  +5.004412] hpet1: lost 318 rtc interrupts
[  +5.011165] hpet1: lost 319 rtc interrupts
[  +5.003002] hpet1: lost 318 rtc interrupts
[  +5.000313] hpet1: lost 318 rtc interrupts
[Dec11 08:04] hpet1: lost 318 rtc interrupts
[  +5.003023] hpet1: lost 318 rtc interrupts
[  +5.003210] hpet1: lost 320 rtc interrupts
[  +5.001847] hpet1: lost 318 rtc interrupts
[  +5.004773] hpet1: lost 318 rtc interrupts
[  +5.000406] hpet1: lost 318 rtc interrupts
[  +5.001794] hpet1: lost 319 rtc interrupts
[  +5.003975] hpet1: lost 318 rtc interrupts
[  +5.002586] hpet1: lost 319 rtc interrupts
[  +5.006031] hpet1: lost 319 rtc interrupts
[  +5.001135] hpet1: lost 319 rtc interrupts
[  +5.002230] hpet1: lost 318 rtc interrupts
[Dec11 08:05] hpet1: lost 318 rtc interrupts
[  +5.003993] hpet1: lost 320 rtc interrupts
[  +5.004664] hpet1: lost 318 rtc interrupts
[  +5.003857] hpet1: lost 319 rtc interrupts
[  +5.003449] hpet1: lost 318 rtc interrupts
[  +5.007276] hpet1: lost 319 rtc interrupts
[  +5.002044] hpet1: lost 318 rtc interrupts
[  +5.004279] hpet1: lost 318 rtc interrupts
[  +5.001440] hpet1: lost 318 rtc interrupts
[  +4.999697] hpet1: lost 318 rtc interrupts
[  +5.004248] hpet1: lost 319 rtc interrupts
[  +5.001080] hpet1: lost 318 rtc interrupts
[Dec11 08:06] hpet1: lost 318 rtc interrupts
[  +5.026897] hpet1: lost 320 rtc interrupts
[  +4.997640] hpet1: lost 318 rtc interrupts
[  +5.001240] hpet1: lost 318 rtc interrupts
[  +5.004637] hpet1: lost 319 rtc interrupts

==> kernel <==
 08:06:25 up  4:24,  0 users,  load average: 0.23, 0.27, 0.13
Linux minikube 4.19.76 #1 SMP Tue Oct 29 14:56:42 PDT 2019 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2019.02.6"

==> kubelet <==
-- Logs begin at Mon 2019-12-09 08:24:20 UTC, end at Wed 2019-12-11 08:06:25 UTC. --
Dec 11 08:06:22 minikube kubelet[7403]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:22 minikube kubelet[7403]: F1211 08:06:22.734136    7403 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Dec 11 08:06:22 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 08:06:22 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 11 08:06:23 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Dec 11 08:06:23 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 384.
Dec 11 08:06:23 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 11 08:06:23 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 11 08:06:23 minikube kubelet[7423]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:23 minikube kubelet[7423]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:23 minikube kubelet[7423]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:23 minikube kubelet[7423]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:23 minikube kubelet[7423]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:23 minikube kubelet[7423]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:23 minikube kubelet[7423]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:23 minikube kubelet[7423]: F1211 08:06:23.498721    7423 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Dec 11 08:06:23 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 08:06:23 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 11 08:06:24 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Dec 11 08:06:24 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 385.
Dec 11 08:06:24 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 11 08:06:24 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 11 08:06:24 minikube kubelet[7487]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7487]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7487]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7487]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7487]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7487]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7487]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7487]: F1211 08:06:24.235316    7487 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Dec 11 08:06:24 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 08:06:24 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 11 08:06:24 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Dec 11 08:06:24 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 386.
Dec 11 08:06:24 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 11 08:06:24 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 11 08:06:24 minikube kubelet[7496]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7496]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7496]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7496]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7496]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7496]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7496]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:24 minikube kubelet[7496]: F1211 08:06:24.978735    7496 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Dec 11 08:06:24 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 08:06:24 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 11 08:06:25 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Dec 11 08:06:25 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 387.
Dec 11 08:06:25 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 11 08:06:25 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 11 08:06:25 minikube kubelet[7506]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:25 minikube kubelet[7506]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:25 minikube kubelet[7506]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:25 minikube kubelet[7506]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:25 minikube kubelet[7506]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:25 minikube kubelet[7506]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:25 minikube kubelet[7506]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 08:06:25 minikube kubelet[7506]: F1211 08:06:25.741991    7506 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Dec 11 08:06:25 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 08:06:25 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

</details>

**The operating system version**:
macos 10.14.6

**Comment by tstromberg** [comment]
Could you please upgrade to minikube v1.6.0? I believe it may have fixed this issue.

**Comment by davix** [comment]
It doesn't happen consistently. Actually, even with my current minikube v1.5.2, it can be up later.
I'll close it now and if it happens again on v1.6, I'll re-open it.
Thanks!
