### ISSUE TITLE
Fedora 31: none: unable to load bootstrap kubeconfig: bootstrap-kubelet.conf: no such file or directory

### ISSUE THREAD

**Issue by rssfed23** [kubernetes/minikube#6062]
**The exact command to reproduce the issue**:
sudo minikube start --vm-driver=none

**The full output of the command that failed**:
In the systemd logs:<details>
Dec 11 18:17:03 virtbio systemd[1]: Started Kubernetes systemd probe.
Dec 11 18:17:03 virtbio kubelet[14346]: I1211 18:17:03.334317   14346 server.go:416] Version: v1.17.0
Dec 11 18:17:03 virtbio kubelet[14346]: I1211 18:17:03.334788   14346 plugins.go:100] No cloud provider specified.
Dec 11 18:17:03 virtbio kubelet[14346]: I1211 18:17:03.334831   14346 server.go:821] Client rotation is on, will bootstrap in background
Dec 11 18:17:03 virtbio kubelet[14346]: F1211 18:17:03.334953   14346 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Dec 11 18:17:03 virtbio systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 18:17:03 virtbio systemd[1]: kubelet.service: Failed with result 'exit-code'.
</details>

**The output of the `minikube logs` command**:<details>
[rob@virtbio ~]$ sudo minikube logs
==> Docker <==
-- Logs begin at Sat 2019-12-07 16:10:02 GMT, end at Wed 2019-12-11 18:20:43 GMT. --
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585470073Z" level=warning msg="Your kernel does not support kernel memory TCP limit"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585493256Z" level=warning msg="Your kernel does not support cgroup cpu shares"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585514464Z" level=warning msg="Your kernel does not support cgroup cfs period"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585534469Z" level=warning msg="Your kernel does not support cgroup cfs quotas"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585553170Z" level=warning msg="Your kernel does not support cgroup rt period"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585572421Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585593136Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585614833Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585636443Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585656743Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585679974Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.585703307Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.586154809Z" level=info msg="Loading containers: start."
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.818852337Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.869191754Z" level=info msg="Loading containers: done."
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.900269878Z" level=info msg="Docker daemon" commit=633a0ea838 graphdriver(s)=overlay2 version=19.03.5
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.900444184Z" level=info msg="Daemon has completed initialization"
Dec 11 18:15:09 virtbio dockerd[12332]: time="2019-12-11T18:15:09.947437531Z" level=info msg="API listen on /run/docker.sock"
Dec 11 18:15:09 virtbio systemd[1]: Started Docker Application Container Engine.
Dec 11 18:15:16 virtbio systemd[1]: Stopping Docker Application Container Engine...
Dec 11 18:15:16 virtbio dockerd[12332]: time="2019-12-11T18:15:16.696531877Z" level=info msg="Processing signal 'terminated'"
Dec 11 18:15:16 virtbio dockerd[12332]: time="2019-12-11T18:15:16.697929439Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Dec 11 18:15:16 virtbio dockerd[12332]: time="2019-12-11T18:15:16.698384766Z" level=info msg="Daemon shutdown complete"
Dec 11 18:15:16 virtbio systemd[1]: docker.service: Succeeded.
Dec 11 18:15:16 virtbio systemd[1]: Stopped Docker Application Container Engine.
Dec 11 18:15:16 virtbio systemd[1]: Starting Docker Application Container Engine...
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.835032007Z" level=info msg="Starting up"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.837579659Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.837624933Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.837659283Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.837699213Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.850838878Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.850966094Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.851000275Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.851044302Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.857627003Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871770097Z" level=warning msg="Your kernel does not support swap memory limit"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871804477Z" level=warning msg="Your kernel does not support memory reservation"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871822024Z" level=warning msg="Your kernel does not support oom control"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871832402Z" level=warning msg="Your kernel does not support memory swappiness"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871842559Z" level=warning msg="Your kernel does not support kernel memory limit"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871852976Z" level=warning msg="Your kernel does not support kernel memory TCP limit"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871863071Z" level=warning msg="Your kernel does not support cgroup cpu shares"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871964310Z" level=warning msg="Your kernel does not support cgroup cfs period"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.871995988Z" level=warning msg="Your kernel does not support cgroup cfs quotas"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872008967Z" level=warning msg="Your kernel does not support cgroup rt period"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872018596Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872028305Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872038236Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872048198Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872058373Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872069617Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872080656Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Dec 11 18:15:16 virtbio dockerd[12570]: time="2019-12-11T18:15:16.872344786Z" level=info msg="Loading containers: start."
Dec 11 18:15:17 virtbio dockerd[12570]: time="2019-12-11T18:15:17.051084353Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 11 18:15:17 virtbio dockerd[12570]: time="2019-12-11T18:15:17.102947664Z" level=info msg="Loading containers: done."
Dec 11 18:15:17 virtbio dockerd[12570]: time="2019-12-11T18:15:17.152997381Z" level=info msg="Docker daemon" commit=633a0ea838 graphdriver(s)=overlay2 version=19.03.5
Dec 11 18:15:17 virtbio dockerd[12570]: time="2019-12-11T18:15:17.153130891Z" level=info msg="Daemon has completed initialization"
Dec 11 18:15:17 virtbio dockerd[12570]: time="2019-12-11T18:15:17.200237828Z" level=info msg="API listen on /run/docker.sock"
Dec 11 18:15:17 virtbio systemd[1]: Started Docker Application Container Engine.

==> container status <==
sudo: crictl: command not found
CONTAINER ID        IMAGE                      COMMAND                  CREATED             STATUS              PORTS               NAMES
6bcdd8407ebe        hello-world                "/hello"                 3 days ago          Created                                 vigorous_lehmann
3784f6fae4f3        google/deepvariant:0.9.0   "/opt/deepvariant/bi…"   3 days ago          Created                                 agitated_edison

==> dmesg <==
[ +10.587742] kauditd_printk_skb: 15 callbacks suppressed
[ +28.958656] kauditd_printk_skb: 10 callbacks suppressed
[Dec11 18:06] kauditd_printk_skb: 21 callbacks suppressed
[Dec11 18:10] kauditd_printk_skb: 2 callbacks suppressed
[ +32.556617] kauditd_printk_skb: 21 callbacks suppressed
[Dec11 18:11] systemd-fstab-generator[8163]: x-systemd.device-timeout ignored for zeus.home.decanha-knight.net:/volume1/Downloads
[  +4.108107] kauditd_printk_skb: 49 callbacks suppressed
[  +4.534621] systemd-fstab-generator[8897]: x-systemd.device-timeout ignored for zeus.home.decanha-knight.net:/volume1/Downloads
[  +1.436859] kauditd_printk_skb: 32 callbacks suppressed
[ +25.134985] kauditd_printk_skb: 20 callbacks suppressed
[Dec11 18:15] kauditd_printk_skb: 82 callbacks suppressed
[  +2.929876] systemd-fstab-generator[12787]: x-systemd.device-timeout ignored for zeus.home.decanha-knight.net:/volume1/Downloads
[ +10.651049] kauditd_printk_skb: 153 callbacks suppressed
[Dec11 18:16] kauditd_printk_skb: 13 callbacks suppressed
[  +6.103188] kauditd_printk_skb: 2 callbacks suppressed
[  +0.929812] systemd-fstab-generator[13856]: x-systemd.device-timeout ignored for zeus.home.decanha-knight.net:/volume1/Downloads
[  +1.838811] systemd-fstab-generator[14267]: x-systemd.device-timeout ignored for zeus.home.decanha-knight.net:/volume1/Downloads
[Dec11 18:17] kauditd_printk_skb: 62 callbacks suppressed
[  +5.250084] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250006] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249897] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249604] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250399] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249968] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249905] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249941] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250056] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250039] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249620] kauditd_printk_skb: 18 callbacks suppressed
[Dec11 18:18] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249965] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250151] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249817] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250054] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249804] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249981] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249797] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250279] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249968] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250011] kauditd_printk_skb: 18 callbacks suppressed
[Dec11 18:19] kauditd_printk_skb: 20 callbacks suppressed
[  +5.249998] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249766] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250315] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249981] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249929] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249801] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249992] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249957] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250349] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249977] kauditd_printk_skb: 18 callbacks suppressed
[Dec11 18:20] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249998] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249797] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250326] kauditd_printk_skb: 18 callbacks suppressed
[  +5.250021] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249951] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249838] kauditd_printk_skb: 18 callbacks suppressed
[  +5.249750] kauditd_printk_skb: 18 callbacks suppressed
[  +5.018839] kauditd_printk_skb: 28 callbacks suppressed

==> kernel <==
 18:20:43 up 16 min,  2 users,  load average: 0.19, 0.26, 0.18
Linux virtbio 5.3.14-300.fc31.x86_64 #1 SMP Mon Dec 2 15:41:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Fedora 31 (Server Edition)"

==> kubelet <==
-- Logs begin at Sat 2019-12-07 16:10:02 GMT, end at Wed 2019-12-11 18:20:43 GMT. --
Dec 11 18:20:41 virtbio kubelet[20628]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:41 virtbio kubelet[20628]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:41 virtbio kubelet[20628]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:41 virtbio kubelet[20628]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:41 virtbio kubelet[20628]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:41 virtbio kubelet[20628]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:41 virtbio kubelet[20628]: I1211 18:20:41.579097   20628 server.go:416] Version: v1.17.0
Dec 11 18:20:41 virtbio kubelet[20628]: I1211 18:20:41.579692   20628 plugins.go:100] No cloud provider specified.
Dec 11 18:20:41 virtbio kubelet[20628]: I1211 18:20:41.579748   20628 server.go:821] Client rotation is on, will bootstrap in background
Dec 11 18:20:41 virtbio kubelet[20628]: F1211 18:20:41.579831   20628 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Dec 11 18:20:41 virtbio systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 18:20:41 virtbio systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 11 18:20:42 virtbio systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Dec 11 18:20:42 virtbio systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 295.
Dec 11 18:20:42 virtbio systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 11 18:20:42 virtbio systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:42 virtbio kubelet[20651]: I1211 18:20:42.337290   20651 server.go:416] Version: v1.17.0
Dec 11 18:20:42 virtbio kubelet[20651]: I1211 18:20:42.337786   20651 plugins.go:100] No cloud provider specified.
Dec 11 18:20:42 virtbio kubelet[20651]: I1211 18:20:42.337821   20651 server.go:821] Client rotation is on, will bootstrap in background
Dec 11 18:20:42 virtbio kubelet[20651]: F1211 18:20:42.337920   20651 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Dec 11 18:20:42 virtbio systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 18:20:42 virtbio systemd[1]: kubelet.service: Failed with result 'exit-code'.
Dec 11 18:20:42 virtbio systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Dec 11 18:20:42 virtbio systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 296.
Dec 11 18:20:42 virtbio systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Dec 11 18:20:42 virtbio systemd[1]: Started kubelet: The Kubernetes Node Agent.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Dec 11 18:20:43 virtbio kubelet[20708]: I1211 18:20:43.101119   20708 server.go:416] Version: v1.17.0
Dec 11 18:20:43 virtbio kubelet[20708]: I1211 18:20:43.101710   20708 plugins.go:100] No cloud provider specified.
Dec 11 18:20:43 virtbio kubelet[20708]: I1211 18:20:43.101763   20708 server.go:821] Client rotation is on, will bootstrap in background
Dec 11 18:20:43 virtbio kubelet[20708]: F1211 18:20:43.101826   20708 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Dec 11 18:20:43 virtbio systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Dec 11 18:20:43 virtbio systemd[1]: kubelet.service: Failed with result 'exit-code'.

</details>

**The operating system version**:
Fedora 31. Docker 19.03.5

**Comment by tstromberg** [comment]
Do you mind sharing the actual output of `minikube start`? It's tricky to see what's going on here, as the logs here are something that can also be seen for a few seconds in a healthy cluster during  the bootstrapping state.

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
