### ISSUE TITLE
Minikube crashes on Preparing Kubernetes v1.17.0 on Docker '19.03.5'

### ISSUE THREAD

**Issue by VovaBobyr** [kubernetes/minikube#6065]
During the first start minikube it crashed.
VM was created and remains in a running state.
Minikube was installed with choco tool. 
minikube version: v1.6.0
commit: 11630973e5aacb8f16d706f97683bf70fffcba3b

It failed with error:
.kube/config: timeout acquiring mutex

**The exact command to reproduce the issue**:
minikube start --vm-driver=virtualbox

**The full output of the command that failed**:<details>
# minikube start --vm-driver=virtualbox
minikube v1.6.0 on Microsoft Windows 10 Enterprise 2016 LTSB 10.0.14393 Build 14393
Selecting 'virtualbox' driver from user configuration (alternates: [hyperv])
Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
Starting existing virtualbox VM for "minikube" ...
Waiting for the host to be provisioned ...
Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...

X Failed to setup kubeconfig: writing kubeconfig: Error writing file C:\Users\<>/.kube/config: error acquiring lock for C:\Users\<>/.kube/config: timeout acquiring mutex

Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
</details>

**The output of the `minikube logs` command**:folder log is empty.

**The operating system version**:
Windows 10 Enterprise 2016 LTSB
version 1607
Processor:
Intel(R) Core(TM) m3-7Y30 1GHz 1.61 GHz
RAM: 4 GB

**Comment by henzeb** [comment]
Be aware that kubernetes v1.17.0 supports up to Docker 18.09.9. 

you should downgrade to that version.

On linux (for anyone coming across this: remove docker, use the official repo and execute the following:
apt-get install docker-ce*=5:18.09.9~3-0~ubuntu-bionic

**Comment by tstromberg** [comment]
My apologies for the issue: this was apparently due to #6058 - which was introduced in minikube v1.6.0 and fixed in v1.6.1. 

Marking this as a resolved duplicate.
