### ISSUE TITLE
VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor.

### ISSUE THREAD

**Issue by yekolla** [kubernetes/minikube#6074]
C:\Kubernetes>minikube.exe start
There is a newer version of minikube available (v1.6.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.6.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
* minikube v1.1.1 on windows (amd64)
* Downloading Minikube ISO ...
 131.29 MB / 131.29 MB [============================================] 100.00% 0s
* Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E1212 17:23:18.176817   63976 start.go:529] StartHost: create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)

X Unable to start VM
* Error:         [VM_BOOT_FAILED_HYPERV_ENABLED] create: precreate: This computer is running Hyper-V. VirtualBox won't boot a 64bits VM when Hyper-V is activated. Either use Hyper-V as a driver, or disable the Hyper-V hypervisor. (To skip this check, use --virtualbox-no-vtx-check)
* Advice:        Disable Hyper-V when you want to run VirtualBox to boot the VM
* Related issues:
  - https://github.com/kubernetes/minikube/issues/4051

* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new

I am getting the above error, Can you please help on this.

**Comment by henzeb** [comment]
as it states, disable he hypervisor.... it's a service under windows. Also, you should start using minikube 1.6.1 1.1.1 is an old version.

**Comment by tstromberg** [comment]
Do you mind first upgrading to `minikube v1.6.1` and seeing how things  work there?

I suggest first running `minikube delete` before you upgrade, as the VM and configs have changed quite a bit since v1.1 was released.
