### ISSUE TITLE
Minikube 1.6.1 Windows installer generates anti virus warning

### ISSUE THREAD

**Issue by daneel3001** [kubernetes/minikube#6078]
Hello

Just a heads'up that I just tried to install Minikube on Windows 10 Pro and that triggered an anti virus warning.
Please see below screenshot:

![image](https://user-images.githubusercontent.com/570729/70734086-dbefe800-1d0b-11ea-8ad9-79f92120e6a5.png)

**Comment by tstromberg** [comment]
Thanks for the heads up! It looks like this was Windows Defender, and hopefully a false positive.

I double checked with VirusTotal, and see that it seems clean other than what likely seems to be a false positive from Qihoo-360: https://www.virustotal.com/gui/file/09e307c2b9582c107b1cdc80b0f99ff9d294a1907386e3cb07ab82082ff9cd43/detection

Oddly, v1.6.0 didn't have any such false positive. Anyone have an insight here?

**Comment by daneel3001** [comment]
Hello

I just installed 1.6.1 on Windows 10 Pro (insider/slow) and didn't get any warning.
I will check the next computer if I do still get that warning though too it got updated to insider/slow so could be false positive that I can no longer repro now.

**Comment by daneel3001** [comment]
Hello again

I think unless there has been any more such reports it would make sense to catalog that as a false positive.

Thanks

**Comment by iliangithub** [comment]
2024, and... do we have any answer ? I tried do execute it, and Smart Screen from Windows Defender doesn't let me do it...

What's the point in downloading it using Chocolatey if, after all, im installing the same Minikube, with the same issue.
