### ISSUE TITLE
High Sierra: Error in driver during machine creation: hyperkit crashed! 

### ISSUE THREAD

**Issue by swastik123** [kubernetes/minikube#6079]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>
when i am trying to start minikube with minikube start --vm-driver=hyperkit command ,i am getting below error.

minikube v1.6.1 on Darwin 10.13.6
✨  Selecting 'hyperkit' driver from existing profile (alternates: [])
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...

Please guide 
</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
Probably related: #5780

Do you mind sharing the output of `hyperkit -version` and `ls -la /usr/local/bin/hyperkit`? 

My bet is that upgrading to the latest of whatever installed hyperkit (Docker or homebrew) will fix this.

**Comment by swastik123** [comment]
I reinstalled hyperkit and It worked.

Thanks

**Comment by tstromberg** [comment]
Great news. Thank you for the update!

**Comment by kosmoit** [comment]
seems like although latest version is installed,  minikube is still using an old one?

brew upgrade hyperkit
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
ammonite-repl   cppcheck        ghq             peco            tectonic
binaryen        cppunit         gmic            python@2        vice
cmake           embulk          hugo            serverless

Warning: hyperkit 0.20190802 already installed
c02wc0l2htdg:~ williamgreene$ minikube start --wait=false
😄  minikube v1.6.2 on Darwin 10.14.6
✨  Selecting 'hyperkit' driver from existing profile (alternates: [virtualbox vmwarefusion])

⚠️  'hyperkit' driver reported an issue: the installed hyperkit version (0.20180403) is older than the minimum recommended version (0.20190201)
💡  Suggestion: Run 'brew upgrade hyperkit'
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/

💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing hyperkit VM for "minikube" ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [HYPERKIT_CRASHED] start: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
💡  Suggestion: Hyperkit is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --vm-driver
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6079
    ▪ https://github.com/kubernetes/minikube/issues/5780

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by adirks-ata** [comment]
> seems like although latest version is installed, minikube is still using an old one?
> 
> brew upgrade hyperkit
> Updating Homebrew...
> ==> Auto-updated Homebrew!
> Updated 1 tap (homebrew/core).
> ==> Updated Formulae
> ammonite-repl cppcheck ghq peco tectonic
> binaryen cppunit gmic python@2 vice
> cmake embulk hugo serverless
> 
> Warning: hyperkit 0.20190802 already installed
> c02wc0l2htdg:~ williamgreene$ minikube start --wait=false
> 😄 minikube v1.6.2 on Darwin 10.14.6
> ✨ Selecting 'hyperkit' driver from existing profile (alternates: [virtualbox vmwarefusion])
> 
> ⚠️ 'hyperkit' driver reported an issue: the installed hyperkit version (0.20180403) is older than the minimum recommended version (0.20190201)
> 💡 Suggestion: Run 'brew upgrade hyperkit'
> 📘 Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/
> 
> 💡 Tip: Use 'minikube start -p ' to create a new cluster, or 'minikube delete' to delete this one.
> 🔄 Starting existing hyperkit VM for "minikube" ...
> 
> 💣 Unable to start VM. Please investigate and run 'minikube delete' if possible
> ❌ Error: [HYPERKIT_CRASHED] start: hyperkit crashed! command line:
> hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
> 💡 Suggestion: Hyperkit is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --vm-driver
> ⁉️ Related issues:
> ▪ #6079
> ▪ #5780
> 
> 😿 If the above advice does not help, please let us know:
> 👉 https://github.com/kubernetes/minikube/issues/new/choose

I had the same issues on Mac OS, though resolved it by simply updating Docker (since I had skipped multiple updates in the past).

**Comment by davidmpatterson** [comment]
This is *still* an issue. OS: Mac Sonoma. Uninstalled/reinstalled hyperkit: crash. Restart system: crash.

**Comment by gayatrisarnobat** [comment]
We can use the default Docker driver for Minikube on macOS Apple Silicon chips. To do this, we need to install the arm64 version of Minikube and start it with the default Docker driver.

1. First uninstall the existing Minikube setup by executing 
`brew uninstall minikube`

2. Remove the ".minikube" directory:
`rm -rf ~/.minikube`

3. Install the arm64 version of Minikube:
`curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-darwin-arm64 && sudo install minikube-darwin-arm64 /usr/local/bin/minikube`

4. Run Minikube:
`minikube start --driver=docker`

The above setup works on macOS Sequoia Version 15.0.1, Apple M2 Chip.
