### ISSUE TITLE
Support image secret and docker config.json customization for minikube

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/minikube#6080]
**The exact command to reproduce the issue**:
minikube start, and when I want to create k8s deployment resource with thirdparty image registry, I need to create image secret inside k8s and create .docker/config.json inside minikube machine.

Is there anyway to customize this, and avoid to manual operation for creating image secret and config.json.

Thanks.

**The full output of the command that failed**:<details>
None

</details>

**The output of the `minikube logs` command**:<details>

None

</details>

**The operating system version**: MacOS Mojave 10.14.6

**Comment by tstromberg** [comment]
https://minikube.sigs.k8s.io/docs/tasks/sync/ might be helpful here - it provides a way to overwrite files within the minikube VM every time you start the cluster. As far as a feature goes, I'd be open to any proposals you might have.

**Comment by Colstuwjx** [comment]
I have tried `sync` feature, it works well!

But k8s still prompt me that I need to create the image secret by some pull errors. I think leave this job to minikube is hard to implement, since we need one image secret for each namespace.

As a result, I'd like to use the `sync` feature to sync docker config, and just create the image secret by manually or by some PaaS platform.

Thanks for your reply, minikube is awesome!
