### ISSUE TITLE
minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: bad response code: 401

### ISSUE THREAD

**Issue by russoz** [kubernetes/minikube#6085]
**The exact command to reproduce the issue**:
downloaded minikube 1.6.1
ran minikube start
tried changing the vm-driver (default was hyperkit) to virtualbox
minikube delete
minikube start -> same error

**The full output of the command that failed**:<details>
$ minikube start
😄  minikube v1.6.1 on Darwin 10.15.2
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
💿  Downloading VM boot image ...

💣  Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: bad response code: 401

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

Downloading that image with wget works perfectly

</details>

**The output of the `minikube logs` command**:<details>
$ minikube logs

💣  Error getting config: stat /Users/aznamensky/.minikube/profiles/minikube/config.json: no such file or directory

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64 i386 MacBookPro14,3 Darwin

**Comment by tstromberg** [comment]
Do you mind sharing the output of:

`curl -vvv https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256` 

Google Storage appears to have been returning a 401 Unauthorized, though I'm not sure why. In the mean time, you can download the ISO manually from either GitHub or Google Storage and place the result into `~/.minikube/cache/iso/` to workaround the error.


Related: #4774

**Comment by russoz** [comment]
Hi Thomas,

The curl output:
```
$ curl -vvv https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256
*   Trying 216.58.203.112...
* TCP_NODELAY set
* Connected to storage.googleapis.com (216.58.203.112) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-ECDSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.storage.googleapis.com
*  start date: Nov 13 09:07:08 2019 GMT
*  expire date: Feb  5 09:07:08 2020 GMT
*  subjectAltName: host "storage.googleapis.com" matched cert's "*.googleapis.com"
*  issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fb367000000)
> GET /minikube/iso/minikube-v1.6.0.iso.sha256 HTTP/2
> Host: storage.googleapis.com
> User-Agent: curl/7.64.1
> Accept: */*
>
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200
< x-guploader-uploadid: AEnB2UowXoHhGI6wXZSkaCAaJAuz4DLHY4xfIL-5qLwBObX1s3qa8igpl_naesK82KPiFYSJJEGC5YbXNhVFSskxraMTHm_4KA
< expires: Tue, 17 Dec 2019 04:24:59 GMT
< date: Tue, 17 Dec 2019 03:24:59 GMT
< last-modified: Wed, 11 Dec 2019 00:23:48 GMT
< etag: "7887ab0611aebc0cdb66c03dcd8e71a4"
< x-goog-generation: 1576023828416621
< x-goog-metageneration: 1
< x-goog-stored-content-encoding: identity
< x-goog-stored-content-length: 65
< content-type: application/octet-stream
< content-language: en
< x-goog-hash: crc32c=KTF4OA==
< x-goog-hash: md5=eIerBhGuvAzbZsA9zY5xpA==
< x-goog-storage-class: STANDARD
< accept-ranges: bytes
< content-length: 65
< server: UploadServer
< cache-control: public, max-age=3600
< age: 2194
< alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q050=":443"; ma=2592000,h3-Q049=":443"; ma=2592000,h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
<
a24153a2e49f082d5f4a36ea5d1608cba2482d563e8642a8dffd6560c40f3ed2
* Connection #0 to host storage.googleapis.com left intact
* Closing connection 0
```

I will place the file in the cache directory as you indicated.

Thanks

**Comment by tstromberg** [comment]
Any luck?

**Comment by russoz** [comment]
hi Thomas, sorry for not posting back earlier: manually copying the file worked fine, I was able to start the cluster. Thanks for the tip.

**Comment by tstromberg** [comment]
Related: #4774

**Comment by priyawadhwa** [comment]
Hey @russoz it seems this issue is resolved so I'm going to go ahead and close it. If you run into any more issues please reopen at any time by including `/reopen` in your comment!

**Comment by joseph-ravenwolfe** [comment]
Manually downloading and moving the `.iso` resolved one of the issues. But I also encountered this when trying to download the hyperkit driver. Removing an old `~/.netrc` file generated resolved the issue for me.

**Comment by Sanyamgrover1** [comment]
> 
> 
> Do you mind sharing the output of:
> 
> `curl -vvv https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256`
> 
> Google Storage appears to have been returning a 401 Unauthorized, though I'm not sure why. In the mean time, you can download the ISO manually from either GitHub or Google Storage and place the result into `~/.minikube/cache/iso/` to workaround the error.
> 
> Related: #4774

/reopen

Where to copy in case if am trying to move the iso file in Windows OS..? I have created a Kubernetes folder in C drive which has the minikube.exe. 

while running minikube start in cmd, I am getting checksum error same as mentioned in this thread.
