### ISSUE TITLE
Error getting host status: state: machine does not exist

### ISSUE THREAD

**Issue by irshad-amp** [kubernetes/minikube#6087]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by irshad-amp** [comment]
*
X Error getting host status: state: machine does not exist
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by tstromberg** [comment]
What operating system and hypervisor are you using?

This can happen if there is a minikube VM that was removed from outside of minikube. Generally `minikube delete` will fix this.

**Comment by priyawadhwa** [comment]
Hey @irshad-amp, hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
