### ISSUE TITLE
minikube crashed

### ISSUE THREAD

**Issue by touseef777** [kubernetes/minikube#6088]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>

Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-addon-manager ["51e03bccf44b"]:
    error: no objects paINFO: == Reconciling with addon-manager label ==
❌  Problems detected in kube-addon-manager ["19343f7287e7"]:
    error: error when retrieving current configuration of:
</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
ubuntu 18.04

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by priyawadhwa** [comment]
Hey @touseef777 I'm going to close this issue --  there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Additionally, the latest version of minikube removes the `kube-addon-manager` so upgrading to the [latest releast](https://github.com/kubernetes/minikube/releases/tag/v1.7.0-beta.1) could resolve your issue. If it doesn't, please comment on this thread or open another issue. Thank you!
