### ISSUE TITLE
start deletes existing VM on error starting VM

### ISSUE THREAD

**Issue by daewok** [kubernetes/minikube#6099]
`minikube start` deletes an existing VM (without any prompt) if there is a problem starting the VM. This was observed using the VirtualBox driver. This should not happen as it can cause data loss *and* configures the new VM differently than the original VM. In this particular case, there was a transient failure starting the VM as the VirtualBox version was out of sync with its kernel modules. 

**The exact command to reproduce the issue**:
`minikube start`
(My default profile is `work-minikube`).

**The full output of the command that failed**:<details>
😄  [work-minikube] minikube v1.6.1 on Gentoo 2.6
✨  Selecting 'virtualbox' driver from existing profile (alternates: [kvm2])
👍  Kubernetes 1.17.0 is now available. If you would like to upgrade, specify: --kubernetes-version=1.17.0
🔄  Starting existing virtualbox VM for "work-minikube" ...
🔄  Retriable failure: start: Unable to start the VM: /usr/bin/VBoxManage startvm work-minikube --type headless failed:
VBoxManage: error: The virtual machine 'work-minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

Details: 15:01:51.198451 Console: Machine state changed to 'PoweredOff'
🔥  Deleting "work-minikube" in virtualbox ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
</details>

**The operating system version**:
Gentoo, Minikube 1.6.1, VirtualBox 6.0.14

**Comment by broomerr** [comment]
The same for me with minikube v1.5.2

**Comment by tstromberg** [comment]
minikube VM's are designed to be ephemeral. They will in fact lose data every time you reboot your host.

That said, this behavior is kind of icky and should be up for further discussion.

**Comment by daewok** [comment]
Sure, some data will lost on reboot, but secrets and PVs hang around and that's what I'm mostly concerned about.

**Comment by tstromberg** [comment]
NOTE: We reverted this behavior in v1.7.
