### ISSUE TITLE
none on v1.2.0: Error restarting cluster: waiting for apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by halulunyan** [kubernetes/minikube#6100]
root@halulu-VirtualBox:~/.minikube/logs# minikube start
* minikube v1.2.0 on linux (amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Restarting existing none VM for "minikube" ...
* Waiting for SSH access ...
* Configuring environment for Kubernetes v1.15.0 on Docker 19.03.5
  - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
* Relaunching Kubernetes v1.15.0 using kubeadm ...

X Error restarting cluster: waiting for apiserver: timed out waiting for the condition

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

[minikube.log](https://github.com/kubernetes/minikube/files/3971382/minikube.log)

**Comment by tstromberg** [comment]
Do you mind upgrading to minikube v1.6.1? It does a better job of handling apiserver issues.

If it still fails, can you please include the output of:

* `kubectl get po -A`
* `minikube logs`

Thanks!

**Comment by medyagh** [comment]
@halulunyan do you still have this issue ?

**Comment by medyagh** [comment]
@halulunyan I will close this issue, please feel free to reopen if you still face this issue.
