### ISSUE TITLE
Sorry that minikube crashed. If this was unexpected

### ISSUE THREAD

**Issue by Raja1090** [kubernetes/minikube#6102]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by surajsunrays** [comment]
sunrays@sunrays-Vostro-3580:~/Downloads/hashicorp-vault/vault-guides/identity/vault-agent-k8s-demo$ export K8S_HOST=$(minikube ip)

💣  Error getting config: stat /home/sunrays/.minikube/profiles/minikube/config.json: no such file or directory

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

Getting this while trying to get the minikube ip.

**Comment by tstromberg** [comment]
@raea1090 - Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=1` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by priyawadhwa** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
