### ISSUE TITLE
hyperv: NewVM:  NotSpecified: (:) [New-VM], VirtualizationException

### ISSUE THREAD

**Issue by pradeepbavirisetty** [kubernetes/minikube#6104]
Hi Team,
I have tried to run minikube in virtualbox and hyperv in windows 10 but i am unable to start the minikube in both the servers. below commands are used in both hyperv and virtualbox.

Virtual box:
**$> minikube start --vm-driver=virtualbox**
output:
Virtual image gets created in virtual box but its asking minikube login and password while opening the image.

Hyper v:

**$> minikube start --vm-driver hyperv --cpus 4 --memory=4096 --hyperv-virtual-switch "Hyper V Switch"**
* minikube v1.6.1 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Selecting 'hyperv' driver from user configuration (alternates: [virtualbox])
* Creating hyperv VM (CPUs=4, Memory=4096MB, Disk=20000MB) ...
E1217 17:48:30.257478   21700 main.go:106] libmachine: [stderr =====>] : Hyper-V\New-VM : Creating the virtual machine failed.
At line:1 char:1
+ Hyper-V\New-VM minikube -Path '\.minikube\machines\m ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.NewVM

* Retriable failure: create: creating: exit status 1
E1217 17:48:40.959954   21700 main.go:106] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
E1217 17:49:03.406675   21700 main.go:106] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

**Comment by tstromberg** [comment]
minikube doesn't have a login or password, so I'm not sure about the VirtualBox issue.

As far as the Hyper-V issue, do you mind sharing the output of:

`minikube start --vm-driver hyperv --alsologtostderr -v=1`

Thank you.

**Comment by priyawadhwa** [comment]
Hey @pradeepbavirisetty are you still seeing this issue?

**Comment by kmcdon03** [comment]
I have this problem...

**Comment by sharifelgamal** [comment]
@kmcdon03 could you provide the output of 

`minikube start --vm-driver hyperv --alsologtostderr -v=1`

that will give us more logs to go on.

**Comment by LCvijovic09** [comment]
Just wanted to comment on what helped me, in case someone has the same issue as I had. Few easy steps:
 1. Delete folder ".minikube" located under WIndows`s User folder
 2. In powershell (started as admin) run minikube delete (THIS WILL DELETE ALL IMAGES IN CACHE)
 3. Run again minikube start --vm-driver hyperv

One more side note,  I had also two Hyper-V Switches with same name and renamed one so they are all unique. I did it before doing above steps. Not sure if it had any impact.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!

**Comment by ACure4IT** [comment]
/reopen

I ran into this issue following this tutorial...

https://medium.com/jsonlovesyaml/12-step-tutorial-to-setup-kubernetes-on-your-windows-10-laptop-b7784b2253ce

When I get back from BK i'll follow up w/ what sharifelgamal suggested as well as try what LCvijovic09 has suggested.

**Comment by ACure4IT** [comment]
Well just adding the --alsologtostderr -v=1 tag ... or running it a second time seems to have resolved the issue somehow.  If interested I can send the output of that...
