### ISSUE TITLE
Update kubeadm api version from v1beta1 to v1beta2

### ISSUE THREAD

**Issue by Colstuwjx** [kubernetes/minikube#6106]
**The exact command to reproduce the issue**:
this issue was part of #6103, and the exact command was `/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml\"`

**The full output of the command that failed**:<details>

...
🚜  拉取镜像 ...
❌  无法拉取映像，有可能是正常状况：running cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml\"": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm config images pull --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1
stdout:

stderr:
W1217 08:28:08.405830    2817 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W1217 08:28:08.406353    2817 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W1217 08:28:08.407869    2817 validation.go:28] Cannot validate kube-proxy config - no validator is available
W1217 08:28:08.407887    2817 validation.go:28] Cannot validate kubelet config - no validator is available
failed to pull image "k8s.gcr.io/kube-apiserver:v1.17.0": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 10.0.2.3:53: no such host
, error: exit status 1
To see the stack trace of this error execute with --v=5 or higher
...

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**: MacOS mojave

**Comment by Colstuwjx** [comment]
According to the output prompted, we may need to run `kubeadm config migrate --old-config old.yaml --new-config new.yaml'`, and using the new configuration spec for generating `/var/tmp/minikube/kubeadm.yaml`.

**Comment by tstromberg** [comment]
Thanks for the heads up. We'll need to do this for v1.18 support.

If you or anyone is interested in helping out with this, your intuition is correct. The steps that need to be performed here are:

* Use `minikube ssh` and run `kubeadm config migrate --old-config /var/tmp/minikube/kubeadm.yaml --new-config  /var/tmp/minikube/v1beta2.yaml`
* Run `diff -ubB /var/tmp/minikube/kubeadm.yaml /var/tmp/minikube/v1beta2.yaml` to inspect the changes.
* Copy the `var configTmplV1Beta1` template to a new `var configTmplV1Beta2` template:

https://github.com/kubernetes/minikube/blob/35fd034896b75282988d1ff8ebf01d220898e8d6/pkg/minikube/bootstrapper/kubeadm/templates.go#L99

* Apply the changes you found into the `configTmplV1Beta2` template you just created
* Copy this logic to tell minikube to use this template for v1.17.0 or higher:
 https://github.com/kubernetes/minikube/blob/0ca6c6c4c6f6ee71ae89be219db5b4061da2162b/pkg/minikube/bootstrapper/kubeadm/kubeadm.go#L775

* Run `make` and `minikube start` to confirm that  minikube works as expected
* Run `make test` to make sure no tests broke
* Send out PR

Thanks!

**Comment by RubenBaez** [comment]
/assign

I will help with this

**Comment by LindaLawton** [comment]
does anyone have a fix for this?  i tried running minikube ssh but i dont appear to have a v1beta2.yaml file.

**Comment by RubenBaez** [comment]
Yes. It is working on that. Some adjustments are being made to the
templates for this change reaches the master branch
