### ISSUE TITLE
Failed to cache ISO: http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by msetodev** [kubernetes/minikube#6107]
minikube start --vm-driver=hyperv

<details>

X Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256: http: server gave HTTP response to HTTPS client

</details>

<details>

PS C:\Work\PowerShell> minikube logs
*
X Error getting config: CreateFile C:\Users\me\.minikube\profiles\minikube\config.json: The system cannot find the path specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:

OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299

Notes: I have set the proxy I am supposed to use using set HTTP_PROXY and set HTTPS_PROXY. I have also tried passing them with --docker-env flags but same issue.

**Comment by tstromberg** [comment]
The error message indicates that a HTTPS_PROXY is being set to a plain HTTP proxy. Can you double check that the HTTPS_PROXY setting is the same as you are using elsewhere for HTTPS?

**Comment by msetodev** [comment]
I was able to fix my proxy settings in environment variables. The trick was closing and opening a new PowerShell session for it to take effect. Thank you!
