### ISSUE TITLE
Error downloading checksum file: remote error: tls: access denied

### ISSUE THREAD

**Issue by sanjay-batra** [kubernetes/minikube#6108]
I have been trying to start minikube on Windows 2019. it fails to download the releases.json file and also the ISO to create the HyperV VM
===============================================================
PS C:\Users\Administrator> minikube.exe start --alsologtostderr -v=8
I1217 09:01:40.739581    3608 notify.go:125] Checking for updates...
W1217 09:01:40.816579    3608 notify.go:56] Error getting json from minikube version url: error with http GET for endpoint https://storage.googleapis.com/minikube/releases.json: Get https://storage.googleapis.com/minikube/releases.json: remote error: tls: access denied
I1217 09:01:40.830581    3608 start.go:255] hostinfo: {"hostname":"WIN-FDESBQ0LDA7","uptime":976,"bootTime":1576593924,"procs":149,"os":"windows","platform":"Microsoft Windows Server 2019 Standard","platformFamily":"Server","platformVersion":"10.0.17763 Build 17763","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"cd1ceecc-ae5a-4ea8-b916-677d1be7b7fb"}
W1217 09:01:40.830581    3608 start.go:263] gopshost.Virtualization returned error: not implemented yet
! minikube v1.6.1 on Microsoft Windows Server 2019 Standard 10.0.17763 Build 17763
I1217 09:01:40.831580    3608 start.go:557] selectDriver: flag="", old=<nil>
I1217 09:01:40.831580    3608 global.go:60] Querying for installed drivers using PATH=C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\\SUT\bin;c:\Kube;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps:C:\kube;
I1217 09:01:42.892578    3608 global.go:68] hyperv priority: 6, state: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I1217 09:01:42.906578    3608 global.go:68] virtualbox priority: 4, state: {Installed:false Healthy:false Error:unable to find VBoxManage in $PATH Fix:Install VirtualBox Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/}
I1217 09:01:42.913578    3608 global.go:68] vmware priority: 5, state: {Installed:false Healthy:false Error:exec: "docker-machine-driver-vmware": executable file not found in %PATH% Fix:Install docker-machine-driver-vmware Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/}
I1217 09:01:42.913578    3608 driver.go:109] requested: ""
I1217 09:01:42.913578    3608 driver.go:132] "hyperv" has a higher priority (6) than "" (0)
I1217 09:01:42.913578    3608 driver.go:146] Picked: hyperv
I1217 09:01:42.913578    3608 driver.go:147] Alternatives: []
* Automatically selected the 'hyperv' driver (alternates: [])
I1217 09:01:42.913578    3608 start.go:297] selected driver: hyperv
I1217 09:01:42.914580    3608 start.go:587] validating driver "hyperv" against <nil>
I1217 09:01:44.410579    3608 start.go:593] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I1217 09:01:44.410579    3608 downloader.go:81] full url: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256
* Downloading VM boot image ...
W1217 09:01:44.543587    3608 exit.go:101] Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256: remote error: tls: access denied
*
X Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256: remote error: tls: access denied
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
===============================================================
Here is the docker and minikube version
===============================================================
PS C:\Users\Administrator> minikube.exe version
minikube version: v1.6.1
commit: 42a9df4854dcea40ec187b6b8f9a910c6038f81a

PS C:\Users\Administrator> docker version
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:37 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
PS C:\Users\Administrator>
===============================================================
Proxy is set correctly as I can pull the images from docker hub.
===============================================================
PS C:\Users\Administrator> docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine
89d9c30c1d48: Pull complete
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:latest
docker.io/library/alpine:latest
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
While the proxy may be setup properly for Docker, it does not appear to be setup properly for other Go programs like minikube. You'll need to configure the proxy as per:

https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

It is interesting that the proxy in your case is responding with `access denied`. I've never seen that before.

**Comment by sanjay-batra** [comment]
Tried as per the link shared by you. 
=============================================
PS C:\Kube> set HTTP_PROXY=http://<proxy url:port>
PS C:\Kube> set HTTPS_PROXY=http://<proxy url:port>
PS C:\Kube> set NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
PS C:\Kube> .\minikube.exe start --alsologtostderr
W1218 22:20:11.728844   13508 root.go:241] Error reading config file at C:\Users\Administrator\.minikube\config\config.json: open C:\Users\Administrator\.minikube\config\config.json: The system cannot find the file specified.
I1218 22:20:11.734843   13508 notify.go:125] Checking for updates...
W1218 22:20:11.812844   13508 notify.go:56] Error getting json from minikube version url: error with http GET for endpoint https://storage.googleapis.com/minikube/releases.json: Get https://storage.googleapis.com/minikube/releases.json: remote error: tls: access denied
I1218 22:20:11.818844   13508 start.go:255] hostinfo: {"hostname":"WIN-FDESBQ0LDA7","uptime":135287,"bootTime":1576593924,"procs":154,"os":"windows","platform":"Microsoft Windows Server 2019 Standard","platformFamily":"Server","platformVersion":"10.0.17763 Build 17763","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"cd1ceecc-ae5a-4ea8-b916-677d1be7b7fb"}
W1218 22:20:11.818844   13508 start.go:263] gopshost.Virtualization returned error: not implemented yet
! minikube v1.6.1 on Microsoft Windows Server 2019 Standard 10.0.17763 Build 17763
I1218 22:20:11.819844   13508 start.go:557] selectDriver: flag="", old=<nil>
I1218 22:20:11.819844   13508 global.go:60] Querying for installed drivers using PATH=C:\ProgramData\DockerDesktop\version-bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\\SUT\bin;c:\Kube;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps:C:\kube;
I1218 22:20:13.980849   13508 global.go:68] hyperv priority: 6, state: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I1218 22:20:13.994849   13508 global.go:68] virtualbox priority: 4, state: {Installed:false Healthy:false Error:unable to find VBoxManage in $PATH Fix:Install VirtualBox Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/}
I1218 22:20:14.000849   13508 global.go:68] vmware priority: 5, state: {Installed:false Healthy:false Error:exec: "docker-machine-driver-vmware": executable file not found in %PATH% Fix:Install docker-machine-driver-vmware Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/}
I1218 22:20:14.001849   13508 driver.go:109] requested: ""
I1218 22:20:14.001849   13508 driver.go:146] Picked: hyperv
I1218 22:20:14.001849   13508 driver.go:147] Alternatives: []
* Automatically selected the 'hyperv' driver (alternates: [])
I1218 22:20:14.002850   13508 start.go:297] selected driver: hyperv
I1218 22:20:14.002850   13508 start.go:587] validating driver "hyperv" against <nil>
I1218 22:20:15.504850   13508 start.go:593] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I1218 22:20:15.505849   13508 downloader.go:81] full url: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256
* Downloading VM boot image ...
W1218 22:20:15.636843   13508 exit.go:101] Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256: remote error: tls: access denied
*
X Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256: remote error: tls: access denied
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
=============================================
Also tried to manually download the files that minikube is trying to download using curl and it works perfectly. No sure why minikube fails to do the same thing.

PS C:\Kube> curl https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso -o minikube-v1.6.0.iso
PS C:\Kube> curl https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256 -o minikube-v1.6.0.iso.sha256
PS C:\Kube> curl https://storage.googleapis.com/minikube/releases.json -o releases.json
PS C:\Kube> dir


    Directory: C:\Kube


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       12/13/2019   8:27 PM       43563520 kubectl.exe
-a----       12/11/2019   2:59 PM         265118 logo.ico
**-a----       12/18/2019   9:20 PM      158261248 minikube-v1.6.0.iso**
**-a----       12/18/2019  10:18 PM             65 minikube-v1.6.0.iso.sha256**
-a----       12/11/2019   2:59 PM       46510080 minikube.exe
**-a----       12/18/2019  10:18 PM          18438 releases.json**
-a----       12/13/2019   9:27 PM         428340 uninstall.exe
-a----       12/11/2019   2:59 PM           2982 update_path.ps1

**Comment by tstromberg** [comment]
It appears that your proxy is still denying access :( Are you running this at home, or within a business? If the latter, I recommend checking with your IT department on the appropriate proxy configuration to use.

As a workaround, you can download the ISO to `C:\Users\Administrator.minikube\cache\iso` and it won't attempt to fetch. You may run into other errors though later when it comes time to download images.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by medyagh** [comment]
@johnnyfriendly I will close this issue due to no update, and sorry to hear you had this issue, please feel free to reopen.

meanwhile I recommend to give our newest driver a try in latest release
```
minikube start --vm-driver=docker
```
that might solve your issue !
