### ISSUE TITLE
Error downloading kubelet: A connection attempt failed because the connected party did not properly respond

### ISSUE THREAD

**Issue by NikhilSarda** [kubernetes/minikube#6109]
**The exact command to reproduce the issue**: minikube start --vm-driver=virtualbox

**The full output of the command that failed**:<details>
* minikube v1.5.2 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E1217 21:31:20.101836   13560 cache_images.go:80] CacheImage k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 -> C:\Us
ers\Nikhil\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13 failed: fetching image: Get https:/
/k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io: no such host
* Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
E1217 21:33:04.898863   13560 start.go:799] Error caching images:  Caching images for kubeadm: caching images:
 caching image C:\Users\Nikhil\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13: fetching image
: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io: no such host
* Unable to load cached images: loading cached images: loading image C:\Users\Nikhil\.minikube\cache\images\k8
s.gcr.io\k8s-dns-sidecar-amd64_1.14.13: CreateFile C:\Users\Nikhil\.minikube\cache\images\k8s.gcr.io\k8s-dns-s
idecar-amd64_1.14.13: The system cannot find the file specified.
* Downloading kubelet v1.16.2
*
X Failed to update cluster: downloading binaries: downloading kubelet: Error downloading kubelet v1.16.2: fail
ed to download: failed to download to temp file: failed to copy contents: read tcp 192.168.0.106:61314->172.21
7.166.176:443: wsarecv: A connection attempt failed because the connected party did not properly respond after
 a period of time, or established connection failed because connected host has failed to respond.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**: windows 10

**Comment by tstromberg** [comment]
minikube needs access to the internet to download the required images and binaries the first time.

Does your machine require an HTTP proxy to access the internet? If so, you will need to configure it: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

**Comment by priyawadhwa** [comment]
Hey @NikhilSarda are you still seeing this issue?

**Comment by NikhilSarda** [comment]
@priyawadhwa Haven't checked yet. Will check and let you know soon.

**Comment by priyawadhwa** [comment]
Hey @NikhilSarda any updates here?

**Comment by priyawadhwa** [comment]
Hey @NikhilSarda --

Hopefully it's OK if I close this, as some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.


Thank you for sharing your experience!
