### ISSUE TITLE
problem command minikube addons enable heapster

### ISSUE THREAD

**Issue by rezabojnordi** [kubernetes/minikube#6115]
**کامندی که مشکل را به وجود می آورد**:
minikube addons enable heapster
**خروجی کامل کامند مورد مشکل:**:<details>
*
X enable failed: property name "heapster" not found
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs` خروجی کامل دسستور**: <details>

</details>

**سیستم عامل مورد استفاده با ذکر ورژن**:
ubuntu 18.04

**Comment by tstromberg** [comment]
heapster support was retired:

https://github.com/kubernetes/minikube/pull/5243

Is this addon something you still need support for?

**Comment by rezabojnordi** [comment]
No I watched a tutorial using this module, do you have a replacement?

**Comment by tstromberg** [comment]
Heapster was retired in preference to metrics-server in Kubernetes v1.11:

https://github.com/kubernetes-retired/heapster/blob/master/docs/deprecation.md

**Comment by rezabojnordi** [comment]
thank you very much
