### ISSUE TITLE
Document upgrading a cluster

### ISSUE THREAD

**Issue by robrich** [kubernetes/minikube#6122]
Now that https://github.com/kubernetes/minikube/pull/5798 is merged, and `minikube start` doesn't auto-upgrade, how do I upgrade my cluster?  Will `minikube start --kubernetes-version ...` upgrade it or dump the VM and start over?  (and consume all the bandwidth as I download base images again.) Is there a `minikube start --kubernetes-version stable` or `minikube start --kubernetes-version latest` that will auto-upgrade the cluster?

Perhaps we need a docs page to answer this.

**Comment by tstromberg** [comment]
`minikube start --kubernetes-version=v1.17.0` will upgrade you, without re-downloading the VM image. That said, the base VM image is only ~120MB compared to the ~600MB it takes to download a new Kubernetes release.

We don't yet support 'stable' or 'latest' designators, but it would certainly be a great feature to add. If you or anyone else is interested in making this work, add a check for `paramVersion == "stable"` here:

https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start.go#L1127

As far as docs, I agree. I'd be happy to review any PR that adds it. Here is where I would probably put it: https://github.com/kubernetes/minikube/tree/master/site/content/en/docs/Tasks

**Comment by tstromberg** [comment]
Also worth noting, this is the message users should see if there is an upgrade available:

`out.T(out.ThumbsUp, "Kubernetes {{.new}} is now available. If you would like to upgrade, specify: --kubernetes-version={{.new}}`

That doesn't invalidate the issues you've raised, just showing the guidance we are currently providing, as the documentation should match it.

**Comment by sharifelgamal** [comment]
We've added the documentation for this, I'm going to go ahead and close this. Feel free to reopen if necessary.

**Comment by life5ign** [comment]
Where is this in the docs?  I can't find it.
