### ISSUE TITLE
failed to copy contents: read tcp wsarecv: A connection attempt failed because the connected party did not properly respond

### ISSUE THREAD

**Issue by gitsilos** [kubernetes/minikube#6123]
In windows 10  home , minikube start failed

C:\Users\usanc>minikube start
* minikube v1.6.1 on Microsoft Windows 10 Home 10.0.18362 Build 18362
* Selecting 'virtualbox' driver from existing profile (alternates: [])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Using the running virtualbox "minikube" VM ...
* Waiting for the host to be provisioned ...
* Found network options:
  - NO_PROXY=192.168.99.100,192.168.99.101
  - no_proxy=192.168.99.100,192.168.99.101
* Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
  - env NO_PROXY=192.168.99.100,192.168.99.101
  - env NO_PROXY=192.168.99.100,192.168.99.101
* Downloading kubeadm v1.17.0
* Downloading kubelet v1.17.0
*
X Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.17.0: failed to download: failed to download to temp file: failed to copy contents: read tcp [2606:a000:81c5:1e00:349a:26c0:7ea6:bbf1]:55317->[2607:f8b0:4004:815::2010]:443: wsarecv: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tdevilleduc** [comment]
I'm behind a corporate proxy and I'm using this no_proxy minimum :
NO_PROXY="localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24,192.168.39.0/24"

**Comment by tstromberg** [comment]
You are going to need to set an HTTPS_PROXY environment variable. See the documentation here:

https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

Do you mind reporting back if this fixes the issue for you?

**Comment by priyawadhwa** [comment]
Hey @gitsilos are you still seeing this issue?

**Comment by gitsilos** [comment]
I took a course from kodekloud and their labs are easy to work. The windows
version of Kubernetes on Minikube is strange. I am spending too much on
troubleshooting. I stopped working on minikube after i raised the defect

So KodeKloud has been good to work on my short term objectives.

**Comment by priyawadhwa** [comment]
Hey @gitsilos sorry to hear that. I'll go ahead and close this issue if you're no longer using minikube. If you ever decide to try minikube again, please reopen at any time by commenting `/reopen` on this thread.
