### ISSUE TITLE
Build new image for gvisor addon as part of each release

### ISSUE THREAD

**Issue by wmuizelaar** [kubernetes/minikube#6146]
Recently https://github.com/kubernetes/minikube/pull/6000 was merged to allow a new gvisor version to be used with the addon.

This was released with v1.16.0, but the image that containts the addon was never rebuilt, as the latest date shown on gcr.io/k8s-minikube/gvisor-addon is still 26 Oct 2019.

What is needed to get a new image being pushed to the registry?

**Comment by tstromberg** [comment]
I've pushed a new build manually by running:

`make push-gvisor-addon-image`

Clearly we do a bad job of remembering to this by hand. I'll send a PR out shortly that adds this to the automated release process.

**Comment by tstromberg** [comment]
Thank you for bringing this to our attention!

**Comment by afbjorklund** [comment]
This will rebuild the image using the same GVISOR_IMAGE_VERSION

This might mean we end up with multiple images with the _same_ tag.

But as long as either will work, I guess it is OK.

"Increment when there are breaking changes."
