### ISSUE TITLE
macOS Catalina hyperkit crashed (not Retriable)

### ISSUE THREAD

**Issue by movd** [kubernetes/minikube#6149]
**The exact command to reproduce the issue**: 
```sh
$ brew install hyperkit
$ minikube start --vm-driver=hyperkit
```

**The full output of the command that failed**:<details>
```sh
😄  minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'hyperkit' driver from user configuration (alternates: [vmware virtualbox vmwarefusion])
💾  Downloading driver docker-machine-driver-hyperkit:
    > docker-machine-driver-hyperkit.sha256: 65 B / 65 B [---] 100.00% ? p/s 0s
    > docker-machine-driver-hyperkit: 10.81 MiB / 10.81 MiB  100.00% 1.49 MiB p
🔑  The 'hyperkit' driver requires elevated permissions. The following commands will be executed:

    $ sudo chown root:wheel /Users/moritz/.minikube/bin/docker-machine-driver-hyperkit
    $ sudo chmod u+s /Users/moritz/.minikube/bin/docker-machine-driver-hyperkit


💿  Downloading VM boot image ...
    > minikube-v1.6.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.6.0.iso: 150.93 MiB / 150.93 MiB [] 100.00% 10.59 MiB p/s 15s
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [HYPERKIT_CRASHED] create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
💡  Suggestion: Hyperkit is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --vm-driver
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6079
    ▪ https://github.com/kubernetes/minikube/issues/5780

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

</details>

**The output of the `minikube logs` command**:<details>
```sh
💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp :22: connect: connection refused

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```
</details>

**The operating system version**:  iMac 2019 running macOS 10.15.2 (19C57)

This error looks different from #5780 as minikube does not even produces a `Retriable failure`. 
I guess something is up with `hyperkit`.  I also have issues with Docker for Mac and created a issue over there. 

I tried rebooting, reinstalling Docker for mac (also latest Edge) and uninstalling Docker and just installing `brew install hyperkit`

My hyperkit version (latest from brew)
```sh
$ hyperkit -v
hyperkit: 0.20190802

Homepage: https://github.com/docker/hyperkit
License: BSD
```

**Comment by fundon** [comment]
Same too.

**Comment by rhockman** [comment]
I had the same issue.  I needed to:

1. brew update && brew upgrade
1. Install the latest Docker Desktop for Mac

It works for me now.

**Comment by David-Kunz** [comment]
Hi, I have the same issue. Upgrading brew and reinstalling docker did not help.

**Comment by movd** [comment]
This sadfully didn't help. My `brew`package are up to date and installed the latest Docker for Mac (Edge) `2.1.7.0`

**Comment by chipsfingrar** [comment]
> I had the same issue. I needed to:
> 
> 1. brew update && brew upgrade
> 2. Install the latest Docker Desktop for Mac
> 
> It works for me now.

Upgrading Docker Desktop solved the issue for me.

**Comment by digital-bhaskar** [comment]
Facing same issue. Uninstalled all hyperkit, minikube related packages.
Please let me know what I am missing.
bash-3.2$ brew list.  <<-- See empty list returned
bash-3.2$ 
bash-3.2$ rm -rf ~/.minikube/
bash-3.2$ brew install hyperkit
==> Installing dependencies for hyperkit: libev
==> Installing hyperkit dependency: libev
==> Downloading https://homebrew.bintray.com/bottles/libev-4.31.catalina.bottle.tar.gz
Already downloaded: /Users/myUserName/Library/Caches/Homebrew/downloads/40c2c3aabdcb02d2ae3f6e85d8a2b8687fbf62fca2729aa7501367185974afa9--libev-4.31.catalina.bottle.tar.gz
==> Pouring libev-4.31.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/libev/4.31: 12 files, 451.3KB
==> Installing hyperkit
==> Downloading https://homebrew.bintray.com/bottles/hyperkit-0.20190802.catalina.bottle.tar.gz
Already downloaded: /Users/myUserName/Library/Caches/Homebrew/downloads/8a593971ef71eeae2dc5c0da6e3cf695f497837ba2dff70c109d63a42f6d4452--hyperkit-0.20190802.catalina.bottle.tar.gz
==> Pouring hyperkit-0.20190802.catalina.bottle.tar.gz
🍺  /usr/local/Cellar/hyperkit/0.20190802: 5 files, 4.0MB
bash-3.2$ brew install minikube
==> Installing dependencies for minikube: kubernetes-cli
==> Installing minikube dependency: kubernetes-cli
==> Downloading https://homebrew.bintray.com/bottles/kubernetes-cli-1.17.0.catalina.bottle.tar.gz
Already downloaded: /Users/myUserName/Library/Caches/Homebrew/downloads/279b7cc265c340bcb1db67b2cef4b07fa56b147eeb4bc594a349a299f6cdb63a--kubernetes-cli-1.17.0.catalina.bottle.tar.gz
==> Pouring kubernetes-cli-1.17.0.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/kubernetes-cli/1.17.0: 235 files, 49MB
==> Installing minikube
==> Downloading https://homebrew.bintray.com/bottles/minikube-1.6.2.catalina.bottle.tar.gz
Already downloaded: /Users/myUserName/Library/Caches/Homebrew/downloads/2cc2ac6632464b9d513472f734c1fef8785bfe1bc98bfafa100feb2509aa96c1--minikube-1.6.2.catalina.bottle.tar.gz
==> Pouring minikube-1.6.2.catalina.bottle.tar.gz
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> Summary
🍺  /usr/local/Cellar/minikube/1.6.2: 8 files, 51.5MB
==> Caveats
==> kubernetes-cli
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
==> minikube
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions have been installed to:
  /usr/local/share/zsh/site-functions
bash-3.2$ minikube start
😄  minikube v1.6.2 on Darwin 10.15.1
✨  Automatically selected the 'hyperkit' driver (alternates: [])
💾  Downloading driver docker-machine-driver-hyperkit:
    > docker-machine-driver-hyperkit.sha256: 65 B / 65 B [---] 100.00% ? p/s 0s
    > docker-machine-driver-hyperkit: 10.81 MiB / 10.81 MiB  100.00% 306.20 KiB
🔑  The 'hyperkit' driver requires elevated permissions. The following commands will be executed:

    $ sudo chown root:wheel /Users/myUserName/.minikube/bin/docker-machine-driver-hyperkit 
    $ sudo chmod u+s /Users/myUserName/.minikube/bin/docker-machine-driver-hyperkit 


Password:
💿  Downloading VM boot image ...
    > minikube-v1.6.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.6.0.iso: 150.93 MiB / 150.93 MiB [-] 100.00% 4.29 MiB p/s 35s
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [HYPERKIT_CRASHED] create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
💡  Suggestion: Hyperkit is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --vm-driver
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6079
    ▪ https://github.com/kubernetes/minikube/issues/5780

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by jwsy** [comment]
I was able to get past this by installing the latest version of Docker Desktop 2.1.0.5 (40693)

```
$ minikube start --vm-driver=hyperkit
😄  minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'hyperkit' driver from user configuration (alternates: [virtualbox])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing hyperkit VM for "minikube" ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [HYPERKIT_CRASHED] start: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
💡  Suggestion: Hyperkit is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --vm-driver
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6079
    ▪ https://github.com/kubernetes/minikube/issues/5780

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

### Installed Docker Desktop 2.1.0.5 (40693)

$ minikube start --vm-driver=hyperkit
😄  minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'hyperkit' driver from user configuration (alternates: [virtualbox])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing hyperkit VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
🚀  Launching Kubernetes ...
🏄  Done! kubectl is now configured to use "minikube"
```

**Comment by medyagh** [comment]
@movd  does upgrading the docker for desktop fix this issue ?

**Comment by mattforni** [comment]
Steps to fix:

**Comment by mattforni** [comment]
Upgrading docker for desktop and running `minikube delete` fixed me.

**Comment by movd** [comment]
> @movd does upgrading the docker for desktop fix this issue ?

Hey no tried this many times but it didn't help

**Comment by tstromberg** [comment]
If you are still running into this, it would be useful to hear if `--driver=docker` helps to unblock you.

**Comment by movd** [comment]
This was a hardware issue. After I got Apple to replace my logic board virtualization via hyperkit works perfectly. Thanks to everyone who helped in debugging this.
