### ISSUE TITLE
Trim kic base image

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6152]
as seen in this PR https://github.com/kubernetes/minikube/pull/6151
Currently KIC base image is based on kindest/node:v1.16.2

The following has to be done : 

- Delete all the images inside the container (600MB) 

I tried to do 
```
crictl images -q | xargs -n 1 crictl rmi 2>/dev/null
```
in Dockerfile but however for that containerd needs to be up and running which during docker build image it is not !

so I need help with that.

**Comment by afbjorklund** [comment]
To actually make the image _smaller_, you have to avoid the layer that adds them in the first place.
This might require going back to the Dockerfile that KIND is using, and forking from there instead...

https://github.com/kubernetes-sigs/kind/blob/master/pkg/build/node/node.go
https://github.com/kubernetes-sigs/kind/tree/master/images/base

```Dockerfile
# start from ubuntu 19.10, this image is reasonably small as a starting point
# for a kubernetes node image, it doesn't contain much we don't need
FROM ubuntu:19.10
```

**Comment by medyagh** [comment]
@afbjorklund that is the real solution ! however the build process seemed to be longer than I liked to.

I meant this issue as a quick win, ( just go inside the image and delete anything kind related)

I would be happy to close this issue, if anyone wants to do it from scratch.

**Comment by medyagh** [comment]
this issue was closed by the PR https://github.com/kubernetes/minikube/pull/6478
