### ISSUE TITLE
Create a minikube native default CNI for kic 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6153]
I need help to make as mall CNI plugin for kic but native to minikube.

currently using kindnet
https://github.com/kubernetes/minikube/blob/d26fdd997b44a077e57cdc770dfaf6347d38f9c2/pkg/minikube/bootstrapper/kicbs/cni.go#L20

**Comment by medyagh** [comment]
I nominate @josedonizetti please feel free to decline.

**Comment by tstromberg** [comment]
What's wrong with kindnet?

**Comment by medyagh** [comment]
not needed
