### ISSUE TITLE
docker ps: open machines\minikube\ca.pem: The system cannot find the file specified.

### ISSUE THREAD

**Issue by manoj629** [kubernetes/minikube#6155]
**The exact command to reproduce the issue**:
minikube start
docker ps

**The full output of the command that failed**:<details>

unable to resolve docker endpoint: open C:\Users\XXXX\.minikube\machines\minikube\ca.pem: The system cannot find the file specified.
<img width="664" alt="Minikube_error" src="https://user-images.githubusercontent.com/16397357/71365001-078d9080-259e-11ea-9f6a-0a3969b27cac.PNG">

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.

Thank you for sharing your experience!

**Comment by gmariotti** [comment]
Hi, I'm currently having the same problem with macOS 10.15.3. The list of commands I'm running with their respective output is the following

```
$ minikube start --memory 4096
😄  minikube v1.7.2 on Darwin 10.15.3
✨  Automatically selected the hyperkit driver
🔥  Creating hyperkit VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
⚠️  Node may be unable to resolve external DNS records
⚠️  VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
🐳  Preparing Kubernetes v1.17.2 on Docker 19.03.5 ...
🚀  Launching Kubernetes ...
🌟  Enabling addons: default-storageclass, storage-provisioner
⌛  Waiting for cluster to come online ...
🏄  Done! kubectl is now configured to use "minikube"

$ eval (minikube docker-env)

$ docker ps
unable to resolve docker endpoint: open /Users/guido.mariotti/.docker/ca.pem: no such file or directory
```

I'm using fish as a shell, and the same behavior occurs if I use `--vm-driver=virtualbox`
