### ISSUE TITLE
hyperv delete: Failed to delete cluster: exit status 1

### ISSUE THREAD

**Issue by SarathChandra24** [kubernetes/minikube#6157]
**minikube delete**:

**The full output of the command that failed**:<details>
* Deleting "minikube" in hyperv ...
*
X Failed to delete cluster: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**: windows 10 pro version 1909
![Screenshot (101)](https://user-images.githubusercontent.com/39090092/71398766-8559a680-2647-11ea-92a3-626f3df28ba9.png)

**Comment by tstromberg** [comment]
What version of minikube is this? Do you mind sharing the output of:

`minikube delete --alsologtostderr -v=3`

That should tell us what command is failing. Thank you!

**Comment by priyawadhwa** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
