### ISSUE TITLE
'minikube stop options' not work

### ISSUE THREAD

**Issue by sesky4** [kubernetes/minikube#6165]
**The exact command to reproduce the issue**:
`minikube stop options`

**The full output of the command that failed**:
`
 ➜  ~ minikube stop options

✋  Stopping "minikube" in hyperkit ...

🛑  "minikube" stopped.
`

**Expected**:
`
➜  Desktop minikube stop -h
Stops a local kubernetes cluster running in Virtualbox. This command stops the VM
itself, leaving all files intact. The cluster can be started again with the "start" command.

Usage:
  minikube stop [flags] [options]

Use "minikube stop options" for a list of global command-line options (applies to all commands).
`

**Version**:
`
➜  Desktop minikube version

minikube version: v1.5.2

commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad
`

**The operating system version**:
`
➜  Desktop uname -rsv

Darwin 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
`

By the way, is there any way to only start the 'Docker Host' instead of 'Docker Host' + 'Kubelet' + 'apiserver'?
Because it consume 50+% cpu while idle which cause a lot of heat on my notebook :)

**Comment by afbjorklund** [comment]
Looks like the auto-generated help text (for "options") is not working properly...

You can use Docker Machine instead of minikube, if all you want is Docker ?

**Comment by afbjorklund** [comment]
I think that help text this imported from "k8s.io/kubectl/pkg/util/templates" :

[k8s.io/kubernetes/staging/src/k8s.io/kubectl/pkg/util/templates/templates.go](https://github.com/kubernetes/kubernetes/blob/8c3b7d7679cc/staging/src/k8s.io/kubectl/pkg/util/templates/templates.go#L68)

**Comment by afbjorklund** [comment]
It is being called through templates.ActsAsRootCommand -> HelpFunc -> templateFuncs optionsCmdFor

[k8s.io/kubernetes/staging/src/k8s.io/kubectl/pkg/util/templates/templater.go](https://github.com/kubernetes/kubernetes/blob/8c3b7d7679cc/staging/src/k8s.io/kubectl/pkg/util/templates/templater.go#L184_L196)

**Comment by priyawadhwa** [comment]
Hey @sesky4 you can use the `minikube pause` and `minikube unpause` commands to pause kubernetes in minikube. Your application will continue to run, but kubernetes will be paused until you unpause it. This should reduce your overhead by a good amount.
