### ISSUE TITLE
nested VirtualBox: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

### ISSUE THREAD

**Issue by danfakha** [kubernetes/minikube#6180]
Enable to start minikube on my Ubuntu 18.04 (Started within virtualBox) Virtual Machine hosted by Win 10. 
VirtualBox is already installed on my  Ubuntu VM
![Annotation 2019-12-30 100440](https://user-images.githubusercontent.com/58121932/71577388-d0facd00-2aeb-11ea-8dee-ba3f71c9a570.png)

 
$ minikube start 

**The full output of the command that failed**:<details>

$ minikube start 

😄  minikube v1.6.2 on Ubuntu 18.04
✨  Selecting 'virtualbox' driver from existing profile (alternates: [none])
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
💡  Suggestion: Virtualization support is disabled on your computer.

</details>

**The output of the `minikube logs` command**:<details>

</details>

Ubuntu 18.04

**Comment by tstromberg** [comment]
You can try `minikube start --no-vtx-check` to disable this check. If it fails, I recommend running minikube on Windows directly, or trying your own VirtualBox image within your Ubuntu 18.04 image to see if it works first.

Please let me know what you find out.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by medyagh** [comment]
@danfakha  I will close this issue due to no update, and sorry to hear you had this issue, please feel free to reopen.

meanwhile I recommend to give our newest driver a try in latest release

minikube start --vm-driver=docker
that might solve your issue !
