### ISSUE TITLE
kubeadm init phase certs: Process exited with status 1

### ISSUE THREAD

**Issue by alimurtuza** [kubernetes/minikube#6184]
**The exact command to reproduce the issue**:
X Error starting cluster: running cmd: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1
stdout:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.

Thank you for sharing your experience!

**Comment by medyagh** [comment]
@alimurtuza I haveb't heard from you, I will close this issue, please feel free to re-open if you have any update or still have the issue.
