### ISSUE TITLE
 VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository

### ISSUE THREAD

**Issue by alimurtuza** [kubernetes/minikube#6186]
**The exact command to reproduce the issue**:
 VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by medyagh** [comment]
@alimurtuza I haven't heard any update from you, I will close this issue for now, please feel free to re-open if needed.

**Comment by medyagh** [comment]
@alimurtuza I haven't heard any update from you, I will close this issue for now, please feel free to re-open if needed.
