### ISSUE TITLE
Suggestion: Remove helm-tiller from addons list

### ISSUE THREAD

**Issue by eisraeli** [kubernetes/minikube#6187]
Hi all,

Now that [Helm 3](https://helm.sh/blog/helm-3-released/) has been released, shouldn't the use of Helm 2 (and Tiller) be discouraged ? Doesn't it make the helm-tiller addon obsolete? (since finally, there is no need for Tiller anymore)

**The exact command to reproduce the issue**:
minikube addons list

**Comment by afbjorklund** [comment]
They have the same adoption plan as python, so it might be around "for a while":
https://helm.sh/blog/2019-10-22-helm-2150-released/

> As Helm moves towards Helm 3’s first release, Helm 2 is now transitioning into “maintenance mode”. Helm 2.15.0 will be the final feature release for Helm 2.

So I suppose it will be around for a year, even though the add-on might be removed sooner.

> 12 months after Helm 3’s public release, support for Helm 2 will formally end.

**Comment by afbjorklund** [comment]
The "helm-tiller" addon is fairly new (#5363), mostly to avoid having to run `helm init`.

@woodcockjosh  and @medyagh might have more ideas about the helm3 integration.

**Comment by tstromberg** [comment]
Closing, as we plan to keep helm-tiller around for users until it is  unsupported (November 2020). There still are many Helm 2 users unfortunately, but it should be a much smoother transition than Python at least =)
