### ISSUE TITLE
ImagePullBackOff after Kubectl run

### ISSUE THREAD

**Issue by shwetankverma** [kubernetes/minikube#6192]
**The exact command to reproduce the issue**:
kubectl run kubernetes-app --image=jenkins:latest --port=8080

kubectl cluster-info dump

**The full output of the command that failed**:<details>

Generated self-signed cert in-memory W1230 10:20:58.777494 1 configmap_cafile_content.go:102] unable to load initial CA bundle for: "client-ca::kube-system::extension-apiserver-authentication::client-ca-file" due to: configmap "extension-apiserver-authentication" not found W1230 10:20:58.778005 1 configmap_cafile_content.go:102] unable to load initial CA bundle for: "client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file" due to: configmap "extension-apiserver-authentication" not found W1230 10:20:58.849619 1 authorization.go:47] Authorization is disabled W1230 10:20:58.850375 1 authentication.go:92] Authentication is disabled

"reason": "Failed", "message": "Failed to pull image\"jenkins:latest\":rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.64.1:53: read udp 192.168.64.3:38558-\u003e192.168.64.1:53: read: connection refused", "source": { "component": "kubelet", "host": "minikube" }

</details>

**The output of the `minikube logs` command**:<details>
Error syncing pod 7dbc7dcc-c697-42e4-b5c0-ab7f2b071837 ("kubernetes-jenkins-6cfc8464cf-q2vs7_default(7dbc7dcc-c697-42e4-b5c0-ab7f2b071837)"), skipping: failed to "StartContainer" for "kubernetes-jenkins" with ImagePullBackOff: "Back-off pulling image \"jenkins:latest\""

</details>

**The operating system version**:
Mac OS Catalina - 10.15.2 

I am using Minikube for Mac with VM hyperkit. I also have docker-desktop installed (in which I have tried both enable/disable Kubernetes).

docker pull is executed smoothly with no error.

but on Kubectl run I get these errors.

**Comment by tstromberg** [comment]
I believe this may be due to a conflict with a local DNS server - #3036. https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/ mentions this briefly.

Do you mind sharing the output of:

`sudo lsof -i :53`

**Comment by shwetankverma** [comment]
output for - sudo lsof -i :53 :

> COMMAND     PID           USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
> mDNSRespo   242 _mdnsresponder  129u  IPv6 0x39bee29022e24711      0t0  UDP *:domain
> mDNSRespo   242 _mdnsresponder  142u  IPv6 0x39bee29020746901      0t0  TCP *:domain (LISTEN)
> dnscrypt- 24446         nobody    7u  IPv4 0x39bee29022b7f881      0t0  UDP localhost:domain
> dnscrypt- 24446         nobody    8u  IPv4 0x39bee290082e42a9      0t0  TCP localhost:domain (LISTEN)

Also, i am sharing few details like --
when i do -- docker pull gcr.io/google-samples/kubernetes-bootcamp:v1
Output is --

> Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io on 192.168.64.1:53: read udp 192.168.64.3:45883->192.168.64.1:53: read: connection refused

And on -- minikube start --vm-driver=hyperkit
Output is --

> 🎉  minikube 1.6.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.6.2
> 💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'
> 
> 🙄  minikube v1.6.1 on Darwin 10.15.2
> ✨  Selecting 'hyperkit' driver from user configuration (alternates: [virtualbox])
> 💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
> 🔄  Starting existing hyperkit VM for "minikube" ...
> ⌛  Waiting for the host to be provisioned ...
> ⚠️  VM may be unable to resolve external DNS records
> ⚠️  VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
> 🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
> 🚀  Launching Kubernetes ... 
> 🏄  Done! kubectl is now configured to use "minikube"


And eventually on Kubectl run i get imagepullbackoff

**Comment by shwetankverma** [comment]
Any help please

**Comment by tstromberg** [comment]
You will need to turn off the dnscrypt service: 

https://minikube.sigs.k8s.io/docs/reference/drivers/hyperkit/#Issues

Alternatively, you can use `--vm-driver=docker`.
