### ISSUE TITLE
请问etcd的证书位置在哪？ where is the etcd cert location?

### ISSUE THREAD

**Issue by cmdedj** [kubernetes/minikube#6195]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by tstromberg** [comment]
Try:

`minikube ssh "sudo grep cert /etc/kubernetes/manifests/etcd.yaml"`

It should return:

```
    - --cert-file=/var/lib/minikube/certs/etcd/server.crt
    - --client-cert-auth=true
    - --key-file=/var/lib/minikube/certs/etcd/server.key
    - --peer-cert-file=/var/lib/minikube/certs/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/var/lib/minikube/certs/etcd/peer.key
    - --peer-trusted-ca-file=/var/lib/minikube/certs/etcd/ca.crt
    - --trusted-ca-file=/var/lib/minikube/certs/etcd/ca.crt
    - mountPath: /var/lib/minikube/certs/etcd
      name: etcd-certs
      path: /var/lib/minikube/certs/etcd
    name: etcd-certs
```

这有帮助吗？

**Comment by medyagh** [comment]
@cmdedj did the solution mentioned here https://github.com/kubernetes/minikube/issues/6195#issuecomment-572220266 help ?

**Comment by medyagh** [comment]
@cmdedj对这里＃6195（注释）中提到的解决方案有帮助吗？

**Comment by cmdedj** [comment]
minikube ssh "sudo grep cert /etc/kubernetes/manifests/etcd.yaml"
    - --cert-file=/var/lib/minikube/certs/etcd/server.crt
    - --client-cert-auth=true
    - --key-file=/var/lib/minikube/certs/etcd/server.key
    - --peer-cert-file=/var/lib/minikube/certs/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/var/lib/minikube/certs/etcd/peer.key
    - --peer-trusted-ca-file=/var/lib/minikube/certs/etcd/ca.crt
    - --trusted-ca-file=/var/lib/minikube/certs/etcd/ca.crt
    - mountPath: /var/lib/minikube/certs/etcd
      name: etcd-certs
      path: /var/lib/minikube/certs/etcd
    name: etcd-certs
 ~  cat /var/lib/minikube/certs/etcd/server.key
cat: /var/lib/minikube/certs/etcd/server.key: No such file or directory

@medyagh @tstromberg but i cant find it yet

**Comment by priyawadhwa** [comment]
Hey @cmdedj, 你可以尝试

```
 minikube ssh "sudo cat /var/lib/minikube/certs/etcd/server.key"
```

请让我知道这是否有效

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
