### ISSUE TITLE
Update minikube tutorial on kubernetes website  on addons

### ISSUE THREAD

**Issue by MyLanPangzi** [kubernetes/minikube#6196]
https://kubernetes.io/docs/tutorials/hello-minikube/
minikube addons enable heapster
X enable failed: property name "heapster" not found

**Comment by priyawadhwa** [comment]
Hey @MyLanPangzi thanks for opening this issue. It seems we no longer support heapster as an addon. We should update the kubernetes documentation to reflect this.

Thank you for pointing this out!

**Comment by medyagh** [comment]
@MyLanPangzi are you still working on this?

**Comment by priyawadhwa** [comment]
Looks like this has been resolved, I'll go ahead and close this issue.
