### ISSUE TITLE
Kubeconfig

### ISSUE THREAD

**Issue by qclovexmj** [kubernetes/minikube#6201]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by priyawadhwa** [comment]
您好 @qclovexmj 感谢您打开此问题。我还没有明确的方法来复制此问题。您介意添加一些其他详细信息吗？以下是其他有用的信息：

*使用的确切的`minikube start`命令行
* `minikube start`命令的完整输出，最好使用 `--alsologtostderr -v = 4` 来进行额外的日志记录。
 * `minikube logs`
*`kubectl get po -A`的完整输出


感谢您分享经验！

**Comment by priyawadhwa** [comment]
希望我能关闭此按钮就可以了-信息不足以使其无法执行，并且已经过去了一段时间。如果您能够提供其他详细信息，则可以随时在注释中添加/ reopen来重新打开它。

感谢您分享经验！
