### ISSUE TITLE
Failed to use minikube in virtual machine

### ISSUE THREAD

**Issue by jiangyongbing24** [kubernetes/minikube#6203]
**The exact command to reproduce the issue**:
minikube start --vm-driver=none --v=5

**The full output of the command that failed**:<details>

💣  Error starting cluster: apiserver healthz: apiserver healthz never reported healthy

🔄  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-scheduler ["fcac8c8aa338"]:
    Error: unknown flag: --authentication-kubeconfig
    unknown flag: --authentication-kubeconfig

</details>

**The output of the `minikube logs` command**:<details>

Jan 03 16:02:11 localhost.localdomain kubelet[30373]: E0103 16:02:11.475176   30373 kubelet.go:2263] node "minikube" not found

</details>

**The operating system version**:
Installed a CentOS Linux 7 (Core) virtual machine in win10 1809

**Comment by priyawadhwa** [comment]
Hey @jiangyongbing24, I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
