### ISSUE TITLE
Can't start minikube with VPN: Unable to verify SSH connectivity

### ISSUE THREAD

**Issue by Anirudh-AppDirect** [kubernetes/minikube#6204]
I am trying to start Minkube locally but the ssh verification keeps coming in the way....

`minikube start --vm-driver=virtualbox`

`⚠️  Unable to verify SSH connectivity: dial tcp 192.168.99.133:22: i/o timeout. Will retry...
⚠️  Unable to verify SSH connectivity: dial tcp 192.168.99.133:22: i/o timeout. Will retry...`

though 
`minikube ssh`
 works just fine

Is there anyway to turn off the SSH Verification for minikube start? 

**The exact command to reproduce the issue**:  minikube start --vm-driver=virtualbox

**The full output of the command that failed**:<details>
😄  minikube v1.6.2 on Darwin 10.14.6
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit parallels])
💿  Downloading VM boot image ...
    > minikube-v1.6.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.6.0.iso: 150.93 MiB / 150.93 MiB  100.00% 701.92 KiB p/s 3m41
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ HTTP_PROXY=http://PROXY_HOST:8080
    ▪ HTTPS_PROXY=http://PROXY_HOST:8080
    ▪ NO_PROXY=localhost,127.0.0.1,192.168.99.128,192.168.99.129,192.168.99.130,192.168.99.131,192.168.99.132,192.168.99.133,192.168.99.134,192.168.99.135,192.168.99.136,192.168.99.137,192.168.99.138
    ▪ http_proxy=http://PROXY_HOST:8080
    ▪ https_proxy=http://PROXY_HOST:8080
    ▪ no_proxy=localhost,127.0.0.1,192.168.99.128,192.168.99.129,192.168.99.130,192.168.99.131,192.168.99.132,192.168.99.133,192.168.99.134,192.168.99.135,192.168.99.136,192.168.99.137,192.168.99.138
⚠️  Unable to verify SSH connectivity: dial tcp 192.168.99.134:22: i/o timeout. Will retry...
⚠️  Unable to verify SSH connectivity: dial tcp 192.168.99.134:22: i/o timeout. Will retry...
⚠️  Unable to verify SSH connectivity: dial tcp 192.168.99.134:22: i/o timeout. Will retry...
⚠️  Unable to verify SSH connectivity: dial tcp 192.168.99.134:22: i/o timeout. Will retry...
💣  minikube is unable to connect to the VM: dial tcp 192.168.99.134:22: i/o timeout

</details>

**The output of the `minikube logs` command**:<details>

E0103 22:49:54.833754    8046 logs.go:175] Failed to list containers for "kube-apiserver": docker ListContainers. : docker ps -a --filter=name=k8s_kube-apiserver --format="{{.ID}}": Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0103 22:49:54.868594    8046 logs.go:175] Failed to list containers for "coredns": docker ListContainers. : docker ps -a --filter=name=k8s_coredns --format="{{.ID}}": Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0103 22:49:54.902050    8046 logs.go:175] Failed to list containers for "kube-scheduler": docker ListContainers. : docker ps -a --filter=name=k8s_kube-scheduler --format="{{.ID}}": Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0103 22:49:54.939447    8046 logs.go:175] Failed to list containers for "kube-proxy": docker ListContainers. : docker ps -a --filter=name=k8s_kube-proxy --format="{{.ID}}": Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0103 22:49:54.975840    8046 logs.go:175] Failed to list containers for "kube-addon-manager": docker ListContainers. : docker ps -a --filter=name=k8s_kube-addon-manager --format="{{.ID}}": Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0103 22:49:55.010792    8046 logs.go:175] Failed to list containers for "kubernetes-dashboard": docker ListContainers. : docker ps -a --filter=name=k8s_kubernetes-dashboard --format="{{.ID}}": Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0103 22:49:55.043931    8046 logs.go:175] Failed to list containers for "storage-provisioner": docker ListContainers. : docker ps -a --filter=name=k8s_storage-provisioner --format="{{.ID}}": Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
E0103 22:49:55.081127    8046 logs.go:175] Failed to list containers for "kube-controller-manager": docker ListContainers. : docker ps -a --filter=name=k8s_kube-controller-manager --format="{{.ID}}": Process exited with status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
==> Docker <==
-- Logs begin at Fri 2020-01-03 21:48:49 UTC, end at Fri 2020-01-03 21:49:55 UTC. --
-- No entries --

==> container status <==
E0103 22:49:57.145104    8046 logs.go:153] command /bin/bash -c "sudo crictl ps -a || sudo docker ps -a" failed with error: /bin/bash -c "sudo crictl ps -a || sudo docker ps -a": Process exited with status 1
stdout:

stderr:
time="2020-01-03T21:49:57Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
 output: "\n** stderr ** \ntime=\"2020-01-03T21:49:57Z\" level=fatal msg=\"failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded\"\nCannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?\n\n** /stderr **"

==> dmesg <==
[Jan 3 21:48] You have booted with nomodeset. This means your GPU drivers are DISABLED
[  +0.000000] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
[  +0.000001] Unless you actually understand what nomodeset does, you should reboot without enabling it
[  +0.149839] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[ +24.506195] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[ +10.415817] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[  +0.010257] systemd-fstab-generator[1352]: Ignoring "noauto" for root device
[  +0.001759] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000003] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +0.488169] vboxvideo: loading out-of-tree module taints kernel.
[  +0.000039] vboxvideo: Unknown symbol ttm_bo_mmap (err -2)
[  +0.000011] vboxvideo: Unknown symbol ttm_bo_global_release (err -2)
[  +0.000010] vboxvideo: Unknown symbol ttm_bo_manager_func (err -2)
[  +0.000003] vboxvideo: Unknown symbol ttm_bo_global_init (err -2)
[  +0.000008] vboxvideo: Unknown symbol ttm_bo_device_release (err -2)
[  +0.000012] vboxvideo: Unknown symbol ttm_bo_kunmap (err -2)
[  +0.000005] vboxvideo: Unknown symbol ttm_bo_del_sub_from_lru (err -2)
[  +0.000007] vboxvideo: Unknown symbol ttm_bo_device_init (err -2)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_init_mm (err -2)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_dma_acc_size (err -2)
[  +0.000003] vboxvideo: Unknown symbol ttm_tt_init (err -2)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_kmap (err -2)
[  +0.000006] vboxvideo: Unknown symbol ttm_bo_add_to_lru (err -2)
[  +0.000003] vboxvideo: Unknown symbol ttm_mem_global_release (err -2)
[  +0.000003] vboxvideo: Unknown symbol ttm_mem_global_init (err -2)
[  +0.000011] vboxvideo: Unknown symbol ttm_bo_init (err -2)
[  +0.000001] vboxvideo: Unknown symbol ttm_bo_validate (err -2)
[  +0.000005] vboxvideo: Unknown symbol ttm_bo_put (err -2)
[  +0.000004] vboxvideo: Unknown symbol ttm_tt_fini (err -2)
[  +0.000002] vboxvideo: Unknown symbol ttm_bo_eviction_valuable (err -2)
[  +0.017040] vgdrvHeartbeatInit: Setting up heartbeat to trigger every 2000 milliseconds
[  +0.000230] vboxguest: misc device minor 57, IRQ 20, I/O port d020, MMIO at 00000000f0000000 (size 0x400000)
[  +0.251998] hpet1: lost 714 rtc interrupts
[  +0.044857] VBoxService 5.2.32 r132073 (verbosity: 0) linux.amd64 (Jul 12 2019 10:32:28) release log
              00:00:00.001887 main     Log opened 2020-01-03T21:48:55.504706000Z
[  +0.000081] 00:00:00.002010 main     OS Product: Linux
[  +0.000042] 00:00:00.002068 main     OS Release: 4.19.81
[  +0.000036] 00:00:00.002107 main     OS Version: #1 SMP Tue Dec 10 16:09:50 PST 2019
[  +0.000047] 00:00:00.002142 main     Executable: /usr/sbin/VBoxService
              00:00:00.002143 main     Process ID: 2096
              00:00:00.002143 main     Package type: LINUX_64BITS_GENERIC
[  +0.000039] 00:00:00.002191 main     5.2.32 r132073 started. Verbose level = 0
[  +0.507450] hpet1: lost 6 rtc interrupts
[  +0.053736] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +2.120447] systemd-fstab-generator[2350]: Ignoring "noauto" for root device
[  +2.346452] hpet1: lost 283 rtc interrupts
[  +5.002429] hpet1: lost 318 rtc interrupts
[Jan 3 21:49] hpet1: lost 318 rtc interrupts
[  +5.003033] hpet1: lost 318 rtc interrupts
[  +5.004526] hpet1: lost 319 rtc interrupts
[  +5.001747] hpet1: lost 318 rtc interrupts
[  +5.003271] hpet1: lost 318 rtc interrupts
[  +5.001864] hpet1: lost 318 rtc interrupts
[  +5.001966] hpet1: lost 318 rtc interrupts
[  +5.001080] hpet1: lost 318 rtc interrupts
[  +5.001371] hpet1: lost 318 rtc interrupts
[  +5.001839] hpet1: lost 320 rtc interrupts
[  +5.000994] hpet1: lost 318 rtc interrupts

==> kernel <==
 21:49:57 up 1 min,  0 users,  load average: 1.21, 0.67, 0.26
Linux minikube 4.19.81 #1 SMP Tue Dec 10 16:09:50 PST 2019 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2019.02.7"

==> kubelet <==
-- Logs begin at Fri 2020-01-03 21:48:49 UTC, end at Fri 2020-01-03 21:49:57 UTC. --
-- No entries --

💣  Error getting machine logs: unable to fetch logs for: container status

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**: MacOS Mojave

**Comment by tstromberg** [comment]
I fully suspect that you will run into issues with accessing the apiserver endpoint, but in the mean time, I've sent out a PR to add --force support for this check.

You may want to try using the `--vm-driver=hyperkit`, as it natively supports some VPN's.
