### ISSUE TITLE
Minikube VM broken?

### ISSUE THREAD

**Issue by dennisjac** [kubernetes/minikube#6216]
**The exact command to reproduce the issue**:
`minikube start`

**The full output of the command that failed**:<details>
```
$ minikube start
😄  minikube v1.6.2 on Fedora 31
✨  Selecting 'kvm2' driver from user configuration (alternates: [none])
🔥  Creating kvm2 VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: create: Error creating machine: Error in driver during machine creation: machine didn't return an IP after 120 seconds

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

</details>

**The output of the `minikube logs` command**:<details>
```
$ minikube logs 

💣  Error getting config: stat /home/dennis/.minikube/profiles/minikube/config.json: no such file or directory

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

</details>

**The operating system version**:
```
$ cat /etc/fedora-release 
Fedora release 31 (Thirty One)
```
**Remarks**:
When I look at the console after `minikube start` I see the output in the attached screenshot.
![minikube](https://user-images.githubusercontent.com/500583/71808678-b4700f00-306e-11ea-9821-1ce74f787ccb.png)

There are more services that fail among them are also the login and ssh services so I assume that this is the reason why minikube cannot contact the running VM.

**Comment by afbjorklund** [comment]
Are you using an AMD CPU ? There was a systemd bug, that affected the most recent minikube ISO

See #6168

**Comment by dennisjac** [comment]
That is indeed the case. I'm running this on a Ryzen 3700X. I'll close the bug and follow #6168 instead. Thanks!
