### ISSUE TITLE
Minikube requires a delete and then start to be accessible UI

### ISSUE THREAD

**Issue by gtan01** [kubernetes/minikube#6221]
Why does Minikube require delete and then start to be accessible through the UI?

**The exact command to reproduce the issue**:
- "minikube delete"
- "minikube start --vm-driver=hyperv"

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
I don't know. Do you mind providing the output of: `minikube start --vm-driver=hyperv --alsologtostderr`?

We used to automatically delete invalid VM states, but users complained so we reverted the behavior in the latest release.

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
