### ISSUE TITLE
Why does the UI not show "kubernetes-bootcamp" under "default" namespace but instead shows as empty?

### ISSUE THREAD

**Issue by gtan01** [kubernetes/minikube#6225]
I created "kubernetes-bootcamp" deployment using "kubectl create deployment kubernetes-bootcamp --image=gcr.io/google-samples/kubernetes-bootcamp:v1".  The deployment defaulted to "default" namespace.

Why does the UI not show "kubernetes-bootcamp" under "default" namespace but instead shows as empty?

Besides, why can't the drop-down Namespace menu list all name spaces?

**The exact command to reproduce the issue**:
PS C:\WINDOWS\system32> kubectl get deployments -A
NAMESPACE              NAME                        READY   UP-TO-DATE   AVAILABLE   AGE
default                kubernetes-bootcamp         1/1     1            1           114m
kube-system            coredns                     2/2     2            2           4h49m
kubernetes-dashboard   dashboard-metrics-scraper   1/1     1            1           105m
kubernetes-dashboard   kubernetes-dashboard        1/1     1            1           105m

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
What UI are you talking about?

**Comment by priyawadhwa** [comment]
Hey @gtan01 are you referring to UI created by `minikube dashboard`?

**Comment by priyawadhwa** [comment]
Hey @gtan01 --

Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
