### ISSUE TITLE
kvm2: cannot perform external dns queries

### ISSUE THREAD

**Issue by billcrook** [kubernetes/minikube#6229]
On arch-linux, after starting minikube, it cannot resolve DNS queries.

My relevant installed packages:
* minikube
* kubectl
* libvirt
* qemu-headless
* ebtables
* dnsmasq 
* docker
* docker-machine
* docker-machine-driver-kvm2 (AUR)

If I replace `/etc/resolv.conf` with a new config file pointing at `nameserver 1.1.1.1`, everything works fine. This is not optimal however as it is wiped out each time minikube is restarted.

**The exact command to reproduce the issue**:
```
$ minikube start --vm-driver kvm2
...
⚠️  VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
...
🏄  Done! kubectl is now configured to use "minikube"
$ minikube ssh 'ping google.com'
```

**The full output of the command that failed**:
`ping: bad address 'google.com'`

**The output of the `minikube logs` command**:
[mk-logs.out.gz](https://github.com/kubernetes/minikube/files/4032536/mk-logs.out.gz)

**The operating system version**:
```
$ uname -a
Linux 5.4.8-arch1-1 #1 SMP PREEMPT Sat, 04 Jan 2020 23:46:18 +0000 x86_64 GNU/Linux
```

**Comment by tstromberg** [comment]
Does `ping 8.8.8.8` work within the VM? If not, this may be related to #5432

**Comment by tstromberg** [comment]
It isn't a solution, but I did want to make sure you knew about https://minikube.sigs.k8s.io/docs/tasks/sync/ if you wanted a persistent override for any file inside the minikube VM.

**Comment by billcrook** [comment]
> Does ping 8.8.8.8 work within the VM?

Yes. DNS works fine if I update the resolv.conf file.

**Comment by billcrook** [comment]
> It isn't a solution, but I did want to make sure you knew about https://minikube.sigs.k8s.io/docs/tasks/sync/

Thanks, I did not know about that. Funny that the example is to adjust dns - was this built to work around the bug? ;)

**Comment by afbjorklund** [comment]
What the previous contents of the /etc/resolv.conf ? The one that didn’t work (including --status)

Wondering if it is libvirt or systemd that is letting us down here... In the old days, VBox proxied DNS

**Comment by priyawadhwa** [comment]
@billcrook ping!

**Comment by billcrook** [comment]
Sorry - my brand new motherboard decided not to come back to life after a reboot a couple weeks ago. I won't be able to provide the resolve.conf.

**Comment by medyagh** [comment]
@billcrook sorry for the dead motherboard :(

**Comment by medyagh** [comment]
@billcrook If you dont mind I will close this issue and if you can recreate it again , please feel free to re-open

**Comment by cmillani** [comment]
I was having the same problem and (thankfully) found this issue.

Setting `resolv.conf` to `nameserver 1.1.1.1` solved the problem and by using the provided link to always set this value I was able to start minikube without the `this VM is having trouble accessing https://k8s.gcr.io` warning, but I still received `ImagePullBackOff` errors when trying to create a deployment. I had to use `minikube ssh` to change the `resolv.conf` again, and only then I was able to pull images for my deployments.

The default value of my `resolv.conf` is `nameserver 192.168.122.1`, that is the IP of the host on interface `virbr0`.

Also, I'm using `iwd` for both DNS and DHCP, so I only installed `dnsmasq` for the VM. On the `libvirt` arch wiki page it seems like this should not be a problem, but it crossed my mind.

I would love to understand better what could I do solve this error and would be happy to provide any more information!

Should I open another issue?

**Comment by cmillani** [comment]
After seeing that the host was set as the nameserver of the VM I started searching in that direction. I mentioned that not running `dnsmasq` on host should not be a problem but only running `iwd` apparently was :smiley: 

I installed NetworkManager and stopped iwd, and now I can resolve external DNS queries inside the minikube VM without changing the `resolv.conf`

**Comment by billcrook** [comment]
Interesting. I'm was running systemd-networkd when I filed this issue. I wonder what NetworkManager is doing that networkd is not.

**Comment by boguima** [comment]
done - https://minikube.sigs.k8s.io/docs/handbook/addons/ingress-dns/
