### ISSUE TITLE
`minikube kubectl` documentation is incorrect and confusing

### ISSUE THREAD

**Issue by RochesterinNYC** [kubernetes/minikube#6238]
To reproduce:

- I installed minikube via brew on a Mac machine: `brew install minikube`
- I started minikube:

```
$ minikube start
😄  minikube v1.6.2 on Darwin 10.15
✨  Selecting 'hyperkit' driver from existing profile (alternates: [virtualbox])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running hyperkit "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
🚀  Launching Kubernetes ...
🏄  Done! kubectl is now configured to use "minikube"
⚠️  /Users/jameswen/google-cloud-sdk/bin/kubectl is version 1.13.11-dispatcher, and is incompatible with Kubernetes 1.17.0. You will need to update /Users/jameswen/google-cloud-sdk/bin/kubectl or use 'minikube kubectl' to connect with this cluster
```

This presumably sets up my local kubectl to talk to the minikube K8s cluster. However, my local `kubectl version` is outdated as seen by the last output message. I decide to use `minikube kubectl` as the output message suggests.

- I'm able to use `minikube kubectl` to execute kubectl commands that don't require a `--namespace` flag:

```
$ minikube kubectl create namespace testing
💾  Downloading kubectl v1.17.0
namespace/testing created
$ minikube kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
$ minikube kubectl get pods
No resources found in default namespace.
```

- However, I'm not able to use `minikube kubectl` to execute `kubectl` commands that require a `--namespace` flag:

```
$ minikube kubectl get pods --namespace kube-system
Error: unknown flag: --namespace


Usage:
  minikube kubectl [flags] [options]

Use "minikube kubectl options" for a list of global command-line options (applies to all commands).
```

```
$ minikube kubectl get pods -n kube-system
Error: unknown shorthand flag: 'n' in -n


Usage:
  minikube kubectl [flags] [options]

Use "minikube kubectl options" for a list of global command-line options (applies to all commands).
```

```
$ minikube kubectl -n kube-system get pods
Error: unknown shorthand flag: 'n' in -n


Usage:
  minikube kubectl [flags] [options]

Use "minikube kubectl options" for a list of global command-line options (applies to all commands).
```

**Comment by tstromberg** [comment]
To disambiguate between flags being sent to `minikube` and those sent to `kubectl`, some magic is required, which comes by adding '--' to tell minikube's flag parser to stop parsing. For example:

`minikube kubectl -- get pods --namespace kube-system`

This is clearly a documentation fail on our part. `minikube help kubectl` is very confusing:

```
Run the kubernetes client, download it if necessary.
Examples:
minikube kubectl -- --help
kubectl get pods --namespace kube-system
```

**Comment by tstromberg** [comment]
Our docs (auto-generated from the help) double down on this confusion:

https://minikube.sigs.k8s.io/docs/reference/commands/kubectl/

I think this is also some room to make this friendlier, by detecting the issue, or automatically passing flags through. Documentation is a good start though.

**Comment by RochesterinNYC** [comment]
Ah, gotcha, thanks for the context. I was guessing that this was something related to documentation rather than a big functionality like that not working. 

In the help output and the docs, what is the `kubectl get pods --namespace kube-system` line intended to convey ?

Would y'all be open to a PR improving the docs?

**Comment by afbjorklund** [comment]
You can also `brew install kubernetes-cli` to install a local `kubectl` client, but it can be tricky to match up the kubernetes version with the one in the cluster (something that minikube does for you).
