### ISSUE TITLE
hyperv: Ran out of memory (0x8007000E)

### ISSUE THREAD

**Issue by PycMono** [kubernetes/minikube#6249]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by PycMono** [comment]
* Microsoft Windows 10 Pro 10.0.18363 Build 18363 上的 minikube v1.6.2
* Selecting 'hyperv' driver from user configuration (alternates: [virtualbox])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing hyperv VM for "minikube" ...
E0109 14:43:34.865456    8480 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : “minikube”无法启动。
系统内存不足，无法启动虚拟机 minikube。
无法初始化内存: Ran out of memory (0x8007000E)。
“minikube”无法启动。(虚拟机 ID 1910E217-8CB5-4164-8319-8F77D26D3AF0)
系统内存不足，无法启动虚拟机 minikube，需要内存大小 4096 MB。(虚拟机 ID 1910E217-8CB5-4164-8319-8F77D26D3AF0)
“minikube”无法初始化内存: Ran out of memory (0x8007000E)。(虚拟机 ID 1910E217-8CB5-4164-8319-8F77D26D3AF0)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM


*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: start: exit status 1
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
您的计算机有多少物理内存？

minikube需要2GB的可用RAM才能启动VM。 根据错误消息，您可能需要释放一些额外的内存才能启动minikube。

---

How much physical memory does your machine have?

minikube requires 2GB of free RAM to start a VM. Based on the error message, you may need to free up some additional memory to start minikube.

**Comment by sharifelgamal** [comment]
希望如果我关闭此按钮就可以了-信息不足以使其无法执行，并且已经过去了一段时间。如果您能够提供其他详细信息，则可以随时在注释中添加/ reopen来重新打开它。

---

Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
