### ISSUE TITLE
1 log.go:172] http: TLS handshake error from 127.0.0.1:39208: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by soumya2223** [kubernetes/minikube#6250]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by sudheerptt** [comment]
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/security.md  - Try this

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
/triage/support

**Comment by sharifelgamal** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by sumitKash** [comment]
I too am getting this message in my kube-apiserver logs:

I0922 11:31:14.904648       1 log.go:172] http: TLS handshake error from 10.80.10.70:33690: remote error: tls: bad certificate
I0922 11:31:15.050911       1 log.go:172] http: TLS handshake error from 10.80.10.70:33698: remote error: tls: bad certificate

The cluster is sitting behind HAproxy.

K8s version: 1.18.8
Installation method: kubeadm
