### ISSUE TITLE
Changelog for new releases

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/minikube#627]
Hi,

It would be nice to have a change log for new releases on the release pages.
If I download v.0.10.0 I don't know what has been added without checking the commits.

thanks

-Sebastien

**Comment by r2d4** [comment]
Thats a good idea.  We should add a link to https://github.com/kubernetes/minikube/blob/master/CHANGELOG.md on the releases page at least

**Comment by r2d4** [comment]
We have a link to the changelog on the releases page for v0.11.0.  Let us know if theres anything else we can add to help!
