### ISSUE TITLE
Minikube fails to start in a Ubuntu 19.10 virtual machine

### ISSUE THREAD

**Issue by dwschulze** [kubernetes/minikube#6270]
I installed kubectl and minikube as shown on the k8s docs on Ubuntu 19.10 running in VMWare Workstation. When I start minikube with --vm-driver=none (since I'm running on a virtual machine) I get this error:

minikube v1.6.2 on Ubuntu 19.10
 Selecting 'none' driver from user configuration (alternates: [])
  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
  Using the running none "minikube" VM ...
  Waiting for the host to be provisioned ...
  Preparing Kubernetes v1.17.0 on Docker '19.03.2' ...
 kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
 Launching Kubernetes ... 

Error starting cluster: running cmd: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": exit status 1
stdout:
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk

stderr:
W0110 13:53:06.531592    6051 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0110 13:53:06.532094    6051 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0110 13:53:06.533419    6051 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0110 13:53:06.533440    6051 validation.go:28] Cannot validate kubelet config - no validator is available
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error
To see the stack trace of this error execute with --v=5 or higher

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-addon-manager ["c7ccb7eb00cc"]:
    error: You must be logged in to the server (error when retrieving current configuration of:
    error: You must be logged in to the server (the server has asked for the client to provide credentials)
    error: You must be logged in to the server (the server has asked for the client to provide credentials)
❌  Problems detected in kube-apiserver ["c91043e54554"]:
    I0110 20:52:44.283421       1 log.go:172] http: TLS handshake error from 127.0.0.1:47838: remote error: tls: bad certificate
    I0110 20:52:44.483603       1 log.go:172] http: TLS handshake error from 127.0.0.1:47846: remote error: tls: bad certificate
    I0110 20:52:44.549909       1 log.go:172] http: TLS handshake error from 127.0.0.1:47848: remote error: tls: bad certificate

Is this a problem with Ubuntu 19.10 which uses the version 5 kernel, or a result of running in a VM, and is there a fix for it?

**Comment by afbjorklund** [comment]
There should be no issues with Ubuntu 19.10, so likely something was missing from the initial start

Since this is the second start, not all logs are shown. Looks like something is off with the ssl certificates

**Comment by noelzubin** [comment]
i have the same issue. i ran the same command.

**Comment by noelzubin** [comment]
restarting minikbe did the trick 
`sudo minikube delete`
`sudo minikube start --vm-driver=none`

**Comment by ventolino** [comment]
> restarting minikbe did the trick
> `sudo minikube delete`
> `sudo minikube start --vm-driver=none`

It works... thank you!

**Comment by priyawadhwa** [comment]
@ventolino since this issue has been resolved I'm going to go ahead and close it. If you see any more issues, feel free to reopen this one by including /reopen in your comment or create a new issue anytime!
