### ISSUE TITLE
✨  Selecting 'virtualbox' driver from user configuration (alternates: [none]) 🛑  The "virtualbox" driver should not be used with root privileges.

### ISSUE THREAD

**Issue by Muhammad-Sohail1** [kubernetes/minikube#6286]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by Muhammad-Sohail1** [comment]
check this thanks

**Comment by afbjorklund** [comment]
You will need to run VirtualBox as a regular user, running it as `root` is not supported (or recommended)

**Comment by afbjorklund** [comment]
See https://help.ubuntu.com/community/RootSudo
