### ISSUE TITLE
hitting github api rate limit

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6308]
one of our tools is mis-using the github api

as seen in https://storage.googleapis.com/minikube-builds/logs/6272/KVM_Linux.txt

```
HTTP code 403! Retrying in 128 ..
{
  "message": "API rate limit exceeded for user ID 20374350.",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
HTTP code 403! Retrying in 256 ..
Build step 'Execute shell' marked build as failure

```

**Comment by afbjorklund** [comment]
Possibly machine: https://github.com/docker/machine/blob/master/README.md#you-may-be-getting-rate-limited-by-github-error-message

**Comment by medyagh** [comment]
update: I generated new API tokens and it seems to be working. I will close this issue for now till we see it agian.

**Comment by medyagh** [comment]
nope that didnt help at all ! 

still getting

```
HTTP code 403! Retrying in 128 ..
{
  "message": "API rate limit exceeded for user ID 20374350.",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```
