### ISSUE TITLE
restart faileds: webhook "sinkbindings.webhook.sources.knative.dev": Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by kameshsampath** [kubernetes/minikube#6312]
minikube version 
`minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392`

**The exact command to reproduce the issue**:

minikube start 

**The full output of the command that failed**:<details>

* first start a minikube instance using the command `minikube -p dmeo start --kubernetes-version=v1.14.7
* once the instance is started wait for some time 
* stop the instance
* start the instance from same profile

```  minikube start
😄  [knative] minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'hyperkit' driver from user configuration (alternates: [virtualbox])
👍  Kubernetes 1.17.0 is now available. If you would like to upgrade, specify: --kubernetes-version=1.17.0
🔄  Starting existing hyperkit VM for "knative" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.14.7 on Docker '19.03.5' ...
🚀  Launching Kubernetes ...

💣  Error starting cluster: addon phase cmd:"/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.14.7:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml\"": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.14.7:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1
stdout:

stderr:
error execution phase addon/coredns: unable to create deployment: Internal error occurred: failed calling webhook "sinkbindings.webhook.sources.knative.dev": Post https://eventing-webhook.knative-eventing.svc:443/sinkbindings?timeout=30s: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```
</details>

**The output of the `minikube logs` command**:  https://gist.github.com/8e68c35f4d80e8376534eda149a56852

**The operating system version**: macOS Catalina v10.15.1

**Comment by medyagh** [comment]
@kameshsampath the problem seems to be the  addon/coredns addon, do you mind disable and enable the addon and see how it will affect the issue?

**Comment by kameshsampath** [comment]
@medyagh  -  none of the addons are enabled but still same issue

**Comment by awgneo** [comment]
I have this problem as well. This addon isn't even in my addons list.

**Comment by tstromberg** [comment]
The coredns addon is built-in and required by kubeadm, so there is no possibility of tuning that behavior.

As best as I can tell, something configured a knative webhook to be contacted in certain cases, and that webhook is not available at the time that coredns comes up. 

You can workaround this by using `minikube delete`, but it would be worth hearing how you got to this point so that we could replicate it ourselves?

I think the proper behavior here may be for `minikube start` to ignore webhooks, but I'm not sure that is possible.

**Comment by tstromberg** [comment]
I'm working on a fix for this, which resets clusters that are in a bad state.
