### ISSUE TITLE
exit status 1: InvalidOperation,Microsoft.HyperV.PowerShell.Commands.NewVM

### ISSUE THREAD

**Issue by bhargodevarya** [kubernetes/minikube#6329]
**The exact command to reproduce the issue**:

minikube start --vm-driver hyperv --hyperv-virtual-switch "Minikube Switch"

**The full output of the command that failed**:<details>

* minikube v1.6.2 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362                                                                                                                     * Selecting 'hyperv' driver from user configuration (alternates: [])
* Downloading VM boot image ...
    > minikube-v1.6.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.6.0.iso: 150.93 MiB / 150.93 MiB [-] 100.00% 23.68 MiB p/s 7s
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0116 15:50:00.456794   65984 main.go:106] libmachine: [stderr =====>] : Hyper-V\New-VM : Sequence contains more than one element
At line:1 char:1
+ Hyper-V\New-VM minikube -Path 'C:\Users\bhaarya\.minikube\machines\mi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.HyperV.PowerShell.Commands.NewVM

*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: exit status 1
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

E0116 15:51:42.334375   37592 main.go:106] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

*
X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:

Microsoft Windows 10 Enterprise 10.0.18362 Build 18362

**Comment by bhargodevarya** [comment]
I have already tried deleting the `.minikube` folder under the user home directory

**Comment by tstromberg** [comment]
Do you mind sharing the output of:

`minikube start --vm-driver hyperv --hyperv-virtual-switch "Minikube Switch" --alsologtostderr -v=1`

I would also be curious to see the output if you do not pass a `--hyperv-virtual-switch` argument.

**Comment by spyd3rw3b** [comment]
I got the same error, Powershell returned as online, from the cmdline, I deleted the .minikube, but Hyper-V had a lock on the virtual drives and would not release. I had to delete the minikube VM under Hyper-V Manager. Close my current cmdline session and it started successfully.

**Comment by priyawadhwa** [comment]
Hey @bhargodevarya could you try doing the same as @spyd3rw3b and let us know if that resolves your issue?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by bhargodevarya** [comment]
Commenting on a closed issue, but I updated the version and now it works like a charm. Thank you for your assistance.
