### ISSUE TITLE
stat /storage-provisione r: no such file or directory\": unknown"

### ISSUE THREAD

**Issue by Fitsh** [kubernetes/minikube#6331]
After I run the command:` minikube start --vm-driver=none` on ubuntu 18.04 
and the  output is:
E0116 18:17:05.326935   28687 start.go:379] kubectl info: exec: exit status 1

**The output of the `minikube logs` command**: 
 16 18:17:01 ThinkPad kubelet[29757]: E0116 18:17:01.347650   29757 remote_runtime.go:222] StartContainer "5ad19eb0f3207e3750136d85b8691a4c2c9
26521fee111c69785337c5bec229b" from runtime service failed: rpc error: code = Unknown desc = failed to start container "5ad19eb0f3207e3750136d85b
8691a4c2c926521fee111c69785337c5bec229b": Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container proce
ss caused "exec: \"/storage-provisioner\": stat /storage-provisioner: no such file or directory": unknown
1月 16 18:17:01 ThinkPad kubelet[29757]: E0116 18:17:01.347787   29757 kuberuntime_manager.go:803] container start failed: RunContainerError: fai
led to start container "5ad19eb0f3207e3750136d85b8691a4c2c926521fee111c69785337c5bec229b": Error response from daemon: OCI runtime create failed:
 container_linux.go:346: starting container process caused "exec: \"/storage-provisioner\": stat /storage-provisioner: no such file or directory"
: unknown
1月 16 18:17:01 ThinkPad kubelet[29757]: E0116 18:17:01.347874   29757 pod_workers.go:191] Error syncing pod 16bb0c81-9458-44ae-8406-c379d76ac29c
 ("storage-provisioner_kube-system(16bb0c81-9458-44ae-8406-c379d76ac29c)"), skipping: failed to "StartContainer" for "storage-provisioner" with R
unContainerError: "failed to start container \"5ad19eb0f3207e3750136d85b8691a4c2c926521fee111c69785337c5bec229b\": Error response from daemon: OC
I runtime create failed: container_linux.go:346: starting container process caused \"exec: \\\"/storage-provisioner\\\": stat /storage-provisione
r: no such file or directory\": unknown"
1月 16 18:17:01 ThinkPad kubelet[29757]: W0116 18:17:01.349174   29757 container.go:412] Failed to create summary reader for "/kubepods/besteffor
t/pod16bb0c81-9458-44ae-8406-c379d76ac29c/5ad19eb0f3207e3750136d85b8691a4c2c926521fee111c69785337c5bec229b": none of the resources are being trac
ked.

The minikube's version is v1.6.2

**Comment by afbjorklund** [comment]
Probably same as #6246 - try doing a `docker pull` to get the fixed image

**Comment by Fitsh** [comment]
> Probably same as #6246 - try doing a `docker pull` to get the fixed image

It's ok to use.Thanks for your help~
