### ISSUE TITLE
PROBLEMA CON MINIKUBE.

### ISSUE THREAD

**Issue by maktup** [kubernetes/minikube#6332]
ME ESTÁ GENERANDO UN GRAN PROBLEMA INICIAR EL MINIKUBE.

X Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
cannot use "fe80::215:5dff:fe65:5115" as the bind address for the API Server

  - MINIKUBE: 1.3.0
 - KUBECTL:  1.15.0

**Comment by medyagh** [comment]
Hola @maktup  I see you use a very old version of minikube, do you mind trying with the latest verison ?

**Comment by maktup** [comment]
Hi actually i overcame the problem with this tools:

 - CHOCO:    v0.10.15
 - MINIKUBE: v1.6.2
 - KUBECTL:  v1.17.1
 - DOCKER:   v19.03

*. INSTALL: 'kubernetes-cli' & 'Minikube'. 
    choco install minikube --force 
    choco install kubernetes-cli --force

**Comment by medyagh** [comment]
@maktup thanks for the update, to clarify you dont have the issue anymore with newest version ?

**Comment by maktup** [comment]
It is much but much more stable, previously used with Hyper-V, because I do not know directly because it did not work with VirtualBox and it was too unstable and I had to be reinstalling and configuring everything at all times. But since I use CHOCOLATE: https://chocolatey.org/, I am very satisfied with it, all easy to install and stable again.

Greetings.

**Comment by priyawadhwa** [comment]
@maktup thanks for opening this issue. It seems that upgrading has resolved this issue, so I'm going to close it for now. If you face any more issues please open another!
