### ISSUE TITLE
运行有问题minikube start --vm-driver=none

### ISSUE THREAD

**Issue by SirBlues** [kubernetes/minikube#6347]
报错：
* minikube v1.4.0 on Centos 7.7.1908
* Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
* Running on localhost (CPUs=4, Memory=7521MB, Disk=51175MB) ...
* OS release is CentOS Linux 7 (Core)
* Preparing Kubernetes v1.16.0 on Docker 18.09.4 ...
* Downloading kubelet v1.16.0
* Downloading kubeadm v1.16.0

* Pulling images ...
* Launching Kubernetes ... 
* 
X Error starting cluster: cmd failed: sudo env PATH=/var/lib/minikube/binaries/v1.16.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap

: running command: sudo env PATH=/var/lib/minikube/binaries/v1.16.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
 output: [init] Using Kubernetes version: v1.16.0
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Port-8443]: Port 8443 is in use
        [ERROR Port-2379]: Port 2379 is in use
        [ERROR Port-2380]: Port 2380 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher
: running command: sudo env PATH=/var/lib/minikube/binaries/v1.16.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
.: exit status 1
* 
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

---

minikube logs

* Jan 19 11:26:50 minikube kubelet[11159]: I0119 11:26:50.636162   11159 server.go:410] Version: v1.16.0
* Jan 19 11:26:50 minikube kubelet[11159]: I0119 11:26:50.636511   11159 plugins.go:100] No cloud provider specified.
* Jan 19 11:26:50 minikube kubelet[11159]: F0119 11:26:50.636586   11159 server.go:271] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
* Jan 19 11:26:50 minikube systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Jan 19 11:26:50 minikube systemd[1]: Unit kubelet.service entered failed state.
* Jan 19 11:26:50 minikube systemd[1]: kubelet.service failed.
* Jan 19 11:26:51 minikube systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Jan 19 11:26:51 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Jan 19 11:26:51 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Jan 19 11:26:51 minikube kubelet[11174]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 19 11:26:51 minikube kubelet[11174]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 19 11:26:51 minikube kubelet[11174]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 19 11:26:51 minikube kubelet[11174]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 19 11:26:51 minikube kubelet[11174]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 19 11:26:51 minikube kubelet[11174]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 19 11:26:51 minikube kubelet[11174]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 19 11:26:51 minikube kubelet[11174]: I0119 11:26:51.388740   11174 server.go:410] Version: v1.16.0
* Jan 19 11:26:51 minikube kubelet[11174]: I0119 11:26:51.389001   11174 plugins.go:100] No cloud provider specified.
* Jan 19 11:26:51 minikube kubelet[11174]: F0119 11:26:51.389050   11174 server.go:271] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
* Jan 19 11:26:51 minikube systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Jan 19 11:26:51 minikube systemd[1]: Unit kubelet.service entered failed state.
* Jan 19 11:26:51 minikube systemd[1]: kubelet.service failed.

不知道改怎么弄，help me

**Comment by medyagh** [comment]
@SirBlues 
it appears that the 
ports that minikube wants to use are taken 
```
[ERROR Port-8443]: Port 8443 is in use
[ERROR Port-2379]: Port 2379 is in use
[ERROR Port-2380]: Port 2380 is in use
```

could you make sure those ports are free ? (maybe uninstall any other tool that is using the port or kill process that uses those ports )

you could also try to make sure no preivous instances of minikube are running by 

```sudo minikbue delete```

kill $(lsof -t -i:8443)
kill $(lsof -t -i:2379)
kill $(lsof -t -i:2380)

**Comment by priyawadhwa** [comment]
@SirBlues are you still seeing this issue?

**Comment by sharifelgamal** [comment]
@SirBlues I'm going to go ahead and close this issue for now, but if you still need help, feel free to reopen it. I would try what @medyagh was suggesting above and freeing up ports that minikube needs.
