### ISSUE TITLE
plugin/docker: Couldn't find network status for default/hello-minikube-5cd8589d76-zl7gs through plugin: invalid network status for

### ISSUE THREAD

**Issue by DFranc-D** [kubernetes/minikube#6356]
minikube service hello-minikube
**The exact command to reproduce the issue**:
~ $ kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
deployment.apps/hello-minikube created
~ $ kubectl expose deployment hello-minikube --type=NodePort --port=8080
service/hello-minikube exposed
~ $ minikube service hello-minikube

**The full output of the command that failed**:<details>
Opening service default/hello-minikube in default browser...
No protocol specified

(google-chrome-stable:6052): Gtk-WARNING **: 16:50:30.404: cannot open display: :1
No protocol specified

(x-www-browser:6075): Gtk-WARNING **: 16:50:30.515: cannot open display: :1
No protocol specified
Unable to init server: Could not connect: Connection refused
Error: cannot open display: :1
/usr/bin/xdg-open: 870: iceweasel: not found
/usr/bin/xdg-open: 870: seamonkey: not found
/usr/bin/xdg-open: 870: mozilla: not found
/usr/bin/xdg-open: 870: epiphany: not found
No protocol specified
qt.qpa.xcb: could not connect to display :1
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

Aborted
No protocol specified

(chromium:6117): Gtk-WARNING **: 16:50:31.143: cannot open display: :1
/usr/bin/xdg-open: 870: chromium-browser: not found
No protocol specified

(google-chrome:6153): Gtk-WARNING **: 16:50:31.283: cannot open display: :1
/usr/bin/xdg-open: 870: www-browser: not found
/usr/bin/xdg-open: 870: links2: not found
/usr/bin/xdg-open: 870: elinks: not found
/usr/bin/xdg-open: 870: links: not found
/usr/bin/xdg-open: 870: lynx: not found
/usr/bin/xdg-open: 870: w3m: not found
xdg-open: no method available for opening 'http://192.168.39.18:30380'

💣  open url failed: http://192.168.39.18:30380: exit status 3

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>
**The output of the `minikube logs` command**:
minikube logs | grep hello-minikube
I0120 22:50:25.732583       1 event.go:281] Event(v1.ObjectReference{Kind:"Deployment", Namespace:"default", Name:"hello-minikube", UID:"81e9d0d0-8ada-4abb-a763-d60c6800b93c", APIVersion:"apps/v1", ResourceVersion:"1912", FieldPath:""}): type: 'Normal' reason: 'ScalingReplicaSet' Scaled up replica set hello-minikube-5cd8589d76 to 1
I0120 22:50:25.758662       1 event.go:281] Event(v1.ObjectReference{Kind:"ReplicaSet", Namespace:"default", Name:"hello-minikube-5cd8589d76", UID:"a6a0dedb-2175-47d6-82d4-ac54379ea4dc", APIVersion:"apps/v1", ResourceVersion:"1913", FieldPath:""}): type: 'Normal' reason: 'SuccessfulCreate' Created pod: hello-minikube-5cd8589d76-zl7gs
Jan 20 22:50:25 minikube kubelet[7233]: I0120 22:50:25.923745    7233 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-z26g2" (UniqueName: "kubernetes.io/secret/d2736a67-fb1b-4966-901e-b063ef4d4aa4-default-token-z26g2") pod "hello-minikube-5cd8589d76-zl7gs" (UID: "d2736a67-fb1b-4966-901e-b063ef4d4aa4")
Jan 20 22:50:28 minikube kubelet[7233]: W0120 22:50:28.345608    7233 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for default/hello-minikube-5cd8589d76-zl7gs through plugin: invalid network status for
Jan 20 22:50:29 minikube kubelet[7233]: W0120 22:50:29.382805    7233 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for default/hello-minikube-5cd8589d76-zl7gs through plugin: invalid network status for
Jan 20 22:50:46 minikube kubelet[7233]: W0120 22:50:46.949297    7233 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for default/hello-minikube-5cd8589d76-zl7gs through plugin: invalid network status for
Jan 20 22:50:48 minikube kubelet[7233]: W0120 22:50:48.398296    7233 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for default/hello-minikube-5cd8589d76-zl7gs through plugin: invalid network status for
2020/01/20 23:10:29 [2020-01-20T23:10:29Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube request from 172.17.0.1:37052: 
2020/01/20 23:10:29 Getting details of hello-minikube deployment in default namespace
2020/01/20 23:10:31 [2020-01-20T23:10:31Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/newreplicaset request from 172.17.0.1:37052: 
2020/01/20 23:10:33 [2020-01-20T23:10:33Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/oldreplicaset?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:37052: 
2020/01/20 23:10:34 [2020-01-20T23:10:34Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/event?itemsPerPage=10&page=1 request from 172.17.0.1:37052: 
2020/01/20 23:10:36 [2020-01-20T23:10:36Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube request from 172.17.0.1:37052: 
2020/01/20 23:10:36 Getting details of hello-minikube deployment in default namespace
2020/01/20 23:10:39 [2020-01-20T23:10:39Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/newreplicaset request from 172.17.0.1:37052: 
2020/01/20 23:10:40 [2020-01-20T23:10:40Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/oldreplicaset?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:37052: 
2020/01/20 23:10:42 [2020-01-20T23:10:42Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/event?itemsPerPage=10&page=1 request from 172.17.0.1:37052: 
2020/01/20 23:10:51 [2020-01-20T23:10:51Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube request from 172.17.0.1:37052: 
2020/01/20 23:10:51 Getting details of hello-minikube deployment in default namespace
2020/01/20 23:10:55 [2020-01-20T23:10:55Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/newreplicaset request from 172.17.0.1:37052: 
2020/01/20 23:11:00 [2020-01-20T23:11:00Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/oldreplicaset?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:37052: 
2020/01/20 23:11:04 [2020-01-20T23:11:04Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/event?itemsPerPage=10&page=1 request from 172.17.0.1:37052: 
2020/01/20 23:11:08 [2020-01-20T23:11:08Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube request from 172.17.0.1:37052: 
2020/01/20 23:11:08 Getting details of hello-minikube deployment in default namespace
2020/01/20 23:11:12 [2020-01-20T23:11:12Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/newreplicaset request from 172.17.0.1:37052: 
2020/01/20 23:11:13 [2020-01-20T23:11:13Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/oldreplicaset?itemsPerPage=10&page=1&sortBy=d,creationTimestamp request from 172.17.0.1:37052: 
2020/01/20 23:11:16 [2020-01-20T23:11:16Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube/event?itemsPerPage=10&page=1 request from 172.17.0.1:37052: 
2020/01/20 23:11:19 [2020-01-20T23:11:19Z] Incoming HTTP/1.1 GET /api/v1/deployment/default/hello-minikube request from 172.17.0.1:37052: 
2020/01/20 23:11:19 Getting details of hello-minikube deployment in default namespace

<details>

</details>
I thought the browser that comes with Kali (Firefox ESR) may have something to do with it but I was able to get to the dashboard eventhough Minikube threw similar errors when issuing the commands "minikube dashboard" ... 

Notice here hello-minikube has a a 10.x.x.x IP , minkube URL above has a 192.x.x.x , what in minikube is doing the NATing?

kubectl get all --all-namespaces | grep hello-minikube
default                pod/hello-minikube-5cd8589d76-zl7gs              1/1     Running   0          15m
default                service/hello-minikube              NodePort    10.96.158.249   <none>        8080:30380/TCP           15m
default                deployment.apps/hello-minikube              1/1     1            1           15m
default                replicaset.apps/hello-minikube-5cd8589d76              1         1         1       15m

**The operating system version**:
cat /etc/*release
DISTRIB_ID=Kali
DISTRIB_RELEASE=kali-rolling
DISTRIB_CODENAME=kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"
PRETTY_NAME="Kali GNU/Linux Rolling"
NAME="Kali GNU/Linux"
ID=kali
VERSION="2019.4"
VERSION_ID="2019.4"
VERSION_CODENAME="kali-rolling"
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="https://www.kali.org/"
SUPPORT_URL="https://forums.kali.org/"
BUG_REPORT_URL="https://bugs.kali.org/"

**Comment by medyagh** [comment]
I am not sure if this is a bug, do you mind clarifying, are you trying to access the private ip ?

**Comment by DFranc-D** [comment]
I did a little more research today... and I think you may be right. I
should have done more in-depth research prior to reporting as a bug but it
was just weird that I do get to the dashboard when browsing to it despite
Minikube displaying the error and it's also odd that I don't get asked to
provide a token to access the dashboard.
Please disregard the issue as I continue to learn more about minikube...

**Comment by medyagh** [comment]
@DFranc-D  glad to see the mystries is solved :) feel free to re-open if you have more questions
