### ISSUE TITLE
Starting minikube in MacOS with virtual box error

### ISSUE THREAD

**Issue by jecihjoy** [kubernetes/minikube#6358]
**The exact command to reproduce the issue**: 
minikube start --vm-driver=virtualbox

**The full output of the command that failed**:
I got the following error while installing minikube, please help
                               
😄  minikube v1.6.2 on Darwin 10.14.6
✨  Selecting 'virtualbox' driver from user configuration (alternates: [])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
E0121 20:00:48.450433     666 cache_images.go:86] CacheImage k8s.gcr.io/kube-apiserver:v1.17.0 -> /Users/jecihjoy/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.17.0 failed: write: read tcp 192.168.43.13:49376->216.58.223.112:443: read: operation timed out
E0121 20:00:48.450979     666 cache_images.go:86] CacheImage k8s.gcr.io/kube-addon-manager:v9.0.2 -> /Users/jecihjoy/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0.2 failed: write: Get https://storage.googleapis.com/eu.artifacts.google-containers.appspot.com/containers/images/sha256:6cacbd9391b8d4b7d29914e2243ca1f90a4eff4dd3897c2cf7b95792c14287d3: read tcp 192.168.43.13:49376->216.58.223.112:443: read: operation timed out
E0121 20:00:48.451015     666 start.go:839] Error caching images:  Caching images for kubeadm: caching images: caching image /Users/jecihjoy/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.17.0: write: read tcp 192.168.43.13:49376->216.58.223.112:443: read: operation timed out
❌  Unable to load cached images: loading cached images: stat /Users/jecihjoy/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0.2: no such file or directory
💾  Downloading kubeadm v1.17.0
💾  Downloading kubelet v1.17.0

💣  Failed to update cluster
❌  Error: [INVALID_PROXY_HOSTNAME] downloading binaries: downloading kubeadm: Error downloading kubeadm v1.17.0: failed to download: failed to download to temp file: download failed: 5 error(s) occurred:

* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubeadm: dial tcp: lookup storage.googleapis.com: no such host
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubeadm: dial tcp: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubeadm: dial tcp: lookup storage.googleapis.com: no such host
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubeadm: dial tcp: i/o timeout
* Temporary download error: Get https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubeadm: dial tcp: lookup storage.googleapis.com: no such host
💡  Suggestion: Verify that your HTTP_PROXY and HTTPS_PROXY environment variables are set correctly.
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

**The operating system version**: MacOs Mojave version 10.14.6

**Comment by medyagh** [comment]
@jecihjoy do you mind checking your connectivty wiith https://storage.googleapis.com/kubernetes-release/release/v1.17.0/bin/linux/amd64/kubeadm

can you download that manually ?

alternatively, you could try with hyperkit driver and see if you have same problem?

**Comment by jecihjoy** [comment]
@medyagh Thanks for your  response.
However I got past this error by reinstalling docker again and running
 **minikube start --vm-driver=virtualbox** after that.
