### ISSUE TITLE
Regression in LoadBalancer support

### ISSUE THREAD

**Issue by rlmcpherson** [kubernetes/minikube#636]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`): v0.10.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX El Capitan 10.11.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **Docker version** (e.g. `docker -v`):  Docker version 1.12.1, build 6f9534c
- **Install tools**: install script on releases page
- **Others**:

**What happened**: 

After creating a service of type LoadBalancer, ran:
```
$ minikube service -n $NAMESPACE $SERVICE
Waiting, endpoint for service is not ready yet...Waiting, endpoint for service is not ready yet...
```

**What you expected to happen**:
According to #384 LoadBalancer works and it was working in the previous version of Minikube from about 2 months ago, but I no longer have the version information. This appears to be a regression.

**How to reproduce it** (as minimally and precisely as possible):

```
For an existing kubernetes deployment, created via the api:
kubectl expose deployment $SERVICE --port=<port> --target-port=<port> --type=LoadBalancer
```

I'm happy to do further debugging or provide more information as needed.

**Comment by dlorenc** [comment]
Could you provide the output of:

`kubectl get services` ?

**Comment by rlmcpherson** [comment]
Yes, the output is:
```
$ kubectl --namespace=$NAMESPACE get services

NAME      CLUSTER-IP   EXTERNAL-IP   PORT(S)             AGE
service   10.0.0.26    <pending>     8080/TCP,7070/TCP   59s
```

The pending state is not surprising since a loadbalancer is not actually created, but the output of 
```
minikube service -n $NAMESPACE --url service
```
used to return a url anyway but now returns 
```
Waiting, endpoint for service is not ready yet...
```

**Comment by VanAxe** [comment]
I'm seeing the same thing as @rlmcpherson on my setup.

**Environment**:

- **OS**: Linux 4.7.5-200.fc24.x86_64
- **VM Driver**: VirtualBox
- **Docker version**: 1.12.1
- **Install tools**: install script on releases page
- **Others**:

**Comment by dlorenc** [comment]
A change went in recently to the service command to make it wait for the endpoints to be in the Ready state before returning.

The code that does this check is here: https://github.com/kubernetes/minikube/blob/a403a949dde02d0c9025f21a821bb4a65725bce9/cmd/minikube/cmd/service.go#L105

Could you attach the output of "kubectl get endpoints -o=json"?

**Comment by ls-avanier** [comment]
I just upgraded to minikube 0.11.0 this morning and I'm getting the same results.

```json
{
    "kind": "List",
    "apiVersion": "v1",
    "metadata": {},
    "items": [
        {
            "kind": "Endpoints",
            "apiVersion": "v1",
            "metadata": {
                "name": "concourse-postgresql",
                "namespace": "default",
                "selfLink": "/api/v1/namespaces/default/endpoints/concourse-postgresql",
                "uid": "fb2a74ff-8c90-11e6-8fd3-e2de7cfc2adf",
                "resourceVersion": "213",
                "creationTimestamp": "2016-10-07T13:21:39Z"
            },
            "subsets": [
                {
                    "addresses": [
                        {
                            "ip": "172.17.0.3",
                            "targetRef": {
                                "kind": "Pod",
                                "namespace": "default",
                                "name": "concourse-postgresql-sl309",
                                "uid": "fb182b8e-8c90-11e6-8fd3-e2de7cfc2adf",
                                "resourceVersion": "211"
                            }
                        }
                    ],
                    "ports": [
                        {
                            "port": 5432,
                            "protocol": "TCP"
                        }
                    ]
                }
            ]
        },
        {
            "kind": "Endpoints",
            "apiVersion": "v1",
            "metadata": {
                "name": "concourse-web",
                "namespace": "default",
                "selfLink": "/api/v1/namespaces/default/endpoints/concourse-web",
                "uid": "fb548daf-8c90-11e6-8fd3-e2de7cfc2adf",
                "resourceVersion": "569",
                "creationTimestamp": "2016-10-07T13:21:40Z"
            },
            "subsets": [
                {
                    "notReadyAddresses": [
                        {
                            "ip": "172.17.0.4",
                            "targetRef": {
                                "kind": "Pod",
                                "namespace": "default",
                                "name": "concourse-web-gxc81",
                                "uid": "fb449c30-8c90-11e6-8fd3-e2de7cfc2adf",
                                "resourceVersion": "568"
                            }
                        }
                    ],
                    "ports": [
                        {
                            "port": 8080,
                            "protocol": "TCP"
                        }
                    ]
                }
            ]
        },
        {
            "kind": "Endpoints",
            "apiVersion": "v1",
            "metadata": {
                "name": "kubernetes",
                "namespace": "default",
                "selfLink": "/api/v1/namespaces/default/endpoints/kubernetes",
                "uid": "c9999e98-8c90-11e6-8fd3-e2de7cfc2adf",
                "resourceVersion": "8",
                "creationTimestamp": "2016-10-07T13:20:16Z"
            },
            "subsets": [
                {
                    "addresses": [
                        {
                            "ip": "10.0.2.15"
                        }
                    ],
                    "ports": [
                        {
                            "name": "https",
                            "port": 8443,
                            "protocol": "TCP"
                        }
                    ]
                }
            ]
        }
    ]
}
```

**Comment by dlorenc** [comment]
@ls-avanier thanks! It looks like the concourse-web service does indeed have some `notReadyAddresses`, which is what we're using to check. Any idea why the service has these? What's in your service configuration?

**Comment by ls-avanier** [comment]
You can find the service definitions [at this repo](https://github.com/ls-avanier/concourse-kubernetes). [This file](https://github.com/ls-avanier/concourse-kubernetes/blob/master/concourse-web-svc.yaml) may be of particular interest since that's the service I'm trying to access, `concourse-web`.

I'm currently running the exact same _yaml_ definitions in Kubernetes `1.4.0` on AWS and I'm not getting the same behavior. In either case, it's running properly working Docker containers hosting the Concourse-CI web interface / API, and those behave as expected.

**Comment by dlorenc** [comment]
Thanks for the details. Just to double check that the LB is actually working, could you run this kubectl command:

echo $(minikube ip):$(kubectl get service concourse-web -o=jsonpath='{.spec.ports[0].nodePort}{"\n"}')

Then open up that URL in your browser to check?

I think it's a bug in `minikube service`, but I'd just like to confirm.

**Comment by jimmidyson** [comment]
For a service to be operational, it should have > 0 endpoints. The number of not ready endpoints is immaterial & should be ignored.

**Comment by ls-avanier** [comment]
```bash
➜  concourse-kubernetes git:(master) echo $(minikube ip):$(kubectl get service concourse-web -o=jsonpath='{.spec.ports[0].nodePort}{"\n"}') | xargs -I {} curl -I http://{}
HTTP/1.1 200 OK
Date: Sat, 08 Oct 2016 16:53:15 GMT
Content-Length: 1836
Content-Type: text/html; charset=utf-8
```

The service is indeed present and answers calls as expected.

**Comment by skunkwerk** [comment]
What is the solution to this issue?  I'm having the same issue with Minikube .17.1
