### ISSUE TITLE
Memory allocation

### ISSUE THREAD

**Issue by mpouyakh7** [kubernetes/minikube#6366]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>
Unable to start VM. Please investigate and run 'minikube delete' if possible: start: error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: pu
2020-01-22T12:16:10.342408Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory')

</details>

**The operating system version**:
Linux LTS 18.04

**Comment by sharifelgamal** [comment]
By default we specify 2 GB of memory for the minikube VM. You might see this error if you don't have enough RAM on your machine to initialize the VM. Try running `cat proc meminfo` to see how much memory you have and perhaps starting minikube with the `--memory` parameter so you can specify a lower amount.

**Comment by sharifelgamal** [comment]
@mpouyakh7 Did setting the memory command help with your issue?

**Comment by mpouyakh7** [comment]
yes, thanks for your response.
