### ISSUE TITLE
minikube.exe start error

### ISSUE THREAD

**Issue by avaughns** [kubernetes/minikube#6379]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by avaughns** [comment]
minikube.exe start error

**Comment by avaughns** [comment]
* minikube v1.6.2 on Microsoft Windows 10 Home 10.0.17763 Build 17763
* Selecting 'virtualbox' driver from existing profile (alternates: [])
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible
* Error: [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--vm-driver=none'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
* Related issues:

**Comment by priyawadhwa** [comment]
Hey @avaughns thanks for opening an issue. It seems your system doesn't support virtualization, which is needed for minikube to create a VM. 

Some alternatives you could try:

1. consult your systems BIOS manual for how to enable virtualization
1. try running minikube with our experimental docker driver which doesn't require a VM. You will need to have docker installed and running, and can enable the feature by appending `--vm-driver=docker` to `minikube start`

Does either of these work for you?

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
