### ISSUE TITLE
Getting below error during starting minikube on Linux

### ISSUE THREAD

**Issue by pnkj007** [kubernetes/minikube#6381]
**minikube start --vm-driver=none**:

** minikube v1.6.2 on Ubuntu 16.04
* Selecting 'none' driver from user configuration (alternates: [])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing none VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.17.0 on Docker '19.03.4' ...
* Launching Kubernetes ...
*
X Error starting cluster: init failed. cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap\"": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap": exit status 1
stdout:
[init] Using Kubernetes version: v1.17.0
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"

stderr:
W0123 12:54:44.037452   22371 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0123 12:54:44.038800   22371 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0123 12:54:44.042723   22371 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0123 12:54:44.042757   22371 validation.go:28] Cannot validate kubelet config - no validator is available
        [WARNING Hostname]: hostname "minikube" could not be reached
        [WARNING Hostname]: hostname "minikube": lookup minikube on 10.44.226.223:53: server misbehaving
error execution phase kubelet-start: error writing a dynamic environment file for the kubelet: failed to create directory "/var/lib/kubelet": mkdir /var/lib/kubelet: not a directory
To see the stack trace of this error execute with --v=5 or higher

*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by priyawadhwa** [comment]
Hey @pnkj007 it seems from this error:

```
error execution phase kubelet-start: error writing a dynamic environment file for the kubelet:
failed to create directory "/var/lib/kubelet": mkdir /var/lib/kubelet: not a directory
```

that minikube is trying to create `/var/lib/kubelet` on your machine but is unable to. Are you able to create that directory yourself with `mkdir -p /var/lib/kubelet`?

**Comment by priyawadhwa** [comment]
Hey @pnkj007 I'm going to go ahead and close this issue as some time has passed. If you continue to see this error, please include /reopen in your comment and this issue will be automatically reopened.

Thank you for sharing your experience!
