### ISSUE TITLE
ssh with kic: driver does not have SSHHostName

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#6382]
I expected this to work with Docker for Desktop on macOS, but it didn't.

```
minikube start --vm-driver=docker  
minikube ssh
```

message:

```
ssh: Creating ssh client: driver does not have SSHHostName
```

If it isn't possible, we should display a nicer error message.

**Comment by afbjorklund** [comment]
For the `none` driver we show a different message:

```
$ sudo minikube ssh
💡  'none' driver does not support 'minikube ssh' command
```

**Comment by medyagh** [comment]
this was solved by adding ssh to minikube docker driver
