### ISSUE TITLE
After VM update of JAVA minikube does not restart

### ISSUE THREAD

**Issue by kube-user2010** [kubernetes/minikube#6384]
I stopped minikube to update the Ubuntu OpenJDK Java version.
After updating the Java, i went to start up minikube and it now fails.

ubuntu@ip-10-240-75-167:~$ sudo minikube start --vm-driver=none
sudo: unable to resolve host ip-10-240-75-167: Resource temporarily unavailable
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running none VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 10.240.75.167
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.09.3
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.14.0 ...
:   Relaunching Kubernetes v1.14.0 using kubeadm ...
:   Waiting for pods: apiserver proxy etcd scheduler controller dns
:   Updating kube-proxy configuration ...
-   Verifying component health .......................
!   kubelet checks failed: Temporary Error: kubelet unhealthy: <nil>: Error
Temporary Error: kubelet unhealthy: <nil>: Error
Temporary Error: kubelet unhealthy: <nil>: Error
*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
X   Problems detected in "kube-addon-manager":
    - error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused

How can this be fixed?

**Comment by kube-user2010** [comment]
Also, this is a linux Ubuntu VM in Amazon AWS, if that matters.

**Comment by tstromberg** [comment]
`minikube logs` would help here, but I do first suggest upgrading to minikube v1.7.3 and running `minikube delete` to remove the old state. Please let me know how it works out!

**Comment by sharifelgamal** [comment]
@kube-user2010 do you still need help here?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
