### ISSUE TITLE
kic: run docker container without --privileged

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6387]
Thanks to @josedonizetti who first noticed we could improve this.

current docker run looks like

--privileged --security-opt seccomp=unconfined

we could get rid of privilged and pass in the selective whitelist of features we need.

**Comment by govargo** [comment]
Rootless docker may be helpful in future.

https://github.com/moby/buildkit/releases/tag/v0.7.0-rc1

**Comment by medyagh** [comment]
I tried to replace --previlaged with --cap-add=ALL but that didnt work. so it is debatable if we could replace --previlaged with a fine grain --cap-add.

Logs are on my other machine, I will paste later.

**Comment by josedonizetti** [comment]
@medyagh Yeah, from the docs seem `priviledged` is required to have `docker in a docker`:

```
The --privileged flag gives all capabilities to the container, and it also lifts all the limitations enforced by the device cgroup controller. In other words, the container can then do almost everything that the host can do. This flag exists to allow special use-cases, like running Docker within Docker.
```

**Comment by medyagh** [comment]
this seems to be not doable
