### ISSUE TITLE
Prevent cluster from auto-starting on reboot

### ISSUE THREAD

**Issue by schollii** [kubernetes/minikube#6400]
**The exact command to reproduce the issue**:
minikube start --vm-driver=none

**The full output of the command that failed**:<details>

The command does not fail; rather, every time I reboot, minikube automatically starts the cluster (not a bad thing if that's what you want). I am unable to find the configuration that will make it start only on demand.

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Ubuntu 18.04 with latest patches

**Comment by afbjorklund** [comment]
The VM that you dedicate to running Kubernetes will have start files installed. The kubelet itself is controlled by systemd unit files.

**Comment by tstromberg** [comment]
I don't believe that kubernetes/kubeadm has a way to control this, but you can run `sudo systemctl disable kubelet` to set kubernetes to be manually started.

Let me know if that helps.

**Comment by schollii** [comment]
Yes it does thank you, not what I expected but it works!
