### ISSUE TITLE
Document how to install the docker client

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#6402]
Some people seem to be confused by the new docker.com site, and some static binaries are missing...

* https://docs.docker.com/install/linux/docker-ce/binaries/

We might need to write a simple guide on how to install the docker client (the CLI), using regular tools ?

Note that the daemon is **not** needed, it is provided by minikube!

## macOS

```console
$ brew install docker
```
https://formulae.brew.sh/formula/docker

## Windows

```console
$ choco install docker-cli
```
https://chocolatey.org/packages/docker-cli

## Linux

As usual the Linux packaging situation is a bit confused, but it _might_ be available as "[docker.io](https://www.collabora.com/news-and-blog/blog/2018/07/04/docker-io-debian-package-back-to-life/)".

But for that platform, the [static binaries](https://download.docker.com/linux/static/stable/) are still available and https://get.docker.com still works...

----

Installing Docker as a CRI for kubeadm (`none` driver) is documented _elsewhere_: 
https://kubernetes.io/docs/setup/production-environment/container-runtimes/#docker

Support for Docker Desktop and other products is also documented _elsewhere_:
https://www.docker.com/products/docker-desktop

For minikube, a simple `docker` CLI program is enough to be able to use `minikube docker-env`
The download should be about 50M, and is a single go binary - without the daemons and such.

And of course, if you use a different container runtime such as CRI-O even that is not needed.
Then you use something like `podman` or other [OCI](https://www.opencontainers.org/) tool, in order to build your container images.

**Comment by afbjorklund** [comment]
Even though this might help _avoid_ support issues, it is not really a support issue itself.

**Comment by tstromberg** [comment]
I feel like this is out of scope for documentation, as docker isn't required for use with minikube. Thoughts?

**Comment by afbjorklund** [comment]
We could hide it somewhere related to `docker-env` perhaps ? While not a strict technical dependency (linked library or so), the output of that command is of limited usability without a client.

It would have been better to link to proper upstream docker/podman documentation, but currently that strategy is letting us down. It is too complicated and drags in too much “stuff”

**Comment by afbjorklund** [comment]
Will just write the PR(s), and we can take it from there...

**Comment by medyagh** [comment]
I am okay with documenting this with the condition that at the very beginning that minikube does not need docker !
and you can install docker if you want to use the following features:

- docker driver instead of vm
- build images directly against docker daemon inside minikube if you use docker runtime (instead of containerd)

and same for podman installation

**Comment by afbjorklund** [comment]
Since we now use podman-env in a similar manner, the same goes for podman-remote.

**Comment by medyagh** [comment]
currently we have a link in our website to docker's docs to install docker 

https://minikube.sigs.k8s.io/docs/drivers/docker/
