### ISSUE TITLE
Add Operators OLM addon

### ISSUE THREAD

**Issue by kameshsampath** [kubernetes/minikube#6419]
/kind feature

It will be nice to have the  operator lifecycle manager installed in to minikube by default as that can support installing stack from https://operatorhub.io/operator.  If not default alteast an addon will help.

e.g. For OLM install we need curl -sL https://github.com/operator-framework/operator-lifecycle-manager/releases/download/0.13.0/install.sh | bash -s 0.13.0

**Comment by tstromberg** [comment]
I'm generally against adding more default addons due to the additional overhead in terms of memory and startup latency. 

I would be happy to see it provided as an addon though, which users can then trivially enable (`minikube start --addons olm`).

**Comment by kameshsampath** [comment]
I see your point!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by priyawadhwa** [comment]
This PR is currently in progress #8129
