### ISSUE TITLE
none driver: Port in use error during reuse

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6425]
as seen in https://github.com/kubernetes/minikube/issues/5899

```
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10251]: Port 10251 is in use
	[ERROR Port-10252]: Port 10252 is in use
	[ERROR Port-2380]: Port 2380 is in use

```
also https://github.com/kubernetes/minikube/issues/6213

**Comment by tstromberg** [comment]
I experimented with explicitly killing old containers in https://github.com/kubernetes/minikube/pull/6519 - but was solving it in the wrong place.
