### ISSUE TITLE
writefile failed for /home/ashwani/.minikube/ca.crt: open /home/ashwani/.minikube/ca.crt: permission denied

### ISSUE THREAD

**Issue by imaskm** [kubernetes/minikube#6426]
**minikube start --vm-driver virtualbox**:

**The full output of the command that failed**:<details>
😄  minikube v1.6.2 on Ubuntu 18.04
✨  Selecting 'virtualbox' driver from user configuration (alternates: [kvm2 none])
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...

💣  Failed to setup certs: Error generating certs: Error generating CA certificate: Error writing certificate to cert path: writefile failed for /home/ashwani/.minikube/ca.crt: open /home/ashwani/.minikube/ca.crt: permission denied

</details>

**The output of the `minikube logs` command**:<details>

an 29 20:17:39 minikube kubelet[6574]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jan 29 20:17:39 minikube kubelet[6574]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jan 29 20:17:39 minikube kubelet[6574]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jan 29 20:17:39 minikube kubelet[6574]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jan 29 20:17:39 minikube kubelet[6574]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jan 29 20:17:39 minikube kubelet[6574]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jan 29 20:17:39 minikube kubelet[6574]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Jan 29 20:17:39 minikube kubelet[6574]: F0129 20:17:39.809445    6574 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
Jan 29 20:17:39 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Jan 29 20:17:39 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

</details>

**The operating system version**:
Ubuntu 18.04, x86_64 GNU/Linux,4.15.0-74-generic

**Comment by tstromberg** [comment]
Can you check that your user is allowed to write to '/home/ashwani/.minikube/ca.crt'? Please share the output of:

* `id`
* `touch /home/ashwani/.minikube/ca.crt`
* `ls -lad /home/ashwani/.minikube/ca.crt`
* `ls -lad /home/ashwani/.minikube`

Thanks!

**Comment by imaskm** [comment]
`ashwani@plumber:~$ id
uid=1000(ashwani) gid=1000(ashwani) groups=1000(ashwani),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),116(lpadmin),126(sambashare),128(docker),134(libvirt)

-rw-r--r-- 1 ashwani ashwani 1066 Jan 30 12:38 /home/ashwani/.minikube/ca.crt


drwxr-xr-x 10 ashwani ashwani 4096 Jan 30 19:41 /home/ashwani/.minikube`

**Comment by medyagh** [comment]
@imaskm do you still have the issue with latest version of minikube?

**Comment by priyawadhwa** [comment]
Hey @imaskm are you still seeing this issue?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
