### ISSUE TITLE
consitstant commit status for github actions and jenkins

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6447]
We need to make github actions to spit out number of failures into the commit status and the duration.

plus currently it always sets the commit status to success. it should also show fail if test has failure.
the jenkins ones look like this : 

```
Docker_Linux — Jenkins: completed with 21 / 48 failures in 26.80 minute(s).
KVM_Linux — Jenkins: completed with 3 / 48 failures in 26.55 minute(s).
VirtualBox_Linux — Jenkins: completed with 2 / 48 failures in 23.01 minute(s).
```

but the github actions dont have same format.
here is the file on jenkins that creates that format : 
https://github.com/kubernetes/minikube/blob/master/hack/jenkins/common.sh#L331

here is the file that needs to be edited.
https://github.com/kubernetes/minikube/blob/master/.github/workflows/main.yml

there should be examples on the web how to set commit status in github actions

**Comment by medyagh** [comment]
@KaenDagger it's yours. This will be an exciting thing to fix

**Comment by medyagh** [comment]
@KaenDagger  are you still working on this ? any updates?

**Comment by KaenDagger** [comment]
Yes I am working on this. Got little busy actually

**Comment by KaenDagger** [comment]
@medyagh may be we can also use the jenkins shell script too in github actions

**Comment by KaenDagger** [comment]
@medyagh 
![image](https://user-images.githubusercontent.com/24780524/74030713-b9114580-49d5-11ea-8bfe-227e5b4b7e0b.png)

this was test, just see no. failures, is this here the output expected ?
If yes, I can move forward

**Comment by medyagh** [comment]
> @medyagh
> ![image](https://user-images.githubusercontent.com/24780524/74030713-b9114580-49d5-11ea-8bfe-227e5b4b7e0b.png)
> 
> this was test, just see no. failures, is this here the output expected ?
> If yes, I can move forward

that is the part that generates the HTML test report based on gopogh https://github.com/medyagh/gopogh

but we want the failure from previous step 
(make integeration)
