### ISSUE TITLE
How to set registry-mirror for docker in minikube?

### ISSUE THREAD

**Issue by blindpirate** [kubernetes/minikube#645]
Hello everyone, I want to set `--registry-mirror` for docker in minikube, but when I create `/home/docker/.docker/config.json` with content `{"registry-mirrors":["xxx"]}`, I can't find how to make docker daemon restart. 

There is no `systemctl` or `service`. When I ran `minikube stop` `minikube start` to restart the cluster, I found that the `/home/docker/.docker/config.json` I just created was missing.

I used `minikube start --registry-mirror=https://registry-mirror.com` and it didn't work.

So what can I do? 

Thank you very much.

**Comment by lli-hiya** [comment]
I run into the same problem. Do you have any solutions?

**Comment by kala888** [comment]
how to set it? i get the same issue.

**Comment by behroozam** [comment]
come on people in china or iran or whatever banned from using official repo and if we want to use mirror there is no option ?

**Comment by ttimasdf** [comment]
See https://github.com/kubernetes/minikube/issues/2638#issuecomment-376130363

**Comment by RainingNight** [comment]
I run into the same problem. Do you have any solutions?
