### ISSUE TITLE
stop+start breaks addons: /etc/kubernetes/addons not recreated

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#6456]
If you attempt to start a started cluster, we output a warning:

```
🌟  Enabling addons: default-storageclass, storage-provisioner
⚠️  Enabling 'default-storageclass' returned an error: running callbacks: [sudo test -d /etc/kubernetes/addons && sudo scp -t /etc/kubernetes/addons && sudo touch -d "0001-01-01 00:00:00 +0000" /etc/kubernetes/addons/storageclass.yaml: Process exited with status 1
output: ]
⚠️  Enabling 'storage-provisioner' returned an error: running callbacks: [sudo test -d /etc/kubernetes/addons && sudo scp -t /etc/kubernetes/addons && sudo touch -d "0001-01-01 00:00:00 +0000" /etc/kubernetes/addons/storage-provisioner.yaml: Process exited with status 1
```

The root cause is unknown.

**Comment by tstromberg** [comment]
This only happens if you run `minikube stop` in between. It seems that the new code to call mkdir only once is not executed if the host is recreated.

**Comment by limbuu** [comment]
i am facing same issue. How to solve this??
![image](https://user-images.githubusercontent.com/22807324/75115146-2256b100-5684-11ea-9d0d-0eedbeb9e266.png)

**Comment by limbuu** [comment]
@tstromberg  doing sudo minikube start --vm-driver=none solve this issue. But i want to run minikube using Virtual Box as VM.
