### ISSUE TITLE
Bug in release script, v1.7.0-beta.2 release failed

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#6457]
The jenkins release job for v1.7.0-beta.2 failed with the following error:

```
22:40:56 make: *** No rule to make target 'out/docker-machine-driver-kvm2_1.7.0~beta.2-0_amd64.deb'.  Stop.
22:40:56 make: *** Waiting for unfinished jobs....
```

Logs can be found [here](https://a646c87040050000000000000000001.proxy.googleprod.com/job/Release/153/console)

It seems the [Makefile rule](https://github.com/kubernetes/minikube/blob/master/Makefile#L544
) doesn't match the [release script](https://github.com/kubernetes/minikube/blob/master/hack/jenkins/release_build_and_upload.sh#L48):

Makefile rule:
```
out/docker-machine-driver-kvm2_$(DEB_VERSION).deb: out/docker-machine-driver-kvm2
```

Release script:

```
  make -j 16 \
  all \
  out/minikube-installer.exe \
  "out/minikube_${DEB_VERSION}-0_amd64.deb" \
  "out/minikube-${RPM_VERSION}-0.x86_64.rpm" \
  "out/docker-machine-driver-kvm2_${DEB_VERSION}-0_amd64.deb" \
  "out/docker-machine-driver-kvm2-${RPM_VERSION}-0.x86_64.rpm"
```

so either the release script or Makefile needs to be updated to match the other.

**Comment by afbjorklund** [comment]
@priyawadhwa : sorry, I missed the release script when I added the arch suffix to the packages.

**Comment by afbjorklund** [comment]
For a future release, we might want to enable KVM also for the ARM architecture...

https://blog.cloudkernels.net/posts/rpi4-64bit-virt/

> What’s interesting about the RPI4, as far as virtualization is concerned, is that it now comes with ARM’s standard GIC (Generic Interrupt Controller). Thus, unlike previous RPI generations that were wired with custom interrupt handling, virtualization is supported natively without any patching needed for interrupt emulation (and the overhead that this can incur…).

https://developer.arm.com/ip-products/system-ip/system-controllers/interrupt-controllers

**Comment by priyawadhwa** [comment]
Nice! So it looks like there's still a bug in the release script, I'll open a PR to fix this:

```
10:51:53 go build \
10:51:53 	-installsuffix "static" \
10:51:53 	-ldflags="-X k8s.io/minikube/pkg/drivers/kvm.version=v1.7.0-beta.2 -X k8s.io/minikube/pkg/drivers/kvm.gitCommitID=c426650b61f3596d3f3c550b746e19cc5c23ebb9" \
10:51:53 	-tags "libvirt.1.3.1 without_lxc" \
10:51:53 	-o out/docker-machine-driver-kvm2-1.7.0~beta.2-0.x86_64.rpm \
10:51:53 	k8s.io/minikube/cmd/drivers/kvm
10:51:53 cmd/go: unsupported GOOS/GOARCH pair linux/1.7.0~beta.2-0.x86_64.rpm
10:51:53 make: *** [out/docker-machine-driver-kvm2-1.7.0~beta.2-0.x86_64.rpm] Error 2
```

**Comment by afbjorklund** [comment]
OK, must have missed a spot! Will double-check, apparently it confuses arch and version

**Comment by afbjorklund** [comment]
Yep, reproduces here. I could swear that it Worked On My Machine before I pushed it, but...
