### ISSUE TITLE
kic with docker-env: endpoint read: connection reset by peer

### ISSUE THREAD

**Issue by balopat** [kubernetes/minikube#6463]
**The exact command to reproduce the issue**:

```bash
$ minikube start --vm-driver=docker --container-runtime=docker 
# ....
$ minikube docker-env                                                                                                                                                
export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://127.0.0.1:32778"
export DOCKER_CERT_PATH="/Users/balintp/.minikube/certs"
# Run this command to configure your shell:
# eval $(minikube docker-env)
```
Now, if I eval...

```bash
$ eval $(minikube docker-env)
echo $DOCKER_HOST
tcp://127.0.0.1:32778
# great! 
$ docker images                                                                                                                                                               
error during connect: Get https://127.0.0.1:32778/v1.40/images/json: EOF
# not that great :( 
```

**The operating system version**:
MacOSX Mojave

**Comment by afbjorklund** [comment]
I think the container runtime option (for docker driver) is quite new, it originally used `containerd`.

**Comment by tstromberg** [comment]
I was able to replicate this on Linux.

**Comment by balopat** [comment]
> I think the container runtime option (for docker driver) is quite new, it originally used `containerd`.
> 
> As a workaround you can avoid the docker-env and talk directly to same docker as minikube uses ?

The point would be to reuse the same daemon the containers are loaded from in the cluster. e.g. skaffold relies on this to avoid pushing.

**Comment by medyagh** [comment]
@balopat I can re-produce this and I have a fix for it. the problem is dockerd is not lsitening on 0.0.0.0 insice the conrtianer

**Comment by medyagh** [comment]
more details https://github.com/kubernetes/minikube/issues/6485
