### ISSUE TITLE
RHEL 8.1 none: apiserver healthz never reported healthy

### ISSUE THREAD

**Issue by shivakumarsy** [kubernetes/minikube#6465]
** [root@localhost ~]# minikube start
😄  minikube v1.6.2 on Redhat 8.1
✨  Selecting 'none' driver from existing profile (alternates: [kvm2])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing none VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🚀  Launching Kubernetes ... 

💣  Error starting cluster: apiserver healthz: apiserver healthz never reported healthy

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
[root@localhost ~]#  **

**Comment by afbjorklund** [comment]
This might be another one of those issues were SELinux is enabled on the host (not supported by kubeadm). This should be covered in the documentation and guarded by the solution detector.

**Comment by tstromberg** [comment]
Do you mind trying again with minikube v1.7.0 and sharing the output of `minikube logs`?

Thanks!

**Comment by priyawadhwa** [comment]
Hey @shivakumarsy -- I'm going to go ahead and close this issue as some time has passed. If you continue to see this issue, please reopen this at any time by including `/reopen` in your comment. Thank you!
