### ISSUE TITLE
kvm2: 'Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied

### ISSUE THREAD

**Issue by amanmirza99** [kubernetes/minikube#6468]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=1` for extra logging.

Thank you for sharing your experience!

**Comment by LasseJacobs** [comment]
I had the same issue after just installing kvm. I think the KVM module (running for my user) did not have permission to the libvirt-sock which caused the error even though my user should have the correct permission. Since it was a fresh install my user group was added but for that to take effect you have to log out and log back in. Once I did that everything worked fine.

**Comment by josedonizetti** [comment]
Had the same problem that @LasseJacobs mentioned in a recent installation. I added my user to the libvirt group in ubuntu, but it only took effect after log out/log in. 

Maybe we can do a check for this in minikube. :thinking:

**Comment by sharifelgamal** [comment]
There seems to be a solution here, so I'm going to go ahead and close this issue for now. Feel free to reopen if you need any more assistance.

**Comment by AurelienGasser** [comment]
Logging out/in didn't fix it for me on Ubuntu 19.10. However, it worked after a reboot.

**Comment by fzyzcjy** [comment]
Logging out/in works for me!

**Comment by raoofnaushad** [comment]
Faced the same issue with recent installation. Logging out/in didn't fix it for me on Ubuntu 18.04. However, it worked after a reboot.

**Comment by lsamayoa** [comment]
Had the same issue on 20.04, log out/log in did not worked had to reboot my vm.

**Comment by subhajit-halder** [comment]
> I had the same issue after just installing kvm. I think the KVM module (running for my user) did not have permission to the libvirt-sock which caused the error even though my user should have the correct permission. Since it was a fresh install my user group was added but for that to take effect you have to log out and log back in. Once I did that everything worked fine.

This works on Pop!_OS 20.10, I feel so stupid I didn't think of this before lmao

**Comment by disorder75** [comment]
Hi, had the same issue on Ubuntu 22.10, a reboot was required, after that everything worked ok.
