### ISSUE TITLE
Get minikube-v.x.x.iso.sha256: remote error: tls: access denied

### ISSUE THREAD

**Issue by kishore-05** [kubernetes/minikube#6486]
I ran the below command in cmd and the following output popped up. Can someone please help me out,thanks in advance!

COMMAND: minikube start

OUTPUT ERROR:
! minikube v1.6.2 on Microsoft Windows 10 Enterprise 10.0.16299 Build 16299
* Automatically selected the 'virtualbox' driver (alternates: [])
* Downloading VM boot image ...
*
X Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso.sha256: remote error: tls: access denied
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
It sounds like you may need to configure a proxy for your corporate environment. Please see:

https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

Let me know if this helps!

**Comment by kishore-05** [comment]
Thank you let me try it out and get back to you.



Regards,
Kishore

**Comment by medyagh** [comment]
@kishore-05  do you still have this issue?

**Comment by priyawadhwa** [comment]
Hey @kishore-05 -- hopefully it's OK if I close this, as some time has passed. If you're still seeing this issue once you've configured the network proxy, please reopen this issue by including /reopen in your comment.

Thank you!
