### ISSUE TITLE
hostPath error: Volume is already mounted to pod, but remount was requested.

### ISSUE THREAD

**Issue by carljmosca** [kubernetes/minikube#649]
BUG REPORT - v0.10.0

macOS 10.12
virtualbox
Docker version 1.12.2-rc1, build 45bed2c, experimental

CrashLoopBackOff status in pods after starting 

message in subject is from minikube logs

**Comment by r2d4** [comment]
I think the CrashLookBackOff is coming from the pods themselves.  Can you do a `kubectl describe pods POD_NAME`?  Additionally, a `minikube logs` might help you diagnose what is going wrong.

**Comment by carljmosca** [comment]
Thank you.  

Spent a bit more time on it today and I think it may be an absolute path name issue.  The examples I found had nice environment variables in them which I want(ed) to use.

Will try to create a simple example and get more specific.

The reported message is from minikube logs.  I don't recall what the describe pods returned but I will take another look now that I have a better idea of what's going on.

**Comment by r2d4** [comment]
Closing this, please feel free to reopen if you're still having issues
