### ISSUE TITLE
kic: unable to recover from attempt when Docker not running

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#6495]
If you  close Docker for Desktop, and create a cluster, it will fail with a scary error message:

`💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: create kic node: create a kic node: args: [run --cpus=2 --memory=2000mb -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run --volume /var -v /lib/modules:/lib/modules:ro --hostname docker --name docker --label io.x-k8s.kic.cluster=docker --label io.k8s.sigs.kic.role= --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.5@sha256:3ddd8461dfb5c3e452ccc44d87750b87a574ec23fc425da67dccc1f0c57d428a]  output: [docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?. See 'docker run --help'.] : exit status 125`

I think we can improve that. Additionally, if you start Docker, and try again, it fails with:

`💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: Error getting state for host: get container docker status: exit status 1`

**Comment by RA489** [comment]
This has been fixed by providing the solution message.
