### ISSUE TITLE
crash while trying to start minikube on ubuntu18.04 on proxmox

### ISSUE THREAD

**Issue by liorms** [kubernetes/minikube#6498]
liorms@k8su1804:~$ minikube start
o   minikube v1.0.1 on linux (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM
X   Error:         [VBOX_VTX_DISABLED] create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
i   Advice:        In some environments, this message is incorrect. Try 'minikube start --no-vtx-check'
-   Related issues:
    - https://github.com/kubernetes/minikube/issues/3900

*   If the above advice does not help, please let us know:
-   https://github.com/kubernetes/minikube/issues/new
liorms@k8su1804:~$ minikube start --no-vtx-check
o   minikube v1.0.1 on linux (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.897179 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

**Comment by tstromberg** [comment]
minikube v1.0 is very very old: do you mind retrying with v1.7.0?

Also, it's quite possible that proxmox does not support VirtualBox. I'm not sure what virtualization it supports, but I would suggest trying kvm2.

**Comment by liorms** [comment]
hi,
it turned up to be proxmox configuration issue.
proxmox does support vbox.
when configured ok - it even starts with older kube* versions:
liorms@k8su1804:~$ minikube start
o   minikube v1.0.1 on linux (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Restarting existing virtualbox VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.99.100
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.06.3-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
@   Downloading kubeadm v1.14.1
@   Downloading kubelet v1.14.1
-   Pulling images required by Kubernetes v1.14.1 ...
:   Relaunching Kubernetes v1.14.1 using kubeadm ...
:   Waiting for pods: apiserver proxy

liorms@k8su1804:~$ minikube status
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100

ALL WORKS...
:-)
