### ISSUE TITLE
Switch to glide from godeps

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#65]
See #33.

Glide gives more control in pinning the versions of dependencies, like k8s.io/kubernetes. It might make it easier to update to newer versions of k8s than godep currently does.

cc @ethernetdan @vishh @luxas 
Thoughts?

**Comment by vishh** [comment]
Glide still has a couple of issues that might be of concern - 

https://github.com/Masterminds/glide/issues/367
https://github.com/Masterminds/glide/issues/368
https://github.com/Masterminds/glide/issues/319

**Comment by vishh** [comment]
I'd recommend holding on to godep, until the issues mentioned above are fixed in glide. Switching to the `vendor` directory is itself a good first step.

**Comment by dlorenc** [comment]
I guess it's a case of the lesser of two evils... I just spent a few hours trying to update the kubernetes components we use, and I got stuck on https://github.com/kubernetes/kubernetes/issues/23529

:(

**Comment by luxas** [comment]
@dlorenc Which `godep` version are you using?

> Switching to the vendor directory is itself a good first step.

@vishh Don't know if you noticed, but we've used `vendor/` from the beginning :)

**Comment by dlorenc** [comment]
I've tried HEAD, 53 and 63 I think. They've all failed in different, mysterious ways. One of them left .git repos all over my vendor directory which basically broke everything.

I *almost* have stuff building with glide and k8s at head though. I'm chasing down a few int<->int32 swaps that I think @luxas was responsible for :)

I'll try to push it tomorrow to show what it looks like.

**Comment by dlorenc** [comment]
Closing this for now, we can revisit if/when k8s makes the switch.
