### ISSUE TITLE
`minikube dashboard` does not open on Windows

### ISSUE THREAD

**Issue by sebgoa** [kubernetes/minikube#651]
When trying minikube on windows (useful in training), there seems to be a problem with `minikube dashboard` command. It does not open/load in IE.

**Comment by aaron-prindle** [comment]
Could you describe in more detail the error with using `minikube dashboard`?  Does the minikube dashboard not open the browser, not render properly, etc?  Please attach a screenshot if possible, thanks.

**Comment by sebgoa** [comment]
unfortunately no, I am reporting second hand. I saw it, but did not have time to write down specifics.

Basically `minikube dashboard` command does not open the app on IE, or it opens a blank URL...bit weird.

The guys bypassed that by going to chrome.

**Comment by sebgoa** [comment]
we need to find someone with a windows box to reproduce :)

Also, folks had to install git bash to do any useful work without too much pain.

**Comment by prestonvanloon** [comment]
I can reproduce on windows 10.

![dashboard not starting](https://cloud.githubusercontent.com/assets/7246818/19349500/5017ecf2-9121-11e6-9f50-3becd9963259.png)

Nothing happens, no browsers open.

**Comment by ReeganHendry** [comment]
I have installed minikube in windows 10 and tried to launch the dashboard, in command prompt it prints Opening Kubernetes dashboard in default browser ...also it opens up the IE browser with the url http://192.168.99.100:30000/, But the page has the message like , Hmm, we cant reach the page. attaching the screen shots
![terminallog](https://cloud.githubusercontent.com/assets/22970245/19583125/b907ae76-96ff-11e6-91d9-32bb49798461.JPG)
![browser-log](https://cloud.githubusercontent.com/assets/22970245/19583124/b9074760-96ff-11e6-950d-cce275bad894.JPG)

Any thoughts about this error?

**Comment by dlorenc** [comment]
@ReeganHendry What shows up if you run:

`kubectl get services --all-namespaces`

**Comment by ReeganHendry** [comment]
![image](https://cloud.githubusercontent.com/assets/22970245/19583347/8eb9f686-9701-11e6-9688-8b2d3957ba75.png)

**Comment by dlorenc** [comment]
Hmm, it looks like the dashboard is up. Maybe you have a proxy/vpn configuration that's preventing your browser from accessing the dashboard. What happens if you use curl to access that URL from a commandline?

**Comment by ReeganHendry** [comment]
![image](https://cloud.githubusercontent.com/assets/22970245/19583385/ea3a3052-9701-11e6-9762-fd7ffeb1f996.png)

**Comment by dlorenc** [comment]
Cool! Looks like you can access that from the command line (it just can't display :) ). I'm not familiar with IE, but could you check your network proxy configuration? Something is preventing your browser from reaching that IP, even though it works from the command line.

**Comment by ReeganHendry** [comment]
Thanks dlorenc. This is not opening in Chrome as well. So should be something to do with proxy.
Will see the proxy configuration. Thanks again.

**Comment by ReeganHendry** [comment]
@dlorenc I just cleared all the existing vms in virtual box and cleared the .minikube in the home directory, then I started the minikube now the dashboard is accessible through chrome browser but not in IE. Dont know what is the exact root cause why it was not accessible earlier.

**Comment by lordvissu** [comment]
Same Issue. I get the dashboard on http://localhost:8001/ui through any browser as pointed out in the article - https://github.com/kubernetes/dashboard/blob/master/docs/user-guide/troubleshooting.md
but. the command "minikube dashboard" points to 192.168.99.100:30000 and shows the "Hmm, we can't reach..." screen as shown by @ReeganHendry .

I am new to this. Can someone please help me with this in detail?
Also, the command "minikube ssh" doesn't load boot2docker.

Using Windows Powershell, Cygwin Terminal.

**Comment by Dmitry1987** [comment]
I'm on windows 7.  minikube says 
```
Opening kubernetes dashboard in default browser...
```
and nothing happens :( .  Is it possible to add the 'print url'  function, so it'll just print to console the needed url:port, in addition to its attempt to open browser?

**Comment by aaron-prindle** [comment]
@Dmitry1987 This is in minikube currently, try running `minikube dashboard --url`

**Comment by Dmitry1987** [comment]
Thanks @aaron-prindle  :)  I didn't know (was lazy to go over all options, my bad :D )

**Comment by imranrazakhan** [comment]
For me it was default trying to open in Microsoft Edge, but its running in IE and Chrome.

**Comment by tarunkg** [comment]
It works for me like any charm in Chrome browser...:)

**Comment by pavanjava** [comment]
C:\Users\~\kubernetes-configs>minikube dashboard
* Verifying dashboard health ...

C:\Users\~\kubernetes-configs>minikube dashboard --url
* Verifying dashboard health ...

C:\Users\~\kubernetes-configs>

For me nothing happens the prompts are as above any one solved this error ? i am on windows 10 with minikube version: v1.28.0
