### ISSUE TITLE
Minikube 1.7.1 image fails to download for invalid checksum

### ISSUE THREAD

**Issue by akoranne** [kubernetes/minikube#6528]
**The exact command to reproduce the issue**: 
minikube start

**The full output of the command that failed**:<details>
○ → minikube start
🙄  minikube v1.7.1 on Darwin 10.15.1
✨  Automatically selected the hyperkit driver
💿  Downloading VM boot image ...

💣  Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.7.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.7.0.iso.sha256: EOF

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

NA

</details>

**The operating system version**:
macOS Catalina Ver 10.15.1

**Comment by akoranne** [comment]
Tried using curl and wget to download the iso image. Get following errors... 

○ → curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64 \
>   && chmod +x minikube
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to storage.googleapis.com:443




○ → wget https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
--2020-02-06 10:49:19--  https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.15.240
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.15.240|:443... connected.
Unable to establish SSL connection.

**Comment by akoranne** [comment]
Seems to work now. Closing the issue.

**Comment by exocode** [comment]
> Seems to work now. Closing the issue.

what have you done?  Have the same error:
```
> kubectl port-forward -n argocd svc/argo-cd-argocd-server 8443:443

❯ curl -v -s -X POST -k -H "Content-Type: application/json" --data '{"username":"admin","password":"'$ARGOCD_ADMIN_SECRET'"}' https://localhost:8443/api/v1/session | jq -r .token
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
} [223 bytes data]
* LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to localhost:8443
* Closing connection 0
```
