### ISSUE TITLE
feature: minikube status- indicate if using "docker-env"

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6535]
one of the common things I do after eval $(minikube docker-env) is checking if I am using my own docker or minikube's docker

it would be nice if "minikube status" command would tell me 

```
host: ...
kubelet: ..
apiserver: ...
kubeconfig: ...
docker-env: in-use
```
and if we are not using docker-env no need to add that line and keep it hidden.
but we could includ that in the json output.

**Comment by medyagh** [comment]
we still need to do this, would be happy to take PR for it

**Comment by medyagh** [comment]
we still wanna do this, but not urgnet or too important

**Comment by medyagh** [comment]
we still want to do this.

**Comment by tharun208** [comment]
@medyagh, I like to work on this
