### ISSUE TITLE
possible inverted logic ?

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6539]
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start.go#L825

**Comment by afbjorklund** [comment]
Logic looked OK to be, `driver.BareMetal(drvName)` should be the same as `local` - no ?

**Comment by medyagh** [comment]
the line code changed: I mean this one : 
why do we do validateCPUCount for none ?

validateCPUCount(driver.BareMetal(drvName))

**Comment by medyagh** [comment]
ah never mind that code is correct.
