### ISSUE TITLE
install CRIO- Per kube version

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6558]
CRI-O and Kubernetes follow the same release cycle and deprecation policy.

```
CRI-O 1.13.x - release-1.13 | Kubernetes 1.13 branch, v1.13.x | =
-- | -- | --
CRI-O 1.14.x - release-1.14 | Kubernetes 1.14 branch, v1.14.x | =
CRI-O 1.15.x - release-1.15 | Kubernetes 1.15 branch, v1.15.x | =
CRI-O 1.16.x - release-1.16 | Kubernetes 1.16 branch, v1.16.x | =
CRI-O 1.17.x - release-1.17 | Kubernetes 1.17 branch, v1.17.x | =
CRI-O HEAD - master | Kubernetes master branch | ✓

```

We have a Provisioner that has a method called Package() which is unimplented

**Comment by afbjorklund** [comment]
There is a problem with this release cycle, in that CRI-O is currently released about a month later...

So this means that you need to run with an older Kubernetes version or with an older CRI-O version.

**Days between releases:** (k8s and crio)
![release-times](https://user-images.githubusercontent.com/10364051/74081470-b6533680-4a4f-11ea-84d8-da547e2397a8.png)

There is also a lack of deb/rpm packages, for instance currently only 1.15 is available - another issue.

But the `Package` method should be fully implemented for ubuntu and for centos, see e.g. #4733

* https://github.com/docker/machine/blob/master/libmachine/provision/ubuntu_systemd.go#L52

* https://github.com/docker/machine/blob/master/libmachine/provision/redhat.go#L81

**Comment by afbjorklund** [comment]
For now we are hoping that the compability is "good enough", and run `v1.16.1` with all k8s versions.

This is the same strategy that we have for all container runtimes (docker/containerd/podman/crio)

We could change to installing `crio` the same way we install `kubeadm`, if it is deemed necessary ?

But for now it has worked, and the plan is to use `v1.17.0` with the introduction of Kubernetes 1.18

**Comment by medyagh** [comment]
you are right I have been trying to install crio in kicbase image 
the instructions on the site doesnt work https://github.com/cri-o/cri-o/issues/3232

but also I found some instructions in old forks that work manually but in a Dockerfile errors out 
```E: Sub-process /usr/bin/dpkg returned an error code (1)```

```
RUN apt-get update && apt-get install -y gnupg2 && \
    echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10/ /' > /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list && \
    curl -o Release.key https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10/Release.key && \
    apt-key add - < Release.key && apt-get update && apt-get install -y cri-o-1.16 
```

over all it is had to install any version of it, let alone different versions of it.

**Comment by afbjorklund** [comment]
> `E: Sub-process /usr/bin/dpkg returned an error code (1)`

I think this was a problem relating to `/etc/crictl.yaml` ?

Both containerd and cri-o tried to install this very same file...

Looks like a packaging error, as it _can't_ be included in the deb.

https://build.opensuse.org/project/show/devel:kubic:libcontainers:stable
