### ISSUE TITLE
unable to start minikube

### ISSUE THREAD

**Issue by timkeating1970** [kubernetes/minikube#6569]
Windows 10 pro notebook running VMware workstation pro 15 / 15.5.1 build-15018445
guest VM is Fedora workstation fc31.x86_64

Getting this error:
Unable to start VM. Please investigate and run 'minikube delete' if possible: create: precreate: exec: "docker": executable file not found in $PATH

minikube start --vm-driver=none
yields the following:
😄  minikube v1.7.2 on Fedora 31
✨  Using the none driver based on user configuration
🤹  Running on localhost (CPUs=2, Memory=3909MB, Disk=17002MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: create: precreate: exec: "docker": executable file not found in $PATH

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:

**Comment by tdevilleduc** [comment]
Is it working if you specify another vm-driver ?
For example, 
`minikube start --vm-driver=hyper-v
`

**Comment by jfmercer** [comment]
I got this to work with `minikube start --vm-driver=virtualbox`.

**Comment by timkeating1970** [comment]
This is from a VM workstation environment? I didn't think to manually input the driver to virtualbox.

**Comment by timkeating1970** [comment]
using minikube start --vm-driver=virtualbox seemed counterintuitive because I'm using VMware workstation but thank you, jfmercer, it worked!
