### ISSUE TITLE
powershell core: Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online fails

### ISSUE THREAD

**Issue by mhintzke** [kubernetes/minikube#6585]
**The exact command to reproduce the issue**:
`minikube start --vm-driver=hyperv`

**The full output of the command that failed**:<details>
```
* minikube v1.7.2 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the hyperv driver based on user configuration

! 'hyperv' driver reported an issue: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed
```
</details>

**The operating system version**:
Microsoft Windows 10 Pro 10.0.18362 Build 18362

I tried this on 2 seperate machines that I use PowerShell Core primarily from and both failed with the same error.  If I run the suspected "failed" command:

`Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online`

It seems to work just fine from Windows PowerShell so the error is at the very least misleading.  I would suggest at least putting notes in the documentation stating that it is incompatible with PS Core until the issue is fixed or update the error message to allow users to be more aware of the actual issue.

Thanks!

**Comment by codysnider** [comment]
I've got it running in PSCore on Linux Mint using the `--vm-driver=none` option and it's working great. Have you tried that?

**Comment by mhintzke** [comment]
I have not, but I am not using Linux.  This issue seems to be specifically related to minikube's ability to detect Hyper-V enablement which would only be applicable on a Windows OS.  If anyone can confirm either a reproduction of the issue or a succesful running of minikube installing under these parameters that would help.

**Comment by NoelJames** [comment]
same 

```
> minikube.exe version
minikube version: v1.7.2
commit: 50d543b5fcb0e1c0d7c27b1398a9a9790df09dfb
```

windows version 
```
> [System.Environment]::OSVersion.Version

Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      18363  0
```

Followed the advice of last failure to enable online feature

```
> Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All


Path          :
Online        : True
RestartNeeded : False
```

Rebooted windows 10, then try minikube install

```
> minikube start --memory=4G --vm-driver hyperv --hyperv-virtual-switch minikube --v=7 --alsologtostderr
I0212 06:42:23.457174    8276 notify.go:125] Checking for updates...
I0212 06:42:23.593411    8276 start.go:259] hostinfo: {"hostname":"LAPTOP-8JAKAPLQ","uptime":1082,"bootTime":1581517461,"procs":229,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"cea0e649-68e9-4d06-82a7-593b6f97a431"}
W0212 06:42:23.594175    8276 start.go:267] gopshost.Virtualization returned error: not implemented yet
* minikube v1.7.2 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
I0212 06:42:23.599204    8276 driver.go:199] Setting default libvirt URI to qemu:///system
* Using the hyperv driver based on user configuration
I0212 06:42:25.622355    8276 start.go:306] selected driver: hyperv
I0212 06:42:25.622355    8276 start.go:612] validating driver "hyperv" against <nil>
I0212 06:42:25.623320    8276 start.go:618] status for hyperv: {Installed:false Healthy:false Error:C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:
 Fix:Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All' Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/}

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed
```

the output of WindowsOptionalFeature 

```
> Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online


FeatureName      : Microsoft-Hyper-V-All
DisplayName      : Hyper-V
Description      : Provides services and management tools for creating and running virtual machines and their
                   resources.
RestartRequired  : Possible
State            : Enabled
CustomProperties :
```

**Comment by NoelJames** [comment]
Using --force as suggested in this issue get me started  and the vm started up #6579

**Comment by codysnider** [comment]
Just looked into the [source where this checks for hyperv availability](https://github.com/kubernetes/minikube/blob/239be7ed941c73a9b5b0b4d1833f23c19b29c0e2/pkg/minikube/registry/drvs/hyperv/hyperv.go#L92) and I think the underlying issue is something that can't really be scripted away: You'll need to run the Powershell session with elevated permissions (as administrator).

**Comment by NoelJames** [comment]
Was running as admin - sorry should have mentioned that. The related issue i posted in my last comment fixed the issue for me.

**Comment by medyagh** [comment]
@mhintzke  in 1.7.3 we added a feature to auto create virtual switches. do you mind trying with 1.7.3 ?

**Comment by medyagh** [comment]
@mhintzke do you still have this issue, have you had the chance to try with latest release ?

**Comment by asatrur** [comment]
I tried this with the v1.8.0 of minikube on W10 and an admin powershell instance.

**Comment by medyagh** [comment]
> I tried this with the v1.8.0 of minikube on W10 and an admin powershell instance.

@asatrur what was the error ?
