### ISSUE TITLE
kic: create container should verify it is running

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6587]
after we create a container we need to verify the status is "running" as opposed to "starting"
before we proceed to next commands.

this happens rarely but on podman I saw this:
```
 Error: cannot exec into container that is not running: container state improper
: exit status 126
```
which means we tried too early to run commands inside the container.

**Comment by medyagh** [comment]
this was done.

**Comment by Amaelb** [comment]
On which version is it resolved ?
It is still happening with minikube-1.9.2-0.x86_64.rpm
