### ISSUE TITLE
failed to download minikube iso

### ISSUE THREAD

**Issue by grigorei** [kubernetes/minikube#6594]
I'm trying to learn kubernetes in order to understand the concepts of native clouding - I'm a completely beginner to that. So I'm using the instructions from internet to activate the hyper-v on Windows- 10 (I got a Windows 10 VM as playground and for Internet access I'm going via an http proxy), install kubernetctl and minikube. Trying to start minikube returns an error - below
**The exact command to reproduce the issue**:
C:\WINDOWS\system32>minikube start --vm-driver="hyperv" --hyperv-virtual-switch="Minikube"

**The full output of the command that failed**:<details>
! minikube v1.7.2 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the hyperv driver based on user configuration
* Downloading VM boot image ...
*
X Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.7.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.7.0.iso.sha256: dial tcp 172.217.22.16:443: connectex: Ein Verbindungsversuch ist fehlgeschlagen, da die Gegenstelle nach einer bestimmten Zeitspanne nicht richtig reagiert hat, oder die hergestellte Verbindung war fehlerhaft, da der verbundene Host nicht reagiert hat.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\WINDOWS\system32>

</details>

**The output of the `minikube logs` command**:<details>
C:\WINDOWS\system32>minikube logs
*
X Error getting config: cluster "minikube" does not exist
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\WINDOWS\system32>windows 

</details>

**The operating system version**:
Windows 10 Pro

**Comment by medyagh** [comment]
@grigorei do you happen to be in a VPN or a network that doesn't have access to download from gcs ? 
does it let you to download this file manually ?
https://storage.googleapis.com/minikube/iso/minikube-v1.7.0.iso

**Comment by priyawadhwa** [comment]
Hey @grigorei -- any update here?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by irtaza909** [comment]
> @grigorei do you happen to be in a VPN or a network that doesn't have access to download from gcs ?
> does it let you to download this file manually ?
> https://storage.googleapis.com/minikube/iso/minikube-v1.7.0.iso

i have the same problem, yes it is downloading manually.
