### ISSUE TITLE
none: certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error

### ISSUE THREAD

**Issue by rafal0502** [kubernetes/minikube#6596]
**The exact command to reproduce the issue**:
sudo minikube start --vm-driver=none

**The full output of the command that failed**:<details>
Error starting cluster: running cmd: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.2:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.2:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": exit status 1
stdout:
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk

stderr:
W0212 17:28:32.301880   14377 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0212 17:28:32.301919   14377 validation.go:28] Cannot validate kubelet config - no validator is available
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error
To see the stack trace of this error execute with --v=5 or higher
</details>

**The output of the `minikube logs` command**:<details>
 Problems detected in kube-apiserver [f654adffe76d]:
    I0212 16:28:32.336059       1 log.go:172] http: TLS handshake error from [::1]:53068: remote error: tls: bad certificate
    I0212 16:28:32.337558       1 log.go:172] http: TLS handshake error from [::1]:53070: remote error: tls: bad certificate
    I0212 16:28:32.339849       1 log.go:172] http: TLS handshake error from [::1]:53066: remote error: tls: bad certificate

</details>

**The operating system version**:
VERSION="18.04.3 LTS (Bionic Beaver)"

**Comment by tstromberg** [comment]
There appears to be a certificate mismatch for unknown reasons. Can you try running `minikube delete` to see if it fixes it?

**Comment by sharifelgamal** [comment]
@rafal0502 do you still need help here?

**Comment by tstromberg** [comment]
It's unclear whether or not this error still happens in minikube v1.9.x. Comments welcome!

**Comment by nickbryan** [comment]
Hi guys, I ran into this issue just now and followed the link to this thread. Tried `minikube delete` with the `--purge` and `--all` flags but no luck fixing it. My minikube cluster was running fine, tried deleting it to start fresh but once started back up everything still remained.  Tried with the purge flag, started back up and then got this error message.

Any help would be appreciated or if there is anything i can to do help debug this i woud be happy to.

**Comment by nickbryan** [comment]
Hmm, running `docker system prune` seemed to fix my issue.

**Comment by dmyoung-tx** [comment]
Was having the same issue and ran "minikube delete --purge --all" and "docker system prune"; fixed my issue.

**Comment by wknickless** [comment]
If using the SSH driver, after doing the ```minikube delete --purge --all``` you might also try ```ssh root@<IP address> "find /var/lib/minikube/certs -type f | perl -ne 'print;chop;unlink;'"```
