### ISSUE TITLE
HTTP_PROXY variable not passed to pods

### ISSUE THREAD

**Issue by aldib** [kubernetes/minikube#6598]
Hi,

I'm testing `minikube` with the following configuration:

* Windows 10 (Host OS)
* CENT OS 8.1 (Running as Linux Guest with VMWare workstation under Windows 10)
* Minikube 1.7.2 + kvm2 driver (Running as Linux Guest with KVM under CENT OS)

I start `minkube` with the following command:

```
minikube start --cpus 2 --memory 2048MB --disk-size 5GB  --docker-env HTTP_PROXY=${HTTP_PROXY} --docker-env HTTPS_PROXY=${HTTPS_PROXY} --docker-env NO_PROXY=${NO_PROXY}
```

If I run a docker container directly:
```
eval $(minikube docker-env)
docker run -it --rm alpine /bin/sh
env
```
I can see that the HTTPS_PROXY, HTTPS_PROXY and NO_PROXY are set in the container.
However, if I run a container inside a pod:
```
kubectl apply -f https://k8s.io/examples/application/shell-demo.yaml
#Wait until STATUS=running
kubectl exec -it shell-demo -- /bin/bash
env
```
The HTTPS_PROXY, HTTPS_PROXY and NO_PROXY are **NOT** set in the container.

Is this expected behaviour? If yes, how do I pass the variables automatically without defining them in the k8s descriptor?

Thanks

Alex

**Comment by medyagh** [comment]
@aldib 
Hi Alex thanks for asking this question,
I am not sure if minikube is supposed to inject envs into pods, but should inject  the env to the docker-daemon that kubernetes is using.

and the host itself.

is there any reason that you would think minikube should do that ? is there a scenario that fails and you need that to happen ?

**Comment by aldib** [comment]
I agree that minikube is not supposed to inject envs into pods directly, but why is there a difference in behaviour when running a container with the docker client vs kubectl? Are they not both using the same docker daemon inside the minkube VM?

Maybe I'm missing something; what is the expected behaviour of passing `--docker-env HTTP_PROXY=${HTTP_PROXY}` with the start command?

**Comment by aldib** [comment]
I figured it out. The HTTPS_PROXY, HTTPS_PROXY and NO_PROXY variables are passed to the containers by the docker client if defined in the environment. kubectl does not behave in the same way, but it is possible to achieve a similar result using a PodPreset
