### ISSUE TITLE
Switching between k8s releases can cause minikube to fail to start

### ISSUE THREAD

**Issue by wstrange** [kubernetes/minikube#660]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Minikube version** (use `minikube version`):

minikube version: v0.10.0

**Environment**:
- **OS** (e.g. from /etc/os-release): mac os Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
  
  "DriverName": "xhyve",

**What happened**:

minikube stop
followed by 
minikube start

minikube would not come up
Logs:
 minikube logs
==> /var/lib/localkube/localkube.err <==
Starting etcd...
==> /var/lib/localkube/localkube.out <==
I1005 17:05:30.568498    1301 server.go:202] Using iptables Proxier.
I1005 17:05:30.568610    1301 server.go:215] Tearing down userspace rules.
E1005 17:05:30.602168    1301 reflector.go:205] pkg/proxy/config/api.go:30: Failed to list *api.Service: Get http://127.0.0.1:8080/api/v1/services?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
E1005 17:05:30.602255    1301 reflector.go:205] pkg/proxy/config/api.go:33: Failed to list *api.Endpoints: Get http://127.0.0.1:8080/api/v1/endpoints?resourceVersion=0: dial tcp 127.0.0.1:8080: getsockopt: connection refused
2016-10-05 17:05:30.662443 I | etcdserver: recovered store from snapshot at index 70007
2016-10-05 17:05:30.662486 I | etcdserver: name = kubeetcd
2016-10-05 17:05:30.662493 I | etcdserver: data dir = /var/lib/localkube/etcd
2016-10-05 17:05:30.662502 I | etcdserver: member dir = /var/lib/localkube/etcd/member
2016-10-05 17:05:30.662508 I | etcdserver: heartbeat = 100ms
2016-10-05 17:05:30.662513 I | etcdserver: election = 1000ms
2016-10-05 17:05:30.662519 I | etcdserver: snapshot count = 10000
2016-10-05 17:05:30.662531 I | etcdserver: advertise client URLs = http://localhost:2379
2016-10-05 17:05:30.662585 W | wal: ignored file 0.tmp in wal
panic: runtime error: makeslice: len out of range
goroutine 1 [running]:
panic(0x3297740, 0xc820869800)
    /usr/local/go/src/runtime/panic.go:464 +0x3e6

**What you expected to happen**:

minikube to start

**How to reproduce it** (as minimally and precisely as possible):

I created the VM using k8s version 1.4.0, but I believe minikube thought it was a previous release.
My desktop kubectl command was potentially 1.3.x - (since upgraded to 1.4) - not sure if this is relevant.

**Anything else do we need to know**:
The problem was resolved by doing a:

minikube stop
minikube config set kubernetes-version v1.4.0
minikube start

**Comment by r2d4** [comment]
This should be working with an upgrade from 1.6 -> 1.7
