### ISSUE TITLE
Failed to start the virtual machine 'minikube' because one of the Hyper-V components is not running.

### ISSUE THREAD

**Issue by aamirsaleemkudcs** [kubernetes/minikube#6601]
* minikube v1.7.2 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* Using the hyperv driver based on user configuration
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0212 20:25:19.520105    8980 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Failed to start the virtual machine 'minikube' because one of the Hyper-V components is not running.
'minikube' failed to start. (Virtual machine ID BB941297-CFAA-41F2-8491-A6A7A36568D5)
The Virtual Machine Management Service failed to start the virtual machine 'minikube' because one of the Hyper-V
components is not running (Virtual machine ID BB941297-CFAA-41F2-8491-A6A7A36568D5).
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: exit status 1
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
**The operating system version**:

**Comment by aamirsaleemkudcs** [comment]
minikube version: v1.7.2
commit: 50d543b5fcb0e1c0d7c27b1398a9a9790df09dfb

**Comment by medyagh** [comment]
cc @blueelvis

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
