### ISSUE TITLE
minikube does not start in ubuntu

### ISSUE THREAD

**Issue by naveeniitbhu** [kubernetes/minikube#6611]
Hello, 
I am trying to setup minikube and facing some problem in the process. I have already installed virtualbox and minikube. 
When i execute the below command:
sudo minikube start --vm-driver=virtualbox

I get the below output:
😄  minikube v1.7.2 on Ubuntu 18.04
✨  Using the virtualbox driver based on user configuration
🛑  The "virtualbox" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --vm-driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/

I cant seem to understand the problem. What is the issue here? Why my clusters are not starting?

**Comment by afbjorklund** [comment]
If you remove the “sudo”, does it work ? Next question would be why you added it, is there some documentation somewhere that needs updating (it’s not needed)

**Comment by naveeniitbhu** [comment]
First I ran it without sudo, it shows the permission denied error for .netrc file. So, I thought to try it with sudo.

**Comment by afbjorklund** [comment]
Okay, so it is #5643

**Comment by naveeniitbhu** [comment]
Yes, closing it here. Will continue in that thread.

**Comment by afbjorklund** [comment]
If your regular file has the wrong permissions (not readable), you can use $NETRC to point to another one (possibly non-existent)
