### ISSUE TITLE
none: [kubelet-check] Initial timeout of 40s passed.

### ISSUE THREAD

**Issue by altanai** [kubernetes/minikube#6612]
**The exact command to reproduce the issue**:
minikube start --vm-driver=none

**The full output of the command that failed**:<details>

💣  Error starting cluster: init failed. cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap\"": command failed: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap"
stdout: [init] Using Kubernetes version: v1.16.2
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [minikube localhost] and IPs [172.31.45.21 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [minikube localhost] and IPs [172.31.45.21 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition

This error is likely caused by:
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'

stderr: 	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING FileExisting-socat]: socat not found in system path
	[WARNING Hostname]: hostname "minikube" could not be reached
	[WARNING Hostname]: hostname "minikube": lookup minikube on 127.0.0.53:53: server misbehaving
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher
: exit status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

</details>

**The output of the `minikube logs` command**:<details>

Feb 13 11:27:22 x.x.x.xkubelet[14474]: I0213 11:27:22.506701   14474 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Feb 13 11:27:22 x.x.x.xkubelet[14474]: E0213 11:27:22.510295   14474 remote_image.go:87] ImageStatus "k8s.gcr.io/etcd:3.3.15-0" from image service failed: rpc error: code = Unknown desc = Error response from daemon: stat /var/lib/docker/overlay2/f0ba2516cb48ed7f2932fc857fc9bffb65486d3a2140327b3626bc02e023a9e6: no such file or directory
Feb 13 11:27:22 x.x.x.xkubelet[14474]: E0213 11:27:22.510465   14474 kuberuntime_image.go:85] ImageStatus for image {"k8s.gcr.io/etcd:3.3.15-0"} failed: rpc error: code = Unknown desc = Error response from daemon: stat /var/lib/docker/overlay2/f0ba2516cb48ed7f2932fc857fc9bffb65486d3a2140327b3626bc02e023a9e6: no such file or directory
Feb 13 11:27:22 x.x.x.xkubelet[14474]: E0213 11:27:22.510612   14474 kuberuntime_manager.go:783] container start failed: ImageInspectError: Failed to inspect image "k8s.gcr.io/etcd:3.3.15-0": rpc error: code = Unknown desc = Error response from daemon: stat /var/lib/docker/overlay2/f0ba2516cb48ed7f2932fc857fc9bffb65486d3a2140327b3626bc02e023a9e6: no such file or directory
Feb 13 11:27:22 x.x.x.xkubelet[14474]: E0213 11:27:22.510741   14474 pod_workers.go:191] Error syncing pod cbf3a546ddd8dfd445b9172b12b57c34 ("etcd-minikube_kube-system(cbf3a546ddd8dfd445b9172b12b57c34)"), skipping: failed to "StartContainer" for "etcd" with ImageInspectError: "Failed to inspect image \"k8s.gcr.io/etcd:3.3.15-0\": rpc error: code = Unknown desc = Error response from daemon: stat /var/lib/docker/overlay2/f0ba2516cb48ed7f2932fc857fc9bffb65486d3a2140327b3626bc02e023a9e6: no such file or directory"
Feb 13 11:27:22 x.x.x.xkubelet[14474]: E0213 11:27:22.562355   14474 kubelet.go:2267] node "minikube" not found

</details>

**The operating system version**:
minikube v1.5.2 on Ubuntu 18.04
🤹  Running on localhost (CPUs=2, Memory=3705MB, Disk=19788MB) ...
ℹ️   OS release is Ubuntu 18.04.3 LTS
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.7' ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

Earnestly looking forward to a speedy response / hint / anything .

**Comment by tstromberg** [comment]
That is a very very old version of minikube. Do you mind trying with v1.7.x?

If it still fails, please share the output of `minikube start --alsologtostderr --vm-driver=none`

**Comment by priyawadhwa** [comment]
Hey @altanai are you still seeing this issue?

**Comment by altanai** [comment]
It works now . @tstromberg  @priyawadhwa
