### ISSUE TITLE
use docker apt-repo for installing docker base image

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6627]
comment from @afbjorklund 
```
@medyagh : supposedly you could switch repositories, from ubuntu to docker ?https://docs.docker.com/install/linux/docker-ce/ubuntu/sudo add-apt-repository \    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \    $(lsb_release -cs) \    stable"That will get you the newer versions:containerd.io_1.2.12-1_amd64.deb docker-ce-cli_19.03.6~3-0~ubuntu-eoan_amd64.deb docker-ce_19.03.6~3-0~ubuntu-eoan_amd64.deb
--


```

**Comment by afbjorklund** [comment]
We use docker binaries from the same place (docker.com), for the regular minikube ISO install.

i.e. https://download.docker.com/linux/static/stable/x86_64/

**Comment by afbjorklund** [comment]
The reason for switching from distro to vendor, was just to get a slightly newer minor version...

https://packages.ubuntu.com/eoan/docker.io (19.03.2)

**Comment by afbjorklund** [comment]
@medyagh : skipping this feature ?
