### ISSUE TITLE
virtualbox: Unable to start VM. creating: Maximum number of retries (5) exceeded

### ISSUE THREAD

**Issue by adarsh-m** [kubernetes/minikube#6631]
I am trying to spin up VM using minikube but facing issue.

**The exact command to reproduce the issue**
minikube start --vm-driver=virtualbox

**The full output of the command that failed**:
minikube v1.7.2 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* Using the virtualbox driver based on user configuration
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: Maximum number of retries (5) exceeded
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**The output of the `minikube logs` command**:
command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**The operating system version**: Windows 10 pro

**Comment by SaiBalaguru** [comment]
I am facing the same issue. Someone please help!

**Comment by timramone** [comment]
Have the same issue :(

**Comment by s709t** [comment]
i'm facing the same issue, this has become annoying, that error doesn't show anything relevant

**Comment by premanr** [comment]
I am also getting same issue, any workaround?

**Comment by SaiBalaguru** [comment]
somehow it got resolved me!

**Comment by SaiBalaguru** [comment]
If you are connected to your corporate network - disconnect. So connect to a restriction free one. 
Secondly, after creating a kubernetes folder in C drive, type "kubectl config"
then "minikube config" .
Now "minikube start".
Then "minikube SSH".

This helps for Oracle Virtual Box in windows 10.

**Comment by derektumulak** [comment]
I am running into the same issue here, running HyperV on Windows 10.

**Comment by tstromberg** [comment]
@adarsh-m - are you still running into this?

It would be helpful to get this information:

`minikube start --alsologtostderr -v=3`

That should reveal the source of the failure. I'm betting there is a VirtualBox misconfiguration or corruption of some sort.

**Comment by tstromberg** [comment]
@derektumulak - Sorry to hear that. Please open another issue for non-virtualbox issues, with the output of `minikube start --alsologtostderr -v=3`.

It would also be helpful to know if `minikube start --driver=docker` works.

**Comment by derektumulak** [comment]
Hi Thomas, thank you for the reply but unfortunately I don't have this
environment up and running any longer.

Best,
-Derek

**Comment by tstromberg** [comment]
Closed, as this creation behavior no longer occurs in minikube v1.7.

**Comment by VRay27** [comment]
@tstromberg Hi, I am facing the same issue. 
Windows, Virtual Box
minikube start --vm-driver=virtualbox

Error :  libmachine: Error dialing TCP: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.

minikube version: v1.12.3

Could you please advise?
