### ISSUE TITLE
Symlink create failure

### ISSUE THREAD

**Issue by johnsje** [kubernetes/minikube#6639]
**The exact command to reproduce the issue**:

minikube start

**The full output of the command that failed**:<details>

🔄  Relaunching Kubernetes using kubeadm ...
E0214 12:40:25.030601   58601 kubeadm.go:455] failed to create compat symlinks: create symlink failed: sudo ln -s /data/minikube /var/lib/minikube/etcd: Process exited with status 1

💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared
---
I did not install as root. 
</details>

**The output of the `minikube logs` command**:<details>

2019/10/23 14:44:51 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.

==> storage-provisioner ["b1dd4014a50c"] <==
E0214 12:45:27.838764   59017 logs.go:153] command /bin/bash -c "docker logs --tail 60 "b1dd4014a50c"" failed with error: Process exited with status 1 output: "\n** stderr ** \nerror from daemon in stream: Error grabbing logs: EOF\n\n\n** /stderr **"

💣  Error getting machine logs: unable to fetch logs for: storage-provisioner ["b1dd4014a50c"]

</details>

**The operating system version**:
Darwin VWGOAAHL317887 17.7.0 Darwin Kernel Version 17.7.0: Thu Jan 23 07:05:23 PST 2020; root:xnu-4570.71.69~1/RELEASE_X86_64 x86_64

**Comment by sharifelgamal** [comment]
@johnsje could you retry your minikube start with `minikube start -v=5 --alsologtostderr`? That might give us more information on why creating the symlink failed.

**Comment by johnsje** [comment]
I'm not able to reproduce now. I was at the time the above was create trying to install kubecost. I do now have a different minikube version (1.5.2). I think I was on 1.4.x before. Sorry I can't provide more detail.
