### ISSUE TITLE
hyperv: powershell Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed

### ISSUE THREAD

**Issue by dlopatin-ms** [kubernetes/minikube#6640]
![image](https://user-images.githubusercontent.com/44682905/74560313-5bea3680-4f77-11ea-84ce-fd1b40e8aceb.png)
HiperV installed, works fine with Docker desktop, also installed GCloud with kubectl (works fine too).

I tried to start with virual-switch :
minikube start --vm-driver hyperv --hyperv-virtual-switch "minikube"
with flag --force
Result the same.
Can someone explain what I do wrong?

**Comment by detroyejr** [comment]
Launch your shell as an admin. Then try again.

**Comment by dlopatin-ms** [comment]
> Launch your shell as an admin. Then try again.

I did, I always use shell from admin.

**Comment by detroyejr** [comment]
Got it. Can you provide more info? What's the output of `minikube start --alsologtostderr -v=7`?

**Comment by dlopatin-ms** [comment]
@detroyejr sure, thanks for helping.
![image](https://user-images.githubusercontent.com/44682905/74562290-8c33d400-4f7b-11ea-9838-1954e382b7a4.png)

**Comment by detroyejr** [comment]
Wouldn't know offhand why it can't find hyperv unless it's really just not installed. Can you double check that you have everything Enabled? What's the output of `Get-WindowsOptionalFeature -Online | Where-Object {$_.State -eq "Enabled"} | Format-Table`? Is it showing everything HyperV related enabled?

**Comment by dlopatin-ms** [comment]
@detroyejr I did everything from the official tutorial.
![image](https://user-images.githubusercontent.com/44682905/74563214-57c11780-4f7d-11ea-8f95-7f5b7e790926.png)

**Comment by detroyejr** [comment]
Yeah, really not sure how to help assuming you're running as admin and HyperV is setup the normal way.

Just as a sanity check, make sure you're really running admin.
```
Begin {
    #Checks if the user is in the administrator group. Warns and stops if the user is not.
    if (-NOT ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {
        Write-Warning "You are not running this as local administrator. Run it again in an elevated prompt." ; break
    }
}
```

You could also try deleting the `.minikube` folder in your user directory and seeing if that helps.

**Comment by dlopatin-ms** [comment]
![image](https://user-images.githubusercontent.com/44682905/74564947-32cea380-4f81-11ea-966d-b8795f936a28.png)
I deleted .minikube folder with all subfolders - result the same :(

**Comment by detroyejr** [comment]
What version of minikube are you using? Latest version?

**Comment by KhangLe96** [comment]
I have the same problem with the latest version 1.7.2

**Comment by dlopatin-ms** [comment]
> What version of minikube are you using? Latest version? Does the same problem exist in in 1.6.2?

Yes, I used the latest version. I will try to reinstal prev version to check

**Comment by KhangLe96** [comment]
Adding --force to the command has solved the problem for me

**Comment by tstromberg** [comment]
Do you mind sharing the output from powershell of the following command:

`Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online`

Thanks!

**Comment by jbcripe68** [comment]
I am having the same problem with v1.7.3.  When I do a systemInfo I get two Hyper-V network cards:

PS C:\WINDOWS\system32> systeminfo

Host Name:                 DESKTOP-C1H04CG
OS Name:                   Microsoft Windows 10 Enterprise
...
Network Card(s):           5 NIC(s) Installed.
                           [01]: Zscaler Network Adapter 1.0.2.0
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [02]: Intel(R) Ethernet Connection (2) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     172.19.217.4
                                 IP address(es)
                                 [01]: 10.114.57.81
                                 [02]: fe80::6911:6481:774e:f71f
                           [03]: Intel(R) Dual Band Wireless-AC 8260
                                 Connection Name: Wi-Fi
                                 Status:          Hardware not present
                           [04]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (Default Switch)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.17.172.193
                                 [02]: fe80::652a:c05e:3e43:1917
                           [05]: Hyper-V Virtual Ethernet Adapter
                                 Connection Name: vEthernet (nat)
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.19.176.1
                                 [02]: fe80::31f9:a0d1:c117:8e47
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

Could this be the problem???

**Comment by jbcripe68** [comment]
I also notice if I run the failing command it works:

PS C:\WINDOWS\system32> minikube start --vm-driver hyperv
! minikube v1.7.3 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
* Using the hyperv driver based on user configuration

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe **Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online** failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed
PS C:\WINDOWS\system32> Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online


FeatureName      : Microsoft-Hyper-V-All
DisplayName      : Hyper-V
Description      : Provides services and management tools for creating and running virtual machines and their
                   resources.
RestartRequired  : Possible
State            : Enabled
CustomProperties :

**Comment by Tallyrald** [comment]
This happened to me right after I installed the latest Windows update packages (KB4535996 & KB4537572 & KB4052623). Same error messages, same everything as OP on minikube v1.7.3. Before the update, everything worked fine. Current Windows build number is Microsoft Windows 10 Pro Build 18363.
Is it possible that Microsoft changed how the HyperV driver reports back it's status and minikube's validation simply cannot read it properly?

Using the --force flag solved the problem for me too.

**Comment by sharifelgamal** [comment]
This should be fixed in the latest version of minikube, starting with 1.8. I'll go ahead and close this, feel free to reopen if it continues to be a problem.
