### ISSUE TITLE
Prevent minikube profile command to create profile

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6647]
one un-intentional side effect of minikube profile command is creating a new profile.

minikube profiles should only be created by minikube start.

so if you by mistake do

```
minikube profile lis
```

(instead of list)

it will create an abandoned profile called list.
I would like to disable the creation of profile by minikube profile command.

however, 'minikube profile pname'
should still change the profile to 'pname' if it exists. but should not create a new one.

and it shoud also send a nice message to the user if it doesnt exist.

"The profie lis doesnt exist, if you want to create a profile you can by this command
minikube start -p lis
"

**Comment by vikkyomkar** [comment]
@medyagh I will take-up this issue and create a PR

**Comment by medyagh** [comment]
@vikkyomkar  it is yours ! please let me know what time you think you could make this. to see if we should include it in this milestone.

**Comment by aallbrig** [comment]
@medyagh I see there is no PR open for this issue. I'm going to try my hand at a solution.

**Comment by aallbrig** [comment]
> however, 'minikube profile pname'
> should still change the profile to 'pname' if it exists. but should not create a new one.

@medyagh I think I have a solution but I am having problems confirming behavior you reported as being expected. **I don't think `minikube profile pname` changes `profile` to `pname`**.

I'm going to open a PR soon but I wanted to know more about this behavior you had described.

<img width="717" alt="Screenshot 2020-02-17 18 53 24" src="https://user-images.githubusercontent.com/3106250/74693191-a1e20d00-51b8-11ea-9271-627d8704bdc9.png">
<img width="718" alt="Screenshot 2020-02-17 18 53 33" src="https://user-images.githubusercontent.com/3106250/74693193-a4446700-51b8-11ea-96ee-567be90ba271.png">
<img width="717" alt="Screenshot 2020-02-17 18 53 43" src="https://user-images.githubusercontent.com/3106250/74693195-a6a6c100-51b8-11ea-94ce-51624b9b0422.png">
<img width="718" alt="Screenshot 2020-02-17 18 53 54" src="https://user-images.githubusercontent.com/3106250/74693198-a8708480-51b8-11ea-8bee-7922182ce941.png">
<img width="717" alt="Screenshot 2020-02-17 18 54 01" src="https://user-images.githubusercontent.com/3106250/74693203-aa3a4800-51b8-11ea-8d8f-dbe7c603872a.png">
<img width="720" alt="Screenshot 2020-02-17 19 04 47" src="https://user-images.githubusercontent.com/3106250/74693206-ac040b80-51b8-11ea-9f85-b01dc4913e85.png">
