### ISSUE TITLE
getting kubeadm bootstrapper: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by tym0114** [kubernetes/minikube#6648]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by tstromberg** [comment]
您介意添加一些其他详细信息吗？ 以下是其他有用的信息：

*使用的确切`minikube start`命令行
* minikube start命令的完整输出，最好使用--alsologtostderr来进行额外的日志记录。

感谢您分享经验！
