### ISSUE TITLE
minikube start 失败

### ISSUE THREAD

**Issue by tym0114** [kubernetes/minikube#6650]
**重现问题所需的命令**：minikube start --vm-driver virtualbox

**失败的命令的完整输出**：<details>

* Microsoft Windows 10 Home China 10.0.18362 Build 18362 上的 minikube v1.6.2
* Selecting 'virtualbox' driver from user configuration (alternates: [])
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\tongy\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**： minikube version: v1.6.2 
win10

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

do you mind trying

minikube delete --all 
and then
minikube start --alsologtostderr -v=8

**Comment by priyawadhwa** [comment]
Hello. I'm going to close this as some time has passed.

If you try running:

```
minikube delete --all
minikube start --alsologtostderr
```

and it doesn't work, please reopen at any time by including /reopen in your comment. 


你好。随着时间的流逝，我将关闭此功能。

如果尝试运行：

```
minikube delete --all
minikube start --alsologtostderr
```

而且它不起作用，请随时在评论中加入/ reopen来重新打开。
