### ISSUE TITLE
failed to connect to the hypervisor while minikube starting

### ISSUE THREAD

**Issue by vinaychaudharyofficial** [kubernetes/minikube#6653]
Below is the KVM permission.

~$ sudo ls -la /var/run/libvirt/libvirt-sock
srwxrwx--- 1 root libvirtd 0 Feb 16 11:24 /var/run/libvirt/libvirt-sock
~$ ls -l /dev/kvm
crw-rw----+ 1 root libvirtd 10, 232 Feb 16 11:24 /dev/kvm

**The exact command to reproduce the issue**: minikube start --vm-driver=kvm2

**The full output of the command that failed**:<details>
 'kvm2' driver reported an issue: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor

</details>

**The output of the `minikube logs` command**:<details>

~$ minikube start --vm-driver=kvm2
😄  minikube v1.6.2 on Ubuntu 16.04
✨  Selecting 'kvm2' driver from user configuration (alternates: [none])

⚠️  'kvm2' driver reported an issue: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor
error: no valid connection
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
💡  Suggestion: Follow your Linux distribution instructions for configuring KVM
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/

💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [KVM_CONNECTION_ERROR] Error getting state for host: getting connection: getting domain: error connecting to libvirt socket.: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied')
💡  Suggestion: Have you set up libvirt correctly?
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/

</details>

**The operating system version**:  Ubuntu 16.04.6 LTS

**Comment by medyagh** [comment]
@vinaychaudharyofficial I wonder if the livirt is in the right user group ? could you check on the kvm docs ? or try to re-install libvirt (not just kvm)

**Comment by medyagh** [comment]
cc @josedonizetti

**Comment by vinaychaudharyofficial** [comment]
> @vinaychaudharyofficial I wonder if the livirt is in the right user group ? could you check on the kvm docs ? or try to re-install libvirt (not just kvm)

@medyagh Issue fixed, After check KVM docs and re-installation of KVM and libvirt. Thanks

**Comment by vinaychaudharyofficial** [comment]
Issue fixed, After re-installation of KVM and libvirt.
