### ISSUE TITLE
How to create cross-cluster DNS between multiple minikube instances

### ISSUE THREAD

**Issue by dbecher-ito** [kubernetes/minikube#6658]
My question is more of a general sort, namely:

When running minikube, e.g., on macOS, is there some way to achieve cross-cluster dns resolution? E.g., I want to be able to spin-up two minikube cluster, one accessible via `cluster1.example.org`, one at `cluster2.example.org` and I also want to be able to run

```shell
nslookup cluster1.example.org
nslookup cluster2.example.org
```

on either of them. Do I have to spin-up a DNS Server, where I put these records and change the `coreDNS` config on both of these machines or how does it work? I would really appreciate some of you helping me out.

All the best,
David

**Comment by medyagh** [comment]
@dbecher-ito that is an interesting question, do you mind sharing what is a use case for this ?

the answer would different based on the driver and the os you are using.
for example on hyperkit on mac would be different with kvm on linux

**Comment by priyawadhwa** [comment]
Hey @dbecher-ito, just a friendly ping in case you're still trying to accomplish this.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
