### ISSUE TITLE
minikube service kuberappdemo not working .. POD status ImagePullBackOff  

### ISSUE THREAD

**Issue by vinaychaudharyofficial** [kubernetes/minikube#6663]
Running below command (kuberappdemo is the image file created in docker manually)

kubectl create deployment kuberappdemo --image=kuberappdemo
kubectl expose deployment kuberappdemo --type=LoadBalancer --port=8080

After the below command mentioned error coming and kuberappdemo has not been exposed and even not in browser.
 
Below command was also run to know the status.
$kubectl get all
NAME                                READY   STATUS             RESTARTS   AGE
pod/kuberappdemo-7df7d6d788-87xsw   0/1     ImagePullBackOff   0          28m

**The exact command to reproduce the issue**: minikube service kuberappdemo

**The full output of the command that failed**:<details>

[23011:23027:0217/165740.204353:ERROR:browser_process_sub_thread.cc(203)] Waited 10 ms for network service

</details>

**The output of the `minikube logs` command**:<details>

 minikube service kuberappdemo
|-----------|--------------|-------------|-----------------------------|
| NAMESPACE |     NAME     | TARGET PORT |             URL             |
|-----------|--------------|-------------|-----------------------------|
| default   | kuberappdemo |             | http://192.168.39.200:31645 |
|-----------|--------------|-------------|-----------------------------|
🎉  Opening service default/kuberappdemo in default browser...
vinay@vinay-Lenovo-ideapad-330S-15IKB-D:~/IdeaProjects/kuberapp$ Opening in existing browser session.
[23011:23027:0217/165740.204353:ERROR:browser_process_sub_thread.cc(203)] Waited 10 ms for network service

</details>

**The operating system version**: Ubuntu 16.04.6 LTS

**Comment by tstromberg** [comment]
Can you include the output of `kubectl describe pods -l app=kuberappdemo`?

My guess is that Docker within minikube does not know how to access your image.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
