### ISSUE TITLE
Newbie question - setting up demo on Windows system

### ISSUE THREAD

**Issue by shaulbehr** [kubernetes/minikube#6666]
Hi,
Minikube n00b here. I'm following the installation instructions [here](https://kubernetes.io/docs/tasks/tools/install-minikube/) for installing Minikube using VirtualBox on Windows 10.
I installed Minikube using Chocolatey without any trouble.
Ran `minikube start --vm-driver=virtualbox`. This yielded the following output:
```
* minikube v1.7.2 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* Using the virtualbox driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.7.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.7.0.iso: 166.68 MiB / 166.68 MiB [ 100.00% 1.48 MiB p/s 1m53s
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible
* Error: [VBOX_INTERFACE_NOT_FOUND] create: creating: Unable to start the VM: D:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Failed to open/create the internal network 'HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2' (VERR_INTNET_FLT_IF_NOT_FOUND).
VBoxManage.exe: error: Failed to attach the network LUN (VERR_INTNET_FLT_IF_NOT_FOUND)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:04.855017 Power up failed (vrc=VERR_INTNET_FLT_IF_NOT_FOUND, rc=E_FAIL (0X80004005))
* Suggestion: VirtualBox is unable to find its network interface. Try upgrading to the latest release and rebooting.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/6036
```
I figured this was because it created a new host-only network adapter, and I had one already set up. So I changed it to use the original adapter, and now I can get the VM to start. But...
```
>minikube status
E0217 21:36:32.390192   30812 status.go:164] Error host driver ip status: getting IP: Could not find matching IP for MAC address 080027248700
E0217 21:36:32.393120   30812 status.go:95] status error: getting IP: Could not find matching IP for MAC address 080027248700
host: Running
kubelet: Nonexistent
apiserver: Error
kubeconfig: Nonexistent
```
FWIW, I can ping the VM from my cmd prompt; it clearly recognizes the machine name and IP:
```
>ping minikube
Pinging minikube [192.168.123.182] with 32 bytes of data:
Reply from 192.168.123.182: bytes=32 time<1ms TTL=64
Reply from 192.168.123.182: bytes=32 time<1ms TTL=64
Reply from 192.168.123.182: bytes=32 time<1ms TTL=64
Reply from 192.168.123.182: bytes=32 time<1ms TTL=64
```
What do I do with this now?

**Comment by medyagh** [comment]
hi @shaulbehr 
I am curious do you happen to be running on a network with vpn ?
or anything different with your virtualbox setup ?

**Comment by shaulbehr** [comment]
@medyagh No VPN set up on my Windows machine. The VM network has two adapters: one for NAT, and one for Host-only adapter.

**Comment by sharifelgamal** [comment]
This looks like it might be a bug in VirtualBox, could you try upgrading to the latest version and seeing if that helps?

**Comment by priyawadhwa** [comment]
Hey @shaulbehr -- did upgrading help?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
