### ISSUE TITLE
Minikube does not update the memory allocation for a stopped VirtualBox instance

### ISSUE THREAD

**Issue by alexbrand** [kubernetes/minikube#6674]
**The exact command to reproduce the issue**:
1. `minikube start --vm-driver virtualbox`
2. `minikube stop`
3. `minikube start --vm-driver=virtualbox --memory=4g`

To improve the UX, we could 1) update the VM configuration if it's different than what already exists, or 2) Print a warning or error out if the configuration does not match the user's request.

**Comment by medyagh** [comment]
That is an interesting obeservation, we need to make the config and re-config of minikube more smooth.

**Comment by medyagh** [comment]
changing memory is not possible
