### ISSUE TITLE
--exra-config=apiserver does not appear to take effect

### ISSUE THREAD

**Issue by charlielj88** [kubernetes/minikube#6676]
**The exact command to reproduce the issue**:
minikube start \
  --extra-config=apiserver.oidc-issuer-url=https://accounts.google.com  \
  --extra-config=apiserver.oidc-client-id="xxxx.apps.googleusercontent.com"

**The full output of the command that failed**:<details>

The k8s cluster can be started successful, but the 2 OIDC flags are not set on "pod/kube-apiserver-minikube" config yaml file

</details>

**The output of the `minikube logs` command**:<details>

==> kubelet <==
-- Logs begin at Wed 2020-02-19 01:46:29 UTC, end at Wed 2020-02-19 01:47:24 UTC. --
Feb 19 01:46:54 minikube kubelet[2277]: E0219 01:46:54.690465    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:54 minikube kubelet[2277]: E0219 01:46:54.790778    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:54 minikube kubelet[2277]: E0219 01:46:54.891006    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:54 minikube kubelet[2277]: E0219 01:46:54.991239    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.091486    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.191823    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.292102    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.392426    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.492665    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.593042    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.693315    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.795392    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.895699    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:55 minikube kubelet[2277]: E0219 01:46:55.996181    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.096579    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.197143    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.297373    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.397622    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.498910    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.599183    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.699512    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.799872    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:56 minikube kubelet[2277]: E0219 01:46:56.900455    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.000926    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.101417    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.201950    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.302365    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.403696    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.504237    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.604750    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.705310    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.805626    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:57 minikube kubelet[2277]: E0219 01:46:57.906003    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: E0219 01:46:58.006380    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: E0219 01:46:58.107004    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: E0219 01:46:58.207344    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: E0219 01:46:58.307679    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: E0219 01:46:58.408167    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: E0219 01:46:58.508436    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: E0219 01:46:58.608780    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: E0219 01:46:58.717423    2277 kubelet.go:2263] node "minikube" not found
Feb 19 01:46:58 minikube kubelet[2277]: I0219 01:46:58.923917    2277 kubelet_node_status.go:112] Node minikube was previously registered
Feb 19 01:46:58 minikube kubelet[2277]: I0219 01:46:58.936112    2277 kubelet_node_status.go:73] Successfully registered node minikube
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.065902    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "coredns-token-ptf76" (UniqueName: "kubernetes.io/secret/b381e21c-92f8-4605-8918-d38f2ed476d9-coredns-token-ptf76") pod "coredns-6955765f44-rtcmr" (UID: "b381e21c-92f8-4605-8918-d38f2ed476d9")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.065938    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "xtables-lock" (UniqueName: "kubernetes.io/host-path/573363b3-ef3e-413b-8d8b-acdf49760e0d-xtables-lock") pod "kube-proxy-7xq84" (UID: "573363b3-ef3e-413b-8d8b-acdf49760e0d")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.065956    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/573363b3-ef3e-413b-8d8b-acdf49760e0d-lib-modules") pod "kube-proxy-7xq84" (UID: "573363b3-ef3e-413b-8d8b-acdf49760e0d")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.065974    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "tmp" (UniqueName: "kubernetes.io/host-path/b4217163-2227-4627-8b4e-57c166ec810b-tmp") pod "storage-provisioner" (UID: "b4217163-2227-4627-8b4e-57c166ec810b")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.065991    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "storage-provisioner-token-xk4q2" (UniqueName: "kubernetes.io/secret/b4217163-2227-4627-8b4e-57c166ec810b-storage-provisioner-token-xk4q2") pod "storage-provisioner" (UID: "b4217163-2227-4627-8b4e-57c166ec810b")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.066010    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/b381e21c-92f8-4605-8918-d38f2ed476d9-config-volume") pod "coredns-6955765f44-rtcmr" (UID: "b381e21c-92f8-4605-8918-d38f2ed476d9")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.066027    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/ec02d2a3-5674-4cb4-a5a5-88bfb506bd47-config-volume") pod "coredns-6955765f44-vj9kr" (UID: "ec02d2a3-5674-4cb4-a5a5-88bfb506bd47")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.066078    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "coredns-token-ptf76" (UniqueName: "kubernetes.io/secret/ec02d2a3-5674-4cb4-a5a5-88bfb506bd47-coredns-token-ptf76") pod "coredns-6955765f44-vj9kr" (UID: "ec02d2a3-5674-4cb4-a5a5-88bfb506bd47")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.066097    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy" (UniqueName: "kubernetes.io/configmap/573363b3-ef3e-413b-8d8b-acdf49760e0d-kube-proxy") pod "kube-proxy-7xq84" (UID: "573363b3-ef3e-413b-8d8b-acdf49760e0d")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.066112    2277 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy-token-vtzkp" (UniqueName: "kubernetes.io/secret/573363b3-ef3e-413b-8d8b-acdf49760e0d-kube-proxy-token-vtzkp") pod "kube-proxy-7xq84" (UID: "573363b3-ef3e-413b-8d8b-acdf49760e0d")
Feb 19 01:46:59 minikube kubelet[2277]: I0219 01:46:59.066120    2277 reconciler.go:156] Reconciler: start to sync state
Feb 19 01:47:03 minikube kubelet[2277]: W0219 01:47:03.839796    2277 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-6955765f44-vj9kr through plugin: invalid network status for
Feb 19 01:47:03 minikube kubelet[2277]: W0219 01:47:03.850608    2277 pod_container_deletor.go:75] Container "08b0d29abce94e7b0c736bbdca336e7df8f89de44ab80c804c060fb0ce83d576" not found in pod's containers
Feb 19 01:47:03 minikube kubelet[2277]: W0219 01:47:03.996337    2277 pod_container_deletor.go:75] Container "3b9a892c2648ae922d1fab48e9a517cabc889ae5bafd8f34d73a019aed9e81b1" not found in pod's containers
Feb 19 01:47:04 minikube kubelet[2277]: W0219 01:47:04.346867    2277 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-6955765f44-rtcmr through plugin: invalid network status for
Feb 19 01:47:05 minikube kubelet[2277]: W0219 01:47:05.028070    2277 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-6955765f44-rtcmr through plugin: invalid network status for
Feb 19 01:47:05 minikube kubelet[2277]: W0219 01:47:05.125056    2277 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-6955765f44-vj9kr through plugin: invalid network status for

==> storage-provisioner [72d3fd7ac554] <==

==> storage-provisioner [ed0c09ecd135] <==

</details>

**The operating system version**:

Mac OS: Darwin 10.15.3
Minikube: v1.7.1

**Comment by tstromberg** [comment]
I tried to replicate this:

```
% minikube start --extra-config=apiserver.oidc-issuer-url=https://accounts.google.com --extra-config=apiserver.oidc-client-id="xxxx.apps.googleusercontent.com"
😄  minikube v1.7.3 on Darwin 10.14.6
✨  Using the hyperkit driver based on existing profile
⌛  Reconfiguring existing host ...
🏃  Using the running hyperkit "minikube" VM ...
🐳  Preparing Kubernetes v1.17.3 on Docker 19.03.6 ...
    ▪ apiserver.oidc-issuer-url=https://accounts.google.com
    ▪ apiserver.oidc-client-id=xxxx.apps.googleusercontent.com
🚀  Launching Kubernetes ... 
🌟  Enabling addons: default-storageclass, ingress, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
 ```

I can  however see that the apiserver does have the correct flags set on the command-line:

```
% minikube ssh "ps -afe | grep apiserver"                                                                                             
root     15077 15060 11 19:46 ?        00:00:46 kube-apiserver --advertise-address=192.168.64.3 --allow-privileged=true --authorization-mode=Node,RBAC --client-ca-file=/var/lib/minikube/certs/ca.crt --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota --enable-bootstrap-token-auth=true --etcd-cafile=/var/lib/minikube/certs/etcd/ca.crt --etcd-certfile=/var/lib/minikube/certs/apiserver-etcd-client.crt --etcd-keyfile=/var/lib/minikube/certs/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/var/lib/minikube/certs/apiserver-kubelet-client.crt --kubelet-client-key=/var/lib/minikube/certs/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --oidc-client-id=xxxx.apps.googleusercontent.com --oidc-issuer-url=https://accounts.google.com --proxy-client-cert-file=/var/lib/minikube/certs/front-proxy-client.crt --proxy-client-key-file=/var/lib/minikube/certs/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/var/lib/minikube/certs/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=8443 --service-account-key-file=/var/lib/minikube/certs/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/var/lib/minikube/certs/apiserver.crt --tls-private-key-file=/var/lib/minikube/certs/apiserver.key
```

Do you mind sharing the output of `minikube start` and your `ps -afe | grep apiserver` output?

**Comment by sharifelgamal** [comment]
@charlielj88 do you still need help here?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
