### ISSUE TITLE
File from the .minikube/files folders are not being copied into the cluster anymore

### ISSUE THREAD

**Issue by nkleroux** [kubernetes/minikube#6677]
In version 1.6.2 we were able to copy files into folder .minikube/files, and they would automatically be copied over when minikube is started. This is how we copied our certificates to the cluster.

This doesn't seem to do the trick on 1.7.2 anymore.

Apologies for the lack of decorum, bit of a github noob and open to constructive criticism.

**Comment by tstromberg** [comment]
Are you on Windows?

If so, this is likely a dupe of #6565

You can tell by running `minikube start --alsologtostderr` and looking for the lines that say `filesync` or `ssh_runner`

**Comment by nkleroux** [comment]
Fantastic! Will follow it there.
