### ISSUE TITLE
Corrupted kubectl binary after upgrading minikube to 1.7.2

### ISSUE THREAD

**Issue by thehappycoder** [kubernetes/minikube#6678]
**The exact command to reproduce the issue**:<details>
1. Upgrade minikube from 1.6.x to 1.7.2
2. Change memory to 6096 in $HOME/.minikube/machines/minikube/config.json
3. Run:
minikube start \
  --kubernetes-version v1.13.12 \
  --disk-size 100g \
  --cpus=2 \
  --memory=4096 \
  --extra-config=apiserver.service-node-port-range=80-32767 \
  --mount-string="$(dirname `pwd`):/projects" \
  --mount
</details>

**The full output of the command that failed**:<details>
I get a few errors like: /var/lib/minikube/binaries/v1.13.12/kubect: cannot execute binary file. I did check if it was executable, and confirmed that inside `minikube ssh`.

Can't get full output yet because I am hoping my Terminal would unfreeze. I'll update it later.
</details>

**The output of the `minikube logs` command**:<details>
Can't get full output yet because I am hoping my Terminal would unfreeze. I'll update it later.
</details>

**The operating system version**:
macos 10.15.3

**Comment by medyagh** [comment]
thank you @thehappycoder that was a bug and fixed it on the master, it will be included in 1.7.3 release. I will close please reopen if it still happens in 1.7.3

**Comment by thehappycoder** [comment]
@medyagh What would you recommend me to do? I am not sure I'll be able to downgrade without creating a minikube VM? Not sure homebrew would let me install 1.7.1 or 1.6.x either.

**Comment by thehappycoder** [comment]
I compiled master branch. Will see if it works for me.
