### ISSUE TITLE
minikube启动失败

### ISSUE THREAD

**Issue by xtxt** [kubernetes/minikube#6705]
**重现问题所需的命令**：
 minikube start --image-mirror-country=cn   --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.7.0.iso  --registry-mirror=https://y05ka14a.mirror.aliyuncs.com  --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=virtualbox
**失败的命令的完整输出**：<details>
设置 kubeconfig 失败: writing kubeconfig: Error writing file /etc/kubernetes/admin.conf: writefile failed for /etc/kubernetes/admin.conf: open /etc/kubernetes/admin.conf: permission denied

</details>

**`minikube logs`命令的输出**： <details>

</details>
<img width="1174" alt="图片" src="https://user-images.githubusercontent.com/8444704/74928196-ff25ca80-5413-11ea-80b6-ce05b16f71b0.png">

**使用的操作系统版本**：
mac os
<img width="285" alt="图片" src="https://user-images.githubusercontent.com/8444704/74928231-1369c780-5414-11ea-83d0-6bec7b71e047.png">

**Comment by xtxt** [comment]
详细信息：
kevin-xutao:kubernetes xutao$ minikube start --image-mirror-country=cn   --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.7.0.iso  --registry-mirror=https://y05ka14a.mirror.aliyuncs.com  --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=virtualbox
😄  Darwin 10.14.4 上的 minikube v1.7.2
    ▪ KUBECONFIG=/etc/kubernetes/admin.conf
✨  Using the virtualbox driver based on user configuration
✅  正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
🔥  正在创建 virtualbox 虚拟机（CPUs=2，Memory=2000MB, Disk=20000MB）...
🐳  正在 Docker 19.03.5 中准备 Kubernetes v1.17.2…

💣  设置 kubeconfig 失败: writing kubeconfig: Error writing file /etc/kubernetes/admin.conf: writefile failed for /etc/kubernetes/admin.conf: open /etc/kubernetes/admin.conf: permission denied

😿  由于出错 minikube 正在退出。如果以上信息没有帮助，请提交问题反馈：
👉  https://github.com/kubernetes/minikube/issues/new/choose
kevin-xutao:kubernetes xutao$

**Comment by medyagh** [comment]
@xtxt do you mind trying with new minikube version 1.7.3 ?
and also could you try with docker driver ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
