### ISSUE TITLE
Unable to use minikube with vmware fusion

### ISSUE THREAD

**Issue by rmattier** [kubernetes/minikube#6718]
**The exact command to reproduce the issue**:
minikube start --v=7 --vm-driver=vmwarefusion

**The full output of the command that failed**:<details>
minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'vmwarefusion' driver from user configuration (alternates: [hyperkit vmware virtualbox])
🔥  Creating vmwarefusion VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: exit status 255

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'vmwarefusion' driver from user configuration (alternates: [hyperkit vmware virtualbox])
🔥  Creating vmwarefusion VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: exit status 255

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
macOS Catalina Version 10.15.2

**Comment by sharifelgamal** [comment]
The vmwarefusion driver is deprecated, so we don't officially support it, I would suggest the [vmware](https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/) driver instead.

To debug this particular issue, append `--alsologtostderr` to your `minikube start` command and paste the output here. It might be a tad verbose but it will be a lot more helpful.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!

**Comment by tehuelche** [comment]
Hi
I had the same problem
Try with:
declare -x PATH="/Users/leo/bin:/Users/leo/.dotfiles/bin:/usr/local/opt/php@7.4/bin:/usr/local/opt/php@7.4/sbin:/usr/local/opt/ruby/bin:/Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/bin:/Users/leo/.go/bin:/Users/leo/.gem/bin:/usr/local/opt/python/libexec/bin:/Users/leo/.composer/vendor/bin:/bin:/usr/local/bin:/usr/local/opt/make/libexec/gnubin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:**/Applications/VMware\\ Fusion.app/Contents/Public**:/Users/leo/.fzf/bin"
try
alias vmrun="/Applications/VMware\ Fusion.app/Contents/Public/vmrun"

but always

😄  minikube v1.9.2 on Darwin 10.15.4
✨  Using the vmwarefusion driver based on user configuration

❗  'vmwarefusion' driver reported an issue: vmrun path check: exec: "vmrun": executable file not found in $PATH
💡  Suggestion: Install VMWare Fusion
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmwarefusion/

💣  vmwarefusion does not appear to be installed
~
▶ minikube start --vm-driver=vmware
😄  minikube v1.9.2 on Darwin 10.15.4
✨  Using the vmware driver based on user configuration

❗  'vmware' driver reported an issue: exec: "vmrun": executable file not found in $PATH
💡  Suggestion: Install vmrun
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/

💣  vmware does not appear to be installed

Thanks

**Comment by ITJamie** [comment]
workaround:
`sudo ln -s /Applications/VMware\ Fusion.app/Contents/Public/vmrun /usr/local/bin/vmrun`

**Comment by tcrowleyibm** [comment]
For me, `vmrun` was in a different directory. I started with what @ITJamie had, but changed it to:

`sudo ln -s /Applications/VMware\ Fusion.app/Contents/Library/vmrun /usr/local/bin/vmrun`
