### ISSUE TITLE
sch_htb kernel module missing for network traffic shaping

### ISSUE THREAD

**Issue by jyee** [kubernetes/minikube#6721]
The `net_htb` module is missing. Aside from general network traffic shaping, `net_htb` is used by Chaos Engineering tools such as [Gremlin](http://gremlin.com) to simulate poor network conditions, latency, etc. This is a similar use case to #6033 and #6738.

**The full output of the command that failed**:<details>
```
$ modprobe -n net_htb
modprobe: FATAL: Module net_htb not found in directory /lib/modules/4.19.81
```
</details>

**The operating system version**:
minikube version: v1.7.2
commit: 50d543b5fcb0e1c0d7c27b1398a9a9790df09dfb

**Comment by medyagh** [comment]
@afbjorklund do we need this ?

@jyee I am curious have u tried the docker driver ? that one uses a different image.

**Comment by jyee** [comment]
@medyagh 

Yes setting `--vm-driver=docker` works (as does running the Docker-Desktop version of K8s). 

I've had other issues with the Docker VM, so it's a tradeoff. As I see it, the Minikube VM is the standard (vs other VMs), so adding this in will be helpful for anyone developing with or testing on Minikube.

**Comment by medyagh** [comment]
@jyee thats fair ! I would accept any PR to add that to our ISO

**Comment by medyagh** [comment]
here is the link how to add kernel modules to our ISO 
https://minikube.sigs.k8s.io/docs/contributing/iso/#adding-kernel-modules

btw I am curious do you mind sharing what issues you have with docker driver that you prefer VM ?
