### ISSUE TITLE
Error when try to run using podman

### ISSUE THREAD

**Issue by koktean** [kubernetes/minikube#6727]
Error: invalid option type "exec" ; exit status 125
when try to run minikube (v1.7.3) using podman (instead of docker) with below commands,
suspect caused by the option type
--volume /root/.minikube/machines/minikube/var:/var:exec

**The exact command to reproduce the issue**:
minikube start --memory 8192 --vm-driver=podman

**The full output of the command that failed**:<details>
X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create: creating: create kic node: create a kic node: args: [run --cgroup-manager cgroupfs -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --volume /root/.minikube/machines/minikube/var:/var:exec --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.5]  output: [Error: invalid option type "exec"] : exit status 125
</details>

**The output of the `minikube logs` command**:<details>
*
X Error getting machine logs: unable to fetch logs for: Docker, container status, dmesg, kernel, kubelet
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
</details>

**The operating system version**:
CentOS Linux release 8.1.1911 (Core)

**Comment by afbjorklund** [comment]
What version of podman do you have ? Maybe exec was added later

@medyagh

**Comment by koktean** [comment]
# podman version
Version:            1.4.2-stable2
RemoteAPI Version:  1
Go Version:         go1.12.8
OS/Arch:            linux/amd64

This is the latest supported version for centos 8 - yum install.
Do I need to install the latest podman ?

**Comment by koktean** [comment]
Issue resolve with the update of podman version
https://podman.io/getting-started/installation
$ sudo yum -y install podman

The version upgraded to 1.6.4, and it looks much better now.
I am still in progress to install / setup the minikube.
I will either update here or create another issue if encounter further problem.

Thanks a lot.

**Comment by afbjorklund** [comment]
Eventually we might be able to adapt the code to work with older/newer versions, but for now the 1.6.x looks like a good compromise (between 1.4/old and 1.8/new), glad that it worked out!
