### ISSUE TITLE
minikube service: Get-VM : You do not have the required permission to complete this task

### ISSUE THREAD

**Issue by ukreddy-erwin** [kubernetes/minikube#6732]
minikube service list
E0221 18:06:44.781428   12584 main.go:106] libmachine: [stderr =====>] : Hyper-V\Get-VM : You do not have the required permission to complete this task. Contact the administrator of the
authorization policy for the computer 'DESKTOP-1CILTF5'.
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : Unspecified,Microsoft.HyperV.PowerShell.Commands.GetVM

X Failed to get service URL: Host is not running
* Check that minikube is running and that you have specified the correct namespace (-n flag) if required.

>kubectl get pods -n kube-system
Unable to connect to the server: dial tcp 192.168.1.64:8443: connectex: No connection could be made because the target machine actively refused it.

**Comment by tstromberg** [comment]
Try running `minikube start` as an administrator, and see if it fixes your issue. If not, can you share the full output of `minikube start --alsologtostderr -v=1`? Thanks!

**Comment by sharifelgamal** [comment]
@ukreddy-erwin do you still need help here?

**Comment by ukreddy-erwin** [comment]
Minikube... Is not working for latest version of virtualbox windows

Thanks and Regards,
Uday Kiran Reddy
Senior Build and Release Engineer
+91-9581226333
Email: ukreddy@erwin.com

________________________________

**Comment by sharifelgamal** [comment]
This issue was a problem with hyper-v. What issues are you experiencing with virtualbox?

**Comment by ukreddy-erwin** [comment]
I am having issue with Hyper-v, so uninstalled Hype-v and installe virtualbox latest version.
It is not starting the minikube cluster, simply getting hung up.

So, uninstalled and installed an older version of virtulabox, there it is working

**Comment by ukreddy-erwin** [comment]
with hyper-v still same issue even with run as admin

**Comment by priyawadhwa** [comment]
Hey @ukreddy-erwin , could you please share the output of `minikube start --alsologtostderr -v=1`?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
