### ISSUE TITLE
act_gact kernel module missing for network packet control

### ISSUE THREAD

**Issue by jyee** [kubernetes/minikube#6738]
The `act_gact` module is missing. Aside from general networking, `act_gact` is used by Chaos Engineering tools such as [Gremlin](http://gremlin.com) to simulate network packet loss.. This is a similar use case to #6033 and #6271.

**The full output of the command that failed**:<details>
```
$ modprobe -n act_gact
modprobe: FATAL: Module act_gact not found in directory /lib/modules/4.19.81
```
</details>

**The operating system version**:
minikube version: v1.7.2
commit: 50d543b5fcb0e1c0d7c27b1398a9a9790df09dfb

**Comment by medyagh** [comment]
@jyee 

if this a feature that others might use I would be happy to accept a PR that adds this kernel module, here is the documentation on how to add kernel modules to the minikube ISO

here is the link how to add kernel modules to our ISO
https://minikube.sigs.k8s.io/docs/contributing/iso/#adding-kernel-modules

https://minikube.sigs.k8s.io/docs/contributing/iso/#adding-kernel-modules

meanwhile, maybe you could use the docker-driver which uses ubuntu as base image?

**Comment by medyagh** [comment]
CC: @afbjorklund
