### ISSUE TITLE
Running unit tests downloads kubernetes binaries

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#6751]
It would be nice if `TestCacheBinariesForBootstrapper` could mock the actual downloads...

 Downloading the `v1.16.0` can take a long time, and wastes space in the minikube cache.

`--- PASS: TestCacheBinariesForBootstrapper (183.97s)`

`418M	/home/anders/.minikube/cache/v1.16.0/`

**Comment by medyagh** [comment]
Wow.

**Comment by nkprince007** [comment]
@medyagh I tried implementing a mocked download solution, but for some test cases like https://github.com/kubernetes/minikube/pull/6907/files#diff-061e1def7add540a87eb3dd7d3e95779L78-L84 I couldn't find a solution that works without hitting the server.

**Comment by adriannowak** [comment]
@nkprince007 Create interface with two methods. 
 - download(....)
 - verify(.....)

1. Mocked version would send HTTP OPTIONS command to verify if the file exists on webserver.
2. Verify might return always true

**Comment by afbjorklund** [comment]
Not sure about either of the PR, leaking go-getter abstraction and exposing it as a param is not very nice and I don't particularly like the new module names with the "interface" (or even if) in them. Sorry.

@tstromberg : Do you have any style guides here, on how best to mock the `download` module ?

**Comment by sharifelgamal** [comment]
We mock downloads for all tests now, refer to the [download package](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/download/download.go) for details there.
