### ISSUE TITLE
Improve search engine ranking for minikube.sigs.k8s.io

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#6763]
I was searching for the documentation which is hosted as part of this repo at this link - https://minikube.sigs.k8s.io/ & surprisingly, I couldn't find it in any of the following search engines on the 1st page when just searching for `minikube` -
1. Google
2. DuckDuckGo
3. Bing

I think that the docs website should come up. What do you guys think?

**Comment by medyagh** [comment]
Any seo experts?

**Comment by medyagh** [comment]
@blueelvis sorry irrelevant but any interest to help have windows tests for docker driver on GitHub actions? This PR is stuck we need some windows expert help https://github.com/kubernetes/minikube/pull/6580

**Comment by blueelvis** [comment]
@medyagh - Yes sir. I have been out travelling quite a lot so just getting back in :( . Just joined as a reviewer on that PR.

Not an SEO expert over here. @tstromberg - Any chance you know someone?

**Comment by blueelvis** [comment]
I just ran a Chrome Lighthouse audit and found the following -

![image](https://user-images.githubusercontent.com/6985763/75104755-c6177100-5632-11ea-8f4e-841da3f0b5f8.png)

**Comment by afbjorklund** [comment]
There's still some duplication, between the Kubernetes docs and the Minikube SIG docs:

https://kubernetes.io/docs/setup/learning-environment/minikube/

* https://kubernetes.io/docs/tasks/tools/install-minikube/

* https://kubernetes.io/docs/tutorials/hello-minikube/

**Comment by afbjorklund** [comment]
I think this part could need some improvement: https://minikube.sigs.k8s.io/blog/

> Posts in 2019
>
> v1.3.1 released
> Tuesday, August 13, 2019 in Releases

**Comment by tstromberg** [comment]
Update:

- #6 on Google
- #3 on Bing
- #7 on DuckDuckGo

Not great, but also not terrible.

**Comment by sharifelgamal** [comment]
There's not a whole lot of us to do here, if we come up with something, we can reopen.
