### ISSUE TITLE
Github integration test failure

### ISSUE THREAD

**Issue by sayboras** [kubernetes/minikube#6765]
As mentioned in https://github.com/kubernetes/minikube/pull/6762#issuecomment-590030374, there are a few integration test cases failed in github action.

```
"TestFunctional/parallel/PersistentVolumeClaim",
"TestFunctional/parallel/MySQL",
"TestFunctional/parallel/DockerEnv"
```

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by medyagh** [comment]
"TestFunctional/parallel/DockerEnv" fails because minikube fails to detect it is running in Shell
and it wont generate a hint !
we need to improve that so minikube can detect if it is shell (currently it is using libmachine to detect it)

**Comment by sayboras** [comment]
> "TestFunctional/parallel/DockerEnv" fails because minikube fails to detect it is running in Shell
> and it wont generate a hint !
> we need to improve that so minikube can detect if it is shell (currently it is using libmachine to detect it)

Thanks for your pointer 👍

**Comment by afbjorklund** [comment]
Weird that GitHub actions doesn't set a proper SHELL variable...

But anyway, it was _supposed_ to generate bash instructions.

`The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.`

Not sure where that got lost along the way. `ErrUnknownShell` ?

**Comment by afbjorklund** [comment]
@medyagh : added #6766 for the confused `minikube docker-env`

**Comment by medyagh** [comment]
yeah I had added en ENV for github actions to specify the shell explicity 
https://github.com/kubernetes/minikube/blob/master/.github/workflows/main.yml#L74

but maybe the "Step" integration does not get that environment variable.


@sayboras it worth trying to pass that "SHELL" env to the actual step to see if that will fix the problem https://github.com/kubernetes/minikube/blob/master/.github/workflows/main.yml#L86

**Comment by medyagh** [comment]
@sayboras please check out this comment as well https://github.com/kubernetes/minikube/issues/6766#issuecomment-590125545

**Comment by medyagh** [comment]
this seems to be fixed
