### ISSUE TITLE
Default to bash shell when $SHELL is missing

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#6766]
The current message is somewhat confused:

```console
$ unset SHELL
$ minikube docker-env
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.


💣  Error detecting shell: Error: Unknown shell

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

```

**Comment by afbjorklund** [comment]
It's equally confused upstream, always something.

```console
$ unset SHELL
$ docker-machine env
The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.

Error: Unknown shell
$
```

I guess people normally **don't** unset their SHELL ?

**Comment by afbjorklund** [comment]
First seen in #6643

**Comment by afbjorklund** [comment]
Probably worth filing a bug in the https://github.com/actions/runner repository ?

Looks like it is written in .NET, and I'm not really sure where the VM / images are.

**Comment by afbjorklund** [comment]
Similar failure with `minikube podman-env` (not surprising, same code)

**Comment by medyagh** [comment]
I would be happy to review a PR that defaults to BASH if nothing else is found. (better not not giving anything)

**Comment by medyagh** [comment]
we could produce something like this for default

```
# Warning we couldn't detect the shell. providing Bash is default.

export DOCKER_TLS_VERIFY="1"
export DOCKER_HOST="tcp://127.0.0.1:32778"
export DOCKER_CERT_PATH="/Users/medya/.minikube/certs"
export MINIKUBE_ACTIVE_DOCKERD="minikube"

# To point your shell to minikube's docker-daemon, run:
# eval $(minikube -p minikube docker-env)
```

**Comment by sayboras** [comment]
Cool let me give it a try, thanks @afbjorklund  @medyagh

**Comment by afbjorklund** [comment]
@medyagh : note that the initial bug is with libmachine, it prints an uncommented string on stdout...

https://github.com/docker/machine/blob/master/libmachine/shell/shell.go#L17_L26

```go
	if shell == "" {
		fmt.Printf("The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.\n\n")
		return "", ErrUnknownShell
	}
```

So even when `ErrUnknownShell` is handled in minikube, that first line will still ruin the `eval`:

```
bash: unexpected EOF while looking for matching `''
bash: syntax error: unexpected end of file
```

Which basically means moving the `os.Getenv("SHELL")` to minikube.

And handle the unset ("") case, before it is even passed to libmachine ?

**Comment by medyagh** [comment]
> @medyagh : note that the initial bug is with libmachine, it prints an uncommented string on stdout...
> 
> https://github.com/docker/machine/blob/master/libmachine/shell/shell.go#L17_L26
> 
> ```go
> 	if shell == "" {
> 		fmt.Printf("The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.\n\n")
> 		return "", ErrUnknownShell
> 	}
> ```
> 
> So even when `ErrUnknownShell` is handled in minikube, that first line will still ruin the `eval`:
> 
> ```
> bash: unexpected EOF while looking for matching `''
> bash: syntax error: unexpected end of file
> ```
> 
> Which basically means moving the `os.Getenv("SHELL")` to minikube.
> 
> And handle the unset ("") case, before it is even passed to libmachine ?

thanks for that finding ! yes I agree the problem is with the libmachine
