### ISSUE TITLE
memory size reset if --memory command-line arg is not always supplied to start

### ISSUE THREAD

**Issue by alewis001** [kubernetes/minikube#6771]
**The exact command to reproduce the issue**:
1. `minikube start -p bug --memory 5000`
2. Check contents of $HOME/.minikube/profiles/bug/config.json: memory is set to 5000.
3. `minikube start -p bug stop`
4. Check contents of $HOME/.minikube/profiles/bug/config.json: memory is still set to 5000.
5. `minikube start -p bug`
   * Error message (see below)
6. `minikube start -p bug`
   * Cluster starts with 2GB memory according to config.json for the profile.

**Output of first start**:<details>
😄  [bug] minikube v1.7.3 on Darwin 10.15.3
✨  Automatically selected the hyperkit driver
🔥  Creating hyperkit VM (CPUs=2, Memory=5000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.17.3 on Docker 19.03.6 ...
🚀  Launching Kubernetes ... 
🌟  Enabling addons: default-storageclass, storage-provisioner
⌛  Waiting for cluster to come online ...
🏄  Done! kubectl is now configured to use "bug"
</details>

**Output of second start (error)**:<details>
😄  [bug] minikube v1.7.3 on Darwin 10.15.3
✨  Using the hyperkit driver based on existing profile
⌛  Reconfiguring existing host ...
🔄  Starting existing hyperkit VM for "bug" ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: post-start: command runner: ssh client: Error dialing tcp via ssh client: dial tcp 192.168.64.11:22: connect: no route to host

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**Output of third start**:<details>
😄  [bug] minikube v1.7.3 on Darwin 10.15.3
✨  Using the hyperkit driver based on existing profile
⌛  Reconfiguring existing host ...
🏃  Using the running hyperkit "bug" VM ...
🐳  Preparing Kubernetes v1.17.3 on Docker 19.03.6 ...
🚀  Launching Kubernetes ... 
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "bug"
</details>

**Comment by priyawadhwa** [comment]
Hey @alewis001 you can set the memory in the global config via:

```
minikube config set memory 5000
```

and it will be automatically applied. 

You can find a list of all configurable settings [here](https://minikube.sigs.k8s.io/docs/reference/commands/config/). 

Does this resolve your issue?

**Comment by alewis001** [comment]
Thanks, it does. I'd used that as the workaround before posting this bug. Apologies, I should have mentioned that in the bug report.

What should the expected behaviour of that flag be? As it is provided to the `start` command I could see it working different ways:
- A temporary override for that run over whatever is written to the config; the config is not modified. As such, that would make this bug invalid.
- Using it on a `start` will update the config so it is not required on future runs. 

I assume it should update the configuration as the `config` command appears to ignore the `-p <profile>` flag?

**Comment by sharifelgamal** [comment]
Yeah, this was a regression in soft restarts of minikube, it should be fixed at HEAD now that #7449 is merged.

**Comment by tstromberg** [comment]
This will be fixed in v1.10.

**Comment by alewis001** [comment]
Great, thanks for the update.

**Comment by medyagh** [comment]
@alewis001 do you mind checking our newest version v1.10.1 and verify we can close this issue?

**Comment by alewis001** [comment]
I can confirm that with 1.10.1 the issue is fixed. Both the failed start and the resetting of the config. 

Thank you!

**Comment by medyagh** [comment]
glad to see this is fixed
