### ISSUE TITLE
virtualbox: minikube freezing with bridged network on windows

### ISSUE THREAD

**Issue by uday1kiran** [kubernetes/minikube#6775]
With hyper-v, minikube vm can be set to external adapter (bridged) and can access the vm like anyother machine in the network.

But with virtual box, when I change the default NAT to bridged, the minikube is just freezing.

Port forwarding is not a solution as we need to create port forward for everyservice even with random ports.

**Comment by priyawadhwa** [comment]
Hey @uday1kiran thanks for opening this issue. We could use some more information to help debug it. Could you please provide the full output of:

``` 
minikube start --alsologtostderr -v 3
```

Thanks you!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!

**Comment by abhinavgarg956** [comment]
if you solved it plz answer
