### ISSUE TITLE
Starting immediately after stopping minikube on Hyper-V causes error

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#6776]
**The exact command to reproduce the issue**: 
```
minikube start --vm-driver=hyperv --hyperv-virtual-switch="Default Switch"
minikube stop
minikube start
```

**The full output of the command that failed**:
```
PS D:\dev> minikube stop
* Stopping "minikube" in hyperv ...
* Powering off "minikube" via SSH ...
* "minikube" stopped.

PS D:\dev> minikube start
* minikube v1.7.3 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
  - KUBECONFIG=C:\Users\bluee\.kube\config
* Using the hyperv driver based on existing profile

! 'hyperv' driver reported an issue: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed, but is specified by an existing profile. Please run 'minikube delete' or install hyperv


```
From what I saw immediately happening in the Hyper-V console is that once the VM is shut down, it goes ahead and merges the current disk state to a checkpoint. This automatic checkpoint is something which is set up while creating the VM from Docker Machine (I believe).

We should -
1. Either wait for the merge of the snapshot to complete.
2. Disable creation of these automatic checkpoints.

Following is the status when the snapshot is being merged -
```
PS D:\dev> Get-VM minikube

Name     State CPUUsage(%) MemoryAssigned(M) Uptime   Status        Version
----     ----- ----------- ----------------- ------   ------        -------
minikube Off   0           0                 00:00:00 Merging disks 9.0
```

What do you think?

**The operating system version**:
Windows 10 Pro

**Comment by tstromberg** [comment]
Any idea if this still happens in minikube v1.9.x?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
