### ISSUE TITLE
Enable required check in github (e.g. build, lint, unit test targets)

### ISSUE THREAD

**Issue by sayboras** [kubernetes/minikube#6782]
There were a few occurrence that the PR got merged with some minor linting error. To avoid such issue, we can consider to enable required check in github for few things:

- build
- lint
- unit test (this one might be flanky)
- travis (this check includes build + lint + unit test together, so might be flanky as well)

**Comment by afbjorklund** [comment]
Do you have a breakdown on what is being run in github actions VM and what is being run in travis ci VM, there seems to be a lack of documentation on these things - and it seems to be always "red" ?

**Comment by sayboras** [comment]
Recently, I have a chance to work on this a little bit. Here is the list

Github actions:
- build
- lint
- unit test
- integration test (once build is passed)
    - docker_ubuntu16_04
    - docker_ubuntu18_04
    - none_ubuntu16_04
    - none_ubuntu18_04
    - podman_ubuntu_18_04

Travis only run build, lint, unit test
Jenkins only integration test

**Comment by sharifelgamal** [comment]
yeah integration tests in github actions is still work in progress, we also have some consistently failing tests that need to get fixed before trusting them.

**Comment by medyagh** [comment]
The reason that build is duplicated between travis and github aciton is, I needed the binary to use in github actions integeation tests , best would be just build it in github and use it there.

in github actions we get free integration tests, but we have a ""The End Result Block" for each integration tests, if you just unfold it u will see exact integration tests

it used to be 20s of failures, now its in some tests only 1 failure.
but I made it look red even if it has one failure.

@sayboras is working on fixing some of the github action flakes
