### ISSUE TITLE
apiserver: Stopped

### ISSUE THREAD

**Issue by suissitakwa** [kubernetes/minikube#6785]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by nengbowan** [comment]
yesterday is ok , but today apiserver status is stopped , i remember i do nothing bad , 
i just do some demos , spring cloud kubernetes , so ...

kubernetes logs about apiserver under below : 
`I0306 02:29:48.197937       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
I0306 02:30:00.311107       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
I0306 02:30:00.311985       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
I0306 02:30:04.682874       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
I0306 02:30:04.682911       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
I0306 02:30:04.683169       1 clientconn.go:1016] blockingPicker: the picked transport is not ready, loop back to repick
I0306 02:30:08.381540       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
I0306 02:30:08.381877       1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}]
W0306 02:30:08.382763       1 asm_amd64.s:1337] Failed to dial 127.0.0.1:2379: grpc: the connection is closing; please retry.
F0306 02:30:08.186932       1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry {[https://127.0.0.1:2379] /var/lib/minikube/certs/apiserver-etcd-client.key /var/lib/minikube/certs/apiserver-etcd-client.crt /var/lib/minikube/certs/etcd/ca.crt} false true {0xc0008f3e60 0xc001ab0090} {{rbac.authorization.k8s.io v1} [{rbac.authorization.k8s.io } {rbac.authorization.k8s.io }] false} <nil> 5m0s 1m0s}), err (context deadline exceeded)`

can anybody help ? appreciate u .

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
