### ISSUE TITLE
Kubelet is not running or not  healthy

### ISSUE THREAD

**Issue by gunalanbalakrishnan** [kubernetes/minikube#6793]
**The exact command to reproduce the issue**:

sudo kubeadm init --config=config.yaml 

**The full output of the command that failed**:

 sudo kubeadm init --config=config.yaml
W0225 09:13:16.371517    8482 strict.go:54] error unmarshaling configuration schema.GroupVersionKind{Group:"kubeadm.k8s.io", Version:"v1beta2", Kind:"ClusterConfiguration"}: error unmarshaling JSON: while decoding JSON: json: unknown field "apiServerCertSANs"
W0225 09:13:16.726036    8482 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0225 09:13:16.726054    8482 validation.go:28] Cannot validate kubelet config - no validator is available
[init] Using Kubernetes version: v1.17.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [rbalv658538.bas.roche.com kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 10.141.178.112 10.141.178.116]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] External etcd mode: Skipping etcd/ca certificate authority generation
[certs] External etcd mode: Skipping etcd/server certificate generation
[certs] External etcd mode: Skipping etcd/peer certificate generation
[certs] External etcd mode: Skipping etcd/healthcheck-client certificate generation
[certs] External etcd mode: Skipping apiserver-etcd-client certificate generation
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
W0225 09:13:20.246843    8482 manifests.go:214] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
[control-plane] Creating static Pod manifest for "kube-scheduler"
W0225 09:13:20.248076    8482 manifests.go:214] the default kube-apiserver authorization-mode is "Node,RBAC"; using "Node,RBAC"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
        timed out waiting for the condition

This error is likely caused by:
        - The kubelet is not running
        - The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
        - 'systemctl status kubelet'
        - 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
        - 'docker ps -a | grep kube | grep -v pause'
        Once you have found the failing container, you can inspect its logs with:
        - 'docker logs CONTAINERID'
error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster
To see the stack trace of this error execute with --v=5 or higher

**The output of the `minikube logs` command**:<details>

I am not using minikube, I am trying kubernetes HA with 3 master, 1 Minion  and 1 HA 

</details>

**The operating system version**:
[root@XXYYZZ ~]# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)
[root@XXYYZZ  ~]# uname -a
Linux XXYYZZ  3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
[root@XXYYZZ  ~]#

 systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/usr/lib/systemd/system/kubelet.service; enabled; vendor preset: disabled)
  Drop-In: /usr/lib/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Tue 2020-02-25 09:22:09 CET; 16s ago
     Docs: https://kubernetes.io/docs/
 Main PID: 16599 (kubelet)
    Tasks: 18
   Memory: 22.2M
   CGroup: /system.slice/kubelet.service
           └─16599 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet...

Feb 25 09:22:25 XXYYZ kubelet[16599]: E0225 09:22:25.646967   16599 kubelet.go:2263] node "XXYYZ" not found
Feb 25 09:22:25 XXYYZ.com kubelet[16599]: I0225 09:22:25.663437   16599 kubelet_node_status.go:294] Setting node annotation to enable volume ...h/detach
Feb 25 09:22:25 XXYYZ.com kubelet[16599]: E0225 09:22:25.664023   16599 reflector.go:156] k8s.io/client-go/informers/factory.go:135: Failed t...n=0: EOF
Feb 25 09:22:25 XXYYZ.com kubelet[16599]: I0225 09:22:25.690880   16599 Hint: Some lines were ellipsized, use -l to show in full.

**Comment by afbjorklund** [comment]
Hi @gunalanbalakrishnan, this repository is for minikube - general kubeadm issues are elsewhere:
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/troubleshooting-kubeadm/

See https://github.com/kubernetes/kubeadm/issues
