### ISSUE TITLE
Running minikube on IBM (s390x, ppc64le), use cases

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#6798]
There's been some requests for minikube binaries for kubernetes IBM Z/POWER platforms:

* [Linux on IBM Z](https://en.wikipedia.org/wiki/Linux_on_IBM_Z) (`s390x`)

* [Linux on POWER](https://en.wikipedia.org/w/index.php?title=Linux_on_Power) (`ppc64le`)

It would be nice with some more background information, how minikube is used there...

----

So far the main use case is running the `none` driver in CI, for installing `kubeadm`.

There is not really any development desktop support, and no available ISO or KIC.

**Comment by runlevel5** [comment]
I am running a RaptorCS Blackbird workstation (which runs Linux ppc64le) mainly for web app development. I would love to be able to get minikube running on this platform so I could experiment with k8s locally. 

I am not aware of any usecase of using minikube on mainframe (`s390x`) at this stage.

**Comment by afbjorklund** [comment]
OK, thanks! That sounds somewhat similar to the `arm64` and the Raspberry Pi 4 scenarios.
Wasn't aware that people were still running PowerPC for their desktop, after the Mac stopped.

**Comment by runlevel5** [comment]
@afbjorklund IBM has been pushing the OpenPOWER platform and I could see a small community of mainly engineers are embracing it. Companies like Raptor CS have offered affordable OpenPOWER-based products that help bridge the adoption gap. And I hope with the level of software support, the gap would be shortened further.

**Comment by edmondsw** [comment]
ppc64le has actually never been used in a mainframe. It's primarily used on-prem in enterprise customer datacenters, but it is making its way into laptops and things via OpenPOWER as @runlevel5 mentioned. You can also now get ppc64le virtual machines in the IBM Cloud: https://cloud.ibm.com/docs/vpc?topic=vpc-about-advanced-virtual-servers#about-power-vsi

**Comment by afbjorklund** [comment]
My bad, when I ran PowerPC it was called G3/G4/G5 :-) It was on the Mac. Maybe we should decouple `ppc64le` from `s390x` then.

**Comment by afbjorklund** [comment]
If someone has a link to some reasonable hardware for minikube, similar to Raspberry Pi 4 ?

https://www.raptorcs.com/content/base/products.html seemed like $2000 ($1000 for board only)

**Comment by edmondsw** [comment]
I'd suggest using the IBM Cloud. You can order a ppc64le virtual server there. https://cloud.ibm.com/docs/vpc?topic=vpc-about-advanced-virtual-servers#about-power-vsi

you might want to start here https://cloud.ibm.com/docs/vpc?topic=vpc-getting-started and when you need to select which VPC generation, use Gen 2.

**Comment by runlevel5** [comment]
@afbjorklund feel free to reply with your SSH pubkey, I could grant you access to my box for development.

**Comment by tstromberg** [comment]
Closing because I think some of the use cases have been answered. 

FWIW, it seems that some folks in IBM are also using minikube for demoing Kuberenetes on top of z-Series machines.
