### ISSUE TITLE
The extra github checks are failing all the time

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#6799]
Seems like no matter **what** you do, you get a bunch of failing GitHub Actions ?

The first three are normal (build + lint + test), and the Travis three are normal (same)

But then we have a bunch of timeouts in the middle, and a bunch of website at the end.

This is somewhat misleading, and is causing **all** the minikube PRs to go "red" (❌)

![minikube-checks](https://user-images.githubusercontent.com/10364051/75291834-4dc3d200-5823-11ea-819e-edc122fee30a.png)

----

Some questions:

1) Do we really need to run the same three checks in _both_ of GitHub and Travis ?

2) Can we disable the tests until they work, or is this part of the kic work-in-progress ?

**Comment by medyagh** [comment]
I agree it is a bit confusing, to do linting twice, I think till we solidify our tests, it helps sometimes to see if somehting is a flake or if it fails in both.

**Comment by afbjorklund** [comment]
The check duplication is not the biggest issue, it's those failing 6 checks... Seems like **all** PR's are 11/17, for this particular reason ?

* CI / docker_ubuntu_16_04 (pull_request) Failing after 42m
* CI / docker_ubuntu_18_04 (pull_request) Failing after 46m
* CI / none_ubuntu16_04 (pull_request) Failing after 10m
* CI / none_ubuntu18_04 (pull_request) Failing after 10m
* CI / podman_ubuntu_18_04 (pull_request) Failing after 70m

**Comment by afbjorklund** [comment]
This is still an issue, especially if people are getting used to seeing broken builds all the time

**Comment by tstromberg** [comment]
I'm going to open more specific issues for GitHub-specific failures (that are not minikube's  fault), and then feel these tests should be disabled until those issues a resolved.

**Comment by medyagh** [comment]
I did some adjustments will continue doing that
