### ISSUE TITLE
Minikube status shows me error

### ISSUE THREAD

**Issue by lmurali89** [kubernetes/minikube#6814]
I tried to check my minikube status and i got the error as shown below.

C:\WINDOWS\system32>minikube status
E0227 12:31:23.986692   11016 status.go:95] status error: host: load: filestore "minikube": open C:\Users\Hp\.minikube\machines\minikube\config.json: The system cannot find the file specified.
E0227 12:31:23.991691   11016 status.go:98] The "minikube" cluster does not exist!
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent

**Comment by priyawadhwa** [comment]
Hey @lmurali89 -- 

could you try running:

```shell
$ minikube delete
$ minikube start
$ minikube status
```

and see if that works?

**Comment by tstromberg** [comment]
Fixed in v1.9.2
