### ISSUE TITLE
Try to preserve IP addresses of containers between system reboots

### ISSUE THREAD

**Issue by CodingSpiderFox** [kubernetes/minikube#6826]
**The exact command to reproduce the issue**:
Yesterday, I started a local nextcloud playground on my minikube setup (vm-driver=none)
I launched it using the following command

`helm install nextcloud stable/nextcloud --set nextcloud.host=172.17.0.4`

Everything worked nice until I rebooted my machine.

After reboot, I started minikube again 

`sudo minikube start --vm-driver=none`

But then the nextcloud container suddenly had the IP 172.17.0.6 instead of 172.17.0.4

I would like that it stays with the same IP because nextcloud needs the IP set as trusted domain for this test setup and I would need to throw away the setup because the IP changed which I don't like

**The output of the `minikube logs` command**:<details>

too much to check whether it contains confidential information

</details>

**The operating system version**:
elementary OS 5.1.2 (based on Ubuntu 18.04)

**Comment by tstromberg** [comment]
I don't believe this is presently possible in Kubernetes. There are no guarantee for pod IP's. 

Perhaps nextcloud.host should not be a container IP?

**Comment by medyagh** [comment]
@CodingSpiderFox I think that is something in kuberentes and not related to minikube.
