### ISSUE TITLE
fix tunnel cleanup to remove load balancer service external-ip

### ISSUE THREAD

**Issue by josedonizetti** [kubernetes/minikube#6834]
If a tunnel process get killed, the services still have the external-ip address set. 

```
kubectl get svc
NAME              TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
hello-minikube1   LoadBalancer   10.104.16.191   10.104.16.191   8080:32394/TCP   10m
kubernetes        ClusterIP      10.96.0.1       <none>          443/TCP          17m
```

minikube tunnel supports a cleanup flag `minikube tunnel -c`, that cleanup routing table, etc, but not the external ip on the service, we should change it to also cleanup the external-ip.

**Comment by tstromberg** [comment]
Moving to longterm (because it hasn't shipped in the past 2 releases)
