### ISSUE TITLE
Support running minikube on Raspbian (arm)

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#6843]
For instance the **Raspberry Pi 4** comes with enough memory (2G) to be able to run Minikube.

* https://www.raspberrypi.org/products/raspberry-pi-4-model-b/

Currently it only runs directly on the host with the `none` driver which is not ideal, but "works".

Docker is available in the standard distribution, packaged in the **Raspbian**/Debian distribution.

* https://www.collabora.com/news-and-blog/blog/2018/07/04/docker-io-debian-package-back-to-life/

* https://packages.debian.org/buster/docker.io

For compatibility this is a 32-bit Linux distro which means we need to supply `arm` binaries.

* https://www.raspberrypi.org/blog/buster-the-new-version-of-raspbian/

----

Example session:

```console
pi@raspberrypi:~ $ sudo minikube start --vm-driver=none
😄  minikube v1.7.3 on Raspbian 10.3 (arm)
✨  Using the none driver based on user configuration
🤹  Running on localhost (CPUs=4, Memory=1887MB, Disk=29729MB) ...
ℹ️   OS release is Raspbian GNU/Linux 10 (buster)
🐳  Preparing Kubernetes v1.17.3 on Docker 18.09.1 ...
🚀  Launching Kubernetes ... 
🌟  Enabling addons: default-storageclass, storage-provisioner
🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://minikube.sigs.k8s.io/docs/reference/drivers/none/

⚠️  kubectl and minikube configuration will be stored in /root
⚠️  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
⌛  Waiting for cluster to come online ...
🏄  Done! kubectl is now configured to use "minikube"
```

If you are running a desktop environment on a 2G machine, you want to enable a [swapfile](https://manpages.debian.org/buster/dphys-swapfile/dphys-swapfile.8.en.html).

```console
pi@raspberrypi:~ $ free -m
              total        used        free      shared  buff/cache   available
Mem:           1887         552         208          44        1127        1260
Swap:          2047           1        2046
pi@raspberrypi:~ $ tail -5 /etc/dphys-swapfile
# restrict size (computed and absolute!) to maximally this limit
#   can be set to empty for no limit, but beware of filled partitions!
#   this is/was a (outdated?) 32bit kernel limit (in MBytes), do not overrun it
#   but is also sensible on 64bit to prevent filling /var or even / partition
CONF_MAXSWAP=2048
```

**Comment by afbjorklund** [comment]
See also the original #5667 for running on arm64 (like ubuntu 18.04/19.10)
https://ubuntu.com/blog/roadmap-for-official-support-for-the-raspberry-pi-4

**Comment by medyagh** [comment]
this would be really cool !

**Comment by afbjorklund** [comment]
It is now available here:
https://storage.googleapis.com/minikube/releases/latest/minikube-linux-arm

**Comment by marjau** [comment]
It's not recommended the use of swap o any kubernetes distributions, you are recommended swapfile, is there any exception about swapfile ?? i have rpi4B 2G with raspbian beta arm64, i tried microk8s(heavy, but works), K3s(lighter and great), what about the performance on minikube, is it a good one ? ,  i wanna tried it... can you upload a screenshoot of top or htop with some pods working, thanks

**Comment by afbjorklund** [comment]
> It's not recommended the use of swap o any kubernetes distributions, you are recommended swapfile, is there any exception about swapfile ?? i have rpi4B 2G with raspbian beta arm64, i tried microk8s(heavy, but works), K3s(lighter and great), what about the performance on minikube, is it a good one ? , i wanna tried it... can you upload a screenshoot of top or htop with some pods working, thanks

It is something being debated. Running the control plane node with `kubeadm` on a raspberry pi with 2 GB memory is likely to start swapping... I would recommend getting 4 GB memory to start with, or to enable swap (or zram) if running with 2 GB memory.
This was when running the desktop on the _same_ machine, in order to leave the required 2 GB available (for kubeadm). You need less available memory when running k3s, probably can get away with 512 MB but it should at least be OK with 1 GB available.

But it's not ideal to run the `none` driver on a desktop anyway, so looking at other options (such as `docker` driver) in #9762. This issue is older, and probably works better as an auxiliary system with the `ssh` driver or something. It's "too small" to do both.
