### ISSUE TITLE
hyperv: Unable to start VM. creating host: create: creating: exit status 1

### ISSUE THREAD

**Issue by VirannaGadgoli** [kubernetes/minikube#6844]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by VirannaGadgoli** [comment]
X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create: creating: exit status 1

Facing this error while minikube start command

**Comment by tstromberg** [comment]
Do you mind sharing the output of:

`minikube start --alsologtostderr -v=4`

That should reveal which underlying command is failing. Thank you!

Also, please confirm that this is with the latest minikube release (v1.7.3)

**Comment by VirannaGadgoli** [comment]
Here is the output of that command:

 minikube start --alsologtostderr -v=4

I0308 13:54:59.135899   12744 notify.go:125] Checking for updates...
I0308 13:54:59.915787   12744 lock.go:35] WriteFile acquiring C:\Users\Admin\.minikube\last_update_check: {Name:mk828987ef1baeb3a88ee65561d38daec3e6ae2d Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
* minikube 1.8.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.8.1
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

I0308 13:54:59.936782   12744 start.go:249] hostinfo: {"hostname":"PEACE","uptime":90681,"bootTime":1583565218,"procs":192,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.18362 Build 18362","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"827ca56b-453b-4fa9-ad2d-e46405598836"}
W0308 13:54:59.936782   12744 start.go:257] gopshost.Virtualization returned error: not implemented yet
! minikube v1.7.3 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
I0308 13:54:59.987796   12744 driver.go:211] Setting default libvirt URI to qemu:///system
* Using the hyperv driver based on user configuration
I0308 13:55:02.017514   12744 start.go:296] selected driver: hyperv
I0308 13:55:02.037684   12744 start.go:472] validating driver "hyperv" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.7.3.iso Memory:2000 CPUs:2 DiskSize:20000 Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false Downloader:<nil> DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.17.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false} Nodes:[{Name:minikube IP: Port:8443 KubernetesVersion:v1.17.3 ControlPlane:true Worker:true}] Addons:map[]}
I0308 13:55:02.037684   12744 start.go:478] status for hyperv: {Installed:false Healthy:false Error:C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:
 Fix:Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All' Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/}

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed, but is specified by an existing profile. Please run 'minikube delete' or install hyperv

**Comment by tstromberg** [comment]
@VirannaGadgoli - Have you tried following the advice given by the command?

`Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'`

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
