### ISSUE TITLE
how to update the registry-mirror of a minikube instance？

### ISSUE THREAD

**Issue by fffffreedom** [kubernetes/minikube#6848]
how to update the registry-mirror of a minikube instance？i find it unable to update it, thks

**Comment by starbassma** [comment]
Hello @fffffreedom ,
If you want to create a new instance with _yourmirror_  you can use :

`minikube start --registry-mirror="http://yourmirror"`

if your VM instance is already created, you can't update registry-mirror through minikube cli, but you modify it manually inside your VM (though not recommended)  : 

1. Connect to the VM  using root :  `minikube ssh su - root` (password: root)

2. Edit this file /usr/lib/systemd/system/docker.service  using _vi_ or _editor_ to change the starting command :
`ExecStart=/usr/bin/dockerd -H tcp://0.0.0. ...... --registry-mirror http://newregistry`
3. save the changes, and then `minikube stop`  and `minikube start`


Regards,

**Comment by tstromberg** [comment]
It's worth noting that "minikube start" can be re-run safely against a VM that has been already created. It should update the configurations properly.

**Comment by starbassma** [comment]
@tstromberg  "minikube start" doesn't update the registry-mirror of an existing vm.

**Comment by starbassma** [comment]
maybe we should enhance the documentation with the "non-updatable parameters"

**Comment by fffffreedom** [comment]
@tstromberg @starbassma starbassma is right, "minikube start" doesn't update the registry-mirror of an existing vm. hoping this will work later, thks

**Comment by fffffreedom** [comment]
@tstromberg @starbassma starbassma is right, "minikube start" doesn't update the registry-mirror of an existing vm. hoping this will work later, thks

**Comment by nobodyiam** [comment]
> 1. Connect to the VM using root : minikube ssh su - root (password: root)
> 2. Edit this file /usr/lib/systemd/system/docker.service using vi or editor to change the starting command :
> ExecStart=/usr/bin/dockerd -H tcp://0.0.0. ...... --registry-mirror http://newregistry
> 3. save the changes, and then minikube stop and minikube start

This doesn't work for me, as the file `/usr/lib/systemd/system/docker.service` is restored after restart.

What did work me was to modify the `config.json` files under `~/.minikube` and update the `RegistryMirror` field, e.g.

~/.minikube/machines/minikube/config.json
```json
           "Labels": null,
           "LogLevel": "",
           "StorageDriver": "",
           "SelinuxEnabled": false,
           "TlsVerify": false,
           "RegistryMirror": [
              "http://newregistry"
            ],
           "InstallURL": ""
```

Hope it helps.
