### ISSUE TITLE
service list: info target port not being populated

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6860]
```
|-----------|----------------|-------------|--------------------------|
| NAMESPACE |      NAME      | TARGET PORT |           URL            |
|-----------|----------------|-------------|--------------------------|
| default   | hello-minikube |             | http://192.168.9.2:30130 |
|-----------|----------------|-------------|--------------------------|

```

in this case the target port is 8080 from https://minikube.sigs.k8s.io/docs/examples/

**Comment by starbassma** [comment]
Actually it show the name of the port (.spec.port.name) not the port

![Screenshot_20200303_005855](https://user-images.githubusercontent.com/6652482/75729433-16ee3000-5ceb-11ea-8ee1-e46a1659d59b.png)

the descriptor of the deployment :

![Screenshot_20200303_010730](https://user-images.githubusercontent.com/6652482/75729990-cdeaab80-5ceb-11ea-882c-4a9af76c42a4.png)
