### ISSUE TITLE
"Error from Server" on Minikube pause / unpause with Skaffold

### ISSUE THREAD

**Issue by etanshaul** [kubernetes/minikube#6861]
Minikube 1.7.3, started with `--vm-driver docker`

To reproduce:
- Pause minikube: `minikube pause -p [my-profile]`
- Unpause
- Run `skaffold dev` with `--minikube-profile [my-profile]`

Error printed in the Skaffold output:
```
[java-hello-world-6c6ffc74bf-cpv5v server] Error from server: Get https://192.168.9.2:10250/containerLogs/default/java-hello-world-6c6ffc74bf-cpv5v/server?follow=true&sinceSeconds=1: dial tcp 192.168.9.2:10250: connect: connection refused
```

This does not happen when starting the Skaffold session _after Minikube is in a `running` state_. I can only repro this when running Skaffold immediately after unpausing Minikube.

**Comment by etanshaul** [comment]
@balopat to see if this rings any bells and to see if this issue belongs on Skaffold instead.

**Comment by medyagh** [comment]
@etanshaul thanks for creating this issue, I will get back to this try to reproduce this issue.

**Comment by tstromberg** [comment]
I suspect this is a race condition caused by `unpause` declaring success after restarting the kubelet, but before the kubelet has started listening on the port.

**Comment by tstromberg** [comment]
Port 10250 (kubelet) will be unavailable if minikube is paused. We'll need to talk to the Skaffold folks to make it smarter on their end.
