### ISSUE TITLE
handle podman-env in PointToHostDockerDaemon

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6886]
```
	if err := oci.PointToHostDockerDaemon(); err != nil {
		return state.Error, errors.Wrap(err, "point host docker daemon")
	}
```

**Comment by afbjorklund** [comment]
Would have been nice to have an "oci" API without requiring the docker daemon concept in the name.

Basically what it wants to do is "env -u", to unset the environment. Not so much "point" to something ?
