### ISSUE TITLE
Labels for this repo

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#69]
I just changed colors for the `cla: xx` labels to match with the official Kubernetes repo.

In this issue we should consider which labels we need.
Examples:
 - priority/P[0-3]
 - area/(localkube|minikube|dependencies|build-release|testing|??)
 - help-wanted
 - lgtm
 - release-note
 - machine/(windows|osx|linux|arm)
 - kind/(bug|feature|documentation|support|??)

Also, we should remove those labels we aren't using, but are there by default
@dlorenc @vishh

**Comment by luxas** [comment]
@dlorenc I see you've labeled things :)
Opinions on this issue/proposal?

**Comment by dlorenc** [comment]
I like it. I think it's a bit heavyweight for now but we'll probably want most of them eventually. Want to set them up or should I?

**Comment by luxas** [comment]
I may fix the essential ones

**Comment by luxas** [comment]
This is fixed now.
