### ISSUE TITLE
apiserver stopped 

### ISSUE THREAD

**Issue by nengbowan** [kubernetes/minikube#6909]
yesterday is ok , but today apiserver status is stopped , i remember i do nothing bad ,
i just do some demos , spring cloud kubernetes , so ...

kubernetes logs about apiserver under below :
I0306 02:29:48.197937 1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] I0306 02:30:00.311107 1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] I0306 02:30:00.311985 1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] I0306 02:30:04.682874 1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] I0306 02:30:04.682911 1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] I0306 02:30:04.683169 1 clientconn.go:1016] blockingPicker: the picked transport is not ready, loop back to repick I0306 02:30:08.381540 1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] I0306 02:30:08.381877 1 asm_amd64.s:1337] balancerWrapper: got update addr from Notify: [{127.0.0.1:2379 <nil>}] W0306 02:30:08.382763 1 asm_amd64.s:1337] Failed to dial 127.0.0.1:2379: grpc: the connection is closing; please retry. F0306 02:30:08.186932 1 storage_decorator.go:57] Unable to create storage backend: config (&{ /registry {[https://127.0.0.1:2379] /var/lib/minikube/certs/apiserver-etcd-client.key /var/lib/minikube/certs/apiserver-etcd-client.crt /var/lib/minikube/certs/etcd/ca.crt} false true {0xc0008f3e60 0xc001ab0090} {{rbac.authorization.k8s.io v1} [{rbac.authorization.k8s.io } {rbac.authorization.k8s.io }] false} <nil> 5m0s 1m0s}), err (context deadline exceeded)

can anybody help ? appreciate u .

**Comment by nengbowan** [comment]
os : windows 
minikube  version : 1.1.1 
kubernete version :1.14.3

**Comment by tstromberg** [comment]
@nengbowan - My bet is that the VM ran out of memory, and the kernel killed the apiserver. If you run `minikube ssh dmesg`, you will likely see "Out of memory" type errrors.

The good news is that newer versions of minikube make it significantly more difficult for this situation to occur.  I recommend running `minikube delete` and upgrading to minikube v1.8.1. Let me know if this helps!

**Comment by nengbowan** [comment]
it works  ,thanks
