### ISSUE TITLE
nvidia-driver-installer addon fails to start (driver fails to install in the container)

### ISSUE THREAD

**Issue by Nick-Harvey** [kubernetes/minikube#6912]
**The exact command to reproduce the issue**:
Following the instructions on https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/

Host: Fedora 31
Kernel: 5.5.7-200.fc31.x86_64
Cuda Drivers Host: 10.2 
Nvidia Driver Host: Driver Version: 440.64

GPUs: 
- Titan V (vfio-pci driver assigned)
- Geforce 1080TI (host GPU nvidia driver)

Minikube start:
`minikube start --vm-driver kvm2 --kvm-gpu --cpus=12 --memory=25480`

Minikube Addons:
`minikube addons enable nvidia-gpu-device-plugin` 
This will fail initially, just edit the `dc/nvidia-gpu-device-plugin` and increase the mem to `100mi` and it'll start fine. 

**The full output of the command that failed**:<details>
`minikube addons enable nvidia-driver-installer`

The container fails to start. and once you fetch teh logs, it will return:

```
Configuring kernel sources... DONE
Running Nvidia installer...
/usr/local/nvidia /
Verifying archive integrity... OK
Uncompressing NVIDIA Accelerated Graphics Driver for Linux-x86_64 390.67.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

ERROR: An error occurred while performing the step: "Building kernel
       modules". See /var/log/nvidia-installer.log for details.


ERROR: An error occurred while performing the step: "Checking to see
       whether the nvidia-drm kernel module was successfully built". See
       /var/log/nvidia-installer.log for details.


ERROR: The nvidia-drm kernel module was not created.


ERROR: The nvidia-drm kernel module failed to build. This kernel module is
       required for the proper operation of DRM-KMS. If you do not need to
       use DRM-KMS, you can try to install this driver package again with
       the '--no-drm' option.


ERROR: Installation has failed.  Please see the file
       '/usr/local/nvidia/nvidia-installer.log' for details.  You may find
       suggestions on fixing installation problems in the README available
       on the Linux driver download page at www.nvidia.com.
```

</details>

**The output of the `minikube logs` command**:<details>

The minikube logs don't say much but here they are:
[minikube-logs.txt](https://github.com/kubernetes/minikube/files/4299842/minikube-logs.txt)

Logs from the nvidia-installer itself:
[nvidia-driver-installer-logs.txt](https://github.com/kubernetes/minikube/files/4299857/nvidia-driver-installer-logs.txt)
 

</details>

**The operating system version**:

**Comment by Nick-Harvey** [comment]
Additional Info...

```
➜  ~ nvidia-smi
Fri Mar  6 13:54:00 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.64       Driver Version: 440.64       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:2D:00.0 Off |                  N/A |
| 18%   31C    P8    12W / 280W |    166MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      7478      G   /usr/libexec/Xorg                             39MiB |
|    0      7509      G   /usr/bin/gnome-shell                         124MiB |
+-----------------------------------------------------------------------------+
```

**Titan GPU:**
```
23:00.0 0300: 10de:1d81 (rev a1) (prog-if 00 [VGA controller])
        Subsystem: 10de:1218
        Control: I/O+ Mem+ BusMaster- SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Interrupt: pin A routed to IRQ 37
        Region 0: Memory at f4000000 (32-bit, non-prefetchable) [size=16M]
        Region 1: Memory at e0000000 (64-bit, prefetchable) [size=256M]
        Region 3: Memory at f0000000 (64-bit, prefetchable) [size=32M]
        Region 5: I/O ports at e000 [size=128]
        Expansion ROM at f5000000 [disabled] [size=512K]
        Capabilities: <access denied>
        Kernel driver in use: vfio-pci
        Kernel modules: nouveau, nvidia_drm, nvidia

23:00.1 0403: 10de:10f2 (rev a1)
        Subsystem: 10de:1218
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR+ FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin B routed to IRQ 39
        Region 0: Memory at f5080000 (32-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: vfio-pci
        Kernel modules: snd_hda_intel
```

**Geforce 1080ti**
```
2d:00.0 0300: 10de:1b06 (rev a1) (prog-if 00 [VGA controller])
        Subsystem: 3842:6696
        Control: I/O+ Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx+
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0
        Interrupt: pin A routed to IRQ 106
        Region 0: Memory at f6000000 (32-bit, non-prefetchable) [size=16M]
        Region 1: Memory at c0000000 (64-bit, prefetchable) [size=256M]
        Region 3: Memory at d0000000 (64-bit, prefetchable) [size=32M]
        Region 5: I/O ports at f000 [size=128]
        [virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
        Capabilities: <access denied>
        Kernel driver in use: nvidia
        Kernel modules: nouveau, nvidia_drm, nvidia

2d:00.1 0403: 10de:10ef (rev a1)
        Subsystem: 3842:6696
        Control: I/O- Mem+ BusMaster+ SpecCycle- MemWINV- VGASnoop- ParErr- Stepping- SERR- FastB2B- DisINTx-
        Status: Cap+ 66MHz- UDF- FastB2B- ParErr- DEVSEL=fast >TAbort- <TAbort- <MAbort- >SERR- <PERR- INTx-
        Latency: 0, Cache Line Size: 64 bytes
        Interrupt: pin B routed to IRQ 102
        Region 0: Memory at f7080000 (32-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel
```

**Comment by Nick-Harvey** [comment]
Just attempted the process again with minikube v 1.8.1 and no luck :( 

I didn't see anything in the change notes that would have helped, but it was worth a shot :)

**Comment by afbjorklund** [comment]
Can you attach the nvidia-installer.log ?

```
ERROR: An error occurred while performing the step: "Building kernel
       modules". See /var/log/nvidia-installer.log for details.

```

**Comment by Nick-Harvey** [comment]
Unfortunately, I can't find a way to get the `/var/log/nvidia-installer.log` file I've tried:

```
➜  ~ kubectl exec -it nvidia-driver-installer-w6f97 -n kube-system /bin/bash
error: unable to upgrade connection: container not found ("pause")
```

long-shot
```
➜  ~ kubectl logs nvidia-driver-installer-w6f97 -n kube-system              
Error from server (BadRequest): container "pause" in pod "nvidia-driver-installer-w6f97" is waiting to start: PodInitializing
``` 

Any idea how to get access to the nvidia-installer.log ? I would love to know myself what Nvidia is saying. I have a sneaking suspicion that it has to do with where the nvidia drivers are installed to on the host, but that's just a guess.

**Comment by cmxela** [comment]
I'm having exactly the same problem with Fedora 31, in my case I have 

Host: Fedora 31
Kernel: 5.5.7-200.fc31.x86_64 
Cuda Drivers Host: 10.2
Nvidia Driver Host: Driver Version: 440.64

GPUs:

GeForce GT 710 (host GPU nvidia driver)
2 Geforce 1080TI (vfio-pci driver assigned)

**Comment by priyawadhwa** [comment]
Hey @Nick-Harvey does the nvidia pod ever have status `Running`?

I'm wondering because of this log when you tried to run:

```
$ kubectl logs nvidia-driver-installer-w6f97 -n kube-system       
> pod "nvidia-driver-installer-w6f97" is waiting to start: PodInitializing
```

The output of `kubectl describe po nvidia-xx-xx -n kube-system` might be helpful here.

If the pod is `Running`, could you try:

```
kubectl exec nvidia-driver-installer-w6f97 -n kube-system -- cat /var/log/nvidia-installer.log
```

**Comment by fvdnabee** [comment]
I'm setting up minikube with the kvm2 driver and gpu passthrough as per https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/.
GPU passthrough is available to the VM (the PCI-E devices are available as hardware to the minikube VM), but I'm failing to install the nvidia drivers inside the VM via

```
minikube addons enable nvidia-gpu-device-plugin
minikube addons enable nvidia-driver-installer
```

The nvidia-gpu-device-plugin pod is listed as running, whereas the second pod is stuck on Init (paused). I'm guessing this is the same issue @Nick-Harvey encountered. 

`kubectl get pods -n kube-system`
```
NAME                               READY   STATUS     RESTARTS   AGE
coredns-66bff467f8-562mh           1/1     Running    0          29m
coredns-66bff467f8-kcxhg           1/1     Running    0          29m
etcd-minikube                      1/1     Running    0          28m
kube-apiserver-minikube            1/1     Running    0          28m
kube-controller-manager-minikube   1/1     Running    0          28m
kube-proxy-mb5lf                   1/1     Running    0          29m
kube-scheduler-minikube            1/1     Running    0          28m
nvidia-driver-installer-c5bvd      0/1     Init:0/1   2          3m22s
nvidia-gpu-device-plugin-57n2l     1/1     Running    0          28m
storage-provisioner                1/1     Running    0          28m
```

`kubectl logs nvidia-gpu-device-plugin-57n2l -n kube-system`
```2020/05/26 14:26:03 Loading NVML
2020/05/26 14:26:03 Failed to initialize NVML: could not load NVML library.
2020/05/26 14:26:03 If this is a GPU node, did you set the docker default runtime to `nvidia`?
2020/05/26 14:26:03 You can check the prerequisites at: https://github.com/NVIDIA/k8s-device-plugin#prerequisites
2020/05/26 14:26:03 You can learn how to set the runtime at: https://github.com/NVIDIA/k8s-device-plugin#quick-start```

Some additional info on the pods:

<details>
<summary>`kubectl describe po nvidia-gpu-device-plugin-57n2l -n kube-system`</summary>
```
Name:                 nvidia-gpu-device-plugin-57n2l
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Node:                 minikube/192.168.39.201
Start Time:           Tue, 26 May 2020 16:25:57 +0200
Labels:               controller-revision-hash=7f89b4b55b
                      k8s-app=nvidia-gpu-device-plugin
                      pod-template-generation=1
Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Running
IP:                   172.17.0.4
IPs:
  IP:           172.17.0.4
Controlled By:  DaemonSet/nvidia-gpu-device-plugin
Containers:
  nvidia-gpu-device-plugin:
    Container ID:  docker://4babe01395d832acec7db0c6b449da25b5c8dd1114ed0e91c7d80f1255510f44
    Image:         nvidia/k8s-device-plugin:1.0.0-beta4
    Image ID:      docker-pullable://nvidia/k8s-device-plugin@sha256:94d46bf513cbc43c4d77a364e4bbd409d32d89c8e686e12551cc3eb27c259b90
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/nvidia-device-plugin
      -logtostderr
    State:          Running
      Started:      Tue, 26 May 2020 16:26:03 +0200
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:        50m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pvcvh (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:  
  default-token-pvcvh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pvcvh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     :NoExecute
                 :NoSchedule
                 node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  34m   default-scheduler  Successfully assigned kube-system/nvidia-gpu-device-plugin-57n2l to minikube
  Normal  Pulling    34m   kubelet, minikube  Pulling image "nvidia/k8s-device-plugin:1.0.0-beta4"
  Normal  Pulled     34m   kubelet, minikube  Successfully pulled image "nvidia/k8s-device-plugin:1.0.0-beta4"
  Normal  Created    34m   kubelet, minikube  Created container nvidia-gpu-device-plugin
  Normal  Started    34m   kubelet, minikube  Started container nvidia-gpu-device-plugin
```
</details>

<details>
<summary>`kubectl describe po nvidia-driver-installer-c5bvd -n kube-system`</summary>
```
Name:         nvidia-driver-installer-c5bvd
Namespace:    kube-system
Priority:     0
Node:         minikube/192.168.39.201
Start Time:   Tue, 26 May 2020 16:51:20 +0200
Labels:       controller-revision-hash=db985bcbc
              k8s-app=nvidia-driver-installer
              pod-template-generation=1
Annotations:  <none>
Status:       Pending
IP:           172.17.0.7
IPs:
  IP:           172.17.0.7
Controlled By:  DaemonSet/nvidia-driver-installer
Init Containers:
  nvidia-driver-installer:
    Container ID:   docker://6e972a48ef014a50b13a12a60a6d0179512d191c24170a5034a04f213eeb8809
    Image:          k8s.gcr.io/minikube-nvidia-driver-installer@sha256:492d46f2bc768d6610ec5940b6c3c33c75e03e201cc8786e04cc488659fd6342
    Image ID:       docker-pullable://k8s.gcr.io/minikube-nvidia-driver-installer@sha256:492d46f2bc768d6610ec5940b6c3c33c75e03e201cc8786e04cc488659fd6342
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Tue, 26 May 2020 16:53:47 +0200
      Finished:     Tue, 26 May 2020 16:54:47 +0200
    Ready:          False
    Restart Count:  2
    Requests:
      cpu:  150m
    Environment:
      NVIDIA_INSTALL_DIR_HOST:       /home/kubernetes/bin/nvidia
      NVIDIA_INSTALL_DIR_CONTAINER:  /usr/local/nvidia
      ROOT_MOUNT_DIR:                /root
    Mounts:
      /dev from dev (rw)
      /root from root-mount (rw)
      /usr/local/nvidia from nvidia-install-dir-host (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pvcvh (ro)
Containers:
  pause:
    Container ID:   
    Image:          k8s.gcr.io/pause:2.0
    Image ID:       
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-pvcvh (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev
    HostPathType:  
  nvidia-install-dir-host:
    Type:          HostPath (bare host directory volume)
    Path:          /home/kubernetes/bin/nvidia
    HostPathType:  
  root-mount:
    Type:          HostPath (bare host directory volume)
    Path:          /
    HostPathType:  
  default-token-pvcvh:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-pvcvh
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
                 nvidia.com/gpu:NoSchedule
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  4m12s                default-scheduler  Successfully assigned kube-system/nvidia-driver-installer-c5bvd to minikube
  Normal   Pulling    4m11s                kubelet, minikube  Pulling image "k8s.gcr.io/minikube-nvidia-driver-installer@sha256:492d46f2bc768d6610ec5940b6c3c33c75e03e201cc8786e04cc488659fd6342"
  Normal   Pulled     4m4s                 kubelet, minikube  Successfully pulled image "k8s.gcr.io/minikube-nvidia-driver-installer@sha256:492d46f2bc768d6610ec5940b6c3c33c75e03e201cc8786e04cc488659fd6342"
  Normal   Created    105s (x3 over 4m4s)  kubelet, minikube  Created container nvidia-driver-installer
  Normal   Started    105s (x3 over 4m4s)  kubelet, minikube  Started container nvidia-driver-installer
  Normal   Pulled     105s (x2 over 3m2s)  kubelet, minikube  Container image "k8s.gcr.io/minikube-nvidia-driver-installer@sha256:492d46f2bc768d6610ec5940b6c3c33c75e03e201cc8786e04cc488659fd6342" already present on machine
  Warning  BackOff    42s (x4 over 2m)     kubelet, minikube  Back-off restarting failed container
```
</details>

**Comment by ysow** [comment]
Hello @fvdnabee did you find a solution ? I'm having the same issue as you.

**Comment by fvdnabee** [comment]
@ysow It is my experience that gpu passthrough does not work with minikube kvm's driver. I managed to get GPU support working in minikube by using the none driver, as explained here https://minikube.sigs.k8s.io/docs/tutorials/nvidia_gpu/#using-the-none-driver

**Comment by Gsantomaggio** [comment]
Same problem here, I can start minikube:
```
minikube start --driver kvm2 --kvm-gpu
``` 
but I get the same errors above.

Minikube version 1.11.0


With docker works:

```
 docker run --gpus all nvidia/cuda:10.0-base nvidia-smi
Thu Jun 18 21:03:32 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 450.36.06    CUDA Version: 11.0     |
```


@fvdnabee I can't make it running not even with  none drive :(

**Comment by priyawadhwa** [comment]
Hey @Nick-Harvey does this work with the none driver for you?

**Comment by sharifelgamal** [comment]
The none driver workaround is just that, a workaround. I suspect this should also work with the docker and kvm2 drivers.

**Comment by skol101** [comment]
Hello,
I've got similar issue: looks like addon uses very old NVIDIA GPU driver 390.67 which doesn't support RTX 3090/3080.
How can I install the addon with the new NVIDIA driver?

**Comment by sharifelgamal** [comment]
We don't currently have the bandwidth to properly maintain the nvidia addon, but would be happy to accept PRs to fix it.

Reopening for visibility.

**Comment by skol101** [comment]
How can I submit a PR if the source Docker is located in a different repo? 

https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/nvidia-driver-installer/minikube

**Comment by skol101** [comment]
I got it, the issue is that RTX30X0 aren't supported in vGPU mode https://docs.nvidia.com/grid/latest/grid-vgpu-release-notes-generic-linux-kvm/index.html#updates-release-update-1

Bloody nvidia.

**Comment by ckjoris** [comment]
hey @skol101, how did you figure out its due to grid/vgpu unsupported ? I know for sure that rtx30 series support passthrough for a single VM, like for KVM.
I'm looking at the nvidia-installer.log, seems that driver is just failling to compile...
by the way, one can find nvidia-installer.log by doing `minikube ssh`, then `less /home/kubernetes/bin/nvidia/nvidia-installer.log`

**Comment by joaquinfdez** [comment]
Could it be due to vGPU is not supported for the GeForce series?

**Comment by joysn71** [comment]
The issue is in the nvidia-driver-installer Docker image. Found using the following command:
`minikube kubectl -- cluster-info dump`.

When the container is using the image it runs through the driver install process, and this process does not find python3 in the container which is created from the image. Too see the following issue: https://github.com/kubernetes/minikube/issues/15123

From cluster-info dump:
```
==== START logs for container nvidia-driver-installer of pod kube-system/nvidia-driver-installer-wftvf ====
+ NVIDIA_DRIVER_VERSION=510.60.02
+ NVIDIA_DRIVER_DOWNLOAD_URL_DEFAULT=https://us.download.nvidia.com/XFree86/Linux-x86_64/510.60.02/NVIDIA-Linux-x86_64-510.60.02.run
+ NVIDIA_DRIVER_DOWNLOAD_URL=https://us.download.nvidia.com/XFree86/Linux-x86_64/510.60.02/NVIDIA-Linux-x86_64-510.60.02.run
+ NVIDIA_INSTALL_DIR_HOST=/home/kubernetes/bin/nvidia
+ NVIDIA_INSTALL_DIR_CONTAINER=/usr/local/nvidia
++ basename https://us.download.nvidia.com/XFree86/Linux-x86_64/510.60.02/NVIDIA-Linux-x86_64-510.60.02.run
+ NVIDIA_INSTALLER_RUNFILE=NVIDIA-Linux-x86_64-510.60.02.run
+ ROOT_MOUNT_DIR=/root
+ CACHE_FILE=/usr/local/nvidia/.cache
++ uname -r
+ KERNEL_VERSION=5.10.57
++ cut -d . -f 1
+++ uname -r
++ echo 5.10.57
+ MAJOR_KERNEL_VERSION=5
+ set +x
KERNEL_VERSION: 5.10.57
Checking cached version
Cache file /usr/local/nvidia/.cache not found.
Downloading kernel sources...
/usr/src /
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  6  111M    6 7455k    0     0  11.1M      0  0:00:09 --:--:--  0:00:09 11.0M^M 32  111M   32 35.8M    0  >
/
Downloading kernel sources... DONE.
Configuring installation directories...
/usr/local/nvidia /
Updating container's ld cache...
Updating container's ld cache... DONE.
/
Configuring installation directories... DONE.
Downloading Nvidia installer...
/usr/local/nvidia /
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
^M  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0^M  4  313M    4 14.7M    0     0  17.5M      0  0:00:17 --:--:--  0:00:17 17.5M^M 14  313M   14 45.3M    0  >
/
Downloading Nvidia installer... DONE.
Configuring kernel sources...
/usr/src/linux-5.10.57 /
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/confdata.o
  HOSTCC  scripts/kconfig/expr.o
  LEX     scripts/kconfig/lexer.lex.c
  YACC    scripts/kconfig/parser.tab.[ch]
  HOSTCC  scripts/kconfig/lexer.lex.o
  HOSTCC  scripts/kconfig/parser.tab.o
  HOSTCC  scripts/kconfig/preprocess.o
  HOSTCC  scripts/kconfig/symbol.o
  HOSTCC  scripts/kconfig/util.o
  HOSTLD  scripts/kconfig/conf
#
# configuration written to .config
#
  SYSTBL  arch/x86/include/generated/asm/syscalls_32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_32_ia32.h
  SYSHDR  arch/x86/include/generated/asm/unistd_64_x32.h
  SYSTBL  arch/x86/include/generated/asm/syscalls_64.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_32.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_64.h
  SYSHDR  arch/x86/include/generated/uapi/asm/unistd_x32.h
  HOSTCC  arch/x86/tools/relocs_32.o
  HOSTCC  arch/x86/tools/relocs_64.o
  HOSTCC  arch/x86/tools/relocs_common.o
  HOSTLD  arch/x86/tools/relocs
  HOSTCC  scripts/genksyms/genksyms.o
  YACC    scripts/genksyms/parse.tab.[ch]
  HOSTCC  scripts/genksyms/parse.tab.o
  LEX     scripts/genksyms/lex.lex.c
  HOSTCC  scripts/genksyms/lex.lex.o
  HOSTLD  scripts/genksyms/genksyms
  HOSTCC  scripts/selinux/genheaders/genheaders
  HOSTCC  scripts/selinux/mdp/mdp
  HOSTCC  scripts/kallsyms
  HOSTCC  scripts/recordmcount
  HOSTCC  scripts/sorttable
  HOSTCC  scripts/asn1_compiler
  HOSTCC  scripts/extract-cert
  WRAP    arch/x86/include/generated/uapi/asm/bpf_perf_event.h
  WRAP    arch/x86/include/generated/uapi/asm/errno.h
  WRAP    arch/x86/include/generated/uapi/asm/fcntl.h
  WRAP    arch/x86/include/generated/uapi/asm/ioctl.h
  WRAP    arch/x86/include/generated/uapi/asm/ioctls.h
  WRAP    arch/x86/include/generated/uapi/asm/ipcbuf.h
  WRAP    arch/x86/include/generated/uapi/asm/param.h
  WRAP    arch/x86/include/generated/uapi/asm/poll.h
  WRAP    arch/x86/include/generated/uapi/asm/resource.h
...
  LD       /usr/src/linux-5.10.57/tools/objtool/objtool-in.o
  LINK     /usr/src/linux-5.10.57/tools/objtool/objtool
  DESCEND  bpf/resolve_btfids
  MKDIR     /usr/src/linux-5.10.57/tools/bpf/resolve_btfids//libbpf

Auto-detecting system features:
...                        libelf: [ ESC[32monESC[m  ]
...                          zlib: [ ESC[32monESC[m  ]
...                           bpf: [ ESC[32monESC[m  ]

  GEN      /usr/src/linux-5.10.57/tools/bpf/resolve_btfids/libbpf/bpf_helper_defs.h
/usr/bin/env: 'python3': No such file or directory
Makefile:182: recipe for target '/usr/src/linux-5.10.57/tools/bpf/resolve_btfids/libbpf/bpf_helper_defs.h' failed
make[3]: *** [/usr/src/linux-5.10.57/tools/bpf/resolve_btfids/libbpf/bpf_helper_defs.h] Error 127
make[3]: *** Deleting file '/usr/src/linux-5.10.57/tools/bpf/resolve_btfids/libbpf/bpf_helper_defs.h'
Makefile:44: recipe for target '/usr/src/linux-5.10.57/tools/bpf/resolve_btfids//libbpf/libbpf.a' failed
make[2]: *** [/usr/src/linux-5.10.57/tools/bpf/resolve_btfids//libbpf/libbpf.a] Error 2
Makefile:71: recipe for target 'bpf/resolve_btfids' failed
make[1]: *** [bpf/resolve_btfids] Error 2
make: *** [tools/bpf/resolve_btfids] Error 2
Makefile:1947: recipe for target 'tools/bpf/resolve_btfids' failed
==== END logs for container nvidia-driver-installer of pod kube-system/nvidia-driver-installer-wftvf ====
==== START logs for container pause of pod kube-system/nvidia-driver-installer-wftvf ====
Request log error: the server rejected our request for an unknown reason (get pods nvidia-driver-installer-wftvf)
==== END logs for container pause of pod kube-system/nvidia-driver-installer-wftvf ====
```
I installed package python3.8 using apt inside the image/container from the image, and symlinked the binary python3.8 to python3 in /usr/bin, but this did not help. And I am not sure how I can "update" the modified image for minikube to consider it.
