### ISSUE TITLE
hyperv: PermissionDenied: (:) [Start-VM], VirtualizationException

### ISSUE THREAD

**Issue by ouyangck** [kubernetes/minikube#6918]
After installed minikube, I tried to start it with minikube start --vm-driver=hyperv. But got the following error:

E0306 15:00:09.591838   12772 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start. (Virtual machine ID D43F8370-1920-4398-AAF3-19C8C7B6F0E6)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : PermissionDenied: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : AccessDenied,Microsoft.HyperV.PowerShell.Commands.StartVM

**Comment by tstromberg** [comment]
Was this from a command or powershell Window running as an administrator?

Also, can you paste the full output of:

`minikube start --alsologtostderr -v=2`

Thank you.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!

**Comment by ibmhack2020** [comment]
> I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`
> 
> If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.
> 
> Thank you for opening the issue!

Am also facing same issue please assist me on this

Thanks
Arul

**Comment by AAATechGuy** [comment]
/reopen
attaching logs.
[logs.txt](https://github.com/kubernetes/minikube/files/7214287/logs.txt)
