### ISSUE TITLE
Preload containerd images 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6933]
implement preload for containerd for overlay2.
by generating a tar ball with all images for a kubernetes version, similar to our docker runtime.

**Comment by afbjorklund** [comment]
> by generating a tar ball with all images for a kubernetes version, similar to our docker runtime.

That is **not** how the current preload works, though. It just dumps the `/var/lib` internals (the guts)

```go
func createImageTarball(tarballFilename string) error {
	// directories to save into tarball
	dirs := []string{
		fmt.Sprintf("./lib/docker/%s", dockerStorageDriver),
		"./lib/docker/image",
		"./lib/minikube/binaries",
	}
	args := []string{"exec", profile, "sudo", "tar", "-I", "lz4", "-C", "/var", "-cvf", tarballFilename}
	args = append(args, dirs...)
	cmd := exec.Command("docker", args...)
	cmd.Stdout = os.Stdout
	if err := cmd.Run(); err != nil {
		return errors.Wrapf(err, "tarball cmd: %s", cmd.Args)
	}
	return nil
}
```

So in this case, it should dump the `/var/lib/containerd` instead of `/var/lib/docker`.

It is still a good idea though (generating the image-only tarball), will add a separate issue for it

**Comment by afbjorklund** [comment]
Nobody uses containerd with minikube, and if they do - they could survive without the preload
