### ISSUE TITLE
Add makefile target to generate HTML integration test results windows

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6937]
Ideally I want to run a make target that runs integraiton tests and generates html report for me.
there should be option to test small or all tests

so I dont have to keep opening a cheat sheet for it

**Comment by priyawadhwa** [comment]
@medyagh are you still working on this?

**Comment by medyagh** [comment]
was done except for windows that will be done by https://github.com/kubernetes/minikube/issues/9306
