### ISSUE TITLE
Cannot preload container runtime docker on windows client

### ISSUE THREAD

**Issue by cvila84** [kubernetes/minikube#6944]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>
$ minikube start --v=8
* minikube v1.8.1 on Microsoft Windows 7 Enterprise Service Pack 1 6.1.7601 Build 7601
* Automatically selected the virtualbox driver
* Downloading VM boot image ...
    > minikube-v1.8.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.8.0.iso: 173.56 MiB / 173.56 MiB [ 100.00% 1.97 MiB p/s 1m28s
* Creating virtualbox VM (CPUs=2, Memory=4051MB, Disk=20000MB) ...
* Downloading preloaded images tarball for k8s v1.17.3 ...
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 116.25 MiB / 499* Found network options:
  - HTTP_PROXY=http://10.43.216.8:8080
  - HTTPS_PROXY=http://10.43.216.8:8080
  - NO_PROXY=localhost,minikube,127.0.0.1,192.168.99.100
  - http_proxy=http://10.43.216.8:8080
  - https_proxy=http://10.43.216.8:8080
  - no_proxy=localhost,minikube,127.0.0.1,192.168.99.100
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 499.26 MiB / 499
E0307 22:08:30.857999   10480 config.go:71] Failed to preload container runtime Docker: copying file: sudo test -d \ && sudo scp -t \ && sudo touch -d "2020-03-07 22:08:29.4839996 +0100" \/preloaded.tar.lz4: Process exited with status 1
output: , falling back to caching images
</details>

**The operating system version**:
Windows 7 x64

I think it is related to
https://github.com/kubernetes/minikube/blob/cbda04cf6bbe65e987ae52bb393c10099ab62014/pkg/minikube/cruntime/docker.go#L278

The command is generated with windows filepath.Dir and filepath.Base whereas it is executed in the VM so with linux path separators

**Comment by afbjorklund** [comment]
Wonder how this one passed the integration tests (on Windows), but the fallback should be working

**Comment by cvila84** [comment]
I confirm the fallback works but it takes time as it first downloads 500M for nothing :)

**Comment by medyagh** [comment]
@cvila84 thank you very much reporting this issue ! that is defentiy a bug !

shamefully our windows integration tests are broken, we have a WIP PR to add windows docker test for github actions.

I will make sure this bug is fixed as soon as possible.

**Comment by cvila84** [comment]
@afbjorklund did not mean to be rude with my comment, I'm actually happy it still works !
@medyagh many thanks !

**Comment by Pbabbar7** [comment]
I am getting error.. 
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 499.26 MiB / 499
E0309 23:50:01.351036    4104 config.go:71] Failed to preload container runtime Docker: copying file: sudo test -d \ && sudo scp -t \ && sudo touch -d "2020-03-09 23:49:59.6914307 +0530" \/preloaded.tar.lz4: Process exited with status 1
output: , falling back to caching images

**Comment by afbjorklund** [comment]
> @afbjorklund did not mean to be rude with my comment, I'm actually happy it still works !

Sorry, I just meant it was sad that it failed in Windows - too few github reaction icons to click I suppose...

We need to get Windows CI back

**Comment by DeepakYadav17** [comment]
Failing for me too:
`Failed to preload container runtime Docker: copying file: sudo test -d \ && sudo scp -t \ && sudo touch -d "2020-03-13 14:00:54.287043 +0530" \/preloaded.tar.lz4: Process exited with status 1`

**Comment by hejunion** [comment]
retry more and using "minikube delete" for cleanning

https://github.com/kubernetes/minikube/issues/6938
