### ISSUE TITLE
kubeconfig/admin: a kubeconfig file "/etc/kubernetes/admin.conf" exists already but has got the wrong CA cert

### ISSUE THREAD

**Issue by happykayy** [kubernetes/minikube#6946]
I'm working under ubuntu. After installed minikube, I run the command :
minikube start --vm-driver=none

I got the output:
😄  minikube v1.7.3 on Ubuntu 18.04
✨  Using the none driver based on user configuration
⌛  Reconfiguring existing host ...
🔄  Starting existing none VM for "minikube" ...
ℹ️   OS release is Ubuntu 18.04.3 LTS
🐳  Preparing Kubernetes v1.17.3 on Docker 18.09.7 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🚀  Launching Kubernetes ... 

💣  **Error starting cluster: running cmd: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.3:$PATH kubeadm init phase kubeconfig all --config /var/tmp/minikube/kubeadm.yaml": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.3:$PATH kubeadm init phase kubeconfig all --config /var/tmp/minikube/kubeadm.yaml": exit status 1
stdout:
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"**

stderr:
W0308 18:10:01.013031     358 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0308 18:10:01.013058     358 validation.go:28] Cannot validate kubelet config - no validator is available
error execution phase kubeconfig/admin: a kubeconfig file "/etc/kubernetes/admin.conf" exists already but has got the wrong CA cert
To see the stack trace of this error execute with --v=5 or higher

any idea how can I solve that error? Thanks for your help !

**Comment by medyagh** [comment]
@happykayy  I am curious had you previously copied certs to ~/.minikub/certs for corp certs?

we fixed a bug about certs in newest version minikube 1.8.1
do you mind trying with latest version to see if that will fix the problem?

**Comment by RealDekkia** [comment]
Hello,
I have the exact same problem on minikube 1.8.2.

I even tried to see what happens when I delete /etc/kubernetes/admin.conf but the file gets created when running the command again.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
