### ISSUE TITLE
minikubestart --driver=none fails: [ERROR NumCPU]: the number of available CPUs 1 is less than the required 2

### ISSUE THREAD

**Issue by bkumar2018** [kubernetes/minikube#6961]
**The exact command to reproduce the issue**:

**#minikube start --driver=none**

**The full output of the command that failed**:<details>

**#minikube start --driver=none**
* minikube v1.8.1 on Centos 7.7.1908
* Using the none driver based on user configuration
* Running on localhost (CPUs=1, Memory=4797MB, Disk=13706MB) ...
* Downloading preloaded images tarball for k8s v1.17.3 ...
* OS release is CentOS Linux 7 (Core)
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 3.47 MiB / 499.2* Preparing Kube                          rnetes v1.17.3 on Docker 19.03.4 ...
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm: 37.52 MiB / 37.52 MiB [---------------] 100.00% 1.49 MiB p/s 25s
    > kubectl: 41.48 MiB / 41.48 MiB [---------------] 100.00% 1.44 MiB p/s 29s
    > kubelet: 106.42 MiB / 106.42 MiB [-------------] 100.00% 2.17 MiB p/s 50s
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 126.75 MiB / 499* Launching Kube                          rnetes ...
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 132.45 MiB / 499*
X Error starting cluster: init failed. output: "-- stdout --\n[init] Using Kubernetes version:                           v1.17.3\n[preflight] Running pre-flight checks\n\n-- /stdout --\n** stderr ** \nW0309 01:56:50.                          862665    2254 validation.go:28] Cannot validate kube-proxy config - no validator is available\                          nW0309 01:56:50.862714    2254 validation.go:28] Cannot validate kubelet config - no validator                           is available\n\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driv                          er. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/doc                          s/setup/cri/\n\t[WARNING Swap]: running with swap on is not supported. Please disable swap\n\t[                          WARNING FileExisting-socat]: socat not found in system path\n\t[WARNING Service-Kubelet]: kubel                          et service is not enabled, please run 'systemctl enable kubelet.service'\nerror execution phase                           preflight: [preflight] Some fatal errors occurred:\n\t[ERROR NumCPU]: the number of available                           CPUs 1 is less than the required 2\n[preflight] If you know what you are doing, you can make a                           check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error exec                          ute with --v=5 or higher\n\n** /stderr **": /bin/bash -c "sudo env PATH=/var/lib/minikube/binar                          ies/v1.17.3:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-erro                          rs=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-                          minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-ku                          bernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-                          manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,SystemVerificati                          on": exit status 1
stdout:
[init] Using Kubernetes version: v1.17.3
[preflight] Running pre-flight checks

stderr:
W0309 01:56:50.862665    2254 validation.go:28] Cannot validate kube-proxy config - no validato                          r is available
W0309 01:56:50.862714    2254 validation.go:28] Cannot validate kubelet config - no validator i                          s available
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The re                          commended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING Swap]: running with swap on is not supported. Please disable swap
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable                           kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR NumCPU]: the number of available CPUs 1 is less than the required 2
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-prefl                          ight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

[root@192.168.0.107 ~]#minikube logs
* ==> Docker <==
* -- Logs begin at Mon 2020-03-09 01:22:09 EDT, end at Mon 2020-03-09 02:00:32 EDT. --
* Mar 09 01:22:18 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.836896336-04:00" level=info msg="Starting up"
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.856193409-04:00" level=info msg="parsed scheme: \"unix\"" module=grpc
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.856249127-04:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.856420581-04:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.856452183-04:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.965810615-04:00" level=info msg="parsed scheme: \"unix\"" module=grpc
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.965984801-04:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.966062564-04:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Mar 09 01:22:24 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:24.966121580-04:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Mar 09 01:22:25 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:25.492661082-04:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
* Mar 09 01:22:26 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:26.842488459-04:00" level=info msg="Loading containers: start."
* Mar 09 01:22:27 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:27.550430169-04:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Mar 09 01:22:27 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:27.639873014-04:00" level=info msg="Loading containers: done."
* Mar 09 01:22:28 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:28.081629922-04:00" level=info msg="Docker daemon" commit=9013bf583a graphdriver(s)=overlay2 version=19.03.4
* Mar 09 01:22:28 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:28.081692453-04:00" level=info msg="Daemon has completed initialization"
* Mar 09 01:22:28 localhost.localdomain dockerd[1091]: time="2020-03-09T01:22:28.134462809-04:00" level=info msg="API listen on /var/run/docker.sock"
* Mar 09 01:22:28 localhost.localdomain systemd[1]: Started Docker Application Container Engine.
* Mar 09 01:55:56 localhost.localdomain systemd[1]: Stopping Docker Application Container Engine...
* Mar 09 01:55:56 localhost.localdomain dockerd[1091]: time="2020-03-09T01:55:56.364560155-04:00" level=info msg="Processing signal 'terminated'"
* Mar 09 01:55:56 localhost.localdomain dockerd[1091]: time="2020-03-09T01:55:56.365275298-04:00" level=info msg="Daemon shutdown complete"
* Mar 09 01:55:56 localhost.localdomain systemd[1]: Stopped Docker Application Container Engine.
* Mar 09 01:55:56 localhost.localdomain systemd[1]: Starting Docker Application Container Engine...
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.428965117-04:00" level=info msg="Starting up"
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.429979238-04:00" level=info msg="parsed scheme: \"unix\"" module=grpc
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.429990747-04:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.430005869-04:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.430014322-04:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.433131721-04:00" level=info msg="parsed scheme: \"unix\"" module=grpc
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.433146603-04:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.433158621-04:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.433164926-04:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.476233612-04:00" level=info msg="[graphdriver] using prior storage driver: overlay2"
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.505285397-04:00" level=info msg="Loading containers: start."
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.637542687-04:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.694524957-04:00" level=info msg="Loading containers: done."
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.722209533-04:00" level=info msg="Docker daemon" commit=9013bf583a graphdriver(s)=overlay2 version=19.03.4
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.722253414-04:00" level=info msg="Daemon has completed initialization"
* Mar 09 01:55:56 localhost.localdomain dockerd[2038]: time="2020-03-09T01:55:56.752569157-04:00" level=info msg="API listen on /var/run/docker.sock"
* Mar 09 01:55:56 localhost.localdomain systemd[1]: Started Docker Application Container Engine.
*
* ==> container status <==
* which: no crictl in (/root/.minikube/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
* sudo: crictl: command not found
* CONTAINER ID        IMAGE                           COMMAND                  CREATED             STATUS                    PORTS               NAMES
* facfe0ec7016        bkumar2018/simpleweb            "docker-entrypoint.s…"   2 days ago          Exited (0) 2 days ago                         flamboyant_dubinsky
* 2e12a3e3072c        48e2138bda3e                    "/bin/bash"              2 days ago          Exited (127) 2 days ago                       amazing_bardeen
* b8ba48f8bf79        hello-world                     "/hello"                 2 days ago          Exited (0) 2 days ago                         determined_mclean
* db496738ae17        dockeridbiru2019/ubuntu-hello   "echo 'Hello welcome…"   2 days ago          Exited (0) 2 days ago                         festive_beaver
*
* ==> dmesg <==
* dmesg: invalid option -- '='
*
* Usage:
*  dmesg [options]
*
* Options:
*  -C, --clear                 clear the kernel ring buffer
*  -c, --read-clear            read and clear all messages
*  -D, --console-off           disable printing messages to console
*  -d, --show-delta            show time delta between printed messages
*  -e, --reltime               show local time and time delta in readable format
*  -E, --console-on            enable printing messages to console
*  -F, --file <file>           use the file instead of the kernel log buffer
*  -f, --facility <list>       restrict output to defined facilities
*  -H, --human                 human readable output
*  -k, --kernel                display kernel messages
*  -L, --color                 colorize messages
*  -l, --level <list>          restrict output to defined levels
*  -n, --console-level <level> set level of messages printed to console
*  -P, --nopager               do not pipe output into a pager
*  -r, --raw                   print the raw message buffer
*  -S, --syslog                force to use syslog(2) rather than /dev/kmsg
*  -s, --buffer-size <size>    buffer size to query the kernel ring buffer
*  -T, --ctime                 show human readable timestamp (could be
*                                inaccurate if you have used SUSPEND/RESUME)
*  -t, --notime                don't print messages timestamp
*  -u, --userspace             display userspace messages
*  -w, --follow                wait for new messages
*  -x, --decode                decode facility and level to readable string
*
*  -h, --help     display this help and exit
*  -V, --version  output version information and exit
*
* Supported log facilities:
*     kern - kernel messages
*     user - random user-level messages
*     mail - mail system
*   daemon - system daemons
*     auth - security/authorization messages
*   syslog - messages generated internally by syslogd
*      lpr - line printer subsystem
*     news - network news subsystem
*
* Supported log levels (priorities):
*    emerg - system is unusable
*    alert - action must be taken immediately
*     crit - critical conditions
*      err - error conditions
*     warn - warning conditions
*   notice - normal but significant condition
*     info - informational
*    debug - debug-level messages
*
*
* For more details see dmesg(q).
*
* ==> kernel <==
*  02:00:32 up 38 min,  2 users,  load average: 0.01, 0.06, 0.06
* Linux localhost.localdomain 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* PRETTY_NAME="CentOS Linux 7 (Core)"
*
* ==> kubelet <==
* -- Logs begin at Mon 2020-03-09 01:22:09 EDT, end at Mon 2020-03-09 02:00:32 EDT. --
* Mar 09 02:00:29 localhost.localdomain kubelet[3889]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3889]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3889]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3889]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3889]: F0309 02:00:29.236232    3889 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Mar 09 02:00:29 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Mar 09 02:00:29 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
* Mar 09 02:00:29 localhost.localdomain systemd[1]: kubelet.service failed.
* Mar 09 02:00:29 localhost.localdomain systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Mar 09 02:00:29 localhost.localdomain systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Mar 09 02:00:29 localhost.localdomain systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Mar 09 02:00:29 localhost.localdomain kubelet[3894]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3894]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3894]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3894]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3894]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3894]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:29 localhost.localdomain kubelet[3894]: F0309 02:00:29.986548    3894 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Mar 09 02:00:29 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Mar 09 02:00:29 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
* Mar 09 02:00:29 localhost.localdomain systemd[1]: kubelet.service failed.
* Mar 09 02:00:30 localhost.localdomain systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Mar 09 02:00:30 localhost.localdomain systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Mar 09 02:00:30 localhost.localdomain systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Mar 09 02:00:30 localhost.localdomain kubelet[3899]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:30 localhost.localdomain kubelet[3899]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:30 localhost.localdomain kubelet[3899]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:30 localhost.localdomain kubelet[3899]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:30 localhost.localdomain kubelet[3899]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:30 localhost.localdomain kubelet[3899]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:30 localhost.localdomain kubelet[3899]: F0309 02:00:30.736318    3899 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Mar 09 02:00:30 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Mar 09 02:00:30 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
* Mar 09 02:00:30 localhost.localdomain systemd[1]: kubelet.service failed.
* Mar 09 02:00:31 localhost.localdomain systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Mar 09 02:00:31 localhost.localdomain systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Mar 09 02:00:31 localhost.localdomain systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Mar 09 02:00:31 localhost.localdomain kubelet[3911]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:31 localhost.localdomain kubelet[3911]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:31 localhost.localdomain kubelet[3911]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:31 localhost.localdomain kubelet[3911]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:31 localhost.localdomain kubelet[3911]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:31 localhost.localdomain kubelet[3911]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:31 localhost.localdomain kubelet[3911]: F0309 02:00:31.486820    3911 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Mar 09 02:00:31 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Mar 09 02:00:31 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
* Mar 09 02:00:31 localhost.localdomain systemd[1]: kubelet.service failed.
* Mar 09 02:00:32 localhost.localdomain systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Mar 09 02:00:32 localhost.localdomain systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Mar 09 02:00:32 localhost.localdomain systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Mar 09 02:00:32 localhost.localdomain kubelet[3916]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:32 localhost.localdomain kubelet[3916]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:32 localhost.localdomain kubelet[3916]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:32 localhost.localdomain kubelet[3916]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:32 localhost.localdomain kubelet[3916]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:32 localhost.localdomain kubelet[3916]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Mar 09 02:00:32 localhost.localdomain kubelet[3916]: F0309 02:00:32.253097    3916 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Mar 09 02:00:32 localhost.localdomain systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Mar 09 02:00:32 localhost.localdomain systemd[1]: Unit kubelet.service entered failed state.
* Mar 09 02:00:32 localhost.localdomain systemd[1]: kubelet.service failed.

</details>

**The operating system version**:
#uname -a
Linux localhost.localdomain 3.10.0-1062.4.1.el7.x86_64 #1 SMP Fri Oct 18 17:15:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by afbjorklund** [comment]
@bkumar2018 : You will need to find a bigger computer, for minikube

**Comment by RA489** [comment]
@bkumar2018 your VM or machine needs to have at least 2 CPU cores.
