### ISSUE TITLE
Minikube start error: E0310 02:47:49.441456    9536 cache.go:116] Error caching images:  saving checksum file

### ISSUE THREAD

**Issue by hantsy** [kubernetes/minikube#6967]
The iso download is successfully, but the checksum failed. This could a network issue in China. I am using Microsoft Hyper-V as VM. 

In my host, I can access the URL *Get https://www.googleapis.com/storage/v1/b/minikube-preloaded-volume-tarballs/o/preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4?alt=json&prettyPrint=false&projection=full* via a proxy. I am not sure this URL is accessed in my host or the client Minikube VM?

Are there some approaches to avoid this checksum? Using Google API is evil for China developers.

```bash
$ minikube start --driver=hyperv --memory=4096m --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
* minikube v1.8.1 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
* Using the hyperv driver based on existing profile
* Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
* Downloading VM boot image ...
* Reconfiguring existing host ...
* Using the running hyperv "minikube" VM ...
* Downloading preloaded images tarball for k8s v1.17.3 ...
E0310 02:47:49.441456    9536 cache.go:116] Error caching images:  saving checksum file: getting storage object: Get https://www.googleapis.com/storage/v1/b/minikube-preloaded-volume-tarballs/o/preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4?alt=json&prettyPrint=false&projection=full: dial tcp 216.58.200.42:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
E0310 02:47:49.479453    9536 config.go:71] Failed to preload container runtime Docker: copying file: sudo test -d \ && sudo scp -t \ && sudo touch -d "2020-03-10 02:33:03.9341566 +0800" \/preloaded.tar.lz4: Process exited with status 1
output: , falling back to caching images
```

**Comment by afbjorklund** [comment]
Unfortunately there is yet no way to disable preloading, and no way to select a local mirror either.

Both of these would probably be nice features to have.

But it after attempting the download, it should fallback to regular images (and the image repository)

ping @priyawadhwa and @medyagh

**Comment by hantsy** [comment]
@afbjorklund Oh, tried again, it works after waiting for minutes. Thanks.
