### ISSUE TITLE
vmwarefusion: space of disk does not match minikube start --disk-size=30g

### ISSUE THREAD

**Issue by dgoldssfo** [kubernetes/minikube#697]
BUG REPORT

**Minikube version** (use `minikube version`): 0.11.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OS/X 10.11.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): vmwarefusion
- **Docker version** (e.g. `docker -v`): 1.12.1
- **Install tools**: n/a
- **Others**:

**What happened**: I ran minikube start --memory=4096 --disk-size=30g --vm-driver=vmwarefusion

**What you expected to happen**: I expected the minikube VM would be created with 30 GB

**How to reproduce it** (as minimally and precisely as possible): Run minikube start --memory=4096 --disk-size=30g --vm-driver=vmwarefusion and then examine the VM that got created

**Anything else do we need to know**: See attached screen shot
![screen shot 2016-10-14 at 1 18 44 pm](https://cloud.githubusercontent.com/assets/10676530/19401690/96ffd5b2-9211-11e6-8b76-099c5138bc88.png)

**Comment by r2d4** [comment]
Looks like we aren't passing along the disk-size flag to vmwarefusion driver.  Should be an easy fix.  I can take this one 

https://github.com/kubernetes/minikube/blob/05edfeaf65563776501834942ddb41d96d094e78/pkg/minikube/cluster/cluster_darwin.go#L28
