### ISSUE TITLE
docker: stop/delete hung at libmachine: Stopping "[my-profile]"...

### ISSUE THREAD

**Issue by etanshaul** [kubernetes/minikube#6971]
minikube version 1.7.3

`minikube status -p [my-profile] --alsologtostderr -v=1`:
```
root.go:242] Error reading config file at /Users/[]/.minikube/config/config.json: open /Users/[]/.minikube/config/config.json: no such file or directory
```

`minikube stop -p [my-profile]`
```
W0309 21:31:08.535489   66523 root.go:242] Error reading config file at /Users/[]/.minikube/config/config.json: open /Users/[]/.minikube/config/config.json: no such file or directory
✋  Stopping "[my-profile]" in docker ...
I0309 21:31:08.536613   66523 main.go:110] libmachine: Stopping "[my-profile]"...
```

`delete --all --purge` also shows the same error, and hangs. It was working for several command before this but somehow got into this state.

**Comment by tstromberg** [comment]
I don't think the hang here is due to the missing file - it's merely reflecting that minikube no longer has internal state for this VM.

The hang appears to be related to Docker. Restarting Docker would probably fix this, but we clearly need a timeout and better error message for this.

**Comment by tstromberg** [comment]
If you see this again, do you mind sharing the output of: 

* `docker ps`
* `docker inspect minikube`

Thanks!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
