### ISSUE TITLE
kvm: ssh: unable to authenticate -> create host timed out 

### ISSUE THREAD

**Issue by gred7** [kubernetes/minikube#6975]
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>

➜  ~ minikube start                               
😄  minikube v1.8.1 on Ubuntu 18.04
✨  Using the kvm2 driver based on existing profile
💿  Downloading VM boot image ...
⌛  Reconfiguring existing host ...
🏃  Using the running kvm2 "minikube" VM ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [SSH_AUTH_FAILURE] post-start: command runner: ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
💡  Suggestion: Your host is failing to route packets to the minikube VM. If you have VPN software, try turning it off or configuring it so that it does not re-route traffic to the VM IP. If not, check your VM environment routing options.
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/vpn/
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3930
➜  ~ minikube delete
🔥  Deleting "minikube" in kvm2 ...
💀  Removed all traces of the "minikube" cluster.
➜  ~ rm -rf .minikube 
➜  ~ minikube start  
😄  minikube v1.8.1 on Ubuntu 18.04
✨  Automatically selected the kvm2 driver. Other choices: virtualbox, none
💾  Downloading driver docker-machine-driver-kvm2:
    > docker-machine-driver-kvm2.sha256: 65 B / 65 B [-------] 100.00% ? p/s 0s
    > docker-machine-driver-kvm2: 13.88 MiB / 13.88 MiB  100.00% 7.34 MiB p/s 3
💿  Downloading VM boot image ...
    > minikube-v1.8.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.8.0.iso: 173.56 MiB / 173.56 MiB [] 100.00% 11.23 MiB p/s 15s
🔥  Creating kvm2 VM (CPUs=2, Memory=3997MB, Disk=20000MB) ...
💾  Downloading preloaded images tarball for k8s v1.17.3 ...
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 499.26 MiB / 499

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
➜  ~ minikube start
😄  minikube v1.8.1 on Ubuntu 18.04
✨  Using the kvm2 driver based on existing profile
💿  Downloading VM boot image ...
⌛  Reconfiguring existing host ...
🏃  Using the running kvm2 "minikube" VM ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [SSH_AUTH_FAILURE] post-start: command runner: ssh client: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
💡  Suggestion: Your host is failing to route packets to the minikube VM. If you have VPN software, try turning it off or configuring it so that it does not re-route traffic to the VM IP. If not, check your VM environment routing options.
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/vpn/
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3930
➜  ~ minikube delete
🔥  Deleting "minikube" in kvm2 ...
💀  Removed all traces of the "minikube" cluster.
➜  ~ minikube start 
😄  minikube v1.8.1 on Ubuntu 18.04
✨  Automatically selected the kvm2 driver. Other choices: virtualbox, none
💿  Downloading VM boot image ...
🔥  Creating kvm2 VM (CPUs=2, Memory=3997MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

💣  command runner
❌  Error: [SSH_AUTH_FAILURE] getting ssh client for bootstrapper: Error dialing tcp via ssh client: ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
💡  Suggestion: Your host is failing to route packets to the minikube VM. If you have VPN software, try turning it off or configuring it so that it does not re-route traffic to the VM IP. If not, check your VM environment routing options.
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/vpn/
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3930

</details>

**The operating system version**:
Ubuntu 18.04

**Comment by tstromberg** [comment]
Do you mind checking if minikube v1.9.2 fixes this issue?

I believe this may have been related to the randomization issue fixed here:
https://github.com/kubernetes/minikube/pull/7208

**Comment by medyagh** [comment]
Hi @gred7 , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
