### ISSUE TITLE
vt-x check not correct in a ubuntu 16.04 vm

### ISSUE THREAD

**Issue by stanlove101** [kubernetes/minikube#699]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**Minikube version** (use `minikube version`):
0.11.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 desktop in a vm
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Nothing exists in the machines dir
- **Docker version** (e.g. `docker -v`): 1.12.1
- **Install tools**:
- **Others**:

**What happened**:
I am running Windows on my laptop.  I created a new VM in both VMware and Virtualbox (same result in each one).  When I install minikube into the Ubuntu 16.04 desktop and try to start the cluster, it informs me that the VT extensions are not installed.  I verified in the BIOS and via an Intel tool that the VT extensions are installed.  Virtualbox thinks that the vt-x extension is enabled while creating a new VM.  minikube will not start up because it fails the vt-x check.  Attached is a screenshot of the Intel CPU id tool showing that the VT extensions are enabled.
![untitled](https://cloud.githubusercontent.com/assets/9037554/19413215/9eb48e52-92ec-11e6-896c-eeac0e2e7ccb.png)

**What you expected to happen**:
Either work properly or have an option somewhere to disable the check.

**How to reproduce it** (as minimally and precisely as possible):
Find a windows box (win7)
Download Intel CPU tool (http://www.intel.com/support/processors/tools/piu/)
Install your choice  of  VMware or Virtualbox
Install a Ubuntu 16.04 desktop
Install minikube
minikube start
Verify  that minikube fails the VT check

**Anything else do we need to know**:
Very nice work!  Thank you.

**Comment by r2d4** [comment]
You don't need to run minikube in the VM itself.  Minikube will handle provisioning a new VM in virtualbox or VMWare by itself.  

Try downloading the .exe for windows and running it right on your windows machine

https://github.com/kubernetes/minikube/releases/download/v0.11.0/minikube-windows-amd64

**Comment by dlorenc** [comment]
@stanlove101 are you still having trouble?

**Comment by stanlove101** [comment]
I have been ping ponged by various support people.  A high level docker employee said that i had to quit using windows ( ALWAYS A GREAT IDEA BUT I HAVE TO INTERACT WITH NON TECHIES).   I then tried the vm approach to create a ubuntu vm.  No good there either.  I am stuck with having to create a bare metal os to run everything anywhere but my laptop.

Thanks for checking in on me.

Stan



Sent from my Sprint Samsung Galaxy S7.


-------- Original message --------
