### ISSUE TITLE
Do not depend on localkube when released

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#7]

**Comment by dlorenc** [comment]
Can you explain this a little more? What's wrong with using localkube?

**Comment by luxas** [comment]
I think we should have the logic in our own code.
So we have control of both the server and the client.

If localkube wants to donate a draft, it would be a great starting point though

**Comment by vishh** [comment]
cc @mfburnett

**Comment by mfburnett** [comment]
Actually, we're happy to donate all of localkube to this project - from a clean abstraction standpoint, though, I think it makes sense to still maintain it as a separate component, which we're also happy to do.

**Comment by luxas** [comment]
Thanks a lot @mfburnett!

**Comment by vishh** [comment]
I think localkube needs to be tested and released as part of kubernetes release. We should add it to core kubernetes, similar to hyperkube...

**Comment by luxas** [comment]
Works fine for me

**Comment by vishh** [comment]
@luxas @mfburnett Will either of you be able to post a patch to add localkube to core kubernetes?

**Comment by mfburnett** [comment]
@vishh yup, we can do that

**Comment by luxas** [comment]
@mfburnett Ping me and I'll review

**Comment by mfburnett** [comment]
@luxas great, thanks

**Comment by runseb** [comment]
if you guys are interested by an alternative for lib machine provisioning, we used the single node deployment here:

https://github.com/skippbox/kmachine/blob/kmachine/libmachine/provision/generic.go

happy to contribute that.

**Comment by dlorenc** [comment]
We could also move localkube into this repo instead of kubernetes/kubernetes.

**Comment by luxas** [comment]
We thought about that initially, but @vishh said this
> I think localkube needs to be tested and released as part of kubernetes release. We should add it to core kubernetes, similar to hyperkube...

I think I agree

**Comment by vishh** [comment]
I originally thought that we might want to support upgrades to existing
local clusters by updating just the localkube image, pulled from a reliable
source. But @dlorenc mentioned that localkube would be bundled into
minikube, so there is less reason to move localkube to core kubernetes.
Sorry for the confusion..

**Comment by luxas** [comment]
@mfburnett Did you notice that @vishh wants it in this repo now?
Just to make sure you don't work on a PR for main Kubernetes :smile: 

Or what's the final call @vishh?

**Comment by ethernetdan** [comment]
@luxas @vishh starting work on this PR tomorrow evening using this repo as the base unless we decide otherwise.

I do see value in testing localkube with Kubernetes releases so that it's kept closely in-sync with development by immediately surfacing breaking changes.

**Comment by vishh** [comment]
The testing requirements can be met by testing `minikube` against Kubernetes HEAD.

**Comment by dlorenc** [comment]
@ethernetdan Thanks for the help. This repo sounds good for now. I'll be on kubernetes slack all day today so feel free to DM me for help getting this merged.

**Comment by luxas** [comment]
Any update on this getting `localkube` merged into `minikube` @ethernetdan and @mfburnett?

**Comment by ethernetdan** [comment]
Sorry got caught up moving to SF but am finally settled. Sitting down with @dlorenc tomorrow to hash out details. I'll then get something preliminary out and we'll iterate from there.
