### ISSUE TITLE
Update Kubernetes to HEAD

### ISSUE THREAD

**Issue by luxas** [kubernetes/minikube#70]
@dlorenc you mentioned you were working on this.

Good to know, as I just had been thinking about doing it too :)
Assigning that to you then.

**Comment by luxas** [comment]
Or wait... Do we want to update to latest alpha release of Kubernetes instead?

**Comment by ethernetdan** [comment]
Related to #33

**Comment by dlorenc** [comment]
I'm currently stuck on this. My branch is here: https://github.com/dlorenc/minikube/tree/updatek8s

I got godeps to resolve, but I can't build. I get:

# k8s.io/minikube/vendor/github.com/google/cadvisor/container/rkt
vendor/github.com/google/cadvisor/container/rkt/client.go:58: cannot use apisvcConn (type *"k8s.io/minikube/vendor/google.golang.org/grpc".ClientConn) as type *"google.golang.org/grpc".ClientConn in argument to v1alpha.NewPublicAPIClient
# k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/kubelet/rkt
vendor/k8s.io/kubernetes/pkg/kubelet/rkt/rkt.go:194: cannot use apisvcConn (type *"k8s.io/minikube/vendor/google.golang.org/grpc".ClientConn) as type *"google.golang.org/grpc".ClientConn in argument to v1alpha.NewPublicAPIClient

Anyone have any ideas?

**Comment by dlorenc** [comment]
Fixed with #74. We should come up with a repeatable way to do this eventually, but that can come later.
