### ISSUE TITLE
localkube.err should not fill up entire disk

### ISSUE THREAD

**Issue by jezell** [kubernetes/minikube#700]
**Minikube version** (use `minikube version`):
 v0.11.0

**Environment**:
- **OS** (e.g. from /etc/os-release):
  OSX
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
  xhyve
- **Docker version** (e.g. `docker -v`):
  Client:
  Version:      1.12.1
  API version:  1.23
  Go version:   go1.7
  Git commit:   23cf638
  Built:        Thu Aug 18 22:32:50 UTC 2016
  OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64
- **Install tools**:
- **Others**:

**What happened**:
/mnt/sda1/var/lib/localkube/localkube.err grows until it consumes all available disk space

**What you expected to happen**:
limit disk space used by logs to a reasonable amount possibly via log rotation

**How to reproduce it** (as minimally and precisely as possible):
run minikube for a few days

**Anything else do we need to know**:

**Comment by dlorenc** [comment]
Thanks! Yeah, we could set this up using systemd once we fix #571

**Comment by aaron-prindle** [comment]
Closing, Minikube now uses systemd which has built in log rotation
