### ISSUE TITLE
minikube ip not working

### ISSUE THREAD

**Issue by priyasubramanitvr** [kubernetes/minikube#7010]
F:\dockerprograms\simplek8s>minikube ip
*
X Error getting host: open C:\Users\Admin\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by RA489** [comment]
@priyasubramanitvr Thanks for reporting this issue. Can you please provide the following detail to debug
The exact command line used.
Full output of minikube start command
output of minikube logs.

**Comment by priyasubramanitvr** [comment]
C:\Users\Admin>minikube start
* minikube 1.8.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.8.2
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

! minikube v1.7.2 on Microsoft Windows 10 Pro 10.0.17134 Build 17134
* Using the hyperv driver based on user configuration

! 'hyperv' driver reported an issue: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed, but is specified by an existing profile. Please run 'minikube delete' or install hyperv

**Comment by sharifelgamal** [comment]
@priyasubramanitvr I believe this issue is fixed with minikube 1.8.2, could you try it and report back?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
