### ISSUE TITLE
Error starting cluster: init failed. output: "\n** stderr ** \nError: unknown flag: --ignore-preflight-errors\nUsage:\n  kubeadm init

### ISSUE THREAD

**Issue by krajapraveen** [kubernetes/minikube#7018]
I am using Windows 10 PRO
I am using minikube version: v1.8.1
I am using Kubectl version: v1.17.0
I am using docker version: 18.09.2. 
Virtual Box with version 5.2.20 came along with installation of Docker.

When I ran the start the minikube start command like below, I am getting the errors.  PFB.

PS C:\windows\system32> . \minikube.exe start --kubernetes-version="v1.8.1" --vm-driver="virtualbox"
* minikube v1.8.1 on Microsoft Windows 10 Pro 10.0.14393 Build 14393
* Using the virtualbox driver based on user configuration
* Downloading VM boot image ...
* Creating virtualbox VM (CPUs=2, Memory=4063MB, Disk=20000MB) ...
* Found network options:
  - NO_PROXY=192.168.99.100
  - no_proxy=192.168.99.100
E0312 18:06:23.336141    6700 config.go:71] Failed to preload container runtime Docker: getting file asset: Error opening file asset: C:\Users\srikanth.ganji\.minikube\cache\preloaded-tarball/
preloaded-images-k8s-v1-v1.8.1-docker-overlay2.tar.lz4: open C:\Users\srikanth.ganji\.minikube\cache\preloaded-tarball/preloaded-images-k8s-v1-v1.8.1-docker-overlay2.tar.lz4: The system cannot
 find the path specified., falling back to caching images
* Preparing Kubernetes v1.8.1 on Docker 19.03.6 ...
  - env NO_PROXY=192.168.99.100
  - env NO_PROXY=192.168.99.100
* Launching Kubernetes ...
*
X Error starting cluster: init failed. output: "\n** stderr ** \nError: unknown flag: --ignore-preflight-errors\nUsage:\n  kubeadm init [flags]\n\nFlags:\n      --apiserver-advertise-address s
tring      The IP address the API Server will advertise it's listening on. 0.0.0.0 means the default network interface's address.\n      --apiserver-bind-port int32               Port for the
API Server to bind to (default 6443)\n      --apiserver-cert-extra-sans stringSlice   Optional extra altnames to use for the API Server serving cert. Can be both IP addresses and dns names.\n
     --cert-dir string                         The path where to save and store the certificates (default \"/etc/kubernetes/pki\")\n      --config string                           Path to kube
adm config file (WARNING: Usage of a configuration file is experimental)\n      --dry-run                                 Don't apply any changes; just output what would be done\n      --featu
re-gates string                    A set of key=value pairs that describe feature gates for various features. Options are:\nSelfHosting=true|false (ALPHA - default=false)\nStoreCertsInSecrets=
true|false (ALPHA - default=false)\n      --kubernetes-version string               Choose a specific Kubernetes version for the control plane (default \"stable-1.8\")\n      --node-name strin
g                        Specify the node name\n      --pod-network-cidr string                 Specify range of IP addresses for the pod network; if set, the control plane will automatically
allocate CIDRs for every node\n      --service-cidr string                     Use alternative range of IP address for service VIPs (default \"10.96.0.0/12\")\n      --service-dns-domain strin
g               Use alternative domain for services, e.g. \"myorg.internal\" (default \"cluster.local\")\n      --skip-preflight-checks                   Skip preflight checks normally run bef
ore modifying the system\n      --skip-token-print                        Skip printing of the default bootstrap token generated by 'kubeadm init'\n      --token string
    The token to use for establishing bidirectional trust between nodes and masters.\n      --token-ttl duration                      The duration before the bootstrap token is automatically d
eleted. 0 means 'never expires'. (default 24h0m0s)\n\n\n** /stderr **": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.8.1:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml
  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yam
l,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,
Swap,SystemVerification,SystemVerification": Process exited with status 1
stdout:

stderr:
Error: unknown flag: --ignore-preflight-errors
Usage:
  kubeadm init [flags]

Flags:
      --apiserver-advertise-address string      The IP address the API Server will advertise it's listening on. 0.0.0.0 means the default network interface's address.
      --apiserver-bind-port int32               Port for the API Server to bind to (default 6443)
      --apiserver-cert-extra-sans stringSlice   Optional extra altnames to use for the API Server serving cert. Can be both IP addresses and dns names.
      --cert-dir string                         The path where to save and store the certificates (default "/etc/kubernetes/pki")
      --config string                           Path to kubeadm config file (WARNING: Usage of a configuration file is experimental)
      --dry-run                                 Don't apply any changes; just output what would be done
      --feature-gates string                    A set of key=value pairs that describe feature gates for various features. Options are:
SelfHosting=true|false (ALPHA - default=false)
StoreCertsInSecrets=true|false (ALPHA - default=false)
      --kubernetes-version string               Choose a specific Kubernetes version for the control plane (default "stable-1.8")
      --node-name string                        Specify the node name
      --pod-network-cidr string                 Specify range of IP addresses for the pod network; if set, the control plane will automatically allocate CIDRs for every node
      --service-cidr string                     Use alternative range of IP address for service VIPs (default "10.96.0.0/12")
      --service-dns-domain string               Use alternative domain for services, e.g. "myorg.internal" (default "cluster.local")
      --skip-preflight-checks                   Skip preflight checks normally run before modifying the system
      --skip-token-print                        Skip printing of the default bootstrap token generated by 'kubeadm init'
      --token string                            The token to use for establishing bidirectional trust between nodes and masters.
      --token-ttl duration                      The duration before the bootstrap token is automatically deleted. 0 means 'never expires'. (default 24h0m0s)
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
* Problems detected in kubelet:
  - Mar 12 12:37:14 minikube kubelet[3085]: unknown flag: --config
  - Mar 12 12:37:15 minikube kubelet[3128]: unknown flag: --config

Can you please suggest me regarding what am I doing wrong and where am I doing wrong ???

![1](https://user-images.githubusercontent.com/44344982/76524506-31b16900-6490-11ea-8a8b-448cde9ff389.JPG)
![2](https://user-images.githubusercontent.com/44344982/76524512-3413c300-6490-11ea-8160-70949a1f2e4f.JPG)

**Comment by afbjorklund** [comment]
Kubernetes 1.8.1 is too old, the oldest reasonable is 1.10. Did you mean **minikube** 1.17.3 ?

**Comment by afbjorklund** [comment]
Shows a different result here:

``` console
$ minikube start --kubernetes-version="v1.8.1" --vm-driver="virtualbox"
😄  minikube v1.8.1 on Ubuntu 16.04
✨  Using the virtualbox driver based on existing profile
⚠️  Specified Kubernetes version 1.8.1 is less than the oldest supported version: v1.11.10
💣  Sorry, Kubernetes 1.8.1 is not supported by this release of minikube

```

**Comment by krajapraveen** [comment]
Hi afbjorklund

I mean that I am using Minikube with version 1.8.1 .

I will use Kubernetes (kubectl) version 1.17.3 as you said and will try to execute. Once done, I will get back to you.

**Comment by afbjorklund** [comment]
@krajapraveen : I was able to reproduce the problem, seems like the error is not displayed properly when starting a new cluster. It's still not possible to run such old versions, but solution message was buggy (will post a PR for that - the output looks very similar to what I got, for an existing machine)

**Comment by krajapraveen** [comment]
@afbjorklund : I have used Kubernetes (Kubectl) version 1.17.3 and it worked. 

Thank You..
