### ISSUE TITLE
proxy: Error downloading checksum file: connectex: Uma tentativa de conexão falhou porque o componente conectado não respondeu

### ISSUE THREAD

**Issue by danccosta** [kubernetes/minikube#7025]
Não consigo iniciar o Minikube (v1.8.0) em uma máquina corporativa que está atrás de um proxy de internet. Já tentei usar o cntlm, mas sem sucesso.

**Os comandos necessários para reproduzir o problema**:
 minikube start --vm-driver="hyperv" --docker-env HTTP_PROXY=http://proxy-xxx.com.br:3128 --docker-env HTTPS_PROXY=http://proxy-xxx.com.br:3128

**A saída completa do comando que apresentou falha**: <details>
! minikube v1.8.1 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* Using the hyperv driver based on user configuration
* Downloading VM boot image ...
E0313 11:35:51.798773   18956 iso.go:88] Unable to download https://storage.googleapis.com/minikube/iso/minikube-v1.8.0.iso: https://storage.googleapis.com/minikube/iso/minikube-v1.8.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.8.0.iso.sha256: dial tcp 172.217.28.240:443: connectex: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu.
E0313 11:36:33.889176   18956 iso.go:88] Unable to download https://github.com/kubernetes/minikube/releases/download/v1.8.0/minikube-v1.8.0.iso: https://github.com/kubernetes/minikube/releases/download/v1.8.0/minikube-v1.8.0.iso: invalid checksum: Error downloading checksum file: Get https://github.com/kubernetes/minikube/releases/download/v1.8.0/minikube-v1.8.0.iso.sha256: dial tcp 18.231.5.6:443: connectex: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu.
E0313 11:37:16.114063   18956 iso.go:88] Unable to download https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.8.0.iso: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.8.0.iso: invalid checksum: Error downloading checksum file: Get https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.8.0.iso.sha256: dial tcp 47.110.177.93:443: connectex: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu.
*
X Failed to cache ISO: unable to cache ISO:
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.8.0.iso: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.8.0.iso: invalid checksum: Error downloading checksum file: Get https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.8.0.iso.sha256: dial tcp 47.110.177.93:443: connectex: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu.
  https://storage.googleapis.com/minikube/iso/minikube-v1.8.0.iso: https://storage.googleapis.com/minikube/iso/minikube-v1.8.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.8.0.iso.sha256: dial tcp 172.217.28.240:443: connectex: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu.
  https://github.com/kubernetes/minikube/releases/download/v1.8.0/minikube-v1.8.0.iso: https://github.com/kubernetes/minikube/releases/download/v1.8.0/minikube-v1.8.0.iso: invalid checksum: Error downloading checksum file: Get https://github.com/kubernetes/minikube/releases/download/v1.8.0/minikube-v1.8.0.iso.sha256: dial tcp 18.231.5.6:443: connectex: Uma tentativa de conexão falhou porque o componente conectado não respondeu
corretamente após um período de tempo ou a conexão estabelecida falhou
porque o host conectado não respondeu.

*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**A saída do comando `minikube logs`**:<details>
X Error getting config: cluster "minikube" does not exist

</details>

**A versão do sistema operacional usado**:
Windows 10 Pro

**Comment by tstromberg** [comment]
Instead of setting `--docker-env`, you'll need to set the HTTP_PROXY and HTTPS_PROXY environment variables: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

Please let me know if this helps.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
