### ISSUE TITLE
document work around for VirtualBox networking be slow

### ISSUE THREAD

**Issue by jgoeres** [kubernetes/minikube#7031]
Hi,
we are using minikube to deploy local test installations of our stack, in particular for developers. In general, we are using the virtual box hypervisor (yes, even on win 10 machines, for *reasons* ;-)).

We note a general sluggishness of the minikube environment, even when running on very powerful host machines to which we assign lots of cores (<< #physical cores on the host, naturally) and RAM to the minikube VM with the "minikube start" command.
We are still in the early phase of pinpointing the bottlenecks, but one observation that we already made is that network performance seems to be a problem and it seems unrelated to our own software, because we can also observe it when doing something trivial like a docker build:

When building one of our images where we download a number of larger artifacts from our artifact repo (Nexus), the build takes ~8 secs on the Docker Toolbox "default" VM. The same build, on the same host machine, takes almost a minute on the minikube VM (which BTW has 6 cores vs. 2 for the docker toolbox VM). The main difference comes from all operations in our RUN commands that involve the network. For example, the download of a ~90MB artifact with curl command reaches ~70MB/s on Docker Toolbox, while it barely reaches 2,5MB/s with the minikube VM. 
The issue is the same when putting a number of large files into the Docker build context and letting Docker upload them.

Is this a known issue? Any ideas where to start looking?

JG

**Comment by afbjorklund** [comment]
Can you compare with earlier versions of the ISO image perhaps?

**Comment by jgoeres** [comment]
We are observing this across different machines with different versions of the minikube CLI and the ISO, but I will give this a try.
How can I find out the version of the ISO I currently have installed? A quick look into the output of "minikube logs" didn't yield an ISO version.
Do you expect that the version of the minikube CLI makes a difference (after all it is what creates the VM)?

**Comment by afbjorklund** [comment]
I was wondering if there had been a regression, but it seems you are mostly comparing it to docker-machine (boot2docker) on the same VirtualBox ?

Some version numbers and such would be nice, but otherwise I guess that is a start in order to compare. There was another bug too, saying that HyperKit was much faster now

**Comment by afbjorklund** [comment]
Will also have to compare the virtual network cards (vNIC) used, if there is a difference perhaps ?

**Comment by afbjorklund** [comment]
The only difference that I can see is that minikube is using virtio:

_default_
```
NIC 1:           MAC: 0800278DBA12, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 40906, guest ip = , guest port = 22
NIC 2:           MAC: 080027A3BA6B, Attachment: Host-only Interface 'vboxnet0', Cable connected: on, Trace: off (file: none), Type: 82540EM, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
```

_minikube_
```
NIC 1:           MAC: 080027A2BCCA, Attachment: NAT, Cable connected: on, Trace: off (file: none), Type: virtio, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
NIC 1 Settings:  MTU: 0, Socket (send: 64, receive: 64), TCP Window (send:64, receive: 64)
NIC 1 Rule(0):   name = ssh, protocol = tcp, host ip = 127.0.0.1, host port = 46754, guest ip = , guest port = 22
NIC 2:           MAC: 08002775A2C5, Attachment: Host-only Interface 'vboxnet0', Cable connected: on, Trace: off (file: none), Type: virtio, Reported speed: 0 Mbps, Boot priority: 0, Promisc Policy: deny, Bandwidth group: none
```

Which seems to be following the guidelines: 
> Here is a short summary of things to check in order to improve network performance:
> 
> Whenever possible use the virtio network adapter. Otherwise, use one of the Intel PRO/1000 adapters.

https://www.virtualbox.org/manual/ch06.html#network_performance

**Comment by afbjorklund** [comment]
Couldn't see any major difference from a local docker build with a large file in it, though

184M	minikube.iso

real	0m3.428s

real	0m3.232s

**Comment by afbjorklund** [comment]
@jgoeres : looking through the boot2docker history, there seems to be an issue with VirtualBox and running multiple vCPU with virtio and the Intel network cards... https://www.virtualbox.org/ticket/10157

Since minikube (kubeadm) requires at least 2 CPU, can you try changing the Network type ? Either by disabling virtio or by selecting AMD PCNet FAST III, I think you can do this through VirtualBox GUI

**Comment by afbjorklund** [comment]
``` 
minikube start --vm-driver=virtualbox --nat-nic-type=Am79C973 --host-only-nic-type=Am79C973
```

**Comment by jgoeres** [comment]
Thank you,  I will give this a try... alas; i now currently have some trouble getting minikube to start successfully.

The first thing I noticed: with my ancient minikube version, I had been using the option 

    --host-only-cidr='192.168.99.1/24' 

which now gives me 

    X Unable to start VM. Please investigate and run 'minikube delete' if possible: driver start: Error setting up host only network on machine start: invalid CIDR address: '192.168.99.1/24'

with both 1.8.1 and 1.8.2.

After leaving out this setting, I still  have various other problems.... under normal circumstances I would reboot the machine, but alas, we are currently confined to permanent home office and the machine is in the office - it might not come up (pre boot authentication for drive encryption etc.).

**Comment by jgoeres** [comment]
Hi,

minikube is running again, and with the changed NIC types, download speed is now on the same level as the Docker Toolbox VM, thank you very much.
Should I find a dedicated issue for the no longer working 

    --host-only-cidr='192.168.99.1/24' 

option? I added it a while ago when I had problems with the Minikube VM getting an IP in the right host-only network, but this time it worked just fine without it.

Regards
J

**Comment by jgoeres** [comment]
Sorry, should have left this open, I think you might want to change the default NIC type in code?

**Comment by afbjorklund** [comment]
Yes, please open separate issue about CIDR

**Comment by jgoeres** [comment]
https://github.com/kubernetes/minikube/issues/7063

**Comment by tstromberg** [comment]
FWIW, there is likely little we can do on the minikube side about slow VirtualBox networking, other than suggest workarounds.

**Comment by jgoeres** [comment]
I guess making the alternative NIC types suggested in the workaround the new default could help - it works really well for me, but of course I cannot judge on the side effects it might have for others. So if this is considered too risky, how about adding some remark in the docs and close this?

**Comment by medyagh** [comment]
> I guess making the alternative NIC types suggested in the workaround the new default could help - it works really well for me, but of course I cannot judge on the side effects it might have for others. So if this is considered too risky, how about adding some remark in the docs and close this?

we should add this to our docs, in minikube site 
I would be happy to review a PR that adds this to troubleshooting or hints section for virtualbox driver docs here https://minikube.sigs.k8s.io/docs/drivers/virtualbox/

**Comment by Aut0R3V** [comment]
I would like to work on this issue. @afbjorklund anything I can do ?

**Comment by priyawadhwa** [comment]
Hey @afbjorklund are you still working on this?

**Comment by afbjorklund** [comment]
No, I haven't done any PR for this

**Comment by skoenig** [comment]
Since I have also encountered this problem and have only found the workaround here, I would like to include the hint in the documentation.
