### ISSUE TITLE
Minikube windows installer replaces Windows system PATH environment variable

### ISSUE THREAD

**Issue by rodcloutier** [kubernetes/minikube#704]
BUG REPORT

**Minikube version** v0.11.0

**Environment**:
- **OS** Windows 7
- **VM Driver** n/a
- **Docker version** Docker version 1.11.1, build 5604cbe
- **Install tools**:
- **Others**:

**What happened**:
Windows installer replaced the system PATH environment variable with the minikube path. All installed applications cannot run anymore.

**What you expected to happen**:
Expected the minikube executable path to only be appended to the system PATH.

**How to reproduce it** (as minimally and precisely as possible):
Use the installer to install a fresh minikube

**Anything else do we need to know**:
This is a major bug that can be quite catastrophic for some users.

**Comment by ereOn** [comment]
I can confirm I had that too. Completely emptied my `PATH` with no possibility for easy backup.

Tools like `where` would not even work anymore.

**Comment by aaron-prindle** [comment]
I am very sorry about this, I believe it is related to this bug:
http://stackoverflow.com/questions/21897103/nsis-envvarupdate-overwrites-system-path-when-path-is-too-long-is-there-a-wor

I have pulled the windows installer from the release page and will work on a workaround in the meantime.  Again sorry for for the trouble this has caused.

**Comment by ereOn** [comment]
@aaron-prindle No big deal.

Gave me the opportunity to clean it up (there were too many things in there anyway) ;)

Perhaps it would be worth considering removing the installer from the release page for now ? People still have access to the naked binary.

**Comment by aaron-prindle** [comment]
I have removed it from the release page for now. Thank you very much for
reporting this and I will try to work on resolving the issue in the
meantime.
