### ISSUE TITLE
want some options that docker-machine bootstrap use ...

### ISSUE THREAD

**Issue by nengbowan** [kubernetes/minikube#7047]
today , i met a question , core componet in minikube can not be work , because of out of memory  , so i deleted all pods , now , i want to know the default cpu  , and memory and other options that docker-machine create minikube use ,thanks

**Comment by afbjorklund** [comment]
I think you mean "minikube start" rather than "docker-machine bootstrap", but anyway. You have some different options when creating the VM, including the number of CPU and the amount of RAM etc:

```
      --cpus=2: Number of CPUs allocated to Kubernetes.
      --memory='': Amount of RAM to allocate to Kubernetes (format: <number>[<unit>], where unit = b, k, m or g).
      --disk-size='20000mb': Disk size allocated to the minikube VM (format: <number>[<unit>], where unit = b, k, m or g).
```

The default is 2 CPU, 2200M RAM, and 20000M disk image.
