### ISSUE TITLE
! 'vmware' driver reported an issue: exec: "docker-machine-driver-vmware": executable file not found in $PATH

### ISSUE THREAD

**Issue by ghorpade84** [kubernetes/minikube#7059]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
Did you install the vmware driver?

https://minikube.sigs.k8s.io/docs/start/macos/

If so, please report the output of `docker-machine-driver-vmware version`. Thank you!

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Comment by atulsharma2000** [comment]
having the same issue, already downloaded docker-machine-driver-vmware.exe.
