### ISSUE TITLE
xhyve: vritio-net not "NATted" on host

### ISSUE THREAD

**Issue by sbadia** [kubernetes/minikube#706]
**BUG REPORT**

**Minikube version** (use `minikube version`):
`v0.11.0`

**Environment**:
- **OS** : `Mac OS X Yosemite (10.10.5)`
- **VM Driver** : `xhyve`
- **Docker version** (e.g. `docker -v`): `1.12.1, build 6f9534c`

**What happened**:
I've noticed that using `minikube` + `xhyve` and the default network driver (`virtio-net`), packets from container are not properly "NATed".

**What you expected to happen**:

`minikube` shoud add a pf rule in order to properly manage outgoing packets.

**How to reproduce it** (as minimally and precisely as possible):
1. start minikube
2. apply or create a deployment, go into the container and try to ping something on the outside world
3. tcpdump on the host (mac)

**Anything else do we need to know**:

In my case, I use a VPN for accessing some others resources, (the VPN create a `utun0` iface), I used this pf rule in order to properly NAT outgoing minikube traffic.

```
echo "nat on {utun0} proto {tcp, udp, icmp} from 192.168.64.0/24 to any -> {utun0}"  | sudo pfctl -a com.apple/utun0nat -f -
```

**Comment by sbadia** [comment]
Possible related issue: https://github.com/mist64/xhyve/issues/84#issuecomment-219497807 (but xhyve side).

**Comment by zchee** [comment]
@sbadia @r2d4 I'll debug it. thanks issue report.

**Comment by dlorenc** [comment]
Closing. I don't think this is still an issue.
