### ISSUE TITLE
kubectl apply: error validating data: kind not set

### ISSUE THREAD

**Issue by priyasubramanitvr** [kubernetes/minikube#7060]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>
kubectl apply -f client-node-port.yaml
error: error validating "client-node-port.yaml": error validating data: kind not set; if you choose to ignore these errors, turn validation off with --validate=false

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by RA489** [comment]
@priyasubramanitvr could you please provide
The exact command-lines used, so that we may replicate the issue
The full output of the command that failed
The full output of the "minikube logs" command
Which operating system version was used

**Comment by tstromberg** [comment]
This appears to be a bug with an invalid YAML input.file.

Feel free to post the file here, but I think you'll find that there is a missing `kind:` section in it.

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!
