### ISSUE TITLE
Support backward compatibility for old profiles

### ISSUE THREAD

**Issue by eashi** [kubernetes/minikube#7062]
I have installed the latest minikube version v1.8.1 (I can't remember the previous version), but then all my clusters wouldn't work because their profiles became invalid.

I checked the code that reads the configuration from the profile and obviously the structure of the profile has changed. 

I suggest to keep the profiles backward compatible as far back as possible, and display warnings about attributes that will be changed in the profile rather than prompting the users to delete the profile. 

If you feel that's the right way I can start with putting back some of the renamed attributes?

**The exact command to reproduce the issue**:
`minikube profile list`

**The full output of the command that failed**:<details>

⚠️  Found 4 invalid profile(s) !
	 keda-external-scaler
	 minikube
	 twitch-keda
	 twitter-scaler
💡  You can delete them using the following command(s):
	 $ minikube delete -p keda-external-scaler
	 $ minikube delete -p minikube
	 $ minikube delete -p twitch-keda
	 $ minikube delete -p twitter-scaler

</details>

**The operating system version**:
MacOS Catalina

**Comment by afbjorklund** [comment]
Possibly related to #6969 (not sure if it is enough)

**Comment by eashi** [comment]
Thanks a lot @afbjorklund for the prompt reply.

I think the PR you mentioned took it to a good position, but I still get invalid profile due to the attribute "Driver" instead for "VMDriver". This is where it fails: 

https://github.com/kubernetes/minikube/blob/82900a7811e479755e03ae020ebb44152dfd93d8/pkg/minikube/config/profile.go#L43

**Comment by afbjorklund** [comment]
So related to #6620 - @sharifelgamal  ?

**Comment by sharifelgamal** [comment]
Yep, that accidentally broke the profiles list command. It's fixable.

**Comment by eashi** [comment]
I have been thinking about this, I think we can solve this elegantly by creating a mapping between a released version (in which the config format is changed) and a corresponding function to load the profile and translate it to the latest version.

Once the user wants to load a profile, the loader would try each mapping starting from the latest version until the earliest version we want to support, and we provide a message output as well (maybe a string property in the Profile we call `stateMessage`). The message would be like: "_It seems that your profile is old, please update your profile manually, we are translating it for you this time :)_"

I wrote about my experience about older profile here in case it helps with this issue: https://www.emadashi.com/2020/03/how-to-fix-minikube-invalid-profile/

This will require some work, but would much better experience. If there is enough pain out there it might be worth it.

**Comment by eashi** [comment]
I can take the first stab implementing this if you folks like the idea.

**Comment by sharifelgamal** [comment]
I like the idea of automatically translating from the old profile format to the new one, I would hope that we wouldn't change the format so often that need to formally version each release, but I would be happy to review a PR to fix this.

**Comment by priyawadhwa** [comment]
Hey @eashi -- are you still working on this?

**Comment by eashi** [comment]
Hey @priyawadhwa , I have created a draf PR to consult with the maintainers if this is a direction they are comfortable with. I didn't receive any comments on the PR and I didn't want spend time on it without the guidance.

I would love to come back to it and work on it more, but I need the feedback above :).

**Comment by priyawadhwa** [comment]
Hey @eashi thank you! I didn't notice the draft PR -- I just opened up the PR to give it some visibility. I'll try to take a look at it in the next couple days.

**Comment by tstromberg** [comment]
Fixed in v1.12.
