### ISSUE TITLE
none start: cluster "minikube" does not exist

### ISSUE THREAD

**Issue by mw-poly** [kubernetes/minikube#7066]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

* The exact command which showed this error message
*  The exact `minikube start` command line used
* The full output of both commands

Thank you for sharing your experience!

**Comment by YannikSc** [comment]
Having the same issue. The `minikube logs` command just outputs more or less the same error message.
- Running on Archlinux
- Installed minikube via pacman, version 1.8.2-1
- Run `sudo minikube --driver=none start`

<details>
<summary>Issuing `minikube status` outputs</summary>

    💣  getting config: cluster "minikube" does not exist
    
    😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
    👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

<details>
<summary>`minikube logs`</summary>

    💣  Error getting config: cluster "minikube" does not exist
    
    😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
    👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**Comment by medyagh** [comment]
@YannikSc do you mind trying
sudo minikube delete
sudo minikube --driver=none --alsologtostderr -v8

and paste the output of the above command ?


alternatively i am curious, have you tried our newst docker driver ? that has better perforamnce and stalibty on linux ?

minikube start --driver=docker ?

**Comment by YannikSc** [comment]
Well .. surprisingly the delete command worked ..
the second minikube command failed with the error "unknown flag --driver" so I assumed, you mean `sudo minikube start  [...]` which results in an error:

<details>
<summary>`sudo minikube start --driver=none --alsologtostderr -v8`</summary>

    I0418 01:16:24.885531  223439 notify.go:125] Checking for updates...
    I0418 01:16:25.142499  223439 start.go:262] hostinfo: {"hostname":"LinuxGaming","uptime":27029,"bootTime":1587138356,"procs":537,"os":"linux","platform":"arch","platformFamily":"arch","platformVersion":"rolling","kernelVersion":"5.6.3-arch1-1","virtualizationSystem":"kvm","virtualizationRole":"host","hostid":"9420ab20-2599-11e7-b654-6045cb9e93f4"}
    I0418 01:16:25.143930  223439 start.go:272] virtualization: kvm host
    😄  minikube v1.9.2 on Arch rolling
    I0418 01:16:25.144083  223439 driver.go:245] Setting default libvirt URI to qemu:///system
    ✨  Using the none driver based on user configuration
    I0418 01:16:25.144197  223439 start.go:310] selected driver: none
    I0418 01:16:25.144218  223439 start.go:656] validating driver "none" against <nil>
    I0418 01:16:25.144235  223439 start.go:662] status for none: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
    💣  Sorry, Kubernetes v1.18.0 requires conntrack to be installed in root's path
</details>

However the start with the docker driver seems to work. I runs successfully and I can use the kubectl command and run stuff. I also can stop it again with the minikube stop command so it seems fixed (or clarified) for me.

**Comment by medyagh** [comment]
@YannikSc glad to see your problem was fixed,

by the way for none driver, you need to install Sorry "conntrack" it is required by kuberentes.
but for docker driver u dont need it

I will close this, please feel free to reopen
