### ISSUE TITLE
Add --vm flag for users who want to autoselect only VM's

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7067]
Some users may need to use kernel modules.

**Comment by tstromberg** [comment]
Just in case someone else has time to address this, here is where I would start:

* Add "vm" boolean flag here: https://github.com/kubernetes/minikube/blob/82900a7811e479755e03ae020ebb44152dfd93d8/cmd/minikube/cmd/start.go#L196

* Add option to `driver.Choices` function to filter for drivers which `IsVM()` is true:  https://github.com/kubernetes/minikube/blob/82900a7811e479755e03ae020ebb44152dfd93d8/pkg/minikube/driver/driver.go#L167

**Comment by prasadkatti** [comment]
Hi. I would like to work on this issue.

**Comment by prasadkatti** [comment]
Looks like there is a PR out already. I will unassign myself.
