### ISSUE TITLE
virtualbox: AMD-V is disabled in the BIOS (or by the host OS)

### ISSUE THREAD

**Issue by SamarGooda** [kubernetes/minikube#7074]
**The exact command to reproduce the issue**:
minikube start --driver=virtualbox

**The full output of the command that failed**:<details>
😄  minikube v1.8.2 on Fedora 31
✨  Using the virtualbox driver based on user configuration
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: AMD-V is disabled in the BIOS (or by the host OS) (VERR_SVM_DISABLED)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.666308 Power up failed (vrc=VERR_SVM_DISABLED, rc=NS_ERROR_FAILURE (0X80004005))

</details>

**The output of the `minikube logs` command**:<details>

💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

</details>

**The operating system version**:
fedora 31

**Comment by runlevel5** [comment]
@SamarGooda would you run into the same error after AMD-V is enabled in the BIOS?

**Comment by priyawadhwa** [comment]
Hey @SamarGooda -- any update here?
