### ISSUE TITLE
The "virtualbox" driver should not be used with root privileges

### ISSUE THREAD

**Issue by zhsh16** [kubernetes/minikube#7083]
`minikube start --driver=virtualbox` while I start the minikube on centos7 it throws the info,I know maybe the priveleges on stating virtualbox ,but I don't know how to change the virtualbox priveleges.pls help ,thanks

**Comment by tstromberg** [comment]
Login to the Linux machine as a non-root user and minikube should work. If it does not, please share the error message.

In the unlikely case that it is not possible to login as a non-root user, you may be able to bypass this check by adding the `--force` flag.

**Comment by zhsh16** [comment]
> Login to the Linux machine as a non-root user and minikube should work. If it does not, please share the error message.
> 
> In the unlikely case that it is not possible to login as a non-root user, you may be able to bypass this check by adding the `--force` flag.
> 
> Please let me know which solution or further error message you end up with.

Thank you for your help. I was in a hurry the day before yesterday, so I changed the implementation method and used docker for desktop to implement kubenetes. I will try your solution when I have time.Thanks again !

**Comment by Alhuzsyam** [comment]
when I use minikube start --force, I get the same error
