### ISSUE TITLE
TestDownloadOnly/group/v1.17.3  failing: expected image file exist at...

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7085]
I think this is related to preload. Do you mind taking a look, @priyawadhwa ?

This test may be need to be updated to check for preloadable versions differently than others.

**Comment by priyawadhwa** [comment]
Yah, I think this is failing because we use preload for VMs as well now, so we don't download the images for v1.17.3 anymore

I'll change it to an unsupported version
