### ISSUE TITLE
docker-env with crio: Error getting service status: Process exited with status 3

### ISSUE THREAD

**Issue by cwansart** [kubernetes/minikube#7111]
**The exact command to reproduce the issue**:

Make sure you're running Docker on Mac and run in a terminal:

```bash
$ minikube start --cpus=4 --memory=4g --container-runtime=cri-o --vm-driver=virtualbox
$ minikube docker-env
```

I guess it is due to the use of VirtualBox? With hyperkit _docker-env_ works, but hyperkit has some issues with the network.

**The full output of the command that failed**:<details>

```
$ minikube docker-env

💣  Error getting service status: Process exited with status 3

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```
</details>

**The output of the `minikube logs` command**:

There is none regarding this issue.

**The operating system version**:

macOS 10.14.6
Docker 19.03.8
minikube 1.8.2
VirtualBox 6.0.18

**Comment by tstromberg** [comment]
This should definitely work. Let me try to reproduce it locally.

**Comment by tstromberg** [comment]
Oh, I know why it doesn't work: `--docker-env` only works with `--container-runtime=docker` (the default). Let me see what I can do about improving the error message.

**Comment by cwansart** [comment]
That makes sense. Guess I missed that. Thank you

**Comment by tstromberg** [comment]
If it helps, there is also `minikube podman-env`, which may work better for the CRIO case.

**Comment by cwansart** [comment]
Oh, good to know. But so far podman didn't work that great on macOS. I'll check it out. :)

**Comment by afbjorklund** [comment]
Sounds like a regression then, it used to give a nice and friendly error message... See ~#3698~

Running `podman-remote` from the Mac is supposed to work fine, let us know if it doesn't ?

**Comment by cwansart** [comment]
Thank you. I'll do.
