### ISSUE TITLE
Update commands to detect non-existent configuration

### ISSUE THREAD

**Issue by zhangfeifeifei** [kubernetes/minikube#7128]
**minikube stop**：

*** 
X Error getting cluster config: cluster "minikube" does not exist
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by tstromberg** [comment]
Thank you for the bug report! The issue is because there is no cluster to be found. I'll use this issue to track updating our commands to give better output.
