### ISSUE TITLE
None driver tests on GitHub actions: connect: connection refused

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7142]
None driver used to have only one failure (test.download only)
Now we have Lots of failures of none driver tests on head in GitHub actions.
I believe last time I saw them was on multi node pr

'''
 The End Result - None on Ubuntu 18:040s
*** 21 Failed ***
Run echo ${GOPOGH_RESULT}
None_Ubuntu_18_04 : completed with 21 / 59 failures in 43 min 22 seconds
----------------21 Failures----------------------------
[
  "TestDownloadOnly/docker/v1.18.0-rc.1",
  "TestDownloadOnly/docker/v1.18.0-rc.1#01",
  "TestOffline/group/docker",
  "TestAddons",
  "TestFunctional/serial/StartWithProxy",
  "TestFunctional/serial/KubectlGetPods",
  "TestFunctional/serial/MinikubeKubectlCmd",
  "TestFunctional/parallel/ComponentHealth",
  "TestFunctional/parallel/DashboardCmd",
  "TestFunctional/parallel/DNS",
  "TestFunctional/parallel/StatusCmd",
  "TestFunctional/parallel/LogsCmd",
  "TestFunctional/parallel/ServiceCmd",
  "TestFunctional/parallel/PersistentVolumeClaim",
  "TestFunctional/parallel/TunnelCmd",
  "TestFunctional/parallel/MySQL",
  "TestFunctional/parallel/DockerEnv",
  "TestFunctional/parallel/NodeLabels",
  "TestChangeNoneUser",
  "TestStartStop/group/old-docker",
  "TestVersionUpgrade"
]
'''

**Comment by medyagh** [comment]
CC: @sharifelgamal  could this be related to multi node PR?

**Comment by sharifelgamal** [comment]
I don't think so but I'll double check

**Comment by medyagh** [comment]
from None test logs
```
TestFunctional/parallel/ServiceCmd: helpers.go:264: TestFunctional/parallel/ServiceCmd: WARNING: pod list for "default" "app=hello-node" returned: Get "https://10.1.0.4:8443/api/v1/namespaces/default/pods?labelSelector=app%3Dhello-node": dial tcp 10.1.0.4:8443: connect: connection refused
```

**Comment by medyagh** [comment]
this seems to be related to https://github.com/kubernetes/minikube/issues/7169

**Comment by sharifelgamal** [comment]
none tests are not in good shape thanks to #7141 and #7180
