### ISSUE TITLE
kube-proxy: Post https://localhost:8443/api/v1/namespaces/kube-system/configmaps?timeout=10s: context deadline exceeded

### ISSUE THREAD

**Issue by stevenbill** [kubernetes/minikube#7146]
Error starting cluster: addon phase cmd:"/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml\"": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1
stdout:
[addons]: Migrating CoreDNS Corefile
[addons] Applied essential addon: CoreDNS

stderr:
W0322 15:49:32.072444    6774 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0322 15:49:32.073690    6774 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0322 15:49:32.077121    6774 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0322 15:49:32.077173    6774 validation.go:28] Cannot validate kubelet config - no validator is available
error execution phase addon/kube-proxy: unable to create configmap: Post https://localhost:8443/api/v1/namespaces/kube-system/configmaps?timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
To see the stack trace of this error execute with --v=5 or higher

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-addon-manager ["73369a71aa30"]:
    error: no matches for kind "Job" in version "batch/v1"

**Comment by priyawadhwa** [comment]
Hey @stevenbill, I see this log:

```
Problems detected in kube-addon-manager ["73369a71aa30"]:
error: no matches for kind "Job" in version "batch/v1"
```

we removed the addon manager a few releases ago. What version of minikube are you running? If it's lower than 1.9, could you try upgrading and see if that resolves this issue?

**Comment by stevenbill** [comment]
thank you
