### ISSUE TITLE
Unable to connect to the server: unexpected EOF

### ISSUE THREAD

**Issue by stevenbill** [kubernetes/minikube#7147]
suddenly my minikube show this error and stopped to start

**Comment by priyawadhwa** [comment]
Hey @stevenbill I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

 * The full output of `minikube logs`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by stevenbill** [comment]
thank you
