### ISSUE TITLE
Opening service default/holding-details in default browser. Access is denied.X open url failed: http://192.168.99.101:31555: exit status 1

### ISSUE THREAD

**Issue by krajapraveen** [kubernetes/minikube#7155]
Hi

When I have provided the following command:
C:\>kubectl get services

NAME                  TYPE            CLUSTER-IP    EXTERNAL-IP    PORT(S)                   AGE
holding-details    NodePort     10.96.38.81    <none>            8080:31555/TCP      25s
kubernetes          ClusterIP       10.96.0.1        <none>           443/TCP                   2d22h
```
C:\>minikube.exe service holding-details
|-----------|-----------------|-------------|-----------------------------|
| NAMESPACE |      NAME       | TARGET PORT |             URL             |
|-----------|-----------------|-------------|-----------------------------|
| default   | holding-details |             | http://192.168.99.101:31555 |
|-----------|-----------------|-------------|-----------------------------|
* Opening service default/holding-details in default browser...
Access is denied.
*
X open url failed: http://192.168.99.101:31555: exit status 1
```
From the above, the system is saying that Application is not found at: http://192.168.99.101:31555

And also when I tried to open the application at http://192.168.99.101:8080/holdings/swagger-ui.html , its not opening.

Can you please help me here.

PFA screenshot for your reference.

![minikube issue](https://user-images.githubusercontent.com/44344982/77292919-4222d880-6d07-11ea-8ddc-0bf6963410f2.JPG)

**Comment by tstromberg** [comment]
This appears to be a system misconfiguration issue.  I took a look at https://github.com/pkg/browser/blob/master/browser_windows.go and saw how it opened a new web page, and it should definitely work on a properly configured system:

`https://github.com/pkg/browser/blob/0a3d74bf9ce488f035cf5bc36f753a711bc74334/browser_windows.go#L11`

Just to verify, can you try running:

`start http://www.google.com/`

**Comment by sharifelgamal** [comment]
Any update @krajapraveen?

**Comment by medyagh** [comment]
Hi @krajapraveen, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

have you had a chance to try thomas's suggestion to see if the "start google.com" command works in your powershell ?

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
