### ISSUE TITLE
vbox: create host timed out in 120.000000 seconds

### ISSUE THREAD

**Issue by gokulsood** [kubernetes/minikube#7159]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

PS C:\WINDOWS\system32> minikube start --vm-driver=virtualbox
* minikube v1.8.2 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
* Using the virtualbox driver based on existing profile

! 'virtualbox' driver reported an issue: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostinfo failed:

* Suggestion: Install the latest version of VirtualBox
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32>

</details>

**The output of the `minikube logs` command**:<details>

PS C:\WINDOWS\system32> minikube logs
*
X command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32>

</details>

Windows 10

**Comment by priyawadhwa** [comment]
Hey @gokulsood, what version of VirtualBox are you running?

If possible, could you try upgrading to the latest version of VirtualBox, and see if that resolves the issue?

**Comment by tstromberg** [comment]
I think this may have been fixed in minikube v1.9, but you'll need to run `minikube delete` first.

Any chance you have a VPN running?

**Comment by mudasar187** [comment]
I also face the same issue. Minikube version: v1.9.2 , Virtualbox v6.1 and Docker v19.03.8. This did not happen before.

**Comment by tstromberg** [comment]
Closing since we haven't heard back from @gokulsood
