### ISSUE TITLE
none: TestVersionUpgrade 'exit 0' : driver does not support ssh command

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7190]
as seen in Two PRs:

https://storage.googleapis.com/minikube-builds/logs/7182/3c37556/none_Linux.html#fail_TestVersionUpgrade

and 

https://storage.googleapis.com/minikube-builds/logs/7173/aec6fdc/none_Linux.html#fail_TestVersionUpgrade

**Comment by medyagh** [comment]
similar to errors in https://github.com/kubernetes/minikube/issues/7194

**Comment by tstromberg** [comment]
Root issue: #4132

**Comment by tstromberg** [comment]
Fixed by #7244
