### ISSUE TITLE
Docker flake: Unable to get machine status: state: inspect <profile> timeout

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7193]
as seen here https://storage.googleapis.com/minikube-builds/logs/7173/67bd258/Docker_Linux.html#fail_TestFunctional%2fparallel%2fUpdateContextCmd

**Comment by tstromberg** [comment]
First seen: Mar 23 15:11
Last seen: Mar 25 23:44

Affects these tests:

```
     11 TestFunctional/parallel/CertSync
      1 TestFunctional/parallel/DashboardCmd
      3 TestFunctional/parallel/FileSync
      5 TestFunctional/parallel/LogsCmd
     28 TestFunctional/parallel/UpdateContextCmd
```

**Comment by tstromberg** [comment]
Appears to be due to https://github.com/kubernetes/minikube/pull/6807
