### ISSUE TITLE
hyperv: The requested operation requires elevation.

### ISSUE THREAD

**Issue by akshayyverma** [kubernetes/minikube#7199]
I ran following command on cmd-
minikube start --vm-driver=hyperv --force

GETTING FOLLOWING ERRORS.

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:
Get-WindowsOptionalFeature : The requested operation requires elevation.
At line:1 char:1
+ Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online
+ CategoryInfo          : NotSpecified: (:) [Get-WindowsOptionalFeature], COMException
    + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand
* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

using windows 10 pro

**Comment by tstromberg** [comment]
Did you try to start `Start PowerShell as Administrator`?

**Comment by akshayyverma** [comment]
Yes, I start Start PowerShell as Administrator.
