### ISSUE TITLE
X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds

### ISSUE THREAD

**Issue by garimagupta779** [kubernetes/minikube#7201]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
Do you mind checking if this command-line from #6716 fixes it for you?

`minikube start --iso-url=http://storage.googleapis.com/minikube-builds/iso/HW_RANDOM_VIRTIO_7208.iso`

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
