### ISSUE TITLE
X Unable to start VM: host remove: Failed to find the VM status

### ISSUE THREAD

**Issue by garimagupta779** [kubernetes/minikube#7204]
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.

Thank you for sharing your experience!

**Comment by tstromberg** [comment]
Fixed at head.
