### ISSUE TITLE
docker driver page missing usage instructions

### ISSUE THREAD

**Issue by richterdavid** [kubernetes/minikube#7217]
https://minikube.sigs.k8s.io/docs/reference/drivers/docker/ lacks a number of sections found in, e.g., https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/, particularly the Usage section.

**Comment by medyagh** [comment]
Thanks for creating this issue. it is time for adding proper docs for docker driver

**Comment by medyagh** [comment]
this has been fixed.
