### ISSUE TITLE
Unable to connect to the server: dial tcp: lookup kubernetes.docker.internal: no such host

### ISSUE THREAD

**Issue by ChuckLinQ** [kubernetes/minikube#7222]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by tstromberg** [comment]
minikube does not provide a `kubernetes.docker.internal` hostname. I believe you may be using this instead:

https://www.docker.com/products/docker-desktop
