### ISSUE TITLE
 Failed to pull image "k8s.gcr.io/echoserver:1.10"

### ISSUE THREAD

**Issue by sashiakula** [kubernetes/minikube#7223]
I have installed minikube in my Windows 10 and started it 

**C:\Program Files\Kubernetes\Minikube>minikube start --vm-driver hyperv --hyperv-virtual-switch "My Virtual Switch"**

The above command gives the below output and my cluster started successfully. But there are 2 warnings as bold below:

   minikube v1.8.2 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
Using the hyperv driver based on existing profile
Reconfiguring existing host ...
Using the running hyperv "minikube" VM ...
**! Node may be unable to resolve external DNS records
! VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository**
Preparing Kubernetes v1.17.3 on Docker 19.03.6 ...
Launching Kubernetes ...
Enabling addons: default-storageclass, storage-provisioner
Done! kubectl is now configured to use "minikube"

After that I have executed the below command to create a container but it is failing with error as shown below. 

**kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.10

Failed to pull image "k8s.gcr.io/echoserver:1.10": rpc error: code = Unknown desc = Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on x.x.x.x:x read udp x.x.x.x:51627->x.x.x.x:x i/o timeout**

Any suggestions on this issue?

**Comment by tstromberg** [comment]
Your VM does not appear to have access to the internet. Any idea why that may be?

Is your machine running in a corporate environment where a proxy may need to be configured? https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

**Comment by sashiakula** [comment]
Now I could successfully installed minikube on my windows 10 machine. 
Steps that I followed:
1. I have stopped and deleted the existing minikube
2. Downloaded "https://github.com/kubernetes/minikube/releases/download/v1.8.2/minikube-windows-amd64.exe" and renamed it to minikube.exe
3. Placed the above exe in the same folder in which my kubectl.exe is existing. (C:\kube\). This path is added to the environment variable "Path" of my user.
4. Created a hyperv switch, Open Hyper-V Manager, Click on Virtual Switch Manager, Create New Virtual Network Switch, Select external type, and OK.
5. Ran this command "minikube start --vm-driver="hyperv" --hyperv-virtual-switch="myswitch"
6. minikube successfully started 
7. Then I created a deployment which successfully pulled the image and ran the container.

**Comment by sashiakula** [comment]
> Your VM does not appear to have access to the internet. Any idea why that may be?
> 
> Is your machine running in a corporate environment where a proxy may need to be configured? https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

My Laptop is connected to the internet. And I am not in corporate network and disconnected VPN. The problem that I faced is I think with the windows installer that was used to install minikube.

**Comment by 0815pascal** [comment]
> Now I could successfully installed minikube on my windows 10 machine.
> Steps that I followed:
> 
> 1. I have stopped and deleted the existing minikube
> 2. Downloaded "https://github.com/kubernetes/minikube/releases/download/v1.8.2/minikube-windows-amd64.exe" and renamed it to minikube.exe
> 3. Placed the above exe in the same folder in which my kubectl.exe is existing. (C:\kube). This path is added to the environment variable "Path" of my user.
> 4. Created a hyperv switch, Open Hyper-V Manager, Click on Virtual Switch Manager, Create New Virtual Network Switch, Select external type, and OK.
> 5. Ran this command "minikube start --vm-driver="hyperv" --hyperv-virtual-switch="myswitch"
> 6. minikube successfully started
> 7. Then I created a deployment which successfully pulled the image and ran the container.

Thanks! Creating a New Virtual Network Switch did the job for me
