### ISSUE TITLE
start: Add flag to signify that it's OK to delete broken clusters

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7233]
Exact flag name TBD, but for embedded use cases, it isn't as important to preserve user data as it is to guarantee that a cluster is created somehow. 

We tried this as a default in v1.5, but users did not like the behavior.

**Comment by etanshaul** [comment]
do you think it would make sense to also retry the command once (e.g `minikube start -p []`) after deleting the cluster?

**Comment by etanshaul** [comment]
also to note: it would be nice if this also applied to the `status` command to help with cases like this:
https://www.google.com/url?sa=j&url=https%3A%2F%2Fgithub.com%2FGoogleCloudPlatform%2Fcloud-code-intellij-internal%2Fissues%2F1565%23issuecomment-602939781&uct=1584625964&usg=KjLbJYOLFH84XPvBYs52dEPhAyg.&source=chat

**Comment by tstromberg** [comment]
@etanshaul - At least In v1.9, we retry cluster creation so long as the cluster was created by this session. We should ensure that this behavior is preserved with this new flag.

**Comment by tstromberg** [comment]
To clarify: the intended behavior here is: If startup fails and flag is set:

- Delete the cluster
- Start it again
