### ISSUE TITLE
Translations are not working, confusing locale and language

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#7285]
I added some Swedish translations, but they are **not** picked up by minikube.

It seems to be confusing the locale (language *and* territory) with language ?

```go
	locale, err := jibber_jabber.DetectIETF()
	if err != nil {
		glog.Infof("Getting system locale failed: %v", err)
		locale = ""
	}
	err = SetPreferredLanguage(locale)
	if err != nil {
		glog.Infof("Setting locale failed: %v", err)
		preferredLanguage = defaultLanguage
	}

```
So it sets the language to `sv_SE`, which misses the `sv.json` translations

```console
$ locale
LANG=sv_SE.UTF-8
LANGUAGE=sv
LC_CTYPE="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_PAPER="sv_SE.UTF-8"
LC_NAME="sv_SE.UTF-8"
LC_ADDRESS="sv_SE.UTF-8"
LC_TELEPHONE="sv_SE.UTF-8"
LC_MEASUREMENT="sv_SE.UTF-8"
LC_IDENTIFICATION="sv_SE.UTF-8"
LC_ALL=
```

----

Changing the code to use `jibber_jabber.DetectLanguage()` makes it work.

https://github.com/cloudfoundry-attic/jibber_jabber

Seems like it only works for `zh_CN` locale now ?

It would be fine if it looked for both, first `sv_SE` and then a more general `sv`.

There are some matchers for `language` available, in order to be able to do this:

https://godoc.org/golang.org/x/text/language

**Comment by afbjorklund** [comment]
Some examples here would be en_GB vs en_US, or sv_SE vs sv_FI.

https://en.wikipedia.org/wiki/Locale_(computer_software)

**Comment by tstromberg** [comment]
> It would be fine if it looked for both, first `sv_SE` and then a more general `sv`.

That was the intent, and at least what once worked properly for cases such as 'zh_CN' and 'fr'.

**Comment by tstromberg** [comment]
Do you mind sharing a Swedish translation PR for testing?

/cc @sharifelgamal

**Comment by tstromberg** [comment]
@afbjorklund - I just merged #7280 which may have fixed this.

**Comment by sharifelgamal** [comment]
yeah that will fix it, it supports both full locale and language now

**Comment by afbjorklund** [comment]
> Do you mind sharing a Swedish translation PR for testing?

I just translated a dozen strings, there's like 600 or so left...

```
😄  minikube v1.9.0 på Ubuntu 16.04
✨  Använder drivrutinen virtualbox baserat på existerande profil
🏃  Uppdaterar den körande virtualbox "minikube" VM ...
🐳  Förbereder Kubernetes v1.18.0 på Docker 19.03.8 ...
🌟  Aktiverar tillägg: default-storageclass, storage-provisioner
🏄  Klart! kubectl är nu konfigurerad till att använda "minikube"
```

But I can do a PR.

**Comment by afbjorklund** [comment]
> yeah that will fix it, it supports both full locale and language now

Yes, now it works (with both). Thanks!
