### ISSUE TITLE
dashboard: fetch and run the built-in kubectl version

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7290]
This would improves our getting started experience.

**Comment by afbjorklund** [comment]
The current "experience" is:

```
💣  kubectl not found in PATH, but is required for the dashboard. Installation guide: https://kubernetes.io/docs/tasks/tools/install-kubectl/
```

As noted elsewhere (~#3645~), the guide is complicated.
https://kubernetes.io/docs/tasks/tools/install-kubectl/

Almost as much information as installing minikube itself.
We should be able to replace it with `minikube kubectl`:

```
minikube kubectl -- --context minikube proxy --port=0 &
```

Except in go code.

**Comment by afbjorklund** [comment]
New experience:

```console
$ minikube dashboard
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 41.98 MiB / 41.98 MiB [---------------] 100.00% 1.05 MiB p/s 41s
🤔  Verifying proxy health ...
🎉  Opening http://127.0.0.1:43790/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
```

Takes a while to download (42M), but at least it is automatic.

[https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/](https://github.com/kubernetes/dashboard/blob/master/docs/user/accessing-dashboard/1.7.x-and-above.md#kubectl-proxy)
