### ISSUE TITLE
vbox: creating host: create host timed out, recovery has: write |1: The pipe has been ended.

### ISSUE THREAD

**Issue by stefanomerlano** [kubernetes/minikube#7298]
**The exact command to reproduce the issue**:
minikube start --driver=virtualbox --insecure-registry "10.0.0.0/24" --insecure-registry "192.168.99.0/24" --cpus=6 --memory=7168m --disk-size=150g --alsologtostderr -v=8

**The full output of the command that failed**:<details>
W0328 12:35:26.288638   13136 root.go:248] Error reading config file at C:\Users\yhdbe\.minikube\config\config.json: open C:\Users\yhdbe\.minikube\config\config.json: Impossibile trovare il percorso specificato.
I0328 12:35:26.296670   13136 notify.go:125] Checking for updates...
I0328 12:35:26.585355   13136 start.go:259] hostinfo: {"hostname":"ALIENFRAME","uptime":74,"bootTime":1585395252,"procs":160,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"edb735db-6fbb-4dc5-8082-f9f9c054f999"}
W0328 12:35:26.586355   13136 start.go:267] gopshost.Virtualization returned error: not implemented yet
* minikube v1.9.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
I0328 12:35:26.594354   13136 driver.go:226] Setting default libvirt URI to qemu:///system
* Using the virtualbox driver based on user configuration
I0328 12:35:27.511752   13136 start.go:307] selected driver: virtualbox
I0328 12:35:27.511752   13136 start.go:596] validating driver "virtualbox" against <nil>
I0328 12:35:27.511752   13136 start.go:602] status for virtualbox: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0328 12:35:27.515752   13136 iso.go:119] acquiring lock: {Name:mk6cbd75a80e6e239aa597ecc209aedb69f3a945 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Downloading VM boot image ...
I0328 12:35:27.518751   13136 iso.go:147] full url: https://storage.googleapis.com/minikube/iso/minikube-v1.9.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.9.0.iso.sha256
    > minikube-v1.9.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s    > minikube-v1.9.0.iso: 9.00 MiB / 174.93 MiB [>_____________] 5.14% ? p/s ?    > minikube-v1.9.0.iso: 18.27 MiB / 174.93 MiB [->__________] 10.44% ? p/s ?    > minikube-v1.9.0.iso: 25.30 MiB / 174.93 MiB [->__________] 14.46% ? p/s ?    > minikube-v1.9.0.iso: 34.95 MiB / 174.93 MiB [ 19.98% 43.19 MiB p/s ETA 3s    > minikube-v1.9.0.iso: 44.30 MiB / 174.93 MiB [ 25.32% 43.19 MiB p/s ETA 3s    > minikube-v1.9.0.iso: 55.30 MiB / 174.93 MiB [ 31.61% 43.19 MiB p/s ETA 2s    > minikube-v1.9.0.iso: 64.73 MiB / 174.93 MiB [ 37.01% 43.61 MiB p/s ETA 2s    > minikube-v1.9.0.iso: 74.30 MiB / 174.93 MiB [ 42.47% 43.61 MiB p/s ETA 2s    > minikube-v1.9.0.iso: 86.39 MiB / 174.93 MiB [ 49.39% 43.61 MiB p/s ETA 2s    > minikube-v1.9.0.iso: 96.55 MiB / 174.93 MiB [ 55.19% 44.22 MiB p/s ETA 1s    > minikube-v1.9.0.iso: 109.34 MiB / 174.93 MiB  62.51% 44.22 MiB p/s ETA 1s    > minikube-v1.9.0.iso: 121.91 MiB / 174.93 MiB  69.69% 44.22 MiB p/s ETA 1s    > minikube-v1.9.0.iso: 135.89 MiB / 174.93 MiB  77.68% 45.60 MiB p/s ETA 0s    > minikube-v1.9.0.iso: 149.05 MiB / 174.93 MiB  85.20% 45.60 MiB p/s ETA 0s    > minikube-v1.9.0.iso: 162.11 MiB / 174.93 MiB  92.67% 45.60 MiB p/s ETA 0s    > minikube-v1.9.0.iso: 172.52 MiB / 174.93 MiB  98.62% 46.59 MiB p/s ETA 0s    > minikube-v1.9.0.iso: 174.93 MiB / 174.93 MiB [-] 100.00% 57.40 MiB p/s 4sI0328 12:35:33.216441   13136 preload.go:81] Checking if preload exists for k8s version v1.18.0 and runtime docker
I0328 12:35:33.348480   13136 preload.go:114] Found remote preload: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4
I0328 12:35:33.351698   13136 cache.go:46] Caching tarball of preloaded images
I0328 12:35:33.352699   13136 preload.go:81] Checking if preload exists for k8s version v1.18.0 and runtime docker
I0328 12:35:33.478726   13136 preload.go:114] Found remote preload: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4
* Downloading Kubernetes v1.18.0 preload ...
I0328 12:35:33.492286   13136 preload.go:144] Downloading: &{Ctx:<nil> Src:https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4 Dst:C:\Users\yhdbe\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4.download Pwd: Mode:2 Detectors:[] Decompressors:map[] Getters:map[] Dir:false ProgressListener:<nil> Options:[0xbf9740]}
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 9.73 MiB /    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 23.88 MiB     > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 40.12 MiB     > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 51.84 MiB     > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 64.58 MiB     > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 74.80 MiB     > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 84.45 MiB     > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 99.30 MiB     > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 114.48 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 130.19 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 145.02 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 160.80 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 175.66 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 190.45 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 204.88 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 219.34 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 233.03 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 243.47 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 254.19 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 267.64 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 282.73 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 293.20 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 298.77 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 310.02 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 316.84 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 331.47 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 345.02 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 361.20 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 375.66 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 387.20 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 400.47 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 414.33 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 428.11 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 441.58 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 446.53 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 474.59 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 492.36 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 507.73 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 520.81 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 536.19 MiB    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 542.91 MiBI0328 12:35:41.966764   13136 preload.go:160] saving checksum for preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4 ...
I0328 12:35:42.193385   13136 preload.go:177] verifying checksumm of C:\Users\yhdbe\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4.download ...
I0328 12:35:43.507422   13136 cache.go:49] Finished downloading the preloaded tar for v1.18.0 on docker
I0328 12:35:43.508422   13136 profile.go:138] Saving config to C:\Users\yhdbe\.minikube\profiles\minikube\config.json ...
I0328 12:35:43.509422   13136 lock.go:35] WriteFile acquiring C:\Users\yhdbe\.minikube\profiles\minikube\config.json: {Name:mk48831678c3570ca0c80eb50783a78608cda8b2 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0328 12:35:43.509422   13136 cache.go:117] Successfully downloaded all kic artifacts
I0328 12:35:43.511422   13136 start.go:260] acquiring machines lock for minikube: {Name:mk850f71233a964691675441ecb9feb2e9016330 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0328 12:35:43.511422   13136 start.go:264] acquired machines lock for "minikube" in 0s
I0328 12:35:43.511422   13136 start.go:86] Provisioning new machine with config: {Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.9.0.iso Memory:7168 CPUs:6 DiskSize:153600 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[10.0.0.0/24 192.168.99.0/24] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.0 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:0 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.18.0 ControlPlane:true Worker:true}] Addons:map[]} {Name:m01 IP: Port:8443 KubernetesVersion:v1.18.0 ControlPlane:true Worker:true}
I0328 12:35:43.511422   13136 start.go:107] createHost starting for "m01" (driver="virtualbox")
* Creating virtualbox VM (CPUs=6, Memory=7168MB, Disk=153600MB) ...
I0328 12:35:43.516454   13136 start.go:143] libmachine.API.Create for "minikube" (driver="virtualbox")
I0328 12:35:43.516454   13136 client.go:169] LocalClient.Create starting
I0328 12:35:43.517434   13136 main.go:110] libmachine: Creating CA: C:\Users\yhdbe\.minikube\certs\ca.pem
I0328 12:35:44.286439   13136 main.go:110] libmachine: Creating client certificate: C:\Users\yhdbe\.minikube\certs\cert.pem
I0328 12:35:44.954441   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
I0328 12:35:44.980454   13136 main.go:110] libmachine: STDOUT:
{
6.1.4r136177
}
I0328 12:35:44.980454   13136 main.go:110] libmachine: STDERR:
{
}
I0328 12:35:45.012437   13136 main.go:110] libmachine: Hyper-V is not installed.
%!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)
I0328 12:35:45.012437   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
I0328 12:35:45.980192   13136 main.go:110] libmachine: STDOUT:
{
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            1b83a5a3-6ee2-4c81-8d21-019e4ed9b214
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::31eb:97b1:435b:a4ee
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            b38b0f5e-8ff9-4a33-bef6-584b89a35234
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::9d2c:6987:bc0c:37ab
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:0e
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

}
I0328 12:35:45.980192   13136 main.go:110] libmachine: STDERR:
{
}
I0328 12:35:45.982189   13136 main.go:110] libmachine: Downloading C:\Users\yhdbe\.minikube\cache\boot2docker.iso from file://C:/Users/yhdbe/.minikube/cache/iso/minikube-v1.9.0.iso...
I0328 12:35:46.226175   13136 main.go:110] libmachine: Creating VirtualBox VM...
I0328 12:35:46.226175   13136 main.go:110] libmachine: Creating SSH key...
I0328 12:35:46.710225   13136 main.go:110] libmachine: Creating disk image...
I0328 12:35:46.710225   13136 main.go:110] libmachine: Creating 153600 MB hard disk image...
I0328 12:35:46.710225   13136 main.go:110] libmachine: Writing magic tar header
I0328 12:35:46.717176   13136 main.go:110] libmachine: Writing SSH key tar header
I0328 12:35:46.718186   13136 main.go:110] libmachine: Calling inner createDiskImage
I0328 12:35:46.718186   13136 main.go:110] libmachine: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe convertfromraw stdin C:\Users\yhdbe\.minikube\machines\minikube\disk.vmdk 161061273600 --format VMDK
I0328 12:35:46.718186   13136 main.go:110] libmachine: Starting command
I0328 12:35:46.723185   13136 main.go:110] libmachine: Copying to stdin
I0328 12:35:46.972487   13136 main.go:110] libmachine: Filling zeroes
I0328 12:37:43.518044   13136 start.go:110] createHost completed in 2m0.0056221s
I0328 12:37:43.518044   13136 start.go:77] releasing machines lock for "minikube", held for 2m0.0066219s
! StartHost failed, but will try again: creating host: create host timed out in 120.000000 seconds
I0328 12:37:43.522046   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0328 12:37:44.269047   13136 main.go:110] libmachine: STDOUT:
{
}
I0328 12:37:44.269047   13136 main.go:110] libmachine: STDERR:
{
VBoxManage.exe: error: Could not find a registered machine named 'minikube'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2699 of file VBoxManageInfo.cpp
}
I0328 12:37:44.269047   13136 delete.go:72] Unable to get host status for minikube, assuming it has already been deleted: state: machine does not exist
I0328 12:37:49.270045   13136 start.go:260] acquiring machines lock for minikube: {Name:mk850f71233a964691675441ecb9feb2e9016330 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0328 12:37:49.270045   13136 start.go:264] acquired machines lock for "minikube" in 0s
I0328 12:37:49.270045   13136 start.go:90] Skipping create...Using existing machine configuration
I0328 12:37:49.270045   13136 fix.go:53] fixHost starting: m01
I0328 12:37:49.271047   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0328 12:37:50.143043   13136 main.go:110] libmachine: STDOUT:
{
}
I0328 12:37:50.143043   13136 main.go:110] libmachine: STDERR:
{
VBoxManage.exe: error: Could not find a registered machine named 'minikube'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2699 of file VBoxManageInfo.cpp
}
I0328 12:37:50.143043   13136 fix.go:105] recreateIfNeeded on minikube: state=Error err=machine does not exist
I0328 12:37:50.143043   13136 fix.go:109] exists: false err=machine does not exist
I0328 12:37:50.143043   13136 fix.go:110] "machine does not exist" vs "machine does not exist"
* virtualbox "minikube" VM is missing, will recreate.
I0328 12:37:50.146046   13136 delete.go:114] DEMOLISHING minikube ...
I0328 12:37:50.146046   13136 main.go:110] libmachine: Stopping "minikube"...
I0328 12:37:50.146046   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0328 12:37:50.195044   13136 main.go:110] libmachine: STDOUT:
{
}
I0328 12:37:50.195044   13136 main.go:110] libmachine: STDERR:
{
VBoxManage.exe: error: Could not find a registered machine named 'minikube'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2699 of file VBoxManageInfo.cpp
}
I0328 12:37:50.195044   13136 main.go:110] libmachine: Error getting machine state: machine does not exist
I0328 12:37:50.195044   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0328 12:37:50.240044   13136 main.go:110] libmachine: STDOUT:
{
}
I0328 12:37:50.240044   13136 main.go:110] libmachine: STDERR:
{
VBoxManage.exe: error: Could not find a registered machine named 'minikube'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2699 of file VBoxManageInfo.cpp
}
I0328 12:37:50.240044   13136 stop.go:56] stop err: machine does not exist
I0328 12:37:50.240044   13136 delete.go:119] stophost failed (probably ok): Temporary Error: stop: machine does not exist
I0328 12:37:50.241044   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0328 12:37:50.284044   13136 main.go:110] libmachine: STDOUT:
{
}
I0328 12:37:50.284044   13136 main.go:110] libmachine: STDERR:
{
VBoxManage.exe: error: Could not find a registered machine named 'minikube'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2699 of file VBoxManageInfo.cpp
}
I0328 12:37:50.284044   13136 delete.go:72] Unable to get host status for minikube, assuming it has already been deleted: state: machine does not exist
I0328 12:37:50.284044   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0328 12:37:50.328044   13136 main.go:110] libmachine: STDOUT:
{
}
I0328 12:37:50.328044   13136 main.go:110] libmachine: STDERR:
{
VBoxManage.exe: error: Could not find a registered machine named 'minikube'
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2699 of file VBoxManageInfo.cpp
}
W0328 12:37:50.347045   13136 delete.go:129] delete failed (probably ok) api remove: remove C:\Users\yhdbe\.minikube\machines\minikube\disk.vmdk: Impossibile accedere al file. Il file è utilizzato da un altro processo.
I0328 12:37:50.347045   13136 fix.go:116] Sleeping 1 second for extra luck!
I0328 12:37:51.348045   13136 start.go:107] createHost starting for "m01" (driver="virtualbox")
* Creating virtualbox VM (CPUs=6, Memory=7168MB, Disk=153600MB) ...
I0328 12:37:51.352044   13136 start.go:143] libmachine.API.Create for "minikube" (driver="virtualbox")
I0328 12:37:51.352044   13136 client.go:169] LocalClient.Create starting
I0328 12:37:51.352044   13136 main.go:110] libmachine: Reading certificate data from C:\Users\yhdbe\.minikube\certs\ca.pem
I0328 12:37:51.352044   13136 main.go:110] libmachine: Decoding PEM data...
I0328 12:37:51.352044   13136 main.go:110] libmachine: Parsing certificate...
I0328 12:37:51.352044   13136 main.go:110] libmachine: Reading certificate data from C:\Users\yhdbe\.minikube\certs\cert.pem
I0328 12:37:51.353044   13136 main.go:110] libmachine: Decoding PEM data...
I0328 12:37:51.353044   13136 main.go:110] libmachine: Parsing certificate...
I0328 12:37:51.353044   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
I0328 12:37:51.382044   13136 main.go:110] libmachine: STDOUT:
{
6.1.4r136177
}
I0328 12:37:51.382044   13136 main.go:110] libmachine: STDERR:
{
}
I0328 12:37:51.415046   13136 main.go:110] libmachine: Hyper-V is not installed.
%!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)
I0328 12:37:51.415046   13136 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
I0328 12:37:51.496046   13136 main.go:110] libmachine: STDOUT:
{
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            1b83a5a3-6ee2-4c81-8d21-019e4ed9b214
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::31eb:97b1:435b:a4ee
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:03
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            b38b0f5e-8ff9-4a33-bef6-584b89a35234
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::9d2c:6987:bc0c:37ab
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:0e
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

}
I0328 12:37:51.496046   13136 main.go:110] libmachine: STDERR:
{
}
I0328 12:37:51.497044   13136 main.go:110] libmachine: Downloading C:\Users\yhdbe\.minikube\cache\boot2docker.iso from file://C:/Users/yhdbe/.minikube/cache/iso/minikube-v1.9.0.iso...
I0328 12:37:51.752044   13136 main.go:110] libmachine: Creating VirtualBox VM...
I0328 12:37:51.752044   13136 main.go:110] libmachine: Creating SSH key...
I0328 12:37:51.899047   13136 main.go:110] libmachine: Creating disk image...
I0328 12:37:51.899047   13136 main.go:110] libmachine: Creating 153600 MB hard disk image...
I0328 12:37:51.899047   13136 main.go:110] libmachine: Writing magic tar header
I0328 12:37:51.899047   13136 main.go:110] libmachine: Writing SSH key tar header
I0328 12:37:51.899047   13136 main.go:110] libmachine: Calling inner createDiskImage
I0328 12:37:51.900046   13136 main.go:110] libmachine: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe convertfromraw stdin C:\Users\yhdbe\.minikube\machines\minikube\disk.vmdk 161061273600 --format VMDK
I0328 12:37:51.900046   13136 main.go:110] libmachine: Starting command
I0328 12:37:51.902046   13136 main.go:110] libmachine: Copying to stdin
I0328 12:37:51.917046   13136 client.go:172] LocalClient.Create took 565.0023ms
I0328 12:37:53.918044   13136 start.go:110] createHost completed in 2.5699997s
I0328 12:37:53.918044   13136 fix.go:55] fixHost completed within 4.6479993s
I0328 12:37:53.918044   13136 start.go:77] releasing machines lock for "minikube", held for 4.6479993s
* StartHost failed again: recreate: creating host: create: creating: write |1: Pipe terminata.
  - Run: "minikube delete", then "minikube start --alsologtostderr -v=1" to try again with more logging
W0328 12:37:53.930044   13136 exit.go:101] Unable to start VM after repeated tries. Please try {{'minikube delete' if possible: recreate: creating host: create: creating: write |1: Pipe terminata.
* 
X Unable to start VM after repeated tries. Please try {{'minikube delete' if possible: recreate: creating host: create: creating: write |1: Pipe terminata.
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
minikube v1.9.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
VirtualBox 6.1.4 r136177 (Qt5.6.2)

**Comment by tstromberg** [comment]
Do you mind sharing the output of:

`C:\Program Files\Oracle\VirtualBox\VBoxManage.exe convertfromraw stdin C:\Users\yhdbe.minikube\machines\minikube\disk.vmdk 161061273600 --format VMDK`

**Comment by stefanomerlano** [comment]
After the command execute is waiting for stdin input.

**The command**:
VBoxManage.exe convertfromraw stdin C:\Users\yhdbe\.minikube\machines\minikube\disk.vmdk 161061273600 --format VMDK

**The full output**:<details>
Converting from raw image file="stdin" to file="C:\Users\yhdbe\.minikube\machines\minikube\disk.vmdk"...
Creating dynamic image with size 161061273600 bytes (153600MB)...

**Comment by priyawadhwa** [comment]
Hey @stefanomerlano sorry for the delay in responding to your issue. I'm wondering if you're still seeing this issue with our [latest release](https://github.com/kubernetes/minikube/releases)?

**Comment by afbjorklund** [comment]
I think the command used to create is just "too slow", and thus hits the arbitrary 2 minute timeout.

`create host timed out in 120.000000 seconds`

Currently it starts with the original raw image, and then fills it up to the requested size with zeroes!

This means that it needs to pipe all of those 150g

```go
        // The total number of bytes written to stdin must match sizeBytes, or
        // VBoxManage.exe on Windows will fail. Fill remaining with zeros.
  ```

It would have been more efficient to resize the image after it has been created, for this scenario.

https://www.virtualbox.org/manual/ch08.html#vboxmanage-convertfromraw

https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifymedium
https://www.virtualbox.org/manual/ch08.html#vboxmanage-convertfromraw

**Comment by tstromberg** [comment]
Recent versions of minikube wait longer (up to 4 minutes), but that doesn't seem to help for all users.

You may have some luck by adding: `minikube start --delete-on-failure=true` in the mean-time, or choosing a non-virtualbox driver.

**Comment by medyagh** [comment]
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
