### ISSUE TITLE
none: "The none driver requires conntrack to be installed" - but it's installed!

### ISSUE THREAD

**Issue by vlganev** [kubernetes/minikube#7301]
Hello,
I get an error `The none driver requires conntrack to be installed for kubernetes version`
I the same time I have:
```
vg@frozensoul:~$ conntrack --version
conntrack v1.4.5 (conntrack-tools)
```
I guess the issue is here 
```
		if version.GTE(semver.MustParse("1.18.0-beta.1")) {
			err := exec.Command("conntrack").Run()
			if err != nil {
				exit.WithCodeT(exit.Config, "The none driver requires conntrack to be installed for kubernetes version {{.k8sVersion}}", out.V{"k8sVersion": version.String()})
			}
		}
```
After commenting the code above it seems fine.

**Comment by tstromberg** [comment]
It may be in your path as `vg`, but I suspect it is not in roots path. Can you confirm:

```
sudo su -
conntrack --version
```

**Comment by tstromberg** [comment]
If nothing else, this error message is misleading and unhelpful. 

If you don't mind, can you also share the output of:

`whereis conntrack`

and:

```
sudo su -
echo $PATH
```

I think a better error message here would be:

`conntrack not found in root users $PATH`

**Comment by tstromberg** [comment]
Also, this should be calling `exec.LookPath` instead of running conntrack.

**Comment by vlganev** [comment]
Hi, this is the output
```
root@frozensoul:~# conntrack --version
conntrack v1.4.5 (conntrack-tools)
```

```
root@frozensoul:~# whereis conntrack
conntrack: /usr/sbin/conntrack /usr/share/man/man8/conntrack.8.gz
```
```
root@frozensoul:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

Thank you for the quick response!

**Comment by tstromberg** [comment]
OK. I think this check is bad, but can you confirm one last thing for me? I'd like to see the output of:

`sudo conntrack; echo $?`

Thank you for your speedy replies. =)

**Comment by vlganev** [comment]
The output is interesting:
```
vg@frozensoul~$ sudo conntrack; echo $?
conntrack v1.4.5 (conntrack-tools): you have to specify `--src' and `--dst'
Try `conntrack -h' or 'conntrack --help' for more information.
2
```

**Comment by tstromberg** [comment]
@vlganev - any chance you could confirm that the binary produced by #7305 fixes your issue?

https://storage.googleapis.com/minikube-builds/7305/minikube-linux-amd64

Thank you!

**Comment by vlganev** [comment]
@tstromberg I've just tested it and it's working. 
Thank you!
