### ISSUE TITLE
hyperkit: Error in driver during machine creation: hyperkit crashed!

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7303]
Faced same issue..any update?

 minikube-v1.9.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.9.0.iso: 174.93 MiB / 174.93 MiB [ 100.00% 1.17 MiB p/s 2m29s
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 542.91 MiB
🔥  Creating hyperkit VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
❌  StartHost failed again: creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
👉  Run: "minikube delete", then "minikube start --alsologtostderr -v=1" to try again with more logging

E0329 00:05:07.799189   41597 style.go:173] unable to parse "💣  Unable to start VM after repeated tries. Please try {{'minikube delete' if possible\n": template: 💣  Unable to start VM after repeated tries. Please try {{'minikube delete' if possible
:1: malformed character constant: 'minikube delete' - returning raw string.
💣  Unable to start VM after repeated tries. Please try {{'minikube delete' if possible
❌  Error: [HYPERKIT_CRASHED] creating host: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
💡  Suggestion: Hyperkit is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --driver
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6079
    ▪ https://github.com/kubernetes/minikube/issues/5780

_Originally posted by @amitmaurya001 in https://github.com/kubernetes/minikube/issues/7140#issuecomment-605501586_

**Comment by tstromberg** [comment]
Hey @amitmaurya001 - do you mind sharing the output  of:

`ls -lad $(which hyperkit) && hyperkit -v`

Mine for instance reports:

```
-rwxr-xr-x  1 tstromberg  primarygroup  257644 Jan 23 17:30 /Users/tstromberg/bin/hyperkit
hyperkit: v0.20190802-4-g97f091
```

In general, hyperkit crashes are nearly always sorted out by upgrading hyperkit.

**Comment by amitmaurya001** [comment]
here it is..
Amits-MacBook-Air:~ Amit$ ls -lad $(which hyperkit) && hyperkit -v
lrwxr-xr-x  1 Amit  staff  67 Jul 23  2019 /usr/local/bin/hyperkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
hyperkit: v0.20180403-17-g3e954c

Homepage: https://github.com/docker/hyperkit
License: BSD

**Comment by tstromberg** [comment]
Also helpful  for me  would be the output of:

`uname -a && docker version --format '{{.Client.Version}}'`

If Docker is installed, you may be able to get unblocked by using `minikube start --driver=docker`

**Comment by amitmaurya001** [comment]
Amits-MacBook-Air:~ Amit$ uname -a && docker version --format '{{.Client.Version}}'
Darwin Amits-MacBook-Air.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
18.09.2
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by amitmaurya001** [comment]
Amits-MacBook-Air:~ Amit$ minikube start --driver=docker
😄  minikube v1.9.0 on Darwin 10.13.6
💥  The existing "minikube" VM was created using the "hyperkit" driver, and is incompatible with the "docker" driver.
👉  To proceed, either:

1) Delete the existing "minikube" cluster using: 'minikube delete'

* or *

2) Start the existing "minikube" cluster using: 'minikube start --driver=hyperkit'

💣  Exiting.

**Comment by tstromberg** [comment]
The version of hyperkit on your machine is older than our minimum supported version: `0.20190201`. minikube was supposed to error out based on this fact with a message like:

`the installed hyperkit version (0.%s) is older than the minimum recommended version (%s)`

If you did not see  a warning, it means that our version check is not working.

The workaround is to install the latest  hyperkit, either by installing the latest version of Docker (optional), or following the hyperki

* Upgrading to the latest version of Docker (recommended, since it's already installed)
* Running "brew install hyperkit"
* Building from https://github.com/moby/hyperkit

**Comment by tstromberg** [comment]
Please let me know if this helps you get through.

**Comment by sharifelgamal** [comment]
@amitmaurya001 I'm going to go ahead and close this. Feel free to reopen if you need more guidance.
