### ISSUE TITLE
need help deleting the ".minikube" directory and resetting environment after running "route -f"

### ISSUE THREAD

**Issue by nnt1054** [kubernetes/minikube#7312]
I had a conflicting route when running "minikube tunnel", so I accidentally ran "route -f" instead of only removing the individual route.  I no longer can access the previously running minikube instances using minikube or kubectl and can't manually delete the ".minikube" directory due to a "files being used by another process." error.

While attempting to debug the issue, "minikube start" also gave a "Could not allocate 4000MB memory" which suggests to me that the previous minikube instances/profiles are still using up memory? The memory usage shown in Task Manager is also seems much higher than normal.

Would appreciate any help to get back to a clean install of minikube again.  Thanks in advance!

**Full output of `minikube start` command used, if not already included:**

> ! "minikube" profile does not exist, trying anyways.
> * Removing C:\Users\Neil\.minikube\machines\minikube ...
> *
> X Unable to remove machine directory: %v: remove C:\Users\Neil\.minikube\machines\minikube\minikube\Virtual Machines\79D736A9-F884-4C67-AEB5-B8716517E7A0.vmcx: The process cannot access the file because it is being used by another process.
> *
> * minikube is exiting due to an error. If the above message is not useful, open an issue:
>   - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube delete` command used, if not already included:**
> ! "minikube" profile does not exist, trying anyways.
> * Removing C:\Users\Neil\.minikube\machines\minikube ...
> *
> X Unable to remove machine directory: %v: remove C:\Users\Neil\.minikube\machines\minikube\minikube\Virtual Machines\79D736A9-F884-4C67-AEB5-B8716517E7A0.vmcx: The process cannot access the file because it is being used by another process.
> *
> * minikube is exiting due to an error. If the above message is not useful, open an issue:
>   - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by nnt1054** [comment]
Update: I used the Powershell Stop-VM command to stop the corresponding VM's and reduced my memory usage by 8GB, but attempting to delete the ".minikube" directory or running "minikube delete" still outputs the error:

> X Unable to remove machine directory: %v: remove C:\Users\Neil\.minikube\machines\minikube\minikube\Virtual Machines\79D736A9-F884-4C67-AEB5-B8716517E7A0.vmcx: The process cannot access the file because it is being used by another process.

**Comment by nnt1054** [comment]
Solution: I deleted the VM's using the Hyper-V Manager, and then used the Powershell "Get-Service" and "Stop-Service" commands to stop all the running hyperv services.  Afterwards I was able to delete the ".minikube" directory and now everything seems to be operating normally.

**Comment by tstromberg** [comment]
OK. Just for clarification - what version of minikube was this with? 

Versions before v1.9.0 had an especially difficult time deleting Hyper-V VM's.

**Comment by tstromberg** [comment]
Also, it should never be necessary to manually delete the `.minikube` folder. You can get the same result more safely with `minikube delete --purge --all`: that attempt to ensure that the VM's are shut down.

**Comment by nnt1054** [comment]
> OK. Just for clarification - what version of minikube was this with?
> 
> Versions before v1.9.0 had an especially difficult time deleting Hyper-V VM's.
I'm using v.1.8.2

> Also, it should never be necessary to manually delete the `.minikube` folder. You can get the same result more safely with `minikube delete --purge --all`: that attempt to ensure that the VM's are shut down.
Thanks for the tip, I'll keep that in mind next time.  It seemed like minikube wasn't finding the profiles for the other VM's so I maybe panicked and opted to delete the '.minikube' folder.  I also don't particularly know too much about routing tables and how minikube interacts with them.

**Comment by WilliamDenniss** [comment]
I had this error.

My case: Windows 10. I upgraded to WSL 2.0, and I also upgraded minikube (through Chocolatey). Along the way, something was misconfigured. I had many errors with `minikube start`, and `minikube delete --purge --all` gave this "file in use" error. Uninstalling minikube/reinstalling didn't help either.

I resolved it by restarting in safe mode, and manually deleting the folder `.minikube`. After doing this, I could use minikube again.

**Comment by Sahilkhurana77** [comment]
hi everyone,
I am getting the same issue and not able to delete the directory /minikube using the above steps please help as it is showing the error :
W0220 17:17:22.343126   12860 main.go:291] Unable to resolve the current Docker CLI context "default": context "default": context not found: open C:\Users\HP\.docker\contexts\meta\37a8eec1ce19687d132fe29051dca629d164e2c4958ba141d5f4133a33f0688f\meta.json: The system cannot find the path specified.
* Removing C:\Users\HP\.minikube\machines\minikube ...

X Exiting due to GUEST_FILE_IN_USE: remove C:\Users\HP\.minikube\machines\minikube\minikube\Virtual Machines\82D445D2-B810-428A-80D9-BCE17779F30F.vmcx: The process cannot access the file because it is being used by another process.
* Suggestion: Another program is using a file required by minikube. If you are using Hyper-V, try stopping the minikube VM from within the Hyper-V manager


Please help...
