### ISSUE TITLE
downloads fail with local error: tls: bad record MAC

### ISSUE THREAD

**Issue by georgedelacruz213** [kubernetes/minikube#7313]
**Steps to reproduce the issue:** 

1. minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"

**Full output of failed command:** 

```
* minikube v1.9.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the hyperv driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.9.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.9.0.iso: 174.93 MiB / 174.93 MiB  100.00% 216.00 KiB p/s 13m4
* Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 161.17 MiB
* Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
E0330 08:37:47.932111   21348 cache.go:63] save image to file "k8s.gcr.io/kube-scheduler:v1.18.0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-scheduler_v1.18.0" failed: write: local error: tls: bad record MAC
E0330 08:37:47.932111   21348 cache.go:63] save image to file "k8s.gcr.io/kube-proxy:v1.18.0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-proxy_v1.18.0" failed: write: local error: tls: bad record MAC
E0330 08:37:47.932111   21348 cache.go:63] save image to file "k8s.gcr.io/kube-apiserver:v1.18.0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-apiserver_v1.18.0" failed: write: local error: tls: bad record MAC
E0330 08:37:47.935114   21348 cache.go:63] save image to file "k8s.gcr.io/kube-controller-manager:v1.18.0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-controller-manager_v1.18.0" failed: write: Get https://storage.googleapis.com/asia.artifacts.google-containers.appspot.com/containers/images/sha256:597de8ba0c30cdd0b372023aa2ea3ca9b3affbcba5ac8db922f57d6cb67db7c8: local error: tls: bad record MAC
E0330 08:37:47.936113   21348 cache.go:63] save image to file "k8s.gcr.io/etcd:3.4.3-0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\etcd_3.4.3-0" failed: write: local error: tls: bad record MAC
E0330 08:37:47.936113   21348 cache.go:126] Error caching images:  Caching images for kubeadm: caching images: caching image "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-scheduler_v1.18.0": write: local error: tls: bad record MAC
E0330 08:38:43.561442   21348 cache.go:63] save image to file "k8s.gcr.io/kube-proxy:v1.18.0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-proxy_v1.18.0" failed: write: local error: tls: bad record MAC
E0330 08:38:43.561442   21348 cache.go:63] save image to file "k8s.gcr.io/etcd:3.4.3-0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\etcd_3.4.3-0" failed: write: local error: tls: bad record MAC
E0330 08:38:43.561442   21348 cache.go:63] save image to file "k8s.gcr.io/kube-scheduler:v1.18.0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-scheduler_v1.18.0" failed: write: local error: tls: bad record MAC
E0330 08:38:43.561442   21348 cache.go:63] save image to file "k8s.gcr.io/kube-apiserver:v1.18.0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-apiserver_v1.18.0" failed: write: Get https://storage.googleapis.com/asia.artifacts.google-containers.appspot.com/containers/images/sha256:597de8ba0c30cdd0b372023aa2ea3ca9b3affbcba5ac8db922f57d6cb67db7c8: local error: tls: bad record MAC
E0330 08:38:43.561442   21348 cache.go:63] save image to file "k8s.gcr.io/kube-controller-manager:v1.18.0" -> "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-controller-manager_v1.18.0" failed: write: local error: tls: bad record MAC
*
X Failed to cache images: Caching images for kubeadm: caching images: caching image "C:\\Users\\<user>\\.minikube\\cache\\images\\k8s.gcr.io\\kube-proxy_v1.18.0": write: local error: tls: bad record MAC
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by tstromberg** [comment]
I'm stumped by this one for two reasons:

* TLS works, because minikube is able to download the ISO and the overlay
* Why are we saving images to files when the overlay is in use? That seems like a bug.

Do you mind sharing the output of your minikube start command + `--alsologtostderr -v=1`? It should shed some light on the later issue.

Looking for the same TLS error, I didn't find much, other than folks blaming NIC hardware offloading:

* https://github.com/rclone/rclone/issues/1774
* https://github.com/cockroachdb/cockroach/issues/9971

**Comment by georgedelacruz213** [comment]
I had minikube running after a few attempts. 

Please check out this [link](https://pastebin.com/cYUyKGst) for the output of _minikube start --alsologtostderr -v=1_

**Comment by tstromberg** [comment]
That's great to hear. Once the artifacts have been downloaded, everything should go smoothly.

Seeing the logs helped everything make sense. Particularly:

`10:11:30.812293   16232 cache.go:52] Error downloading preloaded artifacts will continue without preload: download failed: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: local error: tls: bad record MAC`

The error message comes down to a corrupt message being received by Go's TLS library. Chances are that other applications on your machine are similarly afflicted, but maybe more forgiving if they were not written in Go. Chances are they are retrying the failure. 

I did some research on the situation, and it seems to come down to a couple of possibilities:

* A faulty network card driver. Often recoverable by turning off hardware preload features.
* Anti-virus software intercepting outgoing SSL packets
* Network MTU misconfiguration

Here's what I recommend trying:

* If you are in a corporate environment, see if there is an HTTPS/HTTP proxy you should be using
* Disable SSL/HTTPS scanning in your anti-virus software (or just disable it entirely for a test)
* Update your network card drivers
* See if you can disable any streaming or hardware offload features on your network card

Some additional references I found to base this advice on:

* https://appuals.com/fix-err_ssl_bad_record_mac_alert/
* https://ugetfix.com/ask/how-to-fix-err_ssl_bad_record_mac_alert-error/
* https://stackoverflow.com/questions/8154617/how-to-troubleshoot-ssl-bad-record-mac-exception

If you want to test minikube's ability to download without breaking your current cluster, try:

`minikube start --kubernetes-version=<any random version, like v1.14.10> --download-only -p download-test`

Hope this helps. Let me know what if anything you come up with.

**Comment by georgedelacruz213** [comment]
Thanks @tstromberg 

This might be a hardware issue and not in minikube. Closing this ticket.
