### ISSUE TITLE
initialization failed, will try again: run: /bin/bash -c "sudo

### ISSUE THREAD

**Issue by rizwan-star** [kubernetes/minikube#7319]
**Steps to reproduce the issue:** 

1.initialization failed, will try again: run: /bin/bash -c "sudo 
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by rizwan-star** [comment]
host: Nonexistent
kubelet: Nonexistent
apiserver: Nonexistent
kubeconfig: Nonexistent

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
