### ISSUE TITLE
Shorten minikube version output

### ISSUE THREAD

**Issue by peterlin741** [kubernetes/minikube#7322]
The output of `minikube version` is currently:
```
minikube version: v1.9.0
commit: 48fefd43444d2f8852f527c78f0141b377b1e42a
```

Whereas I expected only the version number: `v1.9.0`

Supporting JSON output would also work, if you need to keep the commit information, since that would also allow me to parse the version directly

**Comment by tstromberg** [comment]
I'm curious where your expectation comes from. Even `kubectl version --short` doesn't just respond with a version number:

```
Client Version: v1.16.3
Server Version: v1.18.0
```

I don't mind if someone adds a `--short` flag to minikube to get what you are looking for, but I don't feel it's necessary to update the default case.

**Comment by afbjorklund** [comment]
We could also add a `--format` option similar to Docker ? Or perhaps a --short like Kubernetes client.

It also have a `--output` option, to choose between yaml and json if you don't need a full go template.

**Comment by peterlin741** [comment]
> I'm curious where your expectation comes from. Even `kubectl version --short` doesn't just respond with a version number:
> 
> ```
> Client Version: v1.16.3
> Server Version: v1.18.0
> ```
> 
> I don't mind if someone adds a `--short` flag to minikube to get what you are looking for, but I don't feel it's necessary to update the default case.
> 
> Anyone else have thoughts here?

I saw that `skaffold version` returns `v1.6.0`. I wasn't entirely sure what the differences were between that and `kubectl` but I see now that `kubectl version --short` returns both a service and client version.

Any of the above suggested solutions work. Thanks for looking into this!

**Comment by sharifelgamal** [comment]
I think having a non-default `--short` option is totally fine, also `version` doesn't currently support `--output` but it wouldn't be hard to do.

**Comment by afbjorklund** [comment]
> I saw that `skaffold version` returns `v1.6.0`. I wasn't entirely sure what the differences were between that and `kubectl` but I see now that `kubectl version --short` returns both a service and client version.

It's like total anarchy in the cloud native world, not only about the "silent" `v` in the versions...

```console
$ runc --version
runc version 1.0.0-rc10
commit: dc9208a3303feef5b3839f4323d9beb36df0a9dd
spec: 1.0.1-dev
$ containerd --version
containerd github.com/containerd/containerd v1.2.13 7ad184331fa3e55e52b890ea95e65ba581ae3429
```
```console
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b7f0
 Built:             Wed Mar 11 01:25:58 2020
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b7f0
  Built:            Wed Mar 11 01:30:32 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
$ minikube kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by afbjorklund** [comment]
Like so:
```console
$ ./out/minikube version
minikube version: v1.9.0
commit: a1cc3188bb6e0598de68c72f61f6a0fc9e1d2922
$ ./out/minikube version --short
minikube version: v1.9.0
$ ./out/minikube version -o json
{"commit":"a1cc3188bb6e0598de68c72f61f6a0fc9e1d2922","minikubeVersion":"v1.9.0"}
$ ./out/minikube version --output yaml
commit: a1cc3188bb6e0598de68c72f61f6a0fc9e1d2922
minikubeVersion: v1.9.0

```

Same as `kubectl version` options.

**Comment by peterlin741** [comment]
> ```
> ./out/minikube version -o json
> ```

Looks great! we'll mainly be using the `./out/minikube version -o json` flags, but good to know the other options are also available

**Comment by peterlin741** [comment]
> Like so:
> 
> ```
> $ ./out/minikube version
> minikube version: v1.9.0
> commit: a1cc3188bb6e0598de68c72f61f6a0fc9e1d2922
> $ ./out/minikube version --short
> minikube version: v1.9.0
> $ ./out/minikube version -o json
> {"commit":"a1cc3188bb6e0598de68c72f61f6a0fc9e1d2922","minikubeVersion":"v1.9.0"}
> $ ./out/minikube version --output yaml
> commit: a1cc3188bb6e0598de68c72f61f6a0fc9e1d2922
> minikubeVersion: v1.9.0
> ```
> 
> Same as `kubectl version` options.

Looks great! we'll mainly be using the `./out/minikube version -o json` flags, but good to know that the other options are available
