### ISSUE TITLE
.kube directory is created outside of MINIKUBE_HOME

### ISSUE THREAD

**Issue by matjung** [kubernetes/minikube#7323]
**Steps to reproduce the issue:** 

1. set MINIKUBE_HOME=G:\Internet\MyKube
2. minikube start

Well despite telling minikube to work with folder MyKube in the G drive
it still creates file **config** in folder **.kube** in folder %USERPROFILE%

I think this is not a critical bug, but it is one.

I expected to get this folder structure
```
...MyKube\.minikube
...MyKube\.kube
```

```
* minikube v1.9.0 on Microsoft Windows 10 Home 10.0.18362 Build 18362
  - MINIKUBE_HOME=G:\Internet\MyKube
* Automatically selected the virtualbox driver
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
* Enabling addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"
* For best results, install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/
```

**Comment by tstromberg** [comment]
The `.kube` folder is not controlled by MINIKUBE_HOME, because it needs to be found by Kubernetes tools like `kubectl` which know nothing about minikube.

If you want to set the location of `.kube\config`, use the `KUBECONFIG` variable documented here:
 https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/

Please let me know if this helps. If nothing else, it sounds like something we should document.

**Comment by priyawadhwa** [comment]
For documentation, we could clarify that MINIKUBE_HOME:

- is used only by minikube
- doesn't include anything related to Kubernetes tools (`kubectl`)

in our documentation around environment variables:

https://minikube.sigs.k8s.io/docs/reference/environment_variables/


If anybody would be interested in updating the documentation, I'd be happy to review any PRs.

**Comment by matjung** [comment]
I made a few tests:
minikube is able to respect parameter KUBECONFIG
KUBECONFIG must point to a filename - it fails with a path

I appreciate if the environment_variables documentation gets an update.

G:\Internet\KubeMine>minikube start
* minikube v1.9.0 on Microsoft Windows 10 Home 10.0.18362 Build 18362
  - KUBECONFIG=G:\Internet\KubeMine\kubeConfig
  - MINIKUBE_HOME=G:\Internet\KubeMine
* Automatically selected the virtualbox driver
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
* Enabling addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"
* For best results, install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/

Directory of G:\Internet\KubeMine

31.03.2020  15:17    <DIR>          .
31.03.2020  15:17    <DIR>          ..
31.03.2020  15:17    <DIR>          .minikube
31.03.2020  15:17               484 kubeConfig
30.03.2020  18:30        54'792'192 minikube.exe

**Comment by matjung** [comment]
I've drafted an update of the environment variables documentation, submitted a pull request and closed the ticket.

**Comment by priyawadhwa** [comment]
Hey @matjung thanks for submitting #7336 

We typically keep issues open until PRs are merged, so I'm going to reopen this.

**Comment by jlaswell** [comment]
I'll pick up the `MINIKUBE_HOME` notes part of the documentation if that's alright. https://github.com/kubernetes/minikube/issues/7323#issuecomment-606261180

@priyawadhwa

**Comment by priyawadhwa** [comment]
@jlaswell sounds good, thank you!
