### ISSUE TITLE
vbox on Windows: ssh exit status 255: WARNING: UNPROTECTED PRIVATE KEY FILE!

### ISSUE THREAD

**Issue by matjung** [kubernetes/minikube#7337]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube ssh
3.

**Full output of failed command:** 
GuestAdditionsVersion="5.2.32 r132056"
GuestAdditionsFacility_VirtualBox Base Driver=50,1585660609196

I0331 15:44:42.658895    3920 main.go:110] libmachine: Using SSH client type: external
I0331 15:44:42.658895    3920 main.go:110] libmachine: &{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i G:\Internet\KubeMine\.minikube\machines\minikube\id_rsa -p 53332] C:\WINDOWS\System32\OpenSSH\ssh.exe <nil>}
I0331 15:44:42.658895    3920 main.go:110] libmachine: C:\WINDOWS\System32\OpenSSH\ssh.exe -F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null docker@127.0.0.1 -o IdentitiesOnly=yes -i G:\Internet\KubeMine\.minikube\machines\minikube\id_rsa -p 53332
ssh: exit status 255

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
Workaround: Do SSH without minikube: And manually approve some warnings

ssh.exe docker@127.0.0.1 -o IdentitiesOnly=yes -i G:\Internet\KubeMine\.minikube\machines\minikube\id_rsa -p  53332
The authenticity of host '[127.0.0.1]:53332 ([127.0.0.1]:53332)' can't be established.
ECDSA key fingerprint is SHA256:3dnHLS7HrBou7s2iZ2sv9HIaT7lhu9IKVX8vfcaiei0.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '[127.0.0.1]:53332' (ECDSA) to the list of known hosts.
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions for 'G:\\Internet\\KubeMine\\.minikube\\machines\\minikube\\id_rsa' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "G:\\Internet\\KubeMine\\.minikube\\machines\\minikube\\id_rsa": bad permissions
docker@127.0.0.1's password:

This is how I got SSH access
</details>

**Comment by matjung** [comment]
Is it possible to tell minikube which SSH client with what parameters to use?

**Comment by matjung** [comment]
I am wondering if the issue could be related with the Virtual Box Guest Additions Version.

**Comment by medyagh** [comment]
@matjung I haven't heard from you I will close this issue please feel free to reopen if needed 

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
