### ISSUE TITLE
image-repository in China: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws"

### ISSUE THREAD

**Issue by zhuzhenfirst** [kubernetes/minikube#7343]
minikube start --image-mirror-country=cn --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
* minikube v1.9.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
* Using the hyperv driver based on existing profile
* Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
* Downloading Kubernetes v1.18.0 preload ...
* Updating the running hyperv "minikube" VM ...
E0401 03:35:31.688636    4896 cache.go:63] save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.0" -> "C:\\Users\\zhuzh\\.minikube\\cache\\images\\registry.cn-hangzhou.aliyuncs.com\\google_containers\\kube-scheduler_v1.18.0" failed: nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.0: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
E0401 03:35:48.722121    4896 cache.go:126] Error caching images:  Caching images for kubeadm: caching images: caching image "C:\\Users\\zhuzh\\.minikube\\cache\\images\\registry.cn-hangzhou.aliyuncs.com\\google_containers\\kube-scheduler_v1.18.0": nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.0: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
E0401 03:35:50.070122    4896 cache.go:63] save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.0" -> "C:\\Users\\zhuzh\\.minikube\\cache\\images\\registry.cn-hangzhou.aliyuncs.com\\google_containers\\kube-scheduler_v1.18.0" failed: nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.0: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
*
X Failed to cache images: Caching images for kubeadm: caching images: caching image "C:\\Users\\zhuzh\\.minikube\\cache\\images\\registry.cn-hangzhou.aliyuncs.com\\google_containers\\kube-scheduler_v1.18.0": nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.0: unsupported MediaType: "application/vnd.docker.distribution.manifest.v1+prettyjws", see https://github.com/google/go-containerregistry/issues/377
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
这还会发生吗？

我无法使用macOS或Linux上的minikube v1.9.2复制此文件：

`minikube start --image-mirror-country = cn --image-repository = registry.cn-hangzhou.aliyuncs.com / google_containers`

我什至尝试添加--preload = false来模仿中国的经验。 这个问题可能已在minikube v1.9中修复，或已在服务器上修复。

**Comment by sharifelgamal** [comment]
任何更新？

**Comment by medyagh** [comment]
Hi @zhuzhenfirst, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
