### ISSUE TITLE
Checksums did not match for kubelet.download

### ISSUE THREAD

**Issue by bobishere** [kubernetes/minikube#7348]
**重现问题所需的命令**：
minikube start --image-mirror-country=cn   --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso  --registry-mirror=https://y0qd3iq.mirror.aliyuncs.com  --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --driver=none

**失败的命令的完整输出**：<details>

</details>
更新 cluster 失败: updating node: downloading binaries: downloading kubelet: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubelet?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubelet.sha256: Checksums did not match for /root/.minikube/cache/linux/v1.18.0/kubelet.download.
Expected: 3a90e7abf9910aebf9ef5845918c665afd4136a8832604ccfabca2defb35ce0f
Got: f0795a9f49e68c51530a16086401406c0b1f645cb0de741058d00975557cb885
*sha256.digest

**`minikube logs`命令的输出**： <details>

 由于出错 minikube 正在退出。如果以上信息没有帮助，请提交问题反馈：
👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**使用的操作系统版本**：
ubuntu（vbox/amd64）19.10

**Comment by tstromberg** [comment]
听起来像kubelet下载已损坏。 这是什么版本的minikube？

如果重试，是否也会以同样的方式失败？

**Comment by medyagh** [comment]
@bobishere haven't heard from you do mind trying miniube v1.10.1 with docker driver ?

minikube delete
minikube start --driver=docker

**Comment by medyagh** [comment]
@bobishere I haven't heard from you I have to close this isssue, please feel free to reopen when you are ready.
