### ISSUE TITLE
brew installed minikube: SIGILL: illegal instruction PC=0x406b3e0 m=0 sigcode=1 goroutine 1 

### ISSUE THREAD

**Issue by strus38** [kubernetes/minikube#7357]
Trying to launch minikube on macos 10.13.6, here are the steps I followed:
1) check system requirements:
`sysctl -a | grep -E --color 'machdep.cpu.features|VMX'
machdep.cpu.features: FPU VME DE PSE TSC MSR PAE MCE CX8 APIC SEP MTRR PGE MCA CMOV PAT PSE36 CLFSH DS ACPI MMX FXSR SSE SSE2 SS HTT TM PBE SSE3 DTES64 MON DSCPL **VMX** SMX EST TM2 SSSE3 CX16 TPR PDCM SSE4.1 SSE4.2 POPCNT
`
2) install dependencies:
`brew update && brew install kubectl && brew cask install docker virtualbox && brew install minikube
`
`go version
go version go1.14.1 darwin/amd64
`
3) run minikube
`minikube start --alsologtostderr --driver=virtualbox
SIGILL: illegal instruction
PC=0x406b3e0 m=0 sigcode=1
goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc00063f8f8 sp=0xc00063f8f0 pc=0x406b3e0
regexp.mergeRuneSets(0xc000176268, 0xc0001761a8, 0x30000000b, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/Cellar/go/1.14/libexec/src/regexp/onepass.go:193 +0x453 fp=0xc00063f9d0 sp=0xc00063f8f8 pc=0x411b2c3
regexp.makeOnePass.func1(0x4, 0xc000390c70, 0xe, 0xe, 0x1)
        /usr/local/Cellar/go/1.14/libexec/src/regexp/onepass.go:342 +0x45e fp=0xc00063fac8 sp=0xc00063f9d0 pc=0x4122bce
regexp.makeOnePass(0xc0005cf6b0, 0xc0005cf6b0)
        /usr/local/Cellar/go/1.14/libexec/src/regexp/onepass.go:448 +0x398 fp=0xc00063fbe0 sp=0xc00063fac8 pc=0x411c4c8
regexp.compileOnePass(0xc0005cf650, 0xc0005cf650)
        /usr/local/Cellar/go/1.14/libexec/src/regexp/onepass.go:500 +0x129 fp=0xc00063fc58 sp=0xc00063fbe0 pc=0x411c7a9
regexp.compile(0x568f44f, 0x33, 0xc0000000d4, 0x44c1171, 0x53a9ae0, 0xc0004aa500)
        /usr/local/Cellar/go/1.14/libexec/src/regexp/regexp.go:189 +0x106 fp=0xc00063fcf0 sp=0xc00063fc58 pc=0x411ca76
regexp.Compile(...)
        /usr/local/Cellar/go/1.14/libexec/src/regexp/regexp.go:133
regexp.MustCompile(0x568f44f, 0x33, 0x0)
        /usr/local/Cellar/go/1.14/libexec/src/regexp/regexp.go:309 +0x4b fp=0xc00063fd78 sp=0xc00063fcf0 pc=0x411d77b
github.com/google/go-cmp/cmp.init()
        /private/tmp/minikube-20200327-28156-c8swdi/.brew_home/go/pkg/mod/github.com/google/go-cmp@v0.3.1/cmp/options.go:238 +0x3a fp=0xc00063fda8 sp=0xc00063fd78 pc=0x51fa1ba
runtime.doInit(0x65be1c0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc00063fdd8 sp=0xc00063fda8 pc=0x40464aa
runtime.doInit(0x65b9660)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063fe08 sp=0xc00063fdd8 pc=0x4046477
runtime.doInit(0x65c9800)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063fe38 sp=0xc00063fe08 pc=0x4046477
runtime.doInit(0x65c3700)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063fe68 sp=0xc00063fe38 pc=0x4046477
runtime.doInit(0x65c4180)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063fe98 sp=0xc00063fe68 pc=0x4046477
runtime.doInit(0x65c9940)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063fec8 sp=0xc00063fe98 pc=0x4046477
runtime.doInit(0x65c62a0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063fef8 sp=0xc00063fec8 pc=0x4046477
runtime.doInit(0x65ca940)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063ff28 sp=0xc00063fef8 pc=0x4046477
runtime.doInit(0x65d6ac0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063ff58 sp=0xc00063ff28 pc=0x4046477
runtime.doInit(0x65c2da0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc00063ff88 sp=0xc00063ff58 pc=0x4046477
runtime.main()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc00063ffe0 sp=0xc00063ff88 pc=0x40398ae
runtime.goexit()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00063ffe8 sp=0xc00063ffe0 pc=0x4069b61
`
4) even simpler command don't work like:
`minikube status`
or
`minikube --version
Error: unknown flag: --version
See 'minikube --help' for usage.
SIGILL: illegal instruction
PC=0x10683a0 m=0 sigcode=1
goroutine 1 [running, locked to thread]:
runtime.asyncPreempt()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/preempt_amd64.s:8 fp=0xc0006ffe38 sp=0xc0006ffe30 pc=0x10683a0
math/rand.(*rngSource).Seed(0xc000145500, 0x1601c01fad7bef68)
        /usr/local/Cellar/go/1.14/libexec/src/math/rand/rng.go:226 +0x14e fp=0xc0006ffe40 sp=0xc0006ffe38 pc=0x10f948e
math/rand.NewSource(0x1601c01fad7bef68, 0x1f0e2a8, 0x39a1560)
        /usr/local/Cellar/go/1.14/libexec/src/math/rand/rand.go:46 +0x4a fp=0xc0006ffe68 sp=0xc0006ffe40 pc=0x10f804a
k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/rand.init()
        /private/tmp/kubernetes-cli-20200326-27263-1sjm487/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apimachinery/pkg/util/rand/rand.go:30 +0x35 fp=0xc0006ffe98 sp=0xc0006ffe68 pc=0x1e3a465
runtime.doInit(0x37b5ac0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5414 +0x8a fp=0xc0006ffec8 sp=0xc0006ffe98 pc=0x1044d8a
runtime.doInit(0x37c7640)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0006ffef8 sp=0xc0006ffec8 pc=0x1044d57
runtime.doInit(0x37b8740)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0006fff28 sp=0xc0006ffef8 pc=0x1044d57
runtime.doInit(0x37cc920)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0006fff58 sp=0xc0006fff28 pc=0x1044d57
runtime.doInit(0x37bc8e0)
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:5409 +0x57 fp=0xc0006fff88 sp=0xc0006fff58 pc=0x1044d57
runtime.main()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/proc.go:190 +0x1ce fp=0xc0006fffe0 sp=0xc0006fff88 pc=0x103810e
runtime.goexit()
        /usr/local/Cellar/go/1.14/libexec/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0006fffe8 sp=0xc0006fffe0 pc=0x1066b31
`
5) Even if I suspect a 'go' issue given the logs, you may have an idea.

Thanks.

**Comment by afbjorklund** [comment]
Probably a go bug, minikube (and kubernetes) suggests using 1.13.8 for now (1.13.9 soon).

https://github.com/golang/go/issues/37478

**Comment by butuzov** [comment]
> Yuck.
I think we broke Darwin/amd64 on pre-AVX chips. VZEROUPPER needs a CPU feature detection guard.
by [@randall77](https://github.com/golang/go/issues/37459#issuecomment-591180408)


I am also one of the affected users (using old MacPro with old Xeons on a board)

```bash
> brew install go 
> go version
go version go1.14.1 darwin/amd64

> brew reinstall --build-from-source minikube
> minikube version
minikube version: v1.9.0
commit: 48fefd43444d2f8852f527c78f0141b377b1e42a
```

`kubectl` can be downgraded with existing binaries. I am using `1.17.4` version.

**Comment by strus38** [comment]
Indeed, using:
`brew reinstall --build-from-source minikube`
seems to fix it!
I will keep testing more using:
`minikube version: v1.9.0
go: v1.14.1
Kubernetes: v1.18.0
`

**Comment by butuzov** [comment]
@strus38 `brew` has release 1.14.1 version few days, which doesn't have this issue.  While all essential software currently ae build with 1.13.8 I guess it's safe to update go via brew.

P/S/
kubectl you using also build with 1.14, you can download patched version build with 1.13.8, check this document (you looking for `kubernetes-client-darwin-amd64.tar.gz`)

https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.18.md#client-binaries

![image](https://user-images.githubusercontent.com/651824/78224895-fbd13480-74d1-11ea-8711-1f7f56be5a7f.png)

**Comment by strus38** [comment]
Thanks, it seems to work like a charm with this new kubectl version... at least for now.
I was able to start minikube and to enable the dashboard.
Thanks for the awesome support.

**Comment by afbjorklund** [comment]
Most likely `brew reinstall --build-from-source kubernetes-client` would fix `kubectl`.

Otherwise you can use `minikube kubectl`, and as a bonus the version will match the cluster...

**Comment by tstromberg** [comment]
Seems like this was addressed in the upstream brew. Closing.
