### ISSUE TITLE
registry-creds addon: Pulling images from private gcr repositiory does not work

### ISSUE THREAD

**Issue by ncri** [kubernetes/minikube#7378]
**Steps to reproduce the issue:** 

1. Deploy a workload that requires pulling pod images from the gcr
2. Run `minikube addons configure registry-creds`, use a service account with sufficient permissions
3. Run `minikube addons enable registry-creds`

**Full output of failed command:** 

After step 1 my pods have the ImagePullBackOff status as expected.
**After step 3 they still have ImagePullBackOff status**

Unfortuately this is hard to debug, as I have no clue why the image pull fails exactly.

**Full output of `minikube start` command used, if not already included:**

minikube start works fine

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
Hi @ncri. I wrote a tutorial about using images in AWS ECR. I know you said that you are trying to use a private GCR repo, but I thought I would still share the link here - https://minikube.sigs.k8s.io/docs/tutorials/configuring_creds_for_aws_ecr/

Take a look at the [caveats](https://minikube.sigs.k8s.io/docs/tutorials/configuring_creds_for_aws_ecr/#caveats) section.

> The service account token for the `default` service account in the `default` namespace is kept updated by the addon. If you create your deployment in a different namespace, the image pull will not work.

**Comment by prasadkatti** [comment]
- are you deploying your workload to the `default` namespace or some other namespace?
- Do you see a secret called `registry-creds-gcr` in `kube_system` - `kubectl get secret -o yaml -n kube-system registry-creds-gcr`
- If the secret exists, you can base64 decode and see if the data matches what you passed in to configure

**Comment by ncri** [comment]
Thanks @prasadkatti, for now I have given up on this, as I use locally built docker images mainly anyway. I can look again into it on the weekend. I did see the secrets and I use the default namespace. Also the secret seems correct, but i will double check that. I had tried out all kind of things for some hours already and just couldn't get it working. Wonder if there is an issue with the service account I assign, but I even tried one with project owner permissions and it didn't work.

**Comment by medyagh** [comment]
@ncri I am curious did you solve this issue ?

**Comment by priyawadhwa** [comment]
Hey @ncri I'm going to close this issue as some time has passed without any activity on it. Feel free to reopen at any time by including /reopen in your comment. Thank you!

**Comment by marcmmx** [comment]
I think there is a bug. I was running it also as documented, configured it, and enabled it. Sometimes it works sometimes not. Not sure what behind the scenes happens. But sometimes when it not runs, I run 2 or 3 times in a row`minikube addons enable registry-creds` and it works and pulls images from ECR. It between deleting the deployments of course.
