### ISSUE TITLE
add extended KVM2 installation documentation for redhat

### ISSUE THREAD

**Issue by mazzystr** [kubernetes/minikube#7405]
This documentation does not work for RHEL/CentOS 8 out of the box with fresh install including group "Virtualization Host".

It would be great if the following could be added...
* add a new user
* add new user to libvirt group
* edit /etc/libvirt/libvirtd.conf
* * set unix_sock_group = "libvirt"
* * set unix_sock_rw_perms = "0770"
* restart libvirtd

**Comment by tstromberg** [comment]
Currently we point to https://access.redhat.com/articles/1344173#Q_how-install-virtualization-packages

Is there a better doc for us to point to?

**Comment by mazzystr** [comment]
I had to do some a pretty large side quest to win the small items just to get started with minkube.  

The Red Hat doc is overwhelming and doesn't include the necessary items on the front page.  You have to go deep into the Administrators Guide.

I think we can do better to get people moving with minikube fast.

**Comment by medyagh** [comment]
we need to add a separate page for KVM docs, that we will link to from the getting started page. (not added to the start page)
