### ISSUE TITLE
docs don't mention how to enable feature gates

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7406]
https://minikube.sigs.k8s.io/docs/reference/configuration/kubernetes is missing mention of feature gates!

example:

`minikube start --feature-gates=EphemeralContainers=true`

**Comment by vikkyomkar** [comment]
I will raise a PR for this

**Comment by prasadkatti** [comment]
This should be closed. Fixed in #7443.

**Comment by medyagh** [comment]
this was closed
