### ISSUE TITLE
when i  running  pod i always get this error  

### ISSUE THREAD

**Issue by stevenbill** [kubernetes/minikube#7412]
E0404 11:53:27.814429   16255 portforward.go:340] error creating error stream for port 8080 -> 8080: Timeout occured

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
* The list of commands required to reproduce your error
* The full output of the command that had an error

Thank you for sharing your experience!
