### ISSUE TITLE
i have error  with Kubernetes in jenkins

### ISSUE THREAD

**Issue by stevenbill** [kubernetes/minikube#7414]
Error testing connection https://192.168.39.41:8443: java.nio.file.NoSuchFileException: /home/yousry/.minikube/ca.crt

![Screenshot from 2020-04-04 18-28-23](https://user-images.githubusercontent.com/29622827/78456167-63d67500-76a2-11ea-92f7-582866c35f80.png)

**Comment by tstromberg** [comment]
I'm not sure this has much to do with minikube. It seems that someone either moved minikube's files or deleted them outright. You can solve this by running `minikube start` again.

Please /reopen if this seems incorrect.

**Comment by stevenbill** [comment]
jenkins works on kubernetes pod

**Comment by stevenbill** [comment]
how can i reopen it

**Comment by fans3210** [comment]
I'm also having the same issue. If I set credentials to 'none' in the configurations, test connection would success. My jenkins runs on a pod deployed using helm.
For more details:
https://github.com/kubernetes/minikube/issues/7444
