### ISSUE TITLE
cloudshell addon for in-cluster web terminal

### ISSUE THREAD

**Issue by vorburger** [kubernetes/minikube#7419]
Would having a web-based terminal running in-cluster be a welcome addon to minikube?

[I toyed with](http://blog2.vorburger.ch/2020/04/open-cloud-web-terminal-shell.html) this in https://github.com/vorburger/cloudshell/ (not with minikube, yet; just the basis).

The workflow I imagine is `minikube addons enable cloudshell; minikube addons open cloudshell` and your browser would take you to a shell to runs "in-cluster" from where you could use `kubectl` (which would already be included in that shell) and what not.

It would also be neat if, after basics are there, one could develop code inside that shell, and build containers (ideally without [Using the Docker daemon](https://minikube.sigs.k8s.io/docs/tasks/docker_daemon/), but with building root less inside the cloudshell), push [to a registry in the cluster](https://minikube.sigs.k8s.io/docs/tasks/docker_registry/), and run.

@tstromberg

**Comment by tstromberg** [comment]
Is this effectively a web based version of `minikube ssh`, or is this something bigger?

FYI - the project name conflict with Google Cloud Shell is going to make this super confusing if made into a minikube addon. We'd probably need to call it vorburger-cloudshell or something else.
