### ISSUE TITLE
hyperkit driver should be happy with current minimum verison

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7422]
we have not updated the hyperkit driver in a year and we still each time we update minikube we redownload it and we ask user to give sudo persmiion for the user group.

currnetly with each new version of minikube, we re-download the hyperkit driver. even if the code for it was not touched.

the hyperkit driver udpate should not download the driver if the checksum is not changed.

simmilar to preload or other things in minikube that do not redownload.

**Comment by medyagh** [comment]
CC @josedonizetti

**Comment by tstromberg** [comment]
Here's another thought: this driver almost never requires updates anymore. Maybe once or twice a year.

How about encoding a minimum version and only upgrading it if necessary?

**Comment by medyagh** [comment]
we still like to do this

**Comment by medyagh** [comment]
@ilya-zuyev this is yours.
