### ISSUE TITLE
do not crash, when missplelled container runtime

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7426]
```
./out/minikube start --driver=docker --container-runtime=conatinerd
😄  minikube v1.9.2 on Darwin 10.13.6
✨  Using the docker driver based on user configuration

💣  Failed to generate config: unknown runtime type: "conatinerd"

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

in this case i misspelled containerd
and instead of crying and crashing and asking user to create an issue, we could say "conatinerd" is not a valid container-runtime,
the valid options are ...

**Comment by zerefwayne** [comment]
@medyagh I would like to work on this one.

**Comment by afbjorklund** [comment]
This should be doable, since we already have a hardcoded list of runtimes in there.

```go
runtimes := []string{"containerd", "crio", "docker"}
```

Arguably this could use a "registry", but then again that is also `broken` elsewhere.

So we could start by moving the list to a function ?

**Comment by medyagh** [comment]
@zerefwayne you can work on this.

please make sure to parse the conatainer-runtime flag from cobra
and then if it is not in the list that @afbjorklund mentioned, you should exit.WtihUsage and tell the user that they valid options are ...

**Comment by sunny-b** [comment]
@zerefwayne Are you still working on this? I see the PRs for this issue have been closed. I can take over if you don't have the time to finish them.
