### ISSUE TITLE
Heapster Addon?

### ISSUE THREAD

**Issue by BenHall** [kubernetes/minikube#743]
Should Minikube deploy Heapster for dashboard metrics? I expected to see the controllers and service files at https://github.com/kubernetes/minikube/tree/master/deploy/addons

**Comment by r2d4** [comment]
It's something we've been meaning to run as an addon but haven't gotten around to it.  

For anyone interested in adding heapster or a different addon to minikube, it should be fairly easy to add. You can take a look at #738 to see how the kube-dns addon was configured.

**Comment by BenHall** [comment]
Thanks @r2d4 - if I get chance this week I'll take a look as I would like it for the Katacoda + Minikube tutorials. I just wanted to make sure there wasn't a underlying reason it didn't exist.

**Comment by aaron-prindle** [comment]
I have not been able to get heapster working within minikube running Linux/Virtualbox.  I am following the instructions here:
[https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md)
with the following modifications to the yaml files:
Changing all LoadBalancer -> NodePort
Removing the line `kubernetes.io/cluster-service: 'true'`

When I attempt to launch the services, they all appear to be running but I am having issues with the services ever coming and and the containers communicating with each other.  I am able to login as admin to grafana via :3000 but the grafana-deployment.yaml setting for  INFLUXDB_HOST do not seem to work out of the box.  I am able to have grafana see influxdb by forwarding both ports and then setting them up manually.  The grafana U.I. however is never populated with data (all the graphs remain empty)
![grafana-1](https://cloud.githubusercontent.com/assets/1951658/20085689/9c0ed2e4-a51f-11e6-80f0-afafcadb148a.png)
![grafana-2](https://cloud.githubusercontent.com/assets/1951658/20085687/9c0cbac2-a51f-11e6-882f-47a8288daeaf.png)

If I go into influxdb U.I.  I see that no k8s database is created:Tin
![influxdb-1](https://cloud.githubusercontent.com/assets/1951658/20085688/9c0dde7a-a51f-11e6-926f-222aaa43b287.png)

In attempting to look into heapster logs I see the following:
https://gist.github.com/aaron-prindle/d2d2eea6d96d8649db84c0789282f69d

I believe DNS is working and that the monitoring-influxdb.kube-system.svc.cluster.local endpoint should come up but it never seems to:
```
aprindle@aprindle:~/heapster$ kubectl exec busybox -- nslookup monitoring-influxdb.kube-system.svc.cluster.local
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      monitoring-influxdb.kube-system.svc.cluster.local
Address 1: 10.0.0.110 monitoring-influxdb.kube-system.svc.cluster.local

```

I believe this is the heart of the issue but it is unclear to me why it is not working.  Any help would be appreciated thanks!

**Comment by aaron-prindle** [comment]
I was able to get this working using the yaml here:
https://github.com/luxas/kubernetes-on-arm/blob/master/addons/heapster.yaml
with some modifications.

**Comment by arun-gupta** [comment]
Using 0.12.2 release. The website https://github.com/kubernetes/minikube says `minikube addons list` should show:

```
- addon-manager: enabled
- dashboard: enabled
- kube-dns: enabled
- heapster: disabled
```

I only see:

```
minikube addons list
- dashboard: enabled
- kube-dns: enabled
- addon-manager: enabled
```

What is the discrepancy?

Will the blessed addon `yaml` be published?

**Comment by r2d4** [comment]
@arun-gupta #868

the PR has been merged and heapster will be an addon in the next release

**Comment by arun-gupta** [comment]
@r2d4 Got the following error:

```
865 > minikube start
Starting local Kubernetes cluster...
Downloading Minikube ISO
 36.00 MB / 36.00 MB [==============================================] 100.00% 0s
Kubectl is now configured to use the cluster.
865 > minikube addons list
- addon-manager: enabled
- dashboard: enabled
- kube-dns: enabled
- heapster: disabled
865 > minikube addons enable heapster
heapster was successfully enabled
865 > minikube addons open heapster
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Could not find finalized endpoint being pointed to by monitoring-grafana: Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
```

**Comment by r2d4** [comment]
I think that its just creating the container.  It may take a minute to pull the images and spin up the pods.  You can check the status with `kubectl get pods --namespace=kube-system`

**Comment by arun-gupta** [comment]
Will create a new bug, have a couple of issues on this.
