### ISSUE TITLE
containerd service is running on docker driver with docker run time

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7433]
While trying to figure out why minikube soft start on docker driver takes longer than VM (https://github.com/kubernetes/minikube/issues/7432)

I noticed on docker driver the containerd service is running but in VM its NOT !

on docker driver:
```
docker@minikube:~$ sudo systemctl status containerd
● containerd.service - containerd container runtime
   Loaded: loaded (/etc/systemd/system/containerd.service; disabled; vendor preset: enabled)
   Active: active (running) since Sun 2020-04-05 10:21:11 UTC; 44s ago
     Docs: https://containerd.io
```

on VM hyperkit:
```
● containerd.service - containerd container runtime
   Loaded: loaded (/usr/lib/systemd/system/containerd.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://containerd.io

```

**Comment by afbjorklund** [comment]
Since dockerd _depends_ on containerd, I think that this situation is normal ?

Previously it had custom docker-runc and docker-containerd, but not anymore.

**Comment by medyagh** [comment]
https://github.com/kubernetes/minikube/blob/792ca8ea3873e054d959f8ff2d4f28a16f6bcfbf/pkg/provision/ubuntu.go#L78
I just saw this that only for ubuntu provisioner (kic provisioner) we add bind to containerd and when I remove it it will get stuck in kubeadm init.


@afbjorklund  why in VM world we dont have containerd service running but only in kic world ?

also if docker service has to have containerd service running, then we need to disable the logic to DISABLE other container run times.... (because for docker it will disable containerd (which api server is running on it) that willi cause an un-needed False needsReset() 
that will make kic soft start (start and then start) very slow compared to VM

what do youu think we should do about it ?

**Comment by medyagh** [comment]
from minikube logs
```
I0405 04:32:31.291549   38471 kic_runner.go:91] Run: curl -sS -m 2 https://k8s.gcr.io/
I0405 04:32:31.293213   38471 kic_runner.go:91] Run: sudo systemctl is-active --quiet service containerd
I0405 04:32:31.519786   38471 kic_runner.go:91] Run: sudo systemctl stop -f containerd
```

**Comment by afbjorklund** [comment]
The VM has two _different_ containerd running:

*  `/run/docker/containerd/containerd.sock`

/usr/lib/systemd/system/docker.service
containerd --config /var/run/docker/containerd/containerd.toml --log-level info

* `/run/containerd/containerd.sock`

/usr/lib/systemd/system/containerd.service
/usr/bin/containerd --root /mnt/sda1/var/lib/containerd

That is, docker will start containerd itself if not running...

See [libcontainerd/supervisor/remote_daemon.go
](https://github.com/docker/docker-ce/blob/v19.03.8/components/engine/libcontainerd/supervisor/remote_daemon.go#L165_L226)

**Comment by afbjorklund** [comment]
The minikube docker.service has this configuration:

`ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=virtualbox --insecure-registry 10.96.0.0/12 `

The ubuntu docker.service has this configuration:

`ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock`

**Comment by tstromberg** [comment]
Can we close this because the mystery is solved?
