### ISSUE TITLE
[docs] Addons - Ingress DNS documentation is missing 

### ISSUE THREAD

**Issue by carlosjgp** [kubernetes/minikube#7438]
https://minikube.sigs.k8s.io/ingress-dns/readme

Returns a 404 and shows a "Not found" page

**Comment by afbjorklund** [comment]
Apparently **all** the addon links are broken, since it was moved to "site".

https://minikube.sigs.k8s.io/docs/tasks/addons/

There was an attempt to fix it in bd3956b8a6821f7f3b27d99865cc0b53a2ce800c, guess that it failed ?

```diff
@@ -20,10 +20,10 @@ minikube has a set of built-in addons that, when enabled, can be used within Kub
 * [nvidia-driver-installer](https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/nvidia-driver-installer/minikube)
 * [nvidia-gpu-device-plugin](https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/cmd/nvidia_gpu)
 * [logviewer](https://github.com/ivans3/minikube-log-viewer)
-* [gvisor](../deploy/addons/gvisor/README.md)
-* [storage-provisioner-gluster](../deploy/addons/storage-provisioner-gluster/README.md)
-* [helm-tiller](../deploy/addons/helm-tiller/README.md)
-* [ingress-dns](../deploy/addons/ingress-dns/README.md)
+* [gvisor](../../../gvisor/readme/)
+* [storage-provisioner-gluster](../../../storage-provisioner-gluster/readme)
+* [helm-tiller](../../../helm-tiller/readme)
+* [ingress-dns](../../../ingress-dns/readme)
 
 ## Listing available addons
 
```

The documents are available from https://github.com/kubernetes/minikube :

https://github.com/kubernetes/minikube/tree/master/deploy/addons/ingress-dns

**Comment by medyagh** [comment]
this should be an easy fix.
@prasadkatti recently made a PR to add alias to documentation pages

**Comment by carlosjgp** [comment]
> Apparently **all** the addon links are broken, since it was moved to "site".
> 
> https://minikube.sigs.k8s.io/docs/tasks/addons/
> 
> There was an attempt to fix it in [bd3956b](https://github.com/kubernetes/minikube/commit/bd3956b8a6821f7f3b27d99865cc0b53a2ce800c), guess that it failed ?
> 
> ```diff
> @@ -20,10 +20,10 @@ minikube has a set of built-in addons that, when enabled, can be used within Kub
>  * [nvidia-driver-installer](https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/nvidia-driver-installer/minikube)
>  * [nvidia-gpu-device-plugin](https://github.com/GoogleCloudPlatform/container-engine-accelerators/tree/master/cmd/nvidia_gpu)
>  * [logviewer](https://github.com/ivans3/minikube-log-viewer)
> -* [gvisor](../deploy/addons/gvisor/README.md)
> -* [storage-provisioner-gluster](../deploy/addons/storage-provisioner-gluster/README.md)
> -* [helm-tiller](../deploy/addons/helm-tiller/README.md)
> -* [ingress-dns](../deploy/addons/ingress-dns/README.md)
> +* [gvisor](../../../gvisor/readme/)
> +* [storage-provisioner-gluster](../../../storage-provisioner-gluster/readme)
> +* [helm-tiller](../../../helm-tiller/readme)
> +* [ingress-dns](../../../ingress-dns/readme)
>  
>  ## Listing available addons
>  
> ```
> 
> The documents are available from https://github.com/kubernetes/minikube :
> 
> https://github.com/kubernetes/minikube/tree/master/deploy/addons/ingress-dns

Thanks for pointing me to the documentation!

**Comment by sharifelgamal** [comment]
We still need to forward old URLs to the newer ones.

**Comment by Aut0R3V** [comment]
Hey anything that can be done here?

**Comment by medyagh** [comment]
@Aut0R3V this Documenation needs to be moved from the github repo to our website 
under this section
https://minikube.sigs.k8s.io/docs/handbook/addons/

**Comment by medyagh** [comment]
I would accept any contribution that moves this Doc to our website

**Comment by Aut0R3V** [comment]
So @medyagh just to make things clear, I have to move the readme at -  https://github.com/kubernetes/minikube/tree/master/deploy/addons/ingress-dns
to the addons section?

**Comment by JacekDuszenko** [comment]
I'll be able to make this quick change in docs /assign

**Comment by JacekDuszenko** [comment]
Moved the docs to site in #11572. Please feel free to review. Thanks!
