### ISSUE TITLE
pulling kic base image does not respect --image-repository or --image-mirror-country flags for CN registry mirrors

### ISSUE THREAD

**Issue by carvendy** [kubernetes/minikube#7447]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

minikube start --registry-mirror=https://registry.docker-cn.com --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=docker --alsologtostderr -v=8
</details>

**`minikube logs`命令的输出**： <details>
W0406 10:08:19.436876   13086 exit.go:101] Failed to start docker container. "minikube start" may fix it.: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=2200mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
: exit status 125

</details>

**使用的操作系统版本**：
ubuntu 18.04

**Comment by listenerri** [comment]
可能跟我的问题一样，我的解决方案是：
https://listenerri.com/2020/04/07/minikube-%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5/

**Comment by sharifelgamal** [comment]
The above workaround of building from source will work for now, we'll work on making kicbase available somewhere.

**Comment by tstromberg** [comment]
We don't maintain the CN registry mirror - and do not know how to contact those who do.

**Comment by chenzhikang** [comment]
我也遇到了，正在想办法解决

**Comment by chenzhikang** [comment]
> 可能跟我的问题一样，我的解决方案是：
> https://listenerri.com/2020/04/07/minikube-%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5/

你提供的解决方案很有价值。
但是我遇到的情况和你不大一样，我这里是确实连不上外网，本次docker images看不到kicbase镜像；

**Comment by chenzhikang** [comment]
> 可能跟我的问题一样，我的解决方案是：
> https://listenerri.com/2020/04/07/minikube-%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5/

你好，你分享的经验很有价值！

结合我这边操作发现：
1：我这直接pull下来的镜像Digest是没问题的【这一点看到你那边pull下来就丢了Digest，感觉比较奇怪】
2：我这边是在docker tag时发现，new image的Digest确实丢了；【也就是说直接pull下载才会加上Digest，tag或其它操作就将Digest丢弃了】

供参考，握手！

**Comment by chenzhikang** [comment]
终于算是搞定这个问题了，成功启动minikube的docker驱动的集群，如图：
![image](https://user-images.githubusercontent.com/9971827/79852979-06f4f180-83fa-11ea-92e0-91b53167bbd7.png)

**Comment by lubocheng** [comment]
官方已推镜像,大家可以试试~~~
https://github.com/AliyunContainerService/minikube/issues/17

**Comment by chenzhikang** [comment]
> 官方已推镜像,大家可以试试~~~
> [AliyunContainerService#17](https://github.com/AliyunContainerService/minikube/issues/17)

 https://yq.aliyun.com/articles/221687
链接404呢？

**Comment by lubocheng** [comment]
> > 官方已推镜像,大家可以试试~~~
> > [AliyunContainerService#17](https://github.com/AliyunContainerService/minikube/issues/17)
> 
> https://yq.aliyun.com/articles/221687
> 链接404呢？
> @lubocheng

![image](https://user-images.githubusercontent.com/3746672/80897111-0fb5c380-8d28-11ea-8239-8e86ef5352d4.png)
链接官方自己删除了...可能过些日子就好了

**Comment by lubocheng** [comment]
```text
minikube start --driver='docker' --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10 --image-mirror-country='cn' --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --addons=ingress --addons=dashboard
```

**Comment by rockxsj** [comment]
换成kind轻松跑起来了一个本地k8s集群，这个问题等维护者解决了关闭吧。

**Comment by sigmaol** [comment]
使用新的1.10.0版本指定--base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10
可以正常启动了。

**Comment by spartucus** [comment]
> 使用新的1.10.0版本指定--base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10
> 可以正常启动了。

好像还是不行：
```
oc@ocserver:~$ minikube start --vm-driver docker --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10 
😄  minikube v1.10.1 on Ubuntu 18.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E0514 11:17:54.137973    3798 cache.go:129] Error downloading kic artifacts:  getting remote image: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:50986->127.0.0.53:53: i/o timeout
🤷  docker "minikube" container is missing, will recreate.
E0514 11:17:54.383291    3798 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:


stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
stdout:

stderr:
Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:36426->127.0.0.53:53: i/o timeout.
See 'docker run --help'.

🤷  docker "minikube" container is missing, will recreate.
E0514 11:19:45.275536    3798 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:


stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
😿  Failed to start docker container. "minikube start" may fix it: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
stdout:

stderr:
Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:60680->127.0.0.53:53: i/o timeout.
See 'docker run --help'.


💣  error provisioning host: Failed to start host: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
stdout:

stderr:
Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:60680->127.0.0.53:53: i/o timeout.
See 'docker run --help'.


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by sigmaol** [comment]
> > 使用新的1.10.0版本指定--base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10
> > 可以正常启动了。
> 
> 好像还是不行：
> 
> ```
> oc@ocserver:~$ minikube start --vm-driver docker --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10 
> 😄  minikube v1.10.1 on Ubuntu 18.04
> ✨  Using the docker driver based on existing profile
> 👍  Starting control plane node minikube in cluster minikube
> 🚜  Pulling base image ...
> E0514 11:17:54.137973    3798 cache.go:129] Error downloading kic artifacts:  getting remote image: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:50986->127.0.0.53:53: i/o timeout
> 🤷  docker "minikube" container is missing, will recreate.
> E0514 11:17:54.383291    3798 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
> stdout:
> 
> 
> stderr:
> Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
> 🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
> 🤦  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
> stdout:
> 
> stderr:
> Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
> docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:36426->127.0.0.53:53: i/o timeout.
> See 'docker run --help'.
> 
> 🤷  docker "minikube" container is missing, will recreate.
> E0514 11:19:45.275536    3798 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
> stdout:
> 
> 
> stderr:
> Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
> 🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
> 😿  Failed to start docker container. "minikube start" may fix it: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
> stdout:
> 
> stderr:
> Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
> docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:60680->127.0.0.53:53: i/o timeout.
> See 'docker run --help'.
> 
> 
> 💣  error provisioning host: Failed to start host: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
> stdout:
> 
> stderr:
> Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
> docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:60680->127.0.0.53:53: i/o timeout.
> See 'docker run --help'.
> 
> 
> 😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
> 👉  https://github.com/kubernetes/minikube/issues/new/choose
> ```

试试这个，我正常启动了
minikube start --registry-mirror=https://registry.docker-cn.com --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=docker --alsologtostderr -v=8 --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10

**Comment by spartucus** [comment]
@sigmaol 这样可以了，多谢~

**Comment by lubocheng** [comment]
> @sigmaol 这样可以了，多谢~

不行...😪

**Comment by spartucus** [comment]
@lubocheng 不清楚跟网络有没有关系。我在移动网络下，就会失败。换成联通就好了。

**Comment by medyagh** [comment]
@carvendy @spartucus @lubocheng @sigmaol @lubocheng @chenzhikang 

in latest version of minikube (v1.11.0) we add the kicbase image to docker hub, do you mind trying the latest version and see if that works for you without adding any tricks?

this should just work
download latest minikube verison: https://minikube.sigs.k8s.io/docs/start/

minikube delete
minikube start --driver=docker

here is the image on docker hub:
https://hub.docker.com/r/kicbase/stable

--- google translate:


在最新版本的minikube（v1.11.0）中，我们将kicbase映像添加到了docker hub，您是否介意尝试最新版本并查看它是否对您有效而未添加任何技巧？

这应该工作
下载最新的minikube版本：https://minikube.sigs.k8s.io/docs/start/

minikube删除
minikube start-驱动程序= docker

这是Docker Hub上的图像：
https://hub.docker.com/r/kicbase/stable

**Comment by medyagh** [comment]
having said all of that, the docker driver should still respect the registory mirrors, and this would duplicate of https://github.com/kubernetes/minikube/issues/7915

**Comment by spartucus** [comment]
I tried latest version(v1.11.0) on ubuntu18.04, minikube started and downloaded images successfully! Everything looks good to me, well done!

**Comment by medyagh** [comment]
@spartucus glad to see that was fixed, in v1.11.0 we pushed a fallback image to dockerhub that probably fixed it.
we still need to respect the registrry mirrors for the base image, 

so if user specificies a mirror, we should download the base image from that mirror.

**Comment by danieltanfh95** [comment]
> > > 使用新的1.10.0版本指定--base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10
> > > 可以正常启动了。
> > 
> > 
> > 好像还是不行：
> > ```
> > oc@ocserver:~$ minikube start --vm-driver docker --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10 
> > 😄  minikube v1.10.1 on Ubuntu 18.04
> > ✨  Using the docker driver based on existing profile
> > 👍  Starting control plane node minikube in cluster minikube
> > 🚜  Pulling base image ...
> > E0514 11:17:54.137973    3798 cache.go:129] Error downloading kic artifacts:  getting remote image: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:50986->127.0.0.53:53: i/o timeout
> > 🤷  docker "minikube" container is missing, will recreate.
> > E0514 11:17:54.383291    3798 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
> > stdout:
> > 
> > 
> > stderr:
> > Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
> > 🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
> > 🤦  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
> > stdout:
> > 
> > stderr:
> > Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
> > docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:36426->127.0.0.53:53: i/o timeout.
> > See 'docker run --help'.
> > 
> > 🤷  docker "minikube" container is missing, will recreate.
> > E0514 11:19:45.275536    3798 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
> > stdout:
> > 
> > 
> > stderr:
> > Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
> > 🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
> > 😿  Failed to start docker container. "minikube start" may fix it: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
> > stdout:
> > 
> > stderr:
> > Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
> > docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:60680->127.0.0.53:53: i/o timeout.
> > See 'docker run --help'.
> > 
> > 
> > 💣  error provisioning host: Failed to start host: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=3900mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10: exit status 125
> > stdout:
> > 
> > stderr:
> > Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
> > docker: Error response from daemon: Get https://docker.pkg.github.com/v2/: dial tcp: lookup docker.pkg.github.com on 127.0.0.53:53: read udp 127.0.0.1:60680->127.0.0.53:53: i/o timeout.
> > See 'docker run --help'.
> > 
> > 
> > 😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
> > 👉  https://github.com/kubernetes/minikube/issues/new/choose
> > ```
> 
> 试试这个，我正常启动了
> minikube start --registry-mirror=https://registry.docker-cn.com --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --vm-driver=docker --alsologtostderr -v=8 --base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10

This works!

**Comment by priyawadhwa** [comment]
It looks like this is working with registry mirrors as well! I'm going to go ahead and close this issue; but if anyone is still seeing errors please reopen by including /reopen in your comment.

**Comment by febzhang** [comment]
This is still an issue.
```
$ minikube version
minikube version: v1.23.2
commit: 0a0ad764652082477c00d51d2475284b5d39ceed
```

**Comment by huxulm** [comment]
> This is still an issue.
> 
> ```
> $ minikube version
> minikube version: v1.23.2
> commit: 0a0ad764652082477c00d51d2475284b5d39ceed
> $ minikube start --image-mirror-country=cn --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
> * minikube v1.23.2 on Centos 7.9.2009
> * Using the docker driver based on existing profile
> * Starting control plane node minikube in cluster minikube
> * Pulling base image ...
> * Restarting existing docker container for "minikube" ...
> * Found network options:
>   - HTTP_PROXY=http://192.168.9.9:8080/
>   - HTTPS_PROXY=https://192.168.9.9:8080/
>   - NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/12
> ! This container is having trouble accessing https://k8s.gcr.io
> * To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
> * Preparing Kubernetes v1.22.2 on Docker 20.10.8 ...
>   - env HTTP_PROXY=http://192.168.9.9:8080/
>   - env HTTPS_PROXY=https://192.168.9.9:8080/
>   - env NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/12
> * Verifying Kubernetes components...
>   - Using image kubernetesui/dashboard:v2.3.1
>   - Using image kubernetesui/metrics-scraper:v1.0.7
>   - Using image gcr.io/k8s-minikube/storage-provisioner:v5
> * Enabled addons: storage-provisioner, default-storageclass, dashboard
> * kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
> * Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
> ```
For my situation is, first minikube pull from gcr.io but failed, then it trys to pull from docker.io.
see below:
```

I0928 19:47:51.046317    4507 cache.go:180] failed to download gcr.io/k8s-minikube/kicbase:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de, will try fallback image if available: getting remote image: Get "https://gcr.io/v2/": dial tcp 74.125.204.82:443: i/o timeout
I0928 19:47:51.046372    4507 image.go:75] Checking for docker.io/kicbase/stable:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de in local docker daemon
I0928 19:47:51.296415    4507 cache.go:146] Downloading docker.io/kicbase/stable:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de to local cache
I0928 19:47:51.296766    4507 image.go:59] Checking for docker.io/kicbase/stable:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de in local cache directory
I0928 19:47:51.296831    4507 image.go:119] Writing docker.io/kicbase/stable:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de to local cache
    > index.docker.io/kicbase/sta...: 299.15 MiB / 355.40 MiB  84.17% 679.12 Ki
```

**Comment by febzhang** [comment]
> > This is still an issue.
> > ```
> > $ minikube version
> > minikube version: v1.23.2
> > commit: 0a0ad764652082477c00d51d2475284b5d39ceed
> > $ minikube start --image-mirror-country=cn --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
> > * minikube v1.23.2 on Centos 7.9.2009
> > * Using the docker driver based on existing profile
> > * Starting control plane node minikube in cluster minikube
> > * Pulling base image ...
> > * Restarting existing docker container for "minikube" ...
> > * Found network options:
> >   - HTTP_PROXY=http://192.168.9.9:8080/
> >   - HTTPS_PROXY=https://192.168.9.9:8080/
> >   - NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/12
> > ! This container is having trouble accessing https://k8s.gcr.io
> > * To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
> > * Preparing Kubernetes v1.22.2 on Docker 20.10.8 ...
> >   - env HTTP_PROXY=http://192.168.9.9:8080/
> >   - env HTTPS_PROXY=https://192.168.9.9:8080/
> >   - env NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,192.168.0.0/12
> > * Verifying Kubernetes components...
> >   - Using image kubernetesui/dashboard:v2.3.1
> >   - Using image kubernetesui/metrics-scraper:v1.0.7
> >   - Using image gcr.io/k8s-minikube/storage-provisioner:v5
> > * Enabled addons: storage-provisioner, default-storageclass, dashboard
> > * kubectl not found. If you need it, try: 'minikube kubectl -- get pods -A'
> > * Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
> > ```
> 
> For my situation is, first minikube pull from gcr.io but failed, then it trys to pull from docker.io. see below:
> 
> ```
> 
> I0928 19:47:51.046317    4507 cache.go:180] failed to download gcr.io/k8s-minikube/kicbase:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de, will try fallback image if available: getting remote image: Get "https://gcr.io/v2/": dial tcp 74.125.204.82:443: i/o timeout
> I0928 19:47:51.046372    4507 image.go:75] Checking for docker.io/kicbase/stable:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de in local docker daemon
> I0928 19:47:51.296415    4507 cache.go:146] Downloading docker.io/kicbase/stable:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de to local cache
> I0928 19:47:51.296766    4507 image.go:59] Checking for docker.io/kicbase/stable:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de in local cache directory
> I0928 19:47:51.296831    4507 image.go:119] Writing docker.io/kicbase/stable:v0.0.27@sha256:89b4738ee74ba28684676e176752277f0db46f57d27f0e08c3feec89311e22de to local cache
>     > index.docker.io/kicbase/sta...: 299.15 MiB / 355.40 MiB  84.17% 679.12 Ki
> ```

I tried Windows 10 which behind the same enterprise proxy, with or without --image-mirror-country=cn both works.

```
C:\Users\zhangx>minikube start --image-mirror-country=cn --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
😄  Microsoft Windows 10 Pro 10.0.18362 Build 18362 上的 minikube v1.23.2
✨  自动选择 docker 驱动
✅  正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > registry.cn-hangzhou.aliyun...: 27.28 MiB / 355.40 MiB  7.68% 26.99 KiB p^C
C:\Users\zhangxj3>minikube delete --all=true
🔥  正在删除 docker 中的“minikube”…
💀  Removed all traces of the "minikube" cluster.
🔥  成功删除所有配置文件

C:\Users\zhang>minikube start
😄  Microsoft Windows 10 Pro 10.0.18362 Build 18362 上的 minikube v1.23.2
✨  自动选择 docker 驱动
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > index.docker.io/kicbase/sta...: 27.27 MiB / 355.40 MiB  7.67% 417.39 KiB
    > index.docker.io/kicbase/sta...: 0 B [______________________] ?% ? p/s 38s
    > gcr.io/k8s-minikube/kicbase...: 355.40 MiB / 355.40 MiB  100.00% 759.64 K
```

**Comment by sharifelgamal** [comment]
This should be fixed.
