### ISSUE TITLE
Figure out automated CNI for multi-node clusters

### ISSUE THREAD

**Issue by sharifelgamal** [kubernetes/minikube#7459]
Currently multinode clusters need a CNI applied manually to make `minikube service` work. We should decide what CNI will be the canonical CNI choice to apply automatically for multinode and actually apply it on start or add node.

**Comment by tstromberg** [comment]
Here's my modest proposal:

A `--cni` flag that defaults to `kindnet` (assuming it works properly). If not, there is `flannel`.

 Eventually we could add support for other CNI's, fulfilling a roadmap item for clear documentation around CNI's.

**Comment by tstromberg** [comment]
@sharifelgamal - if you could use the help still on this, I'm happy to lend a hand.

**Comment by sharifelgamal** [comment]
yeah help would be very much appreciated
