### ISSUE TITLE
fail to start on win 10 - error reading 

### ISSUE THREAD

**Issue by gadieichhorn** [kubernetes/minikube#747]
> minikube version
minikube version: v0.12.0

> minikube start
Starting local Kubernetes cluster...
E1024 19:31:14.996978   12084 start.go:90] Error starting host: Error attempting to cache minikube iso from url: Error copying temp iso file to destination: rename C:\Users\gadei\.minikube\cac
he\iso\.tmp-minikube-0.7.iso329963535 C:\Users\gadei\.minikube\cache\iso\minikube-0.7.iso: The process cannot access the file because it is being used by another process.. Retrying.
E1024 19:31:14.999980   12084 start.go:96] Error starting host:  Error attempting to cache minikube iso from url: Error copying temp iso file to destination: rename C:\Users\gadei\.minikube\ca
che\iso\.tmp-minikube-0.7.iso329963535 C:\Users\gadei\.minikube\cache\iso\minikube-0.7.iso: The process cannot access the file because it is being used by another process.

I tried to reboot and delete the temp files under the .minikube location but still same error

**Comment by r2d4** [comment]
Looks related to https://github.com/kubernetes/minikube/pull/696. Do you have a minikube VM running?  Can you try to `minikube delete`?

**Comment by rhuss** [comment]
I have the very same issue, even when I removed `.minikube` completely before. I'm using `--vm-driver=virtualbox` btw. After this error occured the `.minikube` can be deleted without problems, so there is no other process locking the .iso then.

**Comment by gadieichhorn** [comment]
> minikube delete
Deleting local Kubernetes cluster...
Errors occurred deleting machine:  Error deleting host: minikube: Host does not exist: "minikube"

I also tried this:

> minikube start --kubernetes-version="v1.4.0" --vm-driver="virtualbox"  --show-libmachine-logs --alsologtostderr

And yes, I can delete the .minikube folder, nothing is holding any processes.

I have latest docker and VirtualBox both running fine.

Do I need to have kubectrl to run minikube?

**Comment by ereOn** [comment]
I also have the same issue on Windows 10.

Nothing prevents me from deleting the `.minikube` folder and its content but it doesn't solve the problem. No minikube VM exists in Hyper-V either.

This is puzzling.

**Comment by raeesbhatti** [comment]
I faced same issue when I tried to use latest v0.12.0 release but reverting to v0.11.0 seems to have fixed this issue. But like @ereOn I'm also having an issues connecting to minikube IP.

**Comment by rhuss** [comment]
@jimmidyson  I'm not very fluent in Go but could it be that the `tempFile`  must be closed after the [copy](https://github.com/jimmidyson/minikube/blob/4a4a66b0173a9dda67aa7a927a2e0637d8a04437/pkg/minikube/cluster/cluster.go#L363) before the file can be renamed ?

**Comment by jimmidyson** [comment]
Fixed in #756

**Comment by jimmidyson** [comment]
@dlorenc @r2d4 Can we get a release out with the fix in #756 as this is affecting Windows users?

**Comment by r2d4** [comment]
Yeah I think a 0.12.1 makes sense
