### ISSUE TITLE
minikube : no resources found under namespace metallb-system

### ISSUE THREAD

**Issue by anjyed** [kubernetes/minikube#7473]
**Steps to reproduce the issue:**
Not able to install metalLB on minikube 
1. kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/namespace.yaml

          namespace/metallb-system created

2. kubectl apply -f https://raw.githubusercontent.com/google/metallb/v0.9.3/manifests/metallb.yaml

          podsecuritypolicy.policy/controller created
          podsecuritypolicy.policy/speaker created
          serviceaccount/controller created
          serviceaccount/speaker created
          clusterrole.rbac.authorization.k8s.io/metallb-system:controller created
          clusterrole.rbac.authorization.k8s.io/metallb-system:speaker created
          role.rbac.authorization.k8s.io/config-watcher created
          role.rbac.authorization.k8s.io/pod-lister created
          clusterrolebinding.rbac.authorization.k8s.io/metallb-system:controller created
          clusterrolebinding.rbac.authorization.k8s.io/metallb-system:speaker created
          rolebinding.rbac.authorization.k8s.io/config-watcher created
          rolebinding.rbac.authorization.k8s.io/pod-lister created
          daemonset.apps/speaker created
          deployment.apps/controller created

**Full output of failed command:** 
Eventhough I have applied the yml file and the output show no error. I am not able to list the pods under metallb-system.

3. kubectl get pods -n metallb-system

               No resources found in metallb-system namespace.

**Comment by medyagh** [comment]
do you mind sharing what driver do you use and what OS ?

**Comment by tstromberg** [comment]
The output of:

* `kubectl get po -A`
* `minikube logs`

would be helpful.

**Comment by medyagh** [comment]
@anjyed  I haven't heard from you. do you still need help?

**Comment by medyagh** [comment]
@anjyed I haven't heard from you

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
