### ISSUE TITLE
Spell check of Restarting

### ISSUE THREAD

**Issue by navdeepblock8** [kubernetes/minikube#7474]
**Steps to reproduce the issue:** 

1.Run minikub start command
2. Automatic commands will run to start minikub in Virtual Machine
3. 4th command will have a misspelled ‘Restarting’.

**Full output of failed command:** Retarting existing virtualbox VM for “minikub”...

</details>
![06E68E09-4C3C-439F-8B58-B5F3576BF80B](https://user-images.githubusercontent.com/59728111/78669731-55829600-78fa-11ea-8f96-a2a3dedae2bd.jpeg

**Comment by afbjorklund** [comment]
Please update your minikube, this was fixed in 3f74cb61ef6e2bc4f323bab71508e96f14f50b9e (`v1.9.1`)
