### ISSUE TITLE
Minikube profile crashes my default certificates

### ISSUE THREAD

**Issue by masalinas** [kubernetes/minikube#7488]
**Los comandos necesarios para reproducir la incidencia**:
When create a new minikube profile like this:

[minikube start -p minikube-devel](url)

The profile is correctly created but the client.crt, client.key and other default security files are crashes with the new minikube profile certificates

If I comeback to the default profile kubernetes the kubectl could not connect to the default minikube profile.

How could I recover the old certificates, or How could I configure the old VM profile to use the new certicates of the new profile minikube-devel?

**La versión del sistema operativo que utilizaste**:
Ubuntu 16.04

**Comment by tstromberg** [comment]
Hola @masalinas

Unas cuantas preguntas:

* ¿Con qué versión de minikube es esto?
* ¿Puedes compartir la salida de los comandos que se bloquean?
* Parece que debería poder usar `kubectl --context minikube-devel` para hablar con el otro clúster. No es ese el caso?

¡Gracias por compartir su experiencia!

**Comment by masalinas** [comment]
I',m using the minikube version is 1.7.3 and Oracle VirtualBox version 5.2.2 on Ubuntu 16.04 LTS

I removed all the minikube contexts, remove the VMs and .minikube folder and start again creating two new contexts from scratch:

  - The first one with the name: minikube-mefasa
  - The second one with the name: minikube-devel

Now I don't have any problem, I could jump from one context to the other with any problem. It's strange!. I supouse that I'm using the same security certificates for the both minikube contexts.

So I close the ticket.
