### ISSUE TITLE
Handbook: "Configuration" page should link to "config" command doc

### ISSUE THREAD

**Issue by mat-tia** [kubernetes/minikube#7493]
In "Listing config properties" getting rid of the properties/ config items list seems a bit of a regression to me. I understand that that will change with each new (possibly minor) version of minikube, but it would be great to not just have a list, but also have a short explanation of what each property does, as there's no additional information of what the possible options are. even just linking to the files where the current options are defined (as the kubernetes doc does in some places) would be handy.

This would also allow people to understand if any properties have been disabled in newer minikube versions

**Comment by tstromberg** [comment]
https://minikube.sigs.k8s.io/docs/commands/config/ has the list, but you are correct: it does not yet reveal any documentation about what the options do.
