### ISSUE TITLE
docker-env: "docker run" and "docker rm" hangs

### ISSUE THREAD

**Issue by mcandre** [kubernetes/minikube#7497]
**Steps to reproduce the issue:** 

1. `eval "$(minikube docker-env)"`
2. Use `docker run`, `docker ps -a` to deploy a container and get a container ID.
3. Execute `docker rm -f <container ID>`

For example, deploy an HTTP echo server this way. However, the echo server does not actually bind to localhost:8080 as far as the host observes.

At this point, many things freeze up. The `docker rm -f`... stalls. Control+C (SIGINT) is unable to kill this. `minikube docker-env` also stalls.

Fortunately, `minikube delete` is able to temporarily fix the corrupt cluster, until you repeat the steps.

In fact, even the `docker rm -f`... continues to stall after `minikube delete` completes, so you'll have to manually close the shell session and launch a new one.

```console
$ docker --version
Docker version 19.03.8, build afacb8b

$ minikube version
minikube version: v1.8.2
commit: eb13446e786c9ef70cb0a9f85a633194e62396a1

$ system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: macOS 10.15.4 (19E266)
```

Some good news: I repeated the steps on Windows (Git Bash). As before, host curl was unable to bind to the microservice on 8080. But nothing freezes up, and Control+C is able to terminate the `docker run`. Maybe this is a Mac thing? Just a Catalina thing? Just a static GNU Linux binary on HyperKit thing?

Curious how native Command Prompt and native PowerShell sessions behave. I'd also like to try WSL but I don't have a functioning WSL host at the moment. Also curious about Linux hosts.

**Comment by tstromberg** [comment]
I wasn't able to duplicate this on macOS catalina:

```
$ docker rm -f b66589f19e1c
b66589f19e1c
```

My `docker run` session aborted fairly quickly, and `minikube delete` worked. Can you try upgrading to minikube v1.9.3 and then provide more exact reproduction commands?

Two things I would like to see are:

* an example image to run and the `minikube start` command used

I suspect it's just a Docker quirk, but it would be nice to have something I can reproduce first.

**Comment by medyagh** [comment]
@mcandre are you still having this issue ? do you mind sharing what driver and verison of minikube are you using ?

**Comment by sharifelgamal** [comment]
@mcandre I'm going to go ahead and close this since we haven't heard from you in awhile and do not have a good way to reproduce the issue. If you still need help, feel free to reopen with the details @tstromberg requested above.
