### ISSUE TITLE
Don't require imagePullPolicy: "Never" for Docker Desktop images

### ISSUE THREAD

**Issue by mcandre** [kubernetes/minikube#7499]
Can we improve the default behavior for minikube deployments, so that images that arise from Docker Desktop integration automatically successfully pull and run out of the box?

As a workaround, I'm configuring my containers with `imagePullPolicy: "Never"`, but that litters my deployment YAML files with minikube-specific junk, making it harder to share YAML configurations between development and production environments.

**Comment by sharifelgamal** [comment]
You can push to a public registry or to a private registry with addon creds to make this work without adding a policy to your yaml file.

**Comment by priyawadhwa** [comment]
Hey @mcandre it might be more useful to use `imagePullPolicy: ifNotPresent`? It still adds a line to your yaml, but then you should be able to use the same yaml for dev and production. 

Otherwise, I don't think there's a better workaround for this.

**Comment by tstromberg** [comment]
Do you mind sharing the output of `minikube version`?

imagePullPolicy is not explicitly configured for minikube - it uses the same defaults as Kubernetes. At least in the short-term, we have no intent of diverging behaviors, as it would be too confusing for users. 

I'd like to hear  more about the behavior you are seeing versus the behavior you expect.

**Comment by medyagh** [comment]
this is more a kubernetes question, if u dont specify that kuberntets will pull the image from public
