### ISSUE TITLE
clarify error message with driver none

### ISSUE THREAD

**Issue by nestoralonso** [kubernetes/minikube#7501]
**Steps to reproduce the issue:** 

1. minikube start --driver=none
2. minikube fails to start (which is expected)
3. minikube suggest a wrong command to fix the issue:
```
💣 The "none" driver requires root privileges. Please run minikube using 'sudo minikube --driver=none'.
```
The error message lacks the necessary parameter **start** after minikube, it should print like this:
```
💣The "none" driver requires root privileges. Please run minikube using 'sudo minikube start--driver=none'
```

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
✨  Using the none driver based on existing profile

❗  'none' driver reported an issue: the 'none' driver must be run as the root user
💡  Suggestion: For non-root usage, try the newer 'docker' driver

💣  The "none" driver requires root privileges. Please run minikube using 'sudo minikube --driver=none'.

**Comment by afbjorklund** [comment]
The thing here is that you need to run _every_ minikube command that way.

This is because root will end up owning all the files that are getting created...

Basically this is a bug. (#3760)

Sudo should **not** be required, instead minikube should add `sudo` where needed.
