### ISSUE TITLE
minikube coredns doesn't work

### ISSUE THREAD

**Issue by zehuaiWANG** [kubernetes/minikube#7512]
hey, guys, I have a problem and wonder if anyone here could help me. I installed a minikube in my server, and I create a pod with `clusterFirst` dns, but when I `curl` domain name in the container, it will timeout and then failed. However, it can `curl` successfully in the server.

```
# minikube version
minikube version: v1.9.2
```

here is my coredns configmap:
```
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  creationTimestamp: "2020-04-08T03:21:00Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data: {}
    manager: kubeadm
    operation: Update
    time: "2020-04-08T03:21:00Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:Corefile: {}
    manager: kubectl
    operation: Update
    time: "2020-04-08T08:51:01Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "57049"
  selfLink: /api/v1/namespaces/kube-system/configmaps/coredns
  uid: 7379d8e2-b332-404e-9a40-9d1ec920151f
```

**Comment by medyagh** [comment]
can u plz probide your start args and your versions and os
and also which container run time?

and also provide me what u expect to see and what error do u get?

**Comment by aasmall** [comment]
try the patch command here: https://github.com/kubernetes/minikube/issues/8055

**Comment by zehuaiWANG** [comment]
I have solved the problem. The reason for this problem is that my host has env settings and can access some external addresses, but there is no such env setting in minikube, so the same URL can be accessed on the host and minihub can't. Thank you, and I think we can close this issue. @priyawadhwa @aasmall @medyagh

**Comment by priyawadhwa** [comment]
@zehuaiWANG great to hear!

**Comment by srvmsr** [comment]
Also in some cases , you can edit your core dns conf file to point to a public dns instead of local resolve.conf and restart core dns pods
a example core dns conf file 

{
	"Corefile": ".:53 {
		    errors
		    log
		    health {
		       lameduck 5s
		    }
		    ready
		    kubernetes cluster.local in-addr.arpa ip6.arpa {
		       pods insecure
		       fallthrough in-addr.arpa ip6.arpa
		       ttl 30
		    }
		    prometheus :9153
		    loop
		    reload
		    loadbalance
		    **forward . 8.8.8.8 8.8.4.4**
		}
		"
}
