### ISSUE TITLE
"minikube start --driver=docker" is not working

### ISSUE THREAD

**Issue by noorulhud** [kubernetes/minikube#7534]
**Steps to reproduce the issue:** 

1. minikube delete
2. minikube start --driver=docker
3. 
![Screenshot from 2020-04-08 19-05-17](https://user-images.githubusercontent.com/63110809/78844915-cdb98c00-79cc-11ea-87e5-10a0f429e0ed.png)

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@noorulhud  thank you for creating this issue, do u mind making sure our docker service is running?

what is the output of docker info ?
or docker ps ?

**Comment by noorulhud** [comment]
I run the commands as below:

![Screenshot from 2020-04-09 12-38-46](https://user-images.githubusercontent.com/63110809/78924289-26396980-7a5f-11ea-9bcf-fa35b7d3944a.png)

**Comment by afbjorklund** [comment]
See https://docs.docker.com/engine/install/linux-postinstall/

**Comment by noorulhud** [comment]
> > I run the commands as below:
> 
> You ran the docker command with sudo ?
> 
> See https://docs.docker.com/engine/install/linux-postinstall/

How to apply this document and how much?

**Comment by noorulhud** [comment]
> > I run the commands as below:
> 
> You ran the docker command with sudo ?
> 
> See https://docs.docker.com/engine/install/linux-postinstall/



> > > I run the commands as below:
> > 
> > 
> > You ran the docker command with sudo ?
> > See https://docs.docker.com/engine/install/linux-postinstall/
> 
> How to apply this document and how much?

It works, thank you very much...

![Screenshot from 2020-04-10 08-43-35](https://user-images.githubusercontent.com/63110809/78995180-6522fa00-7b07-11ea-8026-d1a6baa6f781.png)

**Comment by afbjorklund** [comment]
Glad to hear! We can move the discussion about improving the error message to #7566
