### ISSUE TITLE
docs: need to addons on addons

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7537]
our handbook and website doesnt not have much info about all the addons we have
we need a section to list all the addons (use the @priyawadhwa auto generate doc) to list the addons

and maybe a small descrption or example usage of each addon in their page.

cc: are you interested ?
@prasadkatti 

some of our addons alrready have a Readme we can use as a basic start
https://github.com/kubernetes/minikube/tree/master/deploy/addons/helm-tiller

but I believe they are not represtened in the site.

**Comment by prasadkatti** [comment]
Sure! I might have a few questions along the way. I am sure. I will reach out on Slack.
