### ISSUE TITLE
docs: links to netowkring is broken

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7540]
here https://minikube.sigs.k8s.io/docs/handbook/pushing/
the link
https://minikube.sigs.k8s.io/reference/networking/
is broken

addtitioanlly all of the links in the website, that links to our own website should be changed to
this format:

more information on [docker-env]({{< ref "/docs/commands/docker-env" >}})

instead of the full url https://minikube.sigs.k8s.io/...

**Comment by afbjorklund** [comment]
We should probably just delete the whole "docs", there is no content there anyway.

Use can use Google to find wherever the minikube documentation is hiding today ?

**Comment by radeksm** [comment]
@medyagh regarding your comment https://github.com/kubernetes/minikube/pull/7546#issuecomment-611771607 sure I can do.

Just forgive me my lame question :)
I figured out how I can run local Kubernetes docs in container with hugo server.
Is there any way to generate HTML content from .md files and run it locally? maybe with hugo? 
There is *generate-docs* target in Makefile but it seems to be doing something else than what I need.

**Comment by medyagh** [comment]
@radeksm you can run 'make site'

**Comment by ricardoapl** [comment]
I think the link to networking in https://github.com/kubernetes/minikube/blob/master/site/content/en/docs/handbook/pushing.md?plain=1#L252 is still broken, but I'm not sure where it should be pointing to.
