### ISSUE TITLE
docs/networking.md points to non-existing URL

### ISSUE THREAD

**Issue by radeksm** [kubernetes/minikube#7543]
**Steps to reproduce the issue:** 
`cat docs/networking.md`
it points to https://minikube.sigs.k8s.io/docs/reference/networking/ which does not exist any more. 

**Full output of failed command:** 
`Not found 
Oops! This page doesn't exist. Try going back to our home page.`

**Proposed Solution:**
Because *networking* section has gone from minikube.sigs.k8s.io/ we probably should remove the docs/networking.md.

**Comment by afbjorklund** [comment]
Since most of those links broke, we should probably just delete the whole "docs" directory
