### ISSUE TITLE
No connection could be made because the target machine actively refused it.

### ISSUE THREAD

**Issue by kajariagrawal** [kubernetes/minikube#7549]
Windows machine 64 bit. 4gb RAM
Virtual box installed: oracle virtual box 5.2.20
Docker toolbox installed.

**Steps to reproduce the issue:** 

**minikube start --driver=virtualbox --alsologtostderr v=4**

<details>
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="dsound"
audio_in="false"
audio_out="false"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="\\?\c:\Users"
videocap="off"
videocap_audio="off"
videocapscreens=0
videocapfile="C:\Users\admin\.minikube\machines\minikube\minikube\minikube.webm"

videocapres=1024x768
videocaprate=512
videocapfps=25
videocapopts=
GuestMemoryBalloon=0
}
I0409 15:26:30.238006    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:30.238506    6696 main.go:110] libmachine: Check network to re-creat
e if needed...
I0409 15:26:30.238506    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
I0409 15:26:30.358521    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:26:30.472535    6696 main.go:110] libmachine: STDOUT:
{
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            bfa0a775-369f-4110-b937-6f3cd69fd54e
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::f17d:b76e:4828:f729
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:14
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #
2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            572933c4-39e5-47a8-ab7e-60cb27a4d7d3
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::509:ee47:9582:77b8
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:12
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

}
I0409 15:26:30.475036    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:30.772073    6696 main.go:110] libmachine: Searching for hostonly in
terface for IPv4: 192.168.99.1 and Mask: ffffff00
I0409 15:26:30.772573    6696 main.go:110] libmachine: Found: VirtualBox Host-On
ly Ethernet Adapter #2
I0409 15:26:30.772573    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe list dhcpservers
I0409 15:26:31.132619    6696 main.go:110] libmachine: STDOUT:
{
NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
IP:             192.168.56.100
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.56.101
upperIPAddress: 192.168.56.254
Enabled:        Yes

NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

IP:             192.168.99.13
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes

}
I0409 15:26:31.134119    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:31.134619    6696 main.go:110] libmachine: Removing orphan DHCP serv
ers...
I0409 15:26:31.134619    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
I0409 15:26:31.446659    6696 main.go:110] libmachine: STDOUT:
{
Name:            VirtualBox Host-Only Ethernet Adapter #2
GUID:            bfa0a775-369f-4110-b937-6f3cd69fd54e
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::f17d:b76e:4828:f729
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:14
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #
2

Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            572933c4-39e5-47a8-ab7e-60cb27a4d7d3
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::509:ee47:9582:77b8
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:12
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

}
I0409 15:26:31.449659    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:31.450159    6696 main.go:110] libmachine: Adding/Modifying DHCP ser
ver "192.168.99.2" with address range "192.168.99.100" - "192.168.99.254"...
I0409 15:26:31.450159    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe list dhcpservers
I0409 15:26:31.565174    6696 main.go:110] libmachine: STDOUT:
{
NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter
IP:             192.168.56.100
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.56.101
upperIPAddress: 192.168.56.254
Enabled:        Yes

NetworkName:    HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter #2

IP:             192.168.99.13
NetworkMask:    255.255.255.0
lowerIPAddress: 192.168.99.100
upperIPAddress: 192.168.99.254
Enabled:        Yes

}
I0409 15:26:31.566174    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:31.593178    6696 main.go:110] libmachine: Windows might ask for the
 permission to configure a dhcp server. Sometimes, such confirmation window is m
inimized in the taskbar.
I0409 15:26:31.593678    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe dhcpserver modify --netname HostInterfaceNetwo
rking-VirtualBox Host-Only Ethernet Adapter #2 --ip 192.168.99.2 --netmask 255.2
55.255.0 --lowerip 192.168.99.100 --upperip 192.168.99.254 --enable
I0409 15:26:32.246761    6696 main.go:110] libmachine: STDOUT:
{
}
I0409 15:26:32.247761    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:32.248261    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --nic2 hostonly --nictype2 v
irtio --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapte
r #2 --cableconnected2 on
I0409 15:26:32.536297    6696 main.go:110] libmachine: STDOUT:
{
}
I0409 15:26:32.582303    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:32.583303    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --natpf1 delete ssh
I0409 15:26:32.871840    6696 main.go:110] libmachine: STDOUT:
{
}
I0409 15:26:32.872340    6696 main.go:110] libmachine: STDERR:
{
VBoxManage.exe: error: Code E_INVALIDARG (0x80070057) - One or more arguments ar
e invalid (extended info not available)
VBoxManage.exe: error: Context: "RemoveRedirect(Bstr(ValueUnion.psz).raw())" at
line 1872 of file VBoxManageModifyVM.cpp
}
I0409 15:26:32.881841    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --natpf1 ssh,tcp,127.0.0.1,5
4207,,22
I0409 15:26:33.378404    6696 main.go:110] libmachine: STDOUT:
{
}
I0409 15:26:33.378904    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:33.379404    6696 main.go:110] libmachine: COMMAND: C:\Program Files
\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless
I0409 15:26:34.357529    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:26:38.362537    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:26:42.362045    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:26:46.443063    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:26:50.572088    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:26:54.577596    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:26:58.579604    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:26:59.143676    6696 main.go:110] libmachine: STDOUT:
{
Waiting for VM "minikube" to power on...
VM "minikube" has been successfully started.
}
I0409 15:26:59.144176    6696 main.go:110] libmachine: STDERR:
{
}
I0409 15:26:59.144176    6696 main.go:110] libmachine: Checking vm logs: C:\User
s\admin\.minikube\machines\minikube\minikube\Logs\VBox.log
I0409 15:26:59.150677    6696 main.go:110] libmachine: Waiting for an IP...
I0409 15:26:59.151177    6696 main.go:110] libmachine: Getting to WaitForSSH fun
ction...
I0409 15:26:59.274193    6696 main.go:110] libmachine: Using SSH client type: na
tive
I0409 15:26:59.277193    6696 main.go:110] libmachine: &{{{<nil> 0 [] [] []} doc
ker [0x7c06f0] 0x7c06c0 <nil>  [] 0s} 127.0.0.1 54207 <nil> <nil>}
I0409 15:26:59.277693    6696 main.go:110] libmachine: About to run SSH command:

exit 0
I0409 15:27:02.584113    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:06.586621    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:10.594630    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:14.595638    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:18.596646    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:22.600155    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:26.600663    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:30.627674    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:34.706692    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:39.015239    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
I0409 15:27:41.531059    6696 main.go:110] libmachine: Error dialing TCP: ssh: h
andshake failed: read tcp 127.0.0.1:54243->127.0.0.1:54207: wsarecv: An existing
 connection was forcibly closed by the remote host.
I0409 15:27:42.158138    6696 start.go:110] createHost completed in 2m0.09375s
I0409 15:27:42.158638    6696 start.go:77] releasing machines lock for "minikube
", held for 2m0.1007509s
*
* [CREATE_TIMEOUT] Failed to start virtualbox VM. "minikube start" may fix it. c
reating host: create host timed out in 120.000000 seconds
* Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall
 software
I0409 15:27:43.092257    6696 main.go:110] libmachine: Error dialing TCP: dial t
cp 127.0.0.1:54004: connectex: No connection could be made because the target ma
chine actively refused it.
*

</details>

**Comment by tstromberg** [comment]
It looks like your Windows host firewall is interfering:

`No connection could be made because the target machine actively refused it.`

Can you try temporarily turning it off to see if the situation improves?

**Comment by kajariagrawal** [comment]
> It looks like your Windows host firewall is interfering:
> 
> `No connection could be made because the target machine actively refused it.`
> 
> Can you try temporarily turning it off to see if the situation improves?

Thank you for replying.
Yes i tried that too. Actually my issue is similar to issue #4293.
Also I was wondering...I have a very old configuration computer. 4gb RAM windows 7. Could it be that minikube requires a minimum of atleast 8gb RAM?

**Comment by tstromberg** [comment]
@kajariagrawal - This error code is reserved in Windows specifically for when a firewall is blocking the connection from being received, so no need to worry about the amount of RAM. That error would look different.

You can try upgrading your VirtualBox installation, but I'm not sure it will help.

**Comment by omkarprabhu-98** [comment]
@tstromberg Facing the same issue with the following:
- minikube v 1.10
- VirtualBox 6.1
- Windows 10 Home
and Microsoft Defender Firewall off

Had to use `--no-vtx-check` as recommended by some other issue. Virtualization is enabled in BIOS.

```
> minikube start --driver=virtualbox  --no-vtx-check --alsologtostderr -v=5
```
waits for a some time here
```
I0512 20:11:07.755505     736 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x7c0950] 0x7c0920 <nil>  [] 0s} 127.0.0.1 56537 <nil> <nil>}
I0512 20:11:07.756476     736 main.go:110] libmachine: About to run SSH command:
exit 0
I0512 20:12:22.916022     736 main.go:110] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:56539->127.0.0.1:56537: wsarecv: An existing connection was forcibly closed by the remote host.
``` 
then after a number of messages ends with the following:
```
I0512 20:26:58.554186    7268 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:56683: connectex: No connection could be made because the target machine actively refused it.
I0512 20:27:03.558778    7268 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:56683: connectex: No connection could be made because the target machine actively refused it.
I0512 20:27:08.577014    7268 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:56683: connectex: No connection could be made because the target machine actively refused it.
I0512 20:27:12.232022    7268 start.go:107] duration metric: createHost completed in 4m0.0180466s
I0512 20:27:12.232022    7268 start.go:74] releasing machines lock for "minikube", held for 4m0.0299266s
* Failed to start virtualbox VM. "minikube start" may fix it: creating host: create host timed out in 240.000000 seconds
I0512 20:27:12.236909    7268 exit.go:58] WithError(error provisioning host)=Failed to start host: creating host: create host timed out in 240.000000 seconds called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d3660, 0x18b8300)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b3f8ac, 0x17, 0x1dfc1c0, 0xc000004c80)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b53760, 0xc0003d9c40, 0x0, 0x4)
        /app/cmd/minikube/cmd/start.go:170 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b53760, 0xc0003d9c00, 0x4, 0x4, 0x2b53760, 0xc0003d9c00)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b527a0, 0x0, 0x0, 0xc000127101)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
*
* [CREATE_TIMEOUT] error provisioning host Failed to start host: creating host: create host timed out in 240.000000 seconds
* Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
* Related issue: https://github.com/kubernetes/minikube/issues/7072
```

**Comment by medyagh** [comment]
@kajariagrawal sorry to see you are still facing this issue, unforutantely my windows skill are limited but I still think this is a firewall issue, are you running minikube in a admistrative powershell ?

@kajariagrawal do you happen to have docker installed on your windows ? if your windows allows installing docker, have u tried our newest docker driver?

**Comment by medyagh** [comment]
Hi @kajariagrawal , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
