### ISSUE TITLE
Error in decoding kubeconfig on mac

### ISSUE THREAD

**Issue by nitinmuteja** [kubernetes/minikube#7555]
**Steps to reproduce the issue:** 

1. brew install minikube
2. minikube start --memory=6000 --cpus=4 --driver=virtualbox
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
tartup failed: Failed to update kubeconfig file.: could not read config: Error decoding config from data: apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EUXdOREE0TXpBek5Wb1hEVE13TURRd01qQTRNekF6TlZvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBS2xMCi83OHREOWNYVkFPaDNCWVZHd1hGaklzVUV0M2MzWmczQVNBYU5kZitvR3hMOFhpRFBNQ1RPaGsxU21zcUtQQXQKeXNUaG1QMDlxWnV2RzlHK0JzUmhHejZMaEFTQ1V6UFR0QnJCRTYzL3F2Y1o4MnY4LzJHZE1vdWZjbStjVGt5MgpOT3hKUUtock11NlBJOHpUc0tIbTIwa09rVjYxV05DM3ZNdjNqUEFVZ2VkbGFRVUY5STBQQjAzM0RqM3JSZGpGCitEZVhJcyttRGRXOFFhc2puYW13NGpQNEFEdDVuTkFLMk54eWlYV2VrVVdaVTFzemxhTWFOM0M1d0hXMEJ4eFkKWDJYc09UVUNHaVhUK1N5Y2R5YmNSNFVUOEowTUZEQ25KZkFTQVRXbk1ONVlXd0ZuaGpNTjVUWk5DSW55bEhPYgpXSlRsZ0prZXp6UjA0dzN3ZUVjQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0trTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDSE9LWXBtL2FGWXE4NTB3N2lHLzNyZWNXTG8KWk1LcXhoanpnQlRsbGQzVjk3OXgyRm4rK3kwSmZSaDV4NlhseENjQWtwZWV2YjVrK1NFUlBKVlNSaEdvTVM3bQp1c0NRU2MzZis3YlZEeWQrQlE5WUt0L0srVWRpVFlpVDNjMEEzQllpZC9Uc2U0blBHczNSdTQrek9zNExENFFCCnAwR1JwSzRVOGo0ZGxhMjMvOXZEdUlia2t0Q2d1UFJOU0hqZ2NsM2xyUjFqYzVPTnliZzV3c2JXUXpNRnNvREQKZVAvcnVJSXM4WnpnV3NVMmh1Tmt0cytHZTlCUmVRdENEOW5uaVN2dG1WZ1paeGRtVFU2aDU0L2FyaFl0SmhOUgpRVGJuMEwyUjBJSCtSTERrSmNtMWg2alp6NFJJaUhvcU1zWElEUlZOdzJ5V3NMTEhMZlVaeFE3VUpNdz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    server: https://139.59.20.130:6443
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: kubernetes-admin
  name: kubernetes-admin@kubernetes
current-context: kubernetes-admin@kubernetes
kind: Config
preferences: {}
users:
- name: kubernetes-admin
  user:
    client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM4akNDQWRxZ0F3SUJBZ0lJSlZnMEtnM0hFSFV3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TURBME1EUXdPRE13TXpWYUZ3MHlNVEEwTURRd09ETXdNemxhTURReApGekFWQmdOVkJBb1REbk41YzNSbGJUcHRZWE4wWlhKek1Sa3dGd1lEVlFRREV4QnJkV0psY201bGRHVnpMV0ZrCmJXbHVNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUZBQU9DQVE4QU1JSUJDZ0tDQVFFQW5qQm5RQ2pJaHc5N0gyQmwKaDZyOU8wVms0am5YOHFJUCtRSHdVWlE0Rm50QXU0STQwTnpZbkRyY1ROd0dHY3AvcGU1UDFvQmRXbEhNUWhyYgozbEZyUDBHZHJVaGJqNDRYcGoxVFJZYlNsbnJtK0QxMjRTdkhSSk9DM0R0YVN2R0NMNG8xdjRJOENaUy9tc2d3ClhlZzNzVzhQMGxMZlpFM3dwbm81dlJ1am1QaGFWOWtwcEIzeFB2QXBYbnFYOWhJZnYxVmxPL1M4a0xYZmRpaXQKWC9zc2dWMmZPblNNbVlNQkhyQW40MHhmSDdlQkJmMG84TjNYQ0pRWUFVUFZZY05jN25ZNUY1MTNBakhLbnZlRgpnWWU4L3g2WW43d2I4M0pXdGthc3o3eVc0UTdkUyt5QzZzYXpJalUvV1d5MVNJUTBUbTRYRVl6Z0VMZWlxaDBDCkUvN2hEd0lEQVFBQm95Y3dKVEFPQmdOVkhROEJBZjhFQkFNQ0JhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUgKQXdJd0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFLVU9SMkh6ck5HbEhrVHJFZkhmbzhLVTVNaE92eDlpWVYyMQpOYUJxcVdKSFo1TS9QbE5KZXkzNmRSeDBFNGVjZnp5UFk1eUMxWWRsTEcwdTRMaGoyRG9qbG9mb1ZldGxXWVZoCmFZdWVrQ3RmVnpzZXVBeVROUFdnS0U4OGdURVpTUG5SRkRTdXNXaXZpeW82VFFPQm1RQzJSN1dzR1d1Q1E1RVcKMGVDVXdxTnYwQUVpSm8yY3pqU25JUTh6OEdzTm9VTnRYN1lPeHY3VldhQXJ1dEZnS1dGMk5HK1dxMExMMmluQwpYSldQS1lsVDZWUUpTZ0ZTbnI5dHpLeWVnUnd4OXFMeXZvV3c5MGJRVGEvTHdOTGNmaThST00xek1vOXNScUdSCkhEMy9QWnRVNmplNWl0K0swdEZxV3AzUkZ5MHRKc21CUkRJd3RnR3lrZUVZVUxGMnJuVT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBbmpCblFDaklodzk3SDJCbGg2cjlPMFZrNGpuWDhxSVArUUh3VVpRNEZudEF1NEk0C
: v1.Config.AuthInfos: []v1.NamedAuthInfo: v1.NamedAuthInfo.AuthInfo: v1.AuthInfo.ClientKeyData: decode base64: illegal base64 data at input byte 128, error found in #10 byte of ...|dEF1NEk0C"}}]}|..., bigger context ...|SDJCbGg2cjlPMFZrNGpuWDhxSVArUUh3VVpRNEZudEF1NEk0C"}}]}|...

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@nitinmuteja do you mind sharing the minikube version ? and do you mind verifying if the kubeconfig

**Comment by medyagh** [comment]
@nitinmuteja I haven't heard from you, do you still have this issue ?

**Comment by nitinmuteja** [comment]
I was able to solve this by clearing my kubeconfig directory and uninstalling everything. I earlier had my kubeconfig pointing to a kubernetes cluster on cloud and had deleted that cluster. So when doing minikube installation this error popped up.

**Comment by medyagh** [comment]
thats good to hear that deleting the kubeconfig fixed it
