### ISSUE TITLE
Move kic to ssh_runner where possible

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7573]
I noticed that, even at head, minikube still uses kic_runner in many places.

kic_runner has high transactional overhead compared to ssh_runner, since ssh_runner re-uses the same connection. 

Solution would need to be benchmarked, of course.

**Comment by medyagh** [comment]
could also try with setting the --entry-point to "" so docker exec commands not run the entry-point which is pretty heavy and intense.
