### ISSUE TITLE
Skip preload download if `--image-repository` is set

### ISSUE THREAD

**Issue by chengyayu** [kubernetes/minikube#7612]
**重现问题所需的命令**：minikube start --cpus=2 --memory='2000mb' --vm-driver hyperkit --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'

**失败的命令的完整输出**：<details>
😄  minikube v1.9.2 on Darwin 10.15.4
✨  Using the hyperkit driver based on existing profile
✅  Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
👍  Starting control plane node m01 in cluster minikube
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 131.59 MiB
</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：macOS 10.15.4

**Comment by lmdkfs** [comment]
我也用到这个 版本了，preloaded image的时候特别慢

**Comment by tstromberg** [comment]
Similarly to image downloads, the preload download is not currently available in China (both are hosted on Google).

We should probably disable the image preload download if a user has specified `--image-repository` so that it doesn't keep trying to attempt it.

**Comment by afbjorklund** [comment]
Alternatively, we could provide a similar option for the preload url ? (after #7695)
