### ISSUE TITLE
virtualbox 5.2: create host timed out in 120.000000 seconds

### ISSUE THREAD

**Issue by Tayyab30** [kubernetes/minikube#7616]
### plz can enyone help me to solve this error
`1.minikube start --driver=virtualbox`
2. then produce this error
3.Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds

**Comment by mudasar187** [comment]
I also faced the same issue. I am using the newest version of Virtualbox, Minikube and Docker. I think there is some bug that need to be fixed. I am using MacOS Catalina.

**Comment by sharifelgamal** [comment]
Hopefully #7565 will fix this issue.

**Comment by tstromberg** [comment]
@Tayyab30 -  I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
* Does this happen on the latest version of minikube?

Thank you for sharing your experience!

**Comment by sharifelgamal** [comment]
@Tayyab30 We haven't heard from you in awhile, I'm going to go ahead and close this issue. If it remains an issue, feel free to reopen it with the details requested in the post above.

Thank you!
