### ISSUE TITLE
Kubectl install hint on `minikube start`

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#762]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

Minikube requires kubectl for any meaningful behavior.  The download links for standalone kubectl aren't that easy to find and aren't well documented.  If the user doesn't have kubectl, we should output a hint with the install command during startup

```
Starting cluster...
To interact with the kubernetes cluster, please download the kubectl client 
using `gcloud component install kubectl` or 
curl -Lo kubectl http://storage.googleapis.com/kubernetes-release/release/$DEFAULT_MINIKUBE_K8S_VERSION/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
....
```

**Comment by r2d4** [comment]
Thumbs up this comment if you think that minikube should just bundle kubectl and offer the option to install it right from the binary

**Comment by jimmidyson** [comment]
I think minikube should offer to download & install latest version of kubectl if it can't find it in PATH. It could also offer to update the version if it's an old version. I don't like the idea of bundling it personally, prefer to download it if required.

**Comment by aaron-prindle** [comment]
Currently plan on doing the check is to check the OS minikube is running on and then running the appropriate shell cmd for the os to check that minikube is on the path.  Something like:
Linux/OSX:
http://stackoverflow.com/questions/592620/check-if-a-program-exists-from-a-bash-script
Windows:
http://stackoverflow.com/questions/4781772/how-to-test-if-an-executable-exists-in-the-path-from-a-windows-batch-file

Please let me know if you have any feedback/alternatives.  Thanks.

**Comment by r2d4** [comment]
We use exec.LookPath in the integration tests

https://golang.org/src/os/exec/lp_unix.go?s=931:973#L24

**Comment by aaron-prindle** [comment]
Yea, just saw this lol.  Thanks.
