### ISSUE TITLE
virtualbox on Windows 7: create host timed out in 120 seconds

### ISSUE THREAD

**Issue by Nightrider0098** [kubernetes/minikube#7633]
**Steps to reproduce the issue:** 

1.minikube start
2. minikube delete
3. minikube start

![Untitled](https://user-images.githubusercontent.com/39752890/79076946-3aa98a80-7d1b-11ea-8175-f1e646357e73.png)

**Comment by medyagh** [comment]
@Nightrider0098 could u check if u have access to the config file ?
C:\Users\JPC\.minikube\machines\minikube.config.json

**Comment by tstromberg** [comment]
Closing because we haven't heard back from Nightrider0098
