### ISSUE TITLE
error execution phase preflight: [preflight] Some fatal errors occurred:

### ISSUE THREAD

**Issue by redxdevops** [kubernetes/minikube#7634]
**Steps to reproduce the issue:** 

error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10259]: Port 10259 is in use
	[ERROR Port-10257]: Port 10257 is in use
	[ERROR Port-2380]: Port 2380 is in use

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
possible dup of #7647

**Comment by priyawadhwa** [comment]
Hey @redxdevops --  I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by redxdevops** [comment]
thanks that works I appreciate that
