### ISSUE TITLE
cleanup: move storage-provisioner out of the minikube go.mod

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7638]
while doing this PR https://github.com/kubernetes/minikube/pull/7636

I was trying to bump minikube kuberentes version lib to latest but /kubernetes-sigs/sig-storage-lib-external-provisioner uses an older client-go that we can not bump to latest.

however kubernetes-sigs/sig-storage-lib-external-provisioner is only used by pkg/storage/ which is only used by our storage-provisioner in cmd. which its own binary in a docker file

how about we remove storage privsioner outside minikube go mod and have its own go mod.
I bet that would make our binary size smaller too.

https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/issues/74

```
WARN [runner] Can't run linter goanalysis_metalinter: S1037: failed prerequisites: [(inspect@k8s.io/minikube/pkg/storage, isgenerated@k8s.io/minikube/pkg/storage): analysis skipped: errors in package: [/Users/medmac/workspace/minikube/pkg/storage/storage_provisioner.go:33:2: could not import sigs.k8s.io/sig-storage-lib-external-provisioner/controller (/Users/medmac/go/pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner@v4.0.0+incompatible/controller/controller.go:55:2: could not import sigs.k8s.io/sig-storage-lib-external-provisioner/util (/Users/medmac/go/pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner@v4.0.0+incompatible/util/util.go:106:71: cannot use "coredns" (constant of type string) as context.Context value in argument to client.CoreV1().Services(metav1.NamespaceSystem).Get: missing method Deadline))]] 
```

what do you think @afbjorklund

**Comment by afbjorklund** [comment]
Maybe we should move the entire storage-provisioner out of the minikube git repository ?

It hasn't seen a new release in years, and like you say it seems to be mixing up the code.

**Comment by afbjorklund** [comment]
I think it is also **broken** at the moment, there seem to be some reports about it not working ?

**Comment by medyagh** [comment]
I dont think we have capactiy for doing this at the moment. may be long term !
