### ISSUE TITLE
how to fix 

### ISSUE THREAD

**Issue by shujaurr18** [kubernetes/minikube#7639]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
Hi. It looks like you accidentally created an issue before filling out any details. Can you please update the issue description to add necessary details?

**Comment by medyagh** [comment]
@shujaurr18  haven't heard from you
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
