### ISSUE TITLE
startup failed: Failed to update kubeconfig file.: writing kubeconfig: Error creating directory

### ISSUE THREAD

**Issue by ssaxen0** [kubernetes/minikube#7641]
**Steps to reproduce the issue:** 

1.minikube start
2. 
3.

**Full output of failed command:** 
 startup failed: Failed to update kubeconfig file.: writing kubeconfig: Error creating directory: /etc/rancher/k3s: mkdir /etc/rancher: permission denied

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The OS and driver used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!

**Comment by tstromberg** [comment]
I believe you may have a `KUBECONFIG` environment variable set to a location where your user does not have access.

**Comment by medyagh** [comment]
@ssaxen0 I haven't heard from you, 
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
