### ISSUE TITLE
direct user to using minikube's inner kubectl when not installed

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7642]
on a system without kubectl:

```
med@xmac:~$ minikube start 
😄  minikube v1.9.2 on Ubuntu 20.04
✨  Automatically selected the docker driver
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 542.91 MiB
🔥  Creating Kubernetes in docker container with (CPUs=2) (8 available), Memory=3900MB (15990MB available) ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
💡  For best results, install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/

```

instead of saying ```💡  For best results, install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/``` 
we could provide them a link to docs (and add nice docs in website) how to use kubectl inside minikube

minikube kubectl -- get pods ...

and then then in the end say , alternatively install kubectl

**Comment by tstromberg** [comment]
I don't know - should `minikube kubectl`  really be considered the ideal outcome?

I do agree that we should mention it as an alternative, similar to what we do with a version mismatch.

**Comment by 9kranti** [comment]
I'm also getting same output and before this I was getting control plane node as `minikube` and now I'm getting it as `m01`
Why is this node changed? Then where is `minikube node`?

**Comment by afbjorklund** [comment]
> I'm also getting same output and before this I was getting control plane node as `minikube` and now I'm getting it as `m01`
> Why is this node changed? Then where is `minikube node`?

It is not possible to understand what you mean, or how this is related to `kubectl`

Can you open a new issue instead ? It seems to be somewhat related to multi-node

**Comment by Harkishen-Singh** [comment]
I will like to take up this.
