### ISSUE TITLE
v1.9.2 from old ISO: /var/lib/minikube/etcd is not empty error /apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error

### ISSUE THREAD

**Issue by Zerotask** [kubernetes/minikube#7666]
**Steps to reproduce the issue:** 

1. Downloaded the windows installer from https://storage.googleapis.com/minikube/releases/latest/minikube-installer.exe and installed it.
2. Opened a terminal
3. Executed "minikube start"

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

```
$ minikube start
* minikube v1.9.2 auf Microsoft Windows 10 Pro 10.0.19041 Build 19041
* Automatically selected the docker driver
* Starting control plane node m01 in cluster minikube
* Pulling base image ...
* Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 542.91 MiB
* Creating Kubernetes in docker container with (CPUs=2) (2 available), Memory=4000MB (5948MB available) ...
* Vorbereiten von Kubernetes v1.18.0 auf Docker 19.03.2...
  - kubeadm.pod-network-cidr=10.244.0.0/16
! This container is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
! Unable to restart cluster, will reset it: getting k8s client: client config: client config: context "minikube" does not exist
! initialization failed, will try again: run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.18.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,SystemVerification,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": exit status 1
stdout:
[init] Using Kubernetes version: v1.18.0
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk

stderr:
W0414 13:16:20.469832    1230 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
        [WARNING Swap]: running with swap on is not supported. Please disable swap
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error
To see the stack trace of this error execute with --v=5 or higher
```

**Optional: Full output of `minikube logs` command:**
<details>
$ minikube logs
* ==> Docker <==
* -- Logs begin at Tue 2020-04-14 13:15:18 UTC, end at Tue 2020-04-14 13:20:06 UTC. --
* Apr 14 13:15:33 minikube systemd[1]: Started Docker Application Container Engine.
* Apr 14 13:15:33 minikube dockerd[90]: time="2020-04-14T13:15:33.711176003Z" level=info msg="API listen on /run/docker.sock"
* Apr 14 13:15:58 minikube systemd[1]: docker.service: Current command vanished from the unit file, execution of the command list won't be resumed.
* Apr 14 13:15:58 minikube systemd[1]: Stopping Docker Application Container Engine...
* Apr 14 13:15:58 minikube dockerd[90]: time="2020-04-14T13:15:58.116259944Z" level=info msg="Processing signal 'terminated'"
* Apr 14 13:15:58 minikube dockerd[90]: time="2020-04-14T13:15:58.117610443Z" level=info msg="Daemon shutdown complete"
* Apr 14 13:15:58 minikube systemd[1]: docker.service: Succeeded.
* Apr 14 13:15:58 minikube systemd[1]: Stopped Docker Application Container Engine.
* Apr 14 13:15:58 minikube systemd[1]: Starting Docker Application Container Engine...
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.192833237Z" level=info msg="Starting up"
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.205544736Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.205603836Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.205628836Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.205638536Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.205706636Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00005bea0, CONNECTING" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.219260635Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00005bea0, READY" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.219757235Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.219844135Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.219887435Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.219899935Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.219942735Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0008033e0, CONNECTING" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.220266235Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0008033e0, READY" module=grpc
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.222828535Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
* Apr 14 13:15:58 minikube dockerd[359]: time="2020-04-14T13:15:58.337414125Z" level=info msg="Loading containers: start."
* Apr 14 13:15:59 minikube dockerd[359]: time="2020-04-14T13:15:59.244672351Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Apr 14 13:15:59 minikube dockerd[359]: time="2020-04-14T13:15:59.553901626Z" level=info msg="Loading containers: done."
* Apr 14 13:15:59 minikube dockerd[359]: time="2020-04-14T13:15:59.735608711Z" level=info msg="Docker daemon" commit=6a30dfca03 graphdriver(s)=overlay2 version=19.03.2
* Apr 14 13:15:59 minikube dockerd[359]: time="2020-04-14T13:15:59.735677311Z" level=info msg="Daemon has completed initialization"
* Apr 14 13:15:59 minikube systemd[1]: Started Docker Application Container Engine.
* Apr 14 13:15:59 minikube dockerd[359]: time="2020-04-14T13:15:59.915119197Z" level=info msg="API listen on /var/run/docker.sock"
* Apr 14 13:15:59 minikube dockerd[359]: time="2020-04-14T13:15:59.915248497Z" level=info msg="API listen on [::]:2376"
* Apr 14 13:16:00 minikube systemd[1]: Stopping Docker Application Container Engine...
* Apr 14 13:16:00 minikube dockerd[359]: time="2020-04-14T13:16:00.984529861Z" level=info msg="Processing signal 'terminated'"
* Apr 14 13:16:00 minikube dockerd[359]: time="2020-04-14T13:16:00.985557360Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
* Apr 14 13:16:00 minikube dockerd[359]: time="2020-04-14T13:16:00.986310660Z" level=info msg="Daemon shutdown complete"
* Apr 14 13:16:00 minikube systemd[1]: docker.service: Succeeded.
* Apr 14 13:16:00 minikube systemd[1]: Stopped Docker Application Container Engine.
* Apr 14 13:16:01 minikube systemd[1]: Starting Docker Application Container Engine...
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.079640391Z" level=info msg="Starting up"
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.086196988Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.086239588Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.086263288Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.086278788Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.086338988Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006bfcd0, CONNECTING" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.086850187Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0006bfcd0, READY" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.087670287Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.087709087Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.087726087Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.087733887Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.087771987Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000804560, CONNECTING" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.091306186Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000804560, READY" module=grpc
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.093811385Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
* Apr 14 13:16:02 minikube dockerd[563]: time="2020-04-14T13:16:02.271207208Z" level=info msg="Loading containers: start."
* Apr 14 13:16:03 minikube dockerd[563]: time="2020-04-14T13:16:03.195330412Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Apr 14 13:16:03 minikube dockerd[563]: time="2020-04-14T13:16:03.537351165Z" level=info msg="Loading containers: done."
* Apr 14 13:16:03 minikube dockerd[563]: time="2020-04-14T13:16:03.652653816Z" level=info msg="Docker daemon" commit=6a30dfca03 graphdriver(s)=overlay2 version=19.03.2
* Apr 14 13:16:03 minikube dockerd[563]: time="2020-04-14T13:16:03.652736816Z" level=info msg="Daemon has completed initialization"
* Apr 14 13:16:03 minikube systemd[1]: Started Docker Application Container Engine.
* Apr 14 13:16:03 minikube dockerd[563]: time="2020-04-14T13:16:03.808460549Z" level=info msg="API listen on /var/run/docker.sock"
* Apr 14 13:16:03 minikube dockerd[563]: time="2020-04-14T13:16:03.808551349Z" level=info msg="API listen on [::]:2376"
*
* ==> container status <==
* time="2020-04-14T13:20:08Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
*
* ==> describe nodes <==
E0414 15:20:09.128097    8376 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.0/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.0/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": exit status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"
*
* ==> dmesg <==
* [Apr14 13:02] PCI: Fatal: No config space access function found
* [  +0.379960] PCI: System does not support PCI
* [  +0.254839] Hangcheck: starting hangcheck timer 0.9.1 (tick is 180 seconds, margin is 60 seconds).
* [  +0.331610] Unstable clock detected, switching default tracing clock to "global"
*               If you want to keep using the local clock, then add:
*                 "trace_clock=local"
*               on the kernel command line
* [  +0.025758] FAT-fs (sr0): utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
* [  +0.007224] FAT-fs (sr0): utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
* [  +6.094362] FAT-fs (sr2): utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
* [  +0.055351] FAT-fs (sr2): utf8 is not a recommended IO charset for FAT filesystems, filesystem will be case sensitive!
*
* ==> kernel <==
*  13:20:09 up 18 min,  0 users,  load average: 0.28, 0.55, 0.29
* Linux minikube 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* PRETTY_NAME="Ubuntu 19.10"
*
* ==> kubelet <==
* -- Logs begin at Tue 2020-04-14 13:15:18 UTC, end at Tue 2020-04-14 13:20:10 UTC. --
* Apr 14 13:20:07 minikube kubelet[4931]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:07 minikube kubelet[4931]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:07 minikube kubelet[4931]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:07 minikube kubelet[4931]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:07 minikube kubelet[4931]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:07 minikube kubelet[4931]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:07 minikube kubelet[4931]: I0414 13:20:07.846957    4931 server.go:417] Version: v1.18.0
* Apr 14 13:20:07 minikube kubelet[4931]: I0414 13:20:07.847336    4931 plugins.go:100] No cloud provider specified.
* Apr 14 13:20:07 minikube kubelet[4931]: I0414 13:20:07.847426    4931 server.go:837] Client rotation is on, will bootstrap in background
* Apr 14 13:20:07 minikube kubelet[4931]: F0414 13:20:07.847516    4931 server.go:274] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
* Apr 14 13:20:07 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
* Apr 14 13:20:07 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Apr 14 13:20:08 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Apr 14 13:20:08 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 293.
* Apr 14 13:20:08 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Apr 14 13:20:08 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:08 minikube kubelet[4942]: I0414 13:20:08.604540    4942 server.go:417] Version: v1.18.0
* Apr 14 13:20:08 minikube kubelet[4942]: I0414 13:20:08.604732    4942 plugins.go:100] No cloud provider specified.
* Apr 14 13:20:08 minikube kubelet[4942]: I0414 13:20:08.604747    4942 server.go:837] Client rotation is on, will bootstrap in background
* Apr 14 13:20:08 minikube kubelet[4942]: F0414 13:20:08.604775    4942 server.go:274] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
* Apr 14 13:20:08 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
* Apr 14 13:20:08 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Apr 14 13:20:09 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Apr 14 13:20:09 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 294.
* Apr 14 13:20:09 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Apr 14 13:20:09 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Apr 14 13:20:09 minikube kubelet[4974]: I0414 13:20:09.390763    4974 server.go:417] Version: v1.18.0
* Apr 14 13:20:09 minikube kubelet[4974]: I0414 13:20:09.391092    4974 plugins.go:100] No cloud provider specified.
* Apr 14 13:20:09 minikube kubelet[4974]: I0414 13:20:09.391153    4974 server.go:837] Client rotation is on, will bootstrap in background
* Apr 14 13:20:09 minikube kubelet[4974]: F0414 13:20:09.391216    4974 server.go:274] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
* Apr 14 13:20:09 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
* Apr 14 13:20:09 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Apr 14 13:20:10 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Apr 14 13:20:10 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 295.
* Apr 14 13:20:10 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Apr 14 13:20:10 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.

! unable to fetch logs for: describe nodes

</details>

**Comment by tstromberg** [comment]
This appears to be due to an old VM in use:

```
Linux minikube 4.19.76-linuxkit #1 SMP Thu Oct 17 19:31:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

This error message made me suspicious:

```
[WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
error execution phase certs/apiserver-kubelet-client: [certs] certificate apiserver-kubelet-client not signed by CA certificate ca: crypto/rsa: verification error
```

You can fix the problem by using `minikube delete`.

**Comment by tstromberg** [comment]
Nevermind - I misinterpreted, this is a docker container.

**Comment by tstromberg** [comment]
Does `minikube delete` help?

If not, can you provide the output of:

`minikube start --alsologtostderr -v=1`

Thank you!

**Comment by Zerotask** [comment]
Before I could install and use minikube without any problems. The problem occurred after I uninstalled minikube and Docker and did a fresh installation of both. So maybe it's something related to the uninstallation Minikube.

**Comment by Zerotask** [comment]
> Does `minikube delete` help?

Yes, this worked for me. Thank you.

**Comment by sharifelgamal** [comment]
Looks like this issue is fixed. If you feel it isn't feel free to reopen.
