### ISSUE TITLE
clean up after creating temp dirs in uni tests 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7670]
some unit tests are making temp files but they never delete them, I fixed a few of them but there are more of these

```
ioutil.TempDir(""
```

would be a good PR for anyone interested to make the code better

here is an example how to do it: https://github.com/kubernetes/minikube/pull/7669/files

the tricky for the left overs is, there are helper funcs in the unit tests that multple tests call them

the person who takes this PR should make sure there is it is not cleaned up too early before tests use them.

**Comment by zerefwayne** [comment]
@medyagh I would like to take up this issue.

**Comment by BLasan** [comment]
@medyagh Is this issue still opened?

**Comment by medyagh** [comment]
@BLasan  I have not seen this issue recently, if there is evidence we leave left over files I would accept a PR for this.
