### ISSUE TITLE
Failed to cache images

### ISSUE THREAD

**Issue by for-mysql** [kubernetes/minikube#7675]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
Hi 👋. Can you provide some more details about what exactly you are trying to do? What is expected vs what is actually happening?

**Comment by medyagh** [comment]
@for-mysql  haven't heard from you. 
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
