### ISSUE TITLE
kvm: Failed to connect socket to '/var/run/libvirt/libvirt-sock'

### ISSUE THREAD

**Issue by anilsakr** [kubernetes/minikube#7677]
minikube start
😄  minikube v1.9.2 on Ubuntu 18.04 (xen/amd64)
✨  Using the kvm2 driver based on existing profile

❗  'kvm2' driver reported an issue: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
💡  Suggestion: Follow your Linux distribution instructions for configuring KVM
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/

👍  Starting control plane node m01 in cluster minikube
🔄  Restarting existing kvm2 VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: creating network: getting libvirt connection: error connecting to libvirt socket.: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')
🔄  Restarting existing kvm2 VM for "minikube" ...

❌  [KVM_CONNECTION_ERROR] Failed to start kvm2 VM. "minikube start" may fix it. driver start: creating network: getting libvirt connection: error connecting to libvirt socket.: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')
💡  Suggestion: Have you set up libvirt correctly?
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/

**Comment by prasadkatti** [comment]
Have you taken a look at the troubleshooting section on the link above? Can you verify libvirt is installed?

**Comment by mazzystr** [comment]
You'll get this error is qemu is not installed also.  

In Fedora 30 and 31 it's not clear libvirtd, virsh, qemu aren't installed out of the box using Anaconda installs.

**Comment by medyagh** [comment]
@mazzystr sorry to hear you faced that issue installing kvm, I wonder if you found a work arround for this issue ? did you find out how how to install kvm on fedora 30 or 31 that u could share with us ?

**Comment by medyagh** [comment]
@anilsakr on a fresh debian I had this issue
and I was able to fix by

```
sudo adduser $USER libvirt
sudo systemctl enable virtlogd.socket
sudo systemctl restart virtlogd.socket
```

do you mind trying that ?

**Comment by medyagh** [comment]
@mazzystr
@anilsakr

have you had a chance to try the suggestion int his comment ? https://github.com/kubernetes/minikube/issues/7677#issuecomment-652111143

**Comment by priyawadhwa** [comment]
Hey @mazzystr
@anilsakr

are you still seeing this issue?

**Comment by sharifelgamal** [comment]
You can also run `newgrp libvirt` to accomplish the same as above without rebooting. 

Either way, I'm going to go ahead and close this issue, it seems to have been resolved. Feel free to reopen if there continues to be an issue.

**Comment by shotu** [comment]
> @mazzystr
> @anilsakr
> 
> have you had a chance to try the suggestion in this comment ? [#7677 (comment)](https://github.com/kubernetes/minikube/issues/7677#issuecomment-652111143)

I think that was 
 Message='Failed to connect socket to '/var/run/libvirt/virtlogd-sock': **Connection refused'**

for me it is same- and not able to resolve

😄  minikube v1.12.1 on Ubuntu 18.04
    ▪ KUBECONFIG=/home/username/kubernetes_workspace/cluster.conf
✨  Using the kvm2 driver based on user configuration

❗  'kvm2' driver reported an issue: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor
error: Failed to connect socket to **'/var/run/libvirt/libvirt-sock': No such file or directory**
💡  Suggestion: Follow your Linux distribution instructions for configuring KVM
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/

💣  Failed to validate 'kvm2' driver


Please let me know if you guys have the solution.

**Comment by DavePool** [comment]
I was having the same problem because the user running the command to start minicube does not have permissions to use the virtualization libraries, just add libvirt as a supplemental group to my local user.
Then check: getent group libvirt

I use Ferora 33 with Quemu / KVM

**Comment by arslan-ahmad** [comment]
> I had this issue too. For me, it was an issue with the groups that were added to my user but not visible yet. I solved it by rebooting so the new group (libvirt) was actually visible for my user. You can achieve the same without rebooting by running `exec sudo su -l $USER`.

worked for me
