### ISSUE TITLE
[ERROR Port-10259]: Port 10259 is in use

### ISSUE THREAD

**Issue by WebDmitryPetrov** [kubernetes/minikube#7691]
Hi! When starting the minikube, an error is returned.
Ubuntu 18.04 /Docker 19.03.8 / Kybernetes v1.18.0 / minikube v1.9.0  is currently installed
----------------------------------------------------------------------------------------------------------

W0415 19:04:24.946965   19080 configset.go:202] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
        [WARNING Port-10250]: Port 10250 is in use
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR Port-10259]: Port 10259 is in use
        [ERROR Port-10257]: Port 10257 is in use
        [ERROR Port-2380]: Port 2380 is in use

**Comment by tstromberg** [comment]
minikube seems to be conflicting with another running local Kubernetes service (perhaps itself!). What do you see if you run:

`lsof -p 10250`

Also, can you please check if upgrading to minikube v1.9.2 helps? If not, please share the output of `minikube start --alsologtostderr`

If not, `minikube delete` will probably help.

**Comment by medyagh** [comment]
@WebDmitryPetrov  haven't heard from you,
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
