### ISSUE TITLE
updated screenshot on minikube docs 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7698]
the current screenshot does not have the improvements @afbjorklund made.

https://minikube.sigs.k8s.io/images/screenshot.png

**Comment by tstromberg** [comment]
@medyagh - that's because the screenshot is for the most recent release (v1.9.2).

**Comment by RA489** [comment]
@medyagh Looks like this has been already addressed. If you don't mind can we close this issue?
