### ISSUE TITLE
various minikube-bot/jenkins release improvements

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#770]
This is a thread to discuss potential minikube-bot/jenkins release improvements, please add you suggestions below:
- [x] To fully automate the release process, minikube-bot/jenkins should automatically generate the PR and upload the releases.json after release job is run.

**Comment by r2d4** [comment]
Agreed.  Adding to the list of things that the release could use:

- [ ] Add buildroot iso to releases download, make that part of the release
- [ ] Add b2d iso as a github release download
  - We include the checksum, but not the download.  We should include the download.
- [ ] Add CHANGELOG diff to github release page 
  - Some users want to see the new changes right on the releases page.
- [ ] Push new minikube docs upstream to kubernetes.github.io
  - Not sure how we implement this one.  Should the minikube readme be in sync with the getting started?  Probably not.  But we should make a good effort to keep the "upstream" docs in sync as we add new features.

**Comment by aaron-prindle** [comment]
- [ ] Automate CHANGELOG generation via special commit annotations/commit-summary
..*^ Unsure as it might be confusing/slower to document as you go

**Comment by rodcloutier** [comment]
[] Automate the Windows installer upgrade

**Comment by aaron-prindle** [comment]
Additional Integration tests:
Test all bundled addons in some fashion (at least that they start up)
Test hostpath mounting for various os/driver combinations
Test /data persistance
