### ISSUE TITLE
Dashboard error "attempted to generate service url with nil --format template"

### ISSUE THREAD

**Issue by reteptilian** [kubernetes/minikube#771]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):  BUG

**Minikube version** (use `minikube version`): minikube version: v0.12.1

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **Docker version** (e.g. `docker -v`):  Docker version 1.12.2, build bb80604
- **Install tools**:  
- **Others**:

**What happened**:

I had gotten some basic deployments working with minikube v0.12.0.  Today, I saw a new version was available.  I did a "minikube stop", then installed the new version with the recommended curl command ("curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.12.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/").

I then did a "minikube start".  My deployments are working.  However, "minikube dashboard" fails with:

$ minikube dashboard
Error, attempted to generate service url with nil --format template
Check that minikube is running.

I rolled back to 0.12.0 and the dashboard works again.

**What you expected to happen**:
**How to reproduce it** (as minimally and precisely as possible):  see What Happened above

**Comment by r2d4** [comment]
Thanks for the bug report.  I'm not sure how we let this one get past our integration tests.  I've removed the update message for now until we fix this.

**Comment by jimmidyson** [comment]
> I'm not sure how we let this one get past our integration tests

Because there wasn't an integration test for the `minikube dashboard` command... I've added one along with the fix in #776

**Comment by olostan** [comment]
@jimmidyson @dlorenc how to get fixed version? I've run command from doc and got exactly same error.  minikube version: v0.12.1

**Comment by r2d4** [comment]
@olostan This is a few commits after 12.1 but contains another important fix
https://storage.googleapis.com/minikube-builds/776/minikube-windows-amd64.exe
