### ISSUE TITLE
The character device /dev/vboxdrv does not exist: Please upgrade at https://www.virtualbox.org

### ISSUE THREAD

**Issue by muhammadrizwan316** [kubernetes/minikube#7710]
StartHost failed, but will try again: creating host: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-generic.\n\n\t You will not be able to start VMs until this problem is fixed.\n5.2.34_Ubuntur133883". Please upgrade at https://www.virtualbox.org

**Comment by tstromberg** [comment]
Hello @muhammadrizwan316 

The VirtualBox installation on this machine is both very old, and as installed, incompatible with the version of the kernel installed on your machine. Please install VirtualBox 6.1: 

* Ubuntu guide: https://computingforgeeks.com/install-virtualbox-6-on-ubuntu-debian-linux/
* VirtualBox downloads page: https://www.virtualbox.org/wiki/Linux_Downloads

Alternatively, if you are running the latest minikube (v1.9.3), I recommend avoiding VirtualBox entirel and using the Docker driver which is the default on Linux:

* `minikube delete`
* `minikube start --driver=docker`

Please let me know if this helps. Thank you!

**Comment by medyagh** [comment]
@muhammadrizwan316 I haven't heard from you 

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
