### ISSUE TITLE
registry aliases hosts update fails, `diff: command not found`

### ISSUE THREAD

**Issue by tmehlinger** [kubernetes/minikube#7715]
The hosts file update routine in registry aliases uses a recent Fedora image (`registry.fedoraproject.org/fedora`) that doesn't include a `diff` binary. This causes the hosts file update to fail and in turn causes the host environment to resolve registry names via DNS instead of finding aliases in the hosts file.

I've worked around this for now by modifying the [`registry-aliases-hosts-update`](https://github.com/kubernetes/minikube/blob/v1.9.2/deploy/addons/registry-aliases/node-etc-hosts-update.tmpl#L20) daemon set to use ubuntu instead of fedora.

**Steps to reproduce the issue:** 

1. `minikube start`
2. `minikube addons enable registry`
3. `minikube addons enable registry-aliases`
4. `kubectl -n kube-system logs registry-aliases-hosts-update-XXXXX -c update`

**Full output of failed command:** 

The relevant output is the log from the update container in the host update pod:

```
10.111.151.247	example.org
10.111.151.247	example.com
10.111.151.247	test.com
10.111.151.247	test.org
bash: line 7: diff: command not found
Done.
```

**Comment by tstromberg** [comment]
@tmehlinger - Great detective work, and excellent reproduction instructions.

Can you please send your change to `deploy/addons/registry-aliases/node-etc-hosts-update.tmpl`  in the form of a PR?

Thank you!

**Comment by tstromberg** [comment]
FYI, we provide some additional addon docs here: https://minikube.sigs.k8s.io/docs/contrib/addons/

**Comment by tmehlinger** [comment]
@tstromberg I wasn't watching notifications, sorry! I've opened #7864 to fix this.
