### ISSUE TITLE
windows: virtualbox: Could not find matching IP for MAC address

### ISSUE THREAD

**Issue by safoueneraddaoui** [kubernetes/minikube#7725]
X Failed to start virtualbox VM. "minikube start" may fix it.: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027617e85

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines and driver used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by safoueneraddaoui** [comment]
i'm using windows 10 home , 
I just installed minikube & kubectl 
when i tray minikube start i get this error : 
! StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027617e85
* Updating the running virtualbox "minikube" VM ...
*
X Failed to start virtualbox VM. "minikube start" may fix it.: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027617e85

**Comment by medyagh** [comment]
@safoueneraddaoui thanks for the reponse, do you mind sharing the version of minikube as well?

and could u try this and paste the fulloutput?


```
minikube delete --all
minikube start --alsologtostderr -v=9
```

I suspect this might be an issue of virtualbox needing to pass the correct nic-type


howwever I am curious if u have docker installed on your windows ?
in that case you can use minikube start --driver=docker 
docker is our newest driver is better performance virtualbox

**Comment by safoueneraddaoui** [comment]
docker is installed on my machine

**Comment by s709t** [comment]
I'm having the same issue here, i can't use docker driver since i'm using docker-toolbox so

**Comment by tstromberg** [comment]
Hey ya'll - to help me figure this out, do you mind helping by sharing the output for a couple of things?

* `minikube start --alsologtostderr -v=1`
* `VBoxManage -version`
* `VBoxManage guestproperty enumerate minikube | grep /Net/`
* `VBoxManage list hostonlyifs`

Thank you! Also, does `minikube delete` workaround the problem?

**Comment by medyagh** [comment]
@s709t I am curious what is docker toolbox why that would prevent u from using docker driver?

and we just released 1.10.1 that fixes two windows bugs, do u mind trying with that?

**Comment by tstromberg** [comment]
Can anyone confirm if minikube v1.10.1 has this issue?

**Comment by gscott187** [comment]
I'm trying to run minikube v1.10.1 on Windows 10 and I'm seeing the same issues using VMware Workstation 15.5.2 build-15785246.

**Comment by medyagh** [comment]
@gscott187 this issue is for virtualbox, do u mind creating a new issue for vmware? I believe we have fixed this for virtualbox. @s709t I am gonna close this, please feel free to reopen if needed

**Comment by sannnan** [comment]
> i'm using windows 10 home ,
> I just installed minikube & kubectl
> when i tray minikube start i get this error :

I solved it by running `minikube delete` and then `minikube delete --all`

**Comment by aayusranjan** [comment]
> @safoueneraddaoui thanks for the reponse, do you mind sharing the version of minikube as well?
> 
> and could u try this and paste the fulloutput?
> 
> ```
> minikube delete --all
> minikube start --alsologtostderr -v=8
> ```
> 
> I suspect this might be an issue of virtualbox needing to pass the correct nic-type
> you can read about the flags
> 
> ```
> $ minikube start --help | grep nic
>       --host-only-nic-type='virtio': NIC Type used for host only network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
>       --nat-nic-type='virtio': NIC Type used for host only network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
> ```
> 
> howwever I am curious if u have docker installed on your windows ?
> in that case you can use minikube start --driver=docker
> docker is our newest driver is better performance virtualbox

Thanks I solved the issue by running `minikube delete` and `minikube delete --all`
then after that `minikube start --driver=docker`
