### ISSUE TITLE
Massive Cleanup needed: pkg/minikube/service

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7727]
I believe this minikube package is source of a lot of flakes, specially on addon dashboard.

we need to ensure
- use kubernetes wait.Poll to wait on kubernetes objects instead of retry.Expo
- make sure the kubernetes client set does NOT get created on each call ( it retries agressively and not evident that the client is NOT being recreated)
- delgate and use kuberentes wait package, such as wait.Until(condition) instead of aribtary time outs
that way we can esnure till that serviice is not up, do not return, regardless of slow or fast machine.
we can have a max time out. but let kuberentes libs decide if a service is UP
- reduce duplicate functionality between kapi package and service and delegate more to wait. package of kubernetes

**Comment by anencore94** [comment]
Is anyone in charge of this issue now ? If not, I would like to try refactoring to use wait.Poll instead of restry.Expo and arbitrary timeout.

**Comment by medyagh** [comment]
@anencore94 PRs are welcome
