### ISSUE TITLE
lint Dockerfile

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7730]
https://github.com/kubernetes/minikube/blob/3afa3d6970d261746bd7398c30a67d878ddfe3fd/hack/images/kicbase.Dockerfile#L56

**Comment by govargo** [comment]
I came up with the idea to lint the Dockerfile by hadlint.
I'll open another issue.

**Comment by medyagh** [comment]
@govargo that sounds like a good idea to add dockerfile lint

**Comment by govargo** [comment]
@medyagh 
Hi. Could I resend PR to fix this?
Do you have other PR about kic base Dockerfile?

If I should wait for other PR, let me know.

**Comment by govargo** [comment]
This is already fixed in master

https://github.com/kubernetes/minikube/blob/master/deploy/kicbase/Dockerfile

/close
