### ISSUE TITLE
Failed to cache ISO: unable to cache ISO

### ISSUE THREAD

**Issue by fanqingxiang1122** [kubernetes/minikube#7734]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by govargo** [comment]
@fanqingxiang1122 
Hello. Thank you for sharing your experience!
If you don't mind, could you please provide more detail(minikube command & result, `minikube logs`)?

And do you mind trying
`minikube delete --all`
and then
`minikube start --alsologtostderr -v=8 --image-mirror-country=cn --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso --registry-mirror=https://registry.docker-cn.com --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers`

**Comment by medyagh** [comment]
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/


同时，您是否尝试了使用最新版本的minikube的最新驱动程序Docker驱动程序？
你可以尝试
minikube删除
minikube start-驱动程序= docker

有关docker驱动程序签出的更多信息：
https://minikube.sigs.k8s.io/docs/drivers/docker/


I will close this issue for now plz reopen if needed
