### ISSUE TITLE
trouble accessing https://k8s.gcr.io

### ISSUE THREAD

**Issue by safoueneraddaoui** [kubernetes/minikube#7742]
This VM is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
*
X Failed to enable container runtime: enable docker.: NewSession: ssh: disconnect, reason 2: Invalid ssh2 packet type: 232

**Comment by medyagh** [comment]
@safoueneraddaoui  it seems like the documentation link was broken
here is the correct link https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/
does the docs help?
