### ISSUE TITLE
LoadBalancer external IP unroutable on master (service-cluster-ip?)

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7746]
1.  `./out/minikube start --driver=hyperkit`
1. `kubectl create deployment balanced --image=k8s.gcr.io/echoserver:1.4`
1.  `kubectl expose deployment balanced --type=LoadBalancer --port=8081`
1. `./out/minikube tunnel`

The tunnel shows a route `--service-cluster-ip-range='10.96.0.0/12'`

```
Status:	
	machine: minikube
	pid: 67162
	route: 10.96.0.0/12 -> 192.168.64.10
	minikube: Running
	services: [balanced]
    errors: 
		minikube: no errors
		router: no errors
		loadbalancer emulator: no errors
```

`kubectl get services balanced` shows an EXTERNAL-IP in the same range as CLUSTER-IP, rather than the range that the tunnel expects:

```
NAME       TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)          AGE
balanced   LoadBalancer   10.100.105.183   10.100.105.183   8081:31739/TCP   5m27s
```

This IP is not accessible:

```
ping -c1  10.100.105.183
PING 10.100.105.183 (10.100.105.183): 56 data bytes
36 bytes from 192.168.64.1: Time to live exceeded
Vr HL TOS  Len   ID Flg  off TTL Pro  cks      Src      Dst
 4  5  00 5400 45a8   0 0000  01  01 ff3c 192.168.64.1  10.100.105.183 
```

**Comment by tstromberg** [comment]
FWIW, Some of this is may be caused by my lack of understanding here, and/or bad documentation.

**Comment by govargo** [comment]
I reproduced this in my local mac.
I doubted this is kubernetes's specification but wasn't sure.

https://github.com/kubernetes/kubernetes/blob/b54c4eaebbc0eae91071e9bffc160bd9c8ca72d1/staging/src/k8s.io/cloud-provider/fake/fake.go#L181-L202

I'll tried `out/minikube start --extra-config=controller-manager.v=10`.
But no logs about loadbalancer could not be found.
Kubernetes Service is really complex.

**Comment by tstromberg** [comment]
I was able to get this to work.

**Comment by iicky** [comment]
@tstromberg How did you get it to work?

**Comment by ismailsemihsenturk** [comment]
> I was able to get this to work.

@tstromberg  I have the same isssue. How did you get it to work?
