### ISSUE TITLE
docker driver : static ip, make container IPs survive restart.

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7756]
Feature request: assign static IP for minikube docker/podman containers

currently if we stop minikube, we might actually, have a different IP that will cause a kubeadm Reset (expensive)

```
I0417 15:04:19.699937   20147 kubeadm.go:434] needs reset: configs differ:
	-- stdout --
	--- /var/tmp/minikube/kubeadm.yaml	2020-04-17 22:01:08.390045502 +0000
	+++ /var/tmp/minikube/kubeadm.yaml.new	0001-01-01 00:00:00.000000000 +0000
	@@ -1,7 +1,7 @@
	 apiVersion: kubeadm.k8s.io/v1beta1
	 kind: InitConfiguration
	 localAPIEndpoint:
	-  advertiseAddress: 172.17.0.4
	+  advertiseAddress: 172.17.0.2
	   bindPort: 8443
	 bootstrapTokens:
	   - groups:
	@@ -14,25 +14,25 @@
	   criSocket: /var/run/crio/crio.sock
	   name: "crio-20200417T145706-10869"
	   kubeletExtraArgs:
	-    node-ip: 172.17.0.4
	+    node-ip: 172.17.0.2
	   taints: []
	 ---
	 apiVersion: kubeadm.k8s.io/v1beta1
	 kind: ClusterConfiguration
	 apiServer:
	-  certSANs: ["127.0.0.1", "localhost", "172.17.0.4"]
	+  certSANs: ["127.0.0.1", "localhost", "172.17.0.2"]
```

as seen here:
https://storage.googleapis.com/minikube-builds/logs/7752/775a91c/Docker_Linux.html#fail_TestPause%2fserial%2fSecondStartNoReset

**Comment by josedonizetti** [comment]
@medyagh If we create our own custom network, we can set a fixed ip when running the container `--ip`. The problem of creating our own network is possible conflicts of subnets with existing networks, so we would have to try a few subnets options until a non used one is found. 

Although we currently don't worry about this on the kvm2 driver, there is a fixed subnet that could conflict, and if it does we are not trying other options: https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kvm/network.go#L41
