### ISSUE TITLE
TestErrorSpam: cache_images.go: error getting status for <cluster>: Error: No such object

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7760]
in this this it is very clear that Test is unhappy about Error in another Test.
https://storage.googleapis.com/minikube-builds/logs/7752/21ad12f/Docker_Linux.html#fail_TestErrorSpam
```
error_spam_test.go:61: unexpected error log: "E0418 01:01:09.373611   32170 cache_images.go:196] error getting status for docker-flags-20200418T005800-24883: state: unknown state"
error_spam_test.go:61: unexpected error log: "E0418 01:01:11.791557   32170 cache_images.go:196] error getting status for pause-20200418T005800-24883: state: \"docker inspect -f {{.State.Status}} pause-20200418T005800-24883\" failed: exit status 1: Error: No such object: pause-20200418T005800-24883"
```

I believe it is better we put this test in our Funcitional Test and make sure no other VM is running while this test finishes.
so there dont be any talking over this test.

**Comment by tstromberg** [comment]
I believe you are misinterpreting the result. This test already runs in serial. I believe this is showing 
 real errors because of state changes related to other clusters. We should either whitelist these errors, or turn them into warnings.

**Comment by priyawadhwa** [comment]
Reopening as I just saw this error on KVM_Linux in #8010

[test logs](https://storage.googleapis.com/minikube-builds/logs/8010/ec74a37/KVM_Linux.html#fail_TestStartStop%2fgroup%2fold-k8s-version)

```
error_spam_test.go:94: minikube stderr:
! Unable to verify SSH connectivity: dial tcp 192.168.99.249:22: i/o timeout. Will retry...
! Unable to verify SSH connectivity: dial tcp 192.168.99.249:22: i/o timeout. Will retry...
error_spam_test.go:96: *** TestErrorSpam FAILED at 2020-05-05 19:51:03.612317896 +0000 UTC m=+1903.983929985
```

**Comment by tstromberg** [comment]
@priyawadhwa - that seems to be an unrelated issue.

**Comment by tstromberg** [comment]
Opened a new issue: #8011
