### ISSUE TITLE
No way to set the API server port in ~/.minikube/config/config.json

### ISSUE THREAD

**Issue by HillebrandtOldenberg** [kubernetes/minikube#7762]
This is a question: is there a way to set the API server port in `~/.minikube/config/config.json` just like you can set the `vm-driver`, for example?

**Steps to reproduce the issue:** 

1. `minikube start --apiserver-port=8443`

**Full output of `minikube start` command used, if not already included:**
```
* minikube v1.9.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Updating the running virtualbox "minikube" VM ...
* Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
* Enabling addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"
```

**Comment by govargo** [comment]
There seems to be no way now.

```
$ out/minikube config
config modifies minikube config files using subcommands like "minikube config set driver kvm"
Configurable fields:

 * driver
 * vm-driver
 * container-runtime
 * feature-gates
 * v
 * cpus
 * disk-size
 * host-only-cidr
 * memory
 * log_dir
 * kubernetes-version
 * iso-url
 * WantUpdateNotification
 * ReminderWaitPeriodInHours
 * WantReportError
 * WantReportErrorPrompt
 * WantKubectlDownloadMsg
 * WantNoneDriverWarning
 * profile
 * bootstrapper
 * ShowDriverDeprecationNotification
 * ShowBootstrapperDeprecationNotification
 * insecure-registry
 * hyperv-virtual-switch
 * disable-driver-mounts
 * cache
 * embed-certs
 * native-ssh
```

**Comment by medyagh** [comment]
@HillebrandtOldenberg that is a per-cluster (profile) config, but once you create a cluster with a specific api server it will always start as that ...you wont need to set it each time

**Comment by medyagh** [comment]
do you mind sharing what is the need for setting the api-server for all clusters of minikube?
do you have multiple clusters of minikube ?

**Comment by HillebrandtOldenberg** [comment]
I only have a single minikube cluster. It's not an important need, but to have a single point of reference for all my minikube settings.

**Comment by medyagh** [comment]
@HillebrandtOldenberg to change the api server port, u would need to re-create the cluster

minikube start --apiserver-port=1313
