### ISSUE TITLE
Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by Thomas-In** [kubernetes/minikube#7773]
Hello,

I got the following error, can you help?

root@minikube:~# minikube start --container-runtime=cri-o
o   minikube v1.0.1 on linux (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running virtualbox VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.99.100
-   Configuring CRI-O as the container runtime ...
-   Version of container runtime is 1.13.1
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.14.1 ...
:   Relaunching Kubernetes v1.14.1 using kubeadm ... 
:   Waiting for pods: apiserver
!   Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

**Comment by tstromberg** [comment]
@Thomas-In - You should upgrade to a more recent release of minikube. 

In the mean-time, you can likely fix the issue by running `minikube delete`, but you will probably run into the issue again until you upgrade. Also, please don't run minikube as root.

**Comment by Thomas-In** [comment]
Thanks to Thomas Strömberg for help. As you advise, it works. Excellent!!!

**Comment by medyagh** [comment]
glad to see this was solved
