### ISSUE TITLE
Unable to download kubectl from storage.googleapis.com

### ISSUE THREAD

**Issue by sayeduzzamancuet** [kubernetes/minikube#7781]
I am trying to download the kubectl.exe file from the url mentioned in the page. The url is https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/windows/amd64/kubectl.exe
But when I am trying to download it, it is showing 

> storage.googleapis.com unexpectedly closed the connection.
Try:

Checking the connection
Checking the proxy and the firewall
Running Windows Network Diagnostics
ERR_CONNECTION_CLOSED

I have checked with site checker and it is saying the site is down. Is there any alternative repository or url from where I can download the kubectl exe for windows amd64?

**Comment by medyagh** [comment]
@sayeduzzamancuet  this is not the right repo for kubectl support issues, this is only for minikube issues.
however I did try that link and it seems to be working for me, please check your VPN or Proxy settings
