### ISSUE TITLE
VM is unable to access auto, you may need to configure a proxy or set --image-repository

### ISSUE THREAD

**Issue by kunalgarg187** [kubernetes/minikube#7783]
Hi, Can someone please help me with the below issue. I am using hyperkit vm to start minikube but not working.
Logs of the command:

**minikube start --vm-driver=hyperkit --image-repository=auto**
😄  minikube v1.9.0 on Darwin 10.14.6
✨  Using the hyperkit driver based on existing profile
✅  Using image repository 
🔄  Retarting existing hyperkit VM for "minikube" ...
❗  Node may be unable to resolve external DNS records
❗  VM is unable to access auto, you may need to configure a proxy or set --image-repository
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

**Comment by medyagh** [comment]
@kunalgarg187  it seems like minikube had detected network issues, it was not able to do nslook up on kuberentes.io

could u check if u are behind a corp vpn or proxy that restricts your access to public intenret?

**Comment by medyagh** [comment]
@kunalgarg187 I hve not heared from you and it seems like you have a network issue, 

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube that would not have the VPN/network issues.
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
