### ISSUE TITLE
document in the contributing section about cgo and libvirt

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7794]
on a fresh ubuntu computer I had to install these to be able to make lint

install cgo
https://github.com/golang/go/wiki/cgo

install libvirt
 sudo apt-get install -y libvirt-dev

**Comment by priyawadhwa** [comment]
/remove-lifecycle stale

This should be mentioned as a prereq for running `make test` as mentioned in #8992

**Comment by anencore94** [comment]
If no one is taking on this issue now, I would love to add that section on contributing docs @priyawadhwa
