### ISSUE TITLE
Unable start Minikube on macOS using Virtualbox 6.1.6 r137129 (Qt5.6.3)

### ISSUE THREAD

**Issue by ramsuriti** [kubernetes/minikube#7797]
**Steps to reproduce the issue:** 

1. On MacOS Followed all instructions mentioned below until Minikube install 
https://www.linux.com/audience/enterprise/set-cicd-pipeline-kubernetes-part-1-overview/
2. brew install minikube
3. minikube start --driver=viritualbox (used Version 6.1.6 r137129 (Qt5.6.3))
4. Bunch of permission denied issues have come up 
example : /Users/username/.minikube/cache/images/gcr.io
then finally I have I gave up and succeeded with minikube start --driver=vmwarefusion 

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Hi that document seems to be old I suggest using our newest docker driver.
try this
minikube delete 
minikube start --driver=docker

**Comment by ramsuriti** [comment]
it worked.. thank you

**Comment by medyagh** [comment]
glad to see this was solved
