### ISSUE TITLE
How to create docker images inside minikube registry

### ISSUE THREAD

**Issue by elshanakberov** [kubernetes/minikube#7801]
I'm trying to use kubernetes locally. Thus I installed minikube. When I create deployment object, pods can't find the images within minikube docker registry and pods show status as `ErrImageNeverPull`. To solve the problem I followed these steps:

1. `minikube start`
2. `eval $(minikube docker-env)`
3. I changed `ImagePullPolicy` to `Never` in deployment.yaml file
4. docker-compose build && docker-compose up -d

Even though I followed all these steps images for the project not being created within minikube registry. I have double checked it by running this command `eval $(minikube docker-env -u) `in order to switch back to the local docker registry. Images and Containers have been created within local docker registry.

My question is how can I create docker images within minikube docker registry?

**Comment by priyawadhwa** [comment]
Hey @elshanakberov thanks for opening this issue. Could you please provide the output of:

```
eval $(minikube docker-env)
docker images
```

We also have documentation around different ways to push images and make them available to the cluster here:

https://minikube.sigs.k8s.io/docs/handbook/pushing/

**Comment by elshanakberov** [comment]
Thanks for your reply @priyawadhwa .

After switching to Minikube registry `docker ps` returns images related to the minikube itself.

![Screenshot from 2020-04-21 12-30-44](https://user-images.githubusercontent.com/22943221/79844010-21b07180-83cc-11ea-8255-d1b64a665cfb.png)

**Comment by elshanakberov** [comment]
to verify my terminal is using minikuber’s docker-env I printed out the value of MINIKUBE_ACTIVE_DOCKERD to reflect the cluster name. And output was as such

![Screenshot from 2020-04-21 13-02-00](https://user-images.githubusercontent.com/22943221/79847117-53c3d280-83d0-11ea-9207-949df42af716.png)

**Comment by elshanakberov** [comment]
I have solved the problem by following these steps:

1. I restarted the minikube by executing `minikube start` again
2. I ran `minikube -p minikube docker-env` and it returned following:
![Screenshot from 2020-04-21 13-28-19](https://user-images.githubusercontent.com/22943221/79849777-fd589300-83d3-11ea-9bb0-ec5e7da04112.png)

3. I executed `eval $(minikube -p minikube docker-env)` 
4. Then I ran `docker-compose` commands.

Images and Containers was created within minikube docker registry.

To be honest I don't know why  `eval $(minikube docker-env)` didn't do the job and the differences between `eval $(minikube docker-env)` and `eval $(minikube -p minikube docker-env)`.

If you know the reason please let me know.

**Comment by morhook** [comment]
Have you been using different consoles? This steps should be run on the same console because they modify the environment variables that are not shared in multiple windows/tabs.

**Comment by elshanakberov** [comment]
> Have you been using different consoles? This steps should be run on the same console because they modify the environment variables that are not shared in multiple windows/tabs.

No, I've been using same console all along.

**Comment by priyawadhwa** [comment]
Hey @elshanakberov -- So you can create multiple minikube clusters on a machine, and the `-p`, or `--profile` flag, allows you to specify which cluster you want to interact with (all clusters have unique profile names)

Could you provide out the output of `minikube config get profile`? I'm wondering if you have a profile value set in the global config, which may be the cause of this.

And, can you still reproduce the original error with:

```
minikube start
eval $(minikube docker-env)
```
?

**Comment by elshanakberov** [comment]
> minikube config get profile

The output is as such `Error: specified key could not be found in config
`

**Comment by medyagh** [comment]
@elshanakberov 
have u seen our docs on pushing images?
https://minikube.sigs.k8s.io/docs/handbook/pushing/

btw to see list of your profiles u can do
minikube profile list

and also to set minikube's profile u can do
minikube profile NAME (change name to the name you want to change it to, get it from the profile list above)

**Comment by medyagh** [comment]
@elshanakberov have u had a chance to try the suggestion above?
