### ISSUE TITLE
vmware fusion: vmrun not in path

### ISSUE THREAD

**Issue by TrishaChetani** [kubernetes/minikube#7806]
**Steps to reproduce the issue:** 

1.  Followed this document to install VM ware fusion : https://minikube.sigs.k8s.io/docs/drivers/vmware/
2. brew install docker-machine-driver-vmware
3. minikube config set driver vmware

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

https://i.imgur.com/BC1AJNY.png

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@TrishaChetani from the screenshot that u sent, it seems like that minikube saying the "vmrun" binary is not in the path, could u check if your path includes that in the terminal ?
maybe try "which vmrun"

alterntaively , I am curious if u have tried our newest Docker driver? have support for vmware fusion but we dont have integration tests for it.

**Comment by TrishaChetani** [comment]
@medyagh: Thank you, It working Docker driver. Appreciate your help 

But there is an issue with vmrun
https://i.imgur.com/bLdlcS2.png

**Comment by tstromberg** [comment]
@TrishaChetani - If `vmrun` is not in the $PATH,  it's possible that VMware Fusion may be installed improperly. If it appears that VMware Fusion is installed, you can manually add `vmrun` to your PATH. See: https://kb.vmware.com/s/article/53542

Tip: `vmrun` is typically installed under ` /Applications/VMware Fusion.app/Contents/Public`
