### ISSUE TITLE
TestStartStop/group/crio: error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7808]
as seen here
https://storage.googleapis.com/minikube-builds/logs/7785/573152f/Docker_Linux.html#fail_TestStartStop%2fgroup%2fcrio

[WARNING SystemVerification]: failed to parse kernel config: unable to load kernel module: "configs", output: "modprobe: FATAL: Module configs not found in directory /lib/modules/4.9.0-12-amd64\n", err: exit status 1

**Comment by tstromberg** [comment]
I believe that warning may be normal.

These are the more critical failures:

`	error execution phase wait-control-plane: couldn't initialize a Kubernetes cluster`

and 

`[kubelet-check] The HTTP call equal to 'curl -sSL http://localhost:10248/healthz' failed with error: Get http://localhost:10248/healthz: dial tcp 127.0.0.1:10248: connect: connection refused.`

Basically the kubelet is failing. Perhaps we should be invoking `minikube logs` to show the kubelet logs again when an integration test fails?

**Comment by medyagh** [comment]
I have not seen this error in a while. I think this is closed.
