### ISSUE TITLE
Problem with install minikube start --driver=hyperv

### ISSUE THREAD

**Issue by rendynoviyanto4** [kubernetes/minikube#7822]
PS C:\Windows\system32> minikube start --driver=hyperv
* minikube v1.9.2 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the hyperv driver based on existing profile
* Starting control plane node m01 in cluster minikube
! StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\rendy\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X Failed to start hyperv VM. "minikube start" may fix it.: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\rendy\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

What should I do???

**Comment by govargo** [comment]
Could you try following?
```
$ minikube delete --all

$ minikube start --driver=hyperv --alsologtostderr -v=1
```

If the problem remains, could you mind sharing the output of `minikube start --driver=hyperv --alsologtostderr -v=1`?

**Comment by rendynoviyanto4** [comment]
![err1](https://user-images.githubusercontent.com/61722805/79859632-81724100-83fb-11ea-94ba-0cab5243fd9a.PNG)

**Comment by rendynoviyanto4** [comment]
![err2](https://user-images.githubusercontent.com/61722805/79859913-fb0a2f00-83fb-11ea-8dd6-8bccf6fbf92e.PNG)

**Comment by rendynoviyanto4** [comment]
![err3](https://user-images.githubusercontent.com/61722805/79859950-08271e00-83fc-11ea-9ccb-0f166c84ce07.PNG)

**Comment by rendynoviyanto4** [comment]
![err4](https://user-images.githubusercontent.com/61722805/79859976-1412e000-83fc-11ea-87d4-0d588985d117.PNG)

**Comment by rendynoviyanto4** [comment]
![err5](https://user-images.githubusercontent.com/61722805/79860007-20973880-83fc-11ea-996e-31694c316df9.PNG)

**Comment by rendynoviyanto4** [comment]
![err6](https://user-images.githubusercontent.com/61722805/79860075-3c9ada00-83fc-11ea-9aac-bf7e663892e8.PNG)

**Comment by rendynoviyanto4** [comment]
![err7](https://user-images.githubusercontent.com/61722805/79860090-46bcd880-83fc-11ea-8817-b0ba49f3186f.PNG)

**Comment by rendynoviyanto4** [comment]
![err8](https://user-images.githubusercontent.com/61722805/79860117-52100400-83fc-11ea-8c20-cfa5775400aa.PNG)

**Comment by rendynoviyanto4** [comment]
Yes, I also try this
$ minikube delete --all

$ minikube start --driver=hyperv --alsologtostderr -v=1

but it's same like that

**Comment by govargo** [comment]
Thank you for sharing output.

It looks like the free memory is not enough.
`Not enough memory in the system to start the virtual machine minikube.`
`FullyQualifiedErrorid : OutOfMemory, MicroSoft.HyperV.PowerShell.Commands.StartVM`

Could you check if your machine has sufficient memory?
Minikube requires 2200MB at least.

**Comment by sharifelgamal** [comment]
@rendynoviyanto4 Have you checked if your machine has enough memory?

**Comment by sharifelgamal** [comment]
Hey @rendynoviyanto4  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
