### ISSUE TITLE
docker driver: permission denied connecting to docker daemon

### ISSUE THREAD

**Issue by hassankhan98** [kubernetes/minikube#7831]
'docker' driver reported an issue: exit status 1
💡  Suggestion: Docker is not running or is responding too slow. Try: restarting docker desktop.

👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
E0421 23:23:17.442817    4419 cache.go:114] Error downloading kic artifacts:  error loading image: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/load?quiet=0: dial unix /var/run/docker.sock: connect: permission denied
🤷  docker "minikube" container is missing, will recreate.
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: creating volume for minikube container: output Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/volumes/create: dial unix /var/run/docker.sock: connect: permission denied
: exit status 1
🤷  docker "minikube" container is missing, will recreate.

💣  Failed to start docker container. "minikube start" may fix it.: recreate: creating host: create: creating: create kic node: creating volume for minikube container: output Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.38/volumes/create: dial unix /var/run/docker.sock: connect: permission denied
: exit status 1

**Comment by priyawadhwa** [comment]
Hey @hassankhan98 looks like you don't have permissions to access the docker daemon. When you use docker, do you currently have to run as root (e.g. `sudo docker run hello-world` works but `docker run hello-world` doesn't work)?

If so, could you try following these instructions to run docker without sudo? This should fix the minikube issue:


https://docs.docker.com/engine/install/linux-postinstall/

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this @hassankhan98. Feel free to reopen with more detail if this is still an issue.
