### ISSUE TITLE
Executing "docker inspect -f {{.State.Status}} minikube" took an unusually long time

### ISSUE THREAD

**Issue by HM0mar** [kubernetes/minikube#7833]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @HM0mar 

I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
* The full output of `docker ps`
* The full output of `kubectl get po -A`


Thank you for sharing your experience!

**Comment by medyagh** [comment]
@HM0mar I believe this an indication that your docker is too slow

- if you are using windows/mac, you could try to increase the docker-desktop memory
- you can try to prune docker using docker system prune to get rid of abanonded containers and images to make it faster

can you verify if you still facing this issue ?
