### ISSUE TITLE
'minikube' could not initialize memory: Ran out of memory

### ISSUE THREAD

**Issue by amanz25** [kubernetes/minikube#7846]
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

! StartHost failed, but will try again: creating host: create: creating: exit status 1
* Stopping "minikube" in hyperv ...
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0422 10:28:16.500483    7288 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Ran out of memory (0x8007000E).
'minikube' failed to start. (Virtual machine ID 404E3AF5-F7D2-4CD4-8A39-EFF343998471)
Not enough memory in the system to start the virtual machine minikube with ram size 2000 megabytes. (Virtual machine ID 404E3AF5-F7D2-4CD4-8A39-EFF343998471)
'minikube' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID 404E3AF5-F7D2-4CD4-8A39-EFF343998471)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

**Comment by tstromberg** [comment]
It sounds like your machine ran out of memory.

If you are running Docker, you may find it useful to use `--driver=docker` so that minikube can use it's memory reservation. Otherwise, you may just have to quit some applications to get minikube to run - it will need 2GB.

**Comment by a-prezioso** [comment]
Using --driver=docker means has a lot of limitation (like not possibility of using addons).. I'm trying to assign more than 4 gb to minikube VM on Hyper-v but doesn't work. Any suggestions?

**Comment by medyagh** [comment]
@a-prezioso  most of the addons work on docker driver now. is there any specific addon you need that doesn't work ?

**Comment by priyawadhwa** [comment]
Hey @a-prezioso are you still seeing this issue?

**Comment by priyawadhwa** [comment]
Hey @a-prezioso -- I'm going to close this issue as some time has passed without an update. If you're still seeing this issue with the latest version of minikube & require support, please feel free to reopen at any time by including `/reopen` in your comment!
