### ISSUE TITLE
virtualbox: read tcp 127.0.0.1:56132->127.0.0.1:42517: read: connection reset by peer

### ISSUE THREAD

**Issue by vetbijaya** [kubernetes/minikube#7853]
**Steps to reproduce the issue:** 

1.I am using Ubuntu 18.04.1 version on Oracle Virtual Box 6.1 behind the company proxy. I already configured the proxy settings.
2. I installed minikube and kubectl 
3. I am getting error while I'm starting the minikube. 

**Full output of failed command:** 
When I use, $ minikube start --alsologtostderr -v=10 command below is the output:
I0422 14:31:58.356569    3306 notify.go:125] Checking for updates...
I0422 14:31:58.839489    3306 start.go:262] hostinfo: {"hostname":"airshipui-VirtualBox","uptime":471,"bootTime":1587579847,"procs":279,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.3.0-46-generic","virtualizationSystem":"kvm","virtualizationRole":"host","hostid":"d98e476a-627f-48a3-adc1-ccca1c7779da"}
I0422 14:31:58.840111    3306 start.go:272] virtualization: kvm host
😄  minikube v1.9.2 on Ubuntu 18.04
I0422 14:31:58.849039    3306 driver.go:245] Setting default libvirt URI to qemu:///system
✨  Using the virtualbox driver based on existing profile
I0422 14:31:58.949443    3306 start.go:310] selected driver: virtualbox
I0422 14:31:58.949532    3306 start.go:656] validating driver "virtualbox" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.9.0.iso Memory:5900 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[HTTP_PROXY=http://one.proxy.att.com:8888 HTTPS_PROXY=http://one.proxy.att.com:8888 NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.0.2.15,192.168.56.105 HTTP_PROXY=http://one.proxy.att.com:8888 HTTPS_PROXY=http://one.proxy.att.com:8888 NO_PROXY=localhost,127.0.0.1,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,10.0.2.15,192.168.56.105] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.0 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:0 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.18.0 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0422 14:31:58.949711    3306 start.go:662] status for virtualbox: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0422 14:31:58.949927    3306 start.go:1004] Using suggested 5900MB memory alloc based on sys=23750MB, container=0MB
I0422 14:31:58.950091    3306 start.go:1210] Wait components to verify : map[apiserver:true system_pods:true]
I0422 14:31:58.950180    3306 iso.go:119] acquiring lock: {Name:mkbe7a156002ea688bca5395a0d368f1c54d9237 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
👍  Starting control plane node m01 in cluster minikube
I0422 14:31:58.953423    3306 preload.go:81] Checking if preload exists for k8s version v1.18.0 and runtime docker
I0422 14:31:58.953957    3306 preload.go:97] Found local preload: /home/airshipui/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4
I0422 14:31:58.954047    3306 cache.go:46] Caching tarball of preloaded images
I0422 14:31:58.954166    3306 preload.go:123] Found /home/airshipui/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0422 14:31:58.954244    3306 cache.go:49] Finished downloading the preloaded tar for v1.18.0 on docker
I0422 14:31:58.954452    3306 profile.go:138] Saving config to /home/airshipui/.minikube/profiles/minikube/config.json ...
I0422 14:31:58.955001    3306 cache.go:117] Successfully downloaded all kic artifacts
I0422 14:31:58.955164    3306 start.go:260] acquiring machines lock for minikube: {Name:mka75c9d77e4552bec8df3abfdbf18f3b3da0ec4 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0422 14:31:58.955382    3306 start.go:264] acquired machines lock for "minikube" in 104.703µs
I0422 14:31:58.955492    3306 start.go:90] Skipping create...Using existing machine configuration
I0422 14:31:58.955568    3306 fix.go:53] fixHost starting: m01
I0422 14:31:58.956092    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage showvminfo minikube --machinereadable
I0422 14:31:59.173643    3306 main.go:110] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="46e92c23-9427-4c98-b786-4e7f25b5929b"
CfgFile="/home/airshipui/.minikube/machines/minikube/minikube/minikube.vbox"
SnapFldr="/home/airshipui/.minikube/machines/minikube/minikube/Snapshots"
LogFldr="/home/airshipui/.minikube/machines/minikube/minikube/Logs"
hardwareuuid="46e92c23-9427-4c98-b786-4e7f25b5929b"
memory=10731
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="poweroff"
VMStateChangeTime="2020-04-22T18:31:23.821000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="/home/airshipui/.minikube/machines/minikube/boot2docker.iso"
"SATA-ImageUUID-0-0"="243829fb-0e24-4f1f-ac68-bcb1beca423f"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/home/airshipui/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="910331b5-9359-4ee5-a340-9138a11e6ee2"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="080027F4061C"
cableconnected1="on"
nic1="nat"
nictype1="virtio"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,42517,,22"
hostonlyadapter2="vboxnet0"
macaddress2="080027B8DE06"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="pulse"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="hosthome"
SharedFolderPathMachineMapping1="/home"
videocap="on"
videocapaudio="off"
capturescreens="0"
capturefilename="/home/airshipui/.minikube/machines/minikube/minikube/minikube.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts="vc_enabled=true,ac_enabled=false,ac_profile=med"
GuestMemoryBalloon=0
}
I0422 14:31:59.173774    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:31:59.173874    3306 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
I0422 14:31:59.173910    3306 fix.go:109] exists: true err=<nil>
I0422 14:31:59.173916    3306 fix.go:110] %!q(<nil>) vs "machine does not exist"
W0422 14:31:59.173932    3306 fix.go:130] unexpected machine state, will restart: <nil>
🔄  Restarting existing virtualbox VM for "minikube" ...
I0422 14:31:59.186345    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage showvminfo minikube --machinereadable
I0422 14:31:59.426760    3306 main.go:110] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="46e92c23-9427-4c98-b786-4e7f25b5929b"
CfgFile="/home/airshipui/.minikube/machines/minikube/minikube/minikube.vbox"
SnapFldr="/home/airshipui/.minikube/machines/minikube/minikube/Snapshots"
LogFldr="/home/airshipui/.minikube/machines/minikube/minikube/Logs"
hardwareuuid="46e92c23-9427-4c98-b786-4e7f25b5929b"
memory=10731
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="poweroff"
VMStateChangeTime="2020-04-22T18:31:23.821000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="/home/airshipui/.minikube/machines/minikube/boot2docker.iso"
"SATA-ImageUUID-0-0"="243829fb-0e24-4f1f-ac68-bcb1beca423f"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/home/airshipui/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="910331b5-9359-4ee5-a340-9138a11e6ee2"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="080027F4061C"
cableconnected1="on"
nic1="nat"
nictype1="virtio"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,42517,,22"
hostonlyadapter2="vboxnet0"
macaddress2="080027B8DE06"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="pulse"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="hosthome"
SharedFolderPathMachineMapping1="/home"
videocap="on"
videocapaudio="off"
capturescreens="0"
capturefilename="/home/airshipui/.minikube/machines/minikube/minikube/minikube.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts="vc_enabled=true,ac_enabled=false,ac_profile=med"
GuestMemoryBalloon=0
}
I0422 14:31:59.426954    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:31:59.427055    3306 main.go:110] libmachine: Check network to re-create if needed...
I0422 14:31:59.427075    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage list hostonlyifs
I0422 14:31:59.541908    3306 main.go:110] libmachine: STDOUT:
{
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::800:27ff:fe00:0
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

}
I0422 14:31:59.541987    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:31:59.542399    3306 main.go:110] libmachine: Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
I0422 14:31:59.542439    3306 main.go:110] libmachine: Found: vboxnet0
I0422 14:31:59.542475    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage list dhcpservers
I0422 14:31:59.638183    3306 main.go:110] libmachine: STDOUT:
{
NetworkName:    HostInterfaceNetworking-vboxnet0
Dhcpd IP:       192.168.99.8
LowerIPAddress: 192.168.99.100
UpperIPAddress: 192.168.99.254
NetworkMask:    255.255.255.0
Enabled:        Yes
Global Configuration:
    minLeaseTime:     default
    defaultLeaseTime: default
    maxLeaseTime:     default
    Forced options:   None
    Suppressed opts.: None
        1/legacy: 255.255.255.0
Groups:               None
Individual Configs:   None
}
I0422 14:31:59.638243    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:31:59.638350    3306 main.go:110] libmachine: Removing orphan DHCP servers...
I0422 14:31:59.638370    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage list hostonlyifs
I0422 14:31:59.710221    3306 main.go:110] libmachine: STDOUT:
{
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::800:27ff:fe00:0
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-vboxnet0

}
I0422 14:31:59.710254    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:31:59.710367    3306 main.go:110] libmachine: Adding/Modifying DHCP server "192.168.99.18" with address range "192.168.99.100" - "192.168.99.254"...
I0422 14:31:59.710429    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage list dhcpservers
I0422 14:31:59.788416    3306 main.go:110] libmachine: STDOUT:
{
NetworkName:    HostInterfaceNetworking-vboxnet0
Dhcpd IP:       192.168.99.8
LowerIPAddress: 192.168.99.100
UpperIPAddress: 192.168.99.254
NetworkMask:    255.255.255.0
Enabled:        Yes
Global Configuration:
    minLeaseTime:     default
    defaultLeaseTime: default
    maxLeaseTime:     default
    Forced options:   None
    Suppressed opts.: None
        1/legacy: 255.255.255.0
Groups:               None
Individual Configs:   None
}
I0422 14:31:59.788466    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:31:59.788547    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage dhcpserver modify --netname HostInterfaceNetworking-vboxnet0 --ip 192.168.99.18 --netmask 255.255.255.0 --lowerip 192.168.99.100 --upperip 192.168.99.254 --enable
I0422 14:31:59.875113    3306 main.go:110] libmachine: STDOUT:
{
}
I0422 14:31:59.875159    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:31:59.875200    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage modifyvm minikube --nic2 hostonly --nictype2 virtio --nicpromisc2 deny --hostonlyadapter2 vboxnet0 --cableconnected2 on
I0422 14:31:59.981920    3306 main.go:110] libmachine: STDOUT:
{
}
I0422 14:31:59.982011    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:31:59.982153    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage modifyvm minikube --natpf1 delete ssh
I0422 14:32:00.140323    3306 main.go:110] libmachine: STDOUT:
{
}
I0422 14:32:00.140370    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:32:00.140397    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage modifyvm minikube --natpf1 ssh,tcp,127.0.0.1,42517,,22
I0422 14:32:00.232484    3306 main.go:110] libmachine: STDOUT:
{
}
I0422 14:32:00.232554    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:32:00.232587    3306 main.go:110] libmachine: COMMAND: /usr/bin/VBoxManage startvm minikube --type headless
I0422 14:32:00.736458    3306 main.go:110] libmachine: STDOUT:
{
Waiting for VM "minikube" to power on...
VM "minikube" has been successfully started.
}
I0422 14:32:00.736487    3306 main.go:110] libmachine: STDERR:
{
}
I0422 14:32:00.736496    3306 main.go:110] libmachine: Waiting for an IP...
I0422 14:32:00.736516    3306 main.go:110] libmachine: Getting to WaitForSSH function...
I0422 14:32:00.736571    3306 main.go:110] libmachine: Using SSH client type: native
I0422 14:32:00.736755    3306 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x7bf5d0] 0x7bf5a0 <nil>  [] 0s} 127.0.0.1 42517 <nil> <nil>}
I0422 14:32:00.736773    3306 main.go:110] libmachine: About to run SSH command:
exit 0
I0422 14:33:18.873044    3306 main.go:110] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:56132->127.0.0.1:42517: read: connection reset by peer

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
Is possible that you are nesting VirtualBox VM's? That is super sketchy, even on a good day.

If this is the case, we should definitely add a warning.

If you are running minikube inside of a VirtualBox VM, I recommend running `minikube delete` and using `minikube start --driver=docker`, which will prevent nested virtualization from occurring.

**Comment by vetbijaya** [comment]
Now it is working when I'm trying $ minikube start --driver=docker
Thank you!!
