### ISSUE TITLE
Minkube how to view the installable k8s version, I want to install the latest k8s version but get ”failed to download“ error

### ISSUE THREAD

**Issue by gosoon** [kubernetes/minikube#7861]
**Steps to reproduce the issue:** 

1. $ minikube start --kubernetes-version='v1.18.0'

**Full output of failed command:** 

💿  正在下载 VM boot image...
    > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [-] 100.00% 5.67 MiB p/s 26s
🔥  正在创建 hyperkit 虚拟机（CPUs=2，Memory=2000MB, Disk=20000MB）...
🐳  正在 Docker '18.09.9' 中准备 Kubernetes v1.18.0…
💾  正在下载 kubelet v1.18.0
💾  正在下载 kubeadm v1.18.0

💣  更新 cluster 失败: downloading binaries: downloading kubelet: Error downloading kubelet v1.18.0: failed to download: failed to download to temp file: failed to create validator: failed to create validator: failed to download checksum file: received status code 404

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by govargo** [comment]
Hello. Now latest minikube v1.9.2 supports kubernetes v1.18 as default.
So please consider upgrading minikube to latest.

**Comment by medyagh** [comment]
@gosoon please try minikube v.1.11.0 and believe this should be working there.
