### ISSUE TITLE
TestFunctional/parallel/ServiceCmd fail: Permission denied: Consumer 'project:hello-minikube-zero-install' has been suspended.

### ISSUE THREAD

**Issue by govargo** [kubernetes/minikube#7868]
In CI `functional_test_docker_ubuntu`, `TestFunctional/parallel/ServiceCmd` failes due to `Permission denied: Consumer 'project:hello-minikube-zero-install' has been suspended.`.

The detail log:
https://github.com/kubernetes/minikube/pull/7849/checks?check_run_id=612588690#step:7:347

```
Failed to pull image "gcr.io/hello-minikube-zero-install/hello-node": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/hello-minikube-zero-install/hello-node/manifests/latest: denied: Permission denied: Consumer 'project:hello-minikube-zero-install' has been suspended.
```

I tried `docker pull` in my local mac PC, but I cannot pull it.

```
$ docker pull gcr.io/hello-minikube-zero-install/hello-node
Using default tag: latest
Error response from daemon: Get https://gcr.io/v2/hello-minikube-zero-install/hello-node/manifests/latest: denied: Permission denied: Consumer 'project:hello-minikube-zero-install' has been suspended.
```

Anything changed?

```
Permission denied: Consumer 'project:hello-minikube-zero-install' has been suspended.
```

**Comment by priyawadhwa** [comment]
Thanks for opening this issue @govargo ! It's really helpful as we've been trying to make our integration tests reliable for the new release. Should be fixed by #7873
