### ISSUE TITLE
revert Makefile changes to ISO_VERSION

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7870]
after our beta release we will need to go back to the default that we didn't need to build an ISO each time
https://github.com/kubernetes/minikube/commit/b419996b347f8e8f615b80a020c9c739d62e8dea#diff-b67911656ef5d18c4ae36cb6741b7965

**Comment by tstromberg** [comment]
This is part of our standard release instructions - is tracking another bug really necessary?

**Comment by medyagh** [comment]
not sure if it was our standard process. or was a mistake. just make sure for 1.10 we go back to main release process

**Comment by tstromberg** [comment]
I'll update the process docs to clarify.
