### ISSUE TITLE
experimental drivers are not listed in "unable to pick a default driver" display

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7883]
This should have shown something like `podman: experimental (try with --driver=podman)`:

```
😄  minikube v1.10.0-beta.1 on Fedora 32
👎  Unable to pick a default driver. Here is what was considered, in preference order:
   ▪ docker: Not installed: exec: "docker": executable file not found in $PATH
   ▪ kvm2: Not installed: exec: "virsh": executable file not found in $PATH
   ▪ none: Not installed: exec: "docker": executable file not found in $PATH
   ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH
   ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH
👉  Try specifying a --driver, or see https://minikube.sigs.k8s.io/docs/start/
```

**Comment by afbjorklund** [comment]
This was probably a good thing, considering how broken it was ? :-D

Also, we should only show the podman driver when running on Linux.

**Comment by radeksm** [comment]
@tstromberg I run:
`[radek@c8k14 ~]$  ./minikube-linux-amd64 version `
`minikube version: v1.10.0-beta.1`
`commit: 947dc217019cebedde01e74430c17a9f420b1d3f-dirty`

and I can see podman listed here:
`[radek@c8k14 ~]$  ./minikube-linux-amd64   start `
`😄  minikube v1.10.0-beta.1 on Centos 8.1.1911`
`👎  Unable to pick a default driver. Here is what was considered, in preference order:`
`    ▪ docker: Not installed: exec: "docker": executable file not found in $PATH`
`    ▪ kvm2: Not installed: exec: "virsh": executable file not found in $PATH`
`    ▪ none: Not installed: exec: "docker": executable file not found in $PATH`
`    ▪ podman: Not installed: exec: "podman": executable file not found in $PATH`
`    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH`
`    ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH`

@afbjorklund looks like we don't have anything like platform value in driver(s) or in registry.

**Comment by afbjorklund** [comment]
Theoretically you can use podman (remote) on Mac and Win too...

It is just that I don’t want to support it, it makes even less sense than Docker Desktop - we would just have to connect to a somebody else’s VM. And then fix _their_ bugs and their lack of documentation, without have access (or even source). I would rather use the “generic” and be given some SSH ? User can set up their VM “properly”

**Comment by afbjorklund** [comment]
Looks like we are excluding CentOS from the podman driver, due to requiring >= 1.7.0 ?

```go
// minReqPodmanVer is required the mininum version of podman to be installed for podman driver.
var minReqPodmanVer = semver.Version{Major: 1, Minor: 7, Patch: 0}
```

@medyagh : do you recall why this newer podman version was required ? 398c7ef00b5e5744fc5ad07e7d700ecae6a11343

Red Hat Enterprise Linux 8.2 just shipped with podman version 1.6.4...

https://www.redhat.com/en/blog/whats-new-red-hat-enterprise-linux-82

> This release includes a new application stream for Red Hat's container tools (container-tools:2.0) that is supported for 24 months, as well as an update to the container-tools:rhel8 stream that includes Podman 1.6.4.

**Comment by afbjorklund** [comment]
It seems to be working OK with CentOS 8.1 and Podman 1.6.4:

```
😄  minikube v1.10.0-beta.1 on Centos 8.1.1911
✨  Using the podman (experimental) driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v3-v1.18.0-docker-overlay2-amd64.tar.lz4: 525.45 MiB
🔥  Creating podman container (CPUs=2, Memory=2200MB) ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
💡  For best results, install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/
```

There are still some networking issues, when CentOS is in a VM.

----

Biggest 1.6 issue so far seems to be that you cannot mix Go **and** JSON:

```
/tmp/minikube.localhost.admin.log.WARNING.20200426-192503.21772:W0426 19:25:03.920505   21772 podman.go:95] Warning ! mininim required version for podman is 1.7.0. your version is "1.6.4". minikube might not work. use at your own risk. To install latest version please see https://podman.io/getting-started/installation.html 
/tmp/minikube.localhost.admin.log.WARNING.20200426-192503.21772:W0426 19:25:04.556100   21772 start_flags.go:218] Unable to query memory limits: get podman system info: sudo podman system info --format "{{json .}}": exit status 125
```

Fortunately we can easily avoid that by just using `--format json` instead.

**Comment by afbjorklund** [comment]
Once the minor remaining issues are done, podman should become `Default` (where available)

On Linux, that is. It will definitely stay Experimental on Mac and Windows - since it needs a VM.

Basically it will **only** be used on Fedora and RHEL / CentOS, where Docker is harder to install...

All others will run with either `docker-ce` (from binary) or `docker.io` or `moby-engine` (from source)
