### ISSUE TITLE
The image source from the Hello Minicube tutorial doesn't work

### ISSUE THREAD

**Issue by lnikolenko** [kubernetes/minikube#7901]
**Steps to reproduce the issue:** 

1. Launch the shell from https://kubernetes.io/docs/tutorials/hello-minikube/ tutorial
2. `kubectl create deployment hello-node --image=gcr.io/hello-minikube-zero-install/hello-node`
3. `kubectl expose deployment hello-node --type=LoadBalancer --port=8080`
4. `minikube service hello-node`

**Full output of failed command:** 
```
|-----------|------------|-------------|--------------------------|
| NAMESPACE |    NAME    | TARGET PORT |           URL            |
|-----------|------------|-------------|--------------------------|
| default   | hello-node |             | http://172.17.0.31:30553 |
|-----------|------------|-------------|--------------------------|
 Opening service default/hello-node in default browser...
Minikube Dashboard is not supported via the interactive terminal experience.

Please click the 'Preview Port 30000' link above to access the dashboard.
This will now exit. Please continue with the rest of the tutorial.

X open url failed: http://172.17.0.31:30553: exit status 1

minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

```
**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

I think the issue comes from revoked permissions to an image gcr.io/hello-minikube-zero-install/hello-node .
</details>

**Comment by medyagh** [comment]
@lnikolenko thanks for brining this our attention, that image is indeeded no longer a good image, and needs to be updated. If you make a PR on the kubernetes website and add me as the approver, I would be happy to review that PR

**Comment by medyagh** [comment]
meanwhile if u still like to do an example I recommend, trying our quick start guide https://minikube.sigs.k8s.io/docs/start/

**Comment by medyagh** [comment]
been fixed
