### ISSUE TITLE
Upgrade Buildroot to 2020.02 LTS

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#7904]
The current release is nearing EOL. We should upgrade to the next LTS.
> Notice that the 2019.02.x series is now end of life unless somebody
> steps up to take over maintenance. Please migrate to the 2020.02 series
> instead which will be supported until April 2021.

"Buildroot 2020.02 released"
http://lists.busybox.net/pipermail/buildroot/2020-March/276231.html

"Buildroot 2019.02.11 released, 2019.02.x is EOL"
http://lists.busybox.net/pipermail/buildroot/2020-April/279523.html

This will feature upgrade Linux to 5.4 (~4.19~) and systemd to 244 (~240~)

Also upgrades Binutils to 2.32 (~2.30~) and GCC to 8.4.0 (~7.5.0~)
and the system Go compiler is bumped from 1.11.13 to 1.13.14

Also need to upgrade VirtualBox, to get guest additions support for Linux 5.4

**Comment by afbjorklund** [comment]
The original CoreOS (Container Linux) is also reaching EOL, on May 26, 2020.

See http://coreos.com/os/eol/

So we might look at Fedora CoreOS for inspiration, or we might continue on our own.

The current ISO was changed from Boot2Docker-based to Buildroot-based, in 2016.

See #571 #692 (commit f0b7abf42e90e5a8b47237ae4524a130647fcbf8)

Now that we don't support rkt anymore, we could look at rearranging some things...

**Comment by afbjorklund** [comment]
One thing we should do is to _downgrade_ the glibc toolchain headers, to be more compatible:

```diff
-BR2_TOOLCHAIN_HEADERS_AT_LEAST="5.4"
+BR2_TOOLCHAIN_HEADERS_AT_LEAST="4.0"
```

```
BR2_LINUX_KERNEL_VERSION="5.4.40"
```

This is so that we can start looking into running the ISO image also as a KIC image... #6942

`docker import - minikube < output/images/rootfs.tar`

` FATAL: kernel too old`

**Comment by afbjorklund** [comment]
> One thing we should do is to _downgrade_ the glibc toolchain headers, to be more compatible:

> This is so that we can start looking into running the ISO image also as a KIC image... #6942

Out of scope for the 1.11 release, and not certain that we should use the _same_ defconfig

So work on making an image for KIC will be in that other issue, this will be only about the VM.

**Comment by afbjorklund** [comment]
The new ISO seems to be more sensitive to dockerd vs containerd timing: #8203

**Comment by Conan-Kudo** [comment]
> So we might look at Fedora CoreOS for inspiration, or we might continue on our own.

I'd love to see a Fedora CoreOS based system. 😄

**Comment by afbjorklund** [comment]
> I'd love to see a Fedora CoreOS based system. :smile:

There is already [CRC](https://github.com/code-ready/crc) for that, so need to describe what features you are missing from [CoreOS](https://coreos.com/blog/coreos-tech-to-combine-with-red-hat-openshift).
Currently I think the only user-visible feature is the `toolbox`, but there could be others as well.

The Ignition is more of a hassle than a feature, and it's not likely to move to snapshot upgrades.
It's also several times bigger, so there needs to some upside to motivate resource requirements.


I have yet failed to use Fedora CoreOS, and am more likely to use regular Fedora distribution...
But _if_ we make an ISO version based on Ubuntu, it is possible to make one based on Fedora.

It's for a completely different issue than this one though, we talked about it in the KIC context.
But basically: if you would like to use Fedora CoreOS then you should be looking at OpenShift.

**Comment by Conan-Kudo** [comment]
Well, I'd be okay with a traditional Fedora system, too. I just assumed that FCOS would be the only way you'd do a Fedora base.

That said, why do you think Fedora CoreOS is tied to OpenShift? It's specifically generally usable for any container workload...

**Comment by afbjorklund** [comment]
> Well, I'd be okay with a traditional Fedora system, too. I just assumed that FCOS would be the only way you'd do a Fedora base.
> 
> That said, why do you think Fedora CoreOS is tied to OpenShift? It's specifically generally usable for any container workload...

Basically Fedora CoreOS was _made_ for OpenShift 4, even if maybe not completely tied to it.
That means it works out of the box with OKD and CRC, but not at all with minikube (or minishift).

And regular Fedora isn't ideal for running Kubernetes, after they moved to Cgroups V2 "early"
But I suppose it _could_ be used as an alternative kicbase image, if one really wanted to do it.

Will keep this issue about Buildroot.

And whatever CoreOS remains in it...

**Comment by Conan-Kudo** [comment]
> And regular Fedora isn't ideal for running Kubernetes, after they moved to Cgroups V2 "early"
But I suppose it _could_ be used as an alternative "kicbase" image, if one really wanted to do it.

With Kubernetes 1.19, cgroup v2 is fully supported though... That said, you could just make minikube switch back to cgroup v1 for Fedora.

**Comment by afbjorklund** [comment]
I think I will leave both Fedora CoreOS and Fedora to _other_ issues, this was just "CoreOS".
As in the current design of the Buildroot ISO, as opposed to the previous Tiny Core Linux ISO.

Most likely we will just gradually fade out any remaining "coreos", like we did earlier with "rkt".
The OS version upgrade will be plenty for 1.12, without any additional changes to the content.

**Comment by afbjorklund** [comment]
Reverted

**Comment by medyagh** [comment]
we still like to do this, we love to see this land in v1.14.0
