### ISSUE TITLE
aws vm: Error : there are only 1 CPUs available.

### ISSUE THREAD

**Issue by r-suresh-kumar** [kubernetes/minikube#7907]
**Steps to reproduce the issue:** 

Pre-condition:
I am using Amazon EC2 linux instance with virtualization set to hvm.
But when I use command "grep -E --color 'vmx|svm' /proc/cpuinfo" to check if virtualization is enabled or disabled, it does not give any response.......I guess, virtualization is disabled. Please correct me if i am wrong

1. $ minikube start --vm-driver=none

OR

2. $ minikube start --driver=docker

OR

3. $ minikube start --no-vtx-check=false

  minikube v1.9.2 on Amazon 2018.03 (xen/amd64)
  Using the docker driver based on existing profile
  Starting control plane node m01 in cluster minikube
  Pulling base image ...
  docker "minikube" container is missing, will recreate.
  Creating Kubernetes in docker container with (CPUs=2) (1 available), Memory=985MB (985MB available) ...
  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=985mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: docker: Error response from daemon: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available.
See 'docker run --help'.
: exit status 125
  docker "minikube" container is missing, will recreate.
  Creating Kubernetes in docker container with (CPUs=2) (1 available), Memory=985MB (985MB available) ...

  Failed to start docker container. "minikube start" may fix it.: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=985mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: docker: Error response from daemon: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available.
See 'docker run --help'.
: exit status 125

  minikube is exiting due to an error. If the above message is not useful, open an issue:
  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@r-suresh-kumar while the error looks scray and I appologize we need to make the error look better, and provide better action,

it seems that you are running minikube on VM with only 1 CPU ?  the minimum required number of CPU cores are 2. could you please verify and try with a VM with higher CPU ccounts?

**Comment by r-suresh-kumar** [comment]
Thank you for the response. Let me check and fix your recommendations.

**Comment by tstromberg** [comment]
minikube needs 2 CPU's. We'll need to clean up the error message to be more actionable, as well as add a FAQ item.
