### ISSUE TITLE
ingress on kubernetes docs is broken

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7910]
following the docs on linux with KVM2 driver.

https://kubernetes.io/docs/tasks/access-application-cluster/ingress-minikube/

( the docs has a few syntax errorr too but after fixing them)
curl hello-world.info would just hang.

**Comment by tstromberg** [comment]
Which driver was this?

**Comment by medyagh** [comment]
I tried it with kvm2 and both our own docs and kubernets docs seems to broken

**Comment by medyagh** [comment]
cc: @josedonizetti

**Comment by tstromberg** [comment]
AFAIK, this is still an issue.
