### ISSUE TITLE
issue of not creating minikube cluster

### ISSUE THREAD

**Issue by pratap6t6** [kubernetes/minikube#7914]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=1` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
