### ISSUE TITLE
kicbase does not respect --image-repository or --image-mirror-country flags

### ISSUE THREAD

**Issue by wenhui-prudencemed** [kubernetes/minikube#7915]
**Steps to reproduce the issue:** 

minikube start --image-mirror-country=cn --alsologtostderr

**Full output of failed command:** 

I0426 21:05:42.188776    5845 cache.go:66] save to tar file registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.18.0 -> /home/prudencemed/.minikube/cache/images/registry.cn-hangzhou.al
iyuncs.com/google_containers/kube-apiserver_v1.18.0 succeeded
I0426 21:05:42.188790    5845 cache.go:73] Successfully saved all images to host disk.
E0426 21:08:16.404783    5845 cache.go:117] Error downloading kic artifacts:  getting remote image: Get https://gcr.io/v2/: dial tcp 64.233.189.82:443: i/o timeout
I0426 21:08:16.405202    5845 start.go:221] acquiring machines lock for minikube: {Name:mk658abb5985c745ceef5c35481ecb92e05e0b87 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0426 21:08:16.405286    5845 start.go:225] acquired machines lock for "minikube" in 61.735µs
I0426 21:08:16.405304    5845 start.go:85] Skipping create...Using existing machine configuration
I0426 21:08:16.405312    5845 fix.go:53] fixHost starting:
I0426 21:08:16.405572    5845 oci.go:268] executing with [docker inspect -f {{.State.Status}} minikube] timeout: 19s
I0426 21:08:16.437775    5845 fix.go:105] recreateIfNeeded on minikube: state=Error err="docker inspect -f {{.State.Status}} minikube" failed: exit status 1: Template parsing error: template: :1:8: exec
uting "" at <.State.Status>: map has no entry for key "State"
I0426 21:08:16.437806    5845 fix.go:110] machineExists: false. err=machine does not exist
🤷  docker "minikube" container is missing, will recreate.
I0426 21:08:16.452437    5845 delete.go:117] DEMOLISHING minikube ...

**Environment: minikube v1.10.0-beta.1 on Ubuntu 18.04**

seems it still try to access gcr.io after I set --image-mirror-country=cn

maybe the image mirror doesn't download kicbase:v0.0.9 to local?

**Comment by afbjorklund** [comment]
This is still a work-in-progress, see #7447 #7844. On `master` you can now select another location.

`      --base-image='gcr.io/k8s-minikube/kicbase:v0.0.9@sha256:82a826cc03c3e59ead5969b8020ca138de98f366c1907293df91fc57205dbb53': The base image to use for docker/podman drivers. Intended for local development.`

More of a workaround, though. It should probably use the same registry mirror as the other images ?

**Comment by tstromberg** [comment]
Agreed - this is a bug. It seems that even if the other issues are fixed, the kicbase code specifically does not yet support --image-mirror.

On the upside, now that master has support a `--base-image` flag, it should be easy for someone to update the default value to respect `--image-repository.

**Comment by afbjorklund** [comment]
We are also thinking to **not** use `pull`, but to download a regular tarball instead: #7766

In that case, it would work just like the ISO and avoid these issues with the registries ?

**Comment by tstromberg** [comment]
Not using pull seems besides the point. If this is implemented as a Docker image, it should respect the same flag that other docker pulls do.

**Comment by afbjorklund** [comment]
> Not using pull seems besides the point

Sure, just that it will obsolete this feature ?

**Comment by medyagh** [comment]
this is same as https://github.com/kubernetes/minikube/issues/7447

**Comment by febzhang** [comment]
This is still an issue.

```
$ minikube version
minikube version: v1.23.2
commit: 0a0ad764652082477c00d51d2475284b5d39ceed
```
