### ISSUE TITLE
Clarify --addons flag syntax

### ISSUE THREAD

**Issue by Wastack** [kubernetes/minikube#7920]
I would like to start Minikube with one of the following commands, in order to start Minikube with more than one addons enabled:
`minikube start --addons="ingress registry-creds"`
`minikube start --addons="ingress, registry-creds"`
`minikube start --addons="ingress; registry-creds"`

None of the above seems to work.

In the [docs](https://minikube.sigs.k8s.io/docs/commands/start/), I can see that the required type is _minikube addons list_, although the actual syntax is not clear to me.

Anyways, I can enable multiple addons using mutiple `minikube addons` subcommand issued when Minikube is already started.

**Comment by prasadkatti** [comment]
Can you paste the output of `minikube logs`?

**Comment by prasadkatti** [comment]
I just tried `minikube start --addons=dashboard --addons=registry` and it worked for me.

**Comment by Wastack** [comment]
Hmm, indeed, that works. I find the plural form of the flag a bit misleading.
I think it would be great have it documented somewhere.
