### ISSUE TITLE
my  kubectl cant  build  pull  from  registry  server 

### ISSUE THREAD

**Issue by stevenbill** [kubernetes/minikube#7925]
![Screenshot from 2020-04-23 16-34-00](https://user-images.githubusercontent.com/29622827/80471417-af97d980-8943-11ea-8af3-0ea87d3454ad.png)

![Screenshot from 2020-04-22 14-52-38](https://user-images.githubusercontent.com/29622827/80471452-b7f01480-8943-11ea-85ba-a7d4ff7d5a51.png)

when i added on this file /etc/docker/daemon.json

{
"insecure-registries" : ["172.17.0.1:5000"]
}

in my minikube docker show to me first error

and second about kubctl

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by stevenbill** [comment]
![Screenshot from 2020-05-02 13-31-20](https://user-images.githubusercontent.com/29622827/80862974-513b6580-8c79-11ea-970d-d915d0c14874.png)
![Screenshot from 2020-05-02 13-31-12](https://user-images.githubusercontent.com/29622827/80862976-53052900-8c79-11ea-9120-4b4ed5ec7031.png)
![Screenshot from 2020-05-02 13-30-44](https://user-images.githubusercontent.com/29622827/80862977-54365600-8c79-11ea-851f-51a5778bec42.png)
![Screenshot from 2020-05-02 13-30-32](https://user-images.githubusercontent.com/29622827/80862979-54ceec80-8c79-11ea-8d28-49e377d2b91f.png)

i did  all  and  i have same error

**Comment by stevenbill** [comment]
![Screenshot from 2020-05-02 13-32-58](https://user-images.githubusercontent.com/29622827/80862998-77610580-8c79-11ea-8d76-8ccc42294850.png)

**Comment by stevenbill** [comment]
and this  image  from minikube
![Screenshot from 2020-05-02 13-51-30](https://user-images.githubusercontent.com/29622827/80863399-40402380-8c7c-11ea-8a6d-e19579b68fde.png)
  /etc/docker/daemon.json

**Comment by stevenbill** [comment]
and i  did  add  /etc/docker/daemon.json  in  minikube   
then  i restarted minikube docker service  
its  show to me  this 
![Screenshot from 2020-05-02 14-03-43](https://user-images.githubusercontent.com/29622827/80863619-e8a2b780-8c7d-11ea-83ed-48372fe2f778.png)
![Screenshot from 2020-05-02 14-03-19](https://user-images.githubusercontent.com/29622827/80863620-e93b4e00-8c7d-11ea-84c9-836a9ee2d058.png)

**Comment by stevenbill** [comment]
![Screenshot from 2020-05-02 14-08-50](https://user-images.githubusercontent.com/29622827/80863723-78486600-8c7e-11ea-9213-695e97289136.png)
and this  minikube loge  after  edit  file  in   minikube

**Comment by medyagh** [comment]
which driver do u use ?

**Comment by stevenbill** [comment]
kvm2 driver

**Comment by stevenbill** [comment]
thank you

**Comment by stevenbill** [comment]
and  this  in  my  daemon.json  file in  minikube 

  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "storage-driver": "overlay2"
}
~

**Comment by sharifelgamal** [comment]
We have no idea how your minikube is setup without the ability to actually search through logs and the output of minikube start. Could you actually paste them instead of posting screenshots? They would be much more helpful.

**Comment by stevenbill** [comment]
sure

**Comment by stevenbill** [comment]
how  can i  get  my minikube  setup

**Comment by medyagh** [comment]
@stevenbill do you mind pasting the commands that you run from begginng ? are you following any documentation ? are you using Registry addon https://minikube.sigs.k8s.io/docs/handbook/pushing/#4-pushing-to-an-in-cluster-using-registry-addon ?

or are you following another registry docuemntation ? can you tell me what you are trying to do ? and paste for me the list of commands u ran ?

also have u read about our docker-env command ?  ( you can push images directly into the docker inside minikube. here is the link on our website https://minikube.sigs.k8s.io/docs/handbook/pushing/

**Comment by stevenbill** [comment]
https://minikube.sigs.k8s.io/docs/handbook/pushing/#4-pushing-to-an-in-cluster-using-registry-addon 

this  is  a  goog  idea  i  will  try it  but  its  different structure  
my  structure  is  to push  and pull  on local host   registry and  minikube   get  image  from this  localhost

**Comment by stevenbill** [comment]
> @stevenbill do you mind pasting the commands that you run from begginng ? are you following any documentation ? are you using Registry addon https://minikube.sigs.k8s.io/docs/handbook/pushing/#4-pushing-to-an-in-cluster-using-registry-addon ?
> 
> or are you following another registry docuemntation ? can you tell me what you are trying to do ? and paste for me the list of commands u ran ?
> 
> also have u read about our docker-env command ? ( you can push images directly into the docker inside minikube. here is the link on our website https://minikube.sigs.k8s.io/docs/handbook/pushing/

**Comment by medyagh** [comment]
@stevenbill sounds good, have u had any luck with our docs on images?

**Comment by stevenbill** [comment]
> @stevenbill sounds good, have u had any luck with our docs on images?

i tried but   when i  edit the file on  minikube  then  restart  docker  docker  will  show  error to me

**Comment by stevenbill** [comment]
thanks for  all
