### ISSUE TITLE
Starting MiniKF crashed with an error message requesting to contact this project

### ISSUE THREAD

**Issue by jariolehtonen** [kubernetes/minikube#7932]
Hi,

As requested, I'm writing about a problem when trying to launch MiniKF according to https://www.kubeflow.org/docs/started/workstation/getting-started-minikf/ 

Provisioning Minikube ... Kubernetes Cluster takes a long time, and then I always get the problem shown below. I did not manage to find the mentioned logfile provision.log. 

I have Lenovo Thinkpad Win 10 laptop with 16 GB RAM, 4 CPUs. 

Regards,
 Jari

Reason: Command `<ExtCommand [BKkqriBihAQ] `minikube start --v=7 --apiserver-name=10.10.10.10 --apiserver-port=8443--apiserver-ips=10.10.10.10 --apiserver-names=MiniKF --extra-config=kubelet.v=1 --extra-config=kubeadm.ignore-preflight-errors=SystemVerification --extra-config=kubelet.node-ip=10.10.10.10 --extra-config=kubelet.feature-gates=VolumeSnapshotDataSource=true,CSINodeInfo=true,CSIDriverRegistry=true --extra-config=kubelet.image-gc-high-threshold=100 --extra-config=kubelet.image-gc-low-threshold=99 --extra-config=kubelet.eviction-hard=memory.available<10Mi,nodefs.available<10Mi,imagefs.available<10Mi --extra-config=kubelet.eviction-soft=memory.available<10Mi,nodefs.available<10Mi,imagefs.available<10Mi --extra-config=kubelet.eviction-soft-grace-period=memory.available=1h,nodefs.available=1h,imagefs.available=1h --extra-config=apiserver.feature-gates=VolumeSnapshotDataSource=true,CSINodeInfo=true,CSIDriverRegistry=true --extra-config=apiserver.advertise-address=10.10.10.10 --extra-config=apiserver.bind-address=0.0.0.0 --extra-config=apiserver.token-auth-file=/var/lib/minikube/certs/tokens --kubernetes-version=v1.14.3 --extra-config=controller-manager.feature-gates=VolumeSnapshotDataSource=true,CSINodeInfo=true,CSIDriverRegistry=true --extra-config=apiserver.service-account-issuer=api --extra-config=apiserver.service-account-signing-key-file=/var/lib/minikube/certs/sa.key --extra-config=apiserver.service-account-key-file=/var/lib/minikube/certs/sa.pub --extra-config=apiserver.service-account-api-audiences=api --vm-driver=none', status=FINISHED (ret: 70), PID=3567, shell=False>' failed. Error log: \nX Error restarting cluster: waiting for apiserver: timed out waiting for the condition\n\n* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:\n  - https://github.com/kubernetes/minikube/issues/new\n

The logfile `/home/vagrant/provision.log' may contain more information on this error, including a backtrace.

**Comment by tstromberg** [comment]
Any idea what minikube version this is using? I suspect that it may not be a recent one, and the underlying issue may have already been fixed. In the mean-time:

* You can likely fix this issue by upgrading to minikube v1.9.2
* You can likely workaround the issue by running `minikube delete`
* You may be able to debug the issue using `minikube logs`

Please let me know if this advice helps.

**Comment by jariolehtonen** [comment]
Hi,

Well just this evening I tried the MiniKF upgrade sequence of this page: https://www.arrikto.com/minikf/ and it actually helped. Now it seems to work.

Regards,
Jari

**Comment by tstromberg** [comment]
Thanks for the feedback!
