### ISSUE TITLE
integration flake: [KVM_OOM] cannot set up guest memory 'pc.ram': Cannot allocate memory

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#7937]
Seen here: https://storage.googleapis.com/minikube-builds/logs/7896/3bcfebf/KVM_Linux.html

`gvisor_addon_test.go:95: (dbg) Non-zero exit: out/minikube-linux-amd64 start -p gvisor-20200429104009-5416 --memory=2200 --container-runtime=containerd --docker-opt containerd=/var/run/containerd/containerd.sock --driver=kvm2 : exit status 78 (1m17.354381547s)`
...
`* [KVM_OOM] error provisioning host Failed to start host: driver start: error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2020-04-29T17:52:32.323601Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory')`

We may need to optimize the memory settings for our tests.

**Comment by medyagh** [comment]
please use the permanent link in gopogh to link to the exact test
