### ISSUE TITLE
virtualbox: create host timed out in 120 seconds: hostonly interface not found

### ISSUE THREAD

**Issue by kriefsacha** [kubernetes/minikube#7948]
**What i tried**
Running "minikube delete" , didn't changed.
Restart the computer.
Tried with vmware , same thing.
Tried with virtual box opened , same thing , also tried to run the vm when i see it in virtual box and login , same thing.

**Environement**
Windows 10 Home
kubectl v1.18.0
minikube last version
Virtualbox 6.1.6

**Steps to reproduce the issue:** 

1. Run "minikube start --driver=virtualbox" or "minikube start --driver=virtualbox --alsologtostderr" from cmd runed as administrator
2. Click on "yes" when it ask for permissions
3. "StartHost failed" error , "[CREATE_TIMEOUT] Failed to start virtualbox VM. "minikube start" may fix it. creating host: create host timed out in 120.000000 seconds"

**Full output of failed command:** 

> I0430 16:18:50.927165    7716 notify.go:125] Checking for updates...
> I0430 16:18:51.235998    7716 start.go:262] hostinfo: {"hostname":"LAPTOP-DB9LMU92","uptime":3033,"bootTime":1588249698,"procs":245,"os":"windows","platform":"Microsoft Windows 10 Home","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"366009c6-8e98-43b3-bc08-7f067e63a92a"}
> W0430 16:18:51.235998    7716 start.go:270] gopshost.Virtualization returned error: not implemented yet
> * minikube v1.9.2 on Microsoft Windows 10 Home 10.0.18363 Build 18363
> I0430 16:18:51.248963    7716 driver.go:245] Setting default libvirt URI to qemu:///system
> * Using the virtualbox driver based on user configuration
> I0430 16:18:51.356050    7716 start.go:310] selected driver: virtualbox
> I0430 16:18:51.356050    7716 start.go:656] validating driver "virtualbox" against <nil>
> I0430 16:18:51.356050    7716 start.go:662] status for virtualbox: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
...

> I0430 16:19:04.661108    7716 main.go:110] libmachine: Starting the VM...
> I0430 16:19:04.668088    7716 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
> I0430 16:19:04.715051    7716 main.go:110] libmachine: STDOUT:
> {
> name="minikube"
> groups="/"
> ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
> UUID="629125d9-7404-4d93-b2c5-c6f5cc97e8f9"
> CfgFile="C:\\Users\\krief\\.minikube\\machines\\minikube\\minikube\\minikube.vbox"
> SnapFldr="C:\\Users\\krief\\.minikube\\machines\\minikube\\minikube\\Snapshots"
> LogFldr="C:\\Users\\krief\\.minikube\\machines\\minikube\\minikube\\Logs"
> hardwareuuid="629125d9-7404-4d93-b2c5-c6f5cc97e8f9"
> memory=2200
> pagefusion="off"
> vram=8
> cpuexecutioncap=100
> hpet="on"
> cpu-profile="host"
> chipset="piix3"
> firmware="BIOS"
> cpus=2
> pae="on"
> longmode="on"
> triplefaultreset="off"
> apic="on"
> x2apic="off"
> nested-hw-virt="off"
> cpuid-portability-level=0
> bootmenu="disabled"
> boot1="dvd"
> boot2="dvd"
> boot3="disk"
> boot4="none"
> acpi="on"
> ioapic="on"
> biosapic="apic"
> biossystemtimeoffset=0
> rtcuseutc="on"
> hwvirtex="on"
> nestedpaging="on"
> largepages="on"
> vtxvpid="on"
> vtxux="on"
> paravirtprovider="default"
> effparavirtprovider="kvm"
> VMState="poweroff"
> VMStateChangeTime="2020-04-30T13:19:01.236000000"
> graphicscontroller="vboxvga"
> monitorcount=1
> accelerate3d="off"
> accelerate2dvideo="off"
> teleporterenabled="off"
> teleporterport=0
> teleporteraddress=""
> teleporterpassword=""
> tracing-enabled="off"
> tracing-allow-vm-access="off"
> tracing-config=""
> autostart-enabled="off"
> autostart-delay=0
> defaultfrontend=""
> vmprocpriority="default"
> storagecontrollername0="SATA"
> storagecontrollertype0="IntelAhci"
> storagecontrollerinstance0="0"
> storagecontrollermaxportcount0="30"
> storagecontrollerportcount0="30"
> storagecontrollerbootable0="on"
> "SATA-0-0"="C:\Users\krief\.minikube\machines\minikube\boot2docker.iso"
> "SATA-ImageUUID-0-0"="20a7124c-9fbd-4e9b-8589-515d47f17369"
> "SATA-tempeject"="off"
> "SATA-IsEjected"="off"
> "SATA-1-0"="C:\Users\krief\.minikube\machines\minikube\disk.vmdk"
> "SATA-ImageUUID-1-0"="c3e825a6-5a98-4101-85ef-9554922fcd2d"
...

> "SATA-29-0"="none"
> natnet1="nat"
> macaddress1="0800275B9E2A"
> cableconnected1="on"
> nic1="nat"
> nictype1="virtio"
> nicspeed1="0"
> mtu="0"
> sockSnd="64"
> sockRcv="64"
> tcpWndSnd="64"
> tcpWndRcv="64"
> nic2="none"
> nic3="none"
> nic4="none"
> nic5="none"
> nic6="none"
> nic7="none"
> nic8="none"
> hidpointing="ps2mouse"
> hidkeyboard="ps2kbd"
> uart1="off"
> uart2="off"
> uart3="off"
> uart4="off"
> lpt1="off"
> lpt2="off"
> audio="dsound"
> audio_out="off"
> audio_in="off"
> clipboard="disabled"
> draganddrop="disabled"
> vrde="off"
> usb="off"
> ehci="off"
> xhci="off"
> SharedFolderNameMachineMapping1="c/Users"
> SharedFolderPathMachineMapping1="\\\\?\\c:\\Users"
> videocap="off"
> videocapaudio="off"
> capturescreens=""
> capturefilename="C:\\Users\\krief\\.minikube\\machines\\minikube\\minikube\\minikube.webm"
> captureres="1024x768"
> capturevideorate=512
> capturevideofps=25
> captureopts=""
> GuestMemoryBalloon=0
> }
> I0430 16:19:04.715051    7716 main.go:110] libmachine: STDERR:
> {
> }
> I0430 16:19:04.721036    7716 main.go:110] libmachine: Check network to re-create if needed...
> I0430 16:19:04.723108    7716 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe list hostonlyifs
> I0430 16:19:04.773053    7716 main.go:110] libmachine: STDOUT:
> {
> }
> I0430 16:19:04.773053    7716 main.go:110] libmachine: STDERR:
> {
> }
> I0430 16:19:04.813909    7716 main.go:110] libmachine: Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
> I0430 16:19:04.813909    7716 main.go:110] libmachine: Not found
> I0430 16:19:04.815900    7716 main.go:110] libmachine: Windows might ask for the permission to create a network adapter. Sometimes, such confirmation window is minimized in the taskbar.
> I0430 16:19:04.822882    7716 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe hostonlyif create
> I0430 16:20:51.385947    7716 start.go:110] createHost completed in 2m0.0169275s
> I0430 16:20:51.385947    7716 start.go:77] releasing machines lock for "minikube", held for 2m0.0179249s
> ! StartHost failed, but will try again: creating host: create host timed out in 120.000000 seconds
...

**Full output of `minikube start` command used, if not already included:**

> * minikube v1.9.2 on Microsoft Windows 10 Home 10.0.18363 Build 18363
> * Using the virtualbox driver based on user configuration
> * Starting control plane node m01 in cluster minikube
> * Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
> ! StartHost failed, but will try again: creating host: create host timed out in 120.000000 seconds
> * Deleting "minikube" in virtualbox ...
> * Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
> *
> * [CREATE_TIMEOUT] Failed to start virtualbox VM. "minikube start" may fix it. creating host: create host timed out in 120.000000 seconds
> * Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
> * Related issue: https://github.com/kubernetes/minikube/issues/7072

Thank you !

**Comment by tstromberg** [comment]
Here is the important message:

```
I0430 16:21:10.987443 7716 main.go:110] libmachine: Searching for hostonly interface for IPv4: 192.168.99.1 and Mask: ffffff00
I0430 16:21:10.987443 7716 main.go:110] libmachine: Not found
I0430 16:21:10.988441 7716 main.go:110] libmachine: Windows might ask for the permission to create a network adapter. Sometimes, such confirmation window is minimized in the taskbar.
```

Did you see a permissions dialog hiding in the task bar?
Also, do you have a VPN running by any chance?

Thank you for the information.

**Comment by kriefsacha** [comment]
@tstromberg i don't have a VPN and it asked me permission twice which i agreed. And none left on task bar

**Comment by tstromberg** [comment]
@kriefsacha - Thanks! As best as I can tell, minikube has asked VirtualBox for a virtual network interface, but one did not appear at the expected address.

Could you please share the output of

* `VBoxManage list hostonlyifs`
* `vboxmanage hostonlyif create`
* `vboxmanage hostonlyif remove <vboxnet1 or whatever interface name was created in previous step>`

On my machine, it looks like:

```
$ VBoxManage list hostonlyifs   
Name:            vboxnet0
GUID:            786f6276-656e-4074-8000-0a0027000000
DHCP:            Disabled
IPAddress:       192.168.99.1
NetworkMask:     255.255.255.0
IPV6Address:     
IPV6NetworkMaskPrefixLength: 0
HardwareAddress: 0a:00:27:00:00:00
MediumType:      Ethernet
Wireless:        No
Status:          Down
VBoxNetworkName: HostInterfaceNetworking-vboxnet0
```

```
$ vboxmanage hostonlyif create                                                                                                                                                                             
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interface 'vboxnet1' was successfully created
```

```
$ vboxmanage hostonlyif remove vboxnet1                                                                                                                                                                             Fri May  1 08:47:20 2020
0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
```

After I run minikube start, the hostonlyif status turns to:

```
Status:          Up
```

**Comment by tstromberg** [comment]
I can confirm that if one uses `vboxmanage hostonlyif remove` on all of the interfaces, that minikube sets them up again. You may want to try this to see if it helps to get passed your issue.

**Comment by kriefsacha** [comment]
@tstromberg gonna try that on sunday and i'll tell you. Thank you very much for your help !

**Comment by tstromberg** [comment]
Thanks! I look forward to getting to the bottom of this one.

**Comment by kriefsacha** [comment]
@tstromberg when i did : `Vboxmanage list hostonlyifs ` , the ouput was empty , i got nothing.

After that i did `vboxmanage hostonlyif create` , it asked me for permission which i agreed , but after waiting for hours, it still at 

> 0%...

Do virtual box needs to be up when i do this ?

**Comment by medyagh** [comment]
@kriefsacha I am not sure how to help with this, but have u tried to run in the administrative shell ?

@kriefsacha alternatively have u tried out newest driver docker ? if u have docker installed you can user minikube with docker driver.

minikube delete
minikube start --driver=docker

does that help?

**Comment by medyagh** [comment]
@kriefsacha haven't heard from you, I hope you had a chance to try our docker driver and solved this issue
