### ISSUE TITLE
how/where to check minikube driver info 

### ISSUE THREAD

**Issue by nitishvu** [kubernetes/minikube#7949]
**Steps to reproduce the issue:** 

1.  minikube start  --kubernetes-version=v1.14.1 --driver=docker 
2.  minikube config get driver

**Full output of failed command:** 

Error: specified key could not be found in config

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
OS: ubuntu 20.04 LTS

</details>

**Comment by afbjorklund** [comment]
Currently it is hiding under `minikube profile list`

You can view all of your local config , as well. `minikube config view`
But it is normally quite empty, unless you have used `set` before...

What kind of info where you looking for, beyond "docker" ?

You can view the raw configuration of the profile and the machine.
One of those files might have information that you are looking for.

`~/.minikube/profiles/minikube/config.json`
`~/.minikube/machines/minikube/config.json`

**Comment by nitishvu** [comment]
Hi @afbjorklund  thanks for the response.

In my application, I am trying to check if a user started Minkube with driver=docker
I need to connect my application with   docker network(bridge)

**Comment by nitishvu** [comment]
@afbjorklund 
I can see driver details in both files thanks for the info.
