### ISSUE TITLE
minikube start: Improve logs around docker version

### ISSUE THREAD

**Issue by walls00000** [kubernetes/minikube#7952]
**Steps to reproduce the issue:** 

0. Install minikube on an Ubuntu 18.04 linux system with the following command: 
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64; sudo install minikube /usr/local/bin 

1.Install docker version 19.0.3.2 and run minikube start.  Minikube will install and use Docker 19.03.2 using the following commands: 
apt-get install -y docker-ce docker-ce-cli
(current default version is 19.03.2)
2. minikube stop; minikube delete

3. Downgrade docker to 18.09.6 with the following procedure:
sudo apt-get autoremove -y docker-ce
sudo apt-get purge docker-ce -y
sudo rm -rf /etc/docker
sudo systemctl daemon-reload
sudo apt-get remove docker-ce-cli
--- reboot---
sudo apt-cache policy docker-ce | grep 18.09.6
sudo apt-get install -y docker-ce=5:18.09.6~3-0~ubuntu-bionic
sudo apt-get install -y docker-ce-cli=5:18.09.6~3-0~ubuntu-bionic

sudo systemctl daemon-reload
sudo systemctl enable docker
sudo systemctl start docker
sudo systemctl status docker
** docker should be running at 18.09.6 at this point **
eg: 
$ docker version
Client:
 Version:           18.09.6
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        481bc77
 Built:             Sat May  4 02:35:57 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.6
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       481bc77
  Built:            Sat May  4 01:59:36 2019
  OS/Arch:          linux/amd64
  Experimental:     false

4. Nuke and reinstall minikube using this procedure
rm -rf ~/.kube ~/.minikube
docker system prune -af --volumes
sudo rm -f /usr/local/bin/minikube

5. Reinstall minikube with the following command:
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64; sudo install minikube /usr/local/bin

6. Start minikube.  Notice the Preparing Kubernetes line states it is using the old 19.03.2 docker version

**Full output of failed command:** 

`$ minikube start`
`* minikube v1.9.2 on Ubuntu 18.04`
`- KUBECONFIG=/home/wwallace/.kube/config`
`* Using the docker driver based on user configuration`
`* Starting control plane node m01 in cluster minikube`
`* Pulling base image ...`
`* Creating Kubernetes in docker container with (CPUs=2) (4 available), Memory=4000MB (16019MB available) ...`
`* Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...`

**Comment by tstromberg** [comment]
I think we can do a better job of message delivery here, but this is because minikube has it's own built-in version of Docker that is used within the VM or container.

**Comment by afbjorklund** [comment]
Yeah, we don't show the version of the Docker running the node - only the Docker running the pods:

* `Using the docker driver based on user configuration`
1) Docker 18.09.6 running on host (now downgraded)
* `Creating Kubernetes in docker container with (CPUs=2) (4 available), Memory=4000MB (16019MB available) ...`
2) Docker 19.03.2 running on node (docker-in-docker)
* `Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...`

We don't show the version of e.g. VirtualBox either, but we _should_ show some more driver info ?

**Comment by afbjorklund** [comment]
We _could_ show some more info, but the interface might also get cluttered.

So now it is only found in the minikube log:

😄  minikube v1.10.0-beta.2 on Ubuntu 16.04
_docker version: 19.03.8_
✨  Using the docker driver based on user configuration
_Found gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 in local docker daemon, skipping pull_
_Found local preload: /home/anders/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.1-docker-overlay2-amd64.tar.lz4_
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
_Remote host: Ubuntu 19.10_
_Run: docker version --format {{.Server.Version}}_
🐳  Preparing Kubernetes v1.18.1 on Docker 19.03.2 ...

So currently we "hide" the local version and the remote OS from the user.

That can easily get confusing, I suppose.

----

In your case, it was:

1) Ubuntu 18.04 (shown)
    Docker 18.09.6 (hidden)
2) Ubuntu 19.10 (hidden)
    Docker 19.03.2 (shown)

**Comment by afbjorklund** [comment]
@walls00000 : note that if you **want** to change the minikube docker, you need to use `minikube ssh`

```console
$ minikube start --driver=docker
$ minikube ssh
docker@minikube:~$ sudo apt-get update
Get:1 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10  InRelease [1625 B]
Get:2 http://archive.ubuntu.com/ubuntu eoan InRelease [255 kB]                
Get:3 http://security.ubuntu.com/ubuntu eoan-security InRelease [97.5 kB]
Get:4 http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_19.10  Packages [9004 B]
Get:5 http://security.ubuntu.com/ubuntu eoan-security/universe amd64 Packages [204 kB]               
Get:6 http://archive.ubuntu.com/ubuntu eoan-updates InRelease [97.5 kB]
Get:7 http://archive.ubuntu.com/ubuntu eoan-backports InRelease [88.8 kB]
Get:8 http://archive.ubuntu.com/ubuntu eoan/multiverse amd64 Packages [188 kB]
Get:9 http://security.ubuntu.com/ubuntu eoan-security/multiverse amd64 Packages [1079 B]
Get:10 http://security.ubuntu.com/ubuntu eoan-security/main amd64 Packages [253 kB]
Get:11 http://archive.ubuntu.com/ubuntu eoan/main amd64 Packages [1277 kB]              
Get:12 http://security.ubuntu.com/ubuntu eoan-security/restricted amd64 Packages [23.7 kB]
Get:13 http://archive.ubuntu.com/ubuntu eoan/restricted amd64 Packages [22.7 kB]             
Get:14 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages [11.6 MB]
Get:15 http://archive.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages [260 kB]                                                                                   
Get:16 http://archive.ubuntu.com/ubuntu eoan-updates/restricted amd64 Packages [31.7 kB]                                                                                
Get:17 http://archive.ubuntu.com/ubuntu eoan-updates/main amd64 Packages [352 kB]                                                                                       
Get:18 http://archive.ubuntu.com/ubuntu eoan-updates/multiverse amd64 Packages [8374 B]                                                                                 
Get:19 http://archive.ubuntu.com/ubuntu eoan-backports/universe amd64 Packages [3077 B]                                                                                 
Get:20 http://archive.ubuntu.com/ubuntu eoan-backports/main amd64 Packages [669 B]                                                                                      
Fetched 14.8 MB in 12s (1241 kB/s)                                                                                                                                      
Reading package lists... Done
docker@minikube:~$ sudo apt-cache policy docker.io
docker.io:
  Installed: 19.03.2-0ubuntu1
  Candidate: 19.03.6-0ubuntu1~19.10.1
  Version table:
     19.03.6-0ubuntu1~19.10.1 500
        500 http://archive.ubuntu.com/ubuntu eoan-updates/universe amd64 Packages
 *** 19.03.2-0ubuntu1 500
        500 http://archive.ubuntu.com/ubuntu eoan/universe amd64 Packages
        100 /var/lib/dpkg/status
```

We don't yet have any support for choosing different versions of the container runtimes: #6432

**Comment by walls00000** [comment]
afbjorklund Thanks for the clarification.  If I understand correctly, the remote embedded docker version is printed, which for whatever reason is out of sync with my downgraded version.  To remedy this, I need to use minikube ssh to downgrade the docker version on the container.  

A nice compromise would be to distinguish local and remote in the print statement:
$ minikube start
* minikube v1.9.2 on ** local host OS** Ubuntu 18.04
- KUBECONFIG=/home/wwallace/.kube/config
* Using the docker driver based on user configuration
* Starting control plane node m01 in cluster minikube
* Pulling base image ...
* Creating Kubernetes in docker container with (CPUs=2) (4 available), Memory=4000MB (16019MB available) ...
* Preparing Kubernetes v1.18.0 **with remote Docker version** 19.03.2 ...

**Comment by afbjorklund** [comment]
The use of the terms "local" and "remote" here are confusing a lot of users, unfortunately.
(especially since the "remote" machine is running locally on the same host, but not "local")

Minikube was (just like Docker is) trying to pretend that there is only one system involved...
It is not supposed to matter, what virtualization/containerization is used for hosting the node.

I'm not sure that you **have** do anything, unless you actually _wanted_ to change Docker ?

It should be perfectly OK to run one docker on the host and another docker in the kicbase.

**Comment by afbjorklund** [comment]
The reason why kicbase uses an obsolete version is that it is pinned: `docker.io=19.03.2-0ubuntu1`

It should probably **avoid** doing that, and get the latest available ? Now: `19.03.6-0ubuntu1~19.10.1`

https://packages.ubuntu.com/eoan-updates/docker.io

Alternative we _could_ get the binary deb, from docker: #6627

https://download.docker.com/linux/ubuntu/dists/eoan/pool/stable/amd64/ `19.03.8~3-0~ubuntu-eoan`

But there is something nice about having the distro-supported version, and building it from source ?

**Comment by walls00000** [comment]
Agreed, the terms 'local' and 'remote' can be confusing as those terms are indeed overloaded, but distinguishing them is also important. Perhaps using the term 'kicbase' can be used?  In this case, my intent was to change docker, and I was not seeing what I expected to see.  I know now why this is the case.  Any changes to the print statements to clarify this would be helpful.  Thanks

**Comment by tstromberg** [comment]
I wonder if we could get something like this, but less wordy:

`Preparing Kubernetes v1.18.0 with Docker 19.03.2 as the container runtime ..`

**Comment by medyagh** [comment]
> I wonder if we could get something like this, but less wordy:
> 
> `Preparing Kubernetes v1.18.0 with Docker 19.03.2 as the container runtime ..`

that is a bit too long, how about we just remove "as the"
`Preparing Kubernetes v1.18.0 with Docker 19.03.2 container runtime ..`

**Comment by Harkishen-Singh** [comment]
@medyagh does this issue just want a simple message output change?

**Comment by medyagh** [comment]
I dont think we want to do this anymore
