### ISSUE TITLE
none: HTTPS_PROXY is not passed through sudo call to minikube

### ISSUE THREAD

**Issue by GFLEMING133** [kubernetes/minikube#7964]
Hi there (and thanks in advance to anyone who's able to help with this issue).

I am new to kubernetes (although not docker).
I am trying to run minikube on Ubuntu 20.04LTS using the baremetal driver. I can explain why I'm running baremetal if anyone thinks its relevant. For now, suffice to say I'm trying to use it.

## Issue
When I run `sudo minikube start --driver=none`, I receive the following error:
```
🙄  minikube v1.9.2 on Ubuntu 20.04 (vbox/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node  in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 20.04 LTS
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.6 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
❗  This bare metal machine is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

❌  [DOWNLOAD_IO_TIMEOUT] Failed to update cluster updating node: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl.sha256: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl.sha256: dial tcp 172.217.6.112:443: i/o timeout
💡  Suggestion: A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
⁉️   Related issue: https://github.com/kubernetes/minikube/issues/3846
```
I read through `https://minikube.sigs.k8s.io/docs/reference/networking/proxy/`, but I didn't find any new information.
I've also tried with 
```
sudo minikube start \
--docker-env HTTP_PROXY=http://....someproxy...:9090/ \
--docker-env HTTPS_PROXY=http://....someproxy...:9090/ \
--docker-env NO_PROXY=index.docker.io --driver=none
```
This gives the following output:
```
🙄  minikube v1.9.2 on Ubuntu 20.04 (vbox/amd64)
✨  Using the none driver based on existing profile
👍  Starting control plane node  in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 20.04 LTS
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.6 ...
    ▪ env HTTP_PROXY=http://....someproxy...:9090/
    ▪ env HTTPS_PROXY=http://....someproxy...:9090/
    ▪ env NO_PROXY=index.docker.io
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
❗  This bare metal machine is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

❌  [DOWNLOAD_IO_TIMEOUT] Failed to update cluster updating node: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl.sha256: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubectl.sha256: dial tcp 172.217.6.112:443: i/o timeout
💡  Suggestion: A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
⁉️   Related issue: https://github.com/kubernetes/minikube/issues/3846
```

## ....in more detail...

I'm behind a http_proxy (corporate). I have configured the box to use proxy variables through the GUI version of settings. You can see these variables reflected in an `export`:

```
user@user-Machine:~$ export | grep http
declare -x HTTPS_PROXY="http://....someproxy....com:9090/"
declare -x HTTP_PROXY="http://....someproxy.....com:9090/"
declare -x http_proxy="http://....someproxy.....com:9090/"
declare -x https_proxy="http://....someproxy.....com:9090/"
```
I can access the internet just fine, and can perform an http request using CURL without issue. Variables are part of my profile, and they persist after machine reboot/bash logout/etc.

## Minikube version:
```
minikube version: v1.9.2
commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393
```
## Kubectl:
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```
## Docker version:
```
Client: Docker Engine - Community
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.16
 Git commit:        369ce74a3c
 Built:             Thu Feb 13 01:27:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false
```
```
Server: Docker Engine - Community
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.16
  Git commit:       369ce74a3c
  Built:            Thu Feb 13 01:26:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

Let me know if anyone has any suggestions. I have the feeling I'm missing something simple, but I wanted to post an issue on the off-chance there actually is a problem with how minikube sets up a proxy when using the baremetal driver.

**Comment by tstromberg** [comment]
Thanks for the feedback! I believe the reason here is that `sudo` does not pass proxy information by default. When proxies are defined, they should show up in the minikube output. 

Two things to try:

* `sudo -E minikube start ....`
* `sudo env HTTPS_PROXY=x minikube start...`

Please let me know what you end up with.

**Comment by GFLEMING133** [comment]
Even if sudo doesn't pass environment variables through, shouldn't passing the proxy variables as arguments have worked?
```
sudo minikube start \
--docker-env HTTP_PROXY=http://....someproxy...:9090/ \
--docker-env HTTPS_PROXY=http://....someproxy...:9090/ \
--docker-env NO_PROXY=index.docker.io --driver=none
```
(see output for this in my original post)

**Comment by GFLEMING133** [comment]
Update:
Using `sudo -E minikube start --driver=none` worked! 

I wonder if we should update the docs proxy [page](https://minikube.sigs.k8s.io/docs/reference/networking/proxy/) to include a section about this? I imagine I'm not the only user to use a proxy with the baremetal driver for minikube...

If updating the docs is something you'd be in support of, I can put in a PR for it & request you as a reviewer.

**Comment by sharifelgamal** [comment]
Yeah, we would love to for you to update our docs with a bit about proxies on baremetal. Feel free to open a PR.

**Comment by GFLEMING133** [comment]
I have the docs change (minor, obviously just a few sentences) added, but I'm not able to push my branch up so people can review it (e.g., `ERROR: Permission to kubernetes/minikube.git denied to GFLEMING133.
fatal: Could not read from remote repository. Please make sure you have the correct access rights`)

I reviewed [the minikube contribution guide](https://minikube.sigs.k8s.io/docs/contrib/guide/) for how to contribute to minikube, but I didn't see any specific instructions on getting push permissions. What am I missing here...?

P.S. Yes, this isn't related to the original isue, so after a reply gets posted to this post, I can delete this one :)

**Comment by sharifelgamal** [comment]
Make sure to fork this repository, first so you'll have your own copy of minikube, presumably at GFLEMMING133/minikube.git. Then you'll be able to push your changes to your fork and be able to open a PR.

**Comment by medyagh** [comment]
this could be a good first issue, to update the docs to use `sudo -E`
and also in our usage commands that we put in the minikube solution messages we should change it to "sudo -E" only for none
