### ISSUE TITLE
Enabling ABAC not working properly

### ISSUE THREAD

**Issue by pfremm** [kubernetes/minikube#797]
I've tried minikube 0.12.1, and 0.12.2 to try and enable ABAC.  Looking at the guides when I create my instance of minikube with the following command:

minikube start --vm-driver=xhyve --cpus=2 --memory=4096 --insecure-registry=regt.nmlv.nml.com:5000 --extra-config=apiserver.AuthorizationMode=ABAC --extra-config=apiserver.AuthorizationPolicyFile=/Users/PFR5290/Development/ServiceAccountsAuth/policy.json

My Authorization policy.json file has the contents I found in the example listed on this repo available at: https://raw.githubusercontent.com/kubernetes/minikube/05edfeaf65563776501834942ddb41d96d094e78/vendor/k8s.io/kubernetes/pkg/auth/authorizer/abac/example_policy_file.jsonl#

The cluster creates, but when I try and create my own policy after the cluster is create I get an error that bac.authorization.kubernetes.io/v1 is not exposed via the api.  Using minikube ssh I can see this ABAC is not enabled.  Has anyone succesfully got ABAC working with minikube or can see what I am doing wrong?

**Comment by pfremm** [comment]
I've done some more reading and I didn't realize these policies had to be set when the api server is started.  I'm closing this for now, and will try and submit a PR to improve the documentation around ABAC.

**Comment by dlorenc** [comment]
Thanks! Let us know if you get this working :)

**Comment by stverhae** [comment]
If you get this working, do let us know indeed.
I'm currently trying to get this to work, but it seems even with a policyfile which gives full wildcard permissions to everyone I can't get "minikube dashboard" to work (connection refused).

`{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "*", "namespace": "*", "nonResourcePath": "*"}}
{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user": "*", "namespace": "*", "resource": "*", "apiGroup": "*"}}`

call to start:
`minikube start --extra-config=apiserver.AuthorizationMode=ABAC --extra-config=apiserver.AuthorizationPolicyFile=/path/file.json`

**Comment by pfremm** [comment]
I did not try it with the dashboard, but I'll give it a shot.  I will try and submit a PR for some documentation and sample policies.

**Comment by stverhae** [comment]
@pfremm I did get it to work with dashboard. I linked the relevant bits of my policyfile below. Possibly these could be a lot more strict and still allow dashboard to do its thing,but I haven't had time to look into this deeper.

An update in the documentation is still really welcome for other people trying to figure this out.

`{"apiVersion": "abac.authorization.kubernetes.io/v1beta1", "kind": "Policy", "spec": {"user":"*", "nonResourcePath": "*", "readonly": true}}
{"apiVersion":"abac.authorization.kubernetes.io/v1beta1","kind":"Policy","spec":{"user":"system:serviceaccount:kube-system:default","namespace":"*","resource":"*","apiGroup":"*"}}
{"apiVersion":"abac.authorization.kubernetes.io/v1beta1","kind":"Policy","spec":{"user":"minikube","namespace":"*","resource":"*","apiGroup":"*"}}`

**Comment by inge4pres** [comment]
*UPDATE *
From 1.5.1 the extra config should be added `GenericOptions` so to start a minikube with ABAC enabled properly
```
minikube start --kubernetes-version v1.5.3  --extra-config=apiserver.GenericServerRunOptions.AuthorizationMode=ABAC --extra-config=apiserver.GenericServerRunOptions.AuthorizationPolicyFile=/path/to/policy.json
```

**Comment by pfremm** [comment]
I think at this point moving to rbac instead of abac makes a ton of sense since you don’t have to statically define permissions when api server starts
