### ISSUE TITLE
site: add to FAQ page how to ignore system verification.

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7974]
the answer is here
https://github.com/kubernetes/minikube/issues/3320#issuecomment-494511281

**Comment by afbjorklund** [comment]
We should probably document "known issues", before telling people how to disable verification ?
There are a lot of known errors, especially for the `none` driver and the verification actually helps.

Better if we could improve the "scary output" #7368 and add better documentation for e.g. `conntrack`
And I'm not sure if our **first** option should be to support unrecommended runtimes and drivers ?
