### ISSUE TITLE
Minikube doesn't change initial RAM or vCPU allocation

### ISSUE THREAD

**Issue by vugardzhamalov** [kubernetes/minikube#7976]
I am not sure if this is by design - I thought I'll report this observation anyway. It seems like once your named minikube profile has been started with specific RAM and vCPU values explicitly declared - any new values provided during consecutive 'minikube startr' execution(s) will be ignored. In other words underlying KVM virtual machine will stay with RAM and vCPU allocation unchanged. I am not sure if this is how it was intended - but I think it will be nice if we could change these values on the same profile during consecutive 'minikube start' invocations.

Host OS: Fedora 31, kernel: 5.6.7-200.fc31.x86_64
Minikube Version: minikube version: v1.9.2; commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393
qemu-kvm Version: 4.1.1
libvirt Version: 5.6.0

**Steps to reproduce the issue:** 

1. minikube start --container-runtime=crio --profile <my-profile-name> --memory='8192mb' --cpus='4' --disk-size 30g --vm-driver kvm2 --network-plugin=cni --enable-default-cni --kubernetes-version=v1.18.2 --cri-socket='/var/run/crio/crio.sock' --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
2. minikube stop --profile <my-profile-name>
3. minikube start --container-runtime=crio --profile <my-profile-name> --memory='16384mb' --cpus='6' --disk-size 30g --vm-driver kvm2 --network-plugin=cni --enable-default-cni --kubernetes-version=v1.18.2 --cri-socket='/var/run/crio/crio.sock' --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
😄  [minikube-18-knative] minikube v1.9.2 on Fedora 31
✨  Using the kvm2 driver based on existing profile
👍  Starting control plane node m01 in cluster minikube-18-knative
🔄  Restarting existing kvm2 VM for "minikube-18-knative" ...
🎁  Preparing Kubernetes v1.18.2 on CRI-O 1.17.1 ...
    ▪ apiserver.enable-admission-plugins=LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook
🌟  Enabling addons: default-storageclass, istio, istio-provisioner, metrics-server, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube-18-knative"

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
It's a missing feature, you will have to either delete it - or change it yourself using libvirt methods

**Comment by vugardzhamalov** [comment]
Thank you @afbjorklund ! What would you like me to do this with the ticket? Should I close it now?

**Comment by afbjorklund** [comment]
> Thank you @afbjorklund ! What would you like me to do this with the ticket? Should I close it now?

It depends on if you think it needs some more. Maybe it could issue a warning if changing values ?
Or if it should be documented better that the values only apply when actually creating the machine.

Some users get confused that `start` sometimes does the create and sometimes just does the start.
Changing values for existing machine is harder, and requires some driver-specific implementation.

**Comment by vugardzhamalov** [comment]
Thank you @afbjorklund !

I think that my confusion comes from the fact that some of the values once declared during consecutive! 'minikube start' invocation can not be changed - even when declared explicitly. At the same time some of the values fall back to default if they are not explicitly declared...

For example if I don't explicitly declare '--container-runtime=crio' on every consecutive 'minikube start' invocation the value will fall back to 'docker' - and this will happen without warning. I understand that I could probably declare default values somewhere in advance... but I would rather have it -  say a bit more consistent with initial 'minikube start' invocation instead.

Also apart from the issue with CPU and RAM values I've noted earlier, there is one more thing - it seems like we declare RAM in Megabytes (MB) and this value gets translated to Mebibytes (MiB) on KVM side (I am not sure if it was documented anywhere)... this is probably not a big issue but it is there and it means that underlying VM will end up with less of RAM allocated to it.

So coming back to your question - I would rather keep it opened if you think that documentation is a good starting point for a change - on the other hand if you (or maybe someone else...) think that this is rather superficial and there are more important things to work on - let's close it! At the end of the day none of this is a show stopper.

**Comment by afbjorklund** [comment]
There was this idea to split "start" up into only create (vs. delete) and then start (vs. stop).
But it's a rather breaking changing, so currently we still have the all-in-one command to do it.

For historical reasons, we normally give memory in MiB (2200) and disk size in MB (20000).
Then I think it got lost in translation again, when converting to libvirt and KVM configuration...

But the general idea here was 2.1 GiB memory (spelled as "2 GB") and 19.5 GiB disk image size.

The main idea behind improving documentation is to avoid other people having the _same_ issue...

**Comment by vugardzhamalov** [comment]
Dear @afbjorklund maybe I don't know something (or maybe I am totally missing the point)... but personally I don't mind using 'minikube start' for multiple purposes...  In fact I think it is better then splitting it into multiple 'start' vs 'create' vs something else in the future.

What I don't understand - how come all of the initially provided values cannot be properly recorded within named profile 'config.json' file? Please correct me if I am wrong but as far as I know by default named profile config.json file will be created at:

`~/.minikube/machines/<named-profile-name>/config.json`

My assumption will be that once you have all of the values declared explicitly they will end up recorded in the corresponding named profile config.json file so that next time you invoke 'minikube start' against the same named profile there will be no need to worry about values (and guessing which one should be explicitly repeated again and which one shouldn't ).

**Comment by sharifelgamal** [comment]
This is actually fixed at HEAD and should go out with the next release. We respect the initial values of everything on subsequent restarts.

**Comment by medyagh** [comment]
@vugardzhamalov changing CPU and Ram is not allowed after your create the cluster, but you can delete it and recreate it.
