### ISSUE TITLE
The minikube version in Snap Store is out-of-date

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#7977]
https://snapcraft.io/minikube

> minikube
> 
> Casey Marshall (cmars) Server and Cloud 
> 
> Channel | Version | Published |  
> -- | -- | -- | --
> latest/stable | 0.8.0 | 29 September 2016 |  
> latest/edge | 0.24.1 | 24 January 2018 |
> 
> Run Kubernetes locally
>
> Minikube is a tool that makes it easy to run Kubernetes locally. Minikube runs a single-node
> Kubernetes cluster inside a VM on your laptop for users looking to try out Kubernetes or develop
> with it day-to-day.
>
> Details for minikube
> 
> License
>     Proprietary
> Last updated
>     29 September 2016 
> 

----

Starting with Ubuntu 20.04, it is no longer possible to install .deb files using Ubuntu Software:

![ubuntu-software-install-failed](https://user-images.githubusercontent.com/10364051/80863905-99f61d00-8c7f-11ea-8720-7d75150b0c15.png)

And by default, it will recommend the user to install the package from the Ubuntu Snap Store:
```
Command 'minikube' not found, but can be installed with:

sudo snap install minikube

```

So this is probably how many Ubuntu users would prefer to install their version of minikube:

```console
$ sudo snap install minikube
minikube 0.8.0 from Casey Marshall (cmars) installed
$ minikube version
minikube version: v0.8.0
```

It does show a link to the updated version, but as per above it is not possible to install the .deb.

It is still possible to install using the command-line, but maybe we can update the official version ?

https://minikube.sigs.k8s.io/docs/start/

> Binary download
> 
>  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
>  sudo install minikube-linux-amd64 /usr/local/bin/minikube
> 
> Debian package
> 
> curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_1.9.2-0_amd64.deb
> sudo dpkg -i minikube_1.9.2-0_amd64.deb
>

**Comment by afbjorklund** [comment]
https://snapcraft.io/docs/store-brand-accounts

> For larger projects and ISVs it is often a requirement to publish snaps using a brand account.

**Comment by medyagh** [comment]
> https://snapcraft.io/docs/store-brand-accounts
> 
> > For larger projects and ISVs it is often a requirement to publish snaps using a brand account.

oh thanks for finding that, would u be interested to register minikube's brand in snap store? I fully support this effort.

**Comment by afbjorklund** [comment]
>  would u be interested to register minikube's brand in snap store

I would prefer if somebody else did, are you up for it @tstromberg ?

* I have not been in contact with Casey Marshall yet, about the name.

* I have no idea how you make a snap or a flak or whatever the kids use...
    - https://snapcraft.io/ "The app store for Linux"
    - https://flathub.org/ "Apps for Linux, right here"

* I would prefer **not** having to do a 4th (and a 5th and a 6th) package - but.
    - tgz
    - deb
    - rpm

* I am not sure how this interacts with the [snap docker](https://snapcraft.io/docker), as I am using [apt](https://docs.docker.com/engine/install/ubuntu/)

**Comment by dholbach** [comment]
I can help reach out to the Snap Store team if you want to take over the snap. If you have some evidence of having reached out to Casey that'd certainly help. That'd also give you access to marking the snap as private for now so people don't mistakenly install the outdated version.

**Comment by dholbach** [comment]
Looks like this is what the snap was based off? https://github.com/cmars/minikube-pkg

**Comment by afbjorklund** [comment]
Thanks for looking into the snap packaging. As stated above, I just noted it was outdated in the distribution (Ubuntu 20.04).

Unfortunately `minikube` is not available in Debian, which also means that it is not available as an apt package in Ubuntu...

We have tried to get it included with the other "vendor" Kubernetes packages, but those attempts have failed so far: #3110

So the only offer right now is a unsigned repackaged binary deb, which unfortunately doesn't open (double-click) any longer...

----

Here is an up-to-date package, that works better:
https://apps.0install.net/kubernetes/minikube.xml

![0install-minikube](https://user-images.githubusercontent.com/10364051/91631587-fc1b2080-e9da-11ea-9eb9-8faa13bc0e74.png)

It would be nice to get apt/snap back on track too ?
But I understand that it prefers to push microk8s...

> This project is no longer being maintained and is now read-only (archived).
> Use [microk8s](https://snapcraft.io/microk8s) for a much lighter, faster development kubernetes in-a-snap.

**Comment by dholbach** [comment]
Even if Casey now works on microk8s, it would surprise me if willing new maintainers couldn't take over the snap in the store now. As I said: I'd be happy to help coordinate with the snap store people, if somebody wants to start maintaining the snap in the future.

**Comment by afbjorklund** [comment]
> Even if Casey now works on microk8s, it would surprise me if willing new maintainers couldn't take over the snap in the store now. As I said: I'd be happy to help coordinate with the snap store people, if somebody wants to start maintaining the snap in the future.

It wasn't obvious from the store page, how to request a version upgrade or removal of unmaintained apps.

And there was no contact info for the "publisher" either, and the license information just said "Proprietary"

But it wasn't really a "terms of service" or "copyright" violation either, so just opened this issue about it...

https://snapcraft.io/minikube

![minikube-report](https://user-images.githubusercontent.com/10364051/91634744-01846500-e9f3-11ea-9583-1c8fda473873.png)

----

If there is nobody willing to maintain it, it is probably better to remove it and refer users to the upstream ?

From the sources that you posted, it seems there is some more work to be done before it works in snapd:

> Note that for strict confinement, this snap depends on a libvirt interface, which is currently proposed into snapd, but has not released yet. Until it has, I'm afraid this isn't quite ready for general consumption.

> The snap currently only supports minikube with the KVM driver, which will be used by default when starting a new VM. Other drivers may be added later.

Other users have reported problem with docker from snap, so it would require some integration work...

Might as well use https://kubernetes.io/docs/tasks/tools/install-minikube/ until it has been completed ?

**Comment by dholbach** [comment]
Is there a mail alias for the minikube maintainers? I'd be happy to reach out to the Snap Store and ask if snap maintenance could be transferred. Until anyone contributes an updated `snapcraft.yaml` (likely with `classic` confinement), it might make sense to mark the current as "private" in the store. As an aside: snap builds and snap publishing can be hooked up with CI.

**Comment by dholbach** [comment]
@cmars Would you be OK with somebody else taking over maintenance of the `minikube` snap?

**Comment by cmars** [comment]
Hi @dholbach this sounds good to me! Please make a request to transfer ownership of the snap at https://forum.snapcraft.io/c/store-requests. If there's any question, ping me with the link and I'll indicate my approval there.

This comment is outdated, I landed the libvirt interface in snapd a ways back:

> Note that for strict confinement, this snap depends on a libvirt interface, which is currently proposed into snapd, but has not released yet. Until it has, I'm afraid this isn't quite ready for general consumption.

However, there might be other reasons you might need classic confinement -- snapd, minikube and the kvm integration may have changed considerably since I last looked at them. If you do need classic, you'll also need to request it from the snapstore.

**Comment by dholbach** [comment]
Got it, thanks @cmars for your support!

Is there a minikube-maintainers@ alias that could be used for transferring the snap entry to?

**Comment by tstromberg** [comment]
@dholbach - There is a minikube-dev@googlegroups.com alias. It isn't very well used, but it at least goes to some of the maintainers.

I can't say I'm excited about maintaining another packaging mechanism, but if someone doesn't mind helping to integrate the build process into our Makefile, it shouldn't be too terrible to maintain.

**Comment by dholbach** [comment]
AFAICS it'd be a `snapcraft.yaml` file and e.g. a Github action to build and publish to the store.

@tstromberg Is the mail alias a public mailing list? If yes, it might make sense to use the email addresses of individual project maintainers.

**Comment by afbjorklund** [comment]
We need a real maintainer for this package, otherwise it will just bit-rot again I'm afraid.

**Comment by dholbach** [comment]
Maybe @cmars could you unlist the snap for now? I think until somebody is willing to put some work into snapping current minikube, this might help not to confuse users.

**Comment by cmars** [comment]
It is now unlisted.
