### ISSUE TITLE
Warn about default Docker Desktop resources

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7980]
on a fresh windows machine with 32 GB ram and 8 CPus I installed docker-desktop with all default settings,

I noticed a painfully slower than normal minikube significantly (I dont know how to time commands in powershell)

then I noticed docker desktop by default only has 2 GB ram, no matter what your system is.

We need to 
1- Detect the docker desktop resources
2- Warn the user to Increase if possible

![Screen Shot 2020-05-02 at 4 28 24 PM](https://user-images.githubusercontent.com/4564227/80894717-51942a80-8c92-11ea-8fab-1bb59ea8f8a8.png)

**Comment by afbjorklund** [comment]
I thought minikube was supposed to be able to run in a 2GB virtual machine ?
But maybe we beefed that up to 2200M now, and it started swapping on you...

Were you able to log in to the machine, and see what is using the most memory ?
It seems rather sad that we can't even install an _empty_ cluster without 2+ GiB.

----

The documentation is a bit vague, if it is the VM that needs 2G or if it is Kubernetes.

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/

But it does seem to say that it is the **machine**, and that it leaves room for apps ?

> 2 GB or more of RAM per machine (any less will leave little room for your apps)

So if the `kubeadm` documentation is not accurate for newer Kubernetes versions,
it should probably be updated upstream. To require 2200M or whatever (8000M?).

`🔥  Creating docker container (CPUs=2, Memory=8000MB) ...`

Do you know if the situation is the same in the Docker-for-Mac VM ?

**Comment by afbjorklund** [comment]
> Do you know if the situation is the same in the Docker-for-Mac VM ?

Never mind, it seems to be identical: https://docs.docker.com/docker-for-mac/#resources

![](https://docs.docker.com/docker-for-mac/images/menu/prefs-advanced.png)

**Comment by afbjorklund** [comment]
## Linux

The 8G default was when using Docker Engine, running on Ubuntu (with same 32 GB RAM)

`Using suggested 8000MB memory alloc based on sys=32047MB, container=32047MB`

There is no VM, so Docker has access to all of it. So the limit comes from minikube here:

```go
        // Suggest 25% of RAM, rounded to nearest 100MB. Hyper-V requires an even number!
        suggested := int(float32(sysLimit)/400.0) * 100
```


`docker info`
```
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.3GiB
```

**Comment by afbjorklund** [comment]
## OpenShift

As a comparison, minishift4 ("[CodeReady Containers](https://developers.redhat.com/products/codeready-containers/overview)") now requires 8 GB of memory:

https://developers.redhat.com/blog/2019/09/05/red-hat-openshift-4-on-your-laptop-introducing-red-hat-codeready-containers/

> CodeReady Containers requires the following minimum system resources to run Red Hat OpenShift:
> 
>     4 virtual CPUs (vCPUs)
>     8 GB of memory
>     35 GB of storage space

## Minikube (VM/BM)

So maybe it is time to increase the minikube requirements to 4 GB of memory now ?

Perhaps also increase the default disk image size too, from 19.53 GiB to 39.06 GiB.

https://minikube.sigs.k8s.io/docs/start/
>What you’ll need
> * **2 CPU (not documented)**
> * 2GB of free memory
> * 20GB of free disk space

Or we could do like the games:

"Minimum" vs. "Recommended"

-----

For minishift3, I think it was rather similar to the minikube requirements.

Which in turn is twice the amount of the docker-machine requirements...

**Comment by afbjorklund** [comment]
Also related to #3574 - minikube should be able to warn you when the VM is runnnig low...

**Comment by medyagh** [comment]
the thing is, minikube runs with 2 GB ram, but super slow ! most users don't notice that docker desktop was installed by default with 2 GB ram

**Comment by afbjorklund** [comment]
> the thing is, minikube runs with 2 GB ram, but super slow ! most users don't notice that docker desktop was installed by default with 2 GB ram

It should run (at least "idle") on the default memory allocation, _without_ swapping ("super slow"). Before, we have only added swap when running on 1 GB ram, and is not really recommended or supported.

Note that kubeadm does **not** support using swap at all, as it leads to issues when orchestrating.
`[ERROR Swap]: running with swap on is not supported. Please disable swap`

But will move the general discussion to a new issue, I think. It's bigger than "just" Docker VM...

I think it would make sense to make it the new "performance" goal (a memory usage analysis) ?
