### ISSUE TITLE
minikube emojis don't show up in Windows powershell

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7981]
![Screen Shot 2020-05-02 at 4 34 09 PM](https://user-images.githubusercontent.com/4564227/80894745-cd8e7280-8c92-11ea-90ce-2ceac7b96490.png)

For someone who is good with Windows this could be a good first issue.
so unless you are good with windows and powershell, please Do not sign up for this task.

**Comment by sharifelgamal** [comment]
This is an issue on Windows side: https://github.com/microsoft/terminal/issues/190

**Comment by tstromberg** [comment]
Fixed at head if new Terminal is used.
