### ISSUE TITLE
what's the meaning of the top command in minikube

### ISSUE THREAD

**Issue by fffffreedom** [kubernetes/minikube#7987]
i specified the memory param to 8192，how can i know the vm's memory usage?  what does "GiB Mem : 28.2/7.8" mean？thks
top - 10:39:10 up 40 min,  1 user,  load average: 0.45, 1.28, 1.85
Tasks: 269 total,   1 running, 268 sleeping,   0 stopped,   0 zombie
%Cpu0  :   3.5/2.8     6[|||||||                                                                                             ]
%Cpu1  :   9.9/3.5    13[||||||||||||||                                                                                      ]
%Cpu2  :   5.7/3.5     9[||||||||||                                                                                          ]
%Cpu3  :   7.6/2.8    10[|||||||||||                                                                                         ]
GiB Mem : 28.2/7.8      [                                                                                                    ]
GiB Swap:  0.0/0.0      [                                                                                                    ]

**Comment by afbjorklund** [comment]
The `top` output is somewhat confusing. The `7.8` is the amount of memory.

You can also use the `free` command:

```
$ free -m 
              total        used        free      shared  buff/cache   available
Mem:           7972         197        5978        1030        1796        6507
Swap:             0           0           0
```

**Comment by fffffreedom** [comment]
thks

**Comment by afbjorklund** [comment]
You can find more info here: http://man7.org/linux/man-pages/man1/top.1.html

```
       In the alternate memory display modes, two abbreviated summary lines
       are shown consisting of these elements:
                      a    b          c
           GiB Mem : 18.7/15.738   [ ...
           GiB Swap:  0.0/7.999    [ ...

       Where: a) is the percentage used; b) is the total available; and c)
       is one of two visual graphs of those representations.
```

As well as from the original project itself: https://gitlab.com/procps-ng/procps
