### ISSUE TITLE
virtualbox on windows: Error VirtualBox Host-Only Ethernet Adapter

### ISSUE THREAD

**Issue by rsendil** [kubernetes/minikube#7993]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 
C:\My Study\Kubernetes>minikube start --alsologtostderr -v=1

W0504 19:12:37.353888    7704 out.go:201] failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\My Study\Kubernetes>
[minicube -sendilr at gmail dot com.txt](https://github.com/kubernetes/minikube/files/4574991/minicube.-sendilr.at.gmail.dot.com.txt)

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
There seems to be a lot of output from `minikube start` missing here. Could you please include it all? Thank you!

**Comment by tstromberg** [comment]
Also, please share the output of:

` VBoxManage list hostonlyifs`

**Comment by rsendil** [comment]
Team,
I have setup in the different Machine (Intel Core 2 / 4GB RAM ) machines and moved working image to my Laptop. Now I have no issues from starting or communicating to the node. 

c:\kubernetes>minikube start alsologtostderr -v=1
* minikube v1.9.2 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Automatically selected the virtualbox driver
* Starting control plane node m01 in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
! Unable to verify SSH connectivity: dial tcp 192.168.99.112:22: i/o timeout. Will retry...
! This VM is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
* Enabling addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"


C:\kubernetes>kubectl run kubernetes-first-app --image=gcr.io/google-samples/kubernetes-bootcamp:v1 --port=8080
pod/kubernetes-first-app created

C:\kubernetes>kubectl get pods -o wide
NAME                   READY   STATUS             RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
kubernetes-first-app   0/1     **ImagePullBackOff**   0          19s   172.17.0.2   minikube   <none>           <none>

C:\kubernetes>kubectl describe pods
Name:         kubernetes-first-app
Namespace:    default
Priority:     0
Node:         minikube/192.168.99.112
Start Time:   Tue, 05 May 2020 20:59:43 +0530
Labels:       run=kubernetes-first-app
Annotations:  <none>
Status:       Pending
IP:           172.17.0.2
IPs:
  IP:  172.17.0.2
Containers:
  kubernetes-first-app:
    Container ID:
    Image:          gcr.io/google-samples/kubernetes-bootcamp:v1
    Image ID:
    Port:           8080/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6v4hv (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  default-token-6v4hv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6v4hv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  5m38s                  default-scheduler  Successfully assigned default/kubernetes-first-app to minikube
  Normal   Pulling    4m13s (x4 over 5m37s)  kubelet, minikube  Pulling image "gcr.io/google-samples/kubernetes-bootcamp:v1"
  **Warning  Failed     4m13s (x4 over 5m37s)  kubelet, minikube  Failed to pull image "gcr.io/google-samples/kubernetes-bootcamp:v1": rpc error: code = Unknown desc = Error response from daemon: Get https://gcr.io/v2/: x509: certificate signed by unknown authority**
  Warning  Failed     4m13s (x4 over 5m37s)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    4m1s (x6 over 5m37s)   kubelet, minikube  Back-off pulling image "gcr.io/google-samples/kubernetes-bootcamp:v1"
  Warning  Failed     35s (x21 over 5m37s)   kubelet, minikube  Error: ImagePullBackOff

**Comment by sharifelgamal** [comment]
Yeah, the firewall will definitely cause you to not be able to pull images, check out https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/ and see if a proxy could work for you.

**Comment by chwzr** [comment]
having the same error as mentioned above:

```
minikube start
* minikube v1.10.0 auf Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
* Vorbereiten von Kubernetes v1.18.1 auf Docker 19.03.8...
E0512 17:37:36.645372   18924 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
```

**Comment by dbspace** [comment]
Same issue also, any work around

**Comment by JoseFlores97** [comment]
Same issue

**Comment by medyagh** [comment]
thanks everyone for reporting this, we have a fix for this and we will be rolling out an update tonight.

while waiting for the patch release tomorrow, you could try the work around mentioned in this PR:
https://github.com/kubernetes/minikube/pull/8083#issuecomment-627429509

again sorry for this bad experience.

**Comment by JoseFlores97** [comment]
thank you! @medyagh, I will take a look to #8083

**Comment by medyagh** [comment]
this issue will be closed to track it in one place https://github.com/kubernetes/minikube/issues/8096

**Comment by medyagh** [comment]
@JoseFlores97 @dbspace @rsendil @chwzr
while a patch is being released tonight, I encourage everyone to use our newest driver: docker

for more information see:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by medyagh** [comment]
@JoseFlores97 @dbspace @rsendil @chwzr
minikube v1.10.1 is out including fix for this bug 
https://github.com/kubernetes/minikube/releases/tag/v1.10.1

**Comment by deviljoshi** [comment]
> having the same error as mentioned above:
> 
> ```
> minikube start
> * minikube v1.10.0 auf Microsoft Windows 10 Pro 10.0.18363 Build 18363
> * Using the virtualbox driver based on existing profile
> * Starting control plane node minikube in cluster minikube
> * Restarting existing virtualbox VM for "minikube" ...
> * Vorbereiten von Kubernetes v1.18.1 auf Docker 19.03.8...
> E0512 17:37:36.645372   18924 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
> *
> X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
> *
> ```

same issue

**Comment by mwandaxm** [comment]
> @JoseFlores97 @dbspace @rsendil @chwzr
> minikube v1.10.1 is out including fix for this bug
> https://github.com/kubernetes/minikube/releases/tag/v1.10.1

hi am unable to download new version on windows, kindly assist
