### ISSUE TITLE
VirtualBox on windows: create host timed out in 240.000000 seconds

### ISSUE THREAD

**Issue by korivikeerthi** [kubernetes/minikube#7995]
when i give minikube start command the following thing appears... i'm very new to this just not getting where things are going wrong 
C:\kubernetes>minikube.exe start
* minikube v1.10.0-beta.2 on Microsoft Windows 10 Home Single Language 10.0.16299 Build 16299
* Automatically selected the virtualbox driver
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create host timed out in 240.000000 seconds
* Deleting "minikube" in virtualbox ...
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start virtualbox VM. "minikube start" may fix it: creating host: create host timed out in 240.000000 seconds
*
* [CREATE_TIMEOUT] error provisioning host Failed to start host: creating host: create host timed out in 240.000000 seconds
* Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
* Related issue: https://github.com/kubernetes/minikube/issues/7072

Help me out !!!

**Comment by sharifelgamal** [comment]
Hey @korivikeerthi, could you post the output of `minikube start --alsologtostderr -v=5`? That would give us more logs to help debug this issue. Also, are you using a VPN or a firewall? That tends to mess with minikube starting up.

**Comment by KhandelwalA** [comment]
I am also facing similar issue with minikube while starting with command "minikube start --vm-driver="hyperv" --memory=4096 --cpus=4 --hyperv-virtual-switch="minikube" --v=7 --alsologtostderr"

mine is windows 10 with hyperv machine and minikube version is   v1.10.1

**Logs**
I0527 15:18:17.406952    5340 main.go:110] libmachine: [stderr =====>] :
I0527 15:18:17.406952    5340 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipa
ddresses[0]
I0527 15:18:18.899324    5340 main.go:110] libmachine: [stdout =====>] :
I0527 15:18:18.899324    5340 main.go:110] libmachine: [stderr =====>] :
I0527 15:18:18.951254    5340 main.go:110] libmachine: [stdout =====>] :
I0527 15:18:18.951254    5340 main.go:110] libmachine: [stderr =====>] :
I0527 15:18:19.899851    5340 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0527 15:18:19.951707    5340 main.go:110] libmachine: [executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0527 15:18:20.312795    5340 start.go:107] duration metric: createHost completed in 4m0.0100657s
I0527 15:18:20.312795    5340 start.go:74] releasing machines lock for "minikube", held for 4m0.0110676s
* Failed to start hyperv VM. "minikube start" may fix it: creating host: create host timed out in 240.000000 seconds
I0527 15:18:20.312795    5340 exit.go:58] WithError(error provisioning host)=Failed to start host: creating host: create host timed out in 240.000000 seconds called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d3660, 0x18b8300)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b3f8de, 0x17, 0x1dfc340, 0xc000140a20)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b53760, 0xc000583260, 0x0, 0x6)
        /app/cmd/minikube/cmd/start.go:170 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b53760, 0xc000583200, 0x6, 0x6, 0x2b53760, 0xc000583200)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b527a0, 0x0, 0x20, 0xc0002ec860)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
*
* [CREATE_TIMEOUT] error provisioning host Failed to start host: creating host: create host timed out in 240.000000 seconds
* Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
* Related issue: https://github.com/kubernetes/minikube/issues/7072

**Comment by roy-t** [comment]
I might have an explanation.

A few months ago I installed minikube and everything worked without a hitch. Today I wanted to start minikube and I got the following error.

```
the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

I couldn't get minkube to work so I performed `minikube delete` and then again `minikube start`. I then got the error mentioned above:

```
[CREATE_TIMEOUT] error provisioning host Failed to start host: creating host: create host timed out in 240.000000 seconds
```

After some more debugging I figured out that I am on a VPN which tunnels everything. After turning off the VPN I got a different error message:

```
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

I had to perform `minikube delete` again. But when I then tried `minikube start` (while not connected to the VPN) everything worked like it should.

**Comment by YanivHaramati** [comment]
same. turned off vpn. deleted, started again, and it worked.

**Comment by TheAli711** [comment]
Facing same issue I am not using any VPN.
I am using minikube inside a vbox ubuntu vm.
the driver I am using is vbox for running minikube.
I am using bridge connection mode in VM networking on ubuntu VM.
my original host is a w10 machine.

**Comment by priyawadhwa** [comment]
@TheAli711 @korivikeerthi could you try upgrading to minikube v1.12.2 and running:

```
minikube delete --all --purge # This will completely clear your minikube environment
minikube start
```

and let us know if that works?

**Comment by TheAli711** [comment]
@priyawadhwa actyally i was using minikube within an Ubuntu 18.04 VM and now i am using minikube on Windows 10 and Ubuntu 18.04(both are host machines). It's working like a charm.

**Comment by sh-vasily** [comment]
@sharifelgamal Hello. I has same problem on windows 10, but before starting minikube, i disable vpn on my machine, so i dont know how fix that problem. P.S.: before todays problem, minikube works correctly

**Comment by tstromberg** [comment]
Closing as we haven't heard back from the original reporter in 3 months.

If you run into a similar issue, please include the output of `minikube start --alsologtostderr -v=1`. Thank you!
