### ISSUE TITLE
Run localkube outside of a container in the guest VM.

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#8]

**Comment by mfburnett** [comment]
Currently, every release of localkube ships with a binary that can be run on Linux - will need to be tested more extensively, though. https://github.com/redspread/localkube/releases/tag/v1.2.1-v1

**Comment by dlorenc** [comment]
Yeah I gave it a try and it runs, but it seems to expect some stuff from the Weave base image it's usually run inside. This should be pretty straightforward, just need to find all the dependencies and make sure they're present.

**Comment by mfburnett** [comment]
Okay cool, the only dependency is Weave, and that the proper cgroups are set up. [This script](https://github.com/redspread/localkube/blob/master/image/start.sh) shows you how to bring up localkube once Weave is installed.

**Comment by luxas** [comment]
Why a weave dep? If we want `minikube` not to use networking (local machine only), it seems a bit strange.

But it would be really cool to support either flannel or weave OOTB for the minikube server. 
We just don't have to use it for the minikube client.

That way we could reuse the minikube server for docker-multinode. WDYT @vishh?

@mfburnett When we add things to core, we should make sure `serviceAccounts` work, as it's a really important part of Kubernetes.

**Comment by mfburnett** [comment]
Yeah, ideally, the network overlay would run from within localkube, but we couldn't find an overlay that made this easy and allowed users to bring their own Docker daemon. We're not attached to Weave - open to suggestions on that front.

And yup, working on making `serviceAccounts` work!

**Comment by vishh** [comment]
Why do we even need networking support for "local cluster"? Doesn't the
default bridge network work?

On Tue, Apr 19, 2016 at 2:00 PM, Mackenzie Burnett <notifications@github.com

**Comment by mfburnett** [comment]
Hm, [as far as I know](https://github.com/kubernetes/kubernetes/blob/master/docs/design/networking.md#implementation) we need an additional overlay to make the pod-per-IP requirement work outside of GCE

**Comment by vishh** [comment]
For a single node scenario, we don't need a network plugin.

On Tue, Apr 19, 2016 at 2:13 PM, Mackenzie Burnett <notifications@github.com

**Comment by errordeveloper** [comment]
Is there no plan to provide an ability to extend the cluster with extra VMs, to simulate any realistic use-cases?

**Comment by vishh** [comment]
@errordeveloper Not in the near future. `minikube` is primarily meant to test kube apps on localhost before running them in *real* clusters.

**Comment by dlorenc** [comment]
Resolved with #44
