### ISSUE TITLE
minikube is ignoring --kvm-network

### ISSUE THREAD

**Issue by wyaeld** [kubernetes/minikube#802]
**Minikube version** (use `minikube version`):
0.12.2

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm
- **Docker version** (e.g. `docker -v`): 1.12.3
- **Install tools**: curl
- **Others**:

**What happened**:
starting minikube with kvm drivers looks for default network
I don't have a network running on default, so I configure to use the one I have.
It ignores me.
```
11:48 $ minikube start --vm-driver=kvm --kvm-network="docker-machines"
Starting local Kubernetes cluster...
E1104 12:23:43.732848   19773 start.go:92] Error starting host: Error starting stopped host: [Code-55] [Domain-19] Requested operation is not valid: network 'default' is not active. Retrying.
E1104 12:23:43.733080   19773 start.go:98] Error starting host:  Error starting stopped host: [Code-55] [Domain-19] Requested operation is not valid: network 'default' is not active
```

**What you expected to happen**:
For minikube to use the "docker-machines" network

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
```
11:39 $ virsh net-list
 Name                 State      Autostart     Persistent
----------------------------------------------------------
 docker-machines      active     no            yes
```

**Comment by r2d4** [comment]
Minikube won't set the network on subsequent calls to `start`, only on the initial create.  
Can you check if this works with a 

```
minikube delete
minikube start --vm-driver=kvm --kvm-network="docker-machines"
```

**Comment by wyaeld** [comment]
Yes, that appears to work.  Thanks

I'd suggest for user experience that maybe that just requires a warning, something along the lines of
"you have attempted to specify a different network than initial run, please destroy and create" or something.  I have no issue with the way the actual functionality works.

**Comment by r2d4** [comment]
Yeah - we're contemplating a way to split apart `create` vs. `start` in a clean way

we're tracking that here https://github.com/kubernetes/minikube/issues/364

**Comment by wyaeld** [comment]
Ok, well feel free to close this, since its not actually a bug.
