### ISSUE TITLE
Downloading kubelet v1.14.2

### ISSUE THREAD

**Issue by zhouyp520** [kubernetes/minikube#8026]
I have download kubelet via https://storage.googleapis.com/kubernetes-release/release/v1.14.2/bin/linux/amd64/kubelet,but it show 'download error'

**Comment by prasadkatti** [comment]
I was able to download the file without any issues. If you are in China, it is possible that you don't have access to https://storage.googleapis.com.

**Comment by zhouyp520** [comment]
[root@Docker bin]# ls -l
total 270232
-rw-r--r--. 1 root root     86593 Apr 29 10:49 docker-compose
-rwxr-xr-x. 1 root root  28164576 Apr 29 10:36 docker-machine
-rwxr-xr-x  1 root root  39591200 May  7 08:07 kubeadm
-rwxr-xr-x. 1 root root  39153664 May  6 15:17 kubectl
-rwxr-xr-x  1 root root 127981504 May  7 08:07 kubelet
-rwxr-xr-x. 1 root root  41728440 May  6 14:40 minikube
[root@Docker bin]# kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:20:34Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
[root@Docker bin]# pwd
/usr/local/bin

> I was able to download the file without any issues. If you are in China, it is possible that you don't have access to https://storage.googleapis.com. Can you share the command you are using to download and the output?

**Comment by zhouyp520** [comment]
> I was able to download the file without any issues. If you are in China, it is possible that you don't have access to https://storage.googleapis.com. Can you share the command you are using to download and the output?

[root@Docker bin]# kubelet
I0507 09:32:13.379417   22658 server.go:417] Version: v1.14.2
kubeadm version
kubeadm version: &version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T16:20:34Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
I manual download kubelet and kubeadm on /user/local/bin,then run 'Minikube start --vm-driver=non',it also show '[Install]
* Downloading kubeadm v1.14.2
* Downloading kubelet v1.14.2'
