### ISSUE TITLE
minikube start下载镜像时失败

### ISSUE THREAD

**Issue by rockxsj** [kubernetes/minikube#8029]
**重现问题所需的命令**：`minikube start --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --image-mirror-country=cn`

**失败的命令的完整输出**：<details>
😄  Ubuntu 16.04 上的 minikube v1.9.2
✨  根据现有的配置文件使用 docker 驱动程序
✅  正在使用镜像存储库 registry.cn-hangzhou.aliyuncs.com/google_containers
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.0 preload ...
E0507 13:58:43.325474   20819 cache.go:114] Error downloading kic artifacts:  getting remote image: Get https://gcr.io/v2/: dial tcp 108.177.125.82:443: i/o timeout
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating Kubernetes in docker container with (CPUs=2) (8 available), Memory=16000MB (64380MB available) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=16000mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
: exit status 125
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating Kubernetes in docker container with (CPUs=2) (8 available), Memory=16000MB (64380MB available) ...

💣  Failed to start docker container. "minikube start" may fix it.: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=16000mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
: exit status 125

😿  由于出错 minikube 正在退出。如果以上信息没有帮助，请提交问题反馈：
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

💣  Unable to get machine status: state: "docker inspect -f {{.State.Status}} minikube" failed: exit status 1: Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"

😿  由于出错 minikube 正在退出。如果以上信息没有帮助，请提交问题反馈：
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**使用的操作系统版本**：
Linux version 4.4.0-62-generic (buildd@lcy01-30) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017

**Comment by sharifelgamal** [comment]
see https://github.com/kubernetes/minikube/issues/7447 for issues with the docker driver in CN

**Comment by medyagh** [comment]
@rockxsj in next version of minikube we have alternative image repo for kic base image,

do you mind if you can pull this image?
```
docker pull docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10
```

if yes, the next version of minikube will automaticly try to download from github packages

**Comment by rockxsj** [comment]
@medyagh thanks for your reply,but I run a local k8s by Kind, so I won't make a try use your work around. :)

**Comment by 24king** [comment]
pull this image in one second with vpn enabled

> docker pull gcr.io/k8s-minikube/kicbase:v0.0.14

things go to well

or you can just 

> docker tag registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.14 gcr.io/k8s-minikube/kicbase:v0.0.14
