### ISSUE TITLE
Move logic out of `cmd/delete.go` so that it can be called from other packages

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#8040]
`cmd/delete.go` has a lot of interesting logic for cleaning up that is not accessible to `machine/delete.go`, and thus can't be used for cleanup on failure. 

Specifically, it allows for cleanup of orphaned KIC drivers - but we should also handle cleanup for orphaned non-KIC drivers.

**Comment by dominikbraun** [comment]
So there's a ToDo saying that `deletePossibleKicLeftOver` (and probably the functions below it) should be moved into a `delete` package:

https://github.com/kubernetes/minikube/blob/567d2f2f651368a2594af1f12dea1448872b0178/cmd/minikube/cmd/delete.go#L226-L227

* Which particular functions should be moved? `deletePossibleKicLeftOver` and everything below?
* Should the new package be something like `pkg/minikube/delete`?
