### ISSUE TITLE
Error from server (NotFound): the server could not find the requested resource - Using Ubuntu 20.04 VM on Windows

### ISSUE THREAD

**Issue by fpatino** [kubernetes/minikube#8042]
Greetings all

I'm using Minikube in an ubuntu 20.04 VM guest on VirtualBox installed in Host Windows 10 PRO. 

Managed to run the Minikube with docker driver:

agrant@vagrant:~$ minikube start --vm-driver=docker
😄  minikube v1.9.2 on Ubuntu 20.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
🔥  Creating Kubernetes in docker container with (CPUs=2) (2 available), Memory=1987MB (1987MB available) ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

Updated kubectl:

agrant@vagrant:~$ minikube kubectl -- get po -A
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 41.98 MiB / 41.98 MiB [---------------] 100.00% 2.76 MiB p/s 15s
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-66bff467f8-4wq6g           1/1     Running   0          9m4s
kube-system   coredns-66bff467f8-cp7tg           1/1     Running   0          9m4s
kube-system   etcd-minikube                      1/1     Running   0          9m20s
kube-system   kindnet-7z66f                      1/1     Running   0          9m4s
kube-system   kube-apiserver-minikube            1/1     Running   0          9m20s
kube-system   kube-controller-manager-minikube   1/1     Running   0          9m20s
kube-system   kube-proxy-kz629                   1/1     Running   0          9m4s
kube-system   kube-scheduler-minikube            1/1     Running   0          9m20s
kube-system   storage-provisioner                1/1     Running   1          9m18s

After that, checked and dashboard starts correctly.

Now following the example in https://minikube.sigs.k8s.io/docs/start/ to deploy the hello-world example I have the following error:

:~$ kubectl create deployment source-ip-app --image=k8s.gcr.io/echoserver:1.4
**Error from server (NotFound): the server could not find the requested resource**

:~$ minikube status
m01
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

Please kindly let me know what is pending to fix this error, I saw some information on the documentation that it could be related to the network interface here https://leoh0.github.io/images/kubernetes-documents-1.10.pdf .

Best regards

**Comment by fpatino** [comment]
Hi team

Installed docker in windows 10 and started minikube using docker, aparently docker enabled the hull Hyper-v functionality and restarted the machine.

Then in CMD as admin I fount that the documentation in https://minikube.sigs.k8s.io/docs/start/ for windows is missing the following way to create the deployment using kubectl:

`minikube start --alsologtostderr -v=7 

C:\WINDOWS\system32>minikube kubectl -- create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
deployment.apps/hello-minikube created

C:\WINDOWS\system32>minikube kubectl -- expose deployment hello-minikube --type=NodePort --port=8080
service/hello-minikube exposed

C:\WINDOWS\system32>minikube kubectl get services hello-minikube

C:\WINDOWS\system32>minikube kubectl -- get services hello-minikube
NAME             TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
hello-minikube   NodePort   10.98.253.202   <none>        8080:30370/TCP   28s

C:\WINDOWS\system32>minikube kubectl -- port-forward service/hello-minikube 7080:8080
Forwarding from 127.0.0.1:7080 -> 8080
Forwarding from [::1]:7080 -> 8080
Handling connection for 7080
Handling connection for 7080
Handling connection for 7080
Handling connection for 7080
Handling connection for 7080
Handling connection for 7080
`

Apparently that is how kubectl and minikube should be executed in this current version:

C:\WINDOWS\system32>minikube version
minikube version: v1.9.2
commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393

C:\WINDOWS\system32>minikube kubectl -- version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:58:59Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.0", GitCommit:"9e991415386e4cf155a24b1da15becaa390438d8", GitTreeState:"clean", BuildDate:"2020-03-25T14:50:46Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}

Hope this is useful for someone

**Comment by sharifelgamal** [comment]
Thanks for letting us know! We should add some documentation around this. Help wanted!
