### ISSUE TITLE
翻墙和阿里云镜像代理下载问题

### ISSUE THREAD

**Issue by freesia-fy** [kubernetes/minikube#8044]
**重现问题所需的命令**：minikube start --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.2.iso     --registry-mirror=https://xxxxxxxxx.mirror.aliyuncs.com         --image-repository=registry.aliyuncs.com/google_containers

**失败的命令的完整输出**：<details>
minikube v1.9.2 on Ubuntu 18.04 (vbox/amd64)
✨  Using the docker driver based on existing profile
✅  Using image repository registry.aliyuncs.com/google_containers
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.0 preload ...
E0508 18:07:26.322154   27255 cache.go:114] Error downloading kic artifacts:  getting remote image: Get https://gcr.io/v2/: dial tcp 108.177.125.82:443: i/o timeout
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating Kubernetes in docker container with (CPUs=2) (2 available), Memory=2200MB (3944MB available) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=2200mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
: exit status 125
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating Kubernetes in docker container with (CPUs=2) (2 available), Memory=2200MB (3944MB available) ...

💣  Failed to start docker container. "minikube start" may fix it.: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=2200mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81' locally
docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
: exit status 125

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
64位

**Comment by sharifelgamal** [comment]
See #7447 for issues with the docker driver in CN, there are workarounds for getting the appropriate docker drivers. The next release (1.10) will have a permanent solution to this as well.

You can also try using a VM driver like kvm2 or virtualbox.

**Comment by sharifelgamal** [comment]
This should be fixed in minikube 1.12. Please reopen if not.

**Comment by fulongli** [comment]
minikube start --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.2.iso  --image-repository=registry.aliyuncs.com/google_containers
