### ISSUE TITLE
Ubuntu minikube can't start | Docker error 125

### ISSUE THREAD

**Issue by Phantomias3782** [kubernetes/minikube#8045]
Hey,
I'm a complete beginner to minikube. I'm trying to install it on an VirtualBox clear Ubuntu System and keep getting the 125 error by executing minikube start (or minikube start --memory 4096 --cpus 4) --> (Error) Code below.
I think the problem is, that docker only recognizes 1 cpu, but I don't know how to fix that.
docker system info returns:

Kernel Version: 5.4.0-29-generic
 Operating System: Ubuntu 20.04 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 1
 Total Memory: 7.776GiB

I have already uninstalled and reinstalled the complete Ubuntu system, and kepp getting the same Error.

~/Downloads$ minikube start --memory 4096 --cpus 4
😄  minikube v1.9.2 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating Kubernetes in docker container with (CPUs=4) (1 available), Memory=4096MB (7962MB available) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=4 --memory=4096mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: docker: Error response from daemon: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available.
See 'docker run --help'.
: exit status 125

**Comment by afbjorklund** [comment]
You will need more than 2 CPUs to run, so increase the resources given to your VM.

This is supposed to be verified and displayed better, already in the `minikube start`

**Comment by afbjorklund** [comment]
Same as: ~#7850~

**Comment by Phantomias3782** [comment]
Thank you very much - Solved it!

**Comment by afbjorklund** [comment]
Out of curiosity, why did you choose Ubuntu over letting minikube set up the VirtualBox VM for you ?

**Comment by Phantomias3782** [comment]
No real reason, I just need (want) a Linux Operating System, since my MacBook Air is too weak for my further studies.

**Comment by afbjorklund** [comment]
Thanks, I was just wondering if there was something that could be improved in minikube perhaps.
