### ISSUE TITLE
Increase default disk image allocation ?

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#8050]
Something that we discussed about the Docker VM, which allocates 2 GB RAM + 1 GB swap:

As discussed in https://github.com/kubernetes/minikube/issues/7980#issuecomment-623096792

Maybe it is time to increase our default memory allocation to 4 GB, at least where available ?

Similarly, we could up the default disk image to 40 GB, since it will only occupy as much as used.

The idea would be to have something like computer games, "recommended" vs "minimum":

https://minikube.sigs.k8s.io/docs/start/

**Minimum**:
2 CPUs or more
2GB of free memory
20GB of free disk space

**Recommended**:
4 CPUs or more
4GB of free memory
40GB of free disk space

Currently we follow the recommendations from `kubeadm`, but it seems to be a bit low ?

https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/

> Before you begin
> 
>     2 GB or more of RAM per machine (any less will leave little room for your apps)
>     2 CPUs or more

We already use _more_ memory than this, so it is mostly about the documentation.

`🔥  Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...`

`🔥  Creating docker container (CPUs=2, Memory=8000MB) ...`

The hard requirement is currently 1000MB, but that requires swap to even "function".

----

Ideally this would be followed up by an analysis of where the memory is actually going...

Like monitor the memory usage over time, like we did previously with the cpu usage ?

**Comment by afbjorklund** [comment]
We could use `vmstat` for monitoring, or write our own like we did for `iostat` ("[cstat](https://github.com/tstromberg/cstat)")

```
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 1  2   1536 3625936 9905112 15017912    0    0    20   125    6   16 10  3 87  0  0
 2  0   1536 3063600 9905216 15625908    0    0     9 73857 5365 36577  9  9 73  9  0
25  0   1536 3009120 9905632 15632688    0    0     0  1424 3566 12279  8  3 88  1  0
28  0   1536 2721084 9905684 15635796    0    0     0   171 5222 12392 23  4 72  0  0
20  0   1536 2715396 9906596 15641064    0    0    13  2548 7161 23262 10  6 82  3  0
 5  0   1536 2674888 9906792 15671304    0    0  2936   329 5553 18045  7  5 87  1  0
17  0   1536 2589184 9908292 15678200    0    0    33  2283 6654 19200 11  7 80  1  0
 0  0   1536 2576704 9908520 15679836    0    0     2   387 4598 12778  6  4 89  1  0
```

We might need something more advanced for KIC, since `free` will show the host.

e.g. `docker stat` https://docs.docker.com/engine/reference/commandline/stats/

**Comment by afbjorklund** [comment]
Somewhat related to #3574

**Comment by afbjorklund** [comment]
![memory](https://user-images.githubusercontent.com/10364051/81434989-63307300-9167-11ea-87b7-736368e38352.png)

Memory usage of "docker", from start to idle.

**Comment by medyagh** [comment]
@afbjorklund I believe our new Auto Detect memory already does this for memory. but for disk size we have not done anything.

**Comment by medyagh** [comment]
I would accept a PR that would try to allocate more disk space for VM if it is available

**Comment by medyagh** [comment]
if we need disk space issue, lets create another one

**Comment by afbjorklund** [comment]
> if we need disk space issue, lets create another one

We talked about it in #8077, currently we leave 15G

It really depends on which applications you want to run...

The end goal is similar to what Vagrant is trying to do:

> When creating a base box, make sure the user will have enough disk space to do interesting things, without being annoying. For example, in VirtualBox, you should create a dynamically resizing drive with a large maximum size. This causes the actual footprint of the drive to be small initially, but to dynamically grow towards the max size as disk space is needed, providing the most flexibility for the end user.

https://www.vagrantup.com/docs/boxes/base

----

User are free to choose whatever, using the `disk-size` config.

I will probably use 32G as a compromise, size of an SD card
Like a modest 63% size increase, from 20000M to 32768M ?

It would be more interesting to work on the _monitoring_: #3574
