### ISSUE TITLE
Windows w/ VMWare Workstation not supported.

### ISSUE THREAD

**Issue by rbtcollins** [kubernetes/minikube#806]
This is a feature request. It would be really nice to support VMWare workstation as well as virtualbox.

**Minikube version** (use `minikube version`): 0.12.2

```
minikube-windows-amd64.exe start
Starting local Kubernetes cluster...
Downloading Minikube ISO
 36.00 MB / 36.00 MB [==============================================] 100.00% 0s
E1107 14:18:12.297306   50392 start.go:92] Error starting host: Error creating host: Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path". Retrying.
E1107 14:18:12.304346   50392 start.go:98] Error starting host:  Error creating host: Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
```

**Comment by r2d4** [comment]
Hey thanks for opening this up.  We would like to keep our number of supported drivers small so that we can ensure a great experience on all of them, but I think if theres enough interest in supporting this driver we could definitely add it to our list.

**Comment by cab105** [comment]
I have added some support for vmware workstation within kmachine (mainly for Linux support), and am working on porting this to minikube.  Only kicker is that it will also require augmenting the docker-machine vmwarefusion driver minikube depends on.

**Comment by rbtcollins** [comment]
@r2d4 I certainly understanding wanting to provide a great experience. Unfortunately hypervisors are at a pretty awkward spot - having two hypervisors share VT-x on a single machine is not widely supported, at least AFAICT - and nesting different hypervisors equally. So at least from my perspective, I'd rather see a working-but-not-great support for the hypervisor I happen to already be using in my development (with pointers on where to go to help improve it), than having to uninstall and reinstall hypervisors multiple times a day to meet all my use cases :P.

@cab105 cool - I haven't dug into those projects; if the learning curve isn't too steep feel free to point me at PRs to help with.

**Comment by cab105** [comment]
@rbtcollins I have created an issue with Docker Machine (https://github.com/docker/machine/issues/3868) to track this on their side.  Once it goes in, then things should mostly trickle in once the dependency in minikube gets updated.

**Comment by StefanScherer** [comment]
@rbtcollins I don't know if that fits here, but for Windows VMware Workstation there is a docker-machine driver plugin at https://github.com/pecigonzalo/docker-machine-vmwareworkstation/ as well as a chocolatey package to install it.

**Comment by cab105** [comment]
My initial PR to the docker-machine community was rejected due to not wanting to touch or modify the current collection of drivers.  As a result I have created a new repo hosting my slight modifications as: https://github.com/cab105/machine-vmware

**Comment by nerro** [comment]
any progress with this issue?

**Comment by cab105** [comment]
@nerro The driver repo should work for minikube as well as docker-machine given they both use the same plugin interface for provisioning a system.  Granted I haven't touched the repo in a while so I'm not sure how much love it needs to be brought back to snuff.
