### ISSUE TITLE
NO ARRANCA MINIKUBE

### ISSUE THREAD

**Issue by josedefrias** [kubernetes/minikube#8061]
**Los comandos necesarios para reproducir la incidencia**:
minikube start

**El resultado completo del comando que ha fallado**: <details>
[oracle@ServidorLinux7 ~]$ minikube start
😄  minikube v1.9.2 en Oracle 7.8
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node m01 in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: Maximum number of retries (5) exceeded
🏃  Updating the running virtualbox "minikube" VM ...

💣  Failed to start virtualbox VM. "minikube start" may fix it.: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027355dbe

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
[oracle@ServidorLinux7 ~]$ kubectl get pods
The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?
</details>

**El resultado del comando `minikube logs`**: <details>
[oracle@ServidorLinux7 ~]$ minikube logs

💣  Unable to get command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:34741: connect: connection refused

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**La versión del sistema operativo que utilizaste**:
Oracle Linux 7

**Comment by medyagh** [comment]
Hi @josedefrias  sorry to see you are facing a problem, to me it looks like a networking issue, are you by chance using a VPN or corp network?


in that case, I would suggest using our docker driver.
minikube delete 
minikube start --driver=docker

do you mind trying that and see if that helps?

alternatively you can try to tweak with the our virtualbox networking options by passing the nic-type but if you have docker installed, docker driver could be faster solution and better for VPN? or corp network.s

**Comment by josedefrias** [comment]
Hi Medya,
I think the problem started when I installed a new virtual machine with
Debian to configure a kubernetes master node.
This node connects to two slave nodes that are also virtual machines on
another host.
I have done what you have told me and minikube starts well if the other
machine is stopped.
There is clearly a conflict between the two virtual machines.
Thank you



Jose de Frías
e-mail: josedefrias@ipsotravel.com

**Comment by medyagh** [comment]
thank you @josedefrias if this problem only happens for multi-node, in the next version of minikube we will have a more stable multi-node experience. currently our multi-node feature is experimetnal. I will keep this issue open till we fix it. thank you

**Comment by sharifelgamal** [comment]
We don't support running Kubernetes on multiple hosts through minikube, we explicitly only support running nodes locally.
