### ISSUE TITLE
minikube start driver hyperv fails

### ISSUE THREAD

**Issue by pkhatrihds** [kubernetes/minikube#8066]
**Steps to reproduce the issue:** 

1.open CMD as administrator
2. C:\Program Files\Kubernetes\Minikube>minikube.exe start --driver=hyperv

**Full output of failed command:** 
* minikube v1.9.2 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
* Using the hyperv driver based on user configuration

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@pkhatrihds did minikube's suggestion help you ?

minikube suggests that hyperv is not installed on your windows:

```
Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
```
Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

additionally do you happen to have docker installed, in that case I would suggest our docker driver .
minikube delete
minikube start --driver=docker

**Comment by pkhatrihds** [comment]
I decided to install VirtualBox and everything is good.

**Comment by medyagh** [comment]
@pkhatrihds glad to hear your problem was solved, I still suggest you try our docker driver if you have docker installed already.
