### ISSUE TITLE
node list command not available on v1.9.2

### ISSUE THREAD

**Issue by varsharain-a11y** [kubernetes/minikube#8067]
**Steps to reproduce the issue:** 

1.[vasharma@vasharma minikube]$ minikube start
😄  minikube v1.9.2 on Redhat 7.6
✨  Using the kvm2 driver based on existing profile
👍  Starting control plane node m01 in cluster minikube
🏃  Updating the running kvm2 "minikube" VM ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
..

2. [vasharma@vasharma minikube]$ minikube node
💡  Usage: minikube node [add|start|stop|delete]

3. list option is not displayed as usage while running minikube node
~~~~~
// nodeCmd represents the set of node subcommands
var nodeCmd = &cobra.Command{
	Use:   "node",
	Short: "Add, remove, or list additional nodes",
	Long:  "Operations on nodes",
	Run: func(cmd *cobra.Command, args []string) {
		exit.UsageT("Usage: minikube node [add|start|stop|delete|list]")
	},
}

~~~~~~

**Full output of failed command:** 
[vasharma@vasharma minikube]$ minikube node
💡  Usage: minikube node [add|start|stop|delete]

[vasharma@vasharma minikube]$ minikube node list
💡  Usage: minikube node [add|start|stop|delete]

**Comment by medyagh** [comment]
@varsharain-a11y  the list command will be avialbe in our next release v1.10.0 we are planning to release today.

**Comment by medyagh** [comment]
but if you dont want to wait for the release, do u mind trying the binary in this PR to see if that adds the node list for you ?

http://storage.googleapis.com/minikube-builds/7959/minikube-linux-amd64

**Comment by varsharain-a11y** [comment]
@medyagh  
Thanks for your response i see the option is added in latest release already.

[vasharma@vasharma kubemini]$ minikube version
minikube version: v1.10.0
commit: f318680e7e5bf539f7fadeaaf198f4e468393fb9
[vasharma@vasharma Downloads]$ minikube node list
minikube	192.168.39.82
minikube-m02	192.168.39.129

**Comment by medyagh** [comment]
good to see this solved
