### ISSUE TITLE
Minikube regresion on windows

### ISSUE THREAD

**Issue by ksaminat** [kubernetes/minikube#8081]
**Steps to reproduce the issue:** 

1. Created minikube using "minikube start --driver=hyperv"
2. Start up is not successful
3. After that tried to start it explicitly using "minikube start --driver=hyperv"
I got the below error, please help,

**Full output of failed command:** 

minikube : E0512 16:50:39.407016   10648 start.go:95] Unable to get host IP: ip for interface (): Error finding IPV4 
address for vEthernet ()
At line:1 char:1
+ minikube start
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (E0512 16:50:39....or vEthernet ():String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
* 
X failed to start node: startup failed: Failed to setup kubeconfig: ip for interface (): Error finding IPV4 address for 
vEthernet ()

**Full output of `minikube start` command used, if not already included:**
PS C:\Windows\system32> minikube start --driver=hyperv
* minikube v1.10.0 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Using the hyperv driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2900MB, Disk=20000MB) ...
* Stopping "minikube" in hyperv ...
* Powering off "minikube" via SSH ...
* Deleting "minikube" in hyperv ...
minikube : ! StartHost failed, but will try again: creating host: create: provisioning: IP not found
At line:1 char:1
+ minikube start --driver=hyperv
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (! StartHost fai...g: IP not found:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
* Creating hyperv VM (CPUs=2, Memory=2900MB, Disk=20000MB) ...
* Failed to start hyperv VM. "minikube start" may fix it: creating host: create: provisioning: IP not found
* 
X error provisioning host: Failed to start host: creating host: create: provisioning: IP not found
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

PS C:\Windows\system32> minikube start
* minikube v1.10.0 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
* Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
minikube : E0512 16:50:39.407016   10648 start.go:95] Unable to get host IP: ip for interface (): Error finding IPV4 
address for vEthernet ()
At line:1 char:1
+ minikube start
+ ~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (E0512 16:50:39....or vEthernet ():String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
* 
X failed to start node: startup failed: Failed to setup kubeconfig: ip for interface (): Error finding IPV4 address for 
vEthernet ()
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tariqajyusuf** [comment]
Similar issues with minikube running on Linux via Docker

**Excerpt from logs**

```
🐳  Preparing Kubernetes v1.18.1 on Docker 19.03.2 ...
I0512 06:16:24.337060   15860 cli_runner.go:108] Run: docker network ls --filter name=bridge --format {{.ID}}
I0512 06:16:24.389400   15860 cli_runner.go:108] Run: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" ea3573d049c9
98b7bd9fcd08
E0512 06:16:24.464020   15860 start.go:95] Unable to get host IP: inspect IP bridge network "ea3573d049c9\n98b7bd9fcd08".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" ea3573d049c9
98b7bd9fcd08: exit status 1
stdout:


stderr:
Error: No such object: ea3573d049c9
98b7bd9fcd08
I0512 06:16:24.464446   15860 exit.go:58] WithError(failed to start node)=startup failed: Failed to setup kubeconfig: inspect IP bridge network "ea3573d049c9\n98b7bd9fcd08".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" ea3573d049c9
98b7bd9fcd08: exit status 1
stdout:


stderr:
Error: No such object: ea3573d049c9
98b7bd9fcd08
```

I ran this docker command manually and confirmed it does resolve, reverting to v1.9.2 seems to resolve this.

**Comment by cvila84** [comment]
It does not seem to be related to the driver as I encounter the same error with Virtualbox

```
E0512 14:47:59.177008    3040 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
panic: exit status 70
```

**Comment by Ziwi01** [comment]
> 
> 
> It does not seem to be related to the driver as I encounter the same error with Virtualbox
> 
> ```
> E0512 14:47:59.177008    3040 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
> *
> X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
> *
> * minikube is exiting due to an error. If the above message is not useful, open an issue:
>   - https://github.com/kubernetes/minikube/issues/new/choose
> panic: exit status 70
> ```

I confirm, also this happens on both VirtualBox 6.0.20 and 6.1.6. Also I'm using Minikube/VBox on Windows with kubectl from WSL. Tried to reconfigure the virtual network/adapters but it didn't seem to work at all.

**Comment by kitos9112** [comment]
Hitting similar errors here after upgrading to v1.10.0 on Windows 10 Pro

```
[admin] PS> minikube start --driver=hyperv
* minikube v1.10.0 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
* Using the hyperv driver based on user configuration

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe @(Get-Wmiobject Win32_ComputerSystem).HypervisorPresent returned ". : File C:\\Users\\****\\Documents\\WindowsPowerShell\\profile.ps1 cannot be loaded because running scripts is \r\ndisabled on this system. For more information, see about_Execution_Policies at \r\nhttps:/go.microsoft.com/fwlink/?LinkID=135170.\r\nAt line:1 char:3\r\n+ . 'C:\\Users\\***\\Documents\\WindowsPowerShell\\profile.ps1'\r\n+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : SecurityError: (:) [], PSSecurityException\r\n    + FullyQualifiedErrorId : UnauthorizedAccess\r\nTrue\r\n"
* Suggestion: Enable Hyper-V: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

[admin] PS> Get-ExecutionPolicy
Unrestricted
```

**Comment by medyagh** [comment]
@kitos9112 @ksaminat @cvila84 

we are aware of this bug, we have a PR for it, I believe it would fix this problem.
we will releae a patch release today

**Comment by medyagh** [comment]
we have two PRs that fixes both windows issue, we are sorry for this bad experience, stable windows integraiton tests will be added in our milestone as high pirority

https://github.com/kubernetes/minikube/pull/8106
https://github.com/kubernetes/minikube/pull/8103

**Comment by medyagh** [comment]
We sent out the release PRs, 
I am gonna close this issue, and track them in 
virtualbox issue: https://github.com/kubernetes/minikube/issues/8096
hyperv issue: https://github.com/kubernetes/minikube/issues/8080

**Comment by medyagh** [comment]
@ksaminat 
@cvila84
@Ziwi01
@kitos9112 

while a patch is being released tonight, I encourage everyone to use our newest driver: docker

for more information see:
https://minikube.sigs.k8s.io/docs/drivers/docker/

again sorry for this bug !

**Comment by medyagh** [comment]
minikube v1.10.1 is out including fix for this bug
https://github.com/kubernetes/minikube/releases/tag/v1.10.1

**Comment by tariqajyusuf** [comment]
@medyagh I'm still getting a repro (see https://github.com/kubernetes/minikube/issues/8081#issuecomment-627376578) on v1.10.1 on Linux:

```
😄  minikube v1.10.1 on Debian rodete
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.2 preload ...
    > preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4: 525.43 MiB
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
E0515 06:50:24.728807   18490 start.go:95] Unable to get host IP: inspect IP bridge network "f0663eed86fb\n98b7bd9fcd08".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" f0663eed86fb
98b7bd9fcd08: exit status 1
stdout:


stderr:
Error: No such object: f0663eed86fb
98b7bd9fcd08

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "f0663eed86fb\n98b7bd9fcd08".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" f0663eed86fb
98b7bd9fcd08: exit status 1
stdout:


stderr:
Error: No such object: f0663eed86fb
98b7bd9fcd08


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

Is there another place this issue is being tracked?

**Comment by sammym1982** [comment]
Having similar issue :(

```
PS C:\WINDOWS\system32> minikube start
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.19041 Build 19041
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing hyperv VM for "minikube" ...
* Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
E0613 19:17:18.301634   11356 start.go:94] Unable to get host IP: ip for interface (Default Switch): Error finding IPV4 address for vEthernet (Default Switch)
*
X failed to start node: startup failed: Failed to setup kubeconfig: ip for interface (Default Switch): Error finding IPV4 address for vEthernet (Default Switch)
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32> minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```
