### ISSUE TITLE
Minikube is not getting installed in Windows 10

### ISSUE THREAD

**Issue by padmeshgit** [kubernetes/minikube#8088]
Getting below error while installing minikube in Windows 10-- Please help

C:\Program Files\Kubernetes\Minikube>minikube.exe start
* minikube v1.10.0 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
E0512 22:33:02.050242    2480 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\Program Files\Kubernetes\Minikube>

**Comment by medyagh** [comment]
@padmeshgit  Thank you for reporting this, we are aware of this and we are fixing in a patch release, meanwhile there is an another issue that u can track it here, https://github.com/kubernetes/minikube/issues/8102

while u are waiting for the patch release, there is also a work arrond mentioned here https://github.com/kubernetes/minikube/pull/8083#issuecomment-627429509

I will close this in favor of https://github.com/kubernetes/minikube/issues/8102 to track it in a central location
