### ISSUE TITLE
"minikube addons open" only works for kube-system namespace

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#8089]
This bug has probably always been this way, but I noticed it this morning while working on addons docs.

**Comment by concaf** [comment]
@tstromberg I stumbled on this as well :thinking: How do you think this should be fixed?
Namespace can be passed via a flag - `minikube addons open <addon> --namespace <addon namespace>`, WDYT?

**Comment by priyawadhwa** [comment]
@concaf we could also check to see if <addon> is enabled and parse the namespace from addons configs if it is. That way the user doesn't have to pass in an additional flag.
