### ISSUE TITLE
X failed to start node: startup failed

### ISSUE THREAD

**Issue by AkarshAgarwal99** [kubernetes/minikube#8093]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
we have two PRs that fixes both windows issue, we are sorry for this bad experience, stable windows integraiton tests will be added in our milestone as high pirority

https://github.com/kubernetes/minikube/pull/8106
https://github.com/kubernetes/minikube/pull/8103
