### ISSUE TITLE
virtualbox on windows: Error VirtualBox Host-Only Ethernet Adapter

### ISSUE THREAD

**Issue by devmohit-live** [kubernetes/minikube#8096]
**Steps to reproduce the issue:** 

1. minikube start 

* minikube v1.10.0 on Microsoft Windows 10 Home Single Language 10.0.17134 Build 17134
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
* Found network options:
  - NO_PROXY=192.168.99.100
  - no_proxy=192.168.99.100
* Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
  - env NO_PROXY=192.168.99.100
  - env NO_PROXY=192.168.99.100
E0513 02:22:00.961660    9096 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #4
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #4
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@devmohit-live thank you for reporting this, I believe this is a regression, and we are working on it, hopefully we release a patch today or tomorrow. sorry for this bad experience.

**Comment by medyagh** [comment]
while waiting for the patch release tomorrow, you could try the work around mentioned in this PR:
https://github.com/kubernetes/minikube/pull/8083#issuecomment-627429509

again sorry for this bad experience.

**Comment by medyagh** [comment]
same as https://github.com/kubernetes/minikube/issues/7993

**Comment by medyagh** [comment]
@devmohit-live 
minikube v1.10.1 is out including fix for this bug
https://github.com/kubernetes/minikube/releases/tag/v1.10.1
