### ISSUE TITLE
Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter

### ISSUE THREAD

**Issue by bharatprakashparakh** [kubernetes/minikube#8102]
**Steps to reproduce the issue:** 

1.  minikube  start --driver=virtualbox

**Full output of failed command:** 

* minikube v1.10.0 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
* Found network options:
  - NO_PROXY=192.168.99.100
  - no_proxy=192.168.99.100
* Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
  - env NO_PROXY=192.168.99.100
  - env NO_PROXY=192.168.99.100
E0513 04:15:27.114982   17280 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
* ==> Docker <==
* -- Logs begin at Tue 2020-05-12 22:45:17 UTC, end at Tue 2020-05-12 22:46:18 UTC. --
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.731333558Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.731842515Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.732287379Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.732616797Z" level=info msg="skip loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.732653847Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.732782478Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.732799611Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.19.107\n": exit status 1"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.732812907Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734103453Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734219700Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734341676Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734383488Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734420828Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734459717Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734494049Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734527890Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734570988Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734606726Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.734999104Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.735087521Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.735747290Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.735819794Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.735912366Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.735950529Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.735982586Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736015843Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736045704Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736079867Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736111336Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736143810Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736176530Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736425906Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736471524Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736506976Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736543895Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736891400Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.736997753Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.737031818Z" level=info msg="containerd successfully booted in 0.012128s"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.754517164Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.754668447Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.754763027Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.754858828Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.756658761Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.756894034Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.756945861Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.756971944Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.867749373Z" level=warning msg="Your kernel does not support cgroup blkio weight"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.867802856Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.867815810Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.867826235Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.867836823Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.867847043Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
* May 12 22:45:24 minikube dockerd[2346]: time="2020-05-12T22:45:24.868075993Z" level=info msg="Loading containers: start."
* May 12 22:45:25 minikube dockerd[2346]: time="2020-05-12T22:45:25.102826036Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* May 12 22:45:25 minikube dockerd[2346]: time="2020-05-12T22:45:25.175899068Z" level=info msg="Loading containers: done."
* May 12 22:45:25 minikube dockerd[2346]: time="2020-05-12T22:45:25.224986632Z" level=info msg="Docker daemon" commit=afacb8b7f0 graphdriver(s)=overlay2 version=19.03.8
* May 12 22:45:25 minikube dockerd[2346]: time="2020-05-12T22:45:25.225514296Z" level=info msg="Daemon has completed initialization"
* May 12 22:45:25 minikube dockerd[2346]: time="2020-05-12T22:45:25.282754240Z" level=info msg="API listen on /var/run/docker.sock"
* May 12 22:45:25 minikube systemd[1]: Started Docker Application Container Engine.
* May 12 22:45:25 minikube dockerd[2346]: time="2020-05-12T22:45:25.283234947Z" level=info msg="API listen on [::]:2376"
*
* ==> container status <==
* time="2020-05-12T22:46:20Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
*
* ==> describe nodes <==
E0513 04:16:22.685205    3656 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
error: stat /var/lib/minikube/kubeconfig: no such file or directory
 output: "\n** stderr ** \nerror: stat /var/lib/minikube/kubeconfig: no such file or directory\n\n** /stderr **"
*
* ==> dmesg <==
* [May12 22:44] You have booted with nomodeset. This means your GPU drivers are DISABLED
* [  +0.000001] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
* [  +0.000001] Unless you actually understand what nomodeset does, you should reboot without enabling it
* [  +0.156701] APIC calibration not consistent with PM-Timer: 103ms instead of 100ms
* [  +0.059532] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
* [May12 22:45] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
* [ +12.314926] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
* [  +0.028562] systemd-fstab-generator[1362]: Ignoring "noauto" for root device
* [  +0.003817] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
* [  +0.000003] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
* [  +1.496324] vboxvideo: loading out-of-tree module taints kernel.
* [  +0.000083] vboxvideo: Unknown symbol ttm_bo_mmap (err -2)
* [  +0.000018] vboxvideo: Unknown symbol ttm_bo_global_release (err -2)
* [  +0.000015] vboxvideo: Unknown symbol ttm_bo_manager_func (err -2)
* [  +0.000006] vboxvideo: Unknown symbol ttm_bo_global_init (err -2)
* [  +0.000013] vboxvideo: Unknown symbol ttm_bo_device_release (err -2)
* [  +0.000021] vboxvideo: Unknown symbol ttm_bo_kunmap (err -2)
* [  +0.000009] vboxvideo: Unknown symbol ttm_bo_del_sub_from_lru (err -2)
* [  +0.000013] vboxvideo: Unknown symbol ttm_bo_device_init (err -2)
* [  +0.000002] vboxvideo: Unknown symbol ttm_bo_init_mm (err -2)
* [  +0.000002] vboxvideo: Unknown symbol ttm_bo_dma_acc_size (err -2)
* [  +0.000006] vboxvideo: Unknown symbol ttm_tt_init (err -2)
* [  +0.000003] vboxvideo: Unknown symbol ttm_bo_kmap (err -2)
* [  +0.000011] vboxvideo: Unknown symbol ttm_bo_add_to_lru (err -2)
* [  +0.000007] vboxvideo: Unknown symbol ttm_mem_global_release (err -2)
* [  +0.000005] vboxvideo: Unknown symbol ttm_mem_global_init (err -2)
* [  +0.000020] vboxvideo: Unknown symbol ttm_bo_init (err -2)
* [  +0.000003] vboxvideo: Unknown symbol ttm_bo_validate (err -2)
* [  +0.000010] vboxvideo: Unknown symbol ttm_bo_put (err -2)
* [  +0.000007] vboxvideo: Unknown symbol ttm_tt_fini (err -2)
* [  +0.000003] vboxvideo: Unknown symbol ttm_bo_eviction_valuable (err -2)
* [  +0.024405] vgdrvHeartbeatInit: Setting up heartbeat to trigger every 2000 milliseconds
* [  +0.010447] vboxguest: misc device minor 58, IRQ 20, I/O port d020, MMIO at 00000000f0000000 (size 0x400000)
* [  +0.547872] VBoxService 5.2.32 r132073 (verbosity: 0) linux.amd64 (Jul 12 2019 10:32:28) release log
*               00:00:00.002221 main     Log opened 2020-05-12T22:45:25.306796000Z
* [  +0.000126] 00:00:00.002396 main     OS Product: Linux
* [  +0.000086] 00:00:00.002469 main     OS Release: 4.19.107
* [  +0.000052] 00:00:00.002552 main     OS Version: #1 SMP Mon May 11 14:51:04 PDT 2020
* [  +0.000066] 00:00:00.002601 main     Executable: /usr/sbin/VBoxService
*               00:00:00.002602 main     Process ID: 2106
*               00:00:00.002603 main     Package type: LINUX_64BITS_GENERIC
* [  +0.000094] 00:00:00.002669 main     5.2.32 r132073 started. Verbose level = 0
* [  +2.249513] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
* [  +4.093010] systemd-fstab-generator[2326]: Ignoring "noauto" for root device
* [  +0.272118] systemd-fstab-generator[2336]: Ignoring "noauto" for root device
* [  +2.252856] systemd-fstab-generator[2560]: Ignoring "noauto" for root device
*
* ==> kernel <==
*  22:46:23 up 1 min,  0 users,  load average: 1.00, 0.49, 0.18
* Linux minikube 4.19.107 #1 SMP Mon May 11 14:51:04 PDT 2020 x86_64 GNU/Linux
* PRETTY_NAME="Buildroot 2019.02.10"
*
* ==> kubelet <==
* -- Logs begin at Tue 2020-05-12 22:45:17 UTC, end at Tue 2020-05-12 22:46:23 UTC. --
* -- No entries --

! unable to fetch logs for: describe nodes

</details>

**Comment by medyagh** [comment]
@bharatprakashparakh Thank you for reporting this, we are aware of this and we are fixing in a patch release, meanwhile there is an another issue that u can track it here, https://github.com/kubernetes/minikube/issues/8102

while u are waiting for the patch release, there is also a work arrond mentioned here https://github.com/kubernetes/minikube/pull/8083#issuecomment-627429509
