### ISSUE TITLE
windows: myissue

### ISSUE THREAD

**Issue by Uni-wv** [kubernetes/minikube#8113]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by Uni-wv** [comment]
minikube issue

**Comment by Uni-wv** [comment]
Full output of failed command:
minikube 1.10.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.10.1
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

! minikube v1.9.2 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Automatically selected the virtualbox driver
* Downloading VM boot image ...
    > minikube-v1.9.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.9.0.iso: 174.93 MiB / 174.93 MiB [ 100.00% 1.00 MiB p/s 2m55s
* Starting control plane node m01 in cluster minikube
* Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 542.91 MiB
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create host timed out in 120.000000 seconds
* Deleting "minikube" in virtualbox ...
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
*
* [CREATE_TIMEOUT] Failed to start virtualbox VM. "minikube start" may fix it. creating host: create host timed out in 120.000000 seconds
* Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
* Related issue: https://github.com/kubernetes/minikube/issues/7072

C:\Program Files\Kubernetes\Minikube>
C:\Program Files\Kubernetes\Minikube>
C:\Program Files\Kubernetes\Minikube>minikube.exe ip
*
X Unable to get command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\Program Files\Kubernetes\Minikube>minikube delete
* Deleting "minikube" in virtualbox ...
* Failed to delete cluster: api remove: remove C:\Users\user\.minikube\machines\minikube\minikube\Logs\VBox.log: The process cannot access the file because it is being used by another process.
* You may need to manually remove the "minikube" VM from your hypervisor
* Removing C:\Users\user\.minikube\machines\minikube ...
*
* [FILE_IN_USE] Unable to remove machine directory remove C:\Users\user\.minikube\machines\minikube\minikube\Logs\VBox.log: The process cannot access the file because it is being used by another process.
* Suggestion: Another program is using a file required by minikube. If you are using Hyper-V, try stopping the minikube VM from within the Hyper-V manager
* Documentation: https://docs.docker.com/machine/drivers/hyper-v/
* Related issue: https://github.com/kubernetes/minikube/issues/7300

**Comment by Uni-wv** [comment]
>minikube.exe  start  --driver=virtualbox
* minikube v1.9.2 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Using the virtualbox driver based on existing profile
* Starting control plane node m01 in cluster minikube
! StartHost failed, but will try again: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\user\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X Failed to start virtualbox VM. "minikube start" may fix it.: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\user\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@Uni-wv that is a known bug, we fixed it in v1.10.1, do you mind installing v1.10.1 ?

**Comment by medyagh** [comment]
@Uni-wv have u had a chance to try our latest verison it was fixed in there. I close this issue please reopen if you still have this issue with latest version
