### ISSUE TITLE
Missing leading 'v' for start command on new version available

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/minikube#8114]
**Steps to reproduce the issue:** 

1. `minikube start` on _1.10.0_
2. `minikube start` on _1.10.1_ suggests  `Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=1.18.2`
3. `minikube start --kubernetes-version=1.18.2` fails with the final line as `Suggestion: Check that your --kubernetes-version has a leading 'v'. For example: 'v1.1.14'`

**Resolution:**
The message about updating the minikube cluster should be something like
```
Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.2
```

This could either be how the strings are printed, or the actual version itself.
https://github.com/kubernetes/minikube/blob/294a5c3e7b363a999bdb5f73ef6e1b2b8b275193/cmd/minikube/cmd/start.go#L1018

**References:**
- occurrences: https://github.com/kubernetes/minikube/search?q=is+now+available.+If+you+would+like+to+upgrade%2C+specify&unscoped_q=is+now+available.+If+you+would+like+to+upgrade%2C+specify

**Comment by afbjorklund** [comment]
@BobyMCbobs : thanks for reporting, the variable should be split into two (one for user, one for machine). This "silent v" in versioning is very annoying, and comes originally from a git limitation.

> The reason for the preceding 'v' is historical. Older SCCS (cvs,rcs) could not distinguish between a tag identifier and a revision number. Tag identifiers were restricted to not begin with a numeric value so that revision numbers could be detected.

**Comment by afbjorklund** [comment]
Typically, we spent more time on changing the emoji than verifying if it actually worked :-)
