### ISSUE TITLE
Error: minikube status apiserver: Stopped kubeconfig: Misconfigured

### ISSUE THREAD

**Issue by 9kranti** [kubernetes/minikube#8116]
minikube status
![Screenshot from 2020-05-13 10-04-28](https://user-images.githubusercontent.com/61243923/81771641-2d8de000-9501-11ea-830e-4da5edf0cdab.png)

Now check minikube ip then it is pointing to docker ip
minikube ip
172.17.0.1

minikube vm configurations:
CPUs: 2
Base Memory:  16GB
Hypervisor: Oracle VirtualBox

**Comment by afbjorklund** [comment]
If you want to continue using VirtualBox, you can set it as the preferred driver:

`minikube config set vm-driver virtualbox`

```
✨  Using the virtualbox driver based on user configuration
```


Otherwise newer versions of minikube might prefer to use other drivers instead:

```
✨  Automatically selected the docker driver. Other choices: kvm2, virtualbox, podman (experimental)
```

**Comment by 9kranti** [comment]
I did minikube config set vm-driver virtualbox
output: ❗  These changes will take effect upon a minikube delete and then a minikube start

minikube delete
minikube start

Got below error
![Screenshot from 2020-05-13 15-07-15](https://user-images.githubusercontent.com/61243923/81796883-a9048700-952b-11ea-83ef-757feb20506a.png)

**Comment by afbjorklund** [comment]
@9kranti : that looks like a VirtualBox problem can sometimes be resolved by `vboxconfig` and/or rebooting. You might want to verify that you can run other VMs (than minikube) for troubleshooting

**Comment by afbjorklund** [comment]
Also it seems that you forgot to add the flags that you mentioned, for more cpus/memory

> minikube vm configurations:
> CPUs: 2
> Base Memory: 16GB
> Hypervisor: Oracle VirtualBox

**Comment by 9kranti** [comment]
Thank you for suggesting troubleshoot
I guess it's a virtualBox problem
I run `vboxconfig` and got below output
```
vboxdrv.sh: Stopping VirtualBox services.
vboxdrv.sh: Starting VirtualBox services.
```
Tested for `minishift start`
Got same error

![Screenshot from 2020-05-13 16-00-03](https://user-images.githubusercontent.com/61243923/81801982-e3255700-9532-11ea-9460-ed771d2f453a.png)

**Comment by 9kranti** [comment]
I did re-install virtualBox and minikube
I'm getting below output for `minikube status`
![Screenshot from 2020-05-13 18-40-39](https://user-images.githubusercontent.com/61243923/81816852-8a14ed80-9549-11ea-9968-e422fd8c549a.png)

where in previous working minikube I used to get output same as above except `minikube` & `type: Control Plane` lines

So why this change appeared?

**Comment by afbjorklund** [comment]
So it is working now ? The change in "status", are due to the upcoming multi-node feature

**Comment by 9kranti** [comment]
Thanks to you! It is working now and dashboard is also opening now.
One more change I observed for `minikube config view` command
Previous output: `- dashboard: true`
Current output: `- vm-driver: virtualbox`
So will you please guide me for above case?

**Comment by 9kranti** [comment]
Thanks to you! @afbjorklund It is working now and dashboard is also opening now.
One more change I observed for `minikube config view` command
Previous output:` - dashboard: true`
Current output: `- vm-driver: virtualbox`
So will you please guide me for above case?
How to check memory assigned to minikube?

**Comment by medyagh** [comment]
@9kranti minikube by default will allocate memory to your cluster.
when you start the minikube cluster, it will show in the start how big is the ram and CPU size

u can also take a look at the config in the profile config
cat ~/.minikube/profiles/minikube/config.json
