### ISSUE TITLE
minikube dashboard

### ISSUE THREAD

**Issue by vasanthakumars98** [kubernetes/minikube#8119]
Unable to enable dashboard: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.18.0/kubectl apply -f /etc/kubernetes/addons/dashboard-ns.yaml -f /etc/kubernetes/addons/dashboard-clusterrole.yaml -f /etc/kubernetes/addons/dashboard-clusterrolebinding.yaml -f /etc/kubernetes/addons/dashboard-configmap.yaml -f /etc/kubernetes/addons/dashboard-dp.yaml -f /etc/kubernetes/addons/dashboard-role.yaml -f /etc/kubernetes/addons/dashboard-rolebinding.yaml -f /etc/kubernetes/addons/dashboard-sa.yaml -f /etc/kubernetes/addons/dashboard-secret.yaml -f /etc/kubernetes/addons/dashboard-svc.yaml: exec: already started
stdout:

stderr:
]

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by 9kranti** [comment]
Try `minikube addons enable dashboard`

**Comment by sharifelgamal** [comment]
Hi @vasanthakumars98,  I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

* Your operating system 

Thank you for sharing your experience!

**Comment by vasanthakumars98** [comment]
hi @sharifelgamal here is it 
minikube start --driver=none

NAMESPACE              NAME                                         READY   STATUS    RESTARTS   AGE
kube-system            coredns-66bff467f8-22psb                     0/1     Running   0          48m
kube-system            coredns-66bff467f8-csvt5                     0/1     Running   0          48m
kube-system            etcd-vasanth                                 1/1     Running   0          48m
kube-system            kube-apiserver-vasanth                       1/1     Running   0          48m
kube-system            kube-controller-manager-vasanth              1/1     Running   0          48m
kube-system            kube-proxy-w9kfd                             1/1     Running   0          48m
kube-system            kube-scheduler-vasanth                       1/1     Running   0          48m
kube-system            storage-provisioner                          1/1     Running   0          47m
kubernetes-dashboard   dashboard-metrics-scraper-84bfdf55ff-jqvvq   1/1     Running   0          2m11s
kubernetes-dashboard   kubernetes-dashboard-bc446cc64-2r2dn         1/1     Running   2          2m11s

opreating-system: ubuntu-version 18

**Comment by vasanthakumars98** [comment]
hi @9kranti  
i have added adon dashboard and used this commnd **minikube dashboard**  
this is the output 
root@vasanth:/home/vasanth/Desktop/k8's# minikube dashboard

🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
💣  http://127.0.0.1:38843/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ is not accessible: Temporary Error: unexpected response code: 503
root@vasanth:/home/vasanth/Desktop/k8's# 
root@vasanth:/home/vasanth/Desktop/k8's# minikube dashboard

🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
💣  http://127.0.0.1:38843/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ is not accessible: Temporary Error: unexpected response code: 503
root@vasanth:/home/vasanth/Desktop/k8's#

**Comment by 9kranti** [comment]
Once try with
`minikube stop`
`minikube start`
Then go for `minikube dashboard`

**Comment by vasanthakumars98** [comment]
hi @9kranti 
i have tried to stop, delete and start many time 
eventhough is tried this manny time it wont works i was facing the same problem

**Comment by 9kranti** [comment]
Let's try this,
`minikube stop`
`minikube delete`
`minikube start --cpus 2 --memory 16g --driver hypervisor_name`
In above command please provide name of hypervisor which is installed on your system

**Comment by vasanthakumars98** [comment]
hi @9kranti 
how to find hypervisor_name 
i have just installed virtualbox while installing minikube but am not using that

**Comment by 9kranti** [comment]
You can find the list of hypervisor on Kubernetes's official documentation
In your case hypervisor is `VirtualBox`
Try below command:
`minikube start --cpus 2 --memory 16g --driver virtualbox`

**Comment by vasanthakumars98** [comment]
hi @9kranti 
while using this minikube start --cpus 2 --memory 16g --driver virtualbox
this was the output
🎉  minikube 1.10.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.10.1
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

🙄  minikube v1.9.2 on Ubuntu 18.04
✨  Using the virtualbox driver based on user configuration

❗  'virtualbox' driver reported an issue: /usr/bin/VBoxManage list hostinfo failed:

💡  Suggestion: Install the latest version of VirtualBox
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/

🛑  The "virtualbox" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/

**Comment by vasanthakumars98** [comment]
hi @9kranti 
cmd: minikube start --cpus 2 --memory 16g --driver=virtualbox --alsologtostderr
**output**
I0515 15:30:18.513600   23360 start.go:262] hostinfo: {"hostname":"vasanth","uptime":20889,"bootTime":1589515929,"procs":367,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.3.0-46-generic","virtualizationSystem":"kvm","virtualizationRole":"host","hostid":"4c4c4544-0033-5710-8038-c6c04f485831"}
I0515 15:30:18.514880   23360 start.go:272] virtualization: kvm host
😄  minikube v1.9.2 on Ubuntu 18.04
I0515 15:30:18.559460   23360 driver.go:245] Setting default libvirt URI to qemu:///system
✨  Using the virtualbox driver based on user configuration
I0515 15:30:18.894400   23360 start.go:310] selected driver: virtualbox
I0515 15:30:18.894472   23360 start.go:656] validating driver "virtualbox" against <nil>
I0515 15:30:18.894567   23360 start.go:662] status for virtualbox: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
🛑  The "virtualbox" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/

**Comment by vasanthakumars98** [comment]
hi @9kranti 
after using this cmd
minikube start  --driver=virtualbox  --force 
it's working 
thanks for your help

**Comment by afbjorklund** [comment]
Normally you **don't** log in to your system as root, but use sudo where needed instead.

https://help.ubuntu.com/community/RootSudo
