### ISSUE TITLE
StartHost failed: Could not find matching IP for MAC address 080027ae91c3

### ISSUE THREAD

**Issue by itsmeGaffoor** [kubernetes/minikube#8121]
minikube.exe start --driver=virtualbox
* minikube v1.9.2 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the virtualbox driver based on existing profile
* Starting control plane node m01 in cluster minikube
* virtualbox "minikube" VM is missing, will recreate.
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: recreate: creating host: create host timed out in 120.000000 seconds
* Updating the running virtualbox "minikube" VM ...
*
X Failed to start virtualbox VM. "minikube start" may fix it.: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027ae91c3
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by sharifelgamal** [comment]
Have you tried upgrading to minikube 1.10.1?

**Comment by itsmeGaffoor** [comment]
yes

**Comment by sharifelgamal** [comment]
This second run looks like there's an issue with the existing machine configuration. Could you try a `minikube delete` followed by another `minikube start`?

**Comment by aashish-chaubey** [comment]
@sharifelgamal I tried doing that many a times but to no avail. Is there any other way to mitigate it?

**Comment by aashish-chaubey** [comment]
Okay, I solved it on my system. Maybe the problem was this: I was running this behind a firewall software. I disabled it and bam!! it worked!

**Comment by priyawadhwa** [comment]
Great! I'll close this issue.
