### ISSUE TITLE
Add a command to list supported drivers

### ISSUE THREAD

**Issue by kschaab** [kubernetes/minikube#8127]
Need a way to call minikube to get a list of supported drivers on deployed system.  This information comes back from help but is extremely difficult to reliably parse via regex and looks to contain temporal content (like experimental):
`minikube start --help | grep -e "--driver='':"`
```      --driver='': Driver is one of: virtualbox, parallels, vmwarefusion, hyperkit, vmware, docker, podman (experimental) (defaults to auto-detect)```

This will aid us in fixing issue https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/234.

**Comment by kschaab** [comment]
Would be really nice to also return the information from Suggest in pkg/minikube/driver/driver.go in the output from this command.

**Comment by afbjorklund** [comment]
Someone was working on this (in #7679), but it seems to have stalled - we'll need to take over...

**Comment by afbjorklund** [comment]
It's equally stupid in the code base now, but should evolve into something nice from registry.

**Comment by afbjorklund** [comment]
@kschaab : the "options" command is like a side-effect of using the command framework. It's not really something that should be extended.

`Use "minikube options" for a list of global command-line options (applies to all commands).`

So this should probably use some kind of special JSON (or text?) output, similar to what we are doing for the progress output of `minikube start`

Like #8105

The easiest is probably doing it as an option to "start", even if that is a bit weird...

Another question is how much of the decision-making info we should dump
There's a side-project of building some kind of "smart" driver selection: #8012

So you could have reasons _why_ a driver is or is not being selected at the moment.
