### ISSUE TITLE
Getting the following error

### ISSUE THREAD

**Issue by imjasam** [kubernetes/minikube#8128]
$minikube start
* minikube v1.10.0 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
E0513 20:21:09.602096   12676 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@imjasam  this was a bug in v1.10.0 please upgrade to v1.10.1 and it will be fixed sorry about that
