### ISSUE TITLE
VM not reporting ip address in Hyper-V when using new minikube-iso

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#813]
The new minikube-iso is not properly reporting its ip address in HyperV.  This is causing the minikube VM to not be provisioned properly as boot2docker waits for an ip address to be up before continuing and this never occurs.
Related issue:
https://github.com/boot2docker/boot2docker/issues/300#issue-30267845

One way to fix this is to run a Hyper-V key/value daemon on the VM to report the assigned IP address which has to be put into the iso.
Similar to this:
https://github.com/boot2docker/boot2docker/blob/master/Dockerfile#L300

**Comment by dlorenc** [comment]
I'm working on this now.

**Comment by Cedric-Venet** [comment]
Hi,

I tried with minikube 0.15 and it did not work. I tried to force the most recent iso with ( minikube start --vm-driver=hyperv --v=3 --iso-url=https://storage.googleapis.com/stuff-dlorenc-vmtest2/rootfs.iso9660 ) and no luck either.

Is this supposed to work or what do I need to do to fix this issue?
