### ISSUE TITLE
kubelet resolv-conf is not overriding

### ISSUE THREAD

**Issue by okozachenko1203** [kubernetes/minikube#8130]
**Current status:**
OS: Ubuntu 18.0.4
Minikube version: 1.10.x
Driver: none
On former versions, the minikube is auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf" only when kubelet.resolv.conf is not set.
But once it is set, then auto setting is ignored, and the specified conf was overriding.

On version 1.10.x, the minikube is auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf" always.
i.e. the specified resolv conf is appending to the systemd resolv conf.

v1.9.0
$minikube start
```
...
Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
 - kubelet.resolv-conf= /run/systemd/resolve/resolv.conf 
...
```
$minikube start --extra-config=kubelet.resolv-conf=/home/zuul/.minikube/k8s_resolv.conf

```
...
Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
 - kubelet.resolv-conf=/home/zuul/.minikube/k8s_resolv.conf
...
```

v1.10.x
$minikube start
```
...
Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
 - kubelet.resolv-conf= /run/systemd/resolve/resolv.conf 
...
```
$minikube start --extra-config=kubelet.resolv-conf=/home/zuul/.minikube/k8s_resolv.conf

```
...
Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
 - kubelet.resolv-conf=/home/zuul/.minikube/k8s_resolv.conf
 - kubelet.resolv-conf= /run/systemd/resolve/resolv.conf 
...
```

**Expectation**
kubelet.resolv-conf would be overriding.
So once that is specified, then the auto setting would be ignored.

**Comment by medyagh** [comment]
this could be related to the /etc/host kueblet bug ? @priyawadhwa @tstromberg

**Comment by sharifelgamal** [comment]
I can't actually reproduce this behavior. What driver are you using?

1.9.2
```
minikube start --extra-config=kubelet.resolv-conf=/whatever
🎉  minikube 1.10.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.10.1
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

🙄  minikube v1.9.2 on Debian rodete
✨  Automatically selected the docker driver
👍  Starting control plane node m01 in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v2-v1.18.0-docker-overlay2-amd64.tar.lz4: 542.91 MiB
🔥  Creating Kubernetes in docker container with (CPUs=2) (6 available), Memory=8000MB (32149MB available) ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
    ▪ kubelet.resolv-conf=/whatever
```

1.10.1
```
minikube start --extra-config=kubelet.resolv-conf=/whatever
😄  minikube v1.10.1 on Debian rodete
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.2 preload ...
    > preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4: 525.43 MiB
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
    ▪ kubelet.resolv-conf=/whatever
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
```

**Comment by okozachenko1203** [comment]
I am using none driver.
minikube start --driver=none

**Comment by okozachenko1203** [comment]
Looking forward to update for this issue. :)

**Comment by medyagh** [comment]
@okozachenko1203 
do you mind sharing exact steps we could reproduce this issue ?
like what operating system you are using.
and all the steps that u tried, and can u reproduce this isissue in any other other VMS ?

**Comment by okozachenko1203** [comment]
> @okozachenko1203
> do you mind sharing exact steps we could reproduce this issue ?
> like what operating system you are using.
> and all the steps that u tried, and can u reproduce this isissue in any other other VMS ?
sure.
OS: Ubuntu 18.0.4
Minikube version: 1.10.x
Driver: none
I bootstrapped the minikube already by using this command.
$ minikube start --driver=none

Then when I start the cluster again, I tried to pass the extra config parameter to set the coredns resolv conf file.
Because I am using unbound as a local dns caching server so my systemd resolv conf file only includes localhost.
So I need to set the other resolv conf file which I wrote.
I used like this with the last version(1.9.x).
$minikube start --extra-config=kubelet.resolv-conf=/home/zuul/.minikube/k8s_resolv.conf

```
...
Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
 - kubelet.resolv-conf=/home/zuul/.minikube/k8s_resolv.conf
...

```
But now with 1.10.x, 
```
...
Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
 - kubelet.resolv-conf=/home/zuul/.minikube/k8s_resolv.conf
 - kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
...
```

As you can see, the /run/systemd/resolve/resolv.conf is appended automatically in the new version.
I updated the initial issue commend because I used the wrong conf path. 
I hope this information would be helpful for you to get the status of my problem.

**Comment by priyawadhwa** [comment]
Hey @okozachenko1203 could you please provide the output of 

```
minikube start --extra-config=kubelet.resolv-conf=/home/zuul/.minikube/k8s_resolv.conf --alsologtostderr
```

my guess is that the bug is related to this line:

https://github.com/kubernetes/minikube/blob/46cd3a9949b5f623726396077f034ec59a9c23ce/pkg/minikube/driver/driver.go#L172-L178

where if `/run/systemd/resolve/resolv.conf` exists on your machine it's always included

**Comment by okozachenko1203** [comment]
http://paste.openstack.org/show/793766/
Yeah, I also put eyes on that code.
But the version1.9.x has the same code, and I am not sure enough than you. :)
Anyway, I pasted the output of the command execution.

**Comment by priyawadhwa** [comment]
I think the actual fix would go here:

https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start.go#L933-L942

it could look something like:
```go
			glog.Infof("auto setting extra-config to %q.", eo)
                        # Add in this if statement
                        if config.ExtraOptions.Exists(eo) {
                                     continue
                         }
			err = config.ExtraOptions.Set(eo)
			if err != nil {
				err = errors.Wrapf(err, "setting extra option %s", eo)
			}
```

and you would need to write:

```go
func (es *ExtraOptionSlice) Exists(value string) error
```

in [extra_options.go](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/config/extra_options.go) (it would be similar to the `Set` function)

@okozachenko1203 if you, or anyone else, would be interested in fixing this please comment on this PR and I can assign you to the issue

**Comment by jbactad** [comment]
Hi is there someone already working on this? If not, @priyawadhwa can I work on it?

**Comment by okozachenko1203** [comment]
@jbactad 
seems nobody is working on this.
Isn't it, @priyawadhwa ?

**Comment by jbactad** [comment]
Cool, then I'll try to make a PR for this.

**Comment by tstromberg** [comment]
@jbactad - thank you!

**Comment by okozachenko1203** [comment]
@jbactad
Any update?:)

**Comment by okozachenko1203** [comment]
@jbactad
How is it going?
Anyway, You can escalate if you need assistance

**Comment by jbactad** [comment]
> @jbactad
> How is it going?
> Anyway, You can escalate if you need assistance

Hey @okozachenko1203 my apologies for the delay in my reply. Since this is my first issue, I needed to fill out the CLA and I am waiting for the necessary docs from my company.

I am really sorry about this. If someone wants to take up this issue for now, please go ahead.

**Comment by medyagh** [comment]
@jbactad no worries, please let me know if you need an assistance on the CLA, there should be a link on the PR you send to sign the CNCF cla
