### ISSUE TITLE
make docker driver default

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8135]

**Comment by afbjorklund** [comment]
I though it already **was** the default, at least on Linux ? Since bed70069702e8c122f4f3306298a861e1ce9f201 (v1.9.0)

Or is this about VM-docker (Docker Desktop) the default as well, on Mac and Win ?

**Comment by afbjorklund** [comment]
We have the new `--vm` flag, to revert to the previous behavior. Maybe document ?

**Comment by MrMikeFloyd** [comment]
> I though it already **was** the default, at least on Linux ? Since [bed7006](https://github.com/kubernetes/minikube/commit/bed70069702e8c122f4f3306298a861e1ce9f201) (v1.9.0)
> 
> Or is this about VM-docker (Docker Desktop) the default as well, on Mac and Win ?

Was thinking the same thing, I thought docker was the default already. Anyways, it seems as if a good bunch of users have their issues with the docker driver. As https://github.com/kubernetes/minikube/issues/4589 suggests, many users seem to be better off with the VirtualBox driver (including me on Linux). Don't know if this should be taken into account before fully committing to docker?

**Comment by afbjorklund** [comment]
The current default is hyperkit and hyperv, the previous virtualbox was changed in 1fc11f56f1d90ba79e67f2ece877c42ac83f3cbe (v1.5.0)

The VirtualBox driver is still supported, though. And it still has a big benefit of being cross-platform...

Main problem is that you can't run virtual machines from different hypervisors at the same time.
So if you already have some VMs running from before, that can stop you from using VirtualBox.

**Comment by afbjorklund** [comment]
There is a breakdown in https://minikube.sigs.k8s.io/docs/drivers/ about the different available

Would be interesting to expand this, into more of a "solutions" page, showing some more details

**Comment by afbjorklund** [comment]
With the amount of issues with the Docker driver (on Linux), I'm more learning towards reverting that.

I don't mind it (KIC) being available, but most likely we should "prefer" the Hypervisor drivers instead.
