### ISSUE TITLE
Minikube install documentation is misleading about prerequisites

### ISSUE THREAD

**Issue by redborian** [kubernetes/minikube#8137]
https://kubernetes.io/docs/tasks/tools/install-minikube/
![image](https://user-images.githubusercontent.com/6260897/81858222-36d67700-9518-11ea-9ad4-c17a1e9a3794.png)
It seems that I need a hypervisor installed
This documentation doesn’t mention that this isn’t needed if I have docker installed.

**Comment by afbjorklund** [comment]
That documentation is probably a bit outdated, the docker/podman driver part is "under construction"

**Comment by medyagh** [comment]
@tstromberg has an issue for this milestone to conslidate the docs with kubernetes

**Comment by afbjorklund** [comment]
We made a partial update (it's external to minikube), but more work needs to be done.

**Comment by sharifelgamal** [comment]
I'm going to mark this as a duplicate of #5686 since that encompasses updating this documentation. 

In the meantime, feel free to use our documentation on [getting started](https://minikube.sigs.k8s.io/docs/start/)
