### ISSUE TITLE
publish kic base image as a tar for users with no access to gcr

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8144]
currently:
1- we try to download kic base from gcr
2- we try to download from github packages images but unfrotuatenly github packages requires login, even if you wanna download a public image.

I think if those two fail, we should fail over to downloading the TarBall from github and user docker load
as the absolute last resort.
this would be very handy for users in china.

**Comment by afbjorklund** [comment]
Tarball creation as per #7766, as mentioned it would also work for other runtimes (than docker)

One _positive_ side effect is that you will get a progress bar (#7012), also missing from our library.

**Comment by medyagh** [comment]
agree, I would accept any PR that would do this as a Fall back solution

**Comment by medyagh** [comment]
closing this as we have docker hub and github packages
