### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by Shruti1970** [kubernetes/minikube#8146]
**Steps to reproduce the issue:** 

(https://docs.google.com/document/d/1nic7qPJo40KR1Il6MLhmIm7eywsdyUMM4kn6ieyNZjY/edit?usp=sharing)
Please resolve my this query 

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@Shruti1970 I noticed you are using an older minikube verion , please use our latest version 
https://minikube.sigs.k8s.io/docs/start/

and also I wonder if you have docker on your system?
if yes you can use our newest docker driver

minikube delete
minikube start --driver=docker
