### ISSUE TITLE
minikube can't see the newly created multi-node cluster

### ISSUE THREAD

**Issue by charleszheng44** [kubernetes/minikube#8150]
**Steps to reproduce the issue:** 

1. simply run `minikube start --nodes 2 -p multinode-demo --network-plugin=cni --extra-config=kubeadm.pod-network-cidr=10.244.0.0/16`

**Full output of failed command:** 
```bash
😄  [multinode-demo] minikube v1.9.2 on Darwin 10.14.6
✨  Automatically selected the hyperkit driver
👍  Starting control plane node multinode-demo in cluster multinode-demo
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🌟  Enabling addons: default-storageclass, storage-provisioner

👍  Starting node multinode-demo-m02 in cluster multinode-demo
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ NO_PROXY=192.168.64.213
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
🏄  Done! kubectl is now configured to use "multinode-demo"
```

**Optional: Full output of `minikube logs` command:**
```bash
🤷  There is no local cluster named "minikube"
👉  To fix this, run: "minikube start"
```

The multi-nodes cluster is created as expected, but I can't use command like,
`minikube delete`, `minikube ssh`, `minikube status`. Seems like the minikube can't see the newly created multi-node cluster, is this because the name of the multi-node cluster is `minikube-demo`? 

The version of the minikube I am using is 
```bash
minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278
```

**Comment by medyagh** [comment]
@charleszheng44 thank you for reporint this, multi node is still experimental feature. do you mind providing the start logs with 

--alsologtostderr -v=8 ?

CC:
@sharifelgamal

**Comment by sharifelgamal** [comment]
The `-p multinode-demo` in the`minikube start` command means you're specifying a profile name other than `minikube`. You'll have to specify `-p multinode-demo` for any other minikube commands to interact with it.

To avoid having to do that, just omit the `-p multinode-demo` from the initial minikube start call.

**Comment by charleszheng44** [comment]
@sharifelgamal Thanks! it works!

**Comment by mikhailkrotov-42crunch** [comment]
@charleszheng44 you can make this profile the default one using : `minikube profile multinode-demo`. This ensures you do not have to pass the profile name in further minikube commands.
