### ISSUE TITLE
Configuring ingress using minikube

### ISSUE THREAD

**Issue by glinker** [kubernetes/minikube#8153]
**Steps to reproduce the issue:** 

1.  minikube config set ingress true

This used to work but now i get an error saying no such option "ingress" 

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@glinker do u mind clraifying what you are trying to do ? I dont think u can enable ingress by config. I think you are probabbly loooking for minikube addon enable ingress ?

**Comment by glinker** [comment]
@medyagh thanks for the response. It appears that the mechanism to enable ingress changed with later versions of minikube. Before, it was "minikube set config ingress true" to "minikube addon enable ingress". I was able to get this set up and working

**Comment by medyagh** [comment]
> ponse. It appears that the mechanism to enable ingress changed with later versions of minikube. Before, it was "minikube set config ingress true" but has now changed to "minikube addon enable ingress". I was able to get this set up and working

glad to see the issue was solved, do you mind sharing what driver did you use on what operating system and what example did you run?

our documentation on ingress has been a bit out dated, it would be nice to see end users using it with eaxmples in a tutorial on our website. https://minikube.sigs.k8s.io/docs/

**Comment by skrtks** [comment]
"minikube addon enable ingress" does not seem to be working in v1.10.1. The command does not give any errors, but when checking if the controller is running (kubectl get pods -n kube-system), the status is ImagePullBackOff.

**Comment by pashakopot** [comment]
> "minikube addon enable ingress" does not seem to be working in v1.10.1. The command does not give any errors, but when checking if the controller is running (kubectl get pods -n kube-system), the status is ImagePullBackOff.

Seems like quay.io is down

Failed to pull image "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.32.0": rpc error: code = Unknown desc = Error response from daemon: Get https://quay.io/v2/kubernetes-ingress-controller/nginx-ingress-controller/manifests/0.32.0: received unexpected HTTP status: 500 Internal Server Error

**Comment by kevinresol** [comment]
And this is down again, right now.

<img width="872" alt="Screenshot 2020-05-28 at 10 11 07 PM" src="https://user-images.githubusercontent.com/1103788/83152230-2802dd80-a130-11ea-9de4-16c4f4cdebcc.png">

**Comment by jgoeres** [comment]
I noticed the same issue and came here looking for a way to tell minikube to pull the ingress controller image from some other location, alas this seems not possible. Or is it?
How about allowing to set an alternative image (plus pull secret!) for the ingress addon (or for ANY add on that pulls an image)? That would allow people that use minikube in their internal process to host such images on internal registries, to not have a dependency on external systems.

**Comment by sharifelgamal** [comment]
I'm going to close this in favor of #8298, I think properly supporting alternate repositories for addons is a good idea.
