### ISSUE TITLE
Minikube v1.10 - Error dialing TCP: dial tcp 192.168.64.4:22: connect: operation timed out - MacOs

### ISSUE THREAD

**Issue by jes-micron** [kubernetes/minikube#8162]
**Steps to reproduce the issue:** 
I am trying to bring up minikube but facing the below issue. Can someone point what am I doing wrong?

1. minikube start --alsologtostderr -v=7
2. 
3.

**Full output of failed command:** 
W0515 17:11:20.874683    7055 root.go:252] Error reading config file at /Users/jesam/.minikube/config/config.json: While parsing config: unexpected end of JSON input
I0515 17:11:20.909783    7055 start.go:99] hostinfo: {"hostname":"jesam-qlvcj.local","uptime":10580,"bootTime":1589532300,"procs":368,"os":"darwin","platform":"darwin","platformFamily":"","platformVersion":"10.14.6","kernelVersion":"18.7.0","virtualizationSystem":"","virtualizationRole":"","hostid":"a52cf11d-a733-3e77-832b-d42063739c84"}
W0515 17:11:20.909907    7055 start.go:107] gopshost.Virtualization returned error: not implemented yet
😄  minikube v1.10.1 on Darwin 10.14.6
I0515 17:11:20.923950    7055 notify.go:125] Checking for updates...
I0515 17:11:20.924656    7055 main.go:110] libmachine: Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
I0515 17:11:20.924734    7055 main.go:110] libmachine: Launching plugin server for driver hyperkit
I0515 17:11:20.938085    7055 main.go:110] libmachine: Plugin server listening at address 127.0.0.1:58087
I0515 17:11:20.938675    7055 main.go:110] libmachine: () Calling .GetVersion
I0515 17:11:20.939306    7055 main.go:110] libmachine: Using API Version  1
I0515 17:11:20.939326    7055 main.go:110] libmachine: () Calling .SetConfigRaw
I0515 17:11:20.939631    7055 main.go:110] libmachine: () Calling .GetMachineName
I0515 17:11:20.939753    7055 main.go:110] libmachine: (minikube) Calling .DriverName
I0515 17:11:20.939865    7055 driver.go:253] Setting default libvirt URI to qemu:///system
I0515 17:11:20.940156    7055 main.go:110] libmachine: Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
I0515 17:11:20.940187    7055 main.go:110] libmachine: Launching plugin server for driver hyperkit
I0515 17:11:20.954771    7055 main.go:110] libmachine: Plugin server listening at address 127.0.0.1:58091
I0515 17:11:20.955484    7055 main.go:110] libmachine: () Calling .GetVersion
I0515 17:11:20.956045    7055 main.go:110] libmachine: Using API Version  1
I0515 17:11:20.956067    7055 main.go:110] libmachine: () Calling .SetConfigRaw
I0515 17:11:20.956421    7055 main.go:110] libmachine: () Calling .GetMachineName
I0515 17:11:20.956566    7055 main.go:110] libmachine: (minikube) Calling .DriverName
✨  Using the hyperkit driver based on existing profile
I0515 17:11:20.986874    7055 start.go:215] selected driver: hyperkit
I0515 17:11:20.986897    7055 start.go:594] validating driver "hyperkit" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.10.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:4000 CPUs:2 DiskSize:20000 Driver:hyperkit HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.2 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0515 17:11:20.987023    7055 start.go:600] status for hyperkit: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0515 17:11:20.987093    7055 install.go:49] acquiring lock: {Name:mk4023283b30b374c3f04c8805d539e68824c0b8 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0515 17:11:20.987233    7055 install.go:115] Validating docker-machine-driver-hyperkit, PATH=/Users/jesam/.minikube/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/apache-maven-3.6.3/bin
I0515 17:11:23.040770    7055 install.go:77] stdout: /usr/local/bin/docker-machine-driver-hyperkit
I0515 17:11:23.040798    7055 install.go:79] /usr/local/bin/docker-machine-driver-hyperkit looks good
I0515 17:11:23.040933    7055 iso.go:118] acquiring lock: {Name:mk31610b9b9772bc864b85fa65dc6a71494f7e2d Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
👍  Starting control plane node minikube in cluster minikube
I0515 17:11:23.056014    7055 preload.go:81] Checking if preload exists for k8s version v1.18.2 and runtime docker
I0515 17:11:23.056115    7055 preload.go:96] Found local preload: /Users/jesam/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4
I0515 17:11:23.056148    7055 cache.go:48] Caching tarball of preloaded images
I0515 17:11:23.056177    7055 preload.go:122] Found /Users/jesam/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0515 17:11:23.056188    7055 cache.go:51] Finished verifying existence of preloaded tar for  v1.18.2 on docker
I0515 17:11:23.056364    7055 profile.go:156] Saving config to /Users/jesam/.minikube/profiles/minikube/config.json ...
I0515 17:11:23.057846    7055 cache.go:132] Successfully downloaded all kic artifacts
I0515 17:11:23.057900    7055 start.go:223] acquiring machines lock for minikube: {Name:mkf3681309a24a02e0eb3f4bcd921ed5edb43624 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0515 17:11:23.057998    7055 start.go:227] acquired machines lock for "minikube" in 73.861µs
I0515 17:11:23.058027    7055 start.go:87] Skipping create...Using existing machine configuration
I0515 17:11:23.058041    7055 fix.go:53] fixHost starting: 
I0515 17:11:23.058528    7055 main.go:110] libmachine: Found binary path at /usr/local/bin/docker-machine-driver-hyperkit
I0515 17:11:23.058571    7055 main.go:110] libmachine: Launching plugin server for driver hyperkit
I0515 17:11:23.075392    7055 main.go:110] libmachine: Plugin server listening at address 127.0.0.1:58098
I0515 17:11:23.076292    7055 main.go:110] libmachine: () Calling .GetVersion
I0515 17:11:23.076952    7055 main.go:110] libmachine: Using API Version  1
I0515 17:11:23.076988    7055 main.go:110] libmachine: () Calling .SetConfigRaw
I0515 17:11:23.077413    7055 main.go:110] libmachine: () Calling .GetMachineName
I0515 17:11:23.077572    7055 main.go:110] libmachine: (minikube) Calling .DriverName
I0515 17:11:23.077710    7055 main.go:110] libmachine: (minikube) Calling .GetState
I0515 17:11:23.077867    7055 main.go:110] libmachine: (minikube) DBG | exe=/usr/local/bin/docker-machine-driver-hyperkit uid=0
I0515 17:11:23.078186    7055 main.go:110] libmachine: (minikube) DBG | hyperkit pid from json: 6676
I0515 17:11:23.079578    7055 main.go:110] libmachine: (minikube) DBG | hyperkit pid 6676 missing from process table
I0515 17:11:23.079628    7055 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
I0515 17:11:23.079655    7055 main.go:110] libmachine: (minikube) Calling .DriverName
W0515 17:11:23.079780    7055 fix.go:131] unexpected machine state, will restart: <nil>
🔄  Restarting existing hyperkit VM for "minikube" ...
I0515 17:11:23.093250    7055 main.go:110] libmachine: (minikube) Calling .Start
I0515 17:11:23.093457    7055 main.go:110] libmachine: (minikube) DBG | exe=/usr/local/bin/docker-machine-driver-hyperkit uid=0
I0515 17:11:23.093499    7055 main.go:110] libmachine: (minikube) minikube might have been shutdown in an unclean way, the hyperkit pid file still exists: /Users/jesam/.minikube/machines/minikube/hyperkit.pid
I0515 17:11:23.094892    7055 main.go:110] libmachine: (minikube) DBG | hyperkit pid 6676 missing from process table
I0515 17:11:23.094909    7055 main.go:110] libmachine: (minikube) DBG | pid 6676 is in state "Stopped"
I0515 17:11:23.094932    7055 main.go:110] libmachine: (minikube) DBG | Removing stale pid file /Users/jesam/.minikube/machines/minikube/hyperkit.pid...
I0515 17:11:23.095507    7055 main.go:110] libmachine: (minikube) DBG | Using UUID 4e7e9bc0-969f-11ea-b7ff-acde48001122
I0515 17:11:23.280043    7055 main.go:110] libmachine: (minikube) DBG | Generated MAC be:e8:6d:25:0:3b
I0515 17:11:23.280072    7055 main.go:110] libmachine: (minikube) DBG | Starting with cmdline: loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
I0515 17:11:23.281934    7055 main.go:110] libmachine: (minikube) DBG | Attempt 0
I0515 17:11:23.281963    7055 main.go:110] libmachine: (minikube) DBG | exe=/usr/local/bin/docker-machine-driver-hyperkit uid=0
I0515 17:11:23.282099    7055 main.go:110] libmachine: (minikube) DBG | hyperkit pid from json: 7078
I0515 17:11:23.283817    7055 main.go:110] libmachine: (minikube) DBG | Searching for be:e8:6d:25:0:3b in /var/db/dhcpd_leases ...
I0515 17:11:23.283886    7055 main.go:110] libmachine: (minikube) DBG | Found 3 entries in /var/db/dhcpd_leases!
I0515 17:11:23.283923    7055 main.go:110] libmachine: (minikube) DBG | dhcp entry: {Name:minikube IPAddress:192.168.64.4 HWAddress:be:e8:6d:25:0:3b ID:1,be:e8:6d:25:0:3b Lease:0x5ebfcf5a}
I0515 17:11:23.283956    7055 main.go:110] libmachine: (minikube) DBG | Found match: be:e8:6d:25:0:3b
I0515 17:11:23.283968    7055 main.go:110] libmachine: (minikube) DBG | IP: 192.168.64.4
I0515 17:11:23.284009    7055 main.go:110] libmachine: (minikube) Calling .GetConfigRaw
I0515 17:11:23.284680    7055 main.go:110] libmachine: (minikube) Calling .DriverName
I0515 17:11:23.284819    7055 machine.go:86] provisioning docker machine ...
I0515 17:11:23.284833    7055 main.go:110] libmachine: (minikube) Calling .DriverName
I0515 17:11:23.284975    7055 main.go:110] libmachine: (minikube) Calling .GetMachineName
I0515 17:11:23.285101    7055 buildroot.go:163] provisioning hostname "minikube"
I0515 17:11:23.285113    7055 main.go:110] libmachine: (minikube) Calling .GetMachineName
I0515 17:11:23.285247    7055 main.go:110] libmachine: (minikube) Calling .GetSSHHostname
I0515 17:11:23.285383    7055 main.go:110] libmachine: (minikube) Calling .GetSSHPort
I0515 17:11:23.285536    7055 main.go:110] libmachine: (minikube) Calling .GetSSHKeyPath
I0515 17:11:23.285733    7055 main.go:110] libmachine: (minikube) Calling .GetSSHKeyPath
I0515 17:11:23.285855    7055 main.go:110] libmachine: (minikube) Calling .GetSSHUsername
I0515 17:11:23.286003    7055 main.go:110] libmachine: Using SSH client type: native
I0515 17:11:23.286182    7055 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x13b8360] 0x13b8330 <nil>  [] 0s} 192.168.64.4 22 <nil> <nil>}
I0515 17:11:23.286196    7055 main.go:110] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0515 17:11:23.335476    7055 main.go:110] libmachine: (minikube) DBG | 2020/05/15 17:11:23 fcntl(F_PUNCHHOLE) failed: host filesystem does not support sparse files: Operation not permitted
I0515 17:11:23.822180    7055 main.go:110] libmachine: (minikube) DBG | 2020/05/15 17:11:23 rdmsr to register 0x140 on vcpu 0
I0515 17:11:23.936591    7055 main.go:110] libmachine: (minikube) DBG | 2020/05/15 17:11:23 rdmsr to register 0x140 on vcpu 1
I0515 17:11:27.453818    7055 main.go:110] libmachine: (minikube) DBG | 2020/05/15 17:11:27 rdmsr to register 0x64e on vcpu 0
I0515 17:11:27.453846    7055 main.go:110] libmachine: (minikube) DBG | 2020/05/15 17:11:27 rdmsr to register 0x34 on vcpu 0
I0515 17:12:39.481284    7055 main.go:110] libmachine: Error dialing TCP: dial tcp 192.168.64.4:22: connect: operation timed out

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@jes-micron the log is not fully pasted,

are u using a VPN ?
do you mind trying our docker driver and see if that fixes the problem?

minikube delete
minikube start --driver=docker

**Comment by jes-micron** [comment]
@medyagh,
I had to downgrade the minikube version to 1.9 and start minikube using the docker driver which started without any issues. I was wondering as to why minikube won't come up using hyperkit.

**Comment by medyagh** [comment]
@jes-micron unforutnately that is a limitation of VPN on hyperkit driver, there is not much we can do about it, but I recommenmd using the docker driver  and there is no need to downgrade to 1.9, you should be able to use the latest version for the docker driver..

is there any reason u wanted to downgrde?

**Comment by priyawadhwa** [comment]
Hey @jes-micron -- does the docker driver work with our latest release, [v1.11.0](https://github.com/kubernetes/minikube/releases/tag/v1.11.0)?

**Comment by priyawadhwa** [comment]
Hey @jes-micron are you still seeing this issue?

**Comment by sharifelgamal** [comment]
Hey @jes-micron  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
