### ISSUE TITLE
Issues in opening minikube

### ISSUE THREAD

**Issue by ShirshaDatta** [kubernetes/minikube#8177]
**Steps to reproduce the issue:** 

1.minikube.exe start
2. minikube.exe start driver=virtualbox
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
* minikube v1.10.0 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* virtualbox "minikube" VM is missing, will recreate.
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
E0516 18:43:24.258432    7276 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>
* minikube v1.10.0 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
* Automatically selected the virtualbox driver
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
E0516 19:05:28.401991   18520 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #2
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**Comment by medyagh** [comment]
@ShirshaDatta this is a bug in v1.10.0  please ugprade to the v1.10.1 and that should be fixed.

I will close this issue. please reopen if upgrading doesn't fix this
