### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by sugo-85** [kubernetes/minikube#8178]
![11](https://user-images.githubusercontent.com/64470929/82126028-737bca00-97c7-11ea-82c2-c25a0b7f4d09.JPG)

**Comment by medyagh** [comment]
@sugo-85 your apiserver seems to be stopped, please try this
minikube stop
minikube start

does that fix the problem?

**Comment by priyawadhwa** [comment]
Hey @sugo-85  -- Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
