### ISSUE TITLE
minikube.exe v1.9.2: X Failed to setup certs: Unable to decode certificate *

### ISSUE THREAD

**Issue by prakashchoudhary110** [kubernetes/minikube#8181]
C:\Program Files\Kubernetes\Minikube>minikube.exe start
* minikube v1.9.2 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Using the virtualbox driver based on existing profile
* Starting control plane node m01 in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Preparing Kubernetes v1.18.2 on Docker 19.03.8 ...
*
X Failed to setup certs: profile certs: generate signed cert for "minikube": Unable to decode certificate
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@prakashchoudhary110

Thank you for sharing your experience! If you don't mind, could you please provide:
minikube start with logs?
```
minikube start --alsologtostderr 
```
also I noticed  your minikube version is outdated have you had chance to try our newest verison ? minikube v1.10.1 ?

**Comment by prakashchoudhary110** [comment]
I0518 23:28:34.991136   27184 main.go:110] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="f4b59d8f-69db-496c-a90b-c9ff2d2b905a"
CfgFile="C:\\Users\\sai\\.minikube\\machines\\minikube\\minikube\\minikube.vbox"
SnapFldr="C:\\Users\\sai\\.minikube\\machines\\minikube\\minikube\\Snapshots"
LogFldr="C:\\Users\\sai\\.minikube\\machines\\minikube\\minikube\\Logs"
hardwareuuid="f4b59d8f-69db-496c-a90b-c9ff2d2b905a"
memory=2200
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2020-05-18T17:57:59.293000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\sai\.minikube\machines\minikube\boot2docker.iso"
"SATA-ImageUUID-0-0"="77f5a5ce-71c0-40c3-9bbf-536bf0ad2377"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\sai\.minikube\machines\minikube\disk.vmdk"
"SATA-ImageUUID-1-0"="26390aff-a3f0-45c6-9e88-e6f950ad430a"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800272FC706"
cableconnected1="on"
nic1="nat"
nictype1="virtio"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,51888,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #3"
macaddress2="0800277CE80A"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="dsound"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="\\\\?\\c:\\Users"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens=""
capturefilename="C:\\Users\\sai\\.minikube\\machines\\minikube\\minikube\\minikube.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.2.32 r132056"
GuestAdditionsFacility_VirtualBox Base Driver=50,1589824701070
GuestAdditionsFacility_VirtualBox System Service=50,1589824701363
GuestAdditionsFacility_Seamless Mode=0,1589824701070
GuestAdditionsFacility_Graphics Mode=0,1589824701070
}
I0518 23:28:34.991136   27184 main.go:110] libmachine: STDERR:
{
}
I0518 23:28:34.995038   27184 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0518 23:28:35.048013   27184 main.go:110] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="f4b59d8f-69db-496c-a90b-c9ff2d2b905a"
CfgFile="C:\\Users\\sai\\.minikube\\machines\\minikube\\minikube\\minikube.vbox"
SnapFldr="C:\\Users\\sai\\.minikube\\machines\\minikube\\minikube\\Snapshots"
LogFldr="C:\\Users\\sai\\.minikube\\machines\\minikube\\minikube\\Logs"
hardwareuuid="f4b59d8f-69db-496c-a90b-c9ff2d2b905a"
memory=2200
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2020-05-18T17:57:59.293000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\sai\.minikube\machines\minikube\boot2docker.iso"
"SATA-ImageUUID-0-0"="77f5a5ce-71c0-40c3-9bbf-536bf0ad2377"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\sai\.minikube\machines\minikube\disk.vmdk"
"SATA-ImageUUID-1-0"="26390aff-a3f0-45c6-9e88-e6f950ad430a"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800272FC706"
cableconnected1="on"
nic1="nat"
nictype1="virtio"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,51888,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #3"
macaddress2="0800277CE80A"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="dsound"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="\\\\?\\c:\\Users"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens=""
capturefilename="C:\\Users\\sai\\.minikube\\machines\\minikube\\minikube\\minikube.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.2.32 r132056"
GuestAdditionsFacility_VirtualBox Base Driver=50,1589824701070
GuestAdditionsFacility_VirtualBox System Service=50,1589824701363
GuestAdditionsFacility_Seamless Mode=0,1589824701070
GuestAdditionsFacility_Graphics Mode=0,1589824701070
}
I0518 23:28:35.048013   27184 main.go:110] libmachine: STDERR:
{
}
I0518 23:28:35.052735   27184 main.go:110] libmachine: Host-only MAC: 0800277ce80a

I0518 23:28:35.061409   27184 main.go:110] libmachine: Using SSH client type: native
I0518 23:28:35.061409   27184 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x7c0950] 0x7c0920 <nil>  [] 0s} 127.0.0.1 51888 <nil> <nil>}
I0518 23:28:35.061409   27184 main.go:110] libmachine: About to run SSH command:
ip addr show
I0518 23:28:35.174625   27184 main.go:110] libmachine: SSH cmd err, output: <nil>: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:2f:c7:06 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86387sec preferred_lft 86387sec
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:7c:e8:0a brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.107/24 brd 192.168.99.255 scope global dynamic eth1
       valid_lft 1187sec preferred_lft 1187sec
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:7e:32:70:f7 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

I0518 23:28:35.175600   27184 main.go:110] libmachine: SSH returned: 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:2f:c7:06 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.15/24 brd 10.0.2.255 scope global dynamic eth0
       valid_lft 86387sec preferred_lft 86387sec
3: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 08:00:27:7c:e8:0a brd ff:ff:ff:ff:ff:ff
    inet 192.168.99.107/24 brd 192.168.99.255 scope global dynamic eth1
       valid_lft 1187sec preferred_lft 1187sec
4: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
5: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:7e:32:70:f7 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever

END SSH

I0518 23:28:35.180479   27184 profile.go:156] Saving config to C:\Users\sai\.minikube\profiles\minikube\config.json ...
I0518 23:28:35.191216   27184 ssh_runner.go:148] Run: curl -sS -m 2 https://k8s.gcr.io/
I0518 23:28:35.191216   27184 sshutil.go:44] new ssh client: &{IP:127.0.0.1 Port:51888 SSHKeyPath:C:\Users\sai\.minikube\machines\minikube\id_rsa Username:docker}
I0518 23:28:35.213664   27184 ssh_runner.go:148] Run: systemctl --version
I0518 23:28:35.213664   27184 sshutil.go:44] new ssh client: &{IP:127.0.0.1 Port:51888 SSHKeyPath:C:\Users\sai\.minikube\machines\minikube\id_rsa Username:docker}
I0518 23:28:35.286865   27184 preload.go:81] Checking if preload exists for k8s version v1.18.2 and runtime docker
I0518 23:28:35.286865   27184 preload.go:96] Found local preload: C:\Users\sai\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4
I0518 23:28:35.305407   27184 ssh_runner.go:148] Run: docker images --format {{.Repository}}:{{.Tag}}
I0518 23:28:35.344447   27184 docker.go:379] Got preloaded images:
I0518 23:28:35.344447   27184 docker.go:384] k8s.gcr.io/kube-proxy:v1.18.2 wasn't preloaded
I0518 23:28:35.360210   27184 ssh_runner.go:148] Run: sudo cat /var/lib/docker/image/overlay2/repositories.json
I0518 23:28:35.382511   27184 ssh_runner.go:148] Run: which lz4
I0518 23:28:36.509479   27184 ssh_runner.go:148] Run: stat -c "%s %y" /preloaded.tar.lz4
I0518 23:28:36.519249   27184 ssh_runner.go:205] existence check for /preloaded.tar.lz4: stat -c "%s %y" /preloaded.tar.lz4: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/preloaded.tar.lz4': No such file or directory
I0518 23:28:36.521192   27184 ssh_runner.go:215] scp C:\Users\sai\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4 --> /preloaded.tar.lz4 (550953823 bytes)
I0518 23:28:38.988518   27184 ssh_runner.go:188] Completed: curl -sS -m 2 https://k8s.gcr.io/: (3.7973024s)
W0518 23:28:38.988518   27184 start.go:486] [curl -sS -m 2 https://k8s.gcr.io/] failed: curl -sS -m 2 https://k8s.gcr.io/: Process exited with status 28
stdout:

stderr:
curl: (28) Resolving timed out after 2000 milliseconds
! This VM is having trouble accessing https://k8s.gcr.io
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
I0518 23:29:04.670619   27184 docker.go:345] Took 28.172853 seconds to copy over tarball
I0518 23:29:04.688181   27184 ssh_runner.go:148] Run: sudo tar -I lz4 -C /var -xvf /preloaded.tar.lz4
I0518 23:29:54.401386   27184 ssh_runner.go:188] Completed: sudo tar -I lz4 -C /var -xvf /preloaded.tar.lz4: (49.7122523s)
I0518 23:29:54.593749   27184 ssh_runner.go:99] rm: /preloaded.tar.lz4
I0518 23:29:55.722891   27184 ssh_runner.go:148] Run: sudo cat /var/lib/docker/image/overlay2/repositories.json
I0518 23:29:55.759218   27184 ssh_runner.go:215] scp memory --> /var/lib/docker/image/overlay2/repositories.json (3128 bytes)
I0518 23:29:55.826386   27184 ssh_runner.go:148] Run: sudo systemctl daemon-reload
I0518 23:29:55.957170   27184 ssh_runner.go:148] Run: sudo systemctl restart docker
I0518 23:29:58.494728   27184 ssh_runner.go:188] Completed: sudo systemctl restart docker: (2.5375587s)
I0518 23:29:58.599161   27184 ssh_runner.go:148] Run: sudo systemctl cat docker.service
I0518 23:29:58.635270   27184 ssh_runner.go:148] Run: sudo systemctl is-active --quiet service containerd
I0518 23:29:58.806071   27184 ssh_runner.go:148] Run: sudo systemctl is-active --quiet service crio
I0518 23:29:58.843163   27184 ssh_runner.go:148] Run: sudo systemctl daemon-reload
I0518 23:29:59.622050   27184 ssh_runner.go:148] Run: sudo systemctl start docker
I0518 23:29:59.647381   27184 ssh_runner.go:148] Run: docker version --format {{.Server.Version}}
* Preparing Kubernetes v1.18.2 on Docker 19.03.8 ...
I0518 23:30:06.057749   27184 start.go:251] checking
I0518 23:30:06.088991   27184 ssh_runner.go:148] Run: grep 192.168.250.1        host.minikube.internal$ /etc/hosts
I0518 23:30:06.094838   27184 ssh_runner.go:148] Run: /bin/bash -c "{ grep -v '\thost.minikube.internal$' /etc/hosts; echo "192.168.250.1       host.minikube.internal"; } > /tmp/h.$$; sudo cp /tmp/h.$$ /etc/hosts"
I0518 23:30:06.140711   27184 preload.go:81] Checking if preload exists for k8s version v1.18.2 and runtime docker
I0518 23:30:06.140711   27184 preload.go:96] Found local preload: C:\Users\sai\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4
I0518 23:30:06.158278   27184 ssh_runner.go:148] Run: docker images --format {{.Repository}}:{{.Tag}}
I0518 23:30:06.191505   27184 docker.go:379] Got preloaded images: -- stdout --
kubernetesui/dashboard:v2.0.0
k8s.gcr.io/kube-proxy:v1.18.2
k8s.gcr.io/kube-scheduler:v1.18.2
k8s.gcr.io/kube-apiserver:v1.18.2
k8s.gcr.io/kube-controller-manager:v1.18.2
k8s.gcr.io/pause:3.2
k8s.gcr.io/coredns:1.6.7
k8s.gcr.io/etcd:3.4.3-0
kubernetesui/metrics-scraper:v1.0.2
gcr.io/k8s-minikube/storage-provisioner:v1.8.1

-- /stdout --
I0518 23:30:06.191505   27184 docker.go:317] Images already preloaded, skipping extraction
I0518 23:30:06.208053   27184 ssh_runner.go:148] Run: docker images --format {{.Repository}}:{{.Tag}}
I0518 23:30:06.243191   27184 docker.go:379] Got preloaded images: -- stdout --
kubernetesui/dashboard:v2.0.0
k8s.gcr.io/kube-proxy:v1.18.2
k8s.gcr.io/kube-scheduler:v1.18.2
k8s.gcr.io/kube-controller-manager:v1.18.2
k8s.gcr.io/kube-apiserver:v1.18.2
k8s.gcr.io/pause:3.2
k8s.gcr.io/coredns:1.6.7
k8s.gcr.io/etcd:3.4.3-0
kubernetesui/metrics-scraper:v1.0.2
gcr.io/k8s-minikube/storage-provisioner:v1.8.1

-- /stdout --
I0518 23:30:06.255930   27184 cache_images.go:69] Images are preloaded, skipping loading
I0518 23:30:06.331306   27184 kubeadm.go:124] kubeadm options: {CertDir:/var/lib/minikube/certs ServiceCIDR:10.96.0.0/12 PodSubnet: AdvertiseAddress:192.168.99.107 APIServerPort:8443 KubernetesVersion:v1.18.2 EtcdDataDir:/var/lib/minikube/etcd ClusterName:minikube NodeName:minikube DNSDomain:cluster.local CRISocket: ImageRepository: ComponentOptions:[{Component:apiServer ExtraArgs:map[enable-admission-plugins:NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota] Pairs:map[certSANs:["127.0.0.1", "localhost", "192.168.99.107"]]}] FeatureArgs:map[] NoTaintMaster:true NodeIP:192.168.99.107 ControlPlaneAddress:control-plane.minikube.internal KubeProxyOptions:map[]}
I0518 23:30:06.514571   27184 kubeadm.go:128] kubeadm config:
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 192.168.99.107
  bindPort: 8443
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: "minikube"
  kubeletExtraArgs:
    node-ip: 192.168.99.107
  taints: []
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs: ["127.0.0.1", "localhost", "192.168.99.107"]
  extraArgs:
    enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
certificatesDir: /var/lib/minikube/certs
clusterName: mk
controlPlaneEndpoint: control-plane.minikube.internal:8443
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/minikube/etcd
kubernetesVersion: v1.18.2
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
# disable disk resource management by default
imageGCHighThresholdPercent: 100
evictionHard:
  nodefs.available: "0%"
  nodefs.inodesFree: "0%"
  imagefs.available: "0%"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clusterCIDR: ""
metricsBindAddress: 192.168.99.107:10249

I0518 23:30:06.612163   27184 ssh_runner.go:148] Run: docker info --format {{.CgroupDriver}}
I0518 23:30:06.662869   27184 kubeadm.go:737] kubelet [Unit]
Wants=docker.socket

[Service]
ExecStart=
ExecStart=/var/lib/minikube/binaries/v1.18.2/kubelet --authorization-mode=Webhook --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --cgroup-driver=systemd --client-ca-file=/var/lib/minikube/certs/ca.crt --cluster-domain=cluster.local --config=/var/lib/kubelet/config.yaml --container-runtime=docker --fail-swap-on=false --hostname-override=minikube --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=192.168.99.107 --pod-manifest-path=/etc/kubernetes/manifests

[Install]
 config:
{KubernetesVersion:v1.18.2 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:}
I0518 23:30:06.678486   27184 ssh_runner.go:148] Run: sudo ls /var/lib/minikube/binaries/v1.18.2
I0518 23:30:06.716671   27184 binaries.go:43] Found k8s binaries, skipping transfer
I0518 23:30:06.731188   27184 ssh_runner.go:148] Run: sudo mkdir -p /var/tmp/minikube /etc/systemd/system/kubelet.service.d /lib/systemd/system
I0518 23:30:06.740949   27184 ssh_runner.go:215] scp memory --> /var/tmp/minikube/kubeadm.yaml.new (1448 bytes)
I0518 23:30:06.758519   27184 ssh_runner.go:215] scp memory --> /etc/systemd/system/kubelet.service.d/10-kubeadm.conf (535 bytes)
I0518 23:30:06.774136   27184 ssh_runner.go:215] scp memory --> /lib/systemd/system/kubelet.service (349 bytes)
I0518 23:30:06.789751   27184 start.go:251] checking
I0518 23:30:06.805364   27184 ssh_runner.go:148] Run: grep 192.168.99.107       control-plane.minikube.internal$ /etc/hosts
I0518 23:30:06.809271   27184 ssh_runner.go:148] Run: /bin/bash -c "{ grep -v '\tcontrol-plane.minikube.internal$' /etc/hosts; echo "192.168.99.107     control-plane.minikube.internal"; } > /tmp/h.$$; sudo cp /tmp/h.$$ /etc/hosts"
I0518 23:30:06.833668   27184 ssh_runner.go:148] Run: sudo systemctl daemon-reload
I0518 23:30:06.944002   27184 ssh_runner.go:148] Run: sudo systemctl start kubelet
I0518 23:30:07.112852   27184 certs.go:52] Setting up C:\Users\sai\.minikube\profiles\minikube for IP: 192.168.99.107
I0518 23:30:07.191906   27184 certs.go:169] skipping minikubeCA CA generation: C:\Users\sai\.minikube\ca.key
I0518 23:30:07.229988   27184 certs.go:169] skipping proxyClientCA CA generation: C:\Users\sai\.minikube\proxy-client-ca.key
I0518 23:30:07.244860   27184 certs.go:267] generating minikube-user signed cert: C:\Users\sai\.minikube\profiles\minikube\client.key
I0518 23:30:07.258513   27184 crypto.go:69] Generating cert C:\Users\sai\.minikube\profiles\minikube\client.crt with IP's: []
I0518 23:30:07.617650   27184 exit.go:58] WithError(Failed to setup certs)=profile certs: generate signed cert for "minikube-user": Unable to decode certificate called from:
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x20fb)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b3ad1b, 0x15, 0x1dfc340, 0xc0007d4180)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/pkg/minikube/node.setupKubeAdm(0x1e65f40, 0xc00020ec00, 0xc00025c8a0, 0x8, 0x0, 0xc000272690, 0x40, 0xc0004741c0, 0x6b, 0x898, ...)
        /app/pkg/minikube/node/start.go:285 +0x4fc
k8s.io/minikube/pkg/minikube/node.Start(0x1e3a940, 0xc000004f00, 0x1, 0x1e65f40, 0xc00020ec00, 0xc0000ef740, 0xc000059880, 0xc000067d40, 0xc00047f0e0, 0x4e01, ...)
        /app/pkg/minikube/node/start.go:110 +0x412
k8s.io/minikube/cmd/minikube/cmd.startWithDriver(0x1e3a940, 0xc000004f00, 0x1, 0x1e65f40, 0xc00020ec00, 0xc0000ef740, 0xc000059880, 0xc000067d40, 0xc00047f0e0, 0xc000204e00, ...)
        /app/cmd/minikube/cmd/start.go:281 +0x83
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b53760, 0xc000604cd0, 0x0, 0x1)
        /app/cmd/minikube/cmd/start.go:202 +0x6f3
github.com/spf13/cobra.(*Command).execute(0x2b53760, 0xc000604cc0, 0x1, 0x1, 0x2b53760, 0xc000604cc0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b527a0, 0x0, 0x20, 0xc00011fd00)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
W0518 23:30:07.618379   27184 out.go:201] Failed to setup certs: profile certs: generate signed cert for "minikube-user": Unable to decode certificate
*
X Failed to setup certs: profile certs: generate signed cert for "minikube-user": Unable to decode certificate
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\Program Files\Kubernetes\Minikube>

> @prakashchoudhary110
> 
> Thank you for sharing your experience! If you don't mind, could you please provide:
> minikube start with logs?
> 
> ```
> minikube start --alsologtostderr 
> ```
> 
> also I noticed your minikube version is outdated have you had chance to try our newest verison ? minikube v1.10.1 ?
> 
> also I noticed you are using virtualbox driver, have u tried our newest driver, docker ?

**Comment by priyawadhwa** [comment]
Hey @prakashchoudhary110 we fixed some Windows bugs in our latest release -- could you try [v1.10.1](https://github.com/kubernetes/minikube/releases/tag/v1.10.1) and let us know if you still see this bug?

**Comment by sharifelgamal** [comment]
It looks like your cert files are malformed in some way, you could try a `minikube delete` followed by another `minikube start` as a test. Also you can try using our latest release, v1.11.0 as see if that helps as well.

**Comment by prakashchoudhary110** [comment]
every possible condition I try, but not solve problem... but the same problem is occurring like this:
Failed to setup certs: profile certs: generate signed cert for "minikube-user": Unable to decode certificate
*
X Failed to setup certs: profile certs: generate signed cert for "minikube-user": Unable to decode certificate
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@prakashchoudhary110 
could you please help me with this addiotional information so I could try to find a solution ?
1- Run in an administrative powershell
2- Run with latest version of minikbue
either v1.11.0
https://minikube.sigs.k8s.io/docs/start/
or the beta 
https://github.com/kubernetes/minikube/releases/tag/v1.12.0-beta.0

**Comment by medyagh** [comment]
Hi @@prakashchoudhary110, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
