### ISSUE TITLE
connecting to the kubernetes service using curl cmd

### ISSUE THREAD

**Issue by vasanthakumars98** [kubernetes/minikube#8191]
minikube start --driver=docker --force

kubectl apply -f kubedemo.yaml

NAME                        READY   STATUS    RESTARTS   AGE   IP           NODE       NOMINATED NODE   READINESS GATES
pod/smef-567b56d6ff-lcjnk   1/1     Running   0          34m   172.18.0.6   minikube   <none>           <none>

NAME                 TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE   SELECTOR
service/kubernetes   ClusterIP   10.96.0.1        <none>        443/TCP          68m   <none>
service/smef         NodePort    10.110.128.125   <none>        8080:30491/TCP   34m   app=smef

NAME                   READY   UP-TO-DATE   AVAILABLE   AGE   CONTAINERS   IMAGES                                 SELECTOR
deployment.apps/smef   1/1     1            1           34m   smef         gcr.io/google-samples/node-hello:1.0   app=smef

NAME                              DESIRED   CURRENT   READY   AGE   CONTAINERS   IMAGES                                 SELECTOR
replicaset.apps/smef-567b56d6ff   1         1         1       34m   smef         gcr.io/google-samples/node-hello:1.0   app=smef,pod-template-hash=567b56d6ff

kubectl describe services

Name:                     smef
Namespace:                default
Labels:                   <none>
Annotations:              Selector:  app=smef
Type:                     NodePort
IP:                       10.110.128.125
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30491/TCP
Endpoints:                172.18.0.6:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>

root@vasanth:/home/vasanth/Desktop/k8's# curl 172.18.0.6:8080
curl: (7) Failed to connect to 172.18.0.6 port 8080: No route to host

i cant even acces this from the internet
This is my yaml file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smef
  labels:
    app: smef
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smef
  template:
    metadata:
      labels:
        app: smef
    spec:
            #volumes:
            # - name: storage
            # persistentVolumeClaim:
            # claimName: creating-claim
      containers:
      - name: smef
        image: gcr.io/google-samples/node-hello:1.0
        ports:        
        - containerPort: 8080
          name: smef
          #  volumeMounts:
          #- mountPath: "/vasanth/data echo > hi"
          # name: storage
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: smef
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    app: smef

how can i acces this service

**Comment by afbjorklund** [comment]
If you use the docker driver on a VM platform (Mac or Win), you need to tunnel the ports.

See #7879

**Comment by vasanthakumars98** [comment]
hi @afbjorklund 
how to tunnel the port ?
in yaml file ?

**Comment by afbjorklund** [comment]
See https://minikube.sigs.k8s.io/docs/start/

**Comment by vasanthakumars98** [comment]
i have exposed but even though i can access.
but using minikube service smef --url 
this url is coming http://172.17.0.3:30871/ 
and it can be access

**Comment by vasanthakumars98** [comment]
kubectl describe service smef

Name:                     smef
Namespace:                default
Labels:                   <none>
Annotations:              Selector:  app=smef
Type:                     NodePort
IP:                       10.101.148.177
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  30871/TCP
Endpoints:                172.18.0.6:8080
Session Affinity:         None
External Traffic Policy:  Cluster
Events:                   <none>
root@vasanth:/home/vasanth/Desktop/k8's# curl 172.18.0.6
curl: (7) Failed to connect to 172.18.0.6 port 80: No route to host

while using endpoint ip i cant access

**Comment by afbjorklund** [comment]
NodePort only works on Linux, when using the Docker driver

**Comment by vasanthakumars98** [comment]
hi @afbjorklund 
am using ubuntu its also like a linux right then how can use endpoint ip to access the services in the chrome as well as in terminal using curl cmd ?

**Comment by afbjorklund** [comment]
> am using ubuntu its also like a linux

ah, ok. Then the IP should be readily available, for instance through your port 30871 above.

You just seemed to have picked the wrong port, i.e. target port 8080 rather than node port 30491

so something like http://172.18.0.6:30491/ should have worked to access it, sorry about the noise

If you report your minikube version and OS next time, there will be less chance for such confusion

**Comment by vasanthakumars98** [comment]
how to report the minikube version and os where to report ?

**Comment by vasanthakumars98** [comment]
using none driver how to access dash board ?
is there any posibel ?

**Comment by vasanthakumars98** [comment]
hi @afbjorklund 
is there ant possible to deploy and access dashboard using none driver ?
i have enabled dashboard  but in i cant access

**Comment by afbjorklund** [comment]
There is nothing special when using the "none" driver, maybe that the VM might be missing a browser.
