### ISSUE TITLE
Add vmwarefusion driver to `cluster.HostIP` function

### ISSUE THREAD

**Issue by dongkaipo** [kubernetes/minikube#8193]
**重现问题所需的命令**：
`minikube start --driver=vmwarefusion`
**失败的命令的完整输出**：<details>
```
😄  Darwin 10.15.4 上的 minikube v1.10.1
✨  根据现有的配置文件使用 vmwarefusion 驱动程序
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running vmwarefusion "minikube" VM ...
🐳  正在 Docker 19.03.8 中准备 Kubernetes v1.18.2…
E0518 23:53:04.604248     896 start.go:95] Unable to get host IP: HostIP not yet implemented for "vmwarefusion" driver

💣  failed to start node: startup failed: Failed to setup kubeconfig: HostIP not yet implemented for "vmwarefusion" driver

😿  由于出错 minikube 正在退出。如果以上信息没有帮助，请提交问题反馈：
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

</details>

**`minikube logs`命令的输出**：<details>
==> Docker <==
-- Logs begin at Mon 2020-05-18 15:49:28 UTC, end at Mon 2020-05-18 15:54:40 UTC. --
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.884628945Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.884678535Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.884744515Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.884963079Z" level=info msg="skip loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.884995662Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.885032298Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.885039469Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.19.107\n": exit status 1"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.885046095Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.886782027Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.886855222Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.886942687Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.886956482Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.886965971Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.886976451Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.886986674Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.886997551Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.887037729Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.887049841Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.887193067Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.887247706Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888227713Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888278140Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888319046Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888332460Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888341712Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888350482Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888359213Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888368708Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888377283Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888387248Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888395771Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888502811Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888540248Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888553077Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888561772Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888774360Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.888911496Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.889213796Z" level=info msg="containerd successfully booted in 0.009032s"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.901359277Z" level=info msg="parsed scheme: \"unix\"" module=grpc
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.901404573Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.901468890Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.901521889Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.903379070Z" level=info msg="parsed scheme: \"unix\"" module=grpc
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.903418374Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.903437261Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.903446208Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.985988786Z" level=warning msg="Your kernel does not support cgroup blkio weight"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.986056617Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.986067799Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.986124499Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.986133402Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.986139441Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
May 18 15:49:32 minikube dockerd[3453]: time="2020-05-18T15:49:32.986542038Z" level=info msg="Loading containers: start."
May 18 15:49:33 minikube dockerd[3453]: time="2020-05-18T15:49:33.114927648Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
May 18 15:49:33 minikube dockerd[3453]: time="2020-05-18T15:49:33.153512818Z" level=info msg="Loading containers: done."
May 18 15:49:33 minikube dockerd[3453]: time="2020-05-18T15:49:33.206340119Z" level=info msg="Docker daemon" commit=afacb8b7f0 graphdriver(s)=overlay2 version=19.03.8
May 18 15:49:33 minikube dockerd[3453]: time="2020-05-18T15:49:33.206547436Z" level=info msg="Daemon has completed initialization"
May 18 15:49:33 minikube dockerd[3453]: time="2020-05-18T15:49:33.228415402Z" level=info msg="API listen on /var/run/docker.sock"
May 18 15:49:33 minikube dockerd[3453]: time="2020-05-18T15:49:33.229055720Z" level=info msg="API listen on [::]:2376"
May 18 15:49:33 minikube systemd[1]: Started Docker Application Container Engine.

==> container status <==
time="2020-05-18T15:54:42Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> describe nodes <==
E0518 23:54:43.277274     948 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.2/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.2/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
error: stat /var/lib/minikube/kubeconfig: no such file or directory
 output: "\n** stderr ** \nerror: stat /var/lib/minikube/kubeconfig: no such file or directory\n\n** /stderr **"

==> dmesg <==
[May18 15:49] You have booted with nomodeset. This means your GPU drivers are DISABLED
[  +0.000001] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
[  +0.000000] Unless you actually understand what nomodeset does, you should reboot without enabling it
[  +0.059906] core: CPUID marked event: 'cpu cycles' unavailable
[  +0.000001] core: CPUID marked event: 'instructions' unavailable
[  +0.000000] core: CPUID marked event: 'bus cycles' unavailable
[  +0.000000] core: CPUID marked event: 'cache references' unavailable
[  +0.000001] core: CPUID marked event: 'cache misses' unavailable
[  +0.000000] core: CPUID marked event: 'branch instructions' unavailable
[  +0.000000] core: CPUID marked event: 'branch misses' unavailable
[  +0.012214] pmd_set_huge: Cannot satisfy [mem 0xf0000000-0xf0200000] with a huge-page mapping due to MTRR override.
[  +8.448911] sd 0:0:0:0: [sda] Assuming drive cache: write through
[  +0.062654] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +5.037878] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[  +0.021389] systemd-fstab-generator[1950]: Ignoring "noauto" for root device
[  +0.001697] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000002] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +2.352247] vboxguest: loading out-of-tree module taints kernel.
[  +0.006292] vboxguest: PCI device not found, probably running on physical hardware.
[  +0.095266] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +2.386619] systemd-fstab-generator[3433]: Ignoring "noauto" for root device
[  +0.103334] systemd-fstab-generator[3443]: Ignoring "noauto" for root device
[  +1.682528] systemd-fstab-generator[3659]: Ignoring "noauto" for root device
[May18 15:51] NFSD: Unable to end grace period: -110
[May18 15:53] systemd-fstab-generator[3781]: Ignoring "noauto" for root device

==> kernel <==
 15:54:43 up 5 min,  0 users,  load average: 0.04, 0.11, 0.05
Linux minikube 4.19.107 #1 SMP Mon May 11 14:51:04 PDT 2020 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2019.02.10"

==> kubelet <==
-- Logs begin at Mon 2020-05-18 15:49:28 UTC, end at Mon 2020-05-18 15:54:43 UTC. --
-- No entries --

❗  unable to fetch logs for: describe nodes

</details>

**使用的操作系统版本**：
macOS Catalina 10.15.4

**Comment by priyawadhwa** [comment]
Hey @dongkaipo 

Unfortunately it seems that a required function, `HostIP` has not been implemented for vmwarefusion

I'll mark this issue as a feature request. Until this feature is added, could you try using one of the alternate drivers available for darwin? (docker or hyperkit are well supported)

If you, or anyone else, would be interested in contributing this feature, please comment on this PR.


嘿 @dongkaipo 

不幸的是，似乎尚未为vmwarefusion实现必需的功能HostIP。

我将此问题标记为功能请求。在添加此功能之前，您是否可以尝试使用可用于darwin的替代驱动程序之一（很好地支持docker或hyperkit）

如果您或任何其他人有兴趣提供此功能，请对此PR进行评论。

**Comment by dongkaipo** [comment]
更换了驱动，可以正常使用了
