### ISSUE TITLE
mount:  unknown filesystem type '9p'

### ISSUE THREAD

**Issue by Daniel42VTS** [kubernetes/minikube#8202]
mount problems after update of docker desktop to 2.3.0.2 and minikube update. Before it was also not stable as it timed out randomly

minikube start
* minikube v1.10.1 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the docker driver based on existing profile
* Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=1.18.2
* Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=1.18.2
* Starting control plane node minikube in cluster minikube
* Restarting existing docker container for "minikube" ...
* Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
  - kubeadm.pod-network-cidr=10.244.0.0/16
* Enabled addons: dashboard, default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"
**Steps to reproduce the issue:** 

1. minikube start
2. minikube mount -> error

**Full output of failed command:** 
minikube mount "C:\tmp\mqdocker:/mqdocker"
* Mounting host path C:\tmp\mqdocker into VM as /mqdocker ...
  - Mount type:   <no value>
  - User ID:      docker
  - Group ID:     docker
  - Version:      9p2000.L
  - Message Size: 262144
  - Permissions:  755 (-rwxr-xr-x)
  - Options:      map[]
  - Bind Address: 127.0.0.1:50922
* Userspace file server: ufs starting
*
X mount failed: mount with cmd /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=50922,trans=tcp,version=9p2000.L 192.168.65.2 /mqdocker" : /bin/bash -c "sudo mount -t 9p -o dfltgid=$(grep ^docker: /etc/group | cut -d: -f3),dfltuid=$(id -u docker),msize=262144,port=50922,trans=tcp,version=9p2000.L 192.168.65.2 /mqdocker": Process exited with status 32
stdout:

stderr:
mount: /mqdocker: unknown filesystem type '9p'.

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
I think the mount support depends on the kernel, and the Docker VM might not have it (9p)

**Comment by afbjorklund** [comment]
You can verify, by looking under `/lib/modules` (with ssh). It is `kernel/fs/9p/9p.ko`

**Comment by Daniel42VTS** [comment]
`docker@minikube:/lib/modules/4.19.76-linuxkit/kernel/fs$ ls -l
total 8
drwxr-xr-x 1 root root 2048 Apr  3 15:55 lockd
drwxr-xr-x 1 root root 2048 Apr  3 15:55 nfs
drwxr-xr-x 1 root root 2048 Apr  3 15:55 nfs_common
drwxr-xr-x 1 root root 2048 Apr  3 15:55 nfsd`

you are right its missing in kernel

**Comment by Daniel42VTS** [comment]
how can I add that 9p module into kernel?

**Comment by afbjorklund** [comment]
> how can I add that 9p module into kernel?

I don't think that you can, the kernel comes with Docker Desktop (in their LinuxKit OS)...

Maybe file a ticket, but anyway...

So basically "minikube mount" is broken, but possibly there is another way to share files ?
https://www.docker.com/blog/deep-dive-into-new-docker-desktop-filesharing-implementation/

But it is not integregated (yet?)

**Comment by afbjorklund** [comment]
@medyagh : this was the "minikube mount" bug, that was failing on Docker Desktop

it _might_ work with Docker Engine, depending on whether the host has `9p` or not.
i.e. for Red Hat they forcibly remove it in all their kernels, but Ubuntu still provides it.

I think the way forward here, beyond docker-specific options, is to allow using NFS: #4324

**Comment by Daniel42VTS** [comment]
mount is possible by reinstalling again older version of Docker Desktop (v2.1.0.5) 
(still not stable; input/output error after some time - but at least it works some time)

**Comment by humantargetjoe** [comment]
/remove-lifecycle stale

Also experiencing with Minikube running on CentOS 7.

**Comment by gvtaras** [comment]
Same issue:
os: macOS 10.15.6
docker: 19.03.12
docker desktop: 2.3.0.5

**Comment by gdnnasonovandrey** [comment]
Hello!
I am experiencing the same issue on Linux. Did anyone find a fix for this? Kernel's version 5.10.75-1

**Comment by nasonovandrey** [comment]
Hello! I'm also experiencing the same issue on Linux, kernel's version 5.10.75-1. Did anyone find a fix?

**Comment by afbjorklund** [comment]
> Hello! I'm also experiencing the same issue on Linux, kernel's version 5.10.75-1. Did anyone find a fix?

Make sure that your kernel is configured with support for the 9p file system. (`CONFIG_9P_FS` and friends)
