### ISSUE TITLE
Upgrade help text does not include "v" in the version number

### ISSUE THREAD

**Issue by alewis001** [kubernetes/minikube#8205]
**Steps to reproduce the issue:** 

1. Have an existing cluster that is running K8s less than 1.18.2
2. Start the cluster
3. Note the Message: `Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=1.18.2`
    * This message was also duplicated in the console output.
4. Stop the cluster.
5. Start the cluster, including the suggested argument: `--kubernetes-version=1.18.2`
    * Start fails with message: `[KUBERNETES_VERSION_MISSING_V] Failed to update cluster updating node: generating kubeadm cfg: parsing Kubernetes version: strconv.ParseUint: parsing "": invalid syntax`
6. Change the command line parameter to `--kubernetes-version=v1.18.2` (I.e. v1.18.2, not 1.18.2).
7. Start succeeds.

**Full output of failed command:** 
`mk -p bug start`
😄  [bug] minikube v1.10.1 on Darwin 10.15.4
✨  Using the hyperkit driver based on existing profile
🆕  Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=1.18.2
🆕  Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=1.18.2
👍  Starting control plane node bug in cluster bug
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v3-v1.18.0-docker-overlay2-amd64.tar.lz4: 525.45 MiB
🔄  Restarting existing hyperkit VM for "bug" ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
🌟  Enabled addons: default-storageclass, ingress, ingress-dns, metrics-server, storage-provisioner
🏄  Done! kubectl is now configured to use "bug"

`minikube -p bug start --kubernetes-version=1.18.2`
😄  [bug] minikube v1.10.1 on Darwin 10.15.4
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node bug in cluster bug
🔄  Restarting existing hyperkit VM for "bug" ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.8 ...
❌  Unable to load cached images: loading cached images: stat /Users/alewis/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.18.2: no such file or directory

❌  [KUBERNETES_VERSION_MISSING_V] Failed to update cluster updating node: generating kubeadm cfg: parsing Kubernetes version: strconv.ParseUint: parsing "": invalid syntax
💡  Suggestion: Check that your --kubernetes-version has a leading 'v'. For example: 'v1.1.14'

**Comment by alewis001** [comment]
Apologies, I should have included that I've seen this in minikube 1.10.1, I've not tested older versions.

**Comment by afbjorklund** [comment]
Duplicate of issue #8114. And the suggestion offered should still work, i.e. `v1.18.2`

**Comment by alewis001** [comment]
Doh! I promise I searched for a duplicate before raising this one! :)  

I'll close this.

**Comment by afbjorklund** [comment]
Another amazing feature is four different version number standards in two lines of text.

:smile: [bug] minikube v1.10.1 on Darwin 10.15.4
:whale: Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...

Most likely those stupid silent v's should not be shown there either, only for machines.
