### ISSUE TITLE
Enable to start the minikube 

### ISSUE THREAD

**Issue by vasanthakumars98** [kubernetes/minikube#8206]
minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278

log:
😄  minikube v1.10.1 on Ubuntu 18.04
✨  Using the none driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🤹  Running on localhost (CPUs=4, Memory=3809MB, Disk=298924MB) ...
ℹ️  OS release is Ubuntu 18.04.4 LTS
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.6 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

💣  Failed to update cluster: updating node: sudo systemctl start kubelet: exit status 1
stdout:

stderr:
Failed to start kubelet.service: Unit kubelet.service is masked.

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by priyawadhwa** [comment]
Hey @vasanthakumars98 could you trying running:
```
sudo systemctl enable kubelet
```

to try unmasking the service?

If that works, we may need to add that command back into our codebase for the None driver only (I removed it to fix a kubelet/`/etc/hosts` race condition about a week ago).

**Comment by vasanthakumars98** [comment]
hi @priyawadhwa  
using none driver is there any possible to deploy and access dashboard ?

**Comment by afbjorklund** [comment]
There is nothing special when using the "none" driver, maybe that the VM might be missing a browser.

**Comment by afbjorklund** [comment]
@priyawadhwa :
I think unit masked means that it is either symlinked to /dev/null or that the file is empty.

So it is possible that something went silently wrong, when copying these files over.

Maybe we should verify the kubelet.service, but `copyFiles` should be able to do it ?

Anyway, I dont think this has anything to do with Enable - that lives in another directory

**Comment by priyawadhwa** [comment]
Hey @vasanthakumars98 -- we don't support the dashboard command with the none driver (you can find a list of unsupported features w/ none in our docs [here](https://minikube.sigs.k8s.io/docs/drivers/none/#other)

@afbjorklund ah gotcha. I don't know much about this, so if @vasanthakumars98 could provide the output of `minikube start --alsologtostderr` it might help us see if something is going on in `copyFiles`
