### ISSUE TITLE
minikube not starting

### ISSUE THREAD

**Issue by gauravsjc02** [kubernetes/minikube#8212]
C:\Users\hp>minikube start
* minikube v1.10.1 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Could not open the medium 'C:\Users\hp\.minikube\machines\minikube\disk.vmdk'.
VBoxManage.exe: error: VMDK: inconsistency between grain table and backup grain table in 'C:\Users\hp\.minikube\machines\minikube\disk.vmdk' (VERR_VD_VMDK_INVALID_HEADER).
VBoxManage.exe: error: VD: error VERR_VD_VMDK_INVALID_HEADER opening image file 'C:\Users\hp\.minikube\machines\minikube\disk.vmdk' (VERR_VD_VMDK_INVALID_HEADER)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MediumWrap, interface IMedium

Details: 00:00:02.106367 Power up failed (vrc=VINF_SUCCESS, rc=E_FAIL (0X80004005))

**Comment by priyawadhwa** [comment]
Hey @gauravsjc02 -- I looked up the `VERR_VD_VMDK_INVALID_HEADER` error in the logs and apparently it can be related to a corrupt VM image.

Would you mind trying:

```
minikube delete
minikube start --driver virtualbox --alsologtostderr
```

and paste the output of the second command as a comment  here if that fails?

**Comment by gauravsjc02** [comment]
> Hey @gauravsjc02 -- I looked up the `VERR_VD_VMDK_INVALID_HEADER` error in the logs and apparently it can be related to a corrupt VM image.
> 
> Would you mind trying:
> 
> ```
> minikube delete
> minikube start --driver virtualbox --alsologtostderr
> ```
> 
> and paste the output of the second command as a comment here if that fails?

**Comment by gauravsjc02** [comment]
Hey @priyawadhwa , thanks for your help!!
The issue has been solved.
