### ISSUE TITLE
Minikube dashboard using none driver i can access

### ISSUE THREAD

**Issue by vasanthakumars98** [kubernetes/minikube#8218]
root@vasanth:/home/vasanth/Desktop/k8's# minikube start --driver=none
😄  minikube v1.10.1 on Ubuntu 18.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 18.04.4 LTS
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.6 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🤹  Configuring local host environment ...

❗  The 'none' driver is designed for experts who need to integrate with an existing VM
💡  Most users should use the newer 'docker' driver instead, which does not require root!
📘  For more information, see: https://minikube.sigs.k8s.io/docs/reference/drivers/none/

❗  kubectl and minikube configuration will be stored in /root
❗  To use kubectl or minikube commands as your own user, you may need to relocate them. For example, to overwrite your own settings, run:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER $HOME/.kube $HOME/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

root@vasanth:/home/vasanth/Desktop/k8's# kubectl proxy
Starting to serve on 127.0.0.1:8001

root@vasanth:/home/vasanth/Desktop/k8's# 
root@vasanth:/home/vasanth/Desktop/k8's# minikube dashboard
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
💣  http://127.0.0.1:36763/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ is not accessible: Temporary Error: unexpected response code: 503

how can i access the dashboard using none driver ?

**Comment by priyawadhwa** [comment]
Hey @vasanthakumars98 thanks for opening this issue. As mentioned in our [docs](https://minikube.sigs.k8s.io/docs/drivers/none/#other) there are some commands that the `none` driver doesn't support, including dashboard.

If you'd like to use the `dashboard` command I'd recommend switching to the `docker` driver (or any other driver that we currently support).

I'm going to close this issue as this is an unsupported feature.
