### ISSUE TITLE
minikube is exiting due to an error.

### ISSUE THREAD

**Issue by maicloudy** [kubernetes/minikube#8231]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by maicloudy** [comment]
minikube start --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --vm-driver=none --kubernetes-version='v1.18.2'

**Comment by medyagh** [comment]
@maicloudy do you mind sharing the output by adding this flag: --aslologtostderr -v=8 

```
minikube start --image-mirror-country='cn' --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers' --vm-driver=none --kubernetes-version='v1.18.2'
--aslologtostderr -v=8 
```

**Comment by medyagh** [comment]
@maicloudy are you still having this issue ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
