### ISSUE TITLE
Kubernetes upgrade suggestion duplicated

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#8232]
Like so:

😄  [test] minikube v1.10.1 on Ubuntu 18.04
✨  Using the docker driver based on existing profile
🆕  Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.2
🆕  Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.2
🆕  Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.2

It would probably be enough with one such suggestion ?

But now _every_ getKubernetesVersion() call prints it.

stack trace:
```
k8s.io/minikube/cmd/minikube/cmd.getKubernetesVersion(0xc0004adc00, 0x6, 0x7)
	./minikube/cmd/minikube/cmd/start.go:947 +0x37
k8s.io/minikube/cmd/minikube/cmd.provisionWithDriver(0x2af20e0, 0x1ac56cd, 0x6, 0x7, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	./minikube/cmd/minikube/cmd/start.go:230 +0x263
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2af20e0, 0xc0004c7c80, 0x0, 0x6)
	./minikube/cmd/minikube/cmd/start.go:157 +0x221
```

```
k8s.io/minikube/cmd/minikube/cmd.getKubernetesVersion(0xc000681b80, 0x0, 0x0)
	./minikube/cmd/minikube/cmd/start.go:947 +0x37
k8s.io/minikube/cmd/minikube/cmd.createNode(0xc0003d2180, 0x4, 0x0, 0x0, 0x0, 0xc000188460, 0x6b, 0x1f40, 0x2, 0x4e20, ...)
	./minikube/cmd/minikube/cmd/start.go:885 +0xea
k8s.io/minikube/cmd/minikube/cmd.generateClusterConfig(0x2af20e0, 0xc0004adc00, 0xc000464ba0, 0x7, 0x1ac56cd, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	./minikube/cmd/minikube/cmd/start_flags.go:352 +0x237
k8s.io/minikube/cmd/minikube/cmd.provisionWithDriver(0x2af20e0, 0x1ac56cd, 0x6, 0x7, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	./minikube/cmd/minikube/cmd/start.go:231 +0x34b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2af20e0, 0xc0004c7c80, 0x0, 0x6)
	./minikube/cmd/minikube/cmd/start.go:157 +0x221
```

```
k8s.io/minikube/cmd/minikube/cmd.getKubernetesVersion(0xc000681b80, 0xc000464d60, 0x7)
	./minikube/cmd/minikube/cmd/start.go:947 +0x37
k8s.io/minikube/cmd/minikube/cmd.createNode(0xc0003d2180, 0x4, 0x0, 0x0, 0x0, 0xc000188460, 0x6b, 0x1f40, 0x2, 0x4e20, ...)
	./minikube/cmd/minikube/cmd/start.go:894 +0x202
k8s.io/minikube/cmd/minikube/cmd.generateClusterConfig(0x2af20e0, 0xc0004adc00, 0xc000464ba0, 0x7, 0x1ac56cd, 0x6, 0x0, 0x0, 0x0, 0x0, ...)
	./minikube/cmd/minikube/cmd/start_flags.go:352 +0x237
k8s.io/minikube/cmd/minikube/cmd.provisionWithDriver(0x2af20e0, 0x1ac56cd, 0x6, 0x7, 0x101, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	./minikube/cmd/minikube/cmd/start.go:231 +0x34b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2af20e0, 0xc0004c7c80, 0x0, 0x6)
	./minikube/cmd/minikube/cmd/start.go:157 +0x221
```

**Comment by RA489** [comment]
@afbjorklund I tried to reproduce this on Ubuntu 16.04. I got only one upgrade suggestions. Is there something i missed?

😄  minikube v1.10.1 on Ubuntu 16.04
✨  Using the docker driver based on user configuration
🆕  Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.2
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v3-v1.18.0-docker-overlay2-amd64.tar.lz4: 525.45 MiB
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

**Comment by sharifelgamal** [comment]
This is fixed.
