### ISSUE TITLE
Aggressive timeout (2s) on the k8s.gcr.io access test 

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#8234]
```
I0521 12:32:59.714537   15516 ssh_runner.go:188] Completed: curl -sS -m 2 https://k8s.gcr.io/: (5.434384518s)
W0521 12:32:59.714577   15516 start.go:486] [curl -sS -m 2 https://k8s.gcr.io/] failed: curl -sS -m 2 https://k8s.gcr.io/: Process exited with status 28
stdout:

stderr:
curl: (28) Resolving timed out after 2000 milliseconds
```
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

----

Might want to allow for _slightly_ longer completions times too...
It is at least not slow enough to warrant messing with a proxy ?

```go
       // 2 second timeout. For best results, call tryRegistry in a non-blocking manner.
       opts := []string{"-sS", "-m", "2"}
```

commit b23bddb242bbcdb200164aeda81f229852334f1c

It can take longer here.

**Comment by priyawadhwa** [comment]
Hey @afbjorklund is this still something we want to do?

**Comment by afbjorklund** [comment]
Haven't seen this particular error in a while.

Maybe DNS/network was having a bad day ?

**Comment by medyagh** [comment]
haven't seen this happen  either. will close, plz reopen if needed
