### ISSUE TITLE
Automatic restart is hiding the real error

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#8235]
We get a lot of reports, that include a partial log from the restart - but nothing from the inital start.

It would be nice to improve this, to either fail on the first error or show how to report all logs ?

Typical report:

:sparkles: Using the docker driver based on existing profile
:shrug: docker "minikube" container is missing, will recreate.

* Using the virtualbox driver based on existing profile
* Restarting existing virtualbox VM for "minikube" ...

The details from the first start, that shows why it fails, is not included in the bug report or logs.

**Comment by medyagh** [comment]
I was thinking we should by default write your logs for the current start to ~/.minikube/logs.txt or something, so whenever user does not run with --aloslogtostderr we should be able to ask them just pass ~/.minikube/logs.txt

**Comment by tstromberg** [comment]
I believe this has been addressed. If someone sees this again, please re-open with an example.
