### ISSUE TITLE
add wait for API server in docker-env

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8241]
in docker-env if we restart the docker because it was failing, we should wait for apiserver to be up and running

**Comment by afbjorklund** [comment]
I don't really see what docker has to do with the apiserver, you want the raw access to the container runtime

**Comment by afbjorklund** [comment]
If docker service is down, we show a message about that. If docker service is up, we show the address.

💣  The docker service within 'minikube' is not active
