### ISSUE TITLE
hyperV exception windows datacenter

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8245]
on that windows there is no virtualswtich by default

![remmina_mini-test-3_157 55 202 113_2020516-53418 985060](https://user-images.githubusercontent.com/4564227/82614417-a5e94680-9b7c-11ea-8bba-9d2354262e12.png)

**Comment by tstromberg** [comment]
Duplicate of #2954

**Comment by sharifelgamal** [comment]
Turns out this is a duplicate of #2954
