### ISSUE TITLE
Get docker.pkg.github.com/v2/kubernetes/minikube/kicbase/mainfests/v0.0.10: no basic auth credentials

### ISSUE THREAD

**Issue by yihuibest3** [kubernetes/minikube#8247]
**Steps to reproduce the issue:** 

1.  Copy https://minikube.sigs.k8s.io/docs/start to browse
2.  Install minikube-installer.exe in window 10
3.  Start your cluster by run: minikube start

**Full output of failed command:** 
stderr:
Template parsing error: tempate: :1:8: executing "" at <.State.Status>:  map has no entry for key "State"
************
stderr:
Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/kubernetes/minikube/kicbase/mainfests/v0.0.10: no basic auth credentials

**Full output of `minikube start` command used, if not already included:**
stderr:
Unable to find image 'docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10' locally
docker: Error response from daemon: Get https://docker.pkg.github.com/v2/kubernetes/minikube/kicbase/mainfests/v0.0.10: no basic auth credentials

</details>

**Comment by afbjorklund** [comment]
This is addressed in #8192 and #8124, respectively. Sorry for the inconvenience. If in China:
Try `--base-image registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10`

**Comment by medyagh** [comment]
fixed
