### ISSUE TITLE
virtualbox on Windows Enterprise: Creating host: create host timed out in 240s

### ISSUE THREAD

**Issue by Minshu123** [kubernetes/minikube#8254]
**Steps to reproduce the issue:** 

1. * minikube v1.10.1 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Using the virtualbox driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create host timed out in 240.000000 seconds
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start virtualbox VM. "minikube start" may fix it: creating host: create host timed out in 240.000000 seconds
*
* [CREATE_TIMEOUT] error provisioning host Failed to start host: creating host: create host timed out in 240.000000 seconds
* Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software
* Related issue: https://github.com/kubernetes/minikube/issues/7072

**Full output of failed command:** 

W0523 11:26:14.802413   10308 root.go:252] Error reading config file at C:\Users\Minshu Kumar\.minikube\config\config.json: open C:\Users\Minshu Kumar\.minikube\config\config.json: The system cannot find the file specified.
I0523 11:26:14.809286   10308 start.go:99] hostinfo: {"hostname":"DESKTOP-UQBRSAM","uptime":149083,"bootTime":1590064291,"procs":199,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.17134 Build 17134","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"9ce84192-b54b-4e2b-a996-1700129a49f2"}
W0523 11:26:14.809286   10308 start.go:107] gopshost.Virtualization returned error: not implemented yet
* minikube v1.10.1 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
I0523 11:26:15.051934   10308 notify.go:125] Checking for updates...
I0523 11:26:15.060443   10308 driver.go:253] Setting default libvirt URI to qemu:///system
* Using the virtualbox driver based on existing profile
I0523 11:26:15.243953   10308 start.go:215] selected driver: virtualbox
I0523 11:26:15.245518   10308 start.go:594] validating driver "virtualbox" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.10.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.2 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0523 11:26:15.247471   10308 start.go:600] status for virtualbox: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0523 11:26:15.249423   10308 iso.go:118] acquiring lock: {Name:mk89218eceec16214e727a919a7d9e9b61d18a39 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Starting control plane node minikube in cluster minikube
I0523 11:26:15.283208   10308 preload.go:81] Checking if preload exists for k8s version v1.18.2 and runtime docker
I0523 11:26:15.284558   10308 preload.go:96] Found local preload: C:\Users\Minshu Kumar\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4
I0523 11:26:15.286511   10308 cache.go:48] Caching tarball of preloaded images
I0523 11:26:15.287681   10308 preload.go:122] Found C:\Users\Minshu Kumar\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0523 11:26:15.287681   10308 cache.go:51] Finished verifying existence of preloaded tar for  v1.18.2 on docker
I0523 11:26:15.289447   10308 profile.go:156] Saving config to C:\Users\Minshu Kumar\.minikube\profiles\minikube\config.json ...
I0523 11:26:15.293346   10308 cache.go:132] Successfully downloaded all kic artifacts
I0523 11:26:15.296271   10308 start.go:223] acquiring machines lock for minikube: {Name:mk8bc356c9a14d973f1d01b2fc2b3a38b739c48e Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0523 11:26:15.297258   10308 start.go:227] acquired machines lock for "minikube" in 765µs
I0523 11:26:15.310912   10308 start.go:87] Skipping create...Using existing machine configuration
I0523 11:26:15.312863   10308 fix.go:53] fixHost starting:
I0523 11:26:15.314816   10308 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0523 11:26:15.463935   10308 main.go:110] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="c4e68ba3-71dd-44b1-9b6f-c03b48a3a942"
CfgFile="C:\\Users\\Minshu Kumar\\.minikube\\machines\\minikube\\minikube\\minikube.vbox"
SnapFldr="C:\\Users\\Minshu Kumar\\.minikube\\machines\\minikube\\minikube\\Snapshots"
LogFldr="C:\\Users\\Minshu Kumar\\.minikube\\machines\\minikube\\minikube\\Logs"
hardwareuuid="c4e68ba3-71dd-44b1-9b6f-c03b48a3a942"
memory=2200
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2020-05-23T05:28:31.393000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\Minshu Kumar\.minikube\machines\minikube\boot2docker.iso"
"SATA-ImageUUID-0-0"="9bd62857-3342-4291-b75d-802b427f4e41"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\Minshu Kumar\.minikube\machines\minikube\disk.vmdk"
"SATA-ImageUUID-1-0"="a9766613-df9a-4338-93de-e1c878a7ae65"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800276ACC62"
cableconnected1="on"
nic1="nat"
nictype1="virtio"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,56015,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #2"
macaddress2="080027263131"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
bridgeadapter3="Intel(R) Dual Band Wireless-AC 3165"
macaddress3="080027F17D1F"
cableconnected3="on"
nic3="bridged"
nictype3="82540EM"
nicspeed3="0"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="dsound"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="\\\\?\\c:\\Users"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens="0"
capturefilename="C:\\Users\\Minshu Kumar\\.minikube\\machines\\minikube\\minikube\\minikube.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.2.32 r132056"
GuestAdditionsFacility_VirtualBox Base Driver=50,1590211736945
GuestAdditionsFacility_VirtualBox System Service=50,1590211737460
GuestAdditionsFacility_Seamless Mode=0,1590211738062
GuestAdditionsFacility_Graphics Mode=0,1590211736945
}
I0523 11:26:15.464879   10308 main.go:110] libmachine: STDERR:
{
}
I0523 11:26:15.468823   10308 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0523 11:26:15.469831   10308 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running virtualbox "minikube" VM ...
I0523 11:26:15.530429   10308 machine.go:86] provisioning docker machine ...
I0523 11:26:15.531250   10308 buildroot.go:163] provisioning hostname "minikube"
I0523 11:26:15.535176   10308 main.go:110] libmachine: SSH binary not found, using native Go implementation
I0523 11:26:15.535501   10308 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x7c0950] 0x7c0920 <nil>  [] 0s} 127.0.0.1 22 <nil> <nil>}
I0523 11:26:15.536126   10308 main.go:110] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0523 11:26:16.538481   10308 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.
I0523 11:26:20.540477   10308 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
.

</details>

**Comment by Minshu123** [comment]
I don't have any vpn and firewall software other than windows defender I'm using virtualbox as hypervisor.

**Comment by tstromberg** [comment]
Do you mind trying  `minikube delete` to see if it fixes the issue?

**Comment by tstromberg** [comment]
I've looked through the logs and nothing stands out. I'll see if I can replicate this on my own Windows machine, but in the mean time, I suggest trying minikube with either the Docker or Hyper-V driver on this machine.

**Comment by sharifelgamal** [comment]
@Minshu123 Have you tried using the Hyper-V or Docker drivers?

**Comment by sharifelgamal** [comment]
Hey @Minshu123  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!
