### ISSUE TITLE
[help] how expose kubernetes API with ec2 public ip

### ISSUE THREAD

**Issue by nitishvu** [kubernetes/minikube#8258]
**Steps to reproduce the issue:** 
I have installed minikube in ec2 instance with --driver=docker
now I want to access this cluster with kubectl from a public network.
can you please let me know how can we do this?

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
This sounds more like a regular kubernetes deployment than minikube, but similar to #8253

If you are going to deploy a public kubernetes, you probably need to look beyond minikube

**Comment by tstromberg** [comment]
I would recommend SSH port forwarding.
