### ISSUE TITLE
minikube crushed

### ISSUE THREAD

**Issue by mayukh1** [kubernetes/minikube#8277]
**Steps to reproduce the issue:** 

1.Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by RA489** [comment]
@mayukh1 I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

The exact minikube start command line used

The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

The full output of minikube logs

The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by tstromberg** [comment]
This is fixed by upgrading to a recent release of minikube (any from 2020 should be fine). Please comment with `/reopen` if the latest version does not fix your issue.

**Comment by mayukh1** [comment]
Start minikube with vm-driver=none:
sudo minikube start --vm-driver=none
Here is an issue: root privileges are required to use minikube and kubectl (‘minikube start’ command outputs “When using the none driver, the kubectl config and credentials generated will be root owned and will appear in the root home directory”). To fix it run:
export CHANGE_MINIKUBE_NONE_USER=true
sudo -E minikube start --vm-driver=none
Let’s make the fix persistent so it will apply on system bootload:
echo ‘export CHANGE_MINIKUBE_NONE_USER=true’ >> ~/.bashrc
Check that everything works properly:
kubectl cluster-info

solve my problem
