### ISSUE TITLE
Minikube update wipes the cluster state

### ISSUE THREAD

**Issue by krezovic** [kubernetes/minikube#8282]
I have performed the update of minikube executable from 1.9.0 to 1.10.1 recently, and it notified about a new kubernetes version (1.18.2) when starting. I started the upgrade to 1.18.2 using --kubernetes-version, which completed successfully. But, all my deployments, pods and everything that's not part of minikube or minikube addons was gone. What did I do wrong? Let me know If you need more info.

Host: Debian 10 (virtual machine)
Docker: 19.03.8
minikube driver: none

Similar thing happened for my local minikube installation on ArchLinux/docker-machine-driver-kvm2 

My command was simply "minikube start --kubernetes-version=v1.18.2".

I had used "minikube config" before, with an older version, to set memory (4G), cpus (2) and disk space (20G) for KVM virtual machine, not sure if they affect none driver.

**Comment by tstromberg** [comment]
Do you know what Kubernetes version you upgraded from? This is certainly not intentional, and is behavior we explicitly integration test for. 

I was not able to replicate it using:

* `minikube start --kubernetes-version=v1.16.0`
* `minikube addons enable dashboard`
* `minikube start --kubernetes-version=v1.18.2`

**Comment by krezovic** [comment]
Hi, it was version 1.17.3 or something in 1.17.x range.

I did mention that all addons persisted, but nothing that was deployed as custom. I just verified it using minikube 1.10.1 executable, starting with 1.17.3, deploying nginx, shutting it down, restarting it with 1.18.2 upgrade. It did persist. This was done on kvm2 machine using kvm2 driver.

The original problem happened on none target, to which I don't have access to at the moment. I need to do an upgrade from another 1.17.x installation of minikube on another of our dev machines in the next days, so I'll report back.

**Comment by krezovic** [comment]
I did the upgrade today, and it went smoothly on a VM and minikube started with --driver=none. I don't know why it failed before. I do remember there was an issue in one minikube version where you couldn't start a minikube instance created with an earlier version. That could well be the problem I hit, but this issue has long been fixed. Closing.
