### ISSUE TITLE
mkdir /home/dw/.minikube/profiles/minikube: permission denied

### ISSUE THREAD

**Issue by Balakrishna625** [kubernetes/minikube#8286]
everytime i run minikube start i am facing this errors

😄  minikube v1.10.1 on Ubuntu 18.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.2 preload ...
❗  Startup with docker driver failed, trying with alternate driver virtualbox: Failed to save config: mkdir /home/dw/.minikube/profiles/minikube: permission denied
❗  Failed to delete cluster minikube, proceeding with retry anyway.
💿  Downloading VM boot image ...
E0527 17:49:22.821411   21430 cache.go:63] save image to file "k8s.gcr.io/kube-scheduler:v1.18.2" -> "/home/dw/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.18.2" failed: making cache image directory: /home/dw/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.18.2: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.821403   21430 cache.go:63] save image to file "kubernetesui/metrics-scraper:v1.0.2" -> "/home/dw/.minikube/cache/images/kubernetesui/metrics-scraper_v1.0.2" failed: making cache image directory: /home/dw/.minikube/cache/images/kubernetesui/metrics-scraper_v1.0.2: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.822461   21430 cache.go:63] save image to file "k8s.gcr.io/etcd:3.4.3-0" -> "/home/dw/.minikube/cache/images/k8s.gcr.io/etcd_3.4.3-0" failed: making cache image directory: /home/dw/.minikube/cache/images/k8s.gcr.io/etcd_3.4.3-0: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.824023   21430 cache.go:63] save image to file "k8s.gcr.io/kube-apiserver:v1.18.2" -> "/home/dw/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.18.2" failed: making cache image directory: /home/dw/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.18.2: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.824310   21430 cache.go:63] save image to file "k8s.gcr.io/kube-controller-manager:v1.18.2" -> "/home/dw/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.18.2" failed: making cache image directory: /home/dw/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.18.2: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.824767   21430 cache.go:63] save image to file "k8s.gcr.io/pause:3.2" -> "/home/dw/.minikube/cache/images/k8s.gcr.io/pause_3.2" failed: making cache image directory: /home/dw/.minikube/cache/images/k8s.gcr.io/pause_3.2: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.822505   21430 cache.go:63] save image to file "gcr.io/k8s-minikube/storage-provisioner:v1.8.1" -> "/home/dw/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1" failed: making cache image directory: /home/dw/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.825100   21430 cache.go:63] save image to file "k8s.gcr.io/kube-proxy:v1.18.2" -> "/home/dw/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.18.2" failed: making cache image directory: /home/dw/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.18.2: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.824659   21430 cache.go:63] save image to file "kubernetesui/dashboard:v2.0.0" -> "/home/dw/.minikube/cache/images/kubernetesui/dashboard_v2.0.0" failed: making cache image directory: /home/dw/.minikube/cache/images/kubernetesui/dashboard_v2.0.0: mkdir /home/dw/.minikube/cache/images: permission denied
E0527 17:49:22.824718   21430 cache.go:63] save image to file "k8s.gcr.io/coredns:1.6.7" -> "/home/dw/.minikube/cache/images/k8s.gcr.io/coredns_1.6.7" failed: making cache image directory: /home/dw/.minikube/cache/images/k8s.gcr.io/coredns_1.6.7: mkdir /home/dw/.minikube/cache/images: permission denied
    > minikube-v1.10.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
E0527 17:49:23.333227   21430 iso.go:86] Unable to download https://storage.googleapis.com/minikube/iso/minikube-v1.10.0.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.10.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.10.0.iso.sha256 Dst:/home/dw/.minikube/cache/iso/minikube-v1.10.0.iso.download Pwd: Mode:2 Detectors:[0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8] Decompressors:map[bz2:0x2b1f5f8 gz:0x2b1f5f8 tar.bz2:0x2b1f5f8 tar.gz:0x2b1f5f8 tar.xz:0x2b1f5f8 tbz2:0x2b1f5f8 tgz:0x2b1f5f8 txz:0x2b1f5f8 xz:0x2b1f5f8 zip:0x2b1f5f8] Getters:map[file:0xc00043e000 http:0xc00018a040 https:0xc00018a060] Dir:false ProgressListener:0x2af7dc0 Options:[0xc1e140]}: open /home/dw/.minikube/cache/iso/minikube-v1.10.0.iso.download: permission denied
💿  Downloading VM boot image ...
    > minikube-v1.10.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
E0527 17:49:26.038055   21430 iso.go:86] Unable to download https://github.com/kubernetes/minikube/releases/download/v1.10.0/minikube-v1.10.0.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.10.0/minikube-v1.10.0.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.10.0/minikube-v1.10.0.iso.sha256 Dst:/home/dw/.minikube/cache/iso/minikube-v1.10.0.iso.download Pwd: Mode:2 Detectors:[0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8] Decompressors:map[bz2:0x2b1f5f8 gz:0x2b1f5f8 tar.bz2:0x2b1f5f8 tar.gz:0x2b1f5f8 tar.xz:0x2b1f5f8 tbz2:0x2b1f5f8 tgz:0x2b1f5f8 txz:0x2b1f5f8 xz:0x2b1f5f8 zip:0x2b1f5f8] Getters:map[file:0xc000198060 http:0xc0002e0be0 https:0xc0002e0c00] Dir:false ProgressListener:0x2af7dc0 Options:[0xc1e140]}: open /home/dw/.minikube/cache/iso/minikube-v1.10.0.iso.download: permission denied
💿  Downloading VM boot image ...
    > minikube-v1.10.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
E0527 17:49:28.837639   21430 iso.go:86] Unable to download https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.10.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.10.0.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.10.0.iso.sha256 Dst:/home/dw/.minikube/cache/iso/minikube-v1.10.0.iso.download Pwd: Mode:2 Detectors:[0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8 0x2b1f5f8] Decompressors:map[bz2:0x2b1f5f8 gz:0x2b1f5f8 tar.bz2:0x2b1f5f8 tar.gz:0x2b1f5f8 tar.xz:0x2b1f5f8 tbz2:0x2b1f5f8 tgz:0x2b1f5f8 txz:0x2b1f5f8 xz:0x2b1f5f8 zip:0x2b1f5f8] Getters:map[file:0xc000198500 http:0xc0002e0e20 https:0xc0002e0e40] Dir:false ProgressListener:0x2af7dc0 Options:[0xc1e140]}: open /home/dw/.minikube/cache/iso/minikube-v1.10.0.iso.download: permission denied

💣  error provisioning host: Failed to save config: mkdir /home/dw/.minikube/profiles/minikube: permission denied

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
It seems like your user does not have permissions to the minikube state directory. Can you share the output of:

* `id`
* `stat /home/dw/.minikube`
* `touch /home/dw/.minikube/test`

Thanks!

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
