### ISSUE TITLE
VT-x is disabled in the BIOS for all CPU modes -> Unable to find a default driver

### ISSUE THREAD

**Issue by fella752** [kubernetes/minikube#8292]
**Steps to reproduce the issue:** 

1.I have run minikube start command
Getting error that is attached
![P_20200528_105352](https://user-images.githubusercontent.com/59953408/83102318-d0ce2000-a0d1-11ea-97a7-788dec68de6b.jpg)

2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by fella752** [comment]
![P_20200528_203627](https://user-images.githubusercontent.com/59953408/83158870-f59eb380-a122-11ea-8e9a-5c9f9f28265f.jpg)
Now I am getting this

**Comment by RA489** [comment]
os/windows

**Comment by tstromberg** [comment]
Please enable virtualization in your BIOS to make this work. Look at your HP laptop manual for details on how to do so. That said, we don't provide the easy error message that we should be here. 

For the latter error message, could you share the output of: `VBoxManage list hostinfo`

**Comment by medyagh** [comment]
@fella752 

Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by fella752** [comment]
Hi Team,
HyperV is enabled still getting the error to start minikube
![15944868149264400518819304529492](https://user-images.githubusercontent.com/59953408/87229508-1fa3f080-c3c6-11ea-9d79-85e590c04b9a.jpg)
![159448691737252039018218014089](https://user-images.githubusercontent.com/59953408/87229536-5c6fe780-c3c6-11ea-903e-3382d26fe3a2.jpg)
