### ISSUE TITLE
Package/install/link in kubectl code

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#83]
If users don't have kubectl on their path we should offer to install it somehow. We could link it into the minikube binary like monokube does or use an official build.

**Comment by luxas** [comment]
Maybe it's better to download an official build of `kubectl` to `/usr/local/bin/` if they don't have a version of `kubectl` that's supported (or not at all)

**Comment by luxas** [comment]
We should at least link the `kubectl proxy` command, so we're able to run the apiserver proxy to `localhost` in a goroutine in `minikube`

**Comment by dlorenc** [comment]
Releases are available here: https://coreos.com/kubernetes/docs/latest/configure-kubectl.html

**Comment by r2d4** [comment]
Closing as we've decided not to package kubectl, but we will link it in installers when they are ready
