### ISSUE TITLE
--help: bool flags which default to 'false' yield confusing output

### ISSUE THREAD

**Issue by mazzystr** [kubernetes/minikube#8301]
**Steps to reproduce the issue:** 

1.  minikube service --help
2. Take notice of `options: --https=false`.  The description of this option doesn't make sense.  If `--https` is a bool then the wording and pertaining function should read `--https=false: Open the service URL with http instead of https` 

**Full output of failed command:** 
```
$ minikube service --help
Returns the Kubernetes URL for a service in your local cluster. In the case of multiple URLs they will be printed one at
a time.

Available Commands:
  list        Lists the URLs for the services in your local cluster

Options:
      --https=false: Open the service URL with https instead of http
      --interval=1: The initial time interval for each check that wait performs in seconds
  -n, --namespace='default': The service namespace
      --url=false: Display the Kubernetes service URL in the CLI instead of opening it in the default browser
      --wait=2: Amount of time to wait for a service in seconds

Usage:
  minikube service [flags] SERVICE [options]

Use "minikube <command> --help" for more information about a given command.
Use "minikube options" for a list of global command-line options (applies to all commands).
```

**Comment by tstromberg** [comment]
I think this is due in part to Cobra -- it's showing the default value (`false`) for a bool flag (`https`).

Ideally it would say:

`--https: Open the service URL with https instead of http (defaults to "false")`

**Comment by mazzystr** [comment]
Nothing worse than Cobra's and I ain't talking about the Shelby Cobra's!  Ok, bad dad joke. ;-)

I'd be good with that update

**Comment by medyagh** [comment]
I would be happy to review a PR that updates the Help text for this flag. to the one suggested here https://github.com/kubernetes/minikube/issues/8301#issuecomment-635582825

**Comment by Xcalizorz** [comment]
I believe this can be closed now. See https://github.com/kubernetes/minikube/pull/8904
