### ISSUE TITLE
Docker Machine unable to connect if VirtualBox host only interface exists from previous run

### ISSUE THREAD

**Issue by mortenlj** [kubernetes/minikube#831]
**Is this a BUG REPORT or FEATURE REQUEST?** BUG REPORT

**Minikube version** v0.12.2

**Environment**:
- **OS** Funtoo Linux, with 4.4.21 kernel
- **VM Driver** VirtualBox
- **Docker version** Docker version 1.11.0, build 4dc5990
- **Install tools**: None, downloaded binary manually
- **Others**:

**What happened**:
After a successful use, the next time I start minikube, it fails to connect to the machine.

**What you expected to happen**:
I expect `minikube start` to start a working VM with kubernetes every time, not just the first time.

**How to reproduce it** (as minimally and precisely as possible):
I'll add a full log below, but essentially:

    $ minikube start
    $ minikube stop
    $ minikube delete
    $ minikube start

**Anything else do we need to know**:

I started experiencing this after upgrading to v0.12.2. Unfortunately, I don't remember exactly which version I was on before, except that I'm fairly certain it was v0.11.something.

**Complete log**
    
    $ minikube --logtostderr --show-libmachine-logs start
    W1121 12:50:17.330558    9492 root.go:134] Error reading config file at /home/fimojoha/.minikube/config/config.json: open /home/fimojoha/.minikube/config/config.json: no such file or directory
    I1121 12:50:17.330920    9492 notify.go:111] Checking for updates...
    Starting local Kubernetes cluster...
    Downloading Minikube ISO
     36.00 MB / 36.00 MB [==============================================] 100.00% 0s
    Creating CA: /home/fimojoha/.minikube/certs/ca.pem
    Creating client certificate: /home/fimojoha/.minikube/certs/cert.pem
    Running pre-create checks...
    (minikube) You are using version 4.3.38_Gentoor106717 of VirtualBox. If you encounter issues, you might want to upgrade to version 5 at https://www.virtualbox.org
    Creating machine...
    (minikube) Downloading /home/fimojoha/.minikube/cache/boot2docker.iso from file:///home/fimojoha/.minikube/cache/iso/minikube-0.7.iso...
    (minikube) Creating VirtualBox VM...
    (minikube) Creating SSH key...
    (minikube) Starting the VM...
    (minikube) Check network to re-create if needed...
    (minikube) Found a new host-only adapter: "vboxnet0"
    (minikube) Waiting for an IP...
    Waiting for machine to be running, this may take a few minutes...
    Detecting operating system of created instance...
    Waiting for SSH to be available...
    Detecting the provisioner...
    Provisioning with boot2docker...
    Copying certs to the local machine directory...
    Copying certs to the remote machine...
    Setting Docker configuration on the remote daemon...
    Checking connection to Docker...
    Docker is up and running!
    I1121 12:51:36.289676    9492 cluster.go:273] Setting up certificates for IP: %s 192.168.99.100
    I1121 12:51:36.720040    9492 cluster.go:210] sudo killall localkube || true
    I1121 12:51:36.879592    9492 cluster.go:212] killall: localkube: no process killed
    
    I1121 12:51:36.879616    9492 cluster.go:210] 
    # Run with nohup so it stays up. Redirect logs to useful places.
    sudo sh -c 'PATH=/usr/local/sbin:$PATH nohup /usr/local/bin/localkube   \
    --generate-certs=false --logtostderr=true --enable-dns=false --node-ip=192.168.99.100 > /var/lib/localkube/localkube.out 2> /var/lib/localkube/localkube.err < /dev/null & echo $! > /var/run/localkube.pid &'
    
    I1121 12:51:37.034401    9492 cluster.go:212] 
    I1121 12:51:37.301599    9492 start.go:166] Using kubeconfig:  /home/fimojoha/.kube/config
    Kubectl is now configured to use the cluster.

    $ kubectl cluster-info
    Kubernetes master is running at https://192.168.99.100:8443
    KubeDNS is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kube-dns
    kubernetes-dashboard is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
    
    To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
    
    $ minikube --logtostderr --show-libmachine-logs stop
    W1121 12:52:34.699852   10479 root.go:134] Error reading config file at /home/fimojoha/.minikube/config/config.json: open /home/fimojoha/.minikube/config/config.json: no such file or directory
    I1121 12:52:34.700006   10479 notify.go:111] Checking for updates...
    Stopping local Kubernetes cluster...
    Stopping "minikube"...
    Machine "minikube" was stopped.
    Machine stopped.
    
    $ minikube --logtostderr --show-libmachine-logs delete
    W1121 12:52:56.027217   10824 root.go:134] Error reading config file at /home/fimojoha/.minikube/config/config.json: open /home/fimojoha/.minikube/config/config.json: no such file or directory
    I1121 12:52:56.027384   10824 notify.go:111] Checking for updates...
    Deleting local Kubernetes cluster...
    Machine deleted.
    
    $ minikube --logtostderr --show-libmachine-logs start
    W1121 12:53:01.377810   10904 root.go:134] Error reading config file at /home/fimojoha/.minikube/config/config.json: open /home/fimojoha/.minikube/config/config.json: no such file or directory
    I1121 12:53:01.377973   10904 notify.go:111] Checking for updates...
    Starting local Kubernetes cluster...
    Running pre-create checks...
    (minikube) You are using version 4.3.38_Gentoor106717 of VirtualBox. If you encounter issues, you might want to upgrade to version 5 at https://www.virtualbox.org
    Creating machine...
    (minikube) Downloading /home/fimojoha/.minikube/cache/boot2docker.iso from file:///home/fimojoha/.minikube/cache/iso/minikube-0.7.iso...
    (minikube) Creating VirtualBox VM...
    (minikube) Creating SSH key...
    (minikube) Starting the VM...
    (minikube) Check network to re-create if needed...
    (minikube) Waiting for an IP...
    Waiting for machine to be running, this may take a few minutes...
    Detecting operating system of created instance...
    Waiting for SSH to be available...
    Detecting the provisioner...
    Provisioning with boot2docker...
    Copying certs to the local machine directory...
    Copying certs to the remote machine...
    Setting Docker configuration on the remote daemon...
    
    This machine has been allocated an IP address, but Docker Machine could not
    reach it successfully.
    
    SSH for the machine should still work, but connecting to exposed ports, such as
    the Docker daemon port (usually <ip>:2376), may not work properly.
    
    You may need to add the route manually, or use another related workaround.
    
    This could be due to a VPN, proxy, or host file configuration issue.
    
    You also might want to clear any VirtualBox host only interfaces you are not using.
    Checking connection to Docker...
    E1121 12:54:13.802408   10904 start.go:92] Error starting host: Error creating host: Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
    You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
    Be advised that this will trigger a Docker daemon restart which might stop running containers.
    . Retrying.
    E1121 12:54:13.802473   10904 start.go:98] Error starting host:  Error creating host: Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
    You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
    Be advised that this will trigger a Docker daemon restart which might stop running containers.
    
    ================================================================================
    An error has occurred. Would you like to opt in to sending anonymized crash
    information to minikube to help prevent future errors?
    To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
    ================================================================================
    Please enter your response [Y/n]: 
    n
    
    $ VBoxManage list hostonlyifs
    Name:            vboxnet0
    GUID:            786f6276-656e-4074-8000-0a0027000000
    DHCP:            Disabled
    IPAddress:       192.168.99.1
    NetworkMask:     255.255.255.0
    IPV6Address:     fe80:0000:0000:0000:0800:27ff:fe00:0000
    IPV6NetworkMaskPrefixLength: 64
    HardwareAddress: 0a:00:27:00:00:00
    MediumType:      Ethernet
    Status:          Up
    VBoxNetworkName: HostInterfaceNetworking-vboxnet0
    
    
    $ kubectl cluster-info
    The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?
    
    $ minikube --logtostderr --show-libmachine-logs status
    W1121 12:55:43.234744   11941 root.go:134] Error reading config file at /home/fimojoha/.minikube/config/config.json: open /home/fimojoha/.minikube/config/config.json: no such file or directory
    I1121 12:55:43.234889   11941 notify.go:111] Checking for updates...
    E1121 12:55:43.563607   11941 status.go:57] Error getting machine status: Error: Unrecognize output from GetLocalkubeStatus: cat: can't open '/var/run/localkube.pid': No such file or directory
    Running
    ================================================================================
    An error has occurred. Would you like to opt in to sending anonymized crash
    information to minikube to help prevent future errors?
    To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
    ================================================================================
    Please enter your response [Y/n]: 
    n
    
    $ minikube --logtostderr --show-libmachine-logs delete
    W1121 12:56:30.395454   12021 root.go:134] Error reading config file at /home/fimojoha/.minikube/config/config.json: open /home/fimojoha/.minikube/config/config.json: no such file or directory
    I1121 12:56:30.395601   12021 notify.go:111] Checking for updates...
    Deleting local Kubernetes cluster...
    Machine deleted.
    
    $ VBoxManage hostonlyif remove vboxnet0
    0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    
    $ minikube --logtostderr --show-libmachine-logs start
    W1121 12:56:51.505856   12233 root.go:134] Error reading config file at /home/fimojoha/.minikube/config/config.json: open /home/fimojoha/.minikube/config/config.json: no such file or directory
    I1121 12:56:51.506007   12233 notify.go:111] Checking for updates...
    Starting local Kubernetes cluster...
    Running pre-create checks...
    (minikube) You are using version 4.3.38_Gentoor106717 of VirtualBox. If you encounter issues, you might want to upgrade to version 5 at https://www.virtualbox.org
    Creating machine...
    (minikube) Downloading /home/fimojoha/.minikube/cache/boot2docker.iso from file:///home/fimojoha/.minikube/cache/iso/minikube-0.7.iso...
    (minikube) Creating VirtualBox VM...
    (minikube) Creating SSH key...
    (minikube) Starting the VM...
    (minikube) Check network to re-create if needed...
    (minikube) Found a new host-only adapter: "vboxnet0"
    (minikube) Waiting for an IP...
    Waiting for machine to be running, this may take a few minutes...
    Detecting operating system of created instance...
    Waiting for SSH to be available...
    Detecting the provisioner...
    Provisioning with boot2docker...
    Copying certs to the local machine directory...
    Copying certs to the remote machine...
    Setting Docker configuration on the remote daemon...
    Checking connection to Docker...
    Docker is up and running!
    I1121 12:58:20.587754   12233 cluster.go:273] Setting up certificates for IP: %s 192.168.99.100
    I1121 12:58:20.700045   12233 cluster.go:210] sudo killall localkube || true
    I1121 12:58:20.851595   12233 cluster.go:212] killall: localkube: no process killed
    
    I1121 12:58:20.851616   12233 cluster.go:210] 
    # Run with nohup so it stays up. Redirect logs to useful places.
    sudo sh -c 'PATH=/usr/local/sbin:$PATH nohup /usr/local/bin/localkube   \
    --generate-certs=false --logtostderr=true --enable-dns=false --node-ip=192.168.99.100 > /var/lib/localkube/localkube.out 2> /var/lib/localkube/localkube.err < /dev/null & echo $! > /var/run/localkube.pid &'
    
    I1121 12:58:20.961885   12233 cluster.go:212] 
    I1121 12:58:21.251546   12233 start.go:166] Using kubeconfig:  /home/fimojoha/.kube/config
    Kubectl is now configured to use the cluster.
    
    $ VBoxManage list hostonlyifs
    Name:            vboxnet0
    GUID:            786f6276-656e-4074-8000-0a0027000000
    DHCP:            Disabled
    IPAddress:       192.168.99.1
    NetworkMask:     255.255.255.0
    IPV6Address:     fe80:0000:0000:0000:0800:27ff:fe00:0000
    IPV6NetworkMaskPrefixLength: 64
    HardwareAddress: 0a:00:27:00:00:00
    MediumType:      Ethernet
    Status:          Up
    VBoxNetworkName: HostInterfaceNetworking-vboxnet0
    
    
    $ kubectl cluster-info
    Kubernetes master is running at https://192.168.99.100:8443
    KubeDNS is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kube-dns
    kubernetes-dashboard is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
    
    To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.

**Comment by r2d4** [comment]
Hey thanks for the detailed bug report.  I actually think that this is unrelated to the hostonlyifs.  docker-machine previously had a some trouble with many vboxnetX interfaces being made but I believe those are since resolved.

```
This machine has been allocated an IP address, but Docker Machine could not
reach it successfully.
```
This message indicates that the code timed out while trying to dial the docker daemon.  This was due to a bug where we weren't waiting long enough and weren't retrying while the docker daemon was starting up.

I believe that this commit (which hasn't been merged yet) fixes this issue.  

https://github.com/kubernetes/minikube/pull/820/commits/eec10be52a0f1e29113b3a15b4146c904a9f09fe

In the meantime, you should be able to do one additional `minikube start` if you run into this issue.

**Comment by mortenlj** [comment]
I've tried a couple times now, and while *one* additional `minikube start` usually isn't enough, if I do a few more, eventually it will work. So you're probably right that this is the issue you are thinking about, in which case I guess it will be fixed in the next version. :+1:
