### ISSUE TITLE
Access resources on host

### ISSUE THREAD

**Issue by pvanderlinden** [kubernetes/minikube#8313]
I followed the guidelines in:
- https://github.com/kubernetes/minikube/issues/2735
- https://minikube.sigs.k8s.io/docs/handbook/host-access/
None of those work anymore when running in docker (the default now).

**Comment by pvanderlinden** [comment]
After applying this in the running docker container and restarting the ssh daemon I could access the resource: https://github.com/kubernetes/minikube/pull/4338

**Comment by afbjorklund** [comment]
@pvanderlinden : does using `host.docker.internal` work ?

**Comment by pvanderlinden** [comment]
@afbjorklund not sure how you want to use that from kubernetes. And wouldn't that go to the docker inside the docker container which is minikube?

**Comment by tstromberg** [comment]
The old doc should still be accurate, though you are correct - it never covered the Docker driver.

There is a new method that is designed to work reliably across drivers: `host.minikube.internal`. Please let me know if using that host name fixes your issue. I've sent a PR to update the docs accordingly.

**Comment by afbjorklund** [comment]
> @afbjorklund not sure how you want to use that from kubernetes. And wouldn't that go to the docker inside the docker container which is minikube?

Ah, my bad. I was confusing the two host names - don't really run Docker Desktop myself

**Comment by pvanderlinden** [comment]
I understand what the confusion is now.
- the method in the doc didn't really point to the correct ip
- which let me to believe, I had to use the method in the doc (which is to forward the port of the host with ssh into minikube)
- that didn't work, because the docker image for minikube doesn't have Gateway ports enabled like in this PR: https://github.com/kubernetes/minikube/pull/4338

but this method works without the manual ssh tunnel, by grabbing the ip from /etc/hosts in minikube, then use that in your pod (or use a kubernetes service).
