### ISSUE TITLE
Minikube cluster?

### ISSUE THREAD

**Issue by vinhdiesal** [kubernetes/minikube#8318]
I just have a special inquiry request. 
I'm trying to create a kubernetes cluster which includes just two machines so I can try out distributed machine learning between the two machines by using DASK with sci-kit learn. 
The machines I have are a IMAC with Mojave and Razer with Ubuntu 20.04. 
My question is, is there a way to install minikube on both machines and create a local kluster so I can try out Kubeflow to deploy machine learning pipelines between the two machines?

**Comment by tstromberg** [comment]
minikube can be installed on both hosts - https://minikube.sigs.k8s.io/docs/start/

While minikube supports multi-node, we unfortunately do not yet support multi-node across hosts. You could probably hack something together using SSH tunneling and `kubeadm join`, but I suspect that it will be exceedingly painful to do so.

I would suggest looking into http://microk8s.io/ - which has some support for what you are trying to do here.
