### ISSUE TITLE
hyperv: missing test output in powershell Out-File -FilePath

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8322]
in hyperv test the output file does not have the output in order:
and some output is missing form the output file 'testout.txt'

when running manually I noticed sometimes in powershell the output is delayed.

```
.\e2e-windows-amd64.exe --minikube-start-args="--driver=hyperv" --test.timeout=16m --timeout-multiplier=3 --test.v --test.run="TestFunctional" --binary="./minikube-windows-amd64.exe"  2>&1 | Out-File -FilePath .\report\testout.txt -Encoding ASCII

```

https://github.com/kubernetes/minikube/blob/21b7cebaf9997e729dd27d122c092d4f4b720270/.github/workflows/pr.yml#L312

maybe related ? 
- https://stackoverflow.com/questions/34835327/unable-to-pause-or-sleep-after-select-object

- https://stackoverflow.com/questions/53009706/output-of-powershell-script-displaying-incorrectly

**Comment by tstromberg** [comment]
Is there an example you could provide for more details?

**Comment by medyagh** [comment]
@tstromberg
sorry for lack of description in the issue, was meant to come back and fill it up.

so any last job on master in github actions if you click on hyperv test and then click on "end result"
you will see only 1 test reporting. while all tests really ran.


https://github.com/kubernetes/minikube/runs/722007237?check_suite_focus=true

I believe this is a problem with windows powershell delayed output
