### ISSUE TITLE
ingress can't start because secret "ingress-nginx-admission" not found

### ISSUE THREAD

**Issue by minh-thai** [kubernetes/minikube#8332]
**Steps to reproduce the issue:** 

1. Run command: minikube delete then minikube start
2. Enable ingress by command: minikube addons enable ingress, then restart minikube
3. Get pod information: kubectl get pods -n kube-system
4. Observer that ingress-nginx-admission-create-6nrdj, ingress-nginx-admission-patch-d9ggc and ingress-nginx-controller-7bb4c67d67-z6p8l can't start properly

I see this error by running: minikube logs

May 30 09:28:20 minikube kubelet[2242]: E0530 09:28:20.639642    2242 secret.go:195] Couldn't get secret kube-system/ingress-nginx-admission: secret "ingress-nginx-admission" not found
May 30 09:28:20 minikube kubelet[2242]: E0530 09:28:20.640363    2242 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/secret/ae37633a-df13-4e0f-89ae-999c55699487-webhook-cert podName:ae37633a-df13-4e0f-89ae-999c55699487 nodeName:}" failed. No retries permitted until 2020-05-30 09:30:22.640339649 +0000 UTC m=+752.515736438 (durationBeforeRetry 2m2s). Error: "MountVolume.SetUp failed for volume \"webhook-cert\" (UniqueName: \"kubernetes.io/secret/ae37633a-df13-4e0f-89ae-999c55699487-webhook-cert\") pod \"ingress-nginx-controller-7bb4c67d67-z6p8l\" (UID: \"ae37633a-df13-4e0f-89ae-999c55699487\") : secret \"ingress-nginx-admission\" not found"

I tried to list all secrets in namespace kube-system and saw the following 2 rows:
ingress-nginx-admission-token-wpwqt              kubernetes.io/service-account-token   3      37m
ingress-nginx-token-bqkqh                        kubernetes.io/service-account-token   3      37m

Version infos are as follows:
minikube version: v1.11.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

Anyone know how to fix that?

**Comment by minh-thai** [comment]
I deleted all ingress related resources in K8S then created them again. And everything works now, so I close the ticket.

**Comment by bradwood** [comment]
I have this same problem, but that seems like rather an extreme solution...

**Comment by newtoniumx3** [comment]
Same problem

**Comment by JulienBreux** [comment]
Same problem

**Comment by medyagh** [comment]
@JulienBreux 
@bradwood
@minh-thai 

I noticed you are using an old version of minikube we fixed an ingress bug in v1.20.0 do u mind trying again and see if this still happens?

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by philippemiron** [comment]
Hi everyone, I add the same issue, and I think it was related to the certificate not being set correctly initially when I tried to activate the ingress controller. 

I retry by first deleting the cluster:
```
minikube delete
```
then copying the cert.pem to `~/.minikube/certs/` and doing:
```
minikube start --embed-certs
minikube addon enable ingress
```
which did complete correctly. I'm not sure if there is a way to avoid having to delete the full cluster in that situation but maybe it can help someone.
