### ISSUE TITLE
Unable to start minikube on ubuntu 18.04

### ISSUE THREAD

**Issue by Mishraom99** [kubernetes/minikube#8338]
**Steps to reproduce the issue:** 

1.minikube start 
2. minikube v1.11.0 on Ubuntu 18.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🤦  StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
🏃  Updating the running docker "minikube" container ...
😿  Failed to start docker container. "minikube start" may fix it: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

💣  error provisioning host: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
We need some more logs, in order to see what happened here. Can you try with `--alsologtostderr`

Or run the docker command directly, on the container:

`docker container inspect --format "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube`

It normally returns something simple like `172.17.0.4,`

**Comment by Mishraom99** [comment]
The o/p of the first command :

✨  Using the docker driver based on existing profile
I0531 17:39:01.868105    4971 start.go:214] selected driver: docker
I0531 17:39:01.868153    4971 start.go:611] validating driver "docker" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[{Component:kubeadm Key:pod-network-cidr Value:10.244.0.0/16}] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0531 17:39:01.868344    4971 start.go:617] status for docker: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0531 17:39:01.868403    4971 start.go:935] auto setting extra-config to "kubeadm.pod-network-cidr=10.244.0.0/16".
👍  Starting control plane node minikube in cluster minikube
I0531 17:39:01.975986    4971 cache.go:105] Beginning downloading kic artifacts for docker with docker
I0531 17:39:02.047008    4971 image.go:88] Found gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 in local docker daemon, skipping pull
I0531 17:39:02.062152    4971 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0531 17:39:02.062733    4971 preload.go:103] Found local preload: /home/om-mishra/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0531 17:39:02.062765    4971 cache.go:49] Caching tarball of preloaded images
I0531 17:39:02.062833    4971 preload.go:129] Found /home/om-mishra/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0531 17:39:02.062857    4971 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0531 17:39:02.063014    4971 profile.go:156] Saving config to /home/om-mishra/.minikube/profiles/minikube/config.json ...
I0531 17:39:02.063346    4971 cache.go:152] Successfully downloaded all kic artifacts
I0531 17:39:02.063396    4971 start.go:240] acquiring machines lock for minikube: {Name:mk37187116eb3adc8783ec652f9f9b17bbecf133 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0531 17:39:02.063776    4971 start.go:244] acquired machines lock for "minikube" in 330.455µs
I0531 17:39:02.063813    4971 start.go:88] Skipping create...Using existing machine configuration
I0531 17:39:02.063836    4971 fix.go:53] fixHost starting: 
I0531 17:39:02.064161    4971 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0531 17:39:02.140159    4971 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0531 17:39:02.140293    4971 fix.go:131] unexpected machine state, will restart: <nil>
🔄  Restarting existing docker container for "minikube" ...
I0531 17:39:02.257242    4971 cli_runner.go:108] Run: docker start minikube
I0531 17:39:04.695312    4971 cli_runner.go:150] Completed: docker start minikube: (2.437990859s)
I0531 17:39:04.695531    4971 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0531 17:39:04.761777    4971 kic.go:318] container "minikube" state is running.
I0531 17:39:04.762433    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:04.861498    4971 fix.go:55] fixHost completed within 2.770304459s
I0531 17:39:04.861560    4971 start.go:75] releasing machines lock for "minikube", held for 2.797752678s
🤦  StartHost failed, but will try again: IPs output should only be one line, got 2 lines
I0531 17:39:09.862093    4971 start.go:240] acquiring machines lock for minikube: {Name:mk37187116eb3adc8783ec652f9f9b17bbecf133 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0531 17:39:09.862380    4971 start.go:244] acquired machines lock for "minikube" in 192.758µs
I0531 17:39:09.862446    4971 start.go:88] Skipping create...Using existing machine configuration
I0531 17:39:09.862476    4971 fix.go:53] fixHost starting: 
I0531 17:39:09.863222    4971 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0531 17:39:09.929955    4971 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0531 17:39:09.929993    4971 fix.go:131] unexpected machine state, will restart: <nil>
🏃  Updating the running docker "minikube" container ...
I0531 17:39:10.271556    4971 machine.go:88] provisioning docker machine ...
I0531 17:39:10.271661    4971 ubuntu.go:166] provisioning hostname "minikube"
I0531 17:39:10.271809    4971 cli_runner.go:108] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0531 17:39:10.532863    4971 main.go:110] libmachine: Using SSH client type: native
I0531 17:39:11.561267    4971 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x7bf820] 0x7bf7f0 <nil>  [] 0s} 127.0.0.1 32771 <nil> <nil>}
I0531 17:39:11.561352    4971 main.go:110] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0531 17:39:11.563105    4971 main.go:110] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:36380->127.0.0.1:32771: read: connection reset by peer
I0531 17:39:16.376330    4971 main.go:110] libmachine: SSH cmd err, output: <nil>: minikube

I0531 17:39:16.376524    4971 cli_runner.go:108] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0531 17:39:16.448191    4971 main.go:110] libmachine: Using SSH client type: native
I0531 17:39:16.448446    4971 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x7bf820] 0x7bf7f0 <nil>  [] 0s} 127.0.0.1 32771 <nil> <nil>}
I0531 17:39:16.448495    4971 main.go:110] libmachine: About to run SSH command:

		if ! grep -xq '.*\sminikube' /etc/hosts; then
			if grep -xq '127.0.1.1\s.*' /etc/hosts; then
				sudo sed -i 's/^127.0.1.1\s.*/127.0.1.1 minikube/g' /etc/hosts;
			else 
				echo '127.0.1.1 minikube' | sudo tee -a /etc/hosts; 
			fi
		fi
I0531 17:39:16.614033    4971 main.go:110] libmachine: SSH cmd err, output: <nil>: 
I0531 17:39:16.614113    4971 ubuntu.go:172] set auth options {CertDir:/home/om-mishra/.minikube CaCertPath:/home/om-mishra/.minikube/certs/ca.pem CaPrivateKeyPath:/home/om-mishra/.minikube/certs/ca-key.pem CaCertRemotePath:/etc/docker/ca.pem ServerCertPath:/home/om-mishra/.minikube/machines/server.pem ServerKeyPath:/home/om-mishra/.minikube/machines/server-key.pem ClientKeyPath:/home/om-mishra/.minikube/certs/key.pem ServerCertRemotePath:/etc/docker/server.pem ServerKeyRemotePath:/etc/docker/server-key.pem ClientCertPath:/home/om-mishra/.minikube/certs/cert.pem ServerCertSANs:[] StorePath:/home/om-mishra/.minikube}
I0531 17:39:16.614199    4971 ubuntu.go:174] setting up certificates
I0531 17:39:16.614239    4971 provision.go:82] configureAuth start
I0531 17:39:16.614381    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:16.679588    4971 provision.go:85] duration metric: configureAuth took 65.308827ms
W0531 17:39:16.679619    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:16.679839    4971 provision.go:82] configureAuth start
I0531 17:39:16.679919    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:16.745976    4971 provision.go:85] duration metric: configureAuth took 66.117061ms
W0531 17:39:16.746023    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:16.746376    4971 provision.go:82] configureAuth start
I0531 17:39:16.746464    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:16.820052    4971 provision.go:85] duration metric: configureAuth took 73.655846ms
W0531 17:39:16.820085    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:16.820452    4971 provision.go:82] configureAuth start
I0531 17:39:16.820534    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:16.880569    4971 provision.go:85] duration metric: configureAuth took 60.09414ms
W0531 17:39:16.880599    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:16.881039    4971 provision.go:82] configureAuth start
I0531 17:39:16.881137    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:16.946766    4971 provision.go:85] duration metric: configureAuth took 65.709647ms
W0531 17:39:16.946799    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:16.947378    4971 provision.go:82] configureAuth start
I0531 17:39:16.947477    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.010525    4971 provision.go:85] duration metric: configureAuth took 63.130095ms
W0531 17:39:17.010555    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.011566    4971 provision.go:82] configureAuth start
I0531 17:39:17.011714    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.083762    4971 provision.go:85] duration metric: configureAuth took 72.172602ms
W0531 17:39:17.083793    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.084575    4971 provision.go:82] configureAuth start
I0531 17:39:17.084685    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.157144    4971 provision.go:85] duration metric: configureAuth took 72.538268ms
W0531 17:39:17.157183    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.158440    4971 provision.go:82] configureAuth start
I0531 17:39:17.158566    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.225920    4971 provision.go:85] duration metric: configureAuth took 67.445413ms
W0531 17:39:17.225946    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.227602    4971 provision.go:82] configureAuth start
I0531 17:39:17.227736    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.295568    4971 provision.go:85] duration metric: configureAuth took 67.918967ms
W0531 17:39:17.295597    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.298815    4971 provision.go:82] configureAuth start
I0531 17:39:17.298906    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.363023    4971 provision.go:85] duration metric: configureAuth took 64.183635ms
W0531 17:39:17.363052    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.369070    4971 provision.go:82] configureAuth start
I0531 17:39:17.369180    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.439710    4971 provision.go:85] duration metric: configureAuth took 70.602082ms
W0531 17:39:17.439749    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.451257    4971 provision.go:82] configureAuth start
I0531 17:39:17.451393    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.516344    4971 provision.go:85] duration metric: configureAuth took 65.044764ms
W0531 17:39:17.516382    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.525816    4971 provision.go:82] configureAuth start
I0531 17:39:17.525998    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.606037    4971 provision.go:85] duration metric: configureAuth took 80.160839ms
W0531 17:39:17.606075    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.623374    4971 provision.go:82] configureAuth start
I0531 17:39:17.623583    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.688445    4971 provision.go:85] duration metric: configureAuth took 64.993289ms
W0531 17:39:17.688476    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.712583    4971 provision.go:82] configureAuth start
I0531 17:39:17.712721    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.778435    4971 provision.go:85] duration metric: configureAuth took 65.8021ms
W0531 17:39:17.778479    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.821094    4971 provision.go:82] configureAuth start
I0531 17:39:17.822812    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.886914    4971 provision.go:85] duration metric: configureAuth took 65.750687ms
W0531 17:39:17.886951    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:17.938553    4971 provision.go:82] configureAuth start
I0531 17:39:17.938727    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:17.997583    4971 provision.go:85] duration metric: configureAuth took 58.962955ms
W0531 17:39:17.997623    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:18.075945    4971 provision.go:82] configureAuth start
I0531 17:39:18.076127    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:18.139450    4971 provision.go:85] duration metric: configureAuth took 63.44113ms
W0531 17:39:18.139483    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:18.313953    4971 provision.go:82] configureAuth start
I0531 17:39:18.314128    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:18.393417    4971 provision.go:85] duration metric: configureAuth took 79.417739ms
W0531 17:39:18.393454    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:18.552951    4971 provision.go:82] configureAuth start
I0531 17:39:18.553141    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:18.629612    4971 provision.go:85] duration metric: configureAuth took 76.601442ms
W0531 17:39:18.629648    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:18.863676    4971 provision.go:82] configureAuth start
I0531 17:39:18.863816    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:18.935209    4971 provision.go:85] duration metric: configureAuth took 71.492234ms
W0531 17:39:18.935244    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:19.364820    4971 provision.go:82] configureAuth start
I0531 17:39:19.365004    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:19.435148    4971 provision.go:85] duration metric: configureAuth took 70.266391ms
W0531 17:39:19.435192    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:20.236434    4971 provision.go:82] configureAuth start
I0531 17:39:20.236645    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:20.317868    4971 provision.go:85] duration metric: configureAuth took 81.373308ms
W0531 17:39:20.317908    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:21.847168    4971 provision.go:82] configureAuth start
I0531 17:39:21.847373    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:21.925645    4971 provision.go:85] duration metric: configureAuth took 78.420635ms
W0531 17:39:21.925685    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:23.261001    4971 provision.go:82] configureAuth start
I0531 17:39:23.261184    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:23.331929    4971 provision.go:85] duration metric: configureAuth took 70.873921ms
W0531 17:39:23.331962    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:25.344908    4971 provision.go:82] configureAuth start
I0531 17:39:25.345093    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:25.426048    4971 provision.go:85] duration metric: configureAuth took 81.068485ms
W0531 17:39:25.426103    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:30.170651    4971 provision.go:82] configureAuth start
I0531 17:39:30.170860    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:30.241794    4971 provision.go:85] duration metric: configureAuth took 71.090124ms
W0531 17:39:30.241829    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:34.256473    4971 provision.go:82] configureAuth start
I0531 17:39:34.256651    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:34.330578    4971 provision.go:85] duration metric: configureAuth took 74.049967ms
W0531 17:39:34.330616    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:39:45.966597    4971 provision.go:82] configureAuth start
I0531 17:39:45.966743    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:39:46.041982    4971 provision.go:85] duration metric: configureAuth took 75.333503ms
W0531 17:39:46.042061    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:40:01.340396    4971 provision.go:82] configureAuth start
I0531 17:40:01.340579    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:40:01.417644    4971 provision.go:85] duration metric: configureAuth took 77.20311ms
W0531 17:40:01.417679    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:40:21.049711    4971 provision.go:82] configureAuth start
I0531 17:40:21.049885    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:40:21.128190    4971 provision.go:85] duration metric: configureAuth took 78.429234ms
W0531 17:40:21.128228    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:40:36.323826    4971 provision.go:82] configureAuth start
I0531 17:40:36.324011    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:40:36.399211    4971 provision.go:85] duration metric: configureAuth took 75.333376ms
W0531 17:40:36.399240    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:41:04.802327    4971 provision.go:82] configureAuth start
I0531 17:41:04.802503    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:41:04.871151    4971 provision.go:85] duration metric: configureAuth took 68.768786ms
W0531 17:41:04.871182    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:42:11.306567    4971 provision.go:82] configureAuth start
I0531 17:42:11.306791    4971 cli_runner.go:108] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I0531 17:42:11.376923    4971 provision.go:85] duration metric: configureAuth took 70.294305ms
W0531 17:42:11.376956    4971 ubuntu.go:177] configureAuth failed: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:42:11.376978    4971 ubuntu.go:186] Error configuring auth during provisioning Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:42:11.376997    4971 machine.go:91] provisioned docker machine in 3m1.105402409s
I0531 17:42:11.377018    4971 fix.go:55] fixHost completed within 3m1.514548549s
I0531 17:42:11.377031    4971 start.go:75] releasing machines lock for "minikube", held for 3m1.514613956s
😿  Failed to start docker container. "minikube start" may fix it: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
I0531 17:42:11.398735    4971 exit.go:58] WithError(error provisioning host)=Failed to start host: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40c11a, 0x187eca0, 0x186da80)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
k8s.io/minikube/pkg/minikube/exit.WithError(0x1ae579a, 0x17, 0x1db6b80, 0xc0002ca320)
	/app/pkg/minikube/exit/exit.go:58 +0x34
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b00360, 0xc000227610, 0x0, 0x1)
	/app/cmd/minikube/cmd/start.go:169 +0xac2
github.com/spf13/cobra.(*Command).execute(0x2b00360, 0xc000227600, 0x1, 0x1, 0x2b00360, 0xc000227600)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x2b05220, 0x0, 0x1, 0xc000682c60)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:112 +0x747
main.main()
	/app/cmd/minikube/main.go:66 +0xea
W0531 17:42:11.399109    4971 out.go:201] error provisioning host: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

💣  error provisioning host: Failed to start host: provision: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

The second command o/p is a simple as you have mentioned : 172.17.0.2,

**Comment by afbjorklund** [comment]
Unfortunately it seems like the actual stdout/stderr was never logged.

Since it doesn't return any error, only the message itself is written...

```go
        lines, err := inspect(Docker, name, "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}")
        if err != nil {
                return "", "", errors.Wrap(err, "inspecting NetworkSettings.Networks")
        }

        if len(lines) != 1 {
                return "", "", errors.Errorf("IPs output should only be one line, got %d lines", len(lines))
        }
```

Should probably add some verbose/debug logging, in that second case.

**Comment by XieGuochao** [comment]
I have encountered the same issue as well on Ubuntu 18.04!

**Comment by XieGuochao** [comment]
Maybe it is because your permission is wrong for config.json? I try this and then I succeed:
https://askubuntu.com/questions/747778/docker-warning-config-json-permission-denied

**Comment by priyawadhwa** [comment]
Hey @Mishraom99 are you still seeing this issue? If so, could you try:

1. Upgrading to minikube v1.12
1. Running `minikube delete --all`
1. Running `minikube start`

**Comment by medyagh** [comment]
I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by matheusnicolas** [comment]
I had the same problem and first I tried to remove the .docker/config.json file, the same issue persists. So:

After deleted the config.json file I tried these steps:

$ sudo chown "$USER":"$USER" /home/"$USER"/.docker -R
$ sudo chmod g+rwx "$HOME/.docker" -R

Change user for your whoami, try whoami in your terminal and paste the result on $USER and be happy!
