### ISSUE TITLE
Unclear how the container images are updated

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#8339]
The process of updating the minikube.iso is somewhat clear, from the Makefile etc.

But for the "kicbase" and the "storage-provisioner", things are not so straight-forward

They seem to only be building snapshot and latest, but those don't go into release

So it would be good to document, how to make changes to the the container images.

**Comment by afbjorklund** [comment]
@medyagh @tstromberg

**Comment by medyagh** [comment]
we need to rename the current image to -amd64 and then cross-compile.

**Comment by sharifelgamal** [comment]
This has been automated and documented as this point. Closing.
