### ISSUE TITLE
Docker as preferred driver on macOS/Windows

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#8353]
At the moment, we default to:

- Docker on Linux
- Hyperkit on macOS
- Hyper-V on Windows

- On macOS, Docker is better at VPN handling.
- On Windows, Docker is better at privilege handling.

This suggests that for most users, we could make the default Docker for all platforms, and fall-back to Hyperkit/Hyper-V if Docker is not available.

**Comment by afbjorklund** [comment]
Is this related to #8135 ? It seems that some of the "none" users are struggling with "docker"

We have some suggestion where we encourage them to change, not always working out...

**Comment by tstromberg** [comment]
@afbjorklund - not directly related, no. This is for the default case on macOS/Windows when one does not specify a `--driver` option.

**Comment by afbjorklund** [comment]
The semantic difference between preferred and default is not clear to me, they looked the same.

**Comment by afbjorklund** [comment]
There were also some objections to this wording:
`For non-root usage, try the newer 'docker' driver`

Even though minikube itself does not require root,
docker **does** require root (group). So it's not really "non-root" ?

**Comment by afbjorklund** [comment]
Should we make the persistent volume handling a blocker for this ?
Currently they are **not** being persisted, but stored on tmpfs : #8151

It is the same on Linux (where it is already default driver), though.
Just getting more exposure, with more users from Mac and Win.

**Comment by tstromberg** [comment]
Yes, I feel that #8151 should be a blocker for this.

**Comment by afbjorklund** [comment]
Well, at least it is consistent over the platforms now

**Comment by afbjorklund** [comment]
We moved the storage issue to 1.13, see: #8657
