### ISSUE TITLE
How to create a PSP enabled cluster in GitHub actions

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/minikube#8356]
**Steps to reproduce the issue:** 

I am trying to create a PSP enabled cluster in GitHub actions using driver `none`. But I don't see any pods in `kube-system` namespace.

I am able to create a PSP enabled cluster using `minikube` virtualbox driver on a Ubuntu 18.04 host. Here are the steps I follow:

1. Create cluster: 

```
minikube start \
  --driver=virtualbox \
  --kubernetes-version=v1.18.3 \
  --wait=none \
  --extra-config=apiserver.enable-admission-plugins="NamespaceLifecycle,LimitRanger,ServiceAccount,TaintNodesByCondition,Priority,DefaultTolerationSeconds,DefaultStorageClass,StorageObjectInUseProtection,PersistentVolumeClaimResize,RuntimeClass,CertificateApproval,CertificateSigning,CertificateSubjectRestriction,DefaultIngressClass,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,PodSecurityPolicy"
```

2. Now, open a new terminal and run:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/privileged-psp.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/baseline-psp.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/master/content/en/examples/policy/restricted-psp.yaml

kubectl apply -f https://github.com/appscodelabs/tasty-kube/raw/master/minikube/psp/cluster-roles.yaml
kubectl apply -f https://github.com/appscodelabs/tasty-kube/raw/master/minikube/psp/role-bindings.yaml
```

The PSP yamls are taken from https://kubernetes.io/docs/concepts/security/pod-security-standards/#policy-instantiation

3. Now, wait several minutes, you can get a working k8s cluster.

Now, I am doing the same steps in Github Actions, but I am using `--driver=none`, because GitHub actions run inside a VM.
https://github.com/tamalsaha/minikube-actions-demo

**Full output of failed command:** 

I tried to run a pod using storageclass `standard` in the PSP enabled cluster. But the pods will not start. The pods work with `driver=none` when PSP is not enabled.

```
root@mini2:/var/lib/minikube/binaries/v1.18.3# ./kubectl apply -f https://github.com/tamalsaha/minikube-actions-demo/raw/master/hack/kubernetes/pod.yaml
persistentvolumeclaim/local-path-pvc created
pod/volume-test created

root@minikube:/var/lib/minikube/binaries/v1.18.3# ./kubectl get pods --all-namespaces
NAMESPACE     NAME                  READY   STATUS             RESTARTS   AGE
default       volume-test           0/1     Pending            0          54m
kube-system   storage-provisioner   0/1     CrashLoopBackOff   14         55m
```

**Full output of `minikube start` command used, if not already included:**
https://gist.github.com/tamalsaha/85b617c1bb18fe1e6c241e055baff358

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
It doesn't surprise me that PSP would not work with the none driver. Have you tried with the docker driver instead?

**Comment by tamalsaha** [comment]
I tried with Docker driver. It did not work.

**Comment by sharifelgamal** [comment]
What sort of error are you seeing with the docker driver?

**Comment by medyagh** [comment]
@tamalsaha I recommend using minikube github action runner, setup-minikube https://github.com/marketplace/actions/setup-minikube

have your tried [setup-minikube](https://github.com/marketplace/actions/setup-minikube) ?

**Comment by medyagh** [comment]
@tamalsaha did this help ? 
https://github.com/kubernetes/minikube/issues/8356#issuecomment-693592643

**Comment by sharifelgamal** [comment]
Hey @tamalsaha – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
