### ISSUE TITLE
 192 start.go:723] StartHost: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

### ISSUE THREAD

**Issue by yzhang-flexera** [kubernetes/minikube#8358]
**Steps to reproduce the issue:** 

1. minikube start --memory 8Gi --cpus 4

**Full output of failed command:** 
😄  minikube v1.3.1 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=4, Memory=8000MB, Disk=20000MB) ...
E0602 17:04:09.303284     192 start.go:723] StartHost: create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

💣  Unable to start VM
❌  Error: [VBOX_NOT_FOUND] create: precreate: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path
💡  Suggestion: Install VirtualBox, ensure that VBoxManage is executable and in path, or select an alternative value for --vm-driver
📘  Documentation: https://www.virtualbox.org/wiki/Downloads
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3784
    ▪ https://github.com/kubernetes/minikube/issues/3776

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
Also tried to run 
`minikube` start --memory 8Gi --cpus 4 `--vm-driver=VirtualBox`
It returns message:
😄  minikube v1.3.1 on Ubuntu 18.04
💣  The driver 'VirtualBox' is not supported on linux

I have windows environment and wsl enabled. I also have installed minikube version v1.3.1, virtualbox 6.1, Ubuntu 18.04. virtualbox was installed via Chocolatey in powershell.
The Path already contains C:\Program Files\Oracle\VirtualBox in windows.

I tried to type VBoxManage in bash, it can recognize it. Can you please suggest why minikube cannot recorganize the virtualbox I installed? 
</details>

Thank you very much in advance!

**Comment by sharifelgamal** [comment]
You're using minikube 1.3.1, which is 10 months old. Could you upgrade to the latest minikube (1.11) and try again?

**Comment by priyawadhwa** [comment]
Hey @yzhang-flexera -- 
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

If you're still using minikube, I'd recommend what sharif said and try upgrading to our latest release.

Thank you for sharing your experience!
