### ISSUE TITLE
minikube start报错

### ISSUE THREAD

**Issue by phpsxg** [kubernetes/minikube#8364]
**重现问题所需的命令**：
minikube start --image-mirror-country cn  --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso --registry-mirror=https://pee6w651.mirror.aliyuncs.com

**失败的命令的完整输出**：<details>

😄  Debian 8.0 上的 minikube v1.11.0
✨  根据现有的配置文件使用 virtualbox 驱动程序
💿  正在下载 VM boot image...
E0603 17:53:02.690492   26582 iso.go:86] Unable to download https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso Dst:/home/phpsxg/.minikube/cache/iso/minikube-v1.9.0.iso.download Pwd: Mode:2 Detectors:[0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38] Decompressors:map[bz2:0x2b3cb38 gz:0x2b3cb38 tar.bz2:0x2b3cb38 tar.gz:0x2b3cb38 tar.xz:0x2b3cb38 tbz2:0x2b3cb38 tgz:0x2b3cb38 txz:0x2b3cb38 xz:0x2b3cb38 zip:0x2b3cb38] Getters:map[file:0xc000809c70 http:0xc0003151c0 https:0xc0003151e0] Dir:false ProgressListener:0x2b152d0 Options:[0xc1f6a0]}: Get https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso: Bad Request

💣  error provisioning host: Failed to cache ISO: unable to cache ISO: 
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso Dst:/home/phpsxg/.minikube/cache/iso/minikube-v1.9.0.iso.download Pwd: Mode:2 Detectors:[0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38] Decompressors:map[bz2:0x2b3cb38 gz:0x2b3cb38 tar.bz2:0x2b3cb38 tar.gz:0x2b3cb38 tar.xz:0x2b3cb38 tbz2:0x2b3cb38 tgz:0x2b3cb38 txz:0x2b3cb38 xz:0x2b3cb38 zip:0x2b3cb38] Getters:map[file:0xc000809c70 http:0xc0003151c0 https:0xc0003151e0] Dir:false ProgressListener:0x2b152d0 Options:[0xc1f6a0]}: Get https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso: Bad Request

😿  由于出错 minikube 正在退出。如果以上信息没有帮助，请提交问题反馈：
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

🤷  The control plane node must be running for this command
👉  To fix this, run: "minikube start"

</details>

**使用的操作系统版本**：

**Comment by sharifelgamal** [comment]
由于某些原因，下载iso失败，这很奇怪，因为https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso有效

您可以在浏览器中手动点击该网址吗？

**Comment by medyagh** [comment]
Hi @phpsxg c, I haven't heard back from you, I wonder if you still have this issue?
I noticed you are using an old version of minikube, v.1.9.0 is very very old. do you mind trying with latest version ?


Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
