### ISSUE TITLE
minikube start提示 This VM is having trouble accessing https://k8s.gcr.io

### ISSUE THREAD

**Issue by phpsxg** [kubernetes/minikube#8365]
**重现问题所需的命令**：
minikube start
**失败的命令的完整输出**：<details>
😄  Debian 8.0 上的 minikube v1.11.0
✨  根据现有的配置文件使用 virtualbox 驱动程序
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🌐  找到的网络选项：
    ▪ HTTP_PROXY=http://hub-mirror.c.163.com
    ▪ HTTPS_PROXY=https://hub-mirror.c.163.com
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🐳  正在 Docker 19.03.8 中准备 Kubernetes v1.18.3…
    ▪ env HTTP_PROXY=http://hub-mirror.c.163.com
    ▪ env HTTPS_PROXY=https://hub-mirror.c.163.com
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
❗  This VM is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🔎  Verifying Kubernetes components...
🌟  Enabled addons: dashboard, default-storageclass, storage-provisioner
🏄  完成！kubectl 已经配置至 "minikube"

❗  /usr/local/bin/kubectl is version 1.6.4, which may be incompatible with Kubernetes 1.18.3.
💡  You can also use 'minikube kubectl -- get pods' to invoke a matching version

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by LargeOrange** [comment]
我刚刚也遇见了这个问题怎么处理的呢
