### ISSUE TITLE
docker driver: host.minikube.internal is <nil>

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#8369]
@tstromberg 
I don't see any ip addr against `host.minikube.internal` entry in the `/etc/hosts` file.
```
docker@minikube:~$ cat /etc/hosts
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
ff00::0	ip6-mcastprefix
ff02::1	ip6-allnodes
ff02::2	ip6-allrouters
172.17.0.3	minikube
<nil>	host.minikube.internal
```

Also, when I try `ping` command as suggested in the doc you mentioned:
```
docker@minikube:~$ ping host.minikube.internal
-bash: ping: command not found
```

How I installed and started minikube
```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64   && chmod +x minikube
sudo install minikube /usr/bin/

$ minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd

minikube start --driver=docker
```

What am I missing here. Please suggest.

_Originally posted by @codingkapoor in https://github.com/kubernetes/minikube/issues/2735#issuecomment-638518407_

**Comment by govargo** [comment]
I tried docker driver with macOS but this is not reproduced.

```
$ out/minikube version
minikube version: v1.11.0
commit: 4eb09e760b3b55cf0dc541e802c77bc50e52598d

macOS Mojave 10.14.5
```

**Comment by Yiyiyimu** [comment]
Same problem here. `ping not found` error in docker based minikube

**Comment by Aditya91** [comment]
Has this been resolved? I'm getting the same error `-bash: ping: command not found` with minikube and docker driver.
