### ISSUE TITLE
cloudshell: Problems detected in kubelet

### ISSUE THREAD

**Issue by Grappeggia** [kubernetes/minikube#8375]
**Steps to reproduce the issue:** 

1. Open Cloud Shell
2. Run minikube start

**Full output of failed command:** 
(attached file with the ([output.txt](https://github.com/kubernetes/minikube/files/4731985/output.txt)) when using --alsologtostderr)
* minikube v1.10.1 on Debian 9.12
  - MINIKUBE_FORCE_SYSTEMD=true
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running docker "minikube" container ...
* Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
  - kubeadm.pod-network-cidr=10.244.0.0/16
  - Jun 04 18:05:01 minikube kubelet[2116]: E0604 18:05:01.015746    2116 pod_workers.go:191] Error syncing pod 97c575a27f5e44612d2635f3f23ddb5a ("etcd-minikube_k
ube-system(97c575a27f5e44612d2635f3f23ddb5a)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "back-off 20s restarting failed container=e
tcd pod=etcd-minikube_kube-system(97c575a27f5e44612d2635f3f23ddb5a)"
  - Jun 04 18:05:04 minikube kubelet[2116]: E0604 18:05:04.689943    2116 pod_workers.go:191] Error syncing pod e5630850-7048-463e-8645-d200c939efef ("go-guestboo
k-frontend-6cc7f7c86f-jrqrj_default(e5630850-7048-463e-8645-d200c939efef)"), skipping: failed to "StartContainer" for "frontend" with CrashLoopBackOff: "back-off 
20s restarting failed container=frontend pod=go-guestbook-frontend-6cc7f7c86f-jrqrj_default(e5630850-7048-463e-8645-d200c939efef)"
* Problems detected in kubelet:
  - Jun 04 18:05:04 minikube kubelet[2116]: E0604 18:05:04.689943    2116 pod_workers.go:191] Error syncing pod e5630850-7048-463e-8645-d200c939efef ("go-guestboo
k-frontend-6cc7f7c86f-jrqrj_default(e5630850-7048-463e-8645-d200c939efef)"), skipping: failed to "StartContainer" for "frontend" with CrashLoopBackOff: "back-off 
20s restarting failed container=frontend pod=go-guestbook-frontend-6cc7f7c86f-jrqrj_default(e5630850-7048-463e-8645-d200c939efef)"
* Problems detected in kubelet:
  - Jun 04 18:05:04 minikube kubelet[2116]: E0604 18:05:04.689943    2116 pod_workers.go:191] Error syncing pod e5630850-7048-463e-8645-d200c939efef ("go-guestboo
k-frontend-6cc7f7c86f-jrqrj_default(e5630850-7048-463e-8645-d200c939efef)"), skipping: failed to "StartContainer" for "frontend" with CrashLoopBackOff: "back-off 
20s restarting failed container=frontend pod=go-guestbook-frontend-6cc7f7c86f-jrqrj_default(e5630850-7048-463e-8645-d200c939efef)"
* Problems detected in kubelet:
  - Jun 04 18:07:05 minikube kubelet[2116]: E0604 18:07:05.968487    2116 reflector.go:178] object-"kube-system"/"kube-proxy": Failed to list *v1.ConfigMap: confi
gmaps "kube-proxy" is forbidden: User "system:node:minikube" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship fou
nd between node "minikube" and this object
* Enabled addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"
[]

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
thanks @Grappeggia for reporting this, are you running it as the default user ?

( it is probably not related but would you mind trying with latest version and also try --preload=false )

**Comment by medyagh** [comment]
@Grappeggia are you using the normal google cloud shell ? or the boosted one ?
how much ram does it have?
minikube needs at least 2 GB Ram

**Comment by Grappeggia** [comment]
Yes, this is with the regular Cloud Shell (e2-small), with 2GB VM

**Comment by priyawadhwa** [comment]
While trying to reproduce this, I found a different bug. On a clean Cloud Shell VM (not boosted),  on the first `minikube start` the minikube docker container fails to come up with this error:

```
I0605 15:16:11.535973     460 cli_runner.go:108] Run: docker inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0605 15:16:11.589063     460 main.go:110] libmachine: Using SSH client type: native
I0605 15:16:11.589627     460 main.go:110] libmachine: &{{{<nil> 0 [] [] []} docker [0x7bf820] 0x7bf7f0 <nil>  [] 0s} 127.0.0.1 32771 <nil> <nil>}
I0605 15:16:11.589662     460 main.go:110] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0605 15:16:11.590546     460 main.go:110] libmachine: Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:40544->127.0.0.1:32771: read: connection reset by peer
I0605 15:16:14.590934     460 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:32771: connect: connection refused
I0605 15:16:17.591423     460 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:32771: connect: connection refused
I0605 15:16:20.591883     460 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:32771: connect: connection refused
I0605 15:16:23.592421     460 main.go:110] libmachine: Error dialing TCP: dial tcp 127.0.0.1:32771: connect: connection refused
```

Subsequent calls to `minikube delete && minikube start` reliably pass. Looking into why this would fail the first time but not afterwards.

**Comment by priyawadhwa** [comment]
Hey @Grappeggia -- this output looks like you ran `minikube start` on an existing cluster which already had the go-guestbook application installed.

Was there a reason you had to run `minikube start` twice?

**Comment by medyagh** [comment]
@Grappeggia I haven't heard from you are you still having this issue ? I will close please reopen if needed.
