### ISSUE TITLE
Move kubelet parameters to config file

### ISSUE THREAD

**Issue by prasadkatti** [kubernetes/minikube#8380]
Currently, the kubelet parameters are passed in as command line arguments. However, for most of the parameters this was [deprecated in v1.10](https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/). As part of that, if those parameters continue to be passed on the command-line, that generates warnings in the kubelet logs, like these -

> minikube kubelet[3637]: Flag --authorization-mode has been deprecated ...
minikube kubelet[3637]: Flag --cgroup-driver has been deprecated ...
minikube kubelet[3637]: Flag --client-ca-file has been deprecated ...
minikube kubelet[3637]: Flag --pod-manifest-path has been deprecated ...
minikube kubelet[3637]: Flag --cluster-domain has been deprecated ...
minikube kubelet[3637]: Flag --fail-swap-on has been deprecated ...

The recommended solution is to pass in those parameters using kubelet's config file.

I would like to work on this issue. I already have a PR that partially resolves this - https://github.com/kubernetes/minikube/pull/8342

**Comment by medyagh** [comment]
sounds like a good idea

**Comment by prasadkatti** [comment]
#8342 only partially fixes the issue. Reopening...
