### ISSUE TITLE
Addon registry-aliases alpine image missing bash command (ash works)

### ISSUE THREAD

**Issue by tsraza** [kubernetes/minikube#8383]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable registry
3. minikube addons enable registry-aliases

kubelet says:
`
Error: failed to start container "update": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"bash\": executable file not found in $PATH": unknown
`

Easily fixed by changing the daemonset entrypoint (command[0]) from `bash` to `ash`

**Comment by tsraza** [comment]
The offending line: https://github.com/kubernetes/minikube/blob/master/deploy/addons/registry-aliases/node-etc-hosts-update.tmpl#L32

**Comment by sharifelgamal** [comment]
Nice catch, thanks for the heads up. Help wanted!
