### ISSUE TITLE
Upgrade CRI-O to 1.18.3

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#8388]
For Kubernetes 1.19 etc, move to crio 1.18.1 and podman 1.9.3

EDIT: Most likely, this also needs a newer version of conmon

**Comment by afbjorklund** [comment]
Reverted

**Comment by afbjorklund** [comment]
Blocked on #7904

**Comment by afbjorklund** [comment]
Stealth upgraded for Ubuntu, but still pending for Buildroot

**Comment by medyagh** [comment]
we could do this after buildroot upgrade

**Comment by renich** [comment]
Can we just jump directly to cri-o v1.19.0?

**Comment by afbjorklund** [comment]
Theoretically, but they bumped to go 1.15

**Comment by afbjorklund** [comment]
Most likely we will end up using CRI-O 1.19 with Kubernetes 1.20 or something, that is how it usually works out...

**Comment by priyawadhwa** [comment]
If we're skipping 1.18.3, can this issue be closed?

**Comment by afbjorklund** [comment]
> If we're skipping 1.18.3, can this issue be closed?

We're not skipping 1.8.3 as far as I know at least.
