### ISSUE TITLE
cannot edit files in minikube kicbase container image

### ISSUE THREAD

**Issue by schmitt-kevin** [kubernetes/minikube#8393]
**Steps to reproduce the issue:** 

1. minikube start --driver=docker
2. minikube ssh
3. vi /etc/ssh/sshd_config
4. I get the following: "-bash: vi: command not found"

I'm on a centos7 instance.

Am I missing something?

**Comment by afbjorklund** [comment]
There is no editor available in the ubuntu VM. You can install one if you like.

```
docker@minikube:~$ sudo apt update && sudo apt install -y vim
```

**Comment by afbjorklund** [comment]
@medyagh : should we add an $EDITOR ? Note that vim also brings python3...

```
The following additional packages will be installed:
  file libexpat1 libgpm2 libmagic-mgc libmagic1 libmpdec2 libpython3.7 libpython3.7-minimal libpython3.7-stdlib mime-support vim-common vim-runtime xxd xz-utils
Suggested packages:
  gpm ctags vim-doc vim-scripts
The following NEW packages will be installed:
  file libexpat1 libgpm2 libmagic-mgc libmagic1 libmpdec2 libpython3.7 libpython3.7-minimal libpython3.7-stdlib mime-support vim vim-common vim-runtime xxd xz-utils
0 upgraded, 15 newly installed, 0 to remove and 49 not upgraded.
Need to get 11.4 MB of archives.
After this operation, 58.5 MB of additional disk space will be used.
```

**Comment by afbjorklund** [comment]
Maybe this package would work better: https://packages.ubuntu.com/vim-tiny
> This package contains a minimal version of Vim compiled with no GUI and
> a small subset of features. This package's sole purpose is to provide
> the vi binary for base installations.
```

The following additional packages will be installed:
  vim-common xxd
Suggested packages:
  indent
The following NEW packages will be installed:
  vim-common vim-tiny xxd
0 upgraded, 3 newly installed, 0 to remove and 49 not upgraded.
Need to get 655 kB of archives.
After this operation, 1980 kB of additional disk space will be used.
```

**Comment by schmitt-kevin** [comment]
Awesome, vim.tiny works. Another question I had was 'what package manager or linux distro is minikube VM using?', but you answered that in your response.

**Comment by afbjorklund** [comment]
It varies between drivers, but you can check the systemd file: `/etc/os-release`
