### ISSUE TITLE
too much memory during build with docker-machine

### ISSUE THREAD

**Issue by runseb** [kubernetes/minikube#84]
Hi,

I tried a build using a docker-machine based host on OSX.
Bumped the host to 2 GB ram on virtual box and the build keeps failing.

```
Status: Downloaded newer image for golang:1.6
CGO_ENABLED=1 go build -ldflags="-s" -o ./out/localkube ./cmd/localkube
# k8s.io/minikube/cmd/localkube
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory
```

It would be great to make the build without docker and/or to reduce the needed RAM.

-sebastien

**Comment by dlorenc** [comment]
Not sure what we can do here. Building localkube requires building much of kubernetes:
https://github.com/kubernetes/kubernetes/issues/11852

We build in docker right now because we also need CGO, and this is a cross build when you're on OSX.

One idea I had was to give an option of not compiling the localkube binary as part of the minikube build, if all you want to do is hack on the minikube CLI itself.

**Comment by runseb** [comment]
yup, I see why there was the discussion on releasing localkube.
Might be good for now to download localkube from their upstream repo, to simplify the build.

How much RAM is need to build ? I tried in a Vbox VM with 2GB and it fails, which seems strange.

**Comment by dlorenc** [comment]
It seems slightly unpredictable, I've had success with 2GB but normally bump it to 8+ because that's what it takes for me to build k8s stuff.

**Comment by dlorenc** [comment]
@luxas When your changes to compile everything statically in kubernetes land, will we be able to drop cgo? I think that's the only reason we currently need to cross-compile in docker.

**Comment by luxas** [comment]
No we won't. We have to compile inside a container anyway, as official Kubernetes does and probably always will do. The change will be that `glibc` isn't required at _runtime_, which is a huge step forward. 

It will still be required at _compile time_.

But that isn't the same as this issue. Kubernetes just requires much memory when compiling. It's a lot of source code.

**Comment by ngtuna** [comment]
I got the same. I tried VM with 4GB but no luck.

```
# k8s.io/kubernetes/cmd/kubelet
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory

# k8s.io/kubernetes/cmd/hyperkube
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: fork/exec /usr/bin/gcc: cannot allocate memory
```

 Anyone tell me how much memory need to build Kubernetes latest code on master branch?

**Comment by dlorenc** [comment]
Which build are you trying now? Those errors look like kubernetes build errors, not minikube ones. I'm successfully able to build minikube with 4, but I usually need 12ish for k8s.

**Comment by ngtuna** [comment]
@dlorenc Yeah sorry I mean the kubernetes build, not minikube build. I figured out that I need more than 4GB to build the latest kubernetes source.

**Comment by dlorenc** [comment]
I was just able to run a "make quick-release" for kubernetes with 8gb of ram. It failed for me with 4gb as well.

**Comment by dlorenc** [comment]
I'm going to close this out, there's not really anything we can do in the minikube side. Published builds make it so most users don't need to compile.

I added the requirements to the README.
