### ISSUE TITLE
kvm: dial tcp :22: connect: connection refused

### ISSUE THREAD

**Issue by shehryarhashmi71** [kubernetes/minikube#8402]
minikube start --vm-driver kvm2
😄  minikube v1.11.0 on Ubuntu 18.04
✨  Using the kvm2 driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4: 526.01 MiB
🏃  Updating the running kvm2 "minikube" VM ...
🤦  StartHost failed, but will try again: provision: Temporary Error: NewSession: new client: new client: dial tcp :22: connect: connection refused
🏃  Updating the running kvm2 "minikube" VM ...
😿  Failed to start kvm2 VM. "minikube start" may fix it: provision: Temporary Error: NewSession: new client: new client: dial tcp :22: connect: connection refused

💣  error provisioning host: Failed to start host: provision: Temporary Error: NewSession: new client: new client: dial tcp :22: connect: connection refused

**Comment by medyagh** [comment]
@shehryarhashmi71 are you using minikube with a VPN or a corp network ?

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube? that driver doesnt have issues with VPN
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by shehryarhashmi71** [comment]
I have tried but result is 
 minikube start --driver=docker
😄  minikube v1.11.0 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
✋  Stopping "minikube" in docker ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create host timed out in 240.000000 seconds
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 2.836287169s
💡  Restarting the docker service may improve performance.
😿  Failed to start docker container. "minikube start" may fix it: creating host: create: creating: prepare kic ssh: apply authorized_keys file ownership, output 
** stderr ** 
Error response from daemon: Container 357749e2d8fe0cfc845a00e510bb100ddbfe15bd05cfcd39a7bb9ffda7ed0f80 is not running

** /stderr **: chown docker:docker /home/docker/.ssh/authorized_keys: exit status 1
stdout:

stderr:
Error response from daemon: Container 357749e2d8fe0cfc845a00e510bb100ddbfe15bd05cfcd39a7bb9ffda7ed0f80 is not running


💣  error provisioning host: Failed to start host: creating host: create: creating: prepare kic ssh: apply authorized_keys file ownership, output 
** stderr ** 
Error response from daemon: Container 357749e2d8fe0cfc845a00e510bb100ddbfe15bd05cfcd39a7bb9ffda7ed0f80 is not running

** /stderr **: chown docker:docker /home/docker/.ssh/authorized_keys: exit status 1
stdout:

stderr:
Error response from daemon: Container 357749e2d8fe0cfc845a00e510bb100ddbfe15bd05cfcd39a7bb9ffda7ed0f80 is not running

**Comment by medyagh** [comment]
thanks for the update, 
@shehryarhashmi71 can you plz paste the full output of the following commands in order:

$ docker info
$ minikube delete --all
$ docker volume ls
$ docker volume prune
$ minikube start --driver=docker --alsologtostderr

**Comment by priyawadhwa** [comment]
Hey @shehryarhashmi71  are you still seeing this issue? If so, could you please provide the output to the commands in the previous comment?

**Comment by irtaza909** [comment]
i am having the same exact issue please help. it was working fine i upgraded the ram from 4gb to 8gb and now its not working

**Comment by medyagh** [comment]
@shehryarhashmi71 @irtaza909 my guess is you are using a VPN, I suggest using the docker driver, 

have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/
