### ISSUE TITLE
broke vm can't be started and can't be deleted

### ISSUE THREAD

**Issue by runefs** [kubernetes/minikube#8411]
**Steps to reproduce the issue:** 

After having successfully used the hyperv driver my minikube now crashes on start and it can't be deleted either (same issue regardless of whether I run as admin or user)

minikube delete/minikube start
all have the same result (vm crashed)

**Full output of failed command:** 
W0608 10:39:25.126657   11748 root.go:254] Error reading config file at P:\.minikube\config\config.json: open P:\.minikube\config\config.json: The system cannot find the file specified.
I0608 10:39:26.874459   11748 cluster.go:236] host is in state
* Deleting "minikube" in hyperv ...
W0608 10:39:29.651150   11748 exit.go:99] Failed to delete cluster: exit status 1
*
X Failed to delete cluster: exit status 1

**Comment by medyagh** [comment]
@runefs can you access this file manually ? 
```
P:.minikube\config\config.json: open P:.minikube\config\config.json
```

it seems like minikube was created in P:\.minikube but not it cant not access it, is that a network driver or a external hard disk ?

and also you could try deleting using purge

```
minikube delete --all --purge
```

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by tstromberg** [comment]
Also, any idea what version of minikube this was?

**Comment by medyagh** [comment]
@runefs I havent' heard from you, do you still have this issue ?

do you mind providing the output of the following commands ? 

```
virt-host-validate
```
and also
```virsh -c qemu:///system list --all```
and aslo 

```virsh net-list```

and also
```docker-machine-driver-kvm2 version```


link to docs
https://minikube.sigs.k8s.io/docs/drivers/kvm2/

**Comment by runefs** [comment]
I no longer have an environment where I Can reproduce this 

Mvh
Rune
