### ISSUE TITLE
How can I analyse Minikube out of storage every 2 weeks ?

### ISSUE THREAD

**Issue by jotaoncode** [kubernetes/minikube#8422]
I have a local cluster with 2 PV

1 For a mysql dump with a 20Gb

1 For Mongo db with around 10Gb

A bunch of different services, mainly images around 400Mb or less, and 1 legacy of 2.1Gb image.

I am running Skaffold + Minikube + VirtualBox, in a OS Mojave

I get the following error from mysql:

```
2020-06-09T12:49:49.854701Z 0 [ERROR] InnoDB: Write to file ./ibtmp1failed at offset 0, 1048576 bytes should have been written, only 0 were written. Operating system error number 28. Check that your OS and file system support files of this size. Check also that the disk is not full or a disk quota exceeded.
2020-06-09T12:49:49.854724Z 0 [ERROR] InnoDB: Error number 28 means 'No space left on device'
```

Then I start looking at the current system memory, with this:

```
minikube ssh "free -mh"
```

And I get the following:

```
-------------total        used        free      shared  buff/cache   available
Mem:          7.8Gi       2.3Gi       2.4Gi       517Mi       3.1Gi       5.3Gi
```

I run the following command:

```
minikube ssh "df -h"
```

And I get the following:

```
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           7.1G  493M  6.6G   7% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           3.9G   26M  3.9G   1% /run
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
tmpfs           3.9G   12K  3.9G   1% /tmp
/dev/sda1        70G   69G     0 100% /mnt/sda1
/Users          234G  190G   44G  82% /Users
```
I see that `/mnt/sda1` could be the main problem, but I am not able to track down how did that sda1 got filled. How can I see the content /dev/sda1 and the possible guilty process that had filled this device?

I also did the following commands:

`docker image prune` To remove unused images
`docker volume prune` To remove unused volumes

I also run skaffold considering the documuntation with a cleanup:
`skaffoold -f="file-skaffold-config" --no-prune=false --cache-artifacts=false`

`docker rmi -f [IMAGE_ID]` to remove a particular image by ID and see if the removal of this image could eventually free some space in the /dev/sda1

But I cannot see a better situation with my sda1, meaning that `minikube ssh "df -h"` shows exactly the same results as before.

**How can I see with minikube / skaffold / docker what is filling up `/dev/sda1`?**

This is happening every 2 weeks approx, I fixed this by starting minikube again (process that takes about 1 hour to fill the DB) and giving a --disk-size of 80Gb, but now again it got filled out... even if I do it again with a 100Gb will fill again.

**How can I monitor this `/dev/sda1` so I know if this is an issue from Minikube with a local process or if it is my images that are not doing things right?**

Thanks in advance for the help

**Comment by afbjorklund** [comment]
Basically _everything_ in minikube is persisted on that `/dev/sda1`, which is your disk image file...

There are some details under https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/

For the virtualbox driver, you can normally find it here: ~/.minikube/machines/minikube/disk.vmdk

As you can see it is also mounted under `/mnt/sda1`, if you want to analyze the directories (`du`)

----

One tool that I find useful is called "SpaceRadar":  https://github.com/zz85/space-radar

It can read a file with such disk usage data, and make a graph visualizing the contents...

```
minikube ssh sudo du /mnt/sda1 > /tmp/minikube-du.txt
```

![space-radar-minikube-du](https://user-images.githubusercontent.com/10364051/84164922-60c97d80-aa73-11ea-8fed-631275b90967.png)

_(in my case it is mostly showing the docker images and the minikube binaries)_

**Comment by jotaoncode** [comment]
@afbjorklund this is certainly a nice tool to take a look, thanks. This is happening to one of my colleagues that hit this issue, and I was not able to help him properly.

So I guess my next steps would be to ask him to run this process (that I am trying to run now in my machine too with space radar) so we can see where is this issue coming from, and if there is an issue with Minikube I will open an issue a new one with more detail information.

Warm regards and thanks for the advice.

**Comment by jotaoncode** [comment]
Just in case anyone hit this problem I was able to analyse this issue the following way:

I compare my machine disk consumption in minikube with the one from my colleague:
(this is mine)
```
$ minikube ssh "sudo du -sh /mnt/sda1/*"
17G /mnt/sda1/data
4.0K    /mnt/sda1/hostpath-provisioner
4.0K    /mnt/sda1/hostpath_pv
16K /mnt/sda1/lost+found
46G /mnt/sda1/var

```
(this is hims)
```
34G /mnt/sda1/data
4.0K    /mnt/sda1/hostpath-provisioner
4.0K    /mnt/sda1/hostpath_pv
16K /mnt/sda1/lost+found
36G /mnt/sda1/var

```
Meaning that he had by a programmatic error we faced in the past and double sized of the PV with a backup database... This left out of space sd1, we where also able to see about space radar too as a cool solution to see results of consumption with the dump pointed out above.
