### ISSUE TITLE
virtualbox: A firewall is likely blocking

### ISSUE THREAD

**Issue by imsazzad** [kubernetes/minikube#8424]
**Steps to reproduce the issue:** 

1.minikube start --vm-driver virtualbox

**Full output of `minikube start` command used, if not already included:**

😄  minikube v1.10.0 on Ubuntu 20.04
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...

❌  [DOWNLOAD_IO_TIMEOUT] Failed to update cluster updating node: downloading binaries: downloading kubeadm: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.18.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.1/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.18.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.1/bin/linux/amd64/kubeadm.sha256 Dst:/home/mypcname/.minikube/cache/linux/v1.18.1/kubeadm.download Pwd: Mode:2 Detectors:[0x2b1e5f8 0x2b1e5f8 0x2b1e5f8 0x2b1e5f8 0x2b1e5f8 0x2b1e5f8] Decompressors:map[bz2:0x2b1e5f8 gz:0x2b1e5f8 tar.bz2:0x2b1e5f8 tar.gz:0x2b1e5f8 tar.xz:0x2b1e5f8 tbz2:0x2b1e5f8 tgz:0x2b1e5f8 txz:0x2b1e5f8 xz:0x2b1e5f8 zip:0x2b1e5f8] Getters:map[file:0xc000aaabe0 http:0xc00096a4e0 https:0xc00096a500] Dir:false ProgressListener:0x2af6dc0 Options:[0xc1e140]}: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/kubernetes-release/release/v1.18.1/bin/linux/amd64/kubeadm.sha256: net/http: TLS handshake timeout
💡  Suggestion: A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
📘  Documentation: https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/
⁉️   Related issue: https://github.com/kubernetes/minikube/issues/3846

I am new to kubernetis. Also I search the existing issues for example for proxies, start problem, download problem. But nothing works. Maybe I am missing a minor thing or may not be :)

**Comment by medyagh** [comment]
@imsazzad  it seems that you have network issues or don't have access to download the binaries

are you using minikube in a restricted network or a corp restriction? 
I would suggest trying to turn of the proxy or the VPN 
and also if you have docker installed, you could try the docker driver

you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

that would still not fix the connectivity issue but that would help with the VPN issue messing with the local network

**Comment by imsazzad** [comment]
thank you @medyagh .  unfortunately, I have tried all this. 
For example:
I tried with and without VPN. 
I found no firewall rule in IPtable
set the driver to docker and None both when starting minikube.
I am using minikube v1.10.0. So as you suggested I can update it. I can do this only for now.:(

**Comment by medyagh** [comment]
@imsazzad sorry to hear that are you using a corp network or a restricted network?

if you can not download this file, minikube wont able to work:
https://storage.googleapis.com/kubernetes-release/release/v1.18.1/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.1/bin/linux/amd64/kubeadm.sha256

**Comment by imsazzad** [comment]
yes. that's a good one, my friend. I can not download this file. how to verify if I am using a restricted network? one is, I cannot download this file, I guess :)

**Comment by imsazzad** [comment]
Now I got it. google storage API is blocked in my country. So I should use a VPN. Is this the only solution available?

**Comment by imsazzad** [comment]
Thank you. My country is Bangladesh. But I do not think, this is a permanent block in my country. May be due to coronavirus issue, the authority could not address this issue. Hopefully, it will be fixed soon.

**Comment by medyagh** [comment]
at this point I am not sure there is anything minikube do, minikube printed a solution message that 

```
💡 Suggestion: A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
📘 Documentation: https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/
⁉️ Related issue: #3846
```

I think it is better to find solution to solve the resrtrictions for each country
