### ISSUE TITLE
podman: load kic base image from cache if available for offline mode

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#8426]
This should be easier to implement once https://github.com/kubernetes/minikube/pull/8417 is merged

**Comment by cdbattags** [comment]
Any update on this?

**Comment by crfrolik** [comment]
Why is this issue closed?

This line of code still exists: https://github.com/kubernetes/minikube/blob/master/pkg/minikube/node/cache.go#L158

It prints when using podman:

> cache.go:203] Error downloading kic artifacts:  not yet implemented, see issue #8426

**Comment by iapicca** [comment]
since this issue is closed I'm opening a [new one](https://github.com/kubernetes/minikube/issues/14664)

**Comment by terjr938** [comment]
Still receiving the error, even though 8417 has been merged, or so it seems.  I'm attaching the requested logs.txt, so hopefully someone could take a look and let me know if it's a bug, because it sure seems like one.
[logs.txt](https://github.com/user-attachments/files/18378701/logs.txt)

**Comment by jogerj** [comment]
still not resolved but closed

https://github.com/kubernetes/minikube/blob/b973335449467dc12e23956be18336c42ff6b3ce/pkg/minikube/node/cache.go#L159-L161

**Comment by afbjorklund** [comment]
It got reverted, since #11063

**Comment by laundry-96** [comment]
Running into this issue now with Podman Desktop :(

@afbjorklund Sorry if you're the wrong person, but do you know if this will get re-fixed?

EDIT: Running `minikube start --driver podman` helped. I also set the default connection to the root one (not sure if that helped or not either)

**Comment by obnoxxx** [comment]
can this be reopened?
