### ISSUE TITLE
minikube does not start up properly anymore

### ISSUE THREAD

**Issue by joerg-pfruender** [kubernetes/minikube#843]
BUG REPORT

**Minikube does not display dashboard anymore.**

I am a beginner with minikube / kubernetes. I have tried to setup a service and messed it up. Then I have deleted the VM and tried to restart. The kubernetes dashbord does not start any more.

I started minikube with 

`minikube start --network-plugin=cni --container-runtime=rkt --iso-url=http://storage.googleapis.com/minikube/iso/buildroot/minikube-v0.0.6.iso`

I also tried to start without parameters, but the same issue.

extract of minikube logs: 
```
I1123 10:00:44.895950    3354 controller.go:105] Found 0 scheduledjobs
I1123 10:00:44.896839    3354 controller.go:113] Found 0 jobs
I1123 10:00:44.896850    3354 controller.go:116] Found 0 groups
E1123 10:00:53.455580    3354 kubelet.go:2132] Failed to check if disk space is available on the root partition: could not determine capacity for "root" fs. Info: {Usage:0 Capacity:0 Available:0 Timestamp:2016-11-23 10:00:53.455560196 +0000 UTC}
```

server stdout:
![auswahl_044](https://cloud.githubusercontent.com/assets/1325861/20557664/a99e0a84-b16c-11e6-95bb-6263769378a4.png)

**Minikube version**: v0.12.2
**Environment**:
- **OS**: Ubuntu 16.04 LTS
- **VM Driver**: Virtual Box 5.0.24_Ubuntu 3108355
- **Docker version**: Docker version 1.12.3, build 6b644ec
- **Install tools**:
- **Others**:
kubectl https://storage.googleapis.com/kubernetes-release/release/v1.3.0/bin/linux/amd64/kubectl

**What I already tried:**
- Delete vm
- minikube delete
- Delete the .kube and .minikube folders

The minikube log error message inicated that there was no space on the root partition. I attached a screenshot of the vbox machine that shows that there should be enough space.
![minikube](https://cloud.githubusercontent.com/assets/1325861/20557996/4b7f3296-b16e-11e6-822b-bfd80a1929dc.png)

**Comment by joerg-pfruender** [comment]
minikube dashboard says:

```
joerg@joergpfruendersThinkpad:~/ideaprojects/ep2/docker/kubernetes$ minikube dashboard
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Waiting, endpoint for service is not ready yet...
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: endpoints "kubernetes-dashboard" not found
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet
Temporary Error: Endpoint for service is not ready yet

```

**Comment by r2d4** [comment]
Can you do a `kubectl describe rc kubernetes-dashboard --namespace=kube-system` and `kubectl logs` on the corresponding pods?

**Comment by joerg-pfruender** [comment]
Like magically the dashboard now runs again...
I don't know why.

$ kubectl describe rc kubernetes-dashboard --namespace=kube-system
```
Name:		kubernetes-dashboard
Namespace:	kube-system
Image(s):	gcr.io/google_containers/kubernetes-dashboard-amd64:v1.4.2
Selector:	app=kubernetes-dashboard,kubernetes.io/cluster-service=true,version=v1.4.2
Labels:		app=kubernetes-dashboard
		kubernetes.io/cluster-service=true
		version=v1.4.2
Replicas:	1 current / 1 desired
Pods Status:	1 Running / 0 Waiting / 0 Succeeded / 0 Failed
No volumes.
No events.
```
On the dashboard I can see three pods:

![image](https://cloud.githubusercontent.com/assets/1325861/20889175/4926a626-bb02-11e6-8103-0866e97e7938.png)

On the dashboard I can only see the logs from today where everything seems fine. 
The command line shows no logs:

$ kubectl logs kubernetes-dashboard-2f06w
```
Error from server: pods "kubernetes-dashboard-2f06w" not found
```

Thank you for your support. I am sorry that I can not reproduce the bad situation.

**Comment by shoaibjdev** [comment]
Likely, it takes a couple of minutes to bring up the dashboard services. Thanks to @r2d4  (R2-D2) for sharing the command that helped in understanding and having patience while dashboard boots up.

**Comment by amingilani** [comment]
I'ver reproduced this. It happens when you have other docker containers running e.g. via docker-compose

**Comment by amingilani** [comment]
I take that back, it seems to be working again, despite using docker-compose.

**Comment by joan38** [comment]
I have the same issue, how did you solve yours?

**Comment by dkushner** [comment]
@joan38: Interesting, I am currently having this issue in 1.8.0 as well. Is this version just no longer supported by minikube? Kind of frustrated by this as I'm required to maintain compatibility with this version as it matches our GKE deployments.

**Comment by pavanbhosle** [comment]
I am still facing this issue. Please help.

![2](https://user-images.githubusercontent.com/37103675/37023976-a222f448-214d-11e8-9e6a-8ca00196345c.PNG)

**Comment by monte-hayward** [comment]
the solution here 
https://github.com/kubernetes/minikube/issues/2755#issuecomment-385624552
fixed both the dashboard and the issue described in [2755](https://github.com/kubernetes/minikube/issues/2755#issuecomment-385624552) for me.

```
minikube version: v0.27.0

kubectl version
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-04-27T09:22:21Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

```
