### ISSUE TITLE
Some repos are causing Curl error (60): Peer certificate cannot be authenticated 

### ISSUE THREAD

**Issue by ambition-consulting** [kubernetes/minikube#8436]
This is about the Minikube VirtualBox image issue causing errors on some installations:
https://github.com/quarkusio/quarkus/issues/9893

Does this maybe relate to update-crypto-policies set to FUTURE?
https://access.redhat.com/discussions/4524081

On runnin `echo '' | openssl s_client -connect cdn.redhat.com:443 2>/dev/null | openssl x509 -text -noout` I get (with minikube ssh):
unable to load certificate
139820647493504:error:09FFF06C:PEM routines:CRYPTO_internal:no start line:pem/pem_lib.c:684:Expecting: TRUSTED CERTIFICATE

**Comment by ambition-consulting** [comment]
Will test docker driver tomorrow, thanks for the suggestion.

Meanwhile I believe my first comment on crypto size is probably incorrect, since the failure mentioned in their forum says:
Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://cdn-ubi.redhat.com/content/public/ubi/dist/ubi8/8/x86_64/baseos/os/repodata/repomd.xml [SSL certificate problem: **unable to get local issuer certificate**]
Whereas mine:
Curl error (60): Peer certificate cannot be authenticated with given CA certificates for https://cdn.redhat.com/content/dist/rhel8/8/x86_64/baseos/os/repodata/repomd.xml [SSL certificate problem: **EE certificate key too weak**].

**Comment by medyagh** [comment]
cc: @afbjorklund

**Comment by ambition-consulting** [comment]
`C:\Users\f6sb0mx.GZS\src\config-quickstart
λ minikube start --driver=docker
* minikube v1.11.0 auf Microsoft Windows 7 Enterprise Service Pack 1 6.1.7601 Build 7601
  - MINIKUBE_ACTIVE_DOCKERD=minikube
* Using the docker driver based on user configuration

! 'docker' driver reported an issue: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: error during connect: Get http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.40/version: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
* Suggestion:
* Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/

X Failed to validate 'docker' driver`

Unfortunately, elevated permissions are not an option in our company....

**Comment by ambition-consulting** [comment]
Turns out, this was just another sniffing proxy problem...

**Comment by medyagh** [comment]
@ambition-consulting I am sorry that the solution message looks ugly in this error, we could sitll do a better job in solution message

**Comment by medyagh** [comment]
seems to be it is fixable by
"Reset to factory defaults..." under Settings > Reset.
 https://github.com/docker/for-win/issues/1825
