### ISSUE TITLE
Error getting cluster config: stat: stat /home/aunmarthcnc/.minikube/profiles/minikube/config.json: permission denied

### ISSUE THREAD

**Issue by aunrai** [kubernetes/minikube#8437]
**Steps to reproduce the issue:** 

1. sudo minikube start

2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Hey @aunrai  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!
