### ISSUE TITLE
impossible to start correctly ingress-controller addons on VM virtual box on Centos 7.8

### ISSUE THREAD

**Issue by llsn** [kubernetes/minikube#8438]
hello everybody,
this is my problem. I installed minikube on my VM centos 7.8 under virtualbox, i started my minikube with the command "minikube start --driver=none" and after i launched the command "minikube addons enable ingress". and this is the result:
[root@master-node ~]# kubectl get po --all-namespaces

NAMESPACE     NAME                                        READY   STATUS              RESTARTS   AGE
kube-system   coredns-66bff467f8-htf2f                    0/1     Running             0          5m54s
kube-system   coredns-66bff467f8-jkk9d                    0/1     Running             0          5m55s
kube-system   etcd-master-node                            1/1     Running             0          5m53s
kube-system   ingress-nginx-admission-create-b6d2q        0/1     **CrashLoopBackOff**    1          7s
kube-system   ingress-nginx-admission-patch-xkqt5         0/1     **CrashLoopBackOff**    1          7s
kube-system   ingress-nginx-controller-7bb4c67d67-tqvqx   0/1     **ContainerCreating**   0          7s
kube-system   kube-apiserver-master-node                  1/1     Running             0          5m53s
kube-system   kube-controller-manager-master-node         1/1     Running             0          5m53s
kube-system   kube-proxy-x2zkg                            1/1     Running             0          5m55s
kube-system   kube-scheduler-master-node                  1/1     Running             0          5m53s
kube-system   storage-provisioner                         1/1     Running             0          6m

when i launch the command `kubectl logs -n kube-system ingress-nginx-controller-7bb4c67d67-tqvqx`, i have the following result:
`[root@master-node ~]# kubectl logs -n kube-system ingress-nginx-controller-7bb4c67d67-tqvqx
Error from server (BadRequest): container "controller" in pod "ingress-nginx-controller-7bb4c67d67-tqvqx" is waiting to start: ContainerCreating`

any idea?

**Comment by priyawadhwa** [comment]
Hey @llsn  -- hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.


Thank you for sharing your experience!
