### ISSUE TITLE
Virtualization Enabled in BIOS, Hyper-V uninstalled | Windows10 

### ISSUE THREAD

**Issue by njohnjoel** [kubernetes/minikube#8442]
**Steps to reproduce the issue:** 

1. minikube start --vm-driver virtualbox
2. minikube start 
3. minikube start --alsologtostderr -v=5

**Full output of failed command:** 
$ minikube start --alsologtostderr -v=5
I0610 23:34:28.691235    1380 start.go:98] hostinfo: {"hostname":"DESKTOP-0E2F8V1","uptime":1574,"bootTime":1591810694,"procs":177,"os":"windows","platform":"
Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"","virtualizationSystem":"","v
irtualizationRole":"","hostid":"7b7d95f4-a16f-439f-8834-7ecf5bd37b8a"}
W0610 23:34:28.692241    1380 start.go:106] gopshost.Virtualization returned error: not implemented yet
* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
I0610 23:34:28.787597    1380 notify.go:125] Checking for updates...
W0610 23:34:28.790602    1380 start.go:562] selectDriver api.Load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to
list machines. Use "docker-machine create" to add a new one.
I0610 23:34:28.790602    1380 driver.go:253] Setting default libvirt URI to qemu:///system
W0610 23:34:28.792603    1380 start.go:562] selectDriver api.Load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to
list machines. Use "docker-machine create" to add a new one.
* Using the virtualbox driver based on existing profile
I0610 23:34:28.893591    1380 start.go:214] selected driver: virtualbox
I0610 23:34:28.893591    1380 start.go:611] validating driver "virtualbox" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://stor
age.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf
2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:
[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:
false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true H
ostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerI
Ps:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: L
oadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVe
rsion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0610 23:34:28.894591    1380 start.go:617] status for virtualbox: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0610 23:34:28.894591    1380 iso.go:118] acquiring lock: {Name:mk210261a3d2c8cc24123518f11c0bfe3e4559e1 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Starting control plane node minikube in cluster minikube
I0610 23:34:28.911628    1380 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0610 23:34:28.911628    1380 preload.go:103] Found local preload: C:\cygwin64\home\njohn\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-do
cker-overlay2-amd64.tar.lz4
I0610 23:34:28.912599    1380 cache.go:49] Caching tarball of preloaded images
I0610 23:34:28.912599    1380 preload.go:129] Found C:\cygwin64\home\njohn\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-a
md64.tar.lz4 in cache, skipping download
I0610 23:34:28.912599    1380 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0610 23:34:28.913598    1380 profile.go:156] Saving config to C:\cygwin64\home\njohn\.minikube\profiles\minikube\config.json ...
I0610 23:34:28.916598    1380 cache.go:152] Successfully downloaded all kic artifacts
I0610 23:34:28.918598    1380 start.go:240] acquiring machines lock for minikube: {Name:mk6acd5bbac1715a42e2d3f519568dc2383ff6bd Clock:{} Delay:500ms Timeout:
15m0s Cancel:<nil>}
I0610 23:34:28.918598    1380 start.go:244] acquired machines lock for "minikube" in 0s
I0610 23:34:28.919599    1380 start.go:84] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storag
e.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf27
55d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[]
 HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:fa
lse KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true Hos
tOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs
:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: Loa
dBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVers
ion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]} &{Name: IP: Port:8443 KubernetesVersion:v1.18.
3 ControlPlane:true Worker:true}
I0610 23:34:28.920616    1380 start.go:121] createHost starting for "" (driver="virtualbox")
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
I0610 23:34:28.954598    1380 start.go:157] libmachine.API.Create for "minikube" (driver="virtualbox")
I0610 23:34:28.954598    1380 client.go:161] LocalClient.Create starting
I0610 23:34:28.954598    1380 main.go:110] libmachine: Reading certificate data from C:\cygwin64\home\njohn\.minikube\certs\ca.pem
I0610 23:34:28.955592    1380 main.go:110] libmachine: Decoding PEM data...
I0610 23:34:28.955592    1380 main.go:110] libmachine: Parsing certificate...
I0610 23:34:28.955592    1380 main.go:110] libmachine: Reading certificate data from C:\cygwin64\home\njohn\.minikube\certs\cert.pem
I0610 23:34:28.955592    1380 main.go:110] libmachine: Decoding PEM data...
I0610 23:34:28.955592    1380 main.go:110] libmachine: Parsing certificate...
I0610 23:34:28.956595    1380 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
I0610 23:34:28.985594    1380 main.go:110] libmachine: STDOUT:
{
6.1.10r138449
}
I0610 23:34:28.985594    1380 main.go:110] libmachine: STDERR:
{
}
I0610 23:34:28.990591    1380 main.go:110] libmachine: Hyper-V is not installed.
%!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)
I0610 23:34:28.991596    1380 client.go:164] LocalClient.Create took 36.9988ms
I0610 23:34:30.992360    1380 start.go:124] duration metric: createHost completed in 2.0717441s
I0610 23:34:30.992360    1380 start.go:75] releasing machines lock for "minikube", held for 2.0737623s
I0610 23:34:31.005324    1380 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0610 23:34:31.005324    1380 delete.go:45] couldn't inspect container "minikube" before deleting: unknown state "minikube": docker container inspect minikube
 --format={{.State.Status}}: exec: "docker": executable file not found in %PATH%
stdout:

stderr:
I0610 23:34:31.018338    1380 cli_runner.go:108] Run: podman container inspect minikube --format={{.State.Status}}
I0610 23:34:31.019325    1380 delete.go:45] couldn't inspect container "minikube" before deleting: unknown state "minikube": podman container inspect minikube
 --format={{.State.Status}}: exec: "podman": executable file not found in %PATH%
stdout:

stderr:
W0610 23:34:31.020337    1380 start.go:359] delete host: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machi
ne create" to add a new one.
! StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
I0610 23:34:36.021524    1380 start.go:240] acquiring machines lock for minikube: {Name:mk6acd5bbac1715a42e2d3f519568dc2383ff6bd Clock:{} Delay:500ms Timeout:
15m0s Cancel:<nil>}
I0610 23:34:36.023504    1380 start.go:244] acquired machines lock for "minikube" in 0s
I0610 23:34:36.023504    1380 start.go:84] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storag
e.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf27
55d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[]
 HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:fa
lse KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true Hos
tOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs
:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: Loa
dBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVers
ion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]} &{Name: IP: Port:8443 KubernetesVersion:v1.18.
3 ControlPlane:true Worker:true}
I0610 23:34:36.025496    1380 start.go:121] createHost starting for "" (driver="virtualbox")
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
I0610 23:34:36.107483    1380 start.go:157] libmachine.API.Create for "minikube" (driver="virtualbox")
I0610 23:34:36.107483    1380 client.go:161] LocalClient.Create starting
I0610 23:34:36.107483    1380 main.go:110] libmachine: Reading certificate data from C:\cygwin64\home\njohn\.minikube\certs\ca.pem
I0610 23:34:36.108481    1380 main.go:110] libmachine: Decoding PEM data...
I0610 23:34:36.108481    1380 main.go:110] libmachine: Parsing certificate...
I0610 23:34:36.108481    1380 main.go:110] libmachine: Reading certificate data from C:\cygwin64\home\njohn\.minikube\certs\cert.pem
I0610 23:34:36.108481    1380 main.go:110] libmachine: Decoding PEM data...
I0610 23:34:36.108481    1380 main.go:110] libmachine: Parsing certificate...
I0610 23:34:36.109482    1380 main.go:110] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe --version
I0610 23:34:36.137492    1380 main.go:110] libmachine: STDOUT:
{
6.1.10r138449
}
I0610 23:34:36.137492    1380 main.go:110] libmachine: STDERR:
{
}
I0610 23:34:36.142479    1380 main.go:110] libmachine: Hyper-V is not installed.
%!(EXTRA *exec.Error=exec: "vmms.exe": executable file not found in %PATH%)
I0610 23:34:36.142479    1380 client.go:164] LocalClient.Create took 34.9966ms
I0610 23:34:38.142553    1380 start.go:124] duration metric: createHost completed in 2.1160527s
I0610 23:34:38.142553    1380 start.go:75] releasing machines lock for "minikube", held for 2.1190484s
* Failed to start virtualbox VM. "minikube start" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in
the BIOS is mandatory
I0610 23:34:38.144520    1380 exit.go:58] WithError(error provisioning host)=Failed to start host: creating host: create: precreate: This computer doesn't hav
e VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x18bd240)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc000769340)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc0005a44e0, 0x0, 0x2)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc0005a44c0, 0x2, 0x2, 0x2b6c200, 0xc0005a44c0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x20, 0xc0005a4080)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
*
* [VBOX_VTX_DISABLED] error provisioning host Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling
it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your sys
tems BIOS manual for how to enable virtualization.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900
  - https://github.com/kubernetes/minikube/issues/4730

**Full output of `minikube start` command used, if not already included:**
C:\>minikube start
* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start virtualbox VM. "minikube start" may fix it: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
*
* [VBOX_VTX_DISABLED] error provisioning host Failed to start host: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Suggestion: Virtualization support is disabled on your computer. If you are running minikube within a VM, try '--driver=docker'. Otherwise, consult your systems BIOS manual for how to enable virtualization.
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3900
  - https://github.com/kubernetes/minikube/issues/4730

**Optional: Full output of `minikube logs` command:**
C:\>minikube logs
* The control plane node "" does not exist.
  - To fix this, run: "minikube start"

C:\>

</details>

1. Hyper-V is uninstalled , VT-X/AMD-v enabled is enabled in BIOS
1. I wanted to install minikube, kubectl and VirtualBox 
2. I dont wanted to use hyperV as I am more comfortable to VirtualBox and have other machines running

**Comment by njohnjoel** [comment]
@medyagh 
Thanks for your time , I self fixed it , I Can help anyone who has such issues .

**Comment by shikhar4128** [comment]
hey @medyagh I am having this issue when trying to start minikube on virtualbox
minikube start --driver=virtualbox

getting below error:
this computer doesn't have vt-x/amd-v enabled. enabling it in the bios is mandatory

**Comment by LukBukkit** [comment]
I got the same problem and fixed by skipping this check
```ps1
minikube start --driver virtualbox --no-vtx-check
```
Altough the check fails, everything runs fine.

**Comment by spowelljr** [comment]
@shikhar4128 If @LukBukkit suggestion doesn't help, I recommend you create a new issue and reference this issue in it. This ticket has been closed for a while and your issue would get more visibility if you opened a new one.
