### ISSUE TITLE
ISO build is failing

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#8449]
I tried to release v1.12.0-beta.0 today, but the ISO build failed in Jenkins. Logs can be found [here](https://a646c87040050000000000000000001.proxy.googleprod.com/job/ISO/97/console):

In case anyone doesn't have access to those logs, I've copied the output below:
<details>
<pre>
17:22:17 scripts/Makefile.build:265: recipe for target '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/syscall_table.o' failed
17:22:17 make[8]: *** [/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/syscall_table.o] Error 1
17:22:17 ./include/net/sock.h: In function ‘sk_tx_queue_set’:
17:22:17 ././include/linux/compiler_types.h:210:24: error: expected ‘(’ before ‘__inline’
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/sock.h:1753:6: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17   if (WARN_ON_ONCE((unsigned short)tx_queue >= USHRT_MAX))
17:22:17       ^~~~~~~~~~~~
17:22:17 In file included from ./include/linux/bug.h:5:0,
17:22:17                  from ./include/linux/thread_info.h:12,
17:22:17                  from ./arch/x86/include/asm/preempt.h:7,
17:22:17                  from ./include/linux/preempt.h:78,
17:22:17                  from ./include/linux/spinlock.h:51,
17:22:17                  from ./include/linux/seqlock.h:36,
17:22:17                  from ./include/linux/time.h:6,
17:22:17                  from ./include/linux/compat.h:10,
17:22:17                  from /var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_events.c:12:
17:22:17 ./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17                       ^
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/sock.h:1753:6: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17   if (WARN_ON_ONCE((unsigned short)tx_queue >= USHRT_MAX))
17:22:17       ^~~~~~~~~~~~
17:22:17 In file included from <command-line>:0:0:
17:22:17 ././include/linux/compiler_types.h:210:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/sock.h:1753:6: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17   if (WARN_ON_ONCE((unsigned short)tx_queue >= USHRT_MAX))
17:22:17       ^~~~~~~~~~~~
17:22:17 ./include/net/sock.h: In function ‘sk_rx_queue_set’:
17:22:17 ././include/linux/compiler_types.h:210:24: error: expected ‘(’ before ‘__inline’
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/sock.h:1779:7: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17    if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
17:22:17        ^~~~~~~~~~~~
17:22:17 In file included from ./include/linux/bug.h:5:0,
17:22:17                  from ./include/linux/thread_info.h:12,
17:22:17                  from ./arch/x86/include/asm/preempt.h:7,
17:22:17                  from ./include/linux/preempt.h:78,
17:22:17                  from ./include/linux/spinlock.h:51,
17:22:17                  from ./include/linux/seqlock.h:36,
17:22:17                  from ./include/linux/time.h:6,
17:22:17                  from ./include/linux/compat.h:10,
17:22:17                  from /var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_events.c:12:
17:22:17 ./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17                       ^
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/sock.h:1779:7: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17    if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
17:22:17        ^~~~~~~~~~~~
17:22:17 In file included from <command-line>:0:0:
17:22:17 ././include/linux/compiler_types.h:210:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/sock.h:1779:7: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17    if (WARN_ON_ONCE(rx_queue == NO_QUEUE_MAPPING))
17:22:17        ^~~~~~~~~~~~
17:22:17 ./include/net/sock.h: In function ‘sock_graft’:
17:22:17 ././include/linux/compiler_types.h:210:24: error: expected ‘(’ before ‘__inline’
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17  #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
17:22:17                    ^~~~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
17:22:17    __WARN();      \
17:22:17    ^~~~~~
17:22:17 ./include/net/sock.h:1833:2: note: in expansion of macro ‘WARN_ON’
17:22:17   WARN_ON(parent->sk);
17:22:17   ^~~~~~~
17:22:17 In file included from ./include/linux/bug.h:5:0,
17:22:17                  from ./include/linux/thread_info.h:12,
17:22:17                  from ./arch/x86/include/asm/preempt.h:7,
17:22:17                  from ./include/linux/preempt.h:78,
17:22:17                  from ./include/linux/spinlock.h:51,
17:22:17                  from ./include/linux/seqlock.h:36,
17:22:17                  from ./include/linux/time.h:6,
17:22:17                  from ./include/linux/compat.h:10,
17:22:17                  from /var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_events.c:12:
17:22:17 ./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17                       ^
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17  #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
17:22:17                    ^~~~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
17:22:17    __WARN();      \
17:22:17    ^~~~~~
17:22:17 ./include/net/sock.h:1833:2: note: in expansion of macro ‘WARN_ON’
17:22:17   WARN_ON(parent->sk);
17:22:17   ^~~~~~~
17:22:17 In file included from <command-line>:0:0:
17:22:17 ././include/linux/compiler_types.h:210:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17  #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
17:22:17                    ^~~~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
17:22:17    __WARN();      \
17:22:17    ^~~~~~
17:22:17 ./include/net/sock.h:1833:2: note: in expansion of macro ‘WARN_ON’
17:22:17   WARN_ON(parent->sk);
17:22:17   ^~~~~~~
17:22:17 ./include/net/request_sock.h: In function ‘reqsk_free’:
17:22:17 ././include/linux/compiler_types.h:210:24: error: expected ‘(’ before ‘__inline’
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/request_sock.h:119:2: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17   WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
17:22:17   ^~~~~~~~~~~~
17:22:17 In file included from ./include/linux/bug.h:5:0,
17:22:17                  from ./include/linux/thread_info.h:12,
17:22:17                  from ./arch/x86/include/asm/preempt.h:7,
17:22:17                  from ./include/linux/preempt.h:78,
17:22:17                  from ./include/linux/spinlock.h:51,
17:22:17                  from ./include/linux/seqlock.h:36,
17:22:17                  from ./include/linux/time.h:6,
17:22:17                  from ./include/linux/compat.h:10,
17:22:17                  from /var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_events.c:12:
17:22:17 ./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17                       ^
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/request_sock.h:119:2: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17   WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
17:22:17   ^~~~~~~~~~~~
17:22:17 In file included from <command-line>:0:0:
17:22:17 ././include/linux/compiler_types.h:210:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:98:3: note: in expansion of macro ‘__WARN_FLAGS’
17:22:17    __WARN_FLAGS(BUGFLAG_ONCE |   \
17:22:17    ^~~~~~~~~~~~
17:22:17 ./include/net/request_sock.h:119:2: note: in expansion of macro ‘WARN_ON_ONCE’
17:22:17   WARN_ON_ONCE(refcount_read(&req->rsk_refcnt) != 0);
17:22:17   ^~~~~~~~~~~~
17:22:17 scripts/Makefile.build:265: recipe for target '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/main.o' failed
17:22:17 make[8]: *** [/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/main.o] Error 1
17:22:17 ./include/linux/ptrace.h: In function ‘ptrace_release_task’:
17:22:17 ././include/linux/compiler_types.h:210:24: error: expected ‘(’ before ‘__inline’
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, 0);     \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
17:22:17  #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
17:22:17                                                          ^~~
17:22:17 ./include/linux/ptrace.h:237:2: note: in expansion of macro ‘BUG_ON’
17:22:17   BUG_ON(!list_empty(&task->ptraced));
17:22:17   ^~~~~~
17:22:17 In file included from ./include/linux/bug.h:5:0,
17:22:17                  from ./include/linux/thread_info.h:12,
17:22:17                  from ./arch/x86/include/asm/preempt.h:7,
17:22:17                  from ./include/linux/preempt.h:78,
17:22:17                  from ./include/linux/spinlock.h:51,
17:22:17                  from ./include/linux/seqlock.h:36,
17:22:17                  from ./include/linux/time.h:6,
17:22:17                  from ./include/linux/compat.h:10,
17:22:17                  from /var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_events.c:12:
17:22:17 ./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17                       ^
17:22:17 ./arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, 0);     \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
17:22:17  #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
17:22:17                                                          ^~~
17:22:17 ./include/linux/ptrace.h:237:2: note: in expansion of macro ‘BUG_ON’
17:22:17   BUG_ON(!list_empty(&task->ptraced));
17:22:17   ^~~~~~
17:22:17 In file included from <command-line>:0:0:
17:22:17 ././include/linux/compiler_types.h:210:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, 0);     \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
17:22:17  #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
17:22:17                                                          ^~~
17:22:17 ./include/linux/ptrace.h:237:2: note: in expansion of macro ‘BUG_ON’
17:22:17   BUG_ON(!list_empty(&task->ptraced));
17:22:17   ^~~~~~
17:22:17 ././include/linux/compiler_types.h:210:24: error: expected ‘(’ before ‘__inline’
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, 0);     \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
17:22:17  #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
17:22:17                                                          ^~~
17:22:17 ./include/linux/ptrace.h:239:2: note: in expansion of macro ‘BUG_ON’
17:22:17   BUG_ON(!list_empty(&task->ptrace_entry));
17:22:17   ^~~~~~
17:22:17 In file included from ./include/linux/bug.h:5:0,
17:22:17                  from ./include/linux/thread_info.h:12,
17:22:17                  from ./arch/x86/include/asm/preempt.h:7,
17:22:17                  from ./include/linux/preempt.h:78,
17:22:17                  from ./include/linux/spinlock.h:51,
17:22:17                  from ./include/linux/seqlock.h:36,
17:22:17                  from ./include/linux/time.h:6,
17:22:17                  from ./include/linux/compat.h:10,
17:22:17                  from /var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_events.c:12:
17:22:17 ./arch/x86/include/asm/bug.h:35:22: error: expected identifier or ‘(’ before string constant
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17                       ^
17:22:17 ./arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, 0);     \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
17:22:17  #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
17:22:17                                                          ^~~
17:22:17 ./include/linux/ptrace.h:239:2: note: in expansion of macro ‘BUG_ON’
17:22:17   BUG_ON(!list_empty(&task->ptrace_entry));
17:22:17   ^~~~~~
17:22:17 In file included from <command-line>:0:0:
17:22:17 ././include/linux/compiler_types.h:210:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
17:22:17  #define asm_inline asm __inline
17:22:17                         ^
17:22:17 ./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
17:22:17   asm_inline volatile("1:\t" ins "\n"    \
17:22:17   ^~~~~~~~~~
17:22:17 ./arch/x86/include/asm/bug.h:73:2: note: in expansion of macro ‘_BUG_FLAGS’
17:22:17   _BUG_FLAGS(ASM_UD2, 0);     \
17:22:17   ^~~~~~~~~~
17:22:17 ./include/asm-generic/bug.h:62:57: note: in expansion of macro ‘BUG’
17:22:17  #define BUG_ON(condition) do { if (unlikely(condition)) BUG(); } while (0)
17:22:17                                                          ^~~
17:22:17 ./include/linux/ptrace.h:239:2: note: in expansion of macro ‘BUG_ON’
17:22:17   BUG_ON(!list_empty(&task->ptrace_entry));
17:22:17   ^~~~~~
17:22:17 scripts/Makefile.build:265: recipe for target '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_events.o' failed
17:22:17 make[8]: *** [/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_events.o] Error 1
17:22:17 scripts/Makefile.build:265: recipe for target '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_fillers.o' failed
17:22:17 make[8]: *** [/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src/ppm_fillers.o] Error 1
17:22:17 Makefile:1691: recipe for target '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src' failed
17:22:17 make[7]: *** [/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src] Error 2
17:22:17 make[7]: Leaving directory '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/linux-5.4.40'
17:22:17 Makefile:16: recipe for target 'all' failed
17:22:17 make[6]: *** [all] Error 2
17:22:17 make[6]: Leaving directory '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/driver/src'
17:22:17 driver/CMakeFiles/driver.dir/build.make:57: recipe for target 'driver/CMakeFiles/driver' failed
17:22:17 make[5]: *** [driver/CMakeFiles/driver] Error 2
17:22:17 make[5]: Leaving directory '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0'
17:22:17 CMakeFiles/Makefile2:501: recipe for target 'driver/CMakeFiles/driver.dir/all' failed
17:22:17 make[4]: *** [driver/CMakeFiles/driver.dir/all] Error 2
17:22:17 make[4]: Leaving directory '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0'
17:22:17 CMakeFiles/Makefile2:513: recipe for target 'driver/CMakeFiles/driver.dir/rule' failed
17:22:17 make[3]: *** [driver/CMakeFiles/driver.dir/rule] Error 2
17:22:17 make[3]: Leaving directory '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0'
17:22:17 Makefile:342: recipe for target 'driver' failed
17:22:17 make[2]: *** [driver] Error 2
17:22:17 make[2]: Leaving directory '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0'
17:22:17 package/pkg-generic.mk:266: recipe for target '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/.stamp_built' failed
17:22:17 make[1]: *** [/var/lib/jenkins/jobs/ISO/workspace/out/buildroot/output/build/falco-probe-0.21.0/.stamp_built] Error 2
17:22:17 make[1]: Leaving directory '/var/lib/jenkins/jobs/ISO/workspace/out/buildroot'
17:22:17 Makefile:202: recipe for target 'minikube_iso' failed
17:22:17 make: *** [minikube_iso] Error 2
17:22:17 Build step 'Execute shell' marked build as failure
17:22:17 Finished: FAILURE
</pre>
</details>

cc @afbjorklund it looks like something in the falco Makefile is broken, do you have any guidance here?

**Comment by afbjorklund** [comment]
I will take a look, maybe it needs upgrading

**Comment by afbjorklund** [comment]
It worked in Docker, seems unhappy on host. What OS are you running on the Jenkins ?

The Docker image uses `ubuntu:18.04` (while upstream use `debian:stretch-20171210`)

**Comment by afbjorklund** [comment]
@priyawadhwa : could it be that it is trying to re-use a workspace from previous ISO ?

Seems like `CONFIG_CC_HAS_ASM_INLINE` does not have the expected macro value...

**Comment by afbjorklund** [comment]
Upgraded falco (and the bundled sysdig) in PR #8450, hope that helps with the build

**Comment by afbjorklund** [comment]
The problem seems to be that the module uses `gcc` and not `x86_64-minikube-linux-gnu-gcc`

That means that it will use GCC 6.x instead of GCC 9.x, and run into the issues with the syntax.
