### ISSUE TITLE
Invald deployment patch in Ingress nginx tutorial

### ISSUE THREAD

**Issue by sepetrov** [kubernetes/minikube#8452]
Following the steps in the tutorial [Ingress nginx for TCP and UDP services](https://github.com/kubernetes/minikube/blob/6cdffd867f615a5448eef90a9ae8f7b4e344b10d/site/content/en/docs/tutorials/nginx_tcp_udp_ingress.md) there are two issues:

1. Invalid deployment name (fixed in #8451)
1. Invalid deployment patch

# Invalid deployment patch
After executing the command patching the deployment I received the following error:
```bash
$ cat ingress-nginx-controller-patch.yaml

spec:
  template:
    spec:
      containers:
      - name: ingress-nginx-controller
        ports:
         - containerPort: 6379
           hostPort: 6379

$ kubectl patch deployment ingress-nginx-controller --patch "$(cat ingress-nginx-controller-patch.yaml)" -n kube-system

The Deployment "ingress-nginx-controller" is invalid: spec.template.spec.containers[0].image: Required value
```

# minikube version

```bash
$ minikube version: v1.11.0

commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
```

**Comment by medyagh** [comment]
@epetrov which driver are you using ? 

the ingress tutotirals need to consolidated and fixed

**Comment by sepetrov** [comment]
> @epetrov which driver are you using ?

@medyagh, `virtualbox`

**Comment by sepetrov** [comment]
Looks like merging  #8451 closed this issue :(

**Comment by kirkre** [comment]
The name was fixed in the tutorial but not the Invalid deployment patch. Does anyone have a working deployment patch? I get the same error as sepetrov, and I am also using the same minikube version. Thanks.

**Comment by menems** [comment]
Hi it seems that now , the name of the deployment is "controller" not "ingress-nginx-controller"
```
spec:
  template:
    spec:
      containers:
      - name: controller
        ports:
         - containerPort: 6379
           hostPort: 6379
```
