### ISSUE TITLE
Unable to get host IP

### ISSUE THREAD

**Issue by 0x00-ketsu** [kubernetes/minikube#8459]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
Hi @0x00-ketsu. Can you provide some additional details for this issue? Can you provide your full `minikube start` command along with the output?

**Comment by medyagh** [comment]
@0x00-ketsu 
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

**Comment by sharifelgamal** [comment]
Hey @0x00-ketsu – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!
