### ISSUE TITLE
restarting minikube result in zookeeper pod crashing, due to not finding file "myid"

### ISSUE THREAD

**Issue by Hansen1-ELS** [kubernetes/minikube#8462]
**Steps to reproduce the issue:** 
1.
**:~$ minikube start --disk-size 80g --cpus 8 --memory 8192**
😄  minikube v1.11.0 on Ubuntu 18.04
✨  Automatically selected the docker driver. Other choices: kvm2, virtualbox
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=8, Memory=8192MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

2. **Deploy entire environment all is working perfect** 
**:~$ kubectl get pods** 
NAME                                                           READY   STATUS    RESTARTS   AGE
echelon-deployment-767cdf486c-5htc5                            1/1     Running   0          4m49s
manager-deployment-6f5d9f5b99-kxtx4                            1/1     Running   0          4m49s
postgres-operator-56455c9758-t5kjf                             1/1     Running   0          4m51s
recordlog-entity-operator-79998c5fc-8msrh                      3/3     Running   0          3m15s
recordlog-kafka-0                                              2/2     Running   0          3m55s
recordlog-postgres-cluster-0                                   1/1     Running   0          4m28s
recordlog-zookeeper-0                                          1/1     Running   0          4m26s
strimzi-cluster-operator-54565f8c56-kmth6                      1/1     Running   0          4m51s
submission-deployment-8684597b-bdwh5                           1/1     Running   0          4m50s

3.
**:~$ minikube stop**
✋  Stopping "minikube" in docker ...
🛑  Powering off "minikube" via SSH ...
🛑  Node "minikube" stopped.

4.
**:~$ minikube start**
😄  minikube v1.11.0 on Ubuntu 18.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

5. 
**:~$ kubectl get pods** 
NAME                                                           READY   STATUS             RESTARTS   AGE
echelon-deployment-767cdf486c-5htc5                            1/1     Running            1          35m
manager-deployment-6f5d9f5b99-kxtx4                            0/1     CrashLoopBackOff   10         35m
postgres-operator-56455c9758-t5kjf                             1/1     Running            2          35m
recordlog-entity-operator-79998c5fc-8msrh                      1/3     CrashLoopBackOff   24         34m
recordlog-kafka-0                                              1/2     CrashLoopBackOff   13         35m
recordlog-postgres-cluster-0                                   1/1     Running            1          35m
recordlog-zookeeper-0                                          0/1     CrashLoopBackOff   10         35m
strimzi-cluster-operator-54565f8c56-kmth6                      1/1     Running            2          35m
submission-deployment-8684597b-bdwh5                           1/1     Running            3          35m

I narroved it down to the zookeeper being the problem:

**:~$ kubectl logs recordlog-zookeeper-0 -f**
Detected Zookeeper ID 1
**mkdir: cannot create directory '/var/lib/zookeeper/data': Permission denied
/opt/kafka/zookeeper_run.sh: line 26: /var/lib/zookeeper/data/myid: No such file or directory**
Preparing truststore
Adding /opt/kafka/cluster-ca-certs/ca.crt to truststore /tmp/zookeeper/cluster.truststore.p12 with alias ca
Certificate was added to keystore
Preparing truststore is complete
Looking for the right CA
Found the right CA: /opt/kafka/cluster-ca-certs/ca.crt
Preparing keystore for client and quorum listeners
Preparing keystore for client and quorum listeners is complete
Starting Zookeeper with configuration:
# The directory where the snapshot is stored.
dataDir=/var/lib/zookeeper/data

# Zookeeper nodes configuration
server.1=recordlog-zookeeper-0.recordlog-zookeeper-nodes.recordlog.svc:2888:3888:participant;127.0.0.1:12181

mkdir: cannot create directory '/var/lib/zookeeper/logs': Permission denied
OpenJDK 64-Bit Server VM warning: If the number of processors is expected to increase from one, then you should configure the number of parallel GC threads appropriately using -XX:ParallelGCThreads=N
2020-06-12 12:37:02,408 INFO Reading configuration from: /tmp/zookeeper.properties (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-06-12 12:37:02,413 INFO clientPortAddress is 127.0.0.1:12181 (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-06-12 12:37:02,413 INFO secureClientPortAddress is 0.0.0.0:2181 (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
2020-06-12 12:37:02,416 INFO Setting -D jdk.tls.rejectClientInitiatedRenegotiation=true to disable client-initiated TLS renegotiation (org.apache.zookeeper.common.X509Util) [main]
2020-06-12 12:37:02,421 WARN No server failure will be tolerated. You need at least 3 servers. (org.apache.zookeeper.server.quorum.QuorumPeerConfig) [main]
Invalid config, exiting abnormally
2020-06-12 12:37:02,421 ERROR Invalid config, exiting abnormally (org.apache.zookeeper.server.quorum.QuorumPeerMain) [main]
org.apache.zookeeper.server.quorum.QuorumPeerConfig$ConfigException: Error processing /tmp/zookeeper.properties
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:156)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.initializeAndRun(QuorumPeerMain.java:113)
	at org.apache.zookeeper.server.quorum.QuorumPeerMain.main(QuorumPeerMain.java:82)
Caused by: java.lang.IllegalArgumentException: myid file is missing
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.checkValidity(QuorumPeerConfig.java:736)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.setupQuorumPeerConfig(QuorumPeerConfig.java:607)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parseProperties(QuorumPeerConfig.java:422)
	at org.apache.zookeeper.server.quorum.QuorumPeerConfig.parse(QuorumPeerConfig.java:152)

**Comment by afbjorklund** [comment]
Seems to be a permissions issue: 
`mkdir: cannot create directory '/var/lib/zookeeper/logs': Permission denied`

Similar to https://github.com/strimzi/strimzi-kafka-operator/issues/1720

**Comment by Hansen1-ELS** [comment]
Thanks @afbjorklund that lead to the answer.

Adding securityContext runAsUser and fsGroup did the trick.

`apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: recordlog
spec:
  kafka:
    version: 2.5.0
    replicas: 1
    listeners:
      plain: {}
      tls:
        authentication:
          type: tls
      external:
        type: nodeport
        tls: true
        authentication:
          type: tls
        overrides:
          bootstrap:
            nodePort: 32100
    authorization:
      type: simple
    config:
      offsets.topic.replication.factor: 1
      default.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.5"
      message.max.bytes: 10485760
      auto.create.topics.enable: false
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    template:
      pod:
        securityContext: #Be cerefull copying to staging and production as implications has not been checked.
          runAsUser: 0
          fsGroup: 0
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
    template:
      pod:
        securityContext:
          runAsUser: 0
          fsGroup: 0
  entityOperator:
    topicOperator: {}
    userOperator: {}`

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this since it seems to be resolved. Feel free to reopen if necessary.
