### ISSUE TITLE
Minikube failed on starting with docker as driver

### ISSUE THREAD

**Issue by bobmayuze** [kubernetes/minikube#8478]
`minikube start --driver=docker`
**Steps to reproduce the issue:** 

1. Open up terminal and run `minikube start --driver=docker`
2. It froze at line `🚜  Pulling base image ...`

My docker version:
```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:22:34 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:29:19 2019
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by bobmayuze** [comment]
It stuck there for about 5 mins, and it works.

**Comment by afbjorklund** [comment]
This is related to #7012, since it is download 300M

**Comment by bobmayuze** [comment]
Seems like once I deleted the minikube cluster, the image needs to be re-downloaded
