### ISSUE TITLE
Minikube does not start on windows 10

### ISSUE THREAD

**Issue by vvsh** [kubernetes/minikube#848]
**Minikube version** (use `minikube version`):

0.12.2

**Environment**:
- Windows 10 Pro
- Hyper V
- Docker: 1.12.3

**What happened**:

Starting local Kubernetes cluster...
Downloading Minikube ISO
 36.00 MB / 36.00 MB [==============================================] 100.00% 0s
E1123 22:23:23.260481    9008 start.go:92] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: open /Users/name/.minikube/cache/iso/minikube-0.7.iso: The system cannot find the path specified.. Retrying.
E1123 22:23:23.264494    9008 start.go:98] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: open /Users/name/.minikube/cache/iso/minikube-0.7.iso: The system cannot find the path specified.

**What you expected to happen**:

minikube is started

**Anything else do we need to know**:

docker works

**Comment by r2d4** [comment]
Are you trying to run minikube from a driver other than C?

This is an open issue https://github.com/kubernetes/minikube/issues/459#issuecomment-261806796

**Comment by vvsh** [comment]
Yes, but it is okay to me to run from C drive.
