### ISSUE TITLE
minikube dashboard not working : "message": "no endpoints available for service \"http:kubernetes-dashboard:\""

### ISSUE THREAD

**Issue by 9kranti** [kubernetes/minikube#8481]
When I hit `minikube dashboard` it opens dashboard for 12-15 minutes then started showing below error
![k8sDash](https://user-images.githubusercontent.com/61243923/84658497-9c60bd80-af33-11ea-9005-ddfabf4b5dfc.png)

kubernetes-dashboard pod is in CrashLoopBackOff
coredns pod is in CrashLoopBackOff

I described both the pod and in description got Node ip as below:
Node:                 minikube/192.168.99.102

For `minikube ip` got below ip:
192.168.99.100

Then again if I `stop` and `start` minikube then dashboard works fine for 15 minutes and then same error
But now minikube ip and Node: ip are same i.e. 192.168.99.100

Attaching events in describe of k8s dashboard pod
![eventsDash](https://user-images.githubusercontent.com/61243923/84664901-d5e9f680-af3c-11ea-9997-9171c21d8e7f.png)

OS Ubuntu 18.04
minikube version : v1.10.1

**Comment by priyawadhwa** [comment]
Hey @9kranti -- thanks for opening this issue. It looks like the pod sandbox is changed for some reason, causing the dashboard pod to restart.

I did some googling and it seems that this bug is usually CNI related. I'm not super familiar with CNI (cc @medyagh @tstromberg may know more)

Could you please let us know:

1. What OS and driver you're running minikube on 
1. What kubernetes version you're running 

Thank you!

**Comment by 9kranti** [comment]
Kubernetes version : 1.15.1

**Comment by 9kranti** [comment]
Anyone have any updates?

**Comment by sharifelgamal** [comment]
Yeah, the coredns pod crashing is usually very bad news. Have you tried upgrading your version of minikube and trying again. Also, which driver are you using? KVM, docker, virtualbox?

**Comment by priyawadhwa** [comment]
Hey @9kranti were you able to try upgrading?

**Comment by sharifelgamal** [comment]
Hey @9kranti – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
