### ISSUE TITLE
Add command for a "Getting Started" workshop using eduk8s as addon

### ISSUE THREAD

**Issue by blues-man** [kubernetes/minikube#8482]
/kind feature 

Hello,

I was thinking that it would be nice having a katacoda-like tutorial for beginners for local Kubernetes with Minikube, available from cli command and implemented as addon.

One good candidate for this could be creating an addon for [eduk8s](https://docs.eduk8s.io/en/latest/project-details/project-overview.html), a workshop framework installable via Operator and providing CR for creating interactive content, containing the [Kubernetes Foundamentals](https://github.com/eduk8s-labs/lab-k8s-fundamentals) 1h workshop (or creating a new one).

The flow would be similar to `minikube dashboard` command which activates dashboad addon, in this case it would be:

`$ minikube getstarted` 

or 

`$ minikube tutorial`

activating `eduk8s` addon or `getstarted` addon (containing eduk8s + workshop), opening the browser pointing to eduk8s ingress.

![eduk8s](https://docs.eduk8s.io/en/latest/_images/dashboard-terminal.png)

This would help people that'd love to learn Kubernetes doing it from their workstation with Minikube, having so a local persistent env were to execute exercises, and taking benefit from storage and ingress components already available, needed by the workshop framework in this case.

How does that sound?

**Comment by priyawadhwa** [comment]
Hey @blues-man thanks for opening this issue, I think this could be really cool. Would you be interested in first implementing this as an addon?  You can find docs around implementing addons [here](https://minikube.sigs.k8s.io/docs/contrib/addons/) and some recent example PRs adding other addons here: https://github.com/kubernetes/minikube/pull/8129

**Comment by blues-man** [comment]
Hi @priyawadhwa, thanks for the feedback! 

I'm discussing also with eduk8s folks for possibly collaborating on this, we would need to check couples of things like everything is fine their side, all software license involved are OK and workshops tuning for minikube.

I would be happy to contribute to the addon, I understood the mechanism from doc and previous contribution I did there, what I'm missing for this one, and I would like to discuss here, are points like:

* Is it possible to declare a dependency between addons? (this one would require `ingress` addon for instance, I haven't seen this possibility from the code, but there is a [validation block](https://github.com/kubernetes/minikube/blob/a47dc5ed8193fbd21923fad70889f38c96c39f87/pkg/addons/config.go#L57) that may be used for that?)
* At the moment the container image that would be used by the addon is above 500MB, if we would add a command like `minikube getstarted`, would be ok then, from user perspective, the waiting time of such container images download? At least for the first time it is invoked.

I would also add the also integration tests for this addon because the installation of the Operator and CRs for the Workshop are part of a sequence of tasks that need to be validated and consistent.

**Comment by priyawadhwa** [comment]
Hey @blues-man awesome! To address your questions:
1. Yup, the validation block is the best spot for this. If both aren't enabled, just return a clear message asking the user to enable both via:
```
minikube addons enable ingress
minikube addons enable eduk8s
```

or 

```
minikube start --addons=ingress,eduk8s
```
1. I think that should be fine

Sounds good! An integration test would be key here.
