### ISSUE TITLE
vbox  start: unable to find config.json

### ISSUE THREAD

**Issue by FunWithCode-hub** [kubernetes/minikube#8483]
Failed to start virtualbox VM. "minikube start" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\user s\.minikube\machines\minikube\config.json: The system cannot find the file specified. * X error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\user s\.minikube\machines\minikube\config.json: The system cannot find the file specified. * * minikube is exiting due to an error.

**Comment by priyawadhwa** [comment]
Hey @FunWithCode-hub thanks for opening this issue. It looks like minikube is expecting to find this file but is unable to:

```
C:\Users\user s.minikube\machines\minikube\config.json
```

Does that file exist?

If not, could you please try running:
```
minikube delete
minikube start
```

and if that also fails, please provide the output of `minikube logs`.

**Comment by sharifelgamal** [comment]
Hey @FunWithCode-hub  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!
