### ISSUE TITLE
Unable to start minikube-v1.11.0 on windows10

### ISSUE THREAD

**Issue by ashishsingh700** [kubernetes/minikube#8484]
**Steps to reproduce the issue:** 
Yesterday I was configured minilube on docker vm it was working. Today I try to start minikube but facing issue even I tried with docker as well.
1.minikube start --vm-driver=hyperv --force

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
 * minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363                                            * Using the hyperv driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.11.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.11.0.iso: 174.99 MiB / 174.99 MiB [] 100.00% 6.56 MiB p/s 27s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4: 526.01 MiB
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
E0615 16:09:29.698857   13512 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Ran out of memory (0x8007000E).
'minikube' failed to start. (Virtual machine ID 473CB868-0B98-41EC-B464-D25CF6EDB73A)
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. (Virtual machine
ID 473CB868-0B98-41EC-B464-D25CF6EDB73A)
'minikube' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID
473CB868-0B98-41EC-B464-D25CF6EDB73A)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM

* Stopping "minikube" in hyperv ...
* Deleting "minikube" in hyperv ...
! StartHost failed, but will try again: creating host: create: creating: exit status 1
* Failed to start hyperv VM. "minikube start" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\askusingh\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\askusingh\.minikube\machines\minikube\config.json: The system cannot find the file specified.

</details>

**Comment by priyawadhwa** [comment]
Hey @ashishsingh700 thanks for opening this issue. I noticed this error in the logs:

```
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. 
'minikube' could not initialize memory: Ran out of memory
```

it looks like you need to free up some memory on your machine, since minikube requires at least 2GB to run. 

If you have other minikube clusters running, you could try running:

```
minikube delete --all
```

which will delete all of your clusters.

You could also consider running,

```
docker system prune
```
which will delete all unused containers and images in your docker daemon.

Please let us know if this fixes the issue.

**Comment by ashishsingh700** [comment]
@priyawadhwa  I have tried above command as well no progress. My computer have 15 GM available space so required more ?
See below error when pointed to docker container
     C:\WINDOWS\system32> minikube start --vm-driver=docker --memory=2048 --cpus=1 --disk-size=5g --force
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the docker driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating docker container (CPUs=1, Memory=2048MB) ...
* Stopping "minikube" in docker ...
* Deleting "minikube" in docker ...
! StartHost failed, but will try again: creating host: create: creating: create kic node: check container "minikube" running: temporary error created container "minikube" is not running yet
* Creating docker container (CPUs=1, Memory=2048MB) ...
* Failed to start docker container. "minikube start" may fix it: creating host: create: creating: create kic node: check container "minikube" running: temporary error created container "minikube" is not running yet
*
X error provisioning host: Failed to start host: creating host: create: creating: create kic node: check container "minikube" running: temporary error created container "minikube" is not running yet
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose


See another error when execute below command

 minikube start --vm-driver=hyperv --hyperv-virtual-switch=Minikube --memory=2048 --cpus=1 --disk-size=5g --force                                                     * minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the hyperv driver based on user configuration                                                                                                                                        * Downloading VM boot image ...                                                                                                                                                                  > minikube-v1.11.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s                                                                                                                  > minikube-v1.11.0.iso: 174.99 MiB / 174.99 MiB  100.00% 2.17 MiB p/s 1m21s                                                                                                              * Starting control plane node minikube in cluster minikube                                                                                                                                   * Creating hyperv VM (CPUs=1, Memory=2048MB, Disk=5120MB) ...
E0616 17:48:05.217627   32980 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Ran out of memory (0x8007000E).
'minikube' failed to start. (Virtual machine ID 24C4AA52-17AB-4D98-AD0A-8955C0C13B28)
Not enough memory in the system to start the virtual machine minikube with ram size 2048 megabytes. (Virtual machine ID 24C4AA52-17AB-4D98-AD0A-8955C0C13B28)
'minikube' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID 24C4AA52-17AB-4D98-AD0A-8955C0C13B28)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM


* Stopping "minikube" in hyperv ...
* Deleting "minikube" in hyperv ...
! StartHost failed, but will try again: creating host: create: creating: exit status 1
* Creating hyperv VM (CPUs=1, Memory=2048MB, Disk=5120MB) ...
E0616 17:48:33.787206   32980 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Not enough memory in the system to start the virtual machine minikube.
Could not initialize memory: Ran out of memory (0x8007000E).
'minikube' failed to start. (Virtual machine ID 5B8DC6B1-F1ED-40CD-BAE6-894C5D5F5146)
Not enough memory in the system to start the virtual machine minikube with ram size 2048 megabytes. (Virtual machine ID 5B8DC6B1-F1ED-40CD-BAE6-894C5D5F5146)
'minikube' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID 5B8DC6B1-F1ED-40CD-BAE6-894C5D5F5146)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : FromStdErr: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OutOfMemory,Microsoft.HyperV.PowerShell.Commands.StartVM


* Failed to start hyperv VM. "minikube start" may fix it: creating host: create: creating: exit status 1
*
X error provisioning host: Failed to start host: creating host: create: creating: exit status 1
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
```
Not enough memory in the system to start the virtual machine minikube with ram size 2200 megabytes. 
'minikube' could not initialize memory: Ran out of memory
```

@ashishsingh700 do you mind sharing how much ram do you have on your comptuer?

**Comment by ashishsingh700** [comment]
@medyagh  8GB RAM , Every time I get different error . I am sure about it's not memory issue because I have seen many time it throw provisional ip address error as well even I execute minikube ip it return null .

I am frustrating to deal with window and minikube installation ,it just worked for me when I execute below command after that it's not working and come up with different error set.

minikube start --vm-driver=docker --force --extra-config=controller-manager.ClusterSigningCertFile="C:/Users/askusingh/.minikube/ca.pem" --extra-config=controller-manager.ClusterSigningKeyFile="C:/Users/askusingh/.minikube/key.pem"

**Comment by ashishsingh700** [comment]
When tried minikube start
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Automatically selected the docker driver
* Starting control plane node minikube in cluster minikube
* Creating docker container (CPUs=2, Memory=1991MB) ...
* Stopping "minikube" in docker ...
* Deleting "minikube" in docker ...
! StartHost failed, but will try again: creating host: create: creating: create kic node: check container "minikube" running: temporary error created container "minikube" is not running yet
* Creating docker container (CPUs=2, Memory=1991MB) ...
* Failed to start docker container. "minikube start" may fix it: creating host: create: creating: create kic node: check container "minikube" running: temporary error created container "minikube" is not running yet
*
X error provisioning host: Failed to start host: creating host: create: creating: create kic node: check container "minikube" running: temporary error created container "minikube" is not running yet

**Comment by ashishsingh700** [comment]
@priyawadhwa  It's working for me now. 
Could you please let me know what was the issue.
Thanks a lot :)
