### ISSUE TITLE
vmware: Host is not running

### ISSUE THREAD

**Issue by ntippabhatla** [kubernetes/minikube#8488]
**Steps to reproduce the issue:** 

1. I installed Vmware using homebrew and tried the command minikube start --driver=vmware 
2. But it says 🤦  **StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting**
3. I tried using virtual box and docker too as drivers it still failed. 
4. I am using a VPN and can't disable that and trying to do it locally on my computer.

**Full output of failed command:** 
I0615 18:11:53.917149    9931 start.go:98] hostinfo: {"hostname":"RRRRR","uptime":887035,"bootTime":1591372078,"procs":486,"os":"darwin","platform":"darwin","platformFamily":"","platformVersion":"10.15.4","kernelVersion":"19.4.0","virtualizationSystem":"","virtualizationRole":"","hostid":"ab0aa7ee-3d03-3c21-91ad-5719d79d7af6"}
W0615 18:11:53.917254    9931 start.go:106] gopshost.Virtualization returned error: not implemented yet
😄  minikube v1.11.0 on Darwin 10.15.4
I0615 18:11:53.939026    9931 notify.go:125] Checking for updates...
I0615 18:11:53.940007    9931 main.go:110] libmachine: Found binary path at /usr/local/bin/docker-machine-driver-vmware
I0615 18:11:53.940113    9931 main.go:110] libmachine: Launching plugin server for driver vmware
I0615 18:11:53.952160    9931 main.go:110] libmachine: Plugin server listening at address 127.0.0.1:53612
I0615 18:11:53.953000    9931 main.go:110] libmachine: () Calling .GetVersion
I0615 18:11:53.953540    9931 main.go:110] libmachine: Using API Version  1
I0615 18:11:53.953550    9931 main.go:110] libmachine: () Calling .SetConfigRaw
I0615 18:11:53.953850    9931 main.go:110] libmachine: () Calling .GetMachineName
I0615 18:11:53.953980    9931 main.go:110] libmachine: (minikube) Calling .DriverName
I0615 18:11:53.954096    9931 driver.go:253] Setting default libvirt URI to qemu:///system
I0615 18:11:53.954428    9931 main.go:110] libmachine: Found binary path at /usr/local/bin/docker-machine-driver-vmware
I0615 18:11:53.954468    9931 main.go:110] libmachine: Launching plugin server for driver vmware
I0615 18:11:53.964579    9931 main.go:110] libmachine: Plugin server listening at address 127.0.0.1:53618
I0615 18:11:53.965451    9931 main.go:110] libmachine: () Calling .GetVersion
I0615 18:11:53.966060    9931 main.go:110] libmachine: Using API Version  1
I0615 18:11:53.966080    9931 main.go:110] libmachine: () Calling .SetConfigRaw
I0615 18:11:53.966362    9931 main.go:110] libmachine: () Calling .GetMachineName
I0615 18:11:53.966561    9931 main.go:110] libmachine: (minikube) Calling .DriverName
✨  Using the vmware driver based on existing profile
I0615 18:11:53.982943    9931 start.go:214] selected driver: vmware
I0615 18:11:53.982982    9931 start.go:611] validating driver "vmware" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:4000 CPUs:2 DiskSize:20000 Driver:vmware HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0615 18:11:53.983407    9931 start.go:617] status for vmware: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0615 18:11:53.983717    9931 iso.go:118] acquiring lock: {Name:mkd44750c3977e2f59d746e7cb2b96d567b670b7 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
👍  Starting control plane node minikube in cluster minikube
I0615 18:11:54.001388    9931 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0615 18:11:54.001477    9931 preload.go:103] Found local preload: /Users/ntippabhatla/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0615 18:11:54.001529    9931 cache.go:49] Caching tarball of preloaded images
I0615 18:11:54.001574    9931 preload.go:129] Found /Users/ntippabhatla/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0615 18:11:54.001582    9931 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0615 18:11:54.001719    9931 profile.go:156] Saving config to /Users/ntippabhatla/.minikube/profiles/minikube/config.json ...
I0615 18:11:54.002644    9931 cache.go:152] Successfully downloaded all kic artifacts
I0615 18:11:54.002693    9931 start.go:240] acquiring machines lock for minikube: {Name:mk4a9d74a1bdb3da5c930f3529a0617e5c37e3b4 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0615 18:11:54.002864    9931 start.go:244] acquired machines lock for "minikube" in 146.995µs
I0615 18:11:54.002911    9931 start.go:88] Skipping create...Using existing machine configuration
I0615 18:11:54.002927    9931 fix.go:53] fixHost starting: 
I0615 18:11:54.003510    9931 main.go:110] libmachine: Found binary path at /usr/local/bin/docker-machine-driver-vmware
I0615 18:11:54.003548    9931 main.go:110] libmachine: Launching plugin server for driver vmware
I0615 18:11:54.015557    9931 main.go:110] libmachine: Plugin server listening at address 127.0.0.1:53623
I0615 18:11:54.016191    9931 main.go:110] libmachine: () Calling .GetVersion
I0615 18:11:54.016605    9931 main.go:110] libmachine: Using API Version  1
I0615 18:11:54.016621    9931 main.go:110] libmachine: () Calling .SetConfigRaw
I0615 18:11:54.016879    9931 main.go:110] libmachine: () Calling .GetMachineName
I0615 18:11:54.017016    9931 main.go:110] libmachine: (minikube) Calling .DriverName
I0615 18:11:54.017131    9931 main.go:110] libmachine: (minikube) Calling .GetState
I0615 18:11:54.017326    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:11:54.162248    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:11:54.165058    9931 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
I0615 18:11:54.165081    9931 main.go:110] libmachine: (minikube) Calling .DriverName
W0615 18:11:54.165224    9931 fix.go:131] unexpected machine state, will restart: <nil>
🔄  Restarting existing vmware VM for "minikube" ...
I0615 18:11:54.186363    9931 main.go:110] libmachine: (minikube) Calling .Start
I0615 18:11:54.186662    9931 main.go:110] libmachine: (minikube) Starting minikube...
I0615 18:11:54.186811    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun start /Users/ntippabhatla/.minikube/machines/minikube/minikube.vmx nogui
I0615 18:11:54.761723    9931 main.go:110] libmachine: (minikube) DBG | 2020-06-15T18:11:54.760| ServiceImpl_Opener: PID 9945
I0615 18:11:56.995720    9931 main.go:110] libmachine: (minikube) DBG | Error: The operation was canceled
I0615 18:11:56.998431    9931 main.go:110] libmachine: (minikube) Waiting for VM to come online...
I0615 18:11:56.998505    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:11:57.148867    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:11:57.151036    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 1/60, error: Host is not running
I0615 18:11:59.154436    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:11:59.300296    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:11:59.302882    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 2/60, error: Host is not running
I0615 18:12:01.304100    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:01.450601    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:01.453007    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 3/60, error: Host is not running
I0615 18:12:03.453968    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:03.623332    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:03.625794    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 4/60, error: Host is not running
I0615 18:12:05.629460    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:05.777026    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:05.779622    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 5/60, error: Host is not running
I0615 18:12:07.782696    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:07.927991    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:07.930509    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 6/60, error: Host is not running
I0615 18:12:09.932554    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:10.079225    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:10.081916    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 7/60, error: Host is not running
I0615 18:12:12.086619    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:12.233023    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:12.235611    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 8/60, error: Host is not running
I0615 18:12:14.240428    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:14.391751    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:14.394443    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 9/60, error: Host is not running
I0615 18:12:16.395541    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:16.542534    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:16.545005    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 10/60, error: Host is not running
I0615 18:12:18.547057    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:18.720914    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:18.723419    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 11/60, error: Host is not running
I0615 18:12:20.729810    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:20.879532    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:20.882407    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 12/60, error: Host is not running
ZI0615 18:12:22.885060    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:23.027948    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:23.030341    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 13/60, error: Host is not running
ZI0615 18:12:25.032418    9931 main.go:110] libmachine: (minikube) DBG | executing: /Applications/VMware Fusion.app/Contents/Public/vmrun list
I0615 18:12:25.182586    9931 main.go:110] libmachine: (minikube) DBG | Total running VMs: 0
I0615 18:12:25.185017    9931 main.go:110] libmachine: (minikube) DBG | Not there yet 14/60, error: Host is not running
^Z

###################################################

ntippabhatla@RRRRR ~ % minikube start --driver=docker
😄  minikube v1.11.0 on Darwin 10.15.4
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🤦  StartHost failed, but will try again: boot lock: timeout acquiring mutex
😿  Failed to start docker container. "minikube start" may fix it: boot lock: timeout acquiring mutex

💣  error provisioning host: Failed

**Comment by medyagh** [comment]
@ntippabhatla if you are using VPN u should be able to use docker driver

do you mind trying docker driver again (it seems like it was a bad luck mutex race in your case)

minikube delete
and can you please provide the full output of 
```
minikube start --driver=docker --alsologtostderr -v=8
```

**Comment by ntippabhatla** [comment]
Hey @medyagh , tried shutting the laptop once and tried the command you provided. Its working.
🏄  Done! kubectl is now configured to use "minikube".
Thanks for the help..!

**Comment by ntippabhatla** [comment]
Hey, so I realized yesterday that only after going through the docker desktop and then enabling the kubernetes option on the docker dashboard has helped me get a success of the command. Otherwise when I unchecked that option and tried running hte command again it gives the below log and nothing else. Can you please explain why is it so?  


I0616 13:33:47.689436    9185 start.go:98] hostinfo: {"hostname":"C02ZN0RFLVDM","uptime":62009,"bootTime":1592266818,"procs":409,"os":"darwin","platform":"darwin","platformFamily":"","platformVersion":"10.15.4","kernelVersion":"19.4.0","virtualizationSystem":"","virtualizationRole":"","hostid":"ab0aa7ee-3d03-3c21-91ad-5719d79d7af6"}
W0616 13:33:47.689589    9185 start.go:106] gopshost.Virtualization returned error: not implemented yet
😄  minikube v1.11.0 on Darwin 10.15.4
I0616 13:33:47.711848    9185 driver.go:253] Setting default libvirt URI to qemu:///system
I0616 13:33:47.711855    9185 notify.go:125] Checking for updates...
I0616 13:33:47.766614    9185 docker.go:95] docker version: linux-19.03.8
✨  Using the docker driver based on user configuration
I0616 13:33:47.781888    9185 start.go:214] selected driver: docker
I0616 13:33:47.781906    9185 start.go:611] validating driver "docker" against <nil>
I0616 13:33:47.781919    9185 start.go:617] status for docker: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0616 13:33:47.781944    9185 start.go:935] auto setting extra-config to "kubeadm.pod-network-cidr=10.244.0.0/16".
I0616 13:33:47.782015    9185 start_flags.go:218] no existing cluster config was found, will generate one from the flags 
I0616 13:33:47.782149    9185 cli_runner.go:108] Run: docker system info --format "{{json .}}"
I0616 13:33:48.062189    9185 start_flags.go:232] Using suggested 1991MB memory alloc based on sys=16384MB, container=1991MB
I0616 13:33:48.062284    9185 start_flags.go:556] Wait components to verify : map[apiserver:true system_pods:true]
👍  Starting control plane node minikube in cluster minikube
I0616 13:33:48.080115    9185 cache.go:105] Beginning downloading kic artifacts for docker with docker
I0616 13:33:48.133504    9185 image.go:88] Found gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 in local docker daemon, skipping pull
I0616 13:33:48.133554    9185 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0616 13:33:48.133601    9185 preload.go:103] Found local preload: /Users/ntippabhatla/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0616 13:33:48.133609    9185 cache.go:49] Caching tarball of preloaded images
I0616 13:33:48.133621    9185 preload.go:129] Found /Users/ntippabhatla/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0616 13:33:48.133625    9185 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0616 13:33:48.133882    9185 profile.go:156] Saving config to /Users/ntippabhatla/.minikube/profiles/minikube/config.json ...
I0616 13:33:48.134033    9185 lock.go:35] WriteFile acquiring /Users/ntippabhatla/.minikube/profiles/minikube/config.json: {Name:mkfde845bc87b5fcbde7f85882a4a506850c2c6d Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0616 13:33:48.134386    9185 cache.go:152] Successfully downloaded all kic artifacts
I0616 13:33:48.134411    9185 start.go:240] acquiring machines lock for minikube: {Name:mk4a9d74a1bdb3da5c930f3529a0617e5c37e3b4 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}`

**Comment by priyawadhwa** [comment]
Hey @ntippabhatla I'm not sure why this would be happening -- does running:

```
rm /Users/ntippabhatla/.minikube/profiles/minikube/config.json
minikube delete
minikube start --driver docker
```
fix it?

**Comment by ntippabhatla** [comment]
So in the docker desktop it says kubernetes is running with the help of  minikube itself, and also I tried to get-contexts and it shows minikube itself. So my doubt is when we are using docker as a driver, do we need to enable k8 in docker desktop? If that is not neccessary then until and unless I do that I am unable to run teh minikube start --driver=docker command successfully.

**Comment by medyagh** [comment]
@ntippabhatla docker desktop's kubernetes is different than minikube's kuberentes, I recommend only use one of them at same time to not be mixed up

**Comment by ntippabhatla** [comment]
I tried using only docker desktop's kubernetes and it is working. But when I disable the K8 option in the docker desktop, and try to run it using minikube it fails and is usually a timeout log that I have posted earlier. Also I tried @priyawadhwa but it says there is no such file.

**Comment by ntippabhatla** [comment]
This is something I am able to do. Is this okay. [https://blog.duaneleem.com/installing-kubernetes-with-docker/]

**Comment by ntippabhatla** [comment]
[](https://blog.duaneleem.com/installing-kubernetes-with-docker/)

**Comment by priyawadhwa** [comment]
Hey @ntippabhatla that seems correct! Are you still seeing any issues?

**Comment by ntippabhatla** [comment]
Hey @priyawadhwa thanks for letting me know, but one problem I observed is that so whenever I shut down the computer and try to start minikube its working. But when I delete a minikube cluster and then try to restart it again using docker as driver, it again fails not sure what wrong I am doing here.

**Comment by ntippabhatla** [comment]
~ % kubectl run yo --image mongo
pod/yo created
~ % kubectl create deployment yoo --image mongo
deployment.apps/yoo created

Also why does these two commands say two different things, when it is said in the documentation [https://kubernetes.io/docs/concepts/overview/working-with-objects/object-management/](url) , that both of them are supposed to create a deployment instead of a pod?

**Comment by sharifelgamal** [comment]
deployments create pods under the hood, at the end of the day all you're doing is creating pods with either of those commands.
