### ISSUE TITLE
docker: Error response from daemon: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available.

### ISSUE THREAD

**Issue by aamirashid** [kubernetes/minikube#8497]
docker: Error response from daemon: Range of CPUs is from 0.01 to 1.00, as there are only 1 CPUs available.

**Comment by priyawadhwa** [comment]
Hey @aamirashid minikube requires a minimum of 2 CPUs to run, and it seems that only 1 is available in your docker daemon. Is there any chance you could increase the CPUs to 2?

**Comment by afbjorklund** [comment]
This _could_ have a nicer message, like it does for the other drivers ? (same as #7850)

**Comment by medyagh** [comment]
kuberentes needs at least 2 CPUS, @aamirashid 

do you mind sharing the full output of the start
minikube start --driver=docker --alsologtostderr -v=8

we could still provide a better solution message
