### ISSUE TITLE
DNS Resolution Not Working Inside of Cluster

### ISSUE THREAD

**Issue by frankgreco** [kubernetes/minikube#850]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

**minikube version:** v0.12.2

**Environment**:
- **OS**: OS X El Capitan Version 10.11.6
- **VM Driver**: VirtualBox
- **Docker version**: Docker version 1.12.3, build 6b644ec, experimental

**What happened**:
I have a node microservice running in one pod with a `ClusterIP` and then I have have an nginx pod that serves as the entrypoint into the cluster via `NodePort`. Inside of my nginx config, I am doing a proxy pass using the service name to direct traffic to the other pod in my cluster.

What I hit the endpoint and check the logs of the nginx pod, I get the following: 
```
2016-11-24T15:53:09.723018746Z nginx: [emerg] host not found in upstream "algorithm" in /etc/nginx/nginx.conf:17
```

Other interesting logs:

```
kubectl logs --namespace=kube-system $(kubectl get pods --namespace=kube-system -l k8s-app=kube-dns -o name) -c kubedns
```

```
E1124 15:45:39.081743       1 reflector.go:311] pkg/dns/dns.go:155: Failed to watch *api.Service: Get https://10.0.0.1:443/api/v1/watch/services?resourceVersion=13076&timeoutSeconds=588: dial tcp 10.0.0.1:443: getsockopt: connection refused
E1124 15:45:39.072328       1 reflector.go:311] pkg/dns/dns.go:154: Failed to watch *api.Endpoints: Get https://10.0.0.1:443/api/v1/watch/endpoints?resourceVersion=13327&timeoutSeconds=302: dial tcp 10.0.0.1:443: getsockopt: connection refused
E1124 15:45:40.093406       1 reflector.go:214] pkg/dns/dns.go:155: Failed to list *api.Service: Get https://10.0.0.1:443/api/v1/services?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
E1124 15:45:40.094189       1 reflector.go:214] pkg/dns/dns.go:154: Failed to list *api.Endpoints: Get https://10.0.0.1:443/api/v1/endpoints?resourceVersion=0: dial tcp 10.0.0.1:443: getsockopt: connection refused
W1124 16:01:11.812204       1 reflector.go:330] pkg/dns/dns.go:155: watch of *api.Service ended with: too old resource version: 14345 (15561)
W1124 16:11:11.912918       1 reflector.go:330] pkg/dns/dns.go:155: watch of *api.Service ended with: too old resource version: 15562 (16683)
W1124 16:21:12.079413       1 reflector.go:330] pkg/dns/dns.go:155: watch of *api.Service ended with: too old resource version: 16684 (17801)
W1124 16:31:12.222596       1 reflector.go:330] pkg/dns/dns.go:155: watch of *api.Service ended with: too old resource version: 17802 (18917)
W1124 16:41:12.412182       1 reflector.go:330] pkg/dns/dns.go:155: watch of *api.Service ended with: too old resource version: 18918 (20033)
```

Here are the necessary configuration files.

Kubernetes.yml:
```yaml
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: algorithm
  name: algorithm
  namespace: ai-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: algorithm
  template:
    metadata:
      labels:
        app: algorithm
    spec:
      containers:
      - name: algorithm
        image: fbgrecojr/kubernetes-algorithm
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: algorithm
  name: algorithm
  namespace: ai-challenge
spec:
  type: ClusterIP
  ports:
  - port: 80
  selector:
    app: algorithm

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: ai-challenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: fbgrecojr/kubernetes-nginx
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP

---

kind: Service
apiVersion: v1
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: ai-challenge
spec:
  type: NodePort
  ports:
  - port: 80
  selector:
    app: nginx
```

Nginx.conf:
```
worker_processes 1;

events {
    worker_connections 1024;
}

http {

    server_tokens off;

    server {
        listen       80 default_server;
        listen       [::]:80 default_server;
        server_name  _80;

        location /algorithmservice/ {
            proxy_pass http://algorithm/;
        }
    }
}
```
 
**What you expected to happen**:
I expected the dns name `algorithm` to resolve in the Nginx upstream.

**How to reproduce it** (as minimally and precisely as possible):
1. Install everything using the versions above.
2. Create your cluster using the above config
3.  ```curl http://$(minikube ip):$(kubectl get service nginx --namespace=ai-challenge -o jsonpath='{.spec.ports[*].nodePort}')/algorithmservice/algorithms/test```

**Comment by r2d4** [comment]
Can you try to use the DNS record `algorithm.default.svc.cluster.local`? 
http://kubernetes.io/docs/admin/dns/

**Comment by frankgreco** [comment]
I tried with `algorithm.ai-challenge.svc.cluster.local` as the namespace is `ai-challenge` and still no luck. What is more concerning is that if I spin up the kubernetes recommended busybox:

`kubectl run -i --tty busybox --image=busybox --generator="run-pod/v1"`

I can not even resolve `nslookup kubernetes.default` which should always work.

New minimal steps to reproduce:
1. minikube create
2. Verify dns is enabled by `minikube addons list`
2. `kubectl run -i --tty busybox --image=busybox --generator="run-pod/v1"`
3. `nslookup kubernetes.default`

**Comment by frankgreco** [comment]
After not being after to even to an `nslookup kubernetes.default` I know something was broken and so I delete minikube and restarted it. It works as expected now.
