### ISSUE TITLE
issue my systemc

### ISSUE THREAD

**Issue by srronak** [kubernetes/minikube#8504]
![image](https://user-images.githubusercontent.com/50905840/84873868-7bb67600-b0a1-11ea-8b56-b7566d1602c6.png)

why i am getting this error anybody can help me out

**Comment by priyawadhwa** [comment]
Hey @srronak the error "%1 is not a valid Win32 application"

makes me think that you have a corrupt kubectl.exe binary which can't be run for some reason.

Are you able to run `kubectl get po -A` successfully?

You may have to reinstall your `kubectl` binary if not

**Comment by joshuabeny1999** [comment]
I have same issue. I installed minikube via chocolatley as recommended on kubernetes.io and then ran minikube start to set it up with Hyper-V. I have Windows 10 Pro. 

![image](https://user-images.githubusercontent.com/55023662/88037425-28729000-cb45-11ea-81c2-89432c8fb8a2.png)

**Comment by joshuabeny1999** [comment]
Never mind. I found the problem. I had a kubectl.exe inside my Homedirectory: C:/Users/joshu. And minikube tried to use this one. And it was not executeable. I deleted it and now everything works.

**Comment by medyagh** [comment]
glad to see it was solved
