### ISSUE TITLE
minikube nfs mount / bad option & no /sbin/mount.nfs binary

### ISSUE THREAD

**Issue by matclab** [kubernetes/minikube#8514]
Output of minikube start:
```
LC_ALL=C minikube start
😄  minikube v1.10.1 on Arch rolling
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
```

**Steps to reproduce the issue:** 

1.  set up an `nfs-server-provisioner` via the associated helm chart (the provisioner pod starts as expected)
2. use the persistent volume on another pod
  The mount fails with the following error: 
```
│ Mounting command: systemd-run                                                                                                                                                               │
│ Mounting arguments: --description=Kubernetes transient mount for /var/lib/kubelet/pods/a6722f0c-1ed1-43bb-bbec-09f8e703321c/volumes/kubernetes.io~nfs/pvc-41a43eff-3af5-41db-961d-ef5e26b55 │
│ 0d5 --scope -- mount -t nfs -o vers=3 10.96.115.121:/export/pvc-41a43eff-3af5-41db-961d-ef5e26b550d5 /var/lib/kubelet/pods/a6722f0c-1ed1-43bb-bbec-09f8e703321c/volumes/kubernetes.io~nfs/p │
│ vc-41a43eff-3af5-41db-961d-ef5e26b550d5                                                                                                                                                     │
│ Output: Running scope as unit: run-ra1e3354346fd4f82bc3b099f73d9a56b.scope                                                                                                                  │
│ mount: /var/lib/kubelet/pods/a6722f0c-1ed1-43bb-bbec-09f8e703321c/volumes/kubernetes.io~nfs/pvc-41a43eff-3af5-41db-961d-ef5e26b550d5: bad option; for several filesystems (e.g. nfs, cifs)  │
│ you might need a /sbin/mount.<type> helper program.                                                                                                                                         │
│   Warning  FailedMount  29m  kubelet, minikube  MountVolume.SetUp failed for volume "pvc-41a43eff-3af5-41db-961d-ef5e26b550d5" : mount failed: exit status 32
```
3.  And after running `minikube ssh` it looks like there is no `/sbin/mount.nfs` command.

As suggested on the user mailing list, I tried starting minikube with `minikube start --vm` but it didn't seem to  change  anything, neither on the output of the `start` command, neither on the error when trying to mount the nfs share.

**Comment by afbjorklund** [comment]
We need to add the `nfs-common` (the NFS client) to the kicbase, and "hope" that the user's kernel has NFS support

**Comment by afbjorklund** [comment]
The workaround meanwhile would be using `minikube ssh` and doing a `sudo apt update && sudo apt install -y nfs-common`

**Comment by matclab** [comment]
> The workaround meanwhile would be using `minikube ssh` and doing a `sudo apt update && sudo apt install -y nfs-common`

I first tried without the `apt update` and failed to understand why it didn't work. Thank you very much for the detail workaround which seems to work fine !

(I still have the problem that it tries to mount with `vers=3` option when only `vers=4` is supported, but it is probably a missing `mountOptions` in my helm chart).

**Comment by rajitha1998** [comment]
> The workaround meanwhile would be using `minikube ssh` and doing a `sudo apt update && sudo apt install -y nfs-common`

For "none drive", running `sudo apt update && sudo apt install -y nfs-common ` on your local machine terminal is sufficient.
