### ISSUE TITLE
wsl: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

### ISSUE THREAD

**Issue by ckvtvm-arch** [kubernetes/minikube#8515]
**Steps to reproduce the issue:** 

1. open Ubuntu 16.04 terminal in windows.
2. Docker run hello world  - Hello from Docker! - This message shows that your installation appears to be working correctly
2. .minikube start driver=docker
 

 docker: Not healthy: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Optional: Full output of `minikube logs` command:**
 W0619 11:51:10.624196     103 root.go:252] Error reading config file at /home/centy/.minikube/config/config.json: open /home/centy/.minikube/config/config.json: no such file or directory
I0619 11:51:10.696806     103 start.go:98] hostinfo: {"hostname":"L5PXPQN2","uptime":2476,"bootTime":1592579394,"procs":21,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"16.04","kernelVersion":"4.4.0-17763-Microsoft","virtualizationSystem":"","virtualizationRole":"","hostid":"dc8f3018-c094-40f2-a6ee-7579fb08bfc4"}
I0619 11:51:10.703200     103 start.go:108] virtualization:
😄  minikube v1.11.0 on Ubuntu 16.04
I0619 11:51:10.712167     103 driver.go:253] Setting default libvirt URI to qemu:///system
I0619 11:51:10.712657     103 global.go:102] Querying for installed drivers using PATH=/home/centy/.minikube/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu16.04onWindows_1604.2019.523.0_x64__79rhkp1fndgsc:/mnt/c/Users/AF71194/AppData/Roaming/npm:/mnt/c/Program Files/Java/jdk-14/bin:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/ManagementStudio:/mnt/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/mnt/c/Program Files/Microsoft SQL Server/120/DTS/Binn:/mnt/c/Users/AF71194/AppData/Roaming/npm:/mnt/c/Program Files/Java/jdk-14/bin:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/110/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn/ManagementStudio:/mnt/c/Program Files (x86)/Microsoft SQL Server/120/Tools/Binn:/mnt/c/Program Files/Microsoft SQL Server/120/Tools/Binn:/mnt/c/Program Files (x86)/Microsoft SQL Server/120/DTS/Binn:/mnt/c/Program Files/Microsoft SQL Server/120/DTS/Binn:/mnt/c/Program Files/Amazon/AWSCLI/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/AF71194/AppData/Local/terraform/bin:/mnt/c/Maven/apache-maven-3.6.2/bin:/mnt/c/oc-cli:/mnt/c/Program Files/Amazon/AWSCLI:/mnt/c/Program Files/Amazon/AWSCLI:/mnt/c/Users/AF71194/AppData/Roaming/Python/Python38/Scripts:/mnt/c/cwRsync_5.4.1_x86_Free:/mnt/c/Users/AF71194/AppData/Local/Programs/Python/Python38-32/Scripts:/mnt/c/Users/AF71194/AppData/Local/Programs/Python/Python38-32:/mnt/c/Program Files/nodejs:/mnt/c/Users/AF71194/AppData/Local/GitHubDesktop/bin:/mnt/c/Applications/Atlassian/atlassian-plugin-sdk-6.3.6/bin:/mnt/c/Users/AF71194/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/Java/jdk-14.0.1/bin:/mnt/c/Program Files/Amazon/AWSCLI/bin:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/AF71194/AppData/Local/terraform/bin:/mnt/c/Maven/apache-maven-3.6.2/bin:/mnt/c/oc-cli:/mnt/c/Program Files/Amazon/AWSCLI:/mnt/c/Program Files/Amazon/AWSCLI:/mnt/c/Users/AF71194/AppData/Roaming/Python/Python38/Scripts:/mnt/c/cwRsync_5.4.1_x86_Free:/mnt/c/Users/AF71194/AppData/Local/Programs/Python/Python38-32/Scripts:/mnt/c/Users/AF71194/AppData/Local/Programs/Python/Python38-32:/mnt/c/Program Files/nodejs:/mnt/c/Users/AF71194/AppData/Local/GitHubDesktop/bin:/mnt/c/Applications/Atlassian/atlassian-plugin-sdk-6.3.6/bin:/mnt/c/Users/AF71194/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Program Files/Java/jdk-14.0.1/bin:/snap/bin
I0619 11:51:10.713934     103 notify.go:125] Checking for updates...
I0619 11:51:10.772094     103 global.go:110] podman priority: 2, state: {Installed:false Healthy:false Error:exec: "podman": executable file not found in $PATH Fix:Install Podman Doc:https://minikube.sigs.k8s.io/docs/drivers/podman/}
I0619 11:51:10.863257     103 global.go:110] virtualbox priority: 5, state: {Installed:false Healthy:false Error:unable to find VBoxManage in $PATH Fix:Install VirtualBox Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/virtualbox/}
I0619 11:51:10.916984     103 global.go:110] vmware priority: 6, state: {Installed:false Healthy:false Error:exec: "docker-machine-driver-vmware": executable file not found in $PATH Fix:Install docker-machine-driver-vmware Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/}
W0619 11:51:11.232832     103 docker.go:99] docker returned error: exit status 1
I0619 11:51:11.234742     103 global.go:110] docker priority: 7, state: {Installed:true Healthy:false Error:"docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running? Fix:Start the Docker service Doc:https://minikube.sigs.k8s.io/docs/drivers/docker/}
I0619 11:51:11.485997     103 global.go:110] kvm2 priority: 7, state: {Installed:true Healthy:false Error:/usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor
error: no valid connection
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory Fix:Follow your Linux distribution instructions for configuring KVM Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/}
I0619 11:51:11.497713     103 global.go:110] none priority: 3, state: {Installed:true Healthy:false Error:the 'none' driver must be run as the root user Fix:For non-root usage, try the newer 'docker' driver Doc:}
I0619 11:51:11.498966     103 driver.go:201] not recommending "docker" due to health: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I0619 11:51:11.502837     103 driver.go:201] not recommending "kvm2" due to health: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor
error: no valid connection
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
I0619 11:51:11.508996     103 driver.go:201] not recommending "none" due to health: the 'none' driver must be run as the root user
I0619 11:51:11.512026     103 driver.go:235] Picked:
I0619 11:51:11.512640     103 driver.go:236] Alternatives: []
I0619 11:51:11.513667     103 driver.go:237] Rejects: [podman virtualbox vmware docker kvm2 none]
👎  Unable to pick a default driver. Here is what was considered, in preference order:
    ▪ podman: Not installed: exec: "podman": executable file not found in $PATH
    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH
    ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH
    ▪ docker: Not healthy: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
    ▪ kvm2: Not healthy: /usr/bin/virsh domcapabilities --virttype kvm failed:
error: failed to connect to the hypervisor
error: no valid connection
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory
    ▪ none: Not healthy: the 'none' driver must be run as the root user
👉  Try specifying a --driver, or see https://minikube.sigs.k8s.io/docs/start/
centy@L5PXPQN2:~$

**Comment by ckvtvm-arch** [comment]
I added the exec tcp in docker service json

**Comment by ckvtvm-arch** [comment]
It still doesn’t works

**Comment by tstromberg** [comment]
Can you share the output of:

`docker version`

Thanks!

**Comment by ckvtvm-arch** [comment]
> Can you share the output of:
> 
> `docker version`
> 
> Thanks!

centy@L5PXPQN2:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:41 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
centy@L5PXPQN2:~$ minikube start --driver=docker
😄  minikube v1.11.0 on Ubuntu 16.04
✨  Using the docker driver based on user configuration

❗  'docker' driver reported an issue: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
💡  Suggestion: Start the Docker service
📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/

💣  Failed to validate 'docker' driver
centy@L5PXPQN2:~$

**Comment by ckvtvm-arch** [comment]
centy@L5PXPQN2:~$ docker version
Client: Docker Engine - Community
 Version:           19.03.11
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        42e35e61f3
 Built:             Mon Jun  1 09:12:41 2020
 OS/Arch:           linux/amd64
 Experimental:      false
Cannot connect to the Docker daemon at tcp://localhost:2375. Is the docker daemon running?
centy@L5PXPQN2:~$ minikube start --driver=docker
😄  minikube v1.11.0 on Ubuntu 16.04
✨  Using the docker driver based on user configuration

❗  'docker' driver reported an issue: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
💡  Suggestion: Start the Docker service
📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/

💣  Failed to validate 'docker' driver
centy@L5PXPQN2:~$

**Comment by ckvtvm-arch** [comment]
I tried all the below TCP connections such that Linux  docker daemon connects to windows docker.

ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock

ExecStart=/usr/bin/docker daemon -H tcp://172.18.16.1:2375 
ExecStart=/usr/bin/docker daemon -H tcp://192.168.177.129:2375 


ExecStart=/usr/bin/dockerd -H fd:// --dns 8.8.8.8

ExecStart=/usr/bin/dockerd -H unix:// -D -H tcp://127.0.0.1:2375

**Comment by medyagh** [comment]
@ckvtvm-arch minikube is cearly indication that your docker service is not healthy, have you tried to see why your docker version --format {{.Server.Os}}-{{.Server.Version} command is falling?

have you tried minikube's suggesiton to restart tthe docker service?

**Comment by ckvtvm-arch** [comment]
Yes, I tried restarting the docker service many times for minikube.I am using docker windows for building images and it works well.
It is something to do with how minikube from windows subsystem Linux connects to docker windows .


Sent from Yahoo Mail for iPhone


On Tuesday, July 7, 2020, 6:14 PM, Medya Ghazizadeh <notifications@github.com> wrote:




@ckvtvm-arch minikube is cearly indication that your docker service is not healthy, have you tried to see why your docker version --format {{.Server.Os}}-{{.Server.Version} command is falling?

have you tried minikube's suggesiton to restart tthe docker service?

**Comment by medyagh** [comment]
@ckvtvm-arch for using miniikube with docker driver, you need a healthy docker installation, I recommend checking the docker documentaiton on how to uninstalll and install docker for WSL

**Comment by tstromberg** [comment]
This seems to be a docker configuration issue. Please `/reopen` if `docker info` works properly, but minikube is still failing.
