### ISSUE TITLE
minikube start problem please help. i have even downloaded the iso file manually and move it in using "mv minikube-v1.7.0.iso /home/irtaza/.minikube/cache/iso" even then it is stuck on " Downloading VM boot image ..."

### ISSUE THREAD

**Issue by irtaza909** [kubernetes/minikube#8517]
minikube v1.11.0 on Ubuntu 18.04
✨  Using the kvm2 driver based on user configuration
💿  Downloading VM boot image ...
E0620 10:45:07.379228    6379 iso.go:86] Unable to download https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso.sha256 Dst:/home/irtaza/.minikube/cache/iso/minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38] Decompressors:map[bz2:0x2b3cb38 gz:0x2b3cb38 tar.bz2:0x2b3cb38 tar.gz:0x2b3cb38 tar.xz:0x2b3cb38 tbz2:0x2b3cb38 tgz:0x2b3cb38 txz:0x2b3cb38 xz:0x2b3cb38 zip:0x2b3cb38] Getters:map[file:0xc00049e980 http:0xc000187420 https:0xc000187440] Dir:false ProgressListener:0x2b152d0 Options:[0xc1f6a0]}: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso.sha256: proxyconnect tcp: dial tcp :443: connect: connection refused
💿  Downloading VM boot image ...
E0620 10:45:07.480560    6379 iso.go:86] Unable to download https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso.sha256 Dst:/home/irtaza/.minikube/cache/iso/minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38] Decompressors:map[bz2:0x2b3cb38 gz:0x2b3cb38 tar.bz2:0x2b3cb38 tar.gz:0x2b3cb38 tar.xz:0x2b3cb38 tbz2:0x2b3cb38 tgz:0x2b3cb38 txz:0x2b3cb38 xz:0x2b3cb38 zip:0x2b3cb38] Getters:map[file:0xc0003b2af0 http:0xc0000be960 https:0xc0000be9e0] Dir:false ProgressListener:0x2b152d0 Options:[0xc1f6a0]}: invalid checksum: Error downloading checksum file: Get https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso.sha256: proxyconnect tcp: dial tcp :443: connect: connection refused
💿  Downloading VM boot image ...
E0620 10:45:07.592433    6379 iso.go:86] Unable to download https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso.sha256 Dst:/home/irtaza/.minikube/cache/iso/minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38] Decompressors:map[bz2:0x2b3cb38 gz:0x2b3cb38 tar.bz2:0x2b3cb38 tar.gz:0x2b3cb38 tar.xz:0x2b3cb38 tbz2:0x2b3cb38 tgz:0x2b3cb38 txz:0x2b3cb38 xz:0x2b3cb38 zip:0x2b3cb38] Getters:map[file:0xc00049eca0 http:0xc0001876c0 https:0xc0001876e0] Dir:false ProgressListener:0x2b152d0 Options:[0xc1f6a0]}: invalid checksum: Error downloading checksum file: Get https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso.sha256: proxyconnect tcp: dial tcp :443: connect: connection refused

💣  error provisioning host: Failed to cache ISO: unable to cache ISO: 
  https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso.sha256 Dst:/home/irtaza/.minikube/cache/iso/minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38] Decompressors:map[bz2:0x2b3cb38 gz:0x2b3cb38 tar.bz2:0x2b3cb38 tar.gz:0x2b3cb38 tar.xz:0x2b3cb38 tbz2:0x2b3cb38 tgz:0x2b3cb38 txz:0x2b3cb38 xz:0x2b3cb38 zip:0x2b3cb38] Getters:map[file:0xc00049e980 http:0xc000187420 https:0xc000187440] Dir:false ProgressListener:0x2b152d0 Options:[0xc1f6a0]}: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso.sha256: proxyconnect tcp: dial tcp :443: connect: connection refused
  https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso.sha256 Dst:/home/irtaza/.minikube/cache/iso/minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38] Decompressors:map[bz2:0x2b3cb38 gz:0x2b3cb38 tar.bz2:0x2b3cb38 tar.gz:0x2b3cb38 tar.xz:0x2b3cb38 tbz2:0x2b3cb38 tgz:0x2b3cb38 txz:0x2b3cb38 xz:0x2b3cb38 zip:0x2b3cb38] Getters:map[file:0xc0003b2af0 http:0xc0000be960 https:0xc0000be9e0] Dir:false ProgressListener:0x2b152d0 Options:[0xc1f6a0]}: invalid checksum: Error downloading checksum file: Get https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso.sha256: proxyconnect tcp: dial tcp :443: connect: connection refused
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso.sha256 Dst:/home/irtaza/.minikube/cache/iso/minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38 0x2b3cb38] Decompressors:map[bz2:0x2b3cb38 gz:0x2b3cb38 tar.bz2:0x2b3cb38 tar.gz:0x2b3cb38 tar.xz:0x2b3cb38 tbz2:0x2b3cb38 tgz:0x2b3cb38 txz:0x2b3cb38 xz:0x2b3cb38 zip:0x2b3cb38] Getters:map[file:0xc00049eca0 http:0xc0001876c0 https:0xc0001876e0] Dir:false ProgressListener:0x2b152d0 Options:[0xc1f6a0]}: invalid checksum: Error downloading checksum file: Get https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso.sha256: proxyconnect tcp: dial tcp :443: connect: connection refused

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by afbjorklund** [comment]
@irtaza909 : You need to use the _same_ version, i.e. you can't rename minikube-v1.7.0.iso to minikube-v1.11.0.iso

**Comment by irtaza909** [comment]
Thanks for the reply can you please write the exact coomand that is should use to start minikube. I am stuck in this for long.

**Comment by sharifelgamal** [comment]
It looks like you can't download the ISO for some reason. What was the exact command you used that resulted in that output?

**Comment by RA489** [comment]
@irtaza909 can you try this WIP PR https://github.com/kubernetes/minikube/pull/8555 if that works for you?

**Comment by priyawadhwa** [comment]
Hey @irtaza909 are you still seeing this issue?

**Comment by sharifelgamal** [comment]
Hey @irtaza909  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!
