### ISSUE TITLE
Minikube should automatically initialize/configure a Virtual Switch when launched with HyperV

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#852]
Currently users have to create a hyperv virtual switch outside of minikube and configure minikube to use it when attempting to use minikube with the hyper v driver.  It would be a better user experience if minikube created a virtual switch automatically and was configured to use this switch (similar to Docker For Windows solution)

**Comment by r2d4** [comment]
Should we move this issue upstream in the hyper-v driver (docker machine)?

**Comment by aaron-prindle** [comment]
Yes, I have added an issue upstream:
https://github.com/docker/machine/issues/3894
