### ISSUE TITLE
【寻求解释】关于minikube get start的用例返回结果

### ISSUE THREAD

**Issue by hellxz** [kubernetes/minikube#8522]
**重现问题所需的命令**：
创建集群执行测试用例
```bash
kubectl create deployment hello-minikube --image=registry.cn-hangzhou.aliyuncs.com/google_containers/echoserver:1.4
kubectl expose deployment hello-minikube --type=NodePort --port=8080
minikube service hello-minikube
```

**失败的命令的完整输出**：<details>
无法理解测试用例返回的 `request_uri=http://172.17.0.4:8080/` 为什么既不是`<minikube容器ip>:<NodePort>` ，也不是`<Service Cluster IP>:<Serivce Port>`，172.17.0.4是minikube这个节点的ip，这个request_uri表示的是从哪请求到服务的呢，求解？
感谢
</details>

**`minikube logs`命令的输出**： <details>

CLIENT VALUES:
client_address=172.18.0.1
command=GET
real path=/
query=nil
request_version=1.1
request_uri=http://172.17.0.4:8080/

SERVER VALUES:
server_version=nginx: 1.10.0 - lua: 10001

HEADERS RECEIVED:
accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding=gzip, deflate
accept-language=zh-CN,zh;q=0.9
connection=keep-alive
host=172.17.0.4:30642
upgrade-insecure-requests=1
user-agent=Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.61 Safari/537.36
BODY:
-no body in request-

</details>

**使用的操作系统版本**：
- Debian 10.4
- Minikube 1.11.0
- driver Docker 19.3

**Comment by tstromberg** [comment]
您的“ minikube start”命令行是什么？

对于Docker驱动程序，主机无法直接访问Pod IP，这就是为什么可以提供不同IP的原因。

**Comment by hellxz** [comment]
> 您的“ minikube start”命令行是什么？
> 
> 对于Docker驱动程序，主机无法直接访问Pod IP，这就是为什么可以提供不同IP的原因。

@tstromberg 感谢回复，初始化集群的确用的Docker，命令如下：
```bash
minikube start --driver docker --image-repository registry.cn-hangzhou.aliyuncs.com/google_containers --kubernetes-version v1.18.3
```
即然主机无法直接访问Pod IP，所以是NodePort绑定到了8080上？使用minikube节点的IP+NodePort访问Pod IP对么？ 
```bash
kubectl expose deployment hello-minikube --type=NodePort --port=8080
```

**Comment by medyagh** [comment]
I would use 
```minikube service hello-minikube --url```

**Comment by hellxz** [comment]
@medyagh that means don't mind that，okay
