### ISSUE TITLE
enable failed: run callbacks: heapster is not a valid addon

### ISSUE THREAD

**Issue by KellerKnebel** [kubernetes/minikube#8523]
</details>

**A saída do comando `minikube logs`**:<details>

enable failed: run callbacks: heapster is not a valid addon

</details>

**A versão do sistema operacional usado**:

**Comment by tstromberg** [comment]
`heapster` was deprecated in favor of `metrics-server`.

The next release will have an alias.

Duplicate of #6115 and #8360 

Hope this helps!
