### ISSUE TITLE
Add warning when trying to run with cgroups v2 enabled

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#8526]
Until Kubernetes supports running with cgroups v2 enabled, we should add a warning when starting...

This affects the VM-less drivers, such as "none", "ssh", "docker" or "podman", when running under Fedora 31 and later:

https://fedoraproject.org/wiki/Changes/CGroupsV2

https://medium.com/nttlabs/cgroup-v2-596d035be4d7

The choices are either using the libvirt driver ("kvm2"), or changing back to cgroups v1 and rebooting.

Currently we get a lot of subtle errors later on, when it fails to find required files under `/sys/fs/cgroup/`.

**Comment by afbjorklund** [comment]
Problem reports: #6795 #8525 and possibly others - we don't do any testing on Fedora and they use OpenShift by default

**Comment by medyagh** [comment]
I agree and we should do this ! anyone wants to pick this up ?

**Comment by afbjorklund** [comment]
It's getting a bit late in the game, now cgroups v2 _should_ be working - when using Docker 20.10 and Kubernetes 1.20

We still need the warnings for the earlier versions, though. But it is not "mandatory" in the same way that it used to be.

**Comment by mazzystr** [comment]
@afbjorklund except the issue description reads:

This affects the VM-less drivers, such as "*none*" or "_podman_", when running under Fedora 31 and later:

None of us commenting on Fedora issues want to run docker runtime.

**Comment by afbjorklund** [comment]
> None of us commenting on Fedora issues want to run docker runtime.

There was already supports for cgroups v2 in podman and in crun.

https://fedoraproject.org/wiki/Changes/CGroupsV2

The important thing was that Kubernetes would work with it, as well.

We have _other_ Fedora issues now, like cri-o or btrfs.

----

Still need the warning though, when running with older versions...

But there should now be a check available: `IsCgroup2UnifiedMode`

**Comment by afbjorklund** [comment]
Running with cgroups v2 is now the default, there is no warning needed.

You do need to synchronize the k8s settings with the cr settings, though.
