### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by ashwani7273** [kubernetes/minikube#8527]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
Hi. Can you add some details to this issue? What platform are you trying to install on? What issue are you facing?
/triage needs-information
/triage support

**Comment by medyagh** [comment]
@ashwani7273 
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/triage support

**Comment by medyagh** [comment]
I wlll close this issue for now, but please reopen when you are ready to provide more info
