### ISSUE TITLE
docker driver: preload extract container should resect --base-image flag

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8530]
currently if you specify the --base-image the temp container that extracts the preload tar file is not respecting the --base-image flag

**Comment by peterfication** [comment]
I think I had a similar issue. I came across https://github.com/kubernetes/minikube/issues/9227 and saw that the base image was with a different repository tag there. So I tagged my locally present kicbase image in different ways and adjusted the `minikube start` command with `local` and it finally worked.

```
docker tag gcr.io/k8s-minikube/kicbase_v0.0.12-snapshot2 local/kicbase_v0.0.12-snapshot2
docker tag gcr.io/k8s-minikube/kicbase_v0.0.12-snapshot2 kicbase_v0.0.12-snapshot2

minikube start --base-image=local/kicbase_v0.0.12-snapshot2 ...
```

Maybe it helps.

**Comment by priyawadhwa** [comment]
This has been fixed.
