### ISSUE TITLE
https://github.com/kubernetes/minikube/issues/5532

### ISSUE THREAD

**Issue by javaidrauf** [kubernetes/minikube#8532]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by prasadkatti** [comment]
Hi. Are you trying to say that we should reopen https://github.com/kubernetes/minikube/issues/5532?
/triage needs-information
