### ISSUE TITLE
docker: driver start: expected container state be running but got "Stopped"

### ISSUE THREAD

**Issue by jonathancychow** [kubernetes/minikube#8534]
**Steps to reproduce the issue:** 

1. Docker is running (Docker version 19.03.8, build afacb8b)
2. minikube start --driver=docker --alsologtostderr

**Full output of failed command:** 
I0623 12:35:59.442040   13328 start.go:98] hostinfo: {"hostname":"M801845","uptime":76033,"bootTime":1592836126,"procs":339,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"0882b1f4-00bc-44a2-bc61-0d41e65c1cac"}
W0623 12:35:59.443040   13328 start.go:106] gopshost.Virtualization returned error: not implemented yet
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
I0623 12:35:59.451040   13328 notify.go:125] Checking for updates...
I0623 12:35:59.452044   13328 driver.go:253] Setting default libvirt URI to qemu:///system
I0623 12:35:59.912552   13328 docker.go:95] docker version: linux-19.03.8
* Using the docker driver based on existing profile
I0623 12:35:59.915560   13328 start.go:214] selected driver: docker
I0623 12:35:59.916553   13328 start.go:611] validating driver "docker" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:1991 CPUs:2 DiskSize:20000 Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[{Component:kubeadm Key:pod-network-cidr Value:10.244.0.0/16}] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0623 12:35:59.920552   13328 start.go:617] status for docker: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0623 12:35:59.920552   13328 start.go:935] auto setting extra-config to "kubeadm.pod-network-cidr=10.244.0.0/16".
* Starting control plane node minikube in cluster minikube
I0623 12:35:59.927600   13328 cache.go:105] Beginning downloading kic artifacts for docker with docker
I0623 12:36:00.512284   13328 image.go:88] Found gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 in local docker daemon, skipping pull
I0623 12:36:00.512284   13328 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0623 12:36:00.514237   13328 preload.go:103] Found local preload: C:\Users\jonathan.chow\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0623 12:36:00.517239   13328 cache.go:49] Caching tarball of preloaded images
I0623 12:36:00.518236   13328 preload.go:129] Found C:\Users\jonathan.chow\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0623 12:36:00.518236   13328 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0623 12:36:00.519236   13328 profile.go:156] Saving config to C:\Users\jonathan.chow\.minikube\profiles\minikube\config.json ...
I0623 12:36:00.524238   13328 cache.go:152] Successfully downloaded all kic artifacts
I0623 12:36:00.524238   13328 start.go:240] acquiring machines lock for minikube: {Name:mkce9bb9e4e5924804bcdec99bb54cf1f3aa3a3e Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0623 12:36:00.526240   13328 start.go:244] acquired machines lock for "minikube" in 0s
I0623 12:36:00.527237   13328 start.go:88] Skipping create...Using existing machine configuration
I0623 12:36:00.528262   13328 fix.go:53] fixHost starting:
I0623 12:36:00.544270   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:01.148283   13328 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0623 12:36:01.148283   13328 fix.go:131] unexpected machine state, will restart: <nil>
* Restarting existing docker container for "minikube" ...
I0623 12:36:01.160963   13328 cli_runner.go:108] Run: docker start minikube
I0623 12:36:01.918115   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:02.436546   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:02.839324   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:03.246598   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:03.747884   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:04.338103   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:04.739128   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:05.152332   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:05.503088   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:05.967360   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:06.440734   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:06.857209   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:07.389870   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:07.918959   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:08.668486   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:09.402188   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:10.095889   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:10.765105   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:11.505356   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:12.822862   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:14.115463   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:15.633556   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:18.088679   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:22.645911   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:30.585744   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:37.562108   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:37.986521   13328 fix.go:55] fixHost completed within 37.4583081s
I0623 12:36:37.986521   13328 start.go:75] releasing machines lock for "minikube", held for 37.4593326s
! StartHost failed, but will try again: driver start: expected container state be running but got "Stopped"
I0623 12:36:42.988831   13328 start.go:240] acquiring machines lock for minikube: {Name:mkce9bb9e4e5924804bcdec99bb54cf1f3aa3a3e Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0623 12:36:42.988831   13328 start.go:244] acquired machines lock for "minikube" in 0s
I0623 12:36:42.989876   13328 start.go:88] Skipping create...Using existing machine configuration
I0623 12:36:42.998012   13328 fix.go:53] fixHost starting:
I0623 12:36:43.018048   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:43.289125   13328 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0623 12:36:43.289125   13328 fix.go:131] unexpected machine state, will restart: <nil>
* Restarting existing docker container for "minikube" ...
I0623 12:36:43.301988   13328 cli_runner.go:108] Run: docker start minikube
I0623 12:36:43.768708   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:44.199379   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:44.492552   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:44.779318   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:45.071739   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:45.361105   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:45.662663   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:45.946606   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:46.323023   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:46.780094   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:47.156367   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:47.567999   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:47.976396   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:48.467690   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:48.952527   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:49.480811   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:49.919550   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:50.594374   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:51.419412   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:52.298469   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:53.644556   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:55.651228   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:36:57.835006   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:37:01.166330   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:37:08.749014   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:37:16.367658   13328 cli_runner.go:108] Run: docker container inspect minikube --format={{.State.Status}}
I0623 12:37:16.672041   13328 fix.go:55] fixHost completed within 33.6740739s
I0623 12:37:16.672041   13328 start.go:75] releasing machines lock for "minikube", held for 33.6822101s
* Failed to start docker container. "minikube start" may fix it: driver start: expected container state be running but got "Stopped"
I0623 12:37:16.683042   13328 exit.go:58] WithError(error provisioning host)=Failed to start host: driver start: expected container state be running but got "Stopped" called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x18bd240)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc000816c20)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc0008166e0, 0x0, 0x2)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc0008166c0, 0x2, 0x2, 0x2b6c200, 0xc0008166c0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x20, 0xc000816280)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
Do you mind sharing the output of:

`docker ps -a`
`docker logs <CONTAINERD ID mentioning minikube>`

For instance:

You should see something like:

```
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS                                                                                                      NAMES
98af07eae04a        gcr.io/k8s-minikube/kicbase:v0.0.10   "/usr/local/bin/entr…"   2 hours ago         Up 2 hours          127.0.0.1:32783->22/tcp, 127.0.0.1:32782->2376/tcp, 127.0.0.1:32781->5000/tcp, 127.0.0.1:32780->8443/tcp   flannel-20200624080604-19415
```

and thus be able to run:

`docker logs 98af07eae04a`

Thanks!

**Comment by jonathancychow** [comment]
I got the following output: 
INFO: ensuring we can execute /bin/mount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: fix cgroup mounts for all subsystems
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: faking /sys/class/dmi/id/product_name to be "kind"
INFO: faking /sys/class/dmi/id/product_uuid to be random
INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
INFO: setting iptables to detected mode: legacy
update-alternatives: error: no alternatives for iptables
INFO: ensuring we can execute /bin/mount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: fix cgroup mounts for all subsystems
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: faking /sys/class/dmi/id/product_name to be "kind"
INFO: faking /sys/class/dmi/id/product_uuid to be random
INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
INFO: setting iptables to detected mode: legacy
update-alternatives: error: no alternatives for iptables
INFO: ensuring we can execute /bin/mount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: fix cgroup mounts for all subsystems
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: faking /sys/class/dmi/id/product_name to be "kind"
INFO: faking /sys/class/dmi/id/product_uuid to be random
INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
INFO: setting iptables to detected mode: legacy
update-alternatives: error: no alternatives for iptables
INFO: ensuring we can execute /bin/mount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: fix cgroup mounts for all subsystems
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: faking /sys/class/dmi/id/product_name to be "kind"
INFO: faking /sys/class/dmi/id/product_uuid to be random
INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
INFO: setting iptables to detected mode: legacy
update-alternatives: error: no alternatives for iptables
INFO: ensuring we can execute /bin/mount even with userns-remap
INFO: remounting /sys read-only
INFO: making mounts shared
INFO: fix cgroup mounts for all subsystems
INFO: clearing and regenerating /etc/machine-id
Initializing machine ID from random generator.
INFO: faking /sys/class/dmi/id/product_name to be "kind"
INFO: faking /sys/class/dmi/id/product_uuid to be random
INFO: faking /sys/devices/virtual/dmi/id/product_uuid as well
INFO: setting iptables to detected mode: legacy
update-alternatives: error: no alternatives for iptables

**Comment by medyagh** [comment]
@jonathancychow do you mind tryinh with the latest version of minkube and see if you still have the same issue /

we imprved the health and error detection in latest release for docker driver.

https://github.com/kubernetes/minikube/releases/tag/v1.12.0-beta.1

**Comment by jonathancychow** [comment]
I gave that a try and it seems to work. I got to disable Kubernetes on Docker and restarted it before running the follow command:
`minikube start --driver=docker`

**Comment by medyagh** [comment]
glad to see this issue was solved @jonathancychow
