### ISSUE TITLE
docker driver: check docker-desktop has enough cpu/ram on Mac/Windows

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8540]

**Comment by afbjorklund** [comment]
Is this related to #7980 ?

**Comment by afbjorklund** [comment]
We probably should check the memory also on Linux, for people running the docker driver in a custom VM

**Comment by afbjorklund** [comment]
Why is minikube not able to run in a Docker Desktop that has (the default setting of) 2 GB of memory ?
Upstream kubernetes/kubeadm claims that it _should_ be enough, even if we do default to 2200MB now.

```
cmd/minikube/cmd/start_flags.go-        minUsableMem            = 1024 // Kubernetes will not start with less than 1GB
cmd/minikube/cmd/start_flags.go:        minRecommendedMem       = 2000 // Warn at no lower than existing configurations
```
