### ISSUE TITLE
Make problems detected in kubelet logs more user-friendly

### ISSUE THREAD

**Issue by priyawadhwa** [kubernetes/minikube#8542]
In cloud shell, after running `minikube start` about 10 times in a loop,  I got these logs:

minikube start --base-image gcr.io/priya-wadhwa/kic
* minikube v1.10.1 on Debian 10.4
  - MINIKUBE_FORCE_SYSTEMD=true
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running docker "minikube" container ...
* Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
  - kubeadm.pod-network-cidr=10.244.0.0/16
* Problems detected in kubelet:
  - Jun 23 20:16:09 minikube kubelet[2061]: E0623 20:16:09.633335    2061 pod_workers.go:191] Error syncing pod 91440a0228dd84ec2ca1dbb97995518f ("kube-apiserver-minikube_kube-system(91440a0228dd84ec2ca1dbb97995518f)"), skipping: failed to "StartContainer" for "kube-apiserver" with CrashLoopBackOff: "back-off 5m0s restarting failed container=kube-apiserver pod=kube-apiserver-minikube_kube-system(91440a0228dd84ec2ca1dbb97995518f)"
  - Jun 23 20:16:10 minikube kubelet[2061]: E0623 20:16:10.627677    2061 pod_workers.go:191] Error syncing pod 7f415a35d57cff5428871c5a51313bd5 ("kube-controller-manager-minikube_kube-system(7f415a35d57cff5428871c5a51313bd5)"), skipping: failed to "StartContainer" for "kube-controller-manager" with CrashLoopBackOff: "back-off 2m40s restarting failed container=kube-controller-manager pod=kube-controller-manager-minikube_kube-system(7f415a35d57cff5428871c5a51313bd5)"
  - Jun 23 20:16:10 minikube kubelet[2061]: E0623 20:16:10.628367    2061 pod_workers.go:191] Error syncing pod 97c575a27f5e44612d2635f3f23ddb5a ("etcd-minikube_kube-system(97c575a27f5e44612d2635f3f23ddb5a)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "back-off 2m40s restarting failed container=etcd pod=etcd-minikube_kube-system(97c575a27f5e44612d2635f3f23ddb5a)"
  - Jun 23 20:16:10 minikube kubelet[2061]: E0623 20:16:10.628797    2061 pod_workers.go:191] Error syncing pod 155707e0c19147c8dc5e997f089c0ad1 ("kube-scheduler-minikube_kube-system(155707e0c19147c8dc5e997f089c0ad1)"), skipping: failed to "StartContainer" for "kube-scheduler" with CrashLoopBackOff: "back-off 2m40s restarting failed container=kube-scheduler pod=kube-scheduler-minikube_kube-system(155707e0c19147c8dc5e997f089c0ad1)"

similar logs ~20 times

! Unable to restart cluster, will reset it: apiserver healthz: apiserver process never appeared
* Enabled addons: default-storageclass, storage-provisioner
* Done! kubectl is now configured to use "minikube"
+ docker pull gcr.io/priya-wadhwa/kic

In the end minikube fixed itself, but that wall of logs was pretty ugly. I'm thinking we should only output `* Problems detected in kubelet, trying to resolve... ` and show the specifics of those logs only if minikube fails.

<details>

```
$ sudo systemctl status kubelet
● kubelet.service - kubelet: The Kubernetes Node Agent
   Loaded: loaded (/lib/systemd/system/kubelet.service; disabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/kubelet.service.d
           └─10-kubeadm.conf
   Active: active (running) since Tue 2020-06-23 20:19:43 UTC; 10min ago
     Docs: http://kubernetes.io/docs/
 Main PID: 23374 (kubelet)
    Tasks: 17 (limit: 4688)
   Memory: 29.4M
   CGroup: /kubepods/besteffort/pod2f9e3fac99bf3639b3a2b30f72284a85/62e88effb4c74c409e5ee62a4ee8e2fd1786f0c3271a3974894337941d3cbb0
4/docker/fa2c05c06f87399aa2e8594c2081d992140aabb569e039556e01712fbfc61b48/system.slice/kubelet.service
           └─23374 /var/lib/minikube/binaries/v1.18.2/kubelet --authorization-mode=Webhook --bootstrap-kubeconfig=/etc/kubernetes/boo
tstrap-kubelet.conf --cgroup-driver=systemd --client-ca-file=/var/lib/minikube/certs/ca.crt --cluster-domain=cluster.local --config
=/var/lib/kubelet/config.yaml --container-runtime=docker --fail-swap-on=false --hostname-override=minikube --kubeconfig=/etc/kubern
etes/kubelet.conf --node-ip=172.18.0.3 --pod-manifest-path=/etc/kubernetes/manifests

Jun 23 20:30:00 minikube kubelet[23374]: E0623 20:30:00.632374   23374 reflector.go:382] k8s.io/kubernetes/pkg/kubelet/config/apise
rver.go:46: Failed to watch *v1.Pod: Get https://control-plane.minikube.internal:8443/api/v1/pods?allowWatchBookmarks=true&fieldSel
ector=spec.nodeName%3Dminikube&resourceVersion=431&timeoutSeconds=512&watch=true: dial tcp 172.18.0.3:8443: connect: connection ref
used
Jun 23 20:30:00 minikube kubelet[23374]: E0623 20:30:00.644359   23374 reflector.go:382] k8s.io/client-go/informers/factory.go:135:
 Failed to watch *v1beta1.RuntimeClass: Get https://control-plane.minikube.internal:8443/apis/node.k8s.io/v1beta1/runtimeclasses?al
lowWatchBookmarks=true&resourceVersion=425&timeout=5m13s&timeoutSeconds=313&watch=true: dial tcp 172.18.0.3:8443: connect: connecti
on refused
Jun 23 20:30:00 minikube kubelet[23374]: E0623 20:30:00.661143   23374 reflector.go:382] k8s.io/kubernetes/pkg/kubelet/kubelet.go:5
26: Failed to watch *v1.Node: Get https://control-plane.minikube.internal:8443/api/v1/nodes?allowWatchBookmarks=true&fieldSelector=
metadata.name%3Dminikube&resourceVersion=428&timeoutSeconds=345&watch=true: dial tcp 172.18.0.3:8443: connect: connection refused
Jun 23 20:30:00 minikube kubelet[23374]: E0623 20:30:00.662445   23374 reflector.go:382] k8s.io/kubernetes/pkg/kubelet/kubelet.go:5
--More--
```

</details>

**Comment by tstromberg** [comment]
The idea here was to give folks early feedback to scenarios where it is unlikely for minikube to start, for instance, bad flags.

Any idea why the pod was in CrashLoopBackOff? We could turn off that message if it's recoverable, as you've noted.

**Comment by priyawadhwa** [comment]
I didn't try to debug super deepy, but the `sudo systemctl status kubelet` output (in the details above) shows this:

```
Get https://control-plane.minikube.internal:8443/api/v1/pods?allowWatchBookmarks=true&fieldSel
ector=spec.nodeName%3Dminikube&resourceVersion=431&timeoutSeconds=512&watch=true: dial tcp 172.18.0.3:8443: connect: connection ref
used
```

**Comment by priyawadhwa** [comment]
```
$ sudo cat /etc/hosts
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
172.18.0.3      minikube
<nil>   host.minikube.internal
172.18.0.3      control-plane.minikube.internal
```

The nil value seems pretty weird

**Comment by tstromberg** [comment]
Based on the message and scenario (live upgrade), I believe that fixing #8740 may possibly fix this. This assumes that the fix involves shutting down kube-system pods before upgrading.

**Comment by priyawadhwa** [comment]
That makes sense to me, I'll remove the label

**Comment by priyawadhwa** [comment]
Going to close this issue as it hasn't shown up in a while.
