### ISSUE TITLE
minikube start: failed to download checksum file:

### ISSUE THREAD

**Issue by venkatesh551** [kubernetes/minikube#8553]
On ubuntu 18.04

minikube start
😄  minikube v1.6.1 on Ubuntu 18.04
✨  Selecting 'kvm2' driver from existing profile (alternates: [virtualbox none])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running kvm2 "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.18.2 on Docker '19.03.5' ...
💾  Downloading kubeadm v1.18.2
💾  Downloading kubelet v1.18.2

💣  Failed to update cluster: downloading binaries: downloading kubeadm: Error downloading kubeadm v1.18.2: failed to download: failed to download to temp file: failed to create validator: failed to create validator: failed to download checksum file: received status code 404

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by priyawadhwa** [comment]
Hey @venkatesh551 thanks for opening this issue. Could you please try:

1. Downloading the latest version of minikube v1.12.0 [install instructions here](https://minikube.sigs.k8s.io/docs/start/)
1. Running `minikube delete`
1. Running `minikube start`

And if that fails, please provide the output of `minikube start --alsologtostderr`

**Comment by sharifelgamal** [comment]
Hey @venkatesh551  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
