### ISSUE TITLE
Minikube not starting with hyperv

### ISSUE THREAD

**Issue by sourav-code-space** [kubernetes/minikube#8557]
<img width="635" alt="Annotation 2020-06-25 105627" src="https://user-images.githubusercontent.com/66392429/85744155-aa040900-b6d2-11ea-9e3c-49959be4af56.png">

I am trying install minikube with hyperv on Windows 10 Enterprise version 1809(OS build 17763.1282). Tried with different versions of minikube(1.11 and 1.6.2). See logs below for minikube version 1.6.2:
PS C:\WINDOWS\system32> minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"
* minikube v1.6.2 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
* Selecting 'hyperv' driver from user configuration (alternates: [])
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0625 10:50:36.900726    7124 main.go:106] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start.
Virtual machine 'minikube' could not be started because the hypervisor is not running.
'minikube' failed to start. (Virtual machine ID EBF8EB00-EA3C-4C82-A9A6-808787A25DB0)
Virtual machine 'minikube' could not be started because the hypervisor is not running (Virtual machine ID
EBF8EB00-EA3C-4C82-A9A6-808787A25DB0).
The following actions may help you resolve the problem:
1) Verify that the processor of the physical computer has a supported version of hardware-assisted virtualization.
2) Verify that hardware-assisted virtualization and hardware-assisted data execution protection are enabled in the
BIOS of the physical computer.  (If you edit the BIOS to enable either setting, you must turn off the power to the
physical computer and then turn it back on.  Resetting the physical computer is not sufficient.)
3) If you have made changes to the Boot Configuration Data store, review these changes to ensure that the hypervisor
is configured to launch automatically.
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: create: creating: exit status 1
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

For minikube version 1.11
Showing hyperv not running.
Need suggestion.

**Comment by sharifelgamal** [comment]
What was the output of `minikube start` for minikube 1.11? Was it the same as the 1.6 output?

**Comment by priyawadhwa** [comment]
Hey @sourav-code-space I'm going to close this issue as it hasn't seen any activity in some time. If you're still seeing this issue, please:

1. Try upgrading to our latest minikube version (1.12.0) and see if that fixes it
1. Otherwise ,provide the output of `minikube start -v=5 --alsologtostderr`
1. Reopen this issue by including /reopen in your comment

Thank you for sharing your experience!
