### ISSUE TITLE
service list: add FQDN to service name

### ISSUE THREAD

**Issue by mazzystr** [kubernetes/minikube#8559]
It would be great if the minikube service cmd could do a reverse dns lookup.

Currently we have...
```$ minikube service -n cdi cdi-uploadproxy-exposed --url --https
https://10.88.0.6:30000
``` 
Then I have to do some bash magic to get a fqdn and perform other tasks using a fqdn so that I don't have to add aargs like `--insecure` / `-k`.

It would be great if we had something like ...
```$ minikube service -n cdi cdi-uploadproxy-exposed --url --https --fqdn
https://k8s.example.com:30000
```

in which minikube does something like ...
```
dig -x `minikube ip` +short
k8s.example.com
```

**Comment by medyagh** [comment]
@mazzystr apologize I am not sure if I understood fully, do you mind sharing a more detailed example with the expected behavior?

**Comment by mazzystr** [comment]
Here is my output...
```
$ minikube service list
|-------------|-----------------------------|--------------|------------------------|
|  NAMESPACE  |            NAME             | TARGET PORT  |          URL           |
|-------------|-----------------------------|--------------|------------------------|
| cdi         | cdi-api                     | No node port |
| cdi         | cdi-prometheus-metrics      | No node port |
| cdi         | cdi-uploadproxy             | No node port |
| cdi         | cdi-uploadproxy-exposed     |        30000 | http://10.88.0.2:30000 |
| default     | jellyfin                    |         8096 | http://10.88.0.2:30761 |
| default     | kubernetes                  | No node port |
```
It would be awesome if we could display a fqdn of the kubernetes endpoint.  I even tried adding `--apiserver-name=k8s.octacube.co --apiserver-names=k8s.octacube.co` to the minikube start cmd but still no luck with getting a fqdn in service list.

**Comment by medyagh** [comment]
that seems reasonable, I would review any PR which contributes this to minikube
@mazzystr would you like to provide an example of your desired full output ?

**Comment by mazzystr** [comment]
I have nothing to do today so I can hack on it.  :)

**Comment by priyawadhwa** [comment]
Help wanted!
