### ISSUE TITLE
Minikube IP changes whenever new cluster is created

### ISSUE THREAD

**Issue by 9kranti** [kubernetes/minikube#8569]
Minikube's IP changes whenever I delete a cluster `minikube delete` and then hit `minikube start`

Following ways tried but didn't work:
```
sudo minikube stop; sudo minikube delete &&
docker stop $(docker ps -aq) &&
docker system prune -f --volumes &&
sudo rm -rf ~/.kube ~/.minikube &&
sudo rm -rf /usr/local/bin/localkube /usr/local/bin/minikube &&
sudo systemctl stop '*kubelet*.mount' &&
sudo systemctl stop localkube.service &&
sudo systemctl disable localkube.service &&
sudo rm -rf /etc/kubernetes/
```
Removed vboxnet0 configuration from virtualBox

Again download minikube and hit `minikube start --disk-size=90g --memory=16384 --cpus=3 --kubernetes-version=1.15.2 --driver=virtualbox`

Previous IP : 192.168.99.100
New IP: 192.168.99.101
Again delete and start, IP: 192.168.99.102
It increases by 1 everytime.

How to get 192.168.99.100 this as minikube ip?

Hypervisor: VirtualBox Version 6.1.10 r138449 (Qt5.9.5)
kubectl version 1.15.2
Minikube v1.11.0

**Comment by 9kranti** [comment]
@medyagh will please give me a solution?

**Comment by sharifelgamal** [comment]
There is no deterministic IP for the minikube VM, it'll change on restart occasionally.

**Comment by medyagh** [comment]
@9kranti currently minikube can not guarantee a static IP for the clusters acorss, delete and restart due to driver limiations (virtualbox, kvm ...)

josedonizetti is working on a solution to add static IPs for docker driver. that we have it on our milestone for v1.13.0
