### ISSUE TITLE
Error checking that api exists and loading it: Machine does not exist for api.Exists(minikube)

### ISSUE THREAD

**Issue by waprin** [kubernetes/minikube#857]
**Is this a BUG REPORT or FEATURE REQUEST?** Bug

**Minikube version** (use `minikube version`):
minikube version: v0.12.2

**Environment**:
- **OS** (e.g. from /etc/os-release): OS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **Docker version** (e.g. `docker -v`): Docker version 1.12.1, build 6f9534c
- **Install tools**: curl + mv
- **Others**:

**What happened**:
Upgrade using curl and can't use docker-env command anymore

**How to reproduce it** (as minimally and precisely as possible):

Happens everytime on my machine.

**Anything else do we need to know**:

I tried moving ~/.minikube and got the same error, not sure if there's another way to get a clean slate.

**Comment by waprin** [comment]
`minikube start`: 

E1128 15:22:45.337216   90753 start.go:98] Error starting host:  Error creating host: Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"

Do I need to tell these releases that I want to use xyhve somehow?

**Comment by aaron-prindle** [comment]
Did you specify the driver using the --vm-driver flag?
minikube start --vm-driver=xhyve

**Comment by waprin** [comment]
Ah sorry! Forgot I needed that option, even though it's right there in the readme. Trying now...either taking a while or hanging....
