### ISSUE TITLE
windows: error created container "minikube" is not running yet

### ISSUE THREAD

**Issue by iqbaalsingh** [kubernetes/minikube#8580]
Used the following command first after defining the kubectl path & creating external VMswitch in hyperv manager. I'm running this on PowerSheel as admin.
1. **Steps to reproduce the issue:** + **Full output of `minikube start` command used, if not already included:**
minikube start --vm-driver=hyperv -- hyperv-virtual-switch=minikube
�  minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
✨  Using the hyperv driver based on user configuration
�  Starting control plane node minikube in cluster minikube
�  Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
✋  Stopping "minikube" in hyperv ...
�  Deleting "minikube" in hyperv ...
�  StartHost failed, but will try again: creating host: create host timed out in 240.000000 seconds
�  Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
E0627 15:49:46.247967   24172 main.go:106] libmachine: [stderr =====>] : Hyper-V\Get-VMSwitch : Hyper-V encountered an error trying to access an object on computer 'CACYYXF1S0'
because the object was not found. The object might have been deleted. Verify that the Virtual Machine
Management service on the computer is running.
At line:1 char:69
+ ...  [Text.Encoding]::UTF8; ConvertTo-Json @(Hyper-V\Get-VMSwitch|Select  ...
+                                              ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Get-VMSwitch], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.GetVMSwitch

�  Failed to start hyperv VM. "minikube start" may fix it: creating host: create: precreate: no External vs
witch nor Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

�  error provisioning host: Failed to start host: creating host: create: precreate: no External vswitch nor
 Default Switch found. A valid vswitch must be available for this command to run. Check https://docs.docker.com/machine/drivers/hyper-v/

�  minikube is exiting due to an error. If the above message is not useful, open an issue:
�  https://github.com/kubernetes/minikube/issues/new/choose
PS C:\personal\prod\complex> minikube stop
�  "minikube" does not exist, nothing to stop
PS C:\personal\prod\complex> minikube delete
�  Removed all traces of the "minikube" cluster.

Then I tried the following command

2. **Steps to reproduce the issue:** + **Full output of `minikube start` command used, if not already included:**
PS C:\personal\prod\complex> minikube start --vm-driver=docker -- hyperv-virtual-switch=minikube
�  minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.17763 Build 17763
✨  Using the docker driver based on user configuration
�  Starting control plane node minikube in cluster minikube
�  Creating docker container (CPUs=2, Memory=1968MB) ...
❗  Executing "docker ps -a --format {{.Names}}" took an unusually long time: 3.9614076s
�  Restarting the docker service may improve performance.
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 4.0395822s
�  Restarting the docker service may improve performance.
✋  Stopping "minikube" in docker ...
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 4.1591708s
�  Restarting the docker service may improve performance.
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 4.0619961s
�  Restarting the docker service may improve performance.
�  Deleting "minikube" in docker ...
�  StartHost failed, but will try again: creating host: create: creating: create kic node: check container
"minikube" running: temporary error created container "minikube" is not running yet
�  Creating docker container (CPUs=2, Memory=1968MB) ...
❗  Executing "docker ps -a --format {{.Names}}" took an unusually long time: 3.9250691s
�  Restarting the docker service may improve performance.
�  Failed to start docker container. "minikube start" may fix it: creating host: create: creating: create k
ic node: check container "minikube" running: temporary error created container "minikube" is not running yet

�  error provisioning host: Failed to start host: creating host: create: creating: create kic node: check c
ontainer "minikube" running: temporary error created container "minikube" is not running yet

�  minikube is exiting due to an error. If the above message is not useful, open an issue:
�  https://github.com/kubernetes/minikube/issues/new/choose
3.

**Full output of failed command:** 

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Have you tried running the first command without the `hyperv-virtual-switch` argument? It seems like we couldn't find the switch with the name you provided.

**Comment by medyagh** [comment]
@iqbaalsingh have you tried restating docker and ensure it has enough CPUs

**Comment by iqbaalsingh** [comment]
Folks...Have resized my HyperV instance & provided more resources. But it was not helping. Ultimately, had dropped Minikube & installed Docker-Desktop & enabled k8s there. Next step would be to drop HyperV & get it on to WSL2. Tried once but it resulted it my laptop's audio going off --- have to fall back. Will again try sometime later.

**Comment by medyagh** [comment]
does this help ?

docker system prune ?

do you mind sharing the output of these commands


minikbue delete --all
docker system prune
docker volume ls
docker ps
(ensure docker desktop is running)
(please do not enable k8s feature on docker-desktop that is in conflict wit minikube)
docker info
minikube start --driver=docker --alsologtostderr

**Comment by medyagh** [comment]
Hi @iqbaalsingh , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
