### ISSUE TITLE
Virtual Box is not starting up properly

### ISSUE THREAD

**Issue by HarikaGoli** [kubernetes/minikube#8583]
The character device /dev/vboxdrv does not exist.
	 Please install the virtualbox-dkms package and the appropriate
	 headers, most likely linux-headers-generic.

	 You will not be able to start VMs until this problem is fixed.

**Comment by HarikaGoli** [comment]
Couldnot able to able to complete the virtual box installtion which is not allowing to complete with minikube version. Have tried with both virtual box downloads and even with terminal

**Comment by sharifelgamal** [comment]
This is a virtualbox issue, not a minikube issue. 

As a workaround, you can try the kvm2 or docker drivers, if you're on linux.
