### ISSUE TITLE
use --log-dir in command, no output in the directory

### ISSUE THREAD

**Issue by usernameisnull** [kubernetes/minikube#8594]
**Steps to reproduce the issue:** 

1. minikube start --log_dir='/var/log/somepath'
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>
nothing in the /var/log/somepath

**Comment by usernameisnull** [comment]
if print something in the glog/glog_file, you'll see logDir is empty 
```Golang
func createLogDirs() {
	fmt.Printf("glog========================`%s`\n", *logDir)
	if *logDir != "" {
		logDirs = append(logDirs, *logDir)
	}
	logDirs = append(logDirs, os.TempDir())
	fmt.Printf("glog========================`%+v`\n", logDirs)
}
```

**Comment by vvlookman** [comment]
> **Steps to reproduce the issue:**
> 
> 1. minikube start --log_dir='/var/log/somepath'
> 
> **Full output of failed command:**
> 
> **Full output of `minikube start` command used, if not already included:**
> 
> **Optional: Full output of `minikube logs` command:**
> 
> nothing in the /var/log/somepath

I'm having the same problem on the mac.

**Comment by usernameisnull** [comment]
the logs are in the /tmp direcotry, and the content basiclly  the same:
```
Log file created at: 2020/07/12 18:46:43
Running on machine: ubuntu18
Binary: Built with gc go1.13.12 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg

```

**Comment by medyagh** [comment]
@usernameisnull --log_dir is not a supported minikube flag, but I would accept a PR that would add this functioanlity
