### ISSUE TITLE
issue in minikube

### ISSUE THREAD

**Issue by kapil-saratkar** [kubernetes/minikube#8595]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
![image](https://user-images.githubusercontent.com/64770934/86021724-0787b500-ba47-11ea-88fa-767306be16f9.png)

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @kapil-saratkar sorry for the delayed response. Did any of the suggestions in the error message work for you?

Alternatively, the docker driver is our recommended driver on Windows. If you have docker installed, could you upgrade to the latest version of minikube (v1.12.2) and try:

```
minikube start --driver docker
```

and see if that fixes your issue?

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this for now, please reopen if this remains an issue.
