### ISSUE TITLE
flag delete-on-failure should delete if there is a cluster with different driver

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8599]
if you have a cluster running with different driver
and you wanna change the driver u get this error:

```
$ minikube start --driver=hyperkit

$ minikube start --delete-on-failure --driver=docker
😄  minikube v1.12.0-beta.0 on Darwin 10.15.5
💥  The existing "minikube" VM was created using the "hyperkit" driver, and is incompatible with the "docker" driver.
👉  To proceed, either:

1) Delete the existing "minikube" cluster using: 'minikube delete'

* or *

2) Start the existing "minikube" cluster using: 'minikube start --driver=hyperkit'

```

but we should delete it for them since they tell us to delete !

this would be important because when we make the docker driver default
many users would have a pre-existing hyperkit hyperv

that wanna delete for them if they specified the flag

**Comment by sharifelgamal** [comment]
This is actually going to be a fair amount of refactoring, since we do our driver checks way before we start provisioning, which is where delete-on-failure looks. It's not a bad idea, it's just not as simple as the concept would seem.

**Comment by medyagh** [comment]
dupelicate of https://github.com/kubernetes/minikube/issues/8599
