### ISSUE TITLE
docker driver: IPs output should only be one line, got 2 lines

### ISSUE THREAD

**Issue by vadomlore** [kubernetes/minikube#8603]
**重现问题所需的命令**：
 minikube start --iso-url=https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
**失败的命令的完整输出**：<details>

😄  minikube v1.11.0 on Ubuntu 18.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
✋  Stopping "minikube" in docker ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...

😿  Failed to start docker container. "minikube start" may fix it: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

💣  error provisioning host: Failed to start host: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：

**Comment by medyagh** [comment]
@vadomlore do you mind sharing docker info ?

is you swarm enabled in docker ?
do you mind disabling docker swarm and see if it fixes it?

**Comment by medyagh** [comment]
this is a dupe of https://github.com/kubernetes/minikube/issues/8603

plz try to disable swarm that should fix the problem ,in next version we should detect swarm and get the right IP

**Comment by vyom-soft** [comment]
delete the ./docker/config.json and minikube delete. 
this helped me to overcome the issue-

**Comment by mythreyi1905** [comment]
> ./docker/config.json

This step solved the problem of 2 IPs, but I ended up facing another issue #8131 . Thankfully upgrading the version of my minikube helped.

**Comment by PorasS** [comment]
i was also getting the same issue on ubuntu, docker. Found a way, follow the steps, hope it will help you.
steps:
cd ~/.docker
rm -rf config.json
minikube delete --profile=minikube
minikube start --driver=docker
