### ISSUE TITLE
read: connection reset by peer

### ISSUE THREAD

**Issue by ish1963** [kubernetes/minikube#8604]
E0630 12:12:45.697228   43779 cache.go:63] save image to file "kubernetesui/dashboard:v2.0.0" -> "/Users/ibrahims.hussein/.minikube/cache/images/kubernetesui/dashboard_v2.0.0" failed: write: read tcp 192.168.1.3:54081->104.18.124.25:443: read: connection reset by peer

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

**Comment by RA489** [comment]
Hey @ish1963  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
