### ISSUE TITLE
hyperv: Failed to start host: provision: IP not found

### ISSUE THREAD

**Issue by PremSubudhi** [kubernetes/minikube#8606]
**Steps to reproduce the issue:** 
PS C:\WINDOWS\system32> minikube  start                                                                                 * minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32>
1.
2. 
3.

**Full output of failed command:** 

PS C:\WINDOWS\system32> minikube  start  --alsologtostderr
W0630 16:30:52.499361   20120 root.go:252] Error reading config file at C:\Users\pksubudh\.minikube\config\config.json: open C:\Users\pksubudh\.minikube\config\config.json: The system cannot find the file specified.
I0630 16:30:52.515360   20120 start.go:98] hostinfo: {"hostname":"PKSUBUDH-IN","uptime":10378,"bootTime":1593504474,"procs":261,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.18362 Build 18362","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"048ced4b-3706-4bb1-a0b3-9d87e99ebbb2"}
W0630 16:30:52.515360   20120 start.go:106] gopshost.Virtualization returned error: not implemented yet
* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
I0630 16:30:52.552362   20120 notify.go:125] Checking for updates...
I0630 16:30:52.619360   20120 driver.go:253] Setting default libvirt URI to qemu:///system
* Using the hyperv driver based on existing profile
I0630 16:30:54.307894   20120 start.go:214] selected driver: hyperv
I0630 16:30:54.308936   20120 start.go:611] validating driver "hyperv" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:4000 CPUs:2 DiskSize:20000 Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch:Default Switch HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0630 16:30:54.311889   20120 start.go:617] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0630 16:30:54.313887   20120 iso.go:118] acquiring lock: {Name:mk523ab3e1ea082170ab4f3c7efce76985271d90 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Starting control plane node minikube in cluster minikube
I0630 16:30:54.315892   20120 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0630 16:30:54.318888   20120 preload.go:103] Found local preload: C:\Users\pksubudh\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0630 16:30:54.319896   20120 cache.go:49] Caching tarball of preloaded images
I0630 16:30:54.320889   20120 preload.go:129] Found C:\Users\pksubudh\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0630 16:30:54.321940   20120 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0630 16:30:54.323887   20120 profile.go:156] Saving config to C:\Users\pksubudh\.minikube\profiles\minikube\config.json ...
I0630 16:30:54.331895   20120 cache.go:152] Successfully downloaded all kic artifacts
I0630 16:30:54.334911   20120 start.go:240] acquiring machines lock for minikube: {Name:mk6e833ba05c2e30b638ae78809e2da7942cd574 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0630 16:30:54.335909   20120 start.go:244] acquired machines lock for "minikube" in 997.7µs
I0630 16:30:54.336892   20120 start.go:88] Skipping create...Using existing machine configuration
I0630 16:30:54.336892   20120 fix.go:53] fixHost starting:
I0630 16:30:54.347921   20120 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0630 16:30:56.153674   20120 main.go:110] libmachine: [stdout =====>] : Running

I0630 16:30:56.153674   20120 main.go:110] libmachine: [stderr =====>] :
I0630 16:30:56.154684   20120 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0630 16:30:56.154684   20120 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running hyperv "minikube" VM ...
I0630 16:30:56.162182   20120 machine.go:88] provisioning docker machine ...
I0630 16:30:56.162687   20120 buildroot.go:163] provisioning hostname "minikube"
I0630 16:30:56.163686   20120 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0630 16:30:57.399853   20120 main.go:110] libmachine: [stdout =====>] : Running

I0630 16:30:57.399853   20120 main.go:110] libmachine: [stderr =====>] :
I0630 16:30:57.401851   20120 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0630 16:30:59.074754   20120 main.go:110] libmachine: [stdout =====>] :
I0630 16:30:59.074754   20120 main.go:110] libmachine: [stderr =====>] :
I0630 16:30:59.075757   20120 machine.go:91] provisioned docker machine in 2.9130695s
I0630 16:30:59.078758   20120 fix.go:55] fixHost completed within 4.7418661s
I0630 16:30:59.078758   20120 start.go:75] releasing machines lock for "minikube", held for 4.7428493s
! StartHost failed, but will try again: provision: IP not found
I0630 16:31:04.083977   20120 start.go:240] acquiring machines lock for minikube: {Name:mk6e833ba05c2e30b638ae78809e2da7942cd574 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0630 16:31:04.084994   20120 start.go:244] acquired machines lock for "minikube" in 0s
I0630 16:31:04.088974   20120 start.go:88] Skipping create...Using existing machine configuration
I0630 16:31:04.089984   20120 fix.go:53] fixHost starting:
I0630 16:31:04.099024   20120 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0630 16:31:05.327496   20120 main.go:110] libmachine: [stdout =====>] : Running

I0630 16:31:05.327496   20120 main.go:110] libmachine: [stderr =====>] :
I0630 16:31:05.328452   20120 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0630 16:31:05.331453   20120 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running hyperv "minikube" VM ...
I0630 16:31:05.342915   20120 machine.go:88] provisioning docker machine ...
I0630 16:31:05.343915   20120 buildroot.go:163] provisioning hostname "minikube"
I0630 16:31:05.347990   20120 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0630 16:31:06.516306   20120 main.go:110] libmachine: [stdout =====>] : Running

I0630 16:31:06.516306   20120 main.go:110] libmachine: [stderr =====>] :
I0630 16:31:06.516950   20120 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0630 16:31:08.061802   20120 main.go:110] libmachine: [stdout =====>] :
I0630 16:31:08.061802   20120 main.go:110] libmachine: [stderr =====>] :
I0630 16:31:08.062812   20120 machine.go:91] provisioned docker machine in 2.7188965s
I0630 16:31:08.065960   20120 fix.go:55] fixHost completed within 3.9759755s
I0630 16:31:08.065960   20120 start.go:75] releasing machines lock for "minikube", held for 3.9779373s
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
I0630 16:31:08.066816   20120 exit.go:58] WithError(error provisioning host)=Failed to start host: provision: IP not found called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x18bd240)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc000004ea0)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc000808990, 0x0, 0x1)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc000808980, 0x1, 0x1, 0x2b6c200, 0xc000808980)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x0, 0xc000747301)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
W0630 16:31:08.067814   20120 out.go:201] error provisioning host: Failed to start host: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32>
**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
PS C:\WINDOWS\system32> minikube logs
E0630 16:31:52.766355   18496 logs.go:200] Failed to list containers for "kube-apiserver": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0630 16:31:55.796161   18496 logs.go:200] Failed to list containers for "etcd": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0630 16:31:58.601047   18496 logs.go:200] Failed to list containers for "coredns": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0630 16:32:01.545396   18496 logs.go:200] Failed to list containers for "kube-scheduler": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0630 16:32:04.547764   18496 logs.go:200] Failed to list containers for "kube-proxy": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0630 16:32:07.446967   18496 logs.go:200] Failed to list containers for "kubernetes-dashboard": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0630 16:32:10.454436   18496 logs.go:200] Failed to list containers for "storage-provisioner": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0630 16:32:13.530676   18496 logs.go:200] Failed to list containers for "kube-controller-manager": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
* ==> Docker [<==](url
[kubernetics_install_logs.txt](https://github.com/kubernetes/minikube/files/4851344/kubernetics_install_logs.txt)
)

</details>

**Comment by PremSubudhi** [comment]
Hello Experts,

I am unable to start minikube in windows 10 pro VM. Please help me out. I have provided all the details log as required.

Regards,
Prem

**Comment by cjekin** [comment]
Not sure if it's the same issue, but I've been having a similar problem for a couple of days. You can't run Docker Desktop with Hyper-V and Minikube with Hyper-V at the same time.

**Comment by medyagh** [comment]
do you mind trying minikube delete --all
and try again ?

also if you already have docker, I recommend using our docker driver.

btw the latest beta release is availablew here
https://github.com/kubernetes/minikube/releases/tag/v1.12.0-beta.1

**Comment by PremSubudhi** [comment]
Hi Medya,

 

Thank you for writing me.

 

Sorry yesterday I could not reply you, could start minikube from my laptop. Now I need to configure proxy to pull external images.. I will reach out to you incase stuck there..

 

PS C:\WINDOWS\system32> minikube start

* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362

* Using the docker driver based on existing profile

* Starting control plane node minikube in cluster minikube

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 3.641246s

* Restarting the docker service may improve performance.

* Restarting existing docker container for "minikube" ...

* Found network options:

  - NO_PROXY=192.168.99.100

  - no_proxy=192.168.99.100

! This container is having trouble accessing https://k8s.gcr.io

* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

* Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...

  - env NO_PROXY=192.168.99.100

  - kubeadm.pod-network-cidr=10.244.0.0/16

* Verifying Kubernetes components...

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 5.3612849s

* Restarting the docker service may improve performance.

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 6.5942209s

* Restarting the docker service may improve performance.

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 9.2373617s

* Restarting the docker service may improve performance.

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 9.0614596s

* Restarting the docker service may improve performance.

* Enabled addons: dashboard, default-storageclass, storage-provisioner

* Done! kubectl is now configured to use "minikube"

PS C:\WINDOWS\system32>

 

Regards,

Prem

**Comment by PremSubudhi** [comment]
Fyi, this log I am getting while pulling nginx

 

 

PS D:\MyData\kubernetes\YAMLS> kubectl get events

LAST SEEN   TYPE      REASON      OBJECT           MESSAGE

4m38s       Normal    Scheduled   pod/happypanda   Successfully assigned default/happypanda to minikube

2m26s       Normal    Pulling     pod/happypanda   Pulling image "nginx"

2m11s       Warning   Failed      pod/happypanda   Failed to pull image "nginx": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

2m11s       Warning   Failed      pod/happypanda   Error: ErrImagePull

98s         Normal    BackOff     pod/happypanda   Back-off pulling image "nginx"

109s        Warning   Failed      pod/happypanda   Error: ImagePullBackOff

 

From: Prem Subudhi 
Sent: Wednesday, July 8, 2020 11:25 AM
To: kubernetes/minikube <reply@reply.github.com>; kubernetes/minikube <minikube@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [kubernetes/minikube] hyperv: Failed to start host: provision: IP not found (#8606)

 

Hi Medya,

 

Thank you for writing me.

 

Sorry yesterday I could not reply you, could start minikube from my laptop. Now I need to configure proxy to pull external images.. I will reach out to you incase stuck there..

 

PS C:\WINDOWS\system32> minikube start

* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362

* Using the docker driver based on existing profile

* Starting control plane node minikube in cluster minikube

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 3.641246s

* Restarting the docker service may improve performance.

* Restarting existing docker container for "minikube" ...

* Found network options:

  - NO_PROXY=192.168.99.100

  - no_proxy=192.168.99.100

! This container is having trouble accessing https://k8s.gcr.io

* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/

* Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...

  - env NO_PROXY=192.168.99.100

  - kubeadm.pod-network-cidr=10.244.0.0/16

* Verifying Kubernetes components...

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 5.3612849s

* Restarting the docker service may improve performance.

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 6.5942209s

* Restarting the docker service may improve performance.

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 9.2373617s

* Restarting the docker service may improve performance.

! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 9.0614596s

* Restarting the docker service may improve performance.

* Enabled addons: dashboard, default-storageclass, storage-provisioner

* Done! kubectl is now configured to use "minikube"

PS C:\WINDOWS\system32>

 

Regards,

Prem

**Comment by medyagh** [comment]
@PremSubudhi 
minikube is indicating
```
! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 9.2373617s

* Restarting the docker service may improve performance.
```

have you tried restarting your docker desktop ?

do you mind sharing how much Memory and CPUs your docker desktop has ?
you can click on Docker>Preferences>Resources and then see how much CPU and Rams you have allocated.

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
