### ISSUE TITLE
minikube v1.11.0 on Linuxmint 19.1 - Error creating machine

### ISSUE THREAD

**Issue by doviche** [kubernetes/minikube#8609]
I got this error while trying to execute the following command on linux mint: minikube start --vm-driver kvm2

 minikube v1.11.0 on Linuxmint 19.1
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
🔥  Deleting "minikube" in kvm2 ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: ensuring active networks: starting network default: virError(Code=1, Domain=59, Message='internal error: Failed to initialize a valid firewall backend')
🔥  Creating kvm2 VM (CPUs=2, Memory=3900MB, Disk=20000MB) ...
😿  Failed to start kvm2 VM. "minikube start" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: ensuring active networks: starting network default: virError(Code=1, Domain=59, Message='internal error: Failed to initialize a valid firewall backend')

💣  error provisioning host: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: ensuring active networks: starting network default: virError(Code=1, Domain=59, Message='internal error: Failed to initialize a valid firewall backend')

Cheers

**Comment by afbjorklund** [comment]
This sounds like there might some configuration error with libvirt

**Comment by doviche** [comment]
Hi afbjorklund,
I solved, the problem was about libvirt, virsh, iptables and etables related problems.
I solved it by installing iptables and etables properly as follow:

sudo apt-get install ebtables iptables dnsmasq

There was never a real issue, sorry mate for this.

**Comment by doviche** [comment]
Who ever might find him/herself facing this issue, just install sudo apt-get install ebtables iptables dnsmasq.

Regards
