### ISSUE TITLE
minikube start issues

### ISSUE THREAD

**Issue by rizwangcsit** [kubernetes/minikube#8613]
**Steps to reproduce the issue:** 

1. The "docker" driver should not be used with root privileges.
2. 💣  error provisioning host: Failed to save config: mkdir /home/rizwan/.minikube/profiles: permission denied
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
😄  minikube v1.11.0 on Ubuntu 18.04
✨  Automatically selected the docker driver
🛑  The "docker" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/

**Optional: Full output of `minikube logs` command:**
<details>
🤷  There is no local cluster named "minikube"
👉  To fix this, run: "minikube start"

</details>

**Comment by medyagh** [comment]
@rizwangcsit mnikube is telling you that you should not run minikbue with root, please run it with a non-root user and try again

**Comment by priyawadhwa** [comment]
Hey @rizwangcsit -- 
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide the details above, you may reopen it at any point by adding /reopen to your comment.


Thank you for sharing your experience!
