### ISSUE TITLE
breaking changes in minikube docker-env --shell none 

### ISSUE THREAD

**Issue by balopat** [kubernetes/minikube#8615]
`minikube docker-env --shell none` had previously no comments. 
In 1.12.0-beta.0:

```
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://127.0.0.1:32770
DOCKER_CERT_PATH=/Users/balintp/.minikube/certs
MINIKUBE_ACTIVE_DOCKERD=minikube

# To point your shell to minikube's docker-daemon, run:
# eval $(minikube -p minikube docker-env)
```

expected (as it works in 1.11.0) 

```
DOCKER_TLS_VERIFY=1
DOCKER_HOST=tcp://127.0.0.1:32770
DOCKER_CERT_PATH=/Users/balintp/.minikube/certs
MINIKUBE_ACTIVE_DOCKERD=minikube
```

This is breaking skaffold currently and hence Cloud Code when current context is pointing at minikube

**Comment by medyagh** [comment]
seems like it was fixed by https://github.com/kubernetes/minikube/commit/f19ca53f344a90fb7cf6051fbfbb44e03c763afc#diff-c68bcbb27350fca771469475e4c4e5dd

it is fixed on the head
