### ISSUE TITLE
minikube dashboard Autolaunch error: X11 initialization failed.

### ISSUE THREAD

**Issue by eyexin** [kubernetes/minikube#8631]
**Steps to reproduce the issue:** 

1.minkkube dashboard error, like this
2. * Verifying dashboard health ...
* Launching proxy ...
* Verifying proxy health ...
* Opening http://127.0.0.1:43422/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
START /usr/bin/firefox "http://127.0.0.1:43422/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/"
Failed to open connection to "session" message bus: /usr/bin/dbus-launch terminated abnormally with the following error: **Autolaunch error: X11 initialization failed.**

**Running without a11y support!
Error: cannot open display: localhost:10.0**
xdg-open: no method available for opening 'http://127.0.0.1:43422/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/'
X failed to open browser: exit status 3

3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube dashboard --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by eyexin** [comment]
Firstly,I am sorry about I haven't responded to you,because I am studying other project recently,so I haven't time to reply.Secondly,I am starting to use kubernetes cluster now, I don't do minikube anymore for now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubernetes/minikube"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月23日(星期四) 凌晨2:23
收件人:&nbsp;"kubernetes/minikube"<minikube@noreply.github.com&gt;;
抄送:&nbsp;"曾磊"<2559710510@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [kubernetes/minikube] minikube dashboard Autolaunch error: X11 initialization failed. (#8631)





 
Hi @eyexin, I haven't heard back from you, I wonder if you still have this issue?
 Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.
 
I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
 
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
 you could try
 minikube delete
 minikube start --driver=docker
 
for more information on the docker driver checkout:
 https://minikube.sigs.k8s.io/docs/drivers/docker/
