### ISSUE TITLE
X error provisioning host: Failed to start host: driver start: expected container state be running but got "Stopped"

### ISSUE THREAD

**Issue by Ashnam1100** [kubernetes/minikube#8634]
I've just reinstalled Docker and minikube. 

I ran this command: **minikube start --driver=docker**

I have never used minikube before, but have used Docker before.

This is the error I'm receiving:

* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 2.0391443s
* Restarting the docker service may improve performance.
* Restarting existing docker container for "minikube" ...
! StartHost failed, but will try again: driver start: expected container state be running but got "Stopped"
* Restarting existing docker container for "minikube" ...
* Failed to start docker container. "minikube start" may fix it: driver start: expected container state be running but got "Stopped"

**X error provisioning host: Failed to start host: driver start: expected container state be running but got "Stopped"**

* minikube is exiting due to an error. If the above message is not useful, open an issue:
 https://github.com/kubernetes/minikube/issues/new/choose

Does anyone know what the problem might be?

**Comment by medyagh** [comment]
@Ashnam1100 do you mind trying restarting your docker daemon and see if that fixes it?

**Comment by RA489** [comment]
@Ashnam1100 do you had any chance to restart your docker daemon as per above suggestions?

**Comment by priyawadhwa** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  Whether restarting docker resolves the issue

Thank you for sharing your experience!
