### ISSUE TITLE
update kube-webhook-certgen image 1.2.0 -> 1.2.2 in deploy.yaml

### ISSUE THREAD

**Issue by sid226** [kubernetes/minikube#8636]
Need to update kube-webhook-certgen image 1.2.0. -> 1.2.2 in [ingress-dp.yaml.tmpl]( https://github.com/kubernetes/minikube/blob/master/deploy/addons/ingress/ingress-dp.yaml.tmpl)
https://github.com/kubernetes/minikube/tree/master/deploy/addons/ingress

kube-webhook-certgen has been updated recently  to 1.2.2 for adding s390x support.

https://github.com/jet/kube-webhook-certgen/issues/15

https://hub.docker.com/r/jettech/kube-webhook-certgen/tags

as per steps given here :
https://kubernetes.github.io/ingress-nginx/deploy/

**Comment by medyagh** [comment]
@sid226 thank you for making this issue, I would be happy to review any Pr that bumps the version for ingress addon

**Comment by sid226** [comment]
@medyagh If possible, nginx-ingress image also can be bumped to 0.33.0

http://quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.33.0
