### ISSUE TITLE
Kernel with CONFIG_FTRACE_SYSCALLS kubectl-trace

### ISSUE THREAD

**Issue by alban** [kubernetes/minikube#8637]
I would like the Minikube kernel to be compiled with [CONFIG_FTRACE_SYSCALLS](https://cateee.net/lkddb/web-lkddb/FTRACE_SYSCALLS.html) (basic tracer to catch the syscall entry and exit events).

This is to be able to use kubectl-trace on Minikube.
Related issue in kubectl-trace: https://github.com/iovisor/kubectl-trace/issues/120

Symptoms:
```
$ kubectl trace run minikube -e 'tracepoint:syscalls:sys_enter_open { printf("%s %s\n", comm, str(args->filename)); }'
trace 09ecf3b8-bc53-11ea-ac93-c85b763781a4 created

$ kubectl logs kubectl-trace-09ecf3b8-bc53-11ea-ac93-c85b763781a4-4m667
if your program has maps to print, send a SIGINT using Ctrl-C, if you want to interrupt the execution send SIGINT two times
ERROR: tracepoint not found: syscalls:sys_enter_open
exit status 1
```

This is a follow-up to previous efforts to make Minikube work with BPF tools in [Inspektor Gadget](https://github.com/kinvolk/inspektor-gadget/). See issue #8556 that added CONFIG_IKHEADERS.

cc @mauriciovasquezbernal @marga-kinvolk

**Comment by medyagh** [comment]
CC
@afbjorklund

**Comment by priyawadhwa** [comment]
If anyone is interested in contributing a PR, please comment here.

**Comment by afbjorklund** [comment]
I don't know if this has performance implications (i.e. when not used), but otherwise go ahead and add it to the config...

**Comment by dalehamel** [comment]
Howdy, I've filed https://github.com/kubernetes/minikube/pull/9393 which should resolve this issue.
