### ISSUE TITLE
unable to connect the server 

### ISSUE THREAD

**Issue by anuragp0010** [kubernetes/minikube#8640]
**Steps to reproduce the issue:** 

1. kubectl get pods
2. 
3.

**Full output of failed command:** 
Unable to connect to the server: dial tcp [::1]:8080: connectex: No connection could be made because the target machine actively refused it.

**Full output of `minikube start` command used, if not already included:**
* minikube v1.10.0 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
* Preparing Kubernetes v1.18.1 on Docker 19.03.8 ...
E0704 16:02:06.130900   16068 start.go:95] Unable to get host IP: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #3
*
X failed to start node: startup failed: Failed to setup kubeconfig: Error getting VM/Host IP address: Error finding IPV4 address for VirtualBox Host-Only Ethernet Adapter #3
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

C:\Program Files\Kubernetes\Minikube>minikube logs
* ==> Docker <==
* -- Logs begin at Sat 2020-07-04 10:31:53 UTC, end at Sat 2020-07-04 10:50:27 UTC. --
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.857502441Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.858492893Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.859484830Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.860148732Z" level=info msg="skip loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.860218765Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.860311497Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.19.107\n": exit status 1"
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.860346119Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.860367701Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.862708148Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.862804574Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863000534Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863042956Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863076631Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863110222Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863142897Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863177080Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863406563Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863448990Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863671398Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.863901286Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.864997965Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865091671Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865213379Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865253385Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865284737Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865315489Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865347409Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865379338Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865409411Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865442124Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865473849Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865602136Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865639371Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865671454Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.865701132Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.866141038Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.866278148Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.866305181Z" level=info msg="containerd successfully booted in 0.023711s"
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.902674857Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.902768525Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.902834866Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.903009907Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.906878204Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.907144948Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.907344140Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Jul 04 10:32:10 minikube dockerd[2326]: time="2020-07-04T10:32:10.907564404Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.075959228Z" level=warning msg="Your kernel does not support cgroup blkio weight"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.076069289Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.076098898Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.076122255Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.076145107Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.076167061Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.076636060Z" level=info msg="Loading containers: start."
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.455286565Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.582428805Z" level=info msg="Loading containers: done."
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.659194957Z" level=info msg="Docker daemon" commit=afacb8b7f0 graphdriver(s)=overlay2 version=19.03.8
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.660588152Z" level=info msg="Daemon has completed initialization"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.734853173Z" level=info msg="API listen on /var/run/docker.sock"
* Jul 04 10:32:11 minikube dockerd[2326]: time="2020-07-04T10:32:11.735026391Z" level=info msg="API listen on [::]:2376"
* Jul 04 10:32:11 minikube systemd[1]: Started Docker Application Container Engine.
*
* ==> container status <==
* time="2020-07-04T10:50:29Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
*
* ==> describe nodes <==
E0704 16:20:31.689659   19428 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.1/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
error: stat /var/lib/minikube/kubeconfig: no such file or directory
 output: "\n** stderr ** \nerror: stat /var/lib/minikube/kubeconfig: no such file or directory\n\n** /stderr **"
*
* ==> dmesg <==
* [Jul 4 10:31] You have booted with nomodeset. This means your GPU drivers are DISABLED
* [  +0.000001] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
* [  +0.000001] Unless you actually understand what nomodeset does, you should reboot without enabling it
* [  +0.171540] APIC calibration not consistent with PM-Timer: 104ms instead of 100ms
* [  +0.061371] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
* [  +7.457837] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
* [ +12.530946] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
* [  +0.025202] systemd-fstab-generator[1354]: Ignoring "noauto" for root device
* [  +0.018955] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
* [  +0.000007] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
* [  +1.847355] vboxvideo: loading out-of-tree module taints kernel.
* [  +0.000126] vboxvideo: Unknown symbol ttm_bo_mmap (err -2)
* [  +0.000023] vboxvideo: Unknown symbol ttm_bo_global_release (err -2)
* [  +0.000020] vboxvideo: Unknown symbol ttm_bo_manager_func (err -2)
* [  +0.000008] vboxvideo: Unknown symbol ttm_bo_global_init (err -2)
* [  +0.000018] vboxvideo: Unknown symbol ttm_bo_device_release (err -2)
* [  +0.000027] vboxvideo: Unknown symbol ttm_bo_kunmap (err -2)
* [  +0.000010] vboxvideo: Unknown symbol ttm_bo_del_sub_from_lru (err -2)
* [  +0.000017] vboxvideo: Unknown symbol ttm_bo_device_init (err -2)
* [  +0.000003] vboxvideo: Unknown symbol ttm_bo_init_mm (err -2)
* [  +0.000003] vboxvideo: Unknown symbol ttm_bo_dma_acc_size (err -2)
* [  +0.000008] vboxvideo: Unknown symbol ttm_tt_init (err -2)
* [  +0.000004] vboxvideo: Unknown symbol ttm_bo_kmap (err -2)
* [  +0.000014] vboxvideo: Unknown symbol ttm_bo_add_to_lru (err -2)
* [  +0.000008] vboxvideo: Unknown symbol ttm_mem_global_release (err -2)
* [  +0.000006] vboxvideo: Unknown symbol ttm_mem_global_init (err -2)
* [  +0.000025] vboxvideo: Unknown symbol ttm_bo_init (err -2)
* [  +0.000004] vboxvideo: Unknown symbol ttm_bo_validate (err -2)
* [  +0.000012] vboxvideo: Unknown symbol ttm_bo_put (err -2)
* [  +0.000009] vboxvideo: Unknown symbol ttm_tt_fini (err -2)
* [  +0.000004] vboxvideo: Unknown symbol ttm_bo_eviction_valuable (err -2)
* [  +0.059395] vgdrvHeartbeatInit: Setting up heartbeat to trigger every 2000 milliseconds
* [  +0.009873] vboxguest: misc device minor 58, IRQ 20, I/O port d020, MMIO at 00000000f0000000 (size 0x400000)
* [  +0.666676] hpet1: lost 969 rtc interrupts
* [  +0.066141] hpet1: lost 3 rtc interrupts
* [  +0.003010] VBoxService 5.2.32 r132073 (verbosity: 0) linux.amd64 (Jul 12 2019 10:32:28) release log
*               00:00:00.003657 main     Log opened 2020-07-04T10:31:54.594068000Z
* [  +0.000191] 00:00:00.003897 main     OS Product: Linux
* [  +0.000079] 00:00:00.004009 main     OS Release: 4.19.107
* [  +0.000071] 00:00:00.004084 main     OS Version: #1 SMP Mon May 11 14:51:04 PDT 2020
* [  +0.000094] 00:00:00.004153 main     Executable: /usr/sbin/VBoxService
*               00:00:00.004155 main     Process ID: 2089
*               00:00:00.004157 main     Package type: LINUX_64BITS_GENERIC
* [  +0.000073] 00:00:00.004250 main     5.2.32 r132073 started. Verbose level = 0
* [  +0.000948] 00:00:00.005194 main     Error: Service 'control' failed to initialize: VERR_INVALID_PARAMETER
* [  +0.000162] 00:00:00.005360 main     Session 0 is about to close ...
* [  +0.000124] 00:00:00.005483 main     Stopping all guest processes ...
* [  +0.000048] 00:00:00.005549 main     Closing all guest files ...
* [  +0.000309] 00:00:00.005781 main     Ended.
* [  +0.777611] hpet1: lost 34 rtc interrupts
* [  +0.123562] hpet1: lost 3 rtc interrupts
* [  +1.624633] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
* [Jul 4 10:32] systemd-fstab-generator[2306]: Ignoring "noauto" for root device
* [  +0.380030] systemd-fstab-generator[2316]: Ignoring "noauto" for root device
* [  +3.506040] systemd-fstab-generator[2546]: Ignoring "noauto" for root device
* [Jul 4 10:33] NFSD: Unable to end grace period: -110
*
* ==> kernel <==
*  10:50:30 up 19 min,  0 users,  load average: 0.08, 0.06, 0.10
* Linux minikube 4.19.107 #1 SMP Mon May 11 14:51:04 PDT 2020 x86_64 GNU/Linux
* PRETTY_NAME="Buildroot 2019.02.10"
*
* ==> kubelet <==
* -- Logs begin at Sat 2020-07-04 10:31:53 UTC, end at Sat 2020-07-04 10:50:30 UTC. --
* -- No entries --

! unable to fetch logs for: describe nodes

</details>

**Comment by medyagh** [comment]
have u tried with latest minikube version ? @anuragp0010 

there seem to be something wrong with your virutalbox setup I recommend eitehr reinstalling it



Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
