### ISSUE TITLE
Failure of "minikube ip" returns "<nil>" with exit code 0 

### ISSUE THREAD

**Issue by pre** [kubernetes/minikube#8646]
**Steps to reproduce the issue:** 

1. Have cluster on not-ready state
2. Run "minikube ip" 

Expected: exit code != 0 with empty output

Actual: exit code == 0 
Output: `<nil>`

```bash
% minikube ip
<nil>
% echo $?
0
```

Minikube v1.11.0

Why is this a problem? 
When `minikube ip` is used in a script, it'd be straightforward to read the exit code for whether the command succeeded. However, now the exit code is always "success" so the script needs to check for failure against a flaky string `<nil>` which may change at a later Minikube release.

**Comment by afbjorklund** [comment]
@pre : thanks for reporting this issue, it should not return `nil` like that. Which OS and which driver did this happen with ?

**Comment by afbjorklund** [comment]
The problem is in the `ControlPlaneEndpoint`, which doesn't check the hostname or the return value of `net.ParseIP`

**Comment by pre** [comment]
In case it matters, I have Minikube v1.11.0 on MacOS 10.15.5 with Hyperkit.

**Comment by Dean-Coakley** [comment]
I'm taking a look at fixing this. But it's my first minikube contribution so if someone wants to take it first/take it over, let me know.

**Comment by medyagh** [comment]
@Dean-Coakley are you still interested in making a PR for this ?

**Comment by medyagh** [comment]
cc: @sharifelgamal

**Comment by Dean-Coakley** [comment]
@medyagh I opened a PR that seems to resolve the issue.
