### ISSUE TITLE
Failed to connect to 127.0.0.1 port 50502: Connection refused

### ISSUE THREAD

**Issue by ntippabhatla** [kubernetes/minikube#8651]
**Steps to reproduce the issue:** 

1. I have used the following command to start minikube cluster and it was successful. 
```
minikube start --driver=docker
😄  minikube v1.11.0 on Darwin 10.15.5
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=1991MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
    ▪ kubeadm.pod-network-cidr=10.244.0.0/16
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
```

2. Later, I was trying to check if it was working properly or not. So, 
`# kubectl apply -f ./deployment.yaml`
deployment.apps/tomcat-deployment created
`#  kubectl expose deployment tomcat-deployment --type=NodePort`
service/tomcat-deployment exposed

3.Now I try to find the port number and ran the following command

`# minikube service tomcat-deployment --url`
http://127.0.0.1:50502

4.When I tried to run the curl command upon it.
`# curl http://127.0.0.1:50502 `
**curl: (7) Failed to connect to 127.0.0.1 port 50502: Connection refused**

5.But when I tried doing 
`kubectl get svc`
NAME                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
kubernetes          ClusterIP   10.96.0.1       <none>        443/TCP          84s
tomcat-deployment   NodePort    10.106.75.253   <none>        8080:30612/TCP   7s
It is showing some other port number. I tried using both of them to open in the browser, but it did not connect.

6.This is what it shows when I try to access http://127.0.0.1:50502  in the local browser:

**HTTP Status 404 – Not Found Type Status Report**

**Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.**

7. I tried stopping minikube and again deleting it. Not at all sure what the problem might be. Please help ...

**Comment by afbjorklund** [comment]
NodePort deployments don't work with Docker Desktop, unfortunately. Only with Docker Engine.

So you will need to use a LoadBalancer deployment and 'minikube tunnel` instead, or use a VM.

**Comment by ntippabhatla** [comment]
Thanks for giving me the clarity..!
But I deleted and reinstalled it. Now what I observed is it is using minikube tunnel and exposing the website.
But the tomcat deployment still shows the error mentioned above.
`apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 1
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080`  

But where as the nginx deployment is running successfully.
```
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
```

**Also if I am trying to implement the same on a 3 Centos servers through my Mac OS, it tells the same issue. Followed this link [](https://www.tecmint.com/install-kubernetes-cluster-on-centos-7/) How am I supposed to resolve that?**

**Comment by afbjorklund** [comment]
>  But the tomcat deployment still shows the error mentioned above.

It should not return 127.0.0.1 when using the minikube load balancer:
https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access

**Comment by ntippabhatla** [comment]
1. So for nginx deployment its taking me to the successfull page and is executing good. Without including it as load balancer port.

`kubectl expose deployment/nginx-deployment --type="NodePort" --port 80
service/nginx-deployment exposed
#### ~ % kubectl get services nginx-deployment
NAME               TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
nginx-deployment   NodePort   10.107.101.196   <none>        80:32580/TCP   11s
###### ~ % minikube service nginx-deployment
|-----------|------------------|-------------|-------------------------|
| NAMESPACE |       NAME       | TARGET PORT |           URL           |
|-----------|------------------|-------------|-------------------------|
| default   | nginx-deployment |          80 | http://172.17.0.3:32580 |
|-----------|------------------|-------------|-------------------------|
🏃  Starting tunnel for service nginx-deployment.
|-----------|------------------|-------------|------------------------|
| NAMESPACE |       NAME       | TARGET PORT |          URL           |
|-----------|------------------|-------------|------------------------|
| default   | nginx-deployment |             | http://127.0.0.1:51175 |
|-----------|------------------|-------------|------------------------|
🎉  Opening service default/nginx-deployment in default browser...`


2. But for tomcat-deployment it says HTTP 404 error.

`kubectl expose deployment/tomcat-deployment --type="NodePort" --port 80
service/tomcat-deployment exposed
####~ % kubectl get services tomcat-deployment
NAME                TYPE       CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
tomcat-deployment   NodePort   10.101.155.207   <none>        80:30299/TCP   11s
#### ~ % minikube service tomcat-deployment
|-----------|-------------------|-------------|-------------------------|
| NAMESPACE |       NAME        | TARGET PORT |           URL           |
|-----------|-------------------|-------------|-------------------------|
| default   | tomcat-deployment |          80 | http://172.17.0.3:30299 |
|-----------|-------------------|-------------|-------------------------|
🏃  Starting tunnel for service tomcat-deployment.
|-----------|-------------------|-------------|------------------------|
| NAMESPACE |       NAME        | TARGET PORT |          URL           |
|-----------|-------------------|-------------|------------------------|
| default   | tomcat-deployment |             | http://127.0.0.1:51309 |
|-----------|-------------------|-------------|------------------------|
🎉  Opening service default/tomcat-deployment in default browser...`

**Comment by medyagh** [comment]
@ntippabhatla does this tutorial on the minikube website help ? https://minikube.sigs.k8s.io/docs/handbook/accessing/

**Comment by ntippabhatla** [comment]
Yes, I was able to work it out. Thank you. I think we can close the issue.
