### ISSUE TITLE
go mod: upgrade lib k8s.io/kubernetes v1.17.3 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8656]
in our go mod we are using k8s.io/kubernetes v1.17.3 https://github.com/kubernetes/minikube/blob/5e9bb011b7cea625de5b3493c70fe42968edac3d/go.mod#L86

I would accept a PR that bumps this to a more recent version

**Comment by vinu2003** [comment]
Hey @medyagh, Isn't this task involves updating matching version of all three k8s.io/... components in go.mod file ?
```
k8s.io/api kubernetes-1.18.5
k8s.io/apimachinery kubernetes-1.18.5
k8s.io/client-go kubernetes-1.18.5
```

or only k8s.io/kubernetes v1.17.3  => k8s.io/kubernetes v1.18.5 ? Correct me if I am wrong please.
