### ISSUE TITLE
hyperv: Error :  provision: IP not found

### ISSUE THREAD

**Issue by hparekh1982** [kubernetes/minikube#8659]
Getting an Error on Window Machine. Please help to solve 

PS C:\AWS Class> minikube start --vm-driver="hyperv" --hyperv-virtual-switch="minikube"
* minikube v1.11.0 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\AWS Class>

Regrads
Hardik

**Comment by hparekh1982** [comment]
Hi Guys, 

Providing more information of output of ==> minikube logs


PS C:\AWS Class> minikube logs
E0707 12:05:57.666177   23832 logs.go:200] Failed to list containers for "kube-apiserver": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0707 12:06:00.205547   23832 logs.go:200] Failed to list containers for "etcd": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0707 12:06:02.734888   23832 logs.go:200] Failed to list containers for "coredns": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0707 12:06:05.269913   23832 logs.go:200] Failed to list containers for "kube-scheduler": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0707 12:06:07.784609   23832 logs.go:200] Failed to list containers for "kube-proxy": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0707 12:06:10.282455   23832 logs.go:200] Failed to list containers for "kubernetes-dashboard": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0707 12:06:12.778169   23832 logs.go:200] Failed to list containers for "storage-provisioner": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E0707 12:06:15.354007   23832 logs.go:200] Failed to list containers for "kube-controller-manager": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
* ==> Docker <==
E0707 12:06:17.882809   23832 logs.go:178] command /bin/bash -c "sudo journalctl -u docker -n 60" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""
*
* ==> container status <==
E0707 12:06:20.367130   23832 logs.go:178] command /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""
*
* ==> describe nodes <==
E0707 12:06:22.844882   23832 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""
*
* ==> dmesg <==
E0707 12:06:25.346974   23832 logs.go:178] command /bin/bash -c "sudo dmesg -PH -L=never --level warn,err,crit,alert,emerg | tail -n 60" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""
*
* ==> kernel <==
E0707 12:06:27.903361   23832 logs.go:178] command /bin/bash -c "uptime && uname -a && grep PRETTY /etc/os-release" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""
*
* ==> kubelet <==
E0707 12:06:30.596904   23832 logs.go:178] command /bin/bash -c "sudo journalctl -u kubelet -n 60" failed with error: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found output: ""

! unable to fetch logs for: Docker, container status, describe nodes, dmesg, kernel, kubelet

**Comment by medyagh** [comment]
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by priyawadhwa** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
