### ISSUE TITLE
Docker_Linux flake: TestNetworkPlugins/group/kubenet/DNS

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8666]
TestNetworkPlugins/group/kubenet/DNS

```

net_test.go:145: (dbg) Run:  kubectl --context kubenet-20200707215219-5369 exec deployment/netcat -- nslookup kubernetes.default
net_test.go:145: (dbg) Non-zero exit: kubectl --context kubenet-20200707215219-5369 exec deployment/netcat -- nslookup kubernetes.default: exit status 1 (71.683882ms)
** stderr ** 
	Error from server (NotFound): the server could not find the requested resource
** /stderr **
```

https://storage.googleapis.com/minikube-builds/logs/8663/776e6c4/Docker_Linux.html#fail_TestNetworkPlugins%2fgroup%2fkubenet%2fDNS

**Comment by tstromberg** [comment]
FWIW, I'm having a hell of a time trying to duplicate this issue on my workstation so far :(

**Comment by tstromberg** [comment]
Stats do show that this can be flaky, however, so I will keep trying.

```
docker_Linux      | 2020-07-05 |  75% | 9 of 12
docker_Linux      | 2020-07-06 |  75% | 9 of 12
docker_Linux      | 2020-07-07 | 100% | 12 of 12
docker_Linux      | 2020-07-08 |  70% | 7 of 10
docker_Linux      | 2020-07-09 | 100% | 6 of 6
```

**Comment by tstromberg** [comment]
This particular combination is unlikely to be common, so I am tempted to disable the test in this case. I'm going to try a bit more to duplicate it, however:

`loop_until_failure env TEST_ARGS="-minikube-start-args='--vm-driver=docker' -test.run=TestNetworkPlugins/group/kubenet --cleanup=false" make integration`

**Comment by medyagh** [comment]
I haven't seen this in the Flake Chart recentlt
