### ISSUE TITLE
Error when starting minikube start command

### ISSUE THREAD

**Issue by tangent-devop** [kubernetes/minikube#8667]
**Steps to reproduce the issue:** 

1.minikube start 
2. 
3.

**Full output of failed command:** 
minikube v1.11.0 on Microsoft Windows 10 Home 10.0.19041 Build 19041
* Automatically selected the hyperv driver
* Downloading VM boot image ...
E0708 00:43:21.460390    4112 iso.go:86] Unable to download https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso.sha256 Dst:C:\Users\Rub\.minikube\cache\iso\minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0] Decompressors:map[bz2:0x2bae6d0 gz:0x2bae6d0 tar.bz2:0x2bae6d0 tar.gz:0x2bae6d0 tar.xz:0x2bae6d0 tbz2:0x2bae6d0 tgz:0x2bae6d0 txz:0x2bae6d0 xz:0x2bae6d0 zip:0x2bae6d0] Getters:map[file:0xc00005ed50 http:0xc0000043e0 https:0xc000004400] Dir:false ProgressListener:0x2b82e70 Options:[0xc3b9c0]}: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso.sha256: Bad Request
* Downloading VM boot image ...
E0708 00:43:22.028955    4112 iso.go:86] Unable to download https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso.sha256 Dst:C:\Users\Rub\.minikube\cache\iso\minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0] Decompressors:map[bz2:0x2bae6d0 gz:0x2bae6d0 tar.bz2:0x2bae6d0 tar.gz:0x2bae6d0 tar.xz:0x2bae6d0 tbz2:0x2bae6d0 tgz:0x2bae6d0 txz:0x2bae6d0 xz:0x2bae6d0 zip:0x2bae6d0] Getters:map[file:0xc0006d8070 http:0xc000448080 https:0xc0004480c0] Dir:false ProgressListener:0x2b82e70 Options:[0xc3b9c0]}: invalid checksum: Error downloading checksum file: Get https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso.sha256: Bad Request
* Downloading VM boot image ...
E0708 00:43:22.340615    4112 iso.go:86] Unable to download https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso.sha256 Dst:C:\Users\Rub\.minikube\cache\iso\minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0] Decompressors:map[bz2:0x2bae6d0 gz:0x2bae6d0 tar.bz2:0x2bae6d0 tar.gz:0x2bae6d0 tar.xz:0x2bae6d0 tbz2:0x2bae6d0 tgz:0x2bae6d0 txz:0x2bae6d0 xz:0x2bae6d0 zip:0x2bae6d0] Getters:map[file:0xc00005f320 http:0xc000004780 https:0xc0000047c0] Dir:false ProgressListener:0x2b82e70 Options:[0xc3b9c0]}: invalid checksum: Error downloading checksum file: Get https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso.sha256: Bad Request
*
X error provisioning host: Failed to cache ISO: unable to cache ISO:
  https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso.sha256 Dst:C:\Users\Rub\.minikube\cache\iso\minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0] Decompressors:map[bz2:0x2bae6d0 gz:0x2bae6d0 tar.bz2:0x2bae6d0 tar.gz:0x2bae6d0 tar.xz:0x2bae6d0 tbz2:0x2bae6d0 tgz:0x2bae6d0 txz:0x2bae6d0 xz:0x2bae6d0 zip:0x2bae6d0] Getters:map[file:0xc00005ed50 http:0xc0000043e0 https:0xc000004400] Dir:false ProgressListener:0x2b82e70 Options:[0xc3b9c0]}: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso.sha256: Bad Request
  https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso.sha256 Dst:C:\Users\Rub\.minikube\cache\iso\minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0] Decompressors:map[bz2:0x2bae6d0 gz:0x2bae6d0 tar.bz2:0x2bae6d0 tar.gz:0x2bae6d0 tar.xz:0x2bae6d0 tbz2:0x2bae6d0 tgz:0x2bae6d0 txz:0x2bae6d0 xz:0x2bae6d0 zip:0x2bae6d0] Getters:map[file:0xc0006d8070 http:0xc000448080 https:0xc0004480c0] Dir:false ProgressListener:0x2b82e70 Options:[0xc3b9c0]}: invalid checksum: Error downloading checksum file: Get https://github.com/kubernetes/minikube/releases/download/v1.11.0/minikube-v1.11.0.iso.sha256: Bad Request
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso.sha256 Dst:C:\Users\Rub\.minikube\cache\iso\minikube-v1.11.0.iso.download Pwd: Mode:2 Detectors:[0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0 0x2bae6d0] Decompressors:map[bz2:0x2bae6d0 gz:0x2bae6d0 tar.bz2:0x2bae6d0 tar.gz:0x2bae6d0 tar.xz:0x2bae6d0 tbz2:0x2bae6d0 tgz:0x2bae6d0 txz:0x2bae6d0 xz:0x2bae6d0 zip:0x2bae6d0] Getters:map[file:0xc00005f320 http:0xc000004780 https:0xc0000047c0] Dir:false ProgressListener:0x2b82e70 Options:[0xc3b9c0]}: invalid checksum: Error downloading checksum file: Get https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.11.0.iso.sha256: Bad Request

*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by RA489** [comment]
@tangent-devop looks like you are using Minikube in china and unable to download ISO due to restrictions. can you please try out his WIP PR https://github.com/kubernetes/minikube/pull/8555 and let me know if that works for you?

**Comment by priyawadhwa** [comment]
Hey @tangent-devop did you get a chance to try the suggestions in the PR?

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this for now, the workaround for running minikube in China is documented. Feel free to reopen if this remains an issue.
