### ISSUE TITLE
 Error starting host: Error getting state for host: unexpected EOF

### ISSUE THREAD

**Issue by shaikatzir** [kubernetes/minikube#867]
**Minikube version** (use `minikube version`):
 v0.12.2

**Environment**:
- **OS** (e.g. from /etc/os-release):  Ubuntu 14.04 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm
- **Docker version** (e.g. `docker -v`): Docker version 1.12.3
- **Install tools**: 
- **Others**:

**What happened**:
When trying to start a cluster I get an error:

     ✗ sudo minikube start
    Starting local Kubernetes cluster...
    E1130 15:29:30.277137   18796 start.go:92] Error starting host: Error getting state for host:     unexpected EOF. Retrying.
    E1130 15:29:30.277941   18796 start.go:98] Error starting host:  Error getting state for host: unexpected EOF

**Comment by r2d4** [comment]
You don't need sudo to run minikube.  I suspect that something is wrong with your cached ISO.  The download could have been interrupted or invalid.  

Try to `rm -rf ~/.minikube/cache` and then try to run minikube

**Comment by shaikatzir** [comment]
Ran it:
    
     ~ rm -rf ~/.minikube/cache
     ~ minikube start
    Starting local Kubernetes cluster...
    E1130 19:45:40.353550    6859 start.go:92] Error starting host: Error getting state for host:   unexpected EOF. Retrying.
    E1130 19:45:40.354129    6859 start.go:98] Error starting host:  Error getting state for host:    unexpected EOF

Still have the same issue.
I suspect something with the "kvm" driver but I have no proof to back it up.
I wasn't able to run it with VirtualBox though.

**Comment by r2d4** [comment]
As a last resort, can you try

```
minikube delete
rm -rf ~/.minikube
```

**Comment by shaikatzir** [comment]
Seems to solve it. But then I got a new error...
       
       ➜  ~ minikube delete 
	Deleting local Kubernetes cluster...
	Errors occurred deleting machine:  unexpected EOF
	➜  ~ rm -rf ~/.minikube
	➜  ~ minikube start  
	Starting local Kubernetes cluster...
	Downloading Minikube ISO
	 36.00 MB / 36.00 MB [==============================================] 100.00% 0s
	E1130 21:08:00.026929    4265 start.go:92] Error starting host: Error creating host: Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path". Retrying.
	E1130 21:08:00.027295    4265 start.go:98] Error starting host:  Error creating host: Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
	➜  ~ minikube start --vm-driver=kvm
	Starting local Kubernetes cluster...
	E1130 21:09:16.213244    4388 start.go:92] Error starting host: Error creating host: Error creating machine: Error in driver during machine creation: [Code-1] [Domain-20] internal error: no supported architecture for os type 'hvm'. Retrying.
	E1130 21:09:16.214181    4388 start.go:98] Error starting host:  Error creating host: Error creating machine: Error in driver during machine creation: [Code-1] [Domain-20] internal error: no supported architecture for os type 'hvm'
	➜  ~

**Comment by r2d4** [comment]
Are you running minikube inside of a VM? You won't be able to do nested virtualization.  However if you're using windows or OS X you should use those minikube binaries.

**Comment by shaikatzir** [comment]
It's not a VM. I'm running it directly from my ubuntu 14.04 terminal. I have no vm running.

**Comment by r2d4** [comment]
Do you have VT-x enabled? `egrep -c '(vmx|svm)' /proc/cpuinfo` should not return 0.

If you don't have it enabled, you can follow the steps here to enable it

**Comment by shaikatzir** [comment]
```
➜  ~ egrep -c '(vmx|svm)' /proc/cpuinfo
4
```
Running on lenovo yoga pro 2

**Comment by r2d4** [comment]
Are you able to use libvirtd and KVM with other images?  
Can you connect to the libvirt socket `virsh -c qemu:///system list`?
If that doesn't work, make sure you've properly set up libvirtd and added yourself to the libvirtd group.  It can be a little tricky to set up properly the first time on some distros.

**Comment by shaikatzir** [comment]
Finally works!
I checked if the kvm works by running:

```
➜  ~ sudo /usr/sbin/kvm-ok
[sudo] password for shaika: 
INFO: /dev/kvm does not exist
HINT:   sudo modprobe kvm_intel
INFO: Your CPU supports KVM extensions
INFO: KVM (vmx) is disabled by your BIOS
HINT: Enter your BIOS setup and enable Virtualization Technology (VT),
      and then hard poweroff/poweron your system
KVM acceleration can NOT be used
```

I enabled the virtualization in the BIOS and checked kvm installation again.
This time everything worked fine.

**Comment by Aaqib041** [comment]
Hi ,

I am facing similar problem while running **minikube start.** 
I am using vagrant ubuntu box. I followed your suggestions given above by running **rm -rf ~/.minikube/cache** . But while trying to run **minikube delete** , I am getting error.
Also , I checked **egrep -c '(vmx|svm)' 
![111](https://cloud.githubusercontent.com/assets/3587210/21472744/cfdab3d6-cb0d-11e6-80ae-42318ce79ddb.JPG)
![123](https://cloud.githubusercontent.com/assets/3587210/21472745/d54898a6-cb0d-11e6-8d3c-02f12bab0ccd.JPG)

/proc/cpuinfo** , its returning 0 for me. Please guide to resolve this.

**Comment by dlorenc** [comment]
Hey @Aaqib041,

You won't be able to run minikube inside vagrant. What is your host system? You should be able to run minikube there instead of inside the VM.

**Comment by Aaqib041** [comment]
@dlorenc ,

I am using Windows Laptop with O.S Win 10 , I wanted to use minikube in Ubuntu and hence using vagrant for the same. !!!

**Comment by Aaqib041** [comment]
@dlorenc ..
Hi , I was trying to create Ubuntu box using vagrant but got to know I cannot do that. So now I have downloaded minikube for windows.However ,I am still facing issue while running **minikube start**.
I have tried **minkube delete**.Here is the output of **minikube start --show-libmachine-logs**. Please help.
![k4](https://cloud.githubusercontent.com/assets/3587210/21485681/9335dbb2-cbcc-11e6-87e8-8b59543c908f.JPG)

**Comment by KrishnanBabu** [comment]
Hi i am installing minikube inside the VMware VM.The nested virtualization is enabled.i tired installing Oracle virtualbox and also tired installing kvm.It creates a vm but i am getting an error as below
 "error starting host:error getting state for host".

 I tried starting the minikube with the log ,its showing the errror as 
"ssh cmd err,output:exit status 255:(minikube)dbg | error getting ssh command 'exit 0' :something went wrong running an ssh command!".
Need help.

**Comment by abitrolly** [comment]
After enabling VT-x in BIOS I had to do `rm -rf ~/.minikube` to solve the original problem. I'd wish that `minikube` could do this `kvm` driver troubleshooting itself.

**Comment by michaeldg** [comment]
I experience the same issue, I have virtualbox running with several other VM's. I run Ubuntu 16.04.3, I am installing from my laptop (so: bare metal running Linux, not from inside a VM).

Output of the commands:
root@michaellaptop2016:~# minikube start --vm-driver=virtualbox
Starting local Kubernetes cluster...
E1016 16:38:14.140902    8502 start.go:83] Error starting host: Error creating. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path". Retrying.
E1016 16:38:16.162958    8502 start.go:83] Error starting host: Error creating. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path". Retrying.
E1016 16:38:18.180377    8502 start.go:83] Error starting host: Error creating. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path". Retrying.
E1016 16:38:18.180459    8502 start.go:89] Error starting host:  Error creating. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
Error creating. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
Error creating. Error with pre-create check: "VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path"
root@michaellaptop2016:~# minikube start --vm-driver=kvm
Starting local Kubernetes cluster...
E1016 16:38:22.357748    8585 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E1016 16:38:22.372898    8585 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E1016 16:38:22.384285    8585 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E1016 16:38:22.384304    8585 start.go:89] Error starting host:  Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address

root@michaellaptop2016:~# which VBoxManage
/usr/bin/VBoxManage

**Comment by lbenevid** [comment]
$ rm -rf ~/.minikube
$ minikube start

**Comment by bidianqing** [comment]
![image](https://user-images.githubusercontent.com/12196280/34594638-3ebb49e2-f20d-11e7-8f59-78c774cd9a0b.png)
Please tell me what to do?

**Comment by ArtemZ** [comment]
I'm having the same issue

> E0217 15:06:08.998173   24429 start.go:156] Error starting host:  Error creating host: Error executing step: Running precreate checks.
> : VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

yet VBoxManage is available in my system

**Comment by sumanthyasumreddy** [comment]
hi..i am also having the same below error when I am trying to run the 'Minikube start' command on the Linux AWS instance. VBoxManage is already installed on my PC (having Windows 10 OS) from where I am launching my Linux AWS instance. Can someone help. 

E0222 00:15:57.464329   32174 start.go:165] Error starting host:  Error creating host: Error executing step: Running precreate checks.
: VBoxManage not found. Make sure VirtualBox is installed and VBoxManage is in the path

**Comment by sumanthyasumreddy** [comment]
hi

**Comment by sumanthyasumreddy** [comment]
hi

**Comment by hudsantos** [comment]
$ minikube start --vm-driver kvm2
Starting local Kubernetes v1.9.0 cluster...
Starting VM...
Downloading Minikube ISO
 142.22 MB / 142.22 MB [============================================] 100.00% 0s
E0225 22:55:51.088931   16526 start.go:159] Error starting host: Error creating new host: dial tcp: missing address.

 Retrying.
E0225 22:55:51.089960   16526 start.go:165] Error starting host:  Error creating new host: dial tcp: missing address
$ egrep -o '(vmx|svm)' /proc/cpuinfo
vmx
vmx
$ virsh -c qemu:///system list
 Id    Name                           State
----------------------------------------------------
# /etc/init.d/libvirt-bin stop
 * Stopping libvirt management daemon libvirtd                                                                                                         [ OK ] 
# /etc/init.d/libvirt-bin start
 * Starting libvirt management daemon libvirtd                                                                                                         [ OK ] 
# /etc/init.d/libvirt-bin status
 * Checking status of libvirt management daemon libvirtd                                                                                               [ OK ] 
$ whoami
hudson
$ grep libvirtd /etc/group
libvirtd:x:127:hudson

**Comment by markroxor** [comment]
I am also getting the same error like @sumanthyasumreddy and @ArtemZ

**Comment by jorgesece** [comment]
sudo modprobe vboxnetadp
