### ISSUE TITLE
Heapster addon is missing in minikube v0.12.2 for Windows

### ISSUE THREAD

**Issue by dannyk81** [kubernetes/minikube#868]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG REPORT

**Minikube version**: v0.12.2

**Environment**:
- **OS**: (e.g. from /etc/os-release): Microsoft Windows [Version 10.0.10586]
- **VM Driver**: virtualbox
- **Docker version**: 1.11.1, build 5604cbe

**What happened**:

Accordint to #818, heapster addon is expected to me part of minikube addons list, however it seems that it is missing (maybe it's only missing in Windows minikube ?):

```
C:\minikube>minikube addons list
- addon-manager: enabled
- dashboard: enabled
- kube-dns: enabled

```
**What you expected to happen**:

Expected it to be listed :)

**How to reproduce it**:

run `minikube addons list`

**Comment by r2d4** [comment]
Hey @dannyk81 we haven't released a binary with the heapster addon merged in yet - but for now you can grab one from our PR builds at

```
https://storage.googleapis.com/minikube-builds/865/minikube-darwin-amd64
https://storage.googleapis.com/minikube-builds/865/minikube-linux-amd64
https://storage.googleapis.com/minikube-builds/865/minikube-windows-amd64.exe
```

You'll also need to enable it
`minikube addons enable heapster`

The heapster addon will be in minikube v0.12.3

**Comment by dannyk81** [comment]
Thanks @r2d4 !
