### ISSUE TITLE
Error dialing TCP: ssh: handshake failed: read tcp 127.0.0.1:40082->127.0.0.1:40703: read: connection reset by peer

### ISSUE THREAD

**Issue by babiaastor** [kubernetes/minikube#8685]
**Steps to reproduce the issue:** 

1. minikube delete --all

2. minikube start --alsologtostderr -v=8
[issue.txt](https://github.com/kubernetes/minikube/files/4898160/issue.txt)

3.Environment
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd
6.1.6_Ubuntur137129
 minikube v1.11.0 en Ubuntu 20.04

Windows 10 with Virtual Box 6.1 running Ubuntu 20.03

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@babiaastor the lgos you attached are not fully pasted. can you paste the full log

but I see this
```
VBoxManage: error: Code NS_ERROR_INVALID_ARG (0x80070057) - Invalid argument value (extended info not availabl
```
that could mean you have a failing vbox, u might wanna reinstall it

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker


docker driver is our preferd driver
for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by babiaastor** [comment]
Hi
After reinstalling again

1. curl -s https://storage.googleapis.com/kubernetes-release/rele                                                                             ase/stable.txt`/bin/linux/amd64/kubectl
2. chmod +x ./kubectl
3 sudo mv ./kubectl /usr/local/bin/kubectl

I have seen the following
rodrigo@rodrigo-VirtualBox:~$ kubectl version -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "18",
    "gitVersion": "v1.18.5",
    "gitCommit": "e6503f8d8f769ace2f338794c914a96fc335df0f",
    "gitTreeState": "clean",
    "buildDate": "2020-06-26T03:47:41Z",
    "goVersion": "go1.13.9",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
**The connection to the server localhost:8080 was refused - did you specify the ri                                                                             ght host or port?**




rodrigo@rodrigo-VirtualBox:~$ minikube version
**minikube version: v1.12.0**
commit: c83e6c47124b71190e138dbc687d2556d31488d6

Then after installing minikube. Check Logs. 
[logs.txt](https://github.com/kubernetes/minikube/files/4911701/logs.txt)

Installation failed and then virtual image is not valid. Check error from virtual box console
Failed to open image '\VM\ubuntu-basica\ubuntu-basica.vdi' for writing due to wrong permissions (VERR_VD_IMAGE_READ_ONLY).
AHCI: Failed to attach drive to Port0 (VERR_VD_IMAGE_READ_ONLY).

**Comment by priyawadhwa** [comment]
Hey @babiaastor I tried searching for the virtualbox error and found this forum:

https://forums.virtualbox.org/viewtopic.php?f=3&t=17865

it seems you have to install virtualbox as an administrator. Could you try uninstalling it and then reinstalling it as an administrator?

**Comment by babiaastor** [comment]
Hi

I was able to solve this issue.

It was a problem with my memory  and installation of docker

Thanks for your help

**Comment by priyawadhwa** [comment]
Hey @babiaastor glad to hear it, I'll go ahead and close this issue.
