### ISSUE TITLE
virtualbox:  dial tcp 127.0.0.1:51011: connect: connection refused

### ISSUE THREAD

**Issue by juettemann** [kubernetes/minikube#8689]
Minikube freezers when I bridge the network.

It seems the issue was raised a couple of times, but I could not see a solution. Apologies if I missed something, please point me to the correct place in that case

**Steps to reproduce the issue:** 

Versions:
- MacOS 10.14.6
- minikube version: v1.12.0; commit: c83e6c47124b71190e138dbc687d2556d31488d6
- Virtualbox 6.1.10 r138449 (Qt5.6.3)

![Screenshot 2020-07-10 at 13 39 43](https://user-images.githubusercontent.com/752245/87120390-da42ce80-c2b2-11ea-840d-7a2fcdfce1be.png)

**Full output of failed command:** 
minikube start --driver=virtualbox --alsologtostderr -v 3
I0710 13:34:43.541677   30010 start.go:99] hostinfo: {"hostname":"FVFW40CMJ1WV","uptime":152509,"bootTime":1594206774,"procs":348,"os":"darwin","platform":"darwin","platformFamily":"","platformVersion":"10.14.6","kernelVersion":"18.7.0","virtualizationSystem":"","virtualizationRole":"","hostid":"c41337a1-0ec3-3896-a954-a1f85e849d53"}
W0710 13:34:43.541848   30010 start.go:107] gopshost.Virtualization returned error: not implemented yet
😄  minikube v1.12.0 on Darwin 10.14.6
I0710 13:34:43.574231   30010 notify.go:125] Checking for updates...
I0710 13:34:43.583588   30010 driver.go:257] Setting default libvirt URI to qemu:///system
✨  Using the virtualbox driver based on existing profile
I0710 13:34:43.830412   30010 start.go:209] selected driver: virtualbox
I0710 13:34:43.830435   30010 start.go:608] validating driver "virtualbox" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.12.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2200 CPUs:2 DiskSize:20000 Driver:virtualbox HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:192.168.99.103 Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[dashboard:true default-storageclass:true storage-provisioner:true] VerifyComponents:map[apiserver:true system_pods:true]}
I0710 13:34:43.830663   30010 start.go:619] status for virtualbox: {Installed:true Healthy:true NeedsImprovement:false Error:<nil> Fix: Doc:}
I0710 13:34:43.830850   30010 iso.go:118] acquiring lock: {Name:mk2c99223ced7add344e59d125da8c048db8edf5 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
👍  Starting control plane node minikube in cluster minikube
I0710 13:34:43.843859   30010 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0710 13:34:43.843926   30010 preload.go:103] Found local preload: /Users/juettema/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v4-v1.18.3-docker-overlay2-amd64.tar.lz4
I0710 13:34:43.843943   30010 cache.go:51] Caching tarball of preloaded images
I0710 13:34:43.844027   30010 preload.go:129] Found /Users/juettema/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v4-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0710 13:34:43.844043   30010 cache.go:54] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0710 13:34:43.844181   30010 profile.go:150] Saving config to /Users/juettema/.minikube/profiles/minikube/config.json ...
I0710 13:34:43.849054   30010 cache.go:178] Successfully downloaded all kic artifacts
I0710 13:34:43.849112   30010 start.go:240] acquiring machines lock for minikube: {Name:mk34725a5b0b69429fd079ffd65ad043524bc2f1 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0710 13:34:43.849249   30010 start.go:244] acquired machines lock for "minikube" in 110.051µs
I0710 13:34:43.849274   30010 start.go:88] Skipping create...Using existing machine configuration
I0710 13:34:43.849285   30010 fix.go:53] fixHost starting: 
I0710 13:34:43.849669   30010 main.go:115] libmachine: COMMAND: /usr/local/bin/VBoxManage showvminfo minikube --machinereadable
I0710 13:34:44.050161   30010 main.go:115] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="77782d8c-0371-463e-b8e2-53ed6825c6b0"
CfgFile="/Users/juettema/.minikube/machines/minikube/minikube/minikube.vbox"
SnapFldr="/Users/juettema/.minikube/machines/minikube/minikube/Snapshots"
LogFldr="/Users/juettema/.minikube/machines/minikube/minikube/Logs"
hardwareuuid="77782d8c-0371-463e-b8e2-53ed6825c6b0"
memory=2200
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2020-07-10T05:25:04.030000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="/Users/juettema/.minikube/machines/minikube/boot2docker.iso"
"SATA-ImageUUID-0-0"="2f39c760-d59d-4db9-aebd-6cccac3fec74"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="/Users/juettema/.minikube/machines/minikube/disk.vmdk"
"SATA-ImageUUID-1-0"="196400c6-feea-4f4c-84e1-9c90af02b3ac"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
bridgeadapter1="en0: Wi-Fi (AirPort)"
macaddress1="080027B79245"
cableconnected1="on"
nic1="bridged"
nictype1="virtio"
nicspeed1="0"
hostonlyadapter2="vboxnet0"
macaddress2="080027E37C92"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="coreaudio"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="Users"
SharedFolderPathMachineMapping1="/Users"
VRDEActiveConnection="off"
VRDEClients==0
videocap="on"
videocapaudio="off"
capturescreens=""
capturefilename="/Users/juettema/.minikube/machines/minikube/minikube/minikube.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts="vc_enabled=true,ac_enabled=false,ac_profile=med"
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=2
GuestAdditionsVersion="5.2.42 r137960"
GuestAdditionsFacility_VirtualBox Base Driver=50,1594358730432
GuestAdditionsFacility_VirtualBox System Service=50,1594358730914
GuestAdditionsFacility_Seamless Mode=0,1594358731457
GuestAdditionsFacility_Graphics Mode=0,1594358730432
}
I0710 13:34:44.050375   30010 main.go:115] libmachine: STDERR:
{
}
I0710 13:34:44.050546   30010 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0710 13:34:44.050578   30010 fix.go:131] unexpected machine state, will restart: <nil>
🏃  Updating the running virtualbox "minikube" VM ...
I0710 13:34:44.075358   30010 machine.go:88] provisioning docker machine ...
I0710 13:34:44.075394   30010 buildroot.go:163] provisioning hostname "minikube"
I0710 13:34:44.075744   30010 main.go:115] libmachine: Using SSH client type: native
I0710 13:34:44.076195   30010 main.go:115] libmachine: &{{{<nil> 0 [] [] []} docker [0x43b8320] 0x43b82f0 <nil>  [] 0s} 127.0.0.1 51011 <nil> <nil>}
I0710 13:34:44.076216   30010 main.go:115] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I0710 13:34:44.076496   30010 main.go:115] libmachine: Error dialing TCP: dial tcp 127.0.0.1:51011: connect: connection refused
I0710 13:34:47.078884   30010 main.go:115] libmachine: Error dialing TCP: dial tcp 127.0.0.1:51011: connect: connection refused
I0710 13:34:50.080196   30010 main.go:115] libmachine: Error dialing TCP: dial tcp 127.0.0.1:51011: connect: connection refused
I0710 13:34:53.080943   30010 main.go:115] libmachine: Error dialing TCP: dial tcp 127.0.0.1:51011: connect: connection refused
I0710 13:34:56.083256   30010 main.go:115] libmachine: Error dialing TCP: dial tcp 127.0.0.1:51011: connect: connection refused
I0710 13:34:59.088212   30010 main.go:115] libmachine: Error dialing TCP: dial tcp 127.0.0.1:51011: connect: connection refused
I0710 13:35:02.092397   30010 main.go:115] libmachine: Error dialing TCP: dial tcp 127.0.0.1:51011: connect: connection refused
I0710 13:35:05.094098   30010 main.go:115] libmachine: Error dialing TCP: dial tcp 127.0.0.1:51011: connect: connection refused

**Optional: Full output of `minikube logs` command:**
minikube logs
E0710 13:36:00.744322   30062 logs.go:200] Failed to list containers for "kube-apiserver": docker: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused
E0710 13:36:03.806911   30062 logs.go:200] Failed to list containers for "etcd": docker: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused
E0710 13:36:06.993939   30062 logs.go:200] Failed to list containers for "coredns": docker: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused
E0710 13:36:10.562076   30062 logs.go:200] Failed to list containers for "kube-scheduler": docker: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused
E0710 13:36:14.107271   30062 logs.go:200] Failed to list containers for "kube-proxy": docker: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused
E0710 13:36:17.063995   30062 logs.go:200] Failed to list containers for "kubernetes-dashboard": docker: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused
E0710 13:36:20.262681   30062 logs.go:200] Failed to list containers for "storage-provisioner": docker: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused
E0710 13:36:23.186759   30062 logs.go:200] Failed to list containers for "kube-controller-manager": docker: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused
==> Docker <==
E0710 13:36:26.572525   30062 logs.go:178] command /bin/bash -c "sudo journalctl -u docker -n 60" failed with error: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused output: ""

==> container status <==
E0710 13:36:28.975660   30062 logs.go:178] command /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a" failed with error: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused output: ""

==> describe nodes <==
E0710 13:36:32.170745   30062 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused output: ""

==> dmesg <==
E0710 13:36:34.562427   30062 logs.go:178] command /bin/bash -c "sudo dmesg -PH -L=never --level warn,err,crit,alert,emerg | tail -n 60" failed with error: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused output: ""

==> kernel <==
E0710 13:36:38.334929   30062 logs.go:178] command /bin/bash -c "uptime && uname -a && grep PRETTY /etc/os-release" failed with error: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused output: ""

==> kubelet <==
E0710 13:36:40.535790   30062 logs.go:178] command /bin/bash -c "sudo journalctl -u kubelet -n 60" failed with error: NewSession: new client: new client: dial tcp 127.0.0.1:51011: connect: connection refused output: ""

❗  unable to fetch logs for: Docker, container status, describe nodes, dmesg, kernel, kubelet
<details>

</details>

**Comment by medyagh** [comment]
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by juettemann** [comment]
@medyagh 
Thanks, that did the trick. I have 2 VPNs installed, Pulse Secure [https://www.pulsesecure.net/] and ExpressVPN. None was running at the time. For my understanding, what is the issue with VPNs? 

One issue remains, though I understand if it can't be answered here. I can't seem to get an external IP, could this also be connected to the VPNs?

```
NAME                     TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE 
service/db               ClusterIP      10.106.212.41   <none>        5432/TCP       24h
service/kubernetes       ClusterIP      10.96.0.1       <none>        443/TCP        24h
service/redis            ClusterIP      10.105.191.80   <none>        6379/TCP       24h
service/result-service   LoadBalancer   10.103.61.74    <pending>     80:30616/TCP   24h
service/voting-service   LoadBalancer   10.99.118.12    <pending>     80:30233/TCP   24h
```
Thank you!

**Comment by priyawadhwa** [comment]
Hey @juettemann to get an external IP for type `LoadBalancer` you'll need to run `minikube tunnel` in a separate terminal window. The docs for this can be found here:

https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access

**Comment by juettemann** [comment]
@priyawadhwa Thanks so much, that was the missing piece!

**Comment by priyawadhwa** [comment]
@juettemann glad to hear it! I'll go ahead and close this issue, feel free to reopen if you have any questions.
