### ISSUE TITLE
MiniKF start failing all the time

### ISSUE THREAD

**Issue by malocar7** [kubernetes/minikube#8690]
![image](https://user-images.githubusercontent.com/54955131/87130576-0f3b2b00-c28b-11ea-87aa-77483b48b7e8.png)
An unexpected exception has occurred
Line: build/bdist.linux-x86_64/egg/rok_common/cmdutils.py:942
Type: CommandExecutionError
Reason: Command '<ExtCommand [lb8l_MO_MZ4] 'kubectl gets pods -o json -n rok', status=FINISHED (ret:1), PID=12473, shell =False>' failed. Error log: Unable to connect to the server: http2: server sent GOAWAY and closed the connection; LastStreamID=1, ErrCode=NO_ERROR, debug""\n
The logfile '/home/vagrant/provision.log' may contain more information on this error including a backtrace.
*** MiniKF provisioning tool terminated. Press Enter to restart, Ctrl-C to exit... ***

**Comment by malocar7** [comment]
![image](https://user-images.githubusercontent.com/54955131/87131159-e9625600-c28b-11ea-9830-4df7d3c6a10d.png)

**Comment by medyagh** [comment]
@malocar7  we don't maintain MiniKF, however I believe MiniKF uses an old version of minikube, I suggest to ask your support question in MiniKF repo,

I would love to see coperation with miniKF and minikube project to ensure they are using latest supported minikube version

**Comment by medyagh** [comment]
@priyawadhwa

**Comment by priyawadhwa** [comment]
Hey @malocar7 unfortunately we don't know much about MiniKF and can't help debug this issue. I'd suggest reopening this issue in their repo: https://github.com/kubeflow/

I'm going to go ahead and close this issue since it isn't actionable.

**Comment by priyawadhwa** [comment]
I kept https://github.com/kubernetes/minikube/issues/8706 open as a dupe
