### ISSUE TITLE
--extra-config with double quotes breaks kubeadm init

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8694]
we should validate options like this
```
./out/minikube start --driver=docker --extra-config=etcd.client-cert-auth=false”
```

currently running that will make minikube kubeadm hang.

**Comment by vinu2003** [comment]
Hey @medyagh I can help with this.
/assign @vinu2003

**Comment by medyagh** [comment]
@vinu2003 it's yours !

**Comment by vinu2003** [comment]
Reproduced this issue. started working on PR.

**Comment by RA489** [comment]
@vinu2003 Are you still working on this issue?

**Comment by medyagh** [comment]
@vinu2003 I haven't heard any updates, this issue is available for anyone who likes to pick it up
