### ISSUE TITLE
none driver doesn't work on  Amazon Linux

### ISSUE THREAD

**Issue by FaristaS** [kubernetes/minikube#8696]
**Steps to reproduce the issue:** 

1.#minikube start --vm-driver=none
😄  minikube v1.12.0 on Amazon 2
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
🤦  StartHost failed, but will try again: post-start: sudo mkdir (none): sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs: exit status 1
stdout:

stderr:
sudo: PAM account management error: Permission denied

🔄  Restarting existing none bare metal machine for "minikube" ...
😿  Failed to start none bare metal machine. "minikube start" may fix it: post-start: sudo mkdir (none): sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs: exit status 1
stdout:

stderr:
sudo: PAM account management error: Permission denied

💣  error provisioning host: Failed to start host: post-start: sudo mkdir (none): sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs: exit status 1
stdout:

stderr:
sudo: PAM account management error: Permission denied

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

Still unsure about how to run with driver=none

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @FaristaS based on this log:
```
sudo: PAM account management error: Permission denied
```

it seems like you don't have permissions to run the none driver, which requires root permissions. If you have root permissions, then

```
sudo minikube start --vm-driver=none
```

should work. If you're unable to run as root, consider running minikube in docker instead, with `minikube start --driver docker`

**Comment by FaristaS** [comment]
Hi @priyawadhwa,
The above cmd is run thru root user only with driver none, 
I am able to start with non root user with Docker driver, but i want to start with nine driver which require root privilege.
On running with root user i get the above error.

**Comment by afbjorklund** [comment]
Do you get the same errors when you run "sudo minikube" from your regular (non root) user ?

**Comment by FaristaS** [comment]
@afbjorklund, yes 
It gives the same error with $sudo

**Comment by afbjorklund** [comment]
I was just wondering, because there was some bug reports from the old RHEL 7 on which it is based.

The best solution at this point is choosing one of the supported platforms, or maybe another AWS tool

**Comment by FaristaS** [comment]
@afbjorklund  ok
The VM is Amazon AMI based, so i am not sure if the above link is related to the issue.
I would appreciate if you come across any solution or workaround or something...

**Comment by medyagh** [comment]
@FaristaS do you mind sharing the exact linux distro name and verison ? I suspect you should a different AMI and Linux OS, have you tried debian or ubuntu ?

btw have you tried docker driver we recommend docker driver on linux

**Comment by FaristaS** [comment]
Hi @medyagh 
That was on Amazon workspace based on Amazon AMI 2

**Comment by medyagh** [comment]
@FaristaS it seems like you that AMI doesn't suppor kubernetnes requirements, I reocmmend using an image like Debian or any other image that passes the requirements.

I am not fimmiliar with Amazon Linux
