### ISSUE TITLE
Generate basic auth credentials

### ISSUE THREAD

**Issue by yissachar** [kubernetes/minikube#87]
This would make it easier to authenticate when accessing through a browser, e.g. accessing Dashboard.

**Comment by dlorenc** [comment]
Good idea. I wonder if we should dynamically generate the password, or if it's fine to just use a static documented one for all users.

**Comment by dlorenc** [comment]
Could you explain a little more what you need these creds for? I'm able to access the dashboard without authenticating (using kubectl proxy or the HostPort)

**Comment by yissachar** [comment]
I don't have access to my Minikube at the moment, but if I recall these were the steps that prompted me to recreate this issue:

1.  Setup Minikube
2. Deploy Dashboard
3. Try to access Dashboard at `master-ip/ui`
4. Browser returns `Unauthorized`

Looking at the config for my Minikube cluster and other clusters I had, it seemed the only difference was the lack of Basic Auth credentials being created and the browser asking for them.

**Comment by dlorenc** [comment]
I think we need to generate the password dynamically, otherwise we'd still be vulnerable to a CSRF.

**Comment by yissachar** [comment]
FWIW, I've upgraded to Minikube 0.4 and this is no longer an issue for me.

**Comment by dlorenc** [comment]
Nice! I can confirm this works for me too. I'm not sure what changed, maybe the dashboard upgrade we did?

I think I'll close this for now.

**Comment by pswenson** [comment]
so what is the solution?  I just installed minikube today( minikube version: v0.5.0 on OS X ) and get the unauthorized message in the browser

**Comment by dlorenc** [comment]
What exactly are you trying to view? If you go to master-ip/ui it should
work.

**Comment by shanesveller** [comment]
FWIW, I still saw this `unauthorized` response under minikube 0.6.0 when visiting either of the following:
```
https://$vm_ip:8443/ui
https://$vm_ip:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard
```
The latter was retrieved from `kubectl cluster-info`.

**Comment by cotigao** [comment]
I am using v1.3.5.  kubectl cluster-info gives me:

Kubernetes master is running at https://192.168.99.100:8443
kubernetes-dashboard is running at https://192.168.99.100:8443/api/v1/proxy/namespaces/kube-system/services/kubernetes-dashboard

None of the above URLs work for me when I enter them in chrome browser. The browser complains about  insecure connection. However, if I do "minikube dashboard",  it opens up the dashboard page successfully at  192.168.99.100:30000.  What are the above URLs  supposed to show? Same as 192.168.99.100:30000?

**Comment by MrTortoise** [comment]
in my dump i am seeing the following. That info section is like that for my entire buffer repeating every minute.
```
INFO: == Reconciling with addon-manager label ==
INFO: == Kubernetes addon reconcile completed at 2017-06-15T07:07:01+0000 ==
INFO: == Kubernetes addon ensure completed at 2017-06-15T07:08:00+0000 ==
INFO: == Reconciling with deprecated label ==
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==
INFO: == Kubernetes addon reconcile completed at 2017-06-15T07:08:01+0000 ==
INFO: == Kubernetes addon ensure completed at 2017-06-15T07:09:00+0000 ==
INFO: == Reconciling with deprecated label ==
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==
INFO: == Kubernetes addon reconcile completed at 2017-06-15T07:09:00+0000 ==
==== END logs for kube-system/kube-addon-manager-minikube ====
==== START logs for kube-system/kube-dns-196007617-4pxg0 ====
Error from server (BadRequest): the server rejected our request for an unknown reason (get pods kube-dns-196007617-4pxg0)
```
