### ISSUE TITLE
Error initiating MiniKF

### ISSUE THREAD

**Issue by malocar7** [kubernetes/minikube#8706]
**Los comandos necesarios para reproducir la incidencia**:
vagrant init arrikto/minikf
vagrant up

Start MiniKF click ok and Accept and after a while the error appears.
![image](https://user-images.githubusercontent.com/54955131/87283992-cafb9500-c4ed-11ea-9dca-86076d7461f6.png)

**El resultado completo del comando que ha fallado**: <details>

See attached image

</details>

**El resultado del comando `minikube logs`**: <details>

in attached image

</details>

**La versión del sistema operativo que utilizaste**:
Windows 10

**Comment by priyawadhwa** [comment]
Hey @malocar7 unfortunately we don't maintain miniKF and don't know much about it. While this does look like a minikube issue, I'd suggest first opening this issue in their repo for help: github.com/kubeflow

**Comment by priyawadhwa** [comment]
Hey @malocar7 I'm going to go ahead and close this issue as it isn't related to minikube.
