### ISSUE TITLE
Unable to create local Kubernetes cluster

### ISSUE THREAD

**Issue by skmaingi** [kubernetes/minikube#8707]
**Steps to reproduce the issue:** 

1. `minikube start --driver=docker`
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

😄  minikube v1.12.0 on Ubuntu 16.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
✋  Stopping "minikube" in docker ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: provisioning: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
😿  Failed to start docker container. "minikube start" may fix it: creating host: create: provisioning: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

💣  error provisioning host: Failed to start host: creating host: create: provisioning: ssh command error:
command : sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
err     : Process exited with status 1
output  : sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set

**Optional: Full output of `minikube logs` command:**
<details>
`minikube start --driver=docker` fails

Docker Engine version: 19.03.12

</details>

**Comment by priyawadhwa** [comment]
Hey @skmaingi I haven't seen this error before but it looks like the UID of `sudo` _within_ minikube is not 1 or somehow corrupted.

My best suggestion right now is to delete and try again, could you let us know if this works:

```
minikube delete
minikube start --driver docker
```

**Comment by skmaingi** [comment]
@priyawadhwa Thank you for assistance. 
I tried deleting the cluster and using another driver but got "The connection to the server localhost:8080 was refused - did you specify the right host or port?"
I had to uninstall docker and minikube and remove all images. A new installation worked for me.

**Comment by nirandaperera** [comment]
Hi all, any update on this? I am having a similar error. But none of the suggestions seems to be working for me :-( I opened a new issue with the details. #12953
