### ISSUE TITLE
Test against ISO change on PR in GH Action

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8712]

**Comment by medyagh** [comment]
update, I tried and it took 1.5 hours to upload the ISO file in github actions

**Comment by medyagh** [comment]
done

**Comment by afbjorklund** [comment]
There seems to be rather long queue times in the actions, before the build even starts ? 

https://github.com/kubernetes/minikube/actions/runs/222208951 "Queued 4 hours ago"
