### ISSUE TITLE
rootless podman driver

### ISSUE THREAD

**Issue by ejiek** [kubernetes/minikube#8719]
**Steps to reproduce the issue:** 

1. `minikube start --driver=podman`

**Full output of failed command:** 
```
😄  minikube v1.11.0 on Arch rolling
    ▪ KUBECONFIG=/path-to-my-config
✨  Using the podman (experimental) driver based on user configuration

❗  'podman' driver reported an issue: "sudo -k -n podman version --format {{.Version}}" exit status 1: sudo: a password is required
💡  Suggestion: Add your user to the 'sudoers' file: 'ejiek ALL=(ALL) NOPASSWD: /usr/bin/podman'
📘  Documentation: https://podman.io

💣  Failed to validate 'podman' driver
```

This means that with podman driver user is obligated to have root access without password wich is not minimal provilage.
[It's possible](https://www.redhat.com/sysadmin/behind-scenes-podman) to run podman rootless.

[Here](https://wiki.archlinux.org/index.php/Podman#Rootless_Podman) is a bit of Arch wiki on configuring podman not to require root permissions. 

I suggest having a flag for this driver to either use sudo or not.

There is a good chance that rootless podman is not suitable for minikube yet due to it's [shortcomings](https://github.com/containers/podman/blob/v2.0/rootless.md) _(this is a linkg to a particular version of podman)_

**Comment by ejiek** [comment]
might be duplicate of #7480

**Comment by afbjorklund** [comment]
> I suggest having a flag for this driver to either use sudo or not.

We require rootful podman (v1) at the moment. This is unlikely to change, same with dockerd --rootless.

If you are interested in trying to run kubernetes without root, you can look into the [usernetes](https://github.com/rootless-containers/usernetes) project ?

So this is more about #7963

You could also use a VM...

**Comment by afbjorklund** [comment]
> There is a good chance that rootless podman is not suitable for minikube yet due to it's [shortcomings](https://github.com/containers/podman/blob/v2.0/rootless.md) _(this is a linkg to a particular version of podman)_

A lot of these are **blockers**:

* No cgroup V1 Support
* No CNI Support

Others are just bad performance:

* fuse-overlayfs
* slirp4netns

There is no big use case for minikube supporting podman, and it becomes even smaller for rootless podman.

I think we need Cgroups v2 support to land in Kubernetes (and Docker), before we look at supporting it (v2)...

**Comment by ejiek** [comment]
Sounds reasonable, thanks!

Should we keep this issue open for the bright future or you preferto create a new one once the time comes (if at all)?

**Comment by afbjorklund** [comment]
I think spinning up an entire kubernetes "node" inside a rootless container will be hard to accomplish, if at all...

We already see a lot of issues, from the difference between a virtual machine and a (rootful) system container.

So it would definitely be at the bottom of the list.

Minikube runs in virtualbox ("classic")
Minikube runs in "native" hypervisor, linux libvirt
Minikube runs in "native" hypervisor, win hyper-v
Minikube runs in "native" hypervisor, mac hyperkit

Minikube runs on docker engine, linux
Minikube runs on docker desktop, win
Minikube runs on docker desktop, mac
Minikube runs on sudo podman, linux

Already a _lot_ of different platforms (8), to support.

And that's not even including the case when you run the installation right on the linux host with the none driver.

Which then runs into issues with different linux distributions, and with general lack of isolation (and multi-node!)

So I think it would be better off handled in usernetes.

There was some similar "root" discussions in #8257

**Comment by AkihiroSuda** [comment]
Work in progress for kind: https://github.com/kubernetes-sigs/kind/pull/1727

Probably it can be easily ported to minikube as well

**Comment by AkihiroSuda** [comment]
> think we need Cgroups v2 support to land in Kubernetes (and Docker)

Already landed on their master branches (Kubernetes 1.19, Docker 20.0X)

**Comment by afbjorklund** [comment]
> > think we need Cgroups v2 support to land in Kubernetes (and Docker)
> 
> Already landed on their master branches (Kubernetes 1.19, Docker 20.0X)

Good to hear! Then we just need those to be released. I guess Podman 2.0.x is already out

**Comment by medyagh** [comment]
I look forward to see a prototype of rootless docker/podman in minikube

**Comment by AkihiroSuda** [comment]
kind works with Rootless Podman as well as Rootless Docker now: https://github.com/kubernetes-sigs/kind/pull/1935

Should be easily portable to minikube.

**Comment by afbjorklund** [comment]
Guess we just have to add some checks, for latest Podman/Docker (with cgroups v2) and latest Kubernetes

**Comment by AkihiroSuda** [comment]
The first step toward this is to bring proper support for cgroup2: https://github.com/kubernetes/minikube/issues/11310

**Comment by AkihiroSuda** [comment]
PR: https://github.com/kubernetes/minikube/pull/12901

**Comment by AkihiroSuda** [comment]
/remove-lifecycle stale

PR https://github.com/kubernetes/minikube/pull/12901 has received two LGTMs, but not merged yet
