### ISSUE TITLE
hyperv: Failed to start host: provision: IP not found

### ISSUE THREAD

**Issue by Pavs1605** [kubernetes/minikube#8724]
**Steps to reproduce the issue:** 

C:\WINDOWS\system32> minikube start --vm-driver="hyperv" --hyperv-virtual-switch="minikube"
* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of failed command:** 
 minikube start --vm-driver="hyperv" --alsologtostderr

W0715 12:48:05.301708   20580 root.go:252] Error reading config file at C:\Users\pavi\.minikube\config\config.json: open C:\Users\pavi\.minikube\config\config.json: The system cannot find the file specified.
I0715 12:48:05.316711   20580 start.go:98] hostinfo: {"hostname":"pavi","uptime":1953,"bootTime":1594795532,"procs":265,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.18362 Build 18362","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"5dff9e3b-54e6-4c1f-811f-99278854b47b"}
W0715 12:48:05.317711   20580 start.go:106] gopshost.Virtualization returned error: not implemented yet
* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
I0715 12:48:05.323712   20580 driver.go:253] Setting default libvirt URI to qemu:///system
* Using the hyperv driver based on existing profile
I0715 12:48:06.340826   20580 start.go:214] selected driver: hyperv
I0715 12:48:06.341828   20580 start.go:611] validating driver "hyperv" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:4000 CPUs:2 DiskSize:20000 Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch:minikube HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:192.168.137.232 Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[default-storageclass:true storage-provisioner:true] VerifyComponents:map[apiserver:true system_pods:true]}
I0715 12:48:06.342831   20580 start.go:617] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0715 12:48:06.343832   20580 iso.go:118] acquiring lock: {Name:mkd84bdf082506b73b797daa8fe7e83a3eb1d98c Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Starting control plane node minikube in cluster minikube
I0715 12:48:06.350840   20580 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0715 12:48:06.355829   20580 preload.go:103] Found local preload: C:\Users\pavi\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0715 12:48:06.355829   20580 cache.go:49] Caching tarball of preloaded images
I0715 12:48:06.357827   20580 preload.go:129] Found C:\Users\pavi\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0715 12:48:06.357827   20580 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0715 12:48:06.359832   20580 profile.go:156] Saving config to C:\Users\pavi\.minikube\profiles\minikube\config.json ...
I0715 12:48:06.364833   20580 cache.go:152] Successfully downloaded all kic artifacts
I0715 12:48:06.366834   20580 start.go:240] acquiring machines lock for minikube: {Name:mkb4823b8c79d1fa2a889212a4ceec8cd40a75e1 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0715 12:48:06.367838   20580 start.go:244] acquired machines lock for "minikube" in 0s
I0715 12:48:06.370829   20580 start.go:88] Skipping create...Using existing machine configuration
I0715 12:48:06.370829   20580 fix.go:53] fixHost starting:
I0715 12:48:06.381832   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0715 12:48:07.741121   20580 main.go:110] libmachine: [stdout =====>] : Running

I0715 12:48:07.741121   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:07.742123   20580 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0715 12:48:07.745122   20580 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running hyperv "minikube" VM ...
I0715 12:48:07.748122   20580 machine.go:88] provisioning docker machine ...
I0715 12:48:07.749120   20580 buildroot.go:163] provisioning hostname "minikube"
I0715 12:48:07.749120   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0715 12:48:08.905648   20580 main.go:110] libmachine: [stdout =====>] : Running

I0715 12:48:08.905648   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:08.905648   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0715 12:48:10.362238   20580 main.go:110] libmachine: [stdout =====>] :
I0715 12:48:10.362238   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:10.363241   20580 machine.go:91] provisioned docker machine in 2.6141209s
I0715 12:48:10.365244   20580 fix.go:55] fixHost completed within 3.9944147s
I0715 12:48:10.366242   20580 start.go:75] releasing machines lock for "minikube", held for 3.996412s
! StartHost failed, but will try again: provision: IP not found
I0715 12:48:15.368227   20580 start.go:240] acquiring machines lock for minikube: {Name:mkb4823b8c79d1fa2a889212a4ceec8cd40a75e1 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0715 12:48:15.368227   20580 start.go:244] acquired machines lock for "minikube" in 0s
I0715 12:48:15.369234   20580 start.go:88] Skipping create...Using existing machine configuration
I0715 12:48:15.369234   20580 fix.go:53] fixHost starting:
I0715 12:48:15.370228   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0715 12:48:16.537231   20580 main.go:110] libmachine: [stdout =====>] : Running

I0715 12:48:16.537231   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:16.538242   20580 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0715 12:48:16.538242   20580 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running hyperv "minikube" VM ...
I0715 12:48:16.549264   20580 machine.go:88] provisioning docker machine ...
I0715 12:48:16.550269   20580 buildroot.go:163] provisioning hostname "minikube"
I0715 12:48:16.550269   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0715 12:48:17.708262   20580 main.go:110] libmachine: [stdout =====>] : Running

I0715 12:48:17.708262   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:17.708262   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0715 12:48:19.278868   20580 main.go:110] libmachine: [stdout =====>] :
I0715 12:48:19.278868   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:19.278868   20580 machine.go:91] provisioned docker machine in 2.7285993s
I0715 12:48:19.278868   20580 fix.go:55] fixHost completed within 3.9096337s
I0715 12:48:19.278868   20580 start.go:75] releasing machines lock for "minikube", held for 3.9096337s
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
I0715 12:48:19.278868   20580 exit.go:58] WithError(error provisioning host)=Failed to start host: provision: IP not found called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x18bd240)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc00083e740)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc000120d00, 0x0, 0x2)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc000120ce0, 0x2, 0x2, 0x2b6c200, 0xc000120ce0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x0, 0xc000117a01)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
W0715 12:48:19.279870   20580 out.go:201] error provisioning host: Failed to start host: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**
Already included

**Optional: Full output of `minikube logs` command:**
<details>
W0715 12:48:05.301708   20580 root.go:252] Error reading config file at C:\Users\pavi\.minikube\config\config.json: open C:\Users\pavi\.minikube\config\config.json: The system cannot find the file specified.
I0715 12:48:05.316711   20580 start.go:98] hostinfo: {"hostname":"pavi","uptime":1953,"bootTime":1594795532,"procs":265,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.18362 Build 18362","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"5dff9e3b-54e6-4c1f-811f-99278854b47b"}
W0715 12:48:05.317711   20580 start.go:106] gopshost.Virtualization returned error: not implemented yet
* minikube v1.11.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
I0715 12:48:05.323712   20580 driver.go:253] Setting default libvirt URI to qemu:///system
* Using the hyperv driver based on existing profile
I0715 12:48:06.340826   20580 start.go:214] selected driver: hyperv
I0715 12:48:06.341828   20580 start.go:611] validating driver "hyperv" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.11.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:4000 CPUs:2 DiskSize:20000 Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch:minikube HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP:192.168.137.232 Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[default-storageclass:true storage-provisioner:true] VerifyComponents:map[apiserver:true system_pods:true]}
I0715 12:48:06.342831   20580 start.go:617] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0715 12:48:06.343832   20580 iso.go:118] acquiring lock: {Name:mkd84bdf082506b73b797daa8fe7e83a3eb1d98c Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Starting control plane node minikube in cluster minikube
I0715 12:48:06.350840   20580 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0715 12:48:06.355829   20580 preload.go:103] Found local preload: C:\Users\pavi\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4
I0715 12:48:06.355829   20580 cache.go:49] Caching tarball of preloaded images
I0715 12:48:06.357827   20580 preload.go:129] Found C:\Users\pavi\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0715 12:48:06.357827   20580 cache.go:52] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0715 12:48:06.359832   20580 profile.go:156] Saving config to C:\Users\pavi\.minikube\profiles\minikube\config.json ...
I0715 12:48:06.364833   20580 cache.go:152] Successfully downloaded all kic artifacts
I0715 12:48:06.366834   20580 start.go:240] acquiring machines lock for minikube: {Name:mkb4823b8c79d1fa2a889212a4ceec8cd40a75e1 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0715 12:48:06.367838   20580 start.go:244] acquired machines lock for "minikube" in 0s
I0715 12:48:06.370829   20580 start.go:88] Skipping create...Using existing machine configuration
I0715 12:48:06.370829   20580 fix.go:53] fixHost starting:
I0715 12:48:06.381832   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0715 12:48:07.741121   20580 main.go:110] libmachine: [stdout =====>] : Running

I0715 12:48:07.741121   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:07.742123   20580 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0715 12:48:07.745122   20580 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running hyperv "minikube" VM ...
I0715 12:48:07.748122   20580 machine.go:88] provisioning docker machine ...
I0715 12:48:07.749120   20580 buildroot.go:163] provisioning hostname "minikube"
I0715 12:48:07.749120   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0715 12:48:08.905648   20580 main.go:110] libmachine: [stdout =====>] : Running

I0715 12:48:08.905648   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:08.905648   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0715 12:48:10.362238   20580 main.go:110] libmachine: [stdout =====>] :
I0715 12:48:10.362238   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:10.363241   20580 machine.go:91] provisioned docker machine in 2.6141209s
I0715 12:48:10.365244   20580 fix.go:55] fixHost completed within 3.9944147s
I0715 12:48:10.366242   20580 start.go:75] releasing machines lock for "minikube", held for 3.996412s
! StartHost failed, but will try again: provision: IP not found
I0715 12:48:15.368227   20580 start.go:240] acquiring machines lock for minikube: {Name:mkb4823b8c79d1fa2a889212a4ceec8cd40a75e1 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0715 12:48:15.368227   20580 start.go:244] acquired machines lock for "minikube" in 0s
I0715 12:48:15.369234   20580 start.go:88] Skipping create...Using existing machine configuration
I0715 12:48:15.369234   20580 fix.go:53] fixHost starting:
I0715 12:48:15.370228   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0715 12:48:16.537231   20580 main.go:110] libmachine: [stdout =====>] : Running

I0715 12:48:16.537231   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:16.538242   20580 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0715 12:48:16.538242   20580 fix.go:131] unexpected machine state, will restart: <nil>
* Updating the running hyperv "minikube" VM ...
I0715 12:48:16.549264   20580 machine.go:88] provisioning docker machine ...
I0715 12:48:16.550269   20580 buildroot.go:163] provisioning hostname "minikube"
I0715 12:48:16.550269   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0715 12:48:17.708262   20580 main.go:110] libmachine: [stdout =====>] : Running

I0715 12:48:17.708262   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:17.708262   20580 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0715 12:48:19.278868   20580 main.go:110] libmachine: [stdout =====>] :
I0715 12:48:19.278868   20580 main.go:110] libmachine: [stderr =====>] :
I0715 12:48:19.278868   20580 machine.go:91] provisioned docker machine in 2.7285993s
I0715 12:48:19.278868   20580 fix.go:55] fixHost completed within 3.9096337s
I0715 12:48:19.278868   20580 start.go:75] releasing machines lock for "minikube", held for 3.9096337s
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
I0715 12:48:19.278868   20580 exit.go:58] WithError(error provisioning host)=Failed to start host: provision: IP not found called from:
goroutine 1 [running]:
runtime/debug.Stack(0x40acf1, 0x18d85a0, 0x18bd240)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b44a0c, 0x17, 0x1e16f20, 0xc00083e740)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b6c200, 0xc000120d00, 0x0, 0x2)
        /app/cmd/minikube/cmd/start.go:169 +0xac9
github.com/spf13/cobra.(*Command).execute(0x2b6c200, 0xc000120ce0, 0x2, 0x2, 0x2b6c200, 0xc000120ce0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x0, 0xc000117a01)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
W0715 12:48:19.279870   20580 out.go:201] error provisioning host: Failed to start host: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**Comment by priyawadhwa** [comment]
Hey @Pavs1605 thanks for opening this issue. I'm not super familiar with the hyperv driver, but this issue seems to be related to #3648

Could you give the suggestion in this comment a try, and let me know whether or not it solves your issue?

https://github.com/kubernetes/minikube/issues/3648#issuecomment-488218782

**Comment by medyagh** [comment]
@Pavs1605 do you still have this issue, have you tried the docker driver?

**Comment by tstromberg** [comment]
This is related to misconfigured switches. Try:

**Comment by tstromberg** [comment]
min
