### ISSUE TITLE
Not able to spin the VM box. Can someone help?

### ISSUE THREAD

**Issue by vssirigiri** [kubernetes/minikube#8725]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "55a189ef-97e0-403c-a40c-68c02a3bd7bd", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'Windows-LL_default_1594794647859_99969' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\admin\VirtualBox VMs\Windows-LL_default_1594794647859_99969\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

![image](https://user-images.githubusercontent.com/67399495/87518115-da91ef80-c64d-11ea-91d5-dda4d72dc1a3.png)

I have mentioned log files link, currently i'm using 4GB RAM
Version of Vagrant is 2.2.9
Virtual Box - 6.1v

file:///C:/Users/admin/VirtualBox%20VMs/Windows-LL_default_1594794647859_99969/Logs/VBoxHardening.log

**Comment by priyawadhwa** [comment]
Hey @vssirigiri I'm not sure about this one, as it sort of looks like a VBoxManager error rather than a minikube error to me.

Could you see if running:

```
minikube delete
minikube start
```
fixes the issue?

**Comment by vssirigiri** [comment]
Hi Priya, Sorry I posted under wrong heading. Yes Its VBox manager error

**Comment by tstromberg** [comment]
Please use the following forum for your issue: https://forums.virtualbox.org/viewforum.php?f=6
