### ISSUE TITLE
Can't build minikube: https://github.com/sayboras/dockerclient is now 404

### ISSUE THREAD

**Issue by marga-kinvolk** [kubernetes/minikube#8726]
I was trying to build minikube from source and my build failed because https://github.com/sayboras/dockerclient is no longer there:

```
go: github.com/sayboras/dockerclient@v0.0.0-20191231050035-015626177a97: git fetch -f https://github.com/sayboras/dockerclient refs/heads/*:refs/heads/* refs/tags/*:refs/tags/* in /home/marga/go/pkg/mod/cache/vcs/b7e2c898b2aacd5c24d18e8c87d00a4199270783359417b3e6299205d4567dd3: exit status 128:
	fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

The original repo still exists (https://github.com/samalba/dockerclient) but it's very old. I don't know what changes the one by @sayboras had.

**Comment by sayboras** [comment]
@sayboras opps, sorry about this. Let me recover it.

**Comment by marga-kinvolk** [comment]
Thanks for restoring the repo! :)

Unfortunately, it still fails with:
```
go: github.com/sayboras/dockerclient@v0.0.0-20191231050035-015626177a97: unknown revision 015626177a97
```

I guess the rev needs to be updated to the current one?

**Comment by sayboras** [comment]
yup, I just realized that I removed the branch, let me update with tag version, so that I will not clean up the branch by mistake.

**Comment by sayboras** [comment]
Sorry for any inconvenience caused. 

You can checkout the changes in mentioned PR #8727, and proceed with your work.

**Comment by marga-kinvolk** [comment]
Thanks! :+1:

**Comment by priyawadhwa** [comment]
Thanks for opening a PR for this @sayboras , I'll take a look at it today
