### ISSUE TITLE
Add transient states ("stopping", "starting")

### ISSUE THREAD

**Issue by kschaab** [kubernetes/minikube#8730]
Minikube status lists Running, Paused or Stopped for each profile.  It does not account for the state between minikube start and Running.  It would be helpful to indicate when minikube is starting, pausing (maybe, this state seems like it might be super short), stopping and possibly deleting as well as valid states.

**Comment by medyagh** [comment]
seems like a good feature for minikube !

**Comment by tstromberg** [comment]
"downloading" could also be a good state

**Comment by tharun208** [comment]
I like to work on this @tstromberg

**Comment by medyagh** [comment]
@tharun208 I would be happy to review a PR that doe sthis.

**Comment by tstromberg** [comment]
@tharun208 - please confirm if you would still like to take this on. Here is my initial naive implementation idea:

- Create a new file (for example, `~/.minikube/profiles/<name>/state.json`) containing a simple JSON file with a field like:

`{ status = "starting" }`

- Add a `Status` function here that returns the path. You can use `ConfigFile()` as a reference to copy:

https://github.com/kubernetes/minikube/blob/c6000e6c3029f9a37833e20379d789e490379815/pkg/minikube/localpath/localpath.go#L39

- Add code to https://github.com/kubernetes/minikube/blob/c6000e6c3029f9a37833e20379d789e490379815/pkg/minikube/machine/host.go#L28 that references the state output by this file. I'd probably start by ignoring this file if it's modification time is older than 1 minute. 

- Add a method in the same package that allows you to update the state file

- Add code to https://github.com/kubernetes/minikube/blob/c6000e6c3029f9a37833e20379d789e490379815/pkg/minikube/machine/start.go#L66 to set the state to `Starting`

- Add code to https://github.com/kubernetes/minikube/blob/c6000e6c3029f9a37833e20379d789e490379815/pkg/minikube/machine/stop.go#L35 to set the state to `Stopping`.

Other ideas, though I wouldn't necessarily worry about them for the initial implementation, are `Downloading` and `Deleting`.

**Comment by tstromberg** [comment]
If I haven't heard anything back later today, I'll plan to work on this.

One new idea I had is that @priyawadhwa built the concept of "steps" into minikube, for emitting CloudEvent JSON output: https://github.com/kubernetes/minikube/blob/52239798934b24d7da8ba2d9b82997764ff8dccd/pkg/minikube/machine/start.go#L261

I think we should build on this by introducing a concept of state transitions, and storing the combined state transition & step into the status file. For instance:

`state.Transition(state.Starting, register.CreatingContainer, message)`

Could emit the appropriate output.

**Comment by priyawadhwa** [comment]
@tstromberg instead of passing in the specific step `register.CreatingContainer`, you could access the current step via:

```go
register.Reg.CurrentStep()
```

that way you could rely on the steps that have already been set in the register instead of having to uniquely pass them in again

**Comment by tharun208** [comment]
@medyagh, I think I can't make it for the next release. @tstromberg, you can pick this

**Comment by tstromberg** [comment]
Thanks for the heads up @tharun208. I'm sure this feature will require future refinement where we could use your hepl.

**Comment by tstromberg** [comment]
I have some ideas on this, and intend to have an initial PR for review tomorrow, with a target to merge this by EOW.
