### ISSUE TITLE
Should they use RWMutex?

### ISSUE THREAD

**Issue by dddddai** [kubernetes/minikube#8731]
Should they use RWMutex instead of Mutex to avoid the contention between readings?

https://github.com/kubernetes/minikube/blob/6a21774a1e2687a669310b78759b244273f83a43/pkg/minikube/registry/registry.go#L135-L153

https://github.com/kubernetes/minikube/blob/edd095bf1f8e1a88e58bc5b383c9f6d049eac3a4/third_party/go9p/srv_file.go#L239-L250

If it's necessary,I am willing to contribute.

**Comment by priyawadhwa** [comment]
Hey @dddddai that seems reasonable to me. Would you be interested in contributing this fix?

**Comment by dddddai** [comment]
@priyawadhwa Thank you,I have created a PR.
