### ISSUE TITLE
canot ready directory 'xyz/': Unknown error 526  

### ISSUE THREAD

**Issue by artemkoslenkov** [kubernetes/minikube#8732]
Hello everybody, I'm running into this on `ls -la /node_modules`</br> for the mounted folder inside the minikube cluster, </br>
[issue1562](https://github.com/kubernetes/minikube/issues/1562)</br>
[PR1705](https://github.com/kubernetes/minikube/pull/1705)</br>

but still no luck.</br>
the folder size is 187 mb only, how big should `--msize` be? 
Any help would be much appreciated.

**Comment by priyawadhwa** [comment]
Hey @artemkoslenkov thanks for opening this issue. What version of minikube are you running?

**Comment by artemkoslenkov** [comment]
> Hey @artemkoslenkov thanks for opening this issue. What version of minikube are you running?

Hi there, 

minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd

**Comment by artemkoslenkov** [comment]
> > Hey @artemkoslenkov thanks for opening this issue. What version of minikube are you running?
> 
> Hi there,
> 
> minikube version: v1.11.0
> commit: [57e2f55](https://github.com/kubernetes/minikube/commit/57e2f55f47effe9ce396cea42a1e0eb4f611ebbd)

just upgraded to v1.12.0

`docker mount $HOME/path/to/node/project:/var/www/front` 

`docker ssh` -> `cd ../../var/www/front` --> 'ls -la` = ls: reading directory '.': Unknown error 526

basicaly any folder related operations (r+w+x) will throw error 526

**Comment by medyagh** [comment]
@artemkoslenkov what driver are you using ? do you have same issue with any other driver that minikube supports ?
docker or kvm2 or hyperkit ...

**Comment by artemkoslenkov** [comment]
> /triage needs-information
> /triage support

Hi, I'm using kvm2 driver on ubuntu, haven't checked with other drivers.

May it be related to what's mentioned here https://minikube.sigs.k8s.io/docs/handbook/mount/ regarding folders > 600 files issue? In node_modules this may definitely be the case.

How to work around this case? 

Many thanks,
Artem.

**Comment by sharifelgamal** [comment]
You can use driver mounts as an alternative to 9p mounting, although that isn't supported in kvm2. It would require use of another driver (virtualbox perhaps?).

**Comment by CharlieBrownMx** [comment]
I faced this same issue a few days ago, I could solve it tho by booting my cluster up and mounting the directory running this:

`minikube start --driver=docker --mount-string="local_path:target_path" --mount`

For this you would have to have docker daemon up and running.
