### ISSUE TITLE
Minikube is not starting 

### ISSUE THREAD

**Issue by AnandhkumarTV** [kubernetes/minikube#8743]
**Steps to reproduce the issue:** 

when i running the command ` minikube start --driver=none`

The output was 

**Full output of failed command:** 
* minikube v1.12.0 on Centos 7.8.2003
* Using the none driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=2, Memory=1494MB, Disk=6334MB) ...
* OS release is CentOS Linux 7 (Core)
* Preparing Kubernetes v1.18.3 on Docker 18.03.1-ce ...
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubelet: 108.04 MiB / 108.04 MiB [----------] 100.00% 593.43 KiB p/s 3m6s
    > kubectl: 41.99 MiB / 41.99 MiB [-----------] 100.00% 207.85 KiB p/s 3m27s
    > kubeadm: 37.97 MiB / 37.97 MiB [-----------] 100.00% 183.22 KiB p/s 3m32s
*
X Failed to update cluster: updating node: downloading binaries: downloading kubelet: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubelet?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubelet.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubelet?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.3/bin/linux/amd64/kubelet.sha256 Dst:/root/.minikube/cache/linux/v1.18.3/kubelet.download Pwd: Mode:2 Detectors:[0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350] Decompressors:map[bz2:0x2cc1350 gz:0x2cc1350 tar.bz2:0x2cc1350 tar.gz:0x2cc1350 tar.xz:0x2cc1350 tbz2:0x2cc1350 tgz:0x2cc1350 txz:0x2cc1350 xz:0x2cc1350 zip:0x2cc1350] Getters:map[file:0xc0001bf2f0 http:0xc0008293a0 https:0xc0008293c0] Dir:false ProgressListener:0x2c99b20 Options:[0xc2aa30]}: Checksums did not match for /root/.minikube/cache/linux/v1.18.3/kubelet.download.
Expected: 6aac8853028a4f185de5ccb5b41b3fbd87726161445dee56f351e3e51442d669
Got: 4f18132f3340aa581e45e8ca07f81419c003fe930fbd6c6923c757c73f5bbda7
*sha256.digest
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by priyawadhwa** [comment]
Hey @AnandhkumarTV it looks like checksums on the kubelet binary don't match. Maybe they were corrupted somehow during download?

Could you try each of these and let us know if either works?

```
minikube delete --all --purge
minikube start --driver none
```

and

```
minikube delete --all --purge
minikube start --driver none --kubernetes-version v1.18.0
```

**Comment by AnandhkumarTV** [comment]
Hi priyawadha,

I've tried the above commands but sadly the issue still persist

here is the output:

`[root@worker-node1 bin]# minikube delete --all --purge
* Uninstalling Kubernetes v1.18.3 using kubeadm ...
* Deleting "minikube" in none ...
* Removed all traces of the "minikube" cluster.
* Successfully deleted all profiles
* Successfully purged minikube directory located at - [/root/.minikube]
[root@worker-node1 bin]# minikube start --driver none --kubernetes-version v1.18.0
* minikube v1.12.0 on Centos 7.8.2003
* Using the none driver based on user configuration
* Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=2, Memory=1494MB, Disk=6334MB) ...
* minikube 1.12.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.12.1
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

* OS release is CentOS Linux 7 (Core)
* Preparing Kubernetes v1.18.0 on Docker 19.03.9 ...
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm: 37.96 MiB / 37.96 MiB [-----------] 100.00% 471.23 KiB p/s 1m22s
    > kubectl: 41.98 MiB / 41.98 MiB [-----------] 100.00% 483.81 KiB p/s 1m29s
    > kubelet: 108.01 MiB / 108.01 MiB [---------] 100.00% 639.25 KiB p/s 2m53s
*
X Failed to update cluster: updating node: downloading binaries: downloading kubeadm: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.18.0/bin/linux/amd64/kubeadm.sha256 Dst:/root/.minikube/cache/linux/v1.18.0/kubeadm.download Pwd: Mode:2 Detectors:[0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350] Decompressors:map[bz2:0x2cc1350 gz:0x2cc1350 tar.bz2:0x2cc1350 tar.gz:0x2cc1350 tar.xz:0x2cc1350 tbz2:0x2cc1350 tgz:0x2cc1350 txz:0x2cc1350 xz:0x2cc1350 zip:0x2cc1350] Getters:map[file:0xc00035d520 http:0xc000157780 https:0xc0001577c0] Dir:false ProgressListener:0x2c99b20 Options:[0xc2aa30]}: Checksums did not match for /root/.minikube/cache/linux/v1.18.0/kubeadm.download.
Expected: 0261331c2ea718c0cd39114871aa098f1b4685f6101cb78cc880f645e72d0654
Got: c8c4d55d50bb0ab3f99dd06206fc8ffc6d52297a7fe5eedfa7c420cf5351ef50
*sha256.digest
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
`

**Comment by sharifelgamal** [comment]
That is very strange, I don't really see why a checksum would fail on something so simple.

Can you try running `minikube start --driver none --kubernetes-version v1.18.0 -v=8 --alsologtostderr`? That should give us more information to go on.

**Comment by sharifelgamal** [comment]
Any luck @AnandhkumarTV ?

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this for now, feel free to reopen this if it remains an issue.
