### ISSUE TITLE
Improve error message when docker is stopped and attempting to start minikube with docker driver

### ISSUE THREAD

**Issue by kschaab** [kubernetes/minikube#8748]
**Steps to reproduce the issue:** 

1. Stop docker
2. minikube start --driver=docker

**Full output of failed command:** 
![image](https://user-images.githubusercontent.com/7329029/87806763-3b672680-c80c-11ea-800c-4518e09123c2.png)

<details>
As you can see the resulting error from minikube does correctly state that docker might be stopped, but it has other text which might be confusing to the user.  You can query status of the docker service without admin, it would be good to have a message similar to that on Mac/Linux which is a bit more clear.
</details>

**Comment by etanshaul** [comment]
Some context:

IntelliJ Friction log: https://docs.google.com/document/d/1OscVyf02NmRZ6PnTn2mprIEG5IrhWgxIF1V5ha2gq_Q/edit#
VS Code Friction log: https://docs.google.com/document/d/1dj7dSgU5XeiRbJkQ8n3VU6OfyqW5D0xQeOYu_CGQOYs/edit?ts=5f11ce30#heading=h.n6ldogid6n95
