### ISSUE TITLE
Error restarting cluster: waiting for apiserver: apiserver process never appeared 

### ISSUE THREAD

**Issue by soodr** [kubernetes/minikube#8750]
**Steps to reproduce the issue:** 
 I am using the hyperkit driver on my Mac (Os: Mojave version 10.14.6)
1. minikube start --memory=8192 --cpus=3 --kubernetes-version=v1.17.4 -p istio-devnation --alsologtostderr -v=7
2. As a sidenote, I do not have dnsmasq installed, as mentioned here #6296 , though the see connection timeouts to k8s.gcr.io 
3. I do not have a firewall or VPN enabled.
4. docker pull k8s.gcr.io/kube-apiserver:v1.16.0 works fine from the command line.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
[minikube_startup.log](https://github.com/kubernetes/minikube/files/4938973/minikube_startup.log)

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
I noticed that this is minikube v1.5.2, which is quite old. We've definitely fixed this issue since. Do you mind trying again with minikube v1.12?

If that isn't possible, you should be able to workaround this with `minikube delete`. Please let me know how you get by.

**Comment by soodr** [comment]
I was able to fix this with `minikube delete`. Also updated version as suggested. 
thanks.
