### ISSUE TITLE
verifying ingress addon pods : timed out waiting for the condition: timed out waiting for the condition

### ISSUE THREAD

**Issue by staticdev** [kubernetes/minikube#8756]
**Steps to reproduce the issue:** 

1. minikube start --vm-driver=docker --memory 3072
2. minikube addons enable ingress

**Full output of failed command:** tried 3 times.
😄  minikube v1.12.1 on Ubuntu 20.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=3072MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
🔎  Verifying ingress addon...

💣  enable failed: run callbacks: running callbacks: [verifying ingress addon pods : timed out waiting for the condition: timed out waiting for the condition]

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**
-

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
Can you please share the output of:

* `kubectl descr po -A`

The only thing new in v.12.1 is an updated version of ingress: https://github.com/kubernetes/minikube/pull/8705

I was not able to replicate this issue on Docker/Linux or Hyperkit/macOS. My suspicion is that perhaps the download failed? Regardless, we can do a better job of showing an actionable error message.

**Comment by staticdev** [comment]
> `kubectl descr po -A`

```NAMESPACE     NAME                                        READY   STATUS      RESTARTS   AGE
kube-system   coredns-66bff467f8-pkgjv                    1/1     Running     0          4m34s
kube-system   etcd-minikube                               1/1     Running     0          4m31s
kube-system   ingress-nginx-admission-create-f4kgh        0/1     Completed   0          4m17s
kube-system   ingress-nginx-admission-patch-v7wth         0/1     Completed   0          4m17s
kube-system   ingress-nginx-controller-69ccf5d9d8-8pmdm   1/1     Running     0          4m17s
kube-system   kube-apiserver-minikube                     1/1     Running     0          4m31s
kube-system   kube-controller-manager-minikube            1/1     Running     0          4m31s
kube-system   kube-proxy-7m7tl                            1/1     Running     0          4m34s
kube-system   kube-scheduler-minikube                     1/1     Running     0          4m31s
kube-system   metrics-server-5f956b6d5f-9zfvx             1/1     Running     0          4m22s
kube-system   storage-provisioner                         1/1     Running     0          4m35s```

**Comment by shyamkhakhar9** [comment]
I also face the same issue while trying to addons and I have ingress nginx yaml where when I apply kubectl it gives me following error.. how to resolve that

```Error from server (InternalError): error when creating "ingress-service.yaml": Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": Post https://ingress-nginx-controller-admission.kube-system.svc:443/extensions/v1beta1/ingresses?timeout=30s: dial tcp 10.97.204.103:443: connect: connection refused```

**Comment by staticdev** [comment]
@tstromberg update: after some more tests, I see that most of the times it gives the error, but sometimes not. As you said, the max waiting time may be on the edge of the average time it takes. I would like to isolate which version update is causing this increased time so that we can upstream this issue to the component with degraded performance.

How can I do that? Do I need to recompile minikube from source or there is an easier way to do it?

**Comment by Jasstkn** [comment]
Same problem.

**Comment by chitranshi21** [comment]
Hi,
I am getting the same error. 
`enable failed: run callbacks: running callbacks: [verifying ingress addon pods : timed out waiting for the condition: timed out waiting for the condition]`
minikube version - V1.12.1

**Comment by anotherandi** [comment]
I tried down-dating to 1.12.0 but had the same issue on windows 10.

**Comment by chukmunnlee** [comment]
I manage to get enable the ingress add on by enabling cni and install Cilium. Have not tried with other providers

**Comment by vvlookman** [comment]
Because the image is not pulled, try workaround:

```
$ kubectl get pod -A
```
> List all the system pod names

```
$ kubectl describe pod/ingress-nginx-controller-xxxxxx --namespace=kube-system
```
> Find out the image name which has not been pulled successfully, in my case is quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.33.0

```
$ minikube ssh
$ docker pull quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.33.0
```
> Pull the image in minikube vm manully

**Comment by djvasquezvm** [comment]
Same problem. I followed your steps but my problem was:
Warning  FailedMount  12m (x7 over 12m)  kubelet, minikube  MountVolume.SetUp failed for volume "webhook-cert" : secret "ingress-nginx-admission" not found

So I realized it was SELinux. If you  have SELinux enforcing, try using permissive mode.

Worked for me!

> Because the image is not pulled, try workaround:
> 
> ```
> $ kubectl get pod -A
> ```
> 
> > List all the system pod names
> 
> ```
> $ kubectl describe pod/ingress-nginx-controller-xxxxxx --namespace=kube-system
> ```
> 
> > Find out the image name which has not been pulled successfully, in my case is quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.33.0
> 
> ```
> $ minikube ssh
> $ docker pull quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.33.0
> ```
> 
> > Pull the image in minikube vm manully

**Comment by ELTEGANI** [comment]
I faced the same I found the problem from my poor internet connection

**Comment by 839928622** [comment]
> I faced the same I found the problem from my poor internet connection
did u get it fix later on ?

**Comment by ELTEGANI** [comment]
> > I faced the same I found the problem from my poor internet connection
> did u get it fix later on ?

Yeb fixed it

**Comment by renich** [comment]
In my case, I live in México and I have a 100 Mbps connection. Everything installed correctly but not the nginx ingress:

```
0s          Normal    BackOff             pod/ingress-nginx-controller-789d9c4dc-7wpkv    Back-off pulling image "us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20"
0s          Warning   Failed              pod/ingress-nginx-controller-789d9c4dc-7wpkv    Error: ImagePullBackOff
0s          Normal    BackOff             pod/ingress-nginx-controller-789d9c4dc-7wpkv    Back-off pulling image "us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20"
0s          Warning   Failed              pod/ingress-nginx-controller-789d9c4dc-7wpkv    Error: ImagePullBackOff
0s          Normal    Pulling             pod/ingress-nginx-controller-789d9c4dc-7wpkv    Pulling image "us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20"
0s          Warning   Failed              pod/ingress-nginx-controller-789d9c4dc-7wpkv    Error: ErrImagePull
0s          Warning   Failed              pod/ingress-nginx-controller-789d9c4dc-7wpkv    Failed to pull image "us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20": rpc error: code = Unknown desc = Invalid image name "us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20", unknown transport "us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller"
0s          Normal    BackOff             pod/ingress-nginx-controller-789d9c4dc-7wpkv    Back-off pulling image "us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20"
0s          Warning   Failed              pod/ingress-nginx-controller-789d9c4dc-7wpkv    Error: ImagePullBackOff
0s          Warning   Failed              pod/ingress-nginx-controller-789d9c4dc-7wpkv    Error: ImagePullBackOff
```

**Comment by renich** [comment]
It seems that the URL being used isn't correct. If you go here: https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/US/ingress-nginx/controller@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20 it works, but the URL logged is: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20

If you put them side by side, ìt's easy to notice the difference:

```
us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
```

**Comment by renich** [comment]
So, for me, edititng the deployment with the correct image URL seems to have worked. 

![image](https://user-images.githubusercontent.com/225115/94640852-53940100-02a5-11eb-9e06-ea82be777a50.png)

To do this, just: `kubectl -n kube-system edit deployment ingress-nginx-controller` and look for "image:" and change it to:

```
image: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
```

![image](https://user-images.githubusercontent.com/225115/94640901-758d8380-02a5-11eb-8954-ef9ea9d8d052.png)

**Comment by pimenvibritania** [comment]
> So, for me, edititng the deployment with the correct image URL seems to have worked.
> 
> ![image](https://user-images.githubusercontent.com/225115/94640852-53940100-02a5-11eb-9e06-ea82be777a50.png)
> 
> To do this, just: `kubectl -n kube-system edit deployment ingress-nginx-controller` and look for "image:" and change it to:
> 
> ```
> image: us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
> ```
> 
> ![image](https://user-images.githubusercontent.com/225115/94640901-758d8380-02a5-11eb-8954-ef9ea9d8d052.png)

WOOWWW Thank You!! its work!

**Comment by WillNilges** [comment]
I'm still having trouble. I edited the image url, but I'm still not able to pull the image
```
[wnilges@thingsboard-minikube ~]$ kubectl get pods -A
NAMESPACE     NAME                                        READY   STATUS              RESTARTS   AGE
kube-system   coredns-f9fd979d6-lm5j8                     1/1     Running             0          26m
kube-system   etcd-minikube                               1/1     Running             0          26m
kube-system   ingress-nginx-admission-create-gxwkc        0/1     ImagePullBackOff    0          9m19s
kube-system   ingress-nginx-admission-patch-mz5bx         0/1     ImagePullBackOff    0          9m8s
kube-system   ingress-nginx-controller-7977f85d85-xbnwr   0/1     ContainerCreating   0          9m45s
kube-system   kube-apiserver-minikube                     1/1     Running             0          26m
kube-system   kube-controller-manager-minikube            1/1     Running             0          26m
kube-system   kube-proxy-2p9wr                            1/1     Running             0          26m
kube-system   kube-scheduler-minikube                     1/1     Running             0          26m
kube-system   storage-provisioner                         1/1     Running             1          26m
```

**Comment by WillNilges** [comment]
For reference, here's my full `minikube start` attempt:
```
[wnilges@thingsboard-minikube root]$  minikube start --addons=ingress --alsologtostderr -v=5
```
[(It's really big)](https://gist.github.com/WillNilges/3b5db728b2cfdf3116d7a2ff729fd276)

**Comment by WillNilges** [comment]
Weather update: Works on my local Ubuntu 20 machine, not so much on my Fedora Server 32 VM. _Highly_ wack.

**Comment by Hongbo-Miao** [comment]
Thanks @renich ! Met same issue. After `kubectl -n kube-system edit deployment ingress-nginx-controller`

```
us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
```

should be 

```
us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
```

(You can try to open first URL and will get 404 error, the second one which is also version 0.34.1 can be opened)

**Comment by danielbeeke** [comment]
In my case I had something running on port 80, that can also happen.

**Comment by sahilgrover306** [comment]
IT Works after changing the image URL. Thanks for the help

**Comment by EHJ-52n** [comment]
Removing the version tag `:v0.44.0` following @Hongbo-Miao [instructions above](#issuecomment-736699590) solved this issue for me.

Hence, the issues seems to be **not solved** in
```bash
$ minikube version
minikube version: v1.19.0
commit: 15cede53bdc5fe242228853e737333b09d4336b5
```

<details>
<summary>Pods before "fix" application</summary>

```
$ kubectl get pod -A
NAMESPACE              NAME                                        READY   STATUS      RESTARTS   AGE
demo-sensorweb         helgoland-cf7ccb684-2w8ds                   1/1     Running     19         32d
ingress-nginx          ingress-nginx-admission-create-n5wpw        0/1     Completed   0          119m
ingress-nginx          ingress-nginx-admission-patch-knxnr         0/1     Completed   1          119m
ingress-nginx          ingress-nginx-controller-5d88495688-xdtsd   0/1     Pending     0          119m
kube-system            coredns-74ff55c5b-j956h                     1/1     Running     67         104d
kube-system            etcd-minikube                               1/1     Running     88         104d
kube-system            ingress-nginx-admission-create-pkqsj        0/1     Completed   0          40d
kube-system            ingress-nginx-admission-patch-zzpjx         0/1     Completed   0          40d
kube-system            ingress-nginx-controller-65cf89dc4f-jhhqt   1/1     Running     34         40d
kube-system            kube-apiserver-minikube                     1/1     Running     73         40d
kube-system            kube-controller-manager-minikube            1/1     Running     73         40d
kube-system            kube-proxy-thhs2                            1/1     Running     48         52d
kube-system            kube-scheduler-minikube                     1/1     Running     73         40d
kube-system            registry-pj8fc                              1/1     Running     21         32d
kube-system            registry-proxy-72gcx                        1/1     Running     20         32d
kube-system            storage-provisioner                         1/1     Running     88         104d
kubernetes-dashboard   dashboard-metrics-scraper-f6647bd8c-wfx2l   1/1     Running     37         40d
kubernetes-dashboard   kubernetes-dashboard-968bcb79-mdc6n         1/1     Running     52         40d
```

</details>

<details>
<summary>Pods after "fix" application</summary>

```
$ kubectl get pod -A
NAMESPACE              NAME                                        READY   STATUS      RESTARTS   AGE
demo-sensorweb         helgoland-cf7ccb684-2w8ds                   1/1     Running     21         32d
ingress-nginx          ingress-nginx-admission-create-n5wpw        0/1     Completed   0          134m
ingress-nginx          ingress-nginx-admission-patch-knxnr         0/1     Completed   1          134m
ingress-nginx          ingress-nginx-controller-5d88495688-xdtsd   1/1     Running     2          134m
kube-system            coredns-74ff55c5b-j956h                     1/1     Running     69         104d
kube-system            etcd-minikube                               1/1     Running     90         104d
kube-system            ingress-nginx-admission-create-pkqsj        0/1     Completed   0          40d
kube-system            ingress-nginx-admission-patch-zzpjx         0/1     Completed   0          40d
kube-system            ingress-nginx-controller-6cb6b94bc9-79mh6   0/1     Pending     0          12m
kube-system            kube-apiserver-minikube                     1/1     Running     75         40d
kube-system            kube-controller-manager-minikube            1/1     Running     75         40d
kube-system            kube-proxy-thhs2                            1/1     Running     50         52d
kube-system            kube-scheduler-minikube                     1/1     Running     75         40d
kube-system            registry-pj8fc                              1/1     Running     23         32d
kube-system            registry-proxy-72gcx                        1/1     Running     22         32d
kube-system            storage-provisioner                         1/1     Running     91         104d
kubernetes-dashboard   dashboard-metrics-scraper-f6647bd8c-wfx2l   1/1     Running     39         40d
kubernetes-dashboard   kubernetes-dashboard-968bcb79-mdc6n         1/1     Running     55         40d
```

</details>

<details>
<summary>Minikube start logs</summary>

```
$ minikube start
😄  minikube v1.19.0 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.0 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
    ▪ Using image kubernetesui/dashboard:v2.1.0
    ▪ Using image kubernetesui/metrics-scraper:v1.0.4
    ▪ Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image registry:2.7.1
    ▪ Using image gcr.io/google_containers/kube-registry-proxy:0.4
🔎  Verifying registry addon...
🔎  Verifying ingress addon...
🌟  Enabled addons: default-storageclass, registry, storage-provisioner, dashboard, ingress
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

</details>

I can provide additional information, if required.

Kind regards and have a nice day!

**Comment by vagdevik** [comment]
I had the same issue.

The error disappeared when I have run the same command

```
minikube addons enable ingress
```
again after a minute. 
Then, the ingress was set-up after some time. So, the issue might be due to some network delays, I guess.

**Comment by Hongbo-Miao** [comment]
> Thanks @renich ! Met same issue. After `kubectl -n kube-system edit deployment ingress-nginx-controller`, change
> 
> ```
> us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller:v0.34.1@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
> ```
> 
> to
> 
> ```
> us.gcr.io/k8s-artifacts-prod/ingress-nginx/controller@sha256:0e072dddd1f7f8fc8909a2ca6f65e76c5f0d2fcfb8be47935ae3457e8bbceb20
> ```
> 
> (You can try verify by opening first URL in browser, which gets 404 error, the second one which is also version 0.34.1 which can be opened)
> 
> Basically just need remove `:v0.34.1`.
> 
> After editing, sine it is Vim, just type `:wq` or `:x` and hit Enter.
> 
> And then do `minikube addons enable ingress` again.

Just add another update. In later installation, this bug is still there, however, it seems not affecting anything. Even I have a new fresh installation from ground. What I did is just

```
minikube start
minikube addons enable ingress
```

and let minikube retry at the background, eventually it will succeed. The longest time takes like 3 hours after over 10 times retry I think.

**Comment by TimothyLoyer** [comment]
Does anyone know _why_ the URL is wrong or causing issues, and when it will be fixed? Having the ingress-controller break every time I (or someone on my team) restarts Minikube is becoming quite a problem.

**Comment by TimothyLoyer** [comment]
I did some searching and found this- looks like the registry used for the IngressController does not support using a tag and image digest in the same URL the way that docker.io does. https://github.com/google/go-containerregistry/issues/351

**Comment by williamhanseneric** [comment]
Having something so fundamentally broken like ingress is fairly disheartening...

**Comment by jmkozko** [comment]
@tstromberg, why was this issue closed if it's still an ongoing issue? Is it being tracked somewhere else? I just ran into it myself and it seems like an unnecessary landmine for tool that's centered around automation.

**Comment by dogewzy** [comment]
for user in china,you can specified http_proxy_port and https_proxy_port in minikube

**Comment by mnahinkhan** [comment]
What worked for me:

```
minikube start --driver=virtualbox
```

**Comment by aliaksander-samuseu** [comment]
It's still a problem, I'm facing this issue in Ubuntu 20. How can it not be fixed 2 years after it's reported?

**Comment by miladr0** [comment]
I ran to this issue on minikube version `v1.26.0` too.
steps that I've done to solve it:

- type `kubectl get pods -n ingress-nginx` and you should see something like the following:
```
NAME                                        READY   STATUS      RESTARTS        AGE
ingress-nginx-admission-create-zhp94        0/1     Completed   0               3h59m
ingress-nginx-admission-patch-ggrd8         0/1     Completed   0               3h59m
ingress-nginx-controller-755dfbfc65-xtrs5   0/1     ImagePullBackOff     1 (3h11m ago)   3h59m
```
- and then if you do `kubectl describe pod -n ingress-nginx <pod-name>` you should be able to see all of the logs within the pod.
I checked the logs of `ingress-nginx-controller-755dfbfc65-xtrs5` and saw its cant download the image.

- I logged in to minikube container using `minikube ssh`
- then manually download ingress-nginx-controller image using below command:
```
time docker pull k8s.gcr.io/ingress-nginx/controller:v1.2.1@sha256:5516d103a9c2ecc4f026efbd4b40662ce22dc1f824fb129ed121460aaa5c47f8
```

Note: I needed to download `v1.2.1` of ingress-nginx but if you need to download a newer or older version you can check the [google containers registry](https://console.cloud.google.com/gcr/images/k8s-artifacts-prod/us/ingress-nginx/controller) to find correct sha256:xxxx

**Comment by Anyc66666666** [comment]
minikube addons enable ingress --images="KubeWebhookCertgenCreate=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.1.1,KubeWebhookCertgenPatch=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-webhook-certgen:v1.1.1,IngressController=google_containers/nginx-ingress-controller:v1.2.1" --registries="IngressController=registry.cn-hangzhou.aliyuncs.com"

**Comment by jxiang93** [comment]
start your minikube with command below and it should work

` minikube start --insecure-registry="registry.k8s.io"`

then 

`minikube addons enable ingress`
