### ISSUE TITLE
Update documentation to show docker as a preferred driver

### ISSUE THREAD

**Issue by AlekSi** [kubernetes/minikube#8757]
Minikube switched to Docker driver by default on macOS in 1.12. But documentation still says that Hyperkit driver is preferred: https://minikube.sigs.k8s.io/docs/drivers/#macos

**Comment by afbjorklund** [comment]
Current terminology is a bit confusing. There is "Preferred" and "HighlyPreferred"

https://github.com/kubernetes/minikube/commit/7564651d504b90418fbabe82a94b709dc2ff35fb

**Comment by priyawadhwa** [comment]
If anyone is interested in contributing to documentation, feel free to comment on this issue
