### ISSUE TITLE
v1.10: sudo systemctl start docker: Process exited with status 1

### ISSUE THREAD

**Issue by nagesh1332** [kubernetes/minikube#8768]
* minikube v1.10.1 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: provision: ssh command error:
command : sudo diff -u /lib/systemd/system/docker.service /lib/systemd/system/docker.service.new || { sudo mv /lib/systemd/system/docker.service.new /lib/systemd/system/docker.service; sudo systemctl -f daemon-reload && sudo systemctl -f enable docker && sudo systemctl -f restart docker; }
err     : Process exited with status 1
output  : diff: can't stat '/lib/systemd/system/docker.service': No such file or directory
Created symlink /etc/systemd/system/multi-user.target.wants/docker.service → /usr/lib/systemd/system/docker.service.
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

* Updating the running virtualbox "minikube" VM ...
goroutine 1 [running]:
runtime/debug.Stack(0x6, 0x1dfae60, 0xc0001da120)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x29
k8s.io/minikube/pkg/minikube/node.configureRuntimes(0x3bdaef0, 0xc0008504e0, 0xc000393cf8, 0x8, 0x0, 0xc000374960, 0x40, 0xc00012c8c0, 0x6b, 0x898, ...)
        /app/pkg/minikube/node/start.go:257 +0x26c
k8s.io/minikube/pkg/minikube/node.Start(0x1e3a940, 0xc0008504e0, 0x1, 0x1e65f40, 0xc0000e7040, 0xc00039d980, 0xc000448e00, 0xc000492700, 0xc00054a5a0, 0x4e01, ...)
        /app/pkg/minikube/node/start.go:89 +0x1a8
k8s.io/minikube/cmd/minikube/cmd.startWithDriver(0x1e3a940, 0xc0008504e0, 0x1, 0x1e65f40, 0xc0000e7040, 0xc00039d980, 0xc000448e00, 0xc000492700, 0xc00054a5a0, 0xc000458a80, ...)
        /app/cmd/minikube/cmd/start.go:281 +0x83
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2b53760, 0x2b911b0, 0x0, 0x0)
        /app/cmd/minikube/cmd/start.go:202 +0x6f3
github.com/spf13/cobra.(*Command).execute(0x2b53760, 0x2b911b0, 0x0, 0x0, 0x2b53760, 0x2b911b0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b527a0, 0x0, 0x20, 0xc000004140)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
*
X Failed to enable container runtime: sudo systemctl start docker: Process exited with status 1
stdout:

stderr:
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

**Comment by tstromberg** [comment]
Can you please upgrade to minikube v1.12? I am confident that we have fixed this issue since v1.10.

Please let me know if it helps.

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this issue. Please reopen it if the issue persists.

**Comment by kakascx** [comment]
![image](https://user-images.githubusercontent.com/15819504/160777212-b31b2bb5-6955-48c8-bcd5-0b3f81480045.png)
same problem in v1.24.0
