### ISSUE TITLE
macOS docker: Container X is not running

### ISSUE THREAD

**Issue by satva** [kubernetes/minikube#8769]
**Steps to reproduce the issue:** 

1. Tried bringing up Minikube cluster on macOS (Mojave, Version - 10.14.6) with docker as driver 
2. It was not coming UP consistently . Attached the corresponding error below. 

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

<img width="1144" alt="Screen Shot 2020-07-18 at 1 14 58 PM" src="https://user-images.githubusercontent.com/11969761/87881048-7784bd80-c9ab-11ea-9c81-0db2466d8505.png">

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
Can you please upgrade to minikube v1.12? I believe we may have fixed this issue. If not, we should certainly be able to produce a more useful error message.

**Comment by satva** [comment]
Yes , looks it was consistent after upgrade .
