### ISSUE TITLE
Documentation: Minikube registry with docker uses 32773 instead of port 5000

### ISSUE THREAD

**Issue by nishaad78** [kubernetes/minikube#8771]
The documentation for [docker on macOS](https://minikube.sigs.k8s.io/docs/handbook/registry/#docker-on-macos) needs to be updated to listen to port 32773 instead, for pushing images locally:

```
docker run --rm -it --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):32773"
```

ref:
```
 > minikube addons enable registry                                                                                                   

💡  Registry addon on with docker uses 32773 please use that instead of default 5000
📘  For more information see: https://minikube.sigs.k8s.io/docs/drivers/docker
🔎  Verifying registry addon...
🌟  The 'registry' addon is enabled
```

Using Minikube v1.12.0 on Darwin 10.14.6 with Kubernetes v1.18.3 on Docker 19.03.2

**Comment by nishaad78** [comment]
A better alternative could be to use minikube's Docker daemon instead:
```
> eval $(minikube docker-env)
> docker build -t localhost:5000/myimage .
> docker push localhost:5000/myimage
```

**Comment by medyagh** [comment]
@nishaad78 due to the networking limirations of the docker on desktop on mac and indows, docker allocates a random port for 5000 and each time it is different.

as you see in the output of the addon when it enables, it, it changes each time you start minikube but minikube procides you that udpated port

```
 > minikube addons enable registry                                                                                                   

💡  Registry addon on with docker uses 32773 please use that instead of default 5000
📘  For more information see: https://minikube.sigs.k8s.io/docs/drivers/docker
🔎  Verifying registry addon...
🌟  The 'registry' addon is enabled
```

**Comment by mtsgrd** [comment]
Why is this closed? The documentation is clearly inaccurate and should be replaced with the explanation above.
