### ISSUE TITLE
Minikube port-forward service

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#878]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature Request

Add a `minikube port-forward servicename` command that port forwards a service using ssh port forwarding.  

`kubectl port-forward` does not support services yet because services aren't tied to a specific node.  However, minikube is single node so this make sense.

It would mimic the syntax of the `kubectl port-forward` command 
 ```
kubectl port-forward POD [LOCAL_PORT:]REMOTE_PORT [...[LOCAL_PORT_N:]REMOTE_PORT_N] [options]
```

ref https://github.com/kubernetes/kubernetes/issues/15180
ref https://github.com/kubernetes/minikube/issues/877

In my mind, this is different than the local VPN solution, although some of the backend port-forwarding logic could be reused if we ever decide on how to automate this process and remove the command
https://github.com/kubernetes/minikube/issues/38

**Comment by the-destro** [comment]
For at least HTTP services running something like traefik on the host and have it listen for kubernetes events could work for automating the port forwarding.

**Comment by Hajto** [comment]
@BUMP, For me good enough would be `port-forward hostPort:internalPort`

**Comment by calder** [comment]
`/remove-lifecycle stale`

**Comment by afbjorklund** [comment]
@r2d4 : this would be a good feature to have!

Similar to what I did for https://github.com/docker/machine/pull/4351

Sadly, it seems that "minikube ssh" doesn't work:

```Error: unknown shorthand flag: 'L' in -L```

**Comment by afbjorklund** [comment]
Is this related to #2501 somehow ?
