### ISSUE TITLE
Broken podman driver docs due to using templating in .inc file

### ISSUE THREAD

**Issue by Dean-Coakley** [kubernetes/minikube#8785]
https://minikube.sigs.k8s.io/docs/drivers/podman/#experimental docker link is broken.

As far as I can tell this is due to using templating in an `.inc` file which does not seem to be permitted.

https://github.com/kubernetes/minikube/blob/aaebd88251eca8400d95b7232c5d359c5d105679/site/content/en/docs/drivers/includes/podman_usage.inc#L3

Happy to open a PR pending some guidance on the solution that would be accepted. :)

**Comment by afbjorklund** [comment]
This is a bit unfortunate, because for some reason we only talk about to the podman driver here:

https://kubernetes.io/docs/tasks/tools/install-minikube/

In my book they are both equally experimental, though.

**Comment by Evalle** [comment]
Hi @afbjorklund I can start to work on this issue, if you don't mind. 
/assign
