### ISSUE TITLE
docker info --format "{{.CgroupDriver}}" crashes:  indirection through nil pointer to embedded struct

### ISSUE THREAD

**Issue by snirben** [kubernetes/minikube#8798]
**Steps to reproduce the issue:** 

1.sudo minikube start
2. 
3.

**Full output of failed command:** 

😄  minikube v1.12.1 on Ubuntu 18.04
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is Ubuntu 18.04.4 LTS
🐳  Preparing Kubernetes v1.18.3 on Docker  ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

💣  Failed to update cluster: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format {{.CgroupDriver}}: exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
	panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc000531320)
	/usr/local/go/src/text/template/exec.go:170 +0x1b5
panic(0x56247c12e4e0, 0x56247c484890)
	/usr/local/go/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x56247c3132e0, 0xc000280d40, 0x99, 0xc0004c2360, 0x2, 0x2, 0x0, 0x56247c541480, 0x56247c12e4e0)
	/usr/local/go/src/reflect/value.go:876 +0x39e
text/template.(*state).evalField(0xc0005312a0, 0x56247c3132e0, 0xc000280d40, 0x99, 0x7ffdf041c835, 0xc, 0x56247c5104c0, 0xc0004f04e0, 0xc00027bfb0, 0x1, ...)
	/usr/local/go/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc0005312a0, 0x56247c3132e0, 0xc000280d40, 0x99, 0x56247c3132e0, 0xc000280d40, 0x99, 0x56247c5104c0, 0xc0004f04e0, 0xc00027bfa0, ...)
	/usr/local/go/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc0005312a0, 0x56247c3132e0, 0xc000280d40, 0x99, 0xc0004f04e0, 0xc00027bfb0, 0x1, 0x1, 0x56247c1e1c60, 0x56247d425df8, ...)
	/usr/local/go/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc0005312a0, 0x56247c3132e0, 0xc000280d40, 0x99, 0xc0004f04b0, 0x56247c1e1c60, 0x56247d425df8, 0x99, 0xd0, 0x56247c2eaf60, ...)
	/usr/local/go/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc0005312a0, 0x56247c3132e0, 0xc000280d40, 0x99, 0xc000219a40, 0xc0004cb138, 0xc0004e7380, 0xc000531158)
	/usr/local/go/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc0005312a0, 0x56247c3132e0, 0xc000280d40, 0x99, 0x56247c510340, 0xc0004f0510)
	/usr/local/go/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc0005312a0, 0x56247c3132e0, 0xc000280d40, 0x99, 0x56247c510580, 0xc0004f0480)
	/usr/local/go/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc000280cc0, 0x56247c4a8080, 0xc0002dabd0, 0x56247c3132e0, 0xc000280d40, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
	/usr/local/go/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x56247c53c340, 0xc0003a81c0, 0x0, 0xc00027bd70, 0x1, 0x1, 0xc000280bc0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/cli/command/system/info.go:478 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc000482f00, 0x56247c53c340, 0xc0003a81c0, 0xc0003f0f90, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/system/info.go:85 +0x343
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc000482f00, 0xc0004ee2c0, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/system/info.go:52 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc000482f00, 0xc0004a0b80, 0x2, 0x2, 0xc000482f00, 0xc0004a0b80)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:762 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003a5b80, 0xc0004a0b70, 0x3, 0x3)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:800
main.runDocker(0xc0003a81c0, 0x56247c4aa5a0, 0xc000010020)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:281 +0x1d3
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:292 +0xf3

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
Crazy enough - the error here is that docker is crashing when provided this command-line:

`docker info --format "{{.CgroupDriver}}"`

Do you mind trying to run that command yourself to see what happens?

Assuming it crashes, can you share the output of:

`docker info`

**Comment by tstromberg** [comment]
If you are not on the most recent version of Docker, I recommend upgrading. I think we may be able to ignore this command if we get exit code 2, or blacklist the version you have to avoid the check. 

/cc @medyagh

**Comment by snirben** [comment]
restart the service of docker is the solution.
thank you.
