### ISSUE TITLE
Issue in minikube

### ISSUE THREAD

**Issue by DaudMurtazaRind** [kubernetes/minikube#8811]
daud@Latitude-E5510:~$ minikube start
😄  minikube v1.11.0 on Ubuntu 20.04
✨  Using the kvm2 driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🔥  Deleting "minikube" in kvm2 ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: machine didn't return an IP after 120 seconds
🔥  Creating kvm2 VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
😿  Failed to start kvm2 VM. "minikube start" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: machine didn't return an IP after 120 seconds

💣  error provisioning host: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: machine didn't return an IP after 120 seconds

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by sharifelgamal** [comment]
Sorry for the bad experience with the kvm2 driver, it just looks like machine creation timed out. Could you delete your cluster and rerun with `minikube start -v=3 --alsologtostderr` and possibly with `minikube logs`? That'll give us more information to help debug.

Also, you can try the newest version of minikube, which is currently 1.12.1 and see if that fixes the issue.

**Comment by priyawadhwa** [comment]
Hey @DaudMurtazaRind -- Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
