### ISSUE TITLE
Add CSI Hostpath driver as addon to minikube

### ISSUE THREAD

**Issue by 11janci** [kubernetes/minikube#8815]
I am currently working on enabling Volume Snapshots in minikube: #8343. Enabling the snapshots is however useless without a CSI based storage provider, which the user would have to configure manually. Adding the CSI hostpath driver as an addon would not only make the volume snapshots ready for use, but provide a complete CSI based storage solution to minikube.

This change would bring all the required yaml files from the driver to minikube. These files are dependent on kubernetes version, thus an upgrade of kubernetes in minikube could break it. However with a proper integration test this should be detected immediately and the yaml files upgraded accordingly.

If approved, I will rework my PR (#8461) and once done it would close both this issue as well as #8343.

kind/feature

**Comment by priyawadhwa** [comment]
This feature is currently in progress, thanks @11janci !
