### ISSUE TITLE
Add driver alias for kvm -> kvm2

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#8822]
Since we've dropped support for the original kvm like, 3 years ago, it would make sense to support users who drop the 2.

Example: https://twitter.com/csfinch/status/1286501747729604612/photo/1

**Comment by tstromberg** [comment]
We would probably need to put this alias logic in `cmd/minikube/cmd/start.go`, perhaps in the `selectDriver` function.

**Comment by Yogendra0Sharma** [comment]
@tstromberg Hi, can I work on this task?

**Comment by Yogendra0Sharma** [comment]
> `selectDriver`

I think we have to change https://github.com/kubernetes/minikube/blob/02cee02721d6e8c40cf80845160a9913e8bd8cf2/cmd/minikube/cmd/config/config.go#L184 also.

**Comment by Yogendra0Sharma** [comment]
Do we have to check if the provided driver is KVM or KVM2  we have to show a warning message for both the drivers?
https://github.com/kubernetes/minikube/blob/993504e0545ed9d7cee8140a29b7a04e3daac9f1/cmd/minikube/cmd/start.go#L512

**Comment by sharifelgamal** [comment]
Yeah so basically if the user supplies `kvm` as a driver name, we should just treat it as if they supplied `kvm2` for everything. We should only need to check it on start and convert a `kvm` passed in to `kvm2`.

**Comment by sharifelgamal** [comment]
> > `selectDriver`
> 
> I think we have to change
> 
> https://github.com/kubernetes/minikube/blob/02cee02721d6e8c40cf80845160a9913e8bd8cf2/cmd/minikube/cmd/config/config.go#L184
> 
> also.

Yikes, that's just very old documentation. That should updated to something more recent (like `minikube config set driver docker`) regardless.

**Comment by afbjorklund** [comment]
I don't think that minikube works with the original "kvm" driver anymore, it now requires our "kvm2" fork to function.

But there still is such a thing as `docker-machine-driver-kvm`, which is _supposed_ to work with `docker-machine`.

https://github.com/dhiltgen/docker-machine-kvm

It's all unsupported upstream anyway, so feel free to redirect all minikube users to use an existing minikube driver.

It actually uses [libvirt](https://libvirt.org/). At one point we actually tried to change the name, but it wasn't deemed important enough...

https://github.com/machine-drivers/docker-machine-driver-libvirt

**Comment by sadlil** [comment]
Hey @Yogendra0Sharma are you still working on this? If not i will like to take a look at this.

@medyagh @tstromberg A very small proposal, Instead of doing a replace for kvm to kvm2 in `selectDriver`, how do you feel about adding a field for aliases in [DriverDef](https://github.com/kubernetes/minikube/blob/master/pkg/minikube/registry/registry.go#L85). And change https://github.com/kubernetes/minikube/blob/master/pkg/minikube/registry/registry.go#L123 to also register the aliases with def.
Does this sounds reasonable (is there could be any other use cases for this) or i am overthinking this?

**Comment by sadlil** [comment]
@medyagh Put together a WIP PR for the proposal, please take a look https://github.com/kubernetes/minikube/pull/9672.
