### ISSUE TITLE
GCR connectivity check fails when custom SSL certs are used

### ISSUE THREAD

**Issue by bs444** [kubernetes/minikube#8834]
**Steps to reproduce the issue:** 

1. copy company .pem to ~/.minikube/files/etc/ssl/certs/mycacert.pem, chmod 644
2. minikube delete
3. minikube start --alsologtostderr -v=7

**Full output of failed command:** 

From  

I0724 20:06:48.783373   22631 ssh_runner.go:148] Run: sudo mkdir -p /etc/ssl/certs
I0724 20:06:48.791445   22631 ssh_runner.go:148] Run: stat -c "%s %y" /etc/ssl/certs/mycacert.pem
I0724 20:06:48.794930   22631 ssh_runner.go:205] existence check for /etc/ssl/certs/mycacert.pem: stat -c "%s %y" /etc/ssl/certs/mycacert.pem: Process exited with status 1

...

**Full output of `minikube start` command used, if not already included:**

😄  minikube v1.12.1 on Centos 7.8.2003
✨  Using the docker driver based on existing profile

❗  'docker' driver reported a issue that could affect the performance.
💡  Suggestion: enable overlayfs kernel module on your Linux

👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
❗  This container is having trouble accessing https://k8s.gcr.io

💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
E0724 20:43:31.472886   11654 start.go:97] Unable to get host IP: inspect IP bridge network "b96c74d6bc1b\nb092f4daf24a\nbe45ff17cbde".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" b96c74d6bc1b
b092f4daf24a
be45ff17cbde: exit status 1
stdout:

stderr:
Error: No such network: b96c74d6bc1b
b092f4daf24a
be45ff17cbde

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "b96c74d6bc1b\nb092f4daf24a\nbe45ff17cbde".: dockenetwork inspect --format "{{(index .IPAM.Config 0).Gateway}}" b96c74d6bc1b
b092f4daf24a
be45ff17cbde: exit status 1
stdout:

stderr:
Error: No such network: b96c74d6bc1b
b092f4daf24a
be45ff17cbde

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment]
@bs444 I am curious do you have docker swarm enabled ?
it seems that minikube can not get the network ip 
do you mind trying to disable docker swarm and try again?

/triage needs-information
/triage support

**Comment by bs444** [comment]
```
docker info | grep Swarm               349ms  Wed 12 Aug 2020 06:32:54 PM UTC

Swarm: inactive
```

**Comment by medyagh** [comment]
can you also please share 

"docker images | grep kic"

**Comment by bs444** [comment]
```
gcr.io/k8s-minikube/kicbase                v0.0.10             e6bc41c39dc4        3 months ago        974MB
```

**Comment by medyagh** [comment]
also I see 
```
❗ This container is having trouble accessing https://k8s.gcr.io
``` 
do you live in China or country with restricted access to gcr.io ? you might need to provide your company's image repository that has a mirror version of gcr.io 

for example
```
minikube start --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
```

**Comment by medyagh** [comment]
@bs444 I suspect you dont' have acess to gcr.io 
can you try this manually

```
docker pull k8s.gcr.io/kube-apiserver:v1.18.3
```

**Comment by bs444** [comment]
No I am not in China. The trouble is that https is proxied with a custom CA certificate. I am trying to let minikube to trust this certificate authority, (https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/) 

Even if I change minikube to point to Artifactory 

I do not agree with your recent title change of this ticket. Should still be:

"Minikube fails to copy PEM root CA certificate to /etc/ssl/certs/. So Minikube won't connect to https://k8s.gcr.io :

The issue is that these certificates I am placing in the correct location are NOT being copied into the container, and thus Minikube scripts are reporting this. The fact that the ca certs are not being imported means Minikube won't trust the connection.

**Comment by bs444** [comment]
If you have instructions on how to create a remote gcr.io repository inside of Artifactory, point me to it. I cannot find such instructions on how to create an image mirror for gcr.io, especially without login.

**Comment by bs444** [comment]
Specifically, I'm trying this: 

https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/#x509-certificate-signed-by-unknown-authority

**Comment by medyagh** [comment]
> No I am not in China. The trouble is that https is proxied with a custom CA certificate. I am trying to let minikube to trust this certificate authority, (https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/)
> 
> Even if I change minikube to point to Artifactory, I will still have to trust the same CA certificate as my Artifactory server is also using https with a custom CA certificate.
> 
> I do not agree with your recent title change of this ticket. Should still be:
> 
> "Minikube fails to copy PEM root CA certificate to /etc/ssl/certs/. So Minikube won't connect to https://k8s.gcr.io"
> 
> The issue is that these certificates I am placing in the correct location are NOT being copied into the container, and thus Minikube scripts are reporting this. The fact that the ca certs are not being imported means Minikube won't trust the connection.

thanks for waiting on this, we have integration tests that verfies we copy the cert inside minikube. so I would be surprised if it doesn't do that for you.

I still think your company has a diffrent registory mirror (simmilar to china) that blocked access to gcr.io

I believe you can fix this problem by getting the approved mirror your company/corp/network uses
and pass it to 

```
      --image-repository='': Alternative image repository to pull docker images from. This can be used when you have limited access to gcr.io. Set it to "auto" to let minikube decide one for you. For Chinese mainland users, you may use local gcr.io mirrors such as registry.cn-hangzhou.aliyuncs.com/google_containers

```

**Comment by priyawadhwa** [comment]
Hey @bs444 are  you still seeing this issue?

**Comment by bs444** [comment]
@medyagh 

> `docker pull k8s.gcr.io/kube-apiserver:v1.18.3`

```
$ docker image rm k8s.gcr.io/kube-apiserver:v1.18.3; docker pull k8s.gcr.io/kube-apiserver:v1.18.3
Untagged: k8s.gcr.io/kube-apiserver:v1.18.3
Untagged: k8s.gcr.io/kube-apiserver@sha256:e1c8ce568634f79f76b6e8168c929511ad841ea7692271caf6fd3779c3545c2d
Deleted: sha256:7e28efa976bd15fd8cfa42bb5e47e8e724af0f11e4b4ef59d6645099331665db
Deleted: sha256:d7a0fce1e976bf8f91b21048abc22cf363a5042b71bfaaf9e93427ca6adcf994
v1.18.3: Pulling from kube-apiserver
83b4483280e5: Already exists
2bfb66b13a96: Pull complete
Digest: sha256:e1c8ce568634f79f76b6e8168c929511ad841ea7692271caf6fd3779c3545c2d
Status: Downloaded newer image for k8s.gcr.io/kube-apiserver:v1.18.3
k8s.gcr.io/kube-apiserver:v1.18.3
```
and
```
$ nslookup k8s.gcr.io
...
Non-authoritative answer:
k8s.gcr.io      canonical name = googlecode.l.googleusercontent.com.
Name:   googlecode.l.googleusercontent.com
Address: 172.217.214.82
Name:   googlecode.l.googleusercontent.com
Address: 2607:f8b0:4001:c05::52
```

@priyawadhwa 
> are you still seeing this issue?

Yes, I am:

```
ssh_runner.go:148] Run: sudo mkdir -p /etc/ssl/certs
ssh_runner.go:148] Run: stat -c "%s %y" /etc/ssl/certs/mycacert.pem
ssh_runner.go:205] existence check for /etc/ssl/certs/mycacert.pem: stat -c "%s %y" /etc/ssl/certs/mycacert.pem: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/etc/ssl/certs/mycacert.pem': No such file or directory

ssh_runner.go:215] scp /home/me/.minikube/files/etc/ssl/certs/mycacert.pem --> /etc/ssl/certs/mycacert.pem (x bytes)
```

## Update:
I verified that the certificates were indeed added to the minikube container at /etc/ssl/certs/

```
docker exec -ti minikube /bin/bash
ls /etc/ssl/certs
```

However, I do not believe just copying them to /etc/ssl/certs is sufficient to allow the container to fully trust the cert.

```
<inside container>
$ docker exec -ti minikube /bin/bash
$ curl https://k8s.gcr.io -o output.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:05 --:--:--     0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

The following worked:

```
<inside container>
$ mkdir /usr/share/ca-certificates/extra
$ cp /etc/ssl/certs/mycacerts.crt /usr/share/ca-certificates/extra
$ dpkg-reconfigure ca-certificates
$ curl https://k8s.gcr.io -o output.html
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   241  100   241    0     0   1136      0 --:--:-- --:--:-- --:--:--  1136

$ cat output.html
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://cloud.google.com/container-registry/">here</A>.
</BODY></HTML>

```

Therefore, I believe the process (in ssh_runner.go?) for applying certs from the host to the container still needs to be updated.
It should be updated to apply the certs provided (in ~/.minikube/files/etc/ssl/certs) to the container in such a way that all internal tools, such as curl, automatically use them.

**Comment by tstromberg** [comment]
For clarity - do docker pulls work, or is this issue constrained to the curl command?

**Comment by drtywheels** [comment]
https://github.com/kubernetes/minikube/issues/8834



I have the exact same problem. Not sure how helpful it is but this is what I found.

```bash
$ docker images | grep kic
gcr.io/k8s-minikube/kicbase          v0.0.14                                          7ed8827b36a5        3 weeks ago         876MB
```

It seems you can have a root CA cert locally in ~/.minikube/files/etc/ssl/certs and it will be processed (copied to /etc/ssl/certs in the container) early on (before the curl command that fails) or in ~/.minikube/certs and it will be copied to /usr/share/ca-certificates and linked from /etc/ssl/certs. (this happens after the offending curl command).

If a root CA is sourced from ~/.minikube/files/etc/ssl/certs then the cert is copied to /etc/ssl/certs on the minikube container. It is not linked from /usr/share/ca-certificates.
Once minikube is up and running if you execute the curl command from within the minikube container it fails.


```bash
$ docker exec -ti minikube /bin/bash
root@minikube:/# curl -x http://192.168.1.9:3128 -sS -m 2 https://k8s.gcr.io/
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
root@minikube:/# ls -l /etc/ssl/certs/XXRootCA.pem
-rw-r--r-- 1 root root 2656 Dec  2 02:56 /etc/ssl/certs/XXRootCA.pem
```

However if the cert was sourced from ~/.minikube/certs it will get copied and linked to allow a successful curl command from within the container via a proxy.



```bash
$ docker exec -ti minikube /bin/bash
root@minikube:/# ls -l /etc/ssl/certs/XXRootCA.pem
lrwxrwxrwx 1 root root 48 Dec  2 03:07 /etc/ssl/certs/XXRootCA.pem -> /usr/share/ca-certificates/XXRootCA.pem
root@minikube:/# curl -x http://192.168.1.9:3128 -sS -m 2 https://k8s.gcr.io/
<HTML><HEAD><meta http-equiv="content-type" content="text/html;charset=utf-8">
<TITLE>302 Moved</TITLE></HEAD><BODY>
<H1>302 Moved</H1>
The document has moved
<A HREF="https://cloud.google.com/container-registry/">here</A>.
</BODY></HTML>
```



It seems like what ever is processing the cert from ~/.minikube/files/etc/ssl/certs isn't doing the same thing as when processed from ~/.minikube/certs 

So the timing can be seen clearly here's some log snippets where I have the cert in both ~/.minikube/files/etc/ssl/certs and ~/.minikube/certs



```bash
I1202 14:43:24.279701   10188 filesync.go:118] Scanning /Users/myuser/.minikube/addons for local assets ...
I1202 14:43:24.279910   10188 filesync.go:118] Scanning /Users/myuser/.minikube/files for local assets ...
I1202 14:43:24.280954   10188 filesync.go:141] local asset: /Users/myuser/.minikube/files/etc/ssl/certs/XXRootCA.pem -> XXRootCA.pem in /etc/ssl/certs
I1202 14:43:24.280965   10188 vm_assets.go:96] NewFileAsset: /Users/myuser/.minikube/files/etc/ssl/certs/XXRootCA.pem -> /etc/ssl/certs/XXRootCA.pem
I1202 14:43:24.281070   10188 ssh_runner.go:148] Run: sudo mkdir -p /etc/ssl/certs
I1202 14:43:24.295605   10188 ssh_runner.go:148] Run: stat -c "%s %y" /etc/ssl/certs/XXRootCA.pem
I1202 14:43:24.303593   10188 command_runner.go:109] ! stat: cannot stat '/etc/ssl/certs/XXRootCA.pem': No such file or directory
I1202 14:43:24.303633   10188 ssh_runner.go:205] existence check for /etc/ssl/certs/XXRootCA.pem: stat -c "%s %y" /etc/ssl/certs/XXRootCA.pem: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/etc/ssl/certs/XXRootCA.pem': No such file or directory
I1202 14:43:24.303696   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/files/etc/ssl/certs/XXRootCA.pem --> /etc/ssl/certs/XXRootCA.pem (2656 bytes)
.
.
.
.
I1202 14:43:25.014527   10188 ssh_runner.go:148] Run: systemctl --version
I1202 14:43:25.014691   10188 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1202 14:43:25.014863   10188 ssh_runner.go:148] Run: curl -x http://192.168.1.9:3128 -sS -m 2 https://k8s.gcr.io/
I1202 14:43:25.016308   10188 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1202 14:43:25.294082   10188 command_runner.go:109] > systemd 245 (245.4-4ubuntu3.3)
I1202 14:43:25.294119   10188 command_runner.go:109] > +PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid
I1202 14:43:26.206578   10188 command_runner.go:109] ! curl: (60) SSL certificate problem: self signed certificate in certificate chain
I1202 14:43:26.206633   10188 command_runner.go:109] ! More details here: https://curl.haxx.se/docs/sslcerts.html
I1202 14:43:26.206689   10188 command_runner.go:109] ! curl failed to verify the legitimacy of the server and therefore could not
I1202 14:43:26.206716   10188 command_runner.go:109] ! establish a secure connection to it. To learn more about this situation and
I1202 14:43:26.206721   10188 command_runner.go:109] ! how to fix it, please visit the web page mentioned above.
I1202 14:43:26.206732   10188 ssh_runner.go:188] Completed: curl -x http://192.168.1.9:3128 -sS -m 2 https://k8s.gcr.io/: (1.191795539s)
W1202 14:43:26.206776   10188 start.go:509] [curl -x http://192.168.1.9:3128 -sS -m 2 https://k8s.gcr.io/] failed: curl -x http://192.168.1.9:3128 -sS -m 2 https://k8s.gcr.io/: Process exited with status 60
stdout:

stderr:
curl: (60) SSL certificate problem: self signed certificate in certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
I1202 14:43:26.206910   10188 ssh_runner.go:148] Run: sudo systemctl cat docker.service
W1202 14:43:26.207012   10188 out.go:146] ❗  This container is having trouble accessing https://k8s.gcr.io
❗  This container is having trouble accessing https://k8s.gcr.io
W1202 14:43:26.207068   10188 out.go:146] 💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
.
.
.
.
I1202 14:43:27.931797   10188 vm_assets.go:96] NewFileAsset: /Users/myuser/.minikube/certs/XXRootCA.pem -> /usr/share/ca-certificates/XXRootCA.pem
I1202 14:43:27.932490   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/profiles/minikube/apiserver.crt --> /var/lib/minikube/certs/apiserver.crt (1399 bytes)
I1202 14:43:27.962782   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/profiles/minikube/apiserver.key --> /var/lib/minikube/certs/apiserver.key (1675 bytes)
I1202 14:43:27.991844   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/profiles/minikube/proxy-client.crt --> /var/lib/minikube/certs/proxy-client.crt (1147 bytes)
I1202 14:43:28.021534   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/profiles/minikube/proxy-client.key --> /var/lib/minikube/certs/proxy-client.key (1679 bytes)
I1202 14:43:28.051391   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/ca.crt --> /var/lib/minikube/certs/ca.crt (1111 bytes)
I1202 14:43:28.081649   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/ca.key --> /var/lib/minikube/certs/ca.key (1675 bytes)
I1202 14:43:28.112961   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/proxy-client-ca.crt --> /var/lib/minikube/certs/proxy-client-ca.crt (1119 bytes)
I1202 14:43:28.145129   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/proxy-client-ca.key --> /var/lib/minikube/certs/proxy-client-ca.key (1675 bytes)
I1202 14:43:28.175074   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/ca.crt --> /usr/share/ca-certificates/minikubeCA.pem (1111 bytes)
I1202 14:43:28.206807   10188 ssh_runner.go:148] Run: stat -c "%s %y" /usr/share/ca-certificates/XXRootCA.pem
I1202 14:43:28.214876   10188 command_runner.go:109] ! stat: cannot stat '/usr/share/ca-certificates/XXRootCA.pem': No such file or directory
I1202 14:43:28.214932   10188 ssh_runner.go:205] existence check for /usr/share/ca-certificates/XXRootCA.pem: stat -c "%s %y" /usr/share/ca-certificates/XXRootCA.pem: Process exited with status 1
stdout:

stderr:
stat: cannot stat '/usr/share/ca-certificates/XXRootCA.pem': No such file or directory
I1202 14:43:28.215018   10188 ssh_runner.go:215] scp /Users/myuser/.minikube/certs/XXRootCA.pem --> /usr/share/ca-certificates/XXRootCA.pem (2656 bytes)
I1202 14:43:28.246073   10188 ssh_runner.go:215] scp memory --> /var/lib/minikube/kubeconfig (392 bytes)
I1202 14:43:28.269179   10188 ssh_runner.go:148] Run: openssl version
I1202 14:43:28.281910   10188 command_runner.go:109] > OpenSSL 1.1.1f  31 Mar 2020
I1202 14:43:28.282730   10188 ssh_runner.go:148] Run: sudo /bin/bash -c "test -s /usr/share/ca-certificates/XXRootCA.pem && ln -fs /usr/share/ca-certificates/XXRootCA.pem /etc/ssl/certs/XXRootCA.pem"
I1202 14:43:28.308129   10188 ssh_runner.go:148] Run: ls -la /usr/share/ca-certificates/XXRootCA.pem
I1202 14:43:28.322008   10188 command_runner.go:109] > -rw-r--r-- 1 root root 2656 Dec  2 03:05 /usr/share/ca-certificates/XXRootCA.pem
I1202 14:43:28.322037   10188 certs.go:389] hashing: -rw-r--r-- 1 root root 2656 Dec  2 03:05 /usr/share/ca-certificates/XXRootCA.pem
I1202 14:43:28.322147   10188 ssh_runner.go:148] Run: openssl x509 -hash -noout -in /usr/share/ca-certificates/XXRootCA.pem
I1202 14:43:28.339260   10188 command_runner.go:109] > 9052bf42
I1202 14:43:28.339401   10188 ssh_runner.go:148] Run: sudo /bin/bash -c "test -L /etc/ssl/certs/9052bf42.0 || ln -fs /etc/ssl/certs/XXRootCA.pem /etc/ssl/certs/9052bf42.0"
I1202 14:43:28.359783   10188 ssh_runner.go:148] Run: sudo /bin/bash -c "test -s /usr/share/ca-certificates/minikubeCA.pem && ln -fs /usr/share/ca-certificates/minikubeCA.pem /etc/ssl/certs/minikubeCA.pem"
```

**Comment by medyagh** [comment]
@bs444 thanks for patiently giving us all this information I wonder if this is simmilar to this issue https://github.com/kubernetes/minikube/issues/11068


@bs444 if you explicitly specify the --base-image would it not error out ?

do u have a current work arround that works ? if yes how about we add this to our tutorials for other Enterprise Users with custom certs ? could be a new page here https://minikube.sigs.k8s.io/docs/tutorials/

**Comment by medyagh** [comment]
I will bump this issue to soon !

**Comment by medyagh** [comment]
seems simmilar to https://github.com/kubernetes/minikube/issues/11068

**Comment by bs444** [comment]
👍
