### ISSUE TITLE
HyperV: Error finding IPV4 address for vEthernet (minikube v switch)

### ISSUE THREAD

**Issue by ca6a** [kubernetes/minikube#8847]
**Steps to reproduce the issue:** 

1.minikube start --vm-driver hyperv --hyperv-virtual-switch "minikube v switch"
2. 
3.
X failed to start node: startup failed: Failed to setup kubeconfig: ip for interface (minikube v switch): Error finding IPV4 address for vEthernet (minikube v switch)

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
This means that minikube either could not find the hyperv switch you specified, or the switch is somehow misconfigured.

Can you run delete and rerun minikube start with `-v=3 --alsologtostderr` for more details?

**Comment by ca6a** [comment]
Thanks, i will check

**Comment by priyawadhwa** [comment]
Hey @ca6a this looks like a dupe of https://github.com/kubernetes/minikube/issues/8152 which was fixed by https://github.com/kubernetes/minikube/pull/8778

Could you try upgrading to v1.12.2 which should incorporate this change and see if that resolves your issue?

**Comment by sharifelgamal** [comment]
This should be fixed with the latest minikube, feel free to reopen if it remains an issue.
