### ISSUE TITLE
Error creating machine

### ISSUE THREAD

**Issue by saibanna** [kubernetes/minikube#8848]
**Steps to reproduce the issue:** 

1 # minikube start --vm-driver=hyperkit

**Full output of failed command:** 

error provisioning host: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory

**Full output of `minikube start` command used, if not already included:**

😄  minikube v1.12.1 on Darwin 10.15.5
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in hyperkit ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start hyperkit VM. "minikube start" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory

**Optional: Full output of `minikube logs` command:**
<details>
# minikube logs
E0727 21:34:47.914027   19091 logs.go:200] Failed to list containers for "kube-apiserver": docker: NewSession: new client: new client: dial tcp :22: connect: connection refused
E0727 21:34:50.976159   19091 logs.go:200] Failed to list containers for "etcd": docker: NewSession: new client: new client: dial tcp :22: connect: connection refused
E0727 21:34:54.165813   19091 logs.go:200] Failed to list containers for "coredns": docker: NewSession: new client: new client: dial tcp :22: connect: connection refused
E0727 21:34:57.742619   19091 logs.go:200] Failed to list containers for "kube-scheduler": docker: NewSession: new client: new client: dial tcp :22: connect: connection refused
E0727 21:35:01.293358   19091 logs.go:200] Failed to list containers for "kube-proxy": docker: NewSession: new client: new client: dial tcp :22: connect: connection refused
E0727 21:35:04.251148   19091 logs.go:200] Failed to list containers for "kubernetes-dashboard": docker: NewSession: new client: new client: dial tcp :22: connect: connection refused
E0727 21:35:07.447952   19091 logs.go:200] Failed to list containers for "storage-provisioner": docker: NewSession: new client: new client: dial tcp :22: connect: connection refused
E0727 21:35:10.377899   19091 logs.go:200] Failed to list containers for "kube-controller-manager": docker: NewSession: new client: new client: dial tcp :22: connect: connection refused
==> Docker <==
E0727 21:35:13.752522   19091 logs.go:178] command /bin/bash -c "sudo journalctl -u docker -n 60" failed with error: NewSession: new client: new client: dial tcp :22: connect: connection refused output: ""

==> container status <==
E0727 21:35:16.151572   19091 logs.go:178] command /bin/bash -c "sudo `which crictl || echo crictl` ps -a || sudo docker ps -a" failed with error: NewSession: new client: new client: dial tcp :22: connect: connection refused output: ""

==> describe nodes <==
E0727 21:35:19.350206   19091 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: NewSession: new client: new client: dial tcp :22: connect: connection refused output: ""

==> dmesg <==
E0727 21:35:21.734395   19091 logs.go:178] command /bin/bash -c "sudo dmesg -PH -L=never --level warn,err,crit,alert,emerg | tail -n 60" failed with error: NewSession: new client: new client: dial tcp :22: connect: connection refused output: ""

==> kernel <==
E0727 21:35:25.517216   19091 logs.go:178] command /bin/bash -c "uptime && uname -a && grep PRETTY /etc/os-release" failed with error: NewSession: new client: new client: dial tcp :22: connect: connection refused output: ""

==> kubelet <==
E0727 21:35:27.701210   19091 logs.go:178] command /bin/bash -c "sudo journalctl -u kubelet -n 60" failed with error: NewSession: new client: new client: dial tcp :22: connect: connection refused output: ""

❗  unable to fetch logs for: Docker, container status, describe nodes, dmesg, kernel, kubelet

</details>

**Comment by sharifelgamal** [comment]
This dhcp leases issue has long haunted the hyperkit driver, there are any number of reasons that this could happen, ranging from VPN to firewall to antivirus software. Take a look at the options offered in https://github.com/kubernetes/minikube/issues/4206 for more details on how to debug.

The tl;dr is
- Try disabling "Internet Sharing" in your Network Preferences
- If there is a VPN running, try turning it off
- If there is anti-virus software, try turning it off

**Comment by medyagh** [comment]
@saibanna have you tried the suggestions by sharif ? 
btw in mac os I recommend using our Docker driver. and has less issues with VPN

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this for now since there hasn't been an update from OP, but please feel free to reopen with more details if it remains an issue.
