### ISSUE TITLE
Having an issue with minikube start on MacOS

### ISSUE THREAD

**Issue by petebirk** [kubernetes/minikube#8862]
Trying to setup minikube following steps here:  https://backstage.forgerock.com/docs/forgeops/6.5/devops-guide-minikube/#devops-guide-minikube.   

The start command fails and I think it's related to the "Unauthorized" you see below.   If I do anything with kubectl, it gives me an error "You must be logged in to the server (Unauthorized)".   In the minikube logs, there is info about an expired certificate, but not sure what to do about it. . I have uninstalled minikube and kubectl and reinstalled to no avail.  Thanks for any assistance on this.  

Using the following start command (took about 10 minutes to complete):

Peters-MacBook-Pro:~ peter$ minikube start —memory=8192 --cpus=2 -v=7 --disk-size=40g --vm-driver=virtualbox --bootstrapper kubeadm --kubernetes-version=1.17.4
😄  minikube v1.12.1 on Darwin 10.14.6
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=40960MB) ...
🐳  Preparing Kubernetes v1.17.4 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
🌟  Enabled addons: default-storageclass, storage-provisioner

💣  failed to start node: startup failed: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.17.4

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

I've attached the output of minikube logs.

[minikube-logs.log](https://github.com/kubernetes/minikube/files/4988794/minikube-logs.log)

Here are a few more commands..

Peters-MacBook-Pro:Downloads peter$ **minikube status**
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

Peters-MacBook-Pro:Downloads peter$ **minikube kubectl cluster-info**

To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
error: **You must be logged in to the server (Unauthorized)**

Peters-MacBook-Pro:bin peter$ **kubectl cluster-info dump**
error: You must be logged in to the server (Unauthorized)

Use "minikube <command> --help" for more information about a given command.
Peters-MacBook-Pro:Downloads peter$ **minikube dashboard**
🔌  Enabling dashboard ...
🤔  Verifying dashboard health ...
_<hangs right here for about 10 minutes>_
 dashboard service is not running: Temporary Error: Error getting service kubernetes-dashboard: Unauthorized

**Comment by petebirk** [comment]
This can be closed..  I had upgraded from an older version of minikube recently..  The issue documented below fixed the problem.  I ran "minikube delete --all --purge" and that fixed it.   Thanks!

https://github.com/kubernetes/minikube/issues/8844

**Comment by priyawadhwa** [comment]
@petebirk glad your issue is fixed! I'll go ahead and close this issue.
