### ISSUE TITLE
minikube v1.12.1 docker driver:  container exited unexpectedly

### ISSUE THREAD

**Issue by Gaurav7296** [kubernetes/minikube#8888]
* minikube v1.12.1 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the docker driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Creating docker container (CPUs=2, Memory=1991MB) ...
* Stopping "minikube" in docker ...
! Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 2.6520123s
* Restarting the docker service may improve performance.
* Deleting "minikube" in docker ...
! StartHost failed, but will try again: creating host: create: creating: create kic node: container name "minikube": container exited unexpectedly
* Creating docker container (CPUs=2, Memory=1991MB) ...
* Failed to start docker container. "minikube start" may fix it: creating host: create: creating: create kic node: container name "minikube": container exited unexpectedly

! The minikube docker container exited unexpectedly.
* If you are still interested to make docker driver work. The following suggestions might help you get passed this issue:
*
        - Prune unused docker images, volumes and abandoned containers.
*
        - Restart your docker service
*
        - Ensure your docker daemon has access to enough CPU/memory resources.
*
        - Docs https://docs.docker.com/docker-for-windows/#resources
*
        - Delete and recreate minikube cluster
                minikube delete
                minikube start --driver=docker

**Comment by rubenhak** [comment]
experiencing same issue.

**Comment by shakerman** [comment]
Same here... frustrating, can't find a solution.

**Comment by rubenhak** [comment]
after few hours of trying the deleting ~/.minikube and reinstalling minikube helped with making it work with hyperv driver (docker driver still doesn't work).

**Comment by medyagh** [comment]
@rubenhak @shakerman we fixed a "container exited unexpectedly" bug in minkube v1.12.2 have you tried with latest version and see if the problem still happen ?

**Comment by medyagh** [comment]
I recommend using the latest minikube verison as we improved the number of entrypoint flakes

@rubenhak @shakerman @Gaurav7296
