### ISSUE TITLE
StartHost timeout should be configurable

### ISSUE THREAD

**Issue by petr-motejlek** [kubernetes/minikube#8897]
https://github.com/kubernetes/minikube/issues/8512 mentions everything.

My actual use case is on Hyper-V, when creating a disk image for 128 GBs takes more than 240 seconds (the hardcoded timeout), and thus the whole `minikube start` fails.

I guess, this might be two things

* One is to allow configuring the timeout.
* Second is figuring out why does the creation take so long, anyway. During the creation of the VM, it seems like the disk first gets created, then it gets converted. Not sure why would either of these operations take long time, since I am on NVMe PCIe3 SSD, and even filling the file with zeroes should be a matter of several seconds.

I think if we have configurabl timeout, then I can live with this. BUt if there's a way to make the creationg faster (Well withing the hard coded timeout), that would work too.

**Comment by sharifelgamal** [comment]
I believe this is fixed.
