### ISSUE TITLE
Symbolic links don't work in Mounted Host Folders

### ISSUE THREAD

**Issue by tslater** [kubernetes/minikube#890]
**Minikube version**: v0.12.2

**Environment**:
- **OS** : MacOS v10.12.1
- **VM Driver**: xhyve
- **Docker version** (e.g. `docker -v`): Docker version 1.12.2
- **Install tools**: brew

**What happened**: 
I received an error "ln: symlinktestfilelinked.txt: Operation not permitted"

**What you expected to happen**:
Create a successful symbolic link

**How to reproduce it** (as minimally and precisely as possible):
```
minikube ssh
cd /Users/your-user-dir
touch symlinktestfilesource.txt
ln -s symlinktestfilesource.txt symlinktestfilelinked.txt 
```
**Anything else do we need to know**:
This is important to me because I try and do things like `npm install` inside the container (for local development), and I'll get errors about it not being able to make symbolic links.

**Comment by iameli** [comment]
Anyone have any ideas for this? This blocks the xhyve driver for our use case, which is a shame 'cause it's otherwise so much faster. I'd love to spend some time digging into it, but I have no idea where to start.

**Comment by SpencerMalone** [comment]
Any updates? I did note that this is the case for the default more custom configured `/Users` folder, as well as folders mounted with `minikube mount`

**Comment by SpencerMalone** [comment]
Also, I had this happen with a non-xhyve driver as well. 
```
user$ minikube start --vm-driver virtualbox
Starting local Kubernetes v1.6.0 cluster...
Starting VM...
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
user$ minikube ssh
$ cd /Users/<redacted>/
$ touch newoutput2.txt
$ ln -s newoutput2.txt test.txt
ln: failed to create symbolic link 'test.txt': Operation not permitted
```

**Comment by SpencerMalone** [comment]
Interestingly, with the virtualbox driver, the following behavour is exhibited:

- When looking in the default `/Users` folder on a mac, symbolic links work

- If you mount a directory using `minikube mount`, the symbolic links will NOT work

ex:
```
$ cd /mnt/web/_domains/login/
$ ls -l
total 7
<redacted>
-rwxr-xr-x 1 4294967294 4294967294  13 Aug  1  2016 _cache
<redacted>
$ cd  Users/<redacted>/web/_domains/login/
$ ls -l
total 48
lrwxr-xr-x 1 docker docker  13 Aug  1  2016 _cache -> ../../_cache/
```

**Comment by gh-aw** [comment]
I too am running in to this issue in the same environment as above. Any word on this?

**Comment by scheler** [comment]
+1

**Comment by iameli** [comment]
FWIW this issue moved our team from minikube to Kubernetes for Docker for Mac, which is working fine

**Comment by jpswade** [comment]
This is still an issue with minikube.

**Comment by jpswade** [comment]
@iameli What was the fix? Could it be brought into minikube? Is minikube abandoned in favour of Docker for Mac?
