### ISSUE TITLE
how to set --uid & --gid in mounting hostpath in yaml file?

### ISSUE THREAD

**Issue by bfznj** [kubernetes/minikube#8900]
Greetings...

minikube version: v0.28.2, Ubuntu 16.04 server.

I use a yaml file to create a deployment. Since my home directory is automatically mapped to /hosthome in the minikube VM, which is the node where pods will be created. So I use following section to mount my node's hostpath subfolder to a folder in the pod.

  | | | volumeMounts:
  | | | - mountPath: /var/mqm/data/QMGR1
  | | | | name: mqdata
  | | volumes:
  | | - name: mqdata
  | | | hostPath:
  | | | | path: /hosthome/user1/data/mq/QMGR1

The container didn't run in the pod. So I ssh into the pod, and find the mounted folder has ownership 1001:1001, which is quite strange as uid 1001 and gid 1001 don't even exist in the Pod. 

I read other experienced the same but were recommended to use --uid, and --gid flags to set it to the right ownership. But how can that be done in a yaml file?

**Comment by medyagh** [comment]
@bfznj I noticed your minikube version is an ancient version, I am quite amazed that version still works!  :) 
I believe your question is more related to kuberentes itself and I assume the version of kuberntes you are using must be very old, is there a reason you don't use an latest minikube version ?
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/triage support

**Comment by bfznj** [comment]
*   minikube version: v1.12.2
  *   kubectl version v1.18.6
  *   docker Version: 19.03.12

But I also realized after the upgrade, the hosthome folder is no longer there in the minikube VM, so I can't map a host volume any more to the VM and then to Pods.

Someone pointed to local persistent volume. But it seems to work only for base node, not VM based node. would you mind share a trick?

thanks much,
Ben

________________________________

**Comment by medyagh** [comment]
@bfznj you could either use PVC or use mount

https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/
https://minikube.sigs.k8s.io/docs/handbook/mount/

does that help ?


/triage needs-information
/triage support

**Comment by medyagh** [comment]
Hi @, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
