### ISSUE TITLE
hyperkit: trouble accessing https://k8s.gcr.io

### ISSUE THREAD

**Issue by SudhakarKonduru** [kubernetes/minikube#8902]
**Steps to reproduce the issue:** 

1. Mac OS Catalina
2. brew install minikube
3. Not behind VPN or Proxy
3. minikube start

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
/Users/xxxxx> minikube start
😄  minikube v1.12.1 on Darwin 10.15.6
✨  Automatically selected the docker driver. Other choices: hyperkit, virtualbox
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v4-v1.18.3-docker-overlay2-amd64.tar.lz4: 526.27 MiB
🔥  Creating docker container (CPUs=2, Memory=1990MB) ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
/Users/xxxx> 

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Could you post the output of `minikube start -v 5 --alsologtostderr`? That should give us more information to work with to help.

**Comment by douglascamata** [comment]
This has been a problem for since the very first version of minikube with hyperkit: it never got internet connectivity. 

```
W0819 18:51:31.785221   68561 start.go:505] [curl -sS -m 2 https://k8s.gcr.io/] failed: curl -sS -m 2 https://k8s.gcr.io/: Process exited with status 6
stdout:

stderr:
curl: (6) Could not resolve host: k8s.gcr.io```

**Comment by douglascamata** [comment]
I can ping IP addresses from inside the VM but DNS resolution doesn't work at all. Any `nslookup` will fail.

**Comment by douglascamata** [comment]
I reported the same exact problem, which wasn't solved yet in #5951.

**Comment by medyagh** [comment]
@douglascamata do you happen to use a VPN ? if you are using a VPN or a corp network, I suggest using our docker driver.


you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by douglascamata** [comment]
I do use a corporate VPN. The docker driver works, but eats a lot of cpu on
idle. I end up using virtualbox.

**Comment by sharifelgamal** [comment]
The docker driver normally has less CPU overhead than the virtualbox driver, make sure your docker environment is healthy with `docker system prune`.

Either way, I'm going to go ahead and close this issue.

**Comment by dpalmeira** [comment]
Hi I have same issue. If I switch from docker to hyperkit I cannot pull any image from Internet.
BTW, I trying to switch from docker to hyperkit because it seems to be a requirement to enable Nginx ingress on MAC
minikube addons enable ingress <-- this only seems to work with hyperkit.

How can I fix it? I don't mind about vm-driver (docker/hyperkit), I just want to get working the ingress to be able to call my local Nginx in my app with minikube on MAC.

Any idea?

Thank you for your time and help!
