### ISSUE TITLE
Possibility to configure pvDir for storage-provisioner addon

### ISSUE THREAD

**Issue by g9rga** [kubernetes/minikube#8903]
I have a huge minikube cluster for local development with many stateful services(like mysql, rabbitmq, etc). 
If I use docker driver in case of minikube profile recreation(for example, upgrading k8s version or changing cluster resources or something else) I will lose all of my persistent data, because in current implementation **pvDir** is a constant - `/tmp/hostpath-provisioner`.

It would be nice to have possibility to configure **pvDir** option for storage-provisioner, like: `minikube addons configure storage-provisioner`, then I could set **pvDir** to host mounted directory, create necessary pv on cluster setup and all my persistent data would be available on profile recreation.

What do you think about it?

P.S. Now, I use my own version of storage-provisoner to protect my data from losing.

**Comment by afbjorklund** [comment]
Seems like a duplicate of #3318 and #5144, but I guess it is more about #8151 - it was **never** supposed to use /tmp

In the current implementation of minikube (docker driver), the persistent volumes are now being stored on /var instead.

There's another story about host mounts: #7604

I guess those could be mounted in /tmp (or /var)

**Comment by g9rga** [comment]
@afbjorklund ok, I understood, thank you so much for reply

**Comment by afbjorklund** [comment]
@g9rga : no worries, sorry about the data loss. But with minikube 1.12.2, they _should_ end up on the docker volume

One current "problem" with minikube is that both container images and persistent data is mixed, on the same disk image

If you have huge amounts of data, like your stateful services, then it might need **dedicated** disk images / docker volumes.

But the current design only allows for one `/mnt/sda1` or `/var`, and there is no easy way to add custom images/volumes.
