### ISSUE TITLE
virtualbox: cannot create directory '/var/lib/minikube/binaries': Input/output error

### ISSUE THREAD

**Issue by reshma-aws** [kubernetes/minikube#8905]
Hi All, 

I've been trying to install and create a cluster using minikube on MacBook and I get the below error. 

MacOS : Catalina 10.15.6
Version 6.1.12 r139181 (Qt5.6.3)
Used the below commands to install kubectl and minikube
kubectl:
1. curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/kubectl"
2. chmod +x ./kubectl
3. sudo mv ./kubectl /usr/local/bin/kubectl
4. kubectl version --client

minikube
1. sysctl -a | grep -E --color 'machdep.cpu.features|VMX'
2. curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-darwin-amd64 \
  && chmod +x minikube
3. sudo mv minikube /usr/local/bin

minikube start 
😄  minikube v1.12.1 on Darwin 10.15.6
✨  Automatically selected the virtualbox driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.12 ...
❌  Unable to load cached images: loading cached images: transferring cached image: sudo test -d /var/lib/minikube/images && sudo scp -t /var/lib/minikube/images && sudo touch -d "2020-08-03 06:16:43.744700636 +0530" /var/lib/minikube/images/storage-provisioner_v1.8.1: Process exited with status 1
output: 

💣  Failed to update cluster: updating control plane: downloading binaries: sudo mkdir -p /var/lib/minikube/binaries/v1.18.3: Process exited with status 1
stdout:

stderr:
mkdir: cannot create directory '/var/lib/minikube/binaries': Input/output error

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

Things encountered:
1. /var/lib/minikube directory is not being created
2. even tried to promote current user to super user

Kindly help me resolve this. 
Regards
Reshma

**Comment by sharifelgamal** [comment]
The line `mkdir: cannot create directory '/var/lib/minikube/binaries': Input/output error` is very suspicious. This isn't a permission error (that usually says `access is denied`), it seems like that part of your file system is corrupt in some way.

**Comment by tstromberg** [comment]
This sounds like a corrupt VirtualBox disk. Please run `minikube delete`. You may have less occurrences of this with the docker or hyperkit drivers.
