### ISSUE TITLE
already download the preload image

### ISSUE THREAD

**Issue by lowang-bh** [kubernetes/minikube#8906]
**Steps to reproduce the issue:** 

1. minikube start --driver=hyperkit
2. output "Downloading Kubernetes v1.18.3 preload ..." and will download it even through it is already exist.
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
😄  Darwin 10.12.3 上的 minikube v1.12.1
✨  根据现有的配置文件使用 hyperkit 驱动程序
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v4-v1.18.3-docker-overlay2-amd64.tar.lz4: 331.48 Mi

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
I suspect we upgraded the version of the preload tarballs, does this happen on subsequent starts?

**Comment by sharifelgamal** [comment]
@lowang-bh is this still an issue?

**Comment by medyagh** [comment]
I think this was fixed and no longer an issue, please reopen if it is still happening
