### ISSUE TITLE
v1.12.2 & crio outputs error: stat storage-provisioner_v2: no such file or directory

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#8919]
Apparently, minikube decided to download and deploy a new preload to my CRIO cluster after a binary upgrade:

```
😄  minikube v1.12.2 on Darwin 10.15.5
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v5-v1.18.3-cri-o-overlay-amd64.tar.lz4: 575.71 MiB /
🔄  Restarting existing docker container for "minikube" ...
❗  Due to issues with CRI-O post v1.17.3, we need to restart your cluster.
❗  See details at https://github.com/kubernetes/minikube/issues/8861
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🌐  Found network options:
    ▪ NO_PROXY=172.17.0.2
🎁  Preparing Kubernetes v1.18.3 on CRI-O 1.17.4 ...
    ▪ env NO_PROXY=172.17.0.2
❌  Unable to load cached images: loading cached images: stat /Users/tstromberg/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v2: no such file or directory
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
```

The error message is repeatable across `minikube start` invocations.

[minikube.tstromberg-macbookpro.tstromberg.log.INFO.20200804-194155.39262.log](https://github.com/kubernetes/minikube/files/5025876/minikube.tstromberg-macbookpro.tstromberg.log.INFO.20200804-194155.39262.log)

**Comment by afbjorklund** [comment]
Same on ubuntu, logs:

```
image.go:168] retrieving image: gcr.io/k8s-minikube/storage-provisioner:v2

image.go:176] daemon lookup for gcr.io/k8s-minikube/storage-provisioner:v2: Error response from daemon: client version 1.41 is too new. Maximum supported API version is 1.40

ssh_runner.go:148] Run: sudo podman image inspect --format {{.Id}} gcr.io/k8s-minikube/storage-provisioner:v2

cache_images.go:105] "gcr.io/k8s-minikube/storage-provisioner:v2" needs transfer: "gcr.io/k8s-minikube/storage-provisioner:v2" does not exist at hash "2d72ece3274d729ef52beecdcb96413dad922adea3e7b17b50371b1c7ca333f8" in container runtime
```

**Comment by afbjorklund** [comment]
Looks like the wrong image went into the preload

```
$ docker images gcr.io/k8s-minikube/storage-provisioner:v2
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
gcr.io/k8s-minikube/storage-provisioner   v2                  2d72ece3274d        7 hours ago         31.6MB
```

This is a problem with floating tags like "v2" (or latest)

**Comment by afbjorklund** [comment]
Note that we get the same image with docker as well:

```
$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ docker images
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
gcr.io/k8s-minikube/storage-provisioner   v2                  9c3ca9f065bb        40 hours ago        32.2MB
```

But there we trust the tag, rather than re-downloading the manifest.

Different code paths: `DigestByDockerLib` vs `DigestByGoLib`

**Comment by afbjorklund** [comment]
@priyawadhwa : After 0538dddd9d8dd19ce4442fecb5bd30c8a1fd0e85, we will overwrite the deployed "v2" with the new images - possibly as part of the release process.

Previously we had "v1.8.1" in deployment/production, and "latest" as the new image (that ended up **never** getting promoted...)

----

Makefile:STORAGE_PROVISIONER_TAG ?= v2

Makefile:MINIKUBE_LDFLAGS := -X k8s.io/minikube/pkg/version.version=$(VERSION) -X k8s.io/minikube/pkg/version.isoVersion=$(ISO_VERSION) -X k8s.io/minikube/pkg/version.isoPath=$(ISO_BUCKET) -X k8s.io/minikube/pkg/version.gitCommitID=$(COMMIT) -X k8s.io/minikube/pkg/version.storageProvisionerVersion=$(STORAGE_PROVISIONER_TAG)

deploy/addons/storage-provisioner/storage-provisioner.yaml.tmpl:    image: {{default "gcr.io/k8s-minikube" .ImageRepository}}/storage-provisioner{{.ExoticArch}}:{{.StorageProvisionerVersion}}

hack/jenkins/release_build_and_upload.sh:echo "Updating Docker images ..."
hack/jenkins/release_build_and_upload.sh-make push-gvisor-addon-image push-storage-provisioner-image

**Comment by afbjorklund** [comment]
Same issue with containerd as well. (anything non-docker)

ssh_runner.go:148] Run: sudo crictl images --output json

```
     {
       "id": "sha256:9c3ca9f065bb1750be59e8f5b5e2f779dc640151d9521fe8e920b95658d05551",
       "repoTags": [
         "gcr.io/k8s-minikube/storage-provisioner:v2"
       ],
       "repoDigests": [
         "gcr.io/k8s-minikube/storage-provisioner@sha256:a7b2848b673e6a0927a16f30445d8f1b66f1504a35def0efa35e3dcac56b713e"
       ],
       "size": "9800722",
       "uid": null,
       "username": ""
     },

```

containerd.go:412] all images are preloaded for containerd runtime.
containerd.go:322] Images already preloaded, skipping extraction

Wonder why this JSON thing didn't kick in for CRI-O as well ?

**Comment by afbjorklund** [comment]
Some kind of bug, when running crictl with crio.sock:

`Run: sudo crictl images --output json`

failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded

`Completed: sudo crictl images --output json: (2.027468702s)`

Apparently we forgot to start the daemon. Podman works, though.

```
● crio.service - Container Runtime Interface for OCI (CRI-O)
   Loaded: loaded (/usr/lib/systemd/system/crio.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://github.com/cri-o/cri-o

```

`ls: cannot access '/var/run/crio/crio.sock': No such file or directory`

`sudo podman images --format json`

**Comment by afbjorklund** [comment]
The root cause why it was only being called for crio, was yet-another-hardcoding:

```go
// ImagesPreloaded returns true if all images have been preloaded
func ImagesPreloaded(containerRuntime string, runner command.Runner, images []string) bool {
        if containerRuntime == "docker" {
                return dockerImagesPreloaded(runner, images)
        }
        if containerRuntime == "containerd" {
                return containerdImagesPreloaded(runner, images)
        }
        return false
}
```

**Comment by afbjorklund** [comment]
There was another bug with the containerd implementation of `ImageExists`.

It was comparing the digest with the id param, so failed to find a match anyway.

```go
        // ImageExists takes image name and image sha checks if an it exists
        ImageExists(string, string) bool
```

This is unfortunately implemented _differently_ for the different container runtimes.

Docker and Podman/CRI-O are using `{{.Id}}`, while containerd uses DIGEST...

The correct format would be `{{.Digest}}` for podman, and `{{..RepoDigests}` for docker. 

But the user of ImageExists is passing the ID (!), in a parameter called "imgDgst". :facepalm: 

So it is all hopelessly confused, as shown by comment "img.ID in as same as image digest"

----

```console
$ docker pull gcr.io/k8s-minikube/storage-provisioner:v2
v2: Pulling from k8s-minikube/storage-provisioner
Digest: sha256:6571b5c2ad066a9a210ba7d0ff4d6e36e48b4004975391ca1900a38517691bbc
Status: Image is up to date for gcr.io/k8s-minikube/storage-provisioner:v2
gcr.io/k8s-minikube/storage-provisioner:v2
$ docker images gcr.io/k8s-minikube/storage-provisioner:v2
REPOSITORY                                TAG                 IMAGE ID            CREATED             SIZE
gcr.io/k8s-minikube/storage-provisioner   v2                  2d72ece3274d        14 hours ago        31.6MB
```

So in this case, the ID is: 2d72ece3274d729ef52beecdcb96413dad922adea3e7b17b50371b1c7ca333f8
and the digest is: sha256:6571b5c2ad066a9a210ba7d0ff4d6e36e48b4004975391ca1900a38517691bbc


```console
$ sudo ctr images pull gcr.io/k8s-minikube/storage-provisioner:v2
gcr.io/k8s-minikube/storage-provisioner:v2:                                       resolved       |++++++++++++++++++++++++++++++++++++++| 
manifest-sha256:6571b5c2ad066a9a210ba7d0ff4d6e36e48b4004975391ca1900a38517691bbc: done           |++++++++++++++++++++++++++++++++++++++| 
layer-sha256:aa7a33f49db55ac76c641450365f092b67c174f40235caf000ad5326fbcc96ca:    done           |++++++++++++++++++++++++++++++++++++++| 
config-sha256:2d72ece3274d729ef52beecdcb96413dad922adea3e7b17b50371b1c7ca333f8:   exists         |++++++++++++++++++++++++++++++++++++++| 
elapsed: 5.4 s                                                                    total:  9.1 Mi (1.7 MiB/s)                                       
unpacking linux/amd64 sha256:6571b5c2ad066a9a210ba7d0ff4d6e36e48b4004975391ca1900a38517691bbc...
done
$ sudo ctr images check
REF                                        TYPE                                                 DIGEST                                                                  STATUS         SIZE            UNPACKED 
gcr.io/k8s-minikube/storage-provisioner:v2 application/vnd.docker.distribution.manifest.v2+json sha256:6571b5c2ad066a9a210ba7d0ff4d6e36e48b4004975391ca1900a38517691bbc complete (2/2) 9.2 MiB/9.2 MiB true
```

**Comment by afbjorklund** [comment]
I removed the hardcoding and added crio, but it is still not really checking the image id/digest.

That is, it only checks the tags (as provided by the caller). Currently hardcoded to `Kubeadm`.

```go
// Kubeadm returns a list of images necessary to bootstrap kubeadm
func Kubeadm(mirror string, version string) ([]string, error)
```

**Comment by afbjorklund** [comment]
When verifying a tag, we have three options:

1) The lazy option (Digest nil)
Just assume that any image with the right tag is the right one

2) The crazy option (DigestByDockerLib)
Query the host docker daemon, using the wrong API version

3) The slow option (DigestByGoLib)
Download the image manifest from the registry, compare digests
