### ISSUE TITLE
Documentation: change registries title from "docker on macOS" to "docker on Linux/macOS"

### ISSUE THREAD

**Issue by andrewinston** [kubernetes/minikube#8925]
Isn't it worth mentioning something about Linux?

I managed to make the private registry work on my Ubuntu 20.04 machine by following the steps listed in "docker on macOS". Maybe it would be interesting to change that title to "Docker on Linux/macOS".

That said, I haven't followed the whole handbook. I just read the "Registries" page.

**Comment by afbjorklund** [comment]
Sounds like a good idea, maybe you can provide a PR ?

**Comment by priyawadhwa** [comment]
If anyone is interested in taking on this documentation PR, please comment here!

**Comment by Evalle** [comment]
I can take care of it 
/assign

**Comment by dominikbraun** [comment]
> Maybe it would be interesting to change that title to "Docker on Linux/macOS".

Unfortunately, this isn't sufficient for documenting the way to work around Docker's TLS requirements, see the code review comments from #9314. I'll have to un-assign me for this because I'm not experienced enough in this topic.

**Comment by Aut0R3V** [comment]
Hey, I went through the discussion in #9314. Should this issue be closed or are there any other changes that can be worked upon?

**Comment by spowelljr** [comment]
The title of this issue is to simply add Linux to the header, but there is different information required between Mac and Linux so just updating the header is not sufficient. For that reason I'm going to close this issue, but feel free to reopen.
