### ISSUE TITLE
Minikube no longer starts after upgrading from v1.12.1 to v1.12.2 on MacOS Catalina

### ISSUE THREAD

**Issue by cakuros** [kubernetes/minikube#8931]
## Background
Minikube fails to start after I upgraded from v1.12.1 to v1.12.2.  Error is consistently reproducible, even after running `brew uninstall minikube` and reinstalling.  I ended up going back to 1.12.1 by running `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/a3ceb128df8e5e1a1d8105a7daf7773a0a0e82ee/Formula/minikube.rb`, with the commit hash corresponding to the v1.12.1 update, which did work properly without any config changes.

**Steps to reproduce the issue:** 
On MacOS Catalina 10.15.6 on Macbook Pro 2019
HW Overview:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,4
  Processor Name:	Quad-Core Intel Core i5
  Processor Speed:	1.4 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB

1. `brew install minikube` (installs minikube v1.12.2)
2. `minikube start`

Go, go-bindata, and kubernetes-cli (the listed dependencies) are all installed via Homebrew and up to date.

**Full output of `minikube start --logtostderr --v=8` command used**
https://gist.github.com/cakuros/cb9c76c25678d743417af62f2cf4219e

**Comment by phaus** [comment]
I was able to fix the issue by deleting the old `~/.minikube` folder. A then tried `minikube start` again.

**Comment by prasadkatti** [comment]
Looks like the kubelet startup times out. Can you share the kubelet logs? There is also a `minikube logs` command. If you can share the output of that here that would be helpful.

**Comment by cakuros** [comment]
Ok, well IDK what was going on, but now it works, so cool I guess?  BTW, `minikube logs` didn't provide anything relevant, it just said there was no local cluster.
