### ISSUE TITLE
Minikube claims it has an existing VM, but doesn't?

### ISSUE THREAD

**Issue by ale8k** [kubernetes/minikube#8946]
I accidentally forgotten to install kubectl on a fresh install of ubuntu 20.04, and just ran minikube start. It automatically picked the 'none' driver, but failed to start due to kubectl missing. As seen in the output below, I'm a little confused as to why it won't start?
I've tried to suggest 'minikube delete', no luck.

**Steps to reproduce the issue:** 

1. Start with none driver before installing kubectl (as it won't start the VM anyway)
2. Install kubectl
3. Use minikube delete
4. Attempt to start with docker driver

**Full output of failed command:** 
```
ale8k@ale8k:/$ minikube start --driver=docker
😄  minikube v1.12.2 on Ubuntu 20.04
💥  The existing "minikube" VM was created using the "none" driver, and is incompatible with the "docker" driver.
👉  To proceed, either:

1) Delete the existing "minikube" cluster using: 'minikube delete'

* or *

2) Start the existing "minikube" cluster using: 'minikube start --driver=none'

💣  Exiting.

---- minikube delete example ----
ale8k@ale8k:/$ minikube delete
🙄  "minikube" profile does not exist, trying anyways.
💀  Removed all traces of the "minikube" cluster.

```

**Optional: Full output of `minikube logs` command:**
<details>

ale8k@ale8k:/$ minikube logs
🤷  There is no local cluster named "minikube"
👉  To fix this, run: "minikube start"

</details>

**Comment by afbjorklund** [comment]
When you write “kubectl”, do you mean docker ? Or why does installing the kubernetes client affect the driver selection ?

**Comment by ale8k** [comment]
> When you write “kubectl”, do you mean docker ? Or why does installing the kubernetes client affect the driver selection ?

It stops the initial running of the vm if you don't have kubectl installed when you attempt to start. Or at least it did on me?

**Comment by afbjorklund** [comment]
If you don't have _any_ of the requirements installed, it is supposed to exit with an error message.

There is no requirement on `kubectl` to run `minikube start`, only to connect to the cluster later on.

**Comment by afbjorklund** [comment]
Seems to exit properly:
```
👎  Unable to pick a default driver. Here is what was considered, in preference order:
    ▪ vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in $PATH
    ▪ docker: Not installed: exec: "docker": executable file not found in $PATH
    ▪ kvm2: Not installed: exec: "virsh": executable file not found in $PATH
    ▪ none: Not installed: exec: "docker": executable file not found in $PATH
    ▪ podman: Not installed: exec: "podman": executable file not found in $PATH
    ▪ virtualbox: Not installed: unable to find VBoxManage in $PATH
👉  Try specifying a --driver, or see https://minikube.sigs.k8s.io/docs/start/
```

**Comment by ale8k** [comment]
Yeah I just tried it on a fresh install and it worked... I'll close this.

**Comment by afbjorklund** [comment]
The "preference order" seems to be made up too, it looks more like "random order":

vmware priority: 6,
docker priority: 8,
kvm2 priority: 7,
none priority: 3,
podman priority: 2,
virtualbox priority: 5,
