### ISSUE TITLE
--exra-config=apiserver does not appear to take effect in latest version

### ISSUE THREAD

**Issue by mallow111** [kubernetes/minikube#8962]
**Steps to reproduce the issue:** 

Try to turn on OIDC flags for minikube, and found out the flags are not taken, can someone help to take a look at please?

I even tried to use --kubernetes-version v1.13.10, it does not work.

minikube stop
minikube delete
and then run minikube start with the flags still not work.

**Full output of `minikube start` command used, if not already included:**
```
 minikube   --extra-config apiserver.Authentication.OIDC.IssuerURL=https://10.0.2.2:8443/auth/realms/master   --extra-config apiserver.Authentication.OIDC.UsernameClaim=sub   --extra-config apiserver.Authentication.OIDC.ClientID=kubernetes-cluster     start
```

minikube ssh "ps -afe | grep apiserver"                
```
9 kube-apiserver --authorization-mode=Node,RBAC --enable-admission-plugins=Initializers,NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota --advertise-address=192.168.99.112 --allow-privileged=true --client-ca-file=/var/lib/minikube/certs/ca.crt --enable-bootstrap-token-auth=true --etcd-cafile=/var/lib/minikube/certs/etcd/ca.crt --etcd-certfile=/var/lib/minikube/certs/apiserver-etcd-client.crt --etcd-keyfile=/var/lib/minikube/certs/apiserver-etcd-client.key --etcd-servers=https://127.0.0.1:2379 --insecure-port=0 --kubelet-client-certificate=/var/lib/minikube/certs/apiserver-kubelet-client.crt --kubelet-client-key=/var/lib/minikube/certs/apiserver-kubelet-client.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --proxy-client-cert-file=/var/lib/minikube/certs/front-proxy-client.crt --proxy-client-key-file=/var/lib/minikube/certs/front-proxy-client.key --requestheader-allowed-names=front-proxy-client --requestheader-client-ca-file=/var/lib/minikube/certs/front-proxy-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=8443 --service-account-key-file=/var/lib/minikube/certs/sa.pub --service-cluster-ip-range=10.96.0.0/12 --tls-cert-file=/var/lib/minikube/certs/apiserver.crt --tls-private-key-file=/var/lib/minikube/certs/apiserver.key

```
</details>
minikube version: v1.12.2

**Comment by priyawadhwa** [comment]
Hey @mallow111 so the --extra-config flag passes in additional flags to whatever resource you specify (in this case, apiserver)

The formatting should look like this:

```
--extra-config = apiserver.oidc-issuer-url=https://10.0.2.2:8443/auth/realms/master
```
since the flag is called `--oidc-issuer-url ` -- [documentation here](https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/)

Does that work?

**Comment by mallow111** [comment]
@priyawadhwa  hi, thanks for the response, no, it did not work, can you guys try the latest version and pass some of the oidc flags since i see other post mentioning that oidc flag with the latest version has issue too. I tested in minikube version 1.7,  it will take the flag and work.

**Comment by priyawadhwa** [comment]
Hey @mallow111 did you try on a brand new cluster? The `--extra-config` flag currently doesn't work on a preexisting cluster: https://github.com/kubernetes/minikube/issues/8661

Could you try upgrading to minikube v1.13.0 and running:
```
minikube delete
minikube start --extra-config apiserver.oidc-issuer-url=https://10.0.2.2:8443/auth/realms/master
```

and let us know if that fixes the issue?

**Comment by mallow111** [comment]
did you run this with docker or vm and what is the k8s version that you are using?

**Comment by priyawadhwa** [comment]
It should work with either docker or VM, so you can try with whichever is better for you. I used the default k8s version minikube is using (I believe it's 1.19)

**Comment by mallow111** [comment]
great, thanks, you can close this ticket now.
