### ISSUE TITLE
hyperv: create host timeout for larger memory sizes

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8965]
in gh aciton test when I increased the memory size for hyperv, the test timed out in Created Host. at 4 minutes
that made me think, in our hyperv driver, we should wait longer for the VM to be created if user wants more memory.

here is the data, and also the slowjam stacklog in the end
```
-------
PS C:\Windows\system32> Measure-Command { minikube start --driver=hyperv --memory=2200MB }
TotalMinutes      : 1.47394533166667                                                                                                                                                                                      
TotalSeconds      : 88.4367199                                                                                                                                                                                               


--------
PS C:\Windows\system32> Measure-Command { minikube start --driver=hyperv --memory=4400MB }
TotalMinutes      : 1.510028885
TotalSeconds      : 90.6017331


-----------

PS C:\Windows\system32> Measure-Command { minikube start --driver=hyperv --memory=6400MB }
TotalMinutes      : 1.53193910666667
TotalSeconds      : 91.9163464


------------

PS C:\Windows\system32> Measure-Command { minikube start --driver=hyperv --memory=8000MB }
TotalMinutes      : 1.506590405
TotalSeconds      : 90.3954243
--------
PS C:\Windows\system32> Measure-Command { minikube start --driver=hyperv --memory=12000MB }
TotalMinutes      : 1.62044865833333
TotalSeconds      : 97.2269195
--------
````

I attach 3 Stacklogs to be analyzed by slowjam
[minikube_stack_2200MB.log](https://github.com/kubernetes/minikube/files/5054718/minikube_stack_2200MB.log)
[minikube_stack_4400MB.log](https://github.com/kubernetes/minikube/files/5054719/minikube_stack_4400MB.log)
[minikube_stack_12000MB.log](https://github.com/kubernetes/minikube/files/5054720/minikube_stack_12000MB.log)

**Comment by medyagh** [comment]
slow jam analysis shows for 2200mb timeCreateHost takes 45s
for 4400mb it takes 47 seconds
for 12000mb takes 50 seconds

**Comment by tstromberg** [comment]
Can you provide the output of `minikube start --alsologtostderr -v=1`?

Anyways, it seems like the 4 minute timeout may be too short.

**Comment by tstromberg** [comment]
Closing as stale.
