### ISSUE TITLE
Support using kubenet as network plugin

### ISSUE THREAD

**Issue by yujuhong** [kubernetes/minikube#897]
When running minikube with --network-plugin=kubenet, the node will never be ready because podCIDR will not be assigned by the node controller. 

/cc @freehan

**Comment by r2d4** [comment]
Seems like we can allocate podCIDR manually here where we set up the kubelet.

https://github.com/kubernetes/minikube/blob/k8s-v1.5/pkg/localkube/kubelet.go#L28

https://github.com/kubernetes/kubernetes/blob/ca049360e27a324b4004cc5ea111fef5430299eb/cmd/kubelet/app/options/options.go#L217

**Comment by yujuhong** [comment]
Hm...I can also set this manually by using `--extra-config=kubelet.PodCIDR=10.180.1.0/24`, so it works after all.

**Comment by r2d4** [comment]
Does it make sense to set it every time to the full CIDR?

**Comment by freehan** [comment]
kubelet.PodCIDR only matters to `kubenet` and `cni` network plugin. It is not used when using `noop` network plugin. We can always set it. But there will be noise when you look at the node spec and the podcidr is there, but not used.

**Comment by dlorenc** [comment]
This should be fixed.
