### ISSUE TITLE
--apiserver-names does not work as expected when you run minikube start a second time

### ISSUE THREAD

**Issue by jemygraw** [kubernetes/minikube#8990]
Related issue: https://github.com/kubernetes/minikube/issues/8658

**Steps to reproduce the issue:** 

1. minikube start --apiserver-names=k8s-beta.example.com --apiserver-names=k8s-prod-replica.example.com

Version:

```
appdelivery@appdelivery-qvm-1:~$ minikube version
minikube version: v1.12.1
commit: 997fd89b9d3a0072e3112c79d906b6367e760473-dirty
```

Details:  it is right when you first run the minikube start command, and when you re-run the minikube start with the same flags, it is wrong. So if you just run a new minikube, you will not reproduce it. I found the code which cause this error:

**First Run**
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start_flags.go#L162

```
startCmd.Flags().StringArrayVar(&apiServerNames, "apiserver-names", nil, "A set of apiserver names which are used in the generated certificate for kubernetes.  This can be used if you want to make the apiserver available from outside the machine")
```

**Second Run**
https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start_flags.go#L539

```
cc.KubernetesConfig.APIServerNames = viper.GetStringSlice("apiserver-names")
```

Because the apiserverNames is first get by `StringArrayVar` which support the above format of `--apiserver-names=k8s-beta.example.com --apiserver-names=k8s-prod-replica.example.com` to specify multiple values for a single flag, but when you re-run minikue, it will use `viper.GetStringSlice` to get the values from the command line flags.`viper.GetStringSlice` supports the format of `--apiserver-names=k8s-beta.example.com,k8s-prod-replica.example.com`. 

So when you output the values of the above code, it will output:

```
I0813 14:45:12.401533   90740 start_flags.go:539] existing: {v1.18.3 minikube minikubeCA [k8s-beta.duokexuetang.com k8s-prod-replica.duokexuetang.com] [] cluster.local docker    10.96.0.0/12    [] true false   8443 }
I0813 14:45:12.401574   90740 start_flags.go:540] viper: [[k8s-beta.duokexuetang.com,k8s-prod-replica.duokexuetang.com]]
```
---
 I write a simple program to express what happens.

```
package main

import (
	"encoding/json"
	"fmt"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
)

var apiserverNames []string

type ClusterConfig struct {
	KubernetesConfig KubernetesConfig
}

type KubernetesConfig struct {
	APIServerNames []string
}

var startCmd = cobra.Command{
	Use: "start",
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("apiserverNames=", viper.GetStringSlice("apiserver-names"))
		kubeConfig := KubernetesConfig{
			APIServerNames: apiserverNames,
		}
		clusterConfig := ClusterConfig{
			KubernetesConfig: kubeConfig,
		}
		data, _ := json.MarshalIndent(&clusterConfig, "", "    ")
		fmt.Println("Output=", string(data))
	},
}

func init() {
	startCmd.PersistentFlags().StringArrayVar(&apiserverNames, "apiserver-names", nil, "apiserver names")
	viper.BindPFlags(startCmd.PersistentFlags())
}

func main() {
	rootCmd := cobra.Command{}
	rootCmd.AddCommand(&startCmd)
	fmt.Println(rootCmd.Execute())
}
```

Output:

```
apiserverNames= [[hello,world]]
Output= {
    "KubernetesConfig": {
        "APIServerNames": [
            "hello",
            "world"
        ]
    }
}
```

**Comment by priyawadhwa** [comment]
Hey @jemygraw thanks for opening an issue for this bug. If you, or anyone else, would be interested in fixing this bug, feel free to assign yourself to this issue by commenting /assign.
