### ISSUE TITLE
How to attach new disk to Minikube in Virtualbox?

### ISSUE THREAD

**Issue by Jimmyjim123** [kubernetes/minikube#8994]
**Steps to reproduce the issue:** 

*Note im using Virtualbox

1.  minikube start --driver=virtualbox --cpus=4 --memory=6g --disk-size='30g' --network-plugin=cni --enable-default-cni --container-runtime=cri-o --addons=default-storageclass ingress

2.  Power off Minikube

3. Go to settings > storage and add harddrive.

4. Run the start command from step again.

How do i mount this new hard disk to minikube? is there a command that does this?

**Comment by afbjorklund** [comment]
There is no built-in minikube feature to add extra disks (unfortunately).

But you can do it manually, using the `mount` command.
(you would also need to create a mountpoint and format it)

To mount it on boot, you can use `/var/lib/boot2docker/bootlocal.sh`

**Comment by tstromberg** [comment]
There is no command to add or remove storage to minikube, nor is it something we should probably support.
