### ISSUE TITLE
gcp-auth plugin should support image pulls from gcr.io

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#9002]
As reported in #Slack and seen within two friction logs.

**Comment by tstromberg** [comment]
@sharifelgamal - any news?

**Comment by sharifelgamal** [comment]
I'll start working on this soon.

**Comment by medyagh** [comment]
lets check if this is covered by registry-creds  addon

**Comment by mcortinas** [comment]
:eye:

**Comment by medyagh** [comment]
this issue is still on our radar, we hope to deliver this in the beginning of  second quarter
