### ISSUE TITLE
nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v2

### ISSUE THREAD

**Issue by yingfengxiaowangzi** [kubernetes/minikube#9005]
**重现问题所需的命令**：
minikube start --vm-driver=virtualbox --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers
**失败的命令的完整输出**：<details>
😄  minikube v1.12.3 on Darwin 10.15.5
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running virtualbox "minikube" VM ...
E0815 07:42:42.159096   23661 cache.go:63] save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v2" -> "/Users/yishuangshuang/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner_v2" failed: nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v2: GET https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/storage-provisioner/manifests/v2: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v2]
E0815 07:42:43.072888   23661 cache.go:190] Error caching images:  Caching images for kubeadm: caching images: caching image "/Users/yishuangshuang/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner_v2": nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v2: GET https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/storage-provisioner/manifests/v2: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v2]
E0815 07:42:44.206292   23661 cache.go:63] save image to file "registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v2" -> "/Users/yishuangshuang/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner_v2" failed: nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v2: GET https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/storage-provisioner/manifests/v2: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v2]

💣  Failed to cache images: Caching images for kubeadm: caching images: caching image "/Users/yishuangshuang/.minikube/cache/images/registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner_v2": nil image for registry.cn-hangzhou.aliyuncs.com/google_containers/storage-provisioner:v2: GET https://registry.cn-hangzhou.aliyuncs.com/v2/google_containers/storage-provisioner/manifests/v2: MANIFEST_UNKNOWN: manifest unknown; map[Tag:v2]

</details>

**`minikube logs`命令的输出**： <details>

==> Docker <==
-- Logs begin at Fri 2020-08-14 23:00:15 UTC, end at Fri 2020-08-14 23:48:48 UTC. --
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.621752280Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.621895900Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.622176596Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.622690576Z" level=info msg="skip loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.623105794Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.623251308Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.623320440Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.19.114\n": exit status 1"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.623409975Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.626878314Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.626978826Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627096483Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627250299Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627311519Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627369174Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627416845Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627463444Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627580411Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627641386Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627813775Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.627948470Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628323780Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628391238Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628509409Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628569240Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628615635Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628659367Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628707588Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628752780Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628801272Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628845770Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628895712Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.628979868Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.629031319Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.629076431Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.629119097Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.629283946Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.629366908Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.629418894Z" level=info msg="containerd successfully booted in 0.010473s"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.636207372Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.636346798Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.636493767Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.636556876Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.637327682Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.637354203Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.637369479Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.637378090Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.674906863Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.674955932Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.674964766Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.674970858Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.674976890Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.675022606Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.675213595Z" level=info msg="Loading containers: start."
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.798334643Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.863702921Z" level=info msg="Loading containers: done."
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.895470473Z" level=info msg="Docker daemon" commit=48a66213fe graphdriver(s)=overlay2 version=19.03.12
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.895669247Z" level=info msg="Daemon has completed initialization"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.912890122Z" level=info msg="API listen on /var/run/docker.sock"
Aug 14 23:00:28 minikube dockerd[2393]: time="2020-08-14T23:00:28.913078215Z" level=info msg="API listen on [::]:2376"
Aug 14 23:00:28 minikube systemd[1]: Started Docker Application Container Engine.

==> container status <==
time="2020-08-14T23:48:51Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> describe nodes <==
E0815 07:48:51.041471   23774 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: /var/lib/minikube/binaries/v1.18.3/kubectl: command not found
 output: "\n** stderr ** \nsudo: /var/lib/minikube/binaries/v1.18.3/kubectl: command not found\n\n** /stderr **"

==> dmesg <==
[  +5.002885] hpet1: lost 319 rtc interrupts
[  +5.009382] hpet1: lost 318 rtc interrupts
[Aug14 23:44] hpet1: lost 320 rtc interrupts
[  +5.009648] hpet1: lost 320 rtc interrupts
[  +5.007119] hpet1: lost 318 rtc interrupts
[  +5.005383] hpet1: lost 318 rtc interrupts
[  +5.007780] hpet1: lost 319 rtc interrupts
[  +5.008912] hpet1: lost 320 rtc interrupts
[  +5.009586] hpet1: lost 318 rtc interrupts
[  +5.012028] hpet1: lost 320 rtc interrupts
[  +5.014122] hpet1: lost 320 rtc interrupts
[  +5.009750] hpet1: lost 318 rtc interrupts
[  +5.009514] hpet1: lost 319 rtc interrupts
[  +5.008923] hpet1: lost 320 rtc interrupts
[Aug14 23:45] hpet1: lost 318 rtc interrupts
[  +5.007257] hpet1: lost 320 rtc interrupts
[  +5.008446] hpet1: lost 318 rtc interrupts
[  +5.005718] hpet1: lost 319 rtc interrupts
[  +5.014768] hpet1: lost 319 rtc interrupts
[  +5.008761] hpet1: lost 319 rtc interrupts
[  +5.009288] hpet1: lost 319 rtc interrupts
[  +5.004966] hpet1: lost 318 rtc interrupts
[  +5.005044] hpet1: lost 319 rtc interrupts
[  +5.010930] hpet1: lost 320 rtc interrupts
[  +5.002809] hpet1: lost 319 rtc interrupts
[  +5.010894] hpet1: lost 320 rtc interrupts
[Aug14 23:46] hpet1: lost 320 rtc interrupts
[  +5.003102] hpet1: lost 318 rtc interrupts
[  +5.005659] hpet1: lost 319 rtc interrupts
[  +5.004044] hpet1: lost 320 rtc interrupts
[  +5.003019] hpet1: lost 318 rtc interrupts
[  +5.003779] hpet1: lost 319 rtc interrupts
[  +5.005989] hpet1: lost 319 rtc interrupts
[  +5.001762] hpet1: lost 320 rtc interrupts
[  +5.005485] hpet1: lost 319 rtc interrupts
[  +5.001879] hpet1: lost 319 rtc interrupts
[  +5.006943] hpet1: lost 319 rtc interrupts
[  +5.004592] hpet1: lost 319 rtc interrupts
[Aug14 23:47] hpet1: lost 318 rtc interrupts
[  +5.007670] hpet1: lost 320 rtc interrupts
[  +5.010101] hpet1: lost 320 rtc interrupts
[  +5.003957] hpet1: lost 319 rtc interrupts
[  +5.009903] hpet1: lost 318 rtc interrupts
[  +5.008958] hpet1: lost 320 rtc interrupts
[  +5.010629] hpet1: lost 319 rtc interrupts
[  +5.009359] hpet1: lost 319 rtc interrupts
[  +5.012059] hpet1: lost 320 rtc interrupts
[  +5.009602] hpet1: lost 320 rtc interrupts
[  +5.007881] hpet1: lost 318 rtc interrupts
[  +5.012182] hpet1: lost 319 rtc interrupts
[Aug14 23:48] hpet1: lost 319 rtc interrupts
[  +5.010951] hpet1: lost 319 rtc interrupts
[  +5.005130] hpet1: lost 319 rtc interrupts
[  +5.007609] hpet1: lost 318 rtc interrupts
[  +5.007959] hpet1: lost 320 rtc interrupts
[  +5.008088] hpet1: lost 319 rtc interrupts
[  +5.011145] hpet1: lost 319 rtc interrupts
[  +5.006217] hpet1: lost 319 rtc interrupts
[  +5.005954] hpet1: lost 319 rtc interrupts
[  +5.002900] hpet1: lost 318 rtc interrupts

==> kernel <==
 23:48:52 up 48 min,  0 users,  load average: 0.00, 0.00, 0.00
Linux minikube 4.19.114 #1 SMP Mon Aug 3 12:35:22 PDT 2020 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2019.02.11"

==> kubelet <==
-- Logs begin at Fri 2020-08-14 23:00:15 UTC, end at Fri 2020-08-14 23:48:52 UTC. --
-- No entries --

❗  unable to fetch logs for: describe nodes

</details>

**使用的操作系统版本**：
macOS 10.15.5 (19F101)

**Comment by east4ming** [comment]
遇到同样的问题, 是不是阿里的镜像库还没同步这个镜像? storage-provisioner:v2 请问 有临时解决办法么?

**Comment by yingfengxiaowangzi** [comment]
> 遇到同样的问题, 是不是阿里的镜像库还没同步这个镜像? storage-provisioner:v2 请问 有临时解决办法么?

还没解决，没时间搞了；周末再看一下

**Comment by priyawadhwa** [comment]
你好 @yingfengxiaowangzi @east4ming 
您能解决这个问题吗？

Hey @yingfengxiaowangzi @east4ming 
Were you able to fix this?

**Comment by medyagh** [comment]
@yingfengxiaowangzi @east4ming do you still have this issue ?
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by medyagh** [comment]
@yingfengxiaowangzi 

Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!
