### ISSUE TITLE
wsl2: Error creating profile directory: mkdir $HOME/.minikube: permission denied

### ISSUE THREAD

**Issue by Internauta1972** [kubernetes/minikube#9006]
I'm trying to start minikube under virtualbox on Ubuntu 18.04 and I always get the same error:

`manuel1972@Dell:~$ minikube start --driver virtualbox
E0815 15:40:05.278085    6733 cloud_events.go:50] Error creating profile directory: mkdir /home/manuel1972/.minikube/profiles/minikube: permission denied
😄  minikube v1.12.3 on Ubuntu 18.04
❗  Both driver=virtualbox and vm-driver=kvm2 have been set.

    Since vm-driver is deprecated, minikube will default to driver=virtualbox.

    If vm-driver is set in the global config, please run "minikube config unset vm-driver" to resolve this warning.

✨  Using the virtualbox driver based on user configuration
💿  Downloading VM boot image ...
    > minikube-v1.12.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
E0815 15:40:05.607441    6733 iso.go:86] Unable to download https://storage.googleapis.com/minikube/iso/minikube-v1.12.2.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.12.2.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.12.2.iso.sha256 Dst:/home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download Pwd: Mode:2 Detectors:[0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0] Decompressors:map[bz2:0x2d1e7e0 gz:0x2d1e7e0 tar.bz2:0x2d1e7e0 tar.gz:0x2d1e7e0 tar.xz:0x2d1e7e0 tbz2:0x2d1e7e0 tgz:0x2d1e7e0 txz:0x2d1e7e0 xz:0x2d1e7e0 zip:0x2d1e7e0] Getters:map[file:0xc000cd2780 http:0xc000cce680 https:0xc000cce6a0] Dir:false ProgressListener:0x2ce8d80 Options:[0xc7ef40]}: open /home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download: permission denied
💿  Downloading VM boot image ...
    > minikube-v1.12.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
E0815 15:40:07.464831    6733 iso.go:86] Unable to download https://github.com/kubernetes/minikube/releases/download/v1.12.2/minikube-v1.12.2.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.12.2/minikube-v1.12.2.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.12.2/minikube-v1.12.2.iso.sha256 Dst:/home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download Pwd: Mode:2 Detectors:[0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0] Decompressors:map[bz2:0x2d1e7e0 gz:0x2d1e7e0 tar.bz2:0x2d1e7e0 tar.gz:0x2d1e7e0 tar.xz:0x2d1e7e0 tbz2:0x2d1e7e0 tgz:0x2d1e7e0 txz:0x2d1e7e0 xz:0x2d1e7e0 zip:0x2d1e7e0] Getters:map[file:0xc000d6b600 http:0xc000d526a0 https:0xc000d526c0] Dir:false ProgressListener:0x2ce8d80 Options:[0xc7ef40]}: open /home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download: permission denied
💿  Downloading VM boot image ...
    > minikube-v1.12.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
E0815 15:40:13.984238    6733 iso.go:86] Unable to download https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.12.2.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.12.2.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.12.2.iso.sha256 Dst:/home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download Pwd: Mode:2 Detectors:[0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0] Decompressors:map[bz2:0x2d1e7e0 gz:0x2d1e7e0 tar.bz2:0x2d1e7e0 tar.gz:0x2d1e7e0 tar.xz:0x2d1e7e0 tbz2:0x2d1e7e0 tgz:0x2d1e7e0 txz:0x2d1e7e0 xz:0x2d1e7e0 zip:0x2d1e7e0] Getters:map[file:0xc000640390 http:0xc000a285a0 https:0xc000a285c0] Dir:false ProgressListener:0x2ce8d80 Options:[0xc7ef40]}: open /home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download: permission denied

💣  error provisioning host: Failed to cache ISO: unable to cache ISO:
  https://storage.googleapis.com/minikube/iso/minikube-v1.12.2.iso: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/minikube/iso/minikube-v1.12.2.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.12.2.iso.sha256 Dst:/home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download Pwd: Mode:2 Detectors:[0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0] Decompressors:map[bz2:0x2d1e7e0 gz:0x2d1e7e0 tar.bz2:0x2d1e7e0 tar.gz:0x2d1e7e0 tar.xz:0x2d1e7e0 tbz2:0x2d1e7e0 tgz:0x2d1e7e0 txz:0x2d1e7e0 xz:0x2d1e7e0 zip:0x2d1e7e0] Getters:map[file:0xc000cd2780 http:0xc000cce680 https:0xc000cce6a0] Dir:false ProgressListener:0x2ce8d80 Options:[0xc7ef40]}: open /home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download: permission denied
  https://github.com/kubernetes/minikube/releases/download/v1.12.2/minikube-v1.12.2.iso: getter: &{Ctx:context.Background Src:https://github.com/kubernetes/minikube/releases/download/v1.12.2/minikube-v1.12.2.iso?checksum=file:https://github.com/kubernetes/minikube/releases/download/v1.12.2/minikube-v1.12.2.iso.sha256 Dst:/home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download Pwd: Mode:2 Detectors:[0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0] Decompressors:map[bz2:0x2d1e7e0 gz:0x2d1e7e0 tar.bz2:0x2d1e7e0 tar.gz:0x2d1e7e0 tar.xz:0x2d1e7e0 tbz2:0x2d1e7e0 tgz:0x2d1e7e0 txz:0x2d1e7e0 xz:0x2d1e7e0 zip:0x2d1e7e0] Getters:map[file:0xc000d6b600 http:0xc000d526a0 https:0xc000d526c0] Dir:false ProgressListener:0x2ce8d80 Options:[0xc7ef40]}: open /home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download: permission denied
  https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.12.2.iso: getter: &{Ctx:context.Background Src:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.12.2.iso?checksum=file:https://kubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.12.2.iso.sha256 Dst:/home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download Pwd: Mode:2 Detectors:[0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0 0x2d1e7e0] Decompressors:map[bz2:0x2d1e7e0 gz:0x2d1e7e0 tar.bz2:0x2d1e7e0 tar.gz:0x2d1e7e0 tar.xz:0x2d1e7e0 tbz2:0x2d1e7e0 tgz:0x2d1e7e0 txz:0x2d1e7e0 xz:0x2d1e7e0 zip:0x2d1e7e0] Getters:map[file:0xc000640390 http:0xc000a285a0 https:0xc000a285c0] Dir:false ProgressListener:0x2ce8d80 Options:[0xc7ef40]}: open /home/manuel1972/.minikube/cache/iso/minikube-v1.12.2.iso.download: permission denied

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose`
How can I fix this issue?. Thanks

**Comment by tstromberg** [comment]
Try: `sudo chown -R manuel1972 /home/manuel1972/.minikube/`

This should allow you to get passed this permissions issue. Please let me know if it does not.

That said, I do not know if `kvm2` or `virtualbox` are supported in WSL2. You may have better luck using `minikube start --driver=docker`.

**Comment by medyagh** [comment]
@Internauta1972  did that answer your question ? , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
