### ISSUE TITLE
Add support for qemu:///session (currrent error: no network with matching name 'default')

### ISSUE THREAD

**Issue by BobyMCbobs** [kubernetes/minikube#9009]
# Goal
Support QEMU/KVM User Session as a backend, to enable a rootless Minikube.

QEMU/KVM is already supported, but User Session isn't.  
Since QEMU/KVM User Session doesn't require root, this would be the simplest solution for a local rootless cluster.

**Comment by tstromberg** [comment]
I haven't tested it, but what happens today when you pass `--kvm-qemu-uri=qemu:///session` to `minikube start`?

**Comment by afbjorklund** [comment]
We decided **not** to support this, because of the issues with creating the networking as user: ~#4288~

Rootless support will be a separate epic feature in minikube, for now it _requires_ root / admin privileges.

**Comment by fabquenneville** [comment]
Tryed that and thats what I get...

`xxx@desktop:~$ minikube start --kvm-qemu-uri=qemu:///session
Error: unknown flag: --kvm-qemu-uri
`

**Comment by priyawadhwa** [comment]
@fabquenneville what version of minikube are you using? I'd recommend upgrading to v1.14.0.

```
$ minikube version
minikube version: v1.14.0
$ minikube start -h | grep qemu
      --kvm-qemu-uri='qemu:///system': The KVM QEMU connection URI. (kvm2 driver only)
```

**Comment by fabquenneville** [comment]
Sorry stopped experimenting with minikube since.

**Comment by BobyMCbobs** [comment]
This feature would still be useful, particularly for on-boarding.
Some OSes come pre-installed with libvirtd and qemu-*, such as Fedora, so all folks'd need to do is download Minikube.

/remove-lifecycle stale

**Comment by afbjorklund** [comment]
> This feature would still be useful, particularly for on-boarding.
> Some OSes come pre-installed with libvirtd and qemu-*, such as Fedora, so all folks'd need to do is download Minikube.

They can still do that, they just have to be part of the "libvirt" group.

https://docs.fedoraproject.org/en-US/quick-docs/getting-started-with-virtualization/
https://fedoramagazine.org/full-virtualization-system-on-fedora-workstation-30/

Similar to how you configure Docker ? (we use `sudo` for Podman)

**Comment by andriyDev** [comment]
Closing as this has been decided not to be supported (and as @afbjorklund said, this can be managed).

**Comment by ivanov17** [comment]
Hello team! Can I just use another network with some other name? Or is the network name hardcoded?

**Comment by ivanov17** [comment]
@afbjorklund A thousand apologies and many thanks!
