### ISSUE TITLE
minikube start --memory flag is broken in v1.12.3

### ISSUE THREAD

**Issue by mangoleaf** [kubernetes/minikube#9017]
**Steps to reproduce the issue:** 

Run a command which sets a custom memory amount for the cluster with minikube start

minikube start --driver=virtualbox --cpus=6 --memory=15g --disk-size=50g

**Full output of failed command:** 

😄  minikube v1.12.3 on Fedora 32
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=6, Memory=6000MB, Disk=51200MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.12 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

<details>
The memory flag in minikube start is ignored and defaults to 6gb. Note the Memory=6000MB in the command output. This command worked as expected in v1.12.0. I recently updated to v1.12.3

Note: I also tried --memory='15g' and obtained the same output.
</details>

**Comment by vixus0** [comment]
Experiencing the same issue. For me, it defaults to 3900MB.
