### ISSUE TITLE
driver=none sets --extra-config=kubelet.resolv-conf for incorrect path in Ubuntu 16.04

### ISSUE THREAD

**Issue by anencore94** [kubernetes/minikube#9031]
**Steps to reproduce the issue:** 

1. `minikube --vm-driver=none start`  on Ubuntu 16.04
2. then coredns pod's status become CrashLoopBackOff as in #3511

**Full output of failed command:** 

Since there isn't any file `/run/systemd/resolve/resolv.conf` in Ubuntu 16.04, The auto-setting `--extra-config=kubelet.resolv-conf=/run/systemd/resolve/resolv.conf` doesn't work.
- https://github.com/kubernetes/minikube/blob/master/pkg/minikube/driver/driver.go#L207

```
# ls /run/systemd/resolve/resolv.conf
ls: cannot access '/run/systemd/resolve/resolv.conf': No such file or directory

# ls -l /etc/resolv.conf
lrwxrwxrwx 1 root root 29  8월 12  2019 /etc/resolv.conf -> ../run/resolvconf/resolv.conf
```

So different from `minikube start` on Ubuntu 18.04, the stdout of `minikube start` on Ubuntu 16.04 doesn't have following line:
▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf

**How to fix it in Ubuntu 16.04:** 
By https://stackoverflow.com/questions/53075796/coredns-pods-have-crashloopbackoff-or-error-state/53414041#53414041

Following solution works also on Ubuntu 16.04:
Hacky solution: Disable the CoreDNS loop detection
```
Edit the CoreDNS configmap:

kubectl -n kube-system edit configmap coredns
Remove or comment out the line with loop, save and exit.

Then remove the CoreDNS pods, so new ones can be created with new config:

kubectl -n kube-system delete pod -l k8s-app=kube-dns
```

**Other trial in Ubuntu 16.04:.**
I've tried minikube start with `--extra-config=kubelet.resolv-conf=/run/resolvconf/resolv.conf` option, But it doesn't work as I expected. The coredns pod also become CrashLoopBackOff. I have no idea why this happens.

**Comment by tstromberg** [comment]
I didn't think this flag was required for Ubuntu 16.04. What happens if you run `--extra-config=kubelet.resolv-conf=/etc/resolv.conf`?

**Comment by anencore94** [comment]
@tstromberg The same issue happen with `--extra-config=kubelet.resolv-conf=/etc/resolv.conf`.

coredns pod became crashloopbackoff by loop plugin

**Comment by xieydd** [comment]
same error

**Comment by medyagh** [comment]
@xieydd is your error also on ubuntu 16.04 ?

@anencore94 does this happen only on ubuntu 16.04 and not ubuntu 18.04 or newer?

**Comment by medyagh** [comment]
@anencore94 I am curious is there a reason you are not using our Docker driver instead of none ?
none is not our preferred driver 
/triage needs-information
/triage support

**Comment by anencore94** [comment]
@medyagh  Yeap It only happens on 16.04.
Since the path was right on 18.04

I've been using nvdia-docker to use gpu with minikube. With your official docs, only kvm2 and none driver supports gpu. Also, none driver setting was easier than kvm2 driver, so i choose to use none driver.

**Comment by xieydd** [comment]
@medyagh Yep, i use ubuntu 16.04, and i have same purpose as @anencore94 , use minikube and gpu-device-plugin.

**Comment by priyawadhwa** [comment]
Hey @anencore94 I just wanted to confirm that you ran `--extra-config` on a brand new cluster? That flag doesn't work on pre-existing clusters (that issue can be tracked here https://github.com/kubernetes/minikube/issues/8661)

To make sure it worked, could you run:

```
minikube delete
minikube start --extra-config=kubelet.resolv-conf=/etc/resolv.conf
```

and let us know if that fixes the issue?

**Comment by anencore94** [comment]
@priyawadhwa Thanks for checking. But I did this on a brand-new cluster.
I think it is not the same reason with #8661.

Since with log, I can see `minikube start --extra-config=kubelet.resolv-conf=/etc/resolv.conf` sets such extra-config successfully. But CrashLoopBackOff happens.

**Comment by medyagh** [comment]
@anencore94 do you still have this issue ?

do you mind sharing the logs for the crash that you see ?

**Comment by anencore94** [comment]
@medyagh Sry.. I just changed my os to Ubuntu 20.04 now.
When I have some chance to work on Ubuntu 16.04, I'll test again and share log here.
Thanks.
