### ISSUE TITLE
Version compatible issue in kubeflow-kale

### ISSUE THREAD

**Issue by vigneshsolution** [kubernetes/minikube#9038]
Hi ,

I'm new to kubeflow so looking for support to deploy KALE in kubeflow.
I'm referring this link "https://github.com/kubeflow-kale/kale/blob/master/docker/jupyterlab/Dockerfile.rok" to deploy kubeflow+kale environment but facing below issues.

I'm creating an image in docker.

Attached the screenshot below.

@StefanoFioravanzo Can you guide me to fix this issue.
[kale error.docx](https://github.com/kubernetes/minikube/files/5100538/kale.error.docx)

**Comment by tstromberg** [comment]
For kubeflow support, please see: https://github.com/kubeflow/kubeflow - thanks!
