### ISSUE TITLE
error provisioning host: Hyper-V PowerShell Module is not available

### ISSUE THREAD

**Issue by khsabhishek** [kubernetes/minikube#9040]
C:\Users\khsab>minikube start --driver=hyperv
* minikube v1.12.3 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the hyperv driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.12.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.12.2.iso: 173.73 MiB / 173.73 MiB  100.00% 2.41 MiB p/s 1m12s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v5-v1.18.3-docker-overlay2-amd64.tar.lz4: 510.91 MiB
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create: precreate: Hyper-V PowerShell Module is not available
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start hyperv VM. "minikube start" may fix it: creating host: create: precreate: Hyper-V PowerShell Module is not available
*
X error provisioning host: Failed to start host: creating host: create: precreate: Hyper-V PowerShell Module is not available
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment]
Could you please test to see if this command fixes your problem:

`Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-All`

Then run:

`minikube start --driver=hyperv -v=1 --alsologtostderr`

The additional logging here will help us to see what the underlying command line is that docker-machine is attempting to execute. I found some related issues here:

* https://www.altaro.com/hyper-v/install-hyper-v-powershell-module/
* https://forums.docker.com/t/hyper-v-powershell-module-not-installed/12675
* https://stackoverflow.com/questions/49421953/docker-machine-error-hyper-v-powershell-module-is-not-available

**Comment by medyagh** [comment]
@khsabhishek are you sure your windows supports virtualization ?

**Comment by rajurh** [comment]
@medyagh Yes it supports and was working before not sure all of a sudden its broken. I have provided my screenshots above.

**Comment by medyagh** [comment]
@rajurh do you mind trying to crate a VM manuallly using hyper-v manager to see if it allows you ?

yet I would like minikube to provide a better error. 
do you mind also sharing the output of the commands that enable HyperV ?

https://minikube.sigs.k8s.io/docs/drivers/hyperv/


also if you install docker, you can user our newest driver, docker driver.

minikube delete --all
minikube start --driver=docker

**Comment by rajurh** [comment]
@medyagh  No luck, with docker driver we have limitations like ingress controller addons, etc.

**Comment by medyagh** [comment]
@rajurh I wonder if you still have this issue, to me it sounds like there is something about your hyperv installation,

do you mind sharing your hperv virtual switch by clicking on the hyperv manager ? and see if you can create a new virtual switch and pass it to minikube using the flag

```
 --hyperv-virtual-switch='': The hyperv virtual switch name. Defaults to first found. (hyperv driver only)
```

**Comment by rajurh** [comment]
@medyagh Thanks for checking - Yes issue still exists. I tried creating a new switch as shown in the below screenshot and referencing in minikube command no luck still the same error

![image](https://user-images.githubusercontent.com/15551296/97495158-33eb1800-19cc-11eb-9bd0-35dd9ebf535e.png)

![image](https://user-images.githubusercontent.com/15551296/97495381-6eed4b80-19cc-11eb-999b-70e15f843ca7.png)

**Comment by medyagh** [comment]
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by medyagh** [comment]
the error message seems to be hyperv not configured correctly.

**Comment by medyagh** [comment]
@khsabhishek do you have this problem, I wonder if you have tried our docker driver?
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by medyagh** [comment]
Regrettably @khsabhishek , there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

**Comment by sweet-aus** [comment]
minikube start
minikube is local Kubernetes, focusing on making it easy to learn and develop for Kubernetes.

All you need is Docker (or similarly compatible) container or a Virtual Machine environment, and Kubernetes is a single command away: minikube start

Installing...

😄  minikube v1.25.2 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
✨  Automatically selected the hyperv driver
💿  Downloading VM boot image ...
    > minikube-v1.25.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.25.2.iso: 237.06 MiB / 237.06 MiB [] 100.00% 8.65 MiB p/s 28s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.23.3 preload ...
    > preloaded-images-k8s-v17-v1...: 505.68 MiB / 505.68 MiB  100.00% 9.85 MiB
🔥  Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🤦  StartHost failed, but will try again: creating host: create: precreate: Hyper-V PowerShell Module is not available
🔥  Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start hyperv VM. Running "minikube delete" may fix it: creating host: create: precreate: Hyper-V PowerShell Module is not available

❌  Exiting due to PR_HYPERV_MODULE_NOT_INSTALLED: Failed to start host: creating host: create: precreate: Hyper-V PowerShell Module is not available
💡  Suggestion: Run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Tools-All'
📘  Documentation: https://www.altaro.com/hyper-v/install-hyper-v-powershell-module/
🍿  Related issue: https://github.com/kubernetes/minikube/issues/9040

**Comment by hrshlmeht** [comment]
How do I check whether my Hyper-V is working properly or not?

**Comment by hrshlmeht** [comment]
I am getting the exact same error while installing creating a minikube also I see not Hyper-V manger in my system. (I am using windows 11)

**Comment by david3a** [comment]
just run into this, windows home is my issue I assume, guess using minikube is not possible or is likely this can be handled ina  future release?

**Comment by rjdudley** [comment]
> just run into this, windows home is my issue I assume, guess using minikube is not possible or is likely this can be handled ina future release?

A few years ago there was a preview in a Windows Insider build running kubernetes on Home, but I'm not sure what happened to it.  There are a number of options for local kubernetes, I'm not sure if any of them can fake a hypervisor or not.  Most documentation doesn't discern the different editions of Windows so it's hard to tell until things don't work.

**Comment by david3a** [comment]
hyper=v is fine, docker and podman run fine so not sure what is missing

**Comment by git-chinmay** [comment]
Container on windows sucks!!!

**Comment by plppp2001** [comment]
https://ssharizal.medium.com/minikube-on-windows-11-home-edition-with-wsl-2-workaround-267536731402

**Comment by AbdulKhadhar** [comment]
> https://ssharizal.medium.com/minikube-on-windows-11-home-edition-with-wsl-2-workaround-267536731402

The workaround mentioned here worked for me as well 👍 , since I'm using Windows 11 Home edition, that turned out to be the issue.
