### ISSUE TITLE
gcp-auth plugin: propagate GOOGLE_CLOUD_PROJECT env

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#9055]
Something @viglesiasce noticed. 

/cc @sharifelgamal

**Comment by sharifelgamal** [comment]
Yeah, this belongs in the gcp-auth-webhook repo, that's where that code lives.

**Comment by sharifelgamal** [comment]
Opened https://github.com/GoogleContainerTools/gcp-auth-webhook/issues/2
