### ISSUE TITLE
minikube + kvm fails to get libvirt's dnsmasq leases with the new libvirt version.

### ISSUE THREAD

**Issue by mwiens** [kubernetes/minikube#906]
**Is this a BUG REPORT**

**Minikube version**: v0.13.1

**Environment**:
- **OS**: Ubuntu 16.04.1 LTS 64 bit run on OpenStack
- **VM Driver**: kvm (qemu 2.5.0), docker-machine-kvm v0.7.0
- **Docker version**: docker-machine 0.8.2, build e18a919
- **Install tools**: _what do you mean? apt? dpkg?_
- **Others** : 
**from virsh (libvirt console)**:
virsh # version
Compiled against library: libvirt 1.3.1
Using library: libvirt 1.3.1
Using API: QEMU 1.3.1
Running hypervisor: QEMU 2.5.0

**What happened**:
`minikube start --vm-driver kvm` fails to retrieve libvirt's dnsmasq leases for the VMs:

`(minikube) DBG | GetIP called for minikube`
`(minikube) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases`
`(minikube) DBG | Unable to locate IP address for MAC 52:54:00:c9:40:91`
`(minikube) DBG | Waiting for the VM to come up... 0`

**What you expected to happen**:
minikube reads leases from the /var/lib/libvirt/dnsmasq/docker-machines.leases file.

**How to reproduce it** (as minimally and precisely as possible):

That was tested on a fresh Ubuntu installation inside an OpenStack cluster:

1. Get Ubuntu 16.04.1 LTS (as VM or OpenStack instance for example) & login insto it
2. Get root: `sudo su` (so we can omit "sudo")
3. update/upgrade: `apt-get update; apt-get upgrade`
4. Install docker-machine as on [docker-machine release page](https://github.com/docker/machine/releases):
4.1. run: ``curl -L https://github.com/docker/machine/releases/download/v0.8.2/docker-machine-`uname -s`-`uname -m` >/usr/local/bin/docker-machine && chmod +x /usr/local/bin/docker-machine`` 
4.2. (optional) verify version of the docker-machine: `docker-machine -version`
5. Install docker-machine-kvm
5.1 Install KVM driver 0.7.0 as in [DRIVERS.md](https://github.com/kubernetes/minikube/blob/master/DRIVERS.md#kvm-driver): `curl -L https://github.com/dhiltgen/docker-machine-kvm/releases/download/v0.7.0/docker-machine-driver-kvm -o /usr/local/bin/docker-machine-driver-kvm`
5.2. make the driver executable: `chmod +x /usr/local/bin/docker-machine-driver-kvm`
5.3. Install libvirt and qemu-kvm as in [docker-machine-kvm README.md](https://github.com/dhiltgen/docker-machine-kvm): `apt-get install libvirt-bin qemu-kvm`
5.4 Add yourself to the libvirtd group: `usermod -a -G libvirtd $(whoami)`
5.5 Update your current session for the group change to take effect: `newgrp libvirtd`
5.6 (optional) start a test machine to verify docker-machine and kvm works: `docker-machine create -d kvm myengine0` and then `docker-machine ls` to show the machine list. Thenafter remove the machine: `docker-machine rm myengine0`
6. Install minikube
6.1. Get kubectl: `curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.4.6/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/`
6.1. Get minikube as on [release page](https://github.com/kubernetes/minikube/releases):
`curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.13.1/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/`
6.2 (optional) verify minikube version: `minikube version`
7. The issue
7.1 start minikube using kvm driver in verbose mode: `minikube start --vm-driver kvm --show-libmachine-logs --v=10 --alsologtostderr`
7.2. **Enjoy failed retrievement of the libvirt's dnamasq leases:**
`(minikube) DBG | GetIP called for minikube`
`(minikube) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases`
`(minikube) DBG | Unable to locate IP address for MAC 52:54:00:c9:40:91`
`(minikube) DBG | Waiting for the VM to come up... 0`
8. Nevertheless, minikube is running: `minikube status` : 
`minikubeVM: Running`
`localkube: Running`

**Anything else do we need to know**:
Digging in libvirt:
libvirt creates additional network called "docker-machines" bound to "virbr1". (there are actually two bridges the virbr0 is the default bridge). verify: `ifconfig`
You can list libvirts networks in libvirt console (start console with `virsh`):
`net-list` returns two networks: "default" and "docker-machines"
`net-info docker-machines` shows which bridge is bound to that network: `Bridge: virbr1`
Quit the console with `quit`

**Possible solution**
The new version of libvirt does not use /var/lib/libvirt/dnsmasq/_network-name_.leases file to show active leases anymore. Instead of that it uses following: /var/lib/libvirt/dnsmasq/_bridge-interface-name_.status
So we can see all leases of docker-machines by: `cat /var/lib/libvirt/dnsmasq/virbr1.status` as JSON object. 

> "It was done because dnsmasq's lease file did not store enough info for us to report IPv6 addresses assigned to guests.

See comment 3 on this [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1228631)

**Questions**

1. Will it be fixed?
2. Or should we use older libvirt version that writes to *.leases file?

**Comment by r2d4** [comment]
Thanks for the detailed bug report.  However, I think you may be having a different problem.  The KVM driver does try to look in both places for the active leases.   

https://github.com/dhiltgen/docker-machine-kvm/blob/master/kvm.go#L654-L661

The error messages in the KVM driver are sometimes misleading.  If you follow that code block above, you'll see that it prints the `Unable to find IP Address for MAC` message regardless of if it finds the IP or not.  

Can you post the relevant parts of your status file as well as the output of `minikube start --vm-driver kvm --show-libmachine-logs --v=10 --alsologtostderr`?

**Comment by mwiens** [comment]
I have tested the following on the new test-machine:

[command output in Ubuntu 16.04.1](https://gist.github.com/mwiens/9d196a7576d7793cb6db9f0e2abdb06a)
[virbr1.status file in Ubuntu 16.04.1](https://gist.github.com/mwiens/5c30eabe9e06379629c2476410701fed)

Probably the message `(minikube) DBG | Failed to retrieve dnsmasq leases from /var/lib/libvirt/dnsmasq/docker-machines.leases` signals, that `getIPByMACFromLeaseFile()` didn't work and then `getIPByMacFromSettings()` is maybe called (when the IP string was empty). But then, if the getIPByMacFromSettings was successful, we would see the IP adress: `log.Debugf("IP address: %s", value.Ip_address)` but not the failed message, nor the success message from `getIPByMACFromLeaseFile()` is shown. (Maybe the string of `getIPByMACFromLeaseFile()` is not empty?)

Anyway `log.Debugf("Unable to locate IP address for MAC %s", mac)` message is very irritating and confusing, this message shows up every second, 60 times. (see command output). Maybe it should be changed to more accurate output. Or the TODO in your link would maybe resolve the problem.

I also ran the minikube command from an Ubuntu 14.04 test machine and it had similar output. In that case the libvirt uses leases file. Here is the are both - output and leases: 

[command output in Ubuntu 14.04](https://gist.github.com/mwiens/a6febf88be9076702cad5955dd20dc26)
[docker-machines.leases file in Ubuntu 14.04](https://gist.github.com/mwiens/964b478983a0857fa7143d313c1b73d0)

Thank you for your help!

**Comment by r2d4** [comment]
Despite the debug messages from the KVM driver, it looks like minikube is actually configured correctly.

https://gist.github.com/mwiens/9d196a7576d7793cb6db9f0e2abdb06a#file-stdout-L855
https://gist.github.com/mwiens/a6febf88be9076702cad5955dd20dc26#file-gistfile1-txt-L763

Can you give the output of 
`kubectl version`
`minikube status`
`minikube logs`?

**Comment by mwiens** [comment]
For Ubuntu 16.04:
[kubectl version](https://gist.github.com/mwiens/f9071c7b1444b91ff95a28e3e787c734)
[minikube status](https://gist.github.com/mwiens/c010bb7167fb82953db1d682e4370988)
minikube logs produces 500MB(!) of logs. What is the best way to get it to you?

>Despite the debug messages from the KVM driver, it looks like minikube is actually configured correctly.

So it seems, that KVM driver tries to read from leases files. That would explain repeated messages about  `docker-macines.leases` but not missing success/fail messages from `getIPByMacFromSettings()`. Later it also tries  `getIPByMacFromSettings()` to get the ip ([an it gets it](https://gist.github.com/mwiens/9d196a7576d7793cb6db9f0e2abdb06a#file-stdout-L240)) from the status file, that would explain the repeated `(minikube) DBG | IP address: 192.168.42.205` messages later. So it seems that kvm driver reads the correct IP (for many times), but the console messages are not so clear.

**Comment by aaron-prindle** [comment]
Closing, this problem does not seem to be minikube related.  Please make an issue in the kvm driver if you are still having issues.
