### ISSUE TITLE
Connection to server failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp <minikube ip>:9090: connect: connection refused"

### ISSUE THREAD

**Issue by Himanshuxone** [kubernetes/minikube#9063]
**Steps to reproduce the issue:** 

1. create a grpc server running using grpc port flag / environment variables
2. connect mysql local database using service without selector. 
3. create a client in local to connect to running grpc server on minikube service.

**Full output of failed command:** 

=> grpc server is running on pods and created a database connection.

**Error**

`Connection to server failed: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 192.168.5.173:9090: connect: connection refused`

**Note:-**  error comes when I try to run a client from localhost to connect to grpc running server as Kubernetes service.

**Full output of `minikube start` command used, if not already included:**

minikube service is running properly only unable to access using go grpc client from local system

**Optional: Full output of `minikube logs` command:**
<details>

grpc server command running on minikube:-
`go run cmd/server/main.go -grpc-port=9090 -db-host=127.0.0.1:3306 -db-user=$USER -db-password=$password -db-schema=$database`

grpc client to access server running on minikube:-
`go run cmd/client-grpc/main.go -server=$(minikube ip):9090`

</details>

**Comment by fjmacagno** [comment]
How did you fix this?

**Comment by Paragon1970** [comment]
Yes, please do tell

**Comment by syauqisabili** [comment]
how to solve this problem?

**Comment by Paragon1970** [comment]
In my case the server host variable defaulted to localhost.
Setting the server to listen on 0.0.0.0 fixed the issue. (listen / allow for any ip)

**Comment by syauqisabili** [comment]
> In my case the server host variable defaulted to localhost.
> Setting the server to listen on 0.0.0.0 fixed the issue. (listen / allow for any ip)

when i checked netstat, the server was set up to listen on 0.0.0.0.

**Comment by DavidNix** [comment]
I am using kind, but had the same problem. `localhost` was the culprit.

This fixed it for me.

```
net.Listen("tcp", ":9090")
```

**Comment by viplavkatiyar** [comment]
Making the GRPC server listen to 0.0.0.0 instead of localhost fixed the 'Connection Refused' error in my case. This issue happened only when I created the server inside a kubernetes pod.

'localhost' works fine when running the server directly on the host machine.

**Comment by rayfoss** [comment]
Gitlab is down... stop debugging your internet.

![Screenshot from 2021-08-13 11-49-43](https://user-images.githubusercontent.com/876076/129393099-5acaa8d8-ddc3-48f4-aebb-77ec95e9fb55.png)

**Comment by quqonlik** [comment]
I disabled the firewalld on linux hosts and joined successfully
