### ISSUE TITLE
 Unable to pick a default driver. and driver=none is not working in windows 10 home edition

### ISSUE THREAD

**Issue by AmanMishra1321** [kubernetes/minikube#9067]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@AmanMishra1321 none is only for linux and not recommended, on windows 10 if you don't have docker, you could use virtualbox.

have you tried installing virtualbox and then trying minikube with virtualbox ?

/triage needs-information
/triage support

**Comment by AmanMishra1321** [comment]
> @AmanMishra1321 none is only for linux and not recommended, on windows 10 if you don't have docker, you could use virtualbox.
> 
> have you tried installing virtualbox and then trying minikube with virtualbox ?
> 
> /triage needs-information
> /triage support

I do have docker on my windows 10 Home and it is working properly

**Comment by priyawadhwa** [comment]
Hey @AmanMishra1321 that's great. I'll go ahead and close this issue as things are working as expected now. Feel free to reopen by commenting /reopen if needed.
