### ISSUE TITLE
minikube v1.12.3 faild to start on Centos 7.4.1708

### ISSUE THREAD

**Issue by lordk911** [kubernetes/minikube#9075]
$ docker -v
Docker version 17.03.2-ce, build f5ec1e2

$ minikube start --cpus=4 --memory=4096mb --driver=docker
* minikube v1.12.3 on Centos 7.4.1708
* Using the docker driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Creating docker container (CPUs=4, Memory=7900MB) ...
* Stopping node "minikube"  ...
* Powering off "minikube" via SSH ...
* Deleting "minikube" in docker ...
! StartHost failed, but will try again: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset543657973 into minikube:/home/docker/.ssh/authorized_keys, output: unknown shorthand flag: 'a' in -a
See 'docker cp --help'.
: exit status 125
* Creating docker container (CPUs=4, Memory=7900MB) ...
* Failed to start docker container. "minikube start" may fix it: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset080548560 into minikube:/home/docker/.ssh/authorized_keys, output: unknown shorthand flag: 'a' in -a
See 'docker cp --help'.
: exit status 125

**Comment by lordk911** [comment]
ok thanks

**Comment by afbjorklund** [comment]
Upgrading docker might help https://docs.docker.com/engine/install/centos/
