### ISSUE TITLE
save cache files under ~/.cache/minikube

### ISSUE THREAD

**Issue by drewpca** [kubernetes/minikube#9084]
minikube writes a lot to `~/.minikube/cache`, but other programs have agreed to use `~/.cache/<program>` instead. Consider switching to `$XDG_CACHE_HOME` (default `~/.cache`) for files that I can freely delete if I want to trade free disk for some repeated downloads or computation.

Perhaps the rest of `~/.minikube` should go under `$XDG_CONFIG_HOME` (default `~/.config/minikube`) to help curb the homedir dotfile mess, but that's not as important to me. Maybe some people are syncing `~/.config` between multiple hosts?

**Comment by afbjorklund** [comment]
Most of this was just inherited/extended from docker machine, but we talked about it in #4109

**Comment by afbjorklund** [comment]
We also discussed `~/.minikube` to somewhere under `~/.local` (not really XDG, but) in #8635

**Comment by afbjorklund** [comment]
We need ~/.minikube/machines to go _somewhere else_ than under `~/.config`, like `$XDG_DATA_HOME`

**Comment by afbjorklund** [comment]
> Maybe some people are syncing `~/.config` between multiple hosts?

Some people have $HOME on NFS, but they can set $MINIKUBE_HOME
