### ISSUE TITLE
Warn user to upgrade ancient Docker ( "docker cp -a") not working.

### ISSUE THREAD

**Issue by porytskyi** [kubernetes/minikube#9085]
😄  minikube v1.12.3 on Debian 9.13
✨  Using the docker driver based on user configuration

❗  'docker' driver reported a issue that could affect the performance.
💡  Suggestion: enable overlayfs kernel module on your Linux

👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v5-v1.18.3-docker-overlay2-amd64.tar.lz4: 510.91 MiB
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
✋  Stopping node "minikube"  ...
🛑  Powering off "minikube" via SSH ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset852410486 into minikube:/home/docker/.ssh/authorized_keys, output: unknown shorthand flag: 'a' in -a
See 'docker cp --help'.
: exit status 125
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
😿  Failed to start docker container. "minikube start" may fix it: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset160545117 into minikube:/home/docker/.ssh/authorized_keys, output: unknown shorthand flag: 'a' in -a
See 'docker cp --help'.
: exit status 125

💣  error provisioning host: Failed to start host: creating host: create: creating: prepare kic ssh: copying pub key: docker copy /tmp/tmpf-memory-asset160545117 into minikube:/home/docker/.ssh/authorized_keys, output: unknown shorthand flag: 'a' in -a
See 'docker cp --help'.
: exit status 125

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

go version go1.15 linux/amd64

**kubectl**
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server 192.168.0.103:6443 was refused - did you specify the right host or port?

**Comment by porytskyi** [comment]
Minikube started after updrade Docker version to 19.03.8.

**Comment by porytskyi** [comment]
Minikube started after updrade Docker version to 19.03.8.

**Comment by porytskyi** [comment]
Minikube started after updrade Docker version to 19.03.8.

**Comment by medyagh** [comment]
@porytskyi do you mind sharing 
full output of
"docker version"

and what was your docker version before?

**Comment by medyagh** [comment]
@porytskyi do you mind also sharing 
```
docker cp --help
```

**Comment by afbjorklund** [comment]
Same as #9075 - related to #9077

**Comment by medyagh** [comment]
could we try docker cp without -a ?

**Comment by tstromberg** [comment]
`minikube started after updrade Docker version to 19.03.8` - I wonder what version was running before.

 I'll note the -a flag does not exist in `docker.io_1.13.1-0ubuntu6_amd64`. It does seem like a very useful flag though. At a minimum this could use an actionable error message to ask for an upgrade.

**Comment by porytskyi** [comment]
@tstromberg 

The previous version was docker-ce 18.06.0 ~ ce ~ 3-0 ~ debian.
More information here: https://docs.docker.com/engine/install/debian in the Install Docker Engine section, step 2.

**Comment by porytskyi** [comment]
@medyagh 
Please note that I am using Docker version 19.03.8. Everything is working now.


```
Usage:	docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-
	docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH

Copy files/folders between a container and the local filesystem

Use '-' as the source to read a tar archive from stdin
and extract it to a directory destination in a container.
Use '-' as the destination to stream a tar archive of a
container source to stdout.

Options:
  -a, --archive       Archive mode (copy all uid/gid information)
  -L, --follow-link   Always follow symbol link in SRC_PATH
```

**Comment by ilya-zuyev** [comment]
Going to close this issue. The minimum supported docker version is 18.9 and it does have `-a` arg for `cp` command
