### ISSUE TITLE
add short name -o for json output flag

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9088]
medya@~/workspace/minikube (master) $ minikube start -o json
Error: unknown shorthand flag: 'o' in -o
See 'minikube start --help' for usage.

medya@~/workspace/minikube (master) $ minikube start --help | grep json
      --output='text': Format to print stdout in. Options include: [text,json]

**Comment by tstromberg** [comment]
This particular issue has flummoxed me as well.

/cc @priyawadhwa

**Comment by vinu2003** [comment]
Sure @tstromberg
