### ISSUE TITLE
error provisioning host: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800271733c0

### ISSUE THREAD

**Issue by aligandi** [kubernetes/minikube#9093]

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/triage support

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this for now. If you still have this issue, please reopen this and add the details @medyagh asked for above.
