### ISSUE TITLE
Mechanism to notify users of cluster upgrades

### ISSUE THREAD

**Issue by dlorenc** [kubernetes/minikube#91]
When we release new cluster components, we need a mechanism to notify users that the upgrades are available.

cc @vishh

**Comment by dlorenc** [comment]
We should also use a versioned URL for the .iso file, which will prevent incompatibilities later.

**Comment by luxas** [comment]
How should it be notified?
I have an idea that `minikube` could asynchronously fetch [this url](https://api.github.com/repos/kubernetes/minikube/releases), and sort it by date (it might be already), and download `assets.{minikube-GOOS-GOARCH}.browser_download_url` to a specific location.

**Comment by dlorenc** [comment]
There's also the question of how to perform the update. If we just restart localkube etcd data should be preserved, but that's not guaranteed AFAIK across kubernetes versions.

**Comment by vishh** [comment]
AFAIK, updates are supposed to not result in data loss. We do not test
upgrades and downgrades against multiple versions yet. We can just allow
upgrading for now. We can add downgrading once it is tested upstream in
kube.

**Comment by dlorenc** [comment]
I guess there are a few different components to consider:

- Upgrading the minikube CLI itself
- Upgrading the ISO
- Upgrading the cluster version (localkube, bundled inside minikube)

We can notify the users that minikube (and therefore localkube) have updates available by pinging that URL like @luxas suggested, but we'd probably want to finish a real installation script before offering to perform the upgrade.

We'll also want a way for users to opt out of the update notifications, which would require a stateful minikube config, maybe using something like: https://github.com/spf13/viper

@aaron-prindle do you want to take on the first item of notifying users that an updated CLI is available?

**Comment by luxas** [comment]
Moving to v0.4, given that you're releasing now

**Comment by dlorenc** [comment]
Closed with #191
