### ISSUE TITLE
The "new version of minikube" message shouldn't have the type io.k8s.sigs.minikube.error

### ISSUE THREAD

**Issue by jtzwu** [kubernetes/minikube#9108]
**Steps to reproduce the issue:** 

1. Run `minikube start --output=json` 

**Full output of `minikube start` command used, if not already included:**
...
{'data': {'message': 'minikube 1.12.3 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.12.3\n'}, 'datacontenttype': 'application/json', 'id': '561b5628-0fac-487d-b5fd-028a4c63503a', 'source': 'https://minikube.sigs.k8s.io/', 'specversion': '1.0', 'type': 'io.k8s.sigs.minikube.error'}

**Comment by vinu2003** [comment]
@tstromberg  just wanted to confirm even the below one type shouldn't be io.k8s.sigs.minikube.error correct ?
{"data":{"message":"You can also use 'minikube kubectl -- get pods' to invoke a matching version\n"},"datacontenttype":"application/json","id":"51d20524-d797-4f98-a452-0d2e6a84fb33","source":"https://minikube.sigs.k8s.io/","specversion":"1.0","type":"io.k8s.sigs.minikube.error"}

**Comment by tstromberg** [comment]
@vinu2003 - Your right, that does not sound like an error either. Do you mind sending a PR for it?

**Comment by vinu2003** [comment]
Sure I will send it. Thank you.
