### ISSUE TITLE
 --image-mirror-country="cn" still fetches binary SHA's from Google

### ISSUE THREAD

**Issue by hantsy** [kubernetes/minikube#9114]
Already used ` --image-mirror-country="cn"` or `--image-repository` to start minikube, but still failed in the preparing on Docker stage due to fetching sha files from google apis.

1. Why not mirror kubeXXX sha files together?
2. Why not package all essential dependencies in minikube?

**Comment by RA489** [comment]
@hantsy can you please try this WIP PR https://github.com/kubernetes/minikube/pull/8555 if this solve your issue?

**Comment by tstromberg** [comment]
1. The SHA images are kept along side the binaries that are downloaded
2. The dependencies depend on which version of Kubernetes you select.

Do you mind sharing the error message that you saw?

**Comment by medyagh** [comment]
@hantsy do we still have this issue ?
please reopen if still happening
