### ISSUE TITLE
Exposing ingress to a remote host

### ISSUE THREAD

**Issue by surensinghkhatana** [kubernetes/minikube#9116]
Hi, 
I am running a vagrant box using virtual box (running headless ubuntu 18.04) on windows 10 host machine. 
Inside the virtual box, I have minikube set up using docker as the vm-driver
`minikube start --memory=6144 --cpus=2 --disk-size=40g --vm-driver=docker --bootstrapper kubeadm --kubernetes-version=1.17.4`
My application is exposed via an ingress to the ubuntu machine running inside virtual box and I am able to access the application via wget/cURL
![image](https://user-images.githubusercontent.com/37261910/91631203-97fb5b00-e9e0-11ea-83c8-667f39ba2ea1.png)

 On doing minikube IP it gave me the IP of the docker container in which minikube runs

![image](https://user-images.githubusercontent.com/37261910/91631244-d264f800-e9e0-11ea-86f9-68d99c780704.png)

Some additional configuration info -
![image](https://user-images.githubusercontent.com/37261910/91631331-764ea380-e9e1-11ea-94e8-89848414b701.png)
![image](https://user-images.githubusercontent.com/37261910/91631718-5a98cc80-e9e4-11ea-95bd-37556962e274.png)
![image](https://user-images.githubusercontent.com/37261910/91633156-b9634380-e9ee-11ea-91a7-bbac59bbd7a6.png)

Vagrant file -
![image](https://user-images.githubusercontent.com/37261910/91631915-ec550980-e9e5-11ea-9b96-3a318a91e11c.png)

I would like to access the application from my windows machine's browser , any idea how to achieve that ? vagrant port forwarding doesn't seem to help.

Thanks

**Comment by priyawadhwa** [comment]
Hey @surensinghkhatana I'm not familiar with vagrant but it looks like you have this in your config:

```
  config.vm.network "forwarded_port", guest: 80, host: 8080

```

You could try  using `minikube tunnel` to forward your service to a local port in the ubuntu VM, and replace "guest: 80" with the port that provides. Then, the application should be forwarded to port 8080 on your Windows host. 

Let me know if that would helps. More info on tunnel [here](https://minikube.sigs.k8s.io/docs/commands/tunnel/)

**Comment by surensinghkhatana** [comment]
Hi @priyawadhwa ,
Thanks for your comment.
I have removed vagrant from the picture now. Minikube is running inside a docker container in a Ubuntu VM running on virtual box.

Some configuration info from my env :
![image](https://user-images.githubusercontent.com/37261910/92753299-6dbb7d00-f392-11ea-9da3-0cf91835388a.png)

![image](https://user-images.githubusercontent.com/37261910/92753571-af4c2800-f392-11ea-9064-646000ca783e.png)

![image](https://user-images.githubusercontent.com/37261910/92753640-c0953480-f392-11ea-8b2d-f272afd411b8.png)

I don't have any LoadBalancer service in my k8s cluster. I tried using minikube tunnel but couldn't understand how to expose a port on Ubuntu VM which could then be mapped to a port on my Host (windows) machine enabling the access to https://fg.iam.example.com/am from my host browser ?

**Comment by sharifelgamal** [comment]
I think what you're looking for is [ssh port forwarding](https://www.ssh.com/ssh/tunneling/example)

**Comment by ilya-zuyev** [comment]
@surensinghkhatana does ssh port forwarding work for you?

**Comment by surensinghkhatana** [comment]
Thanks for your reply, unfortunately it doesn't work still.
Minikube ip as shown in the picture is not reachable from my host machine ..

![image](https://user-images.githubusercontent.com/37261910/96835327-1e19a800-144c-11eb-9b80-3f945b07e936.png)

**Comment by surensinghkhatana** [comment]
Result of ifconfig inside the VM
![image](https://user-images.githubusercontent.com/37261910/96836556-d136d100-144d-11eb-87b2-e1fd6a62c516.png)

**Comment by medyagh** [comment]
the problem is, our current Docker driver only listens on 127.0.0.1, which is for security reasons. 

we could offer a --listen-remote flag for users who need to listen on non local hosts.


have you tried running minikube driectly on your host ? with either vbox or docker driver?

**Comment by vrybas** [comment]
> the problem is, our current Docker driver only listens on 127.0.0.1, which is for security reasons.
> we could offer a --listen-remote flag for users who need to listen on non local hosts.

@medyagh having this flag would be nice. Is there a temporary solution to make minikube running with docker driver inside Virtualbox VM listen for all requests?

**Comment by vrybas** [comment]
@surensinghkhatana were you able to make minikube to listen to external requests?

**Comment by surensinghkhatana** [comment]
@vrybas I decided to on with microk8s ..

**Comment by priyawadhwa** [comment]
Hey @surensinghkhatana sorry to hear that! Looks like there currently isn't a solution for this is in minikube, but if anyone would be interested in contributing one we'd be happy to look through a [design proposal](https://github.com/kubernetes/minikube/tree/master/enhancements)
