### ISSUE TITLE
ErrImagePull error while deploying service yaml

### ISSUE THREAD

**Issue by VivekMittals** [kubernetes/minikube#9118]
I am trying to understand and learn using minikube on my Ubutnu 18.04.
I can spin a normal pod, service for nginx but when I try doing something on for a node based image, I am running into issue i.e. 
ErrImagePull 

I tried running the very node image locally using docker and that worked.

Please note: I also tried docker login. But even post that I get the same issue.
I tried modifying the /etc/resolv.conf file as well to include "namespace  8.8.8.8"

:~ minikube start --vm-driver virtualbox
😄  minikube v1.9.1 on Ubuntu 18.04
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node m01 in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🐳  Preparing Kubernetes v1.18.0 on Docker 19.03.8 ...
🌟  Enabling addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"

**Steps to reproduce the issue:** 

1. create a deployment yaml. Attached sample.zip contains the Dockerfile, server.js (nodejs) and deployment.yml used
2. try deploying this yaml file. kubectl apply -f deployments/node-app/node-app-v1.deployment.yml
3. Check the status of the pods..

Please suggest if any other troubleshooting can help me narrow down the issue.

**Full output of failed command:** 
:~/Downloads/kubernetes_practise kubectl get pods
NAME                                      READY   STATUS              RESTARTS   AGE
node-app-6bd59b7f66-7s75m   0/1     ContainerCreating   0                  13s
node-app-6bd59b7f66-csvxl      0/1     ErrImagePull           0                  13s
node-app-6bd59b7f66-dfg74     0/1     ErrImagePull           0                  13s

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
==> kubelet <==
-- Logs begin at Sun 2020-08-30 01:40:07 UTC, end at Sun 2020-08-30 01:44:15 UTC. --
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411101    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "kubernetes-dashboard-token-bcn9g" (UniqueName: "kubernetes.io/secret/4a780380-3d84-479f-b385-ece01f11020c-kubernetes-dashboard-token-bcn9g") pod "dashboard-metrics-scraper-6b4884c9d5-vpn7z" (UID: "4a780380-3d84-479f-b385-ece01f11020c")
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411125    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/5b33a0be-5ae3-42cb-9b71-7c9d45fef714-lib-modules") pod "kube-proxy-zr8dc" (UID: "5b33a0be-5ae3-42cb-9b71-7c9d45fef714")
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411150    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "kubernetes-dashboard-certs" (UniqueName: "kubernetes.io/secret/00e78f4b-d924-42c1-ab92-56d19fb8cd9d-kubernetes-dashboard-certs") pod "kubernetes-dashboard-7b544877d5-6f6pc" (UID: "00e78f4b-d924-42c1-ab92-56d19fb8cd9d")
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411173    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "tmp-volume" (UniqueName: "kubernetes.io/empty-dir/00e78f4b-d924-42c1-ab92-56d19fb8cd9d-tmp-volume") pod "kubernetes-dashboard-7b544877d5-6f6pc" (UID: "00e78f4b-d924-42c1-ab92-56d19fb8cd9d")
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411195    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy" (UniqueName: "kubernetes.io/configmap/5b33a0be-5ae3-42cb-9b71-7c9d45fef714-kube-proxy") pod "kube-proxy-zr8dc" (UID: "5b33a0be-5ae3-42cb-9b71-7c9d45fef714")
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411234    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "xtables-lock" (UniqueName: "kubernetes.io/host-path/5b33a0be-5ae3-42cb-9b71-7c9d45fef714-xtables-lock") pod "kube-proxy-zr8dc" (UID: "5b33a0be-5ae3-42cb-9b71-7c9d45fef714")
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411257    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy-token-gcm9l" (UniqueName: "kubernetes.io/secret/5b33a0be-5ae3-42cb-9b71-7c9d45fef714-kube-proxy-token-gcm9l") pod "kube-proxy-zr8dc" (UID: "5b33a0be-5ae3-42cb-9b71-7c9d45fef714")
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411280    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "tmp-volume" (UniqueName: "kubernetes.io/empty-dir/4a780380-3d84-479f-b385-ece01f11020c-tmp-volume") pod "dashboard-metrics-scraper-6b4884c9d5-vpn7z" (UID: "4a780380-3d84-479f-b385-ece01f11020c")
Aug 30 01:40:44 minikube kubelet[2670]: I0830 01:40:44.411291    2670 reconciler.go:157] Reconciler: start to sync state
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.345939    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-66bff467f8-svzbx through plugin: invalid network status for
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.384823    2670 pod_container_deletor.go:77] Container "e9e047e94831b67a76bb8efba1f777ccac11f7d77a7f314221ad09aebd02325a" not found in pod's containers
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.446261    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kubernetes-dashboard/kubernetes-dashboard-7b544877d5-6f6pc through plugin: invalid network status for
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.452464    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-66bff467f8-mpgwr through plugin: invalid network status for
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.456567    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-66bff467f8-mpgwr through plugin: invalid network status for
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.511499    2670 pod_container_deletor.go:77] Container "ec614d4954b242411593ccd224849daa7b4bfc22484c1f383986baf2e5303c63" not found in pod's containers
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.566201    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kubernetes-dashboard/kubernetes-dashboard-7b544877d5-6f6pc through plugin: invalid network status for
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.572778    2670 pod_container_deletor.go:77] Container "ddc474f3f0eee3235fa990ff56a00efaea272a3ae09ff1e89ab4d0733506a1be" not found in pod's containers
Aug 30 01:40:46 minikube kubelet[2670]: W0830 01:40:46.997687    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kubernetes-dashboard/dashboard-metrics-scraper-6b4884c9d5-vpn7z through plugin: invalid network status for
Aug 30 01:40:47 minikube kubelet[2670]: W0830 01:40:47.003582    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kubernetes-dashboard/dashboard-metrics-scraper-6b4884c9d5-vpn7z through plugin: invalid network status for
Aug 30 01:40:47 minikube kubelet[2670]: W0830 01:40:47.026560    2670 pod_container_deletor.go:77] Container "0a84c22e09dbeb303869c841ab9c0bcc048fa90fcac3131ed42775bd969258df" not found in pod's containers
Aug 30 01:40:48 minikube kubelet[2670]: W0830 01:40:48.046922    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kubernetes-dashboard/kubernetes-dashboard-7b544877d5-6f6pc through plugin: invalid network status for
Aug 30 01:40:48 minikube kubelet[2670]: W0830 01:40:48.065762    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kubernetes-dashboard/dashboard-metrics-scraper-6b4884c9d5-vpn7z through plugin: invalid network status for
Aug 30 01:40:48 minikube kubelet[2670]: W0830 01:40:48.084630    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-66bff467f8-svzbx through plugin: invalid network status for
Aug 30 01:40:48 minikube kubelet[2670]: W0830 01:40:48.097517    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-66bff467f8-mpgwr through plugin: invalid network status for
Aug 30 01:40:53 minikube kubelet[2670]: W0830 01:40:53.232586    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for kubernetes-dashboard/kubernetes-dashboard-7b544877d5-6f6pc through plugin: invalid network status for
Aug 30 01:43:47 minikube kubelet[2670]: I0830 01:43:47.485436    2670 topology_manager.go:233] [topologymanager] Topology Admit Handler
Aug 30 01:43:47 minikube kubelet[2670]: E0830 01:43:47.491438    2670 reflector.go:178] object-"default"/"default-token-lkrcx": Failed to list *v1.Secret: secrets "default-token-lkrcx" is forbidden: User "system:node:minikube" cannot list resource "secrets" in API group "" in the namespace "default": no relationship found between node "minikube" and this object
Aug 30 01:43:47 minikube kubelet[2670]: I0830 01:43:47.520675    2670 topology_manager.go:233] [topologymanager] Topology Admit Handler
Aug 30 01:43:47 minikube kubelet[2670]: I0830 01:43:47.525609    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-lkrcx" (UniqueName: "kubernetes.io/secret/bb886b90-e12f-423c-84e9-3a1464cf3ba8-default-token-lkrcx") pod "node-app-6bd59b7f66-dfg74" (UID: "bb886b90-e12f-423c-84e9-3a1464cf3ba8")
Aug 30 01:43:47 minikube kubelet[2670]: I0830 01:43:47.543038    2670 topology_manager.go:233] [topologymanager] Topology Admit Handler
Aug 30 01:43:47 minikube kubelet[2670]: I0830 01:43:47.625983    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-lkrcx" (UniqueName: "kubernetes.io/secret/e4d1e3c1-7fd8-427f-94f9-e7269a9d37eb-default-token-lkrcx") pod "node-app-6bd59b7f66-7s75m" (UID: "e4d1e3c1-7fd8-427f-94f9-e7269a9d37eb")
Aug 30 01:43:47 minikube kubelet[2670]: I0830 01:43:47.626244    2670 reconciler.go:224] operationExecutor.VerifyControllerAttachedVolume started for volume "default-token-lkrcx" (UniqueName: "kubernetes.io/secret/c6a588aa-638e-40f8-9e2c-c51ea7bbf87a-default-token-lkrcx") pod "node-app-6bd59b7f66-csvxl" (UID: "c6a588aa-638e-40f8-9e2c-c51ea7bbf87a")
Aug 30 01:43:48 minikube kubelet[2670]: W0830 01:43:48.327958    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for default/node-app-6bd59b7f66-dfg74 through plugin: invalid network status for
Aug 30 01:43:48 minikube kubelet[2670]: W0830 01:43:48.432460    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for default/no
[sample.zip](https://github.com/kubernetes/minikube/files/5146224/sample.zip)
[sample.zip](https://github.com/kubernetes/minikube/files/5146245/sample.zip)

de-app-6bd59b7f66-csvxl through plugin: invalid network status for
Aug 30 01:43:48 minikube kubelet[2670]: W0830 01:43:48.433103    2670 pod_container_deletor.go:77] Container "945efc99c1d1179f4b8faaeaa337f91059ca161b6f51f772ee2404778d0fb5b6" not found in pod's containers
Aug 30 01:43:48 minikube kubelet[2670]: W0830 01:43:48.443204    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for default/node-app-6bd59b7f66-dfg74 through plugin: invalid network status for
Aug 30 01:43:48 minikube kubelet[2670]: W0830 01:43:48.555572    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for default/node-app-6bd59b7f66-7s75m through plugin: invalid network status for
Aug 30 01:43:48 minikube kubelet[2670]: W0830 01:43:48.557143    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for default/node-app-6bd59b7f66-7s75m through plugin: invalid network status for
Aug 30 01:43:48 minikube kubelet[2670]: W0830 01:43:48.561108    2670 pod_container_deletor.go:77] Container "5236330ab12a5ed285b9d915e00d94e2cba98a0e22faba59704a55733e477da0" not found in pod's containers
Aug 30 01:43:49 minikube kubelet[2670]: W0830 01:43:49.578390    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for default/node-app-6bd59b7f66-7s75m through plugin: invalid network status for
Aug 30 01:43:49 minikube kubelet[2670]: W0830 01:43:49.581450    2670 docker_sandbox.go:400] failed to read pod IP from plugin/docker: Couldn't find network status for default/node-app-6bd59b7f66-csvxl through plugin: invalid network status for
Aug 30 01:43:52 minikube kubelet[2670]: E0830 01:43:52.705598    2670 remote_image.go:113] PullImage "node-app:1.0" from image service failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:43:52 minikube kubelet[2670]: E0830 01:43:52.705669    2670 kuberuntime_image.go:50] Pull image "node-app:1.0" failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:43:52 minikube kubelet[2670]: E0830 01:43:52.705950    2670 kuberuntime_manager.go:801] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:43:52 minikube kubelet[2670]: E0830 01:43:52.706050    2670 pod_workers.go:191] Error syncing pod bb886b90-e12f-423c-84e9-3a1464cf3ba8 ("node-app-6bd59b7f66-dfg74_default(bb886b90-e12f-423c-84e9-3a1464cf3ba8)"), skipping: failed to "StartContainer" for "node-app" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
Aug 30 01:43:53 minikube kubelet[2670]: E0830 01:43:53.657452    2670 pod_workers.go:191] Error syncing pod bb886b90-e12f-423c-84e9-3a1464cf3ba8 ("node-app-6bd59b7f66-dfg74_default(bb886b90-e12f-423c-84e9-3a1464cf3ba8)"), skipping: failed to "StartContainer" for "node-app" with ImagePullBackOff: "Back-off pulling image \"node-app:1.0\""
Aug 30 01:43:57 minikube kubelet[2670]: E0830 01:43:57.314233    2670 remote_image.go:113] PullImage "node-app:1.0" from image service failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:43:57 minikube kubelet[2670]: E0830 01:43:57.315390    2670 kuberuntime_image.go:50] Pull image "node-app:1.0" failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:43:57 minikube kubelet[2670]: E0830 01:43:57.315798    2670 kuberuntime_manager.go:801] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:43:57 minikube kubelet[2670]: E0830 01:43:57.315961    2670 pod_workers.go:191] Error syncing pod c6a588aa-638e-40f8-9e2c-c51ea7bbf87a ("node-app-6bd59b7f66-csvxl_default(c6a588aa-638e-40f8-9e2c-c51ea7bbf87a)"), skipping: failed to "StartContainer" for "node-app" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
Aug 30 01:43:57 minikube kubelet[2670]: E0830 01:43:57.731142    2670 pod_workers.go:191] Error syncing pod c6a588aa-638e-40f8-9e2c-c51ea7bbf87a ("node-app-6bd59b7f66-csvxl_default(c6a588aa-638e-40f8-9e2c-c51ea7bbf87a)"), skipping: failed to "StartContainer" for "node-app" with ImagePullBackOff: "Back-off pulling image \"node-app:1.0\""
Aug 30 01:44:02 minikube kubelet[2670]: E0830 01:44:02.227779    2670 remote_image.go:113] PullImage "node-app:1.0" from image service failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:44:02 minikube kubelet[2670]: E0830 01:44:02.227816    2670 kuberuntime_image.go:50] Pull image "node-app:1.0" failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:44:02 minikube kubelet[2670]: E0830 01:44:02.227867    2670 kuberuntime_manager.go:801] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:44:02 minikube kubelet[2670]: E0830 01:44:02.227904    2670 pod_workers.go:191] Error syncing pod e4d1e3c1-7fd8-427f-94f9-e7269a9d37eb ("node-app-6bd59b7f66-7s75m_default(e4d1e3c1-7fd8-427f-94f9-e7269a9d37eb)"), skipping: failed to "StartContainer" for "node-app" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"
Aug 30 01:44:02 minikube kubelet[2670]: E0830 01:44:02.827334    2670 pod_workers.go:191] Error syncing pod e4d1e3c1-7fd8-427f-94f9-e7269a9d37eb ("node-app-6bd59b7f66-7s75m_default(e4d1e3c1-7fd8-427f-94f9-e7269a9d37eb)"), skipping: failed to "StartContainer" for "node-app" with ImagePullBackOff: "Back-off pulling image \"node-app:1.0\""
Aug 30 01:44:13 minikube kubelet[2670]: E0830 01:44:13.183227    2670 remote_image.go:113] PullImage "node-app:1.0" from image service failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:44:13 minikube kubelet[2670]: E0830 01:44:13.183484    2670 kuberuntime_image.go:50] Pull image "node-app:1.0" failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:44:13 minikube kubelet[2670]: E0830 01:44:13.183917    2670 kuberuntime_manager.go:801] container start failed: ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Aug 30 01:44:13 minikube kubelet[2670]: E0830 01:44:13.184124    2670 pod_workers.go:191] Error syncing pod bb886b90-e12f-423c-84e9-3a1464cf3ba8 ("node-app-6bd59b7f66-dfg74_default(bb886b90-e12f-423c-84e9-3a1464cf3ba8)"), skipping: failed to "StartContainer" for "node-app" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"

</details>

**Comment by kadern0** [comment]
Minikube's docker and host's docker are not the same. You can always push the images to a registry or reuse the docker daemon as shown in the Docs:
https://github.com/kubernetes/minikube/blob/0c616a6b42b28a1aab8397f5a9061f8ebbd9f3d9/README.md#reusing-the-docker-daemon

**Comment by VivekMittals** [comment]
Thanks @kadern0 for your response!

I tried setting the --noproxy option but still am facing the same issue. Not really sure if I am missing a basic config step.

Will try further soon enough and let you know how that goes!

Thanks again!

**Comment by blueelvis** [comment]
@VivekMittals - Hey! Were you able to resolve your issue or is this still an issue?

**Comment by priyawadhwa** [comment]
Hey @VivekMittals I'm going to go ahead and close this issue as it's been quiet for a couple months now. Please feel free to reopen at any time if you're still seeing this issue!

I would also suggest the following:

1. Upgrading to our latest version of minikube (currently 1.15.1) to see if that resolves this issue
1. Using our docker driver via `minikube start --driver docker` which is our recommended driver
1. Making sure you have the correct auth to pull images with minikube via:

```
eval $(minikube docker-env) # This will point your terminal to the docker daemon within minikube
docker pull <image name> # This should work if auth is correctly set up
```

Thank you for opening this issue!

**Comment by Savvy-Wadhwani** [comment]
Thanks @priyawadhwa, I did try upgrading the minikube to latest version i.e. 1.15.1
but unfortunately I still get the same issue for ErrImagePull.

vivek:~ minikube start --driver docker
😄  minikube v1.15.1 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.19.4 preload ...
    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 486.35 MiB
🔥  Creating docker container (CPUs=2, Memory=2900MB) ...
🐳  Preparing Kubernetes v1.19.4 on Docker 19.03.13 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

Is there some detailed steps that I can follow to rule out any other config issue please?

**Comment by VivekMittals** [comment]
@priyawadhwa I did try upgrading the minikube to mentioned 1.15.1 version but still I get the same issue.

Can you list or point me to any detailed steps to check the configuration with respect to authentication etc. so that we can rule out those aspects.

minikube start --driver docker
😄  minikube v1.15.1 on Ubuntu 18.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.19.4 preload ...
    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 486.35 MiB
🔥  Creating docker container (CPUs=2, Memory=2900MB) ...
🐳  Preparing Kubernetes v1.19.4 on Docker 19.03.13 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Comment by VivekMittals** [comment]
@blueelvis I am still facing the same issue even after upgrading to latest minikube version

**Comment by VivekMittals** [comment]
I think I found something, but not sure how to proceed further on this..

Nov 29 14:58:28 minikube kubelet[1097]: E1129 14:58:28.448752    1097 remote_image.go:113] PullImage "node-app:1.0" from image service failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Nov 29 14:58:28 minikube kubelet[1097]: E1129 14:58:28.448811    1097 kuberuntime_image.go:51] Pull image "node-app:1.0" failed: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Nov 29 14:58:28 minikube kubelet[1097]: E1129 14:58:28.448919    1097 kuberuntime_manager.go:815] container &Container{Name:node-app,Image:node-app:1.0,Command:[],Args:[],WorkingDir:,Ports:[]ContainerPort{},Env:[]EnvVar{},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:default-token-h98rp,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:nil,ReadinessProbe:nil,Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:nil,Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,} start failed in pod node-app-7f5f5d85fc-lhp7n_default(b67cc443-7768-4921-80b2-d59f7525988c): ErrImagePull: rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
Nov 29 14:58:28 minikube kubelet[1097]: E1129 14:58:28.448964    1097 pod_workers.go:191] Error syncing pod b67cc443-7768-4921-80b2-d59f7525988c ("node-app-7f5f5d85fc-lhp7n_default(b67cc443-7768-4921-80b2-d59f7525988c)"), skipping: failed to "StartContainer" for "node-app" with ErrImagePull: "rpc error: code = Unknown desc = Error response from daemon: pull access denied for node-app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied"

On further probing on my local ubuntu.. I see docker images that I have created earlier

But if I start minikube using: minikube start --driver docker

and enter the container using... minikube ssh

then I cannot see those docker images..

So there are 2 things:

1) How can this docker container have access to my local docker images?
2) Is there a way to assign some way as to how my docker files can be accessed from within this docker container so that I can rebuild those images from inside this container.
