### ISSUE TITLE
 Checksums did not match for  *sha1.digest

### ISSUE THREAD

**Issue by gudipudipradeep** [kubernetes/minikube#9119]
**Steps to reproduce the issue:** 
sudo minikube start --v=7 --driver=none --kubernetes-version=1.15.0

**Full output of failed command:** 
root@ubuntu-bionic:~# minikube start --driver=none --kubernetes-version=1.15.0 --alsologtostderr
W0830 05:29:35.274978    5712 root.go:246] Error reading config file at /home/vagrant/.minikube/config/config.json: open /home/vagrant/.minikube/config/config.json: no such file or directory
I0830 05:29:35.279234    5712 start.go:99] hostinfo: {"hostname":"ubuntu-bionic","uptime":1334,"bootTime":1598764041,"procs":165,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"4.15.0-112-generic","virtualizationSystem":"vbox","virtualizationRole":"guest","hostid":"f242bdbd-b605-b542-af22-809fedeaae6d"}
I0830 05:29:35.280331    5712 start.go:109] virtualization: vbox guest
😄  minikube v1.12.0 on Ubuntu 18.04 (vbox/amd64)
I0830 05:29:35.290394    5712 exec_runner.go:49] Run: systemctl --version
I0830 05:29:35.297842    5712 driver.go:257] Setting default libvirt URI to qemu:///system
✨  Using the none driver based on existing profile
I0830 05:29:35.302406    5712 start.go:209] selected driver: none
I0830 05:29:35.302426    5712 start.go:608] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2400 CPUs:2 DiskSize:20000 Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.15.0 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:10.0.2.15 Port:8443 KubernetesVersion:v1.15.0 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0830 05:29:35.302577    5712 start.go:619] status for none: {Installed:true Healthy:true NeedsImprovement:false Error:<nil> Fix: Doc:}
I0830 05:29:35.302624    5712 start.go:982] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
🆕  Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
🆕  Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
🆕  Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
🆕  Kubernetes 1.18.3 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.18.3
👍  Starting control plane node minikube in cluster minikube
I0830 05:29:35.314988    5712 profile.go:150] Saving config to /home/vagrant/.minikube/profiles/minikube/config.json ...I0830 05:29:35.315350    5712 cache.go:178] Successfully downloaded all kic artifacts
I0830 05:29:35.315379    5712 start.go:240] acquiring machines lock for minikube: {Name:mk72c716077c0de2524240e3ea60e7918172f15a Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0830 05:29:35.315553    5712 start.go:244] acquired machines lock for "minikube" in 147.008µs
I0830 05:29:35.316025    5712 start.go:88] Skipping create...Using existing machine configuration
I0830 05:29:35.316039    5712 fix.go:53] fixHost starting: m01
W0830 05:29:35.316315    5712 none.go:130] unable to get port: "minikube" does not appear in /home/vagrant/.kube/config
I0830 05:29:35.317043    5712 api_server.go:146] Checking apiserver status ...
I0830 05:29:35.317090    5712 exec_runner.go:49] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0830 05:29:35.347129    5712 api_server.go:150] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0830 05:29:35.348177    5712 system_pods.go:161] Checking kubelet status ...
I0830 05:29:35.348276    5712 exec_runner.go:49] Run: sudo systemctl is-active --quiet service kubelet
I0830 05:29:35.375089    5712 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0830 05:29:35.376028    5712 fix.go:131] unexpected machine state, will restart: <nil>
🔄  Restarting existing none bare metal machine for "minikube" ...
I0830 05:29:35.401135    5712 profile.go:150] Saving config to /home/vagrant/.minikube/profiles/minikube/config.json ...I0830 05:29:35.402664    5712 start.go:203] post-start starting for "minikube" (driver="none")
I0830 05:29:35.403226    5712 start.go:213] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0830 05:29:35.403400    5712 exec_runner.go:49] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0830 05:29:35.436829    5712 main.go:115] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0830 05:29:35.438350    5712 main.go:115] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0830 05:29:35.438731    5712 main.go:115] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
ℹ️  OS release is Ubuntu 18.04.5 LTS
I0830 05:29:35.448865    5712 filesync.go:118] Scanning /home/vagrant/.minikube/addons for local assets ...
I0830 05:29:35.454681    5712 filesync.go:118] Scanning /home/vagrant/.minikube/files for local assets ...
I0830 05:29:35.454976    5712 start.go:206] post-start completed in 51.661366ms
I0830 05:29:35.455731    5712 fix.go:92] none is local, skipping auth/time setup (requires ssh)
I0830 05:29:35.455760    5712 fix.go:55] fixHost completed within 139.718454ms
I0830 05:29:35.457299    5712 start.go:75] releasing machines lock for "minikube", held for 141.281313ms
I0830 05:29:35.460324    5712 exec_runner.go:49] Run: curl -sS -m 2 https://k8s.gcr.io/
I0830 05:29:35.461727    5712 exec_runner.go:49] Run: sudo systemctl is-active --quiet service containerd
I0830 05:29:35.506010    5712 exec_runner.go:49] Run: sudo systemctl cat docker.service
I0830 05:29:35.538901    5712 exec_runner.go:49] Run: sudo systemctl daemon-reload
I0830 05:29:35.849239    5712 exec_runner.go:49] Run: sudo systemctl start docker
I0830 05:29:35.876828    5712 exec_runner.go:49] Run: docker version --format {{.Server.Version}}
🐳  Preparing Kubernetes v1.15.0 on Docker 19.03.6 ...
I0830 05:29:36.277433    5712 start.go:268] checking
I0830 05:29:36.277549    5712 exec_runner.go:49] Run: grep 127.0.0.1    host.minikube.internal$ /etc/hosts
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
I0830 05:29:36.292395    5712 preload.go:95] Checking if preload exists for k8s version v1.15.0 and runtime docker
W0830 05:29:37.202961    5712 preload.go:116] https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v4-v1.15.0-docker-overlay2-amd64.tar.lz4 status code: 404
I0830 05:29:37.203167    5712 cni.go:74] Creating CNI manager for ""
I0830 05:29:37.204237    5712 cni.go:113] CNI unnecessary in this configuration, recommending no CNI
I0830 05:29:37.204541    5712 kubeadm.go:79] Using pod CIDR:
I0830 05:29:37.204626    5712 kubeadm.go:139] kubeadm options: {CertDir:/var/lib/minikube/certs ServiceCIDR:10.96.0.0/12 PodSubnet: AdvertiseAddress:10.0.2.15 APIServerPort:8443 KubernetesVersion:v1.15.0 EtcdDataDir:/var/lib/minikube/etcd EtcdExtraArgs:map[] ClusterName:minikube NodeName:ubuntu-bionic DNSDomain:cluster.local CRISocket: ImageRepository: ComponentOptions:[{Component:apiServer ExtraArgs:map[enable-admission-plugins:NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota] Pairs:map[certSANs:["127.0.0.1", "localhost", "10.0.2.15"]]}] FeatureArgs:map[] NoTaintMaster:true NodeIP:10.0.2.15 ControlPlaneAddress:control-plane.minikube.internal KubeProxyOptions:map[]}
I0830 05:29:37.204993    5712 kubeadm.go:143] kubeadm config:
apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.0.2.15
  bindPort: 8443
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: "ubuntu-bionic"
  kubeletExtraArgs:
    node-ip: 10.0.2.15
  taints: []
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
apiServer:
  certSANs: ["127.0.0.1", "localhost", "10.0.2.15"]
  extraArgs:
    enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
certificatesDir: /var/lib/minikube/certs
clusterName: minikube
controlPlaneEndpoint: control-plane.minikube.internal:8443
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/minikube/etcd
    extraArgs:
      listen-metrics-urls: http://127.0.0.1:2381,http://10.0.2.15:2381
controllerManager:
  extraArgs:
    "leader-elect": "false"
scheduler:
  extraArgs:
    "leader-elect": "false"
kubernetesVersion: v1.15.0
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDomain: "cluster.local"
# disable disk resource management by default
imageGCHighThresholdPercent: 100
evictionHard:
  nodefs.available: "0%"
  nodefs.inodesFree: "0%"
  imagefs.available: "0%"
failSwapOn: false
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clusterCIDR: ""
metricsBindAddress: 10.0.2.15:10249

I0830 05:29:37.206032    5712 exec_runner.go:49] Run: docker info --format {{.CgroupDriver}}
I0830 05:29:37.453875    5712 kubeadm.go:775] kubelet [Unit]
Wants=docker.socket

[Service]
ExecStart=
ExecStart=/var/lib/minikube/binaries/v1.15.0/kubelet --authorization-mode=Webhook --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --cgroup-driver=cgroupfs --client-ca-file=/var/lib/minikube/certs/ca.crt --config=/var/lib/kubelet/config.yaml --container-runtime=docker --hostname-override=ubuntu-bionic --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=10.0.2.15 --pod-manifest-path=/etc/kubernetes/manifests --resolv-conf=/run/systemd/resolve/resolv.conf

[Install]
 config:
{KubernetesVersion:v1.15.0 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:}
I0830 05:29:37.454592    5712 exec_runner.go:49] Run: sudo ls /var/lib/minikube/binaries/v1.15.0
I0830 05:29:37.469101    5712 binaries.go:46] Didn't find k8s binaries: didn't find preexisting kubelet
Initiating transfer...
I0830 05:29:37.469887    5712 exec_runner.go:49] Run: sudo mkdir -p /var/lib/minikube/binaries/v1.15.0
I0830 05:29:37.487737    5712 download.go:73] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl.sha1 -> /home/vagrant/.minikube/cache/linux/v1.15.0/kubectl
I0830 05:29:37.487916    5712 download.go:73] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubelet.sha1 -> /home/vagrant/.minikube/cache/linux/v1.15.0/kubelet
I0830 05:29:37.487968    5712 download.go:73] Downloading: https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubeadm.sha1 -> /home/vagrant/.minikube/cache/linux/v1.15.0/kubeadm
    > kubelet.sha1: 41 B / 41 B [----------------------------] 100.00% ? p/s 0s
    > kubectl.sha1: 41 B / 41 B [----------------------------] 100.00% ? p/s 0s
    > kubeadm.sha1: 41 B / 41 B [----------------------------] 100.00% ? p/s 0s
I0830 05:29:39.752984    5712 exit.go:58] WithError(Failed to update cluster)=updating node: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl.sha1: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl.sha1 Dst:/home/vagrant/.minikube/cache/linux/v1.15.0/kubectl.download Pwd: Mode:2 Detectors:[0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350] Decompressors:map[bz2:0x2cc1350 gz:0x2cc1350 tar.bz2:0x2cc1350 tar.gz:0x2cc1350 tar.xz:0x2cc1350 tbz2:0x2cc1350 tgz:0x2cc1350 txz:0x2cc1350 xz:0x2cc1350 zip:0x2cc1350] Getters:map[file:0xc0009991b0 http:0xc000961260 https:0xc000961280] Dir:false ProgressListener:0x2c99b20 Options:[0xc2aa30]}: Checksums did not match for /home/vagrant/.minikube/cache/linux/v1.15.0/kubectl.download.
Expected: d604417c2efba1413e2441f16de3be84d3d9b1ae
Got: 4523f1c854bb7718df749fa374b461f26b8272f9
*sha1.digest called from:
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0xc000256480)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
k8s.io/minikube/pkg/minikube/exit.WithError(0x1bb5c6a, 0x18, 0x1ea7cc0, 0xc00073e260)
        /app/pkg/minikube/exit/exit.go:58 +0x34
k8s.io/minikube/pkg/minikube/node.setupKubeAdm(0x1f148c0, 0xc000429f40, 0xc00075d5c0, 0x8, 0x0, 0x0, 0x0, 0xc000084a80, 0x6b, 0x960, ...)
        /app/pkg/minikube/node/start.go:297 +0x51a
k8s.io/minikube/pkg/minikube/node.Start(0x1ee67e0, 0x2cc1350, 0x1, 0x1f148c0, 0xc000429f40, 0xc00040a900, 0xc000775c00, 0xc000429b00, 0xc00059f980, 0x1758d01, ...)
        /app/pkg/minikube/node/start.go:111 +0x40b
k8s.io/minikube/cmd/minikube/cmd.startWithDriver(0x1ee67e0, 0x2cc1350, 0x1, 0x1f148c0, 0xc000429f40, 0xc00040a900, 0xc000775c00, 0xc000429b00, 0xc00059f980, 0xc000774000, ...)
        /app/cmd/minikube/cmd/start.go:275 +0x7c
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2c85020, 0xc000128a20, 0x0, 0x3)
        /app/cmd/minikube/cmd/start.go:195 +0x2d6
github.com/spf13/cobra.(*Command).execute(0x2c85020, 0xc0001289f0, 0x3, 0x3, 0x2c85020, 0xc0001289f0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x2c84060, 0x0, 0x1, 0xc00022ff80)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:106 +0x747
main.main()
        /app/cmd/minikube/main.go:71 +0x143
W0830 05:29:39.757516    5712 out.go:201] Failed to update cluster: updating node: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl.sha1: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl.sha1 Dst:/home/vagrant/.minikube/cache/linux/v1.15.0/kubectl.download Pwd: Mode:2 Detectors:[0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350] Decompressors:map[bz2:0x2cc1350 gz:0x2cc1350 tar.bz2:0x2cc1350 tar.gz:0x2cc1350 tar.xz:0x2cc1350 tbz2:0x2cc1350 tgz:0x2cc1350 txz:0x2cc1350 xz:0x2cc1350 zip:0x2cc1350] Getters:map[file:0xc0009991b0 http:0xc000961260 https:0xc000961280] Dir:false ProgressListener:0x2c99b20 Options:[0xc2aa30]}: Checksums did not match for /home/vagrant/.minikube/cache/linux/v1.15.0/kubectl.download.
Expected: d604417c2efba1413e2441f16de3be84d3d9b1ae
Got: 4523f1c854bb7718df749fa374b461f26b8272f9
*sha1.digest

💣  Failed to update cluster: updating node: downloading binaries: downloading kubectl: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl.sha1: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl.sha1 Dst:/home/vagrant/.minikube/cache/linux/v1.15.0/kubectl.download Pwd: Mode:2 Detectors:[0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350 0x2cc1350] Decompressors:map[bz2:0x2cc1350 gz:0x2cc1350 tar.bz2:0x2cc1350 tar.gz:0x2cc1350 tar.xz:0x2cc1350 tbz2:0x2cc1350 tgz:0x2cc1350 txz:0x2cc1350 xz:0x2cc1350 zip:0x2cc1350] Getters:map[file:0xc0009991b0 http:0xc000961260 https:0xc000961280] Dir:false ProgressListener:0x2c99b20 Options:[0xc2aa30]}: Checksums did not match for /home/vagrant/.minikube/cache/linux/v1.15.0/kubectl.download.
Expected: d604417c2efba1413e2441f16de3be84d3d9b1ae
Got: 4523f1c854bb7718df749fa374b461f26b8272f9
*sha1.digest

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @gudipudipradeep thanks for opening this issue. Would you mind downloading the latest version of minikube v1.13.0 and trying with that?

Running the following:

```
sudo minikube delete
sudo minikube start --v=7 --driver=none --kubernetes-version=1.15.0
```

**Comment by priyawadhwa** [comment]
Hey @gudipudipradeep  -- hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

Thank you for sharing your experience!
