### ISSUE TITLE
Update to 1.5.0 stable release

### ISSUE THREAD

**Issue by NickClark** [kubernetes/minikube#912]
You are probably already working on this, but 1.5.0 is out now 😄

**Comment by r2d4** [comment]
Thanks!  We've been working on this in tandem and I've already made a PR #908. And it should be out soon!

**Comment by NickClark** [comment]
Ouch, sorry about that, I swear I searched first 😄

**Comment by r2d4** [comment]
closing, PR was merged.  

minikube v0.14.0 will run kubernetes v1.5.1 by default

**Comment by NickClark** [comment]
Any ETA on 0.14?

**Comment by NickClark** [comment]
Wow. You guys are on the ball! Thanks!
