### ISSUE TITLE
404 in release notes

### ISSUE THREAD

**Issue by arun-gupta** [kubernetes/minikube#913]
Fourth bullet in https://github.com/kubernetes/minikube/blob/v0.13.1/README.md#requirements points to http://kubernetes.io/docs/getting-started-guides/minikube/#install-kubectl for `these steps`. The correct link could be http://kubernetes.io/docs/getting-started-guides/minikube/#kubectl but this does not explain how to install `kubectl`.

May be the link should be http://kubernetes.io/docs/user-guide/prereqs/.

**Comment by r2d4** [comment]
Hey good catch!  The kuberenets.io docs just got updated last night with the v1.5 release. 

Its probably easiest to link to kubectl instructions on the minikube docs from the release note.

**Comment by aaron-prindle** [comment]
Fixed, closing
