### ISSUE TITLE
hyperv: provision: IP not found

### ISSUE THREAD

**Issue by josealmeida-vf** [kubernetes/minikube#9155]
**Steps to reproduce the issue:** 

1. minikube start --vm-driver="hyperv" --hyperv-virtual-switch="minikube"   
2. 
3.

**Full output of failed command:** 
 minikube v1.12.3 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. "minikube start" may fix it: provision: IP not found
*
X error provisioning host: Failed to start host: provision: IP not found
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
Can you include the output of:

`minikube start --alsologtostderr -v=3`

As best as I can tell, this error is being returned by machine-drivers. 

I am also curious if `minikube delete` fixes the issue.

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The driver you are using. (docker, virtualbox, hyperv....)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/triage support

**Comment by medyagh** [comment]
@josealmeida-vf  I have not heard back from you, I wonder if you still have this issue
