### ISSUE TITLE
--extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy not propagating to kube-apiserver command line

### ISSUE THREAD

**Issue by ovidiuf** [kubernetes/minikube#9173]
**Steps to reproduce the issue:** 

1. Execute minikube start command:

```
minikube start --extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy --addons=pod-security-policy
```

2. Wait for the cluster to start, pull kube-apiserver-minikube pod description:

```
kubectl -n kube-system describe pod kube-apiserver-minikube
```

3. The kube-apiserver --enable-admission-plugins argument does not include "PodSecurityPolicy" - in consequence, pod security policy is not activated and pods that are not supposed to be created are created:

```
Name:                 kube-apiserver-minikube
Namespace:            kube-system
Priority:             2000000000
Priority Class Name:  system-cluster-critical
Node:                 minikube/172.17.0.2
Start Time:           Thu, 03 Sep 2020 01:02:35 -0700
[...]
Containers:
  kube-apiserver:
   [...]
    Command:
      kube-apiserver
      --advertise-address=172.17.0.2
      --allow-privileged=true
      --authorization-mode=Node,RBAC
      --client-ca-file=/var/lib/minikube/certs/ca.crt
      --enable-admission-plugins=NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota
   [...]
```

**Full output of failed command:** 

[alsologtostderr.txt](https://github.com/kubernetes/minikube/files/5167440/alsologtostderr.txt)

**Full output of `minikube start` command used, if not already included:**

```
minikube start --extra-config=apiserver.enable-admission-plugins=PodSecurityPolicy --addons=pod-security-policy
😄  minikube v1.12.3 on Darwin 10.14.6
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
    ▪ apiserver.enable-admission-plugins=PodSecurityPolicy
🔎  Verifying Kubernetes components...
🌟  Enabled addons: dashboard, default-storageclass, pod-security-policy, storage-provisioner
🏄  Done! kubectl is now configured to use "minikube"
```

**Optional: Full output of `minikube logs` command:**

[minikube-logs-output.txt](https://github.com/kubernetes/minikube/files/5167420/minikube-logs-output.txt)

**Comment by vishjain** [comment]
Can I take this on a first issue? Thanks!

**Comment by priyawadhwa** [comment]
Hey @ovidiuf thanks for opening this issue, it looks like a duplicate of https://github.com/kubernetes/minikube/issues/8661. I'm going to close this issue so that we can centralize this conversation in one issue.

Unfortunately, right now this flag only seems to work on brand new clusters. Until we fix this, you'll have to delete the cluster and run `minikube start` again for the `--extra-config` flag to work.

Please feel free to comment on that issue, or to reopen this one if you don't think the issue is the same!

**Comment by ovidiuf** [comment]
Thanks.
