### ISSUE TITLE
Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory

### ISSUE THREAD

**Issue by okwunna** [kubernetes/minikube#9174]
**Steps to reproduce the issue:** 

1.minikube start
2. 
3.

**Full output of failed command:** 
W0903 12:29:37.248216    9361 root.go:246] Error reading config file at /Users/nodebe/.minikube/config/config.json: open /Users/nodebe/.minikube/config/config.json: no such file or directory
I0903 12:29:37.327031    9361 out.go:197] Setting JSON to false
I0903 12:29:37.672855    9361 start.go:100] hostinfo: {"hostname":"Nodebes-iMac.local","uptime":11877,"bootTime":1599120700,"procs":306,"os":"darwin","platform":"darwin","platformFamily":"","platformVersion":"10.15.6","kernelVersion":"19.6.0","virtualizationSystem":"","virtualizationRole":"","hostid":"1d3a0f3d-d908-397b-bd16-8f48c0823a2e"}
W0903 12:29:37.673008    9361 start.go:108] gopshost.Virtualization returned error: not implemented yet
I0903 12:29:38.007120    9361 out.go:105] 😄  minikube v1.12.3 on Darwin 10.15.6
😄  minikube v1.12.3 on Darwin 10.15.6
I0903 12:29:38.007281    9361 notify.go:125] Checking for updates...
I0903 12:29:38.162770    9361 out.go:105]     ▪ KUBECONFIG=/Users/nodebe/admin.conf
    ▪ KUBECONFIG=/Users/nodebe/admin.conf
I0903 12:29:38.210805    9361 driver.go:287] Setting default libvirt URI to qemu:///system
I0903 12:29:40.089253    9361 docker.go:87] docker version: linux-19.03.12
I0903 12:29:40.418959    9361 out.go:105] ✨  Using the docker driver based on existing profile
✨  Using the docker driver based on existing profile
I0903 12:29:40.419033    9361 start.go:232] selected driver: docker
I0903 12:29:40.419057    9361 start.go:638] validating driver "docker" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.11@sha256:6fee59db7d67ed8ae6835e4bcb02f32056dc95f11cb369c51e352b62dd198aa0 Memory:1991 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s}
I0903 12:29:40.419314    9361 start.go:649] status for docker: {Installed:true Healthy:true NeedsImprovement:false Error:<nil> Fix: Doc:}
I0903 12:29:40.419508    9361 cli_runner.go:109] Run: docker system info --format "{{json .}}"
I0903 12:29:42.918784    9361 cli_runner.go:151] Completed: docker system info --format "{{json .}}": (2.499316736s)
W0903 12:29:43.038304    9361 out.go:151] ❗  Requested memory allocation (1991MB) is less than the recommended minimum 2000MB. Kubernetes may crash unexpectedly.
❗  Requested memory allocation (1991MB) is less than the recommended minimum 2000MB. Kubernetes may crash unexpectedly.
I0903 12:29:43.042143    9361 start_flags.go:344] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.11@sha256:6fee59db7d67ed8ae6835e4bcb02f32056dc95f11cb369c51e352b62dd198aa0 Memory:1991 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s}
I0903 12:29:43.519107    9361 out.go:105] 👍  Starting control plane node minikube in cluster minikube
👍  Starting control plane node minikube in cluster minikube
I0903 12:29:43.778274    9361 image.go:92] Found gcr.io/k8s-minikube/kicbase:v0.0.11@sha256:6fee59db7d67ed8ae6835e4bcb02f32056dc95f11cb369c51e352b62dd198aa0 in local docker daemon, skipping pull
I0903 12:29:43.806699    9361 cache.go:113] gcr.io/k8s-minikube/kicbase:v0.0.11@sha256:6fee59db7d67ed8ae6835e4bcb02f32056dc95f11cb369c51e352b62dd198aa0 exists in daemon, skipping pull
I0903 12:29:43.806737    9361 preload.go:97] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0903 12:29:43.806815    9361 preload.go:105] Found local preload: /Users/nodebe/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v5-v1.18.3-docker-overlay2-amd64.tar.lz4
I0903 12:29:43.811176    9361 cache.go:51] Caching tarball of preloaded images
I0903 12:29:43.811254    9361 preload.go:131] Found /Users/nodebe/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v5-v1.18.3-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0903 12:29:43.811265    9361 cache.go:54] Finished verifying existence of preloaded tar for  v1.18.3 on docker
I0903 12:29:43.816310    9361 profile.go:150] Saving config to /Users/nodebe/.minikube/profiles/minikube/config.json ...
I0903 12:29:43.845957    9361 cache.go:181] Successfully downloaded all kic artifacts
I0903 12:29:43.882514    9361 start.go:244] acquiring machines lock for minikube: {Name:mk078aa7b711d82f0adc07644f64d078a6493809 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0903 12:29:43.936313    9361 start.go:248] acquired machines lock for "minikube" in 53.721338ms
I0903 12:29:43.936373    9361 start.go:89] Skipping create...Using existing machine configuration
I0903 12:29:43.936384    9361 fix.go:53] fixHost starting: 
I0903 12:29:43.936711    9361 cli_runner.go:109] Run: docker container inspect minikube --format={{.State.Status}}
I0903 12:29:43.973973    9361 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0903 12:29:43.974015    9361 fix.go:131] unexpected machine state, will restart: <nil>
I0903 12:29:44.413537    9361 out.go:105] 🏃  Updating the running docker "minikube" container ...
🏃  Updating the running docker "minikube" container ...
I0903 12:29:44.413578    9361 machine.go:88] provisioning docker machine ...
I0903 12:29:44.449618    9361 ubuntu.go:166] provisioning hostname "minikube"
I0903 12:29:44.523741    9361 cli_runner.go:109] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0903 12:29:44.669525    9361 main.go:115] libmachine: Using SSH client type: native
I0903 12:29:44.669628    9361 main.go:115] libmachine: <nil>
I0903 12:29:44.680245    9361 machine.go:91] provisioned docker machine in 256.064362ms
I0903 12:29:44.680305    9361 fix.go:55] fixHost completed within 743.949987ms
I0903 12:29:44.680313    9361 start.go:76] releasing machines lock for "minikube", held for 743.998331ms
W0903 12:29:44.680416    9361 out.go:151] 🤦  StartHost failed, but will try again: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory
🤦  StartHost failed, but will try again: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory
I0903 12:29:49.681356    9361 start.go:244] acquiring machines lock for minikube: {Name:mk078aa7b711d82f0adc07644f64d078a6493809 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0903 12:29:49.681505    9361 start.go:248] acquired machines lock for "minikube" in 117.364µs
I0903 12:29:49.681538    9361 start.go:89] Skipping create...Using existing machine configuration
I0903 12:29:49.681545    9361 fix.go:53] fixHost starting: 
I0903 12:29:49.681877    9361 cli_runner.go:109] Run: docker container inspect minikube --format={{.State.Status}}
I0903 12:29:49.755461    9361 fix.go:105] recreateIfNeeded on minikube: state=Running err=<nil>
W0903 12:29:49.755496    9361 fix.go:131] unexpected machine state, will restart: <nil>
I0903 12:29:50.009099    9361 out.go:105] 🏃  Updating the running docker "minikube" container ...
🏃  Updating the running docker "minikube" container ...
I0903 12:29:50.009147    9361 machine.go:88] provisioning docker machine ...
I0903 12:29:50.009184    9361 ubuntu.go:166] provisioning hostname "minikube"
I0903 12:29:50.009306    9361 cli_runner.go:109] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I0903 12:29:50.047654    9361 main.go:115] libmachine: Using SSH client type: native
I0903 12:29:50.047705    9361 main.go:115] libmachine: <nil>
I0903 12:29:50.047714    9361 machine.go:91] provisioned docker machine in 38.563105ms
I0903 12:29:50.047735    9361 fix.go:55] fixHost completed within 366.205223ms
I0903 12:29:50.047740    9361 start.go:76] releasing machines lock for "minikube", held for 366.238631ms
W0903 12:29:50.047844    9361 out.go:151] 😿  Failed to start docker container. "minikube start" may fix it: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory
😿  Failed to start docker container. "minikube start" may fix it: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory
I0903 12:29:50.179582    9361 exit.go:58] WithError(error provisioning host)=Failed to start host: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory called from:
goroutine 1 [running]:
runtime/debug.Stack(0x73552f206e65706f, 0x45203a6e6f697369, 0x74656720726f7272)
	/usr/local/Cellar/go/1.14.7/libexec/src/runtime/debug/stack.go:24 +0x9d
k8s.io/minikube/pkg/minikube/exit.WithError(0x57d52dc, 0x17, 0x5af51c0, 0xc0005a4460)
	/private/tmp/minikube-20200812-94589-17snemo/pkg/minikube/exit/exit.go:58 +0x34
k8s.io/minikube/cmd/minikube/cmd.runStart(0x6926240, 0xc0004ac2e0, 0x0, 0x1)
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/start.go:175 +0xe42
github.com/spf13/cobra.(*Command).execute(0x6926240, 0xc0004ac2d0, 0x1, 0x1, 0x6926240, 0xc0004ac2d0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x6925280, 0x0, 0x1, 0xc00055e5e0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/cmd/root.go:106 +0x72c
main.main()
	/private/tmp/minikube-20200812-94589-17snemo/cmd/minikube/main.go:71 +0x11f
W0903 12:29:50.179784    9361 out.go:258] error provisioning host: Failed to start host: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory
W0903 12:29:50.179832    9361 out.go:151] 

W0903 12:29:50.179890    9361 out.go:151] 💣  error provisioning host: Failed to start host: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory
💣  error provisioning host: Failed to start host: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory
W0903 12:29:50.179910    9361 out.go:151] 

W0903 12:29:50.179924    9361 out.go:151] 😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
W0903 12:29:50.179952    9361 out.go:151] 👉  https://github.com/kubernetes/minikube/issues/new/choose
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**
  minikube v1.12.3 on Darwin 10.15.6
    ▪ KUBECONFIG=/Users/nodebe/admin.conf
✨  Using the docker driver based on existing profile
❗  Requested memory allocation (1991MB) is less than the recommended minimum 2000MB. Kubernetes may crash unexpectedly.
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running docker "minikube" container ...
🤦  StartHost failed, but will try again: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory
🏃  Updating the running docker "minikube" container ...
😿  Failed to start docker container. "minikube start" may fix it: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory

💣  error provisioning host: Failed to start host: provision: Error getting config for native Go SSH: open /Users/nodebe/.minikube/machines/minikube/id_rsa: no such file or directory

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by okwunna** [comment]
I can't get minkube to start

**Comment by tstromberg** [comment]
Does `minikube delete` fix it?

**Comment by tstromberg** [comment]
I recommend upgrading to minikube v1.13 and running `minikube delete` to clear the old state.
