### ISSUE TITLE
Remote access of API out of virtualbox VM (ubuntu server 18.04)

### ISSUE THREAD

**Issue by maelfosso** [kubernetes/minikube#9187]
**Steps to reproduce the issue:** 

1. Minikube install in Virtuabox (Ubuntu Server 18.04)
2. Minikube start with docker driver (Docker install in the VM)
3. kubectl proxy

**Full output of failed command:** 

After running `kubectl proxy`, I wanted to access to the API using `curl http://ip-of-vm:8001` from outside the VMs.
I open the port **8001** using `sudo ufw allow 8001` but nothing.

**Full output of `minikube start` command used, if not already included:**
```sh
minikube start --driver=docker
```

**Optional: Full output of `minikube logs` command:**

How to remotely access to the API outside of VMs but from a computer into the same network?

**Comment by priyawadhwa** [comment]
Hey @maelfosso thanks for opening this issue. Have you tried using the `minikube dashboard` command? It will allow you to access the k8s dashboard and will open it in a browser on your machine. You should be able to access the k8s API from there as well.

**Comment by medyagh** [comment]
@maelfosso for security reasons we do not support remote access by default, however you can setup SSH port forwarding on your own ! 


does that answer your question ?
