### ISSUE TITLE
hyperv tunnel: error creating tunnel: another tunnel is already running, shut it down first

### ISSUE THREAD

**Issue by Bjohnson131** [kubernetes/minikube#9188]
**Steps to reproduce the issue:** 

1. minikube start
2.  [commands to start resource of type LoadBalancer]
3. minikube tunnel
4. [wait some time]
5. minikube tunnel

**Full output of failed command:** 

I0904 15:57:31.709164   21148 mustload.go:64] Loading cluster: minikube
I0904 15:57:31.712164   21148 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0904 15:57:32.639094   21148 main.go:110] libmachine: [stdout =====>] : Running

I0904 15:57:32.639094   21148 main.go:110] libmachine: [stderr =====>] :
I0904 15:57:32.639960   21148 host.go:65] Checking if "minikube" exists ...
I0904 15:57:32.639960   21148 api_server.go:145] Checking apiserver status ...
I0904 15:57:32.649974   21148 ssh_runner.go:148] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
I0904 15:57:32.649974   21148 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0904 15:57:33.479020   21148 main.go:110] libmachine: [stdout =====>] : Running

I0904 15:57:33.479020   21148 main.go:110] libmachine: [stderr =====>] :
I0904 15:57:33.480031   21148 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0904 15:57:34.563982   21148 main.go:110] libmachine: [stdout =====>] : 172.17.59.205

I0904 15:57:34.563982   21148 main.go:110] libmachine: [stderr =====>] :
I0904 15:57:34.564798   21148 sshutil.go:44] new ssh client: &{IP:172.17.59.205 Port:22 SSHKeyPath:C:\Users\Brice_Johnson\.minikube\machines\minikube\id_rsa Username:docker}
I0904 15:57:34.662328   21148 ssh_runner.go:188] Completed: sudo pgrep -xnf kube-apiserver.*minikube.*: (2.0123413s)
I0904 15:57:34.681365   21148 ssh_runner.go:148] Run: sudo egrep ^[0-9]+:freezer: /proc/3987/cgroup
I0904 15:57:34.686331   21148 api_server.go:161] apiserver freezer: "4:freezer:/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod167c1607dcb766f2a177b7cfde09cdbf.slice/docker-7ed30cf485861844700edeef26d12b528cb529855dadb0e939d1d215c95b3775.scope"
I0904 15:57:34.698359   21148 ssh_runner.go:148] Run: sudo cat /sys/fs/cgroup/freezer/kubepods.slice/kubepods-burstable.slice/kubepods-burstable-pod167c1607dcb766f2a177b7cfde09cdbf.slice/docker-7ed30cf485861844700edeef26d12b528cb529855dadb0e939d1d215c95b3775.scope/freezer.state
I0904 15:57:34.702326   21148 api_server.go:183] freezer state: "THAWED"
I0904 15:57:34.702326   21148 api_server.go:193] Checking apiserver healthz at https://172.17.59.205:8443/healthz ...
I0904 15:57:34.707325   21148 api_server.go:213] https://172.17.59.205:8443/healthz returned 200:
ok
I0904 15:57:34.707325   21148 tunnel.go:56] Checking for tunnels to cleanup...
I0904 15:57:34.708327   21148 tunnel_manager.go:138] ID { Route: 10.96.0.0/12 -> 172.17.59.205, machineName: minikube, Pid: 15916 } is running: true
I0904 15:57:34.745610   21148 host.go:65] Checking if "minikube" exists ...
I0904 15:57:34.746613   21148 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0904 15:57:35.584093   21148 main.go:110] libmachine: [stdout =====>] : Running

I0904 15:57:35.584093   21148 main.go:110] libmachine: [stderr =====>] :
I0904 15:57:35.586104   21148 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0904 15:57:36.464710   21148 main.go:110] libmachine: [stdout =====>] : Running

I0904 15:57:36.464710   21148 main.go:110] libmachine: [stderr =====>] :
I0904 15:57:36.465469   21148 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
I0904 15:57:37.503606   21148 main.go:110] libmachine: [stdout =====>] : 172.17.59.205

I0904 15:57:37.503606   21148 main.go:110] libmachine: [stderr =====>] :
I0904 15:57:37.504361   21148 exit.go:58] WithError(error starting tunnel)=error creating tunnel: another tunnel is already running, shut it down first: ID { Route: 10.96.0.0/12 -> 172.17.59.205, machineName: minikube, Pid: 15916 } called from:
goroutine 1 [running]:
runtime/debug.Stack(0xc00096b9c8, 0x16eb92e, 0x1b48b84)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa4
k8s.io/minikube/pkg/minikube/exit.WithError(0x1b40ac0, 0x15, 0x1e15a40, 0xc00073c140)
        /app/pkg/minikube/exit/exit.go:58 +0x3b
k8s.io/minikube/cmd/minikube/cmd.glob..func28(0x2b6c9e0, 0xc0004650e0, 0x0, 0x1)
        /app/cmd/minikube/cmd/tunnel.go:99 +0x843
github.com/spf13/cobra.(*Command).execute(0x2b6c9e0, 0xc0004650d0, 0x1, 0x1, 0x2b6c9e0, 0xc0004650d0)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0x2b710c0, 0x0, 0x0, 0xc000118601)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x350
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
        /app/cmd/minikube/cmd/root.go:112 +0x6f5
main.main()
        /app/cmd/minikube/main.go:66 +0xf1
W0904 15:57:37.505358   21148 out.go:201] error starting tunnel: error creating tunnel: another tunnel is already running, shut it down first: ID { Route: 10.96.0.0/12 -> 172.17.59.205, machineName: minikube, Pid: 15916 }
*
X error starting tunnel: error creating tunnel: another tunnel is already running, shut it down first: ID { Route: 10.96.0.0/12 -> 172.17.59.205, machineName: minikube, Pid: 15916 }
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

<details>
minikube reports that process PID 15916 is responsible for the minikube tunnel, but PID 15916 neither exists on the host machine or the guest VM. I'm guessing that this existed at some point, but the information is stale.

</details>

**Comment by tstromberg** [comment]
Can you see what is running at pid 15916?

**Comment by tuskiomi** [comment]
> Can you see what is running at pid 15916?

That's just it, as said above, neither inside the Minikube VM nor inside the host OS does PID 15916 exist as a valid process.

**Comment by tstromberg** [comment]
OK. Do you mind clarifying this :

```
minikube tunnel
[wait some time]
minikube tunnel
```

When you say "wait some time", does this mean that the first tunnel was closed, or that you waited time, and started a second tunnel command?

My guess is that the first tunnel may have exited in a way that prevented it from cleaning up before termination, followed by a bug with how we interpret `os.FindProcess(pid)`.  If that is the case, `minikube tunnel -c` (cleanup) would likely help in this situation.

**Comment by tstromberg** [comment]
If you do run into this again, could you provide the output of:

`tasklist /fi "pid eq 15916" `

One thing that I do notice is that the pid detection code is sub-optimal: if the pid file is found, it will declare success if any process is at that same pid later: it doesn't check if the process is actually a minikube tunnel.

**Comment by tuskiomi** [comment]
@tstromberg Here's the output

```
C:\WINDOWS\system32>tasklist /fi "pid eq 15916"
INFO: No tasks are running which match the specified criteria.
```

**Comment by tuskiomi** [comment]
So, By wait some time, I was executing kubectl commands to query service ports and IPs, but nothing else.

**Comment by priyawadhwa** [comment]
Hey @tuskiomi so during that time that you were executing kubectl commands, did you kill the first `minikube tunnel` command, or was it running the entire time?

**Comment by Bjohnson131** [comment]
This was a user error. I used CTRL - Z to 'terminate' previous tunnels, keeping the port bound.

**Comment by cshashankk** [comment]
I had run into this problem (on Mac) after I had enabled 'ingress' addon. I disabled it. Deleted minikube and restarted minikube without the --vm=true. It's working now.

**Comment by Qwiko** [comment]
I had this issue after an unexpected reboot of my device.
I found here: https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/tunnel.go#L134
that minikube tunnel is searching for a ".tunnel_lock" file. I found that file in my minikube profile and removed it manually and could run minikube tunnel again.
