### ISSUE TITLE
Typo in "version --help"

### ISSUE THREAD

**Issue by cowwoc** [kubernetes/minikube#9191]
When I run `minikube version --help` I get:

```
Print the version of minikube.

Options:
  -o, --output='': One of 'yaml' or 'json'.
      --short=false: Print just the version number.

Usage:
  minikube version [flags] [options]

Use "minikube options" for a list of global command-line options (applies to all commands).
```

But `--short=false` does not `Print just the version number`. It does the opposite. I am expecting the help to read `--short=true: Print just the version number.`

**Comment by afbjorklund** [comment]
Not really a typo, unfortunately. But a bug in the underlying library: #8301

**Comment by cowwoc** [comment]
Agreed. Closing :)
