### ISSUE TITLE
Target of git tag v1.13.0 changed

### ISSUE THREAD

**Issue by SMillerDev** [kubernetes/minikube#9196]
Is the retag of 1.13 intentional? The homebrew maintainers would like to know before we point to the new commit.

---

**Steps to reproduce the issue:** 

1. Check the defined commit belonging to the 1.13 tag in [homebrew](https://github.com/Homebrew/homebrew-core/blob/master/Formula/minikube.rb)
2. See that it differs from the current commit in the 1.13 tag
3. ???
4. profit

**Full output of failed command:** 
Not applicable

**Full output of `minikube start` command used, if not already included:**
Not applicable

**Comment by afbjorklund** [comment]
https://github.com/Homebrew/linuxbrew-core/commit/2ffb4e70d7398fae18cb8d66105e7e3204fc19de

**Comment by SMillerDev** [comment]
That's the commit where it was merged into linuxbrew and at the time the tag still pointed to that commit (Otherwise CI would fail and we won't merge)

**Comment by afbjorklund** [comment]
We have some other issues with the release scripts (#9074), so this could be related to the same underlying problem...

**Comment by SMillerDev** [comment]
Unless the release script creates and deletes the git tags I don't think that's related. Brew will just check out the repo during the build and doesn't actually use the provided releases.

**Comment by afbjorklund** [comment]
I'm guessing human error, but probably a README somewhere that could need some updating. Doesn't look like any code changes, when comparing the commits (above).

**Comment by afbjorklund** [comment]
More info: https://git-scm.com/docs/git-tag#_on_re_tagging

**Comment by noelleleigh** [comment]
Also, will there be release notes written for v1.13.0?

**Comment by sharifelgamal** [comment]
The release script had a bug in it (indeed, it the change Anders pointed out above) that caused the release process to halt midway. I did my best to clean everything up, but yeah, the newest commit should be the one we point at. Fortunately, there should be no functional change between the two commit.

I'll get the release notes fixed up today.

**Comment by afbjorklund** [comment]
@SMillerDev : hopefully that explanation was good enough ? https://github.com/kubernetes/minikube/releases/tag/v1.13.0

**Comment by SMillerDev** [comment]
Yeah, just wanted to make sure it wasn't malicious.

**Comment by afbjorklund** [comment]
Revision was fixed in https://github.com/Homebrew/homebrew-core/commit/d6268ceecdc42392a10339f3c62e019a9de94168

**Comment by noelleleigh** [comment]
So, can this issue be closed now?

**Comment by SMillerDev** [comment]
From my perspective, yes.
