### ISSUE TITLE
Exiting due to DRV_CP_ENDPOINT on Win10 with turned ON Virtualization

### ISSUE THREAD

**Issue by stupidlamo** [kubernetes/minikube#9197]
**Steps to reproduce the issue:** 

1. minikube start --no-vtx-check --container-runtime=cri-o
2. minikube ssh

**Full output of failed command:** 
PS C:\WINDOWS\system32> minikube ssh --alsologtostderr
I0907 22:50:48.477936   17960 mustload.go:66] Loading cluster: minikube
I0907 22:50:48.478915   17960 main.go:115] libmachine: COMMAND: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe showvminfo minikube --machinereadable
I0907 22:50:48.582423   17960 main.go:115] libmachine: STDOUT:
{
name="minikube"
groups="/"
ostype="Linux 2.6 / 3.x / 4.x (64-bit)"
UUID="80462bf4-863a-4f80-a2a0-8857f3a700b0"
CfgFile="C:\\Users\\username\\.minikube\\machines\\minikube\\minikube\\minikube.vbox"
SnapFldr="C:\\Users\\username\\.minikube\\machines\\minikube\\minikube\\Snapshots"
LogFldr="C:\\Users\\username\\.minikube\\machines\\minikube\\minikube\\Logs"
hardwareuuid="80462bf4-863a-4f80-a2a0-8857f3a700b0"
memory=2200
pagefusion="off"
vram=8
cpuexecutioncap=100
hpet="on"
cpu-profile="host"
chipset="piix3"
firmware="BIOS"
cpus=2
pae="on"
longmode="on"
triplefaultreset="off"
apic="on"
x2apic="off"
nested-hw-virt="off"
cpuid-portability-level=0
bootmenu="disabled"
boot1="dvd"
boot2="dvd"
boot3="disk"
boot4="none"
acpi="on"
ioapic="on"
biosapic="apic"
biossystemtimeoffset=0
rtcuseutc="on"
hwvirtex="on"
nestedpaging="on"
largepages="on"
vtxvpid="on"
vtxux="on"
paravirtprovider="default"
effparavirtprovider="kvm"
VMState="running"
VMStateChangeTime="2020-09-07T19:46:21.041000000"
graphicscontroller="vboxvga"
monitorcount=1
accelerate3d="off"
accelerate2dvideo="off"
teleporterenabled="off"
teleporterport=0
teleporteraddress=""
teleporterpassword=""
tracing-enabled="off"
tracing-allow-vm-access="off"
tracing-config=""
autostart-enabled="off"
autostart-delay=0
defaultfrontend=""
vmprocpriority="default"
storagecontrollername0="SATA"
storagecontrollertype0="IntelAhci"
storagecontrollerinstance0="0"
storagecontrollermaxportcount0="30"
storagecontrollerportcount0="30"
storagecontrollerbootable0="on"
"SATA-0-0"="C:\Users\username\.minikube\machines\minikube\boot2docker.iso"
"SATA-ImageUUID-0-0"="0f5d4e21-6954-44e8-8ad8-6ddb156f9f14"
"SATA-tempeject"="off"
"SATA-IsEjected"="off"
"SATA-1-0"="C:\Users\username\.minikube\machines\minikube\disk.vmdk"
"SATA-ImageUUID-1-0"="280f8bd3-2c61-4b9c-a0b1-bb2f7d69bc84"
"SATA-2-0"="none"
"SATA-3-0"="none"
"SATA-4-0"="none"
"SATA-5-0"="none"
"SATA-6-0"="none"
"SATA-7-0"="none"
"SATA-8-0"="none"
"SATA-9-0"="none"
"SATA-10-0"="none"
"SATA-11-0"="none"
"SATA-12-0"="none"
"SATA-13-0"="none"
"SATA-14-0"="none"
"SATA-15-0"="none"
"SATA-16-0"="none"
"SATA-17-0"="none"
"SATA-18-0"="none"
"SATA-19-0"="none"
"SATA-20-0"="none"
"SATA-21-0"="none"
"SATA-22-0"="none"
"SATA-23-0"="none"
"SATA-24-0"="none"
"SATA-25-0"="none"
"SATA-26-0"="none"
"SATA-27-0"="none"
"SATA-28-0"="none"
"SATA-29-0"="none"
natnet1="nat"
macaddress1="0800275FBBF1"
cableconnected1="on"
nic1="nat"
nictype1="virtio"
nicspeed1="0"
mtu="0"
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
Forwarding(0)="ssh,tcp,127.0.0.1,52111,,22"
hostonlyadapter2="VirtualBox Host-Only Ethernet Adapter #2"
macaddress2="080027137E4D"
cableconnected2="on"
nic2="hostonly"
nictype2="virtio"
nicspeed2="0"
nic3="none"
nic4="none"
nic5="none"
nic6="none"
nic7="none"
nic8="none"
hidpointing="ps2mouse"
hidkeyboard="ps2kbd"
uart1="off"
uart2="off"
uart3="off"
uart4="off"
lpt1="off"
lpt2="off"
audio="dsound"
audio_out="off"
audio_in="off"
clipboard="disabled"
draganddrop="disabled"
SessionName="headless"
VideoMode="720,400,0"@0,0 1
vrde="off"
usb="off"
ehci="off"
xhci="off"
SharedFolderNameMachineMapping1="c/Users"
SharedFolderPathMachineMapping1="\\\\?\\c:\\Users"
VRDEActiveConnection="off"
VRDEClients==0
videocap="off"
videocapaudio="off"
capturescreens=""
capturefilename="C:\\Users\\username\\.minikube\\machines\\minikube\\minikube\\minikube.webm"
captureres="1024x768"
capturevideorate=512
capturevideofps=25
captureopts=""
GuestMemoryBalloon=0
GuestOSType="Linux26_64"
GuestAdditionsRunLevel=0
}
I0907 22:50:48.583436   17960 main.go:115] libmachine: STDERR:
{
}
I0907 22:50:48.587345   17960 host.go:65] Checking if "minikube" exists ...
I0907 22:50:48.593199   17960 out.go:109]

W0907 22:50:48.594140   17960 out.go:145] X Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""
X Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""
W0907 22:50:48.596095   17960 out.go:145] *
*
W0907 22:50:48.597071   17960 out.go:145] * If the above advice does not help, please let us know:
* If the above advice does not help, please let us know:
W0907 22:50:48.600003   17960 out.go:145]   - https://github.com/kubernetes/minikube/issues/new/choose
  - https://github.com/kubernetes/minikube/issues/new/choose
I0907 22:50:48.606871   17960 out.go:109]

**Full output of `minikube start` command used, if not already included:**
* minikube v1.13.0 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.19.0 preload ...
    > preloaded-images-k8s-v6-v1.19.0-cri-o-overlay-amd64.tar.lz4: 551.13 MiB /
* virtualbox "minikube" VM is missing, will recreate.
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...

**Optional: Full output of `minikube logs` command:**
PS C:\WINDOWS\system32> minikube logs

X Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose
<details>

</details>

**Comment by priyawadhwa** [comment]
Hey @stupidlamo thanks for opening this issue. I'm not very familiar with Windows errors, but could you try deleting the cluster and restarting it?

```
minikube delete 
minikube start
```

If you want to try starting from scratch, you could even run:

```
minikube delete --all --purge # Will delete the minikube home directory and all clusters
minikube start
```

Please let us know if you continue to see this error.

**Comment by sharifelgamal** [comment]
Hey @stupidlamo  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!
