### ISSUE TITLE
Unable to start minikube in windows 10 pro

### ISSUE THREAD

**Issue by utdevops** [kubernetes/minikube#9213]
**Steps to reproduce the issue:** 

1. minikube start 
2. getting:  Unable to connect to the server: x509: certificate is valid for 192.168.99.101, 10.96.0.1, 127.0.0.1, 10.0.0.1, not 192.168.99.100
3.i am using windows 10 pro .. it was fine 12 hours ago but now its giving this error 
4. tried multiple times and restarted laptop as well  

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
   minikube start 
* minikube v1.13.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Found network options:
  - NO_PROXY=192.168.99.100,192.168.99.101
  - no_proxy=192.168.99.100,192.168.99.101
* Preparing Kubernetes v1.19.0 on Docker 19.03.12 ...
  - env NO_PROXY=192.168.99.100,192.168.99.101
! Unable to restart cluster, will reset it: apiserver health: controlPlane never updated to v1.19.0
* Verifying Kubernetes components...
! Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.99.100:8443/apis/storage.k8s.io/v1/storageclasses": x509: certificate is valid for 192.168.99.101, 10.96.0.1, 127.0.0.1, 10.0.0.1, not 192.168.99.100]
* Enabled addons: default-storageclass, storage-provisioner

X Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.0
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@utdevops does deleting and starting minikube help ?

/triage needs-information
/triage support

**Comment by joshiste** [comment]
Having the same issue on macOS.
Deleting and starting again didn't help.

deleting `~/.minikube` did help

**Comment by utdevops** [comment]
Yes
Deleting and starting the cluster helped me

Regards
K.Anutnam

**Comment by utdevops** [comment]
Yes i follwed bekow steps and its resolved my issue 
> minikube delete 
> minikube start --vm-driver hyperv    (optional if hyper-v is activated then not required ) if not manually we can use this step  
> minikube start 

Well i updated my windows and acivated hyper-v (its jusy an FYI) however delete and start will solve the issue
