### ISSUE TITLE
VBoxManage: error: Invalid NIC type 'virtio' specified for NIC 1

### ISSUE THREAD

**Issue by strakh-alex** [kubernetes/minikube#9214]
**Steps to reproduce the issue:** 

1. Fedora 32 VirtualBox
2. minikube start

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
 minikube start
😄  minikube v1.13.0 on Fedora 32
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in virtualbox ...
🤦  StartHost failed, but will try again: creating host: create: creating: /usr/bin/VBoxManage modifyvm minikube --nic1 nat --nictype1 virtio --cableconnected1 on failed:
VBoxManage: error: Invalid NIC type 'virtio' specified for NIC 1

🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: creating: /usr/bin/VBoxManage modifyvm minikube --nic1 nat --nictype1 virtio --cableconnected1 on failed:
VBoxManage: error: Invalid NIC type 'virtio' specified for NIC 1

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: /usr/bin/VBoxManage modifyvm minikube --nic1 nat --nictype1 virtio --cableconnected1 on failed:
VBoxManage: error: Invalid NIC type 'virtio' specified for NIC 1

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment]
Normally it is included... Here is what you get on Ubuntu:

```
                            [--nic<1-N> none|null|nat|bridged|intnet|hostonly|
                                        generic|natnetwork]
                            [--nictype<1-N> Am79C970A|Am79C973|Am79C960|
                                            82540EM|82543GC|82545EM|
                                            virtio]
```

So maybe the virtualbox package for Fedora is broken ?

Which version was it ?

**Comment by strakh-alex** [comment]
The VB version is:  6.1.14_RPMFusion r140239
The latest from their repository.
minikube version: v1.13.0

**Comment by afbjorklund** [comment]
You can file a bug report with RPMFusion, if you want them to build with "virtio" support.

To get `minikube start` working, you can use one of the emulated drivers instead:

```
      --host-only-nic-type='virtio': NIC Type used for host only network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
      --nat-nic-type='virtio': NIC Type used for host only network. One of Am79C970A, Am79C973, 82540EM, 82543GC, 82545EM, or virtio (virtualbox driver only)
```

**Comment by afbjorklund** [comment]
Seems to be a small copy/paste typo in the help text there. Oh well.

https://www.virtualbox.org/manual/ch06.html#nichardware

**Comment by poornachandratejasvi** [comment]
even im facing the same error. Can i know how can i fix the issue

**Comment by afbjorklund** [comment]
`--host-only-nic-type=Am79C973 --nat-nic-type=Am79C973`

But please report this rpm bug to the packager (RPMFusion)

**Comment by tstromberg** [comment]
Closing as there is a workaround.

**Comment by afbjorklund** [comment]
Looking at upstream bugs: https://bugzilla.rpmfusion.org/buglist.cgi?component=VirtualBox&product=Fedora

It seems that it is fixed now: https://bugzilla.rpmfusion.org/show_bug.cgi?id=5747 (in VirtualBox-6.1.16-1.fc32)
