### ISSUE TITLE
Minikube Installation with Homebrew fails with Checksum.

### ISSUE THREAD

**Issue by sivaswami** [kubernetes/minikube#9219]
• • • brew install minikube
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
...
Error: v1.13.0 tag should be eeb05350f8ba6ff3a12791fcce350c131cb2ff44
but is actually 0c5e9de4ca6f9c55147ae7f90af97eff5befef5f

**Comment by afbjorklund** [comment]
Same as #9196

**Comment by afbjorklund** [comment]
Probably `brew edit` until the new release is trusted

**Comment by sivaswami** [comment]
Thanks. it works fine now
