### ISSUE TITLE
Mention brew on the linux install page too

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#9226]
From PR #9066:
> Homebrew has supported Linux since a while ago and I've been using it on my Linux environment too :)

Currently we only mention Homebrew (https://brew.sh) for Mac, while it also supports Linux (as "linuxbrew")

`brew install minikube`

**Comment by afbjorklund** [comment]
https://docs.brew.sh/Homebrew-on-Linux

**Comment by afbjorklund** [comment]
Currently blocked by #9196 

```
Error: v1.13.0 tag should be eeb05350f8ba6ff3a12791fcce350c131cb2ff44
but is actually 0c5e9de4ca6f9c55147ae7f90af97eff5befef5f
```

**Comment by xiejiangzhao** [comment]
Same meet this error

**Comment by afbjorklund** [comment]
> Same meet this error

Fix is available in mac brew now, so should appear in linux brew too soon...

You can either change it yourself, or cherry-pick the commit (d6268ceecd)

**Comment by medyagh** [comment]
till we figure out what is the miantaince flow for this we should hold on this

**Comment by afbjorklund** [comment]
> till we figure out what is the miantaince flow for this we should hold on this

I guess we close this PR then ?
