### ISSUE TITLE
hyperv: StartVM failed

### ISSUE THREAD

**Issue by smuve1** [kubernetes/minikube#9242]
**Steps to reproduce the issue:** 

1. Run powershell as admin
2. minikube start --vm-driver hyperv --hyperv-virtual-switch "Default Switch" --cpus 6 --memory 4096
3. minikube delete
4. same result after re-running start command

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
* minikube v1.13.0 on Microsoft Windows 10 Enterprise 10.0.17134 Build 17134
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing hyperv VM for "minikube" ...
E0914 08:00:31.919081    4284 main.go:111] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start. (Virtual machine ID AAFE155D-F547-4B98-94AD-E653A8B59390)
'minikube' failed to start worker process: The process terminated unexpectedly. (0x8007042B). (Virtual machine ID
AAFE155D-F547-4B98-94AD-E653A8B59390)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

! StartHost failed, but will try again: driver start: exit status 1
* Restarting existing hyperv VM for "minikube" ...
E0914 08:00:40.638867    4284 main.go:111] libmachine: [stderr =====>] : Hyper-V\Start-VM : 'minikube' failed to start. (Virtual machine ID AAFE155D-F547-4B98-94AD-E653A8B59390)
'minikube' failed to start worker process: The process terminated unexpectedly. (0x8007042B). (Virtual machine ID
AAFE155D-F547-4B98-94AD-E653A8B59390)
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : OperationFailed,Microsoft.HyperV.PowerShell.Commands.StartVM

* Failed to start hyperv VM. Running "minikube delete" may fix it: driver start: exit status 1

X Exiting due to GUEST_PROVISION: Failed to start host: driver start: exit status 1
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Hey @smuve1, sorry for the bad experience here. Could you rerun your `minikube start` command and add `-v=5 --alsologtostderr` to the end of it? That'll help us narrow down the issue you're having.

It's clear that HyperV is failing to start up a VM, but it's not clear why yet.

**Comment by ilya-zuyev** [comment]
@smuve1 do you mind to try to reproduce this issue with the minikube version 1.14.2 and post `-v=5` logs if the problem still exists?

**Comment by priyawadhwa** [comment]
Hey @smuve1  -- hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.

Thank you for sharing your experience!
