### ISSUE TITLE
minicube start: Exiting due to GUEST_START

### ISSUE THREAD

**Issue by princekumar294** [kubernetes/minikube#9245]
**Steps to reproduce the issue:** 

1.Unable to restart cluster, will reset it: getting k8s client: client config: client config: error loading config file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
2. Exiting due to GUEST_START: Failed kubeconfig update: Error reading file "/etc/rancher/k3s/k3s.yaml": open /etc/rancher/k3s/k3s.yaml: permission denied
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
It sounds like you have a KUBECONFIG environment variable setup, but minikube is unable to update it. Could you include the full output of `minikube start`?
