### ISSUE TITLE
improve message, when there is profile name other than "minikube"

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9247]
I only have one cluster, called ```functional-20200910153511-83042```

```
medya@~/workspace/g1 $ minikube profile list
|---------------------------------|-----------|---------|------------|------|---------|---------|
|             Profile             | VM Driver | Runtime |     IP     | Port | Version | Status  |
|---------------------------------|-----------|---------|------------|------|---------|---------|
| functional-20200910153511-83042 | docker    | docker  | 172.17.0.3 | 8441 | v1.19.0 | Running |
|---------------------------------|-----------|---------|------------|------|---------|--------
```

when I run minikube ssh I get this error:
```
medya@~/workspace/g1 $ minikube ssh
🤷  There is no local cluster named "minikube"
👉  To fix this, run: "minikube start"
```

it would be better that we tell them,
```
"Profile "Y" was not found. You have a profile named X, did you mean to use that?"
```

**Comment by tstromberg** [comment]
@A-Hilaly - are you still working on this?

**Comment by sachinkumarsingh092** [comment]
As the default profile is `minikube", Profile Y will always be "minikube"`. I just have to display the name of the existing cluster profile which is Profile X. 
Also, should I remove the message `"There is no local cluster named "minikube""` from above and insert `"Profile "Y" was not found. You have a profile named X, did you mean to use that?"` message instead or is it an additional mesage with the existing one?

**Comment by A-Hilaly** [comment]
@tstromberg No enough progress to send a PR, i don't expect to have anytime this week. Please feel free to reassign if someone can ship it faster :)
/unassign
