### ISSUE TITLE
Create Addon To Mount Google Application Default Credentials Into Minikube

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/minikube#925]
Similar to #366, there should be an easy/automatic way of mounting Google Application Default credentials into minikube so that users can more easily pull images from the Google Cloud Registry

**Comment by dlorenc** [comment]
@aaron-prindle is experimenting with adding google ADC support to https://github.com/upmc-enterprises/awsecr-creds

**Comment by dlorenc** [comment]
cc @stevesloka would you be open to a PR adding Google ADC to your repo if @aaron-prindle gets it working?

**Comment by stevesloka** [comment]
Hey @dlorenc no problems adding Google support. I could maybe rename the project to something more generic to not make it confusing. Also could add quay.io support possibly if there is interest there. 

What do you think? I'm also happy to help out as I can with any coding, etc.

**Comment by aaron-prindle** [comment]
Ref: https://github.com/upmc-enterprises/awsecr-creds/pull/23

**Comment by aaron-prindle** [comment]
Documentation PR here: https://github.com/upmc-enterprises/awsecr-creds/pull/25

**Comment by aaron-prindle** [comment]
@stevesloka Would it be possible to rename the repo to avoid confusion?  Also let me know if hosting the container image for the addon becomes an issue, the minikube team could alternatively host it.

**Comment by stevesloka** [comment]
Hey @aaron-prindle I renamed the repo and merged in your PR. Also have a PR #1001 to rename in minikube and push the updated version of the manifest. 

Is there a way in minikube to update deployments? I guess you could just disable and re-enable the addon.

**Comment by aaron-prindle** [comment]
@stevesloka Thanks!  I have merged in #1001.  I believe that the easiest way to update the addon for users would be to disable and re-enable it as you suggested.

**Comment by stevesloka** [comment]
Sweet! Also in regards to hosting the image, right now it's just on docker hub, I'm happy to update there, but if it would reside better with you let me know and we can work it out.

**Comment by aaron-prindle** [comment]
Closing, PR's are in for this.
