### ISSUE TITLE
Idle network connection killed after 5 minutes.

### ISSUE THREAD

**Issue by Kristof-Mattei** [kubernetes/minikube#9257]
**Steps to reproduce the issue:** 

We have an application that sends data to an external system for processing. 

`(app) POD -> External System`

When the application has sent the last bit, there can be a significant delay until the External System replies back. 

This is causing issues, as somewhere around the 5 minute mark our application receives a `TCP FIN ACK` from the External System. 

Monitoring outside of the cluster it seems that the Kubernetes Process sends a `TCP FIN` to the External System, probably because it sees 0 traffic.  Looking at how K8s is set up it looks to be `kube-proxy`, because there are a lot of timeouts that can be set there. I have tried modifying them, but no luck so far. 

Running the app outside of minikube does not show this behavior, it waits until it receives a reply. 

I have updated the app to send a TCP Keep-Alive every minute, which alleviates the issue. 

How do I properly adjust the knobs that minikube (and Kubernetes overall) doesn't shut down my connection? 

Also, is it common for a proxy/translation device to sever connections that fast? 

Edit: it doesn't seem like `kube-proxy` severs the connection, it comes from outside of it.

I listened to traffic on `kube-proxy` and it never send the `FIN`, it only received the `FIN ACK`. 

I traced it down to Docker's `VPNkit.exe`.

**Full output of failed command:** 
The application receives a TCP FIN, which severs the connection, and causes the process to fail.

**Full output of `minikube start` command used, if not already included:**

    # running on WSL!

    minikube start                            
    😄  minikube v1.13.0 on Ubuntu 20.04
    ✨  Using the docker driver based on existing profile
    👍  Starting control plane node minikube in cluster minikube
    🔄  Restarting existing docker container for "minikube" ...
    🐳  Preparing Kubernetes v1.19.0 on Docker 19.03.8 ...
    🔎  Verifying Kubernetes components...
    🌟  Enabled addons: dashboard, default-storageclass, storage-provisioner
    🏄  Done! kubectl is now configured to use "minikube" by default2. 

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by Kristof-Mattei** [comment]
@RA489 This is Docker on WSL, not Linux. 

Also, I can  reproduce this inside of Docker, without Minikube, without WSL. I think I need to move my issue to the Docker repo.

**Comment by sharifelgamal** [comment]
Yeah this strikes me as a docker issue rather than a minikube issue. I'm going to close this for now, but feel free to reopen if it ends up being related to minikube.

**Comment by caio-vinicius** [comment]
@Kristof-Mattei can you please link the issue that you opened up in Docker repository?

**Comment by Kristof-Mattei** [comment]
@caio-vinicius I can't seem to find it either, I think I might have forgotten since I had a workaround.

But I did find this ticket which shows exactly the same behavior: https://github.com/docker/for-win/issues/2639. Sadly not resolved either.
