### ISSUE TITLE
registry-creds: Add support for Google Artifact Registry

### ISSUE THREAD

**Issue by jonjohnsonjr** [kubernetes/minikube#9259]
I'd love to have [Artifact Registry](https://cloud.google.com/artifact-registry) included in the [registry-creds](https://minikube.sigs.k8s.io/docs/handbook/registry/#using-a-private-registry) addon.

Authentication generally works the same way as GCR: https://cloud.google.com/artifact-registry/docs/docker/quickstart#auth

I'm not sure how registry-creds works or how one might go about adding this. If it's not too difficult, I may be able to contribute given some pointers/guidance.

**Comment by medyagh** [comment]
@jonjohnsonjr would be a great feature, I would happy accept a PR that would implements this

**Comment by jonjohnsonjr** [comment]
I have some questions :)

It looks like [this](https://github.com/kubernetes/minikube/blob/83f9bd1df385ae8d1d47a5951c2bc9231bd8358c/cmd/minikube/cmd/config/configure.go#L76-L93) is what prompts the user to configure GCR credentials with the registry-creds addon. Does this only allow one URL for GCR? It appears to be impossible to configure both e.g. gcr.io and asia.gcr.io using this addon. Is that true?

If the above is true, would it be reasonable to just update some strings to indicate that you can supply an Artifact Registry URL instead of a GCR URL?

**Comment by tstromberg** [comment]
@jonjohnsonjr - This code was added 4 years ago, so your guess is as good as anyone else's on the project at the moment. It seems bizarre to me that we wouldn't allow credentials to be provided for all GCR & AR endpoints.

**Comment by medyagh** [comment]
@jonjohnsonjr  we added GCR support for GCP-Auth addon recently, (on HEAD) https://github.com/kubernetes/minikube/pull/10853

**Comment by medyagh** [comment]
@jonjohnsonjr we added GCR support for GCP-Auth addon  #10853

do u mind trying with minikube 1.20.0beta ? and see if that fixes ? we belive we added this feature with ingegration tests

**Comment by sharifelgamal** [comment]
the gcp-auth addon supports artifact registry now.
