### ISSUE TITLE
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes 

### ISSUE THREAD

**Issue by arunsp1007** [kubernetes/minikube#9262]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by arunsp1007** [comment]
minikube delete
* Removing C:\Users\arunkumar.p\.minikube\machines\minikube ...
* Removed all traces of the "minikube" cluster.
PS C:\WINDOWS\system32> minikube start
* minikube v1.13.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Automatically selected the virtualbox driver
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Not in a hypervisor partition (HVP=0) (VERR_NEM_NOT_AVAILABLE).
VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.179164 Power up failed (vrc=VERR_VMX_MSR_ALL_VMX_DISABLED, rc=E_FAIL (0X80004005))
* Failed to start virtualbox VM. Running "minikube delete" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\arunkumar.p\.minikube\machines\minikube\config.json: The system cannot find the file specified.

X Exiting due to GUEST_NOT_FOUND: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\arunkumar.p\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* Suggestion: minikube is missing files relating to your guest environment. This can be fixed by running 'minikube delete'
* Related issue: https://github.com/kubernetes/minikube/issues/9130

**Comment by sharifelgamal** [comment]
`VBoxManage.exe: error: VT-x is disabled in the BIOS for all CPU modes (VERR_VMX_MSR_ALL_VMX_DISABLED)` means that you don't have virtualization enabled. You need to enable VT-x in your BIOS.

**Comment by arunsp1007** [comment]
PS C:\WINDOWS\system32> minikube start --driver=virtualbox
* minikube v1.13.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* virtualbox "minikube" VM is missing, will recreate.
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
! StartHost failed, but will try again: recreate: creating host: create: creating: rename C:\Users\arunkumar.p\.minikube\machines\minikube\boot2docker.iso.tmp912576470 C:\Users\arunkumar.p\.minikube\machines\minikube\boot2docker.iso: Access is denied.
* virtualbox "minikube" VM is missing, will recreate.
* Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: recreate: creating host: create: creating: rename C:\Users\arunkumar.p\.minikube\machines\minikube\boot2docker.iso.tmp818587965 C:\Users\arunkumar.p\.minikube\machines\minikube\boot2docker.iso: Access is denied.

X Exiting due to GUEST_PROVISION: Failed to start host: recreate: creating host: create: creating: rename C:\Users\arunkumar.p\.minikube\machines\minikube\boot2docker.iso.tmp818587965 C:\Users\arunkumar.p\.minikube\machines\minikube\boot2docker.iso: Access is denied.
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by arunsp1007** [comment]
after enablin vt/d in bios got a new issue
