### ISSUE TITLE
minikube start (kvm) "Error starting host: Error creating new host: dial tcp: missing address."

### ISSUE THREAD

**Issue by broady** [kubernetes/minikube#927]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
bug report

**Minikube version** (use `minikube version`):

minikube version: v0.14.0

**Environment**:
- **OS** (e.g. from /etc/os-release): ubuntu trusty
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm, but machines directory is empty
- **Docker version** (e.g. `docker -v`): 1.12.1
- **Install tools**:
- **Others**:

**What happened**:

```
$ minikube config set vm-driver kvm
$ minikube start                                                                                                                                                                                
Starting local Kubernetes cluster...
E1215 20:30:51.804680    3691 start.go:94] Error starting host: Error creating new host: dial tcp: missing address.

 Retrying.
E1215 20:30:51.805291    3691 start.go:100] Error starting host:  Error creating new host: dial tcp: missing address
Exit code 1
```

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:

**Comment by r2d4** [comment]
Hey we've actually seen this problem before and sent a PR upstream to the KVM driver that was merged, however I don't think theres been a recent release of it. (https://github.com/dhiltgen/docker-machine-kvm/pull/18)

The fix is that you need to also install the `libvirt-bin` package on ubuntu

Ref https://github.com/kubernetes/minikube/issues/278

**Comment by broady** [comment]
```
$ sudo apt-get install libvirt-bin
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libvirt-bin is already the newest version (1.2.2-0ubuntu13.1.17).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

Did you mean I also need a new version of the kvm driver?

**Comment by r2d4** [comment]
No, that PR only made the error message clearer.

Have you added yourself to the `libvirtd` group?
You can verify that everything is running properly if you can run `$ virsh -c qemu:///system list`

**Comment by broady** [comment]
I did run `sudo usermod -a -G libvirtd $(whoami)`

```
$ cat /etc/group | grep libvir
libvirtd:x:134:cbro
$  virsh -c qemu:///system list
error: failed to connect to the hypervisor
error: Failed to connect socket to '/var/run/libvirt/libvirt-sock': Permission denied
Exit code 1
```

Oh, but looks like it works in a brand new tty. D'oh.

**Comment by r2d4** [comment]
Closing this, looks like you got it working.  Feel free to reopen if you're still having problems

**Comment by westlakem** [comment]
Any idea how we can fix this moving forward? i'm running on docker and I'm getting the same error "missing address"

**Comment by dlorenc** [comment]
Can you explain a little more what you're trying to do? This bug is about a permission issue when using the KVM driver.

**Comment by Anticom** [comment]
I'm on Ubuntu 16.04 and installed `kubectl` and `minikube` via Ubuntu's `snap` and I get the same errors:
```bash
$ minikube start --vm-driver="kvm"
There is a newer version of minikube available (v0.23.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.23.0
To disable this notification, add WantUpdateNotification: False to the json config file at /home/anticom/snap/minikube/4/.minikube/config
(you may have to create the file config.json in this folder if you have no previous configuration)
Starting local Kubernetes cluster...
E1115 02:25:58.211464    9757 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E1115 02:25:58.222801    9757 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E1115 02:25:58.232688    9757 start.go:83] Error starting host: Error creating new host: dial tcp: missing address. Retrying.
E1115 02:25:58.232710    9757 start.go:89] Error starting host:  Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address
Error creating new host: dial tcp: missing address
```

**Comment by gabrielmancini** [comment]
+1

**Comment by hudsantos** [comment]
+1

**Comment by vrajanap** [comment]
+1

**Comment by wskinner** [comment]
I also have this problem on Ubuntu 14.04.

**Comment by wskinner** [comment]
@r2d4 can you reopen this? Seems like a lot of people are having this issue now.

**Comment by nkashy1** [comment]
+1

- minikube version: `minikube version: v0.26.0`
- OS: Ubuntu 16.04
- VM Driver: `"DriverName": "kvm2",`
- Docker version: `Docker version 18.03.0-ce, build 0520e24`

**Comment by oesgul** [comment]
+1

**Comment by razeone** [comment]
+1

* minikube version: v0.26.1
* OS: Fedora 27
* VM Driver: kvm/kvm2
* Docker version 18.04.0-ce, build 3d479c0

**Comment by jorgerod** [comment]
+1

minikube version: minikube version: v0.26.0
OS: Ubuntu 16.04
VM Driver: "DriverName": "kvm2",
Docker version: Docker version 18.03.0-ce, build 0520e24

**Comment by tjma2001** [comment]
I am having this issue with snap's version of minikube as well. I uninstalled the snap version and performed the installation with 

`curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/`

And the install seems to be proceeding without a hitch

**Comment by ostretsov** [comment]
Had the same issue. The problem was with my group. Make sure you are in libvirt (libvirtd group in 16.04) group: 
```
$ id
uid=1000(artem) gid=133(libvirtd) groups=133(libvirtd),4(adm),24(cdrom),27(sudo),30(dip),46(plugdev),113(lpadmin),128(sambashare),999(docker),1000(artem)
```

**Comment by skis** [comment]
I have the same issue.
Virtual Machine - Ubuntu 18.10.
Tried KVM2 driver and yet. Anyone else experiencing this issue?

**Comment by vds** [comment]
+1

**Comment by Ddper** [comment]
+1

**Comment by alanwds** [comment]
Same here:

Ubuntu 14.04 with KVM2
minikube version: v0.32.0

**Comment by ugurcan377** [comment]
I had the same problem and the solution in this issue worked.
https://github.com/kubernetes/minikube/issues/3437

**Comment by TimZaman** [comment]
Still a problem! Reopen? Ubuntu 16.04 with KVM2.

**Comment by alexellis** [comment]
I'm still getting this issue with Ubuntu 16.04 KVM2 and v0.33.1

**Comment by krilor** [comment]
I've just tried on Linux Mint 18 (based on Ubuntu 16.04) + KVM and got a similar error.

Downgraded to v0.30.0 helped.

**Comment by jvleminc** [comment]
Also happening on Ubuntu 18.04 after a fresh install of minikube.

**Comment by brennen** [comment]
> Also happening on Ubuntu 18.04 after a fresh install of minikube.

Same; oddly I installed Minikube once on an existing Ubuntu system, then had to nuke and pave the machine for unrelated reasons and now find that I'm unable to get Minikube working again from the same instructions.

**Comment by kasvith** [comment]
Same issue, but using a new terminal or tty fixed issue for me

**Comment by chaitanyanettem** [comment]
For now on ubuntu 16.04, you can also get around this by installing virtualbox (`sudo apt-get install virtualbox`).

You can then start minikube with `minikube start` and it just works.

**Comment by sblcook** [comment]
This is still happening to me on minikube v1.1.0. Opening another terminal doesn't seem to help, but I am included in the ```libvirtd``` group.

**OS**: Ubuntu 16.04
**VM Driver**: kvm
**Docker version**: 18.06.0-ce,

**Comment by ngmariusz** [comment]
same here ( https://github.com/kubernetes/minikube/issues/4416 )

**Comment by Maxiaoyu0** [comment]
use this one sudo minikube start --registry-mirror=https://registry.docker-cn.com --docker-env HTTP_PROXY=http://proxy-ip:port --docker-env HTTPS_PROXY=http://proxy-ip:port

**Comment by Maxiaoyu0** [comment]
use this (sudo minikube start --registry-mirror=https://registry.docker-cn.com --docker-env HTTP_PROXY=http://proxy-ip:port --docker-env HTTPS_PROXY=http://proxy-ip:port)

**Comment by kpooja20** [comment]
same problem after installing  libvirt.

**Comment by afbjorklund** [comment]
For anyone else having the same issue, please check that you are in the group and that libraries are ok.

`id` should include "libvirtd", and for instance `ldd` should *not* show "version `LIBVIRT_3.0.0' not found"

Issue itself will soon be fixed in minikube 1.3.0 (#4555)

It was _supposed_ to be fixed in minikube 1.0.0 (#3689)

**Comment by bezna-hack** [comment]
os: linux mint 19
minikube v1.6.2
vm driver: kvm
docker v19.03

I experienced the same issue after installing minikube with snap. For me the solution was to remove the snap install and delete the /snap/minikube folder and then install minikube wirh:

curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
   && sudo install minikube-linux-amd64 /usr/local/bin/minikube

This is pretty odd since snap is suggested in the official documentation.
I also had to install docker-machine.

**Comment by MykytaLiubshin** [comment]
> I am having this issue with snap's version of minikube as well. I uninstalled the snap version and performed the installation with
> 
> `curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/`
> 
> And the install seems to be proceeding without a hitch

THANK YOU
FIXED IT FOR ME

**Comment by urbandroid** [comment]
uninstalling snap and installing "real" version is not a "real" fix. That makes you run a deceiving app unconfined, deceiving because even though they know their snap is broken they are acting like it is not and using as a honey pot.

**Comment by tjma2001** [comment]
I linked the official minikube binary. If that is a honey pot that I give up. It is running unconfined but I am not sure the snap version of minikube can run unconfined either.
