### ISSUE TITLE
failed to minikube start

### ISSUE THREAD

**Issue by baejinsoo** [kubernetes/minikube#9272]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

Exiting due to K8S_INSTALL_FAILED: updating control plane: downloading binaries: downloading kubeadm: download failed: https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubeadm.sha256: getter: &{Ctx:context.Background Src:https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubeadm?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubeadm.sha256 Dst:/home/vagrant/.minikube/cache/linux/v1.19.0/kubeadm.download Pwd: Mode:2 Detectors:[0x2d1af60 0x2d1af60 0x2d1af60 0x2d1af60 0x2d1af60 0x2d1af60] Decompressors:map[bz2:0x2d1af60 gz:0x2d1af60 tar.bz2:0x2d1af60 tar.gz:0x2d1af60 tar.xz:0x2d1af60 tbz2:0x2d1af60 tgz:0x2d1af60 txz:0x2d1af60 xz:0x2d1af60 zip:0x2d1af60] Getters:map[file:0xc0002a6510 http:0xc000948ee0 https:0xc000948f00] Dir:false ProgressListener:0x2ce5550 Options:[0xc842a0]}: Checksums did not match for /home/vagrant/.minikube/cache/linux/v1.19.0/kubeadm.download.
Expected: 88ce7dc5302d8847f6e679aab9e4fa642a819e8a33d70731fb7bc8e110d8659f
Got: 5e61d7314463f5720314571171a850e50ca47fd94b17d0c4f24af8f9903ac291
*sha256.digest
W0918 16:48:07.283629   17207 out.go:145]

W0918 16:48:07.283723   17207 out.go:145] 😿  If the above advice does not help, please let us know:
😿  If the above advice does not help, please let us know:
W0918 16:48:07.283809   17207 out.go:145] 👉  https://github.com/kubernetes/minikube/issues/new/choose
👉  https://github.com/kubernetes/minikube/issues/new/choose
I0918 16:48:07.311651   17207 out.go:109]

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
It looks like downloading kubeadm failed, are you somewhere that doesn't allow access to GCS?

**Comment by tstromberg** [comment]
You will need to use the `--image-repository` flag in China.
