### ISSUE TITLE
KUBECONFIG set on Windows: The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by PSANGAN** [kubernetes/minikube#9278]
**Steps to reproduce the issue:** 

1. WIN 10 HOME  and Virtual box installed
2. Installed MINIKUBE via the installer
3.  minikube start - give error

**Full output of failed command:** 

C:\WINDOWS\system32>minikube start
* minikube v1.12.3 on Microsoft Windows 10 Home 10.0.19041 Build 19041
  - KUBECONFIG=‪C:\Users\ganes\.kube\config
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! This VM is having trouble accessing https://k8s.gcr.io
* Preparing Kubernetes v1.18.3 on Docker 19.03.12 ...
* To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
! Unable to restart cluster, will reset it: getting k8s client: client config: client config: error loading config file "‪C:\Users\ganes\.kube\config": open ‪C:\Users\ganes\.kube\config: The filename, directory name, or volume label syntax is incorrect.
*
X failed to start node: startup failed: Failed to update kubeconfig file.: Error reading file "\u202aC:\\Users\\ganes\\.kube\\config": open ‪C:\Users\ganes\.kube\config: The filename, directory name, or volume label syntax is incorrect.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
![Issue2](https://user-images.githubusercontent.com/32886735/93667309-9e8e6700-faa2-11ea-803c-925911a8e0e2.jpg)
![Issue2](https://user-images.githubusercontent.com/32886735/93667321-a948fc00-faa2-11ea-9cd7-7ba276d84d91.jpg)
[log.txt](https://github.com/kubernetes/minikube/files/5249839/log.txt)
![Issue1](https://user-images.githubusercontent.com/32886735/93667355-f331e200-faa2-11ea-8860-ded4f0f6d473.jpg)

</details>

**Comment by priyawadhwa** [comment]
Hey @PSANGAN -- were you able to try setting the KUBECONFIG environment variable?

**Comment by ervjbb** [comment]
having the similar error but in Linux. I can unset the KUBECONFIG but what shall instead be set to?

**Comment by priyawadhwa** [comment]
Hey @ervjbb if you unset KUBECONFIG, minikube should set all necessary variables correctly for you.

Could you try:
1. Running `minikube delete` to clear the cluster
2. Unsetting the variable
2. Running `minikube start`

**Comment by ervjbb** [comment]
Worked like a charm....thanks!

**Comment by priyawadhwa** [comment]
Great to hear! I'll close this issue as it's been resolved.

**Comment by priyawadhwa** [comment]
Great to hear! I'll close this issue as it's been resolved.
