### ISSUE TITLE
windows: falesly saying we have not enough memory 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9307]
GH actio machines have 32 or 64 GB memory
```
X Exiting due to RSRC_INSUFFICIENT_REQ_MEMORY: Requested memory allocation 250MiB is less than the usable minimum of 953MB
223
        	I0922 08:58:22.431386   13480 out.go:109]
```

as seen https://github.com/kubernetes/minikube/pull/9302/checks?check_run_id=1148443022#step:8:208

**Comment by sharifelgamal** [comment]
This is a test that's explicitly asking for too little memory. Working as expected.

**Comment by medyagh** [comment]
I just realized the test is doing the right thing
