### ISSUE TITLE
"unable to download gcr.io" but downloads gcr.io

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9317]
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
! minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3, but successfully downloaded gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3 as a fallback image
* Creating docker container (CPUs=2, Memory=4000MB)

**Comment by afbjorklund** [comment]
Think it is just the output that is not showing the `cc.KubernetesConfig.ImageRepository` replacement ?

It should have been "baseImg".

**Comment by afbjorklund** [comment]
It could also be that the cast to Tag is hiding any digest that could have been in the original Ref ?

```go
                        if finalImg != "" && finalImg != baseImg {
                                out.WarningT(fmt.Sprintf("minikube was unable to download %s, but successfully downloaded %s as a fallback image", image.Tag(cc.KicBaseImage), image.Tag(finalImg)))
                                cc.KicBaseImage = finalImg
                        }
```

Would be interesting to see some logs, to see what is going on.
