### ISSUE TITLE
hyperv: Unable to get host IP due to case mismatch in virtual switch

### ISSUE THREAD

**Issue by old-code-monkey** [kubernetes/minikube#9320]
_minikube start --vm-driver=hyperv --hyperv-virtual-switch=Minikube_

Running the above command fails with "**Unable to get host IP: ip for interface (Minikube): Could not find interface vEthernet (Minikube)**"

Investigating my virtual network adapter using the following PowerShell command shows that I had a case mismatch (large K in Kube) compared to the output message 

	Get-NetAdapter | select Name

		Name
		----
		vEthernet (MiniKube)

Renaming the adapter using the command below to have a small K resolved my issue and allowed Minikube to successfully start

	Rename-NetAdapter -Name "vEthernet (MiniKube)" -NewName "vEthernet (Minikube)"

	Get-NetAdapter | select Name

		Name
		----
		vEthernet (Minikube)

During testing I also identified that regardless of what you supply to the hyperv-virtual-switch parameter it still looks for vEthernet (Minikube)

e.g.
minikube start --vm-driver=hyperv --hyperv-virtual-switch=AnyOldThing
Unable to get host IP: ip for interface (Minikube): Could not find interface vEthernet (Minikube)

**Comment by tstromberg** [comment]
Hey old-code-monkey! Thank you for the detailed bug report. I don't have a hyper-v machine, but would you be willing to help test a patch if I propose one? This one seems pretty simple based on how you describe it.

**Comment by tstromberg** [comment]
@old-code-monkey could you confirm if https://storage.googleapis.com/minikube-builds/9342/minikube-windows-amd64.exe fixes this problem? It's built from #9342

**Comment by old-code-monkey** [comment]
Hi Thomas,

Thanks for picking up this one and making the changes.  I'll have a go at testing it this evening and get back to you with the result.

**Comment by old-code-monkey** [comment]
Thomas, as can be seen by the attached files the fix for the case-mismatch is a success.
[minikube_v1.13.0.txt](https://github.com/kubernetes/minikube/files/5295240/minikube_v1.13.0.txt)
[minikube_v1.13.1.txt](https://github.com/kubernetes/minikube/files/5295243/minikube_v1.13.1.txt)

During testing, I did see a strange error when performing a minikube stop after the start had thrown an error.
The original version (v1.13.0) performed the stop cleanly

	> orig-minikube stop
	✋  Stopping node "minikube"  ...
	🛑  Powering off "minikube" via SSH ...
	🛑  1 nodes stopped.

But your newer version (v1.13.1) threw an exception

	> new-minikube stop
	✋  Stopping node "minikube"  ...
	🛑  Powering off "minikube" via SSH ...
	E0928 22:12:34.081948    5940 main.go:114] libmachine: [stderr =====>] : Hyper-V\Stop-VM : Windows PowerShell is in NonInteractive mode. Read and Prompt functionality is not available.
	At line:1 char:1
	+ Hyper-V\Stop-VM minikube
	+ ~~~~~~~~~~~~~~~~~~~~~~~~
		+ CategoryInfo          : InvalidOperation: (:) [Stop-VM], VirtualizationException
		+ FullyQualifiedErrorId : InvalidOperation,Microsoft.HyperV.PowerShell.Commands.StopVM

	✋  Stopping node "minikube"  ...
	🛑  1 nodes stopped.

This behaviour was not consistent and subsequent attempts at the same scenario worked successfully:

	> new-minikube stop
	✋  Stopping node "minikube"  ...
	🛑  Powering off "minikube" via SSH ...
	🛑  1 nodes stopped.

Just for information, I also found that having renamed the Hyper-V virtual switch; which automatically renames the network adaptor; the subsequent minikube start would fail even if you specify the new switch name as a parameter.
e.g.

	> Get-VMSwitch
	Name           SwitchType NetAdapterInterfaceDescription
	----           ---------- ------------------------------
	Blob           Internal
	Default Switch Internal
	WSL            Internal


	> Get-NetAdapter | Select-Object Name | where {$_ -like '*blob*'}
	Name
	----
	vEthernet (Blob)

	> new-minikube start --vm-driver=hyperv --hyperv-virtual-switch=Blob
	✨  Using the hyperv driver based on existing profile
	👍  Starting control plane node minikube in cluster minikube
	��  Updating the running hyperv "minikube" VM ...                                                                       
	��  Preparing Kubernetes v1.19.2 on Docker 19.03.12 ...                                                                 
	E0928 22:44:08.277577     880 start.go:99] Unable to get host IP: ip for interface (Minikube): Could not find interface vEthernet (Minikube) inside [{Index:16 MTU:1488 Name:Ethernet0 HardwareAddr:00:0c:29:f2:ce:aa Flags:up|broadcast|multicast} {Index:17 MTU:1500 Name:vEthernet (Blob) HardwareAddr:00:15:5d:00:65:08 Flags:up|broadcast|multicast} {Index:1 MTU:-1 Name:Loopback Pseudo-Interface 1 HardwareAddr: Flags:up|loopback|multicast} {Index:10 MTU:1500 Name:vEthernet (Default Switch) HardwareAddr:00:15:5d:a3:25:35 Flags:up|broadcast|multicast} {Index:29 MTU:1500 Name:vEthernet (WSL) HardwareAddr:00:15:5d:ba:2e:4c Flags:up|broadcast|multicast}]

	❌  Exiting due to GUEST_START: Failed to setup kubeconfig: ip for interface (Minikube): Could not find interface vEthernet (Minikube) inside [{Index:16 MTU:1488 Name:Ethernet0 HardwareAddr:00:0c:29:f2:ce:aa Flags:up|broadcast|multicast} {Index:17 MTU:1500 Name:vEthernet (Blob) HardwareAddr:00:15:5d:00:65:08 Flags:up|broadcast|multicast} {Index:1 MTU:-1 Name:Loopback Pseudo-Interface 1 HardwareAddr: Flags:up|loopback|multicast} {Index:10 MTU:1500 Name:vEthernet (Default Switch) HardwareAddr:00:15:5d:a3:25:35 Flags:up|broadcast|multicast} {Index:29 MTU:1500 Name:vEthernet (WSL) HardwareAddr:00:15:5d:ba:2e:4c Flags:up|broadcast|multicast}]

	😿  If the above advice does not help, please let us know:
	👉  https://github.com/kubernetes/minikube/issues/new/choose


Deleting the VM and purging the filestore enables the renamed switch to be used

	> new-minikube delete --all --purge
	> new-minikube start --vm-driver=hyperv --hyperv-virtual-switch=Blob
