### ISSUE TITLE
minikube_latest_amd64.deb accidentally included in Github release assets

### ISSUE THREAD

**Issue by tillhoff** [kubernetes/minikube#9341]
When checking through the release assets of the last release (https://github.com/kubernetes/minikube/releases/tag/v1.13.1), I found that there are two .deb files for the same thing:
- minikube_latest_amd64.deb
- minikube_1.13.1-0_amd64.deb

IMO the `latest` one shouldn't be there, since the path to it is still versioned as `https://github.com/kubernetes/minikube/releases/download/v1.13.1/minikube_latest_amd64.deb`.

Since I haven't found the corresponding pipeline so far, maybe you could/should look into this.

**Comment by afbjorklund** [comment]
It’s just to make the URL in the documentation ”static” (latest)
It’s the exact same content as in the “normal” packages (which in turn is identical to the uncompressed binary)

**Comment by afbjorklund** [comment]
See https://github.com/kubernetes/minikube/pull/7971

**Comment by tstromberg** [comment]
This is a bug. The *latest* artifact is indeed intended for static URL's, but it shouldn't be part of the GitHub release. These unversioned files should get filtered out from here:

https://github.com/kubernetes/minikube/blob/11cad2b3e6b2dfc34ed5943ea58083df147ba69c/hack/jenkins/release_github_page.sh#L84

**Comment by afbjorklund** [comment]
Right, the docs* says to get it from google and not github...

\* https://minikube.sigs.k8s.io/docs/start/

**Comment by tillhoff** [comment]
I would love to work on this. Will start tomorrow.

**Comment by tillhoff** [comment]
Short note: `minikube-latest.x86_64.rpm` is also excluded now.

**Comment by tillhoff** [comment]
> This is a bug. The _latest_ artifact is indeed intended for static URL's, but it shouldn't be part of the GitHub release. These unversioned files should get filtered out from here:
> 
> https://github.com/kubernetes/minikube/blob/11cad2b3e6b2dfc34ed5943ea58083df147ba69c/hack/jenkins/release_github_page.sh#L84

@tstromberg Thank you for pointing there, that saved me a lot of time :1st_place_medal:
