### ISSUE TITLE
Hyper-V Tests failing on local machine

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#9344]
I am running the tests locally on my Windows machine but the following tests are failing consistently -
```
"TestFunctional/serial/CopySyncFile",
"TestFunctional/serial/MinikubeKubectlCmdDirectly",
"TestFunctional/parallel/DashboardCmd",
"TestFunctional/parallel/DryRun",
"TestFunctional/parallel/PersistentVolumeClaim",
"TestFunctional/parallel/MySQL",
"TestFunctional/parallel/FileSync",
"TestFunctional/parallel/CertSync",
"TestFunctional/parallel/TunnelCmd/serial/WaitService"
```

These tests are not failing in the CI builds though. Attached is the log file. (Rename it to `.html` from `.txt`)
[testout_59f2c65 (2).txt](https://github.com/kubernetes/minikube/files/5294339/testout_59f2c65.2.txt)

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
