### ISSUE TITLE
parallels: Your Mac host is not connected to Shared network.

### ISSUE THREAD

**Issue by educatux** [kubernetes/minikube#9357]
Hi, 
With MacOS 11.0 beta (20A5374i) and parallels 16.0.1 (48919)
problem to Create Minikube because : Shared Network.

My Command : minikube start --vm-driver=parallels --alsologtostderr -v=7

--------- Log Details
I0930 08:59:09.770672    6797 out.go:191] Setting JSON to false
I0930 08:59:09.822388    6797 start.go:102] hostinfo: {"hostname":"MacBook-Pro.educatux.org","uptime":7008,"bootTime":1601442141,"procs":582,"os":"darwin","platform":"darwin","platformFamily":"","platformVersion":"11.0","kernelVersion":"20.1.0","virtualizationSystem":"","virtualizationRole":"","hostid":"1beb2151-70f0-3656-af8f-9bf853f1f2c1"}
W0930 08:59:09.822507    6797 start.go:110] gopshost.Virtualization returned error: not implemented yet
I0930 08:59:09.894508    6797 out.go:109] 😄  minikube v1.13.1 sur Darwin 11.0
😄  minikube v1.13.1 sur Darwin 11.0
I0930 08:59:09.894698    6797 notify.go:126] Checking for updates...
W0930 08:59:09.895060    6797 start.go:602] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I0930 08:59:09.895110    6797 driver.go:287] Setting default libvirt URI to qemu:///system
W0930 08:59:09.895149    6797 start.go:602] api.Load failed for minikube: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
I0930 08:59:09.939624    6797 out.go:109] ✨  Utilisation du pilote parallels basé sur le profil existant
✨  Utilisation du pilote parallels basé sur le profil existant
I0930 08:59:09.939660    6797 start.go:246] selected driver: parallels
I0930 08:59:09.939670    6797 start.go:653] validating driver "parallels" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.13.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3@sha256:1d687ba53e19dbe5fafe4cc18aa07f269ecc4b7b622f2251b5bf569ddb474e9b Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:parallels HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.19.2 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.19.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s}
I0930 08:59:09.939865    6797 start.go:664] status for parallels: {Installed:true Healthy:true Running:true NeedsImprovement:false Error:<nil> Fix: Doc:}
I0930 08:59:09.946880    6797 start_flags.go:348] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.13.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3@sha256:1d687ba53e19dbe5fafe4cc18aa07f269ecc4b7b622f2251b5bf569ddb474e9b Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:parallels HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.19.2 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.19.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s}
I0930 08:59:09.947109    6797 iso.go:119] acquiring lock: {Name:mkc45cb9c60062de15f1a62f0ce54707ed72d156 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I0930 08:59:10.013412    6797 out.go:109] 👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
👍  Démarrage du noeud de plan de contrôle minikube dans le cluster minikube
I0930 08:59:10.013453    6797 preload.go:97] Checking if preload exists for k8s version v1.19.2 and runtime docker
I0930 08:59:10.013498    6797 preload.go:105] Found local preload: /Users/stephane/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v6-v1.19.2-docker-overlay2-amd64.tar.lz4
I0930 08:59:10.013509    6797 cache.go:53] Caching tarball of preloaded images
I0930 08:59:10.013527    6797 preload.go:131] Found /Users/stephane/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v6-v1.19.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I0930 08:59:10.013532    6797 cache.go:56] Finished verifying existence of preloaded tar for  v1.19.2 on docker
I0930 08:59:10.013640    6797 profile.go:150] Saving config to /Users/stephane/.minikube/profiles/minikube/config.json ...
I0930 08:59:10.014535    6797 cache.go:182] Successfully downloaded all kic artifacts
I0930 08:59:10.014568    6797 start.go:314] acquiring machines lock for minikube: {Name:mka12b7bdfc61e168e4fbdd7cbefb1560f2586ed Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0930 08:59:10.014646    6797 start.go:318] acquired machines lock for "minikube" in 66.003µs
I0930 08:59:10.014669    6797 start.go:90] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.13.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3@sha256:1d687ba53e19dbe5fafe4cc18aa07f269ecc4b7b622f2251b5bf569ddb474e9b Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:parallels HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.19.2 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.19.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s} &{Name: IP: Port:8443 KubernetesVersion:v1.19.2 ControlPlane:true Worker:true}
I0930 08:59:10.014772    6797 start.go:127] createHost starting for "" (driver="parallels")
I0930 08:59:10.081438    6797 out.go:109] 🔥  Création de VM parallels (CPUs=2, Mémoire=4000MB, Disque=20000MB)...
🔥  Création de VM parallels (CPUs=2, Mémoire=4000MB, Disque=20000MB)...
I0930 08:59:10.081822    6797 start.go:164] libmachine.API.Create for "minikube" (driver="parallels")
I0930 08:59:10.081860    6797 client.go:165] LocalClient.Create starting
I0930 08:59:10.081971    6797 main.go:115] libmachine: Reading certificate data from /Users/stephane/.minikube/certs/ca.pem
I0930 08:59:10.082055    6797 main.go:115] libmachine: Decoding PEM data...
I0930 08:59:10.082088    6797 main.go:115] libmachine: Parsing certificate...
I0930 08:59:10.082252    6797 main.go:115] libmachine: Reading certificate data from /Users/stephane/.minikube/certs/cert.pem
I0930 08:59:10.082313    6797 main.go:115] libmachine: Decoding PEM data...
I0930 08:59:10.082333    6797 main.go:115] libmachine: Parsing certificate...
I0930 08:59:10.082400    6797 main.go:115] libmachine: executing: /usr/local/bin/prlctl --version
I0930 08:59:10.201161    6797 main.go:115] libmachine: executing: /usr/local/bin/prlsrvctl info --license
I0930 08:59:10.358922    6797 main.go:115] libmachine: Found Parallels Desktop version: &{%!d(string=) %!d(string=) [16 0 1] 3 %!d(string=16.0.1)}, edition: business
I0930 08:59:10.358963    6797 main.go:115] libmachine: executing: /usr/local/bin/prlsrvctl net info Shared
I0930 08:59:10.678491    6797 client.go:168] LocalClient.Create took 596.608115ms
I0930 08:59:12.683159    6797 start.go:130] duration metric: createHost completed in 2.668341828s
I0930 08:59:12.683188    6797 start.go:81] releasing machines lock for "minikube", held for 2.668511711s
W0930 08:59:12.683214    6797 start.go:377] error starting host: creating host: create: precreate: Your Mac host is not connected to Shared network. Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'
I0930 08:59:12.683363    6797 cli_runner.go:110] Run: docker container inspect minikube --format={{.State.Status}}
I0930 08:59:12.723362    6797 delete.go:46] couldn't inspect container "minikube" before deleting: unknown state "minikube": docker container inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
I0930 08:59:12.723450    6797 cli_runner.go:110] Run: podman container inspect minikube --format={{.State.Status}}
I0930 08:59:13.098059    6797 delete.go:46] couldn't inspect container "minikube" before deleting: unknown state "minikube": podman container inspect minikube --format={{.State.Status}}: exit status 125
stdout:

stderr:
Error: Get "http://d/v1.0.0/libpod../../../_ping": dial unix ///var/folders/lj/c1bx9pvn06v2t2x8jjhrlg500000gn/T/run--1/podman/podman.sock: connect: no such file or directory
W0930 08:59:13.098154    6797 start.go:382] delete host: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.
W0930 08:59:13.098471    6797 out.go:145] 🤦  StartHost failed, but will try again: creating host: create: precreate: Your Mac host is not connected to Shared network. Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'
🤦  StartHost failed, but will try again: creating host: create: precreate: Your Mac host is not connected to Shared network. Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'
I0930 08:59:13.098497    6797 start.go:392] Will try again in 5 seconds ...
I0930 08:59:18.102792    6797 start.go:314] acquiring machines lock for minikube: {Name:mka12b7bdfc61e168e4fbdd7cbefb1560f2586ed Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0930 08:59:18.102956    6797 start.go:318] acquired machines lock for "minikube" in 105.341µs
I0930 08:59:18.102985    6797 start.go:90] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.13.1.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3@sha256:1d687ba53e19dbe5fafe4cc18aa07f269ecc4b7b622f2251b5bf569ddb474e9b Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:parallels HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.19.2 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.19.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s} &{Name: IP: Port:8443 KubernetesVersion:v1.19.2 ControlPlane:true Worker:true}
I0930 08:59:18.103195    6797 start.go:127] createHost starting for "" (driver="parallels")
I0930 08:59:18.169924    6797 out.go:109] 🔥  Création de VM parallels (CPUs=2, Mémoire=4000MB, Disque=20000MB)...
🔥  Création de VM parallels (CPUs=2, Mémoire=4000MB, Disque=20000MB)...
I0930 08:59:18.170017    6797 start.go:164] libmachine.API.Create for "minikube" (driver="parallels")
I0930 08:59:18.170051    6797 client.go:165] LocalClient.Create starting
I0930 08:59:18.170136    6797 main.go:115] libmachine: Reading certificate data from /Users/stephane/.minikube/certs/ca.pem
I0930 08:59:18.170202    6797 main.go:115] libmachine: Decoding PEM data...
I0930 08:59:18.170223    6797 main.go:115] libmachine: Parsing certificate...
I0930 08:59:18.170350    6797 main.go:115] libmachine: Reading certificate data from /Users/stephane/.minikube/certs/cert.pem
I0930 08:59:18.170390    6797 main.go:115] libmachine: Decoding PEM data...
I0930 08:59:18.170405    6797 main.go:115] libmachine: Parsing certificate...
I0930 08:59:18.170459    6797 main.go:115] libmachine: executing: /usr/local/bin/prlctl --version
I0930 08:59:18.291652    6797 main.go:115] libmachine: executing: /usr/local/bin/prlsrvctl info --license
I0930 08:59:18.446457    6797 main.go:115] libmachine: Found Parallels Desktop version: &{%!d(string=) %!d(string=) [16 0 1] 3 %!d(string=16.0.1)}, edition: business
I0930 08:59:18.446501    6797 main.go:115] libmachine: executing: /usr/local/bin/prlsrvctl net info Shared
I0930 08:59:18.767624    6797 client.go:168] LocalClient.Create took 597.557168ms
I0930 08:59:20.772831    6797 start.go:130] duration metric: createHost completed in 2.669598438s
I0930 08:59:20.772864    6797 start.go:81] releasing machines lock for "minikube", held for 2.669878349s
W0930 08:59:20.773164    6797 out.go:145] 😿  Failed to start parallels VM. Running "minikube delete" may fix it: creating host: create: precreate: Your Mac host is not connected to Shared network. Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'
😿  Failed to start parallels VM. Running "minikube delete" may fix it: creating host: create: precreate: Your Mac host is not connected to Shared network. Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'
I0930 08:59:20.820905    6797 out.go:109]

W0930 08:59:20.821125    6797 out.go:145] ❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: Your Mac host is not connected to Shared network. Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'
❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: Your Mac host is not connected to Shared network. Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'
W0930 08:59:20.821204    6797 out.go:145]

W0930 08:59:20.821350    6797 out.go:145] 😿  If the above advice does not help, please let us know:
😿  If the above advice does not help, please let us know:
W0930 08:59:20.821410    6797 out.go:145] 👉  https://github.com/kubernetes/minikube/issues/new/choose
👉  https://github.com/kubernetes/minikube/issues/new/choose
I0930 08:59:20.894777    6797 out.go:109]

-------- /usr/local/bin/prlsrvctl info --license
Searching for installed licenses...
	status="ACTIVE"
	serial="******************************"
	expiration="09/04/2021 18:28:40"
	main_period_ends_at="08/05/2021 18:28:40"
	grace_period_ends_at="09/04/2021 18:28:40"
	cpu_total=32
	max_memory=131072
	edition="business"
	is_volume="yes"
	advanced_restrictions="disabled"
	deferred_activation="disabled"
	uuid="76173ced68f4499aa37ea274f81af1c4"

----------- /usr/local/bin/prlsrvctl net info Shared
Network ID: Shared
Type: shared
Parallels adapter:
	IPv4 address: 10.211.55.2
	IPv4 subnet mask: 255.255.255.0
	Host assign IP v6: off
	IPv6 address: fdb2:2c26:f4e4::1
	IPv6 subnet mask: ffff:ffff:ffff:ffff::
DHCPv4 server:
	Server address: 10.211.55.1
	IP scope start address: 10.211.55.1
	IP scope end address: 10.211.55.254
DHCPv6 server:
	Server address: fdb2:2c26:f4e4::
	IP scope start address: fdb2:2c26:f4e4::
	IP scope end address: fdb2:2c26:f4e4:0:ffff:ffff:ffff:ffff

NAT server:

--------------------

**Comment by tstromberg** [comment]
Were you able to follow the solution it suggested?

`Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'`

**Comment by rca-sgautier** [comment]
This option already  actived.
Bug of Mac OS BigSur ?

Envoyé de mon iPhone

Le 30 sept. 2020 à 18:35, Thomas Strömberg <notifications@github.com> a écrit :

﻿

Were you able to follow the solution that minikube suggested?

Please, enable this option: 'Parallels Desktop' -> 'Preferences' -> 'Network' -> 'Shared' -> 'Connect Mac to this network'

**Comment by rca-sgautier** [comment]
It's not a problem connecting to the Mac's network. I checked before I opened this issue. For me it's a problem maybe with Bigsur Mac OS.

**Comment by rca-sgautier** [comment]
![Uploading Capture d’écran 2020-10-04 à 11.56.45.png…]()

**Comment by rca-sgautier** [comment]
<img width="1564" alt="Capture d’écran 2020-10-04 à 11 56 45" src="https://user-images.githubusercontent.com/72125601/95012497-54c48580-0639-11eb-995d-45058e9220ec.png">

**Comment by legal90** [comment]
Hi all!
The same error was recently reported to `parallels` driver repo: https://github.com/Parallels/docker-machine-parallels/issues/93
We [fixed](https://github.com/Parallels/docker-machine-parallels/issues/93) it recently and released in [v2.0.0](https://github.com/Parallels/docker-machine-parallels/releases/tag/v2.0.0).

However, it's not enough to update `docker-machine-driver-parallels` to v2.0.0, because minikube currently is calling parallels driver as the built-in library (https://github.com/kubernetes/minikube/pull/9494)

Possible solutions:
1) Either detach parallels driver from minikube by merging this PR: https://github.com/kubernetes/minikube/pull/9494
2) or bump the version to v2.0.0 here https://github.com/kubernetes/minikube/blob/a282354419135221325414c1d8d03f3bd37b58e3/go.mod#L8
