### ISSUE TITLE
minikube doesn't start

### ISSUE THREAD

**Issue by mhworth** [kubernetes/minikube#936]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Minikube version** (use `minikube version`): 0.14.0

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS 10.12.1
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **Docker version** (e.g. `docker -v`): Docker version 1.13.0-rc3, build 4d92237
- **Install tools**: curl
- **Others**:

**What happened**: Received the error "E1218 00:18:46.325465   38097 start.go:144] Error setting up kubeconfig:  Error writing file : open : no such file or directory" when running minikube start

**What you expected to happen**: Minikube cluster starts

**How to reproduce it** (as minimally and precisely as possible):

> Matts-MacBook-Pro:bin matt$ curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.14.0/minikube-darwin-amd64 && chmod +x minikube
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100 82.4M  100 82.4M    0     0  7062k      0  0:00:11  0:00:11 --:--:-- 7310k
> Matts-MacBook-Pro:bin matt$ which minikube
> /Users/matt/bin/minikube
> Matts-MacBook-Pro:bin matt$ minikube start
> Starting local Kubernetes cluster...
> E1218 00:16:43.501482   37979 start.go:144] Error setting up kubeconfig:  Error writing file : open : no such file or directory
> 

**Anything else do we need to know**: N/A

**Comment by mhworth** [comment]
xhyve also doesn't work:

> Matts-MacBook-Pro:hellonode matt$ minikube start --vm-driver=xhyve
> Starting local Kubernetes cluster...
> E1218 12:44:35.509088    3983 start.go:144] Error setting up kubeconfig:  Error writing file : open : no such file or directory

**Comment by mhworth** [comment]
Aha, figured out the problem. An earlier kubernetes installer that I tried had exported KUBECONFIG in my bash_profile, so that error was being thrown locally because the config was missing. Fixed by removing KUBECONFIG and deleting .kube (something was wrong in there too that was preventing me from connecting).

**Comment by davideuler** [comment]
I've met exactly the same problem 👍

**Comment by JustinLivi** [comment]
Met the same error message but had a slightly different solution. Posting here for future users. My KUBECONFIG was pointing to files which did indeed exist, but the paths were prefixed by a colon `:`. Removing the colon resolved the issue.
