### ISSUE TITLE
failed to create gluster volume: Invalid JWT token: signature is invalid (client and server secrets may not match)

### ISSUE THREAD

**Issue by mFarghaly** [kubernetes/minikube#9360]
**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable storage-provisioner-gluster
3. following tutorial here https://github.com/kubernetes/minikube/tree/master/deploy/addons/storage-provisioner-gluster

Checking the `kubectl describe pvc` I get the following events

<details>
Events:
  Type     Reason                Age              From                                                                                                   Message
  ----     ------                ----             ----                                                                                                   -------
  Normal   ExternalProvisioning  5s (x4 over 9s)  persistentvolume-controller                                                                            waiting for a volume to be created, either by external provisioner "gluster.org/glusterfile" or manually created by system administrator
  Normal   Provisioning          1s (x2 over 9s)  gluster.org/glusterfile glusterfile-provisioner-86dfc6ddbf-2fj2p fa37b250-0334-11eb-9ee5-0242ac11000a  External provisioner is provisioning volume for claim "default/website"
  Warning  ProvisioningFailed    1s (x2 over 9s)  gluster.org/glusterfile glusterfile-provisioner-86dfc6ddbf-2fj2p fa37b250-0334-11eb-9ee5-0242ac11000a  Failed to provision volume with StorageClass "glusterfile": failed to create volume: failed to create gluster volume: Invalid JWT token: signature is invalid (client and server secrets may not match)

</details>

**Comment by medyagh** [comment]
@mFarghaly do you mind sharing what driver are you using?

**Comment by medyagh** [comment]
Hi @mFarghaly, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
