### ISSUE TITLE
minikube not installed properly on RHEL7

### ISSUE THREAD

**Issue by ysingla0580** [kubernetes/minikube#9369]
I am getting permission denied issue while starting the minikube -

[root@TEST004-K8S ~]# minikube start  --driver=none
* minikube v1.13.1 on Redhat 7.6
* Using the none driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=2, Memory=3931MB, Disk=11967MB) ...
* OS release is Red Hat Enterprise Linux Server 7.6 (Maipo)
* Preparing Kubernetes v1.19.2 on Docker 19.03.13 ...
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubeadm: 37.30 MiB / 37.30 MiB [---------------] 100.00% 14.00 MiB p/s 3s
    > kubectl: 41.01 MiB / 41.01 MiB [---------------] 100.00% 11.53 MiB p/s 4s
    > kubelet: 104.88 MiB / 104.88 MiB [-------------] 100.00% 20.89 MiB p/s 6s
! initialization failed, will try again: run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.19.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap": exit status 126
stdout:

stderr:
env: kubeadm: Permission denied

*
X Error starting cluster: run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.19.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap": exit status 126
stdout:

stderr:
env: kubeadm: Permission denied

*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

X Exiting due to GUEST_START: run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.19.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap": exit status 126
stdout:

stderr:
env: kubeadm: Permission denied

*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

[root@TEST004-K8S ~]# minikube status
minikube
type: Control Plane
host: Stopped
kubelet: Stopped
apiserver: Stopped
kubeconfig: Stopped

**Comment by afbjorklund** [comment]
Most likely `/var/lib/minikube/binaries/v1.19.2/kubeadm` is protected somehow, like /var being mounted noexec or something ?
