### ISSUE TITLE
 AnyConnect  VPN: vbox host-only: "minikube is unable to connect to the VM: dial tcp x:22: i/o timeout"

### ISSUE THREAD

**Issue by huornlmj** [kubernetes/minikube#9380]
X minikube appears to try to connect to the newly created Virtualbox VM on 192.168.99.101:22.  However the VM itself is not reachable from the host when created as it is created on a host-only network.  The VM is also automatically configured for port forwarding, forwarding the VM's port 22 to port 4096 on the host's loopback interface.

If this were to work then the line below (X minikube is unable to connect to the VM) would have to try to connect to 127.0.0.1:4096, not 192.168.99.101:22.

```
minikube start
* minikube v1.13.1 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Kubernetes 1.19.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.19.2
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Found network options:
  - HTTP_PROXY=http://<REDACTED>
  - NO_PROXY=192.168.99.101
  - http_proxy=http://<REDACTED>
  - no_proxy=192.168.99.101
X minikube is unable to connect to the VM: dial tcp 192.168.99.101:22: i/o timeout

        This is likely due to one of two reasons:

        - VPN or firewall interference
        - virtualbox network configuration issue

        Suggested workarounds:

        - Disable your local VPN or firewall software
        - Configure your local VPN or firewall to allow access to 192.168.99.101
        - Restart or reinstall virtualbox
        - Use an alternative --vm-driver
        - Use --force to override this connectivity check


X Exiting due to GUEST_PROVISION: Failed to validate network: dial tcp 192.168.99.101:22: i/o timeout
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose


C:\Users\jcullig>minikube start
* minikube v1.13.1 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Kubernetes 1.19.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.19.2
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
! StartHost failed, but will try again: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027440d10
* Updating the running virtualbox "minikube" VM ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027440d10

X Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 080027440d10
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by tstromberg** [comment]
It may be possible that minikube is incompatible with host-only networking - I've never tried it.

What happens if you run `minikube delete` and `minikube start` -- does in work properly then?

**Comment by kishorevaishnav** [comment]
I had the same kind of issue and resolved it by rebooting my Mac. 
- started minikube
- started AnyConnect VPN
- used for couple of hours due to client project & closed it.
- minikube status - apiserver stopped -- # Don't know how to start it back.
- minikube delete
- minikube start
- didn't work, so restarted and started it 
- it worked fine.

Hope this might help.

**Comment by spowelljr** [comment]
Hi @huornlmj, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by sukumarp2020** [comment]
> I am also receiving same kind of issue here is the trace
> 
> padmavathy_selvaraja ~ $ minikube start --cpus 4 --memory 8192 😄 minikube v1.23.2 on Darwin 11.6 ▪ KUBECONFIG=/Users/padmavathy_selvaraja/.kube/config:/Users/padmavathy_selvaraja/.kube/config_np:/Users/padmavathy_selvaraja/.kube/config_dr:/Users/padmavathy_selvaraja/.kube/support-stage-config:/Users/padmavathy_selvaraja/.kube/support-core-config:/Users/padmavathy_selvaraja/.kube/support-prod-east-config:/Users/padmavathy_selvaraja/.kube/support-prod-west-config ▪ MINIKUBE_ACTIVE_DOCKERD=minikube ✨ Using the virtualbox driver based on existing profile 👍 Starting control plane node minikube in cluster minikube 🏃 Updating the running virtualbox "minikube" VM ... ❌ minikube is unable to connect to the VM: dial tcp 192.168.99.100:22: i/o timeout
> 
> ```
> This is likely due to one of two reasons:
> 
> - VPN or firewall interference
> - virtualbox network configuration issue
> 
> Suggested workarounds:
> 
> - Disable your local VPN or firewall software
> - Configure your local VPN or firewall to allow access to 192.168.99.100
> - Restart or reinstall virtualbox
> - Use an alternative --vm-driver
> - Use --force to override this connectivity check
> ```
> 
> ❌ Exiting due to GUEST_PROVISION: Failed to validate network: dial tcp 192.168.99.100:22: i/o timeout
> 
> ╭───────────────────────────────────────────────────────────────────────────────────────────╮ │ │ │ 😿 If the above advice does not help, please let us know: │ │ 👉 https://github.com/kubernetes/minikube/issues/new/choose │ │ │ │ Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue. │ │ │ ╰───────────────────────────────────────────────────────────────────────────────────────────╯
> 
> FYI: This problem occured after i upgraded my mac from catalina to Big sur

+1
