### ISSUE TITLE
Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: Machine didn't return an IP after 120 seconds

### ISSUE THREAD

**Issue by obaidomer** [kubernetes/minikube#9381]
**Steps to reproduce the issue:** 

1. installation of minikube on MacOS
2. run minikube start 
3. below output is thrown back. 

MacOS has both VMware Fusion and VirtualBox - both give similar exception.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

minikube start
😄  minikube v1.13.1 on Darwin 11.0
✨  Automatically selected the vmwarefusion driver
👍  Starting control plane node minikube in cluster minikube
❗  The vmwarefusion driver is deprecated and support for it will be removed in a future release.
			Please consider switching to the new vmware unified driver, which is intended to replace the vmwarefusion driver.
			See https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/ for more information.
			To disable this message, run [minikube config set ShowDriverDeprecationNotification false]
🔥  Creating vmwarefusion VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🔥  Deleting "minikube" in vmwarefusion ...
🤦  StartHost failed, but will try again: creating host: create: creating: Machine didn't return an IP after 120 seconds, aborting
❗  The vmwarefusion driver is deprecated and support for it will be removed in a future release.
			Please consider switching to the new vmware unified driver, which is intended to replace the vmwarefusion driver.
			See https://minikube.sigs.k8s.io/docs/reference/drivers/vmware/ for more information.
			To disable this message, run [minikube config set ShowDriverDeprecationNotification false]
🔥  Creating vmwarefusion VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
😿  Failed to start vmwarefusion VM. Running "minikube delete" may fix it: creating host: create: creating: Machine didn't return an IP after 120 seconds, aborting

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: creating: Machine didn't return an IP after 120 seconds, aborting

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
Yeah the vmwarefusion driver is no longer supported at all, I'd suggest trying the vmware driver instead.

**Comment by obaidomer** [comment]
> Yeah the vmwarefusion driver is no longer supported at all, I'd suggest trying the vmware driver instead.

Please share the link/steps to do so on Mac.

**Comment by priyawadhwa** [comment]
Hey @obaidomer our documentation website: https://minikube.sigs.k8s.io/

Info on the vmware driver can be found here: https://minikube.sigs.k8s.io/docs/drivers/vmware/

**Comment by priyawadhwa** [comment]
Please let us know if this resolves your issue.

**Comment by obaidomer** [comment]
Hi @priyawadhwa, Thank you for the documentation, 

the same error occurred. For now, I have created individual VM's and moved on. 

here are the logs.

minikube start --driver=vmware
😄  minikube v1.13.1 on Darwin 11.0
✨  Using the vmware driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating vmware VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🔥  Deleting "minikube" in vmware ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
🔥  Creating vmware VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
😿  Failed to start vmware VM. Running "minikube delete" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting

❌  Exiting due to DRV_NO_IP: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds, aborting
💡  Suggestion: Check your firewall rules for interference, and run 'virt-host-validate' to check for KVM configuration issues. If you are running minikube within a VM, consider using --driver=none
📘  Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/kvm2/
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/4249
    ▪ https://github.com/kubernetes/minikube/issues/3566
