### ISSUE TITLE
Fatal errors should include the path to the post-mortem INFO log

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#9398]
Currently, we provide this information, which no one sees: https://minikube.sigs.k8s.io/docs/handbook/troubleshooting/#post-mortem-minikube-debug-logs

I was thinking that when we have a fatal exit, we should be able to say something like:

```
Please open a GitHub issue. If you are able to drag and drop the following log-file into the issue, we'll be able to make faster progress: /path/to/minikube.INFO.log
```

Related: #9323

**Comment by medyagh** [comment]
we agreed this is a good feature to implement. @spowelljr would be a good candidate to work on this

**Comment by spowelljr** [comment]
In-progress
