### ISSUE TITLE
--delete-on-failure does not delete on GUEST_DRIVER_MISMATCH

### ISSUE THREAD

**Issue by j-windsor** [kubernetes/minikube#9399]
**Steps to reproduce the issue:** 

1. `minikube start --driver=docker`
2. `minikube start --driver=hyperkit --delete-on-failure`
3. See message on GUEST_DRIVER_MISMATCH
4. `minikube profile list` to see that the profile is not deleted.

![Screen Shot 2020-10-05 at 3 48 09 PM](https://user-images.githubusercontent.com/554839/95140509-f0322500-0723-11eb-9999-683e8da9a835.png)

This is something that can be fixed by deleting, so I would expect deletion to occur.

**Related:**
- https://github.com/kubernetes/minikube/issues/9372
- https://github.com/kubernetes/minikube/issues/9397

**Comment by vinu2003** [comment]
Hey @j-windsor can i work on this issue if you aren't keen to do this ? then i can fix #9397

**Comment by tstromberg** [comment]
@vinu2003 - go for it!

**Comment by vinu2003** [comment]
My understanding here: the --delete-on-failure when set, should delete the default minikube profile(in this case docker) if it doesn't match with the one provided in start command (in this case"hyperkit") - then it should delete the existing docker cluster and create default one with hyper kit as driver.

**Comment by medyagh** [comment]
@vinu2003 I haven't heard from you, please let me know if you are still working on this

**Comment by azhao155** [comment]
I think the issue got fixed. 

I repro the issue with same cmd and see following:

```
zyanshu@zyanshukvm:~/minikube$ minikube start --driver=docker
-bash: minikube: command not found
zyanshu@zyanshukvm:~/minikube$ ./out/minikube start --driver=docker
😄  minikube v1.16.0 on Debian rodete
    ▪ MINIKUBE_ACTIVE_DOCKERD=p1
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=26100MB) ...
🐳  Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
zyanshu@zyanshukvm:~/minikube$
zyanshu@zyanshukvm:~/minikube$
zyanshu@zyanshukvm:~/minikube$
zyanshu@zyanshukvm:~/minikube$ ./out/minikube start --driver=kvm2 --delete-on-failure
😄  minikube v1.16.0 on Debian rodete
    ▪ MINIKUBE_ACTIVE_DOCKERD=p1

💢  Exiting due to GUEST_DRIVER_MISMATCH: The existing "minikube" cluster was created using the "docker" driver, which is incompatible with requested "kvm2" driver.
💡  Suggestion: Delete the existing 'minikube' cluster using: 'minikube delete', or start the existing 'minikube' cluster using: 'minikube start --driver=docker'

zyanshu@zyanshukvm:~/minikube$
zyanshu@zyanshukvm:~/minikube$
zyanshu@zyanshukvm:~/minikube$
zyanshu@zyanshukvm:~/minikube$ ./out/minikube profile list
|----------|-----------|---------|--------------|------|---------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes |
|----------|-----------|---------|--------------|------|---------|---------|-------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.20.0 | Running |     1 |
|----------|-----------|---------|--------------|------|---------|---------|-------|

```

**Comment by azhao155** [comment]
If we really want to delete the existing cluster, I also have the pr: https://github.com/kubernetes/minikube/pull/10084

**Comment by medyagh** [comment]
closed by https://github.com/kubernetes/minikube/pull/10084
