### ISSUE TITLE
localkube leaving 'wc' zombies

### ISSUE THREAD

**Issue by ankon** [kubernetes/minikube#940]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT.

**Minikube version** (use `minikube version`):
minikube version: v0.14.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Fedora 25 x86_64
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): kvm
- **Docker version** (e.g. `docker -v`): Docker version 1.12.5, build 6009905/1.12.5

Noticed the issue both with minikube v0.14.0 and v0.13.1, cannot remember whether I saw it with earlier versions.

**What happened**:

I'm looking inside the VM with `top`, and I see a *lot* of `wc` processes in Z state, under the localkube process. Watching it for a while: There is a `du` process that quickly goes away, and then a `wc`, which sometimes but not always doesn't seem to get reaped. Eventually the VM can have hundreds of these zombies.

**What you expected to happen**:

Zombie-free environment :)

**How to reproduce it** (as minimally and precisely as possible):

For me it just happens when running the VM with some pods in it, nothing "special" is done.

**Anything else do we need to know**:

Guess: It's somewhere in vendor/github.com/google/cadvisor/fs/fs.go, which seems to talk about `du` and `wc` processes. My go-foo isn't anywhere close to knowing how to debug it further.

![screen-minikube-wc-zombies](https://cloud.githubusercontent.com/assets/1210641/21343692/43a3d22c-c698-11e6-8377-0d5e19896630.png)

**Comment by r2d4** [comment]
This has already been fixed in the new ISO
http://storage.googleapis.com/minikube/iso/buildroot/minikube-v1.0.1.iso

However, we haven't backported a fix to the b2d ISO yet.

ref https://github.com/kubernetes/minikube/issues/923


> When find exits with an error, the wait for the wc process never happens and wc becomes a zombie. On systems without GNU find, these zombies can accrue quickly.

**Comment by ankon** [comment]
Thanks for the reply.

Quickly tested it with `minikube start --vm-driver virtualbox --iso-url https://storage.googleapis.com/minikube/iso/minikube-v1.0.1.iso --kubernetes-version v1.4.5 --memory 4096`, looks good!

**Comment by dlorenc** [comment]
We're not going to backport this to the old iso, this will be fixed in the new ISO in our next release.
