### ISSUE TITLE
FR/crazy idea: delete context when minikube is stopped

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#9410]
The context isn't useful if minikube is stopped, and can mislead folks into talking to a stopped cluster. What if, instead of unselecting it as a default, we just deleted it.

**Comment by prezha** [comment]
not so crazy ;) `.kube/config` gets filled back in with the cluster data on subsequent minikube start - when it can actually be used again

**Comment by tstromberg** [comment]
Thank you @prezha !

**Comment by medyagh** [comment]
@tstromberg this could break the IDE users.  per this request, https://github.com/kubernetes/minikube/issues/9001

@prezha please make sure, this does NOT delete the context if the user has specified 
"--keep-context-active=false"

**Comment by prezha** [comment]
@medyagh yes, the same logic still applies: if `keep-context-active` is set to true, it will not touch the context

**Comment by jorgemoralespou** [comment]
This is not nice. Now, as the context is deleted and recreated, a user needs to select a specific namespace he's working on every time he starts/stops the cluster.

**Comment by prezha** [comment]
@jorgemoralespou you can use `--keep-context-active=true` option to keep the context on `minikube stop`?

**Comment by jorgemoralespou** [comment]
I was expecting that answer. Why would I want to keep the context active if the instance is stopped. When stopped what does make sense is unset, and only delete the context when minikube instance is deleted, hence, previous behavior.

**Comment by prezha** [comment]
i don't think the issue is with deleting/recreating the context when minikube stops/starts, what we potentially could do is additionally saving/restoring also the default namespace

**Comment by jorgemoralespou** [comment]
Yes, you could save/restore the namespace. But IMHO the fact that a namespace is deleted is more confusing than the fact that minikube is stopped and you have a context you can't connect to until you start minikube.
