### ISSUE TITLE
automate pushing kicbase image from snapshot to stable after release

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9420]
before release each time we build the kic base image we add the snashotX to it
for example
https://github.com/medyagh/minikube/blob/32922f4184c31fb405fb8dab7a1d7a8ef120b47a/pkg/drivers/kic/types.go#L27
	Version = "v0.0.13-snapshot1"

this is good for when multiple people make corrections before a release, and once it is finalized, before the release we do this
```
docker tag kicbase/stable:v0.0.13-snapshot1 kicbase/stable:v0.0.13
docker tag kicbase/stable:v0.0.13 gcr.io/k8s-minikube/kicbase:v0.0.13
docker tag kicbase/stable:v0.0.13 docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.13
docker push kicbase/stable:v0.0.13
docker push gcr.io/k8s-minikube/kicbase:v0.0.13
docker push docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.13
```

and change the types.go in kic package 
https://github.com/medyagh/minikube/blob/32922f4184c31fb405fb8dab7a1d7a8ef120b47a/pkg/drivers/kic/types.go#L27

**Comment by prezha** [comment]
@medyagh i've created pr (#9439) to automate pushing kicbase image, please have a look

a few notes (details are in code comments):
- there are some env vars required for passing credentials
- "GitHub Packages Docker registry will be superseded by GitHub Container Registry." ([ref](https://docs.github.com/en/free-pro-team@latest/packages/using-github-packages-with-your-projects-ecosystem/configuring-docker-for-use-with-github-packages#about-docker-and-github-packages)) - maybe we should plan to migrate in (near) future
- this pr does _not_ cover updating corresponding `Version` in `types.go` in `kic` package atm - reason: open questions & proposal:
1. out of the three registries, what is/are minimally acceptable combination(s) of successful/failed updates - ie, which we would accept to fail and still update `Version` in `pkg/drivers/kic/types.go`? eg, just gcr is enough, or, at least gcr and one another, or, all three must be updated, etc.
2. when we (locally) update the `Version` in `types.go`, wouldn't we also want a pr to be automatically created (if one doesn't exist already)? that would also allow it to run as a standalone script
   if so, we could nicely combine this with eg, issue #9264 (i have improved version) with the approach proposed in issue #4392 (pr #9384) and potentially any other issue that needs versions or any other value(s) updated in file(s)
here, i would send out a complete proposal, just waiting to first agree on the proposed approach in issue #4392 (pr #9384) and confirmation that the existing pr #9280 is correct

please share your thoughts

**Comment by prezha** [comment]
@medyagh i've assumed that:
1. it would be acceptable to have at least one registry updated (that can be easily changed if needed), and so
2. i've included the `updating corresponding Version in types.go in kic package`, as well as automatically creating respective (unique) pr, as part of pr #9464 

so this issue should be covered now
