### ISSUE TITLE
While downloading installing minikube  getting below error

### ISSUE THREAD

**Issue by tanmayi2010** [kubernetes/minikube#9437]
❌  Exiting due to HOST_VTX_UNAVAILABLE: Failed to start host: creating host: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.258579 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
💡  Suggestion: Your host does not support virtualization. If you are running minikube within a VM, try '--driver=docker'. Otherwise, enable virtualization in your BIOS
🍿  Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/1994
    ▪ https://github.com/kubernetes/minikube/issues/5326

**Comment by sharifelgamal** [comment]
Hey @tanmayi2010, I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The OS you're running minikube on

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

Thank you for sharing your experience!

**Comment by ilya-zuyev** [comment]
@tanmayi2010 any update?

**Comment by priyawadhwa** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!
