### ISSUE TITLE
minikube启动ingress失败

### ISSUE THREAD

**Issue by jyozq** [kubernetes/minikube#9440]
`minikube start --image-mirror-country=cn --vm-driver=docker --base-image=kicbase/stable:v0.0.12-snapshot3 --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers --registry-mirror=https://ytsch4ca.mirror.aliyuncs.com --insecure-registry=192.168.43.128:1180`
使用以上命令启动minikube之后，无法启动ingress

**重现问题所需的命令**：minikube addons enable ingress

**失败的命令的完整输出**：<details>
I1012 16:10:40.904427  294296 addons.go:55] Setting ingress=true in profile "minikube"
I1012 16:10:40.904478  294296 addons.go:131] Setting addon ingress=true in "minikube"
I1012 16:10:40.904526  294296 host.go:65] Checking if "minikube" exists ...
I1012 16:10:40.905003  294296 cli_runner.go:110] Run: docker container inspect minikube --format={{.State.Status}}
I1012 16:10:40.943888  294296 addons.go:243] installing /etc/kubernetes/addons/ingress-configmap.yaml
I1012 16:10:40.943924  294296 ssh_runner.go:215] scp deploy/addons/ingress/ingress-configmap.yaml.tmpl --> /etc/kubernetes/addons/ingress-configmap.yaml (1251 bytes)
I1012 16:10:40.943979  294296 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1012 16:10:40.981523  294296 sshutil.go:44] new ssh client: &{IP:127.0.0.1 Port:32787 SSHKeyPath:/home/java/.minikube/machines/minikube/id_rsa Username:docker}
I1012 16:10:41.084226  294296 addons.go:243] installing /etc/kubernetes/addons/ingress-rbac.yaml
I1012 16:10:41.084251  294296 ssh_runner.go:215] scp deploy/addons/ingress/ingress-rbac.yaml.tmpl --> /etc/kubernetes/addons/ingress-rbac.yaml (4828 bytes)
I1012 16:10:41.100940  294296 addons.go:243] installing /etc/kubernetes/addons/ingress-dp.yaml
I1012 16:10:41.100961  294296 ssh_runner.go:215] scp memory --> /etc/kubernetes/addons/ingress-dp.yaml (8485 bytes)
I1012 16:10:41.118232  294296 ssh_runner.go:148] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.0/kubectl apply -f /etc/kubernetes/addons/ingress-configmap.yaml -f /etc/kubernetes/addons/ingress-rbac.yaml -f /etc/kubernetes/addons/ingress-dp.yaml
I1012 16:10:41.306442  294296 addons.go:331] Verifying addon ingress=true in "minikube"
I1012 16:10:41.307171  294296 out.go:109] * Verifying ingress addon...
* Verifying ingress addon...
I1012 16:10:41.308967  294296 kapi.go:75] Waiting for pod with label "app.kubernetes.io/name=ingress-nginx" in ns "kube-system" ...
I1012 16:10:41.325672  294296 kapi.go:86] Found 3 Pods for label selector app.kubernetes.io/name=ingress-nginx
I1012 16:10:41.325738  294296 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I1012 16:10:41.829613  294296 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
...
I1012 16:13:41.333864  294296 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I1012 16:13:41.333900  294296 kapi.go:108] duration metric: took 3m0.024936732s to wait for app.kubernetes.io/name=ingress-nginx ...
I1012 16:13:41.334596  294296 out.go:109] 

W1012 16:13:41.334713  294296 out.go:145] X Exiting due to MK_ENABLE: run callbacks: running callbacks: [verifying ingress addon pods : timed out waiting for the condition: timed out waiting for the condition]
X Exiting due to MK_ENABLE: run callbacks: running callbacks: [verifying ingress addon pods : timed out waiting for the condition: timed out waiting for the condition]
W1012 16:13:41.334852  294296 out.go:145] * 
* 
W1012 16:13:41.334871  294296 out.go:145] * If the above advice does not help, please let us know: 
* If the above advice does not help, please let us know: 
W1012 16:13:41.334888  294296 out.go:145]   - https://github.com/kubernetes/minikube/issues/new/choose  - https://github.com/kubernetes/minikube/issues/new/choose
I1012 16:13:41.335569  294296 out.go:109] 

</details>

**使用的操作系统版本**：
CentOS Linux release 7.8.2003
minikube version: v1.13.0

**Comment by RA489** [comment]
@jyozq can you please try this WIP PR https://github.com/kubernetes/minikube/pull/8555 as workaround?

**Comment by ilya-zuyev** [comment]
@jyozq if the issue still exists, do you mind trying minikube v1.18.1? Thanks!

**Comment by medyagh** [comment]
Hi @jyozq , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
