### ISSUE TITLE
x509: certificate is valid for 192.168.99.100, 10.96.0.1, 127.0.0.1, 10.0.0.1, not 192.168.99.101

### ISSUE THREAD

**Issue by Ganesh0509** [kubernetes/minikube#9441]
**Steps to reproduce the issue:** 

1.Install latest version of minikube for windows using windows installer  from https://minikube.sigs.k8s.io/docs/start/
2. minikube start
3.After few minutes below exception will come 

**Full output of failed command:** 

C:\Users\Ganesh>minikube start
* minikube v1.13.1 on Microsoft Windows 10 Home Single Language 10.0.19041 Build 19041
* Kubernetes 1.19.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.19.2
* Using the virtualbox driver based on existing profile
* Downloading VM boot image ...
    > minikube-v1.13.1.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.13.1.iso: 173.91 MiB / 173.91 MiB  100.00% 109.54 KiB p/s 27m
* Starting control plane node minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Found network options:
  - NO_PROXY=192.168.99.100,192.168.99.101
  - no_proxy=192.168.99.100,192.168.99.101
* Preparing Kubernetes v1.19.0 on Docker 19.03.12 ...
  - env NO_PROXY=192.168.99.100,192.168.99.101
! Unable to restart cluster, will reset it: apiserver health: controlPlane never updated to v1.19.0
* Verifying Kubernetes components...
! Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.99.101:8443/apis/storage.k8s.io/v1/storageclasses": x509: certificate is valid for 192.168.99.100, 10.96.0.1, 127.0.0.1, 10.0.0.1, not 192.168.99.101]
* Enabled addons: default-storageclass, storage-provisioner

X Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.0
*

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@Ganesh0509 starting  v1.14.0 we introduced Static IP with docker driver do you mind trying latest version of minikube and docker driver to see if that fixes that issue ?
(delete previous clsuter and start with new driver)

**Comment by Ganesh0509** [comment]
@medyagh  , I am using minikube version: v1.13.1
Yesterday I fallowed the below steps and it works 

**minikube delete
rm -rf ~/.minikube/**


I am using above version from past few months am not sure why all of sudden minikube start started failing with above version Yesterday
