### ISSUE TITLE
minikube does not switch drivers

### ISSUE THREAD

**Issue by kphatak** [kubernetes/minikube#945]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.13.1

**Environment**:
- **OS** (e.g. from /etc/os-release): macOS Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox and xhyve
- **Docker version** (e.g. `docker -v`): Docker version 1.12.5, build 7392c3b
- **Install tools**: NA
- **Others**: NA

**What happened**:
I was running minikube using virtualbox and wanted to change to use native xhyve. Even after specifying --vm-driver xhyve option, it still started existing virtualbox VM. Debug logging showed it is defaulted to old driver.
I had to delete machine explicitly and then deploy again using xhyve

**What you expected to happen**:
It should ignore existing deployment and use provided option.
OR give a warning saying defaulting to old driver as machine exists.

**How to reproduce it** (as minimally and precisely as possible):
Start minikube using no vm-driver option and then without deleting machine try deploying using xhyve.

**Comment by r2d4** [comment]
If theres a running machine, we can't really switch the driver on the fly.  We should definitely put a warning if the machine is running with different options than what was passed in.

**Comment by r2d4** [comment]
I don't think we're going to implement this.

**Comment by dctucker** [comment]
I agree with r2d4, it's rather confusing that the only way to find out which driver was used is to pay attention to `top` or Activity Monitor to see which processes are eating cycles and memory. It would be helpful to issue a warning, or even something as simple as printing which driver is used instead of the vague `Starting VM...` message.
