### ISSUE TITLE
Release: Jenkins does not update the release notes on github 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9451]
for past two releases 
https://github.com/kubernetes/minikube/releases/tag/v1.14.0
and
https://github.com/kubernetes/minikube/releases/tag/v1.14.0-beta.0

we have been updating the release notes manually. 

I ran the command in the script manually and it seems that it is not matching
[hack/jenkins/release_github_page.sh](https://github.com/medyagh/minikube/blob/b09ee50ec047410326a85435f4d99026f9c4f5c4/hack/jenkins/release_github_page.sh#L43-L44)

```
medya@~/workspace/minikube (master) $ 
medya@~/workspace/minikube (master) $ RELEASE_NOTES=$(perl -e "\$p=0; while(<>) { if(/^## Version ${VERSION} -/) { \$p=1 } elsif (/^##/) { \$p=0 }; if (\$p) { print }}" < CHANGELOG.md)
medya@~/workspace/minikube (master) $ 
medya@~/workspace/minikube (master) $ echo $RELEASE_NOTES 


```

**Comment by tstromberg** [comment]
Looking at the v1.15.1 logs on Jenkins, this seems to either have been fixed, or be more subtle than it appears.

**Comment by tstromberg** [comment]
I can confirm that this was definitely broken in v1.14.0, however:

`+ perl -e '$p=0; while(<>) { if(/^## Version 1.14.0 -/) { $p=1 } elsif (/^##/) { $p=0 }; if ($p) { print }}'`

It should be easy enough to isolate what's going wrong here.
