### ISSUE TITLE
Unable to run minikube start with docker driver on ChromeOS

### ISSUE THREAD

**Issue by pushp1997** [kubernetes/minikube#9472]
**Steps to reproduce the issue:** 

1. minikube start --driver=docker

**Full output of failed command:** 

 pushp.vashisht@penguin$ minikube start
😄  minikube v1.13.1 on Debian 10.6
✨  Using the docker driver based on user configuration
💨  For improved Docker performance, enable the overlay Linux kernel module using 'modprobe overlay'
❗  docker is currently using the btrfs storage driver, consider switching to overlay2 for better performance
👍  Starting control plane node minikube in cluster minikube
🎉  minikube 1.14.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.14.0
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=3600MB) ...
✋  Stopping node "minikube"  ...
🔥  Deleting "minikube" in docker ...
🤦  StartHost failed, but will try again: creating host: create: creating: create kic node: container name "minikube": log: 2020-10-15T09:39:42.381192803Z  + echo 'INFO: remounting /sys read-only'
2020-10-15T09:39:42.381200274Z  INFO: remounting /sys read-only
2020-10-15T09:39:42.381206183Z  + mount -o remount,ro /sys
2020-10-15T09:39:42.388276825Z  mount: /sys: permission denied.: container exited unexpectedly

**Optional: Full output of `minikube logs` command:**
<details>

 pushp.vashisht@penguin$ minikube logs
🤷  The control plane node must be running for this command
👉  To fix this, run: "minikube start"

</details>

**Comment by pushp1997** [comment]
I tried to run it after installing v1.14.0 as well and got the same error.

**Comment by afbjorklund** [comment]
Which docker version and platform is this ? We now that we have this issue on ChromeOS: #6411

**Comment by pushp1997** [comment]
Yes, I am on ChromeOS. Sorry I didnt know that its a known issue. Thanks @afbjorklund
