### ISSUE TITLE
stopping a profile which doesn't exists creates profile folder instead of just throwing error

### ISSUE THREAD

**Issue by vinu2003** [kubernetes/minikube#9486]
##minikube stop##
vinodhinis-mbp:minikube vinodhinibalusamy$ ./out/minikube stop -p test2
🤷  There is no local cluster named "test2"
👉  To fix this, run: "minikube start -p test2"

this causes unwanted error message thrown in profile list.

vinodhinis-mbp:minikube vinodhinibalusamy$ ./out/minikube profile list
|----------|-----------|---------|--------------|------|---------|---------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  |
|----------|-----------|---------|--------------|------|---------|---------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.19.2 | Running |
| test1    | docker    | docker  | 192.168.59.2 | 8443 | v1.19.2 | Running |
|----------|-----------|---------|--------------|------|---------|---------|
❗  Found 2 invalid profile(s) ! 
	 test2
	 ttt
💡  You can delete them using the following command(s): 
	 $ minikube delete -p test2 
	 $ minikube delete -p ttt 
vinodhinis-mbp:minikube vinodhinibalusamy$ 

And i did notice /Users/vinodhinibalusamy/.minikube/profiles has test2 folder created which shouldn't be.

**Comment by tstromberg** [comment]
Good catch! Help wanted to fix this -- there is no reason why `minikube stop` should cause a profile to be created.

**Comment by vinu2003** [comment]
thank you.
/assign @vinu2003
