### ISSUE TITLE
The connection to the server 127.0.0.1:32768 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by toluwaanimi** [kubernetes/minikube#9488]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube` command lines used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by medyagh** [comment]
@toluwaanimi I haven't heard from you, I will close this issue, please feel free to reopen once ready

**Comment by Samba73** [comment]
> I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:
> 
> * The exact `minikube` command lines used
> * The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
> * The full output of `minikube logs`
> 
> Thank you for sharing your experience!

I had similar issue and tried this and it started to work
