### ISSUE TITLE
Unable to pull from k8s.gcr.io: failed: write: stream error: stream ID X; INTERNAL_ERROR

### ISSUE THREAD

**Issue by nicolasduminil** [kubernetes/minikube#9491]
**Steps to reproduce the issue:** 

1. minikube start

**Full output of failed command:** 
😄  minikube v1.14.0 on Ubuntu 20.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E1019 17:49:35.843193  342171 cache.go:63] save image to file "k8s.gcr.io/kube-scheduler:v1.19.2" -> "/home/nicolas/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.19.2" failed: write: stream error: stream ID 33; INTERNAL_ERROR
E1019 17:49:36.599773  342171 cache.go:63] save image to file "k8s.gcr.io/kube-controller-manager:v1.19.2" -> "/home/nicolas/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.19.2" failed: write: stream error: stream ID 31; INTERNAL_ERROR
E1019 17:51:34.285395  342171 cache.go:63] save image to file "k8s.gcr.io/pause:3.2" -> "/home/nicolas/.minikube/cache/images/k8s.gcr.io/pause_3.2" failed: write: stream error: stream ID 17; INTERNAL_ERROR
E1019 17:51:35.413105  342171 cache.go:63] save image to file "gcr.io/k8s-minikube/storage-provisioner:v3" -> "/home/nicolas/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v3" failed: write: stream error: stream ID 13; INTERNAL_ERROR

**Comment by tstromberg** [comment]
This appears to be some kind of HTTTP server error (500 error code) emanating from GCR.

Can you try again with `--alsologtostderr -v=1` to see the situation cleared up? If not, it will add additional logging which will be helpful.

What's interesting here is that we also failed to be able to download the preload image, which is the only reason we fell back to pull the individual images.

**Comment by priyawadhwa** [comment]
Hey @nicolasduminil were you able to try again?

**Comment by medyagh** [comment]
@nicolasduminil is your company using a image repository and blocking traffic to gcr.io ? do u mind check connectivity with gcr.io
