### ISSUE TITLE
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)

### ISSUE THREAD

**Issue by ParagNetApp** [kubernetes/minikube#9497]
**Steps to reproduce the issue:** 

1. minikube version: v1.12.2, 
    Microsoft Windows 10 Enterprise , Version 10.0.18363 Build 18363
    Virtual Box  version : Version 6.1.12 r139181 (Qt5.6.2)
    Processor :  Intel® Core™ i5-7300U Processor
   
2. Start minikube as minikube start --driver=virtualbox  --disk-size=40000mb --no-vtx-check 
3.

**Full output of failed command:** 
c:\work>minikube delete --all --purge
* Successfully deleted all profiles
* Successfully purged minikube directory located at - [C:\Users\paragp\.minikube]

c:\work>minikube start --driver=virtualbox  --disk-size=40000mb --no-vtx-check
* minikube v1.12.2 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the virtualbox driver based on user configuration
* minikube 1.14.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.14.0
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

* Downloading VM boot image ...
    > minikube-v1.12.2.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.12.2.iso: 173.73 MiB / 173.73 MiB [] 100.00% 3.44 MiB p/s 51s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v5-v1.18.3-docker-overlay2-amd64.tar.lz4: 510.91 MiB
* Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=40000MB) ...
* Deleting "minikube" in virtualbox ...
! StartHost failed, but will try again: creating host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: VMMR0_DO_NEM_INIT_VM failed: VERR_NEM_MISSING_KERNEL_API_2 (VERR_NEM_MISSING_KERNEL_API_2).
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:02.877441 Power up failed (vrc=VERR_VMX_NO_VMX, rc=E_FAIL (0X80004005))
* Failed to start virtualbox VM. "minikube start" may fix it: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\paragp\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
X error provisioning host: Failed to start host: Error loading existing host. Please try running [minikube delete], then run [minikube start] again.: filestore "minikube": open C:\Users\paragp\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
*
X Unable to get machine status: load: filestore "minikube": open C:\Users\paragp\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**Comment by tstromberg** [comment]
It sounds like VirtualBox may not be properly installed on this machine:

```
C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: VMMR0_DO_NEM_INIT_VM failed: VERR_NEM_MISSING_KERNEL_API_2 (VERR_NEM_MISSING_KERNEL_API_2).
VBoxManage.exe: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole
```

Can you can test with another non-minikube image? https://www.osboxes.org/virtualbox-images/ has some -- for instance, the Debian server image might be helpful here.

**Comment by tstromberg** [comment]
Please let me know what you find out so that we can improve this error message.

**Comment by medyagh** [comment]
@ParagNetApp 
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!


Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by yuriaps** [comment]
This worked for me

https://stackoverflow.com/questions/37955942/vagrant-up-vboxmanage-exe-error-vt-x-is-not-available-verr-vmx-no-vmx-code#_=_

minikube start --driver=virtualbox --disk-size=40000mb --no-vtx-check
