### ISSUE TITLE
tunnel instructions are broken (wrong port): Connection reset by peer

### ISSUE THREAD

**Issue by GRXself** [kubernetes/minikube#9498]
In this [article](https://minikube.sigs.k8s.io/docs/start/), I followed the steps to create a deployment using **type=LoadBalancer**, but I found I can not visit the app after tunnel. When I curl http://localhost:8000, I got connection reset
In this article, the command is as follows:
**kubectl create deployment balanced --image=k8s.gcr.io/echoserver:1.4  
kubectl expose deployment balanced --type=LoadBalancer --port=8000
minikube tunnel
kubectl get services balanced**

I tried to change the expose port to 8080:
**kubectl expose deployment balanced --type=LoadBalancer --port=8080**
After this change, I can curl http://localhost:8080.

I'm new to k8s, I think the guide in this article just give a wrong port, please check it.

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command
*  Any chance you are running minikube on Windows within WSL2?

Thank you for sharing your experience!

**Comment by GRXself** [comment]
Before I start, I want to say that it should be a wrong port use in the getting start documentation.

I was following the get start documentation, and the following is my environment and what I ran in my terminal:

**Environment:**

- OS: macOS Catalina version 10.15.7
- Docker version: 19.03.13
- minikube version: v1.14.0
- kubectl version:
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Command and output:(step to reproduce)**
`minikube start`
> 😄  minikube v1.14.0 on Darwin 10.15.7
> ✨  Automatically selected the docker driver
> 👍  Starting control plane node minikube in cluster minikube
> 🚜  Pulling base image ...
> 🔥  Creating docker container (CPUs=2, Memory=1990MB) ...
> 🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.8 ...
>     > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
>     > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
>     > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
>     > kubeadm: 37.30 MiB / 37.30 MiB [-----------] 100.00% 242.25 KiB p/s 2m37s
>     > kubectl: 41.01 MiB / 41.01 MiB [------------] 100.00% 225.93 KiB p/s 3m6s
>     > kubelet: 104.88 MiB / 104.88 MiB [---------] 100.00% 399.69 KiB p/s 4m29s
> 🔎  Verifying Kubernetes components...
> 🌟  Enabled addons: storage-provisioner, default-storageclass
> 🏄  Done! kubectl is now configured to use "minikube" by default

`kubectl create deployment balanced --image=k8s.gcr.io/echoserver:1.4`
> deployment.apps/balanced created

`kubectl expose deployment balanced --type=LoadBalancer --port=8000`
> service/balanced exposed

`minikube tunnel`
> 🏃  Starting tunnel for service balanced.

Then using command `kubectl get services balanced`, I got the EXTERNAL-IP, and when trying to use this IP and port 8000, my browser say 
> The connection was reset.

If I change the port to 8080, all the thing works fine.

**My thoughts:**
In minikube get started documentation, the 4th part `Deploy applications`, in [LoadBalancer deployments](https://minikube.sigs.k8s.io/docs/start/#loadbalancer-deployments) part, it gives a command `kubectl expose deployment balanced --type=LoadBalancer --port=8000` to let us to expose the port 8000, but the get started documentation are using an image listening to port **8080**, so that's why I visit port **8000** and got a connection reset.

**Comment by tstromberg** [comment]
I was able to confirm this behavior, FWIW. With v1.4.0 and v1.3.1.

**Comment by tstromberg** [comment]
Funny enough, I wasn't able to get the tunnel instructions on https://minikube.sigs.k8s.io/docs/start/ to work with hyperkit either, so I'm even more confused now.

**Comment by tstromberg** [comment]
Can someone follow-up to say they've gotten tunnel to work, or not work, with minikube v1.4.1 on the Docker driver on macOS?

**Comment by GRXself** [comment]
In my view, there is nothing wrong in tunnel, just a wrong port given in [get started documentation](https://minikube.sigs.k8s.io/docs/start/).
If I expose the deployment in the port the docker image expose, it will work. I packaged my own image later and tested this behavior with different port, the `kubectl expose deployment balanced --type=LoadBalancer --port=8000` command should expose the port specified in the image showed  in `kubectl create deployment balanced --image=k8s.gcr.io/echoserver:1.4` create command.
I also find another documentation refering about the port, it's in [Create a Service](https://kubernetes.io/docs/tutorials/hello-minikube/#create-a-service) chapter. It says:
> The application code inside the image k8s.gcr.io/echoserver only listens on TCP port 8080. If you used kubectl expose to expose a different port, clients could not connect to that other port.

So the [get started documentation](https://minikube.sigs.k8s.io/docs/start/) is giving a wrong command in its [LoadBalancer deployments](https://minikube.sigs.k8s.io/docs/start/#loadbalancer-deployments) part.

**Comment by GRXself** [comment]
I'm trying to give a PR(https://github.com/kubernetes/minikube/pull/9511), only change the md file, but failed unit test. I'm lacking the knowledge of Go, I'll try to run the test in my local, but I don't know if I can handle it in few days.

**Comment by tstromberg** [comment]
Good call. Thank you for noticing that -- I wonder where along the lines we got this confused in our getting started doc.

**Comment by tstromberg** [comment]
I can confirm that this now works as expected. Thank you so much for pointing this out & offering an easy solution.
