### ISSUE TITLE
docs: Installation is null

### ISSUE THREAD

**Issue by lengrongfu** [kubernetes/minikube#9507]
![image](https://user-images.githubusercontent.com/15009201/96670125-3bd60700-1391-11eb-91fd-c29d8c985a30.png)
Installation is null

**Comment by tstromberg** [comment]
What URL are you looking at?

https://minikube.sigs.k8s.io/docs/start/ shows the content -- at least with Javascript enabled:

![Screen Shot 2020-10-20 at 9 09 25 PM](https://user-images.githubusercontent.com/101424/96672248-9b440080-1318-11eb-8fe1-274fc1379e53.png)
