### ISSUE TITLE
minikube does not respect global options for logging

### ISSUE THREAD

**Issue by kschaab** [kubernetes/minikube#9518]
**Steps to reproduce the issue:** 

1. minikube [command] --log_dir or minikube [command] --logtostderr
2. note that log_dir is ignored and $TMPDIR is used instead.  When --logtostderr is specified the logs are output to stderr *and* $TMPDIR rather than what is specified: `--logtostderr=false: log to standard error instead of files`

Commands used:
```
minikube status --logtostderr 
minikube status --log_dir=/Users/keithsc/foo 
```

These commands are critical to purge the logs that come from calling into minikube frequently and disassociate unconsequential logs from those that are of consequence.

**Comment by kschaab** [comment]
This will help fix https://github.com/GoogleCloudPlatform/cloud-code-vscode/issues/286.

**Comment by tstromberg** [comment]
It's worth noting that we just changed from glog to klog at master, so behaviors may be different.

`--log_dir` hasn't worked so long as I've been on this project.

I did notice that the new `--log_file` flag also doesn't work.

**Comment by afbjorklund** [comment]
There was some copying of flags, maybe that _could_ have worked.

**Comment by kschaab** [comment]
Shouldn't this work (from https://github.com/kubernetes/minikube/commit/af5fbf78802c9ab0c84051a8b7f6ca0b094ac057)?

```
	klogFlags := flag.NewFlagSet("klog", flag.ExitOnError)
	klog.InitFlags(klogFlags)

	// Sync the glog and klog flags.
	flag.CommandLine.VisitAll(func(f1 *flag.Flag) {
		f2 := klogFlags.Lookup(f1.Name)
		if f2 != nil {
			value := f1.Value.String()
			f2.Value.Set(value)
		}
	})
```

**Comment by sharifelgamal** [comment]
We now support `--log_dir` and `--log_file`, but there are other outstanding issues with it, namely #9156
