### ISSUE TITLE
Sorry that minikube crashed. If this was unexpected, we would love to hear from you

### ISSUE THREAD

**Issue by Jagadeeshmopuri** [kubernetes/minikube#9546]
C:\WINDOWS\system32>minikube start
* minikube v1.5.2 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Using the running hyperv "minikube" VM ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
*
X Failed to update cluster: downloading binaries: copybinary C:\Users\welcome\.minikube\cache\v1.16.2/kubelet -> /var/lib/minikube/binaries/v1.16.2/kubelet: copy: sudo mkdir -p /var/lib/minikube/binaries/v1.16.2 && sudo scp -t /var/lib/minikube/binaries/v1.16.2: Process exited with status 1
output:  scp: /var/lib/minikube/binaries/v1.16.2/kubelet: Text file busy
scp: protocol error: expected control record

*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by tstromberg** [comment]
This has been fixed in more recent versions of minikube. Please update to minikube v1.14.1. Thank you!
