### ISSUE TITLE
Minikube open browser Ubuntu

### ISSUE THREAD

**Issue by cezeno2s** [kubernetes/minikube#9555]
**Steps to reproduce the issue:** 
I am trying to run the hello world service I deployed and exposed but after running  "minikube service helloworld", I am getting an error message instead of minikube launching the service on my default browser. Please can someone help me to fix the error.

**Full output of failed command:** 

david@Ubuntu-VirtualBox:~/Downloads/project/Ex_Files_Learning_Kubernetes_Upd/Exercise Files/03_04$ minikube service helloworld
|-----------|------------|-------------|---------------------------|
| NAMESPACE |    NAME    | TARGET PORT |            URL            |
|-----------|------------|-------------|---------------------------|
| default   | helloworld |          80 | http://192.168.49.2:30357 |
|-----------|------------|-------------|---------------------------|
🎉  Opening service default/helloworld in default browser...
/usr/bin/xdg-open: 869: www-browser: not found
/usr/bin/xdg-open: 869: links2: not found
/usr/bin/xdg-open: 869: elinks: not found
/usr/bin/xdg-open: 869: links: not found
/usr/bin/xdg-open: 869: lynx: not found
/usr/bin/xdg-open: 869: w3m: not found
xdg-open: no method available for opening 'http://192.168.49.2:30357'

❌  Exiting due to HOST_BROWSER: exit status 3

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
What happens if you try the URL in a browser manually? It just looks like minikube can't find a default browser to open the URL in.

**Comment by cezeno2s** [comment]
It works when I try the URL manually on a browser but how can I resolve the
issue of minikube not being able to find a default browser to open the URL
directly?

**Comment by medyagh** [comment]
@cezeno2s do u mind sharing more about your operating system `lsb_release -a`

**Comment by medyagh** [comment]
@cezeno2s it seems like u are running ubuntu on virtualbox does it have a GUI ?

**Comment by OleksiiPasihnyk** [comment]
But it still does nolt work with the same setup and config for me. 

when I use minikube service "name of the service here" command I'm expecting to get service opened in the default browser
