### ISSUE TITLE
Remove failing jenkins Agents and install New ones

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9558]
sometimes KVM test failes unusually with very high numbers on some Jenkins agents with 95+ failures.

example:
https://storage.googleapis.com/minikube-builds/logs/9557/777ac14/KVM_Linux.html

https://storage.googleapis.com/minikube-builds/logs/9557/KVM_Linux.txt
shows that it is agent 7

```
 Building remotely on GCP - Linux 7 (special kvm linux kic-docker docker gcp-linux) in workspace /home/jenkins/workspace/KVM_Linux_integration
```

**Comment by medyagh** [comment]
simmilar to this Docker Driver Test
that sometimes failes 18 tests and sometimes 1 test

https://storage.googleapis.com/minikube-builds/logs/9559/f7baa9c/Docker_Linux.html
https://storage.googleapis.com/minikube-builds/logs/9559/Docker_Linux.txt
(Building remotely on GCP - Linux 8 KIC (kic kic-docker))

**Comment by priyawadhwa** [comment]
We fixed this by adding timeouts to cleaning up kvm networks and making sure we reboot the machine daily.
