### ISSUE TITLE
add initial integration tests for google cloud shell

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9560]
minikube integeration tests should run against cloud shell

**Comment by medyagh** [comment]
```
medya@~/workspace/minimedya $ gcloud beta cloud-shell ssh
Automatic authentication with GCP CLI tools in Cloud Shell is disabled. To enable, please rerun command with `--authorize-session` flag.
Welcome to Cloud Shell! Type "help" to get started.
Your Cloud Platform project in this session is set to k8s-minikube.
Use “gcloud config set project [PROJECT_ID]” to change to a different project.
```

**Comment by priyawadhwa** [comment]
Setup `minikube start` @ HEAD in our performance tracking dashboard in Cloud Shell for crio/docker runtimes. containerd won't work in Cloud Shell until it uses the `systemd` cgroup manager.

This dashboard will:
1. make sure `minikube start` works in cloud shell with both runtimes
1. makes sure it isn't slowing down

and alert if either of those is untrue.
