### ISSUE TITLE
 Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""

### ISSUE THREAD

**Issue by abdou91** [kubernetes/minikube#9564]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by medyagh** [comment]
@abdou91 I haven't heard from you, I will close this, please reopen once ready to give more information
