### ISSUE TITLE
minikube error to start

### ISSUE THREAD

**Issue by andresb39** [kubernetes/minikube#9565]
**Los comandos necesarios para reproducir la incidencia**:
Instalacion de minikube en fedora32

**El resultado completo del comando que ha fallado**: <details>
 minikube start --driver=docker

</details>

**El resultado del comando `minikube logs`**: <details>
StartHost failed, but will try again: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --network minikube --ip 192.168.49.2 --volume minikube:/var --security-opt apparmor=unconfined --memory=3400mb --memory-swap=3400mb --cpus=2 -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 gcr.io/k8s-minikube/kicbase:v0.0.13@sha256:4d43acbd0050148d4bc399931f1b15253b5e73815b63a67b8ab4a5c9e523403f: exit status 125
stdout:
6e9646e556897cc322bb866c140898a6b56ac0c2e9d21e29221affd5692e3869
Exiting due to GUEST_PROVISION: Failed to start host: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --network minikube --ip 192.168.49.2 --volume minikube:/var --security-opt apparmor=unconfined --memory=3400mb --memory-swap=3400mb --cpus=2 -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 gcr.io/k8s-minikube/kicbase:v0.0.13@sha256:4d43acbd0050148d4bc399931f1b15253b5e73815b63a67b8ab4a5c9e523403f: exit status 125
stdout:
b85e036c0cab058a54d2e6954674a00f3fd8a0ce89c93d069b50b35585687157

stderr:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: unknown capability "CAP_PERFMON": unknown.

stderr:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: unknown capability "CAP_PERFMON": unknown.

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by sharifelgamal** [comment]
What version of docker do you have installed? This seems to be a bug on docker's side: https://github.com/moby/moby/issues/41562

**Comment by andresb39** [comment]
Gracias Sharif, era la version de docker que estaba usando.
Actualice la version y pude configurarlo sin problemas.

`❯ docker info
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 9
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.8.16-200.fc32.x86_64
 Operating System: Fedora 32 (Workstation Edition)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 13.64GiB
 Name: lnx-jb
 ID: 3A64:P6N2:YGWU:WYI6:SCNV:GUSN:QXVT:M7Y2:FFR7:OAE6:IA7E:SJ5Z
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: andresb39
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
`

**Comment by priyawadhwa** [comment]
Hello @andresb39 -- Thanks for opening an issue. Has it been resolved? 

Hola @ andresb39 -- Gracias por abrir un problema. ¿Se ha resuelto?

**Comment by priyawadhwa** [comment]
Hi @andresb39 this issue has been silent for a few months, so I'm going to go ahead and close it. If you're still seeing this issue with the latest version of minikube, please reopen at any time!


Hola @ andresb39, este problema ha estado en silencio durante unos meses, así que continuaré y lo cerraré. Si sigues viendo este problema con la última versión de minikube, vuelve a abrir en cualquier momento.
