### ISSUE TITLE
Add support for windows server data center for HyperV driver

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9575]

**Comment by blueelvis** [comment]
@medyagh - This seems to be working fine on an Azure VM I have with nested virtualization.

All I had to do was just follow [this](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/nested-virtualization) guide (& used the DHCP option) till the end, then the usual minikube installation using chocolatey.
What should be done next? Document this?
```
PS C:\Users\blueelvis> minikube start
* minikube v1.14.2 on Microsoft Windows Server 2016 Datacenter 10.0.14393 Build 14393
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing hyperv VM for "minikube" ...
* Preparing Kubernetes v1.19.2 on Docker 19.03.12 ...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" by default
```

**Comment by sharifelgamal** [comment]
This works as long as you create and specify a virtual switch.
