### ISSUE TITLE
minikube error in laptop bare machine(hyper-v) in win 10

### ISSUE THREAD

**Issue by VishalYesurkar02** [kubernetes/minikube#9582]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>
PS C:\WINDOWS\system32> minikube start
* minikube v1.13.1 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* minikube 1.14.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.14.2
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running hyperv "minikube" VM ...
! StartHost failed, but will try again: provision: IP not found
* Updating the running hyperv "minikube" VM ...
* Failed to start hyperv VM. Running "minikube delete" may fix it: provision: IP not found

X Exiting due to GUEST_PROVISION: Failed to start host: provision: IP not found
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose
![Capture](https://user-images.githubusercontent.com/47682931/97604616-b2c76b80-1a33-11eb-83d7-c06dbff3d2f4.JPG)
![Capture](https://user-images.githubusercontent.com/47682931/97604650-bce96a00-1a33-11eb-9fb8-2484adcd3c31.JPG)

**Comment by VishalYesurkar02** [comment]
PS C:\WINDOWS\system32> minikube logs
E1029 22:13:59.809439    9372 logs.go:203] Failed to list containers for "kube-apiserver": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found
E1029 22:14:05.201445    9372 logs.go:203] Failed to list containers for "etcd": docker: NewSession: new client: new client: Error creating new ssh host from driver: Error getting ssh host name for driver: IP not found

**Comment by priyawadhwa** [comment]
Hey @VishalYesurkar02 were you able tot ry the hyperv virtual switch or the docker driver?

**Comment by sharifelgamal** [comment]
I'm going to go ahead and close this issue since we haven't had an update for awhile. If you try a minikube delete/start or try a different driver and have an update, please reopen this issue.
