### ISSUE TITLE
Add details about what can be done to fix an unhealthy driver

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#9590]
**Steps to reproduce the issue:** 

1. On a Windows machine, open a PowerShell prompt without administrator privileges and turn off Docker.
2. `minikube start`

**Full output of failed command:** 

```
PS D:\dev\minikube> minikube-windows-amd64.exe start
* minikube v1.14.2 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Unable to pick a default driver. Here is what was considered, in preference order:
  - vmware: Not installed: exec: "docker-machine-driver-vmware": executable file not found in %PATH%
  - docker: Not healthy: "docker version --format {{.Server.Os}}-{{.Server.Version}}" exit status 1: Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
  - hyperv: Not healthy: Hyper-v commands have to be run as an Administrator
  - podman: Not installed: exec: "podman": executable file not found in %PATH%
  - virtualbox: Not installed: unable to find VBoxManage in $PATH

X Exiting due to DRV_NOT_DETECTED: No possible driver was detected. Try specifying --driver, or see https://minikube.sigs.k8s.io/docs/start/
```

As we can see from the output, it is difficult to understand what can be done to fix an unhealthy driver. The drivers are there and available but in this case, Docker & Hyper-V are unhealthy because Docker is turned off and for Hyper-V, permissions are required.

Also, since the drivers are detected but unhealthy, `DRV_NOT_DETECTED` should be something like `DRV_FOUND_BUT_UNHEALTHY`.

I suggest that we tabularize the information along with the possible fix for each of the drivers unhealthy or not like we do for the `minikube profile list`

**Comment by afbjorklund** [comment]
We also noticed earlier that the "in preference order" is a lie.

**Comment by priyawadhwa** [comment]
I think fixing the "in preference order" and changing the name of the error is the minimum we should do here.

We could also change output to be cleaner, so that if something is not installed we just say "Not installed"

**Comment by spowelljr** [comment]
The preference order has been fixed, and @andriyDev improved the error message when a driver is unhealthy, closing issue.
