### ISSUE TITLE
Update SuggestFix for Docker Driver on Windows

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#9591]
The following line needs to be changed - https://github.com/kubernetes/minikube/blob/5ce9d99d68a57f833b7af035c384479122479968/pkg/minikube/registry/drvs/docker/docker.go#L168

The error which pops up with latest version of Docker Desktop on Windows is -
```
Error response from daemon: open \\.\pipe\docker_engine_linux: The system cannot find the file specified.
```

**Comment by tstromberg** [comment]
Sent a 1-liner PR to fix this.
