### ISSUE TITLE
How to install minikube on MacOS?

### ISSUE THREAD

**Issue by kaojunsong** [kubernetes/minikube#9598]
**Steps to reproduce the issue:** 

1.  The installation section is empty: https://minikube.sigs.k8s.io/docs/start/
2. How can I install minikube on MacOS?

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by RA489** [comment]
@kaojunsong Please click on the MacOS tab in the Installation section here  https://minikube.sigs.k8s.io/docs/start/#

**Comment by kaojunsong** [comment]
![image](https://user-images.githubusercontent.com/9572722/97956168-efec7e80-1de2-11eb-89f1-72d6dea7e414.png)
@RA489 Thank you for your help, I can see the Installation section on my cell phone, but empty on my chrome browser on PC, maybe the problem of browser.

**Comment by Konata9** [comment]
Same problem with @kaojunsong . Installation content is empty. 

Here is the source about this page. @kaojunsong We can follow the step in this file.
https://github.com/kubernetes/minikube/blob/master/site/content/en/docs/start/_index.md

**Comment by kaojunsong** [comment]
@Konata9 Thanks
