### ISSUE TITLE
Mac Xhyve Driver Ignores Memory and CPU Switches

### ISSUE THREAD

**Issue by dbanttari** [kubernetes/minikube#960]
The Mac xhyve driver appears to ignore --memory and --cpus switches:
```
->minikube start --vm-driver=xhyve --container-runtime=docker --show-libmachine-logs --v=10 --alsologtostderr --cpus 4 --memory 6120
[snip]
(minikube) DBG | [xhyve -A -U D6603CF9-B0C5-4B12-81A1-3AC2827DA143 -c 2 -m 2048M -l com1,autopty ....]
```
It doesn't look like the command-line args are getting passed through to xhyve correctly; I would expect to see `-c 4 -m 6120M`

**Minikube version**:
minikube version: v0.14.0

**Environment**:
- **OS:** MacOS 10.10.5 Yosemite
- **VM Driver:** xhyve
- **Docker version:** Docker version 1.12.5, build 7392c3b

**Comment by r2d4** [comment]
This is more of an issue with user experience.  If the minikube VM is already started, memory and cpus flags won't have any effect as hyperkit cant change some options without a recreate.  Right now it silently ignores the flags if minikube is already started.  

We've debated whether to have some help text and continue to ignore the flags or to split `minikube start` into `minikube create` and `minikube start`

**Comment by dbanttari** [comment]
Confirmed.  Using `delete` before trying to `start` again shows the correct settings.  Thanks for the clarification @r2d4 

FWIW a message like this would be quite clear:
```
WARNING: Memory and cpu options are ignored when resuming an already-created minikube instance. 
```

**Comment by grantnicholas** [comment]
+1 @dbanttari , having a warning would definitely save people time when trying to allocate more resources to the VM. Ignoring flags is not a great way to go.

**Comment by fatal-exception** [comment]
I got bitten by this today - was warning text idea shelved?

**Comment by gintautassulskus** [comment]
I believe the same applies to `vbox`. A warning message would be very much welcome.
