### ISSUE TITLE
Stuck on "Pulling base image ..."

### ISSUE THREAD

**Issue by kaojunsong** [kubernetes/minikube#9600]
**Steps to reproduce the issue:** 

~ minikube start

😄  Darwin 10.15.4 上的 minikube v1.14.2
✨  根据现有的配置文件使用 docker 驱动程序
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...

Stuck on this, and no more logs

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by Zarca** [comment]
The same situation

**Comment by chao1301** [comment]
The same situation
