### ISSUE TITLE
Minikube Kubectl - completion does not work on zsh using alias

### ISSUE THREAD

**Issue by StefanLobbenmeier** [kubernetes/minikube#9603]
In the documentation it says
>You can also alias kubectl="minikube kubectl --" for easier usage.

when I use the current kubectl application from yum auto completion works:

```
➜  ~ kubectl
annotate        certificate     cordon          drain           get             port-forward    run             uncordon
api-versions    cluster-info    cp              edit            label           proxy           scale           version
apply           completion      create          exec            logs            replace         set
attach          config          delete          explain         options         rolling-update  taint
autoscale       convert         describe        expose          patch           rollout         top
```

When I use the "minikube kubectl -- " command it no longer works
```
➜  ~ minikube kubectl -- __minikube_handle_flag:31: bad math expression: operand expected at `'
➜  ~ minikube kubectl --
Desktop/              Downloads/            minikube-linux-amd64  Pictures/             Templates/
Documents/            install.sh*           Music/                Public/               Videos/

```

And I also get the same result when I now switch to an alias - I get an error and zsh instead completes with the files and folders from my current directory
```
➜  ~ alias kubectl="minikube kubectl --"
➜  ~ kubectl __minikube_handle_flag:31: bad math expression: operand expected at `'
     kubectl
Desktop/              Downloads/            minikube-linux-amd64  Pictures/             Templates/
Documents/            install.sh*           Music/                Public/               Videos/
```

I guess this is because zsh sees that "kubectl" is only an alias to "minikube ..." so it selects the minikube completion to handle this. From my understanding minikube could fix this in their completion, or there needs to be another way to do the alias so that zsh knows to call the kubectl autocompletion instead.

**Comment by StefanLobbenmeier** [comment]
Just wanted to add since I could not find it in the source code, this is the __minikube_handle_flag from my machine:

```sh
__minikube_handle_flag()
{
    __minikube_debug "${FUNCNAME[0]}: c is $c words[c] is ${words[c]}"

    # if a command required a flag, and we found it, unset must_have_one_flag()
    local flagname=${words[c]}
    local flagvalue
    # if the word contained an =
    if [[ ${words[c]} == *"="* ]]; then
        flagvalue=${flagname#*=} # take in as flagvalue after the =
        flagname=${flagname%=*} # strip everything after the =
        flagname="${flagname}=" # but put the = back
    fi
    __minikube_debug "${FUNCNAME[0]}: looking for ${flagname}"
    if __minikube_contains_word "${flagname}" "${must_have_one_flag[@]}"; then
        must_have_one_flag=()
    fi

    # if you set a flag which only applies to this command, don't show subcommands
    if __minikube_contains_word "${flagname}" "${local_nonpersistent_flags[@]}"; then
      commands=()
    fi

    # keep flag value with flagname as flaghash
    # flaghash variable is an associative array which is only supported in bash > 3.
    if [[ -z "${BASH_VERSION}" || "${BASH_VERSINFO[0]}" -gt 3 ]]; then
        if [ -n "${flagvalue}" ] ; then
            flaghash[${flagname}]=${flagvalue}
        elif [ -n "${words[ $((c+1)) ]}" ] ; then
            flaghash[${flagname}]=${words[ $((c+1)) ]}
        else
            flaghash[${flagname}]="true" # pad "true" for bool flag
        fi
    fi

    # skip the argument to a two word flag
    if [[ ${words[c]} != *"="* ]] && __minikube_contains_word "${words[c]}" "${two_word_flags[@]}"; then
                          __minikube_debug "${FUNCNAME[0]}: found a flag ${words[c]}, skip the next argument"
        c=$((c+1))
        # if we are looking for a flags value, don't show commands
        if [[ $c -eq $cword ]]; then
            commands=()
        fi
    fi

    c=$((c+1))

}
```

**Comment by priyawadhwa** [comment]
Hey @StefanLobbenmeier thanks for opening this issue -- is the code you provided above the output of `minikube completion`?

**Comment by StefanLobbenmeier** [comment]
Yes, it’s part of what I got when I ran 
`minikube completion zsh `

One thing I find quite strange is that the zsh completion contains `BASH_VERSION`

**Comment by afbjorklund** [comment]
@StefanLobbenmeier:
When you install kubectl as root, it will install **two** files for you:

```
/usr/bin/kubectl
/etc/bash_completion.d/kubectl
```

When using the alias for minikube, you will have to call it explicily:

```bash
alias kubectl='minikube kubectl --'
source <(kubectl completion bash)
```

https://kubernetes.io/docs/tasks/tools/install-kubectl/#enabling-shell-autocompletion

The approach is similar for other shells (than bash), but the syntax may vary a bit....

**Comment by StefanLobbenmeier** [comment]
So what you are saying is that bash uses the kubectl completion when kubectl is only an alias?

For me it looks like zsh is using the minikube completion because it sees that kubectl is only an alias for minikube.

**Comment by StefanLobbenmeier** [comment]
I just tested with the minikube kubectl on bash and sourcing did not work for bash either but likely because my cluster is not started:

```
[slobbenmeier@centos02clone ~]$ bash
[slobbenmeier@centos02clone ~]$ alias kubectl='minikube kubectl --'
[slobbenmeier@centos02clone ~]$ source <(kubectl completion bash)
! This is unusual - you may want to investigate using "minikube logs"
bash: /dev/fd/63: line 1: syntax error near unexpected token `('
bash: /dev/fd/63: line 1: `* This control plane is not running! (state=Stopped)'
```

**Comment by StefanLobbenmeier** [comment]
I checked the link you provided and found a dedicated section to aliases - I will check if that can help me with zsh as well
 (Mentioned on the website:)
```
echo 'alias k=kubectl' >>~/.bashrc
echo 'complete -F __start_kubectl k' >>~/.bashrc
```

**Comment by StefanLobbenmeier** [comment]
Ok I got it working on zsh now after finding this: https://unix.stackexchange.com/a/250489

```
➜  ~ setopt complete_aliases
➜  ~ alias kubectl='minikube kubectl --'
➜  ~ kubectl
annotate        certificate     cordon          drain           get             port-forward    run             uncordon
api-versions    cluster-info    cp              edit            label           proxy           scale           version
apply           completion      create          exec            logs            replace         set
attach          config          delete          explain         options         rolling-update  taint
autoscale       convert         describe        expose          patch           rollout         top
```

If we can document this anywhere the issue can be closed

**Comment by afbjorklund** [comment]
Possibly here somewhere: https://minikube.sigs.k8s.io/docs/commands/kubectl/

**Comment by StefanLobbenmeier** [comment]
I would prefer https://minikube.sigs.k8s.io/docs/handbook/kubectl/ as this is where I also first read about creating the alias.

**Comment by yangliuyu** [comment]
> Ok I got it working on zsh now after finding this: https://unix.stackexchange.com/a/250489
> 
> ```
> ➜  ~ setopt complete_aliases
> ➜  ~ alias kubectl='minikube kubectl --'
> ➜  ~ kubectl
> annotate        certificate     cordon          drain           get             port-forward    run             uncordon
> api-versions    cluster-info    cp              edit            label           proxy           scale           version
> apply           completion      create          exec            logs            replace         set
> attach          config          delete          explain         options         rolling-update  taint
> autoscale       convert         describe        expose          patch           rollout         top
> ```
> 
> If we can document this anywhere the issue can be closed

alias kubectl='minikube kubectl --' works with completion, but other alias not.
For example, `alias k=kubectl` and `alias kl='kubectl logs'` defined in `~/.oh-my-zsh/plugins/kubectl/kubectl.plugin.zsh`
When I type `k get space tab` then
(base) ➜  ~ k get
Applications/  Desktop/       Documents/     Downloads/     Library/       Movies/        Music/         Pictures/      Public/        dev/

**Comment by StefanLobbenmeier** [comment]
@yangliuyu Can you double check that you executed `setopt complete_aliases`?

i have the suspicion that you did not execute that, and that you have kubectl completion installed separately and that’s why it is working with that specific alias.  

I am not sure how to debug this any further than that though.

**Comment by Syakhisk** [comment]
For anyone coming from google, I was unable to use the alias, so I use the symlink method.
Add this to your `.zshrc`

```zsh
[[ ! -f "/usr/local/bin/kubectl" ]] && sudo ln -s $(which minikube) /usr/local/bin/kubectl

source <(minikube completion zsh)
source <(kubectl completion zsh)

alias k="kubectl"
compdef _kubectl k
```
