### ISSUE TITLE
Unable to start minikube using Docker driver and CRI-O runtime on Fedora32 (cgroups v1)

### ISSUE THREAD

**Issue by vrubiolo** [kubernetes/minikube#9625]
**Steps to reproduce the issue:** 

As per our [discussion with @tstromberg on Slack](https://kubernetes.slack.com/archives/C1F5CT6Q1/p1604680126134800?thread_ts=1604679550.133500&cid=C1F5CT6Q1), I am opening this issue.

1. `minikube start --alsologtostderr --driver=docker --container-runtime=crio -v=1`
2. Minikube does not start

This works with `minikube start --driver=virtualbox --container-runtime=crio`

**Full output of failed command:** 
[minikube-crio-log.txt](https://github.com/kubernetes/minikube/files/5503806/minikube-crio-log.txt)

Output of `minikube ssh "sudo journalctl -u crio"`
```
-- Logs begin at Fri 2020-11-06 22:32:58 UTC, end at Fri 2020-11-06 22:39:21 UTC. --
Nov 06 22:33:00 minikube systemd[1]: Starting Container Runtime Interface for OCI (CRI-O)...
Nov 06 22:33:00 minikube systemd[1]: Started Container Runtime Interface for OCI (CRI-O).
```
Output of `minikube ssh "sudo journalctl -u kubelet --no-pager"` (12MiB large)
[minikube-crio-kubelet-log.txt.gz](https://github.com/kubernetes/minikube/files/5503818/minikube-crio-kubelet-log.txt.gz)

This is Fedora 32, configured w/ `cgroups v1`:
```
$ cat /proc/cmdline 
BOOT_IMAGE=(hd0,gpt2)/vmlinuz-5.8.16-200.fc32.x86_64 root=/dev/mapper/fedora_localhost--live-root ro resume=/dev/mapper/fedora_localhost--live-swap rd.lvm.lv=fedora_localhost-live/root rd.lvm.lv=fedora_localhost-live/swap rhgb quiet systemd.unified_cgroup_hierarchy=0
```
```
$ minikube version
minikube version: v1.14.2
commit: 2c82918e2347188e21c4e44c8056fc80408bce10
```

**Comment by afbjorklund** [comment]
Looks like the same crio bug as before:

Nov 06 22:33:15 minikube kubelet[796]: F1106 22:33:15.404404     796 kubelet.go:1296] Failed to start ContainerManager failed to initialize top level QOS containers: root container [kubepods] doesn't exist

Reported upstream as https://github.com/cri-o/cri-o/issues/4035

**Comment by afbjorklund** [comment]
There was a cri-o workaround previously: 61583d62492e2be0387563f460c56b1afba264c1

It was reverted recently, for some reason: 8b1def0608ef76df4105b6cefb3bcff10161e149

I think the ISO had the previous version, the KIC was updated ahead-of-time:

```
🔥  Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🎁  Preparing Kubernetes v1.19.2 on CRI-O 1.17.3 ...
```

This is tracked as  #8861(follow up from #8854)

I don't think it is resolved yet ? Can try 1.18.4...

@sharifelgamal @medyagh

**Comment by afbjorklund** [comment]
A similar workaround for the docker driver, would be to change the yum configuration and downgrade to cri-o 1.17.3

It's also possible that a `sudo systemctl restart crio` would also fix it, but maybe the self-destruct feature kicked in first

**Comment by afbjorklund** [comment]
@vrubiolo

There is an updated image in PR #9629, if you like to build it and try it ?

Works OK on Ubuntu, at least. Haven't tried it myself on Fedora, though.

**Comment by vrubiolo** [comment]
@afbjorklund : sure, thanks for the suggestion, let me try that over the weekend and report back.

**Comment by afbjorklund** [comment]
Not sure why there would be any difference, since we're using the same ubuntu 20.04 distribution _inside_ the docker container

but there would be different kernels involved, and I don't what cause the cri-o problem (occasionally?) in the first place anyway

**Comment by afbjorklund** [comment]
But I did change `runc`, since I suspect that it is involved in this - and it was recommended to do so by cri-o upstream...

https://bugzilla.redhat.com/show_bug.cgi?id=1508040#c15

Upgraded from 1.0.0-rc10 to 1.0.0-rc92

> Note: We include cri-o-runc because Ubuntu and Debian include their own packaged version of runc. While this version should work with CRI-O, keeping the packaged versions of CRI-O and runc in sync ensures they work together.

**Comment by vrubiolo** [comment]
Hi @afbjorklund and thanks for being so reactive!

I am pleased to report that https://github.com/kubernetes/minikube/pull/9629 appears to fix the issue for me. I can now start minikube w/ CRI-O and the Docker driver:
```
(kicbase-crio)$ git log -1
commit c2d435945638631faa3f4d200f2895d4852125ea (HEAD -> kicbase-crio, origin/kicbase-crio)
Author: Anders F Björklund <anders.f.bjorklund@gmail.com>
Date:   Sat Nov 7 12:52:43 2020 +0100

    Upgrade cri-o in kicbase to version 1.18.4
    
    Use the latest 1.18, since 1.18.4 is broken again <sigh>
    
    Use the recommended cri-o-runc package instead of runc

(kicbase-crio)$ make
[build went fine]
(kicbase-crio)$ make kic-base-image
[new Docker image generated]

(kicbase-crio)$ ./out/minikube start --driver=docker --base-image=local/kicbase:latest --container-runtime=cri-o --preload=false
😄  minikube v1.14.2 on Fedora 32
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=3900MB) ...
🎁  Preparing Kubernetes v1.19.2 on CRI-O 1.18.4 ...
    > kubeadm.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubelet.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl.sha256: 65 B / 65 B [--------------------------] 100.00% ? p/s 0s
    > kubectl: 41.01 MiB / 41.01 MiB [----------------] 100.00% 9.40 MiB p/s 4s
    > kubeadm: 37.30 MiB / 37.30 MiB [----------------] 100.00% 8.54 MiB p/s 4s
    > kubelet: 104.88 MiB / 104.88 MiB [-------------] 100.00% 12.26 MiB p/s 9s
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

(kicbase-crio)$ kubectl get pods
No resources found in default namespace.

(kicbase-crio)$ kubectl get pods -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-f9fd979d6-h8xtz            1/1     Running   0          57s
kube-system   etcd-minikube                      0/1     Running   0          57s
kube-system   kindnet-5tc64                      1/1     Running   0          57s
kube-system   kube-apiserver-minikube            1/1     Running   0          57s
kube-system   kube-controller-manager-minikube   0/1     Running   0          57s
kube-system   kube-proxy-gt9hb                   1/1     Running   0          57s
kube-system   kube-scheduler-minikube            0/1     Running   0          57s
kube-system   storage-provisioner                1/1     Running   0          65s
```
`./out/minikube start --driver=docker --base-image=local/kicbase:latest --container-runtime=cri-o --preload=false --alsologtostderr -v=1` logs
[minikube-crio-fix.txt](https://github.com/kubernetes/minikube/files/5505441/minikube-crio-fix.txt)

**Comment by vrubiolo** [comment]
Thanks for merging #9629 in!

What is the process for closing an issue like the present one? Should I wait until the next minikube release or do we immediately close it?

**Comment by medyagh** [comment]
> Thanks for merging #9629 in!
> 
> What is the process for closing an issue like the present one? Should I wait until the next minikube release or do we immediately close it?

thanks we can close this issue we are planning to release tomorrow, hope that be helpful

**Comment by vrubiolo** [comment]
Cool, no worries, will be happy to try the new release when it's out!

**Comment by vrubiolo** [comment]
I confirm the `1.15.0` release allows to start/use CRI-O w/ the Docker driver w/o any issues on Fedora32 now (via `minikube start  --container-runtime=crio`).

Thanks for your help fixing this !
