### ISSUE TITLE
MEP: CRI: Containerd by default, Buildkitd on demand

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#9639]
Background:

Kubernetes is moving to deprecate the dockershim in k8s ~~1.10~~ 1.20 and start using CRI by default (instead of Docker)

* [KEP-1985: Removing dockershim from kubelet](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/1985-remove-dockershim/README.md)

* [KEP 2040: Kubelet CRI support](https://github.com/kubernetes/enhancements/blob/master/keps/sig-node/2040-kubelet-cri/README.md) (v1alpha → v1beta)

Docker is not supporting Boot2Docker or Machine anymore, the upstream is deprecated (for years) and **unmaintained**.

Thus, we don't _need_ to start Docker by default...

History:

https://kubernetes.io/blog/2016/07/rktnetes-brings-rkt-container-engine-to-kubernetes/
https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/

> 1.5: "Kubelet does not yet use CRI by default, but we are actively working on making this happen. The first step is to re-integrate Docker with kubelet using CRI. In the 1.5 release, we extended kubelet to support CRI, and also added a built-in CRI shim for Docker. This allows kubelet to start the gRPC server on Docker’s behalf."

https://kubernetes.io/blog/2017/11/containerd-container-runtime-options-kubernetes/
https://kubernetes.io/blog/2018/05/24/kubernetes-containerd-integration-goes-ga/

> 1.10: "The containerd 1.1 integration uses the CRI plugin built into containerd; and the Docker 18.03 CE integration uses the dockershim."

Suggestion:

Instead, we should start a CRI (container runtime for Kubernetes) by default, and start the bigger daemon only when needed.

The default will be "containerd", with buildkitd socket-activated. With an alternative of "cri-o", with podman socket-activated.

This will result in a smaller footprint for users that "only" want to run Kubernetes, and not for instance build container images.

All previous features are still available, since the unix socket will be there and start the daemon when somebody accesses it.

Implications:

1) Install CRI by default, including cri-tools (crictl)

2) Don't start _anything_ automatically at boot time

3) Also deprecate the old Docker tcp port (2376)

4) Complete the fork of the libmachine and drivers

Related issues:

* #9229 Deprecate the old tcp port for docker-env
* #9230 Deprecate the old varlink for podman-env
* #9232 Use socket activation for the docker service
* #8596 Use socket activation for the podman service

MEP PR to follow

Note that for instance kind, microk8s and k3s _already_ run with containerd by default. It is also a graduated CNCF project:

https://containerd.io/

We will continue to offer alternative runtimes (following the CRI/CNI specifications), even at considerable engineering effort.

----

_Note: Local podman is "daemon-less", but remote podman runs as a service through systemd (so it works like dockerd)._
_Since we want to expose the container runtime to users, we want to run the remote versions. We also run as root, for now._

Users will need to upgrade to Docker 18.09 (or later) or Podman 2.0 (or later), if they want to access the service remotely.
Like before, there will be a client installed that can be access over SSH. Only downside is having to transfer the build context.

**Comment by afbjorklund** [comment]
Unfortunately dockerd (and docker-containerd) does **not** share image storage with stand-alone containerd:

https://github.com/moby/moby/issues/38043
~~https://github.com/containerd/containerd/issues/2987~~

This means that any images built will need to be transported from `/var/lib/docker` to `/var/lib/containerd`.

----

Same thing already happens today when using BuildKit to build, but that is a different story (`--output`).

There might be some performance implications because of this, but at least it can all be transferred locally...
Other distributions have other solutions to this issue, including tar + copying the images over the network.

For podman and cri-o the story is different since they are already both using the same `/var/lib/containers`.

**Comment by afbjorklund** [comment]
I changed the title, since docker storage is not compatible with containerd storage

**Comment by afbjorklund** [comment]
There will be an external cri-dockerd, so Docker will be supported for years yet

**Comment by afbjorklund** [comment]
Building using `buildctl` is awkward to say the least, and running containers via `ctr` is similarly user-hostile.
So as long as we want to export the full features of the container runtime to the user, Docker/Moby is the better choice.

We can still offer containerd/buildkitd as a fully supported CRI option of course, but it is unlikely to be the **default**.
Other projects that do this (like kind or microk8s), don't offer the "machine" or "build" functionally that minikube does.

Getting away from docker-machine is still needed, but it is a slightly different topic than changing the default CRI.

Will probably split it out into a separate GitHub issue, for the "naked VM" (item 2) and the "fork machine" (item 4).

**Comment by afbjorklund** [comment]
https://github.com/kubernetes/minikube/blob/master/enhancements/proposed/20201230-containerd-default/container-default.md

/lifecycle frozen

**Comment by AkihiroSuda** [comment]
@afbjorklund Is there an ETA of this?

**Comment by afbjorklund** [comment]
> @afbjorklund Is there an ETA of this?

The consensus was that we should continue to have docker as the default for some more releases.

We need to have stable fallbacks for workflows original based on `docker-env`, such as Skaffold.
But it should be available as a minikube alternative already today (`--container-runtime=containerd`)

And we keep on adding CI resources and tests, to make sure that containerd / buildkitd is tested.

**Comment by afbjorklund** [comment]
We will add Mirantis cri-dockerd, to keep supporting the Docker runtime also with Kubernetes 1.23+
