### ISSUE TITLE
Minikube not starting on windows 10

### ISSUE THREAD

**Issue by naileshjadhav** [kubernetes/minikube#9643]
**Steps to reproduce the issue:** 

1. Install minicube using choco on windows 10
2. execute minikube start
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

PS C:\WINDOWS\system32> minikube start
* minikube v1.14.2 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing docker container for "minikube" ...
! StartHost failed, but will try again: provision: Temporary Error: transferring file: &{BaseAsset:{SourcePath:C:\Users\nj53968.IND\.minikube\certs\ca.pem TargetDir:C:\Users\nj53968.IND\.minikube TargetName:ca.pem Permissions:0777 Source:} reader:0xc00008ef30}: error removing file C:\Users\nj53968.IND\.minikube/ca.pem: remove C:\Users\nj53968.IND\.minikube/ca.pem: Access is denied.
* Updating the running docker "minikube" container ...
* Failed to start docker container. Running "minikube delete" may fix it: provision: Temporary Error: transferring file: &{BaseAsset:{SourcePath:C:\Users\nj53968.IND\.minikube\certs\ca.pem TargetDir:C:\Users\nj53968.IND\.minikube TargetName:ca.pem Permissions:0777 Source:} reader:0xc000981c20}: error removing file C:\Users\nj53968.IND\.minikube/ca.pem: remove C:\Users\nj53968.IND\.minikube/ca.pem: Access is denied.

X Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: transferring file: &{BaseAsset:{SourcePath:C:\Users\nj53968.IND\.minikube\certs\ca.pem TargetDir:C:\Users\nj53968.IND\.minikube TargetName:ca.pem Permissions:0777 Source:} reader:0xc000981c20}: error removing file C:\Users\nj53968.IND\.minikube/ca.pem: remove C:\Users\nj53968.IND\.minikube/ca.pem: Access is denied.
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment]
This looks like a permissions issue, is there any reason your user might not be able to access `C:\Users\nj53968.IND.minikube/ca.pem`?

**Comment by naileshjadhav** [comment]
I have admin right of the system but though it is giving error.
Whenever system/laptop restarted this issue occurs and I need to delete minikube then start again.
This is annoying.

**Comment by medyagh** [comment]
@naileshjadhav is it happening for latest verison of minikbue too ?

so on every Docker Desktop Restart would a `minikube start` fix the problem without deleting it ?

**Comment by sharifelgamal** [comment]
This should be fixed in the newest version of minikube, please reopen if the issue persists.
