### ISSUE TITLE
Error: No such network: 56bcceb8c923

### ISSUE THREAD

**Issue by nianqiang** [kubernetes/minikube#9644]
**重现问题所需的命令**：
minikube start \
--driver=docker \
--registry-mirror=https://n0dwemtq.mirror.aliyuncs.com \
--memory=2048mb

**失败的命令的完整输出**：<details>
[leyou@node1 bin]$ minikube start \
> --driver=docker \
> --registry-mirror=https://n0dwemtq.mirror.aliyuncs.com \
> --memory=2048mb
* minikube v1.12.1 on Centos 7.6.1810
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* docker "minikube" container is missing, will recreate.
* Creating docker container (CPUs=2, Memory=2048MB) ...
* Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
E1109 20:48:43.302326   20660 start.go:97] Unable to get host IP: inspect IP bridge network "56bcceb8c923\n051f84d44254".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 56bcceb8c923
051f84d44254: exit status 1
stdout:

stderr:
Error: No such network: 56bcceb8c923
051f84d44254
* 
X failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "56bcceb8c923\n051f84d44254".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 56bcceb8c923
051f84d44254: exit status 1
stdout:

stderr:
Error: No such network: 56bcceb8c923
051f84d44254

* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
[leyou@node1 bin]$ 

</details>

**`minikube logs`命令的输出**： <details>

[leyou@node1 bin]$ minikube logs
* ==> Docker <==
* -- Logs begin at Mon 2020-11-09 12:48:39 UTC, end at Mon 2020-11-09 12:53:23 UTC. --
* Nov 09 12:48:39 minikube systemd[1]: Starting Docker Application Container Engine...
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.483293947Z" level=info msg="Starting up"
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.484399325Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.484412454Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.484427600Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.484436644Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.484512391Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00005ba30, CONNECTING" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.486816277Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00005ba30, READY" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.487560833Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.487572944Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.487583732Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.487591041Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.487619837Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00066b370, CONNECTING" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.487851223Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00066b370, READY" module=grpc
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.519265068Z" level=info msg="Loading containers: start."
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.626903455Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.671149409Z" level=info msg="Loading containers: done."
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.691598593Z" level=info msg="Docker daemon" commit=6a30dfca03 graphdriver(s)=overlay2 version=19.03.2
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.691745237Z" level=info msg="Daemon has completed initialization"
* Nov 09 12:48:39 minikube dockerd[120]: time="2020-11-09T12:48:39.706436760Z" level=info msg="API listen on /run/docker.sock"
* Nov 09 12:48:39 minikube systemd[1]: Started Docker Application Container Engine.
* Nov 09 12:48:40 minikube systemd[1]: docker.service: Current command vanished from the unit file, execution of the command list won't be resumed.
* Nov 09 12:48:40 minikube systemd[1]: Stopping Docker Application Container Engine...
* Nov 09 12:48:40 minikube dockerd[120]: time="2020-11-09T12:48:40.919994087Z" level=info msg="Processing signal 'terminated'"
* Nov 09 12:48:40 minikube dockerd[120]: time="2020-11-09T12:48:40.920872917Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
* Nov 09 12:48:40 minikube dockerd[120]: time="2020-11-09T12:48:40.921013858Z" level=info msg="Daemon shutdown complete"
* Nov 09 12:48:40 minikube systemd[1]: docker.service: Succeeded.
* Nov 09 12:48:40 minikube systemd[1]: Stopped Docker Application Container Engine.
* Nov 09 12:48:40 minikube systemd[1]: Starting Docker Application Container Engine...
* Nov 09 12:48:40 minikube dockerd[341]: time="2020-11-09T12:48:40.998795287Z" level=info msg="Starting up"
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.000420566Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.000450250Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.000466026Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.000476631Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.000553355Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000121eb0, CONNECTING" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.000855394Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000121eb0, READY" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.001433556Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.001460800Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.001471939Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.001478360Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.001502039Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001c8230, CONNECTING" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.001697932Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001c8230, READY" module=grpc
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.009290540Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.011185059Z" level=info msg="Loading containers: start."
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.105948020Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.140328319Z" level=info msg="Loading containers: done."
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.152391973Z" level=info msg="Docker daemon" commit=6a30dfca03 graphdriver(s)=overlay2 version=19.03.2
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.152459835Z" level=info msg="Daemon has completed initialization"
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.164183129Z" level=info msg="API listen on /var/run/docker.sock"
* Nov 09 12:48:41 minikube dockerd[341]: time="2020-11-09T12:48:41.164239242Z" level=info msg="API listen on [::]:2376"
* Nov 09 12:48:41 minikube systemd[1]: Started Docker Application Container Engine.
* 
* ==> container status <==
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
* time="2020-11-09T12:53:26Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
* 
* ==> describe nodes <==
E1109 20:53:26.077890   27564 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
sudo: /var/lib/minikube/binaries/v1.18.3/kubectl: command not found
 output: "\n** stderr ** \nsudo: /var/lib/minikube/binaries/v1.18.3/kubectl: command not found\n\n** /stderr **"
* 
* ==> dmesg <==
* [Nov 9 12:44] ACPI: RSDP 00000000000f6a00 00024 (v02 PTLTD )
* [  +0.000000] ACPI: XSDT 000000007feeea37 0005C (v01 INTEL  440BX    06040000 VMW  01324272)
* [  +0.000000] ACPI: FACP 000000007fefee73 000F4 (v04 INTEL  440BX    06040000 PTL  000F4240)
* [  +0.000000] ACPI: DSDT 000000007feeec95 101DE (v01 PTLTD  Custom   06040000 MSFT 03000001)
* [  +0.000000] ACPI: FACS 000000007fefffc0 00040
* [  +0.000000] ACPI: BOOT 000000007feeec6d 00028 (v01 PTLTD  $SBFTBL$ 06040000  LTP 00000001)
* [  +0.000000] ACPI: APIC 000000007feeec0f 0005E (v01 PTLTD  ? APIC   06040000  LTP 00000000)
* [  +0.000000] ACPI: MCFG 000000007feeebd3 0003C (v01 PTLTD  $PCITBL$ 06040000  LTP 00000001)
* [  +0.000000] ACPI: SRAT 000000007feeeb33 000A0 (v02 VMWARE MEMPLUG  06040000 VMW  00000001)
* [  +0.000000] ACPI: HPET 000000007feeeafb 00038 (v01 VMWARE VMW HPET 06040000 VMW  00000001)
* [  +0.000000] ACPI: WAET 000000007feeead3 00028 (v01 VMWARE VMW WAET 06040000 VMW  00000001)
* [  +0.000000] Zone ranges:
* [  +0.000000]   DMA      [mem 0x00001000-0x00ffffff]
* [  +0.000000]   DMA32    [mem 0x01000000-0xffffffff]
* [  +0.000000]   Normal   empty
* [  +0.000000] Movable zone start for each node
* [  +0.000000] Early memory node ranges
* [  +0.000000]   node   0: [mem 0x00001000-0x0009efff]
* [  +0.000000]   node   0: [mem 0x00100000-0x7fedffff]
* [  +0.000000]   node   0: [mem 0x7ff00000-0x7fffffff]
* [  +0.000000] Built 1 zonelists in Node order, mobility grouping on.  Total pages: 515945
* [  +0.000000] Policy zone: DMA32
* [  +0.000000] ACPI: All ACPI Tables successfully acquired
* [  +0.023031] core: CPUID marked event: 'cpu cycles' unavailable
* [  +0.000001] core: CPUID marked event: 'instructions' unavailable
* [  +0.000000] core: CPUID marked event: 'bus cycles' unavailable
* [  +0.000001] core: CPUID marked event: 'cache references' unavailable
* [  +0.000000] core: CPUID marked event: 'cache misses' unavailable
* [  +0.000000] core: CPUID marked event: 'branch instructions' unavailable
* [  +0.000001] core: CPUID marked event: 'branch misses' unavailable
* [  +0.003074] NMI watchdog: disabled (cpu0): hardware events not enabled
* [  +0.039488] ACPI: Enabled 4 GPEs in block 00 to 0F
* [  +0.855843] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
* [  +1.554143] sd 0:0:0:0: [sda] Assuming drive cache: write through
* [  +1.490168] piix4_smbus 0000:00:07.3: SMBus Host Controller not enabled!
* [  +5.602084] TECH PREVIEW: Overlay filesystem may not be fully supported.
*               Please review provided documentation for limitations.
* [Nov 9 12:48] TECH PREVIEW: nf_tables may not be fully supported.
*               Please review provided documentation for limitations.
* 
* ==> kernel <==
*  12:53:26 up 8 min,  0 users,  load average: 0.35, 0.29, 0.21
* Linux minikube 3.10.0-957.12.2.el7.x86_64 #1 SMP Tue May 14 21:24:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* PRETTY_NAME="Ubuntu 19.10"
* 
* ==> kubelet <==
* -- Logs begin at Mon 2020-11-09 12:48:39 UTC, end at Mon 2020-11-09 12:53:26 UTC. --
* -- No entries --

! unable to fetch logs for: describe nodes
[leyou@node1 bin]$ 

</details>

**使用的操作系统版本**：
CentOS Linux release 7.6.1810 (Core)

**Comment by medyagh** [comment]
does this help ?

minikube delete
minikube start


I also noticed you are using an old version of minikube, do u mind trying the latest version?

**Comment by kadern0** [comment]
@medyagh it looks same as #8131 (per -> "56bcceb8c923\n051f84d44254" docker inspect is picking two bridge networks )

Upgrading should fix

**Comment by tstromberg** [comment]
Agreed - this should no longer happen in minikube v1.4.2+.
