### ISSUE TITLE
Error creating directory: /etc/kubernetes: mkdir /etc/kubernetes: permission denied

### ISSUE THREAD

**Issue by carlosrmfernandes** [kubernetes/minikube#9658]
![image](https://user-images.githubusercontent.com/22120478/98674184-3425d480-2337-11eb-9631-eea30d30b4bd.png)

**Comment by afbjorklund** [comment]
Seems like your setting of $KUBECONFIG environment variable is in the way.

However, our suggestion doesn't match the exact message since cd91fb84702daf538d3d809868a06e3f3bf61df0.

"Failed kubeconfig update: writing kubeconfig"

"Failed to setup kubeconfig: writing kubeconfig"
