### ISSUE TITLE
README example using extra-config and AuthorizationMode causes error message

### ISSUE THREAD

**Issue by alexguerra-luizalabs** [kubernetes/minikube#966]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): v0.14.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **Docker version** (e.g. `docker -v`): Docker version 1.12.5, build 7392c3b
- **Install tools**:
- **Others**:

**What happened**:

When starting minikube using the README example:

`minikube  start --extra-config=apiserver.AuthorizationMode=RBAC`

got the error message: 

`Unable to set AuthorizationMode to RBAC. Error: Unable to find field by name: AuthorizationMode`

**What you expected to happen**:

minikube should start without error message 

**How to reproduce it** (as minimally and precisely as possible):

`minikube  start --extra-config=apiserver.AuthorizationMode=RBAC`

**Anything else do we need to know**:

**Comment by r2d4** [comment]
This was fixed in the readme by @ankon https://github.com/kubernetes/minikube/pull/969
