### ISSUE TITLE
fix Readme Build Badge

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9661]
after removing Travis the new build icon is pointing to integration tests instead of build

https://github.com/kubernetes/minikube/actions

side effect of https://github.com/kubernetes/minikube/pull/9619

**Comment by afbjorklund** [comment]
Probably should be https://github.com/kubernetes/minikube/actions?query=workflow%3AMaster

To match ![](https://github.com/kubernetes/minikube/workflows/Master/badge.svg)

**Comment by spowelljr** [comment]
It's actually pointing to both the build and integration tests, the way the badges work is you point them to a workflow. The Master workflow contains both build and integration tests, so if one of those fails it will show up as a failure in the badge. You're currently unable to point the badge to a specific job in the workflow, but there is an open issue about doing so https://github.com/badges/shields/issues/4364. If you only want to show the status of build there will have to be another workflow added that only does the build.

**Comment by spowelljr** [comment]
Fixed in #10094
