### ISSUE TITLE
hyperv: Better handle minikube stop error on powershell & windows terminal

### ISSUE THREAD

**Issue by EArminjon** [kubernetes/minikube#9663]
1 . minikube start

![image](https://user-images.githubusercontent.com/37028599/98740776-e4cdbb80-23ab-11eb-8325-645b601ccfcf.png)

2 . minikube stop

Windows PowerShell is not in interactive mode. The read and prompt functionality is not available.

![image](https://user-images.githubusercontent.com/37028599/98740687-c49dfc80-23ab-11eb-89e9-4f6f64c48843.png)

Error here with and without profile. So, i presume on every  windows 10 pro Hyper-V with a powershell and windows terminal...

Despite of this error, ressources seems to be free but I wonder about RAM caching between 6 and 10go...

**Comment by EArminjon** [comment]
Same issue on cmd.exe
![image](https://user-images.githubusercontent.com/37028599/98741438-efd51b80-23ac-11eb-98a4-5eb7571b2e03.png)

**Comment by sharifelgamal** [comment]
This is interesting, so minikube is still successfully stopped then? Just with a spurious error?

**Comment by EArminjon** [comment]
Yes. Just an error because of an unchecked error on minikube script.

**Comment by priyawadhwa** [comment]
Ah gotcha. @EArminjon if you, or anyone else, would be interested in fixing this so that the error is handled better, feel free to take this issue on by commenting /assign.

**Comment by medyagh** [comment]
@EArminjon I am curious does this still happen in the newest version of minikube ?

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
