### ISSUE TITLE
Failed to "Minikube start with Hyper-V" - PROVIDER_HYPERV_NOT_FOUND

### ISSUE THREAD

**Issue by nagomikslai** [kubernetes/minikube#9673]
**Steps to reproduce the issue:** 
Hi,
I could not get the minikube start with Hyper-V. 
Please refer to the attached files for the error messages that being captured. 

Thank you. 

![HyperV_Enabled](https://user-images.githubusercontent.com/43594906/98816642-f07cb900-2463-11eb-8457-545f8117ae64.png)
[minikube_error_log.txt](https://github.com/kubernetes/minikube/files/5524181/minikube_error_log.txt)

**Comment by EArminjon** [comment]
As admin

```
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All
DISM /Online /Enable-Feature /All /FeatureName:Microsoft-Hyper-V 
```

**Comment by nagomikslai** [comment]
Great. It works now!
Thank you for your prompt reply.
