### ISSUE TITLE
docker registry addon changed port missing documentation

### ISSUE THREAD

**Issue by cachvico** [kubernetes/minikube#9688]
`$ minikube addons enable registry` currently outputs:
```
  Registry addon on with docker uses 32781 please use that instead of default 5000
  For more information see: https://minikube.sigs.k8s.io/docs/drivers/docker
  Verifying registry addon...
  The 'registry' addon is enabled
```
I had to work out the edit required:

`$ docker run --rm -it --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):32781".   # <-- port changed at the end`

This could do with a note at the suggested URL.

**Comment by priyawadhwa** [comment]
Hey @cachvico thanks for opening this issue -- I agree that this could be improved. If you, or anyone else, would be interested in contributing a fix to our documentation, PRs would be welcome!

**Comment by Aut0R3V** [comment]
@priyawadhwa I believe that a note can be added at the documentation here :
