### ISSUE TITLE
convert dockerNetworkInspect to a struct

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9690]
currently we use comma to get the info we need

https://github.com/medyagh/minikube/blob/a84cbed217c45c34e13bce14e1c144bcde7ee168/pkg/drivers/kic/oci/network_create.go#L139
```
	cmd := exec.Command(Docker, "network", "inspect", name, "--format", `{{(index .IPAM.Config 0).Subnet}},{{(index .IPAM.Config 0).Gateway}},{{(index .Options "com.docker.network.driver.mtu")}}`)

```

one better approach is using something like this
```
docker network inspect minikube --format='{"Name": "{{.Name}}","Driver": "{{.Driver}}","Subnet": "{{(index .IPAM.Config 0).Subnet}}","Gateway": "{{(index .IPAM.Config 0).Gateway}}",MTU: "{{(index .Options "com.docker.network.driver.mtu")}}",{{$first := true}} "ContainerIPs": [{{range $k,$v := .Containers }} {{if $first}} {{$first = false}}{{else}},{{end}}"{{$v.IPv4Address}}",{{end}}]}'
```

that will output a json
```
{"Name": "minikube","Driver": "bridge","Subnet": "192.168.49.0/24","Gateway": "192.168.49.1",MTU: "1500", "ContainerIPs": [  "192.168.49.3/24", ,"192.168.49.4/24", ,"192.168.49.2/24",]}
```

but the problem is making sure the dateway and subnet get parsed into netinfo struct

so we get more information as a struct, the challenges are making sure it doesn't throw an exception in wide variety of platforms and exceptional cases. when we do json unmarshal

**Comment by valaparthvi** [comment]
@medyagh I would like to take up this issue if it's okay. It would be my first contribution to minikube and this issue looks like a good place to start.

**Comment by medyagh** [comment]
sure, let me know if you have any questions, I am available on slack on minikube's channell.

**Comment by valaparthvi** [comment]
> the challenges are making sure it doesn't throw an exception in wide variety of platforms and exceptional cases. when we do json unmarshal

Can you elaborate on this?

I raised a PR but it's still a WIP because I think I can still improve the code a little. In case you review it do let me know how it looks :)
