### ISSUE TITLE
Fail to resolve kubernetes.default [kvm]

### ISSUE THREAD

**Issue by r2d4** [kubernetes/minikube#970]
```
    		Temporary Error: Temporary Error: Error running command. Error  exit status 1. Output: nslookup: can't resolve 'kubernetes.default'
    		Server:    10.0.0.10
    		Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local
    		
    		
    		Temporary Error: Error running command. Error  exit status 1. Output: nslookup: can't resolve 'kubernetes.default'
    		Server:    10.0.0.10
    		Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local
    		
    		
    		Temporary Error: Error running command. Error  exit status 1. Output: nslookup: can't resolve 'kubernetes.default'
    		Server:    10.0.0.10
    		Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local
```

https://storage.googleapis.com/minikube-builds/logs/965/Linux-KVM.txt

**Comment by dlorenc** [comment]
A little debugging:
From the DNS pod we can resolve things:

```shell
$ kubectl exec kube-dns-v20-wz6t3 --namespace=kube-system nslookup kubernetes.default.svc.cluster.local 127.0.0.1
Defaulting container name to kubedns.
Use 'kubectl describe pod/kube-dns-v20-wz6t3' to see all of the containers in this pod.
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

Name:      kubernetes.default.svc.cluster.local
Address 1: 10.0.0.1 kubernetes.default.svc.cluster.local
```

which makes sense since kube-dns comes with a healthz check that executes this command inside it's own pod, and that's passing.

From a busybox container though, I can't do any resolving:

```shell
$ kubectl exec busybox nslookup kubernetes.default.svc.cluster.local 127.0.0.1
Server:    127.0.0.1
Address 1: 127.0.0.1 localhost

nslookup: can't resolve 'kubernetes.default.svc.cluster.local'
```

**Comment by dlorenc** [comment]
A little more debugging:

it seems like relative DNS lookups are the only ones effected by this. It also seems like an issue with alpine. Using busybox:glibc or a debian image works, but using busybox without glibc fails. I propose we just switch our e2e tests over to glibc.

**Comment by r2d4** [comment]
I'm fine with switching it over to that image if it fixes it

I know there were issues with DNS and alpine images before, but I thought those were resolved.  Is there an upstream issue tracking it?

My only concerns
- the integration test is from copied from the k8s docs  http://kubernetes.io/docs/admin/dns/.  This might make it more confusing to debug when people are having issues with DNS.  
*Although the k8s e2e tests for DNS don't use busybox https://github.com/kubernetes/kubernetes/blob/master/test/e2e/dns.go#L69-L96
- why this only happens with the KVM driver?
- why does it work sometimes?

**Comment by dlorenc** [comment]
Yeah, it's all a bit weird. I discovered the glibc issue while trying to debug. The build of nslookup inside the busybox container doesn't seem to support the debug flags, so I grabbed a debian image and tried to debug there, but then that one worked :)

To get any further we'd need a way to debug the DNS query while it's failing.

**Comment by dlorenc** [comment]
Also the example you linked: http://kubernetes.io/docs/admin/dns/ is slightly different, it uses busybox instead of gcr.io/google-containers/busybox.

gcr.io/google-containers/busybox was last updated in February of last year. It's possible we don't need glibc, and can just grab an updated busybox container.

**Comment by dlorenc** [comment]
This looks related: https://github.com/kubernetes/kubernetes/issues/18934

MUSL and glibc work, it seems like uclibc doesn't.

**Comment by r2d4** [comment]
I'm going to close this for now.  Haven't seen the flake in many tests.  I think https://github.com/kubernetes/minikube/pull/974 fixed it
