### ISSUE TITLE
fix kubeadm unit tests (testdata)

### ISSUE THREAD

**Issue by prezha** [kubernetes/minikube#9707]
ref: #9694
ref: #9693

currently, bsutil (kubeadm) unit tests have hardcoded list of versions to test, referencing `testdata` subdirectories for relevant k8s version to test, and it has to be manually updated with each new version released, eg:

https://github.com/kubernetes/minikube/blob/9b964853a9600eb4661f73a6aef7423c8da96f85/pkg/minikube/bootstrapper/bsutil/kubeadm_test.go#L80

and

https://github.com/kubernetes/minikube/blob/9b964853a9600eb4661f73a6aef7423c8da96f85/pkg/minikube/bootstrapper/bsutil/kubeadm_test.go#L111

we also need to cover the situation where we still don't have the `<major>.<minor>.0` stable version released (eg, as with 'v1.20.0-beta.1'), in which case we should use that latest k8s version until stable version gets released in test data files

therefore, it would be good to:
- have a dynamic (auto-discover) list of k8s versions to test (#9708 will automatically create new testdata set for newer versions), while also
- have only one set (subdirectory) with test data for each `<major>.<minor>` k8s version under `pkg/minikube/bootstrapper/bsutil/testdata/`

**Comment by medyagh** [comment]
this is a good idea
