### ISSUE TITLE
Create versioned formulae in homebrew

### ISSUE THREAD

**Issue by axel-sirota** [kubernetes/minikube#9711]
In homebrew there are no available formulae for past versions since the changes are made over the same formulae. This disables the possibility of going back to a previous version.

```
brew search minikube@
==> Formulae
minikube ✔
```

**Comment by afbjorklund** [comment]
I think you can use git for that, if you _really_ want to...

Why do you need the older minikube versions, BTW ?

**Comment by axel-sirota** [comment]
Yes, I tried using git but now in brew you cannot install from a given commit, you have to create a local formulae, which is a pain...

For example for educational videos you want the least amount of warnings possible, but 1.15.0 has this translation warning mentioned in the Issues that will make learners wonder if it's a local thing of minikube itself. I want to ensure everyone how safe is to develop locally with minikube with 0 warnings! :)

**Comment by afbjorklund** [comment]
Well, that was a bug. Surely fixed in 1.15.1!

You can see locale to en_US as a workaround
