### ISSUE TITLE
Add a button to copy the command to the browser on the docs site

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#9712]
I think that it would be good user experience if we can add a button besides each code snippet which should be copied to the clipboard like several sites do it.

**Comment by priyawadhwa** [comment]
This would be great! If someone is able to contribute this, it would be greatly appreciated.

**Comment by edtrist** [comment]
Happy to take this :)

/assign

**Comment by medyagh** [comment]
@edtrist it is yours ! 

we use docsy for our site https://www.docsy.dev/docs/ 
maybe on their site they have something that we can enable or add
