### ISSUE TITLE
minikube start gives an error connection reset by peer

### ISSUE THREAD

**Issue by joearul09** [kubernetes/minikube#9724]
**Steps to reproduce the issue:** 

1.Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 18.398468512s
💡  Restarting the docker service may improve performance.
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 18.400630923s
💡  Restarting the docker service may improve performance.
❗  Executing "docker container inspect minikube --format={{.State.Status}}" took an unusually long time: 11.435654828s
💡  Restarting the docker service may improve performance.

2. 
3.

**Full output of failed command:** 

Kubernetes master is running at https://172.17.0.2:8443
KubeDNS is running at https://172.17.0.2:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
curl localhost:8443
curl: (7) Failed to connect to localhost port 8443: Connection refused
</details>

**Comment by medyagh** [comment]
@joearul09 the logs indicate that your docker is very slow and is responding slowly, this could mean you might need to prune your docker to make it faster again,.

"docker system prune --all"

@joearul09 I am curious if you have done the advice given by minikube?

```
 Restarting the docker service may improve performance
```

**Comment by medyagh** [comment]
Hi @joearul09, I haven't heard back from you, I wonder if you still have this issue? or if the suggestion helped you ?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
