### ISSUE TITLE
Minikube crashes all the time

### ISSUE THREAD

**Issue by gnarea** [kubernetes/minikube#9729]
Apologies for the vague title, but that's as specific as I can be: Minikube is crashing all the time and I can't figure out why after checking the logs.

This happens even when I'm not using Kubernetes, but I've noticed I can reproduce it consistently when I'm running some automated tests against the services in the cluster.

**Steps to reproduce the issue:** 

1. Create a cluster from scratch: `minikube delete` and `minikube start --driver=virtualbox --cpus=4 --memory=8096`.
2. When all pods are ready according to `kubectl get pod -n kube-system`, I start `skaffold dev` to deploy stuff to the cluster.
3. When all my k8s resources are ready, I run the test suite against some services in the cluster. (These tests are run from the host machine and simply make HTTP requests to the services I deployed to the cluster; they don't use `kubectl`, Minikube or the k8s API)
4. After a few seconds, I'll notice that Skaffold/`kubectl`/etc stops responding, which is consistent with the status of minikube:
   ```
   $ minikube status
   minikube
   type: Control Plane
   host: Stopped
   kubelet: Stopped
   apiserver: Stopped
   kubeconfig: Stopped
   ```

**Full output of failed command:** 

The problem is that the whole Kubernetes is brought down, so I can't use `kubectl` anymore, for example:

```
$ kubectl get pods -A
Unable to connect to the server: dial tcp 192.168.99.105:8443: connect: no route to host
```

**Full output of `minikube start` command used, if not already included:**

   ````
   😄  minikube v1.15.1 on Ubuntu 20.10
   ✨  Using the virtualbox driver based on user configuration
   👍  Starting control plane node minikube in cluster minikube
   🔥  Creating virtualbox VM (CPUs=4, Memory=8096MB, Disk=20000MB) ...
   🐳  Preparing Kubernetes v1.19.4 on Docker 19.03.13 ...
   🔎  Verifying Kubernetes components...
   🌟  Enabled addons: storage-provisioner, default-storageclass
   🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
   ````

**Optional: Full output of `minikube logs` command:**

I'm not able to run `minikube logs` once it crashes, so I do it preemptively with `minikube logs -f  > ~/tmp/minikube.logs 2>&1`. The output is huge so I had to paste it on a gist because GitHub wouldn't let me paste it here: https://gist.github.com/gnarea/53326aac5ded76b3b1e2f918b629250b#file-minikube-logs-txt

In case it's relevant: I'm using Ubuntu 20.20.

**Comment by medyagh** [comment]
hi @gnarea do you mind sharing the output of

```
minikube start --alsologtostderr
``` 

and do you have same problem if you pass force-systemd flag ?
```
minikube start --force-systemd
```

and also do you get the same problem with docker driver ?

**Comment by gnarea** [comment]
Hi @medyagh! Thanks for looking into this. I'll run those commands in a moment and then report back.

In the meantime:

- There's someone else helping replicate this issue on Slack: https://kubernetes.slack.com/archives/C1F5CT6Q1/p1605632817330600
- I have 64 GiB of RAM. And all the pods combined shouldn't need more than 2 GiB.

**Comment by medyagh** [comment]
per conversation in slack, this issue was solved by using the docker driver
