### ISSUE TITLE
add new target `make push-kic-base-snapshot`

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9735]
we could have a new 'make target' called 'make release kic-base-snapshot' that will bump the kicbase verison in types.go to -snapshot-COMIT_ID (6 digit commit sha)
then push it to all 3 repos
and also make sure it builds the kicbase only once
(I think once I noticed it it was building it 3 times)

then commits and makes a PR 

I want us to be able to, as soon as we merge a kicbase file change , we just run "make release-kic-base-snapshot" and it just makes a PR with new image

**Comment by prezha** [comment]
you are most welcome @medyagh
/assign
