### ISSUE TITLE
Show download progress for the Preload Tarball

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#9740]
![image](https://user-images.githubusercontent.com/6985763/99715469-ee9e9f80-2acc-11eb-83a6-1ae5510c0c8d.png)

As you can see in the above screenshot, we don't show the progress of the download. It is missing the bandwidth, size of remaining content, ETA etc. like we show for the ISO.

Since this preload tarball is big, the above information is essential.

**Comment by afbjorklund** [comment]
We have the same issue for the kicbase: #7175

**Comment by afbjorklund** [comment]
We're using the same library and the same storage for both, so it must be something else ?

**Comment by afbjorklund** [comment]
The responses look similar enough:

`curl --head https://storage.googleapis.com/minikube/iso/minikube-v1.15.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.15.0.iso.sha256`
HTTP/2 200 
...
accept-ranges: bytes
content-length: 189796352
...
`curl --head https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4`

HTTP/2 200 
...
accept-ranges: bytes
content-length: 509973850
...

**Comment by afbjorklund** [comment]
The `pb` library omits the progress bar, when the file name is too long (for the terminal).

80
    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 112.34 MiB^C
180
    > preloaded-images-k8s-v6-v1.19.4-docker-overlay2-amd64.tar.lz4: 205.77 MiB / 486.35 MiB [----------------------->________________________________] 42.31% 38.59 MiB p/s ETA 7s^C

So the filename needs to be truncated (...), before it is used for the progress.

**Comment by afbjorklund** [comment]
In order to also show the actual progress bar, we need to stay below 15 characters. Otherwise it won't fit.
This does not really give us space to show the file name. For instance, "minikube-v1.15.0.iso" is 20...

```
💿  Downloading VM boot image ...
    > minikube-v1.15.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.15.0.iso: 181.00 MiB / 181.00 MiB [] 100.00% 33.18 MiB p/s 5s
👍  Starting control plane node minikube in cluster minikube
```

One approach would be to use **two** lines, and then display the full filename and a full progress bar.
Or use a more avanced library, that would offer more options to display all the information available ?

* https://github.com/tianon/go-progress
* https://pypi.org/project/progress/

**Comment by blueelvis** [comment]
Maybe we could just omit that information from the main output but show the full name in the verbose logs?

**Comment by afbjorklund** [comment]
I would like to show a _little_ information. Currently docker doesn't show anything, and it is a bit annoying.

**Comment by afbjorklund** [comment]
And we do show the URL in the logs already.

That `>` looks a bit with all the emoji, too...

The rest of minikube interface is more like this:

https://jamiemaison.github.io/react-emoji-progress-bar/

**Comment by afbjorklund** [comment]
Example output:

```
😄  minikube v1.15.1 on Ubuntu 20.04
✨  Using the virtualbox driver based on existing profile
💿  Downloading VM boot image ...
    181.00 MiB / 181.00 MiB [------------------------] 100.00% 30.54 MiB p/s 6s
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
```
