### ISSUE TITLE
service failure test logs deadline exceeded (1.77µs)

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9741]
```
 kubectl --context functional-20201119014419-7280 describe po hello-node: context deadline exceeded (1.77µs)

```

as seen here

https://storage.googleapis.com/minikube-builds/logs/9734/6c6329e/KVM_Linux.html#fail_TestFunctional%2fparallel%2fServiceCmd

and as discussed here https://kubernetes.slack.com/archives/C1F5CT6Q1/p1605813267401000

**Comment by spowelljr** [comment]
This should hopefully be fixed by #9978
