### ISSUE TITLE
erro minikube start

### ISSUE THREAD

**Issue by devblack21** [kubernetes/minikube#9745]
**Os comandos necessários para reproduzir o problema**:
minikube start
 
**A saída completa do comando que apresentou falha**: 

<details>
stderr:
W1119 20:43:27.044618    8318 configset.go:348] WARNING: kubeadm cannot validate component configs for API groups [kubelet.config.k8s.io kubeproxy.config.k8s.io]
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables does not exist
        [WARNING Swap]: running with swap on is not supported. Please disable swap
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase certs/apiserver: failed to write or validate certificate "apiserver": failure loading apiserver certificate: failed to load certificate: couldn't load the certificate file /var/lib/minikube/certs/apiserver.crt: error reading /var/lib/minikube/certs/apiserver.crt: x509: cannot parse IP address of length 0
To see the stack trace of this error execute with --v=5 or higher

</details>

**A versão do sistema operacional usado**: windows 10

**Comment by tstromberg** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by TomDinunzioMH** [comment]
We came across this issue. In our case both the people running into the issue had $DOCKER_HOST set to an URL locally on their hosts.
I beleive it was broken by 996b05bfc10dcd98515c7fd45363383821a79ff6.
If the $DOCKER_HOST env is not an IP, net.ParseIP() returns nil, which gets added to /var/lib/minikube/certs/apiserver.crt as Subject Alternative Name.

ie. 
```
$ cat /var/lib/minikube/certs/apiserver.crt | openssl x509 --noout --text
{…}
            X509v3 Subject Alternative Name:
                DNS:minikubeCA, DNS:control-plane.minikube.internal, DNS:kubernetes.default.svc.cluster.local, DNS:kubernetes.default.svc, DNS:kubernetes.default, DNS:kubernetes, DNS:localhost, IP Address:192.168.99.109, IP Address:10.96.0.1, IP Address:127.0.0.1, IP Address:10.0.0.1, IP Address:<invalid>
{…}
```
As a workaround unsetting $DOCKER_HOST solves the problem.
