### ISSUE TITLE
Insecure Registry Option Ignored

### ISSUE THREAD

**Issue by millerbill3** [kubernetes/minikube#975]
**BUG REPORT**

**Minikube version**: v0.14.0

**Environment**:
- **OS**: Mac OS Sierra 10.12.2
- **VM Driver**: virtualbox
- **Docker version** (e.g. `docker -v`): 1.12.5, build 7392c3b
- **Install tools**:
- **Others**:

**What happened**: Inability to pull docker images from private registry from within minikube environment

**What you expected to happen**: Using kubectl, create a StatefulSet and have the StatefulSet configuration be able to pull the image from the private registry

**How to reproduce it** (as minimally and precisely as possible): Probably can't as this is environment specific.

**Anything else do we need to know**: Here's the gist of it... I have a private Docker Registry and have created a "Secret" to allow me to pull images using specific credentials. When I launch minikube, I use `minikube start --insecure-registry=<ip address>:5000`. The minikube instance starts successfully, but whenever I attempt to create a ReplicationController or StatefulSet (something requiring an image pull) it fails with the following error:
```
SchedulerPredicates failed due to PersistentVolumeClaim is not bound: "ml-data-marklogic-0", which is unexpected.
Failed to pull image "<ip address>/dcgs-sof/ml8-final:latest": Error response from daemon: Get https://<ip address>/v1/_ping: dial tcp <ip address>:443: getsockopt: connection refused
Error syncing pod, skipping: failed to "StartContainer" for "marklogic" with ErrImagePull: "Error response from daemon: Get https://<ip address>/v1/_ping: dial tcp <ip address>:443: getsockopt: connection refused"> 
```
It appears it's still attempting to pull using a "secure" registry. This worked before I upgraded to the most current version 0.14.0. Does minikube no longer support the `--insecure-registry` flag?

**Comment by millerbill3** [comment]
Deleted minikube original configuration folder and recreated the instance. Seemed to fix the problem

**Comment by yoanisgil** [comment]
It looks like the `insecure-registry` flag is only taken into consideration when running `minikube start` for the first time. In my case I had to edit this file `~/.minikube/machines/minikube/config.json` (to avoid deleting the entire machine configuration or creating a brand new machine. I modified the `InsecureRegistry` option under `EngineOptions'`.
