### ISSUE TITLE
minikube failed to start on ubuntu 16.06

### ISSUE THREAD

**Issue by abdoo** [kubernetes/minikube#976]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Minikube version** (use `minikube version`): v0.14.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04.1 LTS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "virtualbox"
- **Docker version** (e.g. `docker -v`):
- **Install tools**: minikube command
- **Others**: nothing

**What happened**:

root@mini-ubuntu:~# minikube start --memory=4000 --cpus=2 --disk-size=10 --container-runtime=rkt --network-plugin=cni --kubernetes-version=v1.4.7
Starting local Kubernetes cluster...
E0109 12:07:54.938996    1920 start.go:94] Error starting host: Error getting state for host: machine does not exist.

 Retrying.
E0109 12:07:54.939972    1920 start.go:100] Error starting host:  Error getting state for host: machine does not exist

An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
Please enter your response [Y/n]

**What you expected to happen**:
I expect to start minikube normally

**How to reproduce it** (as minimally and precisely as possible):
Everytime I do start it fails.

**Anything else do we need to know**:
I deleted .minikube directory and it didn't help.
do I need to install docker or something. It is not mentioned as a part or requirement for minikube.

**Comment by r2d4** [comment]
Not sure if this is your issue but we haven't gotten around to publishing a 1.4.7 k8s release

```
$ minikube get-k8s-versions
The following Kubernetes versions are available: 
	- v1.5.1
	- v1.4.5
	- v1.4.3
	- v1.4.2
	- v1.4.1
	- v1.4.0
	- v1.3.7
	- v1.3.6
	- v1.3.5
	- v1.3.4
	- v1.3.3
	- v1.3.0
```

**Comment by abdoo** [comment]
I tried 1.4.3 and 1.4.5 and I got the same error. I think it is a different error.

do I need to have docker installed. I have virtualbox 5.1.12 installed.

**Comment by r2d4** [comment]
You do not need to have docker installed.

Can you try a `minikube delete` and then changing the `--disk-size` flag to `10g`.  Right now you just have it as `10`, which is probably not what you want.

```
--disk-size string                Disk size allocated to the minikube VM (format: <number>[<unit>], where unit = b, k, m or g) (default "20g")
```

**Comment by abdoo** [comment]
oh man, that was the trick :-)

letmein@mini-ubuntu:~$ minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
letmein@mini-ubuntu:~$ minikube start --memory=4000 --cpus=2 --disk-size=10g --container-runtime=rkt --network-plugin=cni --kubernetes-version=v1.4.7
Starting local Kubernetes cluster...
E0109 14:03:16.660948    2988 start.go:117] Error updating cluster:  Error updating localkube from uri: Error attempting to download and cache localkube: Error getting localkube download url: Invalid localkube version
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:

**Comment by r2d4** [comment]
We should throw helpful errors when 

- [ ] The kubernetes version is not found
- [ ] disk size is too low (We probably need a minimum of 2gb?)

**Comment by abdoo** [comment]
Finally I have it. but I cant get pods?

letmein@mini-ubuntu:~$ minikube start --memory=4000 --cpus=2 --disk-size=10g --container-runtime=rkt --network-plugin=cni --kubernetes-version=v1.4.5
Starting local Kubernetes cluster...
Downloading localkube binary
 77.35 MB / 77.35 MB [==============================================] 100.00% 0s
Kubectl is now configured to use the cluster.
letmein@mini-ubuntu:~$ kubectl get pods
Unable to connect to the server: Forbidden

**Comment by abdoo** [comment]
I wanted to add that I'm running my ubuntu server behind a proxy.

**Comment by abdoo** [comment]
root@mini-ubuntu:~# kubectl -v7 get pods
I0109 14:56:33.549215    5275 loader.go:354] Config loaded from file /root/.kube/config
I0109 14:56:33.550304    5275 round_trippers.go:296] GET https://192.168.99.100:8443/api
I0109 14:56:33.550333    5275 round_trippers.go:303] Request Headers:
I0109 14:56:33.550342    5275 round_trippers.go:306]     Accept: application/json, */*
I0109 14:56:33.550349    5275 round_trippers.go:306]     User-Agent: kubectl/v1.5.1 (linux/amd64) kubernetes/82450d0
I0109 14:56:33.553488    5275 round_trippers.go:321] Response Status:  in 3 milliseconds
I0109 14:56:33.553618    5275 helpers.go:221] Connection error: Get https://192.168.99.100:8443/api: Forbidden
F0109 14:56:33.553658    5275 helpers.go:116] Unable to connect to the server: Forbidden

**Comment by abdoo** [comment]
I had to stop and start again the cluster and kubectl worked fine.
