### ISSUE TITLE
Error starting minikube via Virtual box  # minikube start --driver=virtualbox --no-vtx-check

### ISSUE THREAD

**Issue by aravindsaravanan** [kubernetes/minikube#9763]
<minikube start --driver=virtualbox --no-vtx-check>
**Steps to reproduce the issue:** 

1.
[start-issue.txt](https://github.com/kubernetes/minikube/files/5579128/start-issue.txt)

2.  I have attached the runtime error log here, please find the attachment named "start-issue.txt"
3.  Though the Minikube VM is alive and running # minikube.exe profile list showing stopped and # kubectl run commands are throwing errors
➤ minikube.exe profile list
|----------|------------|---------|----------------|------|---------|---------|
| Profile  | VM Driver  | Runtime |       IP       | Port | Version | Status  |
|----------|------------|---------|----------------|------|---------|---------|
| minikube | virtualbox | docker  | 192.168.99.103 | 8443 | v1.19.2 | Stopped |
|----------|------------|---------|----------------|------|---------|---------|

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
[minikube-log-cmd.txt](https://github.com/kubernetes/minikube/files/5579134/minikube-log-cmd.txt)

**Optional: Full output of `minikube logs` command:**

<details>

</details>

**Comment by aravindsaravanan** [comment]
[Saravanan.BYOD-SPONNURA] ➤ minikube status
E1122 13:33:52.582366   18152 status.go:363] kubeconfig endpoint: extract IP: "minikube" does not appear in C:\Users\aravi/.kube/config
minikube
type: Control Plane
host: Running
kubelet: Stopped
apiserver: Stopped
kubeconfig: Misconfigured

**Comment by priyawadhwa** [comment]
Hey @aravindsaravanan thanks for opening this issue and sorry for the delayed response.

It looks like `kubeadm init` failed with a SEGV:
>X Exiting due to GUEST_START: run: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.19.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap": Process exited with status 139 from signal SEGV


Could you try deleting your cluster and restarting?
```
minikube delete
minikube start
```
If this fails, I would recommend trying:
1. starting with more memory `minikube start --memory <at least 2GB, but try with more if you can>
2. If you have docker installed, trying the docker driver instead of virtualbox since it is our recommended driver. You can dot his by running `minikube delete && minikube start --driver docker` 

If these fail, the output of `minikube start --alsologtostderr` would be helpful for debugging. Thank you!

**Comment by priyawadhwa** [comment]
related issue https://github.com/kubernetes/minikube/issues/8773

**Comment by priyawadhwa** [comment]
Hey @aravindsaravanan are you still seeing this issue?

**Comment by aravindsaravanan** [comment]
Hi Priya,

Docker Desktop for windows is seems working, Hence this can archive.


Thanks & Regards,
Saravanan P

**Comment by priyawadhwa** [comment]
Great, thanks!
