### ISSUE TITLE
WSL2: Cannot access kubernetes services

### ISSUE THREAD

**Issue by shinebayar-g** [kubernetes/minikube#9765]
**Steps to reproduce the issue:** 

1. Install Docker for Windows with WSL2 backend support. Docs: https://docs.docker.com/docker-for-windows/wsl/
2. Install latest minikube version for linux on WSL2 Ubuntu 20.04 LTS. Docs: https://minikube.sigs.k8s.io/docs/start/#debian-package
```
$ minikube version
minikube version: v1.15.1
commit: 23f40a012abb52eff365ff99a709501a61ac5876
```
3. Start kubernetes cluster
```
minikube config set driver docker
minikube config set memory 8192   (Does this settings work on docker driver?)
minikube config set cpus 4   (Does this settings work on docker driver?)
minikube config set kubernetes-version v1.18.12
minikube start
```

4. Try to access kubernetes dashboard
```
$ minikube dashboard
🤔  Verifying dashboard health ...
🚀  Launching proxy ...
🤔  Verifying proxy health ...
🎉  Opening http://127.0.0.1:33067/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/ in your default browser...
👉  http://127.0.0.1:33067/api/v1/namespaces/kubernetes-dashboard/services/http:kubernetes-dashboard:/proxy/
```

Result:
![image](https://user-images.githubusercontent.com/3091558/99977963-56761400-2d73-11eb-90a8-bcc7a459102c.png)

5. Let's try another example from [docs](https://minikube.sigs.k8s.io/docs/start/)

```
$ kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
$ kubectl expose deployment hello-minikube --type=NodePort --port=8080
$ minikube service hello-minikube
|-----------|----------------|-------------|---------------------------|
| NAMESPACE |      NAME      | TARGET PORT |            URL            |
|-----------|----------------|-------------|---------------------------|
| default   | hello-minikube |        8080 | http://192.168.49.2:30453 |
|-----------|----------------|-------------|---------------------------|
🏃  Starting tunnel for service hello-minikube.
|-----------|----------------|-------------|------------------------|
| NAMESPACE |      NAME      | TARGET PORT |          URL           |
|-----------|----------------|-------------|------------------------|
| default   | hello-minikube |             | http://127.0.0.1:45463 |
|-----------|----------------|-------------|------------------------|
🎉  Opening service default/hello-minikube in default browser...
👉  http://127.0.0.1:45463
❗  Because you are using a Docker driver on linux, the terminal needs to be open to run it.
```

Result:

![image](https://user-images.githubusercontent.com/3091558/99978211-a8b73500-2d73-11eb-933f-7400898ab417.png)

Another try:

```
$  kubectl port-forward service/hello-minikube 7080:8080
Forwarding from 127.0.0.1:7080 -> 8080
Forwarding from [::1]:7080 -> 8080
```

Result:
![image](https://user-images.githubusercontent.com/3091558/99978328-d00e0200-2d73-11eb-8211-3597d5ef8664.png)

Anyone knows what's wrong or it doesn't work?

**Comment by afbjorklund** [comment]
> `minikube config set memory 8192`   (Does this settings work on docker driver?)
> `minikube config set cpus 4`   (Does this settings work on docker driver?)

On the docker driver, these are limits rather than VM resources

If you are using a VM for docker (or in general, like WSL2) you still need to configure that.
When running docker on linux, the bound is the amount of resources the docker host has.

**Comment by shinebayar-g** [comment]
Thanks for the explanation.

**Comment by shinebayar-g** [comment]
It's working! Thanks to [this](https://github.com/microsoft/WSL/issues/4199#issuecomment-668270398) person, now everything is working as expected.

`wsl --shutdown` did the job.  I also ran `kubectl port-forward` on PowerShell, not Terminall app if that helps.
