### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by GoodBoy020** [kubernetes/minikube#9771]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by GoodBoy020** [comment]
CHANGELOG.md

**Comment by GoodBoy020** [comment]
> CHANGELOG.md

![common_content_Nav-Feed](https://user-images.githubusercontent.com/68087598/100127404-f8caf000-2e76-11eb-9215-724610e6b7d2.png)
![Nav-Code 0tJczmQtl3hyKtlh](https://user-images.githubusercontent.com/68087598/100127410-f9fc1d00-2e76-11eb-98f7-5c83cfd9a99a.png)
![Nav-Dashboard S24hPDN9_BLImMxi](https://user-images.githubusercontent.com/68087598/100127411-f9fc1d00-2e76-11eb-9e25-8cc5f8f78448.png)
![Nav-Launch 3tiJhd8JGiL0mrog](https://user-images.githubusercontent.com/68087598/100127412-fa94b380-2e76-11eb-902e-afd80174fb64.png)
![Nav-Plan XB8qU6v7kvBk_Tcy](https://user-images.githubusercontent.com/68087598/100127415-fa94b380-2e76-11eb-9572-3ed13c565387.png)

**Comment by medyagh** [comment]
@GoodBoy020 do u mind adding more details to what u meant by this issue ?

/triage needs-information
/kind support
