### ISSUE TITLE
profile list for multi node shows error wrongfully

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9772]
as noted by @sharifelgamal the missing part of this PR is left https://github.com/kubernetes/minikube/pull/9702#issuecomment-731445695
```

|----------|-----------|---------|--------------|------|---------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes |
|----------|-----------|---------|--------------|------|---------|---------|-------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.19.4 | Running |     1 |
| p2       | docker    | docker  | 192.168.59.2 | 8443 | v1.19.4 | Running |     2 |
|----------|-----------|---------|--------------|------|---------|---------|-------|
❗  Found 1 invalid profile(s) ! 
	 p2-m02
💡  You can delete them using the following command(s): 
	 $ minikube delete -p p2-m02 
```

**Comment by daehyeok** [comment]
Do we have any reason check both of directory and container in the ListProfiles func? https://github.com/kubernetes/minikube/blob/b4bf2bde332c8dea45bc717f23a58caea6d0e1dc/pkg/minikube/config/profile.go#L197 

Is it added to remove all nodes when run delete profile command(https://github.com/kubernetes/minikube/commit/58b637b05fe3485ecbf50834fda84beeedfd044a)? It looks nodes and profiles are not distinguished in the function. (E.g. seconds node p2-m02 also returned as invalid 'profile' by ListProfiles func).

Currently, returned invalidProfiles used only for List, Delete, Valid profile. I'm not sure if i remove sub node(profile) from ListProfiles's result(but also change Delete profile function to keep handling multiple nodes), It will have potential problems or not.

**Comment by medyagh** [comment]
one reason I am thinking is in the clean up process, when there is no minikube config, 
we use the existing Directory as Possible left over minikubes so we use that delete minikube left over containers

**Comment by medyagh** [comment]
https://github.com/medyagh/minikube/blob/0a5ef42ed548d65694b6d96b487fbe0bf8b3db01/pkg/minikube/machine/delete.go#L39

**Comment by daehyeok** [comment]
Is it anyway to check node is part of multnode cluster or not?
