### ISSUE TITLE
Add documentation on how to delete images/containers/network/volumes created by minikube

### ISSUE THREAD

**Issue by FabriceSalvaire** [kubernetes/minikube#9800]
I think you should explain further how to delete data when a minikube test failed ... e.g. just after "If minikube fails to start, ..."

I found later at the end of https://minikube.sigs.k8s.io/docs/start/

```
minikube delete --all
```

But before I did that:

Run as root !!!

```
podman system prune

podman ps

podman images
pdoman rmi ...

podman volume list
pdoman volume prune
```

and look also $HOME/.minikube

**Comment by afbjorklund** [comment]
This removes a whole lot more than just minikube, though.

**Comment by medyagh** [comment]
@FabriceSalvaire 
the command to delete everything on minikube is
```
minikube delete --all --purge
```
we could add this to our FAQ


https://minikube.sigs.k8s.io/docs/faq/
