### ISSUE TITLE
Virtual Box VM not starting

### ISSUE THREAD

**Issue by erakjha** [kubernetes/minikube#9806]
[VBoxSVC.log](https://github.com/kubernetes/minikube/files/5615153/VBoxSVC.log)

**Steps to reproduce the issue:** 

1.Install the minikube on Windows 10
2. Open the Windows Shell and run Command "minikiube start"
3.

**Full output of failed command:** 
PS C:\WINDOWS\system32> minikube start
* minikube v1.15.1 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Unable to start the VM: exit status 1
* Restarting existing virtualbox VM for "minikube" ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: driver start: Unable to start the VM: exit status 1

X Exiting due to GUEST_PROVISION: Failed to start host: driver start: Unable to start the VM: exit status 1
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by spowelljr** [comment]
Please re-run with `minikube start --v=8 --alsologtostderr` and update the logs.
Please also run `minikube logs` and include those as well.

**Comment by priyawadhwa** [comment]
Hey @erakjha I noticed these logs in your output:

>00:00:17.250747 main     ERROR [COM]: aRC=VBOX_E_OBJECT_IN_USE (0x80bb000c) aIID={05f2bbb6-a3a6-4fb9-9b49-6d0dda7142ac} aComponent={Medium} aText={Medium 'C:\Users\hp\.minikube\machines\minikube\disk.vmdk' cannot be closed because it is still attached to 1 virtual machines}, preserve=false

I would recommend running:

```
minikube delete --all
```
and manually cleaning up any virtualbox VMs leftover and see if that resolves the issue?

**Comment by ilya-zuyev** [comment]
Hi @erakjha! Any update on this issue?

**Comment by sharifelgamal** [comment]
Hey @erakjha, we haven't received an update on this issue in quite some time, so I'm going to go ahead and close it. If your problem persists, please reopen this issue and post the output of `minikube start --v=8 --alsologtostderr` and `minikube logs`.
