### ISSUE TITLE
Add static IP for KVM driver

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9809]
similar to our docker and podman driver implementation

**Comment by RA489** [comment]
if we create custom network for KVM , we can set a fixed ip when running the container --ip and hopefully we don't have conflict with subnets with existing networks as KVM has fixed subnet and if it doesn't we can try other options https://github.com/kubernetes/minikube/blob/master/pkg/drivers/kvm/network.go#L41

**Comment by medyagh** [comment]
this task is assigned to @prezha
