### ISSUE TITLE
Less memory

### ISSUE THREAD

**Issue by DolapoOba** [kubernetes/minikube#9817]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide more details ?

Did you mean minikube should use less memory ?

if so have you tried the --memory flag ? by default minikube will allocate memory automatically based on your free resources, but you can limit it to the minimum allowed which is

```
minikube start --memory=2000mb
```
/triage needs-information
/kind support

**Comment by priyawadhwa** [comment]
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.

Thank you for sharing your experience!
