### ISSUE TITLE
multinode fails conformance test with kindnet (but calico works)

### ISSUE THREAD

**Issue by azhao155** [kubernetes/minikube#9825]
Run the conformance test with default kindnet cni. Tests failed due to coreDNS can't resolve service name on the non-mater nodes. 

Run the same test for calico cni for both docker and containerd runtime. All passed. 

There are two things we could do:
1. Change default cni to a more lightweight one which pass all the conformance tests.
2. Investigate the kindnet dns issue.

The attachment are the tests log for calico with docker and containerd runtime.

[e2e.log](https://github.com/kubernetes/minikube/files/5631125/e2e.log)
[e2e.log](https://github.com/kubernetes/minikube/files/5631132/e2e.log)

**Comment by azhao155** [comment]
@medyagh 
@sharifelgamal

**Comment by tstromberg** [comment]
I imagine that the CoreDNS issue might be that the non-master node can't access CoreDNS on the master. 

I'd be open to switching CNI's if another works as well without a performance penalty.

Any movement on this?

**Comment by sharifelgamal** [comment]
I think we'd need to do some benchmarking with each of the passing CNI and figure out the best path forward that way. In addition, there was a PR (#9875) that will have probably fixed kindnet in general. We should rerun conformance with kindnet to double check.

**Comment by prezha** [comment]
i think this issue could be resolved by #10985 with kindnet cni
