### ISSUE TITLE
minikube installation section is empty under Get Started

### ISSUE THREAD

**Issue by qiang0** [kubernetes/minikube#9835]
"Installation" section is empty.
https://minikube.sigs.k8s.io/docs/start/

**Comment by afbjorklund** [comment]
Which platform and browser ? There is supposed to be three tabs

![installation](https://user-images.githubusercontent.com/10364051/101056901-c19dc280-358b-11eb-963e-5578449f3a74.png)

**Comment by qiang0** [comment]
I access this page on with Chrome, on Windows 10 OS.
I access it thru proxy, but it's been set properly and all other contents shown well.
![image](https://user-images.githubusercontent.com/10744290/101111049-4bde3900-3615-11eb-92ab-ec983f0948e2.png)

**Comment by afbjorklund** [comment]
Possibly related to #9814

**Comment by qiang0** [comment]
Seems like table size shrink to 1 pixel on the vertical direction.
![image](https://user-images.githubusercontent.com/10744290/101324021-81e51c80-38a4-11eb-954b-9ccf81688efe.png)

**Comment by afbjorklund** [comment]
Thanks for this information, it does like the jQuery code has some issues - any failure, and it will "hide" the instructions

If you search for `$ is not defined`, you get **lots** of similar hits. In this case, it was from "ERR_CONNECTION_RESET".

**Comment by afbjorklund** [comment]
@spowelljr : any chance of making the code more robust against such connectivity failures, and have a nicer fallback ?

**Comment by spowelljr** [comment]
@afbjorklund I can definitely take a look at this, I tested on a commit before #9814 and it does the same thing when jQuery fails to load, so reverting my change will not fix this.

**Comment by Aut0R3V** [comment]
@afbjorklund I'm interested in working about the documentation for the issue. After I understand the stuff I'd send a PR
