### ISSUE TITLE
Minikube isn't able to reach Docker Hub on Fedora 33

### ISSUE THREAD

**Issue by ppatierno** [kubernetes/minikube#9836]
**Steps to reproduce the issue:** 

1. minikube start
2. Try to create a Deployment with a Docker Hub image

**Output**

Minikube starts but then the Docker daemon is not able to pull an image from Docker Hub with following error.

```shell
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  39s                default-scheduler  Successfully assigned default/strimzi-cluster-operator-54ff55979f-k5rx8 to minikube
  Warning  Failed     23s                kubelet, minikube  Failed to pull image "strimzi/operator:0.20.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
  Normal   BackOff    23s                kubelet, minikube  Back-off pulling image "strimzi/operator:0.20.0"
  Warning  Failed     23s                kubelet, minikube  Error: ImagePullBackOff
  Normal   Pulling    12s (x2 over 38s)  kubelet, minikube  Pulling image "strimzi/operator:0.20.0"
  Warning  Failed     8s (x2 over 23s)   kubelet, minikube  Error: ErrImagePull
  Warning  Failed     8s                 kubelet, minikube  Failed to pull image "strimzi/operator:0.20.0": rpc error: code = Unknown desc = Error response from daemon: Get https://registry-1.docker.io/v2/: dial tcp: lookup registry-1.docker.io on 192.168.49.1:53: read udp 192.168.49.2:35716->192.168.49.1:53: i/o timeout
```

This was just working before updating to Fedora 33.

**Comment by ppatierno** [comment]
I solved switching to use `--driver=kvm2` ... any specific reason why it's needed now on Fedora 33 and the default `--driver=docker` (used by default when auto-detect on my machine) doesn't work?

**Comment by afbjorklund** [comment]
Probably cgroups v2, but hard to tell without the logs

**Comment by priyawadhwa** [comment]
Hey @ppatierno friendly ping, can you run other docker containers without any issues?

**Comment by ppatierno** [comment]
It was a problem with Fedora trusted zone firewall. I fixed via this https://dev.to/yzwdroid/fedora-33-docker-445k
We can close this issue then.

**Comment by afbjorklund** [comment]
@ppatierno : if you install the new Docker (20.10, rather than 19.03) and runc, it should now support cgroups v2 as well.

https://docs.docker.com/engine/install/fedora/

The system version is still older than the vendor version, and I'm not sure if they will update it (or just go with podman)

https://src.fedoraproject.org/rpms/moby-engine
