### ISSUE TITLE
crio + docker + wsl2: Module br_netfilter not found in directory /lib/modules/4.19.128-microsoft-standard

### ISSUE THREAD

**Issue by NatsumiHB** [kubernetes/minikube#9837]
**Steps to reproduce the issue:** 

1. Run `minikube start --container-runtime=cri-o`
2. Get `modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/4.19.128-microsoft-standard`

**Full output of failed command:** 
```
😄  minikube v1.15.1 on Microsoft Windows 10 Pro 10.0.19041 Build 19041
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.19.4 preload ...
    > preloaded-images-k8s-v6-v1.19.4-cri-o-overlay-amd64.tar.lz4: 551.20 MiB /
🔥  Creating docker container (CPUs=2, Memory=3885MB) ...

❌  Exiting due to RUNTIME_ENABLE: br_netfilter: sudo modprobe br_netfilter: Process exited with status 1
stdout:

stderr:
modprobe: FATAL: Module br_netfilter not found in directory /lib/modules/4.19.128-microsoft-standard


😿  If the above advice does not help, please let us know:
```

**Full output of `minikube start` command used:**
https://haste.natsumi.dev/luziwocotu

I was trying to run minikube with cri-o as container runtime and docker as driver as I want to prepare for Kubernetes v.1.20 deprecating the docker container runtime.

**Comment by NatsumiHB** [comment]
Addition: Searching for the error yielded no usable results

**Comment by tstromberg** [comment]
I suspect the way we check for the kernel module may not be appropriate for your environment (WSL2? not sure). I'll propose an alternate PR for you to try.

**Comment by NatsumiHB** [comment]
Nope, I'm not using WSL2. It's running natively on Windows with Docker as host. Docker does have the WSL2 integrated enabled but I don't think that's the cause.

**Comment by afbjorklund** [comment]
Kubernetes 1.20 is only deprecating the dockershim, not the docker container runtime.
And it does seem like your Docker is using WSL, but we fail to detect br_netfilter in it...

**Comment by NatsumiHB** [comment]
> Kubernetes 1.20 is only deprecating the dockershim, not the docker container runtime.
I know but (to my knowledge) they will get rid of the dockershim and therefore docker runtime support as early as v1.23 so I want to prepare with using CRI-O.

> And it does seem like your Docker is using WSL, but we fail to detect br_netfilter in it...
Right, I forgot that that's a thing, sorry for the confusion.

**Comment by tstromberg** [comment]
I can confirm that `--container-runtime=crio` is as broken within WSL2 using master. I'll try to send a PR out for this today.
