### ISSUE TITLE
Aiuda!!!

### ISSUE THREAD

**Issue by SanchezjCoronado** [kubernetes/minikube#9845]
**Los comandos necesarios para reproducir la incidencia**:

**El resultado completo del comando que ha fallado**: <details>

</details>

**El resultado del comando `minikube logs`**: <details>

</details>

**La versión del sistema operativo que utilizaste**:

**Comment by medyagh** [comment]
Thank you for sharing your experience! If you don't mind, could you please provide:

- The version of minikube.
- The driver you are using. (docker, virtualbox, hyperv....)
- The Operation system you are using (windows, mac or linux and version of it)
- The full output of the command you are using by adding --alsologtostderr -v=8 for example
```
minikube start --alsologtostderr -v=8
```
- Also the full the output of the 
```
$ minikube logs
```` 

This will help us isolate the problem further. Thank you!

/triage needs-information
/kind support

**Comment by tstromberg** [comment]
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!
