### ISSUE TITLE
Minikube Offline usage

### ISSUE THREAD

**Issue by gbuchupa** [kubernetes/minikube#9846]
I am trying to install minikube and it dependencies and trying to start minikube offline after copying ".minikube/cache" folder contents from a running minikube machine. But it still throws following error message to me.

[3:12 PM, 12/3/2020] Gangs: bharat@Bharat-Desktop:~$ minikube start
😄  minikube v1.15.1 on Ubuntu 20.04
🆕  Kubernetes 1.19.4 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.19.4
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
E1203 15:08:51.377702    6407 cache.go:179] Error downloading kic artifacts:  failed to download **kic base image or any fallback image**
E1203 15:08:51.379498    6407 cache.go:63] save image to file "docker.io/kubernetesui/metrics-scraper:v1.0.4" -> "/home/bharat/.minikube/cache/images/docker.io/kubernetesui/metrics-scraper_v1.0.4" failed: nil image for **docker.io/kubernetesui/metrics-scraper:v1.0.4**: Get "https://index.docker.io/v2/": dial tcp: lookup index.docker.io: no such host
E1203 15:08:51.379551    6407 cache.go:63] save image to file "docker.io/kubernetesui/dashboard:v2.0.3" -> "/home/bharat/.minikube/cache/images/docker.io/kubernetesui/dashboard_v2.0.3" failed: nil image for **docker.io/kubernetesui/dashboard:v2.0.3**: Get "https://index.docker.io/v2/": dial tcp: lookup index.docker.io: no such host
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.13@sha256:4d43acbd0050148d4bc399931f1b15253b5e73815b63a67b8ab4a5c9e523403f -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image '**gcr.io/k8s-minikube/kicbase:v0.0.13**@sha256:4d43acbd0050148d4bc399931f1b15253b5e73815b63a67b8ab4a5c9e523403f' locally
docker: Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io: no such host.
See 'docker run --help'.

🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
😿  Failed to start docker container. Running "minikube delete" may fix it: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.13@sha256:4d43acbd0050148d4bc399931f1b15253b5e73815b63a67b8ab4a5c9e523403f -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image '**gcr.io/k8s-minikube/kicbase:v0.0.13**@sha256:4d43acbd0050148d4bc399931f1b15253b5e73815b63a67b8ab4a5c9e523403f' locally
docker: Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io: no such host.
See 'docker run --help'.

❌  Exiting due to INET_LOOKUP_HOST: Failed to start host: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.13@sha256:4d43acbd0050148d4bc399931f1b15253b5e73815b63a67b8ab4a5c9e523403f -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image '**gcr.io/k8s-minikube/kicbase:v0.0.13**@sha256:4d43acbd0050148d4bc399931f1b15253b5e73815b63a67b8ab4a5c9e523403f' locally
docker: Error response from daemon: Get https://gcr.io/v2/: dial tcp: lookup gcr.io: no such host.
See 'docker run --help'.

💡  Suggestion: Verify that your HTTP_PROXY and HTTPS_PROXY environment variables are set correctly.
📘  Documentation: https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/

bharat@Bharat-Desktop:~$
[3:13 PM, 12/3/2020] Gangs: this is message I am getting when trying to start minikube without internet connection.

**Comment by afbjorklund** [comment]
If you want to use the docker driver, you need to cache the base-image as well. (`gcr.io/k8s-minikube/kicbase`)
When using the vm drivers, it needs the minikube.iso cached. The k8s images _should_ have been cached though.

Probably this needs a better regression test, it is supposed to be downloaded by `minikube start --download-only`
But currently the base image for the docker driver (or the podman driver) is **not** stored within ~/.minikube/cache.

See #7766

**Comment by afbjorklund** [comment]
Fixed in PR #10918 (for #10912)
