### ISSUE TITLE
不是吧不是吧，现在最新支持的版本才15 ？？

### ISSUE THREAD

**Issue by biubiulu** [kubernetes/minikube#9848]
**重现问题所需的命令**：

**失败的命令的完整输出**：<details>
官方不是都更新到了19了嘛，麻烦把在洗手间打王者荣耀的开发拉出来让他把19的写出来哈哈。开个玩笑，你们辛苦啦

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：                                                                                                  祝好

**Comment by lingsamuel** [comment]
/close 
Not a issue
