### ISSUE TITLE
Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.4

### ISSUE THREAD

**Issue by pribalaji58** [kubernetes/minikube#9860]
**Steps to reproduce the issue:** 

1.* Preparing Kubernetes v1.19.4 on Docker 19.03.13 ...
! Unable to restart cluster, will reset it: apiserver health: controlPlane never updated to v1.19.4
* Verifying Kubernetes components...
! Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
* Enabled addons: storage-provisioner, dashboard

X Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.4
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

PS C:\Users\HP>
PS C:\Users\HP> ssh docker
ssh: Could not resolve hostname docker: No such host is known.
PS C:\Users\HP>
PS C:\Users\HP>
PS C:\Users\HP>
PS C:\Users\HP>
PS C:\Users\HP>
PS C:\Users\HP>
PS C:\Users\HP>
PS C:\Users\HP>
PS C:\Users\HP>
PS C:\Users\HP> ssh docker@192.168.99.200
ssh: connect to host 192.168.99.200 port 22: Connection timed out
PS C:\Users\HP> kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:13:54Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"windows/amd64"}
error: You must be logged in to the server (the server has asked for the client to provide credentials)
PS C:\Users\HP> kubectl get version
error: You must be logged in to the server (Unauthorized)
PS C:\Users\HP>

2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by pribalaji58** [comment]
Hi 

I received below error

1.The exact minikube start command line used

C:\WINDOWS\system32>minikube start
* minikube v1.15.1 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Updating the running virtualbox "minikube" VM ...
* Preparing Kubernetes v1.19.4 on Docker 19.03.13 ...
! Unable to restart cluster, will reset it: apiserver health: controlPlane never updated to v1.19.4
* Verifying Kubernetes components...
! Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
* Enabled addons: storage-provisioner, dashboard

X Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.4
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose


C:\WINDOWS\system32>



The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

W1212 00:42:21.791370    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:22.291599    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:22.790174    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:23.290611    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:23.793486    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:24.294628    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:24.801651    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:25.294315    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:25.792367    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:26.295316    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:26.798321    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:27.296814    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:27.792940    2096 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials
W1212 00:42:28.291522    2096 api_server.go:117] api server version match failed: server ve


C:\WINDOWS\system32>minikube logs
* ==> Docker <==
* -- Logs begin at Fri 2020-12-11 17:11:46 UTC, end at Fri 2020-12-11 19:13:17 UTC. --
* Dec 11 19:04:43 minikube dockerd[2449]: time="2020-12-11T19:04:43.090885917Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
* Dec 11 19:04:43 minikube dockerd[2456]: time="2020-12-11T19:04:43.118073639Z" level=info msg="shim containerd-shim started" address=/containerd-shim/37bdbab975244ff8c08faf9e94721fffb655ccc9260d48bf3a50c328d84ba15e.sock debug=false pid=35827
* Dec 11 19:04:43 minikube dockerd[2456]: time="2020-12-11T19:04:43.198964854Z" level=info msg="shim containerd-shim started" address=/containerd-shim/98de634ff8db9cd02aecd6d029bce79e3c328b6e4f11a393f36351ec86282ee7.sock debug=false pid=35836
* Dec 11 19:04:43 minikube dockerd[2456]: time="2020-12-11T19:04:43.434084079Z" level=info msg="shim reaped" id=e859d84283dc3f545eb6d0cdeacdfe881807fff964e4351d0bcd78a6c9801153
* Dec 11 19:04:43 minikube dockerd[2449]: time="2020-12-11T19:04:43.440419728Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
* Dec 11 19:04:43 minikube dockerd[2456]: time="2020-12-11T19:04:43.770825554Z" level=info msg="shim reaped" id=cf324da64a52f4fe4511adf273ef669fed25a78b9c6479beddbff79d0df84c2c
* Dec 11 19:04:43 minikube dockerd[2449]: time="2020-12-11T19:04:43.784144512Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
* Dec 11 19:04:43 minikube dockerd[2456]: time="2020-12-11T19:04:43.918244251Z" level=info msg="shim reaped" id=2067acad3025d28298c6eb55715db6271e056f0953f55f158d8a7a3cc999ace2
* Dec 11 19:04:43 minikube dockerd[2449]: time="2020-12-11T19:04:43.931518889Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
* Dec 11 19:04:46 minikube dockerd[2456]: time="2020-12-11T19:04:46.492312326Z" level=info msg="shim containerd-shim started" address=/containerd-shim/5ba4133c011b4fe895edc9d27d9020aa6d7dd578fb162f0ab08cc44d52efa8e7.sock debug=false pid=36053
* Dec 11 19:04:47 minikube dockerd[2456]: time="2020-12-11T19:04:47.950524553Z" level=info msg="shim containerd-shim started" address=/containerd-shim/3cabcecdc5da83d36821c5317e4736bd0beb95c59cd17da9473baffdbab5f46e.sock debug=false pid=36093
* Dec 11 19:04:49 minikube dockerd[2456]: time="2020-12-11T19:04:49.256971129Z" level=info msg="shim containerd-shim started" address=/containerd-shim/5ad7de480eef18e6ff84ebe8cb39409a820a67b96d7098bc364b324d14a84174.sock debug=false pid=36131
* Dec 11 19:04:49 minikube dockerd[2456]: time="2020-12-11T19:04:49.671951000Z" level=info msg="shim containerd-shim started" address=/containerd-shim/d78350141995e486bf6c45604caf0e1ec3f0726ff290114d5b560dc375e08672.sock debug=false pid=36155
* Dec 11 19:04:50 minikube dockerd[2456]: time="2020-12-11T19:04:50.154058920Z" level=info msg="shim containerd-shim started" address=/containerd-shim/f51aa66a4e14375cb7bbfa06d185c4455ecd68b89191afa5ac6bedf5599d8dde.sock debug=false pid=36192
* Dec 11 19:11:08 minikube dockerd[2456]: time="2020-12-11T19:11:08.386161736Z" level=info msg="shim reaped" id=516298924d62373f32b45698ee75f32834e8cae9bdf8c23d2fff504549a787d0
* Dec 11 19:11:08 minikube dockerd[2449]: time="2020-12-11T19:11:08.402367945Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
* Dec 11 19:11:08 minikube dockerd[2456]: time="2020-12-11T19:11:08.550075481Z" level=info msg="shim reaped" id=2f839f4f4c7414ccb94e358fd8f519c9efa0b2572401c17e76ad7edd13cce6c9
* Dec 11 19:11:08 minikube dockerd[2449]: time="2020-12-11T19:11:08.570701178Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
* Dec 11 19:11:08 minikube dockerd[2456]: time="2020-12-11T19:11:08.589919020Z" level=info msg="shim reaped" id=bc6ab89b31753fcfdf13afd85d182abb4248bd52441e0e21570b69e5272a288c
* Dec 11 19:11:08 minikube dockerd[2449]: time="2020-12-11T19:11:08.596145783Z" level=info msg="ignoring event" module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
* Dec 11 19:11:08 minikube dockerd[2456]: time="2020-12-11T19:11:08.650733244Z" level=info msg="sh



[minikube_case.txt](https://github.com/kubernetes/minikube/files/5681168/minikube_case.txt)

I have also attached the logs could you please check and help to build a kubernets cluster on minikube

**Comment by pribalaji58** [comment]
[start.txt](https://github.com/kubernetes/minikube/files/5681338/start.txt)
[logs.txt](https://github.com/kubernetes/minikube/files/5681339/logs.txt)

Hi again,

I attached minikube logs and minikube  start output

**Comment by nathanjisaac** [comment]
@pribalaji58 I ran into this issue on Mac OS and running these commands worked for me. Not sure if it will work on Windows though. 

https://github.com/kubernetes/minikube/issues/9070#issuecomment-679314271

**Comment by medyagh** [comment]
@pribalaji58 do u still have this issue ? do u mind sharing the full logs ? "--alsologtostderr"

```
minhikube start --alsologtostderr
```

**Comment by medyagh** [comment]
@pribalaji58 Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. If you can provide any additional details, such as:

The exact minikube start command line used: preferably with --alsologtostderr -v=8 added.
The full output of the command
The full output of "minikube logs"
Please feel free to do so at any point. Thank you for sharing your experience!
