### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by assassin5615** [kubernetes/minikube#9864]
the Installation section is empty.

  
![image](https://user-images.githubusercontent.com/18673892/101245832-9a412400-374a-11eb-967b-a0a77b31bd9a.png)

**Comment by lingsamuel** [comment]
![image](https://user-images.githubusercontent.com/14567045/101320749-3aa85d00-389f-11eb-9e5e-523c4b0b4ad2.png)

Have you enabled JS?

**Comment by afbjorklund** [comment]
Same as #9835

**Comment by lingsamuel** [comment]
> Same as #9835

Disable JS can repro too. Maybe a bad connection cause the scripts not loaded.

**Comment by assassin5615** [comment]
@lingsamuel thanks for checking, javascript is always enabled. I think I've found the reason with your hints.

 I had problem downloading the javascript while opening the page. I can see those tabs after using a VPN.  I guess that people visiting the page from China  are likely to run into the issue.
