### ISSUE TITLE
Consider using CRI for docker runtime

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#9868]
Just like the "dockershim" in Kubernetes, the cruntime uses direct commands for Docker.

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cruntime/docker.go

It would be nice if it would use the CRI (where possible), like the _other_ runtimes are doing.

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/cruntime/cri.go

We do have the `crictl` all configured, so just a matter of "flipping a switch" basically.

The initial approach might be to introduce a feature toggle, to make it opt-in to start with...

**Comment by afbjorklund** [comment]
Once docker also uses it, we could consider making CRI mandatory like we did with CNI.

**Comment by afbjorklund** [comment]
There is now: https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/

The initial prototype is at https://github.com/dims/cri-dockerd, it should be ready before kubernetes 1.23...

**Comment by afbjorklund** [comment]
We don't _call_ the CRI functions yet (like populateCRIConfig), so we don't get a crictl.yaml for instance:

`image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock]. As the default settings are now deprecated, you should set the endpoint instead. `

**Comment by medyagh** [comment]
I belive we merged a PR on this

**Comment by afbjorklund** [comment]
> I belive we merged a PR on this

Just for setting dockershim in /etc/crictl.yaml, though ? (to avoid a warning). Not for starting to use a CRI for docker ?

**Comment by afbjorklund** [comment]
Using  https://github.com/dims/cri-dockerd until https://github.com/Mirantis/cri-dockerd has more than just a README...

See https://github.com/Mirantis/cri-dockerd/issues/1 and https://www.mirantis.com/blog/mirantis-to-take-over-support-of-kubernetes-dockershim-2/
