### ISSUE TITLE
vbox on v1.12.3:  minikube is unable to connect to the VM: dial tcp 172.17.0.1:22: i/o timeout

### ISSUE THREAD

**Issue by sravano9** [kubernetes/minikube#9872]
**Steps to reproduce the issue:** 

1.
2. minikube start
😄  minikube v1.12.3 on Ubuntu 18.04
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running virtualbox "minikube" VM ...
❌  minikube is unable to connect to the VM: dial tcp 172.17.0.1:22: i/o timeout

	This is likely due to one of two reasons:

	- VPN or firewall interference
	- virtualbox network configuration issue

	Suggested workarounds:

	- Disable your local VPN or firewall software
	- Configure your local VPN or firewall to allow access to 172.17.0.1
	- Restart or reinstall virtualbox
	- Use an alternative --vm-driver
	- Use --force to override this connectivity check
	

💣  error provisioning host: Failed to validate network: dial tcp 172.17.0.1:22: i/o timeout

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

Please help me on this ASAP.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment]
As best as I can tell, this is a VirtualBox and/or firewall issue. 

My suggestion is to run `minikube delete` and upgrade to the most recent version of minikube. If it still has an issue, add the output of `minikube start --alsologtostderr -v=1`.

**Comment by sharifelgamal** [comment]
@sravano9 I'm going to go ahead and close this issue for now, please re-open it if you try the suggestions above (and upgrade to minikube 1.16) and it still doesn't work.
