### ISSUE TITLE
Kubernetes v1.20?

### ISSUE THREAD

**Issue by bl-ue** [kubernetes/minikube#9885]
[Kubernetes v1.20.0](https://github.com/kubernetes/kubernetes/releases/tag/v1.20.0) was released.  When will minikube support it?

**Comment by afbjorklund** [comment]
`minikube start --kubernetes-version=v1.20.0` (or: minikube 1.16.0)

**Comment by bl-ue** [comment]
Thank you @afbjorklund!  That worked.
