### ISSUE TITLE
kubelet stopped working

### ISSUE THREAD

**Issue by BenAji** [kubernetes/minikube#9892]
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by BenAji** [comment]
Kill your antivirus firewall
`minikube stop`
and then `minikube start`

**Comment by tstromberg** [comment]
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Comment by BenAji** [comment]
I experienced the same issue,
when I issued a command on my PowerShell 
`minikube status` : I got the message that kubelet stopped while the other components are running. So I paused my fire wall, then I did `minikube stop` After sometime, I did `minikube start` and all components came back running . No much technical thing . You must also make sure the dockers is running.

**Comment by tstromberg** [comment]
Thanks. Please let me know if the problem comes up again.
