### ISSUE TITLE
Documentation - mount - do mounts persist?

### ISSUE THREAD

**Issue by calebstewart** [kubernetes/minikube#9906]
This is related to the documentation for minikube. I'm trying to figure out if mounts persist across `minikube start/stop`. I'm automating the startup of a collection of deployments, and they need a local directory to be mounted. I understand that the `minikube mount` command accomplishes this. I can't find any documentation on *removing* mount points or on what happens to the mount points when you `minikube stop`. I'd like to return the minikube state back to the same as it was prior to executing this script, so I just need to know either:

1. Do mount points disappear after you shutdown minikube (and not come back when you start again)
2. Or, is there a way to remove a mount point after you add one?

**Comment by calebstewart** [comment]
Also, related, is there a way to list current mount points?

**Comment by calebstewart** [comment]
Oh, I realize now what is happening based on the output after running `minikube mount`. It might be helpful for future users to note in the documentation that this mount is not persistent and requires that the `minikube mount` command continue running in the background.

**Comment by Aut0R3V** [comment]
Sure this issue sounds reasonable. Can any of the members give their views for this?

**Comment by tstromberg** [comment]
I'd be all for updating the documentation to clarify the behavior.

**Comment by Aut0R3V** [comment]
Sure okay. If I can help in any ways, then please tell

**Comment by BLasan** [comment]
@calebstewart This would help you.
[PV](https://minikube.sigs.k8s.io/docs/handbook/persistent_volumes/#:~:text=minikube%20is%20configured%20to%20persist,from%20other%20directories%20on%20reboots.&text=You%20can%20also%20achieve%20persistence,in%20a%20mounted%20host%20folder) in minikube
Also I think you can do `minikube ssh` and run `sudo rm -rf <volume_dir>` to remove it manually

**Comment by calebstewart** [comment]
For clarity/historical sake, the mounts only persist as long as `minikube mount` is running. Stopping that process will remove the mount. There's no need to remove it through any API. I solved my problem by simply running a subprocess for the mount, and kill it when I was done. No mess; no fuss. Admittedly, I haven't checked to see if this was added explicitly to documentation anywhere, but it's relatively obvious once you actually run the command.

If someone thinks this still needs to be tracked, feel free to re-open it, but I don't need the issue anymore personally.

/close
