### ISSUE TITLE
Provide more descriptive error codes for GUEST_PROVISIONG

### ISSUE THREAD

**Issue by go-nelango** [kubernetes/minikube#9907]
GUEST_PROVISION comprises 8.5% of minikube start errors in our environment.

These could be because minikube failed to obtain driver options/ generate cluster config/ cache minikube ISO. 

Can minikube provide more descriptive error codes for their scenarios? It would also help to make the error messages actionable wherever possible.

**Comment by tstromberg** [comment]
As a catchall error code, In order to break this code down further, we'll need to collect example error messages for known issues. We can then add support for them here:

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/reason/known_issues.go

**Comment by tstromberg** [comment]
Here's the best advice I have for collecting this info:

https://github.com/kubernetes/minikube/issues?q=is%3Aissue+GUEST_PROVISION

Looks like we have 21 examples currently that can get broken down to more specific exit codes.

**Comment by tstromberg** [comment]
I noticed at least one bug here in #10151 - it should have raised PR_DOCKER_NO_SSH instead of GUEST_PROVISION. This makes me wonder if there is a bug that is causing known_issues to not be parsed.

**Comment by medyagh** [comment]
@azhao155 has too many tasks this milestone, I unassign it for now if anyone wants to pick it up

**Comment by spowelljr** [comment]
In-progress
