### ISSUE TITLE
Create a webpage that provides descriptions for minikube error codes

### ISSUE THREAD

**Issue by nelango** [kubernetes/minikube#9910]
Create a webpage that provides descriptions for minikube error codes (as well as tips and advice for corrective actions) that users can refer to.

**Comment by spowelljr** [comment]
Good request!

/priority important-soon

**Comment by spowelljr** [comment]
/"help wanted"

**Comment by tstromberg** [comment]
This will need to be autogenerated, or point to the code, as otherwise it will become stale technical debt very quickly.

**Comment by medyagh** [comment]
@sharifelgamal is working on auto generating the docs for integration tests, this could be something simmilar to that

**Comment by medyagh** [comment]
this is the place that should be loking at https://github.com/medyagh/minikube/blob/81d144f765a832f6d19a114d273eb6607e4d1a52/pkg/minikube/reason/exitcodes.go#L60
