### ISSUE TITLE
Remove verbose log `-v`  in commands like tar

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes/minikube#9916]
When I am developing multi control plane feature, I need to view kubeadm and other commands output so I made a change like this:
```go
func (s *SSHRunner) RunCmd(cmd *exec.Cmd) (*RunResult, error) {
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
```
Then I found some commands like `tar` uses a `-v` option, produces a massive log which is useless:
```go
r.Runner.RunCmd(exec.Command("sudo", "tar", "-I", "lz4", "-C", "/var", "-xvf", dest));
```

Could we just remove these verbose options?

/kind cleanup

**Comment by afbjorklund** [comment]
This mostly affects the preloaded tarball, but agree - it is annoying
