### ISSUE TITLE
Starting minikube requires sudo due to error with certs copy

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#9919]
Something changed in `copyHostCerts`, that runs locally instead of on the remote ?

`sudo cp -a /tmp/minikube123456789 ~/.minikube/ca.pem`

This fails, and is of course wrong to start with. It should not have needed `sudo`...

Using the virtualbox driver, other commands ran properly.

**Comment by afbjorklund** [comment]
Bug introduced in 4da751f5d78d43ae4fafa0e8dcfe396bc6127e07 by adding "sudo" to copy commands...

**Comment by afbjorklund** [comment]
This should have failed in regression test, we need a worker without sudo...

**Comment by medyagh** [comment]
you are right thanks for finding this out
