### ISSUE TITLE
add multinode integration test two pods should get two different ips on different nodes

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9925]
add a subtest

deploy an app with more than 1 replica on multi node
their pods ips should be different

https://github.com/medyagh/minikube/blob/fc10bca4aec2bf7b53357ad93729643db519fd64/test/integration/multinode_test.go#L29

**Comment by sadlil** [comment]
As long as we are deploying an app, can we also add one more step to this test - exec into the pods and check if they are resolving both in-cluster and external dns.

**Comment by BenTheElder** [comment]
/remove-sig testing
/sig cluster-lifecycle
[SIG Testing](https://github.com/kubernetes/community/blob/master/sig-testing/README.md) does not own this. SIG cluster lifecylce projects own their own tests, we own things like prow, the upstream e2e test framework, etc.

**Comment by medyagh** [comment]
oops wrong label, thank you @BenTheElder !

**Comment by hetong07** [comment]
> As long as we are deploying an app, can we also add one more step to this test - exec into the pods and check if they are resolving both in-cluster and external dns.

Hello Sadlil, Could you help give me more detail about the DNS resolve thing you are suggesting? Thank you.

**Comment by hetong07** [comment]
Have a demo changes here, https://github.com/hetong07/minikube/tree/multinode-test

**Comment by sadlil** [comment]
@hetong07 Sure, What i meant is to try doing a curl to https://google.com and to any in-cluster service url to see if the dns are resolving from the worker nodes.
