### ISSUE TITLE
upload jenkins raw logs Per commit

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9927]
our txt file is uploaded at
https://storage.googleapis.com/minikube-builds/logs/9924/Docker_Linux.txt
but out html is uploaded per commmit
https://storage.googleapis.com/minikube-builds/logs/9924/0a5ef42/Docker_Linuxout.txt
I like our Text to be uploaded per commit
that is in the Jenkins Plugin

**Comment by sharifelgamal** [comment]
This is done.
