### ISSUE TITLE
buildroot based image doesn't mount persistent disk at `/data`

### ISSUE THREAD

**Issue by sykesm** [kubernetes/minikube#993]
**Minikube version** (use `minikube version`): `minikube version: v0.15.0`

**Environment**:
- **OS** (e.g. from /etc/os-release): MacOS Sierra
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **Docker version** (e.g. `docker -v`): `Docker version 1.11.1, build 5604cbe`

**What happened**:
In minikube v0.14.0, the persistent disk allocated at start would be mounted at `/data` as documented in the [README](https://github.com/kubernetes/minikube#persistent-volumes). It appears that this is no longer true with the buildroot based iso in v0.15.0. Any configurations that attempt to use the example `PersistentVolume` configuration will quickly run out of disk space.

**What you expected to happen**:
The persistent disk is available at `/data` instead of (or in addition to) `/mnt/sda1`.

**How to reproduce it** (as minimally and precisely as possible):
Start minikube, run `minikube ssh ls /data` and observe the `No such file or directory` error.

**Anything else do we need to know**:
The disk is allocated and mounted at `/dev/sda1` but it's not available (via bind mount or otherwise) at `/data`.

**Comment by sykesm** [comment]
It appears `/data` was created as symlink to `/mnt/$PARTNAME/data` when [bootlocal.sh] ran in the `boot2docker` based images.

[bootlocal.sh]: https://github.com/kubernetes/minikube/blob/master/deploy/iso/boot2docker/bootlocal.sh

**Comment by r2d4** [comment]
Hey sorry about that.  Looks like that got left out when building the new ISO.  I've added a PR that brings it back.  As a workaround until its merged, you can patch `/usr/sbin/minikube-automount` in the minikube VM (through `minikube ssh`) with those two lines (making the directory on `/mnt/sda1` and linking it.)

**Comment by sykesm** [comment]
No worries. Already addressed on my end. Thanks for the quick fix.
