### ISSUE TITLE
minikube scp

### ISSUE THREAD

**Issue by bl-ue** [kubernetes/minikube#9930]
It would be nice to be able to have `minikube scp` like `minikube ssh`, to copy files in the the minikube node.  An use case would be: copying Dockerfiles to the node to build custom docker images for Kubernetes.

In the meantime, for all of you that want this feature, here's a workaround:
```
scp -i $(minikube ssh-key) <file> docker@$(minikube ip):
```

**edit:** you can also use `minikube docker-env` to set up the `docker` client to point to minikube's docker daemon, and build the image locally.  However, this still doesn't work for *copying* files...

**Comment by afbjorklund** [comment]
This feature is available in docker-machine, so we should probably make it available in minikube as well.

https://docs.docker.com/machine/reference/scp/

**Comment by afbjorklund** [comment]
The turbo-charged version also has support for `rsync`, for delta transfer and other advanced uses.

**Comment by arjunagl** [comment]
I would like to work on this if there is no objection.

**Comment by afbjorklund** [comment]
Sure, please do a PR.

The original code is in: https://github.com/docker/machine/blob/master/commands/scp.go

But minikube is different...

It would be OK to call out to the external programs for "scp" and for "rsync", at least initially.

**Comment by tstromberg** [comment]
I too would love to see this get implemented.

**Comment by anencore94** [comment]
Is there any progress on this issue? @arjunagl
If you are unavailable to take this issue because of other schedule, I would love to take this!

**Comment by arjunagl** [comment]
@anencore94 please go ahead.  I got a bit stuck with some other stuff.

**Comment by anencore94** [comment]
Thanks for your answer @arjunagl :)
/assign

**Comment by bl-ue** [comment]
🎊 🎉 🚀
