### ISSUE TITLE
minikube 1.7.3 start cmd error 

### ISSUE THREAD

**Issue by lintingyong** [kubernetes/minikube#9944]
**重现问题所需的命令**：
./minikube start --vm-driver=docker --image-mirror-country=cn --image-repository=registry.cn-hangzhou.aliyuncs.com/google_containers

**失败的命令的完整输出**：<details>
😄  minikube v1.7.3 on Darwin 10.15.7
✨  Using the docker (experimental) driver based on user configuration
✅  Using image repository registry.cn-hangzhou.aliyuncs.com/google_containers
⌛  Reconfiguring existing host ...
🙄  machine 'minikube' does not exist. Proceeding ahead with recreating VM.
🔥  Creating Kubernetes in docker container with (CPUs=2), Memory=2000MB (16384MB available) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: Error recreating VM: creating host: create: creating: create kic node: create a kic node: args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --volume minikube:/var --cpus=2 --memory=2000mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.5@sha256:3ddd8461dfb5c3e452ccc44d87750b87a574ec23fc425da67dccc1f0c57d428a]  output: [Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.5@sha256:3ddd8461dfb5c3e452ccc44d87750b87a574ec23fc425da67dccc1f0c57d428a' locally docker: Error response from daemon: Get https://gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers). See 'docker run --help'.] : exit status 125

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>

</details>

**使用的操作系统版本**：
Darwin oneminuters-MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

**Comment by medyagh** [comment]
我注意到您的minikube版本太旧了，我不知道您是否对最新版本和Docker驱动程序有同样的疑问？

如果您安装docker您可以尝试

minikube delete
minikube start --driver docker

**Comment by sharifelgamal** [comment]
@lintingyong, 
您是否有幸升级到minikube的最新版本1.17.0？

**Comment by medyagh** [comment]
Hi @lintingyong , I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.
