### ISSUE TITLE
Move machine and drivers to minikube repositories

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#9952]
We don't know how long the docker/machine and machine-drivers organization will stay active.

Both docker/machine and boot2docker/boot2docker are deprecated and dead since 2019.

So there is no release for Docker 20.10 and later releases, and eventually they might disappear.

We need to maintain our own fork of the git repos, until it can be integrated more into minikube.

This affect the current repositories:

- [ ] **github.com/docker/machine** -->
    github.com/machine-drivers/machine

- [x] **github.com/boot2docker/boot2docker** -->
    ~~github.com/machine-drivers/boot2docker~~

- [x] github.com/dhiltgen/docker-machine-kvm -->
    ~~github.com/machine-drivers/docker-machine-kvm~~
    ~~github.com/machine-drivers/docker-machine-driver-libvirt~~

- [x] ~~github.com/machine-drivers/docker-machine-driver-hyperkit~~

- [ ] ~~github.com/docker/machine/drivers/vmwarefusion~~
    **github.com/machine-drivers/docker-machine-driver-vmware**

- [ ] github.com/Parallels/docker-machine-parallels -->
    **github.com/machine-drivers/docker-machine-parallels**

See also #9805 about different architectures

We are currently in the process of converting all the drivers to (incompatible) minikube versions.
So far we have done the "kvm" and the "none" drivers, and are about to do the "generic" driver.
We also have patches to the "hyperv" and "hyperkit" drivers, so they are not identical either...
At some point, we need to stop naming the binaries as `docker-machine-driver` whatsoever.

We should break out the kvm and hyperkit drivers from the "minikube" source code repository,
and set them up with build infrastructure like these other two external (not compiled in) drivers.
Currently they are making the Makefile and other files for minikube needlessly complicated,
since they need to be cross-compiled and add dependencies to native libraries and so on.

See #9583

----

Internal drivers:
* virtualbox
* hyperv
* none (local)
* generic (remote)

External drivers:
* kvm
* hyperkit
* vmware
* parallels

Note that docker and podman are not (real) libmachine drivers.

All minikube driver names are hardcoded into the main binary.

**Comment by afbjorklund** [comment]
Since we download the drivers ourselves now, users don't actually need to notice much.

**Comment by afbjorklund** [comment]
We probably need a separate github organization for this, just for minikube ?

Could also be used to gather some of the personal repositories currently used.

**Comment by medyagh** [comment]
I am okay with moving it to minikube, it would be less complicated release and code review

**Comment by seguins** [comment]
I'm not sure to fully understand the target.
Is the target to : 
- move / duplicate all drivers in the repo
- move / duplicate all drivers in the `machine-drivers` organization
- move / duplicate all drivers in a new repo or organization

Can you provide an update about this issue ?

**Comment by afbjorklund** [comment]
Current patches for the "virtualbox" driver:

```
* 154c4e8d drivers/virtualbox: Follow symlinks on FreeBSD
* 3a0d9357 Fix broken IsVTXDisabled detection on AMD CPU
```

Current patches for the "hyperv" driver:

```
* 6bdd70a8 check resp length as well
* 37dc244c don't panic if hyper-v isn't enabled
* fa999bcf Added selection of default VSwitch to config
* af52a576 Fix HyperV Administrator check
* 21bd2f51 Use switch ID to match default switch
* 2438fc95 Hyper-V: Use Default Switch vSwitch by default
* 6f34be40 Allow localized names for Virtual Switch
```

The "none" driver has been forked, to the "none" driver.
The "generic" driver has been forked, to the "ssh" driver.

**Comment by afbjorklund** [comment]
Done, https://github.com/minikube-machine
