### ISSUE TITLE
Unable to run minikube successfully, appear to fail at container inspect 

### ISSUE THREAD

**Issue by mikemil** [kubernetes/minikube#9953]
**Steps to reproduce the issue:** 

1.  ran the install using curl on my mac
2. minikube --alsologtostderr start

**Full output of failed command:** 
[err.txt](https://github.com/kubernetes/minikube/files/5686327/err.txt)

**Comment by afbjorklund** [comment]
Your docker version is really really old (17.06.0), can you upgrade and try again with something newer ?

**Comment by afbjorklund** [comment]
We should check this, and issue a warning: #9077

**Comment by mikemil** [comment]
Installed docker 3.0 and it worked!
