### ISSUE TITLE
the installation part of the web doc is missing

### ISSUE THREAD

**Issue by praisethejack** [kubernetes/minikube#9956]
The installation portion of the web page documentation(https://minikube.sigs.k8s.io/docs/start/) is missing.
This confused me
Am I looking in the wrong place, or is there something really wrong?

**Comment by afbjorklund** [comment]
Duplicate of #9835 (unfortunately)

**Comment by tstromberg** [comment]
@praisethejack - I'm not sure what browser you are on - but could you please open up the browser's "Web Developer" console, reload the page, and cut and paste any errors you see here? Thanks!
