### ISSUE TITLE
Minikube on windows using docker has issues running the tunnel

### ISSUE THREAD

**Issue by mashanivas** [kubernetes/minikube#9971]
**Steps to reproduce the issue:** 

1. created a service to expose the app. using minikube service command.
2.  minikube opened the ports to the desired one.
3. After the port opened, now getting the password prompt and not sure where to get the password for this.

docker@127.0.0.1's password: |-----------|-----------------------|-------------|-----------------------|
| NAMESPACE |         NAME          | TARGET PORT |          URL          |
|-----------|-----------------------|-------------|-----------------------|
| default   | mongo-express-service |             | http://127.0.0.1:3772 |
|-----------|-----------------------|-------------|-----------------------|
🎉  Opening service default/mongo-express-service in default browser...
❗  Because you are using a Docker driver on windows, the terminal needs to be open to run it.

docker@127.0.0.1's password:
docker@127.0.0.1's password:
✋  Stopping tunnel for service mongo-express-service.

❌  Exiting due to SVC_TUNNEL_STOP: stopping ssh tunnel: invalid argument

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by medyagh** [comment]
@mashanivas that is the same password as your windows admin password,
unfortunately the tunnell on windows needs administration 

you can also do is, open your powershell in adminstrative mode

**Comment by pambhullar** [comment]
**@mashanivas** Try wiping out your local minikube cluster and restarting it back again.
Use the following commands to do so:
1) minikube delete and then 
2) minikube start 
This will wipe out the environment and reset it to a blank slate.

**Comment by medyagh** [comment]
@mashanivas are u still having this issue ?

**Comment by spowelljr** [comment]
Hi @mashanivas, we haven't heard back from you, do you still have this issue?
There isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.

I will close this issue for now but feel free to reopen when you feel ready to provide more information.

**Comment by zzashpaupat** [comment]
I have the same issue running on Mac

**Comment by drewhagen** [comment]
I'm running into this issue as well, and my Windows admin password did not work.

I'm running on WSL, and my ubuntu password didn't work either.

**Comment by Style5000** [comment]
Same issue, did you fix it?

**Comment by supersjgk** [comment]
@Style5000 @drewhagen @jamesl1mbabol @zzashpaupat 
This worked for me on windows:

```
$ minikube ssh
docker@minikube:~$ sudo su -
root@minikube:~# passwd docker
New password:                                       # set a password
Retype new password:

root@minikube:~# logout
docker@minikube:~$ logout

$ minikube tunnel
docker@127.0.0.1's password:                       # enter the password you set earlier here. It will work
```
