### ISSUE TITLE
minikube start: kubectl info: exec: exit status 2

### ISSUE THREAD

**Issue by bl-ue** [kubernetes/minikube#9976]
**Steps to reproduce the issue:** 

1. `minikube start --vm=true --kubernetes-version='v1.20.0'`

**Full output of failed command:** 
```
$ minikube start --vm=true --kubernetes-version='v1.20.0'
😄  minikube v1.15.1 on Darwin 11.1
✨  Automatically selected the hyperkit driver. Other choices: vmware, vmwarefusion
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.0 on Docker 19.03.13 ...
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
E1216 11:24:31.467901   25710 start.go:266] kubectl info: exec: exit status 2
$
```
`--alsologtostderr` didn't help clarify this error.  Last few lines of run with `--alsologtostderr`:
```
I1216 11:28:23.304254   25968 start.go:203] waiting for startup goroutines ...
I1216 11:28:23.408164   25968 out.go:110] 🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
E1216 11:28:23.408190   25968 start.go:266] kubectl info: exec: exit status 2
$
```
If neccessary I can attach the full log with `--alsologtostderr`.

**Optional: Full output of `minikube logs` command:**
[logs.zip](https://github.com/kubernetes/minikube/files/5704022/logs.zip)

**Comment by bl-ue** [comment]
The log line is:
https://github.com/kubernetes/minikube/blob/fdab252f4f1d3aaeea028f90a2153cb1da8e54cb/cmd/minikube/cmd/start.go#L271

minikube is trying to exec `/usr/local/bin/kubectl version --client --output=json`, but getting error 2 aka "No such file or directory".

`kubectl` is linked to minikube i.e.
```
lrwxr-xr-x 1 me admin 23 Dec 13 09:10 /usr/local/bin/kubectl -> /usr/local/bin/minikube*
```

**Comment by bl-ue** [comment]
Installing the Homebrew formula `kubernetes-cli` which provides `kubectl` binary and replacing the link with the actual binary fixes the issue.

**Comment by afbjorklund** [comment]
It  is supposed to be possible to run "minikube kubectl" using a symlink like that.

Looks like something went wrong, when calling the actual `kubectl` binary ?

Try something like:

`minikube --alsologtostderr kubectl version`

It should have more info.

Like `using` and `Running`

**Comment by afbjorklund** [comment]
The command (from start) works OK on linux:

```
$ kubectl version --client --output=json
{
  "clientVersion": {
    "major": "1",
    "minor": "20",
    "gitVersion": "v1.20.0",
    "gitCommit": "af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38",
    "gitTreeState": "clean",
    "buildDate": "2020-12-08T17:59:43Z",
    "goVersion": "go1.15.5",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
```

Alternative invocation (without symlink):

`minikube kubectl -- version --client --output=json`

It should not return "exit status 2"

**Comment by bl-ue** [comment]
@afbjorklund Relevent logs from `minikube --alsologtostderr kubectl version` (can add more):
```
I1217 14:17:55.964853   62803 binary.go:56] Not caching binary, using https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/darwin/amd64/kubectl?checksum=file:https://storage.googleapis.com/kubernetes-release/release/v1.20.0/bin/darwin/amd64/kubectl.sha256
I1217 14:17:55.964885   62803 kubectl.go:51] Running /Users/me/.minikube/cache/darwin/v1.20.0/kubectl [version]
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by afbjorklund** [comment]
Hmm, that command looks happy enough. How did we end up with the error ?

`kubectl info: exec: exit status 2`

**Comment by bl-ue** [comment]
The following simple program works, with `./symlink` linking to `/usr/local/bin/minikube`:
```go
package main

import (
	"fmt"
	"os/exec"
)

func main() {
	out, err := exec.Command("./symlink").Output()
	if err != nil {
		fmt.Printf("%v", err)
		return
	}
	fmt.Printf(string(out))
}
```
Let me investigate.

**Comment by ilya-zuyev** [comment]
Hi @bl-ue! Any update on this issue?

**Comment by bl-ue** [comment]
Oh! I forgot about this one.  Let me see...

**Comment by medyagh** [comment]
Hi @bl-ue c, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Comment by bl-ue** [comment]
Hi @medyagh! Yes, I'm still having the issue and it's still repeatable using the steps given above.  I haven't had much time lately to investigate, and I also wouldn't consider myself a Go expert&mdash;therefore I haven't been able to take care of it.

**Comment by bl-ue** [comment]
>I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

I can't reopen this issue, because once a collaborator closes it, the OP can't reopen it 😕

**Comment by bl-ue** [comment]
FYI&mdash;it's not imparing usablity in the slightest bit; but the I opened an issue about it because it's a defect in the product, but a slight, hidden defect that's not likely to be noticed.

**Comment by prezha** [comment]
/reopen
@bl-ue we can reopen if you have time to continue working on this issue with us - thanks!

can you please confirm (https://github.com/kubernetes/minikube/issues/9976#issuecomment-746745737):
```
kubectl is linked to minikube i.e.
lrwxr-xr-x 1 me admin 23 Dec 13 09:10 /usr/local/bin/kubectl -> /usr/local/bin/minikube*
```
this does not look right

also (https://github.com/kubernetes/minikube/issues/9976#issuecomment-747645797):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:51:19Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
it seems that you have kubectl for two different platforms: `darwin/amd64` and `linux/amd64` - probably one is not good

**Comment by bl-ue** [comment]
Okay @prezha I'll take a look. 👍🏻

**Comment by afbjorklund** [comment]
It's **not** possible to reproduce this issue on linux, but it would be nice to re-visit after fixing #9593

There you would have a linux-amd64 client talking to a linux-arm64 server, maybe similar issues ?

**Comment by bl-ue** [comment]
So I tried it again, here's the output:
```
$ rm /usr/local/bin/kubectl
$ ln -s /usr/local/bin/minikube /usr/local/bin/kubectl
$ readlink /usr/local/bin/kubectl
/usr/local/bin/minikube
$ /usr/local/bin/minikube start --vm=true --kubernetes-version='v1.20.4'
😄  minikube v1.18.0 on Darwin 11.2.2
✨  Automatically selected the hyperkit driver. Other choices: vmware, ssh
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.4 on Docker 20.10.3 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v4
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
E0304 10:14:53.683681   84151 start.go:270] kubectl info: exec: exit status 2
$
```
I was doing some experimenting a few months ago but I didn't come to the slightest conclusion other than the symlinking is causing an issue, because `kubectl` being it's own binary works fine without this error.

**Comment by prezha** [comment]
@bl-ue thank you for your reply

i'm still a bit confused why are you linking kubectl to minikube - the error seems to root to then when, at the end (as shown in your logs), calling effectively `minikube` with `version --client --output=json` params, which are for kubectl and would not work for minikube:

https://github.com/kubernetes/minikube/blob/18e215fed113d3ad1bc1797860e303cae0772373/cmd/minikube/cmd/start.go#L269-L271

->

https://github.com/kubernetes/minikube/blob/18e215fed113d3ad1bc1797860e303cae0772373/cmd/minikube/cmd/start.go#L448-L451

->

https://github.com/kubernetes/minikube/blob/18e215fed113d3ad1bc1797860e303cae0772373/cmd/minikube/cmd/start.go#L520-L526

why do you link them?

**Comment by bl-ue** [comment]
>why do you link them?

@prezha I'm linking them per here: https://minikube.sigs.k8s.io/docs/handbook/kubectl/

Quoting:
>Alternatively, you can create a symbolic link to minikube’s binary named ‘kubectl’.
>
>```bash
>ln -s $(which minikube) /usr/local/bin/kubectl
>```

---

>can you please try w/o linking and see if you still have the issue

I don't have the issue when kubectl is an actual binary.

**Comment by prezha** [comment]
thanks for confirming, that's great, and also for referencing where the linking part comes from :)

there, if you don't have (or don't want to download) kubectl, `alias kubectl="minikube kubectl --"` would work just fine, but tbh, i'm not sure what was the idea in the handbook with linking it

**Comment by bl-ue** [comment]
Sure.  I'll just use the binary.  But I don't think this was happening before k8s 1.20. 🤔

**Comment by prezha** [comment]
great

you can also use the alias, that should work too
this specific code was introduced about a year ago
now, with the link, if you specify any minikube-acceptable command/flag (like `--kubernetes-version='v1.19.0'`) - it _will_ work, but i don't expect it to work with any command/flag specific to kubectl (eg, `get nodes -A`)

if you don't mind we can close this issue now and check separately about the advice given in the handbook

**Comment by bl-ue** [comment]
No, I don't mind at all.  Thank you for your help @prezha! ❤️ 

It's a little odd that it started with k8s v1.20, but...:shrug:
