### ISSUE TITLE
Separate container runtimes from the image

### ISSUE THREAD

**Issue by afbjorklund** [kubernetes/minikube#9989]
Currently we include all **three** CRI runtimes, in the base image:
* Docker (docker)
* CRI-O (crio + podman)
* Containerd (containerd + buildkit)

This makes the image somewhat big, compared to having just one.

### ISO
![graph-size](https://user-images.githubusercontent.com/10364051/102545530-a916c780-40b6-11eb-984e-423427c8db3d.png)

### KIC
![installed-size](https://user-images.githubusercontent.com/10364051/103348940-c4f97080-4a9b-11eb-96ff-a034adbd55d6.png)

We only _start_ one of them, but the others still takes up space on the disk.

(actually we _always_ start docker, as long as using the "docker machine" API...
but we stop it again quickly afterwards, if using the containerd or cri-o runtimes)

----

One alternative to doing three "base" images, would be to use the "provisioner".
This is a docker-machine feature, that is used to install docker on the machine.

https://github.com/docker/machine/tree/master/libmachine/provision

So the base image wouldn't have _any_ of them (maybe `runc`) from the start.
Instead they would be downloaded and installed from separate tarballs/packages.

This is how we currently handle different kubernetes versions, for instance.

* linux/v1.20.0/kubeadm
* linux/v1.20.0/kubectl
* linux/v1.20.0/kubelet

It's also how we handle the preload, instead of making three "node" images:

* preloaded-images-k8s-v8-v1.20.0-containerd-overlay2-amd64.tar.lz4
* preloaded-images-k8s-v8-v1.20.0-cri-o-overlay-amd64.tar.lz4
* preloaded-images-k8s-v8-v1.20.0-docker-overlay2-amd64.tar.lz4

As compared with kind:

* `docker.io/kindest/node:v1.20.0` (always uses containerd-overlay2)

**Comment by afbjorklund** [comment]
We would need an installation script for CRI-O, similar to [get.docker.com](https://get.docker.com) for Docker...

`if ! type docker; then curl -sSL https://get.docker.com | sh -; fi`

See https://github.com/cri-o/cri-o/issues/4343

We also need one for containerd (and buildkit), but maybe we can do it ourselves ?

**Comment by afbjorklund** [comment]
For containerd, it will probably use the binaries from the github releases:

https://github.com/containerd/containerd/releases/download/v1.4.3/containerd-1.4.3-linux-amd64.tar.gz

https://github.com/moby/buildkit/releases/download/v0.8.1/buildkit-v0.8.1.linux-amd64.tar.gz

But only for `amd64`.

**Comment by afbjorklund** [comment]
This includes switching from github.com/docker/machine/libmachine/provision to k8s.io/minikube/pkg/provision

This always installs docker, by calling the configured get.docker.com script version (InstallURL):

https://github.com/docker/machine/blob/7d42fed1b770/libmachine/provision/ubuntu_systemd.go#L99

This currently doesn't provision anything, but assume that everything is in the "base" image:

https://github.com/kubernetes/minikube/blob/v1.16.0/pkg/provision/ubuntu.go#L164

The forked provisioner (in minikube), will need to make sure that runtime is getting installed (from a package).

**Comment by afbjorklund** [comment]
Note that Buildroot doesn't have any package manager (like dpkg), _by design_:
https://buildroot.org/downloads/manual/manual.html#faq-no-binary-packages

The easiest workaround is probably doing something like the preloaded images.
That is, make a _separate_ buildroot build - that creates binary archives (tarballs) ?

```
docker-bin
cri-docker

crio-bin
conmon
podman

containerd-bin
buildkit-bin
```

```
# common
runc-master
crictl-bin
cni
cni-plugins
```

Then these tarballs need to be hosted somewhere, again like the preloaded images...

Most likely the same goes for the packages, should they "disappear" upstream: #9552

**Comment by afbjorklund** [comment]
Here are the matching sections, that would be removed from the kicbase:

    clean-install docker-ce docker-ce-cli containerd.io
    echo "Installing buildkit ...

    clean-install libglib2.0-0
    clean-install containers-common catatonit conmon containernetworking-plugins cri-tools podman-plugins
    clean-install cri-o cri-o-runc
    clean-install podman

Note that docker and containerd are _sharing_ the containerd and runc here.

```
The following additional packages will be installed:
  apparmor containers-golang containers-image crun docker-ce-rootless-extras file git git-man less libcurl3-gnutls liberror-perl libexpat1 libgdbm-compat4 libgdbm6 libglib2.0-data libgpgme11 libltdl7
  libmagic-mgc libmagic1 libmpdec2 libperl5.30 libpython3-stdlib libpython3.8-minimal libpython3.8-stdlib libyajl2 mime-support patch perl perl-modules-5.30 python3 python3-minimal python3.8
  python3.8-minimal shared-mime-info slirp4netns uidmap varlink xdg-user-dirs xz-utils
Suggested packages:
  apparmor-profiles-extra apparmor-utils aufs-tools cgroupfs-mount | cgroup-lite gettext-base git-daemon-run | git-daemon-sysvinit git-doc git-el git-email git-gui gitk gitweb git-cvs git-mediawiki
  git-svn gdbm-l10n ed diffutils-doc perl-doc libterm-readline-gnu-perl | libterm-readline-perl-perl make libb-debug-perl liblocale-codes-perl python3-doc python3-tk python3-venv python3.8-venv
  python3.8-doc binutils binfmt-support
The following NEW packages will be installed:
  apparmor buildkit catatonit conmon containerd.io containernetworking-plugins containers-common containers-golang containers-image cri-o cri-o-runc cri-tools crun docker-ce docker-ce-cli
  docker-ce-rootless-extras file git git-man less libcurl3-gnutls liberror-perl libexpat1 libgdbm-compat4 libgdbm6 libglib2.0-0 libglib2.0-data libgpgme11 libltdl7 libmagic-mgc libmagic1 libmpdec2
  libperl5.30 libpython3-stdlib libpython3.8-minimal libpython3.8-stdlib libyajl2 mime-support patch perl perl-modules-5.30 podman podman-plugins python3 python3-minimal python3.8 python3.8-minimal
  shared-mime-info slirp4netns uidmap varlink xdg-user-dirs xz-utils
0 upgraded, 53 newly installed, 0 to remove and 2 not upgraded.
Need to get 192 MB of archives.
After this operation, 892 MB of additional disk space will be used.
```

**Comment by sharifelgamal** [comment]
@azhao155 are you interested in looking at this?

**Comment by medyagh** [comment]
I think we might not to do this, as it would add a lot of CI complexiites in building and pushing

**Comment by afbjorklund** [comment]
The complexity is already there, since upstreams have issues providing consistent packaging

Installing Docker is easy, but adding cri-o or cri-dockerd or containerd is a pain to maintain...

**Comment by afbjorklund** [comment]
This feature will not make it to the ISO and KIC targets, in time for the 1.26 release

**Comment by medyagh** [comment]
while this is still a good idea, I dont see enough bandiwith to handle the infrastructure part of this task
