### ISSUE TITLE
Minkube fails on readiness prob: getsockopt: connection refused

### ISSUE THREAD

**Issue by anoopl** [kubernetes/minikube#999]
**BUG REPORT:

**Minikube version** 
minikube version: v0.15.0

Testing a readiness probe that works on prod Kubernetes cluster but it fails on minikube

Error:
Readiness probe failed: Get http://172.17.0.4:8080/: dial tcp 172.17.0.4:8080: getsockopt: connection refused

Is this a bug? Can anyone please help me on this. I tried this on Xhyve and Virtulabox drivers

Kube config:
server: https://192.168.99.100:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube

**Environment**:
- **OS** (e.g. from /etc/os-release):
OS: OSX 10.11.6
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
xhyve and virtualbox
- **Docker version** (e.g. `docker -v`):
Docker version 1.12.6, build 78d1802
 OS/Arch:      linux/amd64

**Comment by joshfg** [comment]
Hi @anoopl, I am having a very similar problem. Did you figure out what was going on here?

**Comment by joshfg** [comment]
Hi @anoopl, I am having a very similar problem (probe works on prod Kubernetes cluster but not on Minikube). Did you figure out what was going on here?

**Comment by anoopl** [comment]
@joshfg I could not test this on Minikube and had to use our dev cluster for this testing. So I did not dig much on this

**Comment by joshfg** [comment]
Ah right, ok! I will keep looking into this then...

**Comment by r2d4** [comment]
Without more information its hard to debug, but if you're trying to point directly at  http://172.17.0.4:8080/, that won't work.  You can see from the kubeconfig that the apiserver is configured at https://192.168.99.100:8443

**Comment by joshfg** [comment]
Hi Matt, I'm just using a standard readinessProbe config like this:

readinessProbe:
  httpGet:
    path: /healthcheck
    port: 8080

Kubernetes/Minikube is trying to point at the container IP address
(http://172.17.0.4:8080/) and failing to connect. However this exact
same Kubernetes config works in a production Kubernetes cluster. Is
there any other info I should look at to dig into this? Thanks!

**Comment by Jokero** [comment]
Also faced with this problem. After increasing memory for minikube VM, errors disappeared:
```
minikube start --cpus 2 --memory 4096 // default memory value is 2048
```
