### ISSUE TITLE
minikube_1.16.0-0_amd64.deb: package architecture (arm64) does not match system (amd64)

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [kubernetes/minikube#9995]
**Steps to reproduce the issue:** 

1. Download amd64 debian package of latest release: https://github.com/kubernetes/minikube/releases/download/v1.16.0/minikube_1.16.0-0_amd64.deb
2. Inspect the package file
3. It's marked as an arm64 package not an amd64 package
4. It has stray files in it that are clearly not meant to be there

**Full output of failed command:** 
```
$ dpkg --info minikube_1.16.0-0_amd64.deb ; dpkg --contents minikube_1.16.0-0_amd64.deb 
 new Debian package, version 2.0.
 size 20578594 bytes: control archive=389 bytes.
     381 bytes,    11 lines      control              
 Package: minikube
 Version: 1.16.0
 Section: base
 Priority: optional
 Architecture: arm64
 Maintainer: Thomas Strömberg <t+minikube@stromberg.org>
 Description: Minikube
  minikube is a tool that makes it easy to run Kubernetes locally.
  minikube runs a single-node Kubernetes cluster inside a VM on your
  laptop for users looking to try out Kubernetes or develop with it 
  day-to-day.
drwxr-xr-x root/root         0 2020-12-17 18:41 ./
drwxr-xr-x root/root         0 2020-12-17 18:41 ./minikube_deb_template/
drwxr-xr-x root/root         0 2020-12-17 18:41 ./minikube_deb_template/DEBIAN/
-rw-r--r-- root/root       416 2020-12-17 18:41 ./minikube_deb_template/DEBIAN/control
drwxr-xr-x root/root         0 2020-12-17 18:41 ./usr/
drwxr-xr-x root/root         0 2020-12-17 18:41 ./usr/bin/
-rwxr-xr-x root/root  57925077 2020-12-17 18:41 ./usr/bin/minikube
```

Note: `Architecture: arm64` and `./minikube_deb_template/...` in the contents.

However the actual binary contained within _is_ an amd64 one:
```
# extract the contents of the package
$ file minikube
minikube: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=6LZF01FcZrGBprW2lwYI/gWzE5fRYw4NT_meHguiF/54zHaIwKVnjc2RZCfg6t/T0VXjXYTfvHZFrWQslv4, not stripped
```

**Comment by KernelErr** [comment]
Seems that both releases from Google Storage and GitHub have the same problem.

**Comment by Jorropo** [comment]
Same problem here, the `.deb` package in the [github releases](https://github.com/kubernetes/minikube/releases) are wrong also, but it is different from the arm64 (size is a bit bigger).

**Comment by Jorropo** [comment]
This is only an error in the manifest. With :
```sh
sudo dpkg -i --force-architecture minikube_1.16.0-0_amd64.deb
```
This works fine.

**Comment by tstromberg** [comment]
Thanks for the update. I believe this was our first major release publishing arm64/amd64 debs, and it looks like we got it a bit wrong. I'm no .deb expert, so if anyone is interested in helping us to  fix our .deb file, it's defined here:

https://github.com/kubernetes/minikube/blob/5f6fef80c7597e346392acbbf8d051ebccdc6895/Makefile#L469

**Comment by tstromberg** [comment]
I strongly suspect that v1.16.0-beta.0 was also impacted, although we haven't yet seen reports confirming it.

**Comment by Jorropo** [comment]
> I strongly suspect that v1.16.0-beta.0 was also impacted, although we haven't yet seen reports confirming it.

ok weird, running :
```sh
make out/minikube_1.16.0-0_amd64.deb
```
Works like a charm.
I guess the bug is else where.

**Comment by tstromberg** [comment]
I wonder if it's due to running both commands in the same directory?

**Comment by Jorropo** [comment]
> I wonder if it's due to running both commands in the same directory?

You are right, there is a race condition where they both create their temporary dir at `out/minikube_1.16.0/`.

**Comment by afbjorklund** [comment]
Probably also need some minimal regression tests, when doing the release.

**Comment by Jorropo** [comment]
I have a fix, I'm pushing a pr.

**Comment by afbjorklund** [comment]
The good news is that the arm64.deb looks fine :-)

Also the rpm files got "lucky", in the make race.

**Comment by tstromberg** [comment]
The root cause remains unfixed -- but I will push up a new .deb file this morning for this release.

**Comment by tstromberg** [comment]
Build:

```
git checkout tags/v1.16.0
 curl -L https://github.com/kubernetes/minikube/releases/download/v1.16.0/minikube-linux-amd64 > out/minikube 
make -e DEB_VERSION=1.16.0 -e DEB_REVISION=1 out/minikube_1.16.0-1_amd64.deb
```

Propagate:

```
gsutil cp out/minikube_1.16.0-1_amd64.deb gs://minikube/releases/latest
gsutil cp out/minikube_1.16.0-1_amd64.deb gs://minikube/releases/latest/minikube_latest_amd64.deb 
gsutil cp out/minikube_1.16.0-1_amd64.deb gs://minikube/releases/v1.16.0/
```

Then uploaded manually to GitHub releases:

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_1.16.0-1_amd64.deb
<drag file to GitHub release>
```

**Comment by tstromberg** [comment]
The broken `minikube_1.16.0-0_amd64.deb` package from GitHub and GCS to avoid confusion.

The updated one has a new revision and filename of `minikube_1.16.0-1_amd64.deb`

My apologies for the inconvenience. We'll leave this issue open until the Makefile can be updated so that this build corruption issue cannot occur again.

**Comment by afbjorklund** [comment]
It looks like the actual binaries were all correct, so the issue was with the packaging

**Comment by mgabeler-lee-6rs** [comment]
Was able to download & install the fixed release and restart my local minikube environment with the new version. Thanks! :+1:

**Comment by bl-ue** [comment]
@mgabeler-lee-6rs You should re-open this:

quoting @tstromberg https://github.com/kubernetes/minikube/issues/9995#issuecomment-748182803:
> We'll leave this issue open until the Makefile can be updated so that this build corruption issue cannot occur again.

**Comment by mgabeler-lee-6rs** [comment]
Oops, missed that, sorry!

**Comment by bl-ue** [comment]
This already has two PRs #9998 and #10004 linked
/remove-good-first-issue
